### PR TITLE
New version: Bruno.Bruno version 1.35.0

### PR DESCRIPTION
**Pull request by rodrigoborgesdeoliveira**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/192930)

### CODE REVIEW

**Comment by Trenly** [comment]
```
Found Bruno [Bruno.Bruno] Version 1.35.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/usebruno/bruno/releases/download/v1.35.0/bruno_1.35.0_x64_win.exe
  ██████████████████████████████  90.9 MB / 90.9 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 3221225477
```

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
@stephengillie - Why did you remove the label?

**Comment by stephengillie** [comment]
I didn't thoroughly read the PR comments, and mistook this for a PR that needed a manual merge, based on the labels.

**Comment by rodrigoborgesdeoliveira** [comment]
@Trenly, I've run `winget validate` and `winget install` on both Windows 11 Arm and Windows 10 64 bits and the installation was successful on both.

**Comment by stephengillie** [comment]
I also wasn't able to reproduce the error. Verify:
image
image

**Comment by stephengillie** [comment]
Hi @Trenly,

> ```
> Found Bruno [Bruno.Bruno] Version 1.35.0
> This application is licensed to you by its owner.
> Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
> Downloading https://github.com/usebruno/bruno/releases/download/v1.35.0/bruno_1.35.0_x64_win.exe
>   ██████████████████████████████  90.9 MB / 90.9 MB
> Successfully verified installer hash
> Starting package install...
> Installer failed with exit code: 3221225477
> ```

Do you have the package manager logs from this run? We're having difficulty reproducing the error.

**Comment by Trenly** [comment]
> Hi @Trenly,
> 
> > ```
> > Found Bruno [Bruno.Bruno] Version 1.35.0
> > This application is licensed to you by its owner.
> > Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
> > Downloading https://github.com/usebruno/bruno/releases/download/v1.35.0/bruno_1.35.0_x64_win.exe
> >   ██████████████████████████████  90.9 MB / 90.9 MB
> > Successfully verified installer hash
> > Starting package install...
> > Installer failed with exit code: 3221225477
> > ```
> 
> Do you have the package manager logs from this run? We're having difficulty reproducing the error.

Will try and reproduce

**Comment by Trenly** [comment]
@stephengillie - Here are the package manager logs; The installer itself did not create any logs
[WinGet-2024-12-06-13-20-53.823.log](https://github.com/user-attachments/files/18042800/WinGet-2024-12-06-13-20-53.823.log)

**Comment by Trenly** [comment]
Okay, this is weird; I ran the test five more times, and it succeeded four of the five times. No idea why. Either way, it seems safe enough to say that this package does work as intended

[Policy] Reset Feedback

**Review by Trenly — APPROVED** [review]

**Comment by stephengillie** [comment]
> @stephengillie - Here are the package manager logs; The installer itself did not create any logs [WinGet-2024-12-06-13-20-53.823.log](https://github.com/user-attachments/files/18042800/WinGet-2024-12-06-13-20-53.823.log)
> 
> However, if I run this command after the failure, then it installs and runs just fine - so this is not an issue with the computer or environment supporting the installer
> 
> ```
> start C:\Users\WDAGUtilityAccount\AppData\Local\Temp\WinGet\Bruno.Bruno.1.35.0\bruno_1.35.0_x64_win.exe
> ```

Thanks for the logs, and for testing several times. The inconsistent nature of the error is noteworthy. I found: 

> 2024-12-06 13:21:10.835 [CLI ] ShellExecute installer failed: 3221225477

Exit code `3221225477` might correspond to: 
> Converted to hexadecimal (C0000005) possibly [Access Violation](https://learn.microsoft.com/en-us/shows/inside/access-violation-c0000005-execute). (This is occasionally seen in PRs despite the install otherwise being successful. Should it be added as an `InstallerSuccessCode` or similar here?)

**Pull request merged**
