### PR TITLE
TechSmith.Camtasia.2021/2022 Subfolder for year version

### PR DESCRIPTION
**Pull request by Tawanski**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/102327)

### CODE REVIEW

**Comment by Tawanski** [comment]
Want this change since it makes it easier to not jump year versions so it wont create licensing problems for those that use the program.

**Comment by BrandonWanHuanSheng** [comment]
I think this pull request can only modified 1 manifests at a time.

**Comment by stephengillie** [comment]
> I think this pull request can only modified 1 manifests at a time.

Yes. Automatic Validation failed with:
>  The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.

**Comment by BrandonWanHuanSheng** [comment]
It look like you keep more changing. The file changed must be max=3

**Comment by Tawanski** [comment]
I forgot to remove change the one in that was in the one folder back to what it was before, so I am now changing only 2022 and keeping one path, if that wont work, then I will change one by one and if that is nessecery, when I have time

**Pull request closed without merging**
