### PR TITLE
New version: Mozilla.Firefox version 122.0

### LINKED ISSUE #135907: [Update Request]: Mozilla.Firefox 122.0.0
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Mozilla.Firefox

### Package Version

122.0.0

### Please describe the changes you would like to see

_No response_

### PR DESCRIPTION
**Pull request by krystofkrticka**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`? image
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Resolves: #135907

### CODE REVIEW

**Comment by Exorcism0666** [comment]
- Resolve: #135907

**Comment by stephengillie** [comment]
Hi @krystofkrticka,

> This PR's version number 122.0 has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 121.0.1, which has 3 parameters.

Is this intentional?

(Automated response - build 661)

**Comment by stephengillie** [comment]
Hi @krystofkrticka,

> This PR's version number "122.0" has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 121.0.1, which has 3 parameters.

Is this intentional?

(Automated response - build 661)

**Comment by krystofkrticka** [comment]
@stephengillie thank you for your message I'll look into this once I'm at my computer.

**Comment by krystofkrticka** [comment]
@stephengillie I just kept version number same as previous version number similar as was for previous version which is that version 121.0 had in manifest 121.0 and version 121.0.1 had in manifest 121.0.1 so unless something changed in manifest schema it is intentional.

**Comment by stephengillie** [comment]
I'll add it to my list of exceptions for this check.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
