### PR TITLE
Normalize Kiwix.WikiMed 2.0.4.0

### PR DESCRIPTION
**Pull request by Trenly**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/75891)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
I think this needs an engineer -
```
2022-08-31 10:23:47.034 [FAIL] WindowsPackageManager.dll!00007FFD4B405E12: ReturnHr(1) tid(22b4) 80072EFF     Msg:[winrt::hresult_error: The text associated with this error code could not be found.] 
```

**Comment by Trenly** [comment]
cc @denelon

**Comment by Madhusudhan-MSFT** [comment]
Per log there is an exception WindowsPackageManager.dll - resulting  WININET_E_CONNECTION_RESET. 

2022-08-31 10:23:47.057 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\MsixInfo.cpp(311)\WindowsPackageManager.dll!00007FFD4B296FB7: (caller: 00007FFD4B23E5C0) Exception(1) tid(22b4) 80072EFF 
2022-08-31 10:23:47.057 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\MsixInfo.cpp(311)\WindowsPackageManager.dll!00007FFD4B296FB7: (caller: 00007FFD4B23E5C0) Exception(1) tid(22b4) 80072EFF 

Not sure, if this InstallerType: appx is somehow conflicting with the client code.

**Comment by denelon** [comment]
```text
****************************************************************************************
Manifest Validation
****************************************************************************************
Status: Completed
##[error] Result: Failed
##[error] One or more errors occurred. (Manifest Error: Failed to process installer. Field: InstallerUrl Value: https://github.com/kiwix/kiwix-js-windows/releases/download/v2.0.4-WikiMed/KiwixWebAppWikiMed_2.0.4.0_AnyCPU.appxbundle
) Manifest Error: Failed to process installer. Field: InstallerUrl Value: https://github.com/kiwix/kiwix-js-windows/releases/download/v2.0.4-WikiMed/KiwixWebAppWikiMed_2.0.4.0_AnyCPU.appxbundle
Finishing: Validate Manifest
```
https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=368823&view=logs&j=1c216ba8-f9ef-5707-496b-69e30b6cb45a&t=d5938111-0e28-5713-0070-4b1bb7df6b82&l=64

**Comment by Trenly** [comment]
> ```
> ****************************************************************************************
> Manifest Validation
> ****************************************************************************************
> Status: Completed
> ##[error] Result: Failed
> ##[error] One or more errors occurred. (Manifest Error: Failed to process installer. Field: InstallerUrl Value: https://github.com/kiwix/kiwix-js-windows/releases/download/v2.0.4-WikiMed/KiwixWebAppWikiMed_2.0.4.0_AnyCPU.appxbundle[](https://github.com/kiwix/kiwix-js-windows/releases/download/v2.0.4-WikiMed/KiwixWebAppWikiMed_2.0.4.0_AnyCPU.appxbundle)
> ) Manifest Error: Failed to process installer. Field: InstallerUrl Value: https://github.com/kiwix/kiwix-js-windows/releases/download/v2.0.4-WikiMed/KiwixWebAppWikiMed_2.0.4.0_AnyCPU.appxbundle[](https://github.com/kiwix/kiwix-js-windows/releases/download/v2.0.4-WikiMed/KiwixWebAppWikiMed_2.0.4.0_AnyCPU.appxbundle)
> Finishing: Validate Manifest
> ```
> 
> [dev.azure.com/ms/winget-pkgs/_build/results?buildId=368823&view=logs&j=1c216ba8-f9ef-5707-496b-69e30b6cb45a&t=d5938111-0e28-5713-0070-4b1bb7df6b82&l=64](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=368823&view=logs&j=1c216ba8-f9ef-5707-496b-69e30b6cb45a&t=d5938111-0e28-5713-0070-4b1bb7df6b82&l=64)

As helpful as that error is. . . it really isn't. The installer URL's work for me, and other versions of WikiMed have passed validation. Is there anything saying why it couldn't be processed?

**Comment by denelon** [comment]
I've assigned this to our current "on-call" to look and see what is failing so we can figure out what needs to be fixed in validation, or how we might provide a better message.

**Comment by Trenly** [comment]
> I've assigned this to our current "on-call" to look and see what is failing so we can figure out what needs to be fixed in validation, or how we might provide a better message.

Bumping this thread so it doesn't get marked No-Recent-Activity

**Comment by AmelBawa-msft** [comment]
> Manifest Error: Failed to process installer. Field: InstallerUrl Value: ...

@Trenly; @denelon , for this (and few other) PRs with the same error message above, the issue is occurring because the attempt to get the MSIX information directly from the installer URL is failing unexpectedly during the validation. This bug (tracked internally) needs to be fixed in the client code by potentially downloading the installer to the validation pipeline agent, and then attempting to get the MSIX info, instead of streaming them directly from the installer URL.

**Comment by denelon** [comment]
@AmelBawa-msft can you create an Issue in the repository to track the change? That way we can link the PRs to the issue, and the community will know when we have the fix in place so these can be unblocked.

**Comment by Trenly** [comment]
Thanks for the detailed explanation! That makes a lot of sense

**Review by jedieaston — APPROVED** [review]

**Review by jedieaston — APPROVED** [review]

**Comment by denelon** [comment]
We're actively working on the fix here. Once the fix has been implemented and released to our production environment, we will trigger the build again to see if this will get merged.

**Pull request merged**
