### PR TITLE
Adds Surfshark: Surfshark.Surfshark version 4.5.0

### PR DESCRIPTION
**Pull request by AnthonySibl**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)? Yes
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change? Yes
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? Yes
- [x] Have you tested your manifest locally with `winget install --manifest <path>`? Yes
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)? Yes

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/89802)

### CODE REVIEW

**Comment by AnthonySibl** [comment]
@microsoft-github-policy-service agree

**Comment by AnthonySibl** [comment]
Accidentally pushed another update for Brave without being in a separate branch so the bot saw the change and attempted to check it before I deleted it out of master. Please proceed without the new Brave.Brave version as I will make a separate pull request.

**Comment by russellbanks** [comment]
@OfficialEsco, is this okay to proceed with (I haven't checked values in a Sandbox yet) if the pipelines are passing? I know the url was forbidden in the past (https://github.com/microsoft/winget-pkgs/issues/35134#issuecomment-996103500, https://github.com/microsoft/winget-pkgs/pull/37761).

**Comment by OfficialEsco** [comment]
Since the hash is the same it should in theory be the same version, but i'm also pretty sure when we accept this PR it will be blocked again because the bot will try to download it everyday to check the hash...

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
