### PR TITLE
Add NationalSecurityAgency.Ghidra 10.3.3

### PR DESCRIPTION
**Pull request by chausner**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/119124)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Exception during executable launch operation System.AggregateException: One or more errors occurred. (The specified executable is not a valid application for this OS platform.)  ---
> System.ComponentModel.Win32Exception (216): The specified executable is not a valid application for this OS platform. 
--- End of stack trace from previous location where exception was thrown ---    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

**Comment by chausner** [comment]
> Automatic Validation ended with:
> 
> > Exception during executable launch operation System.AggregateException: One or more errors occurred. (The specified executable is not a valid application for this OS platform.)  ---
> > System.ComponentModel.Win32Exception (216): The specified executable is not a valid application for this OS platform.
> > --- End of stack trace from previous location where exception was thrown ---    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

I think this is because the command is not an executable but a batch file (`ghidra_10.3.3_PUBLIC\ghidraRun.bat`) which invokes the Java runtime. The application is a Java application so there is no Win32 executable.

**Comment by stephengillie** [comment]
> > Automatic Validation ended with:
> > > Exception during executable launch operation System.AggregateException: One or more errors occurred. (The specified executable is not a valid application for this OS platform.)  ---
> > > System.ComponentModel.Win32Exception (216): The specified executable is not a valid application for this OS platform.
> > > --- End of stack trace from previous location where exception was thrown ---    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
> 
> I think this is because the command is not an executable but a batch file (`ghidra_10.3.3_PUBLIC\ghidraRun.bat`) which invokes the Java runtime. The application is a Java application so there is no Win32 executable.
> 
> Is there a way to still make this work? When I install it locally, the ghidra command works as expected.

Yes - I think maybe we weren't supposed to add this package with the BAT file, but previous versions are in the public manifests, and this works in a Windows 10 VM,. So it gets a waiver, to keep PRs flowing.

**Comment by denelon** [comment]
Batch files aren't a supported type.

**Pull request closed without merging**
