### PR TITLE
New package: RCook.Isopy version 0.0.11

### PR DESCRIPTION
**Pull request by rcook**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/102037)

### CODE REVIEW

**Comment by rcook** [comment]
@microsoft-github-policy-service agree

**Comment by BrandonWanHuanSheng** [comment]
Why that file don't have data? https://github.com/microsoft/winget-pkgs/blob/3aca69e76551cdc65d467fa9b76e2b6831507bf3/manifests/r/RCook/Isopy/0.0.11/RCook.Isopy.locale.en-US.yaml

**Comment by BrandonWanHuanSheng** [comment]
Windows Defender Smart Screen detected that file as a malware

**Comment by rcook** [comment]
It's a false positive, but I'll close this PR until I can figure this out. I may need to code-sign the binary.

**Pull request closed without merging**
