### PR TITLE
New version: Microsoft.PowerBI version 2.118.1063.0

### LINKED ISSUE #111467: [Package Issue]: Microsoft.PowerBI
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Installer hash does not match

### Steps to reproduce

winget install Microsoft.PowerBI

### Actual behavior

Found Microsoft PowerBI Desktop [Microsoft.PowerBI] Version 2.118.828.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup_x64.exe
  ██████████████████████████████   478 MB /  478 MB
Installer hash does not match; this cannot be overridden when running as admin

### Expected behavior

Installs

### Environment

```raw
Windows Package Manager v1.4.11071
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.1972
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.11071.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

Links               
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

_No response_

### PR DESCRIPTION
**Pull request by krystofkrticka**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`? image
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

* Resolves #111467

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/111470&drop=dogfoodAlpha

### CODE REVIEW

**Comment by krystofkrticka** [comment]
Just checked the hash again using `certutil -hashfile "PBIDesktopSetup_x64.exe" SHA256` command and it's same hash as is in manifest.

**Comment by Trenly** [comment]
Power BI CDN's always take several days to push the changes across all regions

**Comment by krystofkrticka** [comment]
Well know I know that it is caused by CDN which I thought is the culprit here.

**Comment by stephengillie** [comment]
> Power BI CDN's always take several days to push the changes across all regions

This implies one solution is to periodically retry.

**Comment by BrandonWanHuanSheng** [comment]
Does any application can cross-tool for checking the hashes without require downloading?

**Comment by BrandonWanHuanSheng** [comment]
> Just checked the hash again using `certutil -hashfile "PBIDesktopSetup_x64.exe" SHA256` command and it's same hash as is in manifest.

Are you using a file? That file hashes could be incorrect.

**Comment by mdanish-kh** [comment]
🙃

**Comment by BrandonWanHuanSheng** [comment]
I also noticed this thing also. Which is 
[The PR validation have some issue after adding the waiver label](https://github.com/microsoft/winget-pkgs/issues/111634)

**Comment by mdanish-kh** [comment]
Yes, the pipelines have been quite unstable past few days; The team is probably aware of it

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
