### PR TITLE
VMware.WorkstationPro: Update AppsAndFeaturesEntries.InstallerType to msi

### PR DESCRIPTION
**Pull request by StarsbySea**
The installer is an exe, but after installation it shows msi in the programs and features. This modification allows the software to be upgraded properly from the old version to the new one

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/109193&drop=dogfoodAlpha

### CODE REVIEW

**Comment by StarsbySea** [comment]
Don't know why, works fine in my local environment

**Comment by stephengillie** [comment]
Automatic Validation didn't produce logs.

**Comment by stephengillie** [comment]
> Don't know why, works fine in my local environment

Manual Validation also completed normally:
image

This might just be a transient Automated Pipeline issue.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
