### PR TITLE
New version: Rem0o.FanControl version 189

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#4974](https://github.com/SpecterShell/Dumplings/actions/runs/9004135393).

**Logs**
````
Updated: 188 → 189
Submitting WinGet manifests
````
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/152674)

### CODE REVIEW

**Comment by Trenly** [comment]
> 2024-05-08 08:25:43.450 [FAIL] Installer failed security check. Url: https://github.com/Rem0o/FanControl.Releases/releases/download/V189/FanControl_189_net_8_0_Installer.exe Result: 0x80004005

Will rerun this PR later

**Comment by stephengillie** [comment]
Hi @SpecterShell,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 880.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-08 08:24:40.374 [REPO] Failed to open available source: msstore
> 2024-05-08 08:24:48.205 [REPO] Failed to open available source: msstore
> 2024-05-08 08:25:43.450 [FAIL] Installer failed security check. Url: https://github.com/Rem0o/FanControl.Releases/releases/download/V189/FanControl_189_net_8_0_Installer.exe Result: 0x80004005
> MSI (s) (54:28) [08:25:02:358]: Executing op: ComponentRegister(ComponentId={A2D34B62-88A4-5E6A-AABB-080F66078364},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.4\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1)
> MSI (s) (54:28) [08:25:03:935]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,)
> Property(S): ErrorDialog = ErrorDlg

(Automated response - build 880.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
