### PR TITLE
Add Minecraft Launcher

### PR DESCRIPTION
**Pull request by superusercode**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/405)

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Validation has completed

**Comment by jamierocks** [comment]
This is going to fail in the same way as https://github.com/microsoft/winget-pkgs/issues/659, as the link doesn't point to a specific version.

**Comment by superusercode** [comment]
Is it possible to blank the checksum out like chocolatey does? https://chocolatey.org/packages/minecraft/1.9#files

**Comment by superusercode** [comment]
additionally, I thought the minecraft installer was just a stub that installs another stub for the minecraft launcher and then installs minecraft.

**Pull request merged**
