### PR TITLE
New App: tummychow.git-absorb

### LINKED ISSUE #103855: [Package Request]: git-absorb
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/tummychow/git-absorb/releases
Publisher: tummychow
Package Name: git-absorb
Description: [Absorb extension for git](https://andrewlock.net/super-charging-git-rebase-with-git-absorb/).
Package Version: 0.6.10
Installer URL: https://github.com/tummychow/git-absorb/releases/download/0.6.10/git-absorb-0.6.10-x86_64-pc-windows-msvc.zip

### PR DESCRIPTION
**Pull request by BrandonWanHuanSheng**
Adding New Portable Application. Resolves #103855 

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/103876)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
This one is being taken to manual reviews.

**Comment by BrandonWanHuanSheng** [comment]
@stephengillie I failed out from the Automatic Validation.

**Review by ItzLevvie — APPROVED** [review]
https://github.com/microsoft/winget-pkgs/labels/Validation-Executable-Error is because the `git-absorb` command returns `%ERRORLEVEL% = 1` if it's not being ran inside of a repository folder:
```
Apr 30 15:39:57.871 CRIT absorb failed, err: could not find repository from '.'; class=Repository (6); code=NotFound (-3)
```

Which means that running the `git-absorb` command in `C:\Users\%USERNAME%\Documents\GitHub\winget-pkgs` passes with `%ERRORLEVEL% = 0`:
```
PS C:\Users\TAP\Documents\GitHub\winget-pkgs> git-absorb
Apr 30 15:42:09.041 WARN Will not fix up past commits not authored by you, use --force to override, commit: cccdd4f1db400afd2658a863dc1cd8fcfb21b772
Apr 30 15:42:09.048 CRIT No commits available to fix up, exiting
PS C:\Users\TAP\Documents\GitHub\winget-pkgs> $LASTEXITCODE
0
```

**Comment by BrandonWanHuanSheng** [comment]
> [ Validation-Executable-Error](https://github.com/microsoft/winget-pkgs/labels/Validation-Executable-Error) is because the `git-absorb` command returns `%ERRORLEVEL% = 1` if it's not being ran inside of a repository folder:
> 
> ```
> Apr 30 15:39:57.871 CRIT absorb failed, err: could not find repository from '.'; class=Repository (6); code=NotFound (-3)
> ```
> 
> Which means that running the `git-absorb` command in `C:\Users\%USERNAME%\Documents\GitHub\winget-pkgs` passes with `%ERRORLEVEL% = 0`:
> 
> ```
> PS C:\Users\TAP\Documents\GitHub\winget-pkgs> git-absorb
> Apr 30 15:42:09.041 WARN Will not fix up past commits not authored by you, use --force to override, commit: cccdd4f1db400afd2658a863dc1cd8fcfb21b772
> Apr 30 15:42:09.048 CRIT No commits available to fix up, exiting
> PS C:\Users\TAP\Documents\GitHub\winget-pkgs> $LASTEXITCODE
> 0
> ```

Oh. I see which is depend on other application.

**Pull request merged**
