### PR TITLE
New version: RubyInstallerTeam.RubyWithDevKit version 3.1.2-1

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

* Resolves #58472

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/58502)

### CODE REVIEW

**Review by OfficialEsco — DISMISSED** [review]

**Comment by OfficialEsco** [comment]
```
Name          : Ruby 3.1.2-1-x64-ucrt with MSYS2
Publisher     : RubyInstaller Team
Version       : 3.1.2-1
ProductCode   : RubyInstaller-3.1-x64-mingw-ucrt_is1
Registry Path : Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\RubyInstaller-3.1-x64-mingw-ucrt_is1
Uninstall     : winget uninstall --id "RubyInstaller-3.1-x64-mingw-ucrt_is1"
```
Hmm, this package could be a good candidate for ARP Entries

**Comment by Trenly** [comment]
> ```
> Name          : Ruby 3.1.2-1-x64-ucrt with MSYS2
> Publisher     : RubyInstaller Team
> Version       : 3.1.2-1
> ProductCode   : RubyInstaller-3.1-x64-mingw-ucrt_is1
> Registry Path : Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\RubyInstaller-3.1-x64-mingw-ucrt_is1
> Uninstall     : winget uninstall --id "RubyInstaller-3.1-x64-mingw-ucrt_is1"
> ```
> 
> Hmm, this package could be a good candidate for ARP Entries

Good point; Wasn't sure if we wanted to or not, but ¯\_(ツ)_/¯ might as well

**Comment by OfficialEsco** [comment]
> Good point; Wasn't sure if we wanted to or not, but ¯_(ツ)_/¯ might as well

I do implement it whenever i see need be as Denelon might want to search for them for testing.
Whenever the ARP fields are in the Manifest it also implies we should take a closer look at the metadata, there is a exe package which changes ProductCode (it got the version number) and we keep missing it because its so easy to miss...

Also here is your arm \ ¯\\\_(ツ)_/¯

**Comment by Trenly** [comment]
> > Good point; Wasn't sure if we wanted to or not, but ¯_(ツ)_/¯ might as well
> 
> I do implement it whenever i see need be as Denelon might want to search for them for testing. Whenever the ARP fields are in the Manifest it also implies we should take a closer look at the metadata, there is a exe package which changes ProductCode (it got the version number) and we keep missing it because its so easy to miss...
> 
> Also here is your arm \ ¯\\\_(ツ)_/¯

Thanks, I forgot that Markdown gets weird with and needs the extra \\\ to make it work

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
