### PR TITLE
XUANZHIINTERNATIONALCO.,LIMITED.LDPlayer version 4.0.56

### PR DESCRIPTION
**Pull request by ayushthesmarty**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15707)

### CODE REVIEW

**Comment by KaranKad** [comment]
`PackageIdentifier` is not good.

**Review by GorujoCY — CHANGES_REQUESTED** [review]
Please look at the Package Identifier and correct it

**Comment by KaranKad** [comment]
> [x] Have you tested your manifest locally with `winget install --manifest <path>`?

Did you actually test it?

**Comment by ayushthesmarty** [comment]
> > [x] Have you tested your manifest locally with `winget install --manifest <path>`?
> 
> Did you actually test it?

yes

**Comment by OfficialEsco** [comment]
> > > [x] Have you tested your manifest locally with `winget install --manifest <path>`?
> > 
> > 
> > Did you actually test it?
> 
> yes

Did you? 🤔
```
PS C:\Users\******\Github\winget-pkgs> winget validate '.\manifests\x\XUANZHIINTERNATIONALCO\,LIMITED\LDPlayer\4.0.56\'
Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended.
```

image

**Pull request closed without merging**
