### PR TITLE
Mariocube.DSDecmp version 4

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/103188)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335226 
> 2023-04-22 16:52:48.527 [CLI ] ShellExecute installer failed: 2148734720 

InstallationVerification-x86-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20230422235248

**Comment by upintheairsheep** [comment]
> Automatic Validation ended with:
> 
> > Installation failed with exit code -1978335226
> > 2023-04-22 16:52:48.527 [CLI ] ShellExecute installer failed: 2148734720
> 
> InstallationVerification-x86-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20230422235248

Time to yet again add that dependencies tag 😮‍💨

**Comment by ItzLevvie** [comment]
[Policy] Dependencies

**Review by ItzLevvie — APPROVED** [review]

**Comment by upintheairsheep** [comment]
> [Policy] Dependencies

Hello Levvi, may you please re-open these stale pull requests:
No blocking issues, I need to fix some stuff:
https://github.com/microsoft/winget-pkgs/pull/100053
https://github.com/microsoft/winget-pkgs/pull/99337
https://github.com/microsoft/winget-pkgs/pull/99330
https://github.com/microsoft/winget-pkgs/pull/99334
https://github.com/microsoft/winget-pkgs/pull/99332
https://github.com/microsoft/winget-pkgs/pull/98794
https://github.com/microsoft/winget-pkgs/pull/98792
https://github.com/microsoft/winget-pkgs/pull/98686
https://github.com/microsoft/winget-pkgs/pull/98684
Interactive-only: 
https://github.com/microsoft/winget-pkgs/pull/99338
https://github.com/microsoft/winget-pkgs/pull/98838 (requires dongle)
https://github.com/microsoft/winget-pkgs/pull/98791
https://github.com/microsoft/winget-pkgs/pull/98705
Dependencies:
https://github.com/microsoft/winget-pkgs/pull/99335
Unknown issue, still will tackle it:
https://github.com/microsoft/winget-pkgs/pull/99333
https://github.com/microsoft/winget-pkgs/pull/98696
Requires Folder Move:
https://github.com/microsoft/winget-pkgs/pull/98692
https://github.com/microsoft/winget-pkgs/pull/98682

**Comment by Trenly** [comment]
Seems the package flags don't apply retroactively. 
[Policy] Reset Feedback

**Pull request closed without merging**
