### PR TITLE
Add new version - WK.WKRadar 7.7.0.336

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/121845)

### CODE REVIEW

**Comment by stephengillie** [comment]
The download is 712 MB and pedestrian, having completed 213 MB in the past 34 minutes, for 6.2 mbps.

**Comment by stephengillie** [comment]
Manual Validation ended with a low-memory reboot. Retrying.

**Review by stephengillie — APPROVED** [review]

**Comment by WKSistemas** [comment]
Hi Stephen  @stephengillie , how are you?
Thank you very much for your support.
Is any additional action still necessary to complete the merge?

**Comment by stephengillie** [comment]
> Hi Stephen @stephengillie , how are you? Thank you very much for your support. Is any additional action still necessary to complete the merge?

Hi @WKSistemas,

An automated process is supposed to perform the squash-and-merge step. Sorry that your PR has required so much manual assistance.

**Pull request merged**
