### PR TITLE
New package: LightSpeedStudios.Undawn version 1

### PR DESCRIPTION
**Pull request by solomoncyj**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/112221&drop=dogfoodAlpha

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
#111634

**Comment by stephengillie** [comment]
This package doesn't install any executables. Is that expected?

**Comment by solomoncyj** [comment]
no, it drops the files at `C:\LevelInfinite\Undawn_PC` however it propts the user if they wnat to add a desktop shortvut or not. this might be the reason

**Comment by stephengillie** [comment]
> no, it drops the files at `C:\LevelInfinite\Undawn_PC` however it propts the user if they wnat to add a desktop shortvut or not. this might be the reason

Oh - this doesn't appear to occur. No files are added at this location, nor are any desktop shortcuts are created.

**Comment by solomoncyj** [comment]
the installet does not accept `/S` and just exits

**Pull request closed without merging**
