### PR TITLE
Kiwix.WikiMed version 1.6.2.0

### PR DESCRIPTION
**Pull request by Jaifroid**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/25453)

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]

**Comment by Jaifroid** [comment]
@OfficialEsco What does the Validation-No-Executables label mean? I've noticed in other cases a mod has run the command /azp run to clear this. It would be good to know why I get this flag sometimes.

**Comment by OfficialEsco** [comment]
I don't even know anymore... It should mean "it failed to find/run the executable" so i have no idea what they do on the backend before they rerun the bot..

**Comment by denelon** [comment]
@OfficialEsco I've got a meeting this afternoon to discuss better documentation for the labels and behaviors. You may have noticed the pipeline health badges and final comment once a manifest has been published. I've been trying to get some of the process streamlined and help with transparency about what's going on. Next I hope to tackle the validation steps and what triggers labels. Some of them have been changing quite a bit recently. I apologize for all of the confusion here.

**Comment by OfficialEsco** [comment]
Well @denelon the badges seems.. useless... Just today we had a 3 hour freeze when it was "healthy"...

The `Publish pipeline succeeded for this Pull Request. Once you refresh your index, this change should be present.` message gets posted multiple times and late so we have to keep pressing `Done`

I finally bothered to create Outlook rules for the bot spam (10k mails from the pipeline a month became a bit too much 🙄), and then you guys add 2 more, one which I'm not sure how to filter since it appears as blank..

The labels is ALL OVER THE PLACE, the technicians add the .Validation file and it somehow resolves for example the `Validation-No-Executables` error..

**Comment by Jaifroid** [comment]
Thanks @OfficialEsco and @denelon. I look forward to the new documentation. In the meantime could someone kindly try running the /azp run macro on this PR to see if it gets unstuck?

**Comment by OfficialEsco** [comment]
You can close and reopen the PR (next to the comment button)

Also @denelon the technicians should catch the PRs with issues a lot quicker, at least when there are 12 Administrators... And 2 Moderators that do help where we can on the front-end...

KevinLaMS got assigned https://github.com/microsoft/winget-pkgs/pull/17876 2 months ago and nothing have happened...

**Comment by Jaifroid** [comment]
Thanks @OfficialEsco.

**Comment by Jaifroid** [comment]
Same resul after closing and opening the PR, unfortunately. @ChuckFerring is this something you can fix?

**Comment by OfficialEsco** [comment]
Yeah this is something the technicians have to fix, doesn't seem like they work on Fridays.. Which is sad since they recently made the bot throw a lot more errors

**Comment by denelon** [comment]
@OfficalEsco this one is being looked at now.

**Comment by denelon** [comment]
We have an "on-call" rotation in place, but it's not working and playing well with the bot assigning engineers. We're looking into that as well.

**Comment by denelon** [comment]
I may be the only person with enough rules in Outlook to somewhat narrow down the firehose of e-mail coming from GitHub. I'm getting tempted to put "magic codes" in all of the bot messages so it's easier to build rules. Sadly if someone copies that in their reply it will still fail so nothing fool proof is in place just yet. If you or others know of any techniques to help, I'm all ears.

**Comment by OfficialEsco** [comment]
> I'm getting tempted to put "magic codes" in all of the bot messages so it's easier to build rules. 

Magic codes? Aka a string for each different message?

> Sadly if someone copies that in their reply it will still fail so nothing fool proof is in place just yet. If you or others know of any techniques to help, I'm all ears.

These are my rules as of now
image

These only apply whenever one of the bots post a comment

**Comment by denelon** [comment]
This package installs, but we can't find a "program" that is the one that should be launched. The icon in the start menu launches something that appears similar to a browser, and it works. Our testing infrastructure is normally looking for the program that should be executed so we can continue with dynamic validation (Defender scan etc.).

**Comment by denelon** [comment]
https://github.com/microsoft/winget-pkgs/issues/25594

**Comment by Jaifroid** [comment]
@denelon Thanks for the explanation of what the label means. This app is a completely standard UWP HTML/JS app. It doesn't have an executable because it is a WinRT WebApp that uses the EdgeHTML engine. Ideally the bot should recognize Web apps and exempt them from the "no-executable" rule automatically.-- i.e. those where the entry point is either an .htm(l) file or a .js file.

**Pull request merged**
