### PR TITLE
New version: Kafan.KafanInput version 1.0.0.308

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#9510](https://github.com/SpecterShell/Dumplings/actions/runs/11810385180).

<details>

<summary>Log</summary>

````
Updated: 1.0.0.300 → 1.0.0.308
No ReleaseNotes (zh-CN) for version 1.0.0.308
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
The manifests for the last version 1.0.0.300 will be removed. Reason: No installer URL is changed compared with the last state while the version is updated
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/190943)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-11-12 20:31:47.583 [FAIL] Installer failed security check. Url: https://input-download.kfsafe.cn/Kafan_Input.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-11-17 20:05:28.323 [FAIL] Installer failed security check. Url: https://input-download.kfsafe.cn/Kafan_Input.exe Result: 0x80004005
> 2024-11-17 19:59:16.827 [FAIL] Installer failed security check. Url: https://input-download.kfsafe.cn/Kafan_Input.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-11-20 09:17:47.882 [FAIL] Installer failed security check. Url: https://input-download.kfsafe.cn/Kafan_Input.exe Result: 0x80004005
> 2024-11-20 09:10:11.812 [FAIL] Installer failed security check. Url: https://input-download.kfsafe.cn/Kafan_Input.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 899.)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
[Policy] Reset Labels

**Comment by ItzLevvie** [comment]
[Policy] Moderator-Approved

**Review by ItzLevvie — APPROVED** [review]
test

**Pull request merged**
