### PR TITLE
Update manifests/t/Tencent/QQ/9.7.12.29112/Tencent.QQ.locale.en-US.yaml

### PR DESCRIPTION
**Pull request by Trenly**
Fixes an issue where this package has multiple different monikers
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/181177)

### CODE REVIEW

**Comment by Trenly** [comment]
Needs Attention

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by mdanish-kh** [comment]
[Policy] reset feedback

**Review by mdanish-kh — APPROVED** [review]
[Policy] Needs-Attention

**Comment by mdanish-kh** [comment]
[Policy] Needs-Attention

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
