### PR TITLE
New version: VSCodium.VSCodium.Insiders version 1.72.0.22264

### PR DESCRIPTION
**Pull request by daiyam**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/80324)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by daiyam** [comment]
Hello,

I don't know what the error is...
`winget validate --manifest <path>` and `winget install --manifest <path>` are working without any error.

**Comment by ItzLevvie** [comment]
It installs fine.

It just fails security check in Azure DevOps which will be cleared up in a few days or so.
```
2022-09-21 18:52:53.465 [FAIL] Installer failed security check. Url: https://github.com/VSCodium/vscodium-insiders/releases/download/1.72.0.22264-insider/VSCodiumSetup-x64-1.72.0.22264-insider.exe Result: 0x80004005
``

**Comment by daiyam** [comment]
@ItzLevvie Thx. Where did you get the error message? When I've looked at the logs in the Azure Pipeline, there were only the message "Failed"...

**Comment by ItzLevvie** [comment]
It's usually published in the artifacts of the run as "InstallationVerificationLogs" https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=374375&view=artifacts&pathAsName=false&type=publishedArtifacts

but it looks like it got wiped for some reason.

**Pull request merged**
