### PR TITLE
Reckel.Cantara version 2.4.1

### PR DESCRIPTION
**Pull request by reckel-jm**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://api.github.com/repos/microsoft/winget-pkgs/pulls/95705)

### CODE REVIEW

**Comment by reckel-jm** [comment]
What is the problem here, do you know that @stephengillie?

**Comment by stephengillie** [comment]
> What is the problem here, do you know that @stephengillie?

We've been working through a few issues. Sorry for the inconvenience. 
* https://github.com/microsoft/winget-pkgs/issues/95543

**Review by stephengillie — APPROVED** [review]

**Comment by reckel-jm** [comment]
> > What is the problem here, do you know that @stephengillie?
> 
> We've been working through a few issues. Sorry for the inconvenience.
> 
>     * [P.S.A. Validation Pipeline and Bot Issues #95543](https://github.com/microsoft/winget-pkgs/issues/95543)

Alright, thank you very much!

**Pull request merged**
