### PR TITLE
Add manifest for Theseus2000 version 1.2C

### PR DESCRIPTION
**Pull request by seedy60**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/54972)

### CODE REVIEW

**Comment by Seedy-Threepio** [comment]
There's nothing wrong with the URL on my side.

**Comment by ItzLevvie** [comment]
> There's nothing wrong with the URL on my side.

Wait for an engineer to take a look.

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
cc @Seedy-Threepio: For future updates, please use the [winget-create tool](https://github.com/microsoft/winget-create) so that you don't cause merge conflicts with your branch.

**Comment by Seedy-Threepio** [comment]
Winget-create was giving some error about a filename not being provided when it tried to open my default web browser, so I just said screw it and submitted a PR manually.

**Pull request closed without merging**
