### PR TITLE
Microsoft.WindowsTerminal.Preview version 1.18.1462.0

### PR DESCRIPTION
**Pull request by consvc**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/108349)

### CODE REVIEW

**Comment by ItzLevvie** [comment]
[Policy] Dependencies

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978334972 
> 2023-12-27 13:19:15.623 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!00007FFEDE7E9A45: (caller: 00007FFEDE773515) Exception(1) tid(1430) 80073CF3 Package failed updates, dependency or conflict validation. 
> 2023-12-27 13:19:16.980 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFEDE7E8724: (caller: 00007FFEDE7E9DFC) Exception(2) tid(1430) 80073CF1 Package was not found.     Msg:[Operation failed: Windows cannot remove Microsoft.WindowsTerminalPreview_3001.18.1462.0_neutral_~_8wekyb3d8bbwe because the current user does not have that package installed. Use Get-AppxPackage to see the list of packages installed.]  
> 2023-12-27 13:19:16.981 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(126)\WindowsPackageManager.dll!00007FFEDE96F371: (caller: 00007FFEDE7EB123) LogHr(1) tid(1430) 80073CF1 Package was not found.     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFEDE7E8724: (caller: 00007FFEDE7E9DFC) Exception(2) tid(1430) 80073CF1 Package was not found. 
> 2023-12-27 13:19:16.990 [CLI ] MSIX installer failed: 2147958003 
> 2023-12-27 13:18:32.217 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!55C013F2: (caller: 55B93932) Exception(1) tid(1874) 80073CF3 Package failed updates, dependency or conflict validation. 
> 2023-12-27 13:18:33.116 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!55BFFFD9: (caller: 55C0189B) Exception(2) tid(1874) 80073CF1 Package was not found. 
> 2023-12-27 13:18:33.116 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(126)\WindowsPackageManager.dll!55C014D6: (caller: 55C02918) LogHr(1) tid(1874) 80073CF1 Package was not found.     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!55BFFFD9: (caller: 55C0189B) Exception(2) tid(1874) 80073CF1 Package was not found. 
> 2023-12-27 13:18:33.120 [CLI ] MSIX installer failed: 2147958003

(Automated response - build 508.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
