### PR TITLE
​

### PR DESCRIPTION
**Pull request by ItzLevvie**
​

### CODE REVIEW

**Comment by KevinLaMS** [comment]
image

**Comment by ItzLevvie** [comment]
cc @KevinLaMS: It's installing fine here on my VM:
image

**Comment by KevinLaMS** [comment]
strange. if i go to the web site, i can download from here:  
www.wemod.com/download/direct

**Comment by ItzLevvie** [comment]
The stub installer from https://www.wemod.com/download/direct downloads https://storage-cdn.wemod.com/app/releases/stable/WeMod-7.0.19.exe when clicking on the "WeMod-Setup.exe" file.

**Pull request closed without merging**
