### PR TITLE
New package: CommandLine.Wave version 0.8.12

### LINKED ISSUE #185135: [Package Request]: CommandLine.Wave
### How can we help?

None

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.waveterm.dev/download
Publisher: Command Line Inc
Package Name: Wave
Description: Open-Source AI-Native Terminal Built for Seamless Workflows
Package Version: 0.8.12
Installer Url:  https://dl.waveterm.dev/releases-w2/Wave-win32-x64-0.8.12.exe

### PR DESCRIPTION
**Pull request by esimkowitz**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? closes #185135

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/185133)

### CODE REVIEW

**Comment by esimkowitz** [comment]
@microsoft-github-policy-service agree [company="Command Line Inc"]

**Comment by esimkowitz** [comment]
@microsoft-github-policy-service agree company="Command Line Inc"

**Comment by esimkowitz** [comment]
@microsoft-github-policy-service agree

**Comment by AsciiWolf** [comment]
Please use the msi installer, not exe.

**Review by AsciiWolf — CHANGES_REQUESTED** [review]
See my previous comment.

**Comment by Trenly** [comment]
> Please use the msi installer, not exe. If a msi installer is available and works equally, it should always be preferred.

Actually, both could be included in the manifest; It would be best if the MSI was ordered first, but there isn't any reason both couldn't be present.

```yaml
Installers:
- InstallerType: msi
  Architecture: x64
  InstallerUrl: <url>
  InstallerSha256: <sha256>
- InstallerType: nullsoft
  Architecture: x64
  InstallerUrl: <url>
  InstallerSha256: <sha256>
```

**Comment by esimkowitz** [comment]
Haha the only reason I used the exe is I had the checksum readily available, will swap it out

**Comment by stephengillie** [comment]
Verify:
image
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
