### PR TITLE
add f3d-app.f3d part 2 : Rename package identifier F3d.F3d to f3d-app.f3d

### PR DESCRIPTION
**Pull request by jo-chemla**
PR has to be split into 2 PRs, see https://github.com/microsoft/winget-pkgs/pull/173403

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/173698)

### CODE REVIEW

**Comment by jo-chemla** [comment]
Yes indeed, I was asked to split the PR into two parts, one to remove `F3d.F3d` and the other one (this one) to add back `f3d-app.f3d`

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files\F3D\bin\f3d.exe returned exit code: -1073741819

Automated error analysis suggests -1073741819 may mean Converted to hexadecimal (C0000005) possibly [Access Violation](https://learn.microsoft.com/en-us/shows/inside/access-violation-c0000005-execute). (This is occasionally seen in PRs despite the install otherwise being successful. Should it be added as an `InstallerSuccessCode` or similar here?)

(Automated response - build 895.)

**Comment by stephengillie** [comment]
InstallerUrl contains Manifest version instead of PR version:
    InstallerUrl: https://github.com/f3d-app/f3d/releases/download/v2.5.0/F3D-2.5.0-Windows-x86_64.exe

(Automated message - build 895)

**Comment by jo-chemla** [comment]
Thanks for merging the 2 other PRs. 
However, the package cannot be found via `winget source update && winget install f3d-app.f3d`. 
Any idea why? Thanks!

**Comment by jo-chemla** [comment]
Thanks, this did work now!

**Pull request merged**
