### PR TITLE
Added ProductCode for HandBrake.HandBrake

### PR DESCRIPTION
**Pull request by KaranKad**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?
image

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/18150)

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]
I was gonna say aint the Publisher incorrect? but it appears there is no Publisher
image
This is not a very good workaround since i believe all the Installer Manifests needs to contain the `ProductCode: HandBrake`, but we'll see

**Comment by KaranKad** [comment]
It worked
image

**Comment by OfficialEsco** [comment]
Yeeee, but how does it work if you have a lower/higher version?

**Comment by KaranKad** [comment]
image

**Comment by OfficialEsco** [comment]
Ooooo cool, gotta remember that for the packages that don't have Publisher then

**Pull request merged**
