### PR TITLE
Manifest update for Microsoft.OpenJDK.11 #13983

### PR DESCRIPTION
**Pull request by d3vel0per**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/13985)

### CODE REVIEW

**Comment by d3vel0per** [comment]
Closes #13983

**Comment by OfficialEsco** [comment]
You messed up by commiting 2 different manifests into one branch, revert the java 16 commit, i already made a manifest for java 16 anyways :)
Also you're damn fast between creating a issue and fixing the problem your self 😆

**Comment by d3vel0per** [comment]
> You messed up by commiting 2 different manifests into one branch, revert the java 16 commit, i already made a manifest for java 16 anyways :)
> Also you're damn fast between creating a issue and fixing the problem your self 😆

Ahh! my bad. Removed commit.

**Comment by d3vel0per** [comment]
Yes!!! as a Java enthusiast couldn't wait after the announcement :)

**Comment by OfficialEsco** [comment]
Whats the difference between Microsoft OpenJDK, Liberica JDK and AdoptOpenJDK tho? 🤔

**Comment by d3vel0per** [comment]
> Whats the difference between Microsoft OpenJDK, Liberica JDK and AdoptOpenJDK tho? 🤔

Different vendors for OpenJDK. Each of them has the provision to add additional enhancements, utilities or maintain different schedules for adding patches/backports etc

**Pull request merged**
