### PR TITLE
New Version: VMware.WorkstationPlayer version 17.5.1.23298084

### PR DESCRIPTION
**Pull request by virtualex-itv**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
Snag_239d3138
- [x] Does your manifest conform to the [1.6 schema](https://githu
b.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141182)

### CODE REVIEW

**Comment by virtualex-itv** [comment]
@stephengillie - i'm back!  pinging you as you've handled these for me in the past, thank you in advance!

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Installer https://download3.vmware.com/software/WKST-PLAYER-1751/VMware-player-full-17.5.1-23298084.exe
 Scan request id: '63fe882a-dbc1-4841-9593-e2cd79a1769a'
 Error information: BlockingDetectionFound
 
 2/27/2024 7:58:34 PM
 
 ****************************************************************************************
 Installer Validation
 ****************************************************************************************
 

(Automated response - build 837.)

**Comment by stephengillie** [comment]
This might be due to a network block of data centers, to prevent automated downloads.

(Automated response - build 837.)

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/pull/141183#issuecomment-1967534801

**Comment by virtualex-itv** [comment]
https://github.com/microsoft/winget-pkgs/pull/141183#issuecomment-1967587522

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/pull/141183#issuecomment-1967687088

**Comment by virtualex-itv** [comment]
@stephengillie  - i made a change as requested here https://github.com/microsoft/winget-pkgs/pull/141183#issuecomment-1971228609

can you check again?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Installer https://download3.vmware.com/software/WKST-PLAYER-1751/VMware-player-full-17.5.1-23298084.exe
 Scan request id: '288fe4ea-e81c-4961-8a9b-3c90b1c3ef8d'
 Error information: BlockingDetectionFound
 
 3/8/2024 2:32:17 AM
 
 ****************************************************************************************
 Installer Validation
 ****************************************************************************************
 

(Automated response - build 869.)

**Comment by stephengillie** [comment]
This might be due to a network block of data centers, to prevent automated downloads.

(Automated response - build 869.)

**Comment by virtualex-itv** [comment]
https://github.com/microsoft/winget-pkgs/pull/141183#issuecomment-1993686420

**Comment by virtualex-itv** [comment]
https://github.com/microsoft/winget-pkgs/pull/141183#issuecomment-2008195745

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Installer https://download3.vmware.com/software/WKST-PLAYER-1751/VMware-player-full-17.5.1-23298084.exe
 Scan request id: '279f7ad4-1a46-4895-b73e-e429504d8288'
 Error information: BlockingDetectionFound
 
 4/18/2024 5:28:54 PM
 
 ****************************************************************************************
 Installer Validation
 ****************************************************************************************
 

(Automated response - build 877.)

**Comment by stephengillie** [comment]
This might be due to a network block of data centers, to prevent automated downloads.

(Automated response - build 877.)

**Pull request closed without merging**
