### PR TITLE
Geany.Geany.Plugins version 1.38

### PR DESCRIPTION
**Pull request by superusercode**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/108780)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335226 
> 2023-06-02 12:26:46.204 [CLI ] ShellExecute installer failed: 2

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335226 
> 2023-12-27 13:17:43.556 [CLI ] ShellExecute installer failed: 2

(Automated response - build 498.)

**Comment by stephengillie** [comment]
Hi @superusercode,

Manual Validation also ended with `ShellExecute installer failed: 2`

I'm having difficulty verifying if this package installed correctly. If I'm understanding correctly, it's a plugin package for `Geany.Geany` - which has these dependencies:

image

Are these the expected plugins from this package? Or should other plugins be present?

**Pull request closed without merging**
