### PR TITLE
New Version: Odin-lang.Odin version dev-2024-06

### PR DESCRIPTION
**Pull request by og-mrk**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/156550)

### CODE REVIEW

**Comment by og-mrk** [comment]
> Hello @og-mrk,
> 
> The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.
> 
> Template: msftbot/validationError/installation/general

May I ask for more information on why did the tests fail?
The [Azure logs](https://dev.azure.com/ms/ed6a5dfa-6e7f-413b-842c-8305dd9e89e6/_apis/build/builds/577896/logs/37) doesn't provide any info related to the Failing of Test.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335141
> 2024-06-04 15:05:03.731 [CLI ] Unable to locate nested installer at: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\odin-lang.Odin.dev-2024-06\extracted\odin.exe

Automated error analysis suggests -1978335141 may mean Unable to locate nested installer. Does the `RelativeFilePath` have the previous version number in it?

(Automated response - build 883.)

**Comment by og-mrk** [comment]
> Automatic Validation ended with:
> 
> > Installation failed with exit code -1978335141
> > 2024-06-04 15:05:03.731 [CLI ] Unable to locate nested installer at: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\odin-lang.Odin.dev-2024-06\extracted\odin.exe
> 
> Automated error analysis suggests -1978335141 may mean Unable to locate nested installer. Does the `RelativeFilePath` have the previous version number in it?
> 
> (Automated response - build 883.)

double checked the archive obtained from Intaller URL, and indeed the `RelativeFilePath` has changed in this version, will update the previous commit accordingly...

Thanks for clarification @stephengillie 😄

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335145
> 2024-06-04 16:30:04.789 [CLI ] Caught std::exception: create_symlink: The system cannot find the path specified.: "C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\odin-lang.Odin__DefaultSource\windows_artifacts\odin.exe", "C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\windows_artifacts\odin.exe"

(Automated response - build 883.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
