### PR TITLE
New version: Microsoft.ServiceFabricSDK version 7.0.1949.9590

### LINKED ISSUE #142677: [Package Issue]: Microsoft.ServiceFabricSDK - version changes after installation
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

After installing `Microsoft.ServiceFabricSDK` version `7.0.1949`, the version shown by `winget list` is `7.0.1949.9590`.

Not exactly sure if it's a package issue or an issue with WinGet.

May be related:
When I `winget configure` with the following resource, it always thinks the package is not installed (even after I manually `winget install`):
```yaml
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Service Fabric SDK
        allowPrerelease: true
      settings:
        id: Microsoft.ServiceFabricSDK
        source: winget
        version: "7.0.1949"
        installMode: Default
  configurationVersion: "0.2.0"
```

### Steps to reproduce

```powershell
winget install -e --id Microsoft.ServiceFabricSDK --version 7.0.1949 --accept-package-agreements
```

### Actual behavior

```powershell
> winget list -e --id Microsoft.ServiceFabricSDK
Name                               Id                         Version       Source
-----------------------------------------------------------------------------------
Microsoft Azure Service Fabric SDK Microsoft.ServiceFabricSDK 7.0.1949.9590 winget
```

### Expected behavior

The version should be `7.0.1949`.

### Environment

```raw
Windows Package Manager v1.7.10582
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3155
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10582.0
```

### Screenshots and Logs

_No response_

### LINKED ISSUE #142724: `winget list` incorrect version after `winget install`
### Brief description of your issue

After installing `Microsoft.ServiceFabricSDK` version `7.0.1949`, the version shown by `winget list` is `7.0.1949.9590`.

Not exactly sure if it's a package issue or an issue with WinGet.

May be related:
When I winget configure with the following resource, it always thinks the package is not installed (even after I manually `winget install`):
```yaml
# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install Service Fabric SDK
        allowPrerelease: true
      settings:
        id: Microsoft.ServiceFabricSDK
        source: winget
        version: "7.0.1949"
        installMode: Default
  configurationVersion: "0.2.0"
```

### Steps to reproduce

```powershell
winget install -e --id Microsoft.ServiceFabricSDK --version 7.0.1949 --accept-package-agreements
```

### Expected behavior

The version should be `7.0.1949`.

### Actual behavior

```powershell
> winget list -e --id Microsoft.ServiceFabricSDK
Name                               Id                         Version       Source
-----------------------------------------------------------------------------------
Microsoft Azure Service Fabric SDK Microsoft.ServiceFabricSDK 7.0.1949.9590 winget
```

### Environment

```shell
Windows Package Manager v1.7.10582
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3155
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10582.0
```

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

* Resolves #142677
Resolves microsoft/winget-pkgs#142724

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/142720)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by Trenly** [comment]
I'm going to try a rerun to see if that helps at all

**Comment by stephengillie** [comment]
Reset approval workflow.

**Review by stephengillie — APPROVED** [review]

**Comment by Trenly** [comment]
Just testing 
[Policy] Issue-Bug

**Comment by stephengillie** [comment]
Reset approval workflow.

**Review by stephengillie — APPROVED** [review]

**Comment by Trenly** [comment]
We'll need to wait for wingetbot to retry adding the Validation-Completed label to see if the changes to the policy service worked

**Comment by Trenly** [comment]
* https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
