### PR TITLE
Frequal.LiveSpy version 2.10

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/102586)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
Screenshot (197)

**Comment by stephengillie** [comment]
> Screenshot (197) It look weird. I have Java 8 already installed on the computer. But why the setup still unable to start?

Is a higher level of Java needed?

**Comment by BrandonWanHuanSheng** [comment]
> > Screenshot (197) It look weird. I have Java 8 already installed on the computer. But why the setup still unable to start?
> 
> Is a higher version of Java needed? 

It seem the setup say Java 1.5.0

**Comment by Trenly** [comment]
Dependencies are now supported in the 1.6 client. If you could please submit a new manifest for the latest version of the package, it would be greatly appreciated!

**Comment by BrandonWanHuanSheng** [comment]
Hmmm, most of the Java is greater than 1.5.0

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 

(Automated response - build 525.)

**Comment by stephengillie** [comment]
This package doesn't appear to like `Oracle.JavaRuntimeEnvironment` and Java 8. Which Java package should be used?

image

**Pull request closed without merging**
