### PR TITLE
Remove version: Google.Chrome.Canary version 131.0.6762.0

### PR DESCRIPTION
**Pull request by damn-good-b0t**
### All InstallerUrls returned `404 Not Found`
- https://dl.google.com/release2/chrome/acluzknw67iqqrdvxonjosldbz5q_131.0.6762.0/131.0.6762.0_chrome_installer.exe
- https://dl.google.com/release2/chrome/acscwgbzzeqphp4gd4z6mytkss3q_131.0.6762.0/131.0.6762.0_chrome_installer.exe
- https://dl.google.com/release2/chrome/acvj5vcqksuxkc2mwywb3jxuogja_131.0.6762.0/131.0.6762.0_chrome_installer.exe

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/186003)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
[Policy] Needs-Manual-Merge

**Comment by stephengillie** [comment]
URL: https://dl.google.com/release2/chrome/acscwgbzzeqphp4gd4z6mytkss3q_131.0.6762.0/131.0.6762.0_chrome_installer.exe 
Response Error: The remote server returned an error: (404) Not Found.

(Automated message - build 923)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
