### PR TITLE
Fix Incorrect Version Number Pycharm Community 211.7142.13

### PR DESCRIPTION
**Pull request by ThioJoe**
The current package lists the version as the "marketing" name of 2021.1.1, instead of the build version that windows sees. Therefore WinGet thinks an up to date build is out of date.

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14768)

### CODE REVIEW

**Comment by KaranKad** [comment]
Yo, ThioJoe!

**Comment by itayzimet** [comment]
i just added an app too

**Comment by ItzLevvie** [comment]
Only **one** manifest per PR. Make another PR for the other manifest.

**Comment by ThioJoe** [comment]
> Only **one** manifest per PR. Make another PR for the other manifest.

This is actually correcting a version number, so I had to rename the folder

**Pull request closed without merging**
