### PR TITLE
Updated Moniker for VMware.WorkstationPlayer version 16.1.2

### PR DESCRIPTION
**Pull request by ImJoakim**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/18654)

### CODE REVIEW

**Comment by ImJoakim** [comment]
🤔

**Comment by OfficialEsco** [comment]
The bot taking its sweet time with the validation it seems

**Comment by ImJoakim** [comment]
@OfficialEsco > The bot taking its sweet time with the validation it seems, gotta think hard about the moniker change..

Haha yeah, they've been stuck for a while. I even closed and made brand new PRs for these 5 that are stuck, but they all get stuck on the same part for some reason.

**Comment by denelon** [comment]
It looks like it's not stuck. It will likely timeout at the 24-25 hour mark. We can run again after that if it doesn't pass for some non-obvious reason.

**Comment by ImJoakim** [comment]
> It looks like it's not stuck. It will likely timeout at the 24-25 hour mark. We can run again after that if it doesn't pass for some non-obvious reason.

@denelon They have timed out on my previous PRs:

#18327
#18332
#18334
#18425
#18421 

I closed them and made brand new PRs to see if that would solve it, but it doesn't look like it did.

**Comment by denelon** [comment]
@ImJoakim please don't close this PR if it times out. I want to take a look to see if I can figure out which back end service is timing out.

**Comment by ImJoakim** [comment]
Perfect. I won't :)

**Comment by ImJoakim** [comment]
@denelon These 5 open PRs timed out:

#18654
#18653
#18652 
#18651 
#18650

**Comment by denelon** [comment]
We're going to see if we can determine why this is happening.

**Comment by ImJoakim** [comment]
> We're going to see if we can determine why this is happening.

Sounds good 😃

**Comment by denelon** [comment]
@ImJoakim nothing concrete yet. We're looking into the timeout issue.

**Comment by ImJoakim** [comment]
> @ImJoakim nothing concrete yet. We're looking into the timeout issue.

Sounds good 👍

**Comment by ImJoakim** [comment]
My other VMware PRs went through. Trying this one again now.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
