### PR TITLE
Remove VMware Workstation Player and Workstation Pro from winget repository

### PR DESCRIPTION
**Pull request by auanasgheps**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

Unfortunately Broadcom has ceased VMware Download servers.
All downloads go trough Broadcom's servers.

Workstation Pro is now free for personal use, but the dowload is locked behind a Broadcom account and extensive data sharing.

The download link is https://downloads2.broadcom.com/?file=VMware-workstation-full-17.5.2-23775571.exe but it doesn't work without your personal authentication headers.

Workstation Player has been discontinued after Workstation Pro has been made free for personal use. Still, VMware download server has been discontinued.

These packages are in a broken state right now.

There's no solution to this sad change, hence removing these packages. 

Source: I am a Broadcom (ex VMware) employee.

### CODE REVIEW

**Comment by auanasgheps** [comment]
There's no validation to be done.

**Comment by stephengillie** [comment]
URL: https://download3.vmware.com/software/WKST-PLAYER-1750/VMware-player-full-17.5.0-22583795.exe 
Response status code does not indicate success: 522 ().

(Automated message - build 881)

**Comment by stephengillie** [comment]
>  The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.

We have a limit of 1 manifest change (add/modify/remove) per PR. Can one of these 2 manifest removals be moved to another PR? Then both should pass this check.

**Comment by auanasgheps** [comment]
I don't know how to move the manifest removal, hence I am closing this PR and I will create two new PRs.

**Pull request closed without merging**
