### PR TITLE
TabibitoTechnology.Icaros version 3.2.1.0

### PR DESCRIPTION
**Pull request by musm**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/17324)

### CODE REVIEW

**Comment by musm** [comment]
I don't understand why we have a hash mismatch. I verified the has is correct.

**Comment by musm** [comment]
Any help resolving the has mismatch would be appreciated. I verified that they match so it is confusing why I'm getting the error.

**Comment by musm** [comment]
Any help resolving the has mismatch would be appreciated. I verified that they match so it is confusing why I'm getting the error.

**Comment by musm** [comment]
Any help resolving the has mismatch would be appreciated. I verified that they match so it is confusing why I'm getting the error.

**Comment by denelon** [comment]
@musm the installer URL took me to a page where a download key was generated. I suspect that's part of the problem here. It looks like there isn't a "static" URL directly to the package.

**Comment by musm** [comment]
@denelon Yes that looks correct. Unfortunately I am not sure how we can resolve this.

**Comment by musm** [comment]
In the meantime I will inquire if the package author is able to upload the installer to a stable url.

**Comment by musm** [comment]
Huh, it would be good to find an good solution

**Comment by ItzLevvie** [comment]
Oops, I may accidently  added your PR to the list of PRs that needed to be closed for being invalid, but the only good solution here would be to talk to the application developer about it since the download link can only come from the publisher's or ISV's website rather than uploading it to MediaFire, Google Drive, or OneDrive.

**Pull request closed without merging**
