### PR TITLE
GoogleLLC.GoogleBackupandSync version 1.3.36.82

### PR DESCRIPTION
**Pull request by techflashYT**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14555)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Already added under https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/Google/BackupAndSync

**Comment by sanikdah** [comment]
I already tried searching for this but didn'y find it in the list of programs, either i'm just blind or someone added it at roughly the same time as me.

**Comment by OfficialEsco** [comment]
Ahh ye fair enough, the PR came in 26 hours ago and it got merged 12 hours ago. There is just too many PR's with issues now so didn't investigate too much 👍

**Comment by sanikdah** [comment]
yeah i'm sitting with 3 PRs that had errors and 1 that is just stuck in the validation stage and has been since yesterday.

**Pull request closed without merging**
