### PR TITLE
Update version: Microsoft.PowerToys version 0.72.0

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/115728&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @crutkas,

Do you approve of this update?

**Comment by crutkas** [comment]
Is the reason so release notes are added?  I would rather our github action system does this so we maintain the e2e for the hashes

**Comment by CoolPlayLin** [comment]
It appears this PR used Komac to update. This WinGet Manifest Creator would read ReleaseNotes if the download URLs users typed is belong to Github
Komac: https://github.com/russellbanks/Komac
CC @crutkas

**Comment by Trenly** [comment]
Stale

**Pull request closed without merging**
