### PR TITLE
New: LeiGod.LeiGodAcc version 7.0.5.8

### PR DESCRIPTION
**Pull request by SpecterShell**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
​

**Review by ItzLevvie — APPROVED** [review]

**Comment by vedantmgoyal2009** [comment]
@KevinLaMS @msftrubengu @ChuckFerring @jamespik

**Comment by ItzLevvie** [comment]
> @KevinLaMS @msftrubengu @ChuckFerring @jamespik

I don't think an administrator would be able to do anything with this PR because all PRs have to go through Dynamic Analysis, but it's failing since the application is likely falsely flagged as PUA, malware, spyware, etc. either by Microsoft Defender or other anti-virus software.

**Comment by vedantmgoyal2009** [comment]
I just found https://docs.microsoft.com/en-us/windows/package-manager/package/winget-validation, and you're correct. Thanks.

**Pull request closed without merging**
