### PR TITLE
Fix PackageVersion for PowerShell Preview 7.4.0.1

### PR DESCRIPTION
**Pull request by mdanish-kh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/99814)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/99814)

### CODE REVIEW

**Comment by mdanish-kh** [comment]
Pipelines don't like it when PackageVersion does not match with the version reported by MSIX :/

image

**Review by anamnavi — APPROVED** [review]
LGTM

**Comment by anamnavi** [comment]
Addresses #99631

**Review by stephengillie — APPROVED** [review]

**Comment by mdanish-kh** [comment]
> So the msix version (7.4.1.0) does not need to be specified anywhere at all?

Ideally the MSIX version should be the PackageVersion, there is no way to specify this version in the manifest otherwise (as MSIX installers don't support specifying `AppsAndFeaturesEntries` in the manifest).

There are potential few problems with specifying a version in the manifest that does not match what is reported in Apps&Features, but given the circumstances to avoid ambiguity for the end-user, the fact I've not seen those ever reported for PowerShell and it's a temp scenario, I'd say we don't specify it in the manifest for now.

**Comment by mdanish-kh** [comment]
> So the msix version (7.4.1.0) does not need to be specified anywhere at all?

@anamnavi Ideally the MSIX version should be the PackageVersion, there is no way to specify this version in the manifest otherwise (as MSIX installers don't support specifying `AppsAndFeaturesEntries` in the manifest).

There are potential few problems with specifying a version in the manifest that does not match what is reported in Apps&Features, but given the circumstances to avoid ambiguity for the end-user, the fact I've not seen those ever reported for PowerShell and it's a temp scenario, I'd say we don't specify it in the manifest for now.

(Also, I'm curious to understand why are there separate versions for the MSI and MSIX installers 👀)

**Pull request merged**
