### PR TITLE
Remove version: ArmCord.ArmCord version 3.1.1

### PR DESCRIPTION
**Pull request by fancybody**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/192859)

### CODE REVIEW

**Comment by Trenly** [comment]
[Policy] Highest Version Removal

**Comment by Dragon1573** [comment]
> @Dragon1573, can you open a PR adding `Legcord` as a new package?

According to [`README.md`](https://github.com/Legcord/Legcord/blob/dev/README.md#windows), _LegCord_ is already available in the repository as package identifier [`smartfrigde.Legcord`](https://winstall.app/apps/smartfrigde.Legcord).

@Trenly, I think this pull request of removal can be accepted. 🙏🏼

**Comment by Trenly** [comment]
[Policy] Reset Feedback

**Comment by Trenly** [comment]
[Policy] Moderator Approved

**Review by Trenly — APPROVED** [review]

**Pull request merged**
