### PR TITLE
New Package: seerge.g-helper.PreRelease version 0.170

### PR DESCRIPTION
**Pull request by Trenly**
﻿Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/152026)

### CODE REVIEW

**Comment by Trenly** [comment]
Blocked by defender -
image

**Comment by stephengillie** [comment]
Hi @Trenly,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 880.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-02 17:00:27.981 [REPO] Failed to open available source: msstore
> 2024-05-02 17:00:35.599 [REPO] Failed to open available source: msstore
> 2024-05-02 17:01:10.089 [FAIL] Installer failed security check. Url: https://github.com/seerge/g-helper/releases/download/v0.170/GHelper.zip Result: 0x80004005
> MSI (s) (9C:14) [17:00:48:822]: Executing op: ComponentRegister(ComponentId={A43E4B57-C7E9-532F-9B3C-8BA078535982},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.18\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1)
> MSI (s) (9C:14) [17:00:50:338]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,)
> Property(S): ErrorDialog = ErrorDlg

(Automated response - build 880.)

**Comment by stephengillie** [comment]
Verify: 
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
