### PR TITLE
GiulioSorrentino.CBriscola.Avalonia version 0.7.8

### PR DESCRIPTION
**Pull request by GiulianoSpaghetti**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141343)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 849.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-02-28 12:25:50.612 [FAIL] Installer failed security check. Url: https://github.com/numerunix/CBriscola.Avalonia/releases/download/0.7.8/CBriscola.Avalonia-0.7.8-x64.msi Result: 0x80004005
> MSI (s) (44:60) [12:25:04:655]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1)
> MSI (s) (44:60) [12:25:05:968]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,)
> Property(S): ErrorDialog = ErrorDlg

(Automated response - build 849.)

**Comment by numerunix** [comment]
I think it's the smart screen.

**Comment by numerunix** [comment]
Smart screen of windows defender on x64

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
