### PR TITLE
Add manfiest file for Zoom v5.2.42619.0804

### PR DESCRIPTION
**Pull request by mehtanisarg369**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2905)

### CODE REVIEW

**Review by KevinLaMS — CHANGES_REQUESTED** [review]
This will fail due to the silent and silentwithprogress switches.  They are handled automatically by the MSI installertype.  If you delete those and keep the custom switch, it will work.  Please make the change.

**Comment by KevinLaMS** [comment]
image

**Comment by mehtanisarg369** [comment]
> 
> 
> This will fail due to the silent and silentwithprogress switches. They are handled automatically by the MSI installertype. If you delete those and keep the custom switch, it will work. Please make the change.

Hi @KevinLaMS,
Thank you very much for your notification. I've made the suggested changes and have issued another PR. I'll keep this in mind in future.
Thank you once again for your guidance and support.

Regards,
Nisarg.

**Review by ghost — APPROVED** [review]
Validation has completed

**Review by KevinLaMS — APPROVED** [review]

**Pull request merged**
