### PR TITLE
Update Netron to 6.8.6

### PR DESCRIPTION
**Pull request by lutzroeder**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/103845)

### CODE REVIEW

**Comment by mdanish-kh** [comment]
cc @denelon @stephengillie - Is this a bug with the pipelines? I'm not sure how this didn't get labelled with https://github.com/microsoft/winget-pkgs/labels/PullRequest-Error as two manifests were modified in this PR.

Looking at the pipeline logs it seems only the 6.8.6 manifest was validated and installed

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by denelon** [comment]
We will have to look and see what happened here. This shouldn't have passed with two separate versions in the PR.

**Comment by mdanish-kh** [comment]
@denelon - I guess it was GitHub bugging out with the "Files Changed" counter (or this was pushed from a branch that was quite outdated), that is why I deleted my comment. I took a look and `6.8.5` was already merged into the repo before making of this PR. Since the Pipelines always clone a fresh copy of the winget-pkgs repo, this did not get flagged as two separate manifests.

**Comment by mdanish-kh** [comment]
So, I believe Pipelines are not to blame here..this should not have been shown as `6 Files Changed`

**Pull request merged**
