### PR TITLE
New Version: Scrumchrono 0.1.6

### PR DESCRIPTION
**Pull request by pedrojreis**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141370)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @pedrojreis,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 849.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\pedrojreis.scrumchrono__DefaultSource\ScrumChrono.exe returned exit code: 2
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\ScrumChrono.exe returned exit code: 2
> Installation failed with exit code -1978335187
> 2024-02-28 14:19:52.973 [FAIL] Installer failed security check. Url: https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.6/ScrumChrono_Windows_i386.zip Result: 0x80004005

(Automated response - build 849.)

**Comment by stephengillie** [comment]
Hi @pedrojreis,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 849.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\pedrojreis.scrumchrono__DefaultSource\ScrumChrono.exe returned exit code: 2
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\ScrumChrono.exe returned exit code: 2
> Installation failed with exit code -1978335187
> 2024-02-28 14:19:52.973 [FAIL] Installer failed security check. Url: https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.6/ScrumChrono_Windows_i386.zip Result: 0x80004005

(Automated response - build 849.)

**Comment by pedrojreis** [comment]
It's definitely a false positive, but how can I prevent this from happening? What is actually triggering this? 🤔

**Comment by pedrojreis** [comment]
What can I do?

**Comment by stephengillie** [comment]
Hi @pedrojreis,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 861.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-01 09:34:35.787 [FAIL] Installer failed security check. Url: https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.6/ScrumChrono_Windows_x86_64.zip Result: 0x80004005
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Packages\pedrojreis.scrumchrono__DefaultSource\ScrumChrono.exe returned exit code: 2
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\ScrumChrono.exe returned exit code: 2

(Automated response - build 861.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\pedrojreis.scrumchrono__DefaultSource\ScrumChrono.exe returned exit code: 2
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\ScrumChrono.exe returned exit code: 2
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Packages\pedrojreis.scrumchrono__DefaultSource\ScrumChrono.exe returned exit code: 2
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\ScrumChrono.exe returned exit code: 2

(Automated response - build 863.)

**Comment by stephengillie** [comment]
Completing validation.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
