### PR TITLE
Tgstation.Server version 5.18.2

### PR DESCRIPTION
**Pull request by Cyberboss**
# Automated Pull Request

This pull request was generated by our [deployment pipeline](https://github.com/tgstation/tgstation-server/actions/runs/6924169311) as a result of the release of [tgstation-server-v5.18.2](https://github.com/tgstation/tgstation-server/releases/tag/tgstation-server-v5.18.2). Validation was performed as part of the process.

The user account that created this pull request is available to correct any issues.

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
  - This PR is generated as a direct result of a new release of `tgstation-server` this should be impossible
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
  - Validation is performed as a prerequisite to deployment.
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
  - Manifest installation and uninstallation is performed as a prerequisite to deployment.
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/127366)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 2:38:58 PM:  > 2023-11-20 14:38:57.236 [CLI ] Package hash verification failed. SHA256 in manifest 
[6bae5acd447942b94663ae4f7483ddae50a297d9989eef35e6de75081064860f] does not match download 
[1f2abd00ebe7d273f1ac269904064b7d73726613b510f37675df9eb7f4fbe470]

**Comment by Cyberboss** [comment]
@stephengillie could you try again please? I'm unable to replicate in when installing locally 
image

**Comment by stephengillie** [comment]
@Cyberboss,

Sorry for the chaos with this PR.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
