### PR TITLE
EdrawSoft.EdrawMax.CN version 11.5.2

### PR DESCRIPTION
**Pull request by Dragon1573**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

## Information about the installer

According to responses from online technical support, this **Simplified Chinese** version is different from the **International** version `EdrawSoft.EdrawMax` and does NOT support "silent-installation". Users have to interactively install it.

If there are advanced users can handle that "silent-installation" stuff, could you please do me a favour and improve this manifest?

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
We'll have to wait until interactive-only installers are supported in WinGet and in WinGet's pipelines.

For now, you can set this PR to DRAFT; until this feature has been implemented.

**Comment by Dragon1573** [comment]
Related #40558 . Thank you @ItzLevvie , I'll convert this PR into "Draft Mode".

**Comment by Dragon1573** [comment]
**Winget** does not support "interactive-only" installer at the moment. Waiting for this feature released.

**Review by ItzLevvie — APPROVED** [review]

**Comment by Dragon1573** [comment]
Related #37971, #40558.

Excuse me @ItzLevvie , does `winget.exe` support "interactive-only" installer? Can I mark this PR "ready for reaview"?

**Comment by ItzLevvie** [comment]
> does `winget.exe` support "interactive-only" installer? Can I mark this PR "ready for reaview"?

No not yet.

I approved for filtering purposes.

**Comment by Dragon1573** [comment]
> No not yet.
> 
> I approved this PR for GitHub CLI filtering purposes.

Okay, I'll leave the above 3 prs "work in progress". Can't wait for the feature!

**Comment by Dragon1573** [comment]
It seems like someone else selve this problem. This pull request can be close unmerged.

- Latest version of the package: `12.0.3.930`
- Related pull request: #80698

**Pull request closed without merging**
