### PR TITLE
New package: cjmurph.PlexService version 1.2.3

### LINKED ISSUE #146946: [Package Request]: Plex Media Server service wrapper for windows
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/cjmurph/PmsService
Publisher: cjmurph
Package Name: PlexService
Description: Service wrapper for Plex Media Server
Package Version: 1.2.3.0
Installer URL: https://github.com/cjmurph/PmsService/releases/download/v1.2.3/PlexService_1.2.3.0.msi

### PR DESCRIPTION
**Pull request by Exorcism0666**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Is there a linked Issue?
- Resolve https://github.com/microsoft/winget-pkgs/issues/146946

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/146956)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-03-29 10:16:00.936 [CLI ] ShellExecute installer failed: 1603
> CreateUser:  Error 0x80070103: failed to read attributes from custom action data
> CustomAction CreateUser returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
> Property(S): ErrorDialog = ErrorDlg
> MSI (s) (88:50) [10:16:00:651]: Product: Plex Service -- Installation failed.

(Automated response - build 876.)

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
From the installer log: 

> CreateUser:  Error 0x80070103: failed to read attributes from custom action data
CustomAction CreateUser returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)

Running installer manually:
Installer screen showing "Specify service account credentials" and locations for username and password.

This installer appears to require a service account username and password - is that accurate?

**Comment by palopezv** [comment]
> From the installer log:
> 
> > CreateUser:  Error 0x80070103: failed to read attributes from custom action data
> > CustomAction CreateUser returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
> 
> Running installer manually: Installer screen showing "Specify service account credentials" and locations for username and password.
> 
> This installer appears to require a service account username and password - is that accurate?

Yes, it is accurate, as shown in the screenshot.

**Comment by Exorcism0666** [comment]
> > From the installer log:
> > > CreateUser:  Error 0x80070103: failed to read attributes from custom action data
> > > CustomAction CreateUser returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
> > 
> > 
> > Running installer manually: Installer screen showing "Specify service account credentials" and locations for username and password.
> > This installer appears to require a service account username and password - is that accurate?
> 
> Yes, it is accurate, as shown in the screenshot.

@stephengillie

**Comment by stephengillie** [comment]
The silent install appears to be blocked by a lack of credentials - the username and password needed to [create a user account](https://learn.microsoft.com/en-us/dotnet/api/system.web.security.membership.createuser?view=netframework-4.8.1#system-web-security-membership-createuser(system-string-system-string)) in the OS. Is there a way to supply these through another means, such as installer switch?

It might be possible to specify these settings through a `--custom` switch, which could let the package manager pass the user-specified username and password through to the installer. I'm not completely sure how it would operate, but having another means to specify these credentials is the first step.

**Comment by Exorcism0666** [comment]
> The silent install appears to be blocked by a lack of credentials - the username and password needed to [create a user account](https://learn.microsoft.com/en-us/dotnet/api/system.web.security.membership.createuser?view=netframework-4.8.1#system-web-security-membership-createuser(system-string-system-string)) in the OS. Is there a way to supply these through another means, such as installer switch?
> 
> It might be possible to specify these settings through a `--custom` switch, which could let the package manager pass the user-specified username and password through to the installer. I'm not completely sure how it would operate, but having another means to specify these credentials is the first step.

@palopezv

**Comment by palopezv** [comment]
I forgot to mention that the account can anything as long as it has administrative privilege. I use my personal account. The thing is: the installer asks for a preexisting account.

**Comment by Trenly** [comment]
> The silent install appears to be blocked by a lack of credentials - the username and password needed to [create a user account](https://learn.microsoft.com/en-us/dotnet/api/system.web.security.membership.createuser?view=netframework-4.8.1#system-web-security-membership-createuser(system-string-system-string)) in the OS. Is there a way to supply these through another means, such as installer switch?
> 
> It might be possible to specify these settings through a `--custom` switch, which could let the package manager pass the user-specified username and password through to the installer. I'm not completely sure how it would operate, but having another means to specify these credentials is the first step.

Even if it could be passed in using `--custom`, there is no way to require the argument at runtime

**Pull request closed without merging**
