### PR TITLE
Fixing jq manifest according to 1.4.0 schema

### PR DESCRIPTION
**Pull request by RockyMM**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/116426&drop=dogfoodAlpha

### CODE REVIEW

**Comment by RockyMM** [comment]
To be honest, when I tested this manifest I did get

```
Command line alias added: "jq"
```

However, when I typed `jq` nothing happened. Should I logout/login or refresh the shell somehow?

**Comment by Trenly** [comment]
> To be honest, when I tested this manifest I did get
> 
> ```
> Command line alias added: "jq"
> ```
> 
> However, when I typed `jq` nothing happened. Should I logout/login or refresh the shell somehow?

The symlink likely wasn’t added due to not being run in admin mode. See
* https://github.com/microsoft/winget-cli/issues/3437

**Review by Trenly — COMMENTED** [review]
This PR doesn’t actually change anything, as the items being at the root level of the manifest functions the same as them being at the installer level

**Review by stephengillie — APPROVED** [review]

**Comment by RockyMM** [comment]
> > To be honest, when I tested this manifest I did get
> > ```
> > Command line alias added: "jq"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > However, when I typed `jq` nothing happened. Should I logout/login or refresh the shell somehow?
> 
> The symlink likely wasn’t added due to not being run in admin mode. See
> 
> * [Portable installers are not renamed in non-symlinked installations winget-cli#3437](https://github.com/microsoft/winget-cli/issues/3437)

Thanks for the tip. I will try it out. As for the content of my PR, at least now the content is according to schema. I know it's not much _but it's honest work_ 😁

**Pull request merged**
