### PR TITLE
Modify: B3log.SiYuan version 1.8.2

### PR DESCRIPTION
**Pull request by SpecterShell**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/46665)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Quick question, why do you reverse the Tags? 🤔

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
So then another question, why are you rerunning the script on a version that is already added instead of just adding the ReleaseNotes?
When you are doing it your way you are adding "invalid tags" back in and we don't see the tags you've changed/added as easily

**Comment by OfficialEsco** [comment]
Not 100% sure what you mean by

> to opening new pull requests without leaving the editor.

But if you do `git fetch --all && git checkout upstream/master` you will get the latest manifest, if you have or open the manifest and change the tags or add the Release information you ONLY change whatever you've changed.

"invalid tags" are uppercase characters or space between words which the YamlCreate.ps1 script fixed but your script keeps reversing 😁

**Comment by OfficialEsco** [comment]
Have you submitted a Issue over at the Powershell repo regarding the Sorting? Powershell Core/7 IS the future so it should be fixed there

**Pull request merged**
