### PR TITLE
MisiteBao.MisiteBao version 1.1.3

### PR DESCRIPTION
**Pull request by misitebao**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101404)

### CODE REVIEW

**Comment by misitebao** [comment]
> Hello @misitebao,
> 
> The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.
> 
> Template: msftbot/validationError/installation/general

The local test was successful and no problems were encountered. Can you provide the log of the error?

**Comment by stephengillie** [comment]
I'm not able to find the cause for this error. It installs and runs normally on a Windows 11 VM. The package appears to open the author's website. 
image

**Comment by Trenly** [comment]
> I'm not able to find the cause for this error. It installs and runs normally on a Windows 11 VM. The package appears to open the author's website. image

It's this -
```
2023-04-03 10:53:37.053 [FAIL] Installer failed security check. Url: https://github.com/misitebao/misitebao/releases/download/v1.1.3/MisiteBao_1.1.3_windows_386.zip Result: 0x80004005
```

**Comment by misitebao** [comment]
> I'm not able to find the cause for this error. It installs and runs normally on a Windows 11 VM. The package appears to open the author's website.

This is expected behavior

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
