### PR TITLE
New version: ast-grep.ast-grep version 0.17.1

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136017)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Trenly,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 642.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-24 12:43:18.786 [FAIL] Installer failed security check. Url: https://github.com/ast-grep/ast-grep/releases/download/0.17.1/sg-x86_64-pc-windows-msvc.zip Result: 0x80004005 MSI (s) (E4:F0) [12:43:06:350]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (E4:28) [12:43:07:256]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Additional Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [1FFC:1E70][2024-01-24T12:43:04]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 642.)

**Comment by Trenly** [comment]
```
--> Installing WinGet
--> Disabling safety warning when running installer
Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.

--> Configuring Winget
Enabled admin setting 'LocalManifestFiles'.
Enabled admin setting 'LocalArchiveMalwareScanOverride'.


--> Installing the Manifest 0.17.1

Found ast-grep [ast-grep.ast-grep] Version 0.17.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Packages
      Microsoft.VCRedist.2015+.x64
Installing dependencies:
(1/1) Found Microsoft Visual C++ 2015-2022 Redistributable (x64) [Microsoft.VCRedist.2015+.x64] Version 14.38.33130.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.visualstudio.microsoft.com/download/pr/f04bd1f4-d474-4dc1-bb63-5c059bb86c55/4DFE83C91124CD542F4222FE2C396CABEAC617BB6F59BDCBDF89FD6F0DF0A32F/VC_redist.x64.exe
  ██████████████████████████████  24.2 MB / 24.2 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Downloading https://github.com/ast-grep/ast-grep/releases/download/0.17.1/sg-x86_64-pc-windows-msvc.zip
  ██████████████████████████████  6.04 MB / 6.04 MB
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "sg"
Path environment variable modified; restart your shell to use the new value.
Successfully installed

--> Refreshing environment variables

--> Comparing ARP Entries

DisplayName                                                        DisplayVersion Publisher             ProductCode                            Scope
-----------                                                        -------------- ---------             -----------                            -----
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.38.33130 14.38.33130.0  Microsoft Corporation {1de5e707-82da-4db6-b810-5d140cc4cbb3} Mac...
ast-grep                                                           0.17.1         ast-grep              ast-grep.ast-grep__DefaultSource       User



PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> sg
Search and Rewrite code at large scale using precise AST pattern

Usage: sg.exe <COMMAND>

Commands:
  run          Run one time search or rewrite in command line. (default command)
  scan         Scan and rewrite code by configuration
  test         Test ast-grep rules
  new          Create new ast-grep project or items like rules/tests
  lsp          Start language server
  completions  Generate shell completion script
  docs         Generate rule docs for current configuration. (Not Implemented Yet)
  help         Print this message or the help of the given subcommand(s)

Options:
  -h, --help     Print help (see more with '--help')
  -V, --version  Print version
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> sg --version
ast-grep 0.17.1
```

**Comment by stephengillie** [comment]
Hi @Trenly,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 674.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-26 14:25:50.018 [FAIL] Installer failed security check. Url: https://github.com/ast-grep/ast-grep/releases/download/0.17.1/sg-x86_64-pc-windows-msvc.zip Result: 0x80004005 MSI (s) (D8:00) [14:25:37:457]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (D8:F0) [14:25:38:442]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Additional Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [0694:0A9C][2024-01-26T14:25:35]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 674.)

**Comment by stephengillie** [comment]
Hi @Trenly,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 695.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-30 12:37:11.530 [FAIL] Installer failed security check. Url: https://github.com/ast-grep/ast-grep/releases/download/0.17.1/sg-x86_64-pc-windows-msvc.zip Result: 0x80004005 MSI (s) (98:7C) [12:36:58:557]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (98:2C) [12:36:59:682]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Additional Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [1ACC:0628][2024-01-30T12:36:56]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 695.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 702.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
