### PR TITLE
New package: wagoodman.dive version 0.10.0

### PR DESCRIPTION
**Pull request by Okeanos**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://api.github.com/repos/microsoft/winget-pkgs/pulls/95634)

### CODE REVIEW

**Comment by Okeanos** [comment]
Probably a victim of #95543?

**Comment by denelon** [comment]
I don't think so. Do you have a screenshot showing the output from "dive" after installing the package?

**Comment by Okeanos** [comment]
Sure: Screenshots attached:

Screenshot 2023-02-10 at 22 43 39

Screenshot 2023-02-10 at 22 47 27

If you need I can also provide screenshots of dive in action, however, as a demonstration that installation from the provided manifest works as expected the screenshots above should suffice.

**Comment by denelon** [comment]
With the default execution of "dive" it may be returning a non-zero exit code as it expects input. That's the most likely reason validation would fail. Now that we know the "dive --version" argument provides functional output (as long as the return code is 0) then we should be able to perform a manual validation.

**Comment by Okeanos** [comment]
That totally makes sense … d'oh.

Screenshot 2023-02-10 at 23 12 22

**Comment by Okeanos** [comment]
Should I patch the manifest to include a value for `InstallerSuccessCodes` (`1` in this case)?

**Comment by Trenly** [comment]
> Should I patch the manifest to include a value for `InstallerSuccessCodes` (`1` in this case)?

No, since the installer success code is different than the runtime success code which causes the executable error

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
