### PR TITLE
New version: DuckStudio.FufuDevTools version 2024.06.30.1356

### PR DESCRIPTION
**Pull request by DuckDuckStudio**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue? --No

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
> Only today commit.
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?

```
$ winget validate --manifest manifests\d\DuckStudio\FufuDevTools\2024.06.30.1356
清单验证成功。
```

- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?

> [!NOTE]
> After installation, use the following command to verify the installation:
> ```powershell
> ffdev
> ```

- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

CC @Luna-Grace

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/160758)

### CODE REVIEW

**Review by Luna-Grace — APPROVED** [review]

**Comment by Luna-Grace** [comment]
@DuckDuckStudio 是否应该统一源

**Comment by DuckDuckStudio** [comment]
> @DuckDuckStudio 是否应该统一源

已统一源，但未影响安装程序，故清单无更改。

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files (x86)\Fufu_Dev_Tools\Script\ffdev.exe returned exit code: 1
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\代码校对\参数查重.exe returned exit code: 2
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\代码校对\尾随空格.exe returned exit code: 2
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\代码校对\末尾空行.exe returned exit code: 2
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\代码校对\非UTF-8编码.exe returned exit code: 2
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\生成工具\需求生成.exe returned exit code: 2
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\统计\代码总行数.exe returned exit code: 2
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\git\git连续尝试.exe returned exit code: 1
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\git\账号切换.exe returned exit code: 1
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\git\连续pull尝试.exe returned exit code: 1
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\git\连续push尝试.exe returned exit code: 1

(Automated response - build 886.)

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
