### PR TITLE
Added Amazon.AWSCLI version 2.2.19.0

### PR DESCRIPTION
**Pull request by ImJoakim**
image

```
PS C:\Users\WDAGUtilityAccount\Desktop\manifests> winget install -m "C:\Users\WDAGUtilityAccount\Desktop\manifests\a\Amazon\AWSCLI\2.2.19.0"
Found AWS Command Line Interface v2 [Amazon.AWSCLI]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://awscli.amazonaws.com/AWSCLIV2-2.2.19.msi
  ██████████████████████████████  26.6 MB / 26.6 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/21028)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
The reason why `v2` was removed was because it messes up `winget list` for those that have `v1` installed on their machine.

**Comment by OfficialEsco** [comment]
> The reason why `v2` was removed was because it messes up `winget list` for those that have `v1` installed on their machine.

Isn't v1 and v2 2 different softwares? or is v2 just a newer software which you want the v1 users to update to?

**Review by jedieaston — APPROVED** [review]

**Comment by jedieaston** [comment]
Yes, let me fix that...

**Comment by ItzLevvie** [comment]
> Isn't v1 and v2 2 different softwares? or is v2 just a newer software which you want the v1 users to update to?

They are both different versions but the issue is that having the version displayed will also show the `v2` name for those who've the `v1` version of AWS CLI installed as this is what winget uses to display the name to everyone.

If you named this package as `AWS Command Line Interface 2.2.19.0` those that have v1 installed and did `winget list`, it would show up as 
```
AWS Command Line Interface 2.2.19.0                         1.0.0.0 (example)                        2.2.19.0 (latest version)
```

This would confuse people into thinking that they've `2.2.19.0` but instead they have `1.0.0.0`.

**Comment by OfficialEsco** [comment]
That is not the intended behaviour, winget-cli uses all manifest in the Software folder for metadata matching, so if one locale contains `PackageName: AWS Command Line Interface` it will match against any `AWS Command Line Interface *wildcard*` until its renamed to `AWS Command Line Interface v2`

As far as i can see
<------- This dummy
is guilty in version 2.2.2.0

But yeah we should split them into v1 and v2 eitherway

**Comment by ItzLevvie** [comment]
🤷. It might be on my end but it seems to be happening to K-Lite Codec Pack, it picks up the name from the latest manifest (from https://github.com/microsoft/winget-pkgs/blob/master/manifests/c/CodecGuide/K-LiteCodecPackBasic/16.3.0/CodecGuide.K-LiteCodecPackBasic.locale.en-US.yaml#L8) rather than the one installed on the machine (from https://github.com/microsoft/winget-pkgs/blob/master/manifests/c/CodecGuide/K-LiteCodecPackBasic/16.2.5/CodecGuide.K-LiteCodecPackBasic.locale.en-US.yaml#L7).

Install an old version:
image

`winget list` shows:
image

**Comment by OfficialEsco** [comment]
> It might be on my end but it seems to be happening to K-Lite Codec Pack which has the PackageVersion in the PackageName.

The PackageName is intended because K-Lite have tons of package versions with a bad naming schema, however yes you are correct that winget-cli shows the Metadata from the latest Manifest, this is probably done for a few reasons, however K-Lite `Codec Pack 16.2.5 Basic` will not be detected in `winget list` unless the `PackageName` in that version of the Manifest is `K-Lite Codec Pack 16.2.5 Basic`

This is something that the winget-cli team have to solve, we're just the workaround people 🤷‍♂️
cc @denelon feature idea
Maybe we should have a Standard Manifest Metadata yaml file and version specific Metadata?
```
- Publisher
-- Software
---  Version 1
----    version.yaml
----    locale.yaml
----    installer.yaml
---  Version 2
----    version.yaml
----    locale.yaml
----    installer.yaml
---  locale.yaml
```

**Comment by ItzLevvie** [comment]
>however K-Lite Codec Pack 16.2.5 Basic will not be detected in winget list unless the PackageName in that version of the Manifest is K-Lite Codec Pack 16.2.5 Basic

I'll do a PR test in a couple of days to see if that's the case, if it breaks, then we'll have to revert the PR and wait for the WinGet team to implement better ARP matching in manifests because the way it's currently set up would confuse people into thinking that they've the latest version installed. but in reality, they've the old version of it installed when doing `winget list` and it also shows up in third-party GUIs (like https://winstall.app) a bit weirdly.

If I recall correctly, there was an application that had `blah <version> blah` similar to the K-Lite Codec Pack manifests and when the `<version>` part was removed, it still detected it in `winget list` and I believe there was no `ProductCode` in that manifest back when I made a PR for it.

**Comment by denelon** [comment]
I'm hoping when we get the "AppsAndFeatures" schema bit implemented, this will solve most of these problems. There will likely be a ton of new PRs to change PublisherName and PackageName back to the "Marketing" values. The tougher one is figuring out how to handle the "Marketing" versions. I think JetBrains uses the Year in the marketing version, but the actual version is like 211.y.z or something like that.

**Comment by denelon** [comment]
>This is something that the winget-cli team have to solve, we're just the workaround people 🤷‍♂️
>cc @denelon Demitrius Nelon FTE feature idea
>Maybe we should have a Standard Manifest Metadata yaml file and version specific Metadata?

You are the rock stars who are making the best experiences possible!

We considered the idea of a standard file, and version specific files, but the complexity was pretty messy when considering things like major new features in newer versions, and deprecated or obsolete features in older versions. We also found examples of license changes and publisher name changes. It seemed better to keep the metadata for a version all in one location. It was a decision where there didn't seem to be "one best option", so we went with the one that appeared to be more correct at the expense of more files, and offered a deterministic way to figure out which file(s) needed to change or be copied.

**Pull request merged**
