### PR TITLE
New version: Genymobile.scrcpy version 2.4

### PR DESCRIPTION
**Pull request by coolplaylinbot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141826)

### CODE REVIEW

**Comment by CoolPlayLin** [comment]
Similar issues in #124475

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\scrcpy.exe returned exit code: -1073741515
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\scrcpy.exe returned exit code: -1073741515

(Automated response - build 857.)

**Comment by stephengillie** [comment]
Hi @coolplaylinbot,

> This PR's version number '2.4' has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 2.3.1, which has 3 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 869)

**Comment by CoolPlayLin** [comment]
no closing

**Comment by stephengillie** [comment]
Hi @coolplaylinbot,

> This PR's version number 2.4 has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 2.3.1, which has 3 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 870)

**Comment by stephengillie** [comment]
Verify: 
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
