### PR TITLE
Genymobile.scrcpy version 1.25

### LINKED ISSUE #4083: "Scrcpy"
# Package Requested

Manifest:

Fill out as much of the manifest as you can:

```YAML
Id: string # publisher.package format
Publisher:  Genymobile # the name of the publisher
Name: Scrcpy # the name of the application
Version: 1.16 # version numbering format
License:  Apache-2.0 License # the open source license or copyright
InstallerType: EXE (Standalone and depends on android platform cli tools) # enumeration of supported installer types (exe, msi, msix, inno, wix, nullsoft, appx)
Installers:
  - Arch: x86,x86_64 # enumeration of supported architectures
    Url: https://github.com/Genymobile/scrcpy/releases # path to download installation file
    Sha256: string # SHA256 calculated from installer
# ManifestVersion: 0.1.0
```

### PR DESCRIPTION
**Pull request by Fei1Yang**
This commit resolves #4083.

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/97894)

### CODE REVIEW

**Comment by Trenly** [comment]
This requires an update to the Validation Pipeline and MSFT is aware of it. Going to tag this as blocked so that it doesn’t get closed accidentally. It will be re-run once the pipelines are updated

**Comment by stephengillie** [comment]
This package is expecting arguments:
```
scrcpy 1.25 <https://github.com/Genymobile/scrcpy>
ERROR: Could not find any ADB device
ERROR: Server connection failed
```

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
