### PR TITLE
Update GIMP.GIMP to version `2.10.28` (from `2.10.24`)

### PR DESCRIPTION
**Pull request by mavenor**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/28154)

### CODE REVIEW

**Comment by EccentricHyphus37** [comment]
To anybody reading this thread, sorry about all the force pushes! 😬
They were primarily to cover up an embarrassing typographical mistake (I know, right?) in the manifest (_don't ask!_ 😂)

**Comment by EccentricHyphus37** [comment]
### Why I didn't do this with `wingetcreate`
Tried using the `update` subcommand, but that was insisting on creating a **multi-file** manifest, which I didn't want to submit, since all the previous versions have been **singletons**, and I'm a bit pedantic that way...

**Review by OfficialEsco — COMMENTED** [review]
> 
> ### Why I didn't do this with `wingetcreate`
> 
> Tried using the `update` subcommand, but that was insisting on creating a **multi-file** manifest, which I didn't want to submit, since all the previous versions have been **singletons**, and I'm a bit pedantic that way...

Well.. you see, we prefer Multi-Manifest because its easier to read, people can add more locales and the installer can support  multiple installers.

In this case i see /ALLUSERS which indicates this installer supports /CURRENTUSER, which you NEED a Multi-Manifest for.

Singletons are remains from ManifestVersion 0.0.1

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
Slapping a Requesting Changes on this so it doesn't get approved even tho nothing is technically wrong.
https://github.com/microsoft/winget-pkgs/pull/28154#pullrequestreview-759613048

**Comment by EccentricHyphus37** [comment]
@OfficialEsco thanks for being nice! 😄
I'm new to WinGet and I greatly appreciate it

**Pull request closed without merging**
