### PR TITLE
New version: XSplit.Broadcaster version 4.5.2406.1808

### PR DESCRIPTION
**Pull request by alcosml**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161294)

### CODE REVIEW

**Comment by alcosml** [comment]
What cause the failure in the 'Installation Validation'? The [log](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=591087&view=logs&j=68997d86-8ece-5ae8-3ac5-ccdbfa458731&t=b79910ce-dca5-5e27-ad7f-bd285eecb5a2&l=38) just says `Result: Failed` w/ no details. How do we get past this?

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 886.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
