### PR TITLE
DigiPen.NitronicRush(2012-12-21.2) version 2012.12.21.2

### PR DESCRIPTION
**Pull request by G0rocks**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14077)

### CODE REVIEW

**Comment by KaranKad** [comment]
I think not having version name for folder would be better.
e.g: `DigiPen.NitronicRush(2012-12-21.2)/2012.12.21.2/DigiPen.NitronicRush(2012-12-21.2).installer.yaml` should be `DigiPen.NitronicRush/2012.12.21.2/DigiPen.NitronicRush.installer.yaml` and anywhere else it's mentioned.

**Comment by G0rocks** [comment]
> 
> 
> I think not having version name for folder would be better.
> e.g: `DigiPen.NitronicRush(2012-12-21.2)/2012.12.21.2/DigiPen.NitronicRush(2012-12-21.2).installer.yaml` should be `DigiPen.NitronicRush/2012.12.21.2/DigiPen.NitronicRush.installer.yaml` and anywhere else it's mentioned.

Yeah @KaranKad, that makes sens. Will fix, wait a second. I was just excited to try using the wingetcreate tool. Had no clue how it would turn out on this side of things. Thanks for pointing that out.

**Comment by G0rocks** [comment]
All righty renamed the stuff, let's see how it goes this time

**Comment by KaranKad** [comment]
You will need to remove it from the manifest as well.
From `PackageIdentifier: DigiPen.NitronicRush(2012-12-21.2)` to `PackageIdentifier: DigiPen.NitronicRush` and
`PackageName: Nitronic Rush (2012-12-21 .2)` to `PackageName: Nitronic Rush`

**Comment by G0rocks** [comment]
Whoops, thanks 😅

**Pull request merged**
