### PR TITLE
Wolicheng.WoMicDriver version 1.6.0.0

### PR DESCRIPTION
**Pull request by AlexZorzi**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/18940)

### CODE REVIEW

**Comment by quhxl** [comment]
I don't think there is a silent installer for this app/driver.

**Comment by AlexZorzi** [comment]
@quhxl 
When I tried to install it gets succesfully installed but at the end of the setup it the program asks if the user wants to check for updates
And after that it quits with error 2

**Comment by quhxl** [comment]
I think that's enough. It's not completely silent.

**Comment by OfficialEsco** [comment]
image
This is actually why it fails, but this is a dependency that we can't install i believe, so this might have to go under not 100% unattended since as you said this also pops up
image

**Pull request closed without merging**
