### PR TITLE
TechNobo.TcNoAccountSwitcher version 4

### PR DESCRIPTION
**Pull request by Eddga**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/126209)

### CODE REVIEW

**Comment by Eddga** [comment]
This is the same program version as in #125068 but #125068 is missing some dependencies and also contains the wrong package version. Even though the release should have the version 5.0 2023-07-05 (which is the actual github release version) or something alike it installs as version 4 on Windows. This would lead to it never being the most current version when checked against with winget list --upgrade-available
I tried to submit this using the replace parameter. But that didn't work as expected (already opened #478).
Please remove/revert #125068 when merging this PR.

**Comment by stephengillie** [comment]
Hi @Eddiga,

This package appears to already be in the repository. Should the InstallerUrl be different? Currently its path includes the version number mentioned in the error.

**Comment by Eddga** [comment]
> Hi @Eddga,
> 
> This package appears to already be in the repository. Should the InstallerUrl be different? Currently its path includes the version number mentioned in the error.

Hi @stephengillie,
The InstallerURL is correct and yes the package IS already in the repository.
But the issue is that the app installs as version 4:
image
So it's a bug of the program using the wrong uninstall string: https://github.com/TCNOco/TcNo-Acc-Switcher/issues/355
Therefore the existing manifest needs to be replaced. Otherwise the app will always be detected as update available.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Sorry for the delay.

**Comment by Eddga** [comment]
> Sorry for the delay.

No worries, mate! Thanks a lot for all the time and effort you put in this project! 🙂👍

**Pull request merged**
