### PR TITLE
Metadata: ojdkbuild.openjdk.14.jdk version 14.0.1.1

### PR DESCRIPTION
**Pull request by russellbanks**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

This PR is to make the package naming consistent with the other ojdkbuild.openjdk packages.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/62959)

### CODE REVIEW

**Review by OfficialEsco — COMMENTED** [review]
The DisplayName is technically already correct, however it might not matter cuz IIRC the wildcard requires a space

```

--> Installing WinGet
Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.

--> Configuring Winget
Admin setting enabled.

--> Installing the Manifest 14.0.1.1

Found ojdkbuild OpenJDK 14 [ojdkbuild.openjdk.14.jdk] Version 14.0.1.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/ojdkbuild/ojdkbuild/releases/download/java-14-openjdk-14.0.1.7-0/java-14-openjdk-14.0.1.7-1.windows.ojdkbuild.x86_64.msi
  ██████████████████████████████   247 MB /  247 MB
Successfully verified installer hash
Starting package install...
Successfully installed

--> Refreshing environment variables

--> Comparing ARP Entries

DisplayName                DisplayVersion Publisher                     ProductCode
-----------                -------------- ---------                     -----------
OpenJDK 14.0.1-1-ojdkbuild 14.0.1.1       ojdkbuild open-source project {C1CB3F32-5E70-48F0-896F-05594A937FDA}
```

**Review by Trenly — CHANGES_REQUESTED** [review]

**Comment by russellbanks** [comment]
My justfication for this was if you do `winget search ojdkbuild`, half of the results have the name of `ojdkbuild OpenJDK (version)`, whereas the others just have `OpenJDK (version)`, meaning they're inconsistent. I thought adding the `ojdkbuild` onto this would be better than omitting `ojdkbuild` on others because this distinguishes the package from other OpenJDK distributions as being built by ojdkbuild (in the name, not just by id).

WindowsTerminal_DSqfwcWzMB

**Comment by OfficialEsco** [comment]
AFAIK IIRC from updating the Packages the inconsistency is from the Developer

**Comment by russellbanks** [comment]
> AFAIK IIRC from updating the Packages the inconsistency is from the Developer

Could this not be updated in the manifest though, like #62891?

**Comment by OfficialEsco** [comment]
That PR is actually correct, so it seems like they changed DisplayName in version 16.32.15 and slipped past validation in #62859
```
Enter a pull request number: #62891

Manifest validation succeeded.
Found Azul Zulu JDK 16 [Azul.Zulu.16] Version 16.32.15
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://cdn.azul.com/zulu/bin/zulu16.32.15-ca-jdk16.0.2-win_x64.msi
  ██████████████████████████████   175 MB /  175 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Name          : Azul Zulu JDK 16.32.15 (16.0.2), 64-bit
Publisher     : Azul Systems, Inc.
Version       : 16.32.15
ProductCode   : {C8A8B7C6-66D5-4D71-AD28-D4666ADBCC70}
Registry Path : Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{C8A8B7C6-66D5-4D71-AD28-D4666ADBCC70}
Uninstall     : winget uninstall --id "{C8A8B7C6-66D5-4D71-AD28-D4666ADBCC70}"

Press any key to continue . . .
```

**Pull request closed without merging**
