### PR TITLE
Freelancer.Desktop version 2.4.0

### LINKED ISSUE #69022: [Package Request]: Freelancer Desktop App
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Freelancer
Publisher Url: https://www.freelancer.com/
Package Name: freelancer-desktop-app
Description: Track hours worked and get paid seamlessly building trust every minute of your time
Package Version: 
Installer URL: https://s3.amazonaws.com/desktop-production.freelancer.com/latest/installers/freelancer-desktop-app_windows-installer.exe

Current Package Identifier (for new versions):

### PR DESCRIPTION
**Pull request by infinitepower18**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

Closes #69022

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/78652)

### CODE REVIEW

**Comment by infinitepower18** [comment]
You can see the download points to AWS

[screen-capture.webm](https://user-images.githubusercontent.com/44692189/188508105-65bcc795-d51c-4ba3-a521-483251747974.webm)

**Review by ItzLevvie — APPROVED** [review]

**Comment by infinitepower18** [comment]
Already gave evidence a week ago... https://github.com/microsoft/winget-pkgs/pull/78652#issuecomment-1237428721

**Comment by OfficialEsco** [comment]
@denelon task for Monday, these need a better follow up

**Comment by JohnMcPMS** [comment]
@msftbot merge please

**Review by JohnMcPMS — APPROVED** [review]

**Pull request merged**
