### PR TITLE
New version: AIMP.AIMP version 5.30.2563

### PR DESCRIPTION
**Pull request by soredake**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/169512)

### CODE REVIEW

**Comment by stephengillie** [comment]
> 8/27/2024 10:47:01 AM
Installer Verification Analysis Context Information: 
Installer https://aimp.ru/files/windows/builds/aimp_5.30.2563_w64.exe
Scan request id: '994be411-80c7-4573-8958-a3240803cd03'
Error information: BlockingDetectionFound
Installer https://aimp.ru/files/windows/builds/aimp_5.30.2563_w32.exe
Scan request id: '1db3505b-5555-4ab1-88b6-319a5c6f3ba0'
Error information: BlockingDetectionFound

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Pull request closed without merging**
