### PR TITLE
Update metadata: oxygendioxide.Deepvocal-Hitsuboku-Kumi-CHN-dv1 version 1.1.0

### LINKED ISSUE #133393: [Update Request]: oxygendioxide.Deepvocal-Hitsuboku-Kumi-CHN-dv1 and oxygendioxide.Deepvocal-Hitsuboku-Kumi-CHN
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

oxygendioxide.Deepvocal-Hitsuboku-Kumi-CHN-dv1 and oxygendioxide.Deepvocal-Hitsuboku-Kumi-CHN

### Package Version

1.1.0

### Please describe the changes you would like to see

DeepVocal has since been added to Winget, so it would be best to add this to the metadata:

```
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Boxstar.DeepVocal
```

### PR DESCRIPTION
**Pull request by Dragon1573**
## Description

- Add "Boxstar.DeepVocal" as PackageDependencies
- Resolve #133393

## Checks

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/133429)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-09 07:50:03.168 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000 2024-01-09 07:50:03.169 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFA5341A465: (caller: 00007FFA5341AD01) Exception(1) tid(18f8) 80190193 Forbidden (403). 2024-01-09 07:52:51.477 [FAIL] Installer failed security check. Url: https://github.com/oxygen-dioxide/hitsuboku-kumi-chn-deepvocal/releases/download/v1.1.0/Hitsuboku-Kumi-Chinese-deepvocal-1.1.0-dvtb1.exe Result: 0x80004005

(Automated response - build 541.)

**Comment by stephengillie** [comment]
Hi @Dragon1573,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 541.)

**Comment by Dragon1573** [comment]
Try to validate the manifest in GitHub Workflows. It's able to install unattendedly. See [Dragon1573/winget-test Validation Pipeline #7](https://github.com/Dragon1573/winget-test/actions/runs/7464301113/job/20310980888)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-10 09:18:12.022 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000 2024-01-10 09:18:12.023 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFB6DAFA465: (caller: 00007FFB6DAFAD01) Exception(1) tid(12e4) 80190193 Forbidden (403). 2024-01-10 09:20:34.697 [FAIL] Installer failed security check. Url: https://github.com/oxygen-dioxide/hitsuboku-kumi-chn-deepvocal/releases/download/v1.1.0/Hitsuboku-Kumi-Chinese-deepvocal-1.1.0-dvtb1.exe Result: 0x80004005

(Automated response - build 549.)

**Comment by Dragon1573** [comment]
It's wierd ... 😕

How previous version of the manifests passed the pipeline and have been approved? I can't get it ...

- Related https://github.com/microsoft/winget-pkgs/pull/115971

**Comment by Dragon1573** [comment]
Due to current state of this pull request, both moderators, contributors and I can't handle failures in Azure Pipelines.

This pull request is labeled with https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue and https://github.com/microsoft/winget-pkgs/labels/Validation-Defender-Error, so maybe it's time to stop investigating on this problem and close the pull request without being merged.

**Pull request closed without merging**
