### PR TITLE
Add Architecture x86: chrdavis.smartrename version 1.1.0

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/20714)

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
image
Have you gone mad? It is successfully validated. 😡

**Comment by OfficialEsco** [comment]
`Manifest Error: Schema validation failed. Error context: <root>[Installers] Description: Array should contain no more than 1 elements. Error context: <root> Description: Failed to validate against schema associated with property name 'Installers'.  File: chrdavis.smartrename.yaml`

You need a multi manifest to have multiple installers

**Comment by vedantmgoyal2009** [comment]
Okay, but in the screenshot, it is successfully validated.

**Comment by OfficialEsco** [comment]
> Okay, but in the screenshot, it is successfully validated.

So? The Singleton Schema only allows one Installer. The bot and `winget validate` is 2 different validations. `winget validate` check if the metadata fields are ok and `winget install` checks if the installer worked, that does not mean you will pass validation.

**Comment by vedantmgoyal2009** [comment]
Ok, is there any way to convert it directly or will I have to start from scratch?

**Comment by OfficialEsco** [comment]
Just use YamlCreate since it will add more information, also add the ProductCode when prompted.
Try to use this version #20359 since it fixes some Yaml breaking issues.

**Comment by vedantmgoyal2009** [comment]
Thanks, I will make changes.

**Comment by vedantmgoyal2009** [comment]
The new script is not working.
image

**Comment by OfficialEsco** [comment]
> The new script is not working.

wot, i believe it says you're missing a `}`
Copypaste from here: https://raw.githubusercontent.com/microsoft/winget-pkgs/5b946af61b187b169df055f54600d4795367a588/Tools/YamlCreate.ps1

**Comment by vedantmgoyal2009** [comment]
Done.

**Comment by vedantmgoyal2009** [comment]
Now, is it fine?

**Comment by OfficialEsco** [comment]
Perfect!

**Comment by OfficialEsco** [comment]
@palenshus once again added the wrong label...

**Comment by vedantmgoyal2009** [comment]
Please merge this PR.

**Review by palenshus — APPROVED** [review]

**Pull request merged**
