### PR TITLE
Create the April 2021 PSU installer for Microsoft build of OpenJDK

### PR DESCRIPTION
**Pull request by d3r3kk**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/11369)

### CODE REVIEW

**Comment by d3r3kk** [comment]
@brunoborges please have a look here as well.

**Comment by d3r3kk** [comment]
I think I may be missing some information. The Manifest Content Validation step tells me that the packageUrl is coming back with "Forbidden" for the URL `https://www.microsoft.com/openjdk`. I can't seem to repro that result locally though, either manually in my browser or by running `winget -validate ...` on my manifest changes.

**Comment by d3r3kk** [comment]
I think I may be missing some information. The Manifest Content Validation step tells me that the packageUrl is coming back with "Forbidden" for the URL `https://microsoft.com/openjdk`

**Comment by d3r3kk** [comment]
(Just restarting my PR to see if there was a transient error, not sure if that works 😀)

**Comment by d3r3kk** [comment]
@denelon any tips on how I can discover what the trouble might be here. The log I am currently being shown is lacking any _actionable_ detail. For instance, can I run this validation step locally to see if there is something I can discover myself?

**Comment by denelon** [comment]
@d3r3kk we were having some issues with the validation pipeline. I don't know if the error is related to that or not. That's why I triggered another build.

**Comment by denelon** [comment]
When I looked at the build output, I just see a "Binary validation failed" on the last URL.

**Comment by d3r3kk** [comment]
Yes I see that as well. And I would love to fix it but I don't know what the source of the problem might be. Is there any way I can see the tool that is making that determination so I can try and deduce where the trouble is?

**Comment by zachcarp** [comment]
@d3r3kk - When it says Internal-Error it means our process encountered an error that probably didn't have anything to do with your manifest. In those cases, you sadly need to wait for a dev to figure out why it failed and take action on our end.

**Pull request merged**
