### PR TITLE
Add CCEnhancer

### PR DESCRIPTION
**Pull request by ath0mas**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1279)

### CODE REVIEW

**Comment by ath0mas** [comment]
Sha256 and URL are correct and a local `winget install -m manifests\SingularLabs\CCEnhancer\4.5.6.yaml` succeeds without any Windows Defender alert ; stange :/

**Comment by SoftCreatR** [comment]
@ath0mas Try that url instead:

`https://www.winget.it/dl/2a0bc49873bffacd1681ede3abcb3e61936524f132be5684e7a474cc124a5c54/https%3A%2F%2Fsingularlabs.com%2Fdownload%2F13238%2F?&fn=ccenhancer-install-4.5.6.exe`

**Comment by ath0mas** [comment]
@SoftCreatR what do you mean? I don't have a Windows Defender alert either with the installer downloaded with the url you suggest

**Comment by SoftCreatR** [comment]
There's no Windows Defender alert.

**Comment by SoftCreatR** [comment]
@ath0mas Same issue as before. Try the URL I posted above and see, if that works (it should).

**Comment by ath0mas** [comment]
@SoftCreatR Changing the URL in the manifest file?

**Comment by SoftCreatR** [comment]
> @SoftCreatR Changing the URL in the manifest file?

Yeah.

**Comment by ath0mas** [comment]
@SoftCreatR what is the principle of this winget.it/dl.. prefixed url ?

**Comment by SoftCreatR** [comment]
> @SoftCreatR what is the principle of this winget.it/dl.. prefixed url ?

https://github.com/microsoft/winget-pkgs/issues/1515#issuecomment-639479851

**Comment by SoftCreatR** [comment]
Hooray 🎉

**Comment by ath0mas** [comment]
🙃 I did not understood the whole thing here ^^
ok for a short term solution... not sure for other PR with the same problem or future versions of this package

**Comment by SoftCreatR** [comment]
> 🙃 I did not understood the whole thing here ^^
> ok for a short term solution... not sure for other PR with the same problem or future versions of this package

I'm positive, that the problems have been fixed until the next version of this application has been released. If not, i can easily generate an updated link :)

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
