### PR TITLE
New version: astral-sh.ruff version 0.3.3

### PR DESCRIPTION
**Pull request by frazar**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/145072)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-18 05:48:52.337 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFC6206C11F: (caller: 00007FFC61DF8D6F) LogHr(1) tid(1434) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFC61F72B08: (caller: 00007FFC6201BC20) Exception(1) tid(1434) 8A15005E ] 
> 2024-03-18 05:48:52.337 [REPO] Failed to open available source: msstore
> 2024-03-18 05:48:54.317 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFC61F72B08: (caller: 00007FFC6201BC20) Exception(1) tid(1434) 8A15005E 
> 2024-03-18 05:49:00.721 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFC4BA6C11F: (caller: 00007FFC4B7F8D6F) LogHr(1) tid(12b0) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFC4B972B08: (caller: 00007FFC4BA1BC20) Exception(1) tid(12b0) 8A15005E ] 
> 2024-03-18 05:49:00.721 [REPO] Failed to open available source: msstore
> 2024-03-18 05:49:16.484 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.3.3/ruff-0.3.3-x86_64-pc-windows-msvc.zip Result: 0x80004005
> 2024-03-18 05:48:32.256 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!5489535B: (caller: 54791A80) LogHr(1) tid(1f8c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!548DB5DD: (caller: 549712BF) Exception(1) tid(1f8c) 8A15005E ] 
> 2024-03-18 05:48:32.256 [REPO] Failed to open available source: msstore
> 2024-03-18 05:48:34.219 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!548DB5DD: (caller: 549712BF) Exception(1) tid(1f8c) 8A15005E 
> 2024-03-18 05:48:40.433 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!7927535B: (caller: 79171A80) LogHr(1) tid(1734) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!792BB5DD: (caller: 793512BF) Exception(1) tid(1734) 8A15005E ] 
> 2024-03-18 05:48:40.433 [REPO] Failed to open available source: msstore
> 2024-03-18 05:48:56.085 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.3.3/ruff-0.3.3-i686-pc-windows-msvc.zip Result: 0x80004005

(Automated response - build 870.)

**Comment by frazar** [comment]
Hi @mdanish-kh, it seems I am getting a similar error as for #143774 . Is there a way to solve this for all future submissions?

**Comment by mdanish-kh** [comment]
From the [official docs](https://learn.microsoft.com/en-us/windows/package-manager/package/repository#validation-process):



Validation-Defender-Error | During dynamic testing, Microsoft Defender reported a problem. To  reproduce this problem, install your application, then run a Microsoft  Defender full scan. If you can reproduce the problem, fix the binary or [submit it for analysis](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives?view=o365-worldwide#part-4-submit-a-file-for-analysis) for false positive assistance. If you are unable to reproduce the  problem, add a comment to get the Windows Package Manager engineers to  investigate.
-- | --

Usually with new apps, it may take some time to have MS Defender database updated. In many cases, we need to just wait it out (normally 18 hours) and try a validation run again. If you still experience problems, the publisher will need to follow the above steps

**Comment by mdanish-kh** [comment]
cc @stephengillie if he can add more context since I have limited knowledge about this

**Comment by stephengillie** [comment]
Hi @frazar,

Unfortunately, I also have limited knowledge of the process. I have heard that the Defender team might install new packages on a VM, to ensure that there is no "time-release malware" at play. Some packages might fail for weeks before finally passing.

**Comment by frazar** [comment]
@stephengillie @mdanish-kh Thank you very much for your explanations!

**Comment by stephengillie** [comment]
Hi @frazar,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 871.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-20 03:12:12.272 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!69B0535B: (caller: 69A01A80) LogHr(1) tid(fb8) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!69B4B5DD: (caller: 69BE12BF) Exception(1) tid(fb8) 8A15005E ] 
> 2024-03-20 03:12:12.272 [REPO] Failed to open available source: msstore
> 2024-03-20 03:12:15.328 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!69B4B5DD: (caller: 69BE12BF) Exception(1) tid(fb8) 8A15005E 
> 2024-03-20 03:12:24.346 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!5616535B: (caller: 56061A80) LogHr(1) tid(1510) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!561AB5DD: (caller: 562412BF) Exception(1) tid(1510) 8A15005E ] 
> 2024-03-20 03:12:24.346 [REPO] Failed to open available source: msstore
> 2024-03-20 03:12:43.488 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.3.3/ruff-0.3.3-i686-pc-windows-msvc.zip Result: 0x80004005

(Automated response - build 871.)

**Comment by stephengillie** [comment]
Hi @frazar,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 871.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-21 10:33:52.283 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFBB70EC11F: (caller: 00007FFBB6E78D6F) LogHr(1) tid(c2c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFBB6FF2B08: (caller: 00007FFBB709BC20) Exception(1) tid(c2c) 8A15005E ] 
> 2024-03-21 10:33:52.283 [REPO] Failed to open available source: msstore
> 2024-03-21 10:33:59.888 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFB9C25C11F: (caller: 00007FFB9BFE8D6F) LogHr(1) tid(c70) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFB9C162B08: (caller: 00007FFB9C20BC20) Exception(1) tid(c70) 8A15005E ] 
> 2024-03-21 10:33:59.888 [REPO] Failed to open available source: msstore
> 2024-03-21 10:34:15.099 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.3.3/ruff-0.3.3-x86_64-pc-windows-msvc.zip Result: 0x80004005
> 2024-03-21 10:33:01.520 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!68E8535B: (caller: 68D81A80) LogHr(1) tid(16b8) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!68ECB5DD: (caller: 68F612BF) Exception(1) tid(16b8) 8A15005E ] 
> 2024-03-21 10:33:01.520 [REPO] Failed to open available source: msstore
> 2024-03-21 10:33:08.793 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!54B9535B: (caller: 54A91A80) LogHr(1) tid(1e5c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!54BDB5DD: (caller: 54C712BF) Exception(1) tid(1e5c) 8A15005E ] 
> 2024-03-21 10:33:08.793 [REPO] Failed to open available source: msstore
> 2024-03-21 10:33:22.590 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.3.3/ruff-0.3.3-i686-pc-windows-msvc.zip Result: 0x80004005

(Automated response - build 871.)

**Comment by stephengillie** [comment]
Hi @frazar,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 871.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-22 08:33:02.075 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFE7A56C11F: (caller: 00007FFE7A2F8D6F) LogHr(1) tid(84c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFE7A472B08: (caller: 00007FFE7A51BC20) Exception(1) tid(84c) 8A15005E ] 
> 2024-03-22 08:33:02.075 [REPO] Failed to open available source: msstore
> 2024-03-22 08:33:10.094 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFE600CC11F: (caller: 00007FFE5FE58D6F) LogHr(1) tid(da4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFE5FFD2B08: (caller: 00007FFE6007BC20) Exception(1) tid(da4) 8A15005E ] 
> 2024-03-22 08:33:10.094 [REPO] Failed to open available source: msstore
> 2024-03-22 08:33:25.162 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.3.3/ruff-0.3.3-x86_64-pc-windows-msvc.zip Result: 0x80004005
> 2024-03-22 08:32:36.414 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!67B1535B: (caller: 67A11A80) LogHr(1) tid(9c8) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!67B5B5DD: (caller: 67BF12BF) Exception(1) tid(9c8) 8A15005E ] 
> 2024-03-22 08:32:36.414 [REPO] Failed to open available source: msstore
> 2024-03-22 08:32:43.421 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!5551535B: (caller: 55411A80) LogHr(1) tid(1d6c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!5555B5DD: (caller: 555F12BF) Exception(1) tid(1d6c) 8A15005E ] 
> 2024-03-22 08:32:43.421 [REPO] Failed to open available source: msstore
> 2024-03-22 08:32:57.597 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.3.3/ruff-0.3.3-i686-pc-windows-msvc.zip Result: 0x80004005

(Automated response - build 871.)

**Review by mdanish-kh — APPROVED** [review]

**Pull request merged**
