### PR TITLE
Fix GitHubDesktop installer url

### PR DESCRIPTION
**Pull request by notyusufkhalifa**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/165638)

### CODE REVIEW

**Comment by YusufKhalifadev** [comment]
@microsoft-github-policy-service agree

**Comment by Trenly** [comment]
@YusufKhalifadev - Only one Manifest can be modified per PR. You will need a separate PR for each version of GitHubDesktop that needs to be updated

**Comment by YusufKhalifadev** [comment]
Why is this it's so dumb to create a separate PR for 42 manifest it's weird, why can't it just be merged

**Comment by Trenly** [comment]
> Why is this it's so dumb to create a separate PR for 42 manifest it's weird, why can't it just be merged

Because of the way manifests are published, if multiple manifests are changed in a single PR then the packaging of the index database will fail

**Comment by YusufKhalifadev** [comment]
@Trenly  Ok then i'll change the manifest of the latest version only

**Pull request closed without merging**
