### PR TITLE
SomePythonThings.ElevenClock version 1.2

### PR DESCRIPTION
**Pull request by marticliment**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/29314)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Package already exists due to automation.

**Comment by martinet101** [comment]
what is automation?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
>what is automation?

There's now automation to automatically update packages delivered through GitHub Releases.

Source Code: https://github.com/vedantmgoyal2009/winget-pkgs-automation

The PR was https://github.com/microsoft/winget-pkgs/pull/29376 for this package.

**Comment by martinet101** [comment]
@ItzLevvie, thank you, now I understand why my PRs were getting duplicated. Closing this now

**Pull request closed without merging**
