### PR TITLE
New package: tsukinaha.Tsukimi version 0.6.6

### PR DESCRIPTION
**Pull request by DuckDuckStudio**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? -- #161389

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

屏幕截图 2024-07-04 063353

> [!NOTE]
> Main program: bin\tsukimi.exe

Logs:
- [validate manifest - tsukinaha.Tsukimi version 0.6.6.log](https://github.com/user-attachments/files/16091507/validate.manifest.-.tsukinaha.Tsukimi.version.0.6.6.log)
- [test install - tsukinaha.Tsukimi version 0.6.6.log](https://github.com/user-attachments/files/16091677/test.install.-.tsukinaha.Tsukimi.version.0.6.6.log)
- [test uninstall - tsukinaha.Tsukimi version 0.6.6.log](https://github.com/user-attachments/files/16091679/teset.uninstall.-.tsukinaha.Tsukimi.version.0.6.6.log) - Failed (找不到与输入条件匹配的已安装程序包。)

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161423)

### CODE REVIEW

**Comment by DuckDuckStudio** [comment]
I've tested the installation package, and it installs correctly. I've also provided the relevant logs.
@stephengillie Can you check it again?

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Verify:
image

**Comment by DuckDuckStudio** [comment]
It seems that the relevant issues should be closed.

**Pull request merged**
