### PR TITLE
New Version: TexasInstruments.TI-Nspire v5.3.2

### PR DESCRIPTION
**Pull request by Trenly**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

Closes #28752

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/29088)

### CODE REVIEW

**Review by denelon — DISMISSED** [review]

**Comment by Trenly** [comment]
@denelon I see you've approved; Are the other labels preventing the automatic merge, or is this something that needs a waiver?

**Comment by denelon** [comment]
@Trenly is there a better URL for this? I didn't see the Domain label when I approved it. Yes, it will need a waiver with this URL.

**Comment by Trenly** [comment]
> @Trenly is there a better URL for this? I didn't see the Domain label when I approved it. Yes, it will need a waiver with this URL.

I looked and it seems like every URL that I find ultimately redirects back to that one

**Comment by denelon** [comment]
Redirects should be fine. Is there one from ti.com?

**Comment by Trenly** [comment]
> Redirects should be fine. Is there one from ti.com?

I do see one from TI. I'll update the manifest in just a moment

**Review by jedieaston — APPROVED** [review]

**Pull request merged**
