### PR TITLE
Add manifest for Google Chrome 89.0.4389.90

### PR DESCRIPTION
**Pull request by dumontirou**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [X] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/8672)

### CODE REVIEW

**Comment by dumontirou** [comment]
Hello,
Validation checks are failing for an unknown reason. Would it be possible to check why ?
I didn't meet any problem with the **winget validate** nor the **winget install -m** tests

**Comment by lychichem** [comment]
> Hello,
> @KevinLaMS Validation checks are failing for an unknown reason. Would it be possible to check why ?
> I didn't meet any problem with the **winget validate** nor the **winget install -m** tests

Google Chrome is automatically matainced by wingetbot now, although the version number is incorrect. You don't need to manually push, just believe the bot.

**Comment by dumontirou** [comment]
> > Hello,
> > @KevinLaMS Validation checks are failing for an unknown reason. Would it be possible to check why ?
> > I didn't meet any problem with the **winget validate** nor the **winget install -m** tests
> 
> Google Chrome is automatically matainced by wingetbot now, although the version number is incorrect. You don't need to manually push, just believe the bot.

Oh ok, thank you, I'll close this request.

**Comment by jedieaston** [comment]
@dumontirou you'll have to close it yourself.

**Pull request closed without merging**
