### PR TITLE
Fix Bricklink.Studio package

### PR DESCRIPTION
**Pull request by CanePlayz**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/121954)

### CODE REVIEW

**Comment by CanePlayz** [comment]
Uhm what is this error?

**Comment by CanePlayz** [comment]
Why is it not starting the validation pipeline?

**Comment by CanePlayz** [comment]
Unfortunate haha

**Comment by CanePlayz** [comment]
@stephengillie Sorry for tagging you, but it doesn't assign anyone. I'm quite confused: What is this file, do we need it and why does the pipeline not start?

**Comment by stephengillie** [comment]
Hi @CanePlayz,

The .validation file holds pipeline data including waivers. It's meant to only be modified by the system. 

image

**Comment by CanePlayz** [comment]
> Hi @CanePlayz,
> 
> The .validation file holds pipeline data including waivers. It's meant to only be modified by the system.

Ok thanks, I will add it back then. But why is the pipeline not starting?

**Comment by stephengillie** [comment]
The file shows as being removed and readded, both of which aren't allowed. Can you fully revert the file? 
image

**Comment by CanePlayz** [comment]
> The file shows as being removed and readded, both of which aren't allowed. Can you fully revert the file? image

I'mma just open a new PR I guess

**Pull request closed without merging**
