### PR TITLE
Delete duplicated CrystalDiskInfo

### PR DESCRIPTION
**Pull request by hinaloe**
CrystalDiskInfo is duplicated in [CrystalDewWorld](https://github.com/microsoft/winget-pkgs/blob/4ca9eb06dd0dadd52a3d7ee73ce7e7a9f2d90c41/manifests/CrystalDewWorld/CrystalDiskInfo/8.5.2.yaml) and [hiyohiyo](https://github.com/microsoft/winget-pkgs/blob/4ca9eb06dd0dadd52a3d7ee73ce7e7a9f2d90c41/manifests/hiyohiyo/CrystalDiskInfo/8.5.2.yaml). 

They point to the exact same thing, CrystalDewWorld would be a better namespace.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1315)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
Seems reasonable.  @dstutemann are you comfortable with this since it appears you created this manifest?

**Comment by dstutemann** [comment]
I'm fine with it. You may merge the changes.
I forgot to pull before creating my branch so I missed @hinaloe 's change. Sorry

I'm not sure wether we should add ```/norestart``` to the your manifest...

**Comment by hinaloe** [comment]
@KevinLaMS Could you merge?

**Comment by OfficialEsco** [comment]
Apparently your PR got forgotten and i didn't see it before doing a PR, it got deleted in #1864

**Comment by hinaloe** [comment]
Thank you for telling @OfficialEsco, It was correctly deleted in #1864.

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
