### PR TITLE
VMPlex.VMPlex version 1.0.0.11

### PR DESCRIPTION
**Pull request by jxy-s**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/102646)

### CODE REVIEW

**Comment by jxy-s** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Manual Validation failed with:
> 12:25:02 PM: Application: VMPlex.exe 
> CoreCLR Version: 7.0.423.11508 
> .NET Version: 7.0.4 
> Description: The process was terminated due to an unhandled exception. 
> Exception Info: System.Management.ManagementException: Invalid namespace
>    at System.Management.ThreadDispatch.Start()
>    at System.Management.ManagementScope.Initialize()
>    at System.Management.ManagementScope.Connect()
>    at EasyWMI.WmiScope..ctor(String nameSpace)
>    at VMPlex.App.CheckCapability()
>    at VMPlex.App.OnStartup(StartupEventArgs e)
>    at System.Windows.Application.<.ctor>b__1_0(Object unused)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Windows.Threading.DispatcherOperation.Invoke()
>    at System.Windows.Threading.Dispatcher.ProcessQueue()
>    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    at System.Windows.Application.RunDispatcher(Object ignore)
>    at System.Windows.Application.RunInternal(Window window)
>    at VMPlex.App.Main()

**Comment by stephengillie** [comment]
Hi @jxy-s,

The application installed normally, but errored when launched in a Windows 11 VM.

**Comment by jxy-s** [comment]
@stephengillie the program requires that Hyper-V is enabled and available on the system. It looks like the exception is occurring since the `IMsvm_VirtualSystemManagementService` likely not present on the system:
https://github.com/0xf005ba11/vmplex-ws/blob/main/VMPlex/App.xaml.cs#L34

In a future release, I can add an exception handlers in that block and show a message to users.

**Comment by jxy-s** [comment]
@stephengillie we merged this fix to handle this case: https://github.com/0xf005ba11/vmplex-ws/pull/52

What are the next steps? Is it possible to have you manually validate using a machine with Hyper-V enabled?

**Comment by jxy-s** [comment]
@stephengillie why was the dependencies label added? The project has no dependencies. Hyper-V is a Windows Feature shipped with the operating system. The users need to enable it before using VMPlex.  

image

**Comment by jxy-s** [comment]
It's not specifically necessary for VMPlex to be installed or uninstalled from the machine. Users of this package will have the competency to understand that the underlying virtualization technically is required for the front end.

Installation and uninstallation of the VMPlex package is not affected by the presence of Hyper-V.

Can we push this release through? Or do we need to resubmit with the patch above?

**Comment by jxy-s** [comment]
Since this has gone stale, I will resubmit with the next release containing the aforementioned clarification for users.

**Pull request closed without merging**
