### PR TITLE
First request to add CIB pdf brewer (3.4.1)

### PR DESCRIPTION
**Pull request by pdfbrewer**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/4355)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
This app will not install silently unless a license is available

**Comment by pdfbrewer** [comment]
> 
> 
> This app will not install silently unless a license is available

@KevinLaMS thank you for your time. Would it be possible to submit it without silent installation? If not, would it be possible to only submit silent installation with progress? Current submission will not work, winget still feeds silent parameters to the setup.

**Comment by JanPokorny** [comment]
@pdfbrewer `winget` requires that the installers finish autonomously (meaning that a window can appear, but it can't require any input), which is usually what "silent mode" means. Since you seem to be the author of the app, I advise you to fix your installer's silent mode so it actually installs without user interaction.

**Comment by pdfbrewer** [comment]
> 
> 
> @pdfbrewer `winget` requires that the installers finish autonomously (meaning that a window can appear, but it can't require any input), which is usually what "silent mode" means. Since you seem to be the author of the app, I advise you to fix your installer's silent mode so it actually installs without user interaction.

OK I see, thank you for your reply.

**Pull request closed without merging**
