### PR TITLE
New version: Cisco.CiscoWebexMeetings version 42.2.2.33

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/43870)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by o-l-a-v** [comment]
This package when installed silently:

* ```Upgrade``` does not work, must use ```install```.
* Adds browser extension (should be disabled as default behavior if possible IMO).
* Starts after successfull install.

**Comment by OfficialEsco** [comment]
> upgrade does not work, must use install.

```
PS M:\> winget install Cisco.CiscoWebexMeetings -v 42.1.3.19
Found Cisco Webex Meetings [Cisco.CiscoWebexMeetings] Version 42.1.3.19
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://akamaicdn.webex.com/client/WBXclient-42.1.3-19/webexapp.msi
  ██████████████████████████████   151 MB /  151 MB
Successfully verified installer hash
Starting package install...
Successfully installed

PS M:\> winget upgrade Cisco.CiscoWebexMeetings
Found Cisco Webex Meetings [Cisco.CiscoWebexMeetings] Version 42.2.2.33
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://akamaicdn.webex.com/client/WBXclient-42.2.2-33/webexapp.msi
  ██████████████████████████████   159 MB /  159 MB
Successfully verified installer hash
Starting package install...
Successfully installed

PS M:\> winget list
Name                                        Id                                                  Version           Source
-------------------------------------------------------------------------------------------------------------------------
Cisco Webex Meetings                        Cisco.CiscoWebexMeetings                            42.2.2.33         winget
```
Works like a charm

> Starts after successfull install.

```
PS M:\> winget install Cisco.CiscoWebexMeetings --silent
Found Cisco Webex Meetings [Cisco.CiscoWebexMeetings] Version 42.2.2.33
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://akamaicdn.webex.com/client/WBXclient-42.2.2-33/webexapp.msi
  ██████████████████████████████   159 MB /  159 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

use the --silent switch to specify completely silent

> Adds browser extension (should be disabled as default behavior if possible IMO).

There is no button for this setting in the interactive installer, and the webpage you linked does not say anything about the extension

**Comment by o-l-a-v** [comment]
@OfficialEsco 

Hmm. What winget version and OS?

I used "--silent" both when "upgrade" failed, and when "install" opened the app afterwards.

Will try to reproduce and give you the details.

**Comment by OfficialEsco** [comment]
> Hmm. What winget version and OS?

winget [1.2.3411-preview](https://github.com/microsoft/winget-cli/releases/tag/v1.2.3411-preview) and Windows 11 22000.493

> I used "--silent" both when "upgrade" failed, and when "install" opened the app afterwards.
> 
> Will try to reproduce and give you the details.

Check the logs at `%LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir` + the ExitCode would be nice to know

**Comment by OfficialEsco** [comment]
`2022-02-09 10:24:35.461 [CLI ] Installer [X64,Wix,Machine,] not applicable: Installer scope does not matched currently installed scope: Machine != User`

> Edit: What's probably relevant here is that I installed webex from a web meeting I was joining into. Which probably installs in SYSTEM context. While this one is USER context.

Probably not the best explanation but its the other way around, it says winget found a machine wide installer but the installed package is installed for current user

**Pull request merged**
