### PR TITLE
BitGuardian.BitDriverUpdater version 1.0.0.7

### PR DESCRIPTION
**Pull request by Meteor24**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15822)

### CODE REVIEW

**Comment by KaranKad** [comment]
ShortDescription: Bit Driver Updater helps computers to detect defective drivers, install driver updates when needed, and fix other driver-related issues.

**Comment by Meteor24** [comment]
@KaranKad is the manifest still okay with  the short description i have set? If it isn't how can I change without resubmitting the PR

**Comment by KaranKad** [comment]
Changing ShortDescription won't lead to resubmission.

**Comment by Meteor24** [comment]
ok. where do i change the short description in the pull request?

**Comment by Meteor24** [comment]
never mind i figured it out

**Comment by Meteor24** [comment]
i have commited the change. you can check it if you want

**Comment by KaranKad** [comment]
Yes, it's ok now.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
