### PR TITLE
New version: CrystalDewWorld.CrystalDiskMark version 8.0.5

### LINKED ISSUE #140927: [Update Request]: Update CrystalDewWorld.CrystalDiskMark to 8.0.5
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

CrystalDewWorld.CrystalDiskMark

### Package Version

8.0.5

### Please describe the changes you would like to see

https://crystalmark.info/en/software/crystaldiskmark/crystaldiskmark-history/

Download:
https://crystalmark.info/en/download/

### PR DESCRIPTION
**Pull request by Exorcism0666**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.1.0 :green_apple:

- Resolves #140927

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140949)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

> This PR's version number 8.0.5 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 8.0.4.c, which has 4 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 821)

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

This manifest removes Apps and Features entries that are present in previous PR versions. Should these entries also be added to this version?

(Automated response - build 821.)

**Comment by Exorcism0666** [comment]
> Hi @Exorcism0666,
> 
> This manifest removes Apps and Features entries that are present in previous PR versions. Should these entries also be added to this version?
> 
> (Automated response - build 821.)

No!

**Comment by stephengillie** [comment]
Apps and features entries are supposed to be all-or-none. So if the other versions have it, then it should be included here also. (I need to update my messages.)

**Comment by MagicAndre1981** [comment]
> > Hi @Exorcism0666,
> > This manifest removes Apps and Features entries that are present in previous PR versions. Should these entries also be added to this version?
> > (Automated response - build 821.)
> 
> No!

the [old manifest for 8.0.4c ](https://github.com/microsoft/winget-pkgs/blob/86ab3e9cbb7e3e06fe9775d1711abc17dcf6ae04/manifests/c/CrystalDewWorld/CrystalDiskMark/8.0.4.c/CrystalDewWorld.CrystalDiskMark.installer.yaml#L18)has those entries:

```
  AppsAndFeaturesEntries:
  - DisplayName: CrystalDiskMark 8.0.4c
    DisplayVersion: 8.0.4c
```

I think this is what @stephengillie requests. Old manifest also has `MinimumOSVersion: 10.0.0.0` entry which is now also missing.

**Comment by MagicAndre1981** [comment]
> > Hi @Exorcism0666,
> > This manifest removes Apps and Features entries that are present in previous PR versions. Should these entries also be added to this version?
> > (Automated response - build 821.)
> 
> No!

@Exorcism0666 

the [old manifest for 8.0.4c ](https://github.com/microsoft/winget-pkgs/blob/86ab3e9cbb7e3e06fe9775d1711abc17dcf6ae04/manifests/c/CrystalDewWorld/CrystalDiskMark/8.0.4.c/CrystalDewWorld.CrystalDiskMark.installer.yaml#L18)has those entries:

```
  AppsAndFeaturesEntries:
  - DisplayName: CrystalDiskMark 8.0.4c
    DisplayVersion: 8.0.4c
```

I think this is what @stephengillie requests. Old manifest also has `MinimumOSVersion: 10.0.0.0` entry which is now also missing.

**Comment by MagicAndre1981** [comment]
@Exorcism0666 do you still work on this PR?

**Comment by Exorcism0666** [comment]
> @Exorcism0666 do you still work on this PR?

Sorry for my inactivity, about "MinimumOS", it's useless here.

**Comment by MagicAndre1981** [comment]
> > @Exorcism0666 do you still work on this PR?
> 
> Sorry for my inactivity, about "MinimumOS", it's useless here.

ok, the bot still wants it as it was declared in the past. @Exorcism0666

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

> This PR's version number 8.0.5 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 8.0.4.c, which has 4 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 870)

**Comment by MagicAndre1981** [comment]
> Hi @Exorcism0666,
> 
> > This PR's version number 8.0.5 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 8.0.4.c, which has 4 parameters.
> 
> Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)
> 

Do you mean this? It is version 8.0.5:

image

last manifest has a mistake, the version is 8.0.4c, NOT 8.0.4.c

image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
