### PR TITLE
Microsoft.Git version 2.46.0.0.0

### PR DESCRIPTION
**Pull request by ldennington**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/167577)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by derrickstolee — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @derrickstolee,

This error label only reflects a problem with the pipelines, and does not provide any data about the pacakge. We had an internal issue, which has been reverted. Sorry for any concern caused. 
- This was not the only PR to be impacted: https://github.com/microsoft/winget-pkgs/issues/167800
- More info about this error: https://github.com/microsoft/winget-pkgs/discussions/155218#discussioncomment-10351627

**Comment by derrickstolee** [comment]
@stephengillie: is the service still having issues? Could you please take a closer look at these failures, since Microsoft developers are blocked on this before getting the latest Git features.

**Comment by stephengillie** [comment]
> @ stephengillie: is the service still having issues? Could you please take a closer look at these failures, since Microsoft developers are blocked on this before getting the latest Git features.

Hi @derrickstolee,

Git is used in the validation process, so validating it always casues this error. I'll have to manually validate this package, and every update.

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Comment by derrickstolee** [comment]
Thanks, @stephengillie! I'll try to remember the manual validation requirement next time and make a point of contacting an admin.

**Pull request merged**
