### PR TITLE
New version: OverlayedDev.Overlayed version 0.4.0

### PR DESCRIPTION
**Pull request by schembriaiden**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161400)

### CODE REVIEW

**Comment by vikingnope** [comment]
@stephengillie, any ideas why pipeline isn't running?

**Comment by stephengillie** [comment]
Pipelines are currently throttled, to address an ephemeral service failure that cascaded into a capacity issue.

**Comment by vikingnope** [comment]
If you could run this manually that would be great :)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
