### PR TITLE
Add version: ProjectEnv.ProjectEnvCli version 3.19.0

### PR DESCRIPTION
**Pull request by repolevedavaj**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/176639)

### CODE REVIEW

**Comment by stephengillie** [comment]
> Possible duplicate package entry.
> 
> Similar installer SHA256 hash found in manifest:
> 
> * `InstallerSha256: 33faca8df059451e880172d3b9d8c125feaebbb9352fdacaebd01ea99e06b362`
>   
>   * manifests\p\ProjectEnv\ProjectEnvCli\v3.19.0

Hi @repolevedavaj,

I'm guessing this is an attempt to replace https://github.com/microsoft/winget-pkgs/pull/176066 before removing that version. Is that accurate?

**Comment by repolevedavaj** [comment]
@stephengillie yes, I accidentially pushed new version with the 'v' prefix. It seems that this prevents me from upgrading to that version automatically.

**Comment by repolevedavaj** [comment]
Should I remove the other manifest?

**Comment by stephengillie** [comment]
> Should I remove the other manifest?

Yes, please do.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
