### PR TITLE
New package: NVIDIACorporation.NVIDIAapp version 1.0.14.0

### PR DESCRIPTION
**Pull request by ghost**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141787)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-03-02 09:18:04.212 [CLI ] ShellExecute installer failed: 3858759680

(Automated response - build 857.)

**Comment by Barradel** [comment]
Hi @stephengillie ! Like said @og-mrk, this fails is probably because this app expects Nvidia GPU to be available in the system.

**Comment by stephengillie** [comment]
Hi @Barradel,

Unfortunately yes, this appears to be the case:

NVIDIA APP - requires an NVIDIA GPU.

- This sounds like a very similar situation to https://github.com/microsoft/winget-pkgs/pull/140756

**Comment by og-mrk** [comment]
Hello @stephengillie, thanks for responding to this issue.
I'm wondering on a workaround.. Could we add `ExpectedReturnCodes` and some Context for User when this happens?
like the code snippet below
``` YAML
ExpectedReturnCodes:
  - InstallerReturnCode: 3858759680
    ReturnResponse: systemNotSupported
```

Or do we have to wait for winget-cli [support for hardware](https://github.com/microsoft/winget-cli/issues/1417) to be implemented?

**Comment by Barradel** [comment]
> Hello @stephengillie, thanks for responding to this issue. I'm wondering on a workaround.. Could we add `ExpectedReturnCodes` and some Context for User when this happens? like the code snippet below
> 
> ```yaml
> ExpectedReturnCodes:
>   - InstallerReturnCode: 3858759680
>     ReturnResponse: systemNotSupported
> ```
> 
> Or do we have to wait for winget-cli [support for hardware](https://github.com/microsoft/winget-cli/issues/1417) to be implemented?

Good idea!

**Comment by stephengillie** [comment]
Hi @og-mrk and @Barradel,

That's an interesting proposal - it might make a good [Issue](https://github.com/microsoft/winget-pkgs/issues) - to unblock `Hardware` labeled PRs by adding a warning when the hardware is not present. A problem here is that if the installer won't install in the validation pipeline, then it can't have Defender and other scans performed on it, which is a critical part of our process. Here is the Issue for upgrading the validation pipeline VMs to include OpenGL:
- https://github.com/microsoft/winget-pkgs/issues/12906

**Comment by denelon** [comment]
Supporting custom hardware in validation is "Not Planned".
* https://github.com/microsoft/winget-pkgs/issues/199504

**Comment by DandelionSprout** [comment]
I've been able to add it to the 3rd-party Winget source [winget-extras](https://github.com/pl4nty/winget-extras) by [pl4nty](https://github.com/pl4nty) now, at least:

`winget source add --name winget-extras --type Microsoft.PreIndexed.Package --arg https://winget.tplant.com.au/cache; winget install Nvidia.NVIDIAApp`

**Pull request closed without merging**
