### PR TITLE
RamSoft dicomProxy Updated version: 0.2.256-ci.12

### PR DESCRIPTION
**Pull request by ghost**
RamSoft dicomProxy updated the version 0.2.256-ci.12, RamSoft DicomProxy from release pipeline

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/18400)

### CODE REVIEW

**Comment by ramsoft-inc** [comment]
@ItzLevvie Can you please re-run the pipeline.

**Comment by ramsoft-inc** [comment]
@denelon  Please review my request when you get time.

**Comment by ramsoft-inc** [comment]
@denelon  Please review my request when you get time.

**Review by denelon — APPROVED** [review]

**Pull request merged**
