### PR TITLE
add Deluge

### LINKED ISSUE #492: CI timeout but still running
#279 has running over 24h and the CI timeout
```
5/20/2020 5:00:58 PM
Status: Completed
##[error] Result: Failed
##vso[task.logissue type=error] Operation timed out.
```

But it's still running.

The pr is opened by me, but I don't know why it takes so long time to Installer scan

### PR DESCRIPTION
**Pull request by AusNugz**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/458)

### CODE REVIEW

**Comment by LukasNespor** [comment]
Please see #411 to resolve the validation issue.

**Comment by AusNugz** [comment]
My guess is it's failing due to requiring UAC. Guess I'll abandon this one.

**Comment by auanasgheps** [comment]
Weird. It failed but did not provide any output error.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
