### PR TITLE
Modify: OpenJS.NodeJS version 22.3.0

### PR DESCRIPTION
**Pull request by aisgbnok**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/157605)

### CODE REVIEW

**Comment by SpecterShell** [comment]
@aisgbnok Please do not add `UpgradeCode` to the manifest. Both `OpenJS.NodeJS` and `OpenJS.NodeJS.LTS` are using the same `UpgradeCode` and adding it to the former one will cause the latter to be recognized as the former. (And adding it to both may cause some users unable to update)

**Comment by aisgbnok** [comment]
> @aisgbnok Please do not add `UpgradeCode` to the manifest. Both `OpenJS.NodeJS` and `OpenJS.NodeJS.LTS` are using the same `UpgradeCode` and adding it to the former one will cause the latter to be recognized as the former. (And adding it to both may cause some users unable to update)

@SpecterShell, I see. That makes sense. Thank you for the insight and for flagging this. I will correct my mistake.

---

> (And adding it to both may cause some users unable to update)

Do you happen to know if adding it to say just `OpenJS.NodeJS` and not `OpenJS.NodeJS.LTS` would cause this issue as well? I'm removing it from both, but I'm curious. I haven't had a chance to look deeply at how winget-cli works regarding ARP outside of the docs in this repo yet. Thanks again.

**Comment by SpecterShell** [comment]
> > @aisgbnok Please do not add `UpgradeCode` to the manifest. Both `OpenJS.NodeJS` and `OpenJS.NodeJS.LTS` are using the same `UpgradeCode` and adding it to the former one will cause the latter to be recognized as the former. (And adding it to both may cause some users unable to update)
> 
> @SpecterShell, I see. That makes sense. Thank you for the insight and for flagging this. I will correct my mistake.
> 
> > (And adding it to both may cause some users unable to update)
> 
> Do you happen to know if adding it to say just `OpenJS.NodeJS` and not `OpenJS.NodeJS.LTS` would cause this issue as well? I'm removing it from both, but I'm curious. I haven't had a chance to look deeply at how winget-cli works regarding ARP outside of the docs in this repo yet. Thanks again.

For MSI installers, `UpgradeCode` has a higher priority than any other entries.

If one of the two packages have the `UpgradeCode` entry, all versions of NodeJS (LTS or non-LTS) will be matched to that package. 

And if both packages have that entry, WinGet will complain in the log that there are multiple packages matched. If neither of them has been installed through WinGet (i.e., installed through the installer directly), the installation will remain unmatched. If one of them was installed through WinGet (which will be recorded in `installed.db`), the installation will be matched to that package, regardless of whether it is LTS or non-LTS.

**Review by stephengillie — APPROVED** [review]

**Comment by aisgbnok** [comment]
> > > @aisgbnok Please do not add `UpgradeCode` to the manifest. Both `OpenJS.NodeJS` and `OpenJS.NodeJS.LTS` are using the same `UpgradeCode` and adding it to the former one will cause the latter to be recognized as the former. (And adding it to both may cause some users unable to update)
> > 
> > 
> > @SpecterShell, I see. That makes sense. Thank you for the insight and for flagging this. I will correct my mistake.
> > > (And adding it to both may cause some users unable to update)
> > 
> > 
> > Do you happen to know if adding it to say just `OpenJS.NodeJS` and not `OpenJS.NodeJS.LTS` would cause this issue as well? I'm removing it from both, but I'm curious. I haven't had a chance to look deeply at how winget-cli works regarding ARP outside of the docs in this repo yet. Thanks again.
> 
> For MSI installers, `UpgradeCode` has a higher priority than any other entries.
> 
> If one of the two packages have the `UpgradeCode` entry, all versions of NodeJS (LTS and non-LTS) will be matched to that package.
> 
> And if both packages have that entry, WinGet will complain in the log that there are multiple packages matched. If neither of them has been installed through WinGet (i.e., installed through the installer directly), the installation will remain unmatched. If one of them was previously installed through WinGet (which would be recorded in `installed.db`), the installation will be matched to that package, regardless of whether it is LTS or non-LTS.
> 
> ```
> 2024-06-13 15:16:30.701 [REPO] Finding available package from installed package using system reference search: Query:[none] Include:ProductCode='{97761326-7202-4cb0-9886-6282d9f456b1}'[Exact] Include:UpgradeCode='{47c07a3a-42ef-4213-a85d-8f5a59077c28}'[Exact] Include:NormalizedNameAndPublisher='nodejs'+'nodejsfoundation'[Exact]
> 2024-06-13 15:16:30.701 [REPO]  ... searching source: msstore [StoreEdgeFD]
> 2024-06-13 15:16:30.701 [REPO] Performing search: Query:[none] Include:ProductCode='{97761326-7202-4cb0-9886-6282d9f456b1}'[Exact] Include:UpgradeCode='{47c07a3a-42ef-4213-a85d-8f5a59077c28}'[Exact] Include:NormalizedNameAndPublisher='nodejs'+'nodejsfoundation'[Exact]
> 2024-06-13 15:16:30.702 [REPO] PackageMatchField not supported in this version: UpgradeCode
> 2024-06-13 15:16:30.702 [REPO]  ... searching source: winget [Microsoft.Winget.Source_8wekyb3d8bbwe]
> 2024-06-13 15:16:30.702 [REPO] Performing search: Query:[none] Include:ProductCode='{97761326-7202-4cb0-9886-6282d9f456b1}'[Exact] Include:UpgradeCode='{47c07a3a-42ef-4213-a85d-8f5a59077c28}'[Exact] Include:NormalizedNameAndPublisher='nodejs'+'nodejsfoundation'[Exact]
> 2024-06-13 15:16:30.704 [REPO]  ... setting latest tracking package to: OpenJS.NodeJS
> 2024-06-13 15:16:30.704 [REPO] Performing search: Query:[none] Include:ProductCode='{97761326-7202-4cb0-9886-6282d9f456b1}'[Exact] Include:UpgradeCode='{47c07a3a-42ef-4213-a85d-8f5a59077c28}'[Exact] Include:NormalizedNameAndPublisher='nodejs'+'nodejsfoundation'[Exact]
> 2024-06-13 15:16:30.704 [REPO] Found multiple matches for installed package [ARP\Machine\X64\{97761326-7202-4CB0-9886-6282D9F456B1}] in source [Microsoft.Winget.Source_8wekyb3d8bbwe] when searching for [Query:[none] Include:ProductCode='{97761326-7202-4cb0-9886-6282d9f456b1}'[Exact] Include:UpgradeCode='{47c07a3a-42ef-4213-a85d-8f5a59077c28}'[Exact] Include:NormalizedNameAndPublisher='nodejs'+'nodejsfoundation'[Exact]]
> 2024-06-13 15:16:30.704 [REPO]   Checking match with package id: OpenJS.NodeJS
> 2024-06-13 15:16:30.704 [REPO]   Checking match with package id: OpenJS.NodeJS.LTS
> 2024-06-13 15:16:30.704 [REPO]   Found multiple packages with strong match fields
> 2024-06-13 15:16:30.705 [REPO]   Appropriate available package could not be determined
> 2024-06-13 15:16:30.705 [REPO]  ... using tracking package: OpenJS.NodeJS
> 2024-06-13 15:16:30.705 [REPO] Performing search: Query:[none] Filter:Id='OpenJS.NodeJS'[CaseInsensitive]
> 2024-06-13 15:16:30.705 [REPO]  ... adding available package: OpenJS.NodeJS
> ```

I see. Thank you again for your help.

**Pull request merged**
