### PR TITLE
New version: brimdata.brim version 0.25.0

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/27751)

### CODE REVIEW

**Review by ImJoakim — CHANGES_REQUESTED** [review]
image

**Comment by OfficialEsco** [comment]
This might still fail
image
It does however install when you press yes or no, no idea what it requires..

**Comment by ImJoakim** [comment]
Installed just fine now on a fresh VM. I wanna see what the pipeline says before I approve.

image

**Comment by OfficialEsco** [comment]
Guess its a Sandbox issue ¯\\\_(ツ)_/¯

**Comment by ImJoakim** [comment]
🤷‍♂️ 

image

**Review by ImJoakim — APPROVED** [review]

**Pull request merged**
