### PR TITLE
New version: GitTools.GitVersion version 6.0.2

### PR DESCRIPTION
**Pull request by arturcic**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/167422)

### CODE REVIEW

**Comment by arturcic** [comment]
image

Installing it locally works

image

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-08-12 12:33:34.007 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.2/gitversion-win-x64-6.0.2.zip Result: 0x80004005
> 2024-08-12 12:32:47.548 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.2/gitversion-win-x64-6.0.2.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 887.)

**Comment by thoemmi** [comment]
@arturcic on my machine a virus was detected:

image

Here's screenshot from Windows Security:
image

**Comment by arturcic** [comment]
Ha, that's interesting. We are building the tool in GitHub actions using the standard `dotnet publish` command.

Interesting that the arm64 version as shown in the screenshot is fine, no `viruses detected`. Can that be a false positive?

**Comment by thoemmi** [comment]
I'd guess a false positive too :shrug:

**Comment by arturcic** [comment]
I will give it a try today on an intel machine and see if I get same thing. But I wonder if it's a false positive, will I have to manually check it for every new release?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-08-13 11:17:11.415 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.2/gitversion-win-x64-6.0.2.zip Result: 0x80004005
> 2024-08-13 11:16:26.706 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.2/gitversion-win-x64-6.0.2.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 887.)

**Comment by arturcic** [comment]
@stephengillie  here is the test on a win11 x64:

image

and a VirusTotal scan

https://www.virustotal.com/gui/url/272fd483e551b0c3e401001d8acff01063840864da37cf1a3c67c60cd9bd196f?nocache=1

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-08-15 16:07:48.917 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.2/gitversion-win-x64-6.0.2.zip Result: 0x80004005
> 2024-08-15 16:19:09.485 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.2/gitversion-win-x64-6.0.2.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 887.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-08-20 08:59:30.941 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.2/gitversion-win-x64-6.0.2.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 887.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-08-20 08:59:30.941 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.2/gitversion-win-x64-6.0.2.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 887.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\GitTools.GitVersion__DefaultSource\gitversion.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\gitversion.exe returned exit code: 1
> Installation failed with exit code -1978335187
> 2024-08-22 08:49:30.173 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.2/gitversion-win-x64-6.0.2.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 887.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\GitTools.GitVersion__DefaultSource\gitversion.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\gitversion.exe returned exit code: 1
> Installation failed with exit code -1978335187
> 2024-08-22 08:49:30.173 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.2/gitversion-win-x64-6.0.2.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 887.)

**Comment by arturcic** [comment]
@stephengillie is it possible that you can also perform that manual check as you did [here](https://github.com/microsoft/winget-pkgs/pull/166381#issuecomment-2299431341)?

**Comment by stephengillie** [comment]
Manual Validation ended with:
> Detected 0 Defender (with signature version 1.417.268.0) errors:

(Automated response - build 888.)

**Comment by arturcic** [comment]
@stephengillie @wingetbot The removal of the dependency was on purpose as we [removed](https://github.com/GitTools/GitVersion/pull/4147#issue-2452647805) it from GitVersion.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\GitTools.GitVersion__DefaultSource\gitversion.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\gitversion.exe returned exit code: 1
> Executable C:\Users\VALIDA~1\AppData\Local\Temp\B3CD9143-1C28-46D3-9031-464AE326DEDB\DismHost.exe returned exit code: -2147024809

(Automated response - build 888.)

**Comment by stephengillie** [comment]
> > @ stephengillie @wingetbot The removal of the dependency was on purpose as we [removed](https://github.com/GitTools/GitVersion/pull/4147#issue-2452647805) it from GitVersion.
> 
> @ stephengillie

Hi @arturcic, 

Thanks for the confirmation. I usually ignore the label https://github.com/microsoft/winget-pkgs/labels/Manifest-Metadata-Consistency - either the metadata change is immaterial, or there's a good reason for it. I was waiting for the pipeline to complete, and got distracted approving 450+ PRs.

**Comment by arturcic** [comment]
> > > @ stephengillie @wingetbot The removal of the dependency was on purpose as we [removed](https://github.com/GitTools/GitVersion/pull/4147#issue-2452647805) it from GitVersion.
> > 
> > 
> > @ stephengillie
> 
> Hi @arturcic,
> 
> Thanks for the confirmation. I usually ignore the label [ Manifest-Metadata-Consistency](https://github.com/microsoft/winget-pkgs/labels/Manifest-Metadata-Consistency) - either the metadata change is immaterial, or there's a good reason for it. I was waiting for the pipeline to complete, and got distracted approving 450+ PRs.

I can understand that, no worries

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
