### PR TITLE
 New version: ndd.Notepad-- version 2.8.0

### PR DESCRIPTION
**Pull request by hjkl950217**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/119594)

### CODE REVIEW

**Comment by hjkl950217** [comment]
Why? All the inspections have passed

**Comment by hjkl950217** [comment]
Why? All the inspections have passed

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
> Why? All the inspections have passed

It might have been from our systems being at high load. Sorry for any concern.

**Comment by hjkl950217** [comment]
> > Why? All the inspections have passed
> 
> It might have been from our systems being at high load. Sorry for any concern.

tks,I said it to the robot, I thought it would trigger the deployment process again. Thank you for your efforts

**Pull request merged**
