### PR TITLE
Add: Fluidsynth 2.3.2

### PR DESCRIPTION
**Pull request by superusercode**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/107121)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @superusercode,

This package installs normally. But when launched from the symlink, it gives: 
image

The main program gives this error, which I believe is due to the VM not having an audio device: 
> FluidSynth runtime version 2.3.2
> Copyright (C) 2000-2023 Peter Hanappe and others.
> Distributed under the LGPL license.
> SoundFont(R) is a registered trademark of Creative Technology Ltd.
> 
> fluidsynth: error: fluid_sfloader_load(): Failed to open 'C:\ProgramData\soundfonts\default.sf2': File does not exist.
> fluidsynth: error: Unable to open file 'C:\ProgramData\soundfonts\default.sf2'
> fluidsynth: error: Failed to load SoundFont "C:\ProgramData\soundfonts\default.sf2"
> fluidsynth: error: not enough MIDI in devices found. Expected:1 found:0
> fluidsynth: error: Device "default" does not exists
> Failed to create the MIDI thread; no MIDI input
> will be available. You can access the synthesizer
> through the console.
> fluidsynth: error: Failed to create the DirectSound object: 'Don't know why'
> Failed to create the audio driver. Giving up.

Since the symlink is failing I believe this shouldn't proceed. What do you think?

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Comment by Trenly** [comment]
@superusercode - Support for zipped binaries has now been added and is available in the pipelines. This will require you to update your submission to ManifestVersion: 1.9.0 and set ArchiveBinariesDependOnPath: true in the installer node. To keep things clean, this PR is being closed. Please submit a new PR for the latest version of this package. Thank you for your contributions!

**Comment by luzpaz** [comment]
Great news, just in time for latest stable update: 2.4.1 (https://github.com/FluidSynth/fluidsynth/releases/tag/v2.4.1)

**Pull request closed without merging**
