### PR TITLE
New package: BC3Tech.FileSorter version 0.2.70

### LINKED ISSUE #162878: [Package Request]: BC3Technologies FileSorter
### How can we help?

None

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/bc3tech/FileSorter/releases/download/0.2.70/Filesorter_0.2.70.zip
Publisher: BC3Technologies
Package Name: FileSorter
Description: Sorts files into datetime subfolders, optionally parsing EXIF data of photos to get accurate date/time information.
Package Version: 0.2.70
Installer URL: https://github.com/bc3tech/FileSorter/releases/download/0.2.70/Filesorter_0.2.70.zip

### PR DESCRIPTION
**Pull request by bc3tech**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/162870)

closes #162878

### CODE REVIEW

**Comment by bc3tech** [comment]
@microsoft-github-policy-service agree

**Comment by bc3tech** [comment]
closes #162878

**Comment by Trenly** [comment]
> PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> filesorter
The application to execute does not exist: 'C:\Users\WDAGUtilityAccount\AppData\Local\Microsoft\WinGet\Links\FileSorter.dll'.

[Policy] Zip Binary

**Comment by bc3tech** [comment]
thanks. local install worked for me so not sure what the issue is.

I'll work to repackage as single exe & resubmit

**Comment by bc3tech** [comment]
@Trenly please re-evaluate, thanks!

**Comment by bc3tech** [comment]
@trenly can we remove the `zip-binary` label from this now? Should work w/o issue now.

**Comment by Trenly** [comment]
[Policy] Reset Labels

**Review by Trenly — APPROVED** [review]
Looks like the latest update worked for me too

**Comment by bc3tech** [comment]
> Looks like the latest update worked for me too

@trenly thanks! what do we have to do to merge it?

**Comment by Trenly** [comment]
@stephengillie

* #142854

**Pull request merged**
