### PR TITLE
New version: Microsoft.OneDrive version 22.045.0227.0004

### PR DESCRIPTION
**Pull request by ImJoakim**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/55703)

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]
https://github.com/microsoft/winget-pkgs/pull/51131#issuecomment-1064455480

@hackean-msft did however get around the issue 🤔
Obv not the optimal way, but it should be marked as Internal Issue instead
```
****************************************************************************************
Installation Verification
****************************************************************************************

-----------------------------------------------------
Failed
-----------------------------------------------------
Status: Completed
```

From the Artifact logs its getting Network error `80072EFD Msg:[InternetOpenUrl() failed.]` and `DeliveryOptimization error: 0x80072efd, extended error: 0x00000000`

**Comment by OfficialEsco** [comment]
@denelon someone needs to be assigned, and preferably permanently resolve the issue on the Azure VM (Seniors should know about the issue and most likely the cause)

**Comment by ImJoakim** [comment]
https://github.com/microsoft/winget-pkgs/pull/55703#issuecomment-1086080516

**Comment by OfficialEsco** [comment]
@msftrubengu your old friend OneDrive is still waiting for someone

**Pull request merged**
