### PR TITLE
New package: Corel.MindManager23 version 23.2.209.0

### PR DESCRIPTION
**Pull request by hmlervik**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/179827)

### CODE REVIEW

**Comment by hmlervik** [comment]
Hi! It would be great if this could replace the currently existing MindManager so we can have support for different major versions.

https://github.com/microsoft/winget-pkgs/tree/master/manifests/c/Corel/MindManager

**Comment by hmlervik** [comment]
https://en.wikipedia.org/wiki/MindManager#:~:text=On%20August%209%2C%202016%2C%20Corel%20announced%20that%20they%20had%20acquired%20the%20Mindjet%20MindManager%20business.%5B19%5D

https://blog.mindmanager.com/mindmanager-joins-corel-2/

**Review by stephengillie — CHANGES_REQUESTED** [review]
Hi @hmlervik,

I only found one product website for `MindManager`. If this version has a different `PackageUrl`, please update to that page instead.

**Comment by stephengillie** [comment]
Verify:
image
Just as with https://github.com/microsoft/winget-pkgs/pull/179824#issuecomment-2412024503, I couldn't access the version number. The shortcut here shows "23", while the shortcut in the other PR shows "24". Otherwise, the applications appear very similar to me. 
image

**Comment by hmlervik** [comment]
After some trial and error, it should be ok now. Let me know if there is anything wrong.

**Comment by hmlervik** [comment]
I guess the validation fails because I have also modified the manifests for Corel.MindManager by deleting them. Should I open another PR for removing them? Corel.MindManager will be redundant if this gets merged.

**Comment by stephengillie** [comment]
Automatic Validation ended with: 
> Addition and deletion only permitted in the same package directory.

From the [Files changed](https://github.com/microsoft/winget-pkgs/pull/179827/files) tab:
> ..23.1.243/Corel.MindManager.installer.yaml → ....209.0/Corel.MindManager23.installer.yaml

> I guess the validation fails because I have also modified the manifests for Corel.MindManager by deleting them. Should I open another PR for removing them? Corel.MindManager will be redundant if this gets merged.

Yes - it looks like `Corel.MindManager` is being renamed to `Corel.MindManager23` alongside the addition of `Corel.MindManager24`. For the rename to happen, the addition and removal have to occur in separate PRs. 

- Should the `MindManager` part be combined, using `Corel.MindManager.23` and `Corel.MindManager.24` instead?

**Pull request closed without merging**
