### PR TITLE
New version: Baidu.BaiduWenku version 1.1.4

### PR DESCRIPTION
**Pull request by SpecterShell**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/61481)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by SpecterShell** [comment]
😕

**Comment by SpecterShell** [comment]
https://github.com/microsoft/winget-cli/issues/2057

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by SpecterShell** [comment]
🤔

**Comment by stephengillie** [comment]
@SpecterShell The installer here doesn't seem to have an unattended mode - I wasn't able to find the switch to activate it, nor could I find switches to load a help page.

**Comment by SpecterShell** [comment]
> @SpecterShell The installer here doesn't seem to have an unattended mode - I wasn't able to find the switch to activate it, nor could I find switches to load a help page.

It is a NSIS installer so the silent switch is `/S` (and it works).
There is nothing wrong with the manifest. The validation pipleline fails due to https://github.com/microsoft/winget-cli/issues/2057

**Pull request merged**
