### PR TITLE
Fixing ARP for Winamp.Winamp

### PR DESCRIPTION
**Pull request by krystofkrticka**
According to appwiz.cpl in Windows version number in AppsAndFeaturesEntries should be 5.91.0 
image

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/103157)

### CODE REVIEW

**Comment by krystofkrticka** [comment]
For some reason dependency VC++ waits until you click on install.
https://imgur.com/a/OC4Ye16

**Comment by stephengillie** [comment]
This is due to Winamp having a dependency.

**Comment by krystofkrticka** [comment]
@stephengillie I know but weird thing is that dependency suddenly fails to install silently even though it installs just fine by itself. I thought and expected that it would use install parameters stated in manifest of dependency.

**Comment by stephengillie** [comment]
Oh, dependencies aren't currently supported, pending:
* https://github.com/microsoft/winget-cli/issues/163

**Comment by krystofkrticka** [comment]
I've known about this, but I was little bit surprised that stable version of winget tried to installed dependencies which are still in works.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
