### PR TITLE
Remove version: Kamua.TinyVid version 1.0.1

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/179426)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://quicktrim-public-update.s3.eu-central-1.amazonaws.com/download/latest/win/x64/TinyVid-win-1.0.1.exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 896)

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 896.)

**Comment by stephengillie** [comment]
URL: https://quicktrim-public-update.s3.eu-central-1.amazonaws.com/download/latest/win/x64/TinyVid-win-1.0.1.exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 896)

**Comment by Trenly** [comment]
[Policy] Reset Feedback

**Review by Trenly — APPROVED** [review]
See #182664 for better explanation of removal

**Pull request merged**
