### PR TITLE
ViGEm.BthPS3 version 2.1.153.0

### PR DESCRIPTION
**Pull request by sitiom**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/65544)

### CODE REVIEW

**Comment by sitiom** [comment]
Test in the Sandbox:
image

**Comment by sitiom** [comment]
Test in the Sandbox:
image

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/65544#issuecomment-1179648588

You can set this PR to DRAFT until Bluetooth stack is available in validation pipelines (probably requires custom hardware)

**Comment by sitiom** [comment]
Ok

**Comment by sitiom** [comment]
https://github.com/microsoft/winget-cli/issues/1417

**Comment by ItzLevvie** [comment]
@msftbot Blocking-Issue

**Pull request closed without merging**
