### PR TITLE
Added echocat/watch/1.1.0

### PR DESCRIPTION
**Pull request by blaubaer**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest manifests/e/echocat/watch/1.1.0/`?
- [x] Have you tested your manifest locally with `winget install --manifest manifests/e/echocat/watch/1.1.0/`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `manifests/e/echocat/watch/1.1.0/` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/98029)

### CODE REVIEW

**Comment by blaubaer** [comment]
@microsoft-github-policy-service agree

**Comment by blaubaer** [comment]
Can someone please tell me what exactly failed? Under the URL (of the job) https://dev.azure.com/ms/ed6a5dfa-6e7f-413b-842c-8305dd9e89e6/_apis/build/builds/433324/logs/23 there is no details listed what exactly failed.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @blaubaer,

The execution error is likely because the application is expecting a flag or command, but none were given in validation. But this installed fine in my sandbox, so I'm unsure why that error was reported. 

```
error: required argument 'command' not provided
usage: watch [<flags>] <command>...

Like the unix one but works cross-platform without magic.

Flags:
      --help                     Show context-sensitive help (also try
                                 --help-long and --help-man).
...
```

**Pull request merged**
