### PR TITLE
NI.ni-daqmx version 24.8.0

### PR DESCRIPTION
**Pull request by lars-nvhgroup**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/180597)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
2024-10-10 16:30:32.342 [REPO] Parsing link file at C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\NI Error Reporting (64-bit).lnk
> 2024-10-10 16:30:32.387 [REPO] Link file parsed. Path: C:\Program Files\National Instruments\Shared\NI Error Reporting\nierserver.exe Args:  DisplayName: NI Error Reporting (64-bit)
> 2024-10-10 16:30:32.559 [REPO] Parsing link file at C:\ProgramData\Microsoft\Windows\Start Menu\Programs\National Instruments\NI Error Reporting Settings.lnk
> 2024-10-10 16:30:32.564 [REPO] Link file parsed. Path: C:\Program Files\National Instruments\Shared\NI Error Reporting\common\NationalInstruments.ErrorReporting.SettingsDialog.exe Args:  DisplayName: NI Error Reporting Settings
> 
> Installation failed with exit code -1978335226
> 2024-10-10 16:30:29.889 [CLI ] ShellExecute installer failed: 4294842213
> MSI (s) (CC:44) [16:12:32:558]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (CC:44) [16:12:32:558]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (CC:44) [16:12:32:558]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (CC:44) [16:12:32:558]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (CC:44) [16:12:32:558]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> Property(S): OutOfDiskSpace = 0
> Property(S): OutOfNoRbDiskSpace = 0
> Property(S): PrimaryVolumeSpaceAvailable = 0
> Property(S): PrimaryVolumeSpaceRequired = 0
> Property(S): PrimaryVolumeSpaceRemaining = 0
> MSI (s) (CC:4C) [16:12:33:480]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (CC:4C) [16:12:33:480]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (CC:4C) [16:12:33:480]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (CC:4C) [16:12:33:480]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (CC:4C) [16:12:33:480]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> MSI (s) (CC:D0) [16:12:40:324]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (CC:D0) [16:12:40:324]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (CC:D0) [16:12:40:324]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (CC:D0) [16:12:40:324]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (CC:D0) [16:12:40:324]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> MSI (s) (CC:D0) [16:12:41:137]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (CC:D0) [16:12:41:137]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (CC:D0) [16:12:41:137]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (CC:D0) [16:12:41:137]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (CC:D0) [16:12:41:137]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.

Automated error analysis suggests -1978335226 may mean Running ShellExecute failed

(Automated response - build 896.)

**Comment by lars-nvhgroup** [comment]
> Automatic Validation ended with: 2024-10-10 16:30:32.342 [REPO] Parsing link file at C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp\NI Error Reporting (64-bit).lnk
> 
> > 2024-10-10 16:30:32.387 [REPO] Link file parsed. Path: C:\Program Files\National Instruments\Shared\NI Error Reporting\nierserver.exe Args:  DisplayName: NI Error Reporting (64-bit)
> > 2024-10-10 16:30:32.559 [REPO] Parsing link file at C:\ProgramData\Microsoft\Windows\Start Menu\Programs\National Instruments\NI Error Reporting Settings.lnk
> > 2024-10-10 16:30:32.564 [REPO] Link file parsed. Path: C:\Program Files\National Instruments\Shared\NI Error Reporting\common\NationalInstruments.ErrorReporting.SettingsDialog.exe Args:  DisplayName: NI Error Reporting Settings
> > Installation failed with exit code -1978335226
> > 2024-10-10 16:30:29.889 [CLI ] ShellExecute installer failed: 4294842213
> > MSI (s) (CC:44) [16:12:32:558]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> > MSI (s) (CC:44) [16:12:32:558]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> > MSI (s) (CC:44) [16:12:32:558]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> > MSI (s) (CC:44) [16:12:32:558]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> > MSI (s) (CC:44) [16:12:32:558]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> > Property(S): OutOfDiskSpace = 0
> > Property(S): OutOfNoRbDiskSpace = 0
> > Property(S): PrimaryVolumeSpaceAvailable = 0
> > Property(S): PrimaryVolumeSpaceRequired = 0
> > Property(S): PrimaryVolumeSpaceRemaining = 0
> > MSI (s) (CC:4C) [16:12:33:480]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> > MSI (s) (CC:4C) [16:12:33:480]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> > MSI (s) (CC:4C) [16:12:33:480]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> > MSI (s) (CC:4C) [16:12:33:480]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> > MSI (s) (CC:4C) [16:12:33:480]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> > MSI (s) (CC:D0) [16:12:40:324]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> > MSI (s) (CC:D0) [16:12:40:324]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> > MSI (s) (CC:D0) [16:12:40:324]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> > MSI (s) (CC:D0) [16:12:40:324]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> > MSI (s) (CC:D0) [16:12:40:324]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> > MSI (s) (CC:D0) [16:12:41:137]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> > MSI (s) (CC:D0) [16:12:41:137]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> > MSI (s) (CC:D0) [16:12:41:137]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> > MSI (s) (CC:D0) [16:12:41:137]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> > MSI (s) (CC:D0) [16:12:41:137]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> 
> Automated error analysis suggests -1978335226 may mean Running ShellExecute failed
> 
> (Automated response - build 896.)

What does it actually mean? I can not reproduce this error.

**Comment by stephengillie** [comment]
> What does it actually mean? I can not reproduce this error.

The important bit is:

> ShellExecute installer failed: 4294842213

I got the same error from my VM automation. I retried manually, and couldn't recreate the error. 

image

**Comment by lars-nvhgroup** [comment]
> > What does it actually mean? I can not reproduce this error.
> 
> The important bit is:
> 
> > ShellExecute installer failed: 4294842213
> 
> I got the same error from my VM automation. I retried manually, and couldn't recreate the error.
> 
> image

Is it something inherent to the automation pipeline?

**Comment by stephengillie** [comment]
> Is it something inherent to the automation pipeline?

Thanks for your patience. That the same error occurs in my VMs means it's not a pipeline quirk. It's odd that you did not see the same outcome. Is there a log location or other data that could help with troubleshooting? I'd be happy to run this again and send logs or other data to the destination of your choosing.

**Pull request closed without merging**
