### PR TITLE
Quote version in Mozilla.Thunderbird 102.0

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/113893&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Manual Validation: 
- en-US-x64-wix - Pending
- en-US-x86-wix - Pending
- en-US-x64-exe - Pending
- en-US-x86-exe - Pending
- en-GB-x64-wix - Pending
- en-GB-x86-wix - Pending
- en-GB-x64-exe - Pending
- en-GB-x86-exe - Pending
- de-DE-x64-wix - Pending
- de-DE-x86-wix - Pending
- de-DE-x64-exe - Pending
- de-DE-x86-exe - Pending
- zh-CN-x64-wix - Pending
- zh-CN-x86-wix - Pending
- zh-CN-x64-exe - Pending
- zh-CN-x86-exe - Pending
- zh-TW-x64-wix - Pending
- zh-TW-x86-wix - Pending
- zh-TW-x64-exe - Pending
- zh-TW-x86-exe - Pending
- es-ES-x64-wix - Pending
- es-ES-x86-wix - Pending
- es-ES-x64-exe - Pending
- es-ES-x86-exe - Pending
- ja-JP-x64-wix - Pending
- ja-JP-x86-wix - Pending
- ja-JP-x64-exe - Pending
- ja-JP-x86-exe - Pending
- fr-FR-x64-wix - Pending
- fr-FR-x86-wix - Pending
- fr-FR-x64-exe - Pending
- fr-FR-x86-exe - Pending

**Pull request merged**
