### PR TITLE
Adds Viscosity version 1.10

### PR DESCRIPTION
**Pull request by trametheka**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/31966)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]
Do you know what's happening here?
image


When I press the OK button:
image

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/31966#pullrequestreview-789193070

**Comment by ChuckFerring** [comment]
During validation we get the same error dialog that ItzLevvie shared above. Here is an excerpt from the install log:

...
2021-11-03 11:06:44.813   Successfully imported the DLL function. Delay loaded? No
2021-11-03 11:06:44.829   Extracting temporary file: C:\Users\VALIDA~1\AppData\Local\Temp\is-DTOVC.tmp\MicrosoftEdgeWebview2Setup.exe
2021-11-03 11:06:45.985   Extracting temporary file: C:\Users\VALIDA~1\AppData\Local\Temp\is-DTOVC.tmp\Sidebar_150.bmp
2021-11-03 11:06:46.001   Extracting temporary file: C:\Users\VALIDA~1\AppData\Local\Temp\is-DTOVC.tmp\Sidebar_150.bmp
2021-11-03 11:06:46.048   Downloading temporary file from https://download.visualstudio.microsoft.com/download/pr/f1998402-3cc0-466f-bd67-d9fb6cd2379b/A1592D3DA2B27230C087A3B069409C1E82C2664B0D4C3B511701624702B2E2A3/VC_redist.x64.exe: C:\Users\VALIDA~1\AppData\Local\Temp\is-DTOVC.tmp\vc_redist.x64.exe
2021-11-03 11:06:46.126     0 of 25168640 bytes done.
2021-11-03 11:06:46.173     532479 of 25168640 bytes done.
2021-11-03 11:06:46.235     1064958 of 25168640 bytes done.
2021-11-03 11:06:46.267     1597438 of 25168640 bytes done.
2021-11-03 11:06:46.345     2129917 of 25168640 bytes done.
2021-11-03 11:06:46.438     2662397 of 25168640 bytes done.
2021-11-03 11:06:46.532     3194876 of 25168640 bytes done.
2021-11-03 11:06:46.610     3727356 of 25168640 bytes done.
2021-11-03 11:06:46.704     4259835 of 25168640 bytes done.
2021-11-03 11:06:46.782     4792315 of 25168640 bytes done.
2021-11-03 11:06:46.876     5324794 of 25168640 bytes done.
2021-11-03 11:06:46.970     5857274 of 25168640 bytes done.
2021-11-03 11:06:47.050     6389753 of 25168640 bytes done.
2021-11-03 11:06:47.142     6922233 of 25168640 bytes done.
2021-11-03 11:06:47.236     7454712 of 25168640 bytes done.
2021-11-03 11:06:47.345     7987192 of 25168640 bytes done.
2021-11-03 11:06:47.407     8519671 of 25168640 bytes done.
2021-11-03 11:06:47.501     9052151 of 25168640 bytes done.
2021-11-03 11:06:47.595     9584630 of 25168640 bytes done.
2021-11-03 11:06:47.673     10117110 of 25168640 bytes done.
2021-11-03 11:06:47.751     10649589 of 25168640 bytes done.
2021-11-03 11:06:47.845     11182069 of 25168640 bytes done.
2021-11-03 11:06:47.938     11714548 of 25168640 bytes done.
2021-11-03 11:06:48.032     12247028 of 25168640 bytes done.
2021-11-03 11:06:48.110     12779507 of 25168640 bytes done.
2021-11-03 11:06:48.204     13311987 of 25168640 bytes done.
2021-11-03 11:06:48.282     13844466 of 25168640 bytes done.
2021-11-03 11:06:48.376     14376946 of 25168640 bytes done.
2021-11-03 11:06:48.454     14909425 of 25168640 bytes done.
2021-11-03 11:06:48.548     15441905 of 25168640 bytes done.
2021-11-03 11:06:48.642     15974384 of 25168640 bytes done.
2021-11-03 11:06:48.720     16498688 of 25168640 bytes done.
2021-11-03 11:06:48.814     17031168 of 25168640 bytes done.
2021-11-03 11:06:48.892     17563647 of 25168640 bytes done.
2021-11-03 11:06:48.986     18096127 of 25168640 bytes done.
2021-11-03 11:06:49.079     18628606 of 25168640 bytes done.
2021-11-03 11:06:49.157     19161086 of 25168640 bytes done.
2021-11-03 11:06:49.251     19693565 of 25168640 bytes done.
2021-11-03 11:06:49.360     20226045 of 25168640 bytes done.
2021-11-03 11:06:49.423     20758524 of 25168640 bytes done.
2021-11-03 11:06:49.517     21291004 of 25168640 bytes done.
2021-11-03 11:06:49.611     21823483 of 25168640 bytes done.
2021-11-03 11:06:49.689     22355963 of 25168640 bytes done.
2021-11-03 11:06:49.783     22888442 of 25168640 bytes done.
2021-11-03 11:06:49.876     23420922 of 25168640 bytes done.
2021-11-03 11:06:49.954     23953401 of 25168640 bytes done.
2021-11-03 11:06:50.048     24485881 of 25168640 bytes done.
2021-11-03 11:06:50.126     25018360 of 25168640 bytes done.
2021-11-03 11:06:50.158     25168640 of 25168640 bytes done.
2021-11-03 11:06:50.158   Successfully downloaded file to {tmp}: vc_redist.x64.exe
2021-11-03 11:06:50.798   Message box (OK):
                          Internal error: DownloadTemporaryFile: Invalid Url value.

**Comment by trametheka** [comment]
Cheers @ChuckFerring , found the problem, will submit a new pull when we've updated.

**Pull request closed without merging**
