### PR TITLE
New version: Posit.rig version 0.7.0

### PR DESCRIPTION
**Pull request by gaborcsardi**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/148106)

### CODE REVIEW

**Comment by gaborcsardi** [comment]
> @gaborcsardi please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree company="Posit, PBC"

**Comment by gaborcsardi** [comment]
@microsoft-github-policy-service agree company="Posit, PBC"

**Comment by gaborcsardi** [comment]
I thought I signed the CLA here: https://github.com/microsoft/winget-pkgs/pull/148106#issuecomment-2041612038 But I am not sure.

The license/cla check is green (All CLA requirements met), but the PR has the `Needs-CLA` label.

Is there something I need to do?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files\rig\rig.exe returned exit code: 2
> Executable C:\Program Files\rig\gsudo.exe returned exit code: 999

(Automated response - build 876.)

**Review by stephengillie — APPROVED** [review]

**Comment by gaborcsardi** [comment]
Thank you!

**Pull request merged**
