### PR TITLE
New version: Ablaze.Floorp.Daylight version 11.8.1

### PR DESCRIPTION
**Pull request by Hibi-10000**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

Related: #135131 

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135270)

### CODE REVIEW

**Comment by Hibi-10000** [comment]
[PR Validation > Validate Manifest](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=533463&view=logs&j=dc5484e7-078c-5e69-1cbb-0f132d85a80e&t=3990e129-bab1-55f1-b6c9-010c1219a3a4&l=27)
> Processing manifest: manifests\a\Ablaze\Floorp\Daylight\11.7.1

🤔

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  2024-01-19T03:22:28.7933415Z ##[section]Starting: Download secrets: kv-pkgman-centus-pme
 2024-01-19T03:22:29.2228202Z ==============================================================================
 2024-01-19T03:22:29.2229521Z Task         : Azure Key Vault
 2024-01-19T03:22:29.2230040Z Description  : Download Azure Key Vault secrets
 2024-01-19T03:22:29.2230296Z Version      : 1.232.0
 2024-01-19T03:22:29.2230704Z Author       : Microsoft Corporation
 2024-01-19T03:22:29.2231231Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/deploy/azure-key-vault

(Automated response - build 619.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-19T03:18:22.3058966Z ##[error] One or more errors occurred. (Sequence contains no elements) Sequence contains no elements

(Automated response - build 620.)

**Comment by drshtmstry** [comment]
> Sequence contains no elements

- #133371

**Comment by Hibi-10000** [comment]
New version: #135708

**Pull request closed without merging**
