### PR TITLE
Nelson 0.4.4 available in winget

### PR DESCRIPTION
**Pull request by Nelson-numerical-software**
Nelson is an array programming language providing a powerful open computing environment for engineering and scientific applications using modern C/C++ libraries (Boost, Eigen, …) and others state of art numerical libraries.

It has sophisticated data structures (including cell, struct, linear systems, …), an interpreter and a high level programming language.

Nelson has been developped to be an open/modular system where an user can define these own data types and operations on these data types by using overload.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/853)

### CODE REVIEW

**Comment by Nelson-numerical-software** [comment]
Trouble reported:
Submission details: nelson-0.4.4.2521-x86-64.exeSubmission ID: 760ab3ff-6f75-43a2-a354-eddff1e3540fStatus: SubmittedSubmitted by: nelson.numerical.computation@gmail.comSubmitted: May 25, 2020 21:18:22User Opinion: Incorrect detection

I publish each month a new version. do I need to repost a new Pull request each time ?

**Comment by Nelson-numerical-software** [comment]
image

**Comment by Nelson-numerical-software** [comment]
image

Please merge my PR

**Comment by Nelson-numerical-software** [comment]
"Needs: author feedback" Removed
Please consider this Pull Request

**Comment by Nelson-numerical-software** [comment]
Any news about this PR ?

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
