### PR TITLE
Add ProtonVPN 1.15.0

### PR DESCRIPTION
**Pull request by kutoswiss**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/991)

### CODE REVIEW

**Comment by denelon** [comment]
@kutoswiss I got Installer failed with exit code: 3758096385. Did you install this on your local machine with `winget install -m 1.15.0.yaml`? Does this require elevated terminal?

**Comment by kutoswiss** [comment]
@denelon I installed it on my machine using `winget install -m 1.15.0.yaml` and works well without any elevated privileges. 

However I can reproduce the issue when I try to install it with an elevated terminal as you probably did. Do we need to satisfy this condition ? I also go an error window with the message "Invalid command line".

image

**Comment by kutoswiss** [comment]
@denelon I found the issue. I added wrong silent switches to the yaml file. Should be fine now.

**Review by ghost — APPROVED** [review]
Validation has completed

**Review by ghost — APPROVED** [review]
Validation has completed

**Review by ghost — APPROVED** [review]
Validation has completed

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
