### PR TITLE
New version: Citrix.Workspace version 23.9.0.99

### PR DESCRIPTION
**Pull request by lryanuk**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/122047)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by vidarak** [comment]
Hi. It seems like Citrix has removed this specific download. Can't find a working static URL for the same file/version. Any ideas?

**Comment by lryanuk** [comment]
> Hi. It seems like Citrix has removed this specific download. Can't find a working static URL for the same file/version. Any ideas?

I'm not aware of any other static URLs that could be used for this application. I've checked a few previous versions and the download URLs appear to still be working for those so it's only the latest impacted.

**Comment by MietekW** [comment]
@lryanuk  can you pull this version from the Winget store as long as the URL doesn't work it will fail.
We have a case open with Citrix but they do not seem to understand the impact yet.

**Comment by MietekW** [comment]
@lryanuk Citrix confirmed they pulled the file indeed due to bugs, I don't have any specifics yet, no ETA when it is available again.
Can you remove this version from the Winget store so we can use it again to install the latest (working) citrix.workspace ?

Thanks

**Comment by vidarak** [comment]
> @lryanuk Citrix confirmed they pulled the file indeed due to bugs, I don't have any specifics yet, no ETA when it is available again. Can you remove this version from the Winget store so we can use it again to install the latest (working) citrix.workspace ?
> 
> Thanks

temporary workaround is:
winget install Citrix.Workspace -e -v 23.7.1.18

**Comment by vidarak** [comment]
Citrix did release a new version 2309.1 now. https://docs.citrix.com/en-us/citrix-workspace-app-for-windows/about.html#fixed-issues-in-23091

**Pull request merged**
