### PR TITLE
Added Mazerator-Old Nightly 20200428

### PR DESCRIPTION
**Pull request by AwesomeKalin**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/9780)

### CODE REVIEW

**Comment by AwesomeKalin** [comment]
What is the problem?

**Comment by KevinLaMS** [comment]
@AwesomeKalin the installer just seems to drop a couple GUIDs on my PC.  Is that supposed to be correct?  How do I verify it installed correctly and how do I use?  thanks

**Comment by AwesomeKalin** [comment]
I'm going to have to double check that myself and see tomorrow. I'm on my phone!

**Comment by AwesomeKalin** [comment]
OK, so I just tested it and it works 100%. Maybe to verify it works, check your Program Files folder?

**Comment by AwesomeKalin** [comment]
Any update on this @KevinLaMS

**Comment by KevinLaMS** [comment]
No way this is going to work, but kicking off automated verification again.

**Pull request merged**
