### PR TITLE
New Package: NuzuEmu.Nuzu.EarlyAccess version 4176

### LINKED ISSUE #142143: [Package Request]: Nuzu
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url:
Publisher: Nicola
Package Name: Nuzu
Description: Nuzu is an open-source Nintendo Switch emulator
Package Version: EA-4176
Installer URL: https://github.com/Nikilites/nuzu/releases/download/Nuzu/Windows-Nuzu.YUZU.-EA-4176.zip

### PR DESCRIPTION
**Pull request by og-mrk**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

* Resolves https://github.com/microsoft/winget-pkgs/issues/142143
---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/142214)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\yuzu.exe returned exit code: -1073741515
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\yuzu-cmd.exe returned exit code: -1073741515
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\yuzu-room.exe returned exit code: -1073741515

(Automated response - build 861.)

**Comment by og-mrk** [comment]
> Automatic Validation ended with:
> 
> > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\yuzu.exe returned exit code: -1073741515
> > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\yuzu-cmd.exe returned exit code: -1073741515
> > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\yuzu-room.exe returned exit code: -1073741515
> 
> (Automated response - build 861.)

Hi there @stephengillie,
The Nuzu Emulator, which in reality it's Yuzu's Early Access Build, _this's according to the Source of this program (a Github Repo)_, does work perfectly fine when running it, it'll popup an Error if you don't pass to it An Expected Parameter, which states it needs an Encryption Key(s) of some sort. Which I guess it installs perfectly fine, but the Azure Pipeline can't handle such cases.

### Screenshot for proving previous statement
image

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-03-06 08:07:46.573 [CORE] Started applying motw to C:\Users\User\AppData\Local\Temp\WinGet\NuzuEmu.Nuzu.EarlyAccess.4176\b5d5a12dd2320f442187919ef9e9680a83c36d98fa80584f13114face49bf2a0 with zone: 3 
> 2024-03-06 08:07:46.575 [CORE] Finished applying motw 
> 2024-03-06 08:07:46.575 [CORE] WinINet downloading from url: https://github.com/Nikilites/nuzu/releases/download/Nuzu/Windows-Nuzu.YUZU.-EA-4176.zip 
> 2024-03-06 08:07:46.620 [CORE] Download request failed. Returned status: 404 
> 2024-03-06 08:07:46.620 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFBF18B8767: (caller: 00007FFBF18B9FC9) Exception(4) tid(f90) 80190194 Not found (404). 

(Automated response - build 861.)

**Comment by stephengillie** [comment]
URL: https://github.com/Nikilites/nuzu/releases/download/Nuzu/Windows-Nuzu.YUZU.-EA-4176.zip 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 861)

**Comment by og-mrk** [comment]
Closing due to The source posting 404 (Not Found)

**Pull request closed without merging**
