### PR TITLE
GlobalMarineNet.xocml version 1.31a

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/107509)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by upintheairsheep** [comment]
> Automatic Validation ended with: image

Use the switch.

**Comment by stephengillie** [comment]
> Use the switch.

Could you be more specific about which switch should be used here?

**Comment by upintheairsheep** [comment]
> > Use the switch.
> 
> Could you be more specific about which switch should be used here?

/NCRC

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by upintheairsheep** [comment]
Screenshot?

**Comment by stephengillie** [comment]
It's unchanged. 
https://user-images.githubusercontent.com/114952565/240073035-e80fc952-0f3f-4b66-9481-317c90eca4f8.png
(saving bandwidth)

**Comment by ItzLevvie** [comment]
[Policy] Interactive-Only-Installer

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Pull request closed without merging**
