### PR TITLE
New version: eza-community.eza version 0.18.4

### PR DESCRIPTION
**Pull request by cafkbot-winget**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140470)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-21 21:47:39.405 [FAIL] Installer failed security check. Url: https://github.com/eza-community/eza/releases/download/v0.18.4/eza.exe_x86_64-pc-windows-gnu.zip Result: 0x80004005 2024-02-21 21:47:39.405 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6

(Automated response - build 795.)

**Comment by stephengillie** [comment]
Hi @cafkbot-winget,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 800.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-21 21:47:39.405 [FAIL] Installer failed security check. Url: https://github.com/eza-community/eza/releases/download/v0.18.4/eza.exe_x86_64-pc-windows-gnu.zip Result: 0x80004005 2024-02-21 21:47:39.405 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6

(Automated response - build 800.)

**Comment by stephengillie** [comment]
Hi @cafkbot-winget,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 800.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-21 21:47:39.405 [FAIL] Installer failed security check. Url: https://github.com/eza-community/eza/releases/download/v0.18.4/eza.exe_x86_64-pc-windows-gnu.zip Result: 0x80004005 2024-02-21 21:47:39.405 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6

(Automated response - build 800.)

**Comment by stephengillie** [comment]
Hi @cafkbot-winget,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 800.)

**Comment by stephengillie** [comment]
Hi @cafkbot-winget,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 801.)

**Comment by stephengillie** [comment]
Hi @cafkbot-winget,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 806.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-21 21:47:39.405 [FAIL] Installer failed security check. Url: https://github.com/eza-community/eza/releases/download/v0.18.4/eza.exe_x86_64-pc-windows-gnu.zip Result: 0x80004005 2024-02-21 21:47:39.405 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6

(Automated response - build 806.)

**Comment by cafkafk** [comment]
What is going on here???????????

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
