### PR TITLE
New version: Microsoft.PowerAutomateDesktop version 2.36.146.23279

### LINKED ISSUE #122541: [Package Issue]: Microsoft.PowerAutomateDesktop
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

Installer hash mismatch

### Steps to reproduce

Manifest hash is: A005C875BFD225F21435DE50EF54BD9C9EB6CED9F817E28BF4FA130C0B6F8ED8

### Actual behavior

Manifest hash is: A005C875BFD225F21435DE50EF54BD9C9EB6CED9F817E28BF4FA130C0B6F8ED8

### Expected behavior

Manifest hash is should be: 3596772CC11156E989B35437BC730A33FEF1D853E661D93D8882C53A8F8B672D

### Environment

```raw
Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

### Screenshots and Logs

_No response_

### PR DESCRIPTION
**Pull request by mdanish-kh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

- Resolves #122541

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/122858)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by olegpro81** [comment]
Any idea why this is happening on a regular basis for random apps?

**Comment by mdanish-kh** [comment]
@olegpro81 Hash mismatch typically means that the publisher uses a "vanity"/non-versioned URL and a newer version has been released that is causing the hash mismatch. Whenever you encounter an issue like this, it's best to [create an issue](https://github.com/microsoft/winget-pkgs/issues/new) for it, so that contributors (or even better yourself if you want) can update the package with a PR.

**Comment by mdanish-kh** [comment]
This will be fixed by:
- #125481

**Comment by olegpro81** [comment]
@mdanish-kh - are there any instructions how to update the package?

**Comment by olegpro81** [comment]
Thanks.

Regards,
Oleg
647-881-6305

**Comment by mdanish-kh** [comment]
@olegpro81 You can get started by going through the [submitting a package](https://github.com/microsoft/winget-pkgs#submitting-a-package) guide in the README. If you prefer video over text, there's also an Open at Microsoft episode: [Contributing to Windows Package Manager](https://learn.microsoft.com/en-us/shows/open-at-microsoft/contributing-to-windows-package-manager)

**Pull request merged**
