### PR TITLE
Madsen.VBinDiff version 3.0-beta.5

### PR DESCRIPTION
**Pull request by cn-ml**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/103725)

### CODE REVIEW

**Comment by cn-ml** [comment]
@microsoft-github-policy-service agree

**Comment by cn-ml** [comment]
> This may happen for sites with policies prohibiting distribution or use by third parties.

All programs on [Christopher J. Madsen](https://www.cjmweb.net/) website seem to be licensed under GPLv2 or later and thus free for redistribution.

> This may happen for URLs pointing to domains that do not align with the publisher domain or package domain. If you could provide supporting evidence from the publisher that the URLs for the installer are correct, that would help us to validate and approve this PR.

The download URL is a direct descendant of the project URL, did I use a wrong key in the YAML file?

Here are the relevant urls:

| Type | URL |
|--------|--------|
| Project | https://www.cjmweb.net/vbindiff/ |
| Download | https://www.cjmweb.net/vbindiff/VBinDiff-3.0_beta5.zip |

**Comment by stephengillie** [comment]
> The download URL is a direct descendant of the project URL, did I use a wrong key in the YAML file?
> 
> Here are the relevant urls:
> 
> Type	URL
> Project	https://www.cjmweb.net/vbindiff/
> Download	https://www.cjmweb.net/vbindiff/VBinDiff-3.0_beta5.zip

This check likely occurred because it's a site with relatively little traffic. I've verified that the InstallerUrl can be found by navigating from the PackageUrl, and that it's the developer's site instead of a 3rd party download site.

**Comment by stephengillie** [comment]
This package is expecting arguments:
```
VBinDiff 3.0_beta5
Copyright 1995-2017 Christopher J. Madsen
Usage: VBinDiff.exe FILE1 [FILE2]
Compare FILE1 and FILE2 byte by byte.
If FILE2 is omitted, just display FILE1.

Options:
      --help               display this help information and exit
      -L, --license        display license & warranty information and exit
      -V, --version        display version information and exit
```

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
