### PR TITLE
New version: calibre.calibre version 5.44.0 [FP-D]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | calibre | calibre 64bit    |
| Version     | 5.44.0     | 5.44.0 |
| Publisher   | Kovid Goyal   | Kovid Goyal      |
| ProductCode | {A29ECCA4-0F80-40F2-A69B-6DF3C3FF5BAE}          | {A29ECCA4-0F80-40F2-A69B-6DF3C3FF5BAE}    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [2204](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/2513491084>)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by jedieaston** [comment]
Once more for good measure...

**Comment by ItzLevvie** [comment]
```
2022-05-27 05:16:28.466   Message box (OK):
                          Could not find Git; can not register Git LFS.
```

from Azure Pipelines logs.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/61992#issuecomment-1140137052

**Comment by jedieaston** [comment]
I’m your huckleberry, @msftbot

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
