### PR TITLE
Fixed Razer.Synapse.2

### PR DESCRIPTION
**Pull request by OfficialEsco**
Silent install not possible since it extracts itself
Should probably be added just because people want it and it won't update.

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/16225)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
@denelon thoughts?

**Comment by denelon** [comment]
Do we know if anyone has attempted to contact them to see about getting an upgrade that will do a silent install? Until we can get https://github.com/microsoft/winget-cli/issues/910 done I'm between a rock and a hard place.

**Comment by OfficialEsco** [comment]
Chocolatey does `/S /v/qn` but that doesn't seem to work here, maybe a missing feature?

**Comment by denelon** [comment]
No clue ¯\_(ツ)_/¯

**Comment by denelon** [comment]
@OfficialEsco, I think you did it!

**Comment by OfficialEsco** [comment]
Naaah its cheating, the file it downloads is a extractable, you will be stuck on a MSI window after that, which is why Chocolatey does `/v/qn`
This is how it passed automatic validation.

**Comment by denelon** [comment]
Bummer

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/16225#issuecomment-854948270

**Comment by OfficialEsco** [comment]
@denelon add `Blocking-Issue` and `Validation-Unattended-Failed` on this and #16230

**Pull request closed without merging**
