### PR TITLE
Update: Nvidia.CUDA version 12.6 (12.6.2)

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#8491](https://github.com/SpecterShell/Dumplings/actions/runs/11131811039).

<details>

<summary>Log</summary>

````
Updated: 12.6.1 → 12.6.2
Submitting WinGet manifests
Found existing pull requests:
Update: Nvidia.CUDA version 12.6 (12.6.1) - https://github.com/microsoft/winget-pkgs/pull/170631
New version: Nvidia.CUDA version 12.6 (12.6.0) - https://github.com/microsoft/winget-pkgs/pull/165663
The existing pull requests are ignored as the version is updated while the real version isn't
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/176300)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 896.)

**Review by aisgbnok — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by SpecterShell** [comment]
Installs normally in the sandbox.

image

**Comment by SpecterShell** [comment]
Installs normally in the sandbox. @stephengillie

image

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
> Installs normally in the sandbox. @ stephengillie
> 

Thank you for reminding me. Between high PR load and DSC work, I haven't had the time to go back and dredge the repo for PRs like this.

**Pull request merged**
