### PR TITLE
New package: JeremyHu.Dust3D version 1.0.0-rc.9

### LINKED ISSUE #112171: [Package Request]: dust3d
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://dust3d.org/
Publisher:  https://github.com/huxingyi
Package Name: Dust3D
Description: Low Poly Modeling Tool
Package Version: 1.0.0-rc.7
Installer URL: https://github.com/huxingyi/dust3d/releases/download/1.0.0-rc.7/dust3d-1.0.0-rc.7.zip
Changelog: https://github.com/huxingyi/dust3d/releases/tag/1.0.0-rc.7

### PR DESCRIPTION
**Pull request by RobertHarnett**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

fixes https://github.com/microsoft/winget-pkgs/issues/112171

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/112787&drop=dogfoodAlpha

### CODE REVIEW

**Comment by RobertHarnett** [comment]
Completing package request #112171

**Comment by stephengillie** [comment]
Manual Validation ended with:
image

**Comment by luzpaz** [comment]
Upstream fixed this in and cut a new release https://github.com/huxingyi/dust3d/issues/147?notification_referrer_id=NT_kwDOAD8s17I3MDcxOTc3MjA2OjQxNDAyNDc&notifications_query=is%3Aunread#issuecomment-1653535330

**Comment by RobertHarnett** [comment]
Updated to [the new version that fixes the dependency issue](https://github.com/huxingyi/dust3d/issues/147#issuecomment-1653535330),

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
