### PR TITLE
New version: Unity.Unity.2022 version 2022.3.55f1

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#10360](https://github.com/SpecterShell/Dumplings/actions/runs/12391593205).

<details>

<summary>Log</summary>

````
Updated: 2022.3.54f1 → 2022.3.55f1
Submitting WinGet manifests
Creating manifests
The locale entry "ReleaseNotes" has an invalid value and thus discarded: The running command stopped because the preference variable "WarningPreference" or common parameter is set to Stop: The string has a length of 10331, longer than the maximum length 10000
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/199563)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Pull request merged**
