### PR TITLE
Update ROBLOXCorporation.RobloxBootstrapper to use official sources

### PR DESCRIPTION
**Pull request by thomasthebro1**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/17871)

### CODE REVIEW

**Comment by KaranKad** [comment]
Only one manifest can be edited in one pr. So you need to create different pr's for deleting and submitting new manifest.

**Comment by KaranKad** [comment]
I'll delete the old one

**Comment by thomasthebro1** [comment]
Thanks. Should I create a new PR once the original files have been deleted?

**Comment by KaranKad** [comment]
Files are deleted. You can create it now.

**Comment by OfficialEsco** [comment]
In GitHub Desktop you can revert `Delete ROBLOXCorporation.RobloxBootstrapper (unofficial installer sources)`

**Comment by KaranKad** [comment]
Change `PackageIdentifier` to `Roblox.launcher`

**Comment by thomasthebro1** [comment]
OK will do.

**Comment by thomasthebro1** [comment]
Sorry about being slow this is my first time contributing to this project :)

**Comment by KaranKad** [comment]
Don't worry, you are doing well. 😁

**Comment by thomasthebro1** [comment]
#17877

**Comment by OfficialEsco** [comment]
Better safe then sorry, make sure the `Publisher`, `PackageVersion` and `PackageName` matches what `Add or Remove Programs`/`Programs and Features` reports (Roblox works because it looks for Roblox *wildcard*)
Extra and accurate information is always nice.
You could try [YamlCreate.ps1](https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1) if you like to add proper metadata, then you can add extra metadata with manual edit once generated.

**Pull request closed without merging**
