### PR TITLE
Microsoft.OfficeDeploymentTool version 16.0.16327.20214

### LINKED ISSUE #103927: [Update Request]: Microsoft.OfficeDeploymentTool + old ones are dead
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.OfficeDeploymentTool

### Package Version

16.0.16227.20258

### Please describe the changes you would like to see

https://download.microsoft.com/download/2/7/A/27AF1BE6-DD20-4CB4-B154-EBAB8A7D4A7E/officedeploymenttool_16227-20258.exe

Btw the install links of old versions of the package is dead.
Maybe the package could be reenginered as a portable installation, using
https://officecdn.microsoft.com/pr/wsus/setup.exe

### PR DESCRIPTION
**Pull request by BrandonWanHuanSheng**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

Resolves #103927 

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/105168)

### CODE REVIEW

**Comment by stephengillie** [comment]
This package is a little odd:
- Seems to install normally
- No shortcuts or bookmarks
- Installs to `C:\Program Files\OfficeDeploymentTool\`
- In this folder are 4 website links and 1 `setup.exe`
- Running this `setup.exe` results in:
image

**Comment by BrandonWanHuanSheng** [comment]
It look like the configuration file was in "C:\Program Files\OfficeDeploymentTool\"

**Comment by BrandonWanHuanSheng** [comment]
Most likely could be portable program.

**Comment by BrandonWanHuanSheng** [comment]
It look like that this setup is asking for the location, https://download.microsoft.com/download/2/7/A/27AF1BE6-DD20-4CB4-B154-EBAB8A7D4A7E/officedeploymenttool_16227-20258.exe

**Comment by BrandonWanHuanSheng** [comment]
> This package is a little odd:
> 
> * Seems to install normally
> * No shortcuts or bookmarks
> * Installs to `C:\Program Files\OfficeDeploymentTool\`
> * In this folder are 4 website links and 1 `setup.exe`
> * Running this `setup.exe` results in:
>   image

It look like people make their configuration by themselves.

**Comment by BrandonWanHuanSheng** [comment]
??

**Comment by stephengillie** [comment]
This package appears to have been removed:
image

**Comment by BrandonWanHuanSheng** [comment]
@stephengillie you were too late.

**Comment by BrandonWanHuanSheng** [comment]
Set force push request.

**Comment by BrandonWanHuanSheng** [comment]
> This package appears to have been removed: image

@stephengillie It look like it move the link? You can generate the link over here.
https://www.microsoft.com/en-us/download/confirmation.aspx?id=49117
New URL: https://download.microsoft.com/download/2/7/A/27AF1BE6-DD20-4CB4-B154-EBAB8A7D4A7E/officedeploymenttool_16327-20214.exe

**Comment by stephengillie** [comment]
> > This package appears to have been removed: image
> 
> @stephengillie It look like it move the link? You can generate the link over here. https://www.microsoft.com/en-us/download/confirmation.aspx?id=49117 New URL: https://download.microsoft.com/download/2/7/A/27AF1BE6-DD20-4CB4-B154-EBAB8A7D4A7E/officedeploymenttool_16327-20214.exe

Oh - this kind of link expires quickly and will need to be regenerated too often.

**Comment by BrandonWanHuanSheng** [comment]
> > > This package appears to have been removed: image
> > 
> > 
> > @stephengillie It look like it move the link? You can generate the link over here. https://www.microsoft.com/en-us/download/confirmation.aspx?id=49117 New URL: https://download.microsoft.com/download/2/7/A/27AF1BE6-DD20-4CB4-B154-EBAB8A7D4A7E/officedeploymenttool_16327-20214.exe
> 
> Oh - this kind of link expires quickly and will need to be regenerated too often.

Yes, which is true.

**Comment by BrandonWanHuanSheng** [comment]
Checking to see if there is URL.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
