### PR TITLE
Revert "Trigger label description replies in issues"

### PR DESCRIPTION
**Pull request by mdanish-kh**
Reverts microsoft/winget-pkgs#103148

cc @denelon, sorry for the inconvenience; I wish the configs were documented publicly
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/103211)

### CODE REVIEW

**Comment by denelon** [comment]
I think this might have been an "issue" responder rather than a PR responder. I can't remember the exact syntax myself :(

**Comment by denelon** [comment]
https://github.com/microsoft/winget-pkgs/blob/785d437f8857b9a43d9532c8df8e3f652df85000/.github/fabricbot.json#L7

**Comment by mdanish-kh** [comment]
The intention was to make it an "issue" responder as we already have it working for PRs 

(it may have gotten confusing in the diffs as I modified the description of PR autoresponders to make room for the new ones 😅)

**Comment by mdanish-kh** [comment]
I looked at how the `Needs-Triage` addLabel event works for the implementation

https://github.com/microsoft/winget-pkgs/blob/785d437f8857b9a43d9532c8df8e3f652df85000/.github/fabricbot.json#L3407-L3412

**Comment by denelon** [comment]
@mdanish-kh & @Trenly could it be what I put above?

**Comment by denelon** [comment]
OK, my response was written before the page refreshed with your comments. Do you want me to approve/merge this one?

**Comment by mdanish-kh** [comment]
Since the configurations do not work :sadface:, I think we can go ahead merging this PR

**Review by denelon — APPROVED** [review]

**Pull request merged**
