### PR TITLE
New version: Mozilla.Thunderbird version 115.9.0

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings).
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/145280)

### CODE REVIEW

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Comment by exoosh** [comment]
For some strange reason I was handed the `en-CA` (Canadian English?) installer based on the latest manifest. As far as I can recall previously it was always `en-US`.

The curious thing is that my system definitely has never been set to `en-CA` before and while I adjusted some regional settings to be more international, my system and user locale is `en-US`.

**Comment by SpecterShell** [comment]
> For some strange reason I was handed the `en-CA` (Canadian English?) installer based on the latest manifest. As far as I can recall previously it was always `en-US`.
> 
> The curious thing is that my system definitely has never been set to `en-CA` before and while I adjusted some regional settings to be more international, my system and user locale is `en-US`.

Sorry for late reply.

This bug existed in the previous PRs but it should have been fixed with this PR. I just tested on my machine with `en-US` user locale and it handed the `en-US` installer. 🤔

@exoosh

**Pull request merged**
