### PR TITLE
Graphviz.Graphviz version 7.10

### PR DESCRIPTION
**Pull request by sanyer**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/97776)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by sba923** [comment]
@sanyer IMVHO this package is flawed, as it labels  as version `7.10` an application whose actual (internal, registry) version number is `7.1.0`.

As a result, `winget` currently (incorrectly) states that the new version `7.10` is available when you have the latest version `7.1.0` installed:

image

````
PS> winget show Graphviz.Graphviz
Found Graphviz [Graphviz.Graphviz]
Version: 7.10
Publisher: Graphviz
Publisher Url: https://graphviz.org/
Publisher Support Url: https://graphviz.org/documentation/
Moniker: graphviz
Description: The Graphviz layout programs take descriptions of graphs in a simple text language, and make diagrams in useful formats, such as images and SVG for web pages; PDF or Postscript for inclusion in other documents; or display in an interactive graph browser. Graphviz has many useful features for concrete diagrams, such as options for colors, fonts, tabular node layouts, line styles, hyperlinks, and custom shapes.
Homepage: https://graphviz.org/download/
License: Common Public License Version 1.0
License Url: https://graphviz.org/license/
Copyright: (c) 2022 The Graphviz Authors
Tags:
  diagrams
  graph
  visualization
Installer:
  Installer Type: nullsoft
  Installer Url: https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/7.1.0/windows_10_cmake_Release_graphviz-install-7.1.0-win64.exe
  Installer SHA256: 76067070bab280a36882fdb7bb7d7b79498d1f060c2da51e17833b94b19acb21
````

**Comment by sanyer** [comment]
@sba923  I've submitted a fix #98082

**Comment by sba923** [comment]
> @sba923 I've submitted a fix #98082

Great! Waiting for the package to ripple up to the package repo.

**Comment by sba923** [comment]
> > @sba923 I've submitted a fix #98082
> 
> Great! Waiting for the package to ripple up to the package repo.

It's there! Thanks for the fix.

````
PS> winget show Graphviz.Graphviz
Found Graphviz [Graphviz.Graphviz]
Version: 7.1.0
Publisher: Graphviz
Publisher Url: https://graphviz.org/
Publisher Support Url: https://graphviz.org/documentation/
Moniker: graphviz
Description: The Graphviz layout programs take descriptions of graphs in a simple text language, and make diagrams in useful formats, such as images and SVG for web pages; PDF or Postscript for inclusion in other documents; or display in an interactive graph browser. Graphviz has many useful features for concrete diagrams, such as options for colors, fonts, tabular node layouts, line styles, hyperlinks, and custom shapes.
Homepage: https://graphviz.org/download/
License: Common Public License Version 1.0
License Url: https://graphviz.org/license/
Copyright: (c) 2022 The Graphviz Authors
Tags:
  diagrams
  graph
  visualization
Installer:
  Installer Type: nullsoft
  Installer Url: https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/7.1.0/windows_10_cmake_Release_graphviz-install-7.1.0-win64.exe
  Installer SHA256: 76067070bab280a36882fdb7bb7d7b79498d1f060c2da51e17833b94b19acb21
````

**Comment by sanyer** [comment]
No worries, thanks for sharing this issue @sba923

**Pull request merged**
