### PR TITLE
New version: Diskuv.opam version 2.2.0-beta3

### PR DESCRIPTION
**Pull request by jonahbeckford**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/157658)

### CODE REVIEW

**Comment by jonahbeckford** [comment]
I can't find anywhere in the Azure Pipelines steps and logs what the actual problem is.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-06-13 02:02:31.145 [FAIL] Installer failed security check. Url: https://github.com/diskuv/dkml-installer-opam/releases/download/2.2.0-beta3-20240611/unsigned-opam-windows_x86-i-2.2.0-beta3-20240611.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 885.)

**Comment by jonahbeckford** [comment]
> I've automated the above into a PowerShell script, which then filters for "error", "exception" and "fail", and then filters out the noise.

I don't see your script but it was simple enough for me to use `grep --color` on the logs. Thanks for the useful information!

I'll let it do its security check again but since the inputs aren't changing that doesn't sound promising.

Since it seems to be affecting only the x86 32-bit installer I'll drop that for this release if it fails again. But more generally, we've had problems with false positives in Windows Defender for OCaml binaries (this `Diskuv.opam` package is for the OCaml package manager, and I'm guessing all programming language package managers and compilers do poorly with AV heuristics).

Any suggestions would be appreciated. For a while we signed packages, but that didn't meaningfully reduce the Windows Defender false positives (and cost money and was a pain).

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
