### PR TITLE
New version: GitTools.GitVersion version 6.0.0

### PR DESCRIPTION
**Pull request by arturcic**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164102)

### CODE REVIEW

**Comment by arturcic** [comment]
@stephengillie may I get information on what exactly fails?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-07-23 00:34:41.724 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF8BA22C11F: (caller: 00007FF8B9FB8D6F) LogHr(1) tid(944) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF8BA132B08: (caller: 00007FF8BA1DBC20) Exception(1) tid(944) 8A15005E ] 
> 2024-07-23 00:34:49.153 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF89DC1C11F: (caller: 00007FF89D9A8D6F) LogHr(1) tid(167c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF89DB22B08: (caller: 00007FF89DBCBC20) Exception(1) tid(167c) 8A15005E ] 
> 2024-07-23 00:36:05.600 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.0/gitversion-win-x64-6.0.0.zip Result: 0x80004005
> 2024-07-23 00:35:05.941   Function name: GetLastError
> 2024-07-23 00:35:30.317   Creating directory: C:\Program Files\Git\usr\share\perl5\core_perl\autodie\exception
> 2024-07-23 00:35:32.285   Creating directory: C:\Program Files\Git\usr\share\perl5\vendor_perl\Error
> 2024-07-22 21:15:20.985 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!6883535B: (caller: 68731A80) LogHr(1) tid(a84) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!6887B5DD: (caller: 689112BF) Exception(1) tid(a84) 8A15005E ] 
> 2024-07-22 21:15:28.786 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!553C535B: (caller: 552C1A80) LogHr(1) tid(1a74) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!5540B5DD: (caller: 554A12BF) Exception(1) tid(1a74) 8A15005E ] 
> 2024-07-22 21:16:37.962 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.0/gitversion-win-x64-6.0.0.zip Result: 0x80004005
> 2024-07-22 21:15:41.753   Function name: GetLastError
> 2024-07-22 21:16:00.956   Creating directory: C:\Program Files\Git\usr\share\perl5\core_perl\autodie\exception
> 2024-07-22 21:16:02.706   Creating directory: C:\Program Files\Git\usr\share\perl5\vendor_perl\Error

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 887.)

**Comment by arturcic** [comment]
@stephengillie I wonder why it fails the CI as if I try installing locally from the manifest 
```pwsh
winget install --manifest .\GitTools\GitVersion\6.0.0
```
it is installed and can be used without issues

**Comment by DuckDuckStudio** [comment]
https://github.com/microsoft/winget-pkgs/labels/Internal-Error-Dynamic-Scan is due to dependencies `Git.Git` (my package also experienced this problem)
About the Installer failed security check... I recommend submitting the installer to [Microsoft Security Intelligence](https://www.microsoft.com/en-us/wdsi/filesubmission/) for analysis.

**Comment by arturcic** [comment]
> [ Internal-Error-Dynamic-Scan](https://github.com/microsoft/winget-pkgs/labels/Internal-Error-Dynamic-Scan) The test for Dynamic Scanning in the Installation Validation failed. is due to dependencies `Git.Git` (my package also experienced this problem) About the Installer failed security check... I recommend submitting the installer to _[Microsoft Security Intelligence](https://www.microsoft.com/en-us/wdsi/filesubmission/)_ for analysis.

Can you provide details on how you solved the `Git.Git` dependency issue?

**Comment by DuckDuckStudio** [comment]
> @DuckDuckStudio Can you provide details on how you solved the dependency issue?

This only can let @stephengillie to manually verify it...

**Comment by arturcic** [comment]
> > @DuckDuckStudio Can you provide details on how you solved the dependency issue?
> 
> This only can let @stephengillie to manually verify it...

@DuckDuckStudio @stephengillie does this mean on every new release we need to manually verify?

**Comment by DuckDuckStudio** [comment]
> Does this mean on every new release we need to manually verify?

It seems that the manifest can only pass automated validation once `Git.Git` no longer requires manual verification.
The latest two versions of `Git.Git`: #156357 #153605

**Comment by stephengillie** [comment]
Hi @arturcic,

Unfortunately, yes. Since Git is used by the pipeline VMs, installing it conflicts with validation, causing the IEDS label to be applied to the VM. Every Git package needs manual validation. 

- https://github.com/microsoft/winget-pkgs/discussions/155218

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

Apologies for this PR needing so much manual intervention.

**Comment by arturcic** [comment]
> * [Policy Service sometimes doesn’t enable automerge #142854](https://github.com/microsoft/winget-pkgs/issues/142854)
> 
> Apologies for this PR needing so much manual intervention.

No worries, I will just make sure to mention next time that it needs manual validation due to Git dependency

**Pull request merged**
