### PR TITLE
New package: TimKosse.FileZilla version 3.67.0

### PR DESCRIPTION
**Pull request by Jvr2022**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/149668)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Jvr2022,

[In the past](https://github.com/microsoft/winget-pkgs/issues/78578), this package was blocked by requiring a license. Is this still the case?

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-04-17 20:03:24.793 [CORE] WinINet downloading from url: https://dl1.cdn.filezilla-project.org/client/FileZilla_3.67.0_win64-setup.exe?h=r8SjxgDSopBVF2EzNIx8Jw&x=1713377005 
> 2024-04-17 20:03:25.555 [CORE] Download request failed. Returned status: 403 
> 2024-04-17 20:03:25.555 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFB5F598767: (caller: 00007FFB5F599FC9) Exception(4) tid(1e7c) 80190193 Forbidden (403).      Msg:[Download request status is not success.]   
> 2024-04-17 20:03:25.647 [CLI ] Caught wil::ResultException: C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFB5F598767: (caller: 00007FFB5F599FC9) Exception(4) tid(1e7c) 80190193 Forbidden (403).      Msg:[Download request status is not success.]   

(Automated response - build 876.)

**Comment by Jvr2022** [comment]
Hi there,

I am gonna look to this problem and fix it

**Comment by ItzLevvie** [comment]
Close with reason: Please see https://github.com/microsoft/winget-pkgs/issues/78578;

**Comment by ItzLevvie** [comment]
Close with reason: Please see issue 78578;

**Pull request closed without merging**
