### PR TITLE
Update D:\Git\winget-pkgs\manifests\s\SlackedLime\TimeSpent\1.2

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114632&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
image

**Comment by stephengillie** [comment]
This package installs normally, but when launched it closes immediately. I'll pass it anyway, because it's already in the manifest.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
