### PR TITLE
New version: Box.Box version 2.26.330

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

* Closes #57696

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/57692)

### CODE REVIEW

**Comment by Trenly** [comment]
I get this with a 1603 when running in Sandbox; Probably just a sandbox issue though; I'll wait for someone else to test on VM
```
Calling custom action Box.Desktop.Installer.CustomActions!CustomActions.CustomActions.CreateFallbackDeviceIDKey
Begin CreateFallbackDeviceIDKey
  setting:e92f1a52-778d-404b-8f25-74615e4b3264
MSI (s) (F0:1C) [15:20:42:643]: Product: Box -- Error 1935. An error occurred during the installation of assembly component {22D75DAD-658C-3109-91F7-4CB1A0729109}. HRESULT: 0x80070003. assembly interface: IAssemblyCache, function: CreateAssemblyCacheItem, assembly name: Microsoft.VC90.CRT,version="9.0.30729.6161",publicKeyToken="1fc8b3b9a1e18e3b",processorArchitecture="amd64",type="win32"

Error 1935. An error occurred during the installation of assembly component {22D75DAD-658C-3109-91F7-4CB1A0729109}. HRESULT: 0x80070003. assembly interface: IAssemblyCache, function: CreateAssemblyCacheItem, assembly name: Microsoft.VC90.CRT,version="9.0.30729.6161",publicKeyToken="1fc8b3b9a1e18e3b",processorArchitecture="amd64",type="win32"
Action ended 15:20:42: InstallExecute. Return value 3.
Info 1935. An error occurred during the installation of assembly component {22D75DAD-658C-3109-91F7-4CB1A0729109}. HRESULT: 0x80070422. assembly interface: IAssemblyCache, function: UninstallAssembly, assembly name: Microsoft.VC90.CRT,version="9.0.30729.6161",publicKeyToken="1fc8b3b9a1e18e3b",processorArchitecture="amd64",type="win32"
Action ended 15:20:43: INSTALL. Return value 3.
```

**Comment by OfficialEsco** [comment]
Looks more like error 1935?
https://support.microsoft.com/en-us/topic/fix-an-installation-may-fail-with-error-1935-when-an-msi-file-tries-to-install-many-policy-files-on-a-computer-that-has-the-net-framework-2-0-installed-a0b0439b-0d6e-f149-f550-e869442fcd9d

**Comment by Trenly** [comment]
> Looks more like error 1935? https://support.microsoft.com/en-us/topic/fix-an-installation-may-fail-with-error-1935-when-an-msi-file-tries-to-install-many-policy-files-on-a-computer-that-has-the-net-framework-2-0-installed-a0b0439b-0d6e-f149-f550-e869442fcd9d

Possibly; I just took the first error I saw; At the end of the install it returns a 1603

**Review by ImJoakim — APPROVED** [review]
Works on a VM 👍

image

**Review by ImJoakim — APPROVED** [review]

**Pull request merged**
