### PR TITLE
New Package: DooTask-0.27.1

### PR DESCRIPTION
**Pull request by CoolPlayLin**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/109501&drop=dogfoodAlpha

### CODE REVIEW

**Comment by CoolPlayLin** [comment]
@stephengillie

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
I'm seeing this:
image

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
See https://github.com/microsoft/winget-pkgs/pull/109501#pullrequestreview-1473869440

**Comment by CoolPlayLin** [comment]
@ItzLevvie I have worked out that

**Comment by CoolPlayLin** [comment]
@stephengillie

**Comment by CoolPlayLin** [comment]
@russellbanks Could you please review this for me?

**Comment by CoolPlayLin** [comment]
@russellbanks

**Review by mdanish-kh — APPROVED** [review]
The best practice is to write tags in all lowercase, but since that's an optional field I'll fix it in a separate PR

**Review by mdanish-kh — APPROVED** [review]

**Pull request merged**
