### PR TITLE
Add DevOps pipelines files

### PR DESCRIPTION
**Pull request by msftrubengu**
Setting up Azure DevOps pipelines for project.

### CODE REVIEW

**Review by JohnMcPMS — APPROVED** [review]

**Review by ashpatil-msft — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 10:44:57 AM: 
> 2023-12-12 10:44:56.432 [CLI ] Package hash verification failed. SHA256 in manifest [75e241998f965031f359c2920bef6257dabf22fd501a8d69c5c20631f7fc843a] does not match download [d6c260def3cb6e9684ae8702f73edb91b19c8aa72efa3acdc2e642b4b3162d2c]

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> Faulting application name: CCleaner64.exe, version: 6.19.0.10858, time stamp: 0x656f370a 
> Faulting module name: CCleaner64.exe, version: 6.19.0.10858, time stamp: 0x656f370a Exception code: 0xc0000005 Fault offset: 0x000000000035bda4 
> Faulting process id: 0x26a4 
> Faulting application start time: 0x01da2ed68849a3f2 
> Faulting application path: C:\Program Files\CCleaner\CCleaner64.exe 
> Faulting module path: C:\Program Files\CCleaner\CCleaner64.exe Report Id: 4ec01e5f-7567-46aa-9410-06db1b9892e9 
> Faulting package full name:  
> Faulting package-relative application ID: 

(Automated response - build 485.) Manual Validation ended with:
> 
> Faulting application name: CCleaner64.exe, version: 6.19.0.10858, time stamp: 0x656f370a 
> Faulting module name: CCleaner64.exe, version: 6.19.0.10858, time stamp: 0x656f370a Exception code: 0xc0000005 Fault offset: 0x000000000035bda4 
> Faulting process id: 0x26a4 
> Faulting application start time: 0x01da2ed68849a3f2 
> Faulting application path: C:\Program Files\CCleaner\CCleaner64.exe 
> Faulting module path: C:\Program Files\CCleaner\CCleaner64.exe Report Id: 4ec01e5f-7567-46aa-9410-06db1b9892e9 
> Faulting package full name:  
> Faulting package-relative application ID:

**Review by stephengillie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 2:27:39 PM: 
> 2023-12-21 14:27:37.963 [CLI ] Package hash verification failed. SHA256 in manifest [d6c260def3cb6e9684ae8702f73edb91b19c8aa72efa3acdc2e642b4b3162d2c] does not match download [2a86aedfd5d06f761472e6f3590e840ad44ac1a5944a553af737fe7e0bd365d5]

(Automated response - build 487.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 10:22:38 AM: This command cannot be run due to the error: The specified executable is not a valid application for this OS platform.

(Automated response - build 489.)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-11-12 10:31:08.652 [CLI ] Package hash verification failed. SHA256 in manifest [9d83f48b8fb87524be39ff97acc29f600cab40097f797689b2f3e474110f59d7] does not match download [da192329ba20aae68e205df0a7c7464aa39a97f282757f4e015b6a575543f8b7] with file size [571223832] and content type []

(Automated response - build 897.)

**Review by stephengillie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
Close with reason: Stale pull request;

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Manual Validation ended with: 
> 2026-01-16 09:24:20.719 [CORE] DeliveryOptimization error: 0x80d0201a, extended error: 0x00000000
> 2026-01-16 09:24:20.730 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(361)\WindowsPackageManager.dll!00007FF8427E2CB5: (caller: 00007FF8427E1880) Exception(1) tid(710) 80D0201A 
> 2026-01-16 09:24:21.235 [CLI ] Package hash verification failed. SHA256 in manifest [f32013178d6d9c4828a89b6c285c3ae4cf871bce17438658e0a8d6296a2beaa1] does not match download [3d17afdf2b88d4dbac239d4361672feec407f6036a36b2f2b254291a00dea883] with file size [3493] and content type [text/html] 
 
 | Hex | Dec | Inverted Dec | Symbol | Description | 
 | --- | --- | --- | --- | --- | 
  | 00000000 | 0 | -4294967296 | ERROR_SUCCESS | The operation completed successfully. | 


(Automated response - build 1197.)

**Review by stephengillie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
