### PR TITLE
Update Acrobat Reader to 21.005.20058

### PR DESCRIPTION
**Pull request by alie2n**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/20876)

### CODE REVIEW

**Comment by alie2n** [comment]
This is my first pull request for winget. Are there any details what the pipeline "Installer validation" does? Running for 3h straight seems odd....

**Comment by palenshus** [comment]
> This is my first pull request for winget. Are there any details what the pipeline "Installer validation" does? Running for 3h straight seems odd....

This is a validation service to download and run the installer and among other things check for malware. It still has some reliability issues though, which is why we occasionally see this state. Triggering a rerun usually resolves it

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
