### PR TITLE
Created New Visual Studio 2022 Enterprise Preview Sku.

### PR DESCRIPTION
**Pull request by edwardskrod**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?
----

## What
- Create new Visual Studio 2022 Enterprise manifests in the 2022\Enterprise\Preview folder.
- Rename the PackageIdentifier
- Keep the current Preview manifest to minimize disruptions to the current experience.

## Why
As part of Microsoft's work to take ownership of the Visual Studio WinGet repo, we are deleting, moving, and adding manifests in support of various Channel/SKU combinations.

Rather than have it's own top level folder under '2022', we would like to maintain one set of 'Preview' manifests under the 'Enterprise ' sku folder.  This will provide support for the latest 2022 Enterprise Preview VS.

Furthermore, we are renaming the Preview PackageIdentifier to remove the '-', in keeping with current naming conventions.

Related to https://github.com/microsoft/winget-pkgs/issues/94161

### CODE REVIEW

**Comment by edwardskrod** [comment]
@denelon  Is there anything that can be done about this PR error?  Or should I create two PRs for this move?

**Comment by denelon** [comment]
It needs to be two PRs.

**Comment by edwardskrod** [comment]
> It needs to be two PRs.

I'm going to keep the old Preview manifest in the short term, if that's possible, to minimize disruptions.

The new preview manifests have been placed into a new location and also have had their packageId renamed in keeping with current conventions.

**Comment by edwardskrod** [comment]
@denelon How do I kick off the validation again?  It looks like there were errors provisioning the Azure resources:

##[error]An error occurred while provisioning resources (Error Type: Failure).
,##[error]The remote provider was unable to process the request.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
