### PR TITLE
ProductCode: Adobe.Brackets version 1.1

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23769)

### CODE REVIEW

**Review by OfficialEsco — DISMISSED** [review]

**Comment by OfficialEsco** [comment]
image

**Comment by vedantmgoyal2009** [comment]
In the MSI database, it showed me 1.1.0.0. Let me check again.

**Comment by OfficialEsco** [comment]
> In the MSI database, it showed me 1.1.0.0. Let me check again.

Thats the Installer, the Installer and Package can have a different version, this is why the ProductCode can sometimes be wrong or the Package don't actually have a ProductCode, for example Mozilla Firefox

**Comment by vedantmgoyal2009** [comment]
Oh! That's why Linux's apt-get is so simple because it does not have all these things 🤯. Windows has too many complications in installers and software. I am reverting the commits.

**Comment by OfficialEsco** [comment]
Also fix the Publisher and PackageName where is wrong

**Comment by vedantmgoyal2009** [comment]
Well, it's time to sleep so, I will deal with all the PRs tomorrow.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
