### PR TITLE
Fix DisplayVersion of CUDA Toolkit

### PR DESCRIPTION
**Pull request by CanePlayz**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135223)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-22T22:27:30.1163074Z ##[error] Manifest Error: DisplayVersion declared in the manifest has overlap with existing DisplayVersion range in the index. Existing DisplayVersion range in index:  [ [12.3, 12.3]]

(Automated response - build 628.)

**Comment by CanePlayz** [comment]
Well, the issue is that all of these newer versions of CUDE have the same version number displayed.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-22T22:27:30.1163074Z ##[error] Manifest Error: DisplayVersion declared in the manifest has overlap with existing DisplayVersion range in the index. Existing DisplayVersion range in index:  [ [12.3, 12.3]]

(Automated response - build 675.)

**Comment by stephengillie** [comment]
Hi @mdanish-kh and @Trenly,

Can you help us to understand the `DisplayVersion` error holding this PR?

**Comment by Trenly** [comment]
> Hi @mdanish-kh and @Trenly,
> 
> Can you help us to understand the `DisplayVersion` error holding this PR?

Theres a previous manifest that specifies the same DisplayVersion as this manifest. DisplayVersion must be unique per manifest

**Comment by mdanish-kh** [comment]
> Can you help us to understand the `DisplayVersion` error holding this PR?

As mentioned above, DisplayVersion must be unique per package; This means, if multiple versions are sharing the same DisplayVersion, we may only keep the 'latest' one in the repo, and remove all previous ones.

cc @CanePlayz To unblock this PR, you'll have to remove `12.3.1` and `12.3` versions first from the repo

**Comment by CanePlayz** [comment]
> > Can you help us to understand the `DisplayVersion` error holding this PR?
> 
> As mentioned above, DisplayVersion must be unique per package; This means, if multiple versions are sharing the same DisplayVersion, we may only keep the 'latest' one in the repo, and remove all previous ones.
> 
> cc @CanePlayz To unblock this PR, you'll have to remove `12.3.1` and `12.3` versions first from the repo

In "only leave the lastest manifest in the repo" or "only keep the DisplayVersion in the lastest manifest"?

**Comment by Trenly** [comment]
> > > Can you help us to understand the `DisplayVersion` error holding this PR?
> > 
> > 
> > As mentioned above, DisplayVersion must be unique per package; This means, if multiple versions are sharing the same DisplayVersion, we may only keep the 'latest' one in the repo, and remove all previous ones.
> > cc @CanePlayz To unblock this PR, you'll have to remove `12.3.1` and `12.3` versions first from the repo
> 
> In "only leave the lastest manifest in the repo" or "only keep the DisplayVersion in the lastest manifest"?

Only leave the latest manifest

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-22T22:27:30.1163074Z ##[error] Manifest Error: DisplayVersion declared in the manifest has overlap with existing DisplayVersion range in the index. Existing DisplayVersion range in index:  [ [12.3, 12.3]]

(Automated response - build 679.)

**Comment by CanePlayz** [comment]
Ok thanks, I will open PRs to remove the other manifests then

**Comment by CanePlayz** [comment]
Done.

**Comment by stephengillie** [comment]
> Needs a waiver I think

Yes - was waiting for the discussion to be complete.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
