### PR TITLE
Modify: Google.Chrome version 122.0.6261.70

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings).
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141094)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by khaffner** [comment]
Any reason the msi installertypes got removed?

**Comment by SpecterShell** [comment]
> Any reason the msi installertypes got removed?

There are only dynamics links available for the MSI installers and they get updated frequently, which means the manifests will become outdated when a new version is released and thus we have to update them in time and wait for them being merged, which usually takes 0~2 days. There is no such issue for the EXE installers which have static and versioned links and they could also work on the existing MSI installations properly according to my test. Is there any issue happening on your side?

**Comment by khaffner** [comment]
Just inconsistent ProviderName in the output of Get-Package when using the exe, based on whether it is a clean install or update of the existing msi-based installation. 
A: Clean install of exe --> Get-Package -Name "Google Chrome" returns the ProviderName "programs"
B: Have chrome installed by msi, update chrome with exe --> Get-Package -Name "Google Chrome" returns the ProviderName "msi"

A hickup in our winget-integration, which worked fine when the manifested contained the msi installertypes. We can make it work, as long as the manifest contain these exe's now and in the future.

**Comment by SpecterShell** [comment]
> Just inconsistent ProviderName in the output of Get-Package when using the exe, based on whether it is a clean install or update of the existing msi-based installation. A: Clean install of exe --> Get-Package -Name "Google Chrome" returns the ProviderName "programs" B: Have chrome installed by msi, update chrome with exe --> Get-Package -Name "Google Chrome" returns the ProviderName "msi"
> 
> A hickup in our winget-integration, which worked fine when the manifested contained the msi installertypes. We can make it work, as long as the manifest contain these exe's now and in the future.

This is intended. The EXE installer will update the MSI-based installation if existed, or create/update the EXE-based installation if not. Without this feature there will be two standalone installations which may cause some conflicts and issues in WinGet.

**Comment by SkylerWallace** [comment]
This commit caused me agony for weeks, I'm glad this has been moved to a separate exe version.
This URL installed only for the current user...I'll take an occasional hash-validation error over this install method.

**Comment by SpecterShell** [comment]
> This commit caused me agony for weeks, I'm glad this has been moved to a separate exe version. This URL installed only for the current user...I'll take an occasional hash-validation error over this install method.

It can be installed in machine scope though (by specifying `--scope machine`)... but anyway it has been moved to a separate package due to #147702.

**Pull request merged**
