### PR TITLE
Update Discord.Discord.installer.yaml URL

### PR DESCRIPTION
**Pull request by rakleed**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/130478)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
The URL you provided is simply a redirect to the URL which already exists in the manifest.
The existing URL should be kept to minimize redirects
```
PS D:\Git\winget-pkgs> Get-UrlResponse 'https://discord.com/api/downloads/distributions/app/installers/latest?channel=stable&platform=win&arch=x86'

Name                           Value
----                           -----
ResponseCode                   200
ResponseUrl                    https://dl.discordapp.net/distro/app/stable/win/x86/1.0.9027/DiscordSetup.exe
Headers                        {x-goog-stored-content-length, x-goog-storage-class, Server, Last-Modified...}
Response                       https://dl.discordapp.net/distro/app/stable/win/x86/1.0.9027/DiscordSetup.exe
Url                            https://discord.com/api/downloads/distributions/app/installers/latest?channel=stable&platform=win&arch=x86
ContentLength                  96194848
```

**Comment by rakleed** [comment]
But the installer hash should be the same.

**Comment by stephengillie** [comment]
These files do indeed have different hashes. The new one is first:

```PowerShell
PS C:\ManVal> get-fileHash .\Installers\DiscordSetup.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          7335719742E7BF490E90429D7FDFF85D6EBB923CDB3F4262D218559F670C554E       C:\ManVal\Installers\DiscordSetup…

PS C:\ManVal> get-fileHash '.\Installers\DiscordSetup (1).exe'

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          CA5CF79D0B02543FF39FF904243D566B091CE94126DFA55221A40E74E8E4B4DB       C:\ManVal\Installers\DiscordSetup…
```

**Review by stephengillie — APPROVED** [review]

**Comment by rakleed** [comment]
> [Publish pipeline succeeded for this Pull Request. ](https://dev.azure.com/ms/ed6a5dfa-6e7f-413b-842c-8305dd9e89e6/_build/results?buildId=526515)Once you refresh your index, this change should be present.

@stephengillie can you please correct it so that in the message as above from @wingetbot between “Request.” and "Once" the space was not highlighted as a link?

**Comment by stephengillie** [comment]
@rakleed I don't have direct access to the code, but I'll pass your request up to the team that does.

**Pull request merged**
