### PR TITLE
Kiwix.WikiMed.Electron version 1.9.5-E

### PR DESCRIPTION
**Pull request by Jaifroid**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/56045)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Jaifroid** [comment]
@ItzLevvie This PR seems to have been stuck in validation for over 20 hours... Never seems to complete the Installer Validation...

**Comment by Jaifroid** [comment]
@ItzLevvie The validator has now been stuck for 2 days... I've tested install again using the manifest, and everything is fine:

image

**Comment by ItzLevvie** [comment]
You can close and re-open the PR to re-run the pipelines.

**Comment by Jaifroid** [comment]
OK, I'll try, though the bot seems to re-run them anyway when they get stuck. Let's see.

**Pull request merged**
