### PR TITLE
New version: Hugo.Hugo.Extended version 0.140.0

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#10340](https://github.com/SpecterShell/Dumplings/actions/runs/12375624720).

<details>

<summary>Log</summary>

````
Updated: 0.139.4 → 0.140.0
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/199419)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-12-17 11:38:16.130 [FAIL] Installer failed security check. Url: https://github.com/gohugoio/hugo/releases/download/v0.140.0/hugo_extended_0.140.0_windows-amd64.zip Result: 0x80004005

(Automated response - build 904.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-12-17 12:34:13.185 [FAIL] Installer failed security check. Url: https://github.com/gohugoio/hugo/releases/download/v0.140.0/hugo_extended_0.140.0_windows-amd64.zip Result: 0x80004005

(Automated response - build 904.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-12-17 12:48:45.205 [FAIL] Installer failed security check. Url: https://github.com/gohugoio/hugo/releases/download/v0.140.0/hugo_extended_0.140.0_windows-amd64.zip Result: 0x80004005

(Automated response - build 904.)

**Comment by SpecterShell** [comment]
@stephengillie Any updates on this PR?

**Pull request merged**
