### PR TITLE
Update: Ferdium - remove old nightly versions

### PR DESCRIPTION
**Pull request by Alphrag**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?

-----
Remove the old versions of the Ferdium Nightly to unclutter the folder.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/83292)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by russellbanks** [comment]
For the time being, I would just use YamlCreate and submit a PR for each verison that you want to be deleted. I'm happy to do this for you if you'd like.

**Comment by russellbanks** [comment]
@Alphrag, do you only want a certain amount of nightly versions to be in the repo?

**Comment by Alphrag** [comment]
> @Alphrag, do you only want a certain amount of nightly versions to be in the repo?

My idea would be to keep all the nightly releases of a version until a stable one is pushed out, just in case we want to be able to test where something had broken in the line. So keeping all of the `6.2.1-nightly.xx` until `Ferdium.Ferdium` contains `6.2.1` at which point we will start the nightlies of a new version (likely `6.2.2` or `6.3.0`) at which point we could remove all of the `6.1.1-nightly.xx` ones, if that makes sense.

**Comment by russellbanks** [comment]
@Alphrag, would you like me to remove the nightly versions < 6.2.5-nightly.x as above

**Comment by Alphrag** [comment]
> @Alphrag, would you like me to remove the nightly versions < 6.2.5-nightly.x as above

If you have the time to deal with this, that would be really great indeed 🙇‍♂️ 
I am pretty busy at the moment, so I won't have the time to do that for the next two months as I don't yet have an automatic way of submitting them.

**Comment by russellbanks** [comment]
> If you have the time to deal with this, that would be really great indeed 🙇‍♂️

Honestly it's no bother at all - I just run the same command with a different version number each time

**Pull request closed without merging**
