### PR TITLE
Add Cinebench2024

### PR DESCRIPTION
**Pull request by CanePlayz**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/121672)

### CODE REVIEW

**Comment by CanePlayz** [comment]
Where should I get a different link from?

**Comment by stephengillie** [comment]
On my laptop it redirects to https://www.maxon.net/en/cinebench. I think the validation VM just calls the URL instead of loading it as a webpage, and since the HTTP wasn't rendered, the HTTP Redirect didn't occur.

**Comment by CanePlayz** [comment]
> On my laptop it redirects to https://www.maxon.net/en/cinebench. I think the validation VM just calls the URL instead of loading it as a webpage, and since the HTTP wasn't rendered, the HTTP Redirect didn't occur.

So what do we do about this? The link it redirects to on your machine doesn't initiate a download...

**Comment by stephengillie** [comment]
> > On my laptop it redirects to https://www.maxon.net/en/cinebench. I think the validation VM just calls the URL instead of loading it as a webpage, and since the HTTP wasn't rendered, the HTTP Redirect didn't occur.
> 
> So what do we do about this? The link it redirects to on your machine doesn't initiate a download...

Is the package available from another URL?

**Comment by CanePlayz** [comment]
Unfortunately, I couldn't find one :/ Should I try contacting Maxon?

**Comment by CanePlayz** [comment]
Yeah fair, did not expect that to work.

**Comment by cbr-github** [comment]
The URL for R23 was: https://installer.maxon.net/cinebench/CinebenchR23.zip

I tried modifying it, to check if they uploaded 2024 here as well. Unfortunately no luck on my side :(.

I guess without feedback from Maxon you'll not be able to add this package :(.

**Comment by CanePlayz** [comment]
> The URL for R23 was: https://installer.maxon.net/cinebench/CinebenchR23.zip
> 
> I tried modifying it, to check if they uploaded 2024 here as well. Unfortunately no luck on my side :(.
> 
> I guess without feedback from Maxon you'll not be able to add this package :(.

Yup, had tried that too. I'll reach out to support and try my luck.

**Comment by CanePlayz** [comment]
To get proper help from their support, I'd need to know what's the exact difference of the old link and the new one on a technical level.

**Comment by CanePlayz** [comment]
> To get proper help from their support, I'd need to know what's the exact difference of the old link and the new one on a technical level.

@stephengillie Do you happen to know that?

**Comment by stephengillie** [comment]
Hi @CanePlayz,

Current URL: https://mx-app-blob-prod.maxon.net/mx-package-production/website/windows/maxon/cinebench/Cinebench2024_win_x86_64.zip
New URL: https://installer.maxon.net/cinebench/Cinebench2024_win_x86_64.zip
- As both of these URLs are controlled by Maxon, I'm not aware of any technical differences (CDNs, DNS redirects, etc) between them. 

What are their Support team looking for?

**Comment by CanePlayz** [comment]
> Hi @CanePlayz,
> 
> Current URL: https://mx-app-blob-prod.maxon.net/mx-package-production/website/windows/maxon/cinebench/Cinebench2024_win_x86_64.zip New URL: https://installer.maxon.net/cinebench/Cinebench2024_win_x86_64.zip
> 
> * As both of these URLs are controlled by Maxon, I'm not aware of any technical differences (CDNs, DNS redirects, etc) between them.
> 
> What are their Support team looking for?

This was everything I received:

```
Thank you for reaching out to us.
 
The direct download for Cinebench 2024 (similar to the previous version) can be downloaded directly from our website here:
https://www.maxon.net/en/downloads/cinebench-2024-downloads
```

So I was kind of hoping that I could point them into the right direction by telling them why the current download link does not work for winget.

**Comment by stephengillie** [comment]
Ah - the issue is that their link has a user-specific part at the end. Example:

> https://mx-app-blob-prod.maxon.net/mx-package-production/website/windows/maxon/cinebench/Cinebench2024_win_x86_64.zip?_gl=1*1qv1rnk*_gcl_au*MTQ4MDU2NjIzLjE2OTY1MzA5MDQ.

This first part is normal: `https://mx-app-blob-prod.maxon.net/mx-package-production/website/windows/maxon/cinebench/Cinebench2024_win_x86_64.zip`

The query string (everything after the question mark) is user or time specific and causes the issue: `?_gl=1*1qv1rnk*_gcl_au*MTQ4MDU2NjIzLjE2OTY1MzA5MDQ.`

**Comment by CanePlayz** [comment]
> This first part is normal: `https://mx-app-blob-prod.maxon.net/mx-package-production/website/windows/maxon/cinebench/Cinebench2024_win_x86_64.zip`
> 
> The query string (everything after the question mark) is user or time specific and causes the issue: `?_gl=1*1qv1rnk*_gcl_au*MTQ4MDU2NjIzLjE2OTY1MzA5MDQ.`

Ah, thanks

**Comment by CanePlayz** [comment]
`I've requested some information about this and got the answer, that Cinebench shall not be offered via a package manager, as this would be a violation of our license agreement. For this reason the current versions download has been changed to be usable on personal downloads only.`

Well...

**Pull request closed without merging**
