### PR TITLE
New version: squidowl.halloy version 0.0.2024.8

### LINKED ISSUE #165036: [Update Request]: Halloy (squidowl.halloy)
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

squidowl.halloy

### Package Version

0.0.2024.7

### Please describe the changes you would like to see

New release 2024.8: https://github.com/squidowl/halloy/releases/tag/2024.8

### PR DESCRIPTION
**Pull request by fancybody**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.3.0 :rocket:

- Resolves #165036

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/165050)

### CODE REVIEW

**Review by ClintonOffor — CHANGES_REQUESTED** [review]
Ok

**Comment by KaiKorla** [comment]
I would like to suggest to use the the files from the previous version (https://github.com/microsoft/winget-pkgs/tree/master/manifests/s/squidowl/halloy/0.0.2024.7) as base for 0.0.2024.8 instead of generating new one with komac.

FYI: With the upcoming release of Halloy 2024.9 we will have updated binary metadata and a new WIX5 bases installer. Halloy Version in winget will then reflect the correct Halloy version.

regards
Kai

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
