### PR TITLE
add teamviewer 15.10.5

### PR DESCRIPTION
**Pull request by nicexe**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3870)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
image

**Comment by nicexe** [comment]
@KevinLaMS it works on my end:
image
I uninstalled teamviewer before doing what is shown in the screenshot

**Comment by OfficialEsco** [comment]
Kevin... Why do you always have issues with Teamviewer?..

**Comment by nicexe** [comment]
@KevinLaMS Depending on your UAC configuration, the installer would trigger a dialog box. Make sure to allow the process if you want the installation to start.

**Comment by nicexe** [comment]
@KevinLaMS It looks like the download failed for you, yet the installer was validated in the [Validation URLs in manifest files](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=113648&view=logs&j=c8020aa5-4aab-5881-691f-21986e02afd0&t=b1dedfee-c398-5ffb-7e02-e58e9d543989&l=37) pipeline.
Could you try once more?

**Comment by KevinLaMS** [comment]
Duplicate of #4150

**Comment by nicexe** [comment]
I would say #4150 is the duplicate in this case and the user ignored the "Have you checked that there aren't other open pull requests for the same manifest update/change?" requirement but you merged the duplicated PR anyway.

This could encourage people to copy the changes of a pending PR since the latest PR has a bigger chance of getting merged.

**Pull request closed without merging**
