### PR TITLE
New version: Blueberry.FlashbackExpress version 6.0.6.251

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

* Resolves #46955
* Resolves #47225
* Resolves #47421
* Resolves #47673

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/47083)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Comment by OfficialEsco** [comment]
Url from https://www.flashbackrecorder.com/express/ -> Get for free -> https://www.flashbackrecorder.com/download-start-2/?edition=FlashBack:Ex6&linksrc=expresspage#

**Review by ItzLevvie — DISMISSED** [review]

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-pkgs/pull/47083#issuecomment-1046059477

**Comment by lechacon** [comment]
@OfficialEsco Do you have any idea of why the installed exe is failing?

On the pipelines it seems to be failing with -532462766 (EXCEPTION_COMPLUS).

On my machine it also failed, but with code -1073741515 (STATUS_DLL_NOT_FOUND). The missing dll seemed to have been `C:\Program Files\Blueberry Software\Flashback Express 6\EN\FBRecorderUI.resources.dll`. If I copy the resources for another language, it goes past that but I still get the same error for but for `FBStyleNew.resources.dll`

**Comment by OfficialEsco** [comment]
Think i found a VC++ dependency, one moment

**Comment by OfficialEsco** [comment]
VirtualBoxVM_eJjgCOzx1B

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
