### PR TITLE
Remove version: Codemao.kitten version 3.8.2

### PR DESCRIPTION
**Pull request by CoolPlayLin**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/147676)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://kn-cdn.codemao.cn/zh/kitten-editor/win_kitten_installer_3.8.2.exe 
Status code: 200

(Automated message - build 608)

**Comment by stephengillie** [comment]
Hi @CoolPlayLin,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 876.)

**Comment by stephengillie** [comment]
URL: https://kn-cdn.codemao.cn/zh/kitten-editor/win_kitten_installer_3.8.2.exe 
Status Code: 200

(Automated message - build 876)

**Comment by stephengillie** [comment]
URL: https://kn-cdn.codemao.cn/zh/kitten-editor/win_kitten_installer_3.8.2.exe 
Status Code: 200

(Automated message - build 876)

**Comment by CoolPlayLin** [comment]
Moved

**Comment by stephengillie** [comment]
URL: https://kn-cdn.codemao.cn/zh/kitten-editor/win_kitten_installer_3.8.2.exe 
Status code: 200

(Automated message - build 634)

**Comment by stephengillie** [comment]
URL: https://kn-cdn.codemao.cn/zh/kitten-editor/win_kitten_installer_3.8.2.exe 
Status Code: 200

(Automated message - build 876)

**Comment by stephengillie** [comment]
URL: https://kn-cdn.codemao.cn/zh/kitten-editor/win_kitten_installer_3.8.2.exe 
Status Code: 200

(Automated message - build 876)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
