### PR TITLE
New version: VeyonSolutions.Veyon version 4.7.0.0

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

* Resolves #36841

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/36894)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Please close and re-open the PR to re-run the pipelines.

**Comment by vedantmgoyal2009** [comment]
I have fix the issues in my PR.

**Comment by OfficialEsco** [comment]
u sure the pipeline crashed? 🤔 its just been running for 15min
Also @vedantmgoyal2009 do you always fix your day old PRs once i decide to clean up after you?

**Comment by ItzLevvie** [comment]
> u sure the pipeline crashed? 🤔 its just been running for 15min

It shows that it was cancelled: https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=248288&view=results

**Comment by OfficialEsco** [comment]
Ahaaa so that i what those icons mean
image
Since #36841 is fixed we'll let that one pass then

**Pull request closed without merging**
