### PR TITLE
Update Wondershare.PDFelement to 8.3.6

### PR DESCRIPTION
**Pull request by ghost**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/39239)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie2** [comment]
Hmm.

**Comment by ItzLevvie2** [comment]
lol

image

**Comment by Trenly** [comment]
@ItzLevvie2 I think that as a mod if you comment `Duplicate of <#XXXXX` on the issues, it would close them. I could write a quick powershell statement to do that if you wanted

**Comment by ItzLevvie** [comment]
> @ItzLevvie2 I think that as a mod if you comment `Duplicate of <#XXXXX` on the issues, it would close them. I could write a quick powershell statement to do that if you wanted

I tried it before (https://github.com/microsoft/winget-pkgs/issues/38714#issuecomment-999960446) but I don't think @denelon has added me for it to work.

https://github.com/microsoft/winget-pkgs/issues/38926
https://github.com/microsoft/winget-pkgs/issues/38926

**Comment by Trenly** [comment]
> > @ItzLevvie2 I think that as a mod if you comment `Duplicate of <#XXXXX` on the issues, it would close them. I could write a quick powershell statement to do that if you wanted
> 
> I tried it before ([#38714 (comment)](https://github.com/microsoft/winget-pkgs/issues/38714#issuecomment-999960446)) but I don't think @denelon has added me to the rule for it to work.
> 
> #38926

I cri

**Comment by denelon** [comment]
We're working on the bots to give moderators the ability to close duplicates, I might take a look to see if I can do that this afternoon. It will get refactored, but it's a start.

**Comment by Trenly** [comment]
> We're working on the bots to give moderators the ability to close duplicates, I might take a look to see if I can do that this afternoon. It will get refactored, but it's a start.

It seems to work for Joakim and Esco, just not Levvie

**Comment by denelon** [comment]
I have "ItzLevvie" in the rule for the pkgs repository.

**Comment by Trenly** [comment]
> I have "ItzLevvie" in the rule for the pkgs repository.

Interesting. I don't know why it didn't work on https://github.com/microsoft/winget-pkgs/issues/38926 then

**Comment by denelon** [comment]
No clue on my end. No typo or anything. It's essentially just an "or" with username.

**Pull request closed without merging**
