### PR TITLE
Remove version: Insco.PicGuard version 1.0.3.414

### PR DESCRIPTION
**Pull request by kjxbyz**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/192183)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @kjxbyz,

Is this version older than should be supported?

**Comment by stephengillie** [comment]
URL: https://github.com/picguard/picguard/releases/download/v1.0.3+414/picguard_1.0.3+414_windows_x64_en-US.msi 
Status Code: 200

(Automated message - build 897)

**Comment by kjxbyz** [comment]
@stephengillie 1.0.3.x corresponds to multiple versions. I think you only need to keep the latest build version, such as 1.0.3.414, 1.0.3.415 and 1.0.3.417, of which 1.0.3.417 can be retained and the rest can be deleted.

**Comment by stephengillie** [comment]
URL: https://github.com/picguard/picguard/releases/download/v1.0.3+414/picguard_1.0.3+414_windows_x64_en-US.msi 
Status Code: 200

(Automated message - build 898)

**Comment by stephengillie** [comment]
URL: https://github.com/picguard/picguard/releases/download/v1.0.3+414/picguard_1.0.3+414_windows_x64_en-US.msi 
Status Code: 200

(Automated message - build 899)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
