### PR TITLE
Remove version: WHONET.2023 version 23.13.23

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137480)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://whonet.org/WHONET2023-Setup-x86.exe 
Status Code: 200

(Automated message - build 694)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-01T15:28:48.2733533Z Processing manifest: manifests\w\WHONET\2023\23.13.23
 2024-02-01T15:28:48.2742239Z -----------------------------------------------------
 2024-02-01T15:28:48.2749893Z Status: Started
 2024-02-01T15:28:48.2758576Z Manifest file is Deleted
 2024-02-01T15:28:48.7998038Z Status: Completed
 2024-02-01T15:28:48.8010266Z ##[error] Result: Failed
 2024-02-01T15:28:48.8039864Z ##[error] Sequence contains no elements
 2024-02-01T15:28:48.8669039Z ##[error]Manifest Validation Failed

(Automated response - build 694.)

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 694.)

**Comment by stephengillie** [comment]
URL: https://whonet.org/WHONET2023-Setup-x86.exe 
Status Code: 200

(Automated message - build 694)

**Comment by stephengillie** [comment]
Hi @drshtmstry,

This is the last remaining manifest version for this package. Is it available from another location?

(Automated response - build 694.)

**Comment by drshtmstry** [comment]
> Hi @drshtmstry,
> 
> This is the last remaining manifest version for this package. Is it available from another location?
> 
> (Automated response - build 694.)

That is because it is vanity url package. Submitted new version here https://github.com/microsoft/winget-pkgs/pull/137478.

Previously I used `wingetcreate` which automatically deleted old version in same PR.
But lately I have experienced those PRs are not being approved.
That is why I have switched to `komac` which only adds new version & manually deleted in separate PR.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
