### PR TITLE
New Version: sourcegit-scm.SourceGit version 8.37

### LINKED ISSUE #188406: [Update Request]: SourceGit 8.37
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

sourcegit-scm.SourceGit

### Package Version

8.37

### Please describe the changes you would like to see

There is a new version (8.37) available.
Download URLs are:

X64: https://github.com/sourcegit-scm/sourcegit/releases/download/v8.37/sourcegit_8.37.win-x64.zip
ARM64: https://github.com/sourcegit-scm/sourcegit/releases/download/v8.37/sourcegit_8.37.win-arm64.zip

### PR DESCRIPTION
**Pull request by love-linger**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?
      Resolve #188406

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/188407)

### CODE REVIEW

**Comment by love-linger** [comment]
image

I can install SourceGit 8.37 via command `winget install --manifest .\manifests\s\sourcegit-scm\SourceGit\8.37`

PS. I'm living in China, I need use proxy to download files on Github

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-11-03 18:38:19.161 [FAIL] Installer failed security check. Url: https://github.com/sourcegit-scm/sourcegit/releases/download/v8.37/sourcegit_8.37.win-x64.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-11-04 07:45:28.579 [FAIL] Installer failed security check. Url: https://github.com/sourcegit-scm/sourcegit/releases/download/v8.37/sourcegit_8.37.win-x64.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
