### PR TITLE
New package: LTY.xmltocsv version 1.0.0.0

### PR DESCRIPTION
**Pull request by ltycn**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/115315&drop=dogfoodAlpha

### CODE REVIEW

**Comment by ltycn** [comment]
@Trenly hi, I have no idea why this program always fail at installer validation ...can you give me any advice to this?

**Comment by Trenly** [comment]
Automatic validation ended with: 

> 2023-08-04 17:20:23.186 [FAIL] Installer failed security check. Url: https://github.com/ltycn/xmltocsv/releases/download/1.0.0/xmltocsv_v1.0.0.0.zip Result: 0x80004005

Sometimes waiting a day or two for the package to be scanned by more Antivirus providers resolves the issue

**Comment by ltycn** [comment]
@Trenly Thanks for reply. So I just need to wait a day or two and this pull request will automatically re-check? Do I need to take any action?

**Pull request closed without merging**
