### PR TITLE
NanoBoyAdvance.NanoBoyAdvance version 1.7.1

### PR DESCRIPTION
**Pull request by superusercode**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/107211)

### CODE REVIEW

**Comment by stephengillie** [comment]
This package installed normally, but errored when launched: 
> Faulting application name: NanoBoyAdvance.exe, version: 1.7.1.0, time stamp: 0x64629636 
> Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000 Exception code: 0xc0000005 
> Fault offset: 0x0000000000000000 
> Faulting process id: 0x0x1720 
> Faulting application start time: 0x0x1D989AFECE4518D 
> Faulting application path: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\NanoBoyAdvance.NanoBoyAdvance__DefaultSource\NanoBoyAdvance.exe 
> Faulting module path: unknown Report Id: 47cfdecc-e95a-4633-a102-3e29cc1aac06 
> Faulting package full name:  
> Faulting package-relative application ID:

**Comment by stephengillie** [comment]
> image installs and launches fine for me locally

You've got numerous `VCRedist` and `.NET` packages that the validation VMs may not. Since the VM is meant to emulate what a new PC might be like, if the user hasn't installed anything yet. For a more accurate troubleshooting perspective, please consider installing a fresh copy of Windows onto a Hyper-V instance, checkpointing it, and installing these there - then resetting to the checkpoint between each install. (And regular Windows Updates and Defender updates of course.) This is environment I'm using, automated with a few scripts.

**Comment by stephengillie** [comment]
Oh - sorry - yes, any virtualization solution should work the same here.

**Comment by ItzLevvie** [comment]
[Policy] Hardware

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Comment by denelon** [comment]
Supporting custom hardware in validation is "Not Planned".
* https://github.com/microsoft/winget-pkgs/issues/199504

**Pull request closed without merging**
