### PR TITLE
Add Premake5

### PR DESCRIPTION
**Pull request by 3x3y3z3t**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

The binary is a standalone .exe and not an installer. Support is being tracked via https://github.com/microsoft/winget-cli/issues/182

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14425)

### CODE REVIEW

**Comment by 3x3y3z3t** [comment]
This is a self-contained application, which is distributed via a zip (contains a single .exe). Installation for this kind of application is not currently supported, but issue is being tracked.

**Review by heroku-miraheze — CHANGES_REQUESTED** [review]
Did you forget this???

**Comment by 3x3y3z3t** [comment]
> Did you forget this???

Thanks for reminding. I'm still checking back every few days.
Which changes have you suggested? It showed that you suggested changes but the file looks the same to me...

**Comment by ItzLevvie** [comment]
> Did you forget this???

`.zip` files aren't yet supported by Windows Package Manager.

`Blocking-Issue` PRs are being periodically checked so we'll notify you when it's supported.

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
