### PR TITLE
New version: GIGABYTE.GigabyteControlCenter version 24.12.06.01

### PR DESCRIPTION
**Pull request by DuckDuckStudio**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/200457)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by rakleed** [comment]
@stephengillie why did you approve without `AppsAndFeaturesEntries` in installer?

**Comment by stephengillie** [comment]
Hi @rakleed,

I was asked to remove the `AppsAndFeaturesEntries` check in my approval script, because the entries are often not necessary, and the script was usually giving an incorrect error message. Is the entry necessary for this package?

**Comment by rakleed** [comment]
@stephengillie

> Is the entry necessary for this package?

Yes. See:

- https://github.com/microsoft/winget-pkgs/pull/148917/files
- https://github.com/microsoft/winget-pkgs/pull/148780/files
- https://github.com/microsoft/winget-pkgs/pull/152547/files
- https://github.com/microsoft/winget-pkgs/pull/166889/files

**Comment by DuckDuckStudio** [comment]
Komac doesn't seem to have added an `AppsAndFeaturesEntries` entry for this version of the manifest, I didn't realize it was required...
I will update this manifest.

**Pull request merged**
