### PR TITLE
Package Fix: makeblockteam.mBlock, fix hash

### LINKED ISSUE #153008: [Package Issue]: makeblockteam.mBlock
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The installation only gets a html file

### Steps to reproduce

winget install makeblockteam.mBlock

### Actual behavior

error

### Expected behavior

mblock to be installed

### Environment

```raw
Windows: Windows.Desktop v10.0.19045.4355
Architecture du système : X64
Package : Microsoft.DesktopAppInstaller v1.22.11261.0
```

### Screenshots and Logs

image

### PR DESCRIPTION
**Pull request by schembriaiden**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

Resolves: https://github.com/microsoft/winget-pkgs/issues/153008
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/153031)

### CODE REVIEW

**Comment by vikingnope** [comment]
I think the exe might be a dynamic hash, so I decided to change the installer to an msi

**Comment by vikingnope** [comment]
I have no idea what is wrong with this file:

image

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-05-10 06:16:57.628 [CORE] DeliveryOptimization error: 0x80072f76, extended error: 0x00000000
> 2024-05-10 06:16:57.683 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFACE52A465: (caller: 00007FFACE52AD01) Exception(1) tid(1e9c) 80072F76 

(Automated response - build 880.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-05-10 08:42:52.448 [CORE] DeliveryOptimization error: 0x80072f76, extended error: 0x00000000 
> 2024-05-10 08:42:52.449 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFE45B4F180: (caller: 00007FFE45B4FACC) Exception(1) tid(a60) 80072F76  
> 2024-05-10 08:42:54.355 [CLI ] Package hash verification failed. SHA256 in manifest [9d5bf8cddc60080fd570bb79bfc5867daf56a40f45ee9a2dace714ebc555c5c5] does not match download [a83bba255d2d6e424f058c38a204f273a4f40bcac38c8283f551a7056b605640]

(Automated response - build 880.)

**Comment by vikingnope** [comment]
I think the SHA256 is dynamic, it keeps changing

**Comment by stephengillie** [comment]
- If the SHA256 keeps changing to a new value, then it might be receiving continuous updates, possibly at the end of a CI/CD pipeline. 
- If the SHA256 keeps changing and reverting, then it might be getting an error page sometimes. 

Either way complicates installing through a package manager.

**Comment by vikingnope** [comment]
Don't know what can be done about this

**Pull request closed without merging**
