### PR TITLE
New package: Cilium.CiliumCLI version 0.15.7

### PR DESCRIPTION
**Pull request by nebula-it**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/119048)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @nebula-it,

`x64` Manual Validation (on a 64-bit Windows 10 VM) failed with:
> PS C:\Users\User\Desktop> C:\Users\User\AppData\Local\Microsoft\WinGet\Links\cilium.exe Program 'cilium.exe' failed to run: The specified executable is not a valid application for this OS platform.

Is this a known issue?

**Comment by nebula-it** [comment]
Hey @stephengillie, 
Just found the issue, it does install it but since it is a `.tar` file inside `.gz` it looks like its installed as `cilium-windows-amd64.tar.exe` which obviously fails. Is there a way for winget to auto extract the .tar file as well?
FYI, its same issue with https://github.com/microsoft/winget-pkgs/pull/119050

**Comment by stephengillie** [comment]
Oh, sorry - I failed to check the symlink's target. `.tar.gz` packages aren't currently supported. I believe there are plans to support this in the future, but I can't find a specific Issue for this.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
