### PR TITLE
Update Optimate Solidworks Plugin 0.10.11 -> 1.0.2

### PR DESCRIPTION
**Pull request by ReinhardtJ**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131524)

### CODE REVIEW

**Comment by ReinhardtJ** [comment]
@microsoft-github-policy-service agree company="Optimate GmbH"

**Comment by stephengillie** [comment]
>  Sequence contains no elements

**Comment by ReinhardtJ** [comment]
@stephengillie Hello, can you help me to understand why the pipeline for this PR failed? What can I do to fix this? I tested this manifest locally and both verifying and installing work:
```sh
PS C:\Users\Jonas\Repositories\winget-pkgs> winget validate .\manifests\o\Optimate\OptimateSOLIDWORKSPlugin\1.0.2\
Manifest validation succeeded.
PS C:\Users\Jonas\Repositories\winget-pkgs> winget install --manifest .\manifests\o\Optimate\OptimateSOLIDWORKSPlugin\1.0.2\
Found Optimate SOLIDWORKS Plugin [Optimate.OptimateSOLIDWORKSPlugin] Version 1.0.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://optimate-downloads.s3.eu-central-1.amazonaws.com/Optimate_SOLIDWORKS_Plugin_v1.0.2.msi
  ██████████████████████████████  4.31 MB / 4.31 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```
Thank you

**Comment by stephengillie** [comment]
Hi @ReinhardtJ,

Unfortunately, my knowledge around the cause and resolution of this error is slim.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
