### PR TITLE
ImagingEdgeWebcam version 1.1.00.10051

### PR DESCRIPTION
**Pull request by DanPrs**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/16015)

### CODE REVIEW

**Comment by DanPrs** [comment]
It works if you have the  `-h` parameter. Otherwise it'll ask for user input.

**Comment by KaranKad** [comment]
This application has a lot of options to choose from.
image

**Comment by DanPrs** [comment]
AS far as I can tell, any of those options downloads the same package. Even if you select multiple options, it's always the same package. That's probably just for data collection on Sony's end. 

The manifest does install if you have the `--silent` parameter and running as admin. Maybe we need to force the silent to permanent?! 
Screenshot 2021-06-03 154118

**Comment by KaranKad** [comment]
Yea, we could add `Custom: --silent` switch.

**Pull request closed without merging**
