### PR TITLE
New version: Kiwix.Wikivoyage.Electron version 2.9.6-E

### PR DESCRIPTION
**Pull request by Jaifroid**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135056)

### CODE REVIEW

**Comment by Jaifroid** [comment]
OK, so why has this PR stalled, and isn't running the usual checks? I amended the uploaded package to correct the previous failure, and this should have restarted the pipelines.

**Comment by Jaifroid** [comment]
Help! Can someone get this to run?

**Comment by Jaifroid** [comment]
I have closed the request and re-opened, but it still don't run.

**Comment by Jaifroid** [comment]
@stephengillie Can you kindly get the validation to run? I seem to be in limbo here.

**Comment by stephengillie** [comment]
We've had some unexpected work on our pipelines.

- https://github.com/microsoft/winget-pkgs/issues/135118

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
