### PR TITLE
New version: Nvidia.CUDA version 12.3.1

### PR DESCRIPTION
**Pull request by kimwonj77**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/130119)

### CODE REVIEW

**Comment by kimwonj77** [comment]
Note: Need waiver - See https://github.com/microsoft/winget-pkgs/pull/98333#issuecomment-1457455620

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335226 
> 2023-12-11 18:07:32.559 [CLI ] ShellExecute installer failed: 3772776548

**Comment by stephengillie** [comment]
Hi @kimwonj77

> Current manifest version 12.3 has 2 parameters, which is less than this PR's version number 12.3.1's 3 parameters.

Is this intentional?

**Comment by kimwonj77** [comment]
What means parameter? if you means versions' minor and patch things, Yes. it is intentional. Here's why:
1. NVIDIA releasing new version like as `11.7`(or `11.7 GA`) and `11.7 Update 1`. 
   - See their release node too: https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#id5
2. The previous PRs are following this stand. See also
   - [11.5](https://github.com/microsoft/winget-pkgs/pull/31013) and [11.5 Update 1](https://github.com/microsoft/winget-pkgs/pull/37911) (by OfficialEsco)
   - [11.7](https://github.com/microsoft/winget-pkgs/pull/63320) and [11.7 Update 1](https://github.com/microsoft/winget-pkgs/pull/68981) (by okazunori2013)
 
As of note, [Version archive](https://developer.nvidia.com/cuda-toolkit-archive) is following semver. But if you clicked, it says [`12.2`](https://developer.nvidia.com/cuda-12-2-0-download-archive), [`12.2 Update 1`](https://developer.nvidia.com/cuda-12-2-1-download-archive) and [`12.2 Update 2`](https://developer.nvidia.com/cuda-12-2-2-download-archive)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
