### PR TITLE
New package: UsaneersGmbH.remAid version 1.1.4.0

### PR DESCRIPTION
**Pull request by felixusaneers**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114363&drop=dogfoodAlpha

### CODE REVIEW

**Comment by felixusaneers** [comment]
@microsoft-github-policy-service agree company="Usaneers"

**Review by felixusaneers — COMMENTED** [review]
changes reviewed

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/issues/107639

**Comment by stephengillie** [comment]
Hi @felixusaneers,

Unfortunately, we don't currently have an `arm` pipeline to validate this package.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
```
This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)
```

**Pull request closed without merging**
