### PR TITLE
x64previewdriver 1.0.0

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/6277)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
probably better to use static URL rather than the aka.

https://download.microsoft.com/download/4/f/0/4f08ba34-7963-4c44-97a3-ea0ea3f3e692/Adreno_680_685_690_x64_emulation_driver.msi

**Comment by KevinLaMS** [comment]
Also, the architecture specified in the manifest says ARM.  but this is an emulator that I believe is X64.  if you specify arm, this will only be installed on ARM devices and not Windows x86 / x64.  I think that is incorrect.

**Comment by oxygen-dioxide** [comment]
This emulator is provided for arm PCs, such as surface pro x and huawei matebook e, enabling them to run x64 apps.

**Comment by KevinLaMS** [comment]
image

This is why the architecture needs to change for the Installer.  This is not intended to install on ARM.  It is intended to install on x64 / x86 and enable the ARM image.

**Comment by KevinLaMS** [comment]
Strange, now the installer is failing with a 1603 error for me on both admin and non admin prompts.

**Pull request closed without merging**
