### PR TITLE
Add Machine Scope for Eloston.Ungoogled-Chromium

### LINKED ISSUE #69381: [New Feature]: Add per-machine installer for Eloston Ungoogled-Chromium (Regression)
### Description of the new feature/enhancement

Please reopen #39848.  
This was fixed for eloston ungoogled-chromium 96.0.4664.110, but has regressed in the current version.

Fixed version:
https://github.com/microsoft/winget-pkgs/blob/master/manifests/e/eloston/ungoogled-chromium/96.0.4664.110/eloston.ungoogled-chromium.installer.yaml

It looks like this change didn't make it into the next version.  Is there a template somewhere that needs to be updated?

### Proposed technical implementation details (optional)

_No response_

### PR DESCRIPTION
**Pull request by Trenly**
* Resolves #69381

 @Nifury - I checked the version before this and it did contain scopes for user and machine. If possible, when updating this package in the future, be sure to keep both the user scope and machine scope as it causes issues for people upgrading if both are not present in new versions. (Ref #68863)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/69382)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Nifury** [comment]
Oh sorry I didn't know the machine scope was actually requested by a user. I removed it only because winget-create doesn't support multiple scopes for the same installer. I'll try other ways to update this package automatically.

**Comment by Trenly** [comment]
@denelon - Do you know if there are any open issues over at create regarding same scope for multiple installers?

**Comment by Nifury** [comment]
Ah this issue occurs when I update the manifest. https://github.com/microsoft/winget-create/issues/291#issuecomment-1198459372

**Comment by Trenly** [comment]
Ohhh, I see. Makes sense! Thanks for your help looking into it!!

**Comment by denelon** [comment]
@ryfu-msft can you check wingetcreate for this scenario?

**Pull request merged**
