### PR TITLE
Facebook.Oculus version 1.61.0.0

### PR DESCRIPTION
**Pull request by 2tbc1887**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15717)

### CODE REVIEW

**Comment by 2tbc1887** [comment]
**Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended.**
This installer cannot run unattended, I only noticed this requirement after submitting. Should the merge be cancelled? (It's a simple ok to start the installer, though)

**Comment by OfficialEsco** [comment]
> **Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended.**
> This installer cannot run unattended, I only noticed this requirement after submitting. Should the merge be cancelled? (It's a simple ok to start the installer, though)

Yes, for now silent switches are Required.

**Comment by 2tbc1887** [comment]
> > **Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended.**
> > This installer cannot run unattended, I only noticed this requirement after submitting. Should the merge be cancelled? (It's a simple ok to start the installer, though)
> 
> Yes, for now silent switches are Required.

Shoot, should I close the merge?

**Comment by OfficialEsco** [comment]
Yes please beause we don't have a ETA on installers which require user input

**Comment by DestroyerXyz** [comment]
@OfficialEsco Can I get a new validator on #14530

**Pull request closed without merging**
