### PR TITLE
New version: Insecure.Npcap version 1.76

### PR DESCRIPTION
**Pull request by sharunkumar**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/113468&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by stephengillie** [comment]
Hi @sharunkumar,

Is there an installer switch to automatically accept the above license and proceed automatically with the install?

**Comment by sharunkumar** [comment]
> Is there an installer switch to automatically accept the above license and proceed automatically with the install?

When I set the default silent flag, it gives this message:

```yml
  InstallerSwitches:
    Silent: normal
```

image

**Comment by sharunkumar** [comment]
According to https://npcap.com/oem/#features it seems like silent installs are a pro-feature. is there a way to let winget know that this install needs user input?

**Comment by sharunkumar** [comment]
https://github.com/microsoft/winget-cli/issues/823

**Pull request closed without merging**
