### PR TITLE
Update package: EMOJI-FZCO.VoiceHotKey version 1.4.10

### PR DESCRIPTION
**Pull request by voicehotkey**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164175)

### CODE REVIEW

**Comment by voicehotkey** [comment]
@microsoft-github-policy-service agree company="EMOJI - FZCO"

**Comment by voicehotkey** [comment]
@microsoft-github-policy-service agree [company="EMOJI - FZCO"]

---
Please reply if it solved your issue.
If problem persists you can contact me in Telegram https://t.me/voicekey 
or WhatsApp https://wa.me/971586989075 or reply back to email 
***@***.***

Best regards,
Stepan
VoiceHotKey - best Audio to Text conversion
***@***.***
https://t.me/voicekey - Telegram
https://wa.me/971586989075 - WhatsApp

**Comment by voicehotkey** [comment]
@microsoft-github-policy-service agree

---
Please reply if it solved your issue.
If problem persists you can contact me in Telegram https://t.me/voicekey 
or WhatsApp https://wa.me/971586989075 or reply back to email 
***@***.***

Best regards,
Stepan
VoiceHotKey - best Audio to Text conversion
***@***.***
https://t.me/voicekey - Telegram
https://wa.me/971586989075 - WhatsApp

**Comment by voicehotkey** [comment]
@microsoft-github-policy-service agree company="EMOJI - FZCO"

---
Please reply if it solved your issue.
If problem persists you can contact me in Telegram https://t.me/voicekey 
or WhatsApp https://wa.me/971586989075 or reply back to email 
***@***.***

Best regards,
Stepan
VoiceHotKey - best Audio to Text conversion
***@***.***
https://t.me/voicekey - Telegram
https://wa.me/971586989075 - WhatsApp

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
