### PR TITLE
New package: BSG.Launcher version 13.0.2.2031

### PR DESCRIPTION
**Pull request by SpoonMcForky**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/127499)

### CODE REVIEW

**Comment by SpoonMcForky** [comment]
@microsoft-github-policy-service agree

**Comment by SpoonMcForky** [comment]
There is a more direct URL that is redirected from that URL, however I believe this would break if the app was updated. Perhaps the error comes from their DNS verification? The download should function properly, in my sandboxed test it worked perfectly.

**Comment by stephengillie** [comment]
Hi @SpoonMcForky,

I couldn't find the InstallerUrl from the PackageUrl. Additionally, this package doesn't appear to be released yet - several locations on the website advertise a [pre-order offer](https://github.com/microsoft/winget-pkgs/assets/114952565/8c359e48-4072-45bc-9b03-395efc518747), and mention a beta. 
- Should this be the beta version? Maybe `BSG.launcher.beta`? 
- Can you help me to find the InstallerUrl from the PackageUrl? 

Please do share the other URL, as it might be preferred for one of several reasons.

**Comment by SpoonMcForky** [comment]
> Hi @SpoonMcForky,
> 
> I couldn't find the InstallerUrl from the PackageUrl. Additionally, this package doesn't appear to be released yet - several locations on the website advertise a [pre-order offer](https://github.com/microsoft/winget-pkgs/assets/114952565/8c359e48-4072-45bc-9b03-395efc518747), and mention a beta.
> 
> * Should this be the beta version? Maybe `BSG.launcher.beta`?
> * Can you help me to find the InstallerUrl from the PackageUrl?
> 
> Please do share the other URL, as it might be preferred for one of several reasons.

While the game is stated to be in "beta", which, I suppose it is if the creators say it is, it's been in beta for the last 7 years, and I doubt the links will change. I could add a beta flag however. 
This is the URL it points to: `https://cdn-13.eft-store.com/LauncherDistribs/13.0.2.2031_9a47772135d8be30b58c40d8a7b6fa33/BsgLauncher.13.0.2.2031.exe`
I'm not entirely sure what you mean about the package and installer URL, could you elaborate?

**Comment by stephengillie** [comment]
Hi @SpoonMcForky,

One requirement is to be able to navigate from the PackageUrl to the InstallerUrl. 

Another requirement is that the package has to be available for download from almost any number of anonymous users at the same or any number of terrestrial locations at almost any time. This package's website seems to prevent downloads without registering, which doesn't meet the requirement. 

Thanks for sharing this link - it looks like a direct link to this version instead of a vanity URL that always serves the latest version. This direct link would usually be preferred to the vanity URL. But the 2nd requirement still has to be met.

Is there another page that has either of these links on it? We could change the PackageUrl to that page.

**Pull request closed without merging**
