### PR TITLE
New version: MAMP.MAMP version 5.0.4

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/37808)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
image
Ofc one of the few packages i didn't try would fail

**Comment by Inclushe** [comment]
@OfficialEsco I just contacted MAMP support about this issue.

**Comment by OfficialEsco** [comment]
> @OfficialEsco I just contacted MAMP support about this issue.

Thank you 😁

**Comment by Inclushe** [comment]
Would it be possible to add this dependency to the install: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.22-windows-x64-installer

**Comment by Inclushe** [comment]
> Would it be possible to add this dependency to the install: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.22-windows-x64-installer
@OfficialEsco

**Comment by OfficialEsco** [comment]
As of right now we don't support dependency's (its in experimental)
But if there is no prompt if .net (3.1.22) is installed that is good to know.

So we need to wait for Dependency's to get out of experimental AND wait for [Microsoft.dotnet](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/dotnet) to be split into multiple folders

**Comment by Inclushe** [comment]
@OfficialEsco I just figured out this process of adding packages without the application owner's consent.
I asked support if they could add .NET to their installation process in the next update. Is .NET able to be installed unattended when invoked by an installer with winget?

**Comment by OfficialEsco** [comment]
Well the issue here is that it starts installing .NET once you press OK, which is a silly thing to do when the installer is told to be silent

**Comment by Inclushe** [comment]
And installing that .NET framework fixes it, correct?

**Comment by OfficialEsco** [comment]
Ahh i linked to the wrong dependency (messy names), [Microsoft.dotnetRuntime.3-x86](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/dotnetRuntime/3-x86) is currently the correct dependency
Yes it does.
VirtualBoxVM_Zg1I08BgNB
However this installation end screen look scary (as you can see the Start-Process command is not finished)
VirtualBoxVM_gZMx65dNxL

**Comment by Inclushe** [comment]
From MAMP support:

"We need to take some time and investigate this issue in the time period when work and obligations allows us.
We will report back when we have enough thoroughly investigated data and clear and confirmed information."

Also I didn't realize that the support people didn't have dev knowledge. They are a bigger organization than I thought.

**Pull request closed without merging**
