### PR TITLE
New Version: GodotEngine.GodotEngine version 2.0.4.1

### PR DESCRIPTION
**Pull request by og-mrk**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141456)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\GodotEngine.GodotEngine__DefaultSource\Godot_v2.0.4.1_stable_win64.exe returned exit code: -1073741819
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\Godot_v2.0.4.1_stable_win64.exe returned exit code: -1073741819
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Packages\GodotEngine.GodotEngine__DefaultSource\Godot_v2.0.4.1_stable_win32.exe returned exit code: -1073741819
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\Godot_v2.0.4.1_stable_win32.exe returned exit code: -1073741819

(Automated response - build 855.)

**Comment by stephengillie** [comment]
Hi @og-mrk,

> This PR's version number 2.0.4.1 has 4 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version 4.2.1, which has 3 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 857)

**Comment by og-mrk** [comment]
Hello @stephengillie,

> Hi @og-mrk,
> 
> > This PR's version number 2.0.4.1 has 4 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version 4.2.1, which has 3 parameters.
> 
> Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)
> 
> (Automated response - build 857)

This PR's version number (2.0.4.1) does match the one shown in the Apps & features Settings page, **_see the screenshot below_**.

image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
