### PR TITLE
New package: OptimiseHealth.OptimiseBPDesktop version 4.1.4

### PR DESCRIPTION
**Pull request by fraserbooth**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/146241)

### CODE REVIEW

**Comment by fraserbooth** [comment]
@microsoft-github-policy-service agree

**Comment by fraserbooth** [comment]
Validation-Domain

All URLs point to our www.optbp.com domain except the support URL which is hosted by FreshDesk.

Anyone any idea what is causing this validation error?

**Comment by stephengillie** [comment]
Hi @fraserbooth,

There's a general requirement that anyone be able to navigate from the `PackageUrl` to the `InstallerUrl`. I believe that's the cause of the label here, as I'm also unable to find the `InstallerUrl`, instead finding a Free Trial offer. 

Could you share where you found the `InstallerUrl`? That page might make a better `PackageUrl`.

**Comment by fraserbooth** [comment]
@stephengillie do you know what happens with this next? I've made the changes you suggested, and the @wingetbot has removed all the labels. I assume there still needs to be a review / approval before I can merge this and it become generally available. This is my first foray into the WinGet Repo :)
Thank you for your help & advice.

**Comment by stephengillie** [comment]
I think our bots stalled over the weekend.

**Comment by fraserbooth** [comment]
Thank you, I thought I had resolved this with the link to the downloads URL. Is that not enough? What other information is needed? All the best,
Fraser

**Comment by stephengillie** [comment]
It needed a manual check again, but I wasn't aware. Thank you @fraserbooth, for drawing me back to this PR.

**Comment by stephengillie** [comment]
Manual Validation ended with: 
You must install the .NET Desktop Runtime to run this application.

I tried with `Microsoft.DotNet.DesktopRuntime.6` as a dependency, but the version we have is 64-bit, while this is an `x86` application.

**Pull request closed without merging**
