### PR TITLE
Delete: tibbo.ioninja version 5.0.4

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/46516)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
image

cc @Trenly @vedantmgoyal2009: You can remove this package from the repo.

**Review by ItzLevvie — APPROVED** [review]

**Comment by vedantmgoyal2009** [comment]
@ItzLevvie Should we remove all the versions?

**Comment by vedantmgoyal2009** [comment]
> @ItzLevvie Should we remove all the versions?

@ItzLevvie

**Comment by ItzLevvie2** [comment]
> Should we remove all the versions?

No, looks like the URL was missing `-core` at the end which is why it wasn't installing.

**Pull request merged**
