### PR TITLE
New Version: WHONET.WHONET version 23.15.12

### PR DESCRIPTION
**Pull request by drshtmstry**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/144261)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2145844845
> 2024-03-14 04:31:41.169 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-03-14 04:31:41.211 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFDBEB4A465: (caller: 00007FFDBEB4AD01) Exception(1) tid(bdc) 80190193 Forbidden (403).
> 2024-03-14 04:31:41.634 [CORE] Download request failed. Returned status: 403
> 2024-03-14 04:31:41.634 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFDBEB443D6: (caller: 00007FFDBEB45C49) Exception(2) tid(bdc) 80190193 Forbidden (403).
> 2024-03-14 04:31:41.861 [CLI ] Failed to download, waiting a bit and retry. Url: https://whonet.org/WHONET2023-Setup-x64.exe
> 2024-03-14 04:31:42.515 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-03-14 04:31:42.515 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFDBEB4A465: (caller: 00007FFDBEB4AD01) Exception(3) tid(bdc) 80190193 Forbidden (403).
> 2024-03-14 04:31:42.596 [CORE] Download request failed. Returned status: 403
> 2024-03-14 04:31:42.596 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFDBEB443D6: (caller: 00007FFDBEB45C49) Exception(4) tid(bdc) 80190193 Forbidden (403).
> 2024-03-14 04:31:42.752 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFDBEB443D6: (caller: 00007FFDBEB45C49) Exception(4) tid(bdc) 80190193 Forbidden (403).

(Automated response - build 870.)

**Comment by stephengillie** [comment]
> Possible duplicate package entry.
> 
> Similar installer SHA256 hash found in manifest:
> 
> * `InstallerSha256: 563f5dfc378319e2dfe415922bf3e64dfbf0079e80c8e366dad21d579825299d`
>   
>   * manifests\w\WHONET\2023\23.15.12
> * `InstallerSha256: 766f58c4c259e43b3f503c8636052faf0cb5809837e58c58e7b70100a9639ea1`
>   
>   * manifests\w\WHONET\2023\23.15.12

Hi @drshtmstry,

It looks like a package with this version already exists - is `WHONET.2023` being moved to `WHONET.WHONET`?

**Comment by drshtmstry** [comment]
> > Possible duplicate package entry.
> > Similar installer SHA256 hash found in manifest:
> > 
> > * `InstallerSha256: 563f5dfc378319e2dfe415922bf3e64dfbf0079e80c8e366dad21d579825299d`
> >   
> >   * manifests\w\WHONET\2023\23.15.12
> > * `InstallerSha256: 766f58c4c259e43b3f503c8636052faf0cb5809837e58c58e7b70100a9639ea1`
> >   
> >   * manifests\w\WHONET\2023\23.15.12
> 
> Hi @drshtmstry,
> 
> It looks like a package with this version already exists - is `WHONET.2023` being moved to `WHONET.WHONET`?

Yes this package is being moved to WHONET.WHONET id. I will remove WHONET.2023 after this PR is approved.

This way this package can be automatically upgraded every year by @wingetbot and requires minimal manual intervention.

**Comment by drshtmstry** [comment]
> > Possible duplicate package entry.
> > Similar installer SHA256 hash found in manifest:
> > 
> > * `InstallerSha256: 563f5dfc378319e2dfe415922bf3e64dfbf0079e80c8e366dad21d579825299d`
> >   
> >   * manifests\w\WHONET\2023\23.15.12
> > * `InstallerSha256: 766f58c4c259e43b3f503c8636052faf0cb5809837e58c58e7b70100a9639ea1`
> >   
> >   * manifests\w\WHONET\2023\23.15.12
> 
> Hi @drshtmstry,
> 
> It looks like a package with this version already exists - is `WHONET.2023` being moved to `WHONET.WHONET`?

@stephenghillie Yes, this package is being moved to WHONET.WHONET id. I will remove WHONET.2023 after this PR is approved.

This way this package can be automatically upgraded every year by @wingetbot and requires minimal manual intervention.

**Comment by drshtmstry** [comment]
> > Possible duplicate package entry.
> > Similar installer SHA256 hash found in manifest:
> > 
> > * `InstallerSha256: 563f5dfc378319e2dfe415922bf3e64dfbf0079e80c8e366dad21d579825299d`
> >   
> >   * manifests\w\WHONET\2023\23.15.12
> > * `InstallerSha256: 766f58c4c259e43b3f503c8636052faf0cb5809837e58c58e7b70100a9639ea1`
> >   
> >   * manifests\w\WHONET\2023\23.15.12
> 
> Hi @drshtmstry,
> 
> It looks like a package with this version already exists - is `WHONET.2023` being moved to `WHONET.WHONET`?

@stephenghillie Yes, this package is being moved to WHONET.WHONET id. I will remove WHONET.2023 after this PR is approved.

This way this package can be automatically upgraded every year by @wingetbot and requires minimal manual intervention.

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 1:28:34 PM: 
> 2024-03-15 13:28:28.444 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000 1:28:34 PM: 
> 2024-03-15 13:28:28.445 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFC2A83E73F: (caller: 00007FFC2A83F07C) Exception(1) tid(a70) 80190193 Forbidden (403). 1:28:34 PM: 
> 2024-03-15 13:28:32.462 [CORE] Download request failed. Returned status: 403 1:28:34 PM: 
> 2024-03-15 13:28:32.462 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFC2A838767: (caller: 00007FFC2A839FC9) Exception(2) tid(a70) 80190193 Forbidden (403). 1:28:34 PM: 
> 2024-03-15 13:28:32.465 [CLI ] Failed to download, waiting a bit and retry. Url: https://whonet.org/WHONET2023-Setup-x64.exe 1:28:34 PM: 
> 2024-03-15 13:28:33.514 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000 1:28:34 PM: 
> 2024-03-15 13:28:33.514 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFC2A83E73F: (caller: 00007FFC2A83F07C) Exception(3) tid(a70) 80190193 Forbidden (403). 1:28:34 PM: 
> 2024-03-15 13:28:33.686 [CORE] Download request failed. Returned status: 403 1:28:34 PM: 
> 2024-03-15 13:28:33.686 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFC2A838767: (caller: 00007FFC2A839FC9) Exception(4) tid(a70) 80190193 Forbidden (403).

(Automated response - build 870.)

**Comment by stephengillie** [comment]
URL: https://whonet.org/WHONET2023-Setup-x86.exe 
Status Code: 200

(Automated message - build 870)

**Comment by drshtmstry** [comment]
> URL: https://whonet.org/WHONET2023-Setup-x86.exe Status Code: 200
> 
> (Automated message - build 870) Edit x64 also gives 200 OK. This might be a user-agent string block, to allow users to download but not package managers.

This error only seen some times in validation pipelines.
I have used winget to install this package in many pc. I have never encountered this error.

**Comment by drshtmstry** [comment]
> URL: https://whonet.org/WHONET2023-Setup-x86.exe Status Code: 200
> 
> (Automated message - build 870) Edit x64 also gives 200 OK. This might be a user-agent string block, to allow users to download but not package managers.

@stephengillie  This error only seen some times in validation pipelines.
I have used winget to install this package in many pc. I have never encountered this error.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2145844845
> 2024-03-18 10:02:50.025 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-03-18 10:02:50.064 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFC09E2A465: (caller: 00007FFC09E2AD01) Exception(1) tid(2290) 80190193 Forbidden (403).
> 2024-03-18 10:02:50.764 [CORE] Download request failed. Returned status: 403
> 2024-03-18 10:02:50.764 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFC09E243D6: (caller: 00007FFC09E25C49) Exception(2) tid(2290) 80190193 Forbidden (403).
> 2024-03-18 10:02:50.777 [CLI ] Failed to download, waiting a bit and retry. Url: https://whonet.org/WHONET2023-Setup-x64.exe
> 2024-03-18 10:02:51.413 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-03-18 10:02:51.413 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFC09E2A465: (caller: 00007FFC09E2AD01) Exception(3) tid(2290) 80190193 Forbidden (403).
> 2024-03-18 10:02:51.494 [CORE] Download request failed. Returned status: 403
> 2024-03-18 10:02:51.494 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFC09E243D6: (caller: 00007FFC09E25C49) Exception(4) tid(2290) 80190193 Forbidden (403).
> 2024-03-18 10:02:51.668 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFC09E243D6: (caller: 00007FFC09E25C49) Exception(4) tid(2290) 80190193 Forbidden (403).

(Automated response - build 870.)

**Pull request closed without merging**
