### PR TITLE
Add Notepads

### PR DESCRIPTION
**Pull request by 0x7c13**
Add Notepads
Project Page: https://github.com/JasonStein/Notepads
Store link: https://www.microsoft.com/store/apps/9nhl4nsc67wm

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1177)

### CODE REVIEW

**Comment by Teraskull** [comment]
The correct folder structure should be Publisher/Package, in your case it is Package/Package.
Change it to: JackieLiu/Notepads

Only one installer is allowed per manifest, so separate the x64, x86 and ARM64 in different manifests.

Do not include empty keys (AppMoniker: )

And also, for the future, one manifest is allowed per PR.

**Comment by JasonStein** [comment]
> The correct folder structure should be Publisher/Package, in your case it is Package/Package.
> Change it to: JackieLiu/Notepads
> 
> Only one installer is allowed per manifest, so separate the x64, x86 and ARM64 in different manifests.
> 
> Do not include empty keys (AppMoniker: )
> 
> And also, for the future, one manifest is allowed per PR.

I am changing it to Notepads.Notepads and also remove all archs and replaced with Neutral.

**Comment by Teraskull** [comment]
The correct folder format should be Publisher/Package, in your case it is Package/Package.

> > The correct folder structure should be Publisher/Package, in your case it is Package/Package.
> > Change it to: JackieLiu/Notepads
> > Only one installer is allowed per manifest, so separate the x64, x86 and ARM64 in different manifests.
> > Do not include empty keys (AppMoniker: )
> > And also, for the future, one manifest is allowed per PR.
> 
> I am changing it to Notepads.Notepads and also remove all archs and replaced with Neutral.

Great, should work now

**Comment by KevinLaMS** [comment]
The app appears to be signed incorrectly.  
"Install failed: Error <number> the root certificate of the signature in the app package or bundle must be trusted....

**Comment by JasonStein** [comment]
> The app appears to be signed incorrectly.
> "Install failed: Error the root certificate of the signature in the app package or bundle must be trusted....

I am always using the store certificate to sign my app. If I install it using the  powershell script, it will install the cert and then the app without any problem. But for winget, I can only provide the link to the msixbundle binary file itself. I guess there is some gap here or do I need to do something differently?

**Comment by JasonStein** [comment]
> The app appears to be signed incorrectly.
> "Install failed: Error the root certificate of the signature in the app package or bundle must be trusted....

I uploaded a new one to replace it. Can you help install again? It should work now.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
