### PR TITLE
Add BrickLink Studio 2.1.5_7

### PR DESCRIPTION
**Pull request by latere-a-latere**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/840)

### CODE REVIEW

**Comment by samiranshah** [comment]
Is the version 2.1.5_7 or 2.0?

**Comment by MarNicGit** [comment]
> 
> 
> Is the version 2.1.5_7 or 2.0?

The website advertises it as 2.0 but the actual version is 2.1.5_7. I used the download link used in the changelog on [this page](https://www.bricklink.com/v2/studio/download.page) (scroll down).

It does appear however that their download link is a rolling version - wouldn't be surprised if the installer downloads the most recent minor off the web.

**Comment by MarNicGit** [comment]
Turns out the v3 page of Studio does list version specific download links. Adjusted the manifest as such.
https://www.bricklink.com/v3/studio/download.page?utm_content=subnav

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
