### PR TITLE
Microsoft Azure Storage Explorer 1.20.1

### PR DESCRIPTION
**Pull request by thomasvochten**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23452)

### CODE REVIEW

**Comment by thomasvochten** [comment]
Strange, validation on local machine and inside a Windows Sandbox worked just fine...

**Comment by ImJoakim** [comment]
> Strange, validation on local machine and inside a Windows Sandbox worked just fine...

The bot has been having a few issues lately by the looks of it. Try rerunning it by closing the PR and reopen it again via the **Reopen pull request** button.

**Comment by thomasvochten** [comment]
Reopening as per @ImJoakim 's suggestion...

**Comment by thomasvochten** [comment]
"Installer Validation failed" remains after reopening the PR it seems...

**Comment by ImJoakim** [comment]
> "Installer Validation failed" remains after reopening the PR it seems...

It should go away once it runs that specific check again. Seems like it's gone now.

**Comment by thomasvochten** [comment]
> > "Installer Validation failed" remains after reopening the PR it seems...
> 
> It should go away once it runs that specific check again. Seems like it's gone now because it just started the Installer Validation check.

Got it - reacted too soon, didn't realize the previous run status remains until it runs again...

**Review by jedieaston — APPROVED** [review]

**Review by vedantmgoyal9 — APPROVED** [review]

**Pull request merged**
