### PR TITLE
VMX.APP.Test version 1.0

### PR DESCRIPTION
**Pull request by Timmy5818**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/49984)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/49984#issuecomment-1057784663

**Comment by Timmy5818** [comment]
Hello, if I want to test upload, is there a way for me to test and upload the executable file to the winget test?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> Hello, if I want to test upload, is there a way for me to test and upload the executable file to the winget test?

There is https://github.com/microsoft/winget-pkgs-submission-test which is a test repository for testing and validating manifest submissions to GitHub for the [Windows Package Manager Manifest Creator (Winget-Create)](https://github.com/microsoft/winget-create) tool.

You can test your packages by creating the package using the winget-create tool and then do `winget install --manifest <PATH_TO_PACKAGE_VERSION>` or `winget upgrade --manifest <PATH_TO_PACKAGE_VERSION>`.

If you want to upload test packages and play around with them, you will probably need to set up a REST API using https://github.com/microsoft/winget-cli-restsource

**Comment by Timmy5818** [comment]
Thank you, I'll test it here

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/49984#pullrequestreview-900391719

**Pull request closed without merging**
