### PR TITLE
New version: Ryujinx.Ryujinx.Ava version 1.1.1100

### PR DESCRIPTION
**Pull request by rakleed**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/130889)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Exception during executable launch operation System.InvalidOperationException: No process is associated with this object.

**Review by stephengillie — APPROVED** [review]

**Comment by soredake** [comment]
@rakleed why do you submit regular ryujinx zip into Avalonia package?

**Comment by rakleed** [comment]
@soredake thanks for pointing it out, I'll fix it.

**Pull request merged**
