### PR TITLE
Add Scope: Machine to PowerShell 7.2.8.0 installer manifest

### LINKED ISSUE #95172: winget downloads PowerShell v7.2.7 when machine scope is specified
also related to Powershell: why is winget trying to install v7.2.7 when requested a machine scope? i had to cancel the installation (ctrl-c)

Winget clearly shows that v7.3.1 is in the package manifest... but then it goes to download v7.2.7? 
os: Win 10 x64 Pro 22H2 with full updates, including 2023-01 

```
C:\WINDOWS\system32>winget show Microsoft.PowerShell
Found PowerShell [Microsoft.PowerShell]
Version: 7.3.1.0
Publisher: Microsoft Corporation
Publisher Url: https://github.com/PowerShell/PowerShell/
Publisher Support Url: https://github.com/PowerShell/PowerShell/issues
Author: Microsoft Corporation
Moniker: pwsh
Description:
  PowerShell is a cross-platform (Windows, Linux, and macOS) automation and configuration tool/framework that works well with your existing tools and is optimized for dealing with structured data (e.g. JSON, CSV, XML, etc.), REST APIs, and object models.
  It includes a command-line shell, an associated scripting language and a framework for processing cmdlets.
Homepage: https://microsoft.com/PowerShell
License: MIT
License Url: https://github.com/PowerShell/PowerShell/blob/master/LICENSE.txt
Copyright: Copyright (c) Microsoft Corporation
Copyright Url: https://github.com/PowerShell/PowerShell/blob/master/LICENSE.txt
Release Notes Url: https://github.com/PowerShell/PowerShell/releases/tag/v7.3.1
Tags:
  command-line
  cross-platform
  open-source
  powershell
  pwsh
  shell
Installer:
  Installer Type: wix
  Installer Url: https://github.com/PowerShell/PowerShell/releases/download/v7.3.1/PowerShell-7.3.1-win-x64.msi
  Installer SHA256: cad0026df877f1b195b87aae1858e8bc8ba759c19b7440cd62e1f5432665519f
  Release Date: 2022-12-13

C:\WINDOWS\system32>

C:\WINDOWS\system32>winget install Microsoft.PowerShell  --scope machine
Found PowerShell [Microsoft.PowerShell] Version 7.2.7.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/PowerShell/PowerShell/releases/download/v7.2.7/PowerShell-7.2.7-win-x64.msi
  ████▉                           17.0 MB /  102 MB
^C^C^C Package download canceled.


C:\WINDOWS\system32>winget --info
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.2486
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

User Settings: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json

```

_Originally posted by @R-Adrian in https://github.com/microsoft/winget-pkgs/issues/94861#issuecomment-1409887688_

### PR DESCRIPTION
**Pull request by anamnavi**
Resolves #95172 

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

### CODE REVIEW

**Comment by anamnavi** [comment]
@mdanish-kh I added Machine: scope. It wasn't intentional to remove, we just used the default option. Someone installing with User scope would still be able to do so with the scope listed as machine now, is that correct?

**Comment by mdanish-kh** [comment]
@anamnavi If the installer supports dual context installation, then there should be separate InstallerSwitches present in the manifest for each scope informing WinGet how to carry out the installation. I'll use Oh-my-posh as an example manifest:
https://github.com/microsoft/winget-pkgs/blob/a0fd41b1ad6c8c14f87f5d337b468562a30ecb9d/manifests/j/JanDeDobbeleer/OhMyPosh/14.0.1/JanDeDobbeleer.OhMyPosh.installer.yaml#L15-L26

A quick google search on the MSI Installer Switches showed that `ALLUSERS=2 MSIINSTALLPERUSER=1` need to be passed to the installer at install-time for a per-user installation ([Ref: MSIINSTALLPERUSER property](https://learn.microsoft.com/en-us/windows/win32/msi/msiinstallperuser)). I checked in a fresh VM that silent installation with these switches fails with no installation. If I don't provide the silent switches and go for an interactive installation I get this error:
image

I'm not an expert, but this leads me to believe that PowerShell installer supports only per-machine installation.

**Comment by mdanish-kh** [comment]
A better example would be Microsoft.RemoteDesktopClient which is also an MSI based installer and works with both `winget install Microsoft.RemoteDesktopClient --scope machine` and `winget install Microsoft.RemoteDesktopClient --scope user` as separate switches for it are present in the manifest and the installer seems to support them as well as I've manually verified the behavior in a VM
https://github.com/microsoft/winget-pkgs/blob/d5b6185dca3e271f7242773e5bbb696c255faf6d/manifests/m/Microsoft/RemoteDesktopClient/1.2.3497.0/Microsoft.RemoteDesktopClient.installer.yaml#L16-L32

**Comment by anamnavi** [comment]
@mdanish-kh thanks this explains it well! I checked with my team and we don't support user-scope so just the `Scope: machine` being specified should suffice

**Review by mdanish-kh — APPROVED** [review]

**Comment by anamnavi** [comment]
@mdanish-kh any idea why the internal error may be occurring? thanks :)

**Comment by mdanish-kh** [comment]
@stephengillie would know more, but it's probably because the pipelines were updated recently to add validation for `.zip` packages so we may see these hiccups. Would also be the reason why my moderator powers are not working today to approve this PR. 😅

**Review by ItzLevvie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
