### PR TITLE
Elcomsoft.AdvancedOfficePasswordRecovery version 7.20.2665.6987

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/102161)

### CODE REVIEW

**Comment by upintheairsheep** [comment]
Merge plz, no issues present.

**Comment by stephengillie** [comment]
Automatic Validation failed with:
> ##[error] Installer https://www.elcomsoft.com/download/aopr_setup_en.msi 
> Scan request id: '9962adc5-1ab7-455d-902e-3ce580855fe1' 
> Error information: BlockingDetectionFound 
> ##[error] Result: Failed 

This might be due to a network block of data centers, to prevent automated downloads.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
