### PR TITLE
Add vagrant 2.2.9 manifest

### PR DESCRIPTION
**Pull request by mizutoki79**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2328)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
Installation causes automatic reboot.  This is unexpected.

**Comment by mizutoki79** [comment]
`/promptrestart` switch didn't work.
`/norestart` switch suppressed restart, but winget say `Installer failed with exit code: 3010`.
I think we need to allow 3010 in winget-cli for this installation to succeed.

**Comment by KevinLaMS** [comment]
> https://github.com/microsoft/winget-cli/issues/137

**Comment by KevinLaMS** [comment]
still blocked on error code.

**Comment by denelon** [comment]
We now support non-zero exit codes with the new manifest schema :smile:

**Pull request closed without merging**
