### PR TITLE
New version: mindersec.minder 0.0.78

### PR DESCRIPTION
**Pull request by rdimitrov**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/196758)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-12-06 09:06:01.984 [FAIL] Installer failed security check. Url: https://github.com/mindersec/minder/releases/download/v0.0.78/minder_0.0.78_windows_amd64.zip Result: 0x80004005

(Automated response - build 900.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-12-09 09:37:36.164 [FAIL] Installer failed security check. Url: https://github.com/mindersec/minder/releases/download/v0.0.78/minder_0.0.78_windows_amd64.zip Result: 0x80004005

(Automated response - build 900.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-12-09 10:20:27.894 [FAIL] Installer failed security check. Url: https://github.com/mindersec/minder/releases/download/v0.0.78/minder_0.0.78_windows_amd64.zip Result: 0x80004005

(Automated response - build 900.)

**Comment by rdimitrov** [comment]
@stephengillie - hey, if possible can you share more details why this fails? Thanks in advance!

**Comment by rdimitrov** [comment]
I think we can close this one as it's superseded by https://github.com/microsoft/winget-pkgs/pull/197534

**Comment by stephengillie** [comment]
Verify:
image

**Comment by stephengillie** [comment]
> @stephengillie - hey, if possible can you share more details why this fails? Thanks in advance!

This is a failed Defender scan.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
