### PR TITLE
Add VapourSynth R52 x64

### PR DESCRIPTION
**Pull request by notAutomne**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3521)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
image

**Comment by marwanpro** [comment]
@KevinLaMS Yes, Python 3.8 (64-bit) is mandatory. 
However, if you install it, it will works finely.
I will specify the dependency once WinGet supports it.

**Comment by therealt3nzin** [comment]
@marwanpro Python is now available via winget, should be able to move this PR forward with Python v3.8.x for VapourSynth R52 and Python v3.9.x for VapourSynth R53 when it releases (currently in release candidate stage)

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @marwanpro,

The installer prompts whether to install for all users, or just for the current user. Is there an installer switch to specify this? Packages need a fully-unattended mode to be available for install through Winget.
image

We now support dependencies and have Python 3.8 among our installable packages, though the manifest might need to be rewritten as a [Schema 1.2 multi-part manifest](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)

**Comment by marwanpro** [comment]
Hello,

I will check this next week then commit fixes
________________________________

**Comment by ItzLevvie** [comment]
@msftbot Blocking-Issue

**Comment by ItzLevvie** [comment]
[Policy] Needs-CLA

image

**Comment by ItzLevvie** [comment]
Has been changed to:
image

**Comment by stephengillie** [comment]
Closing PR as stale.

**Pull request closed without merging**
