### PR TITLE
New version: Microsoft.WindowsADK version 10.1.25398.1

### PR DESCRIPTION
**Pull request by rasa**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135254)

### CODE REVIEW

**Comment by rasa** [comment]
It's missing a `ProductCode` value. Komac didn't add it. How do I determine this value, without installing it first?

**Comment by rasa** [comment]
Related to https://github.com/microsoft/winget-pkgs/pull/135256

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335226 2024-01-22 15:40:37.290 [CLI ] ShellExecute installer failed: 2147942487 MSI (s) (D0:E8) [15:40:35:866]: Windows Installer removed the product. Product Name: Toolkit Documentation. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Removal success or error status: 0. MSI (s) (D0:EC) [15:40:32:710]: Windows Installer installed the product. Product Name: Toolkit Documentation. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Installation success or error status: 0. MSI (s) (D0:38) [15:40:34:725]: Windows Installer removed the product. Product Name: Windows Deployment Tools Environment. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Removal success or error status: 0. MSI (s) (D0:A4) [15:40:33:397]: Windows Installer installed the product. Product Name: Windows Deployment Tools Environment. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Installation success or error status: 0. [07FC:0900][2024-01-22T15:39:28]w363: Could not create system restore point, error: 0x80070422. Continuing... [07FC:0900][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to enable logging for package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us to: C:\Users\validator\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Microsoft.WindowsADK.10.1.25398.1-2024-01-22-15-39-23.783_002_package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us.log [07FC:0900][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to execute
> MSI package. [1AF0:1720][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to configure per-machine
> MSI package. [1AF0:1720][2024-01-22T15:40:33]i000: RetryManager: Not an execute error to retry: 0x80070057 for package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us [1AF0:1720][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to execute
> MSI package.

(Automated response - build 628.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335226 2024-01-22 15:40:37.290 [CLI ] ShellExecute installer failed: 2147942487 MSI (s) (D0:E8) [15:40:35:866]: Windows Installer removed the product. Product Name: Toolkit Documentation. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Removal success or error status: 0. MSI (s) (D0:EC) [15:40:32:710]: Windows Installer installed the product. Product Name: Toolkit Documentation. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Installation success or error status: 0. MSI (s) (D0:38) [15:40:34:725]: Windows Installer removed the product. Product Name: Windows Deployment Tools Environment. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Removal success or error status: 0. MSI (s) (D0:A4) [15:40:33:397]: Windows Installer installed the product. Product Name: Windows Deployment Tools Environment. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Installation success or error status: 0. [07FC:0900][2024-01-22T15:39:28]w363: Could not create system restore point, error: 0x80070422. Continuing... [07FC:0900][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to enable logging for package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us to: C:\Users\validator\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Microsoft.WindowsADK.10.1.25398.1-2024-01-22-15-39-23.783_002_package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us.log [07FC:0900][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to execute
> MSI package. [1AF0:1720][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to configure per-machine
> MSI package. [1AF0:1720][2024-01-22T15:40:33]i000: RetryManager: Not an execute error to retry: 0x80070057 for package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us [1AF0:1720][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to execute
> MSI package.

(Automated response - build 642.)

**Comment by stephengillie** [comment]
The installer fails but doesn't seem to give a clear reason.

**Comment by rasa** [comment]
> The installer fails but doesn't seem to give a clear reason.

I tested it manually, and it installed fine. 

Is there a framework that users can submit PRs to that will auto-publish updates to Microsoft-based packages? As they come directly from Microsoft, the typical vetting/approval process should be able to be streamlined, or even automated, no?

This would lead to wider adoption. and therefore increases sales, yes?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335226 2024-01-22 15:40:37.290 [CLI ] ShellExecute installer failed: 2147942487 MSI (s) (D0:E8) [15:40:35:866]: Windows Installer removed the product. Product Name: Toolkit Documentation. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Removal success or error status: 0. MSI (s) (D0:EC) [15:40:32:710]: Windows Installer installed the product. Product Name: Toolkit Documentation. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Installation success or error status: 0. MSI (s) (D0:38) [15:40:34:725]: Windows Installer removed the product. Product Name: Windows Deployment Tools Environment. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Removal success or error status: 0. MSI (s) (D0:A4) [15:40:33:397]: Windows Installer installed the product. Product Name: Windows Deployment Tools Environment. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Installation success or error status: 0. [07FC:0900][2024-01-22T15:39:28]w363: Could not create system restore point, error: 0x80070422. Continuing... [07FC:0900][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to enable logging for package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us to: C:\Users\validator\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Microsoft.WindowsADK.10.1.25398.1-2024-01-22-15-39-23.783_002_package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us.log [07FC:0900][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to execute
> MSI package. [1AF0:1720][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to configure per-machine
> MSI package. [1AF0:1720][2024-01-22T15:40:33]i000: RetryManager: Not an execute error to retry: 0x80070057 for package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us [1AF0:1720][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to execute
> MSI package.

(Automated response - build 675.)

**Comment by stephengillie** [comment]
Hi @rasa,

Unfortunately it's not quite so streamlined.

**Comment by rasa** [comment]
The error `Could not create system restore point, error: 0x80070422` is a build issue, not a code issue, so please consider approving this package, or fix the build system.

There doesn't seem to be anything I can do on this end to move this forward, sorry

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335226 2024-01-22 15:40:37.290 [CLI ] ShellExecute installer failed: 2147942487 MSI (s) (D0:E8) [15:40:35:866]: Windows Installer removed the product. Product Name: Toolkit Documentation. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Removal success or error status: 0. MSI (s) (D0:EC) [15:40:32:710]: Windows Installer installed the product. Product Name: Toolkit Documentation. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Installation success or error status: 0. MSI (s) (D0:38) [15:40:34:725]: Windows Installer removed the product. Product Name: Windows Deployment Tools Environment. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Removal success or error status: 0. MSI (s) (D0:A4) [15:40:33:397]: Windows Installer installed the product. Product Name: Windows Deployment Tools Environment. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Installation success or error status: 0. [07FC:0900][2024-01-22T15:39:28]w363: Could not create system restore point, error: 0x80070422. Continuing... [07FC:0900][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to enable logging for package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us to: C:\Users\validator\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Microsoft.WindowsADK.10.1.25398.1-2024-01-22-15-39-23.783_002_package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us.log [07FC:0900][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to execute
> MSI package. [1AF0:1720][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to configure per-machine
> MSI package. [1AF0:1720][2024-01-22T15:40:33]i000: RetryManager: Not an execute error to retry: 0x80070057 for package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us [1AF0:1720][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to execute
> MSI package.

(Automated response - build 679.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 10:11:10 AM: 2024-01-30 10:11:09.399 [CLI ] ShellExecute installer failed: 2147944022 10:11:10 AM: [0618:1530][2024-01-30T10:09:50]w363: Could not create system restore point, error: 0x80070422. Continuing... 10:11:10 AM: [0618:1530][2024-01-30T10:11:07]e000: Error 0x80070656: Failed to install MSI package. 10:11:10 AM: [0618:1530][2024-01-30T10:11:07]e000: Error 0x80070656: Failed to execute MSI package. 10:11:10 AM: [2268:0264][2024-01-30T10:11:07]e000: Error 0x80070656: Failed to configure per-machine MSI package. 10:11:10 AM: [2268:0264][2024-01-30T10:11:07]i000: RetryManager: Not an execute error to retry: 0x80070656 for package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us 10:11:10 AM: [2268:0264][2024-01-30T10:11:07]e000: Error 0x80070656: Failed to execute MSI package. 10:11:10 AM: MSI (s) (CC:18) [10:11:06:726]: Windows Installer installed the product. Product Name: Toolkit Documentation. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Installation success or error status: 0. 10:11:10 AM: MSI (s) (CC:48) [10:11:07:695]: Windows Installer removed the product. Product Name: Toolkit Documentation. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Removal success or error status: 0. 10:11:10 AM: MSI (s) (CC:08) [10:11:06:992]: Windows Installer installed the product. Product Name: Windows Deployment Tools Environment. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Installation success or error status: 0. 10:11:10 AM: MSI (s) (CC:0C) [10:11:07:351]: Windows Installer removed the product. Product Name: Windows Deployment Tools Environment. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Removal success or error status: 0.

(Automated response - build 679.)

**Comment by stephengillie** [comment]
> The error `Could not create system restore point, error: 0x80070422` is a build issue, not a code issue, so please consider approving this package, or fix the build system.
> 
> There doesn't seem to be anything I can do on this end to move this forward, sorry

Unfortunately, the Manual Validation process ends with essentially the same set of errors. Installing manually works, but doesn't show a dependency installation or other blocker - except for agreeing to a license agreement. The license agreement might be the issue here.

Additionally, the license agreement might be a separate issue, as these usually have to be explicitly accepted, not implicitly through an installer.

**Comment by SpecterShell** [comment]
The restore point error might not be the issue that blocks the installation as it is followed by 'Continuing...'. The real one seems to be:

```
[07FC:0900][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to enable logging for package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us to: C:\Users\validator\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Microsoft.WindowsADK.10.1.25398.1-2024-01-22-15-39-23.783_002_package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us.log
[07FC:0900][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to execute MSI package.
[1AF0:1720][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to configure per-machine MSI package.
[1AF0:1720][2024-01-22T15:40:33]i000: Applied package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us with status 0x80070057
[1AF0:1720][2024-01-22T15:40:33]i000: RetryManager: Not an execute error to retry: 0x80070057 for package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us
[1AF0:1720][2024-01-22T15:40:33]i319: Applied execute package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us, result: 0x80070057, restart: None
[1AF0:1720][2024-01-22T15:40:33]e000: Error 0x80070057: Failed to execute MSI package.
```

Probably caused by the Windows path length problem ig.

**Comment by rasa** [comment]
> Additionally, the license agreement might be a separate issue, as these usually have to be explicitly accepted, not implicitly through an installer.

I didn't accept any license prompts. It just installed.

**Comment by rasa** [comment]
> Please, verify that the application installs correctly on architectures specified in the manifest using winget cli.

It installed fine for me, using the winget cli. This must be a Azure issue, yes?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-05-09 11:07:21.208 [CLI ] ShellExecute installer failed: 2147942487
> MSI (s) (A0:80) [11:07:19:769]: Windows Installer removed the product. Product Name: Toolkit Documentation. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Removal success or error status: 0.
> MSI (s) (A0:18) [11:07:18:941]: Windows Installer removed the product. Product Name: Windows Deployment Tools Environment. Product Version: 10.1.25398.1. Product Language: 1033. Manufacturer: Microsoft. Removal success or error status: 0.
> [0DEC:1570][2024-05-09T11:07:17]e000: Error 0x80070057: Failed to enable logging for package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us to: C:\Users\validator\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Microsoft.WindowsADK.10.1.25398.1-2024-05-09-11-05-25.900_002_package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us.log
> [0DEC:1570][2024-05-09T11:07:17]e000: Error 0x80070057: Failed to execute MSI package.
> [0CDC:1620][2024-05-09T11:07:17]e000: Error 0x80070057: Failed to configure per-machine MSI package.
> [0CDC:1620][2024-05-09T11:07:17]i000: RetryManager: Not an execute error to retry: 0x80070057 for package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us
> [0CDC:1620][2024-05-09T11:07:17]e000: Error 0x80070057: Failed to execute MSI package.

Automated error analysis suggests -1978335226 may mean Install successful but system restart may be required.

(Automated response - build 880.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> [04C8:0BF0][
> 2024-05-10T09:26:50]i319: Applied execute package: package_WindowsDeploymentToolsEnvironment_x86_en_us, result: 0x0, restart: None [0B9C:1438][
> 2024-05-10T09:26:50]i325: Registering dependency: {552c6d25-1a53-43da-9069-7cedb7009a80} on package provider: Microsoft.Windows.WindowsDeploymentToolsEnvironment.x86.10, package: package_WindowsDeploymentToolsEnvironment_x86_en_us [0B9C:1438][
> 2024-05-10T09:26:50]i301: Applying execute package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us, action: Install, path: C:\ProgramData\Package Cache\{6B853FE7-17EC-B19A-56BB-CBFF16F9808B}v10.1.25398.1\Installers\Windows Deployment Image Servicing and Management - Headers and Libraries-x86_en-us.msi, arguments: ' ARPSYSTEMCOMPONENT="1" MSIFASTINSTALL="7" KITSROOT="C:\Program Files (x86)\Windows Kits\10\" KITSOPTION="OptionId.DeploymentTools" ARPSYSTEMCOMPONENT="1" UserLocale="en-us"' [0B9C:1438][
> 2024-05-10T09:26:50]e000: Error 0x80070656: Failed to install MSI package. [0B9C:1438][
> 2024-05-10T09:26:50]e000: Error 0x80070656: Failed to execute MSI package. [04C8:0BF0][
> 2024-05-10T09:26:50]e000: Error 0x80070656: Failed to configure per-machine MSI package. [04C8:0BF0][
> 2024-05-10T09:26:50]i000: Applied package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us with status 0x80070656 [04C8:0BF0][
> 2024-05-10T09:26:50]i000: RetryManager: Not an execute error to retry: 0x80070656 for package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us [04C8:0BF0][
> 2024-05-10T09:26:50]i319: Applied execute package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us, result: 0x80070656, restart: None [04C8:0BF0][
> 2024-05-10T09:26:50]e000: Error 0x80070656: Failed to execute MSI package. [0B9C:1438][
> 2024-05-10T09:26:50]i318: Skipped rollback of package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us, action: Uninstall, already: Absent [04C8:0BF0][
> 2024-05-10T09:26:50]i000: Applied package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us with status 0 [04C8:0BF0][
> 2024-05-10T09:26:50]i319: Applied rollback package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us, result: 0x0, restart: None [0B9C:1438][
> 2024-05-10T09:26:50]i351: Removing cached package: package_WindowsDeploymentImageServicingandManagementHeadersandLibraries_x86_en_us, from path: C:\ProgramData\Package Cache\{6B853FE7-17EC-B19A-56BB-CBFF16F9808B}v10.1.25398.1\ [0B9C:1438][
> 2024-05-10T09:26:50]i326: Removed dependency: {552c6d25-1a53-43da-9069-7cedb7009a80} on package provider: Microsoft.Windows.WindowsDeploymentToolsEnvironment.x86.10, package package_WindowsDeploymentToolsEnvironment_x86_en_us [0B9C:1438][
> 2024-05-10T09:26:50]i301: Applying rollback package: package_WindowsDeploymentToolsEnvironment_x86_en_us, action: Uninstall, path: (null), arguments: ' ARPSYSTEMCOMPONENT="1" MSIFASTINSTALL="7" KITSROOT="C:\Program Files (x86)\Windows Kits\10\" KITSOPTION="OptionId.DeploymentTools" ARPSYSTEMCOMPONENT="1" UserLocale="en-us"' [04C8:0BF0][
> 2024-05-10T09:26:51]i000: Applied package_WindowsDeploymentToolsEnvironment_x86_en_us with status 0 [04C8:0BF0][
> 2024-05-10T09:26:51]i319: Applied rollback package: package_WindowsDeploymentToolsEnvironment_x86_en_us, result: 0x0, restart: None [0B9C:1438][
> 2024-05-10T09:26:51]i351: Removing cached package: package_WindowsDeploymentToolsEnvironment_x86_en_us, from path: C:\ProgramData\Package Cache\{C0C05C2F-4463-9031-01BF-B2C0F077C8C0}v10.1.25398.1\ [0B9C:1438][
> 2024-05-10T09:26:51]i326: Removed dependency: {552c6d25-1a53-43da-9069-7cedb7009a80} on package provider: Microsoft.Windows.ToolkitDocumentation.x86.10, package package_ToolkitDocumentation_x86_en_us [0B9C:1438][
> 2024-05-10T09:26:51]i301: Applying rollback package: package_ToolkitDocumentation_x86_en_us, action: Uninstall, path: (null), arguments: ' ARPSYSTEMCOMPONENT="1" MSIFASTINSTALL="7" KITSROOT="C:\Program Files (x86)\Windows Kits\10\" KITSOPTION="OptionId.Documentation" ARPSYSTEMCOMPONENT="1" UserLocale="en-us"' 

(Automated response - build 880.)

**Comment by rasa** [comment]
@stephengillie Thanks for the follow up, but I am not skilled in this area. Since this is assigned to me, what I am expected to do to fix it? I really have no idea. Perhaps reassign to a Microsoft dev who is familiar with this package (or this specific error)?

**Comment by stephengillie** [comment]
Close with reason: Duplicate of #153237;

**Pull request closed without merging**
