### PR TITLE
New version: Jackett.Jackett version 0.21.1465

### PR DESCRIPTION
**Pull request by ilike2burnthing**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132222)

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
See also https://github.com/microsoft/winget-pkgs/pull/132180 and https://github.com/microsoft/winget-pkgs/pull/132103.

**Comment by ilike2burnthing** [comment]
https://github.com/microsoft/winget-pkgs/pull/132297 approved without issue, again no major changes.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 
> 2023-12-30 22:18:10.096 [FAIL] Installer failed security check. Url: https://github.com/Jackett/Jackett/releases/download/v0.21.1465/Jackett.Installer.Windows.exe Result: 0x80004005

(Automated response - build 516.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
