### PR TITLE
New version: rhysd.actionlint version 1.6.25

### PR DESCRIPTION
**Pull request by sitiom**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/109924&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
image

**Comment by sitiom** [comment]
False positive? How can this be resolved?

Ping @rhysd

**Review by ItzLevvie — APPROVED** [review]

**Comment by sitiom** [comment]
Not sure, but the `Validation-Defender-Error` label means the binary got flagged by Windows Defender. Maybe you can try to submit it as a false positive here: https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by stephengillie** [comment]
Hi @rhysd,

Here's some more information on our validation process: https://learn.microsoft.com/en-us/windows/package-manager/package/repository#validation-process

Here is my manual validation log from the last run: [rhysd.actionlint.x86.1.6.25.log](https://github.com/microsoft/winget-pkgs/files/11790532/rhysd.actionlint.x86.1.6.25.log)
> 11:18:20 AM: 2023-06-16 11:18:20.471 [FAIL] Installer failed security check. Url: https://github.com/rhysd/actionlint/releases/download/v1.6.25/actionlint_1.6.25_windows_386.zip Result: 0x80004005

The installer ZIP failed a Defender scan on download and couldn't be installed by WinGet. Please scan the zipping system for viruses and resubmit, along with updating the hash, as removing the virus should change the hash too.

**Comment by sitiom** [comment]
A manual scan from Windows Defender doesn't seem to trigger anything.
image

**Comment by rhysd** [comment]
@sitiom Thank you for the information and manual scan result.

@stephengillie The binary is built on GitHub-hosted runner of GitHub Actions using [GoReleaser action](https://github.com/goreleaser/goreleaser-action).

Workflow which built the v1.6.25 binary: https://github.com/rhysd/actionlint/actions/runs/5280674972/jobs/9553137042

I never build release binaries on my local. The job automatically runs when new version tag is added so it is hard to rebuild binaries.

**Comment by stephengillie** [comment]
Hi @rhysd,

Apparently it was a false positive, as both the Automated and Manual validation pipelines have passed a Defender scan. Sorry for any concern caused.

**Pull request merged**
