### PR TITLE
Add .netframework 4.8

### PR DESCRIPTION
**Pull request by Reset816**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/544)

### CODE REVIEW

**Comment by Reset12138** [comment]
I wonder why the bot doesn't appear

**Comment by Reset12138** [comment]
> I wonder why the bot doesn't appear

@KevinLaMS @denelon 
This this normal? Or just things goes wrong?

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
