### PR TITLE
New package: CitraEmu.Citra version 2.0

### PR DESCRIPTION
**Pull request by noraa-junker**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/123272)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Aaron-Junker,

This package failed to install in a Windows 10 VM: 
> 2023-10-20 19:43:07.829 [CLI ] ShellExecute installer failed: 1 

When run manually, the installer had an error: 
image

I'm not sure why the Automatic Validation pipeline didn't have the same output.

**Comment by Aaron-Junker** [comment]
Hi @stephengillie 

It does work on my machine, may have been a temporary outage. Can you trigger the pipeline again?

**Comment by Aaron-Junker** [comment]
> Hi @stephengillie
> 
> It does work on my machine, may have been a temporary outage. Can you try to test again?

**Comment by stephengillie** [comment]
Unfortunately, the error is unchanged.
image

This is using my home Internet connection so might be unavailable on at least 1 ISP in the USA.

**Comment by Aaron-Junker** [comment]
> Unfortunately, the error is unchanged.
> image
> 
> This is using my home Internet connection so might be unavailable on at least 1 ISP in the USA. 

@stephengillie I googled the error and it seems it can be caused by wrong defined firewall or DNS settings.

**Comment by stephengillie** [comment]
The current settings allow full Internet access. Does this package require using a specific DNS server? This would be beyond the capabilities of the WinGet package manager.

**Comment by Aaron-Junker** [comment]
> The current settings allow full Internet access. Does this package require using a specific DNS server? This would be beyond the capabilities of the WinGet package manager. 

No. But I mean the validation has no problems and people around the world are using it, so it has to be a problem on your side, although I don't know exactly what🤷

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
