### PR TITLE
New package: F3d.F3d version 2.5.0

### PR DESCRIPTION
**Pull request by jo-chemla**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/172695)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files\F3D\bin\f3d.exe returned exit code: -1073741819

Automated error analysis suggests -1073741819 may mean Converted to hexadecimal (C0000005) possibly [Access Violation](https://learn.microsoft.com/en-us/shows/inside/access-violation-c0000005-execute). (This is occasionally seen in PRs despite the install otherwise being successful. Should it be added as an `InstallerSuccessCode` or similar here?)

(Automated response - build 895.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> Fault bucket 1966890590570331726, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0
> 
> Problem signature:
P1: f3d.exe
P2: 0.0.0.0
P3: 66831e0d
P4: StackHash_ac46
P5: 0.0.0.0
P6: 00000000
P7: PCH_17_FROM_ntdll+0x000000000009D8C4
P8: c0000005
P9: 0000000000000008
P10: 
> 
> Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER67B9.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER67E9.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER67FA.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6802.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER6813.tmp.txt
> 
> These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_f3d.exe_492951c7762b6c3f198b952a96f7fabf09bc0_60c9750a_d934bed5-7408-41e4-9338-995ad128de69
> 
> Analysis symbol: 
Rechecking for solution: 0
Report Id: 1b273eac-a4d8-483d-98ae-3edbd41ac8c0
Report Status: 268435456
Hashed bucket: b1d75aec752de46b8b4bcc923300be4e
Cab Guid: 0
> 
> Faulting application name: f3d.exe, version: 0.0.0.0, time stamp: 0x66831e0d
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0000000000000000
Faulting process id: 0x27a8
Faulting application start time: 0x01db0457694e0eae
Faulting application path: C:\Program Files\F3D\bin\f3d.exe
Faulting module path: unknown
Report Id: 1b273eac-a4d8-483d-98ae-3edbd41ac8c0
Faulting package full name: 
Faulting package-relative application ID: 


Edit: When launched, the application would open a small window, then immediately close.
image

**Comment by stephengillie** [comment]
Hi @jo-chemla,

It seems like the package might either depend on OpenGL, or maybe have a dependency on another software package. What are your thoughts?

**Comment by jo-chemla** [comment]
The software indeed relies heavily on OpenGL from what I understand. Are these dependencies not installed by default via the winget installer current package manifest? In my case I had nothing more to do to get the installer run without errors - also tried uninstalling and reinstalling `winget install -m C:\Dev\winget-pkgs\manifests\f\F3d\F3d\2.5.0` and it did end up in a correct installation. 

Otherwise, should this dependency be added to the package manifest? Could not find such examples on the winget-pkgs repo searching for dependency or opengl.

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/12906
- https://github.com/microsoft/winget-pkgs/issues/107639

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
