### PR TITLE
New version: PhapDieuDuong.ExifGlass version 1.5.0.0

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/143799)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\ExifGlass.exe returned exit code: -532462766

(Automated response - build 869.)

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

> This PR's version number 1.5.0.0 has 4 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version 1.4.1, which has 3 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 870)

**Comment by Exorcism0666** [comment]
> Hi @Exorcism0666,
> 
> > This PR's version number 1.5.0.0 has 4 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version 1.4.1, which has 3 parameters.
> 
> Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)
> 
> (Automated response - build 870)

@stephengillie 
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
