### PR TITLE
New version: KDE.Okular version 22.12.2 [FP-O]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | Okular | Okular    |
| Version     | 22.12.2     | 22.12.2 |
| Publisher   | KDE e.V.   | KDE e.V.      |
| ProductCode |           | Okular    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [5815](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/4106016575>)

### CODE REVIEW

**Review by russellbanks — DISMISSED** [review]

**Review by stephengillie — APPROVED** [review]

**Comment by Croydon** [comment]
@vedantmgoyal2009 The download is unavailable. No idea if it is temporary or permanent. Any ideas?

**Comment by aldeano** [comment]
The installer url in the manifest is this
`InstallerUrl: https://binary-factory.kde.org/view/Windows%2064-bit/job/Okular_Release_win64/1286/artifact/okular-22.12.2-**1286**-windows-cl-msvc2019-x86_64.exe`

But in binary factory the up-to-date url is
`https://binary-factory.kde.org/view/Windows%2064-bit/job/Okular_Release_win64/lastSuccessfulBuild/artifact/okular-22.12.2-1294-windows-cl-msvc2019-x86_64.exe`

Note the difference between both, 1286 in installer and 1294 in binary factory.

**Comment by Croydon** [comment]
So, those are just Nightly builds and they are probably deleting them every now and then...? If there is no permanent available download this is just bad

**Comment by Croydon** [comment]
Thanks to help on their Matrix channel I found a permanently available release: https://download.kde.org/stable/release-service/22.12.1/windows/

Discoverable via https://apps.kde.org/de/okular/ (but not via https://okular.kde.org/)

**Pull request merged**
