### PR TITLE
New version: Nushell.Nushell version 0.77.0

### PR DESCRIPTION
**Pull request by fdncred**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/99543)

### CODE REVIEW

**Comment by fdncred** [comment]
With our last release, winget-validation failed because our software (nu.exe) prompts the user on first launch. Can someone please check to see if that's what is failing again? I've personally tested the msi and had no issues installing this new version. Also, going forward, how do we make this happen automatically, so winget-validation doesn't fail every-single-time?

**Comment by fdncred** [comment]
Hi @stephengillie, 
Thanks for looking into this.  Strange I don't get that dialog when I run the msi. Maybe it's a UAC setting? Either way, I'm guessing this means we need to sign our msi somehow. We've never needed to sign it in the past. Is this a new requirement of winget that we missed?

**Comment by stephengillie** [comment]
> Hi @stephengillie, Thanks for looking into this. Strange I don't get that dialog when I run the msi. Maybe it's a UAC setting? Either way, I'm guessing this means we need to sign our msi somehow. We've never needed to sign it in the past. Is this a new requirement of winget that we missed?

Retrying this on a Windows 11 VM, I'm not seeing the warning and it installs normally.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
