### PR TITLE
Update: qBittorrent.qBittorrent version 4.3.6

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/22431)

### CODE REVIEW

**Review by jedieaston — CHANGES_REQUESTED** [review]
This is an issue with Windows Defender: https://github.com/qbittorrent/qBittorrent/issues/14489. I guess we're blocked on qBittorrent updates until they fix it.

Edit: It looks like it may have been corrected now? Defender isn't triggering for it on my machine. Maybe try the close-reopen dance and see if it works.

**Comment by OfficialEsco** [comment]
Ahh @jedieaston you haven't been in this thread https://github.com/microsoft/winget-pkgs/pull/19135, we have been troubleshooting it for a month and it seems to be on and off if it triggers...

**Comment by vedantmgoyal2009** [comment]
@msftbot it is stuck at windows defender validation.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://docs.microsoft.com/en-us/windows/package-manager/package/binary-validation-errors#what-to-do-if-you-see-the-binary-validation-error-label

You can set this PR as a draft or close it if it can't be solved.

According to the docs, the validation error cannot be bypassed as you'll need to contact the application developer about this.

**Comment by OfficialEsco** [comment]
.

**Comment by vedantmgoyal2009** [comment]
Blocked by SmartScreen.

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
