### PR TITLE
New version: GiulioSorrentino.CBriscola.Avalonia version 0.8.0

### PR DESCRIPTION
**Pull request by GiulianoSpaghetti**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/144092)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-12 17:37:36.843 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFAFD16C11F: (caller: 00007FFAFCEF8D6F) LogHr(1) tid(56c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFAFD072B08: (caller: 00007FFAFD11BC20) Exception(1) tid(56c) 8A15005E ] 
> 2024-03-12 17:37:36.843 [REPO] Failed to open available source: msstore
> 2024-03-12 17:37:40.347 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFAFD072B08: (caller: 00007FFAFD11BC20) Exception(1) tid(56c) 8A15005E 
> 2024-03-12 17:37:51.124 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFAFBE2C11F: (caller: 00007FFAFBBB8D6F) LogHr(1) tid(8d8) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFAFBD32B08: (caller: 00007FFAFBDDBC20) Exception(1) tid(8d8) 8A15005E ] 
> 2024-03-12 17:37:51.124 [REPO] Failed to open available source: msstore
> 2024-03-12 17:39:49.793 [FAIL] Installer failed security check. Url: https://github.com/numerunix/CBriscola.Avalonia/releases/download/0.8.0/CBriscola.Avalonia-0.8.0-amd64.msi Result: 0x80004005
> MSI (s) (64:C4) [17:38:13:620]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1)
> MSI (s) (64:C4) [17:38:16:292]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,)
> Property(S): ErrorDialog = ErrorDlg
> MSI (s) (64:E4) [17:38:32:807]: An error occured while refreshing environment variables updated during the installation of ''. Some users logged on to the machine may not see these changes until they log off and then log back on.

(Automated response - build 870.)

**Comment by numerunix** [comment]
it's the smart screen

**Comment by numerunix** [comment]
I'm sorry, i for error deleted the msi from github, i recompiled it, the hash has changed.

Thanks.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
