### PR TITLE
Remove old version of JanDeDobbeleer.OhMyPosh

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
null

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
image

**Comment by vedantmgoyal2009** [comment]
Should I close my PR or not?

**Comment by ItzLevvie** [comment]
For now yes; and it's a duplicate of https://github.com/microsoft/winget-pkgs/pull/19798.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Check latest comments.

**Comment by vedantmgoyal2009** [comment]
Ok

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
