### PR TITLE
Datto.CloudContinuityAgent version 3.0.15.2

### PR DESCRIPTION
**Pull request by ffrodriguez**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/86328)

### CODE REVIEW

**Comment by ffrodriguez** [comment]
@microsoft-github-policy-service agree [company="Datto Inc."]

**Comment by ffrodriguez** [comment]
@microsoft-github-policy-service agree company="Datto Inc."

**Comment by stephengillie** [comment]
@ffrodriguez The installer stops at about 66%, while processing PlatformVerifier.x64.exe. Does the installer have a dependency?

**Comment by ffrodriguez** [comment]
> @ffrodriguez The installer stops at about 66%, while processing PlatformVerifier.x64.exe. Does the installer have a dependency?

It does but the bundle should be handling it.
PlatformVerifier.x64.exe depends on VC++ runtime and dlls in the code all of which should be installed before the verifier is run.

**Comment by ffrodriguez** [comment]
@stephengillie just wanted to follow up on whether I can provide any additional information to help with the approval.

**Comment by stephengillie** [comment]
Hi @ffrodriguez,

The installer forces a reboot, and unfortunately, we do not accept packages that reboot during installation. The attended installer ends with 2 buttons: "Reboot" and "Cancel". Unattended install initiates a reboot at the end of install. Is there a flag or other way to have this package install without rebooting? 
Additionally, the installer hash provided in this PR no longer matches the downloaded installer's hash. If the provided hash does not match the installer's hash, the install will be aborted. This package URI looks like it might be a main download location that could be frequently updated. Is there a URI with versioned paths, or other download location that might retain the same hash long-term?

**Comment by ffrodriguez** [comment]
@stephengillie 

> The installer forces a reboot, and unfortunately, we do not accept packages that reboot during installation. The attended installer ends with 2 buttons: "Reboot" and "Cancel". Unattended install initiates a reboot at the end of install. Is there a flag or other way to have this package install without rebooting? 

Yes, the installer supports `/norestart` for the unattended install.

> Additionally, the installer hash provided in this PR no longer matches the downloaded installer's hash. If the provided hash does not match the installer's hash, the install will be aborted. This package URI looks like it might be a main download location that could be frequently updated. 

Yeah, after releasing it to a an initial target, we found an issue that warranted rolling back making this specific installer.

> Is there a URI with versioned paths, or other download location that might retain the same hash long-term?

We do, but, sans this issue where we had to rollback this specific 3.0.15.2 version, the goal was get this installer's manifest approved and then use wingetcreate in a CI/CD pipeline to simply submit a version update as new versions are rolled out, with the intention of having winget just have the "latest version".

That said, is the above workflow not supported by/for winget?

**Comment by stephengillie** [comment]
@ffrodriguez

> Yes, the installer supports `/norestart` for the unattended install.

Validation was originally blocked by the mandatory restart. Please add this install parameter to the manifest for validation to proceed.

> Yeah, after releasing it to a an initial target, we found an issue that warranted rolling back making this specific installer.

Validation was subsequently blocked by the hash mismatch. Please also update the hash in the manifest for validation to proceed.

> We do, but, sans this issue where we had to rollback this specific 3.0.15.2 version, the goal was get this installer's manifest approved and then use wingetcreate in a CI/CD pipeline to simply submit a version update as new versions are rolled out, with the intention of having winget just have the "latest version".

This is an ideal workflow in general. The only concern is that if the package at this URI changes, such as being replaced with an updated version, then this would present a hash mismatch again and Winget would no longer install this version. The hash is a security feature, to ensure that the installer being downloaded and executed is the same package as originally submitted.

**Comment by ItzLevvie** [comment]
Close with reason: Stale PR;

**Pull request closed without merging**
