### PR TITLE
New package: Microsoft.PCManager.Beta version 3.8.10.0

### PR DESCRIPTION
**Pull request by schembriaiden**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/151092)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 877.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

Is an installer switch avaiable to bypass this and complete the install silently?

**Comment by vikingnope** [comment]
With my last commit it should install bypassing that popup

**Comment by stephengillie** [comment]
Hi @vikingnope,

I wasn't able to navigate from the `PublisherUrl` to the `InstallerUrl`. Is there another URL that has this link?

**Comment by vikingnope** [comment]
@stephengillie, it should be updated now

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
