### PR TITLE
New version: Microsoft.PowerShell.Preview version 7.5.0-preview.1

### PR DESCRIPTION
**Pull request by strawhat-dev**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/139282)

### CODE REVIEW

**Comment by strawhat-dev** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 751.)

**Comment by stephengillie** [comment]
Hi @anamnavi,

Do you approve of these changes?

**Comment by anamnavi** [comment]
@stephengillie no don't accept this PR. the package version is not correct. I'll open up a PR for this version.

**Comment by stephengillie** [comment]
Close with reason: > @ stephengillie no don't accept this PR. the package version is not correct. I'll open up a PR for this version.;

**Pull request closed without merging**
