### PR TITLE
New version: AuraSide.Mantle version 0.1.0.5

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136035)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Trenly,

> This PR's version number 1.0.5 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 0.1.0.4, which has 4 parameters.

Is this intentional?

(Automated response - build 643)

**Comment by Trenly** [comment]
Yes

**Comment by stephengillie** [comment]
I'm going to start an exception file for these. Let me know if this or any other should be added to it.

**Review by stephengillie — APPROVED** [review]

**Comment by Trenly** [comment]
> I'm going to start an exception file for these. Let me know if this or any other should be added to it.

I don’t think its really that there are exeptions, since it is true that these versions don’t follow the same pattern as previous versions. It's moreso that the version written to control panel has changed and also doesn’t follow the pattern. I don’t know if it's possible (easy) for you to capture the ARP entries from the logs or your own installs, but genrally I would say that if the version matches control panel, changing the number of parameters is intentional

**Pull request merged**
