### PR TITLE
New version: DuckStudio.ChineseGit version v2.7

### PR DESCRIPTION
**Pull request by DuckDuckStudio**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue? --No

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
```
[Powered by 虚空终端] PS D:\...\winget-pkgs> winget validate --manifest D:\...\winget-pkgs\manifests\d\DuckStudio\ChineseGit\2.7
清单验证成功。
```
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
```
[Powered by 虚空终端] PS D:\...\winget-pkgs> winget install --manifest manifests\d\DuckStudio\ChineseGit\2.7
已找到 中文Git [DuckStudio.ChineseGit] 版本 2.7
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://github.com/DuckDuckStudio/Chinese_git/releases/download/v2.7/Chinese_git_Setup_v2.7.exe
  ██████████████████████████████  9.18 MB / 9.18 MB
已成功验证安装程序哈希
正在启动程序包安装...
--> Need: UAC
已成功安装
[Powered by 虚空终端] PS C:\...> 中文git 版本
中文Git by 鸭鸭「カモ」
版本：v2.7-pack
安装在: C:\Program Files (x86)\Chinese_git\中文git.exe
git version 2.42.0.windows.1
```
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

> Edit: No validation Dependencies.

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/160675)

### CODE REVIEW

**Comment by DuckDuckStudio** [comment]
CC @Luna-Grace

**Comment by DuckDuckStudio** [comment]
Is that normal?
image

**Review by Luna-Grace — APPROVED** [review]

**Comment by DuckDuckStudio** [comment]
> [!NOTE]
> Main program: 中文git.exe

**Comment by stephengillie** [comment]
Sorry - the https://github.com/microsoft/winget-pkgs/labels/Internal-Error-Dynamic-Scan label occurs consistently to `Git` packages. I'll need to manually validate this.

**Comment by stephengillie** [comment]
Manual Validation ended with:
> Trojan:Win32/Phonzy.B!ml

(Automated response - build 886.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> Trojan:Win32/Phonzy.B!ml

(Automated response - build 886.)

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Comment by DuckDuckStudio** [comment]
> I think I might have to submit it for validation again...
Update validation progress:
image

**Comment by DuckDuckStudio** [comment]
I will try to get the _Azure Pipelines_ running again...

**Comment by DuckDuckStudio** [comment]
@stephengillie Can you retry this?

**Comment by DuckDuckStudio** [comment]
> Sorry - the [ Internal-Error-Dynamic-Scan](https://github.com/microsoft/winget-pkgs/labels/Internal-Error-Dynamic-Scan) The test for Dynamic Scanning in the Installation Validation failed. label occurs consistently to `Git` packages. I'll need to manually validate this.

Hopefully this issue will not recur.

**Comment by DuckDuckStudio** [comment]
*Azure Pipelines* seems to have taken more than 3 hours...

**Comment by DuckDuckStudio** [comment]
It seem need to manually validate...

**Comment by stephengillie** [comment]
Automatic Validation ended with:
2024-07-13 07:12:09.277 [FAIL] D:\a\1\s\src\AppInstallerRepositoryCore\IconExtraction.cpp(113)\WinGetUtil.dll!00007FFA4356E106: (caller: 00007FFA4356EB22) Exception(1) tid(11a4) 800700E1 Operation did not complete successfully because the file contains a virus or potentially unwanted software.
> 2024-07-13 07:12:09.288 [FAIL] D:\a\1\s\src\AppInstallerRepositoryCore\IconExtraction.cpp(212)\WinGetUtil.dll!00007FFA436BF6B5: (caller: 00007FFA4356EB22) LogHr(1) tid(11a4) 800700E1 Operation did not complete successfully because the file contains a virus or potentially unwanted software.
>     Msg:[D:\a\1\s\src\AppInstallerRepositoryCore\IconExtraction.cpp(113)\WinGetUtil.dll!00007FFA4356E106: (caller: 00007FFA4356EB22) Exception(1) tid(11a4) 800700E1 Operation did not complete successfully because the file contains a virus or potentially unwanted software.
> 
> Executable C:\Program Files\Git\bin\git.exe returned exit code: 1
> Executable C:\Program Files\Git\bin\bash.exe returned exit code: -1
> Executable C:\Program Files\Git\bin\sh.exe returned exit code: -1
> Executable C:\Program Files\Git\cmd\git-gui.exe returned exit code: 259
> Executable C:\Program Files\Git\cmd\git-receive-pack.exe returned exit code: 129
> Executable C:\Program Files\Git\cmd\git-upload-pack.exe returned exit code: 129
> Executable C:\Program Files\Git\cmd\git.exe returned exit code: 1
> Executable C:\Program Files\Git\cmd\gitk.exe returned exit code: 259
> Executable C:\Program Files\Git\cmd\scalar.exe returned exit code: 129
> Executable C:\Program Files\Git\cmd\tig.exe returned exit code: 1
> Executable C:\Program Files\Git\git-bash.exe returned exit code: -1
> Executable C:\Program Files\Git\git-cmd.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\bin\WhoUses.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\bin\adig.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\bin\ahost.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\bin\blocked-file-util.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\bin\brotli.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\bin\bunzip2.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\bin\bzcat.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\bin\bzip2.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\bin\bzip2recover.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\bin\create-shortcut.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\bin\curl.exe returned exit code: 2
> Executable C:\Program Files\Git\mingw64\bin\envsubst.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\bin\gettext.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\bin\git-askpass.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\bin\git-askyesno.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\bin\git-credential-helper-selector.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\bin\git-credential-manager.exe returned exit code: -532462766
> Executable C:\Program Files\Git\mingw64\bin\git-receive-pack.exe returned exit code: 129
> Executable C:\Program Files\Git\mingw64\bin\git-upload-archive.exe returned exit code: 128
> Executable C:\Program Files\Git\mingw64\bin\git-upload-pack.exe returned exit code: 129
> Executable C:\Program Files\Git\mingw64\bin\git.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\bin\lzmadec.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\bin\lzmainfo.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\bin\odt2txt.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\bin\p11-kit.exe returned exit code: 2
> Executable C:\Program Files\Git\mingw64\bin\pkcs1-conv.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\bin\psl.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\bin\scalar.exe returned exit code: 129
> Executable C:\Program Files\Git\mingw64\bin\sexp-conv.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\bin\tclsh.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\bin\tclsh86.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\bin\trust.exe returned exit code: 2
> Executable C:\Program Files\Git\mingw64\bin\unxz.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\bin\wish.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\bin\wish86.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\bin\x86_64-w64-mingw32-agrep.exe returned exit code: 2
> Executable C:\Program Files\Git\mingw64\bin\xmlwf.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\bin\xz.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\bin\xzcat.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\bin\xzdec.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\libexec\git-core\git-credential-wincred.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\libexec\git-core\git-daemon.exe returned exit code: -1
> Executable C:\Program Files\Git\mingw64\libexec\git-core\git-http-fetch.exe returned exit code: 129
> Executable C:\Program Files\Git\mingw64\libexec\git-core\git-http-push.exe returned exit code: 129
> Executable C:\Program Files\Git\mingw64\libexec\git-core\git-imap-send.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\libexec\git-core\git-remote-ftp.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\libexec\git-core\git-remote-ftps.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\libexec\git-core\git-remote-http.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\libexec\git-core\git-remote-https.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\libexec\git-core\git.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\libexec\git-core\headless-git.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\libexec\git-core\scalar.exe returned exit code: 129
> Executable C:\Program Files\Git\mingw64\libexec\p11-kit\p11-kit-remote.exe returned exit code: -1073741515
> Executable C:\Program Files\Git\mingw64\libexec\p11-kit\p11-kit-server.exe returned exit code: -1073741515
> Executable C:\Program Files\Git\mingw64\share\git\compat-bash.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\share\git\edit-git-bash.exe returned exit code: 1
> Executable C:\Program Files\Git\mingw64\share\git\git-wrapper.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\[.exe returned exit code: 2
> Executable C:\Program Files\Git\usr\bin\awk.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\b2sum.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\base32.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\base64.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\basename.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\basenc.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\bash.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\bunzip2.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\bzcat.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\bzip2.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\bzip2recover.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\captoinfo.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\cat.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\chattr.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\chcon.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\chgrp.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\chmod.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\chown.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\chroot.exe returned exit code: 125
> Executable C:\Program Files\Git\usr\bin\cksum.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\cmp.exe returned exit code: 2
> Executable C:\Program Files\Git\usr\bin\comm.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\cp.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\csplit.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\cut.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\cygcheck.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\cygpath.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\cygwin-console-helper.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\d2u.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\dd.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\diff.exe returned exit code: 2
> Executable C:\Program Files\Git\usr\bin\diff3.exe returned exit code: 2
> Executable C:\Program Files\Git\usr\bin\dircolors.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\dirmngr-client.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\dirmngr.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\dirname.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\dos2unix.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\du.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\dumpsexp.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\ex.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\expand.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\expr.exe returned exit code: 2
> Executable C:\Program Files\Git\usr\bin\factor.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\false.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\file.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\fmt.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\fold.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\funzip.exe returned exit code: 3
> Executable C:\Program Files\Git\usr\bin\gawk-5.0.0.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\gawk.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\gencat.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\getconf.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\getfacl.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\gkill.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\gpg-agent.exe returned exit code: 2
> Executable C:\Program Files\Git\usr\bin\gpg-card.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\gpg-connect-agent.exe returned exit code: -1
> Checking if C:\Program Files\Git\usr\bin\gpg-error.exe executable file can be started.
> Launching executable file: C:\Program Files\Git\usr\bin\gpg-error.exe
> Executable C:\Program Files\Git\usr\bin\gpg-error.exe ran for less than 10 seconds: True
> Executable C:\Program Files\Git\usr\bin\gpg-error.exe returned exit code: 2
> Executable C:\Program Files\Git\usr\bin\gpg-wks-client.exe returned exit code: 2
> Executable C:\Program Files\Git\usr\bin\gpg-wks-server.exe returned exit code: 2
> Executable C:\Program Files\Git\usr\bin\gpg.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\gpgparsemail.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\gpgscm.exe returned exit code: 2
> Executable C:\Program Files\Git\usr\bin\gpgsm.exe returned exit code: 2
> Executable C:\Program Files\Git\usr\bin\gpgsplit.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\gpgtar.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\gpgv.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\grep.exe returned exit code: 2
> Executable C:\Program Files\Git\usr\bin\groups.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\gzip.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\head.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\hmac256.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\iconv.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\infotocap.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\install.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\join.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\kbxutil.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\kill.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\ldd.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\ldh.exe returned exit code: 256
> Executable C:\Program Files\Git\usr\bin\lesskey.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\link.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\ln.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\locate.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\lsattr.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\mac2unix.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\md5sum.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\minidumper.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\mkdir.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\mkfifo.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\mknod.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\mpicalc.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\mv.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\nano.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\nettle-hash.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\nettle-lfib-stream.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\nettle-pbkdf2.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\nl.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\nohup.exe returned exit code: 125
> Executable C:\Program Files\Git\usr\bin\numfmt.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\od.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\p11-kit.exe returned exit code: 2
> Executable C:\Program Files\Git\usr\bin\passwd.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\paste.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\patch.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\pathchk.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\perl.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\perl5.38.2.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\pinentry-w32.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\pinentry.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\pkcs1-conv.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\pldd.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\pr.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\printf.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\profiler.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\psl.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\ptx.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\readlink.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\realpath.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\regtool.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\rm.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\rmdir.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\rnano.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\runcon.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\rview.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\rvim.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\scp.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\sdiff.exe returned exit code: 2
> Executable C:\Program Files\Git\usr\bin\sed.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\seq.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\setfacl.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\sexp-conv.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\sftp.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\sh.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\sha1sum.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\sha224sum.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\sha256sum.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\sha384sum.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\sha512sum.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\shred.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\shuf.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\sleep.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\sort.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\split.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\ssh-add.exe returned exit code: 2
> Executable C:\Program Files\Git\usr\bin\ssh-keygen.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\ssh-keyscan.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\ssh.exe returned exit code: 255
> Executable C:\Program Files\Git\usr\bin\sshd.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\ssp.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\stat.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\stdbuf.exe returned exit code: 125
> Executable C:\Program Files\Git\usr\bin\strace.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\sum.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\tac.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\tail.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\tar.exe returned exit code: 2
> Executable C:\Program Files\Git\usr\bin\tee.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\test.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\tic.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\tig.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\timeout.exe returned exit code: 125
> Executable C:\Program Files\Git\usr\bin\touch.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\tput.exe returned exit code: 2
> Executable C:\Program Files\Git\usr\bin\tr.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\truncate.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\trust.exe returned exit code: 2
> Executable C:\Program Files\Git\usr\bin\tsort.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\u2d.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\umount.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\unexpand.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\uniq.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\unix2dos.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\unix2mac.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\unlink.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\unzipsfx.exe returned exit code: 2
> Executable C:\Program Files\Git\usr\bin\vdir.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\view.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\vim.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\vimdiff.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\watchgnupg.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\wc.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\which.exe returned exit code: 255
> Executable C:\Program Files\Git\usr\bin\winpty-agent.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\winpty-debugserver.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\winpty.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\bin\xargs.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\xxd.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\yat2m.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\yes.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\lib\awk\grcat.exe returned exit code: -1073741515
> Executable C:\Program Files\Git\usr\lib\awk\pwcat.exe returned exit code: -1073741515
> Executable C:\Program Files\Git\usr\lib\gnupg\gpg-auth.exe returned exit code: -1073741515
> Executable C:\Program Files\Git\usr\lib\gnupg\gpg-check-pattern.exe returned exit code: -1073741515
> Executable C:\Program Files\Git\usr\lib\gnupg\gpg-pair-tool.exe returned exit code: -1073741515
> Executable C:\Program Files\Git\usr\lib\gnupg\gpg-preset-passphrase.exe returned exit code: -1073741515
> Executable C:\Program Files\Git\usr\lib\gnupg\gpg-protect-tool.exe returned exit code: -1073741515
> Executable C:\Program Files\Git\usr\lib\gnupg\keyboxd.exe returned exit code: -1073741515
> Executable C:\Program Files\Git\usr\lib\gnupg\scdaemon.exe returned exit code: -1073741515
> Executable C:\Program Files\Git\usr\lib\ssh\sftp-server.exe returned exit code: -1073741515
> Executable C:\Program Files\Git\usr\lib\ssh\ssh-keysign.exe returned exit code: -1073741515
> Executable C:\Program Files\Git\usr\lib\ssh\ssh-pkcs11-helper.exe returned exit code: -1073741515
> Executable C:\Program Files\Git\usr\lib\ssh\ssh-sk-helper.exe returned exit code: -1073741515
> Executable C:\Program Files\Git\usr\lib\tar\rmt.exe returned exit code: -1073741515
> Executable C:\Program Files\Git\usr\libexec\frcode.exe returned exit code: -1073741515
> Executable C:\Program Files\Git\usr\libexec\getprocaddr32.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\libexec\getprocaddr64.exe returned exit code: 1
> Executable C:\Program Files\Git\usr\libexec\p11-kit\p11-kit-remote.exe returned exit code: -1073741515
> Executable C:\Program Files\Git\usr\libexec\p11-kit\p11-kit-server.exe returned exit code: -1073741515
> Executable C:\Program Files\Git\usr\bin\dash.exe returned exit code: -1
> Executable C:\Program Files\Git\usr\bin\getopt.exe returned exit code: 2
> Executable C:\Program Files\Git\mingw64\bin\pdftotext.exe returned exit code: 99
> Executable C:\Program Files\Git\usr\bin\column.exe returned exit code: -1
> Executable C:\Program Files (x86)\Chinese_git\中文git更新程序.exe returned exit code: 2

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

Automated error analysis suggests -532462766 may mean EXCEPTION_COMPLUS (Unhandled Exception)

(Automated response - build 886.)

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
