### PR TITLE
New package: BRL-CAD.brlcad version 7.36.0

### LINKED ISSUE #113350: [Package Request]: brlcad
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/BRL-CAD/brlcad/releases/tag/rel-7-36-0
Publisher: BRL-CAD
Package Name: brl-cad or brlcad
Description: BRL-CAD is a powerful cross-platform open source combinatorial solid modeling system 
Package Version: 7.36.0
Installer URL: 
* https://github.com/BRL-CAD/brlcad/releases/download/rel-7-36-0/BRL-CAD_7.36.0_win64.exe
* https://github.com/BRL-CAD/brlcad/releases/download/rel-7-36-0/BRL-CAD_7.36.0_win64.msi  
Changelog: https://raw.githubusercontent.com/BRL-CAD/brlcad/main/NEWS

### PR DESCRIPTION
**Pull request by Dragon1573**
## Description

- Resolve https://github.com/microsoft/winget-pkgs/issues/113350

## Checks

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/129009)

### CODE REVIEW

**Comment by Dragon1573** [comment]
@stephengillie - Could you please help investigate the problem of https://github.com/microsoft/winget-pkgs/labels/Error-Analysis-Timeout ? This problem has encountered for 4 times. 😕

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 12/7/2023 12:12:33 PM
Installer Verification Analysis Context Information: 
The orchestrator function 'InstallerOrchestrator' failed: "The orchestrator function 'ESRPOrchestrator' failed: "Exception of type 'Microsoft.WinGetSvc.WinGet.ESRP.Common.WinGetESRPTimeoutException' was thrown.". See the function execution logs for additional details.". See the function execution logs for additional details.
The orchestrator function 'InstallerOrchestrator' failed: "The orchestrator function 'ESRPOrchestrator' failed: "Exception of type 'Microsoft.WinGetSvc.WinGet.ESRP.Common.WinGetESRPTimeoutException' was thrown.". See the function execution logs for additional details.". See the function execution logs for additional details.

**Comment by Trenly** [comment]
@denelon for Validation Pipeline engineer

**Comment by denelon** [comment]
How long does this package typically take to perform an install?

**Comment by denelon** [comment]
I assigned @stephengillie to coordinate with a validation engineer to look at this one.

**Review by stephengillie — APPROVED** [review]

**Comment by luzpaz** [comment]
Heads-up 7.38.0 is latest stable: https://github.com/BRL-CAD/brlcad/releases/tag/rel-7-38-0

**Pull request merged**
