### PR TITLE
New version: VSCodium.VSCodium version 1.60.1

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
﻿- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/27709)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by vedantmgoyal2009** [comment]
> Hello @wingetbot!
> 
> Because this pull request has the `Validation-Completed` label, I will be glad to assist with helping to merge this pull request once all check-in policies pass.
> 
> ##### p.s. you can customize the way I help with merging this pull request, such as holding this pull request until a specific person approves. Simply @mention me (`@msftbot`) and give me an instruction to get started! Learn more [here](https://github.com/microsoft/fluentui/wiki/Advanced-auto-merge).

@msftbot make sure @ItzLevvie gets to approve

**Comment by vedantmgoyal2009** [comment]
@denelon why this does not work?

**Comment by denelon** [comment]
@vedantmgoyal2009 some of the messages from @msftbot aren't configurable yet. We have disabled much of the functionality as it interferes with our other pipeline instructions. I've got an ask to the team maintaining the bot to be able to customize some of those messages.

**Comment by vedantmgoyal2009** [comment]
@denelon Okay 👍

**Pull request merged**
