### PR TITLE
JanJoneš.ipaSim version 1.0.1.0

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/98647)

### CODE REVIEW

**Comment by upintheairsheep** [comment]
feedback please!

**Comment by stephengillie** [comment]
Validation error:
>  Manifest Error: Failed to process installer. [InstallerUrl] Value: https://github.com/ipasimulator/ipasim/releases/download/v1.0.1/ipasim-build-v1.0.1-2023-01-01.zip

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
I approved this PR in error. The package fails to install with: 
> 2023-03-13 13:37:33.736 [CORE] Deployment operation #0: error 0x800B0109: The root certificate of the signature in the app package or bundle must be trusted.

**Pull request merged**
