### PR TITLE
ppy.osu! version 1.3.3.8

### PR DESCRIPTION
**Pull request by faillock**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14692)

### CODE REVIEW

**Comment by KaranKad** [comment]
It's already available https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/Peppy/Osu!

**Comment by richiesuper** [comment]
> 
> 
> It's already available https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/Peppy/Osu!

ah, sorry... my bad...

**Comment by richiesuper** [comment]
> 
> 
> It's already available https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/Peppy/Osu!

i checked and the one available is the "osu lazer" version... not the "osu stable" version

**Comment by KaranKad** [comment]
I guess stable osu! cannot be installed silently, so currently cannot be added.

**Comment by richiesuper** [comment]
> 
> 
> I guess stable osu! cannot be installed silently, so currently cannot be added.

yeah, seems like it..

**Pull request closed without merging**
