### PR TITLE
New version: Oven-sh.Bun.Baseline version 1.1.4

### PR DESCRIPTION
**Pull request by coolplaylinbot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/149498)

### CODE REVIEW

**Review by mdanish-kh — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @coolplaylinbot,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-04-16 14:34:19.116 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFC3983C11F: (caller: 00007FFC395C8D6F) LogHr(1) tid(1b9c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFC39742B08: (caller: 00007FFC397EBC20) Exception(1) tid(1b9c) 8A15005E ] 
> 2024-04-16 14:34:19.116 [REPO] Failed to open available source: msstore
> 2024-04-16 14:34:27.027 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFC21CAC11F: (caller: 00007FFC21A38D6F) LogHr(1) tid(1c98) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFC21BB2B08: (caller: 00007FFC21C5BC20) Exception(1) tid(1c98) 8A15005E ] 
> 2024-04-16 14:34:27.027 [REPO] Failed to open available source: msstore
> 2024-04-16 14:34:48.459 [FAIL] Installer failed security check. Url: https://github.com/oven-sh/bun/releases/download/bun-v1.1.4/bun-windows-x64-baseline.zip Result: 0x80004005

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Hi @coolplaylinbot,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 877.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-04-17 08:35:14.888 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFEA2E9C11F: (caller: 00007FFEA2C28D6F) LogHr(1) tid(2068) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFEA2DA2B08: (caller: 00007FFEA2E4BC20) Exception(1) tid(2068) 8A15005E ] 
> 2024-04-17 08:35:14.888 [REPO] Failed to open available source: msstore
> 2024-04-17 08:35:22.424 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFE8486C11F: (caller: 00007FFE845F8D6F) LogHr(1) tid(1ac0) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFE84772B08: (caller: 00007FFE8481BC20) Exception(1) tid(1ac0) 8A15005E ] 
> 2024-04-17 08:35:22.424 [REPO] Failed to open available source: msstore
> 2024-04-17 08:35:42.124 [FAIL] Installer failed security check. Url: https://github.com/oven-sh/bun/releases/download/bun-v1.1.4/bun-windows-x64-baseline.zip Result: 0x80004005

(Automated response - build 877.)

**Pull request merged**
