### PR TITLE
Submitting Navigraph.NavigraphHub

### PR DESCRIPTION
**Pull request by kmc00**
- [/ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ /] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ /] This PR only modifies one (1) manifest
- [ /] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ /] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ /] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/106722)

### CODE REVIEW

**Comment by kmc00** [comment]
Review required
Added  Navigraph.NavigraphHub
Thanks

**Comment by stephengillie** [comment]
This package errored when installed in a Windows 11 VM: 
> 2023-05-15 13:01:16.188 [CLI ] ShellExecute installer failed: 3221225477

**Comment by kmc00** [comment]
Don't want to say, it working on my end.
Could be you don't have program that it interacts with.

**Comment by stephengillie** [comment]
> Don't want to say, it working on my end. Could be you don't have program that it interacts with, but is working in Window Sandbox for me - were that program is not present.

Oh - this program interacts with another program? What's the name of that program?

**Comment by kmc00** [comment]
Sorry I didn't put that very well.
The software doesn't depend on another piece of software in order to run but it's a installer that will install to a set location for MSFS. This Application doesn't need to be installed for the software to work. 
    
I've haven't been able to re-produce your issue, could you give me some details on your testing method - I've just followed the steps here: https://learn.microsoft.com/en-us/windows/package-manager/package/repository
I've have tested this on Windows 10 22H2 and Windows 11 22H2 both working as expected.

**Comment by kmc00** [comment]
Closed as new pull request made, with update release of software.

**Pull request closed without merging**
