### PR TITLE
Update: SoftMaker.FreePDF.2022 version 3.0.8

### PR DESCRIPTION
**Pull request by russellbanks**
## Addresses https://github.com/microsoft/winget-pkgs/pull/90549#issuecomment-1336211750

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/90553)

### CODE REVIEW

**Review by mdanish-kh — APPROVED** [review]

**Comment by mdanish-kh** [comment]
I guess the pipelines didn't like the idea 😂

**Comment by borque** [comment]
Hello @mdanish-kh,@russellbanks!
Thanks for discussing all my questions, suggesting corrections and enhancements and implementing them.
I learned something new again with my initial PR: neutral is rather deprecated. Now I wonder -as you do- what is wrong with this corrected version that the pipelines don't like it...

**Comment by russellbanks** [comment]
> Now I wonder -as you do- what is wrong with this corrected version that the pipelines don't like it...

Honestly, no idea. Sometimes the pipelines just have issues with certain PRs so an admin will (probably) add a waiver which just tells the pipelines to ignore the error this once.

**Pull request merged**
