### PR TITLE
New package: Codeium.Windsurf version 1.0.7

### PR DESCRIPTION
**Pull request by nandan-varma**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/196930)

### CODE REVIEW

**Comment by stephengillie** [comment]
Verify:
image
image

**Comment by stephengillie** [comment]
Hi @nandan-varma,

Should the `PackageVersion` be updated from `1.0.7`, to match the Registry's `1.94.0`?

**Comment by nandan-varma** [comment]
> Hi @nandan-varma,
> 
> Should the `PackageVersion` be updated from `1.0.7`, to match the Registry's `1.94.0`?

hey sorry for the late reply, 
about section from the menu bar mentions it's version as 1.0.7 but registry says 1.94.0 (I think it's because this is fork of vscode from that version and registry isn't updated to show that) I think another commit added this with package with 1.94.0 though.

**Comment by stephengillie** [comment]
Close with reason: Duplicate of #198808;

**Pull request closed without merging**
