### PR TITLE
New package: InuInu2022.NodoAme version 0.4.0-beta-2

### PR DESCRIPTION
**Pull request by Exorcism0666**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification.
>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> Faulting application name: NodoAme.exe, version: 0.4.0.0, time stamp: 0xfa20fb26 
> Faulting module name: KERNELBASE.dll, version: 10.0.19041.1202, time stamp: 0xc9db1934 Exception code: 0xe0434352 Fault offset: 0x0000000000034f99 
> Faulting process id: 0x7cc 
> Faulting application start time: 0x01da4295211c8a57 
> Faulting application path: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\InuInu2022.NodoAme__DefaultSource\NodoAme.exe 
> Faulting module path: C:\Windows\System32\KERNELBASE.dll Report Id: a3a90f4c-3c0f-4d8c-8ba2-64283e5b8ef3 
> Faulting package full name:  
> Faulting package-relative application ID:   Application: NodoAme.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.IO.DirectoryNotFoundException    at System.IO.__Error.WinIOError(Int32, System.String)    at System.IO.FileSystemEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].CommonInit()    at System.IO.FileSystemEnumerableIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.String, System.String, System.String, System.IO.SearchOption, System.IO.SearchResultHandler`1<System.__Canon>, Boolean)    at System.IO.Directory.GetFiles(System.String)    at CodingSeb.Localization.Loaders.LocalizationLoader.AddDirectory(System.String)    at NodoAme.App.OnStartup(System.Windows.StartupEventArgs)    at System.Windows.Application.<.ctor>b__1_0(System.Object)    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)    at System.Windows.Threading.DispatcherOperation.InvokeImpl()    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)    at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)    at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)    at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)    at System.Windows.Threading.DispatcherOperation.Invoke()    at System.Windows.Threading.Dispatcher.ProcessQueue()    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)    at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)    at MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)    at System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)    at System.Windows.Application.RunDispatcher(System.Object)    at System.Windows.Application.RunInternal(System.Windows.Window)    at NodoAme.App.Main()  

(Automated response - build 530.)

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

This package installed normally, but didn't run when launched. The above errors were in the Application log.

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

This package installs normally, but doesn't run when lauched.

**Comment by Exorcism0666** [comment]
image

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 2024-01-10 15:53:42.548 [CLI ] Starting: 'C:\Users\User\AppData\Local\Temp\WinGet\Microsoft.DotNet.Framework.DeveloperPack_4.4.8.1\ndp481-devpack-enu.exe' with arguments '/install /passive /norestart' 2024-01-10 15:58:42.013 [CLI ] ShellExecute installer failed: 3010 

(Automated response - build 543.)

**Comment by stephengillie** [comment]
Unfortunately, the dependency `Microsoft.DotNet.Framework.DeveloperPack_4` is requiring reboots, blocking their packages.

**Pull request closed without merging**
