### PR TITLE
Using reported version 2.0.1

### LINKED ISSUE #15782: Update Ottomated.CrewLink Versions
Ottomated.CrewLink is reported with different versions in ARP than what was submitted in the manifest.

### PR DESCRIPTION
**Pull request by Master-Guy**
Using the reported version of 2.0.1 to prevent unwanted behavior of winget.

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15613)

### CODE REVIEW

**Comment by denelon** [comment]
@Master-Guy did you confirm the version reported in Add / Remove Programs? The manifest your PR modifies was built with a tool designed to detect the version from the installer. Additionally, we prefer the multi-file manifest as it is easier to add other localized descriptions.

**Comment by Master-Guy** [comment]
> @Master-Guy did you confirm the version reported in Add / Remove Programs? The manifest your PR modifies was built with a tool designed to detect the version from the installer. Additionally, we prefer the multi-file manifest as it is easier to add other localized descriptions.

@denelon yes I did, which is why I thought it was weird that the versions didn't match up. As for the multi-file manifest: I was unable to upload that, because the bot rejects modifying multiple manifest files in a single PR.

**Review by ItzLevvie — APPROVED** [review]

**Comment by denelon** [comment]
@Master-Guy OK. The challenge with multiple files has to do with how GitHub records a rename as a "delete" and an "add". I think the best way to clean this up is to add the new manifests for the new versions one PR per version. Once they are in, you can delete the old versions. I'll create an Issue for you to reference the PRs against, and I'll link it here.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-pkgs/issues/15782

**Pull request merged**
