### PR TITLE
Move Schrodinger.Pymol 2.5.5 to Schrodinger.PyMOL 2.5.5

### PR DESCRIPTION
**Pull request by SpecterShell**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/190192)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
> fatal: couldn't find remote ref refs/pull/190192/merge
##[error]Git fetch failed with exit code: 128

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Pull request merged**
