### PR TITLE
martinvonz.jj version 0.8.0

### PR DESCRIPTION
**Pull request by sdellysse**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/116802&drop=dogfoodAlpha

### CODE REVIEW

**Comment by sdellysse** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Hi @sdellysse,

This package appears to depend on `Microsoft.VCRedist.2015+.x64`:
image

**Comment by sdellysse** [comment]
@stephengillie I committed your suggestion, thanks!

is there any way I can easily check these sorts of things on my end in the future? Like, is there a minimal vm/container I can spin up to make sure I have these sorts of things sorted before submitting?

**Comment by stephengillie** [comment]
> @stephengillie I committed your suggestion, thanks!
> 
> is there any way I can easily check these sorts of things on my end in the future? Like, is there a minimal vm/container I can spin up to make sure I have these sorts of things sorted before submitting?

Sure - my testing environment is a Windows 10 VM before anything gets installed. This version doesn't yet include the `Microsoft.VCRedist.2015+.x86` or `x64` packages, which are more than 90% of our dependencies. Let me know if I can help with more.

**Comment by sdellysse** [comment]
> > @stephengillie I committed your suggestion, thanks!
> > is there any way I can easily check these sorts of things on my end in the future? Like, is there a minimal vm/container I can spin up to make sure I have these sorts of things sorted before submitting?
> 
> Sure - my testing environment is a Windows 10 VM before anything gets installed. This version doesn't yet include the `Microsoft.VCRedist.2015+.x86` or `x64` packages, which are more than 90% of our dependencies. Let me know if I can help with more.

Apologies if this is a dumb question (I'm a unix girl at heart, my current machine is basically using windows 11 as a glorified WSL2 wrapper, trying to learn more about how things work windows-native after not using it for a few decades), is there a way to spin up that vm, like a command line way? Or is it just, you create a hyper-v vm, install windows 10 to it, snapshot it, and reset to that snapshot each time?

**Comment by stephengillie** [comment]
> Is there a way to spin up that vm, like a command line way? Or is it just, you create a hyper-v vm, install windows 10 to it, snapshot it, and reset to that snapshot each time?

I've got a base Windows 10 image in Hyper-V, and use [automation that I wrote](https://github.com/microsoft/winget-pkgs/blob/master/Tools/ManualValidationPipeline.ps1) and a custom [PowerShell profile](https://github.com/microsoft/winget-pkgs/blob/master/Tools/ManualValidationProfile.ps1) to build testing VMs off the base, to copy files to the VM, write log files back to the host via Windows file sharing, and run snapshots and manual validations.

**Comment by stephengillie** [comment]
Unfortunately, the dependency means this PR might have to wait a short bit until our 1.6 release.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
