### PR TITLE
New package: Zoom.ZoomClientforVDI(64bit) version 5.17.24660

### PR DESCRIPTION
**Pull request by patrickoperationize**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/144913)

### CODE REVIEW

**Comment by patrickoperationize** [comment]
@microsoft-github-policy-service agree [company="{Hurt Consultants, LLC d.b.a. Operationize}"]


Options:

  *   (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.

@microsoft-github-policy-service agree


  *   (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.

@microsoft-github-policy-service agree company="Microsoft"


Patrick Hurt
CEO and Founder
***@***.***
720-617-9604

________________________________

**Comment by patrickoperationize** [comment]
@microsoft-github-policy-service agree company="Hurt Consultants, LLC d.b.a. Operationize"



Patrick Hurt
CEO and Founder
***@***.***
720-617-9604

________________________________

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-03-18 09:20:02.553 [CLI ] Package hash verification failed. SHA256 in manifest [554a6b370af06a84f1f45fbf184690a14bdbc378a77c670487038b6836ef3307] does not match download [b8fc955757a9dc21a5752e64e8074184b07e62b7119917673df99342159a598a]

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-03-18 10:12:02.641 [CLI ] Package hash verification failed. SHA256 in manifest [554a6b370af06a84f1f45fbf184690a14bdbc378a77c670487038b6836ef3307] does not match download [b8fc955757a9dc21a5752e64e8074184b07e62b7119917673df99342159a598a]

(Automated response - build 870.)

**Pull request closed without merging**
