### PR TITLE
Yandex.Browser version 23.1.3.952

### PR DESCRIPTION
**Pull request by Andrej730**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/97854)
 
 
 Tried to use vanity url so that it will be keep itself up to date automatically.

### CODE REVIEW

**Comment by Andrej730** [comment]
@mdanish-kh hello! 👀 
Downloading installer from the same urls seem to produce different hash because they are adding info about the way it was downloaded at the end...

image

Is it possible to validate the installer some other way? I've found that there is so some signature from publisher that match between files.

image

**Comment by mdanish-kh** [comment]
@Andrej730 Yes, I can confirm I'm seeing different hashes from the application from the InstallerUrl you used in the manifest as it redirects to couple other Urls and adds additional parameters at the end of the Url that are serving a different application?

However, if I use the direct Url from the CDN https://cachev2-ams02.cdn.yandex.net/download.cdn.yandex.net/browser/int/23_1_3_949_40687/en/Yandex.exe, I'm consistently getting the same hash and it doesn't appear to add additional params or redirect to any other Url



```pwsh
 ~/Downloads winget hash .\Yandex.exe
InstallerSha256: 0159a0da24910b6b9cbdf888f82862e76bdc334d467f0156c279a82fe55eb449
```
I'm not sure I follow the motivation behind this PR as you used the direct Url with the correct hash in PR  #97827 👀 The merged package seems to work just fine for me with no hash mismatch errors.

**Comment by Andrej730** [comment]
@mdanish-kh the idea was to use vanity url so that wingetbot could have automatically update the manifest in the future

Is there way to use executable signature to check the match?

**Comment by mdanish-kh** [comment]
Oh right, In that case I believe we're out of luck as WinGet only matches Installer256 hash to determine if it's the same downloaded application.

**Comment by stephengillie** [comment]
This situation seems similar to the Roblox installer. https://github.com/microsoft/winget-pkgs/issues/94013#issuecomment-1386209074

**Comment by Andrej730** [comment]
I guess there is no way to get consistent hash from this vanity url, I switch it to direct url.

**Review by mdanish-kh — APPROVED** [review]

**Pull request merged**
