### PR TITLE
Nelson v1.3.0.3872

### PR DESCRIPTION
**Pull request by Nelson-numerical-software**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/147114)

### CODE REVIEW

**Comment by Nelson-numerical-software** [comment]
Please help me to find error :(
local validation and install are OK

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-03-30 23:57:50.712 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF8667BC11F: (caller: 00007FF866548D6F) LogHr(1) tid(a9c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF8666C2B08: (caller: 00007FF86676BC20) Exception(1) tid(a9c) 8A15005E ] 
> 2024-03-30 23:57:50.712 [REPO] Failed to open available source: msstore
> 2024-03-30 23:57:58.931 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF8502FC11F: (caller: 00007FF850088D6F) LogHr(1) tid(8a0) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF850202B08: (caller: 00007FF8502ABC20) Exception(1) tid(8a0) 8A15005E ] 
> 2024-03-30 23:57:58.931 [REPO] Failed to open available source: msstore
> 2024-03-30 23:58:00.238 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x64 with version 14.40.33617.1
> 2024-03-30 23:57:22.013 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!6959535B: (caller: 69491A80) LogHr(1) tid(1858) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!695DB5DD: (caller: 696712BF) Exception(1) tid(1858) 8A15005E ] 
> 2024-03-30 23:57:22.013 [REPO] Failed to open available source: msstore
> 2024-03-30 23:57:29.549 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!54AE535B: (caller: 549E1A80) LogHr(1) tid(1f8c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!54B2B5DD: (caller: 54BC12BF) Exception(1) tid(1f8c) 8A15005E ] 
> 2024-03-30 23:57:29.549 [REPO] Failed to open available source: msstore
> 2024-03-30 23:57:30.647 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x86 with version 14.40.33617.1

(Automated response - build 876.)

**Comment by Nelson-numerical-software** [comment]
sorry but I do not understand trouble here, last month previous version with same dependency worked. Does it required to update what ?

**Comment by stephengillie** [comment]
> sorry but I do not understand trouble here, last month previous version with same dependency worked. Does it required to update what ?

Unfortunately, I'm also not entirely clear on the issue. But this dependency error isn't rare right now, and the package installed and launched normally in a Windows 10 VM.

**Comment by Nelson-numerical-software** [comment]
@stephengillie thanks for your help and support :)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
