### PR TITLE
New Version: Bitvise.SSH.Client 9.24

### PR DESCRIPTION
**Pull request by Trenly**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/84591)

### CODE REVIEW

**Comment by Trenly** [comment]
Must wait until old versions are removed to correct casing on publisher folder

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Comment by Trenly** [comment]
Capitalization sucks

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
