### PR TITLE
ottercorp.FFXIVQuickLauncherCN version 6.2.38-beta7

### PR DESCRIPTION
**Pull request by AinaSnow**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/71596)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
image

**Comment by AinaSnow** [comment]
> 图像

Does the installer have to support silent installation?  We will revise as soon as possible

**Comment by denelon** [comment]
@AinaSnow yes we require a method to install without user intervention. It could either be the default mode, or by adding appropriate switches.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
See https://github.com/microsoft/winget-pkgs/pull/71596#issuecomment-1224345098

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
Close with reason: Inactive PR;

**Pull request closed without merging**
