### PR TITLE
Add: ObinsKit.ObinsKit version 1.1.6

### PR DESCRIPTION
**Pull request by quhxl**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/21596)

### CODE REVIEW

**Comment by quhxl** [comment]
In my case it happens all the time that the YamlCreate script writes the first of several installers twice in the installer file. I always have to remove one of them.

**Review by OfficialEsco — APPROVED** [review]
Whaaaat? I've submitted 35 PR's today with the newest YamlCreate and none have created a duplicate installer o_O

**Comment by quhxl** [comment]
> Whaaaat? I've submitted 20+ PR's today and none have created a duplicate installer o_O

I will send you some screenshots if it happens again. It is really weird because it only happens sometimes. I haven't figured out under which circumstances this occurs...

**Comment by OfficialEsco** [comment]
The only thing i can think of is a lagspike at the perfect time, but i'm not even sure if that can cause it lmao, every time you finish a Installer Metadata part it adds it to the Installs variable (right after you select UpgradeBehavior), it also adds the metadata line by line...
At the end of the script it also just adds the $Installers variable (not for each installer), so there is no way it duplicated there..

**Pull request merged**
