### PR TITLE
Submitting ART version 1.20.0

### PR DESCRIPTION
**Pull request by pxwiz**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/108662)

### CODE REVIEW

**Comment by pxwiz** [comment]
> @microsoft-github-policy-service agree

**Comment by pxwiz** [comment]
Please clarify. All URLs point to same domain.

The base url for all 3 is the package url
- PackageURL:  https://bitbucket.org/agriggio/art/
- PublisherURL/Home:  https://bitbucket.org/agriggio/art/wiki/Home
- Downloads:  https://bitbucket.org/agriggio/art/downloads/

**Comment by stephengillie** [comment]
> Please clarify. All URLs point to same domain.
> 
> The base url for all 3 is the package url
> 
> * PackageURL:  https://bitbucket.org/agriggio/art/
> * PublisherURL/Home:  https://bitbucket.org/agriggio/art/wiki/Home
> * Downloads:  https://bitbucket.org/agriggio/art/downloads/

Hi @pxwiz,

Bitbucket is a commonly-used download and rehost site, so our robot needed a human to confirm. Sorry for any concern. 

As for the [Policy 2.3](https://learn.microsoft.com/en-us/windows/package-manager/package/windows-package-manager-policies#23-risk-of-harm) label, I believe that's due to the other product's name - that product's PRs get a similar label.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
