### PR TITLE
New package: Microsoft.Ctrl2Cap version 2.0

### LINKED ISSUE #171121: [Package Request]: Ctrl2Cap
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://learn.microsoft.com/en-us/sysinternals/downloads/ctrl2cap
Publisher: Microsoft
Package Name: ctrl2cap
Description: Ctrl2cap is a kernel-mode device driver that filters the system's keyboard class driver in order to convert caps-lock characters into control characters.
Package Version: 2.0
Installer URL: https://download.sysinternals.com/files/Ctrl2Cap.zip

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #171121

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/171173)

### CODE REVIEW

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> This package requires manual (un)installation, since `winget.exe` doesn't support customization of uninstall command. See [Installation and Use](https://learn.microsoft.com/en-us/sysinternals/downloads/ctrl2cap#installation-and-use)
>
> Use `/install` and `/uninstall` to achieve that. It requires a modification that adding a `*.sys` file to _Windows Core Zone_. This may fail in _Validation Pipeline_. It was already failed in _Windows 11 `amd64` Sandbox_ instance.

**Comment by stephengillie** [comment]
Hi @Dragon1573,

Since this is a Sysinternals (MS sub-brand or similar) product, should it be under their `PackageIdentifier`, such as `Microsoft.Sysinternals.Ctrl2Cap`?

**Comment by stephengillie** [comment]
Verify:
image
The application can't find a file specified.
- The `PackageUrl` was last updated in 2006 - is it possible that this package doesn't work on newer versions of Windows?

**Comment by Dragon1573** [comment]
Maybe it is? 😕 I can't sure if _Windows 10/11_ is "high enough" or "too high" for _Ctrl2Cap_.

> Runs on:
>
> - Client: Windows Vista and higher.
> - Server: Windows Server 2008 and higher.
>
> _Originally posted at the bottom of [`PackageUrl`](https://learn.microsoft.com/en-us/sysinternals/downloads/ctrl2cap)_

**Comment by Dragon1573** [comment]
Behavior in https://github.com/microsoft/winget-pkgs/pull/171173#issuecomment-2326996766 successfully reproduced in _Windows 11 `amd64` Sandbox_ instance.

image

Give up and close this without being merged. 😞

**Pull request closed without merging**
