### PR TITLE
Newer Version "Zoom.ZoomRooms 5.14.1"

### PR DESCRIPTION
**Pull request by BrandonWanHuanSheng**
Updating Zoom Room to 5.14.1

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101888)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
The setup requested restart.

**Comment by BrandonWanHuanSheng** [comment]
It look like winget returning error 1 while during successful install. It look like missing a command

**Comment by BrandonWanHuanSheng** [comment]
@Trenly How do I find the product code and upgrade code.

**Comment by BrandonWanHuanSheng** [comment]
> > @Trenly How do I find the product code and upgrade code.
> 
> Product code can be found using the SandboxTest.ps1 script in the repo; If you aren't able to use the sandbox, MSI Viewer is a program that will let you find the product code and upgrade code of MSI's (both will be in the Properties table). EXE's don't have upgrade codes, but the product code is the name of the key for the uninstall entry in the registry
Where I can find that application?

**Comment by Trenly** [comment]
> > > @Trenly How do I find the product code and upgrade code.
> > 
> > 
> > Product code can be found using the SandboxTest.ps1 script in the repo; If you aren't able to use the sandbox, MSI Viewer is a program that will let you find the product code and upgrade code of MSI's (both will be in the Properties table). EXE's don't have upgrade codes, but the product code is the name of the key for the uninstall entry in the registry
> 
> Where I can find that application?

In this repo  [./Tools/SandboxTest.ps1](/microsoft/winget-pkgs/blob/master/Tools/SandboxTest.ps1) - [Script Documentation](/microsoft/winget-pkgs/blob/master/doc/tools/SandboxTest.md)

**Comment by BrandonWanHuanSheng** [comment]
@Trenly, It look like wingetbot give a Validation-Shell-Execute Error

**Comment by stephengillie** [comment]
Automatic Validation failed with:
> Installation failed with exit code -1978335226 
> 2023-04-10 08:29:31.547 [CLI ] ShellExecute installer failed: 1

**Comment by stephengillie** [comment]
Manual validation passed, and also had the error:
> 2023-04-10 11:02:35.906 [CLI ] ShellExecute installer failed: 1

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
