### PR TITLE
REDAbierta.URANOSSoftphone version 4.0

### PR DESCRIPTION
**Pull request by rafelrojas**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/83086)

### CODE REVIEW

**Comment by rafelrojas** [comment]
@mencióname

**Comment by rafelrojas** [comment]
@msftbot

**Comment by rafelrojas** [comment]
@msftbot require 3 sign offs.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]

**Comment by rafelrojas** [comment]
@msftbot require 3 sign offs.

**Comment by rafelrojas** [comment]
@msftbot msftbot/validationError/ manifest/ missingManifestsFolder

**Pull request closed without merging**
