### PR TITLE
New version: Insco.FaFaRunner version 1.0.0.358

### PR DESCRIPTION
**Pull request by kjxbyz**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/173879)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @kjxbyz,

This manifest removes the DisplayVersion from the AppsAndFeaturesEntries, which is present in previous manifest versions. This entry should be added to this version, to maintain version matching, and prevent the 'upgrade always available' situation with this package.

(Automated response - build 895.)

**Comment by kjxbyz** [comment]
@stephengillie Maybe this?

```
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/fafarunner/fafarunner/releases/download/v1.0.0+358/fafarunner_1.0.0+358_windows_x64_en-US.msi
    InstallerSha256: EB6C3EDD713C2091DA77D5D55CE08959920DD3CC6D9FFD25E457C9221DE5FCD2
    InstallerLocale: en-US
    ProductCode: '{188AA55D-99AF-4E80-BBA0-294FE036BD39}'
    AppsAndFeaturesEntries:
      - DisplayVersion: 1.0.0
        ProductCode: '{188AA55D-99AF-4E80-BBA0-294FE036BD39}'
        UpgradeCode: '{9e97bd2c-5329-45e7-ad77-34d60acae691}'
  - Architecture: x64
    InstallerUrl: https://github.com/fafarunner/fafarunner/releases/download/v1.0.0+358/fafarunner_1.0.0+358_windows_x64_zh-CN.msi
    InstallerSha256: 500A78E4DBEEE3B034BCF285D94A34D488498409136DE459AA81E70E82FA569B
    InstallerLocale: zh-CN
    ProductCode: '{17AD2E83-DD04-4D62-B16E-E10F98B49FCA}'
    AppsAndFeaturesEntries:
      - DisplayVersion: 1.0.0
        ProductCode: '{17AD2E83-DD04-4D62-B16E-E10F98B49FCA}'
        UpgradeCode: '{9e97bd2c-5329-45e7-ad77-34d60acae691}'
```

**Comment by stephengillie** [comment]
Yes, that appears to be the correct syntax and formatting. I haven't installed the application, so I can't verify the `DisplayVersion`, but so long as it doesn't overlap with other manifests it should pass all checks.

**Comment by kjxbyz** [comment]
> Yes, that appears to be the correct syntax and formatting. I haven't installed the application, so I can't verify the `DisplayVersion`, but so long as it doesn't overlap with other manifests it should pass all checks.

When the `PackageVersion` and `DisplayVersion` are the same, the `DisplayVersion` should be omitted from the AppsAndFeaturesEntries

**Comment by kjxbyz** [comment]
> > Yes, that appears to be the correct syntax and formatting. I haven't installed the application, so I can't verify the `DisplayVersion`, but so long as it doesn't overlap with other manifests it should pass all checks.
> 
> @stephengillie After the modification, the CI system did not pass, reporting an error: invalid manifest.
> 
> I found the following in the documentation: When `PackageVersion` and `DisplayVersion` are the same, `DisplayVersion` should be omitted from `AppsAndFeaturesEntries`.
> 
> So I deleted `DisplayVersion` again.

Any issues?

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
