### PR TITLE
Remove version: Citrix.Workspace version 24.3.0.93

### PR DESCRIPTION
**Pull request by PckgrBot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/151257)

### CODE REVIEW

**Review by jedieaston — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-04-27T14:11:32.6559316Z Processing manifest: manifests\c\Citrix\Workspace\24.3.0.93
 2024-04-27T14:11:32.6568791Z -----------------------------------------------------
 2024-04-27T14:11:32.6574256Z Status: Started
 2024-04-27T14:11:32.6582427Z Manifest file is Deleted
 2024-04-27T14:11:32.9296307Z Status: Completed
 2024-04-27T14:11:32.9306154Z ##[error] Result: Failed
 2024-04-27T14:11:32.9489561Z ##[error] Sequence contains no elements
 2024-04-27T14:11:32.9998910Z ##[error]Manifest Validation Failed

(Automated response - build 877.)

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 877.)

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Comment by stephengillie** [comment]
Hi @PckgrBot,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 877.)

**Pull request merged**
