### PR TITLE
AppsAndFeaturesEntries for DuongDieuPhap.ImageGlass version 8.9.6.9

### PR DESCRIPTION
**Pull request by krystofkrticka**
I was getting upgrade loop for ImageGlass so I tried to add ARP entries if it fixes my issue.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/109646&drop=dogfoodAlpha

### CODE REVIEW

**Comment by krystofkrticka** [comment]
@OfficialEsco Same I found that out later after creating PR should I tell winget to uninstall the original app before updating to new one, or contacting original developer to fix it for the optimal result.

**Comment by OfficialEsco** [comment]
I'm unsure, i think ImageGlass can handle a reinstall since the settings is stored in AppData, but this is also a issue that should be resolved by the ImageGlass devs yes

**Comment by krystofkrticka** [comment]
@OfficialEsco OK, I'll let them know about this issue once I have time to do it.

**Comment by krystofkrticka** [comment]
OK I reported this issue in developers repository https://github.com/d2phap/ImageGlass/issues/1595

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
