### PR TITLE
New package: Microsoft.RemoteToolsforVisualStudio2022 version 17.0.34916.146

### LINKED ISSUE #164769: [Package Request]: Remote Tools for Visual Studio 2022
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://visualstudio.microsoft.com/downloads/?cid=learn-onpage-download-cta#remote-tools-for-visual-studio-2022
Publisher: Microsoft
Package Name: Remote Tools for Visual Studio 2022
Description: Remote Tools for Visual Studio 2022 enables app deployment, remote debugging, remote testing, performance profiling, and unit testing on computers that do not have Visual Studio installed. Use of this tool requires a valid Visual Studio license.
Package Version: 17.0.34916.146
Installer URL: https://aka.ms/vs/17/release/RemoteTools.amd64ret.enu.exe

### PR DESCRIPTION
**Pull request by jbne**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164618)

resolve #164769

### CODE REVIEW

**Comment by denelon** [comment]
I'm not sure if that's an oversight (not to remove from the URL provided), or if it's intentional. I'll let @edwardskrod respond.

**Comment by stephengillie** [comment]
Please add a `PackageUrl` - it should be easy to navigate to the `InstallerUrl` from the `PackageUrl`.

**Comment by jbne** [comment]
@stephengillie cc @denelon @edwardskrod

I updated it to use most of the fields that were used when this package was removed: https://github.com/microsoft/winget-pkgs/pull/95986/files

The problem now is that the `InstallerUrl` always grabs the latest so when that url is updated with a newer installer the sha256 probably will no longer match - I don't have a direct link to any versions except for the ones removed. It seems like maybe the VS team would need to support that, but I don't have the context as to why this tool was removed.

If there's no steam on this, I suppose I can just use these manifest files directly in our repo(s) but I imagine there is a use case for having the remote tools installed without a VS install on the remote machine.

**Comment by stephengillie** [comment]
> The problem now is that the `InstallerUrl` always grabs the latest so when that url is updated with a newer installer the sha256 probably will no longer match[.]

This is a common problem. We call this a "vanity URL" as these are frequently used for marketing purposes. We have an automated process that checks the hash for some of these, and opens removal and addition PRs to update if changed.

**Comment by stephengillie** [comment]
>  Manifest: The manifest file path must match PackageIdentifier and PackageVersion properties from manifest. actual 
'manifests\m\Microsoft\RemoteToolsforVisualStudio2022\Latest', expected 
'manifests\m\Microsoft\VisualStudio\2022\RemoteTools\latest'

**Comment by stephengillie** [comment]
>  Manifest: The manifest file path must match PackageIdentifier and PackageVersion properties from manifest. actual 
'manifests\m\Microsoft\RemoteToolsforVisualStudio2022\Latest', expected 
'manifests\r\RemoteToolsforVisualStudio2022\latest'

Sorry to keep getting caught on the path. The the `\RemoteToolsforVisualStudio2022` folder will need to be moved into `\m\Microsoft`. (The process for doing so is immaterial - can be a file copy or a new file on a system with a filesystem and Git installed - or a modification from within the GitHub editor.)

**Comment by jbne** [comment]
@stephengillie The manifests are already under the `\m\Microsoft` path, seems like the validation is failing on the identifier - I'll try switching it from `RemoteToolsforVisualStudio2022` to `Microsoft.RemoteToolsforVisualStudio2022`

**Comment by jbne** [comment]
@stephengillie just checking in on this PR, were there any action items on me or just needs another review?

**Comment by stephengillie** [comment]
I believe we're still waiting on approval from @edwardskrod.

**Comment by denelon** [comment]
We haven't forgotten this PR. There is some internal discussion happening. I'll update once we come to a decision.

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Review by edwardskrod — CHANGES_REQUESTED** [review]
Blocking until we discuss with our Product Manager.

**Comment by denelon** [comment]
This PR is using an older version of the schema. I'm going to go ahead and close this for now. Once the manifest has been updated, either create a new PR or re-open this one.

**Pull request closed without merging**
