### PR TITLE
RoboPterodactyl.CopyIn version 1.0.0.0

### PR DESCRIPTION
**Pull request by RoboPterodactyl**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114153&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with: 
> 11:43:22 AM: 2023-08-02 11:43:21.640 [FAIL] Installer failed security check. Url: https://github.com/RoboPterodactyl/Copy-in/raw/main/Copy-in.zip Result: 0x80004005

**Comment by stephengillie** [comment]
Hi @RoboPterodactyl,

Unfortunately, this package failed a Defender scan. It might be a false positive, and I'd be happy to check again tomorrow. Please verify that your systems are virus free.

**Comment by stephengillie** [comment]
We're having to wait an extra day due to pipeline load.

**Comment by Trenly** [comment]
[Policy] Reset-Feedback

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
