### PR TITLE
Added IObit.Uninstaller version 10.6.0.6

### PR DESCRIPTION
**Pull request by ImJoakim**
Closes #22537

image

```
PS C:\Users\WDAGUtilityAccount\Downloads\WinGetHelpers-master\WinGetHelpers-master> winget install -m "C:\Users\WDAGUtilityAccount\Desktop\manifests\i\IObit\Uninstaller\10.6.0.6"
Found IObit Uninstaller [IObit.Uninstall]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://cdn.iobit.com/dl/iobituninstaller.exe
  ██████████████████████████████  26.7 MB / 26.7 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/22540)

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]
Lel, i wonder if the bot validates its own PR 🤔

**Comment by jamespik** [comment]
The installer architecture was changed from neutral to x86. Is this intentional? I will need to look in more detail, but I suspect that may be related to why you are seeing the bot update to the same version not encountering the same validation failure.

**Comment by ImJoakim** [comment]
> The installer architecture was changed from neutral to x86. Is this intentional? I will need to look in more detail, but I suspect that may be related to why you are seeing the bot update to the same version not encountering the same validation failure.

Well, it installs as 32-bit on my 64-bit VM, that's why I changed it.

image

**Comment by ImJoakim** [comment]
I could try changing it back for testing to see if it passes if you'd like.

**Comment by OfficialEsco** [comment]
> The installer architecture was changed from neutral to x86. Is this intentional? I will need to look in more detail, but I suspect that may be related to why you are seeing the bot update to the same version not encountering the same validation failure.

Just to be clear, what is Neutral architecture? That it installs x86 and x64 based on the OS architecture? Is ARM included?
If so, how does the bot test a Neutral architecture? Does it just run it on the x64 machine?
Why is it showing `Validation-No-Executables` instead of `Validation-Unattended-Failed` like we have seen before?

I know `wingetcreate` have been experimenting with splitting the "Neutral" architecture's into x64, x86 and ARM64 Installers, would that method help with validation?

**Review by OfficialEsco — APPROVED** [review]

**Comment by quhxl** [comment]
> 
> 
> > The installer architecture was changed from neutral to x86. Is this intentional? I will need to look in more detail, but I suspect that may be related to why you are seeing the bot update to the same version not encountering the same validation failure.
> 
> Just to make it clear, what is Neutral architecture? That it installs x86 and x64 based on the OS architecture? Is ARM included?
> If so, how does the bot test a Neutral architecture? Does it just run it on the x64 machine?
> Why is it showing `Validation-No-Executables` instead of `Validation-Unattended-Failed` like we have seen before?
> 
> I know `wingetcreate` have been experimenting with splitting the "Neutral" architecture's into x64, x86 and ARM64 Installers, would that method help with validation?
> 
> How can we spot the architecture? Isn't the (32 bit) indicator in Task Manager correct?

I am also curious.

**Comment by quhxl** [comment]
btw the ARP still doesn't seem to match and I get this when I run winget list: 

iobit

**Comment by OfficialEsco** [comment]
cc @denelon since this is something we can put in the README and/or [doc/manifest/schema](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.0.0/installer.md#architecture)
However we have also noticed x86 software fail on the x86 Machine..

**Comment by denelon** [comment]
https://github.com/microsoft/winget-pkgs/issues/23624

**Pull request merged**
