### PR TITLE
Devolutions.RemoteDesktopManager version 2022.2.20.0

### PR DESCRIPTION
**Pull request by krystofkrticka**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/69282)

### CODE REVIEW

**Comment by krystofkrticka** [comment]
What?! Why does it says that there is issue with package identifier which was working all previous versions of this app. Also I'm unable to push version of this app in free version because it says that new installer packages must match number of existing ones but there is only one package.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> Why does it says that there is issue with package identifier which was working all previous versions of this app.

Newer versions of winget-create and YamlCreate.ps1 uses `ManifestVersion: 1.2.0` which will be accepted in the coming days once the validation pipelines is updated.

**Review by ItzLevvie — DISMISSED** [review]

**Comment by krystofkrticka** [comment]
Ah finally I found that PSA in which was stated that I need to change manifest version back to 1.1.0 😆

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
