### PR TITLE
New version: Microsoft.vc++2015-2019.x64 14.29.30133.0

### PR DESCRIPTION
**Pull request by lychichem**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

I really what to use https://aka.ms/vs/16/release/vc_redist.x64.exe as download link to let wingetbot to automatically update this package, as I hate manually check the version. But it is not allowed by the principle now. 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/26083)

### CODE REVIEW

**Review by OfficialEsco — COMMENTED** [review]
Why are you deleting the old version if the old version is still up? This is why dynamic urls are not allowed

**Comment by lychichem** [comment]
> Why are you deleting the old version if the old version is still up? This is why dynamic urls are not allowed

The vc++ redist package will keep only the latest version for a main version number when manually updates. So I always change the folder with greatest version number to the latest version number. If it really affects the work of automatic update, I will keep old versions next time. Sorry for that.

**Comment by OfficialEsco** [comment]
> 
> 
> > Why are you deleting the old version if the old version is still up? This is why dynamic urls are not allowed
> 
> The vc++ redist package will keep only the latest version for a main version number when manually updates. So I always change the folder with greatest version number to the latest version number. If it really affects the work of automatic update, I will keep old versions next time. Sorry for that.

What do you mean? When installing VC++ it will uninstall the previous version? This is what most programs do.

There is multiple reasons why we want older version in the repo

The most important one is that VC++ is "broken", it NEEDS the ProductCode for matching, so if you keep removing the older version they will not get this update with `winget upgrade`.

Imo if you can find older versions and add them with a ProductCode that would make A LOT of people update their VC++

**Comment by lychichem** [comment]
> > 
> > 
> > > Why are you deleting the old version if the old version is still up? This is why dynamic urls are not allowed
> > 
> > The vc++ redist package will keep only the latest version for a main version number when manually updates. So I always change the folder with greatest version number to the latest version number. If it really affects the work of automatic update, I will keep old versions next time. Sorry for that.
> 
> What do you mean? When installing VC++ it will uninstall the previous version? This is what most programs do.
> 
> There is multiple reasons why we want older version in the repo
> 
> The most important one is that VC++ is "broken", it NEEDS the ProductCode for matching, so if you keep removing the older version they will not get this update with `winget upgrade`.
> 
> Imo if you can find older versions and add them with a ProductCode that would make A LOT of people update their VC++

ok，i will try to keep all versions from now, as I need to first Uninstall the latest version and install from the first version to find product code, which is impossible for me because some programs I installed require vc++ libs.

**Comment by OfficialEsco** [comment]
Use Sandbox or a VM

**Comment by OfficialEsco** [comment]
`The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.`

**Pull request closed without merging**
