### PR TITLE
New version: Genymobile.scrcpy version 2.7

### PR DESCRIPTION
**Pull request by coolplaylinbot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/173679)

### CODE REVIEW

**Comment by renebentes** [comment]
Hello, @CoolPlayLin. Could you take a look at that?

Thank you for your efforts.

**Comment by welpdx** [comment]
Hi @CoolPlayLin and @stephengillie, sorry for the tag but its been a month. Just want to see if we can bump this up. Thank you.

**Comment by welpdx** [comment]
@stephengillie @renebentes  @CoolPlayLin 
Bump please! Thank you

**Review by stephengillie — APPROVED** [review]

**Comment by aisgbnok** [comment]
Sorry I didn't catch this one in time. This PR uses `ManifestVersion: 1.6.0` without `ArchiveBinariesDependOnPath: true` so scrcpy will fail to work:

image


- Fixed by #199609

**Comment by stephengillie** [comment]
Thank you for finding and fixing this.

**Comment by stephengillie** [comment]
I appreciate your support. The process is almost entirely automated at this point, and I'm just one step from having a completely automated mode. My manual validation system has an "IEDS mode", to run random `Internal-Error-Dynamic-Scan` PRs. And I extended this to cover several other label types. Then I added automatic completion on what's detected as a successful install. 

I've been able to run about 12-15 PRs per hour across 5-6 VMs, in and around new package verifications. Only 5-6 VMs due mostly to RAM limitations on this laptop. I can't involve other hardware without legal considerations.

**Comment by aisgbnok** [comment]
> I appreciate your support. The process is almost entirely automated at this point, and I'm just one step from having a completely automated mode. My manual validation system has an "IEDS mode", to run random `Internal-Error-Dynamic-Scan` PRs. And I extended this to cover several other label types. Then I added automatic completion on what's detected as a successful install.
> 
> I've been able to run about 12-15 PRs per hour across 5-6 VMs, in and around new package verifications. Only 5-6 VMs due mostly to RAM limitations on this laptop. I can't involve other hardware without legal considerations.

That's pretty neat.

**Pull request merged**
