### PR TITLE
ProjectEnv.ProjectEnvShell version 3.2.0

### PR DESCRIPTION
**Pull request by repolevedavaj**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101680)

### CODE REVIEW

**Comment by stephengillie** [comment]
This package is expecting arguments:
```
Missing required options: '--config-file=<configFile>', '--output-template=<outputTemplate>'
Usage: project-env-shell [--debug] --config-file=<configFile>
                         [--output-file=<outputFile>]
                         --output-template=<outputTemplate>
                         [--project-root=<projectRoot>]
      --config-file=<configFile>

      --debug
      --output-file=<outputFile>

      --output-template=<outputTemplate>
...
```

**Comment by stephengillie** [comment]
Automatic Validation failed with:
> Standard error:  

I'm not able to find the cause for this error. It installs and runs normally on a Windows 11 VM.

**Comment by repolevedavaj** [comment]
> Automatic Validation failed with:
> 
> > Standard error:
> 
> I'm not able to find the cause for this error. It installs and runs normally on a Windows 11 VM.



> Automatic Validation failed with:
> 
> > Standard error:
> 
> I'm not able to find the cause for this error. It installs and runs normally on a Windows 11 VM.

Is there anything I can do? 

> Automatic Validation failed with:
> 
> > Standard error:
> 
> I'm not able to find the cause for this error. It installs and runs normally on a Windows 11 VM.

Is there anything I need to do? This package is behaving in a similar way as https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/ProjectEnv/ProjectEnvCli. Worth to mention is, that this package here is calling to ProjectEnv.ProjectEnvCli internally.

**Comment by stephengillie** [comment]
> ##[warning] Validation concluded that this task needs to go to manual review.

**Comment by repolevedavaj** [comment]
@stephengillie I would like to have this merged, even without having the dependencies declared. Is there anything else blocking the merge?

**Comment by stephengillie** [comment]
> @stephengillie I would like to have this merged, even without having the dependencies declared. Is there anything else blocking the merge?

Hi @repolevedavaj, 

Sorry to miss your earlier reply. I do not know when https://github.com/microsoft/winget-cli/issues/163 will be implemented, and unfortunately it might be some time. Adding this package without dependencies would cause a poor user experience, as installing it would result in an error instead of the installation of a useful program.

**Comment by repolevedavaj** [comment]
> > @stephengillie I would like to have this merged, even without having the dependencies declared. Is there anything else blocking the merge?
> 
> Hi @repolevedavaj,
> 
> Sorry to miss your earlier reply. I do not know when [microsoft/winget-cli#163](https://github.com/microsoft/winget-cli/issues/163) will be implemented, and unfortunately it might be some time. Adding this package without dependencies would cause a poor user experience, as installing it would result in an error instead of the installation of a useful program.

Hi @stephengillie, I decided to remove the dependency to allow merging the manifest. In my opinion, having the option to install the package through winget even without having the dependent package installed automatically is still creating the better user experience. I will keep an eye on [microsoft/winget-cli#163](https://github.com/microsoft/winget-cli/issues/163) and add the dependency again, when implemented.

**Comment by stephengillie** [comment]
This package is expecting arguments:
```
SikaLabs Utils, v0.66.0

Usage:
  slu [command]

Available Commands:
  argocd            ArgoCD Utils
  aws               AWS Utils
  awx               AWX Utils
  base64            Base64 Utils
  chaos-monkey      Chaos Monkey Utils
...
```

**Comment by stephengillie** [comment]
In a Windows 11 VM, this package appears to have installed correctly, but doesn't appear to have added or modified any files.

**Comment by repolevedavaj** [comment]
> In a Windows 11 VM, this package appears to have installed correctly, but doesn't appear to have added or modified any files.

I just executed the installation again, but in my case it installs the cli app under `C:\Program Files\Project-Env\Project-Env-Shell`

**Comment by repolevedavaj** [comment]
@stephengillie Could there be another reason?

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
