### PR TITLE
Fix: Zoom.Zoom version 5.17.5.31030

### PR DESCRIPTION
**Pull request by SpecterShell**
This pull request is automatically generated by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136028)

### CODE REVIEW

**Comment by olegpro81** [comment]
Hi guys, anyone can explain how does this work, when zoom version 5.17.5.31030 is already available when searching with winget, but checking here it's still in progress?

**Comment by olegpro81** [comment]
Looks like if when you run the install or upgrade at the moment it will install it only for system, even if you use "--scope machine" and since we have a remediation in place it does kill zoom for all users :( . I hope this can be avoided in the future.

**Review by stephengillie — APPROVED** [review]

**Comment by olegpro81** [comment]
Did anyone test the install? Something is wrong with it. Doesn't not install it for user when running the install as system: .\winget.exe install -e --id Zoom.Zoom --scope machine --silent --accept-package-agreements --accept-source-agreements

**Comment by SpecterShell** [comment]
@olegpro81 The previous version of the manifests have some issues and this PR should fix them.

**Comment by olegpro81** [comment]
> @olegpro81 There are some issues with the previous version of the manifests and this PR should fix them. And I forgot to change the name of this PR when I was trying my new automation script.

Yeah... thanks for all your effort here guys, really appreciated, but just an FYI this did break me over 1000 machines, which I need to fix now. The issue is with zoom installed under system user only and the install for --scope machine will fail until I don't uninstall it for system. :(

**Comment by SpecterShell** [comment]
> @SpecterShell
> 
> Yeah... thanks for all your effort here guys, really appreciated, but just an FYI this did break me over 1000 machines, which I need to fix now. The issue is with zoom installed under system user only and the install for --scope machine will fail until I don't uninstall it for system. :(

Is it working now?

**Comment by olegpro81** [comment]
It’s working when I uninstall it manually for system.

Regards,
Oleg
647-881-6305

**Pull request merged**
