### PR TITLE
BraveSoftwareInc.BraveBrowser version 1.31.91

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/34760)

### CODE REVIEW

**Comment by KaranKad** [comment]
Brave Browser already exists at [manifests/b/BraveSoftware/BraveBrowser](https://github.com/microsoft/winget-pkgs/tree/master/manifests/b/BraveSoftware/BraveBrowser)

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/34760#issuecomment-968067724

**Comment by simple-msu** [comment]
> 
> 
> Brave Browser already exists at [manifests/b/BraveSoftware/BraveBrowser](https://github.com/microsoft/winget-pkgs/tree/master/manifests/b/BraveSoftware/BraveBrowser)

When I searched for Bave Browser in winget ( as in the below picture ) It shows wrong version and if you go to the download link it shows you a pre-release one. Also brave browser has its own version number. 
winget brave

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> When I searched for Bave Browser in winget ( as in the below picture ) It shows wrong version and if you go to the download link it shows you a pre-release one. Also brave browser has its own version number. winget brave

That change was done intentionally. `PackageVersion` must match Control Panel. WinGet heavily relies on version numbers from Control Panel (Registry).

If I accepted this change, all users will not be able to upgrade the application using the `winget upgrade BraveSoftware.BraveBrowser` command because WinGet expects `96.1.32.97` as `PackageVersion` rather than `1.31.91`.

`96.1.32.97` is bigger than `1.31.91` so you'll not be offered any new upgrades if you're running an older version of Brave Browser.

**Comment by simple-msu** [comment]
winget brave(1)
ok but actually the current stable one is having a different version number 

> 
> 
> > When I searched for Bave Browser in winget ( as in the below picture ) It shows wrong version and if you go to the download link it shows you a pre-release one. Also brave browser has its own version number. winget brave
> 
> This is change is intentional.
> 
> `PackageVersion` must match Control Panel. WinGet heavily relies on version numbers from Control Panel which looks at the registry.
> 
> If I accepted this change, all users will not be able to upgrade the application using the `winget upgrade BraveSoftware.BraveBrowser` command because WinGet expects `96.1.32.97` as `PackageVersion` rather than `1.31.91`.
> 
> `96.1.32.97` is bigger than `1.31.91` so you'll not be offered any new upgrades if you're running an older version of Brave Browser.

**Comment by simple-msu** [comment]
is it possible to change the version number after submitting the pull request or do I have to create a new one

**Comment by ItzLevvie** [comment]
`winget install BraveSoftware.BraveBrowser --version 95.1.31.91` should give you `95.1.31.91`.

`96.1.32.97` might be a Release Candidate, according to https://github.com/brave/brave-browser/releases/v1.32.97.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> THE ABOVE IMAGE SHOWS THAT THE STABLE RELEASE OF BRAVE HAS A DIFFERRENT VERSION NUMBER

`winget install BraveSoftware.BraveBrowser --version 95.1.31.91` should give you `95.1.31.91`.

`96.1.32.97` might be a Release Candidate, according to https://github.com/brave/brave-browser/releases/v1.32.97. It's neither Canary, Dev, Beta

So, you're probably free to remove RC releases in that folder.

**Comment by simple-msu** [comment]
> 
> 
> `winget install BraveSoftware.BraveBrowser --version 95.1.31.91` should give you `95.1.31.91`.
> 
> `96.1.32.97` might be a Release Candidate, according to https://github.com/brave/brave-browser/releases/v1.32.97.

https://github.com/brave/brave-browser/releases/tag/v1.31.91 
This link has the latest stable release.
You can also check at https://brave.com/latest/

**Comment by ItzLevvie** [comment]
> https://github.com/brave/brave-browser/releases/tag/v1.31.91
> This link has the latest stable release.
> You can also check at https://brave.com/latest/

I'm aware that 1.31.91 is the current stable release.

Brave is allowing others to install the next stable release early, version 1.32.97, but the developer didn't make probably didn't make it clear that it's a Release Candidate.

I wasn't the one who made that PR - vedant did since the title has "Release" in it so his automation made the PR for it.

The only reason why I accepted that because it has the same DisplayName (ARP) as 1.31.91.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> https://github.com/brave/brave-browser/releases/tag/v1.31.91
> This link has the latest stable release.
> You can also check at https://brave.com/latest/

I'm aware that 1.31.91 is the current stable release.

I don't know if this version is a Release Candidate because it's not a Canary, a Dev, or a Beta build, but Brave is seemingly allowing others to install the next stable release early, version 1.32.9X available in GitHub Releases, but perhaps the developer didn't make this clear that it's a Release Candidate or something else.

I wasn't the one who made that PR, vedant did since the published Brave releases have "Release" in the release's title, so his automation caught it and made a PR for it.

The only reason why I accepted that PR because it has the same DisplayName (ARP) as `95.1.31.91`. You'll most likely receive an update to Chromium 96 in the coming weeks or so which will be based on these releases.

RC builds should be as reliable as non-release candidate builds, but, you're free to remove the release candidates from this folder, if it's bothering you.

You can do that by deleting the `96.1.32.97` version folder from `BraveSoftware.BraveBrowser` using Visual Studio Code by pressing the `.` (dot) on your keyboard on this PR.

**Pull request closed without merging**
