### PR TITLE
New version: Mozilla.Thunderbird version 115.2.2

### PR DESCRIPTION
**Pull request by fancybody**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
There is #119522
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

---
There are 66 different locales available [officially](https://www.thunderbird.net/en-US/thunderbird/all/). The previous merged stable manifest #111940 had only 4 locales.
My manifest only has `en-US` (as default).

Tested on Windows 11 22H2 Build 22621 on Winget 1.5.2201
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/120029)

### CODE REVIEW

**Comment by fancybody** [comment]
The URLs itself are valid. The pipeline [fails](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=497401&view=logs&j=871b4eed-22de-5cb6-c1c8-82f190de633f&t=523ceef4-ddf7-55a0-c83d-dd0f77b67744&l=812) to download from 4 installer URLs.

```
Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/115.2.2/win32/bg/Thunderbird%20Setup%20115.2.2.msi. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-311-120029-20230917-2\c7eef5b2-a832-4616-9274-1025d187fe31' because it is being used by another process..
Error information: 
Http Response: OK
Http Reason Phrase: OK
Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/115.2.2/win64/fy-NL/Thunderbird%20Setup%20115.2.2.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-311-120029-20230917-2\d04a2323-1124-4648-a707-fd7a68f4f0ae' because it is being used by another process..
Error information: 
Http Response: OK
Http Reason Phrase: OK
Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/115.2.2/win32/es-MX/Thunderbird%20Setup%20115.2.2.msi. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-311-120029-20230917-2\f21f5b5c-12b6-4231-b6f4-8284bbd76cf9' because it is being used by another process..
Error information: 
Http Response: OK
Http Reason Phrase: OK
Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/115.2.2/win64/he/Thunderbird%20Setup%20115.2.2.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-311-120029-20230917-2\f6a7212d-5dc9-4182-adca-a55f82cb91c6' because it is being used by another process..
Error information: 
Http Response: OK
Http Reason Phrase: OK
```

**Comment by stephengillie** [comment]
I think the issue here might be having too many concurrent downloads. I believe this package has the most `Installer` entries of any manifest regularly submitted.

**Comment by fancybody** [comment]
Installers Scan is successful but somehow Validation fails, even after removing 204 links (previously had 264)
Please either increase the limit or add a disclaimer on the maximum number of links allowed in a installer manifest.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335216 
image

**Comment by stephengillie** [comment]
Some of the installers aren't able to match with the "Preferred Locale". Here, `da-da` appears to be failing to match with `da-DA`: 
```
2023-09-19 14:18:54.208 [CORE] WinGet, version [1.4.10052], activity [{CF1E0CAB-C7A9-467F-9D5D-EFCB44D3150F}]
2023-09-19 14:18:54.209 [CORE] OS: Windows.Desktop v10.0.19045.3086
2023-09-19 14:18:54.209 [CORE] Command line Args: "C:\Users\validator\AppData\Local\Microsoft\WindowsApps\winget.exe" install --manifest C:\Users\validator\AppData\Local\Temp\Manifest.yaml --locale da-da --accept-package-agreements
2023-09-19 14:18:54.209 [CORE] Package: Microsoft.DesktopAppInstaller v1.19.10052.0
2023-09-19 14:18:54.209 [CORE] IsCOMCall:0; Caller: winget-cli
2023-09-19 14:18:54.226 [CLI ] WinGet invoked with arguments: 'install' '--manifest' 'C:\Users\validator\AppData\Local\Temp\Manifest.yaml' '--locale' 'da-da' '--accept-package-agreements'
2023-09-19 14:18:54.229 [CLI ] Found subcommand: install
2023-09-19 14:18:54.230 [CLI ] Leaf command to execute: root:install
2023-09-19 14:18:54.250 [CLI ] Executing command: install
2023-09-19 14:18:54.258 [CLI ] Manifest fields: Name [Mozilla Thunderbird], Version [115.2.2]
2023-09-19 14:18:54.263 [CLI ] Starting installer selection.
2023-09-19 14:18:54.263 [CLI ] Installer [X86,exe,Unknown,da-DA] not applicable: Installer locale does not match required locale: da-DARequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.263 [CLI ] Installer [X86,wix,Unknown,da-DA] not applicable: Installer locale does not match required locale: da-DARequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.263 [CLI ] Installer [X86,exe,Unknown,de-DE] not applicable: Installer locale does not match required locale: de-DERequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.263 [CLI ] Installer [X86,wix,Unknown,de-DE] not applicable: Installer locale does not match required locale: de-DERequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.263 [CLI ] Installer [X86,exe,Unknown,el-EL] not applicable: Installer locale does not match required locale: el-ELRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.263 [CLI ] Installer [X86,wix,Unknown,el-EL] not applicable: Installer locale does not match required locale: el-ELRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.263 [CLI ] Installer [X86,exe,Unknown,en-GB] not applicable: Installer locale does not match required locale: en-GBRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.263 [CLI ] Installer [X86,wix,Unknown,en-GB] not applicable: Installer locale does not match required locale: en-GBRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.263 [CLI ] Installer [X86,exe,Unknown,en-US] not applicable: Installer locale does not match required locale: en-USRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.263 [CLI ] Installer [X86,wix,Unknown,en-US] not applicable: Installer locale does not match required locale: en-USRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.263 [CLI ] Installer [X86,exe,Unknown,es-ES] not applicable: Installer locale does not match required locale: es-ESRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.263 [CLI ] Installer [X86,wix,Unknown,es-ES] not applicable: Installer locale does not match required locale: es-ESRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.263 [CLI ] Installer [X86,exe,Unknown,fi-FI] not applicable: Installer locale does not match required locale: fi-FIRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.263 [CLI ] Installer [X86,wix,Unknown,fi-FI] not applicable: Installer locale does not match required locale: fi-FIRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.263 [CLI ] Installer [X86,exe,Unknown,fr-FR] not applicable: Installer locale does not match required locale: fr-FRRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.263 [CLI ] Installer [X86,wix,Unknown,fr-FR] not applicable: Installer locale does not match required locale: fr-FRRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.263 [CLI ] Installer [X86,exe,Unknown,it-IT] not applicable: Installer locale does not match required locale: it-ITRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.263 [CLI ] Installer [X86,wix,Unknown,it-IT] not applicable: Installer locale does not match required locale: it-ITRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.263 [CLI ] Installer [X86,exe,Unknown,ja-JA] not applicable: Installer locale does not match required locale: ja-JARequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.263 [CLI ] Installer [X86,wix,Unknown,ja-JA] not applicable: Installer locale does not match required locale: ja-JARequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X86,exe,Unknown,nb-NO] not applicable: Installer locale does not match required locale: nb-NORequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X86,wix,Unknown,nb-NO] not applicable: Installer locale does not match required locale: nb-NORequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X86,exe,Unknown,nn-NO] not applicable: Installer locale does not match required locale: nn-NORequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X86,wix,Unknown,nn-NO] not applicable: Installer locale does not match required locale: nn-NORequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X86,exe,Unknown,pt-PT] not applicable: Installer locale does not match required locale: pt-PTRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X86,wix,Unknown,pt-PT] not applicable: Installer locale does not match required locale: pt-PTRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X86,exe,Unknown,sv-SE] not applicable: Installer locale does not match required locale: sv-SERequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X86,wix,Unknown,sv-SE] not applicable: Installer locale does not match required locale: sv-SERequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X86,exe,Unknown,zh-TW] not applicable: Installer locale does not match required locale: zh-TWRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X86,wix,Unknown,zh-TW] not applicable: Installer locale does not match required locale: zh-TWRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,exe,Unknown,da-DA] not applicable: Installer locale does not match required locale: da-DARequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,wix,Unknown,da-DA] not applicable: Installer locale does not match required locale: da-DARequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,exe,Unknown,de-DE] not applicable: Installer locale does not match required locale: de-DERequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,wix,Unknown,de-DE] not applicable: Installer locale does not match required locale: de-DERequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,exe,Unknown,el-EL] not applicable: Installer locale does not match required locale: el-ELRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,wix,Unknown,el-EL] not applicable: Installer locale does not match required locale: el-ELRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,exe,Unknown,en-GB] not applicable: Installer locale does not match required locale: en-GBRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,wix,Unknown,en-GB] not applicable: Installer locale does not match required locale: en-GBRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,exe,Unknown,en-US] not applicable: Installer locale does not match required locale: en-USRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,wix,Unknown,en-US] not applicable: Installer locale does not match required locale: en-USRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,exe,Unknown,es-ES] not applicable: Installer locale does not match required locale: es-ESRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,wix,Unknown,es-ES] not applicable: Installer locale does not match required locale: es-ESRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,exe,Unknown,fi-FI] not applicable: Installer locale does not match required locale: fi-FIRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,wix,Unknown,fi-FI] not applicable: Installer locale does not match required locale: fi-FIRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,exe,Unknown,fr-FR] not applicable: Installer locale does not match required locale: fr-FRRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,wix,Unknown,fr-FR] not applicable: Installer locale does not match required locale: fr-FRRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,exe,Unknown,it-IT] not applicable: Installer locale does not match required locale: it-ITRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,wix,Unknown,it-IT] not applicable: Installer locale does not match required locale: it-ITRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,exe,Unknown,ja-JA] not applicable: Installer locale does not match required locale: ja-JARequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,wix,Unknown,ja-JA] not applicable: Installer locale does not match required locale: ja-JARequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,exe,Unknown,nb-NO] not applicable: Installer locale does not match required locale: nb-NORequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,wix,Unknown,nb-NO] not applicable: Installer locale does not match required locale: nb-NORequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,exe,Unknown,nn-NO] not applicable: Installer locale does not match required locale: nn-NORequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.264 [CLI ] Installer [X64,wix,Unknown,nn-NO] not applicable: Installer locale does not match required locale: nn-NORequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.265 [CLI ] Installer [X64,exe,Unknown,pt-PT] not applicable: Installer locale does not match required locale: pt-PTRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.265 [CLI ] Installer [X64,wix,Unknown,pt-PT] not applicable: Installer locale does not match required locale: pt-PTRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.265 [CLI ] Installer [X64,exe,Unknown,sv-SE] not applicable: Installer locale does not match required locale: sv-SERequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.265 [CLI ] Installer [X64,wix,Unknown,sv-SE] not applicable: Installer locale does not match required locale: sv-SERequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.265 [CLI ] Installer [X64,exe,Unknown,zh-TW] not applicable: Installer locale does not match required locale: zh-TWRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.265 [CLI ] Installer [X64,wix,Unknown,zh-TW] not applicable: Installer locale does not match required locale: zh-TWRequired locales: [da-da] Or does not satisfy compatible match for Preferred Locales: [en-US]
2023-09-19 14:18:54.307 [CLI ] Terminating context: 0x8a150010 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:a0
```

**Comment by tsunamistate** [comment]
Thunderbird 115.2.3 was released, making this PR obsolete
https://www.thunderbird.net/en-US/thunderbird/115.2.3/releasenotes

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
