### PR TITLE
Add JakobDev.jdDesktopEntryEdit

### PR DESCRIPTION
**Pull request by JakobDev**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/112743&drop=dogfoodAlpha

### CODE REVIEW

**Comment by JakobDev** [comment]
What exactly are the issues?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2023-07-21 08:22:39.340 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFB5D5F1EFD: (caller: 00007FFB5D5F27D0) Exception(1) tid(260) 80072EE2  2023-07-21 08:23:17.957 [FAIL] Installer failed security check. Url: https://sourceforge.net/projects/jddesktopentryedit/files/1.2/jdDesktopEntryEdit-1.2-WindowsInstaller.exe/download Result: 0x80004005

**Comment by JakobDev** [comment]
@stephengillie The download and install works without a problem for me, so you should retry

**Review by ItzLevvie — APPROVED** [review]

**Comment by JakobDev** [comment]
Ping @stephengillie

**Pull request merged**
