### PR TITLE
New version: IDRIX.VeraCrypt version 1.26.7

### LINKED ISSUE #147384: [Update Request]: VeraCrypt 1.26.7
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

IDRIX/VeraCrypt

### Package Version

1.26.7

### Please describe the changes you would like to see

Newer version (1.26.7) is available.
New launchpad link to the msi-file: https://launchpad.net/veracrypt/trunk/1.26.7/+download/VeraCrypt_Setup_x64_1.26.7.msi

### PR DESCRIPTION
**Pull request by BiosPlus**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.1.0 :rocket:

- Resolves #147384

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/147459)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
@BiosPlus https://github.com/microsoft/winget-pkgs/pull/135205#discussion_r1460715990
image

**Comment by BiosPlus** [comment]
Oh damn it.

**Comment by stephengillie** [comment]
The fix here might involve adding an `Agreements` section to the manifest. But I believe a prerequisite for that might involve action or a form of agreement from the developer or publisher.

**Comment by Trenly** [comment]
> @BiosPlus [#135205 (comment)](https://github.com/microsoft/winget-pkgs/pull/135205#discussion_r1460715990) image

@exorcism0666 - This policy has been changed recently with the introduction of the `Agreements` Field

**Pull request closed without merging**
