### PR TITLE
New package: SMARTTechnologies.SMARTNotebook version 24.0

### PR DESCRIPTION
**Pull request by PckgrBot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/162463)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335229
> 2024-07-11 00:25:32.290 [CLI ] Caught std::exception: bad allocation

(Automated response - build 886.)

**Comment by stephengillie** [comment]
Manual Validation failed during or immediately after the download.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335229
> 2024-07-11 21:23:29.501 [CLI ] Caught std::exception: bad allocation

(Automated response - build 886.)

**Comment by stephengillie** [comment]
Verify:
image
image
image
image

Hi @PckgrBot,

This package seems to present 3 different version numbers in different places. Since this application displays version `22.2 (24.0.1733.0)` but writes to the Registry `24.0.306.0`, it should probably have a `DisplayVersion`. If the version number in parentheses matched the Registry, I'd give it a pass.

**Pull request closed without merging**
