### PR TITLE
Speed-Soft.Time-Sync.Client version 1.8.9.0

### PR DESCRIPTION
**Pull request by Speed7811**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101841)

### CODE REVIEW

**Comment by Speed7811** [comment]
@microsoft-github-policy-service agree

**Comment by Speed7811** [comment]
The links are working. Please check it. There is no problem with edge when I visit my site with activated smart screen.

**Comment by ItzLevvie** [comment]
> The links are working. Please check it. There is no problem with edge when I visit my site with activated smart screen.

The website has Azure IP addresses blocked.

Does the website use bot protection? If you're the website owner then you will need to whitelist Azure IPs.

**Comment by Speed7811** [comment]
@ItzLevvie: It seems that you are right. I can see it in the webserver protocol. I got  "access forbidden by rule" error message when MS access to these URLs. I cannot find any firewall blockings but I contacted my provider. Thank you for testing.

**Comment by Speed7811** [comment]
Fixed

**Comment by Speed7811** [comment]
@ItzLevvie I tried this with codespaces and it work. But it seems that the ip ranges are changed. Now I allow all - if this doesn't work I need to talk to my provider again. Please can you start the bot again. Thank you.

**Comment by BrandonWanHuanSheng** [comment]
It look like some link were blocked by automatic data download.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
