### PR TITLE
Update: Badlion.BadlionClient version 3.1.9

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

* Resolves #55297
* Resolves #55296
* Resolves #55295
* Resolves #55293
* Resolves #55276

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/55311)

### CODE REVIEW

**Comment by Trenly** [comment]
#42616

**Comment by OfficialEsco** [comment]
IMO the Bitwig PRs should stay up so wingetbot dosn't create more

**Comment by Trenly** [comment]
> IMO the Bitwig PRs should stay up so wingetbot dosn't create more

Updated PR body

**Review by OfficialEsco — APPROVED** [review]
wingetbot might even cheese the systems later tonight by closing and pushing another PR tho, but well see, hopefully bitwig fixes their certificate..

**Pull request merged**
