### PR TITLE
Rename Version: SergeySerkov.TagScanner 6.1.11 to 6.1.12

### PR DESCRIPTION
**Pull request by ItsPizzaTime1501**
Software and installer clearly say 6.1.12 yet the version in this repo is called 6.1.11

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/40014)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
WinGet relies on the application version from the Control Panel's Add or Remove Programs list:
image

Changing the `PackageVersion` to be `6.1.12` will make everyone download 5 MB in a loop whenever someone runs the `winget upgrade SergeySerkov.TagScanner` or `winget upgrade --all` command in Command Prompt or PowerShell because `6.1.12` (PackageVersion) is higher than `6.1.11` (Control Panel) instead of `6.1.12` (PackageVersion) equaling to `6.1.12` (Control Panel).

You will need to contact the application developer to update their registry entry for `DisplayVersion` to be `6.1.12`.

**Comment by ItsPizzaTime1501** [comment]
Alright, I'll try to get in contact with the dev, thanks for informing me of this I wasn't aware.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> Alright, I'll try to get in contact with the dev, thanks for informing me of this I wasn't aware.

You can set this PR in DRAFT (so it doesn't show up in my GitHub filter) until there's a response from the developer.

**Comment by ItsPizzaTime1501** [comment]
Closing cause I haven't gotten a response.

**Pull request closed without merging**
