### PR TITLE
Microsoft.Git version 2.39.1.0.0

### PR DESCRIPTION
**Pull request by ldennington**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://api.github.com/repos/microsoft/winget-pkgs/pulls/95419)

### CODE REVIEW

**Comment by ldennington** [comment]
Is there something wrong with the validation pipeline? It keeps failing but not showing any errors.

**Comment by stephengillie** [comment]
> Is there something wrong with the validation pipeline? It keeps "failing" but not showing any errors.

Yes, we've been working through a couple of issues.
* https://github.com/microsoft/winget-pkgs/issues/95543

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
