### PR TITLE
New package: Nutstore.NutstoreLightApp version 2.0.3

### PR DESCRIPTION
**Pull request by SpecterShell**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/58988)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Madhusudhan-MSFT** [comment]
@SpecterShell  - I am validating the source of Installer Url used in the manifest. I can't find installers listed in the manifest from the PublisherUrl. Could you please help me understand where these installers are hosted and how we get to these installers from the PublisherUrl ?

**Comment by SpecterShell** [comment]
Yes, this one doesn't have standalone page. It comes from `NutStore.NutStore` and I got the link from its API.
I have asked the publisher whether I can publish this package but it may take days to response. 🤔

**Comment by SpecterShell** [comment]
They replied today. 😀
image
> Hello, it can be reproduced or quoted, but there is a possibility of changes or invalidation afterwards.

**Pull request merged**
