### PR TITLE
Added x86 installer to Elastic.Winlogbeat version 7.13.2

### PR DESCRIPTION
**Pull request by ImJoakim**
image

```
PS C:\Users\WDAGUtilityAccount\Desktop\manifests> winget install -m "C:\Users\WDAGUtilityAccount\Desktop\manifests\e\Elastic\Winlogbeat\7.13.2"
Found Beats winlogbeat [Elastic.Winlogbeat]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://artifacts.elastic.co/downloads/beats/winlogbeat/winlogbeat-7.13.2-windows-x86.msi
  ██████████████████████████████  19.0 MB / 19.0 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/20215)

### CODE REVIEW

**Comment by ImJoakim** [comment]
Are you able to approve this @OfficialEsco?

**Review by OfficialEsco — APPROVED** [review]
Doubt

@jamespik add `Azure-Pipeline-Passed` >:o

**Comment by denelon** [comment]
@OfficialEsco I'm down to about 700 e-mails to review before I'm caught back up. We're rotating some engineers through the validation process to make sure everyone has a good shared understanding of the challenges with validation and approval. We're also reworking some of the bot behavior to make things better. It's a bit painful right now with everyone ramping up, but I hope it gets better soon. I truly appreciate all of the effort you're putting into helping us improve!

I have rules in my e-mail to keep an eye on validation and the pipelines. You and the other moderators @jedieaston & @ItzLevvie are doing AMAZING work to figure out what's going on and educating others. We're getting close to the v1.1 schema changes that should help quite a bit with matching in Add / Remove Programs | Apps & Features. The client implementation will lag behind the schema changes, but the goal is for them to be non breaking so we don't have to update all the manifests and wipe history again.

Again THANK YOU!

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
cc @palenshus @denelon: "Azure-Pipeline-Passed" label needs to be added to this PR.

**Review by denelon — APPROVED** [review]

**Pull request merged**
