### PR TITLE
Submitting francWhite.reportify 0.2.1

### PR DESCRIPTION
**Pull request by francWhite**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/118335)

### CODE REVIEW

**Comment by francWhite** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Hi @francWhite,

This package appears to depend on DLLs that aren't available to its symlink. Running the symlink gives a DLL error: 
```
PS C:\Users\User\Desktop> C:\Users\User\AppData\Local\Microsoft\WinGet\Links\reportify.exe
The application to execute does not exist: 'C:\Users\User\AppData\Local\Microsoft\WinGet\Links\reportify.dll'.
```

But when running from the main folder, it reports missing configuration and access data: 
```
PS C:\Users\User\Desktop> C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\francWhite.reportify__DefaultSource\reportify.exe
Configuration file C:\Users\User\.reportify is invalid, please fix the following errors.
  - ManicTime database file not found: C:\Users\User\AppData\Local\Finkit\ManicTime\ManicTimeReports.db
  - Jira access token is not defined
````

**Comment by francWhite** [comment]
Dear @stephengillie

Thank you for your feedback! I encountered the same error when I tested the package locally, but after adding the FileExtensions field to the installer manifest, it seemed like it fixed the problem, but maybe that was just a coincidence.

I changed the output format of the application yesterday anyway so that it only creates a single executable. If I understand the issue #2711 correctly, the problem should be solved that way, at least locally the error does not occur anymore.

I will push the new manifest for the package version 0.2.1 and delete the initial version.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
