### PR TITLE
BakkesMod.BakkesMod version 31

### PR DESCRIPTION
**Pull request by CanePlayz**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/98387)

### CODE REVIEW

**Comment by CanePlayz** [comment]
@microsoft-github-policy-service agree

**Comment by CanePlayz** [comment]
I have to note that I've heard but I'm not sure that only applications supporting silent installations would be supported. In that case, BakkesMod would be a more complicated case.

What I've submitted here is the Setup.exe which installs the BakkesMod Injector and the current underlying BakkesMod version for you.

However, if only programs supporting silent installs are supported, we could instead make it so that the .exe from [here](https://github.com/bakkesmodorg/BakkesModInjectorCpp/releases/tag/2.0.25.2) is downloaded. That just downloads the injector and then lets you install the underlying version from inside the injector via an update.

**Comment by CanePlayz** [comment]
However, I think the second option isn't that good since the .exe that you later need to open the program is what you download and it doesn't get put into ProgramData or anything similar.

**Comment by CanePlayz** [comment]
Uhm that's not normal, is it?

image

**Comment by CanePlayz** [comment]
Opened a case here: https://www.microsoft.com/en-us/wdsi/submission/7d4fdf5c-a7d6-4115-99e3-b5faee7b108c

**Comment by CanePlayz** [comment]
Unfortunately, MS wasn't able to reproduce any detection: https://www.microsoft.com/en-us/wdsi/submission/7d4fdf5c-a7d6-4115-99e3-b5faee7b108c What am I supposed to do now?

**Comment by stephengillie** [comment]
Hi @CanePlayz,

The installer asks if it's okay to close open applications. Is there an installer switch to bypass this check?
image

**Comment by stephengillie** [comment]
Hi @CanePlayz,

Please ignore the Internal-Error-Dynamic-Scan labels, as these are a pipeline error we're working to identify. 

The installation isn't unattended:
image

Is there an installer switch to bypass this and have it install automatically?

**Comment by CanePlayz** [comment]
Unfortunately, I haven't received any information from the devs yet. I will let you know once I've found out something.

**Comment by CanePlayz** [comment]
The team behind BakkesMod has decided they do not want their software to be featured on winget, and I will respect that of course. I will leave this PR open so you can keep on testing the pipelines if you want to, feel free to close the PR anytime though.

**Comment by stephengillie** [comment]
This is an Inno installer and the switch `/?` gives its installer switches:
image

But even with `/VERYSILENT /SUPPRESSMSGBOXES /FORCECLOSEAPPLICATIONS` it still pops up with the box. So it doesn't appear to have an unattended mode. Blocked by:
* https://github.com/microsoft/winget-cli/issues/910

**Comment by CanePlayz** [comment]
> This is an Inno installer and the switch `/?` gives its installer switches: image
> 
> But even with `/VERYSILENT /SUPPRESSMSGBOXES /FORCECLOSEAPPLICATIONS` it still pops up with the box. So it doesn't appear to have an unattended mode. Blocked by:
> 
> * [Settings for installer modes winget-cli#910](https://github.com/microsoft/winget-cli/issues/910)

Thanks for your investigations, but as I mentioned above, unfortunately, the devs don't want their software on winget...

**Comment by stephengillie** [comment]
> The team behind BakkesMod has decided they do not want their software to be featured on winget, and I will respect that of course. I will leave this PR open so you can keep on testing the pipelines if you want to, feel free to close the PR any time though.

Thanks for letting us know.

**Pull request closed without merging**
