### PR TITLE
New package: AlickolliSoftware.RandomNumberGenerator(UWP) version 1.0…

### PR DESCRIPTION
**Pull request by licon4812**
….0.0

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/93522)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @licon4812,

Validation failed due to a certificate error:
> 800B0109 A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.

I'm not sure, but I believe the certificate in the error is the msixbundle signing certificate. This is probably something that the package's developer has to fix.

**Comment by licon4812** [comment]
> Hi @licon4812,
> 
> Validation failed due to a certificate error:
> 
> > 800B0109 A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
> 
> I'm not sure, but I believe the certificate in the error is the msixbundle signing certificate. This is probably something that the package's developer has to fix.

I am the developer of this application. I signed the msixbundle with a certificate generated by visual studio. Any tips on how to fix this?

**Comment by stephengillie** [comment]
> Hi @stephengillie I am the developer of this application. I signed the msixbundle with a certificate generated by visual studio. Any tips on how to fix this?

Unfortunately I haven't packaged an msixbundle before. Do you have the certificate it was signed with? What other certs are on the chain, including the root?

**Comment by licon4812** [comment]
> > Hi @stephengillie I am the developer of this application. I signed the msixbundle with a certificate generated by visual studio. Any tips on how to fix this?
> 
> Unfortunately I haven't packaged an msixbundle before. Do you have the certificate it was signed with? What other certs are on the chain, including the root?

I Have the certificate it was signed with

**Comment by denelon** [comment]
I did a quick search:

[Sign a Windows 10 app package - MSIX | Microsoft Learn](https://learn.microsoft.com/windows/msix/package/signing-package-overview)

App package signing is a required step in the process of creating a Windows 10 app package that can be deployed. Windows 10 requires all applications to be signed with a valid code signing certificate.

To successfully install a Windows 10 application, the package doesn't just have to be signed but also trusted on the device. This means that the certificate has to chain to one of the trusted roots on the device. By default, Windows 10 trusts certificates from most of the certificate authorities that provide code signing certificates.

**Comment by licon4812** [comment]
> I did a quick search:
> 
> [Sign a Windows 10 app package - MSIX | Microsoft Learn](https://learn.microsoft.com/windows/msix/package/signing-package-overview)
> 
> App package signing is a required step in the process of creating a Windows 10 app package that can be deployed. Windows 10 requires all applications to be signed with a valid code signing certificate.
> 
> To successfully install a Windows 10 application, the package doesn't just have to be signed but also trusted on the device. This means that the certificate has to chain to one of the trusted roots on the device. By default, Windows 10 trusts certificates from most of the certificate authorities that provide code signing certificates.

It looks like I need to purchase a certificate not self-sign for it to be classed as trustworthy. I will do so over the next couple of weeks

**Comment by denelon** [comment]
@licon4812,

I believe it's possible to use the App Installer to "side-load" packages with self-signed certificates. I know that may be a bit confusing, but it allows ISVs to develop and test their applications without needing to purchase a certificate. There may also be scenarios for line of business applications where the certificate is self-signed, and the machines are configured with that "private" trusted root.

**Pull request closed without merging**
