### PR TITLE
Update URL for Bitnami.WAMP version 8.1.11-0

### PR DESCRIPTION
**Pull request by Trenly**
From latest URL Scan:
> https://bitnami.com/redirect/to/2208347/bitnami-wampstack-8.1.11-0-windows-x64-installer.exe for Bitnami.WAMP version 8.1.11-0 redirects to https://downloads.bitnami.com/files/stacks/wampstack/8.1.11-0/bitnami-wampstack-8.1.11-0-windows-x64-installer.exe

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/105654)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
Looks like the pipelines are timing out. It installs silently in a sandbox, but just takes a while
image

**Comment by stephengillie** [comment]
Automatic Validation ended with:
InstallationVerification-x64-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20230504065615

**Comment by stephengillie** [comment]
> Looks like the pipelines are timing out. It installs silently in a sandbox, but just takes a while
Possible, but this is failing after just ~45 minutes, while timeout usually takes over 3 hours.

**Comment by Trenly** [comment]
> > Looks like the pipelines are timing out. It installs silently in a sandbox, but just takes a while
> 
> Possible, but this is failing after just ~45 minutes, while timeout usually takes over 3 hours.

It does spawn several subprocesses and did hang for a few seconds every once in a while to process, but for me it installed without user interaction

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
