### PR TITLE
New version: Tencent.UGit version 5.27.0

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#10336](https://github.com/SpecterShell/Dumplings/actions/runs/12371635515).

<details>

<summary>Log</summary>

````
Updated: 5.26.1 → 5.27.0
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
The manifests for the last version 5.26.1 will be removed. Reason: No installer URL is changed compared with the last state while the version is updated
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/199285)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
I'm not sure, but it seems like the installation didn't complete. The shortcuts are available: 
image

But the EXE is not:
image

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Pull request merged**
