### PR TITLE
GoLang.Go.1.20.2 version 1.20.2

### PR DESCRIPTION
**Pull request by staticfrost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101416)

### CODE REVIEW

**Comment by staticfrost** [comment]
@microsoft-github-policy-service agree

**Comment by staticfrost** [comment]
How long does 
WinGetSvc-Validation (Installer Validation) step normally take?

**Comment by stephengillie** [comment]
Hi @staticfrost,

There's a similar PackageIdentifier `GoLang.Go.1.20` - should that one be used here instead of creating a parallel PackageIdentifier?

**Comment by staticfrost** [comment]
@stephengillie, unsure of what the pros or cons would be?

**Comment by staticfrost** [comment]
Looked at trying to update the current 'GoLang.Go.1.20' 

I get the following error from WingetCreate: ` WingetCreate update GoLang.Go.1.20 --add --urls https://go.dev/dl/go1.20.2.windows-amd64.msi`

"Updating a manifest is only supported with the same number of installer URLs."

So it looks like there is no way to actual use the previous 1.20?

**Comment by staticfrost** [comment]
created https://github.com/microsoft/winget-pkgs/pull/101472 ... this can be closed now.

**Pull request closed without merging**
