### PR TITLE
New version: dotenvx.dotenvx 1.14.0

### PR DESCRIPTION
**Pull request by motdotenv**
New version: dotenvx.dotenvx 1.14.0
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/171629)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-09-04 20:58:45.665 [FAIL] Installer failed security check. Url: https://github.com/dotenvx/dotenvx/releases/download/v1.14.0/dotenvx-1.14.0-windows-x86_64.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 895.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-09-07 04:24:35.017 [FAIL] Installer failed security check. Url: https://github.com/dotenvx/dotenvx/releases/download/v1.14.0/dotenvx-1.14.0-windows-x86_64.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 895.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\dotenvx.dotenvx__DefaultSource\dotenvx.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\dotenvx.exe returned exit code: 1

(Automated response - build 895.)

**Pull request merged**
