### PR TITLE
New version: Jackett.Jackett version 0.21.1461

### PR DESCRIPTION
**Pull request by ilike2burnthing**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132180)

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
There's no issue with installing this build.

The [last build](https://github.com/microsoft/winget-pkgs/pull/132103) was also blocked, however the automated response then mentioned Defender scans being the issue (also wrong, and the Pipelines errors are the same between these two build - scan successful, validation failed).

There have been no major changes since the last successful build 2 days ago - https://github.com/microsoft/winget-pkgs/pull/132009.

Looks like an issue on your end.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 
> 2023-12-29 22:17:30.591 [FAIL] Installer failed security check. Url: https://github.com/Jackett/Jackett/releases/download/v0.21.1461/Jackett.Installer.Windows.exe Result: 0x80004005

(Automated response - build 516.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 
> 2023-12-29 22:17:30.591 [FAIL] Installer failed security check. Url: https://github.com/Jackett/Jackett/releases/download/v0.21.1461/Jackett.Installer.Windows.exe Result: 0x80004005

(Automated response - build 516.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
