### PR TITLE
cuiliang.quicker version 1.27.20

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/37570)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
image

**Comment by oxygen-dioxide** [comment]
> image

The software says that it needs Webview2. Press Enter to install and press Ctrl-C to exit. 

The latest version of windows already have webview2 installed, so most users won't see this.

**Review by Trenly — CHANGES_REQUESTED** [review]
> The software says that it needs Webview2. Press Enter to install webview2 and press Ctrl-C to continue without installing webview2.
> 
> The latest version of windows already have webview2 installed, so most users won't see this.

If it is dependent on webview2, then it should probably be added to the manifest as a dependency. I know that winget doesn't know how to install dependencies yet, and I do realize it won't be an issue for most users, but for the sake of completeness it should probably be included

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/37570#event-5898062671

**Pull request closed without merging**
