### PR TITLE
New version: Microsoft.DevHome version 0.301.198.0

### PR DESCRIPTION
**Pull request by vineeththomasalex**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/112622&drop=dogfoodAlpha

### CODE REVIEW

**Comment by mdanish-kh** [comment]
@stephengillie @denelon I believe the validation error is due to https://github.com/microsoft/winget-cli/issues/3452. Do we want to wait until the pipelines are updated to skip stub package validation or can we let this in through manual validation?

[Policy] reset feedback
[Policy] Needs-Attention

**Comment by stephengillie** [comment]
Automatic Validation ended with: 
>  Manifest Error: Inconsistent value in the manifest. [PackageVersion] Value: 0.300.198.0

**Comment by denelon** [comment]
Once we get the version thing figured out, I'm OK letting this in while we finish the stub package work.

**Comment by stephengillie** [comment]
> Automatic Validation ended with:
> 
> > Manifest Error: Inconsistent value in the manifest. [PackageVersion] Value: 0.300.198.0

I'm not seeing the cause for this error, so I'm unable to suggest a fix.

**Pull request closed without merging**
