### PR TITLE
New version: Nushell.Nushell version 0.64.0

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Failed
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | nu | Dolphin, Google Chrome Canary, Kate    |
| Version     | 0.64.0     | 22.04.2, 105.0.5121.0, 22.04.2 |
| Publisher   | The Nu Project Contributors   | KDE e.V., Google LLC, KDE e.V.      |
| ProductCode | {D3489DE6-521A-4FC3-8F40-A5CDDD7D3795}          | Dolphin, Google Chrome SxS, Kate    |
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/63642)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie2** [comment]
```
2022-06-15 04:30:15.480 [FAIL] Installer failed security check. Url: https://github.com/nushell/nushell/releases/download/0.64.0/nu-0.64.0-x86_64-pc-windows-msvc.msi Result: 0x80004005
```

**Comment by hustcer** [comment]
@vedantmgoyal2009 Hey, Nushell member here, you may wondering what's happened, for more detail see: https://github.com/nushell/nushell/issues/5787, and I will try to fix the install URL later, thanks

**Comment by lechacon** [comment]
@vedantmgoyal2009 I see. I didn't look closely enough at the other PR. I agree with replacing the current manifest with this PR to point to the official release and for future releases nushell can use the updated workflow @hustcer was testing. I'll re-open this PR, however there is still the installation-error and the merge conflict that need to be resolved manually.

**Comment by hustcer** [comment]
@lechacon I have created on already: https://github.com/microsoft/winget-pkgs/pull/63710

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
