### PR TITLE
Add Eclipse Mosquitto 1.6.9

### PR DESCRIPTION
**Pull request by ralight**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/484)

### CODE REVIEW

**Comment by ralight** [comment]
This has been confirmed as a false positive:
fp

**Comment by KevinLaMS** [comment]
smartscreen failed again.   leaving assigned to me to investigate.

**Comment by ralight** [comment]
Thanks @KevinLaMS

**Comment by KevinLaMS** [comment]
This failed to install due to missing dependency on VCRuntime140.DLL.  We have a backlogged item for supporting dependencies, but would it be possible to add that to your installer so it does not fail?

**Pull request closed without merging**
