### PR TITLE
OpenSSL Light 1.1.1k

### PR DESCRIPTION
**Pull request by auanasgheps**
Re-Added

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/13968)

### CODE REVIEW

**Comment by lychichem** [comment]
The manifest schema has switched to 1.0 from 0.1. Do not use 0.1 anymore, otherwise your submission will be rejected again and again.

**Comment by auanasgheps** [comment]
Thank you, will regenerate the Manifest and try. I though was already at 1.0

**Comment by KaranKad** [comment]
```
PackageIdentifier: ShiningLight.OpenSSLLight
PackageVersion: 1.0.0
PackageLocale: en-US
Publisher: Shining Light
PublisherUrl: https://slproweb.com/
PackageName: OpenSSL
PackageUrl: https://slproweb.com/products/Win32OpenSSL.html
License: Apache License 2.0
ShortDescription: The Win32/Win64 OpenSSL Installation Project is dedicated to providing a simple installation of OpenSSL for Microsoft Windows.
Moniker: openssl
Tags:
 - openssl
 - tools
 - ssl
Installers: 
 - Architecture: x64
   InstallerType: msi
   InstallerUrl: https://slproweb.com/download/Win64OpenSSL_Light-1_1_1k.msi
   InstallerSha256: CF29DD125D0FFF9A6A0C20A708B89958738A51F6BB1CD8CBD3BB09010F096D92
   ProductCode: "{1D081372-FA6C-42B1-95C6-C837AFAEDF0E}"
ManifestType: singleton
ManifestVersion: 1.0.0
```
And the folder structure should look like this
manifests/s/ShiningLight/OpenSSLLight/1.0.0/ShiningLight.OpenSSLLight.yaml

**Review by auanasgheps — COMMENTED** [review]
Update

**Review by auanasgheps — COMMENTED** [review]
Rename

**Comment by KaranKad** [comment]
I set the package vesion to 1.0.0 because after installing the app that's what it said in the control panel.

**Comment by KaranKad** [comment]
There is one extra .yaml in the file name

**Comment by auanasgheps** [comment]
> I set the package version to 1.0.0 because after installing the app that's what it said in the control panel.

Interesting, they changed something 

In version 1.1.1d which was installed on one of my PCs, it didn't report any version in such field, but only in the name field.
Now the version in the name field is gone, but the package is 1.0.0 as you reported.
Still, I think we need to show the real OpenSSL version otherwise it won't work for updates.

**Comment by KaranKad** [comment]
Winget currently uses app version that is shown in control panel to determine if the app has to update or no, now this app is reported 1.0.0 in control panel but 1.1.1k in manifest. Winget will think this app has update even if it actually does not.
Its related to this issue  [microsoft/winget-cli#980](https://github.com/microsoft/winget-cli/issues/980)

**Comment by auanasgheps** [comment]
> Winget currently uses app version that is shown in control panel to determine if the app has to update or no, now this app is reported 1.0.0 in control panel but 1.1.1k in manifest. Winget will think this app has update even if it actually does not.
> Its related to this issue [microsoft/winget-cli#980](https://github.com/microsoft/winget-cli/issues/980) and [microsoft/winget-cli#976](https://github.com/microsoft/winget-cli/issues/976)

Allright, so we have to choose between always upgrade or never upgrade?

**Pull request merged**
