### PR TITLE
Remove Microsoft.Azd to fix 404

### PR DESCRIPTION
**Pull request by stephengillie**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/152919)

### CODE REVIEW

**Comment by stephengillie** [comment]
This was created to address `winget show Microsoft.Azd` showing 404. Will be readded after.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-05-09T16:51:43.2407072Z Processing manifest: manifests\m\Microsoft\Azd\1.9.100
 2024-05-09T16:51:43.2407793Z -----------------------------------------------------
 2024-05-09T16:51:43.2408373Z Status: Started
 2024-05-09T16:51:43.2408896Z Manifest file is Deleted
 2024-05-09T16:51:43.2409416Z Status: Completed
 2024-05-09T16:51:43.2409934Z ##[error] Result: Failed
 2024-05-09T16:51:43.2435749Z ##[error] Sequence contains no elements
 2024-05-09T16:51:43.2442462Z ##[error]Manifest Validation Failed

(Automated response - build 880.)

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 880.)

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Review by msftrubengu — APPROVED** [review]

**Pull request merged**
