### PR TITLE
Slonopotamus.Stevedore version 0.6.1

### PR DESCRIPTION
**Pull request by slonopotamus**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/58762)

### CODE REVIEW

**Review by OfficialEsco — COMMENTED** [review]
Getting 1603 in Sandbox probably because of some Windows Features
```
Enter a pull request number: 58762

Manifest validation succeeded.
Found Stevedore [Slonopotamus.Stevedore] Version 0.6.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/slonopotamus/stevedore/releases/download/0.6.1/stevedore-0.6.1-x86_64.msi
  ██████████████████████████████   186 MB /  186 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1603
Installer log is available at: C:\Users\WDAGUtilityAccount\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Slonopotamus.Stevedore.0.6.1-2022-04-26-10-25-54.611.log
```

<details>
<summary>Click for Log</summary>
<br>

```
=== Logging started: 4/26/2022  10:26:01 ===
Action start 10:26:01: INSTALL.
Action start 10:26:01: System64Folder.DFEFC2FE_EEE6_424C_841B_D4E66F0C84A3.
Action ended 10:26:01: System64Folder.DFEFC2FE_EEE6_424C_841B_D4E66F0C84A3. Return value 1.
Action start 10:26:01: FindRelatedProducts.
Action ended 10:26:01: FindRelatedProducts. Return value 1.
Action start 10:26:01: LaunchConditions.
Action ended 10:26:01: LaunchConditions. Return value 1.
Action start 10:26:01: ValidateProductID.
Action ended 10:26:01: ValidateProductID. Return value 1.
Action start 10:26:01: CostInitialize.
Action ended 10:26:01: CostInitialize. Return value 1.
Action start 10:26:01: FileCost.
Action ended 10:26:01: FileCost. Return value 1.
Action start 10:26:01: CostFinalize.
Action ended 10:26:01: CostFinalize. Return value 1.
Action start 10:26:01: SetARPINSTALLLOCATION.
Action ended 10:26:01: SetARPINSTALLLOCATION. Return value 1.
Action start 10:26:01: MigrateFeatureStates.
Action ended 10:26:01: MigrateFeatureStates. Return value 0.
Action start 10:26:01: InstallValidate.
Action ended 10:26:01: InstallValidate. Return value 1.
Action start 10:26:01: InstallInitialize.
Action ended 10:26:01: InstallInitialize. Return value 1.
Action start 10:26:01: RemoveExistingProducts.
Action ended 10:26:01: RemoveExistingProducts. Return value 1.
Action start 10:26:01: ProcessComponents.
Action ended 10:26:03: ProcessComponents. Return value 1.
Action start 10:26:03: UnpublishFeatures.
Action ended 10:26:03: UnpublishFeatures. Return value 1.
Action start 10:26:03: StopServices.
Action ended 10:26:03: StopServices. Return value 1.
Action start 10:26:03: DeleteServices.
Action ended 10:26:03: DeleteServices. Return value 1.
Action start 10:26:03: RemoveRegistryValues.
Action ended 10:26:03: RemoveRegistryValues. Return value 1.
Action start 10:26:03: RemoveShortcuts.
Action ended 10:26:03: RemoveShortcuts. Return value 1.
Action start 10:26:03: RemoveEnvironmentStrings.
Action ended 10:26:03: RemoveEnvironmentStrings. Return value 1.
Action start 10:26:03: RemoveFiles.
Action ended 10:26:03: RemoveFiles. Return value 0.
Action start 10:26:03: SetCreateDockerGroup.
Action ended 10:26:03: SetCreateDockerGroup. Return value 1.
Action start 10:26:03: CreateDockerGroup.
Action ended 10:26:03: CreateDockerGroup. Return value 1.
Action start 10:26:03: SetInstallContainersFeature.
Action ended 10:26:03: SetInstallContainersFeature. Return value 1.
Action start 10:26:03: InstallContainersFeature.
Action ended 10:26:03: InstallContainersFeature. Return value 1.
Action start 10:26:03: SetInstallHyperVFeature.
Action ended 10:26:03: SetInstallHyperVFeature. Return value 1.
Action start 10:26:03: InstallHyperVFeature.
Action ended 10:26:03: InstallHyperVFeature. Return value 1.
Action start 10:26:03: SetInstallWSL2Feature.
Action ended 10:26:03: SetInstallWSL2Feature. Return value 1.
Action start 10:26:03: InstallWSL2Feature.
Action ended 10:26:03: InstallWSL2Feature. Return value 1.
Action start 10:26:03: ConfigureUsers.
Action start 10:26:03: CreateUserRollback.
Action ended 10:26:03: CreateUserRollback. Return value 1.
Action start 10:26:03: CreateUser.
Action ended 10:26:03: CreateUser. Return value 1.
Action ended 10:26:03: ConfigureUsers. Return value 1.
Action start 10:26:03: InstallFiles.
Action ended 10:26:03: InstallFiles. Return value 1.
Action start 10:26:03: CreateShortcuts.
Action ended 10:26:03: CreateShortcuts. Return value 1.
Action start 10:26:03: WriteRegistryValues.
Action ended 10:26:03: WriteRegistryValues. Return value 1.
Action start 10:26:03: WriteEnvironmentStrings.
Action ended 10:26:03: WriteEnvironmentStrings. Return value 1.
Action start 10:26:03: InstallServices.
Action ended 10:26:03: InstallServices. Return value 1.
Action start 10:26:03: SchedServiceConfig.
Action start 10:26:03: RollbackServiceConfig.
Action ended 10:26:03: RollbackServiceConfig. Return value 1.
Action start 10:26:03: ExecServiceConfig.
Action ended 10:26:03: ExecServiceConfig. Return value 1.
Action ended 10:26:03: SchedServiceConfig. Return value 1.
Action start 10:26:03: StartServices.
Action ended 10:26:03: StartServices. Return value 1.
Action start 10:26:03: RegisterUser.
Action ended 10:26:03: RegisterUser. Return value 1.
Action start 10:26:03: RegisterProduct.
Action ended 10:26:03: RegisterProduct. Return value 1.
Action start 10:26:03: PublishFeatures.
Action ended 10:26:03: PublishFeatures. Return value 1.
Action start 10:26:03: PublishProduct.
Action ended 10:26:03: PublishProduct. Return value 1.
Action start 10:26:03: InstallFinalize.
WixQuietExec:  Get-LocalGroup : Group docker-users was not found.
WixQuietExec:  At line:1 char:2
WixQuietExec:  + (Get-LocalGroup -Name docker-users) -or (New-LocalGroup -Name docker- ...
WixQuietExec:  +  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WixQuietExec:      + CategoryInfo          : ObjectNotFound: (docker-users:String) , GroupNotFoundException
WixQuietExec:      + FullyQualifiedErrorId : GroupNotFound,Microsoft.PowerShell.Commands.GetLocalGroupCommand
WixQuietExec:   
WixQuietExec:  True
WixQuietExec:  Enable-WindowsOptionalFeature : Systemet finner ikke angitt bane.
WixQuietExec:  At line:1 char:1
WixQuietExec:  + Enable-WindowsOptionalFeature -Online -FeatureName Containers -All -N ...
WixQuietExec:  + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WixQuietExec:      + CategoryInfo          : NotSpecified: (:) , COMException
WixQuietExec:      + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand
WixQuietExec:   
WixQuietExec:  Error 0x80070001: Command line returned an error.
WixQuietExec:  Error 0x80070001: QuietExec Failed
WixQuietExec:  Error 0x80070001: Failed in ExecCommon method
CustomAction InstallContainersFeature returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox)
Action ended 10:26:12: InstallFinalize. Return value 3.
Action ended 10:26:12: INSTALL. Return value 3.
Property(S): DiskPrompt = Stevedore Installation
Property(S): UpgradeCode = {9A68EC9C-B494-4CDD-B081-F074FE91BF0B}
Property(S): InstallContainersFeature = "C:\Windows\sysnative\WindowsPowerShell\v1.0\powershell.exe" -Command "Enable-WindowsOptionalFeature -Online -FeatureName Containers -All -NoRestart"
Property(S): InstallHyperVFeature = "C:\Windows\sysnative\WindowsPowerShell\v1.0\powershell.exe" -Command "Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All -NoRestart"
Property(S): InstallWSL2Feature = "C:\Windows\sysnative\WindowsPowerShell\v1.0\powershell.exe" -Command "Enable-WindowsOptionalFeature -Online -FeatureName 'Microsoft-Windows-Subsystem-Linux;VirtualMachinePlatform' -All -NoRestart"
Property(S): INSTALLDIR = C:\Program Files\Stevedore\
Property(S): bin = C:\Program Files\Stevedore\bin\
Property(S): cli_plugins = C:\Program Files\Docker\cli-plugins\
Property(S): WixUIRMOption = UseRM
Property(S): ALLUSERS = 1
Property(S): CreateDockerGroup = "C:\Windows\sysnative\WindowsPowerShell\v1.0\powershell.exe" -Command "(Get-LocalGroup -Name docker-users) -or (New-LocalGroup -Name docker-users -Description 'Users of Docker Desktop')"
Property(S): ARPINSTALLLOCATION = C:\Program Files\Stevedore\
Property(S): CreateUser = **********
Property(S): CreateUserRollback = **********
Property(S): ExecServiceConfig = SchedServiceConfigstevedore1restartrestartnone160
Property(S): RollbackServiceConfig = SchedServiceConfig
Property(S): ProgramFiles64Folder = C:\Program Files\
Property(S): Docker = C:\Program Files\Docker\
Property(S): TARGETDIR = C:\
Property(S): ProgramMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\
Property(S): DesktopFolder = C:\Users\Public\Desktop\
Property(S): SourceDir = C:\Users\WDAGUtilityAccount\AppData\Local\Temp\WinGet\Slonopotamus.Stevedore.0.6.1\
Property(S): VersionNT = 603
Property(S): SERVICENAME = stevedore
Property(S): DISABLEADVTSHORTCUTS = 1
Property(S): POWERSHELLEXE = C:\Windows\sysnative\WindowsPowerShell\v1.0\powershell.exe
Property(S): ARPPRODUCTICON = stevedore.ico
Property(S): ARPHELPLINK = https://github.com/slonopotamus/stevedore
Property(S): Manufacturer = Marat Radchenko
Property(S): ProductCode = {0C30127C-7450-444A-A909-50C054869DD9}
Property(S): ProductLanguage = 1033
Property(S): ProductName = Stevedore
Property(S): ProductVersion = 0.6.1
Property(S): DefaultUIFont = WixUI_Font_Normal
Property(S): WixUI_Mode = FeatureTree
Property(S): ErrorDialog = ErrorDlg
Property(S): SecureCustomProperties = WIX_DOWNGRADE_DETECTED;WIX_UPGRADE_DETECTED
Property(S): MsiHiddenProperties = CreateUser;CreateUserRollback;RemoveUser
Property(S): System64Folder.DFEFC2FE_EEE6_424C_841B_D4E66F0C84A3 = C:\Windows\system32\
Property(S): DirectoryTable100_amd64.DFEFC2FE_EEE6_424C_841B_D4E66F0C84A3 = DirectoryTable
Property(S): MsiLogFileLocation = C:\Users\WDAGUtilityAccount\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Slonopotamus.Stevedore.0.6.1-2022-04-26-10-25-54.611.log
Property(S): PackageCode = {3C91B561-069B-4130-A9E6-DC0B1C12024F}
Property(S): ProductState = -1
Property(S): PackagecodeChanging = 1
Property(S): REBOOTPROMPT = S
Property(S): REBOOT = ReallySuppress
Property(S): CURRENTDIRECTORY = C:\Users\WDAGUtilityAccount
Property(S): CLIENTUILEVEL = 2
Property(S): CLIENTPROCESSID = 4872
Property(S): VersionDatabase = 500
Property(S): VersionMsi = 5.00
Property(S): VersionNT64 = 603
Property(S): WindowsBuild = 9600
Property(S): ServicePackLevel = 0
Property(S): ServicePackLevelMinor = 0
Property(S): MsiNTProductType = 1
Property(S): WindowsFolder = C:\Windows\
Property(S): WindowsVolume = C:\
Property(S): System64Folder = C:\Windows\system32\
Property(S): SystemFolder = C:\Windows\SysWOW64\
Property(S): RemoteAdminTS = 1
Property(S): TempFolder = C:\Users\WDAGUtilityAccount\AppData\Local\Temp\
Property(S): ProgramFilesFolder = C:\Program Files (x86)\
Property(S): CommonFilesFolder = C:\Program Files (x86)\Common Files\
Property(S): CommonFiles64Folder = C:\Program Files\Common Files\
Property(S): AppDataFolder = C:\Users\WDAGUtilityAccount\AppData\Roaming\
Property(S): FavoritesFolder = C:\Users\WDAGUtilityAccount\Favorites\
Property(S): NetHoodFolder = C:\Users\WDAGUtilityAccount\AppData\Roaming\Microsoft\Windows\Network Shortcuts\
Property(S): PersonalFolder = C:\Users\WDAGUtilityAccount\Documents\
Property(S): PrintHoodFolder = C:\Users\WDAGUtilityAccount\AppData\Roaming\Microsoft\Windows\Printer Shortcuts\
Property(S): RecentFolder = C:\Users\WDAGUtilityAccount\AppData\Roaming\Microsoft\Windows\Recent\
Property(S): SendToFolder = C:\Users\WDAGUtilityAccount\AppData\Roaming\Microsoft\Windows\SendTo\
Property(S): TemplateFolder = C:\ProgramData\Microsoft\Windows\Templates\
Property(S): CommonAppDataFolder = C:\ProgramData\
Property(S): LocalAppDataFolder = C:\Users\WDAGUtilityAccount\AppData\Local\
Property(S): MyPicturesFolder = C:\Users\WDAGUtilityAccount\Pictures\
Property(S): AdminToolsFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\
Property(S): StartupFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\
Property(S): StartMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\
Property(S): FontsFolder = C:\Windows\Fonts\
Property(S): GPTSupport = 1
Property(S): OLEAdvtSupport = 1
Property(S): ShellAdvtSupport = 1
Property(S): MsiAMD64 = 6
Property(S): Msix64 = 6
Property(S): Intel = 6
Property(S): PhysicalMemory = 4095
Property(S): VirtualMemory = 4521
Property(S): AdminUser = 1
Property(S): MsiTrueAdminUser = 1
Property(S): LogonUser = WDAGUtilityAccount
Property(S): UserSID = S-1-5-21-2047949552-857980807-821054962-504
Property(S): UserLanguageID = 1033
Property(S): ComputerName = 3AED435B-D155-4
Property(S): SystemLanguageID = 1044
Property(S): ScreenX = 1024
Property(S): ScreenY = 768
Property(S): CaptionHeight = 23
Property(S): BorderTop = 1
Property(S): BorderSide = 1
Property(S): TextHeight = 16
Property(S): TextInternalLeading = 3
Property(S): ColorBits = 32
Property(S): TTCSupport = 1
Property(S): Time = 10:26:12
Property(S): Date = 4/26/2022
Property(S): MsiNetAssemblySupport = 4.8.4161.0
Property(S): MsiWin32AssemblySupport = 6.3.22000.1
Property(S): RedirectedDllSupport = 2
Property(S): MsiRunningElevated = 1
Property(S): Privileged = 1
Property(S): DATABASE = C:\Windows\Installer\1022eb.msi
Property(S): OriginalDatabase = C:\Users\WDAGUtilityAccount\AppData\Local\Temp\WinGet\Slonopotamus.Stevedore.0.6.1\stevedore-0.6.1-x86_64.msi
Property(S): UILevel = 3
Property(S): MsiUIProgressOnly = 1
Property(S): MsiUIHideCancel = 1
Property(S): ACTION = INSTALL
Property(S): ROOTDRIVE = C:\
Property(S): CostingComplete = 1
Property(S): OutOfDiskSpace = 0
Property(S): OutOfNoRbDiskSpace = 0
Property(S): PrimaryVolumeSpaceAvailable = 0
Property(S): PrimaryVolumeSpaceRequired = 0
Property(S): PrimaryVolumeSpaceRemaining = 0
Property(S): INSTALLLEVEL = 1
Property(S): SOURCEDIR = C:\Users\WDAGUtilityAccount\AppData\Local\Temp\WinGet\Slonopotamus.Stevedore.0.6.1\
Property(S): SourcedirProduct = {0C30127C-7450-444A-A909-50C054869DD9}
Property(S): ProductToBeRegistered = 1
MSI (s) (58:D8) [10:26:12:459]: Product: Stevedore -- Installation failed.

MSI (s) (58:D8) [10:26:12:459]: Windows Installer installerte produktet. Produktnavn: Stevedore. Produktversjon: 0.6.1. Produktspråk: 1033. Produsent: Marat Radchenko. Installasjonens resultatstatus: 1603.

=== Logging stopped: 4/26/2022  10:26:12 ===

```

</details>

**Comment by slonopotamus** [comment]
So, you want to say that CI is no longer capable of `powershell.exe -Command "Enable-WindowsOptionalFeature -Online -FeatureName Containers -All -NoRestart"`?  Something must have broken since https://github.com/microsoft/winget-pkgs/pull/56748

**Comment by OfficialEsco** [comment]
Na the Pipeline passed so its valid, https://github.com/microsoft/winget-pkgs/pull/56748 i validated on my VM so its probably some Sandbox fuckery which is why i left a comment instead of requested changes so other can check it out =)

It speaks Norwegian because of stoopid Sandbox, nothing special other than `Enable-WindowsOptionalFeature: The system does not find the specified path.` which is probably the issue

**Comment by slonopotamus** [comment]
Oh, OK

**Review by ItzLevvie — APPROVED** [review]
VM (Hyper-V):
image

**Review by ghost — APPROVED** [review]

**Pull request merged**
