### PR TITLE
Add Scope Switches to SomePythonThings.WingetUIStore.Pre-release

### LINKED ISSUE #164407: Unable to update UnigetUI prerelease
```
❯ winget update
Name                  Id                     Version     Available   Source
---------------------------------------------------------------------------
UniGetUI (formerly W… SomePythonThings.Wing… 3.1.1-beta1 3.1.1-beta2 winget
1 upgrades available.
```

```
> winget update SomePythonThings.WingetUIStore.Pre-release
No applicable upgrade found.
A newer package version is available in a configured source, but it does not apply to your system or requirements.
```

❯ winget --version
v1.9.1763-preview
[WinGet-2024-07-22-22-42-41.918.log](https://github.com/user-attachments/files/16343078/WinGet-2024-07-22-22-42-41.918.log)

### PR DESCRIPTION
**Pull request by Trenly**
* Resolves #164407
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164770)

### CODE REVIEW

**Comment by Trenly** [comment]
#42616

**Comment by Trenly** [comment]
@stephengillie - this one may need manual review

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
