### PR TITLE
Update locale: Speed-Soft.Pingt version 1.0.0.17

### PR DESCRIPTION
**Pull request by Speed7811**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/154704)

### CODE REVIEW

**Comment by stephengillie** [comment]
I believe the `Agreements` section needs some kind of preparation by the developer - has this been set up?

**Comment by Speed7811** [comment]
Hey,

in my optinion everything was setup. The license page exists and the test with the manifest was exactly that what I excepted. Do you miss something?

Best regards

Rainer

**Comment by Speed7811** [comment]
Sry I don't understand. Please can you explain a little bit more?

**Review by Trenly — COMMENTED** [review]
This change isn't necessary, as the license is already captured in the `LicenseUrl` field, and the package will install just fine without a custom switch. The CLI also states on install that the license is granted by the application owner.

The only reason to add this change would be if you wanted users to explicitly agree to the terms in the license before they could install the application through WinGet. However, they don't need to do this if they just download the exe from the website, so I'm not sure this change makes a lot of sense

**Comment by Speed7811** [comment]
Hey,

in Germany you need (or it is better) to agree the license before you download the binary (says my lawyer). Installing this software by Winget is the only way to get the software. I changed this option explicit because I want to have it - the users must agree the license. Thats what I want.

Additionally Winget explicit provided this option. If I can use this option but the merges are blocked because I don't should use it please remove the option - this make no sense. 

I see other software installed by Winget which need to be agreeed... So please merge this PR.

Thank you!

Rainer

**Comment by stephengillie** [comment]
Sorry for the delay - I've reached out internally for guidance on next steps.

**Review by denelon — APPROVED** [review]

**Pull request merged**
