### PR TITLE
Add Microsoft OneNote Desktop

### PR DESCRIPTION
**Pull request by DevSecNinja**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/941)

### CODE REVIEW

**Comment by Cloudenius** [comment]
Fails because of #91.

**Comment by Cloudenius** [comment]
Unfortunately the same error @ashpatil-msft.

**Comment by DevSecNinja** [comment]
Have to cancel this PR as the OneNote URL is not reliable. It randomly returns `OfficeSetup.exe` and `setuponenotefreeretail.x64.en-us_.exe` with different SHA-256 hashes:

PwshOneNoteScreenshot

**Pull request closed without merging**
