### PR TITLE
PyPy.PyPy.3.9 version 7.3.11

### LINKED ISSUE #23460: Package request: Pypy
# Package Requested

- [x] I would like someone else to build the manifest.
- [x] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**: The Pypy Team

**Publisher Url**: https://www.pypy.org/people.html (I guess)

**Package Name**: Pypy

**Package Url**: https://www.pypy.org/index.html

**Description**: A fast, compliant alternative implementation of Python

**Package Version**: v7.3.5

**Installer URL**: https://www.pypy.org/download.html

### PR DESCRIPTION
**Pull request by kimwonj77**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

It's my first contribution. and also please check my comment https://github.com/microsoft/winget-pkgs/pull/97132#issuecomment-1435498429

Fixes #23460

Edit: Blocked by https://github.com/microsoft/winget-cli/discussions/3056#discussioncomment-5258709 (Validation-Defender-Error) and microsoft/winget-cli#2711

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/97132)

### CODE REVIEW

**Comment by kimwonj77** [comment]
@microsoft-github-policy-service agree

**Comment by kimwonj77** [comment]
Since windows PyPy distribution doesn't sign their execution files, Installer fails on Archive scan. (Detect malware.)

Also, alias symlink is correctly generated, but doesn't work on terminal. 
Double-click the symlink on `%LocalAppData%\Microsoft\WinGet\Links` in Explorer shows smart defender warning and it works with it however.

**Comment by kimwonj77** [comment]
Note: I just searched other prs and found that there's dependency issue.It neeeds `VS2015+`. 

However, there's other issue which i mentionded earlier. I dont know why symlink doesnt work with termnial but windows explorer.

**Comment by stephengillie** [comment]
Hi @kimwonj77,

> Since windows PyPy distribution doesn't sign their execution files, Installer fails on Archive scan. (Detect malware.)

Unfortunately, packages must pass a Defender scan to be included in the WinGet public manifests.

**Comment by kimwonj77** [comment]
Interesting is, I can't detect any malwares in zip file. Nor [VirusTotal](https://www.virustotal.com/gui/file/57faad132d42d3e7a6406fcffafffe0b4f390cf0e2966abb8090d073c6edf405/detection/f-57faad132d42d3e7a6406fcffafffe0b4f390cf0e2966abb8090d073c6edf405-1673136435), [MetaDefender](https://metadefender.opswat.com/results/url/aHR0cHM6Ly9kb3dubG9hZHMucHl0aG9uLm9yZy9weXB5L3B5cHkzLjktdjcuMy4xMS13aW42NC56aXA=/overview), and Microsoft Defender on my machine. Only winget says 'Malware Detected'
Is winget just rejected this because of they didn't signed files?

**Comment by kimwonj77** [comment]
Note: https://github.com/microsoft/winget-cli/discussions/3056#discussioncomment-5258709

**Comment by kimwonj77** [comment]
Also seems like blocked by https://github.com/microsoft/winget-cli/issues/2711 (which related to can't launch with command line)

**Comment by stephengillie** [comment]
> Interesting is, I can't detect any malwares in zip file. Nor [VirusTotal](https://www.virustotal.com/gui/file/57faad132d42d3e7a6406fcffafffe0b4f390cf0e2966abb8090d073c6edf405/detection/f-57faad132d42d3e7a6406fcffafffe0b4f390cf0e2966abb8090d073c6edf405-1673136435), [MetaDefender](https://metadefender.opswat.com/results/url/aHR0cHM6Ly9kb3dubG9hZHMucHl0aG9uLm9yZy9weXB5L3B5cHkzLjktdjcuMy4xMS13aW42NC56aXA=/overview), and Microsoft Defender on my machine. Only winget says 'Malware Detected' Is winget just rejected this because of they didn't signed files?

The package *does* pass a Defender scan in a VM.

**Review by stephengillie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
