### PR TITLE
New version: Amazon.Kindle version 2.3.70673

### LINKED ISSUE #136763: [Update Request]: Kindle
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Amazon.Kindle

### Package Version

2.3.0

### Please describe the changes you would like to see

Version 2.3.0 is available but winget still offers version 2.0.1

### PR DESCRIPTION
**Pull request by Exorcism0666**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

- Resolve: #136763

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136765)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification.
>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

> This PR's version number 2.3.70673 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 2.0.1.70350, which has 4 parameters.

Is this intentional?

(Automated response - build 674)

**Comment by Exorcism0666** [comment]
@stephengillie Yes!

**Review by stephengillie — APPROVED** [review]

**Comment by FrankConrads** [comment]
Hi all,

it seems that the update is **not working properly** as there might be a confusion: @Exorcism0666  @stephengillie 

Current version seems to be with 4 digits, while the change is reflecting only 3 of 'em. 

About-Dialog says:
Bild_2024-01-30_210350090

Installer-Name says:
KindleForPC-installer-**2.3.70673**.exe

```
Name                                                   ID                            Version     Verfügbar Quelle
-----------------------------------------------------------------------------------------------------------------
Amazon Kindle                                          Amazon.Kindle                 2.3.0.70673 2.3.70673 winget


```

> Hi @Exorcism0666,
> 
> > This PR's version number 2.3.70673 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 2.0.1.70350, which has 4 parameters.
> 
> Is this intentional?
> 
> (Automated response - build 674)

> @stephengillie Yes!

**Pull request merged**
