### PR TITLE
Improve Tencent.QQ 9.7.1.28929 URLs

### PR DESCRIPTION
**Pull request by StarsbySea**
Related to [[New Feature]: Replace dldir1.qq.com with dldir1v6.qq.com for Improved IPv6 Support #116525](https://github.com/microsoft/winget-pkgs/issues/116525)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/117018)

### CODE REVIEW

**Comment by StarsbySea** [comment]
It's downloading fine on my end. Please try again.

**Comment by stephengillie** [comment]
> Installer Verification Analysis Context Information: 
Error occurred while downloading installer from https://dldir1v6.qq.com/qqfile/qq/PCQQ9.7.1/QQ9.7.1.28929.exe. 0x80072EE2.
Error information: 
Http Response: OK
Http Reason Phrase: OK

**Comment by stephengillie** [comment]
Hi @StarsbySea,

Unfortunately, it seems that the IPv6 address cannot be reached from our data centers.

**Comment by StarsbySea** [comment]
Can I try again? Sometimes if you are the first person to download from a nearby CDN, the download may fail and simply trying again can solve the problem.

**Comment by stephengillie** [comment]
> Can you try again? Sometimes if you are the first person to download from a nearby CDN, the download may fail and simply trying again can solve the problem.

This isn't normal behavior from a CDN. The cache miss should trigger a proxy call to the source, and the main call should wait for the source response to cache. But here it sounds as though the main call is erroring while waiting for the cached call. 

I'm concerned that this behavior might present a poor user experience, if users frequently receive an error from WinGet when being the first download from the nearby CDN. This is the second issue with the IPv6 version of this host.

**Pull request closed without merging**
