### PR TITLE
add missing vcredist dependencies for keepassxc

### PR DESCRIPTION
**Pull request by mdonoughe**
KeePassXC depends on the VC redist package but the manifest doesn't declare the dependency. This leads to missing DLLs if you perform an installation on a fresh Windows installation.

This partially fixes ~~keepassxreboot/keepassxc#9773~~ keepassxreboot/keepassxc#7564. KeePassXC is also available in the Windows store, and the Windows store version has the same problem. I don't know how to fix the Windows store version.

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/122990)

### CODE REVIEW

**Comment by mdonoughe** [comment]
Is there a way the validation can detect problems like this? I don't know anything about how the package validation works, but there is a command line interface to keepassxc and I assume running a simple test like creating an empty password database with the cli would fail with a non-zero exit code if any DLLs were missing.

**Comment by mdonoughe** [comment]
I don't think we need to create 6 PRs to make the same change to 6 versions of the same package which all have the same manifest problem.

**Comment by stephengillie** [comment]
Hi @mdonoughe,

We have a 1 manifest change per PR limit. So unfortunately, you'll have to create 5 additional PRs.

**Comment by mdonoughe** [comment]
I think making six PRs that are essentially the same is a moral issue since that'd be 3/4 Hacktoberfest PRs. I'll just fix the latest for now.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
