### PR TITLE
Update manifest: Fork.Fork version 1.90.1

### LINKED ISSUE #130752: [Package Issue]: Fork.Fork installer download link broken
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When trying to install Fork via `winget install --id=Fork.Fork -e`, I get the following error:

```
Downloading https://git-fork.com/update/win/ForkInstaller.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).
```

### Steps to reproduce

Run `winget install --id=Fork.Fork -e

### Actual behavior

I get an error message

### Expected behavior

It should install Fork

### Environment

```raw
Windows Package Manager v1.6.3421
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.2861
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3421.0
```

### Screenshots and Logs

_No response_

### PR DESCRIPTION
**Pull request by Dragon1573**
## Description

Old version of the manifest is outdated and the vanity-like `InstallerUrl` response HTTP 404.

Renew the manifest on `InstallerUrl` property. The official team of this package has changed their download server to a CDN-like, version related URL. 

- Resolve #130752

## Checks

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/130779)

### CODE REVIEW

**Comment by ricardoboss** [comment]
Wait so you're removing Fork.Fork altogether? Can't we just update the installer download URLs?

**Comment by Dragon1573** [comment]
> Can't we just update the installer download URLs?

I can't find the valid download URL of this exact version. Download page of this package is providing a newer version. No "archives for old versions" are provided on that site. 😞

I can make help if I get the valid URL.

**Comment by ricardoboss** [comment]
> ...
> I can make help if I get the valid URL.

The current download URL is https://cdn.fork.dev/win/Fork-1.91.2.exe

Obtained from https://fork.dev/

**Comment by ricardoboss** [comment]
Through trial and error, I found that the URL scheme also supports other versions:

- 1.90.1: https://cdn.fork.dev/win/Fork-1.90.1.exe

So we could just update the URL in the installer for that version instead of removing it, right?

**Comment by Dragon1573** [comment]
> Through trial and error, I found that the URL scheme also supports other versions:
> 
> - 1.90.1: https://cdn.fork.dev/win/Fork-1.90.1.exe

Okay, I'll try if it's valid.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
