### PR TITLE
Update version: Microsoft.PowerShell.Preview version 7.4.0.5

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/117820)

### CODE REVIEW

**Comment by CoolPlayLin** [comment]
I think this PR needs Powershell Team's approval

CC @anamnavi

**Comment by anamnavi** [comment]
@CoolPlayLin @vedantmgoyal2009 is there something wrong with the original PR for this version already merged in for this? #117714

**Review by stephengillie — APPROVED** [review]

**Comment by anamnavi** [comment]
@stephengillie why did we merge this in over changes for this version already in master?

**Comment by anamnavi** [comment]
@stephengillie no worries I understand you're looking at big batches of PRs.

Can we revert this change? I notice the main (non-metadata) changes are that this PR adds a `DisplayName` that's incorporating architecture and an `UpgradeCode` field that we've never included before- what could these changes mean for a user upgrading? If it's non-trivial changes I suppose we can keep this..

**Comment by stephengillie** [comment]
> @stephengillie no worries I understand you're looking at big batches of PRs.
> 
> Can we revert this change? I notice the main (non-metadata) changes are that this PR adds a `DisplayName` that's incorporating architecture and an `UpgradeCode` field that we've never included before- what could these changes mean for a user upgrading? If it's non-trivial changes I suppose we can keep this..

@anamnavi I'm willing, but we don't really have a process for reverting the PR. I'll start manually creating a branch and PR to revert this change.

**Comment by anamnavi** [comment]
I see, if it's easier I can open a PR with my changes again and update this package version with that. Would that be easier/better?

**Comment by stephengillie** [comment]
> I see, if it's easier I can open a PR with my changes again and update this package version with that. Would that be easier/better?

Yes, please.

**Comment by anamnavi** [comment]
> > I see, if it's easier I can open a PR with my changes again and update this package version with that. Would that be easier/better?
> 
> Yes, please.

Here's the PR for updating it: https://github.com/microsoft/winget-pkgs/pull/117893

**Pull request merged**
