### PR TITLE
Added Epiforge Grindstone 4.0.7380.29440

### PR DESCRIPTION
**Pull request by BigBadBleuCheese**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1857)

### CODE REVIEW

**Comment by BigBadBleuCheese** [comment]
I have checked for all of these issues to the best of my ability. I cannot see what is wrong.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
