### PR TITLE
Add ElectronicArts.Origin 10.5.70.40362

### PR DESCRIPTION
**Pull request by cilerler**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/561)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
This installs correctly, but I am not sure what the user experience is supposed to be.  I ran the executable and nothing appeared to happen.  Can you  elaborate for me?

**Comment by cilerler** [comment]
Not sure what do you mean by nothing happened.  It installs the client, and then you need to run Origin application from the Start menu, and it will ask you your EA credentials.

image

**Comment by cilerler** [comment]
@KevinLaMS anything I may do to accept this PR?

**Review by ghost — APPROVED** [review]
Validation has completed

**Review by mddtest — COMMENTED** [review]
Wrong program this is EA Desktop not the EA origin app

**Pull request merged**
