### PR TITLE
New version: pnpm.pnpm version 7.26.3

### PR DESCRIPTION
**Pull request by russellbanks**

### CODE REVIEW

**Comment by sitiom** [comment]
Duplicate of #95215

**Comment by russellbanks** [comment]
> Duplicate of #95215

Thanks for letting me know @sitiom - hadn't realised pnpm was being automated now. This PR does have more metadata (you can add that to the other PR if you want) but I'll close in favour of that one. WinGet Releaser intends to use Komac as a backend in the near future so it will have the extra metadata later on.

**Comment by sitiom** [comment]
The only extra field I see here is the `ReleaseNotes`, but it would be great to have extra metadata

**Comment by russellbanks** [comment]
> The only extra field I see here is the `ReleaseNotes`, but it would be great to have extra metadata

1.4.0 Schemas are being accepted now, but that's not mandatory to change; WinGet Releaser still creates 1.2.0 schemas currently. The Release Notes would be nice to add though :)

**Pull request closed without merging**
