### PR TITLE
7.Zip.7-Zip version 21.02 alpha

### PR DESCRIPTION
**Pull request by ExpertStatue**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14498)

### CODE REVIEW

**Comment by Cheesepuff1** [comment]
i have accept the terms already

**Comment by KaranKad** [comment]
Don't submit something that is already here [21.02-alpha](https://github.com/microsoft/winget-pkgs/tree/master/manifests/7/7zip/7zipAlpha/21.02-alpha)

**Comment by Cheesepuff1** [comment]
well seems like got to try something else

**Comment by NicTanghe** [comment]
seems to not add the install location to the environment variables.

**Pull request closed without merging**
