### PR TITLE
Add 7+ Taskbar Tweaker v5.9

### PR DESCRIPTION
**Pull request by m417z**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2200)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Can you push another change? the bot bugged out.
Also won't the publisher be Rammichael? Then all your Software can be under rammichael\softwarename

**Comment by m417z** [comment]
@OfficialEsco done, thanks.

**Review by ghost — APPROVED** [review]
Validation has completed

**Comment by KyleMit** [comment]
The app doesn't install with

```bash
winget install --id=rammichael.7+TaskbarTweaker -e
```

screenshot won't install


And I can't find the application with any of the following searches

```bash
winget search taskbar
winget search tweaker
winget search rammichael
```

screenshot empty search

```bash 
winget -v
# v0.1.41331 Preview
```

**Pull request merged**
