### PR TITLE
New package: JakobHellermann.Atlas version 1.2.0.0

### PR DESCRIPTION
**Pull request by jakobhellermann**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150846)

### CODE REVIEW

**Comment by 2505lis** [comment]
https://sites.google.com/view/ano-center-gemini25

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files (x86)\Atlas\atlas.exe returned exit code: -1073741515

(Automated response - build 877.)

**Comment by stephengillie** [comment]
Hi @jakobhellermann,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 877.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-04-25 10:54:56.965 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF9CC3CC11F: (caller: 00007FF9CC158D6F) LogHr(1) tid(690) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF9CC2D2B08: (caller: 00007FF9CC37BC20) Exception(1) tid(690) 8A15005E ] 
> 2024-04-25 10:54:56.965 [REPO] Failed to open available source: msstore
> 2024-04-25 10:55:08.685 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF9AB2BC11F: (caller: 00007FF9AB048D6F) LogHr(1) tid(19c4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF9AB1C2B08: (caller: 00007FF9AB26BC20) Exception(1) tid(19c4) 8A15005E ] 
> 2024-04-25 10:55:08.687 [REPO] Failed to open available source: msstore
> 2024-04-25 10:55:49.849 [FAIL] Installer failed security check. Url: https://github.com/jakobhellermann/Atlas/releases/download/1.2.0/Atlas.msi Result: 0x80004005

(Automated response - build 877.)

**Comment by stephengillie** [comment]
Hi @jakobhellermann,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 877.)

**Comment by stephengillie** [comment]
Verify: 
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
