### PR TITLE
New version: Transmission.Transmission version 4.0.4

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/118341)

### CODE REVIEW

**Comment by babblebauble** [comment]
Can a moderator not approve this pull request? Installation is failing because this package has a dependency on Microsoft Visual C++ Redistributable. Previous versions were being approved despite failing the installer validation.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335226 
2023-09-08 14:36:27.098 [CLI ] ShellExecute installer failed: 1603 Property(S): ErrorDialog = ErrorDlg 
MSI (s) (68:94) [14:36:26:884]: Product: Transmission 4.0.4 (24077e3511) (x64) -- Installation failed. 
MSI (s) (68:94) [14:36:26:884]: Windows Installer installed the product. Product Name: Transmission 4.0.4 (24077e3511) (x64). Product Version: 4.0.4. Product Language: 1033. Manufacturer: Transmission Project. Installation success or error status: 1603. 
2023-09-08 14:36:13.467 [CLI ] ShellExecute installer failed: 1603 
MSI (s) (A0:20) [14:36:13:354]: Product: Transmission 4.0.4 (24077e3511) -- Installation failed. MSI (s) (A0:20) [14:36:13:354]: Windows Installer installed the product. Product Name: Transmission 4.0.4 (24077e3511). Product Version: 4.0.4. Product Language: 1033. Manufacturer: Transmission Project. Installation success or error status: 1603. 

- 1603 sometimes indicates a missing dependency.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
