### PR TITLE
New package: Certiport,aPearsonVUEBusiness.CertiportCompass version 19.0.2.1270

### PR DESCRIPTION
**Pull request by ldriskell**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135757)

### CODE REVIEW

**Comment by ldriskell** [comment]
@microsoft-github-policy-service agree [company="{default}"]

**Comment by ldriskell** [comment]
@microsoft-github-policy-service agree

**Comment by ldriskell** [comment]
@microsoft-github-policy-service agree company="default"

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-02-12 15:20:26.483 [CLI ] During package install, 0 changes to ARP were observed, 0 matches were found for the package, and 0 packages were in both 

(Automated response - build 729.)

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
Close with reason: Stale pull request;

**Pull request closed without merging**
