### PR TITLE
Move RARLab.WinRAR version 7.01 to RARLab.WinRAR version 7.01.0

### PR DESCRIPTION
**Pull request by MaanuelMM**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/157012)

### CODE REVIEW

**Review by stephengillie — DISMISSED** [review]

**Comment by stephengillie** [comment]
I approved thinking there would only be a few installers. This changes quite a few from the removal PR:

- Removed from https://github.com/microsoft/winget-pkgs/pull/157013
8C7B2DA1B0F8AF3BFE0A502540160FBAACBE2D0578D6644C12470C64BDFC9099
3ECDD455BA754196581C7D503408B6AB43AD3BAAF6D66B7838AFECAB4EF28920
C5B5DEF1C8882B702B6B25CBD94461C737BC151366D2D9EBA5006C04886BFC9A
A911BBFAB70C7545307B9DBCB06273D899CA03AAD928F0B66D55B41C25CB4F14
163D5489AD7D0A14AC606B02CF4FACF0955B877F33CD2ED38BA36DCE367F7C1E
B92E17D31D6C876E5174C5D0569132C7CB804A8B8D41E278724878DA0470BC38
CD316C877FA39662343DA30A57C63292941EC0ED90A2ADF61129746391BB4065
512CC03FB45C577B2FD824105D56D8EC98CA0D541A737E97B97421CE87F5C365
14E187389BCBDAE52D6A1F80F3518E1FAF8842E7DE2313C073A23437AB61B1A6
60F8DB4F216A06CAF803F66719D97DD4AB422E4D813A3BCBA5BEAAE8D70BF258
24E91784FD0F759116A131B53AF6C8D53B7AE2E1843ECF70E294372A7CAA4A66
BBB0B1F66147D1A156756774357A450ABFF57F803D167F7F69E80F37BBAD685B
622A58577768A7C611F1302697CF86B450343C9ED169B655F1AEFBE456F2337D
8C251241EE36971EA84D3B6DC44F1571397992026BFB14CC4B23D9C5B50D73C1
2177FCC6C2105A01472358AD32A5CE467B4943D69F891CB30BBC82EC42003C60
4D350D66C70100C6F1DB64A012EFCA7FAD39069F083CAACC116F8B1CFAD85CCF
7821F9D85301D59F8D4354FA4D8F203D53300579F1314BD2F0EF09FC18D69AE6
757CEFAC4B0F0CD9DB00A12159009FF5BD8AEAD83F5FD30C9D445F21D25D4B55
D2BF05E837546A5DA35317D1B9C8AEAA98F82AD94BA1137AE2D10BEE6FC8143C
90816F7444951BF9F38C004B0BBFD8BCB504F56B36DF3E1C5EF74083627901EF

- Added here
B8954C14B581AC3EA5EE8FF76CD0405C2118186A53416E20C44D7B253A3EF7A4
347D7ABCD9D9098D1244E53C602CCF0646EB3A364CEC610818D669372F6592BB
BF66FF1181EC95A383BCEFBAF28388230AE77AADC656ED0AC5FEC6B8197AFB95
DBED3A9FB4DE3E247EA22299C565EAECF938F87EE4F2F6269E41B96318159682
809914E4F48DB53F9D8186A09937EB1059FC021439ED27C08AB6D614B37F5A8E
09BFA088FCE1750B4E318554C1229F6A21BDCB33DC352BBF102F2967645CB236
1A47ED2D0983D32CB76AE8FBD98A0A13C9E1FE55D6D73764847F19E579DCE5F6
3982EA59622F7DD78688D74A6875CE4780578C378A99E358A0C72DC385C9BE2E
31F7BA37180F820313B2D32E76252344598409CB932109DD84A071CD58B64AA6
503D7256AB2198B774C91DA1E100960B40D333BCBD1DF0BCAEA68CFED3F2599E
B095499B67ED79E5453CBD25F17EB6E87880400B01B82817F4333C7E2718BE24
04BDED6D1F16AE4C7040EEC827AB0CA4DD3500290A96223B756D1FFAFD8777CC
7B61649A7D98EAA48DB67805100F64CC84EE601AAFD8BF99DE468564F09F6DD4
85C9B388F4F50B1DD53AD38500C1C273A6ADD1C580683078DC403B79872AAC66
0D5E1CD0C197D400EA4C49712285DA9743D1619F1B08DF39173D2A49DC86039C
B3B905779EDD332D4AC368AF508A487A22C08F4AAC660F102A30538AC445195F
3102A19D430B017C2259C5B26A9624C2CEC30FD0EA987E79815730972B0CC3D8
AFC443D4EEB503D77C917C9EA2EE6183D11ACD6587EB8BDB36C1741E8828B61F
B497A39703349C0954B3EBAF09F94AB5EA7C0D8FB3298720B57703D6E1A7422E
83E6AA87CAE3964C666FFC79C6C6939504D7632FD0A2ADAB39E526DCC46B4F91
BE71A7A029BF55DB1FE2CF4BCEEFD5098F2AA1E2577D9A61BB60AB2C5EA164AA
3D308B0DB5184570F52674EAE55D058132D64843FFBAB5D8691304FFC2EA818C
448B443AE6DFDF35FF85630F00986C1AB27CA64CAAD404420F963037D13AAFE2
F980DFD664AF5960E9D3EEE3A83E2FF99D98095A659030A1E2E129AA90CFC1DC
34C8597E07E4624ED67A41E4214487D6AA8DCFFDFE044DBAC7AD495BF4509268
80D19EBFE76AEA3209C81D1582B18D4BFAC446587C14D4DD19686AAD659D2720
395C53A12B01F861824E69545A1518FF14E47FD9BEB9BE8BCAC0CA3812C1A4E3
1F8CAB4C6C81C2E1FC988E85F0EDE7B7149E240AA3AB34734101F72BC4DC1401
C055E6624EAB73B83A7B66A79B30DA9DF9E4E0D35011C0DB88B2180DCECB9801
D3E3DF5181B91A3871609458B4581482B3F8F8640860FE9994AFDE0B7F92D3C3
9AF5544F6397A5AC13EDD4196C3CE933921E88F8E5379658545D4B41902EE408
40725930E0D34948C7581C8B50F9A211D1AB8D907FEA88429013876CF17C51FA
37D4030F070D1FDD440D189EF030A212CA3D81635721A73EEEEEB944AF928F1F
F325E1E893EC8F7C4C9F91FDB0D17FE538233F54AE05DF4A183F52A2DF4ED28C
228DF2EB5A248748C3EDC03FFE751F7BAA4DF16708765A97D7BE60DF2DFB88D5
C7F2C53BFABE33124DBCAF86E0C267CF57F79890688677727A35D974DD2571B3
E74815ABF10E741599F12D40EA902E948F1A864A364ACF9017887EF253727D56
66F1865167F673A1E5216C20F795C55A862547EDD1804DAB111E689AE3CD3DE5

**Comment by MaanuelMM** [comment]
I've autogenerated this YAML installer manifest from rarlab.com (the developers of the WinRAR product) instead of win-rar.com (one of the authorized distributors), so it may have some hash changes for some local installers. Sorry for the inconvenience as I did this change without realizing it (my intention was simply to "fix" the version of the software manifest by changing it from 7.01 to 7.01.0 as it appears in the ARP entries).

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-06-07 15:17:16.977 [FAIL] Installer failed security check. Url: https://www.rarlab.com/rar/winrar-x64-701tc.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 884.)

**Comment by stephengillie** [comment]
Sorry for the delay. `wingetbot run` wasn't listening to due to:

> Octokit was broken because comment id exceeded int maximum value for parsing JSON. A fix was submitted earlier, but we haven't got a NuGet package yet[.] 

- [@denelon on Gitter](https://matrix.to/#/!LEwByvxhTNZZcKeCCY:gitter.im/$c5J6uL4eU3A1Sy9vsPbUgBSahjnfLz6TDh98ZeW56G4?via=gitter.im&via=matrix.org&via=beeper.com)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
