### PR TITLE
Nelson 1.4.0.4010

### PR DESCRIPTION
**Pull request by Nelson-numerical-software**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/151447)

### CODE REVIEW

**Comment by Nelson-numerical-software** [comment]
Hi,
Can you give more information about trouble ?
With previous 1.3.0, application was manually reviewed on your side

I would like fix trouble on my side if it is possible.

Thanks

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-04-29 01:20:21.095 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFD2CA9C11F: (caller: 00007FFD2C828D6F) LogHr(1) tid(720) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFD2C9A2B08: (caller: 00007FFD2CA4BC20) Exception(1) tid(720) 8A15005E ] 
> 2024-04-29 01:20:21.095 [REPO] Failed to open available source: msstore
> 2024-04-29 01:20:29.945 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFD10F3C11F: (caller: 00007FFD10CC8D6F) LogHr(1) tid(1900) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFD10E42B08: (caller: 00007FFD10EEBC20) Exception(1) tid(1900) 8A15005E ] 
> 2024-04-29 01:20:29.945 [REPO] Failed to open available source: msstore
> 2024-04-29 01:20:31.301 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x64 with version 14.38.33135.0
> 2024-04-29 01:19:23.952 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!67A5535B: (caller: 67951A80) LogHr(1) tid(268) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!67A9B5DD: (caller: 67B312BF) Exception(1) tid(268) 8A15005E ] 
> 2024-04-29 01:19:23.952 [REPO] Failed to open available source: msstore
> 2024-04-29 01:19:30.601 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!5448535B: (caller: 54381A80) LogHr(1) tid(b18) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!544CB5DD: (caller: 545612BF) Exception(1) tid(b18) 8A15005E ] 
> 2024-04-29 01:19:30.601 [REPO] Failed to open available source: msstore
> 2024-04-29 01:19:31.823 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x86 with version 14.38.33135.0

(Automated response - build 877.)

**Comment by Nelson-numerical-software** [comment]
and ? @stephengillie 
"No suitable installer found for manifest Microsoft.VCRedist.2015+.x86 with version 14.38.33135.0"
in NelsonNumericalSoftware.Nelson.installer.yaml
lin 21   - PackageIdentifier: Microsoft.VCRedist.2015+.x64   used ?
What need to change here ?

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/issues/149642

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
