### PR TITLE
Added MysqlShell 8.1.1

### PR DESCRIPTION
**Pull request by fabiang**
New updated PR of previous #47644 with dependencies defined in manifest file.

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?
- [x] Have you tested your manifest locally with `winget install --manifest <path> --silent`?
- [x] Have you tested your manifest locally with `winget remove --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path> --silent`?

Note: the [MySQL Shell documentation says](https://dev.mysql.com/doc/mysql-shell/8.1/en/mysql-shell-install.html):

> For the Community and Commercial versions of MySQL Shell: Before installing MySQL Shell, make sure you have the **Visual C++ Redistributable for Visual Studio 2015** (available at the [Microsoft Download Center](http://www.microsoft.com/en-us/download/default.aspx)) installed on your Windows system.

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/120090)

### CODE REVIEW

**Comment by Trenly** [comment]
Looks like this is getting stuck on dependencies, since the feature is not yet released as stable

**Review by Trenly — CHANGES_REQUESTED** [review]

**Comment by denelon** [comment]
Yes, it's not getting through validation until we have the dependency support included in the validation pipelines. We're expecting the WinGet 1.6 client to be released at the end of the month. It will likely take a couple of weeks after that for >50% of clients to be updated, and then we'll begin validation with dependencies in earnest.

**Comment by fabiang** [comment]
1.6 is ready, so can we run the pipelines again?

**Comment by denelon** [comment]
The pipelines are paused while we make some updates. Once they are re-enabled, the validation can be re-run.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335226 
2023-09-18 06:32:58.953 [CLI ] ShellExecute installer failed: 1603 Property(S): ErrorDialog = ErrorDlg 
MSI (s) (BC:F8) [06:32:58:557]: Product: MySQL Shell 8.1.1 -- Installation failed. 
MSI (s) (BC:F8) [06:32:58:572]: Windows Installer installed the product. Product Name: MySQL Shell 8.1.1. Product Version: 8.1.1. Product Language: 1033. Manufacturer: Oracle and/or its affiliates. Installation success or error status: 1603.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
