### PR TITLE
New version: Datadog.Agent version 7.50.0

### PR DESCRIPTION
**Pull request by BiosPlus**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131383)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @BiosPlus,

> Current manifest version 7.45.1.1 has 4 parameters, which is greater than this PR's version number 7.50.0's 3 parameters.

Is this intentional?

(Automated response - build 487)

**Comment by stephengillie** [comment]
Hi @BiosPlus,

This manifest adds Apps and Features entries that aren't present in previous PR versions. Should these entries be added to the previous versions also?

(Automated response - build 487.)

**Comment by stephengillie** [comment]
Hi @BiosPlus,

> Current manifest version 7.45.1.1 has 4 parameters, which is greater than this PR's version number 7.50.0's 3 parameters.

Is this intentional?

(Automated response - build 487)

**Comment by stephengillie** [comment]
Hi @BiosPlus,

This manifest adds Apps and Features entries that aren't present in previous PR versions. Should these entries be added to the previous versions also?

(Automated response - build 487.)

**Comment by BiosPlus** [comment]
The Apps and features entry are just an upgrade code and version number, which are presumably being used for tracking future upgrades when deployed via MSI

**Comment by stephengillie** [comment]
Hi @BiosPlus,

> This PR's version number 7.50.0 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 7.45.1.1, which has 4 parameters.

Is this intentional?

(Automated response - build 489)

**Comment by stephengillie** [comment]
Hi @BiosPlus,

This manifest adds Apps and Features entries that aren't present in previous PR versions. Should these entries be added to the previous versions also?

(Automated response - build 489.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
