### PR TITLE
Package changes for Adoptium Temurin binaries 🧪

### PR DESCRIPTION
**Pull request by d3vel0per**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----
Proposed changes change in package due to:
1) Vendor name change from `Eclipse Foundation` to `Eclipse Adoptium`
2) Product name change from `AdoptOpenJDK` to `Temurin`

This will probably break what is allowed in a single PR ie. multiple manifests and move instead of add/delete but since this is just metadata changes I am hoping a moderators blessing will get this through

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/28737)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
We moderators can't do anything because it requires Validation-Completed, the Administrators do not Approve PRs. Since this is just  18 files you should be able to submit the PR's pretty quickly tho, instead of waiting forever for MAYBE a Administrator to Approve.

**Comment by d3vel0per** [comment]
> We moderators can't do anything because it requires Validation-Completed, the Administrators do not Approve PRs. Since this is just 18 files you should be able to submit the PR's pretty quickly tho, instead of waiting forever for MAYBE a Administrator to Approve.

Added additional 12 PR's as requested. I see the delete ones are getting merged first though. I expected the ones that added to go in first.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/28737#issuecomment-927264963

@denelon also said that merging a PR with a lot of file deletions or file moves breaks the publishing pipelines when merged, which is why one PR per package is better suited for now.

**Comment by d3vel0per** [comment]
All 12 related PR's merged. Closing this.

**Pull request closed without merging**
