### PR TITLE
Add Schema Header

### PR DESCRIPTION
**Pull request by Trenly**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/83966)

### CODE REVIEW

**Comment by Trenly** [comment]
Needs-Attention

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
@Trenly The installer fails a Defender scan with the message: "This program displays deceptive product messages."

**Comment by Trenly** [comment]
> @Trenly The installer fails a Defender scan with the message: "This program displays deceptive product messages."

I'm confused as to how it made it into the repo in the first place then?

**Comment by stephengillie** [comment]
Package fails Defender scan.

**Comment by Trenly** [comment]
> Package fails Defender scan.

@stephengillie - Does the package need to be removed from the repo entirely then?

**Comment by denelon** [comment]
At least this version should be removed if we're getting a Defender failure.

**Pull request closed without merging**
