### PR TITLE
KeepItSafe.SugarSync version 4.1.0.2

### PR DESCRIPTION
**Pull request by cezarandreescu**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15915)

### CODE REVIEW

**Comment by cezarandreescu** [comment]
Can a Dev look into this please? Installer fails with exit code: 1223, but the program is successfully being installed in the background.

**Comment by denelon** [comment]
@cezarandreescu if 1223 is indeed a success code you can add that to the manifest.

https://github.com/microsoft/winget-cli/blob/34c25ead5010fdea7fb8d245e7b4ff4aa1e8361b/schemas/JSON/manifests/v1.0.0/manifest.installer.1.0.0.json#L135

**Comment by cezarandreescu** [comment]
@denelon 1223 is also the exit code returned if the user denies the UAC prompt, so adding that to the manifest will generate other issues on the long run. Any other suggestions?

**Comment by denelon** [comment]
@cezarandreescu well, that's unfortunate. This might be an opportune time for you to reach out as a customer/user and ask them to take a look at the Windows Package Manager, and their installer stack. We are attempting to meet ISVs/Publishers where they are with the Windows Package Manager, but there are benefits to ideally MSIX or MSI installers as opposed to .exe based installers.

They could certainly look at just generating different exit codes for different scenarios, and providing some documentation for customers as to what those error codes mean. We are not trying to force anyone to make changes, or change their preferred technology stack. The Windows Package Manager is new, and this will take all of us working together to build the best end to end experiences for our customers.

**Pull request closed without merging**
