### PR TITLE
[PHP] Add PHP 8.0, 8.1, 8.2, and 8.3

### PR DESCRIPTION
**Pull request by Ayesh**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? Yes, #56226 and #58422

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/147354)

### CODE REVIEW

**Comment by Ayesh** [comment]
@microsoft-github-policy-service agree [company="PHPWatch"]

**Comment by Ayesh** [comment]
@microsoft-github-policy-service agree

**Comment by Ayesh** [comment]
@microsoft-github-policy-service agree company="PHPWatch"

**Comment by Ayesh** [comment]
The manifest proposes to add *four* manifests, but all for the `PHP.PHP` package. 
I'm one of the volunteers at the PHP Foundation (https://thephp.foundation/structure/), and hoping to add PHP to Winget. 

I'm working on to build the manifests [automatically](https://github.com/PHPWatch/php-winget-manifest), but for now, I'm going to manually submit new updates for the next two-three versions.

**Comment by mdanish-kh** [comment]
[Policy] zip-binary

`php.exe` is not a statically linked binary. It relies on `.dlls` being referenced properly present in the archive, something WinGet cannot do properly in all environments. See bot's comment below for more details

**Comment by Kasparsu** [comment]
Any progress on this its been several months already.

**Comment by mdanish-kh** [comment]
@Kasparsu The blocking issue https://github.com/microsoft/winget-cli/issues/2711 has been resolved. We would be accepting these types of packages when WinGet 1.9 is made stable (it has had 2 RC releases, so that _should be pretty soon_) and when schema version 1.9 is rolled out

**Comment by Kasparsu** [comment]
> @Kasparsu The blocking issue [microsoft/winget-cli#2711](https://github.com/microsoft/winget-cli/issues/2711) has been resolved. We would be accepting these types of packages when WinGet 1.9 is made stable (it has had 2 RC releases, so that _should be pretty soon_) and when schema version 1.9 is rolled out

Good to know I have been wanting to install pure php and composer from winget since it came out ;P I can finally be happy ;P

**Comment by Trenly** [comment]
@Ayesh - Support for zipped binaries has now been added and is available in the pipelines. This will require you to update your submission to ManifestVersion: 1.9.0 and set ArchiveBinariesDependOnPath: true in the installer node. To keep things clean, this PR is being closed. Please submit a new PR for the latest version of this package. Thank you for your contributions!

**Comment by Ayesh** [comment]
Thank you for the heads-up, and zip support is a great news! 
I will submit a new PR soon.

**Pull request closed without merging**
