### PR TITLE
Syncthing.Syncthing version 1.23.2

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/106246)

### CODE REVIEW

**Comment by stephengillie** [comment]
This package had an error during install: 
```
2023-05-09 13:56:45.219 [CLI ] Symlink target does not match ARP Entry. Expected:  Actual: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\Syncthing.Syncthing__DefaultSource\syncthing-windows-amd64-v1.23.2\syncthing.exe
2023-05-09 13:56:45.219 [CLI ] Portable file has been modified: C:\Users\User\AppData\Local\Microsoft\WinGet\Links\syncthing.exe

```

**Comment by upintheairsheep** [comment]
Hi

**Comment by upintheairsheep** [comment]
> This package had an error during install:
> 
> ```
> 2023-05-09 13:56:45.219 [CLI ] Symlink target does not match ARP Entry. Expected:  Actual: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\Syncthing.Syncthing__DefaultSource\syncthing-windows-amd64-v1.23.2\syncthing.exe
> 2023-05-09 13:56:45.219 [CLI ] Portable file has been modified: C:\Users\User\AppData\Local\Microsoft\WinGet\Links\syncthing.exe
> ```

Make an Issue to Syncthing

**Comment by upintheairsheep** [comment]
> This package had an error during install:
> 
> ```
> 2023-05-09 13:56:45.219 [CLI ] Symlink target does not match ARP Entry. Expected:  Actual: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\Syncthing.Syncthing__DefaultSource\syncthing-windows-amd64-v1.23.2\syncthing.exe
> 2023-05-09 13:56:45.219 [CLI ] Portable file has been modified: C:\Users\User\AppData\Local\Microsoft\WinGet\Links\syncthing.exe
> ```

Try see if the behavior is expected

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
