### PR TITLE
Add BingWallpaper

### PR DESCRIPTION
**Pull request by Reset816**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1213)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
syntax error, mail to yao

**Comment by yao-msft** [comment]
> syntax error, mail to yao

The InstallerType in the manifest is incorrect, it’s not an inno installer. Since the manifest does not declare its own Silent and SilentWithProgress switches, the BingWallPaper.exe failed with our default Inno type SilentWithProgress parameter “/silent”.

Fix: Please use exe as InstallerType and add Silent and SilentWithProgress switches with proper values.

**Comment by Reset12138** [comment]
> > syntax error, mail to yao
> 
> The InstallerType in the manifest is incorrect, it’s not an inno installer. Since the manifest does not declare its own Silent and SilentWithProgress switches, the BingWallPaper.exe failed with our default Inno type SilentWithProgress parameter “/silent”.
> 
> Fix: Please use exe as InstallerType and add Silent and SilentWithProgress switches with proper values.

Strange, the interface looked like inno or installshield, and if it is one of them, it should work.#1161
 
image

However, if i use exe as InstallerType add Silent and SilentWithProgress with the value "\Q"(which it tell me), it failed too.
image

image
what value should i add?

**Comment by yao-msft** [comment]
> syntax error, mail to yao
> 
> The InstallerType in the manifest is incorrect, it’s not an inno installer. Since the manifest does not declare its own Silent and SilentWithProgress switches, the BingWallPaper.exe failed with our default Inno type SilentWithProgress parameter “/silent”.
> Fix: Please use exe as InstallerType and add Silent and SilentWithProgress switches with proper values.
> 
> Strange, the interface looked like inno or installshield, and if it is one of them, it should work.#1161
> 
> However, if i use exe as InstallerType add Silent and SilentWithProgress with the value "\Q"(which it tell me), it failed too.
> 
> 
> what value should i add?

Regarding InstallShield support, unfortunately we don't have full support for automatic handling of InstallShield type yet, as InstallShield can be built as both exe and msi. And we don't support installer config files like for .iss to be used with InstallShield yet. So currently, InstallShield installers need to declare exe or msi type in the manifest respectively.

But regardless of the above, I took a quick look at the BingWallpaper.exe and I could not relate it to inno or Installshield immediately. Here is what I found. The exe manifest says it's IExpress extraction tool. It indicates this exe is a self extract archive. So I renamed the exe to .cab and it can be successfully extracted. In the cab, there's a exe and msi. By examining the extracted installer exe, I did not find specific installer info in exe resources.

Anyway, the BingWallpaper.exe and the underlying installer does not accept default inno or installer switches, so it's appropriate to use exe type for it. The /Q switch is irrelevant here since it's a switch for IExpress archive, not the underlying installer. I tried a couple of commonly used silent switches and passed to the underlying BWInstaller.exe like _BingWallpaper.exe /Q /C:"BWInstaller.exe /quiet"_ but unfortunately none of them does unattended installation.

Currently we require all installers support unattended installation. If the BingWallPaper installer does not support it(or maybe we did not find correct args for it), we'll have to put this installer on hold for now(we can revisit this in the future when we can handle interactive-only packages appropriately).

Yao

**Comment by KevinLaMS** [comment]
Unfortunately this installer with the /Q switch fails.  We are going to need to have the path for supporting non-silent installs.

**Pull request closed without merging**
