### PR TITLE
Add MySQL Workbench Community

### PR DESCRIPTION
**Pull request by Loupeznik**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/12351)

### CODE REVIEW

**Comment by denelon** [comment]
@Loupeznik I added the "Blocking-Issue" and "Dependency" labels to this PR, so the work to generate the manifest doesn't have to be completely redone.

**Comment by denelon** [comment]
@Loupeznik I'm working on the specification for dependencies. Do you know what dependencies are for this package?

**Comment by Loupeznik** [comment]
@denelon Hi, the package seems to depend on .NET Framework 4.5.2 and Microsoft Visual C++ 2015-2022 Redistributable as per the provided documentation.

**Review by ItzLevvie — APPROVED** [review]

**Comment by licon4812** [comment]
@denelon  @ItzLevvie 
Is this request still active or am I free to have a crack at getting MySQL workbench added?

**Comment by ItzLevvie** [comment]
I think it still requires dependency support which will take a while to go out of experimental features and then added to the pipelines.

**Comment by entreprenr** [comment]
https://cdn.mysql.com//Downloads/MySQLGUITools/mysql-workbench-community-8.0.31-winx64.msi

Does this installer require any dependencies? It seems to install without asking anything (but maybe the dependency is already installed on my machine) ...

**Comment by Trenly** [comment]
* Resolved by #119555

**Pull request closed without merging**
