### PR TITLE
New version: Elgato.CameraHub version 1.3.1.600

### PR DESCRIPTION
**Pull request by mdanish-kh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/79410)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
Uhoh, might have triggered bot protection

```
2022-09-12 10:55:48.795 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(64)\WindowsPackageManager.dll!00007FF851240B70: (caller: 00007FF851240F29) Exception(4) tid(2334) 80190193 Forbidden (403).

    Msg:[Download request status is not success.] 
```

**Comment by mdanish-kh** [comment]
> Uhoh, might have triggered bot protection
> 
> ```
> 2022-09-12 10:55:48.795 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(64)\WindowsPackageManager.dll!00007FF851240B70: (caller: 00007FF851240F29) Exception(4) tid(2334) 80190193 Forbidden (403).
> 
>     Msg:[Download request status is not success.] 
> ```

Can you please elaborate? I don't have a clue 😅

**Comment by OfficialEsco** [comment]
> Can you please elaborate? I don't have a clue sweat_smile

the bot is seeing a Forbidden return code when trying to access the website which often indicates DDOS protection from bots.

**Comment by ItzLevvie** [comment]
@msftbot reset feedback

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
Close with reason: Replaced by PR 87235;

**Pull request closed without merging**
