### PR TITLE
403: KDE.Kate version 21.08.0

### LINKED ISSUE #26945: Automation has determined KDE.Kate 21.08.0 is unavailable
The URL for version 21.08.0 of KDE.Kate has been unavailable for 5 or more days.
This package may be removed from the repository if no valid manifest is available in the next 14 days.

If the installer has been moved, please update the manifest with the new URL. If a new version of the package is available, please create a new manifest with the valid URL, version, and SHA256 hash.
If this package is no longer available, please delete the manifest.

```

```

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

Resolves #26945

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
Resolves #26945

**Review by ItzLevvie — APPROVED** [review]

**Review by quhxl — APPROVED** [review]

**Comment by vedantmgoyal2009** [comment]
The bot has died like before.

**Review by ItzLevvie — APPROVED** [review]

**Review by ImJoakim — APPROVED** [review]

**Comment by ImJoakim** [comment]
Worth a shot

**Comment by vedantmgoyal2009** [comment]
Permanently died, till winget team fix it.

**Comment by vedantmgoyal2009** [comment]
On my PR #26960, the old label of unattended failed did not get removed and new labels got added.

**Comment by vedantmgoyal2009** [comment]
@denelon please introduce a badge for @wingetbot and @msftbot like https://github.com/microsoft/winget-pkgs/pull/26961#issuecomment-912924176

**Review by ItzLevvie — APPROVED** [review]
test

**Comment by vedantmgoyal2009** [comment]
I guess they must be changing something in the bot. We should wait for them.

**Comment by vedantmgoyal2009** [comment]
Has anyone noticed that @msftbot does not add the "Microsoft Reviewers" tag in the PR comments as it did before? Both bots have died.

**Review by ImJoakim — APPROVED** [review]

**Comment by denelon** [comment]
@vedantmgoyal2009 feel free to create an issue to add badges for the bots. I'm not sure how we'll verify they are behaving, but I think it's a good one for us to look at.

**Review by ImJoakim — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
