### PR TITLE
Added Remote Desktop version 1.2.2322.0.

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

------

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/28409)

### CODE REVIEW

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
I will submit a full Manifest overhaul to your repo soon

**Comment by OfficialEsco** [comment]
For some reason Microsoft disabled the silent switch for current user installation so the change only includes x86 and arm64...
@denelon would you be able to relay this to someone? 🤔 Or answer why its disabled?

**Comment by jedieaston** [comment]
I duplicated the installer with `Scope: User` and it installed silently fine for me.

image

**Comment by OfficialEsco** [comment]
Well, did it install to `C:\Users\Username\AppData\Local\Apps\Remote Desktop` without a UAC prompt? 🤔 (obv can't test that in sandbox D:)
According to Orca and my testing ALLUSERS=2 does not exist

**Comment by jedieaston** [comment]
Aha! You also have to pass the `MSIINSTALLPERUSER=1` variable too. 

https://docs.microsoft.com/en-us/windows-server/remote/remote-desktop-services/clients/windowsdesktop-admin#per-user-installation

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
