### PR TITLE
New version: DelineaInc.ThycoticAgent version 12.0.1016

### PR DESCRIPTION
**Pull request by jnichols35**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/147534)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Installer https://tmsnuget.thycotic.com/software/Agents/ThycoticAgent_x86_12_0_1016.msi
 Scan request id: '63647743-8808-4acd-ad3c-3d3262b653bd'
 
 Installer https://tmsnuget.thycotic.com/software/Agents/ThycoticAgent_x64_12_0_1016.msi
 Scan request id: '7aa9ff37-6eaa-4ccf-be85-686f59bc7a8d'
 Error information: BlockingDetectionFound
 
 4/4/2024 4:19:02 PM
 
 ****************************************************************************************

(Automated response - build 876.)

**Comment by stephengillie** [comment]
This might be due to a network block of data centers, to prevent automated downloads.

(Automated response - build 876.)

**Comment by jnichols35** [comment]
@stephengillie I take it there isn't much I can do about this since I'm not the software author?

**Comment by stephengillie** [comment]
Hi @jnichols35,

Unfortunately, yes. This is usually something the software developer would have to address with their website host or ISP.

**Pull request closed without merging**
