### PR TITLE
Update metadata/Add `Scope`: namazso.OpenHashTab version v3.0.1

### PR DESCRIPTION
**Pull request by quhxl**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/21601)

### CODE REVIEW

**Comment by quhxl** [comment]
@palenshus Can you take a look?

**Comment by quhxl** [comment]
It again installs fine on my x86 machine but doesn't pass the pipline...

**Review by OfficialEsco — APPROVED** [review]

**Comment by OfficialEsco** [comment]
This was a weird error tho as it got `Validation-Executable-Error` and `Validation-No-Executables`, but yeah i don't trust the x86 VM as it fails a lot

**Comment by quhxl** [comment]
@OfficialEsco I just stumbled across this. I am assuming that the "v" in the version name does not make this version show as the newest. Is there anything we can do about this? or is this to be related to the way the CLI works?

Screenshot 2021-08-02 123112

**Comment by OfficialEsco** [comment]
I've seen this before, i believe there is a issue on winget-cli about it, is the older version actually 2.3.0 or v2.3.0?

**Comment by quhxl** [comment]
It is actually 2.3.0...

**Comment by OfficialEsco** [comment]
ouch that sucks, i guess we can cheese it by naming it v2.3.0 if its the only version?
or wait for schema v1.1.0

**Pull request merged**
