### PR TITLE
Microsoft.VisualStudioCode: enable "open with code" context menu items by default

### PR DESCRIPTION
**Pull request by soredake**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/106718)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
The Visual Studio Code engineering team uses a hardcoded manifest in its automation which means that the changes in this pull request will be reverted in the next manifest submission by the Visual Studio Code engineering team.

You will need to contact the Visual Studio Code engineering team if you would like to make any changes to the manifest.

**Comment by soredake** [comment]
> You will need to contact the Visual Studio Code engineering team

How can i do this?

**Comment by denelon** [comment]
I'll reach out to the Visual Studio Code team. 😊

**Comment by stephengillie** [comment]
Hi @lszomoru,

We have a request to enable some context menus when installing. Are you okay with these changes?

**Comment by denelon** [comment]
I'm a little hesitant to include this unless @lszomoru thinks this is a good idea.

Optionally, we could add Install Notes to display additional instructions if it's possible to do this another way.

**Comment by soredake** [comment]
This pr will probably never be merged so i created this https://github.com/microsoft/vscode/issues/198519

**Comment by soredake** [comment]
In case someone is not voted yet on this https://github.com/microsoft/vscode/issues/198519 issue, please do so, we need 8 more votes to make them consider this for backlog.

**Comment by denelon** [comment]
The earlier request to upvote is:
* https://github.com/microsoft/vscode/issues/134470

**Comment by denelon** [comment]
I'm going to go ahead and close this PR since it's for an earlier version and it's the older schema version. I've reached out to @lszomoru internally to discuss making the change upstream.

**Comment by denelon** [comment]
@soredake I spoke with the VSCode team. It looks like they have had challenges with the "send to" and are looking at adding the option to the command pallette rather than the installer. They deliver the product to both the Microsoft Store and WinGet, and the option isn't available currently in the Microsoft Store.

**Pull request closed without merging**
