### PR TITLE
Add Armagetron Advanced

### PR DESCRIPTION
**Pull request by Calinou**
[Armagetron Advanced](http://www.armagetronad.org/) is a 3D multiplayer game with Tron-style lightcycles.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/826)

### CODE REVIEW

**Comment by chausner** [comment]
Blocked by https://github.com/microsoft/winget-pkgs/issues/523.

**Comment by Calinou** [comment]
This PR is still valid, it's just blocked by #523.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
