### PR TITLE
Remove: LeadDeskLtd.LeadDesk version 9.90.0

### PR DESCRIPTION
**Pull request by coolplaylinbot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/151426)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: - https://www.leaddesk.com/download-files/LeadDesk_Setup_9.90_voip.msi 
Invalid URI: The URI scheme is not valid.

(Automated message - build 818)

**Comment by stephengillie** [comment]
Hi @coolplaylinbot,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 877.)

**Comment by stephengillie** [comment]
URL: https://www.leaddesk.com/download-files/LeadDesk_Setup_9.90_voip.msi 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 877)

**Comment by stephengillie** [comment]
URL: https://www.leaddesk.com/download-files/LeadDesk_Setup_9.90_voip.msi 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 878)

**Comment by stephengillie** [comment]
URL: https://www.leaddesk.com/download-files/LeadDesk_Setup_9.90_voip.msi 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 880)

**Comment by stephengillie** [comment]
URL: https://www.leaddesk.com/download-files/LeadDesk_Setup_9.90_voip.msi 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 880)

**Comment by CoolPlayLin** [comment]
@CoolPlayLinBot Close with #152222

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
