### PR TITLE
New version: creativeprojects.resticprofile version 0.26.0

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140273)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 776.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-20 13:58:56.659 [CLI ] Installer [X64,portable,Unknown,en-US] not applicable: Machine is not compatible with X64 2024-02-20 13:58:56.659 [CLI ] Installer [Arm64,portable,Unknown,en-US] not applicable: Machine is not compatible with Arm64 2024-02-20 13:59:05.908 [FAIL] Installer failed security check. Url: https://github.com/creativeprojects/resticprofile/releases/download/v0.26.0/resticprofile_0.26.0_windows_386.zip Result: 0x80004005 2024-02-20 13:59:05.908 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6

(Automated response - build 776.)

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 776.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-20 13:58:56.659 [CLI ] Installer [X64,portable,Unknown,en-US] not applicable: Machine is not compatible with X64 2024-02-20 13:58:56.659 [CLI ] Installer [Arm64,portable,Unknown,en-US] not applicable: Machine is not compatible with Arm64 2024-02-20 13:59:05.908 [FAIL] Installer failed security check. Url: https://github.com/creativeprojects/resticprofile/releases/download/v0.26.0/resticprofile_0.26.0_windows_386.zip Result: 0x80004005 2024-02-20 13:59:05.908 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6

(Automated response - build 776.)

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 812.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-21 12:27:18.628 [CLI ] Installer [X64,portable,Unknown,en-US] not applicable: Machine is not compatible with X64 2024-02-21 12:27:18.628 [CLI ] Installer [Arm64,portable,Unknown,en-US] not applicable: Machine is not compatible with Arm64 2024-02-21 12:27:28.634 [FAIL] Installer failed security check. Url: https://github.com/creativeprojects/resticprofile/releases/download/v0.26.0/resticprofile_0.26.0_windows_386.zip Result: 0x80004005 2024-02-21 12:27:28.634 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6

(Automated response - build 812.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 812.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 813.)

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
