### PR TITLE
Update VideoLAN.VLC.installer.yaml

### PR DESCRIPTION
**Pull request by disko**
Fix wrong DisplayVersion.

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/61421)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
VLC nightly builds already have the issue fixed so it's better to wait until the next stable build release.

`DisplayVersion` in the manifest currently does nothing (at least the last time I checked which was a few months ago)

**Comment by disko** [comment]
Then what's the reason for this, when 3.0.17.4 **is already** installed?

```
> winget upgrade

Name             ID              Version    Verfügbar    Quelle
---------------------------------------------------------------
VLC media player VideoLAN.VLC    3.0.17.0   3.0.17.4     winget
```

You can run `winget upgrade VideoLAN.VLC` as many times as you like, it always stays the same…

**Comment by ItzLevvie** [comment]
> Then what's the reason for this, when 3.0.17.4 **is already** installed?
> 
> ```
> > winget upgrade
> 
> Name             ID              Version    Verfügbar    Quelle
> ---------------------------------------------------------------
> VLC media player VideoLAN.VLC    3.0.17.0   3.0.17.4     winget
> ```
> 
> You can run `winget upgrade VideoLAN.VLC` as many times as you like, it always stays the same…

This is due to a bug in VLC (MSI) installers where all 3.0.17.x (MSI) installers are considered as 3.0.17.0 rather than their proper patch levels.

`Verfügbar` comes from the Control Panel's Add or Remove Programs (ARP) so 3.0.17.0 will be displayed in your Control Panel.

`Quelle` comes from the WinGet package repository (winget-pkgs) so `3.0.17.4` comes from `PackageVersion` in the WinGet package repository (winget-pkgs) and will be shown in `winget upgrade` in the `Quelle` section.

PackageVersion was set to `3.0.17.4` to allow people to upgrade to newer versions of VLC to stay up-to-date with bug fixes. It does create upgrade loops but we have no choice since newer 3.0.17.x releases fixes a critical bug that some people encountered.

This will be fixed in newer VLC builds.

**Comment by disko** [comment]
Alright, thanks for the explanation and sorry for the noise!

**Pull request closed without merging**
