### PR TITLE
New package: Files-Community.Files version 3.3.0.0

### PR DESCRIPTION
**Pull request by schembriaiden**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/146185)

### CODE REVIEW

**Comment by vikingnope** [comment]
I do believe this is an interactive installer, so maybe this can be blocked for now?

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 873.)

**Comment by vikingnope** [comment]
I do not believe that there is

**Comment by Danik1601** [comment]
@vikingnope

https://github.com/files-community/Files/issues/8653#issuecomment-2065365048

**Comment by vikingnope** [comment]
@stephen gillie, is there anyways we can run this command with winget?

`Add-AppxPackage -AppInstallerFile https://cdn.files.community/files/stable/Files.Package.appinstaller`

**Pull request closed without merging**
