### PR TITLE
New package: Snowflake.OdbcDriver version 3.1.4

### LINKED ISSUE #106533: [Package Request]: Snowflake ODBC Driver
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: 
    - Instructions https://docs.snowflake.com/en/developer-guide/odbc/odbc-windows
    - Download https://developers.snowflake.com/odbc/
Publisher: Snowflake
Package Name: snowflake-odbc (this matches what they offer for "yum" in linux)
Description: Driver for connecting to Snowflake using Open Database Connectivity (ODBC) and using SQL for accessing the data.
Package Version: 2.25.11
Installer URL: 
    - 64-bit https://sfc-repo.snowflakecomputing.com/odbc/win64/2.25.11/snowflake64_odbc-2.25.11.msi
    - 32-bit https://sfc-repo.snowflakecomputing.com/odbc/win32/2.25.11/snowflake32_odbc-2.25.11.msi

If available in winget, it would be helpful to display a message after a successful installation to direct the user to the configuration documentation available at https://docs.snowflake.com/en/developer-guide/odbc/odbc-parameters which is required for utilizing the installed driver.

### PR DESCRIPTION
**Pull request by Dragon1573**
## Description

- Resolve #106533

## Checks

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/130780)

### CODE REVIEW

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> According to [the documentation](https://docs.snowflake.com/en/developer-guide/odbc/odbc-windows#step-2-configure-the-odbc-driver), users should configure the ODBC driver in _ODBC Data Source_ setting panel. This package does not provide any "executable entrance".

**Comment by Trenly** [comment]
[Policy] Needs Attention

**Comment by stephengillie** [comment]
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
