### PR TITLE
Update version: miurahr.aqtinstall version 3.1.5

### PR DESCRIPTION
**Pull request by russellbanks**
### Pull request has been created with [Komac](https://github.com/russellbanks/Komac) v1.6.0 :lemon:

Publisher added signed executables to this release.

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/106442)

### CODE REVIEW

**Comment by stephengillie** [comment]
This package is expecting arguments:
```
usage: aqt [-h] [-c CONFIG]
           {install-qt,install-tool,install-doc,install-example,install-src,list-qt,list-tool,list-doc,list-example,list-src,install,tool,doc,examples,src,help,version}
           ...

Another unofficial Qt Installer.
aqt helps you install Qt SDK, tools, examples and others

optional arguments:
  -h, --help            show this help message and exit
  -c CONFIG, --config CONFIG
                        Configuration ini file.
...
```

**Comment by russellbanks** [comment]
> This package is expecting arguments:

I'm a bit confused - isn't that expected for a CLI?

**Comment by stephengillie** [comment]
> > This package is expecting arguments:
> 
> I'm a bit confused - isn't that expected for a CLI?

It might be returning a non-zero exit code, due to lack of arguments. I think there might be a `Commands` field in the manifest to supply these. I try to note these, for future reference, when giving a waiver.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
