### PR TITLE
New package: anatawa12.vrc-get version 1.7.1

### PR DESCRIPTION
**Pull request by anatawa12**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/146966)

### CODE REVIEW

**Comment by anatawa12** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\anatawa12.vrc-get__DefaultSource\vrc-get.exe returned exit code: 2
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\vrc-get.exe returned exit code: 2

(Automated response - build 876.)

**Comment by anatawa12** [comment]
It's expected to `vrc-get` exits with 2 if no arguments are passed. with `--version` or `--help`, exits with zero.

**Comment by stephengillie** [comment]
Thanks for the awareness. This is something of a known issue with our pipelines, especially for CLI applications.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
