### PR TITLE
Update PyCharm to 2020.3.3

### PR DESCRIPTION
**Pull request by abdonmorales**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----
Instead of using the build number, we will be. using the marketing version from JetBrains

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15763)

### CODE REVIEW

**Comment by abdonmorales** [comment]
Fixes #15318

**Comment by OfficialEsco** [comment]
Noooo this is reverting the fix that got merged 3 days ago

image

image

**Comment by abdonmorales** [comment]
But the rest of the appplications of JetBrains uses the marketing version compared to the build version

**Comment by OfficialEsco** [comment]
> But the rest of the applications of JetBrains uses the marketing version compared to the build version

Then there might be a few broken manifests

JetBrains.PyCharm.Professional is also broken
image

**Comment by abdonmorales** [comment]
@OfficialEsco Ill fix most of the broken manifests for all of the JetBrains application, Ill do it later since I have class rn

**Comment by abdonmorales** [comment]
@OfficialEsco Which versioning scheme do we use? The marketing or build?

**Comment by OfficialEsco** [comment]
> @OfficialEsco Which versioning scheme do we use? The marketing or build? for JetBrains

You NEED to use the one Windows sees, otherwise you will break `winget upgrade`. Marketing versions will be added later.

**Comment by abdonmorales** [comment]
Okay, got I will start working on converting most of the JetBrains applications to build versioning

**Comment by OfficialEsco** [comment]
Quick tip: if you rename the folder + `PackageVersion` you do not have to submit 1 PR for creation and 1 for deletion aslong as you work inside that `PackageIdentifier`.

**Pull request closed without merging**
