### PR TITLE
Enterbrain.RGSS-RTPStandard version 1.04

### PR DESCRIPTION
**Pull request by Masamune3210**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/27326)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by ChuckFerring** [comment]
What is the expected install location of this application?

**Comment by Masamune3210** [comment]
C:\Program Files (x86)\Common Files\Enterbrain\RGSS\Standard is the default location

**Comment by ChuckFerring** [comment]
The only application I see appears to be an uninstaller (unins000). Is that the only application that this installs?

**Comment by Masamune3210** [comment]
It installs runtime libraries for a game engine, so I would imagine the only exe would be a uninst, yeah

**Pull request merged**
