### PR TITLE
Submitting ContainerDesktop version 1.0.0-beta.11

### PR DESCRIPTION
**Pull request by erwinkersten**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/38146)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
`Installer failed with exit code: 1`

**Comment by erwinkersten** [comment]
@OfficialEsco, @wingetbot 
Container Desktop requires that Virtualization Extensions are enabled for the machine/vm where it is installed on. 
Container desktop will enable the  WindowsFeatures _"VirtualMachinePlatform"_ and _"Microsoft-Windows-Subsystem-Linux"_  during installation. If Virtualization Extensions are not enabled on the machine/vm (and this seems to be the case on the WinGetSVC-Validation VM's) the installation of these features will fail.

When Virtualization Extensions is enabled (winget installation will perform as expected): 
image

When Virtualization Extensions are **NOT** enabled the winget installation of Container Desktop will exit with code 1: This now happens in the Azure Devops pipeline at the WinGetSvc-Validation step):  

image

This behavior is expected.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Looks like it's blocked by Windows Feature dependency support: https://github.com/microsoft/winget-cli/blob/master/schemas/JSON/manifests/v1.1.0/manifest.installer.1.1.0.json#L231-L241

WinGet currently doesn't support dependencies yet; except for Package Dependencies which are in development builds of WinGet.

**Comment by erwinkersten** [comment]
@ItzLevvie thanks - Container Desktop will enable the Windows Features on the Windows OS as part of the installation (if they are not enabled yet) -> for this is doesn't rely on the feature dependency support of WinGet (its part of the exe installation).  The package works as long as you have Virtualization support (that's by default enabled in every bios/physical machine, but not by default on Virtual machines where the WinGetSvc Installation validation is executed) 

@anybody who knows: 
Is there a way to get the logs / output of the WinGetSc-Validation Installation Test (so that is can confirm my hypothesis).?

@anybody who knows:  
Help: What is the process to get this application package merged?  The packages is correct but it fails the automatic installation as the VM don't have the Virtualization Extensions enabled

**Comment by ItzLevvie** [comment]
> thanks - Container Desktop will enable the Windows Features on the Windows OS as part of the installation (if they are not enabled yet) -> for this is doesn't rely on the feature dependency support of WinGet (its part of the exe installation). The package works as long as you have Virtualization support (that's by default enabled in every bios/physical machine, but not by default on Virtual machines where the WinGetSvc Installation validation is executed)

Ah okay,

> Is there a way to get the logs / output of the WinGetSc-Validation Installation Test (so that is can confirm my hypothesis).?

At the moment, no.

Closest you will get to is Windows Sandbox?

> Help: What is the process to get this application package merged? The packages is correct but it fails the automatic installation as the VM don't have the Virtualization Extensions enabled

Pull Request needs to have a green label.

All PRs have to go through VM tests.

**Comment by OfficialEsco** [comment]
Is this not correct?
image

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/38146#issuecomment-997403469

**Comment by erwinkersten** [comment]
@OfficialEsco I tested this in a Hyper-V VM on which in enabled the virtualization extensions on the vCPU with the command: 
```powershell
Set-VMProcessor -VMName <VMName> -ExposeVirtualizationExtensions $true
```
It looks like you are testing this with a VM in VirtualBox.  If you also have Hyper-V enabled on you host then the VT-X/AMD-V setting will not be enabled on you test VM. You can either test it with Hyper-V VM or on you host with the ```Set-VMProcessor -VMName <VMName> -ExposeVirtualizationExtensions $true```  OR  you can disable Hyper-V temporary with ```bcdedit /set hypervisorlaunchtype off``` and reboot to test again in Virtualbox (restart VM), after testing you can enable Hyper-v again with ```bcdedit /set hypervisorlaunchtype auto```


but in any case - the automatic pipeline validation will fail as this is not enabled on the test-agent-servers :-(

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> but in any case - the automatic pipeline validation will fail as this is not enabled on the test-agent-servers :-(

Unfortunately, there's not much we can do to solve this.

For now, you'll likely have to close this PR and wait until the client & pipeline evolve.

**Pull request closed without merging**
