### PR TITLE
Microsoft.VisualStudio.2022.Community-Preview version 17.5.0

### PR DESCRIPTION
**Pull request by edwardskrod**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://api.github.com/repos/microsoft/winget-pkgs/pulls/95530)

### CODE REVIEW

**Comment by edwardskrod** [comment]
@denelon Please kick off new run.

**Comment by edwardskrod** [comment]
@denelon I'm not sure what's going on here.  These were created using wingitcreate update.   Looks like they timed out.  (88 minutes to validate?)

Could I have permission to rerun these? 



****************************************************************************************
Installation Verification
****************************************************************************************

-----------------------------------------------------
Failed
-----------------------------------------------------
Status: Completed

**Comment by edwardskrod** [comment]
> @wingetbot run

Thanks so much Levvie. It looks like I don't have permission to kick off the runs.

**Review by ItzLevvie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
