### PR TITLE
Add wireshark v3.4.5

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

I don't know why, but the download takes FOREEEEEEEEVER
-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/11334)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Wireshark got some trashy download servers, might be a bit hard to validate 3 installers when they all got a decent chance of timing out...

**Comment by OfficialEsco** [comment]
```
URI: https://www.wireshark.org, Validation result: Failed, Http status code: 521 
URI: https://gitlab.com/wireshark/wireshark/-/issues, Validation result: Passed
URI: https://www.wireshark.org, Validation result: Failed, Http status code: 521 
URI: https://github.com/wireshark/wireshark/blob/master/COPYING, Validation result: Passed
URI: https://www.wireshark.org/download/win64/all-versions/Wireshark-win64-3.4.5.msi, Validation result: Passed
URI: https://www.wireshark.org/download/win32/all-versions/Wireshark-win32-3.4.5.msi, Validation result: Passed
URI: https://www.wireshark.org/download/win64/all-versions/Wireshark-win64-3.4.5.exe, Validation result: Passed
```

Seems like their website is broken, its up again now tho

**Comment by zachcarp** [comment]
@KevinLaMS or @denelon - Didn't know if I should remove the labels on this. Validation passed.

**Pull request merged**
