### PR TITLE
CheatEngine.CheatEngine version 7.5.0

### PR DESCRIPTION
**Pull request by tomatotxt**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/108055)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
> Please send us feedback with the Feedback Hub with this issue and paste the link here so we can more easily find your crash information on the back end. Use "Apps" and "Windows Package Manager" for Category. The share link at the bottom of the report will provide the URL to paste into this Issue to help us locate it.
> 
> Template: msftbot/feedbackHub

I already reported it to the Windows Package Manager.

**Comment by Trenly** [comment]
No previous versions of cheat engine have ever made it past the malware scan - https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+cheatengine+is%3Aclosed

**Comment by Trenly** [comment]
Close with reason: Installs PUA;

**Comment by ImMejor35** [comment]
Ok I understand

**Pull request closed without merging**
