### PR TITLE
New version: Torchsoft.RegistryWorkshop version 5.1.0

### PR DESCRIPTION
**Pull request by aesalazar**
Fix for the hash code mismatch.

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/97169)

### CODE REVIEW

**Review by ImJoakim — CHANGES_REQUESTED** [review]
Hash mismatch happened because a new version was released: 5.1.0.
Are you able to update this PR to change the version as well?

**Comment by aesalazar** [comment]
> Hash mismatch happened because a new version was released: 5.1.0. Are you able to update this PR to change the version as well?

@ImJoakim Ahh..sorry about that.  I missed the subtle difference between 5.0.1 and 5.1.0.  I pushed up the change.

**Comment by aesalazar** [comment]
@ImJoakim Should I remove the 5.0.1 folder and contents?  The download url is always pointed at the latest version so the old install package will never work again.

**Comment by ImJoakim** [comment]
> @ImJoakim Should I remove the 5.0.1 folder and contents? The download url is always pointed at the latest version so the old install package will never work again.

Yes please. I was just in the middle of a message asking about this :)

**Review by ImJoakim — APPROVED** [review]
Perfect, thank you!

**Comment by aesalazar** [comment]
@ImJoakim All set!

**Pull request merged**
