### PR TITLE
New version: octobuild.octobuild version 0.9.0

### PR DESCRIPTION
**Pull request by slonopotamus**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/129125)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2023-12-03 23:57:27.031 [FAIL] Installer failed security check. Url: https://github.com/octobuild/octobuild/releases/download/0.9.0/octobuild-0.9.0-x86_64.msi Result: 0x80004005

**Comment by stephengillie** [comment]
Hi @slonopotamus,

This package didn't pass a Defender scan. It might be a false positive and we can retry tomorrow.
image

This was gathered from a script I've been working to automate for some time. it gathers the build run from the GitHub API, uses this to extract a zip of logs from the run artifacts, unzips this, and adds potential errors and failures from the logs into a comment. The last step is to automate image uploading or attaching.

**Comment by slonopotamus** [comment]
This is a [second time](https://github.com/microsoft/winget-pkgs/pull/118045#issuecomment-1693703125) a false positive is reported. And again, the file is [absolutely green on Virus Total](https://www.virustotal.com/gui/url/59e17507347c785d45b314b3a8a8ec15ca1a878ebc3543327db18d8f170c3cc3).

**Comment by slonopotamus** [comment]
@stephengillie how do I rerun validation?

**Comment by stephengillie** [comment]
@slonopotamus,

Sorry for the repeated concern. What about this package causes the false positives? 

A pipeline run can be triggered by any change to the PR. This can be something arbitrary, such as adding a space or line break.

**Comment by slonopotamus** [comment]
> What about this package causes the false positives?

I believe this is because binaries inside are in Rust. Kaspersky Antivirus heuristic analysis is also [very nervous about Rust](https://forum.kaspersky.com/topic/%D1%81-hello-world-vhotrojanwin32sdumgen-16558/).

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
