### PR TITLE
Remove version: MathiasSvensson.MultiCommander version 13.1.0.2955

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137455)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://multicommander.com/files/updates/MultiCommander_x64_(13.1.0.2955).exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 694)

**Review by Trenly — COMMENTED** [review]
This is the newest version in the repository; Is there an updated version available?

Edit: CC @stephengillie in case automation needs to be updated to check for "latest version" removals and not just "only version"

**Comment by Trenly** [comment]
[Policy] Needs author feedback

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
> This is the newest version in the repository; Is there an updated version available?
> 
> Edit: CC @ stephengillie in case automation needs to be updated to check for "latest version" removals and not just "only version"

Hi @Trenly,

When just one version remains, technically it's also the latest version. 😁 

```PowerShell
[int]$NumVersions = (Get-ManifestListing $PackageIdentifier 0 -Versions).count
if ($NumVersions -eq 1) {
	#Action PR
}
```

Currently the automation just gets a count of version folders in the manifest path.  

```PowerShell
$WinGetOutput = Find-WinGetPackage $PackageIdentifier | Where-Object {$_.id -eq $PackageIdentifier}
$ManifestVersion = $WinGetOutput.version
```

I could update this to match against the manifest version instead:

```PowerShell
$Versions = Get-ManifestListing MathiasSvensson.MultiCommander 0 -Versions
if ($ManifestVersion -eq $Versions[-1]) {
	#Action PR
}
```

This will shift the alert from the last version remaining in repo (which is randomized by many factors through the pipelines and approval process) to the highest version in the repo (as dictated by GitHub directory sorting). 

Does that fulfill the request?

**Comment by Trenly** [comment]
> This will shift the alert from the last version remaining in repo (which is randomized by many factors through the pipelines and approval process) to the highest version in the repo (as dictated by GitHub directory sorting).
> 
> Does that fulfill the request?

Yes, thats exactly what I was thinking!

**Pull request merged**
