### PR TITLE
DirectX Software Development Kit (SDK) 9.29.1962.0 (June 2010 version)

### PR DESCRIPTION
**Pull request by Witchilich**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----
The June 2010 version of DirectX SDK is the last version with DirectSound.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/18577)

### CODE REVIEW

**Comment by Witchilich** [comment]
No checks?

**Comment by denelon** [comment]
https://github.com/microsoft/winget-pkgs/issues/17627 The validation pipelines are currently not running.

**Comment by Witchilich** [comment]
Strange that it worked locally.

**Comment by denelon** [comment]
@Witchilich did you try in the sandbox? I'm wondering if there is a dependency.

**Comment by ChuckFerring** [comment]
There is a dependency on the .Net Framework.

**Comment by Witchilich** [comment]
This installer will throw error 1023 if you have a newer version of redist 2010(x86 or x64) since it tries to install an older version. I think that is causing the issue.
https://support.microsoft.com/en-us/help/2728613/s1023-error-when-you-install-the-directx-sdk-june-2010

**Comment by denelon** [comment]
It looks like we're still blocked on the Windows Feature dependency. I'll add the label. Once we get support for these kinds of dependencies, we can try again :)

**Review by ItzLevvie — APPROVED** [review]

**Comment by denelon** [comment]
Hey @Witchilich, we're now doing validation with dependencies if you want to add them to the manifest :)

**Pull request closed without merging**
