### PR TITLE
New version: DuckStudio.GitHubLabelsManager version 1.2

### LINKED ISSUE #163232: [Update Request]: DuckStudio.GitHubLabelsManager version 1.2
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

DuckStudio.GitHubLabelsManager

### Package Version

1.2

### Please describe the changes you would like to see

https://github.com/DuckDuckStudio/GitHub-Labels-Manager/releases/tag/v1.2

### PR DESCRIPTION
**Pull request by DuckDuckStudio**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] close #163232 https://github.com/DuckDuckStudio/GitHub-Labels-Manager/pull/8 Need link issue.

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

> [!NOTE]
> Main program: glm.exe
> To display version:
> ```powershell
> glm config --version
> ```

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/163233)

### CODE REVIEW

**Review by Luna-Grace — APPROVED** [review]

**Review by fjwxzde — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-07-16 17:31:00.900 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerSharedLib\SHA256.cpp(144)\WindowsPackageManager.dll!00007FFD7668273F: (caller: 00007FFD766CAEC4) Exception(1) tid(944) 8A150040 
> 2024-07-16 17:31:07.675 [FAIL] Installer failed security check. Url: https://github.com/DuckDuckStudio/GitHub-Labels-Manager/releases/download/v1.2/GitHub_Labels_Manager_Setup_v1.2_EN.exe Result: 0x80004005
> 2024-07-16 10:30:55.182 [FAIL] Installer failed security check. Url: https://github.com/DuckDuckStudio/GitHub-Labels-Manager/releases/download/v1.2/GitHub_Labels_Manager_Setup_v1.2_EN.exe Result: 0x80004005
> 2024-07-16 10:30:53.172 [FAIL] Installer failed security check. Url: https://github.com/DuckDuckStudio/GitHub-Labels-Manager/releases/download/v1.2/GitHub_Labels_Manager_Setup_v1.2.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 886.)

**Comment by DuckDuckStudio** [comment]
> Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours.
zh-CN:
image
image

---

en-US:
image
image

---

I really don't understand why there's a security issue almost every time...

**Comment by DuckDuckStudio** [comment]
Previous version： #161398

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 886.)

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
