### PR TITLE
New version: Nushell.Nushell version 0.92.2

### PR DESCRIPTION
**Pull request by fdncred**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/148568)

### CODE REVIEW

**Comment by fdncred** [comment]
@stephengillie can you look at this please? i recently restarted it by closing and reopening, which didn't quite work right. then i modified one of the files to add an extra line and that restarted it. I had to restart because the last validation run was over 13 hours long. This one is now over 1.5 hours and we'd like to get this version published since it's in response to a CVE.

**Comment by stephengillie** [comment]
We have recently had a few PRs that had unusual failed runs that provided no logs or labels - possibly froma temporary pipeline issue. The first run or two might have been more of these. This run I recently started appears to still be validating - about 4.5 hours into what I thought was a 3 hour timeout. Unfortunately, I don't currently have any info on why this is occurring.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
@fdncred,

Thank you for your extended patience.

**Comment by fdncred** [comment]
Thanks. So, what was the deal? Should we expect this from now on?

**Pull request merged**
