### PR TITLE
Remove Old: JanDeDobbeleer.OhMyPosh version 3.169.2

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
null

### CODE REVIEW

**Review by jedieaston — CHANGES_REQUESTED** [review]
Why? The architecture option is not in production builds of winget yet. Making this change will lock people out of getting the version they want until 1.2 is released.

**Comment by vedantmgoyal2009** [comment]
Oh, sorry. I thought it is available in production builds. I was offline for some days as my exams are near so I don't know if anything has changed so till now.

**Comment by OfficialEsco** [comment]
I think you can close these since the 1.2 functions are probably far away.
#35226 
#35225 
#35224 
#35223 
#35222 
#35221 
#35220 
#35219

**Comment by vedantmgoyal2009** [comment]
Well, I had thought so but then I converted to draft so that we don't have to do re-work again.

**Comment by jedieaston** [comment]
1.2 preview releases are supposed to be out before the end of the year I thought? Or at least a 1.1.1 or something, there's been like 50 commits since the last one. Dependency support is there, we should probably be testing that even if everyone doesn't have it yet.

@denelon, thoughts?

**Comment by OfficialEsco** [comment]
Ahh, i see, you guys are talking about winget-cli, winget-cli version `1.2.3131-preview` does indeed have support for architecture
```
The following options are available:
  -m,--manifest                The path to the manifest of the package
  --id                         Filter results by id
  --name                       Filter results by name
  --moniker                    Filter results by moniker
  -v,--version                 Use the specified version; default is the latest version
  -s,--source                  Find package using the specified source
  --scope                      Select install scope (user or machine)
  -a,--architecture            Select the architecture to install
  -e,--exact                   Find package using exact match
  -i,--interactive             Request interactive installation; user input may be needed
  -h,--silent                  Request silent installation
  --locale                     Locale to use (BCP47 format)
  -o,--log                     Log location (if supported)
  --override                   Override arguments to be passed on to the installer
  -l,--location                Location to install to (if supported)
  --force                      Override the installer hash check
  --dependency-source          Find package dependencies using the specified source
  --accept-package-agreements  Accept all license agreements for packages
  --header                     Optional Windows-Package-Manager REST source HTTP header
  --accept-source-agreements   Accept all source agreements during source operations
```

HOWEVER the winget manifest does not support selecting the architecture. So, unless we get Manifest Version 1.1.1/1.2.0 at the same time it will break dependencies.
```
        "PackageDependencies": {
          "type": [ "array", "null" ],
          "items": {
            "type": "object",
            "properties": {
              "PackageIdentifier": {
                "$ref": "#/definitions/PackageIdentifier"
              },
              "MinimumVersion": {
                "$ref": "#/definitions/PackageVersion"
              }
            },
            "required": [ "PackageIdentifier" ]
          },
          "maxItems": 16,
          "uniqueItems": true,
          "description": "List of package dependencies from current source"
        },
```

Also

> Well, I had thought so but then I converted to draft so that we don't have to do re-work again.

These manifests are not ready at all. x64, x86 and arm64 needs to be combined and the PackageName and Moniker needs to be renamed.

**Comment by jedieaston** [comment]
The architecture selected with —a should also be used for the dependencies flow, if I did it right ;)

**Comment by vedantmgoyal2009** [comment]
When @jedieaston said that the architecture option is not there in release builds, I stopped otherwise I already have to the script ready to merge architectures once these PRs get merged.

Also, monikers are already updated, I forgot to update the package name 😅.

**Comment by jedieaston** [comment]
I don't have that release, my desktop is still on v1.1.12986:

```
PS C:\Users\easton\projects\winget-pkgs\manifests\s\SaltStack\SaltMinion> winget install --help
Windows Package Manager v1.1.12986
Copyright (c) Microsoft Corporation. All rights reserved.

Installs the selected package, either found by searching a configured source or directly from a manifest. By default, the query must case-insensitively match the id, name, or moniker of the package. Other fields can be used by passing their appropriate option.

usage: winget install [[-q] <query>] [<options>]

The following arguments are available:
  -q,--query                   The query used to search for a package

The following options are available:
  -m,--manifest                The path to the manifest of the package
  --id                         Filter results by id
  --name                       Filter results by name
  --moniker                    Filter results by moniker
  -v,--version                 Use the specified version; default is the latest version
  -s,--source                  Find package using the specified source
  --scope                      Select install scope (user or machine)
  -e,--exact                   Find package using exact match
  -i,--interactive             Request interactive installation; user input may be needed
  -h,--silent                  Request silent installation
  --locale                     Locale to use (BCP47 format)
  -o,--log                     Log location (if supported)
  --override                   Override arguments to be passed on to the installer
  -l,--location                Location to install to (if supported)
  --force                      Override the installer hash check
  --accept-package-agreements  Accept all license agreements for packages
  --header                     Optional Windows-Package-Manager REST source HTTP header
  --accept-source-agreements   Accept all source agreements during source operations

More help can be found at: https://aka.ms/winget-command-install
PS C:\Users\easton\projects\winget-pkgs\manifests\s\SaltStack\SaltMinion> winget --info        
Windows Package Manager v1.1.12986
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.318
Package: Microsoft.DesktopAppInstaller v1.16.12986.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
PS C:\Users\easton\projects\winget-pkgs\manifests\s\SaltStack\SaltMinion> 
```

The Microsoft Store is signed in to my Insiders account, wasn't that enough on Windows 10?

**Comment by OfficialEsco** [comment]
I have no idea how the preview branch got activated 🤷‍♂️

Also according to winget-cli the latest pre-release version is 1.1.12701, i think that might be how i got into preview tbh

@denelon dosn’t the store only releases defeat the purpose of GitHub releases?.. IMO it would show the community that you guys are active by also releasing it on GitHub.

**Comment by denelon** [comment]
@OfficialEsco, we had an issue with the build/release/flighting with other changes to App Installer. We're cutting a build that will be the next development build (1.2 release candidate) for release at GitHub. I'm coordinating with the release team to make sure we don't step on each other. The build is being cut today for internal validation, and if all goes well, should be out for GitHub next week.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
