### PR TITLE
Added jdk17.0.9.8 to Microsoft.OpenJDK.17

### PR DESCRIPTION
**Pull request by jmjaffe37**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/123843)

### CODE REVIEW

**Comment by jmjaffe37** [comment]
Is anyone able to help here? We manually validated the SHAs with what is expected. Furthermore, these manifests work when I attempt to install and uninstall them locally

**Comment by stephengillie** [comment]
The blocker here is the CLA agreement. I think it's supposed to be waived for MS members, but I'm not 100% sure.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335215 
2023-10-26 13:53:22.253 [CLI ] Package hash verification failed. SHA256 in manifest 
[ef9d9f4e0f48c74cb10dfd663c73c65a1211dcdb8b5d8d361dc0f9902cb6c7de] does not match download 
[2b1c48f42203ad99bae9ef75a4c3bf3bff78d19cfb5fc1b40beb6048e5adec21]

**Comment by stephengillie** [comment]
I'm also getting the hash in the manifest. 

```
PS C:\ManVal> Get-FileHash .\Installers\microsoft-jdk-17.0.9-windows-x64.msi

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          EF9D9F4E0F48C74CB10DFD663C73C65A1211DCDB8B5D8D361DC0F9902CB6C7DE       C:\ManVal\Installers\microsoft-j…
```

This might be due to the an error page being downloaded instead of the package.

**Comment by jmjaffe37** [comment]
@microsoft-github-policy-service rerun

**Review by denelon — APPROVED** [review]

**Pull request merged**
