### PR TITLE
Update D:\Git\winget-pkgs\manifests\b\bshuzhang\PPLink\10.4.0

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114818&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by BrandonWanHuanSheng** [comment]
8/7/2023 10:11:41 PM 

Installer Verification Analysis Context Information: 

Error occurred while downloading installer from https://www.ppzhilian.com/download/win/pp直连%20Setup%2010.4.0.exe. 0x80072F19. 

Error information: 

Http Response: OK 

Http Reason Phrase: OK

**Comment by BrandonWanHuanSheng** [comment]
8/7/2023 10:11:41 PM 

Installer Verification Analysis Context Information: 

Error occurred while downloading installer from https://www.ppzhilian.com/download/win/pp直连%20Setup%2010.4.0.exe. 0x80072F19. 

Error information: 

Http Response: OK 

Http Reason Phrase: OK

What happens over here? It failed from the Installation Scan.

**Comment by BrandonWanHuanSheng** [comment]
8/7/2023 10:11:41 PM 

Installer Verification Analysis Context Information: 

Error occurred while downloading installer from https://www.ppzhilian.com/download/win/pp直连%20Setup%2010.4.0.exe. 0x80072F19. 

Error information: 

Http Response: OK 

Http Reason Phrase: OK

What happens over here?  It look like Azure Pipelines failed to download but the installer availability is still there.

**Review by mdanish-kh — APPROVED** [review]

**Pull request merged**
