### PR TITLE
New version: Alibaba.aDrive version 3.3.0

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | 阿里云盘 | 阿里云盘    |
| Version     | 3.3.0     | 3.3.0 |
| Publisher   | Alibaba Group   | Alibaba Group      |
| ProductCode | 300f80e0-781e-56db-ae9d-9d0190486ca9          | 300f80e0-781e-56db-ae9d-9d0190486ca9    |
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/59571)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Madhusudhan-MSFT** [comment]
@vedantmgoyal2009 - I am looking into this. It appears Installer URL has changed since last version published. The current Installer URL doesn't match the download url from the Publisher website. Would like to understand where this Installer URL is hosted and why doesn't it match with Publisher website download link ?

**Comment by vedantmgoyal2009** [comment]
@spectershell

**Comment by vedantmgoyal2009** [comment]
@madhusudhan-msft https://github.com/vedantmgoyal2009/vedantmgoyal2009/issues/150#issuecomment-1096827848

cc @spectershell

**Comment by Madhusudhan-MSFT** [comment]
> 

I don't understand the complete context about that comments/ conversation. Does it mean going forward Installer URL will different i.e new url what we see in this PR manifest? Could you help me understand some context around that? 
Meantime, I do understand there is some valid reason for this change and hence I can apply waiver to get this change in.

**Pull request merged**
