### PR TITLE
Audient.Sono version 4.2.1.0

### PR DESCRIPTION
**Pull request by hansmbakker**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/68036)

### CODE REVIEW

**Comment by hansmbakker** [comment]
Audient calls the version `4.2.1a` instead of `4.2.1.0` but I believe winget expects numbers for the version?

**Comment by hansmbakker** [comment]
I added the requirement for interactive installation in my installer manifest PR but

```
winget install --manifest .\manifests\a\Audient\Sono\4.2.1.0\
```
does not trigger an interactive installation and instead fails with exit code 2 - is that related to https://github.com/microsoft/winget-cli/issues/910?

The executable seems not to respond to command line parameters so I do not know how to make it unattended.

**Comment by hansmbakker** [comment]
The link comes from https://audient.com/products/audio-interfaces/sono/downloads/. It is similar to https://github.com/microsoft/winget-pkgs/pull/60122.

**Review by ItzLevvie — APPROVED** [review]

**Comment by hansmbakker** [comment]
@ItzLevvie thank you for the review!

Could you please help me with my question about the interactive mode required to make the installer succeed?

I put `interactive` as the only supported mode but winget still tries to install it silently unless I specify `-i`.

In the case it tries to install silently, it will install the drivers without the accompanying tools, and it will exit with exitcode 2 (I did not see additional info).

**Comment by ItzLevvie** [comment]
`InstallModes:` currently doesn't do anything in WinGet.

When I installed this application on a clean install of Windows 11 it didn't exit with %ERRORLEVEL% of 2 and installed fine.

image

**Comment by hansmbakker** [comment]
I found out that likely it crashed because of `Controlled folder access` - Windows blocked the installer from creating a folder in the `Documents` folder:
image

After allowing that action, the installation succeeded without an errorcode. ✅

**Comment by hansmbakker** [comment]
I had some questions left (sorry - I'm new to creating these manifests)

As for the output of your terminal - I see it recognizes the three components it installed:
1. the driver
1. the control app
1. another app from Two Notes (Torpedo Remote)

I do not get that output on my console - do you have a newer version of winget maybe? Or do you use a parameter I don't know about?
Is there a way to tell winget how to deal with those components? Can I give those components a specific `Package Identifier`?

The reason I'm asking this is because I would like to package the 3rd component (Torpedo Remote) separately as updated versions are offered separately from https://www.two-notes.com/en/torpedo-series/torpedo-remote/.

**Comment by Trenly** [comment]
> I do not get that output on my console - do you have a newer version of winget maybe? Or do you use a parameter I don't know about?

Levvie uses a custom script for testing pull requests. The best equivalent which is available right now is the [SandboxTest.ps1 script](https://github.com/microsoft/winget-pkgs/blob/master/doc/tools/SandboxTest.md)

> Is there a way to tell winget how to deal with those components? Can I give those components a specific Package Identifier?

The best way is to create a manifest for those additional packages so that they can be matched and upgraded as their own package

**Comment by hansmbakker** [comment]
@Trenly thanks!

> The best way is to create a manifest for those additional packages so that they can be matched and upgraded as their own package
Created a manifest for Torpedo Remote at https://github.com/microsoft/winget-pkgs/pull/68221 and updated it using the manifest.

It installed correctly but `winget list` still shows the incorrect Package Name and Id (it lists Package Id as `Remote5`). Maybe that will be fixed when the manifest is merged in the repo and the winget index is updated?

**Pull request merged**
