### PR TITLE
Remove Diskuv.opam

### PR DESCRIPTION
**Pull request by jonahbeckford**
OCaml.opam is now the official opam release.

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/172923)

### CODE REVIEW

**Comment by jonahbeckford** [comment]
@ManasJayanth @dra27: This is a follow-up to #172923. We no longer need `Diskuv.opam`.

**Comment by stephengillie** [comment]
URL: https://github.com/diskuv/dkml-installer-opam/releases/download/2.2.0/unsigned-opam-windows_x86-i-2.2.0.exe 
OK

(Automated message - build 921)

**Comment by stephengillie** [comment]
I nearly missed this line in your opening comment:

> OCaml.opam is now the official opam release.

**Comment by stephengillie** [comment]
Hi @jonahbeckford,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 895.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
