### PR TITLE
New package: pnpm.pnpm version 7.13.5

### PR DESCRIPTION
**Pull request by russellbanks**
## Will replace `pnpm.pnpm.6` and `pnpm.pnpm.7`

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/85283)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
@russelbanks - I see you've opened PR's to remove the `pnpm.pnpm.6` versions - After they are removed they should be re-added under this new identifier to maintain the full version history

**Comment by russellbanks** [comment]
> @russelbanks - I see you've opened PR's to remove the `pnpm.pnpm.6` versions - After they are removed they should be re-added under this new identifier to maintain the full version history

Will do :)

**Comment by russellbanks** [comment]
I'll wait for this PR to be merged first as the https://github.com/microsoft/winget-pkgs/labels/Validation-Executable-Error usually needs a .validation

**Comment by russellbanks** [comment]
@vedantmgoyal2009 will run their script to add all pnpm versions once this is merged

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
