### PR TITLE
New package: Snijderlab.AlignCli version 0.4.0

### PR DESCRIPTION
**Pull request by douweschulte**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140048)

### CODE REVIEW

**Comment by douweschulte** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-02-21 07:36:37.128 [FAIL] Installer failed security check. Url: https://github.com/snijderlab/align-cli/releases/download/v0.4.0/align.exe Result: 0x80004005 

(Automated response - build 793.)

**Comment by stephengillie** [comment]
Hi @douweschulte,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 793.)

**Comment by stephengillie** [comment]
Hi @douweschulte,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 812.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-21 12:56:22.564 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerSharedLib\SHA256.cpp(144)\WindowsPackageManager.dll!00007FF93DD5273F: (caller: 00007FF93DD9AEC4) Exception(1) tid(df8) 8A150040  2024-02-21 12:56:32.438 [FAIL] Installer failed security check. Url: https://github.com/snijderlab/align-cli/releases/download/v0.4.0/align.exe Result: 0x80004005 2024-02-21 12:56:32.438 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6

(Automated response - build 812.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 812.)

**Comment by stephengillie** [comment]
Manual Validation ended with: 
image

**Comment by douweschulte** [comment]
I set up a windows sandbox to try and get as clean a slate as possible, there the original also seems to work, but I committed the changes you suggested @stephengillie, thanks a lot for helping me out!

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
