### PR TITLE
Fix DisplayVersion Google.AndroidStudio 2022.2.1.20

### PR DESCRIPTION
**Pull request by treysis**
cf. https://github.com/microsoft/winget-pkgs/issues/108921

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140207)

### CODE REVIEW

**Comment by treysis** [comment]
VisualStudio editor in browser seems to use old version of master branch?!

**Review by mdanish-kh — CHANGES_REQUESTED** [review]
Please update `ManifestVersion` to `1.6.0` in all yaml files. Also, update the schema headers

e.g.,

```diff
- # yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.4.0.schema.json
+ # yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
```

**Comment by mdanish-kh** [comment]
[Policy] reset feedback

**Review by mdanish-kh — APPROVED** [review]

**Pull request merged**
