### PR TITLE
New version: AntoineAflalo.SoundSwitch version 6.8.0

### PR DESCRIPTION
**Pull request by Belphemur**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131109)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Belphemur,

> Current manifest version 6.7.2.0 has 4 parameters, which is greater than this PR's version number 6.8.0's 3 parameters.

Is this intentional?

(Automated response - build 486)

**Comment by Belphemur** [comment]
@stephengillie 

Yes, I dropped `build` and only use `major.build.patch` versioning. 

In the past I let .NET generate the `build` but it has lost value to me, so I dropped it.

**Comment by stephengillie** [comment]
Hi @Belphemur,

> This PR's version number 6.8.0 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 6.7.2.0, which has 4 parameters.

Is this intentional?

(Automated response - build 487)

**Comment by Belphemur** [comment]
@Automated system

Yes, it is.

**Comment by stephengillie** [comment]
Hi @Belphemur,

> This PR's version number 6.8.0 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 6.7.2.0, which has 4 parameters.

Is this intentional?

(Automated response - build 487)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
