### PR TITLE
New version: Algoryx.Algodoo version 2.2.1

### PR DESCRIPTION
**Pull request by aaronliu0130**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/193762)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 899.)

**Comment by aaronliu0130** [comment]
what does that mean-

**Comment by stephengillie** [comment]
Pipelines aren't emitting logs for my automation to process. Sorry for the unclar message.

**Comment by aaronliu0130** [comment]
Any updates on why the pipeline failed?

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 4:20:58 PM: 
> 2024-12-12 16:20:57.906 [CLI ] ShellExecute installer failed: 1

(Automated response - build 904.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 2:22:37 PM: 
> 2024-12-17 14:22:36.505 [CLI ] ShellExecute installer failed: 1 2:22:37 PM: 
> 2024-12-17 14:22:36.328   Failed to proceed to next wizard page; aborting.

(Automated response - build 924.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
