### PR TITLE
New package: SaleaeInc.Logic version 2.4.14

### LINKED ISSUE #143041: [Package Request]: Saleae Logic 2
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.saleae.com/pages/downloads
Publisher: Saleae
Package Name: Logic 2
Description: Saleae Logic 2 is the program used with a Saleae logic analyzer to capture digital and analog signals and analyze digital communication protocols.
Package Version: 2.4.14
Installer URL: https://downloads.saleae.com/logic2/Logic-2.4.14-windows-x64.exe

### PR DESCRIPTION
**Pull request by Exorcism0666**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

* Resolve #143041

---

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 869.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
image

Is there an installer switch to have the package install silently?

**Comment by Exorcism0666** [comment]
> Manual Validation ended with: image
> 
> Is there an installer switch to have the package install silently?

I just can't find them 😭 .

**Comment by MatthewA1** [comment]
The package uses Advanced Installer  
* [Saleae FAQ: Is Silent Installation Supported?](https://support.saleae.com/faq/technical-faq/is-silent-installation-supported)  
* [Advanced Installer: How do I create a silent installation MSI package?
](https://www.advancedinstaller.com/user-guide/qa-silent-msi-install.html) Even though the title says MSI, it is still true for the EXE)

Using these flags however does not resolve the problem of Windows needing user confirmation to allow installation of the included drivers.

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Comment by denelon** [comment]
Once the install can complete without user interactivity the package may be added to the community repository.

**Pull request closed without merging**
