### PR TITLE
Flutter 3.16.4

### PR DESCRIPTION
**Pull request by albertopasqualetto**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

It gives malware error. To be suppressed.

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/130839)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
Batch files are disallowed in the community repository as part of the "No Scripts as installers" policy

**Comment by albertopasqualetto** [comment]
> No Scripts as installer

@Trenly well ok, but older versions were accepted.

**Comment by Trenly** [comment]
@denelon - Thoughts?

**Comment by albertopasqualetto** [comment]
But also now I see https://github.com/microsoft/winget-cli/issues/3386 .

**Comment by denelon** [comment]
I believe this package works because Windows recognizes a batch file (.bat). This wasn't an expected scenario when the portable feature was implemented. It looks like it may have mistakenly been approved previously.

**Comment by albertopasqualetto** [comment]
@denelon ok, is this case of use going to be implemented "officially"?

**Comment by denelon** [comment]
Based on our current policies, we would not try to offer support for running batch files or scripts.

I don't know flutter well enough to understand what the batch file is doing. I'm downloading it now to crack it open and see if there is a reasonable way to keep it in the repository.

**Comment by denelon** [comment]
It took a while to download and unzip.

It looks like it's essentially downloading the Git repository for the project, and the batch script is setting environment variables and then calling other batch files in a chain. Once all the environment variables are set up it does appear to be calling portable executables, but I don't know if they would work if they were directly mapped without the user running the batch scripts.

If the references to the .bat files were removed from the manifest and linked directly to the portable executables, I'd be willing to let the package in. It might also make sense to have Install Notes to tell users exactly what they would need to do to get the environment setup by calling the batch files themselves.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\flutter.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\flutter.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\dart.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\dart.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\flutter.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\flutter.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\dart.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\dart.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.

(Automated response - build 487.)

**Comment by albertopasqualetto** [comment]
> It took a while to download and unzip.
> 
> It looks like it's essentially downloading the Git repository for the project, and the batch script is setting environment variables and then calling other batch files in a chain. Once all the environment variables are set up it does appear to be calling portable executables, but I don't know if they would work if they were directly mapped without the user running the batch scripts.
> 
> If the references to the .bat files were removed from the manifest and linked directly to the portable executables, I'd be willing to let the package in. It might also make sense to have Install Notes to tell users exactly what they would need to do to get the environment setup by calling the batch files themselves.

I think that it goes outside the speed of using winget if I would need to set all those environment variables by hand.

**Pull request closed without merging**
