### PR TITLE
New version: KDE.Krita version 5.2.1

### LINKED ISSUE #124968: [Update Request]: KDE.Krita 5.2.1
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

KDE.Krita

### Package Version

5.2.1

### Please describe the changes you would like to see

https://krita.org/en/item/krita-5-2-1-released/

### PR DESCRIPTION
**Pull request by BrandonWanHuanSheng**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

Resolves #124968 

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/124974)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
*%SETUP%\bin\krita.exe"
%SETUP% is mean where krita-x64-5.2.1-setup was saved. But that one exactly install path which %ProgramFiles%\Krita\bin\krita.exe

**Comment by BrandonWanHuanSheng** [comment]
Validation is almost complete.

**Comment by BrandonWanHuanSheng** [comment]
@microsoft-github-policy-service

**Review by stephengillie — APPROVED** [review]

**Comment by BrandonWanHuanSheng** [comment]
Seem like Stephengillie removes that PR labels that supposed to be done by microsoft-github-polcy-service which is 6 November 2023 at 11:30 PM GMT+8. At that time, microsoft-github-policy-service is down. Due to I modified some of the Display Name and Display Version. Wingetbot noticed another run due to I edit the installer manifest. Seem like wingetbot add that 2 other labels which is at 7 November 2023 at 12:21 AM GMT+8 . At that time  7 November 2023, 2:49 AM GMT+8,  Stephengillie removes that PR labels that has not be done by microsoft-github-policy-service bot was back and online. At that time, my pull request was being subscribed to stephengillie and rerun the validation pipelines to make sure the microsoft-github-policy-service bot is working properly  Later on, stephengillie noticed a green light like say the branch has no conflict with the base branch when moderator approved at that time ,  the validation has been completed at. 7 November 2023 at 3:43 AM and I was not around which is 7 November 2023 at 8:47 AM. At the same time, microsoft-github-policy-service merged the branches and changed the branch into closed state

**Pull request merged**
