### PR TITLE
New package: SatowaNetwork.YubiLock version 1.0.2.0

### PR DESCRIPTION
**Pull request by akama-aka**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/118427)

### CODE REVIEW

**Comment by SlushUwU** [comment]
@microsoft-github-policy-service agree [company="{SatowaNetwork}"]

**Comment by SlushUwU** [comment]
@microsoft-github-policy-service agree company="Satowa Network"

**Comment by stephengillie** [comment]
Hi @SlushUwU,

If a user does not have a YubiKey, this running program renders the computer unusable, as it locks the PC immediately on unlock. And this also prevents uninstall. I'm seeing this with a testing VM, which is showing this behavior - it locks as soon as I unlock it. 
- Is there an installer switch or application switch to prevent logoff? 
- Is there any way to recover a PC by uninstalling this, without performing a full reset/reinstall?

**Comment by SlushUwU** [comment]
> Hi @SlushUwU,
> 
> If a user does not have a YubiKey, this running program renders the computer unusable, as it locks the PC immediately on unlock. And this also prevents uninstall. I'm seeing this with a testing VM, which is showing this behavior - it locks as soon as I unlock it.
> 
> * Is there an installer switch or application switch to prevent logoff?
> * Is there any way to recover a PC by uninstalling this, without performing a full reset/reinstall?

We are currently reprogramming the program so that it is not just a normal Windows program but a Windows service program. The service is then downloaded from a batch file that we provide and then executed. With this batch file you can also activate or deactivate the service accordingly when booting, this is planned in 1.0.3. 

Regarding how to get rid of this if you don't have a YubiKey or have lost it, simply boot the Windows system into safe boot mode and then remove the file from the autostart. Currently you have to start the bat file manually or put it in the autoboot. Or wait a few minutes or so and the program should crash because of the Windows Watch Dog (I think that's the problem).

Currently I have some problems with validating the winget manifest (Which dont make really sense for me) files which is why I can't check off all the checkmarks.

**Pull request closed without merging**
