### PR TITLE
New package: TeamXonotic.Xonotic version 0.8.6

### LINKED ISSUE #95619: [Package Request]: Xonotic
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a script file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Team Xonotic
Publisher Url: https://xonotic.org/team/
Package Name: Xonotic
Description: A fast paced first person shooter where crisp movement, nuanced weapons, and in-your-face action combine to create addictive arena-style gameplay.
Package Version: 0.8.5
Installer URL: https://github.com/garymoon/xonotic/releases/

Current Package Identifier (for new versions): N/A

### PR DESCRIPTION
**Pull request by AsciiWolf**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

Closes #95619.

There are sadly three problems with this manifest at the moment:
1. The game was detected as a malware by WinGet for some reason during the local winget install. There definitely is not any malware present in the game archive and it most likely got detected as such because the game executables are not signed.
2. There is no Start Menu item created during the installation. This sadly seems to be a WinGet limitation and is most likely not possible for portable applications at the moment: https://github.com/microsoft/winget-cli/issues/2299
3. When trying to start the game using a "xonotic" command from a Terminal, the game returns [an error](https://github.com/microsoft/winget-pkgs/assets/2339930/2030cab8-7b5f-4ffd-b670-e2424c2c945e). This is caused by the game executable working directory not being the actual game directory when launched from a Terminal and everything works fine when changing the directory to the actual game directory and running the executable from there. Is there any way to modify the working directory of the command or its launch parameters?
 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/113718&drop=dogfoodAlpha

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Hmm, I thought I already signed the CLA (in a different MS repository).

**Comment by AsciiWolf** [comment]
@microsoft-github-policy-service agree

**Comment by CoolPlayLin** [comment]
@AsciiWolf 
Could you check sure the NestedInstallerFiles is correct?

**Comment by AsciiWolf** [comment]
@CoolPlayLin It should be correct except for the false malware scan result and for the incorrect executable working directory. I am not sure how to solve the working directory issue.

**Comment by Trenly** [comment]
> 3\. When trying to start the game using a "xonotic" command from a Terminal, the game returns [an error](https://github.com/microsoft/winget-pkgs/assets/2339930/2030cab8-7b5f-4ffd-b670-e2424c2c945e). This is caused by the game executable working directory not being the actual game directory when launched from a Terminal and everything works fine when changing the directory to the actual game directory and running the executable from there. Is there any way to modify the working directory of the command or its launch parameters?

[Policy] Zip-Binary

**Pull request closed without merging**
