### PR TITLE
New version: Unity.Unity.6000.WebGL version 6000.0.13f1

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#7048](https://github.com/SpecterShell/Dumplings/actions/runs/10218599586).

<details>

<summary>Log</summary>

````
Updated: 6000.0.12f1 → 6000.0.13f1
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
Pull request created: New version: Unity.Unity.6000 version 6000.0.13f1 - https://github.com/microsoft/winget-pkgs/pull/165881
Handling Unity.Unity.6000.Android...
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
Pull request created: New version: Unity.Unity.6000.Android version 6000.0.13f1 - https://github.com/microsoft/winget-pkgs/pull/165883
Handling Unity.Unity.6000.iOS...
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
Pull request created: New version: Unity.Unity.6000.iOS version 6000.0.13f1 - https://github.com/microsoft/winget-pkgs/pull/165884
Handling Unity.Unity.6000.tvOS...
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
Pull request created: New version: Unity.Unity.6000.tvOS version 6000.0.13f1 - https://github.com/microsoft/winget-pkgs/pull/165885
Handling Unity.Unity.6000.visionOS...
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
Pull request created: New version: Unity.Unity.6000.visionOS version 6000.0.13f1 - https://github.com/microsoft/winget-pkgs/pull/165886
Handling Unity.Unity.6000.LinuxIL2CPP...
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
Pull request created: New version: Unity.Unity.6000.LinuxIL2CPP version 6000.0.13f1 - https://github.com/microsoft/winget-pkgs/pull/165887
Handling Unity.Unity.6000.LinuxMono...
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
Pull request created: New version: Unity.Unity.6000.LinuxMono version 6000.0.13f1 - https://github.com/microsoft/winget-pkgs/pull/165888
Handling Unity.Unity.6000.LinuxServer...
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
Pull request created: New version: Unity.Unity.6000.LinuxServer version 6000.0.13f1 - https://github.com/microsoft/winget-pkgs/pull/165889
Handling Unity.Unity.6000.MacMono...
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
Pull request created: New version: Unity.Unity.6000.MacMono version 6000.0.13f1 - https://github.com/microsoft/winget-pkgs/pull/165890
Handling Unity.Unity.6000.MacServer...
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
Pull request created: New version: Unity.Unity.6000.MacServer version 6000.0.13f1 - https://github.com/microsoft/winget-pkgs/pull/165891
Handling Unity.Unity.6000.UWP...
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
Pull request created: New version: Unity.Unity.6000.UWP version 6000.0.13f1 - https://github.com/microsoft/winget-pkgs/pull/165892
Handling Unity.Unity.6000.WebGL...
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/165893)

### CODE REVIEW

**Comment by stephengillie** [comment]
- Depends on: https://github.com/microsoft/winget-pkgs/pull/165881

**Comment by SpecterShell** [comment]
image

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-08-06 09:48:26.223 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFFCE83C11F: (caller: 00007FFFCE5C8D6F) LogHr(1) tid(14fc) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFFCE742B08: (caller: 00007FFFCE7EBC20) Exception(1) tid(14fc) 8A15005E ] 
> 2024-08-06 09:48:38.651 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFFB22FC11F: (caller: 00007FFFB2088D6F) LogHr(1) tid(874) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFFB2202B08: (caller: 00007FFFB22ABC20) Exception(1) tid(874) 8A15005E ] 
> 2024-08-06 10:12:39.923 [CLI ] ShellExecute installer failed: 2

Automated error analysis suggests -1978335226 may mean Running ShellExecute failed

Automated error analysis suggests 8A15005E may mean APPINSTALLER_CLI_ERROR_PINNED_CERTIFICATE_MISMATCH - The server certificate did not match any of the expected values.

(Automated response - build 887.)

**Pull request closed without merging**
