### PR TITLE
adds Pandoc

### LINKED ISSUE #1941: Forgotten pulls #1675 #1651
It seems that these two pull requests pass all checks but be forgot by reviewers.
#1651 
#1675

### PR DESCRIPTION
**Pull request by gab9281**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1675)

### CODE REVIEW

**Comment by qiancy98** [comment]
Sorry but I wonder if this repo has been forgetted.

**Comment by denelon** [comment]
Mentioned in #1941

**Review by ghost — APPROVED** [review]
Validation has completed

**Comment by KevinLaMS** [comment]
Sorry for the delay.  Trying to verify this app works was more challenging since it is not intuitive.

**Pull request merged**
