### PR TITLE
Add Tokei 11.2.0

### PR DESCRIPTION
**Pull request by XAMPPRocky**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/366)

### CODE REVIEW

**Comment by XAMPPRocky** [comment]
It has been submitted, so now just waiting for a response.

**Comment by XAMPPRocky** [comment]
@KevinLaMS It has been confirmed as a false positive.

Screenshot 2020-05-22 at 14 08 48

**Comment by KevinLaMS** [comment]
The binary looks good, but it does not seem to install.  It appears the binary is the CLI not the installer, so I do not see how a user can access it.

**Comment by XAMPPRocky** [comment]
@KevinLaMS Ah okay, I must have misread the instructions as I thought exe was supposed to point to the application. Do you have to provide an installer or is there a way to provide binaries directly like in other package managers?

**Comment by denelon** [comment]
@XAMPPRocky it looks like you are requesting support for https://github.com/microsoft/winget-cli/issues/182.

**Comment by XAMPPRocky** [comment]
Thank you for your response! Yes I believe so.

**Pull request closed without merging**
