### PR TITLE
Add zh-CN Mirror

### PR DESCRIPTION
**Pull request by CoolPlayLin**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/112019&drop=dogfoodAlpha

### CODE REVIEW

**Comment by CoolPlayLin** [comment]
# PS
`mirrors.tuna.tsinghua.edu.cn` is a trusted mirror site in China, supported by the Information Technology Center of Tsinghua University and operated and maintained by the TUNA Association of Tsinghua University.

**Comment by stephengillie** [comment]
Unfortunately, NodeJS doesn't appear to link to any geographic mirrors from their site.

**Comment by CoolPlayLin** [comment]
> Unfortunately, NodeJS doesn't appear to link to any geographic mirrors from their site. Is there another way to verify official mirrors?

It's unofficial mirror station. I didn't see any official Node.JS mirror station in China mainland, `https://nodejs.org` is unstable in this area

**Comment by stephengillie** [comment]
The mirror station still needs to be official, usually shown by a link on the project's site, sorry.

**Pull request closed without merging**
