### PR TITLE
Added KDE.KDEConnect version 21.04.3.656

### PR DESCRIPTION
**Pull request by ImJoakim**
```
PS C:\Users\WDAGUtilityAccount\Downloads> winget install -m "C:\Users\WDAGUtilityAccount\Desktop\manifests\k\KDE\KDEConnect\21.04.3.656" --scope machine
Found KDE Connect [KDE.KDEConnect]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/656/artifact/kdeconnect-kde-21.04.3-656-windows-msvc2019_64-cl.exe
  ██████████████████████████████  58.5 MB / 58.5 MB
Successfully verified installer hash
Starting package install...
Successfully installed

PS C:\Users\WDAGUtilityAccount\Downloads> winget install -m "C:\Users\WDAGUtilityAccount\Desktop\manifests\k\KDE\KDEConnect\21.04.3.656" --scope user
Found KDE Connect [KDE.KDEConnect]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://binary-factory.kde.org/job/kdeconnect-kde_Release_win64/656/artifact/kdeconnect-kde-21.04.3-656-windows-msvc2019_64-cl.exe
  ██████████████████████████████  58.5 MB / 58.5 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/21869)

### CODE REVIEW

**Comment by ImJoakim** [comment]
🤔

**Comment by ImJoakim** [comment]
Is the bot not re-running anymore after close -> open 😕

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
