### PR TITLE
Add version: Microsoft.AppInstaller version 1.21.3482.0

### PR DESCRIPTION
**Pull request by mdanish-kh**
- Resolves  #131101

cc @denelon

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131164)

### CODE REVIEW

**Review by denelon — APPROVED** [review]

**Comment by denelon** [comment]
@mdanish-kh can you create PRs to remove the earlier versions?

**Comment by mdanish-kh** [comment]
@denelon - The earlier versions seem to be following the correct scheme tho:

https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/AppInstaller

Unless you want them removed for some other reason

**Comment by denelon** [comment]
@mdanish-kh I just want to keep the "single" latest stable release. The downgrade scenario is very complex, and full of breaking scenarios, so it's best if we only offer the latest stable version.

**Comment by mdanish-kh** [comment]
Oh right. I'll remove the other versions then.

**Pull request merged**
