### PR TITLE
New version: robinovitch61.goreleaser-testing 0.36.0

### PR DESCRIPTION
**Pull request by robinovitch61**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132238)

### CODE REVIEW

**Comment by robinovitch61** [comment]
> @robinovitch61 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by robinovitch61** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 
> 2023-12-31 08:16:20.191 [FAIL] Installer failed security check. Url: https://github.com/robinovitch61/goreleaser-testing/releases/download/v0.36.0/goreleaser-testing_0.36.0_Windows_x86_64.zip Result: 0x80004005 
> 2023-12-31 08:15:24.888 [FAIL] Installer failed security check. Url: https://github.com/robinovitch61/goreleaser-testing/releases/download/v0.36.0/goreleaser-testing_0.36.0_Windows_i386.zip Result: 0x80004005

(Automated response - build 516.)

**Comment by stephengillie** [comment]
Hi @robinovitch61,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 516.)

**Comment by robinovitch61** [comment]
> Hi @robinovitch61,
> 
> The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.
> 
> (Automated response - build 516.)
 
@stephengillie, I'm not sure what in my package could be flagging this. This package pretty much just prints its own version. I use it for testing my automated release tooling.

What recourse is there if this is indeed a false positive?

**Comment by stephengillie** [comment]
> What recourse is there if this is indeed a false positive?

Wait a day and try again. False positives will pass on the second try, as here.

**Review by stephengillie — APPROVED** [review]

**Comment by robinovitch61** [comment]
Thanks @stephengillie!

**Pull request merged**
