### PR TITLE
Updated KDE Connect to version 21.12.1, build 845.

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

------

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/40706)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
* Duplicate of https://github.com/microsoft/winget-pkgs/pull/40659

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
* Duplicate of https://github.com/microsoft/winget-pkgs/pull/40659

**Comment by jedieaston** [comment]
That's super weird. My local branch was all merged and I didn't see 845. Sorry.

**Comment by OfficialEsco** [comment]
Levvie just approved it because its been open for 9 hours 🤔
I would advice you to go from bottom to top instead of top to bottom when clearing PRs 😁
https://github.com/microsoft/winget-pkgs/pulls?q=is%3Aopen+is%3Apr+label%3AAzure-Pipeline-Passed+-label%3ANeeds-Author-Feedback+-label%3AModerator-Approved+-author%3A%40me

**Pull request closed without merging**
