### PR TITLE
CiderCollective.Cider.Canary version 1.0.0.0-9edeb08

### PR DESCRIPTION
**Pull request by yazninja**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/43768)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Would you be able to publish releases to https://github.com/ciderapp/Cider/releases?

**Comment by yazninja** [comment]
> Would you be able to publish releases to https://github.com/ciderapp/Cider/releases?

Hi as of now, no. As the releases was meant for MSstore. These are Canary and nightly builds which are meant for advanced users and development purposes.

**Comment by cryptofyre** [comment]
Hold off on this for now. There will be release system soon regarding nightly, and canary builds on the official repository.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/43768#issuecomment-1024833530

**Comment by yazninja** [comment]
> [#43768 (comment)](https://github.com/microsoft/winget-pkgs/pull/43768#issuecomment-1024833530)

will drop canary version, we chave a working CI for Nightly and that would be updated there, thanks!

**Pull request closed without merging**
