### PR TITLE
New package: lubomirkurcak.tend version 0.2.9

### PR DESCRIPTION
**Pull request by lkurcak**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/154617)

### CODE REVIEW

**Comment by lubomirkurcak** [comment]
I was able to install using `winget install --manifest <dir>` on Windows Sandbox:

image

These are the program dependencies:

    $ ldd tend-0.2.9-x86_64-pc-windows-msvc/tend.exe
        ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x7ffc12af0000)
        KERNEL32.DLL => /c/Windows/System32/KERNEL32.DLL (0x7ffc11a20000)
        KERNELBASE.dll => /c/Windows/System32/KERNELBASE.dll (0x7ffc0ffa0000)
        bcryptprimitives.dll => /c/Windows/System32/bcryptprimitives.dll (0x7ffc0feb0000)
        shell32.dll => /c/Windows/System32/shell32.dll (0x7ffc11e20000)
        msvcp_win.dll => /c/Windows/System32/msvcp_win.dll (0x7ffc0fe10000)
        ucrtbase.dll => /c/Windows/System32/ucrtbase.dll (0x7ffc10350000)
        USER32.dll => /c/Windows/System32/USER32.dll (0x7ffc110a0000)
        win32u.dll => /c/Windows/System32/win32u.dll (0x7ffc10560000)
        GDI32.dll => /c/Windows/System32/GDI32.dll (0x7ffc119f0000)
        gdi32full.dll => /c/Windows/System32/gdi32full.dll (0x7ffc10590000)
        ole32.dll => /c/Windows/System32/ole32.dll (0x7ffc11840000)
        combase.dll => /c/Windows/System32/combase.dll (0x7ffc10c30000)
        RPCRT4.dll => /c/Windows/System32/RPCRT4.dll (0x7ffc12920000)

Are some of these problematic?

I am not able to learn much more, the validation step only shows:
`##[warning] Validation concluded that this task needs to go to manual review.`

**Comment by lubomirkurcak** [comment]
Previous submission #153248 failed for depending on `VCRUNTIME140.dll`:
    
    $ ldd tend-0.2.8-x86_64-pc-windows-msvc/tend.exe
        ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x7ffc12af0000)
        KERNEL32.DLL => /c/Windows/System32/KERNEL32.DLL (0x7ffc11a20000)
        KERNELBASE.dll => /c/Windows/System32/KERNELBASE.dll (0x7ffc0ffa0000)
        apphelp.dll => /c/Windows/SYSTEM32/apphelp.dll (0x7ffc0cca0000)
        bcryptprimitives.dll => /c/Windows/System32/bcryptprimitives.dll (0x7ffc0feb0000)
        shell32.dll => /c/Windows/System32/shell32.dll (0x7ffc11e20000)
        msvcp_win.dll => /c/Windows/System32/msvcp_win.dll (0x7ffc0fe10000)
        ucrtbase.dll => /c/Windows/System32/ucrtbase.dll (0x7ffc10350000)
        USER32.dll => /c/Windows/System32/USER32.dll (0x7ffc110a0000)
        win32u.dll => /c/Windows/System32/win32u.dll (0x7ffc10560000)
        GDI32.dll => /c/Windows/System32/GDI32.dll (0x7ffc119f0000)
        gdi32full.dll => /c/Windows/System32/gdi32full.dll (0x7ffc10590000)
        ole32.dll => /c/Windows/System32/ole32.dll (0x7ffc11840000)
        combase.dll => /c/Windows/System32/combase.dll (0x7ffc10c30000)
        RPCRT4.dll => /c/Windows/System32/RPCRT4.dll (0x7ffc12920000)
        VCRUNTIME140.dll => /c/Windows/SYSTEM32/VCRUNTIME140.dll (0x7ffbfe6c0000)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\tend.exe returned exit code: 2

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Verify: 
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
