### PR TITLE
New package: KtorCLI version 0.2.0

### PR DESCRIPTION
**Pull request by Stexxe**
Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/173920)

### CODE REVIEW

**Comment by Stexxe** [comment]
@microsoft-github-policy-service agree company="JetBrains"

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-09-17 08:07:55.959 [FAIL] Installer failed security check. Url: https://github.com/ktorio/ktor-cli/releases/download/0.2.0/ktor_installer.msi Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 895.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\JetBrains\KtorCLI\ktor.exe returned exit code: 1

(Automated response - build 895.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-09-18 10:14:01.654 [FAIL] Installer failed security check. Url: https://github.com/ktorio/ktor-cli/releases/download/0.2.0/ktor_installer.msi Result: 0x80004005

(Automated response - build 895.)

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Verify:
image

**Pull request merged**
