### PR TITLE
Merge x64 and x86 Adobe Acrobat Reader installers

### PR DESCRIPTION
**Pull request by rakleed**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132904)

### CODE REVIEW

**Comment by rakleed** [comment]
If that's ok, let me know, and I will create PRs for older version and separate x64 packages.

**Comment by rakleed** [comment]
If that's ok, let me know, and I will create PRs for older version and separate x64 packages.

**Review by mdanish-kh — CHANGES_REQUESTED** [review]
I am not a user of this package, but I know that this package was broken into different architectures because the two architectures install side-by-side. I believe a user reported that the two applications work very differently and that there could be value in having winget handle updates separately for the two variants. 

Also, changing the PackageId would be a breaking change for scripts/applications in the wild that are using winget to install this package. If we want to do this, there should be a convincing enough reason for it. I'm curious to know why would you like to merge the two IDs into one?

**Comment by rakleed** [comment]
@mda since https://github.com/microsoft/winget-pkgs/issues/32785#issuecomment-956495573 and https://helpx.adobe.com/acrobat/kb/about-acrobat-reader-dc-migration-to-64-bit.html.

But in https://github.com/microsoft/winget-pkgs/pull/40297#issuecomment-1008152647 @OfficialEsco mentioned that two separate PackageIDs are needed. @OfficialEsco, can you tell if there is a reason to leave two separate PackageIDs or can they be combined by simply removing AppsAndFeaturesEntries from the manifest?

**Comment by OfficialEsco** [comment]
Ohboi there have been so many changes with the Adobe Acrobat Reader package...
Technically; If a Package can be installed Side-By-Side they should be separate. (Atleast when i was actively validating packages (2 years ago))
IIRC there was a difference (DisplayName?) between the x64 and x86 AND the MUI installation. However yes this can be fixed with the ARP field now days.

Just to note; You're not allowed to move a package, it has to be delete/create PRs

**Comment by rakleed** [comment]
@mdanish-kh @OfficialEsco just checked, they cannot be installed at the same time, only one version. If you install the x86 version first and then try to install it on top of x64, it will automatically update to x64 in silent mode, and in interactive mode it will prompt you to do this:
image
If canceled, only the x86 version will remain.

If the x64 version was installed, then x86 simply will not be installed:
image

I googled and most of the answers were that there is no difference between applications with different architectures.

But yes, x86 and x64 have different DisplayName, Publisher, ProductCode. I was able to add ProductCode to Installers, but can I do the same for DisplayName and Publisher?

**Comment by mdanish-kh** [comment]
If that is indeed the case, merging the PackageIds seems to be a viable option. (_Perhaps the installers behaved differently in the past and have now got updated_?)

I'm out for a couple of days... so I can't test this right now in my VM. I would also like to add some other folks into the loop

- @PckgrBot who reported the two arches behave differently on element
- @Trenly (originally broke the package into different IDs)

**Comment by Trenly** [comment]
There is also the aspect of currently installed architecture. Because of what @PckgrBot mentioned, it would be best to leave users on the architecture they currently have installed. I'd be worried that if we merge the packages, then there would be more issues with matching the currently installed architecture and ensuring users receive the correct upgrade package. There might be ways to get around this with AppsAndFeaturesEntries, but given the history here with Adobe, it may be best to keep them separate

**Comment by rakleed** [comment]
@PckgrBot @Trenly as far as I understand, two manifestos were originally made, since [Manifest 1.0.0 did not support multiple architectures at the same time](https://github.com/microsoft/winget-pkgs/issues/32785#issuecomment-956495573). Then they were apparently separated again, since [it was possible to install x86 and x64 versions at the same time](https://github.com/microsoft/winget-pkgs/pull/132904#issuecomment-1880039371).

But for a long time the manifest has supported several architectures simultaneously, and [Adobe since February 2021 (version 21.xxx.xxxxx and later) is gradually migrating to x64 versions](https://helpx.adobe.com/acrobat/kb/about-acrobat-reader-dc-migration-to-64-bit.html), and does not allow applications from x86 and x64 to be installed simultaneously (I checked this with the earliest available 21.xxx.xxxxx in winget x86 and x64 versions). Apparently there were problems with the 2020 version (20.xxx.xxxxx), since even [on the Adobe website they are highlighted as separate products](https://www.adobe.com/products/catalog.html#category=pdf&types=desktop).

As for the fact that x64 Acrobat Reader is both Acrobat Standard/Pro, I don’t see a problem here, since most users use the free Reader version anyway.

In addition to `ProductCode`, I also added `DisplayName` and `Publisher` to the manifest, validation passed. `InstallerType: msi` was also previously specified, apparently because `ProductCode` only works for them. If necessary, I can also add `InstallerType`.

**Comment by rakleed** [comment]
@stephengillie

**Comment by stephengillie** [comment]
> @ stephengillie

Hi @rakleed,

There's more discussion than information in this PR comment thread. The question is: "Should these installers be merged into a single manifest?" 

- Can these be installed side-by-side? If so they should be separate, if no they should not.
- x86 seems to be losing support going forward, so will need to be removed at some point.

It sounds like - instead of merging them, we should depreciate the `x86` version. 

This situation seems similar to when `Git.Git` depreciated their `x86` version, starting with putting a message in their `x86` package telling users to upgrade - it couldn't be skipped or made silent by installer switch. There, we had no option but to drop the `x86` version from the manifest. Here, Adobe have been working on this for 3 years. 

Do we have many users of this software who are currently using a 32-bit OS and CPU? Or are most users running the 32-bit version on a 64-bit OS?

**Pull request closed without merging**
