### PR TITLE
New version: LinwoodCloud.Butterfly.Nightly version 2.0.0-beta.0

### PR DESCRIPTION
**Pull request by CodeDoctorDE**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/109553&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
I'm seeing this:
image
image
image

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Bypassing Defender results - https://github.com/microsoft/winget-pkgs/labels/Validation-Executable-Error is because this application requires VC Redist:
image

**Review by ItzLevvie — APPROVED** [review]
> The latest one had no conflicts: https://github.com/microsoft/winget-pkgs/pull/102529

You could probably wait until @stephengillie makes a waiver for this package (or removes the https://github.com/microsoft/winget-pkgs/labels/Validation-Executable-Error label from the PR).

The version in the repository also requires VC Redist FYI so it's best to include them in your manifest (so that once dependency support is out of experimental features and enabled in pipelines you will not see the https://github.com/microsoft/winget-pkgs/labels/Validation-Executable-Error issue anymore)

**Comment by CodeDoctorDE** [comment]
How can I add this?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
See https://github.com/microsoft/winget-pkgs/pull/109553#discussion_r1226470580

**Comment by CodeDoctorDE** [comment]
Thanks

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
> I'm seeing this: 

I couldn't replicate the scan outcomes: 
image

**Pull request merged**
