### PR TITLE
RobloxCorporation.RobloxStudio version 1, 6, 0, 419147

### PR DESCRIPTION
**Pull request by markandpreston123**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/47480)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
At the moment, we are unable to add this package due to CDN issues.

**Comment by markandpreston123** [comment]
> At the moment, we are unable to add this package due to CDN issues.

what is CDN?

**Comment by markandpreston123** [comment]
and is it my fault?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> what is CDN?

It seems like Roblox has different installers for different regions with the exact same URL.

So if you added this package other people may not be able to install it and also Roblox updates their InstallerSha256 too frequently for the automation to catch it.

> and is it my fault?

No.

An alternative would be to setup a private repository using https://github.com/microsoft/winget-cli-restsource or create a local manifest file somewhere on your drive instead of publishing it to the community repository.

**Pull request closed without merging**
