### PR TITLE
New package: Unibo.Alchemist version 30.0.5

### PR DESCRIPTION
**Pull request by Zimbrando**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/138912)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 729.)

**Comment by stephengillie** [comment]
Hi @Zimbrando,

This package installed normally on a Windows 10 VM. But when launching, it does not appear to provide any output - to the console, nor to the system logs, nor any log files in its directory that I could find. Is this expected? Is this application supposed to be used in a different way?

**Comment by Zimbrando** [comment]
> Hi @Zimbrando,
> 
> This package installed normally on a Windows 10 VM. But when launching, it does not appear to provide any output - to the console, nor to the system logs, nor any log files in its directory that I could find. Is this expected? Is this application supposed to be used in a different way?

Hi,
It is expected to run from command line and provide an help output that explains how to use it. I am trying to figure out how to add it in the system path correctly, so yes right now it's not working as expected. Do I have to mess with the manifest file or the msi package to accomplish this?

**Comment by Zimbrando** [comment]
@microsoft-github-policy-service agree

**Comment by Zimbrando** [comment]
@stephengillie There seems to be some errors in the configuration and I have figured out how to add the the path in the environment variable. If it is ok, you can approve the merge and then later on i will update the msi package to a newer version. Otherwise we can close this pull request.

**Comment by stephengillie** [comment]
I'll need to review this further. But if the package has a configuration issue, then that issue should be resolved, and then the package can be submitted.

**Comment by stephengillie** [comment]
Hi @Zimbrando, 

Sorry about the delay. 

> @ stephengillie There seems to be some errors in the configuration and I have figured out how to add the the path in the environment variable. 

These seem essential for normal program operation, so we shouldn't add the manifest until after they've been added. 

> If it is ok, you can approve the merge and then later on i will update the msi package to a newer version. Otherwise we can close this pull request.

I'll close this PR for you. Having a version which requires this level of post-install configuration might be a bad experience for users. They might form a negative opinion of this application based on this version.

**Pull request closed without merging**
