### PR TITLE
Kiwix.WikiMed version 2.1.0.0

### PR DESCRIPTION
**Pull request by Jaifroid**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/68684)

### CODE REVIEW

**Comment by Jaifroid** [comment]
@ItzLevvie I can't see what's wrong with this manifest, having tried three times to close the PR and re-open it. The validation error says the InstallerUrl is the issue, but copying and pasting the InstallerUrl into a browser shows that the URL is perfectly valid.

This error isn't the "usual" validation problem I'm getting with UWP HTML/JS apps. This looks different. The manifest was created and submitted via CI with the `wingetcreate update` command, so it's unlikely that there is human error in authoring the manifest. `wingetcreate` downloaded the package from the exact same URL, parsed the file, updated the manifest, validated it and submitted the PR...

**Comment by Jaifroid** [comment]
The problem here seems to be a re-occurrence of https://github.com/microsoft/winget-cli/issues/1987. I've re-opened that issue. See https://github.com/microsoft/winget-cli/issues/1987#issuecomment-1204830212.

@denelon There appear to be multiple issues with msix/appx installers. See https://github.com/microsoft/winget-pkgs/pull/68356 (a different issue from this one) and now this regression.

**Review by ItzLevvie — DISMISSED** [review]

**Comment by Jaifroid** [comment]
@zachcarp Please see https://github.com/microsoft/winget-cli/issues/1987#issuecomment-1207150140 for what is going on here. Winget versions since 1.3.1741 can no longer install large msix/appxbundle packages, possibly due to a timeout in the hash check stage. I can reproduce perfectly the fact that prior to 1.3.1741 this app can be installed, and from 1.3.1741 it can no longer be installed. It applies to previously validated versions of this app too. This only affects msix/appxbundle apps, not exe files. While there is no way, seemingly, around this for the user, other than downgrading winget, for such users it would still be useful if it's possible to merge this PR. The manifest validates locally (and was indeed updated and validated by winget-create).

**Comment by zachcarp** [comment]
I verified that it installed correctly for me, and waived it like the previous version. In doing so we are getting a new validation error for Manifest-Installer-Validation-Error.

**Comment by zachcarp** [comment]
@johnmcpms @denelon - Do you have any context into this?

**Comment by denelon** [comment]
I'm not sure what might have impacted the behavior here. I'm also going to tag @ryfu-msft to see if he has any context. The manifest appears to have been generated with wingetcreate so the schema should be valid.

**Comment by Jaifroid** [comment]
@denelon For some time now, installing appxbundle UWP apps (at least those based on HTML/JS) has been experiencing some small issues with winget. The issue is mostly documented here: https://github.com/microsoft/winget-cli/issues/1987. 

Now there appear to be two separate issues:

* The first is that I'm guessing that there is no automated testing of winget done on HTML/JS UWP apps, so support tends to drift, despite the fact that the UWP AppInstaller has no problems watsover installing these files..
* The second and most serious issue that has emerged since mid June is that winget builds from v1.3.1741: have suddenly stopped being able to install very large appxbundles (mine are >1GB). All the previous KiwixJS.WikiMed archives that had been validated with winget no longer install if you are using > v.1.3.1741. Again, I assume no automated testing was done that would have picked this up? It seems to bomb out at the hash check. Any winget prior to v1.3.1741 can correctly install these files. There must be a regression that occurred in that build, and it probably shouldn't be too hard to identify.

**Comment by Jaifroid** [comment]
This shows the issue that is causing validation and installation to fail with this large bundle (and the previous already validated one):

image

And for the avoidance of doubt, downloading the exact same URL (for the installer in the PR) in a browser and launching it in Explorer allows the app to be successfully installed with no errors:

image

**Comment by Jaifroid** [comment]
@denelon So given that I've determined that this issue is baked in to every winget-cli release since 1.3.1741, I suppose it's going to be a while till the underlying problem can be identified and a new version released. The problem is that it affects every historical package of this app (WikiMed) that had previously worked, so I can't just withdraw this latest version, I would need to withdraw all the old packages currently listed by winget (see below). How do you recommend I proceed?

```
PS C:\Repos> winget show --versions kiwix.wikimed
Found WikiMed by Kiwix [Kiwix.WikiMed]
Version
-------
2.0.9.0
2.0.4.0
1.9.9.0
1.9.8.0
1.9.5.0
1.9.2.0
1.8.9.0
1.8.4.0
1.8.0.0
1.7.7.0
PS C:\Repos>
```

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/1987#issuecomment-1212365048

**Comment by JohnMcPMS** [comment]
Great, we shot ourselves in the foot...  Not sure if we can easily override the "you should have the signature sha" or not though.

**Comment by Jaifroid** [comment]
OK, I'll wait to see.

What I've done in the meantime is post on my releases page for this app a note saying that winget install is currently broken for WikiMed UWP and under investigation, but that users can install the signed package simply by downloading it in a browser from our GitHub repo and opening it.

The [Electron version of this app validates and installs fine](https://github.com/microsoft/winget-pkgs/pull/68872), by the way (and that manifest doesn't have the `SignatureSha256` I assume because it's an .exe). That package is signed by the same Code Signing Certificate, and has almost the same file structure internally as the UWP app (plus files belonging to the Electron framework). So this really does seem to be a UWP-specific issue.

Most of our ordinary users use the Microsoft Store for the UWP app, so the winget version is for power users (who should also be comfortable using a workaround for now).

**Review by ItzLevvie — APPROVED** [review]

**Comment by denelon** [comment]
@Jaifroid just as an FYI, if users `winget show Kiwix.WikiMed` the download URL is clickable in Windows Terminal. It might save them from having to directly open their browser and navigate to releases.

```text
winget show Kiwix.WikiMed 
Found WikiMed by Kiwix [Kiwix.WikiMed]
Version: 2.0.9.0
Publisher: Kiwix
Moniker: wikimed
Description: WikiMed by Kiwix is an offline medical encyclopaedia with content provided by Wikipedia's WikiProject Medicine. Conaining more than 55,000 medical and health-related articles, it makes medical knowledge available to people with limited Internet access or anyone who needs quick reference access to in-depth medical information. The software as well as the content is free to use for anyone.
License: GPL3
License Url: https://github.com/kiwix/kiwix-js-windows/blob/master/LICENSE
Tags:
  wikimed
  medicine
  medical
  offline
  wikipedia
  encylopedia
  encylopaedia
  dictionary
  reference
  reader
  wiki
  zim
  kiwix
  kiwixjs
  kiwix-js
  kiwix-js-windows
Installer:
  Installer Type: msix
  Installer Url: https://github.com/kiwix/kiwix-js-windows/releases/download/v2.0.9-WikiMed/KiwixWebAppWikiMed_2.0.9.0_AnyCPU.appxbundle
  Installer SHA256: cb70c06a3971c0aa5bcf705e73e383975fb7919a4f0a4d15e8d67736aaf1794a
```

**Pull request merged**
