### PR TITLE
New package: Deskflow.Deskflow(64-bit) version 1.17.0

### PR DESCRIPTION
**Pull request by nicola02nb**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/185685)

### CODE REVIEW

**Comment by marlop352** [comment]
@nicola02nb it would probably be better to use the stable 1.17.0 tag instead of the continuous one

**Comment by nicola02nb** [comment]
> @nicola02nb it would probably be better to use the stable 1.17.0 tag instead of the continuous one

Yeah, probably it's better to do like you sayed... I'll make some changes soon

**Comment by nicola02nb** [comment]
Closed to edit package ID

**Comment by nicola02nb** [comment]
New PR #186364

**Pull request closed without merging**
