### PR TITLE
Add new version - WK.WKRadar 7.11.0.0

### PR DESCRIPTION
**Pull request by ghost**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/165291)

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Manifest conform.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-07-30T21:24:59.8700475Z Manifest Validation Failed
 2024-07-30T21:25:04.9325454Z ##[error]Manifest Validation Failed

(Automated response - build 887.)

**Comment by WKSistemas** [comment]
winget_711
Do I need to do something, @stephengillie ?

**Comment by stephengillie** [comment]
>  Manifest Error: Schema Error. [Schema validation failed. Error context: <root>[Tags] Description: Array should contain no more than 16 elements. Error context: <root> Description: Failed to validate against schema associated with property name 'Tags'. ] File: WK.WKRadar.locale.pt-BR.yaml

**Review by ghost — COMMENTED** [review]
Adjusted tags.

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
