### PR TITLE
New version: maximmax42.CustomRP version 1.14.10 [FP]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Failed
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | CustomRP | ImageMagick 7.1.0-32 Q16-HDRI (64-bit) (2022-04-30), Dolphin, Jackett, DBeaver 22.0.4 (current user), Google Chrome Canary, 开黑啦, Kate, KDE Connect, KDevelop, Kile, DOSBox-X 0.83.25 (64-bit)    |
| Version     | 1.14.10     | 7.1.0.32, 22.04.0, 0.20.1001.0, 22.0.4, 103.0.5038.0, 0.0.51.2, 22.04.0, 22.04.0, 5.6.2, 2.9.93, 0.83.25 (64-bit) |
| Publisher   | maximmax42   | ImageMagick Studio LLC, KDE e.V., Jackett, DBeaver Corp, Google LLC, 开黑啦, KDE e.V., KDE e.V., KDE e.V., KDE e.V., joncampbell123 [DOSBox-X Team]      |
| ProductCode |           | ImageMagick 7.1.0 Q16-HDRI (64-bit)_is1, Dolphin, {C2A9FC00-AA48-4F17-9A72-62FBCEE2785B}_is1, DBeaver (current user), Google Chrome SxS, KaiHeiLa, Kate, KDE Connect, KDevelop, Kile, {63E5D76D-0092-415C-B97C-E0D2F4F6D2EC}_is1    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [1364](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/2258307861>)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]
This pull request (PR) has been automatically approved via GitHub CLI using `@(53070, 53069, 53066, 53065, 53047, 53045, 53043, 53041, 53040, 53038, 53036, 53035, 53033, 53031, 53030, 53028, 53026, 53025, 53023, 53021, 53020, 53018, 53017, 53015, 53013, 53011, 53010, 53008, 53007, 53005, 53004, 53002, 53001, 53000, 52998, 52997, 52996, 52994, 52993, 52991, 52989, 52987, 52985, 52984, 52982, 52980, 52979, 52977, 52973, 52970, 52966, 52962, 52957, 52951, 52948, 52947, 52944, 52941, 52939, 52937, 52935, 52934, 52932, 52929, 52925, 52923, 52922, 52919, 52916, 52915, 52914, 52913, 52910, 52909, 52908, 52907, 52906, 52905, 52904, 52898, 52897, 52896, 52895, 52894, 52893, 52892, 52891, 52889, 52885, 52882, 52881, 52878, 52876, 52873, 52872, 52867, 52866, 52858, 52857, 52855, 52853, 52850, 52849, 52846, 52844, 52843, 52841, 52838, 52836, 52834, 52831, 52829, 52827, 52826, 52824, 52822, 52821, 52818, 52815, 52811, 52809, 52806, 52803, 52799, 52797, 52794, 52791, 52789, 52786, 52784, 52783, 52782, 52780, 52779, 52778, 52777, 52776, 52775, 52774, 52773, 52772, 52771, 52770, 52769, 52768, 52767, 52766, 52762, 52760, 52759, 52758, 52757, 52755, 52754, 52733, 52731, 52729, 52727, 52726, 52725, 52723, 52722, 52720, 52718, 52717, 52715, 52714, 52712, 52711, 52709, 52708, 52706, 52645, 52540, 52539, 52485, 52484, 52478, 52477, 52370, 52351, 52331, 52200, 52120, 51328, 50940) | % { gh pr review --approve $_ }` in Windows PowerShell.

**Review by ItzLevvie — DISMISSED** [review]

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/55251#pullrequestreview-917337550

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/53005#pullrequestreview-917501674

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
