### PR TITLE
New package: FrenchGithubUser.Hatt version 0.3.5

### PR DESCRIPTION
**Pull request by soredake**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/147376)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 The orchestrator function 'InstallerOrchestrator' failed: "The orchestrator function 'ESRPOrchestrator' failed: "Exception of type 'Microsoft.WinGetSvc.WinGet.ESRP.Common.WinGetESRPTimeoutException' was thrown.". See the function execution logs for additional details.". See the function execution logs for additional details.
 The orchestrator function 'InstallerOrchestrator' failed: "The orchestrator function 'ESRPOrchestrator' failed: "Exception of type 'Microsoft.WinGetSvc.WinGet.ESRP.Common.WinGetESRPTimeoutException' was thrown.". See the function execution logs for additional details.". See the function execution logs for additional details.
 

(Automated response - build 876.)

**Comment by soredake** [comment]
>The package manager bot determined there was an issue with one of the installers listed in the url field, and cannot continue.

Installed fine on real system.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Installer https://github.com/FrenchGithubUser/Hatt/releases/download/0.3.5/hatt-windows-amd64-installer.exe
 Scan request id: '85f3e295-34ff-4877-80df-276babb7ee59'
 Error information: BlockingDetectionFound
 
 4/4/2024 4:16:32 AM
 
 ****************************************************************************************
 Installer Validation
 ****************************************************************************************
 

(Automated response - build 876.)

**Comment by stephengillie** [comment]
This might be due to a network block of data centers, to prevent automated downloads.

(Automated response - build 876.)

**Comment by soredake** [comment]
Can't do anything.

**Comment by soredake** [comment]
@stephengillie can you please verify & review this manually as it's installs fine on real machine?

**Comment by stephengillie** [comment]
> @ stephengillie can you please verify & review this manually as it's installs fine on real machine?

Hi @soredake,

Sorry to miss your message. Unfortunately, this isn't far enough along in the pipeline for me to manually complete.

**Pull request closed without merging**
