### PR TITLE
New version: Microsoft.PowerShell version 7.4.0.0

### PR DESCRIPTION
**Pull request by anamnavi**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/127133)

### CODE REVIEW

**Review by mdanish-kh — APPROVED** [review]

**Comment by denelon** [comment]
@mdanish-kh how does this look based on your requested changes?

**Comment by denelon** [comment]
😂🎉

**Comment by mdanish-kh** [comment]
Perfecto

**Comment by Mrxx99** [comment]
My winget can't find version 7.4.0, I tried winget source update, winget upgrade, winget upgrade Microsoft.PowerShell but it tells my there is no newer version (I have 7.3.10.0), winget list says it's source is winget search lists this:
image

**Pull request merged**
