### PR TITLE
Add Multi Commander 9.7.0

### PR DESCRIPTION
**Pull request by latere-a-latere**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/807)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
I do not seem to find the Muticomander file on my PC following install.

**Comment by MarNicGit** [comment]
@KevinLaMS it appears that the NSIS installer relaunches itself as admin if the user chooses "all users", which is the default option. The silent parameter appears to skip over this and silently quit instead.

If I run winget as admin it will install the manifest as intended, and so will launching the installer as admin with the silent parameter. Is there a way I can tell winget to always ask for admin privileges when attempting to install this package?

**Comment by KevinLaMS** [comment]
https://github.com/microsoft/winget-cli/issues/152

**Comment by denelon** [comment]
@MarNicGit we've implemented support for User vs. Machine installation if the manifest specifies the install scope. The manifest will need to be updated to the latest schema.

**Comment by MarNicGit** [comment]
Commenting to prevent auto-closure, will provide a fix somewhere this week

**Comment by tiziodcaio** [comment]
Sorry but I tried to fix into my pull...

**Comment by tiziodcaio** [comment]
If it will works, we can close it

**Comment by MarNicGit** [comment]
@tiziodciao This PR is for version 9.7.0, so it doesn't block your PR for 11.0.0. Thanks for reminding me I still had this PR open :)

**Comment by tiziodcaio** [comment]
> @tiziodcaio This PR is for version 9.7.0, so it doesn't block your PR for 11.0.0. Thanks for reminding me I still had this PR open :)

Yep sure...

**Comment by Trenly** [comment]
@ItzLevvie This has been resolved by #31179

**Comment by MarNicGit** [comment]
I'm closing this PR because I abandoned all work on it and it has been made obsolete by #31179.

**Pull request closed without merging**
