### PR TITLE
DRAFT rcmaehl.MSEdgeRedirect version 0.6.2.0

### PR DESCRIPTION
**Pull request by Macleykun**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/45636)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
This might be blocked as interactive-only due to this message -
image

**Comment by Macleykun** [comment]
> This might be blocked as interactive-only due to this message - image

I'm deeply greatful for the incredible fast response and feedback on this pull!
Regarding that message, while i'm not the main developer of said program. I do agree that this will be an interactive only.

For any futher questions regarding improving the installation experience of set program, i would like to ask @rcmaehl for his insight.

**Comment by Trenly** [comment]
> I do agree that this will be an interactive only.

Unfortunately, at this point, all installers must support silent install before they can be added into the repository. Assuming that the pipelines will catch this, you can set this PR to draft mode and then we can label this to revisit it once interactive installers are supportive

**Comment by Macleykun** [comment]
> > I do agree that this will be an interactive only.
> 
> Unfortunately, at this point, all installers must support silent install before they can be added into the repository. Assuming that the pipelines will catch this, you can set this PR to draft mode and then we can label this to revisit it once interactive installers are supportive

Sure thing! Thank you agani for your feedback! I'll talk to the dev/check the documentation if we have a quiet mode!

**Comment by Trenly** [comment]
@denelon - Can you tag this please?
Blocking-Issue, Interactive-Only-Installer

**Comment by rcmaehl** [comment]
`/silentinstall` will work but it'll want a setup.ini file. I'll add the option to skip the file requirement with some default options.

**Pull request closed without merging**
