### PR TITLE
New Version: OO-Software.Defrag.Professional version 27.0.8042

### PR DESCRIPTION
**Pull request by oo-cmatuschka**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/163839)

### CODE REVIEW

**Comment by oo-cmatuschka** [comment]
Hi @stephengillie , 
I thought I had finally understood everything, but that's not the case ☹

We have the problem that when we want to update to a new version, we get this message:

a newer version was found but the install technology is different from the current version installed

We use a wrapper exe around our MSI files and suspect that this is exactly our problem.

Now I have used an MSI as an installation file with this branch here as the basis. 
But there is always an error from the Winget bots. But they are not very detailed in the error description.
The question is, what is bothering them?

With the cmd: msiexec /i “[msi path]” /quiet /norestart the installation runs directly in windows silent.

If I call my manifest with the silent params: /quiet /norestart, a window appears, but it is not interactive. Why is it not as silent as via cmd? Does this disturb the Winget bots?

If I do not specify any silent parameters, it also aborts, although other manifest files from other providers also have no silent parameters.

Or is it because of the dependencies? 

I don't know what to do? Can you please help me?

Best regards

Christian

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334972
> 2024-07-19 05:19:46.964 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFD9143C11F: (caller: 00007FFD911C8D6F) LogHr(1) tid(398) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFD91342B08: (caller: 00007FFD913EBC20) Exception(1) tid(398) 8A15005E ] 
> 2024-07-19 05:19:54.792 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFD76DBC11F: (caller: 00007FFD76B48D6F) LogHr(1) tid(10e8) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFD76CC2B08: (caller: 00007FFD76D6BC20) Exception(1) tid(10e8) 8A15005E ] 
> 2024-07-19 05:19:56.037 [CLI ] No suitable installer found for manifest Microsoft.DotNet.DesktopRuntime.6 with version 6.0.32
> 2024-07-19 05:19:43.490 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF99C61C11F: (caller: 00007FF99C3A8D6F) LogHr(1) tid(970) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF99C522B08: (caller: 00007FF99C5CBC20) Exception(1) tid(970) 8A15005E ] 
> 2024-07-19 05:19:52.258 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF9859CC11F: (caller: 00007FF985758D6F) LogHr(1) tid(135c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF9858D2B08: (caller: 00007FF98597BC20) Exception(1) tid(135c) 8A15005E ] 
> 2024-07-19 05:19:53.632 [CLI ] No suitable installer found for manifest Microsoft.DotNet.DesktopRuntime.6 with version 6.0.32

Automated error analysis suggests -1978334972 may mean This package has a dependency missing from your system.

(Automated response - build 886.)

**Comment by oo-cmatuschka** [comment]
Hi @stephengillie,

thank you very much for your reply. My new try now only resulted in another error. Is there a way to view a detailed error log like the one you sent? I can only find this: 
https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=597114&view=logs&j=68997d86-8ece-5ae8-3ac5-ccdbfa458731&t=b79910ce-dca5-5e27-ad7f-bd285eecb5a2&l=38
I don't always want to ask you either.

**Comment by stephengillie** [comment]
Hi @oo-cmatuschka,

Very sorry to miss this earlier. Please understand that my previous responsee was the result of a scripted process which downloads the zip of logs, filters them, and searches each string against a list of known errors. 

- As for the other error: https://github.com/microsoft/winget-pkgs/discussions/155218

**Comment by stephengillie** [comment]
Hi @oo-cmatuschka,

This manifest adds Apps and Features entries that aren't present in previous PR versions. These entries should be added to the previous versions, or removed from this version.

(Automated response - build 887.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
