### PR TITLE
Proposal - Split 7-Zip Alpha from 'stable' releases

### PR DESCRIPTION
**Pull request by peterlewis**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [ ] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

Can I suggest that the maintainers consider whether splitting 7-Zip alpha releases from the 'stable' non-alpha releases, might be a good idea? I certainly prefer to install a stable, non-alpha release, wherever possible and I imagine there are others who might be keen on the idea, also...

Would welcome thoughts on this!

Thanks,

Peter

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3746)

### CODE REVIEW

**Comment by yigitemres** [comment]
Generally, this repo doesn't allow modifying more than one file (creating, changing etc.). It will be good to doing separate prs.

**Comment by peterlewis** [comment]
Thanks, @yigitemres! I appreciate that helpful feedback! :) At the moment this is still very much draft and has been done to highlight what I had mentioned in https://github.com/microsoft/winget-cli/issues/147, namely:

> > Pinging @KevinLaMS and @denelon for an update here. I went to install 7zip and found that it would be an alpha version (20.0.0-alpha). This is not something I want to install on my development machine and expected that I would be installing the latest stable release of 7zip (19.00)... Can we please revert [microsoft/winget-pkgs#2088](https://github.com/microsoft/winget-pkgs/pull/2088)?
> 
> I agree. Can we at least, for now, consider adopting the same behaviour as is done for Visual Studio Code to differentiate it from Visual Studio Code Insiders?
> 
> I've [**drafted** a PR](https://github.com/microsoft/winget-pkgs/pull/3746) that follows the example of VSCode/VSCode Insiders and that I believe would sort the 7-Zip issue that @tusharb86 raised. Would welcome thoughts from all (@KevinLaMS and @denelon too, perhaps?).

f this is something that the maintainers might entertain as a possibility then can happily split this PR into two, though considering the PR is performing a single action (i.e. splitting alpha releases from stable releases) then, to me, it does make more sense to be in a single PR. However, I don't make the rules and am more than happy to go with the flow, on that! :)

**Comment by KevinLaMS** [comment]
I think it would be fine to create a new -alpha version until there is scope working.  
i would use a -alpha following the pattern VSCode did


C:\Users\kevinla>winget search vscode
Name                         Id                            Version            Match                    Source
-------------------------------------------------------------------------------------------------------------
Visual Studio Code           Microsoft.VisualStudioCode    1.49.1.58bb7b2331  Moniker: vscode          winget
Visual Studio Code - Inside… Microsoft.VisualStudioCodeIn… 1.50.14.635cfbcd0f Moniker: vscode-insiders

the easiest way to do this would be to add a new manifest, then we would delete the alpha version.

Also note one of your manifests have a type apha.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]

**Comment by peterlewis** [comment]
That's great, thanks for that @KevinLaMS. I'll sort out a couple of PRs for both addition of alpha version and deletion of the existing YAMLs.

Thanks for the note regarding the formatting. I simply transposed the existing YAMLs to a new directory, so may have transposed issues along with those.

Closing this draft PR, now! 👍 

Thanks,

Peter

**Comment by peterlewis** [comment]
PR for alpha branch is in as #3756

**Pull request closed without merging**
