### PR TITLE
Samsung.ativ sw.book9 2.1.14.1 04d583a4 3ccb 47c4 b89b a80a903694fb

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/113307&drop=dogfoodAlpha

### CODE REVIEW

**Comment by upintheairsheep** [comment]
validation screenshot?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
`manifests/s/Samsung/ATIV-SW/Book9/2.1.14.1` needs to  be changed to `manifests/s/Samsung/ATIV-SW/Book9/2.1.14`

**Comment by upintheairsheep** [comment]
http://dl.google.com/googletalk/googletalk-setup.exe

**Comment by upintheairsheep** [comment]
https://github.com/FlashpointProject/FlashpointComponentTools/releases/latest/download/FlashpointInstaller.exe

**Comment by stephengillie** [comment]
> Manifest: The manifest file path must match PackageIdentifier and PackageVersion properties from manifest. actual 'manifests\s\Sa***ung\ATIV-SW\Book9\2.1.14', expected 'manifests\s\Sa***ung\SWUpdate\2.1.14'

**Comment by stephengillie** [comment]
Is there a switch to complete silently?
image

**Comment by upintheairsheep** [comment]
> Is there a switch to complete silently? image

No. Interactive Only.

**Pull request closed without merging**
