### PR TITLE
Updated Google Chrome to version 68.73.16498.

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

------

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/9599)

### CODE REVIEW

**Comment by jedieaston** [comment]
It doesn't contain more than one manifest, I think it's getting mad because I added an additional architecture. I think this is a bug (as I couldn't add an additional architecture to the current version in the repo since the hash won't validate for that one, so the update and the x86 stuff have to be a part of the same commit).

**Comment by LanceMcCarthy** [comment]
I'm having the same problem https://github.com/microsoft/winget-pkgs/pull/9600. There's an issue with the validation, or the docs are missing an explanation of breaking changes.

**Comment by denelon** [comment]
We're going to take a look to see what is happening here.

**Comment by denelon** [comment]
We're currently only supporting operations under 1 directory. The best path forward is likely a PR in the new directory for the "add" and a delete PR in the other directory after.

**Pull request merged**
