### PR TITLE
New Version: Microsoft.dotnet version 6.2.22.10605

### PR DESCRIPTION
**Pull request by ItsPizzaTime1501**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/46502)

### CODE REVIEW

**Comment by ItsPizzaTime1501** [comment]
ok really not sure what went wrong there

**Comment by ItsPizzaTime1501** [comment]
upon running it for a second time outside of sandbox it does indeed fail but i unsure as to why, from the logs it does not seem to be an issue with the manifest
```[4D70:465C][2022-02-15T16:41:25]e000: Error 0x80070057: Failed to enable logging for package: Microsoft.NET.Workload.Mono.ToolChain.Manifest_6.0.200.6.0.2_mauipre.1.22102.15_x64.msi to: C:\Users\<username>\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Microsoft.dotnet.6.2.22.10605-2022-02-15-16-41-16.863_008_Microsoft.NET.Workload.Mono.ToolChain.Manifest_6.0.200.6.0.2_mauipre.1.22102.15_x64.msi.log
[4D70:465C][2022-02-15T16:41:25]e000: Error 0x80070057: Failed to execute MSI package.
[1570:3D70][2022-02-15T16:41:25]e000: Error 0x80070057: Failed to configure per-machine MSI package.
[1570:3D70][2022-02-15T16:41:25]i319: Applied execute package: Microsoft.NET.Workload.Mono.ToolChain.Manifest_6.0.200.6.0.2_mauipre.1.22102.15_x64.msi, result: 0x80070057, restart: None
[1570:3D70][2022-02-15T16:41:25]e000: Error 0x80070057: Failed to execute MSI package.```

**Comment by ItsPizzaTime1501** [comment]
welp I think pipelines hates this PR or somethings

**Comment by ItsPizzaTime1501** [comment]
I truly cannot figure out what the hells going wrong with this anymore so I'll just wait for someone to see this I guess

**Comment by zachcarp** [comment]
> I truly cannot figure out what the hells going wrong with this anymore so I'll just wait for someone to see this I guess

I'm taking a look now. Sorry about this PR causing you issues. It's failing because the installation is failing during our automated test. This can be caused by a multitude of reasons - many of which we can't automate. When it has the "Needs-Attention" label it pops up for one of us to investigate.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
​

**Comment by ItsPizzaTime1501** [comment]
Closing at it seems to be an issue with the installer.

**Pull request closed without merging**
