### PR TITLE
New version: Ablaze.Floorp.Daylight version 11.9.0

### PR DESCRIPTION
**Pull request by Hibi-10000**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137495)

### CODE REVIEW

**Comment by Hibi-10000** [comment]
- #133371

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-01T16:22:04.3724485Z Processing manifest: manifests\a\Ablaze\Floorp\Daylight\11.7.1
 2024-02-01T16:22:04.3734307Z -----------------------------------------------------
 2024-02-01T16:22:04.3739342Z Status: Started
 2024-02-01T16:22:04.3747836Z Manifest file is Deleted
 2024-02-01T16:22:04.7803699Z Status: Completed
 2024-02-01T16:22:04.7818214Z ##[error] Result: Failed
 2024-02-01T16:22:04.7847023Z ##[error] Sequence contains no elements
 2024-02-01T16:22:04.8629023Z ##[error]Manifest Validation Failed

(Automated response - build 694.)

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 694.)

**Comment by Hibi-10000** [comment]
- #139206

**Pull request closed without merging**
