### PR TITLE
Zoom.Zoom version 5.14.0.13888

### PR DESCRIPTION
**Pull request by BrandonWanHuanSheng**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101100)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
What is App and Feature Entries? How to I find app and feature entries?

**Comment by BrandonWanHuanSheng** [comment]
Most likely, this wingetcreate does not replace the version.

**Comment by FaserF** [comment]
> Most likely, this wingetcreate does not replace the version.

You have changed the display name version, but not the GUID of the application. This also has changed for all installers. Most likely the check will fail again.

**Comment by FaserF** [comment]
This PR is going to fix #101028

**Comment by BrandonWanHuanSheng** [comment]
Successful created the manifest. I can see what is happening on Azure Pipeline.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
