### PR TITLE
Add manifest file for Mozilla Firefox (Catalan - Valencia) v79.0 x64

### PR DESCRIPTION
**Pull request by mehtanisarg369**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2724)

### CODE REVIEW

**Comment by mehtanisarg369** [comment]
Hi @KevinLaMS, @JohnMcPMS,

I am a bit curious about the 'Internel-Error' being encountered on some manifest files. I've tried to take a look at the documentation, but I'm still a bit unclear about the error being encountered. Could you please let me know what are the possible reasons for a manifest file encountering 'Internal-Error'?

**Comment by JohnMcPMS** [comment]
@mehtanisarg369 , we have a known bug that we cannot deploy a fix for due to external reasons.  It requires us to manually re-run the validation when it occurs.  All Internal-Error bugs are our issue to look at, so if you encounter one you don't need to do anything, we will take care of it.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
