### PR TITLE
New version: Elgato.WaveLink version 1.8.2.730

### PR DESCRIPTION
**Pull request by krystofkrticka**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`? image
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

### CODE REVIEW

**Comment by krystofkrticka** [comment]
Probably CDN issue since when I download the installer it shows correct hash.

**Comment by krystofkrticka** [comment]
This has to be CDN problem, either in US or EU, because right now I downloaded the file again and it shows this hash to me `E68969358F368A58B2277E4980CF993C85E51335D50721092C384CCB8ED46720`, and I probably downloaded the file from european servers.

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 11:24:15 AM:  > 2023-09-06 11:24:15.696 [CLI ] Package hash verification failed. SHA256 in manifest [e68969358f368a58b2277e4980cf993c85e51335d50721092c384ccb8ed46720] does not match download [d07b10c5725d82176d6ca603ab9be767bbade10347c1ba358c35d2a98bc8d643]

**Comment by stephengillie** [comment]
Manually downloading gives the `D07` hash:
```
PS C:\ManVal> get-fileHash .\Installers\WaveLink_1.8.2.730_x64.msi

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          D07B10C5725D82176D6CA603AB9BE767BBADE10347C1BA358C35D2A98BC8D643       C:\ManVal\Installers\WaveLink_1…
```

I'm unsure of the best route to proceed down:
- Leaving the hash won't let it pass validation. It hasn't got far enough for manual validation. 
- Updating the hash would let it pass validation, but possibly not available for a large number of users.

**Comment by krystofkrticka** [comment]
This is what I got in Windows Sandbox right now image

**Comment by krystofkrticka** [comment]
I can't do anything about this since I always get the same hash as is in manifest submitted in PR

**Pull request closed without merging**
