### PR TITLE
Add OpenShift Client 4.16.9

### PR DESCRIPTION
**Pull request by al-lac**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/169479)

### CODE REVIEW

**Comment by al-lac** [comment]
@RickJWagner can you review this?

**Review by RickJWagner — APPROVED** [review]
/lgtm

**Comment by RickJWagner** [comment]
Thank you for your quick and thorough work, @al-lac.

The PR looks good, thanks again for your efforts.

**Review by RickJWagner — APPROVED** [review]
This PR looks good.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
