### PR TITLE
New version: LinwoodCloud.Butterfly version 1.5.1

### PR DESCRIPTION
**Pull request by CodeDoctorDE**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/86794)

### CODE REVIEW

**Comment by CodeDoctorDE** [comment]
What should I do?

**Comment by stephengillie** [comment]
Hi @CodeDoctorDE, 

This package appears to have a dependency on one or more Microsoft C++ Redistributable packages. When running in a clean sandbox, it installed successfully, but did not run, erroring for msvcp140.dll and vcruntime140.dll. If this package has this dependency, can you add the correct [Microsoft.VCRedist](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/VCRedist) package as a package dependency to the manifest? Here is an [example](https://github.com/microsoft/winget-pkgs/blob/92b8d5d7727aa641aa3d758dbd653a4c8ba4ec8c/manifests/v/VMware/WorkstationPro/16.2.3/VMware.WorkstationPro.installer.yaml#L20-L23).

**Comment by CodeDoctorDE** [comment]
This version should work the same as LinwoodCloud.Butterfly.Nightly. I released the version a few weeks ago. And there are no dependencies.

**Comment by CodeDoctorDE** [comment]
:+1:

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
