### PR TITLE
Removed x64 Version

### PR DESCRIPTION
**Pull request by danijeljw**
- Removed x64
- Provided support for x86 instead
- x86 provides application that can be installed on x86 or x64
- Will update package to support both when package manager can support both versions in single YML file

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1278)

### CODE REVIEW

**Comment by WSLUser** [comment]
Please create a x64 variant for now. I would never install a 32 bit app on my 64 bit computer unless it's the only option for the software. In that case, it would behoove me to find a better comparable app.

**Review by ghost — APPROVED** [review]
Validation has completed

**Comment by EwoutH** [comment]
Why did this get merged?! x86 applications on a x64 system carry serious performance penalties, especially when SIMD intrinsics or assembly are involved.

**Comment by ocdtrekkie** [comment]
It looks like all the later versions are the x64 version. So while this PR should not have been merged, it's pointless in the long run?

**Pull request merged**
