### PR TITLE
Remove: Microsoft.ROpen version 4.0.2.0

### PR DESCRIPTION
**Pull request by coolplaylinbot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136928)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://mran.blob.core.windows.net/install/mro/4.0.2/Windows/microsoft-r-open-4.0.2.exe 
Status Code: 

(Automated message - build 671)

**Comment by stephengillie** [comment]
@CoolPlayLin

**Comment by stephengillie** [comment]
URL: https://mran.blob.core.windows.net/install/mro/4.0.2/Windows/microsoft-r-open-4.0.2.exe 
Response status code does not indicate success: 404 (The specified resource does not exist.).

(Automated message - build 671)

**Comment by CoolPlayLin** [comment]
Hi @stephengillie
It seems this is https://github.com/microsoft/microsoft-r-open, But I do know where I can download newer version.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
