### PR TITLE
New package: LGUG2Z.komorebi.Nightly version 0.1.28-dev.0

### PR DESCRIPTION
**Pull request by LGUG2Z**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161695)

### CODE REVIEW

**Comment by LGUG2Z** [comment]
I believe that this is expected behaviour, please see the last PR updating the stable release for example: https://github.com/microsoft/winget-pkgs/pull/158805

**Comment by LGUG2Z** [comment]
Is it possible to get some more detailed feedback about what this validation error actually is? I don't have any issues when installing this manifest locally

**Comment by sitiom** [comment]
It seems like the package version does not match the display version on the installer:
image

**Review by sitiom — CHANGES_REQUESTED** [review]
It seems like the package version does not match the display version on the installer:
image

**Comment by Trenly** [comment]
image

**Comment by amnweb** [comment]
> > 2024-07-08 00:44:53.176 [FAIL] Installer failed security check. Url: https://github.com/LGUG2Z/komorebi/releases/download/nightly/komorebi-nightly-x86_64.msi Result: 0x80004005
> > 2024-07-08 00:44:53.176 [CLI ] Terminating context: 0x8a15002d at D:\a_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6
> 
> image


MS Defender is worst part of Windows ever made.

image

**Comment by LGUG2Z** [comment]
Could we trigger another validation rerun please? We have seen these sorts of false positives before when submitting updates to the stable release.

**Comment by LGUG2Z** [comment]
Thanks for helping us along as always Stephen!

**Comment by stephengillie** [comment]
Verify:
image
image

**Review by stephengillie — DISMISSED** [review]

**Comment by LGUG2Z** [comment]
I think this is alright to merge - the error logs in the screenshot are non-blocking and I think are related specifically to running in a virtualized environment (made a note to look into this anyway since I'm sure some people want to run this in virtualized envs).

For the versioning, I think we'll drop the `-dev.0` suffix in nightly development versions from `0.1.29` onwards, so in the future this is simplified and we just have `MAJOR.MINOR.FIX` without anything extra for the Nightly package + installer as we do for the Stable package.

**Comment by sitiom** [comment]
> Could we trigger another validation rerun please? We have seen these sorts of false positives before when submitting updates to the stable release.

Note: You can do a rerun yourself by closing and re-opening the PR

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
