### PR TITLE
New version: DenoLand.Deno version 1.39.2

### PR DESCRIPTION
**Pull request by coolplaylinbot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132781)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-04 20:13:46.556 [FAIL] Installer failed security check. Url: https://github.com/denoland/deno/releases/download/v1.39.2/deno-x86_64-pc-windows-msvc.zip Result: 0x80004005

(Automated response - build 525.)

**Comment by stephengillie** [comment]
Hi @coolplaylinbot,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 525.)

**Comment by CoolPlayLin** [comment]
CC @kt3k

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
