### PR TITLE
[timschneeb.GalaxyBudsClient] Folder Rename and renamed version 4.2.1-df8e90 files

### PR DESCRIPTION
**Pull request by bioluks**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? - No, but a PR - see PR #153569

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---
This is a series of PR I will update other versions as well. I'm doing everything according to your publishing requirements and seriously hope the checks don't fail.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/154302)

### CODE REVIEW

**Comment by bioluks** [comment]
Waiting for this to be merged so there are no file conflicts because of the different folder name.

**Comment by bioluks** [comment]
This pipeline needs to be updated for multi-file manifests.

**Comment by stephengillie** [comment]
>  The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.

This PR will need to be split across 6 more PRs to proceed.

> This pipeline needs to be updated for multi-file manifests.

Please feel free to create an Issue with this Feature-Request.

**Comment by Trenly** [comment]
> Please feel free to create an Issue with this Feature-Request.

There's already a request
* https://github.com/microsoft/winget-pkgs/issues/125


> This PR will need to be split across 6 more PRs to proceed.

* https://github.com/microsoft/winget-pkgs/pull/154340
* https://github.com/microsoft/winget-pkgs/pull/154341
* https://github.com/microsoft/winget-pkgs/pull/154342
* https://github.com/microsoft/winget-pkgs/pull/154343
* https://github.com/microsoft/winget-pkgs/pull/154344
* https://github.com/microsoft/winget-pkgs/pull/154345
* https://github.com/microsoft/winget-pkgs/pull/154346
* https://github.com/microsoft/winget-pkgs/pull/154347
* https://github.com/microsoft/winget-pkgs/pull/154348
* https://github.com/microsoft/winget-pkgs/pull/154349
* https://github.com/microsoft/winget-pkgs/pull/154350
* https://github.com/microsoft/winget-pkgs/pull/154351
* https://github.com/microsoft/winget-pkgs/pull/154352
* https://github.com/microsoft/winget-pkgs/pull/154353

**Comment by bioluks** [comment]
I was having a hard time understanding the PR procedure since I'm also new to collaborating on open-source projects; thanks for the help @Trenly. Will update the file contents separately after the merge of those PR's.

**Comment by Trenly** [comment]
> I was having a hard time understanding the PR procedure since I'm also new to collaborating on open-source projects; thanks for the help @Trenly. Will update the file contents separately after the merge of those PR's.

Keep in mind that the `Publisher` field in the manifest should match what gets written to control panel, so when you're making the updates, it should still stay as `ThePBone` to ensure the package can still be accurately upgraded by WinGet
```
--> Comparing ARP Entries

DisplayName                                           DisplayVersion Publisher ProductCode                      Scope
-----------                                           -------------- --------- -----------                      -----
Galaxy Buds Manager (Unofficial) 4.5.4-1dfedf (64bit) 4.5.4-1dfedf   ThePBone  Galaxy Buds Manager (Unofficial) Machine
```

**Comment by Trenly** [comment]
> Out of curiosity: since his GitHub account changed, including the repo where he updates Galaxy Buds Manager, shouldn't we have to change that as well, eventually one day? It says this openly on ThePBone's profile: "I changed my username! You can find my current GitHub account here: [@timschneeb](https://github.com/timschneeb)"
> 
> I get it, if we change the publisher existing users won't be able to upgrade via WinGet. If we don't change it the downside is obviously the old username that's not in use anymore. I'll keep the Publisher name for now like you said since I have no logical alternative in mind myself.

If you check the URLs to the repo, you'll notice that they all still work and redirect you to the correct repository - https://github.com/ThePBone/GalaxyBudsClient will redirect you to https://github.com/timschneeb/GalaxyBudsClient automatically

Ideally, @timschneeb would change the NSIS script to reference the new GitHub alias, which would then make new releases have the updated Publisher in Control Panel

**Pull request closed without merging**
