### PR TITLE
AxisCommunications.MediaControl version 7.5.41

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/108025)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation failed with:
> Faulting application name: AxisControlPanelLauncher.exe, version: 1.2.0.0, time stamp: 0x55102617 
> Faulting module name: AxisControlPanelLauncher.exe, version: 1.2.0.0, time stamp: 0x55102617 
> Exception code: 0xc0000005 
> Fault offset: 0x000017ac 
> Faulting process id: 0x0x1FF4 
> Faulting application start time: 0x0x1D98EB3DDB496D9 
> Faulting application path: C:\Program Files (x86)\Axis Communications\AXIS Media Control Embedded\setup\AxisControlPanelLauncher.exe 
> Faulting module path: C:\Program Files (x86)\Axis Communications\AXIS Media Control Embedded\setup\AxisControlPanelLauncher.exe 
> Report Id: a46230ed-fdfd-4dd5-9aeb-8446c7f80f99 
> Faulting package full name:  
> Faulting package-relative application ID:

**Comment by upintheairsheep** [comment]
> This application installed normally, but logged this when launched:
> 
> > Faulting application name: AxisControlPanelLauncher.exe, version: 1.2.0.0, time stamp: 0x55102617
> > Faulting module name: AxisControlPanelLauncher.exe, version: 1.2.0.0, time stamp: 0x55102617
> > Exception code: 0xc0000005
> > Fault offset: 0x000017ac
> > Faulting process id: 0x0x1FF4
> > Faulting application start time: 0x0x1D98EB3DDB496D9
> > Faulting application path: C:\Program Files (x86)\Axis Communications\AXIS Media Control Embedded\setup\AxisControlPanelLauncher.exe
> > Faulting module path: C:\Program Files (x86)\Axis Communications\AXIS Media Control Embedded\setup\AxisControlPanelLauncher.exe
> > Report Id: a46230ed-fdfd-4dd5-9aeb-8446c7f80f99
> > Faulting package full name:
> > Faulting package-relative application ID:
> 
> * Does this package require audio?

I guess. I cannot understand this manifest as it only gives me offsets.

**Comment by upintheairsheep** [comment]
> This application installed normally, but logged this when launched:
> 
> > Faulting application name: AxisControlPanelLauncher.exe, version: 1.2.0.0, time stamp: 0x55102617
> > Faulting module name: AxisControlPanelLauncher.exe, version: 1.2.0.0, time stamp: 0x55102617
> > Exception code: 0xc0000005
> > Fault offset: 0x000017ac
> > Faulting process id: 0x0x1FF4
> > Faulting application start time: 0x0x1D98EB3DDB496D9
> > Faulting application path: C:\Program Files (x86)\Axis Communications\AXIS Media Control Embedded\setup\AxisControlPanelLauncher.exe
> > Faulting module path: C:\Program Files (x86)\Axis Communications\AXIS Media Control Embedded\setup\AxisControlPanelLauncher.exe
> > Report Id: a46230ed-fdfd-4dd5-9aeb-8446c7f80f99
> > Faulting package full name:
> > Faulting package-relative application ID:
> 
> * Does this package require audio?

Add an audio hardware dependency

**Comment by denelon** [comment]
Supporting custom hardware in validation is "Not Planned".
* https://github.com/microsoft/winget-pkgs/issues/199504

**Pull request closed without merging**
