### PR TITLE
New version: JackieLiu.NotepadsApp version 1.4.6.0

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### ARP entries are correct.

Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/winget-pkgs-automation)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/33686)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by palenshus** [comment]
This has a dependency on Microsoft.NET.Native.Framework.2.2, which will only be present on some user machines. Still approving this one as a one-off

**Pull request merged**
