### PR TITLE
Remove: Mp3tag.Mp3tag version 3.24

### PR DESCRIPTION
**Pull request by SpecterShell**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/160971)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://download.mp3tag.de/mp3tagv324setup.exe 
OK

(Automated message - build 911)

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/pull/160966#issuecomment-2200628680

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://download.mp3tag.de/mp3tagv324setup.exe 
Status Code: 200

(Automated message - build 886)

**Comment by SpecterShell** [comment]
> [#160966 (comment)](https://github.com/microsoft/winget-pkgs/pull/160966#issuecomment-2200628680)

Sorry I forgot to mention that: All the links to the non-latest versions are redirected to the homepage.

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
