### PR TITLE
Remove version: CCTV.CBox version 6.0.3.0

### PR DESCRIPTION
**Pull request by DuckDuckStudio**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/198758)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://download.cntv.cn/cbox/v6/ysyy_v6.0.3.0_1001_setup_x64.exe 
Response Error: The remote server returned an error: (403) Forbidden.

(Automated message - build 923)

**Comment by stephengillie** [comment]
Hi @DuckDuckStudio,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 904.)

**Comment by DuckDuckStudio** [comment]
### See https://github.com/microsoft/winget-pkgs/pull/198735#issue-2737673311

(About https://github.com/microsoft/winget-pkgs/labels/Needs-Author-Feedback )

**Comment by stephengillie** [comment]
Our policy is generally that these have to wait for 7 days, in case anyone submits an update in that time.

**Comment by DuckDuckStudio** [comment]
> Our policy is generally that these have to wait for 7 days, in case anyone submits an update in that time. 

I know, it's just that this tag always keeps my automation informed me...

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
In that case, we can expedite.

**Pull request merged**
