### PR TITLE
Fix WireGuard spellings and URLs

### PR DESCRIPTION
**Pull request by zx2c4**
I am the upstream maintainer of this software. This commit fixes up wrong information and wrong spelling, and adds the other supported architectures. Fortunately this is being caught before this particular package has any widespread usage.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/5718)

### CODE REVIEW

**Comment by zx2c4** [comment]
> ##[error] The pull request contains more than one manifest file.

This actually isn't true. This PR cleans up old/broken manifests while adding a single working one. So likely the validator here will need to be overridden.

**Comment by zx2c4** [comment]
CC @ItzLevvie - you might have to intervene to force this one.

**Comment by KevinLaMS** [comment]
I think the problem is with the multiple manifest submissions.  If we remove 1 file at a time, it should work.

**Comment by zx2c4** [comment]
Yes. So you want me to submit 4 pull requests?

**Comment by KevinLaMS** [comment]
I cannot do the merge.  Back end tooling requires that it pass the automated test pass.  If we bypass it, it breaks stuff.  

I also notice that the PR includes multiple architectures.  At this time, we only support a single architecture.  :(
We should comment out arm/arm64 and x86 for now.

I am sorry it is a pain.

**Comment by zx2c4** [comment]
Okay. I'll try submitting a PR that simply removes WireGuard entirely. Then after maybe I can add it in successfully.

**Comment by zx2c4** [comment]
Just submitted https://github.com/microsoft/winget-pkgs/pull/5816 . Let's see if that works better.

**Comment by zx2c4** [comment]
Okay I've split this into 6 PRs:

https://github.com/microsoft/winget-pkgs/pull/5817
https://github.com/microsoft/winget-pkgs/pull/5818
https://github.com/microsoft/winget-pkgs/pull/5819
https://github.com/microsoft/winget-pkgs/pull/5820
https://github.com/microsoft/winget-pkgs/pull/5821
https://github.com/microsoft/winget-pkgs/pull/5822

After those are merged, I'll close this original one.

**Comment by KevinLaMS** [comment]
done.  feel free to close

**Comment by zx2c4** [comment]
Thanks!

**Pull request closed without merging**
