### PR TITLE
New package: orbitalsatelite.HOIC version 2.1.003

### LINKED ISSUE #156116: [Package Request]: HOIC (High Orbit Ion Cannon)
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://sourceforge.net/projects/high-orbit-ion-cannon/files/latest/download
Publisher: [Anonymous](https://en.wikipedia.org/wiki/High_Orbit_Ion_Cannon)
Package Name: HOIC
Description: An open-source network stress testing tool
Package Version: `2.1.003`
Installer URL: https://altushost-swe.dl.sourceforge.net/project/high-orbit-ion-cannon/HOIC.zip?viasf=1

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Related (but failed) #156116

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

## Manual validation

image

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/199295)

### CODE REVIEW

**Comment by Dragon1573** [comment]
Further investigation needed @stephengillie. 🙏🏼

Is it caused by the [detected malware](https://learn.microsoft.com/en-us/windows/package-manager/package/repository#installers-scan-test)?

> [!WARNING]
>
> _Source Forge_ detected there's a malware included in the package.
>
> image

**Comment by stephengillie** [comment]
Hi @Dragon1573,

Unfortunately, I have no insight into this label.

**Comment by Dragon1573** [comment]
> The package manager bot determined there was an issue with one of the installers listed in the url field, and cannot continue.
> 
> The application included in this pull request failed to pass the [Installers Scan](https://docs.microsoft.com/en-us/windows/package-manager/package/winget-validation) test. This test is designed to ensure that the application installs on all environments without warnings. For more details on this error, see [Binary validation errors](https://docs.microsoft.com/en-us/windows/package-manager/package/binary-validation-errors). Please check to ensure the installer URL is correct and update the URL and the Hash if a change is made.
> 
> Template: msftbot/validationError/installers/binaryValidation

> [!CAUTION]
> 
> Close with reason: **Malware detected**.
>
> The installer file is detected as a malware (false positive). It prevents the manifest from passing the validation pipeline. Pull request can be closed.

**Pull request closed without merging**
