### PR TITLE
New package: Rem0o.FanControl version 181

### PR DESCRIPTION
**Pull request by lm-gh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/139277)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/139277)

### CODE REVIEW

**Comment by lm-gh** [comment]
@Rem0o hope this PR is fine for you :)

**Comment by Rem0o** [comment]
Yeah that's fine.

**Comment by stephengillie** [comment]
image

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
This was approved in error. It needs `Microsoft.DotNet.DesktopRuntime.8` as a dependency.

**Comment by lm-gh** [comment]
> image

will fix it here https://github.com/microsoft/winget-pkgs/pull/139480

**Comment by lm-gh** [comment]
> This was approved in error. It needs `Microsoft.DotNet.DesktopRuntime.8` as a dependency.

will fix it here https://github.com/microsoft/winget-pkgs/pull/139480

**Pull request merged**
