### PR TITLE
CenSoft.HostTE version 1.0.0

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/108040)

### CODE REVIEW

**Comment by upintheairsheep** [comment]
Note to self: https://github.com/google/perfetto/releases/download/v34.0/windows-amd64.zip

**Comment by upintheairsheep** [comment]
https://github.com/google/filament/releases/download/v1.36.0/filament-v1.36.0-windows.tgz

**Comment by upintheairsheep** [comment]
https://github.com/google/gapid/releases/download/v1.6.1/gapid-1.6.1-windows.msi

**Comment by upintheairsheep** [comment]
https://github.com/google/cdc-file-transfer/releases/download/v1.0.0/cdc-file-transfer-binaries-v1.0.0-x64.zip
https://github.com/google/aukera/releases/download/v1.0.2/aukera_windows.exe
https://github.com/google/cabbie/releases/download/v1.0.5/cabbie.exe

**Comment by stephengillie** [comment]
This package has an interactive server:
```
HostTE startup [2724], listening on [WinDev2302Eval:8080] for connections.
Recieved signal [0], no active TE sessions, stopping.
```
I'm guessing that this interactive server might be why the `Internal-Error-Dynamic-Scan` label is applied.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
