### PR TITLE
Add Firefox Developer Edition 77.0b9

### PR DESCRIPTION
**Pull request by SoftCreatR**
Auto Generated by softcreatr@winget.it on Wed, 27 May 2020 16:16:15 +0000

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1224)

### CODE REVIEW

**Comment by suneetk92** [comment]
tag is missing
```Channel: beta```

source: https://hacks.mozilla.org/2017/04/simplifying-firefox-release-channels/
 Developer Edition is based on the Beta build

**Comment by SoftCreatR** [comment]
> tag is missing
> `Channel: beta`
> 
> source: https://hacks.mozilla.org/2017/04/simplifying-firefox-release-channels/
> Developer Edition is based on the Beta build

Channel isn't supported by winget, yet.

**Comment by suneetk92** [comment]
according to ManifestSpec is does.
https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv0.1.md

**Comment by SoftCreatR** [comment]
> according to ManifestSpec is does.
> https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv0.1.md

Ignore it. It does not work yet.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
