### PR TITLE
New version: lyswhut.lx-music-desktop version 1.14.0

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/29248)

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
Any idea why is it failing?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
This is what I see:
image

**Comment by vedantmgoyal2009** [comment]
This message if from winget or from your script?

**Comment by ItzLevvie** [comment]
> This message if from winget or from your script?

It's from WinGet; same from https://github.com/microsoft/winget-pkgs/pull/27931:
image

**Comment by vedantmgoyal2009** [comment]
Should we remove all versions of this package?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> Should we remove all versions of this package?

`1.13.0` installs fine, so no:
image

**Comment by vedantmgoyal2009** [comment]
@ItzLevvie It passed the validation.

**Review by ItzLevvie — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
