### PR TITLE
Remove version: WinDirStat.WinDirStat version 1.1.2

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/184048)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://sourceforge.net/projects/windirstat/files/windirstat/1.1.2%20installer%20re-release%20(more%20languages!)/windirstat1_1_2_setup.exe/download 
Status Code: 200

(Automated message - build 897)

**Comment by stephengillie** [comment]
Close with reason: Package still available.;

**Comment by assarbad** [comment]
> Close with reason: Package still available.;

@stephengillie is it still possible to remove it even though the reasoning with the URLs was bogus? I'm one of the co-owners/maintainers of the WinDirStat project

**Comment by stephengillie** [comment]
> @ stephengillie is it still possible to remove it even though the reasoning with the URLs was bogus? I'm one of the co-owners/maintainers of the WinDirStat project

Sure. We have no problem with a package version being removed for almost any reason. Should this PR and similar ones be reopened, or do you want to make new PRs for the removals?

**Comment by assarbad** [comment]
I can create a new PR, no big deal.

**Pull request closed without merging**
