### PR TITLE
Add Nvidia Broadcast

### PR DESCRIPTION
**Pull request by ms-jb**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----
References PR #5157

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/18853)

### CODE REVIEW

**Comment by ms-jb** [comment]
> Hello @ms-jb,
> The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.

I'm looking for some assistance debugging this issue; the ADO pipeline doesn't provide any additional feedback. I just see "Result: Failed" under Installation Validation
https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=185503&view=logs&j=871b4eed-22de-5cb6-c1c8-82f190de633f&t=58bdf892-4e45-5ba7-4782-31912f95e167&l=65

**Comment by jussij** [comment]
I too ran into a few issues submitting my packages and what I found that helped was the Sandbox Testing tool.

I used the 'Sandbox Testing' details found on this page: https://github.com/microsoft/winget-pkgs

**Comment by ms-jb** [comment]
> I too ran into a few issues submitting my packages and what I found that helped was the Sandbox Testing tool.
> 
> I used the 'Sandbox Testing' details found on this page: https://github.com/microsoft/winget-pkgs

Thank you, that helped! It looks like this package won't install unless an Nvidia GPU is detected, so the validation will fail. I'll explore some alternatives.

**Review by OfficialEsco — APPROVED** [review]
Cheater! I might have to steal this trick 👀

**Comment by Neikon** [comment]
there is new version 1.3 https://www.nvidia.com/es-es/geforce/broadcasting/broadcast-app/?ref=winstall

**Comment by ItzLevvie** [comment]
> there is new version 1.3 https://www.nvidia.com/es-es/geforce/broadcasting/broadcast-app/?ref=winstall

https://github.com/microsoft/winget-pkgs/pull/27010

**Pull request merged**
