### PR TITLE
New version: Taiko2k.TauonMusicBox version 7.6.3

### PR DESCRIPTION
**Pull request by Taiko2k**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101378)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
Does it have x86?

**Comment by Taiko2k** [comment]
@BrandonWanHuanSheng I only build a 64 bit build.

**Comment by BrandonWanHuanSheng** [comment]
It does not have x86. I visited that page "https://github.com/Taiko2k/TauonMusicBox/releases"

**Comment by Taiko2k** [comment]
@BrandonWanHuanSheng Its x64 as in x86-64

**Comment by BrandonWanHuanSheng** [comment]
@Taiko2k But winget will not show up x86 into x64. If you do like that. This one most likely choose Neutral.

**Comment by BrandonWanHuanSheng** [comment]
This is a problem with winget client! ⚠️ Winget does not show up x86 instead x64 Installer.
Screenshot (127)
When there is x64 installer only.

**Comment by Taiko2k** [comment]
I can rename it to use x86-64, I assume I will need to re-run the action?

**Comment by BrandonWanHuanSheng** [comment]
If you rename it, I think it might unable on x64. But I don't recommend to do that.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
