### PR TITLE
Fixed Malwarebytes download url

### PR DESCRIPTION
**Pull request by KaranKad**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14358)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
We had a static url before, but Malwarebytes deleted the file very quickly so this is sorta the best solution

**Comment by KaranKad** [comment]
#14340 winget cannot download from this url for some reason.
I am getting the same issue.
image

**Comment by OfficialEsco** [comment]
Hmm, Denelon said there was a few issues with the pipeline or something like that, i think this is a temporary issue when using winget

**Comment by denelon** [comment]
I've seen a few issues that seem to be impacting "download". I'm not sure if it's transient or deterministic yet. You can change the network settings from "default" to "wininet" to test.

**Pull request closed without merging**
