### PR TITLE
Update tencent.wechat to 3.3.0.93

### PR DESCRIPTION
**Pull request by lychichem**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/18005)

### CODE REVIEW

**Comment by lychichem** [comment]
I can confirm the SHA256 is right. But tencent just give this url, I cannot find a direct link.
image

**Comment by ItzLevvie** [comment]
It installed fine for me (no hash errors):
image

**Comment by ItzLevvie** [comment]
cc @denelon

**Comment by lychichem** [comment]
Can anyone run  the pipeline again to check this PR?

**Pull request closed without merging**
