### PR TITLE
add xmake 2.3.5

### PR DESCRIPTION
**Pull request by eaglu**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2640)

### CODE REVIEW

**Comment by perplexityjeff** [comment]
You want to add 

Switches:
      Silent: /S
      SilentWithProgress: /S

And change the installer to Nullsoft probably.

**Comment by waruqi** [comment]
A new pr for xmake v2.3.6, see https://github.com/microsoft/winget-pkgs/pull/2941

**Comment by perplexityjeff** [comment]
I'd suggest to add the switches to the end of the file as well.

Switches:
      Silent: /s
      SilentWithProgress: /s

**Pull request closed without merging**
