### PR TITLE
Update package Cretezy.lazyjj to v0.1.4

### LINKED ISSUE #155901: [Update Request]: Cretezy.lazyjj at v0.1.4
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Cretezy.lazyjj

### Package Version

0.1.4

### Please describe the changes you would like to see

Update to Cretezy.lazyjj to 0.1.4 - https://github.com/Cretezy/lazyjj/releases/download/v0.1.4/lazyjj-v0.1.4-x86_64-pc-windows-msvc.zip

### PR DESCRIPTION
**Pull request by RoscoP**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? Closes #155901 

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/155902)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-31 11:24:01.472 [FAIL] Installer failed security check. Url: https://github.com/Cretezy/lazyjj/releases/download/v0.1.4/lazyjj-v0.1.4-x86_64-pc-windows-msvc.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 882.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-06-03 08:39:34.149 [FAIL] Installer failed security check. Url: https://github.com/Cretezy/lazyjj/releases/download/v0.1.4/lazyjj-v0.1.4-x86_64-pc-windows-msvc.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 882.)

**Comment by stephengillie** [comment]
Sorry for the delay. `wingetbot run` wasn't listening to due to:

> Octokit was broken because comment id exceeded int maximum value for parsing JSON. A fix was submitted earlier, but we haven't got a NuGet package yet[.] 

- [@denelon on Gitter](https://matrix.to/#/!LEwByvxhTNZZcKeCCY:gitter.im/$c5J6uL4eU3A1Sy9vsPbUgBSahjnfLz6TDh98ZeW56G4?via=gitter.im&via=matrix.org&via=beeper.com)

**Review by stephengillie — DISMISSED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-06-11 05:17:11.040 [FAIL] Installer failed security check. Url: https://github.com/Cretezy/lazyjj/releases/download/v0.1.4/lazyjj-v0.1.4-x86_64-pc-windows-msvc.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 884.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-06-13 11:33:46.788 [FAIL] Installer failed security check. Url: https://github.com/Cretezy/lazyjj/releases/download/v0.1.4/lazyjj-v0.1.4-x86_64-pc-windows-msvc.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 885.)

**Review by stephengillie — APPROVED** [review]

**Comment by RoscoP** [comment]
Is this one ready to merge?

**Comment by stephengillie** [comment]
> Is this one ready to merge?

Yes, sorry. 

- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
