### PR TITLE
New version: maximmax42.CustomRP version 1.17.22

### PR DESCRIPTION
**Pull request by maximmax42**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150505)

### CODE REVIEW

**Comment by maximmax42** [comment]
Installs just fine on my end,

**Comment by stephengillie** [comment]
Hi @maximmax42,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 877.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-04-22 08:55:28.410 [FAIL] Installer failed security check. Url: https://github.com/maximmax42/Discord-CustomRP/releases/download/1.17.22/CustomRP.1.17.22.exe Result: 0x80004005

(Automated response - build 877.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
