### PR TITLE
Added Mazerator-Old 20200502

### PR DESCRIPTION
**Pull request by AwesomeKalin**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/19613)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
See https://github.com/microsoft/winget-pkgs/pull/19596#pullrequestreview-698617907.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Need to wait for dependency support to be added.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Adding another "request changes" review for filtering purposes.

**Comment by AwesomeKalin** [comment]
Stop stale

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
@denelon please remove `Azure-Pipeline-Passed`

**Review by ItzLevvie — APPROVED** [review]

**Review by OfficialEsco — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
@ItzLevvie this requires `Validation-Completed`

**Review by vedantmgoyal9 — APPROVED** [review]

**Pull request closed without merging**
