### PR TITLE
Squitch.Tess version 0.6.2

### PR DESCRIPTION
**Pull request by Squitch1**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/82081)

### CODE REVIEW

**Review by OfficialEsco — COMMENTED** [review]
image

**Comment by SquitchYT** [comment]
Hello, I don't have any problem on my local computer running on Windows 11.
I will investigate and come back later. Thanks for reporting this.

**Comment by SquitchYT** [comment]
After some investigation, it seem that this is a false positive due to the use of Inno Setup. https://stackoverflow.com/questions/68834409/program-installed-with-inno-setup-seen-as-trojan-wacatac-bml

**Comment by SquitchYT** [comment]
I have submitted my file to windows defender to correct this false positive

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
