### PR TITLE
Kiwix.Wikivoyage version 1.9.4.0

### PR DESCRIPTION
**Pull request by Jaifroid**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/54541)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Jaifroid** [comment]
@ItzLevvie This PR seems to have stalled. It says it needs moderator approval, but has already been approved by you. Also, the checks that have been undertaken don't look as detailed as usual (which may be the real reason for the block).

**Comment by ItzLevvie** [comment]
> @ItzLevvie This PR seems to have stalled. It says it needs moderator approval, but has already been approved by you. Also, the checks that have been undertaken don't look as detailed as usual (which may be the real reason for the block).

Azure Pipelines are currently limited to 20 PRs per run due to 800+ PRs being opened so it'll probably take a while for it to run on this PR.

**Comment by Jaifroid** [comment]
OK, thanks for explanation, I'll be patient!

**Comment by Jaifroid** [comment]
Thanks for the heads-up!

**Comment by Jaifroid** [comment]
@ItzLevvie Is this installers scan test failure a result of the unhealthy pipeline? The manifest validates locally for me, and I can install the app (see screenshot below). The test failure info suggests it failed a virus scan, but I've scanned the appxbundle locally and there are no warnings. I'm inclined to believe this is a testing software failure rather than a problem with this appxbundle.

image

**Comment by Jaifroid** [comment]
Scan information [here](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=292047&view=logs&j=871b4eed-22de-5cb6-c1c8-82f190de633f&t=523ceef4-ddf7-55a0-c83d-dd0f77b67744) is empty (see line with `Scan information: ''`):

```
3/16/2022 11:40:34 PM
Status: Completed
##[error] Installer https://github.com/kiwix/kiwix-js-windows/releases/download/v1.9.4-
Wikivoyage/KiwixWebAppWikivoyage_1.9.4.0_AnyCPU.appxbundle Scan information: ''
##[error] Result: Failed

```

**Comment by Jaifroid** [comment]
@msftrubengu I've already validated and installed this package, using this manifest, on my local machine. Is this still an issue with the pipeline, or is there a real issue identified with the package?

**Comment by Jaifroid** [comment]
All installing fine here (Windows 10, fully up-to-date):

image

**Comment by msftrubengu** [comment]
The issue is that the installer is returning a non-zero exit code 0x80072EFF (-2147012865)

**Comment by Jaifroid** [comment]
@msftrubengu  Well there are no exit codes or errors flagged when I install locally. So how do we fix this? The package is working fine both with the msix installer and with winget launched locally against this manifest. So it looks like a problem in the validator.

By the way, it's not the first time I've had such problems with msix packages -- see https://github.com/microsoft/winget-cli/issues/1987. At first I used installer type msix for Kiwix JS, Wikivoyage and Wikimed, but then these packages started to fail validation, and I was advised by @Trenly to change the installer type to appx. But now the packages appear to be failing with appx too.

**Review by ghost — APPROVED** [review]

**Comment by Jaifroid** [comment]
@msftrubengu Thank you, that did the trick! 🙏

**Pull request merged**
