### PR TITLE
Remove old version of JanDeDobbeleer.OhMyPosh

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/20311)

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
Why is it failing?

**Comment by denelon** [comment]
@vedantmgoyal2009 we're looking into this issue.

**Comment by denelon** [comment]
@vedantmgoyal2009 we've traced it down to one of the back end systems we call during validation. Once this gets resolved, we hope things will start running smoothly again. No ETA yet.

**Comment by vedantmgoyal2009** [comment]
Any progress on this?

**Comment by denelon** [comment]
@vedantmgoyal2009 we're still investigating this issue. We haven't isolated the root cause yet. It is related to one of our underlying dependencies for static analysis.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
I don't know if this is me, but I'm getting this prompt:
image

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/20311#pullrequestreview-712636165

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/20311#pullrequestreview-712636165

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
