### PR TITLE
qgisorg.qgis version 3.18.3

### PR DESCRIPTION
**Pull request by mluepkes**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15530)

### CODE REVIEW

**Comment by dpprdan** [comment]
@mluepkes @ItzLevvie Any idea why this got closed? Should we submit a new PR for QGIS 3.18.3?

**Comment by ItzLevvie** [comment]
cc @dpprdan: I forgot to put the reasoning here, but a folder for QGIS exists over at `manifests/o/OSGeo/QGIS`, so for 3.18.3; it should be `manifests/o/OSGeo/QGIS/3.18.3`

**Comment by dpprdan** [comment]
@ItzLevvie Oh right, got it! Thanks!

**Comment by dpprdan** [comment]
See #15885

**Pull request closed without merging**
