### PR TITLE
Add Nitro Pro 13.22.0.414

### PR DESCRIPTION
**Pull request by auanasgheps**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3261)

### CODE REVIEW

**Review by auanasgheps — COMMENTED** [review]
Remove second installer

**Comment by auanasgheps** [comment]
The package was generated using **Windows Package Manager YAML Generator**
However, I had to force URLs in HTTP and not HTTPS: the vendor does not provide HTTPS links.

**Comment by perplexityjeff** [comment]
In my opinion https should be mandatory for a download but you do do a checksum with SHA so I understand your point.

**Pull request merged**
