### PR TITLE
Add version: rhysd.actionlint version v1.6.24

### PR DESCRIPTION
**Pull request by rhysd**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/102052)

### CODE REVIEW

**Comment by rhysd** [comment]
@microsoft-github-policy-service agree

**Comment by rhysd** [comment]
This is the first release of [actionlint](https://github.com/rhysd/actionlint) for Winget.

**Comment by stephengillie** [comment]
I'm not able to find the cause for this error. Automatic validation passed, so the cause for the `Validation-Executable-Error` label is unclear. The package installs and runs normally on a Windows 11 VM.

**Review by stephengillie — APPROVED** [review]

**Review by sitiom — COMMENTED** [review]
Wrong `PackageVersion`. Duplicate of #101511 (Move to proper version).

**Pull request merged**
