### PR TITLE
Remove 1 of 2 'alpha'-designated version of 7-Zip from non-alpha listing

### PR DESCRIPTION
**Pull request by peterlewis**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [ ] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

PR to follow #3756 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3762)

### CODE REVIEW

**Comment by peterlewis** [comment]
Have included removal of both alpha versions in a single PR. I'm aware from what @yigitemres mentioned that a single file change per PR is preferred, but not sure if that includes deletions, such as this.

If it does then do just holler, and I'll split into two.

**Comment by peterlewis** [comment]
Hey @KevinLaMS - Here's the other part of the 7-Zip change, i.e. removing the alpha releases from the main listing.

**Comment by KevinLaMS** [comment]
@peterlewis   Great, thanks. 
To get past automation, can you have 1 delete manifest per PR.

**Comment by peterlewis** [comment]
Hah, now you're testing my Git-fu! Think I've managed to do what is required, albeit followed by a revert and then a revert of the revert! :)

**Comment by peterlewis** [comment]
PR for the other file is in as https://github.com/microsoft/winget-pkgs/pull/3807

**Pull request merged**
