### PR TITLE
GH-659 Remove Amazon AWSCLI

### PR DESCRIPTION
**Pull request by jamierocks**
The link that was used pointed to the **latest** 2.x release, rather
than a specific release. The current 2.x version is 2.0.15 (as of
yesterday), as such there is no benefit to continuing to provide this
manifest.

I took a cursory look to see if I could find any direct links, however
so far I've drawn a blank - I'll keep looking.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/682)

### CODE REVIEW

**Comment by chausner** [comment]
I guess it will have to be decided how to handle websites that don't provide persistent download links for specific versions. In those cases, whenever the software gets updated, users will get a verification error until the manifest gets updated, as well. I still think it is better to have these in the repository than not at all. Maybe the SHA256 and version properties in the manifest could be made optional for those websites that have changing download versions. In those cases, the client could print a warning that the download will not be verified.

**Comment by jamierocks** [comment]
Totally agree - however for the time being, I think its best to remove a (currently) erroneous manifest.

**Comment by KevinLaMS** [comment]
thanks for raising the  issue

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
