### PR TITLE
New version: goreleaser.nfpm 2.35.1

### PR DESCRIPTION
**Pull request by caarlos0**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131847)

### CODE REVIEW

**Comment by caarlos0** [comment]
it should be correct... the build logs don't give any details of what happened... how can I verify this?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 
> 2023-12-26 06:19:01.619 [FAIL] Installer failed security check. Url: https://github.com/goreleaser/nfpm/releases/download/v2.35.1/nfpm_2.35.1_Windows_x86_64.zip Result: 0x80004005

(Automated response - build 508.)

**Comment by stephengillie** [comment]
Hi @caarlos0,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 509.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
