### PR TITLE
Add PowerBI Agreements

### PR DESCRIPTION
**Pull request by Trenly**
Testing only

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132127)

### CODE REVIEW

**Comment by stephengillie** [comment]
>  Manifest Error: Field usage requires verified publishers. [Agreements]

**Comment by Trenly** [comment]
> > Manifest Error: Field usage requires verified publishers. [Agreements]

Yep; Just was checking to see if the changes the team was working on were published yet

**Comment by stephengillie** [comment]
Is this PR still needed for testing?

**Pull request closed without merging**
