### PR TITLE
New version: REALiX.HWiNFO version 8.14

### LINKED ISSUE #188214: [Update Request]: REALiX.HWiNFO version 8.14
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

REALiX.HWiNFO

### Package Version

8.14

### Please describe the changes you would like to see

There is a new release (8.14) available.
Here is the download link: https://sourceforge.net/projects/hwinfo/files/Windows_Installer/hwi64_814.exe/download

### PR DESCRIPTION
**Pull request by pr1sm8**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #188214

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/188215)

### CODE REVIEW

**Comment by pr1sm8** [comment]
Resolved https://github.com/microsoft/winget-pkgs/issues/188214

**Comment by pr1sm8** [comment]
force pushed the update to release date

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files\HWiNFO64\HWiNFO64.EXE returned exit code: 183

(Automated response - build 897.)

**Comment by pr1sm8** [comment]
> Automatic Validation ended with:
> 
> > Executable C:\Program Files\HWiNFO64\HWiNFO64.EXE returned exit code: 183
> 
> (Automated response - build 897.)

@stephengillie Excuse me for tagging, but what does this mean,
Does it mean that the application failed to launch?
I have run it in my machine started the program from cmd and i see no exit code: 183, what am i missing?

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @pr1sm8,

Sorry for the delay in responding. The validation pipeline is somewhat designed for Windows Forms, and add the https://github.com/microsoft/winget-pkgs/labels/Validation-Executable-Error link when the exit code is non-zero. But a non-zero exit code is common for CLI applications, so I usually pass exit codes below 1000. I"ve requested to push this upstream: 

- https://github.com/microsoft/winget-pkgs/issues/157749

**Pull request merged**
