### PR TITLE
Removes cloudflare.warp

### PR DESCRIPTION
**Pull request by paulober**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

As discussed in https://github.com/microsoft/winget-pkgs/pull/144984#event-12158788589 cloudflare did great work protecting their downloads agains a usage like widget. Therefore also the already added version of Cloudflare.Warp doesn't work anymore.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/145124)

### CODE REVIEW

**Comment by Trenly** [comment]
Please remove the `.validation` file from your PR

**Comment by paulober** [comment]
> Please remove the `.validation` file from your PR
> 
> 

Can I ask why?
For my understanding this is a relict of an automated process for generating the last release I just deleted.

**Comment by Trenly** [comment]
> > Please remove the `.validation` file from your PR
> 
> Can I ask why? For my understanding this is a relict of an automated process for generating the last release I just deleted.

Because the validation pipelines have special logic for handling them, and they cannot be removed in the same PR as a Manifest

**Comment by paulober** [comment]
Removed

**Comment by Trenly** [comment]
> Removed

It looks like it is still being modified - seems a newline was added at the end of the file

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 870)

**Review by Trenly — APPROVED** [review]

**Pull request merged**
