### PR TITLE
Installer Url 404: Cybelsoft.DriversCloud v11.1.2.0

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/53625)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Review by OfficialEsco — DISMISSED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Comment by ItzLevvie** [comment]
@wingebot run

**Comment by vedantmgoyal2009** [comment]
Hello, dumb bot, don't you know it is a draft pull request.

**Comment by OfficialEsco** [comment]
```
2022-04-03 07:28:41.449 [CLI ] Package hash verification failed. SHA256 in manifest [4c5aa0da383ed173699c4820c52001bfd72cd9a78a0571f1a6ef57d5a1a26dbb] does not match download [631953414b6792bcf6e1543b111d50a2c434e55e874ae04aa947a115c2715d71]
2022-04-03 07:28:41.455 [CLI ] Terminating context: 0x8a150011 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:17f
```

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
