### PR TITLE
Update: astral-sh.ruff version 0.3.1

### PR DESCRIPTION
**Pull request by frazar**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/143016)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @frazar,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 869.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\astral-sh.ruff__DefaultSource\ruff.exe returned exit code: 2
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\ruff.exe returned exit code: 2
> Installation failed with exit code -1978335187
> 2024-03-08 06:28:14.465 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.3.1/ruff-0.3.1-i686-pc-windows-msvc.zip Result: 0x80004005

(Automated response - build 869.)

**Comment by stephengillie** [comment]
Hi @frazar,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 869.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\astral-sh.ruff__DefaultSource\ruff.exe returned exit code: 2
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\ruff.exe returned exit code: 2
> Installation failed with exit code -1978335187
> 2024-03-08 06:28:14.465 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.3.1/ruff-0.3.1-i686-pc-windows-msvc.zip Result: 0x80004005

(Automated response - build 869.)

**Comment by frazar** [comment]
The installer package is just a zip file of the executable, ruff.exe.

No installation is required, but if you run ruff.exe without any argument, it will give exit code 2 (as intended) because some arguments must be supplied.

```
C:\Users\fzardi>ruff
Ruff: An extremely fast Python linter.

Usage: ruff [OPTIONS] <COMMAND>

Commands:
  check    Run Ruff on the given files or directories (default)
  rule     Explain a rule (or all rules)
  config   List or describe the available configuration options
  linter   List all supported upstream linters
  clean    Clear any caches in the current directory and any subdirectories
  format   Run the Ruff formatter on the given files or directories
  version  Display Ruff's version
  help     Print this message or the help of the given subcommand(s)

Options:
  -h, --help     Print help
  -V, --version  Print version

Log levels:
  -v, --verbose  Enable verbose logging
  -q, --quiet    Print diagnostics, but nothing else
  -s, --silent   Disable all logging (but still exit with status code "1" upon detecting diagnostics)

Global options:
      --config <CONFIG_OPTION>  Either a path to a TOML configuration file (`pyproject.toml` or `ruff.toml`), or a TOML
                                `<KEY> = <VALUE>` pair (such as you might find in a `ruff.toml` configuration file)
                                overriding a specific configuration option. Overrides of individual settings using this
                                option always take precedence over all configuration files, including configuration
                                files that were also specified using `--config`
      --isolated                Ignore all configuration files

For help with a specific command, see: `ruff help <command>`.

C:\Users\fzardi>echo %errorlevel%
2
```

However, it seems like the Windows Defender scan expects the exit code to be different from 2 and fails otherwise.

How can I fix this?

**Comment by stephengillie** [comment]
Hi @frazar,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-13 12:32:54.827 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF9F3CBC11F: (caller: 00007FF9F3A48D6F) LogHr(1) tid(d48) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF9F3BC2B08: (caller: 00007FF9F3C6BC20) Exception(1) tid(d48) 8A15005E ] 
> 2024-03-13 12:32:54.827 [REPO] Failed to open available source: msstore
> 2024-03-13 12:32:56.825 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF9F3BC2B08: (caller: 00007FF9F3C6BC20) Exception(1) tid(d48) 8A15005E 
> 2024-03-13 12:33:02.893 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF9D923C11F: (caller: 00007FF9D8FC8D6F) LogHr(1) tid(1118) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF9D9142B08: (caller: 00007FF9D91EBC20) Exception(1) tid(1118) 8A15005E ] 
> 2024-03-13 12:33:02.893 [REPO] Failed to open available source: msstore
> 2024-03-13 12:33:18.795 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.3.1/ruff-0.3.1-x86_64-pc-windows-msvc.zip Result: 0x80004005
> 2024-03-13 12:32:22.412 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!68F6535B: (caller: 68E61A80) LogHr(1) tid(1488) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!68FAB5DD: (caller: 690412BF) Exception(1) tid(1488) 8A15005E ] 
> 2024-03-13 12:32:22.412 [REPO] Failed to open available source: msstore
> 2024-03-13 12:32:23.961 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!68FAB5DD: (caller: 690412BF) Exception(1) tid(1488) 8A15005E 
> 2024-03-13 12:32:29.337 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!545A535B: (caller: 544A1A80) LogHr(1) tid(734) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!545EB5DD: (caller: 546812BF) Exception(1) tid(734) 8A15005E ] 
> 2024-03-13 12:32:29.337 [REPO] Failed to open available source: msstore
> 2024-03-13 12:32:44.478 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.3.1/ruff-0.3.1-i686-pc-windows-msvc.zip Result: 0x80004005

(Automated response - build 870.)

**Comment by frazar** [comment]
I guess this PR requires the manual approval of a moderator like its successor PR, #143774.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
