### PR TITLE
New package: SBRW.NFSW_GameLauncher version 2.2.2

### PR DESCRIPTION
**Pull request by MeTonaTOR**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/198541)

### CODE REVIEW

**Comment by MeTonaTOR** [comment]
@microsoft-github-policy-service agree

**Comment by MeTonaTOR** [comment]
@microsoft-github-policy-service agree [company="SBRW"]

**Comment by MeTonaTOR** [comment]
@microsoft-github-policy-service agree company="SBRW"

**Comment by stephengillie** [comment]
Hi @MeTonaTOR, 

Manual Validation ended with:
image

Is a dependency needed?

**Comment by stephengillie** [comment]
Verify while here:
image

**Comment by Trenly** [comment]
[Policy] zip-binary

**Comment by MeTonaTOR** [comment]
Hey @stephengillie

Yes, this file is actually optional, it was used on older method of obtaining compressed chunks of data. Now it mostlu fetches one single zip-compressed chunk of data that executable itself can manage to extract

**Comment by Trenly** [comment]
> Hey @stephengillie
> 
> Yes, this file is actually optional, it was used on older method of obtaining compressed chunks of data. Now it mostlu fetches one single zip-compressed chunk of data that executable itself can manage to extract

Even though it says it downloaded the file, any time I attempt to start the installer it gives the same message and never actually launches

**Pull request closed without merging**
