### PR TITLE
Dell.command monitor 10.9.1 4 a10 b4 de567824

### PR DESCRIPTION
**Pull request by dellclientopensource**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/113067&drop=dogfoodAlpha

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
#111634

**Comment by dellclientopensource** [comment]
Can you help us explain the issue in detail, so I can fix it ?

**Comment by BrandonWanHuanSheng** [comment]
https://github.com/microsoft/winget-pkgs/pull/112475#issuecomment-1644632620
https://github.com/microsoft/winget-pkgs/pull/112475#issuecomment-1644632620
https://github.com/microsoft/winget-pkgs/pull/112475#issuecomment-1642949658
https://github.com/microsoft/winget-pkgs/pull/87528#issuecomment-1309606044
This one could be a list of https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue https://github.com/microsoft/winget-pkgs/labels/Interactive-Only-Installer

**Comment by dellclientopensource** [comment]
Added /s for silent installation in manifest and validated locally on my side. all other PR are closed, except this one.

**Comment by dellclientopensource** [comment]
DCM_Validation

**Comment by dellclientopensource** [comment]
Able to validate and install locally, this application can only be installed on Dell branded systems.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335226 
> 2023-07-25 11:11:27.871 [CLI ] ShellExecute installer failed: 1

**Comment by stephengillie** [comment]
Silent installs silently fail. Installing in interactive mode reveals the error:
image

**Comment by dellclientopensource** [comment]
Hi,
Dell Command Monitor

Requires physical system to install and run, as VM does not have a WMI-ACPI compliant BIOS.

Is it possible to enable hardware support for winget validation?

Thanks.
________________________________

**Comment by BrandonWanHuanSheng** [comment]
> Hi,
> Dell Command Monitor
> 
> Requires physical system to install and run, as VM does not have a WMI-ACPI compliant BIOS.
> 
> Is it possible to enable hardware support for winget validation?
> 
> Thanks.
> ________________________________
> 

Blocking issue with winget-cli#1417

**Comment by denelon** [comment]
Supporting custom hardware in validation is "Not Planned".
* https://github.com/microsoft/winget-pkgs/issues/199504

**Pull request closed without merging**
