### PR TITLE
New version: WestWind.MarkdownMonster version 2.8.8.0

### PR DESCRIPTION
**Pull request by kkbruce**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/98603)

### CODE REVIEW

**Comment by kkbruce** [comment]
https://www.virustotal.com/gui/file/91b989a8ae1a8e72bfca954079cccc56d19c26a3bcfae293ca10fab108b3875e

I go to virustotal and scan it, no issue.

**Comment by stephengillie** [comment]
Hi @kkbruce,

Unfortunately, packages must pass a Defender scan to be included in the WinGet public manifests.

**Comment by kkbruce** [comment]
Hi @stephengillie 
I have feedback to https://feedback.smartscreen.microsoft.com/feedback.aspx. 
How do you retrigger it? Re-commit?

**Comment by stephengillie** [comment]
> Hi @stephengillie I have feedback to https://feedback.smartscreen.microsoft.com/feedback.aspx. How do you retrigger it? Re-commit?

Yes, another commit will trigger another pipeline run. But Defender feedback may take time to be processed. How much time, I do not know.

**Comment by kkbruce** [comment]
Feedback Hub: https://aka.ms/AAjvmlo
[Microsoft Security Intelligence]: https://www.microsoft.com/en-us/wdsi/submission/4f3c26f7-3db2-4b85-933c-00a872c21bda

I have tried to do everything I can.

**Comment by kkbruce** [comment]
"Url validation error" mean is github.com a bad security site?

Install the file I believe it is safe.
image

I have no idea.

**Comment by kkbruce** [comment]
I have no idea.
Wait for Defender feedback to be processed.

**Pull request closed without merging**
