### PR TITLE
New version: Insecure.Nmap version 7.94

### LINKED ISSUE #130062: [Update Request]: Insecure.Nmap to version 7.94
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Insecure.Nmap

### Package Version

7.94

### Please describe the changes you would like to see

Download Page Url: https://nmap.org/dist/nmap-7.94-setup.exe

### PR DESCRIPTION
**Pull request by Exorcism0666**
### Pull request has been created with [Komac](https://github.com/russellbanks/Komac) v1.11.0 :rocket:

- Resolve: #130062

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132762)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification.
>[!important]
>Please recheck these Pull Request carefully before merging. If it is a incorrect-removing Pull Request and the URLs don't have any issue while manual checking, please close this Pull Request directly(It's best to let Exorcism0666 know).

良い一日をお過ごしください！

**Comment by Exorcism0666** [comment]
image

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978334972

(Automated response - build 530.)

**Comment by stephengillie** [comment]
Hi @Exorcism,

Manual Validation ended with:
image

Is there an installer switch to bypass this and complete the install automatically?

**Comment by Exorcism0666** [comment]
image 💀

**Comment by stephengillie** [comment]
URL: 
Status Code: 200

(Automated message - build 543)

**Comment by stephengillie** [comment]
This might be a user-agent block of the WinGet package manager specifically.

**Pull request closed without merging**
