### PR TITLE
Moving: Tencent.TXEDULite version 2.2.1.38

### PR DESCRIPTION
**Pull request by SpecterShell**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/28769)

### CODE REVIEW

**Comment by BajajAditya123** [comment]
OMG So fast
for me it tooks 45 mins or 1 hour

**Review by ItzLevvie — APPROVED** [review]

**Comment by BajajAditya123** [comment]
wait

**Comment by BajajAditya123** [comment]
@ItzLevvie uhmmm.... what is this 
image

**Comment by ItzLevvie** [comment]
> OMG So fast
> for me it tooks 45 mins or 1 hour

This package is being moved somewhere else, so the Installer Validation in the pipelines are skipped.

**Comment by BajajAditya123** [comment]
oh ok

**Comment by SpecterShell** [comment]
> @ItzLevvie uhmmm.... what is this
> image

The validation process allows modifying only one manifest per pr, and moving the files from one folder to the another directly will be regarded as modifying two different manifests, one for deleting and one for creating. The only way to cope with it is to split the operation into two prs, moving and [moved](https://github.com/microsoft/winget-pkgs/pull/28770).

**Pull request merged**
