### PR TITLE
New version: Coder.Coder version 2.3.3

### PR DESCRIPTION
**Pull request by cdrci**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/124310)

### CODE REVIEW

**Comment by cdrci** [comment]
🤖 cc: @deansheather @matifali

**Review by stephengillie — APPROVED** [review]

**Comment by matifali** [comment]
Hi, @stephengillie any plans for automatic approvals?

**Comment by mdanish-kh** [comment]
@matifali There are a couple issues where it's been discussed

- https://github.com/microsoft/winget-pkgs/issues/89190
- https://github.com/microsoft/winget-pkgs/issues/100
- https://github.com/microsoft/winget-pkgs/issues/118508

Looking at https://github.com/microsoft/winget-pkgs/issues/89190#issuecomment-1322259811, I believe the team is trying to finalize business process for https://github.com/microsoft/winget-pkgs/issues/100 first and then they'll look at if they want to have a system for "automated" approvals

**Comment by stephengillie** [comment]
Apologies for the delay - we had identified an issue in the current approval process, and I was implementing a quick fix.

**Pull request merged**
