### PR TITLE
Remove old version of JanDeDobbeleer.OhMyPosh

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
null

### CODE REVIEW

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
Something weird happened here

**Comment by vedantmgoyal2009** [comment]
Hmm. The web response failed and thus, the old values in the variables didn't get overwritten with new values.

https://github.com/vedantmgoyal2009/winget-pkgs-automation/runs/4154688695?check_suite_focus=true#step:4:556

I think clearing variables after every iteration would fix this issue.

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
Are you going to fix this one?

**Comment by vedantmgoyal2009** [comment]
Marked as draft.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
