### PR TITLE
Remove: SFTPGo versions with security related issues

### PR DESCRIPTION
**Pull request by drakkan**
https://github.com/drakkan/sftpgo/security/advisories?state=published

Signed-off-by: Nicola Murino <nicola.murino@gmail.com>

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/80086)

### CODE REVIEW

**Comment by drakkan** [comment]
Hi, I'm not sure what's wrong here. I just want to remove the old versions (with security related issues)

**Review by ItzLevvie — DISMISSED** [review]

**Review by Trenly — CHANGES_REQUESTED** [review]
Only one version can be modified per PR. You will need to submit separate PR's for removing each version

**Comment by drakkan** [comment]
pushed a separate commit for each version to be removed. I hope is ok this way

**Review by ItzLevvie — APPROVED** [review]

**Comment by drakkan** [comment]
Hi, is there anything else needed on my side? Thank you

**Comment by ItzLevvie** [comment]
Oops. It requires the pull request to be split up into 8 different PRs.

Validation Pipelines can only handle **_one_** package removal per pull request.

**Comment by drakkan** [comment]
> It requires the pull request to be split up into 8 different PRs.
> 
> Validation Pipelines can only handle **_one_** package removal per pull request.

ok, thanks

**Pull request closed without merging**
