### PR TITLE
Elixir.elixir 1.15.7 f1 b06 d8 a97 bc32

### LINKED ISSUE #131582: [Package Request]: Elixir.Elixir
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://elixir-lang.org/install.html#windows
Publisher: [Elixir](https://elixir-lang.org/)
Package Name: Elixir.Elixir
Description: Elixir is a dynamic, functional language for building scalable and maintainable applications.
Package Version: 1.15.7
Installer URL: https://github.com/elixir-lang/elixir/releases/download/v1.15.7/elixir-otp-26.exe

### PR DESCRIPTION
**Pull request by licon4812**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

resolves #131582
---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131596)

### CODE REVIEW

**Review by chen-qingyu — COMMENTED** [review]
Should `MinimumVersion: 26..1.6` be `MinimumVersion: 26.1.6` in [manifests/e/Elixir/Elixir/1.15.7/Elixir.Elixir.installer.yaml](https://github.com/microsoft/winget-pkgs/pull/131596/files#diff-36259b776ccff9d3b91b6ec0f2e18b4d0d968eb499a1811bd34e8e2d593b79c6)?

**Comment by stephengillie** [comment]
Hi @licon4812,

This application appears to be a set of scripts. Is this the case?
image

Unfortunately, we're not currently accepting non-compiled applications.

**Comment by licon4812** [comment]
As far as I know it is just an exe

**Comment by stephengillie** [comment]
Unfortunately, I couldn't find an EXE for this version, and neither could our bots.

**Pull request closed without merging**
