### PR TITLE
update yaml create script

### PR DESCRIPTION
**Pull request by mizutoki79**
- Refactor indent and space
- Correct the cologne leak
- Change the destination of the WriteAllLines' first argument to an absolute path
- Run from any directory to be stored in /manifests/<publisher>/<appname>

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2378)

### CODE REVIEW

**Comment by denelon** [comment]
@mizutoki79 it looks like we just made changes to this file due to another issue. Would you mind resolving conflicts?

**Comment by mizutoki79** [comment]
OK..
I'll resolve tonight (JST) or by day after tomorrow.

**Comment by mizutoki79** [comment]
@denelon I resolved. Please check.

**Comment by denelon** [comment]
@mizutoki79 Sorry, I didn't see the mention.

**Review by denelon — APPROVED** [review]

**Pull request merged**
