### PR TITLE
New package: BeagleSoftware.BeagleEditor version 2024.4

### PR DESCRIPTION
**Pull request by ManiArasteh**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---
- Resolves: #174329
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/174327)

### CODE REVIEW

**Comment by ManiArasteh** [comment]
Please! Help me :(

**Comment by vikingnope** [comment]
It is running fine: https://dev.azure.com/shine-oss/winget-pkgs/_build/results?buildId=2275&view=logs&s=a97a88f2-e22e-5096-4fca-25e04f0f0aae&j=68997d86-8ece-5ae8-3ac5-ccdbfa458731

Just add: `Resolves: https://github.com/microsoft/winget-pkgs/issues/174329` to the description on this PR so that it closes the issue

**Comment by ManiArasteh** [comment]
Aha! Okay thanks!

**Comment by ManiArasteh** [comment]
Now, I don't know where to add description. Please give me complete answer because this is the first time I'm publishing a program for winget.

**Comment by vikingnope** [comment]
Yep that is correct, great :)

**Comment by ManiArasteh** [comment]
The multi file manifest is incomplete.A multi file manifest must contain at least version, installer and defaultLocale

**Comment by vikingnope** [comment]
Your `BeagleSoftware.BeagleEditor.yaml`, should be this code instead:

```yaml
# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: BeagleSoftware.BeagleEditor
PackageVersion: "2024.4"
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2024-08-11
Installers:
- InstallerUrl: https://github.com/beaglesoftware/beagleeditor/releases/download/v2024.4/BeagleEditor-2024.4-Installer.exe
  Architecture: x64
  InstallerSha256: 707F376D2B6AB1E16F43B825C3D44E0DA5B8083CF0C4FEDFC754682A9E2E11ED
ManifestType: installer
ManifestVersion: 1.6.0
```

**Comment by vikingnope** [comment]
> The multi file manifest is incomplete.A multi file manifest must contain at least version, installer and defaultLocale Error when running `winget validate --manifest .\manifests\b\BeagleSoftware\BeagleEditor\2024.4\BeagleSoftware.BeagleEditor.yaml`

Also when running this command it should be the full path of it so it should look something like example:

`winget validate --manifest C:\Documents\winget-pkgs\manifests\b\BeagleSoftware\BeagleEditor\2024.4\BeagleSoftware.BeagleEditor.yaml`

**Comment by ManiArasteh** [comment]
What command should I run for submitting a new PR with 'submit' subcommand in `wingetcreate`?

**Comment by vikingnope** [comment]
> What command should I run for submitting a new PR with 'submit' subcommand in `wingetcreate`?

Do not submit a new command, just go to Files changed at the top:

image


Click the three dots on the installer.yaml file and click edit file, then just paste my code:

image

**Comment by ManiArasteh** [comment]
Ok, But I want command anyway.

**Comment by vikingnope** [comment]
> Ok, But I want command anyway for other purposes.

I do not believe there is a way to edit a manifest using wingetcreate without submitting a new PR

**Comment by ManiArasteh** [comment]
Nope. We have a `submit` sub.... Wait a minute... Ok, I don't want it.

**Comment by ManiArasteh** [comment]
I got this again:
Manifest validation failed.
Manifest Error: The multi file manifest is incomplete.A multi file manifest must contain at least version, installer and defaultLocale manifest. File: BeagleSoftware.BeagleEditor.yaml

**Comment by vikingnope** [comment]
Erm... you edited the wrong file, you had to edit the installer.yaml file, which is the first not the last

**Comment by vikingnope** [comment]
So the `BeagleSoftware.BeagleEditor.yaml` should be:

```yaml
# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json
PackageIdentifier: BeagleSoftware.BeagleEditor
PackageVersion: "2024.4"
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
```

The `BeagleSoftware.BeagleEditor.installer.yaml` should be:

```yaml
# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: BeagleSoftware.BeagleEditor
PackageVersion: "2024.4"
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2024-08-11
Installers:
- InstallerUrl: https://github.com/beaglesoftware/beagleeditor/releases/download/v2024.4/BeagleEditor-2024.4-Installer.exe
  Architecture: x64
  InstallerSha256: 707F376D2B6AB1E16F43B825C3D44E0DA5B8083CF0C4FEDFC754682A9E2E11ED
ManifestType: installer
ManifestVersion: 1.6.0
```

**Comment by ManiArasteh** [comment]
Again! It is really... annoying

**Comment by vikingnope** [comment]
> I got this again: Manifest validation failed. Manifest Error: The multi file manifest is incomplete.A multi file manifest must contain at least version, installer and defaultLocale manifest. File: BeagleSoftware.BeagleEditor.yaml

See this: https://github.com/microsoft/winget-pkgs/pull/174327#issuecomment-2361334552

**Comment by ManiArasteh** [comment]
It gived error and requires me to sign in otherwise I can't do anything.

**Pull request closed without merging**
