### PR TITLE
Add GeForce Experience v3.21.0.36

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----
Does not work on VM
#2347
#4396

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/10113)

### CODE REVIEW

**Comment by jedieaston** [comment]
@KevinLaMS GeForce Experience will not install unless it detects an Nvidia GPU on the system, is this testable or..?

#4396 for another example.

**Comment by jedieaston** [comment]
@msftbot, can't you see we're in the middle of something here? :D

**Comment by denelon** [comment]
@KevinLaMS I think we need a killer gaming rig to test this on!

**Comment by OfficialEsco** [comment]
So, any news on this one? I see 3.22.0.32 is released but there is no reason making a new manifest if its going to get stuck

**Comment by denelon** [comment]
We've been discussing how we're going to deal with this class of scenarios. I don't think we anticipated needing custom hardware to validate packages.

**Comment by OfficialEsco** [comment]
But.. :c it worked in #18853 and in Sandbox

```
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget install -m .\manifests\n\Nvidia\GeForceExperience\3.21.0.36\
Found Nvidia GeForce Experience [Nvidia.GeForceExperience]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://us.download.nvidia.com/GFE/GFEClient/3.21.0.36/GeForce_Experience_v3.21.0.36.exe
  ██████████████████████████████   121 MB /  121 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

**Comment by jedieaston** [comment]
Can you post a screenshot of the display tab in your sandbox’s dxdiag? It’s possible you have graphics acceleration enabled and that’s passing through your host’s card info.

**Comment by OfficialEsco** [comment]
> Can you post a screenshot of the display tab in your sandbox’s dxdiag? It’s possible you have graphics acceleration enabled and that’s passing through your host’s card info.

image

I do not have a Nvidia Graphic Card in this Laptop tho...

GeforceExperience is also not installed because of that, so it should throw the 3858759680 exit code
image

**Comment by jedieaston** [comment]
Does the installer return a 0 exit code if you run it outside of WinGet? I wonder if WinGet is reading the exit code incorrectly for some reason.

**Comment by OfficialEsco** [comment]
@ItzLevvie its go time 😲
The x86 Machine most be messed up, so many x86 manifests fail on it.

**Review by ItzLevvie — APPROVED** [review]

**Comment by denelon** [comment]
@OfficialEsco we've seen a fairly common pattern with installers reporting one architecture and the application having a different architecture. We're digging into options for fallback and validation so we can have the right messaging for users submitting manifests. It would be frustrating to be told "change the architecture and try again" only to fail.

**Pull request merged**
