### PR TITLE
Moved & Modify: Tencent.VooVMeeting version 1.2.10.510

### PR DESCRIPTION
**Pull request by SpecterShell**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/45175)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by ryfu-msft** [comment]
@SpecterShell, when I try installing this app and running it, I am immediately shown an error message that the version is out of date and it forces me to update to a later version. I don't see a reason to add an older version of this package if it's going to force me to update to the latest version 3.0.1.510 in order to use it. 

image

**Comment by SpecterShell** [comment]
This is a part of the "[Moving](https://github.com/microsoft/winget-pkgs/pull/39362) - Moved" process, so I didn't verify this version of software. 😕
If it is not good to publish an outdated version, I will close this pr.

**Comment by denelon** [comment]
@SpecterShell since it wants to upgrade as soon as it's installed, I wouldn't worry about moving it.

**Pull request closed without merging**
