### PR TITLE
New version: Oven-sh.Bun version 1.1.4

### PR DESCRIPTION
**Pull request by coolplaylinbot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/149497)

### CODE REVIEW

**Review by mdanish-kh — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @coolplaylinbot,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-04-16 14:35:14.098 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFF45F7C11F: (caller: 00007FFF45D08D6F) LogHr(1) tid(d64) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFF45E82B08: (caller: 00007FFF45F2BC20) Exception(1) tid(d64) 8A15005E ] 
> 2024-04-16 14:35:14.098 [REPO] Failed to open available source: msstore
> 2024-04-16 14:35:22.701 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFF2910C11F: (caller: 00007FFF28E98D6F) LogHr(1) tid(15c8) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFF29012B08: (caller: 00007FFF290BBC20) Exception(1) tid(15c8) 8A15005E ] 
> 2024-04-16 14:35:22.701 [REPO] Failed to open available source: msstore
> 2024-04-16 14:35:42.836 [FAIL] Installer failed security check. Url: https://github.com/oven-sh/bun/releases/download/bun-v1.1.4/bun-windows-x64.zip Result: 0x80004005

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Hi @coolplaylinbot,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 877.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-04-17 08:34:15.285 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFE5AF4C11F: (caller: 00007FFE5ACD8D6F) LogHr(1) tid(33c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFE5AE52B08: (caller: 00007FFE5AEFBC20) Exception(1) tid(33c) 8A15005E ] 
> 2024-04-17 08:34:15.285 [REPO] Failed to open available source: msstore
> 2024-04-17 08:34:22.889 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFE4287C11F: (caller: 00007FFE42608D6F) LogHr(1) tid(1dc4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFE42782B08: (caller: 00007FFE4282BC20) Exception(1) tid(1dc4) 8A15005E ] 
> 2024-04-17 08:34:22.889 [REPO] Failed to open available source: msstore
> 2024-04-17 08:34:43.222 [FAIL] Installer failed security check. Url: https://github.com/oven-sh/bun/releases/download/bun-v1.1.4/bun-windows-x64.zip Result: 0x80004005

(Automated response - build 877.)

**Pull request merged**
