### PR TITLE
Remove version 2022.2.20.0 of RemoteDesktopManagerFree

### PR DESCRIPTION
**Pull request by rbstp**
This PR removes version 2022.2.20.0 of Remote Desktop Manager Free by Devolutions. RDM Free has been discontinued since October 2022, it should not be used anymore since it will require a free license which cannot be generated anymore. Please see the official blog regarding this: https://blog.devolutions.net/2022/10/news-remote-desktop-manager-is-changing-for-the-better/
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/139127)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://cdn.devolutions.net/download/Setup.RemoteDesktopManagerFree.2022.2.20.0.msi 
Status Code: 200

(Automated message - build 738)

**Comment by stephengillie** [comment]
Hi @rbstp,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 740.)

**Comment by stephengillie** [comment]
URL: https://cdn.devolutions.net/download/Setup.RemoteDesktopManagerFree.2022.2.20.0.msi 
Status Code: 200

(Automated message - build 743)

**Comment by stephengillie** [comment]
URL: https://cdn.devolutions.net/download/Setup.RemoteDesktopManagerFree.2022.2.20.0.msi 
Status Code: 200

(Automated message - build 745)

**Comment by stephengillie** [comment]
> This PR removes version 2022.2.20.0 of Remote Desktop Manager Free by Devolutions. RDM Free has been discontinued since October 2022, it should not be used anymore since it will require a free license which cannot be generated anymore. Please see the official blog regarding this: https://blog.devolutions.net/2022/10/news-remote-desktop-manager-is-changing-for-the-better/

The blog post describes how the free and enterprise versions are reciving a unified installer, not that the product is being discontinued. 

> Remote Desktop Manager Free and Remote Desktop Manager Enterprise are now part of a SINGLE download instead of 2!

**Comment by stephengillie** [comment]
URL: https://cdn.devolutions.net/download/Setup.RemoteDesktopManagerFree.2022.2.20.0.msi 
Status Code: 200

(Automated message - build 745)

**Comment by rbstp** [comment]
The URL https://cdn.devolutions.net/download/Setup.RemoteDesktopManagerFree.2022.2.20.0.msi has been remove,  well as all other mentions of the RDMFree installer on our CDN.

**Comment by stephengillie** [comment]
URL: https://cdn.devolutions.net/download/Setup.RemoteDesktopManagerFree.2022.2.20.0.msi 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 762)

**Comment by rbstp** [comment]
> URL: https://cdn.devolutions.net/download/Setup.RemoteDesktopManagerFree.2022.2.20.0.msi Response status code does not indicate success: 404 (Not Found).
> 
> (Automated message - build 762)

The URL was removed, so the installer is not accessible anymore. This PR is to remove the manifest for that version.

**Comment by stephengillie** [comment]
> > URL: https://cdn.devolutions.net/download/Setup.RemoteDesktopManagerFree.2022.2.20.0.msi Response status code does not indicate success: 404 (Not Found).
> > (Automated message - build 762)
> 
> The URL was removed, so the installer is not accessible anymore. This PR is to remove the manifest for that version.

Sorry for the delay - I had opened this and others a couple of hours ago, with the intent of approving, and had my automation run on them. Then a distraction occurred, and I'm just now back to this PR.

**Comment by stephengillie** [comment]
Hi @rbstp,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 762.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
