### PR TITLE
Add ThinkingManSoftware.Dimension4 v5.31.331.0

### PR DESCRIPTION
**Pull request by VagyokC4**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1676)

### CODE REVIEW

**Comment by SoftCreatR** [comment]
Maybe use the original link?

`http://www.thinkman.com/dimension4/d4time531.msi`

**Comment by VagyokC4** [comment]
@SoftCreatR Are you able to review this and move it forward?  Feels like it's stuck.

**Comment by SoftCreatR** [comment]
> @SoftCreatR Are you able to review this and move it forward? Feels like it's stuck.

Unfortunately, i'm just a regular user like you ;) But it's assigned to @kevinlams so it's just a matter of time, until your PR will be processed.

Or maybe, @Masetty123 wants to take it over, since he/she is a little bit more active atm.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
