### PR TITLE
New version: ChilliBits.Spice version 0.18.5

### PR DESCRIPTION
**Pull request by marcauberer**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132373)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\telegram.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\telegram.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

(Automated response - build 516.)

**Comment by marcauberer** [comment]
@stephengillie seems like this has nothing to do with my application, right?

**Comment by stephengillie** [comment]
> @stephengillie seems like this has nothing to do with my application, right?

Correct - while this diagnostic tool is frequently useful, it's not always helpful.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
