### PR TITLE
New package: meshmakers.octo-cli version 0.0.2307.24002

### PR DESCRIPTION
**Pull request by mmgerald**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/113535&drop=dogfoodAlpha

### CODE REVIEW

**Comment by mmgerald** [comment]
> No commit pushedDate could be found for PR 113535 in repo microsoft/winget-pkgs

@stephengillie @Madhusudhan-MSFT Can I do something here to solve this issue?

**Comment by stephengillie** [comment]
Hi @mmgerald,

Sorry, this is supposed to be a transient issue that indicates the pipeline needs to be manually retried. 
* https://github.com/microsoft/winget-pkgs/issues/111634

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
