### PR TITLE
SublimeHQPtyLtd.SublimeText version Version 4 Build 4107

### PR DESCRIPTION
**Pull request by techflashYT**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14773)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Package already added https://github.com/microsoft/winget-pkgs/tree/master/manifests/s/SublimeHQ/SublimeText

**Comment by sanikdah** [comment]
I searched for the package but nothing came up, that's weird.
image

**Comment by OfficialEsco** [comment]
huh... maybe this is why there is so many PRs..
image

**Comment by ItzLevvie** [comment]
> I searched for the package but nothing came up, that's weird.
> image

Looks like you did a spelling error.

**Comment by sanikdah** [comment]
> huh... maybe this is why there is so many PRs..
> image
> 
> can do winget -v and post the version?

v1.0.11451 and I'm running the (i think latest) insider build of windows

**Comment by sanikdah** [comment]
> > huh... maybe this is why there is so many PRs..
> > image
> > can do winget -v and post the version?
> 
> v1.0.11451 and I'm running the (i think latest) insider build of windows



> > I searched for the package but nothing came up, that's weird.
> > image
> 
> Looks like you did a spelling error.

ahhh no wonder i couldn't find it, oh well

**Comment by denelon** [comment]
@sanikdah Would you care to add your 👍 ?

https://github.com/microsoft/winget-pkgs/issues/15513

**Comment by sanikdah** [comment]
Alright, I added one :)

**Pull request closed without merging**
