### PR TITLE
New version: ente-io.auth-desktop version 4.1.5

### PR DESCRIPTION
**Pull request by drshtmstry**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/196896)

### CODE REVIEW

**Comment by jo-chemla** [comment]
Duplicate of https://github.com/microsoft/winget-pkgs/pull/196887 opened the same day
Requires in installer yaml to follow spec ManifestVersion: 1.9.0 with `ArchiveBinariesDependOnPath: true`
See https://github.com/microsoft/winget-pkgs/issues/147677#issuecomment-2515715538

**Comment by drshtmstry** [comment]
> ArchiveBinariesDependOnPath: true

`ArchiveBinariesDependOnPath: true` is only required for zip archive packages (portable). This manifest contains an exe installer which passed validation and there is not "blocking-issue" policy for this package.

**Comment by jo-chemla** [comment]
Indeed true, not sure why this comment was made by @Trenly then

**Comment by jo-chemla** [comment]
Note to track ente-auth auto push to winget-pkgs via winget-releaser, [here](https://github.com/ente-io/ente/discussions/3950) is the discussion

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
I can't find the other PR, but apparently this manifest already exists.

**Comment by stephengillie** [comment]
Close with reason: Merge Conflicts;

**Pull request closed without merging**
