### PR TITLE
Update version: Git.Git version 2.46.0

### PR DESCRIPTION
**Pull request by russellbanks**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/170665)

### CODE REVIEW

**Comment by russellbanks** [comment]
https://github.com/microsoft/winget-pkgs/pull/165183#issuecomment-2266143950

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Pull request merged**
