### PR TITLE
SEEYOU.SEEYOU version 2.0.2

### PR DESCRIPTION
**Pull request by khaffner**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101232)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
No silent switches, The installer type supposed nullsoft. I am going to check if there is any dependent services.

**Comment by khaffner** [comment]
/allusers /S

Might work

**Comment by BrandonWanHuanSheng** [comment]
I seeing a lot of cmd pop up while during uninstall.

**Comment by stephengillie** [comment]
Hi @khaffner,

The installation isn't unattended:
image

Is there an installer switch to bypass this and have it install without rebooting?

**Comment by BrandonWanHuanSheng** [comment]
I also noticed that one but norestart did not work. Normally the is used when using updating cab and msu when trying to skip this dialog.  Norestart usually suppresses automatic reboots and reboot prompts.

**Comment by BrandonWanHuanSheng** [comment]
I guess it might be NR. Still No Work.

**Comment by BrandonWanHuanSheng** [comment]
I found the help usage https://nsis.sourceforge.io/Docs/Chapter3.html

**Comment by BrandonWanHuanSheng** [comment]
@khaffner, I found the help file. https://nsis.sourceforge.io/Docs/Chapter3.html

**Comment by BrandonWanHuanSheng** [comment]
@stephengillie It look like the installer is not unattended. But I actually tried every command, the reboot dialog keep popping up.

**Comment by stephengillie** [comment]
> @stephengillie It look like the installer is not unattended. But I actually tried every command, the reboot dialog keep popping up. There is no ways to resolve.

Pending:
* https://github.com/microsoft/winget-cli/issues/910

**Comment by BrandonWanHuanSheng** [comment]
closed #101232 

Result: Failure to interactive install because this installer does not accept NoRestart and NoReboot Command.

**Pull request closed without merging**
