### PR TITLE
PaulWoolcock.SyncOutlookandGooglecalendars version 2.9.0-beta

### PR DESCRIPTION
**Pull request by SM-26**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/40602)

### CODE REVIEW

**Comment by SM-26** [comment]
For any human reading this:
this app has 2 branches
beta and alpha.

I have made a manifest for both, what would be the right way to use them both?

**Review by ItzLevvie — APPROVED** [review]

**Comment by SM-26** [comment]
Hey @ItzLevvie 
Thanks for validating this PR.

one questing thought:
this app has 2 branches
beta and alpha.

I have made a manifest for both, what would be the right way to use them both?

**Comment by ItzLevvie** [comment]
> beta and alpha.

You will have to modify this to be `PaulWoolcock.SyncOutlookAndGoogleCalendar.Beta` and `PaulWoolcock.SyncOutlookAndGoogleCalendar.Alpha`

**Comment by SM-26** [comment]
I'm sorry it took me 5 commits (and I can't figure out how to squash them)
But I've done as you instructed.
please tell me if it looks ok
image

**Pull request merged**
