### PR TITLE
Diskuv.OCaml 2.1.0

### PR DESCRIPTION
**Pull request by jonahbeckford**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/129085)

### CODE REVIEW

**Comment by jonahbeckford** [comment]
There was some comment on this issue that I think has now been deleted:

> Hello @jonahbeckford,
One or more of the installer URLs doesn't appear valid.
This may happen for sites with policies prohibiting distribution or use by third parties.
This may happen for URLs pointing to domains that do not align with the publisher domain or package domain. If you could provide supporting evidence from the publisher that the URLs for the installer are correct, that would help us to validate and approve this PR.
Template: msftbot/validationError/urls/domain

If the use of the https://gitlab.com/dkml subdomain is blocking this issue, be aware that I have been changing the language "Diskuv OCaml" to "DkML" to better help my users, and I switched from github to gitlab to become part of the GitLab Open Source Program (OSP). Two examples of the "DkML" rebranding:
1. The current https://ocaml.org/install page is an example of the equivalence, although in the upcoming weeks I will be dropping all language "Diskuv OCaml" from those pages.
2. The documentation site: https://diskuv.com/dkmlbook/

Sadly, GitLab does not publicly list all OSP participants, but I'm sure they would respond if you needed a private off-thread check. They should be able to confirm that https://gitlab.com/dkml is part of OSP and https://gitlab.com/diskuv is owned by the same account. That separation is required for compliance with OSP.

**Comment by stephengillie** [comment]
Hi @jonahbeckford,

The concern is only because Gitlab could be used for either official hosting, or for 3rd party rehosting of popular projects. Our robot couldn't tell which this was, and needed a human to verify.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Not to be onerous, but 46/77 (0.59%) of the installer.yaml lines are comments.

**Pull request merged**
