### PR TITLE
[Zip][Portable] New Package: cURL.cURL 7.85.0

### LINKED ISSUE #726: Package Request: cURL
# Description of the new feature/enhancement

cURL is a commonly used command line based download tool. By allowing `winget install curl` can make ease for its installation on Windows.

# Proposed technical implementation details (optional)

As cURL does not provide official installers for Windows, currently the only way to install it is download its [binary builds for windows](https://curl.haxx.se/windows/), extract, then manually copy `curl.exe` to `C:\Users\xxx` for it to be effective, or add a path via environment variable.

I wonder if there's a way to allow `winget install curl` to come true, and have everything done via one simple command?

### PR DESCRIPTION
**Pull request by Trenly**
* Resolves #726

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/88071)

### CODE REVIEW

**Comment by Trenly** [comment]
@msftbot zip

**Review by ItzLevvie — DISMISSED** [review]

**Comment by stephengillie** [comment]
> 2023-01-30 15:51:12.030 [CLI ] Unable to locate nested installer at: C:\Users\user\AppData\Local\Temp\WinGet\cURL.cURL.7.85.0\extracted\.\curl-7.85.0_9-win64-mingw.zip\curl-7.85.0_9-win64-mingw\bin\curl.exe

This is because the installer is located at: `C:\Users\user\AppData\Local\Temp\WinGet\cURL.cURL.7.85.0\extracted\curl-7.85.0_9-win64-mingw\bin\curl.exe`

The `.\curl-7.85.0_9-win64-mingw.zip\` in the middle is causing the issue.

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
