### PR TITLE
stakira.OpenUTAU version 0.0.808

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/67850)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
We can wait for `InstallerType: zip` which will be coming to WinGet in the future: https://github.com/stakira/OpenUtau/releases/download/OpenUtau-Latest/OpenUtau-win-x64.zip

**Comment by oxygen-dioxide** [comment]
> We can wait for `InstallerType: zip` which will be coming to WinGet in the future: https://github.com/stakira/OpenUtau/releases/download/OpenUtau-Latest/OpenUtau-win-x64.zip

However, the official .zip release are directly replaced when update, and the hash will change.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
We're not allowed to accept repackages of another application so it will be best for it to come from the official publisher.

**Comment by ItzLevvie** [comment]
Close with reason: See previous comment;

**Pull request closed without merging**
