### PR TITLE
Remove wrong version Microsoft.Office 16.0.17531.20046

### PR DESCRIPTION
**Pull request by treysis**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150777)

### CODE REVIEW

**Comment by treysis** [comment]
@stephengillie how to get rid of this "Validation-Dependency-Removal" warning/label? How can the other package put a block on this package? Simply because downgrading is not supposed to happen in winget repo?

**Comment by treysis** [comment]
@stephengillie This PR removes this version folder incl. the manifests because this is not the version of Office, but just the version of the installer file (i.e. deployment tool).

**Comment by 2505lis** [comment]
Одобряю

**Comment by treysis** [comment]
@stephengillie This version of Office (`16.0.17531.20046`) doesn't exist and needs to be removed entirely. The whole manifest is wrong. The newest version of Office is `16.0.17425.20176`. Check the official release history: https://learn.microsoft.com/en-us/officeupdates/update-history-microsoft365-apps-by-date

**Comment by stephengillie** [comment]
URL: https://officecdn.microsoft.com/pr/wsus/setup.exe 
Status Code: 200

(Automated message - build 877)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
