### PR TITLE
Add iMazing

### PR DESCRIPTION
**Pull request by ath0mas**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/999)

### CODE REVIEW

**Comment by ath0mas** [comment]
@samiranshah _please_ any log or detail on this uninstall error, or what is expected and found incorrect?

**Comment by ath0mas** [comment]
or @DigiDNA @macmade for more editor feedback on iMazing itself ; any idea on this uninstall report?

**Comment by codebar33** [comment]
Hi @ath0mas! I can't find your uninstall report. But to uninstall iMazing you can execute:
`"C:\Program Files\DigiDNA\iMazing\unins000.exe" /verysilent /closeapplications /suppressmsgboxes`

**Comment by ath0mas** [comment]
Thx @codebar33 and as I only suggested the iMazing package for **winget**, I don't know what is the exact "problem" about uninstall reported by the bot or @samiranshah
Waiting for more logs or details ;)

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
