### PR TITLE
Kiwix.WikiMed.Electron v2.2.90-E

### PR DESCRIPTION
**Pull request by Jaifroid**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/93262)

### CODE REVIEW

**Comment by Jaifroid** [comment]
This updates v2.2.9-E to v2.2.90-E because 2.2.9 was not being picked up as the latest version.

**Comment by Jaifroid** [comment]
This is indeed a duplicate package. Unfortunately, my numbering scheme works like this: v2.2.0-E -> v2.2.6-E -> v2.2.62-E -> v2.2.9-E, but winget things 2.2.62 is the latest package. Therefore I have updated the numbering to v2.2.90-E, but the package is the same. Generating a new 1.6GB package just for this minor numbering change would be very wasteful (of time, of energy, of resources).

**Comment by Trenly** [comment]
> This is indeed a duplicate package. Unfortunately, my numbering scheme works like this: v2.2.0-E -> v2.2.6-E -> v2.2.62-E -> v2.2.9-E, but winget thinks 2.2.62 is the latest package (see [microsoft/winget-cli#2829](https://github.com/microsoft/winget-cli/issues/2829)). Therefore I have updated the numbering to v2.2.90-E, but the package is the same. Generating a new 1.6GB package just for this minor numbering change would be very wasteful (of time, of energy, of resources).

You should be able to use AppsAndFeatures entries to work around this, but you will need to add it for all versions for the mapping to work properly. You will need to add this section in each `*.installer.yaml` manifest
```yaml
AppsAndFeaturesEntries: 
- DisplayVersion: <displayversion>
```
Then just use these package versions and display versions (from your example)

<table>
<tr>
	<td>Package Version
	<td>Display Version
<tr>
	<td> 2.2.0.0
	<td> v2.2.0-E
<tr>
	<td> 2.2.6.0
	<td>v2.2.6-E
<tr>
	<td> 2.2.6.2
	<td> v2.2.62-E
<tr>
	<td> 2.2.9.0
	<td>v2.2.9-E
</table>

**Comment by Jaifroid** [comment]
@Trenly I think that now I'm aware of this issue, i.e. that winget uses strict numerical numbering and not alphabetic sorting, or the latest manifest, to determine latest, it might just be easier if I deleted the v2.2.9-E manifest, and leave only v2.2.90-E, so as not to complicate things. Do I just submit a separate PR removing a manifest version?

**Comment by Trenly** [comment]
> @Trenly I think that now I'm aware of this issue, i.e. that winget uses strict numerical numbering and not alphabetic sorting, or the latest manifest, to determine latest, it might just be easier if I deleted the v2.2.9-E manifest, and leave only v2.2.90-E, so as not to complicate things. Do I just submit a separate PR removing a manifest version?

That would work

**Comment by Jaifroid** [comment]
@Trenly I've made a PR to remove the prior duplicate: https://github.com/microsoft/winget-pkgs/pull/93347.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
