### PR TITLE
New version: zufuliu.notepad2 version 4.23.08r4962

### PR DESCRIPTION
**Pull request by MerrickZ**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/118668)

### CODE REVIEW

**Comment by MerrickZ** [comment]
I couldn't find out why the installer validation process failed, any detail ?

**Comment by MerrickZ** [comment]
It seems that Microsoft Defender detected some trojan in win32 build. 
image

**Comment by stephengillie** [comment]
> It seems that Microsoft Defender detected some trojan in win32 build. image

Automatic Validation ended with essentially the same:
> Installation failed with exit code -1978335187 
2023-09-01 00:41:09.780 [FAIL] Installer failed security check. Url: https://github.com/zufuliu/notepad2/releases/download/v4.23.08r4962/Notepad2_i18n_Win32_v4.23.08r4962.zip Result: 0x80004005 
image

This might be a false positive. We can rescan tomorrow.

**Pull request closed without merging**
