### PR TITLE
GiulioSorrentino.CBriscola.WPF version 0.6.6

### PR DESCRIPTION
**Pull request by GiulianoSpaghetti**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140327)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 796.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-21 06:46:11.310 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-21 06:46:57.273 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-21 06:47:08.166 [FAIL] Installer failed security check. Url: https://github.com/numerunix/CBriscola.WPF/releases/download/0.6.6/CBriscola.WPF-0.6.6-x64.msi Result: 0x80004005 2024-02-21 06:47:08.166 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (54:BC) [06:46:23:591]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (54:BC) [06:46:25:326]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg MSI (s) (54:BC) [06:46:33:701]: Windows Installer installed the product. Product Name: Microsoft .NET Runtime - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (54:68) [06:46:41:216]: Windows Installer installed the product. Product Name: Microsoft .NET Host FX Resolver - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (54:40) [06:46:42:372]: Windows Installer installed the product. Product Name: Microsoft .NET Host - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (54:D8) [06:46:47:904]: Windows Installer installed the product. Product Name: Microsoft Windows Desktop Runtime - 8.0.2 (x64). Product Version: 64.8.8806. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 796.)

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 797.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-21 06:46:11.310 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-21 06:46:57.273 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-21 06:47:08.166 [FAIL] Installer failed security check. Url: https://github.com/numerunix/CBriscola.WPF/releases/download/0.6.6/CBriscola.WPF-0.6.6-x64.msi Result: 0x80004005 2024-02-21 06:47:08.166 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (54:BC) [06:46:23:591]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (54:BC) [06:46:25:326]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg MSI (s) (54:BC) [06:46:33:701]: Windows Installer installed the product. Product Name: Microsoft .NET Runtime - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (54:68) [06:46:41:216]: Windows Installer installed the product. Product Name: Microsoft .NET Host FX Resolver - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (54:40) [06:46:42:372]: Windows Installer installed the product. Product Name: Microsoft .NET Host - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (54:D8) [06:46:47:904]: Windows Installer installed the product. Product Name: Microsoft Windows Desktop Runtime - 8.0.2 (x64). Product Version: 64.8.8806. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 797.)

**Comment by numerunix** [comment]
It's blocked by defender

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 800.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-21 06:46:11.310 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-21 06:46:57.273 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-21 06:47:08.166 [FAIL] Installer failed security check. Url: https://github.com/numerunix/CBriscola.WPF/releases/download/0.6.6/CBriscola.WPF-0.6.6-x64.msi Result: 0x80004005 2024-02-21 06:47:08.166 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (54:BC) [06:46:23:591]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (54:BC) [06:46:25:326]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg MSI (s) (54:BC) [06:46:33:701]: Windows Installer installed the product. Product Name: Microsoft .NET Runtime - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (54:68) [06:46:41:216]: Windows Installer installed the product. Product Name: Microsoft .NET Host FX Resolver - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (54:40) [06:46:42:372]: Windows Installer installed the product. Product Name: Microsoft .NET Host - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (54:D8) [06:46:47:904]: Windows Installer installed the product. Product Name: Microsoft Windows Desktop Runtime - 8.0.2 (x64). Product Version: 64.8.8806. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 800.)

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 812.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-22 19:29:06.955 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-22 19:29:39.904 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-22 19:29:49.273 [FAIL] Installer failed security check. Url: https://github.com/numerunix/CBriscola.WPF/releases/download/0.6.6/CBriscola.WPF-0.6.6-x64.msi Result: 0x80004005 2024-02-22 19:29:49.273 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (44:70) [19:29:18:160]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (44:70) [19:29:19:972]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg MSI (s) (44:70) [19:29:20:285]: Windows Installer installed the product. Product Name: Microsoft .NET Runtime - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (44:20) [19:29:21:097]: Windows Installer installed the product. Product Name: Microsoft .NET Host FX Resolver - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (44:C4) [19:29:21:972]: Windows Installer installed the product. Product Name: Microsoft .NET Host - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (44:44) [19:29:27:175]: Windows Installer installed the product. Product Name: Microsoft Windows Desktop Runtime - 8.0.2 (x64). Product Version: 64.8.8806. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 812.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-23 11:37:37.240 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-23 11:38:13.582 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-23 11:38:23.136 [FAIL] Installer failed security check. Url: https://github.com/numerunix/CBriscola.WPF/releases/download/0.6.6/CBriscola.WPF-0.6.6-x64.msi Result: 0x80004005 2024-02-23 11:38:23.136 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (9C:EC) [11:37:49:270]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (9C:EC) [11:37:50:692]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg MSI (s) (9C:EC) [11:37:54:973]: Windows Installer installed the product. Product Name: Microsoft .NET Runtime - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (9C:A4) [11:37:59:817]: Windows Installer installed the product. Product Name: Microsoft .NET Host FX Resolver - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (9C:24) [11:38:00:598]: Windows Installer installed the product. Product Name: Microsoft .NET Host - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (9C:0C) [11:38:05:645]: Windows Installer installed the product. Product Name: Microsoft Windows Desktop Runtime - 8.0.2 (x64). Product Version: 64.8.8806. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 813.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
