### PR TITLE
New package: Zoom.ZoomClientforMeetings version 5.16.26186

### PR DESCRIPTION
**Pull request by CalenCyr**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/130808)

### CODE REVIEW

**Comment by stephengillie** [comment]
> Possible duplicate package entry.
> 
> Similar installer SHA256 hash found in manifest:
> 
> * `InstallerSha256: 8fc7e4f3668bfd3862664963e28430f63d1a8147b67e281daf4f181f1acae1c2`
>   
>   * manifests\z\Zoom\Zoom\5.16.10.26186

Hi @CalenCyr,

The `InstallerUrl` has the previous version in the path.

**Comment by CalenCyr** [comment]
Instead of an update, it's an alternate installer, so it's an .msi instead that installs for all users versus the original Zoom.Zoom that is an .exe file that installs only for one user. Would that not be allowed as its own entry?

**Comment by stephengillie** [comment]
Oh - please include the existing data in the update. This would remove the User-only EXE.

**Comment by CalenCyr** [comment]
Okay, so do I need to close this pull request and open a separate one with an updated Zoom manifest for the all users MSI file? It's fine to have the user-only EXE removed?

**Comment by Trenly** [comment]
> Okay, so do I need to close this pull request and open a separate one with an updated Zoom manifest for the all users MSI file? It's fine to have the user-only EXE removed? I just want to make sure I do the next pull request properly.

You can update the existing `Zoom.Zoom` with two installer entries. Installer #1 can be `InstallerType: exe` with `Scope: user` and then Installer #2 can be the `InstallerType: msi` with `Scope: machine`

**Pull request closed without merging**
