### PR TITLE
New package: LinusDierheimer.fastfetch version 1.9.1

### PR DESCRIPTION
**Pull request by sitiom**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/94697)

### CODE REVIEW

**Comment by sitiom** [comment]
Manifest 1.4

**Comment by sitiom** [comment]
- Note: fastfetch is missing out some information, such as terminal font, due to https://github.com/microsoft/winget-cli/issues/2889

**Comment by denelon** [comment]
@sitom I think this can be converted to a "real PR".

**Comment by sitiom** [comment]
There are issues such as https://github.com/microsoft/winget-pkgs/pull/94697#issuecomment-1407229646, though. I wouldn't like to merge a half-working program.

**Review by ItzLevvie — APPROVED** [review]

**Review by niu541412 — APPROVED** [review]

**Comment by CarterLi** [comment]
Hello, I have received [some requests](https://github.com/fastfetch-cli/fastfetch/discussions/955#discussioncomment-9515134) to make fastfetch available in winget. I hope this PR can be made further. A few comments:

1. [This issue](https://github.com/microsoft/winget-pkgs/pull/94697#issuecomment-1407229646) is no longer an issue because [we embedded the the necessary library in fastfetch](https://github.com/fastfetch-cli/fastfetch/tree/dev/src/3rdparty/yyjson). Terminal font should work out of box.
1. The fastfetch version should be updated. The latest version is [v2.13.1](https://github.com/fastfetch-cli/fastfetch/releases).
1. The PackageIdentifier and URLs should be updated. Fastfetch has been moved to Group `fastfetch-cli` and the Windows port of fastfetch was fully written by me @CarterLi.

**Review by niu541412 — APPROVED** [review]

**Comment by niu541412** [comment]
> Hello, I have received [some requests](https://github.com/fastfetch-cli/fastfetch/discussions/955#discussioncomment-9515134) to make fastfetch available in winget. I hope this PR can be made further. A few comments:
> 
> 1. [This issue](https://github.com/microsoft/winget-pkgs/pull/94697#issuecomment-1407229646) is no longer an issue because [we embedded the the necessary library in fastfetch](https://github.com/fastfetch-cli/fastfetch/tree/dev/src/3rdparty/yyjson?rgh-link-date=2024-05-22T01%3A16%3A25Z). Terminal font should work out of box.
> 2. The fastfetch version should be updated. The latest version is [v2.13.1](https://github.com/fastfetch-cli/fastfetch/releases).
> 3. The PackageIdentifier and URLs should be updated. Fastfetch has been moved to Group `fastfetch-cli` and the Windows port of fastfetch was fully written by me @CarterLi.

Have released in wInget-pkgs with updated info, see https://github.com/microsoft/winget-pkgs/pull/94697 @CarterLi

**Comment by sitiom** [comment]
> Have released in wInget-pkgs with updated info, see #154718 @CarterLi

Hi, thanks for the update. I'm currently off-town at the moment, but once I get back, I can set up [Winget Releaser](https://github.com/vedantmgoyal9/winget-releaser) in the fastfetch repo for automated updates (or maybe you can set it up yourself @CarterLi; it's quite easy 🙂).

**Pull request closed without merging**
