### PR TITLE
New version: ScummVM.ScummVM version 2.8.1

### LINKED ISSUE #150324: [Update Request]: ScummVM
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

ScummVM.ScummVM

### Package Version

2.8.1

### Please describe the changes you would like to see

There is a new release (2.8.1) available. Download Page Url: https://www.scummvm.org/en/downloads/ (https://downloads.scummvm.org/frs/scummvm/2.8.1/scummvm-2.8.1-win32.exe)

### PR DESCRIPTION
**Pull request by CoolPlayLin**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.2.1 :rocket:
- Resolves #150324
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150328)

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Looks good, thanks! Not sure about the _Validation-Executable-Error_.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files\ScummVM\scummvm.exe returned exit code: -1073741819

(Automated response - build 877.)

**Comment by AsciiWolf** [comment]
That's weird. It works fine on my system.

**Comment by stephengillie** [comment]
In my testing VM, the GUI version doesn't quite launch, and the Console version gives a few more details before disappearing. (Had to pause the VM to catch it, which is why it's dimmed.)
image

```
WARNING: Could not initialize TTS audio!
WARNING: Could not open audio device: WASAPI can't find requested audio endpoint: Element not found.

WARNING: Unable to enable VSync: That operation is not supported!
WARNING: Libreto is not supported!
```

The first 3 are a known issue:
- https://github.com/microsoft/winget-pkgs/issues/107639

The 4th seems to indicate a dependency on `Libretro.RetroArch`, but this message displays even with that dependency present.

**Comment by AsciiWolf** [comment]
Yeah, most likely because of DX/OpenGL acceleration and other required things. Probably the same thing about the Windows Audio Session API that ScummVM uses to communicate directly with the endpoint audio device.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
