### PR TITLE
Add HandBrake 1.3.2

### PR DESCRIPTION
**Pull request by antigravities**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/355)

### CODE REVIEW

**Comment by danijeljw** [comment]
The yaml file should look like this, the `installer type` is actually `exe`. And it has a silent switch too. 👍 


```yaml
Id: HandBrake.HandBrake
Version: 1.3.2
Name: HandBrake
Publisher: HandBrake
License: GPLv2
LicenseUrl: https://github.com/HandBrake/HandBrake/blob/master/LICENSE
AppMoniker: handbrake
Description: HandBrake is a tool for converting video from nearly any format to a selection of modern, widely supported codecs.
Homepage: https://handbrake.fr/
Installers:
  - Arch: x64
    Url: https://github.com/HandBrake/HandBrake/releases/download/1.3.2/HandBrake-1.3.2-x86_64-Win_GUI.exe
    Sha256: 78F6727431F9065EB3DC3297FFD5CF2822D8866E51A8915A3853633BCEA32E8F
    InstallerType: exe
  - Switches:
        Silent: /s
```

**Comment by antigravities** [comment]
It is actually an NSIS installer, which is why I specified `nullsoft` for `InstallerType`. I don't think that's why the manifest validation is failing though, it validates and installs fine locally. The PR validator just appears to have a problem parsing the YAML file for whatever reason.

**Comment by aslze** [comment]
Looks like the file is UTF16 (or UCS2) Little-endian with BOM. Is it? I don't know if that is supported but I'd make it UTF-8.

**Comment by antigravities** [comment]
It's weird, because the file I committed was generated by the script suggested in the README. Didn't notice it wasn't UTF8, I'll try converting to that later just in case.

**Comment by superusercode** [comment]
closed by #915

**Comment by KevinLaMS** [comment]
Duplicate of #915

**Pull request closed without merging**
