### PR TITLE
New package: topgrade-rs.topgrade version 14.0.1

### LINKED ISSUE #66558: [Package Request]: topgrade
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: https://github.com/topgrade-rs
Publisher Url: https://github.com/topgrade-rs/topgrade
Package Name: topgrade
Description: Keeping your system up to date usually involves invoking multiple package managers. This results in big, non-portable shell one-liners saved in your shell. To remedy this, topgrade detects which tools you use and runs the appropriate commands to update them.
Package Version: 11.0.2
Installer URL: https://github.com/topgrade-rs/topgrade/releases/download/v11.0.2/topgrade-v11.0.2-x86_64-pc-windows-msvc.zip

Current Package Identifier (for new versions):

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

* Resolves #66558

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136492)

### CODE REVIEW

**Comment by Trenly** [comment]
> 2024-01-25 21:15:32.325 [FAIL] Installer failed security check. Url: https://github.com/topgrade-rs/topgrade/releases/download/v14.0.1/topgrade-v14.0.1-x86_64-pc-windows-msvc.zip Result: 0x80004005

Will have to retry in a day or two

**Comment by stephengillie** [comment]
Hi @Trenly,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 660.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-25 21:15:32.325 [FAIL] Installer failed security check. Url: https://github.com/topgrade-rs/topgrade/releases/download/v14.0.1/topgrade-v14.0.1-x86_64-pc-windows-msvc.zip Result: 0x80004005 MSI (s) (60:A8) [21:15:18:632]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (60:FC) [21:15:19:788]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Additional Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [1F74:1C4C][2024-01-25T21:15:16]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 660.)

**Comment by stephengillie** [comment]
Hi @Trenly,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 669.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-26 14:25:48.958 [FAIL] Installer failed security check. Url: https://github.com/topgrade-rs/topgrade/releases/download/v14.0.1/topgrade-v14.0.1-x86_64-pc-windows-msvc.zip Result: 0x80004005 MSI (s) (A0:50) [14:25:36:513]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (A0:F0) [14:25:37:497]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Additional Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [08C0:10B4][2024-01-26T14:25:34]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 669.)

**Comment by stephengillie** [comment]
Hi @Trenly,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 675.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-29 20:17:41.512 [FAIL] Installer failed security check. Url: https://github.com/topgrade-rs/topgrade/releases/download/v14.0.1/topgrade-v14.0.1-x86_64-pc-windows-msvc.zip Result: 0x80004005 MSI (s) (DC:54) [20:17:25:620]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (DC:EC) [20:17:27:589]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Additional Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [0A8C:1874][2024-01-29T20:17:22]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 675.)

**Comment by stephengillie** [comment]
Hi @Trenly,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 694.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-31 18:31:16.586 [FAIL] Installer failed security check. Url: https://github.com/topgrade-rs/topgrade/releases/download/v14.0.1/topgrade-v14.0.1-x86_64-pc-windows-msvc.zip Result: 0x80004005 MSI (s) (BC:68) [18:31:04:096]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (BC:D4) [18:31:05:018]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Additional Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [0460:1FFC][2024-01-31T18:31:01]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 694.)

**Review by stephengillie — APPROVED** [review]

**Comment by niStee** [comment]
@stephengillie Thanks for adding topgrade to winget-pkgs. I was looking forward to automating the process via https://github.com/marketplace/actions/winget-releaser. Would be nice to hear your thoughts on it here https://github.com/topgrade-rs/topgrade/discussions/675.

**Pull request merged**
