### PR TITLE
Add Scoop

### PR DESCRIPTION
**Pull request by NatoBoram**
Requires https://github.com/microsoft/winget-cli/issues/298.

```yaml
InstallerType: ps1
```

Scoop is a command-line installer for Windows.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/825)

### CODE REVIEW

**Comment by NatoBoram** [comment]
I don't know if replying is sufficient for `Needs: author feedback`, but here it is. Requires support for `InstallerType: ps1`.

**Comment by Berkeley-Reject** [comment]
Maybe you could try to create a new directory `manifests/LukeSampson/Scoop` and move the yaml file into it in order to pass the validation test.

**Comment by NatoBoram** [comment]
Oh, I didn't even notice it was missing the `Scoop` folder, my bad!

**Comment by NatoBoram** [comment]
Comment for `Needs: author feedback`.
Requires : 
```yaml
InstallerType: ps1
```

**Comment by KevinLaMS** [comment]
Hey NatoBoram
We do not support PS1 files.

**Comment by NatoBoram** [comment]
It looks like there are open issues about this, like https://github.com/microsoft/winget-cli/issues/298. While this PR doesn't include a fix for https://github.com/microsoft/winget-cli/issues/298, it could be said it's "blocked by https://github.com/microsoft/winget-cli/issues/298" or "requires https://github.com/microsoft/winget-cli/issues/298".

**Comment by denelon** [comment]
The schema for the manifest needs to be updated. I added the .exe label to indicate the dependency on support for the client to support standalone executables.

**Comment by NatoBoram** [comment]
Finally took the time to update it at https://github.com/microsoft/winget-pkgs/pull/19425. It still requires `InstallerType: ps1`, so I don't think the timer should've been triggered in this case.

**Comment by denelon** [comment]
@NatoBoram no worries. I try to keep an eye on everything in any case.

**Pull request closed without merging**
