### PR TITLE
New version: BRL-CAD.brlcad version 7.40.2

### LINKED ISSUE #192947: [Update Request]: BRL-CAD.brlcad 7.40.2
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

BRL-CAD.brlcad

### Package Version

7.40.2

### Please describe the changes you would like to see

Changelog: https://github.com/BRL-CAD/brlcad/blob/a0587001a14bd8673e497681fe748262a0ab9dde/NEWS#L27C24-L37

### PR DESCRIPTION
**Pull request by fancybody**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.6.0 :rocket:

- Resolves #192947

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/193136)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Pull request merged**
