### PR TITLE
New package: meshmakers.octo-cli version 0.0.2304.15002

### PR DESCRIPTION
**Pull request by mmgerald**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/113076&drop=dogfoodAlpha

### CODE REVIEW

**Comment by mmgerald** [comment]
@microsoft-github-policy-service agree [company="meshmakers GmbH"]

**Comment by mmgerald** [comment]
@microsoft-github-policy-service agree [company="meshmakers GmbH"]

**Comment by mmgerald** [comment]
@microsoft-github-policy-service agree company="meshmakers GmbH"

**Comment by stephengillie** [comment]
Hi @mmgerald,

This package installs normally, but doesn't appear to perform any function when launched. Is this expected?

**Comment by mmgerald** [comment]
> Hi @mmgerald,
> 
> This package installs normally, but doesn't appear to perform any function when launched. Is this expected?

Hi @stephengillie,

it is a command line utility (single file/self contained deployment), in my tests the PATH variable was set correctly and in terminal octo-cli returned a help information for the different commands.
Can you confirm this behaviour or what you mean with "no functionality"?

**Comment by stephengillie** [comment]
I'm running it directly, so the PATH variable shouldn't be an issue:
image

**Pull request closed without merging**
