### PR TITLE
Stoplight.Prism version 4.10.6

### PR DESCRIPTION
**Pull request by rodrigoborgesdeoliveira**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/98155)

### CODE REVIEW

**Comment by stephengillie** [comment]
This application expects a command:
```
prism <command>

Commands:
  prism mock <document>              Start a mock server with the given document file
  prism proxy <document> <upstream>  Start a proxy server with the given document file

Options:
  --version  Show version number                                                                               [boolean]
  --help     Show help                                                                                         [boolean]
```

**Comment by rodrigoborgesdeoliveira** [comment]
Hi @stephengillie, is there a field that can be set (with `--version`, for example) in the yaml file that the pipeline can/would use when running the executable validation?

**Comment by stephengillie** [comment]
> Hi @stephengillie, is there a field that can be set (with `--version`, for example) in the yaml file that the pipeline can/would use when running the executable validation?

I think there might be one for `Commands`, but I'm not sure that this is a good way, since adding a switch to the `Commands` in another PR caused issues with the symlink.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
