### PR TITLE
Update: Joplin.Joplin version 2.3.3

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/25010)

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]

**Comment by laurent22** [comment]
@vedantmgoyal2009, it came to my attention that the winget Joplin package also deploys pre-releases. In general that should be avoided because these pre-releases are mainly for beta testing, and can contain bugs or incompatibilities with other Joplin versions.

For example the latest desktop pre-release 2.3 cannot sync with the current Joplin iOS or CLI applications. This will be solved once the official release is out, but for now they are incompatible. So would it be possible to update your process so that pre-releases are not deployed by winget?

**Comment by OfficialEsco** [comment]
This is the reason we have added the Pre Releases https://github.com/microsoft/winget-pkgs/pull/13668#issuecomment-846431219

**Comment by laurent22** [comment]
In general it's relatively safe to install pre-releases, but there are cases where it has to be a user decision. For example in the case I mentioned above if you use the iOS version, you shouldn't install the desktop pre-release because you will no longer be able to sync with your phone until the new iOS app is released.

This situation is rare (it happened twice so far) but can be troublesome enough that it'd be best to keep pre-releases out of the main channel. I hope that makes sense if you need further clarifications let me know.

**Comment by OfficialEsco** [comment]
Hmm okay, would you prefer having the Pre Releases in another "package" or that they use the Pre Release toggle to get them?

**Comment by laurent22** [comment]
@OfficialEsco, I've answered in the pull request thread. I think other packages, such as Chocolatey, simply ignore pre-releases and only deploy actual releases.

**Comment by OfficialEsco** [comment]
Chocolatey does have a Pre-Release branch, however i'm not sure how it works tho, the Package Maintainer probably chooses if they want to use Pre-Release or not.

**Pull request merged**
