### PR TITLE
Add: NextDNS.NextDNS version 2.1.0

### PR DESCRIPTION
**Pull request by quhxl**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/21613)

### CODE REVIEW

**Comment by quhxl** [comment]
Screenshot 2021-07-17 145702

**Comment by quhxl** [comment]
Mhhh...

**Review by OfficialEsco — COMMENTED** [review]
Did you test it on VM or Sandbox?
Found this from the Original addition 
>KevinLaMS: Installation failed suggesting that I need to install device software? https://github.com/microsoft/winget-pkgs/pull/832#issuecomment-633674330

#8308 also failed the automated Validation but passed manual validation by KevinLaMS

**Comment by quhxl** [comment]
I tested in my VM...

**Comment by jedieaston** [comment]
It asks for driver installation, I used this as an example as to why winget needs to be able to trust driver certificates on a user's behalf (there's no issue for it though, it was a discussion thread over somewhere in microsoft/winget-cli).

**Pull request closed without merging**
