### PR TITLE
New version: OpenTofu.Tofu version 1.6.1

### PR DESCRIPTION
**Pull request by kdpuvvadi**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136205)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 655.)

**Comment by kdpuvvadi** [comment]
> Automatic Validation ended with:
> 
> > No errors to post.
> 
> (Automated response - build 655.)

ready to merge then?

**Review by ravager-dk — APPROVED** [review]
All looks good

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 657.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
