### PR TITLE
MoneroProject.MoneroGUIWallet version 0.17.2.2

### PR DESCRIPTION
**Pull request by skatcat743**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14516)

### CODE REVIEW

**Comment by skatcat743** [comment]
I need your help and clarification about this software. The binary is labeled as malware but I disagree.
The Monero GUI Cryptocurrency wallet does have mining code in the daemon but it is not automatic the user must deliberately use advanced mode to enable it. Which is why the binary was flagged by Microsoft Security as "PUA:Win64/CoinMiner" So why does the BOT report back as 
> The installer has been identified as malware. 
Here is Microsoft's documentation stating that not all PUAs are Malware and that Cryptomining is PUA, but again your bot says malware when it means PUA 
The package is free and open source software. 
https://github.com/monero-project/monero-gui
Again let me remind you this does not automatically mine is entirely opt in. 
Looking forward to help to get this issue resolved.

**Comment by denelon** [comment]
@skatcat743, I believe we recently changed the message. Let me run this again to see what it reports now. We may need to make some additional adjustments.

**Comment by skatcat743** [comment]
Thank you for responding,
It seems that I have 2 challenging options.

1. Fork the project with my very limited C++/QML knowledge just to be included here on arbitrary terms. (associated with drama)
2. give up. (What Microsoft lawyers & execs probably want me to do.)
It seems that there are other [projects ](https://docs.microsoft.com/en-us/windows/package-manager/package/binary-validation-errors#what-if-i-cannot-remove-that-code) struggling with this decision to change their software for inclusion. Perhaps something of a compromise could be achieved. Maybe hiding these """"""""""PUAs"""""""""" from winget install, but allowing winget upgrade to process them?

**Comment by denelon** [comment]
@skatcat743 there is another option. The Windows Package Manager has support for private repositories. We're still working on documentation, but the [reference implementation](https://github.com/microsoft/winget-cli-restsource) for the REST API is open source.

**Comment by skatcat743** [comment]
> @skatcat743 there is another option. The Windows Package Manager has support for private repositories. We're still working on documentation, but the [reference implementation](https://github.com/microsoft/winget-cli-restsource) for the REST API is open source.

alright then I'll see if I can get that done. Go ahead and close the PR into this repository.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
​

**Pull request closed without merging**
