### PR TITLE
New version: Gyan.FFmpeg version 7.0

### PR DESCRIPTION
**Pull request by aisgbnok**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/147886)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @aisgbnok,

> This PR's version number 7.0 has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 6.1.1, which has 3 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 876)

**Comment by aisgbnok** [comment]
Hey @stephengillie,

This is a portable installer, so the executable does not place an entry in Windows settings. WinGet seems to do that based on the reported version number in the manifest.

However, I am confident `7.0` is the correct version. The executable reports version `7.0`, and [that is what the author uses](https://github.com/GyanD/codexffmpeg/releases).
image



[This reduction in parameters is not new for `Gyan.FFmpeg` in the `winget-pkgs` repository.](https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/Gyan/FFmpeg) For example, `5.0` -> `5.0.1` -> `5.1`, etc.

**Comment by stephengillie** [comment]
Verify: 
image

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
> [This reduction in parameters is not new for `Gyan.FFmpeg` in the `winget-pkgs` repository.](https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/Gyan/FFmpeg) For example, `5.0` -> `5.0.1` -> `5.1`, etc.

Thanks for letting me know. I'll add it to an exception list for this check. (Currently manual, might be noisy until it's fully automated.)

**Pull request merged**
