### PR TITLE
Update Google.PlatformTools.locale.en-US.yaml

### PR DESCRIPTION
**Pull request by drshtmstry**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/165362)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\adb.exe returned exit code: -1073741515
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\fastboot.exe returned exit code: -1073741515

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 887.)

**Comment by stephengillie** [comment]
URL: - https://dl.google.com/android/repository/platform-tools_r34.0.3-windows.zip 
Invalid URI: The URI scheme is not valid.

(Automated message - build 912)

**Comment by stephengillie** [comment]
Hi @drshtmstry,

The package is still available for download. Why is its manifest being removed?

**Comment by stephengillie** [comment]
URL: https://dl.google.com/android/repository/platform-tools_r34.0.3-windows.zip 
Status Code: 200

(Automated message - build 887)

**Comment by drshtmstry** [comment]
> Hi @drshtmstry,
> 
> The package is still available for download. Why is its manifest being removed?

Old versions are giving validation error which new version don't have.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\adb.exe returned exit code: -1073741515
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\fastboot.exe returned exit code: -1073741515

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 887.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
