### PR TITLE
Added mcmilk.7zip-zstd v21.02 ZS v1.5.0 R1

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/13581)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Hey @arjun-msft whats up with this one?

**Comment by arjun-msft** [comment]
Looks like the installer scan is in progress, will keep an eye on this to see if it fails for some reason.

**Comment by OfficialEsco** [comment]
```
5/22/2021 7:36:17 AM
Status: Completed
##[error] Installer: https://github.com/mcmilk/7-Zip-zstd/releases/download/21.02-v1.5.0-R1/7z21.02-zstd-x32.exe
##[error] Result: Failed
##vso[task.logissue type=error] Operation timed out.

5/22/2021 7:36:53 AM

****************************************************************************************
Installer Validation
****************************************************************************************
Status: Completed
-----------------------------------------------------
Installer https://github.com/mcmilk/7-Zip-zstd/releases/download/21.02-v1.5.0-R1/7z21.02-zstd-x32.exe
Result: Static Analysis Timeout
-----------------------------------------------------
Installer https://github.com/mcmilk/7-Zip-zstd/releases/download/21.02-v1.5.0-R1/7z21.02-zstd-arm64.exe
Result: Validation Succeeded
-----------------------------------------------------
Installer https://github.com/mcmilk/7-Zip-zstd/releases/download/21.02-v1.5.0-R1/7z21.02-zstd-x64.exe
Result: Validation Succeeded
-----------------------------------------------------
Installer https://github.com/mcmilk/7-Zip-zstd/releases/download/21.02-v1.5.0-R1/7z21.02-zstd-arm.exe
Result: Validation Succeeded
-----------------------------------------------------
Result: Failed
```

**Comment by OfficialEsco** [comment]
```
5/22/2021 5:42:56 PM
Status: Completed
##[error] Installer https://github.com/mcmilk/7-Zip-zstd/releases/download/21.02-v1.5.0-R1/7z21.02-zstd-x32.exe Scan information: 'Error information: BlockingDetectionFound'
##[error] Result: Failed

5/22/2021 5:43:04 PM

****************************************************************************************
Installer Validation
****************************************************************************************
Status: Completed
-----------------------------------------------------
Installer https://github.com/mcmilk/7-Zip-zstd/releases/download/21.02-v1.5.0-R1/7z21.02-zstd-x32.exe
Result: Binary Validation Failed
```
Hmm, ok so it seems like the release was a bit dumpy according to their issue thread https://github.com/mcmilk/7-Zip-zstd/issues/206

Luckily its just the 32bit version that is getting flagged

x32: https://www.virustotal.com/gui/url/21233da32ea70b5c3acf39d0965a7ee4e7096b3e535d06e1b48be5e5a89fc69e/detection
x64: https://www.virustotal.com/gui/url/c5c2030aa681269ac2da8ac6016c3af50ea2dd4b6072b1ada9a599b29da46ad6/detection
arm: https://www.virustotal.com/gui/url/70251c65e46416be4978c56e6cfa4b23e9a947ec3f08f48297b5e1d2ab5f8849/detection
arm64: https://www.virustotal.com/gui/url/b31cb218e2229861c07520573c4c7a183c75d1f0d36c24b2997bd14a8d99723d/detection

What do you think we should do about this?

**Comment by OfficialEsco** [comment]
Ehh, ill close this as its the safest

**Pull request closed without merging**
