### PR TITLE
Remove old version of JanDeDobbeleer.OhMyPosh

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
null

### CODE REVIEW

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
image

**Comment by vedantmgoyal2009** [comment]
How did pipelines get passed?

**Comment by OfficialEsco** [comment]
Release: 5 Hours ago
Bot run: 3 Hours ago
New Release: 1 Hour ago -> They deleted the previous version from GitHub

**Comment by vedantmgoyal2009** [comment]
Do you have any idea how to cover these types of things without asking the developer not to delete releases?

Also, @Trenly if you have any idea about it.

**Comment by OfficialEsco** [comment]
IIRC we had a chat with the developer somewhere, and they wanted to use the official site, so you could in theory change your script to do `https://download.calibre-ebook.com/$($version)/calibre-$($version).msi`

**Comment by ItzLevvie** [comment]
> Do you have any idea how to cover these types of things without asking the developer not to delete releases?
> 
> Also, @Trenly if you have any idea about it.

Maybe get the tag release and build URL with it.

For the non-Calibre would probably be something like fetch tags from https://github.com/kovidgoyal/calibre/releases and remove `v` and then save the version into a variable like APP_VERSION and create the URLs.

https://download.calibre-ebook.com/${APP_VERSION}/calibre-${APP_VERSION}.msi
https://download.calibre-ebook.com/${APP_VERSION}/calibre-64bit-${APP_VERSION}.msi

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Should be fixed by https://github.com/microsoft/winget-pkgs/pull/36892.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
