### PR TITLE
Submitting WinZip 26.0

### PR DESCRIPTION
**Pull request by CorelWinZip**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/34454)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
`manifests/c/Corel/WinZip/24.0.14033/Corel.WinZip.yaml` shouldn't be part of this PR. It should be done in a separate PR.

**Comment by CorelWinZip** [comment]
@ItzLevvie then it complains there are 2 manifests so it does not work.

Build log #L35
 One or more errors occurred. (The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.) The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> then it complains there are 2 manifests so it does not work.

No, it doesn't complain.

You're allowed to add **one** package and remove **one** package in **one** PR, but what you're doing here is adding **one** package and removing **two** packages in **one** PR.

What I mean by **two** packages is, that you're removing 24.0.14033 (which counts as a removal) and renaming 25.0.14273 to 26.0.14610 (which counts as another removal because by renaming 25.0.14273 to 26.0.14610, 25.0.14273 is removed).

So, if you want to remove 24.0.14033, you'll need make another PR for that.

You should also avoid making changes to your master branch if you would like to submit multiple applications or packages.

**Comment by CorelWinZip** [comment]
Reverted the 25.0 delete. What is the next step?

**Comment by CorelWinZip** [comment]
@msftbot when is the PR going to be approved?

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
