### PR TITLE
add rust-gnu-1.43.1

### PR DESCRIPTION
**Pull request by CGQAQ**
add rust-gnu-1.43.1(latest version)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1101)

### CODE REVIEW

**Comment by CGQAQ** [comment]
[submission](https://www.microsoft.com/en-us/wdsi/submission/cca06711-4c2a-4780-aaf1-6e04f8f33198)

**Comment by CGQAQ** [comment]
@KevinLaMS (this file)[https://static.rust-lang.org/dist/rust-1.43.1-x86_64-pc-windows-gnu.msi] is Mozilla Rustlang official binary, and static.rust-lang.org is rustlang official website domain, should be ok?

**Comment by CGQAQ** [comment]
https://www.microsoft.com/en-us/wdsi/submission/cca06711-4c2a-4780-aaf1-6e04f8f33198

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
