### PR TITLE
SmokeCloud.FdsPp version 0.2.5

### PR DESCRIPTION
**Pull request by JakeOShannessy**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/99250)

### CODE REVIEW

**Comment by JakeOShannessy** [comment]
@microsoft-github-policy-service agree [company="Smoke Cloud"]

**Comment by JakeOShannessy** [comment]
@microsoft-github-policy-service agree company="Smoke Cloud"

**Comment by stephengillie** [comment]
This package is expecting arguments:
```
FDS pre-processor

Usage: fdspp.exe [OPTIONS] <INPUT-PATH> <OUTPUT-PATH>

Arguments:
  <INPUT-PATH>   Path to the input file or '-' for stdin
  <OUTPUT-PATH>  Path to the input file or '-' for stdin

Options:
      --n-mpi <N-PROCESSES>  Number of MPI processes to use
  -h, --help                 Print help information
...
```

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
