### PR TITLE
Moved: NetEase.YoudaoNote version 6.10

### PR DESCRIPTION
**Pull request by SpecterShell**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/96786)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @SpecterShell,

I wasn't able to find the InstallerUrl from the PackageUrl. Instead, the link to the Windows version appears to be: https://artifact.lx.netease.com/download/ynote-electron/%E6%9C%89%E9%81%93%E4%BA%91%E7%AC%94%E8%AE%B0.exe

Are these the same package? The URI mentions Electron - is this a different version the same package?

**Comment by SpecterShell** [comment]
This one can be downloaded here:
image

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
> This one can be downloaded here: 

Thanks!

**Pull request merged**
