### PR TITLE
PuranSoftware.PuranFileRecovery version 1.2.1

### PR DESCRIPTION
**Pull request by techflashYT**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14513)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Same as #14440

**Comment by sanikdah** [comment]
C:\Users\*****>git commit https://github.com/microsoft/winget-pkgs/pull/14513 --allow-empty --message="Try Again"
fatal: not a git repository (or any of the parent directories): .git

**Comment by OfficialEsco** [comment]
> C:\Users*****>git commit #14513 --allow-empty --message="Try Again"
> fatal: not a git repository (or any of the parent directories): .git

You need to be in the github repo on that branch you want to merge

**Comment by sanikdah** [comment]
> > C:\Users*****>git commit #14513 --allow-empty --message="Try Again"
> > fatal: not a git repository (or any of the parent directories): .git
> 
> You need to be in the github repo on that branch you want to merge

well in the desktop app how do i get to this PR?

**Comment by sanikdah** [comment]
image
like where do i go?

**Comment by OfficialEsco** [comment]
under "Your repositories" click `winget-pkgs`, go trough the process to setup the fork
when the repo is up and running click "current branch" and select the one you want, then in Powershell go to the repo location, then you can use the git commands

**Comment by sanikdah** [comment]
image
This look good?

**Comment by sanikdah** [comment]
should i click push origin?

**Comment by OfficialEsco** [comment]
yap yap, Push or `git push`

**Comment by sanikdah** [comment]
sure is taking a while for that to send

**Comment by sanikdah** [comment]
should I cancel the git push and use the gui push?

**Comment by OfficialEsco** [comment]
> should I cancel the git push and use the gui push?

if you still see Push origin it actually didn't push, just do the gui since you're already there

**Comment by sanikdah** [comment]
there

**Comment by denelon** [comment]
@OfficialEsco thanks for being so patient and helpful! I had no idea we would see this much activity on the holiday weekend. I'm trying to catch up on all the activity. We will discuss moderation options and improvements to wingetcreate today.

**Comment by OfficialEsco** [comment]
> @OfficialEsco thanks for being so patient and helpful! I had no idea we would see this much activity on the holiday weekend. I'm trying to catch up on all the activity. We will discuss moderation options and improvements to wingetcreate today.

The random popularity is because of ThioJoe's video.. https://www.youtube.com/watch?v=uxr7m8wDeGA

**Comment by sanikdah** [comment]
> > @OfficialEsco thanks for being so patient and helpful! I had no idea we would see this much activity on the holiday weekend. I'm trying to catch up on all the activity. We will discuss moderation options and improvements to wingetcreate today.
> 
> The random popularity is because of ThioJoe's video.. https://www.youtube.com/watch?v=uxr7m8wDeGA

Yeah!  I actually just found out about this because of that video and felt the need to contribute because of all the programs that weren't in here.

**Pull request merged**
