### PR TITLE
NotSilent - FailedShack.USBHelperInstaller version 1.2

### PR DESCRIPTION
**Pull request by Masamune3210**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/27052#event-5258362249

**Comment by Masamune3210** [comment]
For some reason I cant understand, when ran from winget it fails with a error about not finding a internet connection and a File Open Error. Running the installer outside of winget manually works fine aside from the lack of a /s flag which I'm going to ask the dev about

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
This is an installer error not related to the Windows Package Manager.

Please contact the application developers for a fix.

You can reproduce this locally without using the Windows Package Manager by doing `"%USERPROFILE%\Downloads\USBHelperInstaller.exe" /S`

**Comment by Masamune3210** [comment]
Will do, will either come back with a fix or close

**Comment by Masamune3210** [comment]
Dev has not gotten back to me on issue, going to close for now

**Pull request closed without merging**
