### PR TITLE
Adding Envolve cli tool

### PR DESCRIPTION
**Pull request by erdemkosk**
Checklist for Pull Requests
- [ x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ x] This PR only modifies one (1) manifest
- [x ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/158801)

### CODE REVIEW

**Comment by erdemkosk** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-06-19 18:26:03.665 [FAIL] Installer failed security check. Url: https://github.com/erdemkosk/envolve/releases/download/v1.0.15/envolve_Windows_x86_64.zip Result: 0x80004005

(Automated response - build 886.)

**Comment by erdemkosk** [comment]
hey , @stephengillie thanks for your effort. I am looking forward it.

**Comment by stephengillie** [comment]
Verify:
image
image

**Comment by erdemkosk** [comment]
Thanks for the comment. I need to fix this

**Comment by erdemkosk** [comment]
@stephengillie hey ı updated new version 1.0.16 and ı fixed color issue on windows + version issue. Thanks for feedback!

**Comment by stephengillie** [comment]
Verify:
image

**Review by stephengillie — APPROVED** [review]

**Review by Misaka13514 — COMMENTED** [review]
Please do not add `.DS_Store` in your commit. Thank you.

**Pull request merged**
