### PR TITLE
New package: VirtualFRA.Installer version 3.6.1.0

### PR DESCRIPTION
**Pull request by schembriaiden**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/151097)

### CODE REVIEW

**Comment by vikingnope** [comment]
@stephengillie, Any ideas on how we can skip this dialogue, maybe you have seen it before:

image

**Comment by stephengillie** [comment]
I've seen this before, but not very often. It seems like an early version or variant of the blue Windows Defender Smart Screen pop-up window. There are ways to disable that, but involve disabling other security systems. It's the one caveat to the silent install requirement.

**Comment by vikingnope** [comment]
Ah, then we might have to scrap this one then

**Comment by stephengillie** [comment]
No, I meant that it's okay and not a blocker.

Installing in a Windows 10 VM, this package didn't seem to add any files to the PC.

**Comment by vikingnope** [comment]
Changed architecture just in case

**Comment by vikingnope** [comment]
Would you be able to check now please

**Comment by stephengillie** [comment]
Other than a couple of cache files, the system doesn't show any modifications from this installation: 
image

**Pull request closed without merging**
