### PR TITLE
New version: OttoZumkeller.QR-CodeReader version 1.1.0

### PR DESCRIPTION
**Pull request by ottozumkeller**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132575)

### CODE REVIEW

**Comment by ottozumkeller** [comment]
winget-cli-install

**Comment by Trenly** [comment]
> 2024-01-03 14:19:10.108 [FAIL] Installer failed security check. Url: https://github.com/ottozumkeller/QR-Code-Reader/releases/download/v1.1.0/QR-Code-Reader-1.1.0.msi Result: 0x80004005

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-03 14:19:10.108 [FAIL] Installer failed security check. Url: https://github.com/ottozumkeller/QR-Code-Reader/releases/download/v1.1.0/QR-Code-Reader-1.1.0.msi Result: 0x80004005

(Automated response - build 516.)

**Comment by stephengillie** [comment]
Hi @ottozumkeller,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 516.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Program Files\QR-Code Reader\reader.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Program Files\QR-Code Reader\reader.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

(Automated response - build 530.)

**Pull request closed without merging**
