### PR TITLE
tabulapdf.tabula version 1.2.1

### PR DESCRIPTION
**Pull request by 14AUDDIN**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/108877)

### CODE REVIEW

**Comment by stephengillie** [comment]
This application installs normally. On first run, it gives a message that it requires JRE, and opens an Oracle website: 
image

With `Oracle.JavaRuntimeEnvironment` preinstalled, it gives the message that it cannot find `WarMain`:
> PS C:\Users\User\Desktop> java -version
java version "1.8.0_371"
Java(TM) SE Runtime Environment (build 1.8.0_371-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.371-b11, mixed mode)
PS C:\Users\User\Desktop> C:\Users\User\AppData\Local\Microsoft\WinGet\Links\tabula.exe
Error: Could not find or load main class WarMain

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Comment by stephengillie** [comment]
Manual Validation ended with:
> PS C:\Users\User\Desktop> C:\Users\User\AppData\Local\Microsoft\WinGet\Links\tabula.exe Error: Could not find or load main class WarMain

(Automated response - build 489.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
