### PR TITLE
Flutter 3.16.1

### PR DESCRIPTION
**Pull request by albertopasqualetto**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/128465)

### CODE REVIEW

**Comment by albertopasqualetto** [comment]
It only has the .bat files

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> An error occurred trying to start process 'C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\flutter.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.

**Review by stephengillie — APPROVED** [review]

**Comment by Yousha** [comment]
Resolves #18414 ?

**Comment by albertopasqualetto** [comment]
@Yousha flutter actually cannot be installed by winget since it is used through a `.bat` file.

**Pull request merged**
