### PR TITLE
FileOpen.FileOpen version 3.0.176.998

### LINKED ISSUE #121595: [Package Request]:
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://plugin.fileopen.com/all.aspx
Publisher: FileOpen Systems Inc.
Package Name: FileOpen Plug-in Installer for Windows
Description: FileOpen Systems provides a set of free plug-ins and viewers that can be used to access documents encrypted with the FileOpen software.
Package Version: Build 998
Installer URL: https://plugin.fileopen.com/current/FileOpenInstaller64.msi

### PR DESCRIPTION
**Pull request by Dragon1573**
Resolve #121595 .

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?
- [x] Have you tested your manifest in Windows Sandbox with `Tools/SandboxTest.ps1 -Manifest <path>`?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/121663)

### CODE REVIEW

**Comment by Dragon1573** [comment]
Related #121595 .

**Comment by Dragon1573** [comment]
While testing in Windows Sandbox, `winget.exe` prompts out an interactive requirements that user should explicitly agree the source agreements terms of `msstore` source.

<details>
<summary>Logs from Windows Sandbox</summary>

```text
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget install -m .\manifests\f\FileOpen\FileOpen\3.0.176.998\
Found FileOpen Client (x64) B998 [FileOpen.FileOpen] Version 3.0.176.998
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").

Do you agree to all the source agreements terms?
[Y] Yes  [N] No: Y
This package requires the following dependencies:
  - Packages
      Adobe.Acrobat.Reader.64-bit
Installing dependencies:
(1/1) Found Adobe Acrobat Reader DC (64-bit) [Adobe.Acrobat.Reader.64-bit] Version 23.006.20320
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://ardownload2.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2300620320/AcroRdrDCx642300620320_MUI.exe
  ██████████████████████████████   422 MB /  422 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Downloading https://plugin.fileopen.com/current/FileOpenInstaller.exe
  ██████████████████████████████  6.51 MB / 6.51 MB
Successfully verified installer hash
Starting package install...
Successfully installed
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs>
```

</details>

Maybe the Azure Pipelines blocked here for `Validation-Unattended-Failed`? How can I agree the terms silently?

**Comment by freddyboy1974** [comment]
Hi, sorry, I don't understand if you need more info from my part. If so, if you want me to open a case with the publisher, i'd be glad to help and submit any issue you ask me to contact support with.

**Comment by Dragon1573** [comment]
Thank you @freddyboy1974 !

The above question is for `winget-pkgs` contributors & collaborators, not for FileOpen Plugin itself. No need for further informations of FileOpen Plugin Client. 

*****

There are some complicated situations to handle with the manifests:

1. `winget.exe` require users to explicitly agree with the `msstore` source agreements terms. Which may cause `Validation-Unattended-Failed` label from @wingetbot .
2. FileOpen Plugin Client require Adobe Acrobat Reader or DC Pro 9+ as dependencies.
3. When configuring Adobe Acrobat Reader 9 (x64) as a "Package Dependency" of FileOpen Plugin Client, `winget.exe` will ONLY skip dependency installation when the exact package `Adobe.Acrobat.Reader.64-bit` is previously installed by user. This may cause package duplications.

**Comment by Trenly** [comment]
>  winget.exe require users to explicitly agree with the msstore source agreements terms. Which may cause Validation-Unattended-Failed label from @wingetbot .

This doesn't affect the pipelines at all, since the tests are executed in an isolated environment

> FileOpen Plugin Client require Adobe Acrobat Reader or DC Pro 9+ as dependencies.

Dependencies aren't enabled in the pipelines yet, this is what is causing the unattended label

**Comment by Dragon1573** [comment]
It seems that https://github.com/microsoft/winget-cli/issues/163 is solved and closed on Aug 30. I can't understand https://github.com/microsoft/winget-cli/issues/163#issuecomment-1703633889 in that issue.

> Dependencies aren't enabled in the pipelines yet.

Could you please explain more?

*****

Currently convert this PR to "Draft" and wait for the implementation.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by Trenly** [comment]
> Could you please explain more?

Dependencies are still an experimental feature until the 1.6 client. Currently, the validation pipeline runs the 1.4 client. This is to ensure that the newer 1.6 version has enough time to roll out to users. It may be a few days or weeks before manifests that have dependencies are able to be automatically processed.

**Comment by Dragon1573** [comment]
Switch status as "Ready for review". As PR #101086 also requires dependencies, but it passed Azure Pipelines and successfully merged.

**Comment by Dragon1573** [comment]
Seems nobody are interested in this pull request, and this version may be outdated.

Close as rejected.

**Comment by tlourey** [comment]
Bugger, I came here hoping this wouldn't need to much to finish. @Dragon1573 , any change your willing to submit again?

**Comment by Dragon1573** [comment]
This package requires Adobe Acrobat series as dependency, which is currently not available for Azure Pipelines.

You can simply copy 3 files from my PR, and submit to this repository for a new PR. I think pipelines will failed as before.

**Pull request closed without merging**
