### PR TITLE
Update: KDE.KDEConnect version 22.04.0 [FP]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | KDE Connect | KDE Connect    |
| Version     | 22.04.0     | 22.04.0 |
| Publisher   | KDE e.V.   | KDE e.V.      |
| ProductCode |           | KDE Connect    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [1364](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/2258307861>)

### CODE REVIEW

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
* Duplicate of #55222

**Comment by OfficialEsco** [comment]
I think we agreed to keep these versions? (which is why they are still there)

**Comment by vedantmgoyal2009** [comment]
Latest is v7.46.2

**Review by jedieaston — CHANGES_REQUESTED** [review]
Why do we need to remove this?

**Review by jedieaston — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/55251#pullrequestreview-917337550

**Review by ItzLevvie — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
