### PR TITLE
Fix: YamlCreate using invalid filename for downloading

### PR DESCRIPTION
**Pull request by SpecterShell**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----
The script obtains the file name by slicing InstallerUrl variable and appends it to the destinaiton path, but sometimes the url doesn't contain a valid filename, which may cause errors.
For example, if InstallerUrl is set to "https://pinyin.thunisoft.com/webapi/v1/setup/downloadSetup?setupid=21f0e88683894ebcb440759c5aa25c47&filename=HuayuPY-V7.2.0.213.exe", the script will use "downloadSetup?setupid=21f0e88683894ebcb440759c5aa25c47&filename=HuayuPY-V7.2.0.213.exe" as file name, which contains an invalid file name character "?".
Many servers tell the client the real file name by adding a "ContentDisposition" field to the response header. If existed, the modified code will use it instead.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/29454)

### CODE REVIEW

**Comment by Trenly** [comment]
I'm not familiar with what this code is actually doing? Would you be able to help me understand how it works?

**Comment by SpecterShell** [comment]
> I'm not familiar with what this code is actually doing? Would you be able to help me understand how it works?

I updated the code so that it will not invoke web requests twice.
The script obtains the file name by slicing InstallerUrl variable and appends it to the destinaiton path, but sometimes the url doesn't contain a valid filename, which may cause errors.
For example, if InstallerUrl is set to "https://pinyin.thunisoft.com/webapi/v1/setup/downloadSetup?setupid=21f0e88683894ebcb440759c5aa25c47&filename=HuayuPY-V7.2.0.213.exe", the script will slice it into "downloadSetup?setupid=21f0e88683894ebcb440759c5aa25c47&filename=HuayuPY-V7.2.0.213.exe", which contains an invalid file name character "?".
Many servers tell the client the real file name by adding a "ContentDisposition" field to the response header. If existed, the modified code will use it instead.

**Comment by jedieaston** [comment]
Why not just name the file `{PackageIdentifier}.{PackageVersion}.{extension}` like winget does? You'll have to write in what the extension is for each installer type, but that way you don't have to rely on a header.  (Or just name it "temp" or something, the extension doesn't really matter for this case I guess). 

I'm fine with this, but I'm just afraid if someone didn't configure their web server correctly you could still get a yucky name.

**Comment by Trenly** [comment]
For the purposes of the script, do we even need the file extension other than for determining the installer type?

**Pull request closed without merging**
