### PR TITLE
Revert "ParagonSoftware.APFS version 2.1.97"

### PR DESCRIPTION
**Pull request by OyePradumya**
Reverts microsoft/winget-pkgs#15055

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15092)

### CODE REVIEW

**Comment by OyePradumya** [comment]
Available here #15085

**Comment by KaranKad** [comment]
Why are you deleting that one 😭

**Comment by KaranKad** [comment]
Those two folders have to merge into one, `Paragon` and `ParagonSoftware`

**Comment by KaranKad** [comment]
Ok this pr is basically does that, its fine

**Pull request merged**
