### PR TITLE
New version: quotient-im.Quaternion version 0.0.96.1

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140312)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 776.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
image

It seems like a dependency is missing, but I'm not sure which package contains `libcrypto-3-x64.dll`.

**Comment by stephengillie** [comment]
[Policy] Needs-Author-Feedback

**Comment by Exorcism0666** [comment]
> Manual Validation ended with:
> image
> 
> It seems like a dependency is missing, but I'm not sure which package contains `libcrypto-3-x64.dll`. 

I don't think Winget supports this and even if we add a dependency, we would have to move the file, which is impossible :  https://github.com/isar/isar/issues/1352#issue-1828013545

**Comment by stephengillie** [comment]
For activities including copying files, something more heavyweight - like a DSC Resource - would be needed.

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Pull request closed without merging**
