### PR TITLE
New version: Tailscale 1.66.3

### PR DESCRIPTION
**Pull request by tiernano**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/153742)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-05-15 14:22:13.105 [CLI ] ShellExecute installer failed: 3221225477
> MSI (s) (2C:C4) [14:22:00:584]: Note: 1: 2205 2:  3: Error 
> MSI (s) (2C:C4) [14:22:01:884]: Note: 1: 2205 2:  3: Error 
> MSI (s) (2C:C4) [14:22:01:884]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1302 
> MSI (s) (2C:C4) [14:22:01:978]: Doing action: SetSetupServiceFailureActions
> MSI (s) (2C:C4) [14:22:01:978]: PROPERTY CHANGE: Adding SetupServiceFailureActions property. Its value is '"C:\Windows\system32\sc.exe" failure Tailscale reset= 60 actions= restart/1000/restart/2000/restart/4000/restart/9000/restart/16000/restart/25000/restart/36000/restart/49000/restart/64000'.
> Action start 14:22:01: SetSetupServiceFailureActions.
> MSI (s) (2C:C4) [14:22:01:978]: Doing action: SetupServiceFailureActions
> Action ended 14:22:01: SetSetupServiceFailureActions. Return value 1.
> Action start 14:22:01: SetupServiceFailureActions.
> Action ended 14:22:01: SetupServiceFailureActions. Return value 1.
> MSI (s) (2C:C4) [14:22:02:009]: Note: 1: 2205 2:  3: Error 
> MSI (s) (2C:C4) [14:22:02:009]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1302 
> MSI (s) (2C:C4) [14:22:03:479]: Executing op: ServiceInstall(Name=Tailscale,DisplayName=Tailscale,ImagePath="C:\Program Files\Tailscale\tailscaled.exe",ServiceType=16,StartType=2,ErrorControl=1,,Dependencies=iphlpsvc[~]netprofm[~]WinHttpAutoProxySvc[~][~][~],,,Password=**********,Description=Connects this computer to others on the Tailscale network.,,SDDLText=D:(A;;CCLCSWRPWPDTLOCRRC;;;SY)(A;;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;BA)(A;;CCLCSWLOCRRC;;;IU)(A;;CCLCSWLOCRRC;;;SU)(A;;0x0010;;;BU)S:(AU;FA;CCDCLCSWRPWPDTLOCRSDRCWDWO;;;WD))
> MSI (s) (2C:C4) [14:22:03:495]: Executing op: ActionStart(Name=SetupServiceFailureActions,,)
> MSI (s) (2C:C4) [14:22:03:495]: Executing op: CustomActionSchedule(Action=SetupServiceFailureActions,ActionType=3073,Source=BinaryData,Target=WixQuietExec,CustomActionData="C:\Windows\system32\sc.exe" failure Tailscale reset= 60 actions= restart/1000/restart/2000/restart/4000/restart/9000/restart/16000/restart/25000/restart/36000/restart/49000/restart/64000)
> MSI (s) (2C:C4) [14:22:05:489]: Note: 1: 2205 2:  3: Error 
> MSI (s) (2C:C4) [14:22:05:489]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 22 
> MSI (s) (2C:C4) [14:22:05:489]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 23 
> MSI (s) (2C:C4) [14:22:05:489]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 16 
> MSI (s) (2C:C4) [14:22:05:489]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 21 
> Property(S): SetupServiceFailureActions = "C:\Windows\system32\sc.exe" failure Tailscale reset= 60 actions= restart/1000/restart/2000/restart/4000/restart/9000/restart/16000/restart/25000/restart/36000/restart/49000/restart/64000
> Property(S): ErrorDialog = ErrorDlg
> MSI (s) (2C:C4) [14:22:05:974]: Note: 1: 2205 2:  3: Error 
> MSI (s) (2C:C4) [14:22:05:974]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1707 
> MSI (s) (2C:C4) [14:22:05:974]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 

Automated error analysis suggests -1978335226 may mean Install successful but system restart may be required.

(Automated response - build 881.)

**Comment by tiernano** [comment]
I double-checked the installer and used the sandbox test and it installs and passes validation. Not sure what the next steps are.

**Comment by stephengillie** [comment]
I had to look up `3221225477`. Converted to hexadecimal, it's 0xC0000005, which sometimes means [Access Violation](https://learn.microsoft.com/en-us/shows/inside/access-violation-c0000005-execute). 

This code is occasionally seen in PRs, despite the install otherwise being successful. Should it be added as an `InstallerSuccessCode` or similar here?

**Comment by tiernano** [comment]
That's weird cause it wasn't needed for 1.66.0, and it's only a minor update. Not the original dev, so not sure what to do next.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Review by stephengillie — APPROVED** [review]

**Comment by tiernano** [comment]
Perfect. Thanks.

**Pull request merged**
