### PR TITLE
Update SparkLabs.Viscosity to 1.9.2

### PR DESCRIPTION
**Pull request by trametheka**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/9353)

### CODE REVIEW

**Comment by trametheka** [comment]
Silent and SilentWithProgress switches are in there and validated.

**Comment by trametheka** [comment]
Just as a follow up to this as an FYI, unless the manifest changes have happened since I made this pull request, the manifest is correct.

I think the issue is the build server is missing either .NET 4.8 or the VC redistributable and our installer is not correctly running those silently, or, a reboot is required after installing one of those pre-requisites. I will make some changes to the installer and resubmit.

@Suirtimed , @denelon , are you able to confirm what the build/test servers have in the way of .NET and VC redist installed? Cheers.

**Comment by denelon** [comment]
@trametheka the Windows Package Manager doesn't support dependencies yet. Does your installer include them? Our validation environment is essentially a base OS without any additional libraries.

**Comment by trametheka** [comment]
@denelon It doesn't include them, but will download and install them if missing. I'll run on the assumption it's getting stuck because the dependency installs are throwing dialogs when the installer is run silently and make some changes. Thanks for the reply.

**Comment by denelon** [comment]
Screenshot 2021-04-21 200324

**Comment by trametheka** [comment]
@denelon Is there a way to force winget to run the install process in verysilent mode? I can't see anything in the help output of winget.

**Comment by denelon** [comment]
I believe we're defaulting to "Silent" for the validation server. You can pass flags for that install mode.

It looks like the manifest has:

Silent: /VERYSILENT /SP- /NORUN

**Comment by arjun-msft** [comment]
@trametheka try changing the SilentWithProgress to be VERYSILENT as well. I think it installs the dependencies with that flag.

**Pull request closed without merging**
