### PR TITLE
Update: Nextcloud.NextcloudDesktop v3.3.82.20211124

### LINKED ISSUE #37497: Automation has determined Nextcloud.NextcloudDesktop 3.4.0.20211129 is unavailable
The URL for version 3.4.0.20211129 of Nextcloud.NextcloudDesktop has been unavailable for 5 or more days.
This package may be removed from the repository if no valid manifest is available in the next 14 days.

If the installer has been moved, please update the manifest with the new URL. If a new version of the package is available, please create a new manifest with the valid URL, version, and SHA256 hash.
If this package is no longer available, please delete the manifest.

```

```

### LINKED ISSUE #37560: Automation has determined TimKosse.FileZilla.Client 3.56.2 is unavailable
The URL for version 3.56.2 of TimKosse.FileZilla.Client has been unavailable for 5 or more days.
This package may be removed from the repository if no valid manifest is available in the next 14 days.

If the installer has been moved, please update the manifest with the new URL. If a new version of the package is available, please create a new manifest with the valid URL, version, and SHA256 hash.
If this package is no longer available, please delete the manifest.

```

```

### PR DESCRIPTION
**Pull request by Trenly**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

* Resolves #37497 
* Resolves #37539 
* Resolves #37538 
* Resolves #37537 
* Resolves #37536 
* Resolves #37535 
* Resolves #37349 
* Resolves #37347 
* Resolves #37560 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/37576)

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]

**Comment by cw789** [comment]
I'm not happy about this PR.
Version 3.3.82 is not anywhere listed as a release -> https://github.com/nextcloud/desktop/tags

This PR ships a release candidate -> v3.4.0-rc2

Version 3.4.0 was withdrawn by Nextcloud as it contains a major bug.
I think 3.4.0-rc2 will probably also contain this bug (https://github.com/nextcloud/desktop/issues/4016).

**Comment by ItzLevvie** [comment]
> Version 3.3.82 is not anywhere listed as a release

We follow versioning in Control Panel because it's what WinGet uses to determine if an app needs to be updated or not.

> This PR ships a release candidate -> v3.4.0-rc2

It's because 3.4.0 is 404 Not Found for some reason so 3.4.0-rc2 takes over.

3.4.0-rc2 does contain the bug you mentioned, though since some people have installed 3.4.0 from WinGet, I don't know if it's a good idea to downgrade everyone by telling them to use `winget install` or `winget upgrade`.

This bug exists in older versions (older than 3.4.0 production) as well: https://help.nextcloud.com/t/desktop-client-3-4-0-destroys-local-time-stamp-and-keeps-uploading-data-to-server/128512/4

**Comment by cw789** [comment]
> We follow versioning in Control Panel because it's what WinGet uses to determine if an app needs to be updated or not.

Thanks. Good to know.

> This bug exists in older versions (older than 3.4.0 production) as well

OK. I understand and also don't think it's a good idea to downgrade then...


So thanks a lot.

**Comment by abysso2** [comment]
> This bug exists in older versions (older than 3.4.0 production) as well: https://help.nextcloud.com/t/desktop-client-3-4-0-destroys-local-time-stamp-and-keeps-uploading-data-to-server/128512/4
> 
> ^ Statement from the developer: "**_EDIT: no, it also hits on older versions. 3.4.1 will have to fix it._**"

Ummm, i think Jos mentions the server version, not the client version:

> 
> I do believe this only hits on systems with Nextcloud 23/Hub II, but I will try to get confirmation for that and if you have evidence to the contrary, let me know.
> 
> EDIT: no, it also hits on older versions. 3.4.1 will have to fix it.

The actual workaround is to downgrade to 3.3.6 ...

**Comment by abysso2** [comment]
> I'm not happy about this PR. Version 3.3.82 is not anywhere listed as a release -> https://github.com/nextcloud/desktop/tags
> 
> This PR ships a release candidate -> v3.4.0-rc2
> 
> Version 3.4.0 was withdrawn by Nextcloud as it contains a major bug. I think 3.4.0-rc2 will probably also contain this bug ([nextcloud/desktop#4016](https://github.com/nextcloud/desktop/issues/4016)).

I installed the AppImage of 3.4.0RC2 and regarding settings /general tab, it says 3.3.82 ...


BTW: No issues so far ...

**Pull request merged**
