### PR TITLE
New version: vim.vim.nightly version 9.1.0105

### PR DESCRIPTION
**Pull request by chrisbra**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/139006)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 735.)

**Review by russellbanks — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @chrisbra,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 748.)

**Comment by stephengillie** [comment]
[Policy] Needs-Attention
[Policy] Validation-Defender-Error

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-13 16:46:08.432 [FAIL] Installer failed security check. Url: https://github.com/vim/vim-win32-installer/releases/download/v9.1.0105/gvim_9.1.0105_x86.exe Result: 0x80004005

(Automated response - build 748.)

**Pull request merged**
