### PR TITLE
Make Multi-line Field Exclude ending Newline

### PR DESCRIPTION
**Pull request by Trenly**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/77652)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
@denelon - Blocking Issue

```
2022-09-02 04:42:57.503 [CLI ] Caught std::exception: No mapping for the Unicode character exists in the target multi-byte code page.
```

microsoft/winget-cli#2057

**Review by jedieaston — APPROVED** [review]

**Review by jedieaston — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
