### PR TITLE
New package: SomePythonThings.WingetUIStore.Pre-release version 3.0.0.0

### PR DESCRIPTION
**Pull request by rakleed**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/143001)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 869.)

**Comment by rakleed** [comment]
What's wrong?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code 1

(Automated response - build 869.)

**Comment by stephengillie** [comment]
> What's wrong?

Nothing, apparently. Some applicaitons give a non-zero exit code.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
