### PR TITLE
Added rule for Manifest-AppsAndFeaturesVersion-Error

### PR DESCRIPTION
**Pull request by denelon**
Also cleaned up a couple of @mention comments not related to an error and deleted disabled rules.

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/66227)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by Trenly — APPROVED** [review]

**Review by Trenly — CHANGES_REQUESTED** [review]
The new labels should be removed when pipelines are rerun or new commits are pushed?
https://github.com/microsoft/winget-pkgs/pull/66223
https://github.com/microsoft/winget-pkgs/pull/66221

Also add one for ShellExecute error?

**Comment by denelon** [comment]
Let's do each change separately, the PR will get ugly with all the id change stuff.

**Comment by Trenly** [comment]
> Let's do each change separately, the PR will get ugly with all the id change stuff.

Sounds good to me

**Review by ryfu-msft — APPROVED** [review]
:shipit:

**Pull request merged**
