### PR TITLE
Add OpenSSL Light 1.1.1

### PR DESCRIPTION
**Pull request by auanasgheps**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3366)

### CODE REVIEW

**Review by auanasgheps — COMMENTED** [review]
Fix

**Comment by auanasgheps** [comment]
I think the re-evaluation did not run.

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
`Manifest Error: Invalid field value. Field: Id Value: ShiningLight.OpenSSL Light Line: 1, Column: 5`

It seems like you can't have spaces in the ID, just remove the space in the ID and File Name

**Review by auanasgheps — COMMENTED** [review]
Fix ID

**Comment by OfficialEsco** [comment]
Missing file name fix

**Comment by auanasgheps** [comment]
dang!

**Review by auanasgheps — COMMENTED** [review]
hope it's the last one...

**Pull request merged**
