### PR TITLE
Compare versions properly (Trenly/winget-pkgs#126)

### PR DESCRIPTION
**Pull request by Trenly**
* Compare versions properly
* Properly cast to array when only single installer
* Bump Version

cc @denelon

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/37378)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Can you add the lowercase and sorting branch so we’re fully up to date?
https://github.com/Trenly/winget-pkgs/pull/127

**Comment by Trenly** [comment]
Cherry picked it onto the branch

**Review by OfficialEsco — APPROVED** [review]

**Review by denelon — APPROVED** [review]

**Comment by OfficialEsco** [comment]
@vedantmgoyal2009 it looks like your automation is still using the bugged 2.0.2 version, i would highly advice you to upgrade to version 2.0.4

**Comment by vedantmgoyal2009** [comment]
I have now upgraded YamlCreate to v2.0.4 👍

**Pull request merged**
