### PR TITLE
HP.HPConnectivityKit version 1.40.13865.0

### PR DESCRIPTION
**Pull request by sennasealy**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `manifests\h\HP\HPConnectivityKit\1.40.13865.0` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/17348)

### CODE REVIEW

**Comment by DylanSealy** [comment]
Can't find the problem. Locally working in Windows Sandbox. Maybe the URL must be https?

**Comment by denelon** [comment]
From "Details" below.

```
6/12/2021 11:05:46 PM
Installer Availability and Hash Validation
Status: Started
Installer: http://www.hp-prime.de/files/HP_Prime_Connectivity_Kit_20180706.exe

6/12/2021 11:07:07 PM
Status: Completed
##[error] Installer http://www.hp-prime.de/files/HP_Prime_Connectivity_Kit_20180706.exe
##[error] Result: Failed
##vso[task.logissue type=error] Error occurred while downloading installer from http://www.hp-prime.de/files/HP_Prime_Connectivity_Kit_20180706.exe. 0x8A15002E.
Error information: 
Http Response: OK
Http Reason Phrase: OK

6/12/2021 11:07:34 PM

****************************************************************************************
Installer Validation
****************************************************************************************
Status: Completed
-----------------------------------------------------
Installer http://www.hp-prime.de/files/HP_Prime_Connectivity_Kit_20180706.exe
Result: Download Failed
-----------------------------------------------------
Result: Failed
```

HTTPS URLs are preferred, but I'm not sure validation got that far. It looks like the installer wasn't downloaded.

**Comment by DylanSealy** [comment]
I found this https://github.com/microsoft/winget-cli/issues/932.

**Pull request closed without merging**
