### PR TITLE
feat: adds ngrok 3.15.1

### PR DESCRIPTION
**Pull request by baywet**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164122)

### CODE REVIEW

**Comment by baywet** [comment]
( I filed a report)

**Comment by baywet** [comment]
@stephengillie @JohnMcPMS After filing a report, and getting in touch with the ngrok team, it seems they've been trying to get support from the smart screen team for months. Any idea how we could get this unblocked?

**Comment by stephengillie** [comment]
Unfortunately, I haven't worked with anyone on that team, and so I don't have any contacts internally to call upon.

**Comment by baywet** [comment]
Giving up on this one. Smartscreen never got back to me on the issue, switching to the alternative [dev tunnels](https://learn.microsoft.com/en-us/azure/developer/dev-tunnels/get-started?tabs=windows) which are available on winget as well.

**Pull request closed without merging**
