### PR TITLE
New version: GlennDelahoy.SnappyDriverInstallerOrigin version 1.12.20.761

### LINKED ISSUE #137824: [Hash problem during installation]:GlennDelahoy.SnappyDriverInstallerOrigin
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

My problen is that whatever i do i couldn't install this package.

1.- Search by "snappy driver installer"

2.- Found 3 packages and select the winget.

3.- Try to install it and receive a message indicating me that there was an error with the hash.
      Found Snappy Driver Installer Origin [GlennDelahoy.SnappyDriverInstallerOrigin] Version 1.12.18
      This application is licensed to you by its owner.
      Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
      Downloading https://www.glenn.delahoy.com/downloads/sdio/SDIO_1.12.18.759.zip
        5.95 MB / 5.95 MB
      Installer hash does not match; this cannot be overridden when running as admin

4.- Try to install clicking wrigt and select "#Omitir comprobacion de hash" 
      Found Snappy Driver Installer Origin [GlennDelahoy.SnappyDriverInstallerOrigin] Version 1.12.18
      This application is licensed to you by its owner.
      Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
      Downloading https://www.glenn.delahoy.com/downloads/sdio/SDIO_1.12.18.759.zip
        5.95 MB / 5.95 MB
      Installer hash does not match; this cannot be overridden when running as admin

5.- Then I change the package options and select "Omitir comprobacion de hash" and unselect "Ejecutar como admin", with identical result

6.- I also try to add "--ignore-security-hash" in the argument command line, but the same.

[wingetui.log.txt](https://github.com/microsoft/winget-pkgs/files/14156913/wingetui.log.txt)

### Steps to reproduce

Try to install the package.

### Actual behavior

Could not install the package

### Expected behavior

Install the refereced package.

### Environment

```raw
PS C:\Users\tomas> winget --info
Administrador de paquetes de Windows v1.6.3482
Copyright (c) Microsoft Corporation. Todos los derechos reservados.

Windows: Windows.Desktop v10.0.22631.3085
Arquitectura del sistema: X64
Paquete: Microsoft.DesktopAppInstaller v1.21.3482.0

Directorios de WinGet
-----------------------------------------------------------------------------------------------------------------------
Registros                                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalS…
Configuración de usuario                    %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalS…
Directorio de vínculos portátiles (usuario) %LOCALAPPDATA%\Microsoft\WinGet\Links
Directorio de vínculos portátiles (equipo)  C:\Program Files\WinGet\Links
Raíz de paquete portátil (usuario)          %LOCALAPPDATA%\Microsoft\WinGet\Packages
Raíz de paquete portátil                    C:\Program Files\WinGet\Packages
Raíz de paquete portátil (x86)              C:\Program Files (x86)\WinGet\Packages
Descargas del instalador                    %USERPROFILE%\Downloads

Vínculos
-----------------------------------------------------------------------------------
Declaración de privacidad   https://aka.ms/winget-privacy
Contrato de licencia        https://aka.ms/winget-license
Avisos de terceros          https://aka.ms/winget-3rdPartyNotice
Página principal            https://aka.ms/winget
Términos de Microsoft Store https://www.microsoft.com/en-us/storedocs/terms-of-sale

Configuración de administrador            Estado
-------------------------------------------------------
LocalManifestFiles                        Deshabilitado
BypassCertificatePinningForMicrosoftStore Deshabilitado
InstallerHashOverride                     Deshabilitado
LocalArchiveMalwareScanOverride           Deshabilitado
```

### Screenshots and Logs

Name                           Id                                       Version Source---------------------------------------------------------------------------------------Snappy Driver Installer Origin GlennDelahoy.SnappyDriverInstallerOrigin 1.12.18 winget

---------Pip
Package | Version | Description
---------------------------------
snappy|3.1.1|Studying the topology and geometry of 3-manifolds, with a focus on hyperbolic structures.
snappy2|0.3|Detect faces and draw overlay images
py-custom-driver-installer|0.0.1|Installs a webdriver from a specified resource/url and returns the path where the file was installed (zip files only)
installer|0.7.0|A library for installing Python wheels.
snappy-hx711|1.0.0|Synapse SNAPpy library for HX711 Load Cell Amplifier/ADC
snappy-manifolds|1.2|Database of snappy manifolds
snappy-stream|0.9.0|Streaming snappy compression for Python file-like objects, with helpers for local FS + S3
aws-snappy|2.1.0|Snappy is a Python library that facilitates taking root volume snapshots from EC2 as well as other EBS volumes.
ctypes-snappy|1.03|Python ctypes interface to Google's libsnappy compression.
py-snappy|0.1.0a1|py-snappy: A pure python implementation of the Snappy compression algorithm
snappy-mpu6050|1.0.0|Synapse SNAPpy library for Ivensense MPU-6050 6-axis accelerometer/gyro
swift-snappy|0.0.1|Crawl any website, extracting URLs, images, or clean screenshots.
python-snappy|0.6.1|Python library for the snappy compression library from Google
aff4-snappy|0.5.1|Python library for the snappy compression library from Google
snappy-15-knots|1.2|Database of snappy manifolds
python-mong0|4.2.0|Python driver for MongoDB <http://www.mongodb.org>
pymongo|4.6.1|Python driver for MongoDB <http://www.mongodb.org>
motor|3.3.2|Non-blocking MongoDB driver for Tornado or asyncio
driver|0.1.0|Support for Pytorch programs.
driver2200087|0.6.1|Python Package to interface with Radio Shack's 2200087 Multimeter
snappi-convergence|0.4.1|A snappi extension for measuring network convergence
pyproject-installer|0.5.2|Pyproject installer
ph-installer|3.2|Installer code for photon
addons-installer|4.1.1|Allow to find Odoo addons from Environment Variables
gae_installer|1.9.54.4|Google App Engine Installer
alfred-installer|0.1.2|A script to install all your favourite applications and perform the most common tasks in Debian, Ubuntu and derivatives
mo-installer|0.3.0|Smoothly integrates mo files in setuptools packaging
qt-installer|0.1.0|Yet Another QT Installer (ya-q-ti!) - A CLI for installing Qt packages and tooling; for use in enviroments like GitHub Actions or Docker
deployme-installer|0.1dev|Simple installer for deployme
ceph-installer|1.3.1|An HTTP API that provides Ceph installation/configuration endpoints
helix-installer|0.0.1|Placeholder for helix-installer package
jupyter_installer|1.0.1|finds all import in jupyter notebook, check if they are alredy present if not then install it.
llvm-installer|1.4.0|Allows installing pre-built LLVM packages for various operating systems
drvn.installer|0.3.7|
PyPI-Installer|1.0.1|A small module for dynamic importing Python packages
scipion-installer|1.0.16|Installs scipion 3 creating a virtual environment for it, for now only for developers.
chromedriver_installer|0.0.6|Chromedriver Installer
font-installer|0.1.2|
cloudmesh-installer|5.0.2|Installer for cloudmesh
djangocms-installer|2.0.0|Command to easily bootstrap django CMS projects

--------
   - 
   \ 
   | 
                                                                                                                        

  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 9.13 MB
  ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 9.13 MB
  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 9.13 MB
  █████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 9.13 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 9.13 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 9.13 MB
  ██████████████████████▒▒▒▒▒▒▒▒  7.00 MB / 9.13 MB
  ██████████████████████████▒▒▒▒  8.00 MB / 9.13 MB
  █████████████████████████████▒  9.00 MB / 9.13 MB
  ██████████████████████████████  9.13 MB / 9.13 MB
                                                                                                                        
Found Snappy Driver Installer Origin [GlennDelahoy.SnappyDriverInstallerOrigin]

Version: 1.12.18

Publisher: Glenn Delahoy

Publisher Url: https://www.glenn.delahoy.com/

Publisher Support Url: https://www.glenn.delahoy.com/forums/forum/snappy-driver-installer-origin/

Author: Glenn Delahoy

Description: Snappy Driver Installer Origin is a portable Windows tool to install and update device drivers. It can be used offline to install drivers where Internet isn’t available. No more searching for drivers after a clean install, just let Snappy Driver Installer Origin do it’s thing and your job will be done in no time. The perfect technician’s tool.

Homepage: https://www.glenn.delahoy.com/snappy-driver-installer-origin/

License: GPLv3

License Url: https://www.glenn.delahoy.com/snappy-driver-installer-origin/

Privacy Url: https://www.glenn.delahoy.com/privacy-policy/

Purchase Url: https://www.glenn.delahoy.com/subscribe-to-snappy-driver-installer-origin/

Documentation:

  FAQs: https://www.glenn.delahoy.com/sdio-faq/

Installer:

  Installer Type: portable (zip)

  Installer Url: https://www.glenn.delahoy.com/downloads/sdio/SDIO_1.12.18.759.zip

  Installer SHA256: a25f87822152e3541ce41af376e40f8f3df3f21b86fb25cdb970fdf162294cf2

--------dotnet

"dotnet-tools-outdated" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.---------Npm
"npm" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

---------Npm@global
"npm" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
---------Scoop
scoop : El trmino 'scoop' no se reconoce como nombre de un cmdlet, funcin, archivo de script o programa ejecutable.
Compruebe si escribi correctamente el nombre o, si incluy una ruta de acceso, compruebe que dicha ruta es correcta e
intntelo de nuevo.
En lnea: 1 Carcter: 1
+ scoop status
+ ~~~~~
+ CategoryInfo          : ObjectNotFound: (scoop:String) [], CommandNotFoundException
+ FullyQualifiedErrorId : CommandNotFoundException
---------Chocolatey
Chocolatey v2.2.2
Outdated Packages
Output is package name | current version | available version | pinned?Chocolatey has determined 0 package(s) are outdated.

---------Winget
- 
   \ 
   | 
   / 
                                                                                                                        

  ███▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  1024 KB / 9.13 MB
  ██████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  2.00 MB / 9.13 MB
  █████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  3.00 MB / 9.13 MB
  █████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒  4.00 MB / 9.13 MB
  ████████████████▒▒▒▒▒▒▒▒▒▒▒▒▒▒  5.00 MB / 9.13 MB
  ███████████████████▒▒▒▒▒▒▒▒▒▒▒  6.00 MB / 9.13 MB
  ██████████████████████▒▒▒▒▒▒▒▒  7.00 MB / 9.13 MB
  ██████████████████████████▒▒▒▒  8.00 MB / 9.13 MB
  █████████████████████████████▒  9.00 MB / 9.13 MB
  ██████████████████████████████  9.13 MB / 9.13 MB
                                                                                                                        

   - 
   \ 
                                                                                                                        
Name                       Id                                Version     Available     Source
---------------------------------------------------------------------------------------------
MariaDB 10.6 (x64)         MariaDB.Server                    10.6.13.0   10.9.3.0      winget
DeepL                      DeepL.DeepL                       Unknown     23.11.2.11449 winget
Sonarr version 3.0         TeamSonarr.Sonarr                 3.0.10.1567 4.0.0.748     winget
Radarr version 4.7.5       TeamRadarr.Radarr                 4.7.5       5.2.6         winget
LibreOffice 7.6.4.1        TheDocumentFoundation.LibreOffice 7.6.4.1     24.2.0.3      winget
Java 8 Update 381          Oracle.JavaRuntimeEnvironment     8.0.3810.9  8.0.4010.10   winget
Java 8 Update 381 (64-bit) Oracle.JavaRuntimeEnvironment     8.0.3810.9  8.0.4010.10   winget
Jackett                    Jackett.Jackett                   0.21.1217   0.21.1672     winget
8 upgrades available.

---------Pip

### PR DESCRIPTION
**Pull request by Exorcism0666**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---
- Resolve: #137824

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification.
>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

> This PR's version number 1.12.20.761 has 4 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version 1.12.18, which has 3 parameters.

Is this intentional?

(Automated response - build 695)

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

> This PR's version number 1.12.20.761 has 4 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version 1.12.18, which has 3 parameters.

Does this PR's version number **exactly** match the version reported in the Apps and Features settings page? (Feel free to attach a screenshot.)

(Automated response - build 700)

**Pull request closed without merging**
