### PR TITLE
Update to ZoomOutlookPlugin 5.14.0

### PR DESCRIPTION
**Pull request by BrandonWanHuanSheng**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101395)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101395)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
Most likely, It is successful pipeline. Because I run with the wingetcreate utility tool.

**Comment by BrandonWanHuanSheng** [comment]
I am sorry causing @wingetbot check to restart.

**Comment by BrandonWanHuanSheng** [comment]
Checking and reconfirming to point the file. 
yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.4.0.schema.json.

**Comment by BrandonWanHuanSheng** [comment]
Normally, when I look back at my wingetcreate.

**Comment by BrandonWanHuanSheng** [comment]
##[warning]Resource file has already set to: D:\a\_tasks\ComponentGovernanceComponentDetection_f2f0881f-4b99-4a1c-80ea-f5b13fd6cec4\0.2320331.1\task.json
I ignored it. What is this?

**Comment by BrandonWanHuanSheng** [comment]
If this one still failed. Most likely, I will delete x64. Most likely, the publisher URL give me x86 build only. But winget will not show up winget show x86 into x64. There is no installer for x64.

**Comment by BrandonWanHuanSheng** [comment]
@stephengillie It look like my pull request failed again.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
> @stephengillie It look like my pull request failed again. Normally, it just 66 min during install validation

These `Internal-Error-Dynamic-Scan` errors are an internal pipeline issue. Sorry for the inconvenience.

**Pull request merged**
