### PR TITLE
Move: rhysd.actionlint version 1.6.24

### PR DESCRIPTION
**Pull request by sitiom**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101511)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation failed with:
> 2023-04-04 08:51:14.290 [FAIL] Installer failed security check. Url: https://github.com/rhysd/actionlint/releases/download/v1.6.24/actionlint_1.6.24_windows_386.zip Result: 0x80004005

**Comment by sitiom** [comment]
What's that supposed to mean? False positive?

**Comment by stephengillie** [comment]
> What's that supposed to mean? False positive?

From https://github.com/microsoft/winget-pkgs/pull/101324#issuecomment-1494972091
> The "failed security check" is usually defender / smartscreen flagging the URL as an unknown / potentially malicious URL before the download ever completes

**Comment by BrandonWanHuanSheng** [comment]
But I download from Microsoft Edge is not flagged as malicious. 
Screenshot (146)

**Comment by sitiom** [comment]
https://github.com/microsoft/winget-pkgs/pull/102567

**Comment by sitiom** [comment]
- https://github.com/microsoft/winget-pkgs/pull/102052#issuecomment-1502066644
- https://github.com/microsoft/winget-pkgs/pull/102567

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
