### PR TITLE
New version: Volta.Volta version 2.0.1

### PR DESCRIPTION
**Pull request by charlespierce**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/168181)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files\Volta\node.exe returned exit code: -1073741515
> Executable C:\Program Files\Volta\npm.exe returned exit code: -1073741515
> Executable C:\Program Files\Volta\npx.exe returned exit code: -1073741515
> Executable C:\Program Files\Volta\pnpm.exe returned exit code: -1073741515
> Executable C:\Program Files\Volta\volta.exe returned exit code: -1073741515
> Executable C:\Program Files\Volta\volta-migrate.exe returned exit code: -1073741515
> Executable C:\Program Files\Volta\volta-shim.exe returned exit code: -1073741515
> Executable C:\Program Files\Volta\yarn.exe returned exit code: -1073741515
> Executable C:\Program Files\Volta\yarnpkg.exe returned exit code: -1073741515

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 887.)

**Comment by charlespierce** [comment]
Hi @stephengillie, is there a way I can see the full output of that automated validation? Neither the x64 nor the arm64 builds should have a dependency on `Microsoft.VCRedist` any more, they are both built with it statically linked.

**Comment by stephengillie** [comment]
Hi @charlespierce,

Yes - It's a bit of a quest:
- Click the [Checks](https://github.com/microsoft/winget-pkgs/pull/157658/checks?check_run_id=26176504766) tab.
- Unfurl `Azure Pipelines`, click `WinGetSvc-Validation` to open that section, then click [View more details on Azure Pipelines](https://dev.azure.com/ms/ed6a5dfa-6e7f-413b-842c-8305dd9e89e6/_build/results?buildId=581650).
- In the tab that just opened, near `Related`, click [4 published; 1 consumed](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=581650&view=artifacts&pathAsName=false). (The number of published might vary a bit.)
- Find `InstallationVerificationLogs` and follow that line to the right edge. Put your mouse there, and 3 vertical dots should appear. Click them, then click `Download artifacts`. This should start a download in your browser.
- Unzip the download - it should contain a set of text files and logs foreach combination of architecture and scope that was validated. 

I've automated the above into a PowerShell script, which then filters for "error", "exception" and "fail", and then filters out the noise. Then matches any strings against a list of error codes, and adds these "automated error analysis" bits to the output string, and posts all of this to the PR comments thread. My previous comment was its output.

**Comment by charlespierce** [comment]
Thanks for those instructions @stephengillie! It turns out it was an environment issue with our CI build that caused it to not build correctly. I've updated with the new info and it should be good!

**Comment by stephengillie** [comment]
Verify:
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
