### PR TITLE
New version: AgileBits.1Password version 8.10.22

### PR DESCRIPTION
**Pull request by rakleed**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/130475)

### CODE REVIEW

**Comment by Trenly** [comment]
* Duplicate of #130395

**Comment by rakleed** [comment]
@stephengillie could you please reopen issue?

**Comment by stephengillie** [comment]
Hi @rakleed,

Yes - but why? The manifest version already exists in the repo.

**Comment by rakleed** [comment]
What is the problem?

**Comment by stephengillie** [comment]
> What is the problem?

Hi @rakleed,

The flies in this PR already exist in the repo. They were added in https://github.com/microsoft/winget-pkgs/pull/130395. I'm going to close this PR as a duplicate.

**Pull request closed without merging**
