### PR TITLE
Added Unifi Identity Desktop 0.1.10.26

### PR DESCRIPTION
**Pull request by bearmannl**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

Initial release of the Identity for Windows desktop app. This is the new 'free tier' Identity solution, not the enterprise solution (UbiquitiInc.UI).
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132640)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 

(Automated response - build 516.)

**Comment by bearmannl** [comment]
Is this a bug? The validation passed.

**Comment by bearmannl** [comment]
> Is this a bug? The validation passed.

              > @walderston I'm not able to find the download link in the publisher page to confirm the URI. Could you provide a link to the downloads page where you got this URI from? I did confirm that ubnt.com forwards to ui.com, but I'd want to see something pointing from ui.com to ubnt.com to be completely sure.

@lechacon

You have to be signed into a UI account to be shown the download links for their new application 'UI Desktop'.

Doing a registration lookup on ubnt.com shows it is owned by Ubiquiti Networks the same as UI.com - https://lookup.icann.org/lookup?q=ubnt.com&t=a (registration last updated in 2018 and valid to 2026).

Also looking at an archive from 2018 shows the main website on ubnt.com. In 2018, they started to move things over to UI.com however have not moved over all their downloads. - such as https://web.archive.org/web/20180223141805/https://www.ubnt.com/

Also looking at the community support site shows many threads about both the move from ubnt.com to ui.com such as [XX ](https://community.ui.com/questions/UBNT-com-Changed-to-UI-com/491f0b28-4d2e-4dbd-9e83-72a10f1ddf50#answer/5c376264-f526-4c33-af44-d52ff591df33) and general support issues around using the ubnt.com page (https://community.ui.com/questions/unifi-crededentials-not-working-at-ui-com-but-ubnt-com-seems-OK/0c4eac0c-10f9-4147-8d3e-a18d6e3b6b92)

If this isn't good enough, I'll close this PR.

_Originally posted by @walderston in https://github.com/microsoft/winget-pkgs/issues/57788#issuecomment-1099969928_
            
Just found this on the UI Desktop client pull request. Can someone add a validation waiver to verify? Same issue as the UI Desktop client, this is the new 'free' tier Identity client, whereas the UI Desktop client is intended for the Enterprise variant.

**Comment by stephengillie** [comment]
Hi @bearmannl,

Could you add an InstallerUrl?

(Automated response - build 528.)

**Comment by bearmannl** [comment]
> Hi @bearmannl,
> 
> Could you add an InstallerUrl?
> 
> (Automated response - build 528.)

Sure, here you go:
https://fw-download.ubnt.com/data/uid-identity-standard-desktop-app/d41c-windows-0.1.10-44709fd3-e269-4184-af77-77292f4aa332.exe

**Comment by bearmannl** [comment]
> > > Hi @bearmannl,
> > > Could you add an InstallerUrl?
> > > (Automated response - build 528.)
> > 
> > 
> > Sure, here you go: https://fw-download.ubnt.com/data/uid-identity-standard-desktop-app/d41c-windows-0.1.10-44709fd3-e269-4184-af77-77292f4aa332.exe
> 
> Thanks - I had a typo in my automated response. Could you provide the PackageUrl?
> 
> Additionally, I couldn't find executables for this package. How should I be interacting with it?

Hmmm, I thought the silent switch installs the application, but appears I already had it running during testing and it doesn't actually install.

Let me close and figure this out later.

**Pull request closed without merging**
