### PR TITLE
New version: TheBrowserCompany.Arc version 0.13.1.15859

### PR DESCRIPTION
**Pull request by Exorcism0666**
﻿Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/145449)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-03-20T11:09:12.6855389Z ##[error] Manifest Error: Failed to process installer. [InstallerUrl] Value: https://releases.arc.net/windows/***/Arc.appinstaller

(Automated response - build 870.)

**Comment by Exorcism0666** [comment]
@trenly @stephengillie I would like some help for this, please. 👀 

@SpecterShell You can activate your automation for this manifest.

**Comment by Trenly** [comment]
`InstallerType: msix` has special validations that decompose the MSIX package and read the manifest inside to validate certain parameters like `MinimumOSVersion`. Because the file is `.appinstaller`, it can't be decomposed as an MSIX package

**Comment by Exorcism0666** [comment]
> `InstallerType: msix` has special validations that decompose the MSIX package and read the manifest.xml inside to validate certain parameters like `MinimumOSVersion`. Because the file is `.appinstaller`, it can't be decomposed as an MSIX package

Oh interesting! So what should i put instead ?

**Comment by Trenly** [comment]
> Oh interesting! So what should i put instead ?

It may need to go through manual validation, or it might simply be an unsupported file format

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by SpecterShell** [comment]
> @Trenly @stephengillie I would like some help for this, please. 👀
> 
> @SpecterShell You can activate your automation for this manifest.

Activated

**Pull request closed without merging**
