### PR TITLE
New version: mentebinaria.retoolkit version 2023.05

### PR DESCRIPTION
**Pull request by SpecterShell**
image
This version comes with Npcap, which forbids silent installation.

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/108566)

### CODE REVIEW

**Comment by stephengillie** [comment]
This package is 1.48 GB. 

Automatic Validation ended with:
image

Manual Validation ended with: 
image

It appears that this installer runs the Npcap installer, which isn't unattended. Is there an installer switch to have it run silently?

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Manual Validation hangs on ImHex.lnk. Is there anything unusual about this program?

**Comment by SpecterShell** [comment]
> Manual Validation hangs on ImHex.lnk. Is there anything unusual about this program?

Idk both the installer and ImHex work properly in Windows Sandbox.

image

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package failed Manual Validation as it put the VM into an unusual state without networking.

**Comment by stephengillie** [comment]
Manual Validation failed with the VM unable to network to other PCs.

**Comment by stephengillie** [comment]
One of the applications in this package captures the computer's networking.

**Pull request merged**
