### PR TITLE
New version: Docker version 4.1.1

### PR DESCRIPTION
**Pull request by soroshsabz**
ITNOA

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest manifests/d/Docker/DockerDesktop/4.1.1`? 
- [x] Have you tested your manifest locally with `winget install --manifest manifests/d/Docker/DockerDesktop/4.1.1`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/30328)

### CODE REVIEW

**Review by jedieaston — APPROVED** [review]

**Comment by soroshsabz** [comment]
@jedieaston @denelon Please re-run AzurePipelines for this PR

thanks

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Close and reopen the PR to rerun pipelines.

**Review by ghost — APPROVED** [review]

**Pull request merged**
