### PR TITLE
New version: riweston.aztx 1.1.0

### PR DESCRIPTION
**Pull request by riweston**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/145727)

### CODE REVIEW

**Comment by riweston** [comment]
Linked to #145728

**Comment by riweston** [comment]
Is this step trying to manually run the executable? If so I would expect a failure as the tool expects a user to have `azure-cli` present and logged in, otherwise a none-zero exit code would be generated...

I could add a benign argument like `--version` which would prove the tool works/generates an exit code 0 for automated tests if it's possible to pass in a parameter for the purposes of testing?

**Comment by Exorcism0666** [comment]
> Automatic Validation ended with:
> 
> > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\riweston.aztx__DefaultSource\aztx.exe returned exit code: 1
> > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\aztx.exe returned exit code: 1
> > Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Packages\riweston.aztx__DefaultSource\aztx.exe returned exit code: 1
> > Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\aztx.exe returned exit code: 1
> 
> (Automated response - build 870.)

image

**Comment by riweston** [comment]
> > Automatic Validation ended with:
> 
> > 
> 
> > > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\riweston.aztx__DefaultSource\aztx.exe returned exit code: 1
> 
> > > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\aztx.exe returned exit code: 1
> 
> > > Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Packages\riweston.aztx__DefaultSource\aztx.exe returned exit code: 1
> 
> > > Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\aztx.exe returned exit code: 1
> 
> > 
> 
> > (Automated response - build 870.)
> 
> 
> 
> image
> 
> 

Yep, that's the error that I'd expect to see without the prerequisites set up 🙂

**Comment by stephengillie** [comment]
> Yep, that's the error that I'd expect to see without the prerequisites set up 🙂

It's become something akin to a known bug, especially with CLI applications. Thanks for your patience.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
