### PR TITLE
New version: Julialang.Juliaup version 1.14.9.0

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#5730](https://github.com/SpecterShell/Dumplings/actions/runs/9432135626).

<details>

<summary>Log</summary>

````
Updated: 1.14.8.0 → 1.14.9.0
No ReleaseNotes (en-US) for version 1.14.9.0
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/157151)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2146762487
> 2024-06-08 19:48:16.001 [CORE] Deployment operation #0: error 0x800B0109: The root certificate of the signature in the app package or bundle must be trusted.
> 2024-06-08 19:48:16.001 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!00007FFC53983F75: (caller: 00007FFC538DA720) Exception(1) tid(1d60) 800B0109 A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
> 2024-06-08 19:48:16.255 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFC53982D2F: (caller: 00007FFC5398432C) Exception(2) tid(1d60) 80073CF1 Package was not found.
> 2024-06-08 19:48:16.256 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(126)\WindowsPackageManager.dll!00007FFC53AF8931: (caller: 00007FFC53985853) LogHr(1) tid(1d60) 80073CF1 Package was not found.
>     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFC53982D2F: (caller: 00007FFC5398432C) Exception(2) tid(1d60) 80073CF1 Package was not found.
> 2024-06-08 19:48:16.419 [CLI ] MSIX installer failed: 2148204809
> 2024-06-08 19:47:09.981 [CORE] Deployment operation #0: error 0x800B0109: The root certificate of the signature in the app package or bundle must be trusted.
> 2024-06-08 19:47:09.981 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!54F3E94A: (caller: 54EA97A7) Exception(1) tid(1a20) 800B0109 A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
> 2024-06-08 19:47:10.165 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!54F3D7AF: (caller: 54F3ED72) Exception(2) tid(1a20) 80073CF1 Package was not found.
> 2024-06-08 19:47:10.165 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(126)\WindowsPackageManager.dll!54F3EA29: (caller: 54F3FBF8) LogHr(1) tid(1a20) 80073CF1 Package was not found.
>     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!54F3D7AF: (caller: 54F3ED72) Exception(2) tid(1a20) 80073CF1 Package was not found.
> 2024-06-08 19:47:10.336 [CLI ] MSIX installer failed: 2148204809

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

Automated error analysis suggests  may mean 

(Automated response - build 884.)

**Comment by SpecterShell** [comment]
Weird. Just tried the manifests and everything works fine.

image

**Comment by stephengillie** [comment]
> Weird. Just tried the manifests and everything works fine.

It validates successfully in my VM too. I don't know much about this check, as it doesn't occur frequently.

**Review by stephengillie — DISMISSED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/pull/162339#issuecomment-2221531127

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM. I've asked for more details about the certificate error, but these details haven't been forthcoming.

**Pull request closed without merging**
