### PR TITLE
New package: Oscillicious.RocketBroadcaster.Free version 1.4.0

### LINKED ISSUE #185879: [Package Request]: Rocket Broadcaster Free Edition
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.rocketbroadcaster.com/download
Publisher: Radio Mast, Inc.
Package Name: Rocket Broadcaster
Description: The Streaming Audio Encoder
Package Version: 1.4.0
Installer Url: https://www.oscillicious.com/rocketbroadcaster/free/rocketbroadcaster_setup.exe

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #185879

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

## Manual validation

> [!NOTE]
>
> This package requires a "broadcast server" to run properly. I have no idea how to test it.

Image
Image

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/185976)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Dragon1573** [comment]
> Please verify the manifest file is compliant with the package manager [1.6 manifest specification](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0).
> 
> Template: msftbot/validationError/manifest/content

It's confused. 😕

Verified that my manifests are valid.

```text
12:03:24 D:\...\winget-pkgs  [pr/Dragon1573/185976 ≡] 41ms pwsh> winget validate .\manifests\r\Oscillicious\RocketBroadcaster\Free\1.4.0\
清单验证成功。
```

**Comment by denelon** [comment]
@Dragon1573, you can click into the pipeline run, and sometimes the error is visible as in this case:

https://dev.azure.com/shine-oss/winget-pkgs/_build/results?buildId=18997&view=logs&j=dc5484e7-078c-5e69-1cbb-0f132d85a80e&t=0ff99015-932f-506f-8afc-34c2cd60b3e2&l=70

The "publisher" portion of the identifier starts with an "O" and the directory path in the PR is "r".

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
[Policy] Needs-Manual-Merge

**Comment by stephengillie** [comment]
Verify:
image
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
