### PR TITLE
New version: Jackett.Jackett version 0.21.1956

### PR DESCRIPTION
**Pull request by ilike2burnthing**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/142685)

### CODE REVIEW

**Review by russellbanks — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @ilike2burnthing,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 861.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-05 22:04:24.789 [FAIL] Installer failed security check. Url: https://github.com/Jackett/Jackett/releases/download/v0.21.1956/Jackett.Installer.Windows.exe Result: 0x80004005

(Automated response - build 861.)

**Comment by ilike2burnthing** [comment]
Reeeeeally wish you could get rid of that Defender check, seems to cause more problems than it solves.

**Comment by ilike2burnthing** [comment]
Seems like this one got lost and forgotten about. Closing as it's an old build.

**Pull request closed without merging**
