### PR TITLE
New version: Microsoft.OneDrive version 21.230.1107.0004

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/36864)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Can someone tell us the error code?
/update fixed error `2147749059`
`2147747474` means there is a newer version installed.

**Review by ItzLevvie — DISMISSED** [review]

**Comment by OfficialEsco** [comment]
@ryfu-msft would be fantastic if you could manually validate this one aaaand explain the reason why it fails

**Comment by OfficialEsco** [comment]
Not sure why i thought a newer version got merged.. anyways added ExpectedReturnCodes

**Comment by OfficialEsco** [comment]
@ryfu-msft @palenshus please (=

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
