### PR TITLE
New package: NASSe.K.HashMich version 1.0.0

### PR DESCRIPTION
**Pull request by manfred-mueller**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/192644)

### CODE REVIEW

**Review by mdanish-kh — CHANGES_REQUESTED** [review]
`.` is used as the delimiter to split directories. WinGet PackageIds are generally in the form `Publisher.Package` which imply a directory structure in the repository as `manifests/p/Publisher/Package/`. Since you have a `.` in the publisher name, the directory structure is looking like `manifests/n/NASSe/K/HashMich` which isn't a conventional directory structure.

Would you be willing to change it to something like `NASSeK.HashMich` which would mean restructuring the directory as `manifests/n/NASSeK/HashMich/<all yaml files>` files

If you do, you'll need to rename each Yaml file to the new PackageId and change the `PackageIdentifier:` field in each manifest file

**Comment by manfred-mueller** [comment]
> Would you be willing to change it to something like `NASSeK.HashMich` which would mean restructuring the directory as `manifests/n/NASSeK/HashMich/<all yaml files>` files

Yes, of course and the change makes sense, I would prefer to choose NASS only then.

How would I update the following winget packages then?:
NASSe.K.AvUpload
NASSe.K.DHLabel
NASSe.K.FBReconnect
NASSe.K.KeepRunning
NASSe.K.PrintButton
NASSe.K.ShowDesktop
NASSe.K.W3Devices
NASSe.K.ado
NASSe.K.mkWritable

Thanks for your work and best regards.

**Comment by Trenly** [comment]
@mdanish-kh - Since there's already several similar packages, I think the non-conventional structure is fine here

**Comment by manfred-mueller** [comment]
@trenly
would it be okay resubmitting the manifests with publisher NASS instead of NASSe.K., or would this create too much additional efforts for the maintainers like you? As it was my mistake, I'm eager to fix it for the future. Sorry that I didn't think about the dotts. I should have known, as I'm working in the IT...

**Comment by mdanish-kh** [comment]
Looks like I forgot to get back to you here. I didn't realize there were a number of existing packages using the same structure. I agree with @Trenly that we can let this PR in for that reason.


> would it be okay resubmitting the manifests with publisher NASS instead of NASSe.K., or would this create too much additional efforts for the maintainers like you? As it was my mistake, I'm eager to fix it for the future. Sorry that I didn't think about the dotts. I should have known, as I'm working in the IT...

No worries. If you're determined to go with more conventional IDs, [YamlCreate.ps1](https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1) offers a friendly way to move packages. You can run the script by cloning this repo, and running `./Tools/YamlCreate.ps1` from the root directory. The main menu would offer some options for you to choose from. Entering `6` would take you to `Move package to a new identifier` flow where you can enter the existing PackageId & the new desired PackageID and it'll automatically create removal & addition PRs for you in the repository.

To avoid filling the repo with lots of PRs at once (although I checked and those PackageId contain at most 2-3 versions), I would suggest going one PackageId at a time and move to the next when PRs for one PackageID have been approved & merged


[Policy] reset feedback

**Comment by mdanish-kh** [comment]
cc @manfred-mueller as I forgot to tag you above

**Review by mdanish-kh — APPROVED** [review]

**Pull request merged**
