### PR TITLE
Remove: Canonical.Ubuntu.1604 version 1604.2019.523.0

### PR DESCRIPTION
**Pull request by jibel**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/159600)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://wsldownload.azureedge.net/Ubuntu_1604.2019.523.0_x64.appx 
OK

(Automated message - build 910)

**Comment by stephengillie** [comment]
Why should this be removed?

**Comment by jibel** [comment]
Hi @stephengillie,

Ubuntu WSL 16.04 reached end of standard support and we stopped maintaining it. 
The official versions of Ubuntu WSL we support are those published on the MS Store and listed there https://github.com/microsoft/WSL/blob/master/distributions/DistributionInfo.json

Thanks,

PS: I'm the [upstream maintainer of Ubuntu WSL at Canonical](https://launchpad.net/~ubuntu-wsl-dev/+members).

**Comment by stephengillie** [comment]
URL: https://wsldownload.azureedge.net/Ubuntu_1604.2019.523.0_x64.appx 
Status Code: 200

(Automated message - build 886)

**Comment by stephengillie** [comment]
URL: https://wsldownload.azureedge.net/Ubuntu_1604.2019.523.0_x64.appx 
Status Code: 200

(Automated message - build 886)

**Comment by stephengillie** [comment]
Hi @jibel,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 886.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
