### PR TITLE
New package: DevToys 2.0.1

### PR DESCRIPTION
**Pull request by veler**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

Keeping this PR as a draft as the links in the manifest are not available yet (GitHub Release is drafted, not publicly released yet), meaning I can't run the command line to validate the manifest for now.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/156567)

### CODE REVIEW

**Comment by stephengillie** [comment]
Verify:
image
image
image

Hi @veler,

The `PackageVersion` usually should match what's reported by the application, and if this is different from Registry (shown by Apps and features) then the Registry data should be added as a `DisplayVersion`. Should this be done here, since the application has the `.1` before the `-preview`, but the Registry has it after?

**Comment by veler** [comment]
Hi @stephengillie, thanks for your feedback and pointing this out.
I updated the installer to reflect the right version number, and therefore updated the PR as the hash changed. 
Thank you very much!

image

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-06-11 06:57:06.182 [FAIL] Installer failed security check. Url: https://github.com/DevToys-app/DevToys/releases/download/v2.0.1.0/devtoys_win_x64.exe Result: 0x80004005

(Automated response - build 884.)

**Comment by veler** [comment]
> Manual Validation ended with:
> 
> > 2024-06-11 06:57:06.182 [FAIL] Installer failed security check. Url: https://github.com/DevToys-app/DevToys/releases/download/v2.0.1.0/devtoys_win_x64.exe Result: 0x80004005
> 
> (Automated response - build 884.)

That is odd. I just installed the app manually on my machine by downloading the GitHub release and it installed without issue. Can you please elaborate on what happened / what you did?

Thanks

**Comment by stephengillie** [comment]
Hi @veler,

That was the scripted response when one of my VMs gets a Defender error. In this case, it was signature/definition version `1.411.160.0`. 

[DevToys-app.DevToys.2.0.1.log](https://github.com/user-attachments/files/15792646/DevToys-app.DevToys.2.0.1.log)

It's probably a false positive, and we can rescan tomorrow.

**Comment by veler** [comment]
> Hi @veler,
> 
> That was the scripted response when one of my VMs gets a Defender error. In this case, it was signature/definition version `1.411.160.0`.
> 
> [DevToys-app.DevToys.2.0.1.log](https://github.com/user-attachments/files/15792646/DevToys-app.DevToys.2.0.1.log)
> 
> It's probably a false positive, and we can rescan tomorrow.

Thank you! Yes, can we please run the validation again (whenever possible, tomorrow is fine) ?
There literally nothing that changed compared to before except the string of the version number.

**Comment by stephengillie** [comment]
Verify:
image
image

**Review by stephengillie — APPROVED** [review]

**Comment by masterflitzer** [comment]
something with the version doesn't seem to be right, it says `2.0-preview.1` is installed, but keeps offering me `2.0.1`, so i'm basically in an infinite update loop

it seems to ignore the `-preview` part of the version (the winget-pkgs path also doesn't have it: <https://github.com/microsoft/winget-pkgs/tree/master/manifests/d/DevToys-app/DevToys/2.0.1>)

the command i'm using is `winget source update && winget upgrade -r`
console output:
```
❯ winget source update && winget upgrade -r
Updating all sources...
Updating source: winget...
Done
Name                                  Id                  Version       Available
---------------------------------------------------------------------------------
DevToys Preview version 2.0-preview.1 DevToys-app.DevToys 2.0-preview.1 2.0.1
1 upgrades available.
6 package(s) have pins that prevent upgrade. Use the 'winget pin' command to view and edit pins. Using the --include-pinned argument may show more results.

(1/1) Found DevToys [DevToys-app.DevToys] Version 2.0.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/DevToys-app/DevToys/releases/download/v2.0.1.0/devtoys_win_x64.exe
  ██████████████████████████████  55.5 MB / 55.5 MB
Successfully verified installer hash
Starting package install...
Successfully installed

29 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.

~ took 42s
❯ winget source update && winget upgrade
Updating all sources...
Updating source: winget...
Done
Name                                  Id                  Version       Available
---------------------------------------------------------------------------------
DevToys Preview version 2.0-preview.1 DevToys-app.DevToys 2.0-preview.1 2.0.1
1 upgrades available.
6 package(s) have pins that prevent upgrade. Use the 'winget pin' command to view and edit pins. Using the --include-pinned argument may show more results.

~ took 2s
❯
```

**Pull request merged**
