### PR TITLE
New version: Microsoft.GitCredentialManagerCore version 2.0.605.12951

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/37432)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Hi there @ldennington, It doesn't look like your automation worked as expected? https://github.com/microsoft/winget-pkgs/pull/30205#issuecomment-943571175

**Comment by ldennington** [comment]
> 

We actually ended up removing this workflow from our repository, so I'm very curious as to how this was triggered. Investigating.

**Comment by OfficialEsco** [comment]
> We actually ended up removing this workflow from our repository, so I'm very curious as to how this was triggered. Investigating.

Nono this is my PR 😁, i just noticed there was a update 23 days ago that wasn't in the repo, if you want we can take care of the updating until we see you guys doing it again?

**Comment by ldennington** [comment]
> > We actually ended up removing this workflow from our repository, so I'm very curious as to how this was triggered. Investigating.
> 
> Nono this is my PR 😁, i just noticed there was a update 23 days ago that wasn't in the repo, if you want we can take care of the updating until we see you guys doing it again?

Ah got it! We actually decided to stop deploying to winget since we really want Windows users to be using the bundled installer that ships with Git For Windows instead. So the lack of updates was on purpose.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
