### PR TITLE
New version: Mozilla.Thunderbird version 115.0.1

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/115186&drop=dogfoodAlpha

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
Url's should have spaces replaced with `%20`

**Comment by stephengillie** [comment]
>  Manifest Error: Duplicate installer entry found.

**Comment by stephengillie** [comment]
@vedantmgoyal2009,

It looks like this package is supposed to have numerous localization installers, but only the English installers are used.

**Pull request closed without merging**
