### PR TITLE
Submitting Winamp version 5.90.0.9999

### PR DESCRIPTION
**Pull request by djegg**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/79952)

### CODE REVIEW

**Comment by djegg** [comment]
Hello.

The /S silent switch works ok for us.

Please could you be more specific?

At what point is it failing exactly?

Is it the UAC prompt?
Or is it a MessageBox for a missing dependency?
And if the latter, what Windows OS and which dependency?
e.g. VS2019/VC142 redist prompt on Win7/8/8.1

**Comment by ItzLevvie** [comment]
It brings up a MessageBox about a dependency on a clean installation of Windows:
image
image

Also, could you please ask your WinAmp development team to remove the trailing spaces from the `DisplayVersion`?

WinAmp currently shows the `DisplayVersion` as `5.90 ` where there's a random space after `5.90` instead of just `5.90` without the space after `5.90`.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
See https://github.com/microsoft/winget-pkgs/pull/79952#issuecomment-1250428312

**Comment by djegg** [comment]
The requested changes have been made.

**Comment by djegg** [comment]
Hello. Again, please could you be more specific?
Which installer URL doesn't appear to be valid?

**Comment by djegg** [comment]
Meanwhile, the current version of Winamp on Winget (Winamp 5.8 Beta, not stable) was submitted by someone who is not an official employee or representative of the company, and was committed under the wrong publisher.

https://github.com/microsoft/winget-pkgs/commit/700584071c89aa262db41595436f9053364b3206

https://winget.run/pkg/Radionomy/Winamp

Radionomy is not the publisher for Winamp

Though note how the InstallerUrl is also download.nullsoft.com

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
For the https://github.com/microsoft/winget-pkgs/labels/Validation-Domain label - please wait for an engineer to take a look.

Also, could you please move to the multi-file format and utilize schema version 1.2.0? because the singleton format is now deprecated and a lot packages that are still using the singleton format are being moved to the multi-file format.

You can take a look at the following guides to move the package to the multi-file format or you can use [winget-create](https://github.com/microsoft/winget-create) to regenerate your manifest to the latest schema version and multi-file format:
1) https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.2.0/installer.md
2) https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.2.0/defaultLocale.md
3) https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.2.0/version.md

--------------------------------------------

**EDIT**: Also I just installed the newer version and it still looks like there's a space after `5.90`.

`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Winamp`:
--> `DisplayVersion` = `5.90 `

image

^ The blue is the trailing space

Running `reg add HKLM\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\Winamp /v DisplayVersion /d "5.90" /f` in Command Prompt fixes this issue.

image

**Comment by djegg** [comment]
Oh! You didn't specify before that it was the DisplayVersion in the Uninstall string in the Registry.

That means I'll need to hunt down and edit the relevant .nsh file, switch back to the 5.9.0Final branch, rebuild the installer, recalculate the hash, edit and push the manifest  again...

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
