### PR TITLE
New version: SomePythonThings.WingetUIStore version 1.7.1

### PR DESCRIPTION
**Pull request by marticliment**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/103963)

### CODE REVIEW

**Review by russellbanks — DISMISSED** [review]

**Comment by marticliment** [comment]
This installer does not require administrator rights, but if it detects a missing vcredist15-22 install, it launches the vcredist installer, which while being in /unattended, shows a UAC prompt. 

Could this be the issue?

**Comment by stephengillie** [comment]
UAC prompts should be disabled. This may cause other issues, but wouldn't block the installer.

**Review by ItzLevvie — DISMISSED** [review]

**Comment by marticliment** [comment]
is there any way I can recreate the testing environment so I can see what is wrong with the installer?

**Comment by stephengillie** [comment]
> is there any way I can recreate the testing environment so I can see what is wrong with the installer?

Yes - validations use fresh installs of base Windows 10 or 11, and x86 programs are validated on a 32-bit version. The automated and manual pipelines are slightly different, which is why some packages may pass one and fail another. The errors above are happening on Windows 10, while manual validation with Windows 11 passes.

**Comment by marticliment** [comment]
On a stock W10 VM machine the installer installs fine for me. I can't find any way to recreate the issue.

And the pipelines don't give anyclue regarding the issue:
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
