### PR TITLE
Add Schema Header

### PR DESCRIPTION
**Pull request by Trenly**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/83863)

### CODE REVIEW

**Comment by Trenly** [comment]
> 2022-10-14 20:52:13.502 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(49)\WindowsPackageManager.dll!00007FFD266501D2: (caller: 00007FFD26650F29) Exception(4) tid(1058) 80072EFD     Msg:[InternetOpenUrl() failed.]

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
Bump

**Pull request merged**
