### PR TITLE
New package: Gyroflow.Gyroflow version 1.6.0

### PR DESCRIPTION
**Pull request by jo-chemla**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/190807)

### CODE REVIEW

**Comment by Trenly** [comment]
This is blocked until 1.9 Manifests are supported in the pipelines.

[Policy] Zip Binary

**Review by ItzLevvie — APPROVED** [review]

**Comment by jo-chemla** [comment]
Thanks for approving the changes @ItzLevvie ! It seems that the bot added the `Moderator-Approved` tag but that a review is still required.

**Comment by Trenly** [comment]
@jo-chemla - Support for zipped binaries has now been added and is available in the pipelines. This will require you to update your submission to ManifestVersion: 1.9.0 and set ArchiveBinariesDependOnPath: true in the installer node. To keep things clean, this PR is being closed. Please submit a new PR for the latest version of this package. Thank you for your contributions!

**Comment by jo-chemla** [comment]
New package submitted here: https://github.com/microsoft/winget-pkgs/pull/197203 with `ArchiveBinariesDependOnPath: true`

**Pull request closed without merging**
