### PR TITLE
New version: GoLang.Go version 1.21.0

### PR DESCRIPTION
**Pull request by staticfrost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/116072&drop=dogfoodAlpha

### CODE REVIEW

**Comment by CoolPlayLin** [comment]
This PR is duplicate of #115760

**Comment by staticfrost** [comment]
The error states:
"Error information: RequestContainsTooManyFlaggedFiles".

This has how many flags are in 1.20.7 that recently got approved, unsure what has changed between that update last week and this one.

**Comment by stephengillie** [comment]
> The error states: "Error information: RequestContainsTooManyFlaggedFiles".
> 
> This has how many flags are in 1.20.7 that recently got approved, unsure what has changed between that update last week and this one.

The previous one may have been approved in error. This is not an error that I can waiver around.

**Comment by stephengillie** [comment]
> This PR is duplicate of #115760

Feel free to close this PR, or let me know and I'd be happy to do so.

**Comment by staticfrost** [comment]
@stephengillie, has there been a change to how many binaries the winget package can handle? 
The Go team distribute three binaries for Windows, AMD64bit, AMD32bit and ARM. The check appears to be stop since we're including the three binaries.

**Review by stephengillie — APPROVED** [review]

**Comment by staticfrost** [comment]
@stephengillie, slight issue I had been trying to troubleshoot the error message for RequestContainsTooManyFlaggedFiles and my last commit only had the 64bit binary included not the 32bit and ARM binaries.

**Comment by stephengillie** [comment]
> @stephengillie, slight issue I had been trying to troubleshoot the error message for RequestContainsTooManyFlaggedFiles and my last commit only had the 64bit binary included not the 32bit and ARM binaries.

Hi @staticfrost,

Oh - the `RequestContainsTooManyFlaggedFiles` means too many of the files were flagged by Defender or another scan we perform. If one of the other packages were blocked by this error, then skipping it for this version might not be a bad idea.

**Pull request merged**
