### PR TITLE
Add jj-vcs.jj, a new publisher for martinvonz.jj

### PR DESCRIPTION
**Pull request by RoscoP**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/202513)

### CODE REVIEW

**Comment by RoscoP** [comment]
Will follow up with another PR updating the metadata for martinvonz.jj

**Comment by stephengillie** [comment]
Is this package moving? Or will there be duplicates going forward?

**Comment by RoscoP** [comment]
The package is moving, from what I was reading in the FAQ, I thought you create two entries (one for new/old publisher), and figured it would be okay for the same version, to help the transition.  What is the correct way forward?
1. wait until new version with new publisher and add that
2. have same version with the two publishers (what this PR does)
3. something else?

**Comment by stephengillie** [comment]
> The package is moving

Oh, thanks for informing.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
