### PR TITLE
NumeRe.NumeRe version 1.1.4.2203

### PR DESCRIPTION
**Pull request by numeredev**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/54448)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by numeredev** [comment]
Hi @ItzLevvie, what's up with the pipeline? Why does it take so much time? Or is that a question for @denelon ?

**Comment by ItzLevvie** [comment]
> Hi @ItzLevvie, what's up with the pipeline? Why does it take so much time? Or is that a question for @denelon ?

Azure Pipelines are currently limited to 20 PRs per run due to 800+ PRs being opened so it'll probably take a while for it to run on this PR.

**Comment by numeredev** [comment]
> > Hi @ItzLevvie, what's up with the pipeline? Why does it take so much time? Or is that a question for @denelon ?
> 
> Azure Pipelines are currently limited to 20 PRs per run due to 800+ PRs being opened so it'll probably take a while for it to run on this PR.

Thank you for this information. That's somehow what I assumed to be the reason.

**Comment by ItzLevvie** [comment]
A PSA has now been posted: https://github.com/microsoft/winget-pkgs/issues/54601

**Comment by numeredev** [comment]
Hi @ItzLevvie!
I'm not expected to do something here, am I? I'll just wait until the pipeline issues are resolved.

**Comment by denelon** [comment]
@numeredev we're working on it. You shouldn't have to do anything. After we get the underlying infrastructure issues resolved and our scaling mechanisms in place this shouldn't happen again. The "on-call" staff will manually trigger restarts for any of the failed builds.

**Review by ghost — APPROVED** [review]

**Pull request merged**
