### PR TITLE
Version Update: TeamSonarr.Sonarr version 4.0.3.1413

### PR DESCRIPTION
**Pull request by babblebauble**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/147205)

### CODE REVIEW

**Comment by babblebauble** [comment]
The usual error of overlapping DisplayVersion.

> Manifest Error: DisplayVersion declared in the manifest has overlap with existing DisplayVersion range in the index. Existing DisplayVersion range in index:  [ [4.0, 4.0]]

**Review by Trenly — CHANGES_REQUESTED** [review]
DisplayVerison should be `"4"` not `"4.0"`

**Comment by babblebauble** [comment]
Same error as before. The only manifest in the repo with an overlapping DisplayVersion is version 4.0.2.1183 which this PR is also deleting. Not sure why this same error keeps happening every time.

>Manifest Error: DisplayVersion declared in the manifest has overlap with existing DisplayVersion range in the index. Existing DisplayVersion range in index:  [ [4.0, 4.0]]

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-04-01T13:16:46.7333629Z ##[error]Manifest Validation Failed
 2024-04-01T13:16:51.7895759Z ##[section]Finishing: Validate Manifest

(Automated response - build 876.)

**Pull request closed without merging**
