### PR TITLE
Remove: TechSmith.Snagit.2024 version 24.2.2.3491

### PR DESCRIPTION
**Pull request by SpecterShell**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/170735)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://download.techsmith.com/snagit/releases/2422/snagit.exe 
OK

(Automated message - build 919)

**Comment by stephengillie** [comment]
Hi @SpecterShell,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 892.)

**Comment by SpecterShell** [comment]
The manifests are being moved to a shorter version (24.2.2) which already exist, so I have to remove these manifests and do the modifications on the shorter versions directly.

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Sorry to have to re-approve these, but I can't find another way to get them to merge.

**Pull request merged**
