### PR TITLE
New version: tailscale.tailscale version 1.40.0

### PR DESCRIPTION
**Pull request by LeaderbotX400**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/103804)

### CODE REVIEW

**Comment by LeaderbotX400** [comment]
@microsoft-github-policy-service agree

**Comment by LeaderbotX400** [comment]
After a second round of manual validation, installation works correctly.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335226 
> 2023-04-28 13:17:19.602 [CLI ] ShellExecute installer failed: 1603

**Comment by stephengillie** [comment]
I'm not seeing the cause for this error. It installed normally on a Windows 11 VM.

**Comment by ItzLevvie** [comment]
Close with reason: Merge conflicts;

**Pull request closed without merging**
