### PR TITLE
Fix PackageVersion for PowerShell Preview 7.3.0.8

### PR DESCRIPTION
**Pull request by mdanish-kh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/99812)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/99812)

### CODE REVIEW

**Review by anamnavi — DISMISSED** [review]
LGTM

**Comment by stephengillie** [comment]
Similar to the others, x86 Manual Validation failed with:
> @PowerShell7.3.0-preview.8 Fatalerror.0xC0000005 atSystem.Management.Automation.Security.SystemPolicy+WldpNativeMethods.WldpCanExecuteFile(System.Guid,WLDP_EXECUTION_EVALUATION_OPTIONS,IntPtr,System.String,WLDP_EXECUTION_POLICYByRef) atSystem.Management.Automation.Security.SystemPolicy.GetFilePolicyEnforcement(System.String,System.IO.FileStream) atSystem.Management.Automation.ExternalScriptInfo.ReadScriptContents() atSystem.Management.Automation.ExternalScriptInfo.get_ScriptBlock() atMicrosoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifestData(System.Management.Automation.ExternalScriptInfo,System.String[],ManifestProcessingFlags,BooleanByRef) atMicrosoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifestData(System.Management.Automation.ExternalScriptInfo,ManifestProcessingFlags,System.Collections.HashtableByRef,System.Collections.HashtableByRef,BooleanByRef) atMicrosoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(System.Management.Automation.PSModuleInfo,System.String,System.String,System.String,System.Management.Automation.SessionState,System.Object,ImportModuleOptionsByRef,ManifestProcessingFlags,BooleanByRef,BooleanByRef) atMicrosoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(System.Management.Automation.PSModuleInfo,System.String,System.String,System.String,System.String,System.String,System.Management.Automation.SessionState,ImportModuleOptions,ManifestProcessingFlags,BooleanByRef,BooleanByRef) atMicrosoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(System.Management.Automation.PSModuleInfo,System.Collections.Generic.IEnumerable`1<System.String>,System.String,System.Management.Automation.SessionState,ImportModuleOptions,ManifestProcessingFlags,System.Management.Automation.PSModuleInfoByRef) atMicrosoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions,System.String) atMicrosoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions,System.String) atMicrosoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord() atSystem.Management.Automation.Cmdlet.DoProcessRecord() atSystem.Management.Automation.CommandProcessor.ProcessRecord() atSystem.Management.Automation.CommandProcessorBase.DoExecute() atSystem.Management.Automation.Internal.PipelineProcessor.Inject(System.Object,Boolean) atSystem.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object) atSystem.Management.Automation.Runspaces.LocalPipeline.InvokeHelper() atSystem.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc() atSystem.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProcImpersonate() atSystem.Management.Automation.Runspaces.PipelineThread.WorkerProc() atSystem.Threading.Thread+StartHelper.Callback(System.Object) atSystem.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext,System.Threading.ContextCallback,System.Object) atSystem.Threading.Thread.StartCallback() ,

**Comment by mdanish-kh** [comment]
> Similar to the others, x86 Manual Validation failed with:

The installer is the same (the same SHA256 hash) which previously passed the pipelines and got merged into the repo in PR https://github.com/microsoft/winget-pkgs/pull/80446, so I don't know what's different now 👀 

https://github.com/microsoft/winget-pkgs/blob/59ff4098692ee6d31421854e1fe0ebfb4322742f/manifests/m/Microsoft/PowerShell/Preview/7.3.8.0/Microsoft.PowerShell.Preview.installer.yaml#L29

**Review by ItzLevvie — DISMISSED** [review]

**Comment by anamnavi** [comment]
@stephengillie could you share the command you used to install/run the x86 msi that generated the error you mentioned? I'm not able to repro on my end.

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/pull/99813#issuecomment-1523933144

**Comment by stephengillie** [comment]
Here's a recent run log: [Microsoft.PowerShell.Preview.7.3.0.8.x86.log](https://github.com/microsoft/winget-pkgs/files/11337789/Microsoft.PowerShell.Preview.7.3.0.8.x86.log)

I began to wonder if this was caused by having a newer version of PowerShell installed here. But then I'd expect the `x64` to have the same error.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
