### PR TITLE
Add OmniMIDI 14.8.5.0

### PR DESCRIPTION
**Pull request by gdm257**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/163905)

### CODE REVIEW

**Comment by gdm257** [comment]
Although the package is innosetup installer, parameters `/VERYSILENT` `/SILENT` are not fully effective.

There is always a popup window to prompt success message in the end.

**Comment by DuckDuckStudio** [comment]
> Although the package is innosetup installer, parameters `/VERYSILENT` `/SILENT` are not fully effective.
> 
> There is always a popup window to prompt success message in the end.

Try `/verysilent` `/suppressmsgboxes` ?

**Comment by stephengillie** [comment]
Sadly, sometimes a developer doesn't add a silent install option, or doesn't ensure it's fully silent.

**Comment by gdm257** [comment]
> @gdm257 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-07-31 17:15:15.448   Function name: idpReportError

(Automated response - build 887.)

**Comment by gdm257** [comment]
> Automatic Validation ended with:
> 
> > 2024-07-31 17:15:15.448   Function name: idpReportError
> 
> (Automated response - build 887.)
> 
> Edit: image
> 
> Hi @gdm257,
> 
> Is there an installer switch to bypass this Information box?

Hi @stephengillie,

Unfortunately, there is no switch available to bypass the information box for this installer. The `/VERYSILENT`, `/SILENT`, and `/SUPPRESSMSGBOXES` options are not effective in this case.

**Pull request closed without merging**
