### PR TITLE
New version: PurpleI2P.i2pd version 2.50.2

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/133022)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification.
>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by Exorcism0666** [comment]
I don't know what's wrong
image

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-06 18:56:22.679 [FAIL] Installer failed security check. Url: https://github.com/PurpleI2P/i2pd/releases/download/2.50.2/setup_i2pd_v2.50.2.exe Result: 0x80004005

(Automated response - build 530.)

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 530.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
