### PR TITLE
Add Hey v1.0.3.0

### PR DESCRIPTION
**Pull request by colinrubbert**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1957)

### CODE REVIEW

**Comment by colinrubbert** [comment]
I don't see any comments on what exactly is won't with this PR. 

It passed validations locally and when it ran through the Azure pipeline via GitHub.

Could I have more clarity?

**Comment by KevinLaMS** [comment]
Hmm.  Seems like sometimes my comments get lost.  Sorry about that.  I suspect the URL has changed.  This is what we get now.
image

**Comment by colinrubbert** [comment]
@KevinLaMS Thanks for getting back to me. I will take a look at this early next week and see if I can get it fixed and resubmit. I'm sure the version got updated and probably changed the URL.

**Comment by KevinLaMS** [comment]
Thanks.

**Pull request closed without merging**
