### PR TITLE
Adobe.AdobeDigitalEditions version 4.5.11

### PR DESCRIPTION
**Pull request by NathanBnm**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/36002)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
I'm stuck here:
image

Are there any switches to suppress this prompt so it can install fully unattended without requiring any user interaction?

When I click the **No, Thank You** button, I get 1223 as exit code, which seems like a success code, so you can add that to `InstallerSuccessCodes`.
image

**Comment by NathanBnm** [comment]
Curiously I don't have such a popup. I'll check the installer options but I will not be able to test the effect.

Regarding the exit code apparently it's a know issue (See https://community.adobe.com/t5/digital-editions-discussions/adobe-digital-editions-exit-code-1223-upon-successful-install/td-p/9560528) but the installations proceeds without any issues so I think it can be added to succes codes as a workaround (anyway Adobe will probably not update this software before a while.)

**Comment by NathanBnm** [comment]
Just made the changes. Let me know if install is still not silent.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
I'm still seeing the same issue:
image

You could try and play around with the switches, or contact Adobe to see if there's any way to suppress this prompt.

I'm using Windows Sandbox to test the PR.

**Comment by NathanBnm** [comment]
@ItzLevvie after looking for a solution I found [this](https://community.adobe.com/t5/digital-editions-discussions/adobe-digital-editions-4-5-silent-install/m-p/7616109). Apparently this pop up is appearing if the installer detects that there is no installed antivirus software by checking a registry value.

The only way to remove the pop up is to fake the installer by adding a registry key before the installation but this could maybe have unwanted side effects.

Any idea?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> The only way to remove the pop up is to fake the installer by adding a registry key before the installation but this could maybe have unwanted side effects.

WinGet doesn't allow scripts to be used during install and there's no support for it in WinGet.

There used to be a Adobe Digital Editions package in this repository before, but I ran into issues with installing it, more specifically the NSS=0 switch didn't work on Windows Sandbox.

It was in the repository before because old manifests were tested on bare-metal hardware before automation came into effect, so now it uses Virtual Machines which has built-in Microsoft Defender and a few other AV software (which is possibly executed through an API - not VirusTotal though).

I removed it because you'll run into prompt issues on a clean install of Windows, so if you're wanting to install 30+ software from WinGet, the prompt blocks the entire install until user interaction is needed.

**Pull request closed without merging**
