### PR TITLE
Remove version: Principle.Lusun version 2.2.8

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164180)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://releases.lusun.com/lusun-2.2.8-win-x64.exe 
Response Error: The remote server returned an error: (403) Forbidden.

(Automated message - build 912)

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 887.)

**Comment by stephengillie** [comment]
URL: https://releases.lusun.com/lusun-2.2.8-win-x64.exe 
Response status code does not indicate success: 403 (Forbidden).

(Automated message - build 887)

**Comment by Exorcism0666** [comment]
## For moderators or/and anyone else

>[!Caution]
As a result of several personal problems I've had over the last few months + my final exams coming up very soon, I'm currently unable to look at my GitHub notifications every day and maintain my executions correctly.
If you detect a certain problem on a certain pul request:
- Either you can close the pull request directly without mentioning me.
- Or you can send me a message on X (Twitter): @Exorcism0666

Thank you for your understanding, and I'm sorry if some pull requests can't be approved due to the situation I'm in.

----------------
This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by Dragon1573** [comment]
> [!IMPORTANT]
>
> This package should NOT be removed! The installer URL is still valid.
>
> ```text
> 21:44:38 D:\...\winget-pkgs  [master ≡] 1ms pwsh> winget download -e Principle.Lusun -v 2.2.8
> 已找到 芦笋 [Principle.Lusun] 版本 2.2.8
> 此应用程序由其所有者授权给你。
> Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
> 正在下载 https://releases.lusun.com/lusun-2.2.8-win-x64.exe
>   ██████████████████████████████  79.9 MB / 79.9 MB
> 已成功验证安装程序哈希
> 已下载安装程序: D:\Download\Aria2\Principle.Lusun_2.2.8\芦笋_2.2.8_Machine_X64_nullsoft_zh-CN.exe
> 21:45:12 D:\...\winget-pkgs  [master ≡] 13.864s pwsh>
> ```

**Comment by stephengillie** [comment]
URL: https://releases.lusun.com/lusun-2.2.8-win-x64.exe 
Response status code does not indicate success: 403 (Forbidden).

(Automated message - build 887)

**Comment by Dragon1573** [comment]
> Response status code does not indicate success: 403 (Forbidden).

Is it related to request headers? Does the server (provided by _Tengine_) block `winget.exe` by detecting it's specific headers?

**Comment by Dragon1573** [comment]
> ### 403 Forbidden
>
> You don't have permission to access the URL on this server.
>
> **Denied by region_block**

Enable "global mode" of my _Clash for Windows_ and switch to a Singapore proxy node. Issue successfully reproduced.

image

It seems requests from China (including Mainland, Hongkong SAR., Macau SAR. and Taiwan Province) are only permitted to access the _Tengine_ server.

**Comment by stephengillie** [comment]
URL: https://releases.lusun.com/lusun-2.2.8-win-x64.exe 
Response status code does not indicate success: 403 (Forbidden).

(Automated message - build 887)

**Comment by stephengillie** [comment]
URL: https://releases.lusun.com/lusun-2.2.8-win-x64.exe 
Response status code does not indicate success: 403 (Forbidden).

(Automated message - build 887)

**Comment by stephengillie** [comment]
URL: https://releases.lusun.com/lusun-2.2.8-win-x64.exe 
Response status code does not indicate success: 403 (Forbidden).

(Automated message - build 887)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
