### PR TITLE
New package: AfreetSoftware.OmniRig version 1.20

### LINKED ISSUE #113446: [Package Request]: OmniRig
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### What's the type of your software?

exe

### Please provide the following information

Download Page Url: https://www.hb9ryz.ch/omnirig/index.html
Install Options: 
Publisher: HB9RYZ
Publisher Page: https://www.hb9ryz.ch
Package Page: https://www.hb9ryz.ch/omnirig/index.html
Package Name: OmniRig
Description: Freeware CAT engine for Ham Radio Transceiver/Receiver control.
Package Version: 2.1
Installer URL: https://www.hb9ryz.ch/downloads/install_omnirigv21.zip
License: Freeware
License Page: 
Copyright: Copyright 2023 by HB9RYZ

### PR DESCRIPTION
**Pull request by AsciiWolf**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

Closes #113446.
Replaces #115353.
 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/116523&drop=dogfoodAlpha

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Oops, I have made a typo in the version number. I will fix it.

**Comment by AsciiWolf** [comment]
Done.

**Comment by AsciiWolf** [comment]
The URL is valid.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
