### PR TITLE
PiriformSoftware.Speccy version 1.32.0.774

### PR DESCRIPTION
**Pull request by OyePradumya**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15041)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
This information is wrong.
image

**Comment by OyePradumya** [comment]
> This information is wrong.
> image

image
you are wrong

**Comment by OfficialEsco** [comment]
The Version inside the app does not match the ARP information.
You are ruining the manifest.

**Comment by OyePradumya** [comment]
> The Version inside the app does not match the ARP information.
> You are ruining the manifest.

the version is mentioned on the official site

**Comment by OfficialEsco** [comment]
> > The Version inside the app does not match the ARP information.
> > You are ruining the manifest.
> 
> the version is mentioned on the official site

WinGet does not look at the Version on the Official Site or inside the App.
Are you like trying to teach me how WinGet works?

**Comment by OyePradumya** [comment]
> > > The Version inside the app does not match the ARP information.
> > > You are ruining the manifest.
> > 
> > 
> > the version is mentioned on the official site
> 
> WinGet does not look at the Version on the Official Site or inside the App.
> Are you like trying to teach me how WinGet works without knowing how it works?

i know that .. i hav mentioned version number by myself

**Comment by OfficialEsco** [comment]
You do not know how WinGet works, please stop submitting PRs before you break more stuff.

**Comment by OyePradumya** [comment]
> You do not know how WinGet works, please stop submitting PRs before you break more stuff.
> Please educate your self on how to use GitHub and WinGet.

are you the developer of winget? what's your problem? i am reverting back the wrong pr and creating new PR with proper info

**Comment by OfficialEsco** [comment]
> > You do not know how WinGet works, please stop submitting PRs before you break more stuff.
> > Please educate your self on how to use GitHub and WinGet.
> 
> are you the developer of winget? what's your problem? i am reverting back the wrong pr and creating new PR with proper info

Ahh no i am just a Package Maintainer since day one with 800+ submissions.
My problem is that you are fucking up the Repo with your incorrect information.

**Comment by OyePradumya** [comment]
> > > You do not know how WinGet works, please stop submitting PRs before you break more stuff.
> > > Please educate your self on how to use GitHub and WinGet.
> > 
> > 
> > are you the developer of winget? what's your problem? i am reverting back the wrong pr and creating new PR with proper info
> 
> Ahh no i am just a Package Maintainer since day one with 800+ submissions.
> My problem is that you are fucking up the Repo with your incorrect information.

I am only creating PR with official info on the official site. You can't deny the info on official website

**Comment by OfficialEsco** [comment]
> I am only creating PR with official info on the official site. You can't deny the info on official website

As i've said earlier, the information on the website or inside the app DOES NOT MATTER, WinGet is INTEGRATED with Windows, WinGet gets its information from WINDOWS.

You DELETED the Manifest with the correct information WITHOUT knowledge of how WinGet WORKS.

**Comment by OyePradumya** [comment]
> > I am only creating PR with official info on the official site. You can't deny the info on official website
> 
> As i've said earlier, the information on the website or inside the app DOES NOT MATTER, WinGet is INTEGRATED with Windows, WinGet gets its information from WINDOWS.
> 
> You DELETED the Manifest with the correct information WITHOUT knowledge of how WinGet WORKS.

if you feel so then kindly ban me from creating new PRs 
✌

**Comment by OfficialEsco** [comment]
Ok genius, so its time to test your manifest.
Install Speccy 1.31 on a VM https://download.ccleaner.com/spsetup131.exe
Do `winget source update` then do `winget upgrade` do you see a upgrade? Nope.
Ahh do `winget list` on your own system, is the Speccy ID `PiriformSoftware.Speccy` instead of `Speccy`? No its not because the information is wrong.

**Pull request merged**
