### PR TITLE
Fix version mismatch for Python.Python.3

### PR DESCRIPTION
**Pull request by ghost**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23409)

### CODE REVIEW

**Comment by ItzLevvie** [comment]
> Why? I after so many days found a vulnerability in the repository that I could fix and you took my opportunity.

You can do the Python 2 ones.

I made all of these changes it seems like Python 3 can be installed SxS (all 25+ versions were installed onto a VM without uninstalling) so it was easy to update all of the manifests.

**Comment by vedantmgoyal2009** [comment]
> You can do the Python 2 ones.

Thank you

**Review by ItzLevvie — APPROVED** [review]

**Comment by vedantmgoyal2009** [comment]
@ItzLevvie @ItzLevvie2 Should I add `ProductCode` in Python 3 installers? They are all MSI installers...

**Comment by ItzLevvie** [comment]
Yes.

**Pull request merged**
