### PR TITLE
SylvainRougeaux.Metatogger version 7.3.3.0

### PR DESCRIPTION
**Pull request by CyberSinh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/121040)

### CODE REVIEW

**Comment by CyberSinh** [comment]
Validation fails with label `Validation-Shell-Execute`.

The validation [pipeline logs](https://dev.azure.com/ms/ed6a5dfa-6e7f-413b-842c-8305dd9e89e6/_apis/build/builds/500507/logs/23) give no details about the error encountered:

```
****************************************************************************************
Installation Verification
****************************************************************************************

-----------------------------------------------------
Result: Failed
-----------------------------------------------------
Status: Completed
```

`winget install --manifest <path>` correctly installs the application, although Windows SmartScreen validation was required. The application is not signed and Windows SmartSreen is particularly intolerant of software that is not yet widely used because it is new.

Can anyone tell me what is blocking the validation of my PR?

Thanks!

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335226 
2023-09-27 18:06:13.503 [CLI ] ShellExecute installer failed: 1603 Property(S): ErrorDialog = ErrorDlg 
MSI (s) (24:38) [18:06:13:278]: Product: Metatogger 7.3 -- Installation failed. 
MSI (s) (24:38) [18:06:13:278]: Windows Installer installed the product. Product Name: Metatogger 7.3. Product Version: 7.3.3.0. Product Language: 1033. Manufacturer: Sylvain Rougeaux. Installation success or error status: 1603. 

Status `1603` frequently means a missing dependency.

**Comment by stephengillie** [comment]
This package installed and launched normally in a Windows 10 VM, so the `Validation-Shell-Execute` label might just be pipeline issue.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
