### PR TITLE
GoLang.Go version 1.20.4

### PR DESCRIPTION
**Pull request by staticfrost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/104688)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
⚠️ It look like there is duplicate pipelines. If any one pipelines approve, it might be marked as duplicate of another pipelines. ⚠️ This is a duplicate PR of 104907.

**Comment by ItzLevvie** [comment]
Close with reason: Merge conflicts;

**Comment by BrandonWanHuanSheng** [comment]
I am easily looking at those title. Because 104907 have 33 comments and had been merged into master. Which cause the validation pipelines to merge conflict if there is a same time pipeline change. Did you notice your pull request?  

> * [x]  Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?

**Comment by BrandonWanHuanSheng** [comment]
I always scan using https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+GoLang.go+is%3Aopen. This can help me to determine if that one is duplicate.

**Pull request closed without merging**
