### PR TITLE
New version: Bitwarden.CLI version 2024.6.0

### PR DESCRIPTION
**Pull request by damn-good-b0t**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/157679)

### CODE REVIEW

**Comment by Utesgui** [comment]
image
https://www.virustotal.com/gui/file/08a7bdbb5eeecbbdfde1ba35917c2c5451a503cb9759a4a94da37b7add93d486

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-06-13 07:49:37.604 [FAIL] Installer failed security check. Url: https://github.com/bitwarden/clients/releases/download/cli-v2024.6.0/bw-windows-2024.6.0.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 885.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-06-14 09:51:28.312 [FAIL] Installer failed security check. Url: https://github.com/bitwarden/clients/releases/download/cli-v2024.6.0/bw-windows-2024.6.0.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 886.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
