### PR TITLE
New version: suse.RancherDesktop version 1.9.1

### LINKED ISSUE #111943: [Update Request]: Update Rancher Desktop to the latest version (1.9.1)
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

suse.RancherDesktop

### Package Version

1.9.1

### Please describe the changes you would like to see

There is a new release (1.9.1) available
Download Page Url: https://github.com/rancher-sandbox/rancher-desktop/releases

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

* Resolves #111943

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/112148&drop=dogfoodAlpha

### CODE REVIEW

**Comment by Trenly** [comment]
Application installed just fine according to the Installation Verification Logs

```
MSI (s) (EC:74) [11:34:17:749]: Product: Rancher Desktop -- Installation completed successfully.

MSI (s) (EC:74) [11:34:17:749]: Windows Installer installed the product. Product Name: Rancher Desktop. Product Version: 1.9.1. Product Language: 1033. Manufacturer: SUSE. Installation success or error status: 0.

MSI (s) (EC:74) [11:34:17:749]: Windows Installer requires a system restart. Product Name: Rancher Desktop. Product Version: 1.9.1. Product Language: 1033. Manufacturer: SUSE. Type of System Restart: 2. Reason for Restart: 2.

MSI (s) (EC:74) [11:34:17:749]: Product: Rancher Desktop. Restart required. The installation or update for the product required a restart for all changes to take effect.  The restart was deferred to a later time.

=== Logging stopped: 7/14/2023  11:34:17 ===
```

The icon even shows on the desktop
image

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978334967 
> 2023-07-14 11:34:18.267 [CLI ] ShellExecute installer failed: 3010 
> Action start 11:33:04: WixSchedFirewallExceptionsUninstall. SchedFirewallExceptions:  Component 'AdminInstallFirewall' action state (1) doesn't match request (2) SchedFirewallExceptions:  No firewall exceptions scheduled Action ended 11:33:04: WixSchedFirewallExceptionsUninstall. Return value 1. Action start 11:33:05: WixSchedFirewallExceptionsInstall. SchedFirewallExceptions:  Scheduling firewall exception (1╬ô├⌐┬╝Rancher Desktop Networking Private Exception╬ô├⌐┬╝2╬ô├⌐┬╝*╬ô├⌐┬╝0╬ô├⌐┬╝2╬ô├⌐┬╝C:\Program Files\Rancher Desktop\resources\resources\win32\internal\host-switch.exe╬ô├⌐┬╝╬ô├⌐┬╝6╬ô├⌐┬╝Rancher Desktop host-switch.exe profile exception for private networks╬ô├⌐┬╝1╬ô├⌐┬╝Rancher Desktop Networking Domain Exception╬ô├⌐┬╝1╬ô├⌐┬╝*╬ô├⌐┬╝0╬ô├⌐┬╝2╬ô├⌐┬╝C:\Program Files\Rancher Desktop\resources\resources\win32\internal\host-switch.exe╬ô├⌐┬╝╬ô├⌐┬╝6╬ô├⌐┬╝Rancher Desktop host-switch.exe profile exception for domain networks) 
>Action start 11:33:05: WixRollbackFirewallExceptionsInstall. Action ended 11:33:05: WixRollbackFirewallExceptionsInstall. Return value 1. Action start 11:33:05: WixExecFirewallExceptionsInstall. Action ended 11:33:05: WixExecFirewallExceptionsInstall. Return value 1. 
> Action ended 11:33:05: WixSchedFirewallExceptionsInstall. Return value 1. ExecFirewallExceptions:  Installing firewall exception2 Rancher Desktop Networking Private Exception (C:\Program Files\Rancher Desktop\resources\resources\win32\internal\host-switch.exe) ExecFirewallExceptions:  Installing firewall exception2 Rancher Desktop Networking Domain Exception (C:\Program Files\Rancher Desktop\resources\resources\win32\internal\host-switch.exe) Property(S): WixRollbackFirewallExceptionsInstall = 1Γö¼├çRancher Desktop Networking Private ExceptionΓö¼├ç2Γö¼├ç*Γö¼├ç0Γö¼├ç2Γö¼├çC:\Program Files\Rancher Desktop\resources\resources\win32\internal\host-switch.exeΓö¼├çΓö¼├ç6Γö¼├çRancher Desktop host-switch.exe profile exception for private networksΓö¼├ç1Γö¼├çRancher Desktop Networking Domain ExceptionΓö¼├ç1Γö¼├ç*Γö¼├ç0Γö¼├ç2Γö¼├çC:\Program Files\Rancher Desktop\resources\resources\win32\internal\host-switch.exeΓö¼├çΓö¼├ç6Γö¼├çRancher Desktop host-switch.exe profile exception for domain networks Property(S): WixExecFirewallExceptionsInstall = 1Γö¼├çRancher Desktop Networking Private ExceptionΓö¼├ç2Γö¼├ç*Γö¼├ç0Γö¼├ç2Γö¼├çC:\Program Files\Rancher Desktop\resources\resources\win32\internal\host-switch.exeΓö¼├çΓö¼├ç6Γö¼├çRancher Desktop host-switch.exe profile exception for private networksΓö¼├ç1Γö¼├çRancher Desktop Networking Domain ExceptionΓö¼├ç1Γö¼├ç*Γö¼├ç0Γö¼├ç2Γö¼├çC:\Program Files\Rancher Desktop\resources\resources\win32\internal\host-switch.exeΓö¼├çΓö¼├ç6Γö¼├çRancher Desktop host-switch.exe profile exception for domain networks Property(S): d_UzwP9Lbg7HUIy4ukNmu0kRezCYzrusdu_e2i3NIdYTI = C:\Program Files\Rancher Desktop\resources\resources\rancher-dashboard\fail-whale\ Property(S): ErrorDialog = ErrorDlg MSI (s) (EC:74) [11:34:17:749]: Windows Installer installed the product. Product Name: Rancher Desktop. Product Version: 1.9.1. Product Language: 1033. Manufacturer: SUSE. Installation success or error status: 0.

**Comment by stephengillie** [comment]
11:53:40 AM: 
> 2023-07-14 11:53:39.934 [CLI ] ShellExecute installer failed: 3010
> 11:53:40 AM: WixQuietExec64:      + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand
> 11:53:40 AM: WixQuietExec64:      + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand
> 11:53:40 AM: Property(S): ErrorDialog = ErrorDlg
> 11:53:40 AM: MSI (s) (70:80) [11:53:39:634]: Windows Installer installed the product. Product Name: Rancher Desktop. Product Version: 1.9.1. Product Language: 1033. Manufacturer: SUSE. Installation success or error status: 0.

**Comment by Trenly** [comment]
Ah, I see. I missed the 3010

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
