### PR TITLE
New version: Julialang.Juliaup version 1.15.0.0

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#6492](https://github.com/SpecterShell/Dumplings/actions/runs/9877640972).

<details>

<summary>Log</summary>

````
Updated: 1.14.9.0 → 1.15.0.0

{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/releases/releases#get-a-release-by-tag-name",
  "status": "404"
}
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/162339)

### CODE REVIEW

**Comment by stephengillie** [comment]
This might be referring to the certificate that the package was signed with. Is the package self-signed?
https://learn.microsoft.com/windows/msix/package/signing-package-overview

**Review by ItzLevvie — APPROVED** [review]

**Comment by SpecterShell** [comment]
> This might be referring to the certificate that the package was signed with. Is the package self-signed? [learn.microsoft.com/windows/msix/package/signing-package-overview](https://learn.microsoft.com/windows/msix/package/signing-package-overview)

Nope

image

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/pull/157151#issuecomment-2233735834

**Pull request closed without merging**
