### PR TITLE
HP.HPSupportAssistant version 0.2.56.9141

### PR DESCRIPTION
**Pull request by TargetCrafter**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/65256)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]
Silent install doesn't skip this prompt - so we're waiting for interactive-only installers to be supported:
image

**Comment by TargetCrafter** [comment]
So we are waiting for HP on this one then?

**Comment by ItzLevvie** [comment]
> So we are waiting for HP on this one then?

WinGet will support interactive-only installers in the future which means installers that doesn't have silent install or the silent install works but some prompts aren't skippable will be supported.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
You can set this pull request to DRAFT until WinGet supports HP Support Assistant.

You could probably try to contact the publisher and see if they can fix it but I feel like the publisher may not respond so it's better to wait until WinGet adds support for HP Support Assistant and other programs.

**Comment by ItzLevvie** [comment]
@msftbot Interactive-Only-Installer

**Comment by ItzLevvie** [comment]
@msftbot Blocking-Issue

**Comment by Padmacharan** [comment]
Request

**Pull request closed without merging**
