### PR TITLE
New version: Evexi.EvexiCLI 0.0.1

### PR DESCRIPTION
**Pull request by AlaNDGT**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/123612)

### CODE REVIEW

**Comment by AlaNDGT** [comment]
@microsoft-github-policy-service agree company="Evexi"

**Comment by zachcarp** [comment]
@AlaNDGT - Could you please update your file location to remove the spaces? It should be "Evexi\EvexiCLI" not "Evexi\Evexi CLI"

**Comment by AlaNDGT** [comment]
@zachcarp Updated

Also path was messed for some reason, as files were generated in the root directory

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 9:48:27 AM:  > 2023-10-26 09:48:26.435 [FAIL] Installer failed security check. Url: https://github.com/evexi/evexi-cli/releases/download/v0.0.1/evexi-cli_Windows_i386.zip Result: 0x80004005 

This is similar to a Defender failure. It might be a false positive, and we can rescan tomorrow.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
