### PR TITLE
Move Arc.Arc 0.11.0.12143 to TheBrowserCompany.Arc 0.11.0.12143

### PR DESCRIPTION
**Pull request by Exorcism0666**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/145118)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Signature Update Failed.
> Failure to parse win 10, attempting win 11
> Installation failed with exit code -1978334960
> 2024-03-18 20:24:10.751 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(722)\WindowsPackageManager.dll!00007FF943B2F3CF: (caller: 00007FF9438B84FF) LogHr(1) tid(1c7c) 8A15005E     Msg:[C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF943A34DD8: (caller: 00007FF943ADF820) Exception(1) tid(1c7c) 8A15005E ] 
> 2024-03-18 20:24:10.751 [REPO] Failed to open available source: msstore
> 2024-03-18 20:24:12.828 [CLI ] Caught wil::ResultException: C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF943A34DD8: (caller: 00007FF943ADF820) Exception(1) tid(1c7c) 8A15005E 
> 2024-03-18 20:24:14.715 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(722)\WindowsPackageManager.dll!00007FF943B2F3CF: (caller: 00007FF9438B84FF) LogHr(1) tid(1f7c) 8A15005E     Msg:[C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF943A34DD8: (caller: 00007FF943ADF820) Exception(1) tid(1f7c) 8A15005E ] 
> 2024-03-18 20:24:14.715 [REPO] Failed to open available source: msstore
> 2024-03-18 20:24:15.636 [CLI ] Caught wil::ResultException: C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF943A34DD8: (caller: 00007FF943ADF820) Exception(1) tid(1f7c) 8A15005E 
> 2024-03-18 20:24:20.916 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(722)\WindowsPackageManager.dll!00007FF94152F3CF: (caller: 00007FF9412B84FF) LogHr(1) tid(d00) 8A15005E     Msg:[C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF941434DD8: (caller: 00007FF9414DF820) Exception(1) tid(d00) 8A15005E ] 
> 2024-03-18 20:24:20.916 [REPO] Failed to open available source: msstore
> 2024-03-18 20:25:04.757 [CLI ] ShellExecute installer failed: 2147944126

(Automated response - build 870.)

**Comment by Exorcism0666** [comment]
@stephengillie I would like some help for this package, please. 😀

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
