### PR TITLE
New version: Elgato.WaveLink version 1.6.1.3029 [FP-O]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | Elgato Wave Link | Elgato Wave Link    |
| Version     | 1.6.1.3029     | 1.6.1.3029 |
| Publisher   | Elgato Systems   | Corsair Memory, Inc.      |
| ProductCode |           | {CE406C04-382B-4904-8E9A-01A2F856BA17}    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [4426](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/3648118189>)

### CODE REVIEW

**Comment by Trenly** [comment]
```
D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFB389C52B9: (caller: 00007FFB389C5AAA) Exception(1) tid(23c4) 80190193 Forbidden (403).
```

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
@msftbot Area-External

**Comment by ItzLevvie** [comment]
@msftbot Blocking-Issue

**Comment by russellbanks** [comment]
Is it still a blocking issue if the Azure Pipelines have passed?

**Comment by vedantmgoyal2009** [comment]
@msftbot reset feedback

**Comment by ItzLevvie** [comment]
@msftbot reset feedback

**Review by ItzLevvie — DISMISSED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
