### PR TITLE
New version: 3ll3d00d.beqdesigner version 0.11.5

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/107011)

### CODE REVIEW

**Review by jedieaston — CHANGES_REQUESTED** [review]
Is there a dependency needed here? 

image

**Comment by stephengillie** [comment]
> Is there a dependency needed here?
> 
> image

It works normally in a Windows 11 VM - is this Windows 10?

**Comment by vedantmgoyal2009** [comment]
@stephengillie can this be approved?

**Comment by stephengillie** [comment]
> @stephengillie can this be approved?

Yes, sorry - was waiting for @Trenly to update.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
