### PR TITLE
CoelWu.Clash.NET version 1.1.2

### PR DESCRIPTION
**Pull request by CoelWu**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/17245)

### CODE REVIEW

**Comment by CoelWu** [comment]
There is weird. I have tested in my local computer, only a UAC pops up and nothing else. The verify and install were both success. Dear Moderators, If you have time, please check it manually. Thanks

**Comment by denelon** [comment]
@CoelWu does this have a dependency on .net framework? If it does, it will be blocked by the dependency.

**Comment by CoelWu** [comment]
> @CoelWu does this have a dependency on .net framework? If it does, it will be blocked by the dependency.

Yes, It is depended on .NET 5.

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
Close with reason: Github repository containing installer has been deleted or made private;

**Pull request closed without merging**
