### PR TITLE
xkonglong.gongwen version 2.2.0.0

### PR DESCRIPTION
**Pull request by xkonglong**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/94967)

### CODE REVIEW

**Comment by xkonglong** [comment]
> @xkonglong请阅读以下贡献者许可协议 (CLA)。如果您同意 CLA，请回复并提供以下信息。
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > 选项：
> > 
> > * （默认 - 未指定公司）我对我的提交内容拥有知识产权的唯一所有权，并且我不会在为我的雇主工作的过程中提交内容。
> > * （当公司提供时）我在为我的雇主工作期间提交意见（或者我的雇主根据合同或适用法律对我的意见拥有知识产权）。我已获得我的雇主的许可，可以代表我的雇主进行提交并签订本协议。通过在下面签名，所定义的术语“您”包括我和我的雇主。
> 
> 贡献者许可协议



> 

@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
The program installs, and starts a demo. But there is a missing file for the Visual Studio Tools for Office 4.0 Runtime:
image

Also, pressing ESC to exit the demo gives another missing file message: 
image

The missing file in the second image - is it one of the files that would be installed by the first image's installer?

**Comment by xkonglong** [comment]
> The missing file in the second image - is it one of the files that would be installed by the first image's installer?

 After the installation is complete, a docx file will open automatically .

 Maybe your test environment does not have MSOffice (Word).

**Review by OverRevvv — APPROVED** [review]

**Comment by stephengillie** [comment]
> This is a VSTO application for Word.
> 
> After the installation is complete, a docx file will open automatically .
> 
> Maybe your test environment does not have MSOffice (Word).

Yes, our testing environments are fresh installs of Windows. Since Word is a dependency for this application, normally we'd add the package. However, it's part of Microsoft.Office, so this should be added as a dependency.

**Comment by xkonglong** [comment]
> it's part of Microsoft.Office

This VSTO  for WPS Office and  MSOffice !    MSOffice is not required .

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
