### PR TITLE
New version: r12f.Rnp version 0.1.115.0

### PR DESCRIPTION
**Pull request by OfficialEsco**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/24297)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by r12f** [comment]
auto tracking future releases? this is awesome!

**Comment by denelon** [comment]
@r12f have you had a chance to take a look at [wingetcreate](https://github.com/microsoft/wingetcreate)? We've built tooling and can help with automated manifest creation from GitHub. This could likely be leveraged with other CI/CD pipelines.

**Comment by r12f** [comment]
Hi @denelon , yes, if you check the first version, the package is created via wingetcreate. But I am having trouble get it integrated with the CI/CD pipeline, because even though I tried to use update command and give it the PST, it is throwing error every time. And maybe I am too dumb, somehow, I didn't see any documentation/examples on what is the expected way to use it. Then, while I am still struggling, I saw this automatic update happened, which is a savior to me!

**Comment by denelon** [comment]
@r12f feel free to create a [discussion](https://github.com/microsoft/winget-create/discussions) over there to ask for tips/help/suggestions. I'm sure plenty of others would benefit from any gaps you found in our documentation, or other unique challenges you have had. Maybe we need more examples, or bug fixes/improvements.

**Comment by r12f** [comment]
sure @denelon ! currently I don't have a new release, so wingetcreate update won't really give me anything, but once the new version is out, will take another look and see how it works!

**Pull request merged**
