### PR TITLE
Updated OpenRA installer with x86 architecture MinimumOS and a few more things

### PR DESCRIPTION
**Pull request by bearmannl**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/19381)

### CODE REVIEW

**Comment by bearmannl** [comment]
For future reference, is there any place I can find the error details myself? Both architecture types seem to work fine on my machine.

**Comment by bearmannl** [comment]
@OfficialEsco, could you point me in the right direction?

**Comment by OfficialEsco** [comment]
> @OfficialEsco, could you point me in the right direction?

https://github.com/microsoft/winget-cli/blob/master/doc/windows/package-manager/package/winget-validation.md
Not like it will help kekw

This is most of the time just the bot being childish and not wanting to cooperate..

**Comment by bearmannl** [comment]
> > @OfficialEsco, could you point me in the right direction?
> 
> https://github.com/microsoft/winget-cli/blob/master/doc/windows/package-manager/package/winget-validation.md
> Not like it will help kekw
> 
> This is most of the time just the bot being childish and not wanting to cooperate..
> 
> **Checks** -> **View more details on Azure Pipelines** is the only issues we peasants can see

Haha thanks anyway!

I was secretly hoping a more veteran peasant maybe had some insights on how to get the internal error details... alas! Will patiently wait for the details ☺

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
