### PR TITLE
New version: martinvonz.jj version 0.19.0

### LINKED ISSUE #161693: [Update Request]: martinvonz.jj to 0.19.0
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

martinvonz.jj

### Package Version

0.19.0

### Please describe the changes you would like to see

Update martinvonz.jj to 0.19.0: https://github.com/martinvonz/jj/releases/download/v0.19.0/jj-v0.19.0-x86_64-pc-windows-msvc.zip

### PR DESCRIPTION
**Pull request by jennings**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

Fixes #161693 
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161694)

### CODE REVIEW

**Comment by jennings** [comment]
@microsoft-github-policy-service agree

**Review by Trenly — APPROVED** [review]

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
