### PR TITLE
Add Zulu-UC 3.5.1

### PR DESCRIPTION
**Pull request by AlexH0661**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2112)

### CODE REVIEW

**Comment by AlexH0661** [comment]
Can use a GET request to pull the installer. Not sure why I'm getting this error when running the Azure Pipelines tests.

https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=90222&view=logs&j=c8020aa5-4aab-5881-691f-21986e02afd0&t=bade86d6-d2be-5ddd-c1b9-7d8db9c4a60d&l=40 **- "Error occurred during installer copy from https://zulu-updater.sangoma.com/download/3.5.1/windows_64/Zulu%20Setup%203.5.1.exe."**

https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=90222&view=logs&j=c8020aa5-4aab-5881-691f-21986e02afd0&t=bade86d6-d2be-5ddd-c1b9-7d8db9c4a60d&l=41  **- "Range GET requests are not supported by the copy source"**

**Comment by AlexH0661** [comment]
#91

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
