### PR TITLE
Nvidia GeForce Experience v3.20.4.14

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [ ] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

Can't test Nvidia GeForce Experience in a VM 🙃

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2347)

### CODE REVIEW

**Comment by denelon** [comment]
Found Nvidia GeForce Experience [Nvidia.GeForceExperience]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://us.download.nvidia.com/GFE/GFEClient/3.20.4.14/GeForce_Experience_v3.20.4.14.exe
  ██████████████████████████████   119 MB /  119 MB
Successfully verified installer hash
Installing ...
Installer failed with exit code: 3858759680

**Comment by denelon** [comment]
@OfficialEsco I couldn't find anything on that exit code. It may just be that I don't have nvidia hardware on this machine.

**Comment by OfficialEsco** [comment]
@denelon Yes it is, which is why i said you can't test it in a VM

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
