### PR TITLE
New package: DigitalDevices.DD-TV version 1.15.0.0

### PR DESCRIPTION
**Pull request by TrueSkrillor**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?
  - None

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/172033)

### CODE REVIEW

**Comment by TrueSkrillor** [comment]
@microsoft-github-policy-service agree

**Comment by TrueSkrillor** [comment]
Given the non-descriptive error message, I don't know why domain validation failed here. I also briefly looked at the Azure pipeline, which mentions `www.digital-devices.eu` to fail validation; however, I did not provide any hint on why this is. I can confirm through manual testing that the URL is valid and that the installation works as expected with a local manifest. There is also no inconsistency between the publisher/package domain and the installer domain. I would appreciate feedback on this matter.

**Comment by stephengillie** [comment]
Verify:
image

**Comment by TrueSkrillor** [comment]
> Verify: image

Looks good to me 👍

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
I forgot to update the labels before running my automation, so it went down the wrong path.

**Pull request merged**
