### PR TITLE
ARP/Update metadata/Add de-DE locale: JanFiala.PSpad 5.0.6.589

### PR DESCRIPTION
**Pull request by quhxl**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/22589)

### CODE REVIEW

**Comment by quhxl** [comment]
```
-----------------------------------------------------
Manifest: manifests\j\JanFiala\PSpad\5.0.6.589
-----------------------------------------------------
URI: http://www.pspad.com/en/, Validation result: Failed, Error Message: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 
URI: http://www.pspad.com/en/faq.htm, Validation result: Failed, Error Message: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 
URI: http://www.pspad.com/include/page/privacypolicy.html, Validation result: Failed, Error Message: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 
URI: http://www.pspad.com/en/, Validation result: Failed, Error Message: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 
URI: http://www.pspad.com/en/licence.php, Validation result: Failed, Error Message: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 
URI: https://pspad.poradna.net/release/pspad506_x64_setup.exe, Validation result: Passed
URI: https://pspad.poradna.net/release/pspad506_setup.exe, Validation result: Passed
URI: http://www.pspad.com/en/, Validation result: Failed, Error Message: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 
URI: http://www.pspad.com/de/faq.htm, Validation result: Failed, Error Message: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 
URI: http://www.pspad.com/include/page/privacypolicy.html, Validation result: Failed, Error Message: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 
URI: http://www.pspad.com/de/, Validation result: Failed, Error Message: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 
URI: http://www.pspad.com/de/licence.php, Validation result: Failed, Error Message: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. 

```

**Comment by OfficialEsco** [comment]
The site does appear to support https, try changing it to that just for lols

**Comment by quhxl** [comment]
Is the bot not accepting http anymore?

**Review by OfficialEsco — APPROVED** [review]
Naaah just had a feeling 😎

**Pull request merged**
