### PR TITLE
New package: Wfview.Wfview version 1.64

### LINKED ISSUE #113087: [Package Request]: wfview
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://wfview.org/download/
Publisher: Elliott Liggett and Phil Taylor
Package Name: wfview
Description: Open Source interface for Icom transceivers. It provides the user with controls that may be comfortably operated from a keyboard, mouse, or touch screen interface.
Package Version: 1.64
Installer URL: https://wfview.org/download/windows-x64-release-v1-62-2/?wpdmdl=1168

### PR DESCRIPTION
**Pull request by BrandonWanHuanSheng**
Resolves #113087

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/129021)

### CODE REVIEW

**Review by Dragon1573 — CHANGES_REQUESTED** [review]

**Comment by stephengillie** [comment]
I need to manually validate, but there are many ongoing conversations. Once @BrandonWanHuanSheng has resolved these, I'll manually validate.

**Comment by BrandonWanHuanSheng** [comment]
Yes, it is true. There are many ongoing conservation.

**Comment by BrandonWanHuanSheng** [comment]
The validation is still failed.

**Comment by stephengillie** [comment]
Manual Validation ended with a stalled download at 60 MB of 61 MB. Retrying.

**Comment by stephengillie** [comment]
This package host seems to be throttling based on user-agent. The WinGet download takes more than 15 minutes and hangs at the last couple of percent, giving only about 4 mb/s for the first 95%. While in Edge it took about 30 seconds, for close to 120 mb/s.

**Comment by stephengillie** [comment]
Manual Validation ended with a stalled download at 59MB of 61 MB. It's as though the package has a problem at the last few MB. But this isn't reflected in Edge.

**Comment by Dragon1573** [comment]
> This package host seems to be throttling based on user-agent.

Yes, I have the same situation.

- When proxy disabled, I'm unable to connect to the host.
- When proxy enabled, ...
  - Edge Dev is downloading package with no more than 50KB/s.
  - [Motrix](https://github.com/agalwood/Motrix) v1.8.19 (bundled modified version of Aria2 v1.36.0 with parallel limit up to 64) can initialize the download with up to 2MB/s and immediately drop to 0B/s in several seconds.
- Seems no throttling behaviour when downloading the package using `wget` in GitHub Codespaces.

**Comment by BrandonWanHuanSheng** [comment]
Hmmm. Pull request change to draft for some reason.

**Comment by BrandonWanHuanSheng** [comment]
It look like this package download and stuck at 95%, it hang about 2 hours to complete the download.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  
> 2023-12-04 14:36:18.495 [CORE] DeliveryOptimization error: 0x80d02002, extended error: 0x80072ee2 
> 2023-12-04 14:36:18.526 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFCA2451EFD: (caller: 00007FFCA24527D0) Exception(1) tid(1f68) 80D02002

**Comment by BrandonWanHuanSheng** [comment]
Currently Publish Pipelines is on paused. Because ICM Users is deploying on minor update in Azure Pipelines.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
