### PR TITLE
New version: ExacqTechnologies.exacqVisionClient version 24.03.4.0

### LINKED ISSUE #157707: [Update Request]: exacqvision Client 24.03.4.0
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

ExacqTechnologies.exacqVisionClient

### Package Version

24.03.4.0

### Please describe the changes you would like to see

The current package in Winget is over a year old. Latest version here:
https://cdnpublic.exacq.com/24.03/exacqVisionClient_24.03.4.0_x64.msi

### PR DESCRIPTION
**Pull request by fancybody**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.2.1 :rocket:

- Resolves #157707

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/157765)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> -- CUSTOM ACTION -- Valid exit codes are 0

(Automated response - build 885.)

**Comment by stephengillie** [comment]
Hi @fancybody,

This manifest adds Apps and Features entries that aren't present in previous PR versions. These entries should be added to the previous versions, or removed from this version.

(Automated response - build 885.)

**Comment by fancybody** [comment]
@stephengillie
> Does this package need different silent installer switches?

The file downloaded from the website is just a wrapper for the actual setup (which gets extracted to the %temp% folder).
That setup can then be run silently using `/S`.

Does winget have a system where it can run the wrapper first and then run the setup?
If not, please close this PR.

**Comment by stephengillie** [comment]
Hi @fancybody,

This manifest adds Apps and Features entries that aren't present in previous PR versions. These entries should be added to the previous versions, or removed from this version.

(Automated response - build 885.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
