### PR TITLE
New version: Mozilla.Thunderbird.Beta version 120.0b5

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/125399)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
= = = = = = PR is modifying Apps and Features Entries = = = = = =
 This PR adds AnF entries. Do other manifest versions need this as well?

**Comment by treysis** [comment]
@stephengillie Please don't approve @vedantmgoyal2009's PRs for Mozilla.Thunderbird.Beta anymore, as these cause problems with the current version of winget.

**Review by treysis — COMMENTED** [review]
Revert all changes. Winget currently can't handle beta versions for Thunderbird due to the current version magic logic.

**Comment by Trenly** [comment]
I think we should pull all beta versions of thunderbird (and firefox) since Mozilla doesn't have a good way to identify what is a release version and what is a beta version

**Comment by denelon** [comment]
@vedantmgoyal2009 & @stephengillie it looks like we should pull the beta versions so we're not causing problems for customers.

**Pull request merged**
