### PR TITLE
New version: eMClient.eMClient version 9.2.1553.0 [FP-D]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | eM Client | eM Client    |
| Version     | 9.2.1553.0     | 9.2.1553.0 |
| Publisher   | eM Client Inc.   | eM Client Inc.      |
| ProductCode |           | {E2D0532A-9FE8-4EEF-9879-795A65206067}    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [5845](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/4119535952>)

### CODE REVIEW

**Review by russellbanks — DISMISSED** [review]

**Comment by stephengillie** [comment]
Superseded by #95580

**Comment by Trenly** [comment]
Close with reason: Cleanup of merge conflicts from fabricbot errors;

**Pull request closed without merging**
