### PR TITLE
New version: tibbo.ioninja version 5.5.0

### PR DESCRIPTION
**Pull request by vovkos**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135301)

### CODE REVIEW

**Comment by vovkos** [comment]
```
1/23/2024 9:35:14 PM

****************************************************************************************
Installation Verification
****************************************************************************************
Status: Started
============================================================================== 
Task         : Installation Validation
Description  : Invoke an Azure Function
Version      : 1.220.0
Author       : Microsoft Corporation
Help URL     : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/azure-function
============================================================================== 
2024-01-23T21:35:15.8047535Z POST ***?code=***&
Request body: {
  "operationId": "WinGetSvc-Validation-359-135301-20240123-1",
  "BuildId": "534695",
  "PlanUrl": "https://dev.azure.com/ms/",
  "HubName": "build",
  "ProjectId": "ed6a5dfa-6e7f-413b-842c-8305dd9e89e6",
  "PlanId": "822dbe47-b8a3-4851-853e-53705abb3de3",
  "JobId": "68997d86-8ece-5ae8-3ac5-ccdbfa458731",
  "TimelineId": "822dbe47-b8a3-4851-853e-53705abb3de3",
  "TaskInstanceId": "b79910ce-dca5-5e27-ad7f-bd285eecb5a2",
  "AuthToken": ***
}
				Response Code: OK
				Response: 

1/23/2024 11:59:13 PM

****************************************************************************************
Installation Verification
****************************************************************************************

-----------------------------------------------------
Result: Failed
-----------------------------------------------------
Status: Completed
```

Hmm. How do I fix this error? The only information I get from the log is `Result: Failed`.

Tried installing the manifest locally with `winget install -m 5.5.0` and it works.

Where do I go from here? Thanks!

**Comment by stephengillie** [comment]
Hi @vovkos,

This error indicates an issue with our pipelines - that the Validation process did not complete, but got far enough that I can perform a manual validation, which I'll perform soon. It doesn't give any feedback about the package. 

The domain host might have an IP block preventing download. But that would usually show up under a different error. Timeout usually happens around the 3 hour point, so this could be a timeout, but seems to have timed out early.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
