### PR TITLE
New version: Ubisoft.Connect version 129.0.10647

### LINKED ISSUE #45719: [Bug]: Ubisoft Connect (Ubisoft.Connect) installer hash not matching, requires --force to install
### Brief description of your issue

Trying to install version 129.0.0.10647 of Ubisoft Connect (id: Ubisoft.Connect) required the use of --force to install due to a mismatching hash

### Steps to reproduce

```
C:\Users\Me>winget install --id Ubisoft.Connect
Found Ubisoft Connect [Ubisoft.Connect] Version 129.0.0.10647
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://ubistatic3-a.akamaihd.net/orbit/launcher_installer/UbisoftConnectInstaller.exe
  ██████████████████████████████   218 MB /  218 MB
Installer hash does not match; to override this check use --force
```

```
C:\Users\Me>winget install --id Ubisoft.Connect --force
Found Ubisoft Connect [Ubisoft.Connect] Version 129.0.0.10647
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://ubistatic3-a.akamaihd.net/orbit/launcher_installer/UbisoftConnectInstaller.exe
  ██████████████████████████████   218 MB /  218 MB
Installer hash does not match; proceeding due to --force
Starting package install...
Successfully installed
```

### Expected behavior

Install should not require the use of --force

### Actual behavior

Have to use --force

### Environment

```shell
Windows Package Manager v1.1.13405
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1526
Package: Microsoft.DesktopAppInstaller v1.16.13405.0
```

### PR DESCRIPTION
**Pull request by KaranKad**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Resolves https://github.com/microsoft/winget-pkgs/issues/45719

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/45726)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by jedieaston — APPROVED** [review]

**Comment by zachcarp** [comment]
@denelon - Can I get your input on the installer link?

**Comment by denelon** [comment]
https://ubisoftconnect.com/en-US/ gives https://ubi.li/4vxt9 for the download link.
@KaranKad how did we find the download URL in the manifest?

**Comment by KaranKad** [comment]
@denelon Thats where the link redirects.
image

**Comment by denelon** [comment]
@KaranKad thank you so much!
I tried several sites that were just throwing me errors when I tried to do that.

**Comment by zachcarp** [comment]
Multiple redirects worked for me. That seems like an odd hosting URL. I'll make a note in our TSG for future reference.

**Pull request merged**
