### PR TITLE
Add Scilab

### PR DESCRIPTION
**Pull request by superusercode**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1567)

### CODE REVIEW

**Comment by superusercode** [comment]
```
6/4/2020 6:47:21 AM
Status: Completed
Result: Failed
Error occurred during installer copy from https://www.scilab.org/download/6.1.0/scilab-6.1.0_x64.exe.
 The source request body for copy source is too large and exceeds the maximum permissible limit (100MB).

```

no mirrors so not sure how I'll get around this

**Comment by superusercode** [comment]
Same issue as #1260

**Comment by superusercode** [comment]
@SoftCreatR any chance you can proxy this one too?

**Comment by SoftCreatR** [comment]
@superusercode Sure :)

`https://www.winget.it/dl/cfb220acfd3edea27f069656c1a6d86ee216faafc4532aba32b00fcbd67aeb76/https%3A%2F%2Fwww.scilab.org%2Fdownload%2F6.1.0%2Fscilab-6.1.0_x64.exe`

**Comment by SoftCreatR** [comment]
Sure :)

`https://www.winget.it/dl/cfb220acfd3edea27f069656c1a6d86ee216faafc4532aba32b00fcbd67aeb76/https%3A%2F%2Fwww.scilab.org%2Fdownload%2F6.1.0%2Fscilab-6.1.0_x64.exe`

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
