### PR TITLE
New version: Anaconda.Anaconda3 version 2023.09-0

### PR DESCRIPTION
**Pull request by Trenly**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/145929)

### CODE REVIEW

**Comment by Trenly** [comment]
Intentionally duplicates #145924 except this is an add-only to avoid the label. Once this has merged and published, the other version should be able to be removed

**Comment by Trenly** [comment]
@stephengillie - if IEDS is applied again, you can maybe take a look at #145924; This isn't a "new" package, it's just correcting the version, so if you search for the hash in the repo, you should see the same Installer URL and Hash already exist, so the installer has already been verified in a previous PR

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Yes - they're in https://github.com/microsoft/winget-pkgs/pull/134161/files

**Comment by thangarajua** [comment]
Could you please update the Anaconda package to the latest version - Anaconda 2024.02-1 (Feb 26, 2024)
https://repo.anaconda.com/archive/Anaconda3-2024.02-1-Windows-x86_64.exe

**Pull request merged**
