### PR TITLE
WinScreenfetch added

### PR DESCRIPTION
**Pull request by sebagomez**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/805)

### CODE REVIEW

**Comment by sebagomez** [comment]
The manifest was created using the Windows Store tool.  
Also, it is just a plain exe with no installation, do I still need to wrap it in an installer?

**Comment by KevinLaMS** [comment]
This does not seem to install.
From what I can tell, this is an EXE that runs rather than installs.

**Comment by sebagomez** [comment]
It is, it does not have an installer. Must it have one? Could it be a powershell script that does the "installation"?

**Comment by denelon** [comment]
@sebagomez we don't have support for "stand alone installers" yet. https://github.com/microsoft/winget-cli/issues/182

**Comment by denelon** [comment]
We need to implement support for standalone executables, and the schema needs to be updated.

**Pull request closed without merging**
