### PR TITLE
New package: Datev.Sicherheitspaketcompact version 7.66

### PR DESCRIPTION
**Pull request by hra42**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150377)

### CODE REVIEW

**Comment by HRA42** [comment]
why does it run into a timeout?

I don't get whats wrong, the installer runs fine on my machine within 3 minutes :/

image

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-04-21 11:27:45.752 [CLI ] ShellExecute installer failed: 2147942487

(Automated response - build 877.)

**Comment by stephengillie** [comment]
Hi @HRA42, 

> Automatic Validation ended with:
> 
> > Installation failed with exit code -1978335226
> > 2024-04-21 11:27:45.752 [CLI ] ShellExecute installer failed: 2147942487
> 
> (Automated response - build 877.)

Manual Validation ended with the same result. Running the installer manually, it downloads and installs many dependencies - does the silent installer do the same, or should these be added to this manifest as package dependencies?

image

The two I caught appear to be `Microsoft.DotNet.DesktopRuntime.6` and I believe `Microsoft.VCRedist.2015+.x64`. But adding these as dependencies didn't change the exit code.

**Comment by HRA42** [comment]
How do you run the manual validation? The application has many dependencies, the 2 you caught are in there and a Kobel san Smart Card Driver. There is lot of other software bundelt in there too. The silent installer should do exactly the same from my experience.

If you could give short guidance on the manual install process I'll check from there.

**Comment by stephengillie** [comment]
Manual Validation is performed on a new and freshly-updated version of Windows 10 or 11 - downloaded with the Hyper-V Quick Create application, speedrun the OOBE, and install all Windows Updates, Microsoft Store updates, and Defender updates. 
- From there I have a [set of scripts](https://github.com/microsoft/winget-pkgs/pull/131556) (becoming an application) which handles the VM lifecycle - including the full manual validation cycle. 

Installing in a Windows Sandbox might give a similar perspective. Either one should show these errors and allow for dependency troubleshooting.

**Pull request closed without merging**
