### PR TITLE
Mozilla.Firefox v99.0 nb-NO InstallerLocale + ProductCodes fix

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/57157)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
@jedieaston you can probably look over this one too
I've used Nullsoft as the InstallerType for the nb-NO version because BCUninstaller claims the installed installer is, however someone said the Firefox exe is not Nullsoft, but could that be because its wrapped as something else too?

**Comment by OfficialEsco** [comment]
@jedieaston you can probably look over this one too
I've used Nullsoft as the InstallerType for the nb-NO version because BCUninstaller claims the installed installer is, however someone said the Firefox exe is not Nullsoft, but could that be because its wrapped as something else too?

**Review by jedieaston — APPROVED** [review]
You are right, the exe installers are generated via Nullsoft: https://searchfox.org/mozilla-central/source/browser/installer/windows/nsis

We need to fix it for the rest of them too.

**Review by jedieaston — APPROVED** [review]

**Pull request merged**
