### PR TITLE
nvQuickSite 2.0.0

### PR DESCRIPTION
**Pull request by david-poindexter**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/4982)

### CODE REVIEW

**Comment by david-poindexter** [comment]
We would love to know how to prevent this!  😃👍

**Comment by KevinLaMS** [comment]
I cannot get this one to install   I get a 1603 error whether admin or not.

image

**Comment by david-poindexter** [comment]
@KevinLaMS unfortunately, we discovered an issue with our installer for 2.0.0.  It only works if a previous version of nvQuickSite was installed prior to the installation of 2.0.0.  

Since we were using the old Microsoft installer (vdproj), and we have seen reports of others having similar issues with the recent Windows updates, we decided to rewrite our installer using Wix.  The new installer works like a charm, but we have yet to make a PR for nvQuickSite 2.1.0 yet.  Since we had two pending PRs (this one and one for v1.4.2) still not approved, we weren't sure if we should continue submitting given the code signing issues.

Let us know and we'll be happy to submit a PR for v2.1.0.  In the meantime, the workaround is to install 1.4.2 (see #4981) and then install 2.0.0.

**Comment by david-poindexter** [comment]
FYI...we have created a PR for nvQuickSite 2.1.0 - see #5359 

I am not sure how that plays into this PR, but I thought I would mention it just in case it helps.  Also, the PR for nvQuickSite 1.4.2 was just merged today - see #4981

**Comment by david-poindexter** [comment]
I'll get this updated as soon as possible.￼

**Comment by denelon** [comment]
@david-poindexter thanks so much for persisting here. Switching installer tech is often frustrating. We tend to see the best results in the Windows Package Manager with MSIX, then MSI, then .exe. Unfortunately, the code signing parts of the process tend to be complex and not free.

**Comment by david-poindexter** [comment]
Thank you. I honestly think we should just close this one because we have since released a newer version that resolves the issue. It is already published on winget.  It is using the WIX installer.

**Pull request closed without merging**
