### PR TITLE
New version: commercialhaskell.stack version 2.7.5

### PR DESCRIPTION
**Pull request by ghost**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/50344)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by vedantmgoyal2009** [comment]
I think I should check the automation. These are the GitHub packages that should have been upgraded by the automation.

**Comment by ItzLevvie** [comment]
> I think I should check the automation. These are the GitHub packages that should have been upgraded by the automation.

It wasn't added because it hit the API limit

**Comment by vedantmgoyal2009** [comment]
I see. I think a delay needs to be added since the GitHub Runners are lightning fast⚡

**Comment by vedantmgoyal2009** [comment]
@itzlevvie should we remove old versions of onedrive?

**Pull request merged**
