### PR TITLE
Update D:\Git\winget-pkgs\manifests\j\JakobDev\jdAppStreamEdit\7.0

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114870&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
Hmm

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -2145844819 
> 2023-08-03 08:24:53.024 [CORE] Download request failed. Returned status: 429 
> 2023-08-03 08:24:53.024 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(67)\WindowsPackageManager.dll!00007FFE8DC51D0B: (caller: 00007FFE8DC52129) Exception(2) tid(1040) 801901AD     Msg:[Download request status is not success.]  
> 2023-08-03 08:24:53.137 [CLI ] Failed to download, waiting a bit and retry. Url: https://sourceforge.net/projects/jdappstreamedit/files/7.0/jdAppStreamEdit-7.0-WindowsInstaller.exe/download 

(Rate limiting)

**Comment by stephengillie** [comment]
Manual Validation has stalled at 21.0 MB / 27.0 MB:
image

**Comment by Trenly** [comment]
Retrying to see if rate limit has been resolved

**Pull request merged**
