### PR TITLE
BinaryFortress.DisplayFusion version 10.0.0.0

### PR DESCRIPTION
**Pull request by zanix**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/106398)

### CODE REVIEW

**Comment by zanix** [comment]
@microsoft-github-policy-service agree

**Comment by zanix** [comment]
I don't understand what the error is. I have tried this manifest locally and it installs. The pipeline details don't seem to have any useful info. I'm not sure what to do.

**Comment by Trenly** [comment]
> 2023-05-09 21:05:43.998 [CORE] Download request failed. Returned status: 429

**Comment by zanix** [comment]
HTTP 429 is too many requests, so does that mean the download URL is throttling the tests?

**Comment by Trenly** [comment]
> HTTP 429 is too many requests, so does that mean the download URL is throttling the tests?

I think that may be the case. When I try to download and install on my machine, it freezes halfway, so it seems likely that it's on the Publishers side.  

I'm sure @stephengillie will take a look and see if this needs an exception

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -2145844819 
> 2023-05-10 10:35:28.857 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(267)\WindowsPackageManager.dll!585586A6: (caller: 58558E35) Exception(1) tid(bcc) 80D02002  2023-05-10 10:35:29.078 [CORE] Download request failed. Returned status: 429 
> 2023-05-10 10:35:29.078 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(67)\WindowsPackageManager.dll!5851A1C4: (caller: 5851A6D1) Exception(2) tid(bcc) 801901AD     Msg:[Download request status is not success.]  
> 2023-05-10 10:35:29.079 [CLI ] Failed to download, waiting a bit and retry. Url: https://binaryfortressdownloads.com/Download/BFSFiles/101/DisplayFusionSetup-10.0.exe 
> 2023-05-10 10:36:29.756 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(267)\WindowsPackageManager.dll!585586A6: (caller: 58558E35) Exception(3) tid(bcc) 80D02002  
> 2023-05-10 10:36:29.822 [CORE] Download request failed. Returned status: 429 
> 2023-05-10 10:36:29.822 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(67)\WindowsPackageManager.dll!5851A1C4: (caller: 5851A6D1) Exception(4) tid(bcc) 801901AD     Msg:[Download request status is not success.]

**Comment by zanix** [comment]
This seems to be stuck. The tests are in their 3rd run since retrying and they are erroring out after a couple hours.

**Comment by stephengillie** [comment]
> This seems to be stuck. The tests are in their 3rd run since retrying and they are erroring out after a couple hours.

It's a loop:
1. Something about the package is causing the Automated Validation pipeline to hit its 3 hour timeout.
2. The `Internal-Error-Dynamic-Scan` label is applied.
3. Wingetbot runs a "clean-up" to re-run some failures, just in case the previous fail was ephemeral.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
