### PR TITLE
New Version: OpenStenoProject.Plover 4.0.0rc2

### PR DESCRIPTION
**Pull request by RAOEUS**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? https://github.com/microsoft/winget-pkgs/issues/168556

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `/manifests/o/OpenStenoProject/Plover/4.0.0rc2/` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/168557)

### CODE REVIEW

**Comment by RAOEUS** [comment]
@microsoft-github-policy-service agree

**Comment by RAOEUS** [comment]
Is there anything I must do to fix that `validation-executable-error`?

**Comment by RAOEUS** [comment]
@stephengillie , please let me know if there is anything else I must do on my end. Thanks for your time!

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files\Open Steno Project\Plover 4.0.0rc2\plover.exe returned exit code: -1073741515
> Executable C:\Program Files\Open Steno Project\Plover 4.0.0rc2\plover_console.exe returned exit code: -1073741515
> Executable C:\Program Files\Open Steno Project\Plover 4.0.0rc2\data\python.exe returned exit code: -1073741515
> Executable C:\Program Files\Open Steno Project\Plover 4.0.0rc2\data\pythonw.exe returned exit code: -1073741515
> Executable C:\Program Files\Open Steno Project\Plover 4.0.0rc2\data\Lib\site-packages\pip\_vendor\distlib\t32.exe returned exit code: 1
> Executable C:\Program Files\Open Steno Project\Plover 4.0.0rc2\data\Lib\site-packages\pip\_vendor\distlib\t64.exe returned exit code: 1
> Executable C:\Program Files\Open Steno Project\Plover 4.0.0rc2\data\Lib\site-packages\pip\_vendor\distlib\w32.exe returned exit code: 1
> Executable C:\Program Files\Open Steno Project\Plover 4.0.0rc2\data\Lib\site-packages\pip\_vendor\distlib\w64.exe returned exit code: 1
> Executable C:\Program Files\Open Steno Project\Plover 4.0.0rc2\data\Lib\site-packages\setuptools\cli-32.exe returned exit code: 2
> Executable C:\Program Files\Open Steno Project\Plover 4.0.0rc2\data\Lib\site-packages\setuptools\cli-64.exe returned exit code: 2
> Executable C:\Program Files\Open Steno Project\Plover 4.0.0rc2\data\Lib\site-packages\setuptools\cli.exe returned exit code: 2
> Executable C:\Program Files\Open Steno Project\Plover 4.0.0rc2\data\Lib\site-packages\setuptools\gui-32.exe returned exit code: 2
> Executable C:\Program Files\Open Steno Project\Plover 4.0.0rc2\data\Lib\site-packages\setuptools\gui-64.exe returned exit code: 2
> Executable C:\Program Files\Open Steno Project\Plover 4.0.0rc2\data\Lib\site-packages\setuptools\gui.exe returned exit code: 2

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 888.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
