### PR TITLE
Action to auto sync fork

### PR DESCRIPTION
**Pull request by OpenWaygate**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

This pr add a new action to sync fork with upstream(`microsoft/winget-pkgs`) schedually.

This action will not be triggered in `microsoft/winget-pkgs`, and will run every 3 days only in forks.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161791)

### CODE REVIEW

**Comment by OpenWaygate** [comment]
I have test it in my fork and it works.

https://github.com/eat-pray-ai/winget-pkgs/actions/runs/9824958955

**Comment by Trenly** [comment]
Thanks for your contribution @OpenWaygate. At this point in time, I don't believe we need a specific action to sync forks. This could also cause additional significant load on the GitHub backend as there are more than 4,500 forks at this time. The tooling that would require a fork to be synced such as WinGetCreate or YamlCreate now either sync the fork automatically, or use detached references to avoid any issues caused by forks being out of sync. 

###### Close with reason: Stale PR;

**Comment by ItzLevvie** [comment]
Close with reason: Stale pull request;

**Pull request closed without merging**
