### PR TITLE
Add Kingsoft/WPSOffice

### PR DESCRIPTION
**Pull request by zirnc**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1339)

### CODE REVIEW

**Comment by MarNicGit** [comment]
Looks like the installer validation has been stuck in progress for _eleven hours and counting._

**Comment by ChungZH** [comment]
?

**Pull request closed without merging**
