### PR TITLE
New version: MillerPuckette.PureData version 0.54-0

### PR DESCRIPTION
**Pull request by Lucarda**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/111566&drop=dogfoodAlpha

### CODE REVIEW

**Comment by Lucarda** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
The silent installer switches aren't resulting in an unattended installation:
image

**Comment by stephengillie** [comment]
Hi @Lucarda,

Does this package have silent installer switches? The installer doesn't respond to common query switches like `/?`.

**Comment by Lucarda** [comment]
Hi @stephengillie

thanks for the contact :)

I think i introduced the bug here

https://github.com/pure-data/pure-data/blob/master/msw/pd.nsi?plain=1#L85-L88

which forces the installer to be interactive. I'll move away the call `SetSilent normal` from the `!macro ONINIT` function.  

until there's a fix for that I won't make a new PR.

at least this is what i think is failing.

**Comment by Lucarda** [comment]
i'm closing this one until i got the fix on upstream.

thanks.

**Pull request closed without merging**
