### PR TITLE
Add AXIS Camera Station Preview 0.2133.061

### PR DESCRIPTION
**Pull request by AlexanderAlfven**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with winget validate --manifest <path>? 
- [ ] Have you tested your manifest locally with winget install --manifest <path>?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: <path> is the name of the directory containing the manifest you're submitting.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/25138)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
cc @AlexanderAlfven: could you please sign the CLA? I believe it's important because it wouldn't be in the template if it wasn't. Thanks.

**Comment by AlexanderAlfven** [comment]
> cc @AlexanderAlfven: could you please sign the CLA? I believe it's important because it wouldn't be in the template if it wasn't. Thanks.

I would require a (printable) paper copy of the agreement to do so.
https://cla.opensource.microsoft.com/ not provide such as option (just a preview); and I'm unsure of a suitable contact person to acquire one.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Couldn't you just sign the digital version over at https://cla.opensource.microsoft.com/microsoft/winget-pkgs? It requires no PDF.

If that's not an option for you, you'll have to ask @denelon about it.

**Comment by AlexanderAlfven** [comment]
> Couldn't you just sign the digital version over at https://cla.opensource.microsoft.com/microsoft/winget-pkgs? It requires no PDF.
> 
> If that's not an option for you, you'll have to ask @denelon about it.

Unfortunately not an option. I'll need to query @denelon then.

**Comment by denelon** [comment]
@AlexanderAlfven I will inquire about a hard copy (paper) version of the CLA.

**Comment by denelon** [comment]
@AlexanderAlfven I reached out to the Microsoft Open Source team. At present there is no support for executing a physically signed CLA agreement. I understand this will prevent you from being able to submit a manifest. As you have already done the work to generate a valid manifest, you could create an Issue in the repository referencing this PR so another community member could submit a manifest. That would at least unblock the submission for this package.

**Comment by denelon** [comment]
@AlexanderAlfven is the restriction based on a business policy? I'd like to understand the scenario or specific restrictions a bit more so I can share with the team.

**Comment by AlexanderAlfven** [comment]
> is the restriction based on a business policy? I'd like to understand the scenario or specific restrictions a bit more so I can share with the team.

@denelon Its a business policy restriction. We require our own copies of agreements we sign.

**Pull request closed without merging**
