### PR TITLE
archwsl 20.11.25.0

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/5331)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
image

this package seems to install but results in an error.  I think this is  a case where we have the blocking work item to support other error codes.

**Comment by KevinLaMS** [comment]
: Support non-zero exit codes as success · Issue #137 · microsoft/winget-cli (github.com)

**Comment by oxygen-dioxide** [comment]
> image
> 
> this package seems to install but results in an error. I think this is a case where we have the blocking work item to support other error codes.

This is archwsl PR. You are replying to me in the wrong PR.

**Comment by denelon** [comment]
We now support non-zero exit codes in the new v1.0 manifest schema :smile:

**Pull request closed without merging**
