### PR TITLE
BenCoeppPublishing.SiffDesktop version 1.0.0.4

### PR DESCRIPTION
**Pull request by bencoepp**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140757)

### CODE REVIEW

**Comment by BenCoepp** [comment]
Issue was found, the manifest for the msix package had the version 1.0.0.3 not 1.0.0.4 this was fixed. Pipeline should now hopefully run without issue.

**Comment by BenCoepp** [comment]
> Automatic Validation ended with:
> 
> > 2024-02-23T17:27:18.7766666Z ****************************************************************************************
> 
> (Automated response - build 808.)

@stephengillie sorry for asking, but i am not quite sure what i should do now? Or to be presise how I can restart the validation pipeline

**Comment by stephengillie** [comment]
> Issue was found, the manifest for the msix package had the version 1.0.0.3 not 1.0.0.4 this was fixed. Pipeline should now hopefully run without issue.

Ah, this was an external fix? Does the installer hash need to be updated? 

Any commit will restart the pipeline, or feel free to @ me.

**Pull request closed without merging**
