### PR TITLE
Remove version: Calibre 6.20.0

### PR DESCRIPTION
**Pull request by pxwiz**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/109634&drop=dogfoodAlpha

### CODE REVIEW

**Comment by russellbanks** [comment]
What's the reason for removal?

**Review by stephengillie — APPROVED** [review]

**Comment by russellbanks** [comment]
> > What's the reason for removal?
> 
> It appears to have been removed by the publisher: image

That's because they keep historic releases on their website, and only the latest on GitHub

https://download.calibre-ebook.com

**Comment by pxwiz** [comment]
@russellbanks @stephengillie, is there a standard policy on number of versions retained in the codebase? 
There are 18 old versions of calibre in that package.

**Comment by russellbanks** [comment]
> is there a standard policy on number of versions retained in the codebase?

No, there no limit or policy on the number of versions

**Pull request merged**
