### PR TITLE
New version: WestWind.MarkdownMonster version 3.2.10.0

### PR DESCRIPTION
**Pull request by kkbruce**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/149272)

### CODE REVIEW

**Comment by kkbruce** [comment]
https://www.microsoft.com/en-us/wdsi/submission/13ea723d-a7c5-41ec-81e8-e1951d2fb0f4

The scan result is passed. I don't have any idea.

**Comment by stephengillie** [comment]
> URI: https://github.com/RickStrahl/MarkdownMonsterReleases/raw/master/v3/v3.2/MarkdownMonsterSetup-3.2.10.exe, Validation result: Failed, Report feedback: https://feedback.smartscreen.microsoft.com/feedback.aspx?v=6&t=16&result=block&type=top&url=aHR0cHM6Ly9naXRodWIuY29tL1JpY2tTdHJhaGwvTWFya2Rvd25Nb25zdGVyUmVsZWFzZXMvcmF3L21hc3Rlci92My92My4yL01hcmtkb3duTW9uc3RlclNldHVwLTMuMi4xMC5leGU%3D

**Comment by kkbruce** [comment]
> URI: https://github.com/RickStrahl/MarkdownMonsterReleases/raw/master/v3/v3.2/MarkdownMonsterSetup-3.2.10.exe, Validation result: Failed, Report feedback: https://feedback.smartscreen.microsoft.com/feedback.aspx?v=6&t=16&result=block&type=top&url=aHR0cHM6Ly9naXRodWIuY29tL1JpY2tTdHJhaGwvTWFya2Rvd25Nb25zdGVyUmVsZWFzZXMvcmF3L21hc3Rlci92My92My4yL01hcmtkb3duTW9uc3RlclNldHVwLTMuMi4xMC5leGU%3D

I can't possibly report on behalf of Github, but as an individual, I've reported as much as I can.

**Comment by kkbruce** [comment]
https://www.virustotal.com/gui/file/b1a133c5681ee1c93833fea60541643a34ccbd4489e6b3a0f8de1ff0d4effe50

We only know that we've been blocked, but we don't know the reason, such as suspected trojans or viruses. We're powerless.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
