### PR TITLE
Telegrafer.Telegrafer version 0.0.2

### PR DESCRIPTION
**Pull request by Timo-Weike**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/98997)

### CODE REVIEW

**Comment by Trenly** [comment]
> This setup requires the x64 .NET Runtime version 6.0.0.  Please install the .NET Runtime and run this setup again.  The .NET Runtime can be obtained from the web.  Would you like to do this now?

From the logs, this has a dependency

**Comment by Timo-Weike** [comment]
@Trenly where can I find those logs to find the issue that occures during installation.

**Comment by Trenly** [comment]
> @Trenly where can I find those logs to find the issue that occures during installation.

Those logs were from me testing in a local VM with just windows installed.

**Comment by Timo-Weike** [comment]
Hmm, I am a bit disappointed in the validation pipelines that they does not output more helpful logs.
I sadly currently don't have a second environment to test the installer in.

**Comment by Trenly** [comment]
> Hmm, I am a bit disappointed in the validation pipelines that they does not output more helpful logs.
> I sadly currently don't have a second environment to test the installer in.

On failed installs the validation pipeline does provide the installation logs as one of the artifacts available for download; I just didn’t happen to use those in this case

**Comment by Timo-Weike** [comment]
Well I think the problem probably is that the Binary is not signed...
Will fix that in the future.

**Comment by Timo-Weike** [comment]
> > Hmm, I am a bit disappointed in the validation pipelines that they does not output more helpful logs.
> > I sadly currently don't have a second environment to test the installer in.
> 
> On failed installs the validation pipeline does provide the installation logs as one of the artifacts available for download; I just didn’t happen to use those in this case

Okay, the dotnet 6 runtime still seems to not be installed

> This setup requires the x64 .NET Runtime version 6.0.0.  Please install the .NET Runtime and run this setup again.  The .NET Runtime can be obtained from the web.  Would you like to do this now?

Despite me [having added ](https://github.com/microsoft/winget-pkgs/pull/98997/commits/d79cd9ccedbc08bdb0b755af39956d78be113798#diff-2c434c3e1dccab32190b9f3e996aa1584cceb8a2454b80c7d51c5bb3b6bbc668:~:text=Dependencies%3A,DotNet.DesktopRuntime.6) the `Microsoft.DotNet.DesktopRuntime.6` as a dependency.
~~~
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.6
~~~

Or is this wrong to declare a dependency like this?

**Comment by Trenly** [comment]
> ```
> Dependencies:
>   PackageDependencies:
>   - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.6
> ```
> 
> Or is this wrong to declare a dependency like this?

That is the correct way to declare them, but Dependencies are still an experimental feature. Until the dependencies feature is released to stable, the validation pipeline won't be able to install them. If you leave this PR open, it will be re-run once dependencies are stable, but is blocked until then.

**Comment by Timo-Weike** [comment]
> > ```
> > Dependencies:
> >   PackageDependencies:
> >   - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.6
> > ```
> > 
> > Or is this wrong to declare a dependency like this?
> 
> That is the correct way to declare them, but Dependencies are still an experimental feature. Until the dependencies feature is released to stable, the validation pipeline won't be able to install them. If you leave this PR open, it will be re-run once dependencies are stable, but is blocked until then.

Would it be valid to create a custom exe or script (PowerShell or CMD) that also checks and installs the net 6 runtime if necessary?

Also what is a reasonable expectation when the dependency feature is stable?

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335226 
> 2023-12-27 12:55:48.573 [CLI ] ShellExecute installer failed: 1603 INFO   : [12/27/2023 12:55:48:376] [VsdLaunchConditions                     ]: MsiSetPropertyW - Setting property 'HideFatalErrorForm' to 'TRUE'. ERROR  : [12/27/2023 12:55:48:376] [VsdLaunchConditions                     ]: Custom Action failed with code: '1603' CustomAction VSDCA_VsdLaunchConditions returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox) Property(S): ErrorDialog = ErrorDialog Property(S): HideFatalErrorForm = TRUE MSI (s) (44:48) [12:55:48:454]: Product: Telegrafer -- Installation failed. MSI (s) (44:48) [12:55:48:454]: Windows Installer installed the product. Product Name: Telegrafer. Product Version: 1.0.0. Product Language: 1033. Manufacturer: Telegrafer. Installation success or error status: 1603.

(Automated response - build 498.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
