### PR TITLE
New Package: Resolume.Avenue version 7.15.0.23381

### PR DESCRIPTION
**Pull request by sandercox**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/110549&drop=dogfoodAlpha

### CODE REVIEW

**Comment by Trenly** [comment]
[Policy] Needs Attention

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/issues/111634

**Comment by sandercox** [comment]
Made small update to update publisher like I did on Resolume.Arena package as that was required for meet review.

As I just pushed new version of Arena I can also do this for Avenue but as these two are tightly related wanted to get the 7.15 version in first before doing that.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
