### PR TITLE
PathofBuildingCommunity.PathofBuildingCommunity version 2.42.0

### PR DESCRIPTION
**Pull request by orange-lion**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/147435)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\Validator\AppData\Roaming\Path of Building Community\Update.exe returned exit code: -1073741515

(Automated response - build 876.)

**Comment by orange-lion** [comment]
> Automatic Validation ended with:
> 
> > Executable C:\Users\Validator\AppData\Roaming\Path of Building Community\Update.exe returned exit code: -1073741515
> 
> (Automated response - build 876.)

Are you able to provide any insight into how the validation process works and how this would be triggered? I just installed from manifest in a sandbox and had no issues through the install process or while checking for updates through the application.

**Comment by stephengillie** [comment]
Hi @orange-lion,

Validation is a console process (I believe) which performs pre-install checks, installs the application, launches any EXEs it can find, performs a Defender scan, and uploads the log output to the ADO Pipeline. The exit code here should be the application's exit code logged by the console process. (Then extracted and posted in PR by another automated process.)

In a Windows 10 VM, it installs and launches normally. 
image

**Review by stephengillie — APPROVED** [review]

**Comment by orange-lion** [comment]
Hey @stephengillie,

Thanks for the info! 

>  launches any EXEs it can find, 

I just went and ran the Update.exe directly (since the initial error seemed related) and got an error due to msvcp100.dll missing. I'm unsure if that caused the issue with this PR or how/why it doesn't present the error when updating in-app, but I'll keep it in mind for next time.

**Pull request merged**
