### PR TITLE
New package: Task.Task version 3.21.0

### LINKED ISSUE #99032: [Package Request]: Task
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not a script file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Task
Publisher Url: https://github.com/go-task
Package Name: Task
Description: A task runner / simpler Make alternative written in Go
Package Version: 3.21.0
Installer URL: https://github.com/go-task/task/releases/download/v3.21.0/task_windows_amd64.zip

Current Package Identifier (for new versions):

### PR DESCRIPTION
**Pull request by mshaugh**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

* Resolves #99032

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/99033)

### CODE REVIEW

**Review by mdanish-kh — APPROVED** [review]

**Comment by stephengillie** [comment]
This package is expecting a task file or `--init`:
```
C:\Users\user\AppData\Local\Microsoft\WinGet\Links\task.exe
task: No Taskfile found in "\\172.18.128.1\ManVal\vm\2" (or any of the parent directories). Use "task --init" to create a new one
```

**Pull request merged**
