### PR TITLE
New version: Stellarium.Stellarium version 1.0 [FP-D]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | Stellarium | Stellarium 1.22.3    |
| Version     | 1.0     | 1.22.3 |
| Publisher   | Stellarium team   | Stellarium team      |
| ProductCode |           | Stellarium_is1    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://bittu.eu.org/docs/wpa-intro) in workflow run [3338](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/3164927831>)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Comment by vedantmgoyal2009** [comment]
bump

**Comment by vedantmgoyal2009** [comment]
@denelon Blocking Issue.

**Pull request merged**
