### PR TITLE
WindscribeLimited.Windscribe version 2.0.2.10

### PR DESCRIPTION
**Pull request by Masamune3210**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/33166)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Interesting, have you taken a look at what's being done to the installer switches for Windscribe in Chocolately? Perhaps that might help?

https://github.com/joachimschmidt557/chocolatey-packages-manual-automatic/blob/master/manual/windscribe/tools/chocolateyinstall.ps1#L17

This PR doesn't show up in Control Panel and doesn't leave any executable files, so it probably hasn't installed properly. Doesn't leave any files in Program Files or in `%LOCALAPPDATA%`.

**Comment by Masamune3210** [comment]
Noticed that as well on my main machine but haven't had the chance to set up a new VM, lost mine when I wiped to install fresh 11. Figured it was just my machine being weird since I had it already installed. According to their changelog they just added the silent flag with the latest version, but didn't see anything about any other flags

**Comment by Masamune3210** [comment]
I just tried literally every way I can think of to call the silent feature or any other of the flags but none of them are working. Either I'm missing some magical way to call these, or their switches just don't seem to work, launching the installer without any switches works just fine so its not a installer corruption issue

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
>Noticed that as well on my main machine but haven't had the chance to set up a new VM, lost mine when I wiped to install fresh 11. Figured it was just my machine being weird since I had it already installed. According to their changelog they just added the silent flag with the latest version, but didn't see anything about any other flags

Looks like it's a known issue for the stable release: https://github.com/joachimschmidt557/chocolatey-packages-manual-automatic/issues/14

The alpha/beta version seems to have it: https://assets.totallyacdn.com/desktop/beta/Windscribe_2_3_build11_beta.exe

**Comment by Masamune3210** [comment]
Welp, guess will just have to wait until the fix hits release unless someone else had an idea

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
You can set the PR in draft for now until a fix is available.

**Pull request closed without merging**
