### PR TITLE
Updated version: 0.1.2-Test

### PR DESCRIPTION
**Pull request by ghost**
Updated the version 0.1.2-Test, DicomProxy from release pipeline

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/17601)

### CODE REVIEW

**Comment by ramsoft-inc** [comment]
@ItzLevvie @KevinLaMS Usually how much time takes to approve into merge.

**Comment by denelon** [comment]
@ramsoft-inc our moderators are reviewing hundreds of PRs. It really depends on their time and how many other PRs are ready for review.

**Comment by denelon** [comment]
This looks like it's for an earlier version of the package. Is this intentional?

**Comment by ramsoft-inc** [comment]
@denelon  Yes, this is intentional. Thanks

**Review by denelon — APPROVED** [review]

**Pull request merged**
