### PR TITLE
New package: Morgen.MorgenCalendar version 3.5.1

### PR DESCRIPTION
**Pull request by ptsouchlos**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161939)

### CODE REVIEW

**Comment by DeveloperPaul123** [comment]
This package was auto generated by a tool. Let me know if there's anything I can do to help fix the issues.

**Comment by DeveloperPaul123** [comment]
Local and Windows Sandbox validation succeed for me.

```powershell
PS <winget-pkgs> winget validate --manifest .\manifests\m\Morgen\MorgenCalendar\3.5.1
Manifest validation succeeded.
```
WindowsSandboxClient_2024-07-10_15-52-27

WindowsSandboxClient_2024-07-10_15-52-37

**Comment by SpecterShell** [comment]
https://github.com/microsoft/winget-pkgs/pull/161094

**Comment by DeveloperPaul123** [comment]
Whoops, seems I completely missed that there is already the `Morgen.Morgen` package. Sorry about that!

**Pull request closed without merging**
