### PR TITLE
YamlCreate Git Variable reference is not valid 

### PR DESCRIPTION
**Pull request by OfficialEsco**
https://github.com/microsoft/winget-pkgs/pull/21213#issuecomment-881658525
https://github.com/microsoft/winget-pkgs/pull/21213#issuecomment-881663162

Give me a moment to validate this since my test got ruined..

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/21223)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
of course

**Comment by OfficialEsco** [comment]
That fixed it #21225 but still this issue
image

@Trenly ideas?

**Comment by Trenly** [comment]
> That fixed it #21225 but still this issue
> image
> 
> @Trenly ideas?
> 
> image

Looks like I made a mistake on Line 80

**Comment by OfficialEsco** [comment]
> > That fixed it #21225 but still this issue
> > image
> > @Trenly ideas?
> > image
> 
> Looks like I made a mistake on Line 80

so `default {Write-Host > exit}` to `default {exit}` as before?

**Comment by Trenly** [comment]
> > > That fixed it #21225 but still this issue
> > > image
> > > @Trenly ideas?
> > > image
> > 
> > 
> > Looks like I made a mistake on Line 80
> 
> so `default {Write-Host > exit}` to `default {exit}` as before?
> edit: just tested on Ubisoft without submitting and it didn't create a exit file..

We want the Write-Host in there so people can see their keypress that actually exited. I accidentally used `>` instead of `;` to join the commands.  The PR I mentioned (#21228) should resolve the issue as well as incorporate the change you needed for the git variable reference

**Comment by OfficialEsco** [comment]
ooo oki

**Pull request closed without merging**
