### PR TITLE
Add ClamWin 0.99.4

### PR DESCRIPTION
**Pull request by latere-a-latere**
Part of https://github.com/microsoft/winget-pkgs/issues/897

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1434)

### CODE REVIEW

**Comment by MarNicGit** [comment]
Looks like SourceForge timed out:
```
-----------------------------------------------------
Installer Availability
-----------------------------------------------------
Status: Started

6/1/2020 8:27:38 AM
Status: Completed
Result: Failed
Error occurred during installer copy from https://sourceforge.net/projects/clamwin/files/clamwin/0.99.4/clamwin-0.99.4-setup.exe/download.
 A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

6/1/2020 8:27:45 AM

****************************************************************************************
Installer Validation
****************************************************************************************
Status: Completed
##[error] Result: Failed
```

Can someone retrigger the bot?

**Comment by SoftCreatR** [comment]
@MarNicGit Try that: https://github.com/microsoft/winget-pkgs/issues/1588#issuecomment-639263718

**Comment by MarNicGit** [comment]
@SoftCreatR Seems like that did the trick. Is there a big difference between ammending the commit and force pushing it compared to simply pushing an empty commit? I tend to do this a lot:

```
git commit --allow-empty -m "Retriggering bot"
git push
```

**Review by ghost — APPROVED** [review]
Validation has completed

**Comment by SoftCreatR** [comment]
@marnicgit Nah, that's fine too.

**Pull request merged**
