### PR TITLE
Add Foobar2000 versions "1.6-beta-4"

### PR DESCRIPTION
**Pull request by koumaza**
Test of `winget install -m 1.5.5-beta-5.yaml` was successful.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2092)

### CODE REVIEW

**Comment by denelon** [comment]
Downloading https://www.foobar2000.org/files/d77e1178cd09384a637385a1768d94ad/foobar2000_v1.6_beta_4.exe
  6.95 KB
Installer hash verification failed. Continue? (Y|N)
N
Canceled; Installer hash mismatch

**Comment by denelon** [comment]
@koumaza I don't see how to run or remove the program after installation. Can you help me to understand how to validate the program installed and how to remove it?

**Comment by koumaza** [comment]
In my case, it failed in the normal env, but succeeded in the sandbox env.
This is my guess, reason for failure under normal env is that silent installation does not support upgrade.

<details><summary>Sandbox screenshot</summary>

image
</details>

**Comment by denelon** [comment]
@koumaza do you know the publisher/author? Maybe they can take a look and help.

**Comment by koumaza** [comment]
@denelon It seems they have a form
https://hydrogenaud.io/index.php?board=28.0

**Comment by denelon** [comment]
https://hydrogenaud.io/index.php?topic=119506.0

**Comment by koumaza** [comment]
>hydrogenaud.io/index.php?topic=119506.0
>[Reply #1](https://hydrogenaud.io/index.php?topic=119506.msg985339#msg985339)
>>The website is designed to prevent hotlinking the downloads. I was hoping Peter himself would have commented here. But this project's income comes solely from the advertisement money so he may not be too happy with third parties trying to circumvent that.

Closes the PR as a result of respect for their survival of the project.

**Pull request closed without merging**
