### PR TITLE
Add version: Easeware.DriverEasy version 5.8.0

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/99786)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
There is no duplicate repository. @Trenly Please check Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change? Yes. wingetbot did not report that. I filter https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+wingetbot

**Comment by stephengillie** [comment]
This is basically an update to https://github.com/microsoft/winget-pkgs/pull/99368 which removes the 4th tuple from the version.

**Comment by Trenly** [comment]
> This is basically an update to #99368 which removes the 4th tuple from the version. Should the 4th tuple stay or go?

It should go because it isn’t written to the ARP entry, causing an upgrade loop

**Review by mdanish-kh — APPROVED** [review]

**Pull request merged**
