### PR TITLE
Remove version: ShaulEizikovich.vJoyDeviceDriver version 2.1.9.1

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/184065)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://downloads.sourceforge.net/project/vjoystick/Beta%202.x/2.1.9.1-160719/vJoySetup.exe 
Status Code: 200

(Automated message - build 897)

**Comment by stephengillie** [comment]
URL: https://downloads.sourceforge.net/project/vjoystick/Beta%202.x/2.1.9.1-160719/vJoySetup.exe 
Status Code: 200

(Automated message - build 897)

**Comment by stephengillie** [comment]
URL: https://downloads.sourceforge.net/project/vjoystick/Beta%202.x/2.1.9.1-160719/vJoySetup.exe 
Status Code: 200

(Automated message - build 897)

**Comment by stephengillie** [comment]
URL: https://downloads.sourceforge.net/project/vjoystick/Beta%202.x/2.1.9.1-160719/vJoySetup.exe 
Response status code does not indicate success: 403 (Forbidden).

(Automated message - build 897)

**Comment by ItzLevvie** [comment]
Close with reason: URL works;

**Pull request closed without merging**
