### PR TITLE
Remeha.service tool 7.3.31.0 93193d82 8cb4 4763 9d21 921d3c5847fd

### PR DESCRIPTION
**Pull request by TutkuSilaVuralEyovgeAlten**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141271)

### CODE REVIEW

**Comment by stephengillie** [comment]
> Possible duplicate package entry.
> 
> Similar installer SHA256 hash found in manifest:
> 
> * `InstallerSha256: b8b5c6cd159420b74f8fc30f90910de71944626df56bce3cc711af7b047c2867`
>   
>   * manifests\r\Remeha\ServiceTool\7.3.20.0

https://github.com/microsoft/winget-pkgs/pull/140973#issuecomment-1966209108

@TutkuSilaVuralEyovgeAlten, please also remove the incorrect version in another PR.

**Comment by TutkuSilaVuralEyovgeAlten** [comment]
> > Possible duplicate package entry.
> > Similar installer SHA256 hash found in manifest:
> > 
> > * `InstallerSha256: b8b5c6cd159420b74f8fc30f90910de71944626df56bce3cc711af7b047c2867`
> >   
> >   * manifests\r\Remeha\ServiceTool\7.3.20.0
> 
> [#140973 (comment)](https://github.com/microsoft/winget-pkgs/pull/140973#issuecomment-1966209108)
> 
> @TutkuSilaVuralEyovgeAlten, please also remove the incorrect version in another PR.

I just removed the wrong version in another PR.

**Comment by stephengillie** [comment]
I'm not able to find the other PR. Could you link to it?

**Comment by TutkuSilaVuralEyovgeAlten** [comment]
> I'm not able to find the other PR. Could you link to it?

You can find the PR via https://github.com/microsoft/winget-pkgs/pull/141429  (TutkuSilaVuralEyovgeAlten:Remeha.ServiceTool-7.3.20.0-9dee46a4-4f8c-4f9d-b1d5-5501aa7d1e25)

**Comment by stephengillie** [comment]
> You can find the PR via #141429 (TutkuSilaVuralEyovgeAlten:Remeha.ServiceTool-7.3.20.0-9dee46a4-4f8c-4f9d-b1d5-5501aa7d1e25)

Thanks. This PR appears to add this version again - it looks like a copy of this PR. Was there a PR to remove the incorrect manifest for version `7.3.20.0`?

**Comment by TutkuSilaVuralEyovgeAlten** [comment]
> . That PR appears to add this version again - it looks like a copy of this PR. Was there a PR to remove the incor

I replaced that one with the copy of this PR. We can add duplicate label and close it.

**Comment by stephengillie** [comment]
> I replaced that one with the copy of this PR. We can add duplicate label and close it.

This is complete. 

The manifest with the wrong version number still needs to be removed. It could cause this package to have the "upgrade always available" bug. Our package manager compares an installed package against every manifest version, and I think it returns the lowest version. So users would update to `7.3.31.0` from this PR, but the other manifest would suggest that what's installed is `7.3.20.0`, and offer to upgrade to `7.3.31.0`.

**Review by stephengillie — APPROVED** [review]

**Comment by TutkuSilaVuralEyovgeAlten** [comment]
Hello, I deleted the branch. Thank you!

**Pull request merged**
