### PR TITLE
New version: Ferdium.Ferdium.Nightly version 6.7.1-nightly.8

### PR DESCRIPTION
**Pull request by Alphrag**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/134004)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Alphrag,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 570.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-15 01:58:24.796 [FAIL] Installer failed security check. Url: https://github.com/ferdium/ferdium-app/releases/download/v6.7.1-nightly.8/Ferdium-win-AutoSetup-6.7.1-nightly.8-ia32.exe Result: 0x80004005

(Automated response - build 570.)

**Comment by Alphrag** [comment]
@stephengillie Thanks for checking this out. I've had no trouble installing this version on my computer, and we haven't had any issues with security check before. So let's see if it resolves itself, otherwise I'll try to figure out what could be causing this.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
