### PR TITLE
New version: pizzaboxer.Bloxstrap version 2.0.0

### PR DESCRIPTION
**Pull request by pizzaboxer**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/97110)

### CODE REVIEW

**Comment by pizzaboxer** [comment]
@microsoft-github-policy-service agree

**Comment by sitiom** [comment]
https://github.com/microsoft/winget-pkgs/pull/92827#issuecomment-1369993178

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
> [#92827 (comment)](https://github.com/microsoft/winget-pkgs/pull/92827#issuecomment-1369993178)

This package may have accidentally become one of a select few where a pre-existing dependency continues to be allowed, despite the general block on dependencies.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @pizzaboxer,

This version requests to install the .NET Desktop Runtime, even when it's already installed on the system: 
image

Is there an installer switch to bypass this?

**Comment by sitiom** [comment]
> Hi @pizzaboxer,
> 
> This version requests to install the .NET Desktop Runtime, even when it's already installed on the system: image


Works for me, though. This is a generic error that just means it's not installed on the system.

**Comment by pizzaboxer** [comment]
> Hi @pizzaboxer,
> 
> This version requests to install the .NET Desktop Runtime, even when it's already installed on the system: image
> 
> Is there an installer switch to bypass this?

The installer is part of the application, which is made in .NET 6, so there's not really any way to get around it unfortunately.
This is strange, I have the x64 SDK installed on my PC and launching the x86 version works fine.

**Comment by stephengillie** [comment]
> The installer is part of the application, which is made in .NET 6, so there's not really any way to get around it unfortunately. This is strange, I have the x64 SDK installed on my PC and launching the x86 version works fine.

There was an issue with mixing dependency architectures on my end. Sorry for the concern.

**Pull request merged**
