### PR TITLE
Added Arch - GoACME.lego 4.15.0

### PR DESCRIPTION
**Pull request by BiosPlus**
Added missing arm arch source (arm7/32bit)

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/138491)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @BiosPlus,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 720.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-08 22:16:21.037 [FAIL] Installer failed security check. Url: https://github.com/go-acme/lego/releases/download/v4.15.0/lego_v4.15.0_windows_amd64.zip Result: 0x80004005

(Automated response - build 720.)

**Comment by BiosPlus** [comment]
The same URL literally passed 24 hours ago 😅

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
