### PR TITLE
Fix netsurf version

### PR DESCRIPTION
**Pull request by aaronliu0130**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----
The uninstall command exits before the user is able to click the uninstaller's confirmation button, though the confirmation dialog stays and confirming does successfully uninstall. Not sure why.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/94817)

### CODE REVIEW

**Comment by aaronliu0130** [comment]
Weird, I ran winget validate, hold on

**Comment by stephengillie** [comment]
For 1.4 manifests, we're monitoring for winget 1.4 to become the majority version among users. We're hopeful this will be soon, possibly in a few days. Sorry for any confusion.

**Comment by aaronliu0130** [comment]
Ah, ok. So we'll restart the workflow later?

**Comment by stephengillie** [comment]
> Ah, ok. So we'll restart the workflow later?

Yes. Several PRs are pending for this.

**Comment by aaronliu0130** [comment]
> The uninstall command exits before the user is able to click the uninstaller's confirmation button, though the confirmation dialog stays and confirming does successfully uninstall. Not sure why.

Could somebody give me some pointers about this? Looks like a standard NSIS uninstaller.

**Comment by stephengillie** [comment]
> > The uninstall command exits before the user is able to click the uninstaller's confirmation button, though the confirmation dialog stays and confirming does successfully uninstall. Not sure why.
> 
> Could somebody give me some pointers about this? Looks like a standard NSIS uninstaller.

Is this the Netsurf uninstaller's behavior? 

While we push for unattended installers, we're less strict about the uninstaller. Though we still prefer completely unattended uninstallation, if possible, a handful do require user interaction. I'm not sure, but Winget might use the installer switches on the uninstaller, expecting the same effect as with the installer. The uninstaller here might react in this unusual way if the switch combination were unexpected.

**Comment by aaronliu0130** [comment]
> I'm not sure, but Winget might use the installer switches on the uninstaller, expecting the same effect as with the installer.
The silent switches should work across NSIS. Regardless of that, the winget uninstall process exits before the uninstall is finished, which is very confusing.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
