### PR TITLE
Version/2.28.2

### PR DESCRIPTION
**Pull request by NickeManarin**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/11325)

### CODE REVIEW

**Comment by NickeManarin** [comment]
Can someone review this?

**Comment by denelon** [comment]
@NickeManarin we do them in batches a few times a day in most cases. It looks like our service issues may be mitigated, so I'd expect another push tonight or in the morning.

**Comment by denelon** [comment]
I love ScreenToGif BTW :)

**Comment by NickeManarin** [comment]
> @NickeManarin we do them in batches a few times a day in most cases. It looks like our service issues may be mitigated, so I'd expect another push tonight or in the morning.

Ohhh, all right :)

> I love ScreenToGif BTW :)

Awesome! I'm glad that you love it :)

**Pull request merged**
