### PR TITLE
Remove uneccesary DisplayVersion from RoyalApps.RoyalTS.V7

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161949)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 886)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 886)

**Comment by Trenly** [comment]
@stephengillie - can this be manually tested?

**Pull request merged**
