### PR TITLE
RamSoft dicomProxy Updated version: 0.2.332-ci.8

### PR DESCRIPTION
**Pull request by ghost**
RamSoft dicomProxy updated the version 0.2.332-ci.8, RamSoft DicomProxy from release pipeline

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/20323)

### CODE REVIEW

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
image

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
image
Powershell needs to be run as Administrator which is how it passed validation, is this something you could look into for a better user experience?

**Comment by ramsoft-inc** [comment]
@OfficialEsco @ItzLevvie2  We need this installer run in administrator  mode only.

**Review by ItzLevvie — APPROVED** [review]
image

**Pull request merged**
