### PR TITLE
Add JakobDev.jdAppStreamEdit

### PR DESCRIPTION
**Pull request by JakobDev**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/108517)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @JaokbDev,

I couldn't navigate to the InstallerUrl from the PackageUrl. Is there a mirror, archive, or other link that I missed?

**Comment by JakobDev** [comment]
The Readme was generated from a template which doesn't include SourceForge, that's why the Link was missing. I have now added the Link.

**Comment by JakobDev** [comment]
Ping @stephengillie

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
