### PR TITLE
Remove PostgreSQL.PostgreSQL Version 16.0

### PR DESCRIPTION
**Pull request by FaserF**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---
More informations are here: https://github.com/microsoft/winget-pkgs/pull/153712#issuecomment-2116465932
This PR Is needed to get the latest version merged.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/154032)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2145844845
> 2024-05-17 08:01:34.751 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-05-17 08:01:34.793 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FF89F04A465: (caller: 00007FF89F04AD01) Exception(1) tid(1410) 80190193 Forbidden (403).
> 2024-05-17 08:01:35.373 [CORE] Download request failed. Returned status: 403
> 2024-05-17 08:01:35.373 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FF89F0443D6: (caller: 00007FF89F045C49) Exception(2) tid(1410) 80190193 Forbidden (403).
> 2024-05-17 08:01:35.461 [CLI ] Failed to download, waiting a bit and retry. Url: https://get.enterprisedb.com/postgresql/postgresql-16.0-1-windows-x64.exe
> 2024-05-17 08:01:36.183 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-05-17 08:01:36.183 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FF89F04A465: (caller: 00007FF89F04AD01) Exception(3) tid(1410) 80190193 Forbidden (403).
> 2024-05-17 08:01:36.291 [CORE] Download request failed. Returned status: 403
> 2024-05-17 08:01:36.292 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FF89F0443D6: (caller: 00007FF89F045C49) Exception(4) tid(1410) 80190193 Forbidden (403).

(Automated response - build 881.)

**Comment by stephengillie** [comment]
URL: https://get.enterprisedb.com/postgresql/postgresql-16.0-1-windows-x64.exe 
OK

(Automated message - build 882)

**Review by stephengillie — DISMISSED** [review]

**Comment by FaserF** [comment]
Installer Download worked fine for me on my private machine. But nevertheless, I have changed this PR to remove 16.0

**Comment by stephengillie** [comment]
URL: https://get.enterprisedb.com/postgresql/postgresql-16.0-1-windows-x64.exe 
OK

(Automated message - build 887)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
