### PR TITLE
Submitting SitdownMW version 1.0.0.0

### PR DESCRIPTION
**Pull request by AshleyStone**
Used to keep Modern Warfare's process running at 'normal' execution priority.

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2417)

### CODE REVIEW

**Comment by AshleyStone** [comment]
Apparently what I can do locally is different from what the wingetbot expects.

**Comment by KevinLaMS** [comment]
Hey @AshleyStone  
When I install this and try to run the executable I am getting this error.  Is there some additional step the user needs to do?
image

**Comment by AshleyStone** [comment]
Hi @KevinLaMS,

This non-interactive background service should be started automatically after install, you can stop it with "net stop SitdownMW", start it with "net start SitdownMW" (provided your cmd console is running with administrative privileges). I go into some detail on it's [home page](https://bitbucket.org/AshleyStone/sitdownmw/).

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
