### PR TITLE
New version: Duplicati.Duplicati version 2.0.7.1

### PR DESCRIPTION
**Pull request by martin-labbe**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132879)

### CODE REVIEW

**Comment by martin-labbe** [comment]
The installations seems to fail because of Microsoft Smart Screen.  Is there something I can do if I am not the author of Duplicati.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978334957 2024-01-05 09:18:48.655 [CLI ] ShellExecute installer failed: 1633 MSI (s) (8C:44) [09:18:48:310]: Product: Duplicati 2 -- Installation failed. MSI (s) (8C:44) [09:18:48:310]: Windows Installer installed the product. Product Name: Duplicati 2. Product Version: 2.0.7.1. Product Language: 1033. Manufacturer: Duplicati Team. Installation success or error status: 1633.

(Automated response - build 530.)

**Comment by stephengillie** [comment]
This application is a locally-hosted webserver. 
image

**Comment by stephengillie** [comment]
Hi @martin-labbe,

This manifest adds Apps and Features entries that aren't present in previous PR versions. Should these entries also be added to the previous versions?

(Automated response - build 532.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
