### PR TITLE
Comment out empty Moniker for Nikkho.FileOptimizer

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/180559)

### CODE REVIEW

**Comment by Trenly** [comment]
Intentional
[Policy] Reset Labels

**Comment by mdanish-kh** [comment]
@Trenly - is the download URL working for you? Doesn't appear to be working at my end. If it isn't, then instead of this PR, you can approve https://github.com/microsoft/winget-pkgs/pull/180542

**Comment by mdanish-kh** [comment]
The URLs did pass validation, which may mean it could be a my region thing only with sourceforge URLs

**Comment by Trenly** [comment]
@mdanish-kh - Yes, the URL works for me

**Review by mdanish-kh — APPROVED** [review]

**Pull request merged**
