### PR TITLE
JanJones.ipasim version 1.0.1

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/106698)

### CODE REVIEW

**Comment by stephengillie** [comment]
This application doesn't appear to install any executable files, or otherwise modify the system in a significant way.

**Comment by upintheairsheep** [comment]
> This package doesn't appear to install any executable files, or otherwise modify the system in a significant way.

What does it do then?

**Comment by stephengillie** [comment]
> > This package doesn't appear to install any executable files, or otherwise modify the system in a significant way.
> 
> What does it do then?

It opens a self-extracting ZIP that opens a PowerShell window that closes soon. It happens very quickly and is easy to miss.

**Comment by upintheairsheep** [comment]
> > > This package doesn't appear to install any executable files, or otherwise modify the system in a significant way.
> > 
> > 
> > What does it do then?
> 
> It opens a self-extracting ZIP that opens a PowerShell window that closes soon. It happens very quickly and is easy to miss.

I think you need admin powershell for this

**Comment by stephengillie** [comment]
Validation normally runs as administrator. Only when a manifest specifies "ElevationProhibited" does validation run in a non-elevated session.

**Comment by upintheairsheep** [comment]
> Validation normally runs as administrator. Only when a manifest specifies "ElevationProhibited" does validation run in a non-elevated session.

Add it.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
I was able to record the PowerShell output using my phone and slowed down the video to see the message:
```
Found package: C:\Users\TAP\AppData\Local\Temp\7zSFB5F.tmp\IpaSimApp_1.0.1.0_Win32.msix
Found package: C:\Users\TAP\AppData\Local\Temp\7zSFB5F.tmp\IpaSimApp_1.0.1.0_Win32.cer

Before installing this app, you need to do the following:
    - Acquire a developer license
    - Install the signing certificate
Acquiring a developer license requires user interaction. Please rerun the script without the -Force parameter.
```

**Comment by ItzLevvie** [comment]
[Policy] Interactive-Only-Installer

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Pull request closed without merging**
