### PR TITLE
update `Miller.Miller` to `6.12.0` (#136590)

### PR DESCRIPTION
**Pull request by rursprung**
the manifest has been created using the following command:
```bash
wingetcreate update miller.miller -v 6.12.0 -u https://github.com/johnkerl/miller/releases/download/v6.12.0/miller-6.12.0-windows-386.zip https://github.com/johnkerl/miller/releases/download/v6.12.0/miller-6.12.0-windows-amd64.zip
```

the `ReleaseNotesUrl` has been manually added as `wingetcreate update` does not yet support release notes (see also
microsoft/winget-create#497).

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/144939)

### CODE REVIEW

**Comment by rursprung** [comment]
@johnkerl: it'd be great if https://github.com/johnkerl/miller/issues/1459 could be implemented so that this were automated (it should be fairly easy to set up, but it's something you have to do yourself due to the required access token in the workflow). thanks!

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\mlr.exe returned exit code: 1
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\mlr.exe returned exit code: 1

(Automated response - build 870.)

**Comment by rursprung** [comment]
> Automatic Validation ended with:
> 
> > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\mlr.exe returned exit code: 1
> > Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\mlr.exe returned exit code: 1
> 
> (Automated response - build 870.)

this is to be expected if `mlr` is being called w/o any arguments and not a packaging problem.

**Comment by stephengillie** [comment]
> this is to be expected if `mlr` is being called w/o any arguments and not a packaging problem.

This situation is common. Thanks for your patience.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
