### PR TITLE
New version: FontForge.FontForge version 20220308

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

* Resolves #93519

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/93526)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Trenly,

Thanks for the quick action. This PR looks to fix:
* https://github.com/microsoft/winget-pkgs/pull/93519

This looks like it removes that version while adding this version - does that count as modifying 2 manifests in one PR?

**Comment by Trenly** [comment]
> Hi @Trenly,
> 
> Thanks for the quick action. This PR looks to fix:
> 
> * [FontForge.FontForge - remove old version 08-03-2022 #93519](https://github.com/microsoft/winget-pkgs/pull/93519/files)
> 
> This looks like it removes that version while adding this version - does that count as modifying 2 manifests in one PR?

It shouldn't, plenty of PR's remove an old version while adding a new one.

**Comment by krystofkrticka** [comment]
I already closed my PR but this will colide with version number reported by appwiz.cpl

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
