### PR TITLE
Modify: Mozilla.Firefox.ESR version 115.8.0

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings).
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/153319)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/115.8.0esr/win32/cs/Firefox%20Setup%20115.8.0esr.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-385-153319-20240513-4\8cec4faa-b741-409e-b11e-ae7171ceca35' because it is being used by another process..
 Error information: 
 Http Response: OK
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 
 5/13/2024 5:35:54 PM
 

(Automated response - build 880.)

**Comment by stephengillie** [comment]
URL: https://download-installer.cdn.mozilla.net/pub/firefox/releases/115.8.0esr/win32/en-US/Firefox%20Setup%20115.8.0esr.exe 
Status Code: 200

(Automated message - build 880)

**Comment by stephengillie** [comment]
Hi @SpecterShell,

This manifest adds Apps and Features entries that aren't present in previous PR versions. These entries should be added to the previous versions, or removed from this version.

(Automated response - build 880.)

**Comment by SpecterShell** [comment]
> Hi @SpecterShell,
> 
> This manifest adds Apps and Features entries that aren't present in previous PR versions. These entries should be added to the previous versions, or removed from this version.
> 
> (Automated response - build 880.)

This PR removes the Apps and Features entries that aren't present in the original manifest.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
