### PR TITLE
New Version: VMware.WorkstationPro version 17.5.1.23298084

### PR DESCRIPTION
**Pull request by virtualex-itv**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
Snag_239dd1fc
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141183)

### CODE REVIEW

**Comment by virtualex-itv** [comment]
@stephengillie - i'm back!  pinging you as you've handled these for me in the past, thank you in advance!

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Installer https://download3.vmware.com/software/WKST-1751-WIN/VMware-workstation-full-17.5.1-23298084.exe
 Scan request id: '712c5dd9-6c4d-472a-adcb-7e7178a810ca'
 Error information: BlockingDetectionFound
 
 2/27/2024 8:04:03 PM
 
 ****************************************************************************************
 Installer Validation
 ****************************************************************************************
 

(Automated response - build 837.)

**Comment by stephengillie** [comment]
This might be due to a network block of data centers, to prevent automated downloads.

(Automated response - build 837.)

**Comment by stephengillie** [comment]
URL: https://download3.vmware.com/software/WKST-1751-WIN/VMware-workstation-full-17.5.1-23298084.exe 
Status Code: 200

(Automated message - build 837)

**Comment by stephengillie** [comment]
Hi @virtualex-itv,,

Unfortunately, this isn't an issue that I can unblock or waiver around. The host serving this file seems to be blocking data centers from downloading the file. This is why the download works for you and I, on our residential IP addresses, but not for our scanning service.

**Comment by virtualex-itv** [comment]
> Hi @virtualex-itv,,
> 
> Unfortunately, this isn't an issue that I can unblock or waiver around. The host serving this file seems to be blocking data centers from downloading the file. This is why the download works for you and I, on our residential IP addresses, but not for our scanning service.

hi @stephengillie - So what has to be done if you know?  Not sure why there is a blocking error as the same URL is used for a Chocolatey package and works without issue.  WinGet has always given a problem with the VMware Workstation Player/Pro packages.

**Comment by stephengillie** [comment]
I'm not aware of a path forward from here.

**Comment by virtualex-itv** [comment]
@w3lld0ne - done!

**Comment by virtualex-itv** [comment]
@w3lld0ne  @stephengillie  - i made a change as requested here https://github.com/microsoft/winget-pkgs/pull/141183#issuecomment-1971228609

can you check again?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Installer https://download3.vmware.com/software/WKST-1751-WIN/VMware-workstation-full-17.5.1-23298084.exe
 Scan request id: '5cfc136c-f9c7-4246-b3b5-2d1f4ed8e73c'
 Error information: BlockingDetectionFound
 
 3/8/2024 2:35:38 AM
 
 ****************************************************************************************
 Installer Validation
 ****************************************************************************************
 

(Automated response - build 869.)

**Comment by stephengillie** [comment]
This might be due to a network block of data centers, to prevent automated downloads.

(Automated response - build 869.)

**Comment by stephengillie** [comment]
URL: https://download3.vmware.com/software/WKST-1751-WIN/VMware-workstation-full-17.5.1-23298084.exe 
Status Code: 200

(Automated message - build 869)

**Comment by virtualex-itv** [comment]
No idea here.  The URL should not be getting blocked but who knows.  I am a VMware employee so I will see what I can find out internally however I also manage this package on the chocolatey repository which uses the same download URL and it works perfectly, no blocking issues.

**Comment by stephengillie** [comment]
The blocking issue has been in place for some time. Is there another host other than `download3`? 
- https://github.com/microsoft/winget-pkgs/pull/139465

**Comment by virtualex-itv** [comment]
> The blocking issue has been in place for some time. Is there another host other than `download3`?
> 
> * [[Agreements] Add back VMware.WorkstationPlayer #139465](https://github.com/microsoft/winget-pkgs/pull/139465)

not that I am aware of, unfortunately.  Is there nothing that can be done to manually approve this?  again, the Chocolatey package that I maintain as well uses this same download URL and does not have any blocking issues present.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Installer https://download3.vmware.com/software/WKST-1751-WIN/VMware-workstation-full-17.5.1-23298084.exe
 Scan request id: '6af3d4f3-3133-4499-9c21-bd80c8e0c6e7'
 Error information: BlockingDetectionFound
 
 4/18/2024 5:31:58 PM
 
 ****************************************************************************************
 Installer Validation
 ****************************************************************************************
 

(Automated response - build 877.)

**Comment by stephengillie** [comment]
This might be due to a network block of data centers, to prevent automated downloads.

(Automated response - build 877.)

**Pull request closed without merging**
