### PR TITLE
Remove version: Ryujinx.Ryujinx version 1.1.1403

### PR DESCRIPTION
**Pull request by Dragon1573**
### Repository has been taken offline

Relevant GitHub organization & project page response with HTTP 404, official download page of the project becomes blank. The package is no longer availalbe for installation.

- Resolves #176342

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/176505)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://github.com/Ryujinx/release-channel-master/releases/download/1.1.1403/ryujinx-1.1.1403-win_x64.zip 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 896)

**Comment by stephengillie** [comment]
Hi @Dragon1573,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 896.)

**Comment by Dragon1573** [comment]
> This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)
> 
> (Automated response - build 896.)

NO. According to [this](https://www.polygon.com/gaming/458905/nintendo-switch-emulator-ryujinx-offline), this package has been "taken down" by **Nintendo** and no longer available for users any more.

image

**Comment by stephengillie** [comment]
URL: https://github.com/Ryujinx/release-channel-master/releases/download/1.1.1403/ryujinx-1.1.1403-win_x64.zip 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 896)

**Comment by stephengillie** [comment]
URL: https://github.com/Ryujinx/release-channel-master/releases/download/1.1.1403/ryujinx-1.1.1403-win_x64.zip 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 896)

**Comment by Dragon1573** [comment]
> [!CAUTION]
>
> This removal is intended!
>
> This package will no longer available for users, since the entire GitHub repository has been removed.
>
> - See https://github.com/microsoft/winget-pkgs/pull/176505#issuecomment-2388874776

**Comment by stephengillie** [comment]
URL: https://github.com/Ryujinx/release-channel-master/releases/download/1.1.1403/ryujinx-1.1.1403-win_x64.zip 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 896)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by Dragon1573** [comment]
@stephengillie https://github.com/microsoft/winget-pkgs/pull/176505#issuecomment-2391916878

**Comment by Dragon1573** [comment]
Is it already been merged several hours ago? 😕

Could this pull request be manually merged? ❤️

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
