### PR TITLE
Add version: h3poteto.whalebird-desktop version 5.0.4

### PR DESCRIPTION
**Pull request by itsAdee**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136887)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://github.com/h3poteto/whalebird-desktop/releases/download/v5.0.4/Whalebird-5.0.4-windows-ia32.exe 
Response status code does not indicate success: 401 (Unauthorized).

(Automated message - build 669)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> URI: https://raw.githubusercontent.com/h3poteto/whalebird-desktop/master/LICENSE.txt, Validation result: Failed, Http status code: NotFound 

(Automated response - build 669.)

**Comment by mdanish-kh** [comment]
> URL: [h3poteto/whalebird-desktop@`v5.0.4` Whalebird-5.0.4-windows-ia32.exe (download)](https://github.com/h3poteto/whalebird-desktop/releases/download/v5.0.4/Whalebird-5.0.4-windows-ia32.exe) Response status code does not indicate success: 401 (Unauthorized).
> 
> (Automated message - build 669)

@stephengillie URL works fine for me. Might want to check your automation.

**Comment by stephengillie** [comment]
> @ stephengillie URL works fine for me. Might want to check your automation.

I'm getting different output now than I was before. Status code isn't getting through for some reason but the response has definitely changed since my last check.

**Review by mdanish-kh — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://github.com/h3poteto/whalebird-desktop/releases/download/v5.0.4/Whalebird-5.0.4-windows-ia32.exe 
Status Code: 200

(Automated message - build 671)

**Pull request merged**
