### PR TITLE
Version Update: Morpheus.Bazarr version 1.4.0

### PR DESCRIPTION
**Pull request by babblebauble**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/128422)

### CODE REVIEW

**Comment by babblebauble** [comment]
> Possible duplicate package entry.
> 
> Similar installer SHA256 hash found in manifest:
> 
>     * `InstallerSha256: 69dfd1591bb0b6f479ffbadf1eb563692ded7c909997425097602dda63f496ec`
>       
>       * manifests\m\Morpheus\Bazarr\1.2.0

The reason for this is that this application uses a single installer which downloads and installs the latest stable version. Therefore it's not possible to have older releases in the repository. Version 1.2.0 will need to be removed from the repository.

**Comment by Trenly** [comment]
> > Possible duplicate package entry.
> > Similar installer SHA256 hash found in manifest:
> > ```
> > * `InstallerSha256: 69dfd1591bb0b6f479ffbadf1eb563692ded7c909997425097602dda63f496ec`
> >   
> >   * manifests\m\Morpheus\Bazarr\1.2.0
> > ```
> 
> The reason for this is that this application uses a single installer ([bazarr/bazarr.github.io/releases/latest/download/bazarr.zip](https://github.com/bazarr/bazarr.github.io/releases/latest/download/bazarr.zip)) which downloads and installs the latest stable version ([morpheus65535/bazarr/releases](https://github.com/morpheus65535/bazarr/releases)). Therefore it's not possible to have older releases in the repository. Version 1.2.0 will need to be removed from the repository.

You can update this PR to remove version 1.2.0 as part of the same PR

**Comment by babblebauble** [comment]
> > > Possible duplicate package entry.
> > > Similar installer SHA256 hash found in manifest:
> > > ```
> > > * `InstallerSha256: 69dfd1591bb0b6f479ffbadf1eb563692ded7c909997425097602dda63f496ec`
> > >   
> > >   * manifests\m\Morpheus\Bazarr\1.2.0
> > > ```
> > 
> > 
> > The reason for this is that this application uses a single installer ([bazarr/bazarr.github.io/releases/latest/download/bazarr.zip](https://github.com/bazarr/bazarr.github.io/releases/latest/download/bazarr.zip)) which downloads and installs the latest stable version ([morpheus65535/bazarr/releases](https://github.com/morpheus65535/bazarr/releases)). Therefore it's not possible to have older releases in the repository. Version 1.2.0 will need to be removed from the repository.
> 
> You can update this PR to remove version 1.2.0 as part of the same PR

Ah, didn't realise that. I created a separate PR (#128438) which has already been approved and merged.

**Comment by stephengillie** [comment]
AzurePipelines run

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
