### PR TITLE
New version: LGUG2Z.komorebi version 0.1.27

### PR DESCRIPTION
**Pull request by LGUG2Z**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/158805)

### CODE REVIEW

**Comment by LGUG2Z** [comment]
Any idea what the validation failure here was?

**Comment by LGUG2Z** [comment]
Is there any action required from me here? I see the latest pipeline runs are marked as cancelled 👀

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/discussions/155218
Sorry for the delay.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
