### PR TITLE
Added JetBrains dotUltimate version 2020.3.3.

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with winget validate <manifest>, where <manifest> is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with winget install -m <manifest>?

----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/7874)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
Installer is failing with error 4294967295

**Comment by jedieaston** [comment]
I cannot replicate this on my (clean Windows Sandbox, if it makes a difference) machine:

image


``` 
PS C:\Users\WDAGUtilityAccount\Desktop\dotUltimate> winget --info
Windows Package Manager v0.2.10191 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19041.804
Package: Microsoft.DesktopAppInstaller v1.11.10191.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
[WinGet-2021-2-25-11-43-11.438.log](https://github.com/microsoft/winget-pkgs/files/6044642/WinGet-2021-2-25-11-43-11.438.log)

Links
--------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
PS C:\Users\WDAGUtilityAccount\Desktop\dotUltimate>
```

Install log:
[WinGet-2021-2-25-11-43-11.438.log](https://github.com/microsoft/winget-pkgs/files/6044647/WinGet-2021-2-25-11-43-11.438.log)

**Comment by KevinLaMS** [comment]
image

**Comment by jedieaston** [comment]
Turns out it wasn't elevating itself if you didn't run it from an administrator shell. It should work all the time now.

**Pull request merged**
