### PR TITLE
New version: NetSarangComputer.PortX Version 2.2.6

### PR DESCRIPTION
**Pull request by netsarang-bigseungho**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/124258)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/153835)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://cdn.netsarang.net/0ac7ea20/PortX-2.2.6-Setup.exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 881)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> URI: https://cdn.netsarang.net/0ac7ea20/PortX-2.2.6-Setup.exe, Validation result: Failed, Http status code: NotFound

(Automated response - build 881.)

**Comment by stephengillie** [comment]
URL: https://cdn.netsarang.net/0ac7ea20/PortX-2.2.6-Setup.exe 
Response Error: The remote server returned an error: (404) Not Found.

(Automated message - build 882)

**Comment by NetSarangComputer** [comment]
The URL access issue has been resolved. Please resume reviewing pull requests.

**Comment by stephengillie** [comment]
URL: https://cdn.netsarang.net/0ac7ea20/PortX-2.2.6-Setup.exe 
OK

(Automated message - build 882)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
