### PR TITLE
Add manifest file for Adobe Acrobat Reader DC (MUI) 2020.012.20048

### PR DESCRIPTION
**Pull request by dumontirou**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [X] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3800)

### CODE REVIEW

**Comment by dumontirou** [comment]
The manifest has been placed in manifest/Adobe/AdobeAcrobatReaderDC
I have deleted the other manifests in the folder, as requested

**Comment by yigitemres** [comment]
You can only modify one file per pr.

**Comment by dumontirou** [comment]
> You can only modify (creating, deleting, change) one file per pr.
> 
> ```
> @azure-pipelines
> azure-pipelines
> / WinGetSvc-Validation (Pull Request Validation)
> 
> Build log #L25
>  The pull request contains more than one manifest file.
> ```

You're right, sorry for that ! I've deleted the other manifest I added in the pull request

**Comment by yigitemres** [comment]
> You're right, sorry for that ! I've deleted the other manifest I added in the pull request

This rule (one file per pr) gonna change. You can look backlogs. 
https://github.com/microsoft/winget-pkgs/milestone/1

Thanks for your contribution. 🥂

**Pull request merged**
