### PR TITLE
Remove version: GoXLR-on-Linux.GoXLR-Utility version 1.1.0

### PR DESCRIPTION
**Pull request by parzival-space**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/148856)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://github.com/GoXLR-on-Linux/goxlr-utility/releases/download/v1.1.0/goxlr-utility-1.1.0.exe 
Status code: 200

(Automated message - build 638)

**Comment by stephengillie** [comment]
Hi @parzival-space,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 876.)

**Comment by parzival-space** [comment]
latest version had a bug. this version has been rolled back.

**Comment by stephengillie** [comment]
URL: https://github.com/GoXLR-on-Linux/goxlr-utility/releases/download/v1.1.0/goxlr-utility-1.1.0.exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 876)

**Comment by stephengillie** [comment]
URL: https://github.com/GoXLR-on-Linux/goxlr-utility/releases/download/v1.1.0/goxlr-utility-1.1.0.exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 876)

**Comment by stephengillie** [comment]
URL: https://github.com/GoXLR-on-Linux/goxlr-utility/releases/download/v1.1.0/goxlr-utility-1.1.0.exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 876)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
