### PR TITLE
Nirsoft.Advancedrun version 1.51

### PR DESCRIPTION
**Pull request by neomax7**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/93807)

### CODE REVIEW

**Comment by neomax7** [comment]
manifest v1.4 with zip

**Comment by neomax7** [comment]
manifest version is 1.4 with zipped portable executable

**Comment by neomax7** [comment]
the manifest version is 1.4 with zipped portable executable.

I have tested manifest locally with winget version v1.5.101-preview and it worked without any error.

I have forked the repository and tried to merge and it worked without any conflict. 

could you please let me know if there is anything I can do to fix the pulling issue?

**Comment by stephengillie** [comment]
> the manifest version is 1.4 with zipped portable executable.

Each of these is somewhat of a blocker currently. 

> I have tested manifest locally with winget version v1.5.101-preview and it worked without any error.
> 
> I have forked the repository and tried to merge and it worked without any conflict.
> 
> could you please let me know if there is anything I can do to fix the pulling issue?

The successful install is encouraging. We're monitoring version adoption and hoping to start accepting packages like this at some point after 1.4 is sufficiently saturated. If this package needs features in the 1.5 version, then it might unfortunately need to wait some time longer, until that version saturates.

**Comment by neomax7** [comment]
> > the manifest version is 1.4 with zipped portable executable.
> 
> 
> 
> Each of these is somewhat of a blocker currently. 
> 
> 
> 
> > I have tested manifest locally with winget version v1.5.101-preview and it worked without any error.
> 
> > 
> 
> > I have forked the repository and tried to merge and it worked without any conflict.
> 
> > 
> 
> > could you please let me know if there is anything I can do to fix the pulling issue?
> 
> 
> 
> The successful install is encouraging. We're monitoring version adoption and hoping to start accepting packages like this at some point after 1.4 has sufficiently saturated into our userbase. If this package needs features in the 1.5 version, then it might unfortunately need to wait some time longer, until that version saturates. 

I understand, thank you 😁

**Comment by neomax7** [comment]
> > the manifest version is 1.4 with zipped portable executable.
> 
> 
> 
> Each of these is somewhat of a blocker currently. 
> 
> 
> 
> > I have tested manifest locally with winget version v1.5.101-preview and it worked without any error.
> 
> > 
> 
> > I have forked the repository and tried to merge and it worked without any conflict.
> 
> > 
> 
> > could you please let me know if there is anything I can do to fix the pulling issue?
> 
> 
> 
> The successful install is encouraging. We're monitoring version adoption and hoping to start accepting packages like this at some point after 1.4 has sufficiently saturated into our userbase. If this package needs features in the 1.5 version, then it might unfortunately need to wait some time longer, until that version saturates. 

I understand, thank you 😁

**Pull request closed without merging**
