### PR TITLE
New version: TheDocumentFoundation.LibreOffice version 24.2.4.2 (24.2.4)

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings).
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/156768)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 Error occurred while downloading installer from https://downloadarchive.documentfoundation.org/libreoffice/old/24.2.4.2/win/x86/LibreOffice_24.2.4.2_Win_x86.msi. 0x80072F78.
 Error information: 
 Http Response: OK
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 
 6/6/2024 12:29:48 PM
 

(Automated response - build 883.)

**Comment by stephengillie** [comment]
URL: https://downloadarchive.documentfoundation.org/libreoffice/old/24.2.4.2/win/x86/LibreOffice_24.2.4.2_Win_x86.msi 
Status Code: 200

(Automated message - build 883)

**Comment by MagicAndre1981** [comment]
those links work and should be used as suggested in an earlier libreoffice PR @SpecterShell :

x86: https://download.documentfoundation.org/libreoffice/stable/24.2.4/win/x86/LibreOffice_24.2.4_Win_x86.msi
x64: https://download.documentfoundation.org/libreoffice/stable/24.2.4/win/x86_64/LibreOffice_24.2.4_Win_x86-64.msi
arm64: https://download.documentfoundation.org/libreoffice/stable/24.2.4/win/aarch64/LibreOffice_24.2.4_Win_aarch64.msi

**Comment by stephengillie** [comment]
Hi @SpecterShell,

This manifest removes Apps and Features entries that are present in previous PR versions. These entries should be added to this version, to maintain version matching, and prevent the 'upgrade always available' situation with this package.

(Automated response - build 883.)

**Comment by SpecterShell** [comment]
> Hi @SpecterShell,
> 
> This manifest removes Apps and Features entries that are present in previous PR versions. These entries should be added to this version, to maintain version matching, and prevent the 'upgrade always available' situation with this package.
> 
> (Automated response - build 883.)
> 
> Edit: The [previous version](https://github.com/microsoft/winget-pkgs/pull/151943/files) had:
> 
> ```
> AppsAndFeaturesEntries:
> - DisplayName: LibreOffice 24.2.3.2
>   UpgradeCode: '{4B17E523-5D91-4E69-BD96-7FD81CFA81BB}'
> ```
> 
> Should this be added here? (With updated version number?)

Nah I'm going to remove it.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
