### PR TITLE
New version: gokcehan.lf version r32

### PR DESCRIPTION
**Pull request by gokcehan**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/147144)

### CODE REVIEW

**Comment by sitiom** [comment]
Works fine for me:
image

**Comment by sitiom** [comment]
Works fine for me:
image

CC @stephengillie

**Comment by stephengillie** [comment]
Hi @gokcehan,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-31 13:22:47.462 [FAIL] Installer failed security check. Url: https://github.com/gokcehan/lf/releases/download/r32/lf-windows-amd64.zip Result: 0x80004005
> 2024-03-31 13:22:01.757 [FAIL] Installer failed security check. Url: https://github.com/gokcehan/lf/releases/download/r32/lf-windows-386.zip Result: 0x80004005

(Automated response - build 876.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
