### PR TITLE
Remove Auto backup pro 2.5.27

### PR DESCRIPTION
**Pull request by oo-cmatuschka**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/158474)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @oo-cmatuschka,

This PR doesn't modify any files. Which files were you trying to remove?

**Comment by oo-cmatuschka** [comment]
> Just seeing the message above.



> Edit: Just seeing the message above.

Hi Stephen,

My goal was simply to delete the supposedly incorrect Professional manifests and continue with the 'Non-Professional' manifest files.

I don't know why the validation process thinks that I've changed the validation-pipeline.yaml, and I don't understand it either. In my commit, you can only see the 4 removed files.

**Comment by stephengillie** [comment]
I'm not sure why the bot believes that the file is being modified either. Is your fork up to date? If not, could you try updating the branch?
The current state of one of my branches, for reference: image

**Comment by oo-cmatuschka** [comment]
> I'm not sure why the bot believes that the file is being modified either. Is your fork up to date? If not, could you try updating the branch? The current state of one of my branches, for reference: image

Hi Stephen,

Ah, there's the mistake. I didn't:

1. Update the fork, and
2. Add and remove are in the same branch.

I'm very sorry! Earlier, I created a new branch for each version to be deleted, and each passed the automatic validation smoothly.

Once they are approved by you, I can delete this branch here, right?

**Pull request closed without merging**
