### PR TITLE
IObit.IObitUnlocker version 1.2.0.1

### PR DESCRIPTION
**Pull request by techflashYT**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14440)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
This one installed correctly so the bot is prolly just stuck, if you have git installed you can do `git commit --allow-empty --message="Try Again"` then `git push`

**Comment by sanikdah** [comment]
I actually don't have git installed, sorry, I might be able to run it through WSL though,

**Comment by sanikdah** [comment]
Wait why did I just an email saying that this PR is the same as literally this PR?

**Comment by OfficialEsco** [comment]
> Wait why did I just an email saying that this PR is the same as literally this PR? (sorry actually its saying that some PR I didn't make is the same as this PR)

I posted a comment on your `PuranSoftware.PuranFileRecovery version 1.2.1` PR 😁
What i meant is that you should also do `get commit` there

**Comment by sanikdah** [comment]
Ahhh ok I see, can you tell me exactly how I would do that through WSL or am I just stupid?

**Comment by OfficialEsco** [comment]
> Ahhh ok I see, can you tell me exactly how I would do that through WSL or am I just stupid?

I have no experience with WSL or git on WSL so no idea

**Comment by sanikdah** [comment]
> > Ahhh ok I see, can you tell me exactly how I would do that through WSL or am I just stupid?
> 
> I have no experience with WSL or git on WSL so no idea

alright I didn't know about github desktop for windows so I knew that git was a command on linux and also on WSL

**Comment by sanikdah** [comment]
ok and this one is also just stuck

**Comment by sanikdah** [comment]
And now it's retrying

**Comment by sanikdah** [comment]
The installer scan is still taking over 30 minutes

**Comment by OfficialEsco** [comment]
Yeee, seems like a technician will have to take a look at it

**Comment by sanikdah** [comment]
Also the github desktop app just doesnt work, when i do ctrl+P to push the changes it just doesnt do anything, and i cant click the commit button,

**Comment by sanikdah** [comment]
so it's been running for another few hours now, sill doesnt work

**Comment by sanikdah** [comment]
what?  it is not malware, some av's identify it as a PUP because it's from IObit but not malware.

**Comment by OfficialEsco** [comment]
I don't know the criteria for it to be accepted, but i think 10 is over the limit
https://www.virustotal.com/gui/file/ae8e0cab1786a619e0e0cb044209e5de7a6a30375dd88400c59551061f318a68/detection

**Comment by sanikdah** [comment]
> I don't know the criteria for it to be accepted, but i think 10 is over the limit
> https://www.virustotal.com/gui/file/ae8e0cab1786a619e0e0cb044209e5de7a6a30375dd88400c59551061f318a68/detection

but yeah you can see they all just say potentially unwanted, not like malicious.  And I know that a while back the company did make malicious products, but not anymore, they are actually legitimate now.

**Comment by sanikdah** [comment]
If it can't be accepted that sucks though because it is a useful program, it lets you unlock files that are in use so you can do stuff like rename or delete them.

**Pull request closed without merging**
