### PR TITLE
Updating Manifest to Malwarebytes.Malwarebytes 4.5.27.262

### PR DESCRIPTION
**Pull request by BrandonWanHuanSheng**
Changing the folder version from 4.5.24.248 to 4.5.27.262
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/103484)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
It look like Azure Pipelines did not work correctly.

**Review by stephengillie — APPROVED** [review]

**Comment by BrandonWanHuanSheng** [comment]
Oops! The pipeline terminated unexpectedly.

**Comment by BrandonWanHuanSheng** [comment]
@stephengillie If you closed and reopened the pull request. Don't say /AzurePipelines run. This is due to wingetbot

**Comment by stephengillie** [comment]
> @stephengillie Stephen Gillie (TEKsystems, Inc.) Vendor If you closed and reopened the pull request. Don't say /AzurePipelines run. This is due to wingetbot saying [#103484 (comment)](https://github.com/microsoft/winget-pkgs/pull/103484#issuecomment-1522660410). It caused duplicate run instance on Azure Pipelines. It also cause the pull request validation error after publish-pipeline-succeed.

Thank you for the advice. Unfortunately, I accidentally closed the PR *while* saying `/AzurePipelines run`, and so had to reopen it and cause this scenario. I'll do my best to avoid this in the future.

**Comment by BrandonWanHuanSheng** [comment]
> The package manager bot determined there was an issue with the pull request. Make sure the manifest files are under the manifests\partition\publisher\appname\version directory and only one package version is being modified in your PR. The partition of the path must be the first letter of the publisher in lower-case.

This is another Azure Pipelines validation-pipelines is running while the pull-request was merged and closed. Saw that the pipelines was not respond.

**Comment by BrandonWanHuanSheng** [comment]
Most likely, I changed is all those manifest validation succeed.

**Pull request merged**
