### PR TITLE
New version: dotenvx.dotenvx 1.11.5

### PR DESCRIPTION
**Pull request by motdotenv**
New version: dotenvx.dotenvx 1.11.5
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/170385)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-08-28 19:17:51.905 [FAIL] Installer failed security check. Url: https://github.com/dotenvx/dotenvx/releases/download/v1.11.5/dotenvx-1.11.5-windows-x86_64.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 891.)

**Comment by motdotenv** [comment]
@stephengillie i have no idea why this is failing a 'security' check. there is no malware added and it passes virustotal's security check here:

https://www.virustotal.com/gui/url/80ef2f150c101ef4ad117c37f2413b0716b73607916a3da661978248c2c73ddf?nocache=1

why is this failing security check? i would like to fix up so i can get this out for our users.

**Comment by motdotla** [comment]
yes, let us know what you can share here @stephengillie so that we can fix up and get out for our users.

**Comment by stephengillie** [comment]
The "security check" is a Defender check or similar. The pipeline VMs are supposed to update their virus signature at the start of each run, before installing and scanning. Unfortunately, I believe the virus signature/definition version number isn't emitted in the pipeline logs - were it, I'd have my automation output this with other log data into the PR.

**Comment by motdotla** [comment]
now that it passed here: https://github.com/microsoft/winget-pkgs/pull/169947

can it be re-run and approved for this PR as well @stephengillie?

**Comment by motdotenv** [comment]
now that it passed here: https://github.com/microsoft/winget-pkgs/pull/169947

can it be re-run and approved for this PR as well @stephengillie?

**Comment by stephengillie** [comment]
Fun fact: two ways that you can trigger a pipeline run are:
1. Commit any update to the branch - even just adding or removing a space or line break.
2. Closing and reopening the PR.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\dotenvx.dotenvx__DefaultSource\dotenvx.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\dotenvx.exe returned exit code: 1

(Automated response - build 892.)

**Review by stephengillie — APPROVED** [review]

**Comment by motdotenv** [comment]
> Commit any update to the branch - even just adding or removing a space or line break.

ok, good to know. thank you for all your help here @stephengillie !

**Pull request merged**
