### PR TITLE
Updated InstallerUrl: to full path Malwarebytes.Malwarebytes version 4.4.0.117

### PR DESCRIPTION
**Pull request by mddtest**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/16229)

### CODE REVIEW

**Comment by mddtest** [comment]
Fixed Install winget install error added full path

https://data-cdn.mbamupdates.com/web/mb4-setup-consumer/MBSetup.exe

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
That is actually the Online installer, https://data-cdn.mbamupdates.com/web/mb4-setup-consumer/offline/mb4-setup-consumer-4.4.0.220-1.0.1318-1.0.41267.exe is the real offline URL, but they seem to be deleting those right after a new release..
However since you are already fixing the manifest, it seems like the version is reported wrong in multiple places which will probably trick the bot too, the real version Windows sees are 4.4.0.117, can you fix the PackageVersion and rename the folder?

**Comment by OfficialEsco** [comment]
This damn GitHub API issue...
@denelon can this issue get fixed ASAP? It only happens to Publisher.PackageName.installer.yaml, or is there a reason for that?

**Comment by mddtest** [comment]
> 
> 
> This damn GitHub API issue...
> @denelon can this issue get fixed ASAP? It only happens to Publisher.PackageName.installer.yaml, or is there a reason for that?

Would it make more logic to have it as Malwarebytes.Malwarebytes-Free ?

**Comment by OfficialEsco** [comment]
> > This damn GitHub API issue...
> > @denelon can this issue get fixed ASAP? It only happens to Publisher.PackageName.installer.yaml, or is there a reason for that?
> 
> Would it make more logic to have it as Malwarebytes.Malwarebytes-Free ?

is there a different download link for premium?.. Free, Beta, Alpha etc in PackageIdentifier is only needed for programs with different branches

**Comment by mddtest** [comment]
> 
> 
> > > This damn GitHub API issue...
> > > @denelon can this issue get fixed ASAP? It only happens to Publisher.PackageName.installer.yaml, or is there a reason for that?
> > 
> > 
> > Would it make more logic to have it as Malwarebytes.Malwarebytes-Free ?
> 
> is there a different download link for premium?.. Free, Beta, Alpha etc in PackageIdentifier is only needed for programs with different branches

Its the same link. So guess keep it the same.

**Review by OfficialEsco — APPROVED** [review]
Huh, its Approvable?

**Comment by mddtest** [comment]
> Huh, its Approvable?

Nice it finally works, very odd issue.

**Comment by denelon** [comment]
@OfficialEsco which issue were you referring to?

**Comment by OfficialEsco** [comment]
> @OfficialEsco which issue were you referring to?

2 files renamed, 1 file created and 1 file deleted when it should actually be 3 files renamed.

https://github.com/microsoft/winget-pkgs/pull/16268/files
Managed to do it for the locale file on this PR

**Pull request merged**
