### PR TITLE
New version: Xmake-io.Xmake version 2.8.9+20240321

### LINKED ISSUE #146501: [Update Request]: XMake
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

xmake-io.XMake

### Package Version

v2.8.9+20240321

### Please describe the changes you would like to see

There's a new release `v2.8.9` available 🚀

- Download page URL: https://github.com/xmake-io/xmake/releases/tag/v2.8.9
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/winget-pkgs/pull/146502
- [ ] https://github.com/microsoft/winget-pkgs/pull/146504
```

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] There's a linked issue. Resolve #146501

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/146504)

### CODE REVIEW

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> There's another pull request of the same issue. This pull request has one more (ZH-CH locale) file of the manifest. Please moderators sincerely select one of them to be merged.
>
> If this pull request is not accepted at the end, please flagged this pull request as duplicated and close it. Thank you! ❤️

**Comment by stephengillie** [comment]
Hi @Dragon1573,

> This PR's version number 2.8.9+20240321 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 3.3.2.0, which has 4 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 875)

**Review by stephengillie — APPROVED** [review]

**Comment by Dragon1573** [comment]
Excuse me, @stephengillie . I'm not able to find the version `3.3.2.0` from the repository. The current latest version prior to this is `2.8.6+20231226` by #138180 .

I tested the manifest in Windows Sandbox, the version number between manifest and ARP entry are matched as expected.

**Comment by stephengillie** [comment]
I'm also not seeing `3.3.2.0`. I'm not sure where my automation found it. Good that the version matching is working.

**Pull request merged**
