### PR TITLE
New version: Woyun.wolai version 1.2.1

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/54792)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by vedantmgoyal2009** [comment]
@denelon this one needs a waiver

**Comment by denelon** [comment]
@vedantmgoyal2009 
Can you give the URL with the reference to the official downloader? That will help speed the waiver approval up on Monday when the team gets in.

**Comment by vedantmgoyal2009** [comment]
> @vedantmgoyal2009 Can you give the URL with the reference to the official downloader? That will help speed the waiver approval up on Monday when the team gets in.

@SpecterShell

**Comment by SpecterShell** [comment]
https://www.wolai.com/downloads

**Pull request merged**
