### PR TITLE
New package: Monero GUI

### PR DESCRIPTION
**Pull request by blackzafiqz**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/110078&drop=dogfoodAlpha

### CODE REVIEW

**Comment by blackzafiqz** [comment]
@microsoft-github-policy-service agree

**Comment by blackzafiqz** [comment]
> @blackzafiqz please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by BrandonWanHuanSheng** [comment]
The threat is Program:Win32/Uwamson.A!ml

**Comment by blackzafiqz** [comment]
> The threat is Program:Win32/Uwamson.A!ml 
> 
> See this https://www.virustotal.com/gui/file/165c183a7490cfe04a8296e05ad592e3e08705c879bd9facf2dab16a6ef2cf05/detection
> 

yeah it's a false positive, nothing i can do from here. it's a legit program for monero wallet, also the code is open source.

**Comment by blackzafiqz** [comment]
@stephengillie I did file a report to smartscreen. Unfortunately there is nothing we can do apart from waiting. As you can see the error was PUA, it can be unwanted to some, but useful to others.

**Pull request closed without merging**
