### PR TITLE
Apple.iCloud version 7.21.0.23

### PR DESCRIPTION
**Pull request by Macleykun**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/46681)

### CODE REVIEW

**Comment by Macleykun** [comment]
Quick things to note here:
Media Features is required to install iCloud.
I wasn't sure how to fill in the release notes, as Apple also uses word: text, which i believe intefere's with the manifest structure.
The program installs correctly but does throw an error: 3010. But given the program still works as expected this can be ignored.

**Comment by Macleykun** [comment]
> Hello @Macleykun, The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.

I would love to check what went wrong, but all i can find is:
image

What went wrong exactly? Where can i find this?
For me on my personal desktop after installing the Media Feature pack it worked as good as iTunes.

**Comment by jedieaston** [comment]
I think that means this is blocked until we have dependencies support so we can tell winget to install that first (although Media Features should only be required on Windows N versions).

https://github.com/microsoft/winget-cli/issues/163

**Comment by jedieaston** [comment]
That error isn't being exposed (yet), although I think they are working on better logging so we can know in the future.

**Comment by Macleykun** [comment]
InstallationVerification-x86-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20220217121119
Sorry but i believe this error isn't related to the icloud installer...?

**Comment by ItzLevvie** [comment]
> Sorry but i believe this error isn't related to the icloud installer...?

Yeah, those screenshots are currently broken at the moment.

> /AzurePipelines run

You can close and re-open the PR to re-run the pipelines.

>Is that also what is thrown as an erro in the CI? I can't see exactly what the error is

You can take a look at the `InstallationVerification-x86-Scope_Undefined-Locale_Undefined-WinGet-2022-02-17-04-10-18.402.log` file.

```
2022-02-17 04:10:18.471 [CORE] Valid settings file not found. Using default values.
2022-02-17 04:10:18.471 [CORE] WinGet, version [1.1.12653], activity [{8FF84D90-6CDB-472D-B4D3-A3F1E2480ABB}]
2022-02-17 04:10:18.472 [CORE] OS: Windows.Desktop v10.0.19042.1052
2022-02-17 04:10:18.472 [CORE] Command line Args: C:\Users\Validator\AppData\Local\Microsoft\WindowsApps\winget.exe install --manifest D:\TRANSFER\2495b07b-ea8f-ec11-9502-000d3a9eda90\Manifest.yaml --accept-package-agreements
2022-02-17 04:10:18.472 [CORE] Package: Microsoft.DesktopAppInstaller v1.16.12653.0
2022-02-17 04:10:18.474 [CORE] IsCOMCall:0; Caller: winget-cli
2022-02-17 04:10:18.497 [CLI ] WinGet invoked with arguments: 'install' '--manifest' 'D:\TRANSFER\2495b07b-ea8f-ec11-9502-000d3a9eda90\Manifest.yaml' '--accept-package-agreements'
2022-02-17 04:10:18.497 [CLI ] Found subcommand: install
2022-02-17 04:10:18.497 [CLI ] Leaf command to execute: root:install
2022-02-17 04:10:18.511 [CLI ] Executing command: install
2022-02-17 04:10:18.515 [CLI ] Manifest fields: Name [iCloud], Version [7.21.0.23]
2022-02-17 04:10:18.519 [CLI ] Starting installer selection.
2022-02-17 04:10:18.519 [CLI ] Completed installer selection.
2022-02-17 04:10:18.566 [CLI ] Generated temp download path: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Apple.iCloud.7.21.0.23
2022-02-17 04:10:18.570 [CORE] Downloading to path: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Apple.iCloud.7.21.0.23
2022-02-17 04:10:18.571 [CORE] DeliveryOptimization downloading from url: https://updates.cdn-apple.com/2020/windows/001-39935-20200911-1A70AA56-F448-11EA-8CC0-99D41950005E/iCloudSetup.exe
2022-02-17 04:10:24.797 [CORE] Download completed.
2022-02-17 04:10:36.105 [CORE] Started applying motw to C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Apple.iCloud.7.21.0.23 with zone: 3
2022-02-17 04:10:36.112 [CORE] Finished applying motw
2022-02-17 04:10:36.116 [CLI ] Installer hash verified
2022-02-17 04:10:36.117 [CORE] Started applying motw using IAttachmentExecute to C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Apple.iCloud.7.21.0.23
2022-02-17 04:10:36.122 [CORE] Started removing motw to C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Apple.iCloud.7.21.0.23
2022-02-17 04:10:36.123 [CORE] Finished removing motw
2022-02-17 04:10:42.577 [CORE] Finished applying motw using IAttachmentExecute. Result: 0 IAttachmentExecute::Save() result: 0
2022-02-17 04:10:42.578 [REPO] Creating PredefinedInstalledSource with filter [ARP]
2022-02-17 04:10:42.578 [REPO] Creating new SQLite Index [4294967295.4294967295] at ':memory:'
2022-02-17 04:10:42.578 [SQL ] Opening SQLite connection: ':memory:' [6, 0]
2022-02-17 04:10:42.670 [REPO] Examining ARP entries for Machine | X86
2022-02-17 04:10:42.682 [REPO] Examining ARP entries for User | X86
2022-02-17 04:10:42.967 [CLI ] Installer args: /qn /norestart /passive
2022-02-17 04:10:42.967 [CLI ] Successfully renamed downloaded installer. Path: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Apple.iCloud.7.21.0.23.exe
2022-02-17 04:10:42.967 [CLI ] Starting: 'C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Apple.iCloud.7.21.0.23.exe' with arguments '/qn /norestart /passive'
2022-02-17 04:11:19.303 [CLI ] ShellExecute installer failed: 1603
2022-02-17 04:11:19.305 [CLI ] Terminating context: 0x8a150006 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:23b
```

It's the same error I'm seeing on Windows Sandbox:
image

```
2022-02-17 21:50:16.835 [CORE] WinGet, version [1.3.431-preview], activity [{82A50BB0-63D5-40FA-A9E5-AC13AE940D42}]
2022-02-17 21:50:16.835 [CORE] OS: Windows.Desktop v10.0.22557.1
2022-02-17 21:50:16.835 [CORE] Command line Args: "C:\Users\WDAGUtilityAccount\AppData\Local\Microsoft\WindowsApps\winget.exe" install --manifest C:\Users\WDAGUtilityAccount\Documents\GitHub\winget-pkgs\manifests\a\Apple\iCloud\7.21.0.23
2022-02-17 21:50:16.835 [CORE] Package: Microsoft.DesktopAppInstaller v1.18.431.0
2022-02-17 21:50:16.836 [CORE] IsCOMCall:0; Caller: winget-cli
2022-02-17 21:50:16.844 [CLI ] WinGet invoked with arguments: 'install' '--manifest' 'C:\Users\WDAGUtilityAccount\Documents\GitHub\winget-pkgs\manifests\a\Apple\iCloud\7.21.0.23'
2022-02-17 21:50:16.844 [CLI ] Found subcommand: install
2022-02-17 21:50:16.844 [CLI ] Leaf command to execute: root:install
2022-02-17 21:50:16.847 [CLI ] Executing command: install
2022-02-17 21:50:16.849 [CLI ] Manifest fields: Name [iCloud], Version [7.21.0.23]
2022-02-17 21:50:16.851 [CLI ] Starting installer selection.
2022-02-17 21:50:16.851 [CLI ] Completed installer selection.
2022-02-17 21:50:16.872 [CLI ] Generated temp download path: C:\Users\WDAGUT~1\AppData\Local\Temp\WinGet\Apple.iCloud.7.21.0.23\4cfd20d13cdce2b5c435f2ddaf4ee4c81d976461846bf3b954e8af6cbcdeb9f7
2022-02-17 21:50:16.875 [CORE] Downloading to path: C:\Users\WDAGUT~1\AppData\Local\Temp\WinGet\Apple.iCloud.7.21.0.23\4cfd20d13cdce2b5c435f2ddaf4ee4c81d976461846bf3b954e8af6cbcdeb9f7
2022-02-17 21:50:16.876 [CORE] Started applying motw to C:\Users\WDAGUT~1\AppData\Local\Temp\WinGet\Apple.iCloud.7.21.0.23\4cfd20d13cdce2b5c435f2ddaf4ee4c81d976461846bf3b954e8af6cbcdeb9f7 with zone: 3
2022-02-17 21:50:16.878 [CORE] Finished applying motw
2022-02-17 21:50:16.878 [CORE] WinINet downloading from url: https://updates.cdn-apple.com/2020/windows/001-39935-20200911-1A70AA56-F448-11EA-8CC0-99D41950005E/iCloudSetup.exe
2022-02-17 21:50:28.652 [CORE] Download hash: 4cfd20d13cdce2b5c435f2ddaf4ee4c81d976461846bf3b954e8af6cbcdeb9f7
2022-02-17 21:50:28.652 [CORE] Download completed.
2022-02-17 21:50:28.653 [CLI ] Installer hash verified
2022-02-17 21:50:28.653 [CORE] Started applying motw using IAttachmentExecute to C:\Users\WDAGUT~1\AppData\Local\Temp\WinGet\Apple.iCloud.7.21.0.23\4cfd20d13cdce2b5c435f2ddaf4ee4c81d976461846bf3b954e8af6cbcdeb9f7
2022-02-17 21:50:28.663 [CORE] Finished applying motw using IAttachmentExecute. Result: 0 IAttachmentExecute::Save() result: 0
2022-02-17 21:50:28.663 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp(141)\WindowsPackageManager.dll!00007FFB3E795295: (caller: 00007FFB3E5F4881) LogHr(1) tid(149c) 8007023E {Application Error}

The exception %s (0x    Msg:[std::exception: rename: The system cannot find the file specified.: "C:\Users\WDAGUT~1\AppData\Local\Temp\WinGet\Apple.iCloud.7.21.0.23\4cfd20d13cdce2b5c435f2ddaf4ee4c81d976461846bf3b954e8af6cbcdeb9f7", "C:\Users\WDAGUT~1\AppData\Local\Temp\WinGet\Apple.iCloud.7.21.0.23\iCloudSetup.exe"] 

2022-02-17 21:50:28.665 [CLI ] Successfully renamed downloaded installer. Path: C:\Users\WDAGUT~1\AppData\Local\Temp\WinGet\Apple.iCloud.7.21.0.23\iCloudSetup.exe
2022-02-17 21:50:28.682 [REPO] Source named 'msstore' is already defined at origin User. The source from origin Default is dropped.
2022-02-17 21:50:28.682 [REPO] Creating PredefinedInstalledSource with filter [ARP]
2022-02-17 21:50:28.682 [REPO] Creating new SQLite Index [4294967295.4294967295] at ':memory:'
2022-02-17 21:50:28.682 [SQL ] Opening SQLite connection: ':memory:' [6, 0]
2022-02-17 21:50:28.742 [REPO] Examining ARP entries for Machine | X64
2022-02-17 21:50:28.742 [REPO] Examining ARP entries for Machine | X86
2022-02-17 21:50:28.742 [REPO] Examining ARP entries for User | X64
2022-02-17 21:50:28.788 [CLI ] Installer args: /qn /norestart /passive
2022-02-17 21:50:28.789 [CLI ] Starting: 'C:\Users\WDAGUT~1\AppData\Local\Temp\WinGet\Apple.iCloud.7.21.0.23\iCloudSetup.exe' with arguments '/qn /norestart /passive'
2022-02-17 21:50:53.065 [CLI ] ShellExecute installer failed: 1603
2022-02-17 21:50:53.067 [CLI ] Terminating context: 0x8a150006 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:162
```

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
You can set this PR to DRAFT mode until dependency support has been added to WinGet.

**Review by ItzLevvie — APPROVED** [review]

**Comment by Macleykun** [comment]
Heya, wanted to ask how it's going with adding that deps support
is there an issue to link to i can keep an eye on?

**Comment by jedieaston** [comment]
@Macleykun you can keep an eye on https://github.com/microsoft/winget-cli/issues/163

**Comment by Macleykun** [comment]
heya, wanted to ask if it's possible to add dependencies like Media Feature pack. Then i can finish this one off and we all can enjoy icloud and itunes in an easy way for altstore :)

**Comment by jedieaston** [comment]
We can't add dependencies like that yet, feature dependencies are still unsupported: https://github.com/microsoft/winget-cli/issues/556 (despite the comments on that thread, this functionality is planned. there's schema support for it but the client doesn't know how to install features yet)

**Comment by Macleykun** [comment]
> We can't add dependencies like that yet, feature dependencies are still unsupported: [microsoft/winget-cli#556](https://github.com/microsoft/winget-cli/issues/556) (despite the comments on that thread, this functionality is planned. there's schema support for it but the client doesn't know how to install features yet)

Thanks for your quick response! I've subbed to it and i'll keep an eye on it :) <3

**Pull request closed without merging**
