### PR TITLE
Lexicool.LexibarFR version 1.4f

### PR DESCRIPTION
**Pull request by UtilisateurDeGithu**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/90570)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
Please merge all of your Lexicool.Lexibar pull requests into a single manifest and use the `InstallerLocale` property for each installer

**Comment by UtilisateurDeGithu** [comment]
@trenly I created 3 pull requests because this is not just translation, every software has different functionnality, that means this is 3 different software for each pull request I submitted.

**Comment by Trenly** [comment]
> @Trenly I created 3 pull requests because this is not just translation, every software has different functionnality, that means this is a different software for each pull request I submitted.

In that case, sub-packages should be used like `Lexicool.Lexibar.FR` (Note the extra . in the identifier) which will make it easier for people searching `Lexibar` to find the software

**Comment by UtilisateurDeGithu** [comment]
Pull request transfered to [https://github.com/microsoft/winget-pkgs/pull/90765](https://github.com/microsoft/winget-pkgs/pull/90765)

**Comment by UtilisateurDeGithu** [comment]
pull request transfered to [https://github.com/microsoft/winget-pkgs/pull/90765](https://github.com/microsoft/winget-pkgs/pull/90765)

**Pull request closed without merging**
