### PR TITLE
Kingdraw 1.1.0.0

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
- [y] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [y] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [y] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [y] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2276)

### CODE REVIEW

**Comment by denelon** [comment]
I did not see how to run the App after the install. I also did not see how to remove the App from Add/Remove. @oxygen-dioxide Can you provide some guidance?

**Comment by oxygen-dioxide** [comment]
The default installation destination is "D:\KingDraw". Do you have D:\? 
Or can I use command line arguments to change the installation destination? The installer type is nullsoft.

**Comment by KevinLaMS** [comment]
We are blocked because this app defaults to D and we do not have a means to specify alternative location.
https://github.com/microsoft/winget-cli/issues/201

**Comment by denelon** [comment]
Any chance Kingdraw has been updated not to need a D: drive?

**Pull request closed without merging**
