### PR TITLE
Added PRTest.ps1.

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?

-----

This PR adds a new PowerShell (5.1+) script to the Tools directory, called `PRTest.ps1`. It is designed for use mostly by moderators when doing manual validation of manifests. 

Presuming you have the GitHub CLI installed (and if you don't, it exits), running `.\Tools\PRTest.ps1 <PRNumber>` will checkout the pull request and use the SandboxTest script to launch it inside a Windows Sandbox. Adding the `-Review` flag will open the PR review tab in your default browser, allowing for easy addition of comments.

I apparently don't have enough permissions to add reviewers, so @OfficialEsco @ItzLevvie @palenshus @denelon.
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/20105)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Hmm, so since i use Virtualbox instead of Hyper-V on my Home computer i decided to implement this to my Virtualbox VM, and boooi it took some tinkering, first of all, you also needs Git, second you need to have a fork and be in the winget repo folder, also there is no error messages for those issues >_>

**Review by denelon — APPROVED** [review]

**Comment by jedieaston** [comment]
@OfficialEsco let me work on some changes then. I didn't think about not having git (since you need it to checkout a branch, unless there's some special magic with wingetcreate I haven't tried yet), and the reason it tries to look for the winget repository is because it needs to find the SandboxTest.ps1 script (I suppose it could take the path to it as a parameter, or look for it in the $PATH? How do you typically use it?).

**Comment by OfficialEsco** [comment]
> and the reason it tries to look for the winget repository root is because it needs to find the SandboxTest.ps1 script (I suppose it could take the path to it as a parameter, or look for it in the $PATH? How do you typically use it?).

No no, GIT dosn't work outside of a repo, it will throw and end the script way before any of your error messages 😁

**Comment by jedieaston** [comment]
GitHub CLI and Git both expect to be in the root of a repo (or else GitHub CLI doesn't know how to do a checkout anyway, even if I didn't try to use Git to find the Tools folder before that). There's a possibility I can work around this, but I kind of need to understand how you usually use SandboxTest.ps1 (so I know how to look for it). Then I can figure out how to do a checkout without being in the repo, and it should be fixed (🤞).

**Comment by vedantmgoyal2009** [comment]
Hi, I am using this script to checkout my OWN PR, but seems like it doesn't work.  
image

**Comment by vedantmgoyal2009** [comment]
Please help! 🙏🏻

**Comment by ItzLevvie** [comment]
Have you ran `gh auth login` as that's what the error message's saying?

**Comment by vedantmgoyal2009** [comment]
> Have you ran `gh auth login` as that's what the error message's saying?

image

**Comment by vedantmgoyal2009** [comment]
> I was able to use the script. It did have me log in with 2FA. Just another data point 😊.

I have read it again. It said, "It is designed for use mostly by moderators when doing manual validation of manifests." That means I can't use it as I am still not a moderator. 😢

> * [x]  Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
> * [x]  Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
> 
> This PR adds a new PowerShell (5.1+) script to the Tools directory, called `PRTest.ps1`. It is designed for use mostly by moderators when doing manual validation of manifests.
> 
> Presuming you have the GitHub CLI installed (and if you don't, it exits), running `.\Tools\PRTest.ps1 <PRNumber>` will checkout the pull request and use the SandboxTest script to launch it inside a Windows Sandbox. Adding the `-Review` flag will open the PR review tab in your default browser, allowing for easy addition of comments.
> 
> I apparently don't have enough permissions to add reviewers, so @OfficialEsco @ItzLevvie @palenshus @denelon.
> 
> ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/20105)

**Comment by vedantmgoyal2009** [comment]
> I was able to use the script. It did have me log in with 2FA. Just another data point 😊.

I tried but ending up with same result.
`GraphQL error: Could not resolve to a Repository with the name 'vedantmgoyal2009/test-sign-key'.
There was an error checking out the PR. Make sure you're logged into GitHub via 'gh auth login' and come back here!`

**Comment by vedantmgoyal2009** [comment]
I don't know why it is requiring a repository with the name `test-sign-key`

**Comment by vedantmgoyal2009** [comment]
After creating the test-sign-key repository:
image

**Comment by ImJoakim** [comment]
@vedantmgoyal2009 Try the following (if you haven't already):

1. Install GitHub CLI (https://cli.github.com/) and Git (https://git-scm.com/download/win)
2. Go into the directory you would like to clone the repository to in PowerShell.
3. `gh auth login` -> sign in.
4. `gh repo clone microsoft/winget-pkgs` (while being in the directory you want it to clone to).
5. Run the `PRTest.ps1` while you're in the directory of the cloned repository.

**Comment by vedantmgoyal2009** [comment]
Thanks, it worked now...

**Comment by ItzLevvie** [comment]
I'm using `git -C` so I don't have to be in the repository directory. You could also remove the Git CLI dependency for PR checkout because you can do it in Git instead.

This is how I'm doing it:
```batch
@echo off
cls

:1
winget --version > nul 2>&1
if %ERRORLEVEL% == 9009 (
    echo Windows Package Manager is not installed.
    goto :EOF
)
(
    echo {
    echo     "network": { "downloader": "wininet" },
    echo     "visual": { "progressBar": "rainbow" }
    echo }
) > "C:/Users/%USERNAME%/AppData/Local/Packages/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe/LocalState/settings.json"
git --version > nul 2>&1
if %ERRORLEVEL% == 9009 (
    echo Git is not installed.
    goto :EOF
)
set REPOSITORY_PATH="C:/Users/%USERNAME%/Documents/GitHub/winget-pkgs"
if not exist %REPOSITORY_PATH% (
    echo %REPOSITORY_PATH% does not exist.
    goto :EOF
)
goto :2

:2
set PR_NUMBER=
set /p PR_NUMBER="Please enter the pull request number: "
if "%PR_NUMBER%" == "" goto :2
git -C %REPOSITORY_PATH% fetch upstream master > nul 2>&1
git -C %REPOSITORY_PATH% fetch upstream refs/pull/%PR_NUMBER%/head:pull/%PR_NUMBER% > nul 2>&1
::if %ERRORLEVEL% == 128 (
    ::echo "%PR_NUMBER%" does not exist.
    ::goto :2
::)
git -C %REPOSITORY_PATH% checkout pull/%PR_NUMBER% > nul 2>&1
goto :3

:3
REM PowerShell has an easy way to figure out the directory path when doing a 'changed files' diff between Git branches and/or commits.
REM Because we're using Batch, we're using a for loop to split words that has a forward-slash (/) but we don't actually want the <Publisher>.<ApplicationName>.yaml part.
REM otherwise the validation of manifests will fail.
REM This means that manifests/m/Microsoft/Teams/1.4.00.19000/Microsoft.Teams.yaml becomes:
REM manifests
REM m
REM Microsoft
REM Teams
REM 1.4.00.19000
REM Each line has its own variable so this means that we can combine it to make a directory path
REM (e.g. manifests/m/Microsoft/Teams/1.4.00.19000) that the Windows Package Manager can understand to validate and install manifests for the 1.0.0 schema.
REM This is, of course, a 'hacky' way of doing it and can break when a directory path like this: manifests/m/Microsoft/VisualStudio/IntPreview/17/Enterprise/0.0.0.0 (8 folders).
REM but if that ever happens we can do set DIRECTORY_PATH_8="%%a/%%b/%%c/%%d/%%e/%%f/%%g/%%h" and modify the code below to install manifests with 8 folders.
for /f "tokens=1,2,3,4,5,6,7 delims=/" %%a in ('git -C %REPOSITORY_PATH% diff --name-only --diff-filter=d upstream/master...pull/%PR_NUMBER%') do (
    set DIRECTORY_PATH_5="%%a/%%b/%%c/%%d/%%e"
    set DIRECTORY_PATH_6="%%a/%%b/%%c/%%d/%%e/%%f"
    set DIRECTORY_PATH_7="%%a/%%b/%%c/%%d/%%e/%%f/%%g"
)
echo Checking if the directory path to the manifest has 5 folders.
set DIRECTORY_PATH=%DIRECTORY_PATH_5%
winget validate --manifest %REPOSITORY_PATH%/%DIRECTORY_PATH_5% > nul 2>&1
if %ERRORLEVEL% == -1978335191 (
    echo Checking if the directory path to the manifest has 6 folders.
    set DIRECTORY_PATH=%DIRECTORY_PATH_6%
    winget validate --manifest %REPOSITORY_PATH%/%DIRECTORY_PATH_6% > nul 2>&1
)
if %ERRORLEVEL% == -1978335191 (
    echo Checking if the directory path to the manifest has 7 folders.
    set DIRECTORY_PATH=%DIRECTORY_PATH_7%
    winget validate --manifest %REPOSITORY_PATH%/%DIRECTORY_PATH_7% > nul 2>&1
)
winget validate --manifest %REPOSITORY_PATH%/%DIRECTORY_PATH%
winget install --manifest %REPOSITORY_PATH%/%DIRECTORY_PATH%
goto :4

:4
git -C %REPOSITORY_PATH% checkout --detach upstream/master > nul 2>&1
git -C %REPOSITORY_PATH% branch --delete --force pull/%PR_NUMBER% > nul 2>&1
pause
cls
goto :2

```

**Comment by vedantmgoyal2009** [comment]
Well, I neither use `gh` nor `git`, I used GitHub Desktop 😅
image

**Comment by OfficialEsco** [comment]
Well that is why this script is for Moderators and not another step in the SandboxTest.ps1 chain..
You gain nothing from using this on your PR.

**Comment by vedantmgoyal2009** [comment]
> I'm using `git -C` so I don't have to be in the repository directory. You could also remove the Git CLI dependency for PR checkout because you can do it in Git instead.
Your script throws an error, please tell me how to fix it.
image

**Pull request merged**
