### PR TITLE
Merge Thunderbird v78.0

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/10885)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
@KevinLaMS Can you do /AzurePipelines run here? pretty sure it just bugged out for a few minutes when i submitted this one

**Comment by hackean-msft** [comment]
@OfficialEsco The url https://www.mozilla.org/en-US/privacy/website does not exists. Can you fix this url. For help see PrivacyUrl property. 

Thanks.

**Comment by OfficialEsco** [comment]
@hackean-msft ahhh right, its fixed now

**Pull request merged**
