### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
As my project now automatically updates all the packages which are distributed via GitHub Releases, I think this should be added in the README in order to avoid duplicates.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/29258)

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@denelon

**Review by jedieaston — CHANGES_REQUESTED** [review]
This project is not supported by Microsoft and ~~doesn't run anywhere where we can see it (I don't see GitHub actions set up on that repo)~~ (found them). As such, I don't think it should be mentioned in README.md.

Just have your script check master to see if someone got to it first, it's what the rest of us do (or, at least what I do).

(Also -- I'm starting to wonder if there's a place for a "official" community project to create GitHub Actions or something on this repo that automatically update stuff in a smarter way than just checking if the hash has changed like wingetbot does.)

**Comment by vedantmgoyal2009** [comment]
@jedieaston Wait... I think you have gone wrong? GitHub Workflow Runs can be very easily found: https://github.com/vedantmgoyal2009/winget-pkgs-automation/actions/workflows/automation.yml.

**Comment by jedieaston** [comment]
Yeah, I was looking in the wrong place. Apologies.

Doesn't change my point though, this isn't supported by Microsoft.

**Comment by denelon** [comment]
We have work on the backlog to look at doing essentially the same thing. Rather than re-inventing the wheel we will likely ask for proposals from the community to see what the best path forward is. Part of this work will involve attempting to identify the best source/mechanism for updating packages. There are several different community members keeping collections up to date. We would still prefer to have publishers provide their own manifests, but this would be a secondary option until then. 

We would also be more likely to use and suggest https://github.com/microsoft/wingetcreate as it has the ability to detect architectures and installer types. I'm expecting to change the pipelines to use that tool instead of the code we originally wrote before the Windows Package Manager Manifest Creator existed.

**Comment by vedantmgoyal2009** [comment]
https://github.com/microsoft/winget-pkgs/issues/500#issuecomment-932892281

**Comment by vedantmgoyal2009** [comment]
> We would still prefer to have publishers provide their own manifests, but this would be a secondary option until then.

This is the best option but I also agree with Felipe Santos that "_But there are some packages in which the developers of it will never care about doing so, but still, we would want them up-to-date in WinGet repo._"

**Comment by denelon** [comment]
I totally agree with @felipecrs on that.

One of the things we've been considering is leveraging the .package file (similar to the .validation) file to identify the source and mechanism for detecting updates, and generating manifests. The good news about that approach is once the publisher has become "verified", it's the same file to let them start managing updates themselves.

**Comment by vedantmgoyal2009** [comment]
I was already prepared for that 🙂 and I am already skipping packages from the automatic upgrade like Oh-my-posh and Rainmeter, etc... (these two I have them on my fingers) which are already automated/published by the developer.

**Comment by jedieaston** [comment]
I like the idea of having designated community members that usually update specific packages. Some people here know a lot about how certain apps install (Visual Studio and Python are two example off the top of my head) and it would be nice to have that written down somewhere. Not to pin responsibility on anyone, of course, but having a designated .package or .maintainer file that says "@jedieaston knows about this, mention them in issues" wouldn't be a bad idea. 

Chocolatey has something similar, see the "Package Maintainers" section to the left of [this page](https://community.chocolatey.org/packages/GoogleChrome).

**Comment by jedieaston** [comment]
Also, re searching for open PRs, you can use `in:path <path to files>` in GitHub's PR search to find pull requests that modify certain paths in the repo. It would be not too hard to see if there was already a PR for a certain version of a package.

For example, `is:pr in:path manifests/m/Microsoft/Edge/94.0.992.38` gets me [my PR from earlier today](https://github.com/microsoft/winget-pkgs/pull/29290) which adds version 94.0.992.38 of Microsoft Edge.

**Comment by vedantmgoyal2009** [comment]
> @vedantmgoyal2009 your project is brilliant, really.

Thank you. It made my day to hear that.

> That said, the concern from @jedieaston about not being a Microsoft supported project is valid (I believe).
> 
> I think the farest you could reach would be:
> 
> After the new "verified" mechanism is in place (referring to @denelon's [message](https://github.com/microsoft/winget-pkgs/pull/29258#issuecomment-933591056)), you could apply for claiming the responsibility for the packages which your project updates automatically.
> 
> And then, this PR could be changed to something like:
> 
> > You can apply for claiming the responsibility of updating packages through [link] and then write code for updating it in the WinGet repo automatically. As example, there are some projects in the community which already does that:
> https://github.com/vedantmgoyal2009/winget-pkgs-automation
> 
> This would solve the issue about not-being a Microsoft supported project, I guess.

Yes, this can be the better option as it gives the opportunity to other community members. This way, more users would get the chance to contribute to the repository in this way. I would like to know if the Microsoft team agrees with this.

> Also, re searching for open PRs, you can use `in:path <path to files>` in GitHub's PR search to find pull requests that modify certain paths in the repo. It would be not too hard to see if there was already a PR for a certain version of a package (you can [search PRs via GitHub's API](https://docs.github.com/en/rest/reference/search#search-issues-and-pull-requests)).
> 
> For example, `is:pr in:path manifests/m/Microsoft/Edge/94.0.992.38` gets me [my PR from earlier today](https://github.com/microsoft/winget-pkgs/pull/29290) which adds version 94.0.992.38 of Microsoft Edge.

@jedieaston The search API gives only 30 requests per minute so I will have to be careful. I am already making a thousand requests (approximately) in a very short amount of time. Btw, I have created an issue on my repo (https://github.com/vedantmgoyal2009/winget-pkgs-automation/issues/18) for which I will start working within a week or so.

**Comment by denelon** [comment]
Do we know who else has built automation like this? I'd rather have a "community" section in the README than to point to a specific one in the event there may be others. I also want to reference some of the work we have on the backlog to further refine the functionality and bring it into this repository as a longer term plan. I think we might make an automation specific page declaring some of our preferences like publishers submitting their own manifests. It also makes it easier to mention the Windows Package Manager Manifest Creator, and tie that into CI/CD scenarios. I can also see some benefit in providing a template to make it easier to submit requests to other open source projects with instructions and options for automation.

**Comment by vedantmgoyal2009** [comment]
> Also, re searching for open PRs, you can use `in:path <path to files>` in GitHub's PR search to find pull requests that modify certain paths in the repo. It would be not too hard to see if there was already a PR for a certain version of a package (you can [search PRs via GitHub's API](https://docs.github.com/en/rest/reference/search#search-issues-and-pull-requests)).
> 
> For example, `is:pr in:path manifests/m/Microsoft/Edge/94.0.992.38` gets me [my PR from earlier today](https://github.com/microsoft/winget-pkgs/pull/29290) which adds version 94.0.992.38 of Microsoft Edge.

Searching this, it should give #29349 in the result.
image

**Comment by jedieaston** [comment]
@denelon The GitHub CLI repo has [one](https://github.com/cli/cli/blob/93cea6d370992d4dc0bfc9206389d199ce196ac4/.github/workflows/releases.yml#L200), as does Azure CLI (I don't think theirs is public, though). 

I can come up with a few others though.

**Pull request closed without merging**
