### PR TITLE
Oracle.MySQLWorkbench version 8.0.34

### PR DESCRIPTION
**Pull request by optsing**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/119555)

### CODE REVIEW

**Comment by optsing** [comment]
Published too early, PR requires a working Dependencies feature, what will happen with the 1.6 release.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335226 
2023-09-13 09:47:55.379 [CLI ] ShellExecute installer failed: 1603 Property(S): ErrorDialog = SetupErrorDialog 
MSI (s) (B4:BC) [09:47:55:062]: Product: MySQL Workbench 8.0 CE -- Installation operation failed. 
MSI (s) (B4:BC) [09:47:55:062]: Windows Installer installed the product. Product Name: MySQL Workbench 8.0 CE. Product Version: 8.0.34. Product Language: 1033. Manufacturer: Oracle Corporation. Installation success or error status: 1603. 

Yes, `1603` often indicates a missing dependency.

**Comment by stephengillie** [comment]
This installs and launches normally in a Windows 10 VM.

**Comment by stephengillie** [comment]
I applied the waiver in error. I assumed that this PR was updating an extant manifest. We'll be accepting new packages with dependencies soon, after the upcoming 1.6 release.

**Review by Trenly — APPROVED** [review]

**Pull request merged**
