### PR TITLE
Metro Commander version 1.3.87.0

### PR DESCRIPTION
**Pull request by ValeraFinebits**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/18164)

### CODE REVIEW

**Comment by ValeraFinebits** [comment]
Where can I find logs to find out what the problem is?

**Comment by OfficialEsco** [comment]
> [X] Have you tested your manifest locally with winget install --manifest <path>?

```
PS C:\Users\Esco\Downloads> winget install -m M:\f\Finebits\MetroCommander\1.3.87.0\
Found Metro Commander [Finebits.MetroCommander]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://finebitsstorage.z22.web.core.windows.net/metrocommander/packages/MC_1.3.87.0.msix
  ██████████████████████████████   106 MB /  106 MB
Successfully verified installer hash
Starting package install...
  ██████████████████████████████  0%
Install failed: Windows cannot install package BOOSTUDIOLLC.METROCOMMANDER_1.3.87.0_x86__b6e429xa66pga because this package depends on a framework that could not be found. Provide the framework "Microsoft.UI.Xaml.2.3" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x86 processor architecture and minimum version 2.31912.11002.0, along with this package to install. The frameworks with name "Microsoft.UI.Xaml.2.3" currently installed are: {}
0x80073cf3 : Package failed updates, dependency or conflict validation.
```

Just tested the 1.3.86.0 Manifest and it seems to have the same issue
```
PS C:\Users\Esco\Downloads> winget install -m M:\f\Finebits\MetroCommander\1.3.86.0\
Found Metro Commander [Finebits.MetroCommander]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://finebitsstorage.z22.web.core.windows.net/metrocommander/packages/MC_1.3.86.0.msix
  ██████████████████████████████   189 MB /  189 MB
Successfully verified installer hash
Starting package install...
  ██████████████████████████████  0%
Install failed: Windows cannot install package BOOSTUDIOLLC.METROCOMMANDER_1.3.86.0_x64__b6e429xa66pga because this package depends on a framework that could not be found. Provide the framework "Microsoft.UI.Xaml.2.3" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 2.31912.11002.0, along with this package to install. The frameworks with name "Microsoft.UI.Xaml.2.3" currently installed are: {}
0x80073cf3 : Package failed updates, dependency or conflict validation.
```
This was detected in https://github.com/microsoft/winget-pkgs/pull/621 but it somehow got approved AFTER adding the `Validation-MSIX-Dependency` label..

**Comment by ValeraFinebits** [comment]
Yes, I tested. It perfectly working locally.

**Comment by OfficialEsco** [comment]
> Yes, I tested. It perfectly working locally.

You're not wrong, it says locally... Should get changed to VM/Sandbox or properly tested..

When you manually run the installer it installs Microsoft Engagement Framework and Microsoft.UI.Xaml.2.3
image
however when you do it from command prompt it doesn't

Also you did get a answer from a technician https://github.com/microsoft/winget-pkgs/pull/16142#issuecomment-864268773

**Comment by ValeraFinebits** [comment]
I deleted Microsoft.Advertising.Xaml, but I can't remove the dependence on Microsoft.UI.Xaml.
What can I do to install Microsoft.UI.Xaml with winget?

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-cli/issues/163
And you need to add Dependency's in the Installer Manifest, since its not supported yet we have no documentation on how to do Packages outside of the Winget Pkgs Repo
```
"Dependencies": {
      "type": [ "object", "null" ],
      "properties": {
        "WindowsFeatures": {
          "type": [ "array", "null" ],
          "items": {
            "type": "string",
            "minLength": 1,
            "maxLength": 128
          },
          "maxItems": 16,
          "uniqueItems": true,
          "description": "List of Windows feature dependencies"
        },
        "WindowsLibraries": {
          "type": [ "array", "null" ],
          "items": {
            "type": "string",
            "minLength": 1,
            "maxLength": 128
          },
          "maxItems": 16,
          "uniqueItems": true,
          "description": "List of Windows library dependencies"
        },
        "PackageDependencies": {
          "type": [ "array", "null" ],
          "items": {
            "type": "object",
            "properties": {
              "PackageIdentifier": {
                "$ref": "#/definitions/PackageIdentifier"
              },
              "MinimumVersion": {
                "$ref": "#/definitions/PackageVersion"
              }
            },
            "required": [ "PackageIdentifier" ]
          },
          "maxItems": 16,
          "uniqueItems": true,
          "description": "List of package dependencies from current source"
        },
        "ExternalDependencies": {
          "type": [ "array", "null" ],
          "items": {
            "type": "string",
            "minLength": 1,
            "maxLength": 128
          },
          "maxItems": 16,
          "uniqueItems": true,
          "description": "List of external package dependencies"
        }
      }
    },
```

Example of Dependency which exist in the winget pkgs repo

```
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VC++2015-2019Redist-x64
    MinimumVersion: 14.28.29913.0
```

**Comment by OfficialEsco** [comment]
Yeeeeh there is no way, you just have to wait for dependency support

**Pull request closed without merging**
