### PR TITLE
Delete manifests/a/ArmCord directory

### PR DESCRIPTION
**Pull request by SomeAspy**
ArmCord has been DMCA'd by ARM LLC.
We are rebranding to legcord, and starting versioning from 1.0.0

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/182322)

### CODE REVIEW

**Comment by SomeAspy** [comment]
@microsoft-github-policy-service agree

**Comment by SomeAspy** [comment]
This is indeed, an abnormal PR. I looked looked around a bit to see if there was a defined process for deleting a package, but didn't find one.

**Comment by stephengillie** [comment]
URL: https://github.com/ArmCord/ArmCord/releases/download/v3.0.8/ArmCord.Setup.3.0.8.exe 
Status Code: 200

(Automated message - build 896)

**Comment by SomeAspy** [comment]
I understand they still exist, but they are a redirect to to the legcord releases pages, which are still under the name armcord
We will be removing these builds, as we are restarting versioning from 1.0.0.
https://github.com/Legcord/Legcord/releases/tag/v1.0.0

**Comment by stephengillie** [comment]
URL: https://github.com/ArmCord/ArmCord/releases/download/v3.0.8/ArmCord.Setup.3.0.8.exe 
Status Code: 200

(Automated message - build 896)

**Comment by stephengillie** [comment]
URL: https://github.com/ArmCord/ArmCord/releases/download/v3.0.8/ArmCord.Setup.3.0.8.exe 
Status Code: 200

(Automated message - build 897)

**Comment by stephengillie** [comment]
URL: https://github.com/ArmCord/ArmCord/releases/download/v3.0.8/ArmCord.Setup.3.0.8.exe 
Status Code: 200

(Automated message - build 897)

**Comment by SomeAspy** [comment]
Hi @Trenly 
I hope this is not a bother, but I'm not sure what else to do here.
The bot seems to be stuck at the fact that the download links are still up
Would you be able to override this?
Thanks!

**Comment by Trenly** [comment]
@someaspy - The validation and publishing pipelines can only change one manifest at a time. You will need to submit separate PRs removing each version

**Comment by SomeAspy** [comment]
Oh I see, I will do that in a moment, Thank you

**Pull request closed without merging**
