### PR TITLE
New package: GlennDelahoy.SnappyDriverInstallerOrigin version 1.12.9

### LINKED ISSUE #32778: [Package Request]: Snappy Driver Installer
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Glenn Delahoy
Publisher Url: https://www.snappy-driver-installer.org
Package Name: SDIO
Description: Driver Installation and Update Tool
Package Version: 1.11.3
Installer URL: https://www.snappy-driver-installer.org/downloads/SDIO_1.11.3.738.zip

Current Package Identifier (for new versions):

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

* Resolves #32778 

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/99150)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/99150)

### CODE REVIEW

**Comment by Trenly** [comment]
Uhhh - @denelon - the glitch where its re-running perfectly good PRs is back

**Comment by Trenly** [comment]
Disabling auto merge to allow eng to investigate

**Comment by mdanish-kh** [comment]
@Trenly Automerge got re-enabled; You might want to disable it again or add a blocking label if we need to hold off this PR.. 👀

**Review by stephengillie — APPROVED** [review]

**Comment by Trenly** [comment]
Welp, guess it didn’t stay disabled

**Pull request merged**
