### PR TITLE
gerardog.gsudo version 1.0.0.0

### PR DESCRIPTION
**Pull request by KaranKad**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/24207)

### CODE REVIEW

**Comment by gerardog** [comment]
> Duration: 22m 7s

I don't know how these winget pipelines work, but I guess its hanging on the expected UAC popup that raises when you call 'gsudo.exe'.

**Comment by KaranKad** [comment]
I don't think UAC will be an issue because validation is done with admin privilege.
This is the issue, because of new release smartscreen thinks this application is not regularly downloaded and blocks it.
image

**Comment by palenshus** [comment]
An almost-dupe of https://github.com/microsoft/winget-pkgs/pull/24207

**Comment by KaranKad** [comment]
image
Should work now

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
