### PR TITLE
Remove PDFCreator Free version 4.4.1

### PR DESCRIPTION
**Pull request by karlo-mirkovic**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135044)

### CODE REVIEW

**Comment by karlo-mirkovic** [comment]
Hello,

I am a part of the development team of the PDFCreator software and have recently started publishing our packages to the winget-pkgs repo. What we noticed is that other users (not associated with our company) published older versions of our free software. While the company does appreciate this, we (the creators of the software) will be publishing the newer packages ourselves from this point forward.

As a result, what I'm attempting to do in this PR is remove these old packages as we will be publishing our packages under the publisher "Avanquestpdfforge". Seeing as the packages in this PR are outdated and inconsistent with this naming scheme, they might be confusing for some users. 
 
Would it be possible to remove these packages? Apologies if this is not the correct way of achieving this, I couldn't find any documentation on the proper steps necessary to remove a package from the repository.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-17T07:57:01.9842268Z Set build variables.

(Automated response - build 586.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-17T07:41:48.3448650Z ##[error] One or more errors occurred. (The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.) The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.

(Automated response - build 596.)

**Comment by stephengillie** [comment]
Hi @karlo-mirkovic,

We have a limit of 1 manifest change, addition, or removal per PR. This PR modifies more than one PR. Can these changes be spread across multiple PRs?

(Automated response - build 597.)

**Comment by karlo-mirkovic** [comment]
Hi @stephengillie,

I have separated the three commits into three different PRs.
PDFCreator Free 4.4.2 removal: https://github.com/microsoft/winget-pkgs/pull/135298
PDFCreator Free 5.1.2 removal: https://github.com/microsoft/winget-pkgs/pull/135299

**Comment by stephengillie** [comment]
> Hi @ stephengillie,
> 
> I have separated the three commits into three different PRs. PDFCreator Free 4.4.2 removal: #135298 PDFCreator Free 5.1.2 removal: #135299

Thanks!

**Comment by stephengillie** [comment]
URL: https://cdn.download.pdfforge.org/pdfcreator/4.4.1/PDFCreator-4_4_1-Setup.exe 
Status Code: 200

(Automated message - build 602)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
