### PR TITLE
IrfanSkiljan.IrfanView_PlugIns version 4.60

### PR DESCRIPTION
**Pull request by borque**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/81899)

### CODE REVIEW

**Comment by borque** [comment]
@microsoft-github-policy-service agree [company="{your company}"]

**Comment by borque** [comment]
@microsoft-github-policy-service agree

**Comment by borque** [comment]
closes #80745

**Review by borque — COMMENTED** [review]
Closes #80745

**Comment by borque** [comment]
I have checked on the installer URLs issue.
I have no problems in obtaining both (x86 and x64) installers using the URLs provided in the manifest.
To make sure it works on other machines as well I have double checked on a foreign machine in a different network.

**Comment by ItzLevvie** [comment]
Close with reason: Please see LINK;

**Pull request closed without merging**
