### PR TITLE
Remove old version of JanDeDobbeleer.OhMyPosh

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
null

### CODE REVIEW

**Comment by KaranKad** [comment]
Because the exe version in control panel shows version as `21.02 alpha` and msi version shows as `21.02.00.0`, to winget they seem completely different versions and thus cause problem using winget upgrade.

**Comment by quhxl** [comment]
Please add the ProductCodes...

**Comment by vedantmgoyal2009** [comment]
Ok, will add tomorrow

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
