### PR TITLE
JanDeDobbeleer.OhMyPosh version 6.42.1

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/39428)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Comment by JanDeDobbeleer** [comment]
I moved to allowing an install for all users as well as the current user meaning there's a popup now asking this context to the user. What's the best way to pass the validation with that change? There's not yet a way to override arguments if I read correctly.

**Comment by jedieaston** [comment]
You'll need to add a command line argument to your Inno Setup file that controls whether to install for all users or just the current one (https://stackoverflow.com/questions/3618257/is-it-possible-to-accept-custom-command-line-parameters-with-inno-setup). Then, you can add multiple installer entries to your manifest with different scopes that include said command line argument, like so:

```
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v6.42.1/install-amd64.exe
  InstallerSha256: 588963560DA039F79FBF58E93A139A1C4C4681BC870C1C26AE3A74A5D3B387EA
  Scope: user
  InstallerSwitches:
      Custom: /justme
- Architecture: x64
  InstallerUrl: https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v6.42.1/install-amd64.exe
  InstallerSha256: 588963560DA039F79FBF58E93A139A1C4C4681BC870C1C26AE3A74A5D3B387EA
  Scope: machine
  InstallerSwitches:
     Custom: /allusers
- Architecture: arm64
  InstallerUrl: https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v6.42.1/install-arm64.exe
  InstallerSha256: B97E075E5885E911A81F42FE18EDE0B240DE6A8C0F42D8797BBDF977F7BA1492
  Scope: user
  InstallerSwitches:
      Custom: /justme
- Architecture: arm64
  InstallerUrl: https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v6.42.1/install-arm64.exe
  InstallerSha256: B97E075E5885E911A81F42FE18EDE0B240DE6A8C0F42D8797BBDF977F7BA1492
  Scope: machine
  InstallerSwitches:
      Custom: /allusers
```

(as an example, of course you'll need to setup the switches how you like).

**Comment by JanDeDobbeleer** [comment]
The switches already exist so that should be straightforward. How does that work from a consumer perspective with those changes? As in, how does a user select which one to run?

**Review by ImJoakim — APPROVED** [review]

**Comment by jedieaston** [comment]
@JanDeDobbeleer The user can use the `--scope` argument from the command line (or set a preference in `winget settings`) to select it. By default, winget will use the user scoped one.

`winget install JanDeDobbeleer.OhMyPosh --scope machine` installs it for the entire machine for example.

**Pull request merged**
