### PR TITLE
calibre: fix download links

### LINKED ISSUE #133004: [Package Issue]: calibre.calibre broken download links
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Manifests for some recent versions of Calibre are using github links for `InstallerUrl` but these become stale after a new release, since they delete old release artifacts from github for some reason. (@kovidgoyal why?)

This makes it impossible to install or upgrade when a new version is released but not yet included in winget.

Instead of

```
https://github.com/kovidgoyal/calibre/releases/download/v${version}/calibre-64bit-${version}.msi
```

the stable link should be

```
https://download.calibre-ebook.com/${version}/calibre-64bit-${version}.msi
```

Please do not submit or accept updates for calibre with github download links in the future unless this issue is resolved upstream and the download links become stable again. (@vedantmgoyal2009)

### Steps to reproduce

Try to install or upgrade `calibre.calibre` to a bad version.

```
winget install calibre.calibre --version 7.2.0
```

### Actual behavior

```
> winget install calibre.calibre --version 7.2.0
Found an existing package already installed. Trying to upgrade the installed package...
Found calibre [calibre.calibre] Version 7.2.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/kovidgoyal/calibre/releases/download/v7.2.0/calibre-64bit-7.2.0.msi
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).
```

### Expected behavior

Old versions should remain accessible.

### Environment

```raw
Windows Package Manager (Preview) v1.7.3481-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.2861
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.3481.0
```

### Screenshots and Logs

_No response_

### PR DESCRIPTION
**Pull request by wickles**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

Resolves #133004
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/133008)

### CODE REVIEW

**Comment by wickles** [comment]
@microsoft-github-policy-service agree

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
You're not allowed to change multiple manifests, it has to be one version for each PR.

**Comment by wickles** [comment]
@OfficialEsco I would hope an exception could be made here. I'm not splitting this into 6 PRs.

**Comment by OfficialEsco** [comment]
Oh we mods/top contributors have tried to get a exclusion for a lot more/less and they say ehhhh no

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-07T00:49:02.5100664Z ##[error] The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.

(Automated response - build 540.)

**Comment by stephengillie** [comment]
Hi @wickles,

Thanks for contributing to our repo. This PR modifies 6 manifests:
image

We have a 1 manifest change per PR limit. Could you move 5 of these to other PRs?

**Pull request closed without merging**
