### PR TITLE
Add NextDNS

### PR DESCRIPTION
**Pull request by QAInsights**
Add NextDNS

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/832)

### CODE REVIEW

**Comment by QAInsights** [comment]
https://github.com/microsoft/winget-pkgs/issues/523

**Comment by KevinLaMS** [comment]
Installation failed suggesting that I need to install device software?

**Comment by QAInsights** [comment]
@KevinLaMS Could you please share the screenshot or details error message? I just tried installing, it went successful without throwing any error. 
image

**Comment by QAInsights** [comment]
Not a malware confirmation. 
image

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
