### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by SandroLinux**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15622)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
You are adding 2 different manifests under
`manifests/d/Dothq/Dot Browser/77.0`
`manifests/d/Dothq/Dot.Browser/77.0`

`PackageIdentifier` needs to be `Dothq.DotBrowser`
`PackageVersion` does not match the folder version
`Tags` contains `Tags - "Cross-Platform" s`

You probably need
```
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
```

There is also a VC++ dependency
image

**Comment by OfficialEsco** [comment]
`Manifest: The manifest file path must match PackageIdentifier and PackageVersion properties from manifest. actual 'manifests\d\Dothq\Dot.Browser\87.0', expected 'manifests\d\Dot\Browser\87.0'`

**Comment by SandroLinux** [comment]
stay open

**Comment by OfficialEsco** [comment]
> stay open

There is no reason for it to stay open if you can't be bothered of fix the issue

**Comment by denelon** [comment]
@SandroLinux are you able to make the changes to this PR to pass validation? I will add the "Blocking-Issue" label for the "dependency".

**Comment by SandroLinux** [comment]
> @SandroLinux are you able to make the changes to this PR to pass validation? I will add the "Blocking-Issue" label for the "dependency".

Ok yeah I will start working on making this PR pass validation

**Comment by OfficialEsco** [comment]
Do you want me to fix it instead?..

**Comment by SandroLinux** [comment]
> Do you want me to fix it instead?..

I am sorry yes can you please help

**Comment by OfficialEsco** [comment]
There ya go #17524

**Pull request closed without merging**
