### PR TITLE
Modify: Microsoft.Git version 2.47.0.0.3

### PR DESCRIPTION
**Pull request by SpecterShell**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/185867)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by comedinha** [comment]
The latest version is 2.47.0.2, and this is version 2.47.0.0.3. Which one is the latest? I upgraded my Git to this version because of the SSH bug, and now I am getting this
image

https://github.com/microsoft/winget-pkgs/pull/185858

**Comment by SpecterShell** [comment]
> The latest version is 2.47.0.2, and this is version 2.47.0.0.3. Which one is the latest? I upgraded my Git to this version because of the SSH bug, and now I am getting this image
> 
> #185858

This one is `Microsoft.Git` a Microsoft fork of Git, not `Git.Git`.

**Comment by SpecterShell** [comment]
> The latest version is 2.47.0.2, and this is version 2.47.0.0.3. Which one is the latest? I upgraded my Git to this version because of the SSH bug, and now I am getting this image
> 
> #185858

How did you update your Git? By `winget upgrade --all` or by `winget upgrade Microsoft.Git`?

**Review by ItzLevvie — APPROVED** [review]

**Comment by comedinha** [comment]
> > The latest version is 2.47.0.2, and this is version 2.47.0.0.3. Which one is the latest? I upgraded my Git to this version because of the SSH bug, and now I am getting this image
> > #185858
> 
> How did you update your Git? By `winget upgrade --all` or by `winget upgrade Microsoft.Git`?

I installed via the URL available inside the manifest as an alternative to resolve the Git.Git error. Only now I noticed the mistake and the conflict appears. I think Microsoft.Git is being identified as Git.Git.

**Comment by comedinha** [comment]
> > The latest version is 2.47.0.2, and this is version 2.47.0.0.3. Which one is the latest? I upgraded my Git to this version because of the SSH bug, and now I am getting this image
> > #185858
> 
> This PR is related to `Microsoft.Git`, a Microsoft fork of Git, not `Git.Git`.
> 
> See #175501. Hope this PR got merged soon.

Oh, okay, I didn't notice this. I only installed Microsoft.Git as an alternative to Git.Git because the latest version has a problem.

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
[Policy] Needs-Manual-Merge

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Pull request merged**
