### PR TITLE
Add Retroshare 0.6.5

### PR DESCRIPTION
**Pull request by latere-a-latere**
Part of https://github.com/MarNicGit/winget-pkgs/issues/3

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1633)

### CODE REVIEW

**Comment by MarNicGit** [comment]
Looks like the pipeline is stuck again.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
