### PR TITLE
New version: Tetrate.func-e version 1.1.2

### PR DESCRIPTION
**Pull request by codefromthecrypt**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/41731)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
Duplicate of #41730

**Comment by codefromthecrypt** [comment]
cool thanks for raising that!

**Comment by Trenly** [comment]
> cool thanks for raising that!

Don't thank me, thank @vedantmgoyal2009. He's the one who wrote the automation. It's a bit more powerful then winget-create at the moment due to how it handles metadata

**Comment by vedantmgoyal2009** [comment]
> > cool thanks for raising that!
> 
> Don't thank me, thank @vedantmgoyal2009. He's the one who wrote the automation. It's a bit more powerful then winget-create at the moment due to how it handles metadata

Still, the first thanks go to @Trenly since he's the only one who has worked and made YamlCreate v2.0.0, upon which the whole automation is dependent.

**Comment by Trenly** [comment]
> Still, the first thanks go to @Trenly since he's the only one who has worked and made YamlCreate v2.0.0, upon which the whole automation is dependent😁

YamlCreate v3.0.0 coming Fall 2022 (maybe, hopefully sooner than that, but depends on how much free time I get)

**Comment by codefromthecrypt** [comment]
Thanks, @Trenly as this automation removed a rather hefty job. good luck with 3.0 (and the free time 😎 )

**Pull request closed without merging**
