### PR TITLE
Finebits 8 Zip app added

### PR DESCRIPTION
**Pull request by ValeraFinebits**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/620)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
Greetings.  This package fails because it is dependent on some frameworks, and we do not support the dependencies yet.  https://github.com/microsoft/winget-cli/issues/163

In the meantime, if you include the dependencies in your package, it should pass.  Thanks.

**Comment by ValeraFinebits** [comment]
Looks like I can't add Microsoft.Services.Store.Engagement

MakeAppx : error: Error info: error 80080204: The package with file name "Microsoft.Services.Store.Engagement_10.0.19011.0_arm__8wekyb3d8bbwe.appx" and package full name "Microsoft.Services.Store.Engagement_10.0.19011.0_arm__8wekyb3d8bbwe" is not valid in the bundle because it's a framework package.
MakeAppx : error: Bundle creation failed.

**Comment by ValeraFinebits** [comment]
Maybe now we can approve and merge this request?

**Comment by denelon** [comment]
This PR is a bit old :smile:

The schema needs to be updated.

**Comment by ValeraFinebits** [comment]
> This PR is a bit old 😄
> 
> The schema needs to be updated.

Done

**Comment by denelon** [comment]
@ValeraFinebits thank you for taking the time to update the manifest. I've contacted one of the engineering team members to see what caused the validation failure.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/163

**Comment by tiziodcaio** [comment]
Maybe use [this](https://github.com/microsoft/winget-cli/blob/master/doc/Settings.md#experimentalmsstore) when will it be relased?

**Comment by Trenly** [comment]
@denelon Package is now available with `winget install 9wzdncrfjb33` and this PR can be closed

**Comment by denelon** [comment]
@ValeraFinebits do you want us to keep this PR open?

**Pull request closed without merging**
