### PR TITLE
New version: Uzero.ScanScan version 0.3.2

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#6482](https://github.com/SpecterShell/Dumplings/actions/runs/9869054784).

<details>

<summary>Log</summary>

````
Updated: 0.3.1 → 0.3.2
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/162251)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-07-11 05:19:17.363 [FAIL] Installer failed security check. Url: https://cdn.desktop.baimiaoapp.com/updater/download/v0.3.2/baimiao.msi.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 886.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-07-12 05:16:27.680 [FAIL] Installer failed security check. Url: https://cdn.desktop.baimiaoapp.com/updater/download/v0.3.2/baimiao.msi.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 886.)

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
