### PR TITLE
Remove: CrystalDewWorld.CrystalDiskInfo.KureiKeiEdition version 8.6.2

### PR DESCRIPTION
**Pull request by coolplaylinbot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141985)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @CoolPlayLin,

This package appears to still be available.

**Comment by stephengillie** [comment]
URL: https://osdn.net/frs/redir.php?m=auto&f=crystaldiskinfo%2F73163%2FCrystalDiskInfo8_6_2KureiKei.exe 
The SSL connection could not be established, see inner exception.

(Automated message - build 857)

**Comment by stephengillie** [comment]
URL: https://osdn.net/frs/redir.php?m=auto&f=crystaldiskinfo%2F73163%2FCrystalDiskInfo8_6_2KureiKei.exe 
Status Code: 200

(Automated message - build 861)

**Comment by stephengillie** [comment]
URL: https://osdn.net/frs/redir.php?m=auto&f=crystaldiskinfo%2F73163%2FCrystalDiskInfo8_6_2KureiKei.exe 
Status Code: 200

(Automated message - build 867)

**Comment by stephengillie** [comment]
URL: https://osdn.net/frs/redir.php?m=auto&f=crystaldiskinfo%2F73163%2FCrystalDiskInfo8_6_2KureiKei.exe 
Status Code: 200

(Automated message - build 869)

**Comment by stephengillie** [comment]
URL: https://osdn.net/frs/redir.php?m=auto&f=crystaldiskinfo%2F73163%2FCrystalDiskInfo8_6_2KureiKei.exe 
The SSL connection could not be established, see inner exception.

(Automated message - build 869)

**Comment by CoolPlayLin** [comment]
@CoolPlayLinBot Close

**Pull request closed without merging**
