### PR TITLE
Seedy-Threepio.Theseus2000 version 1.2C

### PR DESCRIPTION
**Pull request by seedy60**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/55236)

### CODE REVIEW

**Comment by Seedy-Threepio** [comment]
If the URL is invalid, how was Winget-Create able to gather metadata about the installer file? As far as I know, no bot filters are in place, unless cloudflare is blocking something.

**Comment by JohnMcPMS** [comment]
The bot is unhappy because the domain doesn't appear to be associated with the publisher or package name.  As definitely a human, I was able to determine that everything does appear to be good.

**Comment by Seedy-Threepio** [comment]
How can I get around such an error in future? I really don't fancy getting a new domain.

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
