### PR TITLE
New version: ImageLine.FLStudio version 21.2.3.4004

### PR DESCRIPTION
**Pull request by HevyMusic**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/138838)

### CODE REVIEW

**Comment by HevyMusic** [comment]
I'm not sure if it conforms the 1.6 schema changes, I tried to check and it looks good to me, but I'm not deep enough into that stuff to just say "yes, it does".

**Comment by HevyMusic** [comment]
Is there any reason why it always fails on the same validation?

**Review by stephengillie — APPROVED** [review]

**Comment by HevyMusic** [comment]
Is it normal that it verifies the PR 5 times, every 2 hours?

**Comment by HevyMusic** [comment]
@stephengillie It seems like the PR is constantly validated, around every 2 hours.
I always have the problem when updating the version that it fails on the validation, which leads to 5-15x rerunning the pipeline until it is manually validated. 
This is the first time that it is approved 7 times.

If there is anything I can do with the developers of FL Studio to ensure that the failing 2 tests are passing and that this is a more smooth flow, please let me know.

**Comment by stephengillie** [comment]
Hi @HevyMusic,

This wasn't a failing test - but I believe more of a race between the bots. Sorry to have impacted you.

**Comment by HevyMusic** [comment]
@stephengillie 
No problem, I just ask because that as it was the same issue the last 3 times I updated the version (that 2 of the validation tests did not pass) and it had to be manually approved each time.

Thanks for merging!

**Comment by stephengillie** [comment]
Oh - the `Internal-Error-Dynamic-Scan` reflects a pipeline issue, not a package issue. Or an umbrella for numerous errors, including new errors. A few packages might create a unique situation that causes this error on every run - I've been reporting a list back to our team, to try and mitigate repeated situations like this. I'll mention this package specifically.

**Pull request merged**
