### PR TITLE
ipinfo.ipinfo version 3.3.0

### PR DESCRIPTION
**Pull request by abu-usama**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135166)

### CODE REVIEW

**Comment by UmanShahzad** [comment]
@microsoft-github-policy-service agree company="IPinfo"

**Comment by abu-usama** [comment]
@microsoft-github-policy-service agree company="ipinfo"

**Comment by stephengillie** [comment]
Hi @abu-usama,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 602.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-18 09:23:58.969 [FAIL] Installer failed security check. Url: https://github.com/ipinfo/cli/releases/download/ipinfo-3.3.0/ipinfo_3.3.0_windows_386.zip Result: 0x80004005

(Automated response - build 602.)

**Comment by abu-usama** [comment]
@stephengillie I haven't been able to figure out what the issue is. It successfully validates and installs locally. Could this just be an issue from your side?

**Comment by stephengillie** [comment]
Hi @abu-usama,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 629.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-19 15:02:43.638 [FAIL] Installer failed security check. Url: https://github.com/ipinfo/cli/releases/download/ipinfo-3.3.0/ipinfo_3.3.0_windows_386.zip Result: 0x80004005

(Automated response - build 629.)

**Comment by stephengillie** [comment]
> @ stephengillie I haven't been able to figure out what the issue is. It successfully validates and installs locally. Could this just be an issue from your side?

Hi @abu-usama,

Packages have to pass a Defender scan before we can accept their manifest into the repo. Unfortunately, this package hasn't yet passed. The last scan was a few days ago, so I'll rescan to see if it passes this time, with newer virus signature updates.

**Comment by stephengillie** [comment]
Hi @abu-usama,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 642.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-23 13:18:47.451 [FAIL] Installer failed security check. Url: https://github.com/ipinfo/cli/releases/download/ipinfo-3.3.0/ipinfo_3.3.0_windows_386.zip Result: 0x80004005

(Automated response - build 642.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
