### PR TITLE
Hledger 1.40

### PR DESCRIPTION
**Pull request by Clindbergh**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Is there a linked Issue? #186058 

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change? -> This is a fix of  #172510
- [X] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/186059)

### CODE REVIEW

**Comment by Clindbergh** [comment]
@microsoft-github-policy-service agree

**Comment by Clindbergh** [comment]
There still exists a problem with validating:
```bash
C:\Users\Primary User\repos\winget-pkgs>winget validate --manifest  manifests/s/simonmichael/hledger/1.40/simonmichael.hledger.installer.yaml
Manifest validation failed.
Manifest Error: The multi file manifest is incomplete.A multi file manifest must contain at least version, installer and defaultLocale manifest. File: simonmichael.hledger.installer.yaml
```

**Comment by Dragon1573** [comment]
Manually verified.

image
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
