### PR TITLE
Local Installer for Chocolatey.

### PR DESCRIPTION
**Pull request by sharpninja**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [X] Have you tested your manifest locally with `winget install -m <manifest>`?

-----
Local (Non-Admin) install for Chocolatey.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3419)

### CODE REVIEW

**Comment by sharpninja** [comment]
I've fixed the ID issue.

**Comment by KevinLaMS** [comment]
Greetings:
We have a requirement that the URL to the installer come from the publisher location.  This does not appear to be a chocolatey repository.
https://raw.githubusercontent.com/sharpninja/Files/master/ChocolateyInstallNonAdmin.exe
Chocolatey has informed us they are working on a package.  I can put you in touch if you would like.

kevin

**Comment by sharpninja** [comment]
OK, no problem.

**Comment by KevinLaMS** [comment]
OK thanks, closing.

**Pull request closed without merging**
