### PR TITLE
BlenderFoundation.blender version 2.93.0

### PR DESCRIPTION
**Pull request by TargetCrafter**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15854)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Please use `wingetcreate update` for already existing packages so we don't loose tons of useful metadata.
Also use the correct PackageIdentifier which is `BlenderFoundation.Blender`
Difference when using `wingetcreate update` #15862

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Duplicate of https://github.com/microsoft/winget-pkgs/pull/15862.

**Comment by TargetCrafter** [comment]
> Please use `wingetcreate update` for already existing packages so we don't loose tons of useful metadata.
> Also use the correct PackageIdentifier which is `BlenderFoundation.Blender`
> Difference when using `wingetcreate update` #15862

Still learning xD but I'll keep it in mind for the next time, thanks!
As you already have a proper PR, should I close this one?

**Comment by OfficialEsco** [comment]
> Still learning xD but I'll keep it in mind for the next time, thanks!
> As you already have a proper PR, should I close this one?

Yee fixing the issue as a newbie/without using GitHub Desktop takes way too much effort. There is also a issue with `wingetcreate update` which doesn't update the ProductCode so it requires manual editing..

**Comment by TargetCrafter** [comment]
Okay, I'll close it and leave it up to you then.
Is there a good tutorial for updating using wingetcreate you recommend?

**Comment by OfficialEsco** [comment]
> Okay, I'll close it and leave it up to you then.
> Is there a good tutorial for updating using wingetcreate you recommend?

`wingetcreate` is a very very simple tool right now, you'll find the information by doing `wingetcreate -?`, `wingetcreate new -?` and `wingetcreate update -?`

You should rather look into how to maintain the packages repo
https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md
https://github.com/microsoft/winget-cli/tree/master/schemas/JSON/manifests/v1.0.0

[YamlCreate.ps1](https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1) adds more information but is also more manual (knowledge of installers etc)

**Pull request closed without merging**
