### PR TITLE
ReleaseNotes: o2sh.onefetch 2.13.2

### PR DESCRIPTION
**Pull request by Trenly**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/88162)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by o2sh** [comment]
@Trenly Still not published 😢

**Comment by Trenly** [comment]
@denelon / @yao-msft - The only commit in the pipeline run failed commit verification, but the publish pipeline still succeeded?

https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=397432&view=results

**Comment by o2sh** [comment]
ping @stephengillie @JohnMcPMS 
very sorry to insist, but this release is two weeks old and is still not published.

Thanks for your help.

**Comment by denelon** [comment]
Hey, sorry this one seemed to get past my inbox filters. I'll see what needs to be done here.

**Comment by denelon** [comment]
It looks like:
* https://github.com/microsoft/winget-pkgs/pull/86991

got merged with a file that wasn't part of the manifest (expect.txt). That's what caused the actual issue. @Trenly correctly identified that in the other PR. We're going to perform a rebuild to address the issue so the manifest is properly updated.

**Comment by o2sh** [comment]
Thanks @denelon 
Looking forward to seeing this issue being resolved 👍

**Comment by denelon** [comment]
```text
winget search o2sh.onefetch
Name     Id            Version Source
--------------------------------------
onefetch o2sh.onefetch 2.13.2  winget
```

**Pull request merged**
