### PR TITLE
New version: JetBrains.FleetLauncher.Preview version 1.30.83

### PR DESCRIPTION
**Pull request by SpecterShell**
This pull request is automatically generated by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/138530)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 720.)

**Comment by stephengillie** [comment]
Hi @SpecterShell,

This application appeared to install correctly, but gave the above error when launched. 

- Did it install correctly? It seems to be looking for files. But in unusual places, such as under a folder named after the EXE.
- Is there a dependency or something else missing? 
- Is this normal if it doesn't have something like a config file?

**Comment by SpecterShell** [comment]
> Hi @SpecterShell,
> 
> This application appeared to install correctly, but gave the above error when launched.
> 
>     * Is a config file missing? It seems to be looking for `dock.address`.
> 
>     * Did it install correctly? It seems to be looking for files to...canonicalize? But in unusual places, such as under a folder named after the EXE.
> 
>     * Is there a dependency or something else missing?
> 
>     * Is this normal if it doesn't have something like a config file?

It may require some switches to run. See https://www.jetbrains.com/help/fleet/install-on-a-remote-machine.html#options

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\JetBrains.FleetLauncher.Preview__DefaultSource\fleet.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\fleet.exe returned exit code: 1

(Automated response - build 870.)

**Pull request merged**
