### PR TITLE
New version: DuckStudio.FufuDevTools 2024.07.25.2030

### PR DESCRIPTION
**Pull request by DuckDuckStudio**
ffdev-2024.07.25.2030
清单验证成功

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

> [!NOTE]
Primary program: `Script/ffdev.exe`
Show version: `ffdev ver/版本/version/Version/--version/--ver` (`/` indicates `or`)
> Example: `ffdev --version`

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164546)

### CODE REVIEW

**Comment by DuckDuckStudio** [comment]
Installation verification:
```powershell
[Powered by 虚空终端] PS> winget install --manifest manifests\d\DuckStudio\FufuDevTools\2024.07.25.2030 --verbose
已找到 芙芙工具箱开发工具包 [DuckStudio.FufuDevTools] 版本 2024.07.25.2030
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://github.com/DuckDuckStudio/Fufu_Dev_Tools/releases/download/2024.07.25.2030/Fufu_Dev_Tools_Setup_2024.07.25.2030.exe
  ██████████████████████████████  32.5 MB / 32.5 MB
已成功验证安装程序哈希
正在启动程序包安装...
已成功安装
[Powered by 虚空终端] PS> ffdev --version
✓ Version 2024.07.25.2030
```

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files (x86)\Fufu_Dev_Tools\git\账号切换.exe returned exit code: 1
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\git\连续pull尝试.exe returned exit code: 1
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\git\连续push尝试.exe returned exit code: 1
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\Script\ffdev.exe returned exit code: 1
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\代码校对\参数查重.exe returned exit code: 2
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\代码校对\尾随空格.exe returned exit code: 2
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\代码校对\末尾空行.exe returned exit code: 2
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\代码校对\非UTF-8编码.exe returned exit code: 2
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\生成工具\需求生成.exe returned exit code: 2
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\统计\代码总行数.exe returned exit code: 2
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\git\git连续尝试.exe returned exit code: 1

(Automated response - build 887.)

**Review by stephengillie — APPROVED** [review]

**Review by Luna-Grace — APPROVED** [review]

**Review by fjwxzde — APPROVED** [review]

**Comment by DuckDuckStudio** [comment]
@stephengillie

**Comment by DuckDuckStudio** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
