### PR TITLE
New version: xjasonlyu.tun2socks version v2.5.2

### PR DESCRIPTION
**Pull request by coolplaylinbot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/126459)

### CODE REVIEW

**Comment by CoolPlayLin** [comment]
Any suggestion?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2023-11-13 15:21:53.159 [FAIL] Installer failed security check. Url: https://github.com/xjasonlyu/tun2socks/releases/download/v2.5.2/tun2socks-windows-amd64.zip Result: 0x80004005 2023-11-13 15:21:44.848 [FAIL] Installer failed security check. Url: https://github.com/xjasonlyu/tun2socks/releases/download/v2.5.2/tun2socks-windows-386.zip Result: 0x80004005

**Comment by stephengillie** [comment]
Hi @CoolPlayLin,

Unfortunately, this package did not pass a Defender scan. This might be a false positive and we can rescan tomorrow.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
