### PR TITLE
Remove: jbruchon.jdupes version 1.23.0

### PR DESCRIPTION
**Pull request by coolplaylinbot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/145015)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://github.com/jbruchon/jdupes/releases/download/v1.23.0/jdupes-1.23.0-win64.zip 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 870)

**Comment by stephengillie** [comment]
Hi @coolplaylinbot,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 870.)

**Comment by stephengillie** [comment]
URL: https://github.com/jbruchon/jdupes/releases/download/v1.23.0/jdupes-1.23.0-win64.zip 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 870)

**Comment by stephengillie** [comment]
URL: https://github.com/jbruchon/jdupes/releases/download/v1.23.0/jdupes-1.23.0-win64.zip 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 870)

**Comment by stephengillie** [comment]
URL: https://github.com/jbruchon/jdupes/releases/download/v1.23.0/jdupes-1.23.0-win64.zip 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 871)

**Comment by CoolPlayLin** [comment]
@stephengillie

You can safely merge this because the project has been deleted
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
