### PR TITLE
Jellyfin1075.JellyfinServer version 10.7.5.0

### PR DESCRIPTION
**Pull request by Meteor24**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14919)

### CODE REVIEW

**Comment by Meteor24** [comment]
How do I check to see if I did those things or not?

**Comment by OfficialEsco** [comment]
This package is already submitted [j/Jellyfin/Jellyfin](https://github.com/microsoft/winget-pkgs/blob/master/manifests/j/Jellyfin/Jellyfin), please search before you submit and follow the folder structure of already submitted packages.

However i also just tested on my VM and it does install unattended.

**Comment by Meteor24** [comment]
@OfficialEsco When I search for Jellyfin in the package Repo it doesn't show up

**Comment by OfficialEsco** [comment]
1. 
image

2. 
image

3.
image

**Comment by Meteor24** [comment]
@OfficialEsco What did you type when you searched for it in the repository?

**Comment by OfficialEsco** [comment]
I searched for "Jellyfin" in all those examples
1. Just use `winget search JellyFin`
2. Go to the `Pull Request` tab and search `is:pr Jellyfin` (NOT `is:pr is:open Jellyfin`)
3. Be anywhere on `https://github.com/microsoft/winget-pkgs`, click `Search or jump to..` at the top left corner and search for `Jellyfin` and select `In this repository`

**Comment by denelon** [comment]
@OfficialEsco you inspired me https://github.com/microsoft/winget-pkgs/pull/15807

**Comment by OfficialEsco** [comment]
> @OfficialEsco you inspired me #15807

Searching is the most important thing on the Internet you know 👀
*cough* the `Pull Request` tab is VERY sensitive/sentence sensitive, example `Avast` and `AvastAntivirus`

**Pull request closed without merging**
