### PR TITLE
Removed irrelevant switches for FileZilla client version 3.52.2.

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with winget validate <manifest>, where <manifest> is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with winget install -m <manifest>?

----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/6554)

### CODE REVIEW

**Comment by jedieaston** [comment]
Uh, all of the URLs are valid...

**Comment by jedieaston** [comment]
@KevinLaMS Looks like it's still bugged. Should I open an issue?

**Comment by KevinLaMS** [comment]
third times the charm?

**Comment by jedieaston** [comment]
@ashpatil-msft None of the links are invalid for me.

**Comment by KevinLaMS** [comment]
we can probably close this one now, right?  i suspect there are new ones in place.

**Pull request closed without merging**
