### PR TITLE
Beeftext version 9.0

### PR DESCRIPTION
**Pull request by quhxl**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/19676)

### CODE REVIEW

**Comment by ryfu-msft** [comment]
Hey @quhxl, 

Sorry for the delays. Looking into this pull request, I had issues running this app on an x86 host machine. I believe x64 is the correct architecture. Could you try changing the architecture to x64? Lets see if that resolves the other issues. Thanks!

**Comment by quhxl** [comment]
@ryfu-msft Unfortunately, that didn't fix it.

**Comment by ryfu-msft** [comment]
@quhxl sorry :( looking into this now

**Comment by quhxl** [comment]
I added several versions of the app to the repo that day. Only this new version has this error message.  That is why I am confused.

**Comment by ryfu-msft** [comment]
Hey @quhxl,

Looks like your installerURL was flagged by smartscreen. In order to resolve this issue you need to follow the link shown next to the failed URI which I have copied [here](https://feedback.smartscreen.microsoft.com/feedback.aspx?v=6&t=16&result=block&type=top&url=aHR0cHM6Ly9naXRodWIuY29tL3htaWNoZWxvL0JlZWZ0ZXh0L3JlbGVhc2VzL2Rvd25sb2FkL3Y5LjAvQmVlZnRleHQtOS4wLUluc3RhbGxlci5leGU%3D) for you. Sorry for the trouble and delay, hopefully this can get resolved quickly once you fill out that form.

**Comment by quhxl** [comment]
@ryfu-msft How long does this usually take?

**Comment by ItzLevvie** [comment]
The application developer wrote about it: https://github.com/xmichelo/Beeftext/wiki/Beeftext-is-safe#antivirus

It states `The problem is linked to the way Beeftext operates. In order to properly detect keywords and trigger combo substitution, Beeftext listens to the keystrokes typed by the user. Unfortunately, this is exactly the same behavior as the one implemented in malicious keyloggers that record your keystrokes in order to intercept your usernames and passwords. As a consequence, security software (Antiviruses, Malware protection and web security software) that perform an advanced analysis of the behavior of applications (known as heuristic analysis) may mistakenly consider Beeftext as harmful.`

and Microsoft's documentation states `Occasionally, genuine tools used for debugging and low-level activities will appear as PUA to the antivirus vendors. This is because the code necessary to do the debugging will have a similar signature to unwanted software. Even though this is a legitimate use of that coding practice, unfortunately we are unable to allow those applications into the Windows Package Manager repository.` - from https://docs.microsoft.com/en-us/windows/package-manager/package/binary-validation-errors

It doesn't seem to be occuring with the latest version of Beeftext which is 9.1 though.

**Comment by quhxl** [comment]
> 
> 
> The application developer wrote up about it: https://github.com/xmichelo/Beeftext/wiki/Beeftext-is-safe#antivirus
> 
> It states "The problem is linked to the way Beeftext operates. In order to properly detect keywords and trigger combo substitution, Beeftext listens to the keystrokes typed by the user. **Unfortunately, this is exactly the same behavior as the one implemented in malicious keyloggers that record your keystrokes in order to intercept your usernames and passwords. As a consequence, security software (Antiviruses, Malware protection and web security software) that perform an advanced analysis of the behavior of applications (known as heuristic analysis) may mistakenly consider Beeftext as harmful**."
> 
> and Microsoft's documentation states "Occasionally, genuine tools used for debugging and low-level activities will appear as PUA to the antivirus vendors. This is because the code necessary to do the debugging will have a similar signature to unwanted software. Even though **this is a legitimate use of that coding practice, unfortunately we are unable to allow those applications into the Windows Package Manager repository**." - from https://docs.microsoft.com/en-us/windows/package-manager/package/binary-validation-errors#what-if-i-cannot-remove-that-code.
> 
> It doesn't seem to be occuring with the latest version of Beeftext which is 9.1 though.

Thank you for this datailled research. Since the newer version does not have the errors, I will skip this version.

**Pull request closed without merging**
