### PR TITLE
Microsoft.PowerShell.Preview version 7.2.0.10

### PR DESCRIPTION
**Pull request by Masamune3210**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/28945)

### CODE REVIEW

**Comment by Masamune3210** [comment]
Uhhhh, thats a new one....

**Comment by Trenly** [comment]
> Uhhhh, thats a new one....

It's because the paths are case sensitive. You created your files at `/manifests/m/Microsoft/Powershell/Preview/` when the existing casing is `/manifests/m/Microsoft/PowerShell/Preview`

Looks like you need to capitalize the 'S' in PowerShell in the file paths, file names, and Package Identifiers

**Comment by Masamune3210** [comment]
Considering Windows is case-insensitive, the logic behind that requirement is lost to me lol

**Comment by Masamune3210** [comment]
Ok, think I got everything. Famous last words

**Comment by Trenly** [comment]
> Considering Windows is case-insensitive, the logic behind that requirement is lost to me lol

It's actually because Windows is case-insensitive. If there are two paths with different casing, Linux based systems can handle it just fine. However, when using Git with Windows, having two paths with different casing causes Git to not know which set of files to use, or which directory to put new commits/files into. It's an issue called "Path Collision". I experienced it myself a little while back - https://github.com/microsoft/winget-pkgs/issues/27329

**Comment by Masamune3210** [comment]
Sounds like a ball of a time to deal with. Happen to know how to rename a folder in part of a path on github? if not I'm just going to make ....yet another... pull request just to fix the folder name

**Comment by Trenly** [comment]
> Ok, think I got everything. Famous last words

Looks like this needs to be changed to for all the files
image

**Comment by Masamune3210** [comment]
Yeah thats the issue, cant figure out how to rename that folder without just making a new pull

**Comment by Masamune3210** [comment]
Guess ill just do that

**Comment by jedieaston** [comment]
Press "." on the PR page, and a web version of VSCode will launch. Then you can find the folder you want, rename it, and use the source control button on the left to commit it (there's no pushing, it's automatically committed to your GitHub repo).

**Comment by jedieaston** [comment]
image

**Comment by Masamune3210** [comment]
Gods above I wish I had known that was a thing about 30 manually fixed packages ago lol, its amazing!

**Comment by jedieaston** [comment]
It's really nice for making these changes as compared to the basic file editor GitHub's had forever.

**Comment by Masamune3210** [comment]
I'm relatively new to GitHub in general, only started really committing things once this project opened up because the catharsis of collecting all the programs is addicting lol. Unrelated but any other cool tricks like that?

**Comment by jedieaston** [comment]
Codespaces is cool but not directly relevant to this repo, since we're dealing with Windows stuff. It allows you to spawn a VSCode instance on a cloud box with everything checked out ready for you to work. It's awesome if you want to make a quick PR to a repo you haven't worked with before (and is how that light version of VSCode came about). 

`:shipit:` makes a cool squirrel appear in comments.

**Review by jedieaston — APPROVED** [review]

**Comment by TravisEz13** [comment]
thanks @Masamune3210

**Comment by Masamune3210** [comment]
No problem, it's cathartic to work on this so I actually find it quite fun

**Pull request merged**
