### PR TITLE
Add: Vanta version 2.4.0

### PR DESCRIPTION
**Pull request by jnichols35**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/122872)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by stephengillie** [comment]
Hi @jnichols35,

Should this be a `portable` package?

**Comment by jnichols35** [comment]
@stephengillie This app may not work with Winget, when I tested it without a silent flag, mid install it opened an edge window for signin, and when I ran it with the silent flag, I thought it worked the first time, but upon looking into it further it looks like it automatically deletes it's files unless `--overrides` are used to send specfic information. 

Should I go ahead and clsoe this?

**Comment by stephengillie** [comment]
> @stephengillie This app may not work with Winget, when I tested it without a silent flag, mid install it opened an edge window for signin, and when I ran it with the silent flag, I thought it worked the first time, but upon looking into it further it looks like it automatically deletes it's files unless `--overrides` are used to send specfic information.
> 
> Should I go ahead and clsoe this?

Feel free, or I could close it also.

**Pull request closed without merging**
