### PR TITLE
New package: n4af.TR4W version 4.131.0

### LINKED ISSUE #140295: [Package Request]: TR4W Logger
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://tr4w.net
Publisher: Howie Hoyt
Package Name: TR4W Logger
Description: TR4W Contest Logging Software.
Package Version: 4.131.0
Installer URL: https://tr4w.net/4.131/tr4w_setup_4_131.0.exe

### PR DESCRIPTION
**Pull request by Exorcism0666**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.1.0 :rocket:

- Resolve: #140295
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140335)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://tr4w.net/4.131/tr4w_setup_4_131.0.exe 
Status Code: 200

(Automated message - build 776)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Error occurred while downloading installer from https://tr4w.net/4.131/tr4w_setup_4_131.0.exe. 0x80072F0C.
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 

(Automated response - build 776.)

**Comment by stephengillie** [comment]
URL: https://tr4w.net/4.131/tr4w_setup_4_131.0.exe 
Status Code: 200

(Automated message - build 812)

**Comment by stephengillie** [comment]
[Policy] Network-Blocker

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by AsciiWolf** [comment]
@stephengillie It downloads fine on my VPS.

**Comment by stephengillie** [comment]
To prevent automated downloads, some hosts prevent connections with public IP blocks known to be held by data centers. This appears to be occurring here. While you and I can download this package, our scanning servers cannot. And so we can't scan, which is a mandatory step in the validation pipeline.

**Comment by AsciiWolf** [comment]
Version [4.136](https://tr4w.net/4.136/tr4w_setup_4_136.00.exe) got released and the older ones were deleted.

**Comment by AsciiWolf** [comment]
@Exorcism0666 Ping. :-)

**Pull request closed without merging**
