### PR TITLE
New version: DuckStudio.ChineseGit version v2.8

### PR DESCRIPTION
**Pull request by Luna-Grace**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/163956)

### CODE REVIEW

**Comment by Luna-Grace** [comment]
@microsoft-github-policy-service agree company="DuckStudio"

**Review by DuckDuckStudio — APPROVED** [review]

**Comment by DuckDuckStudio** [comment]
> [!NOTE]
> Due the Dependencies (`Git.Git`), this package may need to be verified manually.

**Review by fjwxzde — APPROVED** [review]

**Comment by DuckDuckStudio** [comment]
@Luna-Grace 
Dependencies should be retained.
> [!WARNING]
> This package may need to be verified manually, Because after the dependencies are added, this package will appear https://github.com/microsoft/winget-pkgs/labels/Internal-Error-Dynamic-Scan.

**Comment by Luna-Grace** [comment]
> [!WARNING]
> This package may need to be verified manually, Because after the dependencies are added, this package will appear [ Internal-Error-Dynamic-Scan](https://github.com/microsoft/winget-pkgs/labels/Internal-Error-Dynamic-Scan) The test for Dynamic Scanning in the Installation Validation failed.

@stephengillie

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
