### PR TITLE
Add FormatFactory

### PR DESCRIPTION
**Pull request by auanasgheps**
Adds FormatFactory 5.2.1.0

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1445)

### CODE REVIEW

**Review by auanasgheps — COMMENTED** [review]
Rename publisher

**Review by auanasgheps — COMMENTED** [review]
Updated folder path

**Review by auanasgheps — COMMENTED** [review]
Refactor hoping to solve bot stuck in verification

**Review by auanasgheps — COMMENTED** [review]
Another small change

**Comment by auanasgheps** [comment]
Hi, 
Can you please confirm the root cause?

1. I've checked the SHA256 signature, it matches
2. The download link is publicly available 
3. The installer contains adware detected by _some_ antiviruses, please check [this report](https://www.virustotal.com/gui/file/fba9288b9216722d8ad51bbebf1b12c49e979e7b2afbcd11e2a6ba1da0384f02/detection) from VirusTotal. Does it qualify as _malware_?

**Comment by auanasgheps** [comment]
Hm, the installer has been moved. I will provide an updated manifest tomorrow.

**Review by auanasgheps — COMMENTED** [review]
Update to 5.3.0.1

**Comment by auanasgheps** [comment]
I have validated the updated manifest on my machine. The URL can be downloaded successfully, the hash corresponds and the installation completes successfully. 
image

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
