### PR TITLE
Remove version: Datronicsoft.SpacedeskDriver.Server version 2.1.0.0

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/138403)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-08T17:50:25.5882626Z Processing manifest: manifests\d\Datronicsoft\SpacedeskDriver\Server\2.1.0.0
 2024-02-08T17:50:25.5893590Z -----------------------------------------------------
 2024-02-08T17:50:25.5901681Z Status: Started
 2024-02-08T17:50:25.5909655Z Manifest file is Deleted
 2024-02-08T17:50:25.8662525Z Status: Completed
 2024-02-08T17:50:25.8673645Z ##[error] Result: Failed
 2024-02-08T17:50:25.8806017Z ##[error] Sequence contains no elements
 2024-02-08T17:50:25.9310028Z ##[error]Manifest Validation Failed

(Automated response - build 716.)

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 716.)

**Comment by stephengillie** [comment]
URL: https://spacedesk.net/downloads/spacedesk_driver_Win_10_64_v2100.msi 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 716)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
