### PR TITLE
New version: Wesnoth.BattleForWesnoth version 1.17.3

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/58134)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Download seems to have failed
```
2022-04-19 11:47:24.085 [CORE] Valid settings file not found. Using default values.
2022-04-19 11:47:24.085 [CORE] WinGet, version [1.1.12653], activity [{9F98973B-E3E9-4B33-BA33-F6E6A23929BD}]
2022-04-19 11:47:24.086 [CORE] OS: Windows.Desktop v10.0.19042.1052
2022-04-19 11:47:24.086 [CORE] Command line Args: C:\Users\validator\AppData\Local\Microsoft\WindowsApps\winget.exe install --manifest D:\TRANSFER\85ff9df7-10c0-ec11-9508-000d3a9eda90\Manifest.yaml --scope user --accept-package-agreements
2022-04-19 11:47:24.086 [CORE] Package: Microsoft.DesktopAppInstaller v1.16.12653.0
2022-04-19 11:47:24.090 [CORE] IsCOMCall:0; Caller: winget-cli
2022-04-19 11:47:24.122 [CLI ] WinGet invoked with arguments: 'install' '--manifest' 'D:\TRANSFER\85ff9df7-10c0-ec11-9508-000d3a9eda90\Manifest.yaml' '--scope' 'user' '--accept-package-agreements'
2022-04-19 11:47:24.122 [CLI ] Found subcommand: install
2022-04-19 11:47:24.122 [CLI ] Leaf command to execute: root:install
2022-04-19 11:47:24.137 [CLI ] Executing command: install
2022-04-19 11:47:24.143 [CLI ] Manifest fields: Name [Battle for Wesnoth], Version [1.17.3]
2022-04-19 11:47:24.150 [CLI ] Starting installer selection.
2022-04-19 11:47:24.150 [CLI ] Installer [X64,Nullsoft,Machine,] not applicable: Installer scope does not match required scope: Machine != User
2022-04-19 11:47:24.150 [CLI ] Completed installer selection.
2022-04-19 11:47:24.249 [CLI ] Generated temp download path: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Wesnoth.BattleForWesnoth.1.17.3
2022-04-19 11:47:24.250 [CORE] Downloading to path: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Wesnoth.BattleForWesnoth.1.17.3
2022-04-19 11:47:24.251 [CORE] DeliveryOptimization downloading from url: https://sourceforge.net/projects/wesnoth/files/wesnoth/wesnoth-1.17.3/wesnoth-1.17.3-win64.exe/download
2022-04-19 11:47:42.258 [CORE] DeliveryOptimization error: 0x80190001, extended error: 0x00000000
2022-04-19 11:47:42.260 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\AppInstallerCLI.exe!00007FF7D77A040B: (caller: 00007FF7D77A0C0A) Exception(1) tid(618) 80190001 Unexpected HTTP status code.


2022-04-19 11:47:42.285 [CORE] Started applying motw to C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Wesnoth.BattleForWesnoth.1.17.3 with zone: 3
2022-04-19 11:47:42.290 [CORE] Finished applying motw
2022-04-19 11:47:42.291 [CORE] WinINet downloading from url: https://sourceforge.net/projects/wesnoth/files/wesnoth/wesnoth-1.17.3/wesnoth-1.17.3-win64.exe/download
2022-04-19 11:47:43.025 [CORE] Download request failed. Returned status: 429
2022-04-19 11:47:43.026 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(57)\AppInstallerCLI.exe!00007FF7D7756E93: (caller: 00007FF7D7757222) Exception(2) tid(618) 801901AD     Msg:[Download request status is not success.] 

2022-04-19 11:47:43.254 [CLI ] Failed to download, waiting a bit and retry. Url: https://sourceforge.net/projects/wesnoth/files/wesnoth/wesnoth-1.17.3/wesnoth-1.17.3-win64.exe/download
2022-04-19 11:47:43.769 [CORE] Downloading to path: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Wesnoth.BattleForWesnoth.1.17.3
2022-04-19 11:47:43.769 [CORE] DeliveryOptimization downloading from url: https://sourceforge.net/projects/wesnoth/files/wesnoth/wesnoth-1.17.3/wesnoth-1.17.3-win64.exe/download
2022-04-19 11:47:52.447 [CORE] DeliveryOptimization error: 0x80072ee2, extended error: 0x00000000
2022-04-19 11:47:52.447 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\AppInstallerCLI.exe!00007FF7D77A040B: (caller: 00007FF7D77A0C0A) Exception(3) tid(618) 80072EE2 
2022-04-19 11:47:52.471 [CORE] Started applying motw to C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Wesnoth.BattleForWesnoth.1.17.3 with zone: 3
2022-04-19 11:47:52.474 [CORE] Finished applying motw
2022-04-19 11:47:52.475 [CORE] WinINet downloading from url: https://sourceforge.net/projects/wesnoth/files/wesnoth/wesnoth-1.17.3/wesnoth-1.17.3-win64.exe/download
2022-04-19 11:47:52.651 [CORE] Download request failed. Returned status: 429
2022-04-19 11:47:52.651 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(57)\AppInstallerCLI.exe!00007FF7D7756E93: (caller: 00007FF7D7757222) Exception(4) tid(618) 801901AD     Msg:[Download request status is not success.] 

2022-04-19 11:47:52.911 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(57)\AppInstallerCLI.exe!00007FF7D7756E93: (caller: 00007FF7D7757222) Exception(4) tid(618) 801901AD     Msg:[Download request status is not success.] 


```

**Comment by OfficialEsco** [comment]
Even less informative of a log now and CMD is blocking the winget window
```
2022-04-19 12:51:52.986 [CORE] Valid settings file not found. Using default values.
2022-04-19 12:51:52.987 [CORE] WinGet, version [1.1.12653], activity [{F18084E9-93A1-4A82-B7E2-381EF292F026}]
2022-04-19 12:51:52.987 [CORE] OS: Windows.Desktop v10.0.19042.1052
2022-04-19 12:51:52.987 [CORE] Command line Args: C:\Users\validator\AppData\Local\Microsoft\WindowsApps\winget.exe install --manifest D:\TRANSFER\2819c6fa-19c0-ec11-9507-000d3a9ede8b\Manifest.yaml --scope machine --accept-package-agreements
2022-04-19 12:51:52.987 [CORE] Package: Microsoft.DesktopAppInstaller v1.16.12653.0
2022-04-19 12:51:52.990 [CORE] IsCOMCall:0; Caller: winget-cli
2022-04-19 12:51:53.013 [CLI ] WinGet invoked with arguments: 'install' '--manifest' 'D:\TRANSFER\2819c6fa-19c0-ec11-9507-000d3a9ede8b\Manifest.yaml' '--scope' 'machine' '--accept-package-agreements'
2022-04-19 12:51:53.013 [CLI ] Found subcommand: install
2022-04-19 12:51:53.013 [CLI ] Leaf command to execute: root:install
2022-04-19 12:51:53.026 [CLI ] Executing command: install
2022-04-19 12:51:53.033 [CLI ] Manifest fields: Name [Battle for Wesnoth], Version [1.17.3]
2022-04-19 12:51:53.037 [CLI ] Starting installer selection.
2022-04-19 12:51:53.037 [CLI ] Installer [X64,Nullsoft,User,] not applicable: Installer scope does not match required scope: User != Machine
2022-04-19 12:51:53.037 [CLI ] Completed installer selection.
2022-04-19 12:51:53.067 [CLI ] Generated temp download path: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Wesnoth.BattleForWesnoth.1.17.3
2022-04-19 12:51:53.075 [CORE] Downloading to path: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Wesnoth.BattleForWesnoth.1.17.3
2022-04-19 12:51:53.076 [CORE] DeliveryOptimization downloading from url: https://sourceforge.net/projects/wesnoth/files/wesnoth/wesnoth-1.17.3/wesnoth-1.17.3-win64.exe/download
```

**Review by Trenly — APPROVED** [review]

**Pull request merged**
