### PR TITLE
New package: Qwerty-133.spcache v0.1.0

### PR DESCRIPTION
**Pull request by Qwerty-133**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/112205&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation failed with:
> Error loading Python DLL 'C:\Users\User\AppData\Local\Microsoft\WinGet\Links\python311.dll'. LoadLibrary: The specified module could not be found. 

Is `Python.Python.3.11` a dependency?

**Comment by Qwerty-133** [comment]
Hello! No, `spcache` is bundled using [PyInstaller](https://pyinstaller.org/en/stable/index.html)
The zip file contains a Python interpreter (`python311.dll`), and all the other dlls it needs to run.

**Comment by Qwerty-133** [comment]
```powershell
PS Microsoft.PowerShell.Core\FileSystem::\\wsl.localhost\...> winget uninstall -m .\manifests\q\Qwerty-133\spcache\0.1.0 --purge
Found spcache [Qwerty-133.spcache]
Starting package uninstall...
Purging install directory...
Successfully uninstalled

PS Microsoft.PowerShell.Core\FileSystem::\\wsl.localhost\...> winget install -m .\manifests\q\Qwerty-133\spcache\0.1.0 --verbose
Found spcache [Qwerty-133.spcache] Version 0.1.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Path environment variable modified; restart your shell to use the new value.
Command line alias added: "spcache"
Successfully installed

PS Microsoft.PowerShell.Core\FileSystem::\\wsl.localhost\...> spcache --version
spcache.exe, version 0.1.0
```

Tested it again on my system

**Comment by stephengillie** [comment]
Ah, the issue appears to be that the symlink can't access those files.

**Comment by Trenly** [comment]
@Qwerty-133 - Support for zipped binaries has now been added and is available in the pipelines. This will require you to update your submission to ManifestVersion: 1.9.0 and set ArchiveBinariesDependOnPath: true in the installer node. To keep things clean, this PR is being closed. Please submit a new PR for the latest version of this package. Thank you for your contributions!

**Pull request closed without merging**
