### PR TITLE
Update VMware.WorkstationPro to 17.6.1

### PR DESCRIPTION
**Pull request by FaserF**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/190690)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335140
> 2024-11-11 23:56:25.339 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Archive.cpp(33)\WindowsPackageManager.dll!00007FFBDE6A413B: (caller: 00007FFBDE61EBB5) ReturnHr(1) tid(590) 80004005 Unspecified error
> 2024-11-11 23:56:25.340 [CLI ] Failed to extract archive with code -2147467259
> MSI (s) (30:D0) [23:55:51:481]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (30:D0) [23:55:51:481]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (30:D0) [23:55:51:481]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (30:D0) [23:55:51:481]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (30:D0) [23:55:51:481]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> Property(S): OutOfDiskSpace = 0
> Property(S): OutOfNoRbDiskSpace = 0
> Property(S): PrimaryVolumeSpaceAvailable = 0
> Property(S): PrimaryVolumeSpaceRequired = 0
> Property(S): PrimaryVolumeSpaceRemaining = 0
> MSI (s) (30:80) [23:55:52:231]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (30:80) [23:55:52:231]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (30:80) [23:55:52:231]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (30:80) [23:55:52:231]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (30:80) [23:55:52:231]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.

Automated error analysis suggests -1978335140 may mean Failed to extract archive. Does the `InstallerUrl` actually end in `.zip` - or does it have a different extension? 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Comment by FaserF** [comment]
.tar extractions should be possible with winget [1.9.25180](https://github.com/microsoft/winget-cli/releases/tag/v1.9.25180) due to #4541

I have not found any docs, describing on specifically setting anything within the installer.yaml to use tar.exe - so for me I thought it should work that way? 
Are the tests running with an older winget version?

**Comment by FaserF** [comment]
Same thing as mentioned here: https://github.com/microsoft/winget-pkgs/pull/190690#issuecomment-2475580474

**Comment by FaserF** [comment]
Same thing as mentioned here: https://github.com/microsoft/winget-pkgs/pull/190690#issuecomment-2475580474

Just writing this to remove the "needs author feedback"

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 1:13:16 PM: 
> 2024-12-13 13:13:16.265 [CLI ] Failed to extract archive with code -2147467259 1:13:16 PM: [237C:023C][
> 2024-12-13T13:12:46]w363: Could not create system restore point, error: 0x80070422. Continuing... 1:13:16 PM: MSI (s) (64:78) [13:12:48:313]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.42.34433. Product Version: 14.42.34433. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 904.)

**Comment by denelon** [comment]
WinGet doesn't support compression formats other than .zip. It's a specific setting for users in system context to leverage tar.exe to decompress .zip files as opposed to the shell API for decompression in the referenced PR:
* https://github.com/microsoft/winget-cli/pull/4541

**Comment by denelon** [comment]
Supporting .tar would most likely be part of:
* https://github.com/microsoft/winget-cli/issues/2899

**Comment by denelon** [comment]
Is there an uncompressed version available or something that isn't .tar?

**Comment by FaserF** [comment]
> Is there an uncompressed version available or something that isn't .tar?

Only behind a sign in wall from what I have found :( 

But what about this mergered PR? https://github.com/microsoft/winget-cli/pull/4541 With this from what I read extracting tar files should be available and supported since [1.9.25180](https://github.com/microsoft/winget-cli/releases/tag/v1.9.25180)

**Comment by denelon** [comment]
That PR only switches to use tar.exe to decompress .zip files when the shell APIs aren't available. There is more work needed to support those formats through the normal code flow. We've had work ongoing towards other compression/decompression libraries for multiple formats, but that's been gated by some challenges related to making the feature work on Windows 10.

**Comment by denelon** [comment]
There would also be some similar additional work necessary in wingetcreate to support the other compression formats as well.

**Comment by FaserF** [comment]
Thanks for the clarification, then I am going to close this PR for now.

**Review by rovabunw — COMMENTED** [review]
these are the correct urls

**Pull request closed without merging**
