### PR TITLE
JanDeDobbeleer.OhMyPosh version 7.6.0

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/44393)

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]

**Comment by ryfu-msft** [comment]
@JanDeDobbeleer, when I try installing this on a clean machine, this is what I'm seeing:

```
Found Oh My Posh [JanDeDobbeleer.OhMyPosh] Version 7.6.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v7.6.0/install-amd64.exe
  ██████████████████████████████  5.52 MB / 5.52 MB
Successfully verified installer hash
Starting package install...
Successfully installed
Oh My Posh Error:

NO CONFIG
```

Is that the expected behavior? My prompt also does not automatically change when I know in the past it did like in v7.5.1

**Comment by JanDeDobbeleer** [comment]
@ryfu-msft ah yes. It no longer comes with a default config, the --config flag is required now. Is that an issue for validation?

**Comment by ryfu-msft** [comment]
> @ryfu-msft ah yes. It no longer comes with a default config, the --config flag is required now. Is that an issue for validation?

Not an issue, just wanted to verify the change. I can just create a waiver for this error so that future versions won't produce the same validation result.

**Comment by JanDeDobbeleer** [comment]
@ryfu-msft it might however still be a good idea to have a default output with this indication rather than an error (it should only error when the provided config has an issue).

**Comment by JanDeDobbeleer** [comment]
@ryfu-msft the default config is back as of 7.8.2 (incoming)

**Comment by ryfu-msft** [comment]
> @ryfu-msft the default config is back as of 7.8.2 (incoming)

In that case, I will manually approve your recent PRs until 7.8.2 comes out since this will only be a temporary issue.

**Pull request merged**
