### PR TITLE
New version: WHONET.2023 version 23.14.1

### PR DESCRIPTION
**Pull request by ghost**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137478)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -2145844845 2024-02-01 15:34:58.719 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000 2024-02-01 15:34:58.800 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!555057EB: (caller: 55505E1C) Exception(1) tid(1dc4) 80190193 Forbidden (403). 2024-02-01 15:34:59.315 [CORE] Download request failed. Returned status: 403 2024-02-01 15:34:59.315 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!554FFA75: (caller: 55500E2B) Exception(2) tid(1dc4) 80190193 Forbidden (403). 2024-02-01 15:34:59.561 [CLI ] Failed to download, waiting a bit and retry. Url: https://whonet.org/WHONET
> 2023-Setup-x86.exe 2024-02-01 15:35:00.183 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000 2024-02-01 15:35:00.183 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!555057EB: (caller: 55505E1C) Exception(3) tid(1dc4) 80190193 Forbidden (403). 2024-02-01 15:35:00.249 [CORE] Download request failed. Returned status: 403 2024-02-01 15:35:00.249 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!554FFA75: (caller: 55500E2B) Exception(4) tid(1dc4) 80190193 Forbidden (403). 2024-02-01 15:35:00.452 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!554FFA75: (caller: 55500E2B) Exception(4) tid(1dc4) 80190193 Forbidden (403).

(Automated response - build 694.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -2145844845 2024-02-01 15:34:58.719 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000 2024-02-01 15:34:58.800 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!555057EB: (caller: 55505E1C) Exception(1) tid(1dc4) 80190193 Forbidden (403). 2024-02-01 15:34:59.315 [CORE] Download request failed. Returned status: 403 2024-02-01 15:34:59.315 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!554FFA75: (caller: 55500E2B) Exception(2) tid(1dc4) 80190193 Forbidden (403). 2024-02-01 15:34:59.561 [CLI ] Failed to download, waiting a bit and retry. Url: https://whonet.org/WHONET
> 2023-Setup-x86.exe 2024-02-01 15:35:00.183 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000 2024-02-01 15:35:00.183 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!555057EB: (caller: 55505E1C) Exception(3) tid(1dc4) 80190193 Forbidden (403). 2024-02-01 15:35:00.249 [CORE] Download request failed. Returned status: 403 2024-02-01 15:35:00.249 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!554FFA75: (caller: 55500E2B) Exception(4) tid(1dc4) 80190193 Forbidden (403). 2024-02-01 15:35:00.452 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!554FFA75: (caller: 55500E2B) Exception(4) tid(1dc4) 80190193 Forbidden (403).

(Automated response - build 694.)

**Comment by stephengillie** [comment]
Hi @drshtmstry,

The installation isn't unattended. Is there an installer switch to have the package install silently?

(Automated response - build 694.)

**Comment by drshtmstry** [comment]
```Installation Verification
****************************************************************************************

-----------------------------------------------------
Result: Failed```

How to view what is the error?
How did u get the screenshot of error in previous comment?

> Automatic Validation ended with: ![WHONET 2023 installer](https://private-user-images.githubusercontent.com/114952565/301597308-be571b22-581a-4629-85a7-7643532f84b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY4NTY2OTIsIm5iZiI6MTcwNjg1NjM5MiwicGF0aCI6Ii8xMTQ5NTI1NjUvMzAxNTk3MzA4LWJlNTcxYjIyLTU4MWEtNDYyOS04NWE3LTc2NDM1MzJmODRiNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMlQwNjQ2MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OTJiOTUzMTVhYTk0N2NmZDkyNmI5YzgyYjA1MWEzZWI1NGIyMmM2MTE0YmNmZjhmZTNjOWYxMWJjYTNhMDFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4y8hVqvKRajEWRv-ApgK9GZWtegg8ffP9HLhs_d-I9k)

**Comment by drshtmstry** [comment]
```
Installation Verification
-----------------------------------------------------
Result: Failed
```

How to view what is the error?
How did u get the screenshot of error in previous comment?

> Automatic Validation ended with: WHONET 2023 installer

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 10:53:47 AM: 
> 2024-02-02 10:53:36.500 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000 10:53:47 AM: 
> 2024-02-02 10:53:36.501 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFE01119F7B: (caller: 00007FFE0111A79F) Exception(1) tid(18cc) 80190193 Forbidden (403). 10:53:47 AM: 
> 2024-02-02 10:53:45.263 [CORE] Download request failed. Returned status: 403 10:53:48 AM: 
> 2024-02-02 10:53:45.264 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFE01113F06: (caller: 00007FFE01115769) Exception(2) tid(18cc) 80190193 Forbidden (403). 10:53:48 AM: 
> 2024-02-02 10:53:45.267 [CLI ] Failed to download, waiting a bit and retry. Url: https://whonet.org/WHONET2023-Setup-x64.exe 10:53:48 AM: 
> 2024-02-02 10:53:46.420 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000 10:53:48 AM: 
> 2024-02-02 10:53:46.420 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFE01119F7B: (caller: 00007FFE0111A79F) Exception(3) tid(18cc) 80190193 Forbidden (403). 10:53:48 AM: 
> 2024-02-02 10:53:46.641 [CORE] Download request failed. Returned status: 403 10:53:48 AM: 
> 2024-02-02 10:53:46.641 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFE01113F06: (caller: 00007FFE01115769) Exception(4) tid(18cc) 80190193 Forbidden (403).

(Automated response - build 695.)

**Comment by stephengillie** [comment]
URL: https://whonet.org/WHONET2023-Setup-x86.exe 
Status Code: 200

(Automated message - build 695)

**Review by stephengillie — APPROVED** [review]

**Comment by drshtmstry** [comment]
> > ```
> > Installation Verification
> > -----------------------------------------------------
> > Result: Failed
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > How to view what is the error? How did u get the screenshot of error in previous comment?
> > > Automatic Validation ended with:
> 
> Hi @drshtmstry,
> 
> The image was included in the ADO run log artifacts. They're "available" by:
> 
> * Going through one of the `Azure Pipeline` links on the Checks tab get to the ADO run.
> * Clicking the `N available` (4 for this PR) link.
> * Finding `InstallationVerificationLogs`, clicking the 3 dots to the right, and clicking `Download artifacts`.
> * Unzipping this file.
> * The image should be among the ZIP contents.
> 
> I made a [short function](https://github.com/microsoft/winget-pkgs/blob/39f393fcde6a955901bc2380210e74f7db3747c9/Tools/ManualValidationPipeline.ps1#L992) to automate the above list.

Downloaded the zip file but it only contains txt files. No screenshot of VM.

**Pull request merged**
