### PR TITLE
Renormalize: Spice.SpiceWebDAVd version 2.4.0

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/74899)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by OfficialEsco — APPROVED** [review]
url works

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
