### PR TITLE
New version: PostgreSQL.PostgreSQL.14 version 14.12-1

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings).
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/155103)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 10:52:52 AM: 
> 2024-05-28 10:52:48.619 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000 10:52:52 AM: 
> 2024-05-28 10:52:48.876 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFD8725F180: (caller: 00007FFD8725FACC) Exception(1) tid(d8) 80190193 Forbidden (403). 10:52:52 AM: 
> 2024-05-28 10:52:50.209 [CORE] Download request failed. Returned status: 403 10:52:52 AM: 
> 2024-05-28 10:52:50.209 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFD872591E2: (caller: 00007FFD8725AA19) Exception(2) tid(d8) 80190193 Forbidden (403). 10:52:52 AM: 
> 2024-05-28 10:52:50.211 [CLI ] Failed to download, waiting a bit and retry. Url: https://get.enterprisedb.com/postgresql/postgresql-14.12-1-windows-x64.exe 10:52:52 AM: 
> 2024-05-28 10:52:51.799 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000 10:52:52 AM: 
> 2024-05-28 10:52:51.799 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFD8725F180: (caller: 00007FFD8725FACC) Exception(3) tid(d8) 80190193 Forbidden (403). 10:52:52 AM: 
> 2024-05-28 10:52:52.069 [CORE] Download request failed. Returned status: 403 10:52:52 AM: 
> 2024-05-28 10:52:52.069 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFD872591E2: (caller: 00007FFD8725AA19) Exception(4) tid(d8) 80190193 Forbidden (403).

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 3:08:11 PM: 
> 2024-05-28 15:08:08.673 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000 3:08:11 PM: 
> 2024-05-28 15:08:08.674 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFD8713F180: (caller: 00007FFD8713FACC) Exception(1) tid(29a8) 80190193 Forbidden (403). 3:08:11 PM: 
> 2024-05-28 15:08:09.599 [CORE] Download request failed. Returned status: 403 3:08:11 PM: 
> 2024-05-28 15:08:09.599 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFD871391E2: (caller: 00007FFD8713AA19) Exception(2) tid(29a8) 80190193 Forbidden (403). 3:08:11 PM: 
> 2024-05-28 15:08:09.602 [CLI ] Failed to download, waiting a bit and retry. Url: https://get.enterprisedb.com/postgresql/postgresql-14.12-1-windows-x64.exe 3:08:11 PM: 
> 2024-05-28 15:08:10.759 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000 3:08:11 PM: 
> 2024-05-28 15:08:10.759 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFD8713F180: (caller: 00007FFD8713FACC) Exception(3) tid(29a8) 80190193 Forbidden (403). 3:08:11 PM: 
> 2024-05-28 15:08:10.955 [CORE] Download request failed. Returned status: 403 3:08:11 PM: 
> 2024-05-28 15:08:10.956 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFD871391E2: (caller: 00007FFD8713AA19) Exception(4) tid(29a8) 80190193 Forbidden (403).

(Automated response - build 881.)

**Comment by stephengillie** [comment]
> Manual Validation ended with:
> >  ... Forbidden (403) ... Returned status: 403 ... Forbidden (403) ... Forbidden (403) ... Returned status: 403 ... Forbidden (403).
> 
> (Automated response - build 881.)

Just got the same output. These work in the browser, so it's likely a user-agent block. And what's strange is the first ~30 MB are downloaded before the 403 error occurs. Usually I'd expect the 403 to happen before any downloading happens.

**Comment by SpecterShell** [comment]
> > Manual Validation ended with:
> > > ... Forbidden (403) ... Returned status: 403 ... Forbidden (403) ... Forbidden (403) ... Returned status: 403 ... Forbidden (403).
> > 
> > 
> > (Automated response - build 881.)
> 
> Just got the same output. These work in the browser, so it's likely a user-agent block. And what's strange is the first ~30 MB are downloaded before the 403 error occurs. Usually I'd expect the 403 to happen before any downloading happens.

The server seems to have a strict rate limit. At least for me the installer can be downloaded directly in PowerShell without specifying any user agent.

**Review by Trenly — APPROVED** [review]

**Pull request merged**
