### PR TITLE
New Package: realsast.FlyingCube version 1.0

### PR DESCRIPTION
**Pull request by Trenly**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

* Closes #38669 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/38684)

### CODE REVIEW

**Comment by sastofficial** [comment]
thx so much for doing this for me. ima not delete my forks next time i do this 😃 :)

**Comment by ChuckFerring** [comment]
What is the expected installation location of the application?

**Comment by sastofficial** [comment]
> What is the expected installation location of the application?



> What is the expected installation location of the application?

when i try to download it via the exe file it says D:/Flying Cube. Really weird cus i only had one disk when making this program

(btw the inno project for the installer is https://github.com/superofficial/Flying-Cube/blob/master/Flying%20Cube/Game/Installer/setup%20code.iss)

**Comment by Trenly** [comment]
> What is the expected installation location of the application?
When I run the PRTest script, in windows sandbox it installs to `C:\Program Files (x86)\Flying Cube`

**Comment by ChuckFerring** [comment]
Have you tried running this on an x86 system? I see the following error:

"The specified executable is not a valid application for this OS platform."

Is it possible that this is only able to run on x64 systems?

**Comment by Trenly** [comment]
> Have you tried running this on an x86 system? I see the following error:
> 
> "The specified executable is not a valid application for this OS platform."
> 
> Is it possible that this is only able to run on x64 systems?

I don't have an x86 vm to test on, but I'll see if switching to x64 makes a difference

As a side note, it would be really helpful if those error messages were printed to the pipeline output so that we can see them. Right now we only see that it had to go to manual review
https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=253460&view=logs&j=871b4eed-22de-5cb6-c1c8-82f190de633f&t=58bdf892-4e45-5ba7-4782-31912f95e167

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
