### PR TITLE
Added IntelliJ IDEA Community Edition

### PR DESCRIPTION
**Pull request by denelon**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/179)

### CODE REVIEW

**Comment by mimi89999** [comment]
In the case of Jetbrains installers only `mode=admin` is required. I tried to convince them to make it default (currently they have no default for this), but they didn't understand the issue:

**Comment by lokinmodar** [comment]
> In the case of Jetbrains installers only `mode=admin` is required. I tried to convince them to make it default (currently they have no default for this), but they didn't understand the issue: https://youtrack.jetbrains.com/issue/IDEA-226645
> 
> Maybe the community could convinve them to have sane defaults and not require a config file for a very common install config.

This is an issue for all their installers. They refuse to acknowledge the problem.

**Comment by mimi89999** [comment]
Two other issues have been opened (https://youtrack.jetbrains.com/issue/IDEA-242025, https://youtrack.jetbrains.com/issue/TBX-4949), but there still isn't any real feedback from them. I think that the problem here is that they don't quite understand what they have to do.

**Comment by KevinLaMS** [comment]
as mentioned above this is blocked.
image

**Comment by mimi89999** [comment]
I opened the PR with the required changes to IntelliJ two months ago, but is still hasn't been accepted. The dev that is following this PR asked about winger popularity in https://github.com/JetBrains/intellij-community/pull/1400#issuecomment-684702491. Maybe the community and users who would like to see JetBrains products in WinGet could speak up in that pull request?

**Comment by denelon** [comment]
It looks like the PR at JetBrains is closed https://github.com/JetBrains/intellij-community/pull/1400#issuecomment-684702491 but there was a comment from @trespasserw indicating the change is in the main branch. The manifest here would need to be updated to the current supported version.

**Comment by denelon** [comment]
@mimi89999 feel free to submit a new PR and I'll close this one, or let me know what changes need to be made.

**Comment by mimi89999** [comment]
@denelon I will submit a PR when the new version with that change will be released. Now we basically only need to wait for the release and it should work as any other NSIS installer, so it will be easy to add.

**Comment by mimi89999** [comment]
@denelon Just opened https://github.com/microsoft/winget-pkgs/pull/5212

**Comment by mimi89999** [comment]
Also opened https://github.com/microsoft/winget-pkgs/pull/5213 for PyCharm

**Comment by denelon** [comment]
JetBrains.IntelliJIDEA.Community was added in another PR.

**Pull request closed without merging**
