### PR TITLE
New version: Discord.Discord version 1.0.9031

### LINKED ISSUE #136960: [Package Issue]: Discord.Discord requires explicit targeting and upgrade fails with "Installer hash does not match"
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Discord upgrade with `winget upgrade -h --all` fails because it requires a explicit targeting.
Upgrading with explicit targeting fails with "Installer hash does not match"

### Steps to reproduce

Run `winget upgrade -h --all`, then run `winget upgrade -h Discord.Discord`.

### Actual behavior

After the first command the upgrade is not executed and I get the following message:

```powershell
The following packages have an upgrade available, but require explicit targeting for upgrade:
Name    Id              Version  Available Source
-------------------------------------------------
Discord Discord.Discord 1.0.9012 1.0.9030  winget
``` 

After the second command the upgrade is not executed and I get the following error:

```powershell
Found Discord [Discord.Discord] Version 1.0.9030
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://discord.com/api/downloads/distributions/app/installers/latest?channel=stable&platform=win&arch=x86
  ██████████████████████████████  91.7 MB / 91.7 MB
Installer hash does not match; this cannot be overridden when running as admin
``` 

### Expected behavior

The upgrade succeeds after the first command, or at least after the second.

### Environment

```raw
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3085
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0
```

### Screenshots and Logs

[WinGet-2024-01-29-11-47-13.285.log](https://github.com/microsoft/winget-pkgs/files/14082589/WinGet-2024-01-29-11-47-13.285.log)
[WinGet-2024-01-29-11-47-20.241.log](https://github.com/microsoft/winget-pkgs/files/14082590/WinGet-2024-01-29-11-47-20.241.log)

### PR DESCRIPTION
**Pull request by Exorcism0666**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---
- Resolve: #136960 

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136871)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-28T10:21:04.0662461Z ##[error] One or more errors occurred. (SQL error or missing database (0x87AF0001)) SQL error or missing database (0x87AF0001)

(Automated response - build 669.)

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification.
>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-28T14:42:31.8558339Z -----------------------------------------------------
 2024-01-28T14:42:31.8562620Z Status: Started
 2024-01-28T14:42:31.8567964Z Manifest file is Added
 2024-01-28T14:42:31.9579515Z ##[warning] Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended.
 2024-01-28T14:42:32.0575323Z Manifest content validated.
 2024-01-28T14:42:32.0591023Z Manifest contains installer: https://discord.com/api/downloads/distributions/app/installers/latest?channel=stable&platform=win&arch=x86
 2024-01-28T14:42:32.0592423Z Manifest contains installer: https://discord.com/api/downloads/distributions/app/installers/latest?channel=stable&platform=win&arch=x64
 2024-01-28T14:42:32.1847096Z Status: Completed
2024-01-28T14:42:32.3481040Z -----------------------------------------------------
 2024-01-28T14:42:32.3486951Z Status: Started
 2024-01-28T14:42:32.3495147Z Manifest file is Deleted
 2024-01-28T14:42:32.5996288Z Status: Completed
 2024-01-28T14:42:32.6004349Z ##[error] Result: Failed
 2024-01-28T14:42:32.6198593Z ##[error] Sequence contains no elements
 2024-01-28T14:42:32.6806637Z ##[error]Manifest Validation Failed
 2024-01-28T14:42:32.6818440Z 

(Automated response - build 674.)

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 674.)

**Pull request closed without merging**
