### PR TITLE
Remove version: darktable.darktable version 4.8.0

### PR DESCRIPTION
**Pull request by pxwiz**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164474)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://github.com/darktable-org/darktable/releases/download/release-4.8.0/darktable-4.8.0-win64.exe 
OK

(Automated message - build 912)

**Comment by stephengillie** [comment]
Hi @pxwiz,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 887.)

**Comment by pxwiz** [comment]
> Hi @pxwiz,
> 
> This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)
> 
> (Automated response - build 887.)

@stephengillie, as mentioned in PR description, I'd submitted the manifest for version 4.8.1 & requested removal of the previous version.

**Comment by stephengillie** [comment]
Apologies.
- https://github.com/microsoft/winget-pkgs/pull/164471

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
