### PR TITLE
New version: yt-dlp.yt-dlp version 2024.07.02

### PR DESCRIPTION
**Pull request by aisgbnok**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161200)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by aisgbnok** [comment]
@stephengillie, not sure why this didn't auto merge?

**Comment by DuckDuckStudio** [comment]
> not sure why this didn't auto merge?
Because this? ([my PR](https://github.com/microsoft/winget-pkgs/pull/161155) has same issue, but my PR was no this event)
image

**Comment by aisgbnok** [comment]
> > not sure why this didn't auto merge?
> 
> Because of this? ([my PR](https://github.com/microsoft/winget-pkgs/pull/161155) has same issue, but my PR not have this event) image
> 
> These pull request(s) don't seem to have been automatically merged too: #161100

Yeah, I think, because the policy bot also approves the PR, the auto merge sometimes disables when lots of PRs are being approved at once. Like a race condition.

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
