### PR TITLE
MSI.Afterburner version 4.6.3

### PR DESCRIPTION
**Pull request by techflashYT**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14799)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Where did you find the link to this installer? AFAK MSI Afterburner only comes in zip

**Comment by sanikdah** [comment]
> Where did you find the link to this installer? AFAK MSI Afterburner only comes in zip

gimme a sec to find the website

**Comment by sanikdah** [comment]
It says 4.6.4 but it's actually 4.6.3
https://www.techspot.com/downloads/downloadnow/4895/?evp=9858ec862e7b1c3cd8edfaef2e9cb711&file=1

**Comment by sanikdah** [comment]
also i have to go eat lunch now, i'll be back in like an hour an a half.

**Pull request merged**
