### PR TITLE
Moving plex.plexmediaserver v1.24.2.4973

### PR DESCRIPTION
**Pull request by KaranKad**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/27656)

### CODE REVIEW

**Comment by ImJoakim** [comment]
What/where are you moving it to btw @KaranKad

**Comment by ImJoakim** [comment]
> What/where are you moving it to btw @KaranKad

I'm guessing your notifications are spammed haha, and that you're moving it to manifests/p/Plex/, is that what you're doing?

**Comment by KaranKad** [comment]
> > What/where are you moving it to btw @KaranKad
> 
> I'm guessing your notifications are spammed haha, and that you're moving it to manifests/p/Plex/, is that what you're doing?

Yeah

**Comment by ImJoakim** [comment]
> > > What/where are you moving it to btw @KaranKad
> > 
> > 
> > I'm guessing your notifications are spammed haha, and that you're moving it to manifests/p/Plex/, is that what you're doing?
> 
> Yeah

Alrighty, just wanted to know what I'm approving 😅

**Review by ImJoakim — APPROVED** [review]

**Comment by ImJoakim** [comment]
I might've broken or rate limited the bot 😅

**Pull request merged**
