### PR TITLE
New package: Google.BloggerForWord version 11.00.28844

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/117424)

### CODE REVIEW

**Comment by stephengillie** [comment]
I'm not able to determine that this package is installed.
- It's a Word plugin, if I'm understanding correctly, so has no shortcuts.
- Validation VM doesn't have Office installed - should it be a dependency?
- Doesn't add any files to any Office or Word folders. Can't tell if it added any at all. 
- Not listed in Apps section of Settings. 
- No logs in Event Viewer.

Can you help me to verify that this package installed correctly?

**Comment by upintheairsheep** [comment]
> I'm not able to determine that this package is installed.
> 
> * It's a Word plugin, if I'm understanding correctly, so has no shortcuts.
> * Validation VM doesn't have Office installed - should it be a dependency?
> * Doesn't add any files to any Office or Word folders. Can't tell if it added any at all.
> * Not listed in Apps section of Settings.
> * No logs in Event Viewer.
> 
> Can you help me to verify that this package installed correctly?

I guess it’s added, but office should probably be a dependency

**Comment by stephengillie** [comment]
> I guess it’s added, but office should probably be a dependency

I had the same reaction. Is there a more definitive check?

**Comment by stephengillie** [comment]
Hi @upintheairsheep,

This installer doesn't seem to respond to installer switches in the expected way. Any /S or /s switch makes it fail silently, and any other switch causes the installer to launch interactively.

**Pull request closed without merging**
