### PR TITLE
New package: BigRedConsulting.DirectDepositFileCreator version 2.10

### PR DESCRIPTION
**Pull request by jahvari**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/126923)

### CODE REVIEW

**Comment by jahvari** [comment]
I am currently seeing this in the log when attempting to install. Trying to determine the cause.

2023-11-15 21:54:32.038 [CORE] WinGet, version [1.6.3133], activity [{952885C3-D0F7-48BD-BBB7-2C4192C4E508}]
2023-11-15 21:54:32.038 [CORE] OS: Windows.Desktop v10.0.19045.3570
2023-11-15 21:54:32.038 [CORE] Command line Args: winget  install --manifest "C:\Users\Hunter Johnston\manifests\b\BigRedConsulting\DirectDepositFileCreator\2.10"
2023-11-15 21:54:32.038 [CORE] Package: Microsoft.DesktopAppInstaller v1.21.3133.0
2023-11-15 21:54:32.038 [CORE] IsCOMCall:0; Caller: winget-cli
2023-11-15 21:54:32.045 [CLI ] WinGet invoked with arguments: 'install' '--manifest' 'C:\Users\Hunter Johnston\manifests\b\BigRedConsulting\DirectDepositFileCreator\2.10'
2023-11-15 21:54:32.045 [CLI ] Found subcommand: install
2023-11-15 21:54:32.045 [CLI ] Leaf command to execute: root:install
2023-11-15 21:54:32.047 [CLI ] Executing command: install
2023-11-15 21:54:32.048 [CLI ] Manifest fields: Name [Direct Deposit File Creator], Version [2.10]
2023-11-15 21:54:32.049 [CLI ] Starting installer selection.
2023-11-15 21:54:32.049 [CLI ] Completed installer selection.
2023-11-15 21:54:32.067 [CLI ] Found existing installer file at 'C:\Users\HUNTER~1\AppData\Local\Temp\WinGet\BigRedConsulting.DirectDepositFileCreator.2.10\DirectDepositCreatorInstall210.zip'. Verifying file hash.
2023-11-15 21:54:32.069 [CLI ] Existing installer file hash matches. Will use existing installer.
2023-11-15 21:54:32.069 [CLI ] Installer hash verified
2023-11-15 21:54:32.069 [CORE] Started applying motw using IAttachmentExecute to C:\Users\HUNTER~1\AppData\Local\Temp\WinGet\BigRedConsulting.DirectDepositFileCreator.2.10\DirectDepositCreatorInstall210.zip
2023-11-15 21:54:32.097 [CORE] Finished applying motw using IAttachmentExecute. Result: 0 IAttachmentExecute::Save() result: 0
2023-11-15 21:54:32.097 [REPO] Creating new SQLite Index with version [Latest] at ':memory:'
2023-11-15 21:54:32.097 [SQL ] Opening SQLite connection #1: ':memory:' [6, 0]
2023-11-15 21:54:32.124 [REPO] Reading MSI UpgradeCodes
2023-11-15 21:54:32.191 [REPO] Reading MSI UpgradeCodes
2023-11-15 21:54:32.336 [CLI ] Archive malware scan passed
2023-11-15 21:54:32.336 [CLI ] Extracting archive to: C:\Users\HUNTER~1\AppData\Local\Temp\WinGet\BigRedConsulting.DirectDepositFileCreator.2.10\extracted
2023-11-15 21:54:32.425 [CLI ] Successfully extracted archive
2023-11-15 21:54:32.426 [CLI ] Setting installerPath to: C:\Users\HUNTER~1\AppData\Local\Temp\WinGet\BigRedConsulting.DirectDepositFileCreator.2.10\extracted\BRCDirectDepositCreatorInstall.exe
2023-11-15 21:54:32.533 [CLI ] Installer args: 
2023-11-15 21:54:32.534 [CLI ] Starting: 'C:\Users\HUNTER~1\AppData\Local\Temp\WinGet\BigRedConsulting.DirectDepositFileCreator.2.10\extracted\BRCDirectDepositCreatorInstall.exe' with arguments ''
2023-11-15 21:54:40.405 [CLI ] ShellExecute installer failed: 1
2023-11-15 21:54:40.405 [CLI ] Terminating context: 0x8a150006 at C:\__w\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:1fe

**Comment by jahvari** [comment]
Close #126842

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

(The installer is behind the console window.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by stephengillie** [comment]
Hi @jahvari,

Are there installer switches to complete the install silently?

**Comment by jahvari** [comment]
@stephengillie I do not believe there is any installer switches. The user will have to interact with the installer setup GUI for it to finish it.

**Pull request closed without merging**
