### PR TITLE
IObit.StartMenu version 6.0.0.2

### PR DESCRIPTION
**Pull request by KarbitsCode**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/168067)

### CODE REVIEW

**Comment by stephengillie** [comment]
Verify:
This application won't run due to missing DLLs. Clicking the Desktop shortcut gives: 
- datastate.dll
image
- sqlite3.dll
sqlite3.dll
- FileSearch.dll
FileSearch.dll

But the About page is its own application, and seems to run fine without the DLLs:
image

**Comment by KarbitsCode** [comment]
> This application won't run due to missing DLLs. Clicking the Desktop shortcut gives:

Those DLLs are located in the same directory as the main application (ClassicStart.exe), can you try to start the app from those directory directly?

**Comment by stephengillie** [comment]
> > This application won't run due to missing DLLs. Clicking the Desktop shortcut gives:
> 
> Those DLLs are located in the same directory as the main application (ClassicStart.exe), can you try to start the app from those directory directly?

Double-clicking the `EXE` in its folder had the same outcome:
image
Unfortunately, Windows couldn't find this DLL in the folder:
image

**Comment by KarbitsCode** [comment]
That seems like an incomplete install. I've just testing it in windows sandbox and those dll file installed correctly.

Screenshot 2024-08-21 093301
Screenshot 2024-08-21 094235
Screenshot 2024-08-21 094304
Screenshot 2024-08-21 094353

**Comment by stephengillie** [comment]
Hi @KarbitsCode,

I've installed it twice with the same results. I'm not convinced that installing a 3rd time will have different results. If the install is not completing, then it's a consistent issue that should be troubleshot. 
- Is an inomplete installation a common issue with this package? 
- Or could a framework or library be missing?

**Comment by KarbitsCode** [comment]
> * Is an inomplete installation a common issue with this package?

I'm not sure if this is common issue, since I've just test install this twice on sandbox and both are ok.

> * Or could a framework or library be missing?

Maybe not, this package should be a standalone package (I mean, it comes with the library it's needed).

I guess this is another blocking issue for now.

**Pull request closed without merging**
