### PR TITLE
Remove version: Datronicsoft.SpacedeskDriver.Server version 2.1.0.5

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/138399)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-08T17:39:35.3894117Z Processing manifest: manifests\d\Datronicsoft\SpacedeskDriver\Server\2.1.0.5
 2024-02-08T17:39:35.3901520Z -----------------------------------------------------
 2024-02-08T17:39:35.3910154Z Status: Started
 2024-02-08T17:39:35.3918954Z Manifest file is Deleted
 2024-02-08T17:39:35.6812430Z Status: Completed
 2024-02-08T17:39:35.6856676Z ##[error] Result: Failed
 2024-02-08T17:39:35.7025989Z ##[error] Sequence contains no elements
 2024-02-08T17:39:35.7606728Z ##[error]Manifest Validation Failed

(Automated response - build 716.)

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 716.)

**Comment by stephengillie** [comment]
URL: https://spacedesk.net/downloads/spacedesk_driver_Win_10_64_v2105.msi 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 716)

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

This manifest has the highest version number for this package. Is it available from another location?

(Automated response - build 719.)

**Comment by stephengillie** [comment]
> Hi @Exorcism0666,
> 
> This manifest has the highest version number for this package. Is it available from another location?
> 
> (Automated response - build 719.)

This appears to have been in error. Sorry.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
