### PR TITLE
New version: Storj.Uplink version 1.96.6

### PR DESCRIPTION
**Pull request by mniewrzal**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/142706)

### CODE REVIEW

**Comment by mniewrzal** [comment]
@microsoft-github-policy-service agree company="Storj"

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Storj.Uplink__DefaultSource\uplink.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\uplink.exe returned exit code: 1

(Automated response - build 861.)

**Comment by stephengillie** [comment]
Hi @profclems,

My waiver abilites are blocked currently, but I might have another solution for this and many other PRs.

**Comment by stephengillie** [comment]
Completing validation.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
