### PR TITLE
New version: GiulioSorrentino.Backgrounds version 2.0

### PR DESCRIPTION
**Pull request by GiulianoSpaghetti**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/127470)

### CODE REVIEW

**Comment by stephengillie** [comment]
I couldn't verify that the background images were placed on the VM.

**Comment by numerunix** [comment]
The exe is recompiled with the binary specific of the platform (so it takes a while) and then shows the progress bar, there is not silent install.

The backgrounds are putted in -o"C:\windows\web\wallpaper\numeronesoft-backgrounds" -y

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 2023-11-28 13:32:36.287 [CORE] WinINet downloading from url: http://numeronesoft.ddns.net/numeronesoft-backgrounds-0.4.exe  
> 2023-11-28 13:32:57.432 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FFA71F5395E: (caller: 00007FFA71F55C49) Exception(2) tid(1b74) 80072EFD     Msg:[InternetOpenUrl() failed.]

**Comment by stephengillie** [comment]
The host appears to be down:
image

**Comment by numerunix** [comment]
It's back online.

**Comment by stephengillie** [comment]
> The exe is recompiled with the binary specific of the platform (so it takes a while) and then shows the progress bar, there is not silent install.
> 
> The backgrounds are putted in C:\windows\web\wallpaper\numeronesoft-backgrounds, if runned with administrative priviledges.

Ah here they are. Thanks for helping me to find them. 
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
