### PR TITLE
Add third party repo listing note

### PR DESCRIPTION
**Pull request by mattwojo**
- [ x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ x]Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/45836)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
https://github.com/MicrosoftDocs/windows-uwp/pull/3580#issuecomment-1036570544
> I believe we may remove the section related to third-party repositories all together. We can then evaluate the options for best helping our customers become aware of third-party offerings.

I don't think that this is the best way to list the third party solutions. I would suggest we wait for complete alignment on the best option before adding any additional references that may end up having to be removed later.

**Comment by mattwojo** [comment]
@Trenly - we removed the section relating to third-party repositories from the docs, as docs.microsoft.com needs to remain focused on providing technical guidance, but I'm proposing that these third-party repo offerings be listed here in the winget-pkgs repo. I've looped in @denelon and @KevinLaMS to weigh in.

**Review by denelon — APPROVED** [review]

**Comment by Trenly** [comment]
https://github.com/MicrosoftDocs/windows-uwp/pull/3580#issuecomment-1036570544

> @Trenly - we removed the section relating to third-party repositories from the docs, as docs.microsoft.com needs to remain focused on providing technical guidance, but I'm proposing that these third-party repo offerings be listed here in the winget-pkgs repo. I've looped in @denelon and @KevinLaMS to weigh in.

Not saying that they shouldn't be documented somewhere, but as denelon stated in the other thread, we should evaluate the best option for making customers aware of it. For example, it could be put in with documentation about setting up your own source. But, if denelon and Kevin agree, then that's their decision. Just trying to bring more opinions to the table

**Comment by denelon** [comment]
We can iterate here to include winstall.app and any other GUIs/tools/services. This is a great start!

**Pull request merged**
