### PR TITLE
New package: Comfy.ComfyUI-Desktop version 0.3.18

### PR DESCRIPTION
**Pull request by jo-chemla**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/194595)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 899.)

**Comment by jo-chemla** [comment]
Request to publish comfyUI desktop via future-proof urls on github releases done here https://github.com/Comfy-Org/desktop/issues/455
Otherwise, should I just re-submit the package with the vanity url so the sha256 do match during validation - so then users willing to install ComfyDesktop it can simply do it and accept package hash mismatch?

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-12-10 13:53:58.505 [CLI ] Package hash verification failed. SHA256 in manifest [f4b5b64a902afdbddf39ee2f7e5748afadd8d5017a9ca5deaa351ed42d78faff] does not match download [992e741fb5956aa96061f54345f675292c4672a2aed19cbaa5c38bbde0941452] with file size [111905608] and content type []

(Automated response - build 903.)

**Pull request closed without merging**
