### PR TITLE
New package: NewCloud.NewSSTeacher version 1.03.1197

### PR DESCRIPTION
**Pull request by haohuancheng**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/120001)

### CODE REVIEW

**Comment by haohuancheng** [comment]
@microsoft-github-policy-service agree company="NewCloud"

**Comment by stephengillie** [comment]
Hi @haohuancheng,

This manifest results in the installer being placed onto the PC, instead of the application installed. This appears to be an InstallShield installer instead of a Portable installer. 
image

**Comment by stephengillie** [comment]
I'm not sure why this install got the Student installer despite downloading the Teacher installer.

**Comment by haohuancheng** [comment]
> I'm not sure why this install got the Student installer despite downloading the Teacher installer.

in each installer file, there are same exe application filename, but not config file.

**Comment by haohuancheng** [comment]
> Hi @haohuancheng,
> 
> This manifest results in the installer being placed onto the PC, instead of the application installed. This appears to be an InstallShield installer instead of a Portable installer. image

So, installtype should be exe. I'm trying to make some changes. How can I update them again?

**Pull request closed without merging**
