### PR TITLE
Finebits Metro Commander app added

### PR DESCRIPTION
**Pull request by ValeraFinebits**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/621)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
This is blocked because we do not have a the ability to pull in dependencies
It will not install if the framework is not there.

**Comment by ValeraFinebits** [comment]
> This is blocked because we do not have a the ability to pull in dependencies
> It will not install if the framework is not there.

@KevinLaMS, how I can fix it?

**Comment by KevinLaMS** [comment]
Greetings. This package fails because it is dependent on some frameworks, and we do not support the dependencies yet. microsoft/winget-cli#163

In the meantime, if you include the dependencies in your package, it should pass. Thanks.
From what I can tell, you need Microsoft.Services.Store.Engagement.  If you need further instructions, do not hesitate to ping me.

**Comment by ValeraFinebits** [comment]
Looks like I can't add Microsoft.Services.Store.Engagement

MakeAppx : error: Error info: error 80080204: The package with file name "Microsoft.Services.Store.Engagement_10.0.19011.0_arm__8wekyb3d8bbwe.appx" and package full name "Microsoft.Services.Store.Engagement_10.0.19011.0_arm__8wekyb3d8bbwe" is not valid in the bundle because it's a framework package.
MakeAppx : error: Bundle creation failed.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
