### PR TITLE
Update: KDE.Kate version 22.12.0 [FP-O]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | Kate | Kate    |
| Version     | 22.12.0     | 22.12.0 |
| Publisher   | KDE e.V.   | KDE e.V.      |
| ProductCode |           | Kate    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [5090](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/3853335465>)

### CODE REVIEW

**Comment by stephengillie** [comment]
Duplicate of #93087

**Comment by russellbanks** [comment]
@msftbot reset feedback

**Review by ImJoakim — APPROVED** [review]

**Review by ImJoakim — APPROVED** [review]

**Pull request merged**
