### PR TITLE
ObsidiumSoftware.MonkeyMote4Foobar version 3.3.8.0

### PR DESCRIPTION
**Pull request by MysticCereal**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/100213)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @MysticCereal,

The application installed normally, but didn't install any executables, only these 2 files:
```
C:\Users\User\AppData\Roaming\foobar2000\user-components\foo_monkeymote\foo_monkeymote.dll
C:\Users\User\AppData\Roaming\foobar2000\user-components\foo_monkeymote\foo_monkeymote_uninstall.exe
```

**Comment by MysticCereal** [comment]
Hi @stephengillie,
This is expected. The program is a "component installer" rather than a "program installer". The user installing this program should already know this beforehand. 

It installs the component/plugin needed into the component folder of foobar2000, a media player, which is located by default at `C:\Program Files\foobar2000\components`. If foobar2000 isn't installed on the computer, it then falls back to installing them at `%appdata%\foobar2000\user-components\`.

This behavior is already noted in the manifest `InstallationNotes: The component will by default be installed in either foobar2000\user-components in your application data folder or C:\Program Files\foobar2000\components.` to remind users.

**Comment by MysticCereal** [comment]
Hi @stephengillie,
This is expected. The program is a "component installer" rather than a "program installer". The user installing this program should already know this beforehand. 

It installs the component/plugin into the component folder of foobar2000, a media player, which is located by default at `%appdata%\foobar2000\user-components\`.

This behavior is already noted in the manifest `InstallationNotes: The component will by default be installed in either foobar2000\user-components in your application data folder or C:\Program Files\foobar2000\components.` to remind users.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
