### PR TITLE
New package: JackenWu.MSearcher version 1.4.2

### PR DESCRIPTION
**Pull request by DuckDuckStudio**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`? - https://github.com/microsoft/winget-pkgs/pull/196163#issuecomment-2528305987
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

> [!TIP]
> The developers of the package put the package installer in a zip file.
> The developers of the package provide an introductory video and documentation:
> - [当你相册里有几千张meme图，水群时却找不到那张在你相册角落的图](https://www.bilibili.com/video/BV1sRm9YQEat/)
>
> https://github.com/user-attachments/assets/59360835-d8a6-4dd9-b456-893bba75a2f6
>
> - [如何使用 MSearcher](https://github.com/Jacken-Wu/MSearcher/blob/main/docs/how_to_use.md)

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/196163)

### CODE REVIEW

**Comment by DuckDuckStudio** [comment]
Successfully test the installation manually with the following command:

```powershell
& "D:\Duckhome\CodeDebug\MSearcher Setup 1.4.2.exe" /S /D=D:\Duckhome\CodeDebug\winngetaaa
```

**Comment by DuckDuckStudio** [comment]
@stephengillie - Maybe you can take a look at this pull request before the pipeline validation ends.

Pipeline validation always flagged this pull request as https://github.com/microsoft/winget-pkgs/labels/Validation-Unattended-Failed , but everything worked fine when I used `winget install -m` validation locally.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 899.)

**Comment by stephengillie** [comment]
Verify:
image
I couldn't find how to have the application display its version.

**Comment by DuckDuckStudio** [comment]
> I couldn't find how to have the application display its version.

Me too, maybe the developers didn't design this feature...

**Comment by DuckDuckStudio** [comment]
@stephengillie - It seems waivers were not successfully added...

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-12-06 10:40:28.266 [FAIL] Installer failed security check. Url: https://github.com/Jacken-Wu/MSearcher/releases/download/v1.4.2/MSearcher_Setup_1.4.2_win_x64.zip Result: 0x80004005

(Automated response - build 900.)

**Comment by DuckDuckStudio** [comment]
> Manual Validation ended with:
> 
> > 2024-12-06 10:40:28.266 [FAIL] Installer failed security check. Url: https://github.com/Jacken-Wu/MSearcher/releases/download/v1.4.2/MSearcher_Setup_1.4.2_win_x64.zip Result: 0x80004005
> 
> (Automated response - build 900.)

The installer has been submitted to virustotal.
zip: https://www.virustotal.com/gui/file/26d0e2017e4f7dd084d41c3f426156b4852c0e6b8d4e1f0b9fdadfcfbfbcb0db/detection
unzip: https://www.virustotal.com/gui/file/c72fff26543a4cead8f2a0b92d3b4f0a0fc5367bbb52ed637a8ab8e1f917658c
Also submitted to Microsoft Security Intelligence, results pending.

**Comment by DuckDuckStudio** [comment]
- https://github.com/microsoft/winget-pkgs/pull/196163#issuecomment-2528305987

**Comment by stephengillie** [comment]
Verify:
image

**Comment by stephengillie** [comment]
> @ stephengillie - Pipeline validation always flagged this pull request as [ Validation-Unattended-Failed](https://github.com/microsoft/winget-pkgs/labels/Validation-Unattended-Failed) During installation testing the installer was blocked on user input and no switches were provided. , but everything worked fine when I used `winget install -m` validation locally.

Since a recent pipeline change, logs are no longer emitted. To troubleshoot these, I have to install into a VM. But there are too many to install all errors on to a VM.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
