### PR TITLE
LyX.LyX version 2.3.6.1

### PR DESCRIPTION
**Pull request by Shengyis**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/62657)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Duplicate of https://github.com/microsoft/winget-pkgs/pull/7811.

We're going to have to wait until support for interactive-only installers are implemented.

**Comment by Shengyis** [comment]
> 
Here is my test, no need the user interaction. 

no_user_i

And this is with user interaction.

with_user_i

The architecture is x64 instead of x86. I did not test the x86 one. But it seems the x64 one works well.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
At least on a clean installation of Windows (automated tests happen on VMs), silent install seems broken for this app on WinGet: https://github.com/microsoft/winget-pkgs/issues/54476#issuecomment-1068110105

**Comment by Shengyis** [comment]
oh...this is because lyx needs Texlive or Miktex installed in the system.....sad..

**Review by ItzLevvie — DISMISSED** [review]

**Comment by Trenly** [comment]
@itzlevvie - Just curious as I've seen a few times lately where you've suggested changes, and then later approved the PR with no changes??

If you have automation in place or a function to approve, perhaps a filter to exclude PR's with `Needs-Author-Feedback` would be important?

**Comment by Shengyis** [comment]
@Trenly I don't know what to do next. Lyx needs to locate latex.exe during installation. So if there is Miktex/Texshop installed previously,  Lyx can be installed silently and with no error. But in VMs, the clean installation will report an error.

**Comment by Trenly** [comment]
> @Trenly I don't know what to do next. Lyx needs to locate latex.exe during installation. So if there is Miktex/Texlive installed previously, Lyx can be installed silently and with no error. But in VMs, the clean installation will report an error.

This PR is blocked by microsoft/winget-cli#163 and the PR cannot be merged until the winget cli supports installing dependencies

**Comment by Shengyis** [comment]
thx. good to know.

**Comment by Shengyis** [comment]
but, the current version 2.3.5.2 should have the same problem. it will locate latex.exe when installing as well

**Comment by Trenly** [comment]
> but, the current version 2.3.5.2 should have the same problem. it will locate latex.exe when installing as well

Actually, 2.3.5.2 doesn't require latex.exe to complete the installation. It may cause some issues if it isn't present, but it isn't a dependency until newer versions
image

**Comment by FlorianPfaff** [comment]
The GUI interface has an option "Do not use LaTeX", maybe this could help to install without any dependency on miktex or some other LaTeX distribution. However, I do not know if it can be "checked" using command line commands.

**Comment by Shengyis** [comment]
> 

it seems lyx has no available options to set "do not use latex" when installing using command line. lyx-xxx.exe /? just starts GUI installation.

**Comment by FlorianPfaff** [comment]
Thanks for trying! Inow reported setting this via command line as a feature request now on the LyX bug tracker
[lyx.org/trac/ticket/12559](url)
Maybe they will consider it, which would help solve the problem (though it would be best if winget supported dependencies...).

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
You can set this pull request to DRAFT.

**Comment by ItzLevvie** [comment]
@msftbot Interactive-Only-Installer

**Comment by ItzLevvie** [comment]
@msftbot Blocking-Issue

**Comment by ItzLevvie** [comment]
[Policy] Dependencies

**Pull request closed without merging**
