### PR TITLE
New version: IObit.DriverBooster 11.1.0.26

### PR DESCRIPTION
**Pull request by TommyE123**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `https://github.com/microsoft/winget-pkgs/tree/master/manifests/i/IObit/DriverBooster/11.1.0.26` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131808)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @TommyE123,

> This PR's version number 11.1.0.26 has 4 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version 10.4.0, which has 3 parameters.

Is this intentional?

(Automated response - build 489)

**Comment by stephengillie** [comment]
Hi @TommyE123,

This PR's version number 11.1.0.26 has 4 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version 10.4.0, which has 3 parameters.

Is this intentional?

(Automated response - build 494)

**Comment by TommyE123** [comment]
Hi, I was in two minds if I should include the build number 26. Previously it was missed off, however per the screenshot it is included in the About page of Driver Booster. I'm happy to remove though and revert to 11.1.0, if you would rather. 🙂 DB About

**Comment by stephengillie** [comment]
> Hi, I was in two minds if I should include the build number 26. Previously it was missed off, however per the screenshot it is included in the About page of Driver Booster. I'm happy to remove though and revert to 11.1.0, if you would rather. 🙂 DB About

I believe that this has to match the Apps & Features page in the Settings app.

**Comment by stephengillie** [comment]
This PR appears to modify 2 manifest versions: `10.4.0` and `11.1.0.26`. Is this accurate, or is this an artifact of GitHub displaying the PR?
image

**Comment by TommyE123** [comment]
Hi,
I noticed that version 10.4.0 of Driver Booster in Winget is currently broken. It seems the sha256 hash doesn't match the downloaded file anymore. This is likely because a generic file name is used, which has now been updated to a newer version. As a result, there is no way to install 10.4.0 anymore.

To fix this, I went ahead and changed the version listed from 10.4.0 to the latest working one - 11.1.0.26. This should allow installations to proceed again.

However, if you would prefer to keep the reference to the old broken 10.4.0 version instead of changing it, please let me know. I wanted to provide a quick fix, but don't want to change how you would normally perform this type of change. In which case, I could submit a future request to fully remove the outdated reference of 10.4.0. Just let me know your preference!

thanks
Tom

**Comment by stephengillie** [comment]
Hi @TommyE123,

> Hi, I noticed that version 10.4.0 of Driver Booster in Winget is currently broken. It seems the sha256 hash doesn't match the downloaded file anymore. This is likely because a generic file name is used, which has now been updated to a newer version. As a result, there is no way to install 10.4.0 anymore.
>
> To fix this, I went ahead and changed the version listed from 10.4.0 to the latest working one - 11.1.0.26. This should allow installations to proceed again.

Thanks for working to fix this.

> However, if you would prefer to keep the reference to the old broken 10.4.0 version instead of changing it, please let me know. I wanted to provide a quick fix, but don't want to change how you would normally perform this type of change. In which case, I could submit a future request to fully remove the outdated reference of 10.4.0. Just let me know your preference!

The issue is that we have a limit of 1 manifest change per PR. So the removal will have to occur in a separate PR. If you're willing to revert the removal in this PR, and perform it in another PR, I'd be happy to approve both.

**Comment by TommyE123** [comment]
Hi, Sorry about that, Please see that this PR now simply adds the new version as requested.
Once its merged i'll happily create a remove PR as well for the old version after. 🙂

**Comment by stephengillie** [comment]
Hi @TommyE123,

> This PR's version number 11.1.0.26 has 4 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version 10.4.0, which has 3 parameters.

Is this intentional?

(Automated response - build 522)

**Comment by stephengillie** [comment]
This manifest contains a term that is blocked:

> True True

(Automated response - build 522.)

**Review by stephengillie — APPROVED** [review]

**Comment by hexerus** [comment]
Winget shows an upgrade for DriverBooster when the latest available version it shows is, in fact, already installed:

Screenshot 2024-01-06 102116
Screenshot 2024-01-06 102211
Screenshot 2024-01-06 102235

**Comment by TommyE123** [comment]
@stephengillie, @hexerus

I've submitted an additional PR to address this issue at https://github.com/microsoft/winget-pkgs/pull/132957.

My apologies for my oversight.

Tom

**Pull request merged**
