### PR TITLE
Add ElevationRequirement for Powershell 7.4.0.3

### PR DESCRIPTION
**Pull request by florelis**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/110448&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
> Manifest Error: Inconsistent value in the manifest. [PackageVersion] Value: 7.4.3.0

**Comment by mdanish-kh** [comment]
@stephengillie Similar case to https://github.com/microsoft/winget-pkgs/pull/99498#issuecomment-1478806439, https://github.com/microsoft/winget-pkgs/pull/99813. DisplayVersion for MSI is `7.4.0.3` and for MSIX it's `7.4.3.0`. Since marketing version is 7.4.0.3, we stuck with this as the PackageVersion but there's no way to have ARP entries for MSIX and pipelines aren't happy when PackageVersion is different from the version retrieved from MSIX. This probably requires a manual merge like previous PRs

**Comment by stephengillie** [comment]
> @stephengillie Similar case to [#99498 (comment)](https://github.com/microsoft/winget-pkgs/pull/99498#issuecomment-1478806439), #99813. DisplayVersion for MSI is `7.4.0.3` and for MSIX it's `7.4.3.0`. Since marketing version is 7.4.0.3, we stuck with this as the PackageVersion but there's no way to have ARP entries for MSIX and pipelines aren't happy when PackageVersion is different from the version retrieved from MSIX. This probably requires a manual merge like previous PRs

Thanks for the reminder. We should find a longer-term solution for this issue.

**Pull request merged**
