### PR TITLE
Update: Tencent.qq-devtool version 0.3.1

### PR DESCRIPTION
**Pull request by Trenly**
﻿

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/71174)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
@denelon - Blocking Issue
```
2022-08-20 07:26:16.821 [CLI ] Completed installer selection.
2022-08-20 07:26:16.857 [CLI ] Caught std::exception: No mapping for the Unicode character exists in the target multi-byte code page.
```
microsoft/winget-cli#2057

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Review by jedieaston — DISMISSED** [review]

**Review by ImJoakim — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
