### PR TITLE
Check for duplicate PRs

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
@denelon I have tried to create a workflow that detects duplicate PRs. If it finds that any PR opened is a duplicate,  `github-actions` will comment on the PR. ~I haven't tested it so if you can invite me as a collaborator temporarily, it will help me to test and make corrections in this workflow. I could have tested it but I'm not able to set up the same environment to test it.~

Edit: Finally, after a long research, I was able to test and it is working now.
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/29868)

### CODE REVIEW

**Comment by jedieaston** [comment]
Can you test it on your fork?

**Comment by vedantmgoyal2009** [comment]
Yes, you can see vedantmgoyal2009#7 and vedantmgoyal2009#8

**Comment by vedantmgoyal2009** [comment]
cc @denelon

**Comment by vedantmgoyal2009** [comment]
@Officialesco

**Comment by OfficialEsco** [comment]
This is out of my knowledge zone, you created this on a Saturday so you'll have to wait for MS Working hours so Denelon can assign someone who does from the MS team like the old YamlCreate updates

**Comment by vedantmgoyal2009** [comment]
@denelon JFYI, I have done some testing on the https://github.com/ItzLevvie/winget-pkgs-vedanttest repository and it works. However, I will wait for a review from the Microsoft team so that it won't create conflicts with existing duplicate detection work

**Comment by vedantmgoyal2009** [comment]
It has been days so any progress on this?

**Comment by denelon** [comment]
Last week was "Hackathon". I'll bring this up in today's discussion.

**Comment by vedantmgoyal2009** [comment]
@denelon Just wanted to know if this is ready to be merged.

**Comment by vedantmgoyal2009** [comment]
@denelon Any update on this? Does it still conflict with any other validation systems?

**Comment by denelon** [comment]
This is another case where I need to involve more of the team. We're down several resources for the holidays. I'll try to look at this the week after Thanksgiving holidays in the US.

**Comment by vedantmgoyal2009** [comment]
@denelon Any updates?

**Comment by denelon** [comment]
We've been doing some back-end refactoring work with the limited resources during the holidays. I'm hoping to have the team look at this when we get ramped back up in January. We haven't forgotten this, there are just a lot of things in flight. We have more high priority work items than engineers at this point. We're trying to balance bugs and features with how big the impact is for users.

**Comment by denelon** [comment]
@vedantmgoyal2009 I haven't forgotten about this. We're just concerned about having different chunks of logic and behavior in different places. Thank you for sharing where you did your testing :)

**Comment by denelon** [comment]
Unfortunately, that link doesn't work anymore. Do you have a current example?

**Comment by vedantmgoyal2009** [comment]
> @jedieaston Yes, you can see [vedantmgoyal2009#7](https://github.com/vedantmgoyal2009/winget-pkgs/pull/7) and [vedantmgoyal2009#8](https://github.com/vedantmgoyal2009/winget-pkgs/pull/8) where it finally succeed after lots of tries. If it finds all good to you, can I get an approval?

@denelon

**Comment by vedantmgoyal2009** [comment]
Because at that time, I was a new & fresh GitHub user, I didn't know much about how GitHub Actions work. I still remember the struggle🥲 how I had finally found a solution to change the environment variables permanently since I was using them as a condition for the next step i.e. commenting on the PR.

**Comment by vedantmgoyal2009** [comment]
@denelon ??

**Comment by denelon** [comment]
@vedantmgoyal2009 I'll talk with the team today. If we're not going to have a better solution in the next few days, I'll merge this in.

**Review by denelon — APPROVED** [review]

**Comment by vedantmgoyal2009** [comment]
🎉🎉🎉🎉

**Pull request merged**
