### PR TITLE
New version: FreeCiv.FreeCiv version 3.0.0

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/47679)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
Btw @ItzLevvie we have access to new logs via the Azure pipelines
https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=276974&view=results
Published/Artifacts -> [InstallationVerificationLogs](https://dev.azure.com/ms/ed6a5dfa-6e7f-413b-842c-8305dd9e89e6/_apis/build/builds/276974/artifacts?artifactName=InstallationVerificationLogs&api-version=7.0&%24format=zip) are probably the most interesting

**Comment by lechacon** [comment]
@OfficialEsco do you have a reason to use the mirror from sourceforge and not the one from freeciv.org? This doesn't really matter; just curiosity.

**Comment by OfficialEsco** [comment]
Its the URL which was used in the first PR https://github.com/microsoft/winget-pkgs/pull/1162
From a little snooping i believe its because the website is HTTP instead of HTTPS

Note for later https://github.com/freeciv/freeciv

**Pull request merged**
