### PR TITLE
Update GitKraken to v7.0.0

### PR DESCRIPTION
**Pull request by pivendren**
Update to latest version 7.0.0 with new exe hash.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/511)

### CODE REVIEW

**Comment by VIKTORVAV99** [comment]
You should submit a new manifest for a new version so users can install a specific version.

**Comment by pivendren** [comment]
> 
> 
> You should submit a new manifest for a new version so users can install a specific version.

@VIKTORVAV99 that would be cool but all the download links point to the exe of the latest version. Is there a suggested work around for this?

**Comment by VIKTORVAV99** [comment]
That's a tricky one, I'm worried that updating the manifest could break scripts that pin a specific version.

This probably isn't the case yet since winget is pretty new but I think submitting a new manifest might be the best way even if they point to the same end version.

**Comment by pivendren** [comment]
Yeah, it is a tricky one. I have another PR(#501) with the same situation where I asked these questions with possible solutions. Waiting on a reply from the reviewers for the best approach.

**Comment by VIKTORVAV99** [comment]
I just realized I commented the same thing on that one... Hehe...

But yeah let's wait for the reviewers.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
