### PR TITLE
Remove Whitespace from Mozilla.Firefox.ESR 102.12.0

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/113825&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
1. en-US-x64-wix - Pending
1. en-US-x86-wix - Pending
1. en-GB-x64-wix - Pending
1. en-GB-x86-wix - Pending
1. de-DE-x64-wix - Pending
1. de-DE-x86-wix - Pending
1. da-DK-x64-wix - Pending
1. da-DK-x86-wix - Pending
1. sv-SE-x64-wix - Pending
1. sv-SE-x86-wix - Pending
1. nb-NO-x64-wix - Pending
1. nb-NO-x86-wix - Pending
1. nn-NO-x64-wix - Pending
1. nn-NO-x86-wix - Pending
1. fi-FI-x64-wix - Pending
1. fi-FI-x86-wix - Pending
1. fr-FR-x64-wix - Pending
1. fr-FR-x86-wix - Pending
1. el-GR-x64-wix - Pending
1. el-GR-x86-wix - Pending
1. es-ES-x64-wix - Pending
1. es-ES-x86-wix - Pending
1. pt-PT-x64-wix - Pending
1. pt-PT-x86-wix - Pending
1. it-IT-x64-wix - Pending
1. it-IT-x86-wix - Pending
1. ja-JP-x64-wix - Pending
1. ja-JP-x86-wix - Pending
1. zh-TW-x64-wix - Pending
1. zh-TW-x86-wix - Pending
1. en-US-x64-exe - Pending
1. en-US-x86-exe - Pending
1. en-GB-x64-exe - Pending
1. en-GB-x86-exe - Pending
1. de-DE-x64-exe - Pending
1. de-DE-x86-exe - Pending
1. da-DK-x64-exe - Pending
1. da-DK-x86-exe - Pending
1. sv-SE-x64-exe - Pending
1. sv-SE-x86-exe - Pending
1. nb-NO-x64-exe - Pending
1. nb-NO-x86-exe - Pending
1. nn-NO-x64-exe - Pending
1. nn-NO-x86-exe - Pending
1. fi-FI-x64-exe - Pending
1. fi-FI-x86-exe - Pending
1. fr-FR-x64-exe - Pending
1. fr-FR-x86-exe - Pending
1. el-GR-x64-exe - Pending
1. el-GR-x86-exe - Pending
1. es-ES-x64-exe - Pending
1. es-ES-x86-exe - Pending
1. pt-PT-x64-exe - Pending
1. pt-PT-x86-exe - Pending
1. it-IT-x64-exe - Pending
1. it-IT-x86-exe - Pending
1. ja-JP-x64-exe - Pending
1. ja-JP-x86-exe - Pending
1. zh-TW-x64-exe - Pending
1. zh-TW-x86-exe - Pending

**Comment by stephengillie** [comment]
> Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/102.12.0esr/win64/fr/Firefox%20Setup%20102.12.0esr.msi. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-309-113825-20230810-1\6397fb89-4519-462e-ad9f-8de24ce6b5fd' because it is being used by another process..
Error information: 
Http Response: OK
Http Reason Phrase: OK
Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/102.12.0esr/win32/fr/Firefox%20Setup%20102.12.0esr.msi. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-309-113825-20230810-1\e64679ce-1b3c-473a-905c-1e7af45307fa' because it is being used by another process..
Error information: 
Http Response: OK
Http Reason Phrase: OK

**Pull request merged**
