### PR TITLE
New package: cedric.view2er version 1.0.0

### PR DESCRIPTION
**Pull request by ce-dric**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/171539)

### CODE REVIEW

**Comment by ce-dric** [comment]
@microsoft-github-policy-service agree

**Comment by ce-dric** [comment]
> @ce-dric please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-09-04 09:32:10.472 [FAIL] Installer failed security check. Url: https://github.com/ce-dric/pruebas-de-validacion/releases/download/1.0.0/installer.exe Result: 0x80004005

(Automated response - build 894.)

**Comment by ce-dric** [comment]
> Manual Validation ended with:
> 
> > 2024-09-04 09:32:10.472 [FAIL] Installer failed security check. Url: https://github.com/ce-dric/pruebas-de-validacion/releases/download/1.0.0/installer.exe Result: 0x80004005
> 
> (Automated response - build 894.)
> 
> Edit: With signature version 1.417.272.0: [cedric.view2er.x64.1.0.0.log](https://github.com/user-attachments/files/16874043/cedric.view2er.x64.1.0.0.log)

@stephengillie Thank you for your review. I followed the error message and found that `MS SmartScreen` does not have a certificate, so it seems to be a problem that is recognized as a malicious program. I made software with open source, and I wonder if I can upload it to the `winget` only when I purchase and apply the certificate for a fee.

**Comment by stephengillie** [comment]
Verify:
image
This is the About page. I couldn't find how to have the application display its version number, and the installer doesn't seem to write to the Registry.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
