### PR TITLE
chore: update git-age to version v0.1.11

### PR DESCRIPTION
**Pull request by prskr**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/143957)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\prskr.git-age__DefaultSource\git-age.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\git-age.exe returned exit code: 1

(Automated response - build 870.)

**Comment by prskr** [comment]
Originally the binary was detected as virus. After submitting the binary to the Windows Defender team it is now whitelisted and installation should be possible

**Comment by prskr** [comment]
Could you probably re-queue the pipeline please to see whether it is still detected? I tested the installation this morning on an up-to-date Windows 11 with latest Defender definitions and it was working

**Comment by stephengillie** [comment]
Hi @prskr,

This package passed the Defender scans in the validation pipeline. This label is because it had an exit code of `1`.

**Review by stephengillie — APPROVED** [review]

**Comment by prskr** [comment]
@stephengillie sorry my bad I overlooked the exit code 🙈 

Actually from a program perspective that's correct because the user is supposed to use a sub-command or `--help` 😅  is there any option to pass args to your validation or should I 'fix' this in the program to always exit 0 even though nothing was done?

**Comment by stephengillie** [comment]
Unfortunately, this is a known issue with the validation pipeline.

**Pull request merged**
