### PR TITLE
New version: Jackett.Jackett version 0.21.2476

### PR DESCRIPTION
**Pull request by ilike2burnthing**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/151140)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @ilike2burnthing,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 877.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-04-25 23:19:06.826 [FAIL] Installer failed security check. Url: https://github.com/Jackett/Jackett/releases/download/v0.21.2476/Jackett.Installer.Windows.exe Result: 0x80004005

(Automated response - build 877.)

**Comment by ilike2burnthing** [comment]
Again, no issue here.

**Comment by ilike2burnthing** [comment]
@stephengillie not sure if you were supposed to be unassigned, but a review is required. Thanks!

**Review by ImJoakim — APPROVED** [review]

**Pull request merged**
