### PR TITLE
Added Unity 2021.1.6f1 version 2021.1.7f1.

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

------

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/12901)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Welp, seems like i broke your automation by adding the real PackageName D: I'll fix it when this gets submitted

**Comment by denelon** [comment]
@OfficialEsco sometimes I wish the code would do what we want instead of "EXACTLY" what we told it to do.

**Comment by OfficialEsco** [comment]
> @OfficialEsco sometimes I wish the code would do what we want instead of "EXACTLY" what we told it to do.

Weeeeell, i think this is more about what @jedieaston told his script to do instead of the new things i want his script to do 🙄
Since a few programs have their PackageName like "AppName Version (Architecture)" you guys over at the WinGet team probably have a workaround for this anyways 😄

**Comment by denelon** [comment]
We are working through challenges with matching PackageName and what is registered in ARP. We support multiple architectures in the same manifest now. I'm hoping to see consolidation for PackageIdentifiers not to include architecture. We recently went through this exercise with Visual Studio Code. They are back down to one for stable and one for insider. Both architectures, and User vs. Machine are availabe via a single manifest.

**Comment by OfficialEsco** [comment]
> We are working through challenges with matching PackageName and what is registered in ARP. We support multiple architectures in the same manifest now. I'm hoping to see consolidation for PackageIdentifiers not to include architecture. We recently went through this exercise with Visual Studio Code. They are back down to one for stable and one for insider. Both architectures, and User vs. Machine are availabe via a single manifest.

Its the ARP which includes Version and Architecture i mean btw, which is why i tested this manifest as `PackageName: Unity 2021.1.6f1`
image
VC++ require Architecture tho, but you have Firefox which has `Firefox 88.0 (x64) en-US` as ARP

**Comment by denelon** [comment]
With unity, we probably should stick with the package name excluding the version. We do some normalization work to try to ignore versions and architectures. With the VC++ libraries, a user might want multiple architectures installed on their machine, so those are likely instances where they are different packages that should include the architecture in the name.

**Comment by jedieaston** [comment]
Shoot, I didn't even see that. Sorry @OfficialEsco! I'm going to add an additional argument to take care of this, and I need to remember to look at the PR as well.

**Pull request merged**
