### PR TITLE
Add Netease Cloud Music

### PR DESCRIPTION
**Pull request by xdrl1**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/622)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
Try as I might, I have not been able to uninstall this app.  Please evaluate.

**Comment by mauriceluo69** [comment]
> Try as I might, I have not been able to uninstall this app. Please evaluate.

Hello, @KevinLaMS !

Thank you for your effort!

When closing this application, it may minimized to tray by default. 
image

If you want to uninstall it, please right click the icon, then select the last one in the menu, which means *exit*. 
image

After that, you can easily uninstall it successfully in control panel by click this button, which means *Yes*
image

I will update this PR, adding the homepage as @KiruyaMomochi suggests.

**Comment by KiruyaMomochi** [comment]
However adding the homepage will make u stuck at SmartScreen. ¯\_(ツ)_/¯
So maybe you can remove the homepage field, at least for now.

**Comment by mauriceluo69** [comment]
> However adding the homepage will make you stuck at SmartScreen.
> `¯\_(ツ)_/¯`
> So maybe you can remove the homepage field, at least for now.

Yes, that's true. I have updated a new version without homepage field.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
