### PR TITLE
Cisco.PacketTracer version 8.1.1.0022

### PR DESCRIPTION
**Pull request by AlexDev404**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/62899)

### CODE REVIEW

**Comment by AlexDev404** [comment]
@ItzLevvie

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Only ISV domains are allowed i.e. cisco.com and netacad.com

Cisco provides official download URLs but you will need to contact them to see if they can make the download links public without needing an account.

**Comment by AlexDev404** [comment]
> 

Ok sure no problem. I will get right on it. 

Thanks so much for making me aware of this.

**Comment by AlexDev404** [comment]
@ItzLevvie 
I have a question I want to ask you Levvie,

It's concerning my contributions towards **winget** but I feel as though it would be off-topic to post it here.
Where can I ask you this? Would [issues](https://github.com/microsoft/winget-pkgs/issues) be a suitable place to ask?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> Where can I ask you this? Would [issues](https://github.com/microsoft/winget-pkgs/issues) be a suitable place to ask?

If it's an issue about a particular package then ask in https://github.com/microsoft/winget-pkgs/issues.

If it's an inquiry then probably ask in https://github.com/microsoft/winget-pkgs/discussions?

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
You can set this pull request to DRAFT.

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Comment by ItzLevvie** [comment]
[Policy] Area-External

**Pull request closed without merging**
