### PR TITLE
Microsoft.powershell.preview 7.4.0.6

### PR DESCRIPTION
**Pull request by anamnavi**
This PR includes a msix file for arm/arm64 installers as a temporary solution until we create msi for arm.

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/122076)

### CODE REVIEW

**Review by mdanish-kh — APPROVED** [review]

**Comment by mdanish-kh** [comment]
[Policy] reset feedback
[Policy] Needs-Manual-Merge
[Policy] Needs-Attention

**Review by mdanish-kh — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Review by mdanish-kh — APPROVED** [review]

**Comment by mdanish-kh** [comment]
@stephengillie - Looks like this needs a waiver or a manual merge

**Comment by anamnavi** [comment]
@stephengillie could we please get a manual merge on this, we have community members asking for this. Appreciate it highly!

**Comment by stephengillie** [comment]
> stephengillie could we please get a manual merge on this, we have community members asking for this. Appreciate it highly!

Sorry for missing this over the weekend.

**Pull request merged**
