### PR TITLE
New version: Perforce.P4V version 259.1061

### LINKED ISSUE #154802: [Update Request]: Perforce.P4V
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Perforce.P4V

### Package Version

259.1061

### Please describe the changes you would like to see

New release available on Perforce webpage. There is a link for newest version (MSI) https://www.perforce.com/downloads/perforce/r24.1/bin.ntx64/p4vinst64.msi
Latest package version on winget is: 234.255.8838
Thank you!

### PR DESCRIPTION
**Pull request by schembriaiden**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.2.1 :rocket:

Resolves: https://github.com/microsoft/winget-pkgs/issues/154802
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/154803)

### CODE REVIEW

**Comment by grzmot2** [comment]
Oh no, error :/

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-05-23 00:49:51.385 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x64 with version 14.38.33135.0

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Hi @vikingnope,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-23 12:33:15.561 [FAIL] Installer failed security check. Url: https://github.com/Cretezy/lazyjj/releases/download/v0.1.1/lazyjj-v0.1.1-x86_64-pc-windows-msvc.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Should this be reopened?

**Comment by vikingnope** [comment]
Oh yes oops thanks for letting me know

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-05-29 00:49:50.758 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x64 with version 14.38.33135.0

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Hi @vikingnope,

This manifest adds Apps and Features entries that aren't present in previous PR versions. These entries should be added to the previous versions, or removed from this version.

(Automated response - build 882.)

**Comment by vikingnope** [comment]
Verified manually:

image

**Comment by stephengillie** [comment]
The screenshot doesn't contain the issue.

**Comment by hymerman** [comment]
FYI I added a new PR to upgrade this package to latest - apologies if that's not the right process for this repo given that this current PR exists! It just seemed nice and easy to update the manifest with YamlCreate.ps1, which is what I used to upload a version of this package recently.

https://github.com/microsoft/winget-pkgs/pull/157425

**Pull request closed without merging**
