### PR TITLE
Adding manifest files for SSMS 20.2

### PR DESCRIPTION
**Pull request by Matteo-T**
New set of YAML file to allow users to download SSMS 20.2, which was just released.

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/162149)

### CODE REVIEW

**Comment by Matteo-T** [comment]
Note to self: see how the validation reacts to the use of `https://go.microsoft.com/fwlink/...` instead of `https://download.microsoft.com/download/...`.

Last time we had some issue due to the redirections, IIRC... but maybe this time around it won't be a problem.

**Comment by stephengillie** [comment]
HI @Matteo-T,

Have some of the installers been updated? 

> Specified hash doesn't match.
Actual hash:   12DD3B24330AD074DBB71F28AD06EAAA9757BD5C9A750ADD5088C4DB54A7D4F6
Expected hash: d90b59f92dfdb6cf9ac2a8730dc323af156acfe075ab4d1e37a7b51c96ed5ddf
Specified hash doesn't match.
Actual hash:   12DD3B24330AD074DBB71F28AD06EAAA9757BD5C9A750ADD5088C4DB54A7D4F6
Expected hash: a7d24a0b81959dd6b6e015fe11f628c8b014527c7852bba09c208a82157c23da
Specified hash doesn't match.
Actual hash:   12DD3B24330AD074DBB71F28AD06EAAA9757BD5C9A750ADD5088C4DB54A7D4F6
Expected hash: 32b61f4e661e19b66b094bd473c018cc99eda15d353fbd748232fe293425be01
Specified hash doesn't match.
Actual hash:   12DD3B24330AD074DBB71F28AD06EAAA9757BD5C9A750ADD5088C4DB54A7D4F6
Expected hash: 063f52cb37fef908f5b46c8ec02c51ed490ef1f92f5569b0193525e4d8d7f111
Specified hash doesn't match.
Actual hash:   12DD3B24330AD074DBB71F28AD06EAAA9757BD5C9A750ADD5088C4DB54A7D4F6
Expected hash: 423e813c5f14e4f548b07c5a27a78a37d70d883ce987850590397b8c7a461a24
Specified hash doesn't match.
Actual hash:   12DD3B24330AD074DBB71F28AD06EAAA9757BD5C9A750ADD5088C4DB54A7D4F6
Expected hash: 16accd406ca42bc24c75aa827e552364fcbb47375706513061857957733b607d
Specified hash doesn't match.
Actual hash:   12DD3B24330AD074DBB71F28AD06EAAA9757BD5C9A750ADD5088C4DB54A7D4F6
Expected hash: 8132e17e2903095ee79405098de48d5755ef1d5e86b028424846793bcc76a868
Specified hash doesn't match.
Actual hash:   12DD3B24330AD074DBB71F28AD06EAAA9757BD5C9A750ADD5088C4DB54A7D4F6
Expected hash: feb57edf77310793daa275d2a161e6306ef94a4ed80b568e49247953d1d0ccd5
Specified hash doesn't match.
Actual hash:   12DD3B24330AD074DBB71F28AD06EAAA9757BD5C9A750ADD5088C4DB54A7D4F6
Expected hash: 05f27c102488ca7bcff7f3a224c16f54b0d5b61815d3f36aa41afd643084d660
Specified hash doesn't match.
Actual hash:   12DD3B24330AD074DBB71F28AD06EAAA9757BD5C9A750ADD5088C4DB54A7D4F6
Expected hash: babdfbaf6319c58c2c6506fdfbdcaf165603c7ce2b60565c8a7330bdcd3c1bb3

**Comment by Matteo-T** [comment]
Let me take a look and see what is going on.

**Comment by Matteo-T** [comment]
Oops... there'the Insaller URL did not come out right. Fixing it...

**Comment by Matteo-T** [comment]
@stephengillie, I fixed the links. We should be good... let's see how it goes this time around.

**Comment by Matteo-T** [comment]
Hi @stephengillie, I cannot reallymake sense of the failures. When I click on Details, I only see: "0 error / 0 warnings" and "0 error / 8 warnings". Not sure why the system is rejecting the PR... Any suggestions or insights on what I should be looking at?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 886.)

**Comment by Matteo-T** [comment]
Hey @stephengillie, is there anything I should try to change on my end to make this thing work? I am a bit clueless, though, since my changes are pretty much the same stuff I've made in the past... just different hashes and such... very odd..

**Comment by stephengillie** [comment]
Hi @Matteo-T,

This pipeline issue is normally ephemeral.
- https://github.com/microsoft/winget-pkgs/discussions/155218

I've been reluctant to manually validate this package, since it has so many `InstallerUrl`s, but if it hasn't passed by tomorrow morning I'll do so. For future versions, I'm not sure of the best way to expedite, but hopefully there will be less of the "sporadic demand" that impacted us last week.

**Comment by stephengillie** [comment]
Hi @,

Do you approve of these changes?

(Automated response - build 886.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
