### PR TITLE
Microsoft.VisualStudioCode.Insiders_v1.92.0 desktop

### PR DESCRIPTION
**Pull request by lszomoru**
Microsoft.VisualStudioCode.Insiders_v1.92.0
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161729)

### CODE REVIEW

**Review by ImJoakim — APPROVED** [review]

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Comment by IllusionMH** [comment]
@lszomoru looks like linked build (`82104a3...`) is affected by https://github.com/microsoft/vscode/issues/220999
After removing installed version and installing VS Code insiders again using winget I still see same problem.

Is it possible to update this package with latest version that is not affected by update issue?
I'd submit PR, but I cannot find official hashes (`"sha256hash": "Not Provided"`)

P.S. Initially submitted similar comment but in wrong PR (CLI) - I'm sorry for second notification.

**Pull request merged**
