### PR TITLE
Tyrrrz.DiscordChatExporter.GUI Version 2.40

### PR DESCRIPTION
**Pull request by CanePlayz**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/111230&drop=dogfoodAlpha

### CODE REVIEW

**Comment by CanePlayz** [comment]
Messed up the branch here, will fix later

**Comment by CoolPlayLin** [comment]
image
The action that you change two manifests at the same time in a PR hasn't been allowed

**Comment by CanePlayz** [comment]
Well, this will start working as soon as #111229 gets merged anyways, so we'll just wait that out.

**Comment by CanePlayz** [comment]
Someone just needs to restart the checks

**Comment by stephengillie** [comment]
Hi @CanePlayz,

This PR appears to modify an unrelated package:
image

Could you revert the other package's change, and/or move it to another branch?

**Comment by CanePlayz** [comment]
> Hi @CanePlayz,
> 
> This PR appears to modify an unrelated package: image
> 
> Could you revert the other package's change, and/or move it to another branch?

Yup, will do so. I thought it'd work now since the other changed that I accidentally made on this branch were merged with another PR by now.

**Comment by CanePlayz** [comment]
Where does this need author feedback?

**Comment by stephengillie** [comment]
> Where does this need author feedback?

Unfortunately, this PR still modifies the `IceCreamApps` package.

**Comment by CanePlayz** [comment]
> > Where does this need author feedback?
> 
> Unfortunately, this PR still modifies the `IceCreamApps` package. 

But the result's gonna be the same. Since the PR has been merged, de facto nothing with that package will change. But if it's really necessary, I'll try to clone and rebase.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
