### PR TITLE
New package: Libjxl.Libjxl version 0.10.2

### LINKED ISSUE #151383: [Package Request]: libjxl
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/libjxl/libjxl/releases
Publisher: libjxl
Package Name: libjxl
Description: JPEG XL reference implementation.
Package Version: 0.10.2
Installer URL: https://github.com/libjxl/libjxl/releases/tag/v0.10.2

### PR DESCRIPTION
**Pull request by schembriaiden**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

Resolves: https://github.com/microsoft/winget-pkgs/issues/151383

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/151388)

### CODE REVIEW

**Review by sidy3d — CHANGES_REQUESTED** [review]
`NestedInstallerFiles` should reference the following executables:
* `cjxl`
* `djxl`
* `cjpegli`
* `djpegli`

**Review by sidy3d — CHANGES_REQUESTED** [review]
Remove the reference to `brotli.exe`.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335141
> 2024-04-29 09:20:03.118 [CLI ] Unable to locate nested installer at: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Libjxl.Libjxl.0.10.2\extracted\cjxl.exe
> 2024-04-29 16:19:39.700 [CLI ] Unable to locate nested installer at: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Libjxl.Libjxl.0.10.2\extracted\cjxl.exe

(Automated response - build 877.)

**Comment by Trenly** [comment]
[Policy] Zip binary

**Pull request closed without merging**
