### PR TITLE
Resubmit VRCFaceTracking, version 5.1.1.0

### PR DESCRIPTION
**Pull request by babo4d**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

Previously removed in #104265 due to bad URL.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/124934)

### CODE REVIEW

**Comment by babo4d** [comment]
@microsoft-github-policy-service agree

**Comment by babo4d** [comment]
Yes I believe so. @benaclejames should answer that.

**Comment by babo4d** [comment]
Confirmed with author that this is expected behavior.

**Comment by stephengillie** [comment]
> Confirmed with author that this is expected behavior.

Apologies, I meant for this to become included with the next set of merges.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
