### PR TITLE
[Agreements] Add back WHTA.Tamara

### PR DESCRIPTION
**Pull request by mdanish-kh**
cc @denelon @stephengillie

Installer prompt:

image

image

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://github.com/tekniskakustik/tamara/releases/download/v2023.0.8.4/installer.exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 769)

**Comment by stephengillie** [comment]
Their Releases only shows `2023.0.8.9`. 

- https://github.com/tekniskakustik/tamara/releases/tag/v2023.0.8.9

**Comment by mdanish-kh** [comment]
Looks like the release got deleted, ill push the new version

**Comment by mdanish-kh** [comment]
> Their Releases only shows `2023.0.8.9`.
> 
>     * [tekniskakustik/tamara@`v2023.0.8.9` (release)](https://github.com/tekniskakustik/tamara/releases/tag/v2023.0.8.9)
> 
> 
> Also, the license is for Matlab, not really this product.

The application installs the MATLAB runtime as part of the installation. I believe this is a case where the application requires the user to accept a 3rd party license. If you run the installer manually (screenshot attached above), you'll be shown a prompt to accept the MATLAB license.

**Comment by lars-whta** [comment]
This release was pulled, and this PR is not sanctioned.

**Comment by mdanish-kh** [comment]
We were going through all the packages that got removed and this was one of them. I wasn't aware of the context around it

cc @stephengillie - can we add this package to Auth.csv check with a strictness of `must`?

**Pull request closed without merging**
