### PR TITLE
Added Citrix.Workspace version 21.7.0.44

### PR DESCRIPTION
**Pull request by ImJoakim**
image

```
PS C:\Users\Test\Downloads> winget install -m "M:\Git\winget-pkgs\manifests\c\Citrix\Workspace\21.7.0.44"
Found Citrix Workspace [Citrix.Workspace]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://downloadplugins.citrix.com/ReceiverUpdates/Prod/Receiver/Win/CitrixWorkspaceApp21.7.0.44.exe
  ██████████████████████████████   145 MB /  145 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23656)

### CODE REVIEW

**Comment by ImJoakim** [comment]
Oof

**Review by OfficialEsco — APPROVED** [review]
Can confirm everything works
image

cc @denelon @jamespik

**Review by OfficialEsco — APPROVED** [review]
@palenshus

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
Hmm
```
winget list

Name                                     Id                                          Version             Available  Source
--------------------------------------------------------------------------------------------------------------------------
Citrix Workspace 2105                    CitrixOnlinePluginPackWeb                21.5.0.48
```

**Pull request merged**
