### PR TITLE
Update package: Tillitis.TkeySign version 1.0.0

### PR DESCRIPTION
**Pull request by dehanj**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/149503)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Installer https://github.com/tillitis/tkey-sign-cli/releases/download/v1.0.0/tkey-sign_1.0.0_Windows_amd64.zip
 Scan request id: '6ef92f53-055b-44d1-bb9d-7551cd0e4a1e'
 Error information: BlockingDetectionFound
 Installer https://github.com/tillitis/tkey-sign-cli/releases/download/v1.0.0/tkey-sign_1.0.0_Windows_arm64.zip
 Scan request id: '61439819-0703-4027-9caf-66a9c8e2a78d'
 
 4/16/2024 10:01:10 PM
 
 ****************************************************************************************
 Installer Validation

(Automated response - build 876.)

**Comment by stephengillie** [comment]
This might be due to a network block of data centers, to prevent automated downloads.

(Automated response - build 876.)

**Comment by dehanj** [comment]
@stephengillie Is there something I should do?

**Comment by stephengillie** [comment]
@dehanj,

Sorry for the delayed reply. This is apparently a network block by the host, and they'd have to unblock our data centers from downloading the software package.

**Comment by dehanj** [comment]
@stephengillie Sorry to bother again, but is there some way to get this moving?
Can we trigger a retry? Our other PRs have worked fine and they are at least from the same provider (even if I have no idea about their data centers).

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Tillitis.TKeySign__DefaultSource\tkey-sign.exe returned exit code: 2
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\tkey-sign.exe returned exit code: 2

(Automated response - build 895.)

**Pull request merged**
