### PR TITLE
JP-Minerals VESTA 3.5.8

### PR DESCRIPTION
**Pull request by superusercode**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/97234)

### CODE REVIEW

**Comment by Trenly** [comment]
> 2023-02-19 12:34:48.141 [CLI ] Archive malware scan failed

cc @denelon - Local archive scan still enabled in pipelines

**Comment by denelon** [comment]
Checking.

**Comment by denelon** [comment]
It's in PPE, we're doing additional validation for this and the work to honor "prohibitsElevation" before we roll it out to PROD.

**Comment by stephengillie** [comment]
Hi @superusercode,

The installer did not complete. From the log:
> 2023-03-15 12:53:13.549 [CLI ] Symlink target does not match ARP Entry. Expected:  Actual: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\JP-Minerals.VESTA__DefaultSource\VESTA-win64\VESTA.exe
> 2023-03-15 12:53:13.549 [CLI ] Portable file has been modified: C:\Users\User\AppData\Local\Microsoft\WinGet\Links\vesta.exe
> 2023-03-15 12:53:13.549 [CLI ] Terminating context: 0x8a150057 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\PortableFlow.cpp:112

**Comment by stephengillie** [comment]
Closing as No Recent Activity.

**Pull request closed without merging**
