### PR TITLE
New version: Timthreetwelve.WUView version 0.5.21.0

### PR DESCRIPTION
**Pull request by Timthreetwelve**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/120208)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Timthreetwelve,

This package has a dependency on `Microsoft.DotNet.DesktopRuntime.6`:
image

Clicking "Yes" opens a browser:
image

**Comment by Timthreetwelve** [comment]
I really don't understand why this was blocked and what I'm supposed to do. This package has always required .NET to be installed. Previous versions of this package (0.5.16, 0.5.17, 0.5.20) were all approved, and they had the same requirement that .NET 6 was installed. Furthermore, the GitHub page and the installer itself state that requirement.

My question is why would anyone try to install it on a machine that doesn't have .NET?

So, PLEASE tell me what I need to do.

Tim

**Comment by stephengillie** [comment]
Hi @Timthreetwelve,

> So, PLEASE tell me what I need to do.

Unfortunately, I'm not really sure how to fix this - I'm inexperienced with C# and spend most of my time in PowerShell. 
The package is asking for the dependency even when the dependency is already installed. I'm not sure why - is there a warning or check for .NET in the application code? 

> My question is why would anyone try to install it on a machine that doesn't have .NET?

Windows 10 (and 11?) doesn't come with every single .NET runtime and framework installed. I'm guessing this is because there are dozens of frameworks, each having several architectures and often parallel versions, meaning hundreds of packages that could take up SSD space. And these extra frameworks and runtimes might not have been approved by corporate auditors, lawyers, or security teams.

**Comment by Timthreetwelve** [comment]
@stephengille approved the request for version 0.5.17 on August 7, 2023. @Trenly approved the request for version 0.5.20 on August 23, 2023.  Has the policy changed since then? If not, why are you choosing to enforce it today when you didn't previously?

I ask again, what can I do to fix this?

**Comment by Trenly** [comment]
@stephengillie - I don't believe this is an interactive only installer; It does install just fine without the dependency;

Granted, it has the runtime dependency, but it does install without the dependency

```
--> Installing WinGet
--> Disabling safety warning when running installer
Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.

--> Configuring Winget
Enabled admin setting 'LocalManifestFiles'.
Enabled admin setting 'LocalArchiveMalwareScanOverride'.


--> Installing the Manifest 0.5.21.0

Found Windows Update Viewer [Timthreetwelve.WUView] Version 0.5.21.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/Timthreetwelve/WUView/releases/download/v0.5.21/WindowsUpdateViewer_0.5.21.0_Setup.exe
  ██████████████████████████████  4.24 MB / 4.24 MB
Successfully verified installer hash
Starting package install...
Successfully installed

--> Refreshing environment variables

--> Comparing ARP Entries

DisplayName                    DisplayVersion Publisher   ProductCode                                Scope
-----------                    -------------- ---------   -----------                                -----
Windows Update Viewer 0.5.21.0 0.5.21.0       Tim Kennedy {3A152885-8378-4FDE-AFCC-85D096B16A1D}_is1 User
```

This likely was previously approved because it installed just fine and nobody ever bothered to try running it after the install

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
@Timthreetwelve,

Sorry for the delay in processing your PR.

**Pull request merged**
