### PR TITLE
New version: MartiCliment.UniGetUI.Pre-Release version 3.1.2-beta4

### PR DESCRIPTION
**Pull request by marticliment**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/183630)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @marticliment,

Does this package require `VCRedist` as a dependency? 
image

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Comment by marticliment** [comment]
@stephengillie, isn't winget supposed to install VCRedist it if I declare it as a dependency?
image

**Comment by stephengillie** [comment]
It is. It might be an artifact of the scan step, when all EXEs are launched. But that should be after the dependency installation. I'm not sure what happened to cause the error.

**Pull request merged**
