### PR TITLE
New version: anchor.cli 0.0.23-wingettest2

### PR DESCRIPTION
**Pull request by benburkert**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/149543)

### CODE REVIEW

**Comment by benburkert** [comment]
@microsoft-github-policy-service agree [company="Anchor Security, Inc."]

**Comment by benburkert** [comment]
@microsoft-github-policy-service agree company="Anchor Security, Inc."

**Comment by amerine** [comment]
@benburkert @stephengillie Can we close this? I'm fixing the PackageIdentifier via automation and this will be replaced with a new PR.

**Comment by amerine** [comment]
#149561 is the new PR

**Pull request closed without merging**
