### PR TITLE
New version: Huawei.HuaweiMobileCloud version 11.2.6.300

### PR DESCRIPTION
**Pull request by SpecterShell**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/120570)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @SpecterShell,

This package doesn't seem to modify the system. Is that expected?

**Comment by SpecterShell** [comment]
It works for me. 🤔
image

**Comment by stephengillie** [comment]
After validation, the package doesn't appear to be installed:
image

**Comment by SpecterShell** [comment]
You may have to use another query:
image

**Comment by stephengillie** [comment]
Sorry but it's just not installed:
image

**Comment by stephengillie** [comment]
Manually installing shows that the `x86` version only runs on 32-bit OSes: 
image

**Comment by stephengillie** [comment]
@SpecterShell,

Sorry for the difficulty. Normally `x86` works fine on 64-bit OSes. Here, the `x64` installs and launches normally on a 64-bit OS.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
