### PR TITLE
New package Corel.MindManager v 23.1.243

### PR DESCRIPTION
**Pull request by FaserF**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

This is another try of the old PR https://github.com/microsoft/winget-pkgs/pull/138829 where only the PackageDependencies failed.
There is a newer version 23.2.209 available, but only for the MSI installer, not the exe installer yet.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/153816)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @FaserF,

This `PackageUrl` led to a different `InstallerUrl`: https://dwnld.mindmanager.com/stubs/Release/MindManager23/MindManager23_setup.exe

- Should this be used instead of the current `InstallerUrl`s?
- Where were the current `InstallerUrl`s found?

**Comment by FaserF** [comment]
> Hi @FaserF,
> 
> This `PackageUrl` led to a different `InstallerUrl`: https://dwnld.mindmanager.com/stubs/Release/MindManager23/MindManager23_setup.exe
> 
> * Should this be used instead of the current `InstallerUrl`s?
> * Where were the current `InstallerUrl`s found?

No, this packageurl installerurl should not be used, since this is another setup with no deployment methods. 
The installer URLs have been taken from here: https://www.mindmanager.com/mm-win-enterprise-admin-64

Those are the "enterprise" deployment installers.

**Comment by stephengillie** [comment]
> The installer URLs have been taken from here: https://www.mindmanager.com/mm-win-enterprise-admin-64
> 
> Those are the "enterprise" deployment installers.

Thanks - that link appears to be one of the installers, as it immediately starts downloading, instead of loading a webpage.

**Comment by FaserF** [comment]
Docs are here: https://download.mindjet.com/Help/MindManager_Reader_Large_Scale_Deployment_Guide.pdf

I had found the link public here: https://ideas.patchmypc.com/ideas/PATCHMYPC-I-715
And my company uses this software in the paid version, there we also got the same download link for MSI from the manufacturer.

**Comment by FaserF** [comment]
I would like to bump this one :)

**Comment by stephengillie** [comment]
Thanks for your patience - having a bit of a backlog.

Verify:
image
Main window is bigger than VM screen.
image

**Review by stephengillie — APPROVED** [review]

**Comment by FaserF** [comment]
> Thanks for your patience - having a bit of a backlog.
> 

No worries! I really appreciate all of your work! It's really something great and useful and I appreciate your help when issues occur from my packages!

**Pull request merged**
