### PR TITLE
New version: Elgato.WaveLink version 1.9.3.1962

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141152)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978334967 2024-02-27 10:32:25.178 [CLI ] ShellExecute installer failed: 3010 CAQuietExec:  Error 0x80070001: Command line returned an error. CAQuietExec:  Error 0x80070001: QuietExec Failed CAQuietExec:  Error 0x80070001: Failed in ExecCommon method CustomAction ClearFirewall returned actual error code 1603 but will be translated to success due to continue marking Property(S): DRIVERINSTALLFAILED_MESSAGE = Driver installation failed. Please reboot and start setup again. Property(S): DRIVERINSTALLFAILED_AUTO_MESSAGE = Driver installation failed. Please reboot and Setup will be started again. Property(S): ErrorDialog = ErrorDlg Property(S): SecureCustomProperties = DELETE_APPDATA_FILES_ACCEPTED_VALUE;DRIVERINSTALLFAILED_AUTO_MESSAGE;DRIVERINSTALLFAILED_MESSAGE;EXE_FILE_NAME;INSTALLDIR_PRODUCT_FAKE;INSTALLER_FILE_NAME;IS_DRIVER_UP_TO_DATE;IS_ELGATO_WAVE_DEVICE_CONNECTED;KEEP_SETTINGS_ALERT_MESSAGE;NETFRAMEWORK45;NEW_FIRMWARE_VERSION;OLD_COMP_PATH;OLDER_VERSION_DELETING_REGISTRY_APPDATA_ON_UPGRADE;OLDER_VERSION_WITH_ELGATO_PLUGINS;OLDERVERSIONBEINGUPGRADED;UNPLUG_MESSAGE;USAGE_STATISTICS_ACCEPTED_VALUE;WIN10FOUND;WIX_DOWNGRADE_DETECTED;WIX_UPGRADE_DETECTED;WIXUI_INSTALLDIR

(Automated response - build 832.)

**Comment by OfficialEsco** [comment]
Works on my VM
```
Enter a pull request number: 141152

Manifest validation succeeded.
Found Elgato Wave Link [Elgato.WaveLink] Version 1.9.3.1962
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://edge.elgato.com/egc/windows/wavelink/1.9.3/WaveLink_1.9.3.1962_x64.msi
  ██████████████████████████████   128 MB /  128 MB
Successfully verified installer hash
Starting package install...
Restart your PC to finish installation.

Name          : Elgato Wave Link
Publisher     : Corsair Memory, Inc.
Version       : 1.9.3.1962
ProductCode   : {9F9BB1FC-41D2-427D-ADAE-7B235073C6AF}
Registry Path : Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{9F9BB1FC-41D2-427D-ADAE-7B235073C6AF}
Uninstall     : winget uninstall --id "{9F9BB1FC-41D2-427D-ADAE-7B235073C6AF}"

Press any key to continue . . .
```

Hopefully another run irons it out

**Comment by stephengillie** [comment]
Manual Validation ended with:
> MSI (s) (80:54) [11:52:13:489]: Product: Elgato Wave Link -- Installation completed successfully.  MSI (s) (80:54) [11:52:13:490]: Windows Installer installed the product. Product Name: Elgato Wave Link. Product Version: 1.9.3.1962. Product Language: 1033. Manufacturer: Corsair Memory, Inc.. Installation success or error status: 0.  MSI (s) (80:54) [11:52:13:490]: Windows Installer requires a system restart. Product Name: Elgato Wave Link. Product Version: 1.9.3.1962. Product Language: 1033. Manufacturer: Corsair Memory, Inc.. Type of System Restart: 2. Reason for Restart: 2.  MSI (s) (80:54) [11:52:13:492]: Product: Elgato Wave Link. Restart required. The installation or update for the product required a restart for all changes to take effect.  The restart was deferred to a later time. 

(Automated response - build 832.)

**Comment by stephengillie** [comment]
I'll add a waiver, but I feel like an `ExpectedReturnCode` or similar could be added to handle this better.

**Comment by OfficialEsco** [comment]
The InstallerType is Wix tho, so it should be handled by WinGet-CLI?
Also the exit code you got is 0 = Success? o_O

**Comment by stephengillie** [comment]
> The InstallerType is Wix tho, so it should be handled by WinGet-CLI? 

I'm not well-informed on this topic. 

> Also the exit code you got is 0 = Success? o_O

Yes `3010` often means "Install successful but reboot reqiured". Should it be added to this manifest as an `InstallerSuccessCode` or similar?

**Comment by OfficialEsco** [comment]
Ohh you were referring to the automated exit code, according to my PR-Test script it Winget-CLI does recognize 3010 as a soft reboot code, so i'm not sure why the automation is complaining about it.
From my POV no as this should be handled in the backend. @denelon ? =)

**Comment by denelon** [comment]
MSI 3010 is ERROR_SUCCESS_REBOOT_REQUIRED and validation shouldn't block on that condition.

We could logically map all of those to the Expected return code internally.

WinGet CLI does the right thing here. Let's check if something changed with engineering @stephengillie

**Comment by stephengillie** [comment]
I did reach out to the team, some time ago, but haven't heard a response.

**Comment by stephengillie** [comment]
> I'll add a waiver
...equivalent.

**Comment by stephengillie** [comment]
Hi @OfficialEsco,

This manifest removes Apps and Features entries that are present in previous PR versions. These entries should be added to this version, to maintain version matching, and prevent the 'upgrade always available' situation with this package.

(Automated response - build 881.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
