### PR TITLE
Added Tableau version 21.4.1356.

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

------

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/37994)

### CODE REVIEW

**Review by OfficialEsco — COMMENTED** [review]
```
Enter a pull request number: 37994

Manifest validation succeeded.
Found Tableau [Tableau.Desktop] Version 21.4.1356
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://downloads.tableau.com/tssoftware/TableauDesktop-64bit-2021-4-1.exe
  ██████████████████████████████   668 MB /  668 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 65535
Installer log is available at: C:\Users\User\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Tableau.Desktop.21.4.1356-2021-12-16-20-33-29.919.log
```
With and without Administrator

**Comment by jedieaston** [comment]
Working for me inside a Sandbox and a VM:

image

Can you post that log?

**Comment by OfficialEsco** [comment]
[WinGet-2021-12-16-20-59-38.213.log](https://github.com/microsoft/winget-pkgs/files/7730092/WinGet-2021-12-16-20-59-38.213.log)
[WinGet-Tableau.Desktop.21.4.1356-2021-12-16-20-59-59.493.log](https://github.com/microsoft/winget-pkgs/files/7730094/WinGet-Tableau.Desktop.21.4.1356-2021-12-16-20-59-59.493.log)

Oh i think this is a me issue
```
[0E94:08A4][2021-12-16T21:00:04]e000: Error 0xffffffff: A CPU that supports SSE4.2 and POPCNT is needed to run Tableau.  If you are using a VM, make sure Processor compatibility mode is off.  CPU check return code: -1
[0E94:08A4][2021-12-16T21:00:04]e000: Error 0xffffffff: Failed to initialize data in bootstrapper application.
```

**Review by ItzLevvie — APPROVED** [review]
image
image

**Comment by OfficialEsco** [comment]
Found the issue... It appears a Windows update re-"enabled" Hyper-V... Which made my Virtualbox VM super unstable since
```
DISM /Online /Disable-Feature:Microsoft-Hyper-V

Disable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-Hypervisor

bcdedit /set hypervisorlaunchtype off
```
I don't understand how Hyper-V can be active when its not even enabled anywhere..

**Pull request merged**
