### PR TITLE
New package: VapourSynth.VapourSynth version R54

### PR DESCRIPTION
**Pull request by SpecterShell**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/25670)

### CODE REVIEW

**Comment by SpecterShell** [comment]
Only if the dependencies are missing, or VapourSynth and Python are installed in different scopes, the installer will show a messagebox. Maybe the validation process doesn't install dependencies first?

**Comment by ItzLevvie** [comment]
image

At the moment, WinGet will ignore the dependencies listed in the package because the code for it isn't implemented in the client (winget-cli). It currently doesn't know what the dependencies are and how to those dependencies.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/25670#issuecomment-903255033

**Comment by SpecterShell** [comment]
Emm... So I have to wait for this part to be implemented and then this manifest would get passed?

**Pull request closed without merging**
