### PR TITLE
New package: Azul.Zulu.8.JRE version 8.40.0.25

### PR DESCRIPTION
**Pull request by russellbanks**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/68823)

### CODE REVIEW

**Comment by Trenly** [comment]
@denelon - Do we need to revert the YamlCreate change? I could have sworn that 1.2 manifests were allowed in validation previously, as long as they weren’t portable type

**Comment by denelon** [comment]
I am pretty sure we made the change to block schema 1.2 after that older PR was merged. We're publishing to a REST source and the 1.2 schema isn't completed for https://github.com/microsoft/winget-cli-restsource yet. We do have someone working on that currently. As soon as 1.3 is rolled out to > half the userbase, we'll turn on validation for 1.2 and portable packages. I'm sorry I missed that on the other PR for YamlCreate 🙇‍♂️

**Comment by russellbanks** [comment]
Do you expect it to be long until 1.3 is rolled out to > half the userbase? Should I hold off PRs until then or revert the yamlcreate change locally?

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
> Do you expect it to be long until 1.3 is rolled out to > half the userbase? Should I hold off PRs until then or revert the yamlcreate change locally?
> 
> Edit: shouldn't the 1.2 validation be turned on anyway, even if it is early because wingetcreate has also been updated for 1.2 schema now.

It will probably be wednesday

**Comment by Trenly** [comment]
> Do you expect it to be long until 1.3 is rolled out to > half the userbase? 

I think it was estimated for mid next week?

>Should I hold off PRs until then or revert the yamlcreate change locally?
> 
When using YamlCreate, before selecting “y” to submit PR’s you can open the files and make changes to them manually. I would suggest opening the files and changing the manifest version to 1.1.0, and then hitting ‘y’ to submit

> Edit: shouldn't the 1.2 validation be turned on anyway, even if it is early because wingetcreate has also been updated for 1.2 schema now.
>
Thats a call for MSFT to make. It will take a little while for users of wingetcreate to receive the updates, and you can always install an older version of wingetcreate (or just not update)

**Pull request merged**
