### PR TITLE
New package: Microsoft.AppInstaller.PreRelease version 1.24.2507.0

### LINKED ISSUE #183597: [Package Request]: Microsoft.AppInstaller Development / Release Candidate Builds
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

I would like to have a package for the preview / release candidate / development builds of winget.  
However I'm not sure whether Release Candidates, Development Builds and Preview builds should be split up into different packages or should be all together in one package (and what would be the correct package identifier for this case).  
Can winget even upgrade itself to an unstable version?

**Download Page Url:** https://github.com/microsoft/winget-cli/releases/tag/v1.9.2507
**Publisher:**  Microsoft Corporation
**Package Name:**  App Installer ReleaseCandidate / Development
**Description:** Microsoft App Installer for Windows 10 makes sideloading Windows 10 apps easy: Just double-click the app package, and you won't have to run PowerShell to install apps. App Installer presents the package information like app name, publisher, version, display logo, and the capabilities requested by the app. Get right into the app, no hassles--and if installation doesn't work, the error messages were designed to help you fix the problem. Windows Package Manager is supported through App Installer starting on Windows 10 1809. This application is currently only available for desktop PCs.
**Package Version:** 1.9.2507
**Installer Url:** (x86, x64, arm, arm64)  https://github.com/microsoft/winget-cli/releases/download/v1.9.2507/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #183597

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/183879)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334972
> 2024-10-17 09:01:42.703 [CORE] Deployment operation #2: Windows cannot install package Microsoft.DesktopAppInstaller_1.24.2507.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.33728.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00.UWPDesktop" currently installed are: {Microsoft.VCLibs.140.00.UWPDesktop_14.0.29231.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00.UWPDesktop_14.0.30704.0_x64__8wekyb3d8bbwe}
> 2024-10-17 09:01:42.703 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!00007FFF67673F75: (caller: 00007FFF675CA720) Exception(2) tid(13e0) 80073CF3 Package failed updates, dependency or conflict validation.
> 2024-10-17 09:01:44.575 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFF67672D2F: (caller: 00007FFF6767432C) Exception(3) tid(13e0) 80073CF1 Package was not found.
> 2024-10-17 09:01:44.578 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(126)\WindowsPackageManager.dll!00007FFF677E8931: (caller: 00007FFF67675853) LogHr(2) tid(13e0) 80073CF1 Package was not found.
>     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFF67672D2F: (caller: 00007FFF6767432C) Exception(3) tid(13e0) 80073CF1 Package was not found.
> 2024-10-17 09:01:44.585 [CLI ] MSIX installer failed: 2147958003
> 2024-10-17 08:52:36.287 [CORE] Deployment operation #2: Windows cannot install package Microsoft.DesktopAppInstaller_1.24.2507.0_x86__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x86 processor architecture and minimum version 14.0.33728.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00.UWPDesktop" currently installed are: {Microsoft.VCLibs.140.00.UWPDesktop_14.0.30704.0_x86__8wekyb3d8bbwe}
> 2024-10-17 08:52:36.287 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!55B8E94A: (caller: 55AF97A7) Exception(2) tid(1c80) 80073CF3 Package failed updates, dependency or conflict validation.
> 2024-10-17 08:52:37.267 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!55B8D7AF: (caller: 55B8ED72) Exception(3) tid(1c80) 80073CF1 Package was not found.
> 2024-10-17 08:52:37.267 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(126)\WindowsPackageManager.dll!55B8EA29: (caller: 55B8FBF8) LogHr(2) tid(1c80) 80073CF1 Package was not found.
>     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!55B8D7AF: (caller: 55B8ED72) Exception(3) tid(1c80) 80073CF1 Package was not found.
> 2024-10-17 08:52:37.271 [CLI ] MSIX installer failed: 2147958003

Automated error analysis suggests -1978334972 may mean This package has a dependency missing from your system.

Automated error analysis suggests 2147958003 may mean Error Installing Dependency - Windows cannot install this package because it depends on a framework (version) that could not be found.

(Automated response - build 897.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334972
> 2024-10-17 09:57:23.244 [CORE] Deployment operation #4: Windows cannot install package Microsoft.DesktopAppInstaller_1.24.2507.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.33728.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00.UWPDesktop" currently installed are: {Microsoft.VCLibs.140.00.UWPDesktop_14.0.29231.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00.UWPDesktop_14.0.30704.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00.UWPDesktop_14.0.33321.0_x64__8wekyb3d8bbwe}
> 2024-10-17 09:57:23.245 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!00007FF902FD3F75: (caller: 00007FF902F2A720) Exception(2) tid(10b8) 80073CF3 Package failed updates, dependency or conflict validation.
> 2024-10-17 09:57:24.759 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FF902FD2D2F: (caller: 00007FF902FD432C) Exception(3) tid(10b8) 80073CF1 Package was not found.
> 2024-10-17 09:57:24.761 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(126)\WindowsPackageManager.dll!00007FF903148931: (caller: 00007FF902FD5853) LogHr(2) tid(10b8) 80073CF1 Package was not found.
>     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FF902FD2D2F: (caller: 00007FF902FD432C) Exception(3) tid(10b8) 80073CF1 Package was not found.
> 2024-10-17 09:57:24.780 [CLI ] MSIX installer failed: 2147958003
> 2024-10-17 09:52:59.545 [CORE] Deployment operation #4: Windows cannot install package Microsoft.DesktopAppInstaller_1.24.2507.0_x86__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x86 processor architecture and minimum version 14.0.33728.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00.UWPDesktop" currently installed are: {Microsoft.VCLibs.140.00.UWPDesktop_14.0.30704.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00.UWPDesktop_14.0.33321.0_x86__8wekyb3d8bbwe}
> 2024-10-17 09:52:59.546 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!5071E94A: (caller: 506897A7) Exception(2) tid(9b8) 80073CF3 Package failed updates, dependency or conflict validation.
> 2024-10-17 09:53:00.489 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!5071D7AF: (caller: 5071ED72) Exception(3) tid(9b8) 80073CF1 Package was not found.
> 2024-10-17 09:53:00.489 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(126)\WindowsPackageManager.dll!5071EA29: (caller: 5071FBF8) LogHr(2) tid(9b8) 80073CF1 Package was not found.
>     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!5071D7AF: (caller: 5071ED72) Exception(3) tid(9b8) 80073CF1 Package was not found.
> 2024-10-17 09:53:00.495 [CLI ] MSIX installer failed: 2147958003

Automated error analysis suggests -1978334972 may mean This package has a dependency missing from your system.

Automated error analysis suggests 2147958003 may mean Error Installing Dependency - Windows cannot install this package because it depends on a framework (version) that could not be found.

(Automated response - build 897.)

**Comment by Dragon1573** [comment]
> [!CAUTION]
>
> This package requires `Microsoft.VCLibs.Desktop.14 [>=14.0.33728.0]`, which is currently unavailable from the repository. It should be submitted to the repo before this package can be accepted.

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-10-21 18:38:36.033 [FAIL] WindowsPackageManager.dll!00007FFF4EA2CC5D: LogHr(1) tid(23b8) 800704C7 The operation was canceled by the user.

(Automated response - build 897.)

**Comment by Dragon1573** [comment]
> Edit: I ran it twice to be sure. The same error showed up both times. I didn't cancel the install so I'm not sure why the error says that I did.

Maybe the installation quit by itself automatically but response as if a user canceled it? 😕

**Review by ItzLevvie — APPROVED** [review]

**Comment by denelon** [comment]
We're not going to include Pre-Release versions of App Installer in the community repository. WinGet doesn't have support for channels. This would result in false-positive scenarios where a user with a stable version could end up being upgraded to a preview version.

**Comment by Dragon1573** [comment]
> [!CAUTION]
>
> Close with reason: **Product Manager instructed**.
>
> - This PR may cause unexpected behavior.

**Pull request closed without merging**
