### PR TITLE
New version: Figma.Figma version 124.3.1

### PR DESCRIPTION
**Pull request by aisgbnok**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/166668)

### CODE REVIEW

**Comment by stephengillie** [comment]
I may have approved the other PR too hastily. This PR adds more details. Feel free to submit these as an update and I'll approve.

**Comment by stephengillie** [comment]
Close with reason: Duplicate of #166681;

**Comment by aisgbnok** [comment]
@stephengillie, do you review in reverse chronological order? My scripts ensure they don't open duplicate PRs, and if they do I make sure to close them. But honestly, it's not a big deal I understand you review hundreds of these a day alone.

I have rebased this PR into:

- https://github.com/microsoft/winget-pkgs/pull/166739

Thank you.

**Comment by stephengillie** [comment]
> It seems you sometimes review in reverse chronological order, which is reasonable given the oldest PRs can be stuck in limbo. For future reference, my scripts ensure I don't open duplicate PRs.

This is due to GitHub's default search order. My automation loads `Page 1` of a search query, which defaults to newest first. This should be reversed, so oldest PR is processed first, and I believe I just need to add a sort term to my search query to achieve this.

**Pull request closed without merging**
