### PR TITLE
ARP: Microsoft.GitCredentialManagerforWindows

### PR DESCRIPTION
**Pull request by ghost**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/17018)

### CODE REVIEW

**Comment by ItzLevvie** [comment]
cc @denelon manual merge please? It seems like other PRs had this issue too: https://github.com/microsoft/winget-pkgs/pull/12998, https://github.com/microsoft/winget-pkgs/pull/12999, https://github.com/microsoft/winget-pkgs/pull/13000, https://github.com/microsoft/winget-pkgs/pull/13002.

**Comment by ItzLevvie** [comment]
a

**Comment by ItzLevvie2** [comment]
test

**Comment by denelon** [comment]
Any idea why we're getting unattended failure? I'll run the pipelines again.

**Comment by denelon** [comment]
I saw a comment on one of them that requires admin for install. Could that be what's happening?

**Comment by ItzLevvie** [comment]
No idea. It installed fine for me when I ran it through Windows Terminal Preview with Administrator privileges.

**Comment by denelon** [comment]
I'm about 99% sure we run our testing as administrator, so I've asked an engineer to take a look.

**Comment by denelon** [comment]
@ItzLevvie, you're going to LOVE this. Git is a dependency, and this package launches an interactive install for "Git".

**Comment by ItzLevvie** [comment]
Ah, so that's why it installed fine for me because I had Git preinstalled on my virtual machine.

**Comment by ItzLevvie2** [comment]
a

**Pull request closed without merging**
