### PR TITLE
New version: Nushell.Nushell version 0.90.1

### PR DESCRIPTION
**Pull request by fdncred**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/138220)

### CODE REVIEW

**Comment by fdncred** [comment]
Can y'all re-run this? I ran the SandboxTest.ps1 on my Windows 11 box and it worked without issues. I'm not sure what else to check.

**Comment by fdncred** [comment]
An hour later it fails again. @stephengillie any idea what's going on here and why it works when I run the SandboxTest.ps1 locally but takes an hour and fails here?

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
> Any word on what finally happened? i.e. what were the failures about? why it finally worked? or was it just manually allowed to proceed despite failures?

The `Internal-Error-Dynamic-Scan` label only indicates an issue with the pipeline, and doesn't give any feedback about the application. But this error means Validation is far enough along that I can manually complete the process. Sorry for any concern caused.

**Pull request merged**
