### PR TITLE
New version: Microsoft.ADKPEAddon version 10.1.25398.1

### LINKED ISSUE #132974: [Update Request]:  Microsoft ADK Windows PE Addon
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

Microsoft.ADKPEAddon

### Package Version

10.1.22621.1

### Please describe the changes you would like to see

I am afraid this package does not comply with the naming convention of other packages.
Windows Assessment and Deployment Kit >  Microsoft.WindowsADK
Windows Assessment and Deployment Kit Windows PE Addon > Microsoft.ADKPEAddon

kindly request to change the ID to Microsoft.**Windows**ADKPEAddon.

thank you very much, hope the reasons is clear.

### PR DESCRIPTION
**Pull request by rasa**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135256)

- Resolve: #132974

### CODE REVIEW

**Comment by rasa** [comment]
It's missing a `ProductCode` value. Komac didn't add it. How do I determine this value, without installing it first?

**Comment by Exorcism0666** [comment]
@rasa can you link this issue: #132974, like this in your post:
```
- Resolve: #132974 
```

**Comment by rasa** [comment]
> @rasa can you link this issue: #132974, like this in your post:
> 
> ```
> - Resolve: #132974 
> ```

Sorry, but didn't you link it in your post? I'm not sure what else I need to do.

**Comment by Exorcism0666** [comment]
Example:
image

**Comment by rasa** [comment]
- Resolve: #132974

**Comment by Exorcism0666** [comment]
@rasa Not like this, you need to modify your main message and put the modification necessary

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
