### PR TITLE
Update Zoom.Zoom 5.17.31859

### PR DESCRIPTION
**Pull request by JohnMcPMS**
Similar to #137505 , move to the existing version format.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137509)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-01T18:09:55.1700795Z ##[error] Manifest Error: DisplayVersion declared in the manifest has overlap with existing DisplayVersion range in the index. Existing DisplayVersion range in index:  [ [5.17.5 (31030), 5.17.31030]]

(Automated response - build 694.)

**Comment by JohnMcPMS** [comment]
> Automatic Validation ended with:
> 
> > 2024-02-01T18:09:55.1700795Z ##[error] Manifest Error: DisplayVersion declared in the manifest has overlap with existing DisplayVersion range in the index. Existing DisplayVersion range in index:  [ [5.17.5 (31030), 5.17.31030]]
> 
> (Automated response - build 694.)

Expected, needs a rerun once #137505 is merged.

**Review by Trenly — APPROVED** [review]

**Pull request merged**
