### PR TITLE
[Portable] New Package: Kubernetes.kubectl 1.24.2

### PR DESCRIPTION
**Pull request by Trenly**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/68808)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Comment by russellbanks** [comment]
This is licened under the Apache License 2.0

https://github.com/kubernetes/kubectl/blob/master/LICENSE

**Review by russellbanks — CHANGES_REQUESTED** [review]
This is missing the x86 and arm64 installer

x64: https://dl.k8s.io/v1.24.2/bin/windows/amd64/kubectl.exe
x86: https://dl.k8s.io/v1.24.2/bin/windows/386/kubectl.exe
arm64: https://dl.k8s.io/v1.24.2/bin/windows/arm64/kubectl.exe

It's also licensed under Apache License 2.0
https://github.com/kubernetes/kubectl/blob/master/LICENSE

This is the same with #68809

(See #69105)

**Review by russellbanks — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
Bump

**Pull request merged**
