### PR TITLE
New version: Jackett.Jackett version 0.21.2458

### PR DESCRIPTION
**Pull request by ilike2burnthing**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150916)

### CODE REVIEW

**Review by ImJoakim — APPROVED** [review]

**Comment by ilike2burnthing** [comment]
As per always, there's no issue with Jackett.

**Comment by stephengillie** [comment]
Hi @ilike2burnthing,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 877.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-04-24 23:23:21.747 [FAIL] Installer failed security check. Url: https://github.com/Jackett/Jackett/releases/download/v0.21.2458/Jackett.Installer.Windows.exe Result: 0x80004005

(Automated response - build 877.)

**Pull request merged**
