### PR TITLE
whipinto 0.3.1

### PR DESCRIPTION
**Pull request by Yin-ZP**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132032)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 11:03:27 AM: 
> 2023-12-29 11:03:25.695 [FAIL] Installer failed security check. Url: https://github.com/binbat/live777/releases/download/v0.3.1/whipinto-v0.3.1-x86_64-pc-windows-msvc.exe Result: 0x80004005

(Automated response - build 489.)

**Comment by Yin-ZP** [comment]
> Hi @Yin-ZP,
> 
> The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.
> 
> (Automated response - build 509.)

Is this a suspicion that a virus exists in the program？

**Comment by stephengillie** [comment]
> Is this a suspicion that a virus exists in the program？

There was a concern, but it has passed.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
