### PR TITLE
Remove version: Ablaze.Floorp.Lightning version 11.5.0

### PR DESCRIPTION
**Pull request by Hibi-10000**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

Floorp Lightning is no longer offered.

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136647)

### CODE REVIEW

**Comment by Hibi-10000** [comment]
- #133371

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-26T12:48:29.1602713Z ##[error] One or more errors occurred. (The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.) The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.

(Automated response - build 661.)

**Comment by stephengillie** [comment]
Hi @Hibi-10000,

This PR modifies more than 1 manifest version. We have a limit of 1 manifest version update per PR.
image

Could one of these 2 manifests be moved to another PR. That would allow both PRs to be processed.

**Comment by stephengillie** [comment]
URL: https://github.com/Floorp-Projects/Floorp/releases/download/v11.5.0-lightning/floorp-win64.installer.exe 
Response status code does not indicate success: 401 (Unauthorized).

(Automated message - build 661)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
