### PR TITLE
New version: DuckStudio.ChineseGit version v2.4

### LINKED ISSUE #156167: [Package Request]: Chinese Git v2.4
### How can we help?

None

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/DuckDuckStudio/Chinese_git/releases/
Publisher:`鸭鸭「カモ」`
Package Name:`中文Git`
Description:`一个使用中文命令操作 Git 的简单工具，旨在使不熟悉英文的用户更轻松地使用 Git。`
Package Version:`2.4`
Installer URL: https://github.com/DuckDuckStudio/Chinese_git/releases/download/v2.4/Chinese_git_Setup_v2.4.exe

### PR DESCRIPTION
**Pull request by DuckDuckStudio**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #156167

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
```
[Powered by 虚空终端] PS D:\...\winget-pkgs> winget validate --manifest D:\...\winget-pkgs\manifests\d\DuckStudio\ChineseGit\2.4
清单验证成功。
```
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

Link issue: #156167
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/156168)

### CODE REVIEW

**Comment by DuckDuckStudio** [comment]
@microsoft-github-policy-service agree [company="{Duck Studio}"]

**Comment by DuckDuckStudio** [comment]
@microsoft-github-policy-service agree

**Comment by DuckDuckStudio** [comment]
Emm...The program is ready to use once it's unzip.
Is it necessary to have an installation program?

**Comment by Dragon1573** [comment]
> Is it necessary to have an installation program?

It'd better provide an install wizard instead of just release the loose executable.

## Reason

When there's an `InstallerType: zip` package, `winget.exe` will extract the ZIP archive to a specific directory (here called `A`) and create a symbolic link (here is `B/main.exe` in another directory (here called `B`) only for files you specified in `NestedInstallerFiles.[*].RelativeFilePath` (here use `main.exe` as an example).

Directory `B` will be added to `$env:PATH` environment parameter. If you launch `main.exe`, its working directory will be `B` instead of `A`, and no resources could be found relative to directory `B`.

`winget.exe` can't handle such kind of packages at the moment. See microsoft/winget-cli#2711 for more details.

## Solution

Create an install wizard for the package. The wizard will handle DLLs or other resources instead of `winget.exe`.

**Comment by DuckDuckStudio** [comment]
Because the repository that submitted this pull request has been deleted, I will create a new PR.

**Pull request closed without merging**
