### PR TITLE
New version: AMSSoftware.PassportPhotoMaker version 9.41

### PR DESCRIPTION
**Pull request by mbilal234**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/138231)

### CODE REVIEW

**Comment by mbilal234** [comment]
The URL for download is the same; however the same installer (given on previous version) now installs version 9.41; hence, the PR

**Comment by stephengillie** [comment]
Hi @mbilal234,

> This PR's version number 9.41 has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 9.2.5, which has 3 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 706)

**Comment by stephengillie** [comment]
> The URL for download is the same; however the same installer (given on previous version) now installs version 9.41; hence, the PR

Hi @mbilal234,

We call this a "vanity URL" and this is common. Thanks for submitting a new manifest for the new version. Could you remove the old manifest also?

**Comment by mbilal234** [comment]
> Hi @mbilal234,
> 
> > This PR's version number 9.41 has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 9.2.5, which has 3 parameters.
> 
> Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)
> 
> (Automated response - build 706)

Here's an attached screenshot from the latest version downloaded:

image

**Comment by mbilal234** [comment]
> > The URL for download is the same; however the same installer (given on previous version) now installs version 9.41; hence, the PR
> 
> Hi @mbilal234,
> 
> We call this a "vanity URL" and this is common. Thanks for submitting a new manifest for the new version. Could you remove the old manifest also?

Sure, i'll do that

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
