### PR TITLE
add msix package for powershell 7.3.1 installer manifest

### PR DESCRIPTION
**Pull request by anamnavi**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

### CODE REVIEW

**Comment by mdanish-kh** [comment]
@anamnavi Shouldn't the PackageVersion be `7.3.1.0` to match `Version` field in Registry?

**Comment by anamnavi** [comment]
> @anamnavi Shouldn't the PackageVersion be `7.3.1.0` to match `Version` field in Registry?

Where/which line number of which file do you see that at?

**Comment by mdanish-kh** [comment]
> Where/which line number of which file do you see that at?

Not strictly related to the changes brought in by this PR, but I'm referring to the two recent PRs created for [Microsoft.PowerShell](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/PowerShell) whose PackageVersion fields do not match the Registry/Control Panel. https://github.com/microsoft/winget-pkgs/blob/c257c22617b3f236582cabeea17742d2879de9cb/manifests/m/Microsoft/PowerShell/7.2.8/Microsoft.PowerShell.installer.yaml#L5

https://github.com/microsoft/winget-pkgs/blob/c257c22617b3f236582cabeea17742d2879de9cb/manifests/m/Microsoft/PowerShell/7.3.1/Microsoft.PowerShell.installer.yaml#L5

This is a recent change as previous manifests have been submitted with correct DisplayVersion i.e., PackageVersion matches Registry so just wanted to confirm whether this was intentional or something that requires fixing.

**Comment by mdanish-kh** [comment]
@anamnavi Only one manifest can be modified per PR — You can change `7.3.1` here and create a separate PR for `7.2.8`

**Comment by anamnavi** [comment]
@mdanish-kh I see. I'll do that one at a time then, thanks

**Review by Trenly — APPROVED** [review]

**Pull request merged**
