### PR TITLE
New package: CedricLouvrier.Pingo version 1.17.5

### PR DESCRIPTION
**Pull request by BiosPlus**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/138278)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @BiosPlus,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 708.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-07 10:46:30.537 [FAIL] Installer failed security check. Url: https://css-ig.net/bin/pingo-win64.zip Result: 0x80004005

(Automated response - build 708.)

**Comment by BiosPlus** [comment]
Fair enough, interestingly virustotal hasn't picked up anything for either the [zip](https://www.virustotal.com/gui/file/a797b17b0c76e6c3a06e70d612f3c142512ce1550a065ce0a990173a325f283f) or [exe](https://www.virustotal.com/gui/file/338a68399b4c7f2e18fdaae876a560dfc3d422e5b8f056abd58006854b63036f) files included

**Comment by ye4241** [comment]
I have tried to use CloudFlare Workers to solve this issue. Please refer: #170538 and #170540 .

**Pull request closed without merging**
