### PR TITLE
Added Minecraft Launcher version 1.0.0.0.

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/4124)

### CODE REVIEW

**Comment by kb-1000** [comment]
https://github.com/microsoft/winget-pkgs/pull/2902#issuecomment-669287422
https://github.com/microsoft/winget-pkgs/pull/1544#issue-427349985

**Comment by josh-hemphill** [comment]
Using the PC Launcher linked as it is now always complains that the user should be using the MS Store launcher, but that is not reachable from winget for some reason...

**Comment by jedieaston** [comment]
Apps that rely on Xbox stuff (i.e. Gamepass, Live, etc) aren’t available via the msstore source. I’ve been meaning to open a ticket about that…

**Comment by jedieaston** [comment]
Issue created: https://github.com/microsoft/winget-cli/issues/1833

**Pull request merged**
