### PR TITLE
New version: RussellBanks.Komac version 2.3.0

### PR DESCRIPTION
**Pull request by schembriaiden**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/159610)

### CODE REVIEW

**Comment by vikingnope** [comment]
@stephengillie, tried this in a Windows Sandbox and it worked fine

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 886.)

**Comment by vikingnope** [comment]
@stephengillie, maybe try doing it again?

**Comment by stephengillie** [comment]
It's a relic from when I had waiver permissions. (I'm on an extended test of a reduced permissions set.)

**Comment by stephengillie** [comment]
Hi @russellbanks,

Do you approve of these changes?

(Automated response - build 886.)

**Review by russellbanks — CHANGES_REQUESTED** [review]
x86 builds were removed in 2.3.0 so the entries will need to be manually removed here.

**Review by russellbanks — APPROVED** [review]

**Pull request merged**
