### PR TITLE
New version: DimisAIO.DindeGDPS version 2024.03.05.0

### LINKED ISSUE #142645: [Update Request]: DindeGDPS Launcher
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

DimisAIO.DindeGDPS

### Package Version

2024.03.05.0

### Please describe the changes you would like to see

I updated DindeGDPS from 2024.01.26.0 (previous) to 2024.01.26.0 (now)

Download link still is https://cdn-dinde.141412.xyz/DindeGDPS.exe

### PR DESCRIPTION
**Pull request by Exorcism0666**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.1.1 :rocket:

- Resolves #142645

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/142674)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Review by stephengillie — APPROVED** [review]

**Comment by Exorcism0666** [comment]
@stephengillie ^

**Comment by Exorcism0666** [comment]
@trenly

**Comment by Trenly** [comment]
* https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
