### PR TITLE
Update Microsoft.Skype.installer.yaml 8.109: Add `DisplayVersion`

### PR DESCRIPTION
**Pull request by treysis**
Add 'DisplayVersion' to match ARP entry.

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/128781)

### CODE REVIEW

**Review by mdanish-kh — CHANGES_REQUESTED** [review]
Adding DisplayVersion to a manifest means we need to go back and add to every other manifest of this package (to avoid infinite upgrade issues)

`8.109` should be made the PackageVersion, and DisplayVersion should be removed.

With the above change, you would also have to rename the version folder to match the new PackageVersion. The folder under `manifests/m/Microsoft/Skype` should be renamed from `8.109.0.209` -> `8.109`

A quick and easy way to do this would be here in GitHub Web by pressing the <kbd>.</kbd> (dot) key on your keyboard that'll open up the PR in VS Code Online. Navigate to Explorer menu, find the required folder and make the appropriate rename changes.

After that, stage and commit your changes from Source Control menu on the left. (The changes are automatically pushed)

**Comment by treysis** [comment]
> Adding DisplayVersion to a manifest means we need to go back and add to every other manifest of this package (to avoid infinite upgrade issues)

Ehm, but that is the problem we have NOW. How would the DisplayVersion cause an upgrade loop as well?

**Comment by mdanish-kh** [comment]
> Ehm, but that is the problem we have NOW.

That would be fixed by my suggestion by putting `8.109` under the PackageVersion field. By doing that the installed version will be properly correlated with the available version here in the repo, and WinGet won't try to offer you an upgrade.

> How would the DisplayVersion cause an upgrade loop as well?

That's related to issue 
- https://github.com/microsoft/winget-cli/issues/2503

**Comment by treysis** [comment]
> That's related to issue

Thanks for pointing this out. Actually, upon further inspection, the older Skype versions also just have the shorter version number as `PackageVersion`.

**Review by mdanish-kh — COMMENTED** [review]
PackageVersion should be modified in all 3 `.yaml` files, and also the version folder needs to be renamed as per review comment above

**Review by mdanish-kh — APPROVED** [review]

**Pull request merged**
