### PR TITLE
Moving CrystalDewWorld.CrystalDiskMark.TsukumoTokka v8.0.2

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/18493)

### CODE REVIEW

**Comment by KaranKad** [comment]
Can you try renaming `PackageIdentifier` to `CrystalDewWorld.CrystalDiskMark.TsukumoTokkaEdition` so that it's consistent with other versions. When I submitted this application before as `CrystalDewWorld.CrystalDiskMarkTsukumoTokkaEdition` it was too large and winget validation was throwing error. But submitting it like this `CrystalDewWorld.CrystalDiskMark.TsukumoTokkaEdition` might work.

**Comment by OfficialEsco** [comment]
> Can you try renaming `PackageIdentifier` to `CrystalDewWorld.CrystalDiskMark.TsukumoTokkaEdition` so that it's consistent with other versions. When I submitted this application before as `CrystalDewWorld.CrystalDiskMarkTsukumoTokkaEdition` it was too large and winget validation was throwing error. But submitting it like this `CrystalDewWorld.CrystalDiskMark.TsukumoTokkaEdition` might work.

Ye sure, however ain't near a PC for the next 2 hours so it gotta wait unless you wanna take over

**Review by jedieaston — APPROVED** [review]

**Comment by OfficialEsco** [comment]
@jedieaston >:o

**Comment by KaranKad** [comment]
@OfficialEsco I'll do it.

**Pull request merged**
