### PR TITLE
New version: shirowanisan.COEIROINK.GPU version 2.3.4

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/138657)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335141 2024-02-10 08:39:57.997 [CORE] DeliveryOptimization error: 0x80190190, extended error: 0x00000000 2024-02-10 08:39:58.077 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFE6553A465: (caller: 00007FFE6553AD01) Exception(1) tid(e00) 80190190 Bad request (400).

(Automated response - build 720.)

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 731.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-12 20:07:38.108 [FAIL] Installer failed security check. Url: https://github.com/OpenGMK/GM8Decompiler/releases/download/v2.2.0/gm8decompiler-v2.2.0-x86_64-pc-windows-msvc.zip Result: 0x80004005 MSI (s) (10:88) [20:07:26:708]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.38.33135. Product Version: 14.38.33135. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (10:98) [20:07:27:879]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Additional Runtime - 14.38.33135. Product Version: 14.38.33135. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [13A0:04CC][2024-02-12T20:07:24]w363: Could not create system restore point, error: 0x80070422. Continuing... 2024-02-12 18:55:05.191 [FAIL] Installer failed security check. Url: https://github.com/OpenGMK/GM8Decompiler/releases/download/v2.2.0/gm8decompiler-v2.2.0-i686-pc-windows-msvc.zip Result: 0x80004005 MSI (s) (0C:8C) [18:54:51:109]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (0C:FC) [18:54:52:280]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Additional Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [19C8:19C0][2024-02-12T18:54:48]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 731.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335141 2024-02-13 10:33:54.272 [CORE] DeliveryOptimization error: 0x80190190, extended error: 0x00000000 2024-02-13 10:33:54.273 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFFFB4FA465: (caller: 00007FFFFB4FAD01) Exception(1) tid(1470) 80190190 Bad request (400).

(Automated response - build 734.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 1:38:25 PM: 
> 2024-02-13 13:26:16.562 [CLI ] Failed to download, waiting a bit and retry. Url: https://www.dropbox.com/scl/fi/4bn8b5bq6ojrdnvceh2tk/COEIROINK_WIN_GPU_v.2.3.4.zip?rlkey=sc4ocz1ypd422wgu7y5jg62tt&dl=1 1:38:25 PM: 
> 2024-02-13 13:26:30.137 [CORE] DeliveryOptimization error: 0x80190190, extended error: 0x00000000 1:38:25 PM: 
> 2024-02-13 13:26:30.137 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFE872B9F7B: (caller: 00007FFE872BA79F) Exception(3) tid(1ff0) 80190190 Bad request (400). 1:38:25 PM: 
> 2024-02-13 13:38:24.770 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(185)\WindowsPackageManager.dll!00007FFE872B37C9: (caller: 00007FFE872B5769) Exception(4) tid(1ff0) 80072EE2     Msg:[InternetReadFile() failed.] 1:38:25 PM: 
> 2024-02-13 13:38:24.796 [CLI ] Caught wil::ResultException: C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(185)\WindowsPackageManager.dll!00007FFE872B37C9: (caller: 00007FFE872B5769) Exception(4) tid(1ff0) 80072EE2     Msg:[InternetReadFile() failed.]

(Automated response - build 735.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335141 2024-02-13 14:10:44.511 [CORE] DeliveryOptimization error: 0x80190190, extended error: 0x00000000 2024-02-13 14:10:44.561 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFEAD01A465: (caller: 00007FFEAD01AD01) Exception(1) tid(1c88) 80190190 Bad request (400).

(Automated response - build 745.)

**Comment by stephengillie** [comment]
> Manual Validation ended with:
> 
> > 1:38:25 PM:
> > 2024-02-13 13:26:16.562 [CLI ] Failed to download, waiting a bit and retry. Url: https://www.dropbox.com/scl/fi/4bn8b5bq6ojrdnvceh2tk/COEIROINK_WIN_GPU_v.2.3.4.zip?rlkey=sc4ocz1ypd422wgu7y5jg62tt&dl=1 1:38:25 PM:
> > 2024-02-13 13:26:30.137 [CORE] DeliveryOptimization error: 0x80190190, extended error: 0x00000000 1:38:25 PM:
> > 2024-02-13 13:26:30.137 [FAIL] C:__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFE872B9F7B: (caller: 00007FFE872BA79F) Exception(3) tid(1ff0) 80190190 Bad request (400). 1:38:25 PM:
> > 2024-02-13 13:38:24.770 [FAIL] C:__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(185)\WindowsPackageManager.dll!00007FFE872B37C9: (caller: 00007FFE872B5769) Exception(4) tid(1ff0) 80072EE2     Msg:[InternetReadFile() failed.] 1:38:25 PM:
> > 2024-02-13 13:38:24.796 [CLI ] Caught wil::ResultException: C:__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(185)\WindowsPackageManager.dll!00007FFE872B37C9: (caller: 00007FFE872B5769) Exception(4) tid(1ff0) 80072EE2     Msg:[InternetReadFile() failed.]
> 
> (Automated response - build 735.)

**Comment by stephengillie** [comment]
URL: https://www.dropbox.com/scl/fi/4bn8b5bq6ojrdnvceh2tk/COEIROINK_WIN_GPU_v.2.3.4.zip?rlkey=sc4ocz1ypd422wgu7y5jg62tt&dl=1 
Status Code: 200

(Automated message - build 745)

**Comment by stephengillie** [comment]
[Policy] Network-Blocker

**Comment by stephengillie** [comment]
This host appeears to have a user-agent block against downloads. This is why they work in the browser but not in the package manager.

**Pull request closed without merging**
