### PR TITLE
Mitalk 4.0.100

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3468)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
I cannot run the app.  Seems to be missing dependencies.

image

**Comment by oxygen-dioxide** [comment]
Sorry, I'm not the developer of Mitalk, so I don't know what has happened. However, maybe I can give you some help.

This app can successfully run on my computer (windows 10 professional build 20211)
This app is developed with electron. There are several electron apps that passed validation. here is a list:
utaformatix #3491 
vscodium #3549
wiznote lite #2624 
visual studio code #3215 
atom #2454
majsoul-plus #3384 
picgo #1031
celebro #193
simplenote #3092
jitsi meet #3225 
electorrent #240 
stretchly #2542

**Comment by KevinLaMS** [comment]
@denelon  this still fails with the above dialog.

**Comment by denelon** [comment]
@oxygen-dioxide do you know what the dependencies are?  I'll add "Blocking-Issue" so we can return to this when dependencies are supported.

**Pull request closed without merging**
