### PR TITLE
Update PackageName for Dapr CLI Preview 1.9.0-rc.1

### PR DESCRIPTION
**Pull request by shivamkm07**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

Similar to https://github.com/microsoft/winget-pkgs/pull/84682, the PR updates PackageName for Dapr CLI 1.9.0-rc.1

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/85074)

### CODE REVIEW

**Comment by shivamkm07** [comment]
cc @ItzLevvie2

**Review by Trenly — CHANGES_REQUESTED** [review]
The `PackageName` is actually correct - as the Display Name in Control Panel is `CLI`

image

**Comment by shivamkm07** [comment]
> > The `PackageName` is actually correct - as the Display Name in Control Panel is `CLI`
> > image
> 
> For this specific preview release, yes, it is just `CLI`. But it has been updated to `Dapr CLI` in our scripts and thereby reflected in https://github.com/microsoft/winget-pkgs/tree/master/manifests/d/Dapr/CLI/1.9.1. It would also be same in all future Preview as well as Stable releases. Updating this here so that it gets automatically picked up in future releases.

@Trenly thoughts on this? The motivation here is to update the manifests with the updated `PackageName` as been merged in our repo: https://github.com/dapr/cli/issues/1076. This would help picking up the correct PackageName for future releases where we would be using `wingetcreate update` to update manifests: https://github.com/dapr/cli/pull/1068/files.

If it can't be updated for this specific preview release, I can also update manually later on for the next preview release. Either is fine.

**Comment by Trenly** [comment]
It would be best to wait to make the change until the next release in order to keep metadata accurate for each package version

**Comment by shivamkm07** [comment]
> It would be best to wait to make the change until the next release in order to keep metadata accurate for each package version

Sounds good. I will close this PR then and re-open for next release. Thanks!

**Pull request closed without merging**
