### PR TITLE
New package: PlantUML.PlantUML version v1.2023.9

### PR DESCRIPTION
**Pull request by seppeon**
I've made a manifest for PlantUML, which at this time does not work. I need some assistance fixing an issue.

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/110767&drop=dogfoodAlpha

### CODE REVIEW

**Comment by seppeon** [comment]
I need some help with this one:

1. there is an issue where the standalone `.jar` file is renamed to `.exe`.
2. I'd like to add a dependancy to the openjdk or java runtime if possible.

**Comment by stephengillie** [comment]
> ##[warning] Validation concluded that this task needs to go to manual review.

**Comment by stephengillie** [comment]
Manual Validation failed with:
> 1:55:31 PM: C:\Users\User\AppData\Local\Microsoft\WinGet\Links\plantuml.jar.exe 
> start-process : This command cannot be run due to the error: The specified executable is not a valid application for this OS platform..

**Comment by stephengillie** [comment]
This appears to be a portable `JAR` file. 
- Should `Orcale.JavaRuntimeEdition` or similar be a dependency?
- The `portable` InstallerType appears to be appending a `.exe` to the file name. Another InstallerType might be needed, though I'm unsure of a better type.

**Comment by seppeon** [comment]
Thanks, yeah I'd have to bounce it back to the original author in that case. Is there a downside adding support for .jar in winget-cli, I have read through the code, it doesn't appear to be particularly complicated. There is a renaming function that performs a rename operation on the filenames that appear in the URL, it assumes anything standalone is .exe, remove that assumption and I believe it may work. I got the code building, but for some reason it ran the unmodified version lol, so I'll have to look at it again tonight.

**Comment by seppeon** [comment]
Ok so I've put this PR up.
https://github.com/microsoft/winget-cli/pull/3385

I think that _might_ resolve the renaming issue.

**Comment by denelon** [comment]
As raised in:
* https://github.com/microsoft/winget-cli/issues/3386

I think the best thing to do here is raise a more explicit error when the portable package doesn't have the .exe extension.

We're going to have more work to do around reasoning how WinGet should handle a Java Archive as a "portable" package.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/3387

**Comment by denelon** [comment]
We've got the issues open that would be required to approve a PR for a portable-jar. I'm going to go ahead and close this PR. Be sure to upvote/follow the two issues mentioned above.

**Pull request closed without merging**
