### PR TITLE
New package: LesFerch.WinSetView version 2.99

### PR DESCRIPTION
**Pull request by Akaizoku**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? Closes https://github.com/LesFerch/WinSetView/issues/124

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/175473)

### CODE REVIEW

**Comment by stephengillie** [comment]
image

As with [previous versions](https://github.com/microsoft/winget-pkgs/pull/152223), this package depends on relative links, which don't currently work with symlinks.

**Comment by Akaizoku** [comment]
@stephengillie, I must say that it does appear to work as expected on my machine running Windows 11 build 22631.4169.

When does the error occur?

**Comment by stephengillie** [comment]
The package itself installs and launches normally. The issue is that symlinks are used instead of LNK files, and when the application is launched from these it uses their location as the relative directory. Applications which are built with relative references to DLLs and other files aren't able to find these files, and so can't operate correctly. There might be a fix on the way soon, I have heard.

**Comment by MagicAndre1981** [comment]
there is now an installer for WinSetView 3.00 which can be used for winget support

**Comment by Trenly** [comment]
@Akaizoku - Support for zipped binaries has now been added and is available in the pipelines. This will require you to update your submission to ManifestVersion: 1.9.0 and set ArchiveBinariesDependOnPath: true in the installer node. To keep things clean, this PR is being closed. Please submit a new PR for the latest version of this package. Thank you for your contributions!

**Pull request closed without merging**
