### PR TITLE
Normalize Crazybump.Crazybump 1.2.2

### PR DESCRIPTION
**Pull request by Trenly**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/72874)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
VirtualBoxVM_QZQc1qnLxF

**Comment by Madhusudhan-MSFT** [comment]
This seems to install fine but launching it would result in a failure as follows:

image


this looks .net dependency it looks for is missing.

**Comment by Madhusudhan-MSFT** [comment]
Given this is just only normalization change and this package was submitted long ago. Our assumption is this package likely used by people already have dependencies. So, applying waiver for this one.

**Comment by Trenly** [comment]
> Given this is just only normalization change and this package was submitted long ago. Our assumption is this package likely used by people already have dependencies. So, applying waiver for this one.

Thanks for the context!

**Pull request merged**
