### PR TITLE
Evernote v6.25.0.9084

### PR DESCRIPTION
**Pull request by OfficialEsco**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2072)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Good to know

**Comment by KevinLaMS** [comment]
Hey @OfficialEsco 
When I run this, it seems to succeed, but the error returned from the installer is 3221225477.  Do you know what this is and how we can get rid of it?  The app seems to work fine despite that.

**Comment by OfficialEsco** [comment]
@KevinLaMS i've just tested a few things and the already merged manifest, everything seems to return that error code, Evernote is also missing a icon while using WinGet

**Comment by KevinLaMS** [comment]
https://github.com/microsoft/winget-cli/issues/137

**Comment by OfficialEsco** [comment]
This seems to have been fixed

**Pull request closed without merging**
