### PR TITLE
Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\5.4.4

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114136&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
> 11:49:23 AM:  2023-08-08 11:49:22.319 [CLI ] ShellExecute installer failed: 1603
11:49:23 AM: CustomAction _67AC4AD8_6F00_4853_A52D_C3B81180AEFA returned actual error code 1602 (note this may not be 100% accurate if translation happened inside sandbox)
11:49:23 AM: MSI (s) (38:58) [11:49:21:394]: Product: OneMoreAddIn -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action _67AC4AD8_6F00_4853_A52D_C3B81180AEFA, location: C:\Program Files (x86)\River\OneMoreAddIn\OneMoreSetupActions.exe, command: --install --x86
11:49:23 AM: Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action _67AC4AD8_6F00_4853_A52D_C3B81180AEFA, location: C:\Program Files (x86)\River\OneMoreAddIn\OneMoreSetupActions.exe, command: --install --x86
11:49:23 AM: Property(S): ErrorDialog = ErrorDialog
11:49:23 AM: MSI (s) (38:58) [11:49:22:019]: Product: OneMoreAddIn -- Installation failed.
11:49:23 AM: MSI (s) (38:58) [11:49:22:019]: Windows Installer installed the product. Product Name: OneMoreAddIn. Product Version: 5.4.4. Product Language: 1033. Manufacturer: River. Installation success or error status: 1603.

**Pull request merged**
