### PR TITLE
Add Documentation for manifest 1.4

### PR DESCRIPTION
**Pull request by Trenly**
Creating as draft for later merge

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/87347)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Comment by Trenly** [comment]
cc @stephengillie

**Review by stephengillie — APPROVED** [review]

**Comment by Trenly** [comment]
@stephengillie - Probably needs to be manually merged since there isn't a pipeline run associated with project files

**Comment by denelon** [comment]
@Trenly I think the PR template and the updates to the fabricbot.json were a bit premature. 

Have you seen any 1.4 manifests pass automated validation? If you have, then that's a different issue for me to track down 😊

**Comment by Trenly** [comment]
> @Trenly I think the PR template and the updates to the fabricbot.json were a bit premature.
> 
> Have you seen any 1.4 manifests pass automated validation? If you have, then that's a different issue for me to track down 😊

@denelon - My mistake; I thought those were in a separate PR. I haven't seen any 1.4 pass validation, but they are all marked with Manifest-Validation-Error. Do you think we should roll back, or just wait this one out. Based on what I've seen in the recent submissions, since Wingetcreate and YamlCreate are both still using 1.2, there hasn't been any confusion

**Comment by denelon** [comment]
Worst case, I think we just roll back the fabricbot.json and the PR template.
One of our internal teams got confused and reached out to me.

**Comment by Trenly** [comment]
> Worst case, I think we just roll back the fabricbot.json and the PR template.
> One of our internal teams got confused and reached out to me.

My apologies once again; I'll monitor the pipelines over the next few days, but if any other items come up on your end just @ me and I'll create a revert commit, and then we can revert the revert once everything is ready

**Comment by denelon** [comment]
No worries, we should have caught and handled this one slightly differently :)

**Pull request merged**
