### PR TITLE
Add/metanorma

### PR DESCRIPTION
**Pull request by CAMOBAP**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue? https://github.com/metanorma/packed-mn/issues/159

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/168143)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @CAMOBAP,

Manual Validation ended with:
image

Should `RubyInstallerTeam.Ruby.3.2` or similar be a dependency?

**Comment by CAMOBAP** [comment]
@stephengillie thanks for the details, aсtually no, Ruby dist is embedded into metanorma.exe, looks like some dependent dll is missing, maybe "Microsoft Visual C++ Redistributable" is required, let me doublecheck

**Comment by Trenly** [comment]
[Policy] Zip Binary

**Comment by stephengillie** [comment]
Verify:
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
