### PR TITLE
New package: tonybenoy.ray version 0.1.0

### PR DESCRIPTION
**Pull request by tonybenoy**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/193143)

### CODE REVIEW

**Comment by tonybenoy** [comment]
@microsoft-github-policy-service agree [company="{Tony Benoy}"]

**Comment by tonybenoy** [comment]
@microsoft-github-policy-service agree

**Comment by tonybenoy** [comment]
@microsoft-github-policy-service agree company="Tony Benoy"

**Review by Trenly — CHANGES_REQUESTED** [review]
This package appears to have a dependency on `Microsoft.VCRedist.2015+.x64`. Please add it using 
```
Dependencies:
  PackageDependencies:
```

image

**Comment by tonybenoy** [comment]
> This package appears to have a dependency on `Microsoft.VCRedist.2015+.x64`. Please add it using
> 
> ```
> Dependencies:
>   PackageDependencies:
> ```
> 
> image

Thanks! Added dependency

**Comment by tonybenoy** [comment]
As it's a wrapper windows defender detects it as a trojan. I guess I'll close the submission

**Comment by tonybenoy** [comment]
As it's a wrapper windows defender detects it as a trojan. I guess I'll close the submission

**Pull request closed without merging**
