### PR TITLE
New version: Levminer.Authme version 4.1.0

### PR DESCRIPTION
**Pull request by superusercode**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/107311)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335226 
> 2023-05-18 15:36:46.045 [CLI ] ShellExecute installer failed: 1603 
> CustomAction DownloadAndInvokeBootstrapper returned actual error code 1 (note this may not be 100% accurate if translation happened inside sandbox) 
> MSI (s) (AC:EC) [15:36:45:483]: Product: Authme -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  
> Action DownloadAndInvokeBootstrapper, location: C:\Program Files\Authme\, command: powershell.exe -NoProfile -windowstyle hidden try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 } catch {}; Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile "$env:TEMP\MicrosoftEdgeWebview2Setup.exe" ; Start-Process -FilePath "$env:TEMP\MicrosoftEdgeWebview2Setup.exe" -ArgumentList (&apos;/silent&apos;, '/install') -Wait  Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  
> Action DownloadAndInvokeBootstrapper, location: C:\Program Files\Authme\, command: powershell.exe -NoProfile -windowstyle hidden try { [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12 } catch {}; Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/p/?LinkId=2124703" -OutFile "$env:TEMP\MicrosoftEdgeWebview2Setup.exe" ; Start-Process -FilePath "$env:TEMP\MicrosoftEdgeWebview2Setup.exe" -ArgumentList (&apos;/silent&apos;, '/install') -Wait  Property(S): ErrorDialog = ErrorDlg 
> MSI (s) (AC:EC) [15:36:45:874]: Product: Authme -- Installation failed. 
> MSI (s) (AC:EC) [15:36:45:874]: Windows Installer installed the product. Product Name: Authme. Product Version: 4.1.0. Product Language: 1033. Manufacturer: Levminer. Installation success or error status: 1603.

**Comment by stephengillie** [comment]
This installed successfully in a Windows 11 VM - does it run on Windows 10?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by Trenly** [comment]
> I know /passive works but /quiet doesn't. How do I set that properly on the manifest?

Try adding this to the installer:
```
InstallerSwitches:
  Silent: /passive
  SilentWithProgress: /passive
```

**Comment by Trenly** [comment]
Hmmmm. . .

**Comment by Trenly** [comment]
[Policy] Dependencies

**Review by Trenly — APPROVED** [review]
@superusercode - May also want to submit a PR for version 4.2.1 which is now the latest

**Pull request merged**
