### PR TITLE
New package: Insco.PicGuard version 1.0.0.382

### PR DESCRIPTION
**Pull request by kjxbyz**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/167603)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://github.com/picguard/picguard/releases/download/v1.0.0%2B382/picguard_1.0.0+382_windows_x64_en-US.msi 
Status Code: 200

(Automated message - build 887)

**Comment by kjxbyz** [comment]
> * https://www.picguard.app/en/legal/privacy/

@stephengillie  It works fine.

截屏2024-08-14 05 43 42

**Comment by kjxbyz** [comment]
Is this problem because the URL ends with `/`?

**Comment by stephengillie** [comment]
Verify:
image
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
