### PR TITLE
Update JTL.Wawi to v1.5.46.0

### PR DESCRIPTION
**Pull request by DasCanard**
Changelog: https://www.jtl-software.de/jtl-wawi-download/changelog#version-1-5-46-0

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with Windows Sandbox?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/18344)

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]
Would you mind creating a de-DE locale?

**Comment by DasCanard** [comment]
> Would you mind creating a de-DE locale?

That's a good idea. I'll be adding it in the next few minutes.

**Comment by DasCanard** [comment]
> Would you mind creating a de-DE locale?

Pull Request created for de-DE locale
#18352

**Comment by OfficialEsco** [comment]
> > Would you mind creating a de-DE locale?
> 
> Pull Request created for de-DE locale
> #18352

Great!

**Pull request merged**
