### PR TITLE
Parsec version 150-70 based on 150.47

### PR DESCRIPTION
**Pull request by Master-Guy**
Actually changed the version number and SHA this time, and put it in the correct file..

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15219)

### CODE REVIEW

**Comment by KaranKad** [comment]
I don't think version should be named this vaguely.

**Comment by Master-Guy** [comment]
> I don't think version should be named this vaguely.

It's the actual version as named by the publisher, and reported by `winget list`

**Comment by KaranKad** [comment]
Oh! my bad, didn't know that.

**Comment by Master-Guy** [comment]
The validation might time out, because the app runs immediately after installation.

**Pull request merged**
