### PR TITLE
Update Appium to 1.18.0.Yaml

### PR DESCRIPTION
**Pull request by rajatgupta24**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [ ] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3832)

### CODE REVIEW

**Comment by ItzLevvie** [comment]
cc @rajatgupta24 You can only submit **1 manifest per PR**.

**Comment by rajatgupta24** [comment]
> cc @rajatgupta24 You can only submit **1 manifest per PR**.

**Comment by rajatgupta24** [comment]
> cc @rajatgupta24 You can only submit **1 manifest per PR**.

Oh! can you tell me what should i do now

**Comment by KevinLaMS** [comment]
@rajatgupta24 I think you should break these up into individual PRs.  
Though I think I saw them submitted.  If they are duplicates you can just close this PR.

**Comment by rajatgupta24** [comment]
> @rajatgupta24 I think you should break these up into individual PRs.
> Though I think I saw them submitted. If they are duplicates you can just close this PR.

Okay

**Pull request closed without merging**
