### PR TITLE
[Agreements] Add back Kingsoft.KingsoftPDF 12.6.0.15459

### PR DESCRIPTION
**Pull request by Trenly**
@denelon @stephengillie
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/139290)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-15T20:59:40.1529656Z ##[error] Manifest Error: The multi file manifest has inconsistent field values. [ManifestVersion] Value: 1.5.0 File: Kingsoft.KingsoftPDF.yaml

(Automated response - build 751.)

**Comment by denelon** [comment]
That looks like an inconsistency related to the internal database. We will run a rebuild which should resolve this error.

**Comment by Trenly** [comment]
> That looks like an inconsistency related to the internal database. We will run a rebuild which should resolve this error.

I think it was just an error I made when making the PR. I missed updating one of the files

**Comment by stephengillie** [comment]
This manifest contains a term that is blocked:

> Trenly wants to merge 2 commits into microsoft:master from Trenly:KingsoftPDFEula    - AgreementLabel: End User License Agreement (EULA)   - AgreementLabel: 最终用户许可协议 (EULA)

(Automated response - build 763.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
