### PR TITLE
New version: SomePythonThings.WingetUIStore version 1.7.0

### PR DESCRIPTION
**Pull request by marticliment**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/103821)

### CODE REVIEW

**Comment by marticliment** [comment]
could thjs issue be caused by vcredist requiring administrator rights launched from a non admin process?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code 1 
InstallationVerification-x64-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20230428204911

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
I'm not finding the cause for this error. It installs normally on a Windows 11 VM.

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
