### PR TITLE
Okular: Delete v22.12.2 bc of 404 download

### PR DESCRIPTION
**Pull request by Croydon**
Note: 22.12.01 is currently 404 too, but for this version a stable download exists, see #96500

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/96501)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
This needs to be done in 5 separate pull requests.

**Review by Trenly — CHANGES_REQUESTED** [review]
This should probably be updated to the latest 22.12.2 build rather than removed outright;

https://binary-factory.kde.org/view/Windows%2064-bit/job/Okular_Release_win64/

https://binary-factory.kde.org/view/Windows%2064-bit/job/Okular_Release_win64/lastSuccessfulBuild/artifact/okular-22.12.2-1294-windows-cl-msvc2019-x86_64.exe

**Comment by Croydon** [comment]
> This should probably be updated to the latest 22.12.2 build rather than removed outright;
> 
> https://binary-factory.kde.org/view/Windows%2064-bit/job/Okular_Release_win64/
> 
> https://binary-factory.kde.org/view/Windows%2064-bit/job/Okular_Release_win64/lastSuccessfulBuild/artifact/okular-22.12.2-1294-windows-cl-msvc2019-x86_64.exe

But those are nightly builds again. And they will be gone soon-ish again. Since they are the latest version this will also break again installation via winget without specifying an older version.

**Comment by Croydon** [comment]
Closing for now in favour of #96615, but it will keep breaking as long as upstream does not provide permanent downloads for more versions than currently (currently only #96500)

**Pull request closed without merging**
