### PR TITLE
[YamlCreate] Zip Support

### PR DESCRIPTION
**Pull request by Trenly**
@jedieaston @OfficialEsco @denelon - The manifest version has been left at 1.2.0 to prevent users from submitting zip manifests before validation is ready unless they explicitly override the manifest version.

## Changes:
* Adds a `-Preserve` flag to preserve `ReleaseNotes`, `ReleaseNotesUrl`, and `ReleaseDate` when running an auto-upgrade to support manifest version changes without disturbing existing metadata
* Uses the direct link to the schema files if the aka.ms link is not available for a given manifest version
* Fixed a bug where if an Appx package errored during install, the latest installed Appx package would be removed unintentionally
* No longer automatically adds in `MinimumOsVersion`
* Adds support for Zip installers when `ManifestVersion` is `1.4.0`
* Adds a developer setting for overriding manifest version
* When manifest version has been overridden to a newer manifest version, uses `-Prerelease -EnableExperimentalFeatures` in the sandbox test (to support testing Zip in 1.4)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/80127)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by JohnMcPMS — APPROVED** [review]

**Comment by JohnMcPMS** [comment]
Let me know if you are ready to merge this.

**Comment by Trenly** [comment]
> Let me know if you are ready to merge this.

I'm ready for merge any time; I've done a fair amount of local testing and haven't found any new bugs

**Comment by Trenly** [comment]
❤️

**Comment by fluentmoheshwar** [comment]
Woah. This is we all waiting for.

**Pull request merged**
