### PR TITLE
[Portable] New Package: Haali.WinUtils.lswitch 1.0.0

### PR DESCRIPTION
**Pull request by Trenly**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

* Resolves #31004

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/68807)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by Trenly — COMMENTED** [review]
Bump

**Comment by Trenly** [comment]
Bump

**Comment by Trenly** [comment]
@denelon - Is this winget or is this the publisher? The URL passes the URL Scan, but errors when downloading?
```
8/17/2022 9:26:33 PM
Status: Completed
##[error] Installer https://haali.net/winutils/lswitch.exe
##[error] Result: Failed
##vso[task.logissue type=error] Error occurred while downloading installer from https://haali.net/winutils/lswitch.exe. 0x80072F0C.
Error information: 
Http Response: OK
Http Reason Phrase: OK
```
https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=350886&view=logs&j=871b4eed-22de-5cb6-c1c8-82f190de633f&t=523ceef4-ddf7-55a0-c83d-dd0f77b67744&l=40

**Comment by denelon** [comment]
@Trenly, I've assigned to our "on-call" to investigate.

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
