### PR TITLE
Fixed folder case for WikidPad version 2.3rc02.

### LINKED ISSUE #22505: Problem with w\WikiPad manifest?
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue
When I fork and clone the repository to my local PC, the entry for w\WikiPad in Manifests is always marked as "dirty" on my PC. My fork insists that it is up to date with Master, and I can't see how to resolve this. Is there some error in the repository for the Manifest w\WikiPad ?
# Steps to reproduce
Forked the repo to my account on GitHub and using TortoiseGit created a clone on my local PC

# Expected behavior
I would expect a full, clean copy of the repo on my PC

# Actual behavior
The Manifest w\WikiPad is always flagged as "dirty"

# Environment

```none
Windows Package Manager v1.0.11694
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.100
Package: Microsoft.DesktopAppInstaller v1.15.11694.0

Any other software?
TortoiseGit 2.12.0.0 (C:\Program Files\TortoiseGit\bin)
git version 2.31.1.windows.1 (C:\Program Files\Git\bin; C:\Program Files\Git\mingw64\; C:\Program Files\Git\etc\gitconfig)
```

### PR DESCRIPTION
**Pull request by jedieaston**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

Resolves #22505.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/22546)

### CODE REVIEW

**Comment by jedieaston** [comment]
> 

 Manifest: The manifest file path must match PackageIdentifier and PackageVersion properties from manifest. actual 'manifests\w\WikidPad\WikidPad\2.3rc02', expected 'manifests\w\WikidPad\Wikidpad\2.3rc02'


The PackageIdentifier is `WikidPad.WikidPad` though?

**Comment by vedantmgoyal2009** [comment]
I am also trying to correct it, please do not flag it as duplicate.

**Comment by jedieaston** [comment]
I thought that policy had been disabled (people do git mv for version changes all the time). Understood, closed.

**Comment by vedantmgoyal2009** [comment]
Also, the problem is Windows (I have not tested macOS and Linux) merges WikidPad and Wikipad and shows them inside one directory, and the same with GitBash installed on Windows.

**Comment by OfficialEsco** [comment]
> I thought that policy had been disabled (people do git mv for version changes all the time). Thanks for setting me straight, we should document some of this stuff.

This is something else, the issue here is that GitHub Web shows two different folders if there is a difference in big and small letters in the folder name, Windows does not so it combines the folder and then GitHub Desktop freaks out.

The Policy you are talking about lets us move/rename one(?) folder in "Publisher/Software", but since the GitHub API sees "publisher/software" you are not allowed, i've requested that this is allowed tho so we can fix some folder names.

The reason these got into the repo was because wingetcreate version "1.0.0" didn't check for already existing folders...

**Pull request closed without merging**
