### PR TITLE
Remove version: Sigrok.PulseView version nightly

### PR DESCRIPTION
**Pull request by schembriaiden**
### Wrong naming scheme, will readd

https://github.com/microsoft/winget-pkgs/issues/162354

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/162357)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: http://sigrok.org/download/binary/pulseview/pulseview-NIGHTLY-64bit-static-release-installer.exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 886)

**Comment by stephengillie** [comment]
URL: http://sigrok.org/download/binary/pulseview/pulseview-NIGHTLY-64bit-static-release-installer.exe 
Response Error: The remote server returned an error: (404) Not Found.

(Automated message - build 911)

**Comment by stephengillie** [comment]
Hi @vikingnope,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 886.)

**Comment by vikingnope** [comment]
@stephengillie, This has the wrong filing methods and naming scheme, I have re-adding it after.

**Comment by stephengillie** [comment]
URL: http://sigrok.org/download/binary/pulseview/pulseview-NIGHTLY-64bit-static-release-installer.exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 886)

**Review by ItzLevvie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
