### PR TITLE
New package: Inkdrop.Inkdrop.Portable version 5.8.1

### PR DESCRIPTION
**Pull request by CoolPlayLin**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/154151)

### CODE REVIEW

**Comment by Trenly** [comment]
[Policy] Zip Binary

**Comment by CoolPlayLin** [comment]
Why https://github.com/microsoft/winget-pkgs/labels/zip-binary ?

**Comment by Trenly** [comment]
> Why [ zip-binary](https://github.com/microsoft/winget-pkgs/labels/zip-binary) Depends on library files that aren't available via symlink ?

image

**Comment by CoolPlayLin** [comment]
But it can actually run normally

**Comment by Trenly** [comment]
> But it can actually run normally

Not in all cases. If the user has Developer mode enabled, or runs the install as admin, then attempting to run inkdrop using the command line alias that gets added causes the paths to the DLLs to be unavailable.

**Comment by og-mrk** [comment]
> > But it can actually run normally
> 
> Not in all cases. If the user has Developer mode enabled, or runs the install as admin, then attempting to run inkdrop using the command line alias that gets added causes the paths to the DLLs to be unavailable.

Kind of curious on this particular situation, if the CommandAlias won't work (that is, if the user installs the software as admin to make the Symbolic Link in the first place).. then can't we just remove the PortableCommandAlias field and partially resolve the zip-binary issue?

My apologies if the above suggestion/question might seem like a stupid idea, as I'm kind of new with this particular topic. Thanks in advance @Trenly 😄

**Comment by Trenly** [comment]
> > > But it can actually run normally
> > 
> > 
> > Not in all cases. If the user has Developer mode enabled, or runs the install as admin, then attempting to run inkdrop using the command line alias that gets added causes the paths to the DLLs to be unavailable.
> 
> Kind of curious on this particular situation, if the CommandAlias won't work (that is, if the user installs the software as admin to make the Symbolic Link in the first place).. then can't we just remove the PortableCommandAlias field and partially resolve the zip-binary issue?
> 
> My apologies if the above suggestion/question might seem like a stupid idea, as I'm kind of new with this particular topic. Thanks in advance @Trenly 😄

No, removing the command alias doesn’t change the underlying behavior. WinGet will always attempt to add the program to PATH - if PortableCommandAlias isn’t set, then WinGet will just use the file name as the alias. And, since WinGet doesn’t add start menu entries or desktop icons for portable apps, the only ways to start the application are to use the command line, or navigate to the executable directly. So an admin install always results in a symlink, and a user install results in a symlink if developer mode is enabled, and if there are dll dependencies then the application won’t launch properly from the command line if a symlink is used.

**Comment by Trenly** [comment]
@CoolPlayLin - Support for zipped binaries has now been added and is available in the pipelines. This will require you to update your submission to ManifestVersion: 1.9.0 and set ArchiveBinariesDependOnPath: true in the installer node. To keep things clean, this PR is being closed. Please submit a new PR for the latest version of this package. Thank you for your contributions!

**Pull request closed without merging**
