### PR TITLE
New package: Microsoft.VCRedist.2015+.arm64 version 14.38.33130.0

### PR DESCRIPTION
**Pull request by CoolPlayLin**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.0.1 :rocket:
- Resolve #136925

This also could help merge #136918

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136931)

### CODE REVIEW

**Comment by CoolPlayLin** [comment]
Why?
CC @stephengillie @Trenly

**Review by Trenly — CHANGES_REQUESTED** [review]
This package already exists as Microsoft.VCRedist.2022.arm64 - the manifest should be placed there

**Comment by Trenly** [comment]
> Why? CC @stephengillie @Trenly

https://github.com/microsoft/winget-pkgs/labels/Internal-Error-NoSupportedArchitectures means the pipelines don't have a runnner to support validating Arm64 images. If a manifest only contains an Arm64 installer, that error will be thrown

**Comment by CoolPlayLin** [comment]
> This package already exists as Microsoft.VCRedist.2022.arm64 - the manifest should be placed there

Hi @russellbanks 
Does Komac require Microsoft.VCRedist.2022.arm64 or this package?

CC @sitiom

**Comment by sitiom** [comment]
> This package already exists as Microsoft.VCRedist.2022.arm64 - the manifest should be placed there

Why is the arm64 version placed in `2022` instead of `2015+`?

**Comment by Trenly** [comment]
> > This package already exists as Microsoft.VCRedist.2022.arm64 - the manifest should be placed there
> 
> Why is the arm64 version placed in `2022` instead of `2015+`?

Because a long time ago when the packages were moved to be in their current structure, thats where it got placed. The x64 and x86 installers had the package names of 2015-2019, 2015-2020, a d 2015-2022, where newer versions will overwrite the older ones and so they were grouped together into 2015+. But, the arm64 versions in the repo at the time were only listed as 2019 and 2022, so they were left as their individual packages

**Comment by ItzLevvie** [comment]
Close with reason: See above;

**Pull request closed without merging**
