### PR TITLE
New version: Billfish.Billfish version 2.9.0.11 [FP-D]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | Billfish | Billfish    |
| Version     | 2.9.0.11     | 2.9.0.11 |
| Publisher   | Billfish Co., Ltd.   | Billfish Co., Ltd.      |
| ProductCode | {5D1C4995-CFC4-4212-8358-E5B69581BEA0}_is1          | {5D1C4995-CFC4-4212-8358-E5B69581BEA0}_is1    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [1472](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/2294598489>)

### CODE REVIEW

**Comment by alexmercerind** [comment]
A newer pull-request is available at #59755.
This one is redundant. Sorry for the trouble.

Thanks.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Replaced by https://github.com/microsoft/winget-pkgs/pull/59755.

**Review by ItzLevvie — DISMISSED** [review]

**Review by Trenly — CHANGES_REQUESTED** [review]
This doesn't seem right

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Replaced by https://github.com/microsoft/winget-pkgs/pull/59818.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
