### PR TITLE
New version: OpenTofu.Tofu version 1.8.5

### PR DESCRIPTION
**Pull request by damn-good-b0t**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/188801)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-11-04 18:07:46.076 [FAIL] Installer failed security check. Url: https://github.com/opentofu/opentofu/releases/download/v1.8.5/tofu_1.8.5_windows_amd64.zip Result: 0x80004005
> 2024-11-04 18:02:13.532 [FAIL] Installer failed security check. Url: https://github.com/opentofu/opentofu/releases/download/v1.8.5/tofu_1.8.5_windows_386.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-11-05 05:26:12.927 [FAIL] Installer failed security check. Url: https://github.com/opentofu/opentofu/releases/download/v1.8.5/tofu_1.8.5_windows_amd64.zip Result: 0x80004005
> 2024-11-05 05:24:33.711 [FAIL] Installer failed security check. Url: https://github.com/opentofu/opentofu/releases/download/v1.8.5/tofu_1.8.5_windows_386.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-11-06 12:03:40.984 [FAIL] Installer failed security check. Url: https://github.com/opentofu/opentofu/releases/download/v1.8.5/tofu_1.8.5_windows_amd64.zip Result: 0x80004005
> 2024-11-06 11:50:14.332 [FAIL] Installer failed security check. Url: https://github.com/opentofu/opentofu/releases/download/v1.8.5/tofu_1.8.5_windows_386.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\OpenTofu.Tofu__DefaultSource\tofu.exe returned exit code: 127
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\tofu.exe returned exit code: 127
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Packages\OpenTofu.Tofu__DefaultSource\tofu.exe returned exit code: 127
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\tofu.exe returned exit code: 127

(Automated response - build 897.)

**Pull request merged**
