### PR TITLE
Tencent.QQ.NT version 9.9.2.16183

### PR DESCRIPTION
**Pull request by Dragon1573**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?
- [x] Have you tested your manifest locally with `Tools/SandboxTest.ps1 -Manifest <path>`?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/118186)

### CODE REVIEW

**Comment by Dragon1573** [comment]
## Note

`Tencent.QQ.NT` aims to take place of `Tencent.QQ` in the future, but for now they are "parallel releasing" as different packages.

`Tencent.QQ.NT` created with N(ew) T(echnology) framework by Tencent. Switches of this packages seems totally different from `Tencent.QQ`. Maybe the Azure Pipelines will stuck here because "silent switch" fails.

*****

Appreciate if someone helps me improve this PR, thanks! 😺

**Comment by Dragon1573** [comment]
Someone try it before, but failed with the silent switches. Azure Pipelines may failed with label [`Validation-Unattended-Failed`](https://github.com/microsoft/winget-pkgs/labels/Validation-Unattended-Failed) instead of [`Binary-Validation-Error`](https://github.com/microsoft/winget-pkgs/labels/Binary-Validation-Error).

Related #113453 #111273

**Comment by stephengillie** [comment]
Hi @Dragon1573,

It seems the host is blocking our data center:
> Installer https://dldir1.qq.com/qqfile/qq/QQNT/63f8bbfe/QQ9.9.2.16183_x86.exe
Scan request id: '9d5b7e29-bfa1-474f-8234-db59dfd1ce68'
Error information: BlockingDetectionFound
Installer https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe
Scan request id: 'b38d4015-4dc0-464e-9e10-c939e8966458'
Error information: BlockingDetectionFound

**Comment by stephengillie** [comment]
> @stephengillie Could you please explain "the host is blocking our data center"? Is `dldir1.qq.com` server block Microsoft Azure Pipelines and third-party antivirus system from downloading and scanning the `*.exe` installer?

This is correct - except that we use a first-party antivirus system (Defender) instead of a third-party system. 

> I have no authority controlling `qq.com` and its sub-domain. I see several similar PRs of package `Tencent.QQ` also blocked because of label `Binary-Validation-Error`. If this "blocking our data center" take place on Tencent's server, I can make no effort ...

Sorry, it's out of both of our control.

**Comment by Dragon1573** [comment]
I see the Azure Pipeline failed again inside the "Installer Validation" step 7 hours before in no more than 10 minutes. 

image

<details>
<summary>Run logs of Azure Pipelines</summary>

```log
============================================================================== 
Task         : Installers Scan
Description  : Invoke an Azure Function
Version      : 1.220.0
Author       : Microsoft Corporation
Help URL     : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/azure-function
============================================================================== 
POST ***?code=***&
Request body: {
  "operationId": "WinGetSvc-Validation-311-118186-20230829-1",
  "BuildId": "492672",
  "PlanUrl": "[https://dev.azure.com/ms/",](https://dev.azure.com/ms/%22,)
  "HubName": "build",
  "ProjectId": "ed6a5dfa-6e7f-413b-842c-8305dd9e89e6",
  "PlanId": "30cd3cf1-ccf1-42df-9c5f-d9002b2cf31f",
  "JobId": "871b4eed-22de-5cb6-c1c8-82f190de633f",
  "TimelineId": "30cd3cf1-ccf1-42df-9c5f-d9002b2cf31f",
  "TaskInstanceId": "523ceef4-ddf7-55a0-c83d-dd0f77b67744",
  "AuthToken": ***
}
				Response Code: OK
				Response: 

8/29/2023 6:41:51 PM
Installer Verification Analysis Context Information: 
Installer https://dldir1.qq.com/qqfile/qq/QQNT/bef02a45/QQ9.9.2.16183_x64.exe
Scan request id: '5dba2c8a-16ce-42e1-85e7-5836ca2bfb62'
Error information: BlockingDetectionFound
Installer https://dldir1.qq.com/qqfile/qq/QQNT/63f8bbfe/QQ9.9.2.16183_x86.exe
Scan request id: 'fc614743-fa7a-47f1-9fb7-e18b35a321e5'
Error information: BlockingDetectionFound

8/29/2023 6:41:52 PM

****************************************************************************************
Installer Validation
****************************************************************************************

-----------------------------------------------------
Result: Failed
-----------------------------------------------------
Status: Completed
```

</details>

*****

Emmm... Is it worth continue working on this PR? Maybe this `Tencent.QQ.NT` will block the antivirus detection in a following period. This may stuck anyone who want to contribute this manifest to `winget-pkgs` repo.

I would prefer keep the related issue #118245 open but stop further development on this PR for following reasons: 

1. Even though `Binary-Validation-Error` is solved, `Validation-Unattended-Failed` will still be there.
2. I can't figure out the installer type (Nullsoft, Nix, etc.) of `Tencent.QQ.NT`. Silent switch `/S` of `Tencent.QQ` takes no effect on `Tencent.QQ.NT`.
3. I can't figure out if `Tencent.QQ.NT` supports console parameters for entering silent installtion process.

**Comment by Dragon1573** [comment]
According to https://github.com/microsoft/winget-pkgs/issues/118245#issuecomment-1698422393, there's no reason continue working on this PR. The issue can be closed.

Willing to contribute if there're walkarounds.

**Pull request closed without merging**
