### PR TITLE
Add Belarc/Advisor-9.6.

### LINKED ISSUE #3494: Package Request: Belarc Advisor
# Package Requested
See https://www.belarc.com/products_belarc_advisor

Belarc Advisor v9.0 is available from downloads.com. 
See https://download.cnet.com/Belarc-Advisor/3000-2094_4-10007277.html

Manifest:

Fill out as much of the manifest as you can:

```YAML
Id: string # publisher.package format
Publisher: Belarc
Name: Belarc Advisor
Version: 9.0
License: Free for personal home use only
InstallerType: exe
Installers:
  - Arch: string # enumeration of supported architectures
    Url: https://files.downloadnow.com/s/software/16/32/54/74/advisorinstaller.exe?token=1599740424_f047f450d2a954ec3e2bc88f93098405&fileName=advisorinstaller.exe
    Sha256: e7cb8844770840dc36964471580aabfc8f7893432e5efc56e4b839d51a6beb6a
# ManifestVersion: 0.1.0
```

### PR DESCRIPTION
**Pull request by yigitemres**
Resolve: #3494

----

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3506)

### CODE REVIEW

**Comment by yigitemres** [comment]
Link actually works but WinGetSvc-Validation return this:
```
URI: https://www.belarc.com/products_belarc_advisor, Validation result: Failed, Http status code: Forbidden
```

**Comment by KevinLaMS** [comment]
@ashpatil-msft can you look at this?  Seems like the service check has an issue.  Thanks.

**Comment by BookWorm0** [comment]
@ashpatil-msft, KevinLaMS andI created a pull request for this manifest as well. If I read the dashboard correctly, it has passed automatic validation.

**Comment by BookWorm0** [comment]
@ashpatil-msft, @KevinLaMS and @yigitemres 

I created a pull request for this manifest as well. If I read the dashboard correctly, mine has passed automatic validation.

Sorry for the botched comment, I am new to GitHub and submitting pull requests

**Comment by KevinLaMS** [comment]
@yigitemres  we have  a bug in the service.  it will take a bit to get it fixed and pushed out.  If you want to get this PR through immediately, you can comment out the HomePage and it will pass.
Or we can leave it on Ashwini to resubmit once the fix has been made.

**Comment by yigitemres** [comment]
@KevinLaMS Thanks for the info. I'm gonna comment out.

**Pull request merged**
