### PR TITLE
Wakatime.DesktopWakatime version 0.1.0

### PR DESCRIPTION
**Pull request by KarbitsCode**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/185437)

### CODE REVIEW

**Comment by KarbitsCode** [comment]
> Both the desktop shortcut and double-clicking the EXE directly gave this error.

Comfirmed I can reproduce the error with Windows Sandbox:

Screenshot 2024-10-25 085417

But I can't reproduce that in my host machine, which is why I missed it.
I will investigate this error.

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
[Policy] Reset Labels

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Comment by KarbitsCode** [comment]
Hi @stephengillie,
Why is this getting approved?

**Comment by stephengillie** [comment]
I kept seeing this PR an a "squash-ready" state and merged it along with other PRs in this state. I have been moving too fast, trying to do too much, and mistakes like this are becoming more frequent.

**Comment by KarbitsCode** [comment]
> I kept seeing this PR an a "squash-ready" state and merged it along with other PRs in this state. I have been moving too fast, trying to do too much, and mistakes like this are becoming more frequent.

It's okay, after all the problem only occurs in sandboxed environment anyway.

**Pull request merged**
