### PR TITLE
New version: Coder.Coder version 2.6.0

### PR DESCRIPTION
**Pull request by cdrci**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131589)

### CODE REVIEW

**Comment by cdrci** [comment]
🤖 cc: @deansheather @matifali

**Comment by matifali** [comment]
Hi @stephengillie, @mdanish-kh it's unclear why the check are failing. Can you please take a look when you have time?

**Comment by mdanish-kh** [comment]
@matifali The validation pipelines have been under maintenance which is the likely cause for `Internal-Error-Dynamic-Scan`. I see a new pipeline run has been kicked off...let's see if this one passes. If not, we would need stephengliie to give it a manual check.

**Comment by mdanish-kh** [comment]
Also, it seems the validation pipeline is paused right now, presumably for maintenance. You can check the status through the labels in README.md

https://github.com/microsoft/winget-pkgs#windows-package-manager-community-repository

image

**Review by mdanish-kh — APPROVED** [review]

**Pull request merged**
