### PR TITLE
New version: VMware.WorkstationPlayer version 16.2.4.20089737

### PR DESCRIPTION
**Pull request by virtualex-itv**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/67200)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by virtualex-itv** [comment]
hi @ItzLevvie - seems to be the same issue as with the previous 16.2.3 package...

**Comment by virtualex-itv** [comment]
`##[error] Installer https://download3.vmware.com/software/WKST-PLAYER-1624/VMware-player-full-16.2.4-20089737.exe Scan information: 'Error information: BlockingDetectionFound'`

**Comment by virtualex-itv** [comment]
@ItzLevvie  `##[error] Installer https://download3.vmware.com/software/WKST-PLAYER-1624/VMware-player-full-16.2.4-20089737.exe Scan information: 'Error information: BlockingDetectionFound'`

same issue as the previous version

**Comment by virtualex-itv** [comment]
this PR has been open for 4 months and clearly, the pipeline runs are detecting a false positive and the file may need to be unblocked.  Please manually approve/merge this PR so the community can use it.

**Review by stephengillie — APPROVED** [review]

**Comment by ppvnf** [comment]
> I installed this version [16.2.4](https://download3.vmware.com/software/WKST-PLAYER-1624/VMware-player-full-16.2.4-20089737.exe) from winget, it installed succefully. But I can`t find this proprom in my PC after installation.
> 
> The previous version 16.2.3 doesnot have this issue. Please help to check!

Is it not in C:\Program Files (x86)\VMware\VMware Player?

**Pull request merged**
