### PR TITLE
New version: Cybelsoft.DriversCloud version 11.2.7.0 [FP-D]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | DriversCloud.com | DriversCloud.com    |
| Version     | 11.2.7.0     | 11.2.7.0 |
| Publisher   | Cybelsoft   | Cybelsoft      |
| ProductCode |           | {CB02B9E9-E44D-4A55-901B-C1197BBA61FF}    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [4985](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/3817833879>)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Comment by stephengillie** [comment]
The SQLite3 ODBC drivers are a dependency, and this package runs their installer in an unattended mode:
image

I couldn't find this dependency in Winget. Were it added, and set as a dependency here, this should pass validation.

**Comment by SpecterShell** [comment]
@taozuhong

**Comment by taozuhong** [comment]
Yes, Kangaroo select its ODBC driver default and then install it.

**Comment by taozuhong** [comment]
Yes, Kangaroo selects its ODBC drivers, then downloads and installs them.

**Comment by SpecterShell** [comment]
> Yes, Kangaroo selects its ODBC drivers, then downloads and installs them.

The ODBC drivers should also be installed silently when the Kangaroo installer is running in silent mode, otherwise the silent installation process will be stucked.

**Comment by taozuhong** [comment]
Nice idea, will be fixed at the next version.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
