### PR TITLE
Added Python.Python.3 version 3.9.6150.0

### PR DESCRIPTION
**Pull request by ImJoakim**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/19290)

### CODE REVIEW

**Comment by ImJoakim** [comment]
image

**Review by OfficialEsco — APPROVED** [review]

**Comment by Croydon** [comment]
@ImJoakim Why did you name the version number `3.9.6150.0` instead of `3.9.6`?

**Comment by ItzLevvie** [comment]
cc @Croydon: I don't have Python installed on my device but the version number needs to match whatever's shown in Control Panel so users don't end up in an upgrade loop.

This is reflected in the latest documentation as well: https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.0.0/defaultLocale.md#packageversion

**Comment by ImJoakim** [comment]
> @ImJoakim Why did you name the version number `3.9.6150.0` instead of `3.9.6`?

Hey there @Croydon, ItzLevvie is correct. The version that displays in the control panel is `3.9.6150.0`

Screenshot_1

**Comment by Croydon** [comment]
Thanks for the explanation. For consumers this is pretty bad IMHO, there are probably not many people who know about a Python version like `3.9.6150.0`, if they talk about Python versions they will mostly use e.g. `3.9.6`

**Comment by OfficialEsco** [comment]
Sounds like your issue is with @Python, those issues goes over here https://bugs.python.org.

**Pull request merged**
