### PR TITLE
Nelson v0.5.4

### PR DESCRIPTION
**Pull request by Nelson-numerical-software**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/11485)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Heeeey! The error is  `The pull request contains more than one manifest. Either singleton or multi file manifest under one Version directory.` because you deleted the old manifest + added a new manifest.
You need to post one PR to delete the old one and one to create the new one.

**Comment by OfficialEsco** [comment]
@Nelson-numerical-software read my comment

**Comment by Nelson-numerical-software** [comment]
> @Nelson-numerical-software read my comment

which ?

**Comment by Nelson-numerical-software** [comment]
> Heeeey! The error is `The pull request contains more than one manifest. Either singleton or multi file manifest under one Version directory.` because you deleted the old manifest + added a new manifest.
> You need to post one PR to delete the old one and one to create the new one.
> 
> edit: You also don't have to delete the old one since its version specific

Thanks :) for your help

**Comment by Nelson-numerical-software** [comment]
will be back in another PR ...

**Pull request closed without merging**
