### PR TITLE
Update: SandroMani.gImageReader version ci-latest-master

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132464)

### CODE REVIEW

**Comment by Trenly** [comment]
> 2024-01-02 14:31:00.196 [FAIL] Installer failed security check. Url: https://github.com/manisandro/gImageReader/releases/download/master/gImageReader_latest_qt5_i686.exe Result: 0x80004005

**Comment by stephengillie** [comment]
Hi @Trenly,

> This PR's version number ci-latest-master has 1 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 3.4.1, which has 3 parameters.

Is this intentional?

(Automated response - build 513)

**Comment by Trenly** [comment]
> Hi @Trenly,
> 
> > This PR's version number ci-latest-master has 1 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 3.4.1, which has 3 parameters.
> 
> Is this intentional?
> 
> (Automated response - build 513)

Yes

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
