### PR TITLE
Update: 3T.Robo3T version 1.3.1

### PR DESCRIPTION
**Pull request by Trenly**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/51589)

### CODE REVIEW

**Comment by hackean-msft** [comment]
@Trenly Do you intend for the architecture to be x64? The installer supplied is a x64 installer not x86.

**Comment by Trenly** [comment]
> @Trenly Do you intend for the architecture to be x64? The installer supplied is a x64 installer not x86.

Probably not; I was just using what was in the original manifest. I’ll update and see what happens

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
abcdefg

**Comment by Trenly** [comment]
> SSL Certificate expired.

This is an old package. I’m just converting to multimanifest; 

If the SSL expired I’m surprised it passed validation

**Comment by ItzLevvie** [comment]
> > SSL Certificate expired.
> 
> This is an old package. I’m just converting to multimanifest;
> 
> If the SSL expired I’m surprised it passed validation

Ignore that. I messed up my PowerShell script a bit.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
