### PR TITLE
[Portable] New Version: Rufus.Rufus 3.19

### LINKED ISSUE #26293: Help with Rufus.Rufus package
The current rufus package comes as .appx, but the developer stopped releasing .appx builds of Rufus, so I think it needs to use .exe now

# Package Requested

- [x] I would like someone else to build the manifest.
- [x] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [x] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**:
Rufus
**Publisher Url**:
https://rufus.ie
**Package Name**:
Rufus
**Package Url**:
https://rufus.ie

**Description**:
Rufus is a utility that helps format and create bootable USB flash drives, such as USB keys/pendrives, memory sticks, etc.
**Package Version**:
3.15
**Installer URL**:
https://github.com/pbatard/rufus/releases/download/v3.15/rufus-3.15.exe
## For new versions:

**Current Package Identifier**:
Rufus.Rufus

### LINKED ISSUE #60617: [New Version Available]: Rufus
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Pete Batard
Publisher Url: https://rufus.ie/en/
Package Name: 
Description: Rufus is a utility that helps format and create bootable USB flash drives, such as USB keys/pendrives, memory sticks, etc.
Package Version: 3.1.1877
Installer URL: https://github.com/pbatard/rufus/releases/download/v3.18/rufus-3.18.exe

Current Package Identifier (for new versions):

### PR DESCRIPTION
**Pull request by Trenly**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

* Resolves #60617
* Resolves #26293

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/68805)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Review by Trenly — COMMENTED** [review]
Bump

**Comment by Trenly** [comment]
Bump

**Comment by dwittenberg** [comment]
I found a problem. After installing Rufus as a portable application, it is only available from the command line. Unfortunately not in the start menu. 
Does anyone know if or when this start menu entry can also be created?

**Comment by Trenly** [comment]
> I found a problem. After installing Rufus as a portable application, it is only available from the command line. Unfortunately not in the start menu. Does anyone know if or when this start menu entry can also be created?

According to the [spec](https://github.com/microsoft/winget-cli/blob/master/doc/specs/%23182%20-%20Support%20for%20installation%20of%20portable%20standalone%20apps.md) -
> No shortcuts or icons will be created for the package.

If this is something you would like to see added, be sure to add a thumbs-up on the issue
* https://github.com/microsoft/winget-cli/issues/2299

**Review by KaranKad — APPROVED** [review]

**Pull request merged**
