### PR TITLE
Remove old version of JanDeDobbeleer.OhMyPosh

### LINKED ISSUE #26988: Lexikos.AutoHotkey package results in Installer hash does not match
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue
please confirm autohotkey package as it reports hash mismatch repeatedly

# Steps to reproduce
winget install autohotkey

# Expected behavior
package Lexikos.AutoHotkey installs

# Actual behavior
Found AutoHotkey [Lexikos.AutoHotkey]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/Lexikos/AutoHotkey_L/releases/download/v1.1.33.10/AutoHotkey_1.1.33.10_setup.exe
  ██████████████████████████████  3.13 MB / 3.13 MB
Installer hash does not match; to override this check use --force

# Environment

```none
[winget --info]
Windows Package Manager version v1.0.11694
Windows: Windows.Desktop version v10.0.22000.176
Package: Microsoft.DesktopAppInstaller version v1.15.11694.0

```

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
null

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
URI: https://autohotkey.com, Validation result: Passed
URI: https://www.autohotkey.com/boards, Validation result: Passed
URI: https://autohotkey.com, Validation result: Passed
URI: https://github.com/Lexikos/AutoHotkey_L/blob/master/license.txt, Validation result: Passed
URI: https://github.com/Lexikos/AutoHotkey_L/releases/download/v1.1.33.10/AutoHotkey_1.1.33.10_setup.exe, Validation result: Failed, Report feedback: https://feedback.smartscreen.microsoft.com/feedback.aspx?v=6&t=16&result=block&type=top&url=aHR0cHM6Ly9naXRodWIuY29tL0xleGlrb3MvQXV0b0hvdGtleV9ML3JlbGVhc2VzL2Rvd25sb2FkL3YxLjEuMzMuMTAvQXV0b0hvdGtleV8xLjEuMzMuMTBfc2V0dXAuZXhl

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/26989#event-5257175355

**Comment by vedantmgoyal2009** [comment]
Please post feedback [here](https://feedback.smartscreen.microsoft.com/feedback.aspx?v=6&t=16&result=block&type=top&url=aHR0cHM6Ly9naXRodWIuY29tL0xleGlrb3MvQXV0b0hvdGtleV9ML3JlbGVhc2VzL2Rvd25sb2FkL3YxLjEuMzMuMTAvQXV0b0hvdGtleV8xLjEuMzMuMTBfc2V0dXAuZXhl) or can someone do manual validation?

**Comment by vedantmgoyal2009** [comment]
cc @ryfu-msft @jamespik @KevinLaMS

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Close and reopen the PR to rerun pipelines.

**Comment by vedantmgoyal2009** [comment]
@palenshus

**Review by ItzLevvie — DISMISSED** [review]

**Comment by palenshus** [comment]
This is failing due to smartscreen:

URI: https://github.com/Lexikos/AutoHotkey_L/releases/download/v1.1.33.10/AutoHotkey_1.1.33.10_setup.exe, Validation result: Failed, Report feedback: https://feedback.smartscreen.microsoft.com/feedback.aspx?v=6&t=16&result=block&type=top&url=aHR0cHM6Ly9naXRodWIuY29tL0xleGlrb3MvQXV0b0hvdGtleV9ML3JlbGVhc2VzL2Rvd25sb2FkL3YxLjEuMzMuMTAvQXV0b0hvdGtleV8xLjEuMzMuMTBfc2V0dXAuZXhl

Please report feedback to get this unblocked

**Comment by vedantmgoyal2009** [comment]
I've already done that. Hoping that if some more users would report, it will come to the attention of the SmartScreen team sooner.

**Comment by palenshus** [comment]
> I've already done that. Hoping that if some more users would report, it will come to the attention of the SmartScreen team sooner.

Ah, thanks, I've reported it as well. It seems unlikely that it'll change, but, as I'm an Autohotkey user myself, I certainly hope that'll get overturned!

**Comment by Trenly** [comment]
Created a new PR so the merge conflict doesn't have to be fully rebased

**Pull request merged**
