### PR TITLE
MoheshwarAmarnathBiswas.UsefulToolsForWindows version 2.4

### PR DESCRIPTION
**Pull request by fluentmoheshwar**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/133270)

### CODE REVIEW

**Comment by fluentmoheshwar** [comment]
This software is incorrectly labeled as malicious by several antivirus software. I filed a false positive report for all of them.

https://www.virustotal.com/gui/file/fb3598aee2a1ab57f4890a29114d0a0b90029c18881952e42f9c0d6ce75e5544

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-08 11:46:33.903 [FAIL] Installer failed security check. Url: https://github.com/fluentmoheshwar/useful-tools/releases/download/v2.4/Useful_Tools_For_Windows_Installer.exe Result: 0x80004005

(Automated response - build 530.)

**Comment by stephengillie** [comment]
Hi @fluentmoheshwar,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 530.)

**Comment by stephengillie** [comment]
> This software is incorrectly labeled as malicious by several antivirus software. I filed a false positive report for all of them.
> 

Sorry to hear, and a few of our packages need more than one scan to pass. The best course seems to be giving a day and trying again.

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 3:48:46 PM: 2024-01-08 15:48:45.743 [FAIL] Installer failed security check. Url: https://github.com/fluentmoheshwar/useful-tools/releases/download/v2.4/Useful_Tools_For_Windows_Installer.exe Result: 0x80004005

(Automated response - build 530.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
