### PR TITLE
Updated TeamViewer.TeamViewerHost to version 15.20.6

### PR DESCRIPTION
**Pull request by ImJoakim**
image

```
PS C:\Users\WDAGUtilityAccount\Desktop\manifests> winget install -m "C:\Users\WDAGUtilityAccount\Desktop\manifests\t\TeamViewer\TeamViewerHost\15.20.3"
Found TeamViewer Host [TeamViewer.TeamViewerHost]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl.teamviewer.com/download/version_15x/TeamViewer_Host_Setup.exe
  ██████████████████████████████  19.4 MB / 19.4 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/22502)

### CODE REVIEW

**Comment by ImJoakim** [comment]
You really don't like TeamViewer do ya :p

**Comment by ImJoakim** [comment]
@ryfu-msft

**Review by OfficialEsco — APPROVED** [review]
:o

**Review by quhxl — APPROVED** [review]
magic user powers? :o

**Comment by quhxl** [comment]
This bot is a real comedy show :D

**Comment by OfficialEsco** [comment]
I am even more confused now, @vedantmgoyal2009 have also approved PRs minutes after i did and it moved along...

**Pull request merged**
