### PR TITLE
Libretro.RetroArch version 1.15.0.0

### PR DESCRIPTION
**Pull request by fpscan**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/99790)

### CODE REVIEW

**Comment by fpscan** [comment]
We made some ninja fix

**Comment by BrandonWanHuanSheng** [comment]
Oops! It look like some files is missing.

**Review by BrandonWanHuanSheng — COMMENTED** [review]
Some file is missing. Must have 3 file to commit the change. Detected hash error x86 in "..\manifests\l\Libretro\RetroArch\1.15.0.0\Libretro.RetroArch.installer.yaml"

**Comment by BrandonWanHuanSheng** [comment]
I use aria2c to work on the hashes. Teracopy and Hashdeep use to decrypt the new hashes

**Comment by BrandonWanHuanSheng** [comment]
image
 https://buildbot.libretro.com/stable/1.15.0/windows/x86/RetroArch-Win32-setup.exe
SHA-256=31B3FF5EFF0340DD2FFFC4EE25CF68C66D10B8D0FA255E35ADBD9500F69761F9

**Comment by fpscan** [comment]
okay made some last minute changes, I decided to go with this PR: https://github.com/microsoft/winget-pkgs/pull/99800

**Pull request closed without merging**
