### PR TITLE
New package: Li.CXMLDecompiler version 11

### LINKED ISSUE #201708: [Package Request]: Li.CXMLDecompiler
### How can we help?

None

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://silica.codes/Li/cxml-decompiler/releases
Publisher: Li
Package Name: Li.CXMLDecompiler
Description: a CXML de/compiler for VITA & PS4 CXML formats
Package Version: 11
Installer Url: https://silica.codes/Li/cxml-decompiler/releases/download/v11/CXMLDecompilerv11.zip

### PR DESCRIPTION
**Pull request by LiEnby**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?
closes #201708 

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/201709)

### CODE REVIEW

**Comment by LiEnby** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-12-23 10:45:15.593 [FAIL] Installer failed security check. Url: https://silica.codes/Li/cxml-decompiler/releases/download/v11/CXMLDecompilerv11.zip Result: 0x80004005

(Automated response - build 931.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-12-25 13:23:33.146 [FAIL] Installer failed security check. Url: https://silica.codes/Li/cxml-decompiler/releases/download/v11/CXMLDecompilerv11.zip Result: 0x80004005

(Automated response - build 931.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-12-27 09:48:54.879 [FAIL] Installer failed security check. Url: https://silica.codes/Li/cxml-decompiler/releases/download/v11/CXMLDecompilerv11.zip Result: 0x80004005

(Automated response - build 931.)

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
