### PR TITLE
New version: HulubuluSoftware.AdvancedRenamer version 3.94

### LINKED ISSUE #146055: [Update Request]:     HulubuluSoftware/AdvancedRenamer
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

HulubuluSoftware.AdvancedRenamer

### Package Version

3.94

### Please describe the changes you would like to see

There is a new release (3.94) available.

Download Page Url: https://www.advancedrenamer.com/download

### PR DESCRIPTION
**Pull request by schembriaiden**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.1.0 :rocket:

Resolves: https://github.com/microsoft/winget-pkgs/issues/146055

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/146058)

### CODE REVIEW

**Comment by vikingnope** [comment]
This also worked fine locally:

image

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335123
> 2024-03-22 18:14:48.591 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(267)\WindowsPackageManager.dll!00007FFF93E7A384: (caller: 00007FFF93E7AD01) Exception(1) tid(1a48) 80D02002 
> 2024-03-22 18:14:53.702 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(144)\WindowsPackageManager.dll!00007FFF93E7440C: (caller: 00007FFF93E75C49) Exception(2) tid(1a48) 8A15006D 

(Automated response - build 872.)

**Comment by vikingnope** [comment]
I do not know what the issue is exactly with this manifest, it installs fine on my local machine.

**Comment by stephengillie** [comment]
It might be due to rate limiting. https://github.com/microsoft/winget-pkgs/pull/145261#issuecomment-2018530369

**Comment by vikingnope** [comment]
@stephengillie do you know what the issue is?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335123
> 2024-03-30 01:30:02.517 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(267)\WindowsPackageManager.dll!00007FFAF0C7A384: (caller: 00007FFAF0C7AD01) Exception(1) tid(194c) 80D02002 
> 2024-03-30 01:30:05.895 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(144)\WindowsPackageManager.dll!00007FFAF0C7440C: (caller: 00007FFAF0C75C49) Exception(2) tid(194c) 8A15006D 

(Automated response - build 876.)

**Comment by stephengillie** [comment]
The download doesn't complete when the package manager performs the download, but does work from a browser. This might be a user-agent block, to prevent package managers from downloading but allow users.

**Pull request closed without merging**
