### PR TITLE
New version: Rem0o.FanControl version 198

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#6906](https://github.com/SpecterShell/Dumplings/actions/runs/10125450490).

<details>

<summary>Log</summary>

````
Updated: 197 → 198
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164949)

### CODE REVIEW

**Review by ClintonOffor — CHANGES_REQUESTED** [review]
Hello

**Comment by ClintonOffor** [comment]
Alright

**Comment by ClintonOffor** [comment]
Thanks

**Comment by ClintonOffor** [comment]
Awesome, thanks for the update!

**Comment by ClintonOffor** [comment]
Hello

**Comment by ClintonOffor** [comment]
Awesome, thanks for the update!

**Comment by SpecterShell** [comment]
@stephengillie I didn't see any changes requested in this PR.

**Comment by stephengillie** [comment]
Bot added the label:
> @[microsoft-github-policy-service](https://github.com/apps/microsoft-github-policy-service) microsoft-github-policy-service bot added [Retry-1](https://github.com/microsoft/winget-pkgs/labels/Retry-1) [Changes-Requested](https://github.com/microsoft/winget-pkgs/labels/Changes-Requested) labels [5 days ago](https://github.com/microsoft/winget-pkgs/pull/164949#event-13669325794)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
