### PR TITLE
New version: gopass.gopass-jsonapi version 1.15.15

### PR DESCRIPTION
**Pull request by dpprdan**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---
Sorry, this is identical to #194397 but I messed up my branches.

Output from `.\Tools\SandboxTest.ps1 .\manifests\g\gopass\gopass-jsonapi\1.15.15\`

```ps1
--> Installing WinGet
--> Disabling safety warning when running installers
Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.

--> Configuring Winget
Enabled admin setting 'LocalManifestFiles'.
Enabled admin setting 'LocalArchiveMalwareScanOverride'.

--> Installing the Manifest 1.15.15

Found gopass-jsonapi [gopass.gopass-jsonapi] Version 1.15.15
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Packages
      gopass.gopass
(1/1) Found Gopass CLI [gopass.gopass] Version 1.15.13
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/gopasspw/gopass/releases/download/v1.15.13/gopass-x64-windows-1.15.13.msi
  ██████████████████████████████  7.15 MB / 7.15 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Downloading https://github.com/gopasspw/gopass-jsonapi/releases/download/v1.15.15/gopass-jsonapi-1.15.15-windows-amd64.zip
  ██████████████████████████████  6.03 MB / 6.03 MB
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "gopass-jsonapi"
Path environment variable modified; restart your shell to use the new value.
Successfully installed

--> Refreshing environment variables

--> Comparing ARP Entries

DisplayName    DisplayVersion Publisher      ProductCode                            Scope
-----------    -------------- ---------      -----------                            -----
gopass         1.15.13        gopass         {5716A2AE-2D24-4CCE-AD4A-F396B5BAD080} Machine
gopass-jsonapi 1.15.15        gopass Authors gopass.gopass-jsonapi__DefaultSource   User
```

### CODE REVIEW

**Comment by dpprdan** [comment]
I cannot determine from the [log](https://dev.azure.com/shine-oss/winget-pkgs/_build/results?buildId=30403&view=logs&j=68997d86-8ece-5ae8-3ac5-ccdbfa458731&t=b79910ce-dca5-5e27-ad7f-bd285eecb5a2) what the problem is. 
The application installs fine in the Windows Sandbox, see OP. 
Please advise!

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 899.)

**Comment by dpprdan** [comment]
ping-ing seems to do the trick, (or it did in #194363)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
