### PR TITLE
New version: OSGeo.GeoServer version 2.24.0

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141196)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with: >  Executable C:\Program Files\GeoServer\wrapper\GeoServer.exe returned exit code: 1   (Automated response - build 836.)

**Comment by OfficialEsco** [comment]
Exe requires more parameters
```
PS C:\Users\user> $test = Start-Process -FilePath "C:\Program Files\GeoServer\wrapper\GeoServer.exe" -PassThru
JSL Java Service Launcher by Michael Roeschter (Michael@Roeschter.com)
Version 0.99w January 2020
Command line options:
C:\Program Files\GeoServer\wrapper\GeoServer.exe -install [ini] [...]    to install the service
C:\Program Files\GeoServer\wrapper\GeoServer.exe -configure [ini] [...]  to reconfigure an installed service with new dependencies
C:\Program Files\GeoServer\wrapper\GeoServer.exe -remove [ini] [...]     to remove the service
C:\Program Files\GeoServer\wrapper\GeoServer.exe -debug [ini] [...]      to run as a standalone console app for debugging
C:\Program Files\GeoServer\wrapper\GeoServer.exe -run [ini] [...]        to run as a standalone console app
C:\Program Files\GeoServer\wrapper\GeoServer.exe -runapp [ini] [...]     to run as a standalone console app with no console output
C:\Program Files\GeoServer\wrapper\GeoServer.exe -ini ini                to use the specified init file for running as a service (this option is not useful on command line; only use it if you configure the service option in the registry)
Optional parameters: [...] -console hide | attach | new    'hide' will not show any output on console; 'attach' will show output in current console; 'new' will open a new console window
The configurations file used in the -install and -configure commands will be used for running the service.
Initialization file 'C:\Program Files\GeoServer\wrapper\GeoServer.ini' not found

PS C:\Users\user> $test.ExitCode
1
```

**Comment by stephengillie** [comment]
It looks good for now - I've been waivering these in the past. The difference now is better log filtering. 

Should a `Commands` or `ExpectedReturnCode` or similar be added to future manifests?

**Review by stephengillie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
I don't think `ExpectedReturnCode` works when its related to the automated Validation? `ExpectedReturnCode` defines the Installer Return Codes

Return Code 1 most likely means Installer Requires Administrator to run, which means we should not mess with it, but in this case the executable probably works in 0/1 depending on success

**Pull request merged**
