### PR TITLE
New version: ByteDance.JianyingPro version 2.5.5.6688

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/39123)

### CODE REVIEW

**Review by OfficialEsco — DISMISSED** [review]

**Comment by Trenly** [comment]
Hash matches, but this is the original installation error
image

**Comment by OfficialEsco** [comment]
`>:C` troll package
```
Enter a pull request number: 39123

Manifest validation succeeded.
Found 剪映专业版 [ByteDance.JianyingPro] Version 2.5.5.6688
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://lf3-package.vlabstatic.com/obj/faceu-packages/Jianying_pro_2_5_5_6688_jianyingpro_0.exe
  ██████████████████████████████   333 MB /  333 MB
Installer hash does not match; this cannot be overridden when running as admin

Press any key to continue . . .
```

**Review by OfficialEsco — DISMISSED** [review]
```
PS M:\> winget install -m b\ByteDance\JianyingPro\2.5.5.6688
Found 剪映专业版 [ByteDance.JianyingPro] Version 2.5.5.6688
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://lf3-package.vlabstatic.com/obj/faceu-packages/Jianying_pro_2_5_5_6688_jianyingpro_0.exe
  ██████████████████████████████   333 MB /  333 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

**Comment by OfficialEsco** [comment]
@SpecterShell do you have any insight on this? 🤔

**Comment by SpecterShell** [comment]
I thought there is a cache error somewhere. It works fine here.
```
PS C:\Users\WDAGUtilityAccount\Desktop\manifests> winget install -m .\b\ByteDance\JianyingPro\2.5.5.6688\
Found 剪映专业版 [ByteDance.JianyingPro] Version 2.5.5.6688
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://lf3-package.vlabstatic.com/obj/faceu-packages/Jianying_pro_2_5_5_6688_jianyingpro_0.exe
  ██████████████████████████████   333 MB /  333 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```
But when I tried to download the installer through one of the VPNs to the US, it keeps giving me the same corrupted file as the one the pipeline got.
```
~ » curl 'https://lf3-package.vlabstatic.com/obj/faceu-packages/Jianying_pro_2_5_5_6688_jianyingpro_0.exe' | sha256sum
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  333M  100  333M    0     0  17.2M      0  0:00:19  0:00:19 --:--:-- 19.0M
d5d5d870170fda3c0543c4c7c8306410cd84f9cf732a623c21dd6f19ee62ee81  -
```

**Comment by SpecterShell** [comment]
https://lf3-faceucdn-tos.pstatp.com/obj/faceu-packages/Jianying_pro_2_5_5_6688_jianyingpro_0.exe
You can try this one. The host `lf3-faceucdn-tos.pstatp.com` was used in early versions of this package.

**Comment by OfficialEsco** [comment]
https://lf3-faceucdn-tos.pstatp.com/obj/faceu-packages/Jianying_pro_2_5_5_6688_jianyingpro_0.exe returns `upstream server error`

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
