### PR TITLE
New version: AIMP.AIMP version 5.11.2436

### LINKED ISSUE #113569: [Update Request]: AIMP.AIMP version 5.11.2432
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

AIMP.AIMP

### Package Version

5.11.2432

### Please describe the changes you would like to see

There is a new release (5.11.2432) available.
https://www.aimp.ru/?do=download.file&id=3

### PR DESCRIPTION
**Pull request by Dragon1573**
## Description

- Resolve https://github.com/microsoft/winget-pkgs/issues/113569
- Resolve https://github.com/microsoft/winget-pkgs/issues/117675

## Checks

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/126332)

### CODE REVIEW

**Review by BrandonWanHuanSheng — COMMENTED** [review]
The installer is at risk. 
@Dragon1573 
See here
VT: Detection: 3/72
image

**Comment by Dragon1573** [comment]
I think it's unexpected. An intaller wizard released by official channel should NOT containing any virus.

Shall I ask their Dev Teams for help?

**Comment by stephengillie** [comment]
> 
> 
> I think it's unexpected. An intaller wizard released by official channel should NOT containing any virus.

I feel quite the same. 

> Shall I ask their Dev Teams for help?

This is probably the best course. They have 2 antivirus products reporting an issue, so they should be aware.

**Comment by BrandonWanHuanSheng** [comment]
https://www.aimp.ru/forum/index.php?topic=71857.0

**Pull request closed without merging**
