### PR TITLE
New version: TheDocumentFoundation.LibreOffice.LTS version 7.6.7.2

### LINKED ISSUE #153153: [Update Request]: LibreOffice LTS
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

TheDocumentFoundation.LibreOffice.LTS

### Package Version

7.6.7

### Please describe the changes you would like to see

There is a new release (7.6.7) available.

### PR DESCRIPTION
**Pull request by schembriaiden**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.2.1 :rocket:

Resolves: https://github.com/microsoft/winget-pkgs/issues/153153
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/153156)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by uwekoenig** [comment]
> ### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.2.1 🚀
> 
> Resolves: #153153
> ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/153156)

Please remove the line with the localization because otherwise all users with OS language different than English are not able to install LibreOffice. For details please see https://github.com/microsoft/winget-pkgs/issues/137634

**Comment by vikingnope** [comment]
@uwekoenig, would it be this line?

image

**Comment by uwekoenig** [comment]
Yes, I think so

**Comment by vikingnope** [comment]
Lets try and see

**Comment by uwekoenig** [comment]
@vikingnope: Works great now. Thank you very much.

**Pull request merged**
