### PR TITLE
New version: goplus.gop 1.2.0

### PR DESCRIPTION
**Pull request by cpunion**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137436)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @cpunion,

> This PR's version number 1.2.0 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 1.2.0-test.4, which has 4 parameters.

Is this intentional?

(Automated response - build 694)

**Comment by cpunion** [comment]
> Hi @cpunion,
> 
> > This PR's version number 1.2.0 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 1.2.0-test.4, which has 4 parameters.
> 
> Is this intentional?
> 
> (Automated response - build 694)

@stephengillie These two version numbers both comply with the SemVer ([Semantic Versioning](https://semver.org/)) specification, the format is MAJOR.MINOR.PATCH. The PATCH of `1.2.0-test.4` is `0-test.4`, and the PATCH of `1.2.0` is `0`.

**Comment by cpunion** [comment]
If this version format cannot be supported, I can remove `1.2.0-test.4`.

**Comment by stephengillie** [comment]
> > Hi @cpunion,
> > > This PR's version number 1.2.0 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 1.2.0-test.4, which has 4 parameters.
> > 
> > 
> > Is this intentional?
> > (Automated response - build 694)
> 
> @stephengillie These two version numbers both comply with the SemVer ([Semantic Versioning](https://semver.org/)) specification, the format is MAJOR.MINOR.PATCH. The PATCH of `1.2.0-test.4` is `0-test.4`, and the PATCH of `1.2.0` is `0`.

Does it match the Apps and Features settings page? Versions aren't always semantic, so we just require matching for accuracy.

**Comment by cpunion** [comment]
> Does it match the Apps and Features settings page? Versions aren't always semantic, so we just require matching for accuracy.

It always matches to app's version, run `gop version` can outputs the version info, e.g.:

```shell
c:\> gop version
gop v1.2.0 windows/arm64
```

The `1.2.0-test.4` version outputs:
```shell
c:\> gop version
gop v1.2.0-test.4 windows/arm64
```

**Comment by cpunion** [comment]
@stephengillie  Hi, what's the status of this?

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
