### PR TITLE
Add PortSwigger/BurpSuite-2020.6.

### PR DESCRIPTION
**Pull request by yigitemres**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2413)

### CODE REVIEW

**Comment by yigitemres** [comment]
> 
> 
> Greetings yigitemres
> During installation testing, this application failed to install with out user input. Did you forget to add Silent or SilentWithProgress switches?
> 
> Please investigate a fix and resubmit the Pull Request.

@KevinLaMS 
Installer doesn't have any switches. 😞 If it is not ok sending prs without switches, close the pr. Otherwise, someone have to test it. Btw, fantastic work. 🥂 Thanks all the team and contributors. I'm sure that, winget gonna be improved in the near future.

**Comment by KevinLaMS** [comment]
This item is blocked because it does not have a way to suppress the UI

**Pull request closed without merging**
