### PR TITLE
New package: Rojetto.ReNeo.bone version 1.6.0

### PR DESCRIPTION
**Pull request by libewa**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/186504)

### CODE REVIEW

**Comment by libewa** [comment]
@microsoft-github-policy-service agree

**Comment by libewa** [comment]
ok well defender (technically correctly) flags this as a keylogger, and aborts installation.

**Comment by libewa** [comment]
I have submitted the file for re-evaluation: https://www.microsoft.com/en-us/wdsi/submission/afb97b5c-c0a5-4ccd-a0c1-c6f3ba69a96e

**Comment by stephengillie** [comment]
Verify:
image
The console window displays the active window title. 

image
Trying to run in console window, I discovered that the VM's keyboard input language seems to have changed - from the eszett character I'm guessing German.  

image
This is a tray-based application. 

image
Internet Translation. My laptop's keyboard doesn't seem to have a <kbd>Pause</kbd> button, but clicking the bold menu option returned the VM's input to English. 

image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
