### PR TITLE
Update description for all versions of snoop

### PR DESCRIPTION
**Pull request by lingme**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/5468)

### CODE REVIEW

**Comment by jedieaston** [comment]
@lingme the pipeline fails to validate the PR if you change more than one manifest per PR. Unfortuately, you'll have to break this change up for it to pass.

**Comment by lingme** [comment]
> @lingme the pipeline fails to validate the PR if you change more than one manifest per PR. Unfortuately, you'll have to break this change up for it to pass.

But I just changed the description, can I merge it manually?

**Comment by KevinLaMS** [comment]
sadly there is a block to only allow one PR at a time.  if you make 5 prs it will go through.

**Comment by lingme** [comment]
> sadly there is a block to only allow one PR at a time. if you make 5 prs it will go through.

ok, thanks, will push 5 PRs

**Pull request closed without merging**
