### PR TITLE
New Version: OO-Software.BlueCon version 21.5.12088

### PR DESCRIPTION
**Pull request by oo-cmatuschka**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/162304)

### CODE REVIEW

**Comment by oo-cmatuschka** [comment]
Hi @stephengillie!

Is there anything I can do to make progress here? What could be the reason? It's the first manifest with 'Architecture: neutral'... could that be the reason?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 886.)

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
