### PR TITLE
New version: Corsair.iCUE.5 version 5.21.107

### LINKED ISSUE #193460: [Update Request]: Corsair.iCUE.5
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Corsair.iCUE.5

### Package Version

5.21.107

### Please describe the changes you would like to see

There is a new release: 5.21.107

https://www3.corsair.com/software/CUE_V5/public/modules/windows/installer/Install%20iCUE.exe

### PR DESCRIPTION
**Pull request by VlaDexa**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? Closes #193460

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/193586)

### CODE REVIEW

**Comment by VlaDexa** [comment]
Closes #193460

**Comment by Dragon1573** [comment]
> Closes #193460
>
> _Originally posted in https://github.com/microsoft/winget-pkgs/pull/193586#issuecomment-2496445815_

Hi @VlaDexa, 👋🏼

> [!TIP]
>
> This "close command" is only valid inside the very first comment of the pull request.
>
> Cloud you please edit your [very first comment](https://github.com/microsoft/winget-pkgs/pull/193586#issue-2688701823) and place this "close command" there? 🙏🏼

**Comment by VlaDexa** [comment]
@Trenly I don't think so? I've re-run the `winget install` command once more (after uninstalling iCUE first) on my machine, and it still works. Maybe iCUE has an issue with VM's?

@Dragon1573 Sure, done

**Comment by Dragon1573** [comment]
> @Trenly I don't think so? I've re-run the `winget install` command once more (after uninstalling iCUE first) on my machine, and it still works. Maybe iCUE has an issue with VMs?

It might be? Is _Windows Sandbox_ feature enabled on your device? Could you please manually validate the package with `Tools/SandboxTest.ps1`?

**Comment by Dragon1573** [comment]
@VlaDexa @Trenly, for some reason I'm behind a proxy provided by _Clash for Windows_ version `v0.20.29`, serve as `my.device.local:57890` with protocol `http://` and `socks://`.

I try to launch a _Windows Sandbox_ instance for manual validation, but it seems stuck when I'm performing an interactive installation ...

<details><summary>Console outputs</summary>

```text
21:12:04 D:\...\winget-pkgs  [pr/VlaDexa/193586 +0 ~1 -0 !] 0ms pwsh> .\Tools\SandboxTest.ps1 .\manifests\c\Corsair\iCUE\5\5.21.107\ -WinGetOptions '--interactive'
--> Validating Manifest
清单具有以下未验证的依赖项;确保它们有效：
- 程序包
Microsoft.VCRedist.2015+.x64 [>= 14.38.33130.0]
清单验证成功。
--> Checking Dependencies
--> Starting Windows Sandbox, and:
    - Mounting the following directories:
      - C:\Users\Dragon1573\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\SandboxTest as read-and-write
      - D:\Repository\winget-pkgs as read-and-write
    - Installing WinGet
    - Configuring Winget
      - Installing the Manifest 5.21.107
      - Refreshing environment variables
      - Comparing ARP Entries
```

```text
--> Disabling safety warning when running installers
Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.

--> Configuring Winget
Enabled admin setting 'LocalManifestFiles'.
Enabled admin setting 'LocalArchiveMalwareScanOverride'.

--> Installing the Manifest 5.21.107

Found Corsair iCUE5 Software [Corsair.iCUE.5] Version 5.21.107
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Packages
      Microsoft.VCRedist.2015+.x64 [>= 14.38.33130.0]
(1/1) Found Microsoft Visual C++ 2015-2022 Redistributable (x64) [Microsoft.VCRedist.2015+.x64] Version 14.42.34433.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.visualstudio.microsoft.com/download/pr/c7dac50a-e3e8-40f6-bbb2-9cc4e3dfcabe/1821577409C35B2B9505AC833E246376CC68A8262972100444010B57226F0940/VC_redist.x64.exe
  ██████████████████████████████  24.4 MB / 24.4 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Downloading https://www3.corsair.com/software/CUE_V5/public/modules/windows/installer/Install%20iCUE.exe
  ██████████████████████████████  3.22 MB / 3.22 MB
Successfully verified installer hash
Starting package install...
   |
```

</details>

image

**Comment by Dragon1573** [comment]
If I launch `Tools/SandboxTest.ps1` without `-WingetOptions`, the `winget.exe` install process will soon finish without _iCUE 5_ written to ARP Entries.

Then try to launch a new installation process via `$env:TEMP` folder interactively, it will immediately failed and complaining that "there's another process already running".

It seems that there's something weird blocking the installation in _Windows Sandbox_.

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-11-26_08:47:59 Initial Installer quiet mode enabled with default params 
> 2024-11-26_08:47:59 Setting locale from json file: en_US. 
> 2024-11-26_08:47:59 Failed to open local privacy policy file for reading. 
> 2024-11-26_08:47:59 Failed to read and parse installer embedded payload 
> 2024-11-26_08:47:59 Failed to get mpid value 
> 2024-11-26_08:48:00 Opening file: C:\ProgramData\Corsair\iCUE5 Initial Installer\manager\cuepkg.zip.sha2 
> 2024-11-26_08:48:07 Opening file: C:\ProgramData\Corsair\iCUE5 Initial Installer\manager\cuepkg.zip 
> 2024-11-26_08:48:07 Using bootstrap package from repo: https://www3.corsair.com/software/CUE_V5/public/modules/windows/installerpackage/cuepkg_bootstrap.zip 
> 2024-11-26_08:48:08 Opening file: C:\ProgramData\Corsair\iCUE5 Initial Installer\manager\cuepkg.zip.sha2 
> 2024-11-26_08:48:12 Opening file: C:\ProgramData\Corsair\iCUE5 Initial Installer\manager\cuepkg.zip 
> 2024-11-26_08:48:12 Using bootstrap package from repo: https://www3.corsair.com/software/CUE_V5/public/modules/windows/installerpackage/cuepkg_bootstrap.zip 
> 2024-11-26_08:48:12 Opening file: C:\ProgramData\Corsair\iCUE5 Initial Installer\manager\cuepkg.zip.sha2 
> 2024-11-26_08:48:15 Opening file: C:\ProgramData\Corsair\iCUE5 Initial Installer\manager\cuepkg.zip 
> 2024-11-26_08:48:15 Using bootstrap package from repo: https://www3.corsair.com/software/CUE_V5/public/modules/windows/installerpackage/cuepkg_bootstrap.zip 
> 2024-11-26_08:48:17 Package manager version: iCUE5 Package Manager 1.23.2 
> 2024-11-26_08:48:49 Initial installer version: 1.14.10 
> 2024-11-26_08:48:49 About to execute main installer 
> 2024-11-26_08:48:49 Started the Main Installer 
> 2024-11-26_08:48:49 Quit. 

(Automated response - build 899.)

**Pull request closed without merging**
