### PR TITLE
New package: Fly-io.flyctl version 0.0.450

### PR DESCRIPTION
**Pull request by sitiom**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/94699)

### CODE REVIEW

**Comment by sitiom** [comment]
Manifest validation fails with this error:
```
Manifest validation failed.
Manifest Error: Duplicate relative file path found. [RelativeFilePath]
Manifest Error: Duplicate relative file path found. [RelativeFilePath]
```

`flyctl.exe` expects two aliases: `flyctl` and `fly`. Related to https://github.com/microsoft/winget-cli/issues/2523#issue-1376643992:
> Portable Installer Type doesn't throw an error when two entries have the same `RelativeFilePath`
> * This might be acceptable as long as they have different command aliases?

I guess duplicate relative file path is checked, but not for the exception when they have two different aliases.

**Comment by Trenly** [comment]
1.4 manifests are still waiting for winget 1.4 to hit a majority of users. It will be a few more days until Zip manifests can be merged

**Comment by sitiom** [comment]
Please see https://github.com/microsoft/winget-cli/issues/2523#issuecomment-1405772171

**Comment by sitiom** [comment]
Validation now succeeds locally:
image

**Comment by sitiom** [comment]
- Note: Executable might not work on other commands due to https://github.com/microsoft/winget-cli/issues/2889

**Comment by Trenly** [comment]
> * Note: Executable might not work on other commands due to [Zip binaries installer winget-cli#2711](https://github.com/microsoft/winget-cli/issues/2711)

Seems to work for me
```
--> Installing WinGet
Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.

--> Configuring Winget
Admin setting enabled.

--> Installing the Manifest 0.0.450

Found flyctl [Fly-io.flyctl] Version 0.0.450
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/superfly/flyctl/releases/download/v0.0.450/flyctl_0.0.450_Windows_x86_64.zip
  ██████████████████████████████  24.7 MB / 24.7 MB
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "flyctl"
Command line alias added: "fly"
Path environment variable modified; restart your shell to use the new value.
Successfully installed

--> Refreshing environment variables

--> Comparing ARP Entries

DisplayName DisplayVersion Publisher ProductCode
----------- -------------- --------- -----------
flyctl      0.0.450        Fly.io    Fly-io.flyctl__DefaultSource

PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> flyctl
This is flyctl, the Fly.io command line interface.
```

**Review by Trenly — APPROVED** [review]

**Comment by sitiom** [comment]
> > * Note: Executable might not work on other commands due to [Zip binaries installer winget-cli#2711](https://github.com/microsoft/winget-cli/issues/2711)
> 
> Seems to work for me
> 
> ```
> --> Installing WinGet
> Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.
> 
> --> Configuring Winget
> Admin setting enabled.
> 
> --> Installing the Manifest 0.0.450
> 
> Found flyctl [Fly-io.flyctl] Version 0.0.450
> This application is licensed to you by its owner.
> Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
> Downloading https://github.com/superfly/flyctl/releases/download/v0.0.450/flyctl_0.0.450_Windows_x86_64.zip
>   ██████████████████████████████  24.7 MB / 24.7 MB
> Successfully verified installer hash
> Extracting archive...
> Successfully extracted archive
> Starting package install...
> Command line alias added: "flyctl"
> Command line alias added: "fly"
> Path environment variable modified; restart your shell to use the new value.
> Successfully installed
> 
> --> Refreshing environment variables
> 
> --> Comparing ARP Entries
> 
> DisplayName DisplayVersion Publisher ProductCode
> ----------- -------------- --------- -----------
> flyctl      0.0.450        Fly.io    Fly-io.flyctl__DefaultSource
> 
> PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> flyctl
> This is flyctl, the Fly.io command line interface.
> ```

`wintun.dll` is lazy loaded for certain commands, that would be an issue.

**Comment by denelon** [comment]
@sitom if you'd like us to merge this one, it needs to be converted to a PR from a Draft.

**Pull request merged**
