### PR TITLE
Created new Visual Studio 2022 Community Preview Sku.

### PR DESCRIPTION
**Pull request by edwardskrod**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?
----

## What
- Create new Visual Studio 2022 Community manifests in the 2022\Community\Preview folder.
- Rename the PackageIdentifier
- Keep the current Preview manifest to minimize disruptions to the current experience.

## Why
As part of Microsoft's work to take ownership of the Visual Studio WinGet repo, we are deleting, moving, and adding manifests in support of various Channel/SKU combinations.

Rather than have it's own top level folder under '2022', we would like to maintain one set of 'Preview' manifests under the 'Community' sku folder.  This will provide support for the latest 2022 Community Preview VS.

Furthermore, we are renaming the Preview PackageIdentifier to remove the '-', in keeping with current naming conventions.

Related to https://github.com/microsoft/winget-pkgs/issues/94161

### CODE REVIEW

**Comment by edwardskrod** [comment]
Manifest Error: Schema Error [Schema validation failed. Error context: <root>[PackageIdentifier] Description: Failed to match regex specified by 'pattern' constraint. Error context: <root> Description: Failed to validate against schema associated with property name 'PackageIdentifier'. ] File: Microsoft.VisualStudio.2022.Community.Preview.installer.yaml Manifest Error: Schema Error [Schema validation failed. Error context: <root>[PackageIdentifier] Description: Failed to match regex specified by 'pattern' constraint. Error context: <root> Description: Failed to validate against schema associated with property name 'PackageIdentifier'. ] File: Microsoft.VisualStudio.2022.Community.Preview.locale.en-US.yaml Manifest Error: Schema Error [Schema validation failed. Error context: <root>[PackageIdentifier] Description: Failed to match regex specified by 'pattern' constraint. Error context: <root> Description: Failed to validate against schema associated with property name 'PackageIdentifier'. ] File: Microsoft.VisualStudio.2022.Community.Preview.yaml

**Comment by edwardskrod** [comment]
> 

@denelon  Any idea what's going on here?  This regex is pretty complex.  All I did was change the id from
Microsoft.VisualStudio.2022.Community-Preview to Microsoft.VisualStudio.2022.Community.Preview

^[^\\.\\s\\\\/:\\*\\?\"<>\\|\\x01-\\x1f]{1,32}(\\.[^\\.\\s\\\\/:\\*\\?\"<>\\|\\x01-\\x1f]{1,32}){1,3}$
https://github.com/microsoft/winget-cli/blob/master/schemas/JSON/manifests/v1.2.0/manifest.installer.1.2.0.json

**Comment by edwardskrod** [comment]
> > 
> 
> @denelon Any idea what's going on here? This regex is pretty complex. All I did was change the id from Microsoft.VisualStudio.2022.Community-Preview to Microsoft.VisualStudio.2022.Community.Preview
> 
> ^[^\\.\\s\\\\/:\\*\\?\"<>\\|\\x01-\\x1f]{1,32}(\.[^\\.\\s\\\\/:\\*\\?\"<>\\|\\x01-\\x1f]{1,32}){1,3}$ https://github.com/microsoft/winget-cli/blob/master/schemas/JSON/manifests/v1.2.0/manifest.installer.1.2.0.json

The problem was that we were referencing the 1.0.0 manifest.

I updated to 1.4.0.

**Comment by edwardskrod** [comment]
@denelon I'm not sure what's going on here.  This PR, for the Professional Sku, was successfully validated.  It's basically the same PR.

https://github.com/microsoft/winget-pkgs/pull/95282

**Review by ItzLevvie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
