### PR TITLE
Incus CLI version 0.4.0 / x64 & arm64

### PR DESCRIPTION
**Pull request by nunix**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131752)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 9:38:47 AM: 
> 2023-12-27 09:38:46.135 [FAIL] Installer failed security check. Url: https://github.com/lxc/incus/releases/download/v0.4.0/bin.windows.incus.x86_64.exe Result: 0x80004005

(Automated response - build 489.)

**Comment by stephengillie** [comment]
Hi @nunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

**Comment by nunix** [comment]
@stephengillie hi, thanks a lot for the heads-up and as I'm "just" a community member for Incus, let me tag the right persons to have a look: @stgraber @brauner

**Comment by stgraber** [comment]
Yeah, almost certainly a false positive.

Those upstream binaries are built on a clean Linux system so not much opportunity to pick any malware :)

I remember us occasionally tripping one of the many checks on the Chocolatey side too and they always end up letting it through after a manual check.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
