### PR TITLE
New package: Nickvision.parabolic version 2024.10.1

### PR DESCRIPTION
**Pull request by besdar**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/182928)

### CODE REVIEW

**Comment by besdar** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Verify:
image
image

**Comment by besdar** [comment]
@stephengillie hello. What do you want me to verify? Your screenshots look correct, this is the app I want to see in the winget repository.

**Comment by stephengillie** [comment]
Apologies - I thought I had approved this.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
