### PR TITLE
BetterDiscord.BetterDiscord version 1.1.1

### PR DESCRIPTION
**Pull request by solomoncyj**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/47253)

### CODE REVIEW

**Comment by solomoncyj** [comment]
you know you need discord pre-installed, right?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Requires dependency support.

**Comment by Trenly** [comment]
cc @denelon  - Dependencies; Blocking-Issue

**Comment by solomoncyj** [comment]
.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
You can set this PR to DRAFT until dependency support is in place.

**Review by ItzLevvie — DISMISSED** [review]

**Comment by solomoncyj** [comment]
how do you add dependencies?

**Comment by denelon** [comment]
https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.0.0/installer.md#dependencies

**Comment by solomoncyj** [comment]
.

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
We're waiting for dependency support which would probably be rolling out later this year or next year.

**Pull request closed without merging**
