### PR TITLE
WinGet manifest update for azctx version 2023.11.1: add version

### PR DESCRIPTION
**Pull request by StiviiK**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/125445)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with:
> time=" > 2023-11-14T12:54:27-08:00" level=error msg="azure cli is not installed. please install it and try again. See here: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli" 
Apparently `Microsoft.AzureCLI` is a dependency.

**Comment by StiviiK** [comment]
> Manual Validation ended with:
> 
> > time=" > 2023-11-14T12:54:27-08:00" level=error msg="azure cli is not installed. please install it and try again. See here: [docs.microsoft.com/en-us/cli/azure/install-azure-cli](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli)"
> 
> Apparently `Microsoft.AzureCLI` is a dependency.
> 
> Edit: This message is displayed even with the dependency installed.

Thank you very much for the review.

I have to check that further as the error should only really occur if the az (Azure CLI) command has not been found in the PATH.

**Comment by stephengillie** [comment]
Yes it does. First showing that the Azure CLI is installed, then running the command:
```
PS C:\Users\User\Desktop> az login
A web browser has been opened at https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize. Please continue the login in the web browser. If no web browser is available or if the web browser fails to open, use device code flow with `az login --use-device-code`.
^CTerminate batch job (Y/N)? y
PS C:\Users\User\Desktop> C:\Users\User\AppData\Local\Microsoft\WinGet\Links\azctx.exe
time="
> 2023-11-15T13:02:10-08:00" level=warning msg="AZURE_CONFIG_DIR environment variable is not set. Using default config directory."
time="
> 2023-11-15T13:02:10-08:00" level=warning msg="AZURE_CONFIG_DIR environment variable is not set. Using default config directory."
time="
> 2023-11-15T13:02:10-08:00" level=info msg="If you want to fetch the tenant names, please authenticate the azure cli again using the wraper command: `azctx login`"
Use the arrow keys to navigate: Γåô Γåæ ΓåÆ ΓåÉ  and / toggles search
     | SubscriptionId                       | Tenant

No results
```
It's a bug in my VM scripting that it uses the ManifestVersion line as the bottom line of every file, but here the dependency is below that, so I had to manually add it back into my own process.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
