### PR TITLE
New version: yaser01.MKVMuxingBatchGUI version 2.4.2

### PR DESCRIPTION
**Pull request by ghost**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136748)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Program Files\MKV Muxing Batch GUI\MKV Muxing Batch GUI.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Program Files\MKV Muxing Batch GUI\MKV Muxing Batch GUI.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Program Files\MKV Muxing Batch GUI\Resources\Tools\Windows64\mkvmerge.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Program Files\MKV Muxing Batch GUI\Resources\Tools\Windows64\mkvmerge.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform. Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Program Files\MKV Muxing Batch GUI\Resources\Tools\Windows64\mkvpropedit.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Program Files\MKV Muxing Batch GUI\Resources\Tools\Windows64\mkvpropedit.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.

(Automated response - build 669.)

**Comment by drshtmstry** [comment]
> Automatic Validation ended with:
> 
> > Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Program Files\MKV Muxing Batch GUI\MKV Muxing Batch GUI.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Program Files\MKV Muxing Batch GUI\MKV Muxing Batch GUI.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Program Files\MKV Muxing Batch GUI\Resources\Tools\Windows64\mkvmerge.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Program Files\MKV Muxing Batch GUI\Resources\Tools\Windows64\mkvmerge.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform. Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Program Files\MKV Muxing Batch GUI\Resources\Tools\Windows64\mkvpropedit.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Program Files\MKV Muxing Batch GUI\Resources\Tools\Windows64\mkvpropedit.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.
> 
> (Automated response - build 669.)

No issue. Working fine.

Screenshot 2024-01-27 212713
Screenshot (15)
Screenshot (16)
Screenshot (17)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Program Files\MKV Muxing Batch GUI\MKV Muxing Batch GUI.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Program Files\MKV Muxing Batch GUI\MKV Muxing Batch GUI.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Program Files\MKV Muxing Batch GUI\Resources\Tools\Windows64\mkvmerge.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Program Files\MKV Muxing Batch GUI\Resources\Tools\Windows64\mkvmerge.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform. Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Program Files\MKV Muxing Batch GUI\Resources\Tools\Windows64\mkvpropedit.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Program Files\MKV Muxing Batch GUI\Resources\Tools\Windows64\mkvpropedit.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.

(Automated response - build 674.)

**Comment by stephengillie** [comment]
Hi @drshtmstry,

> This PR's version number 2.4.2 has 3 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version 2.3, which has 2 parameters.

Is this intentional?

(Automated response - build 674)

**Comment by stephengillie** [comment]
Hi @drshtmstry,

This manifest adds Apps and Features entries that aren't present in previous PR versions. Should these entries also be added to the previous versions?

(Automated response - build 674.)

**Comment by drshtmstry** [comment]
> Hi @drshtmstry,
> 
> > This PR's version number 2.4.2 has 3 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version 2.3, which has 2 parameters.
> 
> Is this intentional?
> 
> (Automated response - build 674)

It is as per releases in GitHub.
https://github.com/yaser01/mkv-muxing-batch-gui/releases

**Comment by drshtmstry** [comment]
> Hi @drshtmstry,
> 
> This manifest adds Apps and Features entries that aren't present in previous PR versions. Should these entries also be added to the previous versions?
> 
> (Automated response - build 674.)

https://github.com/microsoft/winget-pkgs/pull/137082

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
