### PR TITLE
Remove version: Wildy.bobonslaught version faf57

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/174021)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: - https://files.gamebanana.com/mods/bobsonslaught_faf57.zip 
Invalid URI: The URI scheme is not valid.

(Automated message - build 922)

**Comment by stephengillie** [comment]
URL: https://files.gamebanana.com/mods/bobsonslaught_faf57.zip 
Status Code: 200

(Automated message - build 895)

**Comment by stephengillie** [comment]
URL: https://files.gamebanana.com/mods/bobsonslaught_faf57.zip 
Status Code: 200

(Automated message - build 896)

**Comment by stephengillie** [comment]
URL: https://files.gamebanana.com/mods/bobsonslaught_faf57.zip 
Status Code: 200

(Automated message - build 896)

**Comment by stephengillie** [comment]
URL: https://files.gamebanana.com/mods/bobsonslaught_faf57.zip 
Status Code: 200

(Automated message - build 896)

**Comment by stephengillie** [comment]
URL: https://files.gamebanana.com/mods/bobsonslaught_faf57.zip 
Status Code: 200

(Automated message - build 896)

**Comment by stephengillie** [comment]
URL: https://files.gamebanana.com/mods/bobsonslaught_faf57.zip 
Status Code: 200

(Automated message - build 896)

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
