### PR TITLE
Update version: Microsoft.PowerToys version 0.73.0

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/118711)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @crutkas,

Could you approve this PR?

**Comment by crutkas** [comment]
@vedantmgoyal2009 can you work with me to get this built into our pipeline via our github action?  love the work but i really want to be able to show supply chain e2e comes from us.

**Comment by vedantmgoyal2009** [comment]
Hello @cruktas, I just saw your comment on my previous PR (https://github.com/microsoft/winget-pkgs/pull/115163#issuecomment-1670601759) and this PR. The automation uses [Komac](https://github.com/russellbanks/Komac), a WinGet manifest creator built by one of the winget's community moderators (@russellbanks). If you are okay to integrate a non-Microsoft project into Power Toys CI, I'm happy to update the [package-submissions workflow](https://github.com/microsoft/PowerToys/blob/main/.github/workflows/package-submissions.yml).

**Comment by Trenly** [comment]
Stale PR; Please update or close
[Policy] Needs-Author-Feedback

**Comment by vedantmgoyal2009** [comment]
Hello, @crutkas, I'm waiting for your reply

**Comment by stephengillie** [comment]
Duplicate of https://github.com/microsoft/winget-pkgs/pull/118597

**Pull request closed without merging**
