### PR TITLE
Update Markdown Monster to 1.26.6

### PR DESCRIPTION
**Pull request by RickStrahl**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/9521)

### CODE REVIEW

**Comment by denelon** [comment]
@RickStrahl try:
```YAML
Tags:
 - markdown
 - editor
 - documentation
 - weblog
```

instead of:
```YAML
Tags:
- markdown editor documentation weblog
```

**Comment by denelon** [comment]
I would also use the value in "Description" for "ShortDescription" and remove the "Description" key. The Windows Package Manager displays "ShortDescription" in `winget show`.

**Comment by denelon** [comment]
YAML is sensitive to white space. The spacing for nested elements beginning with a hyphen is probably also triggering validation errors.

**Comment by RickStrahl** [comment]
I believe this is a duplicate and was already merged from another PR

**Pull request closed without merging**
