### PR TITLE
JonasJohn.RemoveEmptyDirectories version 2.2

### PR DESCRIPTION
**Pull request by Masamune3210**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/27049#event-5258340030

**Comment by Masamune3210** [comment]
This doesnt require user input, it comes up flashes progress and then completes without anything other than granting a UAC prompt

**Comment by Masamune3210** [comment]
Just tested it on a fresh VM running Windows 11, installs without user input as expected

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
This package has a dependency which is why it's not installing:
image

Dependency support is not currently in Windows Package Manager yet.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
image

**Comment by Masamune3210** [comment]
Yeah I know, just going through and adding the Dependencies tag for when support is finally added

**Comment by Masamune3210** [comment]
Not sure how to handle .NET 3.5 since its bundled with Windows, just disabled by default. Manual install package doesn't seem to install on 11 at least

**Comment by Trenly** [comment]
Newer version is available in winget through #30001

**Pull request closed without merging**
