### PR TITLE
MAMPGmbH.MAMP&MAMPPRO version 5.0.5.3998

### PR DESCRIPTION
**Pull request by vladabuba**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/59437)

### CODE REVIEW

**Review by ItzLevvie — COMMENTED** [review]
You should regenerate manifest based on `MAMP.MAMP` PackageIdentifier

https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/MAMP/MAMP

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/59437#pullrequestreview-960478977

**Review by ghost — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/59437#pullrequestreview-960479246

**Review by ItzLevvie — APPROVED** [review]
Just approving for filtering purposes.

It won't go through unless you make the requested changes and then it gets reapproved by someone else.

**Pull request closed without merging**
