### PR TITLE
New version: angryziber.AngryIPScanner version 3.8.1

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/41478)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
@Trenly my VM is so dirty that i have 10 Java's installed and i still get this 😁 (Levvie's script could have broken it tho)
VirtualBoxVM_oUWSPNrdom

**Comment by ItzLevvie** [comment]
> (Levvie's script could have broken it tho)

It's because I made the script delete ARP entries whenever you validate a new PR (after your first one).

It'll work fine if you manually installed the OpenJDK and Angry IP Scanner.

**Comment by OfficialEsco** [comment]
> > (Levvie's script could have broken it tho)
> 
> It's because I made the script delete ARP entries whenever you validate a new PR for now since using the comparing ARP entries code from the `SandboxTest.ps1` script doesn't seem to work too well for validating 30+ apps on a VM.
> 
> It'll work fine if you manually installed OpenJDK (i.e. Eclipse Temurin JDK with Hotspot 17) and Angry IP Scanner.

Did some manual testing at it actually works yeah, i did try with dependencies on 3.8.0 and it still failed which is weird, retested manually and it did work there too with Microsoft JDK 17

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Fixed in newer releases of Angry IP Scanner.

**Pull request closed without merging**
