### PR TITLE
Update version: SpikeHD.Dorion version 4.1.1

### PR DESCRIPTION
**Pull request by headquarter8302**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136725)

### CODE REVIEW

**Comment by headquarter8302** [comment]
Whoops, the folder version didn't change

**Comment by headquarter8302** [comment]
```log
Manifest Error: Field usage requires verified publishers. [Icons]
```
Do they need to be from a specific URL or domain?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-27T07:32:27.2652068Z ##[error] Manifest Error: Field usage requires verified publishers. [Icons]

(Automated response - build 669.)

**Comment by headquarter8302** [comment]
What counts as a verified publisher?

**Comment by headquarter8302** [comment]
You know what, not worth the trouble

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Duplicate of https://github.com/microsoft/winget-pkgs/pull/136712

**Pull request closed without merging**
