### PR TITLE
Updated Albayan to version 1.2.1

### PR DESCRIPTION
**Pull request by MesterPerfect**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/162954)

### CODE REVIEW

**Review by MesterPerfect — COMMENTED** [review]
Added publisher information, official website link, etc

**Review by Trenly — CHANGES_REQUESTED** [review]
Only one package version can be modified per pull request

**Comment by MesterPerfect** [comment]
> Hello @MesterPerfect,
> 
> The package manager bot determined changes have been requested to your PR.
> 
> Template: msftbot/changesRequested

/Approve

**Comment by MesterPerfect** [comment]
> Hello @MesterPerfect,
> 
> The package manager bot determined changes have been requested to your PR.
> 
> Template: msftbot/changesRequested

/approve

**Comment by MesterPerfect** [comment]
@stephengillie e

**Comment by MesterPerfect** [comment]
@stephengillie

**Comment by stephengillie** [comment]
Hi @MesterPerfect,

This PR appears to modify 3 manifest versions - 2 for this package, and 1 for `SoundTranscriber` - is this intentional? 

image

**Comment by MesterPerfect** [comment]
> Hi @MesterPerfect,
> 
> This PR appears to modify 3 manifest versions - 2 for this package, and 1 for `SoundTranscriber` - is this intentional?
> 
> image

Yes, this is completely intentional because I've downloaded several consecutive updates to my software over the past three days.

**Comment by stephengillie** [comment]
Oh - we have a limit of 1 manifest change (add/modify/remove) per PR. While there is an advanced form of PR that adds 1 version and removes another, there isn't any which allows adding multiple versions. But if these changes are spread across 2 more PRs (and branches), then all 3 should be able to pass this check.

**Comment by stephengillie** [comment]
>  The pull requests contains invalid file 'manifests\t\tecwindow\Albayan\1.2.1\chrome.exe'. Only yaml extension allowed.

**Pull request closed without merging**
