### PR TITLE
New package: vivainio.RoughGrep version 3.14.3

### LINKED ISSUE #182569: [Package Request]: RoughGrep
### How can we help?

None

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/vivainio/RoughGrep/releases/tag/v3.14.3
Publisher: Ville Vainio
Package Name: vivainio.RoughGrep
Description: User interface for RipGrep
Package Version: 3.14.3
Installer Url: https://github.com/vivainio/RoughGrep/releases/download/v3.14.3/RoughGrep-3.14.3.zip

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #182569

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

## Manual validation

Image
Image

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/196149)

### CODE REVIEW

**Comment by Dragon1573** [comment]
@Trenly @stephengillie,

The <https://github.com/microsoft/winget-pkgs/labels/zip-binary> label should be removed both in this pull request and the related issue #182569 🙏🏼

**Comment by Trenly** [comment]
> @Trenly @stephengillie,
> 
> The [ zip-binary](https://github.com/microsoft/winget-pkgs/labels/zip-binary) Depends on library files that aren't available via symlink label should be removed both in this pull request and the related issue #182569 🙏🏼

Why? It does depend on DLLs in the zip file

**Comment by stephengillie** [comment]
Verify:
image
The version number displayed by the application seems very different from the version number written to the Registry. Should a `DisplayVersion` be used here?

**Comment by Dragon1573** [comment]
> The version number displayed by the application seems very different from the version number written to the Registry. Should a `DisplayVersion` be used here?

**NO**. `rg.exe` is provided by package identifier `BurntSushi.ripgrep.MSVC`. `rgg.exe` is our target executable. Screenshots are shown in [Manual validation](https://github.com/microsoft/winget-pkgs/pull/196149#issue-2716730876) section.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
