### PR TITLE
Remove version: DATV-Express.DATV-Express version 1.25LP14

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/138367)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-08T16:45:29.1475040Z Processing manifest: manifests\d\DATV-Express\DATV-Express\1.25LP14
 2024-02-08T16:45:29.1476232Z -----------------------------------------------------
 2024-02-08T16:45:29.1477141Z Status: Started
 2024-02-08T16:45:29.1477945Z Manifest file is Deleted
 2024-02-08T16:45:29.2082955Z Status: Completed
 2024-02-08T16:45:29.2090807Z ##[error] Result: Failed
 2024-02-08T16:45:29.2187776Z ##[error] Sequence contains no elements
 2024-02-08T16:45:29.2906335Z ##[error]Manifest Validation Failed

(Automated response - build 716.)

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 716.)

**Comment by stephengillie** [comment]
URL: https://www.datv-express.com/uploads/Software/Windows_setup_datvexpress_dvb_transmitter_v1.25LP14.zip 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 716)

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

This is the last version of this package in the repo. Is it available from another source?

(Automation didn't catch this one.)

**Pull request merged**
