### PR TITLE
Moved: PostgreSQL.PostgreSQL.10 version 10

### PR DESCRIPTION
**Pull request by SpecterShell**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/155128)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-05-28 10:40:05.651 [CLI ] Failed to download, waiting a bit and retry. Url: https://get.enterprisedb.com/postgresql/postgresql-10.23-1-windows-x64.exe 
> 2024-05-28 10:40:06.164 [CORE] Downloading to path: C:\Users\User\AppData\Local\Temp\WinGet\PostgreSQL.PostgreSQL.10.10\da3abe948ddd37024bdedac7c90860d13707899afd2b5fbcab6f1013dc4c0ae7 
> 2024-05-28 10:40:06.165 [CORE] DeliveryOptimization downloading from url: https://get.enterprisedb.com/postgresql/postgresql-10.23-1-windows-x64.exe 
> 2024-05-28 10:40:07.411 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000 
> 2024-05-28 10:40:07.411 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFD8694F180: (caller: 00007FFD8694FACC) Exception(3) tid(10b4) 80190193 Forbidden (403).   
> 2024-05-28 10:40:07.421 [CORE] Started applying motw to C:\Users\User\AppData\Local\Temp\WinGet\PostgreSQL.PostgreSQL.10.10\da3abe948ddd37024bdedac7c90860d13707899afd2b5fbcab6f1013dc4c0ae7 with zone: 3 
> 2024-05-28 10:40:07.422 [CORE] Finished applying motw 
> 2024-05-28 10:40:07.422 [CORE] WinINet downloading from url: https://get.enterprisedb.com/postgresql/postgresql-10.23-1-windows-x64.exe 
> 2024-05-28 10:40:07.707 [CORE] Download request failed. Returned status: 403 
> 2024-05-28 10:40:07.707 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFD869491E2: (caller: 00007FFD8694AA19) Exception(4) tid(10b4) 80190193 Forbidden (403).      Msg:[Download request status is not success.]   
> 2024-05-28 10:40:07.711 [CLI ] Caught wil::ResultException: C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFD869491E2: (caller: 00007FFD8694AA19) Exception(4) tid(10b4) 80190193 Forbidden (403).      Msg:[Download request status is not success.]   

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 10:55:10 AM: 
> 2024-05-28 10:54:56.469 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000 10:55:10 AM: 
> 2024-05-28 10:54:56.469 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFD8739F180: (caller: 00007FFD8739FACC) Exception(1) tid(1a60) 80190193 Forbidden (403). 10:55:10 AM: 
> 2024-05-28 10:54:57.557 [CORE] Download request failed. Returned status: 403 10:55:10 AM: 
> 2024-05-28 10:54:57.557 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFD873991E2: (caller: 00007FFD8739AA19) Exception(2) tid(1a60) 80190193 Forbidden (403). 10:55:10 AM: 
> 2024-05-28 10:54:57.695 [CLI ] Failed to download, waiting a bit and retry. Url: https://get.enterprisedb.com/postgresql/postgresql-10.23-1-windows-x64.exe 10:55:10 AM: 
> 2024-05-28 10:54:58.844 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000 10:55:10 AM: 
> 2024-05-28 10:54:58.844 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFD8739F180: (caller: 00007FFD8739FACC) Exception(3) tid(1a60) 80190193 Forbidden (403). 10:55:10 AM: 
> 2024-05-28 10:54:59.032 [CORE] Download request failed. Returned status: 403 10:55:10 AM: 
> 2024-05-28 10:54:59.032 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFD873991E2: (caller: 00007FFD8739AA19) Exception(4) tid(1a60) 80190193 Forbidden (403).

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2145844845
> 2024-05-28 11:19:15.354 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-05-28 11:19:15.401 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFB6FE7A465: (caller: 00007FFB6FE7AD01) Exception(1) tid(74c) 80190193 Forbidden (403).
> 2024-05-28 11:19:15.918 [CORE] Download request failed. Returned status: 403
> 2024-05-28 11:19:15.918 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFB6FE743D6: (caller: 00007FFB6FE75C49) Exception(2) tid(74c) 80190193 Forbidden (403).
> 2024-05-28 11:19:16.008 [CLI ] Failed to download, waiting a bit and retry. Url: https://get.enterprisedb.com/postgresql/postgresql-10.23-1-windows-x64.exe
> 2024-05-28 11:19:16.654 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-05-28 11:19:16.654 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFB6FE7A465: (caller: 00007FFB6FE7AD01) Exception(3) tid(74c) 80190193 Forbidden (403).
> 2024-05-28 11:19:16.738 [CORE] Download request failed. Returned status: 403
> 2024-05-28 11:19:16.738 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFB6FE743D6: (caller: 00007FFB6FE75C49) Exception(4) tid(74c) 80190193 Forbidden (403).

Automated error analysis suggests 0x80190193 may mean Forbidden (403)

Automated error analysis suggests -2145844845 may mean Forbidden (403).

(Automated response - build 881.)

**Review by Trenly — APPROVED** [review]

**Pull request merged**
