### PR TITLE
AntibodySoftware.WizTree version 4.03

### PR DESCRIPTION
**Pull request by Masamune3210**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/28351)

### CODE REVIEW

**Comment by Masamune3210** [comment]
I dont know whats going on with this manifest and wingetcreate but I keep having to manually update it rather than just using wingetcreate update

**Review by ItzLevvie — APPROVED** [review]

**Review by jedieaston — APPROVED** [review]

**Comment by ryfu-msft** [comment]
> I dont know whats going on with this manifest and wingetcreate but I keep having to manually update it rather than just using wingetcreate update

Copied over from an [earlier PR](https://github.com/microsoft/winget-pkgs/pull/28105) that you made where you also had issues.

Hey @Masamune3210, 

I noticed you had some issues with the update command for Winget-Create. The reason for the mismatch is that the existing manifest is looking for a neutral inno installer, but we detected the installer to be an x86 inno.

Fortunately, in our latest release of Winget-Create, we added an interactive update flag for you to manually fix those mismatches by running

wingetcreate update AntibodySoftware.WizTree -v <Version> -i
We hope you try it out, and feel free to tag me or create a new GitHub issue if it doesn't behave as you expected.

Thanks!

**Comment by Masamune3210** [comment]
Will do next update, sorry didn't get the message until now!

**Comment by Masamune3210** [comment]
https://github.com/microsoft/winget-create/issues/176#issue-1007114096 @ryfu-msft

**Pull request merged**
