### PR TITLE
New version: NI.ni-packagemanager version 24.0.0

### PR DESCRIPTION
**Pull request by lars-nvhgroup**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140139)

### CODE REVIEW

**Comment by stephengillie** [comment]
This manifest contains a term that is blocked:

>   Silent: --quiet --accept-eulas   SilentWithProgress: --passive --accept-eulas - AgreementLabel: End User License Agreement (EULA)

(Automated response - build 763.)

**Comment by lars-whta** [comment]
It was accepted for 23.8.0.

**Comment by lars-whta** [comment]
> This manifest contains a term that is blocked:
> 
> >   Silent: --quiet --accept-eulas   SilentWithProgress: --passive --accept-eulas - AgreementLabel: End User License Agreement (EULA)
> 
> (Automated response - build 763.)

https://github.com/microsoft/winget-pkgs/pull/139458

**Comment by stephengillie** [comment]
Hi @lars-whta,

Sorry for causing concern - I haven't updated my word filter check for the new Agreements section, so I'm doing this now. I'm realizing that I need to make a list of packages that have already had their Agreement approved and can skip this check if the URL is the same. So I'm building this into my approval automation, and you're quicker to reply than I was to fix my automated comment.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
