### PR TITLE
Fix version of ImageLine.FLStudio (remove build number)

### PR DESCRIPTION
**Pull request by w3lld0ne**
- [ x ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ x ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ x ] This PR only modifies one (1) manifest
- [ x ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ x ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ x ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

I've found out Image-Line began to include the version of installed product, but they use only partial 'major.minor.patch' string, excluding build number. I've updated the format here because now FLStudio constantly tries to update itself, and this is no longer hidden under `--include-unknown` flag.

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/103019)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
The version folder also needs to be updated

EDIT: Please ignore this. I'm on mobile so I didn't see the updated folder.

**Comment by w3lld0ne** [comment]
> The version folder also needs to be updated

it is renamed as well

**Comment by ItzLevvie** [comment]
[Policy] Reset-Feedback

**Review by ItzLevvie — APPROVED** [review]

**Comment by BrandonWanHuanSheng** [comment]
It look like previous also having the same problem.

**Pull request merged**
