### PR TITLE
Remove version: GPXSee v13.12

### LINKED ISSUE #135780: [Update Request]: GPXSee 13.15
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

tumic0.GPXSee

### Package Version

13.15

### Please describe the changes you would like to see

GPXSee 13.15 available. Versions 13.12 and 13.13 have been removed from the download server.

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---
- Resolves https://github.com/microsoft/winget-pkgs/issues/135780

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135795)

### CODE REVIEW

**Comment by drshtmstry** [comment]
> Sequence contains no elements

- #133371

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 638.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-23T03:47:15.7629209Z Processing manifest: manifests\t\tumic0\GPXSee\13.12
 2024-01-23T03:47:15.7641218Z -----------------------------------------------------
 2024-01-23T03:47:15.7645605Z Status: Started
 2024-01-23T03:47:15.7654398Z Manifest file is Deleted
 2024-01-23T03:47:16.0183540Z Status: Completed
 2024-01-23T03:47:16.0197933Z ##[error] Result: Failed
 2024-01-23T03:47:16.0251015Z ##[error] Sequence contains no elements
 2024-01-23T03:47:16.0832962Z ##[error]Manifest Validation Failed

(Automated response - build 638.)

**Comment by stephengillie** [comment]
URL: https://sourceforge.net/projects/gpxsee/files/Windows/GPXSee-13.12_x64.exe 
Status Code: 200

(Automated message - build 647)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
