### PR TITLE
Create seriousbit.netbalancer.yaml (#19821)

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/19825)

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
Closes #19821

**Comment by vedantmgoyal2009** [comment]
@quhxl please help to fix this pull request, it successfully ran on the local computer but it is failing in azure pipelines

**Comment by vedantmgoyal2009** [comment]
@OfficialEsco @quhxl anyone please help to fix this pull request, it successfully ran on the local computer but it is failing in azure pipelines

**Comment by quhxl** [comment]
> @OfficialEsco @quhxl anyone please help to fix this pull request, it successfully ran on the local computer but it is failing in azure pipelines

https://github.com/microsoft/winget-pkgs/issues/19821#issuecomment-874018116

**Comment by vedantmgoyal2009** [comment]
Thanks for replying... I didn't see that he has posted a reply there.

**Comment by vedantmgoyal2009** [comment]
Donkey Bot

**Review by ItzLevvie — COMMENTED** [review]
image

**Comment by vedantmgoyal2009** [comment]
Yes, I saw Esco's comment here: https://github.com/microsoft/winget-pkgs/issues/19821#issuecomment-874018116

**Pull request closed without merging**
