### PR TITLE
New package: Yuanli.uTools version 4.4.1

### PR DESCRIPTION
**Pull request by SpecterShell**
😅

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/146114)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @SpecterShell,

I wasn't able to navigate from the `PackageUrl` to the `InstallerUrl`.

**Comment by SpecterShell** [comment]
> Hi @SpecterShell,
> 
> I wasn't able to navigate from the `PackageUrl` to the `InstallerUrl`.

The `InstallerUrl` is indeed present on the `PackageUrl` and just redirects to another URL when accessing.

**Comment by stephengillie** [comment]
The website is constructed in such a way as to obfuscate the URL. But the `InstallerUrl`s are on the same domain as the `PackageUrl`. And both result in the same download URL.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
