### PR TITLE
Update Logitech G Hub checksum

### PR DESCRIPTION
**Pull request by njensen20**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3781)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
Looks like you have to click INSTALL.  :( 
image

**Comment by njensen20** [comment]
After searching forums, looking through previous manifests, and trying random switches, it appears this has no way to execute silently.

**Comment by OfficialEsco** [comment]
Logitech does indeed not use silent switches, Chocolatey uses AHK to silent install Logitech Software.

@KevinLaMS @denelon accepted the original manifest, either the manifest needs to be deleted or you guys need to accept some manifests without silent installers.

**Comment by OfficialEsco** [comment]
@denelon i think its better to close this one since the manifest is outdated + the hash is defiantly wrong

**Pull request closed without merging**
