### PR TITLE
New package: Jigsaw.OutlineClient version 1.12.1

### PR DESCRIPTION
**Pull request by rakleed**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/144081)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 870.)

**Comment by stephengillie** [comment]
Hi @rakleed,

The installation is unattended, but installs a driver which isn't unattended:
image
Unfortunately, installer switches are not usually provided for this situation. Are you aware of an installer switch to have the driver silently install as well?

**Comment by rakleed** [comment]
Are these options not suitable for Winget?

- https://forums.openvpn.net/viewtopic.php?t=28084
- https://superuser.com/q/946105

**Comment by stephengillie** [comment]
> Are these options not suitable for Winget?
> 
> * https://forums.openvpn.net/viewtopic.php?t=28084
> * https://superuser.com/q/946105

I don't see why they wouldn't be suitable for WinGet. But they'd have to be added to the installer by the developer.

**Comment by rakleed** [comment]
> Edit: Would Insecure.Npcap work?

What are you talking about? I could find such solution.

**Comment by rakleed** [comment]
> Edit: Would Insecure.Npcap work?

What are you talking about? I couldn't find such solution.

**Pull request closed without merging**
