### PR TITLE
Location required for AutoHotkey

### LINKED ISSUE #95829: [Package Issue]: AutoHotkey.AutoHotkey
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The installer will use the folder `%USERPROFILE%\AppData\Local\Temp\WinGet\UX\` as destination. Since this is within the `Temp` folder, eventually the installed contents will end up deleted and the program will fail to work correctly.

### Steps to reproduce

`winget install AutoHotkey.AutoHotkey`

Check the target of the AutoHotKey shortcuts in start menu and the program associated with ahk file extension.

### Actual behavior

Program installation target is a temporary directory.

### Expected behavior

Program installation target should be a permanent directory

### Environment

```shell
Windows Package Manager v1.4.10173
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.2486
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0
```

### Screenshots and Logs

```
2023-02-07 18:41:38.459 [CLI ] Generated temp download path: C:\Users\mmv\AppData\Local\Temp\WinGet\AutoHotkey.AutoHotkey.2.0.2\9c8b1aecaf1bdded80bec98ec5ab5b9b9754cbce9439dd9eacc7d1774d1438f8
2023-02-07 18:41:38.461 [CORE] Downloading to path: C:\Users\mmv\AppData\Local\Temp\WinGet\AutoHotkey.AutoHotkey.2.0.2\9c8b1aecaf1bdded80bec98ec5ab5b9b9754cbce9439dd9eacc7d1774d1438f8
2023-02-07 18:41:38.463 [CORE] DeliveryOptimization downloading from url: https://github.com/AutoHotkey/AutoHotkey/releases/download/v2.0.2/AutoHotkey_2.0.2_setup.exe
2023-02-07 18:41:41.650 [CORE] Download completed.
2023-02-07 18:41:46.241 [CORE] Started applying motw to C:\Users\mmv\AppData\Local\Temp\WinGet\AutoHotkey.AutoHotkey.2.0.2\9c8b1aecaf1bdded80bec98ec5ab5b9b9754cbce9439dd9eacc7d1774d1438f8 with zone: 3
2023-02-07 18:41:46.250 [CORE] Finished applying motw
2023-02-07 18:41:46.250 [CLI ] Installer hash verified
2023-02-07 18:41:46.251 [CORE] Started applying motw to C:\Users\mmv\AppData\Local\Temp\WinGet\AutoHotkey.AutoHotkey.2.0.2\9c8b1aecaf1bdded80bec98ec5ab5b9b9754cbce9439dd9eacc7d1774d1438f8 with zone: 2
2023-02-07 18:41:46.268 [CORE] Finished applying motw
2023-02-07 18:41:46.269 [CLI ] Successfully renamed downloaded installer. Path: C:\Users\mmv\AppData\Local\Temp\WinGet\AutoHotkey.AutoHotkey.2.0.2\AutoHotkey_2.0.2_setup.exe
2023-02-07 18:41:46.269 [REPO] Creating PredefinedInstalledSource with filter [ARP]
2023-02-07 18:41:46.269 [REPO] Creating new SQLite Index [4294967295.4294967295] at ':memory:'
2023-02-07 18:41:46.269 [SQL ] Opening SQLite connection #5: ':memory:' [6, 0]
2023-02-07 18:41:46.374 [REPO] Reading MSI UpgradeCodes
2023-02-07 18:41:46.454 [REPO] Examining ARP entries for Machine | X64
2023-02-07 18:41:46.592 [REPO] Examining ARP entries for Machine | X86
2023-02-07 18:41:46.743 [REPO] Reading MSI UpgradeCodes
2023-02-07 18:41:46.828 [REPO] Examining ARP entries for User | X64
2023-02-07 18:41:46.901 [CLI ] Installer args: /user /silent
2023-02-07 18:41:46.903 [CLI ] Starting: 'C:\Users\mmv\AppData\Local\Temp\WinGet\AutoHotkey.AutoHotkey.2.0.2\AutoHotkey_2.0.2_setup.exe' with arguments '/user /silent'
2023-02-07 18:41:54.884 [REPO] Creating PredefinedInstalledSource with filter [ARP]
2023-02-07 18:41:54.884 [REPO] Creating new SQLite Index [4294967295.4294967295] at ':memory:'
2023-02-07 18:41:54.884 [SQL ] Opening SQLite connection #6: ':memory:' [6, 0]
2023-02-07 18:41:55.008 [REPO] Reading MSI UpgradeCodes
2023-02-07 18:41:55.117 [REPO] Examining ARP entries for Machine | X64
2023-02-07 18:41:55.261 [REPO] Examining ARP entries for Machine | X86
2023-02-07 18:41:55.430 [REPO] Reading MSI UpgradeCodes
2023-02-07 18:41:55.520 [REPO] Examining ARP entries for User | X64
2023-02-07 18:41:55.579 [CLI ] During package install, 1 changes to ARP were observed, 1 matches were found for the package, and 1 packages were in both
2023-02-07 18:41:55.579 [CLI ] The entry determined to be associated with the package is 'AutoHotkey (user)', with publisher 'AutoHotkey Foundation LLC'
2023-02-07 18:41:55.613 [REPO] Opening SQLite Index for ReadWrite at 'C:\Users\mmv\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db'
2023-02-07 18:41:55.613 [SQL ] Opening SQLite connection #7: 'C:\Users\mmv\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Microsoft.Winget.Source_8wekyb3d8bbwe\installed.db' [2, 0]
2023-02-07 18:41:55.617 [REPO] Opened SQLite Index with version [1.5], last write [2023-01-28 00:57:24.000]
2023-02-07 18:41:55.746 [CLI ] Removing installer: C:\Users\mmv\AppData\Local\Temp\WinGet\AutoHotkey.AutoHotkey.2.0.2\AutoHotkey_2.0.2_setup.exe
2023-02-07 18:41:55.747 [CLI ] Leaf command succeeded: root:install
```

image

### PR DESCRIPTION
**Pull request by Trenly**
* Resolves #95829
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/95856)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/95856)

### CODE REVIEW

**Comment by Trenly** [comment]
@denelon - Is there no DefaultInstallRoot set in the settings on Pipeline?

**Comment by denelon** [comment]
I'll check with the team.

**Comment by denelon** [comment]
No, there is no default install root set in the validation infrastructure. We will have to manually verify this one.

**Comment by stephengillie** [comment]
Hi @Trenly,

What should be entered for the install root? I tried what seems like a normal location, and got an error:
image

I'm concerned that installing this package might be a poor experience for those who do not know a valid location.

**Comment by Trenly** [comment]
@stephengillie - I think the spaces might be the issue (and the casing)

**Comment by stephengillie** [comment]
A trailing slash seems to cause the error in some cases, and omitting the trailing slash sometimes allows the install to occur.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
