### PR TITLE
Package Fix: Possible fix for Zoom expecting different package version

### LINKED ISSUE #150120: [Package Issue]: Zoom.Zoom
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Zoom has changed its versioning to use parentheses instead of dots for the build number and it is confusing winget about whether the latest version is installed. Thus, winget will always try to update zoom even if the latest version is installed.

Actual version Zoom uses now: `6.0.0 (37205)`
Version winget expects to see: `6.0.0.37205`

### Steps to reproduce

`winget upgrade --all` with Zoom installed.

### Actual behavior

winget reinstalls Zoom even though the latest version is installed.

### Expected behavior

winget should recognize the latest version is installed and not try to update it.

### Environment

```raw
❯ winget --info
Windows Package Manager (Preview) v1.8.924-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3447
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.924.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

### Screenshots and Logs

```
❯ winget upgrade --all
Name           Id             Version       Available   Source
--------------------------------------------------------------
Zoom Workplace XP99J3KP4XZ4VV 6.0.0 (37205) 6.0.0.37205 winget
2 upgrades available.

(1/1) Found Zoom [Zoom.Zoom] Version 6.0.0.37205
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://zoom.us/client/6.0.0.37205/ZoomInstallerFull.exe?archType=x64
  ██████████████████████████████  97.9 MB / 97.9 MB
```

### PR DESCRIPTION
**Pull request by schembriaiden**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

Resolves: https://github.com/microsoft/winget-pkgs/issues/150120

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150124)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
You should use `AppsAndFeaturesEntries` to specify the version to ensure proper sorting

**Comment by vikingnope** [comment]
@Trenly, I tried doing this due to this issue: https://github.com/microsoft/winget-pkgs/issues/150120

**Comment by Trenly** [comment]
> @Trenly, I tried doing this due to this issue: #150120

I understand that, but if you change the PackageVersion then it won’t be sorted the same way as the existing versions and in some cases a newer version could end up being considered a lower version, this being sorted incorrectly.

The `AppsAndFeaturesEntries` specification in a manifest will tell WinGet to sort the version according to the PackageVersion, but match the `DisplayVersion` specified in the `AppsAndFeaturesEntries`. Thereby fixing the linked issue by providing the correct version to match to *and* still maintaining the sort order for all future versions

**Comment by SpecterShell** [comment]
@vikingnope

**Pull request closed without merging**
