### PR TITLE
New version: RussellBanks.Komac version 2.0.1

### PR DESCRIPTION
**Pull request by sitiom**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136918)

### CODE REVIEW

**Comment by sitiom** [comment]
@russellbanks

**Comment by sitiom** [comment]
Works for me

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978334972

(Automated response - build 669.)

**Comment by sitiom** [comment]
Works for me:
image

**Comment by sitiom** [comment]
- Waiting for https://github.com/microsoft/winget-pkgs/pull/136931 to be merged

**Comment by russellbanks** [comment]
@sitiom, the Inno installer for Komac v2.0.2 installs VCRedist if it's not already installed. I'm happy to start from 2.0.2 in WinGet to avoid the need for dependency entries in the manifest.

**Comment by sitiom** [comment]
- Continued in https://github.com/microsoft/winget-pkgs/pull/136980

**Pull request closed without merging**
