### PR TITLE
Remove version: Google.Chrome version 120.0.6099.200

### PR DESCRIPTION
**Pull request by PckgrBot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135439)

### CODE REVIEW

**Comment by drshtmstry** [comment]
> Sequence contains no elements

- #133371

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 642.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-19T04:48:49.1688901Z Processing manifest: manifests\g\Google\Chrome\120.0.6099.200
 2024-01-19T04:48:49.1698626Z -----------------------------------------------------
 2024-01-19T04:48:49.1706123Z Status: Started
 2024-01-19T04:48:49.1714131Z Manifest file is Deleted
 2024-01-19T04:48:49.4716322Z Status: Completed
 2024-01-19T04:48:49.4734033Z ##[error] Result: Failed
 2024-01-19T04:48:49.4825854Z ##[error] Sequence contains no elements
 2024-01-19T04:48:49.5413919Z ##[error]Manifest Validation Failed

(Automated response - build 642.)

**Comment by stephengillie** [comment]
URL: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise.msi 
Status Code: 200

(Automated message - build 642)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
