### PR TITLE
Talkdesk.Talkdesk version 1.6.5.2140

### PR DESCRIPTION
**Pull request by fabiovalverde**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/86242)

### CODE REVIEW

**Review by fabiovalverde — COMMENTED** [review]
OK

**Comment by fabiovalverde** [comment]
The download website is: https://empiricusinvest.mytalkdesk.com/atlas/download
Pointing to: https://td-infra-prd-us-east-1-s3-atlaselectron.s3.amazonaws.com/talkdesk-1.6.5.exe

**Comment by fabiovalverde** [comment]
Hi, 
The Website is: https://empiricusinvest.mytalkdesk.com/atlas/download
The Download link is: https://td-infra-prd-us-east-1-s3-atlaselectron.s3.amazonaws.com/talkdesk-1.6.5.exe

**Comment by stephengillie** [comment]
@fabiovalverde I couldn't find this software available for download on Talkdesk's website. Is there a download or similar page that could be provided?

**Comment by fabiovalverde** [comment]
@stephengillie the link is a shortcut provided by Talkdesk for our company.
the availables links are: 
https://talkdesk.mytalkdesk.com/atlas/download or https://downloadcallbar.talkdesk.com/Callbar%20Setup%201.50.6-electron.exe
i can commit the correct site if needed

**Review by stephengillie — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
