### PR TITLE
New package: HermannSchinagl.LinkShellExtension version 3.9.3.5

### PR DESCRIPTION
**Pull request by RavenMacDaddy**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

Author's note: `SilentWithProgress` is not available according to the arguments described [here](https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html#introduction).

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/66497)

### CODE REVIEW

**Comment by RavenMacDaddy** [comment]
Can't find a way to add `PackageDependencies`; only `MinimumVersion`

Closing.

**Comment by RavenMacDaddy** [comment]
Read that a manifest _must_ support `SilentWithProgress` - closing again.

**Comment by RavenMacDaddy** [comment]
Reopening with the required switches specified - although progress is NOT shown as described in the beginning.

If that won't fly, well, close it - however, consider if having progress available as a mode should continue to be absolutely mandatory, and by all means educate me if I'm missing a very important reason for this.

**Comment by ItzLevvie** [comment]
Close with reason: Duplicate of https://github.com/microsoft/winget-pkgs/pull/49982;

Dependency support will likely be coming to the Validation Pipeline somewhere in 2023 (?).

**Comment by RavenMacDaddy** [comment]
Apologies for missing the duplicate.

**Pull request closed without merging**
