### PR TITLE
Lamdera.Lamdera version 1.2.1

### PR DESCRIPTION
**Pull request by bdukes**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/152458)

### CODE REVIEW

**Comment by bdukes** [comment]
I did run into a failure testing the install. There are some `dll` files in the zip that need to be deployed alongside the `exe`. Is there a way to indicate that in the manifest?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\lamdera.exe returned exit code: -1073741515

Automated error analysis suggests -1073741515 may mean Dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 880.)

**Comment by stephengillie** [comment]
Hi @bdukes,

In a Windows 10 VM, this application installs and runs normally. But the symlink doesn't, probably because it's depending on DLL files that it can't reach. 
image

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Comment by Trenly** [comment]
@bdukes - Support for zipped binaries has now been added and is available in the pipelines. This will require you to update your submission to ManifestVersion: 1.9.0 and set ArchiveBinariesDependOnPath: true in the installer node. To keep things clean, this PR is being closed. Please submit a new PR for the latest version of this package. Thank you for your contributions!

**Pull request closed without merging**
