### PR TITLE
New package: Coloryr.ColorMC version 1.23

### PR DESCRIPTION
**Pull request by Coloryr**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131778)

### CODE REVIEW

**Comment by Coloryr** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 9:51:22 AM: 
> 2023-12-27 09:51:21.789 [FAIL] Installer failed security check. Url: https://github.com/Coloryr/ColorMC/releases/download/A23/colormc-a23-win64.exe Result: 0x80004005

(Automated response - build 489.)

**Comment by stephengillie** [comment]
Hi @Coloryr,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 489.)

**Comment by Coloryr** [comment]
I don't know how to install silently, In my own testing, it requires permission to install

**Comment by stephengillie** [comment]
Hi @Colyr,

This package seems to want to install itself to the D: drive:
image

Internet translation: 
Invalid drive: D:\
OK

Then the install immediately fails:
image

Internet translation: 
Installation not completed.
The installation program was interrupted and failed to install ColorMC. The installer needs to be restarted to try again.
Click Close to exit.
< Previous step(B)   Close(C)

**Comment by Coloryr** [comment]
> Hi @colyr,
> 
> This package seems to want to install itself to the D: drive: image
> 
> Internet translation: Invalid drive: D: OK
> 
> Then the install immediately fails: image
> 
> Internet translation: Installation not completed. The installation program was interrupted and failed to install ColorMC. The installer needs to be restarted to try again. Click Close to exit. < Previous step(B) Close(C)

Ok

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
