### PR TITLE
New version: Caphyon.AdvancedInstaller version 21.6

### PR DESCRIPTION
**Pull request by SpecterShell**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

* Resolves #147794

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/148121)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @SpecterShell,

> This PR's version number 21.6 has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 21.5.1, which has 3 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 876)

**Comment by stephengillie** [comment]
Hi @SpecterShell,

This manifest adds Apps and Features entries that aren't present in previous PR versions. These entries should be added to the previous versions, or removed from this version.

(Automated response - build 876.)

**Comment by SpecterShell** [comment]
image

**Comment by stephengillie** [comment]
Sorry for the delay - `ProductCode` and `UpgradeCode` are okay.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
