### PR TITLE
New version: PhilipGerke.Odassey version 3.0.4

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Failed
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | Odassey | PDFsam Basic, Session 1.9.1, osu!    |
| Version     | 3.0.4     | 4.3.3.0, 1.9.1, 2022.821.0 |
| Publisher   | Philip Gerke   | Sober Lemur S.a.s. di Vacondio Andrea, Oxen Labs, ppy Pty Ltd      |
| ProductCode |           | {24493C22-01EA-4E07-AB21-84910EB826B0}, f1339da8-b3f2-5116-b780-aafa611bc7f7, osulazer    |
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/75582)

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]
> 2022-08-29 19:15:08.622 [FAIL] Installer failed security check. Url: https://github.com/pgerke/get-odassey/releases/download/v3.0.4/Odassey_win_x64_v3.0.4.exe Result: 0x80004005

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
