### PR TITLE
Workflow to check line endings on PRs

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
@denelon this workflow checks line endings of manifests on pull requests.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/79404)

### CODE REVIEW

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
This will stop automated PRs from passing the pipeline and is not the correct way to deal with the issue.

**Review by Trenly — CHANGES_REQUESTED** [review]
Because you're making Github calls, you're also using the default token, which in this case is the Application Token. That is still subject to rate limiting, even though the limits are higher. 

While a workflow could potentially work for this, I would strongly discourage it at this time, as the root causes of wingetbot and wingetcreate using LF endings have not been resolved, and it hasn't been verified that YamlCreate always uses CRLF. It's more important to fix the root causes, as implementing this would just cause PR's to be blocked. 

Ultimately, having LF line endings doesn't break anything, so there isn't any value in breaking PR's

**Comment by vedantmgoyal2009** [comment]
> This will stop automated PRs from passing the pipeline and is not the correct way to deal with the issue.

Instead of requesting changes on PR, will a comment on the PR be fine? If the author can fix it, well and good, and if not, the PR would still be merged.

Another thing we can do is auto-renormalize if LF line endings are detected. @denelon what are your thoughts?

**Comment by Trenly** [comment]
Close with reason: Not Planned for implementation;

**Pull request closed without merging**
