### PR TITLE
Update version: Nvidia.CUDA version 12.6.1

### PR DESCRIPTION
**Pull request by marklani**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/172790)

### CODE REVIEW

**Comment by marklani** [comment]
Installation is fine on my computer. There should be no issue with the package as it is the same installer as in this merged PR https://github.com/microsoft/winget-pkgs/pull/170631 . This PR is important to have better versioning of the package. (Currently version 12.6.1 is patched on top of version 12.6.0 as version 12.6)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-09-11 02:45:51.814 [CLI ] ShellExecute installer failed: 2148270085

Automated error analysis suggests -1978335226 may mean Running ShellExecute failed

(Automated response - build 895.)

**Review by stephengillie — APPROVED** [review]

**Comment by SpecterShell** [comment]
@marklani It's not recommended to use the full version for this package, as WinGet relies on the version value of the ARP entries the installer wrote to the registry to check updates, which, however, only have two parts. Doing so may cause an update loop for users.

image

**Comment by aisgbnok** [comment]
> Installation is fine on my computer. There should be no issue with the package as it is the same installer as in this merged PR #170631. This PR is important to have better versioning of the package. (Currently version 12.6.1 is patched on top of version 12.6.0 as version 12.6)

Unfortunately this PR #172790 and #172785 cause an update loop as @SpecterShell predicted. See: #174522.

Better versioning of the package is hard to achieve because NVIDIA's installer only writes `MAJOR.MINOR` semver (`12.6`) to the Windows registry. @SpecterShell's approach of swapping the installer (#170631) is probably best given Winget's "limitations" in this instance.

There may be alternatives if you must have "better versioning of the package", such as using `DisplayVersion`, but that comes with it's own set of issues. (See `Google.AndroidStudio`: https://github.com/microsoft/winget-pkgs/pull/174516#issuecomment-2364922050)

**Pull request merged**
