### PR TITLE
Submitting Ramsoft.DicomProxy version 0.2.0.yaml

### PR DESCRIPTION
**Pull request by ghost**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [ ] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/7521)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
installer launches and blocks on a command window

image

**Comment by ramsoft-inc** [comment]
The installer launches an interactive powershell script that requires input from user before installation can proceed.

**Comment by KevinLaMS** [comment]
Looks like the installer gets blocked waiting for user input

image

**Comment by ramsoft-inc** [comment]
> Looks like the installer gets blocked waiting for user input
> 
> image

Silent install is not an option because the installer is designed to get user input that includes credentials and other confidential information during clean install.  Update does not require user input.

**Comment by ramsoft-inc** [comment]
@KevinLaMS My manifest file passed local validation but I am getting "Manifest is invalid. Manifest file missing required field: PackageIdentifier" error. What am I missing here? Thanks.

**Comment by denelon** [comment]
It looks like we're blocked until microsoft/winget-cli#910 gets implemented so we can filter out interactive only installers from import and other scenarios where users expect a non-interactive install.

**Pull request merged**
