### PR TITLE
[Portable] New Package: gsass1.NTop 0.3.4

### LINKED ISSUE #34765: [Package Request]: ntop
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher:  gsass1
Publisher Url: https://github.com/gsass1/NTop
Package Name: ntop
Description: system-monitor with Vi-emulation for Windows
Package Version: 0.3.4
Installer URL: https://github.com/gsass1/NTop/releases/download/v0.3.4/ntop.exe

Current Package Identifier (for new versions): 0.3.4

### PR DESCRIPTION
**Pull request by Trenly**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

* Resolves #34765

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/68806)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by Trenly — COMMENTED** [review]
Bump

**Comment by Trenly** [comment]
Bump

**Comment by alex-jitbit** [comment]
After installing the package is just thrown into `%LOCALAPPDATA%\Microsoft\WinGet\Packages\gsass1.NTop_Microsoft.Winget.Source_8wekyb3d8bbwe` and it took me ages to find it

**Pull request merged**
