### PR TITLE
New package: KingoRoot.KingoRoot version 4.7.0

### LINKED ISSUE #155761: [Package Request]: Kingo Root
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.kingoapp.com/android-root/download.htm
Publisher: `Kingo Root team`
Package Name: `KingoRoot`
Description: `KingoRoot, both PC and APK version, offers the easiest Android rooting methods for all android devices of any android version and has the highest success rate.`
Package Version: [4.7.0](https://www.kingoapp.com/root-update.htm)
Installer URL: https://d.kingoroot.com/android_root.exe

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Related #155761 but **failed to solve** it.

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/155958)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with:
> PUABundler:Win32/FusionCore PUADlManager:Win32/InstallCore

(Automated response - build 882.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> PUABundler:Win32/FusionCore PUADlManager:Win32/InstallCore

(Automated response - build 882.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> PUABundler:Win32/FusionCore PUADlManager:Win32/InstallCore

(Automated response - build 883.)

**Comment by Dragon1573** [comment]
Emmm... It seems several vendors in [VirusTotal](url) flagged this installer file as malicious. Since it's a ROOT tool for Android, is it been flagged because of its designed usage?

**Comment by stephengillie** [comment]
Sorry for the delay. `wingetbot run` wasn't listening to due to:

> Octokit was broken because comment id exceeded int maximum value for parsing JSON. A fix was submitted earlier, but we haven't got a NuGet package yet[.] 

- [@denelon on Gitter](https://matrix.to/#/!LEwByvxhTNZZcKeCCY:gitter.im/$c5J6uL4eU3A1Sy9vsPbUgBSahjnfLz6TDh98ZeW56G4?via=gitter.im&via=matrix.org&via=beeper.com)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> PUABundler:Win32/FusionCore PUADlManager:Win32/InstallCore

(Automated response - build 884.)

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> For some specific reason, the package is flagged as malware by _Microsoft Defender_ and won't be able to pass the validation pipeline.
>
> The pull request is now being closed.

**Pull request closed without merging**
