### PR TITLE
SHA256 Fix: InfamousJoeG.cybr-cli version 1.0.1

### PR DESCRIPTION
**Pull request by infamousjoeg**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/118497)

### CODE REVIEW

**Comment by infamousjoeg** [comment]
I don't understand the issue here.  Can someone please explain?

**Comment by infamousjoeg** [comment]
> Hello @infamousjoeg,
> 
> The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.
> 
> Template: msftbot/validationError/installation/general

I don't understand the issue here. Can someone please explain?

**Comment by stephengillie** [comment]
Hi @infamousjoeg,

This appears to be an ephemeral error, sorry for any concern caused.

**Comment by infamousjoeg** [comment]
I've ran `winget install --manifest ...` successfully.  The pipeline is not providing any information.  Is this normal?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335187 
2023-08-30 18:44:30.535 [FAIL] Installer failed security check. Url: https://github.com/infamousjoeg/cybr-cli/releases/download/v1.0.1-release/cybr-cli_1.0.1-release_windows_amd64.zip Result: 0x80004005 

This is the same error as before, and `0x80004005` is essentially a 404 File Not Found error in some ways, so this usually clears after a retry. Here, however, it recurred. Please check your systems to ensure that they're uninfected. This might be a false positive, and we can retry again tomorrow.

**Comment by infamousjoeg** [comment]
Extremely weird.  I'm able to download directly using the URL it reported using.  Also, able to do the same via `winget install --manifest ...` using the manifest I've committed here.

I am trying to fix a SHA256 mismatch... could that be an issue here?  I imagine it's just targeting the local manifest like I do in my tests, as well, so probably not relevant.

**Comment by infamousjoeg** [comment]
@StephenGillie,

Is there something I can do here to move this forward?  I'm kind of lost on what I can provide since tests from my end  all check out.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
