### PR TITLE
Add Icaros

### PR DESCRIPTION
**Pull request by Witchilich**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----
Icaros is another one of those apps that needs winget to support Videohelp links first.
https://github.com/microsoft/winget-cli/issues/524
This PR is here till the issue gets resolved.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3278)

### CODE REVIEW

**Comment by yigitemres** [comment]
@Witchilich Download link in manifest file is not valid.

**Comment by Witchilich** [comment]
@yigitemres It is. There is an issue to recognize videohelp redirect links like Scoop does. 
https://github.com/TheRandomLabs/scoop-nonportable/blob/master/bucket/icaros-np.json

**Comment by yigitemres** [comment]
@Witchilich When I said ıt's not valid, I'm talking about it's not downloading the file. I copy paste your download link `https://www.videohelp.com/download/Icaros_v3.1.0.exe` and redirects to me to `https://www.videohelp.com/software?d=Icaros_v3.1.0.exe` and this is the page:

firefox_dV4bJpNXi5

**Comment by Witchilich** [comment]
The actual link would be `https://www.videohelp.com/download/Icaros_v3.1.0.exe?r=tmLFQDNgmDKr` but the redirection part keeps changing. Thats why this issue exists, winget should learn to use Videohelp redirects like Scoop.
https://github.com/microsoft/winget-cli/issues/524

**Comment by Witchilich** [comment]
This is used to get videohelp link in many Chocolatey packages
`Invoke-WebRequest -Uri "http://www.videohelp.com/download/Icaros_v3.1.0.exe" | Select-Object -ExpandProperty Links | Where-Object { $_ -like "*Icaros_v3.1.0*" } | Select-Object -First 1 -ExpandProperty href`
This will return the url you need.

**Comment by musm** [comment]
Why was this closed?

**Comment by denelon** [comment]
@musm we don't have support for videohelp links.

**Pull request closed without merging**
