### PR TITLE
New package: Files.Community.FilesApp version 2.4.21

### PR DESCRIPTION
**Pull request by yair100**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/93674)

### CODE REVIEW

**Comment by yaira2** [comment]
>  Addition and deletion only permitted in the same package directory.

Can an exception be made in this case? The previous package was published under the wrong publisher.

**Comment by stephengillie** [comment]
Hi @yaira2,

This PR also removes the manifest for `YairAichenbaum.Files`:
image

Reverting the removed files and updating the PR should allow it to pass this validation step.

**Comment by yaira2** [comment]
@stephengillie this was intentional as the manifest was out of date and under the wrong name, should I open a separate PR for removing it?

**Comment by stephengillie** [comment]
@yaira2, 

Yes, please do open a separate PR for that manifest's removal.

**Comment by stephengillie** [comment]
The validation error states that the dependency is a blocker:
> 2023-01-14 16:05:02.284 [CORE] Deployment operation #0: Windows cannot install package Files_2.4.21.0_x64__wvne1zexy08sa because this package depends on a framework that could not be found. Provide the framework "Microsoft.WindowsAppRuntime.1.2" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 2000.707.2303.0, along with this package to install. The frameworks with name "Microsoft.WindowsAppRuntime.1.2" currently installed are: {}

To verify that the dependency is the only blocker, I tested the manifest as written in a VM with a 1.4 version of Winget. This version and newer supports installing dependencies before the main package installer, and the program installed and launched successfully.

**Pull request closed without merging**
