### PR TITLE
Listen for keypresses

### PR DESCRIPTION
**Pull request by Trenly**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
-----

To make the YamlCreate.ps1 script feel more smooth, I have changed the options menu to listen for the keypresses rather than having the user press enter after their selection. Along with this, I have created a function that will write multi-color strings on a single line to improve the readability.

Thanks @OfficialEsco for the feedback on my [discussion](/microsoft/winget-pkgs/discussions/21005)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/21143)

### CODE REVIEW

**Review by OfficialEsco — DISMISSED** [review]

**Comment by OfficialEsco** [comment]
Not sure how GitHub merge completely works, will this cause a issue with https://github.com/microsoft/winget-pkgs/pull/21172 which got merged first?
I don't think we changed the same lines so maybe its aight

**Comment by ItzLevvie** [comment]
It should be fine.

I applied https://patch-diff.githubusercontent.com/raw/microsoft/winget-pkgs/pull/21143.patch on top of the latest commit and there doesn't seem to be any conflicts.

**Comment by Trenly** [comment]
> Not sure how GitHub merge completely works, will this cause a issue with #21172 which got merged first?
> I don't think we changed the same lines so maybe its aight

I just rebased on master just to be 100% certain there were no merge conflicts

**Review by OfficialEsco — APPROVED** [review]
@denelon this one too

**Review by denelon — APPROVED** [review]

**Pull request merged**
