### PR TITLE
New version: vim.vim version 9.0.1240

### PR DESCRIPTION
**Pull request by chrisbra**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/94573)

### CODE REVIEW

**Review by ImJoakim — APPROVED** [review]

**Comment by stephengillie** [comment]
Hopefully intermittent:
> Exception Message: The remote server returned an error: (504) Gateway Timeout. (type WebException)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
