### PR TITLE
CapricornDevelopment.SharepointFileManager version 0.0.7.0

### PR DESCRIPTION
**Pull request by CapricornDevelopment**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/94419)

### CODE REVIEW

**Comment by stephengillie** [comment]
> The root certificate and all intermediate certificates of the signature in the app package or bundle must be trusted.
> A certificate chain could not be built to a trusted root authority.

I believe the certificate in the error is the msixbundle signing certificate. Has this package been signed?

From #93522:
[Sign a Windows 10 app package - MSIX | Microsoft Learn](https://learn.microsoft.com/windows/msix/package/signing-package-overview)

**Comment by CapricornDevelopment** [comment]
Hi @stephengillie ,

the package has been singed with a Self-Signed Certificate by Visual Studio. Is there any way to publish the .msix without a public Code-Signing-Certificate?

**Pull request closed without merging**
