### PR TITLE
Added Mozilla Firefox version 115.0.3.

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----
 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/113879&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
1. en-US-x64-wix-machine - Pending
1. en-US-x64-exe-machine - Pending
1. en-US-x64-exe-user - Pending
1. en-US-x86-wix-machine - Pending
1. en-US-x86-exe-machine - Pending
1. en-US-x86-exe-user - Pending
1. zh-CN-x64-wix-machine - Pending
1. zh-CN-x64-exe-machine - Pending
1. zh-CN-x86-wix-machine - Pending
1. zh-CN-x86-exe-machine - Pending
1. en-GB-x64-wix-machine - Pending
1. en-GB-x64-exe-machine - Pending
1. en-GB-x86-wix-machine - Pending
1. en-GB-x86-exe-machine - Pending
1. ru-RU-x64-wix-machine - Pending
1. ru-RU-x64-exe-machine - Pending
1. ru-RU-x86-wix-machine - Pending
1. ru-RU-x86-exe-machine - Pending
1. de-DE-x64-wix-machine - Pending
1. de-DE-x64-exe-machine - Pending
1. de-DE-x86-wix-machine - Pending
1. de-DE-x86-exe-machine - Pending
1. el-GR-x64-wix-machine - Pending
1. el-GR-x64-exe-machine - Pending
1. el-GR-x86-wix-machine - Pending
1. el-GR-x86-exe-machine - Pending
1. ja-JP-x64-wix-machine - Pending
1. ja-JP-x64-exe-machine - Pending
1. ja-JP-x86-wix-machine - Pending
1. ja-JP-x86-exe-machine - Pending
1. es-ES-x64-wix-machine - Pending
1. es-ES-x64-exe-machine - Pending
1. es-ES-x86-wix-machine - Pending
1. es-ES-x86-exe-machine - Pending
1. es-MX-x64-wix-machine - Pending
1. es-MX-x64-exe-machine - Pending
1. es-MX-x86-wix-machine - Pending
1. es-MX-x86-exe-machine - Pending
1. nb-NO-x64-wix-machine - Pending
1. nb-NO-x64-exe-machine - Pending
1. nb-NO-x86-wix-machine - Pending
1. nb-NO-x86-exe-machine - Pending
1. Architecture: x64-msix - Pending
1. Architecture: x86-msix - Pending
1. fr-FR-x64-wix-machine - Pending
1. fr-FR-x64-exe-machine - Pending
1. fr-FR-x86-wix-machine - Pending
1. fr-FR-x86-exe-machine - Pending
1. ta-IN-x64-wix-machine - Pending
1. ta-IN-x64-exe-machine - Pending
1. ta-IN-x86-wix-machine - Pending
1. ta-IN-x86-exe-machine - Pending

**Pull request merged**
