### PR TITLE
New Version: GodotEngine.GodotEngine version 2.0

### PR DESCRIPTION
**Pull request by og-mrk**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141447)

### CODE REVIEW

**Comment by og-mrk** [comment]
> Automatic Validation ended with:
> 
> > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\GodotEngine.GodotEngine__DefaultSource\Godot_v2.0_stable_win64.exe returned exit code: -1073741819
> > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\Godot_v2.0_stable_win64.exe returned exit code: -1073741819
> > Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Packages\GodotEngine.GodotEngine__DefaultSource\Godot_v2.0_stable_win32.exe returned exit code: -1073741819
> > Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\Godot_v2.0_stable_win32.exe returned exit code: -1073741819
> 
> (Automated response - build 855.)

Godot 2.0 doesn't have Official Documentation anymore, so I've removed these fields in pre-2.1 versions. The other PRs ( for version [2.0.1](https://github.com/microsoft/winget-pkgs/pull/141451), [2.0.2](https://github.com/microsoft/winget-pkgs/pull/141453), [2.0.3](https://github.com/microsoft/winget-pkgs/pull/141455), and [2.0.4.1](https://github.com/microsoft/winget-pkgs/pull/141456)) will have the same issue as this one, and for the same reason.

**Comment by stephengillie** [comment]
Hi @og-mrk,

> Godot 2.0 doesn't have Official Documentation anymore, so I've removed these fields in pre-2.1 versions. The other PRs ( for version https://github.com/microsoft/winget-pkgs/pull/141451, https://github.com/microsoft/winget-pkgs/pull/141453, https://github.com/microsoft/winget-pkgs/pull/141455, and https://github.com/microsoft/winget-pkgs/pull/141456) will have the same issue as this one, and for the same reason.

Guessing this is a response to the automated response above mine. Unless you meant that the missing documentation can cause a non-zero exit code?

**Comment by stephengillie** [comment]
Hi @og-mrk,

> This PR's version number 2.0 has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 4.2.1, which has 3 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 855)

**Comment by og-mrk** [comment]
> Hi @og-mrk,
> 
> > Godot 2.0 doesn't have Official Documentation anymore, so I've removed these fields in pre-2.1 versions. The other PRs ( for version #141451, #141453, #141455, and #141456) will have the same issue as this one, and for the same reason.
> 
> Guessing this is a response to the automated response above mine. Unless you meant that the missing documentation can cause a non-zero exit code?

@stephengillie, Yes, it was.
> "Guessing this is a response to the automated response above mine."

and no, the Removal of `Documentation` Field and its Sub-Fields Should Not cause a non-zero exit code, or in other words, it Shouldn't Cause the Installation to Fail.

**Comment by og-mrk** [comment]
> Hi @og-mrk,
> 
> > This PR's version number 2.0 has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 4.2.1, which has 3 parameters.
> 
> Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)
> 
> (Automated response - build 855)

Hello @stephengillie,
This PR's Version number matches the one shown in the Apps & features Settings page, **_see the screenshot below_**.

image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
