### PR TITLE
chore: add vcredist dep to gptscript installer

### PR DESCRIPTION
**Pull request by drpebcak**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161386)

### CODE REVIEW

**Comment by drpebcak** [comment]
What's going on with this one? Having a hard time deciphering from the pipeline what is actually going wrong with it. This is a package that was already accepted at one point, with an identical dependency change being added that was already done to the rest of the other versions. Is this just a flaky pipeline?

**Comment by stephengillie** [comment]
Hi @drpebcak,

Unfortunately, our pipelines were having a capacity issue due to a high number of requests. Sorry that you were impacted.

- https://github.com/microsoft/winget-pkgs/discussions/155218

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
