### PR TITLE
Add version: Aserto.Topaz version 0.30.27

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/134506)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification.
>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> URI: https://github.com/aserto-dev/topaz/releases/download/v0.30.27/topaz_windows_x86_64.zip, Validation result: Failed, Http status code: NotFound

(Automated response - build 590.)

**Comment by stephengillie** [comment]
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 590)

**Comment by stephengillie** [comment]
This might be due to a network block of data centers, to prevent automated downloads.

(Automated response - build 591.)

**Comment by Exorcism0666** [comment]
@stephengillie unfortunately, yes...

**Pull request closed without merging**
