### PR TITLE
New package: cantino.mcfly version 0.9.1

### PR DESCRIPTION
**Pull request by LukeCarrier**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164752)

### CODE REVIEW

**Comment by LukeCarrier** [comment]
When I extracted the zip archive locally I got a (suspected false positive) malware classification from Defender. After removing dealing with this installation succeeded. What do I do in this case?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-07-26 08:30:56.866 [FAIL] Installer failed security check. Url: https://github.com/cantino/mcfly/releases/download/v0.9.1/mcfly-v0.9.1-x86_64-pc-windows-msvc.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 886.)

**Comment by LukeCarrier** [comment]
VirusTotal results give:

- [0/94 malicious results on the URL](https://www.virustotal.com/gui/url-analysis/u-c8c656ea407e54b499415fc8b0264ec11a1b2c7f05015892cbb7822e9cee5b08-1722021037)
- [0/71 for the archive](https://www.virustotal.com/gui/file/525583d8c6c3bd33eada02aabe13f706bca3a529225e07d9acc6796122e3204a/detection)
- [1/75 for `mcfly.exe`](https://www.virustotal.com/gui/file/afd362d15a15f305bbd6a2aa115847c061a3fc67a3a5c48dfba1a1dda5ded10b)

Behaviour looks pretty boring too.

**Comment by LukeCarrier** [comment]
Do you need anything from me to get this merged, or does it just need review? 🙂

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\cantino.mcfly__DefaultSource\mcfly.exe returned exit code: -1073741515
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\mcfly.exe returned exit code: -1073741515

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 887.)

**Comment by LukeCarrier** [comment]
> Automatic Validation ended with:
> 
> > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\cantino.mcfly__DefaultSource\mcfly.exe returned exit code: -1073741515
> > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\mcfly.exe returned exit code: -1073741515
> 
> Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).
> 
> (Automated response - build 887.)

Out of interest, where are you seeing this information, and how can I reproduce this locally? I don't see anything useful in the AzDO jobs linked in the checks. This seems like it would be useful information to provide contributors that ought not to compromise Microsoft.

**Comment by LukeCarrier** [comment]
Thanks -- I know where to look now. Bit weird that the application can fail to launch and the pipeline returns a successful response, it sorta defeats the purpose of reporting check statuses to GitHub 🙃

**Comment by LukeCarrier** [comment]
Don't have access to a Windows machine to properly test this, but it looks like it's now launching the app and seeing a non-zero exit status because invoking `mcfly` with no args prints help. I'll see if I can get it to test with `mcfly --version` or something.

**Comment by stephengillie** [comment]
Verify:
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
