### PR TITLE
New version: dotenvx.dotenvx 1.11.4

### PR DESCRIPTION
**Pull request by motdotenv**
New version: dotenvx.dotenvx 1.11.4
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/170382)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-08-28 13:49:13.093 [FAIL] Installer failed security check. Url: https://github.com/dotenvx/dotenvx/releases/download/v1.11.4/dotenvx-1.11.4-windows-x86_64.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 891.)

**Comment by motdotenv** [comment]
not sure why this is failing security check. it passes here: https://www.virustotal.com/gui/url/7c89bc23213baa5e56ee54f9149ad87fa64036a5c1fe47330d61fd71c8dca4a5?nocache=1

**Comment by motdotla** [comment]
now that it passed here: https://github.com/microsoft/winget-pkgs/pull/169947

can it be re-run and approved for this PR as well @stephengillie?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\dotenvx.dotenvx__DefaultSource\dotenvx.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\dotenvx.exe returned exit code: 1

(Automated response - build 892.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
