### PR TITLE
Move: Dicarne.TheCenter 1.0.5

### PR DESCRIPTION
**Pull request by quhxl**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23636)

### CODE REVIEW

**Comment by quhxl** [comment]
Screenshot 2021-08-03 204532

**Review by OfficialEsco — DISMISSED** [review]

**Comment by denelon** [comment]
@quhxl I did some digging, and it's hard to verify the license type and "official" source for the package. It looks like @dicarne submitted the earlier manifest. Are we sure this is the correct publisher and package information?

**Comment by dicarne** [comment]
What happend and what's this?

**Comment by denelon** [comment]
@dicarne it looks like @quhxl is doing a rename/move of the manifest. It's likely fixing some issues with upgrade or another reason. We're trying to determine if the package is coming from the official source. It's hard to tell based on the manifest and the URL in the manifest if this is the official source for "The Center" package.

**Comment by lychichem** [comment]
@quhxl You cannot use a private webDAV/Clouddrive that only you can access, or can only access at limited time to store the installer you submitted to this repo. Please use a permanent link. And, please provide detail info for the package. Again, do not use your private webDAV, notebook, or any other private thing.

**Review by lychichem — CHANGES_REQUESTED** [review]
1. Installer URL should change to public and permanent URL.
2. Info URL should change to public and permanent URL.

**Comment by ItzLevvie** [comment]
> @dicarne it looks like @quhxl is doing a rename/move of the manifest. It's likely fixing some issues with upgrade or another reason. We're trying to determine if the package is coming from the official source. It's hard to tell based on the manifest and the URL in the manifest if this is the official source for "The Center" package.

The repository for @dicarne's The Center application is hosted at https://gitee.com/dicarne/the-center and the URL is meant to be from `https://gitee.com/dicarne/the-center/releases/v1.0.6` which is https://gitee.com/dicarne/the-center/attach_files/715855/download/the_center_desktop%20Setup%201.0.6.exe?

**Comment by lychichem** [comment]
@quhxl @denelon As far as I digged, the publisher should be "丢子丢" (If he/she signed the package). The info of this package can be found here:https://zhuanlan.zhihu.com/p/192659688

**Comment by OfficialEsco** [comment]
Na most of the the Metadata is from https://github.com/microsoft/winget-pkgs/pull/14281 which @dicarne submitted
This PR is just a cleanup and added the metadata he could find
image

**Comment by dicarne** [comment]
As the author, although the website corresponding to this zhihu link is made by me, it has nothing to do with this software. Just made use of the CDN agent file download provided by my website. For some reason my Github downloads always fail, gitee is not available for download. Some package descriptions may be incorrect. I hope this information helps you.

**Comment by dicarne** [comment]
> @dicarne what is the GitHub URL for the 1.0.5 release?

I uploaded this project to github: https://github.com/dicarne/the-center

and the release: https://github.com/dicarne/the-center/releases/download/1.0.5/the_center_desktop.Setup.1.0.5.exe

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
