### PR TITLE
New version: Microsoft.Office version 16.0.15028.20204

### LINKED ISSUE #57646: [Installer hash does not match]: microsoft.office
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

When installing microsoft office through the winget client we get the error:

"installer hash does not match; this cannot be overridden when running as admin".

This has happened before previously:

https://github.com/microsoft/winget-pkgs/issues/35459#

### Steps to reproduce

winget install microsoft.office -s winget

### Actual behavior

Gives error when trying to download: Downloading https://officecdn.microsoft.com/pr/wsus/setup.exe

Error in question:

Installer hash does not match; this cannot be overridden when running as admin

### Expected behavior

Installs office silently.

### Environment

```shell
C:\WINDOWS\system32>winget --info
Windows Package Manager v1.2.10271
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.556
Package: Microsoft.DesktopAppInstaller v1.17.10271.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### Screenshots and Logs

_No response_

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

* Resolves #57646

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/57659)

### CODE REVIEW

**Comment by Trenly** [comment]
I think there may be a CDN issue here; When I go to the URL I get 20152
```
PS D:\Git\winget-pkgs> (Get-Item D:\Users\Trenly\Downloads\Temp\setup.exe).VersionInfo

ProductVersion   FileVersion      FileName
--------------   -----------      --------
16.0.15028.20152 16.0.15028.20152 D:\Users\Trenly\Downloads\Temp\setup.exe
```

**Comment by OfficialEsco** [comment]
The Setup.exe is weird, it mainly downloads the latest version
```
❯ (Get-Item 'C:\Users\odin9\Downloads\setup.exe').VersionInfo

ProductVersion   FileVersion      FileName
--------------   -----------      --------
16.0.15028.20152 16.0.15028.20152 C:\Users\Esco\Downloads\setup.exe
```

```
❯ Get-FileHash C:\Users\Esco\Downloads\setup.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          482965FB962D591714DE3665DCCDE5AE3F576D5B10BD0B9801AE76F66965A5E7       C:\Users\Esco\Downloads\setup.…
```

However, the bot does indeed throw
```
2022-04-13 13:51:13.825 [CLI ] Package hash verification failed. SHA256 in manifest [482965fb962d591714de3665dccde5ae3f576d5b10bd0b9801ae76f66965a5e7] does not match download [6d320b8e2b4267cb5e4d16497d5d8e5d586fe58c95d92490c600ba4b758a2361]
2022-04-13 13:51:13.826 [CLI ] Terminating context: 0x8a150011 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:17f
```
when actually running the test, which we have seen more of lately and do not know the cause of since it passed the first Hash validation...

**Comment by Trenly** [comment]
> The Setup.exe is weird, it mainly downloads the latest version
> 
> ```
> ❯ (Get-Item 'C:\Users\odin9\Downloads\setup.exe').VersionInfo
> 
> ProductVersion   FileVersion      FileName
> --------------   -----------      --------
> 16.0.15028.20152 16.0.15028.20152 C:\Users\Esco\Downloads\setup.exe
> ```
> 
> ```
> ❯ Get-FileHash C:\Users\Esco\Downloads\setup.exe
> 
> Algorithm       Hash                                                                   Path
> ---------       ----                                                                   ----
> SHA256          482965FB962D591714DE3665DCCDE5AE3F576D5B10BD0B9801AE76F66965A5E7       C:\Users\Esco\Downloads\setup.…
> ```
> 
> However, the bot does indeed throw
> 
> ```
> 2022-04-13 13:51:13.825 [CLI ] Package hash verification failed. SHA256 in manifest [482965fb962d591714de3665dccde5ae3f576d5b10bd0b9801ae76f66965a5e7] does not match download [6d320b8e2b4267cb5e4d16497d5d8e5d586fe58c95d92490c600ba4b758a2361]
> 2022-04-13 13:51:13.826 [CLI ] Terminating context: 0x8a150011 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:17f
> ```
> 
> when actually running the test, which we have seen more of lately and do not know the cause of since it passed the first Hash validation...

Ahhh, I see. It runs the hash multiple times for some reason and isn't hashing it the same way?

**Comment by OfficialEsco** [comment]
Updated my comment too late, there is a Hash check in the [Installer Scan](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=302417&view=logs&j=871b4eed-22de-5cb6-c1c8-82f190de633f&t=523ceef4-ddf7-55a0-c83d-dd0f77b67744&l=38) part which triggers the Hash Missmatch label, the Validation-Installation-Error we're seeing here is caused by the Azure VM somehow getting a different hash (Which is not the old one E5355C841092D89ACC1E2839039C25E6D842449A473BEE6285213D83403A4D29)

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
```
4/13/2022 5:28:53 PM
Status: Completed
##[error] Installer https://officecdn.microsoft.com/pr/wsus/setup.exe
##[error] Result: Failed
##vso[task.logissue type=error] Specified hash doesn't match.
Actual hash:   E5355C841092D89ACC1E2839039C25E6D842449A473BEE6285213D83403A4D29
Expected hash: 482965fb962d591714de3665dccde5ae3f576d5b10bd0b9801ae76f66965a5e7
```
Now its downloading the previous setup.exe?
```
PS M:\> winget install -m .\m\Microsoft\Office\16.0.15028.20204\ --force
Found Microsoft 365 Apps for enterprise [Microsoft.Office] Version 16.0.15028.20204
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://officecdn.microsoft.com/pr/wsus/setup.exe
  ██████████████████████████████  7.78 MB / 7.78 MB
Installer hash does not match; proceeding due to --force
```
However it still installed `16.0.15028.20204`
VM:
```
PS M:\> Get-FileHash C:\Users\User\Downloads\setup.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          E5355C841092D89ACC1E2839039C25E6D842449A473BEE6285213D83403A4D29       C:\Users\User\Downloads\setup.exe


PS M:\> (Get-Item C:\Users\User\Downloads\setup.exe).VersionInfo

ProductVersion   FileVersion      FileName
--------------   -----------      --------
16.0.14931.20118 16.0.14931.20118 C:\Users\User\Downloads\setup.exe
```
Personal:
```
❯ Get-FileHash C:\Users\Esco\Downloads\setup2.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          482965FB962D591714DE3665DCCDE5AE3F576D5B10BD0B9801AE76F66965A5E7       C:\Users\Esco\Downloads\setup2…


❯ Get-FileHash C:\Users\Esco\Downloads\setup.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          482965FB962D591714DE3665DCCDE5AE3F576D5B10BD0B9801AE76F66965A5E7       C:\Users\Esco\Downloads\setup.…

❯ (Get-Item C:\Users\Esco\Downloads\setup.exe).VersionInfo

ProductVersion   FileVersion      FileName
--------------   -----------      --------
16.0.15028.20152 16.0.15028.20152 C:\Users\Esco\Downloads\setup.exe
```

**Comment by jedieaston** [comment]
Did they roll it back?

**Pull request merged**
