### PR TITLE
fix: broken betterbird download links

### PR DESCRIPTION
**Pull request by ptsouchlos**
According to https://www.betterbird.eu/downloads/index.php, build3 will be available 27 Nov. 2024.

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/194612)

### CODE REVIEW

**Comment by DeveloperPaul123** [comment]
Seems that Betterbird hasn't released the new installers yet. I will update once they do.

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 899)

**Comment by RiseT** [comment]
> Seems that Betterbird hasn't released the new installers yet. I will update once they do.

Just browsing here with no deeper knowledge, but it seems to me that build3 is [only available for Linux](https://www.betterbird.eu/downloads/index.php):
"Linux Version 115.18.0-bb36 replaced with "build 3" on 27 November 2024 due to an incorrect build date."

**Pull request closed without merging**
