### PR TITLE
New version: Kiwix.KiwixJS version 3.3.8.0

### PR DESCRIPTION
**Pull request by Jaifroid**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161959)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Jaifroid** [comment]
Hmm. I can't see a good reason for this to be failing. Installation of manifest works fine locally:

image

**Comment by Jaifroid** [comment]
@stephengillie Validation has now been restarted several times, but it keeps hanging and then coming up with this internal error. There is no substantial change in code from last month, and the app installs correctly and without complaint from the manifest (see screenshot above). So I don't think the app is at fault here.

**Comment by stephengillie** [comment]
Hi @Jaifroid,

We're having some pipeline issues. Sorry for the delay in validating.

**Pull request merged**
