### PR TITLE
FrostWireLLC.FrostWire version 6.9.3.305

### PR DESCRIPTION
**Pull request by ptanmay143**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14072)

### CODE REVIEW

**Comment by ptanmay143** [comment]
The tests seem to be stuck at something.

**Comment by denelon** [comment]
We've got a couple of reasons this could happen. This should timeout at the 23-25 hour mark.

One of these is a bug we're working on, and this is the perfect scenario to validate if that's the reason.

The other is part of the static analysis testing. Once this completes, we should see the bot put the appropriate label on the PR. If this runs past the 25 hour mark, add another comment if we haven't done anything.

**Comment by denelon** [comment]
We're working on improvements to automatically trigger a re-scan when we have this timeout. The changes aren't in production yet, so I'm going to trigger validation again.

**Comment by ptanmay143** [comment]
Hmm, I was worried that this might happen. When trying to install it on my system, Microsoft Defender tagged it as a threat too. I will bring up an issue on Frostwire GitHub for the same. Till then, let's not merge this to the winget-pkgs.

**Pull request closed without merging**
