### PR TITLE
New version: LGUG2Z.komorebi version 0.1.22

### PR DESCRIPTION
**Pull request by LGUG2Z**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141994)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @LGUG2Z,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow. 

(Automated response - build 857.)

**Comment by LGUG2Z** [comment]
I'll try to submit this as a false positive to the defender program later before the next rescan

**Comment by LGUG2Z** [comment]
https://www.microsoft.com/en-us/wdsi/submission/ef9cf870-b10d-4871-908e-73fc1d801aac false positive should be dealt with now 🤞

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
