### PR TITLE
wordaddinformediawiki 1.0.0

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3811)

### CODE REVIEW

**Comment by oxygen-dioxide** [comment]
Sorry, I can't see your picture. What I see is "Uploading image.png…"

**Comment by KevinLaMS** [comment]
image

i am now getting 1603.

**Comment by oxygen-dioxide** [comment]
This app must be installed with an elevated shell. If you're not using an elevated shell, it will prompt a UAC, however it will still fail.

**Comment by KevinLaMS** [comment]
Elevated prompt still shows 1603 error.

**Pull request closed without merging**
