### PR TITLE
Update Moniker: PrimateLabs.Geekbench.5 version 5.4.1

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23282)

### CODE REVIEW

**Comment by ChuckFerring** [comment]
Please verify that the application installs and runs properly on a x86 Windows OS.

**Comment by OfficialEsco** [comment]
Well.. it did pass the same validation 2 months ago https://github.com/microsoft/winget-pkgs/pull/15772. But change the Architecture to x64 since the x86 machine is no fun

**Comment by ItzLevvie** [comment]
> Well.. it did pass the same validation 2 months ago #15772. But change the Architecture to x64 since the x86 machine is no fun

This was back when the pipelines ran all of the 32-bit installers on a 64-bit OS; now it runs all of the 32-bit installers on 32-bit OS.

This is what I see on a 32-bit OS:
image
image
image

`C:\Program Files\Geekbench 5` doesn't have the files to run the application - there are only 2 files:
image

**Comment by OfficialEsco** [comment]
Oh, good to know.
Whats the issue here then? The installer finishes but the executable is broken because of corrupt installation?

**Comment by ItzLevvie** [comment]
It looks like that's what's happening here because the installer is not extracting all of the files properly.

The x64 version of Geekbench runs fine:
image
image
image

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
