### PR TITLE
Remove KDEConnect version 1.4-260

### PR DESCRIPTION
**Pull request by adandreou**
Follow up from #2367 

The download link for KDEConnect version 1.4-260 is no longer reachable.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2421)

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Validation has completed

**Review by sa-orlov — COMMENTED** [review]
Ok

**Review by sa-orlov — COMMENTED** [review]
Ok

**Review by sa-orlov — COMMENTED** [review]
Ok

**Review by sa-orlov — COMMENTED** [review]
Ok

**Review by sa-orlov — COMMENTED** [review]
Ok

**Review by sa-orlov — COMMENTED** [review]
Micosoft

**Pull request merged**
