### PR TITLE
Adds Viscosity version 1.9

### PR DESCRIPTION
**Pull request by trametheka**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/4761)

### CODE REVIEW

**Comment by yigitemres** [comment]
@KevinLaMS This pr needs to be closed. #7717

**Comment by denelon** [comment]
@yigitemres this looks like it is adding a valid version 1.9 (based on me looking at the manfiest). I see the 1.9.1 version was added in #7717. Is there a reason not to include a manifest for 1.9?

**Comment by yigitemres** [comment]
@trametheka Hi there 👋. If you become active again I think that it is a nice thing to reopen your pr 👍. Thanks for your work and have a nice day! 🥂

**Comment by trametheka** [comment]
Hi @yigitemres , I forgot this PR was still here. We've identified a problem with our installer when running silently which is hanging the test process with winget, so we'll fix that and get another PR in soon. Cheers.

**Pull request closed without merging**
