### PR TITLE
Add PyCharm Edu 2021.1.2 (build 211.7628.16)

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/20133)

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@ItzLevvie Please help to fix it.

**Comment by vedantmgoyal2009** [comment]
@denelon I have given a valid edu_silent.config file and the manifest is also WORKING but seems like the repository does not allow to put the config file. Can you please another way to do it?

**Comment by vedantmgoyal2009** [comment]
Please help someone 🙏🏻 🙏🏻 🙏🏻

**Comment by denelon** [comment]
@vedantmgoyal2009 it looks like you asked for help, and then immediately closed the PR. Most of the people working on the project are volunteering their time to support the community. There are hundreds of PRs open and flowing through the system on a daily basis. Since you deleted the branch, it's also hard to diagnose anything. If you figured it out, or gave up, that's fine. Just let others know rather than just a plea for help followed by closing the PR and deleting the branch. 😊

It might take a few days to get a response on an open source project. This is relatively normal based on my experience.

**Comment by denelon** [comment]
We don't have support for silent config files yet.
https://github.com/microsoft/winget-cli/issues/158

**Comment by vedantmgoyal2009** [comment]
> We don't have support for silent config files yet.
> [microsoft/winget-cli#158](https://github.com/microsoft/winget-cli/issues/158)

Thanks for replying. Actually, I thought files with other extensions has been blocked because of security reasons. Since there were some files messed up on my local machine, so I had to delete the fork and fork it again. Well, when I would find a way to install it without a configuration file, I will open a new PR.

**Pull request closed without merging**
