### PR TITLE
New version: LGUG2Z.komorebi version 0.1.26

### PR DESCRIPTION
**Pull request by LGUG2Z**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/154764)

### CODE REVIEW

**Comment by LGUG2Z** [comment]
@sitiom There is a new binary `komorebi-gui.exe` included in this release - does it need to be added to the `Commands` array? 🤔

**Comment by LGUG2Z** [comment]
Looks like the Commands array has nothing to do with adding to the PATH, I think this is good to merge if all checks have passed

**Comment by sitiom** [comment]
> @sitiom There is a new binary `komorebi-gui.exe` included in this release - does it need to be added to the `Commands` array? 🤔

Ideally, yes.

**Comment by LGUG2Z** [comment]
Updated the manifest, hopefully the validation checks don't fail since it's still the same installer with the same files 🤞

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
