### PR TITLE
New Package: azion.azion version 2.3.2

### PR DESCRIPTION
**Pull request by patrick-menoti-azion**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/198803)

### CODE REVIEW

**Comment by PatrickMenoti** [comment]
@microsoft-github-policy-service agree [company="{aziontech}"]

**Comment by PatrickMenoti** [comment]
@microsoft-github-policy-service agree

**Comment by PatrickMenoti** [comment]
@stephengillie I have run both validate and install commands locally and both passed. Is there a more detailed log of what went wrong during the validation workflow??

**Comment by stephengillie** [comment]
Manual Validation ended with:
image
Is there an installer switch to bypass this message and complete the install silently?

**Comment by PatrickMenoti** [comment]
> Hi @PatrickMenoti,
> 
> Manual Validation ended with: image Is there an installer switch to bypass this message and complete the install silently?

Aaah.. Is it possible to pass multiple switches? if so, we can go pass that stage

**Comment by PatrickMenoti** [comment]
It worked 🥳

**Comment by stephengillie** [comment]
Hi @PatrickMenoti,

The installer appears to have only added a few configuration files to the file system:
image

Is this expected?

**Comment by PatrickMenoti** [comment]
> Hi @PatrickMenoti,
> 
> The installer appears to have only added a few configuration files to the file system: image
> 
> Is this expected?

Yeah, during first execution of the executable, those files are created, as they are used by most functionalities.

**Comment by Trenly** [comment]
> > Hi @PatrickMenoti,
> > The installer appears to have only added a few configuration files to the file system: image
> > Is this expected?
> 
> Yeah @stephengillie, during first execution of the executable, those files are created, as they are used by most functionalities.
> 
> The executable does not need to be installed per se. It just executes, as it's a CLI.
> 
> Is there an additional configuration that should be added? (I've looked into some other Manifests from other packages and found this line: NestedInstallerType: portable)

When I go to the URL and download the file, it gives a file with no extension. Can you help me understand how users would typically install this CLI themselves?

**Pull request closed without merging**
