### PR TITLE
New version: ZetaSoftwareGmbH.ZetaResourceEditor version 2.3.72.0

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136466)

### CODE REVIEW

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 660.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-25T23:34:12.4546271Z -----------------------------------------------------
 2024-01-25T23:34:12.4550124Z Status: Started
 2024-01-25T23:34:12.4555425Z Manifest file is Added
 2024-01-25T23:34:12.6006995Z Manifest content validated.
 2024-01-25T23:34:12.6013761Z Manifest contains installer: https://www.zeta-resource-editor.com/zetaresourceeditor-setup.exe
 2024-01-25T23:34:12.6635514Z Status: Completed
 2024-01-25T23:34:12.6644581Z Result: Succeeded
 2024-01-25T23:34:12.7727867Z 
2024-01-25T23:34:12.7751930Z -----------------------------------------------------
 2024-01-25T23:34:12.7758611Z Status: Started
 2024-01-25T23:34:12.7766955Z Manifest file is Deleted
 2024-01-25T23:34:13.0182907Z Status: Completed
 2024-01-25T23:34:13.0196148Z ##[error] Result: Failed
 2024-01-25T23:34:13.0248566Z ##[error] Sequence contains no elements
 2024-01-25T23:34:13.0817337Z ##[error]Manifest Validation Failed
 2024-01-25T23:34:13.0829415Z 

(Automated response - build 660.)

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>     --- End of inner exception stack trace ---

(Automated response - build 785.)

**Pull request merged**
