### PR TITLE
Remove RareWares.LAME

### PR DESCRIPTION
**Pull request by stephengillie**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---
- Reverts https://github.com/microsoft/winget-pkgs/pull/153518

RareWares is a 3rd party rehosting site: "Providing hard-to-find pieces of software since 2001-10-21". The actual developer is https://lame.sourceforge.io/
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/155441)

### CODE REVIEW

**Review by Trenly — APPROVED** [review]

**Comment by Blacklands** [comment]
It doesn't look like https://lame.sourceforge.io/ is hosting any binaries. Isn't a third-party site that provides binaries for codecs fine? Does the manifest really need to be removed?

**Comment by stephengillie** [comment]
URL: https://www.rarewares.org/files/mp3/lame3.100.1-x64.zip 
Status Code: 200

(Automated message - build 881)

**Comment by stephengillie** [comment]
I may have overreacted, after finding the [FLAC PR](https://github.com/microsoft/winget-pkgs/pull/155439). This project only distributes binaries, and links to RareWares on their [3rd party page](https://lame.sourceforge.io/links.php#Binaries). I'm not 100% sure which way this one should go, but it kinda feels like this software might not be a good fit for this package manager, because the developer doesn't actually provide an installer for it.

**Comment by fgimian** [comment]
I will admit that this is a bit of a shame. RareWares is a very trusted source for builds of various encoders and even Scoop uses this build since there are no others available.

**Comment by denelon** [comment]
I would say this one is a bit of an outlier, but since the official site for Lame recognizes RareWares as a location for compiled binaries, I don't have any problems with having the package, but I do want to make sure that the appropriate waivers are maintained, and the manifest has some kind of information regarding the correct license and the actual publisher.

**Pull request merged**
