### PR TITLE
New version: Oxen.Session version 1.12.3

### PR DESCRIPTION
**Pull request by tianyeeT**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/158975)

### CODE REVIEW

**Comment by stephengillie** [comment]
> Possible duplicate package entry.
> 
> Similar installer SHA256 hash found in manifest:
> 
> * `InstallerSha256: 422ae4ffa584292d8d8ac38b5b8556a800fca2890d912159e99a5c74efbd4d15`
>   
>   * manifests\o\OxenLabs\Session\1.12.3

Hi @tianyeeT,

Are these the same package?

```PowerShell
PS C:\ManVal> find-WinGetPackage Oxen.Session

Name    Id           Version Source
----    --           ------- ------
Session Oxen.Session 1.12.2  winget

PS C:\ManVal> find-WinGetPackage OxenLabs.Session

Name    Id               Version Source
----    --               ------- ------
Session OxenLabs.Session 1.12.3  winget
```

**Comment by tianyeeT** [comment]
Hi @stephengillie,
Sorry for the late. They are the same package according to the installer's url. It seems like there is a new repository maintaining the `Session` package called `OxenLabs.Session`.  Is the old one `Oxen.Session` not maintained anymore? Thank you for spotting this!

**Comment by stephengillie** [comment]
Happy to help. They should be merged, which is to say that the old one should be removed, if it's not used.

**Pull request closed without merging**
