### PR TITLE
New Package: gnif.LookingGlass version B6

### PR DESCRIPTION
**Pull request by og-mrk**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141514)

### CODE REVIEW

**Comment by og-mrk** [comment]
This PR should satisfy issue https://github.com/microsoft/winget-pkgs/issues/58708

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files\Looking Glass (host)\looking-glass-host.exe returned exit code: 80

(Automated response - build 855.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files\Looking Glass (host)\looking-glass-host.exe returned exit code: 80

(Automated response - build 856.)

**Comment by og-mrk** [comment]
### Quick Note
I've tried multiple times to use `winget uninstall` command to uninstall this Package after installing it, but for whatever reason, it won't uninstall successfully.
Maybe because I haven't restarted my system after installing said package, but I don't think it's the case.
If anyone more experience with `.exe` Installers like the one used in here, feel free to post your ideas, and I'll respond when I can.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
