### PR TITLE
New version: uvncbvba.UltraVnc version 1.3.2

### PR DESCRIPTION
**Pull request by OfficialEsco**
closes #14699

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

https://github.com/microsoft/winget-cli/issues/163

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14722)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
@arjun-msft / @ChuckFerring can you guys see whats wrong here? It installs fine on my VM, no exit codes or Dependency's.
Same problem as Spotify?

**Comment by denelon** [comment]
@OfficialEsco this looks like a dependency issue with a device driver. "uvnc bvba Display adapters".

**Comment by OfficialEsco** [comment]
Weird, my VM does not show any Driver dependency, how would you go about implementing this since its not something we can install?

**Comment by denelon** [comment]
I'm hoping packages with driver dependencies can be addressed with support for dependencies. That means we would need an installer for the driver as well.

**Comment by OfficialEsco** [comment]
keeping PR for reminder

**Pull request closed without merging**
