### PR TITLE
New version: beeradmoore.dlss-swapper version 1.0.5.0

### PR DESCRIPTION
**Pull request by beeradmoore**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/138688)

### CODE REVIEW

**Comment by beeradmoore** [comment]
@microsoft-github-policy-service agree

**Comment by beeradmoore** [comment]
For whoever reviews this, I don't think the questions of 

```
Have you validated your manifest locally with winget validate --manifest <path>?
Have you tested your manifest locally with winget install --manifest <path>?
Does your manifest conform to the 1.6 schema?
```

as this update was created with the [wingetcreate](https://github.com/microsoft/winget-create) tool

**Comment by stephengillie** [comment]
Hi @beeradmoore,

> For whoever reviews this, I don't think the questions of
> 
> ```
> Have you validated your manifest locally with winget validate --manifest <path>?
> Have you tested your manifest locally with winget install --manifest <path>?
> Does your manifest conform to the 1.6 schema?
> ```
> 
> as this update was created with the [wingetcreate](https://github.com/microsoft/winget-create) tool

Please understand that regardless of how the manifest is created and submitted, these questions are still valid. A manifest creation tool might take care of some of these questions, but the submitter is ultimately responsible for ensuring that the submitted manifest is valid and has been tested. Manifests which don't meet these might not be accepted, or might need significant modifications after initial submission.

**Review by stephengillie — APPROVED** [review]

**Comment by beeradmoore** [comment]
Thanks for the info @stephengillie. Next update I'll go through the steps of answering those questions better, and also filing an issue with the microsoft/wingetcreate team and see if manifest version is going to get bumped to help with the other question.

**Pull request merged**
