### PR TITLE
Added /NORUN parameter to ShareX manifest

### PR DESCRIPTION
**Pull request by Jaex**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/583)

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Validation has completed

**Comment by superusercode** [comment]
https://github.com/microsoft/winget-cli/blob/e997f3e394e66f2389f4f33f36c58b1c2768e975/src/AppInstallerRepositoryCore/Manifest/ManifestInstaller.cpp#L137-L140 @Jaex /VERYSILENT and /SILENT are both included by default, but I don't think there are any ramifications to providing the flag twice.

**Comment by Jaex** [comment]
> https://github.com/microsoft/winget-cli/blob/e997f3e394e66f2389f4f33f36c58b1c2768e975/src/AppInstallerRepositoryCore/Manifest/ManifestInstaller.cpp#L137-L140 @Jaex /VERYSILENT and /SILENT are both included by default for the inno installertype, but I don't think there are any ramifications to providing the flag twice.

Those default flags are not included when you override switch to add new flag.
But still I tested it now without add silent flag and indeed I was right, installer not run as silent.

**Comment by superusercode** [comment]
@Jaex is the Custom switch field what you need then? seen in the spec here: https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv0.1.md

**Pull request merged**
