### PR TITLE
Update Piriform.CCleaner 6.22

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/151517)

### CODE REVIEW

**Comment by aisgbnok** [comment]
I based my implementation of `InstallationMetadata` off of:

https://github.com/microsoft/winget-cli/blob/2ea30553b333b00e631ec49529bf765c0dd4b008/src/WinGetUtilInterop.UnitTests/TestCollateral/V1_6ManifestMerged.yaml#L119-L125

But I assume you noticed that #150484 is still not fixed. Maybe you can figure something out that I could not.

**Review by stephengillie — APPROVED** [review]

**Comment by Trenly** [comment]
> I based [my implementation](https://github.com/microsoft/winget-pkgs/issues/150484#issuecomment-2073015348) of `InstallationMetadata` off of:
> 
> https://github.com/microsoft/winget-cli/blob/2ea30553b333b00e631ec49529bf765c0dd4b008/src/WinGetUtilInterop.UnitTests/TestCollateral/V1_6ManifestMerged.yaml#L118-L125
> 
> But I assume you noticed that #150484 is still not fixed. Maybe you can figure something out that I could not.
> 
> I'm assuming that this is related to #150484, but if not then just ignore my comment.

Yeah, for some reason it isn’t detecting Ccleaner 6.22 at all in my VM, so seeing if changing this helps

**Comment by Trenly** [comment]
@aisgbnok - Seems like using single quotes with the single backslash worked

```
PS C:\Windows\System32> winget install Piriform.CCLeaner --version 6.22
Found CCleaner [Piriform.CCleaner] Version 6.22
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.ccleaner.com/ccsetup622.exe
  ██████████████████████████████  79.5 MB / 79.5 MB
Successfully verified installer hash
Starting package install...
Successfully installed
PS C:\Windows\System32> winget upgrade
Name                  Id                    Version        Available
-------------------------------------------------------------------------
CCleaner              Piriform.CCleaner     6.22           6.23
Microsoft.UI.Xaml.2.7 Microsoft.UI.Xaml.2.7 7.2109.13004.0 7.2208.15002.0
2 upgrades available.
```

**Comment by aisgbnok** [comment]
> @aisgbnok - Seems like using single quotes with the single backslash worked

That's great news.

**Comment by aisgbnok** [comment]
@Trenly,

Though, I'm not sure. How did it work without being published first? Maybe I'm confused.

**Comment by Trenly** [comment]
> @Trenly,
> 
> Though, I'm not sure. How did it work without being published first? Maybe I'm confused.

I tested using a local version of the manifest

**Pull request merged**
