### PR TITLE
New Package: JetBrains.DataSpell version 213.1558.17

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/25553)

### CODE REVIEW

**Review by jedieaston — CHANGES_REQUESTED** [review]
The JetBrains site seems pretty clear that this is a private installer intended only for people in the private beta. Are we good to put this in the repo? (I currently do not have an invite so I can't confirm if there is an NDA or not).

**Comment by denelon** [comment]
I'd agree with @jedieaston on this one. Let's hold off at least until it's a public beta.

**Comment by vedantmgoyal2009** [comment]
I am posting this comment to remove `Needs: author feedback` and `Needs-Author-Feedback` labels. Also, I have a question: Is there any reason that there are two labels for the same purpose.

**Comment by denelon** [comment]
@vedantmgoyal2009 I prefer labels without spaces as it makes it easier to "search" issues. We had code to modify and it was better to support both until it's implemented everywhere. We should be removing the label without spaces fairly soon [tm].

**Comment by vedantmgoyal2009** [comment]
> I'd agree with @jedieaston on this one. Let's hold off at least until it's a public beta.

It is public beta now. Check https://www.jetbrains.com/dataspell

**Comment by jedieaston** [comment]
That's probably fine then, although you'll have to update this PR to the new build.

**Review by ItzLevvie — APPROVED** [review]

**Comment by vedantmgoyal2009** [comment]
> @vedantmgoyal2009 I prefer labels without spaces as it makes it easier to "search" issues. We had code to modify and it was better to support both until it's implemented everywhere. We should be removing the label without spaces fairly soon [tm].

@denelon So, you have implemented this?

**Comment by denelon** [comment]
@vedantmgoyal2009 yes, I was just combing through the bot used to add most of the labels, and I've updated everything I've seen so far.

**Pull request merged**
