### PR TITLE
New version: Baidu.BaiduTranslate version 1.5.4

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | 百度翻译 |     |
| Version     | 1.5.4     |  |
| Publisher   | Baidu Translate   |       |
| ProductCode | b34156d3-fe5f-5fd2-a095-3f35d6dfc923, b34156d3-fe5f-5fd2-a095-3f35d6dfc923, b34156d3-fe5f-5fd2-a095-3f35d6dfc923, b34156d3-fe5f-5fd2-a095-3f35d6dfc923          |     |
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/64058)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by vedantmgoyal2009** [comment]
@denelon please add blocking issue...

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
