### PR TITLE
add potplayer

### PR DESCRIPTION
**Pull request by ghost1372**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/439)

### CODE REVIEW

**Comment by jazzdelightsme** [comment]
See also #403.

**Comment by ghost1372** [comment]
@msftbot url is correct but i dont know why test cant passed

**Comment by Berkeley-Reject** [comment]
> @msftbot url is correct but i dont know why test cant passed

It seems that Microsoft flagged this website `https://t1.daumcdn.net/potplayer/PotPlayer/Version/Latest/PotPlayerSetup64.exe` as unsafe.
You may report this website at [Report a website](https://feedback.smartscreen.microsoft.com/feedback.aspx?v=6&t=512&result=block&type=top&url=aHR0cHM6Ly90MS5kYXVtY2RuLm5ldC9wb3RwbGF5ZXIvUG90UGxheWVyL1ZlcnNpb24vTGF0ZXN0L1BvdFBsYXllclNldHVwNjQuZXhl).

**Comment by ghost1372** [comment]
> > @msftbot url is correct but i dont know why test cant passed
> 
> It seems that Microsoft flagged this URL `https://t1.daumcdn.net/potplayer/PotPlayer/Version/Latest/PotPlayerSetup64.exe` as unsafe.
> You may report this website at [Report a website](https://feedback.smartscreen.microsoft.com/feedback.aspx?v=6&t=512&result=block&type=top&url=aHR0cHM6Ly90MS5kYXVtY2RuLm5ldC9wb3RwbGF5ZXIvUG90UGxheWVyL1ZlcnNpb24vTGF0ZXN0L1BvdFBsYXllclNldHVwNjQuZXhl).

yes i reported
tnx

**Pull request closed without merging**
