### PR TITLE
Remove old version of JanDeDobbeleer.OhMyPosh

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
null

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
If the manifest has the correct version, it should be preserved for application downgrading purposes.

Older Visual Studio Code Insider manifests were removed because it had an incorrect version compared to what's shown in Control Panel.

**Comment by vedantmgoyal2009** [comment]
Can I remove previous versions of Microsoft.OneDriveInsiders

**Comment by ItzLevvie** [comment]
> Can I remove previous versions of Microsoft.OneDriveInsiders

Some people may want to downgrade, removing them would prevent that.

**Comment by vedantmgoyal2009** [comment]
I think we should keep older stable versions but in the case of Beta/Insider/EarlyAccess, only the latest version should be kept.

**Comment by ItzLevvie** [comment]
People like me run insider builds of various programs and may have to downgrade to older versions if the latest one has issues.

**Comment by vedantmgoyal2009** [comment]
Can you please tell me that are you an Microsoft employee or not?

**Comment by vedantmgoyal2009** [comment]
So, the last 5-6 versions should be kept, otherwise, the repository will be so huge and it would not work efficiently.

**Comment by vedantmgoyal2009** [comment]
You can consider VLC as an example.

**Comment by vedantmgoyal2009** [comment]
Daily builds of VLC:
image

**Comment by vedantmgoyal2009** [comment]
What do you say?

**Comment by ItzLevvie** [comment]
> So, the last 5-6 versions should be kept, otherwise, the repository will be so huge and it would not work efficiently. In that case, the last 5-6 versions should be kept, otherwise, the repository will be so huge and it would not work efficiently.

It's already huge, and there's no need to remove them (especially if you compare the repository to Chocolately). There's currently 7460+ versions in total for all applications in this repository; if we removed all of the versions we would be at 2000+ and that would probably make people upset because there are people that depend on these versions for compatibility reasons, etc.

Also, I believe removing older versions would also break updating and registering apps in `winget list` and prevent people from updating to newer versions.

**Comment by vedantmgoyal2009** [comment]
Total versions: 190
image

**Comment by ItzLevvie** [comment]
> What about programs like VLC nightly, which have daily builds

Same reason as above, but if the link is no longer working, wingetbot will automatically remove it. It's nothing to worry about.

**Comment by vedantmgoyal2009** [comment]
Do you know how it detects. I mean the logic it uses...

**Comment by vedantmgoyal2009** [comment]
> > What about programs like VLC nightly, which have daily builds
> 
> Same reason as above, but if the link is no longer working, wingetbot will automatically remove it. It's nothing to worry about.

Okay

**Comment by ItzLevvie** [comment]
> Do you know how it detects. I mean the logic it uses...

If you're talking about wingetbot - it checks the link and if the link's status code is 404 it'll automatically open up a PR.

Similar to mine: https://raw.githubusercontent.com/ItzLevvie/winget-pkgs-biweekly/301-302-403-404-tests/exportedDirectoriesFilesURLsWithCommand.txt?token=ACYQHNX2ETM75KALGWBNRN3A7BBIG

**Comment by vedantmgoyal2009** [comment]
Seems like you have kept the repository private. As I am new, I don't know what it is all about. Please explain it to me in detail.

**Comment by ItzLevvie** [comment]
Basically, just grab download links from all manifests and use cURL (which is built into Windows) to check each of them.

You'll be downloading about 7600+ applications which will use up quite a lot of storage space and bandwidth.

**Comment by vedantmgoyal2009** [comment]
Can you share the code with me?

**Comment by ItzLevvie** [comment]
At the moment, no, but I'll most likely open-source it in the future.

If you want to make one then I would suggest you to not to, you'll run into issues with user agent strings and most likely end up with various errors with the way URLs are parsed, etc.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
PR should be closed now.

**Comment by vedantmgoyal2009** [comment]
Ok, can you give me any mode of contact so that I can contact you for any help. It's difficult to track on GitHub.

**Comment by ItzLevvie** [comment]
> Ok, can you give me any mode of contact so that I can contact you for any help. It's difficult to track on GitHub.

I won't be able to give that out, sorry.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
See https://github.com/microsoft/winget-pkgs/pull/20906#pullrequestreview-706415548.

**Comment by vedantmgoyal2009** [comment]
> If you want to make one then I would suggest you to not to, you'll may run into issues with user agent strings and will most likely end up with various errors with the way URLs are being parsed in your code, etc.

It would be helpful if you told me how to make one.

**Comment by ItzLevvie** [comment]
Grab URLs using the `type` command or `winget show --manifest <DIRECTORY_PATH_TO_MANIFEST>` and then filter the rest of the information out using the `find` command for all manifests and then download each application and if it errors out then remove it from the repo.

**Comment by vedantmgoyal2009** [comment]
Can I use `grep`?

**Comment by vedantmgoyal2009** [comment]
> It's quite similar to mine: https://raw.githubusercontent.com/ItzLevvie/winget-pkgs-biweekly/301-302-403-404-tests/exportedDirectoriesFilesURLsWithCommand.txt?token=ACYQHNX2ETM75KALGWBNRN3A7BBIG

I guess you are using GitHub Actions. You are doing the following things:
`git clone microsoft/winget-pkgs`
`cd winget-pkgs/manifests`
Running a script in which you get URLs and testing HTTP response code
And, save the output to a file.txt in your repository

Am I right?

**Comment by ItzLevvie** [comment]
GitHub Actions with on a Windows VM.

I don't clone the repo (but if you do, run it with `--depth 1 --single-branch` as I do the URLs manually and then upload it to GA to test to save 1 hour of time.

The issue with grep is that it won't be able to find Installer URLs that are on a new line after `InstallerUrl:` (i.e. some Visual Studio manifests) hence why `winget show --manifest` is better.

**Comment by vedantmgoyal2009** [comment]
Can you tell me how to setup a VM on GitHub?

**Comment by vedantmgoyal2009** [comment]
Also, can we make a bash script for it and run it in codespaces?

**Comment by ItzLevvie** [comment]
No, because you'll run out of storage with the free and education version of GitHub Actions & GitHub Codespaces. Most CI/CD agents have storage limits to prevent abuse.

I'm using a Microsoft Azure VM (which I linked to GitHub Actions so I can see what's happening in real-time without having to use RDP) from https://azure.microsoft.com/en-us/pricing/details/virtual-machines/windows/.

Just wait till wingetbot or my project is open-source that should make it easier to make your own tools. This is better suited for Community Moderators to remove manifests that are no longer working.

**Comment by vedantmgoyal2009** [comment]
Are you am Microsoft employee?

**Comment by ItzLevvie** [comment]
Yes, I'm employee on a contractor role.

**Comment by vedantmgoyal2009** [comment]
That's why you have no problem in paying for MS Azure.

**Comment by vedantmgoyal2009** [comment]
> Any career related questions should be on Reddit though.
I am just a 13-year old child and have much more journey to cover.

**Comment by vedantmgoyal2009** [comment]
You have made all things automated, that's why you are a top contributor.

**Comment by ItzLevvie** [comment]
> You have made all things automated, that's why you are a top contributor and I am still 12th.

My PRs are all manual not automated :). I haven't enough time to automate it yet using GitHub CLI.

**Comment by vedantmgoyal2009** [comment]
But the speed when you opened PRs of Deleting old manifests of VSCode.Insiders was extremely fast.

**Comment by ItzLevvie** [comment]
I opened up 25+ browser tabs :)

Anyways, let's not talk here.

**Comment by vedantmgoyal2009** [comment]
Are you on reddit?

**Comment by ItzLevvie** [comment]
I don't but you should be able to find employees at r/cscareerquestions or r/microsoft.

**Comment by vedantmgoyal2009** [comment]
> Grab URLs using the `type` command or `winget show --manifest <DIRECTORY_PATH_TO_MANIFEST>` (this is the recommended method even though it's way slower than `type` because you won't have trailing spaces and whitespace issues) and then filter the rest of the information out using the `find` command for all manifests and then download each application using cURL or wget and if it errors out then remove it from the repo.

Can you please tell me the regular expressions used to grab URLs. Please 🙏

**Comment by ItzLevvie** [comment]
Have you read my messages above 🤔? 

I'm not using registry expressions, but I'll post instructions (if my repository goes public) whenever I get around to it which might be in the next couple or several months. 

As I said previously, you could potentially wait for wingetbot to be open-source because that's likely much better than what I've put together.

I appreciate you wanting to help, and I wish I could help you right now, but I sadly don't have the time to publish the entire instructions due to how busy I am. Please be patient - I don't have a lot of free-time to help people :)

**Comment by vedantmgoyal2009** [comment]
Sorry for commenting here again but please accept my invite to my private repository. There I have created a script that tests all download URLs and writes output to a file (just as your script 🙂). Please help me and suggest changes wherever you like. Thanks.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
