### PR TITLE
Correct Variable Name [YamlCreate.ps1]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23271)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Waiting for @OfficialEsco's approval & @denelon's merge next week.

EDIT: Oops, meant to click on the "Comment" button rather than the "Requires changes" button.

**Review by ItzLevvie — DISMISSED** [review]

**Review by OfficialEsco — DISMISSED** [review]
o_O I've not used this version since the YamlParsing came out so i had no idea about this

**Comment by denelon** [comment]
@vedantmgoyal2009 mention me again after OfficialEsco provides his 👍 

I'm still about 800 messages behind from taking last week off.  As an FYI, I'm taking next week off until August 17th as well. I had a split vacation/holiday this year.

**Review by OfficialEsco — APPROVED** [review]
This is a safe change so yeah, unless https://github.com/microsoft/winget-pkgs/pull/21204 can get merged which is working very smoothly

**Comment by vedantmgoyal2009** [comment]
@denelon Esco has approved these changes.

**Review by denelon — APPROVED** [review]

**Pull request merged**
