### PR TITLE
Add version: Telegram.Unigram version 10.7.0.9893

### PR DESCRIPTION
**Pull request by rakleed**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/148926)

### CODE REVIEW

**Comment by rakleed** [comment]
.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-04-12 12:41:36.283 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFA5917C11F: (caller: 00007FFA58F08D6F) LogHr(1) tid(fec) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFA59082B08: (caller: 00007FFA5912BC20) Exception(1) tid(fec) 8A15005E ] 
> 2024-04-12 12:41:36.283 [REPO] Failed to open available source: msstore
> 2024-04-12 12:41:39.983 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFA5917C11F: (caller: 00007FFA58F08D6F) LogHr(1) tid(70c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFA59082B08: (caller: 00007FFA5912BC20) Exception(1) tid(70c) 8A15005E ] 
> 2024-04-12 12:41:39.983 [REPO] Failed to open available source: msstore
> 2024-04-12 12:41:42.670 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFA5917C11F: (caller: 00007FFA58F08D6F) LogHr(1) tid(18f0) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFA59082B08: (caller: 00007FFA5912BC20) Exception(1) tid(18f0) 8A15005E ] 
> 2024-04-12 12:41:42.670 [REPO] Failed to open available source: msstore
> 2024-04-12 12:41:49.897 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFA4135C11F: (caller: 00007FFA410E8D6F) LogHr(1) tid(1f78) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFA41262B08: (caller: 00007FFA4130BC20) Exception(1) tid(1f78) 8A15005E ] 
> 2024-04-12 12:41:49.897 [REPO] Failed to open available source: msstore
> 2024-04-12 12:42:15.996 [CORE] Deployment operation #4: Windows cannot install package TelegramFZ-LLC.Unigram_10.7.0.9893_x64__1vfw5zm9jmzqy because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.30704.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00" currently installed are: {Microsoft.VCLibs.140.00_14.0.27323.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.29231.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.30035.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.30035.0_x86__8wekyb3d8bbwe}
> 2024-04-12 12:42:15.997 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!00007FFA411E3F75: (caller: 00007FFA4113A720) Exception(2) tid(1f78) 80073CF3 Package failed updates, dependency or conflict validation.
> 2024-04-12 12:42:16.123 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFA411E2D2F: (caller: 00007FFA411E432C) Exception(3) tid(1f78) 80073CF1 Package was not found.
> 2024-04-12 12:42:16.123 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(126)\WindowsPackageManager.dll!00007FFA41358931: (caller: 00007FFA411E5853) LogHr(2) tid(1f78) 80073CF1 Package was not found.
>     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFA411E2D2F: (caller: 00007FFA411E432C) Exception(3) tid(1f78) 80073CF1 Package was not found.
> 2024-04-12 12:42:16.130 [CLI ] MSIX installer failed: 2147958003

(Automated response - build 876.)

**Comment by rakleed** [comment]
I guess the same issue again: https://github.com/microsoft/winget-pkgs/pull/142909#issuecomment-1984936429

**Comment by stephengillie** [comment]
The error here also seems somewhat similar (involving the same dependency, under another name): 
- https://github.com/microsoft/winget-pkgs/pull/148226

**Pull request closed without merging**
