### PR TITLE
Add Postman.Postman 10.9.0

### PR DESCRIPTION
**Pull request by rodrigoborgesdeoliveira**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://api.github.com/repos/microsoft/winget-pkgs/pulls/95334)

### CODE REVIEW

**Comment by rodrigoborgesdeoliveira** [comment]
Not sure what the issue with the `validation-pipeline.yaml` is since it hasn't been changed in this PR.

**Comment by denelon** [comment]
I'm just seeing this for the first time myself. I'm not sure if something is misconfigured or not.

**Comment by Trenly** [comment]
Definitely something weird going on with the bot; I'm seeing it hit triggers that it shouldn't and also missing a lot of triggers it should be hitting

**Comment by Trenly** [comment]
@msftbot reset feedback

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
