### PR TITLE
Remove: Martchus.syncthingtray `.validation`

### PR DESCRIPTION
**Pull request by aisgbnok**
Removes `manifests/m/Martchus/syncthingtray/.validation`.

- https://github.com/microsoft/winget-pkgs/pull/196517#issuecomment-2520065535

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/196886)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 902)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 903)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 903)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 903)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 904)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
