### PR TITLE
Taiga : Update to 1.4.0 and remove older version

### PR DESCRIPTION
**Pull request by Witchilich**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----
The app only has one download link that always points to the latest version. So older version has to be removed.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/87245)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by sitiom** [comment]
> The app only has one download link that always points to the latest version.

Note: Older releases can be found at https://github.com/erengy/taiga/releases

**Comment by Witchilich** [comment]
> > The app only has one download link that always points to the latest version.
> 
> Note: Older releases can be found at https://github.com/erengy/taiga/releases

My bad. If you check the dates, it seems like 20 days ago(that's still 3 days after the latest version) he added the binaries to the current and older versions in GitHub. Previously GitHub only published tarballs of the source code for each version.

**Comment by sitiom** [comment]
Checking on the [Wayback Machine](https://web.archive.org/web/20201210085540/https://github.com/erengy/taiga/releases), the binaries were definitely there, but the older binaries were recently renamed to match the `TaigaSetup_<version>.exe` format.

**Comment by Witchilich** [comment]
> Checking on the [Wayback Machine](https://web.archive.org/web/20201210085540/https://github.com/erengy/taiga/releases), the binaries were definitely there (except for 1.3), but the older binaries were recently renamed to match the `TaigaSetup_<version>.exe` format.

Even in the link you gave me, only for beta releases.
Screenshot_20221125-093323~2
When I made this PR, there were no binaries. 3 days later, he added binaries for 1.4.0 and older stable versions.

**Comment by sitiom** [comment]
Go to the [previous](https://web.archive.org/web/20201210085552/https://github.com/erengy/taiga/releases?after=v1.2.2) [pages](https://web.archive.org/web/20201210091151/https://github.com/erengy/taiga/releases?after=v1.1.4), you would see the older binaries there

**Comment by Witchilich** [comment]
> Go to the [previous](https://web.archive.org/web/20201210085552/https://github.com/erengy/taiga/releases?after=v1.2.2) [pages](https://web.archive.org/web/20201210091151/https://github.com/erengy/taiga/releases?after=v1.1.4), you would see the older binaries there

The previous stable version, 1.3.1 didn't have any binaries for 4 years. And when I made this PR, neither did 1.4.0.

**Pull request merged**
