### PR TITLE
Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\4.12

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114104&drop=dogfoodAlpha

### CODE REVIEW

**Review by ImJoakim — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Exception Message: The request timed out after 60 seconds as no response was received. (type TimeoutException)

**Pull request merged**
