### PR TITLE
New version: goplus.gop 1.2.0-pre.2

### PR DESCRIPTION
**Pull request by cpunion**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136942)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 669.)

**Comment by cpunion** [comment]
> Manual Validation ended with:
> 
> > PS C:\Users\User\Desktop> C:\Users\User\AppData\Local\Microsoft\WinGet\Links\gop.exe 2024/01/29 15:41:41 GOMODCACHE not found: exec: "go": executable file not found in %PATH% panic: GOMODCACHE not found: exec: "go": executable file not found in %PATH%   goroutine 1 [running]: log.Panicln({0xc000121db0?, 0x2?, 0xc000121dd0?})         /opt/hostedtoolcache/go/1.21.6/x64/src/log/log.go:446 +0x5a github.com/goplus/mod/modcache.getGOMODCACHE()         /home/runner/go/pkg/mod/github.com/goplus/mod@v0.12.3/modcache/cache.go:43 +0x138 github.com/goplus/mod/modcache.init()         /home/runner/go/pkg/mod/github.com/goplus/mod@v0.12.3/modcache/cache.go:33 +0xf
> 
> (Automated response - build 677.)

@stephengillie I just tested installation:
image

This package depends `GoLang.Go` package, so install `goplus.gop` also installs `GoLang.Go`. 

After installation and open a new cmd window, I can run `gop` and `go` command.

**Comment by cpunion** [comment]
Oh, seems it blocked by Windows Security.

**Comment by stephengillie** [comment]
Hi @cpunion, 

I meant to reply earlier. The package works from its full install location, but the symlink doesn't work. This is a known issue we're working to resolve.

**Pull request closed without merging**
