### PR TITLE
New Version: Sigil-Ebook.PageEdit version 2.3.0

### PR DESCRIPTION
**Pull request by dougmassay**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/168593)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Programs\PageEdit\PageEdit.exe returned exit code: -1073741515
> Executable C:\Users\validator\AppData\Local\Programs\PageEdit\QtWebEngineProcess.exe returned exit code: -1073741515

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 887.)

**Comment by dougmassay** [comment]
Curious why all checks are green (including installer validation), yet there appears to be a validation-executable-error label?

I doubt it's the vcredist issue as I use the exact same strategy with Sigil-Ebook.Sigil, which has the exact same dependencies: https://github.com/microsoft/winget-pkgs/pull/168149 . Both use the same vcredist dependency for the machine scope, but not the user scope (because no winget Microsoft.VCRedist.2015+.x64 package exists for a user scope installation). Specifying a dependency of Microsoft.VCRedist.2015+.x64 for a user scope installation has historically resulted in complete validation failure.

I've no idea why this is failing for PageEdit when Sigil uses the exact same strategy of limiting the Microsoft.VCRedist.2015+.x64 dependency to the machine scope successfully.

All of this is rather pointless since the minimum Windows 10 version specified in my manifests guarantee that my software can only be installed on machines that already have VCRedist.2015+.x64 installed by default.

**Comment by dougmassay** [comment]
I'll try making the change to requiring the vcredist dependency for both scopes, but doing so was exactly why past PRs (for both Sigil and PageEdit) were failing.

**Comment by dougmassay** [comment]
Seems like a bit of a catch-22 to me. The Microsoft.VCRedist.2015+.x64 package is needed for the test run of the user scope installation to succeed; and yet making Microsoft.VCRedist.2015+.x64 a dependency of the user scope installation causes the installer validation to fail because there is no user scope package available in a user scope install.

Here's to hoping that an order of operations loophole works like it seems to with the Sigil-Ebook.Sigil manifest.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Programs\PageEdit\PageEdit.exe returned exit code: -1073741515
> Executable C:\Users\validator\AppData\Local\Programs\PageEdit\QtWebEngineProcess.exe returned exit code: -1073741515

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 887.)

**Comment by dougmassay** [comment]
I'm afraid I'm terribly confused. All checks are passing. Green checkmarks all around. The only exception being a _warning_ on the installation validation check. But it still passes. So why is that warning being treated as a blocking error?

The bottom line is that I can't install the Microsoft.VCRedist.2015+.x64 package as a dependency in the user scope installation. The pipeline won't let me. I've proven that. So where do we go from here? I'm not willing to drop the user scope installation merely because the publishing pipeline logic is badly broken where scope and vcredist package dependencies are concerned.

**Review by stephengillie — APPROVED** [review]

**Comment by dougmassay** [comment]
> I wanted to check if this package was having an issue with the symlink reaching its DLLs. But I do not mean to block, and haven't had a chance to check, so I'll simply approve.

Thanks much!

**Pull request merged**
