### PR TITLE
Microsoft.BingWallpaper version 2.0.0.6

### PR DESCRIPTION
**Pull request by KarbitsCode**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/160817)

### CODE REVIEW

**Comment by stephengillie** [comment]
> 7/1/2024 1:15:40 AM
Installer Verification Analysis Context Information: 
Installer https://download.microsoft.com/download/2/5/2/252967a0-bd0f-4899-b1bd-1e46e19b07bf/Installer/2.0.0.6/Bing/W011/BingWallpaper.exe
Scan request id: 'fe0a5230-04e6-4271-aed9-bf1f43bfa0f6'
Error information: BlockingDetectionFound

**Comment by KarbitsCode** [comment]
I really don't know what to do about this. Do we have any workaround? Or should I just close this PR?

**Comment by stephengillie** [comment]
> 7/1/2024 10:12:57 PM
Installer Verification Analysis Context Information: 
Installer https://download.microsoft.com/download/2/5/2/252967a0-bd0f-4899-b1bd-1e46e19b07bf/Installer/2.0.0.6/Bing/W011/BingWallpaper.exe
Scan request id: 'a38655ae-c9fc-4166-b172-f630c26d3181'
Error information: BlockingDetectionFound

Unfortunately, I don't know what kind of blocking is being used, nor how it was detected. If you have a business or social relationship with the developer, they might be able to tell you more.

**Comment by KarbitsCode** [comment]
Closing this since there is nothing that I can do to solve this

**Pull request closed without merging**
