### PR TITLE
Submitting Alchemy Viewer 6.3.6.46699

### PR DESCRIPTION
**Pull request by AshleyStone**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2685)

### CODE REVIEW

**Comment by AshleyStone** [comment]
I removed the 32bit platform as validation complained about being able to only support one installer currently. Although, it seems I have caused another issue now.

**Comment by JohnMcPMS** [comment]
No, this is us.  We can't release a fix right now for reasons.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
