### PR TITLE
Submitting NuGetPackageExplorer version 5.8.34.0.yaml

### PR DESCRIPTION
**Pull request by NikiforovAll**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/4041)

### CODE REVIEW

**Comment by jedieaston** [comment]
@NikiforovAll The folder "NuGetPackageExplorer" needs to be inside a folder called "dotnetfoundation" (inside the root manifests folder), I think, for the validation to pass.

**Comment by NikiforovAll** [comment]
Yup, thanks for your help. 

It would be nice if you also add the label 'hacktoberfest-accepted', so this PR would count as part of hacktoberfest.

Ref: <https://hacktoberfest.digitalocean.com/hacktoberfest-update>

**Comment by jedieaston** [comment]
Since the repository is labeled with "hacktoberfest", it should be showing up in your hacktoberfest dashboard once the PR is merged. (It did for my PRs that weren't individually labeled).

**Comment by NikiforovAll** [comment]
@jedieaston. That's nice. Thanks for the clarification.

**Comment by JohnMcPMS** [comment]
The description and tags do not seem to be consistent with the package here.

**Comment by NikiforovAll** [comment]
Ref: https://github.com/NuGetPackageExplorer/NuGetPackageExplorer/issues/1011

**Pull request merged**
