### PR TITLE
​

### PR DESCRIPTION
**Pull request by ItzLevvie**
​

### CODE REVIEW

**Comment by mdanish-kh** [comment]
Yep, I'm confident this will resolve it because of https://github.com/microsoft/winget-pkgs/issues/88726#issuecomment-1398993435

**Review by mdanish-kh — APPROVED** [review]

**Review by mdanish-kh — APPROVED** [review]

**Comment by mdanish-kh** [comment]
@ItzLevvie On second thoughts, this may not be the fix; I re-call if one manifest contains `DisplayVersion`, then all manifests (including past ones) should contain this key in order to resolve the issue.

The solution may just well be to get rid of `3.0.17.4` since no other manifest requires DisplayVersion.
Ref: https://github.com/microsoft/winget-pkgs/issues/88726#issuecomment-1398993435
https://github.com/microsoft/winget-pkgs/issues/94743#issuecomment-1406868090

**Comment by mdanish-kh** [comment]
@kriswilk I actually wrote that before, but the problem is that the current 3.0.18 does require `DisplayVersion` because the version is different between the MSI (`3.0.18.0`) and the EXE (`3.0.18`) installers. We use DisplayVersion key where we want to differentiate between a marketing version and a version that is used in Apps&Features / Registry. Since we cant have the same PackageVersion for both MSIs and EXEs as they write different versions to registry, we need to use `DisplayVersion` here for the MSIs

**Comment by kriswilk** [comment]
> This discrepancy was introduced in 3.0.17.4 and we may just need to remove all manifests prior to that version for the latest ones to work correctly.

OK, now I understand the issue. Thanks for the clarification!

**Comment by kriswilk** [comment]
BTW, I notice that this PR removes the `/pub/` from all the URLs. Note that previous manifests had even simpler URLs without the `/videolan/`. However, this URL path is buggy. For instance, the 32-bit EXE URL is broken:

`https://download.videolan.org/vlc/3.0.18/win32/vlc-3.0.18-win32.exe`

I specifically used the URLs with `/pub/videolan/vlc/` because this is the URL style you get when you navigate to the release archives from the application website. I presume these are the most likely to be maintained/tested.

That said, the ones without `pub` do seem to be OK for this release. 🤷‍♂️

**Pull request merged**
