### PR TITLE
serif.affinity.photo version 2.0.0.1640

### PR DESCRIPTION
**Pull request by borque**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/89210)

### CODE REVIEW

**Comment by borque** [comment]
The installer is (legally) available from various locations. Unfortunately downloading it from the publishers site requires a previous registration. Therfor I chose to provide an url provided by the CDN of "Chip", a large german computer magazine.
The (German) www-page describing the download ca be accessed at https://www.chip.de/downloads/Affinity-Photo_103235186.html

**Comment by stephengillie** [comment]
Hi @borque,
> The installer is (legally) available from various locations. Unfortunately downloading it from the publishers site requires a previous registration. 

This scenario is sadly not supported. Requiring developer-controlled sources obviates numerous risks and liabilities. Are any of the other various download locations supported or endorsed by the developer?

**Comment by borque** [comment]
Hello @stephengilli!
I understand your concerns. I will ask in the Serif's official support forums whether there is any chance to get a "regsitration free" download from their servers or whether they agree that we use the "Chip-servers".
Is it proof enough if I post the link to the thread in the official forum here if there is a positive result?
I just need some time as I am "busy with real life" for most time of the rest of the week.

**Comment by ItzLevvie** [comment]
@msftbot Area-External

**Comment by ItzLevvie** [comment]
@msftbot Blocking-Issue

**Comment by borque** [comment]
As said before, I will try to find out what the publisher thinks about the problem. (Just posting this to prevent the issue from being closed).

**Comment by borque** [comment]
See here for details: #90542

**Pull request closed without merging**
