### PR TITLE
New version: dorssel.usbipd-win version 2.0.0

### PR DESCRIPTION
**Pull request by dorssel**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/41495)

### CODE REVIEW

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/41496#pullrequestreview-858158985 (you used YamlCreate 2.0.0 instead of 2.0.4)

**Comment by dorssel** [comment]
> [#41496 (review)](https://github.com/microsoft/winget-pkgs/pull/41496#pullrequestreview-858158985) (you used YamlCreate 2.0.0 instead of 2.0.4)

See discussion #41496. Turns out this new release was picked up by new automation that I wasn't aware of. I am canceling this PR when that one has completed. Automation is better...

**Comment by OfficialEsco** [comment]
> > [#41496 (review)](https://github.com/microsoft/winget-pkgs/pull/41496#pullrequestreview-858158985) (you used YamlCreate 2.0.0 instead of 2.0.4)
> 
> See discussion #41496. Turns out this new release was picked up by new automation that I wasn't aware of. I am canceling this PR when that one has completed. Automation is better...

I know :) (Its not really new either :D)
Any release via GitHub gets first priority on the Automation since its so simple, feel free you change the metadata, the automation uses the latest manifest's metadata, and notify if you want to maintain it yourself.

**Comment by OfficialEsco** [comment]
We have tried to keep the license url per version, however it gets forgotten and most people don't even look at the manifest before submitting, if you'd like you can fix the urls for the manifests (or atleast when it changes)

**Pull request closed without merging**
