### PR TITLE
ARP/ProductCode: martinchrzan.ColorPicker version 1.1.0

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/22408)

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]

**Comment by OfficialEsco** [comment]
This is actually wrong and needs special treatment

**Comment by OfficialEsco** [comment]
Since this is something you can fix instead of spamming Metadata PR's you can fix this:
Replace all the MSI's with the EXE's found on their GitHub Release page, the silent switch is `--silent`
The version is 3 digit
image
Move the MSI's to `martinchrzan.ColorPicker.MachineWide` with the PackageName `Machine-Wide Installer` to match against any version or since you have the `ProductCode` you can do `Color Picker Machine-Wide Installer` to match against any version which have a `ProductCode`.

**Comment by vedantmgoyal2009** [comment]
Ok, so you mean to move the MSI installers to `martinchrzan.ColorPicker.MachineWide` and add EXE installers to `martinchrzan.ColorPicker` with 3 digit versions and Scope:user.

**Comment by OfficialEsco** [comment]
> Ok, so you mean to move the MSI installers to `martinchrzan.ColorPicker.MachineWide` and add EXE installers to `martinchrzan.ColorPicker` with 3 digit versions and Scope:user.

Yes, could technically be `martinchrzan.ColorPicker.User` but we'll see if they find a way to merge Machine Wide installers and User Installers
My issue on this: https://github.com/microsoft/winget-pkgs/issues/14115
Related: https://github.com/microsoft/winget-cli/issues/982
Suggestion: https://github.com/microsoft/winget-cli/issues/1073
Included in Manifest Schema v1.1.0 https://github.com/microsoft/winget-cli/issues/1243

Nevermind the `martinchrzan.ColorPicker.MachineWide` suggestion, add the User install in the Manifest and keep the MSI version, then we can fix this once v1.1.0 comes out

**Comment by OfficialEsco** [comment]
Add uninstallPrevious as the upgrade behavior for the MSI
image

**Comment by vedantmgoyal2009** [comment]
Well, I will have to delete the existing manifests and then add all manifests again in separate PRs.

**Comment by vedantmgoyal2009** [comment]
If you can approve #22411 #22412 #22413 #22414 #22415 #22416 #22418 #22419 #22420 #22421 otherwise new PRs will be flagged as duplicates.

**Comment by OfficialEsco** [comment]
> If you can approve #22411 #22412 #22413 #22414 #22415 #22416 #22418 #22419 #22420 #22421 otherwise new PRs will be flagged as duplicates.

Hold up, what kind of folder structure are you going to do?

**Comment by vedantmgoyal2009** [comment]
I will out EXE installers under martinchrzan.ColorPicker.User and MSI installers under martinchrzan.ColorPicker.MachineWide

**Comment by OfficialEsco** [comment]
> I will put EXE installers under `martinchrzan.ColorPicker.User` and MSI installers under `martinchrzan.ColorPicker.MachineWide`

Ahh sorry for confusing you, because https://github.com/microsoft/winget-cli/issues/1243 will be implemented Soon™ we can do both in martinchrzan.ColorPicker

**Comment by vedantmgoyal2009** [comment]
Please explain to me from the beginning what you want to say.

**Comment by OfficialEsco** [comment]
When i follow this thread:
>My issue on this: #14115
>Related: microsoft/winget-cli#982
>Suggestion: microsoft/winget-cli#1073
>Included in Manifest Schema v1.1.0 microsoft/winget-cli#1243
>
>Nevermind the martinchrzan.ColorPicker.MachineWide suggestion, add the User install in the Manifest and keep the MSI version, then we can fix this once v1.1.0 comes out

i realized the fix was close, therefore you can add the EXE and MSI in `martinchrzan.ColorPicker` under the MSI Version name

**Comment by vedantmgoyal2009** [comment]
Ok, so you approve the PRs and I will create new PRs with EXE and MSI installers under the MSI version name. Because I deleted my manifests it will time taking to revert commits rather than creating them from scratch.

**Comment by denelon** [comment]
@OfficialEsco the bot just can't keep up with you 😂

**Pull request merged**
