### PR TITLE
 Update QuickLook to version 3.6.9 

### PR DESCRIPTION
**Pull request by admcpr**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1241)

### CODE REVIEW

**Comment by adam7** [comment]
Issue opened with QuickLook https://github.com/QL-Win/QuickLook/issues/663
I'll update once the issue is resolved

**Comment by adam7** [comment]
So this pull request is doomed. SmartScreen is always going to fail unless the quicklook msi is built with a cert which costs hundreds of dollars. No open source developer is going to pay for that so the only way for the msi to get past SmartScreen is for it to be submitted for analysis for every version. Since you can't automate that process, that is also never going to happen. 

Fundamentally this process seems to be broken. All the other PRs with the  [Validation-SmartScreen](https://github.com/microsoft/winget-pkgs/labels/Validation-SmartScreen) seem to support that opinion.

**Comment by superusercode** [comment]
@adam7 I've been pretty successful with getting windows smartscreen clearance on a bunch of my pullrequests.

For instance, the second time I summited buttercup I put this as my explanation for the incorrect detection

> Open source project https://github.com/buttercup/buttercup-desktop submitting to get smartscreen clearance so I can submit this application to the windows package manager

image

and then they used the rep from previous releases to establish rep on the new ones.

If doing this for every release isn't ideal, maybe ask the developer for the MSIX release of quicklook that is signed by the microsoft store. If they publish it in releases (see musicbrainz picard) you should then be able to use that for submitting to winget and get around the smartscreen issue.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
