### PR TITLE
New package: Dev47Apps.DroidCamOBS version 2.3.2

### LINKED ISSUE #22977: droidcamobs Request
PackageIdentifier: Droidcamobs
PackageVersion: 1.3
PackageLocale: en-US
Publisher: droidcamobs
PackageName: droidcamobs
License: open source
ShortDescription: webcam emulator between smartphone and pc
Installers:

Architecture: x64
InstallerType: exe
InstallerUrl: https://files.dev47apps.net/obs/DroidCamOBS.Setup.1.3.exe
ManifestType: singleton
ManifestVersion: 1.0.0

### PR DESCRIPTION
**Pull request by Trenly**
﻿Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

* Resolves #22977

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/151662)

### CODE REVIEW

**Comment by stephengillie** [comment]
Does this require a hardware device for the plugin to be seen? I tried adding a video device: 
image

The changed files scan found numerous plugins, but not this one, in `/obs-plugins`. Should this be validated in another way? 

Verify: 
image

**Comment by Trenly** [comment]
@stephengillie - This is just the plugin, I believe the mobile app is needed to connect a phone as a hardware device. I don't know much about the plugin, perhaps @dtantono does as the submitter of the linked issue, but since it installed and wrote an ARP entry, it seemed fine enough to me

**Comment by stephengillie** [comment]
> @ stephengillie - This is just the plugin,

Yes, and I don't see its files in the file system.

**Comment by Trenly** [comment]
> > @ stephengillie - This is just the plugin,
> 
> Yes, and I don't see its files in the file system.

Looks like the `/S` switch may be broken then. I've sent an email to the publisher

[Policy] Installer Issue

**Pull request closed without merging**
