### PR TITLE
New version: Jackett.Jackett version 0.21.1650

### PR DESCRIPTION
**Pull request by ilike2burnthing**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137255)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @ilike2burnthing,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 684.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-30 22:09:02.952 [FAIL] Installer failed security check. Url: https://github.com/Jackett/Jackett/releases/download/v0.21.1650/Jackett.Installer.Windows.exe Result: 0x80004005

(Automated response - build 684.)

**Comment by ilike2burnthing** [comment]
🙄

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
