### PR TITLE
Remove version: LDraw.AIOI.2023 version 2023-02 v1

### PR DESCRIPTION
**Pull request by DuckDuckStudio**
It return 404.

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/201285)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: - https://www.ldraw.org/files/aioi/LDraw_All-In-One-Installer_2023-02_setup_64Bit_v1.exe 
Invalid URI: The URI scheme is not valid.

(Automated message - build 924)

**Comment by stephengillie** [comment]
Hi @DuckDuckStudio,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 931.)

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
[Policy] Reset Labels
[Policy] Reset Feedback

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
