### PR TITLE
Update SandboxTest.ps1

### PR DESCRIPTION
**Pull request by lars-nvhgroup**
Added "--accept-package-agreements".
It will fail if tested manifest depend on a package with an EULA.

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/183845)

### CODE REVIEW

**Comment by denelon** [comment]
@Trenly it's a trivial change, but I wanted you to take a quick peek.

**Comment by Trenly** [comment]
It looks fine to me; The only real question I have is if theres any value in being able to test that the agreements flow works as expected and shows the information as expected. Having this parameter absent doesn’t cause the script or install to fail, it just means that whomever is testing has to interact with the sandbox and agree to the package agreements

**Comment by lars-nvhgroup** [comment]
> It looks fine to me; The only real question I have is if theres any value in being able to test that the agreements flow works as expected and shows the information as expected. Having this parameter absent doesn’t cause the script or install to fail, it just means that whomever is testing has to interact with the sandbox and agree to the package agreements

Not exactly, you can't accept eulas on dependencies, it will just fail in those cases.

**Comment by lars-nvhgroup** [comment]
> > It looks fine to me; The only real question I have is if theres any value in being able to test that the agreements flow works as expected and shows the information as expected. Having this parameter absent doesn’t cause the script or install to fail, it just means that whomever is testing has to interact with the sandbox and agree to the package agreements
> 
> Not exactly, you can't accept eulas on dependencies, it will just fail in those cases.

A switch would also work, but that's a bigger change.

**Comment by Trenly** [comment]
> > It looks fine to me; The only real question I have is if theres any value in being able to test that the agreements flow works as expected and shows the information as expected. Having this parameter absent doesn’t cause the script or install to fail, it just means that whomever is testing has to interact with the sandbox and agree to the package agreements
> 
> Not exactly, you can't accept eulas on dependencies, it will just fail in those cases.

This will be resolved in WinGet-1.9

**Comment by lars-nvhgroup** [comment]
> > > It looks fine to me; The only real question I have is if theres any value in being able to test that the agreements flow works as expected and shows the information as expected. Having this parameter absent doesn’t cause the script or install to fail, it just means that whomever is testing has to interact with the sandbox and agree to the package agreements
> 
> > 
> 
> > Not exactly, you can't accept eulas on dependencies, it will just fail in those cases.
> 
> 
> 
> This will be resolved in WinGet-1.9

When will it be released?

**Comment by denelon** [comment]
We're planning to release WinGet 1.9 on the 29th of October.

**Comment by Trenly** [comment]
@denelon - This can be merged

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
[Policy] Needs-Manual-Merge

**Pull request closed without merging**
