### PR TITLE
add rust-up-init-1.21.1

### PR DESCRIPTION
**Pull request by CGQAQ**
add rust-up-init-1.21.1 (7832b2ebe 2019-12-20) (latest version)

a convenient setup tool for rust toolchain

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1103)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
The versioning scheme is not following the pattern in the schema.  Is there a reason to include the brackets?  1.21.1 (7832b2ebe 2019-12-20).yaml 
Our pattern is to be 1.22.1 only and the file name 1.22.1.yaml.  Thanks

**Comment by CGQAQ** [comment]
> 
> 
> The versioning scheme is not following the pattern in the schema. Is there a reason to include the brackets? 1.21.1 (7832b2ebe 2019-12-20).yaml
> Our pattern is to be 1.22.1 only and the file name 1.22.1.yaml. Thanks

@KevinLaMS Already fixed

**Comment by KevinLaMS** [comment]
Not sure why this is failing.  Will need to investigate more.

**Comment by CGQAQ** [comment]
> This pull request has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **7 days**. It will be closed if no further activity occurs **within 7 days of this comment**.

.

**Comment by CGQAQ** [comment]
> Not sure why this is failing. Will need to investigate more.

@KevinLaMS Any updates on investigating?

**Comment by denelon** [comment]
@CGQAQ can you convert the file to text UTF-8?

**Comment by CGQAQ** [comment]
> 
> 
> @CGQAQ can you convert the file to text UTF-8?

sure

**Comment by KevinLaMS** [comment]
I cannot get this to install.  The client is giving error 1.

**Comment by CGQAQ** [comment]
> I cannot get this to install. The client is giving error 1.

@KevinLaMS  I think its a bug

image

because I manually downloaded it from the URL inside YAML file, it installed perfectly

**Comment by KevinLaMS** [comment]
Interesting.  Seems to be blocking on missing VC as part of install.  So there is a dependency that is missing.

**Comment by CGQAQ** [comment]
> Interesting. Seems to be blocking on missing VC as part of install. So there is a dependency that is missing.

@KevinLaMS Is there a verbose mode for `winget install` or something like that?
image
I think I will create another issue to point out this issue

**Comment by denelon** [comment]
This PR is a bit old :smile:

I'm not sure if we still need support for dependencies or just to configure the result "1" as a success error code (if that is a success).

In either case, the manifest schema needs to be updated.

**Pull request closed without merging**
