### PR TITLE
New version: LinwoodCloud.Butterfly.Nightly version 2.2.0-rc.0

### PR DESCRIPTION
**Pull request by CodeDoctorDE**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/173740)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334972
> 2024-09-16 00:58:49.941 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x64 with version 14.40.33810.0

Automated error analysis suggests -1978334972 may mean This package has a dependency missing from your system.

(Automated response - build 895.)

**Comment by CodeDoctorDE** [comment]
Why does it not merge the pr?

**Comment by stephengillie** [comment]
Because the merge conditions have not been met. I believe they are https://github.com/microsoft/winget-pkgs/labels/Moderator-Approved and https://github.com/microsoft/winget-pkgs/labels/Validation-Completed labels, and almost no other labels. The pipeline run ended in the error that my automation emitted last week - the pipelines have a situation where they require that the `Scope` for the dependency matches the main installer. But here they do not match, so I must manually validate in a VM.

**Review by stephengillie — APPROVED** [review]

**Comment by CodeDoctorDE** [comment]
Hmm there is already a new one for the second release candiate #174722

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/163098

**Pull request merged**
