### PR TITLE
New version: VMware.HorizonClient version 8.7

### PR DESCRIPTION
**Pull request by auanasgheps**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/87334)

### CODE REVIEW

**Comment by auanasgheps** [comment]
Investigating. It's related to the installer itself.

**Comment by auanasgheps** [comment]
I can install the application successfully using the commands in the yaml, the install ends correctly.
However, that's what I get in the Sandbox.
If someone can help would be great
image

**Review by ItzLevvie — DISMISSED** [review]

**Comment by Trenly** [comment]
After sifting through the log in my sandbox environment, this has a dependency on the .NET Desktop Runtime. It installs fine on your desktop environment because you have the runtime installed, but the sandbox fails because it doesn't.

```
--> Configuring Winget
Admin setting enabled.

--> Installing the Manifest 8.7.0.31805

Found VMware Horizon Client [VMware.HorizonClient] Version 8.7.0.31805
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Packages
      Microsoft.DotNet.DesktopRuntime.6
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").

Do you agree to all the source agreements terms?
[Y] Yes  [N] No: y
Installing dependencies:
(1/1) Found Microsoft .NET Windows Desktop Runtime 6.0 [Microsoft.DotNet.DesktopRuntime.6] Version 6.0.11
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/6.0.11/windowsdesktop-runtime-6.0.11-win-x64.exe
  ██████████████████████████████  54.5 MB / 54.5 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Downloading https://download3.vmware.com/software/CART23FQ3_WIN_2209/VMware-Horizon-Client-2209-8.7.0-20649873.exe
  ██████████████████████████████   416 MB /  416 MB
Successfully verified installer hash
Starting package install...
Successfully installed

--> Refreshing environment variables

--> Comparing ARP Entries

DisplayName                                                        DisplayVersion Publisher             ProductCode
-----------                                                        -------------- ---------             -----------
Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.32.31332        14.32.31332    Microsoft Corporation {3407B900-37F5-4CC2-B612-5CD5D580A163}
Microsoft .NET Host FX Resolver - 6.0.11 (x64)                     48.47.50420    Microsoft Corporation {5E63E49B-C88C-46C5-855C-A7B07C11CDC8}
VMware Horizon Media Engine 15.0.0.0 (64-bit)                      15.0.0.0       VMware, Inc.          {68E893BB-BB6E-4D1C-9FC5-E4E2317064B0}
VMware Horizon HTML5 Multimedia Redirection Client                 8.7.0          VMware, Inc.          {910CBE18-3716-4812-9D75-5F12CAF33F57}
Microsoft Windows Desktop Runtime - 6.0.11 (x64)                   48.47.50419    Microsoft Corporation {A39D4115-3A27-4245-AE92-3214B8B21932}
Microsoft .NET Host - 6.0.11 (x64)                                 48.47.50420    Microsoft Corporation {B92B890A-04F2-4880-BA20-20D4364FB263}
Microsoft .NET Runtime - 6.0.11 (x64)                              48.47.50420    Microsoft Corporation {C3DD1448-513A-4DB8-978D-6991562EA63D}
VMware Horizon Client                                              8.7.0.31805    VMware, Inc.          {C8088F15-0D42-4A3A-9434-404153244125}
VMware Horizon Media Redirection for Microsoft Teams               8.7.0          VMware, Inc.          {EFFD2599-4DA5-4ED8-AE5B-F9056BD008AD}
Microsoft Visual C++ 2022 X64 Additional Runtime - 14.32.31332     14.32.31332    Microsoft Corporation {F4499EE3-A166-496C-81BB-51D1BCDC70A9}
Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.32.31332 14.32.31332.0  Microsoft Corporation {3746f21b-c990-4045-bb33-1cf98cff7a68}
VMware Horizon Client                                              8.7.0.31805    VMware, Inc.          {48700bfe-f426-4489-a3ab-c6dc87f90db6}
Microsoft Windows Desktop Runtime - 6.0.11 (x64)                   6.0.11.31823   Microsoft Corporation {c4846f79-a633-4ae4-92a3-92fdbeb33da2}
```

This needs to be added to the Installer manifest -
```
Dependencies:
  PackageDependencies:
    - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.6
```

@msftbot dependencies

**Comment by auanasgheps** [comment]
Dependecies have been added, but they're not supported yet. Waiting for #163

**Comment by ItzLevvie** [comment]
@msftbot Dependencies

**Review by ItzLevvie — APPROVED** [review]

**Comment by virtualex-itv** [comment]
this PR should be closed in favor of working [PR#88818](https://github.com/microsoft/winget-pkgs/pull/88818).

**Comment by mdanish-kh** [comment]
Close with reason: Replaced by PR 88818;

**Pull request closed without merging**
