### PR TITLE
Fix Mozilla.Thunderbird 115.6.1 languages

### PR DESCRIPTION
**Pull request by krystofkrticka**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135978)

### CODE REVIEW

**Comment by krystofkrticka** [comment]
@stephengillie Well I hope this will finally pass but it looks like validation pipeline is quite disturbed by getting this motherload of links. But unfortunately I'll have to do this again with version 115.7.0 because when winget is not installing the correct language It's quite a headache dealing with it when administering 20 or so computers.

**Comment by stephengillie** [comment]
This many InstallerUrls does seem to cause issues. Any thoughts around separating them into separate PackageIdentifiers?

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
