### PR TITLE
Add [Policy] comment triggers for moderator reviews

### PR DESCRIPTION
**Pull request by Trenly**
This is a temporary workaround for the pull request review triggers not working. It adds two new comment triggers - `[Policy] Approve` and `[Policy] Reject` which have the same functionality as a `PR Review - Approval` or a `PR Review - Changes Requested` respectively.

cc @denelon

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://api.github.com/repos/microsoft/winget-pkgs/pulls/95721)

### CODE REVIEW

**Comment by denelon** [comment]
@Trenly, I want the team to take a look to make sure it isn't going to cause any other unintended consequences.

**Comment by Trenly** [comment]
> @Trenly, I want the team to take a look to make sure it isn't going to cause any other unintended consequences.

Thanks!

**Review by mdanish-kh — COMMENTED** [review]
nit: `[Policy] Feedback` sounds more suitable to me than Reject. Reject implies closing of a PR which we can do through `Close with reason: <reason>;`

**Review by denelon — APPROVED** [review]

**Comment by mdanish-kh** [comment]
[Policy] Approve

**Comment by Trenly** [comment]
Hmm

**Comment by Trenly** [comment]
[Policy] Feedback

**Comment by mdanish-kh** [comment]
[Policy] Area-External

**Pull request merged**
