### PR TITLE
Zoom.ZoomRooms version 5.15.7

### PR DESCRIPTION
**Pull request by BrandonWanHuanSheng**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/116892)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
What is happening right over here?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335226 
2023-08-15 06:12:18.682 [CLI ] ShellExecute installer failed: 1 
image

**Comment by stephengillie** [comment]
Hi @BrandonWanHuanSheng,

Manual Validation also ended with the same error code: 1. When manually running the installer, it had many checkboxes checked that required a reboot:
image

So I'm wondering if the silent installer switches here might be leaving those checked, and that the non-zero error code might be due to the installer wanting to reboot but being unable to initiate one.

**Comment by BrandonWanHuanSheng** [comment]
Later on.

**Comment by BrandonWanHuanSheng** [comment]
I also can't find the switch command

**Comment by BrandonWanHuanSheng** [comment]
????

**Comment by stephengillie** [comment]
Sorry, I don't know where to find the installer switches for this application.

**Comment by BrandonWanHuanSheng** [comment]
> Hi @BrandonWanHuanSheng,
> 
> Manual Validation also ended with the same error code: 1. When manually running the installer, it had many checkboxes checked that required a reboot:
> image
> 
> So I'm wondering if the silent installer switches here might be leaving those checked, and that the non-zero error code might be due to the installer wanting to reboot but being unable to initiate one. 

Actually, it look like some of Zoom Room exe silent switch can‘t be found. But only MSI support reboot

**Comment by Trenly** [comment]
Stale PR; Please update or close
[Policy] Needs-Author-Feedback

**Comment by BrandonWanHuanSheng** [comment]
It looks like exe having a problem with the silent issue.

**Comment by BrandonWanHuanSheng** [comment]
How to I set the InstallerExpectedCode: 1 Does it affects msi?

**Comment by BrandonWanHuanSheng** [comment]
If I remove exe, the previous version of exe will not be able to upgrade Zoom.Rooms

**Comment by BrandonWanHuanSheng** [comment]
This zoom room changed the interface.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
