### PR TITLE
New version: zufuliu.notepad4.AVX2 version 24.11r5548

### PR DESCRIPTION
**Pull request by stevenlele**
Created in https://github.com/stevenlele/winget-update/actions/runs/11877857171
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/192062)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-11-17 02:13:26.099 [FAIL] Installer failed security check. Url: https://github.com/zufuliu/notepad4/releases/download/v24.11r5548/Notepad4_HD_de_AVX2_v24.11r5548.zip Result: 0x80004005
> 2024-11-17 02:24:51.757 [FAIL] Installer failed security check. Url: https://github.com/zufuliu/notepad4/releases/download/v24.11r5548/Notepad4_HD_fr_AVX2_v24.11r5548.zip Result: 0x80004005
> 2024-11-17 02:25:20.870 [FAIL] Installer failed security check. Url: https://github.com/zufuliu/notepad4/releases/download/v24.11r5548/Notepad4_HD_it_AVX2_v24.11r5548.zip Result: 0x80004005
> 2024-11-17 02:26:25.238 [FAIL] Installer failed security check. Url: https://github.com/zufuliu/notepad4/releases/download/v24.11r5548/Notepad4_HD_ja_AVX2_v24.11r5548.zip Result: 0x80004005
> 2024-11-17 02:30:31.252 [FAIL] Installer failed security check. Url: https://github.com/zufuliu/notepad4/releases/download/v24.11r5548/Notepad4_HD_ko_AVX2_v24.11r5548.zip Result: 0x80004005
> 2024-11-17 02:57:19.023 [FAIL] Installer failed security check. Url: https://github.com/zufuliu/notepad4/releases/download/v24.11r5548/Notepad4_HD_en_AVX2_v24.11r5548.zip Result: 0x80004005
> 2024-11-17 02:46:29.339 [FAIL] Installer failed security check. Url: https://github.com/zufuliu/notepad4/releases/download/v24.11r5548/Notepad4_HD_zh-Hans_AVX2_v24.11r5548.zip Result: 0x80004005
> 2024-11-17 02:47:56.669 [FAIL] Installer failed security check. Url: https://github.com/zufuliu/notepad4/releases/download/v24.11r5548/Notepad4_HD_zh-Hant_AVX2_v24.11r5548.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-11-18 09:56:25.471 [FAIL] Installer failed security check. Url: https://github.com/zufuliu/notepad4/releases/download/v24.11r5548/Notepad4_HD_de_AVX2_v24.11r5548.zip Result: 0x80004005
> 2024-11-18 09:59:56.763 [FAIL] Installer failed security check. Url: https://github.com/zufuliu/notepad4/releases/download/v24.11r5548/Notepad4_HD_fr_AVX2_v24.11r5548.zip Result: 0x80004005
> 2024-11-18 10:06:56.529 [FAIL] Installer failed security check. Url: https://github.com/zufuliu/notepad4/releases/download/v24.11r5548/Notepad4_HD_it_AVX2_v24.11r5548.zip Result: 0x80004005
> 2024-11-18 10:17:08.525 [FAIL] Installer failed security check. Url: https://github.com/zufuliu/notepad4/releases/download/v24.11r5548/Notepad4_HD_ja_AVX2_v24.11r5548.zip Result: 0x80004005
> 2024-11-18 10:16:13.157 [FAIL] Installer failed security check. Url: https://github.com/zufuliu/notepad4/releases/download/v24.11r5548/Notepad4_HD_ko_AVX2_v24.11r5548.zip Result: 0x80004005
> 2024-11-18 10:20:20.931 [FAIL] Installer failed security check. Url: https://github.com/zufuliu/notepad4/releases/download/v24.11r5548/Notepad4_HD_ru_AVX2_v24.11r5548.zip Result: 0x80004005
> 2024-11-18 10:24:53.960 [FAIL] Installer failed security check. Url: https://github.com/zufuliu/notepad4/releases/download/v24.11r5548/Notepad4_HD_zh-Hans_AVX2_v24.11r5548.zip Result: 0x80004005
> 2024-11-18 10:26:33.963 [FAIL] Installer failed security check. Url: https://github.com/zufuliu/notepad4/releases/download/v24.11r5548/Notepad4_HD_zh-Hant_AVX2_v24.11r5548.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 898.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-11-20 09:13:56.580 [FAIL] Installer failed security check. Url: https://github.com/zufuliu/notepad4/releases/download/v24.11r5548/Notepad4_HD_de_AVX2_v24.11r5548.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 899.)

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
