### PR TITLE
New version: DigitalOcean.Doctl version 1.116.0

### PR DESCRIPTION
**Pull request by Dvd-Znf**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/185400)

### CODE REVIEW

**Comment by Dvd-Znf** [comment]
Screenshot_2024-10-23_22-05-40
Installer fails security check...

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-10-23 12:44:03.218 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerSharedLib\SHA256.cpp(144)\WindowsPackageManager.dll!00007FFFE0D6273F: (caller: 00007FFFE0DAAEC4) Exception(1) tid(175c) 8A150040 
> 2024-10-23 12:44:07.154 [FAIL] Installer failed security check. Url: https://github.com/digitalocean/doctl/releases/download/v1.116.0/doctl-1.116.0-windows-amd64.zip Result: 0x80004005
> 2024-10-23 12:42:36.554 [FAIL] Installer failed security check. Url: https://github.com/digitalocean/doctl/releases/download/v1.116.0/doctl-1.116.0-windows-386.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-10-24 08:48:00.623 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerSharedLib\SHA256.cpp(144)\WindowsPackageManager.dll!00007FFFE07D273F: (caller: 00007FFFE081AEC4) Exception(1) tid(1bc4) 8A150040 
> 2024-10-24 08:48:04.481 [FAIL] Installer failed security check. Url: https://github.com/digitalocean/doctl/releases/download/v1.116.0/doctl-1.116.0-windows-amd64.zip Result: 0x80004005
> 2024-10-24 08:39:50.958 [FAIL] Installer failed security check. Url: https://github.com/digitalocean/doctl/releases/download/v1.116.0/doctl-1.116.0-windows-386.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Comment by Dvd-Znf** [comment]
Newer version: #185738 merged

**Pull request closed without merging**
