### PR TITLE
New version: Spicetify.Spicetify version 2.32.1

### PR DESCRIPTION
**Pull request by afonsojramos**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140239)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @afonsojramos,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 776.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-20 11:18:38.500 [CLI ] Installer [X64,portable,Unknown,] not applicable: Machine is not compatible with X64 2024-02-20 11:18:46.350 [FAIL] Installer failed security check. Url: https://github.com/spicetify/spicetify-cli/releases/download/v2.32.1/spicetify-2.32.1-windows-x32.zip Result: 0x80004005 2024-02-20 11:18:46.350 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6

(Automated response - build 776.)

**Comment by rxri** [comment]
> Hi @afonsojramos,
> 
> The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.
> 
> (Automated response - build 776.)

@stephengillie hi, spicetify maintainer here. This is clearly false positive. I already reported them to microsoft (both 2.32.0 and 2.32.1) however from what I see it's still showing as pending, so I guess this will need to wait a while?
image

**Comment by rxri** [comment]
Actually after re-scanning submittion, everything looks good in my submissions so it should be good to go for re-run 😄

**Comment by rxri** [comment]
We did not change anything between already released versions on winget and this one so idk why this happens really ^

**Comment by stephengillie** [comment]
Hi @afonsojramos,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 801.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-21 12:17:31.921 [CLI ] Installer [X64,portable,Unknown,] not applicable: Machine is not compatible with X64 2024-02-21 12:17:40.893 [FAIL] Installer failed security check. Url: https://github.com/spicetify/spicetify-cli/releases/download/v2.32.1/spicetify-2.32.1-windows-x32.zip Result: 0x80004005 2024-02-21 12:17:40.893 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6

(Automated response - build 801.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
