### PR TITLE
Add Sourcetree manifest

### PR DESCRIPTION
**Pull request by ollieharker**
- Added manifest for the SourceTree git client

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/339)

### CODE REVIEW

**Comment by ollieharker** [comment]
Phew, apologies for the mess! The issue was that *somehow* I had uploaded the file in a binary format, which it seems the Validate Manifest Pipeline did not enjoy.

**Comment by denelon** [comment]
@ollieharker were you able to do a local install it with the manifest locally? It looks like it installed, but I wasn't able to see where it installed or start it.

**Comment by ollieharker** [comment]
Aye, I was able to install the manifest locally, I also validated. :)

**Comment by ollieharker** [comment]
@denelon I've created an issue for the uploading of binary files as it seems to be affecting a lot of PRs as far as I can see. Probably isn't an issue, but will help people see where they have made a mistake - https://github.com/microsoft/winget-pkgs/issues/411

**Review by ghost — APPROVED** [review]
Validation has completed

**Comment by peter-dolkens** [comment]
Not working on a brand new install of Win 10 Enterprise for me

**Pull request merged**
