### PR TITLE
New version: Chocolatey.Chocolatey version 2.3.0.0

### PR DESCRIPTION
**Pull request by gep13**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/156624)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @gep13,

I didn't see any files added to the filesystem by this installer. Does it need different installer switches?

**Comment by gep13** [comment]
@stephengillie we have identified an issue that is preventing the MSI installer from working correctly.  I will post back here once I have more information to share.  Thank you!

**Comment by gep13** [comment]
@stephengillie would you be in a position to test this out again?  Thanks!

**Comment by stephengillie** [comment]
Yes, the application installs and runs normally:
image

**Comment by stephengillie** [comment]
Hi @pauby,

Do you approve of these changes?

(Automated response - build 884.)

**Comment by pauby** [comment]
@stephengillie Thanks for asking for clarification.

I approve of the changes. Please add @gep13 to the approved uploaders list too.

**Comment by stephengillie** [comment]
https://github.com/stephengillie/winget-pkgs/commit/35dadf6f0236765d32b87382720bf28e60d203f2

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
