### PR TITLE
New version: RevoUninstaller.RevoUninstaller version 2.3.9

### PR DESCRIPTION
**Pull request by ghost**
* Closes https://github.com/microsoft/winget-pkgs/pull/63630
* Closes https://github.com/microsoft/winget-pkgs/pull/63629

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/63651)

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]
@denelon bad logs in this scenario

**Comment by lechacon** [comment]
Looks like we ignore the executables placed by this app because they look like uninstallers due to the name. Maybe we should apply something like "if the app name says 'uninstaller' and all its executables look like uninstallers, consider them"? @denelon

**Comment by denelon** [comment]
> Looks like we ignore the executables placed by this app because they look like uninstallers due to the name. Maybe we should apply something like "if the app name says 'uninstaller' and all its executables look like uninstallers, consider them"? @denelon Demitrius Nelon FTE

What do we think the unintended consequences of this would be? How many other packages have this problem? Before we write code for a specific package I'd like to understand the cost/benefit.

**Comment by denelon** [comment]
It might make more sense for us to add a rule in the bot that looks at "known" packages to add a label and assign the PR to our "on-call" rotation. Microsoft.OneDrive falls into this category as @OfficialEsco pointed out the other day.

**Comment by OfficialEsco** [comment]
Quick look for Packages with Uninstall in the Name
* [RevoUninstaller.RevoUninstaller](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+RevoUninstaller.RevoUninstaller)
* [RevoUninstaller.RevoUninstallerPro](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+RevoUninstaller.RevoUninstallerPro)
* [Klocman.BulkCrapUninstaller](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+Klocman.BulkCrapUninstaller)
* [HiBitSoftware.HiBitUninstaller](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+HiBitSoftware.HiBitUninstaller)
* [CrystalIDEASoftware.UninstallTool](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+CrystalIDEASoftware.UninstallTool)
* [IObit.Uninstaller](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+IObit.Uninstaller)
* [Microsoft.dotnetUninstallTool](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+Microsoft.dotnetUninstallTool)

Not the most amount of Packages, should be ok as long as the On-Call looks into them

**Pull request merged**
