### PR TITLE
New version: RubyInstallerTeam.RubyWithDevKit.3.2 version 3.2.4-1

### PR DESCRIPTION
**Pull request by ItachiSan**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/163432)

### CODE REVIEW

**Comment by ItachiSan** [comment]
Important notes:
- I am not a member of RubyInstaller team, just a regular user of it.
- I noticed there is a slight difference in the installers list, the _AppsAndFeaturesEntries_ is missing.

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Comment by stephengillie** [comment]
Hi @ItachiSan,

This manifest removes Apps and Features entries that are present in previous PR versions. These entries should be added to this version, to maintain version matching, and prevent the 'upgrade always available' situation with this package.

(Automated response - build 886.)

**Comment by ItachiSan** [comment]
Hi, I can definitely work on that tomorrow. :smile:

**Comment by ItachiSan** [comment]
Hi, I will work on it right now.

**Comment by ItachiSan** [comment]
Here, please let me know if I need to modify some more stuff. 😄

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
