### PR TITLE
Remove: KDE.Kdenlive version 23.08.05

### LINKED ISSUE #141108: [Package Issue]: KDE.Kdenlive 23.08.4 -> 23.08.5
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

I have Kdenlive installed 23.08.5, winget shows it's 23.08.4 and offers me an update.

### Steps to reproduce

I have Kdenlive installed 23.08.4
Do winget upgrade KDE.Kdenlive
Installation finishes
winget still shows that I have 23.08.4 installed and there is a new version ready.
I check version in Kdenlive in the About window, it shows 23.08.5 version.

I uninstalled Kdenlive and reinstalled with winget, still having the same issue.

### Actual behavior

winget keeps offering me the 23.08.5 update

### Expected behavior

winget doesn't offer me an update, because I already have 23.08.5 installed.

### Environment

```raw
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.3155
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled

Other software:
WingetUI
```

### Screenshots and Logs

image
image

### PR DESCRIPTION
**Pull request by Exorcism0666**
﻿## Incorrect version

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

* Resolves #141108

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/142109)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
URL: https://download.kde.org/stable/kdenlive/23.08/windows/kdenlive-23.08.5.exe 
Status Code: 200

(Automated message - build 861)

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 861.)

**Comment by stephengillie** [comment]
URL: https://download.kde.org/stable/kdenlive/23.08/windows/kdenlive-23.08.5.exe 
Status Code: 200

(Automated message - build 861)

**Comment by stephengillie** [comment]
URL: https://download.kde.org/stable/kdenlive/23.08/windows/kdenlive-23.08.5.exe 
Status Code: 200

(Automated message - build 861)

**Comment by stephengillie** [comment]
URL: https://download.kde.org/stable/kdenlive/23.08/windows/kdenlive-23.08.5.exe 
Status Code: 200

(Automated message - build 867)

**Comment by stephengillie** [comment]
URL: https://download.kde.org/stable/kdenlive/23.08/windows/kdenlive-23.08.5.exe 
Status Code: 200

(Automated message - build 869)

**Comment by stephengillie** [comment]
URL: https://download.kde.org/stable/kdenlive/23.08/windows/kdenlive-23.08.5.exe 
Status Code: 200

(Automated message - build 869)

**Comment by stephengillie** [comment]
URL: https://download.kde.org/stable/kdenlive/23.08/windows/kdenlive-23.08.5.exe 
Status Code: 200

(Automated message - build 869)

**Review by stephengillie — APPROVED** [review]

**Comment by Exorcism0666** [comment]
* https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
