### PR TITLE
JanDeDobbeleer.OhMyPosh version 3.165.0

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/18427)

### CODE REVIEW

**Comment by JanDeDobbeleer** [comment]
Euh, nothing changed to the underlying logic tbh. So I have no idea what the issue is. I'll try to validate this manually myself.

**Comment by denelon** [comment]
@JanDeDobbeleer are there any dependencies? I wouldn't have expected to see this either.

**Comment by JanDeDobbeleer** [comment]
@ denelon I'll validate myself, maybe something is off that I didn't account for, but when it comes to this and the previous version nothing structurally changed (apart from one theme added on our end).

**Comment by denelon** [comment]
OK. If you don't find anything I'll see if I can get the logs from validation to see what happened in the pipeline. We also updated the "wingetcreate" client so it reports the version in the comment and it should add the JSON Schema comment for IDEs as well.

**Comment by JanDeDobbeleer** [comment]
@denelon let me update that client too first. Might have to do with that as well.

**Comment by OfficialEsco** [comment]
image

Nothing wrong unless you reuploaded

**Comment by JanDeDobbeleer** [comment]
Nope, fully automated.

**Comment by KaranKad** [comment]
Try closing and re-opening this pr.

**Pull request closed without merging**
