### PR TITLE
New version: DigitalScholar.Zotero version 6.0.35

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in Run [#3561](https://github.com/SpecterShell/Dumplings/actions/runs/8179077821).
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/142763)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by treysis** [comment]
Why is there a hash mismatch? Downloading the same file via browser is correct, but downloading using winget offers a seemingly slightly different file!

**Comment by stephengillie** [comment]
The hash mismatch might be from an updated package. But it's unusual that the two software tools would get different versions. They use different `user-agent` strings, and in the past some hosts have blocked the package manager but allowed browser downloads. 

Is it possible that this has happened here? That the package manager `user-agent` is being served a 404 or similar error page, and it's downloading this as the package instead of processing it as a missing file? Is there a size difference between the 2 downloads?

**Comment by treysis** [comment]
Yes, I suspect this is due to the user-agent, though the previous version (6.0.30) has the same hash for both download methods (winget and browser).

No, it's not a 404. Both files have roughly the same size (just a few kilobytes difference), both successfully install version 6.0.35.

**Comment by stephengillie** [comment]
That's indeed unexpected. This might be a malicious change, such as a virus being injected into the installer. But without evidence, it's probably due to a more mundane situation.

**Comment by treysis** [comment]
While both have a valid signature, they're each using their own. Left ist the browser version, right is the winget version:
image

**Comment by treysis** [comment]
Maybe some caching issue with their CDN (cloudfront)?

**Pull request merged**
