### PR TITLE
Nushell.Nushell version 0.72.0

### PR DESCRIPTION
**Pull request by fdncred**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/90032)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @fdncred,

Can you remove .github/actions/spelling/expect.txt from this PR? It's the unexpected file that's blocking validation.

**Comment by fdncred** [comment]
@stephengillie sure, just did. The only reason it was added was because this pipeline automated robot asked me to add it in the first place.

**Comment by mdanish-kh** [comment]
@fdncred Deleting it still counts as an "Unexpected change" in this PR. The correct course of action is to remove the modifications that were made to this file and restore it to its original state. Please restore https://github.com/microsoft/winget-pkgs/blob/master/.github/actions/spelling/expect.txt this file as is to your branch.

**Comment by fdncred** [comment]
@mdanish-kh, your bot said add the expect.txt file. i added it. then @stephengillie says delete it. i delete it. now you're saying add it again as if it originally existed, which it never did. i'm not sure what we need to do now.

**Comment by mdanish-kh** [comment]
> @mdanish-kh, your bot said add the expect.txt file. i added it. then @stephengillie says delete it. i delete it. now you're saying add it again as if it originally existed, which it never did. i'm not sure what we need to do now.

I apologize for all the inconvenience, the point to note is that you should not have additional files modified other than the ones required for the manifest. In this case; the modified files should only be 3, any modifications to other files would result in either `PullRequest-Error` or `Unexpected-File` label.

**Comment by fdncred** [comment]
> I apologize for all the inconvenience, the point to note is that you should not have additional files modified other than the ones required for the manifest. In this case; the modified files should only be 3, any modifications to other files would result in either PullRequest-Error or Unexpected-File label.

Apology accepted. Can we land this now?

**Comment by mdanish-kh** [comment]
It's still showing as modified as you missed a line-ending
image

**Comment by fdncred** [comment]
@mdanish-kh I downloaded the file from the link provided and put it in place without modifying it or even looking at it. not sure what else i can do now.

**Comment by Trenly** [comment]
> @mdanish-kh I downloaded the file from the link provided and put it in place without modifying it or even looking at it. not sure what else i can do now.

I've opened a separate PR just to make things easier.

I think what caused the confusion here is that the message you received saying to update the file (the one you posted in [this comment](https://github.com/microsoft/winget-pkgs/pull/90032#issuecomment-1331299663)) didn't actually come from this repository. It came from your own fork of the repository running the spell check run when you pushed your branch. The easiest thing to do is to disable the spell checking on your own fork, as shown in the [discussion here](https://github.com/microsoft/winget-pkgs/discussions/87054).

**Comment by fdncred** [comment]
Thanks @Trenly. I've disabled the spellcheck in my winget-pkgs fork now. hopefully that won't come up again.

**Pull request closed without merging**
