### PR TITLE
Add Heidi SQL

### PR DESCRIPTION
**Pull request by floh96**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/950)

### CODE REVIEW

**Comment by floh96** [comment]
Error:
>  -----------------------------------------------------
> Installer Availability
> -----------------------------------------------------
> Status: Started
> 
> 5/24/2020 1:37:20 PM
> Status: Completed
> Result: Failed
> Error occurred during installer copy from https://www.heidisql.com/installers/HeidiSQL_11.0.0.5919_Setup.exe.
>  Range GET requests are not supported by the copy source.
> 
> 5/24/2020 1:37:20 PM

URL is correct can someone help?

**Comment by LukasNespor** [comment]
Unfortunately right now the build Pipeline does not support "Range GET requests" to download the package and validate it. See #91

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
