### PR TITLE
New version: Ndd version 2.7.0

### PR DESCRIPTION
**Pull request by hjkl950217**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/116955)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
It look like you were trying modified wingetbot waiver file, Can you do not make any change to the validation file?

**Comment by hjkl950217** [comment]
> It look like you were trying to modified wingetbot waiver file, Can you do not make any change to the validation file?

Yes,But I want to confirm: if not modified, the PackagePath property may not refer to the latest version. Is this allowed?

**Comment by BrandonWanHuanSheng** [comment]
When during publishing stage, wingetbot will automatically modified the waiver

**Comment by stephengillie** [comment]
Hi @hjkl950217,

The .validation waiver is modified in a separate process. This PR can't be merged until the .validation file change is removed.

**Comment by hjkl950217** [comment]
> Hi @hjkl950217,
> 
> The .validation waiver is modified in a separate process. This PR can't be merged until the .validation file change is removed.

ok~

**Comment by hjkl950217** [comment]
> When during publishing stage, wingetbot will automatically modified the waiver

ok~

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
