### PR TITLE
New version: Nvidia.CUDA version 12.1

### PR DESCRIPTION
**Pull request by kimwonj77**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/98333)

### CODE REVIEW

**Comment by kimwonj77** [comment]
Note: This package is 3.1 GB. I think there's download error.

**Comment by stephengillie** [comment]
This application is expecting arguments:
```
Usage  : nvdisasm [options] <image file>

Options
=======

--base-address <value>                         (-base)
        Specify the logical base address of the image to disassemble. This option
        is only valid when disassembling a raw instruction binary (see option '--binary'),
        and is ignored when disassembling an Elf file.
        Default value:  0x0.

--binary <SMxy>                                (-b)
...
```

**Review by stephengillie — APPROVED** [review]

**Comment by nesterenkovy** [comment]
Are there plans to upgrade to the latest current version?
https://developer.download.nvidia.com/compute/cuda/12.3.0/local_installers/cuda_12.3.0_545.84_windows.exe

**Comment by kimwonj77** [comment]
> Are there plans to upgrade to the latest current version? https://developer.download.nvidia.com/compute/cuda/12.3.0/local_installers/cuda_12.3.0_545.84_windows.exe

I just submitted PR for 12.2.2 #124410 and 12.3 #124409. It will be merged sometime in this week if there's no problem.
But you should submit the issue for new version request for next time.

**Pull request merged**
