### PR TITLE
Add Camtasia version 21.0.5.31722

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/20128)

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@ItzLevvie please check this PR also 🙏

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
Please don't remove the `# yaml-language-server:` line from the manifests, instead add them when you update the package if its missing

**Comment by vedantmgoyal2009** [comment]
@OfficialEsco okay

**Comment by denelon** [comment]
@vedantmgoyal2009 those lines help when you're working in an IDE with support for JSON schema validation. For example, there is a Visual Studio Code plugin to enable intellisense and tooltips for YAML files.

**Pull request merged**
