### PR TITLE
Add jetBrains Toolbox App

### PR DESCRIPTION
**Pull request by vasilvestre**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/894)

### CODE REVIEW

**Comment by jamierocks** [comment]
Another duplicate of https://github.com/microsoft/winget-pkgs/pull/318.

**Comment by vasilvestre** [comment]
https://github.com/microsoft/winget-pkgs/pull/894#issuecomment-633221482 except I succeeded for silent

**Comment by jamierocks** [comment]
This pr has the same switch as that pr, so I'm not entirely certain that the concerns in that pr have been addressed?

**Comment by vasilvestre** [comment]
Seems like yes, hope the issue will be addressed

**Pull request closed without merging**
