### PR TITLE
New version: KiCad.KiCad version 7.0.9

### PR DESCRIPTION
**Pull request by fancybody**
Changed the download link from `https://downloads.kicad.org/` (in the previous versions) to github releases [mirror](https://github.com/KiCad/kicad-source-mirror/releases/)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/126054)

### CODE REVIEW

**Comment by marekr** [comment]
FYI, 7.0.9 has a modified installer to support admin or current user installs

It must now be run with /allusers flag on command line to match the earlier 7.0.x  behavior. Or else users upgrading from pre 7.0.9 winget will get duplicated installs

**Comment by marekr** [comment]
The scope cannot be determined automatically it must be done via cli args, it aborts otherwise

This is normally a GUI prompt.

**Comment by fancybody** [comment]
@russellbanks can you please restart the pipeline? it seems to have stopped.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
