### PR TITLE
New package: GyulyVGC.Sniffnet version 1.2.2

### PR DESCRIPTION
**Pull request by MokaSoda**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/134980)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978334972

(Automated response - build 586.)

**Comment by stephengillie** [comment]
Hi @MokaSoda,

This package appears to have a dependency on a packet capture library:
image

**Review by MokaSoda — COMMENTED** [review]
Fix dependency according to https://github.com/microsoft/winget-pkgs/pull/134980#issuecomment-1896628863

Thanks for diagnosing the issue!

**Comment by stephengillie** [comment]
Glad to help!

**Pull request closed without merging**
