### PR TITLE
Add msodbcsql version 17.7.2.1

### PR DESCRIPTION
**Pull request by v-ancha**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/11450)

### CODE REVIEW

**Comment by v-ancha** [comment]
@David-Engel tagged for awareness of PR

**Comment by KevinLaMS** [comment]
I am getting an error and the installer is not succeeding.  

image

**Comment by v-ancha** [comment]
I have tested and found that this error is most likely related to MSI installer. If the application is already installed, this error code will happen. When I uninstalled the app and reinstalled with winget no error messages were received and a successful download was had. Other potential causes for this error due to MSI installer can be found at: https://docs.microsoft.com/en-us/troubleshoot/windows-server/application-management/msi-installation-error-1603#cause

**Comment by KevinLaMS** [comment]
On Clean VM get the following Error Installation failed with exit code -1978335226
Will try again and see if updated pipeline changes.

**Comment by v-ancha** [comment]
@KevinLaMS Could you provide more information on the error? Looking into previous threads that had the same error, it seems to do with not having elevated permissions. However, I haven't been able to reproduce the error using administrator or non-admin permissions.

**Comment by KevinLaMS** [comment]
I get 1603 regardless of admin or not
image

**Comment by v-ancha** [comment]
After testing, this error is probably due to not having the C++ Redist required for the ODBC Driver. Since WinGet does not have package dependency support yet, please install VC++14 and retry.

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
@v-ancha - Dependencies are now supported; Can you please try submitting a new PR for this package?

**Pull request closed without merging**
