### PR TITLE
New version: Streetwriters.Notesnook version 2.2.1

### PR DESCRIPTION
**Pull request by mdanish-kh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/81097)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by thecodrr** [comment]
@mdanish-kh Not sure why it's `Streetwriters.Notesnook` instead of just `Notesnook`.

**Comment by thecodrr** [comment]
Oh wait. I think this is MS policy.

**Comment by mdanish-kh** [comment]
> @mdanish-kh Not sure why it's `Streetwriters.Notesnook` instead of just `Notesnook`.

The naming convention for a `package` in winget is `Publisher.PackageName`. This is just an identifer winget uses to represent a unique package. https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#what-is-a-package. Users will be able to install a package through its unique identifer i.e., `winget install Streetwriters.Notesnook`. Furthermore, a friendly name (Moniker) i.e., `notesnook` is also provided in the manifest so users can install the package through `winget install notesnook`.
 

The `PackageName` in the manifest is still `Notesnook`. This is the name that is displayed in the Control Panel / Apps & Features.

**Comment by mdanish-kh** [comment]
> 
> The problem with this would be the install command:
> 
> ```
> winget install -e --id Streetwriters.Notesnook
> ```
> 
> instead of just
> 
> ```
> winget install -e --id Notesnook
> ```
@thecodrr 
As `Notesnook` is not the `id` of the package but rather its `moniker`, the correct command is actually `winget install --moniker Notesnook` or you could just do `winget install Notesnook` because notesnook as a moniker is unique to this package only so winget automatically installs it for you.

**Comment by thecodrr** [comment]
Awesome.

**Pull request merged**
