### PR TITLE
New version: hickford.git-credential-oauth version 0.11.1

### PR DESCRIPTION
**Pull request by schembriaiden**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/146075)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\hickford.git-credential-oauth__DefaultSource\git-credential-oauth.exe returned exit code: 2
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\git-credential-oauth.exe returned exit code: 2

(Automated response - build 872.)

**Comment by vikingnope** [comment]
Is this good or bad?

**Comment by stephengillie** [comment]
> Is this good or bad?

It is what it is. The pipelines received a non-zero exit code from the application, and applied a label based off this response. The application might have been designed to return a non-zero exit code in some circumstances. I'm hopeful to reimplement my auto-waiver system soon, to again fill this gap and obviate the questions it creates.

**Review by stephengillie — APPROVED** [review]

**Comment by hickford** [comment]
@vikingnope Do you know how to add the arm64 build?

**Pull request merged**
