### PR TITLE
Submitting Adobe Reader version 1901020064.yaml

### PR DESCRIPTION
**Pull request by CaptainBrooksie**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/645)

### CODE REVIEW

**Review by NathanBnm — CHANGES_REQUESTED** [review]
Acrobat Reader should be named "Acrobat Reader DC" because "Acrobat Reader" stands for the older version

**Comment by NathanBnm** [comment]
I created #503 what's the difference between these two versions ?

**Comment by superusercode** [comment]
```
Id: Adobe.AcrobatReaderDC
Version: 2020.009.0063
Name: Adobe Acrobat Reader DC
Publisher: Adobe
License: Copyright (c) Adobe
LicenseUrl: https://www.adobe.com/content/dam/cc/en/legal/licenses-terms/pdf/Reader-EULA-en_US-20181207.pdf
AppMoniker: adobereader
Description: Only with Adobe Acrobat Reader you can view, sign, collect and track feedback, and share PDFs for free. 
Homepage: https://acrobat.adobe.com/us/en/acrobat/pdf-reader.html
Installers:
  - Arch: x86
    Url: http://ardownload.adobe.com/pub/adobe/reader/win/AcrobatDC/2000920063/AcroRdrDC2000920063_en_US.exe
    Sha256: B49F6B49F28712735098836BB7D9BF2FF12568ED166936B7B90C87BC847B2C68
    InstallerType: inno
```

there is an inno version of adobe reader dc that is also not a internet installer stub. This is the full, free version of adobe acrobat dc.

**Comment by superusercode** [comment]
additionally, the version you are submitting appears to be older (or the version of the installer rather than of reader)

**Pull request closed without merging**
