### PR TITLE
New package: Microsoft.DotNet.UninstallTool v4.96.657

### PR DESCRIPTION
**Pull request by SonnyRR**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?
---

ℹNB: This package now resides under the `Microsoft/DotNet/` package directory. I'll create ~~& reference~~ a `PR` (see #116753) which removes the old `1.5.x` version manifest (`Microsoft.dotnetUninstallTool`), since that version does not support `.NET 7` and uses an odd identifier. Please let me know in the comments if that's not okay, I can maybe include a manifest for it in a separate PR in order to confirm with this unified identifier convention for `DotNet` related tools. However, I highly doubt many people will need the old version, since it supports SDKs & runtimes up until `.NET 6.0` (inclusive).
 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/116752&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
The package did install: 
image

But I'm unsure of how to interact with it.

**Comment by stephengillie** [comment]
Hi @SonnyRR,

How do we launch this application?

**Comment by SonnyRR** [comment]
Hi @stephengillie, it's a CLI tool. You can try these statements:
```powershell
dotnet-core-uninstall list
```
```powershell
dotnet-core-uninstall --version
```

Reference: https://learn.microsoft.com/en-us/dotnet/core/additional-tools/uninstall-tool?tabs=windows

**Comment by SonnyRR** [comment]
Any updates on the review of this request ? The other PR for removing the old version was merged, so currently there isn't a way to install this tool.

**Comment by stephengillie** [comment]
Hi @mthalman,

Do you approve this PR?

**Review by mthalman — APPROVED** [review]

**Review by Trenly — APPROVED** [review]

**Pull request merged**
