### PR TITLE
New package: robinovitch61.wander 1.0.1

### PR DESCRIPTION
**Pull request by robinovitch61**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/134018)

### CODE REVIEW

**Comment by robinovitch61** [comment]
I think this is likely a false positive error similar to https://github.com/microsoft/winget-pkgs/pull/132238. Does a moderator mind taking a look/retrying?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-14 19:39:29.715 [FAIL] Installer failed security check. Url: https://github.com/robinovitch61/wander/releases/download/v1.0.1/wander_1.0.1_Windows_x86_64.zip Result: 0x80004005

(Automated response - build 570.)

**Comment by stephengillie** [comment]
Hi @robinovitch61,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 570.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
