### PR TITLE
Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\5.7.2

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114140&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
> 12:07:17 PM: 2023-08-08 12:07:16.749 [CLI ] ShellExecute installer failed: 1603
12:07:17 PM: CustomAction _67AC4AD8_6F00_4853_A52D_C3B81180AEFA returned actual error code 1602 (note this may not be 100% accurate if translation happened inside sandbox)
12:07:17 PM: MSI (s) (90:A4) [12:07:16:185]: Product: OneMoreAddIn -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action _67AC4AD8_6F00_4853_A52D_C3B81180AEFA, location: C:\Program Files (x86)\River\OneMoreAddIn\OneMoreSetupActions.exe, command: --install --x86
12:07:17 PM: Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action _67AC4AD8_6F00_4853_A52D_C3B81180AEFA, location: C:\Program Files (x86)\River\OneMoreAddIn\OneMoreSetupActions.exe, command: --install --x86
12:07:17 PM: Property(S): ErrorDialog = ErrorDialog
12:07:17 PM: MSI (s) (90:A4) [12:07:16:545]: Product: OneMoreAddIn -- Installation failed.
12:07:17 PM: MSI (s) (90:A4) [12:07:16:545]: Windows Installer installed the product. Product Name: OneMoreAddIn. Product Version: 5.7.2. Product Language: 1033. Manufacturer: River. Installation success or error status: 1603.

**Pull request merged**
