### PR TITLE
EdrawSoft.MindMaster.CN version 9.0.10.147

### PR DESCRIPTION
**Pull request by Dragon1573**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/40558)

### CODE REVIEW

**Comment by Dragon1573** [comment]
Related https://github.com/microsoft/winget-pkgs/pull/40559#issue-1099954005 , this **Simplified Chinese** version installer does NOT support "silent-installation" either ...

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
We'll have to wait until interactive-only installers are supported in WinGet and in WinGet's pipelines.

For now, you can set this PR to DRAFT; until this feature has been implemented.

**Comment by Dragon1573** [comment]
@ItzLevvie Oh, I see ...

I'll change this PR (as well as #40559) into "Draft Mode". Thank you!

**Review by ItzLevvie — APPROVED** [review]
This pull request (PR) has been automatically approved via GitHub CLI using `40558..40558 | % { gh pr review --approve $_ }` in Windows PowerShell.

**Comment by Dragon1573** [comment]
It seems that there's someone else fix this issue. This pull request can be closed without being merged.

The latest manifests of this package has been merged into `master` via #85958 and it provides `en-US` and `zh-CN` at the same time.

**Pull request closed without merging**
