### PR TITLE
Added DBeaver

### PR DESCRIPTION
**Pull request by LightDestory**
Free universal database tool!

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/524)

### CODE REVIEW

**Comment by LightDestory** [comment]
How can I implement the silent mode correctly?
Right now the manifest just download and open up the install and the user must manually follow the setup wizard.
Which is the correct type of installation: all user or current user? (winget runs with administrator privileges? If not how can we use the "all user" install type?)

**Comment by KevinLaMS** [comment]
Looking at help, it appears you could pass /currrentuser /S for silent current user.
Eventually the package manager will add support for the user to choose.

**Comment by LightDestory** [comment]
@KevinLaMS I have updated the manifest, now it should do a proper silent installaiton.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
