### PR TITLE
Update AIMP.AIMP.installer.yaml

### PR DESCRIPTION
**Pull request by iDolmatov**
Added "/UPDATE" for upgrade.
https://github.com/microsoft/winget-cli/issues/1057#issuecomment-852177920

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15501)

### CODE REVIEW

**Comment by ItzLevvie** [comment]
Close the PR and reopen it, to automatically start up the pipelines.

**Comment by iDolmatov** [comment]
> Exception Message: Cannot get DNS address for host 'winget.azurefd.net' (No such host is known). (type TeamFoundationServerException)

**Comment by iDolmatov** [comment]
Try fix error with Installation Validation.

**Pull request merged**
