### PR TITLE
New version: YaSuenag.SimpleCom version 1.2.4

### PR DESCRIPTION
**Pull request by YaSuenag**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/167155)

### CODE REVIEW

**Comment by YaSuenag** [comment]
I can install the binary safely, so can you share details of the error?

I saw similar issue in #137723 . Is it false-positive in this case?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-08-11 00:52:23.253 [FAIL] Installer failed security check. Url: https://github.com/YaSuenag/SimpleCom/releases/download/v1.2.4/SimpleComInstaller-1.2.4.msi Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 887.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-08-14 09:14:16.417 [FAIL] Installer failed security check. Url: https://github.com/YaSuenag/SimpleCom/releases/download/v1.2.4/SimpleComInstaller-1.2.4.msi Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 887.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
