### PR TITLE
New package: Isao.Pixia version 6.61p

### LINKED ISSUE #153930: [Package Request]: Pixia
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.ne.jp/asahi/mighty/knight/download.html
Publisher: Isao Maruoka
Package Name: Pixia
Description: A painting tool made exclusively for complete color graphics.
Package Version: 6.61p
Installer URL: https://www.ne.jp/asahi/mighty/knight/apps/pix64_661pe.exe

### PR DESCRIPTION
**Pull request by schembriaiden**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.2.1 :rocket:

Resolves: https://github.com/microsoft/winget-pkgs/issues/153930
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/154002)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-05-17 06:49:37.940 [CLI ] ShellExecute installer failed: 4294967293
> 2024-05-17 06:49:21.717 [CLI ] ShellExecute installer failed: 4294967293

Automated error analysis suggests -1978335226 may mean Install successful but system restart may be required.

(Automated response - build 881.)

**Comment by vikingnope** [comment]
@stephengillie, any ideas on what Ii can do?

**Comment by stephengillie** [comment]
Manual Validation ended with the same code: 
> ShellExecute installer failed: 4294967293

Running the full installer had no errors. 

Query installer:
image

Tried numerous combinations of these switches, but none resulted in an install.

**Comment by vikingnope** [comment]
We might need to close this then because even tried all switches possible.

**Pull request closed without merging**
