### PR TITLE
New version: Mozilla.Firefox version 121.0

### PR DESCRIPTION
**Pull request by lunacd**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131351)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
Hmmm. It seem like the pull request does not assign ICM User during https://github.com/microsoft/winget-pkgs/labels/Needs-Attention labels

**Comment by mdanish-kh** [comment]
Close with reason: Package got merged in #131395;

**Pull request closed without merging**
