### PR TITLE
Update AnsgarBecker.HeidiSQL

### PR DESCRIPTION
**Pull request by JamieMagee**
Use canonical URL

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1914)

### CODE REVIEW

**Comment by JamieMagee** [comment]
#91 Again

**Comment by stedaniels** [comment]
> 6/24/2020 9:06:03 AM
> Status: Completed
> Result: Failed
> Error occurred during installer copy from https://www.heidisql.com/installers/HeidiSQL_11.0.0.5919_Setup.exe.
>  Range GET requests are not supported by the copy source.

https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=90013&view=logs&j=c8020aa5-4aab-5881-691f-21986e02afd0&t=bade86d6-d2be-5ddd-c1b9-7d8db9c4a60d&l=41

Which is pretty annoying, since the winget cli *does* support range requests.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
