### PR TITLE
Remove version: Fort.Firewall version 3.11.5

### PR DESCRIPTION
**Pull request by ghost**
Replaced by https://github.com/microsoft/winget-pkgs/pull/138957
---
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/139421)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://github.com/tnodir/fort/releases/download/v3.11.5/FortFirewall-3.11.5-windows10-x86_64.exe 
Status Code: 200

(Automated message - build 762)

**Comment by stephengillie** [comment]
This package is still available - why is it being removed? Is a goal for this package to only have the latest version available?

**Comment by stephengillie** [comment]
URL: https://github.com/tnodir/fort/releases/download/v3.11.5/FortFirewall-3.11.5-windows10-x86_64.exe 
Status Code: 200

(Automated message - build 762)

**Comment by stephengillie** [comment]
URL: https://github.com/tnodir/fort/releases/download/v3.11.5/FortFirewall-3.11.5-windows10-x86_64.exe 
Status Code: 200

(Automated message - build 762)

**Comment by stephengillie** [comment]
[Policy] Needs-Author-Feedback

**Comment by stephengillie** [comment]
URL: https://github.com/tnodir/fort/releases/download/v3.11.5/FortFirewall-3.11.5-windows10-x86_64.exe 
Status Code: 200

(Automated message - build 762)

**Comment by Emi-Emi-Emi** [comment]
@stephengillie yes. I only want a single version. 
I would only update the URLs if I could. But I don't think I can?

There will be a moment when I might not be able to keep doing this and I will have to remove package. I don't want to remove all 100 versions. Because I can't manually update versions.

The thing is, this program is updated randomly. Sometimes new updates take a while but usually pretty often.
For example the change from 3.11.5 to 3.11.6 happened in 2 hours. And I contained and important bug fix for the speed limiter to work. So all older versions are just useless.

I even removed x86 builds to simplify making this. But I still want some people even one to have it easy to get this great Firewall. I am not developer but my feedback and ideas have helped developer to make it better, in very important parts of it. So I wanted to help him with this but updates sometimes happen! Many versions anweek and even day.

Is this wrong ? Should I just stop trying to achieve the single latest version? which is the only one people should install anyway, but winget will only install latest by default anyway.

**Comment by stephengillie** [comment]
URL: https://github.com/tnodir/fort/releases/download/v3.11.5/FortFirewall-3.11.5-windows10-x86_64.exe 
Status Code: 200

(Automated message - build 762)

**Comment by stephengillie** [comment]
@Emi-Emi-Emi,

Thank you for the thorough explanation. I'll make a note of this package, to skip this check, and hopefully automate this to prevent asking in the future.

**Review by stephengillie — APPROVED** [review]

**Comment by Emi-Emi-Emi** [comment]
@stephengillie

Thank you! That sounds like it will make all this process better.

Have a good day!

**Pull request merged**
