### PR TITLE
New Drumstick.dmidiplayer version 1.7.0

### PR DESCRIPTION
**Pull request by pedrolcl**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/69067)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by pedrolcl** [comment]
I don't understand why this PR is blocked. The download URL is SourceForge, exactly like the latest version 1.6.0 #60988 which was blocked the same way, but was assigned to @JohnMcPMS and @yao-msft but in this case nobody has been assigned. Please, can somebody unblock this? Thanks!

**Comment by pedrolcl** [comment]
[Not even a single false positive on VirusTotal](https://www.virustotal.com/gui/file/2ad84189f9487c28d80a860dadb3491f0326ec0133259558c631ce6fda69cb24), but the installer is still blocked.

Seriously: please can somebody tell me what I need to do so this new version is published?

**Comment by ItzLevvie** [comment]
> Seriously: please can somebody tell me what I need to do so this new version is published?

It requires an engineer to make a waiver for the https://github.com/microsoft/winget-pkgs/labels/Validation-Unapproved-URL label.

**Comment by msftrubengu** [comment]
I'm going to let this through and manually create a waiver to unblock it then I'll look into why wingetbot didn't respond.

If I have to use my psychic debugging powers, I would say that we either drop the message (but two times feels weird) or there's a bug related to this Validation-Unapproved-URL

Sorry about the delay.

**Comment by msftrubengu** [comment]
Ok my physic powers are completely off.

This what happened:
1. The validation ran on the 17 and marked the PR as need for manual review
2. msftbot was in a bad day and decided not to run its tasks that will assign the PR to whoever is on rotation.
3. We use internal data to process the waiver request.
4. We also have internally some code that periodically cleans up resources because we try to be good citizens.
5. Of course that ran 16 hours ago and deleted the data we need to process the request.  

Now the good news is that this isn't the first time that happens, so I already have a bug for it. The bad is that I didn't prioritize it enough because it had only happened once. I'll make sure it goes on our next release.

Sorry about that.

**Comment by pedrolcl** [comment]
@msftrubengu : thank you very much! 

> my psychic debugging powers

You must share the same ~~office~~ shrine with Raymond Chen!

**Pull request merged**
