### PR TITLE
New version: Alibaba.AlibabaCloudCLI version 3.0.211

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#6431](https://github.com/SpecterShell/Dumplings/actions/runs/9832875917).

<details>

<summary>Log</summary>

````
Updated: 3.0.210 → 3.0.211
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161878)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-07-09 01:33:36.436 [FAIL] Installer failed security check. Url: https://github.com/aliyun/aliyun-cli/releases/download/v3.0.211/aliyun-cli-windows-3.0.211-amd64.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 886.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-07-09 17:51:29.843 [FAIL] Installer failed security check. Url: https://github.com/aliyun/aliyun-cli/releases/download/v3.0.211/aliyun-cli-windows-3.0.211-amd64.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 886.)

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
