### PR TITLE
Dup - Oracle.Java8 version 8.0.3010.9

### PR DESCRIPTION
**Pull request by Masamune3210**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/27332)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Manifest already exists https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/Oracle/JavaRuntimeEnvironment/8.0.3010.9

**Comment by Masamune3210** [comment]
Ok, ill close. For some reason a lot of the ones I have made that ended up being dups are unmatched to their manifest when I run winget list, or am I misunderstanding the point of the id column in the list's purpose, as most of them show up as uuid's instead of the name of a manifest

**Comment by ItzLevvie** [comment]
> For some reason a lot of the ones I have made that ended up being dups are unmatched to their manifest when I run winget list, or am I misunderstanding the point of the id column in the list's purpose, as most of them show up as uuid's instead of the name of a manifest

It's either one of these:
1) Package doesn't exist
2) Package does exist but the package has Publisher/PackageName/PackageVersion 
3) Package doesn't have the correct ProductCode.

EA app (prev. EA Desktop) has a fix https://github.com/microsoft/winget-pkgs/pull/27344. For Oracle, I'll take a look.

**Comment by Masamune3210** [comment]
looks like you might be right, I guess at some point they changed their registered information because slightly older version doesn't register as even needing upgraded or anything
image

**Comment by Masamune3210** [comment]
How would I go about fixing the manifests if they don't connect, just pull latest from master, change and submit a push request?

**Pull request closed without merging**
