### PR TITLE
Remove manifest: HDSentinel.HDSentinel.Pro version 6.20

### PR DESCRIPTION
**Pull request by KarbitsCode**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/166939)

### CODE REVIEW

**Comment by KarbitsCode** [comment]
Reason for removal: https://github.com/microsoft/winget-pkgs/pull/166628#issuecomment-2276186857

**Comment by stephengillie** [comment]
URL: https://www.harddisksentinel.com/hdsentinel_pro_setup.zip 
OK

(Automated message - build 912)

**Comment by stephengillie** [comment]
Close with reason: Package still available;

**Comment by KarbitsCode** [comment]
Hi @stephengillie,

I want to remove this manifest because it is a duplicate of JanosMathe.HardDiskSentinelPro, could you approve this PR instead?

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
