### PR TITLE
New Version: sourcegit-scm.SourceGit version 8.23

### LINKED ISSUE #165053: [Update Request]: SourceGit 8.23
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

sourcegit-scm.SourceGit

### Package Version

8.23

### Please describe the changes you would like to see

There is a new version (8.23) available.
Download URLs are:

X64: https://github.com/sourcegit-scm/sourcegit/releases/download/v8.23/sourcegit_8.23.win-x64.zip
ARM64: https://github.com/sourcegit-scm/sourcegit/releases/download/v8.23/sourcegit_8.23.win-arm64.zip

### PR DESCRIPTION
**Pull request by love-linger**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?
  Resolve #165053

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/165055)

### CODE REVIEW

**Comment by love-linger** [comment]
Can someone help? I can't get the reason for the error from the log.

```
7/29/2024 3:12:45 AM

****************************************************************************************
Installation Verification
****************************************************************************************
Status: Started
============================================================================== 
Task         : Installation Validation
Description  : Invoke an Azure Function
Version      : 1.220.0
Author       : Microsoft Corporation
Help URL     : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/azure-function
============================================================================== 
2024-07-29T03:12:46.8224400Z POST ***?code=***&
Request body: {
  "operationId": "WinGetSvc-Validation-401-165055-20240729-1",
  "BuildId": "599170",
  "PlanUrl": "https://dev.azure.com/ms/",
  "HubName": "build",
  "ProjectId": "ed6a5dfa-6e7f-413b-842c-8305dd9e89e6",
  "PlanId": "29a9ed59-c568-4f62-9261-aa515192261e",
  "JobId": "68997d86-8ece-5ae8-3ac5-ccdbfa458731",
  "TimelineId": "29a9ed59-c568-4f62-9261-aa515192261e",
  "TaskInstanceId": "b79910ce-dca5-5e27-ad7f-bd285eecb5a2",
  "AuthToken": ***
}
				Response Code: OK
				Response: 

7/29/2024 3:14:06 AM

****************************************************************************************
Installation Verification
****************************************************************************************

-----------------------------------------------------
Result: Failed
-----------------------------------------------------
Status: Completed
```

I've tested my manifest locally with `winget install --manifest .\manifests\s\sourcegit-scm\SourceGit\8.23`

image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
