### PR TITLE
MisiteBao.Yakia version 0.1.0

### PR DESCRIPTION
**Pull request by misitebao**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/98400)

### CODE REVIEW

**Comment by misitebao** [comment]
> @misitebao please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by misitebao** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
This program only seems to print a string: 
```
Tool is under development, please wait...
```
Is this how the program is supposed to act?

**Comment by misitebao** [comment]
@stephengillie 
Yakia is a CLI developed in Go. Because wingetcreate cannot correctly parse binary files built in Go language, I developed this console program in C# for testing. It is a placeholder for the time being and an announcement at the same time. Hope the PR can be approved.

By the way, wingetcreate cannot correctly parse the binary files built by Go and Rust(https://github.com/microsoft/winget-create/issues/302). I checked the bills in this regard, but I didn't find a better way. Can the official solve this problem?

**Comment by stephengillie** [comment]
> By the way, wingetcreate cannot correctly parse the binary files built by Go and Rust([microsoft/winget-create#302](https://github.com/microsoft/winget-create/issues/302)). I checked the bills in this regard, but I didn't find a better way. Can the official solve this problem?

Please consider using our other manifest building tools, such as [YamlCreate](https://github.com/microsoft/winget-pkgs/blob/master/doc/tools/YamlCreate.md) and [Komac](https://github.com/russellbanks/Komac) (which can be installed with: `WinGet install RussellBanks.Komac`.

**Comment by misitebao** [comment]
@stephengillie 
Thanks for your patient reply, I request to merge this PR.
Regarding the new package maker you mentioned, I will test it locally, thank you very much.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
