### PR TITLE
New package: CubeSoft.CubeICE version 2.0.0

### PR DESCRIPTION
**Pull request by aurigajp**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/78718)

### CODE REVIEW

**Comment by aurigajp** [comment]
What should I do?
A similar product (CubeSoft.CubePDF) made by Cubesoft has been registered.

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
For the https://github.com/microsoft/winget-pkgs/labels/Validation-Domain label, wait for an engineer to take a look.

**Comment by aurigajp** [comment]
Ok. Whenever you've got time.

**Pull request merged**
