### PR TITLE
SumatraPDF.SumatraPDF version 3.3.3

### PR DESCRIPTION
**Pull request by OyePradumya**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/29133)

### CODE REVIEW

**Comment by OyePradumya** [comment]
This is 32 bit version of the Sumatra PDF already submitted here.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Overwrites existing manifest.

**Comment by OyePradumya** [comment]
@ItzLevvie it doesn't overwrite any manifest. 
There is a SumatraPDF manifest which is for 64bit version of this software. I am providing manifest for 32 bit software.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/29133#pullrequestreview-768760496

**Comment by OyePradumya** [comment]
@ItzLevvie brother please see the changes that you are suggesting will remove 64bit already added
 This one #29133 is for 32 bit version. There should be both 64 bit and 32 bit variants for this software.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
>@ItzLevvie brother please see the changes that you are suggesting will remove 64bit already added
>This one #29133 is for 32 bit version. There should be both 64 bit and 32 bit variants for this software.

The changes that are in the green color are your changes, so I'm not sure what you're changing here other than removing the x64 installer with some of the metadata in the package that's being removed in this PR.

The latest package that's currently in the repository already has both x86 & x64 installers: https://github.com/microsoft/winget-pkgs/blob/master/manifests/s/SumatraPDF/SumatraPDF/3.3.3/SumatraPDF.SumatraPDF.installer.yaml; one of the older packages don't through, so if you want to update those then go ahead :). I would suggest to use the metadata from the latest manifest because `PackageName` must not have `32bit` in it.

You can verify this on an x86 VM by doing `winget show SumatraPDF.SumatraPDF`: you will get `https://kjkpubsf.sfo2.digitaloceanspaces.com/software/sumatrapdf/rel/SumatraPDF-3.3.3-install.exe` as Installer URL.

You can verify this on an x64 VM by doing `winget show SumatraPDF.SumatraPDF`: you will get `https://kjkpubsf.sfo2.digitaloceanspaces.com/software/sumatrapdf/rel/SumatraPDF-3.3.3-64-install.exe` as Installer URL.

**Pull request closed without merging**
