### PR TITLE
New version: SideQuestVR.SideQuest version 0.10.32 [FP-D]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | SideQuest | SideQuest 0.10.32    |
| Version     | 0.10.32     | 0.10.32 |
| Publisher   | Shane Harris   | Shane Harris      |
| ProductCode |           | 4924ec51-3e48-5cb7-b145-2119467094c7    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://bittu.eu.org/docs/wpa-intro) in workflow run [2811](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/2966590236>)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Comment by vedantmgoyal2009** [comment]
bump

**Pull request merged**
