### PR TITLE
New version: WHONET.WHONET version 24.6.17

### PR DESCRIPTION
**Pull request by AClark-WHONET**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/158154)

### CODE REVIEW

**Comment by AClark-WHONET** [comment]
Hi @stephengillie, I'm seeing some odd discordance with the error messages. It shows that "all checks have passed", but it also has the "Validation-Installation-Error" label AND the "Azure-Pipeline-Passed" and "Validation-Completed". When I look into the Azure logs, that particular job doesn't list a cause for the failure (I have tested both installers, no problems installing them manually). Any suggestions? Thanks.

**Comment by AClark-WHONET** [comment]
Thank you. Is it possible to re-run this pipeline to see if it completes successfully?

**Comment by stephengillie** [comment]
Happily. I was going to just approve, but no worreis.

**Comment by AClark-WHONET** [comment]
Thanks. Mostly just curiosity, but if it succeeds that would be useful info for your investigation.

**Comment by AClark-WHONET** [comment]
A small detail of my release process that might support your race condition/interference theory: Immediately following the PR request being generated by wingetcreate as part of my script, I go into GitHub and manually edit the locale.yml file because I am missing the ReleaseNotes and ReleaseNotesUrl values, which will cause validation to subsequently fail if I don't.

The system would then trigger the pipeline a second time (within a minute or so) possibly leading to the race issue.

Of course, I would prefer not to edit the .yml, but I can't find any docs which would let me specify the values for these using a command line flag or settings file. Any help there would be greatly appreciated, and would probably prevent the race issue for my case at least.

**Comment by stephengillie** [comment]
This is good to know, and should be recorded as an [Issue](https://github.com/microsoft/winget-pkgs/issues), possibly a `Feature-Request`.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
