### PR TITLE
Add quick-lint-js version 2.17.0.0

### PR DESCRIPTION
**Pull request by strager**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/123771)

### CODE REVIEW

**Comment by strager** [comment]
> The package manager bot determined there was an issue with installing the application correctly.

I can't tell what the error is from the logs on Azure DevOps. I see that the ["Installation Verification" job failed](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=508382&view=logs&jobId=871b4eed-22de-5cb6-c1c8-82f190de633f&j=871b4eed-22de-5cb6-c1c8-82f190de633f&t=58bdf892-4e45-5ba7-4782-31912f95e167), but I don't see any helpful error messages:
```

10/26/2023 1:29:47 AM

****************************************************************************************
Installation Verification
****************************************************************************************
Status: Started
============================================================================== 
Task         : Installation Validation
Description  : Invoke an Azure Function
Version      : 1.220.0
Author       : Microsoft Corporation
Help URL     : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/azure-function
============================================================================== 
2023-10-26T01:29:48.8154657Z POST ***?code=***&
Request body: {
  "operationId": "WinGetSvc-Validation-323-123771-20231026-1",
  "BuildId": "508382",
  "PlanUrl": "https://dev.azure.com/ms/",
  "HubName": "build",
  "ProjectId": "ed6a5dfa-6e7f-413b-842c-8305dd9e89e6",
  "PlanId": "3cb987db-07c1-48f0-8d3d-4a3983a2ede4",
  "JobId": "871b4eed-22de-5cb6-c1c8-82f190de633f",
  "TimelineId": "3cb987db-07c1-48f0-8d3d-4a3983a2ede4",
  "TaskInstanceId": "58bdf892-4e45-5ba7-4782-31912f95e167",
  "AuthToken": ***
}
				Response Code: OK
				Response: 

10/26/2023 1:32:47 AM

****************************************************************************************
Installation Verification
****************************************************************************************

-----------------------------------------------------
Result: Failed
-----------------------------------------------------
Status: Completed
```

**Comment by strager** [comment]
> Please check the application installs correctly. 

The package installed without error on my Windows 10 machine:
```
> pwd

Path
----
C:\Users\strager\Documents\Projects\winget-pkgs\manifests\q\quick-lint\quick-lint-js\2.17.0.0

> winget install --manifest .
Found quick-lint-js [quick-lint.quick-lint-js] Version 2.17.0.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://c.quick-lint-js.com/releases/2.17.0/windows/quick-lint-js.msix
  ██████████████████████████████   898 KB /  898 KB
Successfully verified installer hash
Starting package install...
  ██████████████████████████████  100%
Successfully installed

> quick-lint-js --version
quick-lint-js version 2.17.0
```

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2023-10-25 18:32:10.155 [CORE] Starting RequestAddPackageAsync operation #0: https://c.quick-lint-js.com/releases/2.17.0/windows/quick-lint-js.msix
2023-10-25 18:32:10.158 [CORE] Begin waiting for operation #0
2023-10-25 18:32:10.158 [CORE] Begin blocking for operation #0
2023-10-25 18:32:12.351 [CORE] Deployment operation #0: error 0x800B0101: Opening the package from location quick-lint-js.msix failed.
2023-10-25 18:32:12.351 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!00007FFBEC479A45: (caller: 00007FFBEC403515) Exception(1) tid(2204) 800B0101 A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file.

**Comment by stephengillie** [comment]
Automatic Validation ended with the same error.

**Comment by strager** [comment]
Thanks for sharing the logs. I'll look into it.

**Comment by strager** [comment]
> This might be a data center block to prevent automated downloads.

I see in the server logs (c.quick-lint-js.com) that two requests were made by the CI servers

> c.quick-lint-js.com 13.83.13.163 - - [27/Oct/2023:01:05:43 +0000] "HEAD /releases/2.17.0/windows/quick-lint-js.msix HTTP/2.0" 200 920316 "-" "winget-cli WindowsPackageManager/1.5.5-preview DesktopAppInstaller/none"
>
> c.quick-lint-js.com 13.83.13.163 - - [27/Oct/2023:01:05:43 +0000] "GET /releases/2.17.0/windows/quick-lint-js.msix HTTP/2.0" 206 133884 "-" "winget-cli WindowsPackageManager/1.5.5-preview DesktopAppInstaller/none"
>
> c.quick-lint-js.com 20.75.6.30 - - [27/Oct/2023:01:06:15 +0000] "HEAD /releases/2.17.0/windows/quick-lint-js.msix HTTP/1.1" 200 - "-" "winget/1.0"
>
> c.quick-lint-js.com 20.75.6.30 - - [27/Oct/2023:01:07:08 +0000] "GET /releases/2.17.0/windows/quick-lint-js.msix HTTP/1.1" 200 920316 "-" "winget-cli WindowsPackageManager/1.5.5-preview DesktopAppInstaller/none"

I don't think the requests are blocked at the data center level.

**Comment by strager** [comment]
The [logs you posted](https://github.com/microsoft/winget-pkgs/pull/123771#issuecomment-1782129851) mention certificate validity.
* I checked the HTTPS certificates and they are valid in October 25.
* I also checked the code signature for the .msix file and it is valid in October 25, and its timestamp signature is valid in October 25 too.
* I also checked the code signature for the .exe file inside the .msix file and it and its timestamp signature are valid too.
(Validity was confirmed using Windows Explorer. Right click > Properties > Digital Signatures.)

Perhaps the signature thing is a red herring, or there's something I am overlooking.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -2146762495 
2023-10-26 18:09:47.838 [CORE] Deployment operation #0: error 0x800B0101: Opening the package from location quick-lint-js.msix failed. 
2023-10-26 18:09:47.839 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!00007FFBBF4C9A45: (caller: 00007FFBBF453515) Exception(1) tid(d4c) 800B0101 A required certificate is not within its validity period when verifying against the current system clock or the timestamp in the signed file. 
2023-10-26 18:09:48.179 [CLI ] MSIX installer failed: 2148204801

Log file: [InstallationVerification-x64-Scope_Undefined-Locale_Undefined-collector_logs.txt](https://github.com/microsoft/winget-pkgs/files/13219979/InstallationVerification-x64-Scope_Undefined-Locale_Undefined-collector_logs.txt)

**Comment by strager** [comment]
I think I figured out the issue with version 2.17.0. I will make a new release of quick-lint-js with a fix.

**Comment by strager** [comment]
quick-lint-js version 2.18.0 has a fix for the code signing issue. #124702

**Pull request closed without merging**
