### PR TITLE
New version: TeamViewer.TeamViewer version 15.33.7

### PR DESCRIPTION
**Pull request by ImJoakim**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/71792)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Comment by ImJoakim** [comment]
That's odd.

image

image

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Comment by ygprem** [comment]
Hello @ImJoakim,

I've been having the same issue for the past week and went ahead and opened a ticket with Teamviewer's support, it's the weirdest thing as the download links for the 15.x have this issue :

image

But not the 14.x version files :

image

Let's hope they'll respond positively.

**Comment by ygprem** [comment]
Hello @ImJoakim,

My ticket has been escalated to the relevant service yesterday and even though i didn't receive a confirmation yet, it appears the issue has been fixed for both the host and regular version :

image

Could you update both your PRs accordingly ?

**Comment by ImJoakim** [comment]
> Hello @ImJoakim,
> 
> My ticket has been escalated to the relevant service yesterday and even though i didn't receive a confirmation yet, it appears the issue has been fixed for both the host and regular version :
> 
> image
> 
> Could you update both your PRs accordingly ?

Appreciate it, thank you!

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
