### PR TITLE
Remove old version of JanDeDobbeleer.OhMyPosh

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
null

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Oops, pressed the wrong button.

This PR doesn't address the reboot issue.

**Comment by vedantmgoyal2009** [comment]
> This PR doesn't address the reboot issue.

It worked on my machine.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
It wants you to provide installer switches to prevent rebooting which you can get from https://docs.microsoft.com/en-us/windows/win32/msi/standard-installer-command-line-options.

You can reproduce this issue by running the installer with the `/passive` switch without using Windows Package Manager.

**Comment by vedantmgoyal2009** [comment]
Should the package be removed?

**Comment by arjun-msft** [comment]
We are seeing error 3010 in the log files, which means the installation needs a reboot.  We are tracking this via [this issue](https://github.com/microsoft/winget-cli/issues/994).

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
