### PR TITLE
New package: windows.PCSX2 version 1.6.0

### PR DESCRIPTION
**Pull request by MesterPerfect**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/127891)

### CODE REVIEW

**Comment by MesterPerfect** [comment]
Template: msftbot/requiresApproval/moderator

**Comment by MesterPerfect** [comment]
> MesterPerfect,
> 
> The check-in policies require a moderator to approve PRs from the community.
> 
> Our [moderators](https://github.com/microsoft/winget-pkgs/issues/15674#issue-908889039) are community volunteers, please be patient and allow them sufficient time to review your submission.
> 
> Template: msftbot/requiresApproval/moderator

ok thanks

**Comment by MesterPerfect** [comment]
MesterPerfect:windows.PCSX2-1.6.0-10b500e4-e5c9-437e-a905-3c8d0cb81243

> AND APP.DisplayName = 'Application Name' -- Replace Application Name

AND APP.DisplayName = 'PCSX2'

**Comment by MesterPerfect** [comment]
@stephengillie

**Comment by stephengillie** [comment]
I've validated this program several times in a Windows 10 VM, and the installer doesn't seem to install a completed program. Just a couple of DLLs.

**Comment by MesterPerfect** [comment]
It appears that the developers of PCSX2 did not prioritize in-line commands for installation. Instead, their focus was on command lines to control the program post-installation. Therefore, we can consider the issue resolved.

**Pull request closed without merging**
