### PR TITLE
New package: browsh.browsh version 1.8.2

### LINKED ISSUE #104234: [Package Request]: brow.sh
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.brow.sh/downloads/
Publisher: [Thomas Buckley-Houston](https://tombh.co.uk/)
Package Name: ThomasBuckleyHouston.Browsh
Description: Browsh is a fully-modern text-based browser. It renders anything that a modern browser can; HTML5, CSS3, JS, video and even WebGL.
Package Version: 1.8.0
Installer URL: https://github.com/browsh-org/browsh/releases/download/v1.8.0/browsh_1.8.0_windows_amd64.exe

### PR DESCRIPTION
**Pull request by Dragon1573**
## Description

- Resolve #104234

## Checks

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136968)

### CODE REVIEW

**Comment by Dragon1573** [comment]
@stephengillie - Please remove https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue, as problems from external area is successfully solved.

**Comment by stephengillie** [comment]
Hi @Dragon1573,

Our automation readded the label before I could approve, and I lost track of it. Then it closed the PR. Sorry for this outcome. If you can un-delete the branch somehow, I would be happy to review to approve.

**Comment by Dragon1573** [comment]
The branch `issues/104234` is successfully restored.

Thanks for "re-tracking" this issue ❤️

**Comment by Dragon1573** [comment]
It seems the bot keeps violating your control 😄

Is there anything wrong with my contents? Or is they with the bot? Can I close and recreate a brand new pull request on the same base branch `Dragon1573:issues/104234`?

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
