### PR TITLE
Add Format Factory 5.1.0.0

### PR DESCRIPTION
**Pull request by hifocus**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/709)

### CODE REVIEW

**Comment by hifocus** [comment]
Hello CI.

**Comment by hifocus** [comment]
Thank god

**Comment by auanasgheps** [comment]
I would love to update this to make it working but seems like I can't access this file. I will be opening a new PR, based on the work of @hifocus

**Comment by hifocus** [comment]
> I would love to update this to make it working but seems like I can't access this file. I will be opening a new PR, based on the work of @hifocus

As of download sources:
- `http://www.pcfreetime.com/public/FFSetup5.2.1.0.exe`, this is the link provided by Format Factory's English official site, http://www.pcfreetime.com/formatfactory/index.php?language=en. Hosted on a server within China; normally it would still be accessible globally but incidents do happen.
- `http://down.pcgeshi.com/FormatFactory_setup.exe`, this is the link provided by its Chinese official site, http://www.pcgeshi.com, which is where it's originated. Hosted by a server from `vpls.com` in NY. Should be accessible globally.

You may want to use the second link / official site when raising another PR base on this software.
Thanks for helping.

**Comment by auanasgheps** [comment]
What I meant was your YAML configuration file. By the way I've created a new PR [here](https://github.com/microsoft/winget-pkgs/pull/1445) but the boot seems stuck.

**Comment by KevinLaMS** [comment]
Duplicate of #https://github.com/microsoft/winget-pkgs/pull/1445
can we close this?

**Comment by hifocus** [comment]
> Duplicate of ##1445
> can we close this?

Of course. However as the concerns I raised above still exist, please consider to improve the usability of winget, instead of leaving it under the current style. Thank  you.

**Pull request closed without merging**
