### PR TITLE
New version: o2sh.onefetch version 2.16.0

### PR DESCRIPTION
**Pull request by o2sh**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/97695)

### CODE REVIEW

**Comment by o2sh** [comment]
@vedantmgoyal2009 any idea what could be causing the failure? Thanks in advance 👍

**Comment by stephengillie** [comment]
Hi @o2sh,

The package installs normally, but requires `Microsoft.VCRedist.2015+.x64` to run:
image

Pending:
* https://github.com/microsoft/winget-cli/issues/163

**Comment by Trenly** [comment]
[Policy] Blocking-Issue

**Comment by o2sh** [comment]
@Trenly So what can I do for this PR to be merged? Do I need to wait for https://github.com/microsoft/winget-cli/issues/163 to be  resolved?

**Comment by Trenly** [comment]
> @Trenly So what can I do for this PR to be merged? Do I need to wait for [microsoft/winget-cli#163](https://github.com/microsoft/winget-cli/issues/163) to be resolved?

Yes, until dependencies are not experimental the only thing you can do is to package the dependencies with your installer such that your installer also installs the VC runtime if it isn't present

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Earlier I missed that this is an update to an existing package with a dependency.

**Pull request merged**
