### PR TITLE
Update: Citadel5-JP.GS-Base version 21.1

### PR DESCRIPTION
**Pull request by Trenly**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/181572)

### CODE REVIEW

**Review by mdanish-kh — APPROVED** [review]

**Comment by Citadel5-JP** [comment]
Hi,

A quick question: I added manifests/c/Citadel5-JP/GS-Base/21.1/Citadel5-JP.GS-Base.yaml as a "singleton" two days ago and it was published. However, it the above my folder that single file was split 16 hours ago (or so) into 3 files (not by me), separating those originally merged 3 sections. (And some "internal-error-dynamic-scan" tags appeared after this for a moment.)

I'm not sure re: the following: 
the manifest file still includes the URL of that original single yaml file on my server for auto-updating. Should I copy these new three files to my server or leaving this one till the next version update is OK?

Thanks
JP

**Comment by mdanish-kh** [comment]
@Citadel5-JP Singleton manifest format is deprecated. This PR splits the existing singleton manifest into the preferred "multi-manifest" format. There is tooling available in form of [YamlCreate.ps1](https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1) / [WinGet-Create](https://github.com/microsoft/winget-create) for you to automate this moving forward or even add it as part of your release CI for auto-submission

Helpful videos:

- https://learn.microsoft.com/en-us/shows/open-at-microsoft/contributing-to-windows-package-manager/
- https://learn.microsoft.com/en-us/shows/open-at-microsoft/wingetcreate-keeping-winget-packages-up-to-date/

**Comment by Citadel5-JP** [comment]
Thanks. If I publish a new version (and with a new version number) of the installer on my web server in the same location and with same name overwriting the previous one (that is, although the file name includes the version number, it's mainly the major version number only), may I ask what the typical procedure is (to avoid the sha256 mismatches)?

**Comment by stephengillie** [comment]
> Thanks. If I publish a new version (and with a new version number) of the installer on my web server in the same location and with same name overwriting the previous one (that is, although the file name includes the version number, it's mainly the major version number only), may I ask what the typical procedure is (to avoid the sha256 mismatches)?

This is what we commonly call a "vanity URL", as it's more often used in marketing and promotions than in technical support or archiving. The recommended way to update the hash is to add a CI step that creates the PR. We have automation that scans `InstallerURLs` daily, and opens PRs to update manifests with new hashes, when a hash mismatch is detected, but its coverage rate is below 100%, and takes longer than the CI method.

Here is more info about the `Internal-Error-Dynamic-Scan` label, whose name I sometimes shorten to "IEDS":
- https://github.com/microsoft/winget-pkgs/discussions/155218

**Pull request merged**
