### PR TITLE
New version: Zoom.ZoomRooms version 6.1.0

### PR DESCRIPTION
**Pull request by PckgrBot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/162023)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-07-10 10:35:44.818 [CLI ] ShellExecute installer failed: 1
> Installation failed with exit code -1978334957
> 2024-07-10 10:29:45.646 [CLI ] ShellExecute installer failed: 1633
> MSI (s) (00:BC) [10:29:45:263]: Product: Zoom Rooms Installer -- Installation failed.
> This installation package is not supported by this processor type. Contact your product vendor.

Automated error analysis suggests -1978335226 may mean Install successful but system restart may be required.

Automated error analysis suggests 1633 may mean `ERROR_INSTALL_PLATFORM_UNSUPPORTED` - This installation package is not supported by this processor type. Does this manifest have `Architecture: x86`? It might need to be `x64`.

(Automated response - build 886.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-07-10 10:35:44.818 [CLI ] ShellExecute installer failed: 1
> Installation failed with exit code -1978334957
> 2024-07-10 10:29:45.646 [CLI ] ShellExecute installer failed: 1633
> MSI (s) (00:BC) [10:29:45:263]: Product: Zoom Rooms Installer -- Installation failed.
> This installation package is not supported by this processor type. Contact your product vendor.

Automated error analysis suggests -1978335226 may mean Install successful but system restart may be required.

Automated error analysis suggests 1633 may mean `ERROR_INSTALL_PLATFORM_UNSUPPORTED` - This installation package is not supported by this processor type. Does this manifest have `Architecture: x86`? It might need to be `x64`.

(Automated response - build 886.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-07-10 10:35:44.818 [CLI ] ShellExecute installer failed: 1
> Installation failed with exit code -1978334957
> 2024-07-10 10:29:45.646 [CLI ] ShellExecute installer failed: 1633
> MSI (s) (00:BC) [10:29:45:263]: Product: Zoom Rooms Installer -- Installation failed.
> This installation package is not supported by this processor type. Contact your product vendor.

Automated error analysis suggests -1978335226 may mean Install successful but system restart may be required.

Automated error analysis suggests 1633 may mean `ERROR_INSTALL_PLATFORM_UNSUPPORTED` - This installation package is not supported by this processor type. Does this manifest have `Architecture: x86`? It might need to be `x64`.

(Automated response - build 886.)

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-07-11 00:21:04.980 [CLI ] ShellExecute installer failed: 1

Automated error analysis suggests -1978335226 may mean Install successful but system restart may be required.

(Automated response - build 886.)

**Pull request merged**
