### PR TITLE
RStudio.quarto version 1.1.149

### PR DESCRIPTION
**Pull request by dpprdan**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/75350)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by dpprdan** [comment]
cc @cderv

**Review by cderv — APPROVED** [review]
Thanks @dpprdan for this. I was planning to do it in a few days as usually we wait a few days between last release on Github and official announcement of new release (here v1.1 announcement). This is just in case we missed an obvious thing in the v1.1 release. 

Nevermind, we can make it available now as you've done the PR. Thanks for this ! 

And thanks a lot for having pinged me here, really appreciated. Please do if you do the next update before me 😉

**Review by ItzLevvie — APPROVED** [review]

**Comment by dpprdan** [comment]
@ItzLevvie It seems that your approval wasn't picked up (at least not as to allow merging)... 🤷🏻‍♂️ 

@cderv Sure thing!

**Comment by dpprdan** [comment]
This may need another /azp run?

**Comment by dpprdan** [comment]
@cderv 

> This is just in case we missed an obvious thing in the v1.1 release.

Haha, I suppose you did? 😄 https://github.com/quarto-dev/quarto-cli/releases/tag/v1.1.163 
Should I add this to winget or just leave this to you from now on.
(I just stumbled upon the 1.1.149 release yesterday and thought it might be helpful to add it).

> usually we wait a few days between last release on Github and official announcement [...] just in case we missed an obvious thing

Sounds like Release Candidates might be useful?  😉

**Comment by cderv** [comment]
I told you :) 

First releases of 1.1 were noted as RC. I believe this one is closer to the last one, but until the official announcement of the v1.1 there is still a change that this would change. This is still why we don't automate the winget release for example yet. 
Next releases will be more controled probably, project is still early is this is the first time we upgrade a stable release (v1 to v1.1). 

I'll do the winget update anyway in the future, so no need to watch out for it,n specifically, but that helps anyway, so thank you!

**Pull request merged**
