### PR TITLE
Bluefish: change to https:// schema 

### PR DESCRIPTION
**Pull request by luzpaz**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

-----

Per repology https://repology.org/repository/winget/problems

> Homepage link http://bluefish.openoffice.nl/features.html is a permanent redirect to its HTTPS counterpart https://bluefish.openoffice.nl/features.html and should be updated.

Please squash commits (having issues on my side)
 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/113711&drop=dogfoodAlpha

### CODE REVIEW

**Review by mdanish-kh — CHANGES_REQUESTED** [review]
Only one manifest can be modified per PR. You'll need two separate PRs for this change

**Comment by luzpaz** [comment]
Is it possible to make an exception for this PR since the change is so trivial ?

**Comment by mdanish-kh** [comment]
> Is it possible to make an exception for this PR since the change is so trivial ?

I don't believe so; The validation pipeline checks won't pass when the change is in multiple manifests. The auto-merge process will only kick in when all the pipelines check pass and the PR is approved by a moderator.

**Comment by ItzLevvie** [comment]
[Policy] Needs-Author-Feedback

**Pull request closed without merging**
