### PR TITLE
New version: Freeplane.Freeplane version 1.11.6

### PR DESCRIPTION
**Pull request by jeremytmsi**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/118144)

### CODE REVIEW

**Comment by oldium** [comment]
Just faced the issue with invalid download on 1.11.5 - the download link gets invalid with every release, so it would make sense to use `https://sourceforge.net/projects/freeplane/files/freeplane%20stable/archive/<version>/Freeplane-Setup-with-Java-<version>.exe/download` instead of plain `https://sourceforge.net/projects/freeplane/files/freeplane%20stable/Freeplane-Setup-with-Java-<version>.exe/download`.

**Comment by oldium** [comment]
I fixed download URIs of 1.11.2 and 1.11.5 in #118158 and #118159

**Comment by stephengillie** [comment]
> Just faced the issue with invalid download on 1.11.5 - the download link gets invalid with every release, so it would make sense to use archive link `https://sourceforge.net/projects/freeplane/files/freeplane%20stable/archive/<version>/Freeplane-Setup-with-Java-<version>.exe/download` instead of link `https://sourceforge.net/projects/freeplane/files/freeplane%20stable/Freeplane-Setup-with-Java-<version>.exe/download`, which is valid only for the latest release.
> 
> See also #63220

Hi @oldium,

The issue is really in that the developer removes old versions. The suggestion is basically to use a "vanity" URL that is updated with every release instead of a static URL, which runs counter to one of our best practices. 

We have to create a new manifest version (usually by copying forward details from the previous version), to add the new file hash. That the developer removes old versions means we have a 2nd step of removing the old manifest also. 

Right now, users will see a download error. If we update from the static URL, users will see the download begin and complete, then the install fail due to a hash mismatch. I think the former user experience is better, what are your thoughts?

**Review by stephengillie — APPROVED** [review]

**Comment by oldium** [comment]
> > Just faced the issue with invalid download on 1.11.5 - the download link gets invalid with every release, so it would make sense to use archive link `https://sourceforge.net/projects/freeplane/files/freeplane%20stable/archive/<version>/Freeplane-Setup-with-Java-<version>.exe/download` instead of link `https://sourceforge.net/projects/freeplane/files/freeplane%20stable/Freeplane-Setup-with-Java-<version>.exe/download`, which is valid only for the latest release.
> > See also #63220
> 
> Hi @oldium,
> 
> The issue is really in that the developer removes old versions. The suggestion is basically to use a "vanity" URL that is updated with every release instead of a static URL, which runs counter to one of our best practices.
> 
> We have to create a new manifest version (usually by copying forward details from the previous version), to add the new file hash. That the developer removes old versions means we have a 2nd step of removing the old manifest also.
> 
> Right now, users will see a download error. If we update from the static URL, users will see the download begin and complete, then the install fail due to a hash mismatch. I think the former user experience is better, what are your thoughts?

@stephengillie That is not completely correct. The developer maintains the latest version at `https://sourceforge.net/projects/freeplane/files/freeplane%20stable`, where it is updated every release, so it is expected that the old release is replaced by a new release there and any link to that place gets broken. But at the same time the _identical_ latest release files and also all previous releases can be found at fixed location at `https://sourceforge.net/projects/freeplane/files/freeplane%20stable/archive`. It should be sufficient to take the release simply always from the archive and I do not understand why it is not like that.

**Comment by stephengillie** [comment]
> > > Just faced the issue with invalid download on 1.11.5 - the download link gets invalid with every release, so it would make sense to use archive link `https://sourceforge.net/projects/freeplane/files/freeplane%20stable/archive/<version>/Freeplane-Setup-with-Java-<version>.exe/download` instead of link `https://sourceforge.net/projects/freeplane/files/freeplane%20stable/Freeplane-Setup-with-Java-<version>.exe/download`, which is valid only for the latest release.
> > > See also #63220
> > 
> > 
> > Hi @oldium,
> > The issue is really in that the developer removes old versions. The suggestion is basically to use a "vanity" URL that is updated with every release instead of a static URL, which runs counter to one of our best practices.
> > We have to create a new manifest version (usually by copying forward details from the previous version), to add the new file hash. That the developer removes old versions means we have a 2nd step of removing the old manifest also.
> > Right now, users will see a download error. If we update from the static URL, users will see the download begin and complete, then the install fail due to a hash mismatch. I think the former user experience is better, what are your thoughts?
> 
> @stephengillie That is not completely correct. The developer maintains the latest version at `https://sourceforge.net/projects/freeplane/files/freeplane%20stable`, where it is updated every release, so it is expected that the old release is replaced by a new release there and any link to that place gets broken. But at the same time the _identical_ latest release files and also all previous releases can be found at fixed location at `https://sourceforge.net/projects/freeplane/files/freeplane%20stable/archive`. It should be sufficient to take the release simply always from the archive and I do not understand why it is not like that.
> 
> There is no hash change with new release at `https://sourceforge.net/projects/freeplane/files/freeplane%20stable`, the files are named differently (they have version in them), so when there is new release, the installation fails on 404 error, not on non-matching hash.

Thanks for agreeing with me, that the static URLs are preferred to the dynamic "vanity" URL. And that the 404 error is preferrable to a hash error. I'm confused why the agreement was stated in the form of a correction and challenge, as though confrontation is necessary to conversation, which is untrue.

**Comment by oldium** [comment]
@stephengillie I actually do not understand what you mean with static and dynamic "vanity" URLs. I just described where the developer is storing release files, it is consistent and predictable with every release (`https://sourceforge.net/projects/freeplane/files/freeplane%20stable/archive/<version>/Freeplane-Setup-with-Java-<version>.exe/download`) and I just think we should use that URL in WinGet manifests. Do not take it as an insult, it just described the situation and stated my recommendation.

I also have not expressed any preference on 404 error or hash error, I think (and I repeat myself) we should use the URL with "archive" in it to prevent any download errors. This is why I do not understand (and do not take it as insult) why this Pull Request was merged, when we know it uses URL, which breaks. I do not see this as a Freeplane developer's problem, it is this Pull Request's problem.

**Pull request merged**
