### PR TITLE
[PHP] Add PHP 8.4

### PR DESCRIPTION
**Pull request by Ayesh**
Follow-up to GH-147354.

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? Yes, #56226 and #58422

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/196185)

### CODE REVIEW

**Review by stephengillie — CHANGES_REQUESTED** [review]
Hi @Ayesh,

This package appears to have a dependency on `VCRedist`:
image

**Comment by Ayesh** [comment]
Hi @stephengillie, thank you for catching this. I had indeed missed to add vs17 add dependencies.
Added and force-pushed. It would be great if you could review again. 

Thank you.

**Comment by Ayesh** [comment]
Hi @stephengillie, thank you for catching this. I had indeed missed to add vs17 add dependencies.
Added and force-pushed. It would be great if you could review again. 

Thank you.

**Comment by mdanish-kh** [comment]
@Ayesh - We have a discussion going on in [WinGet community chat at Element](https://matrix.to/#/!LEwByvxhTNZZcKeCCY:gitter.im/$2UAIJXdSBD01LTUwqPnIvOYHxO0jQ8zTd5vFzXbOjcA?via=gitter.im&via=matrix.org&via=mozilla.org) on how best to manage the PHP package and what should be the appropriate PackageIdentifier (either `PHP.PHP` or `PHP.PHP.major.minor`). Would you be able to share your thoughts if any in that discussion?

**Comment by Ayesh** [comment]
Thank you for starting the discussion. I think you  assessment weighing pros and cons is spot-on! I added a some details justifying why it's more desirable to use `PHP.PHP.major.minor` pattern in the chat too.

**Comment by stephengillie** [comment]
Verify:
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
