### PR TITLE
New package: Enterbrain.RPGMaker2000RTP version 1.6

### PR DESCRIPTION
**Pull request by ForeverFloating**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/167318)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 887.)

**Comment by stephengillie** [comment]
Hi @ForeverFloating,

This image was opened during one of my processes, and I've only just connected it to this PR. (Please ignore the Defender notification.)
image
Is there a silent installer switch needed to begin the install process?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 887.)

**Comment by ForeverFloating** [comment]
It might. I'm honestly not sure how to find out what installer switches to use for EXE files, so that could very well be the case.

**Comment by stephengillie** [comment]
Sometimes, an installer will respond to a switch like `/?` or `--help` with a list of switches.

**Comment by ForeverFloating** [comment]
> Sometimes, an installer will respond to a switch like `/?` or `--help` with a list of switches.

Tried those switches and the executable just ran instead. I even tried using the [Ultimate Silent Switch Finder](https://deployhappiness.com/the-ultimate-exe-silent-switch-finder/), which indicated that the EXE file is an NSIS package and should use the `/S`switch, but passing the `/S` switch to the installer doesn't make the package install silently (the typical dialog box still shows up).

**Comment by stephengillie** [comment]
Unfortunately, not every developer has added a silent install path to their installer.

**Comment by ForeverFloating** [comment]
Closing the pull request because there appears to be no silent switch for this installer.

**Pull request closed without merging**
