### PR TITLE
New Version: OO-Software.AutoBackup version 2.5.27

### PR DESCRIPTION
**Pull request by oo-cmatuschka**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/157889)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @oo-cmatuschka,

The hashes of these installers match the hashes from the `Professional` version - is that intentional?

**Comment by oo-cmatuschka** [comment]
> The hashes of these installers match the hashes from the Professional version - is that intentional?

Hello Stephen,

Firstly, I want to thank you for your work and apologize for my mistake. This is one of the first manifests I have submitted.

With the Professional versions of the manifests, our installations are not recognized in "winget list," so here's another attempt without 'Professional.' It might have been better to either delete the Professional manifests or move them with adjustments. What do you think would be the better solution?

Based on my understanding of winget, I assumed that the ProductCodes in the installer.yaml would result in a match for our application in "winget list", but unfortunately, that was not the case. I also hadn't found a way to test this. An attempt with "wingetty" yielded no results, so I thought I’d just give it a try. I was not aware that it required manual review.

Best regards,
Christian

**Comment by stephengillie** [comment]
Thank you and no worries. We're proud to say that every manifest submitted has had some level of human review. I'm not familiar with "wingetty" - did the package manager client have the same output? Can you paste it here? 

It would be best to troubleshoot why the Professional version isn't showing up. This repository is somewhat like a database, and our Publish pipeline packages the contents into an MSIX for the package manager client to download and consume. So duplicate manifests and directories aren't ideal. 

Which keywords were used with `winget list` to find the application?

**Comment by oo-cmatuschka** [comment]
> Thank you and no worries. We're proud to say that every manifest submitted has had some level of human review. I'm not familiar with "wingetty" - did the package manager client have the same output? Can you paste it here?
> 
> It would be best to troubleshoot why the Professional version isn't showing up. This repository is somewhat like a database, and our Publish pipeline packages the contents into an MSIX for the package manager client to download and consume. So duplicate manifests and directories aren't ideal.
> 
> Which keywords were used with `winget list` to find the application?

Hi Stephen,

Yes, all of you can truly be proud of that!

If you're not familiar with Wingetty, that's not a problem. I spent two days trying to integrate a sort of Dev repository to solve such problems in advance. However, with Wingetty, you can only specify very simple manifest files. I didn't get it right, but that doesn't matter now.

As you might have noticed, I uploaded three additional versions (4.10.11, 5.1.157 & 6.1.127) of O&O AutoBackup as manifest files, which you also approved. These versions are recognized by winget. And now, the other versions (2.5.27 & 3.0.37), which weren't recognized before, are also recognized. That’s actually fantastic, but also very mysterious. 😉

However, the first two versions are still present as Professional manifests in the RP (and were supposed to be deleted under #158474 & #158478). Instead of the deleted ones, the numbers #158478 & #157890 should now be active, which are logically recognized as duplicates.

Therefore, my request is, could you approve the deletion of the manifests for #158474 & #158478 and then approve #158478 & #157890 in their place? This would make it consistent.

O&O AutoBackup is just my test application; I have several applications ahead of me with various versions, and I hope the next ones go better. 😉

**Comment by stephengillie** [comment]
I'm willing to help, but I'm not sure that the requested steps will have the desired outcome. 

For these first 2, we need to troubleshoot why they're not being validated. 
- https://github.com/microsoft/winget-pkgs/pull/158474
  - This is listed as a removal, but seems to have both both [removal](https://github.com/microsoft/winget-pkgs/pull/158474/commits/72e93d876614882b0e1cbd69a5d50993c60203c0) and [addition](https://github.com/microsoft/winget-pkgs/pull/158474/commits/9ca2475dbe7f9cb2ed7b5b6d902d7856fba6ec45) commits. 
- https://github.com/microsoft/winget-pkgs/pull/158478
  - This one is being listed as both removal and addition, but also seems to have both [removal](https://github.com/microsoft/winget-pkgs/pull/158478/commits/ae76240f11ef01846320a384099b3ce2a3ce090a) and [addition](https://github.com/microsoft/winget-pkgs/pull/158478/commits/484db8f4a7683d4886aff465462daa57ebb195ac) commits. 
- https://github.com/microsoft/winget-pkgs/pull/157890
  - This is the other addition. It would seem to duplicate the PR above in (re)-[adding](https://github.com/microsoft/winget-pkgs/pull/157890/commits/fe764256c6ea9dc32aad66da5bf1ea9bd8f7490f) version `3.0.37`.

Could you try syncing your branches? https://github.com/microsoft/winget-pkgs/pull/158474#issuecomment-2177283123

**Comment by stephengillie** [comment]
Just curious, and putting into a separate comment to logically separate it from the work above.

> As you might have noticed, I uploaded three additional versions (4.10.11, 5.1.157 & 6.1.127) of O&O AutoBackup as manifest files, which you also approved. These versions are recognized by winget. And now, the other versions (2.5.27 & 3.0.37), which weren't recognized before, are also recognized. That’s actually fantastic, but also very mysterious. 😉

What was the timeilne for this - how long between versions `2.5.27` & `3.0.37` being uploaded and the other 3 versions? 

> ...our Publish pipeline packages the contents into an MSIX for the package manager client to download and consume.

> The more commits that are merged close to one another, the longer the publish pipeline takes since each commit has to update the package index separately. ([Trenly](https://matrix.to/#/!LEwByvxhTNZZcKeCCY:gitter.im/$dc1KgD7XUwaEklgKp6WdGyHb5BLYoluU3irOZiC6nFI?via=gitter.im&via=matrix.org&via=beeper.com) on Gitter chat)

If these were merged during a time of many changes, it might have taken a significant amount of time to become processed and available for download.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
