### PR TITLE
New version: OtfriedCheong.Ipe version 7.2.29

### LINKED ISSUE #176757: [Update Request]: Ipe
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

OtfriedCheong.Ipe

### Package Version

7.2.29

### Please describe the changes you would like to see

There is a new version available fromMay 25, 2024.
https://github.com/otfried/ipe/releases

### PR DESCRIPTION
**Pull request by ghost**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? closes #176757 

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/176816)

### CODE REVIEW

**Comment by paksnuk** [comment]
@microsoft-github-policy-service agree

**Comment by Dragon1573** [comment]
> [!TIP]
>
> Associate this pull request with the issue can help automatically closing issue while pull request is merged.
>
> Edit [your first comment](https://github.com/microsoft/winget-pkgs/pull/176816#issue-2561251339) as follows.
>
> ```diff
> - - [x] Is there a linked Issue? #176757 
> + - [x] Resolve #176757 
> ```

**Comment by Dragon1573** [comment]
Manually verified in _Windows Sandbox_. It seems this package can't be launched by symbolic links 😞

image

**Comment by paksnuk** [comment]
I'm don't know how to debug this, but I can launch the app using the symlink successfully via double-click on Explorer or via the start menu (run command, not a start menu link). Thus the functionality provided by the symlink might be incomplete, but definitely helpful.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\ipe.exe returned exit code: -1073741515
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\ipepresenter.exe returned exit code: -1073741515

Automated error analysis suggests -1073741515 may mean STATUS_DLL_NOT_FOUND - possibly due to a dependency on `Microsoft.VCRedist.2015+.x64` (or `.x86`).

(Automated response - build 896.)

**Comment by paksnuk** [comment]
The dll issue also occurs with the current winget version. If this is an issue with accepting this PR, I think removing the old package is the way to go forward. Otherwise, users will download a version with the same issue, that is also outdated.

**Comment by Trenly** [comment]
@paksnuk - Support for zipped binaries has now been added and is available in the pipelines. This will require you to update your submission to ManifestVersion: 1.9.0 and set ArchiveBinariesDependOnPath: true in the installer node. To keep things clean, this PR is being closed. Please submit a new PR for the latest version of this package. Thank you for your contributions!

**Pull request closed without merging**
