### PR TITLE
Nelson v1.1.0.3654

### PR DESCRIPTION
**Pull request by Nelson-numerical-software**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137040)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @MaanuelMM,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 674.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-29 14:42:17.746 [FAIL] Installer failed security check. Url: https://github.com/nelson-lang/nelson/releases/download/v1.1.0/Nelson-1.1.0.3654-x86-32.exe Result: 0x80004005 MSI (s) (94:30) [14:41:01:946]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.31.31103. Product Version: 14.31.31103. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (94:58) [14:41:02:899]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Additional Runtime - 14.31.31103. Product Version: 14.31.31103. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [1928:1BD8][2024-01-29T14:40:59]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 674.)

**Comment by Nelson-numerical-software** [comment]
> Automatic Validation ended with:
> 
> > Installation failed with exit code -1978335187 2024-01-29 14:42:17.746 [FAIL] Installer failed security check. Url: https://github.com/nelson-lang/nelson/releases/download/v1.1.0/Nelson-1.1.0.3654-x86-32.exe Result: 0x80004005 MSI (s) (94:30) [14:41:01:946]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.31.31103. Product Version: 14.31.31103. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (94:58) [14:41:02:899]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Additional Runtime - 14.31.31103. Product Version: 14.31.31103. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [1928:1BD8][2024-01-29T14:40:59]w363: Could not create system restore point, error: 0x80070422. Continuing...
> 
> (Automated response - build 674.)

This binary was generated on github CI.
It is certainly a false positive (expect if github CI is corrupted).

How to declare that it is a false positive ?

(Thanks)

**Comment by Nelson-numerical-software** [comment]
> Hello @Nelson-numerical-software,
> 
> The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.
> 
> Template: msftbot/validationError/installation/general

Can you get more information ?

application was tested and installed on 32 bits platforms.
There is no major change between 1.1.0 and previous version 1.0.0 (already accepted)

**Comment by stephengillie** [comment]
Hi @Nelson-numerical-software,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 682.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-30 16:21:52.553 [FAIL] Installer failed security check. Url: https://github.com/nelson-lang/nelson/releases/download/v1.1.0/Nelson-1.1.0.3659-x86-32.exe Result: 0x80004005 MSI (s) (BC:64) [16:20:35:281]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.31.31103. Product Version: 14.31.31103. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (BC:E8) [16:20:36:328]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Additional Runtime - 14.31.31103. Product Version: 14.31.31103. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [1210:176C][2024-01-30T16:20:33]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 682.)

**Comment by Nelson-numerical-software** [comment]
installer detected a trojan. It is a false positive :( 
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Trojan%3AWin32%2FWacatac.B!ml&threatid=2147735505

How to declare it as false positive ?

**Comment by stephengillie** [comment]
Hi @Nelson-numerical-software,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 684.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-30 16:21:52.553 [FAIL] Installer failed security check. Url: https://github.com/nelson-lang/nelson/releases/download/v1.1.0/Nelson-1.1.0.3659-x86-32.exe Result: 0x80004005 MSI (s) (BC:64) [16:20:35:281]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.31.31103. Product Version: 14.31.31103. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (BC:E8) [16:20:36:328]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Additional Runtime - 14.31.31103. Product Version: 14.31.31103. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [1210:176C][2024-01-30T16:20:33]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 684.)

**Comment by Nelson-numerical-software** [comment]
> Hello @Nelson-numerical-software,
> 
> The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.
> 
> Template: msftbot/validationError/installation/general

Can you restart check ? (thanks)

**Comment by stephengillie** [comment]
Hi @Nelson-numerical-software,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 695.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-30 21:25:06.701 [FAIL] Installer failed security check. Url: https://github.com/nelson-lang/nelson/releases/download/v1.1.0/Nelson-1.1.0.3659-x86-32.exe Result: 0x80004005 MSI (s) (24:08) [21:23:54:600]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.31.31103. Product Version: 14.31.31103. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (24:D8) [21:23:55:506]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Additional Runtime - 14.31.31103. Product Version: 14.31.31103. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [119C:1500][2024-01-30T21:23:53]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 695.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
