### PR TITLE
New package: ArduinoSA.ArduinoIDE version 2.3.2.0

### PR DESCRIPTION
**Pull request by Jvr2022**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/149638)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Jvr2022,

Arduino software requires a USB driver, to create the virtual serial ports needed to communicate with the board's microprocessors. The installer starts this install also, but doesn't block and continues to install normally:
image

The software appears to be written in such a way that when the driver is missing, it operates with reduced functionality - the Port menu item is disabled:
image

I'm concerned that the driver might not become installed on some user PCs, giving a bad user experience despite otherwise operating correctly. What are your thoughts on this?

**Comment by Jvr2022** [comment]
If this is a big problem I should close this

**Comment by stephengillie** [comment]
I'm not sure that this completely counts as an "unattended install". I'm going to add the `DriverInstall` label, despite the driver installer not completely blocking the main package installer. Let me know if this should change.

**Comment by denelon** [comment]
Once the install can complete without user interactivity the package may be added to the community repository.

**Pull request closed without merging**
