### PR TITLE
iTop.iTopEasyDesktop version 2.7.1.12

### PR DESCRIPTION
**Pull request by KarbitsCode**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?
Closes #184309

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/184587)

### CODE REVIEW

**Comment by KarbitsCode** [comment]
> Hello @KarbitsCode,
> 
> I am sorry to report that the Sha256 Hash does not match the installer. This may be caused by using a vanity URL rather than a URL directly to the binary.
> 
> Please check the HASH and submit again. Sorry for the inconvenience.
> 
> Template: msftbot/validationError/installers/hashMismatch

The hash still matches here, I'm not sure what is the problem.

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335215
> 2024-10-20 17:51:42.309 [CLI ] Package hash verification failed. SHA256 in manifest [b6a828d945e1a22f64e1539dd3385e8f035b19d6004f942e3743a120fa96c38d] does not match download [6fbe6d38cc9069ac02c2de62810b40c6dabee682c90c3bdedab5e353102d6b5a]

Automated error analysis suggests -1978335215 may mean The installer files hash does not match the manifest

(Automated response - build 897.)

**Comment by KarbitsCode** [comment]
Could this be verified manually?

**Comment by stephengillie** [comment]
> Could this be verified manually?

Manual Validation should come to the same outcome. The pipelines are operating correctly, assuming that the hash has changed again. Does this package's hash usually change so quickly? If so, it might be a situation similar to `Nightly` packages:

- https://github.com/microsoft/winget-pkgs/issues/163098

**Comment by KarbitsCode** [comment]
> Does this package's hash usually change so quickly?

Usually it's not. But this case the url apparently served a different file on each step.
From the pipeline, on Installer Scan step the url served this version of the app (with hash b6a828...).
But in the Installer Validation, it's served the previous version of this app, witch is [2.7.11](https://github.com/microsoft/winget-pkgs/pull/184309) (with hash 6fbe6d...)
Maybe this is because of their cdn is not synced yet, thus causing serving different files.

**Comment by KarbitsCode** [comment]
Since there's not much that I can do in this hash situation, I'm closing this PR.

**Pull request closed without merging**
