### PR TITLE
New package: Icedrive.Icedrive version 2.29.9

### LINKED ISSUE #33704: [Package Request]: KDE.Calligra.Nightly
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: KDE e.V.
Publisher Url: http://kde.org
Package Name: KDE.Calligra.Nightly
Description: http://calligra.org
Package Version: master-1347
Installer URL: https://binary-factory.kde.org/job/Calligra_Nightly_win64/lastSuccessfulBuild/artifact/calligra-master-1347-windows-msvc2019_64-cl.exe

Current Package Identifier (for new versions): master-1347

### LINKED ISSUE #33705: [Package Request]: KDE.Alkemia.Nightly
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: KDE e.V.
Publisher Url: http://kde.org
Package Name: KDE.Alkemia.Nightly
Description: 
Package Version: master-426
Installer URL: https://binary-factory.kde.org/view/Windows%2064-bit/job/Alkimia_Nightly_win64/lastSuccessfulBuild/artifact/libalkimia-master-426-windows-msvc2019_64-cl.exe

Current Package Identifier (for new versions): master-426

### LINKED ISSUE #33719: [Package Request]: KDE.Cantor.Release
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: KDE e.V.
Publisher Url: http://kde.org
Package Name: KDE.Cantor.Release
Description: http://apps.kde.org/cantor
Package Version: master-338
Installer URL: http://binary-factory.kde.org/view/Windows%2064-bit/job/Cantor_Release_win64/lastSuccessfulBuild/artifact/cantor-21.08.2-338-windows-msvc2019_64-cl.exe

Current Package Identifier (for new versions): master-338

### LINKED ISSUE #33722: [Package Request]: KDE.Elisa.Release
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: KDE e.V.
Publisher Url: http://kde.org
Package Name: KDE.Elisa.Release
Description: http://apps.kde.org/elisa
Package Version: master-936
Installer URL: http://binary-factory.kde.org/view/Windows%2064-bit/job/Elisa_Release_win64/lastSuccessfulBuild/artifact/elisa-21.12.0-976-windows-msvc2019_64-cl-sideload.appx

Current Package Identifier (for new versions): master-936

### LINKED ISSUE #33726: [Package Request]: KDE.Filelight.Release
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: KDE e.V.
Publisher Url: http://kde.org
Package Name: KDE.Filelight.Nightly
Description: http://apps.kde.org/filelight
Package Version: master-785
Installer URL: http://binary-factory.kde.org/view/Windows%2064-bit/job/Filelight_Release_win64/lastSuccessfulBuild/artifact/filelight-21.08.2-785-windows-msvc2019_64-cl-sideload.appx

Current Package Identifier (for new versions): master-785

### LINKED ISSUE #38852: [Package Request]: Icedrive
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Icedrive
Publisher Url: https://icedrive.net/plans
Package Name: Icedrive
Description: Cloud Storage for Windows
Package Version: 2.29
Installer URL: https://icedrive.net/downloads/win/Icedrive_Installer-2.29.9.exe

Current Package Identifier (for new versions): 2.29

### LINKED ISSUE #38932: [Package Request]: KDE.KDevelop.Release
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: KDE e.V.
Publisher Url: http://kde.org
Package Name: KDE.KDevelop.Release
Description: http://apps.kde.org/kdevelop
Package Version: master-1419
Installer URL: http://binary-factory.kde.org/view/Windows%2064-bit/job/KDevelop_Release_win64/lastSuccessfulBuild/artifact/kdevelop-5.6.2-1419-windows-msvc2019_64-cl.exe

Current Package Identifier (for new versions): master-1419

### LINKED ISSUE #38933: [Package Request]: KDE.KDevelop.Stable
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: KDE e.V.
Publisher Url: http://kde.org
Package Name: KDE.KDevelop.Stable
Description: http://apps.kde.org/kdevelop
Package Version: master-678
Installer URL: http://binary-factory.kde.org/view/Windows%2064-bit/job/KDevelop_Stable_win64/lastSuccessfulBuild/artifact/kdevelop-5.5-678-windows-msvc2019_64-cl.exe

Current Package Identifier (for new versions): master-678

### LINKED ISSUE #38936: [Package Request]: KDE.Kate.Release
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: KDE e.V.
Publisher Url: http://kde.org
Package Name: KDE.Kate.Release
Description: http://apps.kde.org/kate
Package Version: master-1514
Installer URL: http://binary-factory.kde.org/view/Windows%2064-bit/job/Kate_Release_win64/lastSuccessfulBuild/artifact/kate-21.12.0-1514-windows-msvc2019_64-cl-sideload.appx

Current Package Identifier (for new versions): master-1514

### LINKED ISSUE #38967: [Package Request]: KDE.KDiff3.Stable
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not a standalone or portable executable or a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: KDE e.V.
Publisher Url: http://kde.org
Package Name: KDE.KDiff3.Stable
Description: http://apps.kde.org/kdiff3
Package Version: master-560
Installer URL: http://binary-factory.kde.org/view/Windows%2064-bit/job/KDiff3_Stable_win64/lastSuccessfulBuild/artifact/kdiff3-1.9-560-windows-msvc2019_64-cl-sideload.appx

Current Package Identifier (for new versions): master-560

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

* Resolves #38852

Closing these issues in favor of #39190 
-----
* Closes https://github.com/microsoft/winget-pkgs/issues/33705
* Closes https://github.com/microsoft/winget-pkgs/issues/33704
* Closes https://github.com/microsoft/winget-pkgs/issues/38967
* Closes https://github.com/microsoft/winget-pkgs/issues/38933
* Closes https://github.com/microsoft/winget-pkgs/issues/38993
* Closes https://github.com/microsoft/winget-pkgs/issues/38991
* Closes https://github.com/microsoft/winget-pkgs/issues/38980
* Closes https://github.com/microsoft/winget-pkgs/issues/38969
* Closes https://github.com/microsoft/winget-pkgs/issues/38936
* Closes https://github.com/microsoft/winget-pkgs/issues/38932
* Closes https://github.com/microsoft/winget-pkgs/issues/33726
* Closes https://github.com/microsoft/winget-pkgs/issues/33722
* Closes https://github.com/microsoft/winget-pkgs/issues/33719

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/39191)

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]

**Comment by Trenly** [comment]
@denelon - I realize it's holidays for you guys, but is there someone available who can merge this?

**Comment by OfficialEsco** [comment]
@arjun-msft you seem to be alive at this hour, i think we broke stuff 👀

**Comment by Trenly** [comment]
> @arjun-msft you seem to be alive at this hour, i think we broke stuff 👀

I think that the commits merged in, just that the sheer number of issues to be closed caused the bot to not actually close anything. I think all the issues mentioned above can be closed, and then this PR can be marked as closed

**Comment by vedantmgoyal2009** [comment]
Adding a dummy commit then force-pushing the branch should fix the issue, I guess.

**Comment by Trenly** [comment]
> Adding a dummy commit then force-pushing the branch should fix the issue, I guess.

It shouldnt because it should still recognize that the previous commits were already merged in, and return the same PR validation error. I don’t want to break anything further, so I’ll let MSFT fix it first

**Comment by ItzLevvie2** [comment]
Ran into the same issue; looks like @msftbot merges in the commit instead of merging the PR.

https://github.com/microsoft/winget-pkgs/pull/39239#issuecomment-1002612815

**Comment by arjun-msft** [comment]
@OfficialEsco did this make it in? I see it closed but I don't think it got merged but I see it in the repo.  Let me know if something needs to be done!

**Comment by OfficialEsco** [comment]
It got merged 3 times actually, however it never said it merged it or closed the PR or any of the issues
https://github.com/microsoft/winget-pkgs/commit/c20ad0879e75d712193b7bfaab511a30ebe614d7
https://github.com/microsoft/winget-pkgs/commit/76b2877723e750a9432444eca8fe2333eae2e208
https://github.com/microsoft/winget-pkgs/commit/353a337855436a330c3a425a656408d67516aff3
But i think everything is fine and dandy + we found a workaround for the PRs
Would you mind closing https://github.com/microsoft/winget-pkgs/issues/38852 since its resolved?

**Pull request closed without merging**
