### PR TITLE
New package: albertony.npiperelay Version 1.6.2

### PR DESCRIPTION
**Pull request by blaubaer**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161471)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\albertony.npiperelay__DefaultSource\npiperelay.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\npiperelay.exe returned exit code: 1
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Packages\albertony.npiperelay__DefaultSource\npiperelay.exe returned exit code: 1
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\npiperelay.exe returned exit code: 1

(Automated response - build 886.)

**Comment by blaubaer** [comment]
@stephengillie the command `C:\Users\<username>\AppData\Local\Microsoft\WinGet\Links\npiperelay.EXE` without any argument is simply printing the help screen and as this is not suffient, it exit with exit code `1`:
```
npiperelay v1.6.2
  commit 98b61e5808f48ca603a2e99a14a5026a8ecf3497
  build date 2024-04-05T08:08:55Z
  built by goreleaser
  built with go1.22.2

usage:
  -bg
        hide console window and run in background
  -ei
        terminate on EOF reading from stdin, even if there is more data to write
  -ep
        terminate on EOF reading from the pipe, even if there is more data to write
  -p    poll until the the named pipe exists and is not busy
  -s    send a 0-byte message to the pipe after EOF on stdin
  -v    verbose output on stderr
```

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Verify:
image

> @stephengillie the command C:\Users\<username>\AppData\Local\Microsoft\WinGet\Links\npiperelay.EXE without any argument is simply printing the help screen and as this is not suffient, it exit with exit code 1:

Yes, this is something of a known issue with our pipelines, which were built with Windows Forms in mind. Sorry for the delay verifying this new application.

**Pull request merged**
