### PR TITLE
New version: blacktop.ipsw 3.1.371

### PR DESCRIPTION
**Pull request by blacktop**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/113072&drop=dogfoodAlpha

### CODE REVIEW

**Comment by blacktop** [comment]
I ran this exact manifest in a Github Actions windows-latest runner and it worked just fine, so I believe this is an issue on your side?

**Comment by blacktop** [comment]
https://github.com/blacktop/ipsw/actions/workflows/winget.yml

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2023-07-24 09:31:14.387 [FAIL] Installer failed security check. Url: https://github.com/blacktop/ipsw/releases/download/v3.1.371/ipsw_3.1.371_windows_i386.zip Result: 0x80004005 

We can retry the scan tomorrow.

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @blacktop,

This PR is ready to merge - if you click the "Ready for review" button, then it should merge automatically.

**Comment by denelon** [comment]
@blacktop it looks like all the PRs are created as "draft". I see @stephengillie has commented on several of them regarding marking them "Ready for review". I'm not sure what automation is doing to create them as draft as opposed to a PR that's "ready for review".

**Comment by denelon** [comment]
@blacktop I'm seeing this in the Go releaser YAML file:
https://github.com/blacktop/ipsw/blob/a80a84bfd09c578bd60500d296dc088231606876/.goreleaser.yml#L771C8-L771C20

**Comment by blacktop** [comment]
> @blacktop I'm seeing this in the Go releaser YAML file: https://github.com/blacktop/ipsw/blob/a80a84bfd09c578bd60500d296dc088231606876/.goreleaser.yml#L771C8-L771C20

thank you! I just added that because the creator has that set.  I'm changing it to `false` now

**Comment by denelon** [comment]
@blacktop what do you want to do with the other draft Pull Requests? We can either close them or you can mark them as ready for review so they can be merged. It looks like there are a large number of them still open.

https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+author%3Ablacktop

**Comment by blacktop** [comment]
> @blacktop what do you want to do with the other draft Pull Requests? We can either close them or you can mark them as ready for review so they can be merged. It looks like there are a large number of them still open.
> 
> 
> 
> https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Atrue+author%3Ablacktop
> 
> 
> 
> 

We can close/delete the branches. Is it easy for you to close them all at once?

**Pull request closed without merging**
