### PR TITLE
New version: Genymobile.scrcpy version 3.0

### PR DESCRIPTION
**Pull request by ponces**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/196164)

### CODE REVIEW

**Comment by ponces** [comment]
> **Found duplicate pull request(s)**
> 
> * **Manifest Path: manifests\g\Genymobile\scrcpy\3.0**
>   
>   * [New version: Genymobile.scrcpy version 3.0 #196097](https://github.com/microsoft/winget-pkgs/pull/196097)
>   * [New version: Genymobile.scrcpy version 3.0 #196099](https://github.com/microsoft/winget-pkgs/pull/196099)

Please, disregard this as the other pull requests are not bumping the manifest version which enables the use of the `ArchiveBinariesDependOnPath` property which fixes a [known DLL missing issue](https://github.com/microsoft/winget-cli/issues/2711).

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 899.)

**Comment by Ayx03** [comment]
Ok I'll close those as you've bumped the manifest version

**Comment by ponces** [comment]
After merging this, I can push a manifest for each of those new versions (3.0.1 and 3.0.2 right?).

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
