### PR TITLE
New package: FireDaemon.FireDaemonLozenge version 2.0.0.0

### LINKED ISSUE #154496: [Package Request]: FireDaemon Lozenge
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.firedaemon.com/download-firedaemon-lozenge
Publisher: FireDaemon Technologies Limited
Package Name: FireDaemon Lozenge
Description: A sweet, free and soothing file hash calculator.
Package Version: 2.0.0
Installer URL: https://download.firedaemon.com/FireDaemon-Lozenge/2.0.0/FireDaemon-Lozenge-x64-2.0.0.0.msixbundle

### PR DESCRIPTION
**Pull request by schembriaiden**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

Resolves: https://github.com/microsoft/winget-pkgs/issues/154496

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/154553)

### CODE REVIEW

**Comment by vikingnope** [comment]
@stephengillie, same error, seems to be all msix files:

`The system cannot find the file specified`

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-05-21 07:32:13.181 [CORE] Deployment operation #0: Windows cannot install package FireDaemon.Lozenge_2.0.0.0_x64__tg36hcemt43dy because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.30704.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00" currently installed are: {Microsoft.VCLibs.140.00_14.0.27323.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.29231.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.30035.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.30035.0_x86__8wekyb3d8bbwe}
> 2024-05-21 07:32:13.181 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!00007FFB6AFB3F75: (caller: 00007FFB6AF0A720) Exception(1) tid(1a64) 80073CF3 Package failed updates, dependency or conflict validation.
> 2024-05-21 07:32:13.289 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFB6AFB2D2F: (caller: 00007FFB6AFB432C) Exception(2) tid(1a64) 80073CF1 Package was not found.
> 2024-05-21 07:32:13.289 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(126)\WindowsPackageManager.dll!00007FFB6B128931: (caller: 00007FFB6AFB5853) LogHr(1) tid(1a64) 80073CF1 Package was not found.
>     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFB6AFB2D2F: (caller: 00007FFB6AFB432C) Exception(2) tid(1a64) 80073CF1 Package was not found.
> 2024-05-21 07:32:13.293 [CLI ] MSIX installer failed: 2147958003

(Automated response - build 881.)

**Comment by vikingnope** [comment]
Thing is we don't have this package, and I do not know how we can get it. We were supposed to get some feedback on this, but I don't think we ever got it: https://github.com/microsoft/winget-pkgs/pull/150504#issuecomment-2083525083

**Comment by stephengillie** [comment]
Hi @vikingnope,

This application might operate in an unsual way which could be befuddling our pipeline automation. It scans the system for every new EXE, then runs each, looking for one to give a non-zero exit code. 

Manual Validation ended with: 
image

The application doesn't launch when run directly. But from the Start menu: 

image

Verify: 
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
