### PR TITLE
Add Total Commander

### LINKED ISSUE #91: Range GET requests are not supported by the copy source
It looks like we have a problem with Range GET requests. #85

### PR DESCRIPTION
**Pull request by clguiman**
Add the Total Commander file manager

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/306)

### CODE REVIEW

**Comment by clguimanMSFT** [comment]
I can access the link on my computer, I assume the bot can't access it due to issue no. 3. I don't know why it's detected as malware. Total Commander is a widely used tool.

**Comment by sundhaug92** [comment]
Underlying error is:

>  Range GET requests are not supported by the copy source.

[Source](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=80474&view=logs&j=c8020aa5-4aab-5881-691f-21986e02afd0&t=bade86d6-d2be-5ddd-c1b9-7d8db9c4a60d)

**Comment by clguimanMSFT** [comment]
> Underlying error is:
> 
> > Range GET requests are not supported by the copy source.
> 
> [Source](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=80474&view=logs&j=c8020aa5-4aab-5881-691f-21986e02afd0&t=bade86d6-d2be-5ddd-c1b9-7d8db9c4a60d)

Is there any plan to support non-range requests? If not, I'll abandon the PR and create a new one after I contact the tool owner.

**Comment by sundhaug92** [comment]
I'd suggest just holding on this PR for response to 91

**Comment by lutzroeder** [comment]
@clguimanMSFT is `https://totalcommander.ch/win/tcmd951x32_64.exe` the right installer for `x64` or should `https://totalcommander.ch/win/fixed/tcmd951x64.exe` be used instead?

Maybe send an Email to [support@ghisler.com](mailto:support@ghisler.com) for awareness of the issue?

**Comment by chrisgch** [comment]
Author here:
This is the combined 32+64-bit version:
https://totalcommander.ch/win/tcmd951x32_64.exe
This is the 64-bit only version:
https://totalcommander.ch/win/tcmd951x64.exe
same file:
https://totalcommander.ch/win/fixed/tcmd951x64.exe

Range GET requests are disabled via max_ranges=0 in Nginx, they had a severe impact on the stability of the server, some download managers opened dozens of parallel connections although the file itself is small.

**Comment by dotMorten** [comment]
Would it be possible to have arguments for which language to install/not install, where ini-files are located etc?

**Comment by chrisgch** [comment]
Hi!

You wrote:
> Would it be possible to have arguments for which language to install/not install, where ini-files are located etc?

Currently you can only choose which language to install, and whether to install
just that language (plus English) or all languages. See the available parameters
here:
https://www.ghisler.ch/wiki/index.php?title=How_to_make_installation_fully_automatic%3F

You cannot choose the install location or ini location - this doesn't matter for
updates anyway, because they will be preserved.

Best regards

Christian Ghisler

**Comment by denelon** [comment]
@chrisgch thanks for shedding some light on the Nginx range request issue. This might help with how we implement a solution for #91

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
