### PR TITLE
Fix .NET display strings

### PR DESCRIPTION
**Pull request by terrajobst**
I've changed some of the strings to match the official product names.

@MichaelSimons @richlander:

Do we want to change the package ids? I understand that this is a breaking change but I guess now is the time to do that if we aren't happy with them. These are the current ones:

Id                       | Name
-------------------------|----------------
Microsoft.dotnet         | .NET Core
Microsoft.dotNetFramework| .NET Framework

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/537)

### CODE REVIEW

**Comment by richlander** [comment]
LGTM

**Review by MichaelSimons — DISMISSED** [review]
LGTM

**Comment by MichaelSimons** [comment]
@terrajobst, In order to get this PR green, I think you need to split is apart.  The repo readme states that only one manifest can be contained in a PR.

**Comment by MichaelSimons** [comment]
> Do we want to change the package ids? I understand that this is a breaking change but I guess now is the time to do that if we aren't happy with them.

I don't care for the inconsistent casing of dotnet vs dotNet

I chose Microsoft.dotnet vs Microsoft.dotnetCore so that it will be long term applicable when 5.0 is released and we drop “core” from the product name.  I thought it would be acceptable to change the name once .NET 5.0 is released from .NET Core to .NET.  An alternative option would be to have a "core" package for <= 3.1 and a non-core package for >= 5.0.  

Outside of the casing, I have no objections to `Microsoft.dotNetFramework`.

**Comment by terrajobst** [comment]
> @terrajobst, In order to get this PR green, I think you need to split is apart. The repo readme states that only one manifest can be contained in a PR.

Oopsy... probably should have read that. Submitted #551 for .NET Framework and kept this to .NET Core.

**Comment by terrajobst** [comment]
> I chose Microsoft.dotnet vs Microsoft.dotnetCore so that it will be long term applicable when 5.0 is released and we drop “core” from the product name. I thought it would be acceptable to change the name once .NET 5.0 is released from .NET Core to .NET. An alternative option would be to have a "core" package for <= 3.1 and a non-core package for >= 5.0.

I figured and I'm OK with that reasoning. I just raised it because it seems we should make this decision deliberately.

> Outside of the casing, I have no objections to `Microsoft.dotNetFramework`.

Should I submit a PR to change the casing? I'm afraid this will break stuff.

**Comment by MichaelSimons** [comment]
>Should I submit a PR to change the casing? I'm afraid this will break stuff.
Yes please, I think now is the time to change it.

**Review by MichaelSimons — APPROVED** [review]

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
