### PR TITLE
Add manifest file for LibreOffice v6.4.6.1 x64

### PR DESCRIPTION
**Pull request by mehtanisarg369**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2619)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
image

**Comment by mehtanisarg369** [comment]
Hi KevinLaMS,
Thank you for your feedback. I'm unable to replicate the error on my end.

LibreOffice v6 4 6 1 x64 Install Successful

**Comment by mehtanisarg369** [comment]
Hi @KevinLaMS and @denelon ,

Could you please update me regarding the status of this pull request?

I've validated the manifest file and installed LibreOffice from the manifest file multiple times without encountering any errors whatsoever. If it helps, I've also added manifest files for earlier versions of LibreOffice (namely LibreOffice v6.4.5 and LibreOffice PreRelease v7.0.0.2) without any errors whatsoever; and they were merged without further troubles.

Please do let me know if I need to make any further changes to the manifest file, in case required. I'll modify the changes ASAP and issue a PR as well.

Regards,
Nisarg.

**Comment by KevinLaMS** [comment]
I will look again.  I wonder if the issue  is that I am not an admin in the command window

**Comment by KevinLaMS** [comment]
Yes, that appears to be the issue.  This succeeds if you run as admin but fails if you are a non-admin.  Normally i would continue to block this app.  I will mark it as blocking, but let it through.  But we will need to update the manifest when we add support to dictate requirements of requiring admin.

**Review by ghost — APPROVED** [review]
Validation has completed

**Comment by mehtanisarg369** [comment]
Hi @KevinLaMS ,

Thank you for the update -- I did not realize that I was supposed to test the manifest file as a non-admin user as well. I've been using 'winget' as an admin user exclusively. Thank you for bringing this to my attention; I'll take test the manifest files as non-admin user as well. 

I'll definitely be ready to edit the manifest file once the support to dictate requirements of requiring admin has been added to winget.

**Pull request merged**
