### PR TITLE
Update: AdoptOpenJDK.OpenJDK.8 version 8.0.252

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/42635)

### CODE REVIEW

**Comment by Trenly** [comment]
Leaving this unresolved for #42616 

Intentionally not re-running pipelines

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Please close and re-open the PR to re-run the pipelines.

**Comment by Trenly** [comment]
https://github.com/microsoft/winget-pkgs/pull/42826#issuecomment-1023363375

**Comment by Trenly** [comment]
@denelon -
I'm almost certain that this PR does contain Yaml files for a manifest and that they are in the correct path
image

**Comment by denelon** [comment]
I'm inclined to believe you 😊
I'll ask the team to look deeper into this one.

**Comment by Trenly** [comment]
@denelon @zachcarp - I was going to try a rebase to fix the issue, and I think I found the cause. Apologies for the confusion. 

Rebasing gave me a noop, and looking further the files were also updated in #42637. Not sure how I accidentally opened two of them.

Closing as a duplicate.

**Pull request closed without merging**
