### PR TITLE
Arturia.MIDIControlCenter version 1.14.1

### PR DESCRIPTION
**Pull request by dongle**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/89316)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @dongle,

Validation is catching the Arturia USB MIDI driver setup. This launches after the MIDI Control Center install completes. 
image

Is there an installer switch that would make this driver also silent? If not, the driver could possibly be added as a separate package, and then added as a dependency on this package.

**Comment by dongle** [comment]
> Hi @dongle,
> 
> Validation is catching the Arturia USB MIDI driver setup. This launches after the MIDI Control Center install completes. image
> 
> Is there an installer switch that would make this driver also silent? If not, the driver could possibly be added as a separate package, and then added as a dependency in this package's manifest.

Hm, I see -- makes sense. Just to ensure I'm following, the gist is that the installer closes, then launches the driver setup, which would goof scripting winget since winget would return, passing control to the subsequent instructions in the script?

For future reference, is there a ready-made way to check for this locally so I can avoid repeating this?

As far as I know, there's no separate download for the Arturia USB MIDI drivers, and there's no documented switch to pass to the installer. I'll admit that I'm mostly a linux user (Windows for music & games) so I'm not well-informed about ways to inspect windows installers for potential options -- is there a resource I could read or a term I should search to get up to speed?

Thanks for your help!

**Comment by stephengillie** [comment]
> Hm, I see -- makes sense. Just to ensure I'm following, the gist is that the installer closes, then launches the driver setup, which would goof scripting winget since winget would return, passing control to the subsequent instructions in the script?

Validation would wait for the driver installer, were it unattended. It times out, I believe, instead of providing an exit code, signaling a user prompt and not-quite-unattended installer. 

> For future reference, is there a ready-made way to check for this locally so I can avoid repeating this?

Validation happens inside a fresh install of Windows, which uncovers dependencies like this in many other PRs. For testing, we also use Windows Sandboxes which are similarly barren.

> As far as I know, there's no separate download for the Arturia USB MIDI drivers, and there's no documented switch to pass to the installer. I'll admit that I'm mostly a linux user (Windows for music & games) so I'm not well-informed about ways to inspect windows installers for potential options -- is there a resource I could read or a term I should search to get up to speed?

There are a few major installer flavors, including Nullsoft, Inno, Burn, and MSI. Winget has the default silent switches for many of these built-in. Independent installer and nonstandard switches can also be declared directly in the manifest. Most installers can be queried with switches including "/?" and "--help". It can be a guessing game to find what works, but between command-line trial-and-error and some internet searches, the necessary switches can often be unearthed.

A problem with the present situation is that Winget isn't launching the driver installer - the program installer does. So Winget can't directly set switches for the driver installer. Unfortunately, packages must have a completely unattended mode to be included in Winget. 

> Thanks for your help!

Anytime!

**Comment by Trenly** [comment]
@msftbot interactive-only due to driver prompt

**Review by ItzLevvie — CHANGES_REQUESTED** [review]

**Comment by stephengillie** [comment]
Unfortunately, installers must have a fully unattended mode to be included in the Winget manifest.

**Pull request closed without merging**
