### PR TITLE
Improve Tencent.QQ 9.7.1.28940 URLs

### PR DESCRIPTION
**Pull request by StarsbySea**
Related to [[New Feature]: Replace dldir1.qq.com with dldir1v6.qq.com for Improved IPv6 Support #116525](https://github.com/microsoft/winget-pkgs/issues/116525)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/117020)

### CODE REVIEW

**Comment by StarsbySea** [comment]
Why?

**Comment by stephengillie** [comment]
> Installer Verification Analysis Context Information: 
Installer https://dldir1v6.qq.com/qqfile/qq/PCQQ9.7.1/QQ9.7.1.28940.exe
Scan request id: '94526533-91e7-473c-8858-1aa808d8bbb7'
Error information: BlockingDetectionFound

The IPv6 host is blocking our data center, the same as in https://github.com/microsoft/winget-pkgs/pull/117018.

**Comment by StarsbySea** [comment]
Please try again?

**Comment by Trenly** [comment]
Stale PR; Please update or close
[Policy] Needs-Author-Feedback

**Pull request closed without merging**
