### PR TITLE
New version: ElectronicArts.EADesktop version 12.0.116.4974

### PR DESCRIPTION
**Pull request by OfficialEsco**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Resolves #24487

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/24687)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Comment by OfficialEsco** [comment]
Uuuu cool new power

**Comment by OfficialEsco** [comment]
Just checked, it is indeed not unattended... Ill dig up the EULA switch

**Comment by palenshus** [comment]
> Just checked, it is indeed not unattended... Ill dig up the EULA switch

Nice, thanks!

**Comment by OfficialEsco** [comment]
It seems like ACCEPT=YES does not work anymore for some reason..
Gonna bench the PR until next version

**Comment by OfficialEsco** [comment]
Somehow the bot PR passed 🤔

**Pull request closed without merging**
