### PR TITLE
New package: TriliumNext.Notes version 0.90.12

### PR DESCRIPTION
**Pull request by maphew**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/198907)

### CODE REVIEW

**Comment by stephengillie** [comment]
Verify:
image
I couldn't find how to have the application display the version number.
image

**Review by stephengillie — APPROVED** [review]

**Comment by maphew** [comment]
How long does it take for the index to updated? I don't see the package yet (2 hrs after https://github.com/microsoft/winget-pkgs/pull/198907#issuecomment-2546291603)

```
D:\# winget source update
Updating all sources...
Updating source: msstore...
Done
Updating source: winget...
                                  0%  
::progress bar completed but does not show in copied text
Done

D:\# winget search trilium
Failed when searching source; results will not be included: msstore
No package found matching input criteria.

D:\# winget show TriliumNext.Notes
Failed when searching source; results will not be included: msstore
No package found matching input criteria.
```

Test it works for a different package:
```
D:\# winget show vscode
Failed when searching source; results will not be included: msstore
Found Microsoft Visual Studio Code [Microsoft.VisualStudioCode]
Version: 1.95.3
Publisher: Microsoft Corporation
Publisher Url: https://www.microsoft.com/
Moniker: vscode
Description: Microsoft Visual Studio Code is a code editor redefined and optimized for building and debugging modern web and cloud applications. Microsoft Visual Studio Code is free and available on your favorite platform - Linux, macOS, and Windows.
Homepage: https://code.visualstudio.com
License: Microsoft Software License
License Url: https://code.visualstudio.com/license
Privacy Url: https://privacy.microsoft.com/
Tags:
  developer-tools
  editor
Installer:
  Installer Type: inno
  Installer Url: https://vscode.download.prss.microsoft.com/dbazure/download/stable/f1a4fb101478ce6ec82fe9627c43efbf9e98c813/VSCodeUserSetup-x64-1.95.3.exe
  Installer SHA256: 7ce997d7a80ff838c2b7312be6e26917a8b66a67c633ee0b3317b1ae70010077
  Offline Distribution Supported: true
  ```

**Comment by maphew** [comment]
my source settings:
```
D:\# winget source list
Name    Argument                                      Explicit
--------------------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0 false
winget  https://cdn.winget.microsoft.com/cache        false
```

**Comment by maphew** [comment]
it's there now :) 
so the answer is sometime between 2 and 7 hours

**Pull request merged**
