### PR TITLE
New version: Rojo.Rojo version 7.4.1

### PR DESCRIPTION
**Pull request by HeitorAugustoLN**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?
---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141328)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @HeitorAugustoLN,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 844.)

**Comment by HeitorAugustoLN** [comment]
> Hi @HeitorAugustoLN,
> 
> The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.
> 
> (Automated response - build 844.)

Yeah, it is a false positive, it always happens on newer releases of this software, but my defender didn't alert me about anything this time, but soon it will pass

**Comment by HeitorAugustoLN** [comment]
@stephengillie I think that the false positive is gone, can you rescan it?

**Comment by stephengillie** [comment]
> @stephengillie I think that the false positive is gone, can you rescan it?

Sorry for the delay - was also waiting on some work on the bot.

**Comment by HeitorAugustoLN** [comment]
> Hello @HeitorAugustoLN,
> 
> The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.
> 
> Template: msftbot/validationError/installation/general

It is installing correctly, no need to repair.

**Comment by HeitorAugustoLN** [comment]
> > @stephengillie I think that the false positive is gone, can you rescan it?
> 
> Sorry for the delay - was also waiting on some work on the bot.

No problem.

**Comment by stephengillie** [comment]
Hi @HeitorAugustoLN,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow. 

(Automated response - build 857.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-01 09:36:30.010 [FAIL] Installer failed security check. Url: https://github.com/rojo-rbx/rojo/releases/download/v7.4.1/rojo-7.4.1-windows-x86_64.zip Result: 0x80004005

(Automated response - build 857.)

**Comment by HeitorAugustoLN** [comment]
> Hi @HeitorAugustoLN,
> 
> The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.
> 
> (Automated response - build 857.)

Fine.

**Comment by stephengillie** [comment]
Hi @HeitorAugustoLN,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 861.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-04 07:51:11.689 [FAIL] Installer failed security check. Url: https://github.com/rojo-rbx/rojo/releases/download/v7.4.1/rojo-7.4.1-windows-x86_64.zip Result: 0x80004005

(Automated response - build 861.)

**Comment by HeitorAugustoLN** [comment]
Finally 🙌 I think the executable error is probably waived

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Rojo.Rojo__DefaultSource\rojo.exe returned exit code: 2
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\rojo.exe returned exit code: 2

(Automated response - build 873.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
