### PR TITLE
Moniker/ProductCode: BellSoft.LibericaJDK11Full version 11.0.9.11

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]

**Review by quhxl — APPROVED** [review]

**Review by quhxl — APPROVED** [review]

**Review by OfficialEsco — APPROVED** [review]
I really wonder how the bot can be this drunk... Try again in a hour on the PR's that are stuck, as i've noticed its between 1 and 2 hours where it goes straight the merge

**Comment by quhxl** [comment]
> 
> 
> I really wonder how the bot can be this drunk... Try again in a hour on the PR's that are stuck, as i've noticed its between 1 and 2 hours where it goes straight the merge

I wonder anyway why the bot is influenced by my normal "user" reviews.

**Comment by OfficialEsco** [comment]
I think the bot looks at the PR and realizes it got Moderator-Approved, but we have also had a PR with Moderator-Approved open for days and nothing happening when Approving so i think its just living it own life…

And what is it even doing after posting Validation Completed? Why does it need to «timeout»(?) before someone can reapprove and go straight to merge?

cc @denelon we need answers on why this is still a thing

**Comment by denelon** [comment]
@OfficialEsco We had to do some additional "back-end" work to try and adapt to some of the limitations of the bot. I'll have someone take a look at this one to see what is going on.

**Comment by denelon** [comment]
@OfficialEsco the bot runs on a timer. It's shared infrastructure. I'm not sure why it doesn't catch things at times. We contacted the team working on it and they said they have been having some issues with GitHub. There are other behaviors that run on triggers for events related to Issues and PRs. I suspect that on occasion when an Issue/PR has a certain type of event, and the bot captures it, the bot runs other behaviors. I'm not sure if it's coded that way or just a byproduct of another behavior yet.

**Pull request merged**
