### PR TITLE
added the standalone warframe installer

### PR DESCRIPTION
**Pull request by bearmannl**
Added the standalone Warframe Launcher, by Digital Extremes.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14470)

### CODE REVIEW

**Comment by bearmannl** [comment]
Opened a ticket with Digital Extremes to inquire about the URL validation. Maybe GitHub agents are blocked.

**Comment by denelon** [comment]
First Pass:


-----------------------------------------------------
Manifest: manifests\d\DigitalExtremes\Warframe\2021.05.25.08.29
-----------------------------------------------------
URI: https://www.digitalextremes.com/, Validation result: Failed, Http status code: Forbidden 
URI: https://www.warframe.com/zendesk, Validation result: Failed, Http status code: Forbidden 
URI: https://www.warframe.com/privacy, Validation result: Failed, Http status code: Forbidden 
URI: https://www.warframe.com/, Validation result: Failed, Http status code: Forbidden 
URI: https://www.warframe.com/eula, Validation result: Failed, Http status code: Forbidden 
URI: https://www.warframe.com/, Validation result: Failed, Http status code: Forbidden 
URI: https://content.warframe.com/dl/Warframe.msi, Validation result: Passed

**Comment by bearmannl** [comment]
Closing this PR since I haven't heard back from Digital Extremes. Can't move forward without their help.

**Comment by bearmannl** [comment]
Trying once more, maybe it was a fluke.

**Pull request closed without merging**
