### PR TITLE
New package: pb2modlauncher.PB2AdvancedLauncher version 0.1.0

### LINKED ISSUE #109536: [Package Request]: Plazma Burst 2
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.plazmaburst2.com/?s=2&a=#
Publisher: Eric Gurt
Package Name: Plazma Burst 2
Description: 2D Sidescroller shooter game with story
Package Version: 1.41
Installer URL:

Either [this](https://www.plazmaburst2.com/pb2/Plazma%20Burst%202.zip) or [this](https://www.plazmaburst2.com/pb2/Plazma%20Burst%202%20vbs.zip)

### PR DESCRIPTION
**Pull request by Dragon1573**
## Description

- Resolve #109536

## Checks

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/130041)

### CODE REVIEW

**Comment by Dragon1573** [comment]
Manually validated all URLs mentioned in https://github.com/microsoft/winget-pkgs/pull/130041#issuecomment-1850236662, and all of them are valid and response HTTP 200 when visiting via Microsoft Edge Dev and `curl`.

```text
21:15:25 ~/Documents 3ms $ curl -I "https://www.plazmaburst2.com/?s=3&a="
HTTP/1.1 200 Connection established

HTTP/2 200
date: Mon, 11 Dec 2023 16:46:56 GMT
content-type: text/html; charset=UTF-8
vary: User-Agent
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=pxPxLFas%2Bl802Slnl1HRyqVQa5r%2Fh28u6%2FFhlXKiIM31CGVz5qIcimGHpzDXR0OBQej3a8Fv1w6EbRZTAZAPR01iiGfWdj38mSUg9sleb9qDvh%2FqxFRqvneUgxCylKTvC0tikLwdOw%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 833f34de8ea90429-HKG
alt-svc: h3=":443"; ma=86400

21:15:40 ~/Documents 892ms $ curl -I "https://www.plazmaburst2.com/?a=&s=17"
HTTP/1.1 200 Connection established

HTTP/2 200
date: Mon, 11 Dec 2023 16:55:49 GMT
content-type: text/html; charset=UTF-8
vary: User-Agent
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=pljL4HiwIEKXXmMfyMRVpU1fQ0gFD4HMs%2BG45MCcJRFEDxa7VpMlxzeKjG%2Bit0gFy0uo17xe%2Fu1RvAOj3CjI7veC8pgG7bdrxz9DvvYRTS75DDlwKoGvVdUd5gFaPyaXm2iiSnuphw%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 833f41e67a8c04fd-HKG
alt-svc: h3=":443"; ma=86400

21:25:18 ~/Documents 1.22s $ curl -I "https://www.plazmaburst2.com/?s=2&a="
HTTP/1.1 200 Connection established

HTTP/2 200
date: Mon, 11 Dec 2023 16:56:15 GMT
content-type: text/html; charset=UTF-8
vary: User-Agent
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=XMu0krjCoEfU1FAWYsR%2Fks%2BuONHESQypfyILw4mwyXkjD54KrloCWKsKcdRvuG4Aljj4n2KDPof8Jd4tgjZXzgY7zTaIV2J%2FfE8ScefJ4DtGDXcUwSYs3LuvuNRsiKrmrAFy3RCoQg%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 833f4285d8181fa9-HKG
alt-svc: h3=":443"; ma=86400

21:25:46 ~/Documents 775ms $ curl -I "https://www.plazmaburst2.com/pb2/Plazma%20Burst%202%20installer%20by%20Lin.msi"
HTTP/1.1 200 Connection established

HTTP/2 200
date: Mon, 11 Dec 2023 16:56:30 GMT
content-type: application/x-msdownload
content-length: 10395648
last-modified: Mon, 03 Jul 2023 02:05:05 GMT
accept-ranges: bytes
vary: User-Agent
cf-cache-status: DYNAMIC
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=hchoOcOUy%2FypydbNX069leoYk3x1dJH51VBnEz%2Faxubq3bCoPmNTlWbpcEN0Jbln%2FIEgQ2zwdfS%2BFvnvnftR1G0QrLBPSFU%2BBdkgckL1%2B%2F6aYbTQFqBRXxwLrRNg0RDIIUdkYAx6Pg%3D%3D"}],"group":"cf-nel","max_age":604800}
nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 833f42de7fa10495-HKG
alt-svc: h3=":443"; ma=86400
```

Is this behaviour related to `winget.exe` only? Maybe the official download server is behind protections from Cloudflare and CF regards `winget.exe` as an unexpected bot client and blocks it?

Could you please provide more details about the error? I'll check if this problem can be reproduced by simulating the default `User-Agent` of `winget.exe`.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 12/11/2023 2:52:09 PM
Installer Verification Analysis Context Information: 
Error occurred while downloading installer from https://www.plazmaburst2.com/pb2/Plazma%20Burst%202%20installer%20by%20Lin.msi. Forbidden (403). (0x80190193).
Error information: 
Http Response: Forbidden
Http Reason Phrase: Forbidden

**Comment by Dragon1573** [comment]
Reproduce this behaviour with GitHub Actions on GitHub-hosted Runner. It seems the release server only allows end users to download the installer file. It might detect using IP ranges.

image

[logs_4.zip](https://github.com/microsoft/winget-pkgs/files/13643930/logs_4.zip)

@stephengillie - Does this package acceptable? Or I'll close this pull request without merge and mark the issue as "Not planned".

**Comment by stephengillie** [comment]
Unfortunately, the PR did not progress through enough checks to be manually validated. 

> 12/11/2023 2:52:09 PM
Installer Verification Analysis Context Information: 
Error occurred while downloading installer from https://www.plazmaburst2.com/pb2/Plazma%20Burst%202%20installer%20by%20Lin.msi. Forbidden (403). (0x80190193).
Error information: 
Http Response: Forbidden
Http Reason Phrase: Forbidden

**Comment by Dragon1573** [comment]
Okay ...

I think this package is unable to sumit to the repository :disappointed:

Pull request can be closed ...

**Pull request closed without merging**
