### PR TITLE
microsoft store 11808.1001.413.0

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3997)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
The URL that the app is coming from does not look correct.  I would expect the Microsoft store app if distributed via github to come from https://github.com/Microsoft.  
Can you clarify?

**Comment by oxygen-dioxide** [comment]
In most windows 10 computers, microsoft store is pre-installed, so microsoft doesn't provide an official download link for microsoft store appx.
However, windows 10 LTSB and LTSC don't have a microsoft store pre-installed, and microsoft store has to be installed manually. This third-party download link is provided for LTSB and LTSC users.

**Comment by jvintzel** [comment]
> In most windows 10 computers, microsoft store is pre-installed, so microsoft doesn't provide an official download link for microsoft store appx.
> However, windows 10 LTSB and LTSC don't have a microsoft store pre-installed, and microsoft store has to be installed manually. This third-party download link is provided for LTSB and LTSC users.

The Microsoft Store and Store services are not supported on LTSC by design.  This is due to the 10 year supportability commitment of the operating system.  If you require services like the Microsoft Store we do recommend using Windows 10 Enterprise edition.  

More info on recommended uses for LTSC can be found here:  [https://techcommunity.microsoft.com/t5/windows-it-pro-blog/ltsc-what-is-it-and-when-should-it-be-used/ba-p/293181](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/ltsc-what-is-it-and-when-should-it-be-used/ba-p/293181))

**Pull request closed without merging**
