### PR TITLE
New package: Apache NetBeans 17

### PR DESCRIPTION
**Pull request by kimwonj77**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

This requires JDK 8+.
image

Since there's no way to specify JDK in dependency field, I won't added it for now. 

Note: https://github.com/microsoft/winget-cli/blob/master/doc/specs/%23163%20-%20Dependencies.md#external-dependencies
> These include dependencies from outside of the source the original package is distributed. In some cases suitable items may exist in the same source, but for licensing or personal preference, no explicit package should be required. One example is Java. Many vendors offer JREs and JDKs so it may be more reasonable to have a user informed, and allow the user to confirm the presence of a dependency.

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/102998)

### CODE REVIEW

**Comment by Trenly** [comment]
[Policy] Dependencies

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
> Url validation error
> 
> * manifests\a\Apache\NetBeans\17
>   
>   * https://dlcdn.apache.org/netbeans/netbeans-installers/17/Apache-NetBeans-17-bin-windows-x64.exe
>     
>     * Http status code: NotFound

Verify:
image

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335226 
> 2023-12-28 13:08:42.434 [CLI ] ShellExecute installer failed: 1004

(Automated response - build 498.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
