### PR TITLE
Create 24.0.14033.yaml

### PR DESCRIPTION
**Pull request by CorelWinZip**
Created Corel WinZip 24.0.14033 Manifest

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1589)

### CODE REVIEW

**Review by prodiJy2000 — APPROVED** [review]
Created manifest for WinZip 24.0.1433.

**Review by prodiJy2000 — DISMISSED** [review]
I run the command line winget validate manifest.yaml which says my manifest file is valid. This says here the file is not valid. What is going on?

**Review by prodiJy2000 — DISMISSED** [review]
This has only 1 installer.
Not the winget validate tool shall be updated to not accept 2 installers at the moment.
It misleads to validate then it is not valid on GitHub.com.

**Comment by CorelWinZip** [comment]
@microsoft please approve a.s.a.p. Thanks!

**Review by prodiJy2000 — APPROVED** [review]
The changes look good.

**Comment by CorelWinZip** [comment]
@KevinLaMS @superusercode Can you approve this quickly? Thanks in advance!

**Comment by CorelWinZip** [comment]
When is this going to be approved?
Why is this taking a very long time?

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
