### PR TITLE
Normalize TTKN.CNKIExpress 0.1.18

### PR DESCRIPTION
**Pull request by Trenly**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/76454)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
@denelon - Blocking Issue

```
2022-08-31 07:02:06.194 [CLI ] Caught std::exception: No mapping for the Unicode character exists in the target multi-byte code page.
```

microsoft/winget-cli#2057

**Review by vedantmgoyal9 — CHANGES_REQUESTED** [review]
* Duplicate of https://github.com/microsoft/winget-pkgs/pull/74601

**Comment by Trenly** [comment]
Removing Needs-Author-Feedback

**Review by jedieaston — APPROVED** [review]

**Review by jedieaston — APPROVED** [review]

**Review by ImJoakim — APPROVED** [review]

**Pull request merged**
