### PR TITLE
MusicBrainz.Picard version 2.9.1.0

### PR DESCRIPTION
**Pull request by Scavy**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/119211)

### CODE REVIEW

**Comment by Scavy** [comment]
For some reason the there's a difference in the package version that the validator gets from the files:

**MusicBrainz-Picard-2.9.1.msix**
Has a file version of 2.9.1.0 - But in the "AppxManifest.xml" file inside the MSIX file, it says "<Identity Version 2.9.10000.0

**picard-setup-2.9.1.exe**
Has a exe file version of 2.9.1.0

Everywhere in sourcecode and on the website it's referred to as 2.9.1 or 2.9.1.0 - And sometimes 2.9.1.final.0 (from: "PICARD_VERSION = Version(2, 9, 1, 'final', 0)" )

How do I do this correctly - it worked for me on last update under the same conditions.

**Comment by stephengillie** [comment]
I believe the PackageVersion is supposed to match the Control Panel and the AppsAndFeaturesEntries - DisplayVersion should match the Apps and Features entry. 

To verify, the [1.5.0 manifest schema](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.5.0/installer.md): 
- PackageVersion # The package version
- AppsAndFeaturesEntries - DisplayVersion  # Optional version displayed in the ARP entry

**Comment by stephengillie** [comment]
When trying to verify these in a VM, I encountered an error:
image

**Comment by stephengillie** [comment]
Apps and Features > Advanced Options page
image
- It doesn't display the version on the main Apps and Features page.
- This doesn't display in the Control Panel.

File properties:
image

I see the `.0` difference between File Version and Product Version. I'm guessing that the DisplayVersion in the manifest has to match the Product Version, but again I'm not certain of this.

**Comment by stephengillie** [comment]
To summarize, I believe these should be:
`PackageVersion` - `2.9.1`
`AppsAndFeaturesEntries` - `DisplayVersion` 2.9.1000.0

And again, I'm not completely certain of this.

**Comment by Scavy** [comment]
> To summarize, I believe these should be: `PackageVersion` - `2.9.1` `AppsAndFeaturesEntries` - `DisplayVersion` `2.9.1000.0`
> 
> And again, I'm not completely certain of this.

I just tried this, and it came up with the same validation error, so I think it might be the other way around.
I'll test it again :)

And thanks for taking your time to go through this, it also helps me to understand how to make better submissions here :)
I'm looking into submitting an Issue at winget-create repo.. since the original PR was created and submitted by that.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
