### PR TITLE
KDE.Krita version 4.4.7

### PR DESCRIPTION
**Pull request by KaranKad**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/24594)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Hmmm do you feel like its worth fixing the version?
image
the .0 should be ignored, but 🙄

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/24594#issuecomment-897860845

**Comment by KaranKad** [comment]
Let's merge it and see if it works or not, if it works we keep it the way it is, if it doesn't then I'll make changes.

**Review by OfficialEsco — APPROVED** [review]

**Comment by KaranKad** [comment]
image
Somehow it works.

**Comment by OfficialEsco** [comment]
Yeah the .0's are ignored as a new version, `4.4.7.0.00.00.00` is seen as `4.4.7`, but we should keep a consistent version format for the package, but it dosn't seem like they release `X.X.X.1` versions so its okay for now 🤞
Levvie on the other hand would not accept this 🙄😁

**Comment by KaranKad** [comment]
I use oh-my-posh PowerShell module to get fancy looking shell, there are many themes to choose form, you also need to install one of the nerd font to get icons otherwise it will just appear like blocks. 
https://www.nerdfonts.com/
https://github.com/JanDeDobbeleer/oh-my-posh 
https://www.powershellgallery.com/packages/oh-my-posh/

Yeah, I guess I will fix Krita's version for better matching. I've also noticed that VLC's nullsoft installer reports 3.0.16 while msi installer reports 3.0.16.0 so idk what we can do there.

**Comment by OfficialEsco** [comment]
o my lord it was that simple, thaaaaaaaank you, thats hot😍

**Comment by denelon** [comment]
@OfficialEsco I was a bit starstruck when @JanDeDobbeleer showed up to use wingetcreate and automated releases for Oh My Posh. I'm still playing with my settings/preferences, but it's super useful!

**Pull request merged**
