### PR TITLE
New version: ImageMagick.Q16-HDRI version 7.1.1.43

### PR DESCRIPTION
**Pull request by dlemstra**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/202099)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by nbros** [comment]
How come I still get an error after this PR was merged? Is there a delay? Do I need to refresh something?
```
> winget install ImageMagick.ImageMagick
Found ImageMagick Q16-HDRI [ImageMagick.ImageMagick] Version 7.1.1.41
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-41-Q16-HDRI-x64-dll.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : unknown error
```

**Comment by dlemstra** [comment]
This is updating another package than you are referencing. The ImageMagick team is not maintaining the packages with id `ImageMagick.ImageMagick*`. Our packages have the following ids: `ImageMagick.Q16-HDRI`, `ImageMagick.Q16` and `ImageMagick.Q8`.

**Comment by nbros** [comment]
Oh thank you that works with "ImageMagick.Q16-HDRI"! 

I assumed _ImageMagick.ImageMagick_ was a kind of shortcut pointing to the default package but that's confusing if it's a different one altogether.

**Comment by dlemstra** [comment]
We did not take over the other package name because that uses a different kind of installer and is also not using the static version of ImageMagick.

**Pull request merged**
