### PR TITLE
Updated EarTrumpet manifest version

### PR DESCRIPTION
**Pull request by pbrandstetter**
The old EarTrumpet manifest did not work anymore, because the installer provided was not found.
Fix for #5757 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/5758)

### CODE REVIEW

**Review by sa-orlov — APPROVED** [review]

**Review by sa-orlov — APPROVED** [review]

**Comment by pbrandstetter** [comment]
Closed pull-request, because of wrong file-name.
Sorry ;(

**Review by sa-orlov — COMMENTED** [review]
Ok

**Review by sa-orlov — COMMENTED** [review]
Ik

**Review by sa-orlov — COMMENTED** [review]
Ok

**Review by sa-orlov — COMMENTED** [review]
Ik

**Pull request closed without merging**
