### PR TITLE
Remove version: electerm.electerm version 1.40.1

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/174637)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://github.com/electerm/electerm/releases/download/v1.40.1/electerm-1.40.1-win-x64-installer.exe 
Response Error: The remote server returned an error: (404) Not Found.

(Automated message - build 923)

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 896.)

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://github.com/electerm/electerm/releases/download/v1.40.1/electerm-1.40.1-win-x64-installer.exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 896)

**Comment by stephengillie** [comment]
URL: https://github.com/electerm/electerm/releases/download/v1.40.1/electerm-1.40.1-win-x64-installer.exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 896)

**Comment by stephengillie** [comment]
URL: https://github.com/electerm/electerm/releases/download/v1.40.1/electerm-1.40.1-win-x64-installer.exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 896)

**Comment by stephengillie** [comment]
URL: https://github.com/electerm/electerm/releases/download/v1.40.1/electerm-1.40.1-win-x64-installer.exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 896)

**Comment by stephengillie** [comment]
URL: https://github.com/electerm/electerm/releases/download/v1.40.1/electerm-1.40.1-win-x64-installer.exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 896)

**Comment by stephengillie** [comment]
URL: https://github.com/electerm/electerm/releases/download/v1.40.1/electerm-1.40.1-win-x64-installer.exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 896)

**Pull request closed without merging**
