### PR TITLE
Aserto.Topaz.v0.30.32

### PR DESCRIPTION
**Pull request by gertd**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140264)

### CODE REVIEW

**Comment by Trenly** [comment]
@gertd - I understand the previous PR was submitted by a bot account, but this PR seems to only remove metadata. Is there a reason to remove ReleaseDate and ReleaseNotes?

**Comment by stephengillie** [comment]
InstallerUrl contains Manifest version instead of PR version:
  InstallerUrl: https://github.com/aserto-dev/topaz/releases/download/v0.30.32/topaz_windows_x86_64.zip

(Automated message - build 776)

**Comment by stephengillie** [comment]
[Policy] Needs-Author-Feedback

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
This PR appears to conflict with the revert PR
- https://github.com/microsoft/winget-pkgs/pull/140266

**Comment by stephengillie** [comment]
Close with reason: Merge conflicts from #140264;

**Pull request closed without merging**
