### PR TITLE
Remove: pazer.TF2BotDetector version 1.2.1.934

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
Installer URL is 404 not found

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/69923)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
cc @denelon: Any idea what's happening here?

This pull request is meant to delete a package but the pipelines treats it as an addition instead of a deletion.

I created a new PR based on the latest master branch and the issue still happens: https://github.com/microsoft/winget-pkgs/pull/70739

**Comment by denelon** [comment]
@ItzLevvie, I'll ask the team to take a look at this scenario.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
