### PR TITLE
New package: MSI.LiveUpdate version 6.2.0.77

### PR DESCRIPTION
**Pull request by rakleed**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/202091)

### CODE REVIEW

**Comment by stephengillie** [comment]
image

**Comment by stephengillie** [comment]
Adding https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue to prevent my automation from continually re-running.

**Comment by Trenly** [comment]
> Adding [ Blocking-Issue](https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue) Manifest validation is blocked by a known issue. to prevent my automation from continually re-running.

@stephengillie - instead of blocking issue, isn’t `Needs-Author-Feedback` an indicator of which ones to skip?

**Comment by stephengillie** [comment]
Paradoxically, most of the ones which I need to work have that label.

**Comment by rakleed** [comment]
I did not understand the solution to this issue https://github.com/microsoft/winget-pkgs/issues/199504. Do you not accept such software at all?

**Comment by stephengillie** [comment]
> I did not understand the solution to this issue #199504. Do you not accept such software at all?

Unfortunately, not at this time. The software has to pass through the pipeline, but the pipeline doesn't have a method to access the prerequisite hardware.

**Pull request closed without merging**
