### PR TITLE
Add installation notes to 230602 GDK.

### PR DESCRIPTION
**Pull request by MattHyman**
Add installation notes to 230602 GDK.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/118722)

### CODE REVIEW

**Comment by MattHyman** [comment]
@microsoft/xbox-developer-experience-toolbox and @aaron-stebner for review.

**Comment by aaron-stebner** [comment]
LGTM

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2023-09-01 14:13:35.808 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(104)\WindowsPackageManager.dll!00007FFC1DA215CA: (caller: 00007FFC1DA22129) Exception(2) tid(1538) 80072EE2     Msg:[InternetReadFile() failed.]  
2023-09-01 14:13:35.824 [CLI ] Failed to download, waiting a bit and retry. Url: https://github.com/microsoft/GDK/archive/refs/tags/June_2023_Update_2.zip 

Confirming it's the common error.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
