### PR TITLE
Add Microsoft Image Composite Editor

### PR DESCRIPTION
**Pull request by JanPokorny**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/4212)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
I seem to get a failure 1603 if admin or nonadmin.

image

**Comment by JanPokorny** [comment]
@KevinLaMS I am unable to reproduce the error, the installation happens successfully from both admin and non-admin shells. Could you provide contents of the installer log mentioned in your screenshot?

obrazek

**Comment by JanPokorny** [comment]
Looks like the problem is missing dependency: Visual C++ 2013 Redistributable. This is thus blocked by https://github.com/microsoft/winget-cli/issues/163

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
image

**Comment by JanPokorny** [comment]
Looks like Microsoft killed ICE before Microsoft could fix winget to be able to install ICE
image

**Pull request closed without merging**
