### PR TITLE
Update Chrome to 85

### PR DESCRIPTION
**Pull request by auanasgheps**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3259)

### CODE REVIEW

**Review by auanasgheps — COMMENTED** [review]
Fix Silent install command

**Comment by KevinLaMS** [comment]
image

**Comment by auanasgheps** [comment]
Apologies for italian language, but it works on my VM...

image

**Comment by OfficialEsco** [comment]
#3350 got merged, please use the MSI installer and update the latest.yaml in the future

**Pull request closed without merging**
