### PR TITLE
New version: Telegram.TelegramDesktop version 5.5.5

### PR DESCRIPTION
**Pull request by john-preston**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/173260)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 895.)

**Review by stephengillie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
[Policy] Needs-CLA

**Comment by ItzLevvie** [comment]
Close with reason: Merge conflicts;

**Comment by ItzLevvie** [comment]
[Policy] Needs-CLA

**Pull request closed without merging**
