### PR TITLE
Update: Ahlyab.UdemyCouponFetcher version 1.2 [FP-D]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Failed
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | Udemy Coupon Fetcher | AcFun面捕助手 版本 1.31.0.1707    |
| Version     | 1.2     | 1.31.0.1707 |
| Publisher   | Ahlyab   | Beijing Kuaishou Technology Co., Ltd.      |
| ProductCode |           | {791F2E2A-3ACE-47F6-BA52-1DB05CBE720B}_is1    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://bittu.eu.org/docs/wpa-intro) in workflow run [2805](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/2949588313>)

### CODE REVIEW

**Comment by russellbanks** [comment]
@vedantmgoyal2009, I don't think a package being available on the Microsoft Store is a reason for it to be deleted. I personally prefer installing apps from their source via an installer rather than the Microsoft Store, and there are cases where developers will provide both sources, but advise users to use the installer instead (for example, [lively/Differences-Between-Distributions](https://github.com/rocksdanister/lively/wiki/Differences-Between-Distributions))

**Comment by vedantmgoyal2009** [comment]
Okay, if it is so, @itzlevvie can approve deletions for old versions, and the latest version can be kept. Also, 1.x is deprecated (https://github.com/bitwarden/desktop) and the current development is on a new repository (https://github.com/bitwarden/clients).

**Comment by vedantmgoyal2009** [comment]
@ItzLevvie The latest PR is this one, so all previous PRs can be approved.

**Comment by russellbanks** [comment]
That's fair :)

**Review by ItzLevvie — DISMISSED** [review]

**Pull request merged**
