### PR TITLE
r12f.DivoomGateway version 0.1.39.0

### PR DESCRIPTION
**Pull request by r12f**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/68908)

### CODE REVIEW

**Comment by r12f** [comment]
Is this a pipeline issue? I created this PR via the latest wingetcreate with automated pipeline, there is no human involved for generating this new manifest.

image

**Comment by r12f** [comment]
it indeed looks like the manifest is already updated in winget-create, but not the validation pipeline:

https://github.com/microsoft/winget-create/blob/9915d3724472232d12072bbea645f2ac97f79b44/src/WingetCreateCore/Models/VersionManifestModels.cs

image

**Comment by russellbanks** [comment]
> Is this a pipeline issue? I created this PR via the latest wingetcreate with automated pipeline, there is no human involved for generating this new manifest.

The bot hasn't been set to accept 1.2.0 manifests yet, but it will once > half of winget users are on 1.3

**Comment by r12f** [comment]
thanks @russelbanks ! it seems really weird that the latest tool is updated before the pipeline accepts it. i will check the issue and see if we could make https://aka.ms/wingetcreate/latest still points to the one binary.

**Comment by r12f** [comment]
actually, nvm. let me see if i could make the pipeline always use a specific version of winget to workaround, since this will take a while.

**Comment by r12f** [comment]
closing this one and will reinvoke the pipeline for a new one.

**Pull request closed without merging**
