### PR TITLE
Naev.Naev version 0.10.5

### PR DESCRIPTION
**Pull request by superusercode**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/106890)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @superusercode,

This package installs normally, but gives this message when launched:
image

Is this expected?

**Comment by stephengillie** [comment]
> That is not expected, and it's strange that the game data files weren't created since the installer works under other silent contexts (i.e. installed with itch.io).

This package is probably not working correctly because it unexpectedly installs itself to the C:\ root, a somewhat-protected location: 
image

I tried probing for installer switches, but `/?` caused the package to silently install itself. Is there an installer switch to specify install location?

**Comment by stephengillie** [comment]
> since it's a nullsoft installer it should work with the `/D=C:\Bla or /D=C:\Path with spaces`

Unfortunately, this as installer switches didn't change the install location:
```
  InstallerSwitches:
    Custom: /D=C:\Naev\
```

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
I'm seeing the same issue as Stephen: https://github.com/microsoft/winget-pkgs/pull/106890#issuecomment-1550010392

This is on clean install of Windows on Hyper-V + all winget commands ran from `C:\Users\%USERNAME%\Desktop`

**Pull request closed without merging**
