### PR TITLE
RoyalApps.RoyalTS version 6.1.50712.0

### PR DESCRIPTION
**Pull request by StefanKoell**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/65897)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Comment by StefanKoell** [comment]
I re-submitted: https://github.com/microsoft/winget-pkgs/pull/66194

Hopefully it's working this time...

**Review by ItzLevvie — APPROVED** [review]

**Comment by hackean-msft** [comment]
@StefanKoell Is this a duplicate of https://github.com/microsoft/winget-pkgs/pull/66194. I don't see any file changes associated with the pull request.

**Comment by StefanKoell** [comment]
Yes, it seems that in this PR for whatever reason the installer hash was wrong. Not sure what the process is for this case.

**Comment by ItzLevvie** [comment]
Close with reason: Package has been merged;

**Pull request closed without merging**
