### PR TITLE
New package: Tableau.Server version 21.4.1440

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/38375)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
Took some time but it did complete
VirtualBoxVM_G4e55S6EG3

**Comment by ItzLevvie** [comment]
Looks like it's based on the hardware configuration.

It passes on my bare metal with 4 cores and 16 GB RAM.

My VM is set up to use 2 cores and 4 GB RAM and fails:
image

```
[056C:0184][2021-12-22T20:42:48]i000: INFO:  Starting Tableau Server environment requirements checks.
[056C:0184][2021-12-22T20:42:54]i000: ERROR:  Your system does NOT meet the minimum system requirements for Tableau Server.  Tableau Server requires these minimum hardware requirements, http://www.tableau.com/products/server/specs.  Please either try the install on a different computer, or explore our other options for running a trial of Tableau Server, http://www.tableau.com/products/server/download.

Reason:
Processor (cores):  actual = 2, minimum for trial = 4

System memory (in gigabytes):  actual = 4.0, minimum for trial = 16.0


Other resources found:
Free disk space (in gigabytes):  actual = 40.00, recommended = 50.00

Processor (cores):  actual = 2, recommended = 8

System memory (in gigabytes):  actual = 4.0, recommended = 64.0


Tableau Server will not be installed.  Click OK to exit. 

[056C:0184][2021-12-22T20:42:54]i000: ERROR:  Machine doesn't meet Tableau Server requirements, so installation has been terminated.  Exit code: 0x13ec
[056C:0184][2021-12-22T20:42:54]i000: INFO:  Ending Tableau Server environment requirements checks.
[056C:0184][2021-12-22T20:42:54]e000: Error 0xffffffff: The Tableau Server requirements checks failed or user clicked Cancel button on the warning message box.
[056C:0184][2021-12-22T20:42:54]e000: Error 0xffffffff: Failed to initialize data in bootstrapper application.
[056C:1220][2021-12-22T20:42:54]i500: Shutting down, exit code: 0xffff
```

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/38375#issuecomment-999873325

**Comment by OfficialEsco** [comment]
No idea about the Plans, but i believe this can go under https://github.com/microsoft/winget-cli/issues/1417
I'll let @denelon decide

**Comment by denelon** [comment]
Does the package declare hardware requirements?

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-pkgs/pull/38375#issuecomment-999873325

> Tableau Server requires these minimum hardware requirements, http://www.tableau.com/products/server/specs.

In Levvie's testing
> Reason:
> Processor (cores):  actual = 2, minimum for trial = 4
> System memory (in gigabytes):  actual = 4.0, minimum for trial = 16.0
>
>Other resources found:
>Free disk space (in gigabytes):  actual = 40.00, recommended = 50.00
>Processor (cores):  actual = 2, recommended = 8
>System memory (in gigabytes):  actual = 4.0, recommended = 64.0

However this seems a bit wrong, it worked for me with 4gb RAM and 4 Virtual Processors whatever that is in CPU/Threads (Maybe its reading my 16 cores then applies 4 threads?)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
