### PR TITLE
New version: Ferdium.Ferdium version 6.7.3

### PR DESCRIPTION
**Pull request by Alphrag**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/151037)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-04-25 06:38:09.871 [FAIL] Installer failed security check. Url: https://github.com/ferdium/ferdium-app/releases/download/v6.7.3/Ferdium-win-AutoSetup-6.7.3-x64.exe Result: 0x80004005
> 2024-04-25 06:37:35.575 [FAIL] Installer failed security check. Url: https://github.com/ferdium/ferdium-app/releases/download/v6.7.3/Ferdium-win-AutoSetup-6.7.3-ia32.exe Result: 0x80004005

(Automated response - build 877.)

**Review by stephengillie — APPROVED** [review]

**Comment by Alphrag** [comment]
Thanks @stephengillie, I am still wondering what kind of changes make the security scan fail on first try from time to time 🤔

**Comment by stephengillie** [comment]
I do not know. I'm guessing the answer lay around automated heuristics and possibly AI sentiment.

**Pull request merged**
