### PR TITLE
therealpaulgg.ssh-sync version v0.2.2

### PR DESCRIPTION
**Pull request by therealpaulgg**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/99522)

### CODE REVIEW

**Comment by therealpaulgg** [comment]
@microsoft-github-policy-service agree

**Comment by therealpaulgg** [comment]
> @therealpaulgg please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Hi @therealpaulgg,

The installation isn't unattended - it gives this message:
image

Clicking "Run" lets the packge complete installing normally. Is there some way to bypass this message and have the program install automatically?

**Comment by therealpaulgg** [comment]
> Hi @therealpaulgg,
> 
> 
> 
> The installation isn't unattended - it gives this message:
> 
> image
> 
> 
> 
> Clicking "Run" lets the package complete installing normally. Is there some way to bypass this message and have the package install automatically?

sorry I'm honestly very new to creating Windows installers in general. Any resources you'd recommend for unattended installers? I was trying to use NSIS for this one.

**Comment by stephengillie** [comment]
> sorry I'm honestly very new to creating Windows installers in general. Any resources you'd recommend for unattended installers? I was trying to use NSIS for this one.

The bottom of the message suggests that the package isn't digitally signed. Would it be possible to digitally sign the package?

**Comment by therealpaulgg** [comment]
> > sorry I'm honestly very new to creating Windows installers in general. Any resources you'd recommend for unattended installers? I was trying to use NSIS for this one.
> 
> The bottom of the message suggests that the package isn't digitally signed. Would it be possible to digitally sign the package?

I've been looking into this but I don't have a pfx certificate at this time. Is it a standard for all winget apps to be signed?

**Comment by stephengillie** [comment]
> I've been looking into this but I don't have a pfx certificate at this time. Is it a standard for all winget apps to be signed?

I believe basically all WinGet apps are signed. It's basically a tamper-evident seal on the software package.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package is expecting arguments:
```
NAME:
   ssh-sync - A new cli application

USAGE:
   ssh-sync [global options] command [command options] [arguments...]

DESCRIPTION:
   Syncs your ssh keys to a remote server

COMMANDS:
   setup
...
```

**Pull request merged**
