### PR TITLE
New version: Jackett.Jackett version 0.21.1991

### PR DESCRIPTION
**Pull request by ilike2burnthing**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/143536)

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
No issue.

**Comment by stephengillie** [comment]
Hi @ilike2burnthing,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 869.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-09 22:23:49.751 [FAIL] Installer failed security check. Url: https://github.com/Jackett/Jackett/releases/download/v0.21.1991/Jackett.Installer.Windows.exe Result: 0x80004005

(Automated response - build 869.)

**Comment by ilike2burnthing** [comment]
Can I set WD on fire yet?

**Review by ImJoakim — APPROVED** [review]

**Pull request merged**
