### PR TITLE
Create 2.3.6.yaml

### PR DESCRIPTION
**Pull request by bquistorff**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [X] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/5668)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
image

**Comment by bquistorff** [comment]
Typical LyX usage requires a latex installation (e.g., MiKTeX on Windows) and so the LyX installer checks for it. The verbose mode has a page to disable this check, but I'm not sure if this can be specified from the command-line when running the installer. Is there a way to specify dependencies in the manifest or is the only option to find a command-line argument to disable the check?

**Comment by KevinLaMS** [comment]
We have an issue to add dependency support.  https://github.com/microsoft/winget-cli/issues/163

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
