### PR TITLE
Origin v10.5.77.42374

### PR DESCRIPTION
**Pull request by OfficialEsco**
Dependency: VC++2015-2019Redist-x86

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [X] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2621)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
image

**Comment by OfficialEsco** [comment]
What do you mean by

> In the meantime, if you include the dependencies in your package, it should pass.
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

I wrote in the original post which dependency it needed, which should be vc_redist.x86.exe

Thought it would be ok since Origin was already merged, but i just checked the merged manifest and it appears to be a glitch that made it pass

**Comment by OfficialEsco** [comment]
closing since there is a new one

**Pull request closed without merging**
