### PR TITLE
Add OpenRCT2 0.2.6

### PR DESCRIPTION
**Pull request by latere-a-latere**
This manifest installs correctly but for some reason the installer exits with code 1223. Does anybody know how to fix this?

Smartscreen result:

image

Part of https://github.com/MarNicGit/winget-pkgs/issues/4

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1179)

### CODE REVIEW

**Comment by superusercode** [comment]
@MarNicGit smartscreen in edge no longer warns about openrct
image

**Comment by KevinLaMS** [comment]
Installer failed with exit code: 1223

**Comment by MarNicGit** [comment]
@KevinLaMS I am aware, that's why this PR is still a draft. Despite the error code the application runs fine and all the files are there it seems. Currently talking to OpenRCT2 to resolve this issue, once it's been figured out I'll be moving this PR from Draft to Ready for review.

**Comment by MarNicGit** [comment]
@KevinLaMS Could you put the Blocking Issue label on this PR? It relates to https://github.com/microsoft/winget-cli/issues/137.

**Comment by KevinLaMS** [comment]
https://github.com/microsoft/winget-cli/issues/137

**Comment by denelon** [comment]
We now support non-zero success codes. If the manifest schema is updated, this might pass now :smile:

**Pull request merged**
