### PR TITLE
Update Mp3tag to 3.02

### PR DESCRIPTION
**Pull request by auanasgheps**
Update Mp3tag to 3.02

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3251)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
strange, cannot write to folder
image

**Comment by auanasgheps** [comment]
Hi, 
This installer is funny: Installation works if your command prompt is already escalated as Administrator.
I always run my testing with an admin window so I don't have to accept UAC for every app.

So, apparently the installer does not request administrator when installing via winget, because in an interactive installation the user has the option to make a portable installation and don't require administrator rights.

Let me se if I can force the installer to go trough that route.

**Comment by KevinLaMS** [comment]
Thanks, so the issue is that the installer requires admin command window.  
I will mark this blocked waiting on this issue:  https://github.com/microsoft/winget-cli/issues/152

**Comment by auanasgheps** [comment]
Outdated.

**Pull request closed without merging**
