### PR TITLE
New version: PLaSK 2024.02.12

### PR DESCRIPTION
**Pull request by macdems**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/133306)

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/138877)

### CODE REVIEW

**Comment by stephengillie** [comment]
This package isn't over 1 GB, but its dependency `Anaconda.Anaconda` tips the scales at 1.02 GB.

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 12:46:10 PM: 
> 2024-02-13 12:46:08.819 [FAIL] Installer failed security check. Url: https://get.plask.app/packages/PLaSK-
> 2024.02.12-win64-py311.exe Result: 0x80004005

(Automated response - build 732.)

**Comment by stephengillie** [comment]
Hi @macdems,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 732.)

**Comment by macdems** [comment]
> The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.
 
This must be a false positive. I have rebuilt the whole software from source.

**Comment by stephengillie** [comment]
URL: https://get.plask.app/packages/PLaSK-2024.02.12-win64-py311.exe 
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (get.plask.app:443)

(Automated message - build 745)

**Comment by stephengillie** [comment]
URL: https://get.plask.app/packages/PLaSK-2024.02.12-win64-py311.exe 
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (get.plask.app:443)

(Automated message - build 745)

**Comment by stephengillie** [comment]
Hi @macdems,

Has the installer been removed?

(Automated response - build 745.)

**Comment by stephengillie** [comment]
[Policy] Needs-Author-Feedback

**Comment by macdems** [comment]
The web service was temporarily offline due to the maintenance. Now it is back online.

**Comment by stephengillie** [comment]
This package is facing multiple validation hurdles:
- It doesn't make it through our validation pipeline. 
- It hasn't passed a Defender scan in manual validation. 
- Pipeline triggers keep retrying (by design), which complicates discerning the other 2.

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 12:07:43 PM: 
> 2024-02-15 12:07:42.902 [FAIL] Installer failed security check. Url: https://get.plask.app/packages/PLaSK-
> 2024.02.12-win64-py311.exe Result: 0x80004005 12:07:44 PM: Detected 1 Defender (with signature version 1.405.20.0) errors: 12:07:44 PM: Trojan:Win32/Wacatac.B!ml

(Automated response - build 751.)

**Comment by stephengillie** [comment]
Hi @macdems,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 756.)

**Comment by stephengillie** [comment]
Hi @macdems,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 757.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-02-20 17:44:05.677 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFEBEFF597D: (caller: 00007FFEBEFFBE09) Exception(1) tid(63c) 800700B7 Cannot create a file when that file already exists. 
> 2024-02-20 17:44:05.681 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFEBEFF597D: (caller: 00007FFEBEFFBE09) Exception(2) tid(63c) 800700B7 Cannot create a file when that file already exists. 
> 2024-02-20 17:44:05.696 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFEBEFF597D: (caller: 00007FFEBEFFBE09) Exception(3) tid(63c) 800700B7 Cannot create a file when that file already exists. 
> 2024-02-20 17:44:05.701 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFEBEFF597D: (caller: 00007FFEBEFFBE09) Exception(4) tid(63c) 800700B7 Cannot create a file when that file already exists. 
> 2024-02-20 17:44:05.713 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFEBEFF597D: (caller: 00007FFEBEFFBE09) Exception(5) tid(63c) 800700B7 Cannot create a file when that file already exists. 
> 2024-02-20 17:44:05.728 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFEBEFF597D: (caller: 00007FFEBEFFBE09) Exception(6) tid(63c) 800700B7 Cannot create a file when that file already exists. 
> 2024-02-20 17:44:05.737 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFEBEFF597D: (caller: 00007FFEBEFFBE09) Exception(7) tid(63c) 800700B7 Cannot create a file when that file already exists. 
> 2024-02-20 17:44:05.745 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFEBEFF597D: (caller: 00007FFEBEFFBE09) Exception(8) tid(63c) 800700B7 Cannot create a file when that file already exists. 
> 2024-02-20 17:44:05.748 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFEBEFF597D: (caller: 00007FFEBEFFBE09) Exception(9) tid(63c) 800700B7 Cannot create a file when that file already exists. 
> 2024-02-20 17:44:05.758 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFEBEFF597D: (caller: 00007FFEBEFFBE09) Exception(10) tid(63c) 800700B7 Cannot create a file when that file already exists. 
> 2024-02-20 17:44:05.771 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFEBEFF597D: (caller: 00007FFEBEFFBE09) Exception(11) tid(63c) 800700B7 Cannot create a file when that file already exists. 
> 2024-02-20 17:44:05.869 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFEBEFF597D: (caller: 00007FFEBEFFBE09) Exception(12) tid(63c) 800700B7 Cannot create a file when that file already exists. 
> 2024-02-20 17:44:05.874 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFEBEFF597D: (caller: 00007FFEBEFFBE09) Exception(13) tid(63c) 800700B7 Cannot create a file when that file already exists. 
> 2024-02-20 17:44:05.886 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFEBEFF597D: (caller: 00007FFEBEFFBE09) Exception(14) tid(63c) 800700B7 Cannot create a file when that file already exists. 
> 2024-02-20 17:58:53.643 [FAIL] Installer failed security check. Url: https://get.plask.app/packages/PLaSK-
> 2024.02.12-win64-py311.exe Result: 0x80004005

(Automated response - build 776.)

**Comment by stephengillie** [comment]
Hi @macdems,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 776.)

**Pull request closed without merging**
