### PR TITLE
[Zip][Portable] New package: thebookisclosed.ViVeTool version 0.3.2

### PR DESCRIPTION
**Pull request by SpecterShell**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/92418)

### CODE REVIEW

**Comment by stephengillie** [comment]
In a VM, it installed successfully, and ran with no arguments. But both the /query and /enable arguments gave the same error: 

```
PS C:\> C:\Users\user\AppData\Local\Microsoft\WinGet\Links\vivetool.exe /query
ViVeTool v0.3.2 - Windows feature configuration tool


Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Albacore.ViVe, Version=2022.6.27.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at Albacore.ViVeTool.Program.ProcessArgs(String[] args)
   at Albacore.ViVeTool.Program.Main(String[] args)
```
Is there a missing dependency?

**Review by ItzLevvie — APPROVED** [review]

**Comment by SpecterShell** [comment]
> In a VM, it installed successfully, and ran with no arguments. But both the /query and /enable arguments gave the same error:
> 
> ```
> PS C:\> C:\Users\user\AppData\Local\Microsoft\WinGet\Links\vivetool.exe /query
> ViVeTool v0.3.2 - Windows feature configuration tool
> 
> 
> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Albacore.ViVe, Version=2022.6.27.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
>    at Albacore.ViVeTool.Program.ProcessArgs(String[] args)
>    at Albacore.ViVeTool.Program.Main(String[] args)
> ```
> 
> Is there a missing dependency?

I guess it is the `Albacore.ViVe.dll` file in the same directory. I manually copied the remaining files to the `Links` folder and it works fine now.

**Comment by thebookisclosed** [comment]
Hi, actual ViVeTool developer here.
Can this PR please get rejected?
I was never made aware of it and only found it today thanks to users mentioning it in my issue tracker. I find submissions of someone else's tools without any form of approval very unprofessional.

**Comment by denelon** [comment]
@thebookisclosed,

I looked at:
* https://github.com/thebookisclosed/ViVe/issues/43

I don't believe there was any ill will intended here. There are thousands of open-source packages in the community repository here and many are maintained by parties other than the original author. The actual packages aren't being copied over. The PR is to generate a manifest so WinGet could be used to install the package. Ideally, authors would publish manifests with their releases directly, but in many cases, they aren't able due to resource constraints or knowledge.

If you are interested in publishing the package yourself in the future, there are examples of how to do so using GitHub actions and we provide wingetcreate as a tool to support CI/CD scenarios:
* https://github.com/microsoft/PowerToys/blob/main/.github/workflows/package-submissions.yml
* https://github.com/JanDeDobbeleer/oh-my-posh/blob/main/.github/workflows/winget.yml

**Comment by thebookisclosed** [comment]
@denelon
Thank you for closing the PR. I'm sorry if the request sounded a bit brash, it was just a bit weird to see this submission without having the creator at least ask for permission. ViVe is of course open source and the manifest did correctly link to a GitHub release instead of another unofficial mirror, thing is I'd prefer to have some oversight when it comes to publishing it to WinGet. Thank you for understanding.

**Comment by sitiom** [comment]
> @denelon
> Thank you for closing the PR. I'm sorry if the request sounded a bit brash, it was just a bit weird to see this submission without having the creator at least ask for permission.

It was within his right to do so (at least that's what the license allows).

> ViVe is of course open source and the manifest did correctly link to a GitHub release instead of another unofficial mirror

winget-pkgs does not allows software from unofficial sources.

> Thank you very much for the CI/CD pointers, I am interested in eventually pushing to WinGet but there are some quirks I'd like to iron out first.

I do not think you will be able to do this until the symlink dependency problem is resolved in Winget (which was the only problem in this manifest).

**Pull request closed without merging**
