### PR TITLE
OBSStudio.obsstudio version 27.1.3

### PR DESCRIPTION
**Pull request by Recite9014**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/30181)

### CODE REVIEW

**Review by ImJoakim — CHANGES_REQUESTED** [review]
OBS Studio version 27.1.3 already exists here:

https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/OBSProject/OBSStudio/27.1.3

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
>oh alright them, I wasn't able to download it so thought it wasn't in the repository.

Have you done `winget search obs`?

**Comment by rickham75** [comment]
oh it just popped in and I have installed it via winget thanks for the help

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
>oh it just popped in and I have installed it via winget thanks for the help

You can close this PR now :)

**Pull request closed without merging**
