### PR TITLE
Fix openjdk to an id with a version number.

### PR DESCRIPTION
**Pull request by okrc**
* See https://github.com/microsoft/winget-pkgs/issues/8670

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/8937)

### CODE REVIEW

**Comment by zdevcs** [comment]
`One or more errors occurred. (Addition and deletion only permitted in the same directory) Addition and deletion only permitted in the same directory`
Does this mean I'm doing something wrong? Because I noticed that https://github.com/microsoft/winget-pkgs/pull/3378 has also added and deleted files in different directories.

**Comment by denelon** [comment]
@zdevcs, I looked at that PR, and only one file was modified.

**Comment by zdevcs** [comment]
> @zdevcs, I looked at that PR, and only one file was modified.

But I think these two PRs perform similar behavior.
|       | Moved |
| ---------- | :-----------:  |
| https://github.com/microsoft/winget-pkgs/pull/3378 | manifests/Mozilla/Thunderbird_v78.1.0/78.1.0.yaml → manifests/Mozilla/Thunderbird/78.1.0.yaml |
| This | manifests/AdoptOpenJDK/OpenJDK/8.0.252.yaml → manifests/AdoptOpenJDK/OpenJDK8/8.0.252.yaml |

|       | Before |  After |
| ---------- | :-----------:  | :-----------: |
| https://github.com/microsoft/winget-pkgs/pull/3378 | Thunderbird_v78.1.0/xxx.yaml | Thunderbird/xxx.yaml |
| This | OpenJDK/xxx.yaml | OpenJDK8/xxx.yaml |

**Comment by denelon** [comment]
@zdevcs, the limitations were originally designed and built due to the validation we perform on installers. The other examples are essentially a "rename" type of command. For those scenarios it's logically one version of a single package being modified. They are also from several months ago. We're continuously making changes to try and improve the system.

Additional enhancements are being made to try and improve how the system behaves. Once we have the new manifest schema in place (migration scheduled for Monday the 22nd) we will be able to support multiple installers in one PR. We are still going to keep the restrictions for "one logical version" of a single package per PR.

**Comment by zdevcs** [comment]
> @zdevcs, the limitations were originally designed and built due to the validation we perform on installers. The other examples are essentially a "rename" type of command. For those scenarios it's logically one version of a single package being modified. They are also from several months ago. We're continuously making changes to try and improve the system.
> 
> Additional enhancements are being made to try and improve how the system behaves. Once we have the new manifest schema in place (migration scheduled for Monday the 22nd) we will be able to support multiple installers in one PR. We are still going to keep the restrictions for "one logical version" of a single package per PR.

Well, this PR will be closed and I look forward to resolving this issue in the future. Thanks.

**Comment by denelon** [comment]
Thank you for the contribution!

**Pull request closed without merging**
