### PR TITLE
Roblox.Roblox version 1.6.0.24449

### PR DESCRIPTION
**Pull request by UtilisateurDeGithu**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/99427)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/99427)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @UtilisateurDeGithu,

Unfortunately, the architecture of the Roblox CDN, with different per-CDN hashes, makes it a poor fit for installation through the WinGet package manager. 
* https://github.com/microsoft/winget-pkgs/issues/94013

**Comment by UtilisateurDeGithu** [comment]
Hi, @stephengillie,

Do you means that Roblox client is considered as incompatible with winget due to how this knstaller work?

**Comment by stephengillie** [comment]
> Do you means that Roblox client is considered as incompatible with winget due to how this installer work?

Apologies, apparently this isn't an issue anymore. But the installer isn't unattended:
image

Is there an installer switch to clear this OK box? If one is found, then this will pass that validation step.

**Comment by UtilisateurDeGithu** [comment]
> > Do you means that Roblox client is considered as incompatible with winget due to how this installer work?
> 
> Apologies, apparently this isn't an issue anymore. But the installer isn't unattended: image
> 
> Is there an installer switch to clear this OK box? If one is found, then this will pass that validation step.

I'm currently searching if there is a launch argument, the problem is there is no documentation and help menu.

**Comment by UtilisateurDeGithu** [comment]
There is no silent/no interactivity switch to skip the "successfully installed" dialog box, that make winget waiting for the user a manual interaction with the installer.

**Comment by stephengillie** [comment]
This might be supported under:
* https://github.com/microsoft/winget-cli/issues/910

**Pull request closed without merging**
