### PR TITLE
New version: o2sh.onefetch version 2.17.0

### PR DESCRIPTION
**Pull request by o2sh**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/102011)

### CODE REVIEW

**Comment by o2sh** [comment]
Hi @stephengillie @Madhusudhan-MSFT, any idea why this PR was tagged with "Validation-Executable-Error"?

What can I do for this PR to be merged?

**Review by russellbanks — APPROVED** [review]

**Comment by stephengillie** [comment]
> Hello @stephengillie and @Madhusudhan-MSFT,
> 
> I noticed that this PR was tagged with "Validation-Executable-Error." Could you provide some insight as to why this occurred?
> 
> Anything I can do for this PR to be merged?

Hi @o2sh,

This package requires a dependency to install, but dependencies are not currently supported. This presents a blocker to new users, and so new packages are blocked. But for existing packages like yours, existing users already have the dependency installed and are just upgrading, so an exception is made.

**Pull request merged**
