### PR TITLE
Delete manifests/m/Malwarebytes/Malwarebytes/4.6.12.399 directory

### PR DESCRIPTION
**Pull request by coffee-or-death**
The is just a installer file version, not an application version.

Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/147372)

### CODE REVIEW

**Comment by jpdoherty** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
URL: https://data-cdn.mbamupdates.com/web/mb4-setup-consumer/MBSetup.exe 
Status Code: 200

(Automated message - build 876)

**Comment by stephengillie** [comment]
URL: https://data-cdn.mbamupdates.com/web/mb4-setup-consumer/MBSetup.exe 


(Automated message - build 598)

**Comment by stephengillie** [comment]
URL: https://data-cdn.mbamupdates.com/web/mb4-setup-consumer/MBSetup.exe 


(Automated message - build 598)

**Comment by stephengillie** [comment]
Hi @jpdoherty,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 876.)

**Comment by jpdoherty** [comment]
The version is just incorrect. It is only the version of the installer file and not the application itself. There is an error somewhere in the identification of the current application version. 4.6.11.320 is the latest application build.

> Hello @jpdoherty,
> 
> This PR removes the last version of the package from the repository.
> 
> Please check if the package requires an update or is available from another source.
> 
> Template: msftbot/lastVersionRemaining

**Comment by stephengillie** [comment]
URL: https://data-cdn.mbamupdates.com/web/mb4-setup-consumer/MBSetup.exe 
Status Code: 200

(Automated message - build 876)

**Comment by stephengillie** [comment]
URL: https://data-cdn.mbamupdates.com/web/mb4-setup-consumer/MBSetup.exe 
Status Code: 200

(Automated message - build 876)

**Comment by stephengillie** [comment]
URL: https://data-cdn.mbamupdates.com/web/mb4-setup-consumer/MBSetup.exe 
Status Code: 200

(Automated message - build 876)

**Comment by stephengillie** [comment]
URL: https://data-cdn.mbamupdates.com/web/mb4-setup-consumer/MBSetup.exe 
Status Code: 200

(Automated message - build 876)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
