### PR TITLE
New version: blacktop.ipsw 3.1.370

### PR DESCRIPTION
**Pull request by blacktop**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/112799&drop=dogfoodAlpha

### CODE REVIEW

**Comment by blacktop** [comment]
@microsoft-github-policy-service agree

**Comment by blacktop** [comment]
I don't see anywhere where the reason for the validation failure is explained?

**Comment by blacktop** [comment]
Looking for some errors I see:
```
****************************************************************************************
Rebuilding Cache
****************************************************************************************
Status: Completed
##[error] Result: Failed
##[error] One or more errors occurred. (Exception of type 'System.OutOfMemoryException' was thrown.) Exception of type 'System.OutOfMemoryException' was thrown.
```
So it looks like for some reason your CI is exhausting it's memory?  The only thing I can think on my end is I'm using the `goreleaser` tool created by @caarlos0 and maybe it's creating 2 PRs sharing some UUID or something?

**Comment by stephengillie** [comment]
Manual Validation failed with:
> 5:22:38 PM:  > 2023-07-24 17:22:37.778 [FAIL] Installer failed security check. Url: https://github.com/blacktop/ipsw/releases/download/v3.1.370/ipsw_3.1.370_windows_i386.zip Result: 0x80004005 

We can retry the scan tomorrow.

**Comment by caarlos0** [comment]
> maybe it's creating 2 PRs sharing some UUID or something?

https://github.com/microsoft/winget-pkgs/pulls?q=+is%3Apr+author%3Ablacktop+

doesn't look like it...

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
