### PR TITLE
New version: GeodeSDK.GeodeCLI version 2.11.0

### PR DESCRIPTION
**Pull request by matcool**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140059)

### CODE REVIEW

**Comment by matcool** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Hi @matcool,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 763.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-19 05:47:25.008 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerSharedLib\SHA256.cpp(144)\WindowsPackageManager.dll!00007FF8219A273F: (caller: 00007FF8219EAEC4) Exception(1) tid(1c6c) 8A150040  2024-02-19 05:47:26.956 [FAIL] Installer failed security check. Url: https://github.com/geode-sdk/cli/releases/download/v2.11.0/geode-cli-v2.11.0-win.zip Result: 0x80004005 2024-02-19 05:47:26.956 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (48:60) [05:47:12:819]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.38.33135. Product Version: 14.38.33135. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (48:B8) [05:47:13:758]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Additional Runtime - 14.38.33135. Product Version: 14.38.33135. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [0D48:0D5C][2024-02-19T05:47:10]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 763.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 796.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
