### PR TITLE
New version: Datronicsoft.SpacedeskDriver.Client version 0.9.4200.0

### PR DESCRIPTION
**Pull request by krystofkrticka**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`? image
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

### CODE REVIEW

**Comment by stephengillie** [comment]
Unfortunately, we don't have a way to validate this package other than to keep retrying it.

**Comment by stephengillie** [comment]
I'm not sure that this will complete. We might not be able to validate this package with our current pipelines.

**Comment by stephengillie** [comment]
Hi @krystofkrticka,

Unfortunately, I do not believe this package will pass the Automatic Validation pipeline. We might not have a pipeline that can validate at this time.

**Comment by krystofkrticka** [comment]
@stephengillie I know Spacedesk packages always have some issues with pipelines even though in Windows Sandbox it installs just fine.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
