### PR TITLE
New package: hadolint.hadolint version 2.12.0

### PR DESCRIPTION
**Pull request by Okeanos**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://api.github.com/repos/microsoft/winget-pkgs/pulls/95633)

### CODE REVIEW

**Comment by Okeanos** [comment]
Probably the same problem as discussed in #95634 

Screenshot 2023-02-10 at 23 14 07

**Review by Trenly — APPROVED** [review]

**Comment by stephengillie** [comment]
This package expects a Dockerfile as input:
> Please provide a Dockerfile

Having another package as a dependency is a workable requirement, but requiring an output file from another application is less so.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
