### PR TITLE
Apple.QuickTime version 7.79.80.95

### PR DESCRIPTION
**Pull request by DanTheMan827**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/50603)

### CODE REVIEW

**Comment by DanTheMan827** [comment]
This exe doesn't appear to have a completely silent install option, although within the .exe are multiple .msi files

**Review by ghost — CHANGES_REQUESTED** [review]
Seeing the same error on Windows Sandbox - probably requires the Media Feature Pack:
image

You can check the logs for more details: https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=284253&view=artifacts&pathAsName=false&type=publishedArtifacts

**Comment by DanTheMan827** [comment]
It appears to be related to VC80.CRT
image

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> A local winget install from this manifest succeeded on my machine, but I already have various C++ runtimes installed

Maybe wait until dependency support which is coming soon to WinGet and then add the proper dependency to the package and see if it fixes it.

**Comment by ItzLevvie** [comment]
You can set this PR to DRAFT until it's ready.

**Comment by DanTheMan827** [comment]
Waiting on [wingetcli/163](https://github.com/microsoft/winget-cli/issues/163)

**Review by ItzLevvie — APPROVED** [review]
This pull request (PR) has been automatically approved via GitHub CLI using `50603..50603 | % { gh pr review --approve $_ }` in Windows PowerShell.

**Pull request closed without merging**
