### PR TITLE
New version: PragmaTwice.proxinject version 0.4.2-pre

### PR DESCRIPTION
**Pull request by PragmaTwice**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/71606)

### CODE REVIEW

**Comment by PragmaTwice** [comment]
@ItzLevvie Hi, `winget install --manifest ...` in my device works pretty well, and I do not know why it failed in the azure pipeline, could you please help me?

**Comment by PragmaTwice** [comment]
Is there anyone who can help me? @denelon @JohnMcPMS

**Comment by ItzLevvie** [comment]
> Is there anyone who can help me? @denelon @JohnMcPMS [#71606 (comment)](https://github.com/microsoft/winget-pkgs/pull/71606#issuecomment-1222481081)

It's just failing security check;
```
2022-08-22 21:51:46.760 [FAIL] Installer failed security check. Url: https://github.com/PragmaTwice/proxinject/releases/download/v0.4.2-pre/proxinjectSetup-v0.4.2-pre-x64.exe Result: 0x80004005
```

Wait for it to clear out in a few days or so.

**Comment by PragmaTwice** [comment]
@ItzLevvie  Thanks, I think it is a false positive (actually my windows defender sometimes will report virus on it).

This open source software use some dll injection techniques to provide SOCKS5 proxies, so maybe it is why there is a false positive. But I do not know how to connect Microsoft (Security Team) to eliminate it.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
