### PR TITLE
New version: c3er.mdview version 3.0.2

### PR DESCRIPTION
**Pull request by c3er**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131350)

### CODE REVIEW

**Comment by c3er** [comment]
Can't the bot be turned off until the problem is solved? These e-mail notifications about retry and fail every few hours are annoying to me.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
