### PR TITLE
New version: MCXStudio version v2024.2

### LINKED ISSUE #146464: [Update Request]: MCXStudio v2024.2
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

coti.mcxstudio

### Package Version

v2024.2

### Please describe the changes you would like to see

A new version of MCX Studio v2024.2 has been released. The download link is https://mcx.space/nightly/release/v2024.2/MCXStudio-v2024.2-installer.exe

### PR DESCRIPTION
**Pull request by fangq**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?
- resolves #146464

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/146465)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @fangq,

> This PR's version number v2024.2 has 2 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version v2023, which has 1 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 875)

**Comment by Trenly** [comment]
[Policy] Reset Feedback

**Comment by Trenly** [comment]
[Policy] Approved

**Comment by fangq** [comment]
> Hi @fangq,
> 
> > This PR's version number v2024.2 has 2 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version v2023, which has 1 parameters.
> 
> Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)
> 
> (Automated response - build 875)

here is the screenshot of the "Apps & features" setting - I confirm that it shows the matching version number - v2024.2

image

**Pull request merged**
