### PR TITLE
New version: Apache.OpenOffice version 4.114.9811

### PR DESCRIPTION
**Pull request by SpecterShell**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/111297&drop=dogfoodAlpha

### CODE REVIEW

**Comment by SpecterShell** [comment]
@stephengillie Need manual validation

**Comment by SpecterShell** [comment]
🤔

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335216 Installation failed with exit code -2145844819 
> 2023-07-07 19:39:58.409 [CORE] DeliveryOptimization error: 0x80072ee2, extended error: 0x00000000 
> 2023-07-07 19:39:58.411 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!5870877F: (caller: 58708E35) Exception(1) tid(1e8c) 80072EE2  
> 2023-07-07 19:39:59.130 [CORE] Download request failed. Returned status: 429 

This host appears to be [rate limiting](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) the download to the point that it can't complete.

**Comment by stephengillie** [comment]
In Manual Validation, one download is sometimes getting just 0.1 Mbps.

**Comment by stephengillie** [comment]
InstallerLocale: ast
Complete
InstallerLocale: bg
Incomplete
InstallerLocale: ca
Incomplete
InstallerLocale: ca-XV # ca-ES-valencia
Incomplete
InstallerLocale: ca-XR # ca-ES-valencia
Incomplete
InstallerLocale: cs
Incomplete
InstallerLocale: da
Incomplete
InstallerLocale: de
Incomplete
InstallerLocale: el
Incomplete
InstallerLocale: en-GB
Incomplete
InstallerLocale: es
Incomplete
InstallerLocale: eu
Incomplete
InstallerLocale: fi
Incomplete
InstallerLocale: fr
Incomplete
InstallerLocale: gd
Incomplete
InstallerLocale: gl
Incomplete
InstallerLocale: he
Incomplete
InstallerLocale: hi
Incomplete
InstallerLocale: hu
Incomplete
InstallerLocale: it
Incomplete
InstallerLocale: ja
Incomplete
InstallerLocale: km
Incomplete
InstallerLocale: ko
Incomplete
InstallerLocale: lt
Incomplete
InstallerLocale: nb
Incomplete
InstallerLocale: nl
Incomplete
InstallerLocale: pl
Incomplete
InstallerLocale: pt
Incomplete
InstallerLocale: pt-BR
Incomplete
InstallerLocale: ru
Incomplete
InstallerLocale: sk
Incomplete
InstallerLocale: sl
Incomplete
InstallerLocale: sr
Incomplete
InstallerLocale: sv
Incomplete
InstallerLocale: ta
Incomplete
InstallerLocale: th
Incomplete
InstallerLocale: tr
Incomplete
InstallerLocale: vi
Incomplete
InstallerLocale: zh-CN
Incomplete
InstallerLocale: zh-TW
Incomplete

**Comment by stephengillie** [comment]
> @stephengillie Need manual validation

Sorry for misunderstanding. I'm not sure why these 3 (ast, gd, sr) have an error exit code.

**Review by ItzLevvie — APPROVED** [review]

**Comment by SpecterShell** [comment]
> > @stephengillie Need manual validation
> 
> Sorry for misunderstanding. I'm not sure why these 3 (ast, gd, sr) have an error exit code.

It turns out to be an issue with WinGet that it can not match the installers for the three languages for some reasons, although I can find them in PowerShell `Get-Culture` command. 🤔
I replaced these locales with region-specified ones and it should work.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
