### PR TITLE
TrackerSoftware(Canada)Ltd.PDF-XChangeEditor version 9.0.354.0

### PR DESCRIPTION
**Pull request by techflashYT**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14548)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
On this one you should change the PackageIdentifier and rename the files to `TrackerSoftware.PDF-XChangeEditor`

**Comment by sanikdah** [comment]
Can I just edit the files for that instead of completely remaking it?

**Comment by OfficialEsco** [comment]
> Can I just edit the files for that instead of completely remaking it?

If you have GitHub Desktop installed you should be able to rename the folders/files without remaking the manifest.

**Comment by sanikdah** [comment]
> > Can I just edit the files for that instead of completely remaking it?
> 
> If you have GitHub Desktop installed you should be able to rename the folders/files without remaking the manifest.

Ok let me download it then.

**Comment by sanikdah** [comment]
> > > Can I just edit the files for that instead of completely remaking it?
> > 
> > 
> > If you have GitHub Desktop installed you should be able to rename the folders/files without remaking the manifest.
> 
> Ok let me download it then.

Ok I downloaded it and now I'm gonna try that command.

**Comment by sanikdah** [comment]
huh, I still don't have the git command.

**Comment by sanikdah** [comment]
guess I can just install git though.

**Pull request closed without merging**
