### PR TITLE
New package: jazzdelightsme.WingetPathUpdater version 1.0

### PR DESCRIPTION
**Pull request by jazzdelightsme**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/115650&drop=dogfoodAlpha

### CODE REVIEW

**Comment by jazzdelightsme** [comment]
SmartScreen was blocking the download of the EXE... but I believe that should be cleared up now; let's try again.

/AzurePipelines run

**Comment by jazzdelightsme** [comment]
This is the entirety of the log of the failed task:

```
8/9/2023 6:07:57 AM

****************************************************************************************
Installation Verification
****************************************************************************************
Status: Started
============================================================================== 
Task         : Installation Validation
Description  : Invoke an Azure Function
Version      : 1.220.0
Author       : Microsoft Corporation
Help URL     : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/azure-function
============================================================================== 
2023-08-09T06:07:58.7782704Z POST ***?code=***&
Request body: {
  "operationId": "WinGetSvc-Validation-309-115650-20230808-1",
  "BuildId": "485235",
  "PlanUrl": "https://dev.azure.com/ms/",
  "HubName": "build",
  "ProjectId": "ed6a5dfa-6e7f-413b-842c-8305dd9e89e6",
  "PlanId": "4046b19e-201d-45d6-a52a-39ebdfed855c",
  "JobId": "8bd16c8d-8352-5068-a6a9-f8dac8932ab2",
  "TimelineId": "4046b19e-201d-45d6-a52a-39ebdfed855c",
  "TaskInstanceId": "b4fb1ea3-54c6-5082-c163-925ab0c658d6",
  "AuthToken": ***
}
				Response Code: OK
				Response: 

8/9/2023 6:10:57 AM

****************************************************************************************
Installation Verification
****************************************************************************************

-----------------------------------------------------
Result: Failed
-----------------------------------------------------
Status: Completed
```

I don't see what went wrong... :( Is there any way to get more info about what isn't working on the pipeline machines?

**Comment by jazzdelightsme** [comment]
Like... there's not even an exit code from my EXE! :'(

**Comment by jazzdelightsme** [comment]
Does this do what I hope it does?

/AzurePipelines run

**Comment by jazzdelightsme** [comment]
This installer installs fine on machines that I have tried... I don't know why it is failing to install on the pipeline machines.

It should have written some diagnostic information to: `$env:TEMP\WingetPathUpdaterFailure2.txt`

Is there any way to collect that log upon failure? Is there some other way it should emit diagnostic information, in order to be diagnosable?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2023-08-09 18:52:17.791 [CLI ] Installer args: -NoProfile -ExecutionPolicy Bypass -Command . { try { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 ; iex \"& { $(Invoke-WebRequest https://raw.githubusercontent.com/jazzdelightsme/WingetPathUpdater/v1.0/WingetPathUpdaterInstall.ps1) } -SilentWithProgress $args\" ; exit $LastExitCode } catch { Write-Error $_ ; $_ | fl * -Force | Out-String | sc $env:TEMP\WingetPathUpdaterFailure2.txt ; start-sleep -seconds 15 ; exit -3 } }
2023-08-09 18:52:17.794 [CLI ] Starting: 'C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\jazzdelightsme.WingetPathUpdater.1.0\PowershellStub.exe' with arguments '-NoProfile -ExecutionPolicy Bypass -Command . { try { [Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12 ; iex \"& { $(Invoke-WebRequest https://raw.githubusercontent.com/jazzdelightsme/WingetPathUpdater/v1.0/WingetPathUpdaterInstall.ps1) } -SilentWithProgress $args\" ; exit $LastExitCode } catch { Write-Error $_ ; $_ | fl * -Force | Out-String | sc $env:TEMP\WingetPathUpdaterFailure2.txt ; start-sleep -seconds 15 ; exit -3 } }'
2023-08-09 18:52:36.185 [CLI ] ShellExecute installer failed: 4294967293
2023-08-09 18:52:36.186 [CLI ] Terminating context: 0x8a150006 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:1bf

This error is unexpectedly verbose, and appears to have a PowerShell section in the installer args.

**Comment by stephengillie** [comment]
Hi @jazzdelightsme,

The package downloads normally, but fails to install:
image

Here is the log file `$env:TEMP\WingetPathUpdaterFailure2.txt`: 
```
PSMessageDetails      : 
Exception             : System.NotSupportedException: The response content cannot be parsed because the Internet 
                        Explorer engine is not available, or Internet Explorer's first-launch configuration is not 
                        complete. Specify the UseBasicParsing parameter and try again. 
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.VerifyInternetExplorerAvailable(Boolean 
                        checkComObject)
                           at Microsoft.PowerShell.Commands.InvokeWebRequestCommand.ProcessResponse(WebResponse 
                        response)
                           at Microsoft.PowerShell.Commands.WebRequestPSCmdlet.ProcessRecord()
TargetObject          : 
CategoryInfo          : NotImplemented: (:) [Invoke-WebRequest], NotSupportedException
FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

We might not yet support this type of installer or package.

**Comment by jazzdelightsme** [comment]
Thanks for getting me over the hump, @stephengillie! I think I know what caused the last failure, and I've pushed another commit that also adds log support. Is the bot supposed to automatically run the validation pipeline, or does someone have to trigger it?

**Comment by stephengillie** [comment]
> Thanks for getting me over the hump, @stephengillie! I think I know what caused the last failure, and I've pushed another commit that also adds log support. Is the bot supposed to automatically run the validation pipeline, or does someone have to trigger it?

It's supposed to run automatically on changes. Thanks for your patience.

**Comment by jazzdelightsme** [comment]
@stephengillie I see that all the validation mostly passed, with the exception of this warning from the "installation validation" step:

```
##[warning] Validation concluded that this task needs to go to manual review.
```

I also see that there is a "Validation-No-Executables" tag/label that has been added. I am guessing here, but it sounds like that could be because some validation automation looked at what the installer did and said "hey, I didn't find any new EXEs on the system after the thing got installed, what gives?"

If that is the case, then I'll give the explanation: that is expected. This installer only installs a couple new *scripts*: a `.ps1`, and a `.cmd`, and then one or two other files that support those. So "no new EXEs" is expected and fine.

**Comment by stephengillie** [comment]
> @stephengillie I see that all the validation mostly passed, with the exception of this warning from the "installation validation" step:
> 
> ```
> ##[warning] Validation concluded that this task needs to go to manual review.
> ```
> 
> I also see that there is a "Validation-No-Executables" tag/label that has been added. I am guessing here, but it sounds like that could be because some validation automation looked at what the installer did and said "hey, I didn't find any new EXEs on the system after the thing got installed, what gives?"
> 
> If that is the case, then I'll give the explanation: that is expected. This installer only installs a couple new _scripts_: a `.ps1`, and a `.cmd`, and then one or two other files that support those. So "no new EXEs" is expected and fine.

Yes, our robot got confused by the lack of EXEs. Thanks for the quick explanation. @dnelon also gave me some background on this package. Feel free to @ me if I can help again.

**Comment by denelon** [comment]
@jazzdelightsme if a user uninstalls this package, do the files get removed?

I was just curious. @Trenly is working on an "upgrade behavior" none for a couple of packages that don't actually update the program like the Chocolatey Installer. 

If uninstalling this program doesn't actually remove those other files, we should consider how to help a user reason about what might have gotten left behind.

**Review by stephengillie — APPROVED** [review]

**Comment by jazzdelightsme** [comment]
@denelon:
> if a user uninstalls this package, do the files get removed?

Yes, everything gets removed on uninstall.

If a user installs it, and then they just re-run the install, it can tell if the script files look like they came from my package (it just looks for a particular string), and if so it just re-writes them (so if I came up with a v2, or if a user modified a script and wanted to reset it, it would just work).

Oh, wait, when I was testing the local manifest, it was convenient to be able to just keep re-running the install. But "just re-run the install" is apparently not a thing once you are using an actual published package--I just tried it, and it says "hey it's already installed, and there's no upgrade available". So that's fine, too.

If the script files exist on disk, but they *don't* look like they came from my package, install (and uninstall, too, actually) will fail (with an error saying so). And you can force-overwrite by saying "`winget install WingetPathUpdater --custom "-Force"`".

I did find one funny thing: if you are in `cmd.exe`, and you have WingetPathUpdater installed (so you are using `winget.cmd`), then you `winget uninstall WingetPathUpdater`, it successfully uninstalls the package, but right at the very end, you get a message "The batch file cannot be found", because we deleted `winget.cmd` right out from under `cmd`. Oh well. Who uses `cmd`, anyway?! 🤪

**Comment by denelon** [comment]
LOL! I think we can live with that. I'm so glad you implemented a reasonably intelligent uninstall!!!

Let me know when you update the issue. I'll tweet about it.

**Comment by jazzdelightsme** [comment]
Done: https://github.com/microsoft/winget-cli/issues/549#issuecomment-1675410316

BTW, THANK YOU, @stephengillie for getting this one through the system!

Thank you!

Also BTW: I filed my first Issue: https://github.com/jazzdelightsme/WingetPathUpdater/issues/1

One of the packages I tried added other environment variable names to the `PATH` (like "%NVM_HOME%"), instead of adding an actual path. So there may be a 1.1 coming out soon...

**Pull request merged**
