### PR TITLE
VeraCrypt

### PR DESCRIPTION
**Pull request by danthe1st**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
There is #846 but the YAML file is anvalid and it has been closed for inactivity.
- [X] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [X] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

This PR adds the package [VeraCrypt](https://www.veracrypt.fr/en/Home.html).

Silent flags are not supported by the installer as stated [in this issue](https://github.com/veracrypt/VeraCrypt/issues/447).

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3978)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
Validation-Unattend-Failed

**Comment by danthe1st** [comment]
There is no option for an installation without opening an installation window as described [here](https://github.com/veracrypt/VeraCrypt/issues/447).

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/910

We need to give users the ability to filter out packages that require interactive install.

**Comment by lionelberton** [comment]
Latest veracrypt version (1.25.4) now support silent install.
use switch "/qn ACCEPTLICENSE=YES" on msiexec command line to do silent install.
use switch "/norestart" to avoid rebooting.

So you should now be able to push this package forward, at last.
https://github.com/veracrypt/VeraCrypt/issues/447

**Comment by danthe1st** [comment]
closing this in favour of #39863

**Pull request closed without merging**
