### PR TITLE
Remove version: RussellBanks.Komac.Nightly version 2.0.0

### PR DESCRIPTION
**Pull request by CoolPlayLin**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137630)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-02T11:13:21.7548997Z Processing manifest: manifests\r\RussellBanks\Komac\Nightly\2.0.0
 2024-02-02T11:13:21.7563818Z -----------------------------------------------------
 2024-02-02T11:13:21.7572121Z Status: Started
 2024-02-02T11:13:21.7579799Z Manifest file is Deleted
 2024-02-02T11:13:22.0141664Z Status: Completed
 2024-02-02T11:13:22.0149857Z ##[error] Result: Failed
 2024-02-02T11:13:22.0180255Z ##[error] Sequence contains no elements
 2024-02-02T11:13:22.0821673Z ##[error]Manifest Validation Failed

(Automated response - build 694.)

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 694.)

**Comment by CoolPlayLin** [comment]
>Replaced by https://github.com/microsoft/winget-pkgs/pull/137631(This Pull Request requires approval from @russellbanks)

@stephengillie Add Review-Needed for this Pull Request this another metioned Pull Request please

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-02T15:18:08.1752074Z Processing manifest: manifests\r\RussellBanks\Komac\Nightly\2.0.0
 2024-02-02T15:18:08.1761699Z -----------------------------------------------------
 2024-02-02T15:18:08.1768518Z Status: Started
 2024-02-02T15:18:08.1776944Z Manifest file is Deleted
 2024-02-02T15:18:08.4605332Z Status: Completed
 2024-02-02T15:18:08.4618031Z ##[error] Result: Failed
 2024-02-02T15:18:08.4647328Z ##[error] Sequence contains no elements
 2024-02-02T15:18:08.5301132Z ##[error]Manifest Validation Failed

(Automated response - build 695.)

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 695.)

**Comment by stephengillie** [comment]
> > Replaced by #137631 Pull Request requires approval from @russellbanks)
> 
> @ stephengillie Add Review-Needed for this Pull Request and another mentioned Pull Request please

He appears to have approved the other one already.

**Comment by CoolPlayLin** [comment]
@russellbanks Can this be merge?

**Review by russellbanks — APPROVED** [review]

**Pull request merged**
