### PR TITLE
Androidstudio

### LINKED ISSUE #177: One of the request inputs is out of range.
This is the error from PR #132

### PR DESCRIPTION
**Pull request by KevinLaMS**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/132)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
this package seems to install correctly but we get an error 1223.  I suspect this error would be OK to ignore.
https://github.com/microsoft/winget-cli/issues/137

**Comment by denelon** [comment]
fixed by microsoft/winget-cli#137

**Comment by denelon** [comment]
Google.AndroidStudio was added in another PR.

**Pull request closed without merging**
