### PR TITLE
New version: Sandboxie.Classic version 5.55.18

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/57681)

### CODE REVIEW

**Comment by Trenly** [comment]
It seems the internal errors occur mostly when there are multiline elements inside a manifest; Usually ReleaseNotes and Description. I wonder if it has something to do with how it creates the merged manifests for validation?

**Comment by OfficialEsco** [comment]
Imma investigate once i'm done approving, IIRC wingetbot creates a singleton instead of using the original files, which COULD be the cause

**Comment by OfficialEsco** [comment]
<details>
<summary>Azure Manifest</summary>
<br>

```
Author: https://xanasoft.com
CopyrightUrl: https://raw.githubusercontent.com/sandboxie-plus/Sandboxie/master/LICENSE
Description: 'Sandboxie is a sandbox-based isolation software for 32- and 64-bit Windows
  NT-based operating systems.

  It was developed by Sophos (which acquired it from Invincea, which acquired it earlier
  from the original author Ronen Tzur).

  It creates a sandbox-like isolated operating environment in which applications can
  be run or installed without permanently modifying the local or mapped drive.

  Such an isolated virtual environment allows controlled testing of untrusted programs
  and web surfing.'
InstallModes:
- interactive
- silent
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerSha256: 6D3FECD0C86F4C03543A30B498B2CCD6747FBF8C2C85CF6641F17507350DA611
  InstallerUrl: https://github.com/sandboxie-plus/Sandboxie/releases/download/1.0.18/Sandboxie-Classic-x64-v5.55.18.exe
- Architecture: x86
  InstallerSha256: CDF90B3B3077CBD1ABEB3908E71544425C0CE106A9A772F897926391F4D99FE6
  InstallerUrl: https://github.com/sandboxie-plus/Sandboxie/releases/download/1.0.18/Sandboxie-Classic-x86-v5.55.18.exe
License: GNU General Public License v3.0
LicenseUrl: https://raw.githubusercontent.com/sandboxie-plus/Sandboxie/master/LICENSE
ManifestType: merged
ManifestVersion: 1.1.0
MinimumOSVersion: 10.0.0.0
Moniker: sandboxie-classic
PackageIdentifier: Sandboxie.Classic
PackageLocale: en-US
PackageName: Sandboxie
PackageUrl: https://github.com/sandboxie-plus/Sandboxie
PackageVersion: 5.55.18
Platform:
- Windows.Desktop
Publisher: sandboxie-plus.com
PublisherSupportUrl: https://github.com/sandboxie-plus/Sandboxie/issues
PublisherUrl: https://xanasoft.com
ReleaseDate: 2022-04-13
ReleaseNotes: "[5.55.18] - 2022-04-13\nAdded\n\u2022 added minor browsers to BlockSoftwareUpdaters
  template (by APMichael) #1784\n\nChanged\n\u2022 Failed memory read attempts to
  unboxed processes will no longer cause message 2111 by default\n  -- Note: the message
  can be enabled in the settings if desired with \"NotifyProcessAccessDenied=y\"\n\u2022
  reordered BlockSoftwareUpdaters template (by APMichael) #1785\n\nFixed\n\u2022 fixed
  pipe impersonation in compartment mode\n\u2022 fixed issue with box clean-up introduced
  in a recent build\n\u2022 fixed missing trace log cleanup command #1773\n\u2022
  fixed unpin did not work #1694\n\n[5.55.17] - 2022-04-02\nAdded\n\u2022 added checkbox
  for easy read access to memory of unsandboxed processes (old Sbie behaviour, not
  recommended)\n\nChanged\n\u2022 improved OpenProcess/OpenThread logging\n\nFixed\n\u2022
  fixed crash issue with the new monitor mode\n\u2022 fixed issue with resource access
  entry parsing\n\n[5.55.16] - 2022-04-01\nAdded\n\u2022 FIXED SECURITY ISSUE: memory
  of unsandboxed processes can no longer be read, exceptions are possible\n  -- you
  can use ReadIpcPath=$:program.exe to allow read access to unsandboxed processes
  or processes in other boxes\n\u2022 Added \"Monitor Mode\" to the resource access
  trace, similar to the old monitor view of SbieCtrl.exe\n\nChanged\n\u2022 EnableObjectFiltering
  is now set enabled by default, and replaces Sbie's old process/thread handle filter\n\u2022
  the $: syntax now accepts a wildcard $:* no more specialized wildcards though\n\nfixed\n\u2022
  fixed NtGetNextProcess being fully disabled instead of properly filtered\n\u2022
  fixed reworked image name resolution when creating new processes in a sandbox\n\u2022
  fixed regression with HideOtherBoxes=y #1743 #1666"
ReleaseNotesUrl: https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.18
Scope: machine
ShortDescription: Sandboxie is a sandbox-based isolation software for 32- and 64-bit
  Windows NT-based operating systems.
Tags:
- sandbox
UpgradeBehavior: install
```

</details>

<details>
<summary>Test Manifest</summary>
<br>

```
# yaml-language-server: $schema=https://aka.ms/winget-manifest.singleton.1.1.0.schema.json
Author: https://xanasoft.com
CopyrightUrl: https://raw.githubusercontent.com/sandboxie-plus/Sandboxie/master/LICENSE
Description: 'Sandboxie is a sandbox-based isolation software for 32- and 64-bit Windows
  NT-based operating systems.

  It was developed by Sophos (which acquired it from Invincea, which acquired it earlier
  from the original author Ronen Tzur).

  It creates a sandbox-like isolated operating environment in which applications can
  be run or installed without permanently modifying the local or mapped drive.

  Such an isolated virtual environment allows controlled testing of untrusted programs
  and web surfing.'
InstallModes:
- interactive
- silent
InstallerType: nullsoft
Installers:
- Architecture: x64
  InstallerSha256: 6D3FECD0C86F4C03543A30B498B2CCD6747FBF8C2C85CF6641F17507350DA611
  InstallerUrl: https://github.com/sandboxie-plus/Sandboxie/releases/download/1.0.18/Sandboxie-Classic-x64-v5.55.18.exe
License: GNU General Public License v3.0
LicenseUrl: https://raw.githubusercontent.com/sandboxie-plus/Sandboxie/master/LICENSE
ManifestType: singleton
ManifestVersion: 1.1.0
MinimumOSVersion: 10.0.0.0
Moniker: sandboxie-classic
PackageIdentifier: Sandboxie.Classic
PackageLocale: en-US
PackageName: Sandboxie
PackageUrl: https://github.com/sandboxie-plus/Sandboxie
PackageVersion: 5.55.18
Platform:
- Windows.Desktop
Publisher: sandboxie-plus.com
PublisherSupportUrl: https://github.com/sandboxie-plus/Sandboxie/issues
PublisherUrl: https://xanasoft.com
ReleaseDate: 2022-04-13
ReleaseNotes: "[5.55.18] - 2022-04-13\nAdded\n\u2022 added minor browsers to BlockSoftwareUpdaters
  template (by APMichael) #1784\n\nChanged\n\u2022 Failed memory read attempts to
  unboxed processes will no longer cause message 2111 by default\n  -- Note: the message
  can be enabled in the settings if desired with \"NotifyProcessAccessDenied=y\"\n\u2022
  reordered BlockSoftwareUpdaters template (by APMichael) #1785\n\nFixed\n\u2022 fixed
  pipe impersonation in compartment mode\n\u2022 fixed issue with box clean-up introduced
  in a recent build\n\u2022 fixed missing trace log cleanup command #1773\n\u2022
  fixed unpin did not work #1694\n\n[5.55.17] - 2022-04-02\nAdded\n\u2022 added checkbox
  for easy read access to memory of unsandboxed processes (old Sbie behaviour, not
  recommended)\n\nChanged\n\u2022 improved OpenProcess/OpenThread logging\n\nFixed\n\u2022
  fixed crash issue with the new monitor mode\n\u2022 fixed issue with resource access
  entry parsing\n\n[5.55.16] - 2022-04-01\nAdded\n\u2022 FIXED SECURITY ISSUE: memory
  of unsandboxed processes can no longer be read, exceptions are possible\n  -- you
  can use ReadIpcPath=$:program.exe to allow read access to unsandboxed processes
  or processes in other boxes\n\u2022 Added \"Monitor Mode\" to the resource access
  trace, similar to the old monitor view of SbieCtrl.exe\n\nChanged\n\u2022 EnableObjectFiltering
  is now set enabled by default, and replaces Sbie's old process/thread handle filter\n\u2022
  the $: syntax now accepts a wildcard $:* no more specialized wildcards though\n\nfixed\n\u2022
  fixed NtGetNextProcess being fully disabled instead of properly filtered\n\u2022
  fixed reworked image name resolution when creating new processes in a sandbox\n\u2022
  fixed regression with HideOtherBoxes=y #1743 #1666"
ReleaseNotesUrl: https://github.com/sandboxie-plus/Sandboxie/releases/tag/1.0.18
Scope: machine
ShortDescription: Sandboxie is a sandbox-based isolation software for 32- and 64-bit
  Windows NT-based operating systems.
Tags:
- sandbox
UpgradeBehavior: install
```

</details>


I did manage to get a InternetOpenUrl error, but it got resolved after running `winget source update` however it still worked after vm reset so i cannot replicate it..
```
PS M:\> winget install -m C:\Users\User\Desktop\test.yaml
Found Sandboxie [Sandboxie.Classic] Version 5.55.18
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/sandboxie-plus/Sandboxie/releases/download/1.0.18/Sandboxie-Classic-x64-v5.55.18.exe
An unexpected error occurred while executing the command:
InternetOpenUrl() failed.
0x80072f78 : unknown error

PS M:\> winget validate C:\Users\User\Desktop\test.yaml
Manifest validation succeeded.
```

i THINK the engineers can get a better error message tho

**Comment by OfficialEsco** [comment]
@zachcarp @denelon are you guys getting any specific logs from the `Internal-Error` issues?
The current Artifacts for some of these weird issues are non existent and would be interesting for troubleshooting

**Comment by zachcarp** [comment]
@OfficialEsco - I'm starting to look through logs now. I'm not 100% sure what it is at this moment - but I am looking.

**Comment by OfficialEsco** [comment]
IMO its failing really quick, so i'm guessing it doesn't even succeed to do `winget install -m`

**Comment by zachcarp** [comment]
You are correct. It isn't even getting to that part of our validation. It's failing in the actual validation of the manifest. I think I've narrowed down the root cause and will keep you posted. There are a couple failing in a similar manner.

**Comment by zachcarp** [comment]
@OfficialEsco This is an internal failure. An upstream team sent us an unexpected value that we attempted to parse into an enumeration which failed. We are currently working on a fix for this. We will also build measures to help avoid this in the future.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
