### PR TITLE
Microsoft.WindowsTerminalPreview version 1.11.2421.0

### PR DESCRIPTION
**Pull request by DHowett**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/26473)

### CODE REVIEW

**Review by ImJoakim — APPROVED** [review]
image

**Review by ImJoakim — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/26473#issuecomment-909595604

**Comment by DHowett** [comment]
Huh, I suspect that wingetcreate did something else unexepcted. Thank you.

**Comment by DHowett** [comment]
> Huh, I suspect that wingetcreate did something else unexepcted. Thank you.

Oh, or just somebody beat me to submitting the fixed version of my earlier PR which _was_ invalidated because wingetcreate did something unexpected. Thanks all.

**Pull request closed without merging**
