### PR TITLE
Version Update: TeamSonarr.Sonarr version 4.0.1.929

### PR DESCRIPTION
**Pull request by babblebauble**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135595)

### CODE REVIEW

**Comment by babblebauble** [comment]
Issue: #133371

**Comment by babblebauble** [comment]
> > Sequence contains no elements

* [[New Issue]: Sequence contains no elements #133371](https://github.com/microsoft/winget-pkgs/issues/133371)

**Comment by babblebauble** [comment]
Error looks to be related to:

* https://github.com/microsoft/winget-pkgs/issues/133371

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 642.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-20T11:49:19.0072403Z -----------------------------------------------------
 2024-01-20T11:49:19.0076478Z Status: Started
 2024-01-20T11:49:19.0081795Z Manifest file is Added
 2024-01-20T11:49:19.1654881Z Manifest content validated.
 2024-01-20T11:49:19.1665042Z Manifest contains installer: https://github.com/Sonarr/Sonarr/releases/download/v4.0.1.929/Sonarr.main.4.0.1.929.win-x86-installer.exe
 2024-01-20T11:49:19.1669156Z Manifest contains installer: https://github.com/Sonarr/Sonarr/releases/download/v4.0.1.929/Sonarr.main.4.0.1.929.win-x64-installer.exe
 2024-01-20T11:49:19.2609664Z Status: Completed
 2024-01-20T11:49:19.2617831Z Result: Succeeded
2024-01-20T11:49:19.3871164Z -----------------------------------------------------
 2024-01-20T11:49:19.3877821Z Status: Started
 2024-01-20T11:49:19.3886256Z Manifest file is Deleted
 2024-01-20T11:49:19.6584041Z Status: Completed
 2024-01-20T11:49:19.6596847Z ##[error] Result: Failed
 2024-01-20T11:49:19.6601281Z ##[error] Sequence contains no elements
 2024-01-20T11:49:19.7310899Z ##[error]Manifest Validation Failed
 2024-01-20T11:49:19.7319490Z 

(Automated response - build 642.)

**Pull request closed without merging**
