### PR TITLE
Replace OSDN URL: KiCad.KiCad version 5.1.10_1

### PR DESCRIPTION
**Pull request by stevenlele**
- See #167173

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/167174)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://downloads.kicad.org/kicad/windows/explore/stable/download/kicad-5.1.10_1-x86_64.exe 
OK

(Automated message - build 913)

**Comment by stephengillie** [comment]
URL: https://downloads.kicad.org/kicad/windows/explore/stable/download/kicad-5.1.10_1-x86_64.exe 
OK

(Automated message - build 913)

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Pull request merged**
