### PR TITLE
New version: EmoteInteractive.RemoteMouse version 4.503

### PR DESCRIPTION
**Pull request by mdanish-kh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----
- Closes #92695

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/93214)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @mdanish-kh,

This PR appears to remove the 4.502 version's defaultLocale file. Can this be reverted?

**Comment by mdanish-kh** [comment]
@stephengillie That is actually intentional as I deleted the previous manifest. They both contain the same InstallerUrl, so there is no need for `4.502` as it will always result in hash mismatch. wingetbot does this in two PRs (one for update and one for deletion). I did it one PR (update and remove).

All the files for `4.502` were deleted in this PR, but the other ones contained slight changes so GitHub is smart enough to show them as **replaced** and not **deleted**. I made major changes in the locale file, so GitHub is showing it as deleted and not replaced.

**Comment by stephengillie** [comment]
> @stephengillie That is actually intentional as I deleted the previous manifest. They both contain the same InstallerUrl, so there is no need for `4.502` as it will always result in hash mismatch. wingetbot does this in two PRs (one for update and one for deletion). I did it one PR (update and remove).
> 
> All the files for `4.502` were deleted in this PR, but the other ones contained slight changes so GitHub is smart enough to show them as **replaced** and not **deleted**. I made major changes in the locale file, so GitHub is showing it as deleted and not replaced.

Unfortunately, removing one version and adding another counts as changing more than one manifest per PR. The removal of 4.502 will need a separate PR.

**Comment by mdanish-kh** [comment]
@stephengillie, This still counts as change to one manifest as I've replaced the previous one in-place. The limit for one manifest per PR is because the Azure Pipelines cannot validate more than one manifest in the same PR but the Pipelines also agree that this counts as change to one manifest as `Pull-Request-Error` label was not added (you can see in #90939, #90715 where the label was added by the pipelines). 

The in-place upgrades can also be seen in #83397, #89713, #89712 and #89287 just to give a few examples of similar PRs (that **seemingly** change more than one manifest) that got validated and merged without an issue.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
