### PR TITLE
New version: EnderbytePrograms.PyinstallerHelper version 1.7

### PR DESCRIPTION
**Pull request by Enderbyte09**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/156512)

### CODE REVIEW

**Comment by Enderbyte09** [comment]
I promise that I have tested it extensively and it works with the winget install --manifest command without user interaction (_except every exe I touch gets accused of being a virus because it has the word "pyinstaller" in it_)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-06-04 08:04:19.282 [FAIL] Installer failed security check. Url: https://github.com/Enderbyte-Programs/PyinstallerHelper/releases/download/v1.7/pyinstallerhelper-1.7-setup.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 883.)

**Comment by Enderbyte09** [comment]
Hello. I have submitted both v1.7 and the older v1.6 to Windows Defender for inspection. I apologize for this failure.

It seems that Windows Defender will block anything that mentions pyinstaller...

**Comment by Enderbyte09** [comment]
Hello. Should I assume this version has been rejected (and go write some more updates and submit it again later)?

**Comment by stephengillie** [comment]
Sorry for the delay. `wingetbot run` wasn't listening to due to:

> Octokit was broken because comment id exceeded int maximum value for parsing JSON. A fix was submitted earlier, but we haven't got a NuGet package yet[.] 

- [@denelon on Gitter](https://matrix.to/#/!LEwByvxhTNZZcKeCCY:gitter.im/$c5J6uL4eU3A1Sy9vsPbUgBSahjnfLz6TDh98ZeW56G4?via=gitter.im&via=matrix.org&via=beeper.com)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
