### PR TITLE
Remove Systweak.DuplicateMusicFixer 2.1.1000.11070 to SystweakSoftware.DuplicateMusicFixer 2.1.1000.11070

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/149349)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://cdn.systweak.com/setups/baps/dmfsetup.exe 
Status Code: 200

(Automated message - build 876)

**Comment by stephengillie** [comment]
URL: https://cdn.systweak.com/setups/baps/dmfsetup.exe 
Status code: 200

(Automated message - build 661)

**Comment by stephengillie** [comment]
Hi @Trenly,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 876.)

**Comment by stephengillie** [comment]
URL: https://cdn.systweak.com/setups/baps/dmfsetup.exe 
Status Code: 200

(Automated message - build 876)

**Comment by stephengillie** [comment]
URL: https://cdn.systweak.com/setups/baps/dmfsetup.exe 
Status Code: 200

(Automated message - build 876)

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://cdn.systweak.com/setups/baps/dmfsetup.exe 
Status Code: 200

(Automated message - build 877)

**Comment by stephengillie** [comment]
URL: https://cdn.systweak.com/setups/baps/dmfsetup.exe 
Status Code: 200

(Automated message - build 877)

**Comment by stephengillie** [comment]
URL: https://cdn.systweak.com/setups/baps/dmfsetup.exe 
Status Code: 200

(Automated message - build 877)

**Comment by stephengillie** [comment]
URL: https://cdn.systweak.com/setups/baps/dmfsetup.exe 
Status Code: 200

(Automated message - build 877)

**Comment by stephengillie** [comment]
URL: https://cdn.systweak.com/setups/baps/dmfsetup.exe 
Status Code: 200

(Automated message - build 877)

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Sorry to let this get lost in the automation. I'm not sure why I removed the [Last-Version-Remaining](https://github.com/microsoft/winget-pkgs/labels/Last-Version-Remaining) label - I think I was going to switch this to [Highest-Version-Remaining](https://github.com/microsoft/winget-pkgs/labels/Highest-Version-Remaining) and got distracted.

**Pull request merged**
