### PR TITLE
Remove outdated version (0.7.1.0)

### PR DESCRIPTION
**Pull request by boergegrunicke**
The latest version is available in the Microsoft store, as the store is also used as source for winget, it is not necessary anymore, to provide it here as well.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/151614)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://languagetool.org/download/windows-desktop/Languagetool.Packaging_0.7.1.0/Languagetool.Packaging_0.7.1.0_x64.msixbundle 
OK

(Automated message - build 829)

**Comment by stephengillie** [comment]
Hi @boergegrunicke,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 878.)

**Comment by stephengillie** [comment]
URL: https://languagetool.org/download/windows-desktop/Languagetool.Packaging_0.7.1.0/Languagetool.Packaging_0.7.1.0_x64.msixbundle 
Status Code: 200

(Automated message - build 878)

**Comment by Trenly** [comment]
Even if an application is available in the `msstore` source, it is a good idea to keep in in this repo too, as there are several users who do not have the `msstore` source available or who have elected to remove it

**Comment by stephengillie** [comment]
URL: https://languagetool.org/download/windows-desktop/Languagetool.Packaging_0.7.1.0/Languagetool.Packaging_0.7.1.0_x64.msixbundle 
Status Code: 200

(Automated message - build 878)

**Comment by stephengillie** [comment]
URL: https://languagetool.org/download/windows-desktop/Languagetool.Packaging_0.7.1.0/Languagetool.Packaging_0.7.1.0_x64.msixbundle 
Status Code: 200

(Automated message - build 878)

**Comment by stephengillie** [comment]
URL: https://languagetool.org/download/windows-desktop/Languagetool.Packaging_0.7.1.0/Languagetool.Packaging_0.7.1.0_x64.msixbundle 
Status Code: 200

(Automated message - build 880)

**Comment by Trenly** [comment]
@stephengillie - Probably don't need to have your automation re-check this one each day

**Comment by stephengillie** [comment]
It shouldn't be rechecking each day. I think I may have found a bug, where I didn't have the .name property specified. Testing suggests that this was the cause, so hopefully the unnecessary checks will stop now.

**Comment by stephengillie** [comment]
URL: https://languagetool.org/download/windows-desktop/Languagetool.Packaging_0.7.1.0/Languagetool.Packaging_0.7.1.0_x64.msixbundle 
Status Code: 200

(Automated message - build 880)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
