### PR TITLE
JGraph.Draw version 20.2.3

### PR DESCRIPTION
**Pull request by C8H17OH**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/69614)

### CODE REVIEW

**Comment by C8H17OH** [comment]
I created this manifest by WinGet-Create 1.1.2.0, it generated a manifest with ManifestVersion 1.2.0, and your bots only accepts 1.0.0 and 1.1.0. LOL.

**Comment by C8H17OH** [comment]
BTW my all actions are:
- Call `wingetcreate update JGraph.Draw -v 20.2.3 -i`
- Copy urls from the software's official release page, and paste them into the terminal
- WinGet-Create reported manifest error.
- I checked the manifest, and found that an `x64` in the manifest of an older version was mistakenly changed to `x86`, for which I don't know why.
- I manually corrected the architecture above, and now the valiadation passed.
- Submit it here, and was told only older versions are accepted.

**Comment by russellbanks** [comment]
This is expected; the validation for 1.2.0 hasn't been turned on yet. You can either wait and the package will be accepted when it is (looking to be the end of the week), or change the manifest version to 1.1.0 manually.

**Comment by C8H17OH** [comment]
> This is expected; the validation for 1.2.0 hasn't been turned on yet. You can either wait and the package will be accepted when it is (looking to be the end of the week), or change the manifest version to 1.1.0 manually.

Thanks for your reply. Waiting for the update of turning on 1.2.0.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
