### PR TITLE
Update version: GiulioSorrentino.numeronesoeminformations version 1.1

### PR DESCRIPTION
**Pull request by GiulianoSpaghetti**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/119834)

### CODE REVIEW

**Comment by numerunix** [comment]
hello, the package works and is il it's simply blocked by smartscreen

**Comment by numerunix** [comment]
hello, the package works and is il it's simply blocked by smartscreen

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335187 
> 2023-09-15 02:03:45.452 [FAIL] Installer failed security check. Url: https://github.com/numerunix/numoeminformations/releases/download/1.1/numoeminformations-1.1.exe Result: 0x80004005 

Unfortunately, this package didn't pass the security check inside WinGet. This might be a false positive and we can retry tomorrow.

**Comment by numerunix** [comment]
Ok, then i'll not update pull request, but wait.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
