### PR TITLE
New version: WK.WKRadar version 7.12.0.0

### PR DESCRIPTION
**Pull request by ghost**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with winget validate --manifest <path>?
- [x] Have you tested your manifest locally with winget install --manifest <path>?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: <path> is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/175556)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/175896)

### CODE REVIEW

**Comment by WKSistemas** [comment]
@microsoft-github-policy-service agree company="WK Sistemas"

**Comment by henriqueazevedo1999** [comment]
Hi @stephengillie,

Is there any way to streamline the release process for new versions of our application on Winget? We've encountered the same internal pipeline errors during the last two releases, which I believe may be due to the size of the application. Both required manual intervention after retries failed.

Here are the relevant PRs for reference:
7.11: https://github.com/microsoft/winget-pkgs/pull/165291
7.10: https://github.com/microsoft/winget-pkgs/pull/152450

Any guidance on how we could avoid these issues or accelerate the validation process would be greatly appreciated.

**Comment by henriqueazevedo1999** [comment]
@stephengillie Looks like the bot got stuck in a loop

**Comment by stephengillie** [comment]
Hi @henriqueazevedo1999,

Sorry to miss your earlier reply amid the bot spam. 

> Is there any way to streamline the release process for new versions of our application on Winget? We've encountered the same internal pipeline errors during the last two releases, which I believe may be due to the size of the application. Both required manual intervention after retries failed.
> 
> Here are the relevant PRs for reference: 7.11: #165291 7.10: #152450
> 
> Any guidance on how we could avoid these issues or accelerate the validation process would be greatly appreciated.

The size of the installed applications on disk is very probably causing an issue. The validation VMs seem to have about 40 GB of total storage space. The only real way to avoid would be to slim down the footprint of the installed applications.

> @ stephengillie Looks like the bot got stuck in a loop

This is our "PR Cleaner" service, which retries erroring PRs on a regular basis. Sometimes, there's an ephemeral pipeline issue causing these errors, and this service is an attempt to mitigate.

**Review by stephengillie — APPROVED** [review]

**Comment by henriqueazevedo1999** [comment]
Hi @stephengillie,

Thank you for the clarification.

Our application requires about 8 GB of RAM and 20 GB of free disk space, which might be contributing to the issues during validation. Given the limitations of the validation VMs, is there any way we could adjust or configure the pipeline to better accommodate these requirements? Or perhaps there's something we could do on our side to avoid encountering these errors in future submissions?

Additionally, would it be possible to introduce a tag or identifier for PRs with large applications like ours? This could help flag them for special handling or manual review earlier in the process, preventing repetitive errors and retries.

We’re open to any suggestions to help smooth out the release process and prevent these recurring errors.

Thanks again for your support!

**Pull request merged**
