### PR TITLE
Update WindowsAdminCenter yaml to 1.2.2009.21002

### PR DESCRIPTION
**Pull request by donid**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3698)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
This installer is not working for me.
image

**Comment by donid** [comment]
I admit that I haven't actually tested the modified yaml because the old one used a version-agnostic download url, so I just 'fixed' the version number and hash. I also had not found this PR: https://github.com/microsoft/winget-pkgs/pull/2686 because it was already closed. Someone had tried the same with the '2007' version, as I did with '2009'.
I have no idea how to fix the error that is in the log: "CustomAction GenerateSslCertificate returned actual error code 1603"
But since WAC is a Microsoft product, maybe someone from the WAC-team might be interested to take a look?

**Comment by KevinLaMS** [comment]
this is still failing.  we will need to investigate.

**Comment by donid** [comment]
problem has been fixed in https://github.com/microsoft/winget-pkgs/pull/4205

**Pull request closed without merging**
