### PR TITLE
add androidstudio beta version 2020.3.1.19

### PR DESCRIPTION
**Pull request by bearmannl**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/19844)

### CODE REVIEW

**Comment by bearmannl** [comment]
For future reference, https://developer.android.com/studio/archive
I recommend going for the full version, not just major.minor, (ie. 2020.3.1.20 instead of 2020.3.1) as that'll cause trouble with new increments.

**Comment by vedantmgoyal2009** [comment]
#19840

**Comment by vedantmgoyal2009** [comment]
Are you in favour of this?

**Comment by bearmannl** [comment]
> Are you in favour of this?

I am not, besides not being able to 'recognize' the currently installed package in case you haven't updated yet, there is also the matter of wanting to install specific versions due to bugs in newer versions you might want to avoid.

And probably a dozen other reasons I'm missing right now.

**Comment by vedantmgoyal2009** [comment]
You are right. Keeping the latest Stable builds and then beta and canary builds. If you see builds more than a year old are present in this repository. I am talking about removing them.

**Comment by bearmannl** [comment]
> You are right. Keeping the latest Stable builds and then beta and canary builds. If you see builds more than a year old are present in this repository. I am talking about removing them.

I'm not sure why we would want to remove any versions. They're all meticulously organized in folders, so from a manageability perspective it isn't a problem. What's there to gain from removing older versions, other than 'clean-up'?

**Review by jedieaston — APPROVED** [review]

**Pull request merged**
