### PR TITLE
Remove version: TheDocumentFoundation.LibreOffice.SDK.LTS version 7.6.6.3

### PR DESCRIPTION
**Pull request by schembriaiden**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/162549)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://downloadarchive.documentfoundation.org/libreoffice/old/7.6.6.3/win/x86/LibreOffice_7.6.6.3_Win_x86_sdk.msi 
OK

(Automated message - build 911)

**Comment by stephengillie** [comment]
Hi @vikingnope,

This package is still available - was it actually EOL'd?

**Comment by vikingnope** [comment]
Hiya @stephengillie,

I would think that since their normal subsequent versions were EOL'd both the SDK and the Help Pack would be EOL'd since they correspond to them

**Comment by stephengillie** [comment]
URL: https://downloadarchive.documentfoundation.org/libreoffice/old/7.6.6.3/win/x86/LibreOffice_7.6.6.3_Win_x86_sdk.msi 
Status Code: 200

(Automated message - build 886)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
