### PR TITLE
Remove unneccessary AppsandFeaturesEntries * manifests/v/VB-Audio/Voicemeeter/Potato/3.1.1.8/VB-Audio.Voicemeeter.Potato.installer.yaml

### PR DESCRIPTION
**Pull request by Trenly**

### CODE REVIEW

**Review by mdanish-kh — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 899.)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 900)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 902)

**Pull request merged**
