### PR TITLE
Microsoft.Git version 2.47.0.0.2

### PR DESCRIPTION
**Pull request by ldennington**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/184159)

### CODE REVIEW

**Review by derrickstolee — APPROVED** [review]
Approving as a way of saying that this release was generated by real humans.

**Comment by derrickstolee** [comment]
@stephengillie: I am once again requesting manual checks for this package, similar to those needed for #167577.

**Comment by dscho** [comment]
@stephengillie it seems that this validation, as pretty much _all_ previous Microsoft.Git validations, has failed.

Is there anything I can do on my side to remedy this unfortunate pattern?

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Comment by stephengillie** [comment]
Hi @derrickstolee and @dscho, 
CC @denelon 

- Manual Validation has just completed for this package. 
  - My above re-run of the PR was caused by my automation, which runs at :20 minutes after the hour. 
- This package, as well as most `Git` packages, receives the https://github.com/microsoft/winget-pkgs/labels/Internal-Error-Dynamic-Scan label because it uses components that the pipeline also uses. Please see this Discussion for more details: https://github.com/microsoft/winget-pkgs/discussions/155218
- For now, the best solution that I have is to let the pipelines run once, and if this label is reached, then @ me to manually validate.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
