### PR TITLE
Remove: SimonG4ELI.SDR-Radio.Beta version 3.3-b3195

### PR DESCRIPTION
**Pull request by AsciiWolf**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

The SDR-Radio Beta was replaced by the 3.3 stable build and is not useful anymore. Please merge this PR after #137972 gets merged.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137975)

### CODE REVIEW

**Comment by AsciiWolf** [comment]
The error is most likely caused by the _.validation_ file that I also removed. This is intentional, I removed the whole "Beta" folder since I don't plan to publish Beta releases of SDR-Radio on Winget anymore now that the stable (3.3) LTS release with silent installation support is out.

@stephengillie Feel free to waive. ;-)

**Comment by Trenly** [comment]
@asciiwolf - The publishing pipeline will error if the .validation is removed with a manifest; If you put the .validation back, Stephen can do the manual approval for a separate PR and it won't break anything

**Review by Trenly — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-08T16:09:27.4017913Z ##[error] One or more errors occurred. (Sequence contains no elements) Sequence contains no elements

(Automated response - build 714.)

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 714.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
