### PR TITLE
Faithlife.Logos version 23.1.0.0033

### PR DESCRIPTION
**Pull request by torculus**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/97694)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @ torculus,

The package prompts for language:
image

I wasn't able to find an installer switch to clear this. Are you aware of one?

**Comment by torculus** [comment]
Unfortunately, I'm not aware of all of the possible installer switches. Is there a way to re-submit this as "needing user interaction" ?

**Comment by stephengillie** [comment]
> Unfortunately, I'm not aware of all of the possible installer switches. Is there a way to re-submit this as "needing user interaction" ?

Yes - this PR is blocked by:
* https://github.com/microsoft/winget-cli/issues/910

**Comment by stephengillie** [comment]
No recent activity.

**Pull request closed without merging**
