### PR TITLE
GiulioSorrentino.Latorredibabele version 3.0

### PR DESCRIPTION
**Pull request by GiulianoSpaghetti**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/144100)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-12 17:53:40.747 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFB2F5FC11F: (caller: 00007FFB2F388D6F) LogHr(1) tid(414) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFB2F502B08: (caller: 00007FFB2F5ABC20) Exception(1) tid(414) 8A15005E ] 
> 2024-03-12 17:53:40.747 [REPO] Failed to open available source: msstore
> 2024-03-12 17:53:43.650 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFB2F502B08: (caller: 00007FFB2F5ABC20) Exception(1) tid(414) 8A15005E 
> 2024-03-12 17:53:51.692 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFB1A60C11F: (caller: 00007FFB1A398D6F) LogHr(1) tid(8d0) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFB1A512B08: (caller: 00007FFB1A5BBC20) Exception(1) tid(8d0) 8A15005E ] 
> 2024-03-12 17:53:51.692 [REPO] Failed to open available source: msstore
> 2024-03-12 17:54:54.805 [FAIL] Installer failed security check. Url: https://github.com/numerunix/Solitario.Avalonia/releases/download/3.0/Solitario.Avalonia-3.0-amd64.msi Result: 0x80004005
> MSI (s) (0C:98) [17:54:08:650]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1)
> MSI (s) (0C:98) [17:54:10:806]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,)
> Property(S): ErrorDialog = ErrorDlg

(Automated response - build 870.)

**Comment by numerunix** [comment]
it's the smart screen

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-13 12:32:43.742 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFB1F40C11F: (caller: 00007FFB1F198D6F) LogHr(1) tid(964) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFB1F312B08: (caller: 00007FFB1F3BBC20) Exception(1) tid(964) 8A15005E ] 
> 2024-03-13 12:32:43.742 [REPO] Failed to open available source: msstore
> 2024-03-13 12:32:46.019 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFB1F312B08: (caller: 00007FFB1F3BBC20) Exception(1) tid(964) 8A15005E 
> 2024-03-13 12:32:52.542 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFB079EC11F: (caller: 00007FFB07778D6F) LogHr(1) tid(1564) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFB078F2B08: (caller: 00007FFB0799BC20) Exception(1) tid(1564) 8A15005E ] 
> 2024-03-13 12:32:52.542 [REPO] Failed to open available source: msstore
> 2024-03-13 12:33:56.501 [FAIL] Installer failed security check. Url: https://github.com/numerunix/Solitario.Avalonia/releases/download/3.0/Solitario.Avalonia-3.0-amd64.msi Result: 0x80004005
> MSI (s) (10:F0) [12:33:07:705]: Executing op: ComponentRegister(ComponentId={7D8F811F-FA90-5B50-B79B-7BEBC828F0A0},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1)
> MSI (s) (10:F0) [12:33:09:392]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,)
> Property(S): ErrorDialog = ErrorDlg

(Automated response - build 870.)

**Comment by numerunix** [comment]
Smart screen, i suppose

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
