### PR TITLE
rstudio.quarto does not need Scope option in the manifest

### LINKED ISSUE #67560: [Package Issue]: cannot upgrade rstudio.quarto with `winget upgrade rstudio.quarto`
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

The `winget upgrade quarto` command does not install the latest version of quarto.

### Steps to reproduce

```powershell
winget install quarto -v 1.0.36
winget upgrade quarto
```

### Actual behavior

The `winget upgrade quarto` command does not install the latest version of quarto.

### Expected behavior

Installing the latest version, which was listed by `winget upgrade`.

### Environment

```shell
winget --info
Windows パッケージ マネージャー v1.2.11601
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.795
パッケージ: Microsoft.DesktopAppInstaller v1.17.11601.0
```

### Screenshots and Logs

_No response_

### PR DESCRIPTION
**Pull request by cderv**
This prevents correct update. fix  #67560

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by denelon** [comment]
@cderv can quarto be installed in both user and machine? If that's the case, it might be better to add two installer nodes, one for each scope. The Windows Package Manager can look at registry keys to determine which scope is installed and perform the appropriate upgrade action accordingly. We needed to do something similar for [Microsoft.EdgeWebView2Runtime](https://github.com/microsoft/winget-pkgs/blob/5f16647ce8fdba119e7f3e4eb2b29908807053bc/manifests/m/Microsoft/EdgeWebView2Runtime/103.0.1264.71/Microsoft.EdgeWebView2Runtime.installer.yaml#L15-L45)

**Comment by cderv** [comment]
@denelon yes I think Quarto can be installed in both mode
image

I had Scope user at first to make that happen at the default, which is the default when installing interactively but I may be missing an installer switch (`InstallerSwitches` ? )

From log shared in #67560 it seems when installed with `winget` the machine scope was used by default. 

Do you know about default winget behavior and possible installer flag that should be used ? Is `winget install --scope machine` the default ? 

I am happy to create several install manifest - just need to do it correctly and maybe changing the Scope value in manifest is not enough ?

**Comment by denelon** [comment]
@cderv We would normally default to "user" mode unless specified as an argument or setting on the user's machine if both are present. In some cases, running an installer via Windows Package Manager in administrator mode would default to system unless "user" is specified and there is an argument we can pass to the installer.

When we're performing an "upgrade" we check to see which registry keys are present and attempt to honor that mode of installation. Challenges usually end up being the requirement for Administrator or UAC to get the right behavior as the EdgeWebView2Runtime manifest shows.

Installers can be quite tricky to contend with, and I've been working to compile some best practices around Windows Package Manager behavior, and how one can attempt to get their installer to be "[well behaved](https://github.com/microsoft/winget-cli/discussions/2110)". The current best practice if reasonable is to package as an [MSIX](https://docs.microsoft.com/windows/msix/). Other formats are clearly supported in Windows Package Manager, but there are many edge cases to contend with.

**Comment by cderv** [comment]
Thanks a lot. I think I need to check how we are packaging our tool really.

**Pull request merged**
