### PR TITLE
New package: Stellantis.PeugeotUpdate version 1.5.2

### PR DESCRIPTION
**Pull request by MaanuelMM**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136908)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @MaanuelMM,

It appears that entering a valid VIN is required to view the software link on the ISV's website. Is this correct?

As a guideline for packages, anyone should be able to navigate from the PackageUrl to the InstallerUrl at any time, from almost any terrestrial location. Here, the InstallerUrl appears to be hidden. 

If I missed it somewhere else on the page, could you help me find it?

**Comment by MaanuelMM** [comment]
First of all, sorry for the delay in providing comments on the suspicious domain of the installers of all these Stellantis apps.

Regarding your question: yes, it is true that the URL is "hidden" under a query involving the VIN of the vehicle and, in my case, I can provide direct links to both [Peugeot](https://www.peugeot.es/content/dam/peugeot/master/media/majesticinstaller/peugeot_update.exe) and [Citroën](https://www.citroen.es/content/dam/citroen/master/media/majestic-installer/Citroen_Update_Setup_0.1.24.exe) installers. These executables, however, despite being under the Peugeot and Citroën web domains, are outdated versions (`1.3.1`).

As far as I know, every Electron app that make use of `electron-builder` requires the `app-update.yml` under the `resources` folder to be able to auto-update. In that file, there's an URL where the app will check for future updates, however, this is where things get complicated (I'll take **_Citroën Update_** as an example):

Since `1.4.0`, the following `app-update.yml` is bundled with the app:

```yml
provider: generic
url: https://d1tik0o5ahgjm.cloudfront.net/citroen/
updaterCacheDirName: connect_update-updater
publisherName:
  - PSA Automobiles SA
  - Stellantis N.V.
```

However, prior to that version (e.g. `1.3.1`), this was the bundled `app-update.yml`:

```yml
provider: generic
url: 'https://citroen-update.cppv2.awsmpsa.com/'
updaterCacheDirName: connect_update-updater
publisherName:
  - PSA Automobiles SA
  - Stellantis N.V.
```

As you can see in the old version, depending on the _'flavour'_ (car brand) of the `Connect Update` app, the URL would be different (there's a compilation of old download links [here](https://www.peugeotforums.com/threads/nav-map-update-24-0-0-r0-22-11-2022-3008.364979/post-2388432)). Now, they're using the exact same (sub)domain (`https://d1tik0o5ahgjm.cloudfront.net/<car_brand>/`) but just chaning the URL prefix for each car brand.

Now comes the fun part: it turns out that these old links no longer work and that's because there have been changes in the _PSA/Stellantis_ API several months ago that have made these links no longer available. This have made installations older than `1.4.0` no longer "upgradeable", hence my motivation for these pull requests so that those using WinGet can upgrade their current installations (in fact, it's also impossible to perform a clean install of any version newer than `1.3.1` if you don't know this URL, a mistake by Stellantis I still can't understand and I hope they'll fix in the near future).

Now, the tricky part is to prove the veracity of this URL, and this is where I will rely on VirusTotal to demonstrate, first of all, the existence of version `1.4.0` under the old and extinct URL and, consequently, that the web domain changed, thus being able to draw a clear relationship between the currently available version `1.3.1` and the current version `1.5.2` with the new URL:

1. Download [Citroën Update 1.3.1](https://www.citroen.es/content/dam/citroen/master/media/majestic-installer/Citroen_Update_Setup_0.1.24.exe) from Citroën website and open it with a file archiver (e.g. _WinRAR_).

3. Locate `app-update.yml` under the `resources` folder and extract it.

5. Open the extracted file and verify that the included URL is `https://citroen-update.cppv2.awsmpsa.com/`.

7. Now, go to [VirusTotal](https://www.virustotal.com/gui/home/url) and search for this URL: `https://citroen-update.cppv2.awsmpsa.com/Citroen_Update_Setup_0.1.24.exe` (this is where the version `1.4.0` was available not so long ago).

9. Go to `Body SHA-256` under the `Details` tab and click on the value (must be `f9da18af23437365dcd3c7ebefbf2d693365de00c74b95ae4e1cb3e85dfae954`). This will redirect you to the file/body details.
image

10. Now, under the `Relations` tab, search for `app-update.yml` on `Dropped files` (SHA-256 must be `b01b8b397c1af5ce771f1c0dbaea2bd61e646abd71b812d048a93b603f7fd160`).
image

Now, knowing the hash of `app-update.yml` on version `1.4.0`, we can do two different things to prove the veracity of the newer URL:

1. Modify the `app-update.yml` from `Citroën Update 1.3.1` replacing `'https://citroen-update.cppv2.awsmpsa.com/'` with `https://d1tik0o5ahgjm.cloudfront.net/citroen/`, then calculate the SHA-256 file hash and verify that it's the exact same as in version `1.4.0`.

2. Download [Citroën Update 1.5.2](https://d1tik0o5ahgjm.cloudfront.net/citroen/Citroen_Update_Setup_0.1.24.exe) from the newer URL and extract `app-update.yml` under the `resources` folder as we did with version `1.3.1`, then calculate the SHA-256 file hash and verify that it's the exact same as in version `1.4.0`. We must also verify that the included URL is the newer one.

In fact, it is important to mention that the installer that is coming from the new URL is digitally signed with a valid signature of Stellantis N.V. (according to [VirusTotal](https://www.virustotal.com/gui/file/1f6b96468350e2b0831b3455dde438db08c862dc9104f711c23ea1f499d52e7b/details)) and that inside the installer there is an `app-update.yml` file with exactly the same URL from which the file has been downloaded, so that should be proof enough that it is the original source (i.e. one cannot be given without the other).

**Comment by stephengillie** [comment]
@MaanuelMM,

Thank you for the very thorough and detailed reply, with how exactly to locate and verify each URL. Unfortunately it's just a bit more complex than our policies currently support.

**Comment by MaanuelMM** [comment]
@stephengillie
I'll temporarily close these PRs until something changes on Stellantis end just to have a clearer and not so convoluted justification. Appreciated.

**Pull request closed without merging**
