### PR TITLE
New version: Microsoft.OneDrive version 22.002.0103.0004

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/41929)

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]

**Comment by OfficialEsco** [comment]
still none going trough the OneDrive PRs.. @denelon

**Comment by denelon** [comment]
@yao-msft is primary "on-call" today and @ryfu-msft is backup.

**Comment by vedantmgoyal2009** [comment]
Does something exist like whitelisting a package?

**Comment by denelon** [comment]
> Does something exist like whitelisting a package?

No, we need to perform validations. OneDrive has some specific challenges that we still need to manually validate and approve.

**Pull request merged**
