### PR TITLE
TcNoAccountSwitcher

### PR DESCRIPTION
**Pull request by GrPK**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/174985)

### CODE REVIEW

**Comment by GrPK** [comment]
@microsoft-github-policy-service agree

**Comment by GrPK** [comment]
Any way to fix this? I already submitted a feedback that the link is safe (is the official github one) but till now no answer

**Comment by stephengillie** [comment]
Unfortunately, the report is the only way of which I'm aware to unblock this PR.

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Comment by ItzLevvie** [comment]
Close with reason: Duplicate of PR 172271;

**Pull request closed without merging**
