### PR TITLE
New version: FlightGear.FlightGear version 2020.3.17

### PR DESCRIPTION
**Pull request by The-Fl3dd0x**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest manifests\f\FlightGear\FlightGear\2020.3.17`?
- [x] Have you tested your manifest locally with `winget install --manifest manifests\f\FlightGear\FlightGear\2020.3.17`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/98648)

### CODE REVIEW

**Comment by The-Fl3dd0x** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
This package is 1.77 GB and the download appears throttled, as it downloads significantly faster through Edge. These are complicating validation and causing it to take longer than usual.

**Comment by The-Fl3dd0x** [comment]
I wonder why the other versions worked, but thanks for looking into it!

**Comment by stephengillie** [comment]
> I wonder why the other versions worked, but thanks for looking into it!

Oh - I failed to note that this is an upgrade for a package already among the public manifests. Apologies.

**Comment by The-Fl3dd0x** [comment]
No problem, it seems to an issue with the installer though, as other people are also missing the MSVC Runtimes. I'll try it with the next version, but test it in the sandbox beforehand.

**Comment by The-Fl3dd0x** [comment]
Maybe providing a mirror instead of the main download link helps, with this one I get 22 MByte/s: https://deac-riga.dl.sourceforge.net/project/flightgear/release-2020.3/FlightGear-2020.3.17.exe

**Comment by The-Fl3dd0x** [comment]
Alternatively, there also is a very small (60.5 MB) web installer

**Comment by stephengillie** [comment]
The manifest would need to be updated with them.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
After preinstalling the dependency and leaving the download running overnight, I was able to validate the package. This is apparently just an update package and stub to download the main files - which is apparently normal package operation. 
image

The only remaining concern is that the dependency wouldn't automatically install for users installing this upgrade. Once dependency support is in place, this won't be a problem.

**Comment by The-Fl3dd0x** [comment]
Great, is the dependency issue resolved?

**Comment by The-Fl3dd0x** [comment]
I think this can be closed, as there is a newer version merged.

**Pull request closed without merging**
