### PR TITLE
Updated Google.Chrome to version 91.0.4472.164

### PR DESCRIPTION
**Pull request by ImJoakim**
image

```
PS C:\Users\WDAGUtilityAccount\Desktop\manifests> winget install -m "C:\Users\WDAGUtilityAccount\Desktop\manifests\g\Google\Chrome\91.0.4472.164"
Found Google Chrome [Google.Chrome]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise64.msi
  ██████████████████████████████  75.2 MB / 75.2 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

image

```
PS C:\Users\WDAGUtilityAccount\Desktop\manifests> winget install -m "C:\Users\WDAGUtilityAccount\Desktop\manifests\g\Google\Chrome\91.0.4472.164"
Found Google Chrome [Google.Chrome]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi
  ██████████████████████████████  72.7 MB / 72.7 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/21174)

### CODE REVIEW

**Comment by ImJoakim** [comment]
This might fail because of cache, but we'll see.

**Comment by ImJoakim** [comment]
Might work now

**Comment by ImJoakim** [comment]
Guess not, I'll try again a little later.

**Comment by ImJoakim** [comment]
👌

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
