### PR TITLE
Fix SHA256 Hash For CCleaner 5.69

### PR DESCRIPTION
**Pull request by neomedved**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3228)

### CODE REVIEW

**Comment by neomedved** [comment]
Strange, works fine for me.

**Comment by perplexityjeff** [comment]
@neomedved It seems that SmartScreen got triggered? At least as far as I can find out from the results. 

The hash change is accurate I see that the hash should indeed be what you are suggesting. 

Also I tested the file with the new change and all seems to install just fine.

image

**Comment by neomedved** [comment]
@perplexityjeff any idea how to fix this?

**Comment by perplexityjeff** [comment]
I think some feedback from the team is required. It seems all fine on my end.

**Comment by perplexityjeff** [comment]
@KevinLaMS, @denelon I think we require some help here. The manifest seems to be correct from what we both can see and the hash change of @neomedved is correct. 

How can we move forward?

**Pull request merged**
