### PR TITLE
Add PUBGLite 1.0.1.0

### PR DESCRIPTION
**Pull request by KaranKad**
- [yes] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [yes] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [yes] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [yes] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3730)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
The app does not run if cruntime is missing.

**Comment by KaranKad** [comment]
Oh right, I had previously installed this app along with [vc_redist.x64.exe](https://aka.ms/vs/16/release/vc_redist.x64.exe) that's why it worked fine for me, the download site for this app also says that you need .NET Framework 4.5.2 and DirectX 11 but I guess most of the pc's have that installed already. Guess this app will have to wait until dependencies are supported.
Thanks for the feedback.

**Comment by KevinLaMS** [comment]
sorry if this validation got triggered again accidentally.  i am still seeing the vcruntime error.

**Comment by KaranKad** [comment]
I'm sorry I was trying to update my fork but in the process I messed up something. Its ok now.

**Pull request closed without merging**
