### PR TITLE
New package: Fendapp.Fendapp version 0.1.5

### PR DESCRIPTION
**Pull request by JadedBlueEyes**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/149569)

### CODE REVIEW

**Comment by JadedBlueEyes** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files\FendApp\fendapp.exe returned exit code: -1073741515

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files\FendApp\fendapp.exe returned exit code: -1073741515

(Automated response - build 877.)

**Review by stephengillie — CHANGES_REQUESTED** [review]
Hi @JadedBlueEyes,

This package appears to have a dependency:

image

After adding the suggested dependency, running the application, from shortcut or Explorer, or PowerShell, had no visible output. Is this expected?

**Comment by JadedBlueEyes** [comment]
> This package appears to have a dependency

I was working on this, thank you for the change suggestion!

> After adding the suggested dependency, running the application, from shortcut or Explorer, or PowerShell, had no visible output. Is this expected?

No, this isn't expected. Running on both my machine and in a sandbox appears to work correctly for me:

image

Do you have any ideas as to what it might be? I'm coming up blank - everything else is statically linked, and it doesn't require downloading any files to start up.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-04-18 22:58:45.807 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFCEBA1C11F: (caller: 00007FFCEB7A8D6F) LogHr(1) tid(1710) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFCEB922B08: (caller: 00007FFCEB9CBC20) Exception(1) tid(1710) 8A15005E ] 
> 2024-04-18 22:58:45.807 [REPO] Failed to open available source: msstore
> 2024-04-18 22:58:53.523 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFCD29EC11F: (caller: 00007FFCD2778D6F) LogHr(1) tid(c8c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFCD28F2B08: (caller: 00007FFCD299BC20) Exception(1) tid(c8c) 8A15005E ] 
> 2024-04-18 22:58:53.524 [REPO] Failed to open available source: msstore
> 2024-04-18 22:58:54.550 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x64 with version 14.38.33135.0

(Automated response - build 877.)

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/149642

**Pull request closed without merging**
