### PR TITLE
Update: KDE.kdevelop version 5.6.2 [FP-D]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | KDevelop | KDevelop    |
| Version     | 5.6.2     | 5.6.2 |
| Publisher   | KDE e.V.   | KDE e.V.      |
| ProductCode |           | KDevelop    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://bittu.eu.org/docs/wpa-intro) in workflow run [3338](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/3164927831>)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]
Error is due to a WinGet bug: https://github.com/microsoft/winget-cli/issues/2057

**Comment by vedantmgoyal2009** [comment]
bump

**Pull request merged**
