### PR TITLE
PocketSync 4.12.0 can be installed via a silent switch

### PR DESCRIPTION
**Pull request by shock0572**
This pull requests manage to fix my previous ones:

https://github.com/microsoft/winget-pkgs/pull/173037
https://github.com/microsoft/winget-pkgs/pull/174509

It uses a proper moniker (the product is pocketsync, so analogue-pocket-sync, analogue pocket is just the console)
The reason I excluded it could have silent install available from the start was about the naming in the release page of the source repo (the github-action for tauri is supposed to append .nsis.exe to it)
After having it tested, it installs properly with the silent flag (/S)
```
.\Pocket.Sync_4.12.1_x64-setup.exe /S

PS C:\Users\enaselli\AppData\Local\Pocket Sync> dir

    Directory: C:\Users\enaselli\AppData\Local\Pocket Sync

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          12/09/2024    23:12       17800192 Pocket Sync.exe
-a---          26/09/2024    16:17          76266 uninstall.exe

```

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/175276)

### CODE REVIEW

**Comment by shock0572** [comment]
@stephengillie is it possible to waiver this correction for both packages at once?

**Comment by stephengillie** [comment]
Hi @shock0572,

Unfortunately, https://github.com/microsoft/winget-pkgs/pull/125 has not yet been completed. Moving either of these manifests to another PR should allow both PRs to pass this check.

**Comment by shock0572** [comment]
@stephengillie I've deleted the manifest and moved the 4.12.1 to another PR, I think the pipeline needs to be booted up again here?

**Comment by shock0572** [comment]
reopening new

**Pull request closed without merging**
