### PR TITLE
Move CCleaner to Piriform and update yaml

### PR DESCRIPTION
**Pull request by NathanBnm**
Piriform Software is not appropriate. It should be Piriform only so I made the changes. I updated CCleaner details too.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/308)

### CODE REVIEW

**Comment by NathanBnm** [comment]
Checks are saying that they are two manifests but it's not really the case it's because I moved one from a folder to another.

**Comment by NathanBnm** [comment]
@delenon

**Comment by superusercode** [comment]
not sure what change you made to presencelight (seen https://github.com/microsoft/winget-pkgs/pull/308/files) but maybe if you redo it it won't warn?

**Comment by NathanBnm** [comment]
@superusercode didn't noticed that it changed the presencelight manifest this IS really strange. I didn't touch it at all I don't even know the software 😂 I'll check

**Pull request closed without merging**
