### PR TITLE
New version: Overmind.OvermindCLI 1.0.0

### PR DESCRIPTION
**Pull request by dylanratcliffe**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/157392)

### CODE REVIEW

**Comment by dylanratcliffe** [comment]
Hey moderators! This package also failed previously [here](https://github.com/microsoft/winget-pkgs/pull/157354), not sure if that's related to this failure. I couldn't see an error message or work out why in the previous one. I've tested locally and everything seems to work fine, it installs and I can use the CLI fine afterwards, so not really sure where to go with this. Any help would be appreciated

**Comment by dylanratcliffe** [comment]
Hey @stephengillie is there anywhere I can find more information on why this has failed? I googled the error codes and couldn't find anything, and ran the files through virustotal in case there are some detections for some reason but they came back clean:

* [zip file](https://www.virustotal.com/gui/file/d33c5f7ebe162924050ef52649294baaca0f9547ea617a3582a8bb5ac02ea9a0)
* [unzipped exe](https://www.virustotal.com/gui/file/1086aa88428f015090f54bcc9dcf9379c0f16c68f6d8cb77f526aee380cd0139)

Is there anywhere I should be looking to resolve this?

**Comment by stephengillie** [comment]
Hi @dylanratcliffe,

I'm not entirely sure, but I believe that if VirusTotal marked it as clean, then it might be just a matter of time for this data to become available to the copies of Defender running on pipeline VMs. This is generally the course of action needed to pass this check - work with the Defender systems to pass the application, then these should pass the pipeline check. (It's the same Defender scan you can run on your PC.)

**Comment by dylanratcliffe** [comment]
@stephengillie Okay perfect, I've scanned all of the files form all of the releases with Windows Defender this morning and there haven't been any detections, so do I just wait and it'll re-run and maybe pass?

**Comment by dylanratcliffe** [comment]
Ah okay let me release a new version where the version matches, thanks for all your help!

**Pull request closed without merging**
