### PR TITLE
New version: Tencent.QQ version 9.7.11.29084

### PR DESCRIPTION
**Pull request by SpecterShell**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/111207&drop=dogfoodAlpha

### CODE REVIEW

**Comment by lychichem** [comment]
qq just released version 9.9.0.14569 (32 bit and 64bit), could you please write manifest for this version?

**Review by stephengillie — APPROVED** [review]

**Comment by SpecterShell** [comment]
> qq just released version 9.9.0.14569 (32 bit and 64bit), could you please write manifest for this version?

I can not find any switches for that version.

**Comment by lychichem** [comment]
> > qq just released version 9.9.0.14569 (32 bit and 64bit), could you please write manifest for this version?
> 
> I can not find any switches for that version.

I haven't tested either, maybe /s will be ok?

**Comment by SpecterShell** [comment]
> > > qq just released version 9.9.0.14569 (32 bit and 64bit), could you please write manifest for this version?
> > 
> > 
> > I can not find any switches for that version.
> 
> I haven't tested either, maybe /s will be ok?

Nope

**Pull request merged**
