### PR TITLE
JackieLiu.NotepadsApp version 1.4.5.0

### PR DESCRIPTION
**Pull request by denelon**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/13473)

### CODE REVIEW

**Comment by denelon** [comment]
@OfficialEsco I did a search earlier and didn't see Notepads. I saw a presentation today and built this manifest with an early preview of the new wingetcreate tool (to be released soon[tm]). The metadata was pulled from the MSIX (except for the moniker). Do you want me to delete this or migrate the manifests here? You've clearly done more work on this package than I have.

**Comment by OfficialEsco** [comment]
Huh, what did you search for? and why is it NotepadsApp? Also the publisher for this is sorta all over the place, I've seen **Notepads** (the WebSite), **UWP Community** (their Launch project) and **JasonStein** (main author).

You do what you feel is the best way to go about it :) Aslong as we can easily update the Package before your secret weapon is ready 😄

**Comment by denelon** [comment]
@OfficialEsco I think it was a PEBCAK on my part for the search. "NotepadsApp" is what we pulled from the .msix package metadata. The publisher was also selected from the .msix package metadata.

Our new tool will respect metadata in current manifests with the upgrade command used to add new versions.

We're debating the architecture choice regarding whether or not we split them out when generating a manifest from a .msix package. There are lots of variables to consider in a world of different installer choices. I've already come across one with an MSI that essentially does an "in place" upgrade for versions, but the same package has .exe installers that run side-by-side. I've been experimenting with support for multiple installer types for the same version of a package. We've had users who would like to only allow .msix, and for certain developer scenarios it makes sense to let them choose another installer type.

**Pull request merged**
