### PR TITLE
New version: Fndroid.ClashForWindows version 0.19.28

### PR DESCRIPTION
**Pull request by Fndroid**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/72137)

### CODE REVIEW

**Comment by russellbanks** [comment]
@vedantmgoyal2009, I don't think WinGet Releaser has handled the [line ending change](https://github.com/microsoft/winget-pkgs/pull/71918) well

**Comment by vedantmgoyal2009** [comment]
I guess I can fix line endings manually, along with updating the script.

**Comment by russellbanks** [comment]
> I guess I can fix line endings manually, along with updating the ~script~ schema.

I made an issue before I read your comment, so close that with the fixing commit

**Comment by vedantmgoyal2009** [comment]
cc @russellbanks

**Comment by vedantmgoyal2009** [comment]
You're too fast 😆

**Pull request closed without merging**
