### PR TITLE
New version: Bedrock-OSS.regolith version 1.3.0

### LINKED ISSUE #161704: [Update Request]: Bedrock-OSS/regolith to 1.3.0
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Bedrock-OSS.regolith

### Package Version

1.3.0

### Please describe the changes you would like to see

There is a new release available.
- **Download link:** https://github.com/Bedrock-OSS/regolith/releases/download/1.3.0/regolith-1.3.0.msi
- **Related Pull Request:** https://github.com/microsoft/winget-pkgs/pull/161700

### PR DESCRIPTION
**Pull request by Nusiq**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.
---
Resolve #161704
---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161700)

### CODE REVIEW

**Comment by Dragon1573** [comment]
Hi @Nusiq, 👋🏼

could you please add following contents to your [first comment](https://github.com/microsoft/winget-pkgs/pull/161700#issue-2393083224)? This can link this PR to the issue and automatically close issue as completed when this PR is merged. This can also prevent other contributors from wasting their time creating duplicate PRs. ❤️

```markdown
Resolve #161704
```

**Comment by Nusiq** [comment]
> Hi @Nusiq, 👋🏼
> 
> could you please add following contents to your [first comment](https://github.com/microsoft/winget-pkgs/pull/161700#issue-2393083224)? This can link this PR to the issue and automatically close issue as completed when this PR is merged. This can also prevent other contributors from wasting their time creating duplicate PRs. ❤️
> 
> ```
> Resolve #161704
> ```

Done

**Comment by Trenly** [comment]
> 2024-07-06 19:24:05.223 [FAIL] Installer failed security check. Url: https://github.com/Bedrock-OSS/regolith/releases/download/1.3.0/regolith-1.3.0.msi Result: 0x80004005

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-07-08 07:34:52.095 [FAIL] Installer failed security check. Url: https://github.com/Bedrock-OSS/regolith/releases/download/1.3.0/regolith-1.3.0.msi Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 886.)

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/pull/162185 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#162185 opened 20 hours ago by [wingetbot](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3Awingetbot)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/162185#partial-pull-merging)
[ 4](https://github.com/microsoft/winget-pkgs/pull/162185)

https://github.com/microsoft/winget-pkgs/pull/162183 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#162183 opened 20 hours ago by [wingetbot](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3Awingetbot)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/162183#partial-pull-merging)
[ 6](https://github.com/microsoft/winget-pkgs/pull/162183)

https://github.com/microsoft/winget-pkgs/pull/162167 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Manifest-Metadata-Consistency](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AManifest-Metadata-Consistency) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#162167 opened yesterday by [AClark-WHONET](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3AAClark-WHONET)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/162167#partial-pull-merging)
7 tasks done
[ 5](https://github.com/microsoft/winget-pkgs/pull/162167)

https://github.com/microsoft/winget-pkgs/pull/162164 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#162164 opened yesterday by [wingetbot](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3Awingetbot)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/162164#partial-pull-merging)
[ 6](https://github.com/microsoft/winget-pkgs/pull/162164)

https://github.com/microsoft/winget-pkgs/pull/162160 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#162160 opened yesterday by [wingetbot](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3Awingetbot)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/162160#partial-pull-merging)
[ 10](https://github.com/microsoft/winget-pkgs/pull/162160)

https://github.com/microsoft/winget-pkgs/pull/162141 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#162141 opened yesterday by [edwardskrod](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3Aedwardskrod)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/162141#partial-pull-merging)
7 tasks
[ 6](https://github.com/microsoft/winget-pkgs/pull/162141)

https://github.com/microsoft/winget-pkgs/pull/162112 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#162112 opened yesterday by [dotnet-winget-bot](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3Adotnet-winget-bot)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/162112#partial-pull-merging)
7 tasks
@stephengillie
[ 6](https://github.com/microsoft/winget-pkgs/pull/162112)

https://github.com/microsoft/winget-pkgs/pull/162105 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#162105 opened yesterday by [dotnet-winget-bot](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3Adotnet-winget-bot)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/162105#partial-pull-merging)
7 tasks
[ 8](https://github.com/microsoft/winget-pkgs/pull/162105)

https://github.com/microsoft/winget-pkgs/pull/162102 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#162102 opened yesterday by [dotnet-winget-bot](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3Adotnet-winget-bot)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/162102#partial-pull-merging)
7 tasks
@stephengillie
[ 6](https://github.com/microsoft/winget-pkgs/pull/162102)

https://github.com/microsoft/winget-pkgs/pull/162100 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#162100 opened yesterday by [dylanratcliffe](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3Adylanratcliffe)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/162100#partial-pull-merging)
7 tasks
@stephengillie
[ 6](https://github.com/microsoft/winget-pkgs/pull/162100)

https://github.com/microsoft/winget-pkgs/pull/162067 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#162067 opened yesterday by [oo-cmatuschka](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3Aoo-cmatuschka)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/162067#partial-pull-merging)
[ 13](https://github.com/microsoft/winget-pkgs/pull/162067)

https://github.com/microsoft/winget-pkgs/pull/162024 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#162024 opened 2 days ago by [zengqiu](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3Azengqiu)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/162024#partial-pull-merging)
6 of 7 tasks
[ 11](https://github.com/microsoft/winget-pkgs/pull/162024)

https://github.com/microsoft/winget-pkgs/pull/162013 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Possible-Duplicate](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3APossible-Duplicate) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#162013 opened 2 days ago by [wingetbot](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3Awingetbot)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/162013#partial-pull-merging)
[ 14](https://github.com/microsoft/winget-pkgs/pull/162013)

https://github.com/microsoft/winget-pkgs/pull/161995 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#161995 opened 2 days ago by [wingetbot](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3Awingetbot)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/161995#partial-pull-merging)
[ 11](https://github.com/microsoft/winget-pkgs/pull/161995)

https://github.com/microsoft/winget-pkgs/pull/161990 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#161990 opened 2 days ago by [SpecterShell](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3ASpecterShell)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/161990#partial-pull-merging)
[ 15](https://github.com/microsoft/winget-pkgs/pull/161990)

https://github.com/microsoft/winget-pkgs/pull/161983 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#161983 opened 2 days ago by [SpecterShell](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3ASpecterShell)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/161983#partial-pull-merging)
[ 17](https://github.com/microsoft/winget-pkgs/pull/161983)

https://github.com/microsoft/winget-pkgs/pull/161962 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#161962 opened 2 days ago by [daiyam](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3Adaiyam)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/161962#partial-pull-merging)
[ 10](https://github.com/microsoft/winget-pkgs/pull/161962)

https://github.com/microsoft/winget-pkgs/pull/161940 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Manifest-Metadata-Consistency](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AManifest-Metadata-Consistency) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#161940 opened 2 days ago by [SpecterShell](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3ASpecterShell)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/161940#partial-pull-merging)
5 of 7 tasks
[ 17](https://github.com/microsoft/winget-pkgs/pull/161940)

https://github.com/microsoft/winget-pkgs/pull/161936 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#161936 opened 2 days ago by [SpecterShell](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3ASpecterShell)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/161936#partial-pull-merging)
[ 13](https://github.com/microsoft/winget-pkgs/pull/161936)

https://github.com/microsoft/winget-pkgs/pull/161913 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#161913 opened 3 days ago by [SpecterShell](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3ASpecterShell)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/161913#partial-pull-merging)
[ 13](https://github.com/microsoft/winget-pkgs/pull/161913)

https://github.com/microsoft/winget-pkgs/pull/161889 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Manifest-Metadata-Consistency](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AManifest-Metadata-Consistency) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#161889 opened 3 days ago by [aisgbnok](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3Aaisgbnok)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/161889#partial-pull-merging)
7 tasks done
[ 1](https://github.com/microsoft/winget-pkgs/issues/161889/linked_closing_reference?reference_location=REPO_ISSUES_INDEX)
[ 21](https://github.com/microsoft/winget-pkgs/pull/161889)

https://github.com/microsoft/winget-pkgs/pull/161700 
 [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AAzure-Pipeline-Passed) [Moderator-Approved](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AModerator-Approved) [New-Manifest](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ANew-Manifest) [Retry-1](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3ARetry-1) [Validation-Completed](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+draft%3Afalse+label%3AValidation-Completed)
#161700 opened 5 days ago by [Nusiq](https://github.com/microsoft/winget-pkgs/issues?q=is%3Apr+is%3Aopen+author%3ANusiq)
• [Approved](https://github.com/microsoft/winget-pkgs/pull/161700#partial-pull-merging)
7 tasks done

**Pull request merged**
