### PR TITLE
New version: Microsoft.PowerBI version 2.138.1004.0

### LINKED ISSUE #192763: [Package Issue]: Microsoft.PowerBI – Installer Hash Mismatch
### Please confirm these before moving forward

- [x] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [x] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installer hash mismatch.

### Brief description of your issue

The installation of Microsoft.PowerBI fails due to an installer hash mismatch. This error occurs while running the installation via WinGet.

### Steps to reproduce

winget install --id "Microsoft.PowerBI" --source "winget" --silent --accept-package-agreements --accept-source-agreements --verbose-logs

### Actual behavior

Writing command to batch file: "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.24.25200.0_x64__8wekyb3d8bbwe\winget.exe" install --id "Microsoft.PowerBI" --source "winget" --silent --accept-package-agreements --accept-source-agreements --verbose-logs --scope machine  Executing PsExec command: "C:\Windows\System32\PsExec.exe" -s -accepteula "C:\Windows\System32\logs\Phase4\WinGetInstallation\Microsoft.PowerBI\install_Microsoft.PowerBI.bat"  ========== Result for Microsoft.PowerBI ==========   C:\Windows\System32>"C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.24.25200.0_x64__8wekyb3d8bbwe\winget.exe" install --id "Microsoft.PowerBI" --source "winget" --silent --accept-package-agreements --accept-source-agreements --verbose-logs --scope machine      -                                                                                                                              ÛÛÛÛÛÛÛÛÛ±±±±±±±±±±±±±±±±±±±±±  1024 KB / 3.17 MB   ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ±±±±±±±±±±±±  2.00 MB / 3.17 MB   ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ±±  3.00 MB / 3.17 MB   ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ  3.17 MB / 3.17 MB                                                                                                                              -                                                                                                                           Found Microsoft PowerBI Desktop [Microsoft.PowerBI] Version 2.138.782.0 This application is licensed to you by its owner. Microsoft is not responsible for, nor does it grant any licenses to, third-party packages. Agreements for Microsoft PowerBI Desktop [Microsoft.PowerBI] Version 2.138.782.0 Version: 2.138.782.0 Publisher: Microsoft Corporation Publisher Url: https://www.microsoft.com/en-us Publisher Support Url: https://support.microsoft.com/en-us Author: Microsoft Corporation Homepage: https://powerbi.microsoft.com/ License: Proprietary License Url: https://powerbi.microsoft.com/en-us/desktop-eula/ Privacy Url: https://privacy.microsoft.com/en-us/privacystatement Agreements:   End User License Agreement (EULA): https://powerbi.microsoft.com/en-us/desktop-eula/  Downloading https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup_x64.exe     -     \     |     /     -                                                                                                                              ÛÛÛ±±±±±±±±±±±±±±±±±±±±±±±±±±±  62.0 MB /  544 MB   ÛÛÛÛÛÛÛ±±±±±±±±±±±±±±±±±±±±±±±   131 MB /  544 MB   ÛÛÛÛÛÛÛÛÛÛÛ±±±±±±±±±±±±±±±±±±±   204 MB /  544 MB   ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ±±±±±±±±±±±±±±±   281 MB /  544 MB   ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ±±±±±±±±±±±   345 MB /  544 MB   ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ±±±±±±±±   409 MB /  544 MB   ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ±±±±   475 MB /  544 MB   ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ±   540 MB /  544 MB   ÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛÛ   544 MB /  544 MB Installer hash does not match; this cannot be overridden when running as admin

### Expected behavior

The package should install without any hash mismatch issues.

### Environment

```raw
2024-11-21 18:46:31.506 [CORE] WinGet, version [1.8.1911], activity [{268E35D8-2EC7-4185-9F0B-48BA38528B50}]
2024-11-21 18:46:31.507 [CORE] OS: Windows.Desktop v10.0.22631.4317
2024-11-21 18:46:31.507 [CORE] Command line Args: "C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.23.1911.0_x64__8wekyb3d8bbwe\winget.exe"
```

### Screenshots and Logs

_No response_

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings).

Fix #192763

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/194848)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by SpecterShell** [comment]
@stephengillie Could you handle this PR?

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
