### PR TITLE
Add WinGet

### PR DESCRIPTION
**Pull request by NatoBoram**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

---

Any good package manager must *at least* be able to install itself ;)

cc ~~https://github.com/lukesampson/scoop-extras/issues/4107~~ https://github.com/microsoft/winget-cli/issues/505 ~~#825~~ #19425 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/332)

### CODE REVIEW

**Review by jos3s — DISMISSED** [review]
Valid manifest

**Comment by denelon** [comment]
Unfortunately, this suffers from lack of dependencies. We're working on a solution for VCLibs also related to the Sandbox PowerShell script #827 .

**Comment by NatoBoram** [comment]
Couldn't those problems just be solved afterwards? After all, one *might* already have the necessary dependencies, otherwise an error message can be equally helpful, and it's normal for a fairly new installer-executor to not have dependency awareness at first. And now that I think about it, anyone trying to install `WinGet` via `WinGet` probably have most dependencies already.

**Comment by KevinLaMS** [comment]
Deployment wants to shut down old winget to deploy new winget, deployment sends the old winget a ctrl-c signal, the old winget cancels all it’s doing(including the ongoing “install new winget”).

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/505

**Comment by NatoBoram** [comment]
> Unfortunately, this suffers from lack of dependencies. We're working on a solution for VCLibs also related to the Sandbox PowerShell script #827.

Hold on a second, I remember installing from [github.com/microsoft/winget-cli/releases](https://github.com/microsoft/winget-cli/releases) on brand new instances of Windows 10 like last week without missing any dependencies. Are the dependencies in newer builds of Windows?

**Comment by denelon** [comment]
I think we're still blocked on the fact that the install cancels our active installation. We're looking at a delayed registration via MSIX which would unblock this one. I hope we get to that soon 😊

**Comment by ItzLevvie** [comment]
cc @denelon: could you please add the "Blocking-Issue" label on this PR?

**Comment by denelon** [comment]
Just an "FYI" here. It's now possible to `winget install "App Installer` with the connectivity to the "msstore" source. One of the things the Microsoft Store does is handle some of the dependencies related to MSIX packages in the store. We've been talking about the fact that the Windows Package Manager dependencies "must" have been available in order to run `winget upgrade winget` in the first place. The bigger challenge here is that the package is actually the "App Installer" package. We could use `winget` as the moniker though.

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
Close with reason: Replaced by PR 56841;

**Comment by NatoBoram** [comment]
Here's a link to it for mobile users:

* https://github.com/microsoft/winget-pkgs/pull/56841

**Pull request closed without merging**
