### PR TITLE
alibaba.dingtalk Multi Manifest

### PR DESCRIPTION
**Pull request by OfficialEsco**
@lychichem
#16507
#17080

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/17085)

### CODE REVIEW

**Review by lychichem — CHANGES_REQUESTED** [review]
Missing metadata for alibaba.dingtalk.locale.zh-CN.yaml:
```
PublisherSupportUrl: https://page.dingtalk.com/wow/dingtalk/act/dd-server-y
PrivacyUrl: https://terms.alicdn.com/legal-agreement/terms/suit_bu1_dingtalk/suit_bu1_dingtalk202010070946_49604.html
PackageName: 钉钉
LicenseUrl: https://tms.dingtalk.com/markets/dingtalk/service-terms-zh
CopyRightUrl: https://tms.dingtalk.com/markets/dingtalk/service-terms-zh
```

And I wonder whether different `packagename` will cause winget validation fail.

**Comment by OfficialEsco** [comment]
> Missing metadata for alibaba.dingtalk.locale.zh-CN.yaml:
> 
> ```
> PublisherSupportUrl: https://page.dingtalk.com/wow/dingtalk/act/dd-server-y
> PrivacyUrl: https://terms.alicdn.com/legal-agreement/terms/suit_bu1_dingtalk/suit_bu1_dingtalk202010070946_49604.html
> PackageName: 钉钉
> LicenseUrl: https://tms.dingtalk.com/markets/dingtalk/service-terms-zh
> CopyRightUrl: https://tms.dingtalk.com/markets/dingtalk/service-terms-zh
> ```
> 
> And I wonder whether different `packagename` will cause winget validation fail.

Thank you, this is exactly why i left those fields open 😁 No way i would find my way around the website in Chinese 😁
If there is a Chinese Installer which shows up as 钉钉 in Windows Control panel i think that will work, if its still DingTalk it won't work.

**Comment by lychichem** [comment]
So, in your opinion, it is the different `Packagename` in local.zh-CN and local.en-US that causes the check fail? Another question is if I add `钉钉` to tags and use `dingtalk` as packagename, will `winget upgrade` work properly for Chinese users? As dingtalk register itself as `钉钉` in "add or remove programs"

**Comment by OfficialEsco** [comment]
> So, in your opinion, it is the different `Packagename` in local.zh-CN and local.en-US that causes the check fail? Another question is if I add `钉钉` to tags and use `dingtalk` as packagename, will `winget upgrade` work properly for Chinese users? As dingtalk register itself as `钉钉` in "add or remove programs" for Chinese users.

Hmm sounds like it should be 钉钉 then, is the Publisher different too?

**Comment by lychichem** [comment]
> > So, in your opinion, it is the different `Packagename` in local.zh-CN and local.en-US that causes the check fail? Another question is if I add `钉钉` to tags and use `dingtalk` as packagename, will `winget upgrade` work properly for Chinese users? As dingtalk register itself as `钉钉` in "add or remove programs" for Chinese users.
> 
> Hmm sounds like it should be 钉钉 then, is the Publisher different too?

No, the Publisher is the same for Chinese users and foreign users.

**Comment by OfficialEsco** [comment]
> > > So, in your opinion, it is the different `Packagename` in local.zh-CN and local.en-US that causes the check fail? Another question is if I add `钉钉` to tags and use `dingtalk` as packagename, will `winget upgrade` work properly for Chinese users? As dingtalk register itself as `钉钉` in "add or remove programs" for Chinese users.
> > 
> > 
> > Hmm sounds like it should be 钉钉 then, is the Publisher different too?
> 
> No, the Publisher is the same for Chinese users and foreign users.

Alright, you can test if its detected as `alibaba.dingtalk` right now by doing `winget list` if its not you can do `winget list` once this is merged.
If the ID matches whatever the PackageIdentifier is in the Manifest then `winget upgrade` will work.

**Comment by lychichem** [comment]
> > > > So, in your opinion, it is the different `Packagename` in local.zh-CN and local.en-US that causes the check fail? Another question is if I add `钉钉` to tags and use `dingtalk` as packagename, will `winget upgrade` work properly for Chinese users? As dingtalk register itself as `钉钉` in "add or remove programs" for Chinese users.
> > > 
> > > 
> > > Hmm sounds like it should be 钉钉 then, is the Publisher different too?
> > 
> > 
> > No, the Publisher is the same for Chinese users and foreign users.
> 
> Alright, you can test if its detected as `alibaba.dingtalk` right now by doing `winget list` if its not you can do `winget list` once this is merged.
> If the ID matches whatever the PackageIdentifier is in the Manifest then `winget upgrade` will work.

image
The ID is `钉钉`……

**Comment by denelon** [comment]
@lychichem thank you so much for helping us to have better localized metadata!

I've been discussing making it easier to add localizations for manifests using wingetcreate. If you think that is something you would be interested in, let me know.  https://github.com/microsoft/winget-create/issues/78

**Comment by lychichem** [comment]
> @lychichem thank you so much for helping us to have better localized metadata!
> 
> 
> 
> I've been discussing making it easier to add localizations for manifests using wingetcreate. If you think that is something you would be interested in, let me know.  https://github.com/microsoft/winget-create/issues/78

Yes, It's an amazing feature, however, here, the problem is, seems some package will provide different ID for different locale. I don't know whether we can deal with this situation now.
I will test again to confirm later today, as I installs it directly from the installer now but not from winget. However, if it really provides different ID, maybe we'll need a new issue to discuss it.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
