### PR TITLE
Rename package identifier `F3d.F3d` to `f3d-app.f3d`

### PR DESCRIPTION
**Pull request by jo-chemla**
Following request from f3d team, rename package identifier `F3d.F3d` to `f3d-app.f3d`

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/173403)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
It needs to be split into two pull requests.

One to add `f3d-app.f3d` and the other one to remove `F3d.F3d`

**Comment by jo-chemla** [comment]
Thanks for getting back, just did the 2 PRs: 
 - remove `F3d.F3d` https://github.com/microsoft/winget-pkgs/pull/173697
 - add  `f3d-app.f3d` https://github.com/microsoft/winget-pkgs/pull/173698

**Comment by jo-chemla** [comment]
Thanks for merging the 2 other PRs. 
However, the package cannot be found via `winget source update && winget install f3d-app.f3d`, although

**Comment by jo-chemla** [comment]
Might that be because of the dash within the package identifier `f3d-app.f3d`? 

I could not find within the [spec](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.7.0/installer.md#fields) whether there are limitations on special characters on the identifier name: 

> **PackageIdentifier** - The package unique identifier
> **Required Field**
> 
> This key is the unique identifier for a given package. This value is generally in the form of `Publisher.Package`. It is case sensitive, and this value must match the folder structure under the partition directory in GitHub.
>

**Pull request closed without merging**
