### PR TITLE
Add WireGuard 0.3.11

### PR DESCRIPTION
**Pull request by luislavena**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/10719)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Hey! Just a tip for future updates, ProductCode is different for each version, either update the product code or leave it blank, otherwise WinGet Upgrade will get confused

**Comment by luislavena** [comment]
Hello @OfficialEsco, thank you for the tip. I thought `ProductCode` was used consistently across each architecture package (amd64 0.3.5 will be the same for amd64 0.3.11).

Did you received any particular conflict when installing? Apologies if this caused any issue on your end.

I couldn't find any particular reference to the usage of `ProductCode` in the manifest spec, so left the previous reference. I will keep in that in mind and remove the reference in future updates.

Cheers.

**Comment by OfficialEsco** [comment]
I am by no means a expert and i do not really understand `ProductCode`'s but i know the main purpose of the `ProductCode` is to detect the Current version and Outdated version, instead of comparing to `PackageName`, `Publisher` and `Version` which i do not believe works yet (or a lot of packages are wrong).

I'm not using WireGuard so i don't know if it works or not (Its in experimental anyways), i just came here from OpenVPN and noticed `jedieaston` didn't update this one so i took a look 🙃 

The only way i know of finding the `ProductCode` is to install the program and run 
`get-wmiobject Win32_Product | Sort-Object Name | Format-Table IdentifyingNumber, Name -AutoSize` in `PowerShell 5` 
or 
`Get-CimInstance win32_product | Sort-Object Name | Format-Table IdentifyingNumber, Name -AutoSize` in `Powershell 7+`

According to `jedieaston` the `ProductCode` is different in each version for each `Architecture`

**Comment by luislavena** [comment]
Thanks for the details @OfficialEsco!!! I just run that command and found that for this package the `ProductCode` definitely is different (got `{CC68D89C-B50F-4A7E-81C4-AD09F0B5D9A8} WireGuard`)

The only problem with the _install and check_ approach is that I cannot install an arm package or the x86 one, so I cannot obtain these codes 😿.

I hope there is another mechanism, but until that is published or connected, I will remove that from future updates to this package.

Thank you again for the details and your time! ❤️ ❤️ ❤️

**Comment by OfficialEsco** [comment]
Oke i just tested a bit since i also have this problem with ARM64, you can apparently read the msi information without installing it but its a messy progress...
I found this command which works ONLY in Powershell 5...

`Get-AppLockerFileInformation -Path ".\wireguard-amd64-0.3.11.msi" | select -ExpandProperty Publisher | Select BinaryName`

In Powershell 7 it returns blank because when you run `Get-AppLockerFileInformation -Path ".\wireguard-amd64-0.3.11.msi" | select -ExpandProperty Publisher` it returns 
`Publisher  : O=WIREGUARD LLC, L=BOULDER, S=COLORADO, C=US\WIREGUARD\{CC68D89C-B50F-4A7E-81C4-AD09F0B5D9A8},0.3.11.0`

instead of 

```
PublisherName    : O=WIREGUARD LLC, L=BOULDER, S=COLORADO, C=US
ProductName      : WIREGUARD
BinaryName       : {CC68D89C-B50F-4A7E-81C4-AD09F0B5D9A8}
BinaryVersion    : 0.3.11.0
HasPublisherName : True
HasProductName   : True
HasBinaryName    : True
```

You can also use the carbon module
http://get-carbon.org/Get-Msi.html

**Comment by denelon** [comment]
Great feedback on this one!

I've created a specific documentation issue to address ProductCodes:

https://github.com/microsoft/winget-cli/issues/921

**Comment by OfficialEsco** [comment]
Daaamn you found us in a 19 day old PR, thank you for keeping a watch ❤️ 
I feel like this should be a function in Powershell since its actually is a Windows Installer which is getting more and more used..
Also the validation process should include a Product Code check.

**Comment by denelon** [comment]
I actually started an internal e-mail thread with a couple of teams based on the comments here. We're already looking to see what we can do to improve the new winget-create tool we're preparing to ship. We're also looking into what the validation pipelines will be able to do. The current thinking is "warn" if there is no product code, and "error" if we can determine it's the wrong one.

**Pull request merged**
