### PR TITLE
Remove Old: JanDeDobbeleer.OhMyPosh version 3.164.0

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
null

### CODE REVIEW

**Review by OfficialEsco — DISMISSED** [review]

**Comment by OfficialEsco** [comment]
@ryfu-msft can you look at this one, https://github.com/microsoft/winget-pkgs/pull/40606 and https://github.com/microsoft/winget-pkgs/pull/40071?

**Comment by OfficialEsco** [comment]
...

**Comment by OfficialEsco** [comment]
@denelon @palenshus https://github.com/microsoft/winget-pkgs/pull/37208#issuecomment-996231757

**Comment by denelon** [comment]
@yao-msft I think you're on call this week.

**Comment by OfficialEsco** [comment]
@ryfu-msft

**Comment by vedantmgoyal2009** [comment]
@denelon

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
