### PR TITLE
djdjz7.Cloudsnote version 1.0.1.0

### PR DESCRIPTION
**Pull request by illusionaries**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/103299)

### CODE REVIEW

**Comment by djdjz7** [comment]
@microsoft-github-policy-service agree [company="Kubix"]

**Comment by djdjz7** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -2146762487 2023-04-23 23:09:45.524 [CORE] Deployment operation #0: error 0x800B0109: The root certificate of the signature in the app package or bundle must be trusted. 
> 2023-04-23 23:09:45.524 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!582213F2: (caller: 581B3932) Exception(1) tid(15d0) 800B0109 A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.

**Comment by stephengillie** [comment]
Hi @didjz7,

How was this package signed? For best results, packages should be digitally signed. If it's self-signed or with a certificate local to a domain, corporation, or other closed group, please consider using a local manifest (WinGet install --manifest C:\path\to\manifest\files\) for local installations.

**Comment by djdjz7** [comment]
This package is self signed.
Is self signed packages not accepted in this repo?

**Comment by stephengillie** [comment]
> This package is self signed. Is self signed packages not accepted in this repo?

Indirectly, unfortunately. It has [some discussion](https://github.com/microsoft/winget-cli/issues/424).
- Packages basically have to be available for anonymous users to download and install from almost any location. 
- Signing gives a "tamper proof seal" on the package, a way to verify that the bits committed by the developer are the same as received by the user, regardless of identity or location.

**Comment by djdjz7** [comment]
Well then, thanks anyway. I will close this PR.

**Pull request closed without merging**
