### PR TITLE
EpicGames.EpicGamesLauncher version 12.1.7

### PR DESCRIPTION
**Pull request by mddtest**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/16338)

### CODE REVIEW

**Comment by mddtest** [comment]
image

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
It's showing up as `1.2.17.0` for me:
image
image

**Comment by mddtest** [comment]
Yeah I see what you mean.
Installer Reports  12.1.7
Windows Reports 1.2.17.0
Launcher Reports 12.2.6-16532841

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
The version shown in Control Panel is more important so others can upgrade via winget upgrade otherwise they wouldn't be able to.

**Comment by mddtest** [comment]
For launchers I guess it not as big of an issue as they will auto update anyway.

**Pull request closed without merging**
