### PR TITLE
Add Mark Text 0.16.1

### PR DESCRIPTION
**Pull request by Kvanrooyen**
Adds the markdown editor [Mark Text](https://github.com/marktext/marktext) v0.16.1

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/517)

### CODE REVIEW

**Comment by fxha** [comment]
Thanks @Kvanrooyen for adding Mark Text. Could you please change the following entries, thanks!

- `Name` to Mark Text
- `AppMoniker` should be `marktext`
- `InstallerType` is `nullsoft`
- Please add `Author: Mark Text Contributors` or something like that

**Comment by Kvanrooyen** [comment]
> Thanks @Kvanrooyen for adding Mark Text. Could you please change the following entries, thanks!
> 
> * `Name` to Mark Text
> * `AppMoniker` should be `marktext`
> * `InstallerType` is `nullsoft`
> * Please add `Author: Mark Text Contributors` or something like that

Just to confirm before, I push my changes. With the `Author` should I create that in the file, because when I ran the PowerShell script for it, author wasn't an option.

**Comment by fxha** [comment]
> Just to confirm before, I push my changes. With the `Author` should I create that in the file, because when I ran the PowerShell script for it, author wasn't an option.

Yes exactly, you can see an example [here](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv0.1.md#yaml-syntax).

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
