### PR TITLE
Fixed installer hash for TorGuard.

### LINKED ISSUE #10364: Automation has determined TorGuard.TorGuard latest is unavailable
The URL for version latest of TorGuard.TorGuard has been unavailable for 5 or more days.
This package may be removed from the repository if no valid manifest is available in the next 14 days.

If the installer has been moved, please update the manifest with the new URL. If a new version of the package is available, please create a new manifest with the valid URL, version, and SHA256 hash.
If this package is no longer available, please delete the manifest.

```

```

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

------

Per #10364.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/10390)

### CODE REVIEW

**Comment by jedieaston** [comment]
Looks like the TorGuard server is blocking Azure from accessing it. Should I remove this manifest from the repo?

**Comment by KevinLaMS** [comment]
Let's try again.

**Comment by jedieaston** [comment]
it wasn't me. I think this is a bug (unless the pipeline is being blocked by TorGuard).

**Comment by jedieaston** [comment]
I think it got stuck because the validation pipeline failed.

**Comment by jedieaston** [comment]
I just tried to curl the URL in a GitHub Codespace (so I was coming from Azure) and I also got a access denied error. Is there any way to override the pipeline (since the only time the manifest doesn't work is if you are in Azure) or should I just close this?

**Comment by auanasgheps** [comment]
Would be nice to get this sorted.

**Comment by denelon** [comment]
Do we have any ideas why Azure is being blocked? We're going to have to look for an alternative approach for validating packages hosted on sites blocking Azure.

**Comment by jedieaston** [comment]
They must've fixed it, because the bot updated it three days ago (#11930). Closing this...

**Comment by auanasgheps** [comment]
Woho!!! Great!

**Pull request closed without merging**
