### PR TITLE
Pinguin2001.PenguinTo-Do version 1.0.0.0

### PR DESCRIPTION
**Pull request by Pinguin2001**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/38304)

### CODE REVIEW

**Comment by Pinguin2001** [comment]
image

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
This package requires `Microsoft.UI.Xaml.2.7` which is not available in a clean install of Windows 10.

**Comment by ItzLevvie** [comment]
> How can I add it to my manifest?

If you're talking about your WinGet package, it's not possible.
If you're talking about your AppX package, it's already listed.

Add-AppxPackage which is what WinGet uses, doesn't install any dependencies, even if you've listed them in AppxManifest.xml.

> Also, is there any way to specify that an certificate should be installed alongside?

At the moment, no.

Your PR will not pass without a certificate from Microsoft Partner Center or from Code Signing because it's compulsory for all MSIX/APPX packages.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/38304#issuecomment-997962439

**Comment by Pinguin2001** [comment]
> > Also, is there any way to specify that an certificate should be installed alongside?
> 
> No.
> 
> Your pull request will not pass without a certificate signed from Microsoft or other publishers that do code signing because it's compulsory for all MSIX/APPX packages.

Then I will write my own installer for it so people can install my app more easily without me needing to pay for an certificate, thank you for your time ItzLevvie!

**Pull request closed without merging**
