### PR TITLE
Citra-Emulator-Project.Citra-Setup version 1.0

### PR DESCRIPTION
**Pull request by Danmyrer**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/20460)

### CODE REVIEW

**Review by Danmyrer — COMMENTED** [review]
Citra doesn't support silent installations at the moment, since the setup.exe requires the user and manual installations get compressed in the 7z format.

**Comment by ItzLevvie** [comment]
Blocked by https://github.com/microsoft/winget-cli/issues/910.

**Comment by soredake** [comment]
Why close?

**Comment by Danmyrer** [comment]
> Why close?

Since the Citra Setup doesn't support silent installations and the single releases come in a zip package that cannot be unzipped by winget yet.

**Pull request closed without merging**
