### PR TITLE
Add uninstallPrevious to Microsoft.WindowsSDK

### PR DESCRIPTION
**Pull request by Trenly**
* Related to microsoft/winget-cli#2634

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/86277)

### CODE REVIEW

**Comment by Trenly** [comment]
@denelon - Can't seem to find the issue here

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
Bump

**Comment by stephengillie** [comment]
@Trenly This one is failing for the same reason as #86275: dependency on "WPTx64 (OnecoreUAP)-x86_en-us.msi". If a URI for that file could be located, then it could be added to Winget as a package, which could then be listed as a dependency. That would remove this blocker from both of these PRs, and potentially more in the future.

**Comment by denelon** [comment]
@stephengillie since we already have this package, we may need to run manual verification to get past this blocker so we can merge this change.

**Comment by Trenly** [comment]
Bump

**Review by ghost — APPROVED** [review]

**Pull request merged**
