### PR TITLE
New version: Anchor.cli 0.0.30

### PR DESCRIPTION
**Pull request by benburkert**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/151994)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-05-02 16:01:05.202 [FAIL] Installer failed security check. Url: https://github.com/anchordotdev/cli/releases/download/v0.0.30/msi-builder-x64.msi Result: 0x80004005

(Automated response - build 880.)

**Comment by stephengillie** [comment]
Hi @benburkert,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 880.)

**Comment by benburkert** [comment]
ok, my guess is it's a false positive on Go's runtime, please let me know if there's anything I can do.

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-05-03 10:51:18.180 [FAIL] Installer failed security check. Url: https://github.com/anchordotdev/cli/releases/download/v0.0.30/msi-builder-x64.msi Result: 0x80004005

(Automated response - build 880.)

**Comment by stephengillie** [comment]
Hi @benburkert,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 880.)

**Comment by benburkert** [comment]
@stephengillie is there any way to get any insight about why this security scan is failing?

**Comment by stephengillie** [comment]
Unfortunately, I'm sharing all of the data that I have.

**Comment by benburkert** [comment]
replaced by #152140.

**Pull request closed without merging**
