### PR TITLE
Add BleachBit 4.0 for All users

### PR DESCRIPTION
**Pull request by ajtak-angelus**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [ ] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2628)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
image

**Comment by ajtak-angelus** [comment]
Winget must be run as administrator.

image

**Comment by KevinLaMS** [comment]
https://github.com/microsoft/winget-cli/issues/152
Blocked on need to be able to specify needs to be an admin

**Comment by denelon** [comment]
@ajtak-angelus we've updated to the v1.0 manifest schema. We also limit PRs to a single package per PR. This PR is also blocked by the package depending on elevated privilege. I'm not sure if you'd like to update the PR or close it.

**Pull request closed without merging**
