### PR TITLE
VirtualCable.UDSClient version 3.6.0.0

### PR DESCRIPTION
**Pull request by dkmstr**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/107783)

### CODE REVIEW

**Comment by dkmstr** [comment]
@microsoft-github-policy-service agree [company="Virtual Cable S.L.U."]

**Comment by dkmstr** [comment]
@microsoft-github-policy-service agree company="Virtual Cable S.L.U."

**Comment by stephengillie** [comment]
Hi @dkmstr,

This package seems to only launch a notice window:
image

Is this expected? Should it do more?

**Comment by dkmstr** [comment]
Yes, when launched without parameters, it's the expected behavior.

It's the client needed to access to UDS Enterprise Remote VDIs, and need a valid uri (That registers the installation, as udss://....) to launch correctly the remote VDI.

Currently is used by hundred of thousands of users, and we thought than winget could be an easy alternative to the client update, without needing to download directly from the website.

You can see the product website here:

https://udsenterprise.com/en/

Hope this helps...

Regards,

**Comment by Trenly** [comment]
Assigning back to MSFT

[Policy] Needs Attention

**Comment by stephengillie** [comment]
> Yes, when launched without parameters, it's the expected behavior.
> 
> It's the client needed to access to UDS Enterprise Remote VDIs, and need a valid uri (That registers the installation, as udss://....) to launch correctly the remote VDI.
> 
> Currently is used by hundred of thousands of users, and we thought than winget could be an easy alternative to the client update, without needing to download directly from the website.
> 
> You can see the product website here:
> 
> https://udsenterprise.com/en/
> 
> Hope this helps...
> 
> Regards,

Yes, it's very helpful. This is unusual but still valid behavior for an application, and it's good to know that this is by design.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
