### PR TITLE
New version: YggdrasilNetwork.Yggdrasil version 0.5.5

### PR DESCRIPTION
**Pull request by SNMetamorph**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136818)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 669.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-27 16:25:55.292 [FAIL] Installer failed security check. Url: https://github.com/yggdrasil-network/yggdrasil-go/releases/download/v0.5.5/yggdrasil-0.5.5-x64.msi Result: 0x80004005 2024-01-27 23:49:16.992 [FAIL] Installer failed security check. Url: https://github.com/yggdrasil-network/yggdrasil-go/releases/download/v0.5.5/yggdrasil-0.5.5-x86.msi Result: 0x80004005

(Automated response - build 669.)

**Comment by SNMetamorph** [comment]
> Hi @,
> 
> The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.
> 
> (Automated response - build 669.)

Looks like this is false positive detection, what should I do?

**Comment by stephengillie** [comment]
Hi @,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 674.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-27 16:25:55.292 [FAIL] Installer failed security check. Url: https://github.com/yggdrasil-network/yggdrasil-go/releases/download/v0.5.5/yggdrasil-0.5.5-x64.msi Result: 0x80004005 2024-01-27 23:49:16.992 [FAIL] Installer failed security check. Url: https://github.com/yggdrasil-network/yggdrasil-go/releases/download/v0.5.5/yggdrasil-0.5.5-x86.msi Result: 0x80004005

(Automated response - build 674.)

**Comment by stephengillie** [comment]
> Looks like this is false positive detection, what should I do?

We can keep retrying until it passes.

**Comment by SNMetamorph** [comment]
> We can keep retrying until it passes.

Ok. Also VirusTotal doesn't sees any issue with these files.

**Comment by stephengillie** [comment]
Hi @SNMetamorph,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 679.)

**Comment by stephengillie** [comment]
Hi @SNMetamorph,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 695.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-30 12:10:03.905 [FAIL] Installer failed security check. Url: https://github.com/yggdrasil-network/yggdrasil-go/releases/download/v0.5.5/yggdrasil-0.5.5-x86.msi Result: 0x80004005

(Automated response - build 695.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
