### PR TITLE
Peltoche.lsd version 0.23.1

### PR DESCRIPTION
**Pull request by neomax7**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/93775)

### CODE REVIEW

**Review by mdanish-kh — CHANGES_REQUESTED** [review]
> The Windows Package Manager policies requires that the InstallerUrl comes directly from the ISV's release location.

*https://learn.microsoft.com/en-us/windows/package-manager/package/repository#error-labels*

Please add Urls from the official source.

**Comment by neomax7** [comment]
original url only provide zip format. I believe providing it as an installer url wont work.

**Comment by neomax7** [comment]
> > The Windows Package Manager policies requires that the InstallerUrl comes directly from the ISV's release location.
> 
> 
> 
> *https://learn.microsoft.com/en-us/windows/package-manager/package/repository#error-labels*
> 
> 
> 
> Please add Urls from the official source.

original url only provide zip format. I believe providing it as an installer url wont work.

**Comment by mdanish-kh** [comment]
https://github.com/microsoft/winget-pkgs/pull/93774#issuecomment-1383185816

**Comment by neomax7** [comment]
> [#93774 (comment)](https://github.com/microsoft/winget-pkgs/pull/93774#issuecomment-1383185816)

thank you :)

**Pull request closed without merging**
