### PR TITLE
New version: TableClothProject.TableCloth version 1.13.0

### PR DESCRIPTION
**Pull request by rkttu**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/148086)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 876.)

**Comment by stephengillie** [comment]
Hi @rkttu,

Manual Validation ended with: 
image

Should Windows Sandbox be added as an `WindowsFeature`?

**Comment by rkttu** [comment]
Yes. This program extends the functionality of Windows Sandbox, so Windows Sandbox is a required component. 

I'm wondering if there are any parts of the program I'm registering with winget that rely on Windows components and if there are any additional steps I need to take, or if they don't meet the registration requirements.

**Comment by rkttu** [comment]
I would appreciate feedback if there are any additional steps I should take.

**Comment by stephengillie** [comment]
I'm not entirely sure of the next steps from here, either. 

I believe this PR might need a `WindowsFeature`, but I do not know if there is a `Sandbox` feature - it feels like there is a list of them somewhere, but if there is, I'm unaware of its location. I didn't want to suggest that this might be solved with a `WindowsFeature` until I was sure that the `Sandbox` feature existed. 

This seems like the general direction, but without any specifics it feels misleading to suggest.

**Comment by rkttu** [comment]
I'm confused as to what you're referring to, do you mean that programs that add Windows Sandbox as a dependency are not eligible for registration, or do you mean that I just need to edit the PR and resubmit it?

I'd like to know if it's true that I can no longer register my app in this repository because the criteria has changed, and if not, what exactly I should do.

For reference, here's the manifest I had registered previously:

https://github.com/microsoft/winget-pkgs/tree/master/manifests/t/TableClothProject/TableCloth/0.5.5

**Comment by denelon** [comment]
I think this is the one, but I also struggle with the various names for the Windows Optional Features.

It would also be a good idea to add "InstallationNotes" so after one installs this package they can be informed they would need a reboot to get the Windows Optional Feature enabled. We're still working on the "--allow-reboot" and "--resume" features with WinGet so it can gracefully handle the reboot and resume behavior.

```YAML
Dependencies:
  WindowsFeatures:
  - WindowsSandbox
```

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 880.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
