### PR TITLE
Update version: Microsoft.PowerShell version 7.3.7.0

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/120305)

### CODE REVIEW

**Review by mdanish-kh — CHANGES_REQUESTED** [review]
Changes to the PowerShell manifests were reverted by the PowerShell team last time.

- https://github.com/microsoft/winget-pkgs/pull/117893

The team has been maintaining the PowerShell manifests in recent time, so I believe this should be excluded from your GitHub automation. But any proposed changes still should go through the PowerShell team first IMO

cc @anamnavi

**Comment by mdanish-kh** [comment]
[Policy] Needs-Attention

**Comment by anamnavi** [comment]
@mdanish-kh thanks for bringing this to my attention. The PowerShell team already merged in a PR for this version and we'd like to keep those changes. 

In the near future we plan to have automation for this so you can remove it from your automation @vedantmgoyal2009 if you don't mind, thanks!

**Comment by mdanish-kh** [comment]
Close with reason: See above;

**Pull request closed without merging**
