### PR TITLE
Create WinGet package for June 2023 GDK Update 2

### PR DESCRIPTION
**Pull request by aaron-stebner**
Create WinGet package for June 2023 GDK Update 2

Tested locally with winget validate and winget install

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/118378)

### CODE REVIEW

**Comment by aaron-stebner** [comment]
@microsoft/xbox-developer-experience-toolbox for review

**Comment by MattHyman** [comment]
> @microsoft/xbox-developer-experience-toolbox for review

LGTM.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -2147012894 
2023-08-29 13:55:52.272 [CORE] DeliveryOptimization error: 0x80072f76, extended error: 0x00000000 
2023-08-29 13:55:52.293 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFD1BA11EFD: (caller: 00007FFD1BA127D0) Exception(1) tid(1d40) 80072F76  
2023-08-29 13:56:25.101 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(104)\WindowsPackageManager.dll!00007FFD1B9D15CA: (caller: 00007FFD1B9D2129) Exception(2) tid(1d40) 80072EE2     Msg:[InternetReadFile() failed.]  
> 2023-08-29 13:56:25.108 [CLI ] Failed to download, waiting a bit and retry. Url: https://github.com/microsoft/GDK/archive/refs/tags/June_2023_Update_2.zip 

However, unlike last time, the download was successful from my location:
image

**Comment by aaron-stebner** [comment]
> Automatic Validation ended with:
> 
> > Installation failed with exit code -2147012894
> > 2023-08-29 13:55:52.272 [CORE] DeliveryOptimization error: 0x80072f76, extended error: 0x00000000
> > 2023-08-29 13:55:52.293 [FAIL] D:\a_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFD1BA11EFD: (caller: 00007FFD1BA127D0) Exception(1) tid(1d40) 80072F76
> > 2023-08-29 13:56:25.101 [FAIL] D:\a_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(104)\WindowsPackageManager.dll!00007FFD1B9D15CA: (caller: 00007FFD1B9D2129) Exception(2) tid(1d40) 80072EE2     Msg:[InternetReadFile() failed.]
> > 2023-08-29 13:56:25.108 [CLI ] Failed to download, waiting a bit and retry. Url: https://github.com/microsoft/GDK/archive/refs/tags/June_2023_Update_2.zip
> 
> However, unlike last time, the download was successful from my location: image

HR 0x80072F76 = WININET_E_HEADER_NOT_FOUND (The requested header was not found)
HR 0x80072EE2 = WININET_E_TIMEOUT (The operation timed out)

The URL I provided is valid and neither of those errors are in my control.  Why does the automated validation pipeline keep failing for my team's URLs like this?

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
