### PR TITLE
New version: Hitencent.JisuTodo version 3.0.0.6

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#7613](https://github.com/SpecterShell/Dumplings/actions/runs/10554515103).

<details>

<summary>Log</summary>

````
Updated: 3.0.0.5 → 3.0.0.6
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/169367)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2145844848
> 2024-08-25 23:25:35.779 [CORE] DeliveryOptimization error: 0x80190190, extended error: 0x00000000
> 2024-08-25 23:25:35.851 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!54F557EB: (caller: 54F55E1C) Exception(1) tid(d74) 80190190 Bad request (400).
> 2024-08-25 23:25:37.933 [CORE] Download request failed. Returned status: 400
> 2024-08-25 23:25:37.933 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!54F4FA75: (caller: 54F50E2B) Exception(2) tid(d74) 80190190 Bad request (400).
> 2024-08-25 23:25:37.993 [CLI ] Failed to download, waiting a bit and retry. Url: https://dl.jisutodo.com/jisutodo_setup_3.0.0.6.exe
> 2024-08-25 23:25:43.663 [CORE] DeliveryOptimization error: 0x80190190, extended error: 0x00000000
> 2024-08-25 23:25:43.663 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!54F557EB: (caller: 54F55E1C) Exception(3) tid(d74) 80190190 Bad request (400).
> 2024-08-25 23:25:43.910 [CORE] Download request failed. Returned status: 400
> 2024-08-25 23:25:43.911 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!54F4FA75: (caller: 54F50E2B) Exception(4) tid(d74) 80190190 Bad request (400).

(Automated response - build 888.)

**Comment by stephengillie** [comment]
URL: https://dl.jisutodo.com/jisutodo_setup_3.0.0.6.exe 
Response Error: The remote server returned an error: (404) Not Found.

(Automated message - build 917)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
