### PR TITLE
Added ARP entries for Python 3 version 3.6.3150.0.

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

------

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/67671)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
DisplayVersion equal to Package Version should not be included; See https://github.com/microsoft/winget-pkgs/pull/65795#issue-1301190831

**Comment by jedieaston** [comment]
@Trenly Should I hold off on this then, or just remove the DisplayVersions? I was doing this so when we move to Marketing Version for these Python manifests the ARP entries will be already present, but if we remove the displayversions then we'll have to put them back then.

I have no problem removing the DisplayVersions, but if we'll need them later anyway...

**Comment by jedieaston** [comment]
Your wish is my command, I'll close these.

**Comment by Trenly** [comment]
> Your wish is my command, I'll close these.

[My wish](https://www.youtube.com/watch?v=NSWTZllisl0), for you, is that this life becomes all that you want it to

**Pull request closed without merging**
