### PR TITLE
New package: Microsoft.VisualStudioCode.CLI version 1.80.0

### LINKED ISSUE #111729: [Package Request]: Visual Studio Code CLI
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://code.visualstudio.com/Download
Publisher: Microsoft
Package Name: code-cli
Description: Visual Studio Code CLI Standalone
Package Version: 1.80.0
Installer URL: https://code.visualstudio.com/sha/download?build=stable&os=cli-win32-x64

### PR DESCRIPTION
**Pull request by mdanish-kh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

- Resolves #111729 

-----

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with:
> No installation of Visual Studio Code Stable was found. Install it from https://code.visualstudio.com and try again.  If you already installed Visual Studio Code and we didn't detect it, run `code version use stable --install-dir /path/to/installation` 

Should VSC Stable be a dependency?

**Comment by stephengillie** [comment]
@lszomoru, do you approve?

**Comment by cglong** [comment]
Per [the VSCode documentation](https://code.visualstudio.com/docs/editor/command-line#_create-remote-tunnel):

> As you may need to run the CLI on a remote machine that can't install VS Code Desktop, the CLI is also available for standalone install on the [VS Code download page](https://code.visualstudio.com/insiders/).

Will wait for confirmation on this from @lszomoru 🙂

**Comment by lszomoru** [comment]
VS Code packages (Stable/Insiders) are being published to winget through automation. While we could manually publish this one package for the CLI, I do not believe that it would be the right approach as it would quickly become out of date. The right thing to do here, is for me to update our automation so that we start publishing packages for the CLI as well.

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Closing PR in favor of upstream pushes.

**Pull request closed without merging**
