### PR TITLE
the-sz.PreyHelper version 1.14

### PR DESCRIPTION
**Pull request by the-sz**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/121111)

### CODE REVIEW

**Comment by the-sz** [comment]
what does "Validation-Installation-Error" mean? This new version is not really different from previous version which passed your tests...

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335187 
2023-09-28 13:32:36.913 [FAIL] Installer failed security check. Url: https://the-sz.com/common/get.php?product=pr3y Result: 0x80004005 

Hi @the-sz,

This is like a Defender fail. We can retry on Monday.

**Comment by the-sz** [comment]
Can you please rerun? There is no virus inthere: https://www.virustotal.com/gui/file/a767afeb90f490c08c2034f27c34ba0a50bfa4ea998a4e6fb44ecf8611d5f5df and https://www.virustotal.com/gui/file/62e7dbb96a7357ea8434494c9b9dc4c0cb08b1d891da25d312a39e0ec69d6b50

**Comment by the-sz** [comment]
@stephengillie Can you please rerun?

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
