### PR TITLE
Byte dance.tik tok effect house 2.6.2.314 ea4a8da5 507b 43e4 8a8d d50dcde0993f

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/113296&drop=dogfoodAlpha

### CODE REVIEW

**Comment by upintheairsheep** [comment]
Add interactive only installer policy

**Comment by stephengillie** [comment]
>  Manifest: The manifest file path must match PackageIdentifier and PackageVersion properties from manifest. actual 'manifests\b\ByteDance\TikTokEffectHouse\2.6.2.314', expected 'manifests\b\ByteDance\TikTokEffectHouse\2.6.2'

**Comment by stephengillie** [comment]
Manual Validation ended with: 
image

**Comment by upintheairsheep** [comment]
> Manual Validation ended with:
> image

Add interactive only label

**Pull request closed without merging**
