### PR TITLE
New version: prefix-dev.pixi version 0.14.0

### PR DESCRIPTION
**Pull request by ruben-arts**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/139433)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 751.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 762.)

**Comment by stephengillie** [comment]
Hi @ruben-arts,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 762.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-16 08:30:34.565 [FAIL] Installer failed security check. Url: https://github.com/prefix-dev/pixi/releases/download/v0.14.0/pixi-x86_64-pc-windows-msvc.msi Result: 0x80004005

(Automated response - build 762.)

**Comment by ruben-arts** [comment]
Not sure what I can do to fix this :cry: Do the maintainers have any tips?

**Pull request closed without merging**
