### PR TITLE
Update League of Legends to the new Launcher

### PR DESCRIPTION
**Pull request by manuel3108**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

The old launcher doesn't let you login anymore. The new launcher is required.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/4416)

### CODE REVIEW

**Comment by manuel3108** [comment]
I guess there is no way to do it without user input.
Feel free to close if this a rule for the repo.

How can we remove outdated packages? The installation script for the old launcher is working, but the launcher itself is useless because you cannot login. Here is the old one: https://github.com/microsoft/winget-pkgs/blob/master/manifests/RiotGames/LeagueOfLegends/1.0.0.0.yaml
Should I create a PR and remove the old one?

**Comment by KevinLaMS** [comment]
Marking blocked on unattend.  We will leave this alone for now.

**Comment by manuel3108** [comment]
Im on Linux, so im fairly uninterestes in this now. If anyone feels like it feel free to continue

**Comment by ItzLevvie** [comment]
It's been added 14 days ago to the repository, so it can be closed now.

**Pull request closed without merging**
