### PR TITLE
New version: Microsoft.DevHome version 0.200.170.0

### PR DESCRIPTION
**Pull request by mdanish-kh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/110640&drop=dogfoodAlpha

### CODE REVIEW

**Comment by mdanish-kh** [comment]
Manual validation needed 😴

**Comment by mdanish-kh** [comment]
Looks like this depends on WindowsRuntime 1.3 which I've opened a PR for in #110644

**Comment by mdanish-kh** [comment]
https://github.com/microsoft/winget-pkgs/pull/110644 

[Policy] Needs-Attention

**Comment by mdanish-kh** [comment]
Requires manual validation like previous version #108247

**Comment by stephengillie** [comment]
`x64` Automatic Validation ended with:
> 2023-06-27 04:06:47.972 [CORE] Deployment operation #0: Windows cannot install package Microsoft.Windows.DevHome_0.200.170.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.WindowsAppRuntime.1.3" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 3000.820.152.0, along with this package to install. The frameworks with name "Microsoft.WindowsAppRuntime.1.3" currently installed are: {}
2023-06-27 04:06:47.972 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!00007FFC2AC59A45: (caller: 00007FFC2ABE3515) Exception(1) tid(1e38) 80073CF3 Package failed updates, dependency or conflict validation.

`x86` Automatic Validation ended with:
> 2023-06-27 04:05:43.809 [CORE] Deployment operation #0: Windows cannot install package Microsoft.Windows.DevHome_0.200.170.0_x86__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.WindowsAppRuntime.1.3" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x86 processor architecture and minimum version 3000.820.152.0, along with this package to install. The frameworks with name "Microsoft.WindowsAppRuntime.1.3" currently installed are: {}
2023-06-27 04:05:43.810 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!776813F2: (caller: 77613932) Exception(1) tid(5b0) 80073CF3 Package failed updates, dependency or conflict validation.

Also had this output at some point, but can't find its source:
> Failure to parse win 10, attempting win 11 Installation failed with exit code -1978334972 2023-06-27 04:06:47.972 [FAIL]

**Comment by stephengillie** [comment]
This package requires Windows 11, and I'm not sure that the Automated Validation pipeline is performing this "upgrade" correctly. In a Windows 11 VM, the `x86` version installed successfully, but the `x64` had an issue with the dependency which I'm troubleshooting.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
