### PR TITLE
New package: NickGasson.NVC version 1.12.0001

### PR DESCRIPTION
**Pull request by nickg**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/148078)

### CODE REVIEW

**Comment by nickg** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files\NVC\bin\nvc.exe returned exit code: 1

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-04-08 12:53:05.400 [FAIL] Installer failed security check. Url: https://github.com/nickg/nvc/releases/download/r1.12.0/nvc-1.12.0.msi Result: 0x80004005

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Hi @nickg,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Hi @nickg,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-04-08 14:33:11.414 [FAIL] Installer failed security check. Url: https://github.com/nickg/nvc/releases/download/r1.12.0/nvc-1.12.0.msi Result: 0x80004005

(Automated response - build 876.)

**Comment by nickg** [comment]
Can you run the scan again please?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files\NVC\bin\nvc.exe returned exit code: 1

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Verify: 
image

**Review by stephengillie — APPROVED** [review]

**Comment by nickg** [comment]
> Automatic Validation ended with:
> 
> > Executable C:\Program Files\NVC\bin\nvc.exe returned exit code: 1
> 

Is there any way to specify the validation command in the manifest? Running `nvc.exe --version` should return zero.

**Pull request merged**
