### PR TITLE
New version: Kensington.KensingtonWorks version 3.1.8

### PR DESCRIPTION
**Pull request by buzztaiki**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136817)

### CODE REVIEW

**Comment by buzztaiki** [comment]
- https://github.com/microsoft/winget-pkgs/pull/130048#issuecomment-1851102145
- https://github.com/microsoft/winget-pkgs/pull/122865#issuecomment-1765629112

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  WixQuietExec:  ERROR: The process "KensingtonWorks2.exe" not found. WixQuietExec:  ERROR: The process "tbwhelper.exe" not found. WixQuietExec:  Error 0x80070080: Command line returned an error. WixQuietExec:  Error 0x80070080: QuietExec Failed WixQuietExec:  Error 0x80070080: Failed in ExecCommon method CustomAction CA_KillKensigtonWorks returned actual error code 1603 but will be translated to success due to continue marking Action start 15:28:15: WixSchedFirewallExceptionsUninstall. SchedFirewallExceptions:  Component 'tbwhelper_x86' action state (1) doesn't match request (2) SchedFirewallExceptions:  No firewall exceptions scheduled Action ended 15:28:15: WixSchedFirewallExceptionsUninstall. Return value 1. Action start 15:28:15: WixSchedFirewallExceptionsInstall. SchedFirewallExceptions:  Scheduling firewall exception (1€KensingtonWorks Helper€2147483647€127.0.0.1€1€2€C:\Program Files\Kensington\KensingtonWorks2\tbwhelper.exe€€-2147483648€This localhost-only rule allows KensingtonWorks Helper to handle incoming configuration requests from the GUI.) Action start 15:28:15: WixRollbackFirewallExceptionsInstall. Action ended 15:28:15: WixRollbackFirewallExceptionsInstall. Return value 1. Action start 15:28:15: WixExecFirewallExceptionsInstall. Action ended 15:28:15: WixExecFirewallExceptionsInstall. Return value 1. Action ended 15:28:15: WixSchedFirewallExceptionsInstall. Return value 1.

(Automated response - build 669.)

**Comment by buzztaiki** [comment]
hm...
Instalation was successful in my local machine:

```
winget install -m manifests\k\Kensington\KensingtonWorks\3.1.8
見つかりました KensingtonWorks [Kensington.KensingtonWorks] バージョン 3.1.8
このアプリケーションは所有者からライセンス供与されます。
Microsoft はサードパーティのパッケージに対して責任を負わず、ライセンスも付与しません。
インストーラーハッシュが正常に検証されました
パッケージのインストールを開始しています...
インストールが完了しました
```

**Comment by buzztaiki** [comment]
Should I set`interactive` to `InstallModes` as like as https://github.com/microsoft/winget-pkgs/pull/130048?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  WixQuietExec:  ERROR: The process "KensingtonWorks2.exe" not found. WixQuietExec:  ERROR: The process "tbwhelper.exe" not found. WixQuietExec:  Error 0x80070080: Command line returned an error. WixQuietExec:  Error 0x80070080: QuietExec Failed WixQuietExec:  Error 0x80070080: Failed in ExecCommon method CustomAction CA_KillKensigtonWorks returned actual error code 1603 but will be translated to success due to continue marking Action start 15:28:15: WixSchedFirewallExceptionsUninstall. SchedFirewallExceptions:  Component 'tbwhelper_x86' action state (1) doesn't match request (2) SchedFirewallExceptions:  No firewall exceptions scheduled Action ended 15:28:15: WixSchedFirewallExceptionsUninstall. Return value 1. Action start 15:28:15: WixSchedFirewallExceptionsInstall. SchedFirewallExceptions:  Scheduling firewall exception (1€KensingtonWorks Helper€2147483647€127.0.0.1€1€2€C:\Program Files\Kensington\KensingtonWorks2\tbwhelper.exe€€-2147483648€This localhost-only rule allows KensingtonWorks Helper to handle incoming configuration requests from the GUI.) Action start 15:28:15: WixRollbackFirewallExceptionsInstall. Action ended 15:28:15: WixRollbackFirewallExceptionsInstall. Return value 1. Action start 15:28:15: WixExecFirewallExceptionsInstall. Action ended 15:28:15: WixExecFirewallExceptionsInstall. Return value 1. Action ended 15:28:15: WixSchedFirewallExceptionsInstall. Return value 1.

(Automated response - build 674.)

**Comment by stephengillie** [comment]
Hi @buzztaiki,

Is there an installer switch to automatically install the driver? (Unfortunately, these are rare with driver installs.)

**Comment by buzztaiki** [comment]
@stephengillie 

Thank you for your response.

> Is there an installer switch to automatically install the driver? (Unfortunately, these are rare with driver installs.)

I think automatic installation will not be possible.



When referring to `.\kensingtonworks_3.1.8_1704406228.msi /help`, it was noted that the following options are available (sorry for japanese).

<details>

```
Windows ® インストーラー. V 5.0.22621.1 

msiexec /Option <必須パラメーター> [省略可能なパラメーター]

インストール オプション
 </package | /i> <Product.msi>
 製品をインストールまたは構成します。
 /a <Product.msi>
 管理用ツール - ネットワーク上の製品をインストールします。
 /j<u|m> <Product.msi> [/t <変換一覧>] [/g <言語 ID>]
 製品をアドバタイズします - すべてのユーザーには m、現在の
 ユーザーには u を指定します。
 </uninstall | /x> <Product.msi | 製品コード>
 製品をアンインストールします。
表示オプション
 /quiet
 Quiet モード - ユーザーの操作なし
 /passive
 無人モード - 進行状況バーのみ
 /q[n|b|r|f]
 ユーザー インターフェイスのレベルを設定します。
 n - なし
 b - 基本
 r - 簡易
 f - 完全 (既定)
 /help
 ヘルプ情報
再起動オプション
 /norestart
 インストール完了後に再起動しません。
 /promptrestart
 再起動が必要な場合は、ユーザーに再起動を要求します。
 /forcerestart
 常に、インストール後コンピューターを再起動します。
ログ オプション
 /l[i|w|e|a|r|u|c|m|o|p|v|x|+|!|*] <LogFile>
 i - 状態メッセージ
 w - 致命的ではない警告
 e - すべてのエラー メッセージ
 a - 操作のスタートアップ 
 r - 特定の操作の記録
 u - ユーザーの要求
 c - UI パラメーターの初期値
 m - メモリ不足または致命的な終了に関する情報
 o - ディスク領域不足メッセージ
 p - ターミナルのプロパティ
 v - 詳細出力
 x - 詳細デバッグ情報
 + - 既存のログ ファイルに追加
 ! - 各行をログにフラッシュ
 * - v オプションと x オプションを除くすべての情報をログに記録します。
 /log <ログ ファイル>
 /l* <ログ ファイル> と指定したときと同じ情報がログに記録されます。

更新オプション
 /update <Update1.msp>[;Update2.msp]
 更新を適用します。
 /uninstall <修正プログラム コード GUID>[;Update2.msp] 
 /package <Product.msi | 製品コード>
 製品の更新を削除します。
修復オプション
 /f[p|e|c|m|s|o|d|a|u|v] <Product.msi | 製品コード>
 製品を修復します。
 p - ファイルが見つからない場合のみ
 o - ファイルが見つからない、または古いバージョンが
 インストールされている場合 (既定)
 e - ファイルが見つからない、同じバージョンまたは古い
 バージョンがインストールされている場合
 d - ファイルが見つからない、または違うバージョンが
 インストールされている場合
 c - ファイルが見つからない、またはチェックサムと計算
 された値が一致しない場合
 a - すべてのファイルをインストールする
 u - すべてのユーザー固有の必須レジストリ エントリ (既定)
 m - すべてコンピューター固有の必須レジストリ エントリ (既定)
 s - すべての既存のショートカット (既定)
 v - ソースから実行して、パッケージをローカルに再キャッシュする
パブリック プロパティの設定
 [PROPERTY=プロパティ値]

コマンド ラインの構文の詳細については、Windows (R) インストーラー SDK を参照してください。

Copyright (C) Microsoft Corporation. All rights reserved.
Portions of this software are based in part on the work of the Independent JPEG Group.
```

</details>


When adding `/quiet /passive /qn`, the UAC dialog wasn't displayed, but the installation also wasn't proceed.

```
.\kensingtonworks_3.1.8_1704406228.msi /quiet /passive /qn
```

In the case of `/quiet /passive` or `/quiet /passive /qb`, the UAC dialog was displayed.

```
.\kensingtonworks_3.1.8_1704406228.msi /quiet /passive
.\kensingtonworks_3.1.8_1704406228.msi /quiet /passive /qb
```

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Comment by denelon** [comment]
This is an older PR with an earlier version of the schema. If the driver dependency issue has been resolved, feel free to submit a new PR with the current schema.

**Pull request closed without merging**
