### PR TITLE
New version: SomePythonThings.WingetUIStore version 2.0.0

### PR DESCRIPTION
**Pull request by marticliment**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/109983&drop=dogfoodAlpha

### CODE REVIEW

**Comment by marticliment** [comment]
Hello, I have been testing my installer, and with the current settings it can't be more stock as it is now.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code 1 
image

**Comment by stephengillie** [comment]
Manual Validation ended with:
image

**Comment by marticliment** [comment]
> Manual Validation ended with: image

This, I am working on it

**Pull request closed without merging**
