### PR TITLE
New package: wl-std.WLDownloader version 1.2.9

### PR DESCRIPTION
**Pull request by pooriyayt**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164012)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @pooriyayt,

This package seems to have installed and launched normally during validation, but after this appears to have become removed. 
image

The updater also fails to find the application:
image

Is this expected?

**Comment by pooriyayt** [comment]
Dear @stephengillie 

I hope this message finds you well.

We have identified and resolved a bug that was causing the package to appear installed and launched normally during validation but then become removed.

To address this issue, we have released an updated version of the installer. Please download and install the latest version from the following link:

[Download Updated Installer](https://dl1.wl-std.com/WL%20Downloader%20Installer.exe
)

This update resolves the previous bug and ensures the application functions correctly. We apologize for any inconvenience this may have caused and appreciate your understanding and patience.

Thank you for your continued support.

Best regards,

**Comment by pooriyayt** [comment]
@stephengillie  

The updated manifest: https://github.com/microsoft/winget-pkgs/pull/164118

**Comment by stephengillie** [comment]
Close with reason: Duplicate of #164118;

**Pull request closed without merging**
