### PR TITLE
New version: vim.vim.nightly version 9.1.0115

### PR DESCRIPTION
**Pull request by chrisbra**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140000)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @chrisbra,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 763.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-18 16:47:36.910 [CLI ] Installer [X64,nullsoft,Machine,] not applicable: Machine is not compatible with X64 2024-02-18 16:47:44.573 [FAIL] Installer failed security check. Url: https://github.com/vim/vim-win32-installer/releases/download/v9.1.0115/gvim_9.1.0115_x86.exe Result: 0x80004005 2024-02-18 16:47:44.573 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6

(Automated response - build 763.)

**Comment by chrisbra** [comment]
should be fine according to virustotal.com https://www.virustotal.com/gui/url/8d164600f65de2f9213ce58fe2c5e29fc4c901767eea2df3d192b670b6786bfc?nocache=1

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
