### PR TITLE
New version: Suwayomi.Tachidesk-JUI version 1.3.2

### PR DESCRIPTION
**Pull request by Syer10**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/97085)

### CODE REVIEW

**Comment by Syer10** [comment]
@microsoft-github-policy-service agree company="Suwayomi"

**Comment by stephengillie** [comment]
The application installs normally but gives a message when run: 
image

**Comment by Syer10** [comment]
That happens when there is no Java 8+ installed on the machine, since the internal server needs it.

**Comment by stephengillie** [comment]
> That usually happens when there is no Java 8+ installed on the machine, since the internal server needs it. It can be caused by other errors but missing Java is the most common issue.

This sounds as though this could use `Oracle.JavaRuntimeEnvironment` as a dependency.

**Review by stephengillie — APPROVED** [review]

**Comment by Syer10** [comment]
> This sounds as though this could use `Oracle.JavaRuntimeEnvironment` as a dependency.

There isn't only one implementation of the java runtime, so I don't think I can add java as a dependency unless I am able to tell if they don't have another implementation of Java like Temurin or Azul Zulu.

**Pull request merged**
