### PR TITLE
New package: ServantVoice.ServantVoice version 5.4.19.11

### PR DESCRIPTION
**Pull request by servantvoiceapps**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/198140)

### CODE REVIEW

**Comment by servantvoiceapps** [comment]
@microsoft-github-policy-service agree [company="Servant Voice, Inc."]

**Comment by servantvoiceapps** [comment]
@microsoft-github-policy-service agree company="Servant Voice, Inc."

**Comment by servantvoiceapps** [comment]
@microsoft-github-policy-service agree company="Servant Voice Inc"

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-12-12 16:44:15.891 [CLI ] Package hash verification failed. SHA256 in manifest [49f39768db33c0bfe40e04022bd08bcf8aada525e6a71927a92a2681ad58576a] does not match download [537e2316093f9389ff55f165a4fd6ff07a523bffaf28968c450f006eef86e009] with file size [239488512] and content type []

(Automated response - build 904.)

**Comment by servantvoiceapps** [comment]
Sending new pull request with new version release, sorry about that. The version did get updated at the download URL before review.

**Comment by servantvoiceapps** [comment]
Unsure how to update this request with new version and manifest, so I closed this one and pushed a new request to https://github.com/microsoft/winget-pkgs/pull/198866

**Pull request closed without merging**
