### PR TITLE
Intel.ExtremeTuningUtility version 7.5.1.3

### PR DESCRIPTION
**Pull request by Rolling2405**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

### CODE REVIEW

**Comment by Rolling2405** [comment]
**Submission containing materials of a third party: Intel Corporation**

**Comment by Rolling2405** [comment]
How do I fix the manifest validation error but still add the silent install switches?

**Comment by Rolling2405** [comment]
@OfficialEsco How do I add the silent installer switches but still conform to the manifest schema?

**Comment by OfficialEsco** [comment]
The InstallerType is Burn which means you do not have to put the InstallerSwitches in, which is correct but also wrong.
If there was a issue with the switches it would be labeled `Unattended Failed`.

**Comment by Rolling2405** [comment]
> The InstallerType is Burn which means you do not have to put the InstallerSwitches in, which is correct but also wrong.
> If there was a issue with the switches it would be labeled `Unattended Failed`.

You are correct it does not require me to put the InstallerSwitches. I just tested it on my laptop. The previous version did require though that is why I assumed it still required it. My fault for not checking.

**Comment by Rolling2405** [comment]
It can install correctly on my PC

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
image

**Comment by Rolling2405** [comment]
@ItzLevvie It gives that error if it is installed on an unsupported processor.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
We're unable to add this package due as this PR requires special hardware to install and the pipelines are being run on VMs.

**Comment by Rolling2405** [comment]
Hopefully the core dev team can figure out a workaround

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/1417

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
