### PR TITLE
New version: Git.Git version 2.47.0.2

### PR DESCRIPTION
**Pull request by avandorp**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/187028)

### CODE REVIEW

**Comment by avandorp** [comment]
@microsoft-github-policy-service agree

**Review by russellbanks — APPROVED** [review]

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Comment by stephengillie** [comment]
Close with reason: Duplicate of #185858;

**Pull request closed without merging**
