### PR TITLE
New package: mihomo-party.mihomo-party version 1.2.15

### PR DESCRIPTION
**Pull request by sephiroth233**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/172947)

### CODE REVIEW

**Comment by sephiroth233** [comment]
@microsoft-github-policy-service agree

> 在 2024年9月12日，17:23，microsoft-github-policy-service[bot] ***@***.***> 写道：
> 
> @microsoft-github-policy-service agree

**Comment by sephiroth233** [comment]
@microsoft-github-policy-service agree company="mihomo party"

**Comment by sephiroth233** [comment]
@microsoft-github-policy-service agree

**Comment by sephiroth233** [comment]
@microsoft-github-policy-service agree

**Comment by sephiroth233** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Verify:
image

Hi @sephiroth233,

The application displays a slightly higher version number - `1.2.16` instead of `1.2.15`. Should this have a `DisplayVersion`, so the version displayed by the package manager matches the application instead of the Registry?

**Comment by sephiroth233** [comment]
Sorry, 1.2.16 is an update prompt. It just tells users that they can update to the new version. I will change the version number to the latest version.

**Pull request closed without merging**
