### PR TITLE
Fix PackageVersion for PowerShell Preview 7.3.0.101

### PR DESCRIPTION
**Pull request by mdanish-kh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/99813)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/99813)

### CODE REVIEW

**Review by anamnavi — DISMISSED** [review]
LGTM

**Comment by stephengillie** [comment]
Manual Validation failed with:
> @Fatalerror.0xC0000005 atSystem.Management.Automation.Security.SystemPolicy+WldpNativeMethods.WldpCanExecuteFile(System.Guid,WLDP_EXECUTION_EVALUATION_OPTIONS,IntPtr,System.String,WLDP_EXECUTION_POLICYByRef) atSystem.Management.Automation.Security.SystemPolicy.GetFilePolicyEnforcement(System.String,System.IO.FileStream) atSystem.Management.Automation.ExternalScriptInfo.ReadScriptContents() atSystem.Management.Automation.ExternalScriptInfo.get_ScriptBlock() atMicrosoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifestData(System.Management.Automation.ExternalScriptInfo,System.String[],ManifestProcessingFlags,BooleanByRef) atMicrosoft.PowerShell.Commands.ModuleCmdletBase.LoadModuleManifestData(System.Management.Automation.ExternalScriptInfo,ManifestProcessingFlags,System.Collections.HashtableByRef,System.Collections.HashtableByRef,BooleanByRef) atMicrosoft.PowerShell.Commands.ModuleCmdletBase.LoadModule(System.Management.Automation.PSModuleInfo,System.String,System.String,System.String,System.Management.Automation.SessionState,System.Object,ImportModuleOptionsByRef,ManifestProcessingFlags,BooleanByRef,BooleanByRef) atMicrosoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingExtensions(System.Management.Automation.PSModuleInfo,System.String,System.String,System.String,System.String,System.String,System.Management.Automation.SessionState,ImportModuleOptions,ManifestProcessingFlags,BooleanByRef,BooleanByRef) atMicrosoft.PowerShell.Commands.ModuleCmdletBase.LoadUsingModulePath(System.Management.Automation.PSModuleInfo,System.Collections.Generic.IEnumerable`1<System.String>,System.String,System.Management.Automation.SessionState,ImportModuleOptions,ManifestProcessingFlags,System.Management.Automation.PSModuleInfoByRef) atMicrosoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName(ImportModuleOptions,System.String) atMicrosoft.PowerShell.Commands.ImportModuleCommand.ImportModule_LocallyViaName_WithTelemetry(ImportModuleOptions,System.String) atMicrosoft.PowerShell.Commands.ImportModuleCommand.ProcessRecord() atSystem.Management.Automation.Cmdlet.DoProcessRecord() atSystem.Management.Automation.CommandProcessor.ProcessRecord() atSystem.Management.Automation.CommandProcessorBase.DoExecute() atSystem.Management.Automation.Internal.PipelineProcessor.Inject(System.Object,Boolean) atSystem.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(System.Object) atSystem.Management.Automation.Runspaces.LocalPipeline.InvokeHelper() atSystem.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProc() atSystem.Management.Automation.Runspaces.LocalPipeline.InvokeThreadProcImpersonate() atSystem.Management.Automation.Runspaces.PipelineThread.WorkerProc() atSystem.Threading.Thread+StartHelper.Callback(System.Object) atSystem.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext,System.Threading.ContextCallback,System.Object) atSystem.Threading.Thread.StartCallback() ,

**Comment by mdanish-kh** [comment]
> x86 Manual Validation failed with:

I just changed the PackageVersion for an already merged manifest👀 Not sure why it's failing now...

**Review by ItzLevvie — DISMISSED** [review]

**Comment by mdanish-kh** [comment]
@stephengillie - What should be the course of action here? Remove the x86 installers?

Users are experiencing issues with the "infinite" upgrade problem (reports in the above linked two issues) that would be solved by merging these PRs.

**Comment by denelon** [comment]
We will get someone to look a bit deeper into the issue here.

**Comment by mdanish-kh** [comment]
For additional context on the reason for the change for anyone who is investigating the issue:

https://github.com/microsoft/winget-pkgs/pull/99498#issuecomment-1478806439

**Comment by mdanish-kh** [comment]
@denelon -  Got a new user reporting the problem in the linked issue above. Any updates on getting the PR reviewed from someone on the team? 👀

**Comment by denelon** [comment]
Let me reach out again to see.

**Comment by anamnavi** [comment]
@stephengillie could you share the command you used to install/run the x86 msi that generated the error you mentioned. I'm not able to repro on my end.

**Comment by stephengillie** [comment]
> @stephengillie could you share the command you used to install/run the x86 msi that generated the error you mentioned. I'm not able to repro on my end.

Hi @anamnavi,

It's from running the Start menu link. I can repro it endlessly, but the erroring window disappears almost immediately - it's a "blink and you'll miss it" error:
image

Program link: C:\ProgramData\Microsoft\Windows\Start Menu\Programs\PowerShell\PowerShell 7-preview (x86).lnk
- Same behavior from navigating to the Start menu icon and clicking on it. 

System info: 
- Windows Package Manager (Preview) v1.5.441-preview
- Windows: Windows.Desktop v10.0.22621.1555
- System Architecture: X64

**Comment by mdanish-kh** [comment]
@stephengillie @anamnavi - Should I remove the x86 installer from the PR and let this get merged? We can add the x86 in a separate PR. This would unblock a number of users currently experiencing infinite upgrade problems with this package since the versioning isn't consistent across all manifests of PowerShell Preview

**Comment by stephengillie** [comment]
> @stephengillie @anamnavi - Should I remove the x86 installer from the PR and let this get merged? We can add the x86 in a separate PR. This would unblock a number of users currently experiencing infinite upgrade problems with this package since the versioning isn't consistent across all manifests of PowerShell Preview

@mdanish-kh Sorry to miss this. Yes, we probably should remove the x86 for now. This appears to be a [known issue](https://github.com/PowerShell/PowerShell/issues/18545) with `x86` `Microsoft.PowerShell` version `7.3.0`, and the fix appears to be using `x86` version `7.2.7` and modifying the Environment Variable `POWERSHELL_UPDATECHECK=Off` to disable the update notice.

**Comment by mdanish-kh** [comment]
> @mdanish-kh Sorry to miss this. Yes, we probably should remove the x86 for now. This appears to be a [known issue](https://github.com/PowerShell/PowerShell/issues/18545) with `x86` `Microsoft.PowerShell` version `7.3.0`, and the fix appears to be using `x86` version `7.2.7` and modifying the Environment Variable `POWERSHELL_UPDATECHECK=Off` to disable the update notice.

No worries :) I've updated the other two PRs as well

**Comment by anamnavi** [comment]
Thanks for removing @mdanish-kh . I'll check with the team if we have another x86 installer where this is fixed, and open a separate PR to add it back. For now makes sense to remove it and get this in. Thanks!

**Review by anamnavi — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
