### PR TITLE
[PRTest.ps1] Detached HEAD

### PR DESCRIPTION
**Pull request by OfficialEsco**
@jedieaston adding this change since you didn't get around to it 🙄
Working with a Deatched HEAD dosn't create a bunch of local branches
```
Flags:
      --detach               Checkout PR with a detached HEAD
  -f, --force                Reset the existing local branch to the latest state of the pull request
      --recurse-submodules   Update all submodules after checkout
```

Not really sure what --force does, but i don't think it causes any issues?
```
PS C:\Users\Esco\Github\winget-pkgs> gh pr checkout 22373 --detach -f
From https://github.com/microsoft/winget-pkgs
 * branch                refs/pull/22373/head -> FETCH_HEAD
Updating files: 100% (1322/1322), done.
HEAD is now at 26bab6452 trazyn.weweChat version 1.1.7
```

When jumping from branch to branch you might see this, but i don't think its a problem since its returning exit code 0
```
PS C:\Users\Esco\Github\winget-pkgs> gh pr checkout 22400 --detach -f
From https://github.com/microsoft/winget-pkgs
 * branch                refs/pull/22400/head -> FETCH_HEAD
Warning: you are leaving 1 commit behind, not connected to
any of your branches:

  26bab6452 trazyn.weweChat version 1.1.7

If you want to keep it by creating a new branch, this may be a good time
to do so with:

 git branch <new-branch-name> 26bab6452

HEAD is now at 0245eee78 Fixed scope for Badlion.BadlionClient version 3.2.0
```

```
PS C:\Users\Esco\Github\winget-pkgs> $LASTEXITCODE
0
```

cc @KevinLaMS @palenshus since our main man is MIA

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/22403)

### CODE REVIEW

**Review by jedieaston — APPROVED** [review]
Gah! I've been busy with work, literally just thought about doing this five minutes ago. Approved.

**Comment by OfficialEsco** [comment]
If you have other ideas in mind feel free to take over the PR since it most likely won't get approved by any Maintainers for a while..

https://github.com/microsoft/winget-pkgs/pull/22403/commits/95cedff7b42f9ccef88b2abe55ab71eefd8e6347 solves https://github.com/microsoft/winget-pkgs/issues/21941

**Review by JohnMcPMS — APPROVED** [review]
Seems fine to me; I'll wait to merge it until @OfficialEsco approves given that there was some talk of maybe having more changes (there is some magic incantation to tell the bot that but I don't know it...).

**Comment by OfficialEsco** [comment]
Just go ahead and merge it, since i didn't get a reply from @jedieaston i doubt he got time to update it or at least add something new 😁

**Pull request merged**
