### PR TITLE
Change trigger for labels to [Policy]

### PR DESCRIPTION
**Pull request by Trenly**
cc @denelon
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://api.github.com/repos/microsoft/winget-pkgs/pulls/95557)

### CODE REVIEW

**Comment by denelon** [comment]
As soon as I merge this, the rule changes. Have all the moderators been informed?

**Comment by denelon** [comment]
Community Moderators
* @ImJoakim
* @ItzLevvie
* @jedieaston
* @KaranKad
* @mdanish-kh
* @OfficialEsco
* @quhxl
* @russellbanks
* @Trenly

**Comment by Trenly** [comment]
> As soon as I merge this, the rule changes. Have all the moderators been informed?

I see you tagged them all; Thank you :D

**Review by jedieaston — APPROVED** [review]

**Review by mdanish-kh — APPROVED** [review]

**Review by denelon — APPROVED** [review]

**Comment by denelon** [comment]
OK, someone test to make sure it works :)

**Comment by Trenly** [comment]
[Policy] Blocking issue

**Comment by denelon** [comment]
Slow bot?
Rate limited bot?

**Comment by denelon** [comment]
There we go :)

**Comment by Trenly** [comment]
> Slow bot? Rate limited bot?

Seems just slow; Looks like it triggered for me

**Comment by mdanish-kh** [comment]
[Policy] Area-External

**Comment by mdanish-kh** [comment]
Commented to check the bot's behavior as `Close with reason: <reason>` command was not working for me here https://github.com/microsoft/winget-pkgs/issues/95607#issuecomment-1416730846

@Trenly, could it be because the username may be incorrect here? https://github.com/microsoft/winget-pkgs/blob/85db36a985be3fea70c23b5fb751e4011bc9233e/.github/fabricbot.json#L4813-L4815

Should it have `[bot]` written at the end of the username? 👀

**Comment by Trenly** [comment]
> Commented to check the bot's behavior as `Close with reason: <reason>;` command was not working for me here [#95607 (comment)](https://github.com/microsoft/winget-pkgs/issues/95607#issuecomment-1416730846)
> 
> https://github.com/microsoft/winget-pkgs/blob/85db36a985be3fea70c23b5fb751e4011bc9233e/.github/fabricbot.json#L4813-L4815
> 
> @Trenly Should it have `[bot]` written at the end of the username? 👀
> 
> Or it could be there's still work to be done at the back-end for this and reviewing PRs

I think its still backend work. Heres the definition for closing PRs:
https://github.com/microsoft/winget-pkgs/blob/85db36a985be3fea70c23b5fb751e4011bc9233e/.github/fabricbot.json#L2872-L2997

**Pull request merged**
