### PR TITLE
New version: YuzuEmu.Yuzu.Mainline version 1725

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140854)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by Exorcism0666** [comment]
@stephengillie I don't think it's the installer, but rather what's happening in the game in the Switch emulator, otherwise I think we would have been entitled to a command to accept the EULA conditions, which isn't the case.

**Comment by stephengillie** [comment]
URL: https://github.com/yuzu-emu/yuzu-mainline/releases/download/mainline-0-1725/yuzu-windows-msvc-20240224-693144aca.zip 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 861)

**Comment by stephengillie** [comment]
Close with reason: Installer removed.;

**Pull request closed without merging**
