### PR TITLE
New version: Neotys.NeoLoad version 7.5.1

### PR DESCRIPTION
**Pull request by quhxl**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/24721)

### CODE REVIEW

**Comment by quhxl** [comment]
Can someone clarify for me: If the program is simply installed alongside the old version when updating, is it uninstallPrevious? Or is it only used when it is impossible to update the program without uninstalling the previous version?

**Comment by OfficialEsco** [comment]
It is mainly for when the Application complains when a previous version in installed yes.
But you can also add uninstallPrevious if it dosn't make sense to have both programs installed.

This might fail since the bot/winget-cli havn't implemented InstallModes correctly yet..

**Review by OfficialEsco — APPROVED** [review]

**Comment by denelon** [comment]
@quhxl it depends on the program as well. Sometimes a user might want to have the "new" version and the old version. My reference is Ultimaker.Cura. The settings don't tend to get preserved so it's nice to have the new one added first so I can figure out how to bring my settings over before removing the "old" version. In a couple of cases it was useful to have the old version for previous behavior.

**Pull request merged**
