### PR TITLE
Moved Elgato.StreamDeck v4.9.0

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/16601)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
@denelon could you add Validation-Completed to these PRs instead of me creating 10 PRs?..
#16602
#16600
#16599
#16597

**Comment by denelon** [comment]
@OfficialEsco I approved and merged all four of the PRs you requested.

**Comment by OfficialEsco** [comment]
Thaaank you, also this one obv cuz its the same rename blocking c:
We could clean up a few folders if the GitHub API would accept these changes cuz its technically under the same folder..

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
@denelon please add Validation-Completed so the issue can be fixed.

**Comment by denelon** [comment]
Let's see if it complains again before I merge it.

**Comment by OfficialEsco** [comment]
> Let's see if it complains again before I merge it.

Unless you guys tweaked the Wingetbot to allow moving a manifest from `manifests/e/elgato/streamdeck` to `manifests/e/Elgato/StreamDeck` i very much doubt so

**Review by denelon — APPROVED** [review]

**Pull request merged**
