### PR TITLE
Update URL for Seedy-Threepio.Theseus2000 version 3.2

### PR DESCRIPTION
**Pull request by Trenly**
From latest URL Scan:
> https://www.seedy.gq/programs/theseus/Theseus2000_Installer.exe for Seedy-Threepio.Theseus2000 version 3.2 redirects to https://t2000.seedy.gq/Theseus2000_Installer.exe

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/105777)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Comment by BrandonWanHuanSheng** [comment]
It look like the Azure Pipelines logged the hashes didn't match.
Screenshot (225)

**Comment by Trenly** [comment]
> @Trenly It look like the Azure Pipelines logged the hashes didn't match.

Yes, that's what the "Error-Hash-Mismatch" label means

**Comment by BrandonWanHuanSheng** [comment]
It look like you actually deleting from the master.

**Comment by Trenly** [comment]
> It look like you actually deleting from the master.

Yes, because version 3.6 already exists in master

**Review by ImJoakim — APPROVED** [review]

**Pull request merged**
