### PR TITLE
New package: NASSe.K.FBReconnect version 1.0.1

### PR DESCRIPTION
**Pull request by manfred-mueller**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/168692)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @manfred-mueller,

This package installs normally, but when launched, does nothing for a while and then gives this error: 
image
I'm guessing that the application is attempting to connect before providing any output, and this is why it appears to do nothing, before timing out and providing the error. This implies that specific (virtual or bare metal) networking hardware is required. Is this accurate?

**Comment by manfred-mueller** [comment]
Hi,
thank you for reviewing!

Yes your assumption is correct: The program tries to get a xml file from the network gateway which is only present on a Fritz!Box
fbUrl = String.Format("http://{0}:49000/tr64desc.xml", GetDefaultGateway());
If it is found, the taskbar icon gets created and the gui presented.
screenshot

**Comment by manfred-mueller** [comment]
Hello Stephen,
I've reworked the program to show the main window on every router.
Only Fritz!Box related functions are disabled when the router is no Fritz!Box.
I've reuploaded the corrected version to as version [1.0.1](https://github.com/manfred-mueller/FBReconnect/releases/download/1.0.1/FBReconnect-Setup-1.0.1.exe) to git.

Thanks for your efforts!

**Comment by manfred-mueller** [comment]
**### UPDATE:**
I've reworked the program now to show the main window on every router.
Only Fritz!Box related functions are disabled when the router is no Fritz!Box.
I've reuploaded the corrected version to Github as version [1.0.1](https://github.com/manfred-mueller/FBReconnect/releases/download/1.0.1/FBReconnect-Setup-1.0.1.exe).

Thanks for your efforts!

**Pull request closed without merging**
