### PR TITLE
New version: YouXiao.YXCalendar version 2.4.6.22

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#6075](https://github.com/SpecterShell/Dumplings/actions/runs/9631932717).

<details>

<summary>Log</summary>

````
Updated: 2.4.6.5 → 2.4.6.22
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
The manifests for the last version 2.4.6.5 will be removed. Reason: No installer URL is changed compared with the last state while the version is updated
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/159474)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://dl.youxiao.cn/api/1.0/download/url?url=https://vip.123pan.cn/1826849647/????/yxcalendar_latest.exe 
Response Error: The remote server returned an error: (404) Not Found.

(Automated message - build 911)

**Comment by stephengillie** [comment]
URL: https://dl.youxiao.cn/api/1.0/download/url?url=https://vip.123pan.cn/1826849647/????/yxcalendar_latest.exe 
Response Error: The remote server returned an error: (404) Not Found.

(Automated message - build 911)

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
