### PR TITLE
New package: extrame.dget version 2024.07.13.1

### LINKED ISSUE #193537: [Package Request]: extrame.dget
### How can we help?

None

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

| Property        | Value                                                                                                    |
|:----------------|:---------------------------------------------------------------------------------------------------------|
| Package URL     | <https://gitee.com/extrame/dget>                                                                         |
| Publisher       | 刘铭                                                                                                     |
| Package Name    | dget                                                                                                     |
| Description     | Docker Hub 直接下载工具                                                                                  |
| Package Version | `v2024.07.13.1`                                                                                            |
| Installer URL   | <https://gitee.com/extrame/dget/raw/6fff3fe46a6e760588f3817f260fc416ee4a46c8/bin/windows_amd64/dget.exe> |

> [!NOTE]
>
> The installer file of this package is directly included inside the "source code" zone of [the Gitee repository](https://gitee.com/extrame/dget/blob/master/bin/windows_amd64/dget.exe). No _Gitee Releases_ nor _Gitee Tags_ is used by the repository.
>
> Version is extracted by _commit logs_ of this file, according to **build date** and **build SN**. The package itself does NOT support switches like `--version` to check version information.

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #193537

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

## Manual validation

PixPin_2024-11-23_01-59-10

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/193539)

### CODE REVIEW

**Comment by Dragon1573** [comment]
```text
pwsh> dget
time="2024-11-25T00:16:19+08:00" level=fatal msg="请输入需要下载的包名"

0x0001 pwsh> dget --help
Usage of C:\Program Files\WinGet\Links\dget.exe:
  -arch string
        指定架构 (default "linux/amd64")
  -debug
        打印调试信息
  -password string
        password
  -print
        只打印获取信息
  -proxy string
        http proxy
  -registry string
        指定镜像仓库 (default "registry-1.docker.io")
  -sync int
        并发下载数量 (default 3)
  -tags
        获取tag列表
  -username string
        username
```

For https://github.com/microsoft/winget-pkgs/labels/Validation-Executable-Error, an Docker image name is required for running `dget.exe`. It can't launch without any switches or parameters.

For https://github.com/microsoft/winget-pkgs/labels/Validation-Domain, is it caused by _Gitee_ which nobody submit packages hosted on there?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\extrame.dget__DefaultSource\dget.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\dget.exe returned exit code: 1

(Automated response - build 899.)

**Comment by stephengillie** [comment]
> For [ Validation-Domain](https://github.com/microsoft/winget-pkgs/labels/Validation-Domain) , is it caused by _Gitee_ which nobody submit packages hosted on there?

Please understand that even packages hosted on GitHub get this label.

**Comment by stephengillie** [comment]
Verify:
image
- I couldn't find how to have the application display its version number.
- The VM isn't set up properly to display these characters. I'm not sure how to fix this.

**Review by stephengillie — APPROVED** [review]

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> The installer file of this package is directly included inside the "source code" zone of [the Gitee repository](https://gitee.com/extrame/dget/blob/master/bin/windows_amd64/dget.exe). No Gitee Releases nor Gitee Tags is used by the repository.
>
> Version is extracted by commit logs of this file, according to build date and build SN. The package itself does NOT support switches like `--version` to check version information.

**Pull request merged**
