### PR TITLE
New package: BeagleSoftware.BeagleEditor version 2024.4

### LINKED ISSUE #174329: [Package Request]: BeagleEditor
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url:https://github.com/beaglesoftware/beagleeditor/releases
Publisher:BeagleSoftware (Mani Arasteh)
Package Name:BeagleEditor
Description:BeagleEditor, A powerful minimal editor
Package Version:2024.4
Installer URL:https://github.com/beaglesoftware/beagleeditor/releases/download/v2024.4/BeagleEditor-2024.4-Installer.exe

### PR DESCRIPTION
**Pull request by schembriaiden**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.6.0 :rocket:

- Resolves #174329

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/174344)

### CODE REVIEW

**Comment by ManiArasteh** [comment]
Huh?! You?! You opened a PR for me?

**Comment by ManiArasteh** [comment]
Star my repository if you like it

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 896.)

**Comment by KarbitsCode** [comment]
Duplicate of https://github.com/microsoft/winget-pkgs/pull/174608

**Comment by vikingnope** [comment]
@stephengillie, could you verify this manually because for me it installs fine.

**Comment by KarbitsCode** [comment]
> @stephengillie, could you verify this manually because for me it installs fine.

This is already resolved on other PR, see https://github.com/microsoft/winget-pkgs/pull/174608

**Review by ManiArasteh — APPROVED** [review]
I approved it myself :joy: But I don’t think GitHub let me to merge it

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
