### PR TITLE
New version: StrawberryPerl.StrawberryPerl version 5.38.2.2

### PR DESCRIPTION
**Pull request by damn-good-b0t**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/152158)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @damn-good-b0t,

> This PR's version number 5.38.2.2 has 4 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version 5.38.1, which has 3 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 880)

**Comment by stephengillie** [comment]
Hi @damn-good-b0t,

This manifest adds Apps and Features entries that aren't present in previous PR versions. These entries should be added to the previous versions, or removed from this version.

(Automated response - build 880.)

**Comment by a-mnich** [comment]
Maintainer of the damn-good-b0t here.  
I've adapted this PR to now also add AppsAndFeaturesEntries to the previous versions.   
The package version field and DisplayVersion field don't match exactly as the publisher has different marketing and display versions as it's described in the FAQs.
  
Here are screenshots of the Apps & features Settings page for each version:  
grafik
grafik
grafik
grafik
grafik

**Comment by a-mnich** [comment]
Hi @stephengillie,
Maintainer of the damn-good-b0t here.    
The package version field and DisplayVersion field don't match exactly as the publisher has different marketing and display versions as it's described in the FAQs.
I've opened additional PRs for all other versions to now also include AppsAndFeatures entries.
  
Here are screenshots of this PRs Apps & features entry:  
grafik

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
