### PR TITLE
New version: DuckStudio.GitHubLabelsManager version 1.5

### LINKED ISSUE #195056: [Update Request]: DuckStudio.GitHubLabelsManager version 1.5
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

DuckStudio.GitHubLabelsManager

### Package Version

1.5

### Please describe the changes you would like to see

https://github.com/DuckDuckStudio/GitHub-Labels-Manager/releases/tag/v1.5

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Related but failed #195056

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

## Manual validation

image

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/195394)

### CODE REVIEW

**Comment by DuckDuckStudio** [comment]
I have a _question_ , does winget automatically find the appropriate silent install switch when the manifest is not explicitly specified?
(In all the manifests I have submitted, there is a silent installation switch specified in the manifest.)

**Review by ItzLevvie — APPROVED** [review]

**Comment by Dragon1573** [comment]
> Does `winget.exe` automatically find the appropriate silent install switch when the manifest is not explicitly specified?

You're using _InnoSetup_ technology for creating install wizard. `winget.exe` has built-in support for this technology, so users **don't have to** explicitly specify those switches.

**Review by DuckDuckStudio — COMMENTED** [review]
See [Dragon1573/winget-pkgs#5](https://github.com/Dragon1573/winget-pkgs/pull/5/)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 899.)

**Comment by Dragon1573** [comment]
> [!WARNING]
>
> This pull request contains TOO MANY errors of the manifest. It should be closed and recreate.
>
> - Related Dragon1573#5

**Pull request closed without merging**
