### PR TITLE
New version: Microsoft.PowerShell.Preview version 7.5.0.2

### PR DESCRIPTION
**Pull request by anamnavi**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140697)

### CODE REVIEW

**Comment by stephengillie** [comment]
[Policy] Needs-Author-Feedback

**Review by stephengillie — CHANGES_REQUESTED** [review]
Hi @anamnavi,

This PR is missing Apps and features entries that are present on the [previous version](https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/PowerShell/Preview/7.5.0.1/Microsoft.PowerShell.Preview.installer.yaml). 

- I believe these need to be added here - if one manifest version has these, then all need it. 
- Could these be added to the manifest construction process?

**Comment by anamnavi** [comment]
@stephengillie thanks for catching and explaining that! Quick question...now that we publish an msi for arm (for preview versions) do we need an AppFeaturesAndEntries (with a DisplayName) for arm? Is it something we should look to add later?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-23T16:44:54.1031161Z ##[error] One or more errors occurred. (Manifest is invalid.) Manifest is invalid. (Line: 22, Col: 5, Idx: 749) - (Line: 22, Col: 5, Idx: 749): While parsing a block mapping, did not find expected key.

(Automated response - build 808.)

**Comment by stephengillie** [comment]
> @ stephengillie thanks for catching and explaining that! Quick question...now that we publish an msi for arm (for preview versions) do we need an AppFeaturesAndEntries (with a DisplayName) for arm? Is it something we should look to add later?

Glad to help 😁 

From another perspective - we're using the repo, and user registry data, as a distributed database. It reminds me of DNS for packages. We're basically concatenating the PackageIdentifier with version and display information from Registry, as a primary key to lookup against the manifests in repo.

- Some packages don't write version data to the Registry, or write the same number for every version, or have inconsistent or non-linear versioning. This is where these entries are essential. 
- On the other side - if the package version always matches the DisplayVersion, then the DisplayVersion isn't necessary. 
- Also, if one version needs these entries, then every version needs these entries. 

So if the arm version is in a different PackageIdentifier, then I believe these entries shouldn't be necessary, as long as it's writing version data to the Reigstry. But if it's in the same PackageIdentifier, then it will need these entries.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
