### PR TITLE
Unstable Download - TabibitoTechnology.Icaros version 3.2.1.0

### PR DESCRIPTION
**Pull request by Masamune3210**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/28701)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
image

**Comment by Masamune3210** [comment]
not sure what its on about, file matches sha as far as I can tell
image

**Comment by ItzLevvie** [comment]
Looks like a duplicate of https://github.com/microsoft/winget-pkgs/pull/17324? You could contact the application developers to publish their application onto GitHub Releases.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/28701#issuecomment-927186752

**Comment by Masamune3210** [comment]
My bad, will try to ask the dev to upload somewhere stable instead of a uploader site

**Comment by Masamune3210** [comment]
No answer from dev, will close for now

**Pull request closed without merging**
