### PR TITLE
Add gittuf.installer.yml

### PR DESCRIPTION
**Pull request by Yasho-Bapat**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/174831)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Yasho-Bapat,

Is it possible to resubmit this in the multi-file manifest format?

**Comment by Yasho-Bapat** [comment]
@microsoft-github-policy-service agree

**Comment by Yasho-Bapat** [comment]
@stephengillie I've resubmitted this in the multi-file format.

**Comment by stephengillie** [comment]
> @ stephengillie I've resubmitted this in the multi-file format.

Apologies for the vagarities of our pipelines.

**Comment by stephengillie** [comment]
> ##[error] The pull requests contains invalid file 'manifests\g\gittuf\gittuf\0.5.2\gittuf.gittuf.installer.yml'. Only yaml extension allowed.

**Comment by stephengillie** [comment]
Verify:
image

**Review by stephengillie — APPROVED** [review]

**Comment by Yasho-Bapat** [comment]
Thanks! Rolling out 0.6.0 soon, so we'll be back 😄

**Pull request merged**
