### PR TITLE
Peltoche/lsd/0.23.1

### PR DESCRIPTION
**Pull request by neomax7**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://api.github.com/repos/microsoft/winget-pkgs/pulls/95485)

### CODE REVIEW

**Comment by neomax7** [comment]
hello 
the manifest validates and it installs on my laptop without an error. 
is there anyway to check the reason why **winget-svc-validation (installer validation)** process failed here?
thanks in advance

**Comment by neomax7** [comment]
Hi, just checking on the progress

**Comment by sitiom** [comment]
https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=430459&view=logs&jobId=871b4eed-22de-5cb6-c1c8-82f190de633f&j=871b4eed-22de-5cb6-c1c8-82f190de633f&t=523ceef4-ddf7-55a0-c83d-dd0f77b67744
image

False positive?

**Comment by neomax7** [comment]
> https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=430459&view=logs&jobId=871b4eed-22de-5cb6-c1c8-82f190de633f&j=871b4eed-22de-5cb6-c1c8-82f190de633f&t=523ceef4-ddf7-55a0-c83d-dd0f77b67744 image
> 
> False positive?

yah just tried the manifest again, there are no issues on both installing and executing the file.

**Comment by stephengillie** [comment]
Hi @neomax7,

The package installs normally, but requires `Microsoft.VCRedist.2015+.x64` (or `x86`) to run:
image

**Review by sitiom — CHANGES_REQUESTED** [review]
- https://github.com/microsoft/winget-pkgs/pull/118210

**Pull request closed without merging**
