### PR TITLE
New package: RazerInc.RazerInstaller4 version 2.0.0.640

### PR DESCRIPTION
**Pull request by blubbcode**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/198494)

### CODE REVIEW

**Review by blubbcode — COMMENTED** [review]
added synapse 4

**Review by blubbcode — COMMENTED** [review]
looks good

**Review by blubbcode — COMMENTED** [review]
added version 4.

**Comment by zeka5881** [comment]
@microsoft-github-policy-service agree

**Comment by blubbcode** [comment]
@microsoft-github-policy-service agree


Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by stephengillie** [comment]
Verify:
image
This package didn't seem to add any Registry entries.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
