### PR TITLE
New package: Posthaste.Dr version 2.4.3

### PR DESCRIPTION
**Pull request by mendelsphotography**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/158164)

### CODE REVIEW

**Comment by mendelsphotography** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Error occurred while downloading installer from https://www.digitalrebellion.com/download/posthastewin. Forbidden (403). (0x80190193).
 Error information: 
 Http Response: Forbidden
 Http Reason Phrase: Forbidden
 
 6/17/2024 11:22:08 PM

(Automated response - build 886.)

**Comment by stephengillie** [comment]
URL: https://www.digitalrebellion.com/download/posthastewin 
Status Code: 200

(Automated message - build 886)

**Comment by stephengillie** [comment]
It appears that the package is available from my residential IP address, but not available to our data center's IP address. Unfortunately, packages have to be scanned by VMs in the data center for the PR to proceed.

**Comment by mendelsphotography** [comment]
Ok, I figured that was the issue as I was getting 200 status from my end. I contacted the company and they said they added the winget url to there allow list. Is it possible to see if it's working now?

**Comment by mendelsphotography** [comment]
any update?

**Comment by stephengillie** [comment]
> any update?

Unfortunately not, but this Discussion might interest you:
- https://github.com/microsoft/winget-pkgs/discussions/158537

**Comment by mendelsphotography** [comment]
so i guess still don't know what the issue is. Seems like its getting a 403 but not sure what domain or ip needs to unblocked. However i have tested it locally and it works perfectly fine.

**Comment by mendelsphotography** [comment]
still working on it.

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Comment by stephengillie** [comment]
URL: https://www.digitalrebellion.com/download/posthastewin 
OK

(Automated message - build 922)

**Pull request closed without merging**
