### PR TITLE
Fix: EuSoft.Eudic version 13.6.4.0

### PR DESCRIPTION
**Pull request by SpecterShell**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/160078)

### CODE REVIEW

**Comment by SpecterShell** [comment]
Weird. I got a different hash on my side.

**Comment by stephengillie** [comment]
I don't know of a way to confirm what the pipelines are downloading, but there's a possibility that it might be an HTML error page instead of the installer.

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 

(Automated response - build 886.)

**Pull request closed without merging**
