### PR TITLE
Add mIRC latest

### PR DESCRIPTION
**Pull request by chausner**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/10091)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
This was failing... restarting to new baseline

**Comment by chausner** [comment]
I am not sure why installer validation fails in CI, there are no useful error messages in the logs. Installation succeeds when I test locally.

**Comment by OfficialEsco** [comment]
Not sure if this is what Kevin is referering to but this is what my VM gets
image

Also the URL is somehow not static 🤦‍♂️(mIRC's problem)

**Comment by OfficialEsco** [comment]
Ohhhh i figured it out, `https://www.mirc.com/downloads/mirc/32/mirc764.exe` got deleted because they don't keep old versions, for me it redirect to `https://www.mirc.com/get.html` which somehow downloads a file which is unreadable.

The new "temporary" link is `https://www.mirc.com/downloads/mirc/33/mirc765.exe` but it gives a exit code 1223. You can work around this by adding a valid exit code.

I see Chocolatey uses `https://www.mirc.com/get.php?version=765` which seems like a dummy link because it always leads to the newest version, for example you can do `https://www.mirc.com/get.php?version=` and it will lead to 765...

**Comment by chausner** [comment]
@OfficialEsco Thanks for your investigation! I am not sure if this was the original issue that @KevinLaMS experienced but in any case I now updated the URL and hash, and also switched to the "latest" versioning scheme.

**Comment by OfficialEsco** [comment]
You also have to add
```
InstallerSuccessCodes:
  - 1223
```
for it to be valid btw

**Comment by chausner** [comment]
> You also have to add
> 
> ```
> InstallerSuccessCodes:
>   - 1223
> ```
> 
> for it to be valid btw

I just tested once again and it installs successfully with exit code 0 for me in Windows Sandbox. Maybe under certain conditions, the exit code is different but unfortunately we cannot add both:
```yaml
InstallerSuccessCodes:
  - 0
  - 1223
 ```
as the manifest scheme explicitly disallows the value 0 when InstallerSuccessCodes is overridden.

**Comment by OfficialEsco** [comment]
0 is the default success, you don't have to add both :)
Example: https://github.com/microsoft/winget-pkgs/blob/master/manifests/p/plex/Plex/1.31.0/plex.Plex.installer.yaml

We can't see the error on this validation so my guess would be its getting a 1223 exit code which is why it failed

**Comment by chausner** [comment]
> 0 is the default success, you don't have to add both :)

Thanks for the hint, it appears it was really failing due to the success code. 👍

**Pull request merged**
