### PR TITLE
sf-yuzifu.bcm_convertor version 2.0.0

### PR DESCRIPTION
**Pull request by CoolPlayLin**
- Require approval from @sf-yuzifu

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/139414)

### CODE REVIEW

**Review by sf-yuzifu — APPROVED** [review]

**Review by sf-yuzifu — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 751.)

**Comment by stephengillie** [comment]
Hi @CoolPlayLin,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 762.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-15 20:01:13.669 [FAIL] Installer failed security check. Url: https://github.com/sf-yuzifu/bcm_convertor/releases/download/v2.0.0/bcm_convertor.yzf_2.0.0_x86-setup.exe Result: 0x80004005 2024-02-15 20:04:40.872 [FAIL] Installer failed security check. Url: https://gitee.com/sf-yuzifu/bcm_convertor/releases/download/v2.0.0/%E7%BC%96%E7%A8%8B%E7%8C%AB%E6%A0%BC%E5%BC%8F%E5%B7%A5%E5%8E%82_2.0.0_x86-setup.exe Result: 0x80004005

(Automated response - build 762.)

**Comment by stephengillie** [comment]
Hi @CoolPlayLin,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 762.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-15 20:38:46.735 [FAIL] Installer failed security check. Url: https://github.com/sf-yuzifu/bcm_convertor/releases/download/v2.0.0/bcm_convertor.yzf_2.0.0_x86-setup.exe Result: 0x80004005 2024-02-15 20:41:30.728 [FAIL] Installer failed security check. Url: https://gitee.com/sf-yuzifu/bcm_convertor/releases/download/v2.0.0/%E7%BC%96%E7%A8%8B%E7%8C%AB%E6%A0%BC%E5%BC%8F%E5%B7%A5%E5%8E%82_2.0.0_x86-setup.exe Result: 0x80004005

(Automated response - build 762.)

**Comment by CoolPlayLin** [comment]
Hi @stephengillie

Is there any way to submit the software to Microsoft so that it could pass the scan?

**Comment by CoolPlayLin** [comment]
image
Locally installs normal

**Comment by CoolPlayLin** [comment]
image

**Comment by CoolPlayLin** [comment]
I appears this package still cannot pass the scan

@stephengillie @Trenly

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335226 2024-02-20 07:48:26.496 [CLI ] ShellExecute installer failed: 2 2024-02-20 07:48:26.497 [CLI ] Terminating context: 0x8a150006 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:1fd 2024-02-20 07:48:06.570 [CLI ] Installer [X86,nullsoft,Unknown,] not applicable: Installer locale does not match required locale: Required locales: [zh-cn] Or does not satisfy compatible match for Preferred Locales: [en-US] 2024-02-20 07:51:45.200 [CLI ] ShellExecute installer failed: 2 2024-02-20 07:51:45.201 [CLI ] Terminating context: 0x8a150006 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:1fd

(Automated response - build 788.)

**Comment by CoolPlayLin** [comment]
Can https://github.com/microsoft/winget-pkgs/labels/Validation-Domain also be waived?

**Comment by stephengillie** [comment]
Yes! The GitHub page has the GitHub link, and links to the Gitee page with the Gitee link.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
