### PR TITLE
Remove ViGEm.HidHide v1.5.230

### PR DESCRIPTION
**Pull request by masterflitzer**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? https://github.com/microsoft/winget-pkgs/issues/160054#issuecomment-2195016278

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/160484)

### CODE REVIEW

**Comment by masterflitzer** [comment]
@stephengillie i hope it's ok to ping you
i don't understand why the validation fails (what does `Sequence contains no elements` mean), the version 1.5.230 is present on current master so why can't it be removed: https://github.com/microsoft/winget-pkgs/tree/master/manifests/v/ViGEm/HidHide/1.5.230

**Comment by stephengillie** [comment]
URL: https://github.com/nefarius/HidHide/releases/download/v1.5.230.0/HidHide_1.5.230_x64.exe 
OK

(Automated message - build 911)

**Comment by stephengillie** [comment]
Hi @masterflitzer,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 886.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
