### PR TITLE
Submitting Alacritty version 0.4.2.yaml

### PR DESCRIPTION
**Pull request by 149segolte**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1380)

### CODE REVIEW

**Comment by 149segolte** [comment]
The submission details provided by WDNotify@microsoft.com are available at https://www.microsoft.com/en-us/wdsi/submission/c5904f17-2da6-4447-9e96-efca328ca522

**Comment by KevinLaMS** [comment]
sigh.  still a hiccup with smartscreen.  I need to chat with them.

**Comment by KevinLaMS** [comment]
Greetings. I worked with smartscreen to resolve the install error.
Unfortunately the App is failing on 2 VMs.  In one case it does not seem to run.
In another I at least get an error: "The application was unable to start correctly.   0XC000007B  Click OK to close the application"

**Comment by 149segolte** [comment]
On Windows, Alacritty requires Microsoft's VC++ redistributable as a dependency and if the Windows version is older than Windows 10 (October 2018 Update), Alacritty requires winpty to emulate UNIX's PTY API.

**Comment by 149segolte** [comment]
Exact Documentation can be found at [https://github.com/alacritty/alacritty](url).

**Pull request closed without merging**
