### PR TITLE
New version: MarcinOtorowski.MSIXHero version 3.1.0.0 (#197041)

### LINKED ISSUE #197041: [Update Request]: MSIX Hero 3.1.0.0
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

MarcinOtorowski.MSIXHero

### Package Version

3.1.0.0

### Please describe the changes you would like to see

New release 3.1.0.0 is available.
Download link: https://msixhero.net/msix-hero-3.1.0.0.msix

### PR DESCRIPTION
**Pull request by marcinotorowski**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? Closes #197041

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/197043)

### CODE REVIEW

**Comment by Dragon1573** [comment]
> [!TIP]
>
> Don't forget to link this pull request to the issue with ["close keywords"](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests#linking-a-pull-request-to-an-issue) in your [very first comment](https://github.com/microsoft/winget-pkgs/pull/197043#issue-2725369127) ❤️.
>
> This can instruct bots for labeling the issue with <https://github.com/microsoft/winget-pkgs/labels/In-PR>, preventing other contributors from creating duplicate PRs and automatically close issue while this PR is merged.

**Comment by marcinotorowski** [comment]
Closes #197041

**Comment by Dragon1573** [comment]
> Closes #197041

> [!TIP]
>
> The "close keyword" is only valid in your commit messages or [pull request descriptions](https://github.com/microsoft/winget-pkgs/pull/197043#issue-2725369127).

**Comment by stephengillie** [comment]
Including the Issue number in the title prevents my automation from approving this PR.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
