### PR TITLE
update RDMFree to 2021.1.16.0

### PR DESCRIPTION
**Pull request by arielmoisis**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/9133)

### CODE REVIEW

**Comment by arielmoisis** [comment]
the hash when running get-filehash on a pc is 27DD579A0CCE1547D32B15425310BCC5BC3730875AC62ACB781457415C09F051 their seems to be an issue when running in the pipeline where the hash is 8069740DB886555976D371F03A95DD562D40536CB2D8B2CF5FF374E900BE8291

**Comment by arielmoisis** [comment]
@KevinLaMS Are you able to tell me what hash you got. Seems to have had issues i downloaded the installer with a hash of 27DD579A0CCE1547D32B15425310BCC5BC3730875AC62ACB781457415C09F051. The pipeline failed with that one saying the has was 8069740DB886555976D371F03A95DD562D40536CB2D8B2CF5FF374E900BE8291. I am curious if via the CDN we are all getting different versions?

**Comment by yigitemres** [comment]
Manifest works for me.

WindowsSandboxClient_GmsOUyMPQ0

**Comment by denelon** [comment]
@yigitemres as a coincidence I was talking with another publisher about their CDN. It takes from 4-48 hours to update all of their CDN endpoints. Do you mind sharing where you are geographically located? I can see about connecting to a VM on Azure in a different geography and see if that could cause different binaries to be served.

**Comment by yigitemres** [comment]
@denelon Istanbul/Turkey (Not Constantinople 😅)

**Comment by denelon** [comment]
@yigtemres thanks, now I have https://www.youtube.com/watch?v=xo0X77OBJUg stuck in my head 🤣

**Comment by yigitemres** [comment]
> @yigitemres thanks, now I have [youtube.com/watch?v=xo0X77OBJUg](https://www.youtube.com/watch?v=xo0X77OBJUg) stuck in my head 🤣

@denelon Oh, no. 😅 You can also listen [Istanbul Underground by X-Ray Dog](https://www.discogs.com/X-Ray-Dog-Bites-Barks-Growls/release/3482215) or [Race With Devil On Turkish Highway by Al Di Meola](https://www.youtube.com/watch?v=ADb5ikL2Omo).

**Pull request closed without merging**
