### PR TITLE
[Zip][Installer/Portable] New Package: dotPDNLLC.paintdotnet 4.3.12

### LINKED ISSUE #18945: Add Paint.NET
# Package Requested

Paint.NET is a very popular image editor, much like Notepad++. Both scoop and chocolatey have it. Download link: https://www.dotpdn.com/files/paint.net.4.2.16.install.zip

Chocolatey link: https://community.chocolatey.org/packages/paint.net

- [ ] I would like someone else to build the manifest.
- [x] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

Manifest:

Fill out as much of the manifest metadata you can:

```YAML
PackageIdentifier:   # publisher.package format (example: "Microsoft.WindowsTerminal")
PackageVersion:      # version number format x.y.z.a (example: "1.6.10571.0")
PackageLocale:       # meta-data locale (example: "en-US")
Publisher:           # publisher name (example: "Microsoft Corporation")
PackageName:         # package name (example: "Windows Terminal")
License:             # package license (example: "MIT")
ShortDescription:    # package description (example: "The new Windows Terminal")
Installers: 
 - Architecture:     # installer architecture (example: "x64")
   InstallerType:    # installer type (example: "msix")
   InstallerUrl:     # installer URL (should be https://)
   InstallerSha256:  # SHA256 hash calculated from installer
ManifestType: singleton
ManifestVersion: 1.0.0
```

### PR DESCRIPTION
**Pull request by Trenly**
* Resolves #18945

### CODE REVIEW

**Comment by Trenly** [comment]
@msftbot zip

**Review by ItzLevvie — DISMISSED** [review]

**Comment by Trenly** [comment]
@msftbot zip

**Comment by Trenly** [comment]
@msftbot blocking-issue

**Review by ItzLevvie — DISMISSED** [review]

**Comment by mstevens83** [comment]
In the meantime, Paint.NET 5.0(.1) has been released: https://github.com/paintdotnet/release/releases

**Comment by Trenly** [comment]
> In the meantime, Paint.NET 5.0(.1) has been released: [paintdotnet/release/releases](https://github.com/paintdotnet/release/releases)

Will handle this in a separate PR

**Review by ItzLevvie — APPROVED** [review]

**Comment by mdanish-kh** [comment]
@stephengillie - One of those ones that require a manual merge

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
