### PR TITLE
the-sz.Royal version 1.70

### PR DESCRIPTION
**Pull request by the-sz**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/126633)

### CODE REVIEW

**Comment by the-sz** [comment]
Where can I see the reason for failing? Is my application detected as a false-positive virus? What should I do?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2023-11-14 13:45:31.343 [FAIL] Installer failed security check. Url: https://the-sz.com/common/get.php?product=royal Result: 0x80004005 

image

**Comment by stephengillie** [comment]
Hi @the-sz,

Please virus scan your systems. This might be a false positive and we can rescan tomorrow.

**Comment by the-sz** [comment]
> **[stephengillie](/stephengillie) ** c



> Automatic Validation ended with:
> 
> > 2023-11-14 13:45:31.343 [FAIL] Installer failed security check. Url: https://the-sz.com/common/get.php?product=royal Result: 0x80004005
> 
> image

where can I see this image or log line?

**Comment by the-sz** [comment]
> Hi @the-sz,
> 
> Please virus scan your systems. This might be a false positive and we can rescan tomorrow.

My software does not contain any virus:

exe: https://www.virustotal.com/gui/file/f8a8c7f5bce0ad0016f44ebff6b6275a38e3afc7f93c1b6b803eb26afa696600 (only 2 false positives)

zip: https://www.virustotal.com/gui/file/9762019f9a9432a6c0f9d6b29243b5cc4f452fa64c3c56ead38dd2505db5bf19

web: https://www.virustotal.com/gui/url-analysis/u-61b05e38a236472e072e4124e6a8a18dd74e1abbbc31a6cdc873623c2c27e6c3-1700250289

Can you please rerun?

**Comment by the-sz** [comment]
Can you please rerun?

**Comment by the-sz** [comment]
@stephengillie Can you please rerun?

**Comment by the-sz** [comment]
I can't see any error description. What should I do?

image

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @the-sz,

The `Internal-Error-Dynamic-Scan` label is an umbrella error for internal errors during the dynamic scan step of automated validation. It reflects a pipeline issue and not any issue with the package.

**Pull request merged**
