### PR TITLE
Nelson v1.5.0.4088

### PR DESCRIPTION
**Pull request by Nelson-numerical-software**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/155912)

### CODE REVIEW

**Comment by Nelson-numerical-software** [comment]
Can you please help to have error ?
Application was double checked and install is OK
https://github.com/nelson-lang/nelson/actions/runs/9305422105/job/25619745839

**Comment by Nelson-numerical-software** [comment]
> Hello @Nelson-numerical-software,
> 
> The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.
> 
> Template: msftbot/validationError/installation/general

Sorry, Can you provide error message ?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-06-03 08:44:53.492 [FAIL] Installer failed security check. Url: https://github.com/nelson-lang/nelson/releases/download/v1.5.0/Nelson-1.5.0.4088-x86-32.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 882.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-06-03 16:37:37.060 [FAIL] Installer failed security check. Url: https://github.com/nelson-lang/nelson/releases/download/v1.5.0/Nelson-1.5.0.4088-x86-32.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 883.)

**Comment by Nelson-numerical-software** [comment]
@stephengillie 
Any news (Thanks)?
Currently generated app install without error on github CI

**Comment by stephengillie** [comment]
Sorry for the delay. `wingetbot run` wasn't listening to due to:

> Octokit was broken because comment id exceeded int maximum value for parsing JSON. A fix was submitted earlier, but we haven't got a NuGet package yet[.] 

- [@denelon on Gitter](https://matrix.to/#/!LEwByvxhTNZZcKeCCY:gitter.im/$c5J6uL4eU3A1Sy9vsPbUgBSahjnfLz6TDh98ZeW56G4?via=gitter.im&via=matrix.org&via=beeper.com)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
