### PR TITLE
Added TechSmith.Camtasia version 21.0.5.31722

### PR DESCRIPTION
**Pull request by ImJoakim**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/19416)

### CODE REVIEW

**Comment by ImJoakim** [comment]
Hmm

image

**Comment by ImJoakim** [comment]
One more for good measure 😃

**Comment by ImJoakim** [comment]
Any idea why this is failing @OfficialEsco?

**Comment by OfficialEsco** [comment]
Noope, looks like something @arjun-msft or @ChuckFerring have to check

```
PS C:\Users\Esco> winget install -m M:\t\TechSmith\Camtasia\21.0.5.31722\
Found Camtasia [TechSmith.Camtasia]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.techsmith.com/camtasiastudio/releases/2105/camtasia.exe
  ██████████████████████████████   455 MB /  455 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

image

I did have a little fight with this in #16955 but that was only with the MSI which it told me..

**Comment by OfficialEsco** [comment]
Looks like it worked in #20128 🤷‍♂️

**Comment by ImJoakim** [comment]
> Looks like it worked in #20128 🤷‍♂️

Interesting 🤔

**Pull request closed without merging**
