### PR TITLE
Updated PowerBI installer file hash

### PR DESCRIPTION
**Pull request by bearmannl**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----
Closes #19347, no idea why the bot was deleting the whole architecture version?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/19382)

### CODE REVIEW

**Comment by bearmannl** [comment]
Just noticed minimum OS version is Windows 8.1, would that be version 8.1.0.0, or version 9.0.0.0?

https://docs.microsoft.com/en-us/power-bi/fundamentals/desktop-get-the-desktop#minimum-requirements

**Comment by OfficialEsco** [comment]
Ohshit just saw the PR cuz it passed the Pipeline
This is a Dynamic URL so the version is wrong in this one, can you update 2.94.921.0 and add the x64 arch?

**Comment by bearmannl** [comment]
@OfficialEsco, can you see wht this thing isn't moving ahead?  Should be good now 🤔

**Comment by OfficialEsco** [comment]
Close and Reopen the PR (same button just so you don't open another PR)

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
