### PR TITLE
Delete My Software that Has Been Removed By ME

### PR DESCRIPTION
**Pull request by CoolPlayLin**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/103948)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
@CoolPlayLin It look like you were trying to delete the waivers metadata

**Comment by CoolPlayLin** [comment]
image

**Comment by CoolPlayLin** [comment]
I deleted the software

**Comment by BrandonWanHuanSheng** [comment]
> I deleted the software

It look like it still not yet removed from the master.

**Comment by CoolPlayLin** [comment]
@BrandonWanHuanSheng ????

**Comment by CoolPlayLin** [comment]
You could try to download the sfw

**Comment by BrandonWanHuanSheng** [comment]
> @BrandonWanHuanSheng ????

It look like it still there.
Screenshot (222)

**Comment by BrandonWanHuanSheng** [comment]
I am helping you to remove that things from the master. #103960

**Comment by BrandonWanHuanSheng** [comment]
Most likely, when disturbing winget manifest. It look like wingetbot said /AzurePipelines run.

**Comment by CoolPlayLin** [comment]
@BrandonWanHuanSheng Thanks

**Comment by CoolPlayLin** [comment]
btw, I cannot delete `.validation` file right?

**Comment by BrandonWanHuanSheng** [comment]
> btw, I cannot delete `.validation` file right? @BrandonWanHuanSheng

Yes. It is true. Most likely that wingetbot will delete it by itself.

**Comment by CoolPlayLin** [comment]
Thanks a lot.

**Pull request closed without merging**
