### PR TITLE
New version: Google.Chrome.Beta version 123.0.6312.4

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings).
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140884)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @SpecterShell,

This PR appears to modify more than 1 manifest version:
image

Is this the case? Could either the addition or the removal be moved to another PR?

**Comment by stephengillie** [comment]
[Policy] Needs-Author-Feedback

**Comment by SpecterShell** [comment]
> Hi @SpecterShell,
> 
> This PR appears to modify more than 1 manifest version: image
> 
> Is this the case? Could either the addition or the removal be moved to another PR?

It's normal to remove one version and add one version for the same package in one PR...right? @stephengillie

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Sorry, I am confused about our policy now.

**Pull request merged**
