### PR TITLE
New version: Google.Chrome version 131.0.6778.109

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings).
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/196086)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 899.)

**Comment by olegpro81** [comment]
Preview published version is broken too. Just so I can get notifications.

**Review by joker-87 — APPROVED** [review]

**Comment by SpecterShell** [comment]
They may have updated the WiX toolset, which generated this MSI file, to v5 in this version. They may have also updated the internal installer, from GoogleUpdate (Omaha) to Google Updater, in this version. The error might be from the Google Updater solo, or the two stuffs combined (e.g., the way the MSI invokes the internal installer, since `Google.PlayGames.Beta` does not have such issues) **in the SYSTEM context**.

```
[1856:1852:1204/103839.946:VERBOSE1:installer.cc(429)] "C:\Windows\Installer\MSI6500.tmp" --silent --install=appguid={8A69D345-D564-463c-AFF1-A69D9E530F96}&appname=Google --installsource=enterprisemsi --appargs=appguid={8A69D345-D564-463c-AFF1-A69D9E530F96}&installerdata=%7B%22distribution%22%3A%7B%22msi%22%3Atrue%2C%22system_level%22%3Atrue%2C%22verbose_logging%22%3Atrue%2C%22msi_product_id%22%3A%22B08A0E79-5477-3603-BDF8-AC49CB064D5A%22%2C%22allow_downgrade%22%3Afalse%7D%7D --enable-logging --vmodule=*/components/winhttp/*=1,*/components/update_client/*=2,*/chrome/enterprise_companion/*=2,*/chrome/updater/*=2 Chrome&needsAdmin=True&brand=GCEA&ap=x64-stable
[1984:1960:1204/103840.621:VERBOSE1:updater.cc(320)] Version: 131.0.6776.0, opt, 32 bits, command line: "C:\Windows\SystemTemp\Google1856_492864402\bin\updater.exe" --silent --install=appguid={8A69D345-D564-463c-AFF1-A69D9E530F96}&appname=Google --installsource=enterprisemsi --appargs=appguid={8A69D345-D564-463c-AFF1-A69D9E530F96}&installerdata=%7B%22distribution%22%3A%7B%22msi%22%3Atrue%2C%22system_level%22%3Atrue%2C%22verbose_logging%22%3Atrue%2C%22msi_product_id%22%3A%22B08A0E79-5477-3603-BDF8-AC49CB064D5A%22%2C%22allow_downgrade%22%3Afalse%7D%7D --enable-logging --vmodule=*/components/winhttp/*=1,*/components/update_client/*=2,*/chrome/enterprise_companion/*=2,*/chrome/updater/*=2 Chrome&needsAdmin=True&brand=GCEA&ap=x64-stable --offlinedir={d7fcf649-b357-4e36-bb5f-43dc68bdfaab}
[1984:1960:1204/103840.621:VERBOSE1:updater.cc(322)] OS version: 10.0.22621.4541, System uptime (seconds): 92, parent pid: 1856
[6664:6660:1204/103840.653:VERBOSE1:updater.cc(320)] Version: 131.0.6776.0, opt, 32 bits, command line: C:\Windows\SystemTemp\Google1856_492864402\bin\updater.exe --crash-handler --database=C:\Users\WDAGUtilityAccount\AppData\Local\Google\GoogleUpdater\131.0.6776.0\Crashpad --url=https://clients2.google.com/cr/report --annotation=prod=Update4 --annotation=ver=131.0.6776.0 --attachment=C:\Users\WDAGUtilityAccount\AppData\Local\Google\GoogleUpdater\updater.log --initial-client-data=0x2d4,0x2d8,0x2dc,0x2b0,0x2e0,0x926290,0x92629c,0x9262a8
[6664:6660:1204/103840.653:VERBOSE1:updater.cc(322)] OS version: 10.0.22621.4541, System uptime (seconds): 92, parent pid: 1984
[1984:1960:1204/103840.653:VERBOSE1:crash_reporter.cc(121)] Crash handler launched and ready.
[1984:1960:1204/103840.653:VERBOSE1:crash_client.cc(106)] Found 0 completed crash reports
[1984:1960:1204/103840.653:VERBOSE1:crash_client.cc(124)] Found 0 pending crash reports
[1984:1960:1204/103840.653:VERBOSE2:update_usage_stats_task_win.cc(58)] No app enables usagestats.
[1984:1960:1204/103840.653:VERBOSE2:update_usage_stats_task_win.cc(58)] No app enables usagestats.
[1984:1960:1204/103840.653:VERBOSE1:updater.cc(93)] Crash reporting initialized.
[1984:1960:1204/103840.653:VERBOSE1:updater.cc(148)] IsUserAdmin: 1, IsUserNonElevatedAdmin: 0, IsUACOn: 0, IsElevatedWithUACOn: 0, LUA: 0
[1984:1960:1204/103840.668:VERBOSE1:update_service_proxy_win.cc(930)] GetVersion
[1984:2348:1204/103840.668:VERBOSE2:proxy_impl_base_win.h(86)] ::CoCreateInstance failed: {547E9AEF-8043-5D26-879F-01E7664192DC}: 80040154
[1984:1960:1204/103840.668:VERBOSE1:update_service_proxy_win.cc(930)] GetVersion
[1984:2348:1204/103840.668:VERBOSE2:proxy_impl_base_win.h(86)] ::CoCreateInstance failed: {547E9AEF-8043-5D26-879F-01E7664192DC}: 80040154
[1984:1960:1204/103840.668:VERBOSE1:update_service_proxy_win.cc(930)] GetVersion
[1984:2348:1204/103840.668:VERBOSE2:proxy_impl_base_win.h(86)] ::CoCreateInstance failed: {547E9AEF-8043-5D26-879F-01E7664192DC}: 80040154
[1984:2348:1204/103840.668:VERBOSE1:setup.cc(64)] Setup, scope: User
[1984:2348:1204/103840.684:VERBOSE1:setup_util.cc(626)] RegisterUserRunAtStartup
[1984:2348:1204/103840.684:ERROR:work_item_list.cc(46)] item execution failed 
[1984:2348:1204/103840.684:ERROR:work_item_list.cc(55)] Failed execution of work item list 
[1984:2348:1204/103840.684:ERROR:setup.cc(156)] Install failed, rolling back...
[1984:2348:1204/103840.684:ERROR:setup.cc(158)] Rollback complete.
[1984:1960:1204/103840.684:VERBOSE1:app_install_win.cc(732)] Exit
[1984:1960:1204/103840.684:VERBOSE1:app_install_win.cc(987)] Updater error: 75044.
[1984:1960:1204/103840.699:VERBOSE1:update_service_proxy_win.cc(922)] ~UpdateServiceProxyImpl
[1984:2348:1204/103840.699:VERBOSE2:proxy_impl_base_win.h(62)] ~ProxyImplBase
[1984:2372:1204/103840.699:VERBOSE1:app_install_win.cc(173)] OnComplete
[1984:1960:1204/103840.699:VERBOSE1:updater.cc(327)] UpdaterMain (--install) returned 75044.
[6664:6660:1204/103840.699:VERBOSE1:updater.cc(327)] UpdaterMain (--crash-handler) returned 0.
[1856:1852:1204/103840.824:VERBOSE1:installer.cc(538)] Metainstaller WMain returned: 73500, Windows error: 75044
```

**Comment by SpecterShell** [comment]
https://issues.chromium.org/issues/382108340

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
