### PR TITLE
PortugueseGovernment.AutenticacaoGov version 3.5.4272

### PR DESCRIPTION
**Pull request by Touratica**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15174)

### CODE REVIEW

**Comment by Touratica** [comment]
It worked for me...

**Comment by Touratica** [comment]
Everything was working when I tried locally.

**Comment by denelon** [comment]
@Touratica this error usually occurs either when there is some kind of UI required by the installer to complete, or the UI pops up due to dependencies.

**Comment by Touratica** [comment]
I've checked on a Windows Sandbox, it seems to be because it prompts if I'd like to install a device software. It's impossible to get around these, right?
image

**Comment by denelon** [comment]
Yes, that's the current state of the system. We either need to support dependencies so we could install the right ones, and the installer wouldn't prompt, or we would need to support the ability to "prefer" silent installers so we can start allowing "interactive only" installers in the community repository.

**Comment by Touratica** [comment]
It's not possible to add this program to the repository yet, due to always prompting the user, even when using the silent installer.

**Pull request closed without merging**
