### PR TITLE
Update version: GitButler.GitButler version 0.14.4

### PR DESCRIPTION
**Pull request by damn-good-b0t**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/198788)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by ndom91** [comment]
@stephengillie are you responsible for the winget GitButler pavkage? I'm from the GitButler team and wanted to publish a first party winget package, only to find that someone (or some bot? :joy:) has alrady been doing a great job of it!

**Comment by stephengillie** [comment]
Hi @ndom91,

We would be very happy to receive manifest PRs directly from your team. The recommended solution is to add a PR creation step into your CI/CD pipeline, to expedite the process. I believe a GitHub Action is available for this. 

Most of our packages are maintained by community members. Automation is widely leveraged here, so it might have been an automated submission. But there has to be a delay between when your pipeline releases the package, and their automation checks for the update. So having it come directly from your pipeline would skip that delay.

**Comment by a-mnich** [comment]
Hi @ndom91,
The damn-good-b0t is a bot maintained by @Utesgui and myself. It is connected to an automation through which we update or create lot's of winget packages that aren't automatically maintained by others.  
As Stephen already mentioned, it's always best if the publisher integrates the package update into their CI/CD pipelines to reduce the delay between release and the creation of the winget-pkgs PRs.  
Currently, the GitButler GitHub repository is checked every 4 hours for new releases.
If you don't want to automate it yourself, it's absolutely no effort for us to keep maintaining it as it's already fully automated. :)
  
Thanks for appreciating our bot's work :D

**Comment by denelon** [comment]
@ndom91 if you want to handle it yourself, I'd suggest following the pattern used by PowerToys:
https://github.com/microsoft/PowerToys/blob/main/.github/workflows/package-submissions.yml

@a-mnich & @Utesgui thanks so much for lightening the load for folks!!!

**Comment by ndom91** [comment]
Hey guys, thanks a lot for the quick replys! 

It looks like your version of the GitButler package here is well handled and already entirely automated so that's perfectly fine by us. I'll ask the team if we need to make any minor changes to metadata stuff like description, tags, etc. But the most important stuff like the license and publisher look good. 

Thanks again for all your work! :pray:

**Comment by Utesgui** [comment]
@ndom91 As some devs have intresting concepts of releasing we have to get creative from time to time :D in your case however it was fairly easy. Currently we simply follow the static "latest" Link from your website (https://app.gitbutler.com/downloads/release/windows/x86_64/msi) and use the redirected absolut link.

The other Option would have been to watch the GH releases and use that as trigger, however since you have the build number in the download URL, we weren't able to "generate" the correct Download URLS without knowing the build. 

Thanks for providing the API Endpoints! I will switch over to the "full" endpoint as source of truth - This way we don't have any delays if the "static latest" link is not up to date (for whatever reason).
Since you also provide the release notes in the API endpoint i will add them to new winget releases as well. Not sure if anyone has ever read the release notes in a winget package :D but no big work either so why not.

Just let us know when you want us to change something :)

**Pull request merged**
