### PR TITLE
New package: SWIG.SWIG version 4.2.1

### PR DESCRIPTION
**Pull request by ptsouchlos**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/162099)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\ccache-swig.exe returned exit code: 1
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\swig.exe returned exit code: 1

(Automated response - build 886.)

**Comment by DeveloperPaul123** [comment]
Validation on windows sandbox doesn't reproduce this error:

```
--> Installing WinGet
--> Disabling safety warning when running installer
Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.

--> Configuring Winget
Enabled admin setting 'LocalManifestFiles'.
Enabled admin setting 'LocalArchiveMalwareScanOverride'.

--> Installing the Manifest 4.2.1

Found SWIG [SWIG.SWIG] Version 4.2.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://sourceforge.net/projects/swig/files/swigwin/swigwin-4.2.1/swigwin-4.2.1.zip/download
  ██████████████████████████████  11.7 MB / 11.7 MB
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "ccache-swig"
Command line alias added: "swig"
Path environment variable modified; restart your shell to use the new value.
Successfully installed

--> Refreshing environment variables

--> Comparing ARP Entries

DisplayName DisplayVersion Publisher ProductCode              Scope
----------- -------------- --------- -----------              -----
SWIG        4.2.1          SWIG      SWIG.SWIG__DefaultSource User


PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> swig
Must specify an input file. Use -help for available options.
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> ccache-swig.exe
ccache-swig.exe, a compiler cache including support for SWIG. Version 4.2.1
Copyright Andrew Tridgell, 2002

Usage:
        ccache-swig.exe [options]
        ccache-swig.exe compiler [compile options]
        compiler [compile options]    (via symbolic link)

Options:
-s                      show statistics summary
-z                      zero statistics
-c                      run a cache cleanup
-C                      clear the cache completely
-F <maxfiles>           set maximum files in cache
-M <maxsize>            set maximum size of cache (use G, M or K)
-h                      this help page
-V                      print version number
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs>
```

**Comment by stephengillie** [comment]
Hi @DeveloperPaul123,

This is something of a known issue with the pipeline, which was writen with Windows Forms in mind. Because it's so common, with exit codes as high as `127`, I usually mark any exit code with 3 or fewer digits as passing.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Verify:
image

**Pull request merged**
