### PR TITLE
New version: Google.Chrome version 122.0.6261.39

### PR DESCRIPTION
**Pull request by PckgrBot**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/139144)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by thangarajua** [comment]
Hi,

The bot picks up the early stable release version(122.0.6261.39) but the download link gets the older version.
https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi - 121.0.6167.185
image
image

**Comment by kovacsr89** [comment]
Hi!

This is weird. The latest beta is v122.0.6261.39 and the latest stable is v121.0.6167.185.
Maybe the bot messed something up?

**Comment by Bec-de-Xorbin** [comment]
> Hi!
> 
> This is weird. The latest beta is v122.0.6261.39 and the latest stable is v121.0.6167.185. Maybe the bot messed something up?

It's an early stable version: https://chromereleases.googleblog.com/2024/02/early-stable-update-for-desktop.html

There's no direct links available to early stables.

**Comment by BDisp** [comment]
> There's no direct links available to early stables.

If there is no direct links available to early stable then I think it shouldn't included in the packages.

**Comment by mdanish-kh** [comment]
@Pckgrbot - 

Definitely not the expert here. I'm not sure how we can distinguish from `stable` to `early stable` releases. One thing I have noted is that the stable API: https://versionhistory.googleapis.com/v1/chrome/platforms/win/channels/stable/versions?order_by=version%20dsc

and the beta API: https://versionhistory.googleapis.com/v1/chrome/platforms/win/channels/beta/versions

currently point to the same latest version `122.0.6261.39`. Maybe for future, we can compare these two and if they are the same, the bot can skip updating the package?

**Comment by mdanish-kh** [comment]
> The bot uses the stable API to get the latest version, not sure what has happened here. What's more concerning is that is passed validation. @mdanish-kh

The installer validation has no way to distinguish if a version is beta or stable

**Comment by BDisp** [comment]
> @PckgrBot -
> 
> I'm definitely not the expert here. Not exactly sure how we can distinguish from `stable` to `early stable` releases. One thing I have noted is that the stable API: https://versionhistory.googleapis.com/v1/chrome/platforms/win/channels/stable/versions?order_by=version%20dsc
> 
> and the beta API: https://versionhistory.googleapis.com/v1/chrome/platforms/win/channels/beta/versions
> 
> currently point to the same latest version `122.0.6261.39`. Maybe for future, we can compare these two and if they are the same, the bot can skip updating the package?

Maybe is better compare both links and if a stable version is still on the beta version link ignore it.

**Comment by mdanish-kh** [comment]
> Hello, sorry I meant the validation didn't pick up that the same hash's are used in the previous version of Chrome. Usually it would block saying "possible duplicate"

I see, i think I noticed this with another PR as well but thought it was a one-off case. I'm pretty sure this is a regression now. I'll create an issue for this

**Pull request merged**
