### PR TITLE
Remove: Meta.Oculus version 1.86.0.0

### PR DESCRIPTION
**Pull request by SpecterShell**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/154204)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://securecdn.oculus.com/binaries/download/?id=3552425908372122 
OK

(Automated message - build 887)

**Comment by stephengillie** [comment]
Hi @SpecterShell,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 881.)

**Comment by stephengillie** [comment]
URL: https://securecdn.oculus.com/binaries/download/?id=3552425908372122 
Status Code: 200

(Automated message - build 881)

**Comment by SpecterShell** [comment]
> Hi @SpecterShell,
> 
> This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)
> 
> (Automated response - build 881.)

I must remove this version first before submitting a new version in https://github.com/microsoft/winget-pkgs/pull/154205. 
In-place update doesn't work: https://github.com/microsoft/winget-pkgs/pull/153627

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
> > Hi @SpecterShell,
> > This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)
> > (Automated response - build 881.)
> 
> I must remove this version first before submitting a new version in #154205. In-place update doesn't work: #153627

Thank you for helping me to understand.

**Pull request merged**
