### PR TITLE
D4koon.WhatsappTray version 1.9.0.0

### PR DESCRIPTION
**Pull request by medvedev125**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/82559)

### CODE REVIEW

**Comment by medvedev125** [comment]
> 

@microsoft-github-policy-service agree

**Comment by medvedev125** [comment]
There is a related feature request in WhatsappTray project: https://github.com/D4koon/WhatsappTray/issues/145

**Review by ItzLevvie — CHANGES_REQUESTED** [review]

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Please see https://github.com/microsoft/winget-pkgs/pull/82559#discussion_r989226850

**Comment by ItzLevvie** [comment]
Close with reason: Replaced by PR 82817 to avoid having the pull request be stale;

**Pull request closed without merging**
