### PR TITLE
Add other architectures to Syncthing.Syncthing 1.23.3

### PR DESCRIPTION
**Pull request by mdanish-kh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101625)

### CODE REVIEW

**Comment by stephengillie** [comment]
I'm not able to find the cause for this error. It installs and runs normally on a Windows 11 VM.

**Comment by torculus** [comment]
@stephengillie, I'm not sure how to do it, but on my branch the `PATH` variable is updated to `C:\Users\myusername\AppData\Local\Microsoft\WinGet\Packages\Syncthing.Syncthing__DefaultSource`, when it should be `C:\Users\Ben\AppData\Local\Microsoft\WinGet\Packages\Syncthing.Syncthing__DefaultSource\syncthing-windows-amd64-v1.23.4`. Even though the PATH is updated, PowerShell can't find the executable

Perhaps that's the source of the error you're talking about?

**Comment by mdanish-kh** [comment]
@torculus That is a known issue which appears in non-developer mode / user-context shells in Windows and I'm not sure if it's related to https://github.com/microsoft/winget-pkgs/labels/Validation-Executable-Error. Fortunately, the fix for the mentioned PATH issue was merged in https://github.com/microsoft/winget-cli/pull/3002 and will appear in the next release of WinGet

**Comment by torculus** [comment]
@stephengillie , is there anything else blocking this merge request? Once it goes through, I can rebase my other one to update to 1.23.4

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
> @stephengillie , is there anything else blocking this merge request? Once it goes through, I can rebase my other one to update to 1.23.4

@torculus, 

Thanks for your patience.

**Pull request merged**
