### PR TITLE
Remove Version: Sigil-Ebook.Sigil version 1.8.0

### PR DESCRIPTION
**Pull request by dougmassay**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/168250)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://github.com/Sigil-Ebook/Sigil/releases/download/1.8.0/Sigil-1.8.0-Windows-x64-Setup.exe 
OK

(Automated message - build 914)

**Comment by stephengillie** [comment]
Hi @dougmassay,

This version is still available for download. Why is it being removed? Is it near end of support?

**Comment by dougmassay** [comment]
I've typically been deleting older versions on winget whenever a new version is released. Is this a problem? All older Windows versions of Sigil are pretty much unsupported. When bugs are reported, the first step to troubleshoot that bug is to verify that it still exists in the latest release.

But mostly, I just don't like having every version I've ever released being available on winget. Feels a bit hoggish of me. GitHub is my historical repository. But if you tell me to not remove versions still available on GitHub, so be it. I just never read anything that indicated there _needed_ to be a reason to remove versions.

**Comment by stephengillie** [comment]
URL: https://github.com/Sigil-Ebook/Sigil/releases/download/1.8.0/Sigil-1.8.0-Windows-x64-Setup.exe 
Status Code: 200

(Automated message - build 887)

**Comment by stephengillie** [comment]
> I've typically been deleting older versions on winget whenever a new version is released. Is this a problem? All older Windows versions of Sigil are pretty much unsupported. When bugs are reported, the first step to troubleshoot that bug is to verify that it still exists in the latest release.
> 
> But mostly, I just don't like having every version I've ever released being available on winget. Feels a bit hoggish of me. GitHub is my historical repository. But if you tell me to not remove versions still available on GitHub, so be it. I just never read anything that indicated there _needed_ to be a reason to remove versions.

No worries. I like to ask when there's not a reason or linked issue, to make sure somoene isn't being capricious. Even just "removing old version" works fine.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
