### PR TITLE
add binbat/whipinto

### PR DESCRIPTION
**Pull request by Yin-ZP**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/128485)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Yin-ZP,

This PR appears to modify multiple manifests:
image

Could you put one of these into another PR?

**Comment by Yin-ZP** [comment]
The live777 mainfest changed [in Live777 #127396](https://github.com/microsoft/winget-pkgs/pull/127396).I just add whipinto in this version,why it shows that modify multiple manifests?

**Comment by Yin-ZP** [comment]
> The live777 mainfest changed [in Live777 #127396](https://github.com/microsoft/winget-pkgs/pull/127396).I just add whipinto in this version,why it shows that modify multiple manifests?

The live777 mainfest changed https://github.com/microsoft/winget-pkgs/pull/127396.I just add whipinto in this version,why it shows that modify multiple manifests?

**Comment by Yin-ZP** [comment]
> Hi @Yin-ZP,
> 
> This PR appears to modify multiple manifests: image
> 
> Could you put one of these into another PR?

The live777 mainfest changed https://github.com/microsoft/winget-pkgs/pull/127396.I just add whipinto in this version,why it shows that modify multiple manifests?

**Comment by stephengillie** [comment]
Test

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
