### PR TITLE
6.2.10

### PR DESCRIPTION
**Pull request by 1kamma**
- [ v ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ v ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ v ] This PR only modifies one (1) manifest
- [ v ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ v ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ v ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/127287)

### CODE REVIEW

**Comment by 1kamma** [comment]
Can someone approve it?

**Review by 1kamma — COMMENTED** [review]
only abc file

**Review by Trenly — CHANGES_REQUESTED** [review]
Manifests are in incorrect format; Only one manifest can be edited per PR

**Review by 1kamma — COMMENTED** [review]
changed

**Pull request closed without merging**
