### PR TITLE
Added Elastic.Winlogbeat version 7.13.3

### PR DESCRIPTION
**Pull request by ImJoakim**
image

```
PS C:\Users\WDAGUtilityAccount\Desktop\manifests> winget install -m "C:\Users\WDAGUtilityAccount\Desktop\manifests\e\Elastic\Winlogbeat\7.13.3"
Found Beats winlogbeat [Elastic.Winlogbeat]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://artifacts.elastic.co/downloads/beats/winlogbeat/winlogbeat-7.13.3-windows-x86_64.msi
  ██████████████████████████████  19.5 MB / 19.5 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/20214)

### CODE REVIEW

**Comment by ImJoakim** [comment]
Whoops, delete the wrong branch..

**Comment by ImJoakim** [comment]
My apologies for accidently deleting my branch making it re-run. Are you able to add `Azure-Pipeline-Passed` when you get the chance @jamespik?

**Comment by ItzLevvie** [comment]
cc @palenshus @denelon: "Azure-Pipeline-Passed" label needs to be added to this PR.

**Comment by denelon** [comment]
@ItzLevvie thanks. We're working on some changes to make this behavior automatic so we can reduce the human error. The limitation is currently in the bot, so we're writing some more custom code 😊

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
