### PR TITLE
New version: Microsoft.OneDrive version 22.131.0619.0001

### PR DESCRIPTION
**Pull request by mdanish-kh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/67374)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by yao-msft** [comment]
Assigning to @hackean-msft to see why under our Daas environment, the connection to https://oneclient.sfx.ms would fail.

**Comment by yao-msft** [comment]
https://github.com/microsoft/winget-pkgs/pull/51131#issuecomment-1064455480

**Pull request merged**
