### PR TITLE
Deepvocal huanxiaoyi1.2

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
Since #1937 has been solved, I can reopen this pull request.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2499)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
image
App does not install.

**Comment by oxygen-dioxide** [comment]
This app must be installed in an elevated shell

**Comment by KevinLaMS** [comment]
https://github.com/microsoft/winget-cli/issues/152

**Comment by vedantmgoyal2009** [comment]
@KevinLaMS @denelon This PR can also be closed as the manifest schema being used is 0.1.0.

**Comment by denelon** [comment]
@vedantmgoyal, we're implementing the v1.1 schema that will identify installers that require elevation. As we implement some of the new schema behaviors in the client, many of these "older" PRs will be executed again, so they can be addressed and added.

**Comment by vedantmgoyal2009** [comment]
Okay.

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
