### PR TITLE
New package: Swisslogforwindows.Swisslog version 5.107

### LINKED ISSUE #113328: [Package Request]: Swisslog
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.swisslogforwindows.com/download.html
Publisher: swisslogforwindows.com
Package Name: Swisslog
Description: Logging software for the most demanding radio amateur.
Package Version: 5.107
Installer URL: https://www.swisslogforwindows.com/Download/SwisslogSetupv5107.exe

### PR DESCRIPTION
**Pull request by Jvr2022**
Resolve #113328

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by stephengillie** [comment]
Hi @Jvr2022,

Are there silent installer switches, to bypass the above prompt and install automatically?

**Comment by Jvr2022** [comment]
> Hi @Jvr2022,
> 
> Are there silent installer switches, to bypass the above prompt and install automatically? 

No

**Comment by AsciiWolf** [comment]
> Automatic Validation ended with

Oops. :-/

**Comment by Jvr2022** [comment]
Can we add support

**Pull request closed without merging**
