### PR TITLE
CnCNet.YurisRevenge version 8.15.0

### LINKED ISSUE #86291: [Package Request]: CnCNet Red Alert 2 & Yuri's Revenge
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: CnCNet
Publisher Url: https://cncnet.org
Package Name: CnCNet Red Alert 2 & Yuri's Revenge
Description: CnCNet Red Alert 2 & Yuri's Revenge is a community-run multiplayer service which allows people to play the classic Command & Conquer games Red Alert 2 and it's expansion Yuri's Revenge online.
Package Version: 8.15
Installer URL: https://downloads.cncnet.org/CnCNet5_YR_Installer.exe

### PR DESCRIPTION
**Pull request by jeffwlawson**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

Resolves: #86291 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/92549)

### CODE REVIEW

**Comment by jeffwlawson** [comment]
@microsoft-github-policy-service agree

**Comment by jeffwlawson** [comment]
@msftbot dependencies

**Comment by stephengillie** [comment]
Hi @jeffwlawson, 

> I think the validation failed because this has dependencies on having the actual game Red Alert 2 or Yuri's Revenge installed. Not sure if dependency support is implemented yet.

Yes, you're right about why validation failed: 
image

Packages are validated on fresh installs of Windows. Is there a switch to bypass this installer check? 
Winget does support dependencies - is there another package whose installation would clear this prompt?

**Comment by jeffwlawson** [comment]
It looks like the installer is looking for the [ra2md.mix](https://github.com/CnCNet/cncnet-yr-client-package/blob/8ef16ac8a2acc92ee5741d73186fb55ff7060ca4/InnoSetup/CnCNet5_YR_Installer.iss#L64) file in a few [different directories](https://github.com/CnCNet/cncnet-yr-client-package/blob/8ef16ac8a2acc92ee5741d73186fb55ff7060ca4/InnoSetup/CnCNet5_YR_Installer.iss#L65-L71)  based on the different ways that the game can be installed.

Not sure if passing the /SILENT switch would bypass this check or not.  And since I already have the game installed, it's hard for me to check.

**Comment by jeffwlawson** [comment]
#86291

**Comment by stephengillie** [comment]
> Not sure if passing the /SILENT switch would bypass this check or not. And since I already have the game installed, it's hard for me to check.

I've just tested it and unfortunately no, the /SILENT switch still results in the same error.

**Pull request closed without merging**
