### PR TITLE
New package: Aislx.FlameLauncher version 01.00.02.00

### PR DESCRIPTION
**Pull request by aislxflames**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140584)

### CODE REVIEW

**Review by Argha11 — APPROVED** [review]

**Review by DarkStar444 — APPROVED** [review]

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-02-22 18:51:24.428 [FAIL] Installer failed security check. Url: https://github.com/aislxflames/flame-launcher/releases/download/v1.0.0/fmcl.setup.latest.exe Result: 0x80004005

(Automated response - build 807.)

**Comment by stephengillie** [comment]
Hi @aislxflames,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 807.)

**Comment by aislxflames** [comment]
@microsoft-github-policy-service agree
@microsoft-github-policy-service agree [company="{TheFlamEs}"]
@microsoft-github-policy-service agree company="Microsoft"

**Pull request closed without merging**
