### PR TITLE
updated ea app

### PR DESCRIPTION
**Pull request by deadlynjdj**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/40016)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
1) You won't be able to move any files with a .validation file in the folder
2) The new app doesn't appear to install silently. Only apps which support silent installation can be added
3) There is no need to update the package Identifier. The package Identifier can remain `ElectronicArts.EADesktop` while the moniker can be `eaapp`. That way someone searching for either `EADesktop` or `EAApp` will still be able to see the package

**Comment by Trenly** [comment]
> https://github.com/microsoft/winget-pkgs/pull/40016/commits/a3f9baecdbab18bd9f57dc1186b4e4b1ffb7adbb updated the .validation with the correct path

Only Microsoft employees have permissions in this repository to modify .validation files. You will have to submit just the manifest without a .validation file in order for your PR to be tested

**Comment by deadlynjdj** [comment]
I changed the path and the package Identifier back and just changed the moniker and changed the .validation had the wrong folder but failed when not changed and not changed

**Comment by deadlynjdj** [comment]
ok I will remove it

**Comment by Trenly** [comment]
> ok I will remove it

Because you changed the folder, it still detects it as a change to the .validation. You have to leave the original folder

**Comment by deadlynjdj** [comment]
the version folder is the same on the GitHub

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/40016#issuecomment-1006964344

**Pull request closed without merging**
