### PR TITLE
New version: Genivia.ugrep version 5.1.0

### PR DESCRIPTION
**Pull request by genivia-inc**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/142881)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Genivia.ugrep__DefaultSource\ug.exe returned exit code: 2
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Genivia.ugrep__DefaultSource\ugrep.exe returned exit code: 2
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\ugrep.exe returned exit code: 2
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\ug.exe returned exit code: 2

(Automated response - build 867.)

**Comment by genivia-inc** [comment]
> Automatic Validation ended with:
> 
> > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Genivia.ugrep__DefaultSource\ug.exe returned exit code: 2
> > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Genivia.ugrep__DefaultSource\ugrep.exe returned exit code: 2
> > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\ugrep.exe returned exit code: 2
> > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\ug.exe returned exit code: 2
> 
> (Automated response - build 867.)

I saw this pop up. Is there a problem?

I've internally tested ugrep.exe and ug.exe as I do that every time. Compilation is done with MSVC++ 2022 and has not changed for the 5.1 release, i.e. (almost) the same code and the exact same compilation as the previous 5.0 release. I can't see how and why there would be a problem.

**Comment by stephengillie** [comment]
Yes - improved log filtering has added error codes and removed a lot of noise. This has always been occurring, but wasn't being emitted into the PR. 

Basically, the application is exiting with `2` instead of zero when launched with no arguments. 

- For now, I can continue adding a waiver (or similar) as I have been.
- Eventually, this should be fixed. Some options:
  - Add `2` as an `ExpectedReturnCode` or in a [similar manifest field](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.6.0/installer.md).
  - Add a `Command` that returns zero as an exit code. Others have used a `-version` command.
  - If this is your application, have it return a zero exit code when launched with no arguments. 

(Some of these might be more applicable to your situation than others.)

**Comment by stephengillie** [comment]
Completing validation.

**Review by stephengillie — APPROVED** [review]

**Comment by genivia-inc** [comment]
> Yes - improved log filtering has added error codes and removed a lot of noise. This has always been occurring, but wasn't being emitted into the PR.
> 
> Basically, the application is exiting with `2` instead of zero when launched with no arguments.
> 
> * For now, I can continue adding a waiver (or similar) as I have been.
> * Eventually, this should be fixed. Some options:
>   
>   * Add `2` as an `ExpectedReturnCode` or in a [similar manifest field](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.6.0/installer.md).
>   * Add a `Command` that returns zero as an exit code. Others have used a `-version` command.
>   * If this is your application, have it return a zero exit code when launched with no arguments.
> 
> (Some of these might be more applicable to your situation than others.)

Indeed. Invoking ugrep w/o arguments returns an status error code. To avoid that, we should invoke ugrep with option `--version` (two dashes like UNIX long options).

**Comment by genivia-inc** [comment]
Looking at what's in [winget-pkgs](https://github.com/Genivia/winget-pkgs/tree/master)/[manifests](https://github.com/Genivia/winget-pkgs/tree/master/manifests)/[g](https://github.com/Genivia/winget-pkgs/tree/master/manifests/g)/[Genivia](https://github.com/Genivia/winget-pkgs/tree/master/manifests/g/Genivia)/[ugrep](https://github.com/Genivia/winget-pkgs/tree/master/manifests/g/Genivia/ugrep)
/5.1.0/
I don't see where to config this test to avoid this failure. I assume it is on someone else's end to fix?

**Comment by stephengillie** [comment]
Yes, the properties that are needed to avoid this failure aren't currently part of the manifest. This is what I meant with my earlier comments.

**Pull request merged**
