### PR TITLE
REALiX.HWiNFO version 7.06

### PR DESCRIPTION
**Pull request by KaranKad**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/19886)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
I keep getting this
image

Smartscreen shouldn't be the issue
image

https://www.hwinfo.com/files/hwi_706.exe does not download anything for me.
https://www.fosshub.com/HWiNFO.html?dwl=hwi_706.exe does work as expected.
https://www.sac.sk/download/utildiag/hwi_706.exe throws `The requested URL was not found on this server.`

**Comment by KaranKad** [comment]
I just tried using direct download link `https://www.hwinfo.com/files/hwi_706.exe` and it didn't download anything. It's only downloading when you visit that website and manually press download button.

**Comment by OfficialEsco** [comment]
> It's only downloading when you visit that website and manually press download button.

It doesn't even do that for me 😁 even after accepting the cookies which some sites require..
I think this might be why we have used the sac mirror, + IIRC Chocolatey also uses the sac mirror

**Comment by KaranKad** [comment]
Yeah, we might have to wait until they fix sac mirror issue.

**Comment by OfficialEsco** [comment]
> Yeah, we might have to wait until they fix sac mirror issue.

The sac mirror seems to be working now

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
