### PR TITLE
New version: ryanbekhen.nanoproxy 0.13.1

### PR DESCRIPTION
**Pull request by ryanbekhen**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/154817)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @ryanbekhen,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-23 02:44:27.477 [FAIL] Installer failed security check. Url: https://github.com/ryanbekhen/nanoproxy/releases/download/v0.13.1/nanoproxy_Windows_x86_64.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 881.)

**Comment by ryanbekhen** [comment]
@stephengillie how do i do it because i use goreleaser to build it?

**Comment by stephengillie** [comment]
> @stephengillie how do i do it because i use goreleaser to build it?

Sorry to leave you waiting over the American holiday. Any change to the PR (including an inconsequential change, such as adding or removing a space or line break character) will trigger another run of the PR's manifest. So will closing and reopening the PR, but an inconsequential change is less dramatic.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
