### PR TITLE
FineprintSoftware.Fineprint version 11.34

### PR DESCRIPTION
**Pull request by borque**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/97759)

### CODE REVIEW

**Comment by borque** [comment]
**I believe this might be an unsupported/untested scenario (or a bug) in winget-cli:**
fp1134.exe is a self-extracting zip, conatining all files necessary for installation in its root directory. At first winget states it extracted fp1134.exe successfully when working with this manifest. But then it says it could not find the nested installer. Looking into temp-directory instead of extracting the contents of sfx-zip fp1134.exe there, winget creates a file fp1134.zip there. This is a zip file with all the contents of the sfx again...
IMHO this can only be solved in winget-cli if it should be solved!?
If you agree with me, this should get the area-external-tag or smoething like that and someone more involved and with more experience might create an issue for winget-cli?! @denelon , @stephengillie , @Trenly perhaps?

**Comment by Trenly** [comment]
I think the issue is even simpler than that - The installer is an EXE, not a .zip file. Therefore, the installer type should be `exe` and the silent install switches should be used. It doesn't really matter that the EXE is a self-extracting zip, it's still just an exe file

**Comment by borque** [comment]
Hello @Trenly !
Basically you are right, it is an exe. But the silent-switches provided are not passed through to setup(-x64).exe after fp1134.exe is started with them and has finished extraction. Fineprint support suggests to extract the sfx by using 7-zip or WinRAR and then start setup(-x64).exe with the necessary arguments for a silent installation. That is why I hat the idea of declaring it a ZIP (which it also is somewhat).
Any idea how to solve this?

**Comment by Trenly** [comment]
Ah, I see. This might need a feature request for additional feature support at CLI

**Comment by borque** [comment]
I think it is remarkable, that winget-cli already seems to accept this (sfx-zip) exe as zip and processes it without an error message. The only problem is, that it is not successful and the output is not the content of the (sfx-exe) zip but another zip without the exe part. So perhaps such a feature request should be not too difficult to implement? (Just an uneducated guess)

**Comment by Trenly** [comment]
> I think it is remarkable, that winget-cli already seems to accept this (sfx-zip) exe as zip and processes it without an error message. The only problem is, that it is not successful and the output is not the content of the (sfx-exe) zip but another zip without the exe part. So perhaps such a feature request should be not too difficult to implement? (Just an uneducated guess)

Out of curiosity, what happens if you add the name of the zip folder that gets extracted to the relative file path?

**Comment by borque** [comment]
You mean someting like 
`- RelativeFilePath: fp1134.zip\setup-x64.exe` ?

**Comment by Trenly** [comment]
> As fp1134.zip is the file that winget-cli places into its temp diretory when working with this manifest, you mean someting like
> `- RelativeFilePath: fp1134.zip\setup-x64.exe` ?

Exactly

**Comment by borque** [comment]
This ( `- RelativeFilePath: fp1134.zip\setup-x64.exe` ) is handled like a regular folder by winget. 
Errormessage:
`Nested Installer file does not exist. [...] Temp\WinGet\FineprintSoftware.Fineprint.11.34\extracted\fp1134.zip\setup-x64.zip`

The contents of Temp\WinGet\FineprintSoftware.Fineprint.11.34\ are:
>    Directory: C:\Users\WDAGUtilityAccount\AppData\Local\Temp\WinGet\FineprintSoftware.Fineprint.11.34
>Mode                 LastWriteTime         Length Name
>d-----         2/25/2023   9:37 PM                extracted
>-a----         2/25/2023   9:37 PM       15763880 fp1134.zip

Where the directory "extracted" is empty and "fp1134.zip" has the same SHA256 as the original "fp1134.exe". So it was simply renamed and not touched in any way (e.g. by removing the wrapped exe part of a sfx-zip).

**Comment by stephengillie** [comment]
Hi @borque,

This package did not pass a malware scan:
> 2023-02-27 08:45:28.820 [CLI ] Archive malware scan failed

Packages must be free of malware to be accepted into WinGet's public manifests.

**Comment by Trenly** [comment]
> Hi @borque,
> 
> This package did not pass a malware scan:
> 
> > 2023-02-27 08:45:28.820 [CLI ] Archive malware scan failed
> 
> Packages must be free of malware to be accepted into WinGet's public manifests.

@stephengillie - The CLI error isn't a Defender error, it's the built-in archive malware scan failing. This will eventually be disabled in the pipelines, since the built-in scan only occurs when using a local manifest.

**Comment by stephengillie** [comment]
The installer is failing to find the nested installer. Zip extraction failed. 
```
2023-02-27 09:08:53.900 [CLI ] Archive scan detected malware. Proceeding due to --ignore-local-archive-malware-scan
2023-02-27 09:08:53.900 [CLI ] Extracting archive to: C:\Users\user\AppData\Local\Temp\WinGet\FineprintSoftware.Fineprint.11.34\extracted
2023-02-27 09:08:54.194 [CLI ] Successfully extracted archive
2023-02-27 09:08:54.196 [CLI ] Unable to locate nested installer at: C:\Users\user\AppData\Local\Temp\WinGet\FineprintSoftware.Fineprint.11.34\extracted\setup-x64.exe
2023-02-27 09:08:54.197 [CLI ] Terminating context: 0x8a15005b at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\ArchiveFlow.cpp:62
```

Zip file located at `C:\Users\user\AppData\Local\Temp\WinGet\FineprintSoftware.Fineprint.11.34\fp1134.zip` did not extract.

**Comment by borque** [comment]
So after all it might be best to close this PR and create an issue for winget-cli?!

**Comment by stephengillie** [comment]
> So after all it might be best to close this PR and create an issue for winget-cli?!

Maybe leave this open until the issue is resolved? Not sure how long it would take.

**Comment by ryfu-msft** [comment]
/azp run

> > So after all it might be best to close this PR and create an issue for winget-cli?!
> 
> Maybe leave this open until the issue is resolved? Not sure how long it would take.

We are currently looking into this issue so leave the PR open for now. Trenly is correct in that our archive malware scan was still enabled and your submission could be marked as a false positive. We'll report back once the changes have been deployed.

**Comment by stephengillie** [comment]
Manually attempting to extract the zipped files gives the error:
image

**Comment by borque** [comment]
I can not reproduce this problem, for me a manual extraction works without any problems.
Tried it with WinRAR 6.21 and 7-Zip 22.01. Both x64 on Win10 22H2.

**Comment by borque** [comment]
Hello @stephengillie !
Which further feedback from me could be of any help here?

**Comment by denelon** [comment]
@borque this needs to work with the "native" Windows decompression.

**Comment by denelon** [comment]
The installer URLs in the manifest both seem to point to an .exe file not a .zip file.

**Comment by borque** [comment]
Hello @denelon , thanks for your hints:

I tried to use expand-archive and indeed this fails to extract the file. So native Windows zip-support seems to be actually unable to handle this.

Concerning your exe-remark: this is what I was discussing with @Trenly at earlier stages of this PR starting around here: https://github.com/microsoft/winget-pkgs/pull/97759#issuecomment-1445141354

I will close this PR for now, but perhaps adding exe-zip-support might be an enhancement for winget-cli? Perhaps for 2.0-release?

**Comment by denelon** [comment]
I haven't looked at these directly, but I'm assuming they might be "self-extracting" archives. That would mean a new installer type, and some slightly different logic in WinGet to be able to run them to extract their contents and then reason about any necessary "path" related wiring to make them work properly.

**Pull request closed without merging**
