### PR TITLE
Diskuv.OCaml 1.1.0

### PR DESCRIPTION
**Pull request by jonahbeckford**
- [Y] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [Y] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [Y] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [Y] Have you tested your manifest locally with `winget install --manifest <path>`?
- [Y] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/92477)

### CODE REVIEW

**Comment by stephengillie** [comment]
The package may have run into a timeout in the automated validation pipeline. The installer installs its own dependencies, including Visual Studio and msys2. About 25 minutes into the install process, dependencies appear complete, and it's now installing the main package.

**Comment by jonahbeckford** [comment]
It takes 1hr 35mins in a Vagrant build on GitHub Actions. Also had few other people do testing on their PCs. What is the timeout limit? (I was under the impression the timeout was 2hrs when I submitted this package before … so I only resubmitted it now that it is faster).

**Comment by jonahbeckford** [comment]
Maybe it also tests the uninstaller? I see a bug which is waiting for user input there (can fix if that really is the problem).

**Comment by stephengillie** [comment]
I'm not sure of the current pipeline timeout limit. I'm guessing it reached a timeout since the install is lengthy, and the logs record the install beginning, then truncate. This install didn't complete, and a Unicode error caused an issue with the file watcher. I'll keep trying with this until I can give a better answer about why it's failing.

**Comment by jonahbeckford** [comment]
In the interest of not doing the same things twice:
1. My last PR was at https://github.com/microsoft/winget-pkgs/pull/69112
2. There is an important comment from a PR reviewer at https://github.com/microsoft/winget-pkgs/pull/69112#issuecomment-1213541409 about getting Windows Sandbox to work with a Windows Store prompt. I've codified that into more general-purpose test instructions at https://github.com/diskuv/dkml-installer-ocaml/tree/v1.1.0_r2/installer/winget#troubleshooting-with-windows-sandbox . *I think those general-purpose instructions should be somewhere on the winget-pkgs website*

**Comment by stephengillie** [comment]
The install isn't completing, but I'm having trouble finding logs showing why. Is there a way to enable logging in the installer?

**Comment by jonahbeckford** [comment]
> The install isn't completing, but I'm having trouble finding logs showing why. Is there a way to enable logging in the installer?

The logs will be at `$env:LOCALAPPDATA\Programs\DiskuvOCaml\setup-userprofile.full.log` assuming it finished installing Visual Studio. I don't have an easy way (yet) to redirect logs elsewhere. Is that log file around?

**Comment by jonahbeckford** [comment]
Also, submitted a change (`Diskuv.OCaml 1.1.0 release 2. Fixes uninstaller so playground uninstallation does not prompt user`) to have unprompted uninstallation as well.

**Comment by stephengillie** [comment]
Yes - here are the last lines:

```
2022-12-29T21:59:59.751Z [MSYS2] sh -eufcx dos2unix --newfile '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.sh'   '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.sh' && dos2unix --newfile '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.cmd'  '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.cmd' && dos2unix --newfile '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.cmake'  '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.cmake' && dos2unix --newfile '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.sexp' '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.sexp' && rm -f '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.sh' '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.cmd' '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.cmake' '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.sexp' && mv '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.sh'   '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.sh' && mv '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.cmd'  '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.cmd' && mv '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.cmake'  '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.cmake' && mv '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.sexp' '/c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars-v2.sexp'
+ dos2unix --newfile /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.sh /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.sh
dos2unix: converting UTF-16LE file /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.sh to ANSI_X3.4-1968 file /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.sh in Unix format...
+ dos2unix --newfile /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.cmd /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.cmd
dos2unix: converting UTF-16LE file /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.cmd to ANSI_X3.4-1968 file /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.cmd in Unix format...
+ dos2unix --newfile /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.cmake /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.cmake
dos2unix: converting UTF-16LE file /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.cmake to ANSI_X3.4-1968 file /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.cmake in Unix format...
+ dos2unix --newfile /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.sexp /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.sexp
dos2unix: converting UTF-16LE file /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.sexp to ANSI_X3.4-1968 file /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.sexp in Unix format...
+ rm -f /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.sh /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.cmd /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.cmake /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.utf16le-bom.sexp
+ mv /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.sh /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.sh
+ mv /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.cmd /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.cmd
+ mv /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.cmake /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.cmake
+ mv /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars.tmp.sexp /c/Users/user/AppData/Local/Programs/DISKUV~1/dkmlvars-v2.sexp
2022-12-29T21:59:59.985Z [pwsh]$ # Previous entry: [Environment]::SetEnvironmentVariable("DiskuvOCamlHome", "", "User")
2022-12-29T21:59:59.985Z [pwsh]$ [Environment]::SetEnvironmentVariable("DiskuvOCamlHome", "C:\Users\user\AppData\Local\Programs\DISKUV~1", "User")
2022-12-29T22:00:00.110Z [pwsh]$ # Previous entry: [Environment]::SetEnvironmentVariable("DiskuvOCamlVersion", "", "User")
2022-12-29T22:00:00.110Z [pwsh]$ [Environment]::SetEnvironmentVariable("DiskuvOCamlVersion", "1.1.0", "User")
2022-12-29T22:00:00.267Z [pwsh]$ # Previous entry: [Environment]::SetEnvironmentVariable("PATH", "C:\Users\user\AppData\Local\Microsoft\WindowsApps;", "User")
2022-12-29T22:00:00.267Z [pwsh]$ [Environment]::SetEnvironmentVariable("PATH", "C:\Users\user\AppData\Local\Programs\DISKUV~1\bin;C:\Users\user\AppData\Local\Programs\DISKUV~1\usr\bin;C:\Users\user\AppData\Local\Microsoft\WindowsApps;", "User")
```

**Comment by jonahbeckford** [comment]
> Yes - here are the last lines:
> 
> ```
> ...
> 2022-12-29T22:00:00.267Z [pwsh]$ [Environment]::SetEnvironmentVariable("PATH", "C:\Users\user\AppData\Local\Programs\DISKUV~1\bin;C:\Users\user\AppData\Local\Programs\DISKUV~1\usr\bin;C:\Users\user\AppData\Local\Microsoft\WindowsApps;", "User")
> ```

Now I am super confused. Those lines are the last lines of a successful install.

For example, my first and last lines are:

```
2022-12-29T11:52:43.593Z [Win32] C:\Program Files\Git\cmd\git.exe -C C:\Users\beckf\AppData\Local\Temp\PAF7E4~1\0 clone https://github.com/thekid/inotify-win.git
...
2022-12-29T12:32:36.710Z [pwsh]$ # Previous entry: [Environment]::SetEnvironmentVariable("PATH", "C:\Users\beckf\AppData\Local\Programs\DiskuvOCaml\0\bin;C:\Users\beckf\AppData\Local\Programs\DiskuvOCaml\0\usr\bin;C:\Users\beckf\.cargo\bin;C:\Users\beckf\AppData\Local\Microsoft\WindowsApps;C:\Users\beckf\AppData\Roaming\npm;Z:\ProgramFiles\ngrok;C:\Users\beckf\AppData\Local\Programs\Microsoft VS Code\bin;Z:\ProgramFiles\apache-maven-3.8.4\bin;Z:\ProgramFiles\unison-v2.51.5-ocaml-4.12.0-x86_64.windows\bin;C:\Users\beckf\AppData\Local\Microsoft\WindowsApps;Z:\ProgramFiles\CMake\bin;C:\Users\beckf\.dotnet\tools;", "User")
2022-12-29T12:32:36.710Z [pwsh]$ [Environment]::SetEnvironmentVariable("PATH", "C:\Users\beckf\AppData\Local\Programs\DISKUV~1\bin;C:\Users\beckf\AppData\Local\Programs\DISKUV~1\usr\bin;C:\Users\beckf\AppData\Local\Programs\DiskuvOCaml\0\bin;C:\Users\beckf\AppData\Local\Programs\DiskuvOCaml\0\usr\bin;C:\Users\beckf\.cargo\bin;C:\Users\beckf\AppData\Local\Microsoft\WindowsApps;C:\Users\beckf\AppData\Roaming\npm;Z:\ProgramFiles\ngrok;C:\Users\beckf\AppData\Local\Programs\Microsoft VS Code\bin;Z:\ProgramFiles\apache-maven-3.8.4\bin;Z:\ProgramFiles\unison-v2.51.5-ocaml-4.12.0-x86_64.windows\bin;C:\Users\beckf\AppData\Local\Microsoft\WindowsApps;Z:\ProgramFiles\CMake\bin;C:\Users\beckf\.dotnet\tools;", "User")
```

**Comment by jonahbeckford** [comment]
Is it possible to see what `winget install` options are being invoked in `WinGetSvc-Validation (Installer Validation)`?

My manifest has:

```yaml
InstallModes:
  - silent
  - interactive
InstallerSwitches:
  Silent: --ci --quiet --color=never
  SilentWithProgress: --ci
  Interactive: --color=always
  InstallLocation: --prefix "<INSTALLPATH>"
```

and when using either `.\Tools\SandboxTest.ps1 ...` or `winget install --manifest ...` it invokes the silent switches.

Those silent switches are important so that `--ci` is passed along. The `--ci` option avoids a final user prompt on the console about exiting the installer.

Perhaps that isn't working in `WinGetSvc-Validation (Installer Validation)` ?

**Comment by stephengillie** [comment]
> Now I am super confused. Those lines are the last lines of a successful install.

I opened a new window in the VM, and with this was able to launch all programs and perform a Defender scan, completing a manual validation.

The issue here is that the Windows Path in the registry is being updated, but the $env:PATH of the current window isn't. So Validation (running from the same window) gets errors when running executables and links. This is also seen when Git and other path-based applications are installed as dependencies: 
* https://github.com/microsoft/winget-pkgs/issues/90650

This is based off the current console window's $env:PATH variable: 
>C:\Windows\system32;
>C:\Windows;
>C:\Windows\System32\Wbem;
>C:\Windows\System32\WindowsPowerShell\v1.0\;
>C:\Windows\System32\OpenSSH\;
>C:\Users\user\AppData\Local\Microsoft\WindowsApps

Compared to the $env:PATH variable of the new window: 
>C:\Windows\system32;
>C:\Windows;
>C:\Windows\System32\Wbem;
>C:\Windows\System32\WindowsPowerShell\v1.0\;
>C:\Windows\System32\OpenSSH\;
>C:\Program Files\Git\cmd;
>C:\Users\user\AppData\Local\Programs\DISKUV\~1\bin;
>C:\Users\user\AppData\Local\Programs\DISKUV\~1\usr\bin;
>C:\Users\user\AppData\Local\Microsoft\WindowsApps

Unfortunately I don't have access to the validation pipeline to run `winget info`.

**Comment by jonahbeckford** [comment]
> The issue here is that the Windows Path in the registry is being updated, but the $env:PATH of the current window isn't. So Validation (running from the same window) gets errors when running executables and links. 

Interesting. I suppose I could inject the PATH updates into the current window ... that would take a bit of development but is doable. But I'm not sure it is right; injecting environment variables is quite a hacky thing to do!

Question 1: Do you suggest I inject the PATH updates? (If yes, it would be more robust if the `--pid` of the winget current window was passed to the installer switch. Not strictly necessary though.)

I'm also not setting the Git.Git dependency (and Visual Studio Build Tools) in the manifest because I saw all the warnings that dependencies are not used in winget.

Question 2: Should I model the dependencies in the manifest?

**Comment by stephengillie** [comment]
Injecting PATH updates might be a bit excessive. We could change the validation pipeline to install in one window and open a new window for testing. Basically, automate the process described above. But feel free if you really want to. 😁

Winget currently installs the first listed dependency. Hopefully additional dependencies will be supported soon. With this package's numerous dependencies, it might be more streamlined to keep the current arrangement.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
