### PR TITLE
New package: EvanSu.Picocrypt version 1.32

### LINKED ISSUE #92436: [Package Request]: Picocrypt
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: HACKERALERT
Publisher Url: https://github.com/HACKERALERT/Picocrypt
Package Name: Picocrypt
Description: A very small, very simple, yet very secure encryption tool.
Package Version: 1.31
Installer URL: https://github.com/HACKERALERT/Picocrypt/releases/download/1.31/Picocrypt.exe

Current Package Identifier (for new versions):

### PR DESCRIPTION
**Pull request by mdanish-kh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

- Resolves https://github.com/microsoft/winget-pkgs/issues/92436
 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/109575&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @mdanish-kh,

This package doesn't seem to have any output: 
image

Is this expected?

**Comment by mdanish-kh** [comment]
@stephengillie Yes, the portable app is a GUI application. It doesn't have a CLI output

**Comment by stephengillie** [comment]
Oh - GUI applications usually spawn a window when launched from Terminal, but I don't see one here. 
 Launching from File Explorer window also doesn't seem to generate any output or window, nor tray icon. Also no logging to the Application log nor its folder. I'm having difficulty determining how to interact with this package.

**Comment by HACKERALERT** [comment]
Hmm that's weird, it's a GUI application that you can double click to run. A window should pop up.

**Comment by stephengillie** [comment]
Unfortunately, double-clicking on the icon has a similarly-muted response.

**Comment by HACKERALERT** [comment]
Alright, thanks for the attempt. I'll try to create the manifest files myself to see if I can get them working.

**Comment by HACKERALERT** [comment]
Okay so I've created the manifest files and installed them successfully with `winget install -m .`

I can run Picocrypt via the command below, however, I can't run it with `picocrypt`. Is that not added to the PATH?
```
"C:\Users\<user>\AppData\Local\Microsoft\WinGet\Packages\EvanSu.Picocrypt__DefaultSource\Picocrypt.exe"
```
[manifest_files.zip](https://github.com/microsoft/winget-pkgs/files/11729936/manifest_files.zip)

**Comment by mdanish-kh** [comment]
@stephengillie, that's odd I can install the manifest and run the portable app fine (both from the full path, and just the command alias `picocrypt`) on both my personal PC and a VM. I also tested both in user shell (to prevent symlink creation) and in admin shell to launch the app through the symlink. All methods work for me. It may be possible that the executable has a **dependency** on a certain package/runtime?

image


@HACKERALERT you may need to restart the shell process for PATH changes to have effect. If you're using Windows Terminal, that would mean closing and restarting it (not a new tab). You can further check the PATH variable if you're using PowerShell through `$env:PATH` or just typing `PATH` if you're on CMD. Look for either `C:\Users\<user>\AppData\Local\Microsoft\WinGet\Links` or `C:\Users\<user>\AppData\Local\Microsoft\WinGet\Packages\EvanSu.Picocrypt__DefaultSource` in the PATH variable.

Also, may I ask what version of WinGet (`winget -v`) you both are running please? I'm on the [1.5 rc-1](https://github.com/microsoft/winget-cli/releases/tag/v1.5.1572)

**Comment by stephengillie** [comment]
A dependency is probable, but I'm not seeing any errors to suggest which one it might be.

**Comment by HACKERALERT** [comment]
Not quite sure what "dependency" means in this context, but no, Picocrypt shouldn't be using anything like .NET runtime or C++ redistributables. It's a Go app compiled statically. Here are the DLL imports (analyzed with VirusTotal):

image

So yeah it shouldn't be using anything external, other than maybe OpenGL.

I'm using winget v1.4.11071 in the standard command prompt (I'm old lol), so I don't know if that makes a difference.

Also, I'm experimenting with making an installer via InnoSetup. If that is successful and we use that installer instead of the portable executable, then start menu entries should be added assuming that the InnoSetup installer adds it right? That might be a better and more reliable idea. I'll give it a go.

**Comment by HACKERALERT** [comment]
Alrighty, I've made an InnoSetup .exe installer that installs Picocrypt, and it works as well in winget! If everything validates, I think this is the optimal setup.

[manifest_files.zip](https://github.com/microsoft/winget-pkgs/files/11740044/manifest_files.zip)

**Comment by mdanish-kh** [comment]
> Not quite sure what "dependency" means in this context, but no, Picocrypt shouldn't be using anything like .NET runtime or C++ redistributables. It's a Go app compiled statically. Here are the DLL imports (analyzed with VirusTotal):

Yep, I was referring to any external package, runtime that may be required on the system before the installation of picocrypt

> Also, I'm experimenting with making an installer via InnoSetup. If that is successful and we use that installer instead of the portable executable, then start menu entries should be added assuming that the InnoSetup installer adds it right? That might be a better and more reliable idea. I'll give it a go.

Yes, but keep in mind that when creating the installer, you'll have to modify the installer yourself if you want the command to be accessible through the PATH variable. With an installer, WinGet simply executes it with relevant InstallerSwitches for a silent installation, but whether the installer itself adds the executable to the PATH variable or not depends on its specific behavior.

**Comment by mdanish-kh** [comment]
[Policy] reset feedback

**Comment by HACKERALERT** [comment]
> Yes, but keep in mind that when creating the installer, you'll have to modify the installer yourself if you want the command to be accessible through the PATH variable.

Yup that's okay, since now that the program is added to the start menu, there's no need.

Thanks for updating the PR! All the labels are green now so hopefully everything will work.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
