### PR TITLE
Added SumatraPDF.SumatraPDF version 3.3.2

### PR DESCRIPTION
**Pull request by ImJoakim**
image

```
PS C:\Users\WDAGUtilityAccount\Desktop\manifests> winget install -m "C:\Users\WDAGUtilityAccount\Desktop\manifests\s\SumatraPDF\SumatraPDF\3.3.2"
Found SumatraPDF [SumatraPDF.SumatraPDF]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://kjkpubsf.sfo2.digitaloceanspaces.com/software/sumatrapdf/rel/SumatraPDF-3.3.2-64-install.exe
  ██████████████████████████████  6.95 MB / 6.95 MB
Successfully verified installer hash
Starting package install...
Successfully installed

PS C:\Users\WDAGUtilityAccount\Desktop\manifests> winget install -m "C:\Users\WDAGUtilityAccount\Desktop\manifests\s\SumatraPDF\SumatraPDF\3.3.2"
Found SumatraPDF [SumatraPDF.SumatraPDF]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://kjkpubsf.sfo2.digitaloceanspaces.com/software/sumatrapdf/rel/SumatraPDF-3.3.2-install.exe
  ██████████████████████████████  6.34 MB / 6.34 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/21866)

### CODE REVIEW

**Comment by ImJoakim** [comment]
🤔

**Comment by ImJoakim** [comment]
Is the bot not re-running anymore after close -> open 😕

**Comment by ImJoakim** [comment]
@denelon @ChuckFerring I believe this needs the `Azure-Pipeline-Passed` label for a Moderator to approve and merge it.

**Comment by ImJoakim** [comment]
@ItzLevvie Are you able to approve & merge this with only the `Azure-Pipeline-Passed` tag, or does it need `Validation-Completed` too.

**Review by ItzLevvie — APPROVED** [review]

**Comment by ImJoakim** [comment]
Oof

**Comment by quhxl** [comment]
This bot is taking some kind of drugs...

**Comment by ImJoakim** [comment]
You got this bot, I believe in you!

**Comment by ImJoakim** [comment]
@ChuckFerring @palenshus Can one of you add the `Validation-Completed` label?

**Pull request merged**
