### PR TITLE
Update: Datadog.dd-trace-dotnet version 1.28.2

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23743)

### CODE REVIEW

**Comment by lucaspimentel** [comment]
Does anyone know what is causing the `Installer Validation` check to fail?

**Comment by OfficialEsco** [comment]
@ChuckFerring get back here and add `Azure-Pipeline-Passed`
cc @denelon again..

**Review by ItzLevvie — APPROVED** [review]

**Comment by denelon** [comment]
@OfficialEsco we're doing some work on this. We are hoping not to require "Azure-Pipelines-Passed". If we grant a waiver or perform a Manual Validation/Approval, we'd like the labels to reflect the true state of what happened.

**Comment by denelon** [comment]
We're also seeing some interesting behavior with the GitHub APIs.

When a bunch of PRs are being evaluated, we're seeing null on the mergeable_state.

Checking against the [GitHub API documentation](https://docs.github.com/rest/reference/pulls#get-a-pull-request) a null value means that GitHub is running a background task to compute mergeability

The value of the mergeable attribute can be true, false, or null. If the value is null, then GitHub has started a background job to compute the mergeability. After giving the job time to complete, resubmit the request. When the job finishes, you will see a non-null value for the mergeable attribute in the response. If mergeable is true, then merge_commit_sha will be the SHA of the test merge commit.


GitHub

**Review by denelon — APPROVED** [review]

**Pull request merged**
