### PR TITLE
Fix ARP detection: FNMT.ConfiguradorFNMT version 4.0.4

### PR DESCRIPTION
**Pull request by MaanuelMM**
The purpose of this pull request is to fix the detection of the `FNMT.ConfiguradorFNMT` installation based on its ARP entry so that future updates can be offered on existing installations. ~~The behavior related to the `UpgradeBehavior` is also changed.~~ I reverted back to the original `UpgradeBehavior`.

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131674)

### CODE REVIEW

**Comment by MaanuelMM** [comment]
Maybe the exact same thing is happening as with the previous pull request I made a little over a month ago (#126988)?

> Automatic Validation ended with: image
> 
> > Remember that you need AutoFirma for different options. If you do not have it installed you can download it at https:/firmaelectronica.gob.es/
> > (Internet Translation)
> 
> This reflects a pipeline issue. Sorry for any concern caused.

If not, I would like to see a screenshot where the installation hangs and determine if it is possible to fix it.

**Comment by MaanuelMM** [comment]
As I mentioned yesterday, maybe it has to do with the pipeline error that happened on #126988 a month ago but I'm not sure without a screenshot.

I've also reverted to the previous `upgradeBehavior` setting (`install`) due to a misconfiguration error on my end that led me to believe it was set incorrectly.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 

(Automated response - build 509.)

**Comment by MaanuelMM** [comment]
The AutoFirma dependency is already set:

```yaml
Dependencies:
  PackageDependencies:
  - PackageIdentifier: SpanishGovernment.Autofirma
```

In fact, exactly the same thing is happening as in the first pull request of this package ([#126988](https://github.com/microsoft/winget-pkgs/pull/126988#issuecomment-1816925172)).

**Comment by stephengillie** [comment]
This PR omits these files that are present in the current manifest:
> @{InputObject=yaml; SideIndicator=<=}

(Automated response - build 513.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
