### PR TITLE
FxSoundLLC.FxSound version 1.1.7.0

### PR DESCRIPTION
**Pull request by SmilerRyan**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15350)

### CODE REVIEW

**Comment by SmilerRyan** [comment]
> 
> 
> Hello @SmilerRyan,
> During installation testing, this application failed to install without user input. Did you forget to add Silent or SilentWithProgress switches?
> 
> Please investigate a fix and resubmit the Pull Request.
> 
> You may also try using the [Windows Package Manager Manifest Creator](https://github.com/microsoft/winget-create).


Assuming Visual C++ 2015-2019 Redists are installed the software installs without any user input from the setup.
is it possible to have the test run with these redists installed?

**Comment by SmilerRyan** [comment]
I don't think the mentioned pull request is related to this software.

**Comment by ItzLevvie** [comment]
Closing PRs that haven't had any author response for x amount of days.

**Comment by ItzLevvie** [comment]
Hash mismatch:
image

With updated hash - stuck on this prompt:
image
image

**Comment by SmilerRyan** [comment]
Okay then.

**Pull request closed without merging**
