### PR TITLE
New version: GiulioSorrentino.wheelofnumfortune.avalonia version 2.0.3-1

### PR DESCRIPTION
**Pull request by GiulianoSpaghetti**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/166110)

### CODE REVIEW

**Comment by stephengillie** [comment]
> [GiulianoSpaghetti](/GiulianoSpaghetti)

Hi @GiulianoSpaghetti,

Has this version already been submitted?

**Comment by GiulianoSpaghetti** [comment]
It still report 2.0.3.

Thanks.

**Comment by stephengillie** [comment]
If the package manager isn't showing the new version, then we need to fix the current issue. Adding more manifests might make the problem worse, or at least unpredictable.

**Comment by stephengillie** [comment]
Hi @GiulianoSpaghetti,

This version also reports `2.0.3` - even the application doesn't list the `-1`. 
image

Where is this supposed to show up - inside the application, in the package manager, or in the Registry? Does the installer need to be updated to add the `-1`?

**Comment by GiulianoSpaghetti** [comment]
The 2.0.3 should point to https://github.com/GiulianoSpaghetti/numfortune.avalonia.new/releases/download/2.0.3/numfortune.Avalonia-2.0.3-amd64.msi
and
https://github.com/GiulianoSpaghetti/numfortune.avalonia.new/releases/download/2.0.3/numfortune.Avalonia-2.0.3-arm64.msi

That are made with avalonia 11.0.11.

The -1 version, instead, to
https://github.com/GiulianoSpaghetti/numfortune.avalonia.new/releases/download/2.0.3/numfortune.Avalonia-2.0.3-1-amd64.msi
And
https://github.com/GiulianoSpaghetti/numfortune.avalonia.new/releases/download/2.0.3/numfortune.Avalonia-2.0.3-1-arm64.msi


Thanks.

________________________________

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
