### PR TITLE
New version: Bedrock-OSS.regolith version 1.5.0

### LINKED ISSUE #195507: [Update Request]: Bedrock-OSS/regolith to 1.5.0
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Bedrock-OSS.regolith

### Package Version

1.5.0

### Please describe the changes you would like to see

There is a new release available.

- Download link: https://github.com/Bedrock-OSS/regolith/releases/tag/1.5.0
- Related Pull Request: https://github.com/microsoft/winget-pkgs/pull/195505

### PR DESCRIPTION
**Pull request by Nusiq**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

Resolve #195507

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/195505)

### CODE REVIEW

**Comment by theaddonn** [comment]
LGTM!

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 899.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
