### PR TITLE
New version: Microsoft.Sysinternals.Sysmon 15.11

### PR DESCRIPTION
**Pull request by TommyE123**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/Sysinternals/Sysmon/15.11` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132232)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @TommyE123,

This PR appears to add 2 manifests. Is this intentional?
image

**Comment by stephengillie** [comment]
I had just validated this, to clear the `Validation-Executable-Error` from the `15.0` version.

**Comment by TommyE123** [comment]
After finding out that 

> I had just validated this, to clear the `Validation-Executable-Error` from the `15.0` version.

Sorry I had to undo removing the old version as you made me aware earlier that I couldn't remove and add at the same time.

Hopefully this is correct now.
Tom

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
