### PR TITLE
Added Dell Update version 4.1.0.

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with winget validate <manifest>, where <manifest> is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with winget install -m <manifest>?

----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/8761)

### CODE REVIEW

**Comment by jedieaston** [comment]
All of the URLs are valid, I believe this is another case of the URL verification failing if there is a query string in the URL. If you cut off everything after the question mark the page 404s, but if you leave the query string on you get a page, so I think that's what's causing the hiccup.

```
-----------------------------------------------------
Manifest: manifests\Dell\DellUpdate\4.1.0.yaml
-----------------------------------------------------
URI: https://www.dell.com/support/home/en-us/drivers/driversdetails?driverid=ckwj2, Validation result: Failed, Http status code: NotFound 
URI: https://www.dell.com/learn/us/en/uscorp1/legal_terms-conditions_dellgrmwebpage/art-software-license-agreements, Validation result: Passed
URI: https://dl.dell.com/FOLDER06986434M/1/Dell-Update-Application-for-Windows-10_7CKK6_WIN_4.1.0_A00.EXE, Validation result: Passed

****************************************************************************************
Manifest Content Validation
****************************************************************************************
Status: Completed
##[error] Result: Failed
```

See #7920 for another instance of this bug.

**Comment by KevinLaMS** [comment]
/AzurePipelines run
running again.  If it fails assign to ashwini.

**Comment by jedieaston** [comment]
No, @msftbot, wait! This is part of a bug!

**Comment by jedieaston** [comment]
Darn, the bug still exists :(.

**Comment by jedieaston** [comment]
gee this @msftbot guy is pretty slow on the uptake.

**Comment by denelon** [comment]
> gee this @msftbot guy is pretty slow on the uptake.

They are hard to train sometimes 🤣

**Pull request closed without merging**
