### PR TITLE
Update version: Minio.Client version latest

### PR DESCRIPTION
**Pull request by weeix**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/111538&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation failed with:
> 8:06:44 AM:  2023-07-07 08:06:43.162 [CLI ] Package hash verification failed. SHA256 in manifest [f783a5c55a51ee123009c830b1d129f77d7d8f399b0ffd26ae80c074fcf1f226] does not match download [f54c8fb6bc0526dbd5ca32dc4c577acd719839bd78923da9674df788342578dd]

**Review by CoolPlayLin — CHANGES_REQUESTED** [review]
image

**Pull request closed without merging**
