### PR TITLE
mpv.net: new version 7.0.0.6

### PR DESCRIPTION
**Pull request by soredake**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131151)

### CODE REVIEW

**Comment by candrapersada** [comment]
is it possible to add `yt-dlp` as a Dependency?

**Comment by soredake** [comment]
@candrapersada yes, but yt-dlp is not required for mpv.net to work so i am not sure if i want to do this.

winget should implements something like scoop's "suggest" for such deps.

**Comment by soredake** [comment]
It installs fine in vm and on my machine.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978334972

(Automated response - build 490.)

**Comment by candrapersada** [comment]
[v7.0.0.5-beta](https://github.com/mpvnet-player/mpv.net/releases/tag/v7.0.0.5-beta)

**Review by candrapersada — APPROVED** [review]

**Review by candrapersada — APPROVED** [review]
good

**Comment by candrapersada** [comment]
[v7.0.0.6-beta](https://github.com/mpvnet-player/mpv.net/releases/tag/v7.0.0.6-beta)

**Comment by soredake** [comment]
I don't know what i can do if it installs correctly for me.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978334972

(Automated response - build 552.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
