### PR TITLE
gdiObjects.fotoXplorer version 1.0.2108.21

### PR DESCRIPTION
**Pull request by gdiObjects**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

### CODE REVIEW

**Comment by gdiObjects** [comment]
the manifests are generated by 'wingetcreate 0.3.0.6' I don't under stand the error message:
"The PR could not be validated because there is a merge conflict which adds bad characters to the manifest. Please address the merge conflict and resubmit."

please advise.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
You can close the PR since this package was automatically updated by @wingetbot.

**Comment by gdiObjects** [comment]
> 
> 
> You can close the PR since this package was automatically updated by @wingetbot.

it still says, "Review Required" and "Merging is blocked."  Has the PR been successfully processed?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Yes, the PR was successfully merged and processed.

Take a look at https://github.com/microsoft/winget-pkgs/pull/27033

**Pull request closed without merging**
