### PR TITLE
New package: dessant.BusterClient version 0.3.0

### LINKED ISSUE #140960: [Package Request]: Buster Client
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/dessant/buster-client/releases
Publisher: dessant
Package Name: Buster Client
Description: Client to help users complete captchas
Package Version: 0.3.0
Installer URL: https://github.com/dessant/buster-client/releases

### PR DESCRIPTION
**Pull request by Exorcism0666**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.1.1 :rocket:

- Resolves #140960

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140963)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
This might be due to a network block of data centers, to prevent automated downloads.

(Automated response - build 821.)

**Comment by Exorcism0666** [comment]
@stephengillie What should I do ?

**Comment by stephengillie** [comment]
If you have a relationship with the developer or someone who works for the developer, they might be able to unblock our data center IP addresses.

**Comment by Exorcism0666** [comment]
> If you have a relationship with the developer or someone who works for the developer, they might be able to unblock our data center IP addresses. 

@kuro68k

**Comment by kuro68k** [comment]
Apologies, can you explain the issue? It is downloading from Github, so I assume that's not the issue. Is it saying that something about the installer requires network access and the resource is blocked to the integration server?

Once I understand it I will raise an issue on their project. It would help to have details of the network that is blocked. Azure?

**Comment by stephengillie** [comment]
Hi @kuro68k,

Our logs show that the installer download appears to have been blocked. This shouldn't be happening from GitHub, so might be masking another situation. 

(Please forgive the bot response - I'm testing some permissions changes and waiting on a bug to be fixed.)

**Comment by kuro68k** [comment]
No problem. I'll hold off for now, it does seem strange that a GitHub download would fail.

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 869.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-07 18:28:05.292 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerSharedLib\SHA256.cpp(144)\WindowsPackageManager.dll!552E158E: (caller: 55325FA6) Exception(1) tid(1050) 8A150040 
> 2024-03-07 18:28:10.681 [FAIL] Installer failed security check. Url: https://github.com/dessant/buster-client/releases/download/v0.3.0/buster-client-setup-v0.3.0-windows-386.exe Result: 0x80004005

(Automated response - build 869.)

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 869.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-08 21:54:00.401 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerSharedLib\SHA256.cpp(144)\WindowsPackageManager.dll!5564158E: (caller: 55685FA6) Exception(1) tid(1d2c) 8A150040 
> 2024-03-08 21:54:05.575 [FAIL] Installer failed security check. Url: https://github.com/dessant/buster-client/releases/download/v0.3.0/buster-client-setup-v0.3.0-windows-386.exe Result: 0x80004005

(Automated response - build 869.)

**Comment by kuro68k** [comment]
Maybe Microsoft is flagging it because it is software to bypass annoying captchas.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-12 20:31:11.554 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerSharedLib\SHA256.cpp(144)\WindowsPackageManager.dll!558F158E: (caller: 55935FA6) Exception(1) tid(788) 8A150040 
> 2024-03-12 20:31:17.760 [FAIL] Installer failed security check. Url: https://github.com/dessant/buster-client/releases/download/v0.3.0/buster-client-setup-v0.3.0-windows-386.exe Result: 0x80004005

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-13 15:27:45.321 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerSharedLib\SHA256.cpp(144)\WindowsPackageManager.dll!552F158E: (caller: 55335FA6) Exception(1) tid(1c40) 8A150040 
> 2024-03-13 15:27:49.611 [FAIL] Installer failed security check. Url: https://github.com/dessant/buster-client/releases/download/v0.3.0/buster-client-setup-v0.3.0-windows-386.exe Result: 0x80004005

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 871.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-14 08:33:45.549 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerSharedLib\SHA256.cpp(144)\WindowsPackageManager.dll!5549158E: (caller: 554D5FA6) Exception(1) tid(1cb8) 8A150040 
> 2024-03-14 08:33:50.696 [FAIL] Installer failed security check. Url: https://github.com/dessant/buster-client/releases/download/v0.3.0/buster-client-setup-v0.3.0-windows-386.exe Result: 0x80004005

(Automated response - build 871.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Installer https://github.com/dessant/buster-client/releases/download/v0.3.0/buster-client-setup-v0.3.0-windows-amd64.exe
 Scan request id: '5e81d28c-f52b-4a53-9e08-028dfc8a3d6c'
 
 Installer https://github.com/dessant/buster-client/releases/download/v0.3.0/buster-client-setup-v0.3.0-windows-386.exe
 Scan request id: 'aa298649-be2b-4c9e-a3ac-439122139fd5'
 Error information: BlockingDetectionFound
 
 3/20/2024 2:28:54 PM
 
 ****************************************************************************************

(Automated response - build 871.)

**Comment by stephengillie** [comment]
This might be due to a network block of data centers, to prevent automated downloads.

(Automated response - build 871.)

**Pull request closed without merging**
