### PR TITLE
[Remove package] WHONETAutomationTool

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/123573)

### CODE REVIEW

**Comment by Trenly** [comment]
Why is this package being removed?

**Comment by drshtmstry** [comment]
> Why is this package being removed?

Package is not used by many people.
No one uses winget for installing this package.

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/pull/123574#issuecomment-1777727767

**Comment by drshtmstry** [comment]
> [#123574 (comment)](https://github.com/microsoft/winget-pkgs/pull/123574#issuecomment-1777727767)

This package is for very selected users (Microbiologists).
I am the one submitted it to winget-pkgs in the  first place, and being a Microbiologist myself, I know that many users don't use  this package. Most of the Microbiologists don't even know what "winget" is.
This  package uses vanity URL for release which causes frequent installer hash mismatch errors.
Repeatedly submitting new versions is not something that I can do in the long run.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
