### PR TITLE
Modify: Spotify.Spotify version 1.1.99.878.g1e4ccc6e

### PR DESCRIPTION
**Pull request by SpecterShell**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/89683)

### CODE REVIEW

**Review by russellbanks — CHANGES_REQUESTED** [review]
The pull request error is because there is one deletion and one modification (which is seen as a deletion and an addition). Please change this pull request to do one or the other.

**Comment by russellbanks** [comment]
As the `ElevationRequirement: elevationProhibited` is required but causes the validation to fail, it likely just needs a waiver.

**Review by russellbanks — APPROVED** [review]

**Comment by SpecterShell** [comment]
@denelon @stephengillie

**Comment by denelon** [comment]
@SpecterShell thanks for the ping. We're actually testing some of the code on the back end for dealing with "elevationProhibted" in the validation pipeline.

**Comment by stephengillie** [comment]
> @SpecterShell thanks for the ping. We're actually testing some of the code on the back end for dealing with "elevationProhibted" in the validation pipeline.

Yes, with a new version of Winget in my testing VM, (and a non-elevated PowerShell window,) this package installs fully unattended. It should pass validation once the new version is in the pipelines. 
* https://github.com/microsoft/winget-cli/releases/tag/v1.4.3132-preview

**Comment by denelon** [comment]
It looks like we're going to need to add a waiver for the domain change and do a manual review here. The back end isn't going to be ready for this scenario soon enough.

**Pull request merged**
