### PR TITLE
New version: Jackett.Jackett version 0.21.2850

### PR DESCRIPTION
**Pull request by ilike2burnthing**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/155674)

### CODE REVIEW

**Review by russellbanks — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-29 23:19:59.103 [FAIL] Installer failed security check. Url: https://github.com/Jackett/Jackett/releases/download/v0.21.2850/Jackett.Installer.Windows.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 882.)

**Comment by ilike2burnthing** [comment]
Just commenting to clear the `Needs-Author-Feedback` label.

**Comment by ilike2burnthing** [comment]
.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-30 17:33:43.131 [FAIL] Installer failed security check. Url: https://github.com/Jackett/Jackett/releases/download/v0.21.2850/Jackett.Installer.Windows.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 882.)

**Pull request merged**
