### PR TITLE
New package: EFLFE.PingoMeter version 0.9.9

### PR DESCRIPTION
**Pull request by grigoryvp**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/178129)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\pingometer.exe returned exit code: -1073741819
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\pingometer.exe returned exit code: -532462766

Automated error analysis suggests -1073741819 may mean Converted to hexadecimal (C0000005) possibly [Access Violation](https://learn.microsoft.com/en-us/shows/inside/access-violation-c0000005-execute). (This is occasionally seen in PRs despite the install otherwise being successful. Should it be added as an `InstallerSuccessCode` or similar here?)

Automated error analysis suggests -532462766 may mean EXCEPTION_COMPLUS (Unhandled Exception)

(Automated response - build 896.)

**Comment by stephengillie** [comment]
Verify:
image
The symlink can't reach files needed by the application. Here, it's `none.png`. Running from the main folder gives:
image
image

**Comment by grigoryvp** [comment]
@stephengillie thank you a lot for your help! It seems that I have tested the installer not on a "clear" system but on a system there pingometer was already added to PATH, my bad.

I briefly checked the pingometer source code and indeed there is this [line](https://github.com/EFLFE/PingoMeter/blob/269577089ac702a420c73a58990f08b765f6265e/NotificationIcon.cs#L80) that incorrectly gets executable file location, which results in "current directory" being used.

Is it possible for WinGet to install a traditional portable app that just adds app directory to `PATH` and expects "current directory" to be the directory where the `.exe` file is located?

**Comment by grigoryvp** [comment]
I have used the new `ArchiveBinariesDependOnPath` WinGet 1.9 flag to add app's directory to the `PATH`. This should do the trick!

**Comment by grigoryvp** [comment]
Updated and ready for review, I do not understand why Microsoft bot decides that there is "no activity"

**Pull request closed without merging**
