### PR TITLE
WK Radar 7.5.0.405

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/110371&drop=dogfoodAlpha

### CODE REVIEW

**Comment by WKSistemas** [comment]
> @WKSistemas please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement



> @WKSistemas please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement



> @WKSistemas please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree company="WK WK Sistemas de Computação Ltda."

**Review by ghost — COMMENTED** [review]
Submit new yaml.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Singletons are discontinued. Please move over to multi-file manifests — YamlCreate; Komac; and wingetcreate can do this automatically for you.

**Review by ghost — COMMENTED** [review]
Revised file

**Review by ghost — COMMENTED** [review]
Moved over to multi-file manifests

**Review by ghost — COMMENTED** [review]
New review, with installer argument.

**Review by ghost — COMMENTED** [review]
InstallerSwitches:
    Custom: "/qb"

**Review by ghost — COMMENTED** [review]
Update with Manifest Version 1.4.0

**Comment by WKSistemas** [comment]
@ItzLevvie I changed and validated, according to your considerations. Thanks!
@stephengillie  @JohnMcPMS In local tests, using SandboxTest.ps1/Windows Sandbox, the process completed successfully.

**Review by ghost — COMMENTED** [review]
Removal of quotes in tags session

**Comment by WKSistemas** [comment]
> This package appears to be exhausting the validation pipeline's available memory: image

I believe that it is not the app itself, it is very light and this one specifically in the image (WK CR) only uses elements through the Remote App.
What I imagine might be blocking the process is this message (called "Alarm 1202"), which is a simple warning to the end user that the server is running low on resources. An OK and it is finished.
In time: this MSI has several executables (used or not depending on the application's end user profile), so if the automated test opens them all at once without finishing, I believe that at some point, on a very simple machine, the resources may be run out.

**Comment by stephengillie** [comment]
> I believe that it is not the app itself, it is very light and this one specifically in the image (WK CR) only uses elements through the Remote App. What I imagine might be blocking the process is this message (called "Alarm 1202"), which is a simple warning to the end user that the server is running low on resources. An OK and it is finished. In time: this MSI has several executables (used or not depending on the application's end user profile), so if the automated test opens them all at once without finishing, I believe that at some point, on a very simple machine, the resources may be run out.

Apologies - part of validation is to run all installed applications at once, and perform a Defender scan. This is a very memory-intensive process, so this is more in regards to the volume of applications and the pipeline's available memory, and wouldn't be indicative of any individual application's performance.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
