### PR TITLE
Tor.Tor version 0.4.5.8

### PR DESCRIPTION
**Pull request by techflashYT**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14889)

### CODE REVIEW

**Comment by ItzLevvie** [comment]
Tor Browser already exists in `t/TorProject/TorBrowser/10.0.16/TorProject.TorBrowser.yaml`

**Comment by sanikdah** [comment]
Again, I did search for it so idk.
image

**Comment by ItzLevvie** [comment]
> Again, I did search for it so idk.
> image
winget search torbrowser: 
image

**Comment by sanikdah** [comment]
ahh alright, I have a suggestion to keep stuff like this from happening, when searching for a program maybe also add any search results that would come up if that search query was typed in without spaces (and the other way around)?

**Comment by OfficialEsco** [comment]
I bet that manifest is wrong, eitherway that is what tags are for which shitty wingetcreate don’t support.

**Comment by denelon** [comment]
@sanikdah be sure to add your 👍 https://github.com/microsoft/winget-cli/issues/1059

**Comment by sanikdah** [comment]
> @sanikdah be sure to add your 👍 [microsoft/winget-cli#1059](https://github.com/microsoft/winget-cli/issues/1059)

I did, I wasn't able to immediately because I was asleep 2 hours ago lol.

**Pull request closed without merging**
