### PR TITLE
New version: astral-sh.ruff version 0.1.14

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136018)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 8:16:50 AM: 2024-01-24 08:16:49.880 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.1.14/ruff-0.1.14-x86_64-pc-windows-msvc.zip Result: 0x80004005

(Automated response - build 629.)

**Comment by stephengillie** [comment]
Hi @Trenly,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 629.)

**Comment by stephengillie** [comment]
Hi @Trenly,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 656.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-25 12:45:10.850 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.1.14/ruff-0.1.14-i686-pc-windows-msvc.zip Result: 0x80004005 MSI (s) (00:64) [12:44:55:971]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (00:E0) [12:44:57:002]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Additional Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [1AAC:1BBC][2024-01-25T12:44:54]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 656.)

**Comment by stephengillie** [comment]
Hi @Trenly,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 656.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-25 12:45:10.850 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.1.14/ruff-0.1.14-i686-pc-windows-msvc.zip Result: 0x80004005 MSI (s) (00:64) [12:44:55:971]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (00:E0) [12:44:57:002]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Additional Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [1AAC:1BBC][2024-01-25T12:44:54]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 656.)

**Comment by stephengillie** [comment]
This package has failed a Defender scan twice. Should we keep rescanning?

**Comment by Trenly** [comment]
> This package has failed a Defender scan twice. Should we keep rescanning?

Lets give it a few more days before trying one final scan

**Comment by stephengillie** [comment]
Hi @Trenly,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 679.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-25 12:45:10.850 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.1.14/ruff-0.1.14-i686-pc-windows-msvc.zip Result: 0x80004005 MSI (s) (00:64) [12:44:55:971]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (00:E0) [12:44:57:002]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Additional Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [1AAC:1BBC][2024-01-25T12:44:54]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 679.)

**Comment by stephengillie** [comment]
Hi @Trenly,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 679.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-25 12:45:10.850 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.1.14/ruff-0.1.14-i686-pc-windows-msvc.zip Result: 0x80004005 MSI (s) (00:64) [12:44:55:971]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (00:E0) [12:44:57:002]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Additional Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [1AAC:1BBC][2024-01-25T12:44:54]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 679.)

**Comment by stephengillie** [comment]
Hi @Trenly,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 695.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-30 13:41:54.060 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.1.14/ruff-0.1.14-x86_64-pc-windows-msvc.zip Result: 0x80004005 MSI (s) (74:9C) [13:41:35:934]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (74:FC) [13:41:36:887]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Additional Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [14A4:0374][2024-01-30T13:41:33]w363: Could not create system restore point, error: 0x80070422. Continuing... 2024-01-30 16:22:36.968 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.1.14/ruff-0.1.14-i686-pc-windows-msvc.zip Result: 0x80004005 MSI (s) (C0:38) [16:22:22:483]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Minimum Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (C0:30) [16:22:23:483]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X86 Additional Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [061C:04CC][2024-01-30T16:22:20]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 695.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 2:44:39 PM: 
> 2024-02-02 14:44:37.720 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.1.14/ruff-0.1.14-x86_64-pc-windows-msvc.zip Result: 0x80004005

(Automated response - build 695.)

**Comment by stephengillie** [comment]
Hi @Trenly,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 695.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 707.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
