### PR TITLE
Remove version: Parsec.Parsec version 150.92.1.0

### LINKED ISSUE #142695: [Package Issue]: Parsec.Parsec version schema mismatch
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Parsec's installer versioning mismatches the version schema on the installed application

On the latest version of Parsec, installer will report `150.92.1.0` whereas the installed version will be `150-92a` (as of time of writing, Parsec will also automatically update to `150-92b` after install, however that doesn't appear in the Installed version details right away, unsure as how that works entirely), making it appear in the upgrade list.

Installer details
image

Installed version details
image

### Steps to reproduce

1. `winget install Parsec.Parsec`
2. `winget upgrade`

### Actual behavior

Parsec gets listed in the upgrade list
```
Name      Id               Version    Available     Source
----------------------------------------------------------
Parsec    Parsec.Parsec    150-92a    150.92.1.0    winget
```

### Expected behavior

Parsec doesn't appear in the upgrade list

### Environment

```raw
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3007
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0
```

### Screenshots and Logs

_No response_

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/142701)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://builds.parsec.app/package/parsec-windows.exe 
Status Code: 200

(Automated message - build 861)

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 861.)

**Comment by stephengillie** [comment]
URL: https://builds.parsec.app/package/parsec-windows.exe 
Status Code: 200

(Automated message - build 861)

**Comment by stephengillie** [comment]
URL: https://builds.parsec.app/package/parsec-windows.exe 
Status Code: 200

(Automated message - build 867)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
