### PR TITLE
New version: snakefoot.snaketail version 1.9.8.0

### PR DESCRIPTION
**Pull request by TejasMate**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141519)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @TejasMate,

Is the `MinimumOSVersion` no longer needed - does this install on all recent versions of Windows?

**Comment by TejasMate** [comment]
Yeah, this packages supports both 10, 11

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/pull/142030#issuecomment-1977122523

**Comment by stephengillie** [comment]
Hi @TejasMate,

> This PR's version number 1.9.8 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 1.9.7.0, which has 4 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 861)

**Comment by stephengillie** [comment]
Hi @TejasMate,

This manifest adds Apps and Features entries that aren't present in previous PR versions. These entries should be added to the previous versions, or removed from this version.

(Automated response - build 861.)

**Comment by stephengillie** [comment]
> Yeah, this packages supports both 10, 11

I missed this earlier, sorry.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
