### PR TITLE
BalazsTihanyi.NClass version 2.04

### PR DESCRIPTION
**Pull request by TechnicaVivunt**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/51110)

### CODE REVIEW

**Comment by Trenly** [comment]
image
@denelon - Dependencies

**Comment by TechnicaVivunt** [comment]
Should I go ahead and close out this PR until support is added for dependencies?

**Comment by denelon** [comment]
@TechnicaVivunt you may add the dependency to the manifest, and leave this PR. When we have support for dependencies, we will run validation on the PRs with the "Dependency" label, and if they pass, they will be merged in. Note this could take many months. Dependencies aren't likely to start functioning until the 1.4 release (possibly EOY 2022).

**Review by ItzLevvie — APPROVED** [review]

**Comment by denelon** [comment]
Hey @TechnicaVivunt, we're now doing validation with dependencies if you want to add them to the manifest :)

**Pull request closed without merging**
