### PR TITLE
New package: foamzou.media-get version 0.2.10

### PR DESCRIPTION
**Pull request by SpecterShell**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/110647&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
Should this package have a dependency on `Gyan.FFmpeg`?
> ffmpeg or ffprobe not found, please install them first.

**Comment by stephengillie** [comment]
> Should this package have a dependency on `Gyan.FFmpeg`?
> 
> > ffmpeg or ffprobe not found, please install them first.

This package displays this message even when in the same folder as FFmpeg. 
image

**Comment by SpecterShell** [comment]
> > Should this package have a dependency on `Gyan.FFmpeg`?
> > > ffmpeg or ffprobe not found, please install them first.
> 
> This package displays this message even when in the same folder as FFmpeg. image

It works for me though. You may need to enable developer mode due to the bugs from WinGet mentioned in <https://github.com/microsoft/winget-pkgs/issues/95349>.
And to use the FFmpeg in the same folder you have to `cd` to that directory first.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
