### PR TITLE
New package: Stern.Stern version 1.25.0 (#112222)

### PR DESCRIPTION
**Pull request by BoSoeborgPetersen**
* New package: Stern.Stern version 1.25.0

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/112223&drop=dogfoodAlpha

### CODE REVIEW

**Comment by BoSoeborgPetersen** [comment]
@microsoft-github-policy-service agree

**Comment by BoSoeborgPetersen** [comment]
#112222

**Comment by mdanish-kh** [comment]
[Policy] Blocking-Issue

Blocked by
- https://github.com/microsoft/winget-cli/issues/2899

**Comment by denelon** [comment]
I'm going to go ahead and close this PR since the blocking issue is linked in comments above. Be sure to upvote that issue with a 👍so progress can be followed.

**Comment by BoSoeborgPetersen** [comment]
How does that solve anything?
How about fixing the blocking issue and then this PR can be merged.

**Pull request closed without merging**
