### PR TITLE
Create LINQPad 8.0.16 manifest

### PR DESCRIPTION
**Pull request by tiksn**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/128066)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 2023-11-27 15:33:27.135 [CLI ] Package hash verification failed. SHA256 in manifest 
[8e4b1577b2afb9c794048fc0de5f353ff268c756dd06b61e5249835818aa36d2] does not match download 
[4dd8f19d9f4e5b0b0c7fe7dac299606c8d87822dac3383ee1b3539834b388633]

**Comment by stephengillie** [comment]
Hi @tiksn,

This package has numerous dependencies:
image

Can you help me to enumerate all of them?

**Comment by tiksn** [comment]
@stephengillie unfortunately I have all dependencies installed locally apparently, so I was not able to catch that.

**Comment by tiksn** [comment]
Hi @roehl-ottri , thanks for your comment.

I fixed the second part of your comment. Overtime, while the PR is open, I must update it from time to time. Unfortunately, LinqPad is not providing versioned URLs to installers. 

As for `microsoft.netcore.app.ref` and `microsoft.windowsdesktop.app.ref`, those are Shared Frameworks, that should be installed by `Microsoft.DotNet.Runtime.8` and `Microsoft.DotNet.DesktopRuntime.8`.

Please correct me if I am wrong.

**Comment by roehl-ottri** [comment]
The .ref.app packages are not shared frameworks, that would be part of the Runtime. They are packages containing reference assemblies. According to the [NuGet packages page](https://www.nuget.org/packages/Microsoft.NETCore.App.Ref) they are:

> Internal implementation package not meant for direct consumption.

**Comment by albahari** [comment]
`microsoft.netcore.app.ref` and `microsoft.windowsdesktop.app.ref` contain the .NET reference assemblies. These do not come with the standard .NET 8 desktop runtime - they come only when you install the full .NET SDK (as they are considered design-time assets).

LINQPad will prompt to download these (only) if you haven't installed the full .NET SDK. In the context of winget, it is probably easiest to consider these a LINQPad dependency and download them always.

LINQPad requires the .NET Reference assemblies for exactly the same reason that Visual Studio requires them. The only difference is that Visual Studio requires that you install the full .NET SDK for frameworks that you wish to target, whereas with LINQPad, your queries can target frameworks for which just the .NET Desktop Runtime + reference assemblies are present.

(LINQPad author)

**Comment by albahari** [comment]
Another solution would be to make the .NET 8 SDK a requirement (if that's possible).

**Comment by roehl-ottri** [comment]
Ah... that makes a lot of sense. Thanks,  @albahari !

I'm not familiar enough with winget manifests to know if it supports NuGet package dependencies, but the full SDK is available for sure.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
