### PR TITLE
New version: Amazon.Corretto.11 version 11.0.22.7

### PR DESCRIPTION
**Pull request by ccorrion**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135109)

### CODE REVIEW

**Comment by ccorrion** [comment]
@stephengillie Now that the pipelines are back, can we restart on this PR? (And is there a better way to do this than pinging you?)

Thanks!

**Comment by stephengillie** [comment]
> @stephengillie Now that the pipelines are back, can we restart on this PR? (And is there a better way to do this than pinging you?)
> 
> Thanks!

Ideally, the PR re-run would restart these.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
