### PR TITLE
New version: Microsoft.VCRedist.2022.arm64 version 14.38.33130.0

### PR DESCRIPTION
**Pull request by imfelixlaw**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/126999)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @imfelixlaw,

Unfortunately, we do not have any validation pipelines capable of validating this package.

**Comment by imfelixlaw** [comment]
> Hi @imfelixlaw,
> 
> Unfortunately, we do not have any validation pipelines capable of validating this package.

Hi @stephengillie 

You can manually download the File via the link in the manifest 

https://download.visualstudio.microsoft.com/download/pr/f04bd1f4-d474-4dc1-bb63-5c059bb86c55/BAC344CBC947DB8E306986BFB45A33052E1AAEE8F104ADBD9E461EB8199E27D2/VC_redist.arm64.exe

The source is from here 

https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170#visual-studio-2015-2017-2019-and-2022

Architecture = ARM64

This link https://aka.ms/vs/17/release/vc_redist.arm64.exe
will redirect to https://download.visualstudio.microsoft.com/download/pr/f04bd1f4-d474-4dc1-bb63-5c059bb86c55/BAC344CBC947DB8E306986BFB45A33052E1AAEE8F104ADBD9E461EB8199E27D2/VC_redist.arm64.exe

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Review by denelon — APPROVED** [review]

**Comment by denelon** [comment]
manually tested and verified on arm64

**Pull request merged**
