### PR TITLE
Remove "Preview" from PowerToys

### PR DESCRIPTION
**Pull request by auanasgheps**
Removing "Preview", as this is a stable version.

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/178581)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 896)

**Review by stephengillie — APPROVED** [review]

**Comment by crutkas** [comment]
This is incorrect, we are preview

**Comment by auanasgheps** [comment]
@crutkas maybe I am wrong, but [here ](https://github.com/microsoft/PowerToys/releases) the 0.85 is flagged as "latest" and not preview.

**Comment by crutkas** [comment]
PowerToys is Preview.  This is intentional

**Comment by auanasgheps** [comment]
I thought this was treated as many other packages - a stable version and a preview version.

My bad, I am creating a new pull request and reverting this.

**Pull request merged**
