### PR TITLE
GiulioSorrentino.WinDateFrom version 4.1.3

### PR DESCRIPTION
**Pull request by GiulianoSpaghetti**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140326)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 776.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-20 20:35:49.508 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-20 20:36:42.267 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-20 20:37:03.216 [FAIL] Installer failed security check. Url: https://github.com/numerunix/WinDateFrom.avalonia/releases/download/4.1.3/WinDateFrom.Avalonia-4.1.3-x64.msi Result: 0x80004005 2024-02-20 20:37:03.216 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (C4:38) [20:36:01:575]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (C4:38) [20:36:03:231]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg MSI (s) (C4:38) [20:36:11:653]: Windows Installer installed the product. Product Name: Microsoft .NET Runtime - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (C4:58) [20:36:20:465]: Windows Installer installed the product. Product Name: Microsoft .NET Host FX Resolver - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (C4:80) [20:36:25:684]: Windows Installer installed the product. Product Name: Microsoft .NET Host - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (C4:84) [20:36:31:450]: Windows Installer installed the product. Product Name: Microsoft Windows Desktop Runtime - 8.0.2 (x64). Product Version: 64.8.8806. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 776.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-21 08:15:38.836 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-21 08:16:18.260 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-21 08:16:38.274 [FAIL] Installer failed security check. Url: https://github.com/numerunix/WinDateFrom.avalonia/releases/download/4.1.3/WinDateFrom.Avalonia-4.1.3-x64.msi Result: 0x80004005 2024-02-21 08:16:38.274 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (98:5C) [08:15:50:872]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (98:5C) [08:15:52:372]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg MSI (s) (98:5C) [08:16:00:685]: Windows Installer installed the product. Product Name: Microsoft .NET Runtime - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (98:3C) [08:16:03:497]: Windows Installer installed the product. Product Name: Microsoft .NET Host FX Resolver - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (98:FC) [08:16:04:732]: Windows Installer installed the product. Product Name: Microsoft .NET Host - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (98:6C) [08:16:10:013]: Windows Installer installed the product. Product Name: Microsoft Windows Desktop Runtime - 8.0.2 (x64). Product Version: 64.8.8806. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 796.)

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 797.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-21 08:15:38.836 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-21 08:16:18.260 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-21 08:16:38.274 [FAIL] Installer failed security check. Url: https://github.com/numerunix/WinDateFrom.avalonia/releases/download/4.1.3/WinDateFrom.Avalonia-4.1.3-x64.msi Result: 0x80004005 2024-02-21 08:16:38.274 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (98:5C) [08:15:50:872]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (98:5C) [08:15:52:372]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg MSI (s) (98:5C) [08:16:00:685]: Windows Installer installed the product. Product Name: Microsoft .NET Runtime - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (98:3C) [08:16:03:497]: Windows Installer installed the product. Product Name: Microsoft .NET Host FX Resolver - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (98:FC) [08:16:04:732]: Windows Installer installed the product. Product Name: Microsoft .NET Host - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (98:6C) [08:16:10:013]: Windows Installer installed the product. Product Name: Microsoft Windows Desktop Runtime - 8.0.2 (x64). Product Version: 64.8.8806. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 797.)

**Comment by numerunix** [comment]
it's blocked by defender

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 800.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-21 08:15:38.836 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-21 08:16:18.260 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-21 08:16:38.274 [FAIL] Installer failed security check. Url: https://github.com/numerunix/WinDateFrom.avalonia/releases/download/4.1.3/WinDateFrom.Avalonia-4.1.3-x64.msi Result: 0x80004005 2024-02-21 08:16:38.274 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (98:5C) [08:15:50:872]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (98:5C) [08:15:52:372]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg MSI (s) (98:5C) [08:16:00:685]: Windows Installer installed the product. Product Name: Microsoft .NET Runtime - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (98:3C) [08:16:03:497]: Windows Installer installed the product. Product Name: Microsoft .NET Host FX Resolver - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (98:FC) [08:16:04:732]: Windows Installer installed the product. Product Name: Microsoft .NET Host - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (98:6C) [08:16:10:013]: Windows Installer installed the product. Product Name: Microsoft Windows Desktop Runtime - 8.0.2 (x64). Product Version: 64.8.8806. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 800.)

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 812.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-22 14:00:45.516 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-22 14:01:34.508 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-22 14:01:52.505 [FAIL] Installer failed security check. Url: https://github.com/numerunix/WinDateFrom.avalonia/releases/download/4.1.3/WinDateFrom.Avalonia-4.1.3-x64.msi Result: 0x80004005 2024-02-22 14:01:52.505 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (3C:14) [14:00:58:702]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (3C:14) [14:01:00:421]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg MSI (s) (3C:14) [14:01:04:718]: Windows Installer installed the product. Product Name: Microsoft .NET Runtime - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (3C:E4) [14:01:09:640]: Windows Installer installed the product. Product Name: Microsoft .NET Host FX Resolver - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (3C:68) [14:01:15:358]: An error occured while refreshing environment variables updated during the installation of ''. Some users logged on to the machine may not see these changes until they log off and then log back on. MSI (s) (3C:68) [14:01:16:624]: Windows Installer installed the product. Product Name: Microsoft .NET Host - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (3C:E8) [14:01:24:202]: Windows Installer installed the product. Product Name: Microsoft Windows Desktop Runtime - 8.0.2 (x64). Product Version: 64.8.8806. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 812.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
