### PR TITLE
update ea desktop

### PR DESCRIPTION
**Pull request by Masamune3210**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/55017)

### CODE REVIEW

**Comment by Masamune3210** [comment]
honestly not sure what the bot is on about, winget says the manifest validated successfully  and i dont see any issues just looking at it

**Comment by Masamune3210** [comment]
never mind, dont make manifests half asleep lol

**Comment by Masamune3210** [comment]
Ok, never seen that one before. Manifest works fine, I'm currently downloading a game from the app correctly installed from the manifest

**Comment by Trenly** [comment]
Duplicate of #55044

**Comment by Masamune3210** [comment]
There is a hash mismatch which this solves

**Comment by Trenly** [comment]
> There is a hash mismatch which this solves

Yes, but the PR I linked above is for the same change and doesn't have the Validation-Installation-Error; It will fix the Hash Mismatch just like this PR would

**Comment by Masamune3210** [comment]
Ok, still not quite sure whats causing the bot to think the install failed, but I guess if the other one is already passing this one is a moot point

**Comment by ItzLevvie** [comment]
> Ok, still not quite sure whats causing the bot to think the install failed, but I guess if the other one is already passing this one is a moot point

Looks like it was missing the InstallerSwitches:
```yaml
InstallerSwitches:
  Custom: ACCEPT=YES
  Upgrade: /upgrade
```

**Pull request closed without merging**
