### PR TITLE
Sharkdp/bat/0.22.1

### PR DESCRIPTION
**Pull request by neomax7**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://api.github.com/repos/microsoft/winget-pkgs/pulls/95489)

### CODE REVIEW

**Comment by neomax7** [comment]
hello 
the manifest validates and it installs on my laptop without an error. 
is there anyway to check the reason why **winget-svc-validation (installer validation)** process failed here?
thanks in advance

**Comment by sitiom** [comment]
> hello the manifest validates and it installs on my laptop without an error. is there anyway to check the reason why **winget-svc-validation (installer validation)** process failed here? thanks in advance

Just wait for a moderator to approve your PR manually. Do not keep closing and creating new ones.

**Comment by neomax7** [comment]
> > hello the manifest validates and it installs on my laptop without an error. is there anyway to check the reason why **winget-svc-validation (installer validation)** process failed here? thanks in advance
> 
> Just wait for a moderator to approve your PR manually. Do not keep closing and creating new ones (I see you already have created 16 closed PRs of the same thing).

okay, thanks I will wait.
my bad on closed PRs, 
I did closed/opened them, trying to re-initiate validation pipeline.
and just for the note, its not same 16, it is 4 different packages.

**Comment by sitiom** [comment]
> I did closed/opened them, trying to re-initiate validation pipeline.

You can reopen the same PR without making a new one.

**Comment by neomax7** [comment]
> > I did closed/opened them, trying to re-initiate validation pipeline.
> 
> You can reopen the same PR without making a new one.

giphy

**Comment by neomax7** [comment]
Hi, just checking on the progress

**Comment by sitiom** [comment]
@neomax7 Try retriggering the pipelines in your PR

**Comment by neomax7** [comment]
> @neomax7 Try retriggering the pipelines in your PRs

Hi Sitiom,
I am not sure, how to manually retrigger the pipeline,, could you give me a hand?

thank you

**Comment by sitiom** [comment]
Like I said before, try closing and reopening this PR

**Comment by stephengillie** [comment]
Hi @neomax7,

The package installs normally, but requires `Microsoft.VCRedist.2015+.x64` (or `x86`) to run:
image

**Comment by neomax7** [comment]
> Hi @neomax7,
> 
> The package installs normally, but requires `Microsoft.VCRedist.2015+.x64` (or `x86`) to run: image

thank you sir, I just added missing dependencies ! :)

**Comment by stephengillie** [comment]
> thank you sir, I just added missing dependencies ! :)

Unfortunately, it's still generating the same error.

**Comment by Trenly** [comment]
[Policy] Blocking-Issue

**Comment by kritr-msft** [comment]
@stephengillie Just out of curiosity, I thought winget itself had a dependency on vcruntime140.dll ?
At least based on my efforts to use it within Windows Sandbox required me to install the vcredist package before winget.
https://github.com/microsoft/winget-pkgs/blob/master/Tools/SandboxTest.ps1

**Comment by Trenly** [comment]
> @stephengillie Just out of curiosity, I thought winget itself had a dependency on vcruntime140.dll ?
> At least based on my efforts to use it within Windows Sandbox required me to install the vcredist package before winget.
> https://github.com/microsoft/winget-pkgs/blob/master/Tools/SandboxTest.ps1

VC Redist and VC Libs are two separate things. WinGet is dependent upon the VCLibs UWP package, which is not the same as `Microsoft.VCRedist.2015+.[x86 | x64]`

**Review by sitiom — CHANGES_REQUESTED** [review]
- https://github.com/microsoft/winget-pkgs/pull/100636

**Pull request closed without merging**
