### PR TITLE
New version: VMware.WorkstationPlayer version 16.2.1

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/34577)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Gonna wait for https://github.com/microsoft/winget-pkgs/pull/34576#issuecomment-965577095

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
rerun-pipelines-please

**Comment by vedantmgoyal2009** [comment]
/rerun-pipelines-please

Let me test once.

**Comment by o-l-a-v** [comment]
As mentioned here:

* https://github.com/microsoft/winget-cli/issues/229#issuecomment-1013688799

VMWare Workstation, ```winget upgrade --id VMware.WorkstationPlayer``` does not work.

```winget install --id VMware.WorkstationPlayer``` over existing version forced a reboot.

**Pull request merged**
