### PR TITLE
Update: Prusa3D.PrusaSlicer version 2.3.2

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/93941)

### CODE REVIEW

**Comment by stephengillie** [comment]
This package version also prompts to install a newer version.
image

Is there an installer switch to bypass this prompt?

**Comment by stephengillie** [comment]
Here is the installer's output when queried: 
image

**Comment by denelon** [comment]
Does it do the same thing when installed with "--silent"?

As long as the latest version honors our intent, and earlier versions would have done so, they would have been grandfathered in.

**Comment by stephengillie** [comment]
Found it!
`/exenoupdates`

**Comment by stephengillie** [comment]
> Found it! `/exenoupdates`

After running with both switches `/exenoupdates /passive`, the install runs silently. But then it prompts to install a driver: 
image

**Comment by Trenly** [comment]
> Found it! `/exenoupdates`

Perfect! Doesn't work on my end when using the `Custom:` installer switches; Probably they need to be in a certain order. Putting them both into the `SilentWithProgress` worked. I think that it would still pass validation since the process controlling the driver prompt is a sub-process and not tied to the installer completing

> As long as the latest version honors our intent, and earlier versions would have done so

Can confirm that 2.5.0 (latest) does install silently

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
