### PR TITLE
Ferdium.Ferdium.Nightly version 6.0.0-nightly.99

### PR DESCRIPTION
**Pull request by Alphrag**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/66248)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
What's the difference between `Ferdium.Ferdium` and `Ferdium.Ferdium.Nightly`?

Both of them are using nightly URLs: https://github.com/microsoft/winget-pkgs/blob/5e0255aca2809e7bb8dca5df248b22873f8db710/manifests/f/Ferdium/Ferdium/6.0.0.0/Ferdium.Ferdium.installer.yaml#L8-L23

**Comment by Alphrag** [comment]
> What's the difference between `Ferdium.Ferdium` and `Ferdium.Ferdium.Nightly`?

Hi @ItzLevvie thanks for having a look at that. 
I created the winget bucket thinking that we could put all of the releases under `Ferdium.Ferdium` by allowing an install tag for the different types of prereleases, but I only saw after submitting it that `winget` does not support release channels like this. So I moved the nightly and beta into their own id, and we will keep `Ferdium.Ferdium` only for stable release (the first one is coming soon). Should I submit a PR to remove `Ferdium.Ferdium` in the meantime?

**Review by ItzLevvie — APPROVED** [review]

**Comment by Alphrag** [comment]
Hey @ItzLevvie, it seems like the bot has forgotten to take out the `needs-attention` tag. If you could remove it at any point, that would be great. Thanks :-)

**Pull request merged**
