### PR TITLE
New version: Starship.Starship version 1.17.0

### PR DESCRIPTION
**Pull request by davidkna**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132044)

### CODE REVIEW

**Comment by davidkna** [comment]
It installs without issues on my local machine and in the sandbox test (x86_64).

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 
> 2023-12-28 20:15:26.883 [FAIL] Installer failed security check. Url: https://github.com/starship/starship/releases/download/v1.17.0/starship-i686-pc-windows-msvc.msi Result: 0x80004005

(Automated response - build 508.)

**Comment by stephengillie** [comment]
Hi @davidkna,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 509.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
