### PR TITLE
add xmake v2.3.6

### PR DESCRIPTION
**Pull request by waruqi**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2941)

### CODE REVIEW

**Comment by perplexityjeff** [comment]
I'd suggest to add the switches to the end of the file as well?

Switches:
      Silent: /S
      SilentWithProgress: /S

**Comment by waruqi** [comment]
> waruqi The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.

What's the installation errors?

**Comment by KevinLaMS** [comment]
Grrr.  i thought i pasted it in.  I will retry

**Comment by perplexityjeff** [comment]
Firstly I think the installer should be set to nullsoft instead of exe however even after doing that the installer returns with an exit code: 1223. 

The issue is mostly the same as here https://github.com/microsoft/winget-pkgs/pull/843. When using /S the exit code 1223 is not supported yet it seems?

**Comment by waruqi** [comment]
> microsoft/winget-cli#137

Then how should I configure manifest to fix this problem? I did not find a solution about it from this issue.

**Comment by perplexityjeff** [comment]
I don't think you can fix it with your manifest. You could update your nullsoft installer to return exit code 0 if ran silently. Or wait until https://github.com/microsoft/winget-cli/issues/137 is implemented.

**Comment by KevinLaMS** [comment]
We are blocked at the moment.  :(

**Comment by waruqi** [comment]
I don't know how to modify the my installer.nsi script so that it can return the exit code 0

https://github.com/xmake-io/xmake/blob/master/scripts/installer.nsi

**Comment by perplexityjeff** [comment]
@waruqi I am not an expert on NSIS by far but maybe this change that was made in FileZilla can help you as well. or wait until winget supports using custom exit codes for success. 

https://forum.filezilla-project.org/viewtopic.php?t=36679
https://svn.filezilla-project.org/filezilla/FileZilla3/trunk/data/install.nsi.in?r1=6557&r2=6628&pathrev=6628

**Comment by waruqi** [comment]
> @waruqi I am not an expert on NSIS by far but maybe this change that was made in FileZilla can help you as well. or wait until winget supports using custom exit codes for success.
> 
> https://forum.filezilla-project.org/viewtopic.php?t=36679
> https://svn.filezilla-project.org/filezilla/FileZilla3/trunk/data/install.nsi.in?r1=6557&r2=6628&pathrev=6628

Ok, I will try it. thanks!

**Comment by waruqi** [comment]
> @waruqi I am not an expert on NSIS by far but maybe this change that was made in FileZilla can help you as well. or wait until winget supports using custom exit codes for success.
> 
> https://forum.filezilla-project.org/viewtopic.php?t=36679
> https://svn.filezilla-project.org/filezilla/FileZilla3/trunk/data/install.nsi.in?r1=6557&r2=6628&pathrev=6628

@perplexityjeff I have fixed it, thanks!

**Comment by perplexityjeff** [comment]
@waruqi I can confirm as well when testing your file that it all works fine, nice!

@denelon, @KevinLaMS  I think we are all set to merge?

**Comment by waruqi** [comment]
> During installation testing, this app triggered a Microsoft Defender SmartScreen error.
> 
> We are notifying [WDNotify@microsoft.com](mailto:WDNotify@microsoft.com) for investigation.

? What is this problem?

**Comment by perplexityjeff** [comment]
@waruqi, SmartScreen got triggered during installation. I hope that the team can fix this for you and get it merged, I can't help you with this one :(. I see no reason why it would not get fixed tho. 

Maybe we can get @KevinLaMS to get a status?

**Comment by waruqi** [comment]
> @waruqi, SmartScreen got triggered during installation. I hope that the team can fix this for you and get it merged, I can't help you with this one :(. I see no reason why it would not get fixed tho.
> 
> Maybe we can get @KevinLaMS to get a status?

@perplexityjeff Ok, Thanks!

**Pull request merged**
