### PR TITLE
Dead Pull - Nvidia.PhysXLegacy version 9.13.0604

### PR DESCRIPTION
**Pull request by Masamune3210**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/27556)

### CODE REVIEW

**Comment by Masamune3210** [comment]
Can't figure out where this package went, it said it merged and all checked out but the manifest is missing from the repo. Was it removed?

**Comment by vedantmgoyal2009** [comment]
Duplicate of #27446

**Comment by vedantmgoyal2009** [comment]
To resolve Git Path Collision, #27444

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/27446

**Comment by Masamune3210** [comment]
Either I'm blind or missing something because, Nvidia.PhysxLegacy is nowhere in the Nvidia folder 
image

**Comment by Masamune3210** [comment]
Also is not being detected in winget list

**Comment by Masamune3210** [comment]
Sorry, completely missed that part. Still getting used to git

**Pull request closed without merging**
