### PR TITLE
New version: StefHeyenrath.GitHubReleaseNotes 1.0.10.1

### PR DESCRIPTION
**Pull request by StefH**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140361)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @StefH,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 776.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-21 03:42:02.376 [FAIL] Installer failed security check. Url: https://github.com/StefH/GitHubReleaseNotes/releases/download/1.0.10.1/GitHubReleaseNotes.zip Result: 0x80004005 2024-02-21 03:42:02.376 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6

(Automated response - build 776.)

**Comment by StefH** [comment]
Hello @stephengillie,

Can you please advice what to check? Because the Azure Pipelines do not display any error information, so I don't know what's wrong.

Note that I've changed this application to a .NET 8 : **SelfContained** and **SingleFile**:
``` xml
<PublishSingleFile>true</PublishSingleFile>
<SelfContained>True</SelfContained>
<PublishTrimmed>false</PublishTrimmed>
```

Installing the application locally works fine.
``` xmd
winget install --manifest  1.0.10.1

Found GitHubReleaseNotes [StefHeyenrath.GitHubReleaseNotes] Version 1.0.10.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "GitHubReleaseNotes"
Successfully installed
```

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-22 21:51:54.053 [FAIL] Installer failed security check. Url: https://github.com/StefH/GitHubReleaseNotes/releases/download/1.0.10.1/GitHubReleaseNotes.zip Result: 0x80004005 2024-02-22 21:51:54.054 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6

(Automated response - build 808.)

**Comment by stephengillie** [comment]
> Hello @stephengillie,
> 
> Can you please advice what to check? Because the Azure Pipelines do not display any error information, so I don't know what's wrong.

Hi @StefH,

Sorry for the lack of information. These logs are in the ADO run artifacts, which are several links off the main ADO pipeline, inside a ZIP file. 

- From the ADO pipeline run, 
- Find the link named [4 published; 1 consumed](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=546476&view=artifacts&pathAsName=false)
  - This might be "3 published 1 consumed" or another variation of integers. 
- Find "InstallationVerificationLogs" line and follow to the far right edge. 
- Click the 3 dots, and click "Download artifacts"
- Unzip the download, scrape for "error", "fail", and "exception". 

Or feel free to use the [script](https://github.com/microsoft/winget-pkgs/blob/4de203131a5a8e85396eba211fde4864d70360c5/Tools/ManualValidationPipeline.ps1#L992) I made to automate this.

**Comment by stephengillie** [comment]
Hi @StefH,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 813.)

**Comment by stephengillie** [comment]
Hi @StefH,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 821.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-26 06:24:35.056 [FAIL] Installer failed security check. Url: https://github.com/StefH/GitHubReleaseNotes/releases/download/1.0.10.1/GitHubReleaseNotes.zip Result: 0x80004005 2024-02-26 06:24:35.056 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6

(Automated response - build 821.)

**Comment by stephengillie** [comment]
Hi @StefH,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 855.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-02-28 07:57:55.158 [FAIL] Installer failed security check. Url: https://github.com/StefH/GitHubReleaseNotes/releases/download/1.0.10.1/GitHubReleaseNotes.zip Result: 0x80004005

(Automated response - build 855.)

**Comment by stephengillie** [comment]
Hi @StefH,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 858.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-01 10:06:20.676 [FAIL] Installer failed security check. Url: https://github.com/StefH/GitHubReleaseNotes/releases/download/1.0.10.1/GitHubReleaseNotes.zip Result: 0x80004005

(Automated response - build 858.)

**Comment by stephengillie** [comment]
Hi @StefH,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 861.)

**Comment by StefH** [comment]
@stephengillie 
I see indeed that the scan on the Windows machine shows an error from Microsoft Defender Antivirus:
InstallationVerification-x64-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20240304185307

---

However scanning the zip file locally does not reveal any issues.


Also uploading the zip file to https://www.virustotal.com shows no errors:
image

What can I do to resolve this?

**Comment by stephengillie** [comment]
Hi @StefH,

What's needed to resolve is to pass a Defender scan within the validation pipeline. My automation would be retrying, but this is blocked. If you could commit any change - even something mundane such as a line break or space - it would also trigger the automation to retry.

**Comment by StefH** [comment]
> Hi @StefH,
> 
> What's needed to resolve is to pass a Defender scan within the validation pipeline. My automation would be retrying, but this is blocked. If you could commit any change - even something mundane such as a line break or space - it would also trigger the pipeline to retry. 

I did update a file.

**Review by stephengillie — APPROVED** [review]

**Comment by StefH** [comment]
@stephengillie

Thanks for your support.
One if these days I will release a new version. Let's hope that it goes ok.

**Pull request merged**
