### PR TITLE
Update D:\Git\winget-pkgs\manifests\c\CGSecurity\TestDisk\7.1

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114232&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
> 12:27:33 PM: 2023-08-08 12:27:32.818 [CLI ] Package hash verification failed. SHA256 in manifest [1231ccfd46815e324f3c541b1e4a0a569a0a16b5c7d320c8c049c36595785224] does not match download [96e80b179956038d0323fde374949c4c3d603b62d81f84a312dca2499ec17bde]

**Comment by Trenly** [comment]
Hmm

**Pull request merged**
