### PR TITLE
New version: dotenvx.dotenvx 1.10.3

### PR DESCRIPTION
**Pull request by motdotla**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/169176)

### CODE REVIEW

**Comment by motdotla** [comment]
@stephengillie i believe the label `Validation-Executable-Error` is a mistake. My package does not install an application. It installs a cli executable that is run manually by the user on the command line.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Microsoft.Sysinternals.SDelete__DefaultSource\sdelete.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Microsoft.Sysinternals.SDelete__DefaultSource\sdelete64.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\sdelete64.exe returned exit code: 1
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Packages\Microsoft.Sysinternals.SDelete__DefaultSource\sdelete.exe returned exit code: 1
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\sdelete.exe returned exit code: 1

(Automated response - build 888.)

**Comment by stephengillie** [comment]
Verify:
image

**Review by stephengillie — APPROVED** [review]

**Comment by motdotla** [comment]
thank you @stephengillie. anything we can do to prevent that error from showing again on your side of things? otherwise will you have to manually check this everytime?

we have our own check for this (and more) here after every release: https://github.com/dotenvx/dotenvx/actions/runs/10553918092/job/29235106949

image

**Comment by stephengillie** [comment]
Hi @motdotla,

Our pipelines were written with Windows Forms in mind, so this will need me to check the logs and manually approve, as I did with this one. But it won't need the screenshot verification - that's just for first time pacakges.

**Pull request merged**
