### PR TITLE
New package: Z-DBackup.Z-Cron version 6.4

### PR DESCRIPTION
**Pull request by jo-chemla**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/172825)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
image

**Comment by jo-chemla** [comment]
Thanks for the feedback, I edited the zip url for one that seem more permanent, plus also added the `/Silent` flag
```yaml
InstallerSwitches:
  Silent: /Silent
```

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 895.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
image

Hi @jo-chemla, 

Is another installer switch needed here?

**Comment by jo-chemla** [comment]
Correct, sorry for that back-and-forth. Choco [zcron package installer](https://community.chocolatey.org/packages/z-cron#files) shows `/Silent /Languageid 1033` so I just added them to the PR, should now be reday!

**Comment by jo-chemla** [comment]
Thanks for the automated feedback. 
I've succesfully run the test command `winget install -m \Dev\Iconem\winget-pkgs\manifests\z\Z-DBackup\Z-Cron\6.4\` on my device, which resulted in a succesfull install, which indicates that this url should be valid. 

Otherwise, I can replace 
 - that url https://www.z-download.de/down/zcron.zip
 - with that one: https://z-download.de/?smd_process_download=1&download_id=69

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
