### PR TITLE
New package: Aardappel.lobster version 2024.0

### LINKED ISSUE #156085: [Package Request]: Lobster
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/aardappel/lobster
Publisher: https://github.com/aardappel
Package Name: Lobster
Description: The Lobster Programming Language
Package Version: v2024.0
Installer URL: https://github.com/aardappel/lobster/releases/download/v2024.0/lobster_windows_release.zip
Official webpage: https://www.strlen.com/lobster/
Official repository: https://github.com/aardappel/lobster

### PR DESCRIPTION
**Pull request by znarfm**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? Resolves #156085

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`? image
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/163997)

### CODE REVIEW

**Comment by znarfm** [comment]
Oh, there's already an `Aardappel` in the repo, while mine is `aardappel`. Is there any way to 'rename' my folders and files and commit them into this same PR, or should I just open a new PR?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  The file was not found. Verify git path must match with the casing of the file in disk. Not found file on 'manifests\a\aardappel\lobster\2024.0\aardappel.lobster.installer.yaml'

> Oh, there's already an `Aardappel` in the repo, while mine is `aardappel`. Is there any way to 'rename' my folders and files and commit them into this same PR, or should I just open a new PR?

Good catch. It should be possible to update the file casing in a new commit.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\lobster.exe returned exit code: 1

(Automated response - build 887.)

**Comment by stephengillie** [comment]
Verify:
image
Does this package have a dependency on `VCRedist`? 
image

**Review by stephengillie — APPROVED** [review]

**Comment by znarfm** [comment]
The [Getting Started](https://aardappel.github.io/lobster/getting_started.html) guide of the program states `Pre-Requirements: VS2022 Community edition or better, C++ desktop tools installed.` when **building it yourself**. I do not know if that also applies for the pre-built binaries.

**Pull request merged**
