### PR TITLE
Remove version: Wagnardsoft.DisplayDriverUninstaller version 18.0.8.0

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/174014)

### CODE REVIEW

**Comment by aisgbnok** [comment]
This is the latest version in Winget. I am getting status code 200, URL works for me. Please don't remove.

**Comment by stephengillie** [comment]
URL: https://www.wagnardsoft.com/DDU/download/DDU%20v18.0.8.0_setup.exe 
OK

(Automated message - build 922)

**Comment by stephengillie** [comment]
Close with reason: Package still available;

**Comment by stephengillie** [comment]
> This is the latest version on Winget. I am getting status code 200, URL works for me. Please don't remove.

This user's automation could be on a bad network connection, as the false positive rate is high.

**Pull request closed without merging**
