### PR TITLE
Modify: Mozilla.Firefox version 123.0

### PR DESCRIPTION
**Pull request by SpecterShell**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141033)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Installer https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0/win64-aarch64/ne-NP/Firefox%20Setup%20123.0.exe
 Scan request id: 'ff8ee373-8494-402a-ab1d-d3aa67b9dda3'
 
 Installer https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0/win64-aarch64/it/Firefox%20Setup%20123.0.exe
 Scan request id: '2ea252bc-4caa-411e-a2c0-bc0be5cd22ca'

(Automated response - build 831.)

**Comment by stephengillie** [comment]
URL: https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0/win32/en-US/Firefox%20Setup%20123.0.exe 
Status Code: 200

(Automated message - build 831)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0/win64/hu/Firefox%20Setup%20123.0.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-369-141033-20240227-3\aa95a2a3-2d3b-4070-a233-0963b35f8c4c' because it is being used by another process..
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 
 2/27/2024 10:28:40 AM

(Automated response - build 832.)

**Comment by stephengillie** [comment]
URL: https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0/win32/en-US/Firefox%20Setup%20123.0.exe 
Status Code: 200

(Automated message - build 832)

**Comment by SpecterShell** [comment]
> Automatic Validation ended with:
> 
> > Error occurred while downloading installer from [download-installer.cdn.mozilla.net/pub/firefox/releases/123.0/win64/hu/Firefox%20Setup%20123.0.exe](https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0/win64/hu/Firefox%20Setup%20123.0.exe). The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-369-141033-20240227-3\aa95a2a3-2d3b-4070-a233-0963b35f8c4c' because it is being used by another process..
> > Error information:
> > Http Response: OK
> > Http Reason Phrase: OK
> 
> 2/27/2024 10:28:40 AM
> 
> (Automated response - build 832.)
> 
> Edit: This package downloads normally for me too. This appears to be a pipeline issue, not a package issue.

@stephengillie It needs manual validation as it contains too many installers. You can continue from [this PR](https://github.com/microsoft/winget-pkgs/pull/140495) which is from the same branch. Note that some locales have been changed in [this commit](https://github.com/microsoft/winget-pkgs/pull/141033/commits/188d01ca4eb849f71792060ff8398038ef00f832) since last manual validation.

**Comment by stephengillie** [comment]
[Another PR](https://github.com/microsoft/winget-pkgs/pull/140991) was able to pass the pipelines without manual validation. The issue blocking [this PR](https://github.com/microsoft/winget-pkgs/pull/140495#issuecomment-1962011891) wasn't the number of installers, but a mismatch between installers and locales.

**Comment by SpecterShell** [comment]
> [Another PR](https://github.com/microsoft/winget-pkgs/pull/140991) was able to pass the pipelines without manual validation. The issue blocking [this PR](https://github.com/microsoft/winget-pkgs/pull/140495#issuecomment-1962011891) wasn't the number of installers, but a mismatch between installers and locales.

I meant the issue that causes `Internal-Error-Dynamic-Scan`. 😉

The mismatch issue should have been fixed now.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0/win64/ca/Firefox%20Setup%20123.0.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-369-141033-20240228-2\47d807a6-6ccf-435e-b5a1-a8c8504ff2f4' because it is being used by another process..
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 
 2/28/2024 4:19:22 AM

(Automated response - build 843.)

**Comment by stephengillie** [comment]
URL: https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0/win32/en-US/Firefox%20Setup%20123.0.exe 
Status Code: 200

(Automated message - build 843)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0/win64-aarch64/pt-BR/Firefox%20Setup%20123.0.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-371-141033-20240302-1\f41a12e1-e054-4258-96ea-0bed5ff2637b' because it is being used by another process..
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 
 3/2/2024 2:29:38 AM

(Automated response - build 861.)

**Comment by stephengillie** [comment]
URL: https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0/win32/en-US/Firefox%20Setup%20123.0.exe 
Status Code: 200

(Automated message - build 861)

**Comment by stephengillie** [comment]
This might be due to a network block of data centers, to prevent automated downloads.

(Automated response - build 861.)

**Pull request closed without merging**
