### PR TITLE
IBM.SemeruRuntimeOpenEdition.JRE version 21.0.1.12

### PR DESCRIPTION
**Pull request by kazssym**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135840)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @kazssym,

> This PR's version number 21.0.1.12 has 4 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version 18.0.2+9, which has 3 parameters.

Is this intentional?

(Automated response - build 629)

**Comment by kazssym** [comment]
> Hi @kazssym,
> 
> > This PR's version number 21.0.1.12 has 4 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version 18.0.2+9, which has 3 parameters.
> 
> Is this intentional?
> 
> (Automated response - build 629)

Even the previous version indeed had four parameters. The package uses version numbers with a plus sign as an OpenJDK convention but it is encoded instead only with dots by WinGet. I chose the all-dot notation this time as it is printed by WinGet after it is installed.

**Comment by stephengillie** [comment]
> Even the previous version indeed had four parameters. The package uses version numbers with a plus sign as an OpenJDK convention but it is encoded instead only with dots by WinGet. I chose the all-dot notation this time as it is printed by WinGet after it is installed.

If I'm understanding correctly, OpenJDK packages might use the plus sign as equivalent to the dot in delineating version parameters. Is that correct? If so, I can add this to my automation so it doesn't trigger in the future.

**Review by stephengillie — APPROVED** [review]

**Comment by kazssym** [comment]
> > Even the previous version indeed had four parameters. The package uses version numbers with a plus sign as an OpenJDK convention but it is encoded instead only with dots by WinGet. I chose the all-dot notation this time as it is printed by WinGet after it is installed.
> 
> If I'm understanding correctly, OpenJDK packages might use the plus sign as equivalent to the dot in delineating version parameters. Is that correct? If so, I can add this to my automation so it doesn't trigger in the future.

It seems correct as package version 21.0.1.12 of EclipseAdoptium.Temurin.21.JRE uses 21.0.1+12 as its version tag.

https://github.com/microsoft/winget-pkgs/blob/master/manifests/e/EclipseAdoptium/Temurin/21/JRE/21.0.1.12/EclipseAdoptium.Temurin.21.JRE.installer.yaml

**Pull request merged**
