### PR TITLE
Remove version: OpenEducationFoundation.OpenBoard version 1.7.2.240

### PR DESCRIPTION
**Pull request by PckgrTom**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/199698)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://github.com/OpenBoard-org/OpenBoard/releases/download/v1.7.2/OpenBoard_Installer_1.7.2.exe 
OK

(Automated message - build 923)

**Comment by stephengillie** [comment]
Hi @PckgrTom,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 931.)

**Comment by Trenly** [comment]
[Policy] Reset Feedback; Newer version merged in separate PR

**Comment by Trenly** [comment]
[Policy] Moderator Approved

**Pull request merged**
