### PR TITLE
kiwix.kiwixjs version 1.3.2.0

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/16129)

### CODE REVIEW

**Comment by Jaifroid** [comment]
@oxygen-dioxide Thank you for submitting Kiwix JS Windows to the WinGet repo. As the developer of Kiwix JS Windows, I was about to do the same thing, when I saw your submission. I note you've put as the package URL the permalink. I think this might be an issue because when I update the package, the permalink will change and so will the SHA. This will cause installation errors. I think it would be better for me to create this submission using the GitHub repository instead, which is versioned. I will also be able to add the proper locale data.

Could you close this PR without merging, and I will create one, which I can then keep up to date as part of the package creation script?

Many thanks.

**Comment by Jaifroid** [comment]
@oxygen-dioxide please see PR #16135 which I have created with a properly versioned package.

**Comment by denelon** [comment]
@Jaifroid you might want to take a look at https://github.com/microsoft/winget-create. It is still a very early preview, but was designed with CI/CD scenarios in mind to help automate the process of generating manifests and submitting PRs for these packages. We also have a [feature](https://github.com/microsoft/winget-pkgs/issues/100) in progress for "verified publisher(s)" to prevent others from making changes to manifests. The current thinking is to inform the author of the PR (and possibly the verified owner). Then the bot would close the PR.

**Comment by Jaifroid** [comment]
@denelon I actually did use winget-create for the PR that replaces this one: #16135 . I'll be using it in CI/CD for sure.

**Pull request closed without merging**
