### PR TITLE
Remove AppsAndFeaturesEntries from HydrusNetwork.HydrusNetwork v467

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/170393)

### CODE REVIEW

**Comment by russellbanks** [comment]
What's the reason for the ARP entry removals?

**Comment by Trenly** [comment]
@russelbanks - They aren’t needed at all for matching the package, and are actually doing more harm than good because at least one version specifies DisplayVersion when it doesn’t need to

**Comment by russellbanks** [comment]
> @russellbanks - They aren’t needed at all for matching the package, and are actually doing more harm than good because at least one version specifies DisplayVersion when it doesn’t need to

If I ran them through komac, they would all have the correct ARP entries, especially because they're Inno installers:

```yaml
PackageIdentifier: HydrusNetwork.HydrusNetwork
PackageVersion: v467
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Hydrus Network_is1
ReleaseDate: 2021-12-22
AppsAndFeaturesEntries:
- DisplayName: Hydrus Network
  Publisher: Hydrus Network
  ProductCode: Hydrus Network_is1
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/hydrusnetwork/hydrus/releases/download/v467/Hydrus.Network.467.-.Windows.-.Installer.exe
  InstallerSha256: E6F4B01E8B5013CE029E334DFF1E9671C75DD3D3215BCF187C7211727E0C9CAF
ManifestType: installer
ManifestVersion: 1.6.0
```

Otherwise I'm happy to approve all these PRs.

**Comment by Trenly** [comment]
> > @russellbanks - They aren’t needed at all for matching the package, and are actually doing more harm than good because at least one version specifies DisplayVersion when it doesn’t need to
> 
> If I ran them through komac, they would all have the correct ARP entries, especially because they're Inno installers:
> 
> ```yaml
> PackageIdentifier: HydrusNetwork.HydrusNetwork
> PackageVersion: v467
> InstallerLocale: en-US
> Platform:
> - Windows.Desktop
> InstallerType: inno
> Scope: machine
> InstallModes:
> - interactive
> - silent
> - silentWithProgress
> UpgradeBehavior: install
> ProductCode: Hydrus Network_is1
> ReleaseDate: 2021-12-22
> AppsAndFeaturesEntries:
> - DisplayName: Hydrus Network
>   Publisher: Hydrus Network
>   ProductCode: Hydrus Network_is1
> ElevationRequirement: elevatesSelf
> Installers:
> - Architecture: x64
>   InstallerUrl: https://github.com/hydrusnetwork/hydrus/releases/download/v467/Hydrus.Network.467.-.Windows.-.Installer.exe
>   InstallerSha256: E6F4B01E8B5013CE029E334DFF1E9671C75DD3D3215BCF187C7211727E0C9CAF
> ManifestType: installer
> ManifestVersion: 1.6.0
> ```
> 
> Otherwise I'm happy to approve all these PRs.

They are correct, but not needed because PackageName and Publisher are correct in the locale files; so these don’t actually improve the matching. Plus, when one manifest has DisplayVersion then they all do, otherwise it causes upgrade loops

**Review by russellbanks — APPROVED** [review]

**Review by russellbanks — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
