### PR TITLE
New version: Unity.Unity.2022 version 2022.3.41f1

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#7163](https://github.com/SpecterShell/Dumplings/actions/runs/10283126695).

<details>

<summary>Log</summary>

````
Updated: 2022.3.40f1 → 2022.3.41f1
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/166611)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Pull request merged**
