### PR TITLE
New package: LPGhatguy.Aftman version 0.3.0

### LINKED ISSUE #168797: [Package Request]: LPGhatguy.Aftman
### How can we help?

None

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/LPGhatguy/aftman/releases
Publisher: LPGhatguy
Package Name: Aftman
Description: Aftman, the prodigal sequel to Foreman
Package Version: 0.3.0
Installer URL: https://github.com/LPGhatguy/aftman/releases/download/v0.3.0/aftman-0.3.0-windows-x86_64.zip

### PR DESCRIPTION
**Pull request by totallytavi**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

Closes #168797

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/168796)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 887.)

**Review by stephengillie — CHANGES_REQUESTED** [review]
Manual Validation ended with:
image

Hi @totallytavi, 

It seems like this application might have a dependency on `VCRedist`.

**Comment by totallytavi** [comment]
How exactly can I test this? Would updating this from portable to standard be a solution?

**Comment by totallytavi** [comment]
Applied your changes that you requested.

**Comment by totallytavi** [comment]
I'm fine with that, microsoft bot. Was just adding context for when they come back.

**Comment by stephengillie** [comment]
Verify:
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
