### PR TITLE
Ferdium.Ferdium.Nightly version 6.3.0-nightly.5

### PR DESCRIPTION
**Pull request by Alphrag**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/106757)

### CODE REVIEW

**Comment by Alphrag** [comment]
If I understand correctly the validation fails on the analysis of the application which is linked to some antivirus, is that right?
Where could I find a detail of the problem to solve it, since I can't find much information in the logs to explain why the `arm64` version fails when both the `x64` and `x86` pass the analysis (all being built from the same code and same process)?

**Comment by stephengillie** [comment]
> If I understand correctly the validation fails on the analysis of the application which is linked to some antivirus, is that right? Where could I find a detail of the problem to solve it, since I can't find much information in the logs to explain why the `arm64` version fails when both the `x64` and `x86` pass the analysis (all being built from the same code and same process)?

This was due to a pipeline issue. Sorry for the false alarm.

**Review by stephengillie — APPROVED** [review]

**Comment by Alphrag** [comment]
> This was due to a pipeline issue. Sorry for the false alarm. 

No worries, thanks for checking it.

**Pull request merged**
