### PR TITLE
New version: Cockos.REAPER version 7.08

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/133439)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with:
image

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

Are installer switches needed?

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification.
>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

This manifest removes Apps and Features entries that are present in previous PR versions. Should these entries also be added to this version?

(Automated response - build 538.)

**Comment by Exorcism0666** [comment]
Yes! idk why komac remove them

**Comment by stephengillie** [comment]
> Yes! idk why komac remove them

Maybe @russelbanks knows?

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
