### PR TITLE
Microsoft.dotnetRuntime.3 version 3.1.9.29323

### PR DESCRIPTION
**Pull request by KaranKad**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/18546)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Hmm, i think the PackageName might have to be `Microsoft Windows Desktop Runtime - 3`
image

**Comment by KaranKad** [comment]
I'll create new PR's then

**Comment by OfficialEsco** [comment]
Tbh it might be better if we get --scope and scope in dependency instead of making 3 different folders/manifest, so yeah never mind that for now

**Comment by KaranKad** [comment]
Yeah I think `Microsoft.dotnetRuntime.3.x64` might be too much `Microsoft.dotnetRuntime.3-x64` might be better.

**Comment by OfficialEsco** [comment]
I think we might have to consult with @denelon before you commit too much 😁
Because `Microsoft Windows Desktop Runtime - 3 (x64)` wont match ARP unless we type the full version, i think `winget upgrade` might just have to update both (which should work? if you run it twice)

**Comment by KaranKad** [comment]
Because x64 and x86 versions appear different in control panel I think they need to have different manifest and I tried to kept `PackageName` closest to its ARP because version shouldn't be in `PackageName`. I've created an issue at [winget-cli/issues/982](https://github.com/microsoft/winget-cli/issues/982) to introduce `AppName` for per version of the application so winget can show you proper name using `PackageName` and can match the ARP using `AppName` field.

So in case of this application 
`PackageName` would be `Microsoft Windows Desktop Runtime - 3 (x64)` and 
`AppName` would be `Microsoft Windows Desktop Runtime - 3.1.16 (x86)` to better match ARP

**Pull request closed without merging**
