### PR TITLE
Add ZNotify package

### PR DESCRIPTION
**Pull request by Zxilly**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/88133)

### CODE REVIEW

**Comment by Zxilly** [comment]
@microsoft-github-policy-service agree

**Review by Trenly — CHANGES_REQUESTED** [review]
This has a runtime dependency on `Microsoft.VCRedist.2015.x64` on x64 based PC's
image

@stephengillie /@denelon - I'm not sure what the process is on this, since I don't believe portables are validated for runtime errors.

Marking this as requiring feedback for now pending direction from MSFT.

**Comment by Trenly** [comment]
Adding labels so it doesn't get automatically closed
@msftbot Dependencies

**Comment by Zxilly** [comment]
@Trenly Sorry for the inconvience, I have updated it to a static link version and seems it works fine now.

**Review by Trenly — APPROVED** [review]
Thanks for resolving the runtime error; It seems there's a few issues with the build itself - see Znotify/cli#1 and Znotify/cli#2 - but these aren't an issue from the winget side.

**Comment by Zxilly** [comment]
Could you please provide some technical detail about the test of the CI?  It's very hard to resolve the issue by my side

**Pull request merged**
