### PR TITLE
New version: MoonchildProductions.PaleMoon version 33.0.0

### PR DESCRIPTION
**Pull request by BiosPlus**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137438)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 

(Automated response - build 694.)

**Comment by stephengillie** [comment]
Hi @BiosPlus,

The installation isn't unattended. Is there an installer switch to have the package install silently?

(Automated response - build 694.)

**Comment by BiosPlus** [comment]
Hmm, the tests haven't re-run >_>

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
