### PR TITLE
Sylpheed.Sylpheed version 2.2.7

### PR DESCRIPTION
**Pull request by KarbitsCode**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/176071)

### CODE REVIEW

**Comment by KarbitsCode** [comment]
> Hi @KarbitsCode,
> 
> This manifest adds a DisplayVersion to the AppsAndFeaturesEntries that isn't present in previous manifest versions. This entry should be added to the previous versions, or removed from this version.
> 
> (Automated response - build 896.)
> 

Should it? The other manifest that doesn't have DisplayVersion because it already matched with the package version in the manifest.

**Comment by stephengillie** [comment]
> Should it? 

Yes - either the value should be in all manifests in the `PackageIdentifier`, or it should be in none. 

> The other manifest that doesn't have DisplayVersion because it already matched with the package version in the manifest.

Are you referring to https://github.com/microsoft/winget-pkgs/pull/176072? That PR also adds a `DisplayVersion`, as do a number of other recent PRs:

- https://github.com/microsoft/winget-pkgs/pull/176071 (This PR)
- https://github.com/microsoft/winget-pkgs/pull/176072 (Other PR mentioned above)
- https://github.com/microsoft/winget-pkgs/pull/176073
- https://github.com/microsoft/winget-pkgs/pull/176074
- https://github.com/microsoft/winget-pkgs/pull/176075
- https://github.com/microsoft/winget-pkgs/pull/176076
- https://github.com/microsoft/winget-pkgs/pull/176077
- https://github.com/microsoft/winget-pkgs/pull/176078
- https://github.com/microsoft/winget-pkgs/pull/176079
- https://github.com/microsoft/winget-pkgs/pull/176080
- https://github.com/microsoft/winget-pkgs/pull/176081
- https://github.com/microsoft/winget-pkgs/pull/176082
- https://github.com/microsoft/winget-pkgs/pull/176083
- https://github.com/microsoft/winget-pkgs/pull/176084
- https://github.com/microsoft/winget-pkgs/pull/176085
- https://github.com/microsoft/winget-pkgs/pull/176086
- https://github.com/microsoft/winget-pkgs/pull/176087
- https://github.com/microsoft/winget-pkgs/pull/176088
- https://github.com/microsoft/winget-pkgs/pull/176089
- https://github.com/microsoft/winget-pkgs/pull/176090

Related, a number of recent PRs modify existing manifests: 
- https://github.com/microsoft/winget-pkgs/pull/176111
- https://github.com/microsoft/winget-pkgs/pull/176118
- https://github.com/microsoft/winget-pkgs/pull/176122
- https://github.com/microsoft/winget-pkgs/pull/176131
- https://github.com/microsoft/winget-pkgs/pull/176135
- https://github.com/microsoft/winget-pkgs/pull/176138
- https://github.com/microsoft/winget-pkgs/pull/176142
- https://github.com/microsoft/winget-pkgs/pull/176145
- https://github.com/microsoft/winget-pkgs/pull/176150
- https://github.com/microsoft/winget-pkgs/pull/176154
- https://github.com/microsoft/winget-pkgs/pull/176158
- https://github.com/microsoft/winget-pkgs/pull/176162
- https://github.com/microsoft/winget-pkgs/pull/176165
- https://github.com/microsoft/winget-pkgs/pull/176169
- https://github.com/microsoft/winget-pkgs/pull/176173
- https://github.com/microsoft/winget-pkgs/pull/176177
- https://github.com/microsoft/winget-pkgs/pull/176181
- https://github.com/microsoft/winget-pkgs/pull/176185

At first, it seemed like the 2nd group were opened to add a `DisplayVersion` to the existing manifests. But these modify other metadata. Were they modified to also update the `DisplayVersion` it should resolve this issue.

**Comment by KarbitsCode** [comment]
> Are you referring to #176072?

No, I'm referring to version 2.7.0 and all the above.

**Comment by KarbitsCode** [comment]
> Were they modified to also update the `DisplayVersion` it should resolve this issue.

If I understand it correctly, I should add the `DisplayVersion` on all the other manifest like this:
```
...
PackageIdentifier: Sylpheed.Sylpheed
PackageVersion: "3.7"
InstallerType: nullsoft
AppsAndFeaturesEntries:
- DisplayVersion: "3.7"
Installers:
...
```

Is that correct?

**Comment by stephengillie** [comment]
Essentially, yes. The other option would be to remove it from the 2.x series.

**Comment by KarbitsCode** [comment]
Okay, I will add the rest.
Meanwhile, you can approve the one that already has DisplayVersion.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
