### PR TITLE
Update and rename manifests/7/7zip/7zipAlpha/20.0.2-alpha/7zip.7zipAl…

### PR DESCRIPTION
**Pull request by OfficialEsco**
Wrong version name

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/12221)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Huh?
The error message says the manifest path is wrong, however when checking its correct
However the Azure Pipelines says
`The pull request contains more than one manifest. Either singleton or multi file manifest under one Version directory.`

Before we would see one deleted and one added, but in this PR it is not 2 PRs

@Denelon @KevinLaMS

**Comment by denelon** [comment]
@OfficialEsco we're working on the fix. This behavior had to be re-written in our code to support "renames" for manifests. Git sees this as an add and a delete (two files).

We're also making adjustments to manifests to help with matching. By coincidence I updated 7zip.7zip yesterday. Would you mind changing to use the following values? We're starting the process to have keys match more closely with what we see in Add / Remove Programs. I'm not sure what the Package Name displays so I made a guess about the PackageName, but I know 7-zip is hyphenated for the stable build.

```YAML
Author: Igor Pavlov
PackageName: 7-Zip (alpha)
Publisher: Igor Pavlov
```

**Comment by OfficialEsco** [comment]
The plan was to do a quick rename/version fix which is why i didn't do a full convertion, but there ya go :)

**Comment by denelon** [comment]
@wingetbot you need to `winget install Microsoft.SupportForGitHubRenames`

@OfficialEsco let me see how close we are to having this fixed.

**Comment by denelon** [comment]
It looks like mid-next week. End-to-end testing is a bit tricky when we're working with GitHub APIs.

**Comment by OfficialEsco** [comment]
The bot is waiting for the ready signal 👀

**Comment by denelon** [comment]
We're testing in pre-production. It looks like Monday/Tuesday to push to production 😊

**Comment by denelon** [comment]
@OfficialEsco here goes nothing.

**Comment by denelon** [comment]
@OfficialEsco Hooray!

**Pull request merged**
