### PR TITLE
NEW - SafeSign Minidriver with Token Administrator

### PR DESCRIPTION
**Pull request by duv23121**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/196602)

### CODE REVIEW

**Comment by duv23121** [comment]
Can anyone tell me whats wrong with this installer check? It works like a charm wen I install it on my own computer from the local manifest.

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 4:25:56 PM: Error 1723. There is a problem with this Windows Installer package. A DLL required for this install to complete could not be run. Contact your support personnel or package vendor. Action DisableReadWriteMinidriverInstall, entry: DisableReadWriteMinidriverInstall, library: C:\Windows\Installer\MSI3B2D.tmp 4:25:56 PM: Property(S): ErrorDialog = ErrorDlg 4:25:56 PM: MSI (s) (4C:04) [16:25:55:753]: Windows Installer installed the product. Product Name: SafeSign IC MiniDriver. Product Version: 4.1.0.1. Product Language: 0. Manufacturer: A.E.T. Europe B.V.. Installation success or error status: 1603.

(Automated response - build 904.)

**Comment by duv23121** [comment]
> Manual Validation ended with:
> 
> > 4:25:56 PM: Error 1723. There is a problem with this Windows Installer package. A DLL required for this install to complete could not be run. Contact your support personnel or package vendor. Action DisableReadWriteMinidriverInstall, entry: DisableReadWriteMinidriverInstall, library: C:\Windows\Installer\MSI3B2D.tmp 4:25:56 PM: Property(S): ErrorDialog = ErrorDlg 4:25:56 PM: MSI (s) (4C:04) [16:25:55:753]: Windows Installer installed the product. Product Name: SafeSign IC MiniDriver. Product Version: 4.1.0.1. Product Language: 0. Manufacturer: A.E.T. Europe B.V.. Installation success or error status: 1603.
> 
> (Automated response - build 904.)

Hi StephenGille,

The strange thing is that i'm able to install this from my local manifest without any problems. This software contains drivers for smartcard readers and a tool to configure the smartcard. Could it be possible the test failes because this driver does not work in a virtual environment? And if yes, how do i pass this?

Bas

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 3:05:03 PM: Product: SafeSign IC MiniDriver -- Error 1723. There is a problem with this Windows Installer package. A DLL required for this install to complete could not be run. Contact your support personnel or package vendor. Action DisableReadWriteMinidriverInstall, entry: DisableReadWriteMinidriverInstall, library: C:\Windows\Installer\MSIC2F6.tmp

(Automated response - build 928.)

**Pull request closed without merging**
