### PR TITLE
traviskunkel.MealPicker version 1.1.0.0

### PR DESCRIPTION
**Pull request by HabbisSkunkel**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/94480)

### CODE REVIEW

**Comment by HabbisSkunkel** [comment]
This uses a self-signed certificate and the default YAML produces by wingetcreate.

**Comment by stephengillie** [comment]
Hi @HabbisSkunkel,

> This uses a self-signed certificate, and the default YAML produced by "wingetcreate new".

A self-signed certificate may not be sufficient. Validation is failing with this error:
> The root certificate and all intermediate certificates of the signature in the app package or bundle must be trusted.
> A certificate chain could not be built to a trusted root authority.

From https://github.com/microsoft/winget-pkgs/pull/93522#issuecomment-1379644451: [Sign a Windows 10 app package - MSIX | Microsoft Learn](https://learn.microsoft.com/windows/msix/package/signing-package-overview)

> To successfully install a Windows 10 application, the package doesn't just have to be signed but also trusted on the device. This means that the certificate has to chain to one of the trusted roots on the device.

**Comment by HabbisSkunkel** [comment]
Hello @stephengillie, 

This is a self-signed certificate that I created and exported following the instructions at [Create a certificate for package signing](https://learn.microsoft.com/en-us/windows/msix/package/create-certificate-package-signing). The only change I made was adding the -NotAfter switch to set the certificate to expire a year from now.

I have exported the certificate to use on machines this app is intended to be put on (they will have the certificate as a trusted root authority).

Hope this helps!

**Comment by stephengillie** [comment]
> I have exported the certificate to use on machines this app is intended to be put on (they will have the certificate as a trusted root authority).

Ah - the problem here is that the certificate hasn't been exported to the validation pipeline VMs. If the package isn't meant for public distribution, implied by the local certificates, then it might not be a good choice for inclusion in the public manifest. Instead, a local manifest could be used. Using these same files, the command `winget install --manifest c:\path\to\winget\manifest\files` would have Winget install the package described by the manifest files. And since these PCs have the certificate already installed, they would be able to validate and trust the application.

**Comment by HabbisSkunkel** [comment]
> If the package isn't meant for public distribution, implied by the local certificates, then it might not be a good choice for inclusion in the public manifest.

Thanks for the information. I'll go ahead with the method you provided. Thanks for the help!

**Pull request closed without merging**
