### PR TITLE
Remove Sigil-Ebook.Sigil 1.6.0

### PR DESCRIPTION
**Pull request by Trenly**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/76378)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Comment by Trenly** [comment]
```
2022-08-31 06:59:54.759   Message box (Yes/No):
                          The option to check for/install the VS
                          runtime is unchecked. Please make sure a
                          compatible version of the Visual Studio
                          VC++ runtime is already installed (by you
                          or an admin), or click "No" and check
                          the box before proceeding.
                          
                          You will need admin privileges to
                          to install the runtime.
                          
                          Do you wish to proceed as is?
```

**Comment by vedantmgoyal2009** [comment]
Duplicate of https://github.com/microsoft/winget-pkgs/pull/74848

**Review by ItzLevvie — APPROVED** [review]

**Review by vedantmgoyal9 — CHANGES_REQUESTED** [review]
Duplicate of https://github.com/microsoft/winget-pkgs/pull/74848

**Review by ghost — APPROVED** [review]

**Comment by vedantmgoyal2009** [comment]
You need to check for existing PRs before opening duplicates and misusing `wingetbot run` to remove Needs-Author-Feedback.

**Comment by vedantmgoyal2009** [comment]
That's a basic requirement suggested in the PR template.

**Pull request merged**
