### PR TITLE
New Package: ente-io.ente.Auth version 2.0.50+250

### LINKED ISSUE #147677: [Package Request]: ente-auth
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/ente-io/ente
Publisher:ente-io
Package Name: ente-auth
Description: open source end-to-end encrypted authenticator app
Package Version: v2.0.50
Installer URL: https://github.com/ente-io/ente/releases/download/auth-v2.0.50/ente-auth-v2.0.50-installer.exe

### PR DESCRIPTION
**Pull request by Trenly**
﻿Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

* Resolves #147679
* Resolves #147677

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/148226)

### CODE REVIEW

**Comment by Trenly** [comment]
@denelon - Another package failing dependencies due to VCRedist not having a user scope

I could have sworn that this was never an issue for dependencies in the past

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-04-08 15:33:52.735 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF8CC96C11F: (caller: 00007FF8CC6F8D6F) LogHr(1) tid(10f4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF8CC872B08: (caller: 00007FF8CC91BC20) Exception(1) tid(10f4) 8A15005E ] 
> 2024-04-08 15:33:52.735 [REPO] Failed to open available source: msstore
> 2024-04-08 15:34:00.530 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF8AC24C11F: (caller: 00007FF8ABFD8D6F) LogHr(1) tid(1794) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF8AC152B08: (caller: 00007FF8AC1FBC20) Exception(1) tid(1794) 8A15005E ] 
> 2024-04-08 15:34:00.530 [REPO] Failed to open available source: msstore
> 2024-04-08 15:34:01.749 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x64 with version 14.38.33135.0
> 2024-04-08 15:33:29.126 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!6836535B: (caller: 68261A80) LogHr(1) tid(1bc8) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!683AB5DD: (caller: 684412BF) Exception(1) tid(1bc8) 8A15005E ] 
> 2024-04-08 15:33:29.126 [REPO] Failed to open available source: msstore
> 2024-04-08 15:33:36.881 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!545B535B: (caller: 544B1A80) LogHr(1) tid(b94) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!545FB5DD: (caller: 546912BF) Exception(1) tid(b94) 8A15005E ] 
> 2024-04-08 15:33:36.881 [REPO] Failed to open available source: msstore
> 2024-04-08 15:33:29.654 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!6A0C535B: (caller: 69FC1A80) LogHr(1) tid(1c14) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!6A10B5DD: (caller: 6A1A12BF) Exception(1) tid(1c14) 8A15005E ] 
> 2024-04-08 15:33:29.654 [REPO] Failed to open available source: msstore
> 2024-04-08 15:33:37.485 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!55C8535B: (caller: 55B81A80) LogHr(1) tid(d98) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!55CCB5DD: (caller: 55D612BF) Exception(1) tid(d98) 8A15005E ] 
> 2024-04-08 15:33:37.485 [REPO] Failed to open available source: msstore
> 2024-04-08 15:33:38.733 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x86 with version 14.38.33135.0

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-04-08 15:33:52.735 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF8CC96C11F: (caller: 00007FF8CC6F8D6F) LogHr(1) tid(10f4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF8CC872B08: (caller: 00007FF8CC91BC20) Exception(1) tid(10f4) 8A15005E ] 
> 2024-04-08 15:33:52.735 [REPO] Failed to open available source: msstore
> 2024-04-08 15:34:00.530 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF8AC24C11F: (caller: 00007FF8ABFD8D6F) LogHr(1) tid(1794) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF8AC152B08: (caller: 00007FF8AC1FBC20) Exception(1) tid(1794) 8A15005E ] 
> 2024-04-08 15:34:00.530 [REPO] Failed to open available source: msstore
> 2024-04-08 15:34:01.749 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x64 with version 14.38.33135.0
> 2024-04-08 15:33:29.126 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!6836535B: (caller: 68261A80) LogHr(1) tid(1bc8) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!683AB5DD: (caller: 684412BF) Exception(1) tid(1bc8) 8A15005E ] 
> 2024-04-08 15:33:29.126 [REPO] Failed to open available source: msstore
> 2024-04-08 15:33:36.881 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!545B535B: (caller: 544B1A80) LogHr(1) tid(b94) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!545FB5DD: (caller: 546912BF) Exception(1) tid(b94) 8A15005E ] 
> 2024-04-08 15:33:36.881 [REPO] Failed to open available source: msstore
> 2024-04-08 15:33:29.654 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!6A0C535B: (caller: 69FC1A80) LogHr(1) tid(1c14) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!6A10B5DD: (caller: 6A1A12BF) Exception(1) tid(1c14) 8A15005E ] 
> 2024-04-08 15:33:29.654 [REPO] Failed to open available source: msstore
> 2024-04-08 15:33:37.485 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!55C8535B: (caller: 55B81A80) LogHr(1) tid(d98) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!55CCB5DD: (caller: 55D612BF) Exception(1) tid(d98) 8A15005E ] 
> 2024-04-08 15:33:37.485 [REPO] Failed to open available source: msstore
> 2024-04-08 15:33:38.733 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x86 with version 14.38.33135.0

(Automated response - build 876.)

**Comment by denelon** [comment]
I've suggested we remove the "msstore" source from our validation environment to reduce the log load here. Digging into the dependency issue, it seems like we're trying to get a scope match on the package. I'm not sure if we ended up with a newer version of the dependency in our validation environment or something else. We're still investigating.

**Comment by Trenly** [comment]
> I've suggested we remove the "msstore" source from our validation environment to reduce the log load here. Digging into the dependency issue, it seems like we're trying to get a scope match on the package. I'm not sure if we ended up with a newer version of the dependency in our validation environment or something else. We're still investigating.

@denelon - In case it helps, here is an example of a PR where https://github.com/microsoft/winget-pkgs/labels/Validation-Unattended-Failed and https://github.com/microsoft/winget-pkgs/labels/Validation-Installation-Error weren't applied, even though VCRedist is specified as a dependency and `Scope: user` is present - https://github.com/microsoft/winget-pkgs/pull/110135

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
