### PR TITLE
add NVIDIA Broadcast v1.0.0.30

### PR DESCRIPTION
**Pull request by nagakputtagunta**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/5157)

### CODE REVIEW

**Comment by ItzLevvie** [comment]
The filename needs to be ``1.0.0.30.yaml``

**Comment by nagakputtagunta** [comment]
> The filename needs to be `1.0.0.30.yaml` rather than `Broadcast-1.0.0.30.yaml`.

@ItzLevvie I was going off the ManifestSpecv0.1 defined in the winget-cli repo https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv0.1.md when I named the file. Should this be updated to reflect the proper naming convention?

**Comment by KevinLaMS** [comment]
image

**Comment by nagakputtagunta** [comment]
@KevinLaMS I just tried checking the installation on my machine again and it failed the first time because I had NVIDIA Broadcast already running. Once I quit the application and tried the installation again, it worked.

image

One thing I can think of for why it failed for you might be that this needs an NVIDIA GPU to work.

**Comment by link-webcreations** [comment]
Hello, no chance this PR will be merged ?

**Pull request closed without merging**
