### PR TITLE
REDModding.WolvenKit.Installer version 0.2.1.0

### PR DESCRIPTION
**Pull request by rfuzzo**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/93854)

### CODE REVIEW

**Comment by rfuzzo** [comment]
Verification fails because of this.
```
Deployment operation #0: Windows cannot install package 26499Wolvenkit.WolvenKit.Installer_0.2.1.0_x64__str4xaare4n04 because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.30704.0, along with this package to install. 
The frameworks with name "Microsoft.VCLibs.140.00" currently installed are: {Microsoft.VCLibs.140.00_14.0.27323.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.29231.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.30035.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.30035.0_x86__8wekyb3d8bbwe}```

**Comment by stephengillie** [comment]
> Verification fails because of this.
> 
> ```
> Deployment operation #0: Windows cannot install package 26499Wolvenkit.WolvenKit.Installer_0.2.1.0_x64__str4xaare4n04 because this package depends on a framework that could not be found. 
> Provide the framework "Microsoft.VCLibs.140.00" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.30704.0, along with this package to install. 
> The frameworks with name "Microsoft.VCLibs.140.00" currently installed are: {Microsoft.VCLibs.140.00_14.0.27323.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.29231.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.30035.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.30035.0_x86__8wekyb3d8bbwe}```
> ```

Hi @rfuzzo,

The installer has become unavailable - I've made this PR a draft under the assumption that you're updating the installer to address the above. Please feel free to revert to Ready for review when appropriate.

**Comment by rfuzzo** [comment]
> > Verification fails because of this.
> > ```
> > Deployment operation #0: Windows cannot install package 26499Wolvenkit.WolvenKit.Installer_0.2.1.0_x64__str4xaare4n04 because this package depends on a framework that could not be found. 
> > Provide the framework "Microsoft.VCLibs.140.00" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.30704.0, along with this package to install. 
> > The frameworks with name "Microsoft.VCLibs.140.00" currently installed are: {Microsoft.VCLibs.140.00_14.0.27323.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.29231.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.30035.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.30035.0_x86__8wekyb3d8bbwe}```
> > ```
> 
> Hi @rfuzzo,
> 
> The installer has become unavailable - I've made this PR a draft under the assumption that you're updating the installer to address the above. Please feel free to revert to Ready for review when appropriate.

Thank you, it seems it still fails because of missing redists. minimum version 14.0.30704.0 vs 14.0.30035.0. 
Is this a problem with the winget validation runner, or can I include it?

```
Deployment operation #0: Windows cannot install package 26499Wolvenkit.WolvenKit.Installer_0.2.2.0_x64__str4xaare4n04 because this package depends on a framework that could not be found. 

Provide the framework "Microsoft.VCLibs.140.00" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.30704.0, along with this package to install. 

The frameworks with name "Microsoft.VCLibs.140.00" currently installed are: {
Microsoft.VCLibs.140.00_14.0.27323.0_x64__8wekyb3d8bbwe
Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe 
Microsoft.VCLibs.140.00_14.0.29231.0_x64__8wekyb3d8bbwe 
Microsoft.VCLibs.140.00_14.0.30035.0_x64__8wekyb3d8bbwe 
Microsoft.VCLibs.140.00_14.0.30035.0_x86__8wekyb3d8bbwe}
```

**Comment by stephengillie** [comment]
> Thank you, it seems it still fails because of missing redists. minimum version 14.0.30704.0 vs 14.0.30035.0. Is this a problem with the winget validation runner, or can I include it?
> ```
> Deployment operation #0: Windows cannot install package 26499Wolvenkit.WolvenKit.Installer_0.2.2.0_x64__str4xaare4n04 because this package depends on a framework that could not be found. 
> 
> Provide the framework "Microsoft.VCLibs.140.00" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.30704.0, along with this package to install. 
> 
> The frameworks with name "Microsoft.VCLibs.140.00" currently installed are: {
> Microsoft.VCLibs.140.00_14.0.27323.0_x64__8wekyb3d8bbwe
> Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe 
> Microsoft.VCLibs.140.00_14.0.29231.0_x64__8wekyb3d8bbwe 
> Microsoft.VCLibs.140.00_14.0.30035.0_x64__8wekyb3d8bbwe 
> Microsoft.VCLibs.140.00_14.0.30035.0_x86__8wekyb3d8bbwe}
> ```

I believe this error means that the validation VM has 5 versions of the dependency `Microsoft.VCLibs.140.00` installed, 1 of which is x86 and x64 for the rest, all of which are a lower version than required by your package. This appears to be a package that's not yet included in in Winget. This isn't one of the `VCRedist` packages that makes up the vast majority of our dependencies, but a separate library. A possible solution might be to perform a silent install of `Microsoft.VCLibs.140.00` as an early installer step. 

This page has links to different architecture versions of `Microsoft.VCLibs.140.00`, including both x86 and x64: 
- https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/c-runtime-packages-desktop-bridge

**Pull request closed without merging**
