### PR TITLE
New version: Twingate.Client version 2024.99.6390

### PR DESCRIPTION
**Pull request by schweizerbolzonello**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/151961)

### CODE REVIEW

**Comment by schweizerbolzonello** [comment]
@microsoft-github-policy-service agree

**Comment by emrul** [comment]
Hi @schweizerbolzonello - we're curious why/how your GitHub profile ended up opening a pull request for our Twingate Client package that @chenbishop and I look after? (CC @Trenly since you're a moderator here perhaps you know).

**Comment by Trenly** [comment]
> Hi @schweizerbolzonello - we're curious why/how your GitHub profile ended up opening a pull request for our Twingate Client package that @chenbishop and I look after? (CC @Trenly since you're a moderator here perhaps you know).

Anyone can open a PR for any package, it isn’t restricted. This is to ensure that a package isn’t in a state where it is completely outdated and nobody can submit a new version

**Comment by emrul** [comment]
Thanks @Trenly, understood - we submitted an update too around the same time so we just wanted to make sure.

**Comment by schweizerbolzonello** [comment]
Hi @emrul 
Because I am one of your enterprise customers and your Winget packages were severely outdated
Thanks for the Winget package update you made in any case

**Pull request closed without merging**
