### PR TITLE
Add MIT CertAid 2.2.6

### PR DESCRIPTION
**Pull request by a-churchill**
MIT certificate installer

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/671)

### CODE REVIEW

**Comment by a-churchill** [comment]
Any insight into what [this error](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=81612&view=logs&j=c8020aa5-4aab-5881-691f-21986e02afd0&t=bade86d6-d2be-5ddd-c1b9-7d8db9c4a60d&l=41) is about? 
```
 Range GET requests are not supported by the copy source.
```

**Comment by a-churchill** [comment]
I see this is blocked by #523 - once that issue is addressed then hopefully this will work

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
