### PR TITLE
New version: Lexikos.AutoHotkey version 1.1.33.10

### PR DESCRIPTION
**Pull request by Trenly**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
  - Closes #26989 
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

This PR is to remove the merge conflict created in #26989 when #28842 was merged in

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/28845)

### CODE REVIEW

**Comment by Trenly** [comment]
@ryfu-msft I'm guessing this isn't the sort of error we could get a waiver for?

**Comment by ryfu-msft** [comment]
> @ryfu-msft I'm guessing this isn't the sort of error we could get a waiver for?



> @ryfu-msft I'm guessing this isn't the sort of error we could get a waiver for?

Hmm, bringing this up to the team as its complaining about the installer URL failing but it seems to work fine for me. Hang tight.

**Comment by Trenly** [comment]
> > @ryfu-msft I'm guessing this isn't the sort of error we could get a waiver for?
> 
> Hmm, bringing this up to the team as its complaining about the installer URL failing but it seems to work fine for me. Hang tight.

I don't think it's complaining about it failing; I think it complaining that the URL isn't passing smartscreen validation

**Review by ItzLevvie — DISMISSED** [review]

**Comment by denelon** [comment]
@Trenly you are correct. The URL was flagged by SmartScreen. I believe the URL at the end is a link that will allow you to submit the site as a false positive if you believe that to be the case. I've never used AutoHotkey, but I think @palenshus has.

**Comment by Trenly** [comment]
> @Trenly you are correct. The URL was flagged by SmartScreen. I believe the URL at the end is a link that will allow you to submit the site as a false positive if you believe that to be the case. I've never used AutoHotkey, but I think @palenshus has.

It is a pretty popular package. I'm a bit confused as to why SmartScreen is triggering on this URL and not any of the other AutoHotkey versions.  Do you happen to know how long the SmartScreen review process takes? I know that multiple users have submitted it as a false positive, but I'm sure it takes some time for them to process it

**Comment by denelon** [comment]
> > @Trenly you are correct. The URL was flagged by SmartScreen. I believe the URL at the end is a link that will allow you to submit the site as a false positive if you believe that to be the case. I've never used AutoHotkey, but I think @palenshus
> >             
> >             Union Palenshus
> >             FTE has.
> 
> It is a pretty popular package. I'm a bit confused as to why SmartScreen is triggering on this URL and not any of the other AutoHotkey versions. Do you happen to know how long the SmartScreen review process takes? I know that multiple users have submitted it as a false positive, but I'm sure it takes some time for them to process it

I have no idea what their rules are. I just have anecdotal examples for some new versions of packages taking a few days after publish to get a pass. I'm sure there are several different factors affecting some kind of score used to determine how URLs are treated in the OS.

**Comment by Trenly** [comment]
@ItzLevvie Looks like the vanity URL is allowing it to pass the check so far. Would you mind re-reviewing?

**Review by jedieaston — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
