### PR TITLE
NaturalPoint.TrackIR5 version 5.4.2.0000

### PR DESCRIPTION
**Pull request by IOntUMAtIp**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/79443)

### CODE REVIEW

**Comment by Trenly** [comment]
image

**Comment by IOntUMAtIp** [comment]
Thanks for report. I'm still trying to figure out why the installer is not
running in silent mode.

Em seg., 19 de set. de 2022 09:47, Kaleb Luedtke ***@***.***>
escreveu:

**Review by ItzLevvie — APPROVED** [review]
You will need to contact the developer and see if the prompt can be made silent when using silent switches.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
See https://github.com/microsoft/winget-pkgs/pull/79443#pullrequestreview-1116207248

**Comment by ItzLevvie** [comment]
Close with reason: Stale PR;

**Pull request closed without merging**
