### PR TITLE
New version: Apache.OpenOffice version 4.111.9808

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/36513)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
@ItzLevvie any idea as to why this is getting installation-error?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
No idea. It installs fine for me on Windows 10 x86:
image

Have you tried to re-run the pipelines by closing and reopening the PR?

**Comment by OfficialEsco** [comment]
If only there was a way to see which installer failed 🤔
@denelon

**Comment by denelon** [comment]
I'll ask @ryfu-msft to take a look. We're in the process of some refactoring work for validation so we can hopefully put more detailed status responses for PR authors and moderators.

**Review by ItzLevvie — APPROVED** [review]

**Comment by ryfu-msft** [comment]
@OfficialEsco, sorry for the delay. It appears that validation failed for the last 8 installers with a 429 status code. I manually validated the installers that failed and they all worked just fine so I went ahead and approved the PR. It's possible that downloading and validating each installer triggered rate-limiting from SourceForge.

**Comment by OfficialEsco** [comment]
Hmm, that makes sense, however the validation does not?
Are you guys downloading the installer multiple times? **URL Validation** says `Passed` and **Installers Scan** says `Validation Succeeded`

> We're in the process of some refactoring work for validation so we can hopefully put more detailed status responses for PR authors and moderators.

If `Installation Validation` could say anything that makes sense at all then that would be greeeat

**Pull request merged**
