### PR TITLE
Change ProtonVPN 1.15.0 publisher to Proton Technologies

### PR DESCRIPTION
**Pull request by mizarc**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/4042)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
i know you are just changing metadata, but the silent switches are missing.

**Comment by KevinLaMS** [comment]
Interesting.  seems to install correctly but gives an error at the end.  
image

**Comment by Mizarc** [comment]
I'm somewhat certain that I've managed to pinpoint part of the issue and it seems to affect both this version and the 1.16.3 version that was pushed to master earlier. Upon installing ProtonVPN 1.16.3 from the public repo after a fresh uninstall and restart, it appears to install fine with no issues. Uninstalling and reinstalling without a restart prompts the installer that some files already exist and it automatically successfully resolves this issue, though the winget installer is notified of a problem and puts out an error code.

Trying to install 1.15.0 appears to error but still install regardless of whether the program was previously uninstalled and a system restart was done. I don't know if it's possible to fix this problem on my end. I've attempted to use the same manifest arguments as 1.16.3 for 1.15.0 but it doesn't appear to change anything.

image
image

**Comment by Mizarc** [comment]
Tested with a local 1.17.4 manifest. Issue still remains. I did some further testing with the 1.16.3 manifest afterwards and now the uninstall and restart fix doesn't seem to work anymore, despite it being successful twice in a row prior.

**Comment by OfficialEsco** [comment]
@Mizarc you can close this one, i'm deleting it in #11570 because the installer switches don't work at all..

**Pull request closed without merging**
