### PR TITLE
New version: runlet.runlet version 1.0.8 [FP-D]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Failed
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | Runlet | KDevelop    |
| Version     | 1.0.8     | 5.6.2 |
| Publisher   | Runlet   | KDE e.V.      |
| ProductCode |           | KDevelop    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://bittu.eu.org/docs/wpa-intro) in workflow run [3338](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/3164927831>)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Comment by vedantmgoyal2009** [comment]
@denelon please reopen this one...

**Comment by vedantmgoyal2009** [comment]
@denelon please reopen and add Blocking-Issue

**Pull request merged**
