### PR TITLE
Add version: Defang version 0.5.25

### PR DESCRIPTION
**Pull request by lionello**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/159627)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-06-24 16:52:46.800 [FAIL] Installer failed security check. Url: https://github.com/DefangLabs/defang/releases/download/v0.5.25/defang_0.5.25_windows_amd64.zip Result: 0x80004005

(Automated response - build 886.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-06-25 12:10:17.908 [FAIL] Installer failed security check. Url: https://github.com/DefangLabs/defang/releases/download/v0.5.25/defang_0.5.25_windows_amd64.zip Result: 0x80004005

(Automated response - build 886.)

**Comment by stephengillie** [comment]
Good news - it appears to have been a false positive.
image

**Review by stephengillie — APPROVED** [review]

**Comment by lionello** [comment]
Thank you!!

**Pull request merged**
