### PR TITLE
Xml notepad/2.8.0.41

### PR DESCRIPTION
**Pull request by lovettchris**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23468)

### CODE REVIEW

**Comment by denelon** [comment]
@lovettchris is there any reason not to have the .msixbundle published via the GitHub repository?

**Comment by lovettchris** [comment]
@denolon, can you provide help on how to automate that (as per my [publish.cmd](https://github.com/microsoft/XmlNotepad/blob/master/publish.cmd)) ?  I'd also love to automate the creation of this PR at the same time...

**Comment by lovettchris** [comment]
Weird that the PR failed, "winget install xmlnotepad" is working fine on my devbox.  Azure storage isn't down very often...

**Comment by denelon** [comment]
There are many "moving parts" in validation. Several services we depend on have days long SLAs in some cases. We often see longer validation times for "new" releases.

**Comment by lovettchris** [comment]
does it auto-retry or do I have to push some trivial changes to my PR to kick it again?

**Comment by palenshus** [comment]
Hi @lovettchris, automatically pushing to GitHub releases is very straightforward! You can take a look at how we do it in winget-create to get started: https://github.com/microsoft/winget-create/blob/e75696c1ec98e5612988591354ff947057e789d9/pipelines/azure-pipelines.release.yml#L195

To automatically publish to winget-pkgs, you can start with the code here https://github.com/microsoft/winget-create/blob/e75696c1ec98e5612988591354ff947057e789d9/pipelines/azure-pipelines.release.yml#L232. Let us know how that all works for you!

**Comment by lovettchris** [comment]
I'll do that for the next release, in the meantime, how do we fix this one?

**Comment by palenshus** [comment]
The InstallerUrl still points to the blob storage path

**Comment by lovettchris** [comment]
never mind I just created a new version and new pull request to replace this one.

**Pull request closed without merging**
