### PR TITLE
Update Microsoft.OpenJDK.11

### PR DESCRIPTION
**Pull request by VAllens**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/37076)

### CODE REVIEW

**Review by jedieaston — CHANGES_REQUESTED** [review]
This isn't necessary. If your machine's locale isn't in the Installers array, winget will use the default locale instead. Since the JDK doesn't have different installers for different locales, this behavior is correct.

**Comment by VAllens** [comment]
> This isn't necessary. If your machine's locale isn't in the Installers array, winget will use the default locale instead. Since the JDK doesn't have different installers for different locales, this behavior is correct.

Hi, @jedieaston

My computer locale is `zh-CN`, JDK only `en-US`, so winget update failed.
The `winget update` command does not support the `--locale` parameter option.

My winget settings:
```json
{
    "$schema": "https://aka.ms/winget-settings.schema.json",

    // For documentation on these settings, see: https://aka.ms/winget-settings
    // "source": {
    //    "autoUpdateIntervalInMinutes": 5
    // },

    "installBehavior": {
        "preferences": {
            "scope": "machine",
            "locale": [ "zh-CN", "en-US" ]
        }
    },

    "telemetry": {
        "disable": false
    }
}
```

**Comment by VAllens** [comment]
> This isn't necessary. If your machine's locale isn't in the Installers array, winget will use the default locale instead. Since the JDK doesn't have different installers for different locales, this behavior is correct.

@jedieaston

When I run the `winget upgrade Microsoft.OpenJDK.11` command to update, 
winget prompts that there are no updates available.

But in fact, the `winget list` command tells me that there is an update available for `Microsoft.OpenJDK.11`.

After I analyzed the cause of the problem and added the `zh-CN` locale to the `Microsoft.OpenJDK.11.installer.yaml` file,
and executed the `winget upgrade Microsoft.OpenJDK.11 -m "D:\repo\github\winget-pkgs\manifests\m\Microsoft\OpenJDK\11\11.0.13.8"` command.
it updated successfully !!!

**Comment by jedieaston** [comment]
I figured it out, turns out the manifest for Microsoft.OpenJDK.11 was explicitly saying the installer only applied to en-US. 

I've resolved it in #37163.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Should be solved by https://github.com/microsoft/winget-pkgs/pull/37076#issuecomment-988437795.

**Comment by VAllens** [comment]
Okay, Let's close it.
Follow up to this PR: https://github.com/microsoft/winget-pkgs/pull/37163

**Pull request closed without merging**
