### PR TITLE
Min Browser

### PR DESCRIPTION
**Pull request by felipe199903**
add **Min Browser** to manifestes.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1252)

### CODE REVIEW

**Review by felipe199903 — COMMENTED** [review]
add Min Browser to manifests

**Review by felipe199903 — COMMENTED** [review]
remove the label "Needs: author feedback"

**Comment by felipe199903** [comment]
Once Windows Defender Notifications WDNotify@microsoft.com confirms the false positive, please remove the label "Needs: author feedback", and we will restart the pull request.

**Review by felipe199903 — COMMENTED** [review]
aproved by file submission

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
