### PR TITLE
New version: GiulioSorrentino.CBriscola.WPF version 0.6.7

### PR DESCRIPTION
**Pull request by GiulianoSpaghetti**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141141)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 830.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-27 09:09:26.700 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-27 09:09:54.389 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-27 09:10:05.948 [FAIL] Installer failed security check. Url: https://github.com/numerunix/CBriscola.WPF/releases/download/0.6.7/CBriscola.WPF-0.6.7-amd64.msi Result: 0x80004005 MSI (s) (8C:F4) [09:09:37:979]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (8C:F4) [09:09:39:370]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg

(Automated response - build 830.)

**Comment by numerunix** [comment]
Hello there, i think there is a smart screen block.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
