### PR TITLE
New version: LibreWolf.LibreWolf version 125.0.2-1

### PR DESCRIPTION
**Pull request by mariobrostech**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/151195)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @mariobrostech,

> This PR's version number 125.0.2-1 has 3 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version 123.0-1, which has 2 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 877)

**Comment by mariobrostech** [comment]
Yes, the stated version number is correct. Here is a screenshot from Apps & Features on my PC.

As a side-note, can this check please be exempted for this package? LibreWolf uses this versioning scheme, so every release will have this problem until someone reports that the stated version number matches.

image

**Review by stephengillie — APPROVED** [review]

**Comment by mariobrostech** [comment]
Hi @stephengillie,

Thanks for publishing the update! However, you never replied to my request for an exemption of version number checks for this package. Is this something that you'd still be willing to consider? Please see my previous mention of this issue below:

> As a side-note, can this check please be exempted for this package? LibreWolf uses this versioning scheme, so every release will have this problem until someone reports that the stated version number matches.

**Comment by stephengillie** [comment]
Oh, sorry.

**Comment by mariobrostech** [comment]
No worries! Is this something you can help with directly, or is there someone else that I should tag who would be able to comment further?

**Comment by stephengillie** [comment]
Yes - currently I'm implementing the override list manually.

**Comment by mariobrostech** [comment]
Great, thanks for your help! Hopefully, this process will be smoother next time then 🙂

**Pull request merged**
