### PR TITLE
Make Multi-line Field Exclude ending Newline

### PR DESCRIPTION
**Pull request by Trenly**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/77000)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
@denelon - Blocking Issue

```
2022-09-01 13:34:27.526 [CLI ] Caught std::exception: No mapping for the Unicode character exists in the target multi-byte code page.
```

https://github.com/microsoft/winget-cli/issues/2057

**Review by jedieaston — APPROVED** [review]

**Review by jedieaston — APPROVED** [review]

**Comment by stephengillie** [comment]
Validation is blocked by 
* https://github.com/microsoft/winget-cli/issues/2057

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
