### PR TITLE
Added Wings3D.Wings3D v2.2.6.1

### PR DESCRIPTION
**Pull request by OfficialEsco**
Cannot be installed as of now, requires Microsoft.VC++2013Redist-x64 to be installed
https://github.com/microsoft/winget-cli/issues/163

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/18025)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-pkgs/pull/18025#issue-673740138
@denelon add the tags

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by denelon** [comment]
Hey @OfficialEsco, we're now doing validation with dependencies if you want to add them to the manifest :)

**Comment by OfficialEsco** [comment]
🤷
image

**Comment by denelon** [comment]
I guess OpenGL 2.1 or higher needs to be added as well.

**Comment by OfficialEsco** [comment]
@stephengillie Could you investigate this one? It installs correctly on my VM, but opening the program throws the OpenGL probably since there is no graphic card

**Comment by stephengillie** [comment]
> @ stephengillie Could you investigate this one? It installs correctly on my VM, but opening the program throws the OpenGL probably since there is no graphic card

I had the same output: 
image

- https://github.com/microsoft/winget-pkgs/issues/107639

**Comment by stephengillie** [comment]
I do not know the significance nor impact of the `Validation-Missing-Dependency` label.

**Comment by OfficialEsco** [comment]
Finally a output from the bot, buuut its false..

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  
> 2023-12-27 12:10:55.050 [CORE] DeliveryOptimization error: 0x80072ee2, extended error: 0x00000000 
> 2023-12-27 12:10:55.146 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFD1E531EFD: (caller: 00007FFD1E5327D0) Exception(1) tid(714) 80072EE2 

(Automated response - build 509.)

**Comment by denelon** [comment]
Delivery Optimization error is probably on our end, but we still have the Open GL error to deal with. I did a quick search and didn't find an obvious way to handle OpenGL since it looks like it's a per video card installer.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by OfficialEsco** [comment]
That actually makes sense.. Overlooked that dependency, should be fixed now, validated and installed the x64 package

**Comment by denelon** [comment]
It's a long read, but appears to be related:

* #12906

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
