### PR TITLE
Modify: TheDocumentFoundation.LibreOffice version 24.2.2.2

### PR DESCRIPTION
**Pull request by SpecterShell**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150283)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by krystofkrticka** [comment]
Why was the link changed again to downloadarchive, since downloadarchive is not backed by CDN.
Usually same versions which are the latest are usually in https://download.documentfoundation.org/ which is backed by CDN and https://downloadarchive.documentfoundation.org/ isn't backed by it. So there were multiple complaints about abuse of downloadarchive which makes it sometimes painfully slow if you try to download some other version.

**Comment by SpecterShell** [comment]
> Why was the link changed again to downloadarchive, since downloadarchive is not backed by CDN. Usually same versions which are the latest are usually in [download.documentfoundation.org](https://download.documentfoundation.org/) which is backed by CDN and [downloadarchive.documentfoundation.org](https://downloadarchive.documentfoundation.org/) isn't backed by it. So there were multiple complaints about abuse of downloadarchive which makes it sometimes painfully slow if you try to download some other version.

I think downloadarchive is also backed by CDN, as I was redirected to a CDN when accessing the installer and there is also mirror list page like https://downloadarchive.documentfoundation.org/libreoffice/old/24.2.2.2/win/x86_64/LibreOffice_24.2.2.2_Win_x86-64.msi.mirrorlist which shows all the CDNs supporting the downloadarchive. 🤔

**Comment by krystofkrticka** [comment]
This is quite weird because there where multiple complaints like this #137666 in issues.

**Comment by SpecterShell** [comment]
> This is quite weird because there where multiple complaints like this #137666 in issues.

It might be because the files of the last two versions on archive server are somehow linked to the non-archive server so the former appears to be mirrored. Looking at the mirrorlist page mentioned above, although the file is located on the archive server, all the mirror links go to (the mirrored version of) https://download.documentfoundation.org/libreoffice/_testing_/24.2.2/win/x86_64/LibreOffice_24.2.2.2_Win_x86-64.msi, which is on the non-archive server. And since there are also only 4 versions (2 for LTS and 2 for non-LTS) available in the `_testing` folder, the files of all the other versions on the archive server are no longer mirrored, for example [there is only one mirror left for 24.2.1.2](https://downloadarchive.documentfoundation.org/libreoffice/old/24.2.1.2/win/x86_64/LibreOffice_24.2.1.2_Win_x86-64.msi.mirrorlist).

So users should always be able to download from the mirrors if the package is updated in time, and we no longer have to worry about the links becoming expired.

**Comment by krystofkrticka** [comment]
@SpecterShell So today it got was removed from mirrors for downloadarchive so I already created new PR for the latest version which was released today #151943 151943

**Comment by SpecterShell** [comment]
> @SpecterShell So today it got was removed from mirrors for downloadarchive so I already created new PR for the latest version which was released today #151943

OK thanks! (My automation on this package failed for some reasons 🤔).

**Pull request merged**
