### PR TITLE
Bumping schema version to 1.6.x; updating a few URIs

### PR DESCRIPTION
**Pull request by Matteo-T**
I did not see anything obviously different in going from 1.2.0 to 1.6.0.

Also, I'm not really using any of the new features introduced in later minor updates of the schema.

Just silencing the bot that complains about me be using an older schema version.

-------

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

### CODE REVIEW

**Comment by Matteo-T** [comment]
@stephengillie - did my little change caused so much trouble? Or it's just a bad day for the system?

**Comment by stephengillie** [comment]
Hi @Manually-Validated,

This package installs and launches normally on a Windows 10 VM.

(Automated response - build 429.)

**Comment by stephengillie** [comment]
Hi @Matteo-T,

> This PR's version number to has 1 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 20.0, which has 2 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 870)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
