### PR TITLE
Remove version: maforget.ComicRackCE.Nightly version nightly-f851f15

### PR DESCRIPTION
**Pull request by maforget**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/195576)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://github.com/maforget/ComicRackCE/releases/download/nightly/ComicRackCESetup_nightly.exe 
OK

(Automated message - build 923)

**Comment by stephengillie** [comment]
Hi @maforget,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 899.)

**Comment by maforget** [comment]
This isn't the latest, version in fact you will see that the checksum doesn't match. So this version isn't required anymore.

**Comment by maforget** [comment]
A new version was added #196786

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
[Policy] Reset Labels
[Policy] Reset Feedback

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
