### PR TITLE
Move and update CCleaner

### PR DESCRIPTION
**Pull request by NathanBnm**
This PR overwrites #308 in which I had an issue with my GitHub fork.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/594)

### CODE REVIEW

**Comment by NathanBnm** [comment]
@denelon @KevinLaMS checks are failing only because it appears to have two manifests files which is normal because I moved it from one folder to another so you have the deleted one and the moved one. Could you please review this manually?

**Comment by superusercode** [comment]
@NathanBnm git does a weird thing where if the first commit moves the file and the second commit actually edits the file it will recognize that the file has moved instead of as two different files.

**Comment by NathanBnm** [comment]
I thought it could be force validated by the reviewer team. But I agree je with you.

**Comment by msftrubengu** [comment]
@NathanBnm was this a git rm + git add? Or was it a git mv? If the file is marked as renamed we should be able to handle it.

**Comment by NathanBnm** [comment]
I just moved it and edited it in my editor

**Comment by msftrubengu** [comment]
I believe that would do a git rm + git add. The easiest solution would be to revert your commit and do a `git add -A .` Then, do git status to validate the file is marked as renamed. 

Also, note that your submission will fail because the new file was `Version: 1.53.1087`. So you would need to rename the file as 1.53.1087.yaml

**Comment by NathanBnm** [comment]
I'll do that asap thanks 😉

**Pull request closed without merging**
