### PR TITLE
Update D:\Git\winget-pkgs\manifests\k\Kaitai\StructCompiler\0.9

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114413&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Manual Validation failed with:
> A Java JDK is not installed or can't be found.  
Please go to   http://www.oracle.com/technetwork/java/javase/downloads/index.html and download a valid Java JDK and install before running kaitai-struct-compiler.  
If you think this message is in error, please check your environment variables to see if "java.exe" and "javac.exe" are available via JAVA_HOME or PATH.  
Press any key to continue . . .  

Apparently a `JDK` is a dependency.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
