### PR TITLE
New package: LGUG2Z.masir version 0.1.0

### PR DESCRIPTION
**Pull request by LGUG2Z**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/197055)

### CODE REVIEW

**Comment by LGUG2Z** [comment]
Think this might be another occurrence of the known issue of validation of daemon-type applications. Everything is working as expected when validating locally:

```
❯ winget install --manifest .\manifests\l\LGUG2Z\masir\0.1.0\
Found masir [LGUG2Z.masir] Version 0.1.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/LGUG2Z/masir/releases/download/v0.1.0/masir-0.1.0-x86_64.msi
  ██████████████████████████████  1.32 MB / 1.32 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

```
❯ which masir
C:\Program Files\masir\bin\masir.EXE
```

```
❯ masir
2024-12-08T21:11:54.076448Z  INFO masir: masir is now running, and additionally checking hwnds against C:\Users\LGUG2Z\AppData\Local\komorebi\komorebi.hwnd.json
2024-12-08T21:11:55.877242Z  INFO masir: raised hwnd 396112
2024-12-08T21:11:56.429210Z  INFO masir: raised hwnd 1052778
2024-12-08T21:11:56.701098Z  INFO masir: raised hwnd 396112
2024-12-08T21:11:57.074409Z  INFO masir: raised hwnd 67212
2024-12-08T21:11:57.935009Z  INFO masir: received ctrl-c, exiting
```

**Comment by LGUG2Z** [comment]
Not sure if there is anything else I can check from my side at this point given the limited feedback in the CI logs 🤔

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 2:00:51 PM: MSI (s) (08:60) [13:50:21:031]: Windows Installer installed the product. Product Name: masir. Product Version: 0.1.0. Product Language: 1033. Manufacturer: LGUG2Z. Installation success or error status: 0.

(Automated response - build 903.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-12-10 14:19:22.269 [FAIL] Installer failed security check. Url: https://github.com/LGUG2Z/masir/releases/download/v0.1.0/masir-0.1.0-x86_64.msi Result: 0x80004005

(Automated response - build 903.)

**Comment by LGUG2Z** [comment]
Likely a false positive, I have made a submission here: https://www.microsoft.com/en-us/wdsi/submission/9558fa63-b993-4522-b35f-27f1174b9f53

**Comment by stephengillie** [comment]
Verify:
image
I couldn't find how to have the application display the version number.

**Review by stephengillie — APPROVED** [review]

**Comment by LGUG2Z** [comment]
Thanks for approving and merging!

You can display the version number by passing the `--version` flag:

```
❯ masir --version
masir 0.1.1
```

**Pull request merged**
