### PR TITLE
New package: yzf.bcm-convertor version 1.3.0

### PR DESCRIPTION
**Pull request by CoolPlayLin**
Requirements
- sf-yuzifu/bcm_convertor#1

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

### CODE REVIEW

**Comment by CoolPlayLin** [comment]
I have no idea to fix

**Comment by stephengillie** [comment]
> ##[error] Installer https://github.com/214545666/bcm_convertor/releases/download/v1.3.0/bcm-convertor.yzf_1.3.0_ia32.exe
Scan request id: 'a1d27342-a683-4200-8769-a7206f0e9bae'
Error information: BlockingDetectionFound
##[error] Result: Failed

**Comment by CoolPlayLin** [comment]
I've informed that the developer will refactor this software, so please block this PR until the new version has published by develope.
CC @stephengillie

**Comment by stephengillie** [comment]
Hi @CoolPlayLin,

Any update on this refactor?

**Comment by CoolPlayLin** [comment]
CC @sf-yuzifu

**Comment by CoolPlayLin** [comment]
@stephengillie 
The developer replied with
image

**Comment by CoolPlayLin** [comment]
Keep blocking now please @stephengillie

**Comment by CoolPlayLin** [comment]
>[!important]
>The deadline of current blocking status is due in 2023.12.32. Once timeout, this Pull Request should be close directly and no need to ask for my opinion.

**Comment by CoolPlayLin** [comment]
**New Report**

According to secret message: developer current starts refactoring the software using Rust(using tauri exactly,).🤔

**Pull request closed without merging**
