### PR TITLE
Add new version - WK.WKRadar 7.6.0.395

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/113381&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
This package performs an automatic restart: 
image

**Comment by WKSistemas** [comment]
Hello Stephen @stephengillie , how are you?
In local tests, there was no reboot.
image

I believe that the situation is the same as before (https://github.com/microsoft/winget-pkgs/pull/110371): as the installer has dozens of executables (it is an ERP, with several modules), the machine in question does not have the capacity to open all of them at the same time, generating a timeout.

**Comment by stephengillie** [comment]
Hi @WKSistemas,

Sorry for the short reply. The validation process installs the package, then launches all new executable files, then performs a Defender scan. During this process, the VM reboots, which is not expected. Is there an executable, script file, or link that performs a system reboot?

**Review by stephengillie — APPROVED** [review]

**Comment by WKSistemas** [comment]
Hi Stephen @stephengillie, how are you?
Thank you very much for your return.
Is any further action still required?
I noticed that the automatic merge is disabled.

**Comment by stephengillie** [comment]
> Hi Stephen @stephengillie, how are you?
Thank you very much for your return.
Is any further action still required?
I noticed that the automatic merge is disabled.

Hi @WKSistemas,

I'm very sorry for the issues in this thread. I wasn't expecting our automation to undo my approval. I will be more vigilant to prevent this.

**Pull request merged**
