### PR TITLE
New package: BotProductions.PSPThumbnailHandler version 2.10.49

### LINKED ISSUE #170049: [Package Request]: BotProductions.PSPThumbnailHandler
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.botproductions.com/pspthumb/index.html
Publisher: Bot Productions
Package Name: PSP Thumbnail Handler
Description: PSP Thumbnail Handler is a free utility that allows you to view thumbnails of Paint Shop Pro images.
Package Version: 2.10.49
Installer URL: https://www.botproductions.com/pspthumb/v2/pthsetup.exe; https://www.botproductions.com/pspthumb/v2/x64/pthsetup.exe

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #170049

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/170585)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Dragon1573,

This `exe` installer seems to install another `exe` installer: Is this a nested installer?

image
image
There's a similar `Setup32.exe` inside the `x86` folder, possibly to support that architecture as well. 

The nested installer didn't respond to normal help switches `/?` or `--help`, instead just running the installer. Runni

**Comment by stephengillie** [comment]
Apologes, I clicked in the wrong location and accidentally closed the PR.

**Comment by Dragon1573** [comment]
> This `exe` installer seems to install another `exe` installer: Is this a nested installer?

**No.** `pthsetup.exe` is kind of "wrapper" of `Setup.exe`. If you try running `Setup.exe` interactively and manually install it to a different package, you'll get exactly the same contents in the installation directory.

> In addition to silent install switches for the nested installer, an install location switch might also be needed.

`pthsetup.exe` DOES support configuring install location, but it's supported by passing a configuration file to EXE using `/u:config.txt`. We can't dynamically generate config file during installation, right?

<details><summary>Contents in <code>readme.txt</code></summary>

```text

  PSP Thumbnail Handler 2.1
  x64 Edition

  Copyright (C) 2005 Bot Productions.


December 6, 2005


  This document contains an overview of PSP Thumbnail Handler and
  instructions on how to get started.


What is PSP Thumbnail Handler?

  PSP Thumbnail Handler is a free utility developed by Bot
  Productions.  When viewing files on your computer with Windows
  Explorer's thumbnails view, this utility allows you to view
  thumbnails of Paint Shop Pro images.

  PSP Thumbnail Handler is a shell extension, a plugin for Windows
  Explorer. It can display thumbnails of the following types:

    - psp (Images, PSP 6 or 7)
    - tub (Picture tubes, PSP 7)
    - jsl (Shapes, PSP 7)
    - pfr (Picture frames, PSP 7)
    - psimage (Images, PSP 8+)
    - psptube (Picture tubes, PSP 8+)
    - pspshape (Shapes, PSP 8+)
    - pspframe (Picture frames, PSP 8+)

  Also, PSP Thumbnail Handler allows you to view the dimensions of
  PSP images in Windows Explorer's details view.


What's new in PSP Thumbnail Handler 2.1?

  Version 2.1 is a minor update to version 2.0, adding several
  features:

  - A 64-bit version for x64 editions of Windows
  - Full Unicode support on Windows 2000, XP, and newer versions
  - Uses Bot Productions Setup 3.0, allowing a more streamlined
    setup experience as well as command-line deployment options


System Requirements - x64 Edition

  - AMD 64-based or compatible system
  - One of the following Microsoft operating systems:
     - Windows XP Professional x64 Edition
     - Windows Server 2003 x64 Edition
  - 2 MB of available hard drive space

  Note: This installation package is for x64 editions of Windows
  XP, Windows Server 2003, and newer versions.  Separate
  installation packages are available for 32-bit versions of
  Windows XP and Windows Server 2003, as well as for Windows 2000,
  Windows Me, and Windows 98.


Installation 

  To install PSP Thumbnail Handler, run the file pthsetup.exe.
  This begins the PSP Thumbnail Handler Setup Wizard, which guides
  you through installing PSP Thumbnail Handler.

  During Setup, you will be asked which file types you want to
  handle. The list contains PSP 7 and 8+ file types; click the
  check box next to a file type to include or exclude that type.
  To include a PSP file type not listed, click the Add New Type
  button and type in the file extension. Typically, you should
  accept the default settings.

  You must run Setup from an administrator account.


Using PSP Thumbnail Handler

  Open Windows Explorer and navigate to a folder containing Paint
  Shop Pro images. Select "Thumbnails" from the "View" menu, and
  see thumbnails of your PSP images.


Uninstallation

  To remove PSP Thumbnail Handler, use the Control Panel's Add or
  Remove Programs icon. Before uninstalling, close any Explorer or
  folder windows that are currently open, otherwise the utility
  may not be fully uninstalled.

  You must must be logged on as an administrator to uninstall
  PSP Thumbnail Handler.


This utility is not affiliated with Jasc Software, Inc. or Corel
Corporation.  Developed by Bot Productions with the help of the
Paint Shop Pro File Format Specification provided by Jasc
Software, Inc.


For the latest version of PSP Thumbnail Handler, visit Bot
Productions's web site: http://www.botproductions.com

To contact Bot Productions, send an e-mail to:
mail@botproductions.com
```

</details>

**Comment by Dragon1573** [comment]
@stephengillie - Review required 🙏🏼

**Comment by stephengillie** [comment]
Hi @Dragon1573,

I've read part of the Readme, and now understand that this is a shell extension to display thumbnails of `PSP` and similar file extensions inside File Explorer, much like other images. 

- Is PaintShop Pro a dependency? It's available through the MSStore as ``, and the free download option might be a good fit for this package manager as well. 
- I tried this with a non-PSP image, and nothing happened - I'm guessing this is because it's basically a library to allow File Explorer to read and display this image data. Is this accurate?
image
- Is there a good source for testing images?

**Comment by Dragon1573** [comment]
> Is PaintShop Pro a dependency? It's available through the MSStore as `9N6G6F7L1B43`, and the [free download](https://www.paintshoppro.com/en/pages/free-download/) option might be a good fit for this package manager as well.

Can't sure if it's required. If _PaintShop Pro_ is available on users' devices, these file extensions might already associated with it. Users may prefer viewing these files with _PaintShop Pro_ directly.

> I tried this with a non-PSP image, and nothing happened - I'm guessing this is because it's basically a library to allow File Explorer to read and display this image data. Is this accurate?

Yes, it is. It can be regarded as an add-on for `explorer.exe`.

> Is there a good source for testing images?

Nope 😥 I don't know much about _PaintShop Pro_ and it's exclusive file extensions. There seems no "gallery site" (a demo page like _SuperNova_ does) for _PaintShop Pro_. Maybe it's hard to validate manually ...

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
The application doesn't really give any user interface to verify.

**Pull request merged**
