### PR TITLE
New version: ArduinoSA.IDE.stable version 2.3.2

### LINKED ISSUE #152145: [Update Request]: ArduinoSA.IDE.stable
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

ArduinoSA.IDE.stable

### Package Version

2.3.2

### Please describe the changes you would like to see

Version 2.3.2 is released. I'll open a PR for this updating this version, but I'm not sure if there needs to be manifests added for all the version that are missing between the latest in winget-pkgs and the actual latest release.
[MSI for 2.3.2](https://downloads.arduino.cc/arduino-ide/arduino-ide_2.3.2_Windows_64bit.msi)

### PR DESCRIPTION
**Pull request by MatthewA1**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?
Resolves #152145 

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/152147)

### CODE REVIEW

**Comment by vikingnope** [comment]
@MatthewA1, kindly take a look at my review.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-05-03T20:43:45.6652098Z ##[error]Manifest Validation Failed
 2024-05-03T20:43:50.7470601Z ##[section]Finishing: Validate Manifest

(Automated response - build 880.)

**Comment by MatthewA1** [comment]
> @MatthewA1, kindly take a look at my review.
> 
> Verified my review manually: image
> 
> This is the suggestion if you are unable to see it:
> 
> ```
> AppsAndFeaturesEntries:
> - DisplayVersion: 2.3.2
>   DisplayName: Arduino IDE 2.3.2
> ```

I corrected the `AppsAndFeaturesEntries` > `DisplayVersion` entry to be the correct version, 2.3.2. I did not add the `DisplayName` attribute as it does not appear in the old version's manifest. Does it have to be there in the new manifest version?

**Comment by stephengillie** [comment]
The `DisplayName` attribute helps with matching. I'm not sure if it's necessary.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
