### PR TITLE
Moving: VivaldiTechnologies.Vivaldi version 6.5.3206.48

### PR DESCRIPTION
**Pull request by SpecterShell**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136283)

### CODE REVIEW

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 655.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-25T09:43:44.0141484Z Processing manifest: manifests\v\VivaldiTechnologies\Vivaldi\6.5.3206.48
 2024-01-25T09:43:44.0151073Z -----------------------------------------------------
 2024-01-25T09:43:44.0157319Z Status: Started
 2024-01-25T09:43:44.0165436Z Manifest file is Deleted
 2024-01-25T09:43:45.0449190Z Status: Completed
 2024-01-25T09:43:45.0450365Z ##[error] Result: Failed
 2024-01-25T09:43:45.0452474Z ##[error] Sequence contains no elements
 2024-01-25T09:43:45.0454514Z ##[error]Manifest Validation Failed

(Automated response - build 655.)

**Review by Trenly — APPROVED** [review]

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 657.)

**Pull request merged**
