### PR TITLE
New package: ChatterinoTeam.Chatterino version 2.4.6

### LINKED ISSUE #22593: Package Request: Chatterino
# Package Requested

- [x] I would like someone else to build the manifest.
- [x] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**:fourtf

**Publisher Url**: https://chatterino.com/

**Package Name**: chatterino

**Package Url**: https://chatterino.com/

**Description**: Chatterino 2 is a chat client for Twitch.tv.

**Package Version**: 2.3.2

**Installer URL**: https://github.com/Chatterino/chatterino2/releases/download/v2.3.2/Chatterino.Installer.exe or https://chatterino.fra1.digitaloceanspaces.com/bin/2.3.2/Chatterino%20Installer.exe

## For new versions:

**Current Package Identifier**:

### PR DESCRIPTION
**Pull request by hymccord**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

Closes: #22593 
---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/127421)

### CODE REVIEW

**Comment by Nerixyz** [comment]
Linking the old PR #109519 (stale) for completeness.

**Comment by hymccord** [comment]
@microsoft-github-policy-service agree

**Comment by hymccord** [comment]
Previous PR didn't have the correct flags to install without interaction and I believe the dependencies have been fixed as well since it's included in the install but will need manual approval.

Source for VCRedist being included: https://github.com/Chatterino/chatterino2/blob/6d02bb730457f70b6afe770ee679c35b2f661c1e/.CI/chatterino-installer.iss#L85

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Comment by hymccord** [comment]
Any way to get movement on this PR?

**Comment by stephengillie** [comment]
Normally I would approve it, but since the `Blocking-Issue` label keeps reappearing I'm hesitant to proceed.

**Comment by stephengillie** [comment]
This package installed and launched normally in a Windows 10 VM.

**Comment by Wissididom** [comment]
> Normally I would approve it, but since the `Blocking-Issue` label keeps reappearing I'm hesitant to proceed.

I assume it's because the underlying issue has the Blocking-Issue label, which I think was addressed in this PR tho.

**Review by Trenly — APPROVED** [review]
> Normally I would approve it, but since the `Blocking-Issue` label keeps reappearing I'm hesitant to proceed.

@stephengillie - I think this is okay to merge since it does install and run just fine. The blocking issue label is coming from the linked issue, but has been resolved in the installer itself.

**Comment by Trenly** [comment]
Doing a rerun just to be on the safe side

**Pull request merged**
