### PR TITLE
Add `$schema` to `cgmanifest.json`

### PR DESCRIPTION
**Pull request by JamieMagee**
This pull request adds the JSON schema for `cgmanifest.json`.

### Why?

A JSON schema helps you to ensure that your `cgmanifest.json` file is valid.
JSON schema validation is a build-in feature in most modern IDEs like Visual Studio and Visual Studio Code.
Most modern IDEs also provide code-completion for JSON schemas.

### How can I validate my `cgmanifest.json` file?

Most modern IDEs like Visual Studio and Visual Studio Code have a built-in feature to validate JSON files.
You can also use [this small script](https://github.com/JamieMagee/verify-cgmanifest) to validate your `cgmanifest.json` file.

### Why does it suggest camel case for the properties?

Component Detection is able to read camel case and pascal case properties.
However, the JSON schema doesn't have a case-insensitive mode.
We therefore suggest camel case as it's the most common format for JSON.

### Why is the diff so large?

To deserialize the `cgmanifest.json` file, we use [`JSON.parse()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse).
However, to serialize the JSON again we use [`prettier`](https://prettier.io/).
We found that, in general, it gave smaller diffs than the default [`JSON.stringify()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) function.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/76875)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
Can we use CRLF line endings?

**Comment by JamieMagee** [comment]
@Trenly Sure, can do. It looks like you very recently updated `.editorconfig` to enforce this in YAML files. Should it also be enforced in other file types?

**Comment by Trenly** [comment]
> @Trenly Sure, can do. It looks like you very recently updated `.editorconfig` to enforce this in YAML files. Should it also be enforced in other file types?

I think it should, yes. I did a quick scan of all the filetypes in the repository -
```
.editorconfig
.gitattributes
.gitignore
.md
.json
.txt
.yml
.yaml
.validation
.ps1
```
All of these are text types, so I would think that it would be good to set `[*]` to use CRLF in editorconfig. We had tried to set the ending for yaml files in `.gitattributes` to force consistency, but it caused issues with a lot of already merged PR's that had LF, so we are working on re-normalizing those files. I think it would make sense to set CRLF for all types

**Comment by Trenly** [comment]
cc'ing @denelon @jedieaston @OfficialEsco for their opinions on `.json`, `.md`, `.txt`, `.ps1`, and `.validation` files being added to `.gitattributes` and `.editorconfig`

**Comment by denelon** [comment]
Do any of those already stand out by not having CRLF?

I'm fine standardizing all of them as a convention.

**Comment by Trenly** [comment]
> Do any of those already stand out by not having CRLF?
> 
> I'm fine standardizing all of them as a convention.

With #76506 they should all be CRLF. Only the Yaml files seem to be non-standardized at the moment

**Comment by OfficialEsco** [comment]
> cc'ing @denelon @jedieaston @OfficialEsco for their opinions on `.json`, `.md`, `.txt`, `.ps1`, and `.validation` files being added to `.gitattributes` and `.editorconfig`

Any files should be CRLF just so there won’t be any conflicts as we’ve seen at times =) very few seemed to be LF so it def dosn’t hurt

Also reminder to please format your PR to CRLF (:

**Comment by jedieaston** [comment]
Sounds good to me. Also, thanks for adding the `$schema` @JamieMagee!

**Comment by denelon** [comment]
I just merged:

* https://github.com/microsoft/winget-pkgs/pull/77737

**Review by denelon — CHANGES_REQUESTED** [review]
@JamieMagee if you update the line endings, I'll merge this one.

**Comment by JamieMagee** [comment]
Thanks everyone! I rebased my PR on top of current master.

@denelon this should be ready for merge now.

**Review by Trenly — CHANGES_REQUESTED** [review]
Still looks like Line endings aren't changed

**Comment by JamieMagee** [comment]
@Trenly How do I get the line endings correct? This is what I see whenever I `cat` the file with whitespace shown. It shows `^M` as 'Microsoft line-endings' which means `CRLF`.

```
$ cat --show-all cgmanifest.json
{^M$
  "$schema": "https://json.schemastore.org/component-detection-manifest.json",^M$
  "Registrations": [^M$
    {^M$
      "Component": {^M$
        "Type": "git",^M$
        "git": {^M$
          "RepositoryUrl": "https://github.com/cloudbase/powershell-yaml",^M$
          "CommitHash": "03663c66e57ce2d0422077dc073bdb92e4d374b0"^M$
        }^M$
      }^M$
    }^M$
  ]^M$
}^M$
```

**Comment by Trenly** [comment]
> @Trenly How do I get the line endings correct? This is what I see whenever I `cat` the file with whitespace shown. It shows `^M` as 'Microsoft line-endings' which means `CRLF`.
> 
> ```
> $ cat --show-all cgmanifest.json
> {^M$
>   "$schema": "https://json.schemastore.org/component-detection-manifest.json[](https://json.schemastore.org/component-detection-manifest.json)",^M$
>   "Registrations": [^M$
>     {^M$
>       "Component": {^M$
>         "Type": "git",^M$
>         "git": {^M$
>           "RepositoryUrl": "https://github.com/cloudbase/powershell-yaml[](https://github.com/cloudbase/powershell-yaml)",^M$
>           "CommitHash": "03663c66e57ce2d0422077dc073bdb92e4d374b0"^M$
>         }^M$
>       }^M$
>     }^M$
>   ]^M$
> }^M$
> ```

That's odd. It may just be a weird thing with GitHub Web. I can confirm that the line endings do appear correctly locally. I'm not sure why it's showing the whole file changing in the web UI, but after deeper investigation, this looks good to me

**Review by Trenly — APPROVED** [review]

**Review by denelon — APPROVED** [review]

**Pull request merged**
