### PR TITLE
Fixed a typo, and added some more text.

### PR DESCRIPTION
**Pull request by KevinLaMS**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/142)

### CODE REVIEW

**Review by denelon — APPROVED** [review]

**Comment by denelon** [comment]
@ItzLevvie did you mean to comment on this old merged PR?

**Comment by ItzLevvie** [comment]
It is a bug in my command which is meant to run on PRs with Internal-Error: `(gh pr list --search "is:pr is:open label:Internal-Error" --limit 999).Split() | Select-String -Pattern "^\d+$" | % { gh pr comment $_ --body "@wingetbot run" }`

`.Split()` splits all spaces in PR titles with a new line so it picked up https://github.com/microsoft/winget-pkgs/pull/289990 which had 142 in the title and ran "@wingetbot run" on it.

It should be fixed now since I adjusted `Select-String -Pattern "^\d+$"` to be `Select-String -Pattern "^\d{6}$`

**Pull request merged**
