### PR TITLE
Add MEGAsync 4.3.1

### PR DESCRIPTION
**Pull request by NathanBnm**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/616)

### CODE REVIEW

**Comment by NathanBnm** [comment]
@superusercode would you help me with this please? :smile:

**Comment by superusercode** [comment]
looks like the CI failed to download the installer @NathanBnm . The choco equivalent looks pretty much identical https://github.com/teknowledgist/Chocolatey-packages/blob/master/automatic/megasync/tools/chocolateyinstall.ps1

**Comment by NathanBnm** [comment]
@superusercode this is weird it's working perfectly when running `winget -m install 4.3.1.yaml`

**Comment by NathanBnm** [comment]
Blocked by #91

**Comment by KevinLaMS** [comment]
Duplicate of #1620

**Pull request closed without merging**
