### PR TITLE
​

### PR DESCRIPTION
**Pull request by ItzLevvie**
​

### CODE REVIEW

**Comment by ItzLevvie** [comment]
Latest commit should fix it now:
image

**Comment by ItzLevvie** [comment]
cc @KevinLaMS: It's installing fine here:
image

**Comment by ItzLevvie** [comment]
Done another test with Visual C++ uninstalled (via Control Panel, not sure if there would be any leftover files) and the installer is running in unattended mode:
image

Will close PR if you're still encountering it.

**Comment by KevinLaMS** [comment]
I am getting this funny dialog, though it seems to be installed if I click OK.

image

**Pull request closed without merging**
