### PR TITLE
ReleaseNotes: Glodon.CADReader.CN version 5.18.0.90

### PR DESCRIPTION
**Pull request by SpecterShell**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/96943)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Review by rodrigoborgesdeoliveira — COMMENTED** [review]
Hi @SpecterShell, the hash for `http://cdn.cad.glodon.com/app/CADReaderPc_5.18.0.90.exe` has changed to `988B619949042AA37BBAC96B8B74AAAAE107F29613206323E02C9F8F8E36152F`. Could you update it in this PR as well?

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
