### PR TITLE
WHTA.Tamara version 1024.4.5.0

### PR DESCRIPTION
**Pull request by lars-nvhgroup**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/130186)

### CODE REVIEW

**Comment by lars-whta** [comment]
> Hello @lars-whta,
> 
> During installation testing, this application failed to install without user input. Did you forget to add Silent or SilentWithProgress switches?
> 
> This can also happen when a dependency is missing. You can test with https://github.com/microsoft/winget-pkgs#test-your-manifest.
> 
> Please investigate a fix and resubmit the Pull Request.
> 
> You may also try using the [Windows Package Manager Manifest Creator](https://github.com/microsoft/winget-create) to determine the proper installer type. If the installer type is MSIX, MSI, or a known installer technology like NullSoft, Inno, etc. the wingetcreate tool can detect them and the winget client will know what switches to pass. If it's a .exe installer of an unknown type, you will need to search to determine the proper switches for Silent and SilentWithProgress.
> 
> Template: msftbot/validationError/installation/unattended
> 

What failed? (I added vcredist2015+ as suggested.)

**Comment by lars-whta** [comment]
> Hi @lars-whta,
> 
> Manual Validation ended with: image
> 
> Matlab doesn't appear to be among the WinGet public manifests currently.

This is a lightweight online-installer; does the test environment have unrestricted access to the web? Or is it beneficial to try the offline-variant (which does not require access to Mathworks servers)?

**Comment by lars-whta** [comment]
> > Hi @lars-whta,
> > Manual Validation ended with: image
> > Matlab doesn't appear to be among the WinGet public manifests currently.
> 
> This is a lightweight online-installer; does the test environment have unrestricted access to the web? Or is it beneficial to try the offline-variant (which does not require access to Mathworks servers)?

It appears to have been (sort of) installed correctly, but it fails when trying to open the application. Is it possible to 
a) requesting a reboot after installation?
b) see what was installed (a rough list of folders)?

**Comment by stephengillie** [comment]
Hi @lars-whta,

Yes, the test system has full web access. We'd prefer it to download all dependencies instead of presenting an error, to maximize the user experience. 
- Applications can't reboot the system after install, as a general policy of packages installable through WinGet. 
- I'd be happy to attach the ChangedFiles.txt from the next run.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
