### PR TITLE
Remove Old: JanDeDobbeleer.OhMyPosh version 3.166.2

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
null

### CODE REVIEW

**Review by OfficialEsco — DISMISSED** [review]

**Comment by msftrubengu** [comment]
x86 and x64 fail with 0x80072efd

**Comment by OfficialEsco** [comment]
> x86 and x64 fail with 0x80072efd

A quick google search reveals this as a common Windows Problem
Non Microsoft reason: https://ugetfix.com/ask/how-to-fix-error-code-0x80072efd-on-windows-10/
> The error code 0x80072efd might bother Windows 10 operating system users. However, in some cases, this error might cause problems to previous Windows versions users. Indeed, this error is related to the internet connection problems. This error might show up when trying to use or open Windows Store, installing updates, and sometimes when attaching new printers cameras or other devices to the computer for the first time. There are numerous reasons why this error might show up, and the majority of them are related to connection problems. Sometimes users receive this error because firewall or local network prevents the computer from connecting to the Windows Update site. However, most of the time Proxy server settings are responsible for interfering connection to the Windows Updates, so all you have to do to fix 0x80072efd error is to disable Proxy.

**Comment by vedantmgoyal2009** [comment]
.

**Comment by OfficialEsco** [comment]
@denelon...

**Comment by denelon** [comment]
@yao-msft here is another one.

**Comment by OfficialEsco** [comment]
@ryfu-msft

**Comment by vedantmgoyal2009** [comment]
@denelon

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
