### PR TITLE
New version: SomePythonThings.WingetUIStore version 3.1.1

### PR DESCRIPTION
**Pull request by marticliment**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/165016)

### CODE REVIEW

**Comment by ClintonOffor** [comment]
Ok

**Comment by marticliment** [comment]
Is there no way to retrieve logs from the testing pipelines?

**Comment by vikingnope** [comment]
I would recommend removing the `/NoWinGet` flag. That is the only difference between the pre-release manifest and this one, and the pre-release was working fine during pipelines.

**Comment by 404NetworkError** [comment]
I don't know if removing the flag will fix it. Looking at other PRs, all of them since ~9 hrs ago are failing the same way.

**Comment by marticliment** [comment]
> I would recommend removing the `/NoWinGet` flag. That is the only difference between the pre-release manifest and this one, and the pre-release was working fine during pipelines.

The Prerelease did pass? Then this release should also pass. Changes were introduced that shouldn't fail verification amymore. I have tested the pr both with the flag and without the flag, and it failed both of the times. However, if the 3.1.1-beta3 passed, this PR should also pass the checks, since no changes have been introduced since then to the installer

**Comment by marticliment** [comment]
Yes, all new PRs are failing the tests

**Review by stephengillie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Pull request merged**
