### PR TITLE
New version: VMware.WorkstationPro version 16.2.1

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/34576)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
```
11/10/2021 5:22:10 PM
Status: Completed
##[error] Installer https://download3.vmware.com/software/wkst/file/VMware-workstation-full-16.2.1-18811642.exe Scan information: 'Error information: BlockingDetectionFound'
##[error] Result: Failed
```

https://www.virustotal.com/gui/url/b7d99e7d843e7a568688c93d424151900725f2b32661b88e400867decd1c8952?nocache=1
https://www.virustotal.com/gui/file/c73981be21420270c20533c473e90288a5f71bb0ee23ab605b88817919091a8b?nocache=1

Guessing this is why it failed? 
image
@denelon

**Comment by denelon** [comment]
That's a good guess. We will need an engineer to look and see if it's timing out or if something else is pending interaction.

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
Would it be possible for the bot to say which vendor is triggering the AV Validation? Or how many?

**Comment by denelon** [comment]
> Would it be possible for the bot to say which vendor is triggering the AV Validation? Or how many?

Not at this time. I have been informed some of the relationships with AV partners are based on reciprocity, and they aren't prepared to have community engagement (no specific partners were identified). We've opened discussions with our internal security teams to look at options. I don't even know which ones trigger a static analysis failure internally. We simply receive a "pass" / "fail" with the API. No additional data is provided. We do know when we get specific results related to SmartScreen and Defender during dynamic analysis, so those are already broken out.

**Pull request merged**
