### PR TITLE
New package: CyberSift.TutelaWindowsAgent version 1.5.0

### PR DESCRIPTION
**Pull request by dvas0004**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/156760)

### CODE REVIEW

**Comment by dvas0004** [comment]
this is installing correctly, may i know what exactly the issue is please?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-06-06 04:03:48.371 [FAIL] Installer failed security check. Url: http://repo.cybersift.io/cs-vas/tutela.msi Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 883.)

**Comment by dvas0004** [comment]
noted thank you @stephengillie 

Where would we be able to see the exit code next time we try please? Or is this an internal log?

**Comment by stephengillie** [comment]
> noted thank you @stephengillie
> 
> Where would we be able to see the exit code next time we try please? Or is this an internal log?

It's quite the quest:

- Click the [Checks](https://github.com/microsoft/winget-pkgs/pull/156760/checks) tab.
- Unfurl "Azure Pipelines" and click "WinGetSvc-Validation" to expand this section, then click the link "[View more details on Azure Pipelines](https://dev.azure.com/ms/ed6a5dfa-6e7f-413b-842c-8305dd9e89e6/_build/results?buildId=578578)".
- On that page, next to "Related", click "[4 published; 1 consumed](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=578578&view=artifacts&pathAsName=false)" (The number of published might vary.)
- Find the line showing "InstallationVerificationLogs" and goto the right edge. Click the 3 vertical dots, then click "Download artifacts".
- Unzip these and filter for "exit code" with your favorite software.

I've automated the above into a set of scripts, and have another script run this every hour.

**Comment by dvas0004** [comment]
Awesome thank you!!

**Pull request closed without merging**
