### PR TITLE
GiulioSorrentino.CBriscola.Avalonia version 0.7.7

### PR DESCRIPTION
**Pull request by GiulianoSpaghetti**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140167)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 763.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-19 22:08:05.856 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-19 22:08:51.197 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-19 22:09:11.695 [FAIL] Installer failed security check. Url: https://github.com/numerunix/CBriscola.Avalonia/releases/download/0.7.7/CBriscola.Avalonia-0.7.7-2-x64.msi Result: 0x80004005 2024-02-19 22:09:11.695 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (24:80) [22:08:17:199]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (24:80) [22:08:18:519]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg MSI (s) (24:80) [22:08:22:825]: Windows Installer installed the product. Product Name: Microsoft .NET Runtime - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (24:E8) [22:08:27:520]: Windows Installer installed the product. Product Name: Microsoft .NET Host FX Resolver - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (24:C8) [22:08:33:020]: An error occured while refreshing environment variables updated during the installation of ''. Some users logged on to the machine may not see these changes until they log off and then log back on. MSI (s) (24:C8) [22:08:37:817]: Windows Installer installed the product. Product Name: Microsoft .NET Host - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (24:60) [22:08:42:536]: Windows Installer installed the product. Product Name: Microsoft Windows Desktop Runtime - 8.0.2 (x64). Product Version: 64.8.8806. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 763.)

**Comment by numerunix** [comment]
The x64 works?

**Comment by stephengillie** [comment]
x64 failed the "Defender or similar" scan:

> Installer failed security check. Url: https://github.com/numerunix/CBriscola.Avalonia/releases/download/0.7.7/CBriscola.Avalonia-0.7.7-2-x64.msi Result: 0x80004005 
 
 Strings like this get buried in the logs, which is why I have the automation to check for it.

**Comment by numerunix** [comment]
the -2 version did install in program files (x86), the author of the tecnology i used updated it, i'm sorry for any inconvenince, however i have no virus on my pc, so it should be because it's not downloaded frequently.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-21 06:51:54.752 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-21 06:52:42.314 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-21 06:53:02.767 [FAIL] Installer failed security check. Url: https://github.com/numerunix/CBriscola.Avalonia/releases/download/0.7.7/CBriscola.Avalonia-0.7.7-3-x64.msi Result: 0x80004005 2024-02-21 06:53:02.767 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (68:A4) [06:52:07:586]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (68:A4) [06:52:08:961]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg MSI (s) (68:A4) [06:52:15:289]: Windows Installer installed the product. Product Name: Microsoft .NET Runtime - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (68:C0) [06:52:24:055]: Windows Installer installed the product. Product Name: Microsoft .NET Host FX Resolver - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (68:E0) [06:52:27:477]: Windows Installer installed the product. Product Name: Microsoft .NET Host - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (68:D0) [06:52:32:430]: Windows Installer installed the product. Product Name: Microsoft Windows Desktop Runtime - 8.0.2 (x64). Product Version: 64.8.8806. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 796.)

**Comment by numerunix** [comment]
It's blocked by defender

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 800.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-21 06:51:54.752 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-21 06:52:42.314 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-21 06:53:02.767 [FAIL] Installer failed security check. Url: https://github.com/numerunix/CBriscola.Avalonia/releases/download/0.7.7/CBriscola.Avalonia-0.7.7-3-x64.msi Result: 0x80004005 2024-02-21 06:53:02.767 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (68:A4) [06:52:07:586]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (68:A4) [06:52:08:961]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg MSI (s) (68:A4) [06:52:15:289]: Windows Installer installed the product. Product Name: Microsoft .NET Runtime - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (68:C0) [06:52:24:055]: Windows Installer installed the product. Product Name: Microsoft .NET Host FX Resolver - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (68:E0) [06:52:27:477]: Windows Installer installed the product. Product Name: Microsoft .NET Host - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (68:D0) [06:52:32:430]: Windows Installer installed the product. Product Name: Microsoft Windows Desktop Runtime - 8.0.2 (x64). Product Version: 64.8.8806. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 800.)

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 812.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-22 13:48:54.702 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-22 13:49:49.103 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-22 13:50:12.572 [FAIL] Installer failed security check. Url: https://github.com/numerunix/CBriscola.Avalonia/releases/download/0.7.7/CBriscola.Avalonia-0.7.7-3-x64.msi Result: 0x80004005 2024-02-22 13:50:12.572 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (60:64) [13:49:08:249]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (60:64) [13:49:09:937]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg MSI (s) (60:64) [13:49:18:312]: Windows Installer installed the product. Product Name: Microsoft .NET Runtime - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (60:00) [13:49:22:952]: Windows Installer installed the product. Product Name: Microsoft .NET Host FX Resolver - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (60:EC) [13:49:29:562]: Windows Installer installed the product. Product Name: Microsoft .NET Host - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (60:40) [13:49:40:577]: Windows Installer installed the product. Product Name: Microsoft Windows Desktop Runtime - 8.0.2 (x64). Product Version: 64.8.8806. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 812.)

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 812.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-23 11:50:25.739 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-23 11:51:10.271 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-23 11:51:32.695 [FAIL] Installer failed security check. Url: https://github.com/numerunix/CBriscola.Avalonia/releases/download/0.7.7/CBriscola.Avalonia-0.7.7-3-x64.msi Result: 0x80004005 2024-02-23 11:51:32.695 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (E0:DC) [11:50:37:245]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (E0:DC) [11:50:38:626]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg MSI (s) (E0:DC) [11:50:42:917]: Windows Installer installed the product. Product Name: Microsoft .NET Runtime - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (E0:58) [11:50:49:573]: Windows Installer installed the product. Product Name: Microsoft .NET Host FX Resolver - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (E0:E8) [11:50:55:073]: An error occured while refreshing environment variables updated during the installation of ''. Some users logged on to the machine may not see these changes until they log off and then log back on. MSI (s) (E0:E8) [11:50:58:261]: Windows Installer installed the product. Product Name: Microsoft .NET Host - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (E0:D8) [11:51:02:792]: Windows Installer installed the product. Product Name: Microsoft Windows Desktop Runtime - 8.0.2 (x64). Product Version: 64.8.8806. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 812.)

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 813.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-23 12:37:33.942 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-23 12:38:08.455 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-23 12:38:28.000 [FAIL] Installer failed security check. Url: https://github.com/numerunix/CBriscola.Avalonia/releases/download/0.7.7/CBriscola.Avalonia-0.7.7-3-x64.msi Result: 0x80004005 2024-02-23 12:38:28.000 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (B8:84) [12:37:46:745]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (B8:84) [12:37:48:339]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg MSI (s) (B8:84) [12:37:48:699]: Windows Installer installed the product. Product Name: Microsoft .NET Runtime - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (B8:30) [12:37:50:136]: Windows Installer installed the product. Product Name: Microsoft .NET Host FX Resolver - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (B8:D0) [12:37:51:480]: Windows Installer installed the product. Product Name: Microsoft .NET Host - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (B8:08) [12:37:59:276]: Windows Installer installed the product. Product Name: Microsoft Windows Desktop Runtime - 8.0.2 (x64). Product Version: 64.8.8806. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 813.)

**Pull request closed without merging**
