### PR TITLE
 Remove: MediaPress.StatlookServer version 16.3.8

### PR DESCRIPTION
**Pull request by ghost**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/156766)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @konrad-statlook-com,

It appears that the changes didn't quite reach the PR. 

image

**Comment by konrad-statlook-com** [comment]
Hi Stephen,

All we want to do is just unlist (remove) our software (MediaPress.StatlookServer 16.3.8) from winget repository, so I just reverted the commit that added it. How can we proceed?

Regards,
Konrad Wyroba
Media Press

**Comment by stephengillie** [comment]
I took the liberty of making the PR for you - I hope you don't mind. I think a Git-level issue occurred to this PR, possibly an old branch might have been used for it.

**Comment by stephengillie** [comment]
Close with reason: Duplicate of #156850;

**Pull request closed without merging**
