### PR TITLE
Fixed metadata for PhpStorm version 2022.1.4.

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?     
Note: `<path>` is the name of the directory containing the manifest you're submitting.

------
    

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/75687)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Inf166** [comment]
Will there be a release for 2023.1 since thats the current version of PHPStorm?

**Comment by ItzLevvie** [comment]
> Will there be a release for 2023.1 since thats the current version of PHPStorm?

It's already in WinGet: https://github.com/microsoft/winget-pkgs/blob/master/manifests/j/JetBrains/PHPStorm/2023.1/JetBrains.PHPStorm.installer.yaml#L20-L22

You can run `winget install --id JetBrains.PHPStorm --source winget`

**Comment by Inf166** [comment]
I ran Winget list today and saw it there! Thank you so much!

**Pull request merged**
