### PR TITLE
New Version: charmbracelet.vhs version 0.7.2

### PR DESCRIPTION
**Pull request by og-mrk**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/149328)

### CODE REVIEW

**Comment by og-mrk** [comment]
The validation may fail like in [this PR](https://github.com/microsoft/winget-pkgs/pull/142995), which's related to the same problem highlighted by [this comment](https://github.com/microsoft/winget-pkgs/pull/142995#issuecomment-1985882093), and it can be proven that this program works correctly after installation, **_see context/evidence below_**.

### When Installing using winget install --manifest

```powershell
> winget install --manifest .\manifests\c\charmbracelet\vhs\0.7.2\
Found vhs [charmbracelet.vhs] Version 0.7.2
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Packages
      Gyan.FFmpeg
      tsl0922.ttyd
(1/2) Found FFmpeg [Gyan.FFmpeg] Version 7.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/GyanD/codexffmpeg/releases/download/7.0/ffmpeg-7.0-full_build.zip
  ██████████████████████████████   160 MB /  160 MB
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "ffmpeg"
Command line alias added: "ffplay"
Command line alias added: "ffprobe"
Successfully installed

(2/2) Found ttyd [tsl0922.ttyd] Version 1.7.7
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/tsl0922/ttyd/releases/download/1.7.7/ttyd.win32.exe
  ██████████████████████████████  1.34 MB / 1.34 MB
Successfully verified installer hash
Starting package install...
Command line alias added: "ttyd"
Successfully installed

Downloading https://github.com/charmbracelet/vhs/releases/download/v0.7.2/vhs_0.7.2_Windows_x86_64.zip
  ██████████████████████████████  8.26 MB / 8.26 MB
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "vhs"
Successfully installed
> $LASTEXITCODE
0
```

<br>

### Validating that all installed programs are working correctly

```powershell
> ffmpeg
ffmpeg version 7.0-full_build-www.gyan.dev Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      59.  8.100 / 59.  8.100
  libavcodec     61.  3.100 / 61.  3.100
  libavformat    61.  1.100 / 61.  1.100
  libavdevice    61.  1.100 / 61.  1.100
  libavfilter    10.  1.100 / 10.  1.100
  libswscale      8.  1.100 /  8.  1.100
  libswresample   5.  1.100 /  5.  1.100
  libpostproc    58.  1.100 / 58.  1.100
Universal media converter
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
> $LASTEXITCODE
1
> ttyd
ttyd is a tool for sharing terminal over the web

USAGE:
    ttyd [options] <command> [<arguments...>]

VERSION:
    1.7.7-40e79c7

OPTIONS:
    -p, --port              Port to listen (default: 7681, use `0` for random port)
    -i, --interface         Network interface to bind (eg: eth0), or UNIX domain socket path (eg: /var/run/ttyd.sock)
    -U, --socket-owner      User owner of the UNIX domain socket file, when enabled (eg: user:group)
    -c, --credential        Credential for basic authentication (format: username:password)
    -H, --auth-header       HTTP Header name for auth proxy, this will configure ttyd to let a HTTP reverse proxy handle authentication
    -u, --uid               User id to run with
    -g, --gid               Group id to run with
    -s, --signal            Signal to send to the command when exit it (default: 1, SIGHUP)
    -w, --cwd               Working directory to be set for the child program
    -a, --url-arg           Allow client to send command line arguments in URL (eg: http://localhost:7681?arg=foo&arg=bar)
    -W, --writable          Allow clients to write to the TTY (readonly by default)
    -t, --client-option     Send option to client (format: key=value), repeat to add more options
    -T, --terminal-type     Terminal type to report, default: xterm-256color
    -O, --check-origin      Do not allow websocket connection from different origin
    -m, --max-clients       Maximum clients to support (default: 0, no limit)
    -o, --once              Accept only one client and exit on disconnection
    -q, --exit-no-conn      Exit on all clients disconnection
    -B, --browser           Open terminal with the default system browser
    -I, --index             Custom index.html path
    -b, --base-path         Expected base path for requests coming from a reverse proxy (eg: /mounted/here, max length: 128)
    -P, --ping-interval     Websocket ping interval(sec) (default: 5)
    -6, --ipv6              Enable IPv6 support
    -S, --ssl               Enable SSL
    -C, --ssl-cert          SSL certificate file path
    -K, --ssl-key           SSL key file path
    -A, --ssl-ca            SSL CA file path for client certificate verification
    -d, --debug             Set log level (default: 7)
    -v, --version           Print the version and exit
    -h, --help              Print this text and exit

Visit https://github.com/tsl0922/ttyd to get more information and report bugs.
> $LASTEXITCODE
0
> vhs
Run a given tape file and generates its outputs.

Usage:
  vhs <file> [flags]
  vhs [command]

Available Commands:
  help        Help about any command
  new         Create a new tape file with example tape file contents and documentation
  publish     Publish your GIF to vhs.charm.sh and get a shareable URL
  record      Create a new tape file by recording your actions
  serve       Start the VHS SSH server
  themes      List all the available themes, one per line
  validate    Validate a glob file path and parses all the files to ensure they are valid without running them.

Flags:
  -h, --help             help for vhs
  -o, --output strings   file name(s) of video output
  -p, --publish          publish your GIF to vhs.charm.sh and get a shareable URL
  -q, --quiet            quiet do not log messages. If publish flag is provided, it will log shareable URL
  -v, --version          version for vhs

Use "vhs [command] --help" for more information about a command.
> $LASTEXITCODE
0
```

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-04-15 10:02:18.533 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!68CC535B: (caller: 68BC1A80) LogHr(1) tid(17a0) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!68D0B5DD: (caller: 68DA12BF) Exception(1) tid(17a0) 8A15005E ] 
> 2024-04-15 10:02:18.533 [REPO] Failed to open available source: msstore
> 2024-04-15 10:02:21.957 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!68C2535B: (caller: 68B21A80) LogHr(1) tid(13c4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!68C6B5DD: (caller: 68D012BF) Exception(1) tid(13c4) 8A15005E ] 
> 2024-04-15 10:02:21.957 [REPO] Failed to open available source: msstore
> 2024-04-15 10:02:28.572 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!5483535B: (caller: 54731A80) LogHr(1) tid(ab4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!5487B5DD: (caller: 549112BF) Exception(1) tid(ab4) 8A15005E ] 
> 2024-04-15 10:02:28.572 [REPO] Failed to open available source: msstore
> 2024-04-15 10:02:29.733 [CLI ] No suitable installer found for manifest Gyan.FFmpeg with version 7.0

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Close with reason: Duplicate of #149321;

**Comment by og-mrk** [comment]
Hello @stephengillie 
I know that this PR has been closed due to duplication, but may I ask why validation failed?

Is it something wrong with my changes, or is it something related to internal validation pipeline? (Output log below)

If you don't want to answer my above question.. then it's completely understandable.

Thanks in advance 😄

> Automatic Validation ended with:
> 
> > 2024-04-15 10:02:18.533 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!68CC535B: (caller: 68BC1A80) LogHr(1) tid(17a0) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!68D0B5DD: (caller: 68DA12BF) Exception(1) tid(17a0) 8A15005E ] 
> > 2024-04-15 10:02:18.533 [REPO] Failed to open available source: msstore
> > 2024-04-15 10:02:21.957 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!68C2535B: (caller: 68B21A80) LogHr(1) tid(13c4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!68C6B5DD: (caller: 68D012BF) Exception(1) tid(13c4) 8A15005E ] 
> > 2024-04-15 10:02:21.957 [REPO] Failed to open available source: msstore
> > 2024-04-15 10:02:28.572 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!5483535B: (caller: 54731A80) LogHr(1) tid(ab4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!5487B5DD: (caller: 549112BF) Exception(1) tid(ab4) 8A15005E ] 
> > 2024-04-15 10:02:28.572 [REPO] Failed to open available source: msstore
> > 2024-04-15 10:02:29.733 [CLI ] No suitable installer found for manifest Gyan.FFmpeg with version 7.0
> 
> (Automated response - build 876.)

**Comment by stephengillie** [comment]
I'm not sure why this failed, but it appears to be an issue with the dependency. This might be related:
- https://github.com/microsoft/winget-pkgs/pull/148226

**Pull request closed without merging**
