### PR TITLE
New version: TravisLane.SteamArtManager version 3.0.0

### LINKED ISSUE #101920: [Package Request]: Steam Art Manager
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/Tormak9970/Steam-Art-Manager/releases/tag/v1.4.5
Publisher: Travis Lane
Package Name: Steam Art Manager
Description: A tool for setting the artwork of your Steam library.
Package Version: 1.4.5
Installer URL:https://github.com/Tormak9970/Steam-Art-Manager/releases/download/v1.4.5/Steam.Art.Manager_1.4.5_x64_en-US.msi

### PR DESCRIPTION
**Pull request by BiosPlus**
### Pull request has been created with [Komac](https://github.com/russellbanks/Komac) v1.11.0 :rocket:

- Resolves: #101920

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://github.com/Tormak9970/Steam-Art-Manager/releases/download/v3.0.0/steam-art-manager.msi 
Response status code does not indicate success: 401 (Unauthorized).

(Automated message - build 669)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> URI: https://github.com/Tormak9970/Steam-Art-Manager/blob/main/index.html, Validation result: Failed, Http status code: NotFound 

(Automated response - build 669.)

**Comment by BiosPlus** [comment]
Installer is borked, tried fixing it locally but can't get around the errors. Closing

**Pull request closed without merging**
