### PR TITLE
[Version] Waterfox G6.0.4

### PR DESCRIPTION
**Pull request by aaronliu0130**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/122324)

### CODE REVIEW

**Comment by aaronliu0130** [comment]
Same error as #121867

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335146 

image

**Comment by aaronliu0130** [comment]
image

**Comment by aaronliu0130** [comment]
` Manifest Error: DisplayVersion declared in the manifest has overlap with existing DisplayVersion range in the index. Existing DisplayVersion range in index:  [ [115.4.1, 115.4.1]]`
Huh... So either Winget somehow didn't pick up the incorrect version last time or the version wasn't updated.

**Comment by aaronliu0130** [comment]
image
It surely looks like the display version didn't change, this is G6.0.3 installed.

**Comment by aaronliu0130** [comment]
@stephengillie I don't really get what feedback I need to make.

**Comment by stephengillie** [comment]
Hi @aaronliu0130,

Unfortunately, I'm not familiar enough with the Apps and Features part to know for sure what's missing or extra.

**Comment by aaronliu0130** [comment]
This exact same problem is also present in G6.0.5.

**Comment by stephengillie** [comment]
@Trenly and/or @mdanish-kh,

We're not sure what the issue is here. Can you help us to understand the correct path forward?

**Comment by mdanish-kh** [comment]
@aaronliu0130 This is because the `DisplayVersion` property in the manifest is same as the previous manifest with PackageVersion `G6.0.3`. DisplayVersion is meant to pinpoint a unique version and it cannot be the same across manifests. If the publisher is not updating DisplayVersion with newer releases, then unfortunately we cannot accept multiple versions of the package in the repository. Best we can do is to report this to the publisher to update the DisplayVersion string written to Registry with every new release, and on the winget side we can only retain the "latest" version in the repo. This PR will pass validation if you remove `G6.0.3`

[Policy] Area-External
[Policy] Installer-Issue

**Comment by aaronliu0130** [comment]
Remove .03 in this PR?

**Comment by mdanish-kh** [comment]
> Remove .03 in this PR?

Yes you can. The pipelines won't scream since it'll count as update and replace within the same directory

**Comment by mdanish-kh** [comment]
@aaronliu0130 Maybe this needs to be a separate PR for the removal...

**Comment by aaronliu0130** [comment]
>:(

At this point, 6.0.5 has already shipped. If its ESR version is also the same I’ll just forsake this PR, but I’ll have to check when I get home

**Comment by mdanish-kh** [comment]
I checked the G6.0.5 release, unfortunately it has the same DisplayVersion `115.4.1`. This means we'll just have to remove G6.0.3 (skip 0.4) and add 0.5

**Comment by aaronliu0130** [comment]
Will add 05 later.

**Pull request closed without merging**
