### PR TITLE
Submitting ngrok 2.3.35 (x64)

### PR DESCRIPTION
**Pull request by darrenj**
Submitting ngrok tunnelling software to winget

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1139)

### CODE REVIEW

**Comment by Berkeley-Reject** [comment]
#91 Range GET method is currently not supported.

**Comment by KevinLaMS** [comment]
This is Zip file which is not supported
issue https://github.com/microsoft/winget-cli/issues/140

**Comment by denelon** [comment]
This is an old PR :smile:

The schema needs to be updated. It's also possible that we have implemented a solution for the previous range request error.

**Pull request closed without merging**
