### PR TITLE
Moved: Google.ChromeRemoteDesktopHost version 124.0.6367.18

### LINKED ISSUE #152118: [Package Issue]: Google.ChromeRemoteDesktop
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Installer hash does not match

### Steps to reproduce

Try to upgrade Google Chrome Remote Desktop Host

### Actual behavior

Hash does not match

### Expected behavior

Should upgrade normally

### Environment

```raw
Windows Package Manager v1.7.11132
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3527
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.11132.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

### Screenshots and Logs

image

### PR DESCRIPTION
**Pull request by SpecterShell**
* Fix #152118

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/152193)

### CODE REVIEW

**Comment by SpecterShell** [comment]
@vikingnope Hi, I'm moving this package to a new identifier with versioned installer URL.

**Comment by vikingnope** [comment]
Should I close my other PR?

**Comment by SpecterShell** [comment]
> Should I close my PR?

Feel free to close yours

**Comment by stephengillie** [comment]
Hi @SpecterShell,

When run, it gives an error:
image

Is this expected? 

Verify: 
image

**Comment by SpecterShell** [comment]
> Hi @SpecterShell,
> 
> When run, it gives an error: image
> 
> Is this expected?
> 
> Verify: image

Yes, it will be triggered by the extension from https://remotedesktop.google.com/

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
