### PR TITLE
Update version: Microsoft.PowerToys version 0.71.0

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/115163&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @crutkas,

Can I ask for your opinion on this one too?

**Comment by crutkas** [comment]
Same as the 72 pr. I think it is a neat idea to include release notes but would want this to come from our github action.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
