### PR TITLE
Remove Multipass 1.2.1

### PR DESCRIPTION
**Pull request by Saviq**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [ ] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/4351)

### CODE REVIEW

**Comment by Saviq** [comment]
Hi @KevinLaMS, what feedback are you seeking from me? This is an old Multipass version, is it customary to leave them around?

**Comment by KevinLaMS** [comment]
Oh my gosh.  I am sorry my comment was missing.  I was curious why you wanted to remove the manifest.  We recommend leaving them in case someone has taken a dependency on a particular version if it still worksk.

**Comment by Saviq** [comment]
Hi @KevinLaMS, OK, will leave them be :)

**Pull request closed without merging**
