### PR TITLE
Newer Version Typst.Typst 0.5.0

### PR DESCRIPTION
**Pull request by BrandonWanHuanSheng**
@superusercode Holding off with the merge of relative file path due to winget v 1.5 and higher versions is not yet released.
 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/109660

### CODE REVIEW

**Comment by stephengillie** [comment]
I'm not sure what's causing the [Policy 1.2](https://learn.microsoft.com/en-us/windows/package-manager/package/windows-package-manager-policies#12-security) label.

**Comment by BrandonWanHuanSheng** [comment]
Just only syncing with the fork.

**Comment by stephengillie** [comment]
> @[wingetbot](https://github.com/wingetbot) wingetbot added [Azure-Pipeline-Passed](https://github.com/microsoft/winget-pkgs/labels/Azure-Pipeline-Passed) Validation pipeline passed. There may still be manual validation requirements.[Policy-Test-1.2](https://github.com/microsoft/winget-pkgs/labels/Policy-Test-1.2) and removed [Waived-Policy-Test-1.2](https://github.com/microsoft/winget-pkgs/labels/Waived-Policy-Test-1.2) labels [3 hours ago](https://github.com/microsoft/winget-pkgs/pull/109660#event-9666644007)

*sigh*

**Comment by BrandonWanHuanSheng** [comment]
I will create a new PR after 20:00. Because this is not the latest release.

**Review by stephengillie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
