### PR TITLE
New version: GNU.Emacs version 29.4

### LINKED ISSUE #161775: [Update Request]: GNU.Emacs 29.4
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

GNU.Emacs

### Package Version

29.4

### Please describe the changes you would like to see

There is a new version (29.4) available.
Download URL is https://ftp.gnu.org/gnu/emacs/windows/emacs-29/emacs-29.4-installer.exe

This is an emergency bugfix release intended to fix the security vulnerability
https://www.gnu.org/savannah-checkouts/gnu/emacs/news/NEWS.29.4

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- Resolve #161775

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161795)

### CODE REVIEW

**Review by Trenly — APPROVED** [review]
@Dragon1573 - I'm going to approve this to resolve the linked issue, but would appreciate if you could update the copyright as a separate PR

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
