### PR TITLE
New version: BraveSoftware.BraveBrowser.Beta version 98.1.36.94

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/46257)

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]

**Review by ImJoakim — CHANGES_REQUESTED** [review]
Needs a rerun.

**Comment by OfficialEsco** [comment]
@denelon how about that rerun technology? 🤔

**Comment by denelon** [comment]
Yeah, I have too much latency compared with a bot!

**Comment by OfficialEsco** [comment]
> Yeah, I have too much latency compared with a bot!

Well, you seem to be faster than the bot 🤔

**Comment by denelon** [comment]
¯\_ (ツ)_/¯

Maybe we need to feed it more, or give it more training 😊

**Pull request merged**
