### PR TITLE
New version: OpenJS.NodeJS version 22.5.1

### PR DESCRIPTION
**Pull request by aisgbnok**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/163876)

### CODE REVIEW

**Comment by aisgbnok** [comment]
> **Found duplicate pull request(s)**
> 
> * **Manifest Path: manifests\o\OpenJS\NodeJS\22.5.1**
>   
>   * [New version: OpenJS.NodeJS version 22.5.1 #163877](https://github.com/microsoft/winget-pkgs/pull/163877)

Don't close; not a duplicate.

**Review by stephengillie — DISMISSED** [review]

**Comment by aisgbnok** [comment]
@stephengillie, I have rebased this PR because of the merge conflicts. This will fix the outdated/missing metadata introduced in #163877.

**Comment by aisgbnok** [comment]
Cleaned up the patch/diff so it should pass faster now.

**Review by stephengillie — APPROVED** [review]

**Comment by aisgbnok** [comment]
@stephengillie, I'm not going to be changing/rebasing this PR anymore unless needed from you. This is only changing metadata. `Installers` are untouched.

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
