### PR TITLE
New package: Magefile.mage version 1.14.0

### PR DESCRIPTION
**Pull request by mloskot**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/102752)

### CODE REVIEW

**Comment by mloskot** [comment]
The manifest has been validated and tested successfully:

image

**Comment by stephengillie** [comment]
> The manifest has been validated and tested successfully:
> 
> image

Did it pass a Defender scan?

**Comment by mloskot** [comment]
@stephengillie Yes, I think so, unless you mean something else

image

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package is expecting `.go` files:
```
No .go files marked with the mage build tag in this directory.
```

**Comment by mloskot** [comment]
@stephengillie I missed that. It seems to be a very first time I package an app that targets a particular file type. If you could offer me a lesson, shall I submit a patch?

**Pull request merged**
