### PR TITLE
- CS-Script Release v4.8.23.0

### PR DESCRIPTION
**Pull request by oleg-shilo**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/198972)

### CODE REVIEW

**Comment by oleg-shilo** [comment]
Hi I would appreciate some guidance on how to resolve this problem.
The validation stage is failing for me without an indication of the reason.

I have validated the package locally.
I have installed it locally.

The previous version was failing the same step simply because the package zip file contained another small zip and Antivirus did not like it even though the zip file content was scanned by AV without any problems. I solved that problem by removing the zip file from the package at that time.   

I feel that now it is again the antivirus that is giving the false positive.
I have downloaded the zip file the manifest references manually:
https://github.com/oleg-shilo/cs-script/releases/download/v4.8.23.0/cs-script.win.v4.8.23.0.zip

And Windows Defenders scans the zip extracted the content without any problems. 
However the original zip file containing the files is scanned and marked as "Trojan:Script/Wacatac.B!ml".
I have checked the local zip file that was uploaded to GitHub and the file downloaded from the GitHub repo and they are binary identical. And Windows Defender is OK with the local one but flags the downloaded one as infected even though the **are identical** . 

This makes me think that WindowsDefender fails the downloaded zip not because of the content itself but because it was downloaded from the internet.

Can you please guide how this faulty AV behaviour can be addressed in the WinGet pipeline.
Thank you

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-12-16 12:43:18.881 [FAIL] Installer failed security check. Url: https://github.com/oleg-shilo/cs-script/releases/download/v4.8.23.0/cs-script.win.v4.8.23.0.zip Result: 0x80004005

(Automated response - build 904.)

**Comment by oleg-shilo** [comment]
Thank you Stephen, 
but how the author can resolve this problem if i's not saying what security check is falling. 

My experiments with WinDefender indicate that it does not like that the zip file contains .NET assemblies. Which is a very definition of one of the support WinGet package types.

Can you guide my please on how I can resolve this problem.

Thank you

**Comment by oleg-shilo** [comment]
It's very difficult to deal with this

Virus Total gives it all cleat: cs-script.win.v4.8.23.0.winget.zip: [0/63 OK](https://www.virustotal.com/gui/file/8407c192671531b3a7c74eb61c52d83bed7fbe5caff71b7a0c56c17a1bd5291d)
And yet I am sure it is WinDefender who is spitting the dummy here. 

Is there any way for the open-source vendors to deal with the WinGet false positives?

**Comment by Trenly** [comment]
> It's very difficult to deal with this
> 
> Virus Total gives it all cleat: cs-script.win.v4.8.23.0.winget.zip: [0/63 OK](https://www.virustotal.com/gui/file/8407c192671531b3a7c74eb61c52d83bed7fbe5caff71b7a0c56c17a1bd5291d) And yet I am sure it is WinDefender who is spitting the dummy here.
> 
> Is there any way for the open-source vendors to deal with the WinGet false positives?

The security message is given from at least one of the multiple antivirus scans that is performed on the downloaded file, but most commonly Windows Defender. They *usually* resolve themselves within a few days and we can just re-run the validation. However, if it does not resolve automatically, then you may have to submit the executable and a report directly to Windows Defender. There isn't a mechanism to bypass this check and a package can't be merged unless it passes all the security scans

**Comment by stephengillie** [comment]
Apologies for missing this. Please understand that my response above really was automated, the output of the package manager from a VM on my laptop. And for a faster response, please @ me.

**Review by stephengillie — APPROVED** [review]

**Comment by oleg-shilo** [comment]
> Apologies for missing this...

@stephengillie, all good. @Trenly has outlined the process for me. Thank you both of you.

It's actually straightforward:
1. Pre-condition: the security check fails because of Windows Defender.
2. Normal flow: wait a few days for WinDefender to clear the binaries and unblock merge
3. Exceptional flow: if WinDefender does not clear submit the package and a report directly to Windows Defender. 

May I make a suggestion?
It would be great if this process is captured somewhere (unless I missed it). I am sure I am not the only one having this problem.
And it would be fantastic if the security check failure were visible to the PR author. Currently, the failure is communicated as a generic `Validation-Installation-Error`. In my case, I just guessed that it was WinDefender.

Thank you so much for your help. 
Merry Christmas!

**Comment by denelon** [comment]
@oleg-shilo we've been working on improving the response messages we're exposing. When a pipeline runs and a failure is encountered, we are exposing the result codes we're getting from the validation processing. We don't always get a discrete nested "reason" for why the packages was blocked. More work is happening behind the scenes to try and get more detailed responses, and the goal is to expose those directly in comments on the PR.

You should be able to view the "Details" for each validation run with the link in the PR above:

image

There are lots of moving pieces to orchestrate, and all of the work around security is highly scrutinized. Multiple AV partners are involved and the list of partners changes over time as well as their API surface area. I know how frustrating it is myself as I routinely have to submit detailed reports and wait for an e-mail response. 

Thanks for the understanding and the feedback.

**Pull request merged**
