### PR TITLE
ventoy.Ventoy version 1.0.90

### PR DESCRIPTION
**Pull request by unwillinglyawesome**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/100978)

### CODE REVIEW

**Comment by stephengillie** [comment]
This application is picky about where it's launched from - which directory is correct?
image

**Comment by unwillinglyawesome** [comment]
> This application is picky about where it's launched from - which directory is correct? image

For some reason, it won't start via alias. I tested previous manifest and it was the same. I wonder if there's a possibility to create good old start menu shortcuts with winget.

**Comment by BrandonWanHuanSheng** [comment]
I might created a general discussion.

**Comment by BrandonWanHuanSheng** [comment]
It look like all file might be selected.

**Comment by BrandonWanHuanSheng** [comment]
> This application is picky about where it's launched from - which directory is correct? image

Winget must expand all the file. 
The correct directory is supposed to be  ventoy-1.0.90/altexe/
This thing might unable to run without boot, plugin, ventoy folder. So, why that error will come out.

**Comment by BrandonWanHuanSheng** [comment]
#100978 stale pull-request

**Pull request closed without merging**
