### PR TITLE
Microsoft.WindowsTerminal version 1.17.11391.0

### PR DESCRIPTION
**Pull request by DHowett**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/107892)

### CODE REVIEW

**Review by jedieaston — APPROVED** [review]

**Comment by BrandonWanHuanSheng** [comment]
I think most likely there's no scope user to the Windows Store Packages.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978334972 
> 2023-05-23 10:19:18.075 [CORE] Deployment operation #0: Windows cannot install package Microsoft.WindowsTerminal_1.17.11391.0_x64__8wekyb3d8bbwe because this package depends on a framework that could not be found. Provide the framework "Microsoft.UI.Xaml.2.7" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 7.2208.15002.0, along with this package to install. The frameworks with name "Microsoft.UI.Xaml.2.7" currently installed are: {Microsoft.UI.Xaml.2.7_7.2109.13004.0_x64__8wekyb3d8bbwe}

**Comment by stephengillie** [comment]
This package appears to have a dependency on `Microsoft.UI.Xaml.2.7`. Unfortunately, this package is not yet available through the WinGet client.

**Comment by stephengillie** [comment]
The install is failing because the dependency `Microsoft.UI.Xaml_2.7` version `7.2109.13004.0` is too low - version `7.2208.15002.0` is required. The error is written in a convoluted way.

**Comment by BrandonWanHuanSheng** [comment]
It look like I might get a contact with the Microsoft.

**Comment by BrandonWanHuanSheng** [comment]
> The install is failing because the dependency `Microsoft.UI.Xaml_2.7` version `7.2109.13004.0` is too low - version `7.2208.15002.0` is required. The error is written in a convoluted way.

That appx is on the winget. But the URL is broken.  Id: 9P5VK8KZB5QZ

**Comment by DHowett** [comment]
@denelon-msft This doesn't make much sense to us - the store is supposed to resolve these dependencies. Do we need to double-commit our dependencies to WinGet as well?

**Comment by DHowett** [comment]
This is superseded by #108350, but the discussion here is valuable.

**Pull request closed without merging**
