### PR TITLE
New version: Pirinel.GitBlade version 1.0.6

### PR DESCRIPTION
**Pull request by schembriaiden**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/146082)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @vikingnope,

> This PR's version number 1.0.6 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 00.00.8.9, which has 4 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 872)

**Comment by vikingnope** [comment]
@stephengillie, it is a bit weird, in the Apps & Features page it still shows as 00.00.8.9, but within the app it says it is 1.0.6:

image


Screenshot 2024-03-23 080322

**Comment by stephengillie** [comment]
Thanks for the screenshots. The Apps and features page pulls data, I believe, from the Registry just like WinGet, so that value should be used here. The value shown inside the application might never be emitted outside.

**Comment by vikingnope** [comment]
The this shouldn't be update since ther is already a manifest for that version, closing this PR

**Pull request closed without merging**
