### PR TITLE
New version: TopalaSoftwareSolutions.SIW version 2022.03.17c

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/58931)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
* https://github.com/microsoft/winget-pkgs/issues/42616

**Comment by OfficialEsco** [comment]
> Url validation error
> 
>     * manifests\t\TopalaSoftwareSolutions\SIW\2022.03.17c
>       
>       * https://siw64.com/download/siwtrial-setup.exe
>         
>         * Http status code: ServiceUnavailable

works for me 🤖

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Looks like a newer version was already merged: https://github.com/microsoft/winget-pkgs/tree/7999b77976c7af6a14b537c3612db2214cf9c792/manifests/t/TopalaSoftwareSolutions/SIW/2022.05.21g

**Pull request closed without merging**
