### PR TITLE
New version: dorssel.usbipd-win version 4.2.0

### PR DESCRIPTION
**Pull request by dorssel**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/151351)

### CODE REVIEW

**Comment by dorssel** [comment]
I have no idea where the "Validation-Executable-Error" comes from. The package is organized the same as all previous versions, with a single "usbipd.exe" in the main installation directory.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files\usbipd-win\usbipd.exe returned exit code: 2

(Automated response - build 877.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-04-29 11:19:58.876 [FAIL] Installer failed security check. Url: https://github.com/dorssel/usbipd-win/releases/download/v4.2.0/usbipd-win_4.2.0.msi Result: 0x80004005

(Automated response - build 877.)

**Comment by stephengillie** [comment]
Hi @dorssel,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 877.)

**Comment by dorssel** [comment]
> Automatic Validation ended with:
> 
> > Executable C:\Program Files\usbipd-win\usbipd.exe returned exit code: 2
> 
> (Automated response - build 877.)

This is because System.CommandLine requires a command. It is true that this changed in this version. Running the executable without a command is a parse error now. See https://github.com/dorssel/usbipd-win/commit/6b6da498ec4995448789d981c71efd9dfda2fd2c#diff-82cc2bf60ada22c37fafd6f0c348d6f585fbac1e39c4df348a3507cf429239ceL118-L122

And: https://github.com/dorssel/usbipd-win/blob/5b36605535dd52bc3d8a8e4bbaee7f4d480c86ad/Usbipd/ExitCode.cs#L11

I could revert that, but rather not (after all, running without a command is, in fact, a parse error.

**Comment by dorssel** [comment]
> The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

That would be a first. The executable build (.NET 8 NativeAOT) hasn't changed.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files\usbipd-win\usbipd.exe returned exit code: 2

(Automated response - build 878.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
