### PR TITLE
New version: GitTools.GitVersion version 6.0.0-rc.1

### PR DESCRIPTION
**Pull request by arturcic**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/155315)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-05-28 07:40:55.491 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD872F74CC: (caller: 00007FFD872FE129) Exception(1) tid(21e0) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-28 07:40:55.496 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD872F74CC: (caller: 00007FFD872FE129) Exception(2) tid(21e0) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-28 07:40:55.499 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD872F74CC: (caller: 00007FFD872FE129) Exception(3) tid(21e0) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-28 07:40:55.502 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD872F74CC: (caller: 00007FFD872FE129) Exception(4) tid(21e0) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-28 07:40:55.508 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD872F74CC: (caller: 00007FFD872FE129) Exception(5) tid(21e0) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-28 07:40:55.511 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD872F74CC: (caller: 00007FFD872FE129) Exception(6) tid(21e0) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-28 07:40:55.514 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD872F74CC: (caller: 00007FFD872FE129) Exception(7) tid(21e0) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-28 07:40:55.518 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD872F74CC: (caller: 00007FFD872FE129) Exception(8) tid(21e0) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-28 07:40:55.527 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD872F74CC: (caller: 00007FFD872FE129) Exception(9) tid(21e0) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-28 07:40:55.556 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD872F74CC: (caller: 00007FFD872FE129) Exception(10) tid(21e0) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-28 07:40:55.559 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD872F74CC: (caller: 00007FFD872FE129) Exception(11) tid(21e0) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-28 07:40:55.574 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD872F74CC: (caller: 00007FFD872FE129) Exception(12) tid(21e0) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-28 07:40:55.581 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD872F74CC: (caller: 00007FFD872FE129) Exception(13) tid(21e0) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-28 07:40:55.588 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD872F74CC: (caller: 00007FFD872FE129) Exception(14) tid(21e0) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-28 07:40:55.656 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD872F74CC: (caller: 00007FFD872FE129) Exception(15) tid(21e0) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-28 07:42:47.785 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.0-rc.1/gitversion-win-x64-6.0.0-rc.1.zip Result: 0x80004005 
> 2024-05-28 07:41:35.635   Function name: GetLastError 
> 2024-05-28 07:41:41.119   Dest filename: C:\Program Files\Git\mingw64\lib\tk8.6\bgerror.tcl 
> 2024-05-28 07:41:42.978   Dest filename: C:\Program Files\Git\mingw64\share\doc\git-doc\technical\api-error-handling.html 
> 2024-05-28 07:41:43.369   Dest filename: C:\Program Files\Git\mingw64\share\git-gui\lib\error.tcl 
> 2024-05-28 07:41:43.541   Dest filename: C:\Program Files\Git\mingw64\share\perl5\FromCPAN\Error.pm 
> 2024-05-28 07:41:43.556   Dest filename: C:\Program Files\Git\mingw64\share\perl5\Git\LoadCPAN\Error.pm 
> 2024-05-28 07:41:44.306   Dest filename: C:\Program Files\Git\usr\bin\gpg-error.exe 
> 2024-05-28 07:41:45.431   Dest filename: C:\Program Files\Git\usr\bin\msys-gpg-error-0.dll 
> 2024-05-28 07:41:49.291   Dest filename: C:\Program Files\Git\usr\share\perl5\core_perl\Test2\EventFacet\Error.pm 
> 2024-05-28 07:41:50.635   Dest filename: C:\Program Files\Git\usr\share\perl5\vendor_perl\Error.pm 
> 2024-05-28 07:41:50.635   Dest filename: C:\Program Files\Git\usr\share\perl5\vendor_perl\Error\Simple.pm 
> 2024-05-28 07:41:50.635   Creating directory: C:\Program Files\Git\usr\share\perl5\vendor_perl\Error

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Separately, this PR appears to be for a Release Candidate version - should it be moved to another `PackageIdentifier`, possibly `GitTools.GitVersion.RC`?

**Comment by arturcic** [comment]
> Separately, this PR appears to be for a Release Candidate version - should it be moved to another `PackageIdentifier`, possibly `GitTools.GitVersion.RC`?

@stephengillie We are testing now the release workflows in preparation for version `6.0.0`. We will publish only full releases here, this is a draft PR to identify the potential issues before we publish the full release. This draft is not intended to be merged

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-06-18 18:47:15.653 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.0-rc.1/gitversion-win-x64-6.0.0-rc.1.zip Result: 0x80004005
> 2024-06-18 18:46:11.870   Function name: GetLastError
> 2024-06-18 18:46:36.011   Creating directory: C:\Program Files\Git\usr\share\perl5\core_perl\autodie\exception
> 2024-06-18 18:46:38.386   Creating directory: C:\Program Files\Git\usr\share\perl5\vendor_perl\Error
> 2024-06-18 18:47:00.434 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.0-rc.1/gitversion-win-arm64-6.0.0-rc.1.zip Result: 0x80004005
> 2024-06-18 18:45:58.514   Function name: GetLastError
> 2024-06-18 18:46:20.577   Creating directory: C:\Program Files\Git\usr\share\perl5\core_perl\autodie\exception
> 2024-06-18 18:46:22.639   Creating directory: C:\Program Files\Git\usr\share\perl5\vendor_perl\Error

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 886.)

**Pull request closed without merging**
