### PR TITLE
New version: DuckDuckStudio.GitHubLabelsManager version v1.4

### LINKED ISSUE #191995: [Update Request]: DuckStudio.GitHubLabelsManager
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

DuckStudio.GitHubLabelsManager

### Package Version

v1.4

### Please describe the changes you would like to see

There is a new release (v1.4) available.
Download Page Url: https://github.com/DuckDuckStudio/GitHub-Labels-Manager/releases/tag/v1.4

### PR DESCRIPTION
**Pull request by DuckDuckStudio**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? - close #191995 

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/191994)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
2024-11-16 08:26:11.744 [FAIL] D:\a\1\s\src\AppInstallerSharedLib\SHA256.cpp(144)\WinGetUtil.dll!00007FFBAB9BF6A8: (caller: 00007FFBABA65B59) Exception(2) tid(171c) 8A150040 
> 
> 2024-11-16 08:19:08.828 [FAIL] D:\a\1\s\src\AppInstallerSharedLib\SHA256.cpp(144)\WinGetUtil.dll!00007FFBAF98F6A8: (caller: 00007FFBAFA35B59) Exception(2) tid(17c4) 8A150040 
> 2024-11-16 08:28:39.001 [FAIL] D:\a\1\s\src\AppInstallerSharedLib\SHA256.cpp(144)\WinGetUtil.dll!53B2F85A: (caller: 53BD0C63) Exception(2) tid(37c) 8A150040 

(Automated response - build 897.)

**Comment by DuckDuckStudio** [comment]
What does this mean? I don't know how to fix this...

**Review by Luna-Grace — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by fjwxzde — APPROVED** [review]

**Comment by Luna-Grace** [comment]
@stephengillie 
Can you give us some suggestions to fix this issue?

**Comment by stephengillie** [comment]
HI @Luna-Grace,

Sorry for the delay - I left my automation running over the weekend. For this error, it seems that a few bits of unhelpful data got through my filters. But no actual error message, so I will remove the label and validate the PR.

**Pull request merged**
