### PR TITLE
New version: notepad-- version 2.5.0

### PR DESCRIPTION
**Pull request by hjkl950217**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/111315&drop=dogfoodAlpha

### CODE REVIEW

**Comment by hjkl950217** [comment]
[Associated PR 109752](https://github.com/microsoft/winget-pkgs/pull/109752)

**Comment by hjkl950217** [comment]
审核员你好，该软件的作者已经在仓库首页中说明软件在gitee站点和github的站点关系，表明他们是同一个作者同一款软件。

这次PR，说明关系和更新版本

----------------------------
Hello auditor, the author of the software has explained the relationship between the Gitee site and Github site on the warehouse homepage, indicating that they are the same author and software.

This PR, explain the relationship and updated version

**Comment by hjkl950217** [comment]
审核员你好，该软件的作者已经在仓库首页中说明软件在gitee站点和github的站点关系，表明他们是同一个作者同一款软件。

这次PR，说明关系和更新URL

--------------------
Hello auditor, the author of the software has explained the relationship between the Gitee site and Github site on the warehouse homepage, indicating that they are the same author and software.

This PR, explain the relationship and updated URL

**Comment by hjkl950217** [comment]
审核员你好，该软件的作者已经在仓库首页中说明软件在gitee站点和github的站点关系，表明他们是同一个作者同一款软件。

这次PR，说明关系和更新URL

--------------------
Hello auditor, the author of the software has explained the relationship between the Gitee site and Github site on the warehouse homepage, indicating that they are the same author and software.

This PR, explain the relationship and updated URL

**Comment by CoolPlayLin** [comment]
你好 @hjkl950217 
为什么要改成 Gitee 链接呢？

**Comment by CoolPlayLin** [comment]
你好 @hjkl950217 
把 Github 链接改成 Gitee 的同时，请把下面的这些链接改成 Gitee 的对应链接，之后就不会引发`Validation-Domain`
image


但强烈不建议改成 Gitee 链接，WinGet 的用户发布于全球，而 Gitee 的服务只在中国

**Review by CoolPlayLin — CHANGES_REQUESTED** [review]
你好 @hjkl950217 
把 Github 链接改成 Gitee 的同时，请把下面的这些链接改成 Gitee 的对应链接，之后就不会引发`Validation-Domain`
image


**但强烈不建议改成 Gitee 链接，WinGet 的用户分布于全球，而 Gitee 的服务只在中国**

**Comment by hjkl950217** [comment]
> 你好 @hjkl950217 把 Github 链接改成 Gitee 的同时，请把下面的这些链接改成 Gitee 的对应链接，之后就不会引发`Validation-Domain` image
> 
> **但强烈不建议改成 Gitee 链接，WinGet 的用户分布于全球，而 Gitee 的服务只在中国**

OK，Thank you for the reminder. I will modify it now

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
