### PR TITLE
New package: LAME.LAME version 3.100.1

### LINKED ISSUE #194580: [Package Request]: LAME MP3 Encoder
### How can we help?

None

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://lame.sourceforge.io/
Publisher: LAME Developers
Package Name: LAME
Description: LAME is a high quality MPEG Audio Layer III (MP3) encoder.
Package Version: 3.100.1
Installer Url: https://www.rarewares.org/mp3-lame-bundle.php

### PR DESCRIPTION
**Pull request by fgimian**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

Resolves https://github.com/microsoft/winget-pkgs/issues/194580

**Important**: This is a second attempt at adding the LAME MP3 encoder to winget. My first attempt can be found [here](https://github.com/microsoft/winget-pkgs/pull/153518) which was later [rolled back](https://github.com/microsoft/winget-pkgs/pull/155441).

As per previous discussion with @denelon on the removal issue with his comment shown below:

> I would say this one is a bit of an outlier, but since the official site for Lame recognizes RareWares as a location for compiled binaries, I don't have any problems with having the package, but I do want to make sure that the appropriate waivers are maintained, and the manifest has some kind of information regarding the correct license and the actual publisher.

I have attempted to rectify this concern in this PR but am happy to work with you to make sure it meets all your requirements. 😄 

There is no specific publisher name that I can find, the website just refers to the LAME developers, so I used LAME as the publisher name. Hope this is OK.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/194579)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 899.)

**Comment by fgimian** [comment]
@denelon @stephengillie Is there anything further required from my end to push this along?

Thanks heaps
Fotis

**Comment by denelon** [comment]
The domains don't match between the project and the download URL. That will need a waiver if it's a valid URL.

**Comment by fgimian** [comment]
> The domains don't match between the project and the download URL. That will need a waiver if it's a valid URL.

Thanks for the reply. As per our previous discussion at https://github.com/microsoft/winget-pkgs/pull/155441#issuecomment-2137701678, the RareWares site is the site that is linked as the download source for binaries from the official LAME site. These are technically compiled by another developer and distributed to the public as the LAME project only provides source code.

If there's anything further I can do to assist with this please let me know. If you still feel this package is simply not suitable for WinGet due to the points mentioned, I am happy to close the PR and avoid raising it again in future.

Kindest Regards
Fotis

**Comment by denelon** [comment]
@stephengillie the link in the comment above points to the "legwork" to show the InstallerURL is relevant for this package. I'm guessing we'll need a waiver on this one.

**Comment by stephengillie** [comment]
Verify:
image

@fgimian,

Sorry for all of the difficulties in getting this package merged, in this PR and the previous.

**Review by stephengillie — APPROVED** [review]

**Comment by fgimian** [comment]
@stephengillie @denelon Thank you both for your help with this, really appreciate it! 😄

**Comment by denelon** [comment]
You bet! Glad we could figure it out. Your breadcrumb links were just what we needed. It's hard to remember those "one off" or "few off" situations.

**Comment by fgimian** [comment]
> You bet! Glad we could figure it out. Your breadcrumb links were just what we needed. It's hard to remember those "one off" or "few off" situations.

Completely understand, there's a huge amount of activity in this repo! 😄 

Enjoy the rest of your week mate
Fotis

**Pull request merged**
