### PR TITLE
Remove contaminant

### PR DESCRIPTION
**Pull request by ackalker**
I think it is better to remove this, to prevent a fruit fly infestation.

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/165874)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 887)

**Comment by stephengillie** [comment]
Hi @ackalker,

What's the goal with this PR?

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 887)

**Comment by ackalker** [comment]
> Hi @ackalker,
> 
> What's the goal with this PR?

To remove a file which doesn't belong in this repository. I thought this was obvious.

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 894)

**Comment by ItzLevvie** [comment]
Close with reason: Replaced by PR 171589;

**Pull request closed without merging**
