### PR TITLE
New version: DenoLand.Deno version 1.43.5

### PR DESCRIPTION
**Pull request by coolplaylinbot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/154125)

### CODE REVIEW

**Comment by Trenly** [comment]
Looks like it triggered Defender
image

**Comment by stephengillie** [comment]
Hi @coolplaylinbot,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-17 21:54:57.963 [FAIL] Installer failed security check. Url: https://github.com/denoland/deno/releases/download/v1.43.5/deno-x86_64-pc-windows-msvc.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 881.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
