### PR TITLE
Fix the license of `y-chan.SHAREVOX` 0.2.1

### PR DESCRIPTION
**Pull request by qryxip**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

Almost same change as #133664.

SHAREVOX is a proprietary software as VOICEVOX is.

CC: @y-chan (the publisher of SHAREVOX)
CC: @Exorcism0666 (#133054)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/133790)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
Why use the license from `SHAREVOX/sharevox.github.io` when the installer is at `SHAREVOX/sharevox`

**Comment by qryxip** [comment]
Changed `LicenseUrl` to <https://www.sharevox.app/terms> for the same reason as <https://github.com/microsoft/winget-pkgs/pull/133789#discussion_r1451368368>.
[`aa318a2` (#133790)](https://github.com/microsoft/winget-pkgs/pull/133790/commits/aa318a28b6c1feb987466cb18b94efc2f8080b66)

@y-chan OK?

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
