### PR TITLE
UPDATE: Azure DevOps Migration Tools 15.1.3 

### PR DESCRIPTION
**Pull request by MrHinsh**
Will add:

`ElevationRequirement: elevationProhibited`
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/163101)

### CODE REVIEW

**Comment by Trenly** [comment]
Because this is a portable application, `ElevationRequirement` won't actually be checked

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334960
> 2024-07-15 23:04:25.632 [CLI ] ShellExecute installer failed: 2147942405

(Automated response - build 886.)

**Comment by MrHinsh** [comment]
The only difference in this run from the previous one in the elevated permission. 

Dependancies are the same as passed  before.

**Comment by stephengillie** [comment]
I believe the pipelines might be failing to de-elevate properly. This failed from an Administrator Powershell window, but was successful from a non-elevated window.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
