### PR TITLE
Newer Version: Typst.Typst 0.4.0

### PR DESCRIPTION
**Pull request by BrandonWanHuanSheng**
Holding off merged due to the issue of RelativeFilePath. Also, Winget 1.5 and higher version is not yet released. Pull Request is converting to draft.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/107645)

### CODE REVIEW

**Comment by stephengillie** [comment]
I don't see the cause for the [Policy 1.2](https://learn.microsoft.com/en-us/windows/package-manager/package/windows-package-manager-policies#12-security) check.

**Comment by BrandonWanHuanSheng** [comment]
I also don't know why?

**Comment by stephengillie** [comment]
This package is expecting arguments:
```
typst creates PDF files from .typ files

Usage: typst.exe [OPTIONS] <COMMAND>

Commands:
  compile  Compiles the input file into a PDF file [aliases: c]
  watch    Watches the input file and recompiles on changes [aliases: w]
  fonts    List all discovered fonts in system and custom font paths
  help     Print this message or the help of the given subcommand(s)

Options:
...
```

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
