### PR TITLE
Remove version: ElectronicArts.EADesktop version 13.96.0.5609

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135702)

### CODE REVIEW

**Comment by drshtmstry** [comment]
> Sequence contains no elements

- #133371

**Comment by Exorcism0666** [comment]
Duplicate PR

**Comment by drshtmstry** [comment]
> Sequence contains no elements

- #133371

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-22T06:46:49.7097728Z Processing manifest: manifests\e\ElectronicArts\EADesktop\13.96.0.5609
 2024-01-22T06:46:49.7112634Z -----------------------------------------------------
 2024-01-22T06:46:49.7120505Z Status: Started
 2024-01-22T06:46:49.7128485Z Manifest file is Deleted
 2024-01-22T06:46:49.9771853Z Status: Completed
 2024-01-22T06:46:49.9779855Z ##[error] Result: Failed
 2024-01-22T06:46:49.9832950Z ##[error] Sequence contains no elements
 2024-01-22T06:46:50.0372831Z ##[error]Manifest Validation Failed

(Automated response - build 626.)

**Comment by stephengillie** [comment]
URL: https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EAappInstaller.exe 
Status Code: 200

(Automated message - build 627)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
