### PR TITLE
New package: Microsoft.Sysinternals.RAMMap version 1.61

### LINKED ISSUE #172338: [Package Request]: Add RAMMap
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://learn.microsoft.com/en-us/sysinternals/downloads/rammap
Publisher: Microsoft
Package Name: Microsoft.Sysinternals.RAMMap
Description: "Use RAMMap to gain understanding of the way Windows manages memory, to analyze application memory usage, or to answer specific questions about how RAM is being allocated. RAMMap’s refresh feature enables you to update the display and it includes support for saving and loading memory snapshots."
Package Version: 1.61
Installer URL: portable:
x86: https://live.sysinternals.com/RAMMap.exe
x64: https://live.sysinternals.com/RAMMap64.exe
ARM64: https://live.sysinternals.com/ARM64/RAMMap64a.exe

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #172338

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/172432)

### CODE REVIEW

**Comment by Dragon1573** [comment]
Manually validate in _Windows Sandbox_.

image

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Microsoft.Sysinternals.RAMMap__DefaultSource\RAMMap64.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\RAMMap64.exe returned exit code: 1
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Packages\Microsoft.Sysinternals.RAMMap__DefaultSource\RAMMap.exe returned exit code: 1
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\RAMMap.exe returned exit code: 1

(Automated response - build 895.)

**Comment by stephengillie** [comment]
Verify:
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
