### PR TITLE
Delete VMware Workstation Pro

### PR DESCRIPTION
**Pull request by auanasgheps**
Workstation Pro is now free for personal use, but the dowload is locked behind a Broadcom account and extensive data sharing.

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest

---

Workstation Pro is now free for personal use, but the dowload is locked behind a Broadcom account and extensive data sharing.

Broadcom has ceased VMware Download servers: now downloads go trough Broadcom's servers. The new download link is https://downloads2.broadcom.com/?file=VMware-workstation-full-17.5.2-23775571.exe but it doesn't work without your personal authentication headers. 

This package in a broken state right now.

There's no solution to this sad change, hence removing it.

Source: I am a Broadcom (ex VMware) employee.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/154072)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://download3.vmware.com/software/WKST-1750-WIN/VMware-workstation-full-17.5.0-22583795.exe 
Response Error: The remote server returned an error: (522).

(Automated message - build 887)

**Comment by stephengillie** [comment]
Hi @auanasgheps,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 881.)

**Review by stephengillie — APPROVED** [review]

**Comment by Natanel-Shitrit** [comment]
It's still possible to download VMWare Workstation Pro without any registration from [this link](https://softwareupdate.vmware.com/cds/vmw-desktop/ws).

It would not be a drop-in replacement since they've decided to "compress" the files.
I'm not familiar with `winget` but I guess it would not be too hard to support `.tar` extraction.

**Comment by zealic** [comment]
> 仍然可以从此[链接](https://softwareupdate.vmware.com/cds/vmw-desktop/ws)下载 VMWare Workstation Pro，无需任何注册。（来自官方域名）
> 
> 由于他们决定“压缩”文件，因此它不会成为直接替代品。 我对此并不熟悉，`winget`但我猜支持提取不会太难`.tar`。

Latest version url:
`https://softwareupdate.vmware.com/cds/vmw-desktop/ws/17.5.2/23775571/windows/core/VMware-workstation-17.5.2-23775571.exe.tar`

**Comment by auanasgheps** [comment]
Hi, thanks for letting me know, but tar packages are not supported by winget.
We have to wait for #2899

**Comment by Natanel-Shitrit** [comment]
Just to clarify, waiting for: https://github.com/microsoft/winget-cli/issues/2899

**Comment by github-account1111** [comment]
> It's still possible to download VMWare Workstation Pro without any registration from [this link](https://softwareupdate.vmware.com/cds/vmw-desktop/ws). (from the official domain)

For some reason it needs to be https://softwareupdate.vmware.com/cds/vmw-desktop/ws/, not https://softwareupdate.vmware.com/cds/vmw-desktop/ws. Without the `/` at the end, clicking the version links leads to `Object Not Found`.

**Comment by Natanel-Shitrit** [comment]
> ... Broadcom is now requiring users to have a product entitlement (that is, a subscription) to access in-product updates. If a user doesn't have a subscription to a product, in-product updates for that product will not work. Broadcom made changes to the software update servers to enforce this new policy. 

> A statement by Broadcom confirms that the in-product update feature is no longer being provided for Workstation/Fusion users.

[Source](https://community.broadcom.com/vmware-cloud-foundation/discussion/the-update-server-could-not-be-resolved-error-when-checking-for-workstation-updates#bm125429dc-28c8-4ad2-b6d1-577ead955593)

Thank you Broadcom for shutting down the whole updating server to harvest people data and force them into signing up!

**Pull request merged**
