### PR TITLE
New version: Microsoft.WindowsTerminal version 1.12.10983.0

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Preparing to break stuff

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/58834)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
Windows 11 Pipeline VM not ready :(
```
2022-04-27 00:19:00.581 [CLI ] Installer [X64,Msix,Unknown,] not applicable: Current OS is lower than MinOSVersion 10.0.22000.0
2022-04-27 00:19:00.581 [CLI ] Installer [Arm64,Msix,Unknown,] not applicable: Current OS is lower than MinOSVersion 10.0.22000.0
2022-04-27 00:19:00.581 [CLI ] Installer [X86,Msix,Unknown,] not applicable: Current OS is lower than MinOSVersion 10.0.22000.0
```

**Comment by OfficialEsco** [comment]
@denelon where is my Windows 11 Pipeline VM? >:C
```
2022-04-27 17:55:10.697 [CLI ] Installer [X64,msix,Unknown,] not applicable: Current OS is lower than MinOSVersion 10.0.22000.0
2022-04-27 17:55:10.698 [CLI ] Installer [Arm64,msix,Unknown,] not applicable: Current OS is lower than MinOSVersion 10.0.22000.0
2022-04-27 17:55:10.698 [CLI ] Installer [Arm64,msix,Unknown,] not applicable: Machine is not compatible with Arm64
2022-04-27 17:55:10.698 [CLI ] Installer [X86,msix,Unknown,] not applicable: Current OS is lower than MinOSVersion 10.0.22000.0
```

**Comment by denelon** [comment]
@OfficialEsco I think it was a race condition caused by humans 😂

**Pull request merged**
