### PR TITLE
New version: Speakeasy.speakeasy 1.451.6

### LINKED ISSUE #196381: [Package Request]: Speakeasy CLI
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/speakeasy-api/speakeasy/releases/tag/v1.451.5
Publisher: Speakeasy Inc
Package Name: speakeasy.cli
Description: This CLI is a tool for interacting with the Speakeasy platform - the CLI brings the functionality of Speakeasy into your development workflow. It can be run locally or in your CI/CD pipeline to validate your API specs, generate SDKs and more.

      Current functions of the CLI include:

      Generating idiomatic client SDKs from OpenAPI3.X specs:
      Live: Go, Python3, Typescript(Node), Java, PHP, Ruby, Terraform
      Validating the correctness of OpenAPI3 specs. The CLI has a built in command to validate your spec and post helpful error messages.
      Authenticating with the platform and managing API keys.
Package Version: 1.451.5
Installer Url: https://github.com/speakeasy-api/speakeasy/releases/download/v1.451.5/speakeasy_windows_amd64.zip

### PR DESCRIPTION
**Pull request by TristanSpeakEasy**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #196381

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/196383)

### CODE REVIEW

**Comment by TristanSpeakEasy** [comment]
https://github.com/microsoft/winget-pkgs/issues/196381

**Comment by TristanSpeakEasy** [comment]
This seems to work locally and just looks like a timeout in the action, anyway to kick it off again?

image

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-12-05 10:33:08.060 [FAIL] Installer failed security check. Url: https://github.com/speakeasy-api/speakeasy/releases/download/v1.451.6/speakeasy_windows_amd64.zip Result: 0x80004005

(Automated response - build 900.)

**Comment by TristanSpeakEasy** [comment]
@stephengillie is there any more information on the windows defender error? I have scanned it locally on Windows 11 and no issues were picked up.

And I can't see anything in the github checks that were run.

Happy to submit a false positive to the Defender team but not sure what to submit as I don't have the details

**Comment by TristanSpeakEasy** [comment]
@stephengillie I did submit to the Defender team and it can back with no malware detected 
image

**Comment by stephengillie** [comment]
Verify:
image

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
> @stephengillie is there any more information on the windows defender error? I have scanned it locally on Windows 11 and no issues were picked up.
> 
> And I can't see anything in the github checks that were run.
> 
> Happy to submit a false positive to the Defender team but not sure what to submit as I don't have the details

Sorry for the delay. Please find the [log file](https://github.com/user-attachments/files/18043732/Speakeasy.speakeasy.x86.1.451.6.log) attached. Here are some relevant bits:

> 10:33:08 AM: Detected 1 WinGet errors: 
10:33:08 AM: 2024-12-05 10:33:08.060 [FAIL] Installer failed security check. Url: https://github.com/speakeasy-api/speakeasy/releases/download/v1.451.6/speakeasy_windows_amd64.zip Result: 0x80004005
10:33:08 AM: Detected 1 Manual Dependency: 
10:33:08 AM: 
10:33:08 AM: Detected 0 PowerShell errors: 
10:33:08 AM: Detected 0 Application Log errors: 
10:33:08 AM: 
10:33:08 AM: Detected 1 Defender (with signature version ) errors: 
10:33:08 AM: Trojan:Script/Wacatac.B!ml
10:33:08 AM:  = = = = Failing Manual Validation pipeline build 900 on VM 899 for Speakeasy.speakeasy Win10 version 1.451.6 x86  in 49.2742451 seconds. = = = = 

Unfortunately, it seems that the signature version wasn't recorded. I'll have to check if something has changed there.

**Pull request merged**
