### PR TITLE
Added Jackett version 0.18.648.0.

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

------

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/26912)

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
Duplicate of #26881

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/26912#issuecomment-912646965

**Comment by jedieaston** [comment]
My local fork wasn't up to date, sorry.

**Comment by vedantmgoyal2009** [comment]
Why don't you update your fork automatically?

**Comment by jedieaston** [comment]
I don't always remember to run `git pull`. I have a script that checks the file tree against whatever Jackett's current version is and opens a PR if necessary, but since I didn't have the latest upstream changes on my local box it didn't work. (Really, what I should be doing is using winget itself to get the latest version available instead of using the fork, but it wouldn't help if the PR hadn't been approved).

**Comment by vedantmgoyal2009** [comment]
I mean you could set up GitHub Actions like me which runs every 5 minutes and will automatically update your fork. This would save your time in updating the fork manually again and again. I have done like this (https://github.com/vedantmgoyal2009/winget-pkgs/blob/master/.github/workflows/simple-workflow.yml)

> I don't always remember to run `git pull`. I have a script that checks the file tree against whatever Jackett's current version is and opens a PR if necessary, but since I didn't have the latest upstream changes on my local box it didn't work. (Really, what I should be doing is using winget itself to get the latest version available instead of using the fork, but it wouldn't help if the PR hadn't been approved).

Do you make scripts for everything? 😶

**Pull request closed without merging**
