### PR TITLE
NirSoft.UninstallView version 1.51

### LINKED ISSUE #165619: [Package Request]: NirSoft.UninstallView
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.nirsoft.net/utils/uninstall_view.html
Publisher: NirSoft
Package Name: UninstallView
Description: Alternative uninstaller for Windows
Package Version: 1.51
Installer URL: https://www.nirsoft.net/utils/uninstallview.zip; https://www.nirsoft.net/utils/uninstallview-x64.zip

### PR DESCRIPTION
**Pull request by KarbitsCode**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?
Resolves #165619

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/165621)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @KarbitsCode, 

This installer doesn't seem to modify the filesystem. Is this expected?
image

**Comment by KarbitsCode** [comment]
> Hi @KarbitsCode, 
> 
> This installer doesn't seem to modify the filesystem. Is this expected?
> 

It should install UninstallView as a command, have you tried that?

**Comment by stephengillie** [comment]
I'm not entirely sure what kind of command. PowerShell doesn't seem to recognize it:
image

**Comment by KarbitsCode** [comment]
Hm... weird, I'll take a look

**Comment by KarbitsCode** [comment]
Can you verify the install log like this?

Screenshot 2024-08-06 101906

**Comment by stephengillie** [comment]
Yesterday's manual validations: 
[NirSoft.UninstallView.1.51.log](https://github.com/user-attachments/files/16512758/NirSoft.UninstallView.1.51.log)
[NirSoft.UninstallView.x86.1.51.log](https://github.com/user-attachments/files/16512759/NirSoft.UninstallView.x86.1.51.log)
Today's:
[NirSoft.UninstallView.x86.1.51.log](https://github.com/user-attachments/files/16512764/NirSoft.UninstallView.x86.1.51.log)

**Comment by KarbitsCode** [comment]
Works fine on x64 version, maybe x86 is bad? I can't really check the x86 version

Screenshot 2024-08-07 093744

**Comment by stephengillie** [comment]
> Works fine on x64 version, maybe x86 is bad? I can't really check the x86 version
> 
> Screenshot 2024-08-07 093744

I'm seeing the same situation with the `x64` as with the `x86`. Feel free to install the `x86` on a 64-bit OS for testing - that's what I did above. The technology is generally backwards-compatible.

**Comment by KarbitsCode** [comment]
Confirmed both x86 and x64 versions installed and launched normally, and I don't really see anything wrong with either the manifest or the package itself, maybe there is something wrong with the pipeline?

Screenshot 2024-08-10 140620
Screenshot 2024-08-10 141007

**Comment by stephengillie** [comment]
Hi @KarbitsCode, 

The Automatic Validation Pipeline uses SDL-provided VMs. The manual validation pipeline uses VMs downloaded with Hyper-V Quick Create. There are as few modifications as possible performed on these. 

Could you be more specific about the "something" to which you're alluding? Do you believe there is a specific framework or package missing from these? Or is there an application or feature in place which should be removed?

**Comment by KarbitsCode** [comment]
> Could you be more specific about the "something" to which you're alluding?

I don't know, from the manual validation and the log you provide it seems it doesn't even try to extracting anything, so i have no idea how that happened

> Do you believe there is a specific framework or package missing from these?

I don't think so, it should have no dependencies, just like any other nirsoft software

**Comment by KarbitsCode** [comment]
I think this may become a blocking issue, since I didn't have any resolution at the moment

**Pull request closed without merging**
