### PR TITLE
New version: GOMLab.GOMPlayer version 2.3.95.5365

### PR DESCRIPTION
**Pull request by Trenly**
﻿Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.
* https://github.com/microsoft/winget-pkgs/issues/147885
* https://github.com/microsoft/winget-pkgs/issues/137039
---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/147901)

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 The orchestrator function 'InstallerOrchestrator' failed: "The orchestrator function 'ESRPOrchestrator' failed: "Exception of type 'Microsoft.WinGetSvc.WinGet.ESRP.Common.WinGetESRPTimeoutException' was thrown.". See the function execution logs for additional details.". See the function execution logs for additional details.
 The orchestrator function 'InstallerOrchestrator' failed: "The orchestrator function 'ESRPOrchestrator' failed: "Exception of type 'Microsoft.WinGetSvc.WinGet.ESRP.Common.WinGetESRPTimeoutException' was thrown.". See the function execution logs for additional details.". See the function execution logs for additional details.
 

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Installer https://cdn.gomlab.com/gretech/player/GOMPLAYERGLOBALSETUP_CHROME.EXE
 Scan request id: '09d83188-9936-4279-bf8a-cde05b363e52'
 Error information: BlockingDetectionFound
 
 4/8/2024 9:43:51 PM
 
 ****************************************************************************************
 Installer Validation
 ****************************************************************************************
 

(Automated response - build 876.)

**Comment by stephengillie** [comment]
This might be due to a network block of data centers, to prevent automated downloads.

(Automated response - build 876.)

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
