### PR TITLE
New version: Egnyte.EgnyteDesktopApp version 3.21.0.153

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#10385](https://github.com/SpecterShell/Dumplings/actions/runs/12412265176).

<details>

<summary>Log</summary>

````
Updated: 3.20.1.151 → 3.21.0.153
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/199794)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Manual Validation keeps getting stuck after running `profile.lnk`:
image

(The "process latch" is a new feature with a bug that I'm solving seprately.)

**Comment by SpecterShell** [comment]
@stephengillie

图片

**Comment by stephengillie** [comment]
Manual Validation ended with:
> C:\Program Files (x86)\Egnyte Connect\DesktopSync\zmq\backend\cython\error.cp312-win32.pyd C:\Windows\appcompat\UA\GenericError.png 	md $ManValLogFolder -ErrorAction Ignore Function Out-ErrorData ($errArray,[string]$serviceName,$errorName='errors') { 	Out-Log "Detected $($errArray.count) $serviceName $($errorName): " Out-Log 'Clearing PowerShell errors.' $Error.Clear() Clear-EventLog -LogName Application -ErrorAction Ignore Out-ErrorData @($info[0],$info[3],$info[4],$info[5]) 'WinGet' 'infos' 	Out-Log 'Install Failed.'; 		$_ -match 'failed' -OR  		$_ -match 'error' -OR  		$_ -match 'does not match' Out-ErrorData $WinGetLogs 'WinGet' Out-ErrorData '' 'Manual' 'Dependency' Out-ErrorData $Error 'PowerShell' Out-ErrorData (Get-EventLog Application -EntryType Error -after $TimeStart -ErrorAction Ignore).Message 'Application Log' Out-ErrorData $DefenderThreat "Defender (with signature version $((Get-MpComputerStatus).QuickScanSignatureVersion))" if (($WinGetLogs -match '\[FAIL\] Installer failed security check.') -OR  ($WinGetLogs -match 'Package hash verification failed') -OR  	Send-SharedError -clip $WinGetLogs 	Send-SharedError -clip $DefenderThreat 		Get-ChildItem c:\ -File -Recurse -ErrorAction Ignore -Force |  		Get-ChildItem c:\ -File -Recurse -ErrorAction Ignore -Force |  		Get-ChildItem c:\ -File -Recurse -ErrorAction Ignore -Force |  Where-Object {$_ -notmatch 'ErrorDialog = ErrorDlg'} |  Where-Object {$_ -notmatch 'Windows Error Reporting'} |  $WinGetLogs = ((Get-ChildItem $WinGetLogFolder).fullname | ForEach-Object {Get-Content $_ |Where-Object {$_ -match '[[]FAIL[]]' -OR $_ -match 'failed' -OR $_ -match 'error' -OR $_ -match 'does not match'}}) Out-ErrorData $WinGetLogs 'WinGet' Out-ErrorData '' 'Manual' 'Dependency' Out-ErrorData $Error 'PowerShell' Out-ErrorData (Get-EventLog Application -EntryType Error -after $TimeStart -ErrorAction Ignore).Message 'Application Log' Out-ErrorData $DefenderThreat "Defender (with signature version $((Get-MpComputerStatus).QuickScanSignatureVersion))" if (($WinGetLogs -match '\[FAIL\] Installer failed security check.') -OR  ($WinGetLogs -match 'Package hash verification failed') -OR  	Send-SharedError -clip $WinGetLogs 	Send-SharedError -clip $DefenderThreat

(Automated response - build 931.)

**Comment by stephengillie** [comment]
> Manual Validation keeps getting stuck after running `profile.lnk`: image
> 
> (The "process latch" is a new feature with a bug that I'm solving seprately.)

Catching up from the backlog. Had to manually restart the process:
image

**Pull request merged**
