### PR TITLE
New package: Autodesk.Meshmixer version 11.5.474

### PR DESCRIPTION
**Pull request by Masamune3210**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132034)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335226 
> 2023-12-28 14:16:47.765 [CLI ] ShellExecute installer failed: 1223

(Automated response - build 498.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 3:32:23 PM: 
> 2023-12-28 15:32:21.574 [CLI ] ShellExecute installer failed: 1223

(Automated response - build 489.)

**Comment by stephengillie** [comment]
Hi @Masamune3210,

This package seems to have an issue. Installing silently or attended, both seem to install the application. But clicking on the desktop shortcut only gives this error report:

image

**Comment by Masamune3210** [comment]
Hmm, that's weird. I'll look at it when I get home

**Pull request closed without merging**
