### PR TITLE
Remove: Splashtop.SOS 3.6.0.1

### PR DESCRIPTION
**Pull request by BinBinTsai**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/130143)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @BinBinTsai,

The package download still works for me. Why should it be removed?

**Comment by BinBinTsai** [comment]
hi @stephengillie 
We are trying to verify the flow for removing the old version.

**Comment by stephengillie** [comment]
Oh. What flow are you trying to verify?

**Comment by BinBinTsai** [comment]
> Oh. What flow are you trying to verify?

How to remove the old release, if needed.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
