### PR TITLE
Move GrafanaLabs.GrafanaEnterprise 8.3.5.0 to GrafanaLabs.Grafana.Enterprise 8.3.5.0 [Delete Old]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/46769)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
@denelon this one is different

**Comment by denelon** [comment]
So do you want this one to get approved after validation?

**Comment by OfficialEsco** [comment]
I mean its stuck in a different way, it only got the Validation check

**Review by ghost — APPROVED** [review]

**Pull request merged**
