### PR TITLE
Added MySQL Shell 8.0.28

### PR DESCRIPTION
**Pull request by fabiang**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Could not validate and test mainfest locally.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/47644)

### CODE REVIEW

**Comment by Trenly** [comment]
This package has a dependency -
```
MSI (s) (0C:30) [09:24:50:801]: Product: MySQL Shell 8.0.28 -- This application requires Visual Studio 2019 Redistributable. Please install the Redistributable then run this installer again.

This application requires Visual Studio 2019 Redistributable. Please install the Redistributable then run this installer again.
```

**Comment by Trenly** [comment]
@denelon - Blocking-Issue; Dependencies

**Comment by fabiang** [comment]
Ok that explains why I can't find any documentation about dependencies. A package manager that isn't able to resolve dependencies?

**Comment by Trenly** [comment]
> Ok that explains why I can't find any documentation about dependencies. A package manager that isn't able to resolve dependencies?

Winget is still quite new in the realm of software and dependencies are a surprisingly complex topic. Between dependencies on windows features, specific libraries, program dependencies, dependencies that require a specific architecture, one-of-many dependencies, group policy requirements, there is a lot to consider. Especially given that the solution needs to be well planned to cover a majority of scenarios, it makes it even more complex.

As Levvie mentioned, it has been in experimental features and you can add it to the manifest so that once the support for dependencies is finalized then it can be merged

**Comment by fabiang** [comment]
I didn't wanted to start a fight. And we all know thats Windows' software installation routines are fubar, hopefully the software will fix this.

**Comment by Trenly** [comment]
> I didn't wanted to start a fight. 

Apologies if I came off harsh. I like to give as much background into issues as possible so that everyone understands the full picture.

> And we all know thats Windows' software installation routines are fubar

I think that is an understatement. In making things easy for everyone in the past, it has made it more difficult now

> hopefully the software will fix this.

I’m sure it will. It seems that a lot of things planned for the 1.4 client release will help a lot

> // Edit: does it make sense to add those fields to the yaml files or is it better to wait?

Its up to you. There isn’t a set timeline of when the support will be enabled in the validation pipelines. I would personally add it now just so that it isn’t something that has to be worried about later, but it really doesn’t make a difference if its now or later

**Comment by fabiang** [comment]
Thanks. I'll wait till this feature is available to everyone and documentation is ready.

**Review by ItzLevvie — APPROVED** [review]

**Comment by fabiang** [comment]
Since we now have support for dependencies I'll close this PR and will re-submit it with a newer version of the MySQL Shell.

Btw: I hope Microsoft will invest more resource in Winget, as this is the best thing what happend to Windows ever.

**Pull request closed without merging**
