### PR TITLE
Metadata: VMware.WorkstationPro v16.1.2

### PR DESCRIPTION
**Pull request by OfficialEsco**
Added Dependencies
Changed Architecture to x86
image
Added machine scope
Added ProductCode
https://github.com/microsoft/winget-cli/issues/1191#issuecomment-875761265

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/20134)

### CODE REVIEW

**Comment by auanasgheps** [comment]
I guess the pipeline is stuck.

**Comment by OfficialEsco** [comment]
> I guess the pipeline is stuck.

Yeeeeah i was going to say but didn't want to spam the thread, the bot might have freaked out or its going to throw a hidden error that it failed to run on the x86 machine, think i'll wait for the 24h mark timeout before i touch it...

It should technically work since the main process is x86 and it installs in Program Files (x86).. Hopefully this isn't a PowerToys situation where it reports differently

**Comment by OfficialEsco** [comment]
@arjun-msft @ChuckFerring imma need a answer on this, is this a x86 package as shows in task manager or is it x64? If its x86, whats the issue?

**Comment by OfficialEsco** [comment]
Well... @auanasgheps x64 arch passed the validation real quick so i guess its technically x64?
Post a issue on winget-cli if it still dosent work..

**Review by ItzLevvie — APPROVED** [review]
image

**Comment by auanasgheps** [comment]
> 
> 
> Well... @auanasgheps x64 arch passed the validation real quick so i guess its technically x64?
> Post a issue on winget-cli if it still dosent work..

Unfortunately it doesn't work. I'll open a new issue there.

**Pull request merged**
