### PR TITLE
New version: Project64.Project64.Dev (version 4.0.0.6430)

### PR DESCRIPTION
**Pull request by seangibbz**
Checklist for Pull Requests
- [Y] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [N] Is there a linked Issue?

Manifests
- [Y] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [Y] This PR only modifies one (1) manifest
- [Y] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [Y] Have you tested your manifest locally with `winget install --manifest <path>`?
- [Y] Does your manifest conform to the [1.7 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.7.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/166285)

### CODE REVIEW

**Comment by seangibbz** [comment]
Installer URL is correct as per previous release standard from [the official website](https://www.pj64-emu.com/nightly-builds).
The URL yields the appropriate installer when used with tools such as wget, winget, etc.

**Comment by seangibbz** [comment]
Version verification
Screenshot 2024-08-05 223119

**Comment by seangibbz** [comment]
> Hello @seangibbz,
> 
> The package manager bot determined that the ManifestVersion key does not match any version currently approved for release. Please verify the manifest file is compliant with the package manager [1.5 manifest specification](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0) or [1.6 manifest specification](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0).
> 
> For details on the specific error, see the details link below in the build pipeline.
> 
> Template: msftbot/validationError/manifest/version/error

Manifest was configured to match the most updated available version in the repository (i.e. [1.7.0](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.7.0))

**Comment by stephengillie** [comment]
Hi @seangibbz,

It appears that support for 1.7 schema is not yet enabled: 
- https://github.com/microsoft/winget-pkgs/issues/165726

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
