### PR TITLE
Add QOwnNotes 21.7.4

### PR DESCRIPTION
**Pull request by pbek**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/20295)

### CODE REVIEW

**Comment by ImJoakim** [comment]
Hey @pbek, there is currently not support for zip files.

**Comment by pbek** [comment]
Thank you for letting me know, @ImJoakim. Too bad I didn't find that out before the ordeal of creating the manifest files. 😅

**Comment by pbek** [comment]
I was happy to see "ZIP" in https://github.com/microsoft/winget-cli/blob/master/schemas/JSON/manifests/v1.0.0/manifest.installer.1.0.0.json#L56 😁

**Comment by ImJoakim** [comment]
Seems like this issue regarding zip files is this open:

https://github.com/microsoft/winget-cli/issues/140

**Comment by pbek** [comment]
Thank you, I'll subscribe those!

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Since `.zip` files aren't currently supported in the client, would you like to close the PR for now and open it back up when support has been added?

**Comment by pbek** [comment]
Btw. would it work to create an "exe"  from a self extracting zip and use that?

**Comment by denelon** [comment]
@pbek that wouldn't work just yet either. We're adding support for complex installers in the [schema for 1.1](https://github.com/microsoft/winget-cli/issues/1243), but the client implementation to handle the various .zip and self extracting .exe are still not at the top of the to do list yet. We're currently focusing on things to improve the install/upgrade/import success rates.

**Comment by pbek** [comment]
Ok, thank you.

**Pull request closed without merging**
