### PR TITLE
New version: goplus.gop 1.2.5

### PR DESCRIPTION
**Pull request by cpunion**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/143751)

### CODE REVIEW

**Comment by cpunion** [comment]
Need more information.

**Comment by stephengillie** [comment]
Hi @cpunion,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 869.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-10 17:32:30.040 [FAIL] Installer failed security check. Url: https://github.com/goplus/gop/releases/download/v1.2.5/gop_v1.2.5_Windows_x86_64.zip Result: 0x80004005
> MSI (s) (18:30) [17:32:09:348]: An error occured while refreshing environment variables updated during the installation of ''. Some users logged on to the machine may not see these changes until they log off and then log back on.
> Property(S): dirC1D8E01F6B8B58824E992A66BFEC66EA = C:\Program Files\Go\src\cmd\cgo\internal\testerrors\
> Property(S): dir446D7A79D5DF29B74E6C3118A0FBA488 = C:\Program Files\Go\src\cmd\cgo\internal\testerrors\testdata\
> Property(S): dir4C81B01258ED70E2354B05EC1D50A64D = C:\Program Files\Go\src\cmd\vendor\golang.org\x\tools\go\analysis\passes\errorsas\
> Property(S): dir563DB259519880316A9FD76C701BC816 = C:\Program Files\Go\src\errors\
> Property(S): dir18C753920C81A78D6EB38F46F6404A03 = C:\Program Files\Go\src\internal\oserror\
> Property(S): dirDFA0FA250B47DCC2A636304D2F9AA4FE = C:\Program Files\Go\src\internal\types\errors\
> Property(S): ErrorDialog = ErrorDlg
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\gopfmt.exe returned exit code: 2
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\gop.exe returned exit code: 2

(Automated response - build 869.)

**Comment by stephengillie** [comment]
Hi @cpunion,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 869.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-10 17:32:30.040 [FAIL] Installer failed security check. Url: https://github.com/goplus/gop/releases/download/v1.2.5/gop_v1.2.5_Windows_x86_64.zip Result: 0x80004005
> MSI (s) (18:30) [17:32:09:348]: An error occured while refreshing environment variables updated during the installation of ''. Some users logged on to the machine may not see these changes until they log off and then log back on.
> Property(S): dirC1D8E01F6B8B58824E992A66BFEC66EA = C:\Program Files\Go\src\cmd\cgo\internal\testerrors\
> Property(S): dir446D7A79D5DF29B74E6C3118A0FBA488 = C:\Program Files\Go\src\cmd\cgo\internal\testerrors\testdata\
> Property(S): dir4C81B01258ED70E2354B05EC1D50A64D = C:\Program Files\Go\src\cmd\vendor\golang.org\x\tools\go\analysis\passes\errorsas\
> Property(S): dir563DB259519880316A9FD76C701BC816 = C:\Program Files\Go\src\errors\
> Property(S): dir18C753920C81A78D6EB38F46F6404A03 = C:\Program Files\Go\src\internal\oserror\
> Property(S): dirDFA0FA250B47DCC2A636304D2F9AA4FE = C:\Program Files\Go\src\internal\types\errors\
> Property(S): ErrorDialog = ErrorDlg
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\gopfmt.exe returned exit code: 2
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\gop.exe returned exit code: 2

(Automated response - build 869.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\gop.exe returned exit code: 2
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\gopfmt.exe returned exit code: 2
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\gopfmt.exe returned exit code: 2
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\gop.exe returned exit code: 2

(Automated response - build 869.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
