### PR TITLE
New version: GodotEngine.GodotEngine.Mono version 4.2

### PR DESCRIPTION
**Pull request by alexsussy**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/130079)

### CODE REVIEW

**Comment by stephengillie** [comment]
Current manifest version 4.1.2 has 3 parameters, which is greater than this PR's version number 4.2's 2 parameters.

**Comment by stephengillie** [comment]
Hi alexsussy

> Current manifest version 4.1.2 has 3 parameters, which is greater than this PR's version number "4.2"'s 2 parameters.\n\nIs this intentional?

**Comment by alexsussy** [comment]
Hi @stephengillie ,

Forgive me, I'm still quite new to this! I'm unsure how to resolve the parameter issue, but as far as I can tell, the 4.1.2 manifest is near identical and installing 4.2 locally works as expected with no missing functionality. I did push some minor corrections.

Please correct me if I'm wrong, any advice is appreciated.

**Comment by stephengillie** [comment]
Hi @alexsussy,

Just checking if the version number is coming from the developer. We have a few situations where a version number will have parameters added or removed arbitrarily, and this can cause issues with determining which version is the most recent.

But if the developer has called this version `4.1.2` then no worries.

**Comment by stephengillie** [comment]
Hi @alexsussy

> Current manifest version 4.1.2 has 3 parameters, which is greater than this PR's version number 4.2's 2 parameters.

Is this intentional?

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
