### PR TITLE
New version: GitKraken.cli version 2.1.2

### PR DESCRIPTION
**Pull request by sergiolms**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/188542)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-11-04 03:28:16.528 [FAIL] Installer failed security check. Url: https://github.com/gitkraken/gk-cli/releases/download/v2.1.2/gk_2.1.2_Windows_x86_64.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Comment by JBUinfo** [comment]
@stephengillie
I cannot reproduce the error. Everything seems to work fine on my machine 
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
