### PR TITLE
Update: Anaconda.Anaconda3 version 2021.11

### LINKED ISSUE #36706: [Bug]: Anaconda creates multiple entries in add/remove after updating
### Brief description of your issue

I had Anaconda3 2021.05 installed on 30 October 2021. On 29 November 2021, I ran a `winget upgrade --all` command and Anaconda3 2021.11 started installing as expected. After installation though, there were separate entries to uninstall both of the above programs in the add or remove programs page in the settings app.
image

### Steps to reproduce

- Install earlier version at earlier date
- Update to a newer version using `winget upgrade --all`
- Get multiple uninstall entries

### Expected behavior

I think only the latest version entry should be available to uninstall as the actual program installation folder contains only the latest version files.

### Actual behavior

There were separate entries to uninstall both of the above programs in the add or remove programs page in the settings app.

### Environment

```shell
Windows Package Manager (Preview) v1.2.3131-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.348
Package: Microsoft.DesktopAppInstaller v1.17.3131.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

* Resolves #36706

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/41556)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by github-account1111** [comment]
After upgrading Anaconda using winget (`winget upgrade --all --source winget`) I am now getting this:

image

Is this a known issue?
How could I go about fixing?

**Comment by OfficialEsco** [comment]
Hmm, thats weird, i was going to say it changed install location, however when i tested it did install to `C:\Users\User\anaconda3\`
```
PS M:\> C:\Users\User\anaconda3\Scripts\conda.exe
usage: conda-script.py [-h] [-V] command ...

conda is a tool for managing and deploying applications, environments and packages.

Options:

positional arguments:
  command
    clean        Remove unused packages and caches.
    compare      Compare packages between conda environments.
    config       Modify configuration values in .condarc. This is modeled after the git config command. Writes to the
                 user .condarc file (C:\Users\User\.condarc) by default.
    create       Create a new conda environment from a list of specified packages.
    help         Displays a list of available conda commands and their help strings.
    info         Display information about current conda install.
    init         Initialize conda for shell interaction. [Experimental]
    install      Installs a list of packages into a specified conda environment.
    list         List linked packages in a conda environment.
    package      Low-level conda package utility. (EXPERIMENTAL)
    remove       Remove a list of packages from a specified conda environment.
    uninstall    Alias for conda remove.
    run          Run an executable in a conda environment. [Experimental]
    search       Search for packages and display associated information. The input is a MatchSpec, a query language
                 for conda packages. See examples below.
    update       Updates conda packages to the latest compatible version.
    upgrade      Alias for conda update.

optional arguments:
  -h, --help     Show this help message and exit.
  -V, --version  Show the conda version number and exit.

conda commands available from other packages:
  build
  content-trust
  convert
  debug
  develop
  env
  index
  inspect
  metapackage
  pack
  render
  repo
  server
  skeleton
  token
  verify
```
Could you have installed it Machine wide before? aka had 2 installations? (Since it doesn't uninstall the previous one)
Can you check if its installed to `C:\ProgramData\Anaconda3`?

**Comment by github-account1111** [comment]
> Can you check if its installed to C:\ProgramData\Anaconda3?

No that one doesn't exist and iirc never existed.
However `C:\Users\User\anaconda3` is gone, and that one definitely did exist before.
I've found that Anaconda is very fragile in general.
I've lost count of how many times I've had to reinstall it for various reasons.
Thinking of moving to docker + pip-tools because of it.

**Pull request merged**
