### PR TITLE
New version: Sayuri.FFFTP version 5.7 [FP-D]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Failed
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | ffftp | Signal 5.42.0, Signal Beta 5.43.0-beta.1    |
| Version     | 5.7     | 5.42.0, 5.43.0-beta.1 |
| Publisher   | Kurata Sayuri   | Signal Messenger, LLC, Signal Messenger, LLC      |
| ProductCode | {62BB40B0-CF26-414D-B76B-8C3C8D826599}          | 7d96caee-06e6-597c-9f2f-c7bb2e0948b4, b39ac3a0-cc73-5ec2-ba18-5ab3c4de1ca1    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [1401](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/2273576958>)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
Alpha URL - not release URL

**Comment by vedantmgoyal2009** [comment]
@trenly I think I have set the $UpdateCondition correctly in PostResponseScript field correctly. Can you tell why is it true always?

cidercollective.cider: https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/winget-pkgs-automation/packages/c/cidercollective.cider.json
cidercollective.cider.nightly: https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/winget-pkgs-automation/packages/c/cidercollective.cider.nightly.json

**Comment by Trenly** [comment]
> @Trenly I think I have set the $UpdateCondition correctly in PostResponseScript field correctly. Can you tell why is it true always?
> 
> cidercollective.cider: https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/winget-pkgs-automation/packages/c/cidercollective.cider.json cidercollective.cider.nightly: https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/winget-pkgs-automation/packages/c/cidercollective.cider.nightly.json

Because the Post-Response script isn't being implemented correctlt

> @Trenly I think I have set the $UpdateCondition correctly in PostResponseScript field correctly. Can you tell why is it true always?
> 
> cidercollective.cider: https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/winget-pkgs-automation/packages/c/cidercollective.cider.json cidercollective.cider.nightly: https://github.com/vedantmgoyal2009/vedantmgoyal2009/blob/main/winget-pkgs-automation/packages/c/cidercollective.cider.nightly.json

You're missing a `-and` after you check if it matches develop

**Comment by vedantmgoyal2009** [comment]
Oh, thanks! I had seen it a couple of times before adding the JSON but still didn't notice that.

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
Whats up with the title?

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
