### PR TITLE
New version: Telegram.TelegramDesktop version 5.5.1

### PR DESCRIPTION
**Pull request by john-preston**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/172102)

### CODE REVIEW

**Comment by KarbitsCode** [comment]
Duplicate of #172103

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 895.)

**Comment by stephengillie** [comment]
Hi @john-preston,

You've submitted numerous PRs, but have never signed the CLA. WIthout a signed CLA, we cannot use your submissions.

**Comment by stephengillie** [comment]
Close with reason: Duplicate of #172103;

**Pull request closed without merging**
