### PR TITLE
Remove Old: JanDeDobbeleer.OhMyPosh version 3.175.0

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
null

### CODE REVIEW

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
no changes

**Comment by vedantmgoyal2009** [comment]
no changes but found an issue for Trenly ;)

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Removes `ReleaseNotesUrl`.

**Comment by vedantmgoyal2009** [comment]
@itzlevvie, according to Trenly at https://gitter.im/Microsoft/winget-pkgs, yamlcreate is supposed to work that way.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
