### PR TITLE
Add uninstallPrevious to Microsoft.WindowsSDK

### PR DESCRIPTION
**Pull request by Trenly**
* Related to microsoft/winget-cli#2634

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/86275)

### CODE REVIEW

**Comment by Trenly** [comment]
@denelon - I can't seem to figure out what the issue is

**Comment by denelon** [comment]
I'm not sure either. I don't know if this package has particular dependencies or if there is something else that's not quite right.

**Review by stephengillie — DISMISSED** [review]

**Comment by stephengillie** [comment]
@Trenly The unattended installer doesn't install any executables, just log and data files. The "attended" mode won't continue without "WPTx64 (OnecoreUAP)-x86_en-us.msi" - should this be a dependency?

**Comment by Trenly** [comment]
> @Trenly The unattended installer doesn't install any executables, just log and data files. The "attended" mode won't continue without "WPTx64 (OnecoreUAP)-x86_en-us.msi" - should this be a dependency?

I'm not sure. If the unattended mode doesn't install any executables, I'm a bit confused as to how this made it into the repo in the first place

**Comment by Trenly** [comment]
@stephengillie - It seems that it does try to download the dependency in unattended mode, but fails because the URL built into the installer is no longer valid. 
```
[0978:0900][2022-10-26T15:52:37]e000: Error 0x80070002: Failed attempt to download URL: 'https://www.bing.com/Installers/WPTx64 (OnecoreUAP)-x86_en-us.msi' to: 'C:\Windows\Temp\{26B73879-004A-42A9-97CA-5DBE913B0FFF}\package_WPTx64OnecoreUAP_x86_en_us'
[0978:0900][2022-10-26T15:52:37]i000: Retry downloading of payload [package_WPTx64OnecoreUAP_x86_en_us] for Package package_WPTx64OnecoreUAP_x86_en_us
```

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
