### PR TITLE
New package: trzsz.tssh version 0.1.7

### LINKED ISSUE #112317: [Package Request]: tssh
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/trzsz/trzsz-ssh/releases
Publisher: `trzsz`
Package Name: `tssh`
Description: `ssh client that supports trzsz, supports selecting or searching servers for login, supports remember password.`
Package Version: `v0.1.7`
Installer URL: 
- https://github.com/trzsz/trzsz-ssh/releases/download/v0.1.7/tssh_0.1.7_windows_x86_64.zip
- https://github.com/trzsz/trzsz-ssh/releases/download/v0.1.7/tssh_0.1.7_windows_aarch64.zip
- https://github.com/trzsz/trzsz-ssh/releases/download/v0.1.7/tssh_0.1.7_windows_i386.zip

### PR DESCRIPTION
**Pull request by lonnywong**
Close #112317

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/112341&drop=dogfoodAlpha

### CODE REVIEW

**Comment by lonnywong** [comment]
@microsoft-github-policy-service agree

**Comment by Trenly** [comment]
[Policy] Needs Attention

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
