### PR TITLE
Use Validation-Unattended-Failed label ONLY

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
image

Two labels are being used for the same purpose. This PR updates @msftbot configuration to use the `Validation-Unattended-Failed` label since it's currently more frequently used than the other label.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/66348)

### CODE REVIEW

**Comment by denelon** [comment]
@vedantmgoyal2009 this needs to be rebased. @Trenly came up with a scheme for helping with e-mail filtering.

**Comment by denelon** [comment]
What's with the disabled false lines? Did you manually remove those?

**Comment by vedantmgoyal2009** [comment]
That was unnecessarily increasing lines of code, hence, I decided to remove them. Also, they aren't affecting anything unless they're set to true.

**Review by denelon — APPROVED** [review]

**Comment by vedantmgoyal2009** [comment]
@denelon I was thinking of msftbot adding an "automatic-update" label to the PRs created from my account. To differentiate b/w automatic and manual contributions, we can look for `Auto-updated by vedantmgoyal2009/winget-pkgs-automation in workflow run 2760` in the pull request body. That would help to easily filter out automated PRs, until the automation is implemented in winget-pkgs repository itself and wingetbot opens the pull request.

**Comment by denelon** [comment]
What's the benefit of doing that? 

I'm actually more tempted to look at how we could get the integration done sooner rather than later.

**Comment by denelon** [comment]
Yeah, we learned that lesson from our fully automated days after a wildly popular YouTube video 😊

**Pull request merged**
