### PR TITLE
Create WinGet package for March 2023 GDK Update 6

### PR DESCRIPTION
**Pull request by aaron-stebner**
Create WinGet package for March 2023 GDK Update 6

Tested locally with winget validate and winget install
 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/116352&drop=dogfoodAlpha

### CODE REVIEW

**Comment by aaron-stebner** [comment]
@microsoft/xbox-developer-experience-toolbox for review

**Comment by MattHyman** [comment]
> @microsoft/xbox-developer-experience-toolbox for review

LGTM.

**Comment by aaron-stebner** [comment]
The URL https://github.com/microsoft/GDK/archive/refs/tags/March_2023_Update_6.zip is correct and works fine for me.  There's nothing I need to fix here.

**Comment by aaron-stebner** [comment]
The URL https://github.com/microsoft/GDK/archive/refs/tags/March_2023_Update_6.zip is correct and works fine for me. There's nothing I need to fix here.

**Review by ItzLevvie — APPROVED** [review]

**Comment by aaron-stebner** [comment]
> Hello @aaron-stebner,
> 
> When processing this package, the URL to the installer returned a 404 error or was determined to be invalid.
> 
> Please update the URL and hash at your convenience and resubmit your PR.
> 
> Template: msftbot/validationError/urls/404

I don't understand why the bot is getting a 404.  The link at https://github.com/microsoft/GDK/archive/refs/tags/March_2023_Update_6.zip is live and works fine on my PCs.  That same zip is also linked at https://github.com/microsoft/GDK/tags and works fine from there too.

**Comment by aaron-stebner** [comment]
> This might be due to data center blocking to prevent automated downloads.
> 
> > 8/11/2023 5:27:31 PM
> > Installer Verification Analysis Context Information:
> > Error occurred while downloading installer from https://github.com/microsoft/GDK/archive/refs/tags/March_2023_Update_6.zip. 0x80072EE2.
> > Error information:
> > Http Response: OK
> > Http Reason Phrase: OK
> 
> Unfortunately, this isn't an error that I can waiver or easily get around. We might need to contact that team in some way, about this error.

What team would need to be contacted here?

This URL is the same name and formatting as every previous release that I've submitted WinGet packages for.  The URL is live, if you go to it manually it works fine.

Is there some new validation step happening that didn't happen for the previous PRs that I've submitted?

**Comment by denelon** [comment]
@aaron-stebner according to the manifest, this should work on Windows 10 & Windows 11. Is that correct?

@stephengillie does this pass manual validation?

**Comment by aaron-stebner** [comment]
> @aaron-stebner according to the manifest, this should work on Windows 10 & Windows 11. Is that correct?
> 
> @stephengillie does this pass manual validation?

Yes this works on Win10 and Win11. This package has the same settings as all of our previous submissions.

**Comment by stephengillie** [comment]
> @aaron-stebner according to the manifest, this should work on Windows 10 & Windows 11. Is that correct?
> 
> @stephengillie does this pass manual validation?

@denelon,

Sorry, I did not see this until this morning. Yes, it does pass Manual Validation.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
