### PR TITLE
New version: GitHub.GitLFS version 3.4.0

### LINKED ISSUE #62326: New versions of GitHub.GitLFS require Git for Windows
> ```
> 2022-05-27 05:16:28.466   Message box (OK):
   >                        Could not find Git; can not register Git LFS.
> ```
> from Azure Pipelines logs.
> It requires Git for Windows as a dependency now. Wasn't able to suppress it via `/SUPPRESSMSGBOXES` or `/VERYSILENT`

_Originally posted by @ItzLevvie in https://github.com/microsoft/winget-pkgs/issues/61992#issuecomment-1140137052_

Just wanted to note this as being blocked for dependencies.

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

* Resolves #62326

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/120907)

### CODE REVIEW

**Comment by mdanish-kh** [comment]
[Policy] reset feedback

**Comment by mdanish-kh** [comment]
[Policy] reset feedback

**Review by mdanish-kh — APPROVED** [review]

**Comment by Trenly** [comment]
@denelon 

image

I believe the error can be ignored since that is after the install completes and is part of the sandbox script trying to refresh the environment variables

**Review by denelon — APPROVED** [review]

**Pull request merged**
