### PR TITLE
Wolvenkit.WolvenKit.Installer version 0.2.0.0

### PR DESCRIPTION
**Pull request by rfuzzo**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/88879)

### CODE REVIEW

**Comment by mdanish-kh** [comment]
@MSFTbot Dependencies

**Comment by mdanish-kh** [comment]
For context, see https://github.com/microsoft/winget-pkgs/discussions/88963

**Review by ItzLevvie — DISMISSED** [review]

**Comment by stephengillie** [comment]
This package has `WindowsAppRuntime.1.2` as a dependency, and this is available through the MS Store as `9P7VS8XHG9G5`. But maybe MS Store packages don't work as dependencies - the logs end in this error:

```
2022-12-22 10:21:22.457 [CLI ] Manifest fields: Name [WindowsAppRuntime.1.2], Version [Unknown]
2022-12-22 10:21:22.491 [CLI ] Get user entitlement.
2022-12-22 10:21:22.497 [CLI ] Get device entitlement.
2022-12-22 10:21:22.854 [CLI ] Get entitlement succeeded. Server error. ProductId: 9P7VS8XHG9G5
2022-12-22 10:21:22.854 [CLI ] Terminating context: 0x8a15001e at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\MSStoreInstallerHandler.cpp:7a
2022-12-22 10:21:22.854 [CLI ] Terminating context: 0x8a150110 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:231
```

**Comment by stephengillie** [comment]
The `Microsoft.WindowsAppRuntime.1.2` package is now available through Winget. With the dependency above it installs successfully. But when running the installer, it gives this error:
image

So it appears that `Microsoft.DotNet.DesktopRuntime.6` is also a dependency. Currently we only support installing the first dependency:
* https://github.com/microsoft/winget-cli/issues/2202

**Comment by stephengillie** [comment]
Unfortunately, Winget is only able to install the first dependency at this time. This package can be made available through Winget only after Winget can install multiple dependencies.

**Comment by rfuzzo** [comment]
> Unfortunately, Winget is only able to install the first dependency at this time. This package can be made available through Winget only after Winget can install multiple dependencies.

Thank you for this information. Although, it seems it’s still failing on the WindowsApp runtime. Even though it is the first package dependency in the manifest. I assumed winget would install the first dependency, but it seems this is incorrect…

**Review by ItzLevvie — DISMISSED** [review]

**Pull request closed without merging**
