### PR TITLE
New version: Mozilla.Firefox version 122.0.1

### LINKED ISSUE #138209: [Update Request]: Mozilla Firefox 122.0.1
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Mozilla.Firefox

### Package Version

122.0.1

### Please describe the changes you would like to see

_No response_

### PR DESCRIPTION
**Pull request by Exorcism0666**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.0.3 :rocket:

- Resolve: https://github.com/microsoft/winget-pkgs/issues/138209

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/138246)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-07T10:24:05.1417544Z ##[error] One or more errors occurred. (Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Error: Duplicate installer entry found. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. ) Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Error: Duplicate installer entry found. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended. Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended.

(Automated response - build 695.)

**Comment by stephengillie** [comment]
> Manifest Error: Duplicate installer entry found

It appears that repeated errors need to be filtered out.

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

These installer entries appear to be duplicated. Could they be modified or removed? 
  
- cs-CZ-x64-exe-machine
- de-DE-x64-exe-machine
- el-GR-x64-exe-machine
- en-GB-x64-exe-machine
- en-US-x64-exe-machine
- es-MX-x64-exe-machine
- fr-FR-x64-exe-machine
- hu-HU-x64-exe-machine
- ja-JP-x64-exe-machine
- nb-NO-x64-exe-machine
- ru-RU-x64-exe-machine
- ta-IN-x64-exe-machine
- zh-CN-x64-exe-machine

**Comment by ItzLevvie** [comment]
Close with reason: Merge conflicts;

**Pull request closed without merging**
