### PR TITLE
New version: pit-ray.win-vind version 5.10.0

### PR DESCRIPTION
**Pull request by pit-ray**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/133983)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @pit-ray,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 570.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-14 14:31:06.997 [FAIL] Installer failed security check. Url: https://github.com/pit-ray/win-vind/releases/download/v5.10.0/setup_win-vind_5.10.0_32bit.exe Result: 0x80004005

(Automated response - build 570.)

**Comment by stephengillie** [comment]
> @ stephengillie Thanks for your help. I have no idea what to fix since we have not made any changes to the installation process. I received the same error in [5.0.1](https://github.com/microsoft/winget-pkgs/pull/101425).

This was just a false positive. Sorry for any concern caused.

**Review by stephengillie — APPROVED** [review]

**Comment by pit-ray** [comment]
@stephengillie 
Thank you for your generous support.

**Pull request merged**
