### PR TITLE
Remove unneccessary AppsandFeaturesEntries * manifests/g/Geph/Geph/4.8.5/Geph.Geph.installer.yaml

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/194217)

### CODE REVIEW

**Review by mdanish-kh — APPROVED** [review]

**Comment by Trenly** [comment]
```
--> Installing WinGet
--> Disabling safety warning when running installers
Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.

--> Configuring Winget
Enabled admin setting 'LocalManifestFiles'.
Enabled admin setting 'LocalArchiveMalwareScanOverride'.

--> Installing the Manifest 4.8.5

Found Geph [Geph.Geph] Version 4.8.5
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Packages
      Microsoft.EdgeWebView2Runtime
(1/1) Found Microsoft Edge WebView2 Runtime [Microsoft.EdgeWebView2Runtime] Version 131.0.2903.70
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/91530f73-1202-471b-86a9-a3b1d9655560/MicrosoftEdgeWebView2RuntimeInstallerX64.exe
  ██████████████████████████████   173 MB /  173 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Downloading https://f001.backblazeb2.com/file/geph4-dl/geph-releases/windows-stable/4.8.5/geph-windows-setup.exe
  ██████████████████████████████  12.9 MB / 12.9 MB
Successfully verified installer hash
Starting package install...
Successfully installed

--> Refreshing environment variables

--> Comparing ARP Entries

DisplayName           DisplayVersion Publisher  ProductCode                                Scope
-----------           -------------- ---------  -----------                                -----
Microsoft Edge Update 1.3.195.39                Microsoft Edge Update                      Machine
Geph version v4.8.5   v4.8.5         Gephyra OÜ {09220679-1AE0-43B6-A263-AAE2CC36B9E3}_is1 Machine
```

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 899)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 902)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 903)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 903)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 904)

**Pull request merged**
