### PR TITLE
Update version: twpayne.chezmoi version 2.34.0

### PR DESCRIPTION
**Pull request by twpayne**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/109011)

### CODE REVIEW

**Review by mdanish-kh — CHANGES_REQUESTED** [review]
Bad autogenerated PR?

**Comment by mdanish-kh** [comment]
cc @denelon Another bad approval by fabricbot similar to the one in https://github.com/microsoft/winget-pkgs/pull/107052. Both PRs are roughly the same in that they have `Files Changed: 0` and the `Unexpected-File` label

**Comment by denelon** [comment]
Thanks @mdanish-kh we're looking at how these are getting through the cracks. We've just gotten a new fabric bot configuration format so hopefully it will give us the ability to find/fix these quickly.

**Comment by twpayne** [comment]
Thanks for looking into this! A bit of context, in case it is helpful:

* The upstream software (https://github.com/twpayne/chezmoi) uses https://github.com/vedantmgoyal2009/winget-releaser to generate these PRs.
* The winget-releaser config used is https://github.com/twpayne/chezmoi/blob/006230cc05fc1fe017c942758ee92aee3058d9c5/.github/workflows/winget.yml.
* In this particular case, the initial run of winget-releaser failed: https://github.com/twpayne/chezmoi/actions/runs/5171912128/jobs/9315748879. It looks like it failed fairy late in the process, after the creation of https://github.com/microsoft/winget-pkgs/pull/108890.
* Seeing the failed winget-releaser job, I simply re-ran the failed job, which created this PR.

cc @vedantmgoyal2009 as author of winget-releaser for input.

**Comment by twpayne** [comment]
It looks like the issue in winget-releaser is already fixed: https://github.com/vedantmgoyal2009/winget-releaser/issues/167

So, it looks like the change to make fabric bot reject PRs like this one is the remaining task.

**Pull request closed without merging**
