### PR TITLE
LocktimeSoftware.NetLimiter4 version 4.1.11.0

### PR DESCRIPTION
**Pull request by krystofkrticka**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/20129)

### CODE REVIEW

**Comment by krystofkrticka** [comment]
Hopefully the failed validation is not caused by the CMD window which installer opens to install service.

**Comment by krystofkrticka** [comment]
Great it failed again and I don't now if it was once again error 1603 which I'm unable to reproduce in my VM.

**Comment by krystofkrticka** [comment]
@ItzLevvie Well automated testing once again failed probably on error 1603. So it looks like I have to contact Windows Package Manager team.

**Comment by krystofkrticka** [comment]
I'm adding here screen recording of successful installation on freshly installed VM.

https://user-images.githubusercontent.com/37749100/124811681-02671b00-df63-11eb-8fc1-19510d01aa66.mp4

**Comment by OfficialEsco** [comment]
Still failing in Sandbox with exit code 1603
```
--> Installing WinGet

                                                                                                                                                 Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.                                                                                                                                                                                                                                                                                                                     --> Installing the Manifest 4.1.11.0                                                                                                             
Found NetLimiter [LocktimeSoftware.NetLimiter4]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.netlimiter.com/files/download/nl4/netlimiter-4.1.11.0.exe
  ██████████████████████████████  7.19 MB / 7.19 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1603

--> Refreshing environment variables

PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs>
```

**Comment by krystofkrticka** [comment]
> Still failing in Sandbox with exit code 1603
> ```
> --> Installing WinGet
> 
>                                                                                                                                                  Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.                                                                                                                                                                                                                                                                                                                     --> Installing the Manifest 4.1.11.0                                                                                                             
> Found NetLimiter [LocktimeSoftware.NetLimiter4]
> This application is licensed to you by its owner.
> Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
> Downloading https://www.netlimiter.com/files/download/nl4/netlimiter-4.1.11.0.exe
>   ██████████████████████████████  7.19 MB / 7.19 MB
> Successfully verified installer hash
> Starting package install...
> Installer failed with exit code: 1603
> 
> --> Refreshing environment variables
> 
> PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs>
> ```

@OfficialEsco well it looks I have to install windows setbox and try it in it because in VMs I don't have this behavior.

**Comment by OfficialEsco** [comment]
> @OfficialEsco well it looks I have to install windows setbox and try it in it because in VMs I don't have this behavior.

Yeah for some reason Sandbox catches some of the bottom cases, however not all the time, i have no idea what the MS Team means by Clean VM when we also use bare bone VMs AND Sandbox where it still successes 🤷‍♂️

I've also found some programs which require certain devices to be connected (gets passed trough to VM), but this shouldn't the issue here..

Anyways i found the issue
Just tested the Exe in interactive mode to see if there was anything that could cause the issue, nothing, however it installed VC++2015-2019 x64 and x86, i then uninstalled NetLimiter but not the VC++2015-2019 and it successes
```
--> Installing WinGet

                                                                                                                                                 Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.                                                                                                                                                                                                                                                                                                                     PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget install -m .\manifests\l\LocktimeSoftware\NetLimiter4\4.1.11.0\                       Found NetLimiter [LocktimeSoftware.NetLimiter4]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.netlimiter.com/files/download/nl4/netlimiter-4.1.11.0.exe
  ██████████████████████████████  7.19 MB / 7.19 MB
Successfully verified installer hash
Starting package install...
Successfully installed
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs>
```

I then uninstalled NetLimiter and VC++2015-2019
```
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget install -m .\manifests\l\LocktimeSoftware\NetLimiter4\4.1.11.0\
Found NetLimiter [LocktimeSoftware.NetLimiter4]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.netlimiter.com/files/download/nl4/netlimiter-4.1.11.0.exe
  ██████████████████████████████  7.19 MB / 7.19 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1603
```

**Comment by krystofkrticka** [comment]
Well I didn't think of that that failed installation might be caused by not installed VC++ 2015-2019. I on website of app developer there is no information that it's dependent on VC++ 2015-2019.

**Comment by OfficialEsco** [comment]
> Well I didn't think of that that failed installation might be caused by not installed VC++ 2015-2019. I on website of app developer there is no information that it's dependent on VC++ 2015-2019.

Well you have the answer to this, is VC++2015-2019 x64 and x86 installed on your VM? Does it still work if you uninstall VC++2015-2019?
The EXE clearly installs VC++2015-2019 x64 and x86, it might not be dependent on it, but it probably tries to install it but fails.

**Comment by krystofkrticka** [comment]
VM in my screen recording is fresh VM from iso downloaded from Microsoft

**Comment by OfficialEsco** [comment]
> VM in my screen recording is fresh VM from iso downloaded from Microsoft

take a Screenshot of Control Panel before and after Install please =)

**Comment by krystofkrticka** [comment]
OK I'll do from my main computer after I come home after work.

**Comment by krystofkrticka** [comment]
@OfficialEsco Well I did fresh install of Windows 10 in VM and it looks like MS started to include VC++ 2015-2019 directly in Windows.

**Comment by OfficialEsco** [comment]
> @OfficialEsco Well I did fresh install of Windows 10 in VM and it looks like MS started to include VC++ 2015-2019 directly in Windows.

That most be a VMware thing, because VC++2015-2019 is never preinstalled on any of the PC's i've installed on, and my Virtualbox server with the same ISO also don't have VC++2015-2019

🤷‍♂️

**Comment by krystofkrticka** [comment]
> > @OfficialEsco Well I did fresh install of Windows 10 in VM and it looks like MS started to include VC++ 2015-2019 directly in Windows.
> 
> That most be a VMware thing, because VC++2015-2019 is never preinstalled on any of the PC's i've installed on, and my Virtualbox server with the same ISO also don't have VC++2015-2019
> 
> 🤷‍♂️

So probably VMware Tools did it

**Comment by krystofkrticka** [comment]
So that's probably why installation was successful. So yeah there is VC++ dependency.

**Comment by krystofkrticka** [comment]
@OfficialEsco You were right VC++ was installed by VMware Tools

**Comment by krystofkrticka** [comment]
So I installed manually netlimiter on VM without VMware tools so no VC++ and installer automatically downloaded VC++ so yeah all along it was caused by VC++ dependency. But I thought there aren't any because a always had it installed in my VM.

**Comment by krystofkrticka** [comment]
So thank you for your help because I would probably never notice that VMware Tools installs VC++ automatically.

**Comment by krystofkrticka** [comment]
@OfficialEsco Can you mark this PR that it's waiting for dependency support please?

**Comment by ItzLevvie** [comment]
You'll have to ask @denelon; wait until Monday or so.

**Comment by krystofkrticka** [comment]
> Please wait until Monday or so.

OK, no problem.

**Comment by krystofkrticka** [comment]
Well at least I tried to test if dependencies will work in insider version of winget. I'll probably change this PR to draft.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
You can set the PR to draft and wait until dependency support is added.

**Pull request closed without merging**
