### PR TITLE
New version: yt-dlp.yt-dlp.nightly version 2024.02.15.232705

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/139396)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 

(Automated response - build 751.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 

(Automated response - build 762.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  2024-02-20 18:17:16.341 [CLI ] Installer [X64,portable,Unknown,] not applicable: Machine is not compatible with X64 2024-02-20 18:17:16.359 [CLI ] Installer [X64,portable,Unknown,] not applicable: Machine is not compatible with X64 2024-02-20 18:17:16.376 [CLI ] Installer [X64,portable,Unknown,] not applicable: Machine is not compatible with X64 2024-02-20 18:17:16.453 [CLI ] Installer [X64,portable,Unknown,] not applicable: Machine is not compatible with X64 2024-02-20 18:17:16.547 [CLI ] Installer [X64,portable,Unknown,] not applicable: Machine is not compatible with X64 2024-02-20 18:17:16.619 [CLI ] Installer [X64,portable,Unknown,] not applicable: Machine is not compatible with X64 2024-02-20 18:17:16.696 [CLI ] Installer [X64,portable,Unknown,] not applicable: Machine is not compatible with X64 2024-02-20 18:17:16.787 [CLI ] Installer [X64,portable,Unknown,] not applicable: Machine is not compatible with X64 2024-02-20 18:17:16.787 [CLI ] Terminating context: 0x8a150010 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\UpdateFlow.cpp:b8 2024-02-20 18:17:22.330 [CLI ] Installer [X64,portable,Unknown,en-US] not applicable: Machine is not compatible with X64 2024-02-20 18:17:23.407 [CLI ] Installer [X64,portable,Unknown,] not applicable: Machine is not compatible with X64 2024-02-20 18:17:23.408 [CLI ] No suitable installer found for manifest Gyan.FFmpeg with version 6.1.1 2024-02-20 18:17:23.410 [CLI ] Terminating context: 0x8a150104 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DependenciesFlow.cpp:11a

(Automated response - build 796.)

**Comment by stephengillie** [comment]
Dependency mismatch: 

> 2024-02-20 18:17:23.408 [CLI ] No suitable installer found for manifest Gyan.FFmpeg with version 6.1.1

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
