### PR TITLE
New package: Dothq.DotBrowser version 87.0

### PR DESCRIPTION
**Pull request by OfficialEsco**
Fixes #15622
https://github.com/microsoft/winget-cli/issues/163

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

@denelon add blocking-issue and dependency

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/17524)

### CODE REVIEW

**Review by SandroLinux — APPROVED** [review]
Ok thanks for the changes!

**Review by SandroLinux — APPROVED** [review]
thanks that works!

**Comment by OfficialEsco** [comment]
> thanks that works!

It will stop for the bot tho since VC++2015-2019 have to be installed, so it cannot be added until Dependency's are added..

**Comment by SandroLinux** [comment]
> > thanks that works!
> 
> It will stop for the bot tho since VC++2015-2019 have to be installed, so it cannot be added until Dependency's are added..

ok

**Comment by OfficialEsco** [comment]
@denelon

**Comment by SandroLinux** [comment]
@officialesco So do I need to wait for this dependancy ?

**Comment by OfficialEsco** [comment]
> @OfficialEsco So do I need to wait for this dependancy ?

You can close your PR and ill wait for the dependency

**Comment by SandroLinux** [comment]
> > @OfficialEsco So do I need to wait for this dependancy ?
> 
> You can close your PR and ill wait for the dependency

ok

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
image

From Validation
```log
Checking if C:\Program Files\Dot Browser\crashreporter.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\crashreporter.exe
Executable C:\Program Files\Dot Browser\crashreporter.exe ran for less than 10 seconds: False
Executable C:\Program Files\Dot Browser\crashreporter.exe returned exit code: -1
Checking if C:\Program Files\Dot Browser\default-browser-agent.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\default-browser-agent.exe
Executable C:\Program Files\Dot Browser\default-browser-agent.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\default-browser-agent.exe returned exit code: -2147024809
Checking if C:\Program Files\Dot Browser\dot.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\dot.exe
Executable C:\Program Files\Dot Browser\dot.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\dot.exe returned exit code: 0
Checking if C:\Program Files\Dot Browser\maintenanceservice.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\maintenanceservice.exe
Executable C:\Program Files\Dot Browser\maintenanceservice.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\maintenanceservice.exe returned exit code: 0
Checking if C:\Program Files\Dot Browser\maintenanceservice_installer.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\maintenanceservice_installer.exe
Executable C:\Program Files\Dot Browser\maintenanceservice_installer.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\maintenanceservice_installer.exe returned exit code: 0
Checking if C:\Program Files\Dot Browser\minidump-analyzer.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\minidump-analyzer.exe
Executable C:\Program Files\Dot Browser\minidump-analyzer.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\minidump-analyzer.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\pingsender.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\pingsender.exe
Executable C:\Program Files\Dot Browser\pingsender.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\pingsender.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\plugin-container.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\plugin-container.exe
Executable C:\Program Files\Dot Browser\plugin-container.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\plugin-container.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\plugin-hang-ui.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\plugin-hang-ui.exe
Executable C:\Program Files\Dot Browser\plugin-hang-ui.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\plugin-hang-ui.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\updater.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\updater.exe
Executable C:\Program Files\Dot Browser\updater.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\updater.exe returned exit code: 1
Checking if C:\Program Files (x86)\Mozilla Maintenance Service\maintenanceservice.exe executable file can be started.
Launching executable file: C:\Program Files (x86)\Mozilla Maintenance Service\maintenanceservice.exe
Executable C:\Program Files (x86)\Mozilla Maintenance Service\maintenanceservice.exe ran for less than 10 seconds: True
Executable C:\Program Files (x86)\Mozilla Maintenance Service\maintenanceservice.exe returned exit code: 0
Checking if C:\Program Files\Dot Browser\default-browser-agent.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\default-browser-agent.exe
Executable C:\Program Files\Dot Browser\default-browser-agent.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\default-browser-agent.exe returned exit code: -2147024809
Checking if C:\Program Files\Dot Browser\minidump-analyzer.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\minidump-analyzer.exe
Executable C:\Program Files\Dot Browser\minidump-analyzer.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\minidump-analyzer.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\pingsender.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\pingsender.exe
Executable C:\Program Files\Dot Browser\pingsender.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\pingsender.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\plugin-container.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\plugin-container.exe
Executable C:\Program Files\Dot Browser\plugin-container.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\plugin-container.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\plugin-hang-ui.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\plugin-hang-ui.exe
Executable C:\Program Files\Dot Browser\plugin-hang-ui.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\plugin-hang-ui.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\updater.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\updater.exe
Executable C:\Program Files\Dot Browser\updater.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\updater.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\default-browser-agent.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\default-browser-agent.exe
Executable C:\Program Files\Dot Browser\default-browser-agent.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\default-browser-agent.exe returned exit code: -2147024809
Checking if C:\Program Files\Dot Browser\minidump-analyzer.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\minidump-analyzer.exe
Executable C:\Program Files\Dot Browser\minidump-analyzer.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\minidump-analyzer.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\pingsender.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\pingsender.exe
Executable C:\Program Files\Dot Browser\pingsender.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\pingsender.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\plugin-container.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\plugin-container.exe
Executable C:\Program Files\Dot Browser\plugin-container.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\plugin-container.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\plugin-hang-ui.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\plugin-hang-ui.exe
Executable C:\Program Files\Dot Browser\plugin-hang-ui.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\plugin-hang-ui.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\updater.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\updater.exe
Executable C:\Program Files\Dot Browser\updater.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\updater.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\default-browser-agent.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\default-browser-agent.exe
Executable C:\Program Files\Dot Browser\default-browser-agent.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\default-browser-agent.exe returned exit code: -2147024809
Checking if C:\Program Files\Dot Browser\minidump-analyzer.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\minidump-analyzer.exe
Executable C:\Program Files\Dot Browser\minidump-analyzer.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\minidump-analyzer.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\pingsender.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\pingsender.exe
Executable C:\Program Files\Dot Browser\pingsender.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\pingsender.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\plugin-container.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\plugin-container.exe
Executable C:\Program Files\Dot Browser\plugin-container.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\plugin-container.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\plugin-hang-ui.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\plugin-hang-ui.exe
Executable C:\Program Files\Dot Browser\plugin-hang-ui.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\plugin-hang-ui.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\updater.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\updater.exe
Executable C:\Program Files\Dot Browser\updater.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\updater.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\default-browser-agent.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\default-browser-agent.exe
Executable C:\Program Files\Dot Browser\default-browser-agent.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\default-browser-agent.exe returned exit code: -2147024809
Checking if C:\Program Files\Dot Browser\minidump-analyzer.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\minidump-analyzer.exe
Executable C:\Program Files\Dot Browser\minidump-analyzer.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\minidump-analyzer.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\pingsender.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\pingsender.exe
Executable C:\Program Files\Dot Browser\pingsender.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\pingsender.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\plugin-container.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\plugin-container.exe
Executable C:\Program Files\Dot Browser\plugin-container.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\plugin-container.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\plugin-hang-ui.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\plugin-hang-ui.exe
Executable C:\Program Files\Dot Browser\plugin-hang-ui.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\plugin-hang-ui.exe returned exit code: 1
Checking if C:\Program Files\Dot Browser\updater.exe executable file can be started.
Launching executable file: C:\Program Files\Dot Browser\updater.exe
Executable C:\Program Files\Dot Browser\updater.exe ran for less than 10 seconds: True
Executable C:\Program Files\Dot Browser\updater.exe returned exit code: 1
```

**Comment by denelon** [comment]
@stephengillie any ideas on this one?

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
