### PR TITLE
New version: MartiCliment.UniGetUI version 3.1.3

### PR DESCRIPTION
**Pull request by marticliment**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/186052)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by marticliment** [comment]
The installer works for me. I can't see why it fails validation.

Azure pipelines don't provide any details on what the issue is. Those are the provided logs: https://dev.azure.com/shine-oss/8b78618a-7973-49d8-9174-4360829d979b/_apis/build/builds/19421/logs/54

**Comment by marticliment** [comment]
The installer works for me. I can't see why it fails validation.

Azure pipelines don't provide any details on what the issue is. Those are the provided logs: https://dev.azure.com/shine-oss/8b78618a-7973-49d8-9174-4360829d979b/_apis/build/builds/19759/logs/54

**Review by ItzLevvie — APPROVED** [review]

**Comment by marticliment** [comment]
Still failing, any idea why it could be failing?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335146

Automated error analysis suggests -1978335146 may mean The installer cannot be run from an administrator context - does this package require `ElevationRequirement: elevationProhibited`? 

(Automated response - build 897.)

**Comment by marticliment** [comment]
elevationProhibited is already there for the user entry, and elevationRequired is set for machine installer

**Comment by stephengillie** [comment]
It's unexpected that the pipeline would reach this error. I coudln't reproduce it in a VM.

**Pull request merged**
