### PR TITLE
UniversityofLjubljana.Orange version 3.29.3

### PR DESCRIPTION
**Pull request by quhxl**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/19763)

### CODE REVIEW

**Comment by quhxl** [comment]
Can't find the error in the manifest. 🤔

**Comment by quhxl** [comment]
@OfficialEsco Any ideas? The installation works fine for me in the VM and in the sandbox.

**Comment by OfficialEsco** [comment]
```
Manifest: The filename must match the PackageIdentifier and ManifestType properties from the manifest. 
actual 'UniversityofLjubljana.locale.en-US.yaml', 
expected 'UniversityofLjubljana.Orange.locale.en-US.yaml'
```
Missing `.Orange.`

**Comment by quhxl** [comment]
> 
> 
> ```
> Manifest: The filename must match the PackageIdentifier and ManifestType properties from the manifest. 
> actual 'UniversityofLjubljana.locale.en-US.yaml', 
> expected 'UniversityofLjubljana.Orange.locale.en-US.yaml'
> ```
> 
> Missing `.Orange.`

Thank you! Where did you get this exact description? Because to find the error is really hard...

**Comment by OfficialEsco** [comment]
[Checks](https://github.com/microsoft/winget-pkgs/pull/19763/checks) -> [View more details on Azure Pipelines](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=188415&view=results)

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
