### PR TITLE
New package: keif888.SSISMHash version 1.7.6.0

### LINKED ISSUE #137398: [Package Request]: keif888.SSISMHash
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/keif888/SSISMHash/releases/tag/v1.7.6.0
Publisher: [keif888](https://github.com/keif888)
Package Name: SSISMHash
Description: SSIS Multiple Hash makes it possible to generate many Hash values from each input row. Hash's supported include MD5 and SHA1.
Package Version: 1.7.6.0
Installer URL: https://github.com/keif888/SSISMHash/releases/download/v1.7.6.0/MultipleHashInstallerx64.msi

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

- Resolves #137398

### CODE REVIEW

**Comment by moomoomafia** [comment]
Oh this is sweet. Sorry. I just created my first manifest (didn't publish), validated it, and installed it based on the documentation on [this site](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#creating-your-manifest-with-winget-create). I only fairly recently found winget, and only today learned that THIS was possible.

**Comment by stephengillie** [comment]
Hi @moomoomafia and @drshtmstry,

This package appears to be like a plugin for Microsoft SQL Server. The [wiki page](https://github.com/keif888/SSISMHash/wiki) says to reinstall the program if you add a new version of SQL, as it detects installed versions. The installer log reflects this, showing the various folders:
image

What happens if there is no version of Microsoft SQL Server installed? 

Unfortunately, SQL Server doesn't have a manifest among our public manifests yet, and licensing might complicate adding one - so we can't easily test using it as a dependency. This is normally fine, and I could validate that the files were installed. I tried creating empty folders to mimic the 2019 version, but this also yielded no installed files. 

The goal we're working to meet is to have the installer place files on the file system which can receive a Defender scan. Is there an installer switch to force installing a specific version, or something similar?

**Comment by stephengillie** [comment]
This application doesn't directly modify the system much. Evidence of install:

Apps and Features entry :
Apps and Features entry for Multiple Hash x64

MultipleHash2019.dll:
Windows Explorer showing MultipleHash2019.dll under DTS slash PipelineComponents

SSISMhash.xml and SSISMHash.extension.xml:
Windows Explorer showing SSISMhash.xml and SSISMHash.extension.xml under DTS slash UpgradeMappings

**Comment by stephengillie** [comment]
This package needs *any* edition of SQL Server for the installer to detect. But specifying any one version would force that version to become installed, regardless of other versions. In this way, the package is very similar to packages which depend on any edition of Git. 

I'll approve this manifest. If the WinGet Package Manager gains the functionality to specify any edition in the future, then this manifest should be updated to have any version of SQL as a dependency.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
