### PR TITLE
New version: Kitware.CMake version 3.29.0-rc1

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/139161)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by Carbenium** [comment]
@Exorcism0666 @stephengillie 
This is a release candidate and not a stable version of CMake which is now offered as an update. I'm pretty sure this shouldn't be the case.
Would you consider a revert or is there some reasoning behind this change? Thanks!

**Comment by exoosh** [comment]
@Carbenium thank you! **Exactly** this is why I came here to search for this PR. This is _really bad form_ smuggling a pre-release version into such a widely used tool as `winget` -- even if it is a _release candidate_.

Create a new manifest under a new product name, instead. Other products have created numerous precedents, for example: `manifests/a/ArduinoSA/IDE/rc`, `manifests/d/Dapr/CLI/Preview`, `manifests/l/LinwoodCloud/Butterfly/Nightly`, `manifests/o/OBSProject/OBSStudio/Pre-release`, `manifests/p/Prusa3D/PrusaSlicer/Alpha`, `manifests/o/OpenTofu/Tofu/RC` as well as a number of beta versions:

```
$ find -type d -iname 'beta'
./manifests/a/AdGuard/AdGuardVPN/Beta
./manifests/a/AgileBits/1Password/Beta
./manifests/a/AprelTech/SilentInstallBuilder/Beta
./manifests/a/ArduinoSA/IDE/beta
./manifests/b/BitSum/ProcessLasso/Beta
./manifests/b/bozbez/WinCaptureAudio/beta
./manifests/b/Brave/Brave/Beta
./manifests/c/ClipTeam/ClipCC/Beta
./manifests/c/Coq/CoqPlatform/Beta
./manifests/c/CozyCloud/CozyDrive/Beta
./manifests/f/FeePerfect/Feem/Beta
./manifests/f/Ferdium/Ferdium/Beta
./manifests/g/Getscreenme/Dashboard/Beta
./manifests/g/GitHub/Atom/Beta
./manifests/g/GitHub/GitHubDesktop/Beta
./manifests/g/Google/AndroidStudio/Beta
./manifests/g/Google/Chrome/Beta
./manifests/g/Google/PlayGames/Beta
./manifests/h/Hashicorp/Terraform/Beta
./manifests/h/Hiddify/Next/Beta
./manifests/i/i2p/firefox/beta
./manifests/i/Intel/PresentMon/Beta
./manifests/i/InTheLoop/LoopEmail/Beta
./manifests/k/Kuro/Mery/Beta
./manifests/m/Microsoft/Edge/Beta
./manifests/m/Microsoft/OpenSSH/Beta
./manifests/n/NetEase/CloudMusic/Beta
./manifests/o/OpenTofu/Tofu/Beta
./manifests/o/OpenWhisperSystems/Signal/Beta
./manifests/o/Opera/Opera/Beta
./manifests/p/PicGo/PicGo/Beta
./manifests/p/Premake/Premake/5/Beta
./manifests/r/RandomEngy/VidCoder/Beta
./manifests/r/rickbutton/workspacer/beta
./manifests/s/SFLinux/Jami/Beta
./manifests/s/SlackTechnologies/Slack/Beta
./manifests/s/stakira/OpenUTAU/Beta
./manifests/s/StarfaceGmbH/StarfaceUCC/Beta
./manifests/s/stnkl/EverythingToolbar/Beta
./manifests/s/subhra74/XtremeDownloadManager/Beta
./manifests/t/TeamSpeakSystems/TeamSpeakClient/Beta
./manifests/t/Telegram/TelegramDesktop/Beta
./manifests/t/thomasnordquist/MQTT-Explorer/Beta
./manifests/w/WeMod/WeMod/Beta
./manifests/w/WhatsApp/WhatsApp/Beta
./manifests/w/WinMerge/WinMerge/Beta
./manifests/w/WowUp/Beta
./manifests/y/YutakaSawada/MultiPar/Beta
./manifests/z/Zettlr/Zettlr/Beta
```

**Comment by Carbenium** [comment]
I've created now a PR reverting this change: #140344.

**Comment by denelon** [comment]
@exoosh we don't necessarily know all software and their release mechanisms/cadences. That's exactly why there is so much value in having this repository open-source. We do try to ensure packages install and upgrade correctly, but there are cases like this where the community knows more than we do.

Thank you so much for "seeing something" and "saying something"!

**Comment by exoosh** [comment]
> @exoosh we don't necessarily know all software and their release mechanisms/cadences. That's exactly why there is so much value in having this repository open-source. We do try to ensure packages install and upgrade correctly, but there are cases like this where the community knows more than we do.
> 
> Thank you so much for "seeing something" and "saying something"!

Hey @denelon, thanks for the response. My question was more about whether you have guidance regarding how to deal with betas or other pre-release versions (I gave some examples how other manifests treat those). The reason I ask is because _with_ such guidance one could point to the guide. I'm not suggesting that you folks should know the modus operandi for each and every piece of software with a manifest. Sorry if that wasn't clear.

**Comment by denelon** [comment]
@exoosh, ah... That makes sense. @stephengillie what do you think about updating the guidance/policy stuff so it can be linked to?

**Comment by stephengillie** [comment]
Sounds like a plan.

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/pull/141399

**Pull request merged**
