### PR TITLE
New version: Bilibili.Livehime version 4.13.0.2923

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/41637)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
@SpecterShell i can't copy these damn patch notes >_>

**Comment by SpecterShell** [comment]
https://api.live.bilibili.com/client/v1/LiveHime/getVerList?type=3

**Comment by OfficialEsco** [comment]
> https://api.live.bilibili.com/client/v1/LiveHime/getVerList?type=3

I just used Microsoft Edge's Web Capture tool instead, hopefully its correct?

**Comment by SpecterShell** [comment]
> > [api.live.bilibili.com/client/v1/LiveHime/getVerList?type=3](https://api.live.bilibili.com/client/v1/LiveHime/getVerList?type=3)
> 
> I just used Microsoft Edge's Web select tool instead, hopefully its correct?

It is much better than selecting text in DevTools. Thanks for mentioning that.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
