### PR TITLE
Normalize TTKN.CNKIExpress 0.1.14

### PR DESCRIPTION
**Pull request by Trenly**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/76453)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by vedantmgoyal9 — CHANGES_REQUESTED** [review]
* Duplicate of https://github.com/microsoft/winget-pkgs/pull/74600

**Comment by Trenly** [comment]
Removing Needs-Author-Feedback

**Review by jedieaston — APPROVED** [review]

**Review by jedieaston — APPROVED** [review]

**Review by ImJoakim — APPROVED** [review]

**Pull request merged**
