### PR TITLE
Remove version: OpenJS.NodeJS.LTS version 20.11.1

### PR DESCRIPTION
**Pull request by CoolPlayLin**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/143386)

### CODE REVIEW

**Review by mdanish-kh — CHANGES_REQUESTED** [review]
I don't quite get the reason, @CoolPlayLin can you please elaborate why would you like these manifests removed?

**Comment by mdanish-kh** [comment]
> I don't quite get the reason, @CoolPlayLin can you please elaborate why would you like these manifests removed?

I see, the other PRs you're referring are these ones:

- https://github.com/microsoft/winget-pkgs/pulls?q=is%3Aopen+is%3Apr+author%3Acoolplaylinbot+OpenJS

I don't agree with these changes, why would you want to prepend `v` in the version and use `DisplayVersion` field? The version written by the NodeJS installer exactly matches the current PackageVersions in the repo. I don't see a need for this change

Also, mass modifications should really be discussed in an issue first, so that it's easier to request changes and get to a consensus

**Comment by mdanish-kh** [comment]
https://www.github.com/microsoft/winget-pkgs/pull/143386#issuecomment-1986949152 [Policy] Needs-Author-Feedback

**Comment by CoolPlayLin** [comment]
@mdanish-kh This change can better distinguish this from OpenJS.NodeJS

**Comment by mdanish-kh** [comment]
@CoolPlayLin Unfortunately, these changes won't help in distinguishing the packages better. WinGet would still use DisplayVersion internally for package matching, and the matching would remain the same as before. Having DisplayVersion will introduce an additional version layer that is unnecessary, and it'll bring more churn in updating the manifests. In addition, if someone misses adding DisplayVersion in the newer manifest, this can cause issues like upgrade loop scenarios. I think the current state of the manifests is good, and doesn't need changing

**Comment by mdanish-kh** [comment]
Close with reason: Changes not needed, see discussion above;

**Pull request closed without merging**
