### PR TITLE
Delete manifests/r/RussellBanks/Komac/Nightly/.validation

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
No versions are present under the package id. 
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/142683)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 861)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 867)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 869)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 869)

**Review by denelon — APPROVED** [review]

**Pull request merged**
