### PR TITLE
Add Scope and ElevationRequirement filips.FirefoxPWA

### LINKED ISSUE #103815: [Package Issue]: filips.FirefoxPWA
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The `filips.FirefoxPWA` cannot be installed in a user scope, despite the installer having the ability to choose the installation scope.

The installer is built with WiX, its source is [here](https://github.com/filips123/PWAsForFirefox/blob/main/native/packages/wix/main.wxs). It is configured to allow users to choose if they want to install the package per machine or per user. Maybe there is some way to tell `winget` that it allows that and to configure it automatically based on the provided scope argument?

### Steps to reproduce

```sh
winget install --scope user firefoxpwa
```

### Actual behavior

The package cannot be installed per user:

```
No applicable installer found; see logs for more details.
```

### Expected behavior

The package should be installed per user.

### Environment

```raw
Windows Package Manager (Preview) v1.5.1081-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.918
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.20.1081.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

### Screenshots and Logs

[WinGet-2023-04-28-11-59-14.479.log](https://github.com/microsoft/winget-pkgs/files/11356545/WinGet-2023-04-28-11-59-14.479.log)

### PR DESCRIPTION
**Pull request by BrandonWanHuanSheng**
Testing Azure Pipelines. Resolves #103815

-----------

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/103854)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
> Hello @BrandonWanHuanSheng,
> 
> During installation testing, this application failed to install without user input. Did you forget to add Silent or SilentWithProgress switches?
> 
> This can also happen when a dependency is missing. You can test with https://github.com/microsoft/winget-pkgs#test-your-manifest.
> 
> Please investigate a fix and resubmit the Pull Request.
> 
> You may also try using the [Windows Package Manager Manifest Creator](https://github.com/microsoft/winget-create) to determine the proper installer type. If the installer type is MSIX, MSI, or a known installer technology like NullSoft, Inno, etc. the wingetcreate tool can detect them and the winget client will know what switches to pass. If it's a .exe installer of an unknown type, you will need to search to determine the proper switches for Silent and SilentWithProgress.
> 
> Template: msftbot/validationError/installation/unattended

Seeing that option /v is missing from msiexec.exe

**Comment by filips123** [comment]
Thanks for this PR! I don't know why that validation error happens, but it was fine before, so there is probably some problem with those switches?

I also have a question. If the user hasn't specified the scope explicitly and hasn't set anything in settings, in which scope will the package be installed? Is it possible to install it in a machine scope by default, as this is also the scope that is used by default in a normal installation?

**Comment by BrandonWanHuanSheng** [comment]
> Thanks for this PR! I don't know why that validation error happens, but it was fine before, so there is probably some problem with those switches?
> 
> I also have a question. If the user hasn't specified the scope explicitly and hasn't set anything in settings, in which scope will the package be installed? Is it possible to install it in a machine scope by default, as this is also the scope that is used by default in a normal installation?

Default is scope: machine

**Comment by BrandonWanHuanSheng** [comment]
It look like something was incomplete.

**Comment by BrandonWanHuanSheng** [comment]
I converted to draft.

**Comment by BrandonWanHuanSheng** [comment]
Checking if two places error. This is commonly that could be Windows 10 x64 or Windows 10 x86 reported it.

**Comment by BrandonWanHuanSheng** [comment]
I am going to investigating this pipelines issue.

**Comment by BrandonWanHuanSheng** [comment]
This one is most likely the final confirmed.

**Comment by BrandonWanHuanSheng** [comment]
The pipelines was successfully fixed.

**Comment by BrandonWanHuanSheng** [comment]
@filips123 It look like the issue was resolved.

**Comment by filips123** [comment]
I tested this locally with `winget install --manifest`. Although the installation in a user scope now works, it seems that this is the default option, instead of the machine scope...

This causes problems when the user has older version installed in a machine scope and then updates to the newer version, where user scope is the default. In my example, I had PWAsForFirefox installed in a machine scope, and then installed this new version, which got installed in a user scope. However, the old installation has remained, so now I have two versions, one per machine and one per user:

slika

**Comment by BrandonWanHuanSheng** [comment]
But the upgradeBehaviour seem like it make sense for me.

**Comment by BrandonWanHuanSheng** [comment]
> I tested this locally with `winget install --manifest`. Although the installation in a user scope now works, it seems that this is the default option, instead of the machine scope...
> 
> This causes problems when the user has older version installed in a machine scope and then updates to the newer version, where user scope is the default. In my example, I had PWAsForFirefox installed in a machine scope, and then installed this new version, which got installed in a user scope. However, the old installation has remained, so now I have two versions, one per machine and one per user:
> 
> slika

I already set the manifests to UpgradeBehaviour: uninstallPrevious

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
