### PR TITLE
Add ARM64 installer for `AdGuard.dnsproxy`

### PR DESCRIPTION
**Pull request by rakleed**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141418)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\dnsproxy.exe returned exit code: 1
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\dnsproxy.exe returned exit code: 1

(Automated response - build 855.)

**Comment by rakleed** [comment]
Same as https://github.com/microsoft/winget-pkgs/pull/141022#issuecomment-1965312305

**Review by stephengillie — APPROVED** [review]

**Comment by rakleed** [comment]
@stephengillie but this is a console program, which is also portable. Why should it return any code at all?

**Comment by stephengillie** [comment]
Every application returns an exit code when it exits. By default, this is 0. You can see the exit code for an application by running it in this way, and then closing it normally: 

```PowerShell
(Start-Process C:\path\to\app.exe -wait -PassThru).ExitCode
```

**Pull request merged**
