### PR TITLE
Remove version: gnome.Dia version 0.97.2

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/196462)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://sourceforge.net/projects/dia-installer/files/dia-win32-installer/0.97.2/dia-setup-0.97.2-2-unsigned.exe/download 
OK

(Automated message - build 923)

**Comment by stephengillie** [comment]
URL: https://sourceforge.net/projects/dia-installer/files/dia-win32-installer/0.97.2/dia-setup-0.97.2-2-unsigned.exe/download 
OK

(Automated message - build 923)

**Comment by stephengillie** [comment]
URL: https://sourceforge.net/projects/dia-installer/files/dia-win32-installer/0.97.2/dia-setup-0.97.2-2-unsigned.exe/download 
Status Code: 200

(Automated message - build 900)

**Comment by ItzLevvie** [comment]
Close with reason: URL works;

**Pull request closed without merging**
