### PR TITLE
New version: GnuPG.GnuPG version 2.5.0

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#6374](https://github.com/SpecterShell/Dumplings/actions/runs/9812063496).

<details>

<summary>Log</summary>

````
Updated: 2.4.5 → 2.5.0
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161690)

### CODE REVIEW

**Review by Trenly — APPROVED** [review]

**Comment by R-Adrian** [comment]
GnuPG 2.5.0 is a beta/test version... not a stable one.
Anything in the 2.5.x series is a test version... as a result of this commit WinGet now upgrades stable versions of GnuPG 2.4.5 to the 2.5.0 test version.
see https://lists.gnupg.org/pipermail/gnupg-announce/2024q3/000484.html

**When eventually released, stable versions will have a 2.6.x version number**

**Pull request merged**
