### PR TITLE
Rafelrojas patch 1

### PR DESCRIPTION
**Pull request by rafelrojas**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/81495)

### CODE REVIEW

**Comment by rafelrojas** [comment]
> @microsoft-github-policy-service agree company="RED Abierta"

**Comment by rafelrojas** [comment]
> @rafelrojas please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree company="RES Abierta"

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
`LICENSE` file need to be reverted to the one in the repository as that's the winget-pkgs' `LICENSE` file.

Only the `.YAML` files in `manifests/r/REDAbierta/URANOSSoftphone/3.21.3` should be in this PR.

**Comment by ItzLevvie** [comment]
Close with reason: Replaced by PR 81548;

**Pull request closed without merging**
