### PR TITLE
add rust-msvc-1.43.1

### PR DESCRIPTION
**Pull request by CGQAQ**
add rust-msvc-1.43.1(latest version)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1102)

### CODE REVIEW

**Comment by CGQAQ** [comment]
[submission](https://www.microsoft.com/en-us/wdsi/submission/20f06938-0fe4-4a84-8b3c-65126f1d6e47)

**Comment by JeremiSharkboy** [comment]
[submission](https://www.microsoft.com/en-us/wdsi/submission/bd083053-a232-4f7e-b4eb-b9ae3d5583c5)

**Comment by CGQAQ** [comment]
@KevinLaMS it's Mozilla Rustlang official binary, should be ok?

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
