### PR TITLE
Update TeamViewer to 15.9.4 + silent

### PR DESCRIPTION
**Pull request by auanasgheps**
Update TeamViewer to 15.9.4 + make the installation silent

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3256)

### CODE REVIEW

**Comment by auanasgheps** [comment]
The hash is correct. I have re-downloaded the package and I get
`81339C07FACE06056AB3BBD3326F5BF9F6C5A637F9305D2DF9FC84C8BFBB1D86`

**Comment by auanasgheps** [comment]
It worked fine on my machine. Please let me know if you need action from my side.

**Comment by yigitemres** [comment]
@auanasgheps Can confirm, your hash is correct. 

```
┌[yigitemres]
└[~\Desktop]> winget hash .\TeamViewer_Setup.exe
Sha256: 81339c07face06056ab3bbd3326f5bf9f6c5a637f9305d2df9fc84c8bfbb1d86
```

**Comment by luislavena** [comment]
Perhaps the URL is causing that?

`https://download.teamviewer.com/download/version_15x/TeamViewer_Setup.exe` returns 302 response to `https://dl.teamviewer.com/download/version_15x/TeamViewer_Setup.exe`, which has the final binary, matching the Sha256 provided.

Cheers.

**Comment by auanasgheps** [comment]
@luislavena thanks for the great heads up. I am commiting this change, tested in a VM works perfectly.

**Review by auanasgheps — COMMENTED** [review]
Update URL to avoid mismatch

**Comment by auanasgheps** [comment]
The bot is still failing with the updated URL, but the SHA-256 is right as outline above. Someone should review this manually, thanks.

**Comment by OfficialEsco** [comment]
I was gonna say we don't need to make a new manifest for Teamviewer15 since it uses the same url, but after reading the comments i decided to trace https://download.teamviewer.com/download/TeamViewer_Setup.exe via https://wheregoes.com/retracer.php

By looking at the traces it seems like https://dl.teamviewer.com/download/version_15x/Jmp-91/TeamViewer_Setup.exe is the specific version url, but the hash for that installer is 55c952edd08ab920dbc50ae7eac6476c0bf54dd51f4b4aa42edfa65c1a19ff11

**Review by auanasgheps — COMMENTED** [review]
Another URL update

**Comment by OfficialEsco** [comment]
Did the link work for you? I tried to submit TeamViewer Host over at #3303 but Kevin couldn't reach the page..

**Comment by auanasgheps** [comment]
@OfficialEsco thanks, your recommendations have worked.

**Comment by auanasgheps** [comment]
@OfficialEsco well the bot has approved the changes with the link you have provided. Waiting on human confirmation.

**Comment by auanasgheps** [comment]
Can you please motivate the installation error? I have tested this YAML once again and works.

**Comment by OfficialEsco** [comment]
Ok now that 15.10.5 is out i can see that https://dl.teamviewer.com/download/version_15x/Jmp-91/TeamViewer_Setup.exe is not infact the direct download link.

I think we should have a manifest named teamviewer15 used as latest version unless TeamViewer wants to give us the direct link to the downloader.

**Comment by auanasgheps** [comment]
This will likely happen in the future, I have raised the question already, but as of now I think we have to keep updating it.

**Comment by auanasgheps** [comment]
Closing, not needed anymore.

**Pull request closed without merging**
