### PR TITLE
New version: therealpaulgg.ssh-sync version v0.3.8

### PR DESCRIPTION
**Pull request by therealpaulgg**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/145829)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @therealpaulgg,

We have a limit of 1 manifest change, addition, or removal per PR. This PR modifies more than one PR. Can these changes be spread across multiple PRs?

(Automated response - build 871.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-03-21T15:31:08.1939843Z ##[error] One or more errors occurred. (The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.) The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.

(Automated response - build 871.)

**Comment by therealpaulgg** [comment]
> Hi @therealpaulgg,
> 
> We have a limit of 1 manifest change, addition, or removal per PR. This PR modifies more than one PR. Can these changes be spread across multiple PRs?
> 
> (Automated response - build 871.)
> 
> Edit: Adding the `v` to `0.3.7` alongside adding `v0.3.8`. Could one of these be moved to another PR?

Yeah that's fine, I will remove the v0.3.7 changes and do a new PR.

**Comment by therealpaulgg** [comment]
PR to address the version change is here. https://github.com/microsoft/winget-pkgs/pull/145840 Thanks!

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
