### PR TITLE
New version: Elgato.WaveLink version 1.9.0.1846

### PR DESCRIPTION
**Pull request by krystofkrticka**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`? image
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135533)

### CODE REVIEW

**Comment by krystofkrticka** [comment]
It installs correctly for me, it just needs reboot of the PC on which it was installed.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978334967 2024-01-19 13:05:47.029 [CLI ] ShellExecute installer failed: 3010 CAQuietExec:  Error 0x80070001: Command line returned an error. CAQuietExec:  Error 0x80070001: QuietExec Failed CAQuietExec:  Error 0x80070001: Failed in ExecCommon method CustomAction ClearFirewall returned actual error code 1603 but will be translated to success due to continue marking Property(S): DRIVERINSTALLFAILED_MESSAGE = Driver installation failed. Please reboot and start setup again. Property(S): DRIVERINSTALLFAILED_AUTO_MESSAGE = Driver installation failed. Please reboot and Setup will be started again. Property(S): ErrorDialog = ErrorDlg Property(S): SecureCustomProperties = DELETE_APPDATA_FILES_ACCEPTED_VALUE;DRIVERINSTALLFAILED_AUTO_MESSAGE;DRIVERINSTALLFAILED_MESSAGE;EXE_FILE_NAME;INSTALLDIR_PRODUCT_FAKE;INSTALLER_FILE_NAME;IS_DRIVER_UP_TO_DATE;IS_ELGATO_WAVE_DEVICE_CONNECTED;KEEP_SETTINGS_ALERT_MESSAGE;NETFRAMEWORK45;NEW_FIRMWARE_VERSION;OLD_COMP_PATH;OLDER_VERSION_DELETING_REGISTRY_APPDATA_ON_UPGRADE;OLDER_VERSION_WITH_ELGATO_PLUGINS;OLDERVERSIONBEINGUPGRADED;UNPLUG_MESSAGE;USAGE_STATISTICS_ACCEPTED_VALUE;WIN10FOUND;WIX_DOWNGRADE_DETECTED;WIX_UPGRADE_DETECTED;WIXUI_INSTALLDIR MSI (s) (D8:D4) [13:05:46:702]: Windows Installer installed the product. Product Name: Elgato Wave Link. Product Version: 1.9.0.1846. Product Language: 1033. Manufacturer: Corsair Memory, Inc.. Installation success or error status: 0.

(Automated response - build 615.)

**Comment by stephengillie** [comment]
Hi @krystofkrticka,

`Driver installation failed. Please reboot and start setup again.`

Despite having a failing error message, this package appears to install and launch normally. Also, there wasn't any interactive installer after rebooting the VM. Thoughts?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978334967 2024-01-19 13:05:47.029 [CLI ] ShellExecute installer failed: 3010 CAQuietExec:  Error 0x80070001: Command line returned an error. CAQuietExec:  Error 0x80070001: QuietExec Failed CAQuietExec:  Error 0x80070001: Failed in ExecCommon method CustomAction ClearFirewall returned actual error code 1603 but will be translated to success due to continue marking Property(S): DRIVERINSTALLFAILED_MESSAGE = Driver installation failed. Please reboot and start setup again. Property(S): DRIVERINSTALLFAILED_AUTO_MESSAGE = Driver installation failed. Please reboot and Setup will be started again. Property(S): ErrorDialog = ErrorDlg Property(S): SecureCustomProperties = DELETE_APPDATA_FILES_ACCEPTED_VALUE;DRIVERINSTALLFAILED_AUTO_MESSAGE;DRIVERINSTALLFAILED_MESSAGE;EXE_FILE_NAME;INSTALLDIR_PRODUCT_FAKE;INSTALLER_FILE_NAME;IS_DRIVER_UP_TO_DATE;IS_ELGATO_WAVE_DEVICE_CONNECTED;KEEP_SETTINGS_ALERT_MESSAGE;NETFRAMEWORK45;NEW_FIRMWARE_VERSION;OLD_COMP_PATH;OLDER_VERSION_DELETING_REGISTRY_APPDATA_ON_UPGRADE;OLDER_VERSION_WITH_ELGATO_PLUGINS;OLDERVERSIONBEINGUPGRADED;UNPLUG_MESSAGE;USAGE_STATISTICS_ACCEPTED_VALUE;WIN10FOUND;WIX_DOWNGRADE_DETECTED;WIX_UPGRADE_DETECTED;WIXUI_INSTALLDIR MSI (s) (D8:D4) [13:05:46:702]: Windows Installer installed the product. Product Name: Elgato Wave Link. Product Version: 1.9.0.1846. Product Language: 1033. Manufacturer: Corsair Memory, Inc.. Installation success or error status: 0.

(Automated response - build 656.)

**Comment by stephengillie** [comment]
Hi @krystofkrticka,

The installation isn't unattended. Is there an installer switch to have the package install silently?

(Automated response - build 656.)

**Comment by krystofkrticka** [comment]
@stephengillie Oh this might help since it uses wix installer which is compiled to .msi file so I could try usual switches.

**Comment by krystofkrticka** [comment]
@stephengillie just tried adding /quiet /qn /norestart but it still returns code 3010 which means that it installed successfully but restart is needed. When I tried promptrestart it just rebooted the computer without asking.

**Comment by krystofkrticka** [comment]
@stephengillie So I guess I have to probably add expected response code in manifest.

**Comment by krystofkrticka** [comment]
@stephengillie I have added switches for installer and expected return code but it still says that installer failed because the reboot is needed to finish.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978334967 2024-01-25 15:22:35.929 [CLI ] ShellExecute installer failed: 3010 CAQuietExec:  Error 0x80070001: Command line returned an error. CAQuietExec:  Error 0x80070001: QuietExec Failed CAQuietExec:  Error 0x80070001: Failed in ExecCommon method CustomAction ClearFirewall returned actual error code 1603 but will be translated to success due to continue marking Property(S): DRIVERINSTALLFAILED_MESSAGE = Driver installation failed. Please reboot and start setup again. Property(S): DRIVERINSTALLFAILED_AUTO_MESSAGE = Driver installation failed. Please reboot and Setup will be started again. Property(S): ErrorDialog = ErrorDlg Property(S): SecureCustomProperties = DELETE_APPDATA_FILES_ACCEPTED_VALUE;DRIVERINSTALLFAILED_AUTO_MESSAGE;DRIVERINSTALLFAILED_MESSAGE;EXE_FILE_NAME;INSTALLDIR_PRODUCT_FAKE;INSTALLER_FILE_NAME;IS_DRIVER_UP_TO_DATE;IS_ELGATO_WAVE_DEVICE_CONNECTED;KEEP_SETTINGS_ALERT_MESSAGE;NETFRAMEWORK45;NEW_FIRMWARE_VERSION;OLD_COMP_PATH;OLDER_VERSION_DELETING_REGISTRY_APPDATA_ON_UPGRADE;OLDER_VERSION_WITH_ELGATO_PLUGINS;OLDERVERSIONBEINGUPGRADED;UNPLUG_MESSAGE;USAGE_STATISTICS_ACCEPTED_VALUE;WIN10FOUND;WIX_DOWNGRADE_DETECTED;WIX_UPGRADE_DETECTED;WIXUI_INSTALLDIR MSI (s) (88:48) [15:22:35:758]: Windows Installer installed the product. Product Name: Elgato Wave Link. Product Version: 1.9.0.1846. Product Language: 1033. Manufacturer: Corsair Memory, Inc.. Installation success or error status: 0.

(Automated response - build 657.)

**Comment by stephengillie** [comment]
Despite returning an error, this package installs and launches normally in a Windows 10 VM.

**Comment by krystofkrticka** [comment]
That's exactly what I saw when testing it with Windows Sandbox which is opened by YamlCreate.ps1 script.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
