### PR TITLE
New version: zokugun.MrCode version 1.77.0.23092

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Failed
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | MrCode |     |
| Version     | 1.77.0.23092     |  |
| Publisher   | Microsoft Corporation   |       |
| ProductCode |           |     |
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101392)

### CODE REVIEW

**Comment by Trenly** [comment]
@stephengillie - Usually if you can't replicate the error, I've found that it's recorded in the pipeline installation validation logs. In this case:
```
2023-04-03 12:24:52.784 [FAIL] Installer failed security check. Url: https://github.com/zokugun/MrCode/releases/download/1.77.0.23092/MrCodeUserSetup-ia32-1.77.0.23092.exe Result: 0x80004005
```

**Comment by Trenly** [comment]
> > @stephengillie - Usually if you can't replicate the error, I've found that it's recorded in the pipeline installation validation logs. In this case:
> > ```
> > 2023-04-03 12:24:52.784 [FAIL] Installer failed security check. Url: https://github.com/zokugun/MrCode/releases/download/1.77.0.23092/MrCodeUserSetup-ia32-1.77.0.23092.exe Result: 0x80004005
> > ```
> 
> Where did you find this?

Checks tab -> Azure Pipelines -> View more details in Pipeline -> Artifacts -> InstallationValidationLogs -> . . . -> Download

**Comment by stephengillie** [comment]
> Checks tab -> Azure Pipelines -> View more details in Pipeline -> Artifacts -> InstallationValidationLogs -> . . . -> Download

Where is Artifacts?
image

**Comment by Trenly** [comment]
> > Checks tab -> Azure Pipelines -> View more details in Pipeline -> Artifacts -> InstallationValidationLogs -> . . . -> Download
> 
> Where is Artifacts?

My mistake; It's not a very clear button -
image

**Comment by stephengillie** [comment]
> My mistake; It's not a very clear button - 

No worries and thank you for showing me.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
