### PR TITLE
Create WinGet package for June 2023 GDK Update 1

### PR DESCRIPTION
**Pull request by aaron-stebner**
Create WinGet package for June 2023 GDK Update 1

Tested locally with winget validate and winget install
 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/113009&drop=dogfoodAlpha

### CODE REVIEW

**Comment by aaron-stebner** [comment]
@microsoft/xbox-developer-experience-toolbox for review

**Review by ItzLevvie — APPROVED** [review]

**Comment by MattHyman** [comment]
> @microsoft/xbox-developer-experience-toolbox for review

LGTM.

**Pull request merged**
