### PR TITLE
New version: Joplin.Joplin version 2.13.13

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132964)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification.
>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Review by OfficialEsco — COMMENTED** [review]
Joplin starts but it gets stuck installing
image

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 

(Automated response - build 525.)

**Comment by stephengillie** [comment]
The installer appears to launch the application:
image

**Comment by stephengillie** [comment]
Hi @Exorcism666,

Unlike previous versions of `Joplin.Joplin`, this appears to be the portable version. Should it be under `Joplin.Joplin.Portable` instead?

**Comment by Exorcism0666** [comment]
I will reopen a pull request.

**Pull request closed without merging**
