### PR TITLE
New package: Microsoft.XboxApp version 1.0.1.30

### PR DESCRIPTION
**Pull request by rakleed**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141815)

### CODE REVIEW

**Comment by rakleed** [comment]
I could not find silent parameter

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 857.)

**Comment by og-mrk** [comment]
Looking into Package Installer, no available switches to use with .exe file
Should be closed for https://github.com/microsoft/winget-pkgs/labels/License-Blocks-Install due it requiring User Input when trying to install this Package.

**Review by og-mrk — COMMENTED** [review]
Looking into Package Installer, no available switches to use with .exe file
Should be closed for https://github.com/microsoft/winget-pkgs/labels/License-Blocks-Install due it requiring User Input when trying to install this Package.

**Pull request closed without merging**
