### PR TITLE
Theseus2000 manifest  update for version 1.2B

### PR DESCRIPTION
**Pull request by seedy60**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/54071)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
```
Manifest validation failed.
Manifest Error: The multi file manifest has inconsistent field values. Field: PackageVersion Value: 1.2 File: Seedy-Threepio.Theseus2000.locale.en-US.yaml
```

**Comment by Seedy-Threepio** [comment]
I changed the offending file, hopefully my changes saved; I'm still getting the hang of this GitHub thing :)

**Review by ItzLevvie — CHANGES_REQUESTED** [review]

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Missing this as well: https://github.com/microsoft/winget-pkgs/pull/54071#discussion_r825831863

**Review by ItzLevvie — APPROVED** [review]

**Comment by Seedy-Threepio** [comment]
I don't see what was wrong with that hash value.

**Pull request closed without merging**
