### PR TITLE
ExodusMovementInc.Exodus version 21.5.25

### PR DESCRIPTION
**Pull request by QuinnGraham15**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14368)

### CODE REVIEW

**Comment by Meteor24** [comment]
Where did you get the license for this?

**Comment by QuinnGraham15** [comment]
> Where did you get the license for this?

https://www.exodus.com/
https://www.exodus.com/legal/exodus-tos-20201107-v16.pdf

**Comment by QuinnGraham15** [comment]
Closed at the request of exodus devs.

**Comment by Xanthus58** [comment]
Hello; just thought id post this here, I reached out to exodus for the reasoning in refusing winget implementation and this is what they had to say .

## Hi Aviion,

Thanks for reaching out to Exodus support. My name is Jamie and I'll be happy to help you out today.

While I do not have insight into why this request was closed in GitHub, I can reach out to our development team to log your request for Exodus being added to the Windows Package Community Repository.

However, we love when members of our community express themselves and advocate for projects/features. This helps build confidence in the space.

I have made a note of your request for information from our development team, rest assured, we look at all the feedback we receive.

I hope this helps! I'll be sure to reach back out to you when I have an answer from the dev team.

Hope you're having a great weekend so far.

All my best,
Jamie

**Comment by QuinnGraham15** [comment]
> Hello; just thought id post this here, I reached out to exodus for the reasoning in refusing winget implementation and this is what they had to say .
> 
> ## Hi Aviion,
> Thanks for reaching out to Exodus support. My name is Jamie and I'll be happy to help you out today.
> 
> While I do not have insight into why this request was closed in GitHub, I can reach out to our development team to log your request for Exodus being added to the Windows Package Community Repository.
> 
> However, we love when members of our community express themselves and advocate for projects/features. This helps build confidence in the space.
> 
> I have made a note of your request for information from our development team, rest assured, we look at all the feedback we receive.
> 
> I hope this helps! I'll be sure to reach back out to you when I have an answer from the dev team.
> 
> Hope you're having a great weekend so far.
> 
> All my best, Jamie

They reached out to me and asked me to close the PR to add it because they do not want any way except the official way to download exodus. The only way they want you to download it is from the official website and nothing else. This is due to security concerns and such. They don't want people to possibly download a fraudulent version of exodus.

They went further on to say, they love the intentions and maybe they will work with the winget team directly but they don't want others to do it for mainly security reasons.

**Comment by ItzLevvie** [comment]
Exodus developers have three options:
- publish onto the Microsoft Store
- wait until WinGet gets support for verified publishers (where only the publisher can modify their own packages, and contributors & moderators aren't allowed)
- create a private repository using the REST API

**Pull request closed without merging**
