### PR TITLE
Update D:\Git\winget-pkgs\manifests\c\CPUID\CPU-Z\2.05

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114245&drop=dogfoodAlpha

### CODE REVIEW

**Review by ImJoakim — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Validation: 
1. en-US
1. zh-SG

**Pull request merged**
