### PR TITLE
Add MinIO.Client 2024.01.18

### PR DESCRIPTION
**Pull request by stevapple**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136158)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 655.)

**Comment by stevapple** [comment]
Please add `dl.min.io` to allow list, as described in https://min.io/download#/windows

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 656.)

**Comment by stephengillie** [comment]
> Please add `dl.min.io` to allow list, as described in https://min.io/download#/windows

The general requirement is that anyone can navigate from the `PackageUrl` to the `InstallerUrl`, or failing that, find the package easily on the developer's website. An Internet search for `min.io archive` brought me to [this archive page](https://dl.min.io/client/mc/release/windows-amd64/archive/), which has the package on it. This satisfies our requirement.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
