### PR TITLE
Url Forbidden: ItsSim.fsolauncher

### LINKED ISSUE #25500: Automation has determined ItsSim.fsolauncher 1.7.7 is unavailable
The URL for version 1.7.7 of ItsSim.fsolauncher has been unavailable for 5 or more days.
This package may be removed from the repository if no valid manifest is available in the next 14 days.

If the installer has been moved, please update the manifest with the new URL. If a new version of the package is available, please create a new manifest with the valid URL, version, and SHA256 hash.
If this package is no longer available, please delete the manifest.

```

```

### LINKED ISSUE #38825: Automation has determined ItsSim.fsolauncher 1.7.7 is unavailable
The URL for version 1.7.7 of ItsSim.fsolauncher has been unavailable for 5 or more days.
This package may be removed from the repository if no valid manifest is available in the next 14 days.

If the installer has been moved, please update the manifest with the new URL. If a new version of the package is available, please create a new manifest with the valid URL, version, and SHA256 hash.
If this package is no longer available, please delete the manifest.

```

```

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

This update failed in #25586 but imma try again

* Resolves #25500
* Resolves #38825

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/37993)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
@riperiperi would this be something you could resolve?

**Comment by riperiperi** [comment]
Both of those URLs are accessible here, I might need a bit more info.

**Comment by OfficialEsco** [comment]
Uhm, the winget validation is getting blocked by your webpage, probably by bot protection
@denelon could probably elaborate if hes available :)

**Review by ItzLevvie — DISMISSED** [review]

**Comment by denelon** [comment]
We've seen examples where our "user agent" isn't allowed to get a response, as well as examples where our IP address range has been blocked.

**Comment by Trenly** [comment]
> We've seen examples where our "user agent" isn't allowed to get a response, as well as examples where our IP address range has been blocked.

Is there a fallback user agent, where if it can't get through with your default user agent it tries again with just a default chrome user agent?

**Comment by vedantmgoyal2009** [comment]
> > We've seen examples where our "user agent" isn't allowed to get a response, as well as examples where our IP address range has been blocked.
> 
> Is there a fallback user agent, where if it can't get through with your default user agent it tries again with just a default chrome user agent?

@denelon

**Comment by denelon** [comment]
That's an interesting suggestion. I don't know what percentage of the time that would improve the results, but we could look at that.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
