### PR TITLE
New package: Prog.ProgDVB.NetworkEdition version 7.60.8

### LINKED ISSUE #154507: [Package Request]: ProgDVB Network Edition
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.progdvb.com/download_progdvb.html
Publisher: Prog
Package Name: ProgDVB Network Edition
Description: Universal and very powerful software for watching digital TV and listening to radio channels.
Package Version: 7.60.8
Installer URL: https://files.progdvb.com/progdvb/ProgDVB7.60.8x64NetPro.exe

### PR DESCRIPTION
**Pull request by schembriaiden**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.2.1 :rocket:

Resolves: https://github.com/microsoft/winget-pkgs/issues/154507
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/154550)

### CODE REVIEW

**Comment by stephengillie** [comment]
Verify: 
image

**Comment by stephengillie** [comment]
Hi @vikingnope,

The Registry version (7.x) doesn't appear to match the version data in the manifest. Should it be modified?

**Comment by vikingnope** [comment]
Yes do not merge this yet please

**Comment by vikingnope** [comment]
Should be correct now, although the apps and features version seems to be fine that way.

**Comment by stephengillie** [comment]
Verify: 
image

https://github.com/microsoft/winget-pkgs/pull/154577#issuecomment-2123676645

**Comment by vikingnope** [comment]
> Should be correct now, although the apps and features version seems to be fine that way.
> 
> Edit: sorry closed by mistake

@stephengillie

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
