### PR TITLE
New Package: Joplin.Joplin.Pre-release version 2.3.5

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/25221)

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
https://github.com/microsoft/winget-pkgs/pull/25010#issuecomment-899020942

@laurent22 @OfficialEsco Should I move all Joplin packages to this package?

**Comment by laurent22** [comment]
@vedantmgoyal2009, sorry I'm not familiar with winget packages. Do you mean that all Joplin versions would go under that pre-release package? Because there are two types of Joplin releases:

- Regular ones, which could simply go under the name "Joplin"
- Pre-releases, which (up to you) could either be ignored or released under for example "Joplin.Pre-release".

But I don't think both release types should go under a "pre-release" package. Hope that makes sense.

**Comment by OfficialEsco** [comment]
@vedantmgoyal2009 don't move ALL, move or just delete the ones who were Pre-Release, you can probably figure out which is which from the Change Notes or use Chocolatey Version history.

@laurent22 In the future we will have support for Channels, so both Branches can be in the same folder, but as of now they can be split into `Joplin.Joplin` and `Joplin.Joplin.Pre-Release` (unless you want another name).

Since you don't have a different `PackageName` for the Pre-Release branch the user will have to do `winget install Joplin.Joplin.Pre-Release` or `"Joplin (Pre-Release)"` to install the Pre-Release version, if they do `winget upgrade` they will only get or upgrade to the lastest `Stable` version

**Comment by vedantmgoyal2009** [comment]
Sorry for being less clear but as we are currently talking about only pre-release versions, I was trying to mention the ones that are Pre-Release.

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
