### PR TITLE
New version: Tencent.WeChat version 3.9.6.33

### PR DESCRIPTION
**Pull request by SpecterShell**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/109308&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by stephengillie** [comment]
For some reason, this package's installer doesn't complete once the software is installed. 
image

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation didn't complete within the timeout

**Comment by stephengillie** [comment]
> For some reason, this package's installer doesn't complete once the software is installed. image

As before, the installer does not exit after installing the application. I was mistaken before, believing the QR code to be the end of the installer. Now I see it's the installer launching the application. Now the application doesn't launch automatically, so it's not blocking the installer. 
image

Running the application from the desktop icon works great! If we could get the installer to complete, it would be ready to merge.

**Review by Trenly — APPROVED** [review]

**Pull request merged**
