### PR TITLE
Update NVAccess.NVDA manifests to all have a ProductCode and X86 architecture

### PR DESCRIPTION
**Pull request by LeonarddeR**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/66488)

### CODE REVIEW

**Comment by mdanish-kh** [comment]
[#65253 (comment)](https://github.com/microsoft/winget-pkgs/pull/65253#issuecomment-1176315066) You need to make separate pull requests for each of the packages.

**Comment by leonardder** [comment]
I assume that would make te pipelines run succesfully, but it should be possible to review this pr manually, right?

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
Oh i didn't see the comments

> I assume that would make te pipelines run succesfully, but it should be possible to review this pr manually, right?

They don't manually merge PRs other than for very special reasons, any normal PRs have to be separate until the pipeline supports multiple package version changes

**Comment by leonardder** [comment]
Ugh, ooh well. I will do separate pull requests then.

**Pull request closed without merging**
