### PR TITLE
Create Mirth OAI Installer folder

### PR DESCRIPTION
**Pull request by Sriraksha26**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/103095)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
I know what is the problem. It look like missing 2 file.

**Comment by BrandonWanHuanSheng** [comment]
@stephengillie can you request suggested change to this PR?

**Comment by stephengillie** [comment]
Automatic Validation failed with:
> Manifest: The manifest file path must match PackageIdentifier and PackageVersion properties from manifest. actual 
> 'manifests\r\RamSoft\MirthOAI\1.0.667', expected 
> 'manifests\m\MirthOAI\1.0.667-sriraksha-int-190-pipelineFor-buildMirth.70'  
image

The red boxes have to match. Except that the first one has a `\` instead of a `.`. 
And the blue boxes have to match.

**Comment by stephengillie** [comment]
The singleton manifest format is out of date. Please consider using the [1.4.0 multi-file manifest](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0) format.

**Review by shaqmate — APPROVED** [review]

**Pull request closed without merging**
