### PR TITLE
Delete Mozilla.Thunderbird-es.yaml

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/10888)

### CODE REVIEW

**Comment by jedieaston** [comment]
@OfficialEsco Here's the script I made to remove the Firefox duplicates: https://gist.github.com/jedieaston/8cd3a965158f221e53c6da4e163b5a75

You'll have to set the paths to wherever you keep your copy of winget-pkgs, and it needs the github cli to be installed. PATH_TO_PR_BODY is a path to a file with the body you want for the pull request.

Let me know if you have more questions, I made it kind of quickly and didn't put comments.

**Comment by OfficialEsco** [comment]
@jedieaston i just tested the script and got
```
Press enter to begin opening pull requests.
Press Enter to continue...:
Switched to branch 'Thunderbird-78.1.0(AF)-DELETE'
Your branch is ahead of 'upstream/master' by 1 commit.
  (use "git push" to publish your local commits)
info: please complete authentication in your browser...
fatal: An error occurred while sending the request.
fatal: Unable to connect to the remote server
fatal: An attempt was made to access a socket in a way forbidden by its access permissions 140.82.121.4:443
Username for 'https://github.com':
```
I got a popup about login in via the website or token, i clicked on website and it prompted for Username, i then entered my Email and the next line became Password for 'https://private@email.com@github.com'
I tried to rerun the script but then it just ends at 
```
Press enter to begin opening pull requests.
Press Enter to continue...:
```
aaaand now i'm stuck with a bunch of local branches that i don't know how to remove D:

**Comment by jedieaston** [comment]
@OfficialEsco In a new PowerShell, do ` gh login ` and follow the instructions (if there are any, maybe you got logged in the first time

Then go to your winget-pkgs folder, make sure you have master checked out, and do ` foreach ($branch in (git branch --list | findstr "Thunderbird-*"|)) { git branch -D $branch.trim() } ` to clear the branches you don't want. (Really, it clears all of the ones starting with Thunderbird-, so maybe check to make sure you don't have any branches you want to keep before you do that :P).

Then try it again, hopefully it will work this time now that you are logged into GitHub!

**Comment by OfficialEsco** [comment]
Thaaaaaaanks, apperently this was a user error because i've never downloaded Github CLI and i was mega confused when `gh` didn't work..

**Comment by jedieaston** [comment]
Oops. I had been using a path there, quickly swapped it to a variable when I posted it on the Gist. that's why I should really test things first. good that you got it working though.

**Pull request merged**
