### PR TITLE
CmdUtil.WhatTheFile version v1.0.1

### PR DESCRIPTION
**Pull request by UsernameIsNotAvailiable**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/190295)

### CODE REVIEW

**Comment by UsernameIsNotAvailiable** [comment]
@microsoft-github-policy-service agree

**Comment by UsernameIsNotAvailiable** [comment]
what do i do now

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\CmdUtil.WhatTheFile__DefaultSource\whatthefile.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\whatthefile.exe returned exit code: 1

(Automated response - build 897.)

**Comment by UsernameIsNotAvailiable** [comment]
?

**Comment by stephengillie** [comment]
Hi @UsernameIsNotAvailiable,

Sorry for the delayed response. I'm dealing with capacity issues.

Please understand that my previous comment was the output of a scripted process which downloaded the run logs, filtered to include and exclude specific terms, then matcheed this against a list of error codes to produce the error analysis - before posting this output to the PR. 

The validation pipeline is somewhat designed for Windows Forms, and add the https://github.com/microsoft/winget-pkgs/labels/Validation-Executable-Error link when the exit code is non-zero. But a non-zero exit code is common for CLI applications, so I usually pass exit codes below 1000. I"ve requested to push this upstream: 
- https://github.com/microsoft/winget-pkgs/issues/157749

**Comment by stephengillie** [comment]
Verify:
image
I couldn't find how to have the application display the version number.

**Review by stephengillie — APPROVED** [review]

**Comment by UsernameIsNotAvailiable** [comment]
@stephengille sorry for my delayed response but i don't have version built in.

**Comment by stephengillie** [comment]
No worries, and thank you for taking the time to respond, even at a delay.

**Pull request merged**
