### PR TITLE
New version: TeamLidarr.Lidarr version 2.4.3.4248

### PR DESCRIPTION
**Pull request by KaranKad**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/163119)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @KaranKad,

This manifest adds Apps and Features entries that aren't present in previous PR versions. These entries should be added to the previous versions, or removed from this version.

(Automated response - build 886.)

**Comment by KaranKad** [comment]
DisplayVersion in arp is 2.4.3 as opposed to version released on github 2.4.3.4248, this causes the application to upgrade each time when its not necessary.

**Comment by mdanish-kh** [comment]
[Policy] reset feedback

**Comment by mdanish-kh** [comment]
> DisplayVersion in arp is 2.4.3 as opposed to version released on github 2.4.3.4248, this causes the application to upgrade each time when its not necessary.

@KaranKad Yes DisplayVersion should be used here, but @stephengillie's point is also valid that if we are to add DisplayVersion, then it should be added on all previous versions as well because of how WinGet handles version ranges. If DisplayVersion is not present in all manifests, then users may face the "upgrade always available" problem where users are stuck in an upgrade loop. I'm going to approve this PR, but we need to either go back and add this value in older manifests, or remove them from the repo

**Review by mdanish-kh — APPROVED** [review]

**Pull request merged**
