### PR TITLE
Updated TeamViewer.TeamViewer from v15.18.5 to v15.19.3

### PR DESCRIPTION
**Pull request by ImJoakim**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/18929)

### CODE REVIEW

**Comment by ImJoakim** [comment]
TeamViewer

image

**Comment by ImJoakim** [comment]
Trying to run this one more time. Installs just fine when testing.

**Comment by ImJoakim** [comment]
Guess not 🤔

**Comment by ImJoakim** [comment]
Do any of you have any suggestions? @ItzLevvie @OfficialEsco 

Happens to TeamViewer and TeamViewerHost (#18930). Works perfectly fine when I'm testing.

**Comment by OfficialEsco** [comment]
I think the bot is just acting up lately… my #18872 PR is also getting this but installing fine in sandbox… more and more PR are failing too..

**Comment by ryfu-msft** [comment]
Hey @ImJoakim, 

I apologize for the delay on this PR. When I tried running winget on this manifest, I am consistently met with an unexpected InternetOpenUrl() - 0x80072ee7. I have tried this locally and on a clean vm. Can you let me know what version of winget you have? This could potentially be a bug on winget because the installer url does work with no issues. Thanks!

**Comment by ImJoakim** [comment]
> Hey @ImJoakim,
> 
> I apologize for the delay on this PR. When I tried running winget on this manifest, I am consistently met with an unexpected InternetOpenUrl() - 0x80072ee7. I have tried this locally and on a clean vm. Can you let me know what version of winget you have? This could potentially be a bug on winget because the installer url does work with no issues. Thanks!

Hey @ryfu-msft,
I am running it via Windows Sandbox. This script specifically:
https://github.com/microsoft/winget-pkgs/blob/master/Tools/SandboxTest.ps1

This script should install the latest winget:

image

**Comment by ImJoakim** [comment]
Hey again @ryfu-msft,

It seems like it fails on the previous version of winget, but works on latest:

image

**Comment by ryfu-msft** [comment]
> Hey again @ryfu-msft,
> 
> It seems like it fails on the previous version of winget, but works on latest:
> 
> image

Hmm very interesting. Thank you for this info, I will need to investigate this further and get back to you.

**Comment by ImJoakim** [comment]
> > Hey again @ryfu-msft,
> > It seems like it fails on the previous version of winget, but works on latest:
> > image
> 
> Hmm very interesting. Thank you for this info, I will need to investigate this further and get back to you.

Sounds good! Let me know if there's anything I can do :)

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
