### PR TITLE
New version: ImageLine.FLStudio version 24.1.0.4219

### PR DESCRIPTION
**Pull request by HevyMusic**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/160093)

### CODE REVIEW

**Comment by HevyMusic** [comment]
There is a new version in-between, is it possible to stop the process for a file that is being validated (how can I do if we again release a new version before the older one is verified)?
FL Studio always has that issue that it needs to be validated manually in my past updates

**Comment by stephengillie** [comment]
Hi @HevyMusic,

Versions can be added and removed independently of each other. Feel free to open another PR with the other new version.

As for the persistent pipeline error...
- https://github.com/microsoft/winget-pkgs/discussions/155218

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Comment by HevyMusic** [comment]
> Hi @HevyMusic,
> 
> Versions can be added and removed independently of each other. Feel free to open another PR with the other new version.
> 
> As for the persistent pipeline error...
> 
> * [internal error dynamic scan #155218](https://github.com/microsoft/winget-pkgs/discussions/155218)

Thanks, pushed it.
Also thanks for the link good to know.
It just wondered me that it always happens with this application.

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
