### PR TITLE
Update manifest: Maltego.Maltego version 4.7.0

### LINKED ISSUE #167705: [Package Issue]: Maltego.Maltego Don't read the right installed version.
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

Winget finds that the installed version of Maltego is 4, but in fact version 4.7.0 is already installed.

### Steps to reproduce

winget update Maltego.Maltego

### Actual behavior

winget try to install but its dosent work 

### Expected behavior

Don't ask to update.

### Environment

```raw
Gestionnaire de package Windows v1.8.1911
Copyright (c) Microsoft Corporation. Tous droits réservés.

Windows: Windows.Desktop v10.0.19045.4717
Architecture du système : X64
Package : Microsoft.DesktopAppInstaller v1.23.1911.0

Répertoires Winget
-----------------------------------------------------------------------------------------------------------------------
Journaux                                     %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Paramètres utilisateurs                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\Local…
Répertoire des liens portables (utilisateur) %LOCALAPPDATA%\Microsoft\WinGet\Links
Répertoire des liens portables (ordinateur)  C:\Program Files\WinGet\Links
Racine de package portable (utilisateur)     %LOCALAPPDATA%\Microsoft\WinGet\Packages
Racine du package portable                   C:\Program Files\WinGet\Packages
Racine de package portable (x86)             C:\Program Files (x86)\WinGet\Packages
Téléchargements du programme d’installation  %USERPROFILE%\Downloads

Liens
---------------------------------------------------------------------------------------------
Déclaration de confidentialité        https://aka.ms/winget-privacy
Contrat de licence                    https://aka.ms/winget-license
Avis de tiers                         https://aka.ms/winget-3rdPartyNotice
Page d’accueil                        https://aka.ms/winget
Conditions générales du Windows Store https://www.microsoft.com/en-us/storedocs/terms-of-sale

Paramètre administrateur                  État
---------------------------------------------------
LocalManifestFiles                        Désactivé
BypassCertificatePinningForMicrosoftStore Désactivé
InstallerHashOverride                     Activé
LocalArchiveMalwareScanOverride           Désactivé
ProxyCommandLineOptions                   Désactivé
DefaultProxy                              Désactivé
```

### Screenshots and Logs

image

―― 11:00:47 - winget ――――――――――――――――――――――――
Nom               ID                               Version     Disponible     Source
――――――――――――――――――――――――――――――――――
Maltego          Maltego.Maltego       4               4.7.0               winget

### PR DESCRIPTION
**Pull request by Dragon1573**
## Details

- Correction of `DisplayVersion` in ARP entries
- Add `UpgradeBehavior` according to some errors

## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- Resolve #167705

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/167723)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-08-14T18:09:16.5177446Z Manifest Validation Failed
 2024-08-14T18:09:21.5658770Z ##[error]Manifest Validation Failed

(Automated response - build 887.)

**Comment by Dragon1573** [comment]
Manually validated.

image

**Comment by stephengillie** [comment]
> Automatic Validation ended with:
> 
> > Manifest Error: DisplayVersion declared in the manifest has overlap with existing DisplayVersion range in the index. Existing DisplayVersion range in index:  [ [4, 4]]

There's already a manifest with `DisplayVersion: "4"` in the repo. It will need to be removed before this can be added.

**Comment by Dragon1573** [comment]
Previous version is removed by #167963. This PR can continue ❤️

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
