### PR TITLE
New package: Devicetree compiler version 1.6.1

### PR DESCRIPTION
**Pull request by carlescufi**
This adds the Devicetree compiler (dtc) version 1.6.1.

Replaces previous attempt in #114001

Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/202965)

### CODE REVIEW

**Comment by carlescufi** [comment]
> The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.

`winget install --manifest <path>` seems to work fine locally for me. The [logs](https://dev.azure.com/shine-oss/winget-pkgs/_build/results?buildId=41791&view=logs&j=68997d86-8ece-5ae8-3ac5-ccdbfa458731&t=b79910ce-dca5-5e27-ad7f-bd285eecb5a2) do not seem to show any useful information.

@stephengillie @Trenly @mdanish-kh pinging you since you commented on this PR's [predecessor](https://github.com/microsoft/winget-pkgs/pull/114001), any clues as to what is wrong?

**Comment by Trenly** [comment]
@carlescufi - If you go to the artifacts of the pipeline run, you can download additional logs from the check which aren't able to be exposed to the Azure Pipelines console. In these logs I see 
```
2024-12-28 07:41:46.975 [FAIL] Installer failed security check. Url: https://github.com/carlescufi/winget-packages/raw/refs/heads/main/packages/dtc/1.6.1/dtc-msys2-1.6.1-x86_64.zip Result: 0x80004005
2024-12-28 07:41:46.975 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6
```

This error usually means that it isn't a URL that Windows Defender Smart Screen is aware of. Typically, these errors resolve themselves in a day or two after SmartScreen finishes scanning the URL. I believe Stephen's automation will attempt a retry after a day automatically, but if not, feel free to simply close and re-open this PR to kick off a new validation run

**Comment by carlescufi** [comment]
> This error usually means that it isn't a URL that Windows Defender Smart Screen is aware of. Typically, these errors resolve themselves in a day or two after SmartScreen finishes scanning the URL. I believe Stephen's automation will attempt a retry after a day automatically, but if not, feel free to simply close and re-open this PR to kick off a new validation run

I see, thank you @Trenly.

**Review by ItzLevvie — APPROVED** [review]

**Comment by carlescufi** [comment]
CC @piernov

**Pull request merged**
