### PR TITLE
New version: Tencent.WeCom version 4.1.6.6017

### PR DESCRIPTION
**Pull request by StarsbySea**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----
Based on #42975
 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/111272&drop=dogfoodAlpha

### CODE REVIEW

**Comment by StarsbySea** [comment]
First of all, this is the official domain name of Tencent, and the file downloaded from here is consistent with the content of the official website.
Again, the difference between dldir1.qq.com and dldir1v6.qq.com is that the former only provides A type domain name resolution, that is, it only supports IPv4 network, while the latter's A resolution is consistent with the former, but at the same time provides AAAA, that is, IPv6 address resolution results. Both provide exactly the same content and are already in use in some places, such as https://github.com/microsoft/winget-pkgs/blob/58be5060cee1c937d9429ab6fa67c10f905997a0/manifests/t/Tencent/QQMusic/19.37/Tencent.QQMusic.installer.yaml#L58, so it can be considered as the official download address.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
