### PR TITLE
New version: Hitencent.JisuTodo version 3.0.0.3

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#6478](https://github.com/SpecterShell/Dumplings/actions/runs/9867119714).

<details>

<summary>Log</summary>

````
Updated: 3.0.0.2 → 3.0.0.3
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/162202)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2145844848
> 2024-07-10 07:30:34.558 [CORE] DeliveryOptimization error: 0x80d02002, extended error: 0x80190190
> 2024-07-10 07:30:34.601 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!550D57EB: (caller: 550D5E1C) Exception(1) tid(1894) 80D02002 
> 2024-07-10 07:30:41.410 [CORE] Download request failed. Returned status: 400
> 2024-07-10 07:30:41.412 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!550CFA75: (caller: 550D0E2B) Exception(2) tid(1894) 80190190 Bad request (400).
> 2024-07-10 07:30:41.423 [CLI ] Failed to download, waiting a bit and retry. Url: https://dl.jisutodo.com/jisutodo_setup_3.0.0.3.exe
> 2024-07-10 07:31:42.378 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(267)\WindowsPackageManager.dll!550D570C: (caller: 550D5E1C) Exception(3) tid(1894) 80D02002 
> 2024-07-10 07:31:43.119 [CORE] Download request failed. Returned status: 400
> 2024-07-10 07:31:43.120 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!550CFA75: (caller: 550D0E2B) Exception(4) tid(1894) 80190190 Bad request (400).

Automated error analysis suggests 0x80D02002 may mean The operation timed out.

(Automated response - build 886.)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2145844848
> 2024-07-11 17:34:57.170 [CORE] DeliveryOptimization error: 0x80190190, extended error: 0x00000000
> 2024-07-11 17:34:57.271 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!556857EB: (caller: 55685E1C) Exception(1) tid(700) 80190190 Bad request (400).
> 2024-07-11 17:34:59.586 [CORE] Download request failed. Returned status: 400
> 2024-07-11 17:34:59.586 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!5567FA75: (caller: 55680E2B) Exception(2) tid(700) 80190190 Bad request (400).
> 2024-07-11 17:34:59.602 [CLI ] Failed to download, waiting a bit and retry. Url: https://dl.jisutodo.com/jisutodo_setup_3.0.0.3.exe
> 2024-07-11 17:35:05.576 [CORE] DeliveryOptimization error: 0x80190190, extended error: 0x00000000
> 2024-07-11 17:35:05.576 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!556857EB: (caller: 55685E1C) Exception(3) tid(700) 80190190 Bad request (400).
> 2024-07-11 17:35:05.870 [CORE] Download request failed. Returned status: 400
> 2024-07-11 17:35:05.870 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!5567FA75: (caller: 55680E2B) Exception(4) tid(700) 80190190 Bad request (400).

(Automated response - build 886.)

**Comment by stephengillie** [comment]
URL: https://dl.jisutodo.com/jisutodo_setup_3.0.0.3.exe 
Response Error: The remote server returned an error: (404) Not Found.

(Automated message - build 911)

**Comment by stephengillie** [comment]
URL: https://dl.jisutodo.com/jisutodo_setup_3.0.0.3.exe 
Response Error: The remote server returned an error: (404) Not Found.

(Automated message - build 911)

**Pull request closed without merging**
