### PR TITLE
GerhardRöhner.Java-Editor version 19.23

### PR DESCRIPTION
**Pull request by gasts**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/30312)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Last time I checked, Git has issues parsing special characters in folders, so you'll have to rename the folder and file names from `GerhardRöhner` to `GerhardRohner`.

Also, you need to sign the CLA.

**EDIT: File names too.**

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
`manifests/g/GerhardRöhner` needs to be changed to `manifests/g/GerhardRohner`

The pipelines are also having some issues atm.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Missing a dot (`.`) in `GerhardRoehnerJava-Editor.installer.yaml`

It needs to be `GerhardRoehner.Java-Editor.installer.yaml`

**Review by ItzLevvie — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
