### PR TITLE
Update ZAP to 2.15.0

### PR DESCRIPTION
**Pull request by psiinon**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/152806)

### CODE REVIEW

**Comment by kingthorin** [comment]
Can someone let us know how to get this passing? I suspect the jobs are timing out because the installer is unknown to Defender SmartScreen?

I was able to validate and install on a local Win 11 VM.

**Comment by kingthorin** [comment]
@stephengillie as far as I can tell that's completely outside our control? That seems to be the result for lots of PRs these days 😞

**Comment by stephengillie** [comment]
> @stephengillie as far as I can tell that's completely outside our control? The same result is definitely seen on other PRs recently.
> 
> ex: [#149313 (comment)](https://github.com/microsoft/winget-pkgs/pull/149313#issuecomment-2059350627)

Yes. My automation should be automatically retrying these.

**Comment by psiinon** [comment]
I'm not sure what feedback is expected from me here - can anyone explain?

**Comment by psiinon** [comment]
Just updated the manifest schema version

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
