### PR TITLE
Apple.QuickTime version 7.79.80.95

### PR DESCRIPTION
**Pull request by rohith1125**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14625)

### CODE REVIEW

**Comment by KaranKad** [comment]
I've submitted #14650, let's see if it works this time.

**Comment by rohith1125** [comment]
What changes did you make?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by KaranKad** [comment]
Changed `InstallerSwitches` but still didn't worked.

**Comment by rohith1125** [comment]
Oh, Hmmm.. If you get to know any more info, or if it accepts the PR, please do tell me


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by rohith1125** [comment]
Hey dude, Please have a look at this... It struck at build state,https://github.com/microsoft/winget-pkgs/pull/14677On May 30, 2021 6:24 PM, Rohith T ***@***.***> wrote:

Oh, Hmmm.. If you get to know any more info, or if it accepts the PR, please do tell me
 
 
Sent from 
Mail for Windows 10
 

From: Karan09
Sent: 30 May 2021 06:23 PM
To: microsoft/winget-pkgs
Cc: Rohith; 
State change
Subject: Re: [microsoft/winget-pkgs] Apple.QuickTime version 7.79.80.95 (#14625)

 
Changed InstallerSwitches but still didn't worked.
—
You are receiving this because you modified the open/close state.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.

**Comment by KaranKad** [comment]
It will stop after a long time.

**Pull request closed without merging**
