### PR TITLE
Allow moderators to tag Zip-Binary

### PR DESCRIPTION
**Pull request by mdanish-kh**
cc @denelon @Trenly

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/102492)

### CODE REVIEW

**Review by Trenly — APPROVED** [review]

**Review by denelon — APPROVED** [review]

**Comment by denelon** [comment]
Test please :)

**Comment by Trenly** [comment]
[Policy] zip binary

**Comment by Trenly** [comment]
[Policy] Dependencies

**Comment by Trenly** [comment]
Sorry for spamming your PR :D

**Pull request merged**
