### PR TITLE
New version: Opera.Opera version 111.0.5168.55

### PR DESCRIPTION
**Pull request by PckgrBot**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161048)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @PckgrBot,

Is a new installer switch needed to bypass this?
image

The word which appears blacked out is "EULA", and this appears to be a display issue. Clicking it gives a window which doesn't display properly:
image

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
