### PR TITLE
New version: NI.ni-daqmx version 24.3.0

### PR DESCRIPTION
**Pull request by lars-nvhgroup**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/149299)

### CODE REVIEW

**Comment by lars-whta** [comment]
> @wingetbot run

Is it possible to beforehand request more than 3h of validation? Most of the NI packages take a very long time to install, even on a fast computer.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-04-15 08:30:38.063 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF89BAAC11F: (caller: 00007FF89B838D6F) LogHr(1) tid(1340) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF89B9B2B08: (caller: 00007FF89BA5BC20) Exception(1) tid(1340) 8A15005E ] 
> 2024-04-15 08:30:38.063 [REPO] Failed to open available source: msstore
> 2024-04-15 08:30:42.354 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF89BAAC11F: (caller: 00007FF89B838D6F) LogHr(1) tid(ef4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF89B9B2B08: (caller: 00007FF89BA5BC20) Exception(1) tid(ef4) 8A15005E ] 
> 2024-04-15 08:30:42.354 [REPO] Failed to open available source: msstore
> 2024-04-15 08:30:45.787 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF89BAAC11F: (caller: 00007FF89B838D6F) LogHr(1) tid(1b64) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF89B9B2B08: (caller: 00007FF89BA5BC20) Exception(1) tid(1b64) 8A15005E ] 
> 2024-04-15 08:30:45.787 [REPO] Failed to open available source: msstore
> 2024-04-15 08:30:54.023 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF88221C11F: (caller: 00007FF881FA8D6F) LogHr(1) tid(11a4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF882122B08: (caller: 00007FF8821CBC20) Exception(1) tid(11a4) 8A15005E ] 
> 2024-04-15 08:30:54.023 [REPO] Failed to open available source: msstore
> 2024-04-15 08:49:20.077 [CLI ] ShellExecute installer failed: 4294842213

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Hi @Manually-Validated,

This package installs and launches normally on a Windows 10 VM.

(Automated response - build 662.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
