### PR TITLE
JesseDuffield.Lazydocker version 0.21.1

### PR DESCRIPTION
**Pull request by optsing**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/115203&drop=dogfoodAlpha

### CODE REVIEW

**Comment by Trenly** [comment]
> 2023-08-03 19:34:51.211 [FAIL] Installer failed security check. Url: https://github.com/jesseduffield/lazydocker/releases/download/v0.21.1/lazydocker_0.21.1_Windows_x86.zip Result: 0x80004005

**Comment by optsing** [comment]
I don't understand what the problem is. All hashes match the files, x64 and x86 versions are installed correctly from the local manifest.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335141 

image

**Comment by stephengillie** [comment]
This package installed and launched normally in a VM.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
