### PR TITLE
Uplay v112.2

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [X] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2487)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
When running this app, it is hanging my shell.  I have to reboot.  Thoughts?

**Comment by OfficialEsco** [comment]
I just took a new test in Sandbox and everything worked fine, realized my Uplay was outdated so i installed it on my main computer too, everything works fine... 

Is it a VM problem? I know Origin don't like Sandbox, maybe Uplay have a problem with the VM your using?

**Comment by OfficialEsco** [comment]
Just checked in Sandbox and locally, the hash matches, what hash are you getting?
Would be really nice if the bot could spit out the hash when it throws the error

**Comment by KevinLaMS** [comment]
@OfficialEsco I re-run this and it seems to HANG the shell in the Windows VM I am using.  Is there some dependency Issue?  I have to kill the VM.  :(

**Comment by OfficialEsco** [comment]
Weird, what kind of dependency can your VM miss that the Windows Sandbox is loading?

Also how did you validate 112.0 9 days ago if the same installer makes your VM hang?

**Comment by OfficialEsco** [comment]
image
Alright, just tested in a clean Hyper-V VM install, AND it installed without a problem...
Your VM most be broken...

**Comment by KevinLaMS** [comment]
Yeah.  I see it working in sandbox.  I am trying to figure out with dev, why the difference and should I be concerned.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
