### PR TITLE
New package: Xiph.FLAC version 1.4.3

### LINKED ISSUE #151382: [Package Request]: flac
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://xiph.org/flac/download.html
Publisher: Xiph
Package Name: flac
Description: Free Lossless Audio Codec
Package Version: 1.4.3
Installer URL: 
https://github.com/xiph/flac/releases
or
https://ftp.osuosl.org/pub/xiph/releases/flac/

### PR DESCRIPTION
**Pull request by fgimian**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)? No, this particular package requires the 1.9.0 manifest version, see comment below for further information 😄 

Note: `<path>` is the directory's name containing the manifest you're submitting.

Resolves https://github.com/microsoft/winget-pkgs/issues/151382

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/194574)

### CODE REVIEW

**Comment by fgimian** [comment]
> Hello @fgimian,
> 
> One or more of the installer URLs doesn't appear valid.
> 
> This may happen for sites with policies prohibiting distribution or use by third parties.
> 
> This may happen for URLs pointing to domains that do not align with the publisher domain or package domain. If you could provide supporting evidence from the publisher that the URLs for the installer are correct, that would help us to validate and approve this PR.
> 
> Template: msftbot/validationError/urls/domain

Hey there, the links used are those which I'm directed to by the official FLAC site.

1. Browse to https://xiph.org/flac/download.html
2. Under **Windows**, click **FLAC for Windows**
3. You'll be redirected to https://ftp.osuosl.org/pub/xiph/releases/flac/ with the downloads

**Comment by fgimian** [comment]
@stephengillie Hey there, would you kindly let me know what is required for this PR to be merged please?

Thanks heaps
Fotis

**Comment by fgimian** [comment]
@stephengillie Just following this one up again. Is it currently possible to accept this package with the 1.9.0 manifest version or will it have to wait until that's stabalised further?

Kindly let me know if I can provide any further assistance to push it along.

Cheers
Fotis

**Comment by Trenly** [comment]
Reopen with reason: Automation error;

**Comment by Trenly** [comment]
@fgimian - If you update this to 1.9.0 and set the `ArchiveBinariesDependOnPath`, it should work

**Comment by fgimian** [comment]
> @fgimian - If you update this to 1.9.0 and set the `ArchiveBinariesDependOnPath`, it should work

Hey there @Trenly, this PR already uses manifest version 1.9.0 and leverages the ArchiveBinariesDependOnPath option.

Kindly give it another look and let me know if it looks good 😄 

Cheers
Fotis

**Comment by Trenly** [comment]
> > @fgimian - If you update this to 1.9.0 and set the `ArchiveBinariesDependOnPath`, it should work
> 
> Hey there @Trenly, this PR already uses manifest version 1.9.0 and leverages the ArchiveBinariesDependOnPath option.
> 
> Kindly give it another look and let me know if it looks good 😄
> 
> Cheers Fotis

Ah, I didn't see that since the headers still referenced 1.6.0; Will review

**Review by Trenly — APPROVED** [review]

**Comment by fgimian** [comment]
> > > @fgimian - If you update this to 1.9.0 and set the `ArchiveBinariesDependOnPath`, it should work
> > 
> > 
> > Hey there @Trenly, this PR already uses manifest version 1.9.0 and leverages the ArchiveBinariesDependOnPath option.
> > Kindly give it another look and let me know if it looks good 😄
> > Cheers Fotis
> 
> Ah, I didn't see that since the headers still referenced 1.6.0; Will review

Oh let me fix that for you mate, gimme 2 minutes.

**Comment by Trenly** [comment]
> > > > @fgimian - If you update this to 1.9.0 and set the `ArchiveBinariesDependOnPath`, it should work
> > > 
> > > 
> > > Hey there @Trenly, this PR already uses manifest version 1.9.0 and leverages the ArchiveBinariesDependOnPath option.
> > > Kindly give it another look and let me know if it looks good 😄
> > > Cheers Fotis
> > 
> > 
> > Ah, I didn't see that since the headers still referenced 1.6.0; Will review
> 
> Oh let me fix that for you mate, gimme 2 minutes.

No need; they don’t really impact anything other than intellisense

**Comment by fgimian** [comment]
> > > > > @fgimian - If you update this to 1.9.0 and set the `ArchiveBinariesDependOnPath`, it should work
> > > > 
> > > > 
> > > > Hey there @Trenly, this PR already uses manifest version 1.9.0 and leverages the ArchiveBinariesDependOnPath option.
> > > > Kindly give it another look and let me know if it looks good 😄
> > > > Cheers Fotis
> > > 
> > > 
> > > Ah, I didn't see that since the headers still referenced 1.6.0; Will review
> > 
> > 
> > Oh let me fix that for you mate, gimme 2 minutes.
> 
> No need; they don’t really impact anything other than intellisense

Oh oops, just forced pushed that fix for completeness.

```
~\source\winget-pkgs on  Xiph.FLAC-1.4.3-d7a14a5b-ee2b-428b-8731-bb4e85c13e6b [+]
🕙 [ 10:22:23 AM ] ❯ git diffc | cat
diff --git a/manifests/x/Xiph/FLAC/1.4.3/Xiph.FLAC.installer.yaml b/manifests/x/Xiph/FLAC/1.4.3/Xiph.FLAC.installer.yaml
index 1dec2950cad..d5e42434525 100644
--- a/manifests/x/Xiph/FLAC/1.4.3/Xiph.FLAC.installer.yaml
+++ b/manifests/x/Xiph/FLAC/1.4.3/Xiph.FLAC.installer.yaml
@@ -1,5 +1,5 @@
 # Created using wingetcreate 1.6.5.0
-# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
+# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

 PackageIdentifier: Xiph.FLAC
 PackageVersion: 1.4.3
diff --git a/manifests/x/Xiph/FLAC/1.4.3/Xiph.FLAC.locale.en-US.yaml b/manifests/x/Xiph/FLAC/1.4.3/Xiph.FLAC.locale.en-US.yaml
index a3e5cc32a66..3e5ca45f2e7 100644
--- a/manifests/x/Xiph/FLAC/1.4.3/Xiph.FLAC.locale.en-US.yaml
+++ b/manifests/x/Xiph/FLAC/1.4.3/Xiph.FLAC.locale.en-US.yaml
@@ -1,5 +1,5 @@
 # Created using wingetcreate 1.6.5.0
-# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json
+# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

 PackageIdentifier: Xiph.FLAC
 PackageVersion: 1.4.3
diff --git a/manifests/x/Xiph/FLAC/1.4.3/Xiph.FLAC.yaml b/manifests/x/Xiph/FLAC/1.4.3/Xiph.FLAC.yaml
index be547684202..30747e94547 100644
--- a/manifests/x/Xiph/FLAC/1.4.3/Xiph.FLAC.yaml
+++ b/manifests/x/Xiph/FLAC/1.4.3/Xiph.FLAC.yaml
@@ -1,5 +1,5 @@
 # Created using wingetcreate 1.6.5.0
-# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json
+# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

 PackageIdentifier: Xiph.FLAC
 PackageVersion: 1.4.3
``

Here's the `git diff` since the last commit for your reference.

Thanks heaps
Fotis

**Review by Trenly — APPROVED** [review]

**Comment by fgimian** [comment]
@denelon Sorry to tag you in, but this is relatively similar to the PR for the LAME MP3 encoder which you helped me with. The downloads linked to by the official FLAC site technically reside at a different domain. As I mentioned above, the source code and release binaries are also published on GitHub on the official flac repo, so I'm happy to switch to that dowload if it's preferred (they are identical as compared via checksums here), but the website dowlnoad link does direct you to the links I used.

**Comment by fgimian** [comment]
Thank you so much for the merge!

Cheers
Fotis

**Pull request merged**
