### PR TITLE
falkon 3.1.0

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3716)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
I was unable to run the app on my vm due to missing dependency.
image

**Comment by oxygen-dioxide** [comment]
This app isn't developed by me, so I have to wait until the developers add dependencies into this package.

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
@oxygen-dioxide - I think this was resolved with #16102 ?

**Comment by Trenly** [comment]
Close with reason: Resolved by #16102;

**Pull request closed without merging**
