### PR TITLE
Remove old version of JanDeDobbeleer.OhMyPosh

### LINKED ISSUE #20218: RStudio Package Correction
# Description of the new feature/enhancement

RStudio should be renamed RStudio Desktop because they have two versions, RStudio Desktop and RStudio Server.
Even in RStudio Desktop, they have two editions, RStudio Desktop Open-Source and RStudio Desktop Pro.

# Proposed technical implementation details (optional)

Hence, to give a user more detailed information about the package, here is what I think should be correct :
- RStudio.RStudioDesktop.OpenSource
- RStudio.RStudioDesktop.Pro
- RStudio.RStudioServer.OpenSource
- RStudio.RStudioServer.Workbench
Fixes #20226

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----
Fixes #20218

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/20226)

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@denelon Please approve this PR. You can see #20218 to see what I actually wanted to do.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Looks like upon opening the application - it has a dependency on R - so it might need to be temporarily removed from the repository until https://github.com/microsoft/winget-cli/issues/163 is implemented:
image

Clicking "OK" shows this:
image

**Comment by vedantmgoyal2009** [comment]
I have just changed the following:
- PackageName
- PackageIdentifier
- Description
- ShortDescription

Migrated all versions from **RStudio.RStudio** to **RStudio.DesktopOpenSource**

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/20226#pullrequestreview-702345676

**Comment by vedantmgoyal2009** [comment]
They were all pre-existing, don't know why the problem occurs.

> Looks like upon opening the application - it has a dependency on R - so it might need to be temporarily removed from the repository until [microsoft/winget-cli#163](https://github.com/microsoft/winget-cli/issues/163) is implemented:
> image
> 
> Clicking "OK" shows this:
> image

**Comment by vedantmgoyal2009** [comment]
@ItzLevvie does [this](https://github.com/microsoft/winget-pkgs/pull/20226/commits/6946b8b3585caae0d3bd08652e19391274655f34) fix the issue?

**Comment by ItzLevvie** [comment]
> @ItzLevvie does [this](https://github.com/microsoft/winget-pkgs/pull/20226/commits/6946b8b3585caae0d3bd08652e19391274655f34) fix the issue?

Partially. We need to wait for the Windows Package Manager team to add support for dependencies to the client so it can install it.

**Comment by vedantmgoyal2009** [comment]
Okay

**Comment by vedantmgoyal2009** [comment]
@ItzLevvie you can refer to this. no prompt [#20206 (review)](https://github.com/microsoft/winget-pkgs/pull/20226#pullrequestreview-702345676) occurred in my computer.

**Comment by ItzLevvie** [comment]
If you open it up, it'll still require it.

**Comment by vedantmgoyal2009** [comment]
Please recheck 🙏🏻

**Comment by vedantmgoyal2009** [comment]
No, it is opening successfully.

**Comment by vedantmgoyal2009** [comment]
See here: 
image

**Comment by ItzLevvie** [comment]
Will check it out.

**Comment by ItzLevvie** [comment]
Did another install - Windows Package Manager doesn't install the R dependency, it only installs RStudio, you manually installed it on your machine which is why it works fine for you.

**Comment by vedantmgoyal2009** [comment]
That means adding these flags is of no use.
``` 
Dependencies:
  PackageDependencies:
  - PackageIdentifier: RProject.R
    MinimumVersion: 4.1.0
```

**Comment by vedantmgoyal2009** [comment]
@denelon what do you say, should it be removed or not?

**Comment by denelon** [comment]
I'll mark it as blocked so we can approve once dependency support is in place. It might still require some minor changes depending on how "dependency" support lands, but at least this work to build this manifest can be retained.

**Comment by cderv** [comment]
I am ending up here because I was surprised to see that the RStudio IDE manifest has been removed and I wanted to understand why. 

Unfortunately, I am not sure to understand the rationale. As an R user, I contributed the manifest in the first place because I am using `winget` to install those versions on my system. And now I can't anymore. 

RStudio IDE is a tool to use with R. You would not do `winget install` to install RStudio IDE if you did plan to install R also. You can install both with `winget` even if the dependency mechanism is not in place in the client. It is just two step instead of one. Why prevent current user to be able to install this software in the meantime ? 

It was working perfectly as of now even if the dependency mechanism you are mentioning is not yet in place. 

I see [Pycharm](https://github.com/microsoft/winget-pkgs/tree/master/manifests/j/JetBrains/PyCharm) is still there in this repo and this is an IDE for python. You can really use Pycharm without Python installed. So you would need to install Python then Pycharm, until the dependency mechanism is there. 

Maybe I am missing something obvious... 

Anyway, I am happy to help get those manifest back online. It took me time to create the previous one with current rule at the times. It is sad to see this work removed...

Thanks !

**Comment by denelon** [comment]
@cderv I'm not familiar with the dependencies between R and RStudio. Currently we block manifests for packages that have "Install time" dependencies rather than "run time" dependencies. We are actively working on dependency support, but it's not ready yet. We validate on a "clean" VM with no dependencies installed so we can validate a successful install. 

I don't know which PR(s) removed one or both of the packages. If either one can successfully install with our current policies (no install time dependencies, no UI required for install) then they should be able to validate for inclusion.

**Comment by ItzLevvie** [comment]
cc @cderv: It was removed due to run-time dependencies as when I installed it, there was no way to use the application without R installed and there was also no way to skip installing R.

Pycharm is fine because there's no run-time dependencies there, it doesn't force you to install Python before using it.

@palenshus said several days ago that run-time dependencies are allowed, but not install-time dependencies so I was going to reupload all of the RStudio manifests but was a bit busy, so you can go ahead and do that.

**Comment by cderv** [comment]
Thanks for the precisions @denelon and @ItzLevvie !

I can confirm RStudio IDE have no install time dependency. The installation should pass on your clean VM. I don't have one to test that but it should. 

However, RStudio IDE is an IDE mainly for R and yes it requires R to be found so that it can be used. Mainly because it is not useful otherwise for now. Same way I would not install Pycharm to use it except with Python - that is why I made the comparaison. I understand that RStudio IDE is blocking the opening, where Pycharm is not. This is interesting feedback !

About the reupload, I understand from this PR that a renaming is required and the previous manifest are not up to date with that ? If so, they can't be restored as is and need to be updated in the process. Maybe the pycharm folder organization is the one to follow ?

**Comment by vedantmgoyal2009** [comment]
Can't we simply merge this PR? Only the problem is that it contains multiple manifests, so during Validation, it throws 'PullRequest-Error'

**Comment by cderv** [comment]
@vedantmgoyal2009 From the contribution guide in README (https://github.com/microsoft/winget-pkgs#authoring-a-manifest) this is one manifest per PR so it needs to be split in several PR I think.

I believe this is important for auto validation process which knows how to handle one manifest per PR..

**Comment by vedantmgoyal2009** [comment]
Well, then I have to create manifests again.. Will do it!

**Comment by ItzLevvie** [comment]
> About the reupload, I understand from this PR that a renaming is required and the previous manifest are not up to date with that ? If so, they can't be restored as is and need to be updated in the process. Maybe the pycharm folder organization is the one to follow ?

Yep, it'll have to follow a similar folder structure to PyCharm (i.e. RStudio.OpenSource & RStudio.Pro or something along those lines).

This PR also has a spelling error: https://github.com/microsoft/winget-pkgs/pull/20226/files#diff-9be3a39684c7086b1a54f341a8f5cac487f06b0d6168aa4c058cc5b6d3d8d2b1R3

**Comment by vedantmgoyal2009** [comment]
Now, I am closing this PR as Levvie will make new manifests from scratch.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
