### PR TITLE
Updated ElectronicArts.EADesktop to v12.0.89.4920

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15890)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
I seem to be getting a user interaction prompt. Is this happening to you? It doesn't install until I press the "Let's Go" button.
image

**Comment by OfficialEsco** [comment]
I actually had this issue yesterday too, was about to delete the manifest, tested tons of switches, nothing worked, reset to clean state, found switches for EULA, booted up and ran with the the EULA switch, successful, ran it without the EULA switch to test, somehow worked, rebooted to clean state, ran it without EULA switch, still worked...

**Comment by OfficialEsco** [comment]
@ItzLevvie try now, i have no idea if this is placebo or not anymore
```
PS C:\Users\Esco> winget install -m M:\e\ElectronicArts\EADesktop\12.0.92.4925\
Found EA Desktop [ElectronicArts.EADesktop]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EADesktopInstaller.exe
  ██████████████████████████████  1.21 MB / 1.21 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

**Review by ItzLevvie — APPROVED** [review]
image

**Comment by mddtest** [comment]
@OfficialEsco Just a thought should we add the Beta header since EA still has the Desktop in Open Beta.

**Comment by OfficialEsco** [comment]
> @OfficialEsco Just a thought should we add the Beta header since EA still has the Desktop in Open Beta.

There is nowhere to put Beta.

**Pull request merged**
