### PR TITLE
Remove: MindsetInnovationInc.Enowork version 0.6.2

### PR DESCRIPTION
**Pull request by SIDNut**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/90720)

### CODE REVIEW

**Comment by Trenly** [comment]
@SIDNut - Is there a reason these packages are being removed?

**Comment by SIDNut** [comment]
Company is closing down, so the servers will too.

**Comment by SIDNut** [comment]
@Trenly Company is closing and file source will become unavailable.

**Review by SIDNut — COMMENTED** [review]
Company is closing and file source will become unavailable.

**Review by SIDNut — COMMENTED** [review]
Company is closing. Source will become unavailable.

**Comment by mdanish-kh** [comment]
Please see https://github.com/microsoft/winget-pkgs/pull/90718#issuecomment-1346263239

**Comment by stephengillie** [comment]
Source still available.

**Pull request closed without merging**
