### PR TITLE
Add MyMoney manifest

### PR DESCRIPTION
**Pull request by clovett**
See https://github.com/clovett/MyMoney.Net

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1123)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
The installer fails.  8007000D Opening the package from location LovettSoftware.Mymoney.Net1.1.60 failed.

**Comment by clovett** [comment]
I give up.  It installs fine manually from this link:
http://lovettsoftware.com/Downloads/MyMoney.Net/index.html

How does one create a proper winget manifest for this app ?

**Comment by lovettchris** [comment]
Ok, trying one more time, this time I copied the way xmlnotepad is setup, so hopefully this time my URL and has are correct.  When I download the file `MoneyPackage_1.1.61.0_AnyCPU_Debug.msixbundle` and run it locally it installs fine.  Perhaps my mistake was trying to point to the `MoneyPackage.appinstaller` instead...

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
