### PR TITLE
GiulioSorrentino.numeronesoeminformations version 1.1.1

### PR DESCRIPTION
**Pull request by GiulianoSpaghetti**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140374)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 794.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-21 08:11:27.489 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-21 08:12:00.128 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-21 08:12:11.606 [FAIL] Installer failed security check. Url: https://github.com/numerunix/numoeminformations/releases/download/1.1.1/numoeminformations-1.1.1-x64.msi Result: 0x80004005 2024-02-21 08:12:11.607 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (0C:24) [08:11:39:146]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (0C:24) [08:11:40:547]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg MSI (s) (0C:24) [08:11:44:860]: Windows Installer installed the product. Product Name: Microsoft .NET Runtime - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (0C:5C) [08:11:46:751]: Windows Installer installed the product. Product Name: Microsoft .NET Host FX Resolver - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (0C:90) [08:11:47:563]: Windows Installer installed the product. Product Name: Microsoft .NET Host - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (0C:2C) [08:11:52:641]: Windows Installer installed the product. Product Name: Microsoft Windows Desktop Runtime - 8.0.2 (x64). Product Version: 64.8.8806. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 794.)

**Comment by numerunix** [comment]
I think that the problem is always the same: it's not signed so it's stopped by windows defender.

**Comment by stephengillie** [comment]
> I think that the problem is always the same: it's not signed so it's stopped by windows defender.

This is possible - it might become flagged for closer review. I haven't worked with anyone on Defender so I'm only guessing.

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 812.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-22 21:52:07.111 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-22 21:52:52.564 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-22 21:53:07.190 [FAIL] Installer failed security check. Url: https://github.com/numerunix/numoeminformations/releases/download/1.1.1/numoeminformations-1.1.1-x64.msi Result: 0x80004005 2024-02-22 21:53:07.190 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (FC:F8) [21:52:21:664]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (FC:F8) [21:52:23:805]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg MSI (s) (FC:F8) [21:52:25:914]: Windows Installer installed the product. Product Name: Microsoft .NET Runtime - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (FC:BC) [21:52:26:976]: Windows Installer installed the product. Product Name: Microsoft .NET Host FX Resolver - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (FC:3C) [21:52:30:914]: Windows Installer installed the product. Product Name: Microsoft .NET Host - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (FC:D8) [21:52:40:773]: Windows Installer installed the product. Product Name: Microsoft Windows Desktop Runtime - 8.0.2 (x64). Product Version: 64.8.8806. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 812.)

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 813.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-23 11:36:16.495 [CLI ] Installer [Arm64,burn,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-23 11:36:39.748 [CLI ] Installer [Arm64,wix,Unknown,] not applicable: Machine is not compatible with Arm64 2024-02-23 11:36:53.015 [FAIL] Installer failed security check. Url: https://github.com/numerunix/numoeminformations/releases/download/1.1.1/numoeminformations-1.1.1-x64.msi Result: 0x80004005 2024-02-23 11:36:53.015 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6 MSI (s) (B8:7C) [11:36:26:271]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1) MSI (s) (B8:7C) [11:36:27:458]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,) Property(S): ErrorDialog = ErrorDlg MSI (s) (B8:7C) [11:36:27:677]: Windows Installer installed the product. Product Name: Microsoft .NET Runtime - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (B8:38) [11:36:28:255]: Windows Installer installed the product. Product Name: Microsoft .NET Host FX Resolver - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (B8:48) [11:36:28:974]: Windows Installer installed the product. Product Name: Microsoft .NET Host - 8.0.2 (x64). Product Version: 64.8.8795. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (B8:7C) [11:36:33:240]: Windows Installer installed the product. Product Name: Microsoft Windows Desktop Runtime - 8.0.2 (x64). Product Version: 64.8.8806. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 813.)

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 821.)

**Comment by numerunix** [comment]
Hello there, i think there is a smart screen error

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 855.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-02-28 07:57:50.303 [FAIL] Installer failed security check. Url: https://github.com/numerunix/numoeminformations/releases/download/1.1.1/numoeminformations-1.1.1-x64.msi Result: 0x80004005
> MSI (s) (18:F4) [07:57:07:137]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1)
> MSI (s) (18:F4) [07:57:08:621]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,)
> Property(S): ErrorDialog = ErrorDlg

(Automated response - build 855.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
