### PR TITLE
Modify: JetBrains.Rider version 2024.1.1

### PR DESCRIPTION
**Pull request by SpecterShell**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150701)

### CODE REVIEW

**Comment by 2505lis** [comment]
Одобряю

**Comment by 2505lis** [comment]
Одобряю

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
