### PR TITLE
New package: Rizin.Cutter in version 2.2.1

### PR DESCRIPTION
**Pull request by assarbad**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

xref: https://github.com/rizinorg/cutter/issues/3056
 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/109817&drop=dogfoodAlpha

### CODE REVIEW

**Comment by assarbad** [comment]
@microsoft-github-policy-service agree

**Review by stephengillie — APPROVED** [review]

**Comment by Trenly** [comment]
@stephengillie / @denelon - I'm not sure the Validation-Executable-Error should have been waived here.

Although it may install and run fine on Windows 11, on Windows 10 machines it has a dependency on MSVCP140 and VCRUNTIME140_1 and VCRUNTIME140 - that is to say, has a dependency on `Microsoft.VCRedist.2015+.x64`

image
image

After installing the dependency on Win10, it runs fine -
image

**Comment by denelon** [comment]
@Trenly We validate on Windows 11 by default unless the minimum OS version specifies Windows 10 if I'm not mistaken.

**Comment by denelon** [comment]
Let me confirm with the team.

**Comment by Trenly** [comment]
Confirmed with @denelon the Pipelines run Win10 by default and Win11 only if specified - It's possible that manual validation uses Win11 instead of Win10

**Comment by denelon** [comment]
Sorry for the delay. I was offline for some mandatory in person training.

I was wrong.

We default to a Windows 10 VM during validation unless the manifest states a requirement for Windows 11.

It appears not all users who were performing manual validation were also defaulting to a Windows 10 VM. This will be communicated to the team today and added to our process documentation.

**Comment by assarbad** [comment]
Could you explain in brief how this affects future contributions? Is there a way to express the dependency on `Microsoft.VCRedist.2015+.x64`?

Thanks anyway for pointing it out!

**Comment by denelon** [comment]
We don't yet have support for dependencies as a stable feature. We're still looking at a few challenges related to reboots that can get triggered by dependencies being upgraded. Yes, the dependency can be identified in the manifest, but we're holding off on accepting packages that fail during install if the dependency isn't present.

**Comment by assarbad** [comment]
> We don't yet have support for dependencies as a stable feature. We're still looking at a few challenges related to reboots that can get triggered by dependencies being upgraded. Yes, the dependency can be identified in the manifest, but we're holding off on accepting packages that fail during install if the dependency isn't present.

Shame, but thanks so much for the clarification!

**Comment by denelon** [comment]
I've got it in the 1.6 milestone so we're aiming for September.

**Comment by XVilka** [comment]
@assarbad @Trenly you might be interested in https://github.com/microsoft/winget-pkgs/issues/115801

BTW, if something is needed from our side - please let us know by opening an issue at https://github.com/rizinorg/cutter/issues

**Pull request merged**
