### PR TITLE
Add TeamViewer 15.10.5.0

### PR DESCRIPTION
**Pull request by dumontirou**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [X] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3896)

### CODE REVIEW

**Comment by dumontirou** [comment]
Hello @KevinLaMS 
I may have an idea of where the problem's coming from : have you tried installing it with admin privileges ?
I encountered the following error when I tried to install it as an ordinary user : 

> **Installer failed with exit code: 2**

**Comment by KevinLaMS** [comment]
Duplicate of #4150 can we close?

**Comment by dumontirou** [comment]
> 
> 
> Duplicate of #4150 can we close?

Yes and thank you for updating it ;)

**Comment by OfficialEsco** [comment]
@dumontirou you can close it your self btw or @KevinLaMS if he reacts to the mention

**Pull request closed without merging**
