### PR TITLE
Add claudetozenn

### PR DESCRIPTION
**Pull request by nuitsjp**
Checklist for Pull Requests
- [ x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ x] This PR only modifies one (1) manifest
- [ x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/176637)

### CODE REVIEW

**Comment by nuitsjp** [comment]
@microsoft-github-policy-service agree

**Review by stephengillie — CHANGES_REQUESTED** [review]
Hi @nuitsjp,

Manual Validation ended with:
image

**Comment by nuitsjp** [comment]
Hi @stephengillie.
Thanks for the excellent point.
I didn't know such a description was possible. We have applied it.

Please review again.

**Comment by nuitsjp** [comment]
Hi @stephengillie 
I have raised the MinimumOSVersion to 10.0.22621.0.
NET Framework 4.8.1 should then be included by default, so I removed the description of Microsoft.DotNet.Framework.DeveloperPack_4. Is this a problem?

**Comment by nuitsjp** [comment]
I am able to install locally, but I don't know why I am getting an error.Is it possible to provide log details?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Signature Update Failed.
> Failure to parse win 10, attempting win 11
> Installation failed with exit code -1978335216

Automated error analysis suggests -1978335216 may mean None of the installers are applicable for the current system

(Automated response - build 896.)

**Comment by stephengillie** [comment]
> Hi @ stephengillie I have raised the MinimumOSVersion to 10.0.22621.0. NET Framework 4.8.1 should then be included by default, so I removed the description of Microsoft.DotNet.Framework.DeveloperPack_4. Is this a problem?

I'm still getting this message:
image

**Comment by nuitsjp** [comment]
@stephengillie 
NET Framework 4.8 in the modified version 0.0.13.
Please make sure that the version you have installed is 0.0.13.

**Comment by stephengillie** [comment]
Hi @nuitsjp,

Please understand that my scripts just download the manifest into a VM and run it, then open all changed executables and run a Defender scan. You're controlling the version that I am installing. 

This is unchanged: 
> I'm still getting this message: image

**Comment by nuitsjp** [comment]
@stephengillie 
Sorry.
Indeed my installer was not properly updated.
It should work with this update.

Please confirm that it works as follows.
Type two lines in the console with the appropriate values and verify that you get an error.

```pwsh
PS C:\Users\nuitsjp\AppData\Local\ClaudeToZenn> . \ClaudeToZenn.exe
1
2
... {“IsSuccess”:false, “Exception”: “The JSON value could not be converted to ClaudeToZenn.Request. Path: $ | LineNumber: 0 | BytePositionInLine: 1.”}
````

This application is used by Native Messaging from Chrome Extension, so it is difficult to run a test that terminates successfully on its own.

Thank you in advance.

Translated with www.DeepL.com/Translator (free version)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-10-04 16:09:50.676 [FAIL] Installer failed security check. Url: https://github.com/nuitsjp/ClaudeToZenn/releases/download/v0.0.18/ClaudeToZenn-0.0.18-setup.exe Result: 0x80004005

(Automated response - build 896.)

**Comment by nuitsjp** [comment]
I have no direct means of resolving that issue at this time.
Therefore, this PR is closed.
I appreciate your cooperation!

**Comment by nuitsjp** [comment]
I heard that the problem will be resolved after a certain period of time.
If there is no problem, please let it stay Open for a while.

**Comment by stephengillie** [comment]
Verify:
image
I wasn't able to find how to have the application display its version number.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
