### PR TITLE
New version: maximmax42.CustomRP version 1.16.10

### PR DESCRIPTION
**Pull request by maximmax42**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/84452)

### CODE REVIEW

**Comment by maximmax42** [comment]
?????
It installs just fine.

**Review by Trenly — DISMISSED** [review]

**Comment by Trenly** [comment]
> ????? It installs just fine.

```
2022-10-16 15:09:57.846 [FAIL] Installer failed security check. Url: https://github.com/maximmax42/Discord-CustomRP/releases/download/1.16.10/CustomRP.1.16.10.exe Result: 0x80004005
```

**Comment by maximmax42** [comment]
> ```
> 2022-10-16 15:09:57.846 [FAIL] Installer failed security check. Url: https://github.com/maximmax42/Discord-CustomRP/releases/download/1.16.10/CustomRP.1.16.10.exe Result: 0x80004005
> ```

Well that's really vague. No idea what's causing this. I asked multiple people to check if the installer works (can't check it myself until later tomorrow), and they all said everything installs just fine.

**Comment by maximmax42** [comment]
Asked someone to do a clean install via Sandboxie, thought maybe it fails to do a clean install rather than an upgrade - nope, works just fine. Seems to be an issue with Azure?

**Comment by maximmax42** [comment]
Apparently for some people Windows Defender is finding some sort of trojan in the installer, I'm certain it's a false positive. What do I do here?

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
