### PR TITLE
Microsoft.Git version 2.47.0.0.3

### PR DESCRIPTION
**Pull request by ldennington**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/185315)

### CODE REVIEW

**Comment by dscho** [comment]
@stephengillie would you mind giving this PR a little nudge? It comes soon after the 2.47.0.0.2 release, with an important fix.

**Comment by dscho** [comment]
@stephengillie does this need the <kbd>Moderator-Approved</kbd> label, like in [this PR](https://github.com/microsoft/winget-pkgs/pull/184159#issuecomment-2422926641)?

**Review by ItzLevvie — APPROVED** [review]

**Comment by dscho** [comment]
> @wingetbot run

@ItzLevvie I think the validation is _supposed_ to fail, see [this comment](https://github.com/microsoft/winget-pkgs/pull/184159#issuecomment-2422926641).

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Pull request merged**
