### PR TITLE
FilesCommunity.FilesPreview version 3.7.13.0

### PR DESCRIPTION
**Pull request by Josh65-2201**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/192238)

### CODE REVIEW

**Comment by Josh65-2201** [comment]
This will have the VClib issue like https://github.com/microsoft/winget-pkgs/pull/184766 and will need to be manually validated

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334972
> 2024-11-18 14:37:58.408 [CORE] Deployment operation #2: Windows cannot install package FilesPreview_3.7.13.0_x64__1y0xx7n9077q4 because this package depends on a framework that could not be found. Provide the framework "Microsoft.WindowsAppRuntime.1.5" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 5001.311.2039.0, along with this package to install. The frameworks with name "Microsoft.WindowsAppRuntime.1.5" currently installed are: {Microsoft.WindowsAppRuntime.1.5_5001.275.500.0_x64__8wekyb3d8bbwe Microsoft.WindowsAppRuntime.1.5_5001.275.500.0_x86__8wekyb3d8bbwe}
> 2024-11-18 14:37:58.408 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!00007FFBDEB53F75: (caller: 00007FFBDEAAA720) Exception(2) tid(17f8) 80073CF3 Package failed updates, dependency or conflict validation.
> 2024-11-18 14:37:58.522 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFBDEB52D2F: (caller: 00007FFBDEB5432C) Exception(3) tid(17f8) 80073CF1 Package was not found.
> 2024-11-18 14:37:58.523 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(126)\WindowsPackageManager.dll!00007FFBDECC8931: (caller: 00007FFBDEB55853) LogHr(2) tid(17f8) 80073CF1 Package was not found.
>     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFBDEB52D2F: (caller: 00007FFBDEB5432C) Exception(3) tid(17f8) 80073CF1 Package was not found.
> 2024-11-18 14:37:58.533 [CLI ] MSIX installer failed: 2147958003

Automated error analysis suggests -1978334972 may mean This package has a dependency missing from your system.

Automated error analysis suggests 2147958003 may mean Error Installing Dependency - Windows cannot install this package because it depends on a framework (version) that could not be found.

(Automated response - build 897.)

**Comment by Josh65-2201** [comment]
@stephengillie can you manually validate this like you did for the stable version of Files.

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-11-19 12:20:25.339 [CLI ] MSIX installer failed: 2147958003 12:20:25 PM:  finished with exit code: -1978334972  

Automated error analysis suggests -1978334972 may mean This package has a dependency missing from your system. 

Automated error analysis suggests 2147958003 may mean Error Installing Dependency - Windows cannot install this package because it depends on a framework (version) that could not be found.

(Automated response - build 897.)

**Comment by Josh65-2201** [comment]
I see it that WinAppSDK 1.5.8 isn't on here, is the someone that normal adds them or should I add it?

**Comment by Josh65-2201** [comment]
Closing as 3.8.0.0 will be released in a few days, the should be less preview update after too.

**Pull request closed without merging**
