### PR TITLE
Kiwix.KiwixJS version 2.0.9.0

### PR DESCRIPTION
**Pull request by Jaifroid**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/64672)

### CODE REVIEW

**Comment by Jaifroid** [comment]
No problem installing the package here:

image

**Comment by Jaifroid** [comment]
I can't reproduce this install failure locally. I have already tried closing and re-opening this PR.

image

**Comment by Jaifroid** [comment]
@ItzLevvie Can you flag this for a dev to look at? It's failing validation, but it installs fine from the manifest locally with no errors. I've tried closing and re-opening this PR three times now.

**Review by ItzLevvie — APPROVED** [review]
Azure Pipelines is seeing this error message:
```
2022-06-28 23:58:58.798 [CORE] Deployment operation #0: error 0x800B0110: Opening the package from location KiwixWebApp_2.0.9.0_AnyCPU.appxbundle failed.
2022-06-28 23:58:58.798 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(159)\WindowsPackageManager.dll!00007FF90FB97684: (caller: 00007FF90FB295E5) Exception(1) tid(60c) 800B0110 The certificate is not valid for the requested usage.

2022-06-28 23:58:58.800 [CORE] Starting RemovePackage operation #1: Kiwix.KiwixJS_2.0.9.0_neutral_~_qwjmsdmcnwx12
2022-06-28 23:58:58.815 [CORE] Begin waiting for operation #1
2022-06-28 23:58:58.815 [CORE] Begin blocking for operation #1
2022-06-28 23:58:58.933 [CORE] Deployment operation #1: Windows cannot remove Kiwix.KiwixJS_2.0.9.0_neutral_~_qwjmsdmcnwx12 because the current user does not have that package installed. Use Get-AppxPackage to see the list of packages installed.
2022-06-28 23:58:58.935 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FF90FB9657A: (caller: 00007FF90FB97966) Exception(2) tid(60c) 80073CF1 Package was not found.
    Msg:[Operation failed: Windows cannot remove Kiwix.KiwixJS_2.0.9.0_neutral_~_qwjmsdmcnwx12 because the current user does not have that package installed. Use Get-AppxPackage to see the list of packages installed.] 

2022-06-28 23:58:58.935 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(124)\WindowsPackageManager.dll!00007FF90FCE92EE: (caller: 00007FF90FB97A03) LogHr(1) tid(60c) 80073CF1 Package was not found.
    Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FF90FB9657A: (caller: 00007FF90FB97966) Exception(2) tid(60c) 80073CF1 Package was not found.
    Msg:[Operation failed: Windows cannot remove Kiwix.KiwixJS_2.0.9.0_neutral_~_qwjmsdmcnwx12 because the current user does not have that package installed. Use Get-AppxPackage to see the list of packages installed.] 
] 

2022-06-28 23:58:58.940 [CLI ] MSIX installer failed: 2148204816
2022-06-28 23:58:58.944 [CLI ] Terminating context: 0x800b0110 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:15d
```

**Comment by Jaifroid** [comment]
@ItzLevvie Thanks for taking a look. As it's still failing, and it is signalling some kind of certificate error, I'll try rebuilding the package, in case there was some issue I didn't detect during signing. What is confusing is that it installs fine on my machine, with no certificate complaint.

**Pull request closed without merging**
