### PR TITLE
New version: nkdAgility.AzureDevOpsMigrationTools.Preview version 15.0.0-Preview.267

### PR DESCRIPTION
**Pull request by MrHinsh**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/139835)

### CODE REVIEW

**Comment by MrHinsh** [comment]
Is there more details? This works for me locally.

**Comment by stephengillie** [comment]
Hi @MrHinsh,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 792.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-17 10:28:31.086 [FAIL] Installer failed security check. Url: https://github.com/nkdAgility/azure-devops-migration-tools/releases/download/v15.0.0-Preview.267/MigrationTools-15.0.0-Preview.267.zip Result: 0x80004005 2024-02-17 10:28:31.086 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6

(Automated response - build 792.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
