### PR TITLE
Modify: Spotify.Spotify version 1.1.96.785.g464c973a

### PR DESCRIPTION
**Pull request by SpecterShell**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/79966)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
Close with reason: Replaced by PR 80581;

**Comment by SpecterShell** [comment]
> Close with reason: Replaced by PR 80581;

Could you reopen this PR? I don't think this PR is needed to be replaced.

**Comment by SpecterShell** [comment]
@ItzLevvie

**Comment by ItzLevvie** [comment]
cc @denelon: This PR needs to be re-opened.

It replaces the non-versioned URL (which always points to the latest version) with the versioned URL.

**Comment by ItzLevvie** [comment]
@msftbot reset feedback

**Review by ItzLevvie — DISMISSED** [review]

**Review by Trenly — APPROVED** [review]

**Pull request merged**
