### PR TITLE
Prevent auto restart after LibreOffice install

### LINKED ISSUE #1154: LibreOffice - Reboot after installation
# Description of the problem

I installed an update to LibreOffice via winget and my PC just rebooted without a warning after the installation finished. Luckily I didn't had any important work opened.

# Proposed technical implementation details

Don't force reboots, but if a reboot is necessary, there should be a warning, so you have time to react.

### PR DESCRIPTION
**Pull request by SoftCreatR**
n/t

Resolves #1154

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1210)

### CODE REVIEW

**Review by Reset816 — DISMISSED** [review]

**Review by noxifoxi — DISMISSED** [review]

**Comment by Reset12138** [comment]
why you close the PR? It has't been merged.

**Comment by SoftCreatR** [comment]
> why you close the PR? It has't been merged.

Accident ;)

**Comment by noxifoxi** [comment]
Why does it take so long for this to get merged? 🤨

**Comment by SoftCreatR** [comment]
Well, that applies for most PRs. I have no idea, why it takes so long.

**Comment by KevinLaMS** [comment]
I get Installer failed with exit code 1603

**Comment by SoftCreatR** [comment]
I don't 😁

**Comment by SoftCreatR** [comment]
> 1603

From https://support.microsoft.com/en-us/help/834484/you-receive-an-error-1603-a-fatal-error-occurred-during-installation:

You may receive this error message if any one of the following conditions is true:
- Windows Installer is attempting to install an app that is already installed on your PC.
- The folder that you are trying to install the Windows Installer package to is encrypted.
- The drive that contains the folder that you are trying to install the Windows Installer package to is accessed as a substitute drive.
- The SYSTEM account does not have Full Control permissions on the folder that you are trying to install the Windows Installer package to. You notice the error message because the Windows Installer service uses the SYSTEM account to install software.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
