### PR TITLE
NETFoundation.WiXToolset version 3.11.2.4516

### PR DESCRIPTION
**Pull request by ryfu-msft**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/96043)

### CODE REVIEW

**Comment by Trenly** [comment]
Dependent upon .NET Framework 3.5

https://github.com/microsoft/winget-pkgs/pull/895

**Comment by ryfu-msft** [comment]
> Dependent upon .NET Framework 3.5 image
> 
> * [Add WiXToolset 3.11.2 #895](https://github.com/microsoft/winget-pkgs/pull/895)
> * [WiXToolset.WiXToolset version 3.11.2.4516 #23647](https://github.com/microsoft/winget-pkgs/pull/23647)
> * [NETFoundation.WixToolset version 3.11.2 #25268](https://github.com/microsoft/winget-pkgs/pull/25268)
> * [NETFoundation.WiXToolset version 3.11.2 #58825](https://github.com/microsoft/winget-pkgs/pull/58825)
> * [NETFoundation.WiXToolsetv3 version 3.11.2.4516 #65900](https://github.com/microsoft/winget-pkgs/pull/65900)
> * [Add: WiX Toolset #89819](https://github.com/microsoft/winget-pkgs/pull/89819)

Ah, thanks for the links, was wondering why this package didn't exist yet...

**Comment by Trenly** [comment]
[Policy] Dependencies;

Leaving this  note for time travelers - I'd like to leave this open to track for WiXToolset since the other PR is so out of date. I think having a cleaner manifest to work off of once Windows Features can make it into the dependencies flow will be better in the long run. I know we typically defer to the older issue, but I believe this case to be a reasonable exception.

**Comment by bevancollins** [comment]
https://wixtoolset.org/docs/about/#license

**Pull request closed without merging**
