### PR TITLE
Rinrab.AOVpnManager version 0.1.0

### PR DESCRIPTION
**Pull request by rinrab**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132984)

### CODE REVIEW

**Comment by rinrab** [comment]
@microsoft-github-policy-service agree

**Review by OfficialEsco — COMMENTED** [review]
> An anti-virus product reports an infection in the installer

**Comment by rinrab** [comment]
> An anti-virus product reports an infection in the installer

That's because I don't have certificate to sign my build.

Is it important to add my application to winget?

**Comment by OfficialEsco** [comment]
Unsure how installer signing works, but i keep seeing other installer which is just blocked by smart screen and they go trough the validation (mby they got certificate but not validated with MS?), this installer is just straight up blocked, i won't approve the package but it did go trough validation so ill let someone else deal with it =)

**Pull request closed without merging**
