### PR TITLE
New version: Microsoft.Skype version 8.112.0.206

### PR DESCRIPTION
**Pull request by PckgrBot**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137559)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @PckgrBot,

> This PR's version number 8.112.0.206 has 4 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version 8.112, which has 2 parameters.

Is this intentional?

(Automated response - build 694)

**Review by stephengillie — APPROVED** [review]

**Comment by mdanish-kh** [comment]
@PckgrBot -

Unfortunately, this was not the correct version, and it's causing issues for users (infinite upgrade scenario). The PackageVersion field must match whatever is written to Control Panel / Apps&Features after installation. In this case, the actual version report to Registry / Control Panel / Apps&Features is `8.112`. See -

image

I'll create a PR to fix this issue

**Comment by mdanish-kh** [comment]
@PckgrBot -

Unfortunately, this was not the correct version, and some users are starting to face the "infinite upgrade" issue. The PackageVersion field must match whatever is written to Control Panel / Apps&Features after installation. In this case, the actual version report to Registry / Control Panel / Apps&Features is `8.112`. See -

image

I'll create a PR to fix this issue

**Comment by t-matsuu** [comment]
InstallerUrl in Microsoft.Skype.installer.yaml still sets as 8.112.0.203.

**Pull request merged**
