### PR TITLE
EpicPrivacyBrowser.EpicPrivacyBrowserInstaller version 1.3.29.13

### PR DESCRIPTION
**Pull request by sarvex**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/102503)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
Unexpected Behaviour when I run /? or /Help. 
Screenshot (194)

**Comment by stephengillie** [comment]
Automatic Validation failed with:
InstallationVerification-x86-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20230414081151

I'm not exactly sure what occurred here.

**Comment by stephengillie** [comment]
Hi @sarvex,

The installation isn't unattended:
image

Is there an installer switch to bypass this and have it complete installing automatically?

**Comment by sarvex** [comment]
@stephengillie @BrandonWanHuanSheng 

The installer is an EXE file to download the Browser, and the error comes whenever any parameter is passed to the installer. 

I kept the silent options as empty but it seems that winget is still passing empty strings to the installer.

**Comment by stephengillie** [comment]
> @stephengillie @BrandonWanHuanSheng
> 
> The installer is an EXE file to download the Browser, and the error comes whenever any parameter is passed to the installer.
> 
> I kept the silent options as empty but it seems that winget is still passing empty strings to the installer.

Without any options, it installs normally, but requires clicking "Close" to complete. Is there a way to skip that "Close" button and have it close automatically?

**Comment by sarvex** [comment]
@stephengillie unfortunately there is no documentation on the installer flags so there is not way to make it truely unattended

**Comment by sarvex** [comment]
There seems to be no option for non-interactive installation. Let's discard the PR

**Pull request closed without merging**
