### PR TITLE
New package: NewCloud.WakeOnLan version 1.0

### PR DESCRIPTION
**Pull request by haohuancheng**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/128270)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
InstallationVerification-x86-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20231127180950

**Comment by stephengillie** [comment]
Hi @haohuancheng,

Does this package have a dependency?

**Comment by haohuancheng** [comment]
Hi:

 

No any dependency.

 

My program only has one wakeolan.exe to work, which is used to implement network wake-up function. However, whether submitted directly or packaged as a zip file, the wingetcreate new command does not display correctly during execution and cannot proceed. Could it be due to the file being too small? So I added another file inside, and the wingetcreate new was approved.

Can you tell me the basic parameters of XML when only submitting independent and uninstalled exe programs?

 

Thank you!

 

 

发件人: Stephen Gillie ***@***.***> 
发送时间: 2023年11月29日 7:10
收件人: microsoft/winget-pkgs ***@***.***>
抄送: NewCloud ***@***.***>; Mention ***@***.***>
主题: Re: [microsoft/winget-pkgs] New package: NewCloud.WakeOnLan version 1.0 (PR #128270)

 

Hi @haohuancheng <https://github.com/haohuancheng> ,

Does this package have a dependency?

**Comment by haohuancheng** [comment]
Wakeonlan.exe is the program.

The other files are redundant, but if not, they cannot be passed, so we have to add them.

 

发件人: Stephen Gillie ***@***.***> 
发送时间: 2023年11月29日 7:07
收件人: microsoft/winget-pkgs ***@***.***>
抄送: NewCloud ***@***.***>; Assign ***@***.***>
主题: Re: [microsoft/winget-pkgs] New package: NewCloud.WakeOnLan version 1.0 (PR #128270)

 

Automatic Validation ended with:
InstallationVerification-x86-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20231127180950.png (view on web) <https://github.com/microsoft/winget-pkgs/assets/114952565/ca5f4312-2375-4099-bad6-5f32c9e64f00>

**Pull request closed without merging**
