### PR TITLE
New Package: Ngrok.Ngrok version 3.5.0

### PR DESCRIPTION
**Pull request by nmontesinoc**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/152056)

resolves #152054

### CODE REVIEW

**Comment by nmontesinoc** [comment]
resolves #152054

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Installer https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-386.zip
 Scan request id: 'b0915919-0e6a-4a2d-b576-d7532bc1fd88'
 Error information: BlockingDetectionFound
 Installer https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip
 Scan request id: '12dc9128-6803-4b94-8549-174f3301fa47'
 Error information: BlockingDetectionFound
 
 5/4/2024 11:02:09 AM
 
 ****************************************************************************************

(Automated response - build 880.)

**Comment by stephengillie** [comment]
This might be due to a network block of data centers, to prevent automated downloads.

(Automated response - build 880.)

**Pull request closed without merging**
