### PR TITLE
New version: Mozilla.Thunderbird 115.6.0

### PR DESCRIPTION
**Pull request by tsunamistate**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131261)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by krystofkrticka** [comment]
@stephengillie Why was this PR merged because it purged all languages from manifest.

**Comment by tsunamistate** [comment]
@krystofkrticka because all the other locale installers were causing CI internal errors on "installer scan" step, because of the huge number of installers to scan (4 per locale).

**Comment by krystofkrticka** [comment]
If you wait long enough the mod will override it becuase this causes issues to people using other locale then english.

**Comment by tsunamistate** [comment]
@krystofkrticka 
1. Looking at other PRs, other packages have no problems providing only English
2. Language can be changed in Thunderbird after install

**Comment by krystofkrticka** [comment]
Yes but if you install applications for users as system administrator on fleet of machines its kind of annoying to change it for every users because at my work I have quite high percentage of users which are unable to speak or read in English so they are kind of dependent on computers communicating with them in their native language. And deploying languages using GPO is very annoying in mozillas applications because you have to change it every time there is an update.

**Comment by stephengillie** [comment]
Hi @krystofkrticka,

I haven't been checking for modifications to language files before. I'll start this going forward.

**Pull request merged**
