### PR TITLE
New version: WatchGuard.MobileVPNWithSSLClient version 12.11.0

### PR DESCRIPTION
**Pull request by PckgrMiranda**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/189987)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @PckgrMiranda,

This manifest adds a DisplayVersion to the AppsAndFeaturesEntries that isn't present in previous manifest versions. This entry should be added to the previous versions, or removed from this version.

(Automated response - build 897.)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by PckgrMiranda** [comment]
@PckgrBot

**Comment by stephengillie** [comment]
image

<html>
<body>

Unicode Character | Unicode Character Name | Unicode Number | Code Point HEXadecimal | Code Point DECimal | HTML Entity HEXadecimal | HTML Entity DECimal | General Category (Major, minor) | SubHeading (SubGrouping) | Unicode Block
-- | -- | -- | -- | -- | -- | -- | -- | -- | --

⡨ | BRAILLE PATTERN DOTS-467 | U+2868 | 2868 | 10344 | &#x2868 | &#10344 | So - Symbol, other | Braille patterns | Braille Patterns

<br class="Apple-interchange-newline">
</body>
</html>

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
Close with reason: See above;

**Pull request closed without merging**
