### PR TITLE
New PR for Winamp 5.91.0.10029

### PR DESCRIPTION
**Pull request by djegg**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/92109)

### CODE REVIEW

**Comment by djegg** [comment]
This PR is for Winamp 5.91.0.10029 only: 
https://github.com/microsoft/winget-pkgs/pull/92109/commits/d752630d66001da7cc64ab4c898eac6bd06d22c3

No other changes have been made.

**Comment by djegg** [comment]
Note the /SD IDYES silent switch in the NSIS script for the 2015 VCRedist

> ; Code for Download and Install vc_redist.x86.exe...
> 
> MessageBox MB_YESNO|MB_ICONQUESTION "$(IDS_MSG_VC_REDIST_LINK_TO_MSDOWNLOAD)$\r$\n$\r$\n$(IDS_VC_REDIST_MSDOWNLOAD_URL)$\r$\n$\r$\n$(IDS_VC_DOWNLOAD)$\r$\n$(IDS_VC_DOWNLOAD_OR_ABORT)" `/SD IDYES` IDYES download IDNO abortInstaller

**Comment by djegg** [comment]
Ugh, I think for 5.90.0.999 I ended up creating a separate installer for winget which used the "vc_redist.x86.exe /install /quiet /norestart" switches (we decided on requiring user notification & interaction for the main installer).

It'll be a hassle to do this again for 5.91.0.10029, especially now... but let me know if it's essential and I'll start again...again... and will submit another PR when done, if ever... :-(

**Comment by stephengillie** [comment]
Validation is using a stable release of Winget, which doesn't install dependencies until after the package. I've validated the 5.91.0.10029 files manually with a newer version which installs dependencies first, and added the waiver.

**Comment by djegg** [comment]
Hi. Is there anything else I need to do in order to get this PR approved & merged?

**Review by ItzLevvie — APPROVED** [review]

**Comment by djegg** [comment]
> Apologies, I am afraid I am encountering technical difficulties that might have hampered my ability to assist with merging this pull request. I will continue to try to assist if there are further changes to this pull request.

What needs to be done to resolve this?

**Comment by djegg** [comment]
> Apologies, I am afraid I am encountering technical difficulties that might have hampered my ability to assist with merging this pull request. I will continue to try to assist if there are further changes to this pull request.

Please could someone explain?

**Comment by ItzLevvie** [comment]
cc @djegg,: It's a bug with the bot. @stephengillie needs to manually merge the pull request.

**Comment by djegg** [comment]
> cc @djegg: It's a bug with the bot. @stephengillie needs to manually merge the pull request.

Ok. I'll leave it with you then. Thanks again for everything.

**Review by denelon — CHANGES_REQUESTED** [review]
There should be no files from the 5.90.0.9999 directory in the PR.

**Comment by ItzLevvie** [comment]
cc @djegg: Would you be able to merge latest commits from master? That should solve the `5.90.0.9999` being included in this pull request because it's caused by your fork not being up-to-date with the upstream's master branch.

You can do that by going to https://github.com/djegg/winget-pkgs and clicking on the `Sync fork` button then press on the `Update branch` button:
image

**Review by ItzLevvie — APPROVED** [review]

**Comment by djegg** [comment]
@ItzLevvie @denelon 
done & done
Thanks!

**Review by denelon — APPROVED** [review]

**Pull request merged**
