### PR TITLE
New version: uvncbvba.UltraVnc version 1.3.8.1

### PR DESCRIPTION
**Pull request by russellbanks**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

There is #50166 but I wanted to try it again

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/68067)

### CODE REVIEW

**Comment by russellbanks** [comment]
:( same issue

**Review by ItzLevvie — APPROVED** [review]

**Comment by russellbanks** [comment]
.

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
Is there no Inno version for this version? IIRC the MSI have a dependency issue (+ the virus scan)

**Comment by Trenly** [comment]
https://github.com/microsoft/winget-pkgs/pull/79210

**Comment by ItzLevvie** [comment]
Close with reason: Replaced by PR 79210;

**Pull request closed without merging**
