### PR TITLE
New package: FNMT.ConfiguradorFNMT version 4.0.4

### PR DESCRIPTION
**Pull request by MaanuelMM**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/126988)

### CODE REVIEW

**Comment by MaanuelMM** [comment]
I just checked it and, indeed, if you don't have **Autofirma** installed _(**SpanishGovernment.Autofirma**)_, the installation generates a popup window reminding you that you don't have this application installed. My bad for not noticing it.

It is true that, with user interaction, it is possible to accept this message and finish the installation, but it is also true that this application is only useful in conjunction with Autofirma to generate signature certificates for citizens and institutions located in Spain.

Therefore, I proceed to add it as a dependency.

**Comment by MaanuelMM** [comment]
To be honest, I have no idea why the error once the dependency with _**Autofirma**_ was resolved. Is there any way to access a detailed log to check what is happening? Thanks in advance.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

> Remember that you need AutoFirma for different options. If you do not have it installed you can download it at https:/firmaelectronica.gob.es/
(Internet Translation)

This reflects a pipeline issue. Sorry for any concern caused.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
