### PR TITLE
New version: Microsoft.OneDrive version 24.076.0414.0005

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings).
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150333)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2147012867
> 2024-04-20 18:04:33.597 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-04-20 18:04:33.691 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FF893C4A465: (caller: 00007FF893C4AD01) Exception(1) tid(b1c) 80072EFD 
> 2024-04-20 18:04:36.120 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FF893C4395E: (caller: 00007FF893C45C49) Exception(2) tid(b1c) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-04-20 18:04:36.259 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.065.0331.0002/amd64/OneDriveSetup.exe
> 2024-04-20 18:04:46.857 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-04-20 18:04:46.857 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FF893C4A465: (caller: 00007FF893C4AD01) Exception(3) tid(b1c) 80072EFD 
> 2024-04-20 18:04:48.932 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FF893C4395E: (caller: 00007FF893C45C49) Exception(4) tid(b1c) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-04-20 18:04:25.282 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-04-20 18:04:25.357 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FF89381A465: (caller: 00007FF89381AD01) Exception(1) tid(494) 80072EFD 
> 2024-04-20 18:04:27.764 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FF89381395E: (caller: 00007FF893815C49) Exception(2) tid(494) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-04-20 18:04:27.875 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.065.0331.0002/amd64/OneDriveSetup.exe
> 2024-04-20 18:04:38.892 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-04-20 18:04:38.892 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FF89381A465: (caller: 00007FF89381AD01) Exception(3) tid(494) 80072EFD 
> 2024-04-20 18:04:40.974 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FF89381395E: (caller: 00007FF893815C49) Exception(4) tid(494) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-04-20 18:03:45.830 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-04-20 18:03:45.907 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!55AE57EB: (caller: 55AE5E1C) Exception(1) tid(13c4) 80072EFD 
> 2024-04-20 18:03:48.123 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!55ADF0BF: (caller: 55AE0E2B) Exception(2) tid(13c4) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-04-20 18:03:48.264 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.065.0331.0002/OneDriveSetup.exe
> 2024-04-20 18:03:58.581 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-04-20 18:03:58.581 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!55AE57EB: (caller: 55AE5E1C) Exception(3) tid(13c4) 80072EFD 
> 2024-04-20 18:04:00.640 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!55ADF0BF: (caller: 55AE0E2B) Exception(4) tid(13c4) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-04-20 18:03:51.518 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-04-20 18:03:51.641 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!558757EB: (caller: 55875E1C) Exception(1) tid(175c) 80072EFD 
> 2024-04-20 18:03:53.826 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!5586F0BF: (caller: 55870E2B) Exception(2) tid(175c) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-04-20 18:03:53.952 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.065.0331.0002/OneDriveSetup.exe
> 2024-04-20 18:04:04.206 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-04-20 18:04:04.206 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!558757EB: (caller: 55875E1C) Exception(3) tid(175c) 80072EFD 
> 2024-04-20 18:04:06.310 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!5586F0BF: (caller: 55870E2B) Exception(4) tid(175c) 80072EFD     Msg:[InternetOpenUrl() failed.] 

(Automated response - build 877.)

**Comment by stephengillie** [comment]
URL: https://oneclient.sfx.ms/Win/Installers/24.065.0331.0002/OneDriveSetup.exe 
OK

(Automated message - build 674)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2147012867
> 2024-04-22 10:34:08.334 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-04-22 10:34:08.408 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFFFC57A465: (caller: 00007FFFFC57AD01) Exception(1) tid(1b84) 80072EFD 
> 2024-04-22 10:34:10.820 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FFFFC57395E: (caller: 00007FFFFC575C49) Exception(2) tid(1b84) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-04-22 10:34:10.860 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.065.0331.0002/amd64/OneDriveSetup.exe
> 2024-04-22 10:34:21.331 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-04-22 10:34:21.331 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFFFC57A465: (caller: 00007FFFFC57AD01) Exception(3) tid(1b84) 80072EFD 
> 2024-04-22 10:34:23.420 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FFFFC57395E: (caller: 00007FFFFC575C49) Exception(4) tid(1b84) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-04-22 10:30:49.996 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-04-22 10:30:50.082 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FF8014BA465: (caller: 00007FF8014BAD01) Exception(1) tid(1b74) 80072EFD 
> 2024-04-22 10:30:52.477 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FF8014B395E: (caller: 00007FF8014B5C49) Exception(2) tid(1b74) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-04-22 10:30:52.679 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.065.0331.0002/amd64/OneDriveSetup.exe
> 2024-04-22 10:31:03.743 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-04-22 10:31:03.743 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FF8014BA465: (caller: 00007FF8014BAD01) Exception(3) tid(1b74) 80072EFD 
> 2024-04-22 10:31:05.865 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FF8014B395E: (caller: 00007FF8014B5C49) Exception(4) tid(1b74) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-04-22 10:30:29.081 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-04-22 10:30:29.256 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!545457EB: (caller: 54545E1C) Exception(1) tid(ae8) 80072EFD 
> 2024-04-22 10:30:31.720 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!5453F0BF: (caller: 54540E2B) Exception(2) tid(ae8) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-04-22 10:30:31.753 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.065.0331.0002/OneDriveSetup.exe
> 2024-04-22 10:30:42.159 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-04-22 10:30:42.160 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!545457EB: (caller: 54545E1C) Exception(3) tid(ae8) 80072EFD 
> 2024-04-22 10:30:44.236 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!5453F0BF: (caller: 54540E2B) Exception(4) tid(ae8) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-04-22 10:30:52.764 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-04-22 10:30:52.883 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!502357EB: (caller: 50235E1C) Exception(1) tid(1d1c) 80072EFD 
> 2024-04-22 10:30:55.153 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!5022F0BF: (caller: 50230E2B) Exception(2) tid(1d1c) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-04-22 10:30:55.351 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.065.0331.0002/OneDriveSetup.exe
> 2024-04-22 10:31:06.736 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-04-22 10:31:06.737 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!502357EB: (caller: 50235E1C) Exception(3) tid(1d1c) 80072EFD 
> 2024-04-22 10:31:08.850 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!5022F0BF: (caller: 50230E2B) Exception(4) tid(1d1c) 80072EFD     Msg:[InternetOpenUrl() failed.] 

(Automated response - build 877.)

**Comment by stephengillie** [comment]
Hi @SpecterShell,

Are these available from another URL?

**Comment by SpecterShell** [comment]
> Hi @SpecterShell,
> 
> Are these available from another URL?

@stephengillie Nope, but I guess it is related to https://github.com/microsoft/winget-pkgs/pull/51131#issuecomment-1064455480

**Comment by SpecterShell** [comment]
> > Hi @SpecterShell,
> > Are these available from another URL?
> 
> @stephengillie Nope, but I guess it is related to [#51131 (comment)](https://github.com/microsoft/winget-pkgs/pull/51131#issuecomment-1064455480)

Any chance this PR will be approved and merged?

**Comment by stephengillie** [comment]
Hi @SpecterShell,

I just ran this in 4 VMs. User scope for both architectures had this error: 
image

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2147012867
> 2024-05-04 00:24:56.633 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-05-04 00:24:56.702 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFD13BDA465: (caller: 00007FFD13BDAD01) Exception(1) tid(18c8) 80072EFD 
> 2024-05-04 00:24:59.007 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FFD13BD395E: (caller: 00007FFD13BD5C49) Exception(2) tid(18c8) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-05-04 00:24:59.276 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.076.0414.0005/amd64/OneDriveSetup.exe
> 2024-05-04 00:25:10.147 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-05-04 00:25:10.147 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFD13BDA465: (caller: 00007FFD13BDAD01) Exception(3) tid(18c8) 80072EFD 
> 2024-05-04 00:25:12.221 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FFD13BD395E: (caller: 00007FFD13BD5C49) Exception(4) tid(18c8) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-05-04 00:25:03.440 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-05-04 00:25:03.529 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFD1665A465: (caller: 00007FFD1665AD01) Exception(1) tid(dac) 80072EFD 
> 2024-05-04 00:25:05.802 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FFD1665395E: (caller: 00007FFD16655C49) Exception(2) tid(dac) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-05-04 00:25:05.897 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.076.0414.0005/amd64/OneDriveSetup.exe
> 2024-05-04 00:25:16.823 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-05-04 00:25:16.823 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFD1665A465: (caller: 00007FFD1665AD01) Exception(3) tid(dac) 80072EFD 
> 2024-05-04 00:25:18.911 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FFD1665395E: (caller: 00007FFD16655C49) Exception(4) tid(dac) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-05-04 00:24:23.568 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-05-04 00:24:23.666 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!54F657EB: (caller: 54F65E1C) Exception(1) tid(e88) 80072EFD 
> 2024-05-04 00:24:25.825 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!54F5F0BF: (caller: 54F60E2B) Exception(2) tid(e88) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-05-04 00:24:25.966 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.076.0414.0005/OneDriveSetup.exe
> 2024-05-04 00:24:36.285 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-05-04 00:24:36.285 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!54F657EB: (caller: 54F65E1C) Exception(3) tid(e88) 80072EFD 
> 2024-05-04 00:24:38.387 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!54F5F0BF: (caller: 54F60E2B) Exception(4) tid(e88) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-05-04 00:24:19.953 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-05-04 00:24:20.033 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!518B57EB: (caller: 518B5E1C) Exception(1) tid(1ffc) 80072EFD 
> 2024-05-04 00:24:22.231 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!518AF0BF: (caller: 518B0E2B) Exception(2) tid(1ffc) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-05-04 00:24:22.277 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.076.0414.0005/OneDriveSetup.exe
> 2024-05-04 00:24:32.593 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-05-04 00:24:32.594 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!518B57EB: (caller: 518B5E1C) Exception(3) tid(1ffc) 80072EFD 
> 2024-05-04 00:24:34.684 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!518AF0BF: (caller: 518B0E2B) Exception(4) tid(1ffc) 80072EFD     Msg:[InternetOpenUrl() failed.] 

Automated error analysis suggests -2147012867 may mean Network or Firewall Error.

(Automated response - build 880.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
