### PR TITLE
New package: aiko-chan-ai.DiscordBotClient version 2.4.2

### PR DESCRIPTION
**Pull request by sitiom**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137651)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with:
image

The package installed normally, but when launched it didn't seem to present any UI. Is this expected?

**Comment by sitiom** [comment]
> but when launched it didn't seem to present any UI. Is this expected?

No, the package installs and launches fine for me.

**Comment by sitiom** [comment]
Continued in #137819

**Pull request closed without merging**
