### PR TITLE
New version: TheDocumentFoundation.LibreOffice version 24.2.5.2

### LINKED ISSUE #162187: Remove TheDocumentFoundation.LibreOffice.LTS
### Description of the new feature/enhancement

I'm thinking about removing the `TheDocumentFoundation.LibreOffice.LTS` package and only keeping the non-LTS one, as the LTS one no longer makes sense:

1. The 7.x series got removed from the download page some hours before this post today.
2. The LibreOffice auto updater is now suggesting 7.x series users to update to 24.2.4, which is the current non-LTS version.
image
3. [The 7.x has been EOL'd.](https://wiki.documentfoundation.org/ReleasePlan/7.6)

Also see: https://github.com/chocolatey-community/chocolatey-packages/issues/2496

### Proposed technical implementation details (optional)

_No response_

### PR DESCRIPTION
**Pull request by schembriaiden**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.3.0 :rocket:

Resolves: https://github.com/microsoft/winget-pkgs/issues/162187

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/162548)

### CODE REVIEW

**Comment by vikingnope** [comment]
https://github.com/microsoft/winget-pkgs/issues/162187

**Comment by vikingnope** [comment]
@stephengillie, this didn't actually go through the pipeline, may you start it again please?

**Comment by stephengillie** [comment]
Hi @vikingnope,

This manifest adds Apps and Features entries that aren't present in previous PR versions. These entries should be added to the previous versions, or removed from this version.

(Automated response - build 886.)

**Comment by vikingnope** [comment]
Package Version is incorrect, will fix it

**Comment by stephengillie** [comment]
Close with reason: Duplicate of #162557;

**Pull request closed without merging**
