### PR TITLE
New version: JesseDuffield.lazygit version 0.39.4

### PR DESCRIPTION
**Pull request by Pjstaab**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/115274&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Pjstaab,

Should this package have `Git.Git` as a dependency? It gave this message when launched: 
> 2023/08/07 12:09:19 Git version must be at least 2.20 (i.e. from 2018 onwards). Please upgrade your git version. Alternatively raise an issue at https://github.com/jesseduffield/lazygit/issues for lazygit to be more backwards compatible.

**Comment by Pjstaab** [comment]
@stephengillie I would assume so since it's a wrapper for git. If that needs to be added somewhere I can add it, I just bumped the version.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
