### PR TITLE
New version: vim.vim version 9.0.1365

### PR DESCRIPTION
**Pull request by chrisbra**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/98049)

### CODE REVIEW

**Comment by russellbanks** [comment]
@stephengillie

**Comment by stephengillie** [comment]
Hi @russellbanks and @chrisbra,

Packages must pass a Defender scan to be included in Winget's public manifests. Unfortunately, this error can't be waivered or manually validated.

**Comment by chrisbra** [comment]
there are already several new versions since 9.0.1365, so I particularly do not care for this version. 

However, FWIW, I have seen to many false reports of anti-virus heuristic scans that claim bad behaviour, that I personally do not trust too much those anymore. 

But just for the record, here is what virustotal thinks of it:
- [https://github.com/vim/vim-win32-installer/releases/download/v9.0.1365/gvim_9.0.1365_x86.exe](https://www.virustotal.com/gui/url/662deab11ea2549e5dc96f17ac85ca48b3ceaad927f9cba6c00dc3beba991be0)
- [https://github.com/vim/vim-win32-installer/releases/download/v9.0.1365/gvim_9.0.1365_x64_signed.exe](https://www.virustotal.com/gui/url/32ce70559d5a2f1cebcc42185985fef2e79bbe07fa086fa5809a5f5f39ad2b86)

Both report: "_No security vendors flagged this URL as malicious_"

**Comment by chrisbra** [comment]
I already send feedback here: https://github.com/microsoft/winget-pkgs/pull/98049#issuecomment-1464015087

**Comment by russellbanks** [comment]
> Packages must pass a Defender scan to be included in Winget's public manifests. Unfortunately, this error can't be waivered or manually validated.

If there's no way to waiver this and new versions are passing fine, I'll close this as it's blocked until this specific version gets unflagged.

**Comment by russellbanks** [comment]
Close with reason: Blocked by Microsoft Defender SmartScreen;

**Pull request closed without merging**
