### PR TITLE
New version: MullvadVPN.MullvadVPN version 2024.1-beta1

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135226)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification.
>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

> This PR's version number 2024.1-beta1 has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 2023.6.0, which has 3 parameters.

Is this intentional?

(Automated response - build 628)

**Comment by Exorcism0666** [comment]
> Hi @Exorcism0666,
> 
> > This PR's version number 2024.1-beta1 has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 2023.6.0, which has 3 parameters.
> 
> Is this intentional?
> 
> (Automated response - build 628)

Yes!

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

> This PR's version number 2024.1-beta1 has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 2023.6.0, which has 3 parameters.

Is this intentional?

(Automated response - build 674)

**Review by stephengillie — APPROVED** [review]

**Comment by lasofeli** [comment]
Hello, @Exorcism0666!

I would just like to ask if there's a reason that the beta version of the app is being pushed to the repo. Based on the tags on the Github page, it seems that it's not supposed to be an official release.

**Comment by zotabee** [comment]
Hello.

Don't push beta release please.

Last stable version is the 2023.6

Sources:

https://mullvad.net/en/download/vpn/windows
https://github.com/mullvad/mullvadvpn-app/releases

Thank you!

**Pull request merged**
