### PR TITLE
replayweb-page 1.3.8

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/7232)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
Appears to use a proxy: https://ghproxy.com/

**Comment by KevinLaMS** [comment]
@oxygen-dioxide can you share why you were using the proxy?  Is \ was it providing some service I am not familiar with?
@denelon

**Comment by oxygen-dioxide** [comment]
> @oxygen-dioxide can you share why you were using the proxy? Is \ was it providing some service I am not familiar with?
> @denelon

Because github downloads very slow in mainland China without this proxy.

**Comment by KevinLaMS** [comment]
@oxygen-dioxide Thanks for clarifying.  I will not reject anymore of these and investigate if we can approve with the proxy.

**Pull request merged**
