### PR TITLE
Add Zype.Compass v1.0.0

### PR DESCRIPTION
**Pull request by isworking**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/11788)

### CODE REVIEW

**Review by TechGeeks-TG — APPROVED** [review]
Everything is fine.

**Comment by TechGeeks-TG** [comment]
Dear Danelon, please consider this pull request as Approved. Otherwise please tell the errors/bugs in the Manifest File(s).

**Comment by KevinLaMS** [comment]
previous run gave error, Installation failed with exit code -1978335187  running again in automation

**Pull request merged**
