### PR TITLE
New package: TruffleSecurity.TruffleHog version 3.63.7

### PR DESCRIPTION
**Pull request by BiosPlus**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131710)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\TruffleSecurity.TruffleHog__DefaultSource\trufflehog_3.63.7_windows_amd64.tar.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\TruffleSecurity.TruffleHog__DefaultSource\trufflehog_3.63.7_windows_amd64.tar.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\trufflehog.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\trufflehog.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.

(Automated response - build 490.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> PS C:\Users\User\Desktop> C:\Users\User\AppData\Local\Microsoft\WinGet\Links\trufflehog.exe Program 'trufflehog.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1 char:1 + C:\Users\User\AppData\Local\Microsoft\WinGet\Links\trufflehog.exe + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~. At line:1 char:1 + C:\Users\User\AppData\Local\Microsoft\WinGet\Links\trufflehog.exe + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException     + FullyQualifiedErrorId : NativeCommandFailed  PS C:\Users\User\Desktop> C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\TruffleSecurity.TruffleHog__DefaultSource\trufflehog.exe Program 'trufflehog.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1 char:1 + C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\TruffleSecurity ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~. At line:1 char:1 + C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\TruffleSecurity ... + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~     + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException     + FullyQualifiedErrorId : NativeCommandFailed  PS C:\Users\User\Desktop>

(Automated response - build 489.)

**Comment by stephengillie** [comment]
Hi @BiosPlus,

Unfortunately, `.tar.gz` packages aren't currently supported. I'm not sure if support for these files is planned.

**Comment by Trenly** [comment]
* Waiting for https://github.com/microsoft/winget-cli/issues/2899

**Comment by Trenly** [comment]
[Policy] portable-tar

**Comment by BiosPlus** [comment]
@Trenly heads up, I think that response template references the wrong issue, probably looking for this: https://github.com/microsoft/winget-cli/issues/2899

**Pull request closed without merging**
