### PR TITLE
New version: TeamLidarr.Lidarr version 1.1.4.3027

### PR DESCRIPTION
**Pull request by superusercode**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/110134&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by stephengillie** [comment]
Manual Validation ended with:
image

The installer appears to get stuck on the final "Removing previous Windows Service" step.

**Comment by BrandonWanHuanSheng** [comment]
It look like the setup hangs.

**Comment by BrandonWanHuanSheng** [comment]
Superusercode, can you talk?

**Pull request closed without merging**
