### PR TITLE
NitroPDFIncNitroPDFPtyLtd version 5.1.0.2

### PR DESCRIPTION
**Pull request by techflashYT**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14551)

### CODE REVIEW

**Comment by KaranKad** [comment]
Don't use comma (,) in name

**Comment by sanikdah** [comment]
Huh, is there any info on why it didn't install without user input?  It did when I was testing it locally.

**Comment by KaranKad** [comment]
The `InstallerUrl:` you provided is gonna expire after some time.

**Comment by sanikdah** [comment]
Alright, I'll see if I can deal with that tomorrow, its already past midnight for me and I have to go to bed once I get this last piece of software up.

**Comment by sanikdah** [comment]
Alright so now let me deal with the commas in the name and files.

**Comment by sanikdah** [comment]
Can you show me how to make the URL not expire?  I tried just getting rid of the ?Expires=1622391378 part and that without the ? and still didnt work.

**Comment by sanikdah** [comment]
ok nevermind I found one that won't expire

**Comment by sanikdah** [comment]
alright and the sha256 matches

**Comment by sanikdah** [comment]
I'm just gonna remake it this is such a pain to edit.

**Pull request closed without merging**
