### PR TITLE
Remove old version of JanDeDobbeleer.OhMyPosh

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
null

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
URLs seem weird.

**Comment by vedantmgoyal2009** [comment]
Yes, whole GitHub was experiencing issues at the time of workflow run.

Screenshot_20211128-085049-1

That's why the automation was not performing well at that moment. You can see logs by clicking the workflow run number in the PR comment. BTW, I will fix this and other PRs sometime later as I am not on PC.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/36264#issuecomment-980830866

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/36264#issuecomment-980830866

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
