### PR TITLE
JFrog.Conan version 1.64.1

### PR DESCRIPTION
**Pull request by MiKom**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/154984)

### CODE REVIEW

**Comment by MiKom** [comment]
One small issue is that MS Defender still warns about these files as dangerous and shows a warning window because JFrog doesn't sign these binaries. But it should go away over time i guess?

**Comment by stephengillie** [comment]
Hi @MiKom,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-24 02:20:31.178 [FAIL] Installer failed security check. Url: https://github.com/conan-io/conan/releases/download/1.64.1/conan-win-32.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Hi @MiKom,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-28 09:08:32.634 [FAIL] Installer failed security check. Url: https://github.com/conan-io/conan/releases/download/1.64.1/conan-win-32.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 881.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
