### PR TITLE
New package: Intel.IntelArcGraphics version 31.0.101.4972

### PR DESCRIPTION
**Pull request by jahvari**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/128483)

### CODE REVIEW

**Comment by jahvari** [comment]
Resolves #119812

**Comment by jahvari** [comment]
closes #119812

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 2023-11-29 10:01:00.567 [CORE] DeliveryOptimization downloading from url: https://downloadmirror.intel.com/793688/gfx_win_101.4972.exe
> 2023-11-29 10:01:01.553 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2023-11-29 10:01:01.565 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFAA399A465: (caller: 00007FFAA399AD01) Exception(1) tid(6c8) 80190193 Forbidden (403).

**Comment by stephengillie** [comment]
If you know someone at Intel, you might ask them if they can get this removed. Otherwise there is limited recourse.

**Pull request closed without merging**
