### PR TITLE
Fixed Zoom 5.6.7 version

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/16757)

### CODE REVIEW

**Review by jedieaston — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by ThioJoe** [comment]
@OfficialEsco I might be missing something, but I think it was actually correct before the commit. The latest version is 5.6.7 (1016) which is also how it shows up in the programs list, not 5.6.1016.  Unless the parenthesis are causing issues.

**Comment by OfficialEsco** [comment]
> @OfficialEsco I might be missing something, but I think it was actually correct before the commit. The latest version is 5.6.7 (1016) which is also how it shows up in the programs list, not 5.6.1016. Unless the parenthesis are causing issues.

Zoom's EXE and MSI installer sadly show different versions in the control panel.. The MSI installs 5.6.1016 while the EXE installs 5.6.7 (1016) which is why i haven't added the EXE InstallerType.

AnyDesk's EXE and MSI have different PackageName and PackageVersion which is why that is split up, however Zoom's PackageName is the same so i don't think there is a good workaround before we get support for alternative version https://github.com/microsoft/winget-cli/issues/980

**Comment by ThioJoe** [comment]
> > @OfficialEsco I might be missing something, but I think it was actually correct before the commit. The latest version is 5.6.7 (1016) which is also how it shows up in the programs list, not 5.6.1016. Unless the parenthesis are causing issues.
> 
> Zoom's EXE and MSI installer sadly show different versions in the control panel.. The MSI installs 5.6.1016 while the EXE installs 5.6.7 (1016) which is why i haven't added the EXE InstallerType.
> 
> AnyDesk's EXE and MSI have different PackageName and PackageVersion which is why that is split up, however Zoom's PackageName is the same so i don't think there is a good workaround before we get support for alternative version [microsoft/winget-cli#980](https://github.com/microsoft/winget-cli/issues/980)

Ah I see, that's strange

**Comment by denelon** [comment]
I'm working on capturing all of the schema changes we're targeting for v1.1. We're going to add a section to the installers so we can have multiple ARP entries https://github.com/microsoft/winget-cli/issues/1073 as well as matching for Publisher, App name, and version. I'll also be adding UpgradeCode https://github.com/microsoft/winget-cli/issues/1145 to help with some of the MSI upgrade challenges, EULA https://github.com/microsoft/winget-cli/issues/1144, and a couple more once we lock on them.

**Pull request merged**
