### PR TITLE
Update zufuliu.notepad4.installer.yaml

### PR DESCRIPTION
**Pull request by MerrickZ**
reduce installers for automatically publish

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/189333)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 

(Automated response - build 897.)

**Comment by MerrickZ** [comment]
retry

**Comment by MerrickZ** [comment]
Reason: I'm going to integrate auto-publish-to-winget CI to notepad4, reducing other locales, leaving only i18n builds.

**Review by stephengillie — APPROVED** [review]

**Comment by MerrickZ** [comment]
> [Publish pipeline succeeded for this Pull Request.](https://dev.azure.com/shine-oss/8b78618a-7973-49d8-9174-4360829d979b/_build/results?buildId=23086) Once you refresh your index, this change should be present.

well, no
nothing changes
when I try ```winget show notepad4```
It still is what it was before this PR, while winget-pkgs/manifest already changed.
bug?
Thanks.


@stephengillie

**Comment by stephengillie** [comment]
Hi @MerrickZ,

Sorry for not replying soon. I hope that @ Trenly's reply in the Issue was satisfactory.

**Pull request merged**
