### PR TITLE
New Version: Powershell 7.5.0.1

### PR DESCRIPTION
**Pull request by anamnavi**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/139470)

### CODE REVIEW

**Comment by anamnavi** [comment]
@stephengillie this is the manifest that should be accepted :) it'll need manual validation as it does contain msix, but good news is that our next releases will only have msi now, woohoo!

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-16T15:55:59.8785208Z ##[error] Manifest Error: Inconsistent value in the manifest. [PackageVersion] Value: 7.5.1.0

(Automated response - build 762.)

**Comment by anamnavi** [comment]
@stephengillie I believe this has to do with the Msix installer version, but PackageVersion "7.5.0.1" should be correct. See discussion with @mdanish-kh from awhile ago regarding this: https://github.com/microsoft/winget-pkgs/pull/99498#issuecomment-1478806439

**Review by mdanish-kh — APPROVED** [review]

**Comment by mdanish-kh** [comment]
>  but good news is that our next releases will only have msi now, woohoo!

That means we should be to set up automation using wingetcreate for future releases 🎉

**Pull request merged**
