### PR TITLE
New package: EliWeitzman.ETT version 1.1

### PR DESCRIPTION
**Pull request by eliweitzman**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/123049)

### CODE REVIEW

**Comment by eliweitzman** [comment]
@microsoft-github-policy-service agree

**Comment by eliweitzman** [comment]
I have a feeling this might fail since I'm missing silent install keys in the manifest

**Comment by eliweitzman** [comment]
This feels like it's taking longer than it should

**Comment by eliweitzman** [comment]
I'm not quite sure where this failed, but I have a few ideas... I used Inno to make the installer, which I thought was already included... But also I might take a peek and make sure everything looks okay in the manifest.

Also this might have totally been slow since this is an application written in PowerShell, compiled to an EXE, then bundled with Inno. I wonder if by nature it's a bit hesitant.

Lastly, in case it applies, this was JUST cleared by Microsoft today for Defender SmartScreen, so the latest definition update clears it usually.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

(The package manager window is covering the installer window.)

**Comment by stephengillie** [comment]
Manual Validation ended with: 
image

**Comment by stephengillie** [comment]
Hi @eliweitzman,

Is there an installer switch to select the installer scope?

**Comment by eliweitzman** [comment]
Ah!  Appending '/ALLUSERS' or '/CURRENTUSER' when running the executable installer by command line does let you set the scope...

**Comment by TheDeadGPU** [comment]
The following should work for silent installs.

"ETT.Installer.exe /SILENT /ALLUSERS" - Install for all users

"ETT.Installer.exe /SILENT /CURRENTUSER" - Install for current user

**Review by TheDeadGPU — CHANGES_REQUESTED** [review]
Please make the following changes to the installer.yaml under Installers:

  InstallerSwitches:
    Silent: "/SILENT /ALLUSERS"
    SilentWithProgress: "/VERYSILENT /ALLUSERS"

**Review by TheDeadGPU — APPROVED** [review]
Look great! Full send!

giphy (1)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
