### PR TITLE
Remove version: calibre.calibre version 7.3.0

### PR DESCRIPTION
**Pull request by pxwiz**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135442)

### CODE REVIEW

**Comment by drshtmstry** [comment]
> Sequence contains no elements

- #133371

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 642.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-19T05:48:19.1258318Z Processing manifest: manifests\c\calibre\calibre\7.3.0
 2024-01-19T05:48:19.1267452Z -----------------------------------------------------
 2024-01-19T05:48:19.1275073Z Status: Started
 2024-01-19T05:48:19.1283760Z Manifest file is Deleted
 2024-01-19T05:48:20.2777145Z Status: Completed
 2024-01-19T05:48:20.2778158Z ##[error] Result: Failed
 2024-01-19T05:48:20.2780183Z ##[error] Sequence contains no elements
 2024-01-19T05:48:20.2782385Z ##[error]Manifest Validation Failed

(Automated response - build 642.)

**Comment by stephengillie** [comment]
URL: https://github.com/kovidgoyal/calibre/releases/download/v7.3.0/calibre-64bit-7.3.0.msi 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 642)

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Duplicate of https://github.com/microsoft/winget-pkgs/pull/133843

**Pull request closed without merging**
