### PR TITLE
Add recommendation for users to move away from WinDirStat

### PR DESCRIPTION
**Pull request by Trenly**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

There have now been a few issues filed indicating confusion around the behavior of WinDirStat and the version being unknown.
* https://github.com/microsoft/winget-pkgs/issues/161769
* https://github.com/microsoft/winget-pkgs/issues/54490
* https://github.com/microsoft/winget-pkgs/issues/88994
* https://github.com/microsoft/winget-pkgs/issues/173833

Because the last release of WinDirStat was in 2016, it should be safe to assume that it is not in active development and no new updates for the package will be coming. However, another package - WizTree - provides the same functionality as WinDirStat but is newer, much faster, and is still being patched and developed upon. 

This PR adds an installation note to help reduce confusion and point users towards the newer software if they should choose to install it.

###### Related to microsoft/winget-cli#1899

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Lonniebiz** [comment]
> Because the last release of WinDirStat was in 2016, it should be safe to assume that it is not in active development and no new updates for the package will be coming. However, another package - WizTree - provides the same functionality as WinDirStat but is newer, much faster, and is still being patched and developed upon.
> 
> This PR adds an installation note to help reduce confusion and point users towards the newer software if they should choose to install it.

While WizTree may be faster, and more actively developed, it isn't open source (like WinDirStat is). Users like myself may prefer WinDirStat for this reason alone (even if it is slower).

**Comment by Trenly** [comment]
That is true, which is why I just added it as a note so that users can make their own decisions about the software they choose to install

**Comment by cvrebert** [comment]
> it should be safe to assume that it is not in active development and no new updates for the package will be coming

They've been making alpha/beta releases periodically this year (https://github.com/windirstat/windirstat-next/releases ). Likewise for commits (https://github.com/windirstat/windirstat/commits/master/ ), including one yesterday.

> There have now been a few issues filed indicating confusion around the behavior of WinDirStat and the version being unknown.

Presumably they'll have that fixed when they finally make their next major stable release: https://github.com/windirstat/windirstat/issues/46
Seems they're switching to a Wix installer.

**Comment by Trenly** [comment]
Perfect; Once a new version is released I'll update the manifest and remove this note

**Comment by NoMoreFood** [comment]
@Trenly The next two months is my goal. Would you like me to take over updating this when the release is ready?  I would appreciate you removing the note now since it is false.

**Comment by Lonniebiz** [comment]
@NoMoreFood: Couldn't you do a quick release of WinDirStat, that is exactly like the current version provided in winget except that it merely sets that version registry entry that winget needs to remain aware of the installed version of WinDirstat?

Perhaps that alone is more work than it might appear me, and it is just better to wait.

As for WinDirStat and "active development", I've used it for years and it doesn't bother me much that it hasn't changed since 2016. When something works well for its purpose it doesn't require too much active development. Plus, it is open source, and I typically favor that over closed source alternatives (that's more of a priority to me than performance in this case).

While I'm glad to be informed of the existence WizTree, I don't like a package manager recommending a proprietary application as an alternative to an open source one unless this difference is explicitly made clear. I guess that's just my preference, but now that the note has been discovered untrue, that's probably a more agreeable reason to go ahead and remove it.

**Comment by aisgbnok** [comment]
FYI, @Trenly improved the accuracy of the note last week:

- #174360

As I understand it, the note aimed to minimize user confusion and reduce the amount of issues being opened in this [microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs) repository. While I agree that the previous note may have seemed biased, the updated note appears to be a reasonable compromise until 2.x.x lands.

Note as of 2024-09-27:

> **Installation Notes:** Because this software does not write a version to the registry, WinGet is not able to determine the installed version. This will be fixed in the next release of WinDirStat. See https://github.com/windirstat/windirstat/issues/75 for more info.

**Pull request merged**
