### PR TITLE
Remove version: Microsoft.Sysinternals.Sysmon version 15.14

### LINKED ISSUE #199755: [Update Request]: Sysmon 15.15
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.Sysinternals.Sysmon

### Package Version

15.15.0.0

### Please describe the changes you would like to see

Download Page: https://live.sysinternals.com/Sysmon64.exe

### PR DESCRIPTION
**Pull request by Dragon1573**
> [!WARNING]
>
> This package uses vanity URL for downloading installer file. Since there're newer versions available, outdated versions should be removed from the repository.

## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #199755 

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/199825)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://live.sysinternals.com/Sysmon.exe 
Response Error: The remote server returned an error: (406) Not Acceptable.

(Automated message - build 923)

**Comment by stephengillie** [comment]
Hi @Dragon1573,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 931.)

**Comment by Dragon1573** [comment]
> This PR removes the highest available version of the package from the repository.
> 
> Please provide the reason for removal to help our moderators understand the context.
> 
> Template: msftbot/highestVersionRemoval

The removal is intended.

- See **the ⚠️ WARNING section** of https://github.com/microsoft/winget-pkgs/pull/199825#issue-2750665395

**Comment by Trenly** [comment]
The issue is that the PRs were raised at the same time, and the addition of the new version was not complete by the time Stephen's PR checker got to this one. In the future, it would be better to add the new version and remove the old version in a single PR. Note that you can only remove one version and add one version in a single PR if they are the same identifier, and you can't remove multiple versions.

[Policy] Reset Labels

**Review by Trenly — APPROVED** [review]

**Pull request merged**
