### PR TITLE
New package: Microsoft.Sysinternals.RegJump version 1.11

### LINKED ISSUE #182745: [Package Request]: Microsoft.Sysinternals.RegJump
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://learn.microsoft.com/en-us/sysinternals/downloads/regjump
Publisher: Microsoft
Package Name: RegJump
Description: This little command-line applet takes a registry path and makes Regedit open to that path.
Package Version: 1.11
Installer Url: https://download.sysinternals.com/files/regjump.zip

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #182745

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/182762)

### CODE REVIEW

**Comment by Dragon1573** [comment]
Manually verified in _Windows Sandbox_ instance.

Image
Image

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Packages\Microsoft.Sysinternals.RegJump__DefaultSource\regjump.exe returned exit code: 1
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\regjump.exe returned exit code: 1

(Automated response - build 896.)

**Comment by Dragon1573** [comment]
@stephengillie - This is an expected behavior. A parameter with any valid registry key or a `-c` switch is required for running `regjump.exe`.

**Comment by stephengillie** [comment]
Verify:
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
