### PR TITLE
New version: tencent.qq 9.6.2.28755

### PR DESCRIPTION
**Pull request by lychichem**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/64919)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
@ItzLevvie @OfficialEsco @jedieaston 

Can one of you approve this? I'd like to see if it gets merged

**Review by ItzLevvie — APPROVED** [review]
abcd

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
abcd

**Review by Trenly — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
Hmm; Doesn't seem to remove the author feedback when all reviewers approve

**Comment by jedieaston** [comment]
It used to, because I remember approving stuff after someone else gave feedback and it going through. Weird.

**Comment by Trenly** [comment]
> It used to, because I remember approving stuff after someone else gave feedback and it going through. Weird.

Used to being the key words there ;)

**Pull request merged**
