### PR TITLE
Added Plex Desktop version 1.20.0.1406

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/4074)

### CODE REVIEW

**Comment by jedieaston** [comment]
These URLs are resolving fine on my end, I'm not sure what's going on. #4075 is encountering the same error. I haven't edited the URLs from the previous version.

**Comment by KevinLaMS** [comment]
Well we made progress, but the installer is erroring at the end.  

image

**Comment by jedieaston** [comment]
Looks like I'm getting that too now, both for 1.20.0.1406 and 1.15.0.1358 (the version that is currently in the repo). 

image


I'll see if Plex Support has anything to say about it, but if we need to close this for now that is fine.

**Comment by jedieaston** [comment]
Plex doesn't seem to monitor their issues repo. I'll close this for now, once different return code support is out I'll fix it and resubmit.

**Pull request closed without merging**
