### PR TITLE
AdoptOpenJDK.IcedTea-Web version 1.8.8.0

### PR DESCRIPTION
**Pull request by gab9281**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/66377)

### CODE REVIEW

**Comment by hackean-msft** [comment]
@gab9281 This manifest appears to require JRE to run correctly on the machine

**Comment by gab9281** [comment]
> @gab9281 This manifest appears to require JRE to run correctly on the machine

Yes it does, I'll add the dependancy to the manifest when I'll be able to (on mobile). Is it possible to link to another package inside Winget ?

**Comment by denelon** [comment]
We don't have support for dependencies yet. It's an experimental feature we're currently working on. If the package installs without dependencies, it can pass automation in some cases. If the dependency is necessary for installation, then this PR will get blocked until we have support for them. You can add the package dependency to the manifest if you like, or you can wait until we remove the labels when we have support and update it then.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
