### PR TITLE
FSN.TyperspeedSepia version 3.1

### PR DESCRIPTION
**Pull request by seedy60**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/22978)

### CODE REVIEW

**Comment by quhxl** [comment]
Duplicate #22953

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/22978#issuecomment-890951042

**Comment by fireseed66** [comment]
What exactly are the bad characters?

**Comment by OfficialEsco** [comment]
Its a dumb description for duplicate/overwrite, nothing to worry about.
Please close the PR :)

**Comment by fireseed66** [comment]
It says there are unmerged commits, but WinGet says otherwise. I'm confused.

**Comment by quhxl** [comment]
PR #22953 has already been merged, so your PR becomes redundant. You can simply leave it closed.

**Pull request closed without merging**
