### PR TITLE
Reverting the postman app version to 10.24.16 as v11 version is not available/working as expected

### PR DESCRIPTION
**Pull request by manavbharambe**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/148306)

### CODE REVIEW

**Comment by manavbharambe** [comment]
@microsoft-github-policy-service agree [company="Postman"]

**Comment by manavbharambe** [comment]
@microsoft-github-policy-service agree

**Comment by manavbharambe** [comment]
This URL is wrong the current latest version is 10.24.16 (https://dl.pstmn.io/download/version/10.24.3/win64)
PR which introduced this change: 
https://github.com/microsoft/winget-pkgs/pull/147931

**Comment by manavbharambe** [comment]
@PckgrBot I am able to add reviewers at this point in time can you help ?

**Comment by manavbharambe** [comment]
@stephengillie Can you help get approval on this PR ?

**Comment by manavbharambe** [comment]
@ agree company="Postman"

**Comment by manavbharambe** [comment]
agree company="Postman"

**Comment by manavbharambe** [comment]
@agree company="Postman"

**Comment by manavbharambe** [comment]
@microsoft-github-policy-service agree company="postman"

**Review by kuzco201 — APPROVED** [review]

**Review by Trenly — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @manavbharambe,

> @ stephengillie Can you help get approval on this PR ? Given the the PR which introduced V11 was approved by you, thought could get some help on this

I was sleeping, sorry for the delay. Was there a way for our automated processes to detect that this apparently pre-release version wasn't ready? We're always looking to improve.

**Comment by manavbharambe** [comment]
Thank you @stephengillie .
Yes, it is recommended to use `https://dl.pstmn.io/api/version/latest?channel=stable` endpoint for getting the latest stable version available for Postman App as it will point to a valid version always.

**Comment by manavbharambe** [comment]
@PckgrBot Sure do let me know if I can help, would be more than happy to help.

**Pull request merged**
