### PR TITLE
Update: OSGeo.QGIS version 3.40.0 (3.40.0-1)

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#9265](https://github.com/SpecterShell/Dumplings/actions/runs/11646987904).

<details>

<summary>Log</summary>

````
Updated: 3.38.3-1 → 3.40.0-1
Submitting WinGet manifests
Found existing pull requests:
Update: OSGeo.QGIS-3.40.0 - https://github.com/microsoft/winget-pkgs/pull/186397
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/188172)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Pull request merged**
