### PR TITLE
Tangent90.CoolapkUWP version 2.1.38.0

### PR DESCRIPTION
**Pull request by wherewhere**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/33167)

### CODE REVIEW

**Comment by Trenly** [comment]
```
Found Coolapk UWP [Tangent90.CoolapkUWP] Version 2.1.38.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 0x800b0109 : A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
```

**Comment by wherewhere** [comment]
> ```
> Found Coolapk UWP [Tangent90.CoolapkUWP] Version 2.1.38.0
> This application is licensed to you by its owner.
> Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
> Successfully verified installer hash
> Starting package install...
> Installer failed with exit code: 0x800b0109 : A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
> ```

So how to solve this problem? I see other issues also mention this, but there is no solution. . .

**Comment by ItzLevvie** [comment]
> A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.

This error reminds me when the GUI version of UUP Media Creator was in development.

It looks like the `.appxbundle` isn't signed? Please contact the developer to sign their application. They can follow these instructions: https://docs.microsoft.com/en-us/windows/msix/package/sign-app-package-using-signtool or https://www.twelve21.io/how-to-sign-a-uwp-application-with-a-digital-certificate/.

Error: `
This app package is not signed with a trusted certificate. Contact your system administrator or the app developer to obtain a new certificate or app package with trusted certificates. The root certificate and all immediate certificates of the signature in the app package must be trusted (0x800B010A)
`

UUP Media Creator:
image

CoolapkUWP:
image

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/33167#issuecomment-962597533

**Comment by wherewhere** [comment]
> https://github.com/microsoft/winget-pkgs/pull/33167#issuecomment-962597533

It needs a trusted certificate. But I don't know how to get one. . .

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> It needs a trusted certificate. But I don't know how to get one. . .

I'm not too familiar with packaged applications, but I think you might have to purchase one from https://comodosslstore.com/codesigning.aspx, the Standard Validation (SV) one from Comodo, and then set up your pipelines and project to sign your package.

EXE and MSI installers don't have to do this, unless you want to hide the blue Microsoft Defender SmartScreen warnings, which you'll need an Extended Validation certificate for that.

Alternatively, you can just publish your application to Microsoft Store and get the application signed for free using Microsoft's own certificate.

If you do it the alternative way, you don't need to add your application here because WinGet can download applications from Microsoft Store, but if you want add your application here, download the application from Microsoft Store (probably use https://store.rg-adguard.net) and then host the binary on GitHub Releases, and create a package using wingetcreate or YamlCreate.ps1.

**Pull request closed without merging**
