### PR TITLE
Don't remove Blocking Issue on changes pushed

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
PRs such as:

* https://github.com/microsoft/winget-pkgs/pull/64058
* https://github.com/microsoft/winget-pkgs/pull/62517

have blocking issues and they're removed on every synchronize event. Its hard to mention @denelon, again and again, to add blocking issues, and sometimes to reopen if they're closed with No-Recent-Activity.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/76500)

### CODE REVIEW

**Comment by denelon** [comment]
@Trenly does this look like a good change to you? What's the blast radius you perceive?

**Comment by Trenly** [comment]
> @Trenly does this look like a good change to you? What's the blast radius you perceive?

Any PR labeled blocking-issue will have to have it manually removed when the blocking issue is resolved.

Honestly, I think that keeping the behavior as it is probably a good thing. There shouldn’t need to be changes pushed to branches with "Blocking-Issue" anyways, so it would make sense that when changes are pushed, it should be re-evaluated as to whether or not it is still blocking

**Comment by vedantmgoyal2009** [comment]
> Any PR labeled blocking-issue will have to have it manually removed when the blocking issue is resolved.

@denelon

**Comment by denelon** [comment]
We're going to leave the behavior as it is currently implemented. I believe it to be the better choice since the "Blocking-Issue" label may be put in place intentionally for a manual decision, and automatically removing it forces someone to re-evaluate it again. We don't want these to get missed when we have a high PR volume.

**Pull request closed without merging**
