### PR TITLE
New version: Google.AndroidStudio 2023.2.1.25

### PR DESCRIPTION
**Pull request by aisgbnok**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150629)

### CODE REVIEW

**Comment by aisgbnok** [comment]
@stephengillie,

>  Manifest Error: DisplayVersion declared in the manifest has overlap with existing DisplayVersion range in the index. Existing DisplayVersion range in index:  [ [2023.2, 2023.2]]

Google.AndroidStudio `2023.2.1.25` and `2023.2.1.23` use the same `DisplayVersion`: `"2023.2"`. Unfortunately, Android Studio only writes `MAJOR.MINOR` to registry/arp entries, no `.PATCH`, etc.

I attempted to skirt around this by adding `InstallationMetadata`:

https://github.com/microsoft/winget-pkgs/blob/f9a90b9ab8dece8b7f3c3f096963b8a1d8b43c25/manifests/g/Google/AndroidStudio/2023.2.1.25/Google.AndroidStudio.installer.yaml#L18-L25

But it didn't work.

Is there any other way to resolve this? or can there only be one package with the same `DisplayVersion`? 

If that is the case, then would it be acceptable to remove `2023.2.1.23` and add/replace with `2023.2.1.25`? Thanks.

**Comment by stephengillie** [comment]
> can there only be one package with the same DisplayVersion?

I believe so, yes. The `DisplayVersion` creates a Range with itself as the only member, and doesn't allow overlaps. Since both have to have that same range, there can be only one in the repo at a time.

**Comment by aisgbnok** [comment]
> I believe so, yes. The `DisplayVersion` creates a Range with itself as the only member, and doesn't allow overlaps. Since both have to have that same range, there can be only one in the repo at a time.

Thanks, and your right only a single `DisplayVersion` at a time.

So I have removed `2023.2.1.23` and added `2023.2.1.25` in this single PR to ensure only one package with `DisplayVersion` `"2023.2"`. However, the validation fails because the `DisplayVersion` is still present in the index.

Is it possible to do an update like this without causing a situation where the `"2023.2"` version is momentarily removed from the index/unpublished? Should this be done in two PRs or one like this? What is preferred for a situation like this? Thank you for your insight!

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-04-26T19:56:19.0351217Z ##[error]Manifest Validation Failed
 2024-04-26T19:56:24.1005379Z ##[section]Finishing: Validate Manifest

(Automated response - build 877.)

**Comment by stephengillie** [comment]
I'm not sure of the best way to proceed here. 

@mdanish-kh and @Trenly, could either of you advise on the best course here?

**Comment by mdanish-kh** [comment]
@aisgbnok The validation works by scanning the current index for a duplicate DisplayVersion. In order to resolve this issue, the previous version should be removed in a separate PR. After that gets published and the index gets updated, we can re-run pipelines here and add the new version in

**Comment by Trenly** [comment]
I've run into this issue in the past myself and the guidance I received was exactly as @mdanish-kh said, as the pipelines do not create a new index and check it as part of the pipeline run (creating the index is conputationally expensive, the publish pipeline is separate for this reason)

Perhaps opening a [feature request](https://github.com/microsoft/winget-pkgs/issues/new/choose) with more details might give @hackean-msft some ideas on how a commit processor could potentially apply the diffs from the commits to the existing index without rebuilding it, but for now all we can do is remove and then add the new version

**Comment by Trenly** [comment]
> @wingetbot run

You need to wait for the removal to pass the publish pipeline

**Comment by aisgbnok** [comment]
Index published so I've rebased on `origin/master`.

- https://github.com/microsoft/winget-pkgs/pull/151501#issuecomment-2083621293

It should work this time. Thank you everyone for your help.

**Review by Trenly — APPROVED** [review]

**Pull request merged**
