### PR TITLE
Fix YamlCreate.ps1

### PR DESCRIPTION
**Pull request by SpecterShell**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/25672)

### CODE REVIEW

**Review by jedieaston — APPROVED** [review]

**Comment by jedieaston** [comment]
@OfficialEsco

**Comment by Trenly** [comment]
This will probably create a merge conflict with #21204. Depending on how long #22081 and any other required updates take it may make more sense to resolve the merge conflict on the YamlParsing pull request, or it may make more sense to wait on this pull request. 

I'll let everyone else decide what is best, since I don't know how close the 2.0.0 update is

**Comment by jedieaston** [comment]
@SpecterShell could change the target branch on this to Trenley:YamlParsing, no? I don't know if you can do it cross repo without closing the PR.

**Comment by Trenly** [comment]
> @SpecterShell could change the target branch on this to Trenley:YamlParsing, no? I don't know if you can do it cross repo without closing the PR.

Could, but this has already been resolved in Trenly:YamlParsing with the multitude of other changes

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/25672#issuecomment-905633676

**Review by Trenly — APPROVED** [review]

**Comment by Trenly** [comment]
@denelon Since #27522 has been merged in; It doesn't make sense to wait on this one anymore

**Review by denelon — APPROVED** [review]

**Pull request merged**
