### PR TITLE
Add WebRTC Redirector Service

### PR DESCRIPTION
**Pull request by alexwilcox9**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

Adding the WebRTC Redirector Service for Teams on AVD, more information here:
https://docs.microsoft.com/en-us/azure/virtual-desktop/teams-on-avd

Note the `InstallerUrl` is a generic URL for the latest version as I couldn't find a URL for this specific version

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/38391)

### CODE REVIEW

**Comment by alexwilcox9** [comment]
This seems to install locally fine and I think that's as I have the Microsoft Visual C++ Redistributable installed which is a requirement of this package
Is there a way to list dependencies so that winget installs those first?
https://docs.microsoft.com/en-us/azure/virtual-desktop/teams-on-avd#install-the-teams-websocket-service

**Comment by ItzLevvie** [comment]
> Is there a way to list dependencies so that winget installs those first?

At the moment, no.

Package Dependencies are still work in progress and available in development builds of WinGet.

**Comment by alexwilcox9** [comment]
@ItzLevvie thanks for confirming that

With this is mind what's the approach for apps with dependencies? Is there a way around this pipeline failure or does this need to wait until dependencies are supported?

Thanks

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> With this is mind what's the approach for apps with dependencies? Is there a way around this pipeline failure or does this need to wait until dependencies are supported?

You will have to either ask the publisher to include dependencies into their application or wait until WinGet gets support for package dependencies for Azure Pipelines to pass.

**Comment by alexwilcox9** [comment]
Follow up question: can this be merged with a failing pipeline if the dependency can be proved to be the issue or must everything be green to get an app approved?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> Follow up question: can this be merged with a failing pipeline if the dependency can be proved to be the issue or must everything be green to get an app approved?

It must have a green (i.e. an `Azure-Pipelines-Passed` or `Validation-Completed`) label to be merged.

**Pull request closed without merging**
