### PR TITLE
ppy.osu! version 1.3.3.8

### PR DESCRIPTION
**Pull request by EdiValentin101**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14693)

### CODE REVIEW

**Comment by richiesuper** [comment]
what a coincidence XD
i also put this pull request moments ago XDXD

**Comment by EdiValentin101** [comment]
> what a coincidence XD
> i also put this pull request moments ago XDXD

No wayyy :))))
I just saw now, I'm sorry, the first time I checked nothing showed up

**Comment by KaranKad** [comment]
It's already available https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/Peppy/Osu!

**Comment by richiesuper** [comment]
> 
> 
> > what a coincidence XD
> > i also put this pull request moments ago XDXD
> 
> No wayyy :))))
> I just saw now, I'm sorry, the first time I checked nothing showed up

hahaha it's ok buddy :))
and it looks like osu! can't silently install :(((

**Comment by EdiValentin101** [comment]
> > > what a coincidence XD
> > > i also put this pull request moments ago XDXD
> > 
> > 
> > No wayyy :))))
> > I just saw now, I'm sorry, the first time I checked nothing showed up
> 
> hahaha it's ok buddy :))
> and it looks like osu! can't silently install :(((

Yup...sadly

**Pull request closed without merging**
