### PR TITLE
New package: Kubernetes.kustomize version 5.0.1

### PR DESCRIPTION
**Pull request by mloskot**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101695)

### CODE REVIEW

**Comment by mloskot** [comment]
This PR does not handle nested TAR correctly

**Comment by mloskot** [comment]
@stephengillie The executable is packaged in `.tar.gz`, so tarred file is deployed e.g. `name.tar.exe`, and I have no idea how to deal with it. I've asked for help here https://github.com/microsoft/winget-pkgs/discussions/101705

**Comment by mdanish-kh** [comment]
Blocked by https://github.com/microsoft/winget-cli/issues/2899

**Comment by mloskot** [comment]
First, the Kustomize issue blocking this PR has now been resolved and Kustomize releases Windows binaries in zip
- https://github.com/kubernetes-sigs/kustomize/issues/5116

However, this PR is now obsolete as manifests for newer, current Kustomize 5.3.0 have already been submitted and merged 
- #129954

So, I'm closing this PR as it needs no merging.

**Pull request closed without merging**
