### PR TITLE
ESUNBank.WebATMService version 1.0.0.7

### PR DESCRIPTION
**Pull request by MysticCereal**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/100118)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @MysticCereal,

This program presents an interesting message box: 
image

Clicking the 1st button gives:
image

Clicking Cancel gives:
image

Clicking OK gives:
image

Back to the message box, the 2nd button gives:
image

The 3rd button gives:
 image

And the 4th button closes the box. Does this application need a language pack?

**Comment by MysticCereal** [comment]
Hi @stephengillie,
The program is designed mainly for Traditional Chinese (Taiwanese) users, therefore "Control Panel > Region > Administrative > Language for non-Unicode programs > Change system locale..." has to be set to "Chinese (Traditional, Taiwan)" for the characters to display properly.

Under usual circumstances, the service runs in the background and doesn't show any error message. The message that's showing up is most likely to advise the user to download a compatible web browser, but I'll need a VM with no browsers installed to confirm that exactly is shown there.

**Comment by MysticCereal** [comment]
Update: I went ahead and set up a new VM with the latest Windows 11 22H2 image to test the manifest. The system was set up with US/Eng only. Besides VMWare tools, no additional software was installed. I was not able to reproduce the aforementioned issue. Details below:

1. I retested the manifest, it ran properly and the software proceeded to run as a service in the tray after installation, requiring no manual tinkering. I was not able to reproduce the weird message box.
2. I also downloaded the installation file and installed it manually. During installaing, the characters were actually being displayed with no issues. Same as above, nothing went wrong.
3. I attempted to uninstall Microsoft Edge to see if not having any browser would cause the box to appear, but Windows isn't allowing me to uninstall Edge.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
