### PR TITLE
Newer Version: Typst.Typst versions 0.3.0

### PR DESCRIPTION
**Pull request by BrandonWanHuanSheng**
Holding off merged because Winget 1.5 and higher version is not yet released. Converting to draft.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/106054)

### CODE REVIEW

**Comment by stephengillie** [comment]
[Policy 1.2](https://learn.microsoft.com/en-us/windows/package-manager/package/windows-package-manager-policies#12-security) (for reference)

**Comment by stephengillie** [comment]
This package is expecting arguments:
```
typst creates PDF files from .typ files

Usage: typst.exe [OPTIONS] <COMMAND>

Commands:
  compile  Compiles the input file into a PDF file [aliases: c]
  watch    Watches the input file and recompiles on changes [aliases: w]
  fonts    List all discovered fonts in system and custom font paths
  help     Print this message or the help of the given subcommand(s)

Options:
...
```

**Comment by BrandonWanHuanSheng** [comment]
I am going to leave it undraft.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
