### PR TITLE
Add StepMania 5.0.12

### PR DESCRIPTION
**Pull request by latere-a-latere**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/712)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
the tool fails to run with d3d9_43.dll

**Comment by MarNicGit** [comment]
Just tried it out in the win10 dev environment and you are correct, @KevinLaMS. Installing DirectX by hand solves this problem: https://www.microsoft.com/en-us/download/details.aspx?id=35

**Comment by KevinLaMS** [comment]
This app has a dependency on DirectX

**Comment by denelon** [comment]
We need to support dependencies, and the schema needs to be updated.

**Comment by KevinLaMS** [comment]
Clearing assignees until unblocked.

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
