### PR TITLE
New: Spicebrains.Instant-Eyedropper version 2.0.0

### LINKED ISSUE #21989: Request: Instant Eyedropper
# Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**:

**Publisher Url**:

**Package Name**:

**Package Url**:

**Description**:

**Package Version**:

**Installer URL**:

## For new versions:

**Current Package Identifier**:

All I know is this: http://instant-eyedropper.com/

### PR DESCRIPTION
**Pull request by OfficialEsco**
Resolves #21989
Hey @miaupaw is this ok with you?
~~I can't seem to find any License information?~~

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

```
Found Instant Eyedropper [Spicebrains.Instant-Eyedropper]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading http://instant-eyedropper.com/download/instant-eyedropper-2.0.0.exe
  ██████████████████████████████   530 KB /  530 KB
Successfully verified installer hash
Starting package install...
Successfully installed
```

image

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/21991)

### CODE REVIEW

**Comment by ItzLevvie** [comment]
Licence file is found here https://github.com/miaupaw/instant-eyedropper/blob/main/vsproject/output/license.txt

**Comment by OfficialEsco** [comment]
Yeah okay, ty 🤦‍♂️

**Review by ItzLevvie — APPROVED** [review]

**Comment by Poopooracoocoo** [comment]
thanks broski <3

**Pull request merged**
