### PR TITLE
Delete manifests/m/Microsoft/Skype/8.112.0.206 directory

### LINKED ISSUE #4138: Winget upgrade available for same version of app
### Brief description of your issue

**winget upgrade** return **upgrades available** for same installed version of skype.

### Steps to reproduce

winget upgrade

### Expected behavior

Should return nothing for upgrade.

### Actual behavior

https://github.com/microsoft/winget-cli/assets/16545063/9798f0af-1b0c-492d-b5c2-3743aa0eed65

### Environment

```shell
Windows Package Manager v1.6.3482
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3085
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.3482.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                D:\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
```

### PR DESCRIPTION
**Pull request by mdanish-kh**
There's already [`8.112`](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/Skype/8.112) directory in the repo that uses the correct PackageVersion;

- Resolves https://github.com/microsoft/winget-cli/issues/4138

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137740)

### CODE REVIEW

**Review by Trenly — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-03T18:28:47.8946769Z Processing manifest: manifests\m\Microsoft\Skype\8.112.0.206
 2024-02-03T18:28:47.8957588Z -----------------------------------------------------
 2024-02-03T18:28:47.8964722Z Status: Started
 2024-02-03T18:28:47.8973955Z Manifest file is Deleted
 2024-02-03T18:28:48.1430244Z Status: Completed
 2024-02-03T18:28:48.1439953Z ##[error] Result: Failed
 2024-02-03T18:28:48.1499672Z ##[error] Sequence contains no elements
 2024-02-03T18:28:48.2499800Z ##[error]Manifest Validation Failed

(Automated response - build 695.)

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 695.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
