### PR TITLE
Microsoft.PowershellPreview version 7.2.0.10

### PR DESCRIPTION
**Pull request by Masamune3210**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/28919)

### CODE REVIEW

**Comment by Masamune3210** [comment]
Not sure if this kind of thing is possible or if there is a better way, making a separate ID for preview versions of a program. Would it be better just to add the preview version installer to the normal id? or would that screw with versions and upgrade detection.

**Comment by bddckr** [comment]
@Masamune3210 There's a PowerShell Preview folder already, which this should be moved into (along with using that one's ID etc.) I believe: https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/PowerShell/Preview

Note: I just stumbled upon this PR as I was looking to upgrade to the latest PS Preview via winget. I am not familiar with this repo :)

**Review by jedieaston — APPROVED** [review]

**Review by jedieaston — CHANGES_REQUESTED** [review]
I was too fast on the draw. This should be moved to Microsoft.PowerShell.Preview, thanks @bddckr.

**Comment by Masamune3210** [comment]
No problem, ill get it moved!

**Comment by Masamune3210** [comment]
Fixed, just gotta wait for the bot and for someone to review it! Thanks for the help

**Pull request merged**
