### PR TITLE
New version: Suwayomi.Tachidesk-Sorayomi version 0.4.0

### PR DESCRIPTION
**Pull request by DattatreyaReddy**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/96636)

### CODE REVIEW

**Comment by DattatreyaReddy** [comment]
@microsoft-github-policy-service agree company="Suwayomi"

**Comment by stephengillie** [comment]
Hi @DattatreyaReddy,

The program installed normally, but gave an error when launched:
image

Is a dependency missing?

**Comment by DattatreyaReddy** [comment]
in the .msi version does'nt install all the .dll files like the .zip version, it say that can't find the permission_handler_windows_plugin.dll, so i put the missing files from the .zip version and fixed.

**Comment by DattatreyaReddy** [comment]
i think i have to update the version

**Pull request closed without merging**
