### PR TITLE
gdiObjects.Perspective version 3.0.2202.3

### PR DESCRIPTION
**Pull request by gdiObjects**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/44763)

### CODE REVIEW

**Comment by Trenly** [comment]
#42616 - Close and reopen the PR to re-run the pipelines

**Review by OfficialEsco — APPROVED** [review]

**Comment by gdiObjects** [comment]
> Hello @gdiObjects, The PR could not be validated because there is a merge conflict which adds bad characters to the manifest. Please address the merge conflict and resubmit.

I've looked at the files and can't see the bad characters.  please help

**Comment by OfficialEsco** [comment]
> > Hello @gdiObjects, The PR could not be validated because there is a merge conflict which adds bad characters to the manifest. Please address the merge conflict and resubmit.
> 
> I've looked at the files and can't see the bad characters. please help

Its just a merge conflict because https://github.com/microsoft/winget-pkgs/pull/44701 got merged

**Comment by gdiObjects** [comment]
> > > Hello @gdiObjects, The PR could not be validated because there is a merge conflict which adds bad characters to the manifest. Please address the merge conflict and resubmit.
> > 
> > 
> > I've looked at the files and can't see the bad characters. please help
> 
> Its just a merge conflict because #44701 got merged

Do I need to do anything?

**Comment by ItzLevvie** [comment]
> Do I need to do anything?

No, it's now available on WinGet because the bot automatically updated it. That means you don't need to do anything.

**Comment by gdiObjects** [comment]
> > Do I need to do anything?
> 
> No, it's now available on WinGet because the bot automatically updated it. That means you don't need to do anything.

Thanks!

**Comment by OfficialEsco** [comment]
> > > Do I need to do anything?
> > 
> > 
> > No, it's now available on WinGet because the bot automatically updated it. That means you don't need to do anything.
> 
> Thanks!

Well, it means you can close the PR =)

**Comment by gdiObjects** [comment]
Thanks for the help and quick turnaround!

**Pull request closed without merging**
