### PR TITLE
Split some of the labelAdded rules into their own files

### PR DESCRIPTION
**Pull request by Trenly**
cc @denelon
 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/109135&drop=dogfoodAlpha

### CODE REVIEW

**Comment by denelon** [comment]
That's a lot of files 😊

**Review by denelon — APPROVED** [review]

**Comment by Trenly** [comment]
[Policy] zip-binary

**Comment by Trenly** [comment]
[Policy] Hardware

**Comment by Trenly** [comment]
[Policy] needs-cla

**Pull request merged**
