### PR TITLE
New version: Oracle.VirtualBox version 6.1.34

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/58903)

### CODE REVIEW

**Review by jedieaston — DISMISSED** [review]

**Comment by OfficialEsco** [comment]
InstallationVerification-x64-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20220427185224
Well thats not good

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Seeing the same here:
image

**Comment by OfficialEsco** [comment]
@denelon what can be done about this kind of blocking-issue?
Would it be considered a bug?
> • Unattended install: Improvements
> • Windows guest: Make driver install smarter

Kinda weird how its not trusting `Microsoft Windows Hardware Compatibility `

**Comment by denelon** [comment]
@OfficialEsco, I don't think I've ever seen this before.

@JohnMcPMS do you have any clues on this one?

**Comment by jedieaston** [comment]
It's definitely signed by Microsoft: https://docs.microsoft.com/en-us/answers/questions/438415/driver-certification-on-windows-10-2016-server-201.html

I think the certificate they are using to sign it isn't shipped with Windows, which is why it's asking about it.

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by vedantmgoyal2009** [comment]
@denelon

**Comment by ItzLevvie** [comment]
@msftbot Blocking-Issue

**Comment by ItzLevvie** [comment]
@msftbot Interactive-Only-Installer

**Review by linghengqian — COMMENTED** [review]
- Looks like #89053 is working fine. Is the current PR really necessary to continue the investigation?

**Pull request closed without merging**
