### PR TITLE
New package: Genesys.GenesysCloud version 2.34.771

### LINKED ISSUE #149330: [Package Request]: Genesys Cloud
### How can we help?

None

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://apps.mypurecloud.com/directory-windows/
Publisher: Genesys Cloud
Package Name: genesys-cloud-windows-2.34.771.exe
Description: Genesys Cloud
Package Version: 2.34.771
Installer URL: https://app.mypurecloud.com/directory-windows/build-assets/2.34.771-90/genesys-cloud-windows-2.34.771.exe

_Originally posted by @tarunsinghhf in https://github.com/microsoft/winget-pkgs/issues/148919#issuecomment-2056847664_

```[tasklist]
### Tasks
- [ ] #149331
```

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] This resolves #149330

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/149331)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-04-15 10:04:03.042 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!69BF535B: (caller: 69AF1A80) LogHr(1) tid(e24) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!69C3B5DD: (caller: 69CD12BF) Exception(1) tid(e24) 8A15005E ] 
> 2024-04-15 10:04:03.042 [REPO] Failed to open available source: msstore
> 2024-04-15 10:04:11.839 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!54D3535B: (caller: 54C31A80) LogHr(1) tid(154c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!54D7B5DD: (caller: 54E112BF) Exception(1) tid(154c) 8A15005E ] 
> 2024-04-15 10:04:11.839 [REPO] Failed to open available source: msstore
> 2024-04-15 10:04:13.203 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x86 with version 14.38.33135.0

(Automated response - build 876.)

**Comment by Dragon1573** [comment]
The manifest is valid on my _Windows Sandbox_. Cannot figure out what was wrong.

```text
11:15:53 (base) D:\...\winget-pkgs   master ≡  ?1 1ms pwsh> .\Tools\SandboxTest.ps1 .\manifests\g\Genesys\GenesysCloud\2.34.771\
--> Validating Manifest
清单具有以下未验证的依赖项;确保它们有效：
  - 程序包
      Microsoft.VCRedist.2015+.x86
清单验证成功。

--> Closing Windows Sandbox

--> Checking dependencies
--> Starting Windows Sandbox, and:
    - Mounting the following directories:
      - C:\Users\Administrator\AppData\Local\Temp\SandboxTest as read-only
      - D:\Workloads\winget-pkgs as read-and-write
    - Installing WinGet
    - Configuring Winget
    - Installing the Manifest 2.34.771
    - Refreshing environment variables
    - Comparing ARP Entries
```

```text
--> Installing WinGet
--> Disabling safety warning when running installer
Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.

--> Configuring Winget
Enabled admin setting 'LocalManifestFiles'.
Enabled admin setting 'LocalArchiveMalwareScanOverride'.


--> Installing the Manifest 2.34.771

Found GenesysCloud [Genesys.GenesysCloud] Version 2.34.771
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Packages
      Microsoft.VCRedist.2015+.x86
(1/1) Found Microsoft Visual C++ 2015-2022 Redistributable (x86) [Microsoft.VCRedist.2015+.x86] Version 14.38.33135.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.visualstudio.microsoft.com/download/pr/71c6392f-8df5-4b61-8d50-dba6a525fb9d/510FC8C2112E2BC544FB29A72191EABCC68D3A5A7468D35D7694493BC8593A79/VC_redist.x86.exe
  ██████████████████████████████  13.2 MB / 13.2 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Downloading https://app.mypurecloud.com/directory-windows/build-assets/2.34.771-90/genesys-cloud-windows-2.34.771.msi
  ██████████▍                     50.0 MB /  143 MB
Cancelled
```

**Comment by stephengillie** [comment]
This might be related:
- https://github.com/microsoft/winget-pkgs/pull/148226

**Comment by Dragon1573** [comment]
@stephengillie - Re-validate in _Windows Sandbox_ again.

image

**Comment by stephengillie** [comment]
Verify: 
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
