### PR TITLE
New version: Jellyfin.JellyfinMediaPlayer version 1.11.1

### PR DESCRIPTION
**Pull request by schembriaiden**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/157130)

### CODE REVIEW

**Comment by KaranKad** [comment]
It has x86 version as well, could you please add that?

**Comment by vikingnope** [comment]
@stephengillie, can you test out the x86 version and let me know what is wrong please?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334957
> 2024-06-08 07:51:53.027 [CLI ] ShellExecute installer failed: 1633
> MSI (s) (50:10) [07:51:52:349]: Product: Jellyfin Media Player -- Installation failed.
> This installation package is not supported by this processor type. Contact your product vendor.
> [0498:0A58][2024-06-08T07:51:52]e000: Error 0x80070661: Failed to install MSI package.
> [0498:0A58][2024-06-08T07:51:52]e000: Error 0x80070661: Failed to execute MSI package.
> [1154:0364][2024-06-08T07:51:52]e000: Error 0x80070661: Failed to configure per-machine MSI package.
> [1154:0364][2024-06-08T07:51:52]e000: Error 0x80070661: Failed to execute MSI package.

(Automated response - build 884.)

**Comment by stephengillie** [comment]
Close with reason: Duplicate of #157721;

**Pull request closed without merging**
