### PR TITLE
Fix NetSurf.NetSurf upgrade loop

### PR DESCRIPTION
**Pull request by Ferk**
Currently NetSurf.NetSurf is constantly requesting for upgrade, since the
version advertised in the yaml doesn't match the version is is being installed.
There are quotes around the installed version as below:

    Name                                       Id                                     Version          Available    Source
    ------------------------------------------------------------------------------------------------------------------------
    NetSurf - NetSurf - Web Browser            NetSurf.NetSurf                        "3.10.0"         3.10.0       winget

This attempts to fix it by making the yaml include the quotes around the
version number to match the installed version string scheme.

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/27914)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Unfortunately, this isn't an easy fix in the package due to YAML parsing.

A workaround will be to run `reg add "HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\NetSurf NetSurf" /v DisplayVersion /t REG_SZ /d 3.10.0 /f` in Command Prompt with administrator privileges.

Please contact the developer to ask them to remove the quotes around the version number.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/27914#pullrequestreview-757241834

EDIT: I don't know if that would work, but let's see.

**Comment by ItzLevvie** [comment]
Okay it does, you just need to update the version folder.

**Comment by Ferk** [comment]
Sorry, I got it the other way around... the installer is actually the one who is providing the quotes around the string, not winget.
So, as long as the author of the software doesn't release a new release with a different version string that doesn't include quotes the problem will persist.

image

But as a way to at least prevent winget from having issues with the package, why not include the version string exactly to reflect the pattern the author used in this release?

I've updated the yaml to match that.

**Comment by Ferk** [comment]
Oh, I see... if the folder needs to match the version string, then I expect it's not possible at all to fis this.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Once WinGet v1.1 is out, try out https://github.com/microsoft/winget-cli/blob/master/schemas/JSON/manifests/v1.1.0/manifest.installer.1.1.0.json#L399-L404.

For now, you'll most likely need to close this or set this PR as a draft and wait for the previews of 1.1.

**Comment by vedantmgoyal2009** [comment]
> Okay it does, you just need to update the version folder to "3.10.0" from 3.10.0
> 
> EDIT: Nope:

I can add quotes on my computer, but when any contributors will clone the repository on their computer, wouldn't their directory structure get corrupt?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
>I can add quotes on my computer, but when any contributors will clone the repository on their computer, wouldn't their directory structure get corrupt?

cc @vedantmgoyal2009: Not entirely sure, but either way, we'll not be able to accept PRs with quotes in folder names, as this will cause UX issues with WinGet.

It'll be much better to wait for the 1.1.0 schema to implement the `DisplayVersion` key into the package.

**Pull request closed without merging**
