### PR TITLE
Delete Manifest: TeamSonarr.Sonarr version 4.0.4.1491

### PR DESCRIPTION
**Pull request by babblebauble**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161745)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://github.com/Sonarr/Sonarr/releases/download/v4.0.4.1491/Sonarr.main.4.0.4.1491.win-x86-installer.exe 
OK

(Automated message - build 911)

**Comment by stephengillie** [comment]
Hi @babblebauble,

This package is still available. Why should the manifest be removed?

**Comment by babblebauble** [comment]
> Hi @babblebauble,
> 
> This package is still available. Why should the manifest be removed?

There can only be one version 4 manifest in the repo since the installer only places the major.minor version information into the registry therefore the validation pipelines cannot differentiate between multiple 4.0 versions. 

Submitting a version update and removal of the previous version in a single PR keeps resulting in an error
>Manifest Error: DisplayVersion declared in the manifest has overlap with existing DisplayVersion range in the index. Existing DisplayVersion range in index: [ [4, 4]]

which takes ages to get resolved so submitting two separate PRs (one to remove the old version and another to update to the latest version) should get around that and be much more expedient.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
