### PR TITLE
Update manifests: ykhwong.DOSBoxSVN-Daum version 20150125

### LINKED ISSUE #133464: DOSBoxSVN-Daum/20150125
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

winget keeps installing the same version of "DOSBox SVN Daum 20150125"

### Steps to reproduce

winget upgrade --all or winget upgrade ykhwong.DOSBoxSVN-Daum

### Actual behavior

It keeps showing up as needing to update when it shouldn't. I checked the GitHub and the author's release page which was updated in 2018. It shows version 20150125 as well. Then checked the installation via RevoUninstaller and winget. They both show the DOSBox SVN Daum installation as version 201501254. Then I manually installed it from GitHub. IT showed version 201501254 as well! It is forcing winget to update over and over again.

### Expected behavior

It should be okay with the last known version.

### Environment

```raw
Windows Package Manager v1.6.3482
Windows: Windows.Desktop v10.0.19044.3803
Package: Microsoft.DesktopAppInstaller v1.21.3482.0
```

### Screenshots and Logs

_No response_

### PR DESCRIPTION
**Pull request by Dragon1573**
## Details

- Add ARP entries of the package
- This may prevent it from an infinite upgrade loop

## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] This resolves #133464

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/157185)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Dragon1573,

This manifest adds Apps and Features entries that aren't present in previous PR versions. These entries should be added to the previous versions, or removed from this version.

(Automated response - build 884.)

**Comment by Dragon1573** [comment]
Should I "backports" these APR entries to previous versions? I can help creating PRs for them.

**Comment by stephengillie** [comment]
Yes, that is a good idea.

**Comment by Dragon1573** [comment]
@stephengillie - Sorry, inspecting all version of package identifier `ykhwong.DOSBoxSVN-Daum`, there's only version `20150125` available. It's the only available version in `winget`.

```text
22:58:06 D:\...\winget-pkgs  [master ≡] 1.26s pwsh> komac list-versions --identifier ykhwong.DOSBoxSVN-Daum
20150125
```

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
