### PR TITLE
Add Tor Browser 9.5

### PR DESCRIPTION
**Pull request by xiaoyang-sde**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1517)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
This app installs on the users desktop which is a bad experience.  In addition I could not find an uninstall string option.  Can you please investigate?

**Comment by chausner** [comment]
Note there is already another PR open for Tor Browser but it appears to be an older version: https://github.com/microsoft/winget-pkgs/pull/1388

**Comment by Berkeley-Reject** [comment]
> This app installs on the users desktop which is a bad experience. In addition I could not find an uninstall string option. Can you please investigate?

Tor Browser is not installed as the classic sense of applications. On Windows, the user should delete the Tor folder or directory named "Tor Browser" to uninstall it.

**Comment by denelon** [comment]
@Berkeley-Reject is there a plan for an uninstall in the future?

**Pull request closed without merging**
