### PR TITLE
New package: Zen-Team.Zen-Browser.Optimized version 1.0.0-a.31

### PR DESCRIPTION
**Pull request by sitiom**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/168942)

### CODE REVIEW

**Comment by sitiom** [comment]
@stephengillie Strange, the pipeline has been running since yesterday 🤔

**Comment by sitiom** [comment]
Works

**Comment by stephengillie** [comment]
Manual Validation ended with:
image

**Comment by stephengillie** [comment]
Manual Validation ended with:
> PUA:Win32/Packunwan

(Automated response - build 888.)

**Comment by sitiom** [comment]
@stephengillie False positive:
- https://github.com/zen-browser/desktop/issues/37

**Comment by sitiom** [comment]
Website seems to be down right now

**Comment by sitiom** [comment]
Website is down right now

**Comment by sitiom** [comment]
Website is down right now

**Comment by stephengillie** [comment]
Verify:
image
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
