### PR TITLE
New version: Facebook.Messenger version 191.0.494866009

### PR DESCRIPTION
**Pull request by zeldrisho**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/112455&drop=dogfoodAlpha

### CODE REVIEW

**Comment by giatrung2012** [comment]
https://www.messenger.com/messenger/desktop/downloadV2/?platform=win redirects to the Url used in the manifest.

**Comment by stephengillie** [comment]
Hi @giatrung2012,

Thanks for submitting this package. The publisher uses a hashed URL, which seems to be unique per user and might be time-based. I'm concerned that this URL might not work for very long before needing an update, or using the same hash for multiple users might violate the publisher's downloading TOS. 
- What are your thoughts? 
- Is this package available from another location, possibly a static vanity URL?

**Comment by giatrung2012** [comment]
- I had used winget to install an old version of this manifest, which uses the regular link (https://www.messenger.com/messenger/desktop/downloadV2/?platform=win) to download the installer. It failed because the manifest hasn't been updated for a while. So, I thought using the redirected link to the specific version would be better, and I made this pull request.
- I had the link in the manifest when I hadn't logged in, and I thought that the link would remain static. However, today, when I visited the regular link, it redirected to a URL with a different hash. Surprisingly, the old URL in the manifest still works.
- If the link in the manifest violates the publisher's downloading terms of service, I suppose I will have to revert back to using the regular link.

**Comment by giatrung2012** [comment]
> Hi @giatrung2012,
> 
> Thanks for submitting this package. The publisher uses a hashed URL, which seems to be unique per user and might be time-based. I'm concerned that this URL might not work for very long before needing an update, or using the same hash for multiple users might violate the publisher's downloading TOS.
> 
> * What are your thoughts?
> * Is this package available from another location, possibly a static vanity URL?

- I had used winget to install an old version of this manifest, which uses the regular link (https://www.messenger.com/messenger/desktop/downloadV2/?platform=win) to download the installer. It failed because the manifest hasn't been updated for a while. So, I thought using the redirected link to the specific version would be better, and I made this pull request.
- I had the link in the manifest when I hadn't logged in, and I thought that the link would remain static. However, today, when I visited the regular link, it redirected to a URL with a different hash. Surprisingly, the old URL in the manifest still works.
- If the link in the manifest violates the publisher's downloading terms of service, I suppose I will have to revert back to using the regular link.

**Pull request closed without merging**
