### PR TITLE
Add Netease Cloud Music

### PR DESCRIPTION
**Pull request by KiruyaMomochi**
aka. 网易云音乐

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/425)

### CODE REVIEW

**Comment by KiruyaMomochi** [comment]
```
URI: https://music.163.com, 
Validation result: Failed, 
Report feedback: https://feedback.smartscreen.microsoft.com/feedback.aspx?v=6&t=512&result=block&type=top&url=aHR0cHM6Ly9tdXNpYy4xNjMuY29t
```

Feedback reported.

**Comment by taotieren** [comment]
大佬能否帮忙看看我这边 PR 的 `KiCad` 是出了什么问题？

https://github.com/microsoft/winget-pkgs/pull/421

**Comment by KiruyaMomochi** [comment]
Will close it if <https://github.com/microsoft/winget-pkgs/pull/622> is merged.

**Comment by KiruyaMomochi** [comment]
Close since #622 has been merged.

**Pull request closed without merging**
