### PR TITLE
New version: MartiCliment.UniGetUI version 3.1.5

### PR DESCRIPTION
**Pull request by marticliment**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/200905)

### CODE REVIEW

**Comment by marticliment** [comment]
The installer is exactly the same as https://github.com/microsoft/winget-pkgs/pull/199437

**Comment by marticliment** [comment]
Can't see why It would fail, the installer is the same of https://github.com/microsoft/winget-pkgs/pull/199437, only the program changes, and the tests passed fine for the last PRs

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
