### PR TITLE
Removal: Google.Chrome accepts EULA on user's behalf

### PR DESCRIPTION
**Pull request by lars-nvhgroup**
"By downloading Chrome, you agree to the [Google Terms of Service](https://policies.google.com/terms) and [Chrome and ChromeOS Additional Terms of Service](https://www.google.com/chrome/terms/)"

Accepts the EULA terms on user's behalf, silently.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131095)

### CODE REVIEW

**Comment by denelon** [comment]
This is not the same as a manifest passing explicit agreements. Users aren't required to accept agreements to download via https://www.google.com/chrome/index.html.

**Comment by denelon** [comment]
The license URL does not have a restriction for download based on: https://www.google.com/intl/en_us/chrome/terms/

**Comment by lars-whta** [comment]
> "By downloading Chrome, you agree to the [Google Terms of Service](https://policies.google.com/terms) and [Chrome and ChromeOS Additional Terms of Service](https://www.google.com/chrome/terms/)"



> This is not the same as a manifest passing explicit agreements. Users aren't required to accept agreements to download via https://www.google.com/chrome/index.html.

It contradicts what is stated here:
https://www.google.com/chrome/

"By downloading Chrome, you agree to the [Google Terms of Service](https://policies.google.com/terms) and [Chrome and ChromeOS Additional Terms of Service](https://www.google.com/chrome/terms/)"

**Comment by lars-whta** [comment]
> This is not the same as a manifest passing explicit agreements. Users aren't required to accept agreements to download via https://www.google.com/chrome/index.html.

How is it not the same? By downloading Chrome the EULA is implicitly accepted, per the language on that page.

**Comment by lars-whta** [comment]
> This is not the same as a manifest passing explicit agreements. Users aren't required to accept agreements to download via https://www.google.com/chrome/index.html.

They definitely are. How can you as a user avoiding the EULA by downloading, if it is accepted by mere downloading?

image

**Comment by Trenly** [comment]
The difference is in how the installer handles the terms and licenses.

If you download the google chrome installer and use the command line switch `/SILENT`, the application will install and run perfectly fine. There is no blocking dialogue which requires accepting the terms of a EULA.  Because the publisher allows for the agreement to be implicit through the use of the silent switch, having the license URL is no different than what Google does by publishing the license URL on their downloads page. Users aren't required to read the EULA to download and install Chrome, so they aren't required to read the EULA to download and install it using WinGet.

With installers that require explicit agreements, users must read the EULA or agree to it before the install can continue. These agreements are the ones that cannot be suppressed with just a `/SILENT` switch. Even though there may be a `--accept-licenses` switch, that is still a form of the user explicitly saying `I have read and agree to the license terms and conditions`. Because the publisher of the installer has required that the user explicitly agree, having the license URL is *not* enough to satisfy the requirement.  Users must be required to either check a box or click accept on the agreement. So, if WinGet doesn't show the agreement and get explicit consent then WinGet cannot pass any form of `--accept-licenses` to the installer because the user, *legally speaking*, has not agreed to the EULA in the manner prescribed by the publisher of the installer.

**Comment by denelon** [comment]
We are actively working on the "verified publisher" feature so we can have the same mechanisms provided by WinGet in the "msstore" source available to the community repository.

**Pull request closed without merging**
