### PR TITLE
Update installer hash of PKI.NCALayer v1.3

### PR DESCRIPTION
**Pull request by Kesantielu**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/62704)

### CODE REVIEW

**Comment by Kesantielu** [comment]
The installer hash has changed, but the version remains the same

**Comment by ItzLevvie** [comment]
```
Enter a pull request number: https://github.com/microsoft/winget-pkgs/pull/62704

This script requires the pull request to have no merge conflicts.

Press any key to continue . . .
```

Your branch seems to be outdated.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/62704#issuecomment-1146177069

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/62704#issuecomment-1146177069

**Pull request closed without merging**
