### PR TITLE
Update: SparkLabs.openvpn-configuration-generator version 1.0.7.1007

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/47017)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by lechacon** [comment]
This looks like a CLI application which fails when run with no arguments.

**Comment by Trenly** [comment]
@OfficialEsco Might want to close and reopen

**Comment by OfficialEsco** [comment]
wingetbot also forgot to add the waiver for Validation-Executable-Error so ya

**Comment by lechacon** [comment]
I had added the waiver manually in #48355 but forgot to merge 🤦‍♀️

**Comment by OfficialEsco** [comment]
I think the new waiver system requires a `@wingetbot waivers add Validation-Executable-Error`?

**Comment by msftrubengu** [comment]
We have a bug that is preventing @wingetbot waivers to work for this particular scenario. I fixed it this week, but it hasn't reach prod. The waiver should have work tho. @lechacon I'm looking into this.

**Pull request merged**
