### PR TITLE
New Version: Astronomer.Astro version 1.26.0

### PR DESCRIPTION
**Pull request by kushalmalani**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150818)

### CODE REVIEW

**Review by sunkickr — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @kushalmalani,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 877.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-04-24 09:53:25.400 [FAIL] Installer failed security check. Url: https://github.com/astronomer/astro-cli/releases/download/v1.26.0/astro_1.26.0_windows_386.exe Result: 0x80004005

(Automated response - build 877.)

**Comment by kushalmalani** [comment]
@stephengillie Not sure what is the issue here. Is there anything needed from my end or do we just need to re-run the scan again?

**Comment by stephengillie** [comment]
Hi @kushalmalani,

Yes, we keep rescanning until it passes. My automation should be retrying these every 18 hours, but lately some seem to be skipped, so I'll need to troubleshoot.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
