### PR TITLE
Delete xmake 2.5.2

### PR DESCRIPTION
**Pull request by hackean-msft**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/11634)

### CODE REVIEW

**Comment by waruqi** [comment]
Why delete it?

**Comment by denelon** [comment]
@waruqi, I believe we are encountering some issues in our validation infrastructure and it looked like this manifest was invalid to the periodic scheduler. @hackean-msft which problem was this manifest related to? What needs to be done to ensure the package can function properly? Do we need to submit a new manifest?

**Comment by denelon** [comment]
@waruqi the hash for this version is incorrect.

**Comment by waruqi** [comment]
> @waruqi the hash for this version is incorrect.

I think that we need only update hash instead of delete.

**Pull request merged**
