### PR TITLE
New version: SomePythonThings.WingetUIStore version 1.6.5

### PR DESCRIPTION
**Pull request by marticliment**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101229)

### CODE REVIEW

**Comment by stephengillie** [comment]
I'm not able to find the cause for this error. It installs and runs normally on a Windows 11 VM. Pipeline logs don't show an error.

**Comment by marticliment** [comment]
I have filed a report regarding the false-positive installer

**Comment by ppvnf** [comment]
is version 1.7.1 also flagged by smartscreen?

**Comment by stephengillie** [comment]
> is version 1.7.1 also flagged by smartscreen?

The only way I know to test is to submit. I believe this usually only blocks specific packages, so other versions on the same host might be unaffected.

**Comment by marticliment** [comment]
I think so, since sometimes I get the Unknown app popup.

I have submitted the installer twice, but they won't accept it as a false positive

**Comment by Trenly** [comment]
Stale PR; Please update or close
[Policy] Needs-Author-Feedback

**Pull request closed without merging**
