### PR TITLE
Add Internet Download Manager

### PR DESCRIPTION
**Pull request by Reset816**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/558)

### CODE REVIEW

**Comment by Reset12138** [comment]
@superusercode do you have any idea about it?

**Comment by superusercode** [comment]
@Reset12138 the CI will randomly stop for no reason sometimes. You can force it again by adding/removing a blank line from the bottom of the manifest.

**Comment by Reset12138** [comment]
> @Reset12138 the CI will randomly stop for no reason sometimes. You can force it again by adding/removing a blank line from the bottom of the manifest.

got it. thanks

**Comment by denelon** [comment]
@Reset12138 The install does not run unattended. It looks like the application is asking for manual intervention to stop any browsers, and prompts for EULA during install. I also see you added some switches to support silent install, but it's still not running unattended. Have you been able to use the manifest and install the file on your local system `winget install -m 6.37.yaml` ?

**Comment by Reset12138** [comment]
> @Reset12138 The install does not run unattended. It looks like the application is asking for manual intervention to stop any browsers, and prompts for EULA during install. I also see you added some switches to support silent install, but it's still not running unattended. Have you been able to use the manifest and install the program on your local system `winget install -m 6.37.yaml` ?

sorry i did't try it. i will try to fix it

**Comment by denelon** [comment]
@Reset12138 We are looking to add meta-data to the manifest so we can identify packages that require EULA during install and can't run unattended in the future. We may just tag the PRs accordingly so we can find the packages that need the attributes added to their manifests after those features have been implemented.

**Comment by Reset12138** [comment]
> @Reset12138 The install does not run unattended. It looks like the application is asking for manual intervention to stop any browsers, and prompts for EULA during install. I also see you added some switches to support silent install, but it's still not running unattended. Have you been able to use the manifest and install the program on your local system `winget install -m 6.37.yaml` ?

btw, I wonder what's the difference between `Silent` and `SilentWithProgress`. I can't find any document about it.

**Pull request closed without merging**
