### PR TITLE
New version: MilosParipovic.OneCommander version 3.65.2

### LINKED ISSUE #135193: [Update Request]: MilosParipovic.OneCommander 3.65.2
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

MilosParipovic.OneCommander

### Package Version

3.65.2

### Please describe the changes you would like to see

There is a new Release avaliable, 3.65.2 at https://www.onecommander.com/OneCommanderSetup3.65.2.0.msi

### PR DESCRIPTION
**Pull request by Exorcism0666**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.0.0 :rocket:

- Resolve: #135193
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135201)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification.
>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

> This PR's version number 3.65.2 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 3.65.2.0, which has 4 parameters.

Is this intentional?

(Automated response - build 629)

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

This manifest adds Apps and Features entries that aren't present in previous PR versions. Should these entries also be added to the previous versions?

(Automated response - build 629.)

**Pull request closed without merging**
