### PR TITLE
Microchip.MicrochipStudio version 7.0.2594

### PR DESCRIPTION
**Pull request by khaffner**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/99005)

### CODE REVIEW

**Comment by khaffner** [comment]
> Hi @khaffner,
> 
> The installation is unattended, but installs a driver which isn't unattended: image
> 
> Unfortunately, installer switches are not usually provided for this situation. Are you aware of an installer switch to have the driver silently install as well?

I'm afraid not.

**Comment by SpecterShell** [comment]
There is only one custom switch available in this installer: `-logtoconsole`

**Comment by ItzLevvie** [comment]
Close with reason: Stale pull request;

**Pull request closed without merging**
