### PR TITLE
New version: FlightGear.FlightGear version 2020.3.11

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/38022)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]
Installs fine on x64 Windows Sandbox:
image

**Comment by arjun-msft** [comment]
@OfficialEsco this doesn't work for me, I've tried twice and I keep getting the following:
image

**Comment by OfficialEsco** [comment]
Levvie prolly installed as Administrator

I just installed as User (1 UAC prompt)
```
Enter a pull request number: 38022

Manifest validation succeeded.
Found FlightGear [FlightGear.FlightGear] Version 2020.3.11
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://sourceforge.net/projects/flightgear/files/release-2020.3/FlightGear-2020.3.11.exe/download
  ██████████████████████████████  1.72 GB / 1.72 GB
Successfully verified installer hash
Starting package install...
Successfully installed

Finding the application in the following registry paths below...
1) Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall
2) Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall
3) Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall



Name          : FlightGear v2020.3.11
Publisher     : The FlightGear Team
Version       : 2020.3.11
Product Code  : FlightGear_2020.3_is1
Registry Path : Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\FlightGear_2020.3_is1
Uninstall     : winget uninstall "FlightGear_2020.3_is1"
```

Do you see anything or does it just throw cancelled by user after the download?

@jedieaston @Trenly would you mind validating?

**Comment by ItzLevvie** [comment]
I only get "You cancelled the installation." when I don't do anything with the UAC prompt (which is what happened when I went to the bathroom for 15 minutes):
image

I re-tried it again when I was back on my PC and UAC poped up.
image
image

**Comment by arjun-msft** [comment]
Got it to work here as well, thank you @OfficialEsco and @ItzLevvie!

**Pull request merged**
