### PR TITLE
New package: AlgorandFoundation.AlgoKit version 2.2.2

### PR DESCRIPTION
**Pull request by algofoundation**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? Yes, resolves https://github.com/microsoft/winget-pkgs/issues/165104

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/165113)

### CODE REVIEW

**Comment by algofoundation** [comment]
@microsoft-github-policy-service agree company="Algorand Foundation"

**Comment by stephengillie** [comment]
Verify:
image
Advanced options:
image

Hi @algofoundation,

Since this package displays version `2.2.1`, but its installer writes `2.2.2.0` to the Registry, it should probably have a `DisplayVersion`. This way, the package manager could display `2.2.1` to match the application. (Or have the application and Registry match, if possible.) What do you think?

**Comment by neilcampbell** [comment]
@stephengillie Thanks! `--version` should absolutely be outputting 2.2.2, so we'll get this fixed.

**Comment by neilcampbell** [comment]
@stephengillie The exe has been updated to correctly represent the version and an updated installer msix has been published. We've also refreshed the hashes in `.installer.yaml` file.

**Comment by stephengillie** [comment]
> @stephengillie The exe has been updated to correctly represent the version and an updated installer msix has been published. We've also refreshed the hashes in `.installer.yaml` file.
> 
> With regards to the `DisplayVersion` how do we set that with an msix?

The `DisplayVersion` would still be set under `AppsAndFeaturesEntries`.

**Comment by stephengillie** [comment]
Verify:
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
