### PR TITLE
Unsupported - Samsung.NVMExpressDriver version 3.3.0.2003

### PR DESCRIPTION
**Pull request by Masamune3210**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/27328)

### CODE REVIEW

**Comment by Masamune3210** [comment]
In my vm, iirc the only prompt it threw was after install, complaining if it didn't find any applicable hardware for the driver. As far as I could tell, the driver itself installed fine unless applying it to the hardware is considered still part of the install

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
This is the issue I see and clicking the OK button doesn't actually install it even though it says "Successfully installed" and returns 0 as exit code:
image

**All manifests need to be installed without special hardware and no keyboard/mouse key/button presses (a.k.a. fully unattended without requiring the user's attention that means no prompts for dependencies/driver installation, etc.)**

**Comment by Masamune3210** [comment]
My bad, trusted the error code meant that it at least was in the driver store and had actually installed. Will close

**Comment by ItzLevvie** [comment]
> My bad, trusted the error code meant that it at least was in the driver store and had actually installed. Will close

It'll show up in Control Panel as well:
image

**Pull request closed without merging**
