### PR TITLE
Add manifest for Enpass v6.4.2.669

### PR DESCRIPTION
**Pull request by SaifAqqad**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/324)

### CODE REVIEW

**Comment by ollieharker** [comment]
Hi, I had this issue just - the issue is that your manifest has been uploaded as a binary file (Have a look at the 'Files Changed' tab. Can I suggest recommitting it as a non-binary file? It worked for me :)

**Comment by SaifAqqad** [comment]
> 
> 
> Hi, I had this issue just - the issue is that your manifest has been uploaded as a binary file (Have a look at the 'Files Changed' tab. Can I suggest recommitting it as a non-binary file? It worked for me :)

Thanks will try that now :D

**Comment by SaifAqqad** [comment]
> 
> 
> Greetings SaifAqqad
> During installation testing, this application failed to install with out user input. Did you forget to add Silent or SilentWithProgress switches?
> 
> Please investigate a fix and resubmit the Pull Request.

I already included the silent switch in the last commit, and I just tested the manifest on 2 devices and it worked perfectly 🤔

**Comment by denelon** [comment]
I tested the manifest. It looks like Enpass requires the user to accept a EULA before the application will install. Ideally silent install doesn't require any user input and will complete "unattended".

**Comment by SaifAqqad** [comment]
> 
> 
> I tested the manifest. It looks like Enpass requires the user to accept a EULA before the application will install. Ideally silent install doesn't require any user input and will complete "unattended".

I tried running winget install with --silent and it installs without prompting the user for a EULA, isn't this how it's supposed to work?

**Comment by ollieharker** [comment]
> > Hi, I had this issue just - the issue is that your manifest has been uploaded as a binary file (Have a look at the 'Files Changed' tab. Can I suggest recommitting it as a non-binary file? It worked for me :)
> 
> Thanks will try that now :D

I've raised this as an "issue" now https://github.com/microsoft/winget-pkgs/issues/411 , though I guess it's more for informational purposes.

**Comment by SaifAqqad** [comment]
> 
> 
> I tested the manifest. It looks like Enpass requires the user to accept a EULA before the application will install. Ideally silent install doesn't require any user input and will complete "unattended".

Should install silently as intended now :D

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
