### PR TITLE
New package: iwalton3.plex-mpv-shim version 1.11.0

### LINKED ISSUE #192489: [Package Request]: plex-mpv-shim
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/iwalton3/plex-mpv-shim
Publisher: iwalton3
Package Name: plex-mpv-shim
Description: Cast media from Plex Mobile and Web apps to MPV. (Unofficial) 
Package Version: [v1.11.0](https://github.com/iwalton3/plex-mpv-shim/releases/tag/v1.11.0)
Installer Url: https://github.com/iwalton3/plex-mpv-shim/releases/download/v1.11.0/plex-mpv-shim_1.11.0_installer.exe

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #192489

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

## Manual validation

Image
Image

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/192829)

### CODE REVIEW

**Comment by Dragon1573** [comment]
> During installation testing, this application failed to install without user input. Did you forget to add Silent or SilentWithProgress switches?
> 
> This can also happen when a dependency is missing. You can test with https://github.com/microsoft/winget-pkgs#test-your-manifest.
> 
> Please investigate a fix and resubmit the Pull Request.
> 
> You may also try using the [Windows Package Manager Manifest Creator](https://github.com/microsoft/winget-create) to determine the proper installer type. If the installer type is MSIX, MSI, or a known installer technology like NullSoft, Inno, etc. the wingetcreate tool can detect them and the winget client will know what switches to pass. If it's a .exe installer of an unknown type, you will need to search to determine the proper switches for Silent and SilentWithProgress.
> 
> Template: msftbot/validationError/installation/unattended

Unable to reproduce the problem in _Windows Sandbox_ instance. It might be cause by an incorrect "architecture detection" from _Komac_.

**Comment by Dragon1573** [comment]
Can't determine what was wrong. Everything works fine in _Windows Sandbox_.

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 899.)

**Comment by stephengillie** [comment]
Hi @Dragon1573,

Manual Validation ended with:
image

Should `Plex.PlexMediaServer` or a similar package be a dependency?

Verify:
image

**Comment by Dragon1573** [comment]
Manual validate on the physical device again. Nothing wrong with it.

```text
11:10:57 D:\...\winget-pkgs  [issues/192489 ≡] 124ms 0x80070003 pwsh> winget install -m .\manifests\i\iwalton3\plex-mpv-shim\1.11.0\ -l D:\Applications\iwalton3\plex-mpv-shim\
已找到 Plex MPV Shim [iwalton3.plex-mpv-shim] 版本 1.11.0
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://github.com/iwalton3/plex-mpv-shim/releases/download/v1.11.0/plex-mpv-shim_1.11.0_installer.exe
  ██████████████████████████████  38.3 MB / 38.3 MB
已成功验证安装程序哈希
正在启动程序包安装...
安装程序将请求以管理员身份运行，需要提示。
已成功安装
```

image
image

**Comment by Dragon1573** [comment]
Duplicate case of https://github.com/microsoft/winget-pkgs/pull/192829#issuecomment-2492631987.

CC @stephengillie 😕

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
