### PR TITLE
Remove: GNU.Nano version 2.7.5

### PR DESCRIPTION
**Pull request by coolplaylinbot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136734)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
This is the only version in the repo; Is there a new version available instead of just removing the old one?

**Comment by CoolPlayLin** [comment]
New version is in #136827.

**Comment by stephengillie** [comment]
> New version is in #136827.

I'll merge this PR just after merging the above.

**Comment by Jason-Clark-FG** [comment]
Unfortunately, this old version (`2.7.5`) is the only one that works well in Windows. I think we should keep it for now. There's a PR to fix the [download URL](https://github.com/microsoft/winget-pkgs/pull/137354) for this version.

**Comment by stephengillie** [comment]
Duplicate of https://github.com/microsoft/winget-pkgs/pull/137354

**Pull request closed without merging**
