### PR TITLE
New version: Hitencent.JisuPDFToWord version 3.0.0.9

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#7608](https://github.com/SpecterShell/Dumplings/actions/runs/10551976959).

<details>

<summary>Log</summary>

````
Updated: 3.0.0.8 → 3.0.0.9
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/169346)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2145844848
> 2024-08-25 18:49:36.827 [CORE] DeliveryOptimization error: 0x80190190, extended error: 0x00000000
> 2024-08-25 18:49:36.894 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!560857EB: (caller: 56085E1C) Exception(1) tid(16b4) 80190190 Bad request (400).
> 2024-08-25 18:49:38.415 [CORE] Download request failed. Returned status: 400
> 2024-08-25 18:49:38.415 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!5607FA75: (caller: 56080E2B) Exception(2) tid(16b4) 80190190 Bad request (400).
> 2024-08-25 18:49:38.619 [CLI ] Failed to download, waiting a bit and retry. Url: https://dl.jisupdftoword.com/jisupdftoword_setup_3.0.0.9.exe
> 2024-08-25 18:49:44.435 [CORE] DeliveryOptimization error: 0x80190190, extended error: 0x00000000
> 2024-08-25 18:49:44.435 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!560857EB: (caller: 56085E1C) Exception(3) tid(16b4) 80190190 Bad request (400).
> 2024-08-25 18:49:44.681 [CORE] Download request failed. Returned status: 400
> 2024-08-25 18:49:44.681 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!5607FA75: (caller: 56080E2B) Exception(4) tid(16b4) 80190190 Bad request (400).

(Automated response - build 888.)

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/pull/169367#issuecomment-2310589392

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
