### PR TITLE
New version: SomePythonThings.WingetUIStore version 2.0.3

### PR DESCRIPTION
**Pull request by marticliment**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/113776&drop=dogfoodAlpha

### CODE REVIEW

**Comment by marticliment** [comment]
is the same issue as always

**Comment by stephengillie** [comment]
> is the same issue as always

Hi @martincliment,

Sorry, yes. WinGet installs this successfully then exits with a 1 code. I do not know why.

**Comment by MisterT87** [comment]
@stephengillie just a question about this: what would you do to fix it ? asking coz of automate winget PR process...
I thought first time, to exclude / try without vc_redis installer ?

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
> @stephengillie just a question about this: what would you do to fix it ? asking coz of automate winget PR process... I thought first time, to exclude / try without vc_redis installer ?

Hi @MisterT87,

Unfortunately, I don't have enough information about the cause to suggest a solution. I only know that it's occurring.

**Pull request merged**
