### PR TITLE
Move TheDocumentFoundation.LibreOffice 7.5.0.3 to TheDocumentFoundati…

### PR DESCRIPTION
**Pull request by Trenly**
…on.LibreOffice.LTS 7.5.0.3

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/147237)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Error occurred while downloading installer from https://downloadarchive.documentfoundation.org/libreoffice/old/7.5.0.3/win/x86_64/LibreOffice_7.5.0.3_Win_x86-64.msi. 0x80072EE2.
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 
 4/1/2024 9:09:15 PM

(Automated response - build 876.)

**Comment by stephengillie** [comment]
URL: https://downloadarchive.documentfoundation.org/libreoffice/old/7.5.0.3/win/x86_64/LibreOffice_7.5.0.3_Win_x86-64.msi 
Status Code: 200

(Automated message - build 876)

**Comment by og-mrk** [comment]
Hello @stephengillie
The status code 200 indicates that the GET Request was successful, [reference link](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200), **_see screenshot below for evidence_**.

image


</br>

[Other PRs](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+is%3Aopen+Move+TheDocumentFoundation.LibreOffice+label%3AError-Installer-Availability) that suffer the same issue

**Comment by Trenly** [comment]
@og-mrk - I'm sure Stephen is aware that status code 200 is a success; The tooling Stephen has built first fetches the information from the pipeline runs whenever the `Error-Installer-Availability` label is on a PR. After this, it checks to see if it can access the URL and get a successful response before posting the response code into the issue. This is to help identify when the label is caused by an error like a 503, or if it's something else.

In this case, TheDocumentFoundation rate limits concurrent downloads, so having multiple PRs submitted at the same time causes most of them to be timed out

**Comment by og-mrk** [comment]
> @og-mrk - I'm sure Stephen is aware that status code 200 is a success; The tooling Stephen has built first fetches the information from the pipeline runs whenever the `Error-Installer-Availability` label is on a PR. After this, it checks to see if it can access the URL and get a successful response before posting the response code into the issue. This is to help identify when the label is caused by an error like a 503, or if it's something else.

yahh my bad, and it's interesting how this works.

> In this case, TheDocumentFoundation rate limits concurrent downloads, so having multiple PRs submitted at the same time causes most of them to be timed out

Also I've never in a million years thought this could be the reason 😆
And now I guess it's all smooth sailing, so the tests should pass without problems, thanks for info @Trenly 👍

**Comment by Trenly** [comment]
[Policy] Reset Labels - This is just moving the existing manifest, so the warnings are expected

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
