### PR TITLE
Update FormatFactory to 5.4.5.1

### PR DESCRIPTION
**Pull request by auanasgheps**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3673)

### CODE REVIEW

**Comment by auanasgheps** [comment]
Oh gosh every time I update this package this error is thrown.
This application contains a PUP but the silent installer skips it. The actual application is legit.
Please check #3420 #3360 #1445

**Comment by KevinLaMS** [comment]
Thanks for the detail.

**Comment by auanasgheps** [comment]
Outdated, closing.

**Pull request closed without merging**
