### PR TITLE
New version: GiulioSorrentino.CBriscola.WPF version 0.7.0

### PR DESCRIPTION
**Pull request by GiulianoSpaghetti**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/144093)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @numerunix,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-12 17:30:58.349 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF828B1C11F: (caller: 00007FF8288A8D6F) LogHr(1) tid(17a8) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF828A22B08: (caller: 00007FF828ACBC20) Exception(1) tid(17a8) 8A15005E ] 
> 2024-03-12 17:30:58.349 [REPO] Failed to open available source: msstore
> 2024-03-12 17:31:00.253 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF828A22B08: (caller: 00007FF828ACBC20) Exception(1) tid(17a8) 8A15005E 
> 2024-03-12 17:31:06.248 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF80BA6C11F: (caller: 00007FF80B7F8D6F) LogHr(1) tid(214) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF80B972B08: (caller: 00007FF80BA1BC20) Exception(1) tid(214) 8A15005E ] 
> 2024-03-12 17:31:06.248 [REPO] Failed to open available source: msstore
> 2024-03-12 17:31:37.835 [FAIL] Installer failed security check. Url: https://github.com/numerunix/CBriscola.WPF/releases/download/0.7/CBriscola.WPF-0.7.0-amd64.msi Result: 0x80004005
> MSI (s) (0C:28) [17:31:20:266]: Executing op: ComponentRegister(ComponentId={AEF93A1C-8596-5F1B-918E-36EDE0A6E322},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.2\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1)
> MSI (s) (0C:28) [17:31:21:844]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,)
> Property(S): ErrorDialog = ErrorDlg

(Automated response - build 870.)

**Comment by numerunix** [comment]
it's the smart screen

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-13 20:28:13.695 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF8D0CFC11F: (caller: 00007FF8D0A88D6F) LogHr(1) tid(ba4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF8D0C02B08: (caller: 00007FF8D0CABC20) Exception(1) tid(ba4) 8A15005E ] 
> 2024-03-13 20:28:13.695 [REPO] Failed to open available source: msstore
> 2024-03-13 20:28:15.657 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF8D0C02B08: (caller: 00007FF8D0CABC20) Exception(1) tid(ba4) 8A15005E 
> 2024-03-13 20:28:21.184 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF8BB15C11F: (caller: 00007FF8BAEE8D6F) LogHr(1) tid(aa0) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF8BB062B08: (caller: 00007FF8BB10BC20) Exception(1) tid(aa0) 8A15005E ] 
> 2024-03-13 20:28:21.184 [REPO] Failed to open available source: msstore
> 2024-03-13 20:29:00.945 [FAIL] Installer failed security check. Url: https://github.com/numerunix/CBriscola.WPF/releases/download/0.7/CBriscola.WPF-0.7.0-amd64.msi Result: 0x80004005
> MSI (s) (C0:38) [20:28:34:133]: Executing op: ComponentRegister(ComponentId={7D8F811F-FA90-5B50-B79B-7BEBC828F0A0},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.3\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1)
> MSI (s) (C0:38) [20:28:35:602]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,)
> Property(S): ErrorDialog = ErrorDlg

(Automated response - build 870.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
