### PR TITLE
Update: SuperTux.SuperTux version 0.6.3

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/47033)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Comment by Trenly** [comment]
@OfficialEsco Is this maybe an x86 package causing the `Validation-Executable-Error`?
```
Launching executable file: C:\Program Files (x86)\SuperTux\bin\supertux2.exe
Executable C:\Program Files (x86)\SuperTux\bin\supertux2.exe ran for 10 seconds: False
Executable C:\Program Files (x86)\SuperTux\bin\supertux2.exe returned exit code: -1073741819
Launching executable file: C:\Users\validator\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\SuperTux\SuperTux.lnk
Executable C:\Users\validator\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\SuperTux\SuperTux.lnk ran for 10 seconds: False
Executable C:\Users\validator\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\SuperTux\SuperTux.lnk returned exit code: -1073741819
```

**Comment by Trenly** [comment]
Rip me 😢

**Comment by OfficialEsco** [comment]
Yeah i'm pretty sure the Validation don't check the exact bit, it just tries to execute it, if the installer is wrong it will be unattended because its stuck on a "This OS is not supported", if it says `Validation-Executable-Error` it failed to execute the exe, which can be a issue for x64 software on x86 OS, but since this failed on x64 OS it can actually be a dependency issue now that i think about it

Result: It IS x32 bit, but no dependency, maybe its GPU based?
VirtualBoxVM_6tpCPCwmRV

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
