### PR TITLE
NetDocuments.ndSync version 2.5.0.3171

### PR DESCRIPTION
**Pull request by EmmaTheEmu**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136778)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with:
> NetDocuments® Terms of Use Acceptance of the TERMS OF USE THESE NETDOCUMENTS TERMS OF USE (THESE “TERMS OF USE”) STATE THE TERMS AND CONDITIONS UPON WHICH ACCESS TO OR USE OF THIS WEBSITE, THE NETDOCUMENTS SERVICE AND RELATED SERVICES (THE "SERVICE") OFFERED BY NETDOCUMENTS SOFTWARE INC. (“NETDOCUMENTS”) MAY BE PROVIDED TO INDIVIDUALS WHO USE OR SEEK TO USE THE SERVICE (EACH, A “USER” OR “YOU”). THESE TERMS OF USE ARE NOT A CUSTOMER SUBSCRIPTION AGREEMENT AND DO NOT GRANT YOU THE RIGHT TO USE THE WEBSITE OR THE SERVICE. ALL USERS OF THE SERVICE MUST BE AUTHORIZED TO USE THE SERVICE BY A CUSTOMER OF NETDOCUMENTS (AN “AUTHORIZING CUSTOMER”) WHO HAS EXECUTED A SEPARATE SERVICE AGREEMENT WITH NETDOCUMENTS (THE SERVICE AGREEMENT WITH SUCH AUTHORIZING CUSTOMER, THE “SERVICE AGREEMENT”) AND HAS AUTHORIZED THE USER TO USE ALL OR A PORTION OF THE SERVICE THROUGH THE AUTHORIZING CUSTOMER’S ACCOUNT. ANY USE OF THE SERVICE IS SUBJECT TO THE TERMS OF CONDITIONS OF THE SERVICE AGREEMENT OF THE AUTHORIZING CUSTOMER, MAY BE TERMINATED BY THE AUTHORIZING CUSTOMER AT ANY TIME FOR ANY OR NO REASON AND MAY BE TERMINATED BY NETDOCUMENTS AS PROVIDED IN THESE TERMS OF USE. OTHER THAN AS EXPRESSLY PROVIDED HEREIN, THESE TERMS OF USE IMPOSE NO OBLIGATIONS ON NETDOCUMENTS TO ANY USER OR THE AUTHORIZING CUSTOMER, AND NO USER SHALL ACQUIRE ANY RIGHT AGAINST NETDOCUMENTS BY VIRTUE OF THESE TERMS OF USE OR THE USER’S USE OF THIS WEBSITE OR THE SERVICE. YOU MAY NOT USE THIS WEBSITE OR THE SERVICES WITHOUT ACCEPTING THESE TERMS OF USE.  Please read these Terms of Use carefully before your use any aspect of the Service.  By using www.netdocuments.com (including all subpages, this “Website”) or by clicking to accept or agree to these Terms of Use when the option is made available to you, you accept and agree to be bound and abide by these Terms of Use and our Privacy Policy found at http://www.netdocuments.com/en-us/TermsConditions/PrivacyPolicy and incorporated herein by reference. If you do not want to agree to these Terms of Use, you may not use this Website or the Service. These Terms of Use are in addition to any terms, conditions, representations, warranties and covenants in the Service Agreement with the Authorizing Customer.   This Website and the Service is offered and available to users who are 18 years of age or older, reside in the United States and have either been provided a username and password by an Authorizing Customer or are viewing the Website in order to evaluate a possible subscription to the Service. By using this Website or the Service, you represent and warrant that you are of legal age to form a binding contract with NetDocuments and meet all of the foregoing eligibility requirements. If you do not meet all of these requirements, you must not access or use the Website or the Service.   Changes to the Terms of Use  Subject to any restrictions in the Service Agreement, NetDocuments may revise and update these Terms of Use from time to time in its sole discretion. All changes to these Terms of Use are effective immediately when we post them and apply to all access and use of the Website and the Service thereafter. NetDocuments may require acceptance on the Website of such modified Terms of Use as a condition to any Users’ initial use or continued use of the Website and the Service. Notwithstanding the foregoing, your continued use of the Website and the Service shall constitute acceptance of any revisions and updates to these Terms of Use. You are expected to check this page from time to time so that you are aware of any changes these Terms of Use, as they are binding on you.  Accessing the Service and Account Security Subject to any limitations in the Service Agreement, NetDocuments reserves the right to modify the Website and the Service in its sole discretion without notice. NetDocuments will not be liable to any User if for any reason all or any part of the Website and the Service is unavailable at any time or for any period. From time to time, NetDocuments may restrict access to some parts of Website and  the Service, or the entire Website and the Service, to Users for scheduled maintenance or for other purposes.  You acknowledge that use of the Service requires compliance with certain minimum requirements for hardware, systems software and Internet browsers for User workstations and the download of certain desktop applications software on you workstation, as well as Internet connectivity. Such minimum recommended levels can be found at https://vault.netvoyage.com/neWeb2/helpRedirect.aspx?topic=service-requirements and may be amended from time to time by NetDocuments. Your failure to comply with these requirements may cause the Service not function at all or to function poorly. You are responsible for ensuring that you systems meet all minimum requirements, as modified from time to time.   To access the Service or some of the resources it offers, Users may be asked to provide certain registration details or other information. It is a condition of your use of the Service that all the information you provide on the Service is correct, current and complete, and you represent that all such information will be correct, current and complete. You agree that all information you provide to register with the Service or otherwise, including but not limited to through the use of any interactive features on the Service, is governed by our Privacy Policy at http://www.netdocuments.com/en-us/TermsConditions/PrivacyPolicy, which NetDocuments may update from time to time in its discretion, and you consent to all actions NetDocuments takes consistent with our Privacy Policy.   If you are provided with a user name, password or any other piece of information as part of our security procedures, you must treat such information as confidential and must not provide third parties with, or permit third parties to use, user names, passwords or other security information. You agree not to permit any other person to authorize the account associated with your user name and password (sometimes referred to as your “account”) and not to use the account of, or to impersonate, any other person. You agree to notify, or to cause the Authorizing Customer to notify, NetDocuments immediately of any unauthorized access to or use of your user name or password or any other breach of security with respect to the Service involving your account. You also agree to ensure that you exit from your account at the end of each session. Users should use particular caution when accessing account from a public or shared computer so that others are not able to view or record their respective password or other personal information.  NetDocuments shall have the right to disable any user name, password or other identifier, at any time in our sole discretion for any or no reason, including if, in our opinion, any User or Authorizing Customer has violated any provision of these Terms of Use.   Users to Look to Authorizing Customer for Support  NetDocuments shall have no obligation to provide support to any User with respect to the Service. Users shall direct requests for support to the IT personnel or help desk of the Authorizing Customer and shall not contact NetDocuments directly to request Support. If NetDocuments directly or indirectly provides any support to a User, no standards of service or other duties shall govern such support.  Deletion of Documents upon Termination of Service PRIOR TO THE TERMINATION OF THE AUTHORIZING CUSTOMER’S SERVICE AGREEMENT, IT IS THE OBLIGATION OF USER AND/OR AUTHORIZING CUSTOMER TO MAKE ANY REQUIRED COPIES OF DOCUMENTS AND DATA IN THE REPOSITORY OF THE AUTHORIZING CUSTOMER (“CUSTOMER DATA”, AND/OR TO TRANSITION SUCH CUSTOMER DATA ANOTHER DATABASE OR SERVICE. UNDER THE SERVICE AGREEMENT, AUTHORIZING CUSTOMER IS PERMITTED TO DELETE ALL CUSTOMER DATA, INCLUDING ANY DATA ADDED TO THE REPOSITORY BY YOU, IN ITS REPOSITORY AT ANY TIME. FOLLOWING THE TERMINATION OF THE SERVICE AGREEMENT (AND ANY TRANSITION PERIOD) DESCRIBED IN THE SERVICE AGREEMENT, NETDOCUMENTS IS AUTHORIZED TO DELETE ALL CUSTOMER DATA, INCLUDING ANY CUSTOMER DATA ADDED TO THE REPOSITORY BY YOU. NETDOCUMENTS WILL NOT BE LIABLE UNDER ANY LEGAL THEORY FOR ANY LOSS OR DAMAGE CAUSED BY THE DELETION OF ALL CUSTOMER DATA OF THE AUTHORIZING CUSTOMER OR USER FROM THE SERVICE FOLLOWING THE TERMINATION OF THE SERVICE AGREEMENT (AND ANY TRANSITION PERIOD) OR FOR ANY DELETIONS OF CUSTOMER DATA BY THE AUTHORIZING CUSTOMER OR ANY OTHER USERS OF THE AUTHORIZING CUSTOMER.  Intellectual Property Rights The Service and its entire contents, features and functionality are owned by the NetDocuments, its licensors or other providers of such material and are protected by United States and international copyright, trademark, patent, trade secret and/or other intellectual property or proprietary rights laws. No right, title or interest in or to the Service or any rights associated with the service is transferred to Users. Users shall not copy, modify, sublicense, distribute, rent, lease, convey, translate, disassemble, reverse engineer or decompile any portion of the Service and related NetDocuments software and other intellectual property. Any use of the Service not expressly permitted by these Terms of Use is a breach of these Terms of Use and may violate copyright, trademark and other laws. If any User violates these Terms of Use, the rights of such User may be terminated immediately.  Trademarks The marks NetDocuments® and all related names, logos, products and service names, designs and slogans are trademarks of NetDocuments or its affiliates or licensors. You must not use such marks without the prior written permission of NetDocuments. All other names, logos, product and service names, designs and slogans on this Service or the Website (the “Website”) are the trademarks of their respective owners.  Prohibited Uses You may use the Service only for lawful purposes and in accordance with these Terms of Use. You agree not to use the Service:  • in any way that violates any applicable federal, state, local or international law or regulation (including, without limitation, any laws regarding the export of data or software to and from the US or other countries);  • to impersonate or attempt to impersonate NetDocuments, a NetDocuments employee, another user or any other person or entity; and • to engage in any other conduct that restricts or inhibits anyone's use or enjoyment of the Service, or which, as determined by us, may harm NetDocuments or users of the Service or expose them to liability. Additionally, you agree not to:  • use the Service in any manner that could disable, overburden, damage, or impair the Service or interfere with any other party's use of the Service, including their ability to engage in real time activities through the Service; • use any robot, spider or other automatic device, process or means to access the Service for any purpose, including monitoring or copying any of the material from the Service; • use any device, software or routine that interferes with the proper working of the Service; • introduce any viruses, trojan horses, worms, logic bombs or other material which is malicious or technologically harmful; • attempt to gain unauthorized access to, interfere with, damage or disrupt any parts of the Service, the server on which the Service is stored or the Website, or any server, computer or database connected to the Service;  • attack the Service via a denial-of-service attack or a distributed denial-of-service attack; or • otherwise attempt to interfere with the proper working of the Service. Legal Demand for Authorizing Customer and User Information NetDocuments disclaims any interest in the Customer Data. NetDocuments may from time to time receive a subpoena, order from a court, tribunal or government entity with jurisdiction or other legally binding demand (collectively, a “Legal Demand”) to obtain access to or copies of Customer Data. Upon such receipt, NetDocuments will, unless prohibited by the terms of the Legal Demand or governing law, promptly provide written notice to the Authorizing Customer, not to any Users, of such Legal Demand. To the extent the Authorizing Customer does not eliminate the legal efficacy, by means of a successful motion to quash or other action of the Legal Demand, NetDocuments may comply with the Legal Demand. This paragraph is not intended to, and does not, create a duty on the part of NetDocuments to preserve Customer Data if there is threatened or pending litigation, which shall be the responsibility of the Authorizing Customer and the User. NETDOCUMENTS WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY NETDOCUMENTS ‘S PRODUCTION OF CUSTOMER DATA, OR ANY OTHER ACTION OF OMISSION, IN COMPLIANCE WITH THIS PARAGRAPH.  Reliance on Information Posted  The information presented on the Website or through the Service is made available solely for general information purposes. NetDocuments does not warrant the accuracy, completeness or usefulness of this information. Any reliance you place on such information is strictly at your own risk.  Changes to Website  NetDocuments may update the content on this Website from time to time in its discretion, but its content is not necessarily complete or up-to-date. Any of the material on this Website may be out of date at any given time, and we are under no obligation to update such material.  Linking to the Service and Social Media Features You may link to our homepage, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it, but you must not establish a link in such a way as to suggest any form of association, approval or endorsement on our part without our express written consent.  Links from the Service If the Service or the Website contains links to other sites and resources provided by third parties, these links are provided for your convenience only. This includes links contained in advertisements, including banner advertisements and sponsored links. NetDocuments has no control over the contents of those sites or resources, and accepts no responsibility for them or for any loss or damage that may arise from your use of them. If you decide to access any of the third party websites linked to the Service or the Website, you do so entirely at your own risk and subject to the Terms of Use of use for such websites.  Geographic Restrictions NetDocuments is based in the state of Utah in the United States. NetDocuments provides the Service through this Website for use only by persons located in the United States. NetDocuments make no claims that the Service or any of its content is accessible or appropriate outside of the United States. Access to the Service may not be legal by certain persons or in certain countries. If you access the Service from outside the United States, you do so on your own initiative and are responsible for compliance with local laws.  Disclaimer of Warranties You acknowledge and agree that NetDocuments cannot and does not guarantee or warrant that files available for downloading from the Website or the Service, or any Customer Data, will be free of viruses or other destructive code. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for anti-virus protection and accuracy of data input and output, and for maintaining a means external to our site for any reconstruction of any lost data. NETDOCUMENTS WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY A DISTRIBUTED DENIAL-OF-SERVICE ATTACK, VIRUSES OR OTHER TECHNOLOGICALLY HARMFUL MATERIAL THAT MAY INFECT YOUR COMPUTER EQUIPMENT, COMPUTER PROGRAMS, DATA OR OTHER PROPRIETARY MATERIAL DUE TO YOUR USE OF THE WEBSITE OR THE SERVICE OR ITEMS OBTAINED THROUGH THE WEBSITE OR THE SERVICE OR TO YOUR DOWNLOADING OF ANY MATERIAL POSTED ON IT, OR ON ANY WEBSITE LINKED TO IT.  YOUR USE OF THE WEBSITE AND THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER NETDOCUMENTS OR IMPLIED. NEITHER NETDOCUMENTS NOR ANY PERSON ASSOCIATED WITH NETDOCUMENTS MAKES ANY WARRANTY OR REPRESENTATION TO ANY USER WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY, FUNCTIONALITY OR AVAILABILITY OF THE SERVICE. WITHOUT LIMITING THE FOREGOING, NEITHER NETDOCUMENTS NOR ANYONE ASSOCIATED WITH NETDOCUMENTS REPRESENTS OR WARRANTS THAT THE SERVICE WILL BE RELIABLE, ERROR-FREE OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS OR THAT THE SERVICES WILL OTHERWISE MEET THE NEEDS OR EXPECTATIONS OF ANY USER.  NETDOCUMENTS HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT AND FITNESS FOR PARTICULAR PURPOSE.  THE FOREGOING DOES NOT AFFECT ANY WARRANTIES WHICH CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.  Disclaimer of Liability IN NO EVENT WILL NETDOCUMENTS, ITS AFFILIATES OR THEIR LICENSORS, SERVICE PROVIDERS, EMPLOYEES, AGENTS, OFFICERS OR DIRECTORS BE LIABLE FOR DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE, OR INABILITY TO USE, THE SERVICES OR ANY WEBSITES ASSOCIATED WITH IT, INCLUDING ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO, PERSONAL INJURY, PAIN AND SUFFERING, EMOTIONAL DISTRESS, LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, LOSS OF DATA, AND WHETHER CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT OR OTHERWISE, EVEN IF FORESEEABLE.  THE FOREGOING DOES NOT AFFECT ANY LIABILITY WHICH CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.  Indemnification You agree to defend, indemnify and hold harmless NetDocuments, its affiliates, licensors and service providers, and its and their respective officers, directors, employees, contractors, agents, licensors, suppliers, successors and assigns from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses or fees (including reasonable attorneys' fees) arising out of or relating to your violation of these Terms of Use or your use of the Website or the Service other than as expressly authorized in these Terms of Use.  Governing Law and Jurisdiction All matters relating to the Service and these Terms of Use and any dispute or claim arising therefrom or related thereto (in each case, including non-contractual disputes or claims), shall be governed by and construed in accordance with the internal laws of the State of Utah without giving effect to any choice or conflict of law provision or rule (whether of the State of Utah or any other jurisdiction).  Any legal suit, action or proceeding arising out of, or related to, these Terms of Use or the Service shall be instituted exclusively in the federal courts of the United States or the courts of the State of Utah in each case located in Salt Lake City and Salt Lake County. User waives any and all objections to the exercise of jurisdiction over you by such courts and to venue in such courts.  Limitation on Time to File Claims ANY CAUSE OF ACTION OR CLAIM YOU MAY HAVE ARISING OUT OF OR RELATING TO THESE TERMS OF USE, THE SERVICE OR THE WEBSITE MUST BE COMMENCED WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES, OTHERWISE, SUCH CAUSE OF ACTION OR CLAIM IS PERMANENTLY BARRED.  Waiver and Severability No waiver by NetDocuments of any term or condition set forth in these Terms of Use shall be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of NetDocuments to assert a right or provision under these Terms of Use shall not constitute a waiver of such right or provision.  If any provision of these Terms of Use is held by a court or other tribunal of competent jurisdiction to be invalid, illegal or unenforceable for any reason, such provision shall be eliminated or limited to the minimum extent such that the remaining provisions of the Terms of Use will continue in full force and effect.  Entire Agreement These Terms of Use and our Privacy Policy constitute the sole and entire agreement between you and NetDocuments with respect to the Service and the Website and supersede all prior and contemporaneous understandings, agreements, representations and warranties, both written and oral, with respect to the Service and the Website. There exists a separate Service Agreement between NetDocuments and the Authorizing Customer under which the Authorizing Customer may have certain rights and obligations, but you are not a party to, or intended third party beneficiary of such Service Agreement.  Designated Agent under 17 U.S.C. §512(c) Receiving Complaints and Infringement Claims  Pursuant to 17 U.S.C. §512(c), notice is hereby given that the person identified below is designated as NetDocument’s agent for receiving complaints concerning this Website, including for purposes of receiving notification of any claims of intellectual property infringement:  Legal Affairs Department  2500 W Executive Parkway Suite 350, Lehi, UT 84043, USA (801) 226-6882  legal@netdocuments.com   NetDocuments  The Service is powered by NetDocuments Software Inc., a Delaware, USA corporation, located at 2500 W Executive Parkway Suite 350, Lehi, UT 84043, Phone 801.226.6882 (www.netdocuments.com). Answers to technical questions about the Service are found in Help which is accessed from within the Service. Any further questions should be submitted to the Authorizing Customer’s helpdesk.  All NetDocuments Services are: Copyright © 2020 NetDocuments Software Inc. and are covered by U.S. Patent No. 6,182,080. All rights reserved.   

(Automated response - build 671.)

**Comment by stephengillie** [comment]
Hi @EmmaTheEmu,

This package appears to require the user to accept a license agreement before use. Is this the case? 

Unfortunately, this kind of license usually requires explicit agreement, and including an installer switch to silently agree doesn't meet the requirement.

**Comment by EmmaTheEmu** [comment]
Hello @stephengillie 
That is correct, when installing the application standardly you accept the license in the installer. 
With the Winget package itself - during my testing the installer never prompted me for anything. With Windows Sandbox it installed without any additional pop ups, without sandbox it just prompted me for UAC.
Is there anything else I can/need to add in this case to make this package suitable?

**Comment by EmmaTheEmu** [comment]
@stephengillie 

Still awaiting for your response regarding my question

**Comment by stephengillie** [comment]
Hi @EmmaTheEmu,

Sorry for the delay. During your testing, you didn't encounter an installer window such as the one in [my previous comment above](https://github.com/microsoft/winget-pkgs/pull/136778#issuecomment-1915301462)? 

Unfortunately, we've [recently had to remove](https://github.com/microsoft/winget-pkgs/issues/131328) a number of manifests from our repo because their installer included a license accepting installer switch. Most licenses do not support this kind of implicit agreement, and as you said instead require the user to explicitly agree to the license terms. We're working to add an Agreements section, which would allow developers to coordinate this type of agreement with a package manager install. 

Here, a compounding issue is that the installer with the license terms also is not unattended. It appears that the Automatic Validation pipeline is mis-detecting the package as installed.

- Do you encounter the above installer window in your testing? 
- Is there an installer switch to bypass the above installer window and complete the install without interaction? it's definitely blocking manual validation.
- Do these installer switches include a switch to accept the terms, which might cause the situation described above?

**Comment by EmmaTheEmu** [comment]
This is how my installation looks like on Sandbox:

https://github.com/microsoft/winget-pkgs/assets/106916657/baac0434-7d4c-4a82-878f-9764c977bc1b

If required I can also add a video on how ndMail installs to that push request.

**Comment by stephengillie** [comment]
Was the license agreement accepted in a past installation? A previous installer might have saved that information, to streamline future installs. 

Pipeline validations are performed on fresh installs of Windows.

**Comment by EmmaTheEmu** [comment]
The video was filmed on the Sandbox feature. Apart from installing winget, copying manifest and enabling manifest installs - nothing else was done.

**Comment by EmmaTheEmu** [comment]
I was wondering, would it be possible to provide the specifications of the system that the pop up appeared? I only tested this in a 22H2 Windows 11 Sandbox, but there is a separate x86 installer that might be tripping it up.

**Comment by stephengillie** [comment]
Sure: 
- Windows 10 Enterprise Evaluation
- Version 21H2
- Installed 1/4/2024
- Build 19044.1288

WIndows specifications - Windows 10 Enterprise Evaluation, Version 21H2, Installed 1/4/2024, Build 19044.1288, Experience Windows Feature Experience Package 120.2212.3920.0

Here is a screenshot of a list of installed applications: https://github.com/microsoft/winget-pkgs/issues/107639#issuecomment-1734683940

**Pull request closed without merging**
