### PR TITLE
[Zip] New Package: SamuelTulach.VirusTotalUploader 0.1.9

### LINKED ISSUE #80937: [Package Request]: VirusTotalUploader (unofficial)
### Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: [SamuelTulach](https://github.com/SamuelTulach)
Publisher Url: https://github.com/SamuelTulach/VirusTotalUploader
Package Name: VirusTotalUploader (unofficial)
Description: C# Open-Source Winforms application for uploading files to VirusTotal
Package Version: 0.1.9
Installer URL: https://github.com/SamuelTulach/VirusTotalUploader/releases

I know there's an official VirusTotal.VirusTotalUploader package, however it has a limitation on 32mb for uploading files.  This is because the official app was [discontinued](https://support.virustotal.com/hc/en-us/articles/115002179065-Desktop-apps) in favor of the unofficial one.

### PR DESCRIPTION
**Pull request by Trenly**
* Resolves #80937

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/88070)

### CODE REVIEW

**Comment by Trenly** [comment]
@msftbot zip

**Comment by Trenly** [comment]
@msftbot zip

**Comment by Trenly** [comment]
@msftbot zip

**Review by ItzLevvie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
