### PR TITLE
New version: Nushell.Nushell version 0.85.0

### PR DESCRIPTION
**Pull request by fdncred**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/120211)

### CODE REVIEW

**Comment by fdncred** [comment]
The msi works when you run it manually, of course. It's always something with winget.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335187 2023-09-19 13:43:07.792 [FAIL] Installer failed security check. Url: https://github.com/nushell/nushell/releases/download/0.85.0/nu-0.85.0-x86_64-pc-windows-msvc.msi Result: 0x80004005

**Comment by stephengillie** [comment]
Hi @fdncred,

The package did not pass a security check. This might be a false positive and we can retry tomorrow.

**Comment by fdncred** [comment]
I tried to look at the logs and they just say "failed". No clue what "security check" means either.

**Comment by sitiom** [comment]
Installation failed on my machine:
image

**Comment by fdncred** [comment]
> Installation failed on my machine:

The first thing I did was install the version from the release and didn't have any issues with it installing on Windows 11. I wonder why yours is failing @sitiom?

**Comment by sitiom** [comment]
Have you tried installing it on a sandbox?

**Comment by sitiom** [comment]
Run [`SandboxTest.ps1`](https://github.com/microsoft/winget-pkgs/blob/master/Tools/SandboxTest.ps1) and pass the manifest folder.

**Comment by fdncred** [comment]
No issues installing and running in Sandbox
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
