### PR TITLE
New package: Canon.i-SENSYS.MF3010 version 3.901

### PR DESCRIPTION
**Pull request by Alexejhero**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/171042)

### CODE REVIEW

**Comment by Alexejhero** [comment]
@microsoft-github-policy-service agree

**Comment by Alexejhero** [comment]
After trying to create the manifest for this package, there seem to be multiple problems with this installer:
1. There doesn't seem to be any switch for running the installer silently
2. After the installer finishes, another installer is opened for the experience program or something (this is a separate exe that is run by the main process)
3. The installer always exits with exit code 1
4. For whatever reason the antivirus scan detects malware in the archive

With all of these in mind, is it safe to assume that this cannot be turned into a winget package?

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 895.)

**Comment by stephengillie** [comment]
Hi @Alexejhero,

This PR seems ready to merge. Feel free to click the "Ready for review" button and the merge should happen automatically.

**Comment by Alexejhero** [comment]
Hello @stephengillie

I have noted down several issues that I found with this package in a [previous comment](https://github.com/microsoft/winget-pkgs/pull/171042#issuecomment-2323256299). Please let me know your thoughts.

**Comment by stephengillie** [comment]
I hadn't installed the application locally to inspect. Thanks for bringing these concerns to my attention.

**Pull request closed without merging**
