### PR TITLE
New version: cmlanche.lightningvine version 2.8.0+280

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings).
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/203187)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Manual Validation ended with:
> finished with exit code: -2147012867 

Automated error analysis suggests -2147012867 may mean Network or Firewall Error.

(Automated response - build 931.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
>  11:21:00 AM: 
> 2024-12-30 11:19:31.733 [CLI ] Failed to download, waiting a bit and retry. Url: https://sdtpub.s3.bitiful.net/publish/2.8.0/sdt-2.8.0-windows-installer.exe            11:21:00 AM: 
> 2024-12-30 11:20:59.138 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(150)\WindowsPackageManager.dll!00007FFBC37F039C: (caller: 00007FFBC37ECECB) Exception(4) tid(2464) 80072EFD     Msg:[InternetOpenUrl() failed.]

(Automated response - build 931.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 11:31:04 AM: 
> 2024-12-30 11:29:35.462 [CLI ] Failed to download, waiting a bit and retry. Url: https://sdtpub.s3.bitiful.net/publish/2.8.0/sdt-2.8.0-windows-installer.exe            11:31:04 AM: 
> 2024-12-30 11:31:02.930 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(150)\WindowsPackageManager.dll!00007FFBC453039C: (caller: 00007FFBC452CECB) Exception(4) tid(2b58) 80072EFD     Msg:[InternetOpenUrl() failed.]

(Automated response - build 931.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 11:47:19 AM: 
> 2024-12-30 11:45:50.940 [CLI ] Failed to download, waiting a bit and retry. Url: https://sdtpub.s3.bitiful.net/publish/2.8.0/sdt-2.8.0-windows-installer.exe                                                                       11:47:19 AM: 
> 2024-12-30 11:46:51.470 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(324)\WindowsPackageManager.dll!00007FFBF71C4C07: (caller: 00007FFBF71C38BC) Exception(3) tid(18a0) 80D02002                     11:47:19 AM: 
> 2024-12-30 11:47:18.674 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(150)\WindowsPackageManager.dll!00007FFBF71C039C: (caller: 00007FFBF71BCECB) Exception(4) tid(18a0) 80072EFD     Msg:[InternetOpenUrl() failed.]                                                                                                           11:47:19 AM: 
> 2024-12-30 11:47:18.798 [CLI ] Caught wil::ResultException: C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(150)\WindowsPackageManager.dll!00007FFBF71C039C: (caller: 00007FFBF71BCECB) Exception(4) tid(18a0) 80072EFD     Msg:[InternetOpenUrl() failed.]      

(Automated response - build 931.)

**Pull request merged**
