### PR TITLE
New package: CloudFoundry.CLI.v8 version 8.6.1

### LINKED ISSUE #106116: [Package Request]: cf8-cli
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/cloudfoundry/cli/wiki/V8-CLI-Installation-Guide#installers-and-compressed-binaries
Publisher: https://www.cloudfoundry.org/
Package Name: cf8-cli
Description: The cf CLI is the official command line client for Cloud Foundry.
Package Version: 8.6.1 (currently)
Installer URL: 
    - 64-bit https://packages.cloudfoundry.org/stable?release=windows64&version=v8
    - 32-bit https://packages.cloudfoundry.org/stable?release=windows32&version=v8

There is also a related installer for version 7 of this application.  Ideally being able to run [winget install cf-cli] would match with both versions and prompt the user to pick from the two prominent versions.

### PR DESCRIPTION
**Pull request by mdanish-kh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----
- Resolves #106116
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/107769)

### CODE REVIEW

**Comment by mdanish-kh** [comment]
Direct CDN Urls are taken from https://github.com/cloudfoundry/cli/releases/tag/v8.6.1

**Comment by stephengillie** [comment]
This package is expecting arguments:
```
cf8.exe version 8.6.1+b5a352a68.2023-02-27, Cloud Foundry command line tool
Usage: cf8.exe [global options] command [arguments...] [command options]

Before getting started:
  config    login,l      target,t
  help,h    logout,lo

Application lifecycle:
  apps,a        run-task,rt    events
  push,p        logs           set-env,se
  start,st      ssh            create-app-manifest
...
```

**Review by stephengillie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Comment by BrandonWanHuanSheng** [comment]
Most likely, it look like this thing might not handle properly.

**Pull request merged**
