### PR TITLE
Add GoLand EAP build 212.4638.10

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/20262)

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@azure-pipelines Why is it taking forever to run?

**Comment by vedantmgoyal2009** [comment]
@ItzLevvie Please fix this PR. It successfully ran on a local computer but local on Azure Pipelines.

**Comment by vedantmgoyal2009** [comment]
@ItzLevvie Please tell me what is wrong with this PR?

**Comment by ItzLevvie** [comment]
I have no idea, sorry. You'll have to wait for an engineer to take a look.

**Comment by vedantmgoyal2009** [comment]
Okay 😔

**Comment by vedantmgoyal2009** [comment]
@OfficialEsco Please approve this. It took 6 days to get the PASSED label.

**Review by OfficialEsco — APPROVED** [review]

**Comment by denelon** [comment]
@vedantmgoyal2009 I'm not sure about this one, but in some cases one of the back end systems has a 24 hour SLA to get us a response. It seems to happen when it's a new installer or a new domain for all of the security analysis. Once everything has been evaluated by the various detection systems we will finally get a result. Sometimes a PASS takes much longer to get to than a FAIL. We've also been seeing some intermittent issues with the infrastructure across all of the various services and technology stacks. That's why you will often see the bot come in for a retry. We've been gradually adding more retry logic if we can't truly root cause and correct the fundamental problem. Often we will go back to see if we can find the true root cause and implement a permanent solution.

**Pull request merged**
