### PR TITLE
New package: TCHelicon.GoXLRApp version 1.3.3.130

### LINKED ISSUE #137778: [Package Request]: TCHelicon.GoXLRApp
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.tc-helicon.com/product.html?modelCode=P0DI7
Publisher: TC Helicon
Package Name: TCHelicon.GoXLRApp
Description: App for managing the GoXLR
Package Version: 1.3.3.130
Installer URL: https://mediadl.musictribe.com/download/software/tchelicon/GoXLR/GoXLR-App-1.3.3.130.zip

### PR DESCRIPTION
**Pull request by Exorcism0666**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.0.3 :rocket:

- Resolve: #137778
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137805)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification.
>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 695.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 719.)

**Comment by stephengillie** [comment]
> Automatic Validation ended with: image
> 
> Hi @Exorcism0666,
> 
> Is an installer switch missing?

**Comment by stephengillie** [comment]
The `/SILENT` and `/VERYSILENT` switches should be working. 
image

**Comment by stephengillie** [comment]
This is actually 2 installers - the app installer runs a driver installer:

Image of an installer window on the upper left, partially covered with a driver installer window.


Both look the same and have similar names, which makes them seem like the same installer. The silent installer switches are working as expected. But they fail to work on the driver installer, which is common. 

It's unlikely that silent install switches exist for the driver. If they do, the PR could proceed.

**Comment by Exorcism0666** [comment]
@stephengillie What change do you propose?

**Comment by stephengillie** [comment]
@Exorcism0666,

Unfortunately, packages like this - involving a driver install - usually get blocked at this step. The problem is that the main installer launches a nested driver installer. Installers nested in this way are hard to reach to provide installer switches, without disassembling the installer file. And driver installs usually require explicit user permission in addition to elevated permissions. 

Potential paths forward:

- Locate installer switches that would inform the main installer to silently install the driver. 
- Find the driver package separately, find silent installer switches, add driver package manifest to repo, include driver package as dependency in main package.
- Find another method to install this driver before the package, if one exists. 
- Create your own driver installer to install this driver, with silent installer switches. Follow remaining steps from previous bullet point.

**Comment by stephengillie** [comment]
> * Find the driver package separately, find silent installer switches, add driver package manifest to repo, include driver package as dependency in main package.

This might be the goal with this PR: 
- https://github.com/microsoft/winget-pkgs/pull/137804

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Pull request closed without merging**
