### PR TITLE
Remove version: EADesktop v13.86.0.5599

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135789)

### CODE REVIEW

**Comment by drshtmstry** [comment]
> Sequence contains no elements

- #133371

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 638.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-23T03:24:06.0711640Z Processing manifest: manifests\e\ElectronicArts\EADesktop\13.86.0.5599
 2024-01-23T03:24:06.0726869Z -----------------------------------------------------
 2024-01-23T03:24:06.0734798Z Status: Started
 2024-01-23T03:24:06.0742711Z Manifest file is Deleted
 2024-01-23T03:24:06.3373607Z Status: Completed
 2024-01-23T03:24:06.3409650Z ##[error] Result: Failed
 2024-01-23T03:24:06.3412633Z ##[error] Sequence contains no elements
 2024-01-23T03:24:06.3996279Z ##[error]Manifest Validation Failed

(Automated response - build 638.)

**Comment by stephengillie** [comment]
URL: https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EAappInstaller.exe 
Status Code: 200

(Automated message - build 647)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
