### PR TITLE
New package: rwxrob.pomo version 0.2.3

### PR DESCRIPTION
**Pull request by jamiebarrow**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/167762)

### CODE REVIEW

**Comment by jamiebarrow** [comment]
@microsoft-github-policy-service agree

**Comment by jamiebarrow** [comment]
@stephengillie I noticed this keeps failing. I saw as well it seems to be a general error on [the WinGetSvc-Validation pipeline](https://dev.azure.com/ms/winget-pkgs/_build?definitionId=337&_a=summary&statusFilter=failed) with multiple PR's. I did run the `winget validate --manifest <path>` step locally and it passed validation, so I'm not sure why the Installers Scan step is failing - [see here](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=604588&view=logs&j=68997d86-8ece-5ae8-3ac5-ccdbfa458731&t=a6d88639-1ba6-5d70-db6d-8e283a18f2b4&l=41).

I presume that it's then a problem with the tooling / function that it calls? Let me know though if it's anything related to the PR :)

**Comment by stephengillie** [comment]
Hi @jaimebarrow,

This label is very much like [Internal-Error-Dynamic-Scan](https://github.com/microsoft/winget-pkgs/discussions/155218) in that it reflects solely an error with the pipelines, and not any information about the package. The difference is that this Internal Error occurred during the Static Scan phase of Validation, where packages go through static scans such as detecting "installer bombs".

**Comment by jamiebarrow** [comment]
Thanks for linking to that discussion @stephengillie, much appreciated for the explanation in that thread. I'm guessing then that it requires you to manually install and scan it? The exe is only 11.9 MB, so I don't know if the Storage Drive out of space problem is relevant.

Looking forward to hearing back from you :) Thanks again!

**Comment by stephengillie** [comment]
> Thanks for linking to that discussion @stephengillie, much appreciated for the explanation in that thread. I'm guessing then that it requires you to manually install and scan it? The exe is only 11.9 MB, so I don't know if the Storage Drive out of space problem is relevant.
> 
> Looking forward to hearing back from you :) Thanks again!

This isn't quite far enough along for me to manually complete. But the issue has been found and fixed, so the next run should have a better outcome.

**Comment by stephengillie** [comment]
Hi @jamiebarrow,

This application installs normally, but doesn't seem to do anything when launched. From either the symlink or the full file. Is a special syntax needed?

**Comment by jamiebarrow** [comment]
> Hi @jamiebarrow,
> 
> 
> 
> This application installs normally, but doesn't seem to do anything when launched. From either the symlink or the full file. Is a special syntax needed?

Yes, try 'pomo --help' for more information. It's a Pomodoro timer utility catered for the command line. When you run it without arguments it displays the current status (empty by default since no timer is running). After running 'pomo start', running it again with no arguments displays output.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Comment by stephengillie** [comment]
Verify:
image
image
That's extremely specific behavior. When run with no arguments, it should give some kind of output.

**Comment by jamiebarrow** [comment]
> That's extremely specific behavior. When run with no arguments, it should give some kind of output.

Yes, indeed. Actually when I first used the tool I was also wondering if it was working properly haha. But I understand why: it is originally used in a Linux environment with the `tmux` tool to provide a status in a 'toolbar' visible on the screen. So just running the command displays the status. I suppose it's also easier to type out in general when working on the command line with any custom functions or aliases in the shell.

Perhaps I'll create a ticket in the authors repository to suggest having this behaviour behind a flag/command instead. And by default, having it run its help command.

I've wanted to learn Go for a while, I might even create a PR someday :)

Anyways, thanks for your assistance @stephengillie

**Pull request merged**
