### PR TITLE
Renormalize: Segger.EmbeddedStudioARM version 5.42

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/74813)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
Why is this deleted?

**Comment by vedantmgoyal2009** [comment]
> Hello @vedantmgoyal2009, When processing this package, the URL to the installer returned a 404 error or was determined to be invalid.
> 
> Please update the URL and hash at your convenience and resubmit your PR.
> 
> Template: msftbot/validationError/urls/404

@officialesco

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
Probably because you sent too many requests.
Both urls work on my end

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
