### PR TITLE
New version: Microsoft.EdgeDriver version 126.0.2592.87

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#6311](https://github.com/SpecterShell/Dumplings/actions/runs/9771217304).

<details>

<summary>Log</summary>

````
Updated: 126.0.2592.81 → 126.0.2592.87
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161259)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
@stephengillie

* #142854

**Pull request merged**
