### PR TITLE
Remove version: WHONET.2023 version 23.13.17

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135586)

### CODE REVIEW

**Comment by drshtmstry** [comment]
> Sequence contains no elements

- #133371

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 642.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-20T04:01:37.6853367Z Processing manifest: manifests\w\WHONET\2023\23.13.17
 2024-01-20T04:01:37.6864101Z -----------------------------------------------------
 2024-01-20T04:01:37.6869115Z Status: Started
 2024-01-20T04:01:37.6877514Z Manifest file is Deleted
 2024-01-20T04:01:37.9198054Z Status: Completed
 2024-01-20T04:01:37.9206184Z ##[error] Result: Failed
 2024-01-20T04:01:37.9215341Z ##[error] Sequence contains no elements
 2024-01-20T04:01:37.9823363Z ##[error]Manifest Validation Failed

(Automated response - build 642.)

**Comment by stephengillie** [comment]
URL: https://whonet.org/WHONET2023-Setup-x86.exe 
Status Code: 200

(Automated message - build 642)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
