### PR TITLE
Dup - ElectronicArts.OriginThinSetup version 10,5,103,48818

### PR DESCRIPTION
**Pull request by Masamune3210**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/27044#event-5258278180

**Comment by Masamune3210** [comment]
Currently making a VM so I can test these more on a clean sample and see what I messed up easier

**Comment by Masamune3210** [comment]
Is there any way to add redists or other dependencies to the manifest? This is failing due to a clean system not having the C++ Redist it needs

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Applications that need dependencies aren't yet supported by Windows Package Manager.

**Pull request closed without merging**
