### PR TITLE
New version: IrfanSkiljan.IrfanView version 4.70

### LINKED ISSUE #181559: [Update Request]: Update IrfanSkiljan.IrfanView to 4.70
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

IrfanSkiljan.IrfanView

### Package Version

4.70

### Please describe the changes you would like to see

New version 4.70:

> **(Release date: 2024-10-11)**
> 
> New option: Keep existing alpha/transparency color (Properties->Viewing)
> Show checkerboard image; Alpha/Color also used for saving
> New option in Increase Color Depth dialog: 32 BPP (with alpha layer)
> New option in Replace Color dialog: Set transparent color (if 32 BPP image)
> New Image menu: Edit or Set alpha/transparency color>
> New option: Show Browse buttons in main window (Properties->Browsing)
> Fine Rotation option can work on selections
> New in OCR PlugIn: read QR or Barcode (thanks to ZXing guys)
> New slideshow hotkey: SHIFT + "," (comma): Toggle random and automatic time
> New Print dialog option: Reverse pages (for multipage images, page ranges)
> Support for EXIF data in WEBP files (EXIF dialog)
> Command line: "/effect" can be combined with "/slideshow", like:
> i_view64.exe /slideshow=c:\mypics.txt /effect=(30,0,0)
> Loading issues in several PlugIns fixed (thanks to Trend Micro)
> (CADImage, Formats, CamRAW, DjVu, JPM, ECW, WSQ)
> SVG PlugIn loading bugs fixed (thanks to nerty_nerty)
> EXR PlugIn loading bugs fixed (thanks to leeho and Who4mI)
> Several PlugIns are changed/updated

**Download:**
https://www.irfanview.com/main_download_engl.htm ( I have no idea which hoster is best for winget)

### PR DESCRIPTION
**Pull request by Dragon1573**
> [!NOTE]
>
> Since **TECHSPOT** does not provide self-extracting EXE installer for `v4.70`, currently switch to **Major Geeks** with compressed ZIP archive.
>
> - See https://github.com/microsoft/winget-pkgs/issues/181559#issuecomment-2408601573

## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #181559

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/183094)

### CODE REVIEW

**Comment by Dragon1573** [comment]
Manually validated in _Windows Sandbox_ instance.

Image
Image

**Review by ItzLevvie — APPROVED** [review]

**Comment by MagicAndre1981** [comment]
@Dragon1573 I can't update irfanview as install method is different. Log shows this:

```
2024-10-17 23:35:37.833 [CLI ] Installer [X86,portable,Unknown,] not applicable: Installed package type 'exe' is not compatible with installer type portable
2024-10-17 23:35:37.833 [CLI ] Installer [X64,portable,Unknown,] not applicable: Installed package type 'exe' is not compatible with installer type portable
```

4.67 shows setup exe and you have used zip.

**Comment by Dragon1573** [comment]
> I can't update irfanview as install method is different. Log shows this:
> 
> ```text
> 2024-10-17 23:35:37.833 [CLI ] Installer [X86,portable,Unknown,] not applicable: Installed package type 'exe' is not compatible with installer type portable
> 2024-10-17 23:35:37.833 [CLI ] Installer [X64,portable,Unknown,] not applicable: Installed package type 'exe' is not compatible with installer type portable
> ```

Currently, **TECHSPOT** does not provide self-extracted EXE installer for version `v4.70`. Could you please validate all mirrors manually and find a stable EXE installer URL?

- See https://github.com/microsoft/winget-pkgs/issues/181559#issuecomment-2408601573

**Comment by MagicAndre1981** [comment]
I only found the polish programosy site that provides direct links, but they also provide other software that defender blocks, so this host is not recommand. 

Maybe someone from Microsoft should contact the author of Irfanview asking for directlink on his site when using usersagent of winget similar to GPU-Z

**Comment by MagicAndre1981** [comment]
ok, there are now techspot links available:

https://files01.tchspt.com/down/iview470_setup.exe
https://files02.tchspt.com/down/iview470_x64_setup.exe

**Pull request merged**
