### PR TITLE
Luca-AlexanderThomas.AutoHome-Autostart version 1.0.0

### PR DESCRIPTION
**Pull request by luca-alexander-thomas**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23587)

### CODE REVIEW

**Review by vedantmgoyal9 — COMMENTED** [review]
Looks like the installer does not support silent installation yet. I downloaded the file and ran it with flags mentioned in the manifests. 
image

**Comment by luca-alexander-thomas** [comment]
Hello I dont´t now how i must create an installer for an Packege manager... where i can read how to do that, or can you explain me how in must do it...

**Comment by vedantmgoyal2009** [comment]
Actually, I have not created an installer for any application till now, but I would suggest using Inno or Nullsoft for creating installers that are currently supported by WinGet. Support for portable installers and Dependencies will be coming soon.

**Comment by denelon** [comment]
@luca-alexander-thomas take a look at [MSIX](https://docs.microsoft.com/en-us/windows/msix/overview). There are also other open source or "free" tools to help building MSIX packages.

**Pull request closed without merging**
