### PR TITLE
Vipre.IPVTest version 1.0.0.0

### PR DESCRIPTION
**Pull request by vimalraj-adikesavan**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/88449)

### CODE REVIEW

**Comment by vimalraj-adikesavan** [comment]
> @microsoft-github-policy-service agree

**Comment by russellbanks** [comment]
@vimalraj-adikesavan, is this just a test or do you want IPVTest submitted publically?

**Comment by vimalraj-adikesavan** [comment]
> 

Hello Russell, I am learning about windows package manger. IPVTest is a WPF based test application. Please submit IPVTest publically. So that I can test using WinGet tools.

**Review by russellbanks — CHANGES_REQUESTED** [review]

**Comment by russellbanks** [comment]
If you want to test a package locally, you can do `winget install --manifest <path>`.

For submitting publically, please see https://github.com/microsoft/winget-pkgs/pull/88449#discussion_r1022998635 for a license correction.

**Review by russellbanks — APPROVED** [review]

**Pull request merged**
