### PR TITLE
Microsoft.VisualStudio.2022.Professional version 17.6.0

### PR DESCRIPTION
**Pull request by edwardskrod**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/106935)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @edwardskrod,

This package installed normally but errored when launched:
> Activation context generation failed for "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.exe". Dependent Assembly Automation,processorArchitecture="&#x2a;",type="win32",version="1.0.0.0" could not be found. Please use sxstrace.exe for detailed diagnosis.

**Review by jedieaston — APPROVED** [review]

**Comment by jedieaston** [comment]
(I couldn't make this fail locally..?)

**Comment by stephengillie** [comment]
> (I couldn't make this fail locally..?)

In my Windows 11 VMs, it doesn't add any shortcuts, so I'm not sure which application should be launched. I've been going with `devenv.exe` because it seems to be the only EXE with the application's icon. But this EXE seems to error every time. 

How are you validating this package? Does it add shortcuts for you, or are you finding a different EXE to run?

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
