### PR TITLE
Added ALLUSERS=1 switch for Nushell machine-wide installation manifest

### PR DESCRIPTION
**Pull request by misaka4a92**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---
closes https://github.com/microsoft/winget-pkgs/issues/157954
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/157957)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Comment by justinbarclay** [comment]
@stephengillie this commit seems to have [broken](https://github.com/nushell/nushell/issues/13281) the install process for nuget users. 

Before, we could just install nushell with `winget install nushell`, but now we need to do it from an elevated prompt.

**Comment by stephengillie** [comment]
Hi @justinbarclay,

Before, would nushell install to `Program Files` or to `AppData`? I'm guessing that without any switches, the installer determines install location based on elevation and permissions - installilng into the `user` scope usually, and only installing into the `machine` scope if elevated. Is this accurate? 

The `ALLUSERS=1` switch should force the installer to install in `Program Files` or another machine-scoped location. This would match the `Scope: machine` entry on the subsequent line. 

One fix would be to remove both the switch and the `Scope`, which would let elevation again determine the install location. Another would be moving these to the installer level, and duplicating the current installers with `user` scope and switches - which would allow these to be selected at insatll time, and I believe default to `user` scope for install. 

Which fix would be preferred?

**Comment by dander** [comment]
The current installer seems to support both per-user and per-machine, so the first solution seems preferable.

**Comment by fdncred** [comment]
As one of the maintainers of nushell, seems to me like the second option is better. Thanks for the input. To follow along further, please see https://github.com/nushell/nushell/issues/13281

**Pull request merged**
