### PR TITLE
New version: JetBrains.dotTrace version 2023.3.4

### PR DESCRIPTION
**Pull request by OfficialEsco**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/145527)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @OfficialEsco,

> This PR's version number 2023.3.4 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 233.0.20231204.184458, which has 4 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 870)

**Comment by OfficialEsco** [comment]
```
Enter a pull request number: 145527

Manifest validation succeeded.
Found JetBrains dotTrace [JetBrains.dotTrace] Version 2023.3.4
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download-cdn.jetbrains.com/resharper/dotUltimate.2023.3.4/JetBrains.dotTrace.2023.3.4.web.exe
  ██████████████████████████████  41.5 MB / 41.5 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Name          : JetBrains dotTrace 2023.3.4
Publisher     : JetBrains s.r.o.
Version       : 2023.3.4
ProductCode   : {0ebdb488-4d18-5190-8947-9fbd96b6367d}
Registry Path : Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\{0ebdb488-4d18-5190-8947-9fbd96b6367d}
Uninstall     : winget uninstall --id "{0ebdb488-4d18-5190-8947-9fbd96b6367d}"

Press any key to continue . . .
```
They have not changed their version schema. This is a issue with wingetcreate using the version from details instead of the real version. This should have been validated on new package submission.

**Comment by stephengillie** [comment]
Verify: 
image

**Comment by stephengillie** [comment]
Verify:

image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
