### PR TITLE
New version: DuckStudio.ChineseGit version 2.2

### PR DESCRIPTION
**Pull request by DuckDuckStudio**
image

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/199987)

### CODE REVIEW

**Comment by DuckDuckStudio** [comment]
> /AzurePipelines run

This validation seemed to run for ~9 hours long, so I reopened the pull request to retry.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Pull request merged**
