### PR TITLE
GlobalMarineNet.XGatePatch version 1.16

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/107511)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

Is there a switch to bypass this?

**Comment by upintheairsheep** [comment]
> Automatic Validation ended with: image
> 
> Is there a switch to bypass this?

Try common ones, and if they don't work add interactive only installer.

**Comment by Trenly** [comment]
> Try common ones, and if they don't work add interactive only installer.

There are many switches that it could be. I know of at least 12 different combinations for various installers that could be used. To go through and try common switches takes a lot of time away from the validation of other PRs. Can you test yourself to try and find the silent switch?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by upintheairsheep** [comment]
> > Try common ones, and if they don't work add interactive only installer.
> 
> There are many switches that it could be. I know of at least 12 different combinations for various installers that could be used. To go through and try common switches takes a lot of time away from the validation of other PRs. Can you test yourself to try and find the silent switch?

Can you put up a guide to identification guide of installers and their switches on the docs? I'm now identifying installers and adding the flags myself.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
I'm stuck here:
image

> Can you put up a guide to identification guide of installers and their switches on the docs?

Some are covered — except for a few like InstallShield, SetupFactory, InstallBuilder, AdvancedInstaller & Squirrel — in https://github.com/microsoft/winget-cli/blob/83cd0dcaddd31cc64570422b081f7743a79dc10d/src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp#L763-L795

For other installer types — you can use https://github.com/appget/appget/tree/master/src/AppGet/Installers/InstallerWhisperer as a reference.

For this application — you will have to contact the application developers to see if there are any silent switches for this application.

**Comment by ItzLevvie** [comment]
[Policy] Interactive-Only-Installer

**Pull request closed without merging**
