### PR TITLE
New package: Toxblh.WinToLinux version 1.1.0

### LINKED ISSUE #171308: [Package Request]: WinToLinux
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/Toxblh/WinToLinux/releases
Publisher: Toxblh
Package Name: WinToLinux
Description: Reboot Windows to Linux in two clicks! Editing UEFI order for next start of the system
Package Version: v.1.1.0
Installer URL: https://github.com/Toxblh/WinToLinux/releases/download/v1.1.0/WinToLinux.zip

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #171308

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/171447)

### CODE REVIEW

**Comment by stephengillie** [comment]
Verify:
image
Neither `exe` had any output - is this expected in a VM, and/or if a distro isn't installed on a visible volume?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\WinToLinux.exe returned exit code: -532462766

Automated error analysis suggests -532462766 may mean EXCEPTION_COMPLUS (Unhandled Exception)

(Automated response - build 894.)

**Comment by Dragon1573** [comment]
> Neither `exe` had any output - is this expected in a VM, and/or if a distro isn't installed on a visible volume?

So do I in _Windows Sandbox_. It can be launched without explicitly configuring other dependencies on my _Windows 11_ device. There might be some mechanism so the package can interact with boot settings. _Sandbox_ or other VM instance provides none of them.

**Comment by Dragon1573** [comment]
In _Windows Sandbox_ instance, there's no "Boot options" available. I can't sure if it's the reason why `WinToLinux.exe` failed to launch.

image

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Close with reason: Unable to launch in VM instances. Failed to pass Validation Pipeline.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334972
> 2024-09-04 01:32:48.799 [CLI ] No suitable installer found for manifest Microsoft.DotNet.Framework.DeveloperPack_4 with version 4.8.1

Automated error analysis suggests -1978334972 may mean This package has a dependency missing from your system.

(Automated response - build 895.)

**Pull request closed without merging**
