### PR TITLE
New version: Rye.Rye version 0.21.0

### PR DESCRIPTION
**Pull request by zengqiu**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137802)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  2024-02-04 05:27:32.403 [FAIL] WindowsPackageManager.dll!00007FF877ECBDD2: ReturnHr(1) tid(274) 80190193 Forbidden (403).     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\HttpStream\HttpClientWrapper.cpp(50)\WindowsPackageManager.dll!00007FF877EB203A: (caller: 00007FF877D97669) Exception(1) tid(274) 80190193 Forbidden (403). 2024-02-04 05:27:32.403 [FAIL] WindowsPackageManager.dll!00007FF877D53AF1: LogHr(1) tid(274) 80190193 Forbidden (403). 2024-02-04 05:27:32.404 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(53)\WindowsPackageManager.dll!00007FF877ED7301: (caller: 00007FF877DA04FE) LogHr(2) tid(274) 80190193 Forbidden (403).     Msg:[winrt::hresult_error: Forbidden (403).]  2024-02-04 05:27:32.404 [REPO] Source add/update failed, waiting a bit and retrying: winget 2024-02-04 05:27:34.426 [FAIL] WindowsPackageManager.dll!00007FF877ECBDD2: ReturnHr(2) tid(274) 80190193 Forbidden (403).     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\HttpStream\HttpClientWrapper.cpp(50)\WindowsPackageManager.dll!00007FF877EB203A: (caller: 00007FF877D97669) Exception(2) tid(274) 80190193 Forbidden (403). 2024-02-04 05:27:34.426 [FAIL] WindowsPackageManager.dll!00007FF877D53AF1: LogHr(3) tid(274) 80190193 Forbidden (403). 2024-02-04 05:27:34.426 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(540)\WindowsPackageManager.dll!00007FF877ED68E3: (caller: 00007FF877C98B8D) LogHr(4) tid(274) 80190193 Forbidden (403). 2024-02-04 05:27:34.426 [REPO] Failed to update source: winget 2024-02-04 05:27:34.606 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(564)\WindowsPackageManager.dll!00007FF877ED6B53: (caller: 00007FF877C98B8D) LogHr(5) tid(274) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF877DE9298: (caller: 00007FF877EA24F9) Exception(3) tid(274) 8A15005E ]  2024-02-04 05:27:34.606 [REPO] Failed to open available source: msstore 2024-02-04 05:27:34.619 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(205)\WindowsPackageManager.dll!00007FF877DB453A: (caller: 00007FF877DA0B9E) Exception(4) tid(274) 8A15000F  2024-02-04 05:27:34.619 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(564)\WindowsPackageManager.dll!00007FF877ED6B53: (caller: 00007FF877C98B8D) LogHr(6) tid(274) 8A15000F     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(205)\WindowsPackageManager.dll!00007FF877DB453A: (caller: 00007FF877DA0B9E) Exception(4) tid(274) 8A15000F ]  2024-02-04 05:27:34.619 [REPO] Failed to open available source: winget 2024-02-04 05:27:34.619 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(571)\WindowsPackageManager.dll!00007FF877DA10DB: (caller: 00007FF877C98B8D) Exception(5) tid(274) 8A15004B 

(Automated response - build 695.)

**Comment by zengqiu** [comment]
I don't know why it fails every time, but there is no problem when I test it locally.



https://github.com/microsoft/winget-pkgs/pull/122107 https://github.com/microsoft/winget-pkgs/pull/121190

**Comment by stephengillie** [comment]
> I don't know why it fails every time, but there is no problem when I test it locally.
> 
> 
> 
> #122107 #121190

Hi @zengqiu,

Sorry that you keep experiencing this frustration. If it helps, it's failing for the same reason as before. I've added this package to a list in my automation that might help in the future. I'll ask internally, to see if there's anything else we can do to fix this.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
