### PR TITLE
Remove version: CiderCollective.Cider version 1.6.2

### PR DESCRIPTION
**Pull request by DuckDuckStudio**
### It return 404 in [GitHub Action](https://github.com/DuckDuckStudio/winget-tools/actions/runs/12452429058/job/34761372752#step:6:142), and the project has been archived.

image

- Replace #198939

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/201288)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://github.com/ciderapp/Cider/releases/download/v1.6.2/Cider-Setup-1.6.2.exe 
Response Error: The remote server returned an error: (404) Not Found.

(Automated message - build 924)

**Comment by stephengillie** [comment]
Hi @DuckDuckStudio,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 931.)

**Comment by ItzLevvie** [comment]
[Policy] Reset Labels
[Policy] Reset Feedback

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
