### PR TITLE
Normalize Prusa3D.PrusaSlicer 2.3.3

### PR DESCRIPTION
**Pull request by Trenly**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/76165)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Comment by Trenly** [comment]
image

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
