### PR TITLE
Add OutSystems.ServiceStudio11 manifest

### PR DESCRIPTION
**Pull request by sergiomiranda-outsystems**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/118881)

### CODE REVIEW

**Comment by sergiomiranda-outsystems** [comment]
@microsoft-github-policy-service agree

**Comment by sergiomiranda-outsystems** [comment]
> 

Hello,

The domain of the URL used in the manifest is of a blob storage hosted at Azure and managed by the Publisher.
This domain is also used as the source of installer files by an open source PowerShell module managed by the Publisher that also allows for the installation of the software in this manifest.

https://github.com/OutSystems/OutSystems.SetupTools/blob/869f33f18e667b3da607d182b26996fe5dfa43be/src/Outsystems.SetupTools/Lib/Constants.ps1#L88C1-L88C66

**Comment by stephengillie** [comment]
Hi, @sergiomiranda-outsystems,

Unfortunately, I can't navigate from the PackageUrl to the InstallerUrl. The website doesn't appear to present this package for download without registering. Without finding the InstallerUrl on the ISV website, I can't verify that this is an official source.

**Comment by sergiomiranda-outsystems** [comment]
> Hi, @sergiomiranda-outsystems,
> 
> Unfortunately, I can't navigate from the PackageUrl to the InstallerUrl. The website doesn't appear to present this package for download without registering. Without finding the InstallerUrl on the ISV website, I can't verify that this is an official source.

Hello @stephengillie 

The account is free to create but even if you have one, the download that you could get from PublisherUrl is only valid temporarily and would come from another domain and not from InstallerUrl.

The InstallerUrl is an alternate location to obtain the installer that doesn't have that time limitation and is used in the code of a PowerShell module from the Publisher that exists for use in scripts and automation (one of it's purposes is to install the package) and that code is hosted in a public repository of the Publisher organisation at GitHub.

So there will not be a direct path from the PublisherURL to the InstallerUrl, but InstallerUrl is used as a source for the installer in that repository of the Publisher. If this is not enough to validate this source, unfortunately I don't have other options for now.

**Comment by stephengillie** [comment]
Sorry for the delayed reply. This InstallerUrl doesn't appear anywhere on the ISV's website, so I can't independently verify that it's an approved download source. All packages have to be hosted by the ISV's official hosting. The suggested host is a public storage service, so has to be verified to ensure it's part of the ISV's official hosting.

**Pull request closed without merging**
