### PR TITLE
New Version: SoftFever.OrcaSlicer version 2.0.0

### PR DESCRIPTION
**Pull request by og-mrk**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/147065)

### CODE REVIEW

**Comment by og-mrk** [comment]
> Hello @og-mrk,
> 
> The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.
> 
> Template: msftbot/validationError/installation/general

May I ask for further details on why the validation test(s) failed?

**Comment by og-mrk** [comment]
Will convert this PR to Draft until PR #147146 is merged, mainly because I have some speculation around this package depending on **vcredist2019 x64** to be installed on the system, so when vcredist2019 x64 is added, I'll update this Manifest.

**Comment by og-mrk** [comment]
> Hello @og-mrk,
> 
> The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.
> 
> Template: msftbot/validationError/installation/general

Any details on why validation tests failed would be appreciated.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334960
> 2024-03-31 15:31:29.778 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFA20A2C11F: (caller: 00007FFA207B8D6F) LogHr(1) tid(196c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFA20932B08: (caller: 00007FFA209DBC20) Exception(1) tid(196c) 8A15005E ] 
> 2024-03-31 15:31:29.778 [REPO] Failed to open available source: msstore
> 2024-03-31 15:31:33.863 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFA20A2C11F: (caller: 00007FFA207B8D6F) LogHr(1) tid(1424) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFA20932B08: (caller: 00007FFA209DBC20) Exception(1) tid(1424) 8A15005E ] 
> 2024-03-31 15:31:33.864 [REPO] Failed to open available source: msstore
> 2024-03-31 15:31:41.239 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFA04B3C11F: (caller: 00007FFA048C8D6F) LogHr(1) tid(4e8) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFA04A42B08: (caller: 00007FFA04AEBC20) Exception(1) tid(4e8) 8A15005E ] 
> 2024-03-31 15:31:41.239 [REPO] Failed to open available source: msstore
> 2024-03-31 15:31:44.236 [CLI ] Package hash verification failed. SHA256 in manifest [0685c3054bbc59a1b1502257d0dafdf4dec22f0965ada2ea88939b4f729b795c] does not match download [d652ace87dc6b2b4bcf85e17e099a6928414134a71e4f5e45e580148c759a685]

(Automated response - build 876.)

**Comment by og-mrk** [comment]
> Automatic Validation ended with:
> 
> > Installation failed with exit code -1978334960
> > ...
> > 2024-03-31 15:31:44.236 [CLI ] Package hash verification failed. SHA256 in manifest [0685c3054bbc59a1b1502257d0dafdf4dec22f0965ada2ea88939b4f729b795c] does not match download [d652ace87dc6b2b4bcf85e17e099a6928414134a71e4f5e45e580148c759a685]
> 
> (Automated response - build 876.)
> 
> Edit: Neither of those hashes match the `InstallerSha256` in this manifest - because it's the dependency `Microsoft.EdgeWebView2Runtime` with the out-of-date `InstallerSha256`.

I've looked into Microsoft's Edge WebView 2 Runtime package, and it turns out the Installer Manifests for it uses a [this link](https://go.microsoft.com/fwlink/p/?LinkId=2124703), which changes overtime.

So I've a solution to give if it's possible to do so, which's utilizing **Microsoft Update Catalog** to retrieve pretty much all versions a user/package maintainer will ever need, but I don't know if this will break The Terms of Service that Microsoft has when we use the static download links they provide in this particular case, if you have a resource to direct me in the right direction, then it'll be of great help.

Also there's a way to automate the retrieval of all down links from a Search Query, using something like PowerShell Modules, so Implementing a simple script that automates this process is relatively easy if you know what you're doing.

**Comment by stephengillie** [comment]
> I've looked into Microsoft's Edge WebView 2 Runtime package, and it turns out all versions of Installer Manifests uses [this download link](https://go.microsoft.com/fwlink/p/?LinkId=2124703), which changes overtime.

Ah, we call this a "vanity URL" and we have many in our repo. Keeping all of their manifests updated with the current installer hash is a constant task. 

> So I've a solution to give if it's possible to do so, which's utilizing **Microsoft Update Catalog** to retrieve pretty much all versions a user/package maintainer will ever need, but I don't know if this will break The Terms of Service that Microsoft has when we use the static download links they provide in this particular case, if you have a resource to direct me in the right direction, then it'll be of great help.
> 
> Note
> 
> The Installers provided in Microsoft Update Catalog are Standalone, Platform Specific Installers (x86, amd64/x64, arm64 etc...), so every Installer Manifest, for every version Requires having all of the Different Installers specified, meaning we can't use a "Bootstrap" installation method, like the one currently being used in Edge Webview2 Runtime Package.

This implies that the manifest will need to detail every installer and location. There would be a measurable increase in the level of effort required to generate this package's manifest. 

> Also there's a way to automate the retrieval of all down links from a Search Query, using something like PowerShell Modules, so Implementing a simple script that automates this process is relatively easy if you know what you're doing.

This might be better as an input into one of our several manifest creation tools.

**Comment by stephengillie** [comment]
image
 
- https://github.com/microsoft/winget-pkgs/issues/107639

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
