### PR TITLE
Yandex browser 84.0.4147.112

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3655)

### CODE REVIEW

**Comment by oxygen-dioxide** [comment]
This app must be installed in an elevated shell microsoft/winget-cli#152

**Comment by oxygen-dioxide** [comment]
Wait a minute, the version of this yaml may be wrong.
The version of yandex browser's installer is 20.8.3.112.
image

However, the version in "chrome://version" is 84.0.4147.112
image

So which version should I write in the yaml?

**Comment by KevinLaMS** [comment]
i am seeing an isntall failure.
while it installs, it seems to have an error code at the end.

image

**Comment by oxygen-dioxide** [comment]
You have successfully installed yandex browser.
This app returns 1 when it installs successfully. We are blocked by microsoft/winget-cli#137

**Comment by denelon** [comment]
We now support non-zero exit codes :smile:

**Pull request closed without merging**
