### PR TITLE
Add version of ImageLine.FLStudio: 21.0.3.3517

### PR DESCRIPTION
**Pull request by w3lld0ne**
- [*] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [*] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [*] This PR only modifies one (1) manifest
- [*] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [*] Have you tested your manifest locally with `winget install --manifest <path>`?
- [*] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/102955)

### CODE REVIEW

**Comment by w3lld0ne** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Automatic Validation failed with:
> Response: An error was encountered while processing request. Exception:  
> Exception Message: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server. (type WebException)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
Exception during validation: System.Runtime.InteropServices.COMException (0x8007000D): The data is invalid. (0x8007000D) 
InstallationVerification-x64-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20230420002421

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
