### PR TITLE
​

### PR DESCRIPTION
**Pull request by ItzLevvie**
​

### CODE REVIEW

**Comment by ItzLevvie** [comment]
cc @KevinLaMS

**Comment by KevinLaMS** [comment]
This installer seems to reboot at completion.  I tried to see if I could suppress with --ignore-reboot, but it did not work. Thoughts?

**Comment by ItzLevvie** [comment]
cc @KevinLaMS, this PR has the same situation as https://github.com/microsoft/winget-pkgs/pull/4431#issuecomment-721975205

**Comment by KevinLaMS** [comment]
Sigh.  :(

**Pull request closed without merging**
