### PR TITLE
Fix Scope for Microsoft.VisualStudio.2022.Community 17.6.4

### PR DESCRIPTION
**Pull request by mdanish-kh**
- Related to https://github.com/microsoft/winget-cli/issues/3280

Tested locally by installing an older version and running `winget upgrade --manifest` on this manifest. I have a script to update other versions as well if required but fixing it for the latest one should unblock majority of the users

cc @denelon if this requires an approval from VS Team

[Policy] Blocking-Issue

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/108303)

### CODE REVIEW

**Comment by mdanish-kh** [comment]
[Policy] Blocking-Issue

**Comment by denelon** [comment]
@edwardskrod what are your thoughts on this one?

**Comment by mdanish-kh** [comment]
I'm seeing newer reports for the issue in https://github.com/microsoft/winget-pkgs/issues/94621; It seems that @stephengillie had manually verified the scope and added `Validation-Completed` label. Can we have a merge on this since this is blocking users from receiving upgrades of the package?

**Review by ItzLevvie — APPROVED** [review]

**Comment by denelon** [comment]
@edwardskrod I sent an e-mail about this PR.

**Comment by edwardskrod** [comment]
> * Related to [`winget upgrade --all` finds update but does nothing winget-cli#3280](https://github.com/microsoft/winget-cli/issues/3280)
> 
> Tested locally by installing an older version and running `winget upgrade --manifest` on this manifest. I have a script to update other versions as well if required but fixing it for the latest one should unblock majority of the users
> 
> cc @denelon if this requires an approval from VS Team
> 
> [Policy] Blocking-Issue
> 
> ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/108303)

Do we ALWAYS want the scope to be machine here?  If so, I'll update the templates.

**Comment by mdanish-kh** [comment]
@edwardskrod Yes; Since VS Installer appears to always install for "ALL USERS". Unless there's a future change to make it install per-user, we'd want to set the Scope value to `machine` in the manifest for WinGet to correctly match the installed version with an upgrade available in the repository

**Comment by edwardskrod** [comment]
Thanks very much.  

I fixed this issue on our side in Visual Studio.   The next time a package is generated and uploaded to WinGet, it will have the scope set to machine.

In the meantime, let's fix this issue here.

**Comment by edwardskrod** [comment]
> @edwardskrod what are your thoughts on this one?

I'm happy to take this.  Thanks [mdanish-kh](https://github.com/mdanish-kh)

**Comment by edwardskrod** [comment]
> @edwardskrod Yes; Since VS Installer appears to always install for "ALL USERS". Unless there's a future change to make it install per-user, we'd want to set the Scope value to `machine` in the manifest for WinGet to correctly match the installed version to an upgrade available in the repository

THANKS for confirming :)

**Review by denelon — APPROVED** [review]

**Pull request merged**
