### PR TITLE
Added MongoDB Server version 5.0.2.

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

------

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23839)

### CODE REVIEW

**Comment by jedieaston** [comment]
@ChuckFerring can this be merged or not? It still added the executable error even after you merged the override.

**Review by ItzLevvie — APPROVED** [review]

**Comment by palenshus** [comment]
> @ChuckFerring Chuck Ferring FTE can this be merged or not? It still added the executable error even after you merged the override.

The override only applies if it's for an already-checked-in version, that's why this one didn't take effect yet. It will for future version of this app though

**Pull request merged**
