### PR TITLE
New version: gmbertani.Echoes version 0.55

### LINKED ISSUE #154370: [Update Request]: Echoes
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

gmbertani.Echoes

### Package Version

0.52

### Please describe the changes you would like to see

There is a new release (0.52) available. Download Page Url: https://sourceforge.net/projects/echoes/files/Windows%20binaries/ (https://sourceforge.net/projects/echoes/files/Windows binaries/Install-echoes-0.52-Win64.exe)

### PR DESCRIPTION
**Pull request by schembriaiden**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.2.1 :rocket:

Resolves: https://github.com/microsoft/winget-pkgs/issues/154370

### CODE REVIEW

**Comment by vikingnope** [comment]
@stephengillie, can you rerun this please?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-05-21 09:29:21.596 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(267)\WindowsPackageManager.dll!00007FFA24A5A384: (caller: 00007FFA24A5AD01) Exception(2) tid(1710) 80D02002 
> 2024-05-21 09:29:33.286 [CLI ] ShellExecute installer failed: 2

Automated error analysis suggests -1978335226 may mean Install successful but system restart may be required.

(Automated response - build 881.)

**Comment by stephengillie** [comment]
This package doesn't appear to be finding its dependency. Running the attended installer gives: 
image

**Comment by vikingnope** [comment]
I think the PothosSDR install is still giving a bit of issues, we need the following setting to be enabled during the install, any idea on how to do this:

image

I think currently the silent install leaves it as `do not add to system PATH`

**Comment by stephengillie** [comment]
The package manager should already be adding it to the system PATH.

**Pull request closed without merging**
