### PR TITLE
New version: Google.Chrome.Canary version 128.0.6571.0

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#6293](https://github.com/SpecterShell/Dumplings/actions/runs/9758112279).

<details>

<summary>Log</summary>

````
Updated: 128.0.6570.0 → 128.0.6571.0
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161107)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by mdanish-kh** [comment]
[Policy] Needs-Manual-Merge

- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
