### PR TITLE
Updated GitExtensionsTeam.GitExtensions version 3.4.1.9675

### PR DESCRIPTION
**Pull request by ImJoakim**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/19765)

### CODE REVIEW

**Comment by ImJoakim** [comment]
----

**Review by jedieaston — APPROVED** [review]

**Comment by ImJoakim** [comment]
Liar!

**Comment by ImJoakim** [comment]
🤔 
```
PS C:\Users\WDAGUtilityAccount\Desktop\manifests> winget install -m "C:\Users\WDAGUtilityAccount\Desktop\manifests\g\GitExtensionsTeam\GitExtensions\3.4.1.9675"
Found Git Extensions [GitExtensionsTeam.GitExtensions]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/gitextensions/gitextensions/releases/download/v3.4.1/GitExtensions-3.4.1.9675-f49b4d059.msi
  ██████████████████████████████  22.3 MB / 22.3 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

**Comment by ImJoakim** [comment]
😕

**Comment by ImJoakim** [comment]
Any idea why this is failing @OfficialEsco?

**Comment by OfficialEsco** [comment]
> Any idea why this is failing @OfficialEsco?

If any of the PR's fails multiple times for some unknown reason @arjun-msft or @ChuckFerring will look at it as long as its not labeled with something we can fix, for example `Validation-Unattended-Failed`

However the MS team is only online in MS Work hours.. And the US celebrated Independence Day on the 4th and 5th which is why nothing got fixed in the weekend and yesterday..

**Comment by denelon** [comment]
We're not sure what caused this yet. We're looking into it.

```
##[error] Installer https://github.com/gitextensions/gitextensions/releases/download/v3.4.1/GitExtensions-3.4.1.9675-f49b4d059.msi Scan information: 'Error information: BlockingDetectionFound'
##[error] Result: Failed
```

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Please close and reopen the PR to rerun pipelines on this PR.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
