### PR TITLE
New version: SomePythonThings.WingetUIStore.Pre-release version 3.1.0

### PR DESCRIPTION
**Pull request by schembriaiden**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/154256)

### CODE REVIEW

**Comment by vikingnope** [comment]
Don't know if we should change the package identifier since it is now becoming unigetUI instead of wingetUI

**Comment by vikingnope** [comment]
On my system it installs correctly when run in sandbox

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code 1

(Automated response - build 881.)

**Comment by vikingnope** [comment]
Is it installing correctly or no?

**Comment by stephengillie** [comment]
Yes, this application installs and launches correctly in a Windows 10 VM: 
image

Despite this, the package manager still returned an exit code of `1`.

Should `1` be added as an `InstallerSuccessCode` or similar?

**Comment by vikingnope** [comment]
Previous versions did not have this but we can try and add it and see what happens.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code 1

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Hi @vikingnope,

> This PR's version number 3.1.0-alpha0 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 3.0.0.0, which has 4 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 881)

**Comment by stephengillie** [comment]
Hi @vikingnope,

This manifest adds Apps and Features entries that aren't present in previous PR versions. These entries should be added to the previous versions, or removed from this version.

(Automated response - build 881.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
