### PR TITLE
Update Dell.CommandUpdate.Universal to 5.0.0

### PR DESCRIPTION
**Pull request by FaserF**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/122363)

### CODE REVIEW

**Comment by FaserF** [comment]
Hmmm, I dont get the issue here. The URL is valid and works

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335226 
2023-10-11 01:15:35.434 [CLI ] ShellExecute installer failed: 4 

image

**Comment by stephengillie** [comment]
Manual Valdiation ended with:

**Comment by stephengillie** [comment]
This message is new in this version.

**Comment by FaserF** [comment]
Yeah that makes sense now that you say it. The program only runs on Dell devices. Anything I can do from my side?

**Comment by FaserF** [comment]
Wont be merged until https://github.com/microsoft/winget-cli/issues/1417

Therefore I close the PR for now.

**Pull request closed without merging**
