### PR TITLE
New version: SomePythonThings.WingetUIStore version 1.3.0

### PR DESCRIPTION
**Pull request by marticliment**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/78572)

### CODE REVIEW

**Review by sitiom — CHANGES_REQUESTED** [review]
Use the actual 1.3 release and not the test release: https://github.com/martinet101/WingetUI/releases/tag/1.3

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
See https://github.com/microsoft/winget-pkgs/pull/78572#pullrequestreview-1096239865

**Comment by martinet101** [comment]
@sitiom, The action won't run again. Do I need to create a new tag?

**Comment by sitiom** [comment]
> @sitiom, The action won't run again. Do I need to create a new tag?

1. Delete the existing tags
2. Tag `1.3` on the latest commit and attach the release on that tag
3. Convert to draft and undraft to retrigger the workflow

**Pull request closed without merging**
