### PR TITLE
Version Update: TeamRadarr.Radarr version 5.2.6

### PR DESCRIPTION
**Pull request by babblebauble**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131760)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @babblebauble,

This manifest removes Apps and Features entries that are present in previous PR versions. Should these entries be added to this version also?

(Automated response - build 489.)

**Comment by babblebauble** [comment]
> Hi @babblebauble,
> 
> This manifest removes Apps and Features entries that are present in previous PR versions. Should these entries be added to this version also?
> 
> (Automated response - build 489.)

Hi. I tested installation without the Apps and Features entries in the manifest and the installer writes the correct ARP entries to the registry so having the following entries in the manifest is unnecessary. 

`AppsAndFeaturesEntries:`
`- DisplayName: Radarr version x.x.x`

Capture

**Comment by stephengillie** [comment]
Hi @Trenly and @mdanish-kh,

Thoughts on Apps and Features entries for this package?

**Comment by Trenly** [comment]
Since it is *only* the display name that is in the manifest, I *think* it's okay to be left off. The biggest concern is if PackageVersion is missing.

I'd say let's merge this, I can do some testing after it passes publishing and add the entry if needed

**Comment by mdanish-kh** [comment]
It is generally a good idea to add as much metadata as you can, and Apps&Features helps with package correlation. In this case however, winget can already get a good match using the `PackageName` and `PackageVersion`. Having `AppsAndFeatures > DisplayName` for this package means that it would need to be manually updated for every new version (since current manifest creators don't have the ability to automate updating these fields).

Since it's only the `DisplayName` field in question here, and there is no need for explicit matching, I would gravitate towards excluding it

**Review by Trenly — APPROVED** [review]

**Comment by Trenly** [comment]
Ah, probably won't merge with the Needs-Attention label

[Policy] Reset Feedback

**Review by Trenly — APPROVED** [review]

**Pull request merged**
