### PR TITLE
New version: TheBrowserCompany.Arc version 1.12.2.40112

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#6957](https://github.com/SpecterShell/Dumplings/actions/runs/10151845738).

<details>

<summary>Log</summary>

````
Updated: 1.12.1.39629 → 1.12.2.40112
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/165159)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334972
> 2024-07-31 02:07:24.252 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFFDD89C11F: (caller: 00007FFFDD628D6F) LogHr(1) tid(5f4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFFDD7A2B08: (caller: 00007FFFDD84BC20) Exception(1) tid(5f4) 8A15005E ] 
> 2024-07-31 02:07:27.536 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFFC323C11F: (caller: 00007FFFC2FC8D6F) LogHr(1) tid(464) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFFC3142B08: (caller: 00007FFFC31EBC20) Exception(1) tid(464) 8A15005E ] 
> 2024-07-31 02:07:39.739 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFFBF33C11F: (caller: 00007FFFBF0C8D6F) LogHr(1) tid(1cf4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFFBF242B08: (caller: 00007FFFBF2EBC20) Exception(1) tid(1cf4) 8A15005E ] 
> 2024-07-31 02:08:30.958 [CORE] Deployment operation #2: Windows cannot install package TheBrowserCompany.Arc_1.12.2.40112_x64__ttt1ap7aakyb4 because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.33728.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00.UWPDesktop" currently installed are: {Microsoft.VCLibs.140.00.UWPDesktop_14.0.29231.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00.UWPDesktop_14.0.30704.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00.UWPDesktop_14.0.33321.0_x64__8wekyb3d8bbwe}
> 2024-07-31 02:08:30.958 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!00007FFFBF1C3F75: (caller: 00007FFFBF11A720) Exception(2) tid(1cf4) 80073CF3 Package failed updates, dependency or conflict validation.
> 2024-07-31 02:08:31.095 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFFBF1C2D2F: (caller: 00007FFFBF1C432C) Exception(3) tid(1cf4) 80073CF1 Package was not found.
> 2024-07-31 02:08:31.095 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(126)\WindowsPackageManager.dll!00007FFFBF338931: (caller: 00007FFFBF1C5853) LogHr(2) tid(1cf4) 80073CF1 Package was not found.
>     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFFBF1C2D2F: (caller: 00007FFFBF1C432C) Exception(3) tid(1cf4) 80073CF1 Package was not found.
> 2024-07-31 02:08:31.159 [CLI ] MSIX installer failed: 2147958003

Automated error analysis suggests -1978334972 may mean This package has a dependency missing from your system.

Automated error analysis suggests 8A15005E may mean APPINSTALLER_CLI_ERROR_PINNED_CERTIFICATE_MISMATCH - The server certificate did not match any of the expected values.

Automated error analysis suggests 2147958003 may mean Error Installing Dependency - Windows cannot install this package because it depends on a framework (version) that could not be found.

(Automated response - build 887.)

**Comment by spectopo** [comment]
https://github.com/microsoft/winget-pkgs/issues/161022

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
[Policy] Dependencies

**Comment by ItzLevvie** [comment]
[Policy] Dependencies
[Policy] Blocking-Issue

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

(Automated response - build 923.)

**Pull request merged**
