### PR TITLE
New version: lin-ycv.EverythingPowerToys version 0.81.0.1

### PR DESCRIPTION
**Pull request by lin-ycv**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/155163)

### CODE REVIEW

**Comment by lin-ycv** [comment]
@stephengillie what is this internal error dynamic scan? Everytime I push a release I get this error, and it retries multiple times. Is it something I can do to solve on my side?

**Comment by lin-ycv** [comment]
> This installer didn't add any files to the file system. Only the dependency was installed.

The issue seem to be that the exe can't be executed if it's downloaded by winget...? any idea why? if it's downloaded from browser it executes fine
800704c7

**Comment by stephengillie** [comment]
Hi @lin-ycv,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-29 15:41:31.220 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerSharedLib\SHA256.cpp(144)\WindowsPackageManager.dll!00007FFF005B273F: (caller: 00007FFF005FAEC4) Exception(2) tid(fc0) 8A150040 
> 2024-05-29 15:41:41.523 [FAIL] Installer failed security check. Url: https://github.com/lin-ycv/EverythingPowerToys/releases/download/v0.81.0.1/EverythingPT-0.81.0.1-x64%2BARM64.exe Result: 0x80004005
> MSI (s) (04:B4) [15:40:43:548]: Doing action: WixSchedFirewallExceptionsUninstall
> MSI (s) (04:E8) [15:40:43:564]: Invoking remote custom action. DLL: C:\Windows\Installer\MSIBE11.tmp, Entrypoint: SchedFirewallExceptionsUninstall
> Action start 15:40:43: WixSchedFirewallExceptionsUninstall.
> SchedFirewallExceptions:  Component 'MouseWithoutBordersFirewallComponent' action state (1) doesn't match request (2)
> SchedFirewallExceptions:  No firewall exceptions scheduled
> Action ended 15:40:43: WixSchedFirewallExceptionsUninstall. Return value 1.
> MSI (s) (04:B4) [15:40:46:626]: Doing action: WixSchedFirewallExceptionsInstall
> MSI (s) (04:18) [15:40:46:642]: Invoking remote custom action. DLL: C:\Windows\Installer\MSICA09.tmp, Entrypoint: SchedFirewallExceptionsInstall
> Action start 15:40:46: WixSchedFirewallExceptionsInstall.
> MSI (s) (04!0C) [15:40:46:658]: PROPERTY CHANGE: Adding WixRollbackFirewallExceptionsInstall property. Its value is '1PowerToys.MouseWithoutBorders2147483647LocalSubnet12C:\Users\validator\AppData\Local\PowerToys\PowerToys.MouseWithoutBorders.exe-2147483648'.
> SchedFirewallExceptions:  Scheduling firewall exception (1€PowerToys.MouseWithoutBorders€2147483647€LocalSubnet€1€2€C:\Users\validator\AppData\Local\PowerToys\PowerToys.MouseWithoutBorders.exe€€-2147483648€)
> MSI (s) (04!0C) [15:40:46:658]: Doing action: WixRollbackFirewallExceptionsInstall
> Action start 15:40:46: WixRollbackFirewallExceptionsInstall.
> MSI (s) (04!0C) [15:40:46:673]: PROPERTY CHANGE: Adding WixExecFirewallExceptionsInstall property. Its value is '1PowerToys.MouseWithoutBorders2147483647LocalSubnet12C:\Users\validator\AppData\Local\PowerToys\PowerToys.MouseWithoutBorders.exe-2147483648'.
> Action ended 15:40:46: WixRollbackFirewallExceptionsInstall. Return value 1.
> MSI (s) (04!0C) [15:40:46:673]: Doing action: WixExecFirewallExceptionsInstall
> Action start 15:40:46: WixExecFirewallExceptionsInstall.
> Action ended 15:40:46: WixExecFirewallExceptionsInstall. Return value 1.
> Action ended 15:40:46: WixSchedFirewallExceptionsInstall. Return value 1.
> MSI (s) (04:B4) [15:40:59:001]: Executing op: FileCopy(SourceName=e1qvh0l8.png|app_error.dark.png,SourceCabKey=launcherImagesComponentFiles_File_app_error.dark.png,DestName=app_error.dark.png,Attributes=512,FileSize=166,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,,,InstallMode=62914560,,,,,,,)
> MSI (s) (04:B4) [15:40:59:001]: File: C:\Users\validator\AppData\Local\PowerToys\Assets\PowerLauncher\app_error.dark.png;	To be installed;	Won't patch;	No existing file
> MSI (s) (04:B4) [15:40:59:001]: Source for file 'launcherImagesComponentFiles_File_app_error.dark.png' is compressed
> MSI (s) (04:B4) [15:40:59:001]: Executing op: FileCopy(SourceName=4btfkenk.png|app_error.light.png,SourceCabKey=launcherImagesComponentFiles_File_app_error.light.png,DestName=app_error.light.png,Attributes=512,FileSize=154,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,,,InstallMode=62914560,,,,,,,)
> MSI (s) (04:B4) [15:40:59:017]: File: C:\Users\validator\AppData\Local\PowerToys\Assets\PowerLauncher\app_error.light.png;	To be installed;	Won't patch;	No existing file
> MSI (s) (04:B4) [15:40:59:017]: Source for file 'launcherImagesComponentFiles_File_app_error.light.png' is compressed
> MSI (s) (04:B4) [15:41:00:205]: Executing op: FileCopy(SourceName=error32.png,SourceCabKey=RegistryPreviewAssetsFiles_File_error32.png,DestName=error32.png,Attributes=512,FileSize=678,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,,,InstallMode=62914560,,,,,,,)
> MSI (s) (04:B4) [15:41:00:205]: File: C:\Users\validator\AppData\Local\PowerToys\WinUI3Apps\Assets\RegistryPreview\error32.png;	To be installed;	Won't patch;	No existing file
> MSI (s) (04:B4) [15:41:00:205]: Source for file 'RegistryPreviewAssetsFiles_File_error32.png' is compressed
> MSI (s) (04:B4) [15:41:12:220]: Executing op: ActionStart(Name=WixRollbackFirewallExceptionsInstall,Description=Rolling back Windows Firewall configuration,)
> MSI (s) (04:B4) [15:41:12:220]: Executing op: CustomActionSchedule(Action=WixRollbackFirewallExceptionsInstall,ActionType=3329,Source=BinaryData,Target=ExecFirewallExceptions,CustomActionData=1PowerToys.MouseWithoutBorders2147483647LocalSubnet12C:\Users\validator\AppData\Local\PowerToys\PowerToys.MouseWithoutBorders.exe-2147483648)
> MSI (s) (04:B4) [15:41:12:220]: Executing op: ActionStart(Name=WixExecFirewallExceptionsInstall,Description=Installing Windows Firewall configuration,)
> MSI (s) (04:B4) [15:41:12:220]: Executing op: CustomActionSchedule(Action=WixExecFirewallExceptionsInstall,ActionType=3073,Source=BinaryData,Target=ExecFirewallExceptions,CustomActionData=1PowerToys.MouseWithoutBorders2147483647LocalSubnet12C:\Users\validator\AppData\Local\PowerToys\PowerToys.MouseWithoutBorders.exe-2147483648)
> MSI (s) (04:A0) [15:41:12:236]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI2E07.tmp, Entrypoint: ExecFirewallExceptions
> ExecFirewallExceptions:  Installing firewall exception2 PowerToys.MouseWithoutBorders (C:\Users\validator\AppData\Local\PowerToys\PowerToys.MouseWithoutBorders.exe)
> Property(S): WixRollbackFirewallExceptionsInstall = 1PowerToys.MouseWithoutBorders2147483647LocalSubnet12C:\Users\validator\AppData\Local\PowerToys\PowerToys.MouseWithoutBorders.exe-2147483648
> Property(S): WixExecFirewallExceptionsInstall = 1PowerToys.MouseWithoutBorders2147483647LocalSubnet12C:\Users\validator\AppData\Local\PowerToys\PowerToys.MouseWithoutBorders.exe-2147483648
> Property(S): ErrorDialog = ErrorDlg

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 881.)

**Comment by stephengillie** [comment]
> > This installer didn't add any files to the file system. Only the dependency was installed.
> 
> The issue seem to be that the exe can't be executed if it's downloaded by winget... it's blocked and needs to check unblock 
(GIF)
(GIF)
I feel that this is something winget should be able to deal with, is there anything i can add to the manifest to unblock after download?

I believe this is the "MOTW" (Mark Of The Web) seen in logs. Normally, this doesn't block applications from being executed, but instead prompts the user to install through SmartScreen and UAC.

**Review by stephengillie — DISMISSED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-30 14:34:08.002 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerSharedLib\SHA256.cpp(144)\WindowsPackageManager.dll!00007FFF7773273F: (caller: 00007FFF7777AEC4) Exception(2) tid(1a94) 8A150040 
> 2024-05-30 14:34:10.419 [FAIL] Installer failed security check. Url: https://github.com/lin-ycv/EverythingPowerToys/releases/download/v0.81.0.1/EverythingPT-0.81.0.1-x64%2BARM64.exe Result: 0x80004005
> MSI (s) (00:58) [14:33:26:570]: Doing action: WixSchedFirewallExceptionsUninstall
> MSI (s) (00:5C) [14:33:26:570]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI1A21.tmp, Entrypoint: SchedFirewallExceptionsUninstall
> Action start 14:33:26: WixSchedFirewallExceptionsUninstall.
> SchedFirewallExceptions:  Component 'MouseWithoutBordersFirewallComponent' action state (1) doesn't match request (2)
> SchedFirewallExceptions:  No firewall exceptions scheduled
> Action ended 14:33:26: WixSchedFirewallExceptionsUninstall. Return value 1.
> MSI (s) (00:58) [14:33:29:367]: Doing action: WixSchedFirewallExceptionsInstall
> MSI (s) (00:00) [14:33:29:367]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI250F.tmp, Entrypoint: SchedFirewallExceptionsInstall
> Action start 14:33:29: WixSchedFirewallExceptionsInstall.
> MSI (s) (00!E4) [14:33:29:382]: PROPERTY CHANGE: Adding WixRollbackFirewallExceptionsInstall property. Its value is '1PowerToys.MouseWithoutBorders2147483647LocalSubnet12C:\Users\validator\AppData\Local\PowerToys\PowerToys.MouseWithoutBorders.exe-2147483648'.
> SchedFirewallExceptions:  Scheduling firewall exception (1€PowerToys.MouseWithoutBorders€2147483647€LocalSubnet€1€2€C:\Users\validator\AppData\Local\PowerToys\PowerToys.MouseWithoutBorders.exe€€-2147483648€)
> MSI (s) (00!E4) [14:33:29:382]: Doing action: WixRollbackFirewallExceptionsInstall
> Action start 14:33:29: WixRollbackFirewallExceptionsInstall.
> MSI (s) (00!E4) [14:33:29:382]: PROPERTY CHANGE: Adding WixExecFirewallExceptionsInstall property. Its value is '1PowerToys.MouseWithoutBorders2147483647LocalSubnet12C:\Users\validator\AppData\Local\PowerToys\PowerToys.MouseWithoutBorders.exe-2147483648'.
> Action ended 14:33:29: WixRollbackFirewallExceptionsInstall. Return value 1.
> MSI (s) (00!E4) [14:33:29:382]: Doing action: WixExecFirewallExceptionsInstall
> Action start 14:33:29: WixExecFirewallExceptionsInstall.
> Action ended 14:33:29: WixExecFirewallExceptionsInstall. Return value 1.
> Action ended 14:33:29: WixSchedFirewallExceptionsInstall. Return value 1.
> MSI (s) (00:58) [14:33:39:101]: Executing op: FileCopy(SourceName=e1qvh0l8.png|app_error.dark.png,SourceCabKey=launcherImagesComponentFiles_File_app_error.dark.png,DestName=app_error.dark.png,Attributes=512,FileSize=166,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,,,InstallMode=62914560,,,,,,,)
> MSI (s) (00:58) [14:33:39:101]: File: C:\Users\validator\AppData\Local\PowerToys\Assets\PowerLauncher\app_error.dark.png;	To be installed;	Won't patch;	No existing file
> MSI (s) (00:58) [14:33:39:101]: Source for file 'launcherImagesComponentFiles_File_app_error.dark.png' is compressed
> MSI (s) (00:58) [14:33:39:101]: Executing op: FileCopy(SourceName=4btfkenk.png|app_error.light.png,SourceCabKey=launcherImagesComponentFiles_File_app_error.light.png,DestName=app_error.light.png,Attributes=512,FileSize=154,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,,,InstallMode=62914560,,,,,,,)
> MSI (s) (00:58) [14:33:39:101]: File: C:\Users\validator\AppData\Local\PowerToys\Assets\PowerLauncher\app_error.light.png;	To be installed;	Won't patch;	No existing file
> MSI (s) (00:58) [14:33:39:101]: Source for file 'launcherImagesComponentFiles_File_app_error.light.png' is compressed
> MSI (s) (00:58) [14:33:39:851]: Executing op: FileCopy(SourceName=error32.png,SourceCabKey=RegistryPreviewAssetsFiles_File_error32.png,DestName=error32.png,Attributes=512,FileSize=678,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,,,InstallMode=62914560,,,,,,,)
> MSI (s) (00:58) [14:33:39:851]: File: C:\Users\validator\AppData\Local\PowerToys\WinUI3Apps\Assets\RegistryPreview\error32.png;	To be installed;	Won't patch;	No existing file
> MSI (s) (00:58) [14:33:39:851]: Source for file 'RegistryPreviewAssetsFiles_File_error32.png' is compressed
> MSI (s) (00:58) [14:33:46:710]: Executing op: ActionStart(Name=WixRollbackFirewallExceptionsInstall,Description=Rolling back Windows Firewall configuration,)
> MSI (s) (00:58) [14:33:46:710]: Executing op: CustomActionSchedule(Action=WixRollbackFirewallExceptionsInstall,ActionType=3329,Source=BinaryData,Target=ExecFirewallExceptions,CustomActionData=1PowerToys.MouseWithoutBorders2147483647LocalSubnet12C:\Users\validator\AppData\Local\PowerToys\PowerToys.MouseWithoutBorders.exe-2147483648)
> MSI (s) (00:58) [14:33:46:710]: Executing op: ActionStart(Name=WixExecFirewallExceptionsInstall,Description=Installing Windows Firewall configuration,)
> MSI (s) (00:58) [14:33:46:710]: Executing op: CustomActionSchedule(Action=WixExecFirewallExceptionsInstall,ActionType=3073,Source=BinaryData,Target=ExecFirewallExceptions,CustomActionData=1PowerToys.MouseWithoutBorders2147483647LocalSubnet12C:\Users\validator\AppData\Local\PowerToys\PowerToys.MouseWithoutBorders.exe-2147483648)
> MSI (s) (00:F4) [14:33:46:710]: Invoking remote custom action. DLL: C:\Windows\Installer\MSI68D2.tmp, Entrypoint: ExecFirewallExceptions
> ExecFirewallExceptions:  Installing firewall exception2 PowerToys.MouseWithoutBorders (C:\Users\validator\AppData\Local\PowerToys\PowerToys.MouseWithoutBorders.exe)
> Property(S): WixRollbackFirewallExceptionsInstall = 1PowerToys.MouseWithoutBorders2147483647LocalSubnet12C:\Users\validator\AppData\Local\PowerToys\PowerToys.MouseWithoutBorders.exe-2147483648
> Property(S): WixExecFirewallExceptionsInstall = 1PowerToys.MouseWithoutBorders2147483647LocalSubnet12C:\Users\validator\AppData\Local\PowerToys\PowerToys.MouseWithoutBorders.exe-2147483648
> Property(S): ErrorDialog = ErrorDlg

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 882.)

**Comment by lin-ycv** [comment]
Anything I can do to not reduce the chance of this false positive? 
It just a self extractor built using NSIS, doesn't stop or start any processes

The script of the builder
```
!define EPT "EverythingPT"
!define PT "PowerToys.exe"

LoadLanguageFile "${NSISDIR}\Contrib\Language files\English.nlf"
;--------------------------------
;Version Information
  VIProductVersion "${ver}.0"
  VIAddVersionKey /LANG=${LANG_ENGLISH} "ProductName" "${EPT} Setup"
  VIAddVersionKey /LANG=${LANG_ENGLISH} "CompanyName" "lin-ycv"
  VIAddVersionKey /LANG=${LANG_ENGLISH} "LegalCopyright" "lin-ycv"
  VIAddVersionKey /LANG=${LANG_ENGLISH} "FileDescription" "Everything search plugin for PowerToys Run"
  VIAddVersionKey /LANG=${LANG_ENGLISH} "FileVersion" "${ver}"
  VIAddVersionKey /LANG=${LANG_ENGLISH} "ProductVersion" "${ver}"
;--------------------------------

BrandingText "${EPT} v${ver}"
CRCCheck force
FileErrorText "Can't write: $\r$\n$\r$\n$0$\r$\n$\r$\nPowerToys is probably still running, please close it and retry."
Icon Everything.ico
InstallDir "$LOCALAPPDATA\Microsoft\PowerToys\PowerToys Run\Plugins\Everything"
Name "${EPT}"
OutFile ".\..\bin\${EPT}-${ver}-x64+ARM64.exe"
RequestExecutionLevel user
SetCompressor /SOLID /FINAL lzma
LicenseData "MIT.txt"

;--------------------------------

Page license
Page instfiles

;--------------------------------

Section ""

  ClearErrors
  SetOutPath $INSTDIR
  GetFullPathName $0 "$EXEDIR\"
  GetFullPathName $0 $0
  File /r "${direct}\*"

  IfErrors 0 +5
  SetErrorlevel 2
  IfSilent +2
  MessageBox MB_ICONEXCLAMATION "Unable to install, PowerToys is probably still running, please close it manually before install."
  Abort
  
SectionEnd
```

**Comment by stephengillie** [comment]
Verify:
image
- No Registry entry
- Not showing up in PowerToys Run Settings:
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
