### PR TITLE
Update Arduino.Arduino to 1.8.15

### PR DESCRIPTION
**Pull request by KaranKad**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/13593)

### CODE REVIEW

**Comment by KaranKad** [comment]
This software tries to install usb drivers which winget cannot install

**Comment by arjun-msft** [comment]
https://github.com/microsoft/winget-cli/issues/910
https://github.com/microsoft/winget-cli/issues/163

**Comment by KaranKad** [comment]
image
Drivers are included in the installer and it even executes them, but windows security prompt pops up asking to install it or no. Just clicking install here completes the installation.

**Comment by KaranKad** [comment]
image
Drivers are included in the installer and by default it tries to install them, however Windows security screen pops up asking if you want to install the driver or no and winget is not able to do anything here. Just clicking install completes the installation, so I wonder if we could do that.

**Comment by denelon** [comment]
It looks like we're still blocked by microsoft/winget-cli#910 then. Be sure to 👍 that issue to help raise priority.

**Pull request closed without merging**
