### PR TITLE
Libretro.RetroArch version 1.10.3

### PR DESCRIPTION
**Pull request by fpscan**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/58053)

### CODE REVIEW

**Comment by fpscan** [comment]
I've tested on my environment before I submit this PR and it was worked fine. Now it's [failed](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=303579&view=logs&j=871b4eed-22de-5cb6-c1c8-82f190de633f&t=58bdf892-4e45-5ba7-4782-31912f95e167&l=38) but I can't see the reason or error code. It needs Directx9.0,(it work without it but some issues can happen) and I [added](https://github.com/microsoft/winget-pkgs/pull/58053/files#diff-f872def1c621bd8855b99fed1049399c05b34a744d0987fa8225be2538ead54fR11). Is there anything else I need to do in this state?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
In unattended (silent) mode, there's a prompt that shows it needs DirectX which requires user interaction which is why it fails.

This issue is being tracked at https://github.com/libretro/RetroArch/issues/13778.

**Comment by fpscan** [comment]
> In unattended (silent) mode, there's a prompt that shows it needs DirectX which requires user interaction which is why it fails.
> 
> This issue is being tracked at [libretro/RetroArch#13778](https://github.com/libretro/RetroArch/issues/13778).

I was expecting that if I add dependency in the yaml, it will install dx9 before installation start. I'll try to find another way, I belive zip installation is still not implemented(?)

**Comment by ItzLevvie** [comment]
> I was expecting that if I add dependency in the yaml, it will install dx9 before installation start. 

Support for WindowsFeatures hasn't been added yet. It's listed in the schema because it'll be coming soon in the future.

> I belive zip installation is still not implemented(?)

Not at the moment but it'll be coming soon.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/58053#issuecomment-1102551507

**Comment by fpscan** [comment]
> > I was expecting that if I add dependency in the yaml, it will install dx9 before installation start.
> 
> Support for WindowsFeatures hasn't been added yet. It's listed in the schema because it'll be coming soon in the future.
> 
> > I belive zip installation is still not implemented(?)
> 
> Not at the moment but it'll be coming soon.

So we will revisit the packaging nsi script end of this month meanwhile can we not close this PR? I also wonder if there is any roadmap that show us when these features will be added or not. Is it good idea to wait WindowsFeatures get implement so we don't deal with packaging on our end?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> So we will revisit the packaging nsi script end of this month meanwhile can we not close this PR?

You can keep the PR in DRAFT until it's fixed.

> Is it good idea to wait WindowsFeatures get implement so we don't deal with packaging on our end?

WindowsFeatures would probably take a while to implement. It seems like most of the focus right now is on PackageDependencies.

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
