### PR TITLE
New version: VPNetwork.TorGuard version 4.8.9-build.144.1+g3174a6b

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/45897)

### CODE REVIEW

**Review by quhxl — COMMENTED** [review]
Maybe we should change the link to this site:
https://updates.torguard.biz/Software/Windows/

was mentioned here:
https://forums.torguard.net/index.php?/topic/851-old-version-download/

**Review by quhxl — APPROVED** [review]
👀

**Comment by quhxl** [comment]
winget upgrade outputs this:
`VPNetwork LLC - TorGuard -… VPNetwork.TorGuard           "4.8.9-build.144.1+g3174a6b" 4.8.9-build.144.1+g3174a6b winget`

does the package version need to be changed to: `'"4.8.9-build.144.1+g3174a6b"'`? or does that cause even more problems with version comparison?

**Comment by OfficialEsco** [comment]
> winget upgrade outputs this: `VPNetwork LLC - TorGuard -… VPNetwork.TorGuard "4.8.9-build.144.1+g3174a6b" 4.8.9-build.144.1+g3174a6b winget`
> 
> does the package version need to be changed to: `'"4.8.9-build.144.1+g3174a6b"'`? or does that cause even more problems with version comparison?

I see..
`'"4.8.9-build.144.1+g3174a6b"'` gives  `String does not match the pattern of "^[^\\/:\*\?"<>\|\x01-\x1f]+$".`

**Pull request merged**
