### PR TITLE
New version: SimonG4ELI.SDR-Radio version 3.3

### PR DESCRIPTION
**Pull request by AsciiWolf**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

This PR replaces the [Beta package](https://github.com/microsoft/winget-pkgs/pull/137006). I will also make a PR that removes the old Beta.

Tested and works fine on my system. 64-bit installer only for now since the 32-bit one is hosted only on Dropbox at the moment and I would like to avoid using Dropbox for stable release packages.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137972)

### CODE REVIEW

**Comment by AsciiWolf** [comment]
@stephengillie Feel free to waive. Thanks! :-)

**Comment by stephengillie** [comment]
This PR uses the `Webhost` link while the previous used the `Dropbox` link. No action needed, just observing.

**Comment by AsciiWolf** [comment]
The Azure Pipeline fail looks unrelated.

**Comment by AsciiWolf** [comment]
@stephengillie Any idea what could be wrong? The manifest works without issues on my local system and is based on the previous beta one that was already published.

**Comment by AsciiWolf** [comment]
I am not sure what is wrong with the Azure Pipeline, but it is most likely unrelated to this PR. The installer should be basically the same as the already published [beta one](https://github.com/microsoft/winget-pkgs/pull/137006).

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
