### PR TITLE
New version: TranslucentTB.TranslucentTB version 2021.5.0.0

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/winget-pkgs-automation)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/29790)

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@KevinLaMS

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
This issue is caused by a dependency not available in the validation pipelines.

from the latest version of WinGet:
image

from an older version of WinGet:
image

**Review by ItzLevvie — COMMENTED** [review]
Considering that TranslucentTB is available in the Microsoft Store and the `msstore` source may likely be the default source. I don't know if this is needed.

winget install 9PF4KZ2VN4W9 should install `TranslucentTB` from the Microsoft Store.

**Comment by sylveon** [comment]
But `winget install TranslucentTB` should *not* install an old version. The version WinGet installs is old, broken on Windows 11, and not supported anymore.

Windows Terminal also depends on WinUI 2.6, and is updated regularly on WinGet, so what's up with that?

**Comment by ItzLevvie** [comment]
> Worse even, while it does find a duplicate when the msstore source is enabled, it does not say which one is newer:

You should be able to find the version of the package by searching for it via `winget search` or by being specific with `winget show`:
image

Currently, the Microsoft Store API that WinGet depends on doesn't expose a version; so "Unknown" in this case is the latest version that you published to the Microsoft Store (Retail).

> Windows Terminal also depends on WinUI 2.6+, and is updated regularly on WinGet, so what's up with that?

Windows Terminal ships with a pre-built version of WinUI 2.7 which is outside of the installation process.

I should have been a bit more clearer but this only affects applications that have `Microsoft.UI.Xaml` listed as a dependency (`<Dependency></Dependency>`) in their `AppxManifest.xml` file.

> If the version WinGet distributes cannot be updated to something newer, then TranslucentTB should be removed entirely from WinGet.

PR was created for it: #44603

**Pull request closed without merging**
