### PR TITLE
Devolutions.RemoteDesktopManager version 2021.1.34.0

### PR DESCRIPTION
**Pull request by krystofkrticka**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/16211)

### CODE REVIEW

**Comment by krystofkrticka** [comment]
Updated version of Remote Desktop Manager Enterprise

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
Please use `wingetcrate update -i Devolutions.RemoteDesktopManager -v 2021.1.34.0 -u https://cdn.devolutions.net/download/Setup.RemoteDesktopManager.2021.1.34.0.msi` when there is a existing package.

**Comment by krystofkrticka** [comment]
OK I'll fix that immediately.

**Comment by krystofkrticka** [comment]
> Please use `wingetcrate update -i Devolutions.RemoteDesktopManager -v 2021.1.34.0 -u https://cdn.devolutions.net/download/Setup.RemoteDesktopManager.2021.1.34.0.msi` when there is a existing package.

@OfficialEsco Should I create new PR when I use command with correct syntax?

**Comment by OfficialEsco** [comment]
> > Please use `wingetcrate update -i Devolutions.RemoteDesktopManager -v 2021.1.34.0 -u https://cdn.devolutions.net/download/Setup.RemoteDesktopManager.2021.1.34.0.msi` when there is a existing package.
> 
> @OfficialEsco Should I create new PR when I use command with correct syntax?

That would probably be easier yes

**Comment by krystofkrticka** [comment]
OK, I'll do that, this is first time I tried to updated package in repo so that's why I did this mistake.

**Comment by OfficialEsco** [comment]
> OK, I'll do that, this is first time I tried to updated package in repo so that's why I did this mistake.

Understandable :)
When doing `wingetcreate new` make sure the program you are about to add does not exist, search with both `winget search` and on GitHub.
If the package exist copy the `PackageIdentifier` and do `wingetcreate update -i "PackageIdentifier" -v "version" -u "url"`

**Comment by krystofkrticka** [comment]
OK, fixed version of manifest from this PR is in new PR with number #16216

**Pull request closed without merging**
