### PR TITLE
New version: Anchore.Grype version 0.84.0

### PR DESCRIPTION
**Pull request by popey**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/192597)

### CODE REVIEW

**Comment by popey** [comment]
@microsoft-github-policy-service agree company="Anchore"

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Anchore.Grype__DefaultSource\grype.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\grype.exe returned exit code: 1

(Automated response - build 898.)

**Comment by popey** [comment]
Sorry about this @stephengillie - unfortunately it's "Working As Designed" - as that's actually what happens if grype (and [syft](https://github.com/microsoft/winget-pkgs/pull/192601#issuecomment-2489162904) produce when run with no parameters.

Both programs detect that they're running in automation instead of an interactive terminal and suppress output. If the same executable is run inside a command prompt window, you'll get a summary help, and the same exit code (`%errorlevel%`) `1`. 

One workaround is to run either command with `--help` or `version`, which should yield a zero `%errorlevel%` and some output.

I just downloaded the zip, unpacked on a Windows 10 VM, and produced this:

windows-syft-grype

Is there some metadata I can specify in the packaging to coerce the automated testing to add some parameters to get a zero return code?

Many thanks.

**Comment by stephengillie** [comment]
Hi @popey,

The validation pipeline is somewhat designed for Windows Forms, and adds the https://github.com/microsoft/winget-pkgs/labels/Validation-Executable-Error link when the exit code is non-zero. But a non-zero exit code is common for CLI applications, so I usually pass exit codes below 1000. I"ve requested this change be pushed upstream: 
- https://github.com/microsoft/winget-pkgs/issues/157749

Please understand that my previous comment was the output of a scripted process which downloaded the run logs, filtered to include and exclude specific terms, then matched this against a list of error codes to produce the error analysis - before posting this output to the PR.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
