### PR TITLE
New version: SomePythonThings.WingetUIStore version 3.1.0

### PR DESCRIPTION
**Pull request by marticliment**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161285)

### CODE REVIEW

**Comment by marticliment** [comment]
Hi, it is the same issue as always. I thought I had fix it but what I changed was not the cause

**Comment by marticliment** [comment]
It fails

**Comment by marticliment** [comment]
> @marticliment, check the review and add the line

Excuse me, which line?

**Comment by vikingnope** [comment]
> > @marticliment, check the review and add the line
> 
> Excuse me, which line?

Oh ye sometimes it does not show, here it is

```suggestion
InstallerSuccessCodes:
- 1
```

Add this just above `Upgrade Behaviour`

**Comment by stephengillie** [comment]
The package manager is still using the dependency's exit code instead of the package's, it would appar.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
