### PR TITLE
Added TIDALMusicAS.TIDAL v2.28.0

### PR DESCRIPTION
**Pull request by OfficialEsco**
fixes #14132
closes #15944

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14250)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
@denelon what can we do about this?

**Comment by denelon** [comment]
Manifest: manifests\t\TIDALMusicAS\TIDAL\2.28.0
-----------------------------------------------------
URI: https://tidal.com/, Validation result: Failed, Http status code: Forbidden 
URI: https://tidal.com/help, Validation result: Passed
URI: https://tidal.com/privacy, Validation result: Failed, Http status code: Forbidden 
URI: https://tidal.com/, Validation result: Failed, Http status code: Forbidden 
URI: https://tidal.com/terms, Validation result: Passed
URI: https://tidal.com/terms, Validation result: Passed
URI: https://download.tidal.com/desktop/TIDALSetup.exe, Validation result: Passed

I have no idea why some pass and some are forbidden. I'll kick this off again.

**Comment by OfficialEsco** [comment]
```
URI: https://tidal.com/, Validation result: Failed, Http status code: Forbidden 
URI: https://tidal.com/help, Validation result: Failed, Http status code: Forbidden 
URI: https://tidal.com/privacy, Validation result: Failed, Http status code: Forbidden 
URI: https://tidal.com/, Validation result: Failed, Http status code: Forbidden 
URI: https://tidal.com/terms, Validation result: Failed, Http status code: Forbidden 
URI: https://tidal.com/terms, Validation result: Failed, Http status code: Forbidden 
URI: https://download.tidal.com/desktop/TIDALSetup.exe, Validation result: Passed
```

Seems like they closed the door completely this time, i think this needs a manual validation..

**Comment by denelon** [comment]
I just saw an e-mail from earlier that Azure Pipelines was having some trouble. It looks like there may still be degraded performance in the US https://status.dev.azure.com/

**Comment by denelon** [comment]
🤦‍♂️

**Comment by denelon** [comment]
Pretty please let /azp run pass.

**Pull request merged**
