### PR TITLE
New package: KernelWanderers.OCSysInfo version 1.1.0

### LINKED ISSUE #197035: [Package Request]: OCSysInfo
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [x] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/KernelWanderers/OCSysInfo
Publisher: KernelWanderers
Package Name: OCSysInfo
Description: A basic, high-level and efficient CLI for discovering hardware information about the current system.
Package Version: 1.1.0
Installer Url: https://github.com/KernelWanderers/OCSysInfo/releases/download/v1.1.0/ocsysinfo_win_x86_64-RELEASE.exe

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #197035

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

## Manual validation

image
image
image
image

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/197044)

### CODE REVIEW

**Comment by stephengillie** [comment]
Verify:
image

**Comment by stephengillie** [comment]
Hi @Dragon1573,

Since the application displays `1.0.8` while `1.1.0` is written to Registry, should a `DisplayVersion` be used here?

**Comment by Dragon1573** [comment]
I can't sure if it's intended. 😕

Which version should I attach to `DisplayVersion`? Could you please guide me with a "Change Request"? 🙏🏼

-----

Sorry to ping @KernelWanderers @xnus-kernel here 🙏🏼,

for a brief summary of what we're discussing - the package you released at `Jul 17, 2023, 9:04 AM GMT+8` with Git tag [`v1.1.0`](https://github.com/KernelWanderers/OCSysInfo/releases/tag/v1.1.0) responses version `v1.0.8` with `--version`.

Is it expected? Or did you accidentally publish the release with fault assets?

- See https://github.com/microsoft/winget-pkgs/pull/197044#issuecomment-2529370136

**Comment by kernel-dev** [comment]
> I can't sure if it's intended. 😕
> 
> Which version should I attach to `DisplayVersion`? Could you please guide me with a "Change Request"? 🙏🏼
> 
> Sorry to ping @KernelWanderers @Mahasvan @xnus-kernel here 🙏🏼,
> 
> for a brief summary of what we're discussing - the package you released at `Jul 17, 2023, 9:04 AM GMT+8` with Git tag [`v1.1.0`](https://github.com/KernelWanderers/OCSysInfo/releases/tag/v1.1.0) responses version `v1.0.8` with `--version`.
> 
> Is it expected? Or did you accidentally publish the release with fault assets?
> 
>     * See [New package: KernelWanderers.OCSysInfo version 1.1.0 #197044 (comment)](https://github.com/microsoft/winget-pkgs/pull/197044#issuecomment-2529370136)

That is a mere mistake on my part, I forgot to update the internal version within the application itself! I can try updating the current version with a quick-fix, but I'm unsure if our CI/CD that we have would update our version tag. In any case, I will resolve this issue if it's critical.

To be clear, the intended version displayed is meant to be v1.1.0

**Comment by kernel-dev** [comment]
To be clear once again, I am looking for a definitive answer as to whether or not I should push an update. cc: @Dragon1573  

Thank you in advance!

**Comment by Dragon1573** [comment]
> That is a mere mistake on my part, I forgot to update the internal version within the application itself! I can try updating the current version with a quick-fix, but I'm unsure if our CI/CD that we have would update our version tag. In any case, I will resolve this issue if it's critical.
> 
> To be clear, the intended version displayed is meant to be v1.1.0

@kernel-dev - Thanks for you explanation. ❤️

@stephengillie - Version information in "Add & Remove Programs" panel is the correct one, which is `v1.1.0` exactly ✅. `v1.0.8` shown with `ocsysinfo.exe` hasn't been modified before the release action and is just a mistake 😄. I think it's no need to add `DisplayVersion` into our manifest 🙏🏼.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
@Dragon1573 and @kernel-dev,

Thank you both for helping to resolve the issue. As long as it's known, there's no problem.

**Pull request merged**
