### PR TITLE
Delete manifests/o/Opera/OperaGX/76.0.4017.208 directory

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/77695)

### CODE REVIEW

**Review by jedieaston — CHANGES_REQUESTED** [review]
Why? These links still work for me.

**Comment by vedantmgoyal2009** [comment]
@jedieaston We keep the latest version for Brave, Edge and Chrome browsers since they auto-update themselves to newer versions. Hence, doing the same for Opera.

**Review by ItzLevvie — APPROVED** [review]

**Comment by vedantmgoyal2009** [comment]
.

**Pull request merged**
