### PR TITLE
GitHub,Inc.GitHubCLI version 1.11.0

### PR DESCRIPTION
**Pull request by Vishesh-Gupta**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/16617)

### CODE REVIEW

**Comment by Vishesh-Gupta** [comment]
Please wait for approval on this :) https://github.com/cli/cli/pull/3800.

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
https://github.com/cli/cli/pull/3801#issuecomment-856655782
Also why did you not bring the Metadata from the proper Manifest to this lazy `wingetcreate` version?

**Comment by jedieaston** [comment]
I went ahead and corrected the ID in a review on cli/cli#3801. Please make sure to correct the ID before that gets merged. (and it really shouldn't be merged until wingetcreate provides correct metadata, see [here](https://github.com/microsoft/winget-pkgs/discussions/15951#discussioncomment-823872)

**Comment by Vishesh-Gupta** [comment]
@jedieaston, the ID is now correct on cli/cli#3801. Will wait until wingetcreate provides correct metadata now.

**Pull request closed without merging**
