### PR TITLE
New package: FujiApple.Trippy version 0.7.0

### LINKED ISSUE #100719: [Package Request]: Trippy 0.7.0
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/fujiapple852/trippy/releases/tag/0.7.0
Publisher: https://github.com/fujiapple852
Package Name: Trippy (trip.exe)
Description: A network diagnostic tool
Package Version: 0.7.0
Installer URL: https://github.com/fujiapple852/trippy/releases/download/0.7.0/trippy-0.7.0-x86_64-pc-windows-msvc.zip

Note that I tried to create this myself using `wingetcreate` but was not able to get it to work (I understood that a zip'd `exe` should work?):

```
PS C:\Users\vboxuser> wingetcreate new https://github.com/fujiapple852/trippy/releases/download/0.7.0/trippy-0.7.0-x86_64-pc-windows-msvc.zip
Downloading and parsing: https://github.com/fujiapple852/trippy/releases/download/0.7.0/trippy-0.7.0-x86_64-pc-windows-msvc.zip...
Failed to parse the package from [https://github.com/fujiapple852/trippy/releases/download/0.7.0/trippy-0.7.0-x86_64-pc-windows-msvc.zip]
```

### PR DESCRIPTION
**Pull request by mdanish-kh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----
- Resolves  #100719
 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101363)

### CODE REVIEW

**Comment by mdanish-kh** [comment]
Hold off merging until issue with `RelativeFilePath` [#2909](https://www.github.com/microsoft/winget-cli/issues/2909) is resolved

**Comment by stephengillie** [comment]
This package is expecting arguments:
```
error: the following required arguments were not provided:
  <TARGETS>...

Usage: trip.exe <TARGETS>...

For more information, try '--help'.
```

**Review by ItzLevvie — APPROVED** [review]

**Comment by BrandonWanHuanSheng** [comment]
It look like winget cli released a newer version.

**Comment by BrandonWanHuanSheng** [comment]
Why github keep spamming your PR? That is weird.

**Comment by mdanish-kh** [comment]
@stephengillie Old PR here that was waiting on the stable release of WinGet 1.5; Now that we have 1.5 as stable release, this needs to be re-validated please

**Pull request merged**
