### PR TITLE
New version: ryanbekhen.nanoproxy 0.12.6

### PR DESCRIPTION
**Pull request by ryanbekhen**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/129578)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
image

**Comment by stephengillie** [comment]
Hi @BrandonWanHuanSheng,

This package didn't pass a Defender scan. This might be a false positive and we can rescan tomorrow.

**Comment by ryanbekhen** [comment]
@stephengillie So what should I do?

**Comment by stephengillie** [comment]
Hi @ryanbekhen,

Please virus scan your systems. Also beware using online services for creating icons and other artifacts - they often inject a virus after the image data in the file.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
