### PR TITLE
New version: yt-dlp.yt-dlp.nightly version 2024.02.05.232712

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137990)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification.
>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335226 2024-02-05 22:39:29.029 [FAIL] WindowsPackageManager.dll!00007FFE2164BDD2: ReturnHr(1) tid(19a4) 80190193 Forbidden (403).     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\HttpStream\HttpClientWrapper.cpp(50)\WindowsPackageManager.dll!00007FFE2163203A: (caller: 00007FFE21517669) Exception(1) tid(19a4) 80190193 Forbidden (403). 2024-02-05 22:39:29.029 [FAIL] WindowsPackageManager.dll!00007FFE214D3AF1: LogHr(1) tid(19a4) 80190193 Forbidden (403). 2024-02-05 22:39:29.031 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(53)\WindowsPackageManager.dll!00007FFE21657301: (caller: 00007FFE215204FE) LogHr(2) tid(19a4) 80190193 Forbidden (403).     Msg:[winrt::hresult_error: Forbidden (403).]  2024-02-05 22:39:29.031 [REPO] Source add/update failed, waiting a bit and retrying: winget 2024-02-05 22:39:31.057 [FAIL] WindowsPackageManager.dll!00007FFE2164BDD2: ReturnHr(2) tid(19a4) 80190193 Forbidden (403).     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\HttpStream\HttpClientWrapper.cpp(50)\WindowsPackageManager.dll!00007FFE2163203A: (caller: 00007FFE21517669) Exception(2) tid(19a4) 80190193 Forbidden (403). 2024-02-05 22:39:31.057 [FAIL] WindowsPackageManager.dll!00007FFE214D3AF1: LogHr(3) tid(19a4) 80190193 Forbidden (403). 2024-02-05 22:39:31.057 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(540)\WindowsPackageManager.dll!00007FFE216568E3: (caller: 00007FFE21418B8D) LogHr(4) tid(19a4) 80190193 Forbidden (403). 2024-02-05 22:39:31.057 [REPO] Failed to update source: winget 2024-02-05 22:39:31.239 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(564)\WindowsPackageManager.dll!00007FFE21656B53: (caller: 00007FFE21418B8D) LogHr(5) tid(19a4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFE21569298: (caller: 00007FFE216224F9) Exception(3) tid(19a4) 8A15005E ]  2024-02-05 22:39:31.239 [REPO] Failed to open available source: msstore 2024-02-05 22:39:31.251 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(205)\WindowsPackageManager.dll!00007FFE2153453A: (caller: 00007FFE21520B9E) Exception(4) tid(19a4) 8A15000F  2024-02-05 22:39:31.251 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(564)\WindowsPackageManager.dll!00007FFE21656B53: (caller: 00007FFE21418B8D) LogHr(6) tid(19a4) 8A15000F     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(205)\WindowsPackageManager.dll!00007FFE2153453A: (caller: 00007FFE21520B9E) Exception(4) tid(19a4) 8A15000F ]  2024-02-05 22:39:31.251 [REPO] Failed to open available source: winget 2024-02-05 22:39:31.251 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(571)\WindowsPackageManager.dll!00007FFE215210DB: (caller: 00007FFE21418B8D) Exception(5) tid(19a4) 8A15004B  2024-02-05 22:41:17.921 [CLI ] ShellExecute installer failed: 2 Installation failed with exit code -1978334972

(Automated response - build 695.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335226 2024-02-05 22:39:29.029 [FAIL] WindowsPackageManager.dll!00007FFE2164BDD2: ReturnHr(1) tid(19a4) 80190193 Forbidden (403).     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\HttpStream\HttpClientWrapper.cpp(50)\WindowsPackageManager.dll!00007FFE2163203A: (caller: 00007FFE21517669) Exception(1) tid(19a4) 80190193 Forbidden (403). 2024-02-05 22:39:29.029 [FAIL] WindowsPackageManager.dll!00007FFE214D3AF1: LogHr(1) tid(19a4) 80190193 Forbidden (403). 2024-02-05 22:39:29.031 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(53)\WindowsPackageManager.dll!00007FFE21657301: (caller: 00007FFE215204FE) LogHr(2) tid(19a4) 80190193 Forbidden (403).     Msg:[winrt::hresult_error: Forbidden (403).]  2024-02-05 22:39:29.031 [REPO] Source add/update failed, waiting a bit and retrying: winget 2024-02-05 22:39:31.057 [FAIL] WindowsPackageManager.dll!00007FFE2164BDD2: ReturnHr(2) tid(19a4) 80190193 Forbidden (403).     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\HttpStream\HttpClientWrapper.cpp(50)\WindowsPackageManager.dll!00007FFE2163203A: (caller: 00007FFE21517669) Exception(2) tid(19a4) 80190193 Forbidden (403). 2024-02-05 22:39:31.057 [FAIL] WindowsPackageManager.dll!00007FFE214D3AF1: LogHr(3) tid(19a4) 80190193 Forbidden (403). 2024-02-05 22:39:31.057 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(540)\WindowsPackageManager.dll!00007FFE216568E3: (caller: 00007FFE21418B8D) LogHr(4) tid(19a4) 80190193 Forbidden (403). 2024-02-05 22:39:31.057 [REPO] Failed to update source: winget 2024-02-05 22:39:31.239 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(564)\WindowsPackageManager.dll!00007FFE21656B53: (caller: 00007FFE21418B8D) LogHr(5) tid(19a4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFE21569298: (caller: 00007FFE216224F9) Exception(3) tid(19a4) 8A15005E ]  2024-02-05 22:39:31.239 [REPO] Failed to open available source: msstore 2024-02-05 22:39:31.251 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(205)\WindowsPackageManager.dll!00007FFE2153453A: (caller: 00007FFE21520B9E) Exception(4) tid(19a4) 8A15000F  2024-02-05 22:39:31.251 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(564)\WindowsPackageManager.dll!00007FFE21656B53: (caller: 00007FFE21418B8D) LogHr(6) tid(19a4) 8A15000F     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(205)\WindowsPackageManager.dll!00007FFE2153453A: (caller: 00007FFE21520B9E) Exception(4) tid(19a4) 8A15000F ]  2024-02-05 22:39:31.251 [REPO] Failed to open available source: winget 2024-02-05 22:39:31.251 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(571)\WindowsPackageManager.dll!00007FFE215210DB: (caller: 00007FFE21418B8D) Exception(5) tid(19a4) 8A15004B  2024-02-05 22:41:17.921 [CLI ] ShellExecute installer failed: 2 Installation failed with exit code -1978334972

(Automated response - build 695.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978334972

(Automated response - build 707.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
