### PR TITLE
Add version: Python.Python.3.12 version 3.12.0b4

### PR DESCRIPTION
**Pull request by CoolPlayLin**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/112951&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by SpecterShell** [comment]
🤔
image

**Comment by CoolPlayLin** [comment]
> 🤔
> image
> 
> 

The id is correct. It appears winget regard 3.12 as the latest version of python

**Comment by BrandonWanHuanSheng** [comment]
I think could be related to that issues [Matching Logic need to be updated.](https://github.com/microsoft/winget-cli/issues/2995)

**Comment by CoolPlayLin** [comment]
> I think could be related to that issues [Matching Logic need to be updated.](https://github.com/microsoft/winget-cli/issues/2995)

It seems more serious in my machine 
image
It even regards 3.11 as 3.12

**Pull request merged**
