### PR TITLE
New version: pizzaboxer.Bloxstrap version 2.4.0

### PR DESCRIPTION
**Pull request by pizzaboxer**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/113084&drop=dogfoodAlpha

### CODE REVIEW

**Review by 7xa5h — APPROVED** [review]

**Comment by pizzaboxer** [comment]
Likely due to missing .NET 6 dependency. See https://github.com/microsoft/winget-pkgs/pull/105938#issuecomment-1534973236.

image

**Comment by kxorey** [comment]
is there a way to add roshade or maybe reshade to bloxstrap?

**Comment by pizzaboxer** [comment]
Forgot about this, thanks for that.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
