### PR TITLE
Remove old version of JanDeDobbeleer.OhMyPosh

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/37292)

### CODE REVIEW

**Review by OfficialEsco — COMMENTED** [review]
Uh oh
```
Enter a pull request number: 37292

Manifest validation succeeded.
Found Standard Notes [StandardNotes.StandardNotes] Version 3.9.8
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/standardnotes/desktop/releases/download/v3.9.8/standard-notes-3.9.8-win-x64.exe
  ██████████████████████████████  68.6 MB / 68.6 MB
Successfully verified installer hash
An anti-virus product reports an infection in the installer

Press any key to continue . . .
```

**Review by OfficialEsco — COMMENTED** [review]
Not sure how THIS passed and not qBittorrent that we are allowed to install...
image
This gets obliviated by Windows Defender the second its downloaded...
@denelon any comments? 🤔
https://www.virustotal.com/gui/url/ab2825b88b5174ca1762d2c18f41b10230c0edce2c6cbf40926b78875c3208ad/detection
https://www.virustotal.com/gui/file/e27b7ab4785ac2bc2e018d1b3f83069b5c31a21a5d9f01ab5a6b499c1d8f6383

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Oops.

Please see https://github.com/microsoft/winget-pkgs/pull/37292#pullrequestreview-827965499:
image

**Comment by ItzLevvie** [comment]
Issue is being tracked at https://github.com/standardnotes/desktop/issues/795

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
