### PR TITLE
GlobalMarineNet.Xoc version 1.22

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/107510)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

I believe both of these required OSes (2000 and XP) have passed beyond long-term support and thus aren't suitable for validation. Is there an installer switch or other way to have it install on a newer OS?

**Comment by upintheairsheep** [comment]
> Automatic Validation ended with: image
> 
> I believe both of these required OSes (2000 and XP) have passed beyond long-term support and thus aren't suitable for validation. Is there an installer switch or other way to have it install on a newer OS?

Correct. Both are discontinued however in properties there is an option to fake a windows version, including 2000 and XP (which we'll choose)

**Comment by upintheairsheep** [comment]
> Automatic Validation ended with: image
> 
> I believe both of these required OSes (2000 and XP) have passed beyond long-term support and thus aren't suitable for validation. Is there an installer switch or other way to have it install on a newer OS?

Like this: https://m.majorgeeks.com/index.php?ct=content&action=file&id=3071

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
I'm seeing this:
image

**Comment by ItzLevvie** [comment]
[Policy] Interactive-Only-Installer

Putting this as `Interactive-Only-Installer` since this requires Compatibility mode.

You can bypass the "requires an old OS prompt" by right-clicking `xocsetup1.22.exe` > Properties > Compatibility > Windows XP (Service Pack 3):
image

**Pull request closed without merging**
