### PR TITLE
JanDeDobbeleer.OhMyPosh version 14.0.3

### PR DESCRIPTION
**Pull request by JanDeDobbeleer**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

### CODE REVIEW

**Review by ImJoakim — APPROVED** [review]

**Review by mdanish-kh — APPROVED** [review]

**Review by mdanish-kh — APPROVED** [review]

**Comment by JanDeDobbeleer** [comment]
@stephengillie why is this stuck? Seems like every PR is blocked just like this one.

**Comment by mdanish-kh** [comment]
- https://github.com/microsoft/winget-pkgs/issues/95543

**Comment by stephengillie** [comment]
> @stephengillie why is this stuck? Seems like every PR is blocked just like this one.

We're working to identify and resolve some issues that are causing internal errors within the pipeline. https://github.com/microsoft/winget-pkgs/issues/95543

**Review by mdanish-kh — APPROVED** [review]

**Review by ryfu-msft — APPROVED** [review]

**Pull request merged**
