### PR TITLE
Signal v1.34.3

### PR DESCRIPTION
**Pull request by OfficialEsco**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2155)

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Validation has completed

**Comment by bearmannl** [comment]
@OfficialEsco, is there a reason you went for the Signal.Signal package name instead of OpenWhisperSystems.Signal as per the Publisher.Package convention? Am considering deleting all 21 versions of the package and re-adding them with the correct naming convention, as I did for the Signal-Beta package, but would like to get your thoughts before I get started on 42 PR's to get it done...

**Comment by OfficialEsco** [comment]
This is a oooooooooooold Package Identifier as you can see in https://github.com/microsoft/winget-pkgs/pull/605. Back then none mentioned Publisher as per Control Panel. So instead we used the website or simplified "Publisher". Publisher got fixed in https://github.com/microsoft/winget-pkgs/pull/12182 which is when we got the word that winget uses the control panel to match packages.

Just downloaded 1.0.35 to see if they actually did Publish under Signal but they never did.
image

`Signal.Signal` is sorta a "valid" PackageIdentifier as long as `Open Whisper Systems` do not publish multiple Softwares or are known as `Open Whisper Systems`.

Feel free to move the manifests (which i see you've stated with lmao), however recommend you to wait until i approve a Manifest in `OpenWhisperSystems.Signal` so you can easily make good manifests with `wingetcreate update "id" --version --url --submit`

**Comment by bearmannl** [comment]
> This is a oooooooooooold Package Identifier as you can see in #605. Back then none mentioned Publisher as per Control Panel. So instead we used the website or simplified "Publisher". Publisher got fixed in #12182 which is when we got the word that winget uses the control panel to match packages.
> 
> Just downloaded 1.0.35 to see if they actually did Publish under Signal but they never did.
> image
> 
> `Signal.Signal` is sorta a "valid" PackageIdentifier as long as `Open Whisper Systems` do not publish multiple Softwares or are known as `Open Whisper Systems`.
> 
> Feel free to move the manifests (which i see you've stated with lmao), however recommend you to wait until i approve a Manifest in `OpenWhisperSystems.Signal` so you can easily make good manifests with `wingetcreate update "id" --version --url --submit`

Cool, that makes sense.

I get that this has some history and that it is 'sorta' valid, although I'm seeing mixed implementations in the repository at times, which is not only inconsistent but also confusing to newcomers who lack some of the history (case in point 👋🏻☺).

Call me crazy (for doing the work now) but it makes it easier to apply the naming convention in a uniform manner without exception. Imagine if Open Whisper Systems publishes an additional app a few years down the line, then you would have to do the same rework I just did, but with even more versions in the backlog...

Thanks for the reply Esco, very informative 👊🏻

**Pull request merged**
