### PR TITLE
New version: LutzRoeder.Netron version 7.3.8

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/133895)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification.
>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by mdanish-kh** [comment]
[Policy] Needs-Attention

@stephengillie - Can you add this package in your auth list? The publisher @[lutzroeder](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+author%3Alutzroeder) usually submits PRs for this package.

**Comment by stephengillie** [comment]
@mdanish-kh,

Should this be a "should" or "must"? "Should" will alert but still approve, while "must" blocks the approval.

**Comment by mdanish-kh** [comment]
@stephengillie 

I believe it can be a "should" unless @lutzroeder feels that any modifications to Netron's manifests are to be restricted

**Pull request closed without merging**
