### PR TITLE
bump ACLAP.DownloadHelperCoApp to 2.0.19

### PR DESCRIPTION
**Pull request by ACasset**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/147476)

### CODE REVIEW

**Comment by ACasset** [comment]
@microsoft-github-policy-service agree

**Comment by ACasset** [comment]
Possible duplicate of #147461 (but different package name)

**Comment by ACasset** [comment]
Adresses https://github.com/microsoft/winget-pkgs/issues/147477

**Comment by stephengillie** [comment]
> Possible duplicate of #147461 (but different package name)

Same hash `E1AF498F95432A4F2F666A8CBEC7BD6AB9DEB4D1695C6E7CDE7ACB9BD408E600` in 
- #147461

These `PackageIdentifiers` should be merged. Thanks for catching this.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
