### PR TITLE
New version: Dell.CommandUpdate.Universal 5.2.0

### PR DESCRIPTION
**Pull request by AidanRB**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/145814)

### CODE REVIEW

**Comment by AidanRB** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-03-21 07:00:36.803 [CLI ] ShellExecute installer failed: 4

(Automated response - build 870.)

**Comment by AidanRB** [comment]
> Automatic Validation ended with:
> 
> > Installation failed with exit code -1978335226
> > 2024-03-21 07:00:36.803 [CLI ] ShellExecute installer failed: 4
> 
> (Automated response - build 870.)

The installer exits with code 4 on non-Dell systems, as this is Dell exclusive software. Should this be added as a success code, or can this check be bypassed?

**Comment by AidanRB** [comment]
@stephengillie Unsure of how to proceed, see my comment above

**Comment by AidanRB** [comment]
Duplicate of https://github.com/microsoft/winget-pkgs/pull/138818

**Pull request closed without merging**
