### PR TITLE
New Version: Sigil-Ebook.Sigil version 2.2.0

### PR DESCRIPTION
**Pull request by dougmassay**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/158783)

### CODE REVIEW

**Comment by dougmassay** [comment]
Same exact process for the last update that worked just fine, now generates a new error. Why isn't there any consistency with these validation checks any more?

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/discussions/155218

**Review by stephengillie — APPROVED** [review]

**Comment by denelon** [comment]
> Same exact process for the last update that worked just fine, now generates a new error. Why isn't there any consistency with these validation checks any more?

@dougmassay we've been working through a large number of internal changes associated with Azure Dev Ops pipelines, and other mandatory changes to Azure services recently. I'm expecting that's most likely the reason you're seeing some inconsistency.

**Comment by dougmassay** [comment]
> @dougmassay we've been working through a large number of internal changes associated with Azure Dev Ops pipelines, and other mandatory changes to Azure services recently. I'm expecting that's most likely the reason you're seeing some inconsistency.

OK. Thanks.

It just seems like something has either changed or broken on Winget's end with each new version (of the one piece of software I maintain) that I try to submit. The times that things have "just worked as they should" have been few and far between.

**Pull request merged**
