### PR TITLE
VulkanRT 1.3.268.0

### PR DESCRIPTION
**Pull request by sandercox**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/124997)

### CODE REVIEW

**Comment by sandercox** [comment]
@stephengillie yes it's ok not that many files are installed there. TO run run vkcube example from the SDK you needed vulkan-1.dll but that gets installed by this installer into the `c:\windows\system32` folder. which is where it is 'supposed' to be. And next to a couple of other vulkan based tools.

**Comment by stephengillie** [comment]
I see these files when running the installer manually, but not with the manifest. I wonder if the installer switches need adjustment.

**Comment by sandercox** [comment]
> I see these files when running the installer manually, but not with the manifest. I wonder if the installer switches need adjustment.

Not sure what you mean. When I run this installer in the sandbox I don't have the vulkan-1.dll in c:\Windows\System32 before and I do have them afterwards. I'm not sure what else to test regarding this. They are not installed into c:\program files

**Comment by stephengillie** [comment]
Closing due to no activity.

**Comment by sandercox** [comment]
@stephengillie can you explain how I can test what you observe to be an error. I think the package behaves as supposed to be.

Bit if I have not reproducible steps to evaluate what you want changed I cannot move forward on this either. Willing to help here, but need more input.

**Comment by stephengillie** [comment]
Hi @sandercox,

Our validations start with a fresh image of Windows 10 or 11 inside a VM, and we ask that testing be performed on a similar system, or in a prepared Sandbox. On your system, it seems you have some additional software installed, possibly including display drivers. 

* Could you prepare a fresh Windows 10 VM and install the software? Hopefully this will present a similar-enough environment to recreate the issue I'm seeing.

**Comment by sandercox** [comment]
@stephengillie sorry It took a while for me to get back to this but as I'd still like to have this added to WinGet as I'm setting up new computers soon I reviewed it again today.

I think we misread each others messages before but the package is still valid as it is today.

> In a Windows 10 VM, this package only installed a couple of files. Is this expected? image

While maybe this is bad behaviour from the package itself it is how it will be installed even with other install flags, the files are actually installed into `%windir%\System32` and `%windir%\SysWOW64`.

When you run the installer manually this can be viewed in the installer details:

```
Delete file: C:\Program Files (x86)\VulkanRT\install.log
Output folder: C:\Windows\System32
File C:\Windows\System32\vulkan-1.dll (version 1.3.268.0) will be upgraded to 1.3.268.0
Extract: vulkan-1.dll... 100%
File C:\Windows\System32\vulkan-1-999-0-0-0.dll (version 1.3.268.0) will be upgraded to 1.3.268.0
Extract: vulkan-1-999-0-0-0.dll... 100%
File C:\Windows\System32\vulkaninfo.exe (version 1.3.268.0) will be upgraded to 1.3.268.0
Extract: vulkaninfo.exe... 100%
File C:\Windows\System32\vulkaninfo-1-999-0-0-0.exe (version 1.3.268.0) will be upgraded to 1.3.268.0
Extract: vulkaninfo-1-999-0-0-0.exe... 100%
Output folder: C:\Windows\SysWOW64
File C:\Windows\SysWOW64\vulkan-1.dll (version 1.3.268.0) will be upgraded to 1.3.268.0
Extract: vulkan-1.dll... 100%
File C:\Windows\SysWOW64\vulkan-1-999-0-0-0.dll (version 1.3.268.0) will be upgraded to 1.3.268.0
Extract: vulkan-1-999-0-0-0.dll... 100%
File C:\Windows\SysWOW64\vulkaninfo.exe (version 1.3.268.0) will be upgraded to 1.3.268.0
Extract: vulkaninfo.exe... 100%
File C:\Windows\SysWOW64\vulkaninfo-1-999-0-0-0.exe (version 1.3.268.0) will be upgraded to 1.3.268.0
Extract: vulkaninfo-1-999-0-0-0.exe... 100%
Output folder: C:\Program Files (x86)\VulkanRT
Extract: VulkanRT-License.txt... 100%
Completed
```

I verfied these files do not exist on a blank sandbox (`.\Tools\SandboxTest.ps1`) and are created when running (`.\Tools\SandboxTest.ps1 .\manifests\k\KhronosGroup\VulkanRT\1.3.268.0`)

So I believe that all is valid - but maybe unconventional for the package to install directly into the System32/SysWOW64 directory though but the package has it's reasons for this as these are main drivers for the Vulkan Engine that are used by many different software applications from this shared location.

Please reconsider approving this MR.

**Pull request closed without merging**
