### PR TITLE
New version: Microsoft.GitCredentialManagerCore version 2.0.567

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/winget-pkgs-automation)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/30205)

### CODE REVIEW

**Review by OfficialEsco — CHANGES_REQUESTED** [review]

**Review by jedieaston — CHANGES_REQUESTED** [review]
This should probably be excluded from your automation (as @OfficialEsco alludes to). Just wanted to add context: https://github.com/microsoft/Git-Credential-Manager-Core/actions/workflows/release-winget.yaml

**Comment by jedieaston** [comment]
I'm not sure if they'll be escaped or not, you might have to test it in a fork. Maybe `\# Automatically updated with workflow`?

**Comment by vedantmgoyal2009** [comment]
YAML supports comments: https://github.com/microsoft/winget-pkgs/blob/master/manifests/a/AntoineAflalo/SoundSwitch/5.0.4.31153/AntoineAflalo.SoundSwitch.yaml#L5

**Comment by OfficialEsco** [comment]
Well, that would be ANOTHER way to submit PRs, i just wanted to make this https://github.com/microsoft/Git-Credential-Manager-Core/blob/main/.github/workflows/release-winget.yaml into a multi manifest
Also any Microsoft project should start using wingetcreate which is made my Microsoft tbh..

**Comment by ldennington** [comment]
This package has been removed from [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/winget-pkgs-automation). I am in the process of updating it to be deployed automatically with multiple manifest files via `wingetcreate`. I believe this PR can be closed.

**Review by ldennington — APPROVED** [review]

**Comment by jedieaston** [comment]
> During installation testing, the test was unable to locate the primary application. Make sure the application installs correctly on all platforms. If your application does not install an application, but should still be included in the repository, add a comment to the pull request to get the Windows Package Manager engineers to investigate.

(excerpt from [here](https://docs.microsoft.com/en-us/windows/package-manager/package/winget-validation)) 

Can anyone manually verify that the other installer entry that’s being added here works? I have no idea how wingetsvc looks for an executable ([*ahem*](https://github.com/microsoft/winget-pkgs/discussions/13643)) but if it’s going into a weird spot (like program files (x86) instead of normal program files) it might be tripping the pipeline up.

**Review by ItzLevvie — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
