### PR TITLE
New version: vim.vim.nightly version 9.1.0454

### PR DESCRIPTION
**Pull request by chrisbra**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/155940)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-31 16:01:57.495 [FAIL] Installer failed security check. Url: https://github.com/vim/vim-win32-installer/releases/download/v9.1.0454/gvim_9.1.0454_x86.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 882.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-06-03 08:39:02.501 [FAIL] Installer failed security check. Url: https://github.com/vim/vim-win32-installer/releases/download/v9.1.0454/gvim_9.1.0454_x86.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 882.)

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/pull/155807#issuecomment-2159424970

**Review by ImJoakim — APPROVED** [review]

**Pull request merged**
