### PR TITLE
New version: pizzaboxer.Bloxstrap version 2.1.1

### PR DESCRIPTION
**Pull request by pizzaboxer**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/102611)

### CODE REVIEW

**Comment by pizzaboxer** [comment]
Requires .NET 6 desktop runtime as a dependency, see https://github.com/microsoft/winget-pkgs/issues/92827#issuecomment-1369993178.

image

**Comment by stephengillie** [comment]
Automatic Validation failed with:
InstallationVerification-x86-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20230416021120

**Comment by pizzaboxer** [comment]
> Even with the dependency preinstalled, the installer asks to install it. image

It doesn't really make sense that the installer asks to install it when it's preinstalled, since in my screenshot above I had the runtime preinstalled, and installing with Winget was completely fine. I even tried it in a VM to be sure, and it definitely works. Besides, the runtime check is done by .NET itself and not by me - if it failed to detect itself when it's really installed then I think there'd be a wider problem than just this. Can I see which version of the desktop runtime is installed?

image

**Comment by pizzaboxer** [comment]
> x86 Automatic Validation failed with: InstallationVerification-x86-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20230416021120
> 
> x64 validation failed for the `x64` architecture version of the dependency.


I noticed this myself when testing the install in a VM, but Winget doesn't even try to install the runtime even though it's explicitly specified as a dependency in the installer YAML for `Microsoft.DotNet.DesktopRuntime.6`. I know it was mentioned that dependency support is an experimental feature, but has it always been like this? I'm just wondering why this is only a problem now as nothing relating to this has changed between the previous version and now.

**Comment by sitiom** [comment]
This happens every time. Is validation not installing the correct .NET Runtime arch?

**Comment by pizzaboxer** [comment]
> This happens every time. Is validation not installing the correct .NET Runtime arch?

See https://github.com/microsoft/winget-pkgs/pull/103098#issuecomment-1518421875, seems like it's being worked out.

**Pull request closed without merging**
