### PR TITLE
sharkdp.bat version 0.22.1

### PR DESCRIPTION
**Pull request by neomax7**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/93805)

### CODE REVIEW

**Comment by neomax7** [comment]
manifest v1.4 with zip

**Comment by neomax7** [comment]
manifest version is 1.4 with zipped portable executable

**Comment by Trenly** [comment]
@msftbot zip

**Review by sitiom — CHANGES_REQUESTED** [review]
Please add 32-bit executable: https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-v0.22.1-i686-pc-windows-msvc.zip

I also think the manifest name should be lowercased: `sharkdp.bat`

**Comment by neomax7** [comment]
> Please add 32-bit executable: https://github.com/sharkdp/bat/releases/download/v0.22.1/bat-v0.22.1-i686-pc-windows-msvc.zip
> 
> I also think the manifest name should be lowercased: `sharkdp.bat`

Hi,
I have added 32-bit executable
but I think the manifest name is correct as it is now.
ref:
https://learn.microsoft.com/en-us/windows/package-manager/package/manifest?tabs=minexample%2Cversion-example
image

**Comment by sitiom** [comment]
Not all manifests in this repo are upper case (e.g., [vim.vim](https://github.com/microsoft/winget-pkgs/tree/master/manifests/v/vim/vim)), we should try to match the casing of the original program. Clearly both `sharkdp` and `hyperfine` are referenced by the author as lowercase.

- Please try to match it with my manifest: https://github.com/microsoft/winget-pkgs/pull/94708

**Comment by neomax7** [comment]
> Not all manifests in this repo are upper case (e.g., [vim.vim](https://github.com/microsoft/winget-pkgs/tree/master/manifests/v/vim/vim)). We should try to match the casing of the original program. Clearly, the author references both his name (`sharkdp`) and `hyperfine` as lowercase.
> 
> Please try to match it with my manifests:
> 
> * [New package: sharkdp.hyperfine version 1.15.0 #94708](https://github.com/microsoft/winget-pkgs/pull/94708)
> * [New package: sharkdp.fd version 8.6.0 #94714](https://github.com/microsoft/winget-pkgs/pull/94714)

okay updated the identifier and the filename. 
I thought it's a rule to keep the first letter as a capital.

**Review by sitiom — CHANGES_REQUESTED** [review]
In my experience, [`YamlCreate.ps1`](https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1) is better than WingetCreate. The `Sharkdp/Bat` folder is also still capitalized; please fix. Here are some other improvements:

**Pull request closed without merging**
