### PR TITLE
Update minimum dependency version for DevHome

### PR DESCRIPTION
**Pull request by mdanish-kh**
- Related to https://github.com/microsoft/winget-cli/issues/3668

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/120840)

### CODE REVIEW

**Comment by mdanish-kh** [comment]
cc @denelon Is MinimumVersion validation not enabled in the pipelines? 👀 It passes validation locally -

image

**Comment by mdanish-kh** [comment]
image

Not sure if this is the expected result but putting this here just in case 🤔 Maybe I'm incorrectly using the field

**Comment by denelon** [comment]
@mdanish-kh that's correct. Until more than half the clients on devices in the wild have the latest client, we don't update the validation pipelines.

**Review by denelon — APPROVED** [review]

**Pull request merged**
