### PR TITLE
Add version 6.20.529 of VNCViewer

### PR DESCRIPTION
**Pull request by piraces**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [X] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3924)

### CODE REVIEW

**Comment by piraces** [comment]
This type of installer does not have `Silent` or `SilentWithProgress` switches.

**Comment by KevinLaMS** [comment]
image

**Comment by piraces** [comment]
🤕 Ouch... I review it and I will try to make it work without user input. Sorry

**Comment by piraces** [comment]
I think this installer does not support unattended setup... Then, How do I proceed?

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/910

We need to give users the ability to filter out installers that require interactive experiences.

**Pull request closed without merging**
