### PR TITLE
GitVersion: added version 5.11.1

### PR DESCRIPTION
**Pull request by arturcic**
Apply suggestions from code review

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/97653)

### CODE REVIEW

**Comment by arturcic** [comment]
@stephengillie is there anything I need to fix to move this forward?

**Comment by arturcic** [comment]
Sure, thanks for the feedback,

**Comment by stephengillie** [comment]
Hi @arturcic,

Sorry for the sparse response.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
