### PR TITLE
New package: tecnocrata.depscop version 0.1.42

### PR DESCRIPTION
**Pull request by tecnocrata**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/153649)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @tecnocrata,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-14 19:59:49.967 [FAIL] Installer failed security check. Url: https://github.com/tecnocrata/deps-cop/releases/download/0.1.42/depscop-windows-0.1.42.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 881.)

**Comment by tecnocrata** [comment]
@microsoft-github-policy-service agree [company="tecnocrata"]

**Comment by tecnocrata** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Hi @tecnocrata,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-15 20:34:34.862 [FAIL] Installer failed security check. Url: https://github.com/tecnocrata/deps-cop/releases/download/0.1.42/depscop-windows-0.1.42.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Hi @tecnocrata,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-16 16:33:26.981 [FAIL] Installer failed security check. Url: https://github.com/tecnocrata/deps-cop/releases/download/0.1.42/depscop-windows-0.1.42.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\depscop.exe returned exit code: 2

(Automated response - build 881.)

**Comment by tecnocrata** [comment]
> Hi @tecnocrata,
> 
> This package installs to the C:\ root. Installing and operating from this location is not recommended. Can it be installed to another location, such as Program Files or AppData?
> 
> Edit: Verify while here: (No Registry data) image

I'm fixing the issue using a portable app

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\tecnocrata.depscop__DefaultSource\depscop.exe returned exit code: 2
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\depscop.exe returned exit code: 2

(Automated response - build 881.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
