### PR TITLE
New package: AmyXun.AxMath version 2.7059

### LINKED ISSUE #88303: [Package Request]: AxMath
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher:Amyxun
Publisher Url:https://www.amyxun.com/
Package Name:AxMath
Description:A professional formula editor for users of Microsoft Office programs
Package Version:2.7058
Installer URL:https://download.s21i.faiusr.com/4232652/0/0/ABUIABBPGAAg886mmQYolufQ4AU.zip?f=%E5%85%AC%E5%BC%8F%E7%BC%96%E8%BE%91%E5%99%A8_AxMath_Setup_Win_20220920.zip&v=1663674227

Current Package Identifier (for new versions):

### PR DESCRIPTION
**Pull request by SpecterShell**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

* Resolves #88303

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/121437)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @SpecterShell,

This package doesn't appear to be freely available for download. I couldn't find the InstallerUrl from the PackageUrl.

**Comment by SpecterShell** [comment]
It can be directly downloaded from <https://www.amyxun.com/>, the homepage for zh-CN.

**Comment by SpecterShell** [comment]
And for their English site, the download link can be found in the homepage, which is Mega Drive.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
