### PR TITLE
Windscribe.Windscribe version 2.10.16

### PR DESCRIPTION
**Pull request by Eddga**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/169337)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 888.)

**Comment by Eddga** [comment]
> Automatic Validation ended with:
> 
> 
> (Automated response - build 888.)

What does that mean? It worked when I tried it on my machine.
Silent install before was achieved by only using -silent switch. However WindScribe would always automatically launch after installing which I wouldn't consider silent. So I added -no-auto-start which according to installer help file prevents this. This worked fine for me.
I also added the x86 architecture as according to installer name it supports both x64 and x86. However I only have a x64 machine and can't test x86. Maybe that's the one throwing an error?

**Comment by stephengillie** [comment]
> > Automatic Validation ended with:
> > 
> > (Automated response - build 888.)
> 
> What does that mean? It worked when I tried it on my machine. Silent install before was achieved by only using -silent switch. However WindScribe would always automatically launch after installing which I wouldn't consider silent. So I added -no-auto-start which according to installer help file prevents this. This worked fine for me. I also added the x86 architecture as according to installer name it supports both x64 and x86. However I only have a x64 machine and can't test x86. Maybe that's the one throwing an error?

Hi @Eddga,

That's the filtered output of the run logs - it's supposed to say "No errors to post" but there must be a non-printing character slipping past the filters. The pipelines failed this package, but did not emit any error data to support, so I mark this as passing.

**Review by stephengillie — APPROVED** [review]

**Comment by Eddga** [comment]
Thanks a lot @stephengillie! 😊

**Pull request merged**
