### PR TITLE
Update: Mozilla.Firefox.DeveloperEdition version 128.0 (128.0b9)

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#6207](https://github.com/SpecterShell/Dumplings/actions/runs/9717310629).

<details>

<summary>Log</summary>

````
Updated: 128.0b8 → 128.0b9
Submitting WinGet manifests
Found existing pull requests:
Update: Mozilla.Firefox.DeveloperEdition version 128.0 (128.0b8) - https://github.com/microsoft/winget-pkgs/pull/160111
This task is configured to ignore existing pull requests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/160572)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by mdanish-kh** [comment]
[Policy] Needs-Manual-Merge

- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
