### PR TITLE
Go musicfox 4.1.4

### PR DESCRIPTION
**Pull request by anhoder**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

### CODE REVIEW

**Comment by anhoder** [comment]
@microsoft-github-policy-service agree

**Comment by anhoder** [comment]
It should be displayed in Chinese. Maybe the character set set by your terminal does not support Chinese, try to change it to utf8?

**Comment by stephengillie** [comment]
I tried changing to UTF8, but the output was the same.

**Comment by anhoder** [comment]
Sorry, I don't know what package I need to rely on to display Chinese in the terminal, because I always use it on the Chinese version of Windows, and it works very well. Maybe I need to specify a Chinese language package, but I don't know the exact name. Can you give me any help, thanks🙏🏻

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
