### PR TITLE
Try to fix EVGA 1.0.6

### PR DESCRIPTION
**Pull request by lychichem**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/7920)

### CODE REVIEW

**Comment by jedieaston** [comment]
is this another instance of the URL bug? It also happens with the links in the FileZilla manifests, see #7841.

**Comment by lychichem** [comment]
> is this another instance of the URL bug? It also happens with the links in the FileZilla manifests, see #7841.

I think so. I can download the file via the link in #7841 .

**Comment by KevinLaMS** [comment]
Ashwini, can you see why the service is getting a permission error.

**Comment by ashpatil-msft** [comment]
Investigating, will update once I find anything.

**Pull request closed without merging**
