### PR TITLE
Add Files UWP

### PR DESCRIPTION
**Pull request by yair100**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/925)

### CODE REVIEW

**Comment by Jaiganeshkumaran** [comment]
Id should not contain spaces

**Comment by yaichenbaum** [comment]
I think I found where the issue is.

**Comment by yaichenbaum** [comment]
@Jaiganeshkumaran And idea what I am doin wrong here? I tried many different ideas 😂.

**Comment by ath0mas** [comment]
Hello, my PR #1033 duplicates yours, so I suggest you to look at it for diffs (mostly `Id:`, `Version:`, `Name:`, `Publisher:` and `Description:`)

**Comment by yaichenbaum** [comment]
@ath0mas Hi, I am one of the developer of Files UWP, is there anything you think I should change with this pull request?

**Comment by ath0mas** [comment]
@yaichenbaum ok fine ;) and after review of my suggestions I think your PR is alright

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
