### PR TITLE
New package: swxtz.etec-config version 1.0.0

### PR DESCRIPTION
**Pull request by swxtz**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/144940)

### CODE REVIEW

**Comment by swxtz** [comment]
@microsoft-github-policy-service agree [company="swxtz"]

**Comment by swxtz** [comment]
@microsoft-github-policy-service agree company="swxtz"

**Comment by stephengillie** [comment]
Hi @swxtz,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-17 02:04:34.358 [FAIL] Installer failed security check. Url: https://github.com/swxtz/etec-config/releases/download/v1/etec-config.msi Result: 0x80004005

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-03-22 16:29:04.562 [CLI ] ShellExecute installer failed: 1603
> CustomAction _B3D13F97_1369_417D_A477_B4C42B829328 returned actual error code -1073741515 (note this may not be 100% accurate if translation happened inside sandbox)
> MSI (s) (FC:94) [16:29:04:135]: Product: Exe to msi converter free -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action _B3D13F97_1369_417D_A477_B4C42B829328, location: C:\Windows\Installer\MSI7594.tmp, command:  
> Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action _B3D13F97_1369_417D_A477_B4C42B829328, location: C:\Windows\Installer\MSI7594.tmp, command:  
> MSI (s) (FC:94) [16:29:04:230]: Product: Exe to msi converter free -- Installation failed.

(Automated response - build 873.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 10:18:05 AM: 
> 2024-03-25 10:18:05.164 [CLI ] ShellExecute installer failed: 1603 10:18:05 AM: CustomAction _B3D13F97_1369_417D_A477_B4C42B829328 returned actual error code -1073741515 (note this may not be 100% accurate if translation happened inside sandbox) 10:18:05 AM: MSI (s) (50:D8) [10:18:04:646]: Product: Exe to msi converter free -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action _B3D13F97_1369_417D_A477_B4C42B829328, location: C:\Windows\Installer\MSI87CC.tmp, command: 10:18:05 AM: Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action _B3D13F97_1369_417D_A477_B4C42B829328, location: C:\Windows\Installer\MSI87CC.tmp, command: 10:18:05 AM: MSI (s) (50:D8) [10:18:04:693]: Product: Exe to msi converter free -- Installation failed. 10:18:05 AM: MSI (s) (50:D8) [10:18:04:693]: Windows Installer installed the product. Product Name: Exe to msi converter free. Product Version: 2.0.0. Product Language: 1033. Manufacturer: www.exetomsi.com. Installation success or error status: 1603.

(Automated response - build 873.)

**Pull request closed without merging**
