### PR TITLE
Correct Folder Structure (WikidPad) Continued from #22551

### LINKED ISSUE #22505: Problem with w\WikiPad manifest?
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue
When I fork and clone the repository to my local PC, the entry for w\WikiPad in Manifests is always marked as "dirty" on my PC. My fork insists that it is up to date with Master, and I can't see how to resolve this. Is there some error in the repository for the Manifest w\WikiPad ?
# Steps to reproduce
Forked the repo to my account on GitHub and using TortoiseGit created a clone on my local PC

# Expected behavior
I would expect a full, clean copy of the repo on my PC

# Actual behavior
The Manifest w\WikiPad is always flagged as "dirty"

# Environment

```none
Windows Package Manager v1.0.11694
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22000.100
Package: Microsoft.DesktopAppInstaller v1.15.11694.0

Any other software?
TortoiseGit 2.12.0.0 (C:\Program Files\TortoiseGit\bin)
git version 2.31.1.windows.1 (C:\Program Files\Git\bin; C:\Program Files\Git\mingw64\; C:\Program Files\Git\etc\gitconfig)
```

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----
Fixes #22505 
Continuation of #22551 
Dup. of #22546

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/22552)

### CODE REVIEW

**Comment by vedantmgoyal2009** [comment]
@jedieaston Please review it.

**Comment by OfficialEsco** [comment]
Can you update the Metadata on this one since it's a newer version? Can't check PR's for another 1.5h anyways so

**Review by OfficialEsco — APPROVED** [review]

**Comment by vedantmgoyal2009** [comment]
@msftbot why do i need to remind you every time, can't you marge automatically? died bot!

**Comment by OfficialEsco** [comment]
Your comments don't do anything, it reruns every hour of when we reapprove it

**Comment by jedieaston** [comment]
Is the hour a guarantee? I was watching it last night when I was cleaning stuff up and stuff sat in Moderator-Approved for multiple hours before being merged (wish I had an example on me, oh wells). 

That wingetbot/pipeline open source can't come soon enough. I want to know why some of this stuff is happening.

**Comment by OfficialEsco** [comment]
I know it tries to run them hourly (since the issues started), but if there are a bunch it might just run some, AFAIK you seem to be active when the MS Team is working, so the delays might be because of them tweaking stuff

The new issue where the bot removes `Needs: author feedback` and `Needs-Author-Feedback` seems to be a side effect of this
https://github.com/microsoft/winget-pkgs/pull/22608
(My timezone)
```
12:15 AM Levvie requested changes
12:45 AM (Late MS Work hours)
12:47 AM Levvie requested changes
02:00 AM
02:02 AM Levvie requested changes
06:01 AM
10:58 AM I requested changes
12:01 PM
12:02 AM Levvie requested changes
12:15 AM Levvie closed it
```
As you can see, its not even consistent, but something happens around the hour mark
As for case https://github.com/microsoft/winget-pkgs/pull/22355 it seems like the bot forgot the PR even existed and instead wanted its own PRs to get merged

revalidated on the hour PRs: (last 25 approved reviews by me)
https://github.com/microsoft/winget-pkgs/pull/22596
https://github.com/microsoft/winget-pkgs/pull/22594
https://github.com/microsoft/winget-pkgs/pull/22565
https://github.com/microsoft/winget-pkgs/pull/22556
https://github.com/microsoft/winget-pkgs/pull/22552 (this PR)
https://github.com/microsoft/winget-pkgs/pull/22550
https://github.com/microsoft/winget-pkgs/pull/22544

I've noticed if we Approve a bunch real fast it will start hanging

**Comment by vedantmgoyal2009** [comment]
Is `Moniker` **case-sensitive** or **case-insensitive**?

**Comment by jedieaston** [comment]
> Is Moniker case-sensitive or case-insensitive?

The field name or the value? You have to capitalize the field name, the value isn't case sensitive.

> I've noticed if we Approve a bunch real fast it will start hanging

I wonder why it doesn't just go over the open PRs like a queue. Although that brings up a different question, which one is hanging: msftbot (which is a different team at Microsoft AFAIK, and seems to be doing the merging in this repo based on configuration the winget team set), or @wingetbot, which is something that the team has more control over. And what's @wingetbot's architecture anyway? Can it not be scaled at peak times? 

I'll have to go ping that ticket I made a while back about open-sourcing the bot and see if there's been any traction on it lately, I'm really interested in how it works.

**Comment by vedantmgoyal2009** [comment]
> The field name or the value? You have to capitalize the field name, the value isn't case sensitive.

Thanks. Actually, I am making a script to find duplicate monikers in the repository. Only error catching part is left.

**Comment by OfficialEsco** [comment]
> Edit: Please also tell if the moniker can have spaces. I don't think so...

it can, it shouldnt as its should be a quick nickname

> Anyways, I saw Levvie and other users, who have their scripts to get some functionalities of @wingetbot.

None but the MS Team can interract with the bot and there is certanly no script functionalities…

**Comment by vedantmgoyal2009** [comment]
> it can, it shouldnt as its should be a quick nickname

So, should I update the moniker of the packages so that they don't have spaces?

> None but the MS Team can interract with the bot and there is certanly no script functionalities…

To be clear, Levvie has created a script to get the HTTP codes of all the Download URLs present in the repository. Like @wingetbot does periodically.

**Comment by OfficialEsco** [comment]
> So, should I update the moniker of the packages so that they don't have spaces?

Yes, all spaces should be replaced with "-", the moniker could also be the same as Chocolatey or Scoop uses

> To be clear, Levvie has created a script to get the HTTP codes of all the Download URLs present in the repository. Like @wingetbot does periodically.

Can't really call it a wingetbot function when its as simple as just checking the InstallerUrls from the Winget Pkgs repo 🤷‍♂️

**Comment by vedantmgoyal2009** [comment]
@OfficialEsco I ran my script to check moniker conflicts and found about a hundred packages that need to be corrected. Since the validation pipeline supports one version of one package, I will have to open lots of PR so please don't call me a spammer. Also, this time, I'm not stealing someone else's work. Please 🙏

**Comment by OfficialEsco** [comment]
Hmm, just got to thinking after approving the Powershell ones, it would be smart to also corrected the Publisher and PackageName on those cuz that can also cause issues

**Comment by vedantmgoyal2009** [comment]
Hello again, just wanted to confirm that is it necessary to add Product Codes for msi, msix and appx installers?

**Comment by OfficialEsco** [comment]
If the MSI contains the ProductCode you might aswell add it, but you don't need to dig around Registry for it, YamlCreate will show you the ProductCode (when using Powershell 5)
MSIX and Appx is different because they integrate with the Microsoft Store, here the FamilyName is important AFAIK.

However there is no reason to mass update manifests to add the ProductCode, as it is used for matching the application to the PackageID incase the Publisher/PackageName/Version is causing issues.

**Comment by vedantmgoyal2009** [comment]
> If the MSI contains the ProductCode you might aswell add it, but you don't need to dig around Registry for it, YamlCreate will show you the ProductCode (when using Powershell 5)

Well, I am using PS 7 and it never showed me up so, I removed that condition on my machine. In the YamlCreate v2.0.0, I would suggest using 'greater than equal to' rather than using only 'equal to' for the condition.

> However there is no reason to mass update manifests to add the ProductCode, as it is used for matching the application to the PackageID incase the Publisher/PackageName/Version is causing issues.

Okay, actually I was experimenting with the repository and found 972 packages that have MSI installers but don't have Product Codes.

**Comment by OfficialEsco** [comment]
The function does not work on PS5+.
It is only actually needed if it dosn't match, most of those 972 packages most likely already matches.

**Comment by denelon** [comment]
@msftbot is a tool developed by another team.
They are just about to make modifications so that we can have the config as code in this repository. I don't know when/if they plan to open source that tool. It mostly gives us the ability to have actions/responses when events happen to Issues/PRs etc.

@wingetbot is a bot we implemented.
It requires quite a bit more custom logic and code, but because of this, it is "more" capable.

We're constantly running into challenges with infrastructure and connectivity across GitHub, Azure DevOps, Azure Functions, etc. There are several different work arounds and retry algorithms we implement to address flaky behavior when we encounter it. The assumption is everything is going to break, so try to build resilient distributed systems. We're moving fast to try and fix issues, and improve things, but that comes as the cost of stability of behavior. I've been working with the teams to try and be better about adding issues in this repository to at least telegraph what we're working on. We've been making heavy investments to improve things here at the expense of other areas of the product.

**Comment by vedantmgoyal2009** [comment]
> The function does not work on PS5+.

# SEE THIS
image

**Comment by OfficialEsco** [comment]
Ahh right, what i meant was the command works differently in PS5+, you need to regex the ProductCode from the Publisher field.

**Comment by jedieaston** [comment]
> Okay, actually I was experimenting with the repository and found 972 packages that have MSI installers but don't have Product Codes.

There's a lot of reasons why this could be, mostly because lots of MSIs add more than one entry to the ARP table and therefore we didn't (or at least I didn't) put any ProductCode entry since it would've been inaccurate. Once schema 1.1 is ready for use, we can figure out the best strategy for filling the new array of ARP entries for every installer entry (my vote is to have @wingetbot automatically determine what the ARP changes are after the installer runs and post them as a [pull request review](https://docs.github.com/en/rest/reference/pulls#create-a-review-for-a-pull-request), but i've gotta write down what I'm envisioning better)).

**Comment by denelon** [comment]
@jedieaston we've also been thinking about how the validation pipelines can help with this. We've looked at a few options, but we're open to feedback. Our initial thoughts are for the validation service to respond to a PR with what has been detected with respect to installers. In particular we're also looking at the best way to handle installers with multiple ARP entries. 

I did a poll a while back with how we could handle these system driven suggestions, and we got some mixed results. We've been thinking about attempting to parse the initial PR conversation to see if users want us to just commit changes to the PR (this would likely change the ordering of the keys in the YAML), or make suggestions on the PR. A large percentage of users wanted both of those options, and some users just wanted us to make comments on the PR so the user could make the changes on their own.

**Pull request merged**
