### PR TITLE
New version: rhysd.actionlint version 1.7.3

### PR DESCRIPTION
**Pull request by rhysd**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/175722)

### CODE REVIEW

**Comment by rhysd** [comment]
I don't know how to fix the issue. I used [the same GitHub Actions workflow]https://github.com/rhysd/actionlint/blob/main/.github/workflows/release.yaml) as the previous version for creating this PR. And [the previous version PR](https://github.com/microsoft/winget-pkgs/pull/174773) was successful.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-09-29 12:48:12.975 [FAIL] Installer failed security check. Url: https://github.com/rhysd/actionlint/releases/download/v1.7.3/actionlint_1.7.3_windows_amd64.zip Result: 0x80004005
> 2024-09-29 05:45:34.206 [FAIL] Installer failed security check. Url: https://github.com/rhysd/actionlint/releases/download/v1.7.3/actionlint_1.7.3_windows_386.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 896.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\rhysd.actionlint__DefaultSource\actionlint.exe returned exit code: 3
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\actionlint.exe returned exit code: 3
> Installation failed with exit code -1978335187
> 2024-10-03 11:37:18.538 [FAIL] Installer failed security check. Url: https://github.com/rhysd/actionlint/releases/download/v1.7.3/actionlint_1.7.3_windows_386.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 896.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\rhysd.actionlint__DefaultSource\actionlint.exe returned exit code: 3
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\actionlint.exe returned exit code: 3
> Installation failed with exit code -1978335187
> 2024-10-03 11:37:18.538 [FAIL] Installer failed security check. Url: https://github.com/rhysd/actionlint/releases/download/v1.7.3/actionlint_1.7.3_windows_386.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 896.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\rhysd.actionlint__DefaultSource\actionlint.exe returned exit code: 3
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\actionlint.exe returned exit code: 3
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Packages\rhysd.actionlint__DefaultSource\actionlint.exe returned exit code: 3
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\actionlint.exe returned exit code: 3

(Automated response - build 896.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
