### PR TITLE
pit-ray.win-vind version 5.0.1

### PR DESCRIPTION
**Pull request by pit-ray**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101425)

### CODE REVIEW

**Comment by Trenly** [comment]
>2023-04-03 08:59:07.515 [FAIL] Installer failed security check. Url: https://github.com/pit-ray/win-vind/releases/download/v5.0.1/setup_win-vind_5.0.1_32bit.exe Result: 0x80004005

**Comment by pit-ray** [comment]
@Trenly 
Thanks for your feedback.

I didn't change the installation way from its previous version, so I am confused to do.
Please let me know how to check defects locally.

Thanks.

**Review by stephengillie — APPROVED** [review]

**Comment by pit-ray** [comment]
@Trenly @stephengillie 
Thanks for your generous support.

**Pull request merged**
