### PR TITLE
Update: RProject.Rtools version 4.3

### LINKED ISSUE #137625: RProject.Rtools
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

I tried to install the winget version of Rtools. The conciludes with an error 404. It appears that there is a newer version of Rtools available at HTTPS://cloud.r-project.org/bin/windows/Rtools/rtools43/files. this is not being dowloaded when executing the winget command.

### Steps to reproduce

winget install -e --id RProject.Rtools results in an 404 error

### Actual behavior

above command results in an 404 error
this because of th source files being different.

### Expected behavior

Rtools being installed

### Environment

```raw
[winget --info]
Windows Package Manager v1.6.3482
Windows: Windows. Desktop v10.0.19045.3930
Package: Microsoft.DesktopAppInstaller v1.21.3482.0
```

### Screenshots and Logs

afbeelding
afbeelding

### PR DESCRIPTION
**Pull request by SpecterShell**
* Resolves: #137625

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137288)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
- Resolve: #137625

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
