### PR TITLE
New version: WHONET.WHONET version 24.6.13

### PR DESCRIPTION
**Pull request by drshtmstry**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/157818)

### CODE REVIEW

**Comment by AClark-WHONET** [comment]
Hi @drshtmstry,

I've already submitted this update last night. Thanks for helping to keep this up to date.

**Comment by drshtmstry** [comment]
> Hi @drshtmstry,
> 
> I've already submitted this update last night. Thanks for helping to keep this up to date.

Sorry, I didn't check for duplicates before submitting. I have also removed WHONET 2023 in this PR.

**Comment by AClark-WHONET** [comment]
Yours was first actually, you're too fast!

**Comment by AClark-WHONET** [comment]
@drshtmstry,

I can take over the winget updates as part of my normal release process going forward so we don't crash into each other again (especially since I might have to release patches in the coming days). Thank you again for helping to set this process up.

**Comment by drshtmstry** [comment]
> @drshtmstry,
> 
> I can take over the winget updates as part of my normal release process going forward so we don't crash into each other again (especially since I might have to release patches in the coming days). Thank you again for helping to set this process up.

This needs to be done once when URL changes (when new version is released like this). Routine updates are automatically submitted by @wingetbot.
@wingetbot regularly check for changes in file hash (sha256) and submits PR for new versions.

**Comment by stephengillie** [comment]
> > @ drshtmstry,
> > I can take over the winget updates as part of my normal release process going forward so we don't crash into each other again (especially since I might have to release patches in the coming days). Thank you again for helping to set this process up.
> 
> This needs to be done once when URL changes (when new version is released like this). Routine updates are automatically submitted by @wingetbot. @wingetbot regularly check for changes in file hash (sha256) and submits PR for new versions.

Let us know if you'd like this behavior to change. I can block the bot updates if you'd like.

**Review by stephengillie — APPROVED** [review]

**Comment by AClark-WHONET** [comment]
I am going to update our release process to no longer use the "vanity URLs" we use presently. We will maintain a persistent "releases" folder going forward on our website with fixed URLs that include the version number (WHONET2024-Setup-x64-v24.6.13.exe for example).

Once we do this @stephengillie, will the wingetbot be able to detect the updates automatically, or should we still be generating and submitting a manifest with each version?

**Comment by drshtmstry** [comment]
> I am going to update our release process to no longer use the "vanity URLs" we use presently. We will maintain a persistent "releases" folder going forward on our website with fixed URLs that include the version number (WHONET2024-Setup-x64-v24.6.13.exe for example).
> 
> Once we do this @stephengillie, will the wingetbot be able to detect the updates automatically, or should we still be generating and submitting a manifest with each version?

wingetbot only detects file hash changes, so it only works for vanity URLs.

**Comment by AClark-WHONET** [comment]
> > I am going to update our release process to no longer use the "vanity URLs" we use presently. We will maintain a persistent "releases" folder going forward on our website with fixed URLs that include the version number (WHONET2024-Setup-x64-v24.6.13.exe for example).
> > Once we do this @stephengillie, will the wingetbot be able to detect the updates automatically, or should we still be generating and submitting a manifest with each version?
> 
> wingetbot only detects file hash changes, so it only works for vanity URLs. Manual submission for versioned URL requires wingetcreate to be implemented in release process like WHONET.AMRIE.

Thanks! I will add this step to my release process, since I think it might be preferable for winget to have a history of versions rather than only the latest in case users have trouble with a particular build.

**Comment by AClark-WHONET** [comment]
Hi @stephengillie, I'm testing out the new release process with persistent URLs, but I am hitting a roadblock when I run `wingetcreate update` on the package. Everything seems to be generated correctly, including the new PackageVersion with the updated value, but I receive an error at the end indicating "Submitting a manifest without any updated changes is not allowed.
Please ensure that the updated manifest you are submitting is different from the existing package."

Is there a setting that needs to be changed as I convert this from the "vanity URLs" over to the persistent URLs?

Thanks

**Pull request merged**
