### PR TITLE
Gyroflow.gyroflow 1.6.0 4 dc60738422 e4017 a4 e2 d6 dffaa53011

### PR DESCRIPTION
**Pull request by jo-chemla**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/197203)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
It appears this package has a dependency on `Microsoft.VCRedist.2015+.x64`. Please add this dependency to the manifest

image

**Comment by stephengillie** [comment]
Manual Validation ended with:
image

Does this package require OpenCL to run? This package isn't in the repo, but is in the MSStore as `9NQPSL29BFFF`.

**Comment by AdrianEddy** [comment]
in general, OpenCL.dll should be provided by the GPU driver, not the application

**Comment by jo-chemla** [comment]
So it should be provided as a `ExternalDependencies` then? But what should be the package listed as a dependency if it dependens on the host GPU?

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/12906
- https://github.com/microsoft/winget-pkgs/issues/107639

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
