### PR TITLE
New package: QuakeWorld.ezQuake version 3.6.2

### LINKED ISSUE #113178: [Package Request]: ezQuake
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://ezquake.com/info/downloads.html
Publisher: QuakeWorld Group
Package Name: ezQuake
Description: A modern QuakeWorld client.
Package Version: 3.6.2
Installer URL: https://github.com/QW-Group/ezquake-source/releases/download/3.6.2/ezquake.exe

### PR DESCRIPTION
**Pull request by CoolPlayLin**
- Resolve #113178

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/113213&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
image

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Standard error:  Exception during executable launch operation System.AggregateException: One or more errors occurred. (The specified executable is not a valid application for this OS platform.)  ---
> System.ComponentModel.Win32Exception (216): The specified executable is not a valid application for this OS platform. 
--- End of stack trace from previous location where exception was thrown ---    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

**Comment by stephengillie** [comment]
image

This message shows despite the dependency being installed.

**Comment by CoolPlayLin** [comment]
It appears this package requires `Microsoft Net Framework`

**Comment by stephengillie** [comment]
Hi @CoolPlayLin,

This installer doesn't seem to respond to installer switches in the expected way. Any /S or /s switch makes it fail silently, and any other switch causes the installer to launch interactively.

**Comment by stephengillie** [comment]
> image
> 
> This message shows despite the dependency being installed.

This persists.

**Pull request closed without merging**
