### PR TITLE
New version: DevToys version 2.0.4.0

### PR DESCRIPTION
**Pull request by veler**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/163331)

### CODE REVIEW

**Comment by veler** [comment]
To anyone: Hi, I'm not seeing what the error is in the pipeline. It says it failed without much details. The installer works on my machine.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-07-16 19:47:09.254 [FAIL] Installer failed security check. Url: https://github.com/DevToys-app/DevToys/releases/download/v2.0.4.0/devtoys_win_x86.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 886.)

**Comment by veler** [comment]
Thanks @stephengillie !

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
