### PR TITLE
AkeoConsulting.Rufus version 3.14.1788

### PR DESCRIPTION
**Pull request by TheGift73**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14610)

### CODE REVIEW

**Comment by KaranKad** [comment]
AkeoConsulting is not correct name for the publisher.

**Comment by TheGift73** [comment]
```
PS C:\Users\Dickie PC> winget install --manifest "C:\Users\Dickie PC\manifests\a\AkeoConsulting\Rufus\3.14.1788"
Found Rufus [AkeoConsulting.Rufus]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://github.com/pbatard/rufus/releases/download/v3.14/rufus-3.14.exe
  ██████████████████████████████  1.11 MB / 1.11 MB
Successfully verified installer hash
Starting package install...
Successfully installed
PS C:\Users\Dickie PC>
```

Ran `winget install --manifest "C:\Users\Dickie PC\manifests\a\AkeoConsulting\Rufus\3.14.1788"` in Powershell and installed fine on my end (except for UAT prompt)

When I ran `winget validate --manifest "C:\Users\Dickie PC\manifests\a\AkeoConsulting\Rufus\3.14.1788"` it succeeded with the following warning:

```
Manifest validation succeeded with warnings.
Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended.
```

This is my first pull request and just trying to assist the community for winget being released/updated for Windows. Noticed that Rufus wasn't on the repository list, so ran the `winget install wingetcreate` followed by `wingetcreate new https://github.com/pbatard/rufus/releases/download/v3.14/rufus-3.14.exe` to get it added so other users can install easily via winget.

@KaranKad Got the publishers name for Rufus from the exe properties under the Digital Signatures tab

If I have errored in this, let me know so I know for the future.

**Comment by KaranKad** [comment]
Rufus exists at [manifests/r/Rufus/Rufus](https://github.com/microsoft/winget-pkgs/tree/master/manifests/r/Rufus/Rufus). AkeoConsulting is just name of the company that the application is licensed under.

**Comment by TheGift73** [comment]
@KaranKad Ah, sorry, I should have check correctly.

Had an email back from Pete Batard after letting him know that I just did a pull request for winget install with the following:

"Hi Richard,

That sounds good, but I am not planning to get involved with Winget
packages at the moment, so I will leave it to users like you to sort the
specifics of creating a package.

Regards,

/Pete"

So will leave the correct specifics of a correct implementation of this to others here as I guess I did mine incorrectly.

Thank you though for the reply and I'll make sure to check for next time.

**Comment by KaranKad** [comment]
Yeah no problem, thanks for contributing.

**Comment by OfficialEsco** [comment]
@TheGift73
> This is my first pull request and just trying to assist the community for winget being released/updated for Windows. Noticed that Rufus wasn't on the repository list

What repository list?
image

The Rufus exe is not a installer, its just a portable program so it requires the appx which installs as a Windows Store app.

**Pull request closed without merging**
