### PR TITLE
New package: MinnowIT.Foldr version 3.1.0

### PR DESCRIPTION
**Pull request by sean-minnow**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/171452)

### CODE REVIEW

**Comment by sean-minnow** [comment]
@microsoft-github-policy-service agree company=“Minnow IT"

**Comment by sean-minnow** [comment]
@microsoft-github-policy-service agree company=“Minnow IT”

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-09-03 11:33:44.252 [CLI ] ShellExecute installer failed: 1603
> INFO   : [09/03/2024 11:33:37:937] [CheckFX                                 ]: Allocating space...
> INFO   : [09/03/2024 11:33:37:953] [CheckFX                                 ]: Allocating space...
> Action start 11:33:38: AllocateRegistrySpace.
> Action ended 11:33:38: AllocateRegistrySpace. Return value 1.
> CustomAction +_BCE950AB701548C3915A47FE0297FC36 returned actual error code -2147024770 (note this may not be 100% accurate if translation happened inside sandbox)
> MSI (s) (7C:30) [11:33:42:749]: Product: Foldr -- Error 1904. Module C:\Program Files\Minnow IT\Foldr\OverlayIconsAmber.dll failed to register.  HRESULT -2147024770.  Contact your support personnel.
> Error 1904. Module C:\Program Files\Minnow IT\Foldr\OverlayIconsAmber.dll failed to register.  HRESULT -2147024770.  Contact your support personnel.
> Property(S): ErrorDialog = ErrorDialog
> Property(S): OutOfDiskSpace = 0
> Property(S): OutOfNoRbDiskSpace = 0
> Property(S): PrimaryVolumeSpaceAvailable = 0
> Property(S): PrimaryVolumeSpaceRequired = 0
> Property(S): PrimaryVolumeSpaceRemaining = 0
> MSI (s) (7C:30) [11:33:44:046]: Product: Foldr -- Installation failed.

Automated error analysis suggests -1978335226 may mean Running ShellExecute failed

Automated error analysis suggests 1603 may mean Install successful but system restart may be required. Should this be add as an `InstallerSuccessCode` or similar?

(Automated response - build 894.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 12:13:00 PM: Detected 7 WinGet errors: 12:13:00 PM: 
> 2024-09-03 12:13:00.022 [CLI ] ShellExecute installer failed: 1603 12:13:00 PM: CustomAction +_BCE950AB701548C3915A47FE0297FC36 returned actual error code -2147024770 (note this may not be 100% accurate if translation happened inside sandbox) 12:13:00 PM: MSI (s) (C0:80) [12:12:59:349]: Product: Foldr -- Error 1904. Module C:\Program Files\Minnow IT\Foldr\OverlayIconsAmber.dll failed to register.  HRESULT -2147024770.  Contact your support personnel. 12:13:00 PM: Error 1904. Module C:\Program Files\Minnow IT\Foldr\OverlayIconsAmber.dll failed to register.  HRESULT -2147024770.  Contact your support personnel. 12:13:00 PM: Property(S): ErrorDialog = ErrorDialog 12:13:00 PM: MSI (s) (C0:80) [12:12:59:802]: Product: Foldr -- Installation failed. 12:13:00 PM: MSI (s) (C0:80) [12:12:59:802]: Windows Installer installed the product. Product Name: Foldr. Product Version: 3.1.0. Product Language: 1033. Manufacturer: Minnow IT. Installation success or error status: 1603. 12:13:00 PM: Detected 1 Manual Dependency: 12:13:00 PM: 12:13:00 PM: Detected 0 PowerShell errors: 12:13:00 PM: Detected 1 Application Log errors: 12:13:00 PM: Product: Foldr -- Error 1904. Module C:\Program Files\Minnow IT\Foldr\OverlayIconsAmber.dll failed to register.  HRESULT -2147024770.  Contact your support personnel.

(Automated response - build 894.)

**Comment by sean-minnow** [comment]
Closed this PR as a new one has been raised which supersedes it: https://github.com/microsoft/winget-pkgs/pull/171524

**Pull request closed without merging**
