### PR TITLE
New version: TorProject.TorBrowser version 11.0.4

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/40730)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
```
Installer https://dist.torproject.org/torbrowser/11.0.4/torbrowser-install-11.0.4_en-US.exe
Result: Download Failed
```

**Review by ItzLevvie — APPROVED** [review]

**Comment by Yolgie** [comment]
all downloads in the manifest work for me, can the automatic check be restarted?

**Comment by OfficialEsco** [comment]
The error is most likely caused by the Azure Pipeline getting blocked by visiting the website too much, one download will timeout every time

**Comment by OfficialEsco** [comment]
As you can see ¯\\\_(ツ)_/¯
```
-----------------------------------------------------
Installer https://dist.torproject.org/torbrowser/11.0.4/torbrowser-install-win64-11.0.4_en-US.exe
Result: Download Failed
-----------------------------------------------------
Installer https://dist.torproject.org/torbrowser/11.0.4/torbrowser-install-11.0.4_de.exe
Result: Download Failed
-----------------------------------------------------
1/20/2022 7:49:51 PM
Status: Completed
##[error] Installer https://dist.torproject.org/torbrowser/11.0.4/torbrowser-install-win64-11.0.4_en-US.exe
##[error] Result: Failed
##vso[task.logissue type=error] Error occurred while downloading installer from https://dist.torproject.org/torbrowser/11.0.4/torbrowser-install-win64-11.0.4_en-US.exe. 0x80072EE2.
Error information: 
Http Response: OK
Http Reason Phrase: OK

1/20/2022 7:49:51 PM
Status: Completed
##[error] Installer https://dist.torproject.org/torbrowser/11.0.4/torbrowser-install-11.0.4_de.exe
##[error] Result: Failed
##vso[task.logissue type=error] Error occurred while downloading installer from https://dist.torproject.org/torbrowser/11.0.4/torbrowser-install-11.0.4_de.exe. 0x80072EE2.
Error information: 
Http Response: OK
Http Reason Phrase: OK
```

**Comment by Yolgie** [comment]
hmmm, I can't imagine this is the only software affected, what would have to be changed to fix this, maybe update the pipeline to not download everything at the same time but stagger it a little? If the pipeline takes a few minutes longer for manifests with many links that would not be a big problem right?

**Comment by Yolgie** [comment]
Created a discussion here: https://github.com/microsoft/winget-pkgs/discussions/41662 maybe you have other ideas how to solve this :)

**Comment by OfficialEsco** [comment]
> Created a discussion here: #41662 maybe you have other ideas how to solve this :)

Already saw it and upvoted it :)
Waiting for MS to reply since the bots are closed source, calibre might have a similar issue, however over multiple manifests

**Pull request merged**
