### PR TITLE
New package: RareWares.FLAC version 1.4.3

### LINKED ISSUE #155263: [Package Request]: FLAC (RareWares Builds)
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.rarewares.org/lossless.php
Publisher: RareWares
Package Name: FLAC
Description: Free Lossless Audio Codec (FLAC) command-line encoder and decoder.
Package Version: 1.4.3
Installer URL:
- https://www.rarewares.org/files/lossless/flac-1.4.3-x64-20240525.zip
- https://www.rarewares.org/files/lossless/flac-1.4.3-x86-nonXP-20240525.zip

I have already raised a PR for this package at https://github.com/microsoft/winget-pkgs/pull/155261

This issue is related to https://github.com/microsoft/winget-pkgs/issues/151382 although this issue tracks the statically linked builds provided by RareWares which can work with winget today. Meanwhile, the official builds require a DLL at runtime and are blocked by https://github.com/microsoft/winget-cli/issues/2711.

I think it's best to keep the original issue open so we can build a package of the official Xhip binaries when the required feature is implemented.

These RareWare builds have recently been improved after some discussions I had with John Edwards who runs the site. The prior builds on the site were compiled with the Intel 19 compiler and the non-AVX2 build was quite a lot slower than the official build. The new builds (used in this package manifest) are compiled with GCC and have identical if not better performance than the official Xhip builds.

I have specifically selected the following builds:
- **x86**: The non-XP build is compiled with GCC and is faster than the build that provides Windows XP compatibility. Since winget is only supported on Windows 10 onward, I didn't think Windows XP compatibility was a concern. 😄 
- **x64**: I chose the regular build which doesn't require an AVX2-compatible CPU. The reason is that in benchmarks performed by both John and I, the performance of both builds is comparable and thus I chose the more compatible build. The official Xhip builds also do not have a hard requirement on an AVX2-compatible processor either so this made the most sense.

### PR DESCRIPTION
**Pull request by fgimian**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

Resolves #155263

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/155261)

### CODE REVIEW

**Comment by fgimian** [comment]
Resolves #155263

**Comment by stephengillie** [comment]
Verify: 
image

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Looking closer, I may have made an error in approving this. RareWares appears to be a rehoster, with the tag line:

> Providing hard-to-find pieces of software since 2001-10-21

It appears that the official developer is https://xiph.org/flac/

**Comment by BiosPlus** [comment]
> Looking closer, I may have made an error in approving this. RareWares appears to be a rehoster, with the tag line:
> 
> > Providing hard-to-find pieces of software since 2001-10-21
> 
> It appears that the official developer is https://xiph.org/flac/

I think it should be fine no?

FLAC is FOSS and these are just builds of it done by third parties since the original source may rely on external DLLs packaged within the zip. Similar to how FFMPEG for Windows tends to be built by several different parties each with their own processes to optimize for certain CPU architectures.

**Comment by fgimian** [comment]
Yeah RareWares is a site which hosts their own statically linked versions of various open source tools. The intention was to add the builds from Xhip once runtime DLLs were supported.

I also created the RareWares.LAME package FYI.

**Comment by fgimian** [comment]
I see the LAME package was also removed https://github.com/microsoft/winget-pkgs/pull/155441 now 😢

**Comment by stephengillie** [comment]
FLAC's download link leads here: https://ftp.osuosl.org/pub/xiph/releases/flac/ 
- ZIP files are provided for Windows users. This package should be readded with these links and publisher.

**Comment by fgimian** [comment]
> FLAC's download link leads here: https://ftp.osuosl.org/pub/xiph/releases/flac/
> 
>     * ZIP files are provided for Windows users. This package should be readded with these links and publisher.

The problem with these builds is that they require a DLL at runtime, they're not statically linked like the RareWares builds. Such builds are blocked by https://github.com/microsoft/winget-cli/issues/2711.

Please also see https://github.com/microsoft/winget-pkgs/issues/151382 which was the original request for the FLAC package.

**Pull request merged**
