### PR TITLE
Microsoft.VisualStudio.2022.Community version 17.6.0

### PR DESCRIPTION
**Pull request by edwardskrod**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/106933)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @edwardskrod,

This package installed normally but errored when launched:
> Activation context generation failed for "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe". Dependent Assembly Automation,processorArchitecture="&#x2a;",type="win32",version="1.0.0.0" could not be found. Please use sxstrace.exe for detailed diagnosis.

Is this the correct application to validate?

**Review by jedieaston — APPROVED** [review]

**Comment by edwardskrod** [comment]
> Hi @edwardskrod,
> 
> This package installed normally but errored when launched:
> 
> > Activation context generation failed for "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe". Dependent Assembly Automation,processorArchitecture="*",type="win32",version="1.0.0.0" could not be found. Please use sxstrace.exe for detailed diagnosis.
> 
> Is this the correct application to validate?

Yes.  This looks correct to me.

> Hi @edwardskrod,
> 
> This package installed normally but errored when launched:
> 
> > Activation context generation failed for "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe". Dependent Assembly Automation,processorArchitecture="*",type="win32",version="1.0.0.0" could not be found. Please use sxstrace.exe for detailed diagnosis.
> 
> Is this the correct application to validate?

I don't think so.  The application should be installed to a different location on disk - more than likely the default for the Community sku:

"C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.com"

Is the test installing the app to the Enterprise directory?  If so, then yes, that would be the correct location.

I tested the InstallerUri in the manifest:  https://download.visualstudio.microsoft.com/download/pr/12bf87fa-ff4f-4b5d-9fb2-2b1c1b59eb10/019e9c92dc19bfc056bc294ee40f4b87f597d4bded4bb3395cadb0c2ec32db09/vs_Community.exe

I'm able to successfully download, install, and run the Community edition of VS without error.

Any other ideas?  We need to be able to install this version of the Community edition via WinGet for a Build keynote.

**Comment by edwardskrod** [comment]
I ran winget install --manifest locally.

The app downloads and installs Visual Studio as expected to C:\Program Files\Microsoft Visual Studio\2022\Community\

The VS process is at "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\devenv.exe"

It opens locally for me fine.

**Pull request merged**
