### PR TITLE
caoyue.WindowResizer version 1.0.1

### PR DESCRIPTION
**Pull request by KarbitsCode**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/170868)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with:
> Application: WindowResizer.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.IO.FileNotFoundException    at WindowResizer.TrayContext+<Update>d__5.MoveNext()    at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[WindowResizer.TrayContext+<Update>d__5, WindowResizer, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null]](<Update>d__5 ByRef)    at WindowResizer.TrayContext.Update()    at WindowResizer.Program.Main()  
> Faulting application name: WindowResizer.exe, version: 1.0.1.0, time stamp: 0x61cd5930 
> Faulting module name: KERNELBASE.dll, version: 10.0.19041.1202, time stamp: 0xc9db1934 Exception code: 0xe0434352 Fault offset: 0x0000000000034f99 
> Faulting process id: 0x2fc 
> Faulting application start time: 0x01dafe25c4de83d4 
> Faulting application path: C:\Users\User\AppData\Local\WindowResizer\app-1.0.1\WindowResizer.exe 
> Faulting module path: C:\Windows\System32\KERNELBASE.dll Report Id: f76b1af5-e4e0-40f4-a9e3-dbadeee814ed 
> Faulting package full name:  
> Faulting package-relative application ID: 

(Automated response - build 894.)

**Comment by KarbitsCode** [comment]
> Clicking "Open Setup Log" just closes the window.

This was a known bug in [Squirrel Installer](https://github.com/Squirrel/Squirrel.Windows), but they didn't fix that yet.
Usually the setup log located at %localappdata%\SquirrelTemp, could you please check the setup log located in that directory?

**Review by stephengillie — APPROVED** [review]

**Comment by KarbitsCode** [comment]
> The window is not resizable, and there seems to be some text peeking up from the lower left.

Screenshot 2024-09-10 170652

**Pull request merged**
