### PR TITLE
WindscribeLimited.Windscribe version 2.0.2.10

### PR DESCRIPTION
**Pull request by Masamune3210**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/27226)

### CODE REVIEW

**Comment by quhxl** [comment]
It was removed in #19480 because there were problems with the installation.

**Comment by Masamune3210** [comment]
I see, going to try to reproduce with my own VM and if I cant figure out the issue Ill close

**Comment by Masamune3210** [comment]
Ok, so the installer actually works perfectly fine if you remove the /s flag. Is it required for the installer to be silent? If so I can talk to support and see about the silent flag, if not can just remove the /s and should be good at least according to my Win11 VM

**Comment by ItzLevvie** [comment]
> Is it required for the installer to be silent? If so I can talk to support and see about the silent flag, if not can just remove the /s and should be good at least according to my Win11 VM

Yes, it is required (unattended = installs the application without requiring the user's attention).

Right now, I can see this:
image

**Comment by Masamune3210** [comment]
Ok, ill talk to support and see what silent support if any the installer has

**Comment by Masamune3210** [comment]
Got referred to making a feedback request for silent support, so I'm going to close this until I get a firmitive answer

**Comment by Masamune3210** [comment]
Good news on this, should be adding it to the database soon!

image

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
image

**Comment by Masamune3210** [comment]
Just adding Dependencies

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
You can set the PR to draft and wait until dependency support is added.

**Pull request closed without merging**
