### PR TITLE
Add Postman 9.22.2

### PR DESCRIPTION
**Pull request by al-lac**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/63987)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Comment by al-lac** [comment]
Yeah looks like the installer is not available via https://dl.pstmn.io/download/version/9.21.2/win64. 

Seems like it is currently only available from here which is odd: https://dl.pstmn.io/download/latest/win64

**Comment by al-lac** [comment]
So 9.21.2 was not available because it was only a UI release. 
The latest desktop platform release can be found here: https://dl.pstmn.io/api/version/latest

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
