### PR TITLE
New package: peanut996.CloudflareWarpSpeedTest version 1.1.4

### PR DESCRIPTION
**Pull request by puzige**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/123308)

### CODE REVIEW

**Comment by peanut996** [comment]
> @microsoft-github-policy-service agre

@microsoft-github-policy-service agre

**Comment by peanut996** [comment]
> @peanut996 the command you issued was incorrect. Please try again.
> 
> Examples are:
> 
> ```
> @microsoft-github-policy-service agree
> ```
> 
> and
> 
> ```
> @microsoft-github-policy-service agree company="your company"
> ```

```
@microsoft-github-policy-service agree
```

**Comment by peanut996** [comment]
@microsoft-github-policy-service agree

**Comment by peanut996** [comment]
> @peanut996 please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 2:16:22 PM:  > 2023-10-23 14:16:21.094 [FAIL] Installer failed security check. Url: https://github.com/peanut996/CloudflareWarpSpeedTest/releases/download/v1.1.4/CloudflareWarpSpeedTest-v1.1.4-windows-amd64.zip Result: 0x80004005 

This is similar to a Defender error. We can retry tomorrow.

**Comment by peanut996** [comment]
> Manual Validation ended with:
> 
> > 2:16:22 PM:  > 2023-10-23 14:16:21.094 [FAIL] Installer failed security check. Url: https://github.com/peanut996/CloudflareWarpSpeedTest/releases/download/v1.1.4/CloudflareWarpSpeedTest-v1.1.4-windows-amd64.zip Result: 0x80004005
> 
> This is similar to a Defender error. It might be a false positive, and we can retry tomorrow.

thank you in advance

**Comment by stephengillie** [comment]
Hi @peanut996,

Good news - the security check passed. 
The application seems like it's missing characters - is it meant to be run with a certain localization or certain language files? Or are the squares with question marks expected? 

image

**Comment by peanut996** [comment]
> Hi @peanut996,
> 
> 
> 
> Good news - the security check passed. 
> 
> The application seems like it's missing characters - is it meant to be run with a certain localization or certain language files? Or are the squares with question marks expected? 
> 
> 
> 
> image
> 
> 

thanks for your feedback！ 
all these character is Chinese, it will display normally in UTF-8 encoding

image

And I ll replace it by English next version!

**Comment by stephengillie** [comment]
> > Hi @peanut996,
> > Good news - the security check passed.
> > The application seems like it's missing characters - is it meant to be run with a certain localization or certain language files? Or are the squares with question marks expected?
> > image
> 
> thanks for your feedback！ all these character is Chinese, it will display normally in UTF-8 encoding
> 
> image
> 
> And I ll replace it by English next version!

Ah, this was what I was hoping. Thanks!

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
