### PR TITLE
Update manifest: Microsoft.LogParser version 2.2.10

### LINKED ISSUE #161664: [Update Request]: Microsoft.LogParser
### What type of update are you requesting?

A new locale, architecture, or installer type of an existing version

### Current Package Identifier

Microsoft.LogParser

### Package Version

2.2.10

### Please describe the changes you would like to see

Please add the `scope: machine` and `scope: user` to the existing yaml file.

### PR DESCRIPTION
**Pull request by Dragon1573**
## Details

- Add `Scope` parameter of this package

## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- Related #161664

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161747)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
This won't work, as Wix installers won't install in the user scope - the ARP entries will always be under HKLM so WinGet will always detect it as Machine scope. It would be better to just remove the scope specification

**Comment by Dragon1573** [comment]
Okay ... ❤️

But is there any other ways to solve https://github.com/microsoft/winget-pkgs/issues/161664#issue-2392330389?

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Close with reason: https://github.com/microsoft/winget-pkgs/pull/161747#pullrequestreview-2163510064

**Pull request closed without merging**
