### PR TITLE
Narazaka.vrc-tail version 1.3.0

### PR DESCRIPTION
**Pull request by Narazaka**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/187713)

### CODE REVIEW

**Comment by Narazaka** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Narazaka.vrc-tail__DefaultSource\vrc-tail.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\vrc-tail.exe returned exit code: 1

(Automated response - build 897.)

**Comment by Narazaka** [comment]
vrc-tail.exe is an application for environments with VRChat applications. So it is expected behavior that errors occur in environments without VRChat.

**Comment by stephengillie** [comment]
Hi @Narazaka,

I'm very sorry to have let this PR slip through the process. A non-zero exit code is expected for most CLI applications, since our pipelines were built to expect Windows Forms. I meant to approve and merge this PR. But it became hidden in one of many browser windows and I lost track of it. If you're willing to reopen this PR, I would be happy to merge it.

**Pull request closed without merging**
