### PR TITLE
New version: XunLei.xunlei 11.3.1.1820

### PR DESCRIPTION
**Pull request by Voya9e**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/29251)

### CODE REVIEW

**Comment by jedieaston** [comment]
You probably need to clean up your local branch. Try merging the master branch from this repo.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/29251#issuecomment-932944037

**Comment by Meng5in** [comment]
> You probably need to clean up your local branch. Try merging the master branch from this repo.

I have tried, it doesn't work.

**Comment by Meng5in** [comment]
> > You probably need to clean up your local branch. Try merging the master branch from this repo.
> 
> I have tried, it doesn't work.

or it worked?😶

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
It will be better to reset your branch and then make a new branch from master.

**Comment by Meng5in** [comment]
> It will be better to reset your branch and then make a new branch from master.

🙌🙌🙌

**Comment by Meng5in** [comment]
> It will be better to reset your branch and then make a new branch from master.

I re-forked then it worked. That's not a good solution, but useful🥲

**Pull request closed without merging**
