### PR TITLE
New version: SomePythonThings.WingetUIStore version 3.0.1

### PR DESCRIPTION
**Pull request by marticliment**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/144886)

### CODE REVIEW

**Comment by marticliment** [comment]
This is the same issue as always

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code 1

(Automated response - build 870.)

**Comment by marticliment** [comment]
it always fails

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
