### PR TITLE
New package: HiroshibaKazuyuki.VOICEVOX version 0.14.10

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132085)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is bot account and belongs to CoolPlayLin. Any issue should call him up instead of assigning to this account. He has the write permission of this account's fork so that he can resolve the issue directly.

>[!important]
>Please recheck these Pull Request carefully before merging. If it is a incorrect-removing Pull Request and the URLs don't have any issue while manual checking, please close this Pull Request directly(It's best to let CoolPlayLin know).

Have a good day!

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification. It has the write permission of this account's fork so that it can resolve the issue directly.

>[!important]
>Please recheck these Pull Request carefully before merging. If it is a incorrect-removing Pull Request and the URLs don't have any issue while manual checking, please close this Pull Request directly(It's best to let Exorcism0666 know).

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
>  Manifest Error: Duplicate installer entry found.

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

From the URLs, these appear to be CPU, CUDA, and Web versions respectively. But they're all given the same identifier of just `Architecture: x86`, so the package manager can't tell them apart.

**Comment by Exorcism0666** [comment]
@stephengillie i think so!

**Comment by Exorcism0666** [comment]
@stephengillie what should I do now, maintain this pull request, or close it to create a new one?

**Pull request closed without merging**
