### PR TITLE
New package: cmlanche.lightningvine version 2.5.5+255

### PR DESCRIPTION
**Pull request by SpecterShell**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/182763)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @SpecterShell,

The `PackageUrl` seems to lead to `https://www.123684.com/s/cXByVv-mlfk`, which appears to require login to download. Is there another `PackageUrl` or location where this `InstallerUrl` is available?

**Comment by SpecterShell** [comment]
> Hi @SpecterShell,
> 
> The `PackageUrl` seems to lead to `https://www.123684.com/s/cXByVv-mlfk`, which appears to require login to download. Is there another `PackageUrl` or location where this `InstallerUrl` is available?
> 
> Edit: I missed this in my browser's download section: image It seems that the file was blocked locally for security reasons, when I believed it was blocked remotely for authentication reasons.

The update source: https://github.com/cmlanche/lightningvine-docs/blob/main/docs/public/appcast.xml

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
> The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.

image

Hi @SpecterShell,

It seems that this PR changes an unrelated file.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2147012867
> 2024-10-15 19:15:02.368 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(267)\WindowsPackageManager.dll!00007FFBF533A384: (caller: 00007FFBF533AD01) Exception(1) tid(1e98) 80D02002 
> 2024-10-15 19:15:23.917 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FFBF533395E: (caller: 00007FFBF5335C49) Exception(2) tid(1e98) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-10-15 19:15:23.926 [CLI ] Failed to download, waiting a bit and retry. Url: https://sdtpub.s3.bitiful.net/publish/2.5.5/sdt-2.5.5-windows.exe
> 2024-10-15 19:16:24.595 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(267)\WindowsPackageManager.dll!00007FFBF533A384: (caller: 00007FFBF533AD01) Exception(3) tid(1e98) 80D02002 
> 2024-10-15 19:16:45.860 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FFBF533395E: (caller: 00007FFBF5335C49) Exception(4) tid(1e98) 80072EFD     Msg:[InternetOpenUrl() failed.] 

Automated error analysis suggests -2147012867 may mean Network or Firewall Error.

Automated error analysis suggests 80072EFD may mean The operation timed out.

Automated error analysis suggests 80D02002 may mean The operation timed out.

(Automated response - build 897.)

**Comment by stephengillie** [comment]
> The update source: https://github.com/cmlanche/lightningvine-docs/blob/main/docs/public/appcast.xml

Thank you - this PR passes the `Validation-Domain` check, if it reappears.

**Comment by stephengillie** [comment]
URL: https://sdtpub.s3.bitiful.net/publish/2.5.5/sdt-2.5.5-windows.exe 
Status Code: 200

(Automated message - build 897)

**Comment by stephengillie** [comment]
Verify:
image
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
