### PR TITLE
New package: Thwani.Uhm version 0.1.3

### PR DESCRIPTION
**Pull request by Thwani47**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/157567)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Thwani.Uhm__DefaultSource\uhm.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\uhm.exe returned exit code: 1

(Automated response - build 885.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-06-12 19:28:58.778 [FAIL] Installer failed security check. Url: https://github.com/Thwani47/uhm/releases/download/v0.1.3/uhm_0.1.3_windows_amd64.exe Result: 0x80004005

(Automated response - build 885.)

**Comment by Thwani47** [comment]
Hi @stephengillie, can you please help clarify what caused the security check failure?

The initial run passed the security check, and I closed the PR by mistake, I opened it again and got the validatoin-executable-error tag

thanks

**Comment by Thwani47** [comment]
Hi @stephengillie 

Thanks for your response. This is a new package and this is the first PR submitted for it. 

Do you reckon closing the PR and creating a new one might help?

**Comment by stephengillie** [comment]
Verify:
image

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
> Hi @ stephengillie
> 
> Thanks for your response. This is a new package and this is the first PR submitted for it.
> 
> Do you reckon closing the PR and creating a new one might help?

I misunderstood, moving too fast, sorry. My VMs must have had an old Defender definition version.

**Pull request merged**
