### PR TITLE
New version: Microsoft.Skype version 8.123 (8.123.0.203)

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#6439](https://github.com/SpecterShell/Dumplings/actions/runs/9838426816).

<details>

<summary>Log</summary>

````
Updated: 8.122.0.205 → 8.123.0.203
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161932)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
