### PR TITLE
Remove new manifest labels on changes pushed

### PR DESCRIPTION
**Pull request by mdanish-kh**
cc @Trenly @denelon

These don't appear to get auto-removed by wingetbot. See https://github.com/microsoft/winget-pkgs/pull/139070

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/139076)

### CODE REVIEW

**Review by Trenly — APPROVED** [review]

**Comment by stephengillie** [comment]
[Policy] Force Merge

**Comment by stephengillie** [comment]
[Policy] Force-Merge

**Comment by stephengillie** [comment]
[Policy] Manually-Validated

**Comment by stephengillie** [comment]
[Policy] Force Merge

**Comment by Trenly** [comment]
Hmm. Very strange

**Review by Trenly — APPROVED** [review]

**Comment by Trenly** [comment]
[Policy] Reset Feedback

**Review by Trenly — APPROVED** [review]

**Pull request merged**
