### PR TITLE
New version: EnderbytePrograms.PyinstallerHelper version 1.6

### PR DESCRIPTION
**Pull request by Enderbyte09**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/156235)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 882.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-06-02 11:54:39.813 [FAIL] Installer failed security check. Url: https://github.com/Enderbyte-Programs/PyinstallerHelper/releases/download/v1.6/pyinstallerhelper-1.6-setup.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 883.)

**Comment by Enderbyte09** [comment]
Hello, The installer is working properly with no input, other than the obligatory "THIS IS A DANGEROUS UNSIGNED APP" warning. Should I try resubmitting?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-06-03 17:31:34.829 [FAIL] Installer failed security check. Url: https://github.com/Enderbyte-Programs/PyinstallerHelper/releases/download/v1.6/pyinstallerhelper-1.6-setup.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 883.)

**Comment by stephengillie** [comment]
> Hello, The installer is working properly with no input, other than the obligatory "THIS IS A DANGEROUS UNSIGNED APP" warning. Should I try resubmitting?

Hi @Enderbyte09,

Currently, this PR is waiting for the package to pass a Defender scan. Unfortunately, some packages linger in this state for an extended duration. I haven't worked with anyone on Defender teams, so I'm not sure, but I've heard there might be other means to expedite this process, such as submitting a false positive report.

**Comment by Enderbyte09** [comment]
I'll go submit it to Defender, along with v1.7 (I hoped that by writing a new update, the error would magically go away because the EXE changed, it didn't)....

**Comment by Enderbyte09** [comment]
Hello. Should I assume this version has been rejected (and go write some more updates and submit it again later)?

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/pull/156512#issuecomment-2159430993

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
