### PR TITLE
New version: Google.AndroidStudio version 2023.2.1.24

### PR DESCRIPTION
**Pull request by OfficialEsco**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/145289)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-03-19T21:33:18.4174061Z ##[error] Manifest Error: DisplayVersion declared in the manifest has overlap with existing DisplayVersion range in the index. Existing DisplayVersion range in index:  [ [2023.2, 2023.2]]

(Automated response - build 870.)

**Comment by OfficialEsco** [comment]
```
Enter a pull request number: 145289

Manifest validation succeeded.
Found Android Studio [Google.AndroidStudio] Version 2023.2.1.24
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://redirector.gvt1.com/edgedl/android/studio/install/2023.2.1.24/android-studio-2023.2.1.24-windows.exe
  ██████████████████████████████  1.07 GB / 1.07 GB
Successfully verified installer hash
Starting package install...
Successfully installed

Name          : Android Studio
Publisher     : Google LLC
Version       : 2023.2
ProductCode   : Android Studio
Registry Path : Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Android Studio
Uninstall     : winget uninstall --id "Android Studio"

Press any key to continue . . .
```
image

**Comment by stephengillie** [comment]
This manifest has the same `DisplayVersion` as the [previous version 2023.2.1.23](https://github.com/microsoft/winget-pkgs/pull/141805/files): `"2023.2"`.

**Comment by OfficialEsco** [comment]
?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-03-21T18:35:41.8273760Z ##[error] Manifest Error: DisplayVersion declared in the manifest has overlap with existing DisplayVersion range in the index. Existing DisplayVersion range in index:  [ [2023.2, 2023.2]]

(Automated response - build 872.)

**Comment by OfficialEsco** [comment]
cba

**Pull request closed without merging**
