### PR TITLE
New package: YannHamon.kubeconform version 0.6.1

### PR DESCRIPTION
**Pull request by mloskot**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101691)

### CODE REVIEW

**Comment by stephengillie** [comment]
This package is expecting data:
```
2023/04/06 09:19:46 failing to read data from stdin
```

**Comment by stephengillie** [comment]
I'm not able to find the cause for this error. It installs and runs normally on a Windows 11 VM.

**Comment by mloskot** [comment]
I have also installed it on Windows 11 Pro fine using `winget install --manifest <path>` just fine:

```
$ which kubeconform
/c/Users/mateuszl/AppData/Local/Microsoft/WinGet/Links/kubeconform

$ kubeconform -v
v0.6.1
```

**Review by Trenly — APPROVED** [review]

**Pull request merged**
