### PR TITLE
New version: MikeFarah.yq version 4.33.2

### PR DESCRIPTION
**Pull request by Okeanos**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101324)

### CODE REVIEW

**Comment by Okeanos** [comment]
I have no idea what's broken here 🤷‍♂️

Screenshot 2023-04-01 at 18 12 47

Screenshot 2023-04-01 at 18 12 59

**Comment by stephengillie** [comment]
> I have no idea what's broken here 🤷‍♂️

Hi @Okeanos,

Installing in a VM ended with this result:
> 2023-04-03 10:23:40.331 [FAIL] Installer failed security check. Url: https://github.com/mikefarah/yq/releases/download/v4.33.2/yq_windows_amd64.exe Result: 0x80004005

This is despite having set the switch:`--ignore-local-archive-malware-scan`

**Comment by Trenly** [comment]
> This is despite having set the switch:`--ignore-local-archive-malware-scan`

That specific check is a different check than the local archive malware check. The "failed security check" is usually defender / smartscreen flagging the URL as an unknown / potentially malicious URL before the download ever completes

**Comment by Okeanos** [comment]
Okay, I have no idea why this would happen? This is, as best as I can tell, the official and correct release URL pointing at a Github.com release item.

**Comment by mloskot** [comment]
FYA, newer bugfix release is out https://github.com/mikefarah/yq/releases/tag/v4.33.3, so may be worth to update this PR.

p.s. Thanks for this update @Okeanos

**Comment by Okeanos** [comment]
> FYA, newer bugfix release is out https://github.com/mikefarah/yq/releases/tag/v4.33.3, so may be worth to update this PR.
> 
> p.s. Thanks for this update @Okeanos

Feel free to create a PR for that … not sure I have the time to do so (and deal with the errors & feedback loop).

**Comment by mloskot** [comment]
Reminder, this PR can be closed w/o merging. See https://github.com/microsoft/winget-pkgs/pull/101324#issuecomment-1507440147

**Comment by ItzLevvie** [comment]
Close with reason: See above;

**Pull request closed without merging**
