### PR TITLE
Move NewBreedSoftware.TuxPaintStamps 2018.09.01 to NewBreedSoftware.TuxPaint.Stamps 2018.09.01

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
Pull Request created using **Trenly**'s script

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/31245)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
image

EDIT: Ah I remember this app, I made a PR for it back when automation for validation didn't exist. It should probably be removed since Tux Paint Stamps requires Tux Paint as dependency, unless there's switches to bypass this prompt or message.

**Review by ItzLevvie — APPROVED** [review]

**Comment by vedantmgoyal2009** [comment]
@denelon "Blocking-Issue" label was removed when I committed new changes. Please label it again. 

Also, is there

**Comment by denelon** [comment]
Dependency support is still experimental. It's likely to be a long tail feature taking several iterations to improve to the point we release it as a stable feature.

**Comment by vedantmgoyal2009** [comment]
Not again...

**Comment by denelon** [comment]
Is this an install time dependency or just a run time dependency?

**Comment by vedantmgoyal2009** [comment]
I don't know about that, but here is the screenshot posted by @Itzlevvie.

https://github.com/microsoft/winget-pkgs/pull/31245#pullrequestreview-787509064

**Pull request closed without merging**
