### PR TITLE
New version: WasmEdge.WasmEdge version 0.11.2

### PR DESCRIPTION
**Pull request by abhinandanudupa**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/112750&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
Is the same dependency needed here? 
- https://github.com/microsoft/winget-pkgs/pull/112747#issuecomment-1645904821

**Comment by ItzLevvie** [comment]
[Policy] Dependencies

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
