### PR TITLE
Submitting MCXStudio version 0.9.8.yaml

### PR DESCRIPTION
**Pull request by fangq**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [ ] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2398)

### CODE REVIEW

**Comment by fangq** [comment]
My first winget manifest submission - `winget validate` works fine, but `winget install -m` gives me an "access is denied" error and the below printed messages:
```
PS C:\Users\cotiadmin\Downloads\winget-pkgs\manifests\COTI\MCXStudio> winget install -m .\0.9.8.yaml
Found MCX Studio [coti.mcxstudio]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading http://mcx.space/nightly/release/v2020.alpha/MCXStudio-v2020_alpha-installer.exe
  ██████████████████████████████  21.6 MB / 21.6 MB
Successfully verified installer hash
Installing ...
Installer failed with exit code: 1
PS C:\Users\cotiadmin\Downloads\winget-pkgs\manifests\COTI\MCXStudio> winget --version
v0.1.41331 Preview
```

I saw a couple of similar tickets, such as https://github.com/microsoft/winget-cli/issues/199 and https://github.com/microsoft/winget-cli/issues/189, not sure if this is an winget-cli issue or my installer's issue. The installer was built with Inno Setup 6, and installs fine in the admin mode.

**Comment by fangq** [comment]
WinGetSvc-Validation failed with the below error:
```
Manifest is invalid. (Line: 1, Col: 1, Idx: 0) - (Line: 1, Col: 1, Idx: 0): Exception during deserialization Property 'ManifestVersion' not found on type 'Microsoft.WinGetSvc.WinGet.Models.Manifest.Manifest'.
```

The field `ManifestVersion` does present in my [manifest file](https://github.com/fangq/winget-pkgs/blob/master/manifests/COTI/MCXStudio/0.9.8.yaml), I am wondering if this was caused by something else?

**Comment by KevinLaMS** [comment]
image

**Comment by fangq** [comment]
thanks @KevinLaMS for the comment. I was able to fix the inno error, and tested the installer on multiple machines. However, after pushing the rebuilt installer, I am still getting an "access is denied" error.

double-clicking on the installer installs everything smoothly without any issue. can you let me know if there is something else that I should fix? thanks

**Comment by KevinLaMS** [comment]
Looks like the homepage URL is not correct.  It worked if I removed the "s" and went just to the HTTP url.

image

**Comment by fangq** [comment]
thanks @KevinLaMS, the url is now fixed.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
