### PR TITLE
Submitting RuneScape 2.2.7.yaml

### PR DESCRIPTION
**Pull request by dandridgenet**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3849)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
This package has a dependency on DirectX which causes the installer to block.

**Comment by KevinLaMS** [comment]
DirectX is blocking this unattend install

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
[Policy] Needs-CLA

image

**Comment by ItzLevvie** [comment]
[Policy] reset feedback

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Pull request closed without merging**
