### PR TITLE
Microsoft.VisualStudioCode.Insiders_v1.84.0

### PR DESCRIPTION
**Pull request by lszomoru**
Microsoft.VisualStudioCode.Insiders_v1.84.0
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/123527)

### CODE REVIEW

**Comment by Trenly** [comment]
Trying this one more time; If that doesn't work, we'll send it to the professionals

**Comment by Trenly** [comment]
[Policy] Needs-Attention

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  The pull request doesn't include any manifest files yaml. 

I don't see why this error is encountered. The file seems to follow YAML syntax to me, and a web-based linter also passes it as valid.

**Comment by stephengillie** [comment]
Error unchanged.
>  The pull request doesn't include any manifest files yaml.

**Comment by Trenly** [comment]
Aha! I found the issue! 
* This is a duplicate of #123479 and the git diff doesn't seem to account for the fact that the commit has already been merged. Possibly because it's the exact same commit ID in both PR's

**Comment by stephengillie** [comment]
@Trenly, Great catch!

Closing as duplicate of https://github.com/microsoft/winget-pkgs/pull/123479

**Pull request closed without merging**
