### PR TITLE
Remove: Wondershare.PDFelement.8 version 8.4.8

### PR DESCRIPTION
**Pull request by coolplaylinbot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/122656)

### CODE REVIEW

**Comment by SpecterShell** [comment]
@coolplaylin The installer of this version is still available.

**Comment by CoolPlayLin** [comment]
Close with Reason: Mistaken Remove
CC @Trenly @stephengillie

**Comment by CoolPlayLin** [comment]
@SpecterShell issue opened in 122670

**Review by mdanish-kh — CHANGES_REQUESTED** [review]
Only the x86 arch installer node should be removed, not the whole manifest

**Comment by mdanish-kh** [comment]
Close with reason: See above discussion;

**Pull request closed without merging**
