### PR TITLE
Update D:\Git\winget-pkgs\manifests\k\Kiraku\AudioJam\1.17.3-352

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114416&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
Seems the publisher may be blocking pipelines?

**Comment by stephengillie** [comment]
> Installer Verification Analysis Context Information: 
Error occurred while downloading installer from https://download.kirakuapp.com/AUM_PC/Audio%20Jam%20Setup%201.17.3-352.exe. 0x80072F19.
Error information: 
Http Response: OK
Http Reason Phrase: OK

This isn't an error that I can waiver or approve around.

**Pull request closed without merging**
