### PR TITLE
New version: Microsoft.OneDrive version 24.111.0602.0003

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#5995](https://github.com/SpecterShell/Dumplings/actions/runs/9589636716).

<details>

<summary>Log</summary>

````
Updated: 24.108.0528.0005 → 24.111.0602.0003
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/158818)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2147012867
> 2024-06-21 18:49:46.868 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-06-21 18:49:46.950 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFA538EA465: (caller: 00007FFA538EAD01) Exception(1) tid(13f0) 80072EFD 
> 2024-06-21 18:49:49.330 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FFA538E395E: (caller: 00007FFA538E5C49) Exception(2) tid(13f0) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-06-21 18:49:49.536 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.111.0602.0003/amd64/OneDriveSetup.exe
> 2024-06-21 18:50:00.662 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-06-21 18:50:00.662 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFA538EA465: (caller: 00007FFA538EAD01) Exception(3) tid(13f0) 80072EFD 
> 2024-06-21 18:50:02.736 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FFA538E395E: (caller: 00007FFA538E5C49) Exception(4) tid(13f0) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-06-21 18:44:08.851 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-06-21 18:44:08.930 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFBE1CBA465: (caller: 00007FFBE1CBAD01) Exception(1) tid(1e54) 80072EFD 
> 2024-06-21 18:44:11.319 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FFBE1CB395E: (caller: 00007FFBE1CB5C49) Exception(2) tid(1e54) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-06-21 18:44:11.366 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.111.0602.0003/amd64/OneDriveSetup.exe
> 2024-06-21 18:44:22.041 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-06-21 18:44:22.041 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFBE1CBA465: (caller: 00007FFBE1CBAD01) Exception(3) tid(1e54) 80072EFD 
> 2024-06-21 18:44:24.318 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FFBE1CB395E: (caller: 00007FFBE1CB5C49) Exception(4) tid(1e54) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-06-21 18:45:08.043 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-06-21 18:45:08.186 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!54DB57EB: (caller: 54DB5E1C) Exception(1) tid(fec) 80072EFD 
> 2024-06-21 18:45:10.432 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!54DAF0BF: (caller: 54DB0E2B) Exception(2) tid(fec) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-06-21 18:45:10.449 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.111.0602.0003/OneDriveSetup.exe
> 2024-06-21 18:45:20.875 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-06-21 18:45:20.875 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!54DB57EB: (caller: 54DB5E1C) Exception(3) tid(fec) 80072EFD 
> 2024-06-21 18:45:22.995 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!54DAF0BF: (caller: 54DB0E2B) Exception(4) tid(fec) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-06-21 18:43:28.834 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-06-21 18:43:28.956 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!54CC57EB: (caller: 54CC5E1C) Exception(1) tid(14e4) 80072EFD 
> 2024-06-21 18:43:31.172 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!54CBF0BF: (caller: 54CC0E2B) Exception(2) tid(14e4) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-06-21 18:43:31.204 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.111.0602.0003/OneDriveSetup.exe
> 2024-06-21 18:43:41.562 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-06-21 18:43:41.563 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!54CC57EB: (caller: 54CC5E1C) Exception(3) tid(14e4) 80072EFD 
> 2024-06-21 18:43:43.706 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!54CBF0BF: (caller: 54CC0E2B) Exception(4) tid(14e4) 80072EFD     Msg:[InternetOpenUrl() failed.] 

Automated error analysis suggests -2147012867 may mean Network or Firewall Error.

Automated error analysis suggests 0x80072EFD may mean The operation timed out.

(Automated response - build 886.)

**Comment by SpecterShell** [comment]
@stephengillie This package needs manual review.

**Comment by stephengillie** [comment]
Yes, was just clearing VMs to make space for it.

**Review by stephengillie — DISMISSED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
