### PR TITLE
Add Screenpresso

### PR DESCRIPTION
**Pull request by gpon64**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/934)

### CODE REVIEW

**Comment by DocBox12** [comment]
Why was pipelines not started?

**Comment by KevinLaMS** [comment]
The problem with this submission is that it is not using the right path.  The publisher folder should be in manifests.

**Pull request closed without merging**
