### PR TITLE
[Zip][Portable] BurntSushi.ripgrep.GNU 13.0.0

### PR DESCRIPTION
**Pull request by Trenly**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/88067)

### CODE REVIEW

**Comment by Trenly** [comment]
@msftbot zip

**Review by ItzLevvie — DISMISSED** [review]

**Review by stephengillie — APPROVED** [review]

**Comment by adigitoleo** [comment]
Can't find the entry point on windows 11. Tried both GNU and MSVC installs. No 'rg', 'ripgrep' or similar, can't even see the directory in Program Files. Am I doing it wrong?

**Comment by sitiom** [comment]
> Edit: Found the directory, under Microsoft > WinGet > Packages. It is added to path but the problem is that the .exe resides in another level of nested directory and is not copied out of there.

Workaround: Enable developer mode
- https://github.com/microsoft/winget-cli/issues/2909

**Pull request merged**
