### PR TITLE
New version: Google.Chrome.Canary version 111.0.5556.0 [FP-D]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | Google Chrome Canary | Google Chrome Canary    |
| Version     | 111.0.5556.0     | 111.0.5556.0 |
| Publisher   | Google LLC   | Google LLC      |
| ProductCode |           | Google Chrome SxS    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [5495](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/3990497673>)

### CODE REVIEW

**Review by ImJoakim — DISMISSED** [review]

**Comment by stephengillie** [comment]
Unfortunately, this package did not pass a Defender scan:
image

**Review by ImJoakim — APPROVED** [review]

**Pull request merged**
