### PR TITLE
z1gProject.z1gHub version 1.1.0.0

### PR DESCRIPTION
**Pull request by Notplayingallday383**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/105604)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
InstallationVerification-x86-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20230503195636

**Comment by stephengillie** [comment]
Hi @Notplayingallday383,

The installation isn't unattended:
InstallationVerification-x86-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20230503195636

Is there an installer switch to bypass this and have it install automatically?

**Comment by Notplayingallday383** [comment]
> Hi @Notplayingallday383,
> 
> The installation isn't unattended: InstallationVerification-x86-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20230503195636
> 
> Is there an installer switch to bypass this and have it install automatically?

I used VB.NET for the installation. If there is any knowlage for how to make it silent installable let me know

**Comment by Notplayingallday383** [comment]
Is it fine if I resubmit the package with a silent installer?

**Comment by stephengillie** [comment]
> @stephengillie Is it fine if I resubmit the package with a silent installer?

Yes - please update the PR with the new manifest (and file location if changed) and it will start a new validation run.

**Comment by Notplayingallday383** [comment]
> > @stephengillie Is it fine if I resubmit the package with a silent installer?
> 
> Yes - please update the PR with the new file hash (and location if changed) and it will start a new validation run.

@stephengillie I am unable to update the manifest is there a different command I need to run? 
image

**Comment by Notplayingallday383** [comment]
Moved pull request to #106098

**Pull request closed without merging**
