### PR TITLE
New version: LinwoodCloud.Butterfly.Nightly version 2.0.0-beta.1

### PR DESCRIPTION
**Pull request by CodeDoctorDE**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/110564&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation failed with:
> 1:36:56 PM:  > 2023-06-23 13:36:55.744 [FAIL] Installer failed security check. Url: https://github.com/LinwoodDev/Butterfly/releases/download/v2.0.0-beta.1/linwood-butterfly-windows-setup.exe Result: 0x80004005 
image

**Comment by CodeDoctorDE** [comment]
like explained in https://github.com/microsoft/winget-pkgs/pull/109553#issuecomment-1587002400 this should be a false positive

**Comment by CodeDoctorDE** [comment]
Any update?

**Comment by stephengillie** [comment]
> Any update?

It was a false positive. Thanks for your patience and understanding.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
