### PR TITLE
Add Developer ISSUE_TEMPLATE

### PR DESCRIPTION
**Pull request by CoolPlayLin**
CC @denelon @stephengillie

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/115303&drop=dogfoodAlpha

### CODE REVIEW

**Comment by Trenly** [comment]
As discussed on Gitter / Element - I feel that having a template with such a similar name will only confuse users more, especially because it won't be clear who should use which template or when.

**Comment by CoolPlayLin** [comment]
@Trenly
I've modified the description of these template to differentiate them.

**Review by Trenly — CHANGES_REQUESTED** [review]
> @Trenly
> I've modified the description of these template to differentiate them.

I still don’t think the difference is clear. Also, if someone is taking the time to provide all the manifest information in an issue, it would be just as fast (and arguably easier) for them to make the manifest themselves.

I disagree with the concept at a fundamental level

**Comment by stephengillie** [comment]
If this template gathers all the info needed to build a manifest, then it should also kick off a GitHub Action to generate the template PR. Basically this would be a web-based intake method. But should be optional.

**Comment by Trenly** [comment]
Since this has been sitting for over a month, marking it as stale;

**Pull request closed without merging**
