### PR TITLE
cyberduck 7.5.1

### PR DESCRIPTION
**Pull request by zed76r**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3135)

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Validation has completed

**Comment by KevinLaMS** [comment]
I had to remove this PR.
Defender found "browsermodifier:win32/Foxibro

**Comment by ZeddG93** [comment]
> I had to remove this PR.
> Defender found "browsermodifier:win32/Foxibro

I think it's maybe a false alarm.
https://r.virscan.org/language/zh-cn/report/fa291cb23b40468323c5979ce4fbcee4

**Comment by KevinLaMS** [comment]
I ran another review, and will see if it will pass again.

**Comment by KevinLaMS** [comment]
i have created PR 3208

**Pull request merged**
