### PR TITLE
enabled use of InstallLocation for Oracle.JDK.17

### PR DESCRIPTION
**Pull request by Cube707**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

made the `-l,--location` option functional for this package

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/40984)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
I saw https://stackoverflow.com/a/8841965; which is enabled by default in https://github.com/microsoft/winget-cli/blob/b79e4087821c993f83f7c4731bbde7aa25612c73/src/AppInstallerCommonCore/Manifest/ManifestCommon.cpp#L461 for all packages using MSI

**Comment by Cube707** [comment]
hm, ok than I must have bodged up somewhere else, because the `-l` option wasn't working for me. I will test again....

**Comment by Cube707** [comment]
@lutzroeder  did some more Testing and even on a fresh Win10 VM it isn't working as expected:

All of the following result in a installation to the default directory, *NOT* to the given directory:

`winget install Oracle.JDK.17 -l C:\ProgStuff\jdk`
`winget install Oracle.JDK.17 -l "C:\ProgStuff\jdk"`
`winget install Oracle.JDK.17 --override "/passive TARGETDIR=C:\ProgStuff\jdk"`

The only thing that work and results in a different installation directory is:

`winget install Oracle.JDK.17 --override "/passive INSTALLDIR=C:\ProgStuff\jdk"`

**Comment by ItzLevvie** [comment]
I double-checked, looks like this installer supports `INSTALLDIR` instead of `TARGETDIR`.

**Review by ItzLevvie — APPROVED** [review]

**Comment by Cube707** [comment]
reading [the link you provided](https://stackoverflow.com/a/8841965), as I understand it, this is also the correct behavior:

> `TARGETDIR` represents [..] when the user runs Setup.exe or MsiExec.exe *with the /a command-line switch* 

the targetdir option may not be the correct option here? The `/a` switch for the msi process is not used or is it?

**Comment by Cube707** [comment]
@ItzLevvie I tested a few more packages and there seems to be some more inconsistency.

`ChristianHohnstadt.xca` and `StrawberryPerl.StrawberryPerl` seem to suffer from the same problem while `Borvid.HttpMasterExpress` works absoloutely fine as is and doesn't work with the INSTALLDIR option.

just using both options at the same time seems to work fine though. At least in my quick tests.

should I open a issue about this?

**Comment by OfficialEsco** [comment]
> should I open a issue about this?

Please do, this will break waaaaaaaaaaaaay too many Packages

**Pull request merged**
