### PR TITLE
New version: eza-community.eza version 0.18.13

### PR DESCRIPTION
**Pull request by cafkbot-winget**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/151047)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @cafkbot-winget,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 877.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-04-25 10:53:34.721 [FAIL] Installer failed security check. Url: https://github.com/eza-community/eza/releases/download/v0.18.13/eza.exe_x86_64-pc-windows-gnu.zip Result: 0x80004005

(Automated response - build 877.)

**Comment by cafkafk** [comment]
This has happened sporadically since october, initially we'd report these to microsoft and some analyst would spend a few days until we were again removed from defender. But these false flags kept happening and if felt like a lot of work that shouldn't be our responsibility, so we eventually stopped doing it. I really think a permanent fix would be in order.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
