### PR TITLE
Update D:\Git\winget-pkgs\manifests\f\ForceBindIP\ForceBindIP\1.32

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114340&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
