### PR TITLE
Submitting studio-cli version 23.9.3

### PR DESCRIPTION
**Pull request by TotTheMax**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135032)

### CODE REVIEW

**Comment by TotTheMax** [comment]
Hello, friends. I want to submit a new version of winget. Both the check and local installation tests pass, but the PR's pipeline has been failing for several days now. Could you please help me figure out the reason? Thank you very much.

**Comment by stephengillie** [comment]
Hi @TotTheMax,

We had some unexpected work on the pipelines. Sorry for the impact.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Installer https://distro.windriver.com/dist/wrstudio/wrstudio-cli-distro-cd-staged/23.9.3/win64/studio-cli_all.zip
 Scan request id: 'baed6f12-35ff-46cc-a274-e205fc733f5e'
 Error information: BlockingDetectionFound
 
 1/17/2024 8:19:38 PM

(Automated response - build 598.)

**Comment by stephengillie** [comment]
This might be due to a network block of data centers, to prevent automated downloads.

(Automated response - build 598.)

**Pull request closed without merging**
