### PR TITLE
New package: HB9RYZ.OmniRig version 2.1

### LINKED ISSUE #113446: [Package Request]: OmniRig
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### What's the type of your software?

exe

### Please provide the following information

Download Page Url: https://www.hb9ryz.ch/omnirig/index.html
Install Options: 
Publisher: HB9RYZ
Publisher Page: https://www.hb9ryz.ch
Package Page: https://www.hb9ryz.ch/omnirig/index.html
Package Name: OmniRig
Description: Freeware CAT engine for Ham Radio Transceiver/Receiver control.
Package Version: 2.1
Installer URL: https://www.hb9ryz.ch/downloads/install_omnirigv21.zip
License: Freeware
License Page: 
Copyright: Copyright 2023 by HB9RYZ

### PR DESCRIPTION
**Pull request by CoolPlayLin**
- Resolve #113446

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/115353&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by AsciiWolf** [comment]
@CoolPlayLin There is a slightly older version 2.0 of OmniRig available from the original author (2.1 is from a new developer that took over this project):

https://www.dxatlas.com/omnirig/
https://www.dxatlas.com/OmniRig/Files/OmniRig.zip
(Zip containing EXE installer.)

Unlike the version 2.1, this version 2.0 has working silent installation. :-) Feel free to prepare a new PR with this version instead of the 2.1 fork from HB9RYZ.

**Comment by AsciiWolf** [comment]
@CoolPlayLin There is a slightly older version 2.0 of OmniRig available from the original author (2.1 is from a new developer that took over this project):

https://www.dxatlas.com/omnirig/
https://www.dxatlas.com/OmniRig/Files/OmniRig.zip
(Zip containing EXE installer.)

Unlike the version 2.1, this version 2.0 has working silent installation. :-) Feel free to prepare a new PR with this version instead of the 2.1 fork from HB9RYZ.

**Comment by AsciiWolf** [comment]
> Unlike the version 2.1, this version 2.0 has working silent installation. :-) Feel free to prepare a new PR with this version instead of the 2.1 fork from HB9RYZ.

#116523

**Pull request closed without merging**
