### PR TITLE
Add new version - WK.WKRadar 7.9.0.379

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141338)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-03-06 08:21:49.878 [CORE] Started applying motw to C:\Users\User\AppData\Local\Temp\WinGet\WK.WKRadar.7.6.0.320\5d7facdd94c331e3b77b87fe72dbee84f0d68b19199665e1138c38e013c02945 with zone: 3 
> 2024-03-06 08:21:49.880 [CORE] Finished applying motw 
> 2024-03-06 08:21:49.880 [CORE] WinINet downloading from url: https://extranet.wk.com.br/extranet/download/7.6.0.320/Instalador.zip 
> 2024-03-06 08:21:50.621 [CORE] Download request failed. Returned status: 404 
> 2024-03-06 08:21:50.621 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFBB8B08767: (caller: 00007FFBB8B09FC9) Exception(4) tid(a78) 80190194 Not found (404). 

(Automated response - build 861.)

**Comment by stephengillie** [comment]
URL: https://extranet2.wk.com.br/download-wk-radar/?versao=7.9 
Status Code: 200

(Automated message - build 861)

**Comment by WKSistemas** [comment]
Hello @stephengillie, how are you?
I don't know the origin of this link from your manual analysis (version 7.6) but the .yalm I am currently submitting has this download link (version 7.9):
https://extranet2.wk.com.br/download-wk-radar/?versao=7.9

**Comment by stephengillie** [comment]
Hi @WKSistemas,

I believe my tools might be taking data from the first commit in this PR, instead of the most recent. Apologies.

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
