### PR TITLE
New version: Microsoft.PowerBI version 2.124.2028.0

### PR DESCRIPTION
**Pull request by PckgrBot**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137236)

### CODE REVIEW

**Comment by mdanish-kh** [comment]
[Policy] Blocking-Issue

- Blocked by #131328

@stephengillie this needs `License-Blocks-Install` label

**Comment by mdanish-kh** [comment]
> Let me know if you want this removed from my automation.

@PckgrBot -

Yes, i think we should do that until support for agreements is added in the community repository (#131328), or until the package offers a silent install without the `ACCEPT_EULA=1` switch

**Comment by Trenly** [comment]
Close with reason: package added in different PR;

**Pull request closed without merging**
