### PR TITLE
Softmaker.FreePDF.2019 version 2.10

### PR DESCRIPTION
**Pull request by borque**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/89277)

### CODE REVIEW

**Comment by borque** [comment]
I am unsure, what is wrong here as I simply "copied" the manifest-naming-structure used for other Softmaker-Products such as Softmaker Office or FreeOffice. They all follow the same schema at that company!?

**Comment by russellbanks** [comment]
This is because there is already a Publisher `SoftMaker` with the capital `M` as a [directory](https://github.com/microsoft/winget-pkgs/tree/c0b00af8d39af746bd28344dc642e62daa9af7a0/manifests/s/SoftMaker). Please submit under `SoftMaker.FreePDF.2022`.

**Review by russellbanks — CHANGES_REQUESTED** [review]
This is because there is already a Publisher `SoftMaker` with the capital `M` as a [directory](https://github.com/microsoft/winget-pkgs/tree/c0b00af8d39af746bd28344dc642e62daa9af7a0/manifests/s/SoftMaker). Please submit under `SoftMaker.FreePDF.2022`.

**Comment by borque** [comment]
Will be replaced by a new version!

**Pull request closed without merging**
