### PR TITLE
TeamViewer Host v15.9.4

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [X] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3303)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
I am not able to install this version. is the URL correct?
image

**Comment by OfficialEsco** [comment]
Weird, seems like my plan for TeamViewer doesn't work, could you use https://wheregoes.com to trace https://dl.teamviewer.com/download/version_15x/TeamViewer_Host_Setup.exe and tell me the final destination for you?

**Comment by OfficialEsco** [comment]
TeamViewer is doing some bullshit, the bot confirmed that the https://dl.teamviewer.com/download/version_15x/Jmp-91/TeamViewer_Host_Setup.exe worked, even the hash matched.
Now with TeamViewer's dynamic link the hash fails, no idea why...

**Comment by OfficialEsco** [comment]
New version and it was infact not the direct download link..

**Pull request closed without merging**
