### PR TITLE
New version: Netbird.Netbird version 0.23.0

### PR DESCRIPTION
**Pull request by BiosPlus**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/153009)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @BiosPlus,

> This PR's version number 0.23.0 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 0.20.3.5023577365, which has 4 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 880)

**Comment by stephengillie** [comment]
Hi @BiosPlus,

This manifest adds Apps and Features entries that aren't present in previous PR versions. These entries should be added to the previous versions, or removed from this version.

(Automated response - build 880.)

**Comment by stephengillie** [comment]
Hi @BiosPlus,

> This PR's version number 0.23.0 has 3 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 0.20.3.5023577365, which has 4 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 880)

**Comment by stephengillie** [comment]
Hi @BiosPlus,

This manifest adds Apps and Features entries that aren't present in previous PR versions. These entries should be added to the previous versions, or removed from this version.

(Automated response - build 880.)

**Comment by BiosPlus** [comment]
> Does this PR's version number exactly match the version reported in the Apps & features Settings page?

We're winning!
image


@stephengillie Any chance of merging this? My intent is to base the future version manifests off of this one and remove the `0.20.3.5023577365` version.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
