### PR TITLE
New version: stevencohn.OneMore version 3.28 

### PR DESCRIPTION
**Pull request by quhxl**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/24221)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Since you're a fast one here is another package https://github.com/gerardog/gsudo
Also simple fix for the issue https://github.com/Trenly/winget-pkgs/pull/9/files

**Comment by quhxl** [comment]
Okay, I'll take care of that. My RSS feed is not yet as advanced as yours. I am still missing more than half :/

**Comment by OfficialEsco** [comment]
Well you still catch updates faster than me so 🤷‍♂️
are you missing the links or does it not support 800 feeds?

**Comment by quhxl** [comment]
Im just missing links haha

**Comment by OfficialEsco** [comment]
Try this https://gist.github.com/OfficialEsco/599257140346fa4a79b36dc63bb20d61
make sure `$Manifests` points to the winget folder repo
You should then be able to import xml/opml to your RSS reader, and it will not make duplicates.

**Comment by quhxl** [comment]
That's insane. Thanks!

But after I loaded it twice because first the reader crashed, my access on GitHub was restricted Hahahaha

**Comment by OfficialEsco** [comment]
> That's insane. Thanks!
> 
> But after I loaded it twice because first the reader crashed, my access on GitHub was restricted Hahahaha
> Nothing what a bit of VPN magic can't fix haha

Haha i would suggest refreshing some of the feeds at a time, 800 requests is a bit too much in a short amount of time, QuiteRSS actually stops after 100ish i don't get blocked, but you can update at least 100 each 10 second i believe

**Comment by OfficialEsco** [comment]
Hmm try to rerun this one, the x86 might be the problem again..

**Pull request merged**
