### PR TITLE
Remove: Tableau.PrepBuilder version 23.3.30378

### PR DESCRIPTION
**Pull request by coolplaylinbot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150452)

### CODE REVIEW

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
Url works in the browser for me?

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/pull/150450#issuecomment-2072952469

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/pull/150450#issuecomment-2072952469

**Comment by stephengillie** [comment]
Pre-empted by 
- https://github.com/microsoft/winget-pkgs/pull/150796

**Pull request closed without merging**
