### PR TITLE
New version: Jackett.Jackett version 0.21.1556

### PR DESCRIPTION
**Pull request by ilike2burnthing**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135128)

### CODE REVIEW

**Comment by ilike2burnthing** [comment]
test

**Comment by ilike2burnthing** [comment]
Worth a shot :P

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
