### PR TITLE
New package: Thewh1teagle.Serust version 0.0.1

### PR DESCRIPTION
**Pull request by thewh1teagle**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

### CODE REVIEW

**Comment by thewh1teagle** [comment]
@microsoft-github-policy-service agree [company="Serust"]

**Comment by thewh1teagle** [comment]
@microsoft-github-policy-service agree

**Comment by thewh1teagle** [comment]
> ```
> @microsoft-github-policy-service agree
> ```

@microsoft-github-policy-service agree

**Comment by thewh1teagle** [comment]
tested locally
```console
winget install --manifest Serust\0.0.1\
Found Serust [Thewh1teagle.Serust] Version 0.0.1
Downloading https://github.com/thewh1teagle/serust/releases/download/v0.0.1/serust_v0.0.1_x86_64-pc-windows-gnu.zip
  ██████████████████████████████  2.78 MB / 2.78 MB
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "serust"
Path environment variable modified; restart your shell to use the new value.
Successfully installed

> refreshenv     
Reading environment variables from registry. Please wait... Done.

>where serust
C:\Users\User\AppData\Local\Microsoft\WinGet\Links\serust.exe


>serust -h
Serial monitor cli in rust

Usage: serust [OPTIONS]

Options:
 ...
```

**Comment by Trenly** [comment]
> 2024-01-03 18:24:25.860 [FAIL] Installer failed security check. Url: https://github.com/thewh1teagle/serust/releases/download/v0.0.1/serust_v0.0.1_x86_64-pc-windows-gnu.zip Result: 0x80004005

**Comment by thewh1teagle** [comment]
@Trenly 
I'm not sure why the sec check failed
The exe Isn't signed, maybe that's the problem?

**Comment by Trenly** [comment]
> @Trenly I'm not sure why the sec check failed The exe Isn't signed, maybe that's the problem?

Sometimes it takes a few days for AV software to scan through and validate it isn’t a threat

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-03 18:24:25.860 [FAIL] Installer failed security check. Url: https://github.com/thewh1teagle/serust/releases/download/v0.0.1/serust_v0.0.1_x86_64-pc-windows-gnu.zip Result: 0x80004005

(Automated response - build 516.)

**Comment by thewh1teagle** [comment]
> Hello @thewh1teagle,
> 
> The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.
> 
> Template: msftbot/validationError/installation/general

I already checked the package locally and it worked.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335141

(Automated response - build 530.)

**Comment by stephengillie** [comment]
> > Hello @thewh1teagle,
> > The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.
> > Template: msftbot/validationError/installation/general
> 
> I already checked the package locally and it worked.

Yes - our pipelines are made primarily to work with Windows Forms, and sometimes need some assistance with CLI applications. Thanks for your patience.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
