### PR TITLE
New version: goplus.gop 1.2.0-test.4

### PR DESCRIPTION
**Pull request by cpunion**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/133915)

### CODE REVIEW

**Comment by cpunion** [comment]
I have tested in local machine, it succeed.

**Comment by cpunion** [comment]
image

**Comment by stephengillie** [comment]
Hi @cpunion,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 602.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-18 00:54:04.273 [FAIL] Installer failed security check. Url: https://github.com/goplus/gop/releases/download/v1.2.0-test.4/gop_v1.2.0-test.4_Windows_i386.zip Result: 0x80004005 Property(S): dirC1D8E01F6B8B58824E992A66BFEC66EA = C:\Program Files\Go\src\cmd\cgo\internal\testerrors\ Property(S): dir446D7A79D5DF29B74E6C3118A0FBA488 = C:\Program Files\Go\src\cmd\cgo\internal\testerrors\testdata\ Property(S): dir931AE0ADF19288284C29A8F6AFF9D20B = C:\Program Files\Go\src\cmd\go\testdata\failssh\ Property(S): dir4C81B01258ED70E2354B05EC1D50A64D = C:\Program Files\Go\src\cmd\vendor\golang.org\x\tools\go\analysis\passes\errorsas\ Property(S): dir563DB259519880316A9FD76C701BC816 = C:\Program Files\Go\src\errors\ Property(S): dir18C753920C81A78D6EB38F46F6404A03 = C:\Program Files\Go\src\internal\oserror\ Property(S): dirDFA0FA250B47DCC2A636304D2F9AA4FE = C:\Program Files\Go\src\internal\types\errors\ Property(S): ErrorDialog = ErrorDlg MSI (s) (A4:10) [00:53:41:622]: Windows Installer installed the product. Product Name: Go Programming Language 386 go1.21.6. Product Version: 1.21.6. Product Language: 1033. Manufacturer: https://go.dev. Installation success or error status: 0.

(Automated response - build 602.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
