### PR TITLE
New version: AlekseyHoffman.Sigma-File-Manager version 1.4.0

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

### CODE REVIEW

**Comment by aleksey-hoffman** [comment]
@OfficialEsco hey man, I only just found out Sigma was available on winget. I didn't know you were uploading it here yourself.
Thanks for doing this. I was just surprised to learn this from a reddit comment.

I updated the windows exe asset for the v.1.4 release about 30 minutes after the release was published because someone found an error on launch. The hash of the asset should match this commit:
https://github.com/aleksey-hoffman/sigma-file-manager/commit/3b4a4f58afd7a09d23fca28fdcf23305f8468331

A Redditor just told me that winget still serves v1.3 version. Maybe that's why the checks are failing?

**Comment by OfficialEsco** [comment]
Microsoft gave msftbot some sleeping pills on Friday before they took the weekend which is why the errors..
This Error is just a random one that appears at times 
```
****************************************************************************************
Domain Url Validation
****************************************************************************************
Status: InProgress

9/5/2021 8:21:25 PM

****************************************************************************************
Domain Url Validation
****************************************************************************************
Status: InProgress

9/5/2021 8:21:29 PM

****************************************************************************************
Domain Url Validation
****************************************************************************************
Status: Completed
Result: Failed
```
Since all the urls point to GitHub this should be fixed by a rerun

**Comment by aleksey-hoffman** [comment]
@OfficialEsco ok, well thanks for handling all of this.
What if I modify the installer and let the user choose the directory during installation. Will winget be able to handle this? Or is it using a custom build config?

**Comment by OfficialEsco** [comment]
Winget does support the default installation switch for the common installertypes, in this case Nullsoft/NSIS which is `/D=` which can be used with `—location`.

GitHub project releases are the simples to track so unless you want to automate the submission it will get picked up fairly quick 😁

Also we do merge quickly when the bot don’t throw tantrums..

**Review by ItzLevvie — APPROVED** [review]

**Comment by aleksey-hoffman** [comment]
@OfficialEsco hey mate, v1.5 is out, would you be able to add this version to winget?

**Pull request merged**
