### PR TITLE
Remove LMStudio.LMStudio 0.2.25 to ElementLabs.LMStudio 0.2.25

### PR DESCRIPTION
**Pull request by SpecterShell**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/170753)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://releases.lmstudio.ai/windows/0.2.25/latest/LM-Studio-0.2.25-Setup.exe 
OK

(Automated message - build 920)

**Comment by stephengillie** [comment]
URL: https://releases.lmstudio.ai/windows/0.2.25/latest/LM-Studio-0.2.25-Setup.exe 
OK

(Automated message - build 920)

**Comment by stephengillie** [comment]
URL: https://releases.lmstudio.ai/windows/0.2.25/latest/LM-Studio-0.2.25-Setup.exe 
Status Code: 200

(Automated message - build 894)

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://releases.lmstudio.ai/windows/0.2.25/latest/LM-Studio-0.2.25-Setup.exe 
Status Code: 200

(Automated message - build 894)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
