### PR TITLE
Update version: RustDesk.RustDesk version 1.2.3

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132942)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification.
>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Review by OfficialEsco — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 1/7/2024 1:04:19 PM
 Installer Verification Analysis Context Information: 
 Installer https://github.com/rustdesk/rustdesk/releases/download/1.2.3/rustdesk-1.2.3-x86_64.exe
 Scan request id: 'fdb1a1ed-9f95-46ec-993d-278ce916b0da'
 Error information: BlockingDetectionFound

(Automated response - build 525.)

**Pull request closed without merging**
