### PR TITLE
New version: twpayne.chezmoi 2.39.0

### PR DESCRIPTION
**Pull request by twpayne**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/118850)

### CODE REVIEW

**Comment by twpayne** [comment]
@microsoft-github-policy-service there is no output from your validation actions. How am I supposed to know what to fix?

**Comment by twpayne** [comment]
image

Relevant links:
* https://github.com/microsoft/winget-pkgs/pull/118850/checks?check_run_id=16458418214
* https://github.com/microsoft/winget-pkgs/pull/118850/checks?check_run_id=16458413896

Not sure what else I can do here.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Standard error:  Installation failed with exit code -1978335187 2023-09-03 14:58:17.922 [FAIL] Installer failed security check. Url: https://github.com/twpayne/chezmoi/releases/download/v2.39.0/chezmoi_2.39.0_windows_i386.zip Result: 0x80004005

**Comment by twpayne** [comment]
Thanks! https://go.dev/doc/faq#virus is likely relevant, but you surely already know about this.

**Comment by twpayne** [comment]
Closing in favor of https://github.com/microsoft/winget-pkgs/pull/119009

**Pull request closed without merging**
