### PR TITLE
Update: Xunlei 11.2.5.1778

### PR DESCRIPTION
**Pull request by Voya9e**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/24195)

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]
The PackageName and Publisher is technically wrong, but since the zh-CN locale have the metadata i believe it should still match

**Comment by OfficialEsco** [comment]
Dude, stop changing the branch

**Comment by Meng5in** [comment]
> Dude, stop changing the branch

I'm sorry, I pressed the wrong button.

**Pull request merged**
