### PR TITLE
Remove Old: JanDeDobbeleer.OhMyPosh version 3.171.1

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
null

### CODE REVIEW

**Review by ImJoakim — COMMENTED** [review]
> Product: MySQL Workbench 8.0 CE -- MySQL Workbench requires the Visual C++ 2019 Redistributable Package to be installed. Click the Download-Button on the next page to open a web page containing further instructions.
> 
> MySQL Workbench requires the Visual C++ 2019 Redistributable Package to be installed. Click the Download-Button on the next page to open a web page containing further instructions.


image

**Comment by vedantmgoyal2009** [comment]
@denelon Please add `Dependencies` and `Blocking-Issue` to this PR. I have added `PackageDependencies` in the manifest. When Dependencies support will roll out, we can merge this PR.

**Comment by ImJoakim** [comment]
> @denelon Please add `Dependencies` and `Blocking-Issue` to this PR. I have added `PackageDependencies` in the manifest. When Dependencies support will roll out, we can merge this PR.

He's currently unavailable this week. I'll go ahead and tag @palenshus

**Comment by vedantmgoyal2009** [comment]
Oh, I forgot... Levvie told me in my other PR. Thanks.

**Comment by palenshus** [comment]
Done, thanks for the heads up @vedantmgoyal2009 and @ImJoakim!

**Comment by vedantmgoyal2009** [comment]
@msftbot it has been tagged with "Blocking-Issue"

**Comment by denelon** [comment]
@vedantmgoyal2009 I just checked the rules and I had to add the check for the "Blocking-Issue" label in this specific case. It shouldn't do that again.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
