### PR TITLE
Add OBS Studio 26.1.1

### PR DESCRIPTION
**Pull request by mdonoughe**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/6463)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
image

**Comment by mdonoughe** [comment]
The installer is supposed to check for the runtimes and offers to download them if they are missing. I don't know if this prompt appears during the install from winget because I already have them on my system. https://github.com/obsproject/obs-studio/blob/8285141ba5e5687e7ba1b3c97f303583941cfcbf/UI/installer/mp-installer.nsi#L114-L119

25.0.8, the previous version in this repo, uses similar logic for msvc 12. Maybe that one works because the test environment already has 12?

**Comment by mdonoughe** [comment]
Looks like there was a PR for a previous version that was closed after a similar issue. It'd be nice if there was a way to signal that so people don't keep trying to add new versions and failing (for this package and others with the same issue).

**Comment by ItzLevvie** [comment]
Is this issue resolved now? I see OBS Studio 27.0.0 in https://github.com/microsoft/winget-pkgs/tree/master/manifests/o/OBSProject/OBSStudio.

**Comment by mdonoughe** [comment]
Not needed anymore.

**Pull request closed without merging**
