### PR TITLE
Remove version: OSGeo.GeoServer version 2.23.0

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/196116)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://sourceforge.net/projects/geoserver/files/GeoServer/2.23.0/GeoServer-2.23.0-winsetup.exe/download 
OK

(Automated message - build 923)

**Comment by stephengillie** [comment]
URL: https://sourceforge.net/projects/geoserver/files/GeoServer/2.23.0/GeoServer-2.23.0-winsetup.exe/download 
OK

(Automated message - build 923)

**Comment by stephengillie** [comment]
URL: https://sourceforge.net/projects/geoserver/files/GeoServer/2.23.0/GeoServer-2.23.0-winsetup.exe/download 
Status Code: 200

(Automated message - build 900)

**Comment by ItzLevvie** [comment]
Close with reason: URL works;

**Pull request closed without merging**
