### PR TITLE
Update Nvidia.GeForceNow.installer.yaml URL

### PR DESCRIPTION
**Pull request by rakleed**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/130493)

### CODE REVIEW

**Comment by SpecterShell** [comment]
What is the point of this PR?

**Comment by stephengillie** [comment]
> What is the point of this PR?

Update the file path. Note that the hash doesn't change, so it's very likely the same package.

**Review by stephengillie — APPROVED** [review]

**Comment by SpecterShell** [comment]
> > What is the point of this PR?
> 
> Update the file path. Note that the hash doesn't change, so it's very likely the same package.

The previous link is a versioned link and the `F11A7B` at the end of it is the unique identifier for each version of this package. The link this PR changes to is unversioned.

**Pull request merged**
