### PR TITLE
Libretro.RetroArch version 1.10.3.0

### PR DESCRIPTION
**Pull request by fpscan**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

While I have multiple PR related to our project to get in WinGet, this should be the final one. This contains stable where we fix with ninja release the directx9 popup and HASH values are valid. 

image

```
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: http://buildbot.libretro.com/stable/1.10.3/windows/x86_64/RetroArch-Win64-setup.exe
  InstallerSha256: 7FAE3676A37A2B174692C9FC3D17B0C4DB284966049E8630CF93A004AA588C60
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
- Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: http://buildbot.libretro.com/stable/1.10.3/windows/x86/RetroArch-Win32-setup.exe
  InstallerSha256: 8F855E0AEA8702A6192812EF29FD6EFBBC10A5B86833C943A404B8D422F3A712
  InstallerSwitches:
    Silent: /S
    SilentWithProgress: /S
```

image

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/59350)

### CODE REVIEW

**Comment by fpscan** [comment]
@j82w @Trenly @ItzLevvie 
I thought I could tag you since you have been provide helpful tips. So we pushed ninja release for directx9 thing and it is no longer a problem. I double check the hash(fresh build from today) and it was correct but [Azure still fails](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=307609&view=logs&j=871b4eed-22de-5cb6-c1c8-82f190de633f&t=523ceef4-ddf7-55a0-c83d-dd0f77b67744) for x64:

```
****************************************************************************************
Installer Validation
****************************************************************************************
Status: Completed
-----------------------------------------------------
Installer http://buildbot.libretro.com/stable/1.10.3/windows/x86/RetroArch-Win32-setup.exe
Result: Validation Succeeded
-----------------------------------------------------
Installer http://buildbot.libretro.com/stable/1.10.3/windows/x86_64/RetroArch-Win64-setup.exe
Result: Hash Validation Failed
-----------------------------------------------------
Result: Failed
```
I also made submission for both build where having incorrect detection for smartscreen and here is a part of MS response;
```
We can confirm that the application "retroarch-win64-setup.exe", f5fdb51e3ce4b7ab3a2af7859188aba3bef3a3ea4c3e76cb72481f76d551a074”) has since established reputation and attempting to
download or run the application should no longer show any warnings...
```

At this moment I'm about to give up. Scoop and Chocolatey working fine but I couldn't manage WinGet work least for this version so we can announce and see if it's usable for people or not.

**Review by ItzLevvie — DISMISSED** [review]

**Comment by Trenly** [comment]
@fpscan have you tried using https instead of http?

**Review by ItzLevvie — APPROVED** [review]

**Comment by fpscan** [comment]
> @fpscan have you tried using https instead of http?

Thank you for pointing that I was sure that I used https instead http but I saw it wasn't. So I'm on the go but I used browser desktop view and made the changes. So far it's is running and not failed.

**Comment by ItzLevvie** [comment]
x86 hash error:
```
2022-05-02 14:24:03.488 [CORE] WinGet, version [1.2.10271], activity [{D60A44EB-ECE1-404E-A857-FA39140484C4}]
2022-05-02 14:24:03.488 [CORE] OS: Windows.Desktop v10.0.19042.1052
2022-05-02 14:24:03.488 [CORE] Command line Args: C:\Users\Validator\AppData\Local\Microsoft\WindowsApps\winget.exe install --manifest D:\TRANSFER\24d28397-40ca-ec11-950a-000d3a9eda90\Manifest.yaml --accept-package-agreements
2022-05-02 14:24:03.488 [CORE] Package: Microsoft.DesktopAppInstaller v1.17.10271.0
2022-05-02 14:24:03.488 [CORE] IsCOMCall:0; Caller: winget-cli
2022-05-02 14:24:03.506 [CLI ] WinGet invoked with arguments: 'install' '--manifest' 'D:\TRANSFER\24d28397-40ca-ec11-950a-000d3a9eda90\Manifest.yaml' '--accept-package-agreements'
2022-05-02 14:24:03.509 [CLI ] Found subcommand: install
2022-05-02 14:24:03.509 [CLI ] Leaf command to execute: root:install
2022-05-02 14:24:03.521 [CLI ] Executing command: install
2022-05-02 14:24:03.526 [CLI ] Manifest fields: Name [RetroArch], Version [1.10.3.0]
2022-05-02 14:24:03.529 [CLI ] Starting installer selection.
2022-05-02 14:24:03.529 [CLI ] Installer [X64,nullsoft,Unknown,] not applicable: Machine is not compatible with X64
2022-05-02 14:24:03.529 [CLI ] Completed installer selection.
2022-05-02 14:24:03.572 [CLI ] Generated temp download path: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Libretro.RetroArch.1.10.3.0\8f855e0aea8702a6192812ef29fd6efbbc10a5b86833c943a404b8d422f3a712
2022-05-02 14:24:03.576 [CORE] Downloading to path: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Libretro.RetroArch.1.10.3.0\8f855e0aea8702a6192812ef29fd6efbbc10a5b86833c943a404b8d422f3a712
2022-05-02 14:24:03.576 [CORE] DeliveryOptimization downloading from url: https://buildbot.libretro.com/stable/1.10.3/windows/x86/RetroArch-Win32-setup.exe
2022-05-02 14:24:07.603 [CORE] Download completed.
2022-05-02 14:24:23.366 [CORE] Started applying motw to C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Libretro.RetroArch.1.10.3.0\8f855e0aea8702a6192812ef29fd6efbbc10a5b86833c943a404b8d422f3a712 with zone: 3
2022-05-02 14:24:23.374 [CORE] Finished applying motw
2022-05-02 14:24:23.375 [CLI ] Package hash verification failed. SHA256 in manifest [8f855e0aea8702a6192812ef29fd6efbbc10a5b86833c943a404b8d422f3a712] does not match download [f847b92f8e6a13546abb88d0961b2f3f4f419de17a0a53ca895bf4094df03a37]
2022-05-02 14:24:23.375 [CLI ] Terminating context: 0x8a150011 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:19d
```

**Comment by fpscan** [comment]
> 



> x86 hash error:
> 
> ```
> 2022-05-02 14:24:03.488 [CORE] WinGet, version [1.2.10271], activity [{D60A44EB-ECE1-404E-A857-FA39140484C4}]
> 2022-05-02 14:24:03.488 [CORE] OS: Windows.Desktop v10.0.19042.1052
> 2022-05-02 14:24:03.488 [CORE] Command line Args: C:\Users\Validator\AppData\Local\Microsoft\WindowsApps\winget.exe install --manifest D:\TRANSFER\24d28397-40ca-ec11-950a-000d3a9eda90\Manifest.yaml --accept-package-agreements
> 2022-05-02 14:24:03.488 [CORE] Package: Microsoft.DesktopAppInstaller v1.17.10271.0
> 2022-05-02 14:24:03.488 [CORE] IsCOMCall:0; Caller: winget-cli
> 2022-05-02 14:24:03.506 [CLI ] WinGet invoked with arguments: 'install' '--manifest' 'D:\TRANSFER\24d28397-40ca-ec11-950a-000d3a9eda90\Manifest.yaml' '--accept-package-agreements'
> 2022-05-02 14:24:03.509 [CLI ] Found subcommand: install
> 2022-05-02 14:24:03.509 [CLI ] Leaf command to execute: root:install
> 2022-05-02 14:24:03.521 [CLI ] Executing command: install
> 2022-05-02 14:24:03.526 [CLI ] Manifest fields: Name [RetroArch], Version [1.10.3.0]
> 2022-05-02 14:24:03.529 [CLI ] Starting installer selection.
> 2022-05-02 14:24:03.529 [CLI ] Installer [X64,nullsoft,Unknown,] not applicable: Machine is not compatible with X64
> 2022-05-02 14:24:03.529 [CLI ] Completed installer selection.
> 2022-05-02 14:24:03.572 [CLI ] Generated temp download path: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Libretro.RetroArch.1.10.3.0\8f855e0aea8702a6192812ef29fd6efbbc10a5b86833c943a404b8d422f3a712
> 2022-05-02 14:24:03.576 [CORE] Downloading to path: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Libretro.RetroArch.1.10.3.0\8f855e0aea8702a6192812ef29fd6efbbc10a5b86833c943a404b8d422f3a712
> 2022-05-02 14:24:03.576 [CORE] DeliveryOptimization downloading from url: https://buildbot.libretro.com/stable/1.10.3/windows/x86/RetroArch-Win32-setup.exe
> 2022-05-02 14:24:07.603 [CORE] Download completed.
> 2022-05-02 14:24:23.366 [CORE] Started applying motw to C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\Libretro.RetroArch.1.10.3.0\8f855e0aea8702a6192812ef29fd6efbbc10a5b86833c943a404b8d422f3a712 with zone: 3
> 2022-05-02 14:24:23.374 [CORE] Finished applying motw
> 2022-05-02 14:24:23.375 [CLI ] Package hash verification failed. SHA256 in manifest [8f855e0aea8702a6192812ef29fd6efbbc10a5b86833c943a404b8d422f3a712] does not match download [f847b92f8e6a13546abb88d0961b2f3f4f419de17a0a53ca895bf4094df03a37]
> 2022-05-02 14:24:23.375 [CLI ] Terminating context: 0x8a150011 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:19d
> ```

Everytime I check I only get `8F855E0AEA8702A6192812EF29FD6EFBBC10A5B86833C943A404B8D422F3A712` for 32bit build. I may seem like I repeat myself but is there any chance manual merge can be apply at this time?

**Comment by Trenly** [comment]
@denelon - Is there any chance someone could take an hour or two to look into why the hash would pass the Installer scan but not the installation validation? This isn't the only PR we've seen this on (I'll try and find a few others for reference, as well as open an issue if I can find them)

**Comment by denelon** [comment]
@Trenly, I've asked the team to take a look.

**Comment by denelon** [comment]
RetroArch requires DirectX 9.0C and it was not detected.

**Comment by denelon** [comment]
We're also getting a different hash.

**Comment by fpscan** [comment]
> RetroArch requires DirectX 9.0C and it was not detected.

We are working on this.

> We're also getting a different hash.

I'm not sure what causes this but I get correct hash, stable build uses same hash until new version uploaded. We are using basic cloud flare.

**Comment by fpscan** [comment]
@denelon Hi, I'm not sure why Hash is act like that even file didn't changed last time I uploaded. What we can do for hash at this moment? Winget is an official MS platform and directx is a fundamental part of many windows applications. Why MS think it is acceptable not to support the inclusion of directx when installing anything? I assume dependencies is not considering fo `v1.3-Client` so our installer won't be there. However I see zip installation for 1.3 in here https://github.com/microsoft/winget-cli/issues/182 and there https://github.com/microsoft/winget-cli/issues/140, so I guess there is nothing I can do beside waiting zip installation get merge for 1.3 and I make new PR for zip version instead installer(?)

**Comment by denelon** [comment]
@fpscan

Dependencies is still experimental and only supported in the simplest use case. We are looking to tackle dependencies after .zip. Unfortunately, portable apps was a bit more complex and took a bit longer than we anticipated. .zip is currently at risk for getting into 1.3, but we're going to keep working on it.

**Comment by Madhusudhan-MSFT** [comment]
During our manual verification process, we are observing the hashes are changing for ex:

image

We think this is likely due to publisher is changing the installer on their end after publishing.  If the hash mismatch is still an issue after this is un-blocked for dependency, we will investigate further at that time.

**Comment by fpscan** [comment]
> During our manual verification process, we have been noticing the hashes for the installers are keep getting changed for ex. see 64 bit installer hash value in the below screenshot:
> 
> image
> 
> We think this is likely due to publisher is changing the installer on their end after publishing. If the hash mismatch is still an issue after this is un-blocked for dependency, we will investigate further at that time.

I don't know why HASH is changing but I have not published another build for 1.10.3 now or earlier. When I check the hash I get the same numbers.

I think we need to wait until WinGet gets either Dependencies or Portable app installer. The RA installer already includes a bundled directx installer - it seems that this is the problem, and packages on winget cannot include any external installers at all. Regardless of how you bundle directx, it has to call dxsetup.exe at some point - there is no way around this.
So what is needed is an RA installer that doesn't need directx at all.... I think the main problem there is that it's needed for the default windows audio driver - and there's not good alternative. If we don't have directx9 at all then we will have a lot of sound issue. I was expecting this could be painless experience for us but it is not right now, I'll check the milestone time to time. I would like to say that I am open for any suggestion.

**Pull request closed without merging**
