### PR TITLE
New package: Nvidia.GRID version 538.46

### LINKED ISSUE #166666: [Package Request]: Nvidia.GRID version 538.46
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://learn.microsoft.com/en-us/azure/virtual-machines/windows/n-series-driver-setup
Publisher: NVIDIA Corporation
Package Name: NVIDIA GRID Display Driver
Description: NVIDIA GRID driver installers for NV, NVv3 and NVads A10 v5-series VMs used as virtual workstations or for virtual applications. Also for NCas_T4_V3 VM series where the GRID drivers enable the graphics functionalities similar to NV-series.
Package Version: 16.5 (538.46)
Installer URL: https://go.microsoft.com/fwlink/?linkid=874181

### PR DESCRIPTION
**Pull request by jbne**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/166661)

Resolve #166666

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 887.)

**Comment by Dragon1573** [comment]
> [!TIP]
>
> Adding `Resolve #166666` to the [very first comment](https://github.com/microsoft/winget-pkgs/pull/166661#issue-2453969772) of this PR will link this with that issue. When PR is successfully merged, the issue will also be automatically closed.

CC @jbne

**Comment by stephengillie** [comment]
Manual Validation ended with:
image

Hi @jbne,

Is another installer switch needed to verify where these files will be saved?

**Comment by jbne** [comment]
@stephengillie I'm not aware of any other installer switches. Using the silent install flag `-s` should not show that dialog, I validated this directly with the .exe installer without Winget. I noticed doing `winget install` on the manifest without the `--silent` flag does result in the dialog. Does `winget install` not do silent install by default?

**Comment by stephengillie** [comment]
Yes, `winget install` performs silent installs by default, because community members have found the silent install combination for every software package in the repo. You might be referring to default silent switches for certain installer types, which do not always work. Unfortunately, not every installer is configured to allow silent install.

**Comment by jbne** [comment]
Looks like `winget install --manifest` uses SilentWithProgress by default, removing that fixes it - the `-passive` flag probably does not work.

**Comment by jbne** [comment]
The build may be failing because the GRID drivers can only be installed on certain Azure VMs. I think I have the appropriate return codes specified for dealing with that case as well:

```
- InstallerReturnCode: 3858759936
  ReturnResponse: systemNotSupported
```

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334957
> 2024-08-13 09:21:04.045 [CLI ] ShellExecute installer failed: 3858759936

Automated error analysis suggests -1978334957 may mean Package not supported by the system.

(Automated response - build 887.)

**Comment by jbne** [comment]
Yeah I guess so, I wonder why -1978334957 would be used instead of 3858759936? It seems to correspond to [APPINSTALLER_CLI_ERROR_INSTALL_SYSTEM_NOT_SUPPORTED](https://github.com/microsoft/winget-cli/blob/542759707d980a1068145283b821568bc45593c7/doc/windows/package-manager/winget/returnCodes.md?plain=1#L170), is that something being returned from the Winget CLI instead of the installer?

**Comment by stephengillie** [comment]
Manual Validation ended with the same errors. 
[Nvidia.GRID.x64.538.46.log](https://github.com/user-attachments/files/16630604/Nvidia.GRID.x64.538.46.log)

**Comment by stephengillie** [comment]
Hi @jbne,

This set of switches seems not to modify the filesystem at all:
image

**Comment by jbne** [comment]
@stephengillie 

I'm not entirely sure what to do about this one since this will only install successfully on specific Azure VM SKUs: https://learn.microsoft.com/en-us/azure/virtual-machines/windows/n-series-driver-setup

My last change I made the exit code specific to "platform not supported" an expected successful code, which at least doesn't result in a failure in the pipeline but is also the reason why it did not modify the filesystem:
```
InstallerSuccessCodes:
- 3858759936
```

**Comment by Trenly** [comment]
[Policy] Hardware

**Comment by denelon** [comment]
Supporting custom hardware in validation is "Not Planned".
* https://github.com/microsoft/winget-pkgs/issues/199504

**Pull request closed without merging**
