### PR TITLE
Irfanview.IrfanviewPlugins version 4.60.0.0

### PR DESCRIPTION
**Pull request by ostrich**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/59777)

### CODE REVIEW

**Comment by KaranKad** [comment]
We can't use fosshub links according to https://www.fosshub.com/tos.html#fh-tou-o2
Also see https://github.com/microsoft/winget-pkgs/issues/23933

**Comment by lychichem** [comment]
Seems this PR validation blocks all other PR validation created behind it? Could anyone fix it?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/59777#issuecomment-1120387411

**Comment by ItzLevvie** [comment]
@lychichem we'll have to wait until the WinGet team comes back on Monday.

**Comment by ItzLevvie** [comment]
looks like it's back up and running again.

**Comment by ostrich** [comment]
> We can't use fosshub links according to https://www.fosshub.com/tos.html#fh-tou-o6 Also see #23933

Sorry, don't know how to update the download link in the merge request. It's available here (same site that the main Irfanview installer downloads from): https://download.betanews.com/download/1099412658-1/iview460_plugins_x64_setup.exe

**Comment by ItzLevvie** [comment]
We need to wait for https://github.com/microsoft/winget-cli/issues/163 so we can add IrfanView as a dependency.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
You can set this PR to DRAFT until it's solved.

There's also another PR for this (https://github.com/microsoft/winget-pkgs/pull/21591) but it's an older version.

**Comment by ostrich** [comment]
> We need to wait for [microsoft/winget-cli#163](https://github.com/microsoft/winget-cli/issues/163) so we can add IrfanView as a dependency.

That's from 2020. Does it really need to be resolved before we can add IrfanView Plugins to the winget repo?

**Comment by ostrich** [comment]
> @ostrich,
> 
> This package appears to require dependencies in order to install succesfully.
> 
> This PR is blocked until support for dependencies is implemented in:
> 
> * [Support for package dependencies winget-cli#163](https://github.com/microsoft/winget-cli/issues/163)

lol this is ridiculous. that issue is from 2020 and shows no signs of being addressed any time soon. guess it's back to choco for me.

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
