### PR TITLE
Update version: Vendicated.Vencord version 1.4.0

### PR DESCRIPTION
**Pull request by sharunkumar**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/191252)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334972
> 2024-11-13 13:37:19.843 [CLI ] No suitable installer found for manifest Discord.Discord with version 1.0.9170

Automated error analysis suggests -1978334972 may mean This package has a dependency missing from your system.

(Automated response - build 897.)

**Comment by stephengillie** [comment]
Hi @sharunkumar,

It appears that the installer has an interactive compoent. Is there an installer switch to bypass this?
image

**Comment by sharunkumar** [comment]
> Hi @sharunkumar,
> 
> It appears that the installer has an interactive compoent. Is there an installer switch to bypass this? image

Looks like the switches are available: https://github.com/sharunkumar/winget-pkgs/blob/1e016505bf24c57ca0ffee5831cebf719e7e146c/manifests/v/Vendicated/Vencord/1.4.0/Vendicated.Vencord.installer.yaml#L7-L11

not sure why the silent install fails 🤔

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue
[Policy] Interactive-Only-Installer

**Pull request closed without merging**
