### PR TITLE
New version: Unity.Unity.6000.Android version 6000.0.11f1

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#6684](https://github.com/SpecterShell/Dumplings/actions/runs/9994002544).

<details>

<summary>Log</summary>

````
Updated: 6000.0.10f1 → 6000.0.11f1
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
Pull request created: New version: Unity.Unity.6000 version 6000.0.11f1 - https://github.com/microsoft/winget-pkgs/pull/163619
Handling Unity.Unity.6000.Android...
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/163620)

### CODE REVIEW

**Comment by stephengillie** [comment]
- Depends on https://github.com/microsoft/winget-pkgs/pull/163619

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 887.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334960
> 2024-07-22 14:23:16.440 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFE42BBC11F: (caller: 00007FFE42948D6F) LogHr(1) tid(19c8) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFE42AC2B08: (caller: 00007FFE42B6BC20) Exception(1) tid(19c8) 8A15005E ] 
> 2024-07-22 14:23:27.333 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFE28F4C11F: (caller: 00007FFE28CD8D6F) LogHr(1) tid(15d0) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFE28E52B08: (caller: 00007FFE28EFBC20) Exception(1) tid(15d0) 8A15005E ] 
> 2024-07-22 14:40:51.995 [CLI ] ShellExecute installer failed: 2

Automated error analysis suggests -1978334960 may mean Failed to install package dependencies.

(Automated response - build 887.)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
