### PR TITLE
added kubelogin

### PR DESCRIPTION
**Pull request by weinong**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/83157)

### CODE REVIEW

**Comment by weinong** [comment]
The manifest version is 1.4.0 as I need to use nested portable installer. So it won't be conformed to 1.2.0 manifest. Would that be a problem?

**Comment by weinong** [comment]
marking it as Draft since this is blocked on winget 1.4 release

**Review by ItzLevvie — DISMISSED** [review]

**Comment by ItzLevvie** [comment]
@msftbot .zip

**Comment by Trenly** [comment]
[Policy] Reset Feedback

**Review by ryfu-msft — APPROVED** [review]

**Pull request merged**
