### PR TITLE
ESET.ESETEndpointAntivirus version 8.0.2028.0

### PR DESCRIPTION
**Pull request by m4ttyj**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15398)

### CODE REVIEW

**Comment by KaranKad** [comment]
Don't create same pr again and again.

**Comment by KaranKad** [comment]
Duplicate #15393

**Comment by m4ttyj** [comment]
> Don't create same pr again and again.

Hi Karan. 

Not a duplicate. two different product versions.

**Comment by KaranKad** [comment]
Oh sorry I didn't check properly.

**Comment by m4ttyj** [comment]
> Oh sorry I didn't check properly.

NP. Can you separate or should I re-issue?

**Comment by KaranKad** [comment]
It's fine checking is still going on.

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
