### PR TITLE
realsast.FlyingCube version 1.0

### PR DESCRIPTION
**Pull request by sastofficial**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/38669)

### CODE REVIEW

**Comment by Trenly** [comment]
Github isn't letting me leave suggestions in a review, giving a 500 error;

Please change `Publisher:` to be `Supergames` to match control panel
Please provide a better `ShortDescription` or move what you currently have in the description to the short description

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/38669#issuecomment-999646552

**Comment by sastofficial** [comment]
> Github isn't letting me leave suggestions in a review, giving a 500 error;
> 
> Please change `Publisher:` to be `Supergames` to match control panel Please provide a better `ShortDescription` or move what you currently have in the description to the short description

how to i upload the edited file?

**Comment by Trenly** [comment]
> > Github isn't letting me leave suggestions in a review, giving a 500 error;
> > Please change `Publisher:` to be `Supergames` to match control panel Please provide a better `ShortDescription` or move what you currently have in the description to the short description
> 
> how do i upload the edited file?

You just push a commit onto the branch. If you can't figure out how to upload it, you can go to the files tab and press `.` to open the online editor

**Comment by sastofficial** [comment]
> > > Github isn't letting me leave suggestions in a review, giving a 500 error;
> > > Please change `Publisher:` to be `Supergames` to match control panel Please provide a better `ShortDescription` or move what you currently have in the description to the short description
> > 
> > 
> > how do i upload the edited file?
> 
> You just push a commit onto the branch. If you can't figure out how to upload it, you can go to the files tab and press `.` to open the online editor

i already have the files on my pc how to i commit it. period works but i wanna commit it. also the edit button is grayed out. https://i.imgur.com/CQf0exO.png

**Comment by Trenly** [comment]
> i already have the files on my pc how to i commit it. period works but i wanna commit it. also the edit button is grayed out. https://i.imgur.com/CQf0exO.png

I don't really know how to explain it well, since it depends on your exact setup. Whether you're using github dekstop, github cli, git bash, it will be different for each of them. It will also be different if you're using an IDE as compared to editing files manually.   I know that you can drag and drop files into the online editor, so if you open the online editor, then drag your updated file into the editor, replacing the one that is there, that might work either.

The best guidance I can give is to do a google search with your exact setup to learn how to use git in order to be able to push commits directly to files on PRs

**Comment by sastofficial** [comment]
> > i already have the files on my pc how to i commit it. period works but i wanna commit it. also the edit button is grayed out. https://i.imgur.com/CQf0exO.png
> 
> I don't really know how to explain it well, since it depends on your exact setup. Whether you're using github dekstop, github cli, git bash, it will be different for each of them. It will also be different if you're using an IDE as compared to editing files manually. I know that you can drag and drop files into the online editor, so if you open the online editor, then drag your updated file into the editor, replacing the one that is there, that might work either.
> 
> The best guidance I can give is to do a google search with your exact setup to learn how to use git in order to be able to push commits directly to files on PRs

the web editor just gives me an error https://i.imgur.com/eqaBAiy.png

**Comment by Trenly** [comment]
> the web editor just gives me an error https://i.imgur.com/eqaBAiy.png

That explains why it wouldn't let me comment. It appears that somehow the branch associated with the pull request got deleted. You would have to restore the branch before you're able to use the editor

**Comment by sastofficial** [comment]
> > the web editor just gives me an error https://i.imgur.com/eqaBAiy.png
> 
> That explains why it wouldn't let me comment. It appears that somehow the branch associated with the pull request got deleted. You would have to restore the branch before you're able to use the editor

how do i do that

**Comment by Trenly** [comment]
> how do i do that
I would imagine there's a button somewhere on this page that says "Restore Branch"

If not, then again, it will be dependent on your exact setup

**Comment by sastofficial** [comment]
> > how do i do that
> > I would imagine there's a button somewhere on this page that says "Restore Branch"
> 
> If not, then again, it will be dependent on your exact setup

im using the website. what is a branch and where do i restore it

**Comment by Trenly** [comment]
> > > how do i do that
> > > I would imagine there's a button somewhere on this page that says "Restore Branch"
> > 
> > 
> > If not, then again, it will be dependent on your exact setup
> 
> im using the website. what is a branch and where do i restore it

In developer terms, a branch is a specific version of the code that has a reference.

 Think of all of github like a tree. You have one root, that is the main repository. In this case, the root is [microsoft/winget-pkgs](/microsoft/winget-pkgs). In order to contribute code to the root repository, you have to climb up the trunk of the tree and make a fork. A fork is just your own copy of the code that you have permission to modify. Since you can't modify the root, you are always working out of your own fork. Inside your fork, you have what are called branches. A branch is just a way of separating changes. You could have one branch where you change files `a`, `b`, and `c`, then decide you want to work on a different thing, switch branches, and then modify files `d`, `e`, and `f`.  This way, you can have multiple different versions of the code and be changing only specific files at a time.

**Comment by sastofficial** [comment]
> > > > how do i do that
> > > > I would imagine there's a button somewhere on this page that says "Restore Branch"
> > > 
> > > 
> > > If not, then again, it will be dependent on your exact setup
> > 
> > 
> > im using the website. what is a branch and where do i restore it
> 
> In developer terms, a branch is a specific version of the code that has a reference.
> 
> Think of all of github like a tree. You have one root, that is the main repository. In this case, the root is [microsoft/winget-pkgs](/microsoft/winget-pkgs). In order to contribute code to the root repository, you have to climb up the trunk of the tree and make a fork. A fork is just your own copy of the code that you have permission to modify. Since you can't modify the root, you are always working out of your own fork. Inside your fork, you have what are called branches. A branch is just a way of separating changes. You could have one branch where you change files `a`, `b`, and `c`, then decide you want to work on a different thing, switch branches, and then modify files `d`, `e`, and `f`. This way, you can have multiple different versions of the code and be changing only specific files at a time.

oh shit i deleted my fork cus i thouight i was a accidental fork. do i need to reupload this entire pull request to get it back or can i make a new fork and then link it to this pull?

**Comment by Trenly** [comment]
> > > > > how do i do that
> > > > > I would imagine there's a button somewhere on this page that says "Restore Branch"
> > > > 
> > > > 
> > > > If not, then again, it will be dependent on your exact setup
> > > 
> > > 
> > > im using the website. what is a branch and where do i restore it
> > 
> > 
> > In developer terms, a branch is a specific version of the code that has a reference.
> > Think of all of github like a tree. You have one root, that is the main repository. In this case, the root is [microsoft/winget-pkgs](/microsoft/winget-pkgs). In order to contribute code to the root repository, you have to climb up the trunk of the tree and make a fork. A fork is just your own copy of the code that you have permission to modify. Since you can't modify the root, you are always working out of your own fork. Inside your fork, you have what are called branches. A branch is just a way of separating changes. You could have one branch where you change files `a`, `b`, and `c`, then decide you want to work on a different thing, switch branches, and then modify files `d`, `e`, and `f`. This way, you can have multiple different versions of the code and be changing only specific files at a time.
> 
> oh shit i deleted my fork cus i thouight i was a accidental fork. do i need to reupload this entire pull request to get it back or can i make a new fork and then link it to this pull?

Pull requests are tied directly to the fork by their refs, so you wouldn't be able to link a new fork to this pull.
I already created a new PR though with the changes that had been requested, so you shouldn't need to worry about it at all

**Comment by ChuckFerring** [comment]
Is this pull request still necessary now that #38684 has been created?  If not, please close.

**Comment by sastofficial** [comment]
> Is this pull request still necessary now that #38684 has been created? If not, please close.

ok :)

**Pull request closed without merging**
