### PR TITLE
New package: azurejoga.aurora,windowsoptimizer version 9

### PR DESCRIPTION
**Pull request by azurejoga**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131947)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 
> 2023-12-27 14:38:56.916 [FAIL] Installer failed security check. Url: https://github.com/azurejoga/Aurora-Windows-Optimizer/releases/download/aurora9/aurora-install.exe Result: 0x80004005

(Automated response - build 508.)

**Comment by stephengillie** [comment]
Hi @azurejoga,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 509.)

**Comment by azurejoga** [comment]
Hello
@stephengillie 
I can guarantee that my application is completely safe however the installer seems to trigger something from Windows Defender however my application has md5 GPG keys and others 
I'm using Anthem Script Studio to make the installer.

**Comment by azurejoga** [comment]
Hello
@stephengillie 
I can guarantee that my application is completely safe however the installer seems to trigger something from Windows Defender however my application has md5 GPG keys and others 
I'm using Anthem Script Studio to make the installer.

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 10:30:52 AM: 2024-01-03 10:30:52.352 [FAIL] Installer failed security check. Url: https://github.com/azurejoga/Aurora-Windows-Optimizer/releases/download/aurora9/aurora-install.exe Result: 0x80004005

(Automated response - build 513.)

**Comment by stephengillie** [comment]
Hi @azurejoga,

Unfortunately, we can't accept manifests for software packages that don't pass a Defender scan. The cause of the issue will have to be resolved before we can accept this manifest. Please consider these suggestions when working to resolve:

- Consider virus scanning your systems, just to be sure. 
  - If you have a periodic or scheduled virus scan, double-check that it's running frequently. 
- Be very careful about using Internet icon generation or similar sites to make or modify icons or images, as this is a common virus insertion vector - adding virus code in the file after the image data. 
- Double check the software used to package these, and make sure it came from an official source - as unofficial download sites are sometimes another common vector for injecting viruses into legitimate software. 
- Double-check plugins and modules, as these have been an attack vector in the past.

**Pull request closed without merging**
