### PR TITLE
New Version: tsl0922.ttyd version 1.7.7

### PR DESCRIPTION
**Pull request by og-mrk**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/147882)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 876.)

**Comment by og-mrk** [comment]
... interesting, there's a validation error, but all the tests have passed successfully. Any reason why this could happen?

**Comment by stephengillie** [comment]
> ##[warning] Validation concluded that this task needs to go to manual review.

 It's not quite an error, not quite a warning, and not quite a failure. The installer provided a zero exit code, but this wasn't enough to pass. I'm not sure of the cause, but it's not uncommon.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
