### PR TITLE
[Zip][Portable] New package: Sass.DartSass.Embedded version 1.57.1

### PR DESCRIPTION
**Pull request by SpecterShell**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/92419)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by SpecterShell** [comment]
Hold

**Comment by Trenly** [comment]
@msftbot zip

**Comment by Trenly** [comment]
[Policy] Reset Feedback

**Comment by stephengillie** [comment]
Hi @SpecterShell,

In a sandbox, this package installed normally, but when launched opened an unresponsive console window. Is this expected?
image

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @SpecterShell,

Feel free to revert this PR to Ready for review, and it should automatically merge.

**Pull request merged**
