### PR TITLE
Modify: HermannSchinagl.LinkShellExtension version 3.9.3.5

### PR DESCRIPTION
**Pull request by SpecterShell**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/49982)

### CODE REVIEW

**Comment by denelon** [comment]
@OfficialEsco do we know which runtime is missing here? I do see one in the manifest. If that's the correct one, this manifest is good, it provides a bad user experience until we can inform the user of the dependency (crawl maybe in 1.3 client). What are your thoughts? 

Missing dependencies makes me sad 😞 I'm hoping to get the basics for installing dependencies from the same source in the 1.4 client.

**Comment by denelon** [comment]
If people are using this package. I'm willing to grandfather it in.

**Comment by OfficialEsco** [comment]
> do we know which runtime is missing here? I do see one in the manifest. If that's the correct one, this manifest is good

It works with VC++2015-2019 or 2022 which most PCs already have installed

> it provides a bad user experience until we can inform the user of the dependency (crawl maybe in 1.3 client). What are your thoughts?

I think we already have a few in the repo, we might see more complains when importing is more used

> Missing dependencies makes me sad 😞 I'm hoping to get the basics for installing dependencies from the same source in the 1.4 client.

So in 1.3 we're just getting dependencies as experimental? Weelll, its missing features so probably safest ye

> If people are using this package. I'm willing to grandfather it in.

@SpecterShell should probably answer this one, but i think since it already got into the repo its best to update the metadata to the correct ones OR Remove it until its supported

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
just out of curiosity

**Comment by denelon** [comment]
It looks like the dependency is already added to the manifest, and since there is only one dependency, it would work for clients with the experimental dependency support enabled. I don't see too many issues with approving this one unless someone has a strong reason to want to exclude it from the community repository.

**Review by OfficialEsco — APPROVED** [review]
Its already in the repo, SpecterShell is just changing it from a Singleton to Multi Manifest

**Comment by SpecterShell** [comment]
Destale

**Comment by denelon** [comment]
I'm thinking about going ahead and letting this one in. Can someone who has the experimental dependencies share a screenshot or output of it being successfully installed where winget installs the dependency?

**Comment by OfficialEsco** [comment]
image

**Review by ItzLevvie — APPROVED** [review]

**Review by denelon — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
