### PR TITLE
New version: Avidemux.Avidemux version 2.8.1.220917

### PR DESCRIPTION
**Pull request by superusercode**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/107357)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by stephengillie** [comment]
This package has an interesting way of displaying its installer switches: From `--help`: 
```
Usage: C:\Users\User\AppData\Local\Temp\WinGet\Avidemux.Avidemux.2.8.1.220917\Avidemux_2.8.1%20VC%2B%2B%2064bits.exe [options] Key=Value

Options:
  -?, -h, --help                           Displays this help.
  --version                                Displays version information.
  --framework-version                      Displays the version of the Qt
                                           Installer Framework.
  -v, --verbose                            Verbose mode. Prints out more
                                           information.
  --proxy                                  Use system proxy on Windows and
                                           Linux. This option has no effect on
                                           OS X.
  --no-proxy                               Do not use system proxy.
  --script <file>                          Execute the script given as
                                           argument.
  --checkupdates                           Check for updates and return an XML
                                           description.
  --updater                                Start application in updater mode.
  --manage-packages                        Start application in package manager
                                           mode.
  --no-force-installations                 Allow deselecting components that
                                           are marked as forced.
  --show-virtual-components                Show virtual components in installer
                                           and package manager.
  --logging-rules <rules>                  Enables logging according to passed
                                           rules. Comma separated logging rules
                                           have the following syntax:
                                           loggingCategory=true/false. Passing
                                           empty logging rules enables all
                                           logging categories. The following
                                           rules enable a single category:
                                           ifw.*=false,ifw.category=true The
                                           following logging categories are
                                           available:
                                           ifw.componentChecker
                                           ifw.resources
                                           ifw.translations
                                           ifw.network
  --create-local-repository                Create a local repository inside the
                                           installation directory. This option
                                           has no effect on online installers.
  --addRepository <URI,...>                Add a local or remote repository to
                                           the list of user defined
                                           repositories.
  --addTempRepository <URI,...>            Add a local or remote repository to
                                           the list of temporary available
                                           repositories.
  --setTempRepository <URI,...>            Set a local or remote repository as
                                           temporary repository, it is the only
                                           one used during fetch.
                                           Note: URI must be prefixed with the
                                           protocol, i.e. file:///, https://,
                                           http:// or ftp://.
  --startserver <mode,socketname,key>      Starts the application as headless
                                           process waiting for commands to
                                           execute. Mode can be DEBUG or
                                           PRODUCTION. In DEBUG mode, the option
                                           values can be omitted.Note: The
                                           server will not shutdown on his own,
                                           you need to quit the process by hand.
  --startclient <socketname,key>           Starts the application to debug the
                                           client-server communication. If a
                                           value is omitted, the client will use
                                           a default instead. Note: The server
                                           process is not started by the client
                                           application in that case, you need to
                                           start it on your own.
  --installCompressedRepository <URI,...>  Installs QBSP or 7z file. The QBSP
                                           (Board Support Package) file must be
                                           a .7z file which contains a valid
                                           repository.
  --silentUpdate                           Updates all packages silently.
  --platform <plugin>                      Use the specified platform plugin.
  --squish-port <port number>              Give a port where Squish can connect
                                           to. If no port is given, default port
                                           11233 is used. Note: To enable Squish
                                           support you first need to build IFW
                                           with SQUISH_PATH parameter where
                                           SQUISH_PATH is pointing to your
                                           Squish installation folder:
                                           <path_to_qt>/bin/qmake -r
                                           SQUISH_PATH=<pat_to_squish>

Arguments:
  Key=Value                                Key Value pair to be set.



```

**Comment by stephengillie** [comment]
> Additionally, chocolatey supposedly gets a clean install out of it with `/S` per https://community.chocolatey.org/packages/avidemux#files image

I do not know why the switch appears to work there but not here.  We could get a Chocolatey expert to help us understand.

**Comment by luzpaz** [comment]
Can someone explain why this ticket was closed ?

**Comment by luzpaz** [comment]
bump

**Pull request closed without merging**
