### PR TITLE
Revert "New version: Aserto.Topaz version 0.30.32"

### PR DESCRIPTION
**Pull request by gertd**
Reverts microsoft/winget-pkgs#140152
Submitter is not the owner of the software but an automated bot acccount.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140266)

### CODE REVIEW

**Comment by Trenly** [comment]
@gertd - Why revert? Won't your other pull request achieve the same thing?
* #140264

**Comment by stephengillie** [comment]
InstallerUrl contains Manifest version instead of PR version:
  InstallerUrl: https://github.com/aserto-dev/topaz/releases/download/v0.30.32/topaz_windows_x86_64.zip

(Automated message - build 776)

**Comment by stephengillie** [comment]
[Policy] Needs-Author-Feedback

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
@gert I've added you as the authorized uploader. (This used to be in Auth.csv, but it's being combined with several other data files into one new data file.) This will prevent others from adding manifests for this package.

**Pull request merged**
