### PR TITLE
New package: Bithack.Principia version 2024.02.29

### PR DESCRIPTION
**Pull request by griffi-gh**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/142091)

### CODE REVIEW

**Comment by griffi-gh** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files\Principia\principia.exe returned exit code: 1

(Automated response - build 861.)

**Comment by griffi-gh** [comment]
(Pretty sure this is expected. The latest version has a bug that crashes the game instead of displaying an error screen on unsupported systems)

**Comment by griffi-gh** [comment]
> I tested this in my environment and although the application installs correctly, it just doesn't launch at all. My environment is a clean install of Windows 10 with nothing else on it
> 
> image

Yeah, this is a known regression in the latest version of the game.    
The game segfaults while initializing SDL2 with the default software renderer. (and I assume the vm doesn't support hardware acceleration)  
  
It's *supposed to* show an error screen and exit, but due to a regression in SDL2, it segfaults before it could do that.  
  
It should run in a VM with the Mesa software renderer (copy mesa3d's opengl32.dll to the ganme install directory)

...or on any "real" gpu that supports at least OpenGL 1.1.

**Comment by Trenly** [comment]
[Policy] Hardware

**Comment by griffi-gh** [comment]
so, no games or any other applications rhat require hardware acceleration are allowed on the official winget repo until that gets implemented?

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/12906

**Comment by denelon** [comment]
Supporting custom hardware in validation is "Not Planned".
* https://github.com/microsoft/winget-pkgs/issues/199504

**Comment by griffi-gh** [comment]
@denelon no custom hardware is required, just a gpu or an  opengl driver (this would be required by any other game)
#12906 is still open (and this is what this is blocked on) so why close this?
Also there are some other applications that rely on OpenGL/Vulkan and are just given exceptions during validatiob (notably, iirc Ryujinx), why doesnt this apply here?

**Comment by denelon** [comment]
Custom hardware is a blanket to represent any specific hardware requirement. A required GPU is just one example of hardware that might be required for a package to install/run. There were several other packages blocked by custom hardware like SSDs, UPSs, etc.

Is there a package in the community repository that supports OpenGL that could be specified as a dependency so the package would install and run in our validation infrastructure? I created the OpenGL issue in the hopes that we would eventually have a package or a means of adding OpenGL to the validation infrastructure, but I never came across one.

**Comment by denelon** [comment]
I'd love to be able to extend the repository as much as possible given the constraints we have on our validation policies. I've gotten used to WinGet for all the things, and I'd love to have everything, but it's just not feasible at this time.

**Pull request closed without merging**
