### PR TITLE
New version: MartiCliment.UniGetUI version 3.1.2

### PR DESCRIPTION
**Pull request by marticliment**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/184469)

### CODE REVIEW

**Comment by marticliment** [comment]
is it normal for Azure pipelines to take 1h:30 on installer validation before failing?

**Comment by marticliment** [comment]
Failed again after 1h:30. 
Didn't it take around 15/20 minutes before?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334972
> 2024-10-20 01:40:08.002 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x64 with version 14.40.33816.0

Automated error analysis suggests -1978334972 may mean This package has a dependency missing from your system.

(Automated response - build 897.)

**Comment by stephengillie** [comment]
> Failed again after 1h:30. 
Didn't it take around 15/20 minutes before?

Unfortunately, I have neither good statistics of previous runs, nor a good answer for why it could take longer.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
