### PR TITLE
Fix: Updated Files package

### PR DESCRIPTION
**Pull request by yair100**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

- Removed version of Files linking to the wrong installer and publisher.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/93758)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @yaira2,

Why should we remove these? Is there a problem with the installer?

**Comment by yaira2** [comment]
It's technically the right installer but it's preferable to use the one from the cdn. The main issue here is that it's published under the wrong name.

**Comment by yaira2** [comment]
@stephengillie instead of removing, I moved to the correct publisher and edited the meta data.

**Comment by stephengillie** [comment]
Validation is failing with the error:
> ##[error] Addition and deletion only permitted in the same package directory.

But this PR appears to only modify one manifest.

**Comment by yaira2** [comment]
If the manifest is valid, perhaps the PR can be merged as is. The only other way I think is to remove the package and add it back separately.

**Review by mdanish-kh — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/93758#issuecomment-1385969406 Correct.

Please split this PR in two. One for deletion of `YairAichenbaum.Files` and the other for addition of `FilesCommunity.Files`

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
