### PR TITLE
Ultimaker.Cura version 4.10.0

### PR DESCRIPTION
**Pull request by Dr-Ari-Gami**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23391)

### CODE REVIEW

**Comment by quhxl** [comment]
#21224
#20759
#20123
#19798

**Comment by denelon** [comment]
@quhxl Do we know if anybody has submitted an Issue at Ultimaker Cura to see if they can suppress UI for the driver installation?

**Comment by Dr-Ari-Gami** [comment]
That's why it validated on my end. The drivers were already installed.

**Comment by quhxl** [comment]
@denelon
Ultimaker/Cura#10091
Ultimaker/Cura#1245

**Comment by denelon** [comment]
@quhxl Thanks I added my 👍 

@Dr-Ari-Gami, @vedantmgoyal2009, @KaranKad
I submitted this a while back too:
https://github.com/Ultimaker/Cura/issues/8439

It could also use a thumbs up if you have another thumb 😊

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
