### PR TITLE
New version: SomePythonThings.WingetUIStore.Pre-release version 3.1.1-beta0

### PR DESCRIPTION
**Pull request by schembriaiden**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161738)

### CODE REVIEW

**Comment by vikingnope** [comment]
Usual issue, can be merged

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code 1

(Automated response - build 886.)

**Comment by vikingnope** [comment]
https://github.com/marticliment/UniGetUI/releases/download/3.1.1-beta0/UniGetUI.Installer.exe

**Comment by vikingnope** [comment]
Normal behaviour, can be merged

**Comment by vikingnope** [comment]
Newer version so closing

**Pull request closed without merging**
