### PR TITLE
Add IceChat

### PR DESCRIPTION
**Pull request by ath0mas**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1001)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
This app has a dependency on the ,NET framework.  And though I try to install it, I cannot get it to successfully install.  Is there a way to add the framework to your installation package?

**Comment by ath0mas** [comment]
@KevinLaMS my PR but not my package :/
so, any feedback on that _please_ @icechat ?

**Comment by icechat** [comment]
There is no installer yet for IceChat 9.50

**Comment by ath0mas** [comment]
trying to add version 9.22 here,
so you say it should be fixed for future 9.50 only?
nothing more to do than to close this PR about 9.22 for now?

**Comment by icechat** [comment]
The installer for 9.22 will install .NET 3.5 automatically. 
9.50 has no installer as of yet, and it requires .NET 4.5.2 which comes by default with Windows 10.

**Comment by ath0mas** [comment]
ok thanks @icechat !
@KevinLaMS so .NET 3.5 should be installed automatically it seems

**Comment by icechat** [comment]
It is not an MSI installer, but an installer made by InnoSetup. Could this be a problem?

**Comment by ath0mas** [comment]
Inno is supported by Winget, and used by many other packages here

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
