### PR TITLE
Update Spotify 1.1.32.618

### PR DESCRIPTION
**Pull request by mehulrao**
Add YAML manifest for Spotify 1.1.32.618

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1004)

### CODE REVIEW

**Comment by DanaBear** [comment]
@mehulrao How did you make this a binary file? And why? Is it safer?

**Comment by mehulrao** [comment]
@DanaBear I'm not sure why github thinks its a binary file. It is just a regular YAML.

**Comment by DanaBear** [comment]
@mehulrao Ahh, I see now. Thank you! :)

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
