### PR TITLE
Remove unnecessary DisplayVersion from GitExtensionsTeam.GitExtensions version 4.0.0.15569

### PR DESCRIPTION
**Pull request by mdanish-kh**
Issue https://www.github.com/microsoft/winget-pkgs/issues/138520 describes scenarios where DisplayVersion should not be used. This PR removes unnecessary DisplayVersion from the manifest file.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/191504)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334972
> 2024-11-14 05:38:42.927 [CLI ] No suitable installer found for manifest Microsoft.DotNet.DesktopRuntime.6 with version 6.0.36
> 2024-11-14 05:38:43.193 [CLI ] No suitable installer found for manifest Git.Git with version 2.47.0.2

Automated error analysis suggests -1978334972 may mean This package has a dependency missing from your system.

(Automated response - build 897.)

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://github.com/gitextensions/gitextensions/releases/download/v4/GitExtensions-4.0.0-cba315df5.msi 
Status Code: 200

(Automated message - build 897)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://github.com/gitextensions/gitextensions/releases/download/v4/GitExtensions-4.0.0-cba315df5.msi 
Status Code: 200

(Automated message - build 897)

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://github.com/gitextensions/gitextensions/releases/download/v4/GitExtensions-4.0.0-cba315df5.msi 
Status Code: 200

(Automated message - build 898)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://github.com/gitextensions/gitextensions/releases/download/v4/GitExtensions-4.0.0-cba315df5.msi 
Status Code: 200

(Automated message - build 899)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://github.com/gitextensions/gitextensions/releases/download/v4/GitExtensions-4.0.0-cba315df5.msi 
Status Code: 200

(Automated message - build 899)

**Comment by stephengillie** [comment]
URL: https://github.com/gitextensions/gitextensions/releases/download/v4/GitExtensions-4.0.0-cba315df5.msi 
Status Code: 200

(Automated message - build 902)

**Comment by stephengillie** [comment]
URL: https://github.com/gitextensions/gitextensions/releases/download/v4/GitExtensions-4.0.0-cba315df5.msi 
Status Code: 200

(Automated message - build 903)

**Comment by stephengillie** [comment]
URL: https://github.com/gitextensions/gitextensions/releases/download/v4/GitExtensions-4.0.0-cba315df5.msi 
Status Code: 200

(Automated message - build 904)

**Comment by stephengillie** [comment]
URL: https://github.com/gitextensions/gitextensions/releases/download/v4/GitExtensions-4.0.0-cba315df5.msi 
Status Code: 200

(Automated message - build 904)

**Pull request merged**
