### PR TITLE
New version: BrettMayson.HEMTT version 1.11.0

### PR DESCRIPTION
**Pull request by BrettMayson**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137692)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @BrettMayson,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 695.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-02 23:45:54.967 [FAIL] WindowsPackageManager.dll!00007FF98C45BDD2: ReturnHr(1) tid(12a8) 80190193 Forbidden (403).     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\HttpStream\HttpClientWrapper.cpp(50)\WindowsPackageManager.dll!00007FF98C44203A: (caller: 00007FF98C327669) Exception(1) tid(12a8) 80190193 Forbidden (403). 2024-02-02 23:45:54.967 [FAIL] WindowsPackageManager.dll!00007FF98C2E3AF1: LogHr(1) tid(12a8) 80190193 Forbidden (403). 2024-02-02 23:45:54.968 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(53)\WindowsPackageManager.dll!00007FF98C467301: (caller: 00007FF98C3304FE) LogHr(2) tid(12a8) 80190193 Forbidden (403).     Msg:[winrt::hresult_error: Forbidden (403).]  2024-02-02 23:45:54.968 [REPO] Source add/update failed, waiting a bit and retrying: winget 2024-02-02 23:45:56.994 [FAIL] WindowsPackageManager.dll!00007FF98C45BDD2: ReturnHr(2) tid(12a8) 80190193 Forbidden (403).     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\HttpStream\HttpClientWrapper.cpp(50)\WindowsPackageManager.dll!00007FF98C44203A: (caller: 00007FF98C327669) Exception(2) tid(12a8) 80190193 Forbidden (403). 2024-02-02 23:45:56.994 [FAIL] WindowsPackageManager.dll!00007FF98C2E3AF1: LogHr(3) tid(12a8) 80190193 Forbidden (403). 2024-02-02 23:45:56.994 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(540)\WindowsPackageManager.dll!00007FF98C4668E3: (caller: 00007FF98C228B8D) LogHr(4) tid(12a8) 80190193 Forbidden (403). 2024-02-02 23:45:56.994 [REPO] Failed to update source: winget 2024-02-02 23:45:57.221 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(564)\WindowsPackageManager.dll!00007FF98C466B53: (caller: 00007FF98C228B8D) LogHr(5) tid(12a8) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF98C379298: (caller: 00007FF98C4324F9) Exception(3) tid(12a8) 8A15005E ]  2024-02-02 23:45:57.221 [REPO] Failed to open available source: msstore 2024-02-02 23:45:57.234 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(205)\WindowsPackageManager.dll!00007FF98C34453A: (caller: 00007FF98C330B9E) Exception(4) tid(12a8) 8A15000F  2024-02-02 23:45:57.234 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(564)\WindowsPackageManager.dll!00007FF98C466B53: (caller: 00007FF98C228B8D) LogHr(6) tid(12a8) 8A15000F     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(205)\WindowsPackageManager.dll!00007FF98C34453A: (caller: 00007FF98C330B9E) Exception(4) tid(12a8) 8A15000F ]  2024-02-02 23:45:57.234 [REPO] Failed to open available source: winget 2024-02-02 23:45:57.234 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(571)\WindowsPackageManager.dll!00007FF98C3310DB: (caller: 00007FF98C228B8D) Exception(5) tid(12a8) 8A15004B  2024-02-02 23:46:16.235 [FAIL] Installer failed security check. Url: https://github.com/BrettMayson/HEMTT/releases/download/v1.11.0/windows-x64.zip Result: 0x80004005

(Automated response - build 695.)

**Comment by BrettMayson** [comment]
This version adds a feature that checks a git repo for an update version of bundled files. That would be the only thing I suspect it'd be picking up that was added in the latest version.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 703.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
