### PR TITLE
Added SQL Server 2019 LocalDB 15.0.2000.5

### PR DESCRIPTION
**Pull request by sootysec**
Signed-off-by: Daniel Sutton <daniel@ducksecops.uk>

- [x ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/29334)

### CODE REVIEW

**Comment by ducksecops** [comment]
Requires the installation of Microsoft.VC++2015-2019Redist-x64 first or the installation fails to start the service correctly. Added the dependency but my understanding this functionality is not working in terms of installing in advance of the actual package install.

**Comment by ducksecops** [comment]
@jedieaston quick question, is it possible to get these sort of packages added when it has a dependency on another package which results in a hard fail?

**Comment by jedieaston** [comment]
Not at the moment, unfortuately. Since the client can't install dependencies yet we don't merge these (since on a clean Windows install, it wouldn't work). 

Some manifests list dependencies anyway for testing the schema, but it's just for metadata purposes.

**Comment by ducksecops** [comment]
Closing as unable to resolve without dependency

**Pull request closed without merging**
