### PR TITLE
Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\4.13

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114106&drop=dogfoodAlpha

### CODE REVIEW

**Review by ImJoakim — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
image

**Pull request merged**
