### PR TITLE
New version: Fossil.Fossil version 2.23

### PR DESCRIPTION
**Pull request by OfficialEsco**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/145592)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Fossil.Fossil__DefaultSource\fossil.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\fossil.exe returned exit code: 1
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Packages\Fossil.Fossil__DefaultSource\fossil.exe returned exit code: 1
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\fossil.exe returned exit code: 1

(Automated response - build 870.)

**Comment by OfficialEsco** [comment]
```
Enter a pull request number: 145592

Manifest validation succeeded.
Found Fossil [Fossil.Fossil] Version 2.23
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://fossil-scm.org/home/uv/fossil-w64-2.23.zip
  ██████████████████████████████  3.22 MB / 3.22 MB
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "fossil"
Path environment variable modified; restart your shell to use the new value.
Successfully installed

Name          : Fossil
Publisher     : D. Richard Hipp
Version       : 2.23
ProductCode   : Fossil.Fossil__DefaultSource
Registry Path : Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\Fossil.Fossil__DefaultSource
Uninstall     : winget uninstall --id "Fossil.Fossil__DefaultSource"

Press any key to continue . . .
```
image

Nothing does indeed happen when you execute fossil.exe

**Comment by stephengillie** [comment]
Yes - 

- Many applications have a non-zero exit code, for one reason or another. Especially CLI applications when run without an argument. These are so common that I've had an auto-waiver system to keep them going, and I need to set it up again. 
- SmartScreen prompts aren't blockers. They're disabled in the pipeline and I click through them in my VMs.

**Comment by OfficialEsco** [comment]
The exe is not supposed to be launched, use fossil in cmd.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
