### PR TITLE
Add HeidiSQL

### PR DESCRIPTION
**Pull request by superusercode**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1583)

### CODE REVIEW

**Comment by superusercode** [comment]
getting really sick of these copy source errors

**Comment by SoftCreatR** [comment]
@superusercode Please use the full version number (11.0.0.5919) instead.

**Comment by superusercode** [comment]
@SoftCreatR done, but I find it weird that they use different version number for their github releases and the actually executables. This wasn't me shortening it but rather trying to match the github tags.

**Comment by SoftCreatR** [comment]
> @SoftCreatR done, but I find it weird that they use different version number for their github releases and the actual executables. This wasn't me shortening it but rather trying to match the github tags.

@superusercode Yeah, i know. Btw: Linking from Majorgeeks won't work. The hashes generated are temporary.

**Comment by superusercode** [comment]
Until the copy error is fixed I will just use the official URL since I cannot find a reputable mirror

**Comment by SoftCreatR** [comment]
@superusercode I've created another PR: https://github.com/microsoft/winget-pkgs/pull/1610

As you can see, it uses a proprietary download URL. This is just a proxy around #91. It downloads the given file from the given URL and returns it to the client in a "proper" way.

Looks like it's working as expected, so i'll try to take over some of the failing applications.

**Comment by SoftCreatR** [comment]
Obsolete by https://github.com/microsoft/winget-pkgs/pull/1610

**Pull request closed without merging**
