### PR TITLE
New version: DuckStudio.GitHubLabelsManager version v1.3

### PR DESCRIPTION
**Pull request by DuckDuckStudio**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?

> I can install it manual.

- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

> [!NOTE]
> To show version: `glm config --version`
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/173045)

### CODE REVIEW

**Review by fjwxzde — APPROVED** [review]

**Comment by DuckDuckStudio** [comment]
> === manifests\d\DuckStudio\GitHubLabelsManager\v1.3 ===
> 
> Missing Properties value based on version v1.2: 
> 
> Scope
> 
> ElevationRequirement

> Scope

My program can be installed at user/global scope

> ElevationRequirement

I'm not sure why the last version had this.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files (x86)\GitHub_Labels_Manager\glm.exe returned exit code: 2

(Automated response - build 895.)

**Comment by stephengillie** [comment]
> > Missing Properties value based on version v1.2:
> 
> > Scope
> 
> My program can be installed at user/global scope
> 
> > ElevationRequirement
> 
> I'm not sure why the last (之前的) version had this.

I usually assume that there is a good reason for properties to be missing, and that I'm unaware of it.

**Review by stephengillie — APPROVED** [review]

**Comment by DuckDuckStudio** [comment]
> I usually assume that there is a good reason for properties to be missing, and that I'm unaware of it.

All of my manifests are created using `yamlCreation.ps1` .
And I press Enter when I encounter `Scope`; I not encounter `ElevationRequirement`.
So I have no idea why properties are missing...

**Pull request merged**
