### PR TITLE
Move Geekbench 2 and 3 to their correct location

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/108880)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
@upintheairsheep It look like the Azure Pipelines does not run due to the manifests/p/PrimateLabs/Geekbench/winget-pkgs.code-workspace. Can you pls delete the file?

**Comment by BrandonWanHuanSheng** [comment]
I think you need to seperate the PR.
One or more errors occurred. (The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.) The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.

**Comment by upintheairsheep** [comment]
> I think you need to seperate the PR.
> One or more errors occurred. (The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.) The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.

It’s the fact that the names in the manifest are not changed

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
You'll have to do this in separate pull requests. It'll be 4 pull requests in total.

1) Removing `PrimateLabs.Geekbench2`
2) Removing `PrimateLabs.Geekbench3`
3) Adding `PrimateLabs.Geekbench.2`
4) Adding `PrimateLabs.Geekbench.3`

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.

These will need to be separated as described by ItzLevvie.

**Pull request closed without merging**
