### PR TITLE
Update: Tencent.qq-devtool version 0.3.2

### PR DESCRIPTION
**Pull request by Trenly**
﻿

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/71175)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
@denelon - Blocking Issue
```
2022-08-20 07:26:16.821 [CLI ] Completed installer selection.
2022-08-20 07:26:16.857 [CLI ] Caught std::exception: No mapping for the Unicode character exists in the target multi-byte code page.
```
microsoft/winget-cli#2057

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by jedieaston — APPROVED** [review]

**Comment by denelon** [comment]
I'm testing to see if a client with the fix for:
* https://github.com/microsoft/winget-cli/issues/2057

is already in the validation pipeline.

**Comment by denelon** [comment]
Not yet :(

**Comment by Trenly** [comment]
Not sure when the pipelines were last updated, but lets see if there's been any movement

@wingetbot run

**Comment by Trenly** [comment]
@msftbot blocking issue

**Review by ImJoakim — APPROVED** [review]

**Pull request merged**
