### PR TITLE
New Package: Kuwo.KuwoMusic-9.2.0.0

### PR DESCRIPTION
**Pull request by CoolPlayLin**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/110531&drop=dogfoodAlpha

### CODE REVIEW

**Comment by CoolPlayLin** [comment]
Why it scans so long time?

**Comment by CoolPlayLin** [comment]
Why it scan so long time? @stephengillie

**Comment by CoolPlayLin** [comment]
It has been scanning for more than half a day

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> ##[error] Installer https://down.kuwo.cn/mbox/kwmusic_web_6.exe 
> Scan request id: '95eceb34-de3f-4d9a-8689-f7c4db1ac849' 
> Error information: BlockingDetectionFound 
> ##[error] Result: Failed

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
