### PR TITLE
Upgrade FutureRestore GUI to 1.90

### PR DESCRIPTION
**Pull request by CoocooFroggy**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/22174)

### CODE REVIEW

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
Hey there @CoocooFroggy you need to update the Publisher which shows up in **A**dd or **R**emove **P**rograms, otherwise `winget list` and `winget upgrade` will not work as expected.
image

**Comment by CoocooFroggy** [comment]
> Hey there @CoocooFroggy you need to update the Publisher which shows up in **A**dd or **R**emove **P**rograms, otherwise `winget list` and `winget upgrade` will not work as expected.

Thanks so much!

**Comment by OfficialEsco** [comment]
Ahh i see what you did, wondered why there was 2 PRs with the same change...

You can only submit one version per PR. You are currently submitting 1.90 and 1.80.

**Comment by CoocooFroggy** [comment]
Ah got it, I'll redo the PR in a bit then

**Pull request closed without merging**
