### PR TITLE
New version: OONI.OONI-Probe version 3.9.5

### PR DESCRIPTION
**Pull request by Dvd-Znf**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150787)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 877.)

**Comment by Dvd-Znf** [comment]
Previous version: #139248 also had an unattended error even though the installation does works unattended
I dont know why this is a recurring issue/error

**Comment by stephengillie** [comment]
This is something of a known issue with our pipelines.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
I approved this in error - the `Architecture` should be changed from `x86` to `x64`: 

image

**Comment by Dvd-Znf** [comment]
Sorry, I’ll make a new PR to change the arch.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
