### PR TITLE
New Version: Astronomer.Astro version 1.24.0

### PR DESCRIPTION
**Pull request by kushalmalani**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141203)

### CODE REVIEW

**Review by sunkickr — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @+Validation-Defender-ErrorBinary-Validation-ErrorError-Analysis-TimeoutError-Hash-MismatchError-Installer-AvailabilityInternal-ErrorInternal-Error-Dynamic-ScanInternal-Error-ManifestInternal-Error-URLManifest-AppsAndFeaturesVersion-ErrorManifest-Installer-Validation-ErrorManifest-Validation-ErrorPossible-DuplicatePullRequest-ErrorURL-Validation-ErrorValidation-DomainValidation-Executable-ErrorValidation-Hash-Verification-FailedValidation-Missing-DependencyValidation-Merge-ConflictValidation-No-ExecutablesValidation-Installation-ErrorValidation-Shell-ExecuteValidation-Unattended-FailedPolicy-Test-1.2Policy-Test-2.3Policy-Test-2.3Validation-Forbidden-URL-ErrorValidation-Unapproved-URLValidation-RetryNeeds-Author-Feedback[0],

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 836.)

**Comment by stephengillie** [comment]
Automatic Validation ended with: >  Installation failed with exit code -1978335187 > 
> 2024-02-27 12:48:33.361 [CLI ] Installer [X64,portable,Unknown,en-US] not applicable: Machine is not compatible with X64 > 
> 2024-02-27 12:48:48.870 [FAIL] Installer failed security check. Url: https://github.com/astronomer/astro-cli/releases/download/v1.24.0/astro_1.24.0_windows_386.exe Result: 0x80004005   (Automated response - build 836.)

**Comment by stephengillie** [comment]
Hi @+Validation-Defender-ErrorBinary-Validation-ErrorError-Analysis-TimeoutError-Hash-MismatchError-Installer-AvailabilityInternal-ErrorInternal-Error-Dynamic-ScanInternal-Error-ManifestInternal-Error-URLManifest-AppsAndFeaturesVersion-ErrorManifest-Installer-Validation-ErrorManifest-Validation-ErrorPossible-DuplicatePullRequest-ErrorURL-Validation-ErrorValidation-DomainValidation-Executable-ErrorValidation-Hash-Verification-FailedValidation-Missing-DependencyValidation-Merge-ConflictValidation-No-ExecutablesValidation-Installation-ErrorValidation-Shell-ExecuteValidation-Unattended-FailedPolicy-Test-1.2Policy-Test-2.3Validation-CompletedValidation-Forbidden-URL-ErrorValidation-Unapproved-URLValidation-RetryNeeds-Author-Feedback[0],

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 843.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:   Installation failed with exit code -1978335187  > 2024-02-28 01:07:48.694 [CLI ] Installer [X64,portable,Unknown,en-US] not applicable: Machine is not compatible with X64  > 2024-02-28 01:08:09.392 [FAIL] Installer failed security check. Url: https://github.com/astronomer/astro-cli/releases/download/v1.24.0/astro_1.24.0_windows_386.exe Result: 0x80004005   (Automated response - build 843.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
