### PR TITLE
New version: YaSuenag.SimpleCom version 1.2.3

### PR DESCRIPTION
**Pull request by YaSuenag**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137723)

### CODE REVIEW

**Comment by YaSuenag** [comment]
I don't know why the pod determined this installer is invalid. I tested the installer on Windows Sandbox (Win 11), and it works.

Can you share details of error?

**Comment by stephengillie** [comment]
Hi @YaSuenag,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 703.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-03 06:17:27.766 [FAIL] Installer failed security check. Url: https://github.com/YaSuenag/SimpleCom/releases/download/v1.2.3/SimpleComInstaller-1.2.3.msi Result: 0x80004005

(Automated response - build 703.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
