### PR TITLE
New version: TTKN.CNKIExpress version 0.2.29 [FP-O]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | 全球学术快报 | 全球学术快报 0.2.29    |
| Version     | 0.2.29     | 0.2.29 |
| Publisher   | 同方知网(北京)技术有限公司   | 同方知网（北京）技术有限公司      |
| ProductCode |           | fdb21ffe-a525-5be7-af3a-a9436d18cc4f    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [3398](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/3315259837>)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
@msftbot reset feedback

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
@msftbot Blocking-Issue

**Comment by stephengillie** [comment]
Validation is blocked by 
* https://github.com/microsoft/winget-cli/issues/2057

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
