### PR TITLE
Deleting Browser Tamer from winget

### PR DESCRIPTION
**Pull request by aloneguid**
I'm an author of "Browser Tamer" utility and I would like it to be permanently removed from the winget package manager please.

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/115266&drop=dogfoodAlpha

### CODE REVIEW

**Comment by Trenly** [comment]
Each manifest will need to be removed as a separate PR

**Comment by aloneguid** [comment]
Haha

**Comment by aloneguid** [comment]
I hope you understand that raising tens of PRs is ridiculous and I'm not going to do that.

**Comment by Trenly** [comment]
> I hope you understand that raising tens of PRs is ridiculous and I'm not going to do that.

Unfortunately, the pipelines can only process changes to individual manifests at a time. I'll see what I can do to raise those PR's

**Comment by Trenly** [comment]
Individual PRs have been opened;

**Comment by sharunkumar** [comment]
Curious though... why?

**Comment by aloneguid** [comment]
yes, spot on, nothign against WinGet, I personally use it every day :)

**Pull request closed without merging**
