### PR TITLE
CustomRP: Hindi localization

### PR DESCRIPTION
**Pull request by maximmax42**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/118480)

### CODE REVIEW

**Comment by maximmax42** [comment]
Uh... Site's up, not blocked by Windows SmartScreen. Not sure what's wrong.

**Comment by Trenly** [comment]
> Uh... Site's up, not blocked by Windows SmartScreen. Not sure what's wrong.

Some sites block automated connections, like the ones that the validation pipeline uses. This has to wait for a repository admin to review

**Comment by maximmax42** [comment]
If I remove PackageUrl from this manifest, winget will just pull the URL from the default locale manifest, correct?

**Comment by maximmax42** [comment]
Okay, I think I might know what the issue is. The site is using Cloudflare, and I've recently enabled "Bot Fight Mode" for the site. I've disabled it for now.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
