### PR TITLE
Godot 3.3.2

### PR DESCRIPTION
**Pull request by Avellea**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

Latest stable release of Godot Engine without C# support.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15806)

### CODE REVIEW

**Comment by KaranKad** [comment]
I think we should add it once winget supports extracting from a .zip file.

**Comment by DynamicDonkey** [comment]
> I think we should add it when winget supports extracting from a .zip file.

You think so? It could easily be repackaged into a self extracting 7zip archive or an inno installer like the issue here. I'll be happy to close this unresolved if some more opinions come in. :)

**Comment by KaranKad** [comment]
There was discussion about moderation at #14621 and so the application should come from it's original source.

**Comment by DynamicDonkey** [comment]
Guess I'll go ahead and close this PR then, no sense in letting it run if its considered "untrustworthy". Hopefully winget gets .zip support soon!

**Comment by DynamicDonkey** [comment]
Closing in response to #14621. Waiting for .zip support in winget.

**Comment by podynoo** [comment]
@Avellea maybe this could be re-opened since winget now supports .zip installation [ #140](https://github.com/microsoft/winget-cli/issues/140)

**Comment by Avellea** [comment]
Wow I completely forgot about this. I'll submit a new PR with updated versions and mono support later today, if nobody has yet. Thank you!

**Comment by Calinou** [comment]
Note that pull requests referencing ZIP files won't be accepted until 1.4 has reached enough adoption among users: https://github.com/microsoft/winget-pkgs/issues/87300

**Comment by sitiom** [comment]
See https://github.com/godotengine/godot-proposals/issues/1523#issuecomment-1407850750

**Pull request closed without merging**
