### PR TITLE
GovHu.eSzemelyiKliens version 1.6.19

### PR DESCRIPTION
**Pull request by diakritikus**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/35298)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
This cannot install fully unattended due to a driver prompt:
image

**Comment by diakritikus** [comment]
OK, thanks for letting me know, I'll have to get back to the original
developers about this.
Can you please deny and close this PR, I'll open a new one for this later.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> Can you please deny and close this PR, I'll open a new one for this later.

Since you're the one that made this PR, you have the ability to close this, not me.

**Pull request closed without merging**
