### PR TITLE
New version: Microsoft.VCLibs.Desktop.14 version 14.0.33728.0

### LINKED ISSUE #161022: [Update Request]: Microsoft.VCLibs.Desktop.14
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.VCLibs.Desktop.14

### Package Version

14.0.33728.0

### Please describe the changes you would like to see

Several PRs depend on this version, but we don't have it in the repo yet. 

- https://github.com/microsoft/winget-pkgs/pull/157744
- https://github.com/microsoft/winget-pkgs/pull/158966
- https://github.com/microsoft/winget-pkgs/pull/159246
- https://github.com/microsoft/winget-pkgs/pull/160435

### PR DESCRIPTION
**Pull request by zaochih**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? Resolved #161022

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

> [!NOTE]
> As [_Microsoft deprecated its public distribution links for Desktop framework packages_](https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/c-runtime-packages-desktop-bridge/?wt.mc_id=studentamb_203301#how-to-install-and-update-desktop-framework-packages), I hosted them at Azure Storage account as the workaround for the newer versions. The domain, `dl.licaoz.com`, owned by me and hosted by Azure.
> ~~Hope my $150 monthly credit could afford it~~ :)

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/183895)

### CODE REVIEW

**Comment by LiCaoZ** [comment]
I'm using my domain as Microsoft didn't officially provide a permanent link :)

**Comment by stephengillie** [comment]
Unfortunately, packages have to be provided by the developer. We can't accept third party rehosted packages, for a variety of reasons. If the developer hasn't provided a permanent link for the package, then it might not be a good fit for the package manager. 

Yes, the package manager is provided by the same developer as this package. But this organization is very large, and different teams have different objectives. I'll ask the package manager team if anyone has a contact on this package's team, to see if we can get a permanent URL.

**Comment by LiCaoZ** [comment]
> Unfortunately, packages have to be provided by the developer. We can't accept third party rehosted packages, for a variety of reasons. If the developer hasn't provided a permanent link for the package, then it might not be a good fit for the package manager. 
> 
> Yes, the package manager is provided by the same developer as this package. But this organization is very large, and different teams have different objectives. I'll ask the package manager team if anyone has a contact on this package's team, to see if we can get a permanent URL. 

Glad to hear that, will wait for the response :)

**Comment by denelon** [comment]
@LiCaoZ this particular version of VCLibs is the one that would be installed as a dependency automatically for UWP applications via the Microsoft Store. Visual Studio includes this package with the appropriate workload for building UWP applications. We're working with an internal team to get a version specific URL rather than the "vanity" URL or "permalink" as the package gets updated underneath WinGet and when that happens, it causes a hash mismatch.

**Comment by stephengillie** [comment]
Close with reason: Duplicate of #191581;

**Pull request closed without merging**
