### PR TITLE
Update ImageMagick 7.0.10 to -16

### PR DESCRIPTION
**Pull request by ath0mas**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1505)

### CODE REVIEW

**Comment by MarNicGit** [comment]
@ath0mas You should add a new manifest for this new version instead of replacing the existing one! Winget will automatically grab the last version available in the repository, unless the user specifies that he wants an older version.

**Comment by ath0mas** [comment]
@MarNicGit it's a real question for me, for an often updated package like ImageMagick, do we want to add any new sub-version or to update it?
from my experience sometimes maintaining it for **brew**, I am used to their way of doing = updating (see [here](https://github.com/Homebrew/homebrew-core/commits/master/Formula/imagemagick.rb))

**Comment by MarNicGit** [comment]
@ath0mas All packages currently in the repo use separate manifests for each of their versions. It's not a whole lot of extra work either compared to updating existing manifests - Just copy the old one into a new file and adjust that file instead.

How does brew handle users that want to install older versions?

**Comment by ath0mas** [comment]
@MarNicGit I don't know the exact logic, and I suppose it's an update oriented process: you can install ImageMagick (v7) or ImageMagick@6, and _brew update/upgrade_ manage updating for you after _install_ ; you can not install a previous "sub-version"
back to our question, and my suggestion for this kind of package, would be to have manifests for each of major.minor.patch version but not maintaining history of sub-versions ... ? 🤔

**Comment by MarNicGit** [comment]
@ath0mas I'd just make a separate manifest for now, even for sub-versions, unless the maintainers disagree.

@samiranshah, what is MS's stance on this?

**Comment by ath0mas** [comment]
@MarNicGit Thanks for your feedback! I'm going to do another PR with separate manifest and close this one ;)

As a followup, I think that having a large list of historical download links may be hard to maintain as those previous versions will possibly not be downloadable forever

**Comment by MarNicGit** [comment]
> As a followup, I think that having a large list of historical download links may be hard to maintain as those previous versions will possibly not be downloadable forever

I fully agree! Considering that practically all but a select few applications in the repo aren't hosted by Microsoft themselves (unlike many other package managers) it's worth opening an issue over this to discuss how 'dead' versions can be discovered quickly.

**Comment by ath0mas** [comment]
And in fact, ImageMagick does not keep much binaries other than the last one, so the update I suggest is needed: previous download url for -14 fails now

see https://imagemagick.org/download/binaries/
more versions are still available in releases/ or windows/releases/, but only archives (zip) not binaries (exe)

**Comment by samiranshah** [comment]
As long as the previous versions work, you can add a new manifest for the latest version.
In this case since the previous version download fails, it is okay to replace the version and download link.
Ideally, we do want the yaml file name to reflect the complete version number.

@KevinLaMS do you want to add anything to this?

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
