### PR TITLE
mar10.yabs_test version 0.2.8.0

### PR DESCRIPTION
**Pull request by mar10**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/67330)

### CODE REVIEW

**Comment by mar10** [comment]
Do we have details on what caused the [Binary validation errors](https://docs.microsoft.com/en-us/windows/package-manager/package/binary-validation-errors)?

Can I assume that it is a false positive, or do you have other criteria to detect PUAs as well?

I built the installer using Python (cx_Freeze) on may machine, which has Defender installed.
Installation went through

[virustotal.com](https://www.virustotal.com/) reports
>No security vendors and no sandboxes flagged this file as malicious

**Review by Trenly — CHANGES_REQUESTED** [review]
It appears this is just a test installer from a temporary repository and is not an actual application

**Comment by mar10** [comment]
> It appears this is just a test installer from a temporary repository and is not an actual application

That is true: test_yabs is an application that I am using to test my continuous integration application [Yabs](https://github.com/mar10/yabs/).
yabs_test is already published on [GitHub](https://github.com/mar10/yabs-test/) and [PyPI](https://pypi.org/project/yabs-test/) and marked as 'test' by its name, project description, and program output when run.

Yabs is already used to publish other *real* applications ([WsgiDAV](https://github.com/mar10/wsgidav), [pyftpsync](https://github.com/mar10/pyftpsync), [stressor](https://github.com/mar10/stressor), [yabs](https://github.com/mar10/yabs), ...). 
stressor and WsgiDAV are also already published here on the winget-pkgs repo.

Since I am currently adding Windows Package Manager support to *Yabs*, I would like to add yabs_test here as well in order to test `wingetcreate update` in Yabs workflows without having to create releases for *real* apps.
Sadly there seems to be no dry-run mode for wingetcreate afaik.

Do you think it is possible to add yabs_test here, given this special context?

**Comment by denelon** [comment]
@ryfu-msft do we have a "dry run" option in wingetcreate to help authors test in these kinds of cases?

@mar10 there are examples of GitHub actions to show how to build your own GitHub action (via MIT license) at both PowerToys and oh-my-posh.

**Comment by mar10** [comment]
> there are examples of GitHub actions to show how to build your own GitHub action (via MIT license) at both PowerToys and oh-my-posh.

Thanks for the pointers.

**Comment by mar10** [comment]
Let me know if you decide to reject this PR, I can close it then, no problem.
(Maybe you want to add a link to the acceptance policy through,  if you have one.)

**Comment by ItzLevvie** [comment]
Close with reason: See above;

**Pull request closed without merging**
