### PR TITLE
New version: Tencent.WeChat version 3.4.0.54

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

* Resolves #37617

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/37651)

### CODE REVIEW

**Comment by Trenly** [comment]
@ChuckFerring or @palenshus - I believe this is a Pipelines error
image

**Comment by ItzLevvie** [comment]
Installs fine here as well:

**Review by ItzLevvie — DISMISSED** [review]

**Comment by lychichem** [comment]
However, the latest version of tencent.wechat is 3.4.5.27, and up till now I haven't find other URL to download it.

**Comment by Trenly** [comment]
> However, the latest version of tencent.wechat is 3.4.5.27, and up till now I haven't find other URL to download it.

Due to the way winget works, the version has to be the same as is displayed in control panel. The download link results in 3.4.0.54 as the version

**Comment by lychichem** [comment]
> > However, the latest version of tencent.wechat is 3.4.5.27, and up till now I haven't find other URL to download it.
> 
> Due to the way winget works, the version has to be the same as is displayed in control panel. The download link results in 3.4.0.54 as the version

No, it's 3.4.5.27,at least for Chinese users.

**Comment by Trenly** [comment]
> > > However, the latest version of tencent.wechat is 3.4.5.27, and up till now I haven't find other URL to download it.
> > 
> > 
> > Due to the way winget works, the version has to be the same as is displayed in control panel. The download link results in 3.4.0.54 as the version
> 
> No, it's 3.4.5.27,at least for Chinese users.

I’ve not heard of a package that changes version based on the language of the users system.

I suppose it is possible that they are using different CDN’s to serve different versions of the package though. If they have a dynamic CDN which is determined based on the IP of the requestor, it would explain the differences in version as well as the hash mismatches.

**Comment by OfficialEsco** [comment]
Weeeell, the checks kinda explains the Error-Hash-Mismatch issues as a CND mess😁

* #30962, version 3.4.0.38 hash 8986782FCE19402B989FD43DEF39338AAB91822DAC2EA27AE302E7ACA79EF3BA
* #37617, version 3.4.5.27 hash 006206B1714A5D32432D346D676AC007961DFA138047DE4491E039C20084328C
```
12/16/2021 6:59:51 AM
Status: Completed
##[error] Installer https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe
##[error] Result: Failed
##vso[task.logissue type=error] Specified hash doesn't match.
Actual hash:   852C5EBF11F3FD1E87CA3913773EFCDD2BA0BF96DC188AE2A9D06CB37040A664
Expected hash: 006206b1714a5d32432d346d676ac007961dfa138047de4491e039c20084328c
```
* #37651, version 3.4.0.54 hash 852C5EBF11F3FD1E87CA3913773EFCDD2BA0BF96DC188AE2A9D06CB37040A664
```
12/13/2021 11:56:39 PM
Status: Completed
##[error] Installer https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe
##[error] Result: Failed
##vso[task.logissue type=error] Specified hash doesn't match.
Actual hash:   006206B1714A5D32432D346D676AC007961DFA138047DE4491E039C20084328C
Expected hash: 852c5ebf11f3fd1e87ca3913773efcdd2ba0bf96dc188ae2a9d06cb37040a664
```

@lychichem could they have pulled the update?

**Comment by OfficialEsco** [comment]
```
Status: Completed
##[error] Installer https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe
##[error] Result: Failed
##vso[task.logissue type=error] Specified hash doesn't match.
Actual hash:   006206B1714A5D32432D346D676AC007961DFA138047DE4491E039C20084328C
Expected hash: 852c5ebf11f3fd1e87ca3913773efcdd2ba0bf96dc188ae2a9d06cb37040a664
```
I guess only @lychichem and wingetbot is allowed to download 3.4.5.27

**Comment by Trenly** [comment]
> ```
> Status: Completed
> ##[error] Installer https://dldir1.qq.com/weixin/Windows/WeChatSetup.exe
> ##[error] Result: Failed
> ##vso[task.logissue type=error] Specified hash doesn't match.
> Actual hash:   006206B1714A5D32432D346D676AC007961DFA138047DE4491E039C20084328C
> Expected hash: 852c5ebf11f3fd1e87ca3913773efcdd2ba0bf96dc188ae2a9d06cb37040a664
> ```
> 
> I guess only @lychichem and wingetbot is allowed to download 3.4.5.27

I just tried running PRTest on my local machine and now I get the new version 3.4.5.27 in sandbox, but when downloading through google chrome I get 3.4.0.54. I wonder if there is just some caching delay in their CDN

**Comment by OfficialEsco** [comment]
I tested when i posted the first comment, got 3.4.0.54, guess we'll have to go with 3.4.5.27 tho

**Review by ItzLevvie — APPROVED** [review]
image

**Comment by lychichem** [comment]
I just waked up from sleeping... The version info of Tencent.WeChat can be seen at https://weixin.qq.com/ (just in Chinese,but you can easily find the x.x.x version number). But the version number provided on this site lacks the last part so you have to download from the link below this page and install it. Note: the last part of version number is always different from what displayed in the " property" part of the downloaded installer ( which is always 100, 1000)

**Comment by SpecterShell** [comment]
https://webcdn.m.qq.com/spcmgr/download/WeChatSetup_3.4.5.27.exe

**Pull request closed without merging**
