### PR TITLE
Update: Google.Chrome version 92.0.4515.131

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

image

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23568)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
```
--> Installing WinGet

                                                                                                                                                 Tip: you can type 'Update-EnvironmentVariables' to update your environment variables, such as after installing a new software.                                                                                                                                                                                                                                                                                                                     --> Installing the Manifest 92.0.4515.131                                                                                                        
Found Google Chrome [Google.Chrome]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise64.msi
  ██████████████████████████████  76.2 MB / 76.2 MB
Successfully verified installer hash
Starting package install...
Successfully installed

--> Refreshing environment variables

PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs>
```
Are you going to tell me the x86 is not x86 anymore? 🤔

**Comment by jedieaston** [comment]
Is winget choosing the x64 build on x86?

**Comment by OfficialEsco** [comment]
Since https://github.com/microsoft/winget-pkgs/pull/22562 passed 6 days ago i would say no, but since we keep having issues with x86 maybe?

**Comment by ItzLevvie** [comment]
By testing this PR, hashes may have changed?

image

Running the `.msi` file, it successfully installed:
image
image
image
image
image

I can't find any issues with the installer.

**Comment by OfficialEsco** [comment]
Hmm oke there is something weird here
image
image
x64 from msi:
image

```
Found Google Chrome [Google.Chrome]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise64.msi
  ██████████████████████████████  76.2 MB / 76.2 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```
from WinGet install:
image

Redownload msi:
image
image

**Comment by jedieaston** [comment]
Duplicated. On a x86 test box:

image

image

(downloaded from https://dl.google.com/edgedl/chrome/install/GoogleChromeStandaloneEnterprise.msi).

**Review by jedieaston — APPROVED** [review]
Approved. But this is an interesting problem.

@denelon how hard would it be to run some of the validation pipelines (specifically the hash verification) in multiple/randomly selected datacenters? That would shake out these CDN issues, but I don't know how difficult that is with how the functions are currently designed. Maybe it wouldn't be worth it.

**Comment by denelon** [comment]
@jedieaston we've discussed this as a possibility. CDN issues cause the most pain with vanity URLs for installers. They are a small segment of the packages we currently have. The other challenge is what to do when there are different versions handed out in different geographies with different hash values. From the data I've seen on hash errors, it usually takes 48 hours to roll through global CDNs. Putting multiple hash values in a manifest also seems a bit less than optimal from a security perspective.

**Comment by denelon** [comment]
That's an interesting idea. I hadn't thought about a fallback to a hash from a previous manifest. I'll talk with the team about it. It wouldn't help with the new package version, but it would help when we update the manifest and the CDN hasn't fully rolled out.

It also doesn't work very well with version == "latest", but it's still an improvement.

I like it 😊

**Pull request merged**
