### PR TITLE
New version: Sandboxie.Plus version 1.0.22

### PR DESCRIPTION
**Pull request by DavidXanatos**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/60863)

### CODE REVIEW

**Comment by ItzLevvie** [comment]
cc @DavidXanatos: You need to sign the CLA.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
See https://github.com/microsoft/winget-pkgs/pull/60863#issuecomment-1126995033

**Comment by DavidXanatos** [comment]
> cc @DavidXanatos: You need to sign the CLA.

How exactly? Do I need to add a file to the repo indicating that or how doe sit work?

**Comment by DavidXanatos** [comment]
thx done

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
