### PR TITLE
Specify download link for GeoGebra.Classic v6.0.794

### PR DESCRIPTION
**Pull request by 9R2by**
Regarding [Package Issue]: GeoGebra.Classic #116962

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/117360)

### CODE REVIEW

**Comment by 9R2by** [comment]
@BrandonWanHuanSheng 
> It look like we can't tell when the update is available,. if we use the latest download URL to synchronize geogebra across github, it might noticed there is a new update available. But if we use direct link, it also keep stay there until when we need to search for update which means more difficult to find the update because it was different link.

Due to an issue I created a new PR. 
I think the main concern is, that if you dont specify the version, people that want to download a specific version are not able to.
Please correct me, if this statement is incorrect.

**Comment by BrandonWanHuanSheng** [comment]
Sometimes another URL also tricky, it only available after release https://download.geogebra.org/installers/6.0/GeoGebra-Windows-Installer-6-0-795-0.msi | Current Status: 404

**Comment by 9R2by** [comment]
> Sometimes another URL also tricky, it only available after release https://download.geogebra.org/installers/6.0/GeoGebra-Windows-Installer-6-0-795-0.msi | Current Status: 404 - Not Found before release.

Did you just changed the url to a version does not exist?

Here are all available installers for GeoGebra v6: https://download.geogebra.org/installers/6.0/
I am sorry but I don't see your point. The approach of giving a link that will automatically link to the latest version if existing, will not update the manifest as far as I understand (e.g. the hash does not change). This will lead to the packet being not installable.
Also the user is not able to install a specific version as mentioned before, but this is a feature from winget.

**Comment by 9R2by** [comment]
#116962 
@Orava2

**Comment by 9R2by** [comment]
I will close this PR and open another one, as I saw, that I linked the commit to the wrong issue.

**Pull request closed without merging**
