### PR TITLE
New Version: qBittorrent version 4.4.0

### PR DESCRIPTION
**Pull request by babblebauble**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/40968)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
I think this app is flagged by an anti-virus software.

**Comment by OfficialEsco** [comment]
Duplicate of #40105, #40410 and #40421

**Comment by babblebauble** [comment]
Should I close this PR? Looks like Windows Defender doesn't like any version of qBittorrent higher than 4.3.5.

**Comment by OfficialEsco** [comment]
You caaaaan let it run for a few hours, but i doubt it will do anything else than timeout after 24+h

**Pull request closed without merging**
