### PR TITLE
Add WinPower

### PR DESCRIPTION
**Pull request by sorge13248**
WinPower is a very simple yet powerful utility to shutdown, restart or hibernate your Windows computer

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/488)

### CODE REVIEW

**Comment by LukasNespor** [comment]
Please see #411 to resolve the validation issue.

**Comment by sorge13248** [comment]
> 
> 
> Please see #411 to resolve the validation issue.

Opening it with VS Code and saving in UTF-8 solved the problem for me, thank you LukasNespor

**Comment by sorge13248** [comment]
Confirmed false positive 
image

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
