### PR TITLE
added package in manifest

### PR DESCRIPTION
**Pull request by tirtharajsinha**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15826)

### CODE REVIEW

**Comment by KaranKad** [comment]
Rainmeter does not support silent installation. see this pr for more detail #15086

**Review by tirtharajsinha — COMMENTED** [review]
preformed all tasks

**Comment by OfficialEsco** [comment]
image

You sure did perform all the tasks

**Review by tirtharajsinha — COMMENTED** [review]
updated tasks

**Comment by tirtharajsinha** [comment]
> image
> 
> You sure did perform all the tasks

It just found the problem, actually rainmeter does not support silent installation.

**Pull request closed without merging**
