### PR TITLE
New version: Jackett.Jackett version 0.21.1645

### PR DESCRIPTION
**Pull request by ilike2burnthing**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137093)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @ilike2burnthing,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 677.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-29 22:07:09.914 [FAIL] Installer failed security check. Url: https://github.com/Jackett/Jackett/releases/download/v0.21.1645/Jackett.Installer.Windows.exe Result: 0x80004005

(Automated response - build 677.)

**Comment by ilike2burnthing** [comment]
Aaaaaand we're back to this crap again...

There's no issue with Jackett.

**Comment by stephengillie** [comment]
Hi @ilike2burnthing,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 677.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
