### PR TITLE
New version: Git.Git version 2.47.1 (2.47.1.windows.1)

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings).
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/193710)

### CODE REVIEW

**Comment by MagicAndre1981** [comment]
There is also an arm64 version which should be added:

https://github.com/git-for-windows/git/releases/download/v2.47.1.windows.1/Git-2.47.1-arm64.exe

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by SpecterShell** [comment]
@stephengillie The PR is not merging.

**Comment by stephengillie** [comment]
Sorry for the delay. The issue preventing merging has been declared as fixed, and my attempts to reopen it have failed, so I do my best to catch these and not make waves.

**Pull request merged**
