### PR TITLE
Spotify v1.1.36.734.g8731c306 + Manifest fix

### PR DESCRIPTION
**Pull request by OfficialEsco**
Apparently SpotifyFullSetup.exe is way behind SpotifySetup.exe

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [ ] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

I don't have a real vm so i can't test if the install works locally since i the Microsoft Store version

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2284)

### CODE REVIEW

**Comment by Xeevis** [comment]
@OfficialEsco There is [PR](https://github.com/microsoft/winget-pkgs/pull/827) for [SandboxTest.ps1](https://github.com/microsoft/winget-pkgs/blob/b20c3f21965fd47f05e0410c7bbdd18920857873/Tools/SandboxTest.ps1) script that automatically tests manifests in [Windows Sandbox](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-sandbox/windows-sandbox-overview). I'm using it for local testing all the time.

image

**Comment by OfficialEsco** [comment]
@Xeevis Ahhh right i've seen that but never got around to using it since it never got committed, i've always used Sandbox for testing of help/silent commands but found no easy fast way to use WinGet, this obv solves that problem 😃 

On the other hand i just setup a VM last night, so ill have to test both options, tbh Sandbox seems faster with 1 manifest.

@KevinLaMS 
[X] Have you tested your manifest locally with winget install -m <manifest>?

**Comment by OfficialEsco** [comment]
Tested on 3 different computers, the hash is 100% correct.

**Comment by OfficialEsco** [comment]
I don't know whats going on, now the hash is the old one `35ce7176234b5a050472f00e102fc50ab64ad8e96d53eff66f30f2217938723d`
Which should be 1.1.35.458 which i thought didn't work..

**Comment by Xeevis** [comment]
Works fine for me
**Url:** https://download.scdn.co/SpotifySetup.exe
**Version:** 1.1.36.734
**Sha256:** 2433603a22c01b288aa8647223092de58c5a7f2dbf3cb8bbbb80e78744764343

Perhaps CDN serves older files from time to time from the same url?

**Comment by OfficialEsco** [comment]
@KevinLaMS i need you to decide what to do. Spotify is updating faster then you can validate the hash. Since Spotify don't have a Direct download link the Manifest needs to be updated for each version.

I can create a Manifest for each version that goes to the same link with a different hash or you need to let the Manifest update go trough.

image

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
