### PR TITLE
SimonTatham.PuTTYrelease0.75(64-bit) version 0.75.0.0

### PR DESCRIPTION
**Pull request by NIAGRAFALZ**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14454)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Putty 0.75 is already added under https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/PuTTY/PuTTY

**Comment by KaranKad** [comment]
remove `release0.75(64-bit)` from folders and PackageIdentifier

**Comment by NIAGRAFALZ** [comment]
Don't mind me. Just sending my pack.

**Comment by NIAGRAFALZ** [comment]
Hey karan, \o/\o/\o/\o/\o/\o/\o/\o/\o/\o/\o/\o/\o/\o/\o/ HINT: Sympathy
Guess what that is

**Pull request merged**
