### PR TITLE
Add AxCrypt 1

### PR DESCRIPTION
**Pull request by ath0mas**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1667)

### CODE REVIEW

**Comment by SoftCreatR** [comment]
Take it, while it's hot 😸 

`https://www.winget.it/dl/949b053bf17e3948f2b666a212ba28be1734328f608aac4b717640bf8c35c1a6/https%3A%2F%2Fwww.opensource-dvd.de%2Ffiles%2FAxCrypt-1.7.3201.0-Setup.exe`

**Comment by ath0mas** [comment]
@SoftCreatR works with the alternate url I found, but it should be better with a winget.it url I think... would you mind hosting it too and giving me the url for it please?

**Comment by ath0mas** [comment]
@SoftCreatR ahah too quick for me
Thanks!

**Comment by SoftCreatR** [comment]
> @SoftCreatR works with the alternate url I found, but it should be better with a winget.it url I think... would you mind hosting it too and giving me the url for it please?

Too slow 😛

**Comment by ath0mas** [comment]
@SoftCreatR original url is `http://www.axantum.com/Download/AxCrypt-1.7.3201.0-Setup.exe`
can the winget.it url be based on that, instead of the alternate url _please_?

**Comment by SoftCreatR** [comment]
> @SoftCreatR original url is `http://www.axantum.com/Download/AxCrypt-1.7.3201.0-Setup.exe`
> can the winget.it url be based on that, instead of the alternate url _please_?

Doesn't matter, because once cached, it will serve the file from the winget.it server and not from the origin. However, if you really want:

`https://www.winget.it/dl/d994dbcbb44373da3246edaa4c01c242b8efa2eca1747038d8bb36ab91b3680b/http%3A%2F%2Fwww.axantum.com%2FDownload%2FAxCrypt-1.7.3201.0-Setup.exe`

**Comment by ath0mas** [comment]
Perfect!
Thank you @SoftCreatR again

**Comment by SoftCreatR** [comment]
yw

**Comment by KevinLaMS** [comment]
The URL provided for the app is not from the correct source.  I would expect it to be from:
https://account.axcrypt.net/download/axcrypt-2-setup.exe

**Comment by ath0mas** [comment]
@KevinLaMS ... changed to https://www.opensource-dvd.de/files/AxCrypt-1.7.3201.0-Setup.exe that is mostly the only maintained download url available on the internet for v1

Axantum is giving http://www.axantum.com/Download/AxCrypt-1.7.3201.0-Setup.exe dowload url but they do not maintain it anymore and redirect to v2 download page instead: see http://www.axantum.com/AxCrypt/LegacyDownloads.html

**Comment by KevinLaMS** [comment]
Thanks for the update.  We will need to consider this.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
