### PR TITLE
New version: Amazon.Corretto.11 version 11.0.21.9.1

### PR DESCRIPTION
**Pull request by ccorrion**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/133287)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978334957 2024-01-08 09:42:58.699 [CLI ] ShellExecute installer failed: 1633 MSI (s) (EC:14) [09:42:58:585]: Product: Amazon Corretto (x64) -- Installation failed. MSI (s) (EC:14) [09:42:58:585]: Windows Installer installed the product. Product Name: Amazon Corretto (x64). Product Version: 11.0.21.9. Product Language: 1033. Manufacturer: Amazon. Installation success or error status: 1633.

(Automated response - build 530.)

**Comment by stephengillie** [comment]
Hi @ccorrion,

> This PR's version number 11.0.21.9.1 has 5 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version 11.0.16.9, which has 4 parameters.

Is this intentional?

(Automated response - build 532)

**Comment by stephengillie** [comment]
Hi @ccorrion,

This manifest adds Apps and Features entries that aren't present in previous PR versions. Should these entries also be added to the previous versions?

(Automated response - build 532.)

**Comment by ccorrion** [comment]
> Hi @ccorrion,
> 
> This manifest adds Apps and Features entries that aren't present in previous PR versions. Should these entries also be added to the previous versions?
> 
> (Automated response - build 532.)

@stephengillie Yes, that makes sense - I think it's Komac generating more comprehensive manifests.  What's the process for getting that done?

**Comment by stephengillie** [comment]
Hi @ccorrion,

The version number was updated inside the files, but the path needs to match also. The `Manifest-Validation-Error` label was applied because the `.1` wasn't removed from the path. They have to match.

> This manifest adds Apps and Features entries that aren't present in previous PR versions. Should these entries also be added to the previous versions?
> 
> (Automated response - build 532.)
> 
> @ stephengillie Yes, that makes sense - I think it's Komac generating more comprehensive manifests. What's the process for getting that done?

Ah, that's probably the case. 

We have a limit of one manifest change per PR, so a PR would have to be opened foreach of the existing manifests, adding this. This PR can become approved and merged while work continues on the others.

**Pull request closed without merging**
