### PR TITLE
New package: Adobe.Acrobat.Reader.ALSD version 23.008.20421

### LINKED ISSUE #166451: [Package Request]: Asian Language And Spelling Dictionaries Support For Adobe Acrobat Reader
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://helpx.adobe.com/nz/acrobat/kb/font-pack-spelling-dictionary-64-bit-windows.html
Publisher: Adobe
Package Name: Asian Language And Spelling Dictionaries Support For Adobe Acrobat Reader
Description: Adobe Document Cloud Font Pack and Spelling Dictionary enable you to display and interact with documents authored in languages other than those supported in your native Acrobat Reader. It is needed to correctly display a document when an author does not embed the appropriate font into the document. It is also needed when the author does embed the font, but the document reader wishes to interact with the content somehow, for example, by collaborating, commenting, or filling out forms.
Package Version: 23.008.20421
Installer URL: https://ardownload3.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2300820421/AcroRdrALSDx64_2300820421_all_DC.msi

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- Resolve #166451

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/166633)

### CODE REVIEW

**Comment by Dragon1573** [comment]
image
image

Both URL are proved valid.

**Comment by stephengillie** [comment]
URL: https://ardownload3.adobe.com/pub/adobe/acrobat/win/AcrobatDC/2300820421/AcroRdrALSDx64_2300820421_all_DC.msi 
Status Code: 200

(Automated message - build 887)

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Closed because https://github.com/microsoft/winget-pkgs/labels/URL-Validation-Error https://github.com/microsoft/winget-pkgs/labels/Validation-SmartScreen-Error

**Pull request closed without merging**
