### PR TITLE
New package: Unity.DownloadAssistant version 6000.0.1f1

### LINKED ISSUE #153335: Unity 6000.0.0f1
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://unity.com/releases/editor/archive
Publisher:Unity
Package Name: Unity Download Assistant for version 6000.0f1
Description: A new version of unity's game engine.
Package Version:6000.0.0f1
Files

Installer URL: https://download.unity3d.com/download_unity/4ff56b3ea44c/UnityDownloadAssistant-6000.0.0f1.exe

We would like to include every package into the deployment (which can be done using the download assistant). The install.bat is optional but the arguments inside are the same.

the DownloadAssistant gives the option to install all of the different packages or the option to just download them.

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #153335 
- [x] This is a recreation of #153343 

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/153486)

### CODE REVIEW

**Comment by Dragon1573** [comment]
@stephengillie - This package was verified in Windows Sandbox, and able to install unattendedly.

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 880.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 881.)

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/pull/153360#issuecomment-2111491135

**Comment by Dragon1573** [comment]
Because of https://github.com/microsoft/winget-pkgs/pull/153360#issuecomment-2118156672, the PR should be closed.

**Pull request closed without merging**
