### PR TITLE
Added TechSmith.Camtasia version 21.0.6.32207

### PR DESCRIPTION
**Pull request by ImJoakim**
image

```
PS C:\Users\Test> winget validate --manifest "M:\Git\winget-pkgs\manifests\t\TechSmith\Camtasia\21.0.6.32207"
Manifest validation succeeded.

PS C:\Users\Test> winget install -m "M:\Git\winget-pkgs\manifests\t\TechSmith\Camtasia\21.0.6.32207"
Found Camtasia [TechSmith.Camtasia]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.techsmith.com/camtasiastudio/releases/2106/camtasia.exe
  ██████████████████████████████   451 MB /  451 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23823)

### CODE REVIEW

**Comment by ImJoakim** [comment]
image


image

**Comment by denelon** [comment]
@ImJoakim we're looking at this one. It passed once via manual run, but failed again with the second execution here.

**Review by ItzLevvie — APPROVED** [review]

**Comment by ImJoakim** [comment]
@ChuckFerring This needs the `Azure-Pipeline-Passed` label as well for it to merge.

**Pull request merged**
