### PR TITLE
New package: FreakinSoftMania.WinUEFI version 1.9.3

### PR DESCRIPTION
**Pull request by Minionguyjpro**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/115062&drop=dogfoodAlpha

### CODE REVIEW

**Comment by Minionguyjpro** [comment]
I have manually tested and it works! This is probably an issue where the software gets detected as suspicious and blocks it from installing. Maybe someone can test again, however, I just came to the fact my app automatically starts and reboots into firmware settings (intention of my app) after installing it whoch I don't want. I had set it up so it doesn't check running it automatically when installed. Because how it is now is just not handy.

**Comment by Minionguyjpro** [comment]
Okay, I made some changes. It might come through now.

**Comment by Minionguyjpro** [comment]
Can someone rerun it please?

**Comment by Minionguyjpro** [comment]
> Hello @Minionguyjpro,
> 
> The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.
> 
> Template: msftbot/validationError/installation/general

It works. I cannot do anything about it!

**Comment by Minionguyjpro** [comment]
@stephengillie, can you please help me with this in some way? I tested that it works when installing the local manifest. Or is this  a virus issue again?

**Comment by stephengillie** [comment]
Hi @Minionguyjpro,

This error means the installer didn't complete - possibly because a silent installer switch is missing, or possibly because it encountered an error. We can check the run logs for the specific error after this run is complete.

**Comment by Minionguyjpro** [comment]
> Hi @Minionguyjpro,
> 
> This error means the installer didn't complete - possibly because a silent installer switch is missing, or possibly because it encountered an error. We can check the run logs for the specific error after this run is complete.

Please do this. It should work now. I set up the silent install flag ``skipifsilent``. I have tested the manifest myself locally with install command linking to the directory with the manifest, and it fully installs without me needing to do anything. Can you please check the logs and report back to me @stephengillie? Thanks in advance.

**Comment by Trenly** [comment]
> 2023-08-04 15:54:22.741 [FAIL] Installer failed security check. Url: https://github.com/FreakinSoftMania/WinUEFI/releases/download/v1.9.3/WinUEFI-setup.exe Result: 0x80004005

We can try again in a day or two to see if this resolves itself.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2023-08-07 13:13:20.397 [FAIL] Installer failed security check. Url: https://github.com/FreakinSoftMania/WinUEFI/releases/download/v1.9.3/WinUEFI-setup.exe Result: 0x80004005

**Comment by Minionguyjpro** [comment]
Okay, so what now?

**Comment by stephengillie** [comment]
> Okay, so what now?

It might be a false positive, so we'll check again. We can check daily for a while. And there is the possibility that the ISV/developer/publisher accidentally had a virus involved when compiling or packaging the application.

**Comment by Minionguyjpro** [comment]
> > Okay, so what now?
> 
> It might be a false positive, so we'll check again. We can check daily for a while. And there is the possibility that the ISV/developer/publisher accidentally had a virus involved when compiling or packaging the application. 

It builds on GitHub so I don't think so.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2023-08-10 11:51:11.552 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\SHA256.cpp(147)\WindowsPackageManager.dll!00007FFA85F92B7F: (caller: 00007FFA860B2986) Exception(1) tid(1db0) 8A150040  2023-08-10 11:51:18.619 [FAIL] Installer failed security check. Url: https://github.com/FreakinSoftMania/WinUEFI/releases/download/v1.9.3/WinUEFI-setup.exe Result: 0x80004005 
image

This might be a false positive. We can rescan tomorrow.

**Comment by Minionguyjpro** [comment]
> Automatic Validation ended with:
> > 2023-08-10 11:51:11.552 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\SHA256.cpp(147)\WindowsPackageManager.dll!00007FFA85F92B7F: (caller: 00007FFA860B2986) Exception(1) tid(1db0) 8A150040  2023-08-10 11:51:18.619 [FAIL] Installer failed security check. Url: https://github.com/FreakinSoftMania/WinUEFI/releases/download/v1.9.3/WinUEFI-setup.exe Result: 0x80004005 
> image
> 
> This might be a false positive. We can rescan tomorrow. 

@stephangillie, can you do so?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335187 2023-08-14 09:10:04.272 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\SHA256.cpp(147)\WindowsPackageManager.dll!00007FFA96382B7F: (caller: 00007FFA964A2986) Exception(1) tid(110c) 8A150040  2023-08-14 09:10:07.899 [FAIL] Installer failed security check. Url: https://github.com/FreakinSoftMania/WinUEFI/releases/download/v1.9.3/WinUEFI-setup.exe Result: 0x80004005 

image

Unfortunately, the issue has merely changed form.

**Comment by Minionguyjpro** [comment]
> Automatic Validation ended with:
> > Installation failed with exit code -1978335187 2023-08-14 09:10:04.272 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\SHA256.cpp(147)\WindowsPackageManager.dll!00007FFA96382B7F: (caller: 00007FFA964A2986) Exception(1) tid(110c) 8A150040  
> 2023-08-14 09:10:07.899 [FAIL] Installer failed security check. Url: https://github.com/FreakinSoftMania/WinUEFI/releases/download/v1.9.3/WinUEFI-setup.exe Result: 0x80004005 
> 
> image
> 
> 

What does this mean for me?

**Comment by stephengillie** [comment]
> > Automatic Validation ended with:
> > > Installation failed with exit code -1978335187 2023-08-14 09:10:04.272 [FAIL] D:\a_work\1\s\external\pkg\src\AppInstallerCommonCore\SHA256.cpp(147)\WindowsPackageManager.dll!00007FFA96382B7F: (caller: 00007FFA964A2986) Exception(1) tid(110c) 8A150040
> > > 2023-08-14 09:10:07.899 [FAIL] Installer failed security check. Url: https://github.com/FreakinSoftMania/WinUEFI/releases/download/v1.9.3/WinUEFI-setup.exe Result: 0x80004005
> > 
> > 
> > image
> 
> What does this mean for me?

This package keeps failing a Defender scan. This might not be a false positive. Packages have to pass a Defender scan to be accepted into the WinGet public manifests.

**Comment by Minionguyjpro** [comment]
> > > Automatic Validation ended with:
> > > > Installation failed with exit code -1978335187 2023-08-14 09:10:04.272 [FAIL] D:\a_work\1\s\external\pkg\src\AppInstallerCommonCore\SHA256.cpp(147)\WindowsPackageManager.dll!00007FFA96382B7F: (caller: 00007FFA964A2986) Exception(1) tid(110c) 8A150040
> > > > 2023-08-14 09:10:07.899 [FAIL] Installer failed security check. Url: https://github.com/FreakinSoftMania/WinUEFI/releases/download/v1.9.3/WinUEFI-setup.exe Result: 0x80004005
> > > 
> > > 
> > > image
> > 
> > 
> > What does this mean for me?
> 
> This package keeps failing a Defender scan. This might not be a false positive. Packages have to pass a Defender scan to be accepted into the WinGet public manifests.

I see. Is there some way to look very heavily into it to see what causes it? It might fail security scan because it runs a command to reboot into UEFI firmware. I also tested on VirusTotal, and it gives the flag ``direct-cpu-clock-access``, probably because it will reboot into firmware. This might be why it fails, but don't know what to do about it.

**Comment by Minionguyjpro** [comment]
@stephengillie, as I explained I think this is the cause of it.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335226 
2023-10-04 15:28:30.426 [CLI ] ShellExecute installer failed: 1603 
INFO   : [10/04/2023 15:28:30:186] [VsdLaunchConditions                     ]: MsiSetPropertyW - Setting property 'HideFatalErrorForm' to 'TRUE'. 
ERROR  : [10/04/2023 15:28:30:186] [VsdLaunchConditions                     ]: Custom Action failed with code: '1603' CustomAction VSDCA_VsdLaunchConditions returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox) Property(S): ErrorDialog = ErrorDialog Property(S): HideFatalErrorForm = TRUE 
MSI (s) (8C:C0) [15:28:30:264]: Product: clawPDF 0.9.2 -- Installation failed. 
MSI (s) (8C:C0) [15:28:30:264]: Windows Installer installed the product. Product Name: clawPDF 0.9.2. Product Version: 0.9.2. Product Language: 0. Manufacturer: Andrew Hess // clawSoft. Installation success or error status: 1603. 

Code `1603` often indicates a missing dependency.

**Comment by Minionguyjpro** [comment]
Yeah that's normal. It's made to boot into the UEFI settings but I know on
Hyper-V it shows that when doing so.

Op do 5 okt. 2023 20:20 schreef Stephen Gillie ***@***.***>:

**Comment by Minionguyjpro** [comment]
@stephengillie if you could please check the above comment.

**Comment by stephengillie** [comment]
Hi @Minionguyjpro,

Sorry for not responding. I believe packages which reboot the system aren't currently being accepted.

**Comment by Minionguyjpro** [comment]
> Hi @Minionguyjpro,
> 
> Sorry for not responding. I believe packages which reboot the system aren't currently being accepted. 

Hmmm, sad to hear but I do understand.

**Pull request closed without merging**
