### PR TITLE
New version: Anchor.cli 0.1.4

### PR DESCRIPTION
**Pull request by benburkert**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/177862)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-10-04 07:02:53.710 [FAIL] Installer failed security check. Url: https://github.com/anchordotdev/cli/releases/download/v0.1.4/msi-builder-x86.msi Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 896.)

**Comment by Dragon1573** [comment]
Manually verified.

```text
10:40:17 D:\...\winget-pkgs  [pull/177862] 0ms pwsh> winget download -m .\manifests\a\Anchor\cli\0.1.4\
Found cli [Anchor.cli] Version 0.1.4
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/anchordotdev/cli/releases/download/v0.1.4/msi-builder-x64.msi
  ██████████████████████████████  5.07 MB / 5.07 MB
Successfully verified installer hash
Installer downloaded: D:\Dragon1573\Downloads\Anchor.cli_0.1.4\cli_0.1.4_X64_wix_en-US.msi

10:41:44 D:\...\winget-pkgs  [pull/177862] 8ms pwsh> winget install -m .\manifests\a\Anchor\cli\0.1.4\
Found cli [Anchor.cli] Version 0.1.4
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/anchordotdev/cli/releases/download/v0.1.4/msi-builder-x64.msi
  ██████████████████████████████  5.07 MB / 5.07 MB
Successfully verified installer hash
Starting package install...
Successfully installed

10:44:22 D:\...\winget-pkgs  [pull/177862] 0ms pwsh> winget --info
Windows Package Manager (Preview) v1.9.2411-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.4249
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.24.2411.0

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Enabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Enabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
