### PR TITLE
New version: altair-graphql.altair version 5.1.0

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Pull request has been created with [WinGet Automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) :melon:

### CODE REVIEW

**Comment by mdanish-kh** [comment]
[Policy] Needs-Attention

Holding off merge until someone can take a look how the PR passed validation with non-existent RelativeFilePaths

**Comment by stephengillie** [comment]
Duplicate of https://github.com/microsoft/winget-pkgs/pull/115563

**Comment by stephengillie** [comment]
Reset PR

**Comment by stephengillie** [comment]
Hi @vedantmgoyal2009,

This PR appears to modify quite a few files:
image

**Pull request closed without merging**
