### PR TITLE
New version: Elgato.WaveLink version 1.10.1.2293

### PR DESCRIPTION
**Pull request by krystofkrticka**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/151651)

### CODE REVIEW

**Comment by krystofkrticka** [comment]
In windows sandbox it installs just fine. There is just one requirement and that is reboot after installation.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334967
> 2024-04-30 08:21:11.190 [CLI ] ShellExecute installer failed: 3010
> CAQuietExec:  Error 0x80070001: Command line returned an error.
> CAQuietExec:  Error 0x80070001: QuietExec Failed
> CAQuietExec:  Error 0x80070001: Failed in ExecCommon method
> CustomAction ClearFirewall returned actual error code 1603 but will be translated to success due to continue marking
> Property(S): DRIVERINSTALLFAILED_MESSAGE = Driver installation failed. Please reboot and start setup again.
> Property(S): DRIVERINSTALLFAILED_AUTO_MESSAGE = Driver installation failed. Please reboot and Setup will be started again.
> Property(S): ErrorDialog = ErrorDlg
> Property(S): SecureCustomProperties = DELETE_APPDATA_FILES_ACCEPTED_VALUE;DRIVERINSTALLFAILED_AUTO_MESSAGE;DRIVERINSTALLFAILED_MESSAGE;EXE_FILE_NAME;INSTALLDIR_PRODUCT_FAKE;INSTALLER_FILE_NAME;IS_DRIVER_UP_TO_DATE;IS_ELGATO_WAVE_DEVICE_CONNECTED;KEEP_SETTINGS_ALERT_MESSAGE;NETFRAMEWORK45;NEW_FIRMWARE_VERSION;OLD_COMP_PATH;OLDER_VERSION_DELETING_REGISTRY_APPDATA_ON_UPGRADE;OLDER_VERSION_WITH_ELGATO_PLUGINS;OLDERVERSIONBEINGUPGRADED;UNPLUG_MESSAGE;USAGE_STATISTICS_ACCEPTED_VALUE;WIN10FOUND;WIX_DOWNGRADE_DETECTED;WIX_UPGRADE_DETECTED;WIXUI_INSTALLDIR

Automated error analysis suggests 1603 may mean Sometimes "Install successful

(Automated response - build 878.)

**Comment by krystofkrticka** [comment]
We already had this issue once and it was merged manually because we couldn't reproduce the installation failure when manually starting PR Test in windows sandbox.

**Comment by stephengillie** [comment]
> We already had this issue once and it was merged manually because we couldn't reproduce the installation failure when manually starting PR Test in windows sandbox. But when I'm installing this app manually it requires reboot.

Thanks for reminding me. I might need occasional reminders until we get a more permanent system set up.

**Comment by stephengillie** [comment]
Hi @krystofkrticka,

This manifest adds Apps and Features entries that aren't present in previous PR versions. These entries should be added to the previous versions, or removed from this version.

(Automated response - build 878.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
