### PR TITLE
Microsoft.Ironpython3 version 3.4.0.0001

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/18598)

### CODE REVIEW

**Review by jedieaston — COMMENTED** [review]
@OfficialEsco @ItzLevvie WinGet is picking this package up as `Microsoft.Ironpython2`, and I can't figure out why. Does anybody have a hypothesis? (I tried changing PackageName to what it appears as in the ARP table, that didn't help). I'm fine with merging this but upgrades will be broken for both IronPython2 and IronPython3 until this is resolved. 

(ps @denelon Are there any docs in microsoft/winget-cli that explain exactly how the ARP matching works? If not that might be something for the backlog, because it'd help a ton with diagnosing these types of issues.)

**Review by jedieaston — APPROVED** [review]

**Comment by OfficialEsco** [comment]
> @OfficialEsco @ItzLevvie WinGet is picking this package up as `Microsoft.Ironpython2`, and I can't figure out why. Does anybody have a hypothesis? (I tried changing PackageName to what it appears as in the ARP table, that didn't help). I'm fine with merging this but upgrades will be broken for both IronPython2 and IronPython3 until this is resolved.
> 
> (ps @denelon Are there any docs in microsoft/winget-cli that explain exactly how the ARP matching works? If not that might be something for the backlog, because it'd help a ton with diagnosing these types of issues.)

Every Publisher and PackageName in that Package folder looks for a matching ARP, so [Microsoft/Ironpython2/2.7.11.1000/Microsoft.Ironpython2.yaml](https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/Ironpython2/2.7.11.1000/Microsoft.Ironpython2.yaml) have `PackageName: IronPython` which is causing this match.

If `PackageName: IronPython 2` and `PackageName: IronPython 3` actually works we should use that (Some fails because of `.` and `-` in the package name)
This should also be moved to `Microsoft.IronPython.2` and `Microsoft.IronPython.3` where the manifests have a consistent `Publisher` and `PackageName`

**Comment by jedieaston** [comment]
But why does WinGet show the name "IronPython" instead of "IronPython 3.4.0a1" as it appears in the ARP table? Where does it get that value from? (This happens with a lot of apps, not just this one, where the name WinGet comes up with != the name in the ARP table or the name in the package).

**Comment by OfficialEsco** [comment]
It should show the `PackageName` from the latest Manifest (gimme a few examples), WinGet actually shows very little ARP Information without us providing it, if `Publisher` and `PackageName` matches it will show the `PackageIdentifier` which controls everything else. `Publisher` and `PackageName` by default looks for `PackageName/Publisher "wildcard"`, so we don't actually have to type the whole thing, but it helps.

**Comment by jedieaston** [comment]
I didn't know it added a wildcard (thought that was just something that was proposed), so thanks, that makes a lot of sense. So `winget list` looks in the package source(s) for the "actual" name to display? 

(`Automattic.Wordpress` was the immediate example I thought of, but that does what you say, since `WordPress.com*` would match `WordPress.com 6.15.0`.)

**Comment by OfficialEsco** [comment]
It's most likely a wildcard made for version numbers in the name because from experience if I don't remember wrong `WordPress*` would fail but `WordPress.com *` works (aka you need the space...)  

`WinGet list` displays the PackageName from the latest manifest probably because it's showing that one, but if you do `winget show "packageid" --version` it will show the PackageName from that specific manifest.

The suggestion is so we can use wildcards in the Manifest, like `Mozilla Firefox * (en-US)` or `IronPython 3*` in this case.

**Comment by denelon** [comment]
We're getting ready to work on the https://github.com/microsoft/winget-cli/issues/1073 specification 
I'll add some notes to make sure we share the logic

**Pull request merged**
