### PR TITLE
New version: LinwoodCloud.Butterfly.Nightly version 2.1.0-beta.2

### PR DESCRIPTION
**Pull request by CodeDoctorDE**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/143784)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-03-11 05:23:25.917 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x64 with version 14.38.33135.0

(Automated response - build 869.)

**Comment by CodeDoctorDE** [comment]
How can I fix this?

**Comment by stephengillie** [comment]
I didn't get the same error in a Windows 10 VM.

**Comment by CodeDoctorDE** [comment]
it first appears in https://github.com/microsoft/winget-pkgs/pull/141032 for me, but I don't know why.
I upgraded to flutter 3.19 maybe this is the issue?

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
