### PR TITLE
Create DSC for bootstrapping YamlCreate.ps1

### PR DESCRIPTION
**Pull request by Trenly**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?

cc @denelon / @stephengillie
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/130038)

### CODE REVIEW

**Comment by denelon** [comment]
I love taking the approach of building a WinGet configuration here. I've been looking and haven't found anything that gives the SKU of Windows to make sure Windows SandBox is available.

It would be nice if we could somehow deal with the scenario where a Windows SKU doesn't have the ability to run the Windows Sandbox rather than just having the configuration fail in that case.

@ryfu-msft have you found anything that can do this?

**Comment by Trenly** [comment]
> I love taking the approach of building a WinGet configuration here. I've been looking and haven't found anything that gives the SKU of Windows to make sure Windows SandBox is available.
> 
> It would be nice if we could somehow deal with the scenario where a Windows SKU doesn't have the ability to run the Windows Sandbox rather than just having the configuration fail in that case.
> 
> @ryfu-msft have you found anything that can do this?

It may be possible to use the `Script` DSC resource to write a custom Get, Test, and Set function but that's a fair bit of work. There are also ways to enable sandbox in Home Edition, but they involve manually registering all the containers packages with DISM and then using DISM again to enable the feature.

**Comment by denelon** [comment]
It might be worth just documenting that via comments and pulling it out of this configuration since it would likely cause the configuration to fail. Maybe a different configuration could be used to bootstrap Sandbox appropriately and launch it.

**Review by denelon — APPROVED** [review]

**Comment by denelon** [comment]
Nice fix for the "project file" thing too!

**Pull request merged**
