### PR TITLE
Add XnView MP

### PR DESCRIPTION
**Pull request by auanasgheps**
Adds XnView MP version 0.94.1

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1441)

### CODE REVIEW

**Review by auanasgheps — COMMENTED** [review]
.yaml extension was missing

**Review by auanasgheps — COMMENTED** [review]
Fixed again

**Review by auanasgheps — COMMENTED** [review]
Fixed architectures

**Review by auanasgheps — COMMENTED** [review]
Removed x86 installer as multiple installers are currently not supported. Sorry 32 bit users.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
