### PR TITLE
New version: twpayne.chezmoi 2.43.0

### PR DESCRIPTION
**Pull request by twpayne**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132483)

### CODE REVIEW

**Comment by twpayne** [comment]
What action do you want me to take? As far as I can tell, the problems are with winget-pkg's infrastructure:

The [WinGetSvc-Validation](https://github.com/microsoft/winget-pkgs/pull/132483/checks?check_run_id=20111024897) check seems to have [a failing step with no actual warnings or errors](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=527630&view=logs&j=68997d86-8ece-5ae8-3ac5-ccdbfa458731&t=b79910ce-dca5-5e27-ad7f-bd285eecb5a2) apart from a [final `Result: Failed`](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=527630&view=logs&j=68997d86-8ece-5ae8-3ac5-ccdbfa458731&t=b79910ce-dca5-5e27-ad7f-bd285eecb5a2&l=38).

The [WinGetSvc-Validation (WinGetSvc_Validation Installer Validation) check](https://github.com/microsoft/winget-pkgs/pull/132483/checks?check_run_id=20111020110) reports 0 errors / 0 warnings and yet is still shown as failed.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-02 16:46:52.914 [FAIL] Installer failed security check. Url: https://github.com/twpayne/chezmoi/releases/download/v2.43.0/chezmoi_2.43.0_windows_i386.zip Result: 0x80004005

(Automated response - build 516.)

**Comment by stephengillie** [comment]
Hi @twpayne,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 516.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
