### PR TITLE
update bottom to 0.6.5

### PR DESCRIPTION
**Pull request by ClementTsang**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/38313)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Updated in #38314

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
image

Duplicate of https://github.com/microsoft/winget-pkgs/pull/38314.

**Comment by ClementTsang** [comment]
Huh, guess someone else already updated it for me.  Closing this one then.

**Comment by OfficialEsco** [comment]
Your PR was acting weird and got stuck, https://github.com/vedantmgoyal2009/winget-pkgs-automation takes care of most GitHub releases, i see you've been taking care of the releases tho, do you want to keep maintaining the releases or should the bot do it?

**Comment by ClementTsang** [comment]
Nah, it's all good - was just surprised, that's all.  Would be happy for a bot to manage this stuff, especially since that would mean less burden on me when I release a new version on my end.

**Pull request closed without merging**
