### PR TITLE
New version: JFrog.Conan version 2.2.0

### PR DESCRIPTION
**Pull request by OfficialEsco**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/145495)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
```
Enter a pull request number: #145495

Manifest validation succeeded.
Found Conan Package Manager [JFrog.Conan] Version 2.2.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/conan-io/conan/releases/download/2.2.0/conan-2.2.0-windows-x86_64-installer.exe
  ██████████████████████████████  9.34 MB / 9.34 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Name          : Conan Package Manager version 2.2.0
Publisher     :
Version       : 2.2.0
ProductCode   : Conan Package Manager_is1
Registry Path : Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Conan Package Manager_is1
Uninstall     : winget uninstall --id "Conan Package Manager_is1"

Press any key to continue . . .
```

**Comment by stephengillie** [comment]
Hi @OfficialEsco,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-20 19:48:11.443 [FAIL] Installer failed security check. Url: https://github.com/conan-io/conan/releases/download/2.2.0/conan-2.2.0-windows-i686-installer.exe Result: 0x80004005

(Automated response - build 870.)

**Comment by OfficialEsco** [comment]
* https://www.virustotal.com/gui/url/4094ef1510f9035147967ea7c0788e7463f92c343a80cb14c7977fd4cc79c058
* https://www.virustotal.com/gui/file/61e00f22e5829ffdde93270dceaf9260b27bed46575accde317d38270ca41587?nocache=1

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
