### PR TITLE
Normalize CodecGuide.K-LiteCodecPack.Full 17.2.0

### PR DESCRIPTION
**Pull request by Trenly**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/75753)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
image

**Comment by Trenly** [comment]
@denelon - can you remove "Needs-Attention"? I think MSFTbot forgot to remove it

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
