### PR TITLE
New package: chaiNNer-org.chaiNNer version 0.19.2

### PR DESCRIPTION
**Pull request by onyx-nxt**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/116831&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
>  Manifest Error: Field usage requires verified publishers. [Icons]

**Comment by stephengillie** [comment]
Hi @KK-Designs, 

I'm not sure if we're accepting icons quite yet.

**Comment by KK-Designs** [comment]
> @KK-Designs,
> 
> Your manifest appears to contain one or more issues with the content. Please ensure it meets the contribution guidelines.
> 
>     * Manifests should be tested to ensure applications can install unattended
> 
>     * Manifests should be tested to ensure application version matches the Package Version, or that AppsAndFeaturesEntries are included if necessary
> 
>     * Manifests should be tested to ensure application publisher matches the defaultLocale Publisher, or that AppsAndFeaturesEntries are included if necessary
> 
>     * Manifests should be tested to ensure application name matches the defaultLocale PackageName, or that AppsAndFeaturesEntries are included if necessary
> 
> 
> Please review your manifest and make the appropriate changes. This PR will be automatically closed if no changes are made.
> 
> Template: msftbot/validationError/manifest/contentIncomplete

Whats this? I created this using the wingetcreate.exe

**Comment by stephengillie** [comment]
Hi @KK-Designs,

I'm sorry for applying that label and causing you some concern. It was in error and I meant to retry the PR instead.

**Comment by KK-Designs** [comment]
Is the PR ok and valid?

**Comment by KK-Designs** [comment]
Fixed the invalid icons

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
