### PR TITLE
New version: TechNobo.TcNoAccountSwitcher version 2024.08.30.01

### PR DESCRIPTION
**Pull request by rakleed**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/172271)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @rakleed,

This isn't failing a Defender scan. It's on a SmartScreen block list. I do not know how to change this, but I believe it's through a slightly different team.

**Comment by stephengillie** [comment]
It's the only means I know to pass this check. Unfortunately, I can't waiver or manually validate this.

**Comment by Eddga** [comment]
This might be the reason: 

> NOTE: TcNo Account Switcher is NO LONGER signed. Reason here: https://github.com/TCNOco/TcNo-Acc-Switcher/commit/c283aa2bae4deaed93e7757f188813560ef3b02e. Builds are done with [AppVeyor](https://github.com/TCNOco/TcNo-Acc-Switcher/tree/appveyor) now to allow [SignPath](https://signpath.org/) to help out with signing. This may change shortly :)

It's noted as very last point in the release notes here:
https://github.com/TCNOco/TcNo-Acc-Switcher/releases/tag/2024-08-30_01

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Pull request closed without merging**
