### PR TITLE
Add EqualizerAPO-1.2.1.

### LINKED ISSUE #9186: Equalizer APO (x64)
# Package Requested

Manifest:

```YAML
Id: jthedering.equalizerapo
Publisher: jthedering
Name: Equalizer APO (x64)
Version: 1.2.1
License: GNU General Public License version 2.0 (GPLv2)
InstallerType: Nullsoft
Installers:
  - Arch: x64
    Url: https://altushost-swe.dl.sourceforge.net/project/equalizerapo/1.2.1/EqualizerAPO64-1.2.1.exe
    Sha256: BD0AC49633D02A387F906B5D4F47F9235D229470742D3433018245136756F583
ManifestVersion: 0.1.0
```

### PR DESCRIPTION
**Pull request by yigitemres**
Fixes: #9186.

-----
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/9198)

### CODE REVIEW

**Comment by yigitemres** [comment]
`Switches` works correctly but during the end of the installation process there is a `Configurator` part which cannot be bypassed by `Switches`. This part is needed for correctly configure interfaces/devices.

WindowsSandboxClient_NM0Udw54sL

**Comment by denelon** [comment]
We currently don't allow packages that require interactive install behavior in the community repository. Many users are wanting the ability to run unattended install and import. We're going to need to add an ability for a client to avoid showing results for non-silent installers, and respecting the users install mode preferences and requirements before we can change this policy.

https://github.com/microsoft/winget-cli/issues/910

**Review by ItzLevvie — APPROVED** [review]

**Comment by Sparticuz** [comment]
As a user of the program in question, I disagree with the idea that configurator is part of the installation process. It's part of the set of programs that gets installed. It would be impossible to set that up automatically because every computers output options are different.

Perhaps it's because it auto opens after installation?

**Comment by denelon** [comment]
The validation infrastructure is looking for a "0" return code after installation to determine success. If the configurator app launches and requires user input prior to getting the "0" return code, then it's treated as an "interactive only" installer.

**Pull request closed without merging**
