### PR TITLE
New version: MuhammadFareezIqmal.IIUMSchedule version 1.4.4.0

### PR DESCRIPTION
**Pull request by iqfareez**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150015)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-04-18 14:25:20.939 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFEA30CC11F: (caller: 00007FFEA2E58D6F) LogHr(1) tid(12fc) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFEA2FD2B08: (caller: 00007FFEA307BC20) Exception(1) tid(12fc) 8A15005E ] 
> 2024-04-18 14:25:20.941 [REPO] Failed to open available source: msstore
> 2024-04-18 14:25:28.304 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFE8BA5C11F: (caller: 00007FFE8B7E8D6F) LogHr(1) tid(1fcc) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFE8B962B08: (caller: 00007FFE8BA0BC20) Exception(1) tid(1fcc) 8A15005E ] 
> 2024-04-18 14:25:28.304 [REPO] Failed to open available source: msstore
> 2024-04-18 14:25:29.191 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x64 with version 14.38.33135.0

(Automated response - build 877.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-04-19 11:42:17.998 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFB5EF3069C: (caller: 00007FFB5EF373A9) Exception(1) tid(24f4) 800700B7 Cannot create a file when that file already exists. 
> 2024-04-19 11:42:18.006 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFB5EF3069C: (caller: 00007FFB5EF373A9) Exception(2) tid(24f4) 800700B7 Cannot create a file when that file already exists. 
> 2024-04-19 11:42:18.012 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFB5EF3069C: (caller: 00007FFB5EF373A9) Exception(3) tid(24f4) 800700B7 Cannot create a file when that file already exists. 
> 2024-04-19 11:42:18.018 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFB5EF3069C: (caller: 00007FFB5EF373A9) Exception(4) tid(24f4) 800700B7 Cannot create a file when that file already exists. 
> 2024-04-19 11:42:18.027 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFB5EF3069C: (caller: 00007FFB5EF373A9) Exception(5) tid(24f4) 800700B7 Cannot create a file when that file already exists. 
> 2024-04-19 11:42:18.035 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFB5EF3069C: (caller: 00007FFB5EF373A9) Exception(6) tid(24f4) 800700B7 Cannot create a file when that file already exists. 
> 2024-04-19 11:42:18.042 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFB5EF3069C: (caller: 00007FFB5EF373A9) Exception(7) tid(24f4) 800700B7 Cannot create a file when that file already exists. 
> 2024-04-19 11:42:18.050 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFB5EF3069C: (caller: 00007FFB5EF373A9) Exception(8) tid(24f4) 800700B7 Cannot create a file when that file already exists. 
> 2024-04-19 11:42:18.068 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFB5EF3069C: (caller: 00007FFB5EF373A9) Exception(9) tid(24f4) 800700B7 Cannot create a file when that file already exists. 
> 2024-04-19 11:42:18.138 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFB5EF3069C: (caller: 00007FFB5EF373A9) Exception(10) tid(24f4) 800700B7 Cannot create a file when that file already exists. 
> 2024-04-19 11:42:18.144 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFB5EF3069C: (caller: 00007FFB5EF373A9) Exception(11) tid(24f4) 800700B7 Cannot create a file when that file already exists. 
> 2024-04-19 11:42:18.165 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFB5EF3069C: (caller: 00007FFB5EF373A9) Exception(12) tid(24f4) 800700B7 Cannot create a file when that file already exists. 
> 2024-04-19 11:42:18.187 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFB5EF3069C: (caller: 00007FFB5EF373A9) Exception(13) tid(24f4) 800700B7 Cannot create a file when that file already exists. 
> 2024-04-19 11:42:18.199 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFB5EF3069C: (caller: 00007FFB5EF373A9) Exception(14) tid(24f4) 800700B7 Cannot create a file when that file already exists. 
> 2024-04-19 12:45:58.532 [FAIL] Installer failed security check. Url: https://github.com/iiumschedule/iium_schedule/releases/download/1.4.4%2B43/iiumschedulesetup.exe Result: 0x80004005 [1A04:1358][
> 2024-04-19T11:42:25]w363: Could not create system restore point, error: 0x80070422. Continuing... MSI (s) (80:88) [11:42:27:265]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.38.33135. Product Version: 14.38.33135. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (80:84) [11:42:27:781]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Additional Runtime - 14.38.33135. Product Version: 14.38.33135. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 877.)

**Comment by stephengillie** [comment]
Hi @iqfareez,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 877.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-04-19 17:32:41.059 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFCEB44C11F: (caller: 00007FFCEB1D8D6F) LogHr(1) tid(a3c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFCEB352B08: (caller: 00007FFCEB3FBC20) Exception(1) tid(a3c) 8A15005E ] 
> 2024-04-19 17:32:41.059 [REPO] Failed to open available source: msstore
> 2024-04-19 17:32:48.613 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFCD1E9C11F: (caller: 00007FFCD1C28D6F) LogHr(1) tid(195c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFCD1DA2B08: (caller: 00007FFCD1E4BC20) Exception(1) tid(195c) 8A15005E ] 
> 2024-04-19 17:32:48.613 [REPO] Failed to open available source: msstore
> 2024-04-19 17:32:49.872 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x64 with version 14.38.33135.0

(Automated response - build 877.)

**Comment by iqfareez** [comment]
Hmm. I think I will try bundling the vcredist with the installer. Will update the binary soon.

**Pull request closed without merging**
