### PR TITLE
Newer Version: Typst.Typst version 0.6.0

### PR DESCRIPTION
**Pull request by BrandonWanHuanSheng**
https://github.com/microsoft/winget-pkgs/pull/111477#issue-1791386735

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/111553&drop=dogfoodAlpha

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
@stephengillie, The Azure Pipelines keep saying 


> No commit pushedDate could be found for PR 111553 in repo microsoft/winget-pkgs

What is happening.

**Comment by BrandonWanHuanSheng** [comment]
@stephengillie It look like my pull request did not apply the label. Why this thing is happening?

> No commit pushedDate could be found for PR 111553 in repo microsoft/winget-pkgs

I did not see another pipelines have this issue

**Comment by BrandonWanHuanSheng** [comment]
When I try to close and reopened the pipelines, It apply no label. Only Waived-Validation-Executable-Error. Also, The Azure Pipelines did not add the label and it is also not running properly. Suppose, there are 3 label,

**Comment by BrandonWanHuanSheng** [comment]
stephengillie, 

It look like there is a validation bug after you have waived validation-executable-error. Also, the pull request is out of my control because Azure Pipelines keep commenting about this.


> No commit pushedDate could be found for PR 111553 in repo microsoft/winget-pkgs

Suppose, The Azure Pipelines need to say started successfully running one pipelines.

**Review by ItzLevvie — APPROVED** [review]

**Comment by BrandonWanHuanSheng** [comment]
It still won't work because https://github.com/microsoft/winget-pkgs/labels/Azure-Pipeline-Passed and https://github.com/microsoft/winget-pkgs/labels/Validation-Completed.is not yet added to my pull request. Also, Github will say the last comment when this one is added.

**Pull request merged**
