### PR TITLE
Update validation-pipeline.yaml

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
https://github.com/microsoft/winget-pkgs/issues/30321#issuecomment-943521645

Resolves #30321 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/30346)

### CODE REVIEW

**Review by ghost — DISMISSED** [review]

**Comment by Trenly** [comment]
> Yes, I was thinking if it could at least **list** the pipelines.

https://dev.azure.com/ms/winget-pkgs/_build

**Comment by Trenly** [comment]
> It can’t, since you aren’t a maintainer. ADO projects store pipelines in many repositories, being able to enumerate them even if you don’t have access to said repositories would be a security uh-oh. For this project, the only relevant ones are in this repo (and public in ADO), but that’s why you can’t use commands.
> 
> The reason I didn’t draft a PR was because I’m only 70% sure that that’s the problem (without being able to check the settings on the pipeline in ADO, I cannot be certain that’s what’s up). I was hoping the comment would get a maintainer to say “@jedieaston you dummy it was something completely different, here’s an explanation:”, or if it was the right answer, for them to do it since they’ll also have to go check the settings in ADO to make sure that they’re correct as well.



> It can’t, since you aren’t a maintainer. ADO projects store pipelines in many repositories, being able to enumerate them even if you don’t have access to said repositories would be a security uh-oh. For this project, the only relevant ones are in this repo (and public in ADO), but that’s why you can’t use commands.
> 
> The reason I didn’t draft a PR was because I’m only 70% sure that that’s the problem (without being able to check the settings on the pipeline in ADO, I cannot be certain that’s what’s up). I was hoping the comment would get a maintainer to say “@jedieaston you dummy it was something completely different, here’s an explanation:”, or if it was the right answer, for them to do it since they’ll also have to go check the settings in ADO to make sure that they’re correct as well.

I would also add that it appears that there is some form of automation which also updates the pipelines, so a Maintainer should also check to make sure that this wouldn't break that automation

**Review by ItzLevvie — COMMENTED** [review]
cc @msftrubengu

**Review by msftrubengu — CHANGES_REQUESTED** [review]

**Review by msftrubengu — APPROVED** [review]

**Comment by msftrubengu** [comment]
The behavior is the same. Internally in the DevOps configuration we had an override for the pr triggers with the same triggers that you added. I don't know what happened, but this is broken. I'll follow up with the DevOps team internally to find out what went wrong.

Untitled

**Pull request merged**
