### PR TITLE
New version: SomePythonThings.WingetUIStore.Pre-release version 3.1.1-beta1

### PR DESCRIPTION
**Pull request by schembriaiden**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161946)

### CODE REVIEW

**Comment by vikingnope** [comment]
Normal behaviour, can be merged

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
