### PR TITLE
New Version: Astronomer.Astro version 1.23.0

### PR DESCRIPTION
**Pull request by kushalmalani**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/139151)

### CODE REVIEW

**Review by sunkickr — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @kushalmalani,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 743.)

**Comment by stephengillie** [comment]
[Policy] Needs-Attention

**Comment by stephengillie** [comment]
[Policy] Validation-Defender-Error

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-14 14:16:25.368 [FAIL] Installer failed security check. Url: https://github.com/astronomer/astro-cli/releases/download/v1.23.0/astro_1.23.0_windows_386.exe Result: 0x80004005

(Automated response - build 743.)

**Comment by neel-astro** [comment]
@stephengillie I wanted to rerun the pipeline to ensure that it was a flaky false positive, but not being the owner of the PR I wasn't able to do it (as @kushalmalani is on leave). So I have created a separate PR (https://github.com/microsoft/winget-pkgs/pull/139441) with the same changes and it seems to be passing the tests.
Let me know if there are any steps required so we can get either of the PRs approved/merged, and thanks for all the debug info.

**Comment by neel-astro** [comment]
@stephengillie I have moved to use the `1.6.0` manifest version in https://github.com/microsoft/winget-pkgs/pull/139441, so would appreciate it if we could close this PR, and review that instead 🙂

**Comment by stephengillie** [comment]
Close with reason: Duplicate of #139441;

**Pull request closed without merging**
