### PR TITLE
New package: abhimanyu003.sttr 0.2.23

### PR DESCRIPTION
**Pull request by abhimanyu003**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/172705)

### CODE REVIEW

**Comment by abhimanyu003** [comment]
> ```
> @microsoft-github-policy-service agree
> ```

@microsoft-github-policy-service agree

**Comment by abhimanyu003** [comment]
I have tested it locally on windows and it's working fine, I would like to better understand why this is failing here.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-09-11 00:01:47.740 [FAIL] Installer failed security check. Url: https://github.com/abhimanyu003/sttr/releases/download/v0.2.23/sttr_0.2.23_windows_386.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 895.)

**Comment by abhimanyu003** [comment]
What could be wrong here, it's a simple go binary 🤔

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-09-11 18:32:08.271 [FAIL] Installer failed security check. Url: https://github.com/abhimanyu003/sttr/releases/download/v0.2.23/sttr_0.2.23_windows_amd64.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 895.)

**Comment by abhimanyu003** [comment]
Thanks Let me try to look for it and see. Will share update

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-09-12 19:45:08.865 [FAIL] Installer failed security check. Url: https://github.com/abhimanyu003/sttr/releases/download/v0.2.23/sttr_0.2.23_windows_amd64.zip Result: 0x80004005

(Automated response - build 895.)

**Comment by abhimanyu003** [comment]
This looks like a false positive.
Is it because this command line software can also run as TUI and take input in the terminal?
This is a Go binary, is there any known flag I can pass during the build to avoid this?

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-09-13 07:48:30.351 [FAIL] Installer failed security check. Url: https://github.com/abhimanyu003/sttr/releases/download/v0.2.23/sttr_0.2.23_windows_amd64.zip Result: 0x80004005

(Automated response - build 895.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-09-13 07:50:36.745 [FAIL] Installer failed security check. Url: https://github.com/abhimanyu003/sttr/releases/download/v0.2.23/sttr_0.2.23_windows_amd64.zip Result: 0x80004005

(Automated response - build 895.)

**Comment by stephengillie** [comment]
> This looks like a false positive. Is it because this command line software can also run as TUI and take input in the terminal? This is a Go binary, is there any known flag I can pass during the build to avoid this?

I have no idea. My VMs won't even complete the download due to the detected virus.
image

This is with the newest signature defintions that I can get:
image

**Comment by abhimanyu003** [comment]
I will try to boot up windows VM and see how it goes.

**Comment by stephengillie** [comment]
Sorry for the extended delay. Verify:
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
