### PR TITLE
New version: mpv.net version 7.1.0.0

### PR DESCRIPTION
**Pull request by soredake**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/133814)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978334972

(Automated response - build 563.)

**Comment by soredake** [comment]
Same error again https://github.com/microsoft/winget-pkgs/pull/131151#issuecomment-1885937544

I hope this will be fixed in future.

**Review by stephengillie — APPROVED** [review]

**Comment by stax76** [comment]
@soredake

Thanks for bringing v7.1.0.0 to winget!

**Pull request merged**
