### PR TITLE
New version: TechSmith.Snagit.2024 version 24.2.0.3285 (24.2.0)

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#7143](https://github.com/SpecterShell/Dumplings/actions/runs/10269090051).

<details>

<summary>Log</summary>

````
Updated: 24.1.4 → 24.2.0
No ReleaseNotes (en-US) for version 24.2.0
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/166375)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Comment by thangarajua** [comment]
Snagit 2024.2.2 released. can this be updated here?
https://support.techsmith.com/hc/en-us/articles/115006435067-Snagit-Windows-Version-History

**Pull request merged**
