### PR TITLE
Added Android Studio Beta 2020.3.1.20

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/19841)

### CODE REVIEW

**Comment by bearmannl** [comment]
@vedantmgoyal2009, please go ahead and rename the PackageIdentifier to Google.AndroidStudio.Beta, and then save the manifest under the corresponding folder structure: Google\AndroidStudio\Beta\2020.3.1

**Comment by vedantmgoyal2009** [comment]
ok

**Comment by vedantmgoyal2009** [comment]
> @vedantmgoyal2009, please go ahead and rename the PackageIdentifier to Google.AndroidStudio.Beta, and then save the manifest under the corresponding folder structure: Google\AndroidStudio\Beta\2020.3.1

please check now

**Comment by bearmannl** [comment]
@vedantmgoyal2009, go ahead and pull my changes if you want: https://github.com/bearmannl/winget-pkgs/tree/users/bearmannl/add-google-androidstudio-beta

**Comment by bearmannl** [comment]
> @vedantmgoyal2009, please go ahead and rename the PackageIdentifier to Google.AndroidStudio.Beta, and then save the manifest under the corresponding folder structure: Google\AndroidStudio\Beta\2020.3.1

@vedantmgoyal2009, don't forget the folder structure.

**Comment by vedantmgoyal2009** [comment]
> > @vedantmgoyal2009, please go ahead and rename the PackageIdentifier to Google.AndroidStudio.Beta, and then save the manifest under the corresponding folder structure: Google\AndroidStudio\Beta\2020.3.1
> 
> @vedantmgoyal2009, don't forget the folder structure.

@bearmannl folder structure modified and **Validation Successful**

**Comment by vedantmgoyal2009** [comment]
@bearmannl can you please tell me what I have to do for being a "reviewer with write access"

**Comment by bearmannl** [comment]
> @bearmannl can you please tell me what I have to do for being a "reviewer with write access"

@vedantmgoyal2009, I'm not one myself, just trying to be helpful. Someone from the team will be along to validate your PR once it gets the 'azure-pipelines-passed' label. You don't have to do anything else, it's automated from here.

**Comment by vedantmgoyal2009** [comment]
okay, thanks for replying

**Comment by bearmannl** [comment]
Also added a previous version to demonstrate the file structure, #19844

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Update the existing manifest.

**Comment by vedantmgoyal2009** [comment]
> Update the existing manifest.

Okay.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
You can close this PR and open up a new one to update the existing manifest.

**Comment by vedantmgoyal2009** [comment]
Okay

**Pull request closed without merging**
