### PR TITLE
Remembear 1.4.4.0

### PR DESCRIPTION
**Pull request by Dana-Pr**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1219)

### CODE REVIEW

**Comment by DanaBear** [comment]
@samiranshah Hey Samiranshah, could you help me? This installer cannot run without user input, user input is required. I am not sure how to fix the yaml file to indicate that :S 
Thanks for your help!

**Comment by denelon** [comment]
@Dana-Woo this PR is a bit old :smile:

We've made some substantial changes to the manifest schema. You could try to convert this to the new format or submit a "package request" issue.

**Comment by Dana-Woo** [comment]
@denelon I believe this new format won't work either, as the RememBear installer can't work silently and such a feature won't be implemented. Do I have any other options?
Thanks!

**Comment by denelon** [comment]
It looks like we're blocked until https://github.com/microsoft/winget-cli/issues/910 gets implemented so we can filter out interactive only installers from import.

What kind of a tool is RememBear? Is it commercial or open-source? Maybe there is a way to ask for silent support or see if someone can contribute.

**Comment by Dana-Woo** [comment]
@denelon It's a commercial app, so we wouldn't be able to get someone in the community to add the silent installer. 
The App is a password manager. 
We can close this PR if you'd like, or leave it open until microsoft/winget-cli#910 gets implemented :)

**Comment by denelon** [comment]
@Dana-Woo you've done the work of finding the meta-data and building a manifest. I'm fine leaving it open with "Blocking-Issue" so we can try again once that's implemented.

**Comment by Dana-Woo** [comment]
Okay, great, thanks! :)

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
Remembear is shutting down. No new user accounts can be created, and all current user accounts will be disabled on January 1st, 2024.  Since 1.4.4.0 is blocked due to interactive-only install and no new Remembear development is ongoing, to add this package is a moot point. 

https://www.remembear.com/blog/saying-goodbye-to-remembear/

Close with reason: Service shutting down;

**Pull request closed without merging**
