### PR TITLE
Manifest Update for Microsoft.OpenJDK.16 v16.0.1.9

### PR DESCRIPTION
**Pull request by OfficialEsco**
#13984
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/13986)

### CODE REVIEW

**Comment by d3vel0per** [comment]
Someone has already put in JDK 16. Just for my knowledge how do you figure out ProductCode attribute?

**Comment by OfficialEsco** [comment]
What the >:o
Microsoft Employee not follow PR requirements >:o

> Someone has already put in JDK 16. Just for my knowledge how do you figure out ProductCode attribute?

There is 2 ways, the safest way is to install the program then run `get-wmiobject Win32_Product | Sort-Object Name | Format-Table IdentifyingNumber, Name -AutoSize` (in powershell 5)

The other way which works most of the time only on MSI installers is `Get-AppLockerFileInformation -Path ".\Downloads\package.msi" | select -ExpandProperty Publisher`

**Comment by d3vel0per** [comment]
> What the >:o
> Microsoft Employee not follow PR requirements >:o
> 
> > Someone has already put in JDK 16. Just for my knowledge how do you figure out ProductCode attribute?
> 
> There is 2 ways, the safest way is to install the program then run `get-wmiobject Win32_Product | Sort-Object Name | Format-Table IdentifyingNumber, Name -AutoSize` (in powershell 5)
> 
> The other way which works most of the time only on MSI installers is `Get-AppLockerFileInformation -Path ".\Downloads\package.msi" | select -ExpandProperty Publisher`

Got it. Thank you 👍

**Comment by OfficialEsco** [comment]
Also @d3vel0per you can easily create/update new manifests with [/Tools/YamlCreate.ps1](https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1) then you can test your Manifest either on a VM or in Sandbox with this script [/Tools/SandboxTest.ps1](https://github.com/microsoft/winget-pkgs/blob/master/Tools/SandboxTest.ps1).

The WinGet team is currently working on `winget create` which will do the same but hopefully better/more advanced.

If you only need to update the Version, InstallerURL, Hash and ProductCode the simplest way is to copy paste the folder and hand editing the files

**Comment by d3vel0per** [comment]
> Also @d3vel0per you can easily create/update new manifests with [/Tools/YamlCreate.ps1](https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1) then you can test your Manifest either on a VM or in Sandbox with this script [/Tools/SandboxTest.ps1](https://github.com/microsoft/winget-pkgs/blob/master/Tools/SandboxTest.ps1).
> 
> The WinGet team is currently working on `winget create` which will do the same but hopefully better/more advanced.
> 
> If you only need to update the Version, InstallerURL, Hash and ProductCode the simplest way is to copy paste the folder and hand editing the files

Got it @OfficialEsco ! Had used the latter today for install verification. For manifest I just copied the template from JDK11 and updated it for 16 as needed(will have a look into the mentioned utility).
I had been using scoop as my package manager for longtime now. I has an utility for autogenerating updated manifests whenever a new version comes up but you need a fixed URL path which can be explored for newer versions. I think something like that will be useful here as well

**Comment by lychichem** [comment]
> What the >:o
> Microsoft Employee not follow PR requirements >:o
> 
> > Someone has already put in JDK 16. Just for my knowledge how do you figure out ProductCode attribute?
> 
> There is 2 ways, the safest way is to install the program then run `get-wmiobject Win32_Product | Sort-Object Name | Format-Table IdentifyingNumber, Name -AutoSize` (in powershell 5)
> 
> The other way which works most of the time only on MSI installers is `Get-AppLockerFileInformation -Path ".\Downloads\package.msi" | select -ExpandProperty Publisher`

These two ways listed seems useless for `Microsoft.VC++2015-2019-x86` and `Microsoft.VC++2015-2019-x64`, which report their productcode as `{4b2f3795-f407-415e-88d5-8c8ab322909d}` and `{dfea0fad-88b2-4a1f-8536-3f8f9391f4ef}` respectively, by using winget list
image
image

**Comment by OfficialEsco** [comment]
All programs do not have a ProductCode, some programs install sub packages which do have ProductCodes, but yes you are correct that `get-wmiobject` and `winget list` does infact show different ProductCode's, and i do actually see the same ProductCodes that you see on the same version.

Maybe @denelon can give a better answer

**Comment by denelon** [comment]
I'll put my reply in "general" terms to try and not be technically incorrect.

For MSIX installers we tend to rely on "Package Family Name" to do the matching against Add / Remove Programs (ARP) for the "list" logic.

For MSI installers we can typically parse out the "Product Code". We have a couple of related features to look at better means to capture them and report back to manifest authors. We're also doing some of this work with [`wingetcreate`](https://github.com/microsoft/wingetcreate).

When it comes to other installer formats resulting in a .exe much more variability exists.

**Pull request merged**
