### PR TITLE
[Zip] New Package: PolarGoose.ShowWhatProcessLocksFile 3.0

### LINKED ISSUE #82926: [Package Request]: ShowWhatProcessLocksFile
### Package Requested

- [ ] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [ ] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: PolarGoose
Publisher Url: https://github.com/PolarGoose/ShowWhatProcessLocksFile
Package Name: ShowWhatProcessLocksFile
Description: An utility to discover what processes lock a specific file or folder.
Package Version: 3.0
Installer URL: https://github.com/PolarGoose/ShowWhatProcessLocksFile/releases/tag/v3.0

Current Package Identifier (for new versions): 3.0

### PR DESCRIPTION
**Pull request by Trenly**
* Resolves #82926

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/88069)

### CODE REVIEW

**Comment by Trenly** [comment]
@msftbot zip

**Comment by Trenly** [comment]
@msftbot zip

**Review by ItzLevvie — DISMISSED** [review]

**Review by mdanish-kh — APPROVED** [review]

**Comment by Trenly** [comment]
@stephengillie - MSFTbot is on vacation

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
