### PR TITLE
EricLawrence.FiddlerNetLogImporter version 1.3.4.4

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/99338)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @upintheairsheep,

The installation isn't unattended - it has a message at the end of the install:
image

Is there an installer switch to bypass this?

**Comment by upintheairsheep** [comment]
https://dl.google.com/tag/s/appguid%3D%7BF7A0263C-9459-4A49-BDD5-AA35E1C35151%7D%26iid%3D%7B177D8BB7-4423-514F-CCE2-EEDCF41A1819%7D%26lang%3Den%26browser%3D4%26usagestats%3D0%26appname%3DGoogle%2520Ads%2520Editor%26needsadmin%3DFalse/adwords_editor/GoogleAdsEditorSetup.exe

**Comment by upintheairsheep** [comment]
http://appldnld.apple.com.edgesuite.net/content.info.apple.com/Safari3/061-4833.20080619.E45tg/SafariSetup.exe

**Comment by upintheairsheep** [comment]
http://appldnld.apple.com.edgesuite.net/content.info.apple.com/Safari3/061-4833.20080619.Vgfr5/SafariQuickTimeSetup.exe

**Pull request closed without merging**
