### PR TITLE
New version: Adobe.Acrobat.Reader.64-bit version 22.001.20085

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/50964)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by crrodriguez** [comment]
This version requires me to remove the old acrobat version ..then install fails with code 150201

**Comment by OfficialEsco** [comment]
It is probably telling you it detects another installertype? The fix for that is in the 1.3 preview version.

Gotta look into the installer exit code

**Comment by OfficialEsco** [comment]
@krystofkrticka

**Comment by krystofkrticka** [comment]
I see it does some problems to people which have non MUI version but the problem here is that managing 30 locales would be little bit tedious..

**Comment by crrodriguez** [comment]
> It is probably telling you it detects another installertype? The fix for that is in the 1.3 preview version.

Yes, it told me it detects another installer type and I have to uninstall. I did,

**Comment by OfficialEsco** [comment]
You uninstalled Acrobat Reader and now its giving you 150201? Try running it manually with `-i`

**Comment by krystofkrticka** [comment]
> It is probably telling you it detects another installertype? The fix for that is in the 1.3 preview version.

Yes, just updated other program with preview 1.3 and I saw that it was uninstalling the previous version.

**Comment by crrodriguez** [comment]
> You uninstalled Acrobat Reader and now its giving you 150201? Try running it manually with `-i`

I did..and it ended in the same error, this time in a GUI box of course,

**Comment by crrodriguez** [comment]
> > You uninstalled Acrobat Reader and now its giving you 150201? Try running it manually with `-i`
> 
> I did..and it ended in the same error, this time in a GUI box of course,

I have tried again using the latest 1.3 preview release and the situation is the same.

**Comment by krystofkrticka** [comment]
> > > You uninstalled Acrobat Reader and now its giving you 150201? Try running it manually with `-i`
> > 
> > 
> > I did..and it ended in the same error, this time in a GUI box of course,
> 
> I have tried again using the latest 1.3 preview release and the situation is the same.

Well this looks like you may need to use adobe's tool to remove leftovers of the application.

**Comment by krystofkrticka** [comment]
https://helpx.adobe.com/download-install/kb/uninstall-reinstall-acrobat.html in this help article from adobe there is link for their cleaner tool because it can happen that their installer don't work correctly, and you have to use their cleaner tool.

**Comment by krystofkrticka** [comment]
I was just googling this issue and I found other error which is few years old but when I read OPs post on that page it looks like their issue is similar to yours https://community.adobe.com/t5/acrobat-reader-discussions/what-is-error-150210/td-p/4741741

**Comment by crrodriguez** [comment]
I ran both the 32 bit and the 64 bit "Cleaner" and installation still fails.

**Comment by krystofkrticka** [comment]
Well that's weird, because that app was usually thing which helped me when I was trying to solve issues with Adobe Acrobat software no matter if it was Acrobat (the paid one) or Acrobat Reader that's the one we are talking about. I'm trying to replicate your issue but so far no luck of replicating it.

**Comment by crrodriguez** [comment]
> Well that's weird, because that app was usually thing which helped me when I was trying to solve issues with Adobe Acrobat software no matter if it was Acrobat (the paid one) or Acrobat Reader that's the one we are talking about. I'm trying to replicate your issue but so far no luck of replicating it. Which version you were using before trying to update?

The version just before this one I noticed that it switched the install from 32 bit version to 64 bit  too. but it otherwise worked fine.

**Comment by krystofkrticka** [comment]
Have you tried rebooting computer before running cleaner because windows sometimes tends to hold files and you can't delete them unless you reboot or kill process which is holding them.

**Review by ItzLevvie — APPROVED** [review]
​

**Comment by crrodriguez** [comment]
> Have you tried rebooting computer before running cleaner because windows sometimes tends to hold files and you can't delete them unless you reboot or kill process which is holding them.

Yes, I 've now tested the installer from http://get.adobe.com/es/reader/enterprise/ and selected the 32 bit MUI version and that installer actually work .. I jusdt don't want the 32bit version..

**Comment by crrodriguez** [comment]
unpacking the 64 bit MUI installer with 7-zip and running setup.exe , finally gave me a working acrobat reader 64 bit install. the self-extracting installer is maybe attempting to decompress in some wrong place.

**Comment by krystofkrticka** [comment]
That could happen that self extracting archive would be doing something weird. Also it could also have it's files extracted in temp directory and didn't delete it last Tim it was used and just tried to run that other installer. Some self extractors tend to do quite a mess on your drive because they don't delete files after they finish with installation.

**Pull request merged**
