### PR TITLE
Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\5.5.0

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114137&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
> 11:49:40 AM: 2023-08-08 11:49:39.369 [CLI ] ShellExecute installer failed: 1603
11:49:40 AM: CustomAction _67AC4AD8_6F00_4853_A52D_C3B81180AEFA returned actual error code 1602 (note this may not be 100% accurate if translation happened inside sandbox)
11:49:40 AM: MSI (s) (CC:C0) [11:49:38:774]: Product: OneMoreAddIn -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action _67AC4AD8_6F00_4853_A52D_C3B81180AEFA, location: C:\Program Files (x86)\River\OneMoreAddIn\OneMoreSetupActions.exe, command: --install --x86
11:49:40 AM: Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  Action _67AC4AD8_6F00_4853_A52D_C3B81180AEFA, location: C:\Program Files (x86)\River\OneMoreAddIn\OneMoreSetupActions.exe, command: --install --x86
11:49:40 AM: Property(S): ErrorDialog = ErrorDialog
11:49:40 AM: MSI (s) (CC:C0) [11:49:39:228]: Product: OneMoreAddIn -- Installation failed.
11:49:40 AM: MSI (s) (CC:C0) [11:49:39:228]: Windows Installer installed the product. Product Name: OneMoreAddIn. Product Version: 5.5.0. Product Language: 1033. Manufacturer: River. Installation success or error status: 1603.

**Pull request merged**
