### PR TITLE
New package: nCine.nCine version 2024.07

### PR DESCRIPTION
**Pull request by znarfm**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/163995)

### CODE REVIEW

**Comment by znarfm** [comment]
Resolves Issue #156110.
Related to #156129.

Working...
image

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-07-22 08:56:58.637 [FAIL] Installer failed security check. Url: https://github.com/nCine/nCine-artifacts/raw/nCine-master-windows-vs2022/nCine-
> 2024.07.r472-569fffc-Win64-VS2022.exe Result: 0x80004005 [20D8:0A8C][
> 2024-07-22T08:56:13]w363: Could not create system restore point, error: 0x80070422. Continuing... MSI (s) (9C:F4) [08:56:14:408]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.40.33810. Product Version: 14.40.33810. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (9C:E4) [08:56:14:752]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Additional Runtime - 14.40.33810. Product Version: 14.40.33810. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 886.)

**Comment by stephengillie** [comment]
Hi @znarfm,

The packge installs normally, but unfortunately doesn't seem to run when launched. Either directly, or from any of the links.

**Comment by znarfm** [comment]
Hmm, I don't seem to spot the problem on my end since it installs and opens using the `SandboxTest.ps1` on my local machine.

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
