### PR TITLE
New package: SecretsOPerationS.SOPS version 3.8.0

### PR DESCRIPTION
**Pull request by Okeanos**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/121524)

### CODE REVIEW

**Comment by Okeanos** [comment]
This is the designated successor to [Mozilla.SOPS](https://github.com/microsoft/winget-pkgs/pull/96198).

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Launching executable file: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\SecretsOPerationS.SOPS.3.8.0\sops-v3.8.0.exe
Exception during executable launch operation System.AggregateException: One or more errors occurred. (The system cannot find the file specified.)

**Review by stephengillie — APPROVED** [review]

**Comment by jetersen** [comment]
Could use a `Commands` section, created #124125
```yaml
Commands:
- sops
```

**Pull request merged**
