### PR TITLE
Adobe.Acrobat.Reader.32-bit - Changed installer to multi language installer

### PR DESCRIPTION
**Pull request by krystofkrticka**
Changed installer to MUI version so it detects OS language and installs correct Adobe Reader in correct language

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/40296)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
SEE >:O
VirtualBoxVM_itwKNNGITe

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
SEE >:O
VirtualBoxVM_itwKNNGITe

**Comment by krystofkrticka** [comment]
@OfficialEsco I know that is in 32-bit version I already wrote that in 64-bit thread

**Comment by OfficialEsco** [comment]
Ahhhh i only saw this comment, not the edit

> @OfficialEsco I did same change to 32 bit reader and that was just fine.

**Comment by krystofkrticka** [comment]
but when I try to create new package name like "Adobe.Acrobat.Reader.32-bit.MUI" it says:
image

**Comment by OfficialEsco** [comment]
ill wait for @ItzLevvie to share her thoughts, i'm not sure if there is a difference between the locale and MUI installer, but if there is we can't just overwrite their install

**Comment by krystofkrticka** [comment]
OK, no problem

**Comment by krystofkrticka** [comment]
Well just tried this myself but when I manually try to install MUI version over non-MUI version it says that I already have installed this product.

**Review by OfficialEsco — APPROVED** [review]
Alrighty then 🤷‍♂️

**Pull request merged**
