### PR TITLE
New version: Surfshark.Surfshark version 5.10.2.999

### PR DESCRIPTION
**Pull request by imfelixlaw**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/183381)

### CODE REVIEW

**Comment by imfelixlaw** [comment]
Hi, I have test install with local manifest before submit PR

`
C:\Users\Felix>winget install --manifest E:\github\winget-pkgs\manifests\s\Surfshark\Surfshark\5.10.2.999
Found Surfshark [Surfshark.Surfshark] Version 5.10.2.999
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://downloads.surfshark.com/windows/latest/SurfsharkSetup.exe
  ██████████████████████████████  84.3 MB / 84.3 MB
Successfully verified installer hash
Starting package install...
Successfully installed`

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-10-16 01:57:12.729 [CLI ] ShellExecute installer failed: 1603
> LookupUserGroupFromRid() FAILED
> LookupAccountSidW() FAILED
> LookupUserGroupFromRidSDDL() FAILED
> LookupAliasFromRid() FAILED
> [SC] OpenService FAILED 1060:
> ERROR: The process "Surfshark.AntivirusService.exe" not found.
> CustomAction StopAndRemoveAVService returned actual error code 1603 but will be translated to success due to continue marking
> MSI (s) (34:E0) [01:57:11:133]: Product: Surfshark -- Error 1606. Could not access network location Surfshark.
> Error 1606. Could not access network location Surfshark.
> Property(S): ErrorDialog = ErrorDlg
>    Write-Output "ERROR: $($_.Exception.Message)"
>    Exit 0x23E #ERROR_UNHANDLED_EXCEPTION
> Property(S): POWERSHELL_EXECUTION_LOG = [SC] OpenService FAILED 1060:
> Property(S): OutOfDiskSpace = 0
> Property(S): OutOfNoRbDiskSpace = 0
> Property(S): PrimaryVolumeSpaceAvailable = 0
> Property(S): PrimaryVolumeSpaceRequired = 0
> Property(S): PrimaryVolumeSpaceRemaining = 0

Automated error analysis suggests -1978335226 may mean Running ShellExecute failed

Automated error analysis suggests 1603 may mean Previous MSI installer is missing (Or it might mean Install successful but system restart may be required.) Should this be add as an `InstallerSuccessCode` or similar?

Automated error analysis suggests 1606 may mean `ERROR_UNKNOWN_FEATURE` - Feature ID not registered.

(Automated response - build 897.)

**Comment by imfelixlaw** [comment]
> Automatic Validation ended with:
> 
> > Installation failed with exit code -1978335226
> > 2024-10-16 01:57:12.729 [CLI ] ShellExecute installer failed: 1603
> > LookupUserGroupFromRid() FAILED
> > LookupAccountSidW() FAILED
> > LookupUserGroupFromRidSDDL() FAILED
> > LookupAliasFromRid() FAILED
> > [SC] OpenService FAILED 1060:
> > ERROR: The process "Surfshark.AntivirusService.exe" not found.
> > CustomAction StopAndRemoveAVService returned actual error code 1603 but will be translated to success due to continue marking
> > MSI (s) (34:E0) [01:57:11:133]: Product: Surfshark -- Error 1606. Could not access network location Surfshark.
> > Error 1606. Could not access network location Surfshark.
> > Property(S): ErrorDialog = ErrorDlg
> > Write-Output "ERROR: $($_.Exception.Message)"
> > Exit 0x23E #ERROR_UNHANDLED_EXCEPTION
> > Property(S): POWERSHELL_EXECUTION_LOG = [SC] OpenService FAILED 1060:
> > Property(S): OutOfDiskSpace = 0
> > Property(S): OutOfNoRbDiskSpace = 0
> > Property(S): PrimaryVolumeSpaceAvailable = 0
> > Property(S): PrimaryVolumeSpaceRequired = 0
> > Property(S): PrimaryVolumeSpaceRemaining = 0
> 
> Automated error analysis suggests -1978335226 may mean Running ShellExecute failed
> 
> Automated error analysis suggests 1603 may mean Previous MSI installer is missing (Or it might mean Install successful but system restart may be required.) Should this be add as an `InstallerSuccessCode` or similar?
> 
> Automated error analysis suggests 1606 may mean `ERROR_UNKNOWN_FEATURE` - Feature ID not registered.
> 
> (Automated response - build 897.)

I have compared with the old manifest version 5.8.2.999 I think is not much different with this commit

**Comment by stephengillie** [comment]
Close with reason: Duplicate of #183766;

**Pull request closed without merging**
