### PR TITLE
Remove unnecessary DisplayVersion from MusicBrainz.Picard version 2.8.30000.0

### PR DESCRIPTION
**Pull request by mdanish-kh**
Issue https://www.github.com/microsoft/winget-pkgs/issues/138520 describes scenarios where DisplayVersion should not be used. This PR removes unnecessary DisplayVersion from the manifest file.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/191197)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://github.com/metabrainz/picard/releases/download/release-2.8.3/MusicBrainz-Picard-2.8.3.msix 
Status Code: 200

(Automated message - build 897)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://github.com/metabrainz/picard/releases/download/release-2.8.3/MusicBrainz-Picard-2.8.3.msix 
Status Code: 200

(Automated message - build 897)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://github.com/metabrainz/picard/releases/download/release-2.8.3/MusicBrainz-Picard-2.8.3.msix 
Status Code: 200

(Automated message - build 897)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://github.com/metabrainz/picard/releases/download/release-2.8.3/MusicBrainz-Picard-2.8.3.msix 
Status Code: 200

(Automated message - build 897)

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://github.com/metabrainz/picard/releases/download/release-2.8.3/MusicBrainz-Picard-2.8.3.msix 
Status Code: 200

(Automated message - build 898)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://github.com/metabrainz/picard/releases/download/release-2.8.3/MusicBrainz-Picard-2.8.3.msix 
Status Code: 200

(Automated message - build 899)

**Comment by Trenly** [comment]
```
2024-11-13 12:39:00.576 [CORE] Deployment operation #1: Windows cannot remove MetaBrainzFoundationInc.org.musicbrainz.Picard_2.8.30000.0_x64__6cfbg5p5jt8h8 because the current user does not have that package installed. Use Get-AppxPackage to see the list of packages installed.
2024-11-13 12:39:00.576 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFC41642D2F: (caller: 00007FFC4164432C) Exception(2) tid(1090) 80073CF1 Package was not found.

    Msg:[Operation failed: Windows cannot remove MetaBrainzFoundationInc.org.musicbrainz.Picard_2.8.30000.0_x64__6cfbg5p5jt8h8 because the current user does not have that package installed. Use Get-AppxPackage to see the list of packages installed.] 

2024-11-13 12:39:00.577 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(126)\WindowsPackageManager.dll!00007FFC417B8931: (caller: 00007FFC41645853) LogHr(1) tid(1090) 80073CF1 Package was not found.

    Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFC41642D2F: (caller: 00007FFC4164432C) Exception(2) tid(1090) 80073CF1 Package was not found.

    Msg:[Operation failed: Windows cannot remove MetaBrainzFoundationInc.org.musicbrainz.Picard_2.8.30000.0_x64__6cfbg5p5jt8h8 because the current user does not have that package installed. Use Get-AppxPackage to see the list of packages installed.] 
] 

2024-11-13 12:39:00.811 [CLI ] MSIX installer failed: 2148204801
2024-11-13 12:39:00.812 [CLI ] Terminating context: 0x800b0101 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:1fd
```

**Comment by stephengillie** [comment]
URL: https://github.com/metabrainz/picard/releases/download/release-2.8.3/MusicBrainz-Picard-2.8.3.msix 
Status Code: 200

(Automated message - build 902)

**Comment by stephengillie** [comment]
URL: https://github.com/metabrainz/picard/releases/download/release-2.8.3/MusicBrainz-Picard-2.8.3.msix 
Status Code: 200

(Automated message - build 903)

**Comment by stephengillie** [comment]
URL: https://github.com/metabrainz/picard/releases/download/release-2.8.3/MusicBrainz-Picard-2.8.3.msix 
Status Code: 200

(Automated message - build 903)

**Comment by stephengillie** [comment]
URL: https://github.com/metabrainz/picard/releases/download/release-2.8.3/MusicBrainz-Picard-2.8.3.msix 
Status Code: 200

(Automated message - build 904)

**Comment by stephengillie** [comment]
URL: https://github.com/metabrainz/picard/releases/download/release-2.8.3/MusicBrainz-Picard-2.8.3.msix 
Status Code: 200

(Automated message - build 904)

**Pull request merged**
