### PR TITLE
Create 1.0.1.yaml

### PR DESCRIPTION
**Pull request by chrpai**
Microsoft Sysinternals Suite installer

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1288)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
I spoke to the owner of the tools.  He does not want the tools sourced from another location.  We are currently blocked on 
Add SysInternals tools #650 
Open Support installing .zip files microsoft/winget-cli#140

Please consider closing this PR.

**Comment by chrpai** [comment]
The tool isn't being sourced from another location.  The automation downloads the content from https://download.sysinternals.com/files/SysinternalsSuite.zip  in a way that most chocolatey packages work.

I see dozens of packages in winget.  Did MSFT talk to all of those authors to see if they approve of being in WinGet or does MSFT VPs get special consideration?

FWIW, the automation is all MS-PL and I'm willing to assign all of it to MSFT if that's what it takes to have progress.    SysInternals thinking that it doesn't need an installer and that a proper distribution mechanism is to be on a publicly accessible SMB share (\\live.sysinternals.com\tools\) is just thinking that is stuck in the 1990s.

**Comment by darkpixel** [comment]
Microsoft is stuck in the 90s.

What package management they do have is fragmented and buggy...with the best of these being Windows Installer...and because of some "super secret" reason, Mark and/or Microsoft doesn't want to create an MSI file.

Lame.

**Comment by denelon** [comment]
@darkpixel this is a very old PR.

Sysinternals has been built into an MSIX package and is available via the Microsoft Store.
`winget install "Sysinternals Suite"` should do the trick.

In addition, WinGet supports .zip-based packages for installers and portable apps. Several of the individual sysinternals applications are available:

```text
winget search sysinternals
Name                              Id                                     Version Match             Source
----------------------------------------------------------------------------------------------------------
Sysinternals Suite                9P7KNL5RWT25                           Unknown                   msstore
Process Monitor                   Microsoft.Sysinternals.ProcessMonitor  3.93    Tag: Sysinternals winget
Process Explorer                  Microsoft.Sysinternals.ProcessExplorer 17.04   Tag: sysinternals winget
Autoruns                          Microsoft.Sysinternals.Autoruns        14.09   Tag: Sysinternals winget
Desktops                          Microsoft.Sysinternals.Desktops        2.01    Tag: Sysinternals winget
BGInfo                            Microsoft.Sysinternals.BGInfo          4.32    Tag: Sysinternals winget
TCPView                           Microsoft.Sysinternals.TCPView         4.19    Tag: sysinternals winget
ZoomIt                            Microsoft.Sysinternals.ZoomIt          7.0     Tag: sysinternals winget
Remote Desktop Connection Manager Microsoft.Sysinternals.RDCMan          2.92                      winget
```

**Comment by darkpixel** [comment]
...and winget is built in to Windows 10 and 11 like msiexec is? ;)

**Comment by denelon** [comment]
Yes.
WinGet is shipped via "App Installer" in Windows 10 and Windows 11.
WinGet goes down level to Windows 10 RS5.
The Microsoft Store provides automatic updates for the "App Installer", so the latest version is available for Windows 10 and Windows 11.

**Comment by darkpixel** [comment]
I'm not going to drag on a long-since closed PR...but I can see package management is still a dumpster fire.

It looks like the "App Installer" (found here: https://apps.microsoft.com/store/detail/app-installer/9NBLGGH4NNS1) is part of the Microsoft Store ecosystem.

...none of our ~400 Windows Workstations appear to have the Windows Store on them.

With next to zero knowledge of this new system, I checked both "Add/Remove Programs" -> "Optional Features" and the confusingly similarly named "Turn Windows Features On/Off" and there's no mention of the Windows Store.

Did some more digging and found it's part of the new AppxPackage package system (yay--another package management tool) and there's some info for reinstalling it here: https://answers.microsoft.com/en-us/windows/forum/all/how-to-reinstall-microsoft-store-app-in-windows-10/e9d71c80-8399-49d5-9d92-a18add81a4dc

Just a simple...
```
Get-AppXPackage *WindowsStore* -AllUsers | Foreach {Add-AppxPackage -DisableDevelopmentMode -Register "$($_.InstallLocation)\AppXManifest.xml"}
```

Well...that got the store back on my test box...but no 'winget' command.

*more googling*

I guess I have to manually launch the store on ~400 workstations, search for "App Installer" and then install it?

Wait... https://christitus.com/installing-appx-without-msstore/ says I just have to run:
```
Set-PSRepository -Name 'PSGallery' -InstallationPolicy Trusted
Install-Script -Name winget-install -Force
winget-install.ps1
```
And I'll have winget installed.

Oh look...it's installing NuGet.  How many different package managers are we up to now?  4?  5?

But I guess winget is installed now.

Let's try this...

Screenshot from 2023-06-14 16-06-33

Oh...a prompt?  That'll scale well when trying to automate deploying to ~400 machines.

All that just to get sysinternals because Microsoft doesn't want to package it as an MSI?

Nevermind.  I'll just uninsta...oh....I can't uninstall App Installer or Windows Store from Add/Remove Programs because it's greyed out.

Like I said initially...packaging dumpster fire...

**Comment by denelon** [comment]
You can add "--accept-package-agreements" and there is no prompt.

**Pull request closed without merging**
