### PR TITLE
Remove version: bloodrock.pkg-config-lite version 0.28-1

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/181625)

### CODE REVIEW

**Comment by Trenly** [comment]
[Policy] Highest Version Removal

**Comment by stephengillie** [comment]
URL: https://zenlayer.dl.sourceforge.net/project/pkgconfiglite/0.28-1/pkg-config-lite-0.28-1_bin-win32.zip 
Status Code: 200

(Automated message - build 896)

**Comment by stephengillie** [comment]
URL: https://zenlayer.dl.sourceforge.net/project/pkgconfiglite/0.28-1/pkg-config-lite-0.28-1_bin-win32.zip 
Status Code: 200

(Automated message - build 896)

**Review by stephengillie — APPROVED** [review]

**Comment by lygstate** [comment]
Does not make sense, it's can downloading now.

**Pull request merged**
