### PR TITLE
New version: RussellBanks.HashHash version 1.2.0

### PR DESCRIPTION
**Pull request by russellbanks**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/59830)

### CODE REVIEW

**Comment by russellbanks** [comment]
Unless it's not good to delete all old packages at once, I'm unsure what's wrong with this PR

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> Unless it's not good to delete all old packages at once, I'm unsure what's wrong with this PR

You'll need to open up 2-3 more PRs to remove each version.

**Comment by russellbanks** [comment]
> You'll need to open up 2-3 more PRs to remove each version.

Thanks for the feedback. Resolved.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
