### PR TITLE
New version: SonicWALL.NetExtender version 10.2.338

### PR DESCRIPTION
**Pull request by Ganesh-ITMA**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/134000)

### CODE REVIEW

**Comment by Ganesh-ITMA** [comment]
@microsoft-github-policy-service agree company="ITMA"

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335226 2024-01-15 01:04:16.998 [CLI ] ShellExecute installer failed: 1603 MSI (s) (1C:A4) [00:58:33:886]: Error: cannot register 64 bit component {126CDDF0-1850-4C99-ADE3-1335B26C4CEB} on 32 bit system. KeyPath: C:\Program Files\SonicWall\SSL-VPN\NetExtender\ InstallClientProtection:  Install offload task failed, exit with code: -1 CustomAction InstallClientProtection returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox) Property(S): ErrorDialog = ErrorDialog MSI (s) (1C:A4) [01:04:16:823]: Product: SonicWall NetExtender -- Installation operation failed. MSI (s) (1C:A4) [01:04:16:823]: Windows Installer installed the product. Product Name: SonicWall NetExtender. Product Version: 10.2.338. Product Language: 1033. Manufacturer: SonicWall Inc.. Installation success or error status: 1603.

(Automated response - build 570.)

**Comment by stephengillie** [comment]
Hi @Ganesh-ITMA,

This manifest adds Apps and Features entries that aren't present in previous PR versions. Should these entries also be added to the previous versions?

(Automated response - build 571.)

**Review by stephengillie — APPROVED** [review]

**Comment by Ganesh-ITMA** [comment]
Hi @stephengillie 

Appears that Komac must of added the UpgradeCode when updating this package. It looks like the previous version has had the same upgrade code but wasn't included on the manifest. I'm unsure whether this is required on previous entries as this is my first upgrade that I've done but I don't think it will hurt to add them?

**Comment by stephengillie** [comment]
> Hi @stephengillie
> 
> Appears that Komac must of added the UpgradeCode when updating this package. It looks like the previous version has had the same upgrade code but wasn't included on the manifest. I'm unsure whether this is required on previous entries as this is my first upgrade that I've done but I don't think it will hurt to add them?

I'm not completely sure with Apps and Features either, but this has come up enough that I automated asking. 

@Trenly and @mdanish-kh, could you advise on applying Apps and Features to previous versions here?

**Comment by Trenly** [comment]
> @stephengillie UpgradeCode is not exclusive to AppsAndFeaturesEntries. It can exist under the manifest (root) level, and at the installer level also. It's an optional field that improves package correlation for MSIs. Having it defined is better, but it's not all that important in this case where correlation already looks solid to me with `PackageName`, `Publisher` and `ProductCode` fields

This is incorrect. UpgradeCode is only used in AppsAndFeaturesEntries according to the manifest specification - 

https://github.com/search?q=repo%3Amicrosoft%2Fwinget-cli%20UpgradeCode%20path%3Amanifest.installer.1.6.0.json&type=code

The `ProductCode` can be at any level, but Upgrade Code is only in AppsAndFeaturesEntries

**Comment by mdanish-kh** [comment]
Oopsiesss....not sure how I mixed up `ProductCode` & `UpgradeCode` . Thanks for correcting my mistake; Though I think this bit is still valid:

> Having it defined is better, but it's not all that important in this case where correlation already looks solid to me with PackageName, Publisher and ProductCode fields

**Pull request merged**
