### PR TITLE
New version: o2sh.onefetch version 2.13.2

### PR DESCRIPTION
**Pull request by o2sh**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/86991)

### CODE REVIEW

**Comment by o2sh** [comment]
Hi, Is there something preventing this PR from being merged?

**Comment by o2sh** [comment]
Should be good now 👍

**Comment by o2sh** [comment]
@AmelBawa-msft ping

**Review by stephengillie — DISMISSED** [review]

**Review by stephengillie — APPROVED** [review]

**Comment by o2sh** [comment]
Hello @stephengillie, 
Is there a reason why this version hasn't been published yet?

Thanks in advance for your response.

**Comment by o2sh** [comment]
Thanks @Trenly

**Pull request merged**
