### PR TITLE
Remove version: Prog.ProgDVB.Professional version 7.60.8

### PR DESCRIPTION
**Pull request by damn-good-b0t**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/171081)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://files.progdvb.com/progdvb/ProgDVB7.60.8Pro.exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 894)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://files.progdvb.com/progdvb/ProgDVB7.60.8Pro.exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 894)

**Comment by stephengillie** [comment]
URL: https://files.progdvb.com/progdvb/ProgDVB7.60.8Pro.exe 
Response status code does not indicate success: 404 (Not Found).

(Automated message - build 895)

**Comment by ItzLevvie** [comment]
Close with reason: PR not needed anymore because the version was already removed;

**Pull request closed without merging**
