### PR TITLE
ProtonVPN update v1.17.5

### PR DESCRIPTION
**Pull request by mloskot**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/5007)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
image

Seems to have an error code on install.  this may be blocked on the update to have a different return value.

**Comment by mloskot** [comment]
@KevinLaMS It worked for me. Sorry, but I'm not yet enough experienced with the winget or installers to understand what's going wrong or how to fix it :-(

**Comment by OfficialEsco** [comment]
@mloskot i think you can close this one as 1.18.5 and 1.20.1 have been added, i don't know if @KevinLaMS used the Silent switch (that seems to be broken), if so that might be why it failed for him and worked for you.
Also this manifest is out of date since manifest version 1.0.0

**Comment by mloskot** [comment]
Closing as per @OfficialEsco suggestion https://github.com/microsoft/winget-pkgs/pull/5007#issuecomment-827374058

**Pull request closed without merging**
