### PR TITLE
Update manifests/n/NGWIN/PicPick/7.2.2/NGWIN.PicPick.locale.en-US.yaml

### PR DESCRIPTION
**Pull request by Trenly**
Fixes an issue where this package has multiple different monikers
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/181024)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 

(Automated response - build 896.)

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://www.picpick.org/releases/7.2.2/picpick_inst.exe 
Status Code: 200

(Automated message - build 896)

**Comment by Trenly** [comment]
@stephengillie - Even if users attempt to install, it will just result in a hash mismatch

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
[Policy] Reset Labels

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
