### PR TITLE
New package: Mapillary.MapillaryUploader version 4.3.0

### LINKED ISSUE #152226: [Package Request]: Mapillary Uploader
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.mapillary.com/desktop-uploader
Publisher: Meta
Package Name: Mapillary Uploader
Description: The Mapillary Desktop Uploader is a desktop application that enables uploading Mapillary imagery in bulk.
Package Version: 4.3.0
Installer URL: https://tools.mapillary.com/uploader/download/win

### PR DESCRIPTION
**Pull request by BiosPlus**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.2.1 :rocket:

- Resolves: #152226

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/152228)

### CODE REVIEW

**Comment by vikingnope** [comment]
@BiosPlus, kindly change architecture to x64

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 880.)

**Comment by BiosPlus** [comment]
Apologies for the delay, the flu has knocked me on my back 😅

**Comment by stephengillie** [comment]
Verify: 
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
