### PR TITLE
Add Tencent Tim

### LINKED ISSUE #492: CI timeout but still running
#279 has running over 24h and the CI timeout
```
5/20/2020 5:00:58 PM
Status: Completed
##[error] Result: Failed
##vso[task.logissue type=error] Operation timed out.
```

But it's still running.

The pr is opened by me, but I don't know why it takes so long time to Installer scan

### PR DESCRIPTION
**Pull request by YadominJinta**
Add Tencent Tim.

It's a popular IM in China.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/279)

### CODE REVIEW

**Comment by YadominJinta** [comment]
Is the CI stuck?

**Comment by zachcarp** [comment]
The CI doesn't appear to be stuck. Some installers can take longer than others to finish that stage. If it continues for over 48 hours, please let us know by submitting an issue.

**Comment by denelon** [comment]
Kicking this off again to see if the same error persists " The remote server returned an error: (401) Unauthorized."

**Comment by denelon** [comment]
https://github.com/microsoft/winget-pkgs/issues/492

**Pull request closed without merging**
