### PR TITLE
Correct information about MinIO.Client 2023.07.07

### PR DESCRIPTION
**Pull request by stevapple**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

Note for reviewers: Due to changing the publisher ID from `Minio` to `MinIO`, `MinIO.Server` manifests were renamed unevitably. Corresponding changes will be submitted in future PRs.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135917)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
Only one manifest can be modified per pull request. To change PackageIdentifier will require separate PRs - one to remove from the old identifier and one to add it back in the new identifier

**Comment by stevapple** [comment]
Please tell me a way to achieve this. AFAIK there's no way to update the case of parent directory for a single subdirectory in Git. It will automatically propagate to all subdirectories.
________________________________

**Comment by Trenly** [comment]
> Please tell me a way to achieve this. AFAIK there's no way to update the case of parent directory for a single subdirectory in Git. It will automatically propagate to all subdirectories.
> […](#)
> ________________________________

You will need to process all the removals and then re-add them individually

**Comment by stephengillie** [comment]
> Please tell me a way to achieve this. AFAIK there's no way to update the case of parent directory for a single subdirectory in Git. It will automatically propagate to all subdirectories.
> […](#)
> ________________________________

Correct - all packages will need to be removed, and then re-added with the correct case. And each version in its own PR. 

Please note that the `.validation` files are a somewhat protected, and are triggering the `Unexpected-File` label. It works a little better for each of these to be removed in its own PR as well. To readd these, I'll have to review and re-apply the waiver to the readded package. (It will look like a new package to most of our systems.)

**Comment by stevapple** [comment]
Now that the removal has completed (thanks to having only two releases), this PR is superseded by #136158 and #136159. Thank you @Trenly and @stephengillie!

**Comment by stevapple** [comment]
> To readd these, I'll have to review and re-apply the waiver to the readded package. (It will look like a new package to most of our systems.)

BTW I don’t think the waiver is required any more. MinIO kept all prior releases, so the validation always worked if the installer URL is set to a permanent one.

**Pull request closed without merging**
