### PR TITLE
New package: RODE.RODECentral version 2.0.41

### PR DESCRIPTION
**Pull request by jahvari**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/129560)

### CODE REVIEW

**Comment by jahvari** [comment]
@stephengillie I am not sure what the command is to retry the pipeline, are you able to retry it?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335141

**Comment by stephengillie** [comment]
> @stephengillie I am not sure what the command is to retry the pipeline, are you able to retry it?

One sure way to trigger another run is to make any change to the manifest, including an arbitrary change such as adding a space or line break.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Windows\Installer\{89A4A3E3-CCF0-40E9-9B73-6C28AA33F932}\RODECentral.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Windows\Installer\{89A4A3E3-CCF0-40E9-9B73-6C28AA33F932}\RODECentral.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Windows\Installer\{D742CB1C-CAA5-4675-AD29-9B0EE782A3C9}\icon.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Windows\Installer\{D742CB1C-CAA5-4675-AD29-9B0EE782A3C9}\icon.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.

**Comment by stephengillie** [comment]
Manual Validation ended with:
> PS C:\Users\User\Desktop> &"C:\Windows\Installer\{89A4A3E3-CCF0-40E9-9B73-6C28AA33F932}\RODECentral.exe" Program 'RODECentral.exe' failed to run: The specified executable is not a valid application for this OS platform.

**Comment by jahvari** [comment]
@stephengillie I am unable to duplicate that error. It installs just fine on my windows 10 machine.

**Comment by stephengillie** [comment]
Hi @jahvari,

I might be launching it incorrectly. What is the normal way of interacting with this application?

**Comment by jahvari** [comment]
@stephengillie It is just a normal application. You install it, and then launch it. It seems to work just fine on PC that runs Windows 10.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Windows\Installer\{89A4A3E3-CCF0-40E9-9B73-6C28AA33F932}\RODECentral.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Windows\Installer\{89A4A3E3-CCF0-40E9-9B73-6C28AA33F932}\RODECentral.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Windows\Installer\{D742CB1C-CAA5-4675-AD29-9B0EE782A3C9}\icon.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Windows\Installer\{D742CB1C-CAA5-4675-AD29-9B0EE782A3C9}\icon.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> Faulting application name: RODE Central.exe, version: 2.0.41.0, time stamp: 0x6555fc47 
> Faulting module name: RODE Central.exe, version: 2.0.41.0, time stamp: 0x6555fc47 Exception code: 0xc0000005 Fault offset: 0x00000000008f4b46 
> Faulting process id: 0x2a54 
> Faulting application start time: 0x01da33757fb27cb3 
> Faulting application path: C:\Program Files\RØDE Microphones\RODE Central\RODE Central.exe 
> Faulting module path: C:\Program Files\RØDE Microphones\RODE Central\RODE Central.exe Report Id: 9b90e742-72b9-42a4-8a5a-fbe8ef0675e7 
> Faulting package full name:  
> Faulting package-relative application ID: 

(Automated response - build 487.)

**Comment by stephengillie** [comment]
In a Windows 10 VM, the application has both as Desktop shortcut and a Start menu shortcut. But launching with either generates the error above. 
- Does this package have any software dependencies? 
- Does this package work if there's no microphone plugged in?

**Pull request closed without merging**
