### PR TITLE
Modify: JetBrains.CLion version 2024.1

### PR DESCRIPTION
**Pull request by SpecterShell**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150717)

### CODE REVIEW

**Comment by 2505lis** [comment]
Одобряю

**Comment by stephengillie** [comment]
Hi @SpecterShell,

> This PR's version number 2024.1 has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 2024.1.1, which has 3 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 878)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
