### PR TITLE
Update version: DuckStudio.FufuTools version 1.3.2

### PR DESCRIPTION
**Pull request by CoolPlayLin**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/160522)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by DuckDuckStudio** [comment]
CC @DuckDuckStudio & @Luna-Grace

**Comment by CoolPlayLin** [comment]
@DuckDuckStudio you can decide whether set your manifest as requiring to be approved. If you agree, all the PRs that change you manifests will require your approval and @stephengillie 's automation will note you in time.

**Comment by CoolPlayLin** [comment]
image

**Pull request merged**
