### PR TITLE
the-sz.Trion version 1.16

### PR DESCRIPTION
**Pull request by the-sz**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/100432)

### CODE REVIEW

**Comment by the-sz** [comment]
Where can I see whats wrong?

image

Says "[0 errors / 0 warnings]"

**Comment by stephengillie** [comment]
Hi the-sz,

Unfortunately, this package doesn't pass a Defender scan:
image

**Comment by the-sz** [comment]
VirusTotal has a different opinion:
https://www.virustotal.com/gui/file/3a26419464124c53bdb2ec870ab0356c29469859eb52e90ccfdc5cea75048979
https://www.virustotal.com/gui/file/9b43b9c7d22f709358ca601d97843b5ee3f9dde4af83754176d710aae6ba06a1
hmmm

**Comment by the-sz** [comment]
what can I do? Virustotal doesn't see a virus, and there is no virus, I'm the author...

**Comment by stephengillie** [comment]
> what can I do? Virustotal doesn't see a virus, and there is no virus, I'm the author...

Can you run a Defender scan, after updating the virus signatures? I found it using signature version 1.385.98.0.

**Comment by the-sz** [comment]
seems you are out of date: mine is at 1.385.1369.0

image

**Pull request closed without merging**
