### PR TITLE
New version: advaith.CurrencyConverterPowerToys version 1.4.0

### PR DESCRIPTION
**Pull request by Advaith3600**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/195078)

### CODE REVIEW

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Comment by Advaith3600** [comment]
@stephengillie how do I complete the WinGetSvc-Validation? I believe I have already done that for the previous PRs.

**Comment by ItzLevvie** [comment]
[Policy] Reset Feedback

**Comment by ItzLevvie** [comment]
[Policy] Reset Labels

**Comment by ItzLevvie** [comment]
[Policy] Moderator-Approved

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]
a

**Comment by ItzLevvie** [comment]
[Policy] Needs-Manual-Merge

**Pull request merged**
