### PR TITLE
New version: deviceinsight.kafkactl-azure-plugin 1.0.4

### PR DESCRIPTION
**Pull request by d-rk**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/144296)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @d-rk,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\deviceinsight.kafkactl-azure-plugin__DefaultSource\kafkactl-azure-plugin.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\kafkactl-azure-plugin.exe returned exit code: 1
> Installation failed with exit code -1978335187
> 2024-03-14 04:16:02.352 [FAIL] Installer failed security check. Url: https://github.com/deviceinsight/kafkactl-plugins/releases/download/v1.0.4/kafkactl-azure-plugin_1.0.4_windows_386.zip Result: 0x80004005

(Automated response - build 870.)

**Comment by d-rk** [comment]
Hey @stephengillie ,

is this the same issue like my [other PR](https://github.com/microsoft/winget-pkgs/pull/144295) which got merged recently?
Does the Pipeline also need to be retriggered?

Thank you for your help!

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\deviceinsight.kafkactl-azure-plugin__DefaultSource\kafkactl-azure-plugin.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\kafkactl-azure-plugin.exe returned exit code: 1
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Packages\deviceinsight.kafkactl-azure-plugin__DefaultSource\kafkactl-azure-plugin.exe returned exit code: 1
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\kafkactl-azure-plugin.exe returned exit code: 1

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-03-18 09:34:10.515 [FAIL] Installer failed security check. Url: https://github.com/deviceinsight/kafkactl-plugins/releases/download/v1.0.4/kafkactl-azure-plugin_1.0.4_windows_amd64.zip Result: 0x80004005

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Hi @d-rk,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-03-18 12:04:24.525 [FAIL] Installer failed security check. Url: https://github.com/deviceinsight/kafkactl-plugins/releases/download/v1.0.4/kafkactl-azure-plugin_1.0.4_windows_amd64.zip Result: 0x80004005

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Hi @d-rk,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Verify: 
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
