### PR TITLE
New version: DelineaInc.ThycoticLocalSecurityAgent version 11.4.3235

### PR DESCRIPTION
**Pull request by jnichols35**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140538)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-22T16:18:55.5259827Z ##[error] One or more errors occurred. (SQL error or missing database (0x87AF0001)) SQL error or missing database (0x87AF0001)

(Automated response - build 795.)

**Comment by stephengillie** [comment]
Hi @jnichols35,

This installer claims to have successfully installed the software package, but there appear to be no changes to the file system. Is this expected? Or is a dependency missing?

**Comment by jnichols35** [comment]
@stephengillie That's odd, normally I think it deploys a powershell file or something like that, previous versions I created PR's for this pkg had `Add Validation-No-Executables` added to them. Not sure if that helps.

**Comment by stephengillie** [comment]
I had to review the installer log file to find them. Somehow, they didn't get added to the file system until 2 seconds after WinGet exited. 
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
