### PR TITLE
Add E-Viewer 2011.11.1

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

To install this application, you need to manually trust the personal signature of this developer. Please install the .cer file here.
https://github.com/OpportunityLiu/E-Viewer/releases/tag/v2020.11.1

### CODE REVIEW

**Comment by g-aghayev** [comment]
You need to indicate in the document a warning that multiple architectures are not supported。

**Comment by KevinLaMS** [comment]
image

**Comment by g-aghayev** [comment]
Please see my reminder in #1
>To install this application, you need to manually trust the personal signature of this developer. Please install the .cer file here.
https://github.com/OpportunityLiu/E-Viewer/releases/tag/v2020.11.1

If there is a simpler method that does not require the user to manually operate to trust a certain certificate, please let me know.

**Pull request closed without merging**
