### PR TITLE
New Version: Youdao.youdaodict 8.10.0.0

### PR DESCRIPTION
**Pull request by lychichem**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/27920)

### CODE REVIEW

**Comment by palenshus** [comment]
I can't find that download link. At https://www.youdao.com/ I see this link http://c.youdao.com/dict/download.html?app=dict&vendor=webdict_default&platform=win&url=http%3A%2F%2Fcodown.youdao.com%2Fcidian%2FYoudaoDict_webdict_default.exe, where did you find the one in the manifest (http://download.ydstatic.cn/cidian/static/8.10/20210915/YoudaoDictSetup.exe) ?

**Comment by lychichem** [comment]
> I can't find that download link. At https://www.youdao.com/ I see this link http://c.youdao.com/dict/download.html?app=dict&vendor=webdict_default&platform=win&url=http%3A%2F%2Fcodown.youdao.com%2Fcidian%2FYoudaoDict_webdict_default.exe, where did you find the one in the manifest (http://download.ydstatic.cn/cidian/static/8.10/20210915/YoudaoDictSetup.exe) ?

Go to http://cidian.youdao.com and click download, then copy the link from downloading file. You can see the link has a pattern`https://download.ydstatic.cn/cidian/static/<first two parts of version number>/<update time>/YoudaoDictSetup.exe`

**Comment by palenshus** [comment]
I see that now, thanks!

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
