### PR TITLE
New version: Microsoft.NuGet version 6.10.0

### PR DESCRIPTION
**Pull request by damn-good-b0t**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/155176)

### CODE REVIEW

**Comment by a-mnich** [comment]
The previous manifests all had an AppsAndFeaturesEntries section, but portable applications (which this installer is) don't even create those entries.  (Correct?)
So wouldn't it make sense to remove the section from the manifests of this package?

**Comment by stephengillie** [comment]
Hi @damn-good-b0t,

This manifest removes Apps and Features entries that are present in previous PR versions. These entries should be added to this version, to maintain version matching, and prevent the 'upgrade always available' situation with this package.

(Automated response - build 881.)

**Comment by a-mnich** [comment]
> Looking at the [previous manifest](https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/NuGet/6.9.1/Microsoft.NuGet.installer.yaml), it has a `DisplayVersion`. This is an important one, as it may impact other manifests from being added, and I think might cause the "upgrade always available" situation. It's supposed to block here, but isn't for some reason.

@stephengillie I've adapted the manifest accordingly to match the DisplayVersion with the FileVersion as in the previous manifest.   

I got a bit confused here as I that that a portable installer doesn't need the `AppsAndFeaturesEntries` section as it doesn't write an ARP entry. I guess the manifest schema naming is a bit misleading in this case.

**Comment by stephengillie** [comment]
It looks good to me. 

I'm not sure, but I believe the package manager might write an ARP entry.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
