### PR TITLE
New package: NVIDIACorporation.NVIDIAapp version 1.0.14.0

### PR DESCRIPTION
**Pull request by blubbcode**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/198796)

### CODE REVIEW

**Comment by blubbcode** [comment]
new Nvidia app

**Comment by stephengillie** [comment]
Manual Validation ended with:
image

**Comment by denelon** [comment]
Supporting custom hardware in validation is "Not Planned".
* https://github.com/microsoft/winget-pkgs/issues/199504

**Comment by DandelionSprout** [comment]
I've been able to add it to the 3rd-party Winget source [winget-extras](https://github.com/pl4nty/winget-extras) by [pl4nty](https://github.com/pl4nty) now, at least:

`winget source add --name winget-extras --type Microsoft.PreIndexed.Package --arg https://winget.tplant.com.au/cache; winget install NVIDIA.NvidiaApp`

**Pull request closed without merging**
