### PR TITLE
New version: Google.Chrome version 94.0.4606.61

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/28530)

### CODE REVIEW

**Comment by jedieaston** [comment]
I'm having trouble pulling down this one in US Central. You might have to close and reopen a few times.

**Comment by OfficialEsco** [comment]
Pretty sure the bot have cached the previous installer so this will probably take a day to update...

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
