### PR TITLE
srjuddington.slade version 3.1.12

### PR DESCRIPTION
**Pull request by DawnVespero**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14311)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
This fails because of VC++2015 dependency
image

**Comment by ifreak490** [comment]
Too bad, that dependency wasn't mentioned anywhere. It had worked fine for me, but I guess only because I already had VC++ installed. Since [#163](https://github.com/microsoft/winget-cli/issues/163) is still open, I'm guessing there isn't any implementation for adding dependencies to manifests? If so, I guess this will just have to be abandoned until that issue is resolved.

**Comment by OfficialEsco** [comment]
Yea thats why we test in VM/Sandbox ^^
You can add it like this https://github.com/microsoft/winget-pkgs/pull/11468/files so its ready for when it works

**Comment by ifreak490** [comment]
> You can add it like this https://github.com/microsoft/winget-pkgs/pull/11468/files so its ready for when it works
Thank you for the suggestion! I've added it to my manifest now, so I'll try to resubmit it as soon as dependencies have been implemented.

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
