### PR TITLE
New version: HiteVision.HitePai6 version V6.2.312 (V6.2.312.20240618)

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#6827](https://github.com/SpecterShell/Dumplings/actions/runs/10075465988).

<details>

<summary>Log</summary>

````
Updated: 6.2.312.20231212 → V6.2.312.20240618
No ReleaseNotes (zh-CN) for version V6.2.312.20240618
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164366)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2145844845
> 2024-07-24 04:35:52.246 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFFA123C11F: (caller: 00007FFFA0FC8D6F) LogHr(1) tid(1f68) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFFA1142B08: (caller: 00007FFFA11EBC20) Exception(1) tid(1f68) 8A15005E ] 
> 2024-07-24 04:36:01.802 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFF89D8C11F: (caller: 00007FFF89B18D6F) LogHr(1) tid(155c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFF89C92B08: (caller: 00007FFF89D3BC20) Exception(1) tid(155c) 8A15005E ] 
> 2024-07-24 04:37:05.223 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-07-24 04:37:05.224 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFF89AFA465: (caller: 00007FFF89AFAD01) Exception(2) tid(155c) 80190193 Forbidden (403).
> 2024-07-24 04:37:31.140 [CORE] Download request failed. Returned status: 403
> 2024-07-24 04:37:31.141 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFF89AF43D6: (caller: 00007FFF89AF5C49) Exception(3) tid(155c) 80190193 Forbidden (403).
> 2024-07-24 04:37:31.142 [CLI ] Failed to download, waiting a bit and retry. Url: https://appmarket.hitecloud.cn/appMarket/package/2024-07-24/6d8d9ed488aa4d228befe8dbbc7b95c1/HitePai6.exe
> 2024-07-24 04:37:32.762 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-07-24 04:37:32.762 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFF89AFA465: (caller: 00007FFF89AFAD01) Exception(4) tid(155c) 80190193 Forbidden (403).
> 2024-07-24 04:37:33.044 [CORE] Download request failed. Returned status: 403
> 2024-07-24 04:37:33.044 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFF89AF43D6: (caller: 00007FFF89AF5C49) Exception(5) tid(155c) 80190193 Forbidden (403).
> MSI (s) (24:28) [04:36:10:346]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (24:28) [04:36:10:346]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (24:28) [04:36:10:346]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (24:28) [04:36:10:346]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (24:28) [04:36:10:346]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> Property(S): OutOfDiskSpace = 0
> Property(S): OutOfNoRbDiskSpace = 0
> Property(S): PrimaryVolumeSpaceAvailable = 0
> Property(S): PrimaryVolumeSpaceRequired = 0
> Property(S): PrimaryVolumeSpaceRemaining = 0
> MSI (s) (24:44) [04:36:11:221]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (24:44) [04:36:11:221]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (24:44) [04:36:11:221]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (24:44) [04:36:11:221]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (24:44) [04:36:11:221]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.

Automated error analysis suggests -2145844845 may mean Forbidden (403).

Automated error analysis suggests 80190193 may mean Forbidden (403)

(Automated response - build 886.)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Signature Update Failed.
> Installation failed with exit code -2145844845
> 2024-07-26 05:32:16.431 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFE68B2C11F: (caller: 00007FFE688B8D6F) LogHr(1) tid(157c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFE68A32B08: (caller: 00007FFE68ADBC20) Exception(1) tid(157c) 8A15005E ] 
> 2024-07-26 05:32:24.668 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFE6A7CC11F: (caller: 00007FFE6A558D6F) LogHr(1) tid(1cc0) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFE6A6D2B08: (caller: 00007FFE6A77BC20) Exception(1) tid(1cc0) 8A15005E ] 
> 2024-07-26 05:33:12.832 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-07-26 05:33:12.832 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFE6A53A465: (caller: 00007FFE6A53AD01) Exception(2) tid(1cc0) 80190193 Forbidden (403).
> 2024-07-26 05:33:52.168 [CORE] Download request failed. Returned status: 403
> 2024-07-26 05:33:52.170 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFE6A5343D6: (caller: 00007FFE6A535C49) Exception(3) tid(1cc0) 80190193 Forbidden (403).
> 2024-07-26 05:33:52.182 [CLI ] Failed to download, waiting a bit and retry. Url: https://appmarket.hitecloud.cn/appMarket/package/2024-07-24/6d8d9ed488aa4d228befe8dbbc7b95c1/HitePai6.exe
> 2024-07-26 05:33:53.731 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-07-26 05:33:53.731 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFE6A53A465: (caller: 00007FFE6A53AD01) Exception(4) tid(1cc0) 80190193 Forbidden (403).
> 2024-07-26 05:33:53.983 [CORE] Download request failed. Returned status: 403
> 2024-07-26 05:33:53.983 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFE6A5343D6: (caller: 00007FFE6A535C49) Exception(5) tid(1cc0) 80190193 Forbidden (403).
> MSI (s) (10:D4) [05:32:32:902]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (10:D4) [05:32:32:902]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (10:D4) [05:32:32:902]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (10:D4) [05:32:32:902]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (10:D4) [05:32:32:902]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> Property(S): OutOfDiskSpace = 0
> Property(S): OutOfNoRbDiskSpace = 0
> Property(S): PrimaryVolumeSpaceAvailable = 0
> Property(S): PrimaryVolumeSpaceRequired = 0
> Property(S): PrimaryVolumeSpaceRemaining = 0
> MSI (s) (10:70) [05:32:33:558]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (10:70) [05:32:33:558]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (10:70) [05:32:33:558]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (10:70) [05:32:33:558]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (10:70) [05:32:33:558]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.

Automated error analysis suggests -2145844845 may mean Forbidden (403).

Automated error analysis suggests 8A15005E may mean APPINSTALLER_CLI_ERROR_PINNED_CERTIFICATE_MISMATCH - The server certificate did not match any of the expected values.

Automated error analysis suggests 80190193 may mean Forbidden (403)

(Automated response - build 887.)

**Comment by stephengillie** [comment]
The URL works for me, so this might be blocking data centers by IP.

**Pull request closed without merging**
