### PR TITLE
Add Glimpse 0.2.0

### PR DESCRIPTION
**Pull request by robsonpiere**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----
Submission containing materials of a third party @glimpse-editor https://glimpse-editor.github.io/](https://glimpse-editor.github.io/)

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3368)

### CODE REVIEW

**Comment by hchorey** [comment]
Is it worth having separate manifests for the x86 and the x64 builds, as multiple installers are not currently supported in the 5/24/2020 Preview and this is the first builds of Glimpse that have a separate installer for 64-bit? (see here: https://glimpse-editor.github.io/downloads/ )

**Comment by hchorey** [comment]
@robsonpiere what do you think about renaming this .yaml to 0.2.0_x64.yaml, and having 0.2.0.yaml be the 32-bit payload?

Something like the attached:
[Glimpse_0.2.0_Manifests.zip](https://github.com/microsoft/winget-pkgs/files/5162965/Glimpse_0.2.0_Manifests.zip)

**Comment by robsonpiere** [comment]
Hello @hchorey 

I think it's cool to have both installation options.

And if we create two folders, like:

- manifests / Glimpse / Glimpse-x86 / 0.2.0.yaml
- manifests / Glimpse / Glimpse-x64 / 0.2.0.yaml

as there is no defined standard, I thought of following the example of Microsoft vc ++

**Comment by hchorey** [comment]
> @robsonpiere what do you think about renaming this .yaml to 0.2.0_x64.yaml, and having 0.2.0.yaml be the 32-bit payload?
> 
> Something like the attached:
> [Glimpse_0.2.0_Manifests.zip](https://github.com/microsoft/winget-pkgs/files/5162965/Glimpse_0.2.0_Manifests.zip)

I'm working on it, but ran into a few hitches here:  https://github.com/microsoft/winget-pkgs/pull/3396

**Comment by hchorey** [comment]
> Hello @hchorey
> 
> I think it's cool to have both installation options.
> 
> And if we create two folders, like:
> 
> * manifests / Glimpse / Glimpse-x86 / 0.2.0.yaml
> * manifests / Glimpse / Glimpse-x64 / 0.2.0.yaml
> 
> as there is no defined standard, I thought of following the example of Microsoft vc ++

I'm working on it, but ran into a few hitches here: https://github.com/microsoft/winget-pkgs/pull/3396

**Pull request merged**
