### PR TITLE
remove scrcpy+ menifest with older publisher name

### PR DESCRIPTION
**Pull request by milindgoel15**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

This PR aims to remove older publisher named manifest as publisher name got changed

### CODE REVIEW

**Comment by milindgoel15** [comment]
Needed to remove older published manifests with older publisher name.

**Comment by BrandonWanHuanSheng** [comment]
The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.

**Comment by milindgoel15** [comment]
> The pull request contains more than one manifest

Does targeting multiple versions of the same package mean 2 different manifests? It's same publisher in the end tho.

> Either singleton or multi file manifest under one version directory.

I am not sure i understood what to do.

**Comment by BrandonWanHuanSheng** [comment]
That means 2 different versions manifests.

**Comment by milindgoel15** [comment]
> That means 2 different versions manifests.

so what should I do if I want to remove both versions?

**Comment by BrandonWanHuanSheng** [comment]
Split into two pr

**Comment by milindgoel15** [comment]
Oh got it.

**Pull request closed without merging**
