### PR TITLE
[Zip][WiX] New package: Mobatek.MobaXterm version 23.0.0.5042

### LINKED ISSUE #27576: Mobatek.MobaXterm
# Package Requested

- [x] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [x] I have performed a search and couldn't find this package.
- [ ] I think there is a new version available and I have provided the URL.

---

## Please provide the following information if you can:

**Publisher**: Mobatek

**Publisher Url**: https://www.mobatek.net/

**Package Name**: MobaXterm Home Edition

**Package Url**:  https://mobaxterm.mobatek.net/

**Description**: Enhanced terminal for Windows with X11 server, tabbed SSH client, network tools and much more

**Package Version**: 21.3

**Installer URL**: https://download.mobatek.net/2132021082033134/MobaXterm_Installer_v21.3.zip

## For new versions:

**Current Package Identifier**: 21.3

### LINKED ISSUE #77910: [Package Request]: mobaxterm
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [ ] I have checked that the installer for this package is not contained in a .zip file
- [ ] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: 
Publisher Url: https://mobaxterm.mobatek.net/
Package Name: mobaxterm
Description: A ssh client
Package Version: 22.1
Installer URL: https://download.mobatek.net/2212022060563542/MobaXterm_Installer_v22.1.zip

Current Package Identifier (for new versions):

### PR DESCRIPTION
**Pull request by SpecterShell**
* Resolves #77910
* Resolves #27576

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/87332)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Comment by bet4it** [comment]
Could it be merged now?

**Comment by SpecterShell** [comment]
https://github.com/microsoft/winget-pkgs/issues/87300

**Comment by Macleykun** [comment]
Thank you for adding Mobaxterm :) looking forward to this being merged!

**Comment by Macleykun** [comment]
I believe this one fails b/c it detects malware, even tho this is untrue:
```
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs\manifests\m\Mobatek\MobaXterm\23.0.0.5042> winget install --manifest=. --ignore-local-archive-malware-scan
Found MobaXterm [Mobatek.MobaXterm] Version 23.0.0.5042
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Archive scan detected malware. Proceeding due to --ignore-local-archive-malware-scan
Extracting archive...
Successfully extracted archive
Starting package install...
Successfully installed
``` 
https://www.virustotal.com/gui/url/35dcaeaa3ac8ed72edfee834517468904bf11f01ed72644ce9d70b5c1f808c77

Install went well in my sandbox enviroment.

**Comment by Macleykun** [comment]
Also, this PR closes:
https://github.com/microsoft/winget-pkgs/issues/77910
https://github.com/microsoft/winget-pkgs/issues/27576

**Comment by SpecterShell** [comment]
> virustotal.com/gui/url/35dcaeaa3ac8ed72edfee834517468904bf11f01ed72644ce9d70b5c1f808c77

You need to manually upload the file to VirusTotal instead:
https://www.virustotal.com/gui/file/668550319b08dbc690290b13d129d337b3d82383b7def31afaecff4e793b5c1d

**Comment by Macleykun** [comment]
> > virustotal.com/gui/url/35dcaeaa3ac8ed72edfee834517468904bf11f01ed72644ce9d70b5c1f808c77
> 
> You need to manually upload the file to VirusTotal instead: https://www.virustotal.com/gui/file/668550319b08dbc690290b13d129d337b3d82383b7def31afaecff4e793b5c1d

I see, both luckily come out fully safe :)
I hope ya PR gets merged nevertheless!

**Comment by Trenly** [comment]
```
2023-02-09 05:01:53.888 [CLI ] Archive malware scan failed
2023-02-09 05:01:53.889 [CLI ] Terminating context: 0x8a150060 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\ArchiveFlow.cpp:29
```
Interesting, I thought this was disabled. I'm going to try it once more to be sure

**Review by ItzLevvie — APPROVED** [review]

**Comment by Macleykun** [comment]
Can this PR be merged now with the approvals?

**Comment by Trenly** [comment]
> Can this PR be merged now with the approvals?

Not until it has a successful pipelines run or is manually validated by Microsoft

**Comment by adripo** [comment]
I created an alternative package for this application here:
#97869 

Please consider fixing this PR or accepting my version. Thank you

**Comment by Trenly** [comment]
> I created and tested a working alternative package for this application here: #97869
> 
> Please consider fixing this PR or accepting my version. Thank you

The referenced PR has the same issue, and the manifest in this PR is both complete and accurate. This application cannot be added until the pipelines are updated or a manual review by Microsoft occurs.

**Comment by stephengillie** [comment]
> > I created and tested a working alternative package for this application here: #97869
> > Please consider fixing this PR or accepting my version. Thank you
> 
> The referenced PR has the same issue, and the manifest in this PR is both complete and accurate. This application cannot be added until the pipelines are updated or a manual review by Microsoft occurs.

Sorry to miss this for so long. Feel free to @ me for a manual review in the future.

**Pull request merged**
