### PR TITLE
New package: ddev.ddev version 1.22

### PR DESCRIPTION
**Pull request by tyler36**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114945&drop=dogfoodAlpha

### CODE REVIEW

**Comment by ItzLevvie** [comment]
[Policy] Needs-Author-Feedback

**Comment by stephengillie** [comment]
Hi @tyler36,

This PR is ready to merge, if you'll accept the CLA.

**Comment by tyler36** [comment]
@microsoft-github-policy-service agree company="DDEV"

**Comment by stephengillie** [comment]
Running this in a VM, the installer failed. This might be due to needing to accept the new root certificate:
image
image

I'm not sure why it passed Automated Validation but failed here. Sorry @tyler36, I wasn't expecting a certificate.

**Comment by tyler36** [comment]
@stephengillie Thanks for the feedback.

Does this prevent the package from being accepted? What needs to be done?

**Comment by stephengillie** [comment]
> @stephengillie Thanks for the feedback.
> 
> Does this prevent the package from being accepted? What needs to be done?

Hi @tyler36,

Apparently we just had to wait a day. With no changes, it works today - the installer completed without error, and the CLI application provides a response before exiting:
```
PS C:\Users\User\Desktop>  &"C:\Program Files\DDEV\sudo.exe"
Error: Already running as the specified user/permission-level (and no command specified). Exiting...
```

**Review by stephengillie — APPROVED** [review]

**Comment by tyler36** [comment]
@stephengillie 

Thank you for the update. It wasn't clear to me if there was something actionable or there was additional steps in the pipeline.
I appreciate your follow-up.

**Comment by adamgross42** [comment]
Hi @tyler36, are there plans to continue pushing updated DDEV versions to winget?  This configuration is not aligned with what the DDEV installers get from choco, e.g. https://github.com/ddev/ddev/blob/master/scripts/install_ddev_wsl2_docker_inside.ps1#L40

Also, this is missing the patch version number, which may be causing an issue: winget is giving me the following and stating my version is outdated, despite the installer URL here being set to "v1.22.0" (which is what I have installed).

Version: v1.22.0
Available: 1.22
(winget tries to do an update, and fails)

**Comment by tyler36** [comment]
Hi @adamgross42.

I attempted to add it to the build process but was unsuccessful. 

There wasn't much interest in supporting _another_ install process so I think it might be best to remove it before it gets painfully out of sync. I'm not sure how I can get the package de-listed though.

**Comment by adamgross42** [comment]
Thanks for the quick reply, that makes sense.

Hopefully it is close to a simple revert of the commit in this PR...

**Comment by stephengillie** [comment]
> Thanks for the quick reply, that makes sense.
> 
> Hopefully it is close to a simple revert of the commit in this PR...

Hi @adamgross42,

Please submit another PR with the manifest deleted. That will remove it from WinGet.

**Pull request merged**
