### PR TITLE
New version: SomePythonThings.WingetUIStore version 2.0.1

### PR DESCRIPTION
**Pull request by marticliment**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/110026&drop=dogfoodAlpha

### CODE REVIEW

**Comment by marticliment** [comment]
The installer should be now returning 0 as the output code

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code 1 

image

**Comment by marticliment** [comment]
But this is stock inno setup, I don't get why the validator fails.

Is there any way to get details about the environment where the installer fails?

**Comment by stephengillie** [comment]
I was able to replicate the issue in a Windows 11 VM. Here is the installer log: [WinGet-SomePythonThings.WingetUIStore.2.0.1-2023-06-19-10-40-26.250.log](https://github.com/microsoft/winget-pkgs/files/11790883/WinGet-SomePythonThings.WingetUIStore.2.0.1-2023-06-19-10-40-26.250.log)

And it appears to have installed: 
image

So I'm also unsure of why a code of 1 was returned. Maybe it's from the `VC Redist check` value of `1`?

**Comment by stephengillie** [comment]
> Hello,
> 
> Calling the installer with the same conditions the log you sent me shows, it still returns zero-state output codes. I passed the same arguments and ran it as administrator, as your log says you did. image Furthermore, i have analyzed the log generated by my WingetUI Instance and the one provided by you, and they look the same (only small differences regarding date/time).

Hi @martinclement,

Apologies for being unclear - I couldn't determine why WinGet was returning 1 after WingetUIStore installed successfully. Rethinking this, I believe it's a good cause for a waiver.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
