### PR TITLE
Discord.Discord.x64 version 1.0.9031

### LINKED ISSUE #137934: [Update Request]: Splitting Discord.Discord into two packages for each architecture
### What type of update are you requesting?

A new locale, architecture, or installer type of an existing version

### Current Package Identifier

Discord.Discord

### Package Version

1.0.9030

### Please describe the changes you would like to see

Would it be possible to split Discord into two packages: `Discord.Discord.x86` & `Discord.Discord.x64`

The current system keeps showing me updates for x86 Discord when i have x64 Discord installed.

### PR DESCRIPTION
**Pull request by drshtmstry**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

- Resolves #137934

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/139072)

### CODE REVIEW

**Comment by Trenly** [comment]
As I mentioned in the issue, Discord does not have a way to identify which architecture is installed, and this may cause more issues. 

I don't believe splitting the packages will help, and it may cause more issues than it solves

**Comment by stephengillie** [comment]
Review file blocks this package: 

> Self-updates and does not update the version number in the registry when doing so - applying an update via winget will break/override the user preferences and forcefully enable auto-start on system boot.

- #90642

**Comment by drshtmstry** [comment]
> As I mentioned in the issue, Discord does not have a way to identify which architecture is installed, and this may cause more issues.
> 
> I don't believe splitting the packages will help, and it may cause more issues than it solves

If you are right then when x64 is installed, it should update to x86 newer version automatically.
I tested this by installing x64 from manifest and it did not upgrade.
Previously it only showed winget upgrade because both architecture were using same ID & x86 had higher version number.

Screenshot 2024-02-15 085334
Screenshot (19)
Screenshot 2024-02-15 085818

**Comment by Trenly** [comment]
> If you are right then when x64 is installed, it should update to x86 newer version automatically. I tested this by installing x64 from manifest and it did not upgrade. Previously it only showed winget upgrade because both architecture were using same ID & x86 had higher version number.

Thats not quite what I meant. Discord itself is not going to detect updates incorrectly - internally it knows which architecture it is running.

The issue is that winget will have no way to know which version a user has installed. If you look at the information Discord writes to the registry, the DisplayName, Publisher, and ProductCode are exactly the same between the x86 and x64 versions. This is why they can be in the same manifest without requiring `AppsAndFeaturesEntries`. If the two manifests are split, winget may not be able to determine which package is actually installed since both `Discord.Discord.x86` and `Discord.Discord.x64` will be a strong match to the data in the registry.

**Comment by xAphex** [comment]
> > If you are right then when x64 is installed, it should update to x86 newer version automatically. I tested this by installing x64 from manifest and it did not upgrade. Previously it only showed winget upgrade because both architecture were using same ID & x86 had higher version number.
> 
> Thats not quite what I meant. Discord itself is not going to detect updates incorrectly - internally it knows which architecture it is running.
> 
> The issue is that winget will have no way to know which version a user has installed. If you look at the information Discord writes to the registry, the DisplayName, Publisher, and ProductCode are exactly the same between the x86 and x64 versions. This is why they can be in the same manifest without requiring `AppsAndFeaturesEntries`. If the two manifests are split, winget may not be able to determine which package is actually installed since both `Discord.Discord.x86` and `Discord.Discord.x64` will be a strong match to the data in the registry.

How about deprecating x86 version all together?

**Pull request closed without merging**
