### PR TITLE
Remove: Google.AndroidStudio 2024.1.2.12 for 2024.1.2.13

### PR DESCRIPTION
**Pull request by aisgbnok**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

Removing for:
- #174517

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/174516)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://redirector.gvt1.com/edgedl/android/studio/install/2024.1.2.12/android-studio-2024.1.2.12-windows.exe 
OK

(Automated message - build 923)

**Comment by stephengillie** [comment]
Hi @aisgbnok,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 896.)

**Comment by aisgbnok** [comment]
@stephengillie, unfortunately this is how `Google.AndroidStudio` get's updated in winget-pkgs repo. Google uses `MAJOR.MINOR` DisplayVersion so the previous version needs to be removed from the index to free up the DisplayVersion so patches like #174517 can then go through.

**Comment by aisgbnok** [comment]
- Please approve this PR (#174516), then #174517 will pass validation and can be approved. Thank you.

**Comment by stephengillie** [comment]
Sorry to miss these messages for so long. I'm not sure why they didn't show up in GitHub notifications.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
