### PR TITLE
New version: Microsoft.AzureCLI version 2.60.0

### PR DESCRIPTION
**Pull request by PckgrBot**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/151737)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by bebound** [comment]
@stephengillie 
I'm the maintainer of azure-cli, we use [azclibot](https://github.com/azclibot) to create a PR when new version is released.

I found that [PckgrBot](https://github.com/PckgrBot) and [Exorcism0666](https://github.com/Exorcism0666) also create PR automatically. [wingetbot](https://github.com/wingetbot) also create automatic update PR.
I wonder who is the maintainer of these bots and are they reliable? Thank you.

Ref:
https://github.com/microsoft/winget-pkgs/pull/151599
https://github.com/microsoft/winget-pkgs/pull/147430

**Comment by stephengillie** [comment]
Hi @bebound,

These are all regular uploaders and heavy users of automation. The first works with a kind of Intune integration, the second is independent, and the third is run by a member of the internal team. 

- Do you have specific concerns or issues about individual PRs or in general? 
- Would you like to modify upload permissions to change these behaviors?

**Comment by bebound** [comment]
Thanks for your reply.
I'm wondering if there's a reliable service we can rely on, so we don't have to maintain azclibot.

**Comment by stephengillie** [comment]
What metrics do you use to determine if a service is reliable?

**Pull request merged**
