### PR TITLE
New version: Swift.Toolchain version 5.7.1

### PR DESCRIPTION
**Pull request by riina**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/90165)

### CODE REVIEW

**Comment by v69ar73aqvc** [comment]
@microsoft-github-policy-service agree

**Comment by mdanish-kh** [comment]
image

Looks as if the publisher forgot to update the `DisplayVersion` ARP Entry. It should be `5.7.1` instead of `5.7.0`

**Comment by mdanish-kh** [comment]
@msftbot Area-External
@msftbot Blocking-Issue

**Comment by mdanish-kh** [comment]
Close with reason: Replaced by #92644;

**Pull request closed without merging**
