### PR TITLE
New version: Aserto.DSLoad version 0.30.6

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150888)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by gertd** [comment]
Please reject this bot is not associated with the author or the company the author represents!

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Aserto.DSLoad__DefaultSource\ds-load-auth0.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Aserto.DSLoad__DefaultSource\ds-load-azuread.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Aserto.DSLoad__DefaultSource\ds-load-cognito.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Aserto.DSLoad__DefaultSource\ds-load-google.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Aserto.DSLoad__DefaultSource\ds-load-ldap.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Aserto.DSLoad__DefaultSource\ds-load-okta.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Aserto.DSLoad__DefaultSource\ds-load.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\ds-load-auth0.exe returned exit code: 1

(Automated response - build 877.)

**Comment by stephengillie** [comment]
> Please reject this bot is not associated with the author or the company the author represents!

**Pull request closed without merging**
