### PR TITLE
New version: GitExtensionsTeam.GitExtensions version 5.0

### PR DESCRIPTION
**Pull request by namtab00**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/179184)

### CODE REVIEW

**Comment by namtab00** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
URL: https://github.com/gitextensions/gitextensions/releases/download/v5.0/GitExtensions-x64-5.0.0.17897-2a3b78b86.msi 
Status Code: 200

(Automated message - build 896)

**Comment by namtab00** [comment]
@stephengillie the validation fails due to an invalid URL to the privacy policy, which I haven't found in the sources.

I've created https://github.com/gitextensions/gitextensions/issues/11966 to track it for the maintainers (I am not one...).

**Comment by namtab00** [comment]
...the pipeline remains in "cancelled", will closr PR and retry from scratch

**Comment by namtab00** [comment]
new PR is #179204

**Pull request closed without merging**
