### PR TITLE
Update YogaDNS to 1.41

### PR DESCRIPTION
**Pull request by agkini**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/118142)

### CODE REVIEW

**Comment by agkini** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

Hi @agkini,

Is there an installer switch to automatically install this driver?

**Comment by agkini** [comment]
> 

Hi Stephen, I will look into this. Thanks for the screenshot. I didn't see this prompt locally in Windows Sandbox. Let me check if there is a flag.

I don't own this software, so will take some trials from myside.

**Comment by stephengillie** [comment]
> > 
> 
> Hi Stephen, I will look into this. Thanks for the screenshot. I didn't see this prompt locally in Windows Sandbox. Let me check if there is a flag.
> 
> I don't own this software, so will take some trials from myside.

Take your time. 

The screenshot is included in an artifact ZIP folder for the individual PR run. I wrote a PowerShell function to gather this ZIP, extract error data from logs, and open photos. It's in the [Manual Validation Pipeline](https://github.com/microsoft/winget-pkgs/blob/master/Tools/ManualValidationPipeline.ps1) script file as function `Get-AutoValLogs` on line 992.

**Pull request closed without merging**
