### PR TITLE
New package: AdoptOpenJDK.OpenJDK.17.OpenJ9 version 17.0.0.18

### PR DESCRIPTION
**Pull request by SpecterShell**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164816)

### CODE REVIEW

**Comment by stephengillie** [comment]
> Possible duplicate package entry.
> 
> Similar installer SHA256 hash found in manifest:
> 
> * `InstallerSha256: 5d50f769b5969d629e95d1cd91a09114db28a56f0487b94f81bf1d87a678e3bc`
>   
>   * manifests\a\AdoptOpenJDK\OpenJDK\17\17.0.0.18

Hi @SpecterShell,

Is this package already in the repo?

**Comment by SpecterShell** [comment]
> > Possible duplicate package entry.
> > Similar installer SHA256 hash found in manifest:
> > 
> > * `InstallerSha256: 5d50f769b5969d629e95d1cd91a09114db28a56f0487b94f81bf1d87a678e3bc`
> >   
> >   * manifests\a\AdoptOpenJDK\OpenJDK\17\17.0.0.18
> 
> Hi @SpecterShell,
> 
> Is this package already in the repo?

The manifests should have been removed in https://github.com/microsoft/winget-pkgs/pull/164822

**Comment by stephengillie** [comment]
> The manifests should have been removed in #164822

- https://github.com/microsoft/winget-pkgs/pull/164822

This seems to be another version.

**Comment by SpecterShell** [comment]
> > The manifests should have been removed in #164822
> 
>     * [New version: AdoptOpenJDK.OpenJDK.17 version 17.0.0.20 #164822](https://github.com/microsoft/winget-pkgs/pull/164822)
> 
> 
> This seems to be another version.

The `AdoptOpenJDK.OpenJDK.17` package previously uses the OpenJ9 edition, which has been replaced by the Hotspot one in that PR. This PR moves the OpenJ9 one to another package, although for some reasons the OpenJ9 edition is 2 version behind the Hotspot one.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Pull request merged**
