### PR TITLE
Add Czech language to Mozilla.Firefox manifest

### PR DESCRIPTION
**Pull request by krystofkrticka**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/127335)

### CODE REVIEW

**Comment by lunacd** [comment]
@krystofkrticka I'm currently generating Firefox manifests automatically. I'll add the Czech metadata that you added here to the next firefox release, which is scheduled on 19 Dec.

**Comment by krystofkrticka** [comment]
@lunacd OK, hopefully you'll have better luck with validation then I had.

**Comment by lunacd** [comment]
Because my script already passes validation for the past several versions, adding Czech metadata shouldn't break it. I'll ping you once next release arrives so that you could check the metadata. I don't want to accidentally mess up a language I don't speak lol

**Comment by lunacd** [comment]
@krystofkrticka Please check #129227 for the Czech locale. If that one works, please close this PR as completed

**Comment by krystofkrticka** [comment]
@lunacd thanks for adding Czech to Firefox manifest, from my point of view it looks just fine. BTW if you took the text from my PR I borrowed the description from Wikipedia 😆 because I was too lazy to create my own.

**Comment by lunacd** [comment]
I wouldn't know what to copy from Wikipedia even if I wanted to, lol.

**Pull request closed without merging**
