### PR TITLE
New version: GitExtensionsTeam.GitExtensions version 5.0

### PR DESCRIPTION
**Pull request by namtab00**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/179204)

### CODE REVIEW

**Comment by namtab00** [comment]
@stephengillie any chance you could look into why this stays stuck in pipeline play loop with installer validation failure?

**Comment by stephengillie** [comment]
> @stephengillie any chance you could look into why this stays stuck in pipeline play loop with installer validation failure?

This used to be common with any Git-based package, and still seems to afflict this one. I'll have to manually validate.

**Comment by namtab00** [comment]
@stephengillie are further retries necessary before you can manually validate? I noticed the wingetbot stopped running retries...

**Comment by stephengillie** [comment]
It's not a question of retries, but a question of my availability. I haven't had a chance to work on this (or any other) PR because I have had too many PRs to approve,

**Comment by namtab00** [comment]
@stephengillie thank you for your time, that's ok, I didn't mean to put any pressure.

I was asking because I'm not familiar with the timeline in such cases.

**Comment by stephengillie** [comment]
There are a couple of situations that can cause this label - some are ephemeral, so I usually let a PR retry a couple of times before manually trying it. 

- https://github.com/microsoft/winget-pkgs/discussions/155218

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 1:21:20 PM:  finished with exit code: -2147024846 1:21:34 PM: Install Failed. 1:21:34 PM: Detected 1 WinGet errors: 1:21:34 PM: 
> 2024-10-10 13:21:19.553 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp(60)\WindowsPackageManager.dll!00007FF8EC7C03A3: (caller: 00007FF8EC7C0495) Exception(1) tid(678) 80070032 The request is not supported. 

Automated error analysis suggests 8007003 may mean The request is not supported.

(Automated response - build 896.)

**Comment by namtab00** [comment]
@stephengillie any chance you could go through another manual installer validation?
the pipeline output contains no error hints I could look into...

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334972
> 2024-10-14 21:13:46.141 [CLI ] No suitable installer found for manifest Microsoft.DotNet.DesktopRuntime.8 with version 8.0.10

Automated error analysis suggests -1978334972 may mean This package has a dependency missing from your system.

(Automated response - build 896.)

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
