### PR TITLE
New Package: BeyondDimension.WattToolkit-2.8.6

### PR DESCRIPTION
**Pull request by CoolPlayLin**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/109426&drop=dogfoodAlpha

### CODE REVIEW

**Comment by CoolPlayLin** [comment]
@ItzLevvie It has scanned more than 1h...

**Comment by CoolPlayLin** [comment]
image
@stephengillie

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
This application is meant to extract to `C:\Program Files\Steam++` and create a shortcut on the desktop but it fails which is likely the reason why this PR has `Validation-No-Executables`

**Comment by stephengillie** [comment]
Unfortunately, the installer doesn't respond to common queries.

**Pull request closed without merging**
