### PR TITLE
n0-computer.sendme version 0.4.1

### PR DESCRIPTION
**Pull request by legowerewolf**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/148782)

### CODE REVIEW

**Comment by legowerewolf** [comment]
It's the AV again.

**Comment by stephengillie** [comment]
Hi @legowerewolf,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-04-11 13:49:10.841 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFFCC32C11F: (caller: 00007FFFCC0B8D6F) LogHr(1) tid(368) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFFCC232B08: (caller: 00007FFFCC2DBC20) Exception(1) tid(368) 8A15005E ] 
> 2024-04-11 13:49:10.841 [REPO] Failed to open available source: msstore
> 2024-04-11 13:49:18.516 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFFB578C11F: (caller: 00007FFFB5518D6F) LogHr(1) tid(14e4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFFB5692B08: (caller: 00007FFFB573BC20) Exception(1) tid(14e4) 8A15005E ] 
> 2024-04-11 13:49:18.516 [REPO] Failed to open available source: msstore
> 2024-04-11 13:49:33.657 [FAIL] Installer failed security check. Url: https://github.com/n0-computer/sendme/releases/download/v0.4.1/sendme-v0.4.1-windows-x86_64.zip Result: 0x80004005

(Automated response - build 876.)

**Comment by legowerewolf** [comment]
It's still the AV. Once I allow in in Defender, it installs and works fine.

**Comment by stephengillie** [comment]
Hi @legowerewolf,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-04-12 11:31:57.671 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF96E02C11F: (caller: 00007FF96DDB8D6F) LogHr(1) tid(1c1c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF96DF32B08: (caller: 00007FF96DFDBC20) Exception(1) tid(1c1c) 8A15005E ] 
> 2024-04-12 11:31:57.671 [REPO] Failed to open available source: msstore
> 2024-04-12 11:32:05.205 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF9569DC11F: (caller: 00007FF956768D6F) LogHr(1) tid(c88) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF9568E2B08: (caller: 00007FF95698BC20) Exception(1) tid(c88) 8A15005E ] 
> 2024-04-12 11:32:05.205 [REPO] Failed to open available source: msstore
> 2024-04-12 11:32:20.807 [FAIL] Installer failed security check. Url: https://github.com/n0-computer/sendme/releases/download/v0.4.1/sendme-v0.4.1-windows-x86_64.zip Result: 0x80004005

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Hi @legowerewolf,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-04-15 18:31:26.167 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFC8DB2C11F: (caller: 00007FFC8D8B8D6F) LogHr(1) tid(a5c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFC8DA32B08: (caller: 00007FFC8DADBC20) Exception(1) tid(a5c) 8A15005E ] 
> 2024-04-15 18:31:26.167 [REPO] Failed to open available source: msstore
> 2024-04-15 18:31:34.297 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFC7714C11F: (caller: 00007FFC76ED8D6F) LogHr(1) tid(1f6c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFC77052B08: (caller: 00007FFC770FBC20) Exception(1) tid(1f6c) 8A15005E ] 
> 2024-04-15 18:31:34.297 [REPO] Failed to open available source: msstore
> 2024-04-15 18:31:54.592 [FAIL] Installer failed security check. Url: https://github.com/n0-computer/sendme/releases/download/v0.4.1/sendme-v0.4.1-windows-x86_64.zip Result: 0x80004005

(Automated response - build 876.)

**Comment by legowerewolf** [comment]
So there's #149519 now... Should we bother with this?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-04-16 14:35:08.477 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF9380AC11F: (caller: 00007FF937E38D6F) LogHr(1) tid(8dc) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF937FB2B08: (caller: 00007FF93805BC20) Exception(1) tid(8dc) 8A15005E ] 
> 2024-04-16 14:35:08.477 [REPO] Failed to open available source: msstore
> 2024-04-16 14:35:16.643 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF91E10C11F: (caller: 00007FF91DE98D6F) LogHr(1) tid(1e8c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF91E012B08: (caller: 00007FF91E0BBC20) Exception(1) tid(1e8c) 8A15005E ] 
> 2024-04-16 14:35:16.643 [REPO] Failed to open available source: msstore
> 2024-04-16 14:35:31.538 [FAIL] Installer failed security check. Url: https://github.com/n0-computer/sendme/releases/download/v0.4.1/sendme-v0.4.1-windows-x86_64.zip Result: 0x80004005

(Automated response - build 877.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
