### PR TITLE
added nvm-windows to manifests

### PR DESCRIPTION
**Pull request by riazXrazor**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3823)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
Hey @riazXrazor 
The installer does not seem to be coming from the homepage location.  Is this really the correct installer?  I would have expected the URL to come from: https://github.com/coreybutler/nvm-windows/releases based on the homepage and license urls.

**Comment by riazXrazor** [comment]
> Hey @riazXrazor
> The installer does not seem to be coming from the homepage location. Is this really the correct installer? I would have expected the URL to come from: https://github.com/coreybutler/nvm-windows/releases based on the homepage and license urls.

yup as the official tool is opensource doesn't have a direct `.exe` url so i added it to my google drive and made it direct download.

**Comment by riazXrazor** [comment]
@KevinLaMS any update

**Pull request closed without merging**
