### PR TITLE
add .netframework 3.5 sp1

### PR DESCRIPTION
**Pull request by Reset816**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/545)

### CODE REVIEW

**Comment by Reset12138** [comment]
It seems that I meet a bug. When I first pull a request the bot didn't appear and Azure Pipelines didn't started, like this PR [https://github.com/microsoft/winget-pkgs/pull/544](url)
If I commit again and the bot work properly.
What cases it?

**Comment by Reset12138** [comment]
> It seems that I meet a bug. When I first pull a request the bot didn't appear and Azure Pipelines didn't started, like this PR [https://github.com/microsoft/winget-pkgs/pull/544](url)
> If I commit again and the bot work properly.
> What cases it?

WTF, if I click the link and 404 appear
image
but if I copy the link and go to it, it's fine 
image
do you have any idea about it? @superusercode

**Comment by superusercode** [comment]
@Reset12138 looks like your actual link (visible in markdown) has null in it but the visible text has the proper link 

if you copy and paste it like https://github.com/microsoft/winget-pkgs/pull/544 it should work properly

**Comment by Reset12138** [comment]
> @Reset12138 looks like your actual link (visible in markdown) has null in it but the visible text has the proper link
> 
> if you copy and paste it like #544 it should work properly

I got it. I'm a freshman in university and just started to learn CS so very grateful for your answer.
I've seen your comment in [PR](https://github.com/microsoft/winget-pkgs/pull/661), and I'll tried to fix it.

Besides do you have any idea about the bot's problem?

**Comment by msftrubengu** [comment]
@Reset12138 I'm still looking into it, but it appears that we either didn't get or dropped the GitHub's payload for #544 and #545 so the bot didn't process the PRs. Please file an issue describing what you've seen for us to follow up.

**Comment by Reset12138** [comment]
> @Reset12138 I'm still looking into it, but it appears that we either didn't get or dropped the GitHub's payload for #544 and #545 so the bot didn't process the PRs. Please file an issue describing what you've seen for us to follow up.

got it

**Comment by KevinLaMS** [comment]
I cannot get this one to install on Windows.  Claims it wants .Net 3.5 Framework installed first and pops the dialog.  I need to follow up with .net to see what should happen.

**Comment by KevinLaMS** [comment]
Approving this despite 3 issues.
1) it has a dependency, but it helps resolve.
2) it has a space in the version
3) there does not seem to be an uninstall.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
