### PR TITLE
New version: Nushell.Nushell version 0.80.0

### PR DESCRIPTION
**Pull request by fdncred**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/106977)

### CODE REVIEW

**Comment by fdncred** [comment]
@stephengillie can you please help again? each release, same story. not sure why it always fails.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335226 
> 2023-05-16 17:48:21.070 [CLI ] ShellExecute installer failed: 1603 
> CAQuietExec:  Error 0xc0000135: Command line returned an error. 
> CAQuietExec:  Error 0xc0000135: QuietExec Failed 
> CAQuietExec:  Error 0xc0000135: Failed in ExecCommon method CustomAction ReplacePathsInWindowsTerminalProfile returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox) Property(S): ErrorDialog = ErrorDlg 
> MSI (s) (74:6C) [17:48:20:955]: Product: nu -- Installation failed. 
> MSI (s) (74:6C) [17:48:20:955]: Windows Installer installed the product. Product Name: nu. Product Version: 0.80.0. Product Language: 1033. Manufacturer: The Nushell Project Developers. Installation success or error status: 1603.

**Comment by stephengillie** [comment]
This package installed normally on a Windows 11 VM: 
```
No environment config file found at C:\Users\User\AppData\Roaming\nushell\env.nu
Would you like to create one with defaults (Y/n):
y
Environment config file created at: C:\Users\User\AppData\Roaming\nushell\env.nu
No config file found at C:\Users\User\AppData\Roaming\nushell\config.nu
Would you like to create one with defaults (Y/n):
y
Config file created at: C:\Users\User\AppData\Roaming\nushell\config.nu
     __  ,
 .--()┬░'.' Welcome to Nushell,
'|, . ,'   based on the nu language,
 !_-(_\    where all data is structured!

Please join our Discord community at https://discord.gg/NtAbbGn
Our GitHub repository is at https://github.com/nushell/nushell
Our Documentation is located at https://nushell.sh
Tweet us at @nu_shell
Learn how to remove this at: https://nushell.sh/book/configuration.html#remove-welcome-message

It's been this long since Nushell's first commit:
4yrs 7days 40mins 44secs 119ms 793┬╡s 400ns

Startup Time: 10sec 505ms 653┬╡s 800ns

~/Desktop>                                                                                        05/17/2023 10:39:56 AM
```

**Comment by fdncred** [comment]
> This package installed normally on a Windows 11 VM:

Does that mean we can land this?

I see the ReplacePathsInWindowsTerminalProfile in our wix file. Maybe we'll remove it. Not sure what the deal is.

**Comment by stephengillie** [comment]
I'm concerned about the 1603 error above - that sometimes means that elevation is required but not requested, yet validation should be taking place in an elevated session.

**Review by stephengillie — APPROVED** [review]

**Comment by fdncred** [comment]
> I'm concerned about the 1603 error above - that sometimes means that elevation is required but not requested, yet validation should be taking place in an elevated session. Edit: I tested with a non-elevated session in the VM, but got no error. So I do not know the cause.

@stephengillie we're trying to figure out a solution so our winget-pkgs PRs quit failing. One of our contributors did some research into the 1603 error. Does the research sound reasonable to you that the winget-pkgs ci could be having permission issues? https://github.com/nushell/nushell/pull/5812#issuecomment-1555877586

I'm trying to figure out if we should just remove this Windows Terminal fragment json file or if we should try what they're suggesting. Any guidance here would be great.

**Comment by stephengillie** [comment]
> > I'm concerned about the 1603 error above - that sometimes means that elevation is required but not requested, yet validation should be taking place in an elevated session. Edit: I tested with a non-elevated session in the VM, but got no error. So I do not know the cause.
> 
> @stephengillie we're trying to figure out a solution so our winget-pkgs PRs quit failing. One of our contributors did some research into the 1603 error. Does the research sound reasonable to you that the winget-pkgs ci could be having permission issues? [nushell/nushell#5812 (comment)](https://github.com/nushell/nushell/pull/5812#issuecomment-1555877586)
> 
> I'm trying to figure out if we should just remove this Windows Terminal fragment json file or if we should try what they're suggesting. Any guidance here would be great.

This is very possible. We see numerous inexplicable 1603 errors. An issue could be made in the [WinGet-CLI](https://github.com/microsoft/winget-cli/issues) repo to identify and resolve any permissions issues.

**Pull request merged**
