### PR TITLE
Kiwix JS Windows v1.3.2.0

### PR DESCRIPTION
**Pull request by Jaifroid**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/16135)

### CODE REVIEW

**Comment by Jaifroid** [comment]
There is another submission that has been opened by @oxygen-dioxide, but it uses a permalink for the package that will create versioning issues. I have asked @oxygen-dioxide to close that PR in favour of this one. I am the developer of Kiwix JS Windows -- see the GitHub repo https://github.com/kiwix/kiwix-js-windows , and I can ensure that this Repo is updated as part of the build toolchain for Kiwix JS Windows. Thank you.

**Comment by Jaifroid** [comment]
The other submission PR has now been closed, so there is no obstacle to merging this PR: Thank you.

**Comment by Jaifroid** [comment]
Info for reviewer:

* The Kiwix JS Windows offficial repo is here: https://github.com/kiwix/kiwix-js-windows
* On that repo, you can easily see that I am the main dev: look at [commit history](https://github.com/kiwix/kiwix-js-windows/commits/master)
* This app has an entry in the Microsoft Store: https://www.microsoft.com/en-gb/store/p/kiwix-js/9p8slz4j979j
* The package is the same as that in the MS Store, but it has been digitally signed with the Kiwix org's certificate.

**Review by denelon — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Comment by denelon** [comment]
@Jaifroid the wingetcreate tool is an early preview. Many other fields might add value for your package like "Tags" and "Moniker".

**Pull request merged**
