### PR TITLE
New version: deviceinsight.kafkactl 5.0.6

### PR DESCRIPTION
**Pull request by d-rk**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/144295)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @d-rk,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-14 03:26:06.392 [FAIL] Installer failed security check. Url: https://github.com/deviceinsight/kafkactl/releases/download/v5.0.6/kafkactl_5.0.6_windows_386.zip Result: 0x80004005

(Automated response - build 870.)

**Comment by d-rk** [comment]
> Hi @d-rk,
> 
> The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.
> 
> (Automated response - build 870.)

Hey @stephengillie this is my first PR here so I'm unsure if I need to do something now. 
Can I get more details about the claimed security issue?
Will the rescan be triggered automatically tomorrow?

**Comment by stephengillie** [comment]
Howdy @d-rk,

My automation will retry this and every `Validation-Defender-Error` PR every 18 hours. I've heard that the Defender team sometimes installs a new package in a VM and monitors it for a duration, to verify no "time-release malware" technology is in play. So it's not unusual for a package to have a few rounds before passing.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
