### PR TITLE
New version: Mozilla.Firefox version 123.0.1

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings).
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/142659)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0.1/win64/ko/Firefox%20Setup%20123.0.1.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-371-142659-20240306-3\cc10b408-a1e5-4cb9-99fa-2dc63c92497e' because it is being used by another process..
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 
 3/6/2024 10:20:21 AM

(Automated response - build 861.)

**Comment by stephengillie** [comment]
URL: https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0.1/win32/en-US/Firefox%20Setup%20123.0.1.exe 
Status Code: 200

(Automated message - build 861)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0.1/win64-aarch64/et/Firefox%20Setup%20123.0.1.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-371-142659-20240307-1\b9bc0630-7d6d-450b-a09f-a6555a34537e' because it is being used by another process..
 Error information: 
 Http Response: OK
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0.1/win64/tr/Firefox%20Setup%20123.0.1.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-371-142659-20240307-1\d6f649cb-eb7b-45b0-abc6-d10f3f0c1060' because it is being used by another process..
 Error information: 
 Http Response: OK
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0.1/win32/sat/Firefox%20Setup%20123.0.1.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-371-142659-20240307-1\e385076a-6049-42e5-95ea-2aeb688ce189' because it is being used by another process..
 Error information: 
 Http Response: OK
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0.1/win32/ru/Firefox%20Setup%20123.0.1.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-371-142659-20240307-1\ee73bbc1-9596-43c0-ba59-802278b95a43' because it is being used by another process..
 Error information: 
 Http Response: OK
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 
 3/7/2024 11:25:22 AM
 

(Automated response - build 869.)

**Comment by stephengillie** [comment]
URL: https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0.1/win32/en-US/Firefox%20Setup%20123.0.1.exe 
Status Code: 200

(Automated message - build 869)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0.1/win64/is/Firefox%20Setup%20123.0.1.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-371-142659-20240312-1\6487efc3-4022-4afe-83be-b19e5f499e37' because it is being used by another process..
 Error information: 
 Http Response: OK
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0.1/win32/az/Firefox%20Setup%20123.0.1.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-371-142659-20240312-1\8ecff30b-7a47-471f-8901-f0317ab783c2' because it is being used by another process..
 Error information: 
 Http Response: OK
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0.1/win32/fr/Firefox%20Setup%20123.0.1.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-371-142659-20240312-1\965e681f-cc6e-40a6-b5fd-24b9a92bb1f4' because it is being used by another process..
 Error information: 
 Http Response: OK
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0.1/win64-aarch64/gu-IN/Firefox%20Setup%20123.0.1.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-371-142659-20240312-1\a36f0a5a-c023-4190-8a2a-7bd7407d3ba1' because it is being used by another process..
 Error information: 
 Http Response: OK
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0.1/win64-aarch64/bg/Firefox%20Setup%20123.0.1.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-371-142659-20240312-1\b3a884e6-23ee-4f3d-a5b9-7eb175315f61' because it is being used by another process..
 Error information: 
 Http Response: OK
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0.1/win64/bs/Firefox%20Setup%20123.0.1.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-371-142659-20240312-1\bbf79415-5a18-4440-ad61-aec580d6e6ff' because it is being used by another process..
 Error information: 
 Http Response: OK
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0.1/win32/ko/Firefox%20Setup%20123.0.1.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-371-142659-20240312-1\ccc0aa4b-c47e-4e7b-aadd-c4ad964219b1' because it is being used by another process..
 Error information: 
 Http Response: OK
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0.1/win64-aarch64/zh-TW/Firefox%20Setup%20123.0.1.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-371-142659-20240312-1\d5119444-64d8-49de-a04b-fb027b9c5fc2' because it is being used by another process..
 Error information: 
 Http Response: OK
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0.1/win32/cy/Firefox%20Setup%20123.0.1.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-371-142659-20240312-1\e4238ada-7ac1-42db-975d-730a50a307d7' because it is being used by another process..
 Error information: 
 Http Response: OK
 Error information: 
 Http Response: OK
 Http Reason Phrase: OK
 
 3/12/2024 8:32:22 AM
 

(Automated response - build 870.)

**Comment by stephengillie** [comment]
URL: https://download-installer.cdn.mozilla.net/pub/firefox/releases/123.0.1/win32/en-US/Firefox%20Setup%20123.0.1.exe 
Status Code: 200

(Automated message - build 870)

**Comment by SpecterShell** [comment]
I reckon this PR needs manual validation. "The process cannot access the file" error is likely to occur when there are too many installers. @stephengillie

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
