### PR TITLE
SyncMLViewer submission

### PR DESCRIPTION
**Pull request by okieselbach**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141001)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @okieselbach,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 813.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-26 06:52:58.072 [FAIL] Installer failed security check. Url: https://github.com/okieselbach/SyncMLViewer/raw/master/SyncMLViewer/dist/SyncMLViewer-v131.zip Result: 0x80004005 2024-02-26 06:52:58.072 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6

(Automated response - build 813.)

**Comment by okieselbach** [comment]
The source code is public here: https://github.com/okieselbach/SyncMLViewer
It might help in analyzing and for the final verdict. I think the tool does nothing really special. The tool basically uses ETW to trace SyncML messages and displays them. This is very helpful for better insights and troubleshooting. It is used by a lot of people in the community already. So I would love to see it on winget for easier access.

**Comment by stephengillie** [comment]
Hi @okieselbach,

It sounds like a cool tool. This would be good info for the Defender team to consider. I don't know how to contact them.

**Comment by okieselbach** [comment]
The submission on the defender portal gave me this:
The warning you experienced indicates that submitted file(s) did not have dedicated determination in our system. We can confirm that the files submitted are now determined as clean and attempting to download or run the application should no longer show any warnings.
Due to the complexity of our backend systems, it may take up to 12 hours for the determination to be fully reflected and for the SmartScreen warnings to stop.

**Comment by okieselbach** [comment]
Should it validate again in near future? Thx, Oli

**Comment by stephengillie** [comment]
Yes - usually the bot would have triggered a run within a minute. I believe we've located the issue, so hopefully the bot will have this PR retry soon.

**Comment by okieselbach** [comment]
It doesn't look like it will run 🤷‍♂️ or something happened in the background which I can't see here.

**Comment by okieselbach** [comment]
The bot goes on strike 😂✌️

**Comment by okieselbach** [comment]
An idea of why it is not re-validating the program. For me it looks like the validation is still the first one, it never ran again

**Comment by stephengillie** [comment]
Hi @okieselbach,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 856.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-01 09:31:14.208 [FAIL] Installer failed security check. Url: https://github.com/okieselbach/SyncMLViewer/raw/master/SyncMLViewer/dist/SyncMLViewer-v131.zip Result: 0x80004005

(Automated response - build 856.)

**Comment by okieselbach** [comment]
I don't know where the issue is here. I can download the source it is a zip archive and it is correctly flagged as a portable install in the yaml and the URL is accessible, the archive is downloadable and not broken (the zip archive itself). When I test the package locally everything runs smoothly. So where it the issue here exactly?

**Comment by stephengillie** [comment]
Hi @okieselbach,

My automation found the following line in the validation logs: `Installer failed security check`. 

- This message indicates that the installer failed a security check, which is a Defender scan or similar. 
- This might be a false positive and we can rescan tomorrow. My automation will automatically retry this PR in a little more than 18 hours - it runs at 20 minutes after every hour. 
- The package hasn't been fully installed and examined yet - it hasn't got that far in the pipeline. 

Does this help?

**Comment by okieselbach** [comment]
I submitted it to the defender portal and they told me this in the end:

The warning you experienced indicates that submitted file(s) did not have dedicated determination in our system. We can confirm that the files submitted are now determined as clean and attempting to download or run the application should no longer show any warnings.
Due to the complexity of our backend systems, it may take up to 12 hours for the determination to be fully reflected and for the SmartScreen warnings to stop.

So, I don't know what to do more. This was 4 days ago already.

**Comment by okieselbach** [comment]
Also, I submitted it to VirusTotal, no issue.... Defender portal gave me the message above. After the Defender message, I would assume the Defender is not reporting it as an issue, but this doesn't seem to be true. So, I'm unaware of how to proceed here. I can submit it again to the Defender portal, but when this doesn't help the first time, what should be different the second time? I can try...

**Comment by okieselbach** [comment]
I re-submitted it and it was flagged with everything fine. So even the Defender Portal says now green 🤷‍♂️

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
