### PR TITLE
New package: BancoBradesco.NavegadorExclusivo version 4.1.0

### PR DESCRIPTION
**Pull request by ghost**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/142126)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-03-04 14:29:06.178   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\browser\skin\classic\browser\aboutNetError.css
> 2024-03-04 14:29:06.194   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\browser\skin\classic\browser\aboutSocialError.css
> 2024-03-04 14:29:06.241   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\browser\skin\classic\browser\cert-error.svg
> 2024-03-04 14:29:06.272   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\browser\skin\classic\browser\error-pages.css
> 2024-03-04 14:29:06.850   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\browser\skin\classic\browser\update-badge-failed.svg
> 2024-03-04 14:29:06.913   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\browser\skin\classic\browser\addons\addon-install-error.svg
> 2024-03-04 14:29:08.350   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\devtools\modules\devtools\client\aboutdebugging\components\addons\install-error.js
> 2024-03-04 14:29:09.006   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\devtools\modules\devtools\client\memory\reducers\errors.js
> 2024-03-04 14:29:10.319   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\devtools\modules\devtools\client\webconsole\new-console-output\components\message-types\page-error.js
> 2024-03-04 14:29:10.507   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\devtools\modules\devtools\server\actors\errordocs.js
> 2024-03-04 14:29:11.944   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\devtools\skin\images\editor-error.png
> 2024-03-04 14:29:12.038   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\devtools\skin\images\search-clear-failed.svg
> 2024-03-04 14:29:12.600   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\en-US\locale\browser\netError.dtd
> 2024-03-04 14:29:14.944   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\langpack-en-US@scopus.com.br\browser\chrome\pt-BR\locale\browser\netError.dtd
> 2024-03-04 14:29:15.824   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\langpack-en-US@scopus.com.br\chrome\pt-BR\locale\pt-BR\global\layout_errors.properties
> 2024-03-04 14:29:15.835   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\langpack-en-US@scopus.com.br\chrome\pt-BR\locale\pt-BR\global\netError.dtd
> 2024-03-04 14:29:15.835   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\langpack-en-US@scopus.com.br\chrome\pt-BR\locale\pt-BR\global\netErrorApp.dtd
> 2024-03-04 14:29:16.319   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\langpack-en-US@scopus.com.br\chrome\pt-BR\locale\pt-BR\pipnss\nsserrors.properties
> 2024-03-04 14:29:16.366   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\langpack-en-US@scopus.com.br\chrome\pt-BR\locale\pt-BR\services\errors.properties
> 2024-03-04 14:29:16.538   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\langpack-es-ES@scopus.com.br\browser\chrome\es-ES\locale\browser\netError.dtd
> 2024-03-04 14:29:17.413   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\langpack-es-ES@scopus.com.br\chrome\es-ES\locale\es-ES\global\layout_errors.properties
> 2024-03-04 14:29:17.428   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\langpack-es-ES@scopus.com.br\chrome\es-ES\locale\es-ES\global\netError.dtd
> 2024-03-04 14:29:17.444   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\langpack-es-ES@scopus.com.br\chrome\es-ES\locale\es-ES\global\netErrorApp.dtd
> 2024-03-04 14:29:17.757   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\langpack-es-ES@scopus.com.br\chrome\es-ES\locale\es-ES\pipnss\nsserrors.properties
> 2024-03-04 14:29:17.788   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\langpack-es-ES@scopus.com.br\chrome\es-ES\locale\es-ES\services\errors.properties
> 2024-03-04 14:29:18.725   Dest filename: C:\Program Files (x86)\AppBrad\chrome\en-US\locale\en-US\global\layout_errors.properties
> 2024-03-04 14:29:18.725   Dest filename: C:\Program Files (x86)\AppBrad\chrome\en-US\locale\en-US\global\netError.dtd
> 2024-03-04 14:29:18.741   Dest filename: C:\Program Files (x86)\AppBrad\chrome\en-US\locale\en-US\global\netErrorApp.dtd
> 2024-03-04 14:29:19.100   Dest filename: C:\Program Files (x86)\AppBrad\chrome\en-US\locale\en-US\pipnss\nsserrors.properties
> 2024-03-04 14:29:19.116   Dest filename: C:\Program Files (x86)\AppBrad\chrome\en-US\locale\en-US\services\errors.properties
> 2024-03-04 14:29:19.194   Dest filename: C:\Program Files (x86)\AppBrad\chrome\marionette\content\error.js
> 2024-03-04 14:29:19.350   Dest filename: C:\Program Files (x86)\AppBrad\chrome\pippki\content\pippki\exceptionDialog.js
> 2024-03-04 14:29:19.350   Dest filename: C:\Program Files (x86)\AppBrad\chrome\pippki\content\pippki\exceptionDialog.xul
> 2024-03-04 14:29:19.850   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\content\global\netError.xhtml
> 2024-03-04 14:29:20.600   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\content\passwordmgr\passwordManagerExceptions.js
> 2024-03-04 14:29:20.600   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\content\passwordmgr\passwordManagerExceptions.xul
> 2024-03-04 14:29:20.913   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\skin\classic\global\netError.css
> 2024-03-04 14:29:21.225   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\skin\classic\global\icons\error-16-XP.png
> 2024-03-04 14:29:21.225   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\skin\classic\global\icons\error-16.png
> 2024-03-04 14:29:21.225   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\skin\classic\global\icons\error-64-XP.png
> 2024-03-04 14:29:21.241   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\skin\classic\global\icons\error-64.png
> 2024-03-04 14:29:21.241   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\skin\classic\global\icons\Error-XP.png
> 2024-03-04 14:29:21.241   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\skin\classic\global\icons\Error.png
> 2024-03-04 14:29:21.475   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\skin\classic\global\media\error.png
> 2024-03-04 14:29:21.897   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\skin\classic\mozapps\extensions\alerticon-error.svg

(Automated response - build 861.)

**Comment by Barradel** [comment]
> Automatic Validation ended with:
> 
> > 2024-03-04 14:29:06.178   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\browser\skin\classic\browser\aboutNetError.css
> > 2024-03-04 14:29:06.194   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\browser\skin\classic\browser\aboutSocialError.css
> > 2024-03-04 14:29:06.241   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\browser\skin\classic\browser\cert-error.svg
> > 2024-03-04 14:29:06.272   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\browser\skin\classic\browser\error-pages.css
> > 2024-03-04 14:29:06.850   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\browser\skin\classic\browser\update-badge-failed.svg
> > 2024-03-04 14:29:06.913   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\browser\skin\classic\browser\addons\addon-install-error.svg
> > 2024-03-04 14:29:08.350   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\devtools\modules\devtools\client\aboutdebugging\components\addons\install-error.js
> > 2024-03-04 14:29:09.006   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\devtools\modules\devtools\client\memory\reducers\errors.js
> > 2024-03-04 14:29:10.319   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\devtools\modules\devtools\client\webconsole\new-console-output\components\message-types\page-error.js
> > 2024-03-04 14:29:10.507   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\devtools\modules\devtools\server\actors\errordocs.js
> > 2024-03-04 14:29:11.944   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\devtools\skin\images\editor-error.png
> > 2024-03-04 14:29:12.038   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\devtools\skin\images\search-clear-failed.svg
> > 2024-03-04 14:29:12.600   Dest filename: C:\Program Files (x86)\AppBrad\browser\chrome\en-US\locale\browser\netError.dtd
> > 2024-03-04 14:29:14.944   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\[langpack-en-US@scopus.com.br](mailto:langpack-en-US@scopus.com.br)\browser\chrome\pt-BR\locale\browser\netError.dtd
> > 2024-03-04 14:29:15.824   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\[langpack-en-US@scopus.com.br](mailto:langpack-en-US@scopus.com.br)\chrome\pt-BR\locale\pt-BR\global\layout_errors.properties
> > 2024-03-04 14:29:15.835   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\[langpack-en-US@scopus.com.br](mailto:langpack-en-US@scopus.com.br)\chrome\pt-BR\locale\pt-BR\global\netError.dtd
> > 2024-03-04 14:29:15.835   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\[langpack-en-US@scopus.com.br](mailto:langpack-en-US@scopus.com.br)\chrome\pt-BR\locale\pt-BR\global\netErrorApp.dtd
> > 2024-03-04 14:29:16.319   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\[langpack-en-US@scopus.com.br](mailto:langpack-en-US@scopus.com.br)\chrome\pt-BR\locale\pt-BR\pipnss\nsserrors.properties
> > 2024-03-04 14:29:16.366   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\[langpack-en-US@scopus.com.br](mailto:langpack-en-US@scopus.com.br)\chrome\pt-BR\locale\pt-BR\services\errors.properties
> > 2024-03-04 14:29:16.538   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\[langpack-es-ES@scopus.com.br](mailto:langpack-es-ES@scopus.com.br)\browser\chrome\es-ES\locale\browser\netError.dtd
> > 2024-03-04 14:29:17.413   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\[langpack-es-ES@scopus.com.br](mailto:langpack-es-ES@scopus.com.br)\chrome\es-ES\locale\es-ES\global\layout_errors.properties
> > 2024-03-04 14:29:17.428   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\[langpack-es-ES@scopus.com.br](mailto:langpack-es-ES@scopus.com.br)\chrome\es-ES\locale\es-ES\global\netError.dtd
> > 2024-03-04 14:29:17.444   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\[langpack-es-ES@scopus.com.br](mailto:langpack-es-ES@scopus.com.br)\chrome\es-ES\locale\es-ES\global\netErrorApp.dtd
> > 2024-03-04 14:29:17.757   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\[langpack-es-ES@scopus.com.br](mailto:langpack-es-ES@scopus.com.br)\chrome\es-ES\locale\es-ES\pipnss\nsserrors.properties
> > 2024-03-04 14:29:17.788   Dest filename: C:\Program Files (x86)\AppBrad\browser\extensions\[langpack-es-ES@scopus.com.br](mailto:langpack-es-ES@scopus.com.br)\chrome\es-ES\locale\es-ES\services\errors.properties
> > 2024-03-04 14:29:18.725   Dest filename: C:\Program Files (x86)\AppBrad\chrome\en-US\locale\en-US\global\layout_errors.properties
> > 2024-03-04 14:29:18.725   Dest filename: C:\Program Files (x86)\AppBrad\chrome\en-US\locale\en-US\global\netError.dtd
> > 2024-03-04 14:29:18.741   Dest filename: C:\Program Files (x86)\AppBrad\chrome\en-US\locale\en-US\global\netErrorApp.dtd
> > 2024-03-04 14:29:19.100   Dest filename: C:\Program Files (x86)\AppBrad\chrome\en-US\locale\en-US\pipnss\nsserrors.properties
> > 2024-03-04 14:29:19.116   Dest filename: C:\Program Files (x86)\AppBrad\chrome\en-US\locale\en-US\services\errors.properties
> > 2024-03-04 14:29:19.194   Dest filename: C:\Program Files (x86)\AppBrad\chrome\marionette\content\error.js
> > 2024-03-04 14:29:19.350   Dest filename: C:\Program Files (x86)\AppBrad\chrome\pippki\content\pippki\exceptionDialog.js
> > 2024-03-04 14:29:19.350   Dest filename: C:\Program Files (x86)\AppBrad\chrome\pippki\content\pippki\exceptionDialog.xul
> > 2024-03-04 14:29:19.850   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\content\global\netError.xhtml
> > 2024-03-04 14:29:20.600   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\content\passwordmgr\passwordManagerExceptions.js
> > 2024-03-04 14:29:20.600   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\content\passwordmgr\passwordManagerExceptions.xul
> > 2024-03-04 14:29:20.913   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\skin\classic\global\netError.css
> > 2024-03-04 14:29:21.225   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\skin\classic\global\icons\error-16-XP.png
> > 2024-03-04 14:29:21.225   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\skin\classic\global\icons\error-16.png
> > 2024-03-04 14:29:21.225   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\skin\classic\global\icons\error-64-XP.png
> > 2024-03-04 14:29:21.241   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\skin\classic\global\icons\error-64.png
> > 2024-03-04 14:29:21.241   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\skin\classic\global\icons\Error-XP.png
> > 2024-03-04 14:29:21.241   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\skin\classic\global\icons\Error.png
> > 2024-03-04 14:29:21.475   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\skin\classic\global\media\error.png
> > 2024-03-04 14:29:21.897   Dest filename: C:\Program Files (x86)\AppBrad\chrome\toolkit\skin\classic\mozapps\extensions\alerticon-error.svg
> 
> (Automated response - build 861.)

Sorry, I did not understand if there is a problem.

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 865.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
image

Is there an installer switch to skip this message and complete the install silently?

**Pull request closed without merging**
