### PR TITLE
Remove version: TheDocumentFoundation.LibreOffice.SDK.LTS version 7.6.7.2

### PR DESCRIPTION
**Pull request by schembriaiden**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/162550)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://downloadarchive.documentfoundation.org/libreoffice/old/7.6.7.2/win/x86/LibreOffice_7.6.7.2_Win_x86_sdk.msi 
OK

(Automated message - build 911)

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/pull/162549#issuecomment-2223354742

**Comment by stephengillie** [comment]
URL: https://downloadarchive.documentfoundation.org/libreoffice/old/7.6.7.2/win/x86/LibreOffice_7.6.7.2_Win_x86_sdk.msi 
Status Code: 200

(Automated message - build 886)

**Comment by stephengillie** [comment]
Hi @vikingnope,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 886.)

**Comment by stephengillie** [comment]
URL: https://downloadarchive.documentfoundation.org/libreoffice/old/7.6.7.2/win/x86/LibreOffice_7.6.7.2_Win_x86_sdk.msi 
Status Code: 200

(Automated message - build 886)

**Comment by vikingnope** [comment]
Hiya @stephengillie,

I would think that since their normal subsequent versions were EOL'd both the SDK and the Help Pack would be EOL'd since they correspond to them

The SDK and Help Pack are usually released with their respective version.

I think this can be removed.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
