### PR TITLE
BlizzardEntertainement.Battle.net version 1.18.0.3086

### PR DESCRIPTION
**Pull request by bebewold**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/58217)

### CODE REVIEW

**Comment by Trenly** [comment]
Looks like a CDN issue. I get a different hash than the manifest and pipelines. Similar behavior in 
* #40512
* #53748
Also no silent install
* #28696
* #25070

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/58217#issuecomment-1103467134

**Comment by PAI5REECHO** [comment]
> Also no silent install
I don't think this is a problem

**Comment by Trenly** [comment]
> > Also no silent install
> 
> I don't think this is a problem

Applications which do not have a silent or unattended install mode currently cannot be added to the repository

**Comment by PAI5REECHO** [comment]
> Applications which do not have a silent or unattended install mode currently cannot be added to the repository

Where is this written? I've installed several different applications that required user input

**Comment by Trenly** [comment]
> Where is this written? I've installed several different applications that required user input

It is on the official Docs site with the error meanings - https://docs.microsoft.com/en-us/windows/package-manager/package/winget-validation#submission-expectations

> * The installer supports non-interactive modes.

**Comment by KaranKad** [comment]
> Where is this written? I've installed several different applications that required user input

User input means the one where your need to configure app settings during installation not UAC pop up.

**Pull request closed without merging**
