### PR TITLE
Modify: EastMoney.EastMoney version 11.5.1

### PR DESCRIPTION
**Pull request by DuckDuckStudio**
Update to Manifest 1.9.0
Add Architecture x64
Update Publisher in Location en-US
Add ReleaseDate

- close #197441

Successfully verify on a Windows11 x64 virtual machine:
image

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/197130)

### CODE REVIEW

**Comment by DuckDuckStudio** [comment]
I am not sure if this package complies with [policy requirements 1.8.1](https://learn.microsoft.com/en-us/windows/package-manager/package/windows-package-manager-policies#181).
If not, please @ me and I will remove all versions of this package.

> Under no circumstances can this package fail to meet the [policy requirement 2.9](https://learn.microsoft.com/en-us/windows/package-manager/package/windows-package-manager-policies#29-excessive-profanity-and-inappropriate-content).
> (但无论如何，此软件包都不会不符合[政策要求2.9](https://learn.microsoft.com/en-us/windows/package-manager/package/windows-package-manager-policies#29-excessive-profanity-and-inappropriate-content))

**Comment by DuckDuckStudio** [comment]
I just tested it in my virtual machine and I'm guessing it might have something to do with user-generated content or information?

**Comment by stephengillie** [comment]
I honestly do not know anything about the data source which drives the `Policy-Test` set of labels.

**Comment by stephengillie** [comment]
> The head ref may contain hidden characters: "\u4E1C\u65B9\u8D22\u5BCC"

Can these be removed?

**Comment by DuckDuckStudio** [comment]
- https://github.com/microsoft/winget-pkgs/pull/197173#issuecomment-2529750215

This means I need to create a new pull request to change the branch name...
Can we ignore this issue?

**Comment by DuckDuckStudio** [comment]
> [!TIP]
> I used the keyword "close" in both pull requests. When one pull request is merged, the other pull request should automatically close.

**Comment by stephengillie** [comment]
Thank you for the deep research. Sorry for the unfortunate conversion issue.

**Pull request closed without merging**
