### PR TITLE
New version: POQDavid.PotatoWall version 1.7

### PR DESCRIPTION
**Pull request by poqdavid**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/119111)

### CODE REVIEW

**Comment by poqdavid** [comment]
From what I am reading it says my program is a PUA but here https://www.virustotal.com/gui/url/de7f032bb5d12a64084e25be7db5bc5c10ed474101f35f7e74ba6a768d3b1668?nocache=1 its all clean what's going on with this?

**Comment by stephengillie** [comment]
Hi @poqdavid,

Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
Installer https://github.com/poqdavid/PotatoWall/releases/download/v1.7/PotatoWall_Release_SelfContained_v1.7_x64_en-us.msi
Scan request id: '82f6876b-14af-4768-a524-1ef5b6883814'
Error information: BlockingDetectionFound

Unfortunately, this package appears to be blocked from download by the host.

**Comment by poqdavid** [comment]
> Hi @poqdavid,
> 
> Automatic Validation ended with:
> 
> > Installer Verification Analysis Context Information:
> > Installer https://github.com/poqdavid/PotatoWall/releases/download/v1.7/PotatoWall_Release_SelfContained_v1.7_x64_en-us.msi
> > Scan request id: '82f6876b-14af-4768-a524-1ef5b6883814'
> > Error information: BlockingDetectionFound
> 
> Unfortunately, this package appears to be blocked from download by the host. It might be a data center block, to prevent automated downloads.

Wait so you are saying I can't use github to do this?? what do you suggest me to do?

**Comment by stephengillie** [comment]
> > Hi @poqdavid,
> > Automatic Validation ended with:
> > > Installer Verification Analysis Context Information:
> > > Installer https://github.com/poqdavid/PotatoWall/releases/download/v1.7/PotatoWall_Release_SelfContained_v1.7_x64_en-us.msi
> > > Scan request id: '82f6876b-14af-4768-a524-1ef5b6883814'
> > > Error information: BlockingDetectionFound
> > 
> > 
> > Unfortunately, this package appears to be blocked from download by the host. It might be a data center block, to prevent automated downloads.
> 
> Wait so you are saying I can't use github to do this?? what do you suggest me to do?

No - we have many packages that are hosted on GitHub. It appears that GitHub is preventing the VM in our Automated Validation pipeline from downloading the package to analyze it. 

I had assumed that this blocking was due to a setting that was enabled within GitHub. But based on your reaction, this might not be a setting in GitHub, but a technical bug with the hosting infrastructure. Could you contact GitHub support to ask about this blocking error?

**Comment by poqdavid** [comment]
> > > Hi @poqdavid,
> > > Automatic Validation ended with:
> > > > Installer Verification Analysis Context Information:
> > > > Installer https://github.com/poqdavid/PotatoWall/releases/download/v1.7/PotatoWall_Release_SelfContained_v1.7_x64_en-us.msi
> > > > Scan request id: '82f6876b-14af-4768-a524-1ef5b6883814'
> > > > Error information: BlockingDetectionFound
> > > 
> > > 
> > > Unfortunately, this package appears to be blocked from download by the host. It might be a data center block, to prevent automated downloads.
> > 
> > 
> > Wait so you are saying I can't use github to do this?? what do you suggest me to do?
> 
> No - we have many packages that are hosted on GitHub. It appears that GitHub is preventing the VM in our Automated Validation pipeline from downloading the package to analyze it.
> 
> I had assumed that this blocking was due to a setting that was enabled within GitHub, because packages on GitHub don't usually see this error. But based on your reaction, this might not be a setting in GitHub, but a technical bug with the hosting infrastructure. Could you contact GitHub support to ask about this blocking error?

Sure I will contact them and as soon as I get a reply I will let you know

**Comment by poqdavid** [comment]
So any progress or how I should solve this do I have to upload my builds some places else?

**Comment by Trenly** [comment]
Lets try one more time and see if the same thing happens

**Review by Trenly — APPROVED** [review]

**Pull request merged**
