### PR TITLE
Devolutions.RemoteDesktopManagerFree version 2021.1.34.0

### PR DESCRIPTION
**Pull request by krystofkrticka**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/16209)

### CODE REVIEW

**Comment by krystofkrticka** [comment]
Updated version of Remote Desktop Manager Free

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
Please use `wingetcreate update -i Devolutions.RemoteDesktopManagerFree -v 2021.1.34.0 -u https://cdn.devolutions.net/download/Setup.RemoteDesktopManagerFree.2021.1.34.0.msi` since the package already exsists.

**Comment by krystofkrticka** [comment]
OK I'll fix that immediately.

**Comment by krystofkrticka** [comment]
OK, fixed version of manifest from this PR is in new PR with number #16218

**Pull request closed without merging**
