### PR TITLE
Update manifest: clsid2.mpc-hc version 2.3.2

### LINKED ISSUE #161087: [Update Request]: wrong file link
### What type of update are you requesting?

A change to the package metadata

### Current Package Identifier

clsid2.mpc-hc

### Package Version

2.3.2

### Please describe the changes you would like to see

There is a wrong X64 file link in package manifest. Instead of
**https://github.com/clsid2/mpc-hc/releases/download/2.3.2/MPC-HC.2.3.2.x64.exe**
there must be
**https://github.com/clsid2/mpc-hc/releases/download/2.3.2/MPC-HC.2.3.2.1.x64.exe**

### PR DESCRIPTION
**Pull request by Dragon1573**
## Details

- Change `InstallerUrl` of `x64` architecture.
- Chagne `InstallerSha256` of `x64` architecture.

## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- Resolve #161087

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161111)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by aslze** [comment]
What is going on here? This seems stuck with that validation error since a few days ago. But I'm not sure if it is a problem in the installer or in the validation procedure.

Also this is a duplicate of PR #161077

**Comment by ewanm89** [comment]
> What is going on here? This seems stuck with that validation error since a few days ago. But I'm not sure if it is a problem in the installer or in the validation procedure.
> 
> Also this is a duplicate of PR #161077

Looking at the azure pipeline, it is trying to run the installer, probably with a parameter wrong, this is returning a non-zero exit code and therefore it fails installer validation and needs manual review and intervention, there are a bunch of others that have this problem currently, might be related to issue #157749 but that is talking about CLI applications not graphical installers.

**Comment by Dragon1573** [comment]
> [!CAUTION]
>
> Close with reason: **Duplicate**
>
> - See #161077

**Pull request closed without merging**
