### PR TITLE
New version: Oracle.MySQL version 8.0.39

### LINKED ISSUE #164353: [Package Issue]: Oracle.MySQL
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The Installer download Url appears to be broken.

### Steps to reproduce

`winget update Oracle.MySQL`

I would assume that `winget install Oracle.MySQL` reproduces the issue as well.

### Actual behavior

Install/Update fails to download the installer and fails.

### Expected behavior

Install/Update uses a valid Url and succeeds

### Environment

```raw
PS > winget --info
Windows Package Manager v1.8.1911
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22631.3880
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.23.1911.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                D:\Bennet\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled
```

### Screenshots and Logs

```powershell
PS >winget update Oracle.MySQL
Name                        Id           Version Available Source
-----------------------------------------------------------------
MySQL Installer - Community Oracle.MySQL 8.0.36  8.0.38    winget
1 upgrades available.
1 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.

Installing dependencies:
This package requires the following dependencies:
  - Packages
      Microsoft.VCRedist.2015+.x64
(1/1) Found MySQL [Oracle.MySQL] Version 8.0.38
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dev.mysql.com/get/Downloads/MySQLInstaller/mysql-installer-community-8.0.38.0.msi
An unexpected error occurred while executing the command:
InternetOpenUrl() failed.
0x80072ee2 : unknown error
PS >
```

image

### PR DESCRIPTION
**Pull request by damn-good-b0t**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.3.0 :rocket:

resolves #164353

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164202)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-07-23T08:33:41.8252511Z Manifest Validation Failed
 2024-07-23T08:33:46.8702575Z ##[error]Manifest Validation Failed

(Automated response - build 886.)

**Comment by stephengillie** [comment]
Hi @damn-good-b0t,

It seems there is already a manifest version in the repo with this `DisplayVersion`. The existing manifest will need to be removed before this can be added.

**Comment by stephengillie** [comment]
> @ stephengillie this versioning comes straight from hell #164402

The paths to both "heaven" and "hell" are paved in good intentions. The path to "heaven" is narrow in the ordering of good intentions. (This is a lyrical definiton of entropy, finding the "heaven" of your desired outcome, or the "hell" of some other outcome.) 

The path to this "hell" lay in the unplanned process flow of blocking the removal of the highest version of a package, but requiring the removal of the highest version of a package when a newer version has the same `DisplayVersion`. A better process would be "heavenly".

**Comment by stephengillie** [comment]
>  Manifest Error: DisplayVersion declared in the manifest has overlap with existing DisplayVersion range in the index. Existing DisplayVersion range in index:  [ [1.6.11.0, 1.6.11.0]]

Maybe we need to wait for this manifest to Publish? The other PR is merged, so I'm not sure why the error reocurred.

**Comment by Skgland** [comment]
Are the tests run on the last commit of the PR or on the PR merged with master? In the former case the deletion wouldn't be seen by the tests until the PR updated to be rebased on/merged with master.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334972
> 2024-07-26 06:30:38.105 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!67DD535B: (caller: 67CD1A80) LogHr(1) tid(bf8) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!67E1B5DD: (caller: 67EB12BF) Exception(1) tid(bf8) 8A15005E ] 
> 2024-07-26 06:30:44.675 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!5527535B: (caller: 55171A80) LogHr(1) tid(1560) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!552BB5DD: (caller: 553512BF) Exception(1) tid(1560) 8A15005E ] 
> 2024-07-26 06:30:45.743 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x64 with version 14.40.33810.0

Automated error analysis suggests -1978334972 may mean This package has a dependency missing from your system.

(Automated response - build 887.)

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
