### PR TITLE
PostgreSQL.pgAdmin version 6.2

### PR DESCRIPTION
**Pull request by dpprdan**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/35648)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Please close and reopen the PR to rerun the pipelines.

**Comment by denelon** [comment]
@ItzLevvie take a look at https://github.com/microsoft/winget-pkgs/issues/30364

The command for moderators is `/rerun-pipelines-please`

You can now trigger pipelines to run again 😁

**Comment by ItzLevvie** [comment]
cc @denelon

It doesn't seem to restart the pipelines, seems like only the command works:
image

https://github.com/microsoft/winget-pkgs/pull/35381 & https://github.com/microsoft/winget-pkgs/pull/35712.

**Pull request merged**
