### PR TITLE
New version: Plex.Plex version 1.55.0 [FP-D]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | Plex | Plex    |
| Version     | 1.55.0     | 1.55.0 |
| Publisher   | Plex, Inc.   | Plex, Inc.      |
| ProductCode |           | Plex    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://bittu.eu.org/docs/wpa-intro) in workflow run [3320](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/3160305027>)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Comment by vedantmgoyal2009** [comment]
bump

**Comment by vedantmgoyal2009** [comment]
@denelon please assign to an engineer...

**Comment by Madhusudhan-MSFT** [comment]
@vedantmgoyal2009 - I investigated bit on this installer validation failure. On our local sandbox environment installation is failing with following exception per logs and I do see same exception with the validation pipeline logs.

2022-07-31 14:14:21.676 [CLI ] Completed installer selection.
2022-07-31 14:14:21.729 [CLI ] Caught std::exception: No mapping for the Unicode character exists in the target multi-byte code page.

not sure if this is related to resources file content. Will check with team for the additional understanding.

**Comment by lechacon** [comment]
Looks like a client bug triggered by the Installer URI.

Debugging I found that this is throwing while generating the download path for the installer here:
https://github.com/microsoft/winget-cli/blob/1a6ca17040a0577dceb25af3232649e4bd271b81/src/AppInstallerCLICore/Workflows/DownloadFlow.cpp#L72

At this point, from the installer URI `https://download.cnki.net/cnkiexpress/%E5%85%A8%E7%90%83%E5%AD%A6%E6%9C%AF%E5%BF%AB%E6%8A%A5%20Setup%200.2.23.exe` we have extracted the file name `"全球学术快报%20Setup%200.2.23.exe"`, which seems to be causing that line to throw.

I haven't looked into why it's throwing, so I have no idea for a possible fix.

**Comment by lechacon** [comment]
Oh, there's already an issue in the client for this...
microsoft/winget-cli#2057

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
