### PR TITLE
New version: LesFerch.WinSetView version 2.96

### PR DESCRIPTION
**Pull request by CoolPlayLin**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/152223)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @CoolPlayLin,

This package installs normally, but gives an error when launched:
image

After this it closes.

**Comment by CoolPlayLin** [comment]
CC @LesFerch

**Comment by CoolPlayLin** [comment]
@stephengillie may you retry?

**Comment by LesFerch** [comment]
> CC @LesFerch

Sorry for my ignorance, but what is the correct command line?

I tried:
`winget install CoolPlayLin:LesFerch.WinSetView-2.96-892d3e7f-d497-44bf-ba68-b3bc36b701c7`
`winget search winsetview`

Result:
No package found matching input criteria.

**Comment by LesFerch** [comment]
@CoolPlayLin

What is the correct command line to test the install? I tried searching for it:

`winget search winsetview`

Result: No package found matching input criteria.

**Comment by LesFerch** [comment]
It's a portable app with the only requirement that the files remain together as provided in the zip file. In particular, the Language folder must remain with the Exe. It's pretty simple.

**Comment by stephengillie** [comment]
Oh, that explains it - our package manager creates a symlink into another folder, and running from that location makes these files inaccessable.

**Comment by LesFerch** [comment]
> Oh, that explains it - our package manager creates a symlink into another folder, and running from that location makes these files inaccessable.

I may have been misunderstood. The app does not run from a zip file. The zip file on my GitHub page is nothing special. Just download and unzip it to a folder of your choice and the app should run fine. I'm really struggling to understand how it could be broken in the process of being packaged. If I could just try to install the package I'm sure I'll be able to see right away what's wrong, so please let me know how I can test it.

**Comment by stephengillie** [comment]
To test:
- Copy the 3 files from the [Files changed](https://github.com/microsoft/winget-pkgs/pull/152223/files) tab into 3 new files on a VM or inside a Sandbox. (I use VMs from Hyper-V Quick Create, then speedrun the OOBE and install all updates. Snapshot this and export, then import several times for a small fleet.)
- Run `winget install --manifest c:\path\to\manifest`

> I may have been misunderstood. The app does not run from a zip file. The zip file on my GitHub page is nothing special. Just download and unzip it to a folder of your choice and the app should run fine. I'm really struggling to understand how it could be broken in the process of being packaged. If I could just try to install the package I'm sure I'll be able to see right away what's wrong, so please let me know how I can test it.

Our package manager should only be doing 1 step more than your recommendation:
- Download zip file
- Unzip to a location under `C:\Users\`(username)`\appdata\` (I forget the exact path.)
- Create a symlink to the EXE in a neighboring folder. 

The last step is causing the issue here. It's a design decision by the package manager team to use a symlink (soft link) instead of a .LNK file. This manifest is blocked, but not by an issue with this software package.

**Comment by LesFerch** [comment]
> The last step is causing the issue here. It's a design decision by the package manager team to use a symlink (soft link) instead of an .LNK file. This manifest is blocked, but not by an issue with this software package.

Is there any way to populate the "Start in" property with the exe path? That should fix the problem. As it is currently, the Exe's starting folder is the "Links" folder.
image

**Comment by stephengillie** [comment]
Unfortunately, symlinks don't support "start in" functionality. That's why that box is greyed out in your screenshot.

**Comment by LesFerch** [comment]
> Unfortunately, symlinks don't support "start in" functionality. That's why that box is greyed out in your screenshot.

The symlink works fine if double-clicked or run via Start, Run. The error occurs for me when I execute the symlink from Cmd or PowerShell. I'll take a look at the code and see if there's any way around that.

**Comment by stephengillie** [comment]
> > Unfortunately, symlinks don't support "start in" functionality. That's why that box is greyed out in your screenshot.
> 
> The symlink works fine if double-clicked or run via Start, Run. The error occurs for me when I execute the symlink from Cmd or PowerShell. I'll take a look at the code and see if there's any way around that.

Great catch. I've confirmed this behavior.

**Comment by LesFerch** [comment]
I did some testing and it's clear that the same problem is going to occur with any app that has external files, such as DLLs or language files. All of them error out when the symlink is run from Cmd or PowerShell. For example, here is the error you will get with Audacity:
image

**Comment by Trenly** [comment]
@CoolPlayLin - Support for zipped binaries has now been added and is available in the pipelines. This will require you to update your submission to ManifestVersion: 1.9.0 and set ArchiveBinariesDependOnPath: true in the installer node. To keep things clean, this PR is being closed. Please submit a new PR for the latest version of this package. Thank you for your contributions!

**Pull request closed without merging**
