### PR TITLE
New package: OpenScanTools.OpenScanTools version 1.0.4

### PR DESCRIPTION
**Pull request by jo-chemla**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/172838)

### CODE REVIEW

**Comment by jo-chemla** [comment]
Thanks for the feedback, indeed the installer download link is from pcloud - [here](https://e.pcloud.link/publink/show?code=kZgc6nZ1TnYlXWJ7NRpWjJpbDtwJJ8dYhtX) is the working one, but requires user input to download and select right user key. 

I'll ask the package maintainers if they can release installer to github and update the manifest as soon as it is done. Just did the request here https://github.com/open-scan-crew/OpenScanTools/issues/32 if you want to track it.

**Comment by stephengillie** [comment]
URL: https://edef5.pcloud.com/cBZaSJW8eZzdtqV3ZZZIJ9wkkZ2ZZnoFZkZyHjoRZj5ZAJZ0zZxVZlFZXpZLFZdVZbJZmHZhFZIFZk5Zs0Zgc6nZNexlCqRMThzQnOCn5saEbQHeNh5V/Setup-OpenScanTools-v1.0-build-1.0.4.zip 
Response Error: The remote server returned an error: (410) Gone.

(Automated message - build 921)

**Comment by jo-chemla** [comment]
While the OpenScanTools release is not made available on a more permanent url like a github release, this package cannot be made available to winget-pkgs

**Pull request closed without merging**
