### PR TITLE
Optimate.OptimateSOLIDWORKSPlugin version 0.2.0

### PR DESCRIPTION
**Pull request by schms27**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/103412)

### CODE REVIEW

**Comment by schms27** [comment]
@microsoft-github-policy-service agree company="mcs software ag"

**Comment by schms27** [comment]
I'm not sure how the supporting evidence might look like in our case here. At the moment, the InstallerUrl points to a public package of a private project on gitlab. The publisher wants to keep the project closed source, therefore the private part. Would it be sufficient to make the project public (while keeping the source-repository part of the gitlab project private) and setting the PackageUrl to the then public visible url like https://gitlab.com/optimate1/cad-plugin/-/packages?

**Comment by stephengillie** [comment]
This installer adds mostly DLLs, and the occasional BMP and JSON and other file.

**Comment by stephengillie** [comment]
Hi @schms27,

I'm having difficulty finding the installer on the developer's site. Can you link to the page where you found it?

**Comment by schms27** [comment]
> Hi @schms27,
> 
> I'm having difficulty finding the installer on the developer's site. Can you link to the page where you found it?

I tried to improve this by adding a PackageUrl and by moving the installer to a public gitlab package registry. I asked the publisher (optimate) to link it on their website, but they are hesitant at the moment to use up resources for this. I suppose this is strictly necessary?

**Comment by stephengillie** [comment]
> > Hi @schms27,
> > I'm having difficulty finding the installer on the developer's site. Can you link to the page where you found it?
> 
> I tried to improve this by adding a PackageUrl and by moving the installer to a public gitlab package registry. I asked the publisher (optimate) to link it on their website, but they are hesitant at the moment to use up resources for this. I suppose this is strictly necessary?

Sorry to have caused so much work. Unfortunately, the package also has to come from the publisher's hosting - rehosting or 3rd party hosting won't work out. 

It seems like the publisher doesn't have a direct link to the package on their website - is this true? If so, then the package might not be a good fit for addition into the WinGet public manifests. Packages generally have to be available for anonymous download from almost any physical location at any time. Here, the publisher seems to require registration before download.

**Comment by schms27** [comment]
> > > Hi @schms27,
> > > I'm having difficulty finding the installer on the developer's site. Can you link to the page where you found it?
> > 
> > 
> > I tried to improve this by adding a PackageUrl and by moving the installer to a public gitlab package registry. I asked the publisher (optimate) to link it on their website, but they are hesitant at the moment to use up resources for this. I suppose this is strictly necessary?
> 
> Sorry to have caused so much work. Unfortunately, the package also has to come from the publisher's hosting - rehosting or 3rd party hosting won't work out.
> 
> It seems like the publisher doesn't have a direct link to the package on their website - is this true? If so, then the package might not be a good fit for addition into the WinGet public manifests. Packages generally have to be available for anonymous download from almost any physical location at any time. Here, the publisher seems to require registration before download.

Thanks a lot for clarifying! I will close this for now and ask the publisher to link the package on their site.

**Pull request closed without merging**
