### PR TITLE
Add Brook 20200502

### PR DESCRIPTION
**Pull request by xiaoyang-sde**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1157)

### CODE REVIEW

**Comment by Berkeley-Reject** [comment]
I submitted the file just now.

**Comment by Berkeley-Reject** [comment]
> User Opinion: Incorrect detectionAnalyst comments:
> 
> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"

**Comment by KevinLaMS** [comment]
Greetings.  We got the app through smartscreen, but when I try to run Brook, I get nothing.  Am I missing a dependency?

**Pull request closed without merging**
