### PR TITLE
New package: tumic0.GPXSee version 13.6

### LINKED ISSUE #112088: [Package Request]: GPXSee
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://sourceforge.net/projects/gpxsee/files/Windows/
Publisher: tumic0
Package Name: GPXSee
Description: GPS log file viewer and analyzer.
Package Version: 13.4
Installer URL: https://sourceforge.net/projects/gpxsee/files/Windows/GPXSee-13.4_x64.exe

### PR DESCRIPTION
**Pull request by CoolPlayLin**
### Pull request has been created with [Komac](https://github.com/russellbanks/Komac) v1.9.1 :rocket:
- Resolve #112088
 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/115682&drop=dogfoodAlpha

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Any update?

**Comment by AsciiWolf** [comment]
@CoolPlayLin Any update?

**Comment by CoolPlayLin** [comment]
@AsciiWolf Sorry, I forget to handle this.

**Comment by AsciiWolf** [comment]
It looks like two new versions got released in the meantime:

https://sourceforge.net/projects/gpxsee/files/Windows/GPXSee-13.6_x64.exe

This is the latest one.

**Comment by AsciiWolf** [comment]
@CoolPlayLin

It looks like two new versions got released in the meantime:

https://sourceforge.net/projects/gpxsee/files/Windows/GPXSee-13.6_x64.exe

This is the latest one.

**Review by AsciiWolf — CHANGES_REQUESTED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
