### PR TITLE
Add Cryptomator 1.5.11

### PR DESCRIPTION
**Pull request by luislavena**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/5568)

### CODE REVIEW

**Comment by luislavena** [comment]
Hello @KevinLaMS not sure why validation failed, as this version uses the same installer type (Inno) than previous one (#4956)

In both cases, progress window was shown during installation, but no confirmation was required.

Do you have any other indication what could be the problem?

Thank you in advance ❤️ ❤️ ❤️ 

https://user-images.githubusercontent.com/4182/102674793-798bbc00-4197-11eb-909e-c70c6f3ce85c.mp4

**Comment by luislavena** [comment]
Hello @KevinLaMS, saw the updated labels, but still not sure what is required from my end. Will love to adjust the PR accordingly.

Thank you in advance for your time.
Cheers.

**Comment by KevinLaMS** [comment]
I do not recall.  We will start the process over.

**Comment by KevinLaMS** [comment]
Here is what I am seeing.

image

Maybe you have something that a clean VM does not have installed

**Comment by luislavena** [comment]
Thank you @KevinLaMS, completely forgot that Cryptomator depends on Dokany being installed 🤦🏽‍♂️

It seems silent parameters are not passed down to it.

Will investigate a bit further and get back on this issue.

Thank you again for your detailed response.
❤️ ❤️ ❤️

**Comment by luislavena** [comment]
Closing this now that 1.5.14 has been merged (https://github.com/microsoft/winget-pkgs/pull/10441)

**Pull request closed without merging**
