### PR TITLE
Add Streaming Video Downloader

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/33157)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by binarymark** [comment]
@ItzLevvie Do you know why this is not merged? It says needs at least one review, but you approved it. Your help would be appreciated!

**Review by vedantmgoyal9 — COMMENTED** [review]
Please close and reopen the PR to re-run the pipelines.

**Review by vedantmgoyal9 — CHANGES_REQUESTED** [review]
Please close and reopen the PR to re-run the pipelines.

Pressed the wrong button before.

**Comment by binarymark** [comment]
@vedantmgoyal2009 Thanks for your help!

**Pull request merged**
