### PR TITLE
New Version: TorProject.TorBrowser version 11.0.6

### PR DESCRIPTION
**Pull request by ItsPizzaTime1501**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?
-----
I'll be damned if this ever makes it past pipelines

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/45998)

### CODE REVIEW

**Comment by ItsPizzaTime1501** [comment]
Hm, all URLs should be valid. I guess the bot must've been blocked for downloading too much. Not quite sure what to do about that one.

**Review by OfficialEsco — DISMISSED** [review]
YOU ADDED MORE URLS? You crazy man, it failed with 10 urls before https://github.com/microsoft/winget-pkgs/pull/40730/files

<details>
<summary>Bot validation log</summary>
<br>
 
```
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_tr.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_nb-NO.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_zh-CN.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_mk.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_es-ES.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_pt-BR.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_ca.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_pl.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_nl.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_sv-SE.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_el.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_hu.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_ru.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_id.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_th.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_cs.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_lt.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_it.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_pt-BR.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_zh-TW.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_is.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_lt.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_ja.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_he.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_da.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_en-US.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_my.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_el.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_de.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_tr.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_cs.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_en-US.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_is.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_pl.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_nl.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_fr.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_ja.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_mk.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_sv-SE.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_fr.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_de.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_ro.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_es-AR.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_th.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_vi.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_ru.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_es-ES.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_my.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_hu.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_ga-IE.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_ca.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_es-AR.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_it.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_ka.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_ka.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_ko.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_vi.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_zh-CN.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_he.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_nb-NO.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_ko.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_ms.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_da.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_ro.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_ms.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_id.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-11.0.6_fa.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_zh-TW.exe
Result: Validation Succeeded
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_ga-IE.exe
Result: Download Failed
 
Installer https://dist.torproject.org/torbrowser/11.0.6/torbrowser-install-win64-11.0.6_fa.exe
Result: Download Failed
```
</details>

**Comment by ItsPizzaTime1501** [comment]
> YOU ADDED MORE URLS? You crazy man, it failed with 10 urls before https://github.com/microsoft/winget-pkgs/pull/40730/files

OH, guess I'll remove some and try again. Seems like adding all of the installers might not have been the greatest idea.

**Comment by ItsPizzaTime1501** [comment]
I just commented a bunch out in case someone wants to try it again at a later date.

**Review by OfficialEsco — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
