### PR TITLE
New Version Martchus.syncthingctl version 1.4.1

### PR DESCRIPTION
**Pull request by BrandonWanHuanSheng**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/108082)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
> Possible duplicate package entry.
> 
> Similar installer SHA256 hash found in manifest:
> 
> * `InstallerSha256: 82cb1f3e4a57796d0be6c0360a9b2feaa3bed28de83fa9a49c1a59ff7e480079`
>   
>   * manifests\m\Martchus\syncthingtray\1.4.1

Moving it to new URL, That manifest use wrong URL.manifests\m\Martchus\syncthingtray\1.4.1

**Comment by BrandonWanHuanSheng** [comment]
Suspend Validation-Pipelines

**Comment by BrandonWanHuanSheng** [comment]
It will reopened afterward.

**Comment by stephengillie** [comment]
This package is expecting a config file:
```
QFSFileEngine::open: No file name specified
Error: Unable to locate Syncthing config file and no API key specified
```

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package is expecting arguments:
```
QFSFileEngine::open: No file name specified
Error: Unable to locate Syncthing config file and no API key specified
```

**Pull request merged**
