### PR TITLE
New version: Microsoft.VCLibs.Desktop.14 version 14.0.33728.0

### LINKED ISSUE #161022: [Update Request]: Microsoft.VCLibs.Desktop.14
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Microsoft.VCLibs.Desktop.14

### Package Version

14.0.33728.0

### Please describe the changes you would like to see

Several PRs depend on this version, but we don't have it in the repo yet. 

- https://github.com/microsoft/winget-pkgs/pull/157744
- https://github.com/microsoft/winget-pkgs/pull/158966
- https://github.com/microsoft/winget-pkgs/pull/159246
- https://github.com/microsoft/winget-pkgs/pull/160435

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- Related #161022, but unable to solve it 😞

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161103)

### CODE REVIEW

**Comment by Dragon1573** [comment]
> There were either inconsistencies or values not present in the manifest. Please adjust the manifest accordingly.

Can't understand 😕

**Comment by SpecterShell** [comment]
This is 14.0.33321.0, not 14.0.33728.0.

image

**Comment by Dragon1573** [comment]
## How to install and update Desktop framework packages

Microsoft provides C++ Runtime framework packages to allow applications to reference the C++ runtime from desktop applications distributed through the Windows Store. These packages are distributed and updated through the Windows Store and are handled similarly to C++ UWP framework packages.

For development purposes, the current version (v14.0) of both debug and retail appx packages are included with Visual Studio 2022 when you choose the Universal Windows Platform Development workload with the optional C++ (v143) Universal Windows Tools component. The packages can be found under `%ProgramFiles(x86)%\Microsoft SDKs\Windows Kits\10\ExtensionSDKs\Microsoft.VCLibs.Desktop\14.0`.

> [!NOTE]
>
> **The following package download links are now deprecated, and may no longer work in the future.** Make sure to use the method described above to obtain the framework packages.
>
> - [arm](https://aka.ms/Microsoft.VCLibs.arm.14.00.Desktop.appx)
> - [arm64](https://aka.ms/Microsoft.VCLibs.arm64.14.00.Desktop.appx)
> - [x64](https://aka.ms/Microsoft.VCLibs.x64.14.00.Desktop.appx)
> - [x86](https://aka.ms/Microsoft.VCLibs.x86.14.00.Desktop.appx)

_Originally posted on [C++ Runtime framework packages for Desktop Bridge - Microsoft Learn](https://learn.microsoft.com/en-us/troubleshoot/developer/visualstudio/cpp/libraries/c-runtime-packages-desktop-bridge#how-to-install-and-update-desktop-framework-packages)_

-----

It seems _Microsoft_ will not provide `*.appx` for newer versions of this package. We can only install the package with _Visual Studio IDE_ or _Visual Studio Build Tools_.

Shall I close this pull request? I can't find `*.appx` from any other pages.

**Comment by Dragon1573** [comment]
This pull request will be closed.

- See "Notes" in https://github.com/microsoft/winget-pkgs/pull/161103#issuecomment-2203306513 for more details.

**Pull request closed without merging**
