### PR TITLE
New package: FilesCommunity.Files.Preview version 3.6.0.0

### LINKED ISSUE #166364: [Package Request]: `FilesCommunity.Files.Preview`
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

<table><tr>
	<th>Download Page URI</th>
	<td><a href="https://files.community/download">https://files.community/download</a></td>
</tr><tr>
	<th>Publisher</th>
	<td><a href="https://github.com/files-community">https://github.com/files-community</a></td>
</tr><tr>
	<th>Package Name</th>
	<td>
		<table><tr>
			<th>Static</th>
			<td><code>FilesCommunity.Files.Preview</code></td>
		</tr><tr>
			<th>Vanity</th>
			<td><i>Files - Preview</i> per <a href="https://github.com/microsoft/winget-pkgs/issues/150390#issuecomment-2081062536:~:text=The%20name%20should%20show%20as%20Files%20%2D%20Preview.">https://github.com/microsoft/winget-pkgs/issues/150390#issuecomment-2081062536:~:text=The%20name%20should%20show%20as%20Files%20%2D%20Preview.</a></td>
		</tr></table>
	</td>
</tr><tr>
	<th>Description</th>
	<td> <blockQuote cite="https://apps.microsoft.com/detail/9nghp3dx8hdx?hl=en-gb&gl=GB#:~:text=Introducing%20Files%2C%20the%20ultimate%20file,compression%20and%20decompression%20a%20breeze.">Introducing Files, the ultimate file manager for Windows. With its sleek and intuitive design, navigating through your files and documents has never been easier.</blockQuote> </td>
</tr><tr>
	<th>Package Version</th>
	<td><code>3.6.0.0</code>, from <a href="https://github.com/files-community/Files/releases/tag/v3.6">https://github.com/files-community/Files/releases/tag/v3.6</a> (per <a href="https://github.com/files-community/Files/releases/latest">https://github.com/files-community/Files/releases/latest</a>).</td>
</tr><tr>
	<th>Installer URI</th>
	<td><a href="https://cdn.files.community/files/preview/Files.Package_3.6.0.0_Preview_Test/Files.Package_3.6.0.0_x64_arm64_Preview.msixbundle">https://cdn.files.community/files/preview/Files.Package_3.6.0.0_Preview_Test/Files.Package_3.6.0.0_x64_arm64_Preview.msixbundle</a></td>
</tr></table>

1.	Relates to https://github.com/microsoft/winget-pkgs/issues/150390#issuecomment-2068290158.
1.	Remediates https://github.com/files-community/Files/issues/11380#issue-1591954869.

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- Resolve #166364

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/166641)

### CODE REVIEW

**Comment by stephengillie** [comment]
>  Manifest Error: Optional field missing. [MinimumOSVersion] Value: 10.0.19041.0

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Manually validated. Error `0x80070002` has occurred.
>
> image

Can't sure what was wrong. 😕

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334972
> 2024-08-10 06:22:16.742 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF847A0C11F: (caller: 00007FF847798D6F) LogHr(1) tid(1a34) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF847912B08: (caller: 00007FF8479BBC20) Exception(1) tid(1a34) 8A15005E ] 
> 2024-08-10 06:22:21.385 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF847A0C11F: (caller: 00007FF847798D6F) LogHr(1) tid(14cc) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF847912B08: (caller: 00007FF8479BBC20) Exception(1) tid(14cc) 8A15005E ] 
> 2024-08-10 06:22:29.465 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FF83052C11F: (caller: 00007FF8302B8D6F) LogHr(1) tid(c38) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FF830432B08: (caller: 00007FF8304DBC20) Exception(1) tid(c38) 8A15005E ] 
> 2024-08-10 06:23:08.647 [CORE] Deployment operation #2: Windows cannot install package FilesPreview_3.6.0.0_x64__1y0xx7n9077q4 because this package depends on a framework that could not be found. Provide the framework "Microsoft.WindowsAppRuntime.1.5" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 5001.178.1908.0, along with this package to install. The frameworks with name "Microsoft.WindowsAppRuntime.1.5" currently installed are: {Microsoft.WindowsAppRuntime.1.5_5001.119.156.0_x64__8wekyb3d8bbwe Microsoft.WindowsAppRuntime.1.5_5001.119.156.0_x86__8wekyb3d8bbwe}
> 2024-08-10 06:23:08.647 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!00007FF8303B3F75: (caller: 00007FF83030A720) Exception(2) tid(c38) 80073CF3 Package failed updates, dependency or conflict validation.
> 2024-08-10 06:23:08.756 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FF8303B2D2F: (caller: 00007FF8303B432C) Exception(3) tid(c38) 80073CF1 Package was not found.
> 2024-08-10 06:23:08.756 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(126)\WindowsPackageManager.dll!00007FF830528931: (caller: 00007FF8303B5853) LogHr(2) tid(c38) 80073CF1 Package was not found.
>     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FF8303B2D2F: (caller: 00007FF8303B432C) Exception(3) tid(c38) 80073CF1 Package was not found.
> 2024-08-10 06:23:08.761 [CLI ] MSIX installer failed: 2147958003

Automated error analysis suggests -1978334972 may mean This package has a dependency missing from your system.

Automated error analysis suggests 8A15005E may mean APPINSTALLER_CLI_ERROR_PINNED_CERTIFICATE_MISMATCH - The server certificate did not match any of the expected values.

Automated error analysis suggests 2147958003 may mean Error Installing Dependency - Windows cannot install this package because it depends on a framework (version) that could not be found.

(Automated response - build 887.)

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/152555

**Pull request closed without merging**
