### PR TITLE
New package: JackMacWindows.CraftOS-PC version 2.7.5

### LINKED ISSUE #115055: [Package Request]: CraftOS-PC
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/MCJack123/craftos2/releases
Publisher: JackMacWindows
Package Name: CraftOS-PC
Description: A fast and feature-filled ComputerCraft emulator that allows you to write and run programs inside an '80s-style text console.
Package Version: 2.7.5
Installer URL: https://github.com/MCJack123/craftos2/releases/download/v2.7.5/CraftOS-PC-Setup.exe

### PR DESCRIPTION
**Pull request by Dragon1573**
## Description

- Resolve https://github.com/microsoft/winget-pkgs/issues/115055

## Checks

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/123714)

### CODE REVIEW

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/pull/123726#issuecomment-1779868368

**Comment by Dragon1573** [comment]
Failed ... Discussion is created for help.

- https://github.com/MCJack123/craftos2/discussions/333

_Originally posted by @Dragon1573 in https://github.com/microsoft/winget-pkgs/issues/123726#issuecomment-1781403891_

**Comment by stephengillie** [comment]
Thanks - please feel free to @ me when the discussion is resolved.

**Comment by Dragon1573** [comment]
@stephengillie - The discussion is resolved. 

> Unfortunately it does not appear to be possible to stop the program from automatically launching. There is an option in Inno Setup's source code to disable auto-launching; however, this interferes with the auto-updater, which expects the app to relaunch after updating. I also cannot disable the analytics box for user privacy reasons. I may investigate alternate solutions involving runtime variables if possible, but for the time being you will have to tell users to close the app manually.
>
> _Originally posted by @MCJack123 in [MCJack123/craftos2 discussion-333](https://github.com/MCJack123/craftos2/discussions/333#discussioncomment-7396926)_

**Pull request closed without merging**
