### PR TITLE
Add the Tor Browser

### PR DESCRIPTION
**Pull request by filiptronicek**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/733)

### CODE REVIEW

**Comment by superusercode** [comment]
@filiptronicek tor browser uses the "nullsoft" installertype. If you use that type you don't need to include switches. 

I would do a suggestion to your commit, but github recognizes your file as binary.

**Comment by filiptronicek** [comment]
@superusercode should I then close the pull and create a new one?

**Comment by chausner** [comment]
> @superusercode should I then close the pull and create a new one?

No need to make a new PR, just change the InstallerType in https://github.com/microsoft/winget-pkgs/blob/7c0878788d2879a1dcc4bdf4782314df481e504d/manifests/Tor/Tor/9.0.10.yaml to "nullsoft" and commit to the same branch. This PR will be updated automatically then.

In addition to fixing the installer type, I suggest to change the name to "Tor Browser" as that is the official name on the website and the installed software.

**Comment by filiptronicek** [comment]
I accidentally deleted my fork. Any way I can refference my new fork here?

**Comment by chausner** [comment]
> I accidentally deleted my fork. Any way I can refference my new fork here?

You may try if https://github.blog/2016-08-15-change-the-base-branch-of-a-pull-request/ works. Otherwise it's probably easiest to just open a new PR and close this one here.

**Comment by filiptronicek** [comment]
Unfortunately cannot change the repo from which it is pulling the commits. Will close and make a new pull.
image

**Comment by filiptronicek** [comment]
#1388 is the new pull request.

**Pull request closed without merging**
