### PR TITLE
Added IrfanView x64

### PR DESCRIPTION
**Pull request by JudahGabriel**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/47)

### CODE REVIEW

**Comment by chausner** [comment]
I think this currently fails due to multiple issues:

1. ZIP files are currently not supported so you should use the EXE installer instead.

2. The other problem is that there does not seem to exist any direct download link. The one that you specified that looks like a direct link still resolves to a landing page.

3. The validation bot currently does not seem to be compatible with websites that don't provide the file size in the response header (Content-Length), see https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=79280&view=logs&jobId=c8020aa5-4aab-5881-691f-21986e02afd0&j=c8020aa5-4aab-5881-691f-21986e02afd0&t=bade86d6-d2be-5ddd-c1b9-7d8db9c4a60d:
   ````
   Error occurred during installer copy from https://www.irfanview.info/files/iview454_x64.zip.
    The Content-Length for the copy source is not specified.
   ````

**Comment by superusercode** [comment]
there is an official mirror for the installer at http://m.majorgeeks.com/files/details/irfanview_64.html

**Comment by JudahGabriel** [comment]
@superusercode is there a direct link to the installer? I don't see any on that page.

**Comment by superusercode** [comment]
The link is http://files2.majorgeeks.com/6467afde578ca6d96a9a3f62a7f5a68d5dd8ff51/graphics/iview454_x64_setup.exe

**Comment by JudahGabriel** [comment]
Thanks for the link there. Looks like that's not using any dynamic download tokens. I'll try using that link in the package.

**Comment by JudahGabriel** [comment]
Looks like someone found a direct link to the installer and issued a working PR: https://github.com/microsoft/winget-pkgs/pull/1208

Closing this; we should use that PR instead.

**Pull request closed without merging**
