### PR TITLE
Removed Duplicate voidtools.everything v1.4.1.1005

### PR DESCRIPTION
**Pull request by OfficialEsco**
closes #14381

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14394)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
@arjun-msft or @ChuckFerring please approve, my repo is going crazy because there is a duplicate under 2 different folder names
how did voidtools.everything get past validation when the folder is voidtools.Everything?

**Comment by arjun-msft** [comment]
@OfficialEsco Thanks! We'll need to investigate how to do that, one way would be #13861. 

For this one, you're removing x86 but we actually don't have an x86 entry in the Everything installers, so until we have that we shouldn't remove this even due to the casing issue.

**Comment by OfficialEsco** [comment]
funny story, #14381 removed the x86, i am also reverting that -_-

**Comment by arjun-msft** [comment]
Ha! OK let's see how this goes.

**Comment by OfficialEsco** [comment]
Thaaaank yooou

**Pull request merged**
