### PR TITLE
LocktimeSoftware.NetLimiter4 version 4.1.12.0

### PR DESCRIPTION
**Pull request by krystofkrticka**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/38359)

### CODE REVIEW

**Comment by krystofkrticka** [comment]
That's weird why some packages are able to use dependencies but other don't

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> That's weird why some packages are able to use dependencies but other don't

`PackageDependencies` is listed in some packages because we're still waiting for WinGet to have package dependencies support.

It's currently available in development builds of WinGet, so once it rolls out to the public, the package doesn't need anymore changes because the dependencies are already included in the package.

For this PR, wait until package dependencies rolls out to the public builds of WinGet, and the re-run the pipelines by closing and re-opening the PR.

**Comment by krystofkrticka** [comment]
@ItzLevvie Then why NordVPN package haven't had any problem in which I changed dependency from VC2015-2019 to VC2015-2022

**Comment by ItzLevvie** [comment]
> @ItzLevvie Then why NordVPN package haven't had any problem in which I changed dependency from VC2015-2019 to VC2015-2022

I believe the installer ships VC++ for that package.

Even though you put `Microsoft.VC++2015-2022Redist-x64`, it'll still installs `Microsoft.VC++2015-2019Redist-x64`.

For this package, there's something preventing VC++ from installing correctly in Azure Pipelines.

**Comment by krystofkrticka** [comment]
Yeah this will need to wait for quite a while. Yeah I see dependencies are working for me since I have winget dev build installed.

**Review by ItzLevvie — APPROVED** [review]

**Comment by krystofkrticka** [comment]
@ItzLevvie Is dependency support added or was this approved by mistake?

**Comment by ItzLevvie** [comment]
> Is dependency support added

iirc it won't be out until Q3 or Q4 of 2022.

It's still blocked by https://github.com/microsoft/winget-cli/issues/163.

> was this approved by mistake?

I did it for filtering in GitHub CLI.

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by krystofkrticka** [comment]
This PR is waiting on dependencies

**Comment by ItzLevvie** [comment]
@msftbot Blocking-Issue

**Pull request closed without merging**
