### PR TITLE
New package: SBC.MicroBrowser version 147.5

### PR DESCRIPTION
**Pull request by nicola02nb**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/184762)

### CODE REVIEW

**Comment by stephengillie** [comment]
Verify:
image

Hi @nicola02nb,

image
The last 2 version parameters displayed by the application match the 2 displayed by the Registry. Should a `DisplayVersion` be used here?

**Comment by nicola02nb** [comment]
Yeah, probably is also better to diplay the entire vesrision instead of th e short one... but when you download it form the main website, it's displayed the shorter one... @stephengillie what's you r best suggetison here?

**Comment by Trenly** [comment]
> The last 2 version parameters displayed by the application match the 2 displayed by the Registry. Should a DisplayVersion be used here?

No, since DisplayVersion must match the registry. Since the website and the registry both use the short version (just the last 2 parts), having the `PackageVersion` set to the full version could be confusing for end users

**Comment by nicola02nb** [comment]
Just for reference:

image

**Comment by stephengillie** [comment]
It appears that this application's version number might be confusing for end users, regardless of the changes made to this manifest. As the `DisplayVersion` has a number of downsides, and it wouldn't seem to add value here, I'll approve this manifest without the parameter.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
