### PR TITLE
Treexy.DriverFusion version 10.2.0.5

### PR DESCRIPTION
**Pull request by TreexySoftware**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101124)

### CODE REVIEW

**Comment by TreexySoftware** [comment]
@microsoft-github-policy-service agree company="Treexy"

**Comment by stephengillie** [comment]
Examining this application in a VM causes the PowerShell window to stop responding.

**Comment by TreexySoftware** [comment]
> Examining this application in a VM causes the PowerShell window to stop responding.

You mean the installer or the application? Both work here (tried on three systems).

**Comment by TreexySoftware** [comment]
Works OK in Windows Sandbox too:
image

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
> Works OK in Windows 10 + 11 Sandbox too:
> 
> PowerShell remains responsive; there are no problems.

I think it was an issue with my testing VM's configuration in running this package. After changing a couple of operations, it doesn't freeze.

**Pull request merged**
