### PR TITLE
VcXsrv uses nullsoft, not a generic exe

### PR DESCRIPTION
**Pull request by superusercode**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1086)

### CODE REVIEW

**Review by ghost — APPROVED** [review]
Validation has completed

**Comment by echoix** [comment]
The download URL uses a /latest shortcut (https://sourceforge.net/projects/vcxsrv/files/latest/download), instead of directly pinning a particular file. This will cause a problem if the version is changed. The file should be pinned specifically to the file downloaded on the page https://sourceforge.net/projects/vcxsrv/files/vcxsrv/1.20.8.1/vcxsrv-64.1.20.8.1.installer.exe/download . I don't know exactly how to use the sourceforge links though.

**Comment by superusercode** [comment]
@echoix that is the right way to do it, sorry I missed that on my first PR. Feel free to make a PR amending this.

**Comment by echoix** [comment]
I’m not confortable doing it, since I didn’t understand how to get a direct download link from Sourceforge. On my browser it hand the landing page with ads, and the direct link didn’t seem to work on another browser (took more than 15 sec to respond)

**Comment by superusercode** [comment]
@echoix that link exactly works with winget

you can get the direct download link (using chrome/edge) doing this: 
image

i.e. https://newcontinuum.dl.sourceforge.net/project/vcxsrv/vcxsrv/1.20.8.1/vcxsrv-64.1.20.8.1.installer.exe

but the downside to this is that some users on winget may not be near these servers or these download servers could eventually be removed

if you do submit a pr, all you'll have to do is change the download url line.

**Pull request merged**
