### PR TITLE
New package: SimonG4ELI.SDR-Radio version 3.2

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
image

**Comment by stephengillie** [comment]
Even with the dependency, it still prompts:
image

**Comment by upintheairsheep** [comment]
> Even with the dependency, it still prompts:
> image

Interactive Only

**Comment by AsciiWolf** [comment]
I have created a thread about this in the Bugs section of the [official forums](https://forum.sdr-radio.com:4499). So, hopefully this issue will get fixed.

**Comment by AsciiWolf** [comment]
> I have created a thread about this in the Bugs section of the [official forums](https://forum.sdr-radio.com:4499). So, hopefully this issue will get fixed.

https://forum.sdr-radio.com:4499/viewtopic.php?f=71&t=2044

**Comment by AsciiWolf** [comment]
The "Interactive Only" issue was fixed in latest 3.3 beta build and will be available when a stable 3.3 build gets released. :-)

**Pull request closed without merging**
