### PR TITLE
New version: Microsoft.OneDrive version 22.099.0508.0001

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/62640)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by lechacon** [comment]
Downloading the installer fails with code 80072EFD = WININET_E_CANNOT_CONNECT. It worked on my sandbox just now. Hoping it was a transient error and just re-running it works.

**Comment by OfficialEsco** [comment]
Oh sweet newcomer its not that simple (look at previous PRs up to a year), @denelon i've said it before, but you need to talk to the old/senior winget-pkgs Administrators because OneDrive have been blocked on the VM side because it Auto updates, they blocked it so they had to do a manual review every time, however that was before i found new switches/exit codes.

@palenshus might know about this

**Comment by lechacon** [comment]
Ah, how fun. I wonder how I got lucky enough to not see this on my previous on-call rotations. I'll waive the error, but I agree we need to do something to fix it.

**Pull request merged**
