### PR TITLE
New package: Kingsoft.WPSAI version 12.1.0.15066

### PR DESCRIPTION
**Pull request by CoolPlayLin**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/111635&drop=dogfoodAlpha

### CODE REVIEW

**Comment by SpecterShell** [comment]
You should publish a new version on the existing package `Kingsoft.WPSOffice.CN` instead of creating a new package as this is actually a newer version of that.
BTW the `Publisher` and `PackageName` fields in this manifest should match the ARP entries written by the installer.

**Comment by CoolPlayLin** [comment]
@SpecterShell 
> You should publish a new version on the existing package instead of creating a new package as this is actually a newer version of that. BTW the and fields in this manifest should match the ARP entries written by the installer according to the [docs](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.4.0/installer.md#fields), which are also identical to the ones in .`Kingsoft.WPSOffice.CN``Publisher``PackageName``Kingsoft.WPSOffice.CN`

LGTM, You could open a new PR to replace this PR.

**Comment by Trenly** [comment]
Duplicate of #111655

**Pull request closed without merging**
