### PR TITLE
Fixed generating of yaml file using YamlCreate.ps1

### PR DESCRIPTION
**Pull request by LukasNespor**
Fixed issue with generated yaml file. The file is created using UTF-16 LE encoding which make Azure Pipeline fail during validation.

**Repro steps**
1) Use YamlCreate.ps1
2) Generated yaml file is UTF-16 LE encoded
3) Commit and Push changes to GitHub - yaml file is "broken" and validation fails

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/451)

### CODE REVIEW

**Comment by maxmichels** [comment]
This way you generate UTF8 with BOM. Also you have modified many more lines than needed. I have committed PR #462 to create the file with UTF8 without BOM

**Review by KevinLaMS — APPROVED** [review]

**Comment by KevinLaMS** [comment]
@qiancy98  As you mentioned in the PR 2177, this PR was addressed with #2196 #491 and therefore could be closed a duplicate.  However in addition to the UTF8 issue there are some spacing changes in this PR.  The repo is gone, so I cannot do a merge and will need to recreate like we did with 2196.  @qiancy98 @LukasNespor  Let me know your thoughts.

**Comment by LukasNespor** [comment]
@maxmichels should recreate the the commot/PR because his change is more concise.

**Comment by qiancy98** [comment]
Any choice is OK to me. I did not write any *.ps1 code, and therefore I have no idea on which style is better.

**Comment by qiancy98** [comment]
Seems it can be closed not since #2378

**Comment by denelon** [comment]
#2378 approved.

**Pull request closed without merging**
