### PR TITLE
New package: AILight.AILZ80ASM version 1.0.6

### PR DESCRIPTION
**Pull request by kkamegawa**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest .\manifests\a\AILight\AILZ80ASM\1.0.6`?
- [ ] Have you tested your manifest locally with `winget install --manifest .\manifests\a\AILight\AILZ80ASM\1.0.6`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/120753)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @kkamegawa,

This package installs and launches normally. But most of the text are question marks (?):
image

Is this expected?

**Comment by kkamegawa** [comment]
@stephengillie Thank you validation testing.
This app message works only ja-jp locale. All messages works fine in my Windows(ja-jp).

image

**Comment by stephengillie** [comment]
> wingetbot installationmetadata exe add AILZ80ASM.exe --help

I'm unsure what is meant or implied by this - is this PR missing metadata?

**Comment by hackean-msft** [comment]
> > wingetbot installationmetadata exe add AILZ80ASM.exe --help
> 
> I'm unsure what is meant or implied by this - is this PR missing metadata?

This is meant to add a metadata to to the .validation file that allows daas to append the argument tot he installation during installation verification. The goal is to prevent new versions of this package from returning a non zero exit code, ultimately making it run to completion without the need to apply any form of waiver. This feature has been implemented in the service for a while but only allowed for standalone portables(InstallerType is portable not zip). Thought this installer was just simply a portable installer. @denelon we should open this feature for zip installers(I rarely see standalone portables that are not part of a zip package.

**Comment by denelon** [comment]
If the NestedInstallerType is portable, that would make sense.

**Comment by kkamegawa** [comment]
@hackean-msft @stephengillie 

Is there anything I can do to get them to merge?

**Comment by stephengillie** [comment]
Hi @kkamegawa,

Manual Validation ended with:
> 1:34:06 PM:  > 2023-10-06 13:34:05.201 [FAIL] Installer failed security check. Url: https://github.com/AILight/AILZ80ASM/releases/download/v1.0.6/AILZ80ASM.win-x64.v1.0.6.zip Result: 0x80004005 

This is like a Defender failure. We can retry tomorrow.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
