### PR TITLE
Edit: DuckStudio.ChineseGit version 2.5

### PR DESCRIPTION
**Pull request by DuckDuckStudio**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164363)

### CODE REVIEW

**Review by fjwxzde — APPROVED** [review]

**Review by Luna-Grace — APPROVED** [review]

**Comment by DuckDuckStudio** [comment]
I want to know why there was https://github.com/microsoft/winget-pkgs/labels/Binary-Validation-Error this time and not last time ( #156224 )...

**Comment by stephengillie** [comment]
> 7/24/2024 3:21:50 PM
Installer Verification Analysis Context Information: 
Installer https://github.com/DuckDuckStudio/Chinese_git/releases/download/v2.5/Chinese_git_Setup_v2.5.exe
Scan request id: '79f33f1c-1cf8-4fb3-8efa-ace230e2b9e9'
Error information: BlockingDetectionFound

Unfortunately, I do not have any info about the type of block being used, nor how it was detected.

**Comment by DuckDuckStudio** [comment]
So... how do I solve this problem?

**Comment by DuckDuckStudio** [comment]
It doesn't seem to be for security reasons...

**Comment by DuckDuckStudio** [comment]
image

It doesn't seem to be for security reasons...

**Comment by DuckDuckStudio** [comment]
Is there any way I can solve this issue? The installer looks normal.

**Comment by DuckDuckStudio** [comment]
@stephengillie 
I can't think of any way to solve this issue... If you have any suggestions, please let me know. If not, close the pull request.
Thanks a million.

**Comment by DuckDuckStudio** [comment]
- https://github.com/microsoft/winget-pkgs/pull/164363#issuecomment-2249056411

**Pull request closed without merging**
