### PR TITLE
Delete manifests/m/Malwarebytes/Malwarebytes/4.6.14.401 directory

### PR DESCRIPTION
**Pull request by eldair**
Removed Malwarebytes 4.6.14.401 since that version is not available/released https://support.malwarebytes.com/hc/en-us/sections/360005863113

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/155871)

### CODE REVIEW

**Comment by eldair** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
URL: https://data-cdn.mbamupdates.com/web/mb4-setup-consumer/offline/MBSetup.exe 
OK

(Automated message - build 900)

**Comment by stephengillie** [comment]
Hi @eldair,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 882.)

**Comment by eldair** [comment]
@stephengillie This pull request removes version 4.6.14.401 because that version does not exist/is not released. When I download 4.6.14.401 via winget download, it installs 4.6.13.324 (same as the file from your comment).

image

Also, this seems to be a recurring issue with malawarebytes, new non-existing version being uploaded even though they are the same as current version and not available on malwarebytes website.
https://github.com/microsoft/winget-pkgs/issues/136644
https://github.com/microsoft/winget-pkgs/issues/103103
https://github.com/microsoft/winget-pkgs/issues/62567
there are more of those

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @eldair,

I've added `Malwarebytes.Malwarebytes` to the Review file, so it should prompt me to verify new versions with the release notes provided in your fist comment. Thanks for pointing this out, and that it keeps reocurring.

**Pull request merged**
