### PR TITLE
SylvainRougeaux.Metatogger version 7.5.0.0

### PR DESCRIPTION
**Pull request by CyberSinh**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137780)

### CODE REVIEW

**Comment by CyberSinh** [comment]
Validation fails with label `Validation-Shell-Execute`.

The validation [pipeline logs](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=539443&view=logs&j=68997d86-8ece-5ae8-3ac5-ccdbfa458731&t=b79910ce-dca5-5e27-ad7f-bd285eecb5a2) give no details about the error encountered:

```
****************************************************************************************
Installation Verification
****************************************************************************************

-----------------------------------------------------
Result: Failed
-----------------------------------------------------
Status: Completed
```

Providing the MSI log would be helpful.

`winget install --manifest <path>` correctly installs the application, although Windows SmartScreen validation was required. 

Can anyone tell me what is blocking the validation of my PR?

Thanks!

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335226 2024-02-04 02:40:52.113 [FAIL] WindowsPackageManager.dll!00007FFA6AFEBDD2: ReturnHr(1) tid(6a8) 80190193 Forbidden (403).     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\HttpStream\HttpClientWrapper.cpp(50)\WindowsPackageManager.dll!00007FFA6AFD203A: (caller: 00007FFA6AEB7669) Exception(1) tid(6a8) 80190193 Forbidden (403). 2024-02-04 02:40:52.113 [FAIL] WindowsPackageManager.dll!00007FFA6AE73AF1: LogHr(1) tid(6a8) 80190193 Forbidden (403). 2024-02-04 02:40:52.113 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(53)\WindowsPackageManager.dll!00007FFA6AFF7301: (caller: 00007FFA6AEC04FE) LogHr(2) tid(6a8) 80190193 Forbidden (403).     Msg:[winrt::hresult_error: Forbidden (403).]  2024-02-04 02:40:52.113 [REPO] Source add/update failed, waiting a bit and retrying: winget 2024-02-04 02:40:54.131 [FAIL] WindowsPackageManager.dll!00007FFA6AFEBDD2: ReturnHr(2) tid(6a8) 80190193 Forbidden (403).     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\HttpStream\HttpClientWrapper.cpp(50)\WindowsPackageManager.dll!00007FFA6AFD203A: (caller: 00007FFA6AEB7669) Exception(2) tid(6a8) 80190193 Forbidden (403). 2024-02-04 02:40:54.131 [FAIL] WindowsPackageManager.dll!00007FFA6AE73AF1: LogHr(3) tid(6a8) 80190193 Forbidden (403). 2024-02-04 02:40:54.131 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(540)\WindowsPackageManager.dll!00007FFA6AFF68E3: (caller: 00007FFA6ADB8B8D) LogHr(4) tid(6a8) 80190193 Forbidden (403). 2024-02-04 02:40:54.131 [REPO] Failed to update source: winget 2024-02-04 02:40:54.319 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(564)\WindowsPackageManager.dll!00007FFA6AFF6B53: (caller: 00007FFA6ADB8B8D) LogHr(5) tid(6a8) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFA6AF09298: (caller: 00007FFA6AFC24F9) Exception(3) tid(6a8) 8A15005E ]  2024-02-04 02:40:54.319 [REPO] Failed to open available source: msstore 2024-02-04 02:40:54.329 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(205)\WindowsPackageManager.dll!00007FFA6AED453A: (caller: 00007FFA6AEC0B9E) Exception(4) tid(6a8) 8A15000F  2024-02-04 02:40:54.329 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(564)\WindowsPackageManager.dll!00007FFA6AFF6B53: (caller: 00007FFA6ADB8B8D) LogHr(6) tid(6a8) 8A15000F     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(205)\WindowsPackageManager.dll!00007FFA6AED453A: (caller: 00007FFA6AEC0B9E) Exception(4) tid(6a8) 8A15000F ]  2024-02-04 02:40:54.329 [REPO] Failed to open available source: winget 2024-02-04 02:40:54.329 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(571)\WindowsPackageManager.dll!00007FFA6AEC10DB: (caller: 00007FFA6ADB8B8D) Exception(5) tid(6a8) 8A15004B  2024-02-04 02:42:07.214 [CLI ] ShellExecute installer failed: 1603 Property(S): ErrorDialog = ErrorDlg MSI (s) (BC:3C) [02:42:06:961]: Product: Metatogger 7.5 -- Installation failed. MSI (s) (BC:3C) [02:42:06:961]: Windows Installer installed the product. Product Name: Metatogger 7.5. Product Version: 7.5.0.0. Product Language: 1033. Manufacturer: Sylvain Rougeaux. Installation success or error status: 1603.

(Automated response - build 703.)

**Comment by CyberSinh** [comment]
> Automatic Validation ended with:
> 
> > Installation failed with exit code -1978335226 2024-02-04 02:40:52.113 [FAIL] 
ShellExecute installer failed: 1603 Property(S): ErrorDialog = ErrorDlg MSI (s) (BC:3C) [02:42:06:961]: Product: Metatogger 7.5 -- Installation failed. MSI (s) (BC:3C) [02:42:06:961]: Windows Installer installed the product. Product Name: Metatogger 7.5. Product Version: 7.5.0.0. Product Language: 1033. Manufacturer: Sylvain Rougeaux. Installation success or error status: 1603.
> 
> (Automated response - build 703.)

Status 1603 frequently means a missing dependency. This is not the [first time](https://github.com/microsoft/winget-pkgs/pull/121040) that the pipeline has encountered difficulties in correctly managing software dependencies. Is a definitive fix planned? Thanks!

**Comment by CyberSinh** [comment]
Again a pipeline issue about URL validation: https://github.com/microsoft/winget-pkgs/pull/127314#issuecomment-1823719692

What I don't understand is that [Echosync](https://github.com/microsoft/winget-pkgs/pull/137781), distributed on the same site/domain as Metatogger, poses no problems at all when it comes to validation.

Between the intolerances of the pipeline to software dependencies, and then of the domain, updating Metatogger via winget is anything but smooth and fast.

**Comment by stephengillie** [comment]
Hi @CyberSinh,

Thanks for your patience with our automation, pipelines, and bots. Apparently I was incorrect about `1603` before, and here it wasn't an issue so I added a waiver for that earlier. For the domain, I'm unsure, but if this persists I have an auto-waiver system to mitigate.

**Comment by CyberSinh** [comment]
Hi @stephengillie,

I can see a `Needs-Author-Feedback` tag. 
Do you expect anything from me?

Thanks.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
