### PR TITLE
Update version: Microsoft.PowerToys version 0.78.0

### PR DESCRIPTION
**Pull request by coolplaylinbot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137594)

### CODE REVIEW

**Comment by CoolPlayLin** [comment]
This Pull Request requires approval from @crutkas

**Review by CoolPlayLin — CHANGES_REQUESTED** [review]
This Pull Request requires approval from @crutkas

**Comment by stephengillie** [comment]
Hi @crutkas,

Do you approve of these changes?

(Automated response - build 695.)

**Comment by CoolPlayLin** [comment]
@crutkas

**Pull request closed without merging**
