### PR TITLE
Update Google.Picasa version 3.9.141.259

### PR DESCRIPTION
**Pull request by wtrbtl03**
Updated installer source URL
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/16368)

### CODE REVIEW

**Comment by KaranKad** [comment]
Obsolete application from unofficial download link not allowed.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Download link must come from the ISV's servers.

**Comment by wtrbtl03** [comment]
> 
> 
> Obsolete application from unofficial download link not allowed.

Discontinued but still popular and widely used. Official link not available due to the same reason, hence the use of [arvhive.org](https://archive.org/download/picasa39-setup_201910) link.

**Comment by wtrbtl03** [comment]
> 
> 
> Download link must come from the ISV's servers.

ISV source not available as application has been discontinued by Google. Due to being discontinued, the application doesn't even connect to the internet, this should straighten out some security concerns.
If it's still against some policy do tell me. I'll close the PR.

**Comment by wtrbtl03** [comment]
@ItzLevvie can you provide further instructions

**Comment by ItzLevvie** [comment]
A couple months ago, we had people submitting someone else's apps on OneDrive, Dropbox, etc; despite there being an official download link.

If I rememeber correctly, according to Kevin, the URL must come from the ISV's server, and if it's unavailable, it won't be able to be accepted.

Since the application is discontinued and no longer downloadable on Google's website - I can't confirm if the application has been tampered with.

**Comment by arjun-msft** [comment]
Nice summary @ItzLevvie!  And it is correct, the software needs to come from the ISV's server.

**Comment by wtrbtl03** [comment]
I understand. Even though it is claimed and believed that archive.org only stores the snapshot of the website without any alterations, adding a source from there only adds inconsistencies. I'm taking the PR down.

**Comment by upintheairsheep** [comment]
http://dl.google.com/dl/desktop/R/en/GoogleDesktopSetup.exe
Google still keeps Google Desktop online despite being discontinued for ages

**Pull request closed without merging**
