### PR TITLE
Stoplight.Spectral version 6.6.0

### PR DESCRIPTION
**Pull request by rodrigoborgesdeoliveira**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/86263)

### CODE REVIEW

**Comment by rodrigoborgesdeoliveira** [comment]
@Trenly @ItzLevvie, sorry to tag you here. Do any of you happen to know what the issue might be here? I tested it locally with `winget install -m .\manifests\s\Stoplight\Spectral\6.6.0\` and it worked as expected. But I can't seem to figure out what failed in the azure pipeline. Any help would be appreciated. Thanks!

**Comment by Trenly** [comment]
I believe that portable packages are currently experiencing issues with the pipelines. It seems many (all?) of them are failing validation. Since this has the `Needs-Attention` Label, I'm sure that someone from MSFT like @stephengillie will take a look at it, or @denelon will assign it to the other on-call staff

**Comment by denelon** [comment]
@Trenly is correct. We have some challenges associated with "running" portable packages without any arguments and getting good results. Often, portable packages need arguments to "run" so we can perform thorough analysis in a hands-free automated environment.

**Comment by rodrigoborgesdeoliveira** [comment]
@denelon, is passing an argument something I can try doing to solve this issue? Or is there something better/"more correct" I should try?

**Comment by Trenly** [comment]
> @denelon, is passing an argument something I can try doing to solve this issue? Or is there something better/"more correct" I should try?

Unfortunately there isn’t currently a way to pass an argument into the validation pipelines. The manifest looks correct to me, and seems to install just fine as you said. The only thing we can really do is wait until the on-call engineers evaluate the package and manually approve it

**Comment by rodrigoborgesdeoliveira** [comment]
Yes, it would throw an error if an argument isn't passed. It is possible to pass a `--version` to it.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
