### PR TITLE
GoLang.Go version 1.17.1

### PR DESCRIPTION
**Pull request by tg123**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/27358)

### CODE REVIEW

**Comment by tg123** [comment]
PUA in go386.msi? error `RequestContainsTooManyFlaggedFiles`

**Review by ItzLevvie — APPROVED** [review]

**Comment by tg123** [comment]
@ItzLevvie @denelon no actions at my side right?

**Comment by denelon** [comment]
@tg123, no, there isn't anything to be done on your side. Unless you think this is a false PUA and you want to submit it as a false positive.

**Comment by tg123** [comment]
> @tg123, no, there isn't anything to be done on your side. Unless you think this is a false PUA and you want to submit it as a false positive.

I am not 100% sure, but this is an official download from google `https://dl.google.com/go/go1.17.1.windows-386.msi`
Is there anyway to get detail of PUA? so can file a bug to google

**Comment by denelon** [comment]
Copy Paste from: https://docs.microsoft.com/windows/package-manager/package/winget-validation

During dynamic testing, Microsoft Defender reported a problem. To reproduce this problem, install your application, then run a Microsoft Defender full scan. If you can reproduce the problem, fix the binary or [submit it for analysis](https://docs.microsoft.com/microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives?#part-4-submit-a-file-for-analysis) for false positive assistance. If you are unable to reproduce the problem, add a comment to get the Windows Package Manager engineers to investigate.

**Comment by tg123** [comment]
> Copy Paste from: https://docs.microsoft.com/windows/package-manager/package/winget-validation
> 
> During dynamic testing, Microsoft Defender reported a problem. To reproduce this problem, install your application, then run a Microsoft Defender full scan. If you can reproduce the problem, fix the binary or [submit it for analysis](https://docs.microsoft.com/microsoft-365/security/defender-endpoint/defender-endpoint-false-positives-negatives?#part-4-submit-a-file-for-analysis) for false positive assistance. If you are unable to reproduce the problem, add a comment to get the Windows Package Manager engineers to investigate.

unable to repro, 

env: clean win10 h2

image
image


I also extracted .msi and scan with the defender, nothing found

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Have you tried closing and reopening the PR to rerun the pipelines?

**Comment by tg123** [comment]
seems az pipeline stuck 
@denelon better to check it. no timeout?

**Pull request merged**
