### PR TITLE
New version: TheBrowserCompany.Arc version 1.7.0.33510

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#6009](https://github.com/SpecterShell/Dumplings/actions/runs/9598930945).

<details>

<summary>Log</summary>

````
Updated: 1.6.1.32587 → 1.7.0.33510
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/158966)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-06-20 08:43:39.841 [CORE] Deployment operation #2: Windows cannot install package TheBrowserCompany.Arc_1.7.0.33510_x64__ttt1ap7aakyb4 because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.33728.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00.UWPDesktop" currently installed are: {Microsoft.VCLibs.140.00.UWPDesktop_14.0.29231.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00.UWPDesktop_14.0.30704.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00.UWPDesktop_14.0.33321.0_x64__8wekyb3d8bbwe}
> 2024-06-20 08:43:39.841 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!00007FFBE1443F75: (caller: 00007FFBE139A720) Exception(2) tid(1cf0) 80073CF3 Package failed updates, dependency or conflict validation.
> 2024-06-20 08:43:40.001 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFBE1442D2F: (caller: 00007FFBE144432C) Exception(3) tid(1cf0) 80073CF1 Package was not found.
> 2024-06-20 08:43:40.001 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(126)\WindowsPackageManager.dll!00007FFBE15B8931: (caller: 00007FFBE1445853) LogHr(2) tid(1cf0) 80073CF1 Package was not found.
>     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFBE1442D2F: (caller: 00007FFBE144432C) Exception(3) tid(1cf0) 80073CF1 Package was not found.
> 2024-06-20 08:43:40.050 [CLI ] MSIX installer failed: 2147958003

(Automated response - build 886.)

**Comment by SpecterShell** [comment]
Hold until a newer version of `Microsoft.VCLibs.Desktop.14` is available.

**Comment by stephengillie** [comment]
For reference, waiting until version `14.0.33728.0` or newer is found in [this search](https://github.com/search?q=repo%3Amicrosoft%2Fwinget-pkgs+Microsoft.VCLibs.Desktop.14&type=pullrequests).

**Review by ItzLevvie — APPROVED** [review]

**Comment by SpecterShell** [comment]
https://github.com/microsoft/winget-pkgs/issues/161022

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334972
> 2024-07-31 19:24:10.703 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFF74F2C11F: (caller: 00007FFF74CB8D6F) LogHr(1) tid(fe8) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFF74E32B08: (caller: 00007FFF74EDBC20) Exception(1) tid(fe8) 8A15005E ] 
> 2024-07-31 19:24:13.994 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFF74F2C11F: (caller: 00007FFF74CB8D6F) LogHr(1) tid(14c8) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFF74E32B08: (caller: 00007FFF74EDBC20) Exception(1) tid(14c8) 8A15005E ] 
> 2024-07-31 19:24:24.477 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFF593DC11F: (caller: 00007FFF59168D6F) LogHr(1) tid(1418) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFF592E2B08: (caller: 00007FFF5938BC20) Exception(1) tid(1418) 8A15005E ] 
> 2024-07-31 19:25:11.509 [CORE] Deployment operation #2: Windows cannot install package TheBrowserCompany.Arc_1.7.0.33510_x64__ttt1ap7aakyb4 because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00.UWPDesktop" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.33728.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00.UWPDesktop" currently installed are: {Microsoft.VCLibs.140.00.UWPDesktop_14.0.29231.0_x86__8wekyb3d8bbwe Microsoft.VCLibs.140.00.UWPDesktop_14.0.30035.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00.UWPDesktop_14.0.30704.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00.UWPDesktop_14.0.33321.0_x64__8wekyb3d8bbwe}
> 2024-07-31 19:25:11.509 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!00007FFF59263F75: (caller: 00007FFF591BA720) Exception(2) tid(1418) 80073CF3 Package failed updates, dependency or conflict validation.
> 2024-07-31 19:25:11.637 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFF59262D2F: (caller: 00007FFF5926432C) Exception(3) tid(1418) 80073CF1 Package was not found.
> 2024-07-31 19:25:11.638 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(126)\WindowsPackageManager.dll!00007FFF593D8931: (caller: 00007FFF59265853) LogHr(2) tid(1418) 80073CF1 Package was not found.
>     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FFF59262D2F: (caller: 00007FFF5926432C) Exception(3) tid(1418) 80073CF1 Package was not found.
> 2024-07-31 19:25:11.667 [CLI ] MSIX installer failed: 2147958003

Automated error analysis suggests -1978334972 may mean This package has a dependency missing from your system.

Automated error analysis suggests 8A15005E may mean APPINSTALLER_CLI_ERROR_PINNED_CERTIFICATE_MISMATCH - The server certificate did not match any of the expected values.

Automated error analysis suggests 2147958003 may mean Error Installing Dependency - Windows cannot install this package because it depends on a framework (version) that could not be found.

(Automated response - build 887.)

**Comment by SpecterShell** [comment]
https://github.com/microsoft/winget-pkgs/issues/161022

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
[Policy] Dependencies
[Policy] Blocking-Issue

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

(Automated response - build 923.)

**Pull request merged**
