### PR TITLE
New package: DG0JBJ.HDSDR version 2.81-b6

### LINKED ISSUE #111376: [Package Request]: HDSDR
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.hdsdr.de
Publisher: hdsdr.de
Package Name: HDSDR
Description: Freeware Software Defined Radio (SDR) program.
Package Version: 2.80
Installer URL: https://www.hdsdr.de/download/HDSDR_install.exe

### PR DESCRIPTION
**Pull request by AsciiWolf**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

Closes #111376.

Tested and everything works fine.
 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114332&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by AsciiWolf** [comment]
It looks like there is something wrong with the bot.

**Comment by AsciiWolf** [comment]
@ItzLevvie Any idea what could be wrong? Thanks!

**Comment by AsciiWolf** [comment]
@stephengillie Any idea what could be wrong?

**Comment by AsciiWolf** [comment]
@Trenly Any idea what could be wrong?

**Comment by Trenly** [comment]
[Policy] Reset-Feedback

**Review by Trenly — APPROVED** [review]

**Pull request merged**
