### PR TITLE
Create 1.18.0.yaml

### PR DESCRIPTION
**Pull request by yualan**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/358)

### CODE REVIEW

**Comment by denelon** [comment]
@yualan Can you check for switches to support unattended / no UI?

**Comment by yualan** [comment]
We have the same installer as VS Code, so if they have support for unattended UI, we can follow same pattern. If they do not, then we can proceed with the same experience as VS Code.

**Comment by denelon** [comment]
Thanks for the clarification. Since the installer did complete without me having to engage with any other UX, I'll go ahead and mark this completed.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
