### PR TITLE
PowerShell Preview 7.4.0.5: Correct msix installer URL

### PR DESCRIPTION
**Pull request by anamnavi**
Due to a typo with incorrect installer URL (but correct hashes) the hash doesn't match the installer and wingetbot created a PR to remove this installer entirely. Instead this PR, fixes the installer URL so that it now matches the hashes.

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131926)

### CODE REVIEW

**Comment by stephengillie** [comment]
Labels didn't apply and I'm not sure why.

**Review by mdanish-kh — APPROVED** [review]

**Comment by stephengillie** [comment]
>  Manifest Error: Inconsistent value in the manifest. [PackageVersion] Value: 7.4.5.0

**Comment by stephengillie** [comment]
> Manifest Error: Inconsistent value in the manifest. [PackageVersion] Value: 7.4.5.0

This is odd as I do not find `7.4.5.0` at all in this manifest file.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
