### PR TITLE
Update MicaForEveryone.MicaForEveryone.installer.yaml URL

### PR DESCRIPTION
**Pull request by rakleed**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/130481)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
The URLs should be pointed at the specific version and not at latest. If the Latest version changes, it will cause the package to become broken.

The URLS existing in the manifest should not be changed

**Comment by Trenly** [comment]
> > The URLs should be pointed at the specific version and not at latest. If the Latest version changes, it will cause the package to become broken.
> 
> @Trenly but why? If I specify the URL to the latest version, then your system could automatically detect a new version when the installer hash will change.

The detection system is not perfect, and it will also remove old versions. It is intended only for Vanity URLs when there is not a versioned URL available.  There are other tools available for detecting new GitHub releases such as @vedantmgoyal2009's automation or his WinGetReleaser action

**Comment by stephengillie** [comment]
I'll add this as a buggy solution. It should be removed and replaced with a more robust solution in the future.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
