### PR TITLE
Telegram.TelegramDesktop 2.1.13

### PR DESCRIPTION
**Pull request by Xeevis**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2313)

### CODE REVIEW

**Comment by denelon** [comment]
@Xeevis is your intent to remove support for the 2.1.10 version from the repository? Generally, we would keep the previous package versions available.

**Comment by Xeevis** [comment]
@denelon I understand, however I don't see any benefit in keeping older versions for this package. Upon first launch, after installation, update is automatically downloaded and applied with no apparent way to avoid it (only future updates can be disabled). This behavior can be observed on the following video https://vimeo.com/436521846

**Comment by denelon** [comment]
@Xeevis That's fine. You might get the same message from one of us again. We've been thinking about ways to indicate Apps that auto-update themselves.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
