### PR TITLE
add git-tfs 0.34.0

### PR DESCRIPTION
**Pull request by pmiossec**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? No.

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/153871)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @pmiossec,

This package installed normally, but had a few issues running:
image

- First is a known issue where the package manager creates a symlink to the application, and while the application runs, the symlink does not. This is usually due to the "start in" folder being the symlink location instead of the application location, preventing the application from reaching files it needs.
- Second, this application gave an error when launched from its folder. Is this expected?

**Comment by pmiossec** [comment]
@stephengillie Thanks for the feedback

>     * First is a known issue where the package manager creates a symlink to the application, and while the application runs, the symlink does not. This is usually due to the "start in" folder being the symlink location instead of the application location, preventing the application from reaching files it needs.

What do you recommend to solve the issue?
Removing the symlink is enough? Or there is a better solution?
I have not found a clear solution...

>     * Second, this application gave an error when launched from its folder. Is this expected? Edit: Should `Microsoft.VisualStudioCode` or similar be a dependency?

There is a dependency on "Microsoft Visual Studio" (not Code 😉 ).
But we can't enforce a dependency for a specific version because normally, the developer already has a version installed and it could be any version in 2015, 2017, 2019 or 2022. git-tfs successfully load the dependency dll depending on the version installed.
It could be handled a little more gracefully but I don't think we should block the merge for this reason (the behavior is like that for years and we never had a complain because it's a known dependency by the user)

**Comment by stephengillie** [comment]
A bot is supposed to link this issue when the https://github.com/microsoft/winget-pkgs/labels/zip-binary label is applied: 
- https://github.com/microsoft/winget-cli/issues/2711

**Comment by pmiossec** [comment]
> A bot is supposed to link this issue when the [ zip-binary](https://github.com/microsoft/winget-pkgs/labels/zip-binary) label is applied:

It did 😉 
That's why I said that "**I** have not found a clear solution" 😟
A lot of messages and talking about different subject (auto-unpack exe, bat file) bat without a message providing a clear answer of a solution to follow...

As I said, I think I will remove the symlink because I don't see an added value. Is it ok?

**Comment by stephengillie** [comment]
> As I said, I think I will remove the symlink because I don't see an added value. Is it ok?

If it's possible to remove, I would be very interested to learn how.

**Comment by pmiossec** [comment]
> > As I said, I think I will remove the symlink because I don't see an added value. Is it ok?
> 
> If it's possible to remove, I would be very interested in learning how.

Indeed. A previous attempt made me think that not adding `PortableCommandAlias:` line will not create the symlink but a quick try confirm your thought, the symlink is created. A dirty (working) workaround is to name it something like `PortableCommandAlias: _git-tfs_DONT_USE_THIS_ALIAS`...

**Comment by pmiossec** [comment]
@stephengillie Do you think it's an acceptable (dirty) workaround?
If yes, I push it. Otherwise, I don't know how to go forward...

**Comment by stephengillie** [comment]
Hi @pmiossec,

Sorry to miss this. Without the symlink alias, how will users find the application? Some of our users might be people who install random applications for a hobby, and some might install this.

**Comment by Trenly** [comment]
@pmiossec - Support for zipped binaries has now been added and is available in the pipelines. This will require you to update your submission to ManifestVersion: 1.9.0 and set ArchiveBinariesDependOnPath: true in the installer node. To keep things clean, this PR is being closed. Please submit a new PR for the latest version of this package. Thank you for your contributions!

**Pull request closed without merging**
