### PR TITLE
Updated Tidal (yes, people use Tidal) to version 2.29.7.

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

------

I don't use Tidal, but people do. Apparently.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/43154)

### CODE REVIEW

**Review by OfficialEsco — DISMISSED** [review]
I use Tidal! >:C + Spotify with Adblock 😎

**Comment by OfficialEsco** [comment]
> Hello @jedieaston, The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.

```
Enter a pull request number: #43154

Manifest validation succeeded.
Found TIDAL [TIDALMusicAS.TIDAL] Version 2.29.6
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.tidal.com/desktop/TIDALSetup.exe
  ██████████████████████████████  95.2 MB / 95.2 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Press any key to continue . . .
```
VirtualBoxVM_ACzlLtI71O
VirtualBoxVM_Lmpv58K6i8

**Comment by jedieaston** [comment]
It looks like they just pushed a patch to 2.29.7, at least on some of their CDN. 

image

**Comment by jedieaston** [comment]
I'll give it a few hours and try again...

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
