### PR TITLE
Add AxCrypt 2

### PR DESCRIPTION
**Pull request by ath0mas**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1668)

### CODE REVIEW

**Comment by SoftCreatR** [comment]
@ath0mas Just in case you need it ;)

`https://www.winget.it/dl/c01ae6a5c51c54c100ff731e8ea3b67bffe1ce3598bfc6c2b70cbff4da685f6b/https%3A%2F%2Faccount.axcrypt.net%2Fdownload%2FAxCrypt-2.1.1585.0-Setup.exe`

**Comment by ath0mas** [comment]
@SoftCreatR so nice of you! ^^
I was thinking about it, and about you ;) and it maybe be needed for its sister PR #1667 (I found an alternate download url for version 1.7 as the main site download urls work like 10% of the time...)

**Comment by KevinLaMS** [comment]
The URL provided for the app is not from the correct source.  I would expect it to be from:
https://account.axcrypt.net/download/axcrypt-2-setup.exe

**Comment by SoftCreatR** [comment]
@kevinlams But the original URL doesn't work with winget as you can see here: https://github.com/microsoft/winget-pkgs/pull/1668#issuecomment-640278602

**Comment by SoftCreatR** [comment]
@kevinlams

Okay, that's ridiculous. All PRs using my proxy solution are now being declined for no real reason. Go and fix your client then.

I don't want to waste any more time and money with this. I'll shut down our build server and do something useful, where my work is being respected and where people have trust in what I do.

**Comment by ath0mas** [comment]
@KevinLaMS ... changed to https://account.axcrypt.net/download/AxCrypt-2.1.1585.0-Setup.exe = the official and stable link
=> but please fix download failure issue in your pipelines!! trying this manifest locally works fine

**Pull request closed without merging**
