### PR TITLE
New version: PolarGoose.ShowWhatProcessLocksFile version 6.0

### PR DESCRIPTION
**Pull request by PolarGoose**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/153131)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @PolarGoose,

This manifest removes Apps and Features entries that are present in previous PR versions. These entries should be added to this version, to maintain version matching, and prevent the 'upgrade always available' situation with this package.

(Automated response - build 880.)

**Comment by PolarGoose** [comment]
@stephengillie,
Thank you for the remark.
I have tested my manifest, and it creates an `Apps and Features` entry:
image

**Comment by stephengillie** [comment]
Oh - this is referring to the `AppsAndFeaturesEntries` field and values in a manifest. Not the entry in the Settings page. This message is out of date. The main value that it's seeking to mitigate is `DisplayVersion`, but that's not in use here, so it's not as important.

The [previous PR](https://github.com/microsoft/winget-pkgs/pull/88069/files) had:

```yaml
  AppsAndFeaturesEntries:
    - ProductCode: '{2D35E2E6-3FE3-4D1E-9B94-8352495D1A35}'
      UpgradeCode: '{ECBB21BF-5B26-4971-AAC2-D3528A7F10FB}'
```

Should these values be added to this manifest? If not, it's okay.

**Comment by PolarGoose** [comment]
It is ok not to add them. These fields are optional.

**Comment by stephengillie** [comment]
Hi @PolarGoose,

This manifest removes Apps and Features entries that are present in previous PR versions. These entries should be added to this version, to maintain version matching, and prevent the 'upgrade always available' situation with this package.

(Automated response - build 880.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
