### PR TITLE
removed incorrect 'v' PackageVersion prefix (partial revert of #16683)

### PR DESCRIPTION
**Pull request by ErikBjare**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

Partially reverted #16683, reason explained therein.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/17564)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
(re: https://github.com/microsoft/winget-pkgs/pull/16683): This is because your application shows up as `v0.10.0` in Control Panel:
image

Windows Package Manager seem to work a bit differently (compared to other package managers), and requires the keys in the manifest to match whatever shows up in Control Panel's **A**dd or **R**emove **P**rograms (**ARP**) to make sure that other people can have the best application upgrade experience as possible.

This is documented here: https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.0.0/defaultLocale.md#packageversion; alongside with other keys.

If possible, I would advise you to update the application to remove `v` part before submitting a revert and getting it merged to master, otherwise, it won't be merged because people will submit issues about the application being updated on a constant loop with the `winget upgrade` command.

I've also wrote other comments about it here: https://github.com/microsoft/winget-pkgs/pull/17302#issuecomment-860293746

**Comment by ErikBjare** [comment]
Ah, I see.

I'll fix the upstream installer. Will loop back here when we have a new release.

**Comment by ErikBjare** [comment]
@ItzLevvie v0.11.0 released! Please let me know how to proceed :)

**Comment by OfficialEsco** [comment]
Hey @ErikBjare would you mind if i created the Manifest? then you can edit the Metadata if something is wrong/missing?

**Pull request closed without merging**
