### PR TITLE
Metadata: dnGrep.dnGrep version 2.9.256.0

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

image

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/22167)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-pkgs/pull/22166#issuecomment-886110868

**Comment by OfficialEsco** [comment]
@ItzLevvie can you test this one?
I was going to try a few properties from the MSI to check if i could find a property to disable the popup, but for some reason ITS NOT THERE ANYMORE??

**Comment by ItzLevvie** [comment]
image

**Comment by OfficialEsco** [comment]
Welp thank you, guess there is no updates for me then
image

I can't seem to find ANYTHING in the MSI referring to `check for new version`, and my installation is actually lightning fast now that it doesn't do it, guessing it can't connect to the server?

**Comment by OfficialEsco** [comment]
.

**Comment by OfficialEsco** [comment]
Closing these PRs since the dnGrep devs seems to have no idea how to not check for update.

**Pull request closed without merging**
