### PR TITLE
Update Stremio.Stremio to 4.4.137

### PR DESCRIPTION
**Pull request by ptanmay143**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/13119)

### CODE REVIEW

**Comment by ptanmay143** [comment]
I don't understand why it says mutiple manifests. It's only one application. I checked it twice and I have that directory structure too. I'm not sure why its failing.

**Comment by denelon** [comment]
@ptanmay143 it looks like you did a "rename". Unfortunately, the code to support this scenario isn't in production quite yet. We anticipate having the change completed in production this week. GitHub shows us a delete and an add. That's why you are seeing the reference for multiple manifests (one for delete and one for add). You will either need to perform the "add" and once it's merged, perform the delete if you want to remove the previous version.

Otherwise, we can see when the change to support rename works it's way into production.

**Comment by ptanmay143** [comment]
I will make a PR for adding just the new manifest. Is it required for me to delete the old manifest? I found a lot of apps with multiple versions.

**Comment by denelon** [comment]
@ptanmay143 many users prefer to have the ability to install a specific (earlier) version of a package. If the earlier version is still available, it is preferred to add a new manifest for the new version.

**Pull request closed without merging**
