### PR TITLE
New version: SAPIEN.PowerShellStudio version 5.8.235.0

### PR DESCRIPTION
**Pull request by SpecterShell**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/130517)

### CODE REVIEW

**Comment by SpecterShell** [comment]
```
Disk full: Out of disk space -- Volume: 'C:'; required space: 6,555,376 KB; available space: 3,602,048 KB.  Free some disk space and retry.
```

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 
> 2023-12-14 23:37:18.342 [FAIL] D:\a\1\s\src\AppInstallerRepositoryCore\IconExtraction.cpp(113)\WinGetUtil.dll!00007FFFF3FC97A6: (caller: 00007FFFF3FCA1C2) Exception(1) tid(1114) 800700C1 %1 is not a valid Win32 application. 
> 2023-12-14 23:37:18.369 [FAIL] D:\a\1\s\src\AppInstallerRepositoryCore\IconExtraction.cpp(212)\WinGetUtil.dll!00007FFFF41175F5: (caller: 00007FFFF3FCA1C2) LogHr(1) tid(1114) 800700C1 %1 is not a valid Win32 application.     Msg:[D:\a\1\s\src\AppInstallerRepositoryCore\IconExtraction.cpp(113)\WinGetUtil.dll!00007FFFF3FC97A6: (caller: 00007FFFF3FCA1C2) Exception(1) tid(1114) 800700C1 %1 is not a valid Win32 application.  Installation failed with exit code -1978335226 
> 2023-12-14 23:37:17.062 [CLI ] ShellExecute installer failed: 1603 LookupUserGroupFromRid() FAILED LookupAccountSidW() FAILED LookupUserGroupFromRidSDDL() FAILED LookupAliasFromRid() FAILED Property(S): ErrorDialog = ErrorDlg MSI (s) (34:84) [23:37:11:671]: Product: PowerShell Studio 2023 -- Installation failed. MSI (s) (34:84) [23:37:11:671]: Windows Installer installed the product. Product Name: PowerShell Studio 2023. Product Version: 5.8.235.0. Product Language: 1033. Manufacturer: SAPIEN Technologies, Inc.. Installation success or error status: 1603.

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 12:55:07 PM: 
> 2023-12-15 12:55:06.097 [CORE] Download request failed. Returned status: 403

(Automated response - build 485.) Manual Validation ended with:
> 12:55:07 PM: 
> 2023-12-15 12:55:06.097 [CORE] Download request failed. Returned status: 403

**Comment by stephengillie** [comment]
Verify: 
image

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 
> 2023-12-21 04:30:16.620 [FAIL] D:\a\1\s\src\AppInstallerRepositoryCore\IconExtraction.cpp(113)\WinGetUtil.dll!00007FFEEA818BA0: (caller: 00007FFEEA8195BF) Exception(1) tid(60c) 800700C1 %1 is not a valid Win32 application. 
> 2023-12-21 04:30:16.656 [FAIL] D:\a\1\s\src\AppInstallerRepositoryCore\IconExtraction.cpp(212)\WinGetUtil.dll!00007FFEEA963C65: (caller: 00007FFEEA8195BF) LogHr(1) tid(60c) 800700C1 %1 is not a valid Win32 application.     Msg:[D:\a\1\s\src\AppInstallerRepositoryCore\IconExtraction.cpp(113)\WinGetUtil.dll!00007FFEEA818BA0: (caller: 00007FFEEA8195BF) Exception(1) tid(60c) 800700C1 %1 is not a valid Win32 application.  Installation failed with exit code -1978335226 
> 2023-12-21 04:30:14.385 [CLI ] ShellExecute installer failed: 3221226356 LookupUserGroupFromRid() FAILED LookupAccountSidW() FAILED LookupUserGroupFromRidSDDL() FAILED LookupAliasFromRid() FAILED Property(S): ErrorDialog = ErrorDlg MSI (s) (10:DC) [04:30:06:419]: Windows Installer installed the product. Product Name: PowerShell Studio 2023. Product Version: 5.8.235.0. Product Language: 1033. Manufacturer: SAPIEN Technologies, Inc.. Installation success or error status: 0.

(Automated response - build 490.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
