### PR TITLE
Add version: Henry++.simplewall version .3.6

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
\n\nAuto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/winget-pkgs-automation)

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/34448)

### CODE REVIEW

**Review by jedieaston — DISMISSED** [review]

**Review by jedieaston — APPROVED** [review]

**Comment by OfficialEsco** [comment]
Hey @jedieaston since you know this kind of stuff, would you be able to look at Simplewall's installer? Its not installing correctly when you use the /S switch, which wingetbot probably noticed too...

I DID make a issue over there but got yelled at that its Open Source and that i can fix it my self by submitting a PR... Which i obv can't when i don't know what i'm looking at.

**Comment by jedieaston** [comment]
Oh, I see. I thought it not writing to the ARP table was intentional, not that it literally wasn't installing at all. I'll take a peek.

**Comment by OfficialEsco** [comment]
> Oh, I see. I thought it not writing to the ARP table was intentional, not that it literally wasn't installing at all. I'll take a peek.

Weeeell, it does "install", but its works more like extracting when the silent switch is included, if you run the installer in interactive mode everything works as expected, so yeah something is just wrong with their installer, which they don't like people pointing at 🤦‍♂️

**Comment by jedieaston** [comment]
Their .nsi file isn't in that repo. Without that I can't figure out what's going on, but I'm guessing that they've set some of the properties to be set only if the GUI is rendered. 

Maybe you should reopen that issue and ask them to post it.

**Comment by vedantmgoyal2009** [comment]
> Maybe you should reopen that issue and ask them to post it.

He probably can't because the issue was closed by the maintainer itself.

**Comment by jedieaston** [comment]
Well, darn. I'm not in a very "stirring stuff up" mood at the moment or I'd open another issue.

Since this PR is assigned, maybe we can get a validation override for the executable error? It _is_ putting an executable in Program Files.

**Comment by ItzLevvie** [comment]
> Their .nsi file isn't in that repo. Without that I can't figure out what's going on, but I'm guessing that they've set some of the properties to be set only if the GUI is rendered.

Is it this https://github.com/henrypp/builder/blob/master/setup_script.nsi?

**Comment by vedantmgoyal2009** [comment]
Probably yes because this line exists in that... https://github.com/henrypp/builder/blob/master/setup_script.nsi#L185

I think he maintains one script for "all" his projects.

**Comment by jedieaston** [comment]
The start menu shortcuts and other areas we have trouble with all have `IfSilent: Skip` turned on. They might have a reason (maybe it interferes with their automatic updater?)

**Pull request merged**
