### PR TITLE
Elgato.StreamDeck version 5.0.1.14252

### PR DESCRIPTION
**Pull request by zephiowl**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/17513)

### CODE REVIEW

**Comment by Xanthus58** [comment]
I am unsure of the issue; I have tried troubleshooting and testing on my end, and everything comes back positive. If I could get some assistance that would be greatly appreciated.

**Comment by OfficialEsco** [comment]
Late answer, try to close and reopen the PR. (The bot is being childish and requires another /AzurePipelines run)

**Comment by Xanthus58** [comment]
> Late answer, try to close and reopen the PR. (The bot is being childish and requires another /AzurePipelines run)

ahh alrighty thank you I'll resubmit it

**Comment by Xanthus58** [comment]
> > Late answer, try to close and reopen the PR. (The bot is being childish and requires another /AzurePipelines run)
> 
> ahh alrighty thank you I'll resubmit it

https://github.com/microsoft/winget-pkgs/pull/17528

**Comment by OfficialEsco** [comment]
🤦‍♂️ The button you used to close the PR becomes a Open PR button when you click it :D 
Npnp

**Pull request closed without merging**
