### PR TITLE
Synology.DriveClient version 7.5.0.16084

### PR DESCRIPTION
**Pull request by s-crypt**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150139)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-04-19 13:05:34.948 [CLI ] ShellExecute installer failed: 1603
> Property(S): ErrorDialog = ErrorDlg
> MSI (s) (2C:F8) [13:05:34:742]: Product: Synology Drive Client -- Installation failed.

(Automated response - build 877.)

**Comment by s-crypt** [comment]
This is strange. The installer works when run manually, but not when run through winget. Tested via Windows Sandbox on Windows 11 where the logs say "Windows version is not compatible". Not quite sure how to fix this.

<details><summary>Winget Log</summary>

```
=== Logging started: 4/22/2024  16:00:40 ===
Action start 16:00:40: INSTALL.
Action start 16:00:40: LaunchConditions.
Action ended 16:00:40: LaunchConditions. Return value 0.
Action start 16:00:40: NotSupportedWindows.
MSI (s) (EC:9C) [16:00:40:168]: Product: Synology Drive Client -- Cannot install Synology Drive Client because your Windows version is not compatible.

Cannot install Synology Drive Client because your Windows version is not compatible.
Action ended 16:00:40: NotSupportedWindows. Return value 3.
Action ended 16:00:40: INSTALL. Return value 3.
Property(S): ProductCode = {F041F9D7-6AD5-47AC-A0AB-817DBCE2972B}
Property(S): InstallMode = Complete
Property(S): UpgradeCode = {227BB9F5-9F79-4686-AC42-15132A1EB39E}
Property(S): LaunchApp = 1
Property(S): BannerBitmap = bannrbmp
Property(S): IAgree = No
Property(S): AppsShutdownOption = All
Property(S): ProductID = none
Property(S): ALLUSERS = 1
Property(S): ARPHELPLINK = http://www.synology.com
Property(S): ARPNOMODIFY = 1
Property(S): ARPNOREPAIR = 1
Property(S): ARPPRODUCTICON = desktop_icon.exe
Property(S): ButtonText_Back = &Back
Property(S): ButtonText_Browse = Br&owse
Property(S): ButtonText_Cancel = Cancel
Property(S): ButtonText_Exit = &Exit
Property(S): ButtonText_Finish = &Finish
Property(S): ButtonText_Ignore = &Ignore
Property(S): ButtonText_Install = &Install
Property(S): ButtonText_Next = &Next
Property(S): ButtonText_No = &No
Property(S): ButtonText_OK = OK
Property(S): ButtonText_Print = &Print
Property(S): ButtonText_Remove = &Remove
Property(S): ButtonText_Repair = &Repair
Property(S): ButtonText_Reset = &Reset
Property(S): ButtonText_Resume = &Resume
Property(S): ButtonText_Retry = &Retry
Property(S): ButtonText_Return = &Return
Property(S): ButtonText_Yes = &Yes
Property(S): CloudStationVersion = 3010
Property(S): CompleteSetupIcon = completi
Property(S): CustomSetupIcon = custicon
Property(S): DefaultUIFont = DlgFont8
Property(S): DialogBitmap = dlgbmp
Property(S): DlgTitleFont = {&DlgFont8}
Property(S): ErrorDialog = ErrorDlg
Property(S): ExclamationIcon = exclamic
Property(S): INSTALLLEVEL = 3
Property(S): InfoIcon = info
Property(S): InstallerIcon = insticon
Property(S): Link = Windows Installer Development Tools on MSDN
Property(S): LinkURL = http://msdn2.microsoft.com/en-us/library/aa372834(VS.85).aspx
Property(S): Manufacturer = Synology
Property(S): PIDTemplate = 12345<###-%%%%%%%>@@@@@
Property(S): PROMPTROLLBACKCOST = P
Property(S): ProductLanguage = 1033
Property(S): Progress1 = Installing
Property(S): Progress2 = installs
Property(S): REGSVR32 = [SystemFolder]\regsvr32
Property(S): RemoveIcon = removico
Property(S): RepairIcon = repairic
Property(S): SecureCustomProperties = UPGRADEFOUND;NEWPRODUCTFOUND
Property(S): Setup = Setup
Property(S): ShowUserRegistrationDlg = 0
Property(S): Wizard = Setup Wizard
Property(S): welcomdialogpng = testbmp
Property(S): VersionNT = 603
Property(S): WINDOWS_RELEASE_ID = 0
Property(S): INSTALLER_TYPE = msi
Property(S): BACKUP_INSTALLER_TYPE = no_backup
Property(S): VersionNT64 = 603
Property(S): INSTALLER_ARCH = x64
Property(S): ProductVersion = 7.5.0.16084
Property(S): ProductName = Synology Drive Client
Property(S): CONFIGPATH = empty
Property(S): DesktopFolder = C:\Users\Public\Desktop\
Property(S): ProgramFiles64Folder = C:\Program Files\
Property(S): ProgramMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\
Property(S): MsiLogFileLocation = C:\Users\WDAGUtilityAccount\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Synology.DriveClient.7.5.0.16084-2024-04-22-16-00-38.865.log
Property(S): PackageCode = {10E4D9CA-9ABC-41DF-B4CE-D18D574A3E52}
Property(S): ProductState = -1
Property(S): PackagecodeChanging = 1
Property(S): REBOOTPROMPT = S
Property(S): REBOOT = ReallySuppress
Property(S): CURRENTDIRECTORY = C:\Users\WDAGUtilityAccount
Property(S): CLIENTUILEVEL = 2
Property(S): CLIENTPROCESSID = 5496
Property(S): MsiRestartManagerSessionKey = da09fb9e07dd0840bfd968ca58ff96b4
Property(S): VersionDatabase = 200
Property(S): VersionMsi = 5.00
Property(S): WindowsBuild = 9600
Property(S): ServicePackLevel = 0
Property(S): ServicePackLevelMinor = 0
Property(S): MsiNTProductType = 1
Property(S): WindowsFolder = C:\Windows\
Property(S): WindowsVolume = C:\
Property(S): System64Folder = C:\Windows\system32\
Property(S): SystemFolder = C:\Windows\SysWOW64\
Property(S): RemoteAdminTS = 1
Property(S): TempFolder = C:\Users\WDAGUT~1\AppData\Local\Temp\
Property(S): ProgramFilesFolder = C:\Program Files (x86)\
Property(S): CommonFilesFolder = C:\Program Files (x86)\Common Files\
Property(S): CommonFiles64Folder = C:\Program Files\Common Files\
Property(S): AppDataFolder = C:\Users\WDAGUtilityAccount\AppData\Roaming\
Property(S): FavoritesFolder = C:\Users\WDAGUtilityAccount\Favorites\
Property(S): NetHoodFolder = C:\Users\WDAGUtilityAccount\AppData\Roaming\Microsoft\Windows\Network Shortcuts\
Property(S): PersonalFolder = C:\Users\WDAGUtilityAccount\Documents\
Property(S): PrintHoodFolder = C:\Users\WDAGUtilityAccount\AppData\Roaming\Microsoft\Windows\Printer Shortcuts\
Property(S): RecentFolder = C:\Users\WDAGUtilityAccount\AppData\Roaming\Microsoft\Windows\Recent\
Property(S): SendToFolder = C:\Users\WDAGUtilityAccount\AppData\Roaming\Microsoft\Windows\SendTo\
Property(S): TemplateFolder = C:\ProgramData\Microsoft\Windows\Templates\
Property(S): CommonAppDataFolder = C:\ProgramData\
Property(S): LocalAppDataFolder = C:\Users\WDAGUtilityAccount\AppData\Local\
Property(S): MyPicturesFolder = C:\Users\WDAGUtilityAccount\Pictures\
Property(S): AdminToolsFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Administrative Tools\
Property(S): StartupFolder = C:\ProgramData\Microsoft\Windows\Start Menu\Programs\Startup\
Property(S): StartMenuFolder = C:\ProgramData\Microsoft\Windows\Start Menu\
Property(S): FontsFolder = C:\Windows\Fonts\
Property(S): GPTSupport = 1
Property(S): OLEAdvtSupport = 1
Property(S): ShellAdvtSupport = 1
Property(S): MsiAMD64 = 6
Property(S): Msix64 = 6
Property(S): Intel = 6
Property(S): PhysicalMemory = 4095
Property(S): VirtualMemory = 4095
Property(S): AdminUser = 1
Property(S): MsiTrueAdminUser = 1
Property(S): LogonUser = WDAGUtilityAccount
Property(S): UserSID = S-1-5-21-2047949552-857980807-821054962-504
Property(S): UserLanguageID = 1033
Property(S): ComputerName = 96CEB24C-F3A7-4
Property(S): SystemLanguageID = 1033
Property(S): ScreenX = 1024
Property(S): ScreenY = 768
Property(S): CaptionHeight = 23
Property(S): BorderTop = 1
Property(S): BorderSide = 1
Property(S): TextHeight = 16
Property(S): TextInternalLeading = 3
Property(S): ColorBits = 32
Property(S): TTCSupport = 1
Property(S): Time = 16:00:40
Property(S): Date = 4/22/2024
Property(S): MsiNetAssemblySupport = 4.8.9032.0
Property(S): MsiWin32AssemblySupport = 6.3.22621.2506
Property(S): RedirectedDllSupport = 2
Property(S): MsiRunningElevated = 1
Property(S): Privileged = 1
Property(S): DATABASE = C:\Windows\Installer\14ed45.msi
Property(S): OriginalDatabase = C:\Users\WDAGUT~1\AppData\Local\Temp\WinGet\Synology.DriveClient.7.5.0.16084\Synology%20Drive%20Client-3.5.0-16084-x64.msi
Property(S): UILevel = 3
Property(S): MsiUIProgressOnly = 1
Property(S): MsiUIHideCancel = 1
Property(S): ACTION = INSTALL
MSI (s) (EC:9C) [16:00:40:231]: Product: Synology Drive Client -- Installation failed.

MSI (s) (EC:9C) [16:00:40:231]: Windows Installer installed the product. Product Name: Synology Drive Client. Product Version: 7.5.0.16084. Product Language: 1033. Manufacturer: Synology. Installation success or error status: 1603.

=== Logging stopped: 4/22/2024  16:00:40 ===

```
</details> 

Why can't my winget package updates ever be easy 😞

**Comment by s-crypt** [comment]
Running the installer manually has no issues on either Windows 10 or 11. I am not sure why the unattended install has issues with the OS version.

**Comment by PckgrTom** [comment]
image

**Comment by s-crypt** [comment]
Is there any reason an automated install would not work but a manual install would considering the information in the installer only says windows 10?

**Comment by PckgrTom** [comment]
> d install would not work but a manual install would considering the information in the installer only says windows 10?

I think the 64bit does not have a silent install switch yet.

**Comment by s-crypt** [comment]
Interesting, thanks for your input. I will reach out to Synology and see if they can resolve this issue.

Thanks again for your help, I still learning program packing and installing and somehow every program I use has a nonstandard installer.

**Pull request closed without merging**
