### PR TITLE
New package: Nox.NoxPlayer version 7.0.5.8

### LINKED ISSUE #78464: [Package Request]: add Noxplayer
### Package Requested

- [X] I would like someone else to build the manifest.
- [ ] I would like help so I can submit the manifest.
- [X] I have performed a search and couldn't find this package.
- [X] I have checked that the installer for this package is not contained in a .zip file
- [X] I think there is a new version available and I have provided the URL.

### Please provide the following information

Publisher: Bignox
Publisher Url: https://www.bignox.com/
Package Name: Bignox.Noxplayer
Description: An Android emulator to play mobile games on PC.
Package Version: 7.0.35
Installer URL: https://res06.bignox.com/full/20220902/7d37168d3750455da2a7fda06f7026fd.exe?filename=nox_setup_v7.0.3.5_full_intl.exe

Current Package Identifier (for new versions): 
https://res06.bignox.com/full/20220902/7d37168d3750455da2a7fda06f7026fd.exe?filename=nox_setup_v7.0.3.5_full_intl.exe

### PR DESCRIPTION
**Pull request by SpecterShell**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

* Resolves #78464

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/111879&drop=dogfoodAlpha

### CODE REVIEW

**Comment by SpecterShell** [comment]
The hardware issue should have been resolved.

**Comment by stephengillie** [comment]
This package causes the Manual Validation pipeline VMs to freeze.

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
> This package causes the Manual Validation pipeline VMs to freeze.

image

This situation is unchanged. I've tried with 16 GB of RAM and it still gives both the message about insufficient RAM and also freezes during the Defender scan.

**Comment by SpecterShell** [comment]
It is incompatible with Hyper-V and also caused both my Hyper-V VM and Windows Sandbox freezing without any warning messages when I ran it inside, maybe because it uses some hardware tricks for emulating? (And it is also incompatible with Core Isolation)

**Comment by stephengillie** [comment]
image
 
* https://github.com/microsoft/winget-pkgs/issues/107639

**Pull request closed without merging**
