### PR TITLE
New package: Stardock.Curtains version 1.19

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Resolves #26681

```
PS C:\Users\Esco> winget install -m M:\s\Stardock\Curtains\1.19\
Found Stardock Curtains [Stardock.Curtains]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://cdn.stardock.us/downloads/public/software/curtains/Curtains_setup.exe
  ██████████████████████████████  35.0 MB / 35.0 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

image

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/26690)

### CODE REVIEW

**Comment by BajajAditya123** [comment]
why do you stole mine package?!?!?!?

**Comment by OfficialEsco** [comment]
Because this is actually working.

**Review by ImJoakim — DISMISSED** [review]

**Comment by ImJoakim** [comment]
🤔

**Comment by ImJoakim** [comment]
This is on a x86 VM:

image

x64 Sandbox:

image

**Comment by OfficialEsco** [comment]
mmmm, never trust a scuffed Manifest

**Review by ItzLevvie — APPROVED** [review]

**Comment by BajajAditya123** [comment]
how to get moderation-approved label??

**Comment by BajajAditya123** [comment]
#27921

**Comment by BajajAditya123** [comment]
#27921

**Comment by ItzLevvie** [comment]
> how to get moderation-approved label?? in my approved manifest #27921

You'll have to wait for a Community Moderator to review your PR so it can be merged.

**Comment by BajajAditya123** [comment]
i cloased that one now it is #27970

**Comment by BajajAditya123** [comment]
@OfficialEsco Please review my changes in #27970

**Pull request merged**
