### PR TITLE
New version: Posit.rig version 0.6.0

### PR DESCRIPTION
**Pull request by eitsupi**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/118562)

### CODE REVIEW

**Comment by gaborcsardi** [comment]
FWIW: https://www.virustotal.com/gui/file/8b75b5a912800e3d0c2ef2470d7633cd8c329d2cf5451c9f8f98dc3a965a6b8e/detection
seems pretty clean.

**Comment by gaborcsardi** [comment]
Pretty clean here as well: https://opentip.kaspersky.com/8B75B5A912800E3D0C2EF2470D7633CD8C329D2CF5451C9F8F98DC3A965A6B8E/results?tab=upload

**Comment by gaborcsardi** [comment]
@stephengillie Can we help with anything do move this along? Thanks!

**Review by stephengillie — APPROVED** [review]

**Comment by eitsupi** [comment]
Thanks for merging!

**Comment by gaborcsardi** [comment]
> Our https://github.com/microsoft/winget-pkgs/issues/15674#issue-908889039 are community volunteers, please be patient and allow them sufficient time to review your submission.

I am sorry if my [message](https://github.com/microsoft/winget-pkgs/pull/118562#issuecomment-1708394690) seemed like I was urging you, that was not my intention at all. I wrote it because the PR had a "Needs-Author-Feedback" label, but I wasn't sure what feedback was needed from us.

**Pull request merged**
