### PR TITLE
New version: GitTools.GitVersion version 6.0.1

### PR DESCRIPTION
**Pull request by arturcic**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/166381)

### CODE REVIEW

**Comment by arturcic** [comment]
It needs manual validation due to Git dependency - see https://github.com/microsoft/winget-pkgs/pull/164102#issuecomment-2248359077

**Comment by arturcic** [comment]
@stephengillie can you check this one as well? same issue as with the previous release.

In the next release we removed the dependency on `Git` executable as it was used only in couple of places that are not critical to the tool

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-08-06 09:34:52.282 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFD4A20C11F: (caller: 00007FFD49F98D6F) LogHr(1) tid(1528) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFD4A112B08: (caller: 00007FFD4A1BBC20) Exception(1) tid(1528) 8A15005E ] 
> 2024-08-06 09:35:02.943 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFD2F8AC11F: (caller: 00007FFD2F638D6F) LogHr(1) tid(b18) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFD2F7B2B08: (caller: 00007FFD2F85BC20) Exception(1) tid(b18) 8A15005E ] 
> 2024-08-06 09:36:29.796 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.1/gitversion-win-x64-6.0.1.zip Result: 0x80004005
> 2024-08-06 09:35:19.742   Function name: GetLastError
> 2024-08-06 09:35:52.992   Creating directory: C:\Program Files\Git\usr\share\perl5\core_perl\autodie\exception
> 2024-08-06 09:35:55.757   Creating directory: C:\Program Files\Git\usr\share\perl5\vendor_perl\Error
> 2024-08-06 10:15:57.590 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!6816535B: (caller: 68061A80) LogHr(1) tid(1060) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!681AB5DD: (caller: 682412BF) Exception(1) tid(1060) 8A15005E ] 
> 2024-08-06 10:16:09.719 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!54FF535B: (caller: 54EF1A80) LogHr(1) tid(1aac) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!5503B5DD: (caller: 550D12BF) Exception(1) tid(1aac) 8A15005E ] 
> 2024-08-06 10:17:54.380 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.1/gitversion-win-arm64-6.0.1.zip Result: 0x80004005
> 2024-08-06 10:16:23.883   Function name: GetLastError
> 2024-08-06 10:16:57.059   Creating directory: C:\Program Files\Git\usr\share\perl5\core_perl\autodie\exception
> 2024-08-06 10:16:59.993   Creating directory: C:\Program Files\Git\usr\share\perl5\vendor_perl\Error

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 8A15005E may mean APPINSTALLER_CLI_ERROR_PINNED_CERTIFICATE_MISMATCH - The server certificate did not match any of the expected values.

Automated error analysis suggests 1653 may mean `ERROR_FAIL_FAST_EXCEPTION` - A fail fast exception occurred. Exception handlers will not be invoked and the process will be terminated immediately.

(Automated response - build 887.)

**Comment by arturcic** [comment]
@stephengillie is this the same issue as with the previous version when you said because it depends in Git, it requires manual verification?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-08-08 15:16:46.226 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFFCE39C11F: (caller: 00007FFFCE128D6F) LogHr(1) tid(ff4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFFCE2A2B08: (caller: 00007FFFCE34BC20) Exception(1) tid(ff4) 8A15005E ] 
> 2024-08-08 15:16:54.192 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFFB7F9C11F: (caller: 00007FFFB7D28D6F) LogHr(1) tid(cd4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFFB7EA2B08: (caller: 00007FFFB7F4BC20) Exception(1) tid(cd4) 8A15005E ] 
> 2024-08-08 15:18:01.386 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.1/gitversion-win-x64-6.0.1.zip Result: 0x80004005
> 2024-08-08 15:17:06.235   Function name: GetLastError
> 2024-08-08 15:17:28.610   Creating directory: C:\Program Files\Git\usr\share\perl5\core_perl\autodie\exception
> 2024-08-08 15:17:30.750   Creating directory: C:\Program Files\Git\usr\share\perl5\vendor_perl\Error
> 2024-08-08 15:16:43.269 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!69EC535B: (caller: 69DC1A80) LogHr(1) tid(1e70) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!69F0B5DD: (caller: 69FA12BF) Exception(1) tid(1e70) 8A15005E ] 
> 2024-08-08 15:16:50.937 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!557E535B: (caller: 556E1A80) LogHr(1) tid(920) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!5582B5DD: (caller: 558C12BF) Exception(1) tid(920) 8A15005E ] 
> 2024-08-08 15:18:06.485 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.1/gitversion-win-arm64-6.0.1.zip Result: 0x80004005
> 2024-08-08 15:17:03.408   Function name: GetLastError
> 2024-08-08 15:17:24.142   Creating directory: C:\Program Files\Git\usr\share\perl5\core_perl\autodie\exception
> 2024-08-08 15:17:26.033   Creating directory: C:\Program Files\Git\usr\share\perl5\vendor_perl\Error

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 8A15005E may mean APPINSTALLER_CLI_ERROR_PINNED_CERTIFICATE_MISMATCH - The server certificate did not match any of the expected values.

(Automated response - build 887.)

**Comment by arturcic** [comment]
It can be installed locally:

image

image

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-08-13 08:06:59.166 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFA25E2C11F: (caller: 00007FFA25BB8D6F) LogHr(1) tid(1874) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFA25D32B08: (caller: 00007FFA25DDBC20) Exception(1) tid(1874) 8A15005E ] 
> 2024-08-13 08:07:11.934 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFA08ADC11F: (caller: 00007FFA08868D6F) LogHr(1) tid(1f04) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFA089E2B08: (caller: 00007FFA08A8BC20) Exception(1) tid(1f04) 8A15005E ] 
> 2024-08-13 08:09:07.857 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.1/gitversion-win-x64-6.0.1.zip Result: 0x80004005
> 2024-08-13 08:07:29.444   Function name: GetLastError
> 2024-08-13 08:08:06.397   Creating directory: C:\Program Files\Git\usr\share\perl5\core_perl\autodie\exception
> 2024-08-13 08:08:09.881   Creating directory: C:\Program Files\Git\usr\share\perl5\vendor_perl\Error
> 2024-08-13 07:32:10.525 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!67DF535B: (caller: 67CF1A80) LogHr(1) tid(1ef0) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!67E3B5DD: (caller: 67ED12BF) Exception(1) tid(1ef0) 8A15005E ] 
> 2024-08-13 07:32:18.897 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!5439535B: (caller: 54291A80) LogHr(1) tid(9a8) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!543DB5DD: (caller: 544712BF) Exception(1) tid(9a8) 8A15005E ] 
> 2024-08-13 07:33:43.693 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.1/gitversion-win-arm64-6.0.1.zip Result: 0x80004005
> 2024-08-13 07:32:32.283   Function name: GetLastError
> 2024-08-13 07:32:56.674   Creating directory: C:\Program Files\Git\usr\share\perl5\core_perl\autodie\exception
> 2024-08-13 07:32:58.971   Creating directory: C:\Program Files\Git\usr\share\perl5\vendor_perl\Error

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 8A15005E may mean APPINSTALLER_CLI_ERROR_PINNED_CERTIFICATE_MISMATCH - The server certificate did not match any of the expected values.

(Automated response - build 887.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-08-14 14:51:29.180 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.1/gitversion-win-x64-6.0.1.zip Result: 0x80004005 
> 2024-08-14 14:47:28.484   Function name: GetLastError 
> 2024-08-14 14:47:32.093   Dest filename: C:\Program Files\Git\mingw64\lib\tk8.6\bgerror.tcl 
> 2024-08-14 14:47:33.124   Dest filename: C:\Program Files\Git\mingw64\share\doc\git-doc\technical\api-error-handling.html 
> 2024-08-14 14:47:33.327   Dest filename: C:\Program Files\Git\mingw64\share\git-gui\lib\error.tcl 
> 2024-08-14 14:47:33.421   Dest filename: C:\Program Files\Git\mingw64\share\perl5\FromCPAN\Error.pm 
> 2024-08-14 14:47:33.437   Dest filename: C:\Program Files\Git\mingw64\share\perl5\Git\LoadCPAN\Error.pm 
> 2024-08-14 14:47:33.952   Dest filename: C:\Program Files\Git\usr\bin\gpg-error.exe 
> 2024-08-14 14:47:34.718   Dest filename: C:\Program Files\Git\usr\bin\msys-gpg-error-0.dll 
> 2024-08-14 14:47:37.327   Dest filename: C:\Program Files\Git\usr\share\perl5\core_perl\Test2\EventFacet\Error.pm 
> 2024-08-14 14:47:38.155   Dest filename: C:\Program Files\Git\usr\share\perl5\vendor_perl\Error.pm 
> 2024-08-14 14:47:38.155   Dest filename: C:\Program Files\Git\usr\share\perl5\vendor_perl\Error\Simple.pm 
> 2024-08-14 14:47:38.155   Creating directory: C:\Program Files\Git\usr\share\perl5\vendor_perl\Error

(Automated response - build 887.)

**Comment by arturcic** [comment]
@stephengillie tested in VirusTotal https://www.virustotal.com/gui/url/dd78a533359e3d5c77aa32fbd0191d4f7c6bc0651e44b97508a49db1fec874a6?nocache=1

No viruses

image

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-08-16 05:17:39.413 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFD4A03C11F: (caller: 00007FFD49DC8D6F) LogHr(1) tid(1700) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFD49F42B08: (caller: 00007FFD49FEBC20) Exception(1) tid(1700) 8A15005E ] 
> 2024-08-16 05:17:46.751 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFD3221C11F: (caller: 00007FFD31FA8D6F) LogHr(1) tid(f50) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFD32122B08: (caller: 00007FFD321CBC20) Exception(1) tid(f50) 8A15005E ] 
> 2024-08-16 05:18:53.125 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.1/gitversion-win-x64-6.0.1.zip Result: 0x80004005
> 2024-08-16 05:17:58.798   Function name: GetLastError
> 2024-08-16 05:18:21.235   Creating directory: C:\Program Files\Git\usr\share\perl5\core_perl\autodie\exception
> 2024-08-16 05:18:23.266   Creating directory: C:\Program Files\Git\usr\share\perl5\vendor_perl\Error
> 2024-08-16 05:17:22.640 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!68C6535B: (caller: 68B61A80) LogHr(1) tid(3c8) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!68CAB5DD: (caller: 68D412BF) Exception(1) tid(3c8) 8A15005E ] 
> 2024-08-16 05:17:31.736 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!550B535B: (caller: 54FB1A80) LogHr(1) tid(ef0) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!550FB5DD: (caller: 551912BF) Exception(1) tid(ef0) 8A15005E ] 
> 2024-08-16 05:18:53.409 [FAIL] Installer failed security check. Url: https://github.com/GitTools/GitVersion/releases/download/6.0.1/gitversion-win-arm64-6.0.1.zip Result: 0x80004005
> 2024-08-16 05:17:42.785   Function name: GetLastError
> 2024-08-16 05:18:06.598   Creating directory: C:\Program Files\Git\usr\share\perl5\core_perl\autodie\exception
> 2024-08-16 05:18:09.051   Creating directory: C:\Program Files\Git\usr\share\perl5\vendor_perl\Error

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 8A15005E may mean APPINSTALLER_CLI_ERROR_PINNED_CERTIFICATE_MISMATCH - The server certificate did not match any of the expected values.

(Automated response - build 887.)

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
