### PR TITLE
aie 0.10.0

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/8452)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
image

**Comment by oxygen-dioxide** [comment]
This app installs and works fine on my pc (winget v0.2.10191)
Is this error happening during installing or the first launching after installation?

**Comment by oxygen-dioxide** [comment]
This app installs and works fine on my pc (winget v0.2.10191)
Is this error happening during installing or the first launching after installation?

**Comment by KevinLaMS** [comment]
i will retry

**Pull request merged**
