### PR TITLE
GlobalMarineNet.DfW version 1.0

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/107500)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by upintheairsheep** [comment]
> Automatic Validation ended with: image

Try common flags and what the help flag gives you first.

**Comment by Trenly** [comment]
> Try common flags and what the help flag gives you first.

Can you please provide the silent flag? It takes time away from reviewing and fixing other PRs to test the many different combinations of flags, and it is your responsibility as the manifest author to provide the correct metadata and installer switches. We are happy to help when we are able, but it is extremely frustrating when multiple PRs fail for the same reason and we are asked to fix them all.

**Comment by upintheairsheep** [comment]
> > Try common flags and what the help flag gives you first.
> 
> Can you please provide the silent flag? It takes time away from reviewing and fixing other PRs to test the many different combinations of flags, and it is your responsibility as the manifest author to provide the correct metadata and installer switches. We are happy to help when we are able, but it is extremely frustrating when multiple PRs fail for the same reason and we are asked to fix them all.

OK. I apologize.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
