### PR TITLE
New version: GitKraken.cli version 1.6.1

### PR DESCRIPTION
**Pull request by sergiolms**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/144290)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @sergiolms,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-14 03:09:20.089 [FAIL] Installer failed security check. Url: https://github.com/gitkraken/gk-cli/releases/download/v1.6.1/gk_1.6.1_Windows_i386.zip Result: 0x80004005

(Automated response - build 870.)

**Comment by JBUinfo** [comment]
Hi @stephengillie !
Sorry for the inconvenience, we had a false positive with windows defender but it has been fixed. Could you relaunch the tests?

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
