### PR TITLE
nepnep.neofetch-win version v1.0.0

### PR DESCRIPTION
**Pull request by nepnep39**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/97866)

### CODE REVIEW

**Comment by nepnep39** [comment]
@microsoft-github-policy-service agree

**Comment by Trenly** [comment]
This package errors when installing due to a dependency on MSVCP140.dll, which I presume if one of the Visual C++ redistributables

**Comment by Trenly** [comment]
[Policy] dependencies

**Comment by nepnep39** [comment]
going to fix that right away, working on a .msi installer

**Pull request closed without merging**
