### PR TITLE
New version: ImageMagick.ImageMagick.Q8 version 7.1.1.36

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#6901](https://github.com/SpecterShell/Dumplings/actions/runs/10123767478).

<details>

<summary>Log</summary>

````
Updated: 7.1.1.35 → 7.1.1.36
No ReleaseTime and ReleaseNotes (en-US) for version 7.1.1.36
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
The manifests for the last version 7.1.1.35 will be removed. Reason: This task is configured to remove the last version
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164937)

### CODE REVIEW

**Comment by SpecterShell** [comment]
@stephengillie Could you approve this PR?

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Comment by stephengillie** [comment]
Sorry for so much trouble with these.

**Pull request merged**
