### PR TITLE
Add manifest file for Vagrant v2.2.9

### PR DESCRIPTION
**Pull request by ifurther**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3033)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
azp /run

**Comment by KevinLaMS** [comment]
the path of the file is manifests/Vagrant/2.2.9.yaml
it needs to be manifests/Hashicorp/Vagrant/2.2.9.yaml

**Comment by KevinLaMS** [comment]
This installer automatically reboots.  We need to specify no reboot using the custom switch if possible.

**Comment by ifurther** [comment]
I added it.

**Comment by KevinLaMS** [comment]
image

**Comment by KevinLaMS** [comment]
Strange. I am still seeing a failure.  Thoughts?
image

**Comment by floh96** [comment]
@KevinLaMS Error Code 3010 means the installation was successfull but needs an restart. See [Docs](https://docs.microsoft.com/en-us/windows/win32/msi/error-codes).
See also [Chocolatey Install Script](https://github.com/chocolatey-community/chocolatey-coreteampackages/blob/master/automatic/vagrant/tools/chocolateyinstall.ps1) exit code 1641 is also possible.
Is it possible to add 3010 and 1641 as valid exit codes for the package?

**Comment by ifurther** [comment]
@floh96 I have tried already. But the `silentArgs' doesn't work for winget ymal file.

**Comment by geant44** [comment]
Maybe should wait winget-cli add function for #296

**Comment by KevinLaMS** [comment]
image
Still waiting on support for additional error codes

**Comment by KevinLaMS** [comment]
image
Interesting.  I will see if i can repro.

**Comment by KevinLaMS** [comment]
I am not able to install.  Both admin and non admin fail.
image

**Pull request closed without merging**
