### PR TITLE
New version: astral-sh.uv version 0.5.2

### LINKED ISSUE #191661: [Update Request]: astral-sh.uv version 0.5.2
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

astral-sh.uv

### Package Version

0.5.2

### Please describe the changes you would like to see

There's a new stable release `v0.5.2` available.

| Property          | Value                                                                                                                                                                                                                         |
| :---------------- | :---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| Release Notes URL | <https://github.com/astral-sh/uv/releases/tag/0.5.2>                                                                                                                                                                          |
| Installer URL     | [`i686`](https://github.com/astral-sh/uv/releases/download/0.5.2/uv-i686-pc-windows-msvc.zip) \| [`amd64`](https://github.com/astral-sh/uv/releases/download/0.5.2/uv-x86_64-pc-windows-msvc.zip) |

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #191661 

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

## Manual validation

Image
Image

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/191664)

### CODE REVIEW

**Comment by Dragon1573** [comment]
> The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.
> 
> Template: msftbot/validationError/installation/general

Why is that? I've tested in _Windows Sandbox_ without anything wrong. 😕

- See https://github.com/microsoft/winget-pkgs/pull/191664#issue-2660490646

**Comment by KarbitsCode** [comment]
There is a previous attempt updating this package: #190127
Not sure if this is related.

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-11-14 18:02:19.096 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/uv/releases/download/0.5.2/uv-i686-pc-windows-msvc.zip Result: 0x80004005
> MSI (s) (BC:D4) [18:02:10:084]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (BC:D4) [18:02:10:084]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (BC:D4) [18:02:10:084]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (BC:D4) [18:02:10:084]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (BC:D4) [18:02:10:084]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> Property(S): OutOfDiskSpace = 0
> Property(S): OutOfNoRbDiskSpace = 0
> Property(S): PrimaryVolumeSpaceAvailable = 0
> Property(S): PrimaryVolumeSpaceRequired = 0
> Property(S): PrimaryVolumeSpaceRemaining = 0
> MSI (s) (BC:A8) [18:02:10:928]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (BC:A8) [18:02:10:928]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (BC:A8) [18:02:10:928]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (BC:A8) [18:02:10:928]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (BC:A8) [18:02:10:928]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Comment by Dragon1573** [comment]
> [!CAUTION]
>
> Close with reason: https://github.com/microsoft/winget-pkgs/labels/Validation-Defender-Error
>
> - Related astral-sh/uv#9144

**Pull request closed without merging**
