### PR TITLE
New package: MouseJ.MouseJ version 1.0.7.1

### PR DESCRIPTION
**Pull request by ForeverFloating**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/168255)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 887.)

**Comment by ForeverFloating** [comment]
According to the download page: http://www.mousej.org/download/
"MouseJ requires Windows .NET Framework 4.5 or later to run. The installer package includes this library."
Could this be causing the installation issue?

**Comment by stephengillie** [comment]
Hi @ForeverFloating,

A bug with my automation is that it can't post the screenshots it unzips, so these sit open on my laptop, waiting for me to connect them to a PR. I've done this above - are installer switches needed to complete the install silently?

**Comment by ForeverFloating** [comment]
> Hi @ForeverFloating,
> 
> A bug with my automation is that it can't post the screenshots it unzips, so these sit open on my laptop, waiting for me to connect them to a PR. I've done this above - are installer switches needed to complete the install silently?

My screenshot below shows what shows up when I pass the `-?` parameter to the executable file on the command line.
image

**Comment by stephengillie** [comment]
`/S /v/qn` is a common one for InstallShield. It will need to be added.

**Pull request closed without merging**
