### PR TITLE
BrianMathis.WinHotKey version 0.70

### PR DESCRIPTION
**Pull request by zephiowl**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/29606)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
image

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> I don't know how the hash didn't match, I used wingetcreate for it, I'll update it manually when I can at home tomorrow.

This can happen when you're using a temporary link that's only valid for several hours or so; realistically, the link you used is now expired, so it's downloading a HTML file rather than a EXE file.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> Ahh I see, I'm not sure how I would go about getting the direct download, there doesn't seem to be much of an official source online. And I don't think it'd be a good idea so host the download myself. Any suggestions?

The best way would be to contact the developer if you have their contact details to publish the application to GitHub Releases, otherwise, I don't think there's much that can be done.

**Comment by Xanthus58** [comment]
Alrighty sounds good I'll try to get in contact if possible, I'm gonna close this pull request. With any luck I'll open another request in the near future. Thank you for your help!

**Pull request closed without merging**
