### PR TITLE
Add Kingdraw

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
Add Kingdraw

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/413)

### CODE REVIEW

**Comment by oxygen-dioxide** [comment]
image
https://www.microsoft.com/en-us/wdsi/submission/a3c88c62-f540-4d4a-b89f-e1f42c318754

**Comment by KevinLaMS** [comment]
I got this through the smartscreen errors, but I am not seeing any files get installed with this app.

**Comment by oxygen-dioxide** [comment]
The default installation destination is "D:\KingDraw\". Do you have D:\? Or can I use command line arguments to change the installation destination? The installer type is nullsoft.

**Comment by denelon** [comment]
@oxygen-dioxide this is an older PR :smile:

Has anything changed with this package?

Do you want to convert the manifest and trigger another build or close this?

**Pull request closed without merging**
