### PR TITLE
Add script to ensure unique DisplayVersions

### PR DESCRIPTION
**Pull request by Trenly**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

One of the reasons the publishing pipeline failed recently was due to some packages having overlapping DisplayVersion. While this overlap should have been caught by the pipelines and prevented, somehow they slipped through.

This script will iterate through the entirety of the manifests folder on a local machine and fetch the manifests that have DisplayVersion specified. Using this, for each package that specifies a DisplayVersion, it will create a list of all the DisplayVersions aggregated from each package version. This is filtered for uniqueness and compared to itself. If they are equal, there is no overlap. If they are not equal, there is an overlap.

The script will return either a list of identifiers and the overlapping DisplayVersions, along with the PackageVersions that the errors were found in; or null if there are no overlaps
The script will have an exit code of 1 if there were overlaps found, or 0 if no overlaps

image

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/180721)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
[Policy] Needs Manual Merge

@denelon / @stephengillie

**Review by denelon — APPROVED** [review]

**Comment by stephengillie** [comment]
Just out of curiosity: Is there a way to make this work without having a local copy of the repo? 
- WIth a local copy, the script is just incurring disk calls, and this becomes basically a database query for an oddly-collated database. 
- WIthout the local copy, web API calls and responses are needed.

**Comment by Trenly** [comment]
I'm sure there is, but given that the repo is only expected to grow, the only other way would be to download the indexV1, extract it, and run complex SQL queries against it. This wouldn’t be possible with indexV2 either.

**Pull request merged**
