### PR TITLE
Permission: DuckStudio.FufuTools should be reviewed before merging

### PR DESCRIPTION
**Pull request by CoolPlayLin**
This should be merged after #157822 

CC @DuckDuckStudio @stephengillie 
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/157839)

### CODE REVIEW

**Comment by stephengillie** [comment]
HI @CoolPlayLin,

In which way should this package be reviewed before merging? Is the goal to prevent other users from adding new manifests? 

The Auth.csv "should" entry will indicate, but not block, when other users submit PRs for this `PackageIdentifier`. Changing to "must" will block PRs from other users from being approved. Is this the desired functionality?

**Comment by CoolPlayLin** [comment]
Hi @DuckDuckStudio

**Comment by DuckDuckStudio** [comment]
Reply @CoolPlayLin ,

> I'm sorry for the delayed response.

I'm not familiar with the Auth.csv file, but if it is used to determine whether other users can initiate a PR for this program, I believe it should be filled with 'should' or left unchanged. I think other people's PRs might be helpful for my program (as this is my first time submitting a package to winget, and there are many things I'm not familiar with).

**Comment by stephengillie** [comment]
I'll close this PR for now. If this is incorrect, or if things change later and this becomes requested, please @ me.

**Comment by DuckDuckStudio** [comment]
@CoolPlayLin 
Thanks for all your suggestions, I will create a new PR.

**Pull request closed without merging**
