### PR TITLE
New package: caarlos0.fork-cleaner 2.3.0

### PR DESCRIPTION
**Pull request by caarlos0**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/110633&drop=dogfoodAlpha

### CODE REVIEW

**Comment by caarlos0** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Hi @caarlos0,

Unfortunately, this package didn't pass a Defender scan:
image

Please check your systems and recompile. It's also possible this might be a false positive that clears later.

**Comment by caarlos0** [comment]
That's weird, will make sure all dependencies are up to date just in case, but I think this is a false positive 🤔

**Comment by stephengillie** [comment]
> That's weird, will make sure all dependencies are up to date just in case, but I think this is a false positive 🤔

I've rechecked and it was. This Defender scan passed. Thank you for your patience and understanding.

**Comment by stephengillie** [comment]
This package needs a GitHub token.
> missing github token

I'll give it a waiver when validation errors.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
