### PR TITLE
Unity.Unity.2021 version 2021.3.10f1

### PR DESCRIPTION
**Pull request by edson3279**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/82380)

### CODE REVIEW

**Review by vedantmgoyal9 — CHANGES_REQUESTED** [review]
Duplicate of https://github.com/microsoft/winget-pkgs/pull/82108

**Comment by edson3279** [comment]
@vedantmgoyal2009

No duplicate.

The version is 3.11f1 and this is 3.10f1

**Comment by vedantmgoyal2009** [comment]
@edson3279 sorry, btw, can you move the package identifier to Unity.Unity.2021 instead of [UnityTechnologiesApS.Unity2021.3.10f1](https://github.com/microsoft/winget-pkgs/pull/82380#top)

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
See https://github.com/microsoft/winget-pkgs/pull/82380#issuecomment-1266503496

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
