### PR TITLE
Remove: Unity.Unity.6000.WindowsIL2CPP version 6000.0.3f1

### PR DESCRIPTION
**Pull request by SpecterShell**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/186121)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @SpecterShell,

This package is still available. Why is it being removed?

**Review by ItzLevvie — APPROVED** [review]

**Comment by SpecterShell** [comment]
> Hi @SpecterShell,
> 
> This package is still available. Why is it being removed?

Already explained in the Gitter chat:

> Those are the target support packages not the main editor. They do not work without the exactly corresponding version of the main editor.
> Maintaining these packages is a bit annoying, and right now they have been fallen behind for several versions. I’ll merge them into one later.

**Comment by ItzLevvie** [comment]
[Policy] Needs-Manual-Merge

**Comment by stephengillie** [comment]
> Already explained in the Gitter chat:
> 
> > Those are the target support packages not the main editor. They do not work without the exactly corresponding version of the main editor.
> > Maintaining these packages is a bit annoying, and right now they have been fallen behind for several versions. I’ll merge them into one later.

I missed your comments there - thank you for reposting them here.

**Pull request merged**
