### PR TITLE
New version: Alibaba.DingTalk version 7.0.20-Release.4199103

### PR DESCRIPTION
**Pull request by SpecterShell**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/103058)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation failed with:
> Installation failed with exit code -1978335226 
> 2023-04-20 17:20:18.425 [CLI ] ShellExecute installer failed: 2

**Comment by stephengillie** [comment]
This installed normally in a VM.

**Comment by SpecterShell** [comment]
> This installed normally in a VM.

I guess this one is also caused by disk space issue like <https://github.com/microsoft/winget-pkgs/pull/103074#issuecomment-1518363088>.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
