### PR TITLE
New version: Mozilla.Firefox version 130.0

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#7812](https://github.com/SpecterShell/Dumplings/actions/runs/10683594405).

<details>

<summary>Log</summary>

````
Updated: 129.0.2 → 130.0
Submitting WinGet manifests
Found existing pull requests:
Update: Mozilla.Firefox.DeveloperEdition version 130.0 (130.0b9) - https://github.com/microsoft/winget-pkgs/pull/168871
Update: Mozilla.Firefox.DeveloperEdition version 130.0 (130.0b8) - https://github.com/microsoft/winget-pkgs/pull/168567
Update: Mozilla.Firefox.DeveloperEdition version 130.0 (130.0b7) - https://github.com/microsoft/winget-pkgs/pull/168261
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/171413)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://download-installer.cdn.mozilla.net/pub/firefox/releases/130.0/win32/en-US/Firefox%20Setup%20130.0.exe 
OK

(Automated message - build 920)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://download-installer.cdn.mozilla.net/pub/firefox/releases/130.0/win32/en-US/Firefox%20Setup%20130.0.exe 
OK

(Automated message - build 921)

**Comment by stephengillie** [comment]
The error is near the end of the log - starting at line 585:

> Installer https://download-installer.cdn.mozilla.net/pub/firefox/releases/130.0/win64/it/Firefox%20Setup%20130.0.exe
Scan request id: 'c719e7a5-04e5-46e3-bd8b-444c7899484e'
> 
> Installer https://download-installer.cdn.mozilla.net/pub/firefox/releases/130.0/win32/ka/Firefox%20Setup%20130.0.exe
Scan request id: '0cdcc98e-6b91-4a4d-8d76-1ba022e252be'
> 
> Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/130.0/win64-aarch64/pt-PT/Firefox%20Setup%20130.0.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-411-171413-20240912-2\2b288e77-f190-4f48-9774-8a1295288d00' because it is being used by another process..
Error information: 
Http Response: OK
Http Reason Phrase: OK
Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/130.0/win64-aarch64/ro/Firefox%20Setup%20130.0.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-411-171413-20240912-2\40b4a66b-e1e4-4af5-8386-c83aaad9e302' because it is being used by another process..
Error information: 
Http Response: OK
Http Reason Phrase: OK
Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/130.0/win64/fi/Firefox%20Setup%20130.0.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-411-171413-20240912-2\561366d0-4d73-42e3-8c02-c632fd8d34fe' because it is being used by another process..
Error information: 
Http Response: OK
Http Reason Phrase: OK
Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/130.0/win64-aarch64/de/Firefox%20Setup%20130.0.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-411-171413-20240912-2\5959d5cb-9cde-4bb1-9388-500888f402bc' because it is being used by another process..
Error information: 
Http Response: OK
Http Reason Phrase: OK
Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/130.0/win64-aarch64/et/Firefox%20Setup%20130.0.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-411-171413-20240912-2\5e3bcee2-e935-4946-96b7-b2212e49c5d1' because it is being used by another process..
Error information: 
Http Response: OK
Http Reason Phrase: OK
Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/130.0/win64/ms/Firefox%20Setup%20130.0.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-411-171413-20240912-2\7bc4dad5-9881-47c1-91b2-ed409dc41d1e' because it is being used by another process..
Error information: 
Http Response: OK
Http Reason Phrase: OK
Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/130.0/win32/ms/Firefox%20Setup%20130.0.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-411-171413-20240912-2\bdc625ed-1456-4d3e-8052-130fd4321910' because it is being used by another process..
Error information: 
Http Response: OK
Http Reason Phrase: OK
Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/130.0/win64-aarch64/ar/Firefox%20Setup%20130.0.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-411-171413-20240912-2\c51833ee-0169-4729-8aa4-e60a810dc042' because it is being used by another process..
Error information: 
Http Response: OK
Http Reason Phrase: OK
Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/130.0/win64/sk/Firefox%20Setup%20130.0.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-411-171413-20240912-2\d4279ad4-3cbc-4b6e-84ca-cc668df20db1' because it is being used by another process..
Error information: 
Http Response: OK
Http Reason Phrase: OK
Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/130.0/win32/is/Firefox%20Setup%20130.0.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-411-171413-20240912-2\d6dc125e-d312-4a47-831f-8e9d978d842f' because it is being used by another process..
Error information: 
Http Response: OK
Http Reason Phrase: OK
Error occurred while downloading installer from https://download-installer.cdn.mozilla.net/pub/firefox/releases/130.0/win64-aarch64/hu/Firefox%20Setup%20130.0.exe. The process cannot access the file 'C:\local\Temp\WinGetSvc-Validation-411-171413-20240912-2\f0a2245b-f592-42f0-93a3-8ee869edb0f5' because it is being used by another process..
Error information: 
Http Response: OK
Http Reason Phrase: OK

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
