### PR TITLE
ThePokemonCompany.PokemonTCGOnline version 2.94.0

### PR DESCRIPTION
**Pull request by solomoncyj**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/91441)

### CODE REVIEW

**Comment by solomoncyj** [comment]
???

**Comment by stephengillie** [comment]
The validation log is reporting that the manifest version is too new.
> ##[error] Manifest: The manifest version is not supported. Supported versions: 1.0.0,1.1.0,1.2.0.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
