### PR TITLE
Normalize DiegoFernandes.jsdesign 1.0.2

### PR DESCRIPTION
**Pull request by Trenly**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/73069)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Review by OfficialEsco — DISMISSED** [review]
```
Enter a pull request number: #73069

Manifest validation succeeded.
Found 即时设计 [DiegoFernandes.jsdesign] Version 1.0.4
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
An unexpected error occurred while executing the command:
No mapping for the Unicode character exists in the target multi-byte code page.
```

**Comment by Trenly** [comment]
@denelon - Blocking Issue

microsoft/winget-cli#2057

**Review by jedieaston — APPROVED** [review]

**Review by jedieaston — DISMISSED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
