### PR TITLE
New package: pnpm.pnpm version 7.9.0

### PR DESCRIPTION
**Pull request by russellbanks**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Correction and update of https://github.com/microsoft/winget-pkgs/pull/68438

It still seems to not recognise the command after restarting the shell:

https://user-images.githubusercontent.com/74878137/183264836-b3ef1dba-f929-43dd-97a4-05789e874eab.mp4

WindowsSandboxClient_4NG3VrMwfS

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/68904)

### CODE REVIEW

**Comment by russellbanks** [comment]
beep boop 1.2 manifest

**Comment by ItzLevvie** [comment]
> It still seems to not recognise the command after restarting the shell:

It works fine here on VMware Workstation Pro - maybe it's a Windows Sandbox issue?

image

image

Current Shell:
image

Restarting Shell:
image

**Review by ItzLevvie — APPROVED** [review]

**Comment by russellbanks** [comment]
> It works fine here on VMware Workstation Pro - maybe it's a Windows Sandbox issue?

Must be - thank you for testing it! :)

**Comment by russellbanks** [comment]
Replaced by #68910 because there are two pnpm channels that recieve updates: `pnpm 6` and `pnpm 7`.

**Pull request closed without merging**
