### PR TITLE
New version: Microsoft.OneDrive version 22.055.0313.0001

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/56970)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-pkgs/pull/55703#issuecomment-1086080516

**Review by jedieaston — APPROVED** [review]
image

Now that is a ProductCode.

**Comment by OfficialEsco** [comment]
@msftrubengu and one more that have been abandoned

**Pull request merged**
