### PR TITLE
Winget 0.1.41821

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
- [y] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [y] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [y] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [y] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2402)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
Deployment wants to shut down old winget to deploy new winget, deployment sends the old winget a ctrl-c signal, the old winget cancels all it’s doing(including the ongoing “install new winget”).

**Comment by JohnMcPMS** [comment]
I've created this issue for future use:
https://github.com/microsoft/winget-cli/issues/505

**Comment by vedantmgoyal2009** [comment]
@JohnMcPMS @KevinLaMS @denelon This PR can be closed as the version of the manifest being used is 0.1.0.

**Comment by denelon** [comment]
Once we have the ability to update ourselves, we will add the manifest automatically.

**Pull request closed without merging**
