### PR TITLE
Add Microsoft China CDN for Visual Studio Code 1.80.2

### PR DESCRIPTION
**Pull request by CoolPlayLin**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/113843&drop=dogfoodAlpha

- Related to #113844

### CODE REVIEW

**Comment by CoolPlayLin** [comment]
I haven't found the mirror in official VSC page, but this domain name is owned Microsoft China or its subcompany. According to this, We can be sure of is that this CDN or Mirror is being maintained by them.

**Comment by mdanish-kh** [comment]
The manifests are maintained by the VSCode Team and apparently they use hard-coded manifests for each update. Even if we include the URLs here, they'll probably get removed in a newer version. The actual fix would be for the VSCode Team to include these URLs in their automation.

cc @denelon @lszomoru

**Comment by CoolPlayLin** [comment]
cc @denelon @lszomoru @stephengillie

**Comment by stephengillie** [comment]
lszomoru will have the best advice here.

**Comment by CoolPlayLin** [comment]
CC @lszomoru

**Comment by CoolPlayLin** [comment]
We've sent notice for 2 days, but @lszomoru hasn't replied us now. What should I do except waiting? @stephengillie

**Comment by stephengillie** [comment]
Hi @CoolPlayLin,

Unfortunately we can't really accept these without lszomoru's approval. His team is using automation to create these manifests, so any changes we approve would be overwritten on their next update.

**Comment by denelon** [comment]
I've contacted @lszomoru internally via Teams to make sure the VSCode team is aware.

**Comment by CoolPlayLin** [comment]
> I've contacted @lszomoru internally via Teams to make sure the VSCode team is aware.

@denelon
Is there any other way to contact other member of VSCode Team?😊

**Comment by denelon** [comment]
@coolPlayLin the only other avenue I'm aware of is their GitHub project https://github.com/microsoft/vscode

**Comment by lszomoru** [comment]
Thank you very much for your contribution. I will look at making the necessary changes to our automation this week.

**Comment by CoolPlayLin** [comment]
@lszomoru
> Thank you very much for your contribution. I will look at making the necessary changes to our automation this week.

Thanks to make time in busy❤️

**Pull request closed without merging**
