### PR TITLE
Update D:\Git\winget-pkgs\manifests\d\Dogramming\Imaconverter\2.0

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114834&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
image

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
