### PR TITLE
New version: Canonical.Multipass version 1.14.1

### PR DESCRIPTION
**Pull request by Exorcism0666**
Created by [🥟 Dumplings](https://github.com/Exorcism0666/Dumplings) in workflow run [#4993](https://github.com/Exorcism0666/Dumplings/actions/runs/11383874644).

**Logs**
````
Updated: 1.14.0 → 1.14.1
Cannot validate argument on parameter 'ChatID'. The argument is null, empty, or consists of only white-space characters. Provide an argument that contains non white-space characters, and then try the command again.
Submitting WinGet manifests
Cannot validate argument on parameter 'ChatID'. The argument is null, empty, or consists of only white-space characters. Provide an argument that contains non white-space characters, and then try the command again.
````
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/183849)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by Trenly** [comment]
@stephengillie - ARP did not match, resulting in upgrade loop. Ref -
* https://github.com/microsoft/winget-cli/discussions/5047

**Comment by stephengillie** [comment]
> @stephengillie - ARP did not match, resulting in upgrade loop. Ref -
> 
> * [Winget and Canonical Multipass winget-cli#5047](https://github.com/microsoft/winget-cli/discussions/5047)

Assuming that not merging and validating in a VM are both not options, how could I have handled this PR in a way that did not result in the upgrade loop?

**Comment by Trenly** [comment]
> > @stephengillie - ARP did not match, resulting in upgrade loop. Ref -
> > 
> > * [Winget and Canonical Multipass winget-cli#5047](https://github.com/microsoft/winget-cli/discussions/5047)
> 
> Assuming that edit: ignoring the PR and validating in a VM are both not options, how could I have handled this PR in a way that did not result in the upgrade loop?

I wasn't aware that validating in a VM wasn't available?

**Comment by stephengillie** [comment]
Our volume has grown prohibitive.

**Pull request merged**
