### PR TITLE
New version: Deskflow.Deskflow version 1.17.2

### PR DESCRIPTION
**Pull request by nbolton**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/192630)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @nbolton,

Agreeing to the CLA is necessary for this PR to proceed. I'm not a lawyer, but my understanding is that these files are your (or your company's) property. And for us to be allowed to use these files - to host these in our repo, repackage them into a file for the package manager client to download, and otherwise manipulate and process - we need your agreement first. Which is what the CLA provides. Does this help?

**Comment by nbolton** [comment]
> Hi @nbolton,
> 
> Agreeing to the CLA is necessary for this PR to proceed. I'm not a lawyer, but my understanding is that these files are your (or your company's) property. And for us to be allowed to use these files - to host these in our repo, repackage them into a file for the package manager client to download, and otherwise manipulate and process - we need your agreement first. Which is what the CLA provides. Does this help?

Hi. Deskflow is GPLv2 and I am one of the copyright holders. Do you still need me to accept the CLA?
https://github.com/deskflow/deskflow/blob/master/LICENSE

**Comment by stephengillie** [comment]
Yes - this is regarding the YAML files that describe the software package, not the software package itself. 

If these YAML files are covered by the GPLv2 license, unfortunately we don't have a custom mechanism to bypass the CLA that I am aware of. The workarould would be agreeing to the CLA. 

Does this help?

**Comment by nbolton** [comment]
@microsoft-github-policy-service agree

**Pull request merged**
