### PR TITLE
New version: Unity.Unity.6000 version 6000.0.8f1

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#6207](https://github.com/SpecterShell/Dumplings/actions/runs/9717310629).

<details>

<summary>Log</summary>

````
Updated: 6000.0.7f1 → 6000.0.8f1
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/160574)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-06-28 22:59:59.630 [CLI ] ShellExecute installer failed: 2

Automated error analysis suggests -1978335226 may mean Install successful but system restart may be required.

(Automated response - build 886.)

**Review by ItzLevvie — APPROVED** [review]

**Comment by SpecterShell** [comment]
Hmm... This package needs manual validation.

**Comment by stephengillie** [comment]
The download is 2.59 GB.

image

The validation pipelines were recently found to have just 40 GB of storage drive space. I'm not sure if this has been increased since. Also not sure how much of that space is taken up by the OS and default applications - they might operate with less than 2 GB of free disk space, to meet other constraints.

**Comment by stephengillie** [comment]
> The download is 2.59 GB.
> 
> image
> 
> My manual validation VMs are downloaded from Hyper-V Quick Create and then have all updates run, so are very close to the base image. The OS and default applications take up ~22 GB. And the Automatic Validation VMs might have additional software to support SDL and similar services.
> 
> image
> 
> The validation pipelines were recently found to have just 40 GB of storage drive space. I'm not sure if this has been increased since. Also not sure how much of that space is taken up by the OS and default applications - they might operate with less than 2 GB of free disk space, to meet other constraints.

To follow up, I realized that I've been calling out either the installer, or the installed package. When really, it's both. Such as here, where the 2.59 GB installer, 6.5 GB installed package, and I'm guessing some errata or other small installed packages, sum to ~10 GB. 
image

To combine with above:
- Total pipeline VM storage "budget" is 40 GB
- The OS and default applications take up ~22 GB, leaving 18 GB.
- This package's installer and application take up ~10 GB, leaving as much as 8 GB, or as little as 6, depending on rounding.
- Not sure how much SDL/SFI required applications might take up. If more than 6-8 GB it's a problem.

**Pull request merged**
