### PR TITLE
Pangea CLI v1.1.1

### PR DESCRIPTION
**Pull request by pangea-andrest**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164559)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-07-25 07:47:47.455 [FAIL] Installer failed security check. Url: https://github.com/pangeacyber/pangea-cli/releases/download/v1.1.1/pangea-windows-386.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 887.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-07-26 13:14:56.312 [FAIL] Installer failed security check. Url: https://github.com/pangeacyber/pangea-cli/releases/download/v1.1.1/pangea-windows-amd64.exe Result: 0x80004005

(Automated response - build 886.)

**Comment by pangea-andrest** [comment]
@microsoft-github-policy-service agree company="PangeaCyber"

**Comment by stephengillie** [comment]
Verify:
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
