### PR TITLE
Create Mega Sync Installer

### PR DESCRIPTION
**Pull request by daljo25**
Create Mega Sync Installer

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/986)

### CODE REVIEW

**Comment by daljo25** [comment]
update hash

**Comment by daljo25** [comment]
update hash of installer

**Comment by LukasNespor** [comment]
Blocked by #91

**Comment by NathanBnm** [comment]
@daljo25 I already submitted a PR for MEGASync you should have looked for duplicates before opening this

**Comment by KevinLaMS** [comment]
Duplicate of #1620

**Pull request closed without merging**
