### PR TITLE
Add version: univrsal.input-overlay version 5.0.2

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/108644)

### CODE REVIEW

**Comment by stephengillie** [comment]
x86 Automatic Validation ended with:
image

x64 appears to have completed normally.

**Comment by Trenly** [comment]
> x64 appears to have completed normally.

I'm confused. Since the latest commit, I get this now
image

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by stephengillie** [comment]
Very confusing - it appears that the 64-bit installer can't run on 64-bit Windows. I'm unsure if they're expecting users to dual-boot 32-bit and 64-bit OSes, or install through another means:
image

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Closing PR as stale.

**Pull request closed without merging**
