### PR TITLE
Kiwix.KiwixJS version 2.0.9.0

### PR DESCRIPTION
**Pull request by Jaifroid**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/64990)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Jaifroid** [comment]
@ItzLevvie I rebuilt this app and signed it again, because validation was failing before. It's still failing, yet it installs fine locally (see screenshot below). I cannot find anything wrong with the package. I can only assume now that there is a problem in the winget validation pipeline. It wouldn't be the first time I've had this issue with appxbundle packages, and it has needed developer attention to resolve it. I believe the winget devs don't test regularly on appxbundles that contain HTML/JS UWP apps. Can this PR be flagged for developer attention, please?

image

**Comment by ItzLevvie** [comment]
Monday, 4th of July 2022 is a holiday in the United States so the WinGet engineering team will check back on Tuesday, 5th of July 2022.

cc @denelon: This pull request needs an engineer's attention.

**Comment by Trenly** [comment]
```
2022-07-05 09:32:09.365 [CORE] Deployment operation #0: error 0x800B0110: Opening the package from location KiwixWebApp_2.0.9.0_AnyCPU.appxbundle failed.
2022-07-05 09:32:09.367 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(159)\WindowsPackageManager.dll!00007FFECACF7684: (caller: 00007FFECAC895E5) Exception(1) tid(cec) 800B0110 The certificate is not valid for the requested usage.
```

**Comment by Jaifroid** [comment]
Installing on Windows 11, standard mode (not developer), the file referenced by the manifest is this one: https://github.com/kiwix/kiwix-js-windows/releases/download/v2.0.9/KiwixWebApp_2.0.9.0_AnyCPU.appxbundle 

Download it, double click it, app installer loads:

image

Installs correctly.

**Comment by Jaifroid** [comment]
Uninstall above install and now try using winget:

image

@Trenly could you kindly explain the steps necessary to reproduce the error you're seeing, because I can't see it locally in Windows 11, either with the package installer or with winget.

**Comment by Trenly** [comment]
> Windows 11, either with the package installer or with winget.

Clone the repo; Open powershell; CD to the folder and run `./Tools/PRTest.ps1 64990`

**Comment by Jaifroid** [comment]
I've just tested installation of the package on a friend's PC. Windows 11 Pro, not in developer mode. Her windows is Spanish language. Installs correctly, says "Kiwix JS is ready":

image

**Comment by Jaifroid** [comment]
But the package installs fine with winget. How can I find out what the "requested usage" is that the package is not valid for? Clearly it is valid for installation of the package, or winget would fail to install it.

**Comment by Trenly** [comment]
I found [this related issue](https://github.com/ViGEm/DsHidMini/issues/138#issuecomment-932545732)

I also found this image, showing how sometimes your system setup restricts the certificate -
image

This article on [Extended Key Usage](https://www.sysadmins.lv/blog-en/constraining-extended-key-usages-in-microsoft-windows.aspx) may also be helpful.

**Comment by Jaifroid** [comment]
Thank you very much @Trenly for the interesting research that may help to identify the issue as being a problem with Windows 11 keychain checking.

The thing is, no matter how much I adjust the certificate settings on my local machine, it will not change the fact that the error is manifesting in the PR validation script running on Azure, and that the error has manifested only this month when I [first submitted KiwixJS 2.0.9.0](https://github.com/microsoft/winget-pkgs/pull/64672) -- all the previous versions of Kiwix JS prior to July have validated fine, using the same certificate and build chain.

Having said that, the current package is built with our new org certificate (the previous one runs out end of August). New certificate, same error, only on the .appxbundle package. At the same time I (originally) submitted 2.0.9.0, I also submitted [an .exe Electron package](https://github.com/microsoft/winget-pkgs/pull/64673) built with the same (previous) certificate, which passed with no problems.

So: a certificate is valid when submitting an .exe package, but fails when submitting an .appxbundle. But the appxbundle installs fine with winget anyway. This suggests an inconsistency in the PR Testing script to me, though I'm happy to try to test other possibilities.

**Comment by Jaifroid** [comment]
@Trenly, @denelon Please find here (below) screenshot proof that the certificate on this appxbundle is correctly signed and timestamped. This, coupled with the fact that winget installs the manifest in this PR correctly when run locally against the manifest, shows that that the problem needs to be fixed on your side. There is an issue in your scripts that since last month is failing to verify correctly coded and signed appxbundles, whereas all my packages signed and timestamped in this way prior to the end of June passed verification correctly.

You can verify my screenshot by [downloading the referenced appxbundle in this manifest from GitHub](https://github.com/kiwix/kiwix-js-windows/releases/download/v2.0.9/KiwixWebApp_2.0.9.0_AnyCPU.appxbundle), and right clicking in Windows, choose Properties -> Digital Signatures -> select signature -> Details -> select signature -> Details. I verified this certificate many times, have uninstalled and installed the package many times, with winget and with the Windows appx/msix installer, with no error. I have rebuilt, signed and timestamped my package three times now. Windows confirms the package is correctly signed, and it installs correctly in everything _except_ the Azure verification script for winget. Thank you for your attention to this matter.

image

**Comment by AmelBawa-msft** [comment]
@Jaifroid Thank you for sharing the details above. I am working with the team to help investigate the issue.
CC: @hackean-msft @denelon

**Comment by Jaifroid** [comment]
@AmirMS Thank you for adding a waiver for this app. @ItzLevvie Would you be able to mark this as reviewed again, as merging is blocked?

**Review by ItzLevvie — APPROVED** [review]

**Comment by Jaifroid** [comment]
@denelon This has passed validation, has the required review, but the bot still thinks it is blocked due to missing review...

**Review by AmelBawa-msft — APPROVED** [review]
Manually approving since bot was not triggered post "validation-completed" label
CC: @denelon

**Pull request merged**
