### PR TITLE
​

### PR DESCRIPTION
**Pull request by ItzLevvie**
​

### CODE REVIEW

**Comment by KevinLaMS** [comment]
image

**Comment by ItzLevvie** [comment]
cc @KevinLaMS Installer requires Administrator privileges:
image

**Comment by ItzLevvie** [comment]
cc @KevinLaMS

**Comment by KevinLaMS** [comment]
This installer seems to reboot at completion.  I tried to see if I could suppress with --ignore-reboot, but it did not work. Thoughts?

**Comment by ItzLevvie** [comment]
> This installer seems to reboot at completion. I tried to see if I could suppress with --ignore-reboot, but it did not work. Thoughts?

@KevinLaMS Which build are you on? Just did another install today (4 Nov 2020) manually via winget and the installer didn't restart my VM.

image

If I remember correctly, the latest Insider build (not sure if it's fixed) seem to have some issues with virtualization softwares.

**Pull request merged**
