### PR TITLE
ArduinoSA.IDE version 1.8.16

### PR DESCRIPTION
**Pull request by kdpuvvadi**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/29721)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Blocked by driver software prompt:
image

**Comment by kdpuvvadi** [comment]
> Blocked by driver software prompt:
> image
> 

I'm trying to replicate this but for some reason it's not promting me to install the drivers. I've connected uni r3 to windows box and windows update installed the drivers. I, then uninstalled the drivers, rebooted and tried again, still not asking for me.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> I'm trying to replicate this but for some reason it's not promting me to install the drivers. I've connected uni r3 to windows box and windows update installed the drivers. I, then uninstalled the drivers, rebooted and tried again, still not asking for me.

I think if you uninstall the drivers, it'll still be in the Driver Store, but not sure. My screenshot was from a clean installation of Windows.

You can repro this by installing it on VirtualBox, VMware, or Windows Sandbox.

**Comment by kdpuvvadi** [comment]
> I think if you uninstall the drivers, it'll still be in the Driver Store, but not sure

just checked, drivers are still there in the driverstore. 

just tested this in sandbox, was able reproduce, 
image

So, how do we automate driver installation?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
>So, how do we automate driver installation?

At the moment, we can't.

image

I think there's an issue about this in Arduino's GitHub org for tracking, but forgot the issue number.

**Pull request closed without merging**
