### PR TITLE
DanTheMan827.ClassicContext version 1.0.1

### PR DESCRIPTION
**Pull request by DanTheMan827**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/54371)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
```
2022-03-18 17:06:25.278 [CLI ] Installer [X64,Nullsoft,Unknown,] not applicable: Current OS is lower than MinOSVersion 10.0.22000
2022-03-18 17:06:25.321 [CLI ] Terminating context: 0x8a150010 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\InstallFlow.cpp:73
```

Azure Pipelines is running 10.0.19042.1052 which is lower than the `MinimumOSVersion` listed in the manifest so it doesn't install.

**Comment by DanTheMan827** [comment]
@ItzLevvie this is only intended to be installed on Windows 11, that’s the proper minimum version for that, isn’t it?

**Comment by ItzLevvie** [comment]
> that’s the proper minimum version for that, isn’t it?

Yes but you will need to remove that if you want Azure Pipelines to pass because it's on Windows 10.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
See https://github.com/microsoft/winget-pkgs/pull/54371#issuecomment-1073368764.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
