### PR TITLE
New package: facebook.watchman

### PR DESCRIPTION
**Pull request by jennings**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Is there a linked Issue? #196632

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/196635)

### CODE REVIEW

**Comment by RoscoP** [comment]
I think this needs the VCRedist for the install.  When I tried this (not realizing you already had a PR) it didn't work using the tools/sandboxtest.ps1 script.
```
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
```

**Comment by jennings** [comment]
@RoscoP Thanks! I've added that to the PR.

**Comment by stephengillie** [comment]
Verify:
image

The application's version number has the same numerals, but in a different version schema, than the Registry displays. I believe most users will be able to relate the two.

**Review by stephengillie — APPROVED** [review]

**Comment by jennings** [comment]
> The application's version number has the same numerals, but in a different version schema, than the Registry displays.

Oh interesting. I wrote the version number that they tagged it with in GitHub. In the future, would it be preferred to use the version number the binary reports, or the one they use in release notes?

**Pull request merged**
