### PR TITLE
New version: SaltStack.SaltMinion version 30.07.1

### LINKED ISSUE #163087: [Update Request]: SaltStack.SaltMinion
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

SaltStack.SaltMinion

### Package Version

30.07.0+

### Please describe the changes you would like to see

- To replace https://github.com/microsoft/winget-pkgs/pull/163002

If the developer has stopped hosting this application, please state this in the comments.

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- Resolve #163087
- Related #163002

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/163578)

### CODE REVIEW

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Seems already fixed by #163419, but it tagged the version as `3007.1` instead of `30.07.1`.

**Comment by stephengillie** [comment]
> > [!Note]
> > 
> > Seems already fixed by #163419, but it tagged the version as `3007.1` instead of `30.07.1`.

Hi @Trenly,

Can you help us to find the correct version number for this package version?

**Comment by Trenly** [comment]
> > > [!Note]
> > > Seems already fixed by #163419, but it tagged the version as `3007.1` instead of `30.07.1`.
> 
> Hi @Trenly,
> 
> Can you help us to find the correct version number for this package version?

@stephengillie - It writes 3007.1 to the registry

```
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> winget install Saltstack.saltminion -s winget
Found Salt Minion [SaltStack.SaltMinion] Version 3007.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://repo.saltproject.io/salt/py3/windows/latest/Salt-Minion-3007.1-Py3-AMD64-Setup.exe
  ██████████████████████████████  60.7 MB / 60.7 MB
Successfully verified installer hash
Starting package install...
Successfully installed
PS C:\Users\WDAGUtilityAccount\Desktop\winget-pkgs> Get-ARPTable | ft

DisplayName                                                        DisplayVersion Publisher             ProductCode                            Scope
-----------                                                        -------------- ---------             -----------                            -----
Notepad++ (64-bit x64)                                             8.6.9          Notepad++ Team        Notepad++                              Mac...
Salt Minion 3007.1 (Python 3)                                      3007.1         SaltStack, Inc        Salt Minion                            Mac...
```

**Comment by stephengillie** [comment]
Close with reason: Duplicate of #163419;

**Pull request closed without merging**
