### PR TITLE
New version: Telegram.Unigram version 10.8.0.9930

### PR DESCRIPTION
**Pull request by rakleed**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/142909)

### CODE REVIEW

**Comment by rakleed** [comment]
@stephengillie

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-03-07 13:03:32.143 [CORE] Deployment operation #3: error 0x80073D02: Unable to install because the following apps need to be closed Microsoft.DesktopAppInstaller_1.21.2771.0_x64__8wekyb3d8bbwe Microsoft.XboxGamingOverlay_5.721.5282.0_x64__8wekyb3d8bbwe.
> 2024-03-07 13:03:37.512 [CORE] Deployment operation #4: Windows cannot install package TelegramFZ-LLC.Unigram_10.8.0.9930_x64__1vfw5zm9jmzqy because this package depends on a framework that could not be found. Provide the framework "Microsoft.VCLibs.140.00" published by "CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US", with neutral or x64 processor architecture and minimum version 14.0.30704.0, along with this package to install. The frameworks with name "Microsoft.VCLibs.140.00" currently installed are: {Microsoft.VCLibs.140.00_14.0.27323.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.29231.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.30035.0_x64__8wekyb3d8bbwe Microsoft.VCLibs.140.00_14.0.30035.0_x86__8wekyb3d8bbwe}
> 2024-03-07 13:03:37.512 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(161)\WindowsPackageManager.dll!00007FF8B4A33F75: (caller: 00007FF8B498A720) Exception(1) tid(534) 80073CF3 Package failed updates, dependency or conflict validation.
> 2024-03-07 13:03:37.663 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FF8B4A32D2F: (caller: 00007FF8B4A3432C) Exception(2) tid(534) 80073CF1 Package was not found.
> 2024-03-07 13:03:37.663 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(126)\WindowsPackageManager.dll!00007FF8B4BA8931: (caller: 00007FF8B4A35853) LogHr(1) tid(534) 80073CF1 Package was not found.
>     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Deployment.cpp(54)\WindowsPackageManager.dll!00007FF8B4A32D2F: (caller: 00007FF8B4A3432C) Exception(2) tid(534) 80073CF1 Package was not found.
> 2024-03-07 13:03:37.675 [CLI ] MSIX installer failed: 2147958003

(Automated response - build 867.)

**Comment by stephengillie** [comment]
I believe that the version of `Microsoft.VCRedist.2015+.x64` that the package requires might be higher than the highest manifest version in our repo.

**Comment by rakleed** [comment]
On https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version I can download the same version as put in winget. But `DisplayName` and `ProductCode` are incorrect for https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/VCRedist/2015%2B/x64/14.38.33135.0/Microsoft.VCRedist.2015%2B.x64.installer.yaml. Could be this a problem?

image

**Comment by stephengillie** [comment]
Yes, these might be causing the issue.

**Comment by rakleed** [comment]
https://github.com/microsoft/winget-pkgs/pull/142930

**Comment by rakleed** [comment]
What's wrong now?

**Comment by rakleed** [comment]
@stephengillie

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
