### PR TITLE
New version: GiulioSorrentino.WinDateFrom version 4.6

### PR DESCRIPTION
**Pull request by GiulianoSpaghetti**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140915)

### CODE REVIEW

**Comment by numerunix** [comment]
I'm seeing in file that the url is https://github.com/numerunix/WinDateFrom.avalonia/releases/download/4.6/WinDateFrom.Avalonia-4.6-x64.msi
that is correct.

Why does exist the exe in the log?

**Comment by stephengillie** [comment]
URL: https://github.com/numerunix/WinDateFrom.avalonia/releases/download/4.6/WinDateFrom.Avalonia-4.6-x64.msi 
Status Code: 200

(Automated message - build 813)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> URI: https://github.com/numerunix/WinDateFrom.avalonia/releases/download/4.0/WinDateFrom-4.0-x64.exe, Validation result: Failed, Http status code: NotFound 

(Automated response - build 813.)

**Comment by stephengillie** [comment]
[Policy] Network-Blocker

**Comment by numerunix** [comment]
Nope i removed all versione, the ones rhat remains are 4.6 in msi. The package .exe does not exists anymore.

**Comment by numerunix** [comment]
Hello there, the url windatefrom-4.0 has been deleted, the new url is 4.6 msi, due to a security fix that invalidate all previous version.

Thanks

**Comment by numerunix** [comment]
I solved the network blocker, the url was in windaframe.locale.en-us.

Try now thanks

**Comment by numerunix** [comment]
smart screen

**Comment by numerunix** [comment]
All is done, it must only be approved.

**Comment by numerunix** [comment]
Please, delete all previous version from your repository and approve it. That are dead links.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
