### PR TITLE
Update D:\Git\winget-pkgs\manifests\w\Wagnardsoft\DisplayDriverUninstaller\18.0.6.4

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114734&drop=dogfoodAlpha

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
Going to do one retry in case it was a transient error due to high load on pipelines, but not expecting much.

@denelon - Since the package already exists, not sure what the policy is on whether or not it should be removed if it fails pipelines again

**Comment by stephengillie** [comment]
Automatic Validation ended with: 
> URI: [https://www.wagnardsoft.com,](https://www.wagnardsoft.com%2C/) Validation result: Failed, Http status code: Forbidden 
URI: https://wagnardsoft.com/content/Privacy-Policy, Validation result: Passed
URI: https://www.wagnardsoft.com/display-driver-uninstaller-ddu-, Validation result: Failed, Http status code: Forbidden 
URI: https://www.wagnardsoft.com/DDU/download/DDU%20v18.0.6.4_setup.exe, Validation result: Failed, Http status code: Forbidden

It appears that this ISV is blocking automated downloads. I won't be able to waiver this.

**Pull request closed without merging**
