### PR TITLE
Add Tachidesk-Server

### PR DESCRIPTION
**Pull request by Witchilich**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/47124)

### CODE REVIEW

**Comment by Witchilich** [comment]
It definitely worked locally for me.

**Comment by OfficialEsco** [comment]
found this in the logs
```
MSI (s) (08:48) [10:00:46:009]: Product: Tachidesk Server -- Installation failed.

MSI (s) (08:48) [10:00:46:009]: Windows Installer installed the product. Product Name: Tachidesk Server. Product Version: 0.6.1. Product Language: 1033. Manufacturer: Suwayomi. Installation success or error status: 1633.

This installation package is not supported by this processor type. Contact your product vendor.
```

**Comment by Trenly** [comment]
cc @denelon

**Comment by denelon** [comment]
This looks like a "Hardware" related issue. Is there any documentation to help identify the requirement?

**Comment by KaranKad** [comment]
It seems that x86 version is failing to install on x86 os.
https://github.com/microsoft/winget-pkgs/pull/48746

**Pull request closed without merging**
