### PR TITLE
New version: MullvadVPN.MullvadVPN version 2024.3

### PR DESCRIPTION
**Pull request by Exorcism0666**
Created by [🥟 Dumplings](https://github.com/Exorcism0666/Dumplings) in workflow run [#1433](https://github.com/Exorcism0666/Dumplings/actions/runs/9096470558).

**Logs**
````
Updated: 2024.2 → 2024.3
Cannot validate argument on parameter 'ChatID'. The argument is null, empty, or consists of only white-space characters. Provide an argument that contains non white-space characters, and then try the command again.
Submitting WinGet manifests
Cannot validate argument on parameter 'ChatID'. The argument is null, empty, or consists of only white-space characters. Provide an argument that contains non white-space characters, and then try the command again.
````
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/153702)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

> This PR's version number 2024.3 has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 2024.2.0, which has 3 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 881)

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by IndyV** [comment]
@Exorcism0666 just like #151443 this PR is missing the patch parameter of the version (`.0`), which makes the automated checks fail and require feedback.
I'd love to have these updates automated. Could you fix this and future PR's by adding the patch version to it?

The "Apps & Features" settings page does contain the patch version btw.
image

**Comment by Trenly** [comment]
@stephengillie - I don't know if this is easy to add to your validation, but WinGet treats all versions as having infinite trailing `.0`, so `2024.2` is treated the same as `2024.2.0` and `2024.2.0.0`. So even though the number of parameters isn't the same, if you trimmed the end of `.0`, then the number of parameters would be the same

**Comment by stephengillie** [comment]
The `.0^` could be replaced with an empty string. Though I'm wondering if the check shouldn't be depreciated completely. 
- The bug it was meant to catch - Wingetbot adding or removing parameters - has been somewhat fixed, and moderators can modify its PRs now. 
- Many developers freely add and remove parameters. Especially dropping trailing `.0` sections. 
- As you described, the package manager freely adds and drops trailing `.0` sections as necessary to perform matching. 

I believe it might be causing more issues than it's solving now. What are your thoughts?

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @Manually-Validated,

This package installs and launches normally on a Windows 10 VM.

(Automated response - build 887.)

**Comment by Trenly** [comment]
> The `.0^` could be replaced with an empty string. Though I'm wondering if the check shouldn't be depreciated completely.
> 
> * The bug it was meant to catch - Wingetbot adding or removing parameters - has been somewhat fixed, and moderators can modify its PRs now.
> * Many developers freely add and remove parameters. Especially dropping trailing `.0` sections.
> * As you described, the package manager freely adds and drops trailing `.0` sections as necessary to perform matching.
> 
> I believe it might be causing more issues than it's solving now. What are your thoughts?

I think removing it could be okay, or perhaps we could just make it not add `Needs-Author-Feedback`  so that it doesn't block a PR?

**Pull request merged**
