### PR TITLE
New Version: Guru3D.RTSS version 7.3.5

### LINKED ISSUE #142070: [Update Request]: Guru3D.RTSS version 7.3.5
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Guru3D.RTSS

### Package Version

7.3.5

### Please describe the changes you would like to see

There is a new release ( 7.3.5) available
Download Page: https://www.guru3d.com/download/rtss-rivatuner-statistics-server-download/

### PR DESCRIPTION
**Pull request by og-mrk**
- [x] Resolves #142070

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/142094)

### CODE REVIEW

**Comment by og-mrk** [comment]
Hello @stephengillie,

May I ask why Linking PR to Issue isn't working? Thought it was a simple Keyword Usage in PR Description and that's it... maybe there's something I'm missing?

Thanks in advance 😄

**Comment by og-mrk** [comment]
Looks like the Validation of URL seems to suggest that this URL (ftp.nluug.nl) requires Manual Review, [link log line](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=549837&view=logs&j=129b3b09-7d10-5f42-7e8e-d03c270d019d&t=b1271a28-5e41-5241-ea64-08d00d7f0dc9&l=32), and a [link to warning](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=549837&view=logs&j=129b3b09-7d10-5f42-7e8e-d03c270d019d&t=b1271a28-5e41-5241-ea64-08d00d7f0dc9&l=36)

**Comment by og-mrk** [comment]
Interesting respond by @wingetbot ...
Is there anything I can do to help with validation URL problem @stephengillie ?

**Comment by stephengillie** [comment]
> Interesting respond by @wingetbot ... Is there anything I can do to help with validation URL problem @stephengillie ?

I'm testing some small changes in moderation for the team to bugfix. This is another bug we've just found.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
