### PR TITLE
Files-Community.Files version 1.5.0.0

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/18836)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
@jedieaston or @KaranKad can one of you test this Package for me?
The sandbox script won't cooperate atm (it would fail anyways tho cuz of the dependency (sandbox issue))

```
PS C:\Users\******\Github\winget-pkgs> .\Tools\SandboxTest.ps1 -Manifest .\manifests\f\Files-Community\Files\1.5.0.0\
--> Validating Manifest
Manifestvalideringen er fullført.

--> Checking dependencies
    - Downloading:

Exception: C:\Users\******\Github\winget-pkgs\Tools\SandboxTest.ps1:139
Line |
 139 |        throw "Error downloading $($dependency.url)."
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error downloading .
```

**Comment by KaranKad** [comment]
@OfficialEsco I am having same issue.
```
SandboxTest.ps1 .\files\
--> Validating Manifest
Manifest validation succeeded.

--> Checking dependencies
    - Downloading:

Exception: C:\Users\karan\Documents\GitHub\winget-pkgs\Tools\SandboxTest.ps1:139
Line |
 139 |        throw "Error downloading $($dependency.url)."
     |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error downloading .
```

**Comment by OfficialEsco** [comment]
> @OfficialEsco I am having same issue.

Realized this #18812 is why once i cleared a few manifests 😁 guess i'll get to my VM before someone gets to test it

**Comment by ItzLevvie** [comment]
This is what I see:
image

**Comment by OfficialEsco** [comment]
Hmm, is Microsoft.dotNetFramework the same as Microsoft.UI.Xaml? (Requesting same version)
And how did that become a problem by rereleasing the installer as `Files.Package_1.5.0.0_x86_x64.msixbundle` 🤔
Guess i'll make a issue over there..

**Comment by quhxl** [comment]
Look at this issue: files-community/Files#5176

**Pull request closed without merging**
