### PR TITLE
New version: Tencent.TencentDocs version 3.1.9

### PR DESCRIPTION
**Pull request by SpecterShell**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/123219)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @SpecterShell,

I can't navigate from the PackageUrl to the InstallerUrl. This version is newer than the version on the ISV site. Is the link to this package in a different location?

**Comment by SpecterShell** [comment]
It was obtained from their update API. You can find the script here: https://github.com/SpecterShell/Dumplings/tree/main/Tasks/Tencent.TencentDocs

**Comment by stephengillie** [comment]
Oh - need to be able to navigate from the PackageUrl to the InstallerUrl, and the PackageUrl has to be a full URL that supports the GET verb.

**Comment by SpecterShell** [comment]
> Oh - need to be able to navigate from the PackageUrl to the InstallerUrl, and the PackageUrl has to be a full URL that supports the GET verb.

The request to API for getting the InstallerUrl is POST, and the InstallerUrl obtained is GET.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
