### PR TITLE
AprelTech.SilentInstallBuilder.Beta version 6.2.2.0

### PR DESCRIPTION
**Pull request by OyePradumya**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/81335)

### CODE REVIEW

**Comment by OyePradumya** [comment]
Hey @OfficialEsco  @ItzLevvie 
Please help. This runs well perfectly in my machine, I can't find the issue. Is it something to do with any dependency?

**Comment by OfficialEsco** [comment]
Its blocked by some AntiVirus vendor, quite quickly too, maybe it will pass later if this is a new release or it won't pass at all..

**Comment by OyePradumya** [comment]
> Its blocked by some AntiVirus vendor, quite quickly too, maybe it will pass later if this is a new release or it won't pass at all..

Thank you. I'll wait for it to clear.

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
