### PR TITLE
New package: Microchip.MicrochipStudio version 7.0.2594

### LINKED ISSUE #112819: [Package Request]: Microchip Studio
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.microchip.com/en-us/tools-resources/develop/microchip-studio#Downloads
Publisher: Microchip Technology Inc.
Package Name: Microchip Studio
Description: Integrated Development Environment (IDE) for developing and debugging AVR® and SAM microcontroller applications.
Package Version: 7.0.2594
Installer URL: https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/as-installer-7.0.2594-full.exe

### PR DESCRIPTION
**Pull request by CoolPlayLin**
### Pull request has been created with [Komac](https://github.com/russellbanks/Komac) v1.9.1 :rocket:
- Resolve #112819
 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/115692&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
InstallationVerification-x86-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20230808142002

**Comment by CoolPlayLin** [comment]
It appears this software haven't supported for silent install because there is a PR that has already closed get same result
- https://github.com/microsoft/winget-pkgs/pull/99005

**Comment by CoolPlayLin** [comment]
？

**Comment by CoolPlayLin** [comment]
DO NOT CLOSE

**Comment by CoolPlayLin** [comment]
No

**Comment by CoolPlayLin** [comment]
？

**Pull request closed without merging**
