### PR TITLE
New package: Mattodev.Lifetime version 0.5.1

### PR DESCRIPTION
**Pull request by Matto58**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/154146)

### CODE REVIEW

**Comment by Matto58** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\Mattodev.Lifetime__DefaultSource\mtdeploy-1.0.0-win-x64.exe returned exit code: -2147450749
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\mtdeploy-1.0.0-win-x64.exe returned exit code: -2147450749

(Automated response - build 881.)

**Review by stephengillie — CHANGES_REQUESTED** [review]
image

**Comment by stephengillie** [comment]
With the dependency added, the application errors. Is this expected? 
image

**Comment by Matto58** [comment]
> With the dependency added, the application errors. Is this expected? image
> 
> Edit: Verify: image

prob not, some bug in my code, i tried to write an installer that installs the program but apparently winget does that for me, i thought i had to do that myself, sorry for these dumb mistakes, it's my first time submitting a package here

**Comment by Matto58** [comment]
is it okay if i make another commit with just the program (and the dependency edit you suggested)?

**Comment by stephengillie** [comment]
Hi @Matto58,

Sorry to not have responded - I get too many replies from bots to see those from humans, so feel free to @ me in the future. 

A PR can have more than 1 commit. It's manifests where the PR can only have 1 each. Feel free to update this with more commits if you would like, including adding the dependency.

**Comment by Matto58** [comment]
hi @stephengillie can i close this and open a new pr? i've released a new version of this after making the pr and i wanna remake the manifest to make things easier

**Comment by stephengillie** [comment]
Sure, feel free.

**Pull request closed without merging**
