### PR TITLE
theAzurian.Bookmarkr version 1.0.0

### PR DESCRIPTION
**Pull request by BelRarr**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/192385)

### CODE REVIEW

**Comment by BelRarr** [comment]
@stephengillie this is my first submission. Can you help me? I don't understand what I need to do. Thanks! :)

**Comment by stephengillie** [comment]
Hi @BelRarr,

In this case, there is nothing to do. The validation pipeline is somewhat designed for Windows Forms, and adds the https://github.com/microsoft/winget-pkgs/labels/Validation-Executable-Error link when the exit code is non-zero. But a non-zero exit code is common for CLI applications, so I usually pass exit codes below 1000. I"ve requested this change be pushed upstream: 
- https://github.com/microsoft/winget-pkgs/issues/157749

**Comment by BelRarr** [comment]
So, this means that my submission will be accepted and that my package will
be available?

Kind regards.

Le mar. 19 nov. 2024 à 14:52, Stephen Gillie ***@***.***> a
écrit :

**Comment by stephengillie** [comment]
Yes, I've been performing the verification as we corresponded. Verify:
image

The package seems to write version `1.0.0` to the Registry, but displays `1.0.3` - is this expected? 

- Once this version discrepancy is resolved, I intend to approve the PR.
- Our GitOps automation should process this and merge the PR, which would add the manifest into the repo.
- Then, our Publish pipeline will package this with all other manifest data, and make this available on our CDN, for the package manager client to download.

**Comment by BelRarr** [comment]
Oh! My bad! The version number in the csproj indicates 1.0.3.

I will fix this in the next few minutes.

Thank you.

Le mar. 19 nov. 2024 à 15:00, Stephen Gillie ***@***.***> a
écrit :

**Comment by BelRarr** [comment]
@stephengillie just submitted a new PR to fix the issue:
https://github.com/microsoft/winget-pkgs/pull/192486

**Comment by stephengillie** [comment]
Close with reason: Duplicate of #192486;

**Comment by BelRarr** [comment]
Yes, indeed. This one can be closed. Thank you very much!

**Pull request closed without merging**
