### PR TITLE
Add ARM64 for Spotify

### PR DESCRIPTION
**Pull request by louis993546**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/95000)

### CODE REVIEW

**Comment by louis993546** [comment]
Not sure why the installation validation step failed, and the log is not helpful either. Can someone help?

(I have an arm64 machine and the installer works just fine on my machine)

**Comment by SpecterShell** [comment]
It seems that the ARM64 version has lagged behind for a while, so you can not append it to this manifest at present otherwise it will cause a infinite upgrade loop.
image

**Comment by SpecterShell** [comment]
This one should work: https://download.scdn.co/SpotifyFullSetupARM64.exe
image

**Comment by louis993546** [comment]
Got it and thank you @SpecterShell

Will update this PR in a few hours

**Comment by SpecterShell** [comment]
@stephengillie

**Comment by louis993546** [comment]
hmm why is it still failing?

**Comment by SpecterShell** [comment]
It was due to a bug from the old versions of WinGet client which can not force the installer to run in user mode in the validation pipeline. As the client in the validation pipeline has been updated recently, this bug should be fixed now. You can simply trigger the validation process by closing and re-opening the PR. You may see the "Internal-Error-Dynamic-Scan" but it is OK.

**Comment by louis993546** [comment]
oh there is a new version now brb

**Comment by louis993546** [comment]
#95479

**Comment by SpecterShell** [comment]
https://upgrade.scdn.co/upgrade/client/win32-arm64/spotify_installer-1.2.3.1115.gd61a8f5c-384.exe
You can use this static link.

**Pull request closed without merging**
