### PR TITLE
Fix Fossil.Fossil x64 installer SHA-256 hash

### PR DESCRIPTION
**Pull request by ManuelBlanc**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

Previous `InstallerSha256` value was the hash of the first 2 bytes, as shown in this bash session:

```
$ printf 'PK' | sha256sum
fcab7fcc2b4cffd9bb45003bfc2e468a04ef6f77ca8200a7341f027631584d25  -

$ curl -s https://fossil-scm.org/home/uv/fossil-w64-2.22.zip | sha256sum
3c62f706b1d421a6b26585ad93e72dee54f1d4450b059661601cd3f446618419  -
```

This caused installation to fail when extracting:

```
2023-07-04 01:23:01.799 [CLI ] Extracting archive to: C:\Users\mbc\AppData\Local\Temp\WinGet\Fossil.Fossil.2.22\extracted
2023-07-04 01:23:01.843 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Archive.cpp(33)\WindowsPackageManager.dll!00007FFC3C57EACB: (caller: 00007FFC3C527281) ReturnHr(1) tid(1300) 80004005 Unspecified error
2023-07-04 01:23:01.844 [CLI ] Failed to extract archive with code -2147467259
2023-07-04 01:23:01.844 [CLI ] Terminating context: 0x8a15005c at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\ArchiveFlow.cpp:42
```

I've been able to verify locally that fossil will install correctly when the hash is fixed.
 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/111228&drop=dogfoodAlpha

### CODE REVIEW

**Comment by ManuelBlanc** [comment]
Apologies, I didn't realize until after submission that I ran my local tests with a manual download of `fossil-w64-2.22.zip` into `%TEMP%\WinGet\Fossil.Fossil.2.22`. A clean reinstall produced the following error:

```
Downloading https://fossil-scm.org/home/uv/fossil-w64-2.22.zip
  ██████████████████████████████  2.00 B / 2.00 B
Installer hash does not match.
```

Enabling verbose logging for Delivery Optimization reveals a HTTP spec violation by the fossil-scm.org webserver: it is returning a 200 OK response with a [`Content-Range`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range) header which is disallowed by https://www.rfc-editor.org/rfc/rfc9110#section-14.4-14. Relevant log excerpt is included at the bottom of this post.

I am looking to the Fossil devs regarding this.
In the meantime, would it be possible to manually approve this PR?

---

```
2023-07-04T02:27:21.7101806Z 1F4C 10C4     Info {CSwarm::_InternalStart} Swarm: 3c62f706b1d421a6b26585ad93e72dee54f1d4450b059661601cd3f446618419, DownloadMode_Simple for URL: https://fossil-scm.org/home/uv/fossil-w64-2.22.zip
2023-07-04T02:27:21.7101863Z 1F4C 10C4     Info {CSwarm::_TryCreateMetaInfoMock} Swarm: 3c62f706b1d421a6b26585ad93e72dee54f1d4450b059661601cd3f446618419, Creating metadata from URL: https://fossil-scm.org/home/uv/fossil-w64-2.22.zip
2023-07-04T02:27:21.7104640Z 1F4C 10C4          {LogTokenUserInfo} WinHTTP session token: yADKAOYA1gDoAN4A4ABaAGIAxADEAOYAZgDgANAAuADaAMQAxgA=
2023-07-04T02:27:21.7126478Z 1F4C 10C4          {CWinHttpAgent::_DoConnect} Establishing HTTP Connection to https://fossil-scm.org/home/uv/fossil-w64-2.22.zip
2023-07-04T02:27:21.7126535Z 1F4C 10C4          {CWinHttpAgent::_DoConnect} Connecting to the following host: fossil-scm.org, IP: :443
2023-07-04T02:27:22.1929397Z 1F4C 4298          {CCore::_ClearInStartup} left startup mode 16067 mSec after creation, 504 mSec after first swarm, 1 swarms created
2023-07-04T02:27:22.1929587Z 1F4C 4298          {CGlobalConfigManager::GetUploadLimitCalcIntervalSecs} UploadLimitCalcIntervalSec = 20
2023-07-04T02:27:22.1935263Z 1F4C 4298          {CGlobalConfigManager::GetUploadLimitGBPerMonth} UploadLimitGBMonth = 20.000000
2023-07-04T02:27:22.1935286Z 1F4C 4298          {CCore::_UpdateMonthlyUploadRestriction} Monthly usage: curMonth: 7, curBytes: 0, limitBytes: 21474836480, restriction: 0
2023-07-04T02:27:22.1936407Z 1F4C 4298          {CGlobalConfigManager::IsDownloadRateAutoLimitEnabled} DownloadRateLimiting: fEnabled = 1
2023-07-04T02:27:22.1939086Z 1F4C 4298          {CUploadRateStrategy::SetUploadRateStrategyParams} UploadRateStrategy params: autoLimit? 0, ratePct: 50, periodicCycleSecs: 900, unlimitedDurationSecs: 20, userSetRate: 0
2023-07-04T02:27:22.1941922Z 1F4C 4298          {CGlobalConfigManager::GetDownloadRateLimitParams} DownloadRateLimiting for foreground: pctRate = 90, bpsRate = 0, pctProvider = 99, bpsProvider = 99
2023-07-04T02:27:22.1944653Z 1F4C 4298          {CGlobalConfigManager::GetDownloadRateLimitParams} DownloadRateLimiting for background: pctRate = 45, bpsRate = 0, pctProvider = 99, bpsProvider = 99
2023-07-04T02:27:22.1944705Z 1F4C 4298          {CGlobalConfigManager::GetOSSCalcIntervalSecs} OSS calc interval = 2400
2023-07-04T02:27:22.1944783Z 1F4C 4298          {CGlobalConfigManager::GetMaxDownloads} MaxForegroundDownloads = 100
2023-07-04T02:27:22.1944843Z 1F4C 4298          {CGlobalConfigManager::GetMaxDownloads} MaxBackgroundDownloads = 100
2023-07-04T02:27:22.1944861Z 1F4C 4298          {CCore::_OssRecalcAll} All: 1, FG: 0, FG_sleeping: 0, BG: 0, BG_sleeping: 0, UP: 0
2023-07-04T02:27:22.1944896Z 1F4C 4298          {CGlobalConfigManager::GetOSSMaxUploads} OSSMaxUploads = 4
2023-07-04T02:27:22.1946313Z 1F4C 4298          {CGlobalConfigManager::GetOSSMaxUploadSwarms} OSSMaxUploadSwarms = 50
2023-07-04T02:27:22.1948803Z 1F4C 4298          {CGlobalConfigManager::IsPolicyAllowVPNPeerCaching} PolicyAllowVPNPeerCaching: 0
2023-07-04T02:27:22.6240019Z 1F4C 10D0          {CWinHttpAgent::_OnHeadersAvailable} Using Http version HTTP/1.1 for resource /home/uv/fossil-w64-2.22.zip
2023-07-04T02:27:22.6240186Z 1F4C 10D0          {CMetaInfoDownloader::OnConnection} MetaInfo: OnConnection returned headers: HTTP/1.1 200 OK
Cache-Control: max-age=0
Content-Length: 2
Content-Type: application/zip
Content-Range: bytes 0-1/3333494
Last-Modified: Wed, 31 May 2023 15:38:35 +0000
ETag: 58639c7e2396dc36015bf8c8c8176b91
Content-Security-Policy: default-src 'self' data:; script-src 'self' 'nonce-2db26be30312d62c9ef687a0be5af1ffa684d5ce4bdb3301'; style-src 'self' 'unsafe-inline'; img-src * data:
X-Frame-Options: SAMEORIGIN
```

**Comment by ManuelBlanc** [comment]
Report in the Fossil forums: https://fossil-scm.org/forum/forumpost/0906f8108a

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
