### PR TITLE
Remove version: Bosyun.Pixso version 1.34.2

### PR DESCRIPTION
**Pull request by damn-good-b0t**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/172496)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://pixso-cms-ff.oss-eu-central-1.aliyuncs.com/packages/download/desktop/bosyun/1.34.2/Pixso_win_v1_34_2.exe 
Response Error: The remote server returned an error: (404) Not Found.

(Automated message - build 920)

**Comment by stephengillie** [comment]
Hi @damn-good-b0t,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 895.)

**Comment by stephengillie** [comment]
URL: https://pixso-cms-ff.oss-eu-central-1.aliyuncs.com/packages/download/desktop/bosyun/1.34.2/Pixso_win_v1_34_2.exe 
Response Error: The remote server returned an error: (404) Not Found.

(Automated message - build 920)

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
[Policy] Needs-Manual-Merge

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
