### PR TITLE
New version: Perforce.P4V version 242.260.6884

### LINKED ISSUE #154802: [Update Request]: Perforce.P4V
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Perforce.P4V

### Package Version

259.1061

### Please describe the changes you would like to see

New release available on Perforce webpage. There is a link for newest version (MSI) https://www.perforce.com/downloads/perforce/r24.1/bin.ntx64/p4vinst64.msi
Latest package version on winget is: 234.255.8838
Thank you!

### PR DESCRIPTION
**Pull request by hymerman**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---
Fixes https://github.com/microsoft/winget-pkgs/issues/154802

There's an existing PR here: https://github.com/microsoft/winget-pkgs/pull/154803 - but it seems to have some unresolved issues and has gone stale. The package version number looks incorrect too. I've just run a simple update of the existing manifest using YamlCreate.ps1, which has passed all validation and testing locally in a sandbox.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/157425)

### CODE REVIEW

**Comment by hymerman** [comment]
Looks like the second step, "WinGetSvc-Validation (WinGetSvc_Validation Installer Validation)", is marked as failing but with no errors/warnings or output. The log on Azure pipelines just says "Result: Failed".

The first check "WinGetSvc-Validation" has a warning "Installer Type Validation is disabled" - perhaps that's why the second check fails?

**Comment by stephengillie** [comment]
> Looks like the second step, "WinGetSvc-Validation (WinGetSvc_Validation Installer Validation)", is marked as failing but with no errors/warnings or output. The log on Azure pipelines just says "Result: Failed".
> 
> The first check "WinGetSvc-Validation" has a warning "Installer Type Validation is disabled" - perhaps that's why the second check fails?

https://github.com/microsoft/winget-pkgs/discussions/155218#discussioncomment-9739881

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
