### PR TITLE
Indent.Access version 0.10.11

### PR DESCRIPTION
**Pull request by ethernetdan**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/106831)

### CODE REVIEW

**Comment by ethernetdan** [comment]
@stephengillie looks like a job may have hung, is there a way to restart it?

**Comment by stephengillie** [comment]
> @stephengillie looks like a job may have hung, is there a way to restart it?

Yes - it looks like you found one way, by adding a commit. Closing and reopening the PR will also trigger this, and community volunteers & admins can also.

**Comment by stephengillie** [comment]
Manual Validation failed with:
> Description: A .NET application failed. Application: migration.exe Path: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\nkdAgility.AzureDevOpsMigrationTools__DefaultSource\preview\migration.exe 
> Message: You must install .NET to run this application.  
>App: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\nkdAgility.AzureDevOpsMigrationTools__DefaultSource\preview\migration.exe Architecture: x64 
> App host version: 7.0.5 .
> NET location: Not found  
> Learn about runtime installation: https://aka.ms/dotnet/app-launch-failed  
> Download the .NET runtime: https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=7.0.5   

With the dependency preinstalled, the package installs and runs normally.

**Comment by ethernetdan** [comment]
> Manual Validation failed with:
> 
> > Description: A .NET application failed. Application: migration.exe Path: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\nkdAgility.AzureDevOpsMigrationTools__DefaultSource\preview\migration.exe
> > Message: You must install .NET to run this application.
> > App: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\nkdAgility.AzureDevOpsMigrationTools__DefaultSource\preview\migration.exe Architecture: x64
> > App host version: 7.0.5 .
> > NET location: Not found
> > Learn about runtime installation: https://aka.ms/dotnet/app-launch-failed
> > Download the .NET runtime: https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=7.0.5
> 
> With the dependency preinstalled, the package installs and runs normally.

@stephengillie I'm a bit confused, is this for another package? I don't believe any dependencies should be required

**Comment by Trenly** [comment]
I've verified this installs and runs correctly in a sandbox environment.

image

**Review by Trenly — APPROVED** [review]

**Comment by Trenly** [comment]
Going to re-run the pipeline to remove the blocking issue

**Comment by ethernetdan** [comment]
Makes sense, thanks for the help!

**Pull request merged**
