### PR TITLE
Glimpse x86 & x64 branches.

### PR DESCRIPTION
**Pull request by hchorey**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3396)

### CODE REVIEW

**Comment by hchorey** [comment]
It seems like the Pull Request Validation is only failing because I moved the location of one of the files up a folder level and into a different folder; The system is seeing the deletion and recreation of the file as the creation of 2 separate manifests which is now allowed.  Is there a different way I should be doing this, or is this a bug in the verification process?

**Comment by hchorey** [comment]
To clarify what I am doing: up until the 0.2.0 release of Glimpse, all Windows builds were x86 applications.  With the release of 0.2.0, there is now the x86 msi installer (same upgrade path as previous version), and a separate x64 msi installer, which installs in a different folder than the previous release.  I am changing the manifest folder structure to reflect the 2 different builds with Glimpse-x86 and Glimpse-x64, and have moved the previous 0.1.2.yaml up into the Glimpse-x86 folder and modified the ID accordingly.

**Comment by hchorey** [comment]
@KevinLaMS I hate to ask and bother you, but is this a bug in the Pull Request Validation process? If not, could you point towards what I did incorrectly?

**Comment by hchorey** [comment]
...could this be related to Issue #128 (https://github.com/microsoft/winget-pkgs/issues/128)?  Everything appears to be valid, so I am unsure why the Pull Request Validation failed.  There's only 1 manifest per folder.

**Comment by KevinLaMS** [comment]
@hchorey It looks to me like the main issue is that there are 3 manifest files in the PR.  Unfortunately we can only have 1 file per PR until that limitation is eliminated.
If you are moving a file, if it shows up as a delete and an add, you will need to make 2 PRs to add and  delete the file.
@msftrubengu

**Comment by hchorey** [comment]
Ok, I'm trying again doing each step incrementally for each pull request here: https://github.com/microsoft/winget-pkgs/pull/3434  Here goes.  :)

**Pull request closed without merging**
