### PR TITLE
Update FormatFactory to 5.4

### PR DESCRIPTION
**Pull request by auanasgheps**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3360)

### CODE REVIEW

**Comment by auanasgheps** [comment]
I have validated the updated manifest on my machine. The URL can be downloaded successfully, the hash corresponds and the installation completes successfully.

**Comment by OfficialEsco** [comment]
Its actually failing because of the SmartScreen scan, the bot is drunk

**Comment by auanasgheps** [comment]
I have only updated URL, SHA and versions. See #1445 for more information.

**Comment by OfficialEsco** [comment]
```
-----------------------------------------------------
Manifest: manifests\FreeTime\FormatFactory\5.4.yaml
-----------------------------------------------------
URI: http://www.pcfreetime.com/formatfactory/index.php, Validation result: Passed
URI: http://www.pcfreetime.com/formatfactory/aboutus.php?language=en, Validation result: Passed
URI: http://public.pcfreetime.com/FFSetup5.4.0.0.exe, Validation result: Failed, Report feedback: https://feedback.smartscreen.microsoft.com/feedback.aspx?v=6&t=512&result=block&type=top&url=aHR0cDovL3B1YmxpYy5wY2ZyZWV0aW1lLmNvbS9GRlNldHVwNS40LjAuMC5leGU%3D

****************************************************************************************
Manifest Content Validation
****************************************************************************************
Status: Completed
##[error] Result: Failed
```
I've also submitted a manifest which received this error earlier, and i downloaded the file myself and got the SmartScreen msg so this is infact the cause.

**Pull request merged**
