### PR TITLE
SylvainRougeaux.Metatogger version 7.3.1.2

### PR DESCRIPTION
**Pull request by CyberSinh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/93751)

### CODE REVIEW

**Comment by CyberSinh** [comment]
I see only one possible reason for the failure of the MSI installer: the non installation of the VS C++ runtime.
The necessity of this prerequisite is however declared in the manifest:
```yaml
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
```

Is the support of the manifest `Dependencies` tag planned in the short or medium term (winget 1.5 ?) or do you recommend me rather to push an executable installer (burn), embedding all the software prerequisites? 

Thanks.

**Comment by stephengillie** [comment]
> I see only one possible reason for the failure of the MSI installer: the non installation of the VS C++ runtime. The necessity of this prerequisite is however declared in the manifest:
> 
> ```yaml
> Dependencies:
>   PackageDependencies:
>   - PackageIdentifier: Microsoft.VCRedist.2015+.x64
> ```
> 
> Is the support of the manifest `Dependencies` tag planned in the short or medium term (winget 1.5 ?) or do you recommend me rather to push an executable installer (burn), embedding all the software prerequisites?
> 
> Thanks.

Hi @CyberSinh,

Yes, the dependency is causing the issue. From the logs: 
```
MSI (s) (38:88) [14:17:08:550]: Product: Metatogger 7.3 -- This application requires the Visual C++ Runtime 2015-2022 (x64). Please install it then run this installer again.
```

I've tested the installer in a VM with a 1.4 preview, and since this version installs dependencies before the main package installer, it installs normally. We're monitoring version adoption and plan to start accepting packages with dependencies after 1.4 is sufficiently saturated.

**Comment by CyberSinh** [comment]
@stephengillie, now that winget version 1.4 is widely deployed, when do you plan to validate this RP?

**Comment by stephengillie** [comment]
> @stephengillie, now that winget version 1.4 is widely deployed, when do you plan to validate this RP?

Sorry for the delay and thank you for the reminder. We were impacted by a couple of issues right around the pipeline upgrade. 
* https://github.com/microsoft/winget-pkgs/issues/95543

**Comment by CyberSinh** [comment]
Hi @stephengillie,

The pipeline failed with "Validation-Shell-Execute". Is it a bug of the pipeline or an issue with my PR ? Because everything is fine on my side if the dependency VC++ runtime is installed before running the setup.

Thanks.

**Comment by stephengillie** [comment]
Hi @CyberSinh,

Yes, validation is failing due to the missing package `Microsoft.VCRedist.2015+.x64`. Validations are performed on fresh installs of Windows. 

From the installer:
> MSI (s) (70:A8) [18:36:13:385]: Product: Metatogger 7.3 -- This application requires the Visual C++ Runtime 2015-2022 (x64). Please install it then run this installer again.

**Comment by CyberSinh** [comment]
Hi @stephengillie,

I may not have understood how the `winget` dependency mechanism works, but this error should not occur if the VC Runtime is properly installed by `winget` before installing Metatogger.
I can understand that the validation is done on a fresh system but why is the installation of the declared dependencies not done before?
If this is the expected behavior of the validation pipeline, what are your recommendations? Disable all checks for the presence of dependencies at Metatogger installation?

Thanks.

**Comment by stephengillie** [comment]
> Hi @stephengillie,
> 
> I may not have understood how the `winget` dependency mechanism works, but this error should not occur if the VC Runtime is properly installed by `winget` before installing Metatogger. I can understand that the validation is done on a fresh system but why is the installation of the declared dependencies not done before? If this is the expected behavior of the validation pipeline, what are your recommendations? Disable all checks for the presence of dependencies at Metatogger installation?
> 
> Thanks.

Ideally, dependencies are installed before the main package. And in experimental testing, this does occur. I've mistakenly believed that dependencies were fully supported. And hopefully after this issue is resolved, we'll be able to accept this one. 
* https://github.com/microsoft/winget-cli/issues/163

**Comment by Trenly** [comment]
[Policy] Blocking-Issue

**Comment by CyberSinh** [comment]
The version 7.3.1.2 of Metatogger is now outdated.
I will send new pull request when winget will fully support dependencies (v1.5?).

**Pull request closed without merging**
