### PR TITLE
New package: Microsoft.AppInstaller version 1.21.3133.0

### PR DESCRIPTION
**Pull request by denelon**
Testing adding App Installer to community repository.

This should work for `winget upgrade winget` and `winget upgrade --all`

No dependencies are included since WinGet already has the dependencies if it's installed.

There is **NO** intention to support preview versions of WinGet.

This should work for `winget upgrade winget` and `winget upgrade --all`

---

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/129354)

### CODE REVIEW

**Comment by denelon** [comment]
Hey moderators...

I'm thinking about letting this one in. I don't want the preview versions because WinGet will just try to upgrade everyone to preview builds which would be terrible. What are your thoughts?

@stephengillie Let's be sure to keep an eye on things and make sure that doesn't happen.

@ImJoakim
@ItzLevvie
@jedieaston
@KaranKad
@mdanish-kh
@OfficialEsco
@quhxl
@russellbanks
@Trenly

**Comment by Trenly** [comment]
Sounds good to me

**Review by Trenly — APPROVED** [review]

**Comment by babblebauble** [comment]
Shouldn't the package version be 1.21.3132.0? I already have the latest stable version installed but winget is showing an update available because of this manifest listing the version as 1.21.3133.0.


Capture

**Comment by babblebauble** [comment]
> This is a subtle issue related to what we call a stub-package. The version from the Microsoft Store defaults to a stub preference which would be version 1.21.3132 for the App Installer. By default, that version wouldn't have the WinGet Configure functionality enabled. The release at GitHub includes the WinGet Configure enabled (version 1.21.3133).
> 
> If you actually had the "earlier" version with the stub preference, when you attempted to run `winget configure` you would get a message with the instructions to enable the feature. Enabling the feature would download the additional binaries necessary for WinGet Configure, and the version would bump to 1.21.3133.
> 
> Once the configuration feature has been enabled the stub preference is changed to "full" and any future updates via the Microsoft Store would include the additional code.

I actually installed Winget from the GitHub releases rather than the Microsoft Store and use the Github releases to update as well. When I run `winget configure` I don't get any notification to enable the feature (just brings up the usage syntax and the available aliases and arguments).

**Pull request merged**
