### PR TITLE
Add version: TabbyML.Tabby version v0.15.0

### PR DESCRIPTION
**Pull request by ptsouchlos**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/168629)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334960
> 2024-08-21 21:18:00.244 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFB3443C11F: (caller: 00007FFB341C8D6F) LogHr(1) tid(140c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFB34342B08: (caller: 00007FFB343EBC20) Exception(1) tid(140c) 8A15005E ] 
> 2024-08-21 21:18:04.496 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFB3443C11F: (caller: 00007FFB341C8D6F) LogHr(1) tid(1ee4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFB34342B08: (caller: 00007FFB343EBC20) Exception(1) tid(1ee4) 8A15005E ] 
> 2024-08-21 21:18:12.414 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFB146CC11F: (caller: 00007FFB14458D6F) LogHr(1) tid(1320) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFB145D2B08: (caller: 00007FFB1467BC20) Exception(1) tid(1320) 8A15005E ] 
> 2024-08-21 21:27:52.177 [CLI ] ShellExecute installer failed: 3772776448
> MSI (s) (4C:00) [21:18:21:452]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (4C:00) [21:18:21:452]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (4C:00) [21:18:21:452]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (4C:00) [21:18:21:452]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (4C:00) [21:18:21:452]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> Property(S): OutOfDiskSpace = 0
> Property(S): OutOfNoRbDiskSpace = 0
> Property(S): PrimaryVolumeSpaceAvailable = 0
> Property(S): PrimaryVolumeSpaceRequired = 0
> Property(S): PrimaryVolumeSpaceRemaining = 0
> MSI (s) (4C:3C) [21:18:22:374]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (4C:3C) [21:18:22:374]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (4C:3C) [21:18:22:374]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (4C:3C) [21:18:22:374]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (4C:3C) [21:18:22:374]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.

Automated error analysis suggests -1978334960 may mean Failed to install package dependencies.

Automated error analysis suggests 8A15005E may mean APPINSTALLER_CLI_ERROR_PINNED_CERTIFICATE_MISMATCH - The server certificate did not match any of the expected values.

(Automated response - build 887.)

**Comment by DeveloperPaul123** [comment]
Pushed some changes and seems to work for me:
image

**Comment by DeveloperPaul123** [comment]
See https://github.com/microsoft/winget-pkgs/pull/168629#issuecomment-2307168149 for validation.

**Review by stephengillie — APPROVED** [review]

**Comment by DeveloperPaul123** [comment]
@stephengillie Is there something else I need to do? I keep getting notifications regarding validation.

**Pull request merged**
