### PR TITLE
Seedy-Threepio.Theseus2000 version 3.6

### PR DESCRIPTION
**Pull request by seedy60**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/102185)

### CODE REVIEW

**Comment by SeedyThreeSixty** [comment]
@microsoft-github-policy-service agree
Sent from Windows Live Mail 2009

**Comment by stephengillie** [comment]
Automatic Validation failed with:
> Installation failed with exit code -1978335187 
> 2023-04-11 03:28:39.264 [FAIL] Installer failed security check. Url: https://t2000.seedy.gq/Theseus2000_Installer.exe Result: 0x80004005

**Comment by SeedyThreeSixty** [comment]
I'm guessing this error is being thrown because the installer is unsigned?

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
