### PR TITLE
Remove old version of JanDeDobbeleer.OhMyPosh

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
null

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
image

**Comment by vedantmgoyal2009** [comment]
@ItzLevvie Now, please check, maybe I had got the new version early. It is now reflecting 2.2126.11

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
Still
image

> Possible duplicate package entry.
> 
> Similar installer SHA256 hash found in manifest:
> 
> * `InstallerSha256: f64aeca0f1393df5bf9b1c168630a884f401d9794f5959c2d2cc8ddbb8ea5759`
>   
>   * manifests\w\WhatsApp\WhatsApp\2.2126.10
> * `InstallerSha256: 8b11b6c01518a43d91598ea5cd1dd87aea2fe122cfe521b867e8192c81139360`
>   
>   * manifests\w\WhatsApp\WhatsApp\2.2126.10

Your PR also have the 2.2126.10 Hashes.

**Comment by vedantmgoyal2009** [comment]
I think EXE has not been updated yet and the update is directly delivered to users who have WhatsApp Desktop installed.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
image

Version's still the same as of today:
image

**Comment by vedantmgoyal2009** [comment]
> image
> 
> Version's still the same as of today:
> image

Can you please send your modified PRTest.ps1 here.

**Comment by OfficialEsco** [comment]
This has nothing to do with `PRTest.ps1`. `PRTest.ps1` runs `SandboxTest.ps1` which runs `winget install -m %PathToVersion%` in Sandbox.
This PR have the InstallerUrl and SHA256 of WhatsApp 2.2126.10 so its incorrect in all the ways which means you failed to do 
`[X] Have you tested your manifest locally with winget install --manifest <path>?` as expected.
If your URL redirects you to the 2.21.26.11 installer it would fail because the Hash does not match.

**Comment by vedantmgoyal2009** [comment]
Oh! I want PRTest.ps1 of Levvie because she has some modifications.
and since I got an update on WhatsApp Desktop, I have opened this PR, but now I realized that this update has been delivered directly and the EXE on the website has not been updated with the new version.

**Comment by OfficialEsco** [comment]
> Oh! I want PRTest.ps1 of Levvie because she has done some modifications.

What kind of Modification would help you start doing quality control?..

> And since I got an update on WhatsApp Desktop, I have opened this PR, but now I realized that this update has been delivered directly and the EXE on the website has not been updated with the new version yet.

Then you can close the PR, if there is a update wingetbot will catch it

**Comment by ItzLevvie** [comment]
> Can you please send your modified PRTest.ps1 here.

It's open-source at https://github.com/ItzLevvie/winget-pkgs-validate-and-install.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
