### PR TITLE
Huawei.HiSuite version 11.0.0.580

### PR DESCRIPTION
**Pull request by Dragon1573**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/37971)

### CODE REVIEW

**Comment by Dragon1573** [comment]
1. Installed successfully on my own device with `winget install -m` command. Could you please do me a favour if there're still mistakes in the manifests?
2. The latest version of this application is `v11.0.0.590`. It doesn't released on the offical page, so I can't figure out the downloading URL of that version. It will popup a dialog asking you for upgrading when you first launch the application.

**Comment by Dragon1573** [comment]
@ItzLevvie 

I'm really sorry for submitting such a wierd `InstallerURL` in the manifest. 🙏🏼

In the offical homepage of this application, the **Download** button is associated with a shorter URL. But I can't figure out if the associated URL is generated dynamically.

image

The wierd so-long URL is copied from the file-downloader embedded in Microsoft Edge. Maybe it's not a good idea?

**Comment by SpecterShell** [comment]
https://github.com/microsoft/winget-pkgs/pull/30806

The short URL from the homepage is enough.

**Comment by Dragon1573** [comment]
> The installer itself requires VC++, so it cannot pass before the dependency feature is implemented in WinGet.

I haven't searched for those previous Pull Requests. It's my fault. 😢

Now I get it. Can't wait for such a usefull features in future version of WinGet! 🎉

> The short URL from the homepage is enough.

OKay, thanks for your instructions. I'll change the wierd `InstallerUrl` to shorter one.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Manifest validation succeeded with warnings:
image

Shortened URL works fine :)

but seems like installation is blocked by VC++ dependency:
image

**Comment by Dragon1573** [comment]
> https://github.com/microsoft/winget-pkgs/pull/37971#pullrequestreview-835115813
>
> Manifest validation succeeded with warnings

Oops?! There's an indentation error in my `installer.yaml` file 🤣 Now it's fixed by a771aa4.

> https://github.com/microsoft/winget-pkgs/pull/37971#pullrequestreview-835115813
>
> Shortened URL works fine :)

Okay, that's nice! 🎉

Nice

> https://github.com/microsoft/winget-pkgs/pull/37971#pullrequestreview-835115813
>
> Seems like installation is blocked by VC++ dependency

My device is previously installed dual version of **Microsoft Visual C++ 2015-2019 Redistributable**. But when I invoke the uninstallation process, it seems that **Hisuite** itself is not "silent-able". I have no idea how to handle it this time ...

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
You can set this PR in draft mode until dependency support works in WinGet.

**Comment by Dragon1573** [comment]
> You can set this PR in draft mode until dependency support works in WinGet.

@ItzLevvie Okay, thank you for your remindings.

**Review by ItzLevvie — APPROVED** [review]

**Comment by Dragon1573** [comment]
Someone else fixed this issue. This pull request can be closed without merging. 

- Latest version: `11.0.0.650`
- Related pull request: #66513

**Pull request closed without merging**
