### PR TITLE
New package: DuckStudio.FufuDevTools version 2024.06.24.2036

### PR DESCRIPTION
**Pull request by DuckDuckStudio**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue? --No

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

> [Test Log]
> [DuckStudio.FufuDevTools.Test.log](https://github.com/user-attachments/files/16033927/DuckStudio.FufuDevTools.Test.log)

> [!NOTE]
> If encountering windows Defender errors, refer to the PR #157822  , which also includes this toolkit.
> New version #160758 
---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/160563)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Program Files (x86)\Fufu_Dev_Tools\git\账号切换.exe returned exit code: 1
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\git\连续pull尝试.exe returned exit code: 1
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\Script\ffdev.exe returned exit code: 1
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\生成工具\需求生成.exe returned exit code: 2
> Executable C:\Program Files (x86)\Fufu_Dev_Tools\统计\代码总行数.exe returned exit code: 2

(Automated response - build 886.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> Program:Win32/Wacapew.C!ml Trojan:Win32/Wacatac.B!ml Trojan:Win32/Wacatac.H!ml

(Automated response - build 886.)

**Comment by DuckDuckStudio** [comment]
https://www.microsoft.com/en-us/wdsi/submission/2b4fb3f2-d5bd-4fec-bd3e-20ffe967228a
image

**Comment by stephengillie** [comment]
Verify:
image
I couldn't find an application that displayed version information. 

Is there any terminal software that could display these characters natively, without modifying the OS? It would be useful for validation.

**Review by stephengillie — APPROVED** [review]

**Comment by DuckDuckStudio** [comment]
> Verify: 图像 I couldn't find an application that displayed version information.
> 
> Is there any terminal software that could display these characters natively, without modifying the OS? It would be useful for validation.

Since this toolkit is a pre-release version, there is no version display program set...
The version information is only in the file VERSION.

**Pull request merged**
