### PR TITLE
New version: tencent.tencentmeeting 3.4.1.436

### PR DESCRIPTION
**Pull request by lychichem**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/40756)

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]

**Comment by SpecterShell** [comment]
This seems to be a beta version... 🤔

**Comment by OfficialEsco** [comment]
How can you tell? I don't read structure letters so if it says that go ahead and fix it 😁

**Comment by SpecterShell** [comment]
https://meeting.tencent.com/download-win.html?from=1000&fromSource=1
This page downloads stable version. It is now at 3.3.4.444.

https://meeting.tencent.com/download-beta.html?from=1000&fromSource=1&fromSource=1&type=3
This page downloads beta version. It is now at 3.4.1.436.

I am working on pushing this package to the automation (https://github.com/vedantmgoyal2009/winget-pkgs-automation/issues/230). However the current version (3.4.1.436) in winget-pkgs is newer than that in the stable channel (3.3.4.444), which blocks the process.

@lychichem How about waiting for newer stable version or removing existing beta versions so that the automation process could get passed?

**Comment by lychichem** [comment]
> https://meeting.tencent.com/download-win.html?from=1000&fromSource=1 This page downloads stable version. It is now at 3.3.4.444.
> 
> https://meeting.tencent.com/download-beta.html?from=1000&fromSource=1&fromSource=1&type=3 This page downloads beta version. It is now at 3.4.1.436.
> 
> I am working on pushing this package to the automation ([vedantmgoyal2009/winget-pkgs-automation#230](https://github.com/vedantmgoyal2009/winget-pkgs-automation/issues/230)). However the current version (3.4.1.436) in winget-pkgs is newer than that in the stable channel (3.3.4.444), which blocks the process.
> 
> @lychichem How about waiting for newer stable version or removing existing beta versions so that the automation process could get passed?

If it blocks automation, I need to say apologize to you. The reason for adding beta version is even if I installed a stable version of tencentmeeting on my machine, every time when I start it, the software will check for beta version and show a red dot, so I will install a new version...

**Pull request merged**
