### PR TITLE
Add reko

### PR DESCRIPTION
**Pull request by superusercode**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/929)

### CODE REVIEW

**Comment by superusercode** [comment]
image
What would I put as the detection name?

**Comment by ousugo** [comment]
just put the filename of the installer, Smartscreen identify a file through sha256.

**Comment by superusercode** [comment]
image
 Despite passing the check from the submission to windows defender it is still marked by safescreen. Not sure how reputation is supposed to be established when this app isn't really popular.

**Comment by superusercode** [comment]
image
Despite passing the check from the submission to windows defender it is still marked by safescreen. Not sure how reputation is supposed to be established when this app isn't really popular.

**Comment by superusercode** [comment]
@KevinLaMS reko no longer fails smartscreen

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
