### PR TITLE
New version: JakobDev.jdMinecraftLauncher version 5.1

### PR DESCRIPTION
**Pull request by JakobDev**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/115963&drop=dogfoodAlpha

### CODE REVIEW

**Comment by JakobDev** [comment]
The installation worked locally for me

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2023-08-09 12:50:14.835 [FAIL] Installer failed security check. Url: https://sourceforge.net/projects/jdminecraftlauncher/files/5.1/jdMinecraftLauncher-5.1-WindowsInstaller.exe/download Result: 0x80004005

**Comment by JakobDev** [comment]
[It has been build by a CI](https://ci.codeberg.org/repos/12318/pipeline/3/6), so it's virus free. I used Wine to build, so I guess this the reason for the problems.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
