### PR TITLE
Delete manifests/s/ShiningLight/OpenSSL/Light/3.0.11

### PR DESCRIPTION
**Pull request by JohnMcPMS**
A recent change by @szhu25 introduced `DisplayVersion` values for all 3 versions of this package that are all `1.0.0`.  This makes the update process unhappy; removing the older two versions for now.  If possible, I would suggest updating the installer to write the appropriate version.  If not, then the only choice is to remove the `DisplayVersion` again.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/121483)

### CODE REVIEW

**Comment by szhu25** [comment]
I believe the MSI version of the OpenSSL installers all showed the same version... Would removing this value help? 
I'm not the maintainer for the OpenSSL installers (produced by Shining Light Productions), so couldn't comment on that...

**Comment by szhu25** [comment]
Hi @JohnMcPMS,
I have submitted new PRs (#121488, #121487, #121486) & modified existing PRs (#121304, #121293, #121268) to remove display version from all manifests. Sorry about the trouble

**Review by denelon — APPROVED** [review]

**Comment by stephengillie** [comment]
> Sequence contains no elements
https://github.com/microsoft/winget-pkgs/pull/121482#issuecomment-1744040718

**Comment by treysis** [comment]
I would rather have ShiningLight's OpenSSL removed from winget as the author of the MSI is unwilling to adhere to MSI versioning standards and is saying winget should find another way to determine the version number then.

So until this is resolved, I vote for complete removal.

**Pull request closed without merging**
