### PR TITLE
Updated Google Chrome to version 93.0.4577.82.

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

------

The bot seems to have a higher tolerance for bad hashes lately.

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/27578)

### CODE REVIEW

**Comment by jedieaston** [comment]
Gosh darn CDN....

**Comment by jedieaston** [comment]
han

image

**Review by ItzLevvie — APPROVED** [review]

**Comment by jedieaston** [comment]
Getting closer, now only the x86 installer is failing.

image

**Comment by jedieaston** [comment]
Now the 64-bit one is wrong again. Heck.

image

**Pull request merged**
