### PR TITLE
update zoom to 5.1.2

### PR DESCRIPTION
**Pull request by alanlima**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2335)

### CODE REVIEW

**Comment by denelon** [comment]
@alanlima I got "Installer failed with exit code: 1603". When I looked at the log:

> MSI (s) (A0:18) [11:17:07:442]: Product: Zoom -- Error 1925. You do not have sufficient privileges to complete this installation for all users of the machine.  Log on as administrator and then retry this installation.
> 
> Error 1925. You do not have sufficient privileges to complete this installation for all users of the machine.  Log on as administrator and then retry this installation.

Is there a user based install rather than a machine based install?

**Comment by alanlima** [comment]
@denelon yeah, there is an exe installer (https://zoom.us/client/5.1.28642.0705/ZoomInstaller.exe).

I tried it here and it works without admin. **However, the Zoom client will automatically start after the installation finishes.**

I could not find any switches that can prevent that on EXE installer (only on MSI). I will try to contact Zoom support to check, or if someone knows what to do, I can update the manifest. 🤗

If there is no problem to let the zoom auto-start, I can submit my changes. 😁

**Comment by denelon** [comment]
@alanlima I think we will stick with the .msi over the .exe. I just wish the error message regarding admin mode was a bit more clear. This will probably show up as a bug in the future, but I'll go ahead and approve this for now.

**Review by ghost — APPROVED** [review]
Validation has completed

**Comment by alanlima** [comment]
> @alanlima I think we will stick with the .msi over the .exe. I just wish the error message regarding admin mode was a bit more clear. This will probably show up as a bug in the future, but I'll go ahead and approve this for now.

I agree with that. Not sure if it will be better to show a message when fails like "Some installers may required admin level, try to run again as administrator".

**Pull request merged**
