### PR TITLE
add manifest for Unifyned

### PR DESCRIPTION
**Pull request by chris-kruining**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3598)

### CODE REVIEW

**Comment by chris-kruining** [comment]
I am still working on obtaining a code-signing-cert, however I had hoped I could still upload the manifest in advance to "reserve" the name

**Comment by KevinLaMS** [comment]
image

**Comment by chris-kruining** [comment]
still working on obtaining a code signing cert.

**Comment by chris-kruining** [comment]
@KevinLaMS I repeat, still working on getting the code signing cert

**Comment by chris-kruining** [comment]
fixed it

**Comment by KevinLaMS** [comment]
I am struggling to identify the files installed with this installer.  Can you provide me a hint?

**Comment by chris-kruining** [comment]
there are none as of yet, I am still working on the application. I am mostly waiting for updates on dependencies (I use webview 2 which still requires a user to have edge beta installed instead of a dll). But in order to reserve the name I wanted to upload a manifest pre-emptively.

**Comment by KevinLaMS** [comment]
Removing pass so I quit processing.

**Comment by denelon** [comment]
@chris-kruining we've updated the manifest schema to v1.0. Does Unifyned still have the dependency on Edge beta?

We haven't implemented support for dependencies yet, so this might not pass even with the manifest schema upgrade. 

I'm just going through older PRs to see if any more of them can be validated and approved. :smile:

**Comment by chris-kruining** [comment]
> @chris-kruining we've updated the manifest schema to v1.0. Does Unifyned still have the dependency on Edge beta?
> 
> We haven't implemented support for dependencies yet, so this might not pass even with the manifest schema upgrade.
> 
> I'm just going through older PRs to see if any more of them can be validated and approved. 😄

depends, I haven't looked at this issue in a while because I had to focus on other tasks. Unifyned relies on Webview2 WPF component. I believe -but don't quote me on this- that that component no longer requires a local installed version of edge and can instead package it with the app via a dll. If this is the case than I don't have a dependency anymore

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
image

**Comment by chris-kruining** [comment]
I will just open a new PR by the time I have an actuall running app

**Pull request closed without merging**
