### PR TITLE
New version: nkdAgility.AzureDevOpsMigrationTools.Preview version 15.1.6-Preview.1

### PR DESCRIPTION
**Pull request by MrHinsh**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164759)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-07-26 19:26:54.581 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFB4B7BC11F: (caller: 00007FFB4B548D6F) LogHr(1) tid(770) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFB4B6C2B08: (caller: 00007FFB4B76BC20) Exception(1) tid(770) 8A15005E ] 
> 2024-07-26 19:26:58.100 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFB4B7BC11F: (caller: 00007FFB4B548D6F) LogHr(1) tid(19f4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFB4B6C2B08: (caller: 00007FFB4B76BC20) Exception(1) tid(19f4) 8A15005E ] 
> 2024-07-26 19:27:04.943 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFB2B32C11F: (caller: 00007FFB2B0B8D6F) LogHr(1) tid(120c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFB2B232B08: (caller: 00007FFB2B2DBC20) Exception(1) tid(120c) 8A15005E ] 
> 2024-07-26 19:29:27.854 [FAIL] Installer failed security check. Url: https://github.com/nkdAgility/azure-devops-migration-tools/releases/download/v15.1.6-Preview.1/MigrationTools-15.1.6-Preview.1.zip Result: 0x80004005
> MSI (s) (20:7C) [19:27:16:132]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (20:7C) [19:27:16:132]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (20:7C) [19:27:16:132]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (20:7C) [19:27:16:132]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (20:7C) [19:27:16:132]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> MSI (s) (20:7C) [19:27:17:366]: Executing op: ComponentRegister(ComponentId={30152033-0219-5D29-82E3-281991AAECB6},KeyPath=22*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.7\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=1)
> MSI (s) (20:7C) [19:27:18:694]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=1,,)
> Property(S): ErrorDialog = ErrorDlg
> Property(S): OutOfDiskSpace = 0
> Property(S): OutOfNoRbDiskSpace = 0
> Property(S): PrimaryVolumeSpaceAvailable = 0
> Property(S): PrimaryVolumeSpaceRequired = 0
> Property(S): PrimaryVolumeSpaceRemaining = 0
> MSI (s) (20:44) [19:27:19:225]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (20:44) [19:27:19:225]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (20:44) [19:27:19:225]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (20:44) [19:27:19:225]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (20:44) [19:27:19:225]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> MSI (s) (20:F4) [19:27:19:819]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (20:F4) [19:27:19:819]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (20:F4) [19:27:19:819]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (20:F4) [19:27:19:819]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (20:F4) [19:27:19:819]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> MSI (s) (20:B0) [19:27:20:835]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (20:B0) [19:27:20:835]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (20:B0) [19:27:20:835]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (20:B0) [19:27:20:835]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (20:B0) [19:27:20:835]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 8A15005E may mean APPINSTALLER_CLI_ERROR_PINNED_CERTIFICATE_MISMATCH - The server certificate did not match any of the expected values.

(Automated response - build 887.)

**Comment by MrHinsh** [comment]
We often have issues with this one, but it's often identical to the non-preview version.

For example, this build is exactly the same code as the current non-preview. (Rebuilt, but same code).

Why does this one fail and the other one passes?

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
