### PR TITLE
[Agreements] Add back VMware.WorkstationPlayer

### PR DESCRIPTION
**Pull request by mdanish-kh**
cc @denelon @stephengillie

Installer prompt:
image

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/139465)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Installer https://download3.vmware.com/software/WKST-PLAYER-1702/VMware-player-full-17.0.2-21581411.exe
 Scan request id: '396616f2-cbde-4b2b-b5db-38a530c8aa02'
 Error information: BlockingDetectionFound
 
 2/16/2024 3:54:37 PM
 
 ****************************************************************************************
 Installer Validation
 ****************************************************************************************
 

(Automated response - build 762.)

**Comment by stephengillie** [comment]
This might be due to a network block of data centers, to prevent automated downloads.

(Automated response - build 762.)

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Installer https://download3.vmware.com/software/WKST-PLAYER-1702/VMware-player-full-17.0.2-21581411.exe
 Scan request id: '92cb2b90-ac2f-4756-ac3b-fad6fcda2b66'
 Error information: BlockingDetectionFound
 
 2/18/2024 2:28:02 PM
 
 ****************************************************************************************
 Installer Validation
 ****************************************************************************************
 

(Automated response - build 781.)

**Comment by mdanish-kh** [comment]
Any chance this can be manually validated? Package used to exist, I'm just re-adding it with agreements

**Comment by stephengillie** [comment]
Unfortunately, it hasn't progressed through the pipelines far enough to manually validate. And the network block would prevent future versions. I agree that - in theory - this should be easy to readd, and if an exception were made I'd merge it.

**Comment by mdanish-kh** [comment]
Since https://github.com/microsoft/winget-pkgs/pull/143919, I'll try a re-run of this PR

**Comment by mdanish-kh** [comment]
Closing in favor of newer version merged in https://github.com/microsoft/winget-pkgs/pull/143919

**Pull request closed without merging**
