### PR TITLE
New version: JetBrains.Rider version 213.6461.51

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/38862)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by jedieaston** [comment]
Can you close and reopen this one so the pipelines re-run?

**Comment by vedantmgoyal2009** [comment]
@jedieaston I think I miss some of the GitHub notifications. Do you know any settings which might a user has to enable to get all notifications?

**Comment by jedieaston** [comment]
I don't. You may want to play with the settings here: https://github.com/settings/notifications

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Please close and re-open the PR to re-run the pipelines.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Please close and re-open the PR to re-run the pipelines.

**Comment by vedantmgoyal2009** [comment]
How many times 😢

**Comment by vedantmgoyal2009** [comment]
How many times 😢

**Pull request merged**
