### PR TITLE
New version: octobuild.octobuild version 0.6.1

### PR DESCRIPTION
**Pull request by slonopotamus**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/118045)

### CODE REVIEW

**Comment by slonopotamus** [comment]
I looked at CI logs but failed to find any error message that would explain why installer validation failed.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335187 
2023-08-25 05:39:06.691 [FAIL] Installer failed security check. Url: https://github.com/octobuild/octobuild/releases/download/0.6.1/octobuild-0.6.1-x86_64.msi Result: 0x80004005 

Hi @slonopotamus, 

This like is a type of Defender error. Unfortunately, I'm not able to waiver or manually validate to get around this easily. There's a chance that this is a false positive, and we can rescan tomorrow.

**Comment by slonopotamus** [comment]
Weird. On VirusTotal the file is absolutely clean: https://www.virustotal.com/gui/url/c641a58b56446e2f9214d8b0a901f0ef03382a765add9c8f83196ae94b185733

**Comment by slonopotamus** [comment]
So, how do I proceed?

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
> So, how do I proceed?

@slonopotamus,

Sorry to leave you hanging. I made a mistake in removing the `Needs-Attention` label. In the future, please @ me so the PR shows up in my mentions.

**Pull request merged**
