### PR TITLE
Add Irfan View 4.54

### LINKED ISSUE #48: Question: how to handle installers without direct links?
As I'm playing with this tool, I notice a great deal of Win32 apps have installers which are not available for direct link. This prevents them from being used with winget.

For example, [IrfanView](https://www.irfanview.com/), a popular image viewer and editor. Its installer is listed on the 3rd party site fosshub.com. Here is the link: https://www.fosshub.com/IrfanView.html?dwl=iview454_x64_setup.exe

**The URL is misleading, however: this isn't the actual installer link, it's a page (with ads) that programmatically triggers downloading the installer.** This way, there is no direct link to the installer, and thus, fosshub gets ad views to subsidize their bandwidth.

Looking at Irfanview's download page, all the installers are on 3rd party sites, and all of them prevent hotlinking like this.

**How can I submit a manifest when the installer doesn't have a direct URL?** Obviously, I could host the installer myself, but my servers couldn't handle e.g. a million downloads. Will Microsoft fetch these installers and mirror them on its own CDN? IMO, this is the best option.

### PR DESCRIPTION
**Pull request by SoftCreatR**
Auto Generated by softcreatr@winget on Wed, 27 May 2020 08:26:40 +0000

Resolves #48

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1208)

### CODE REVIEW

**Comment by SoftCreatR** [comment]
Huh? I broke it 😸

**Comment by JudahGabriel** [comment]
You found a working direct link to the IrfanView installer. Kudos! I will close my PR for IrfanView, which was using workarounds for the missing direct link to the installer.

**Comment by SoftCreatR** [comment]
> You found a working direct link to the IrfanView installer. Kudos! I will close my PR for IrfanView, which was using workarounds for the missing direct link to the installer.

I just checked if there's already a PR or a manifest file. Must have missed it, sorry.

**Comment by MCOfficer** [comment]
How does mediaside involved with IrfanView? I didn't see it among the [official mirrors](https://www.irfanview.com/main_download_engl.htm).

You might want to try [fileforum](https://fileforum.betanews.com/detail/IrfanView/967963863/1) instead, which is one of the recommended mirrors: http://download.betanews.com/download/967963863-1/iview454_x64_setup.exe

**Comment by SoftCreatR** [comment]
https://irfanview.mediaside.co.uk/

**Comment by MCOfficer** [comment]
Ah, there's also a mirror selection at the top of the website, that's where the link to mediaside is. Fair enough.

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
