### PR TITLE
Helix.Helix version 23.03

### PR DESCRIPTION
**Pull request by Revnixcad**
- [ x ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ x ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ x ] This PR only modifies one (1) manifest
- [ x ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ x ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ x ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/101377)

### CODE REVIEW

**Comment by Revnixcad** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
I'm not able to find the cause for this error. It installs and runs normally on a Windows 11 VM.
image

Note for future reference: this package accepts commands in a way similar to VI, and the exit command is a similar `:q!` - be sure to press the `Esc` key to exit `insert mode` beforehand.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation failed with:
> Standard error:  Exception during executable launch operation System.AggregateException: One or more errors occurred. (The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): The specified executable is not a valid application for this OS platform. --- End of stack trace from previous location where exception was thrown ---    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) 

So the x86 version should probably be removed.

**Comment by Revnixcad** [comment]
I will make a new pull request without x86 version.

**Pull request merged**
