### PR TITLE
Update: Perforce.P4Merge version 2020.1

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/46130)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
@denelon here is one you can tell the engineers to investigate =)

**Comment by denelon** [comment]
I've asked one of the engineers to take a look at this one.

**Comment by zachcarp** [comment]
I don't know why it's showing as canceled here - that's not what I am seeing upon closer inspection. What I do see is that it's still running the installer validation. I would leave this for now so we don't have to start that over in case it is one of the installers that is going to take a little extra time. If we haven't seen any traction by end of day we can kick it again.

**Comment by zachcarp** [comment]
I take it back - it is for some reason canceled. I'm kicking it again - will dig in deeper if the issue persists.

**Comment by OfficialEsco** [comment]
> I take it back - it is for some reason canceled. I'm kicking it again - will dig in deeper if the issue persists.

This is the most common issue we see with the pipeline, https://github.com/microsoft/winget-pkgs/issues/42616

**Pull request merged**
