### PR TITLE
Remove version: taers232c.GAMADV-XTD3 version 6.76.15

### PR DESCRIPTION
**Pull request by taers232c**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/158580)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://github.com/taers232c/GAMADV-XTD3/releases/download/v6.76.15/gamadv-xtd3-6.76.15-windows-x86_64.msi 
OK

(Automated message - build 910)

**Comment by stephengillie** [comment]
Hi @taers232c,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 886.)

**Comment by taers232c** [comment]
Seems to be right

**Comment by stephengillie** [comment]
- This can be approved once https://github.com/microsoft/winget-pkgs/pull/158506 is merged.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
