### PR TITLE
SeriousBit.NetBalancer version 10.5.3.3032

### PR DESCRIPTION
**Pull request by AlexDev404**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/63623)

### CODE REVIEW

**Comment by AlexDev404** [comment]
@ItzLevvie 
This one shouldn't have any problems.

**Comment by AlexDev404** [comment]
@ItzLevvie **Ignore my last ping. No need to waste your time on this issue - It has dependency issues.**

Oh wait...[you already tried this](https://github.com/microsoft/winget-pkgs/pull/19825#pullrequestreview-707831647) but it doesnt work huh?

I'm guessing the [dependency issues](https://github.com/microsoft/winget-pkgs/issues/19821#issuecomment-874018116) are gonna block it. No worries, I'll just wait for the implementation.

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
It isn't a dependency issue - It is an issue that the installer cannot run unattended due to the driver installation prompt.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
You can set this pull request to DRAFT.

**Comment by AlexDev404** [comment]
> You can set this pull request to DRAFT.

@ItzLevvie Sure Levvy! I'll do just that.

**Comment by ItzLevvie** [comment]
@msftbot Blocking-Issue

**Comment by ItzLevvie** [comment]
@msftbot Interactive-Only-Installer

**Comment by AlexDev404** [comment]
@ItzLevvie What am I supposed to do now?

**Comment by AlexDev404** [comment]
@ItzLevvie So it's okay to leave it as draft, right?

**Comment by ItzLevvie** [comment]
yes

**Comment by AlexDev404** [comment]
> yes

Okay, but won't it be closed?

**Pull request closed without merging**
