### PR TITLE
matchmycolor.ColibriBeta version 22.3.1.9988

### PR DESCRIPTION
**Pull request by matchmycolor**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://api.github.com/repos/microsoft/winget-pkgs/pulls/95510)

### CODE REVIEW

**Comment by matchmycolor** [comment]
@microsoft-github-policy-service agree company="matchmycolor"

**Comment by stephengillie** [comment]
This package requires the .NET Desktop Runtime 6.0.5 (x86):
image

I tried using the package `Microsoft.DotNet.DesktopRuntime.6`, but it must be a 64-bit package, as the installer generated the error even with it installed.

**Comment by matchmycolor** [comment]
Yes, we have some prerequisite dependencies for .net runtimes. We also have an installer that includes these dependencies. Should we publish this installer with winget? What is the proper way of dealing with prerequisites?

**Comment by denelon** [comment]
We're working through support for dependencies. It's currently an experimental feature. The one open remaining item is updating the path for the install flow so the dependency is recognized by the "main" package to be installed.

* https://github.com/microsoft/winget-cli/issues/2939

If you publish a version including dependencies, the PR can be approved.

The schema supports referencing dependencies, but the issue mentioned above is the blocker.

**Pull request closed without merging**
