### PR TITLE
Remove user scope and ARP entries from KeePass 2.56.0 manifest

### PR DESCRIPTION
**Pull request by mdanish-kh**
Changes discussed in https://github.com/microsoft/winget-pkgs/pull/137901#discussion_r1479583335 (user scope) and https://github.com/microsoft/winget-pkgs/pull/137901#issuecomment-1929293584 (ARP)

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/138415)

### CODE REVIEW

**Comment by mdanish-kh** [comment]
> Hello @mdanish-kh,
> 
> Please verify the manifest file is compliant with the package manager [1.0 manifest specification](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.0.0?rgh-link-date=2024-02-08T19%3A06%3A53Z), [1.1 manifest specification](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0?rgh-link-date=2024-02-08T19%3A06%3A53Z), [1.2 manifest specification](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0?rgh-link-date=2024-02-08T19%3A06%3A53Z), or [1.4 manifest specification](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0?rgh-link-date=2024-02-08T19%3A06%3A53Z).
> 
> Make sure the ID is of the form publisher.appname and that the folder structure is manifests\partition\publisher\appname\version.
> 
> > Note: The path and "PackageIdentifier" are case sensitive.
> 
> Be sure to use a tool like [VSCode](code.visualstudio.com) to make sure the manifest YAML syntax is correct. You can also validate your manifest using the `winget validate` command.
> 
> For details on the specific error, see the details link below in the build pipeline.
> 
> Template: msftbot/validationError/manifest/content

You may have got this wrong, chief.

**Comment by mdanish-kh** [comment]
> > Hello @mdanish-kh,
> > Please verify the manifest file is compliant with the package manager [1.0 manifest specification](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.0.0?rgh-link-date=2024-02-08T19%3A19%3A15Z), [1.1 manifest specification](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0?rgh-link-date=2024-02-08T19%3A19%3A15Z), [1.2 manifest specification](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0?rgh-link-date=2024-02-08T19%3A19%3A15Z), or [1.4 manifest specification](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0?rgh-link-date=2024-02-08T19%3A19%3A15Z).
> > Make sure the ID is of the form publisher.appname and that the folder structure is manifests\partition\publisher\appname\version.
> > > Note: The path and "PackageIdentifier" are case sensitive.
> > 
> > 
> > Be sure to use a tool like [VSCode](code.visualstudio.com) to make sure the manifest YAML syntax is correct. You can also validate your manifest using the `winget validate` command.
> > For details on the specific error, see the details link below in the build pipeline.
> > Template: msftbot/validationError/manifest/content
> 
> You may have got this wrong, chief.

Or maybe I have

**Review by Trenly — APPROVED** [review]

**Pull request merged**
