### PR TITLE
New version: Racket.Racket version 8.11.1

### PR DESCRIPTION
**Pull request by custardtwist**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/133976)

### CODE REVIEW

**Comment by custardtwist** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Hi @custardtwist,

> This PR's version number 8.11.1 has 3 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version 8.10, which has 2 parameters.

Is this intentional?

(Automated response - build 566)

**Comment by custardtwist** [comment]
Hi @stephengillie 
Yes, this is the latest version, 8.11.1 being a bug-fix release of version 8.11.
Should a PR be submitted adding version 8.11?

**Comment by stephengillie** [comment]
It's okay, just wanted to be sure. 

Sometimes version numbers get added or omitted, and this causes issues with matching. So I have automation that asks when the number of parameters changes.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
