### PR TITLE
Lambda.openexr-viewer version 0.6.0

### PR DESCRIPTION
**Pull request by afichet**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/108450)

### CODE REVIEW

**Comment by afichet** [comment]
My software includes a huge work from third parties, mainly from OpenEXR team (Academy Software Foundation) and Qt.
Your CLA clearly state that "each of Your Submissions is entirely Your original work".
So I won't see how my software would comply with those CLA.

**Comment by stephengillie** [comment]
> My software includes a huge work from third parties, mainly from OpenEXR team (Academy Software Foundation) and Qt. Your CLA clearly states that "each of Your Submissions is entirely Your original work". So I won't see how my software would comply with those CLA.

I believe the CLA applies to your manifest submission, and not the end package. Since technically it's a link to the package that's being submitted, not the package itself.

**Comment by BrandonWanHuanSheng** [comment]
@afichet You need to sign the license/cla.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
See https://github.com/microsoft/winget-pkgs/pull/108450#issuecomment-1569296173

**Comment by afichet** [comment]
I raised some concerns about the CLA here https://github.com/microsoft/winget-pkgs/pull/108450#issuecomment-1569125084

Can you confirm the CLA and more specifically "each of Your Submissions is entirely Your original work" applies only to the manifest files and not to the actual source code as suggested by stephengillie?

Otherwise, I cannot sign the CLA since my program multiple third party libraries.

**Comment by afichet** [comment]
Would be great as well if @microsoft-github-policy-service stops spamming my PR.

**Comment by afichet** [comment]
So, based on the information provided in this PR the CLA applies solely to the manifest.

@microsoft-github-policy-service agree

**Review by ItzLevvie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
