### PR TITLE
New version: ImageMagick.ImageMagick.Q8 version 7.1.1.43

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#10466](https://github.com/SpecterShell/Dumplings/actions/runs/12457627505).

<details>

<summary>Log</summary>

````
Updated: 7.1.1.42 → 7.1.1.43
Submitting WinGet manifests
Creating manifests
WinGet exits with exitcode -1978335231
Uploading manifests and making commits
The manifests for the last version 7.1.1.41 will be removed. Reason: This task is configured to remove the last version
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/201577)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
InstallerUrl contains Manifest version instead of PR version:
  InstallerUrl: https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-41-Q8-x86-dll.exe
   InstallerUrl: https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-41-Q8-x64-dll.exe
   InstallerUrl: https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-41-Q8-arm64-dll.exe
   InstallerUrl: https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-41-portable-Q8-x86.zip
   InstallerUrl: https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-41-portable-Q8-x64.zip
   InstallerUrl: https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-41-portable-Q8-arm64.zip

(Automated message - build 931)

**Comment by SpecterShell** [comment]
@stephengillie https://github.com/microsoft/winget-pkgs/issues/120261#issuecomment-2561750123

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 1:44:21 PM: 
> 2024-12-25 13:44:11.445 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(176)\WindowsPackageManager.dll!00007FFBF7931139: (caller: 00007FFBF792CECB) Exception(2) tid(1b7c) 80190194 Not found (404).       1:44:21 PM: 
> 2024-12-25 13:44:11.672 [CLI ] Failed to download, waiting a bit and retry. Url: https://imagemagick.org/archive/binaries/ImageMagick-7.1.1-41-Q8-x64-dll.exe                                                                       1:44:21 PM: 
> 2024-12-25 13:44:15.843 [CORE] DeliveryOptimization error: 0x80190194, extended error: 0x00000000           1:44:21 PM: 
> 2024-12-25 13:44:15.843 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(346)\WindowsPackageManager.dll!00007FFBF7934BDB: (caller: 00007FFBF79338BC) Exception(3) tid(1b7c) 80190194 Not found (404).     1:44:21 PM: 
> 2024-12-25 13:44:15.980 [CORE] Download request failed. Returned status: 404

(Automated response - build 931.)

**Comment by SpecterShell** [comment]
@stephengillie

**Comment by stephengillie** [comment]
Thanks for helping me to find these.

**Pull request merged**
