### PR TITLE
New version: JesseDuffield.lazygit version 0.38.2

### PR DESCRIPTION
**Pull request by mloskot**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/107885)

------

image

### CODE REVIEW

**Comment by stephengillie** [comment]
This package is expecting a Git version:
```
2023/05/23 13:53:06 Git version must be at least 2.20 (i.e. from 2018 onwards). Please upgrade your git version. Alternatively raise an issue at https://github.com/jesseduffield/lazygit/issues for lazygit to be more backwards compatible.
PS C:\Users\User\Desktop> C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\JesseDuffield.lazygit__DefaultSource\lazygit.exe -version
commit=5149b24ab3dfad3860e2300519c7c583dcc8c9ff, build date=2023-05-03T08:00:22Z, build source=binaryRelease, version=0.38.2, os=windows, arch=386, git version=
```
Is Git a dependency here?

**Comment by mloskot** [comment]
Apparently - I had no idea and I failed to check - it does! https://github.com/jesseduffield/lazygit/issues/583

How should I handle this? All packages I've submitted so far were dependency-less.

**Comment by stephengillie** [comment]
Testing with `Git.Git` preinstalled, the error persists:
> 2023/05/23 17:57:57 Git version must be at least 2.0 (i.e. from 2014 onwards). Please upgrade your git version. Alternatively raise an issue at https://github.com/jesseduffield/lazygit/issues for lazygit to be more backwards compatible.
PS C:\Users\User\Desktop> C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\JesseDuffield.lazygit_Microsoft.Winget.Source_8wekyb3d8bbwe\lazygit.exe -version
commit=16802a048e0425182f08cf0e9a2bc31480e9a55d, build date=2023-02-01T11:02:43Z, build source=binaryRelease, version=0.37.0, os=windows, arch=amd64, git version=
PS C:\Users\User\Desktop> &"C:\Program Files\Git\bin\git.exe" "-v"
git version 2.40.1.windows.1

**Comment by stephengillie** [comment]
> Apparently - I had no idea and I failed to check - it does! [jesseduffield/lazygit#583](https://github.com/jesseduffield/lazygit/issues/583)
> 
> How should I handle this? All packages I've submitted so far were dependency-less.

No worries! We're currently looking forward to supporting dependencies, and are gladly collecting these packages under the `dependencies` label in anticipation of this feature being added soon.

**Comment by stephengillie** [comment]
> Testing with `Git.Git` preinstalled, the error persists:
> 
> > 2023/05/23 17:57:57 Git version must be at least 2.0 (i.e. from 2014 onwards). Please upgrade your git version. Alternatively raise an issue at https://github.com/jesseduffield/lazygit/issues for lazygit to be more backwards compatible.
> > PS C:\Users\User\Desktop> C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\JesseDuffield.lazygit_Microsoft.Winget.Source_8wekyb3d8bbwe\lazygit.exe -version
> > commit=16802a048e0425182f08cf0e9a2bc31480e9a55d, build date=2023-02-01T11:02:43Z, build source=binaryRelease, version=0.37.0, os=windows, arch=amd64, git version=
> > PS C:\Users\User\Desktop> &"C:\Program Files\Git\bin\git.exe" "-v"
> > git version 2.40.1.windows.1

**Comment by mloskot** [comment]
I shared the latest findings with Lazygit in https://github.com/jesseduffield/lazygit/issues/3099#issuecomment-1867890930

**Pull request closed without merging**
