### PR TITLE
Ubiquiti.UniFiNetworkController version 6.2.25

### PR DESCRIPTION
**Pull request by JackW6809**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15785)

### CODE REVIEW

**Comment by JackW6809** [comment]
I do not understand. There is no popup when I install it using `winget install --manifest C:\manifests\u\Ubiquiti\UniFiNetworkController\6.2.25` so what is going on?

**Comment by JackW6809** [comment]
Also I have verified the manifest etc.
```
PS C:\> winget validate --manifest C:\manifests\u\Ubiquiti\UniFiNetworkController\6.2.25
Manifest validation succeeded.
PS C:\> winget install --manifest C:\manifests\u\Ubiquiti\UniFiNetworkController\6.2.25
Found Ubiquiti UniFi Controller [Ubiquiti.UniFiNetworkController]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licences to, third-party packages.
Downloading https://dl.ubnt.com/unifi/6.2.25/UniFi-installer.exe
  ██████████████████████████████   154 MB /  154 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

**Comment by denelon** [comment]
@JackW6809, did you try in the SandBox? Sometimes this happens when you have a dependency on your system, and the SilentInstall doesn't get honored so a pop-up happens with the request to install a driver or some other dependency.

**Comment by JackW6809** [comment]
> @JackW6809, did you try in the SandBox? Sometimes this happens when you have a dependency on your system, and the SilentInstall doesn't get honored so a pop-up happens with the request to install a driver or some other dependency.

Apologies for the delay, I will check now.

**Comment by JackW6809** [comment]
> @JackW6809, did you try in the SandBox? Sometimes this happens when you have a dependency on your system, and the SilentInstall doesn't get honored so a pop-up happens with the request to install a driver or some other dependency.

Yeah, I just ran it and it has a dependency of Java,

**Comment by JackW6809** [comment]
Well, I just ran it in Sandbox and all it asked for was Java 8 and I added it to the dependencies list so not too sure on it. Obviously, I cannot get winget in Sandbox as far as I am aware so I am not able to test the manifest in a Sandbox environment.

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
PackageDependencies isn't currently implemented into the validation pipelines yet.

For now, you can set this PR to DRAFT until it's implemented and supported by the validation pipelines.

**Pull request closed without merging**
