### PR TITLE
Add MEGASync

### PR DESCRIPTION
**Pull request by javiergualix**
Solves package request #793 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/804)

### CODE REVIEW

**Comment by LukasNespor** [comment]
Blocked by #91

**Comment by NathanBnm** [comment]
This is duplicate of #616 Please search for duplicates before submitting PRs

**Comment by KevinLaMS** [comment]
Duplicate of #1620

**Pull request closed without merging**
