### PR TITLE
Chase Package

### PR DESCRIPTION
**Pull request by frypan05**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---
A simple command-line application that provides you relevant research paper analysis from different sites right from your terminal. This is highly beneficial for researchers as they do not need to search up for a particular topic related to their research and waste their time. However, they can access it all from their cmd.
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164393)

### CODE REVIEW

**Comment by frypan05** [comment]
@microsoft-github-policy-service agree

**Comment by frypan05** [comment]
@microsoft-github-policy-service agree


Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by stephengillie** [comment]
Hi @frypan05,

This doesn't seem to be the typical singlet or multi-file manifest:
image

Please check the [manifest schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0) for more details.

**Pull request closed without merging**
