### PR TITLE
New Package: CXWorld.CapFrameX version 1.7.2

### PR DESCRIPTION
**Pull request by og-mrk**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/147069)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @og-mrk,

This application installs and launches normally, but doesn't seem to present any interface once launched. The `InstallationNotes` recommend installing the full version, to ensure all dependencies are installed. 

>   - To use the portable version you have to install the standard version on your system once to ensure all frameworks are installed.

Is this package missing a dependency?

**Comment by og-mrk** [comment]
> Hi @og-mrk,
> 
> This application installs and launches normally, but doesn't seem to present any interface once launched. The `InstallationNotes` recommend installing the full version, to ensure all dependencies are installed. 
> 
> >   - To use the portable version you have to install the standard version on your system once to ensure all frameworks are installed.
> 
> Is this package missing a dependency? 

This's for the portable (.zip) edition of this program, while the one used is the installer. Of course, these installation notes were from their official download page for this package, and as far as I can tell, the program installs successfully.

To not confuse the user in the future, I'll remove this point, as it's not relevant to this edition of the progam (installer edition).

**Comment by stephengillie** [comment]
> Hi @og-mrk,
> 
> This application installs and launches normally, but doesn't seem to present any interface once launched. 
> 
> Is this package missing a dependency?

**Comment by og-mrk** [comment]
> > Hi @og-mrk,
> > This application installs and launches normally, but doesn't seem to present any interface once launched.
> > Is this package missing a dependency?

Hello @stephengillie
It looks like CapFrameX runs another process and exits, **_see screenshot below for context_**.

image

**Comment by stephengillie** [comment]
I'm not seeing that window at all. The installer also installs an application called PresentMon, and double-clicking this also has no effect, after accepting the UAC prompt.

**Comment by og-mrk** [comment]
> I'm not seeing that window at all. The installer also installs an application called PresentMon, and double-clicking this also has no effect, after accepting the UAC prompt.

Hello @stephengillie
I've looked into PresentMon, and it turns out to be like a Backend Tool other programs (Like CapFrameX) can utilize it's High-Performance Analyses features, here's the [GitHub Page for PresentMon](https://github.com/GameTechDev/PresentMon)

In this case, PresentMon is a program that's not designed to be ran directly by users, but in-directly using GUI Apps like CapFrameX, Guru3D RTSS RivaTuner Statistics Server, and other similar programs...

**Comment by stephengillie** [comment]
All of these are backend tools - should they have a dependency on a front-end tool for display? If not it's okay.

**Comment by stephengillie** [comment]
Verify: 
image

**Review by stephengillie — APPROVED** [review]

**Comment by og-mrk** [comment]
> All of these are backend tools - should they have a dependency on a front-end tool for display? If not it's okay.

I don't think so, may be someone more experience with such tools can correct me.

> Edit:
> 
> > Overlay provided by Rivatuner Statistics Server.
> 
> Should `Guru3D.RTSS` be a dependency?

The installer should be a standalone one, _This is when I've tested it on machine_, so it'll extract and install all the necessary components that CapFrameX might require.

**Pull request merged**
