### PR TITLE
New package: Unity.Unity.6000.WindowsServer version 6000.0.1f1

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings).
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/153360)

### CODE REVIEW

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/pull/153347#issuecomment-2108338347

**Comment by stephengillie** [comment]
This package doesn't appear to have installed anything - only the dependency is installed. I ddin't closely examine the other PRs (similar to this) that I approved, as I thought they were some type of variation that I wasn't noticing. But now I realize that it was just the dependency each time.

**Comment by SpecterShell** [comment]
> This package doesn't appear to have installed anything - only the dependency is installed. I ddin't closely examine the other PRs (similar to this) that I approved, as I thought they were some type of variation that I wasn't noticing. But now I realize that it was just the dependency each time.

All these packages are installed to the directory of the main editor (`Unity.Unity.6000`) and they don't write ARP entries. The installation will fail if they can't detect the corresponding version of the main editor.

**Comment by SpecterShell** [comment]
@stephengillie

**Comment by stephengillie** [comment]
I saw that error pop up, but I thought it was an application error during the "launch all EXEs" part of validation. Not all EXEs are meant to be run, so sometimes this creates odd errors. Now I understand that it was the installer failing to run. 

> All these packages are installed to the directory of the main editor (Unity.Unity.6000) and they don't write ARP entries. 

Running manually, it asks for an install location, without giving the same helpful tips as you provided: 
image

> The installation will fail if they can't detect the corresponding version of the main editor.
> 
> image

And this occurs even with the interactive installer: 
image

However, installing to the Unity folder gives a message more in-line with expectations: 
image
- This pacakge appears to be tied to a specifc version of the dependency. I don't see a way to gate the installed dependency in the [schema](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.6.0/installer.md). 

Going back to the silent installer, [official docs](https://docs.unity3d.com/Manual/InstallingUnity.html) confirm `/S` for silent, and give`/D=C:\path\to\Unity` as the syntax to specify install location, with a default location of `C:\Program Files\Unity`. But in testing, I couldn't get this switch to work - it gave the error every time:

image

The example doesn't have any spaces in the name, but this does, and I'm wondering if this is why it's failing.

- Is it possible to install Unity to the "default location" of `C:\Program Files\Unity`? Is it possible to set its installer location? It might be an easier way to solve this problem.
- Is there another way to specify the path? I tried wrapping with quotes but I feel like these were ignored. Is there another way to wrap it so the spaces will get passed to the installer instead of parsed out by the console host?

**Comment by SpecterShell** [comment]
> I saw that error pop up, but I thought it was an application error during the "launch all EXEs" part of validation. Not all EXEs are meant to be run, so sometimes this creates odd errors. Now I understand that it was the installer failing to run.
> 
> > All these packages are installed to the directory of the main editor (Unity.Unity.6000) and they don't write ARP entries.
> 
> Running manually, it asks for an install location, without giving the same helpful tips as you provided: image
> 
> > The installation will fail if they can't detect the corresponding version of the main editor.
> > image
> 
> And this occurs even with the interactive installer: image
> 
> However, installing to the Unity folder gives a message more in-line with expectations: image
> 
>     * This pacakge appears to be tied to a specifc version of the dependency. I don't see a way to gate the installed dependency in the [schema](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.6.0/installer.md?rgh-link-date=2024-05-17T00%3A47%3A05Z).
> 
> 
> Going back to the silent installer, [official docs](https://docs.unity3d.com/Manual/InstallingUnity.html) confirm `/S` for silent, and give`/D=C:\path\to\Unity` as the syntax to specify install location, with a default location of `C:\Program Files\Unity`. But in testing, I couldn't get this switch to work - it gave the error every time:
> 
> image
> 
> The example doesn't have any spaces in the name, but this does, and I'm wondering if this is why it's failing.
> 
>     * Is it possible to install Unity to the "default location" of `C:\Program Files\Unity`? Is it possible to set its installer location? It might be an easier way to solve this problem.
> 
>     * Is there another way to specify the path? I tried wrapping with quotes but I feel like these were ignored. Is there another way to wrap it so the spaces will get passed to the installer instead of parsed out by the console host?

The installer requires exactly the same version of the main editor (`Unity.Unity.6000`). When the same version of the main editor is installed, the installer will be able to locate it automatically and the path will pop up in the textbox without specifying. However, when a different version is installed, the installer just simply ignores it and that textbox will remain blank.

Currently the `MinimumVersion` is set and automatically updated so the main editor will be updated if it has a lower version. There is no equivalent like `MaximumVersion` though.

Animation

**Comment by stephengillie** [comment]
This implies that - since the dependency version has increased from "`1f11`" to "`2f11`", that this PR won't validate correctly. Since it can't get its same version dependency. And that this PR should be closed in favor of version  "`2f11`"  of this package.

**Pull request closed without merging**
