### PR TITLE
Update: Posit.Positron version 2024.07.0 (2024.07.0-107)

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#6943](https://github.com/SpecterShell/Dumplings/actions/runs/10139697535).

<details>

<summary>Log</summary>

````
Updated: 2024.07.0-100 → 2024.07.0-107
Submitting WinGet manifests
Found existing pull requests:
Update: Posit.Positron version 2024.07.0 (2024.07.0-100) - https://github.com/microsoft/winget-pkgs/pull/164700
Update: Posit.Positron version 2024.07.0 (2024.07.0-97) - https://github.com/microsoft/winget-pkgs/pull/164517
Update: Posit.Positron version 2024.07.0 (2024.07.0-95) - https://github.com/microsoft/winget-pkgs/pull/164334
The existing pull requests are ignored as the version is updated while the real version isn't
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/165070)

### CODE REVIEW

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/pull/165222#issuecomment-2261372683

**Comment by SpecterShell** [comment]
> [#165222 (comment)](https://github.com/microsoft/winget-pkgs/pull/165222#issuecomment-2261372683)

I've closed another one.

**Comment by SpecterShell** [comment]
@stephengillie https://github.com/microsoft/winget-pkgs/pull/165070#issuecomment-2261662365

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
