### PR TITLE
Move: ZeroTier.ZeroTierOne

### PR DESCRIPTION
**Pull request by quhxl**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/24032)

### CODE REVIEW

**Comment by quhxl** [comment]
zerotier/ZeroTierOne#1392

I think this is back.

**Comment by ItzLevvie** [comment]
It seems to be stuck on this prompt for me:
image

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
image

**Comment by quhxl** [comment]
[#24032 (comment)](https://github.com/microsoft/winget-pkgs/pull/24032#issuecomment-894218111)

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Please double-check that the `InstallerSwitches` are correct.

It seems to be installing fully unattended OOB without any prompts when winget-cli runs the `.msi` installer with `/quiet` switch:
image

**Comment by quhxl** [comment]
349a722960f018b8599b87fb948096635b6036d2 should then not have displayed any errors.

**Comment by quhxl** [comment]
It seems that it is only displayed at silentWithProgress. I'll try this...

**Comment by quhxl** [comment]
Now it installs unattended....

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Oops, hold on, winget-cli doesn't actually run `.msi` installers with `/quiet`, it runs it with `/passive` by default which is the progress bar. The issue is fixed with `/quiet` (or `--override "/quiet"` if using `winget install --manifest <PATH>`) as a switch.

You most likely need to add:
```yaml
  InstallerSwitches:
    Silent: /quiet
```

If that doesn't work there's nothing we moderators or administrators can do to solve this issue, other than making an issue over at their issue tracker to allow the application to be installed from Windows Package Manager, since they're actively working on the next major version ZeroTierOne v2.0.0, they probably won't fix that.

**Comment by quhxl** [comment]
Since we don't know how the pipline works exactly, I didn't know that the bot checks with /passive despite the fact that a silentWithProgress installation is not specified in the InstallModes.

**Comment by ItzLevvie** [comment]
It doesn't look like `InstallModes` does anything in winget-cli - from https://github.com/microsoft/winget-pkgs/pull/16994/files#r649564695.

image

**Review by OfficialEsco — APPROVED** [review]
@quhxl i've warned you about this before 😁 Which is why i was surprised the PR i gave you the warning on passed 

> It doesn't look like `InstallModes` does anything in winget-cli - from https://github.com/microsoft/winget-pkgs/pull/16994/files#r649564695.

Also this installer seems to require CMD to be run as Administrator which is a flag we need to add whenever that gets added

```
Manifest validation succeeded.
Found ZeroTier One [ZeroTier.ZeroTierOne]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.zerotier.com/RELEASES/1.6.5/dist/ZeroTierOne.msi
  ██████████████████████████████  15.9 MB / 15.9 MB
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1603
Installer log is available at: C:\Users\Esco\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-ZeroTier.ZeroTierOne.1.6.5-2021-08-16-21-31-33.851.log
Press any key to continue . . .
```

image

**Comment by denelon** [comment]
@quhxl the "InstallModes" was added so we could begin to start filtering applications based on preferences / requirements. We have been requiring silent / silent with progress for all packages to date. This is primarily to support unattended install / import scenarios. Once we have added the behavior for the client to be able to filter packages based on install modes, we can start letting "interactive" installers into the repository and build the rest of the behavior for users to be able to ignore "interactive" only installers.

**Pull request merged**
