### PR TITLE
New version: Kubernetes.kind version 0.21.0

### PR DESCRIPTION
**Pull request by ste93cry**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137682)

### CODE REVIEW

**Comment by ste93cry** [comment]
@stephengillie can you please help me troubleshoot the problem?

**Comment by stephengillie** [comment]
> @stephengillie can you please help me troubleshoot the problem?

Hi @ste93cry,

This error indicates an issue with our pipeline, and doesn't reflect on the package.

**Comment by ste93cry** [comment]
Ok, thanks for letting me know!

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
