### PR TITLE
New package Cretezy.lazyjj at v0.1.1

### LINKED ISSUE #154889: [Package Request]: Cretezy.lazyjj at version 0.1.1
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/Cretezy/lazyjj/releases
Publisher: Cretezy
Package Name: Cretezy.lazyjj
Description: TUI for Jujutsu/jj. Built in Rust with Ratatui. Interacts with jj CLI.
Package Version: 0.1.1
Installer URL: https://github.com/Cretezy/lazyjj/releases/download/v0.1.1/lazyjj-v0.1.1-x86_64-pc-windows-msvc.zip

### PR DESCRIPTION
**Pull request by RoscoP**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? Closes #154889

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/154892)

### CODE REVIEW

**Comment by Cretezy** [comment]
Hi! I'm the author of the original package, however I am not a regular Windows user.

How can I get this validation error to pass?

**Comment by RoscoP** [comment]
@Trenly - Looking at the details, it isn't clear why it is failing:
[validation failure](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=574815&view=logs&jobId=68997d86-8ece-5ae8-3ac5-ccdbfa458731&j=68997d86-8ece-5ae8-3ac5-ccdbfa458731&t=b79910ce-dca5-5e27-ad7f-bd285eecb5a2)

Log doesn't really give any reasons for the failure, so not sure what to fix.  Installing locally works, running from `tools/sandboxtest.ps1` also passed correctly when I did it.  Any guidance on what to do next?
```
5/23/2024 7:33:35 PM

****************************************************************************************
Installation Verification
****************************************************************************************

-----------------------------------------------------
Result: Failed
-----------------------------------------------------
Status: Completed

```

**Comment by Trenly** [comment]
> @Trenly - Looking at the details, it isn't clear why it is failing: [validation failure](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=574815&view=logs&jobId=68997d86-8ece-5ae8-3ac5-ccdbfa458731&j=68997d86-8ece-5ae8-3ac5-ccdbfa458731&t=b79910ce-dca5-5e27-ad7f-bd285eecb5a2)
> 
> Log doesn't really give any reasons for the failure, so not sure what to fix. Installing locally works, running from `tools/sandboxtest.ps1` also passed correctly when I did it. Any guidance on what to do next?
> 
> ```
> 5/23/2024 7:33:35 PM
> 
> ****************************************************************************************
> Installation Verification
> ****************************************************************************************
> 
> -----------------------------------------------------
> Result: Failed
> -----------------------------------------------------
> Status: Completed
> ```

@RoscoP - You can get more detailed logs by going to the artifacts of the validation run in the pipelines and downloading the InstallerValidationLogs. 

In this case the client showed that the installer failed a security check as I posted above. This means that Windows Defender believes the URL is not proven to be safe (yet). This specific error of "Installer failed security check" usually only lasts a day or two - so we will try re-running the validation periodically. If it doesn’t clear up, then the next step is to report the URL as safe to Microsoft Defender using their URL False positive report form

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-24 09:31:12.226 [FAIL] Installer failed security check. Url: https://github.com/Cretezy/lazyjj/releases/download/v0.1.1/lazyjj-v0.1.1-x86_64-pc-windows-msvc.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Hi @RoscoP,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-28 07:46:00.301 [FAIL] Installer failed security check. Url: https://github.com/Cretezy/lazyjj/releases/download/v0.1.1/lazyjj-v0.1.1-x86_64-pc-windows-msvc.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 881.)

**Comment by RoscoP** [comment]
Inspected the validation logs, and it appears to still be failing based on failing the security check.  @Trenly suggested:
> If it doesn’t clear up, then the next step is to report the URL as safe to Microsoft Defender using their URL False positive report form.

I found the MS site to report false positives, but it is asking for information (detection name and version), but I didn't see that information in the validation run output, and my local Defender didn't complain when I ran it.  Any suggested next steps?

**Comment by stephengillie** [comment]
Sometimes it just takes time - I believe Defender teams have automated processes which sometimes install packages into a VM and let it sit for a while, to ensure there is no "time-release malware" involved. I think maybe it became passable after the last run, then you checked and got a good response, then we did too just now. It's the downside to waiting 18 hours between checks.

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-05-29 11:02:09.772 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD875574CC: (caller: 00007FFD8755E129) Exception(1) tid(560) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-29 11:02:09.778 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD875574CC: (caller: 00007FFD8755E129) Exception(2) tid(560) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-29 11:02:09.783 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD875574CC: (caller: 00007FFD8755E129) Exception(3) tid(560) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-29 11:02:09.787 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD875574CC: (caller: 00007FFD8755E129) Exception(4) tid(560) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-29 11:02:09.794 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD875574CC: (caller: 00007FFD8755E129) Exception(5) tid(560) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-29 11:02:09.798 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD875574CC: (caller: 00007FFD8755E129) Exception(6) tid(560) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-29 11:02:09.802 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD875574CC: (caller: 00007FFD8755E129) Exception(7) tid(560) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-29 11:02:09.808 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD875574CC: (caller: 00007FFD8755E129) Exception(8) tid(560) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-29 11:02:09.818 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD875574CC: (caller: 00007FFD8755E129) Exception(9) tid(560) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-29 11:02:09.847 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD875574CC: (caller: 00007FFD8755E129) Exception(10) tid(560) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-29 11:02:09.851 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD875574CC: (caller: 00007FFD8755E129) Exception(11) tid(560) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-29 11:02:09.867 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD875574CC: (caller: 00007FFD8755E129) Exception(12) tid(560) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-29 11:02:09.876 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD875574CC: (caller: 00007FFD8755E129) Exception(13) tid(560) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-29 11:02:09.885 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD875574CC: (caller: 00007FFD8755E129) Exception(14) tid(560) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-29 11:02:09.957 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\Schema\1_0\Interface_1_0.cpp(197)\WindowsPackageManager.dll!00007FFD875574CC: (caller: 00007FFD8755E129) Exception(15) tid(560) 800700B7 Cannot create a file when that file already exists. 
> 2024-05-29 11:02:27.576 [FAIL] Installer failed security check. Url: https://github.com/Cretezy/lazyjj/releases/download/v0.1.1/lazyjj-v0.1.1-x86_64-pc-windows-msvc.zip Result: 0x80004005 [206C:204C][
> 2024-05-29T11:02:20]w363: Could not create system restore point, error: 0x80070422. Continuing... MSI (s) (60:44) [11:02:21:519]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.38.33135. Product Version: 14.38.33135. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (60:40) [11:02:21:972]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Additional Runtime - 14.38.33135. Product Version: 14.38.33135. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0.

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Hi @RoscoP,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Verify: 
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
