### PR TITLE
YggdrasilNetwork.Yggdrasil version 0.5.6

### PR DESCRIPTION
**Pull request by SNMetamorph**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/157562)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Installer https://github.com/yggdrasil-network/yggdrasil-go/releases/download/v0.5.6/yggdrasil-0.5.6-arm.msi
 Scan request id: 'c5dfc42f-9d1c-4bd3-98cc-236c22c5dc78'
 
 Installer https://github.com/yggdrasil-network/yggdrasil-go/releases/download/v0.5.6/yggdrasil-0.5.6-x64.msi
 Scan request id: 'ea740249-c335-4753-a4a0-23a58faf3c15'
 Error information: BlockingDetectionFound
 Installer https://github.com/yggdrasil-network/yggdrasil-go/releases/download/v0.5.6/yggdrasil-0.5.6-x86.msi
 Scan request id: 'ad2c8fc1-1098-41c7-8532-437625ca672f'
 
 Installer https://github.com/yggdrasil-network/yggdrasil-go/releases/download/v0.5.6/yggdrasil-0.5.6-arm64.msi

(Automated response - build 885.)

**Comment by stephengillie** [comment]
This might be due to a network block of data centers, to prevent automated downloads.

(Automated response - build 885.)

**Comment by SNMetamorph** [comment]
> This might be due to a network block of data centers, to prevent automated downloads.

For what purpose GitHub can block downloads for CI workflows running on Azure? This isn't seems logical, so I think we just need to restart checks.

**Comment by stephengillie** [comment]
Hi @SNMetamorph,

My script matched `BlockingDetectionFound` in the logs and applied the message and label based on this. The scenario you describe does seem unusual, but not unheard of.

**Comment by SNMetamorph** [comment]
Ok, I think we should trying again until it worked

**Comment by SNMetamorph** [comment]
bump

**Comment by SNMetamorph** [comment]
bump

**Pull request closed without merging**
