### PR TITLE
New version  Microsoft.PowerShell version 7.3.5.0

### PR DESCRIPTION
**Pull request by mrjcap**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/110820&drop=dogfoodAlpha

### CODE REVIEW

**Review by jedieaston — APPROVED** [review]

**Comment by anamnavi** [comment]
Hi, I'm from the PowerShell team and I'm opening a PR for this that also has support for other architectures (arm). It would be best if we can take that one into master. Thank you for creating this and the time put in though :)

**Comment by stephengillie** [comment]
@anamnavi is this okay to merge?

**Comment by anamnavi** [comment]
@stephengillie can we merge this PR I've linked instead: https://github.com/microsoft/winget-pkgs/pull/110847
It's got entries for the arm msix packages (again a temporary solution for us to support arm)

**Comment by mrjcap** [comment]
> Hi, I'm from the PowerShell team and I'm opening a PR for this that also has support for other architectures (arm). It would be best if we can take that one into master. Thank you for creating this and the time put in though :)
> 
> #110847

Sure thing. I'll go ahead and close this one. At the time there were no msixbundles available. :)

**Pull request closed without merging**
