### PR TITLE
Update manifest: DuckStudio.FufuDevTools version 2024.06.24.2036

### PR DESCRIPTION
**Pull request by fjwxzde**
Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

* 移除一些不必要的项
* 修改一些项
* 添加`x86`安装程序

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/175258)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 896.)

**Comment by stephengillie** [comment]
Hi @fjwxzde,

This package is on an informal restricted list of submitters. If you're working with this developer and will frequently be modifying these manifests, then we should get the developer's approval to add you to this list of submitters.

**Comment by DuckDuckStudio** [comment]
> Also, should @fjwxzde be added to the Auth.csv approval list? So that she can make these changes without your approval?
> 另外，是否应该添加到Auth.csv批准列表中？这样她就可以在未经您批准的情况下进行这些更改？

If Auth.csv can add more than one approver(?), please add the following to all of my programs:
Luna-Grace, fjwxzde, DuckDuckStudio

My programs:
DuckStudio.FufuTools
DuckStudio.FufuDevTools
DuckStudio.ChineseGit
DuckStudio.GitHubLabelsManager

Thanks.

**Comment by stephengillie** [comment]
This is complete. https://github.com/stephengillie/winget-pkgs/commit/aba249105c45b25808476c9de54415ab3985de48

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
