### PR TITLE
New package: EagleDynamics.DCSWorldOpenBeta version 2.9

### LINKED ISSUE #113847: [Package Request]: EagleDynamics.DCSWorldOpenBeta
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.digitalcombatsimulator.com/en/downloads/world/beta/
Publisher: Eagle Dynamics
Package Name: DCS World Open Beta
Description: A free-to-play digital battlefield game and simulation environment. Open Beta branch.
Package Version: 2
Installer URL: https://www.digitalcombatsimulator.com/upload/iblock/722/10xqudpzyvruo62jw9830unu8qst3kes/DCS_World_OpenBeta_web.exe

This is the exact same configuration as this previous package, but for the Open Beta branch. All yaml besides the above differences and the installer hash can be directly copied from the Stable branch (`EagleDynamics.DCSWorld`).
https://github.com/microsoft/winget-pkgs/pull/32803#issue-1038088297

### PR DESCRIPTION
**Pull request by Dragon1573**
## Description

- Resolve https://github.com/microsoft/winget-pkgs/issues/113847

## Checks

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/123975)

### CODE REVIEW

**Comment by Dragon1573** [comment]
Can't figure out why there's a `Validation-Domain` error. 😕

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Made an error in approving this, as it did not fully install in a VM: 
image

**Comment by Dragon1573** [comment]
> Made an error in approving this, as it did not fully install in a VM.

This is an online installer of the main application of DCSWorld, very similar to Visual Studio Installer (for installing VSIDE online).

The main application of DCSWorld has a massive size up to 160GB. I think its too large installing in a cloud-based, test-only VM.

**Comment by Dragon1573** [comment]
This package is intended to only install the "online installer". After the online installer is successfully installed and configured, user should install the main application by that installer.

**Pull request merged**
