### PR TITLE
New version: JohnTaylor.less version 608

### PR DESCRIPTION
**Pull request by jftuga**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/78896)

### CODE REVIEW

**Review by Trenly — APPROVED** [review]

**Comment by Trenly** [comment]
```
2022-09-07 14:28:35.394 [FAIL] Installer failed security check. Url: https://github.com/jftuga/less-Windows/releases/download/less-v608/less.exe Result: 0x80004005
```

**Comment by Trenly** [comment]
```
2022-09-07 14:28:35.394 [FAIL] Installer failed security check. Url: https://github.com/jftuga/less-Windows/releases/download/less-v608/less.exe Result: 0x80004005
```

**Comment by sitiom** [comment]
@Trenly what does that mean?

**Review by ghost — APPROVED** [review]

**Pull request merged**
