### PR TITLE
New Version: Samsung.SamsungMagician version 8.1.0

### PR DESCRIPTION
**Pull request by og-mrk**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/148013)

### CODE REVIEW

**Comment by og-mrk** [comment]
> Hello @og-mrk,
> 
> The package manager bot determined there was an issue with one of the installers listed in the url field, and cannot continue.
> 
> The application included in this pull request failed to install during dynamic validation. This test is designed to ensure that the application installs on all environments without warnings. Please, verify that the application installs correctly on architectures specified in the manifest using winget cli.
> 
> Template: msftbot/validationError/installers/shellExecute
> 

I really can't see why this would happen. Any info/logs would help.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-04-06 10:47:48.402 [CORE] DeliveryOptimization error: 0x80072f76, extended error: 0x00000000
> 2024-04-06 10:47:48.497 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!54A557EB: (caller: 54A55E1C) Exception(1) tid(e60) 80072F76 
> 2024-04-06 10:49:10.683 [CLI ] ShellExecute installer failed: 1
> 2024-04-06 10:48:51.632   Function name: GetLastError
> 2024-04-06 10:49:08.679   Got EAbort exception.

(Automated response - build 876.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-04-08 12:51:49.593   De
> Faulting to 0 for suppressed message box (OK):                           Samsung Magician cannot be installed in silent mode. Remove silent mode and retry. 
> 2024-04-08 12:51:49.593   InitializeSetup returned False; aborting. 
> 2024-04-08 12:51:49.593   Got EAbort exception. 
> 2024-04-08 12:51:49.593   Deinitializing Setup. 
> 2024-04-08 12:51:51.249   Log closed.

(Automated response - build 876.)

**Comment by og-mrk** [comment]
Hello @stephengillie
Thanks for the info, may I ask if it's possible to have an Interactive Only installer in WinGet Packages Repo?

If not, Guess I would be out of luck. Unless I _or anyone interested_, finds a way to install it silently, or contact / ask the Program Authors (In this case it's Samsung) to provide a way to install it silently, which's something out of my reach, both in time & effort, and the possibility for this to happen (They can simply deny my request, which's in their right to do so).

Anyhow, if this PR didn't go through the Validation Pipeline (which's very likely to happen)... Then my bad for wasting your time in this PR, and thanks for your help.

**Comment by stephengillie** [comment]
We're hopeful to have an interactive-installer switch at some point, but this work appears to be is lower priority than other work. That switch wouldn't automate the installer, but would only notify the user to expect to click "Next" several times and then "Finish".

**Comment by og-mrk** [comment]
After taking a further look into this specific package, I've noticed multiple issues requesting an update (https://github.com/microsoft/winget-pkgs/issues/121594 & https://github.com/microsoft/winget-pkgs/issues/145127) and a previous PR trying to update it (https://github.com/microsoft/winget-pkgs/pull/134001), all of which could not be possible because Interactive Only Installation isn't possible at the time of writing this comment (see [this issue](https://github.com/microsoft/winget-cli/issues/823) from winget-cli repo for further reading), and like what @stephengillie have mentioned, this feature/improvement is of lower priority, so it'll take some time before it's available.

will convert this PR to draft for the time being.

**Comment by og-mrk** [comment]
> Hello @og-mrk,
> 
> This pull request has been automatically marked as stale because it has been marked as requiring author feedback but has not had any recent activity. It will be closed if no further activity occurs **within 3 days of this comment**.
> 
> Template: msftbot/noRecentActivity
> 

As I've previously explained, this PR will remain as a draft until one of two things happens, either the creators add silent installation support to the Installer of this program, or WinGet support Interactive Only Installers.

Which, _at the time of writing_, none of the previous two has happened.

**Pull request closed without merging**
