### PR TITLE
New version: ItsSim.fsolauncher version 1.8.1

### LINKED ISSUE #25500: Automation has determined ItsSim.fsolauncher 1.7.7 is unavailable
The URL for version 1.7.7 of ItsSim.fsolauncher has been unavailable for 5 or more days.
This package may be removed from the repository if no valid manifest is available in the next 14 days.

If the installer has been moved, please update the manifest with the new URL. If a new version of the package is available, please create a new manifest with the valid URL, version, and SHA256 hash.
If this package is no longer available, please delete the manifest.

```

```

### PR DESCRIPTION
**Pull request by OfficialEsco**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Resolves #25500
image

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/25586)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Ahaaaa this is why the bot thinks the link dosn't work

```
URI: https://freeso.org, Validation result: Failed, Http status code: ServiceUnavailable 
URI: https://github.com/riperiperi/FreeSO/issues, Validation result: Passed
URI: https://freeso.org, Validation result: Failed, Http status code: ServiceUnavailable 
URI: https://raw.githubusercontent.com/riperiperi/FreeSO/master/LICENSE.md, Validation result: Passed
URI: https://raw.githubusercontent.com/riperiperi/FreeSO/master/LICENSE.md, Validation result: Passed
URI: https://beta.freeso.org/FreeSO%20Launcher%20Setup.exe, Validation result: Failed, Http status code: ServiceUnavailable 
```

**Review by ItzLevvie — DISMISSED** [review]
image

**Comment by arjun-msft** [comment]
I'm seeing an "Installer hash does not match" error for this, can you double check the url?

**Comment by OfficialEsco** [comment]
```
URI: https://freeso.org, Validation result: Failed, Http status code: ServiceUnavailable 
URI: https://github.com/riperiperi/FreeSO/issues, Validation result: Passed
URI: https://freeso.org, Validation result: Failed, Http status code: ServiceUnavailable 
URI: https://raw.githubusercontent.com/riperiperi/FreeSO/master/LICENSE.md, Validation result: Passed
URI: https://raw.githubusercontent.com/riperiperi/FreeSO/master/LICENSE.md, Validation result: Passed
URI: https://beta.freeso.org/FreeSO%20Launcher%20Setup.exe, Validation result: Failed, Http status code: ServiceUnavailable
```

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
