### PR TITLE
New version: jftuga.less version 668

### PR DESCRIPTION
**Pull request by jftuga**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/184031)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-10-17 19:17:09.157 [FAIL] Installer failed security check. Url: https://github.com/jftuga/less-Windows/releases/download/less-v668/less-x64.zip Result: 0x80004005
> 2024-10-17 19:11:18.298 [FAIL] Installer failed security check. Url: https://github.com/jftuga/less-Windows/releases/download/less-v668/less-x86.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Comment by sitiom** [comment]
Works for me:
image

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-10-21 09:16:29.081 [FAIL] Installer failed security check. Url: https://github.com/jftuga/less-Windows/releases/download/less-v668/less-x86.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
