### PR TITLE
Nelson 0.5.4

### PR DESCRIPTION
**Pull request by Nelson-numerical-software**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/11504)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
@Nelson-numerical-software when you get a error you can check the issue by going to [Checks](https://github.com/microsoft/winget-pkgs/pull/11504/checks) tab -> [View more details on Azure Pipelines](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=159388&view=results) and follow the errors.

I didn't get to see the `Manifest Validation Errors` so i'm not sure where the problem is, but its probably some string in the yaml or the file name. However on the last one the WinGetbot failed.

I can submit the PR if you'd like?

**Comment by Nelson-numerical-software** [comment]
> @Nelson-numerical-software when you get a error you can check the issue by going to the [Checks](https://github.com/microsoft/winget-pkgs/pull/11504/checks) tab -> [View more details on Azure Pipelines](https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=159388&view=results) and follow the errors.
> 
> I didn't get to see the `Manifest Validation Errors` so i'm not sure where the problem is, but its probably some string in the yaml or the file name. However on the last one the WinGetbot failed.
> 
> I can submit the PR if you'd like?

Hi,
It seems that you push often in winget-pkgs repository :)
Do not hesitate to update PR to push Nelson.
Thanks for your help !

**Comment by OfficialEsco** [comment]
PR Submited, happy to help :) The move from Single manifest to Multi manifest in v1.0.0 is a bit weird and confusing, should go smoothly once the multimanifest gets merged :)
I also noticed its getting blocked by Smartscreen right now, but it will probably get approved by a few hours.

**Comment by Nelson-numerical-software** [comment]
Thanks to @OfficialEsco  for your help
merged in another PR

**Pull request closed without merging**
