### PR TITLE
VapourSynth.VapourSynth version R54

### PR DESCRIPTION
**Pull request by SpecterShell**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/25004)

### CODE REVIEW

**Comment by SpecterShell** [comment]
Well, the installation would be stucked if no python is installed.🤔

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
And this is why you test the pacakge
image

But your right about this
image

```
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Python.Python.3
    MinimumVersion: 3.9
```

Requires microsoft/winget-cli#163

**Comment by SpecterShell** [comment]
> And this is why you test the pacakge
> image
> 
> But your right about this
> image
> 
> ```
> Dependencies:
>   PackageDependencies:
>   - PackageIdentifier: Python.Python.3
>     MinimumVersion: 3.9
> ```
> 
> Requires [microsoft/winget-cli#163](https://github.com/microsoft/winget-cli/issues/163)

The first messagebox can be suppressed by passing `/SUPPRESSMSGBOXES`, and the installer will install for all users as default. However, VapourSynth can only be installed in the same scope as python. Since winget installs python3 in user scope, the installation will fail.
image

**Comment by OfficialEsco** [comment]
Python can be installed for current user and machine wide as specified in the Installer switches, VapourSynth can also be installed for current user and machine wide if you put it in the installer switches and correct scope.

**Pull request closed without merging**
