### PR TITLE
Remove: Epiforge.Grindstone

### PR DESCRIPTION
**Pull request by quhxl**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

screeen

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23510)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
no update?

**Comment by quhxl** [comment]
I tried to update (#23501), but then noticed that the package is completely broken.

**Review by OfficialEsco — APPROVED** [review]
No screenshots :c ill take your word on it 👍

**Comment by OfficialEsco** [comment]
Ahhhh i see, it has the 2 Bytes issue 🤦‍♂️

**Comment by ItzLevvie** [comment]
Looks like an issue between DO & WinINet. My VM is configured on WinINet:
image

Issue related to https://github.com/microsoft/winget-cli/issues/1261.

**Pull request merged**
