### PR TITLE
New Package tinygo-org.tinygo 0.27.0

### LINKED ISSUE #109049: [Package Request]: TinyGo
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://tinygo.org/getting-started/install/windows/
Publisher: The TinyGo Authors
Package Name: TinyGo
Description: TinyGo brings the [Go programming language](https://golang.org/) to embedded systems and to the modern web by creating a new compiler based on [LLVM](https://llvm.org/).
Package Version: 0.27.0
Installer URL: https://tinygo.org/getting-started/install/windows/

### PR DESCRIPTION
**Pull request by BrandonWanHuanSheng**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

Resolves #109049

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/109060)

### CODE REVIEW

**Review by Trenly — APPROVED** [review]

**Comment by BrandonWanHuanSheng** [comment]
Pull request will be marked as merge because there is a validation error in the pipelines.

**Comment by stephengillie** [comment]
> Stephengille Pull request will be marked as not merge because there is a validation-executable-error in the pipelines.

I believe this error might be due to the dependency.

**Comment by BrandonWanHuanSheng** [comment]
Ok.

**Comment by BrandonWanHuanSheng** [comment]
Another problem is the TinyGoRoot environment on the app which unable to set.

**Comment by BrandonWanHuanSheng** [comment]
Hmmmm....

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Exception during executable launch operation System.AggregateException: One or more errors occurred. (The system cannot find the file specified.)  ---
> System.ComponentModel.Win32Exception (2): The system cannot find the file specified. 
--- End of stack trace from previous location where exception was thrown ---    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

**Pull request merged**
