### PR TITLE
Add version: shirowanisan.COEIROINK version 1.0.1

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141294)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
URL: https://www.dropbox.com/s/1o6bzzyeo1euqwg/COEIROINK-CPU-v.1.0.1.zip?dl=1 
Status Code: 200

(Automated message - build 844)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335141
> 2024-02-28 02:25:22.641 [CORE] DeliveryOptimization error: 0x80190190, extended error: 0x00000000
> 2024-02-28 02:25:22.684 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFD67A4A465: (caller: 00007FFD67A4AD01) Exception(1) tid(450) 80190190 Bad request (400).

(Automated response - build 848.)

**Comment by stephengillie** [comment]
I worked on this last week, but forgot to hit "Comment": 
> The nested installer appears to be there - copy from Windows Explorer on top, copy from WinGet logs on bottom:
> 
> image
> 
> Maybe it's picky about the slash? 

Since then I tried reversing the slash, but this had no impact. I'm not seeing why the package manager can't find the nested installer.

**Pull request closed without merging**
