### PR TITLE
New version: KuaiFan.DooTask version 0.37.76

### PR DESCRIPTION
**Pull request by coolplaylinbot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/166342)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2145844844
> 2024-08-06 04:27:28.410 [CORE] DeliveryOptimization error: 0x80190194, extended error: 0x00000000
> 2024-08-06 04:27:28.444 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FF8BA36A465: (caller: 00007FF8BA36AD01) Exception(1) tid(90c) 80190194 Not found (404).
> 2024-08-06 04:27:29.066 [CORE] Download request failed. Returned status: 404
> 2024-08-06 04:27:29.066 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FF8BA3643D6: (caller: 00007FF8BA365C49) Exception(2) tid(90c) 80190194 Not found (404).
> 2024-08-06 04:27:29.295 [CLI ] Failed to download, waiting a bit and retry. Url: https://github.com/kuaifan/dootask/releases/download/v0.37.76/DooTask-v0.37.76-win-x64.exe
> 2024-08-06 04:27:32.010 [CORE] DeliveryOptimization error: 0x80190194, extended error: 0x00000000
> 2024-08-06 04:27:32.010 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FF8BA36A465: (caller: 00007FF8BA36AD01) Exception(3) tid(90c) 80190194 Not found (404).
> 2024-08-06 04:27:32.165 [CORE] Download request failed. Returned status: 404
> 2024-08-06 04:27:32.165 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FF8BA3643D6: (caller: 00007FF8BA365C49) Exception(4) tid(90c) 80190194 Not found (404).
> 2024-08-06 04:26:56.887 [CORE] DeliveryOptimization error: 0x80190194, extended error: 0x00000000
> 2024-08-06 04:26:56.950 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!565B57EB: (caller: 565B5E1C) Exception(1) tid(1698) 80190194 Not found (404).
> 2024-08-06 04:26:57.525 [CORE] Download request failed. Returned status: 404
> 2024-08-06 04:26:57.525 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!565AFA75: (caller: 565B0E2B) Exception(2) tid(1698) 80190194 Not found (404).
> 2024-08-06 04:26:57.726 [CLI ] Failed to download, waiting a bit and retry. Url: https://github.com/kuaifan/dootask/releases/download/v0.37.76/DooTask-v0.37.76-win.exe
> 2024-08-06 04:27:00.449 [CORE] DeliveryOptimization error: 0x80190194, extended error: 0x00000000
> 2024-08-06 04:27:00.449 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!565B57EB: (caller: 565B5E1C) Exception(3) tid(1698) 80190194 Not found (404).
> 2024-08-06 04:27:00.633 [CORE] Download request failed. Returned status: 404
> 2024-08-06 04:27:00.633 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!565AFA75: (caller: 565B0E2B) Exception(4) tid(1698) 80190194 Not found (404).

Automated error analysis suggests -2145844844 may mean Not Found (404).

Automated error analysis suggests 80190194 may mean Not found (404).

(Automated response - build 887.)

**Comment by stephengillie** [comment]
URL: https://github.com/kuaifan/dootask/releases/download/v0.37.76/DooTask-v0.37.76-win.exe 
OK

(Automated message - build 913)

**Comment by stephengillie** [comment]
Don't circumvent our automation please :)
CC @CoolPlayLin

**Comment by stephengillie** [comment]
Close with reason: Regenerate with new hash, and the newest version number.;

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
