### PR TITLE
New package: 4ngel2769.MessyOrganizer version 1.0.0-beta.1

### LINKED ISSUE #156594: [Package Request]: MessyFileOrganizer
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/4ngel2769/messy-file-organizer/releases
Publisher: 4ngel2769
Package Name: MessyFileOrganizer
Description: An application that sorts newly downloaded files into categories to fix your messy folders.
Package Version: 1.0.0
Installer URL: https://github.com/4ngel2769/messy-file-organizer/releases/latest/download/MessyFileOrganizer-setup-x64.exe

### PR DESCRIPTION
**Pull request by schembriaiden**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.2.1 :rocket:

Resolves: https://github.com/microsoft/winget-pkgs/issues/156594
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/156596)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 883.)

**Comment by stephengillie** [comment]
Verify: This is a tray-based application:
image
image
image

**Review by stephengillie — DISMISSED** [review]

**Comment by stephengillie** [comment]
Hi @vikingnope,

The Registry and application don't have `-beta.1` in the version. This seems like the full `1.0.0` release, not a beta release. Should the `PackageVersion` be updated?

**Comment by vikingnope** [comment]
I added a display version, don't know if that helps?

On GitHub it is still listed as beta

**Review by stephengillie — APPROVED** [review]

**Comment by 4ngel2769** [comment]
> Hi @vikingnope,
> 
> The Registry and application don't have `-beta.1` in the version. This seems like the full `1.0.0` release, not a beta release. Should the `PackageVersion` be updated?

Hello @stephengillie, the package is indeed in the full 1.0.0 release despite the `-beta.1`.

**Comment by 4ngel2769** [comment]
Hello again, @vikingnope @stephengillie
The release tags have been updated on github to 1.0.0

**Comment by vikingnope** [comment]
https://github.com/microsoft/winget-pkgs/pull/156801

**Pull request merged**
