### PR TITLE
Update D:\Git\winget-pkgs\manifests\s\stevencohn\OneMore\4.18

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/114111&drop=dogfoodAlpha

### CODE REVIEW

**Review by ImJoakim — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Manual Validation failed with:
> 10:52:27 AM: Product: OneMoreAddIn -- Error 1722. There is a problem with this Windows Installer package. A program run as part of the setup did not finish as expected. Contact your support personnel or package vendor.  
Action _92AF78F8_2EBA_4DB2_B799_F8741DC7E4C6, location: C:\Program Files (x86)\River\OneMoreAddIn\OneMoreSetupActions.exe, command: --install-activesetup 
10:52:27 AM: Application: OneMoreSetupActions.exe Framework Version: v4.0.30319 Description: The process was terminated due to an unhandled exception. Exception Info: System.NullReferenceException    
at OneMoreSetupActions.ActiveSetupAction.Install()    
at OneMoreSetupActions.Program.Main(System.String[])   
10:52:27 AM: The storage optimizer couldn't complete slab consolidation on (C:) because: The slab consolidation operation was aborted because an insufficient number of slabs could be reclaimed (based on the limits specified in the registry). (0x89000028)

**Pull request merged**
