### PR TITLE
Delete manifests/f/FredEmmott/OpenKneeboard directory

### PR DESCRIPTION
**Pull request by fredemmott**
I'm unwilling to use winget-releaser [without more transparency for updates](https://github.com/vedantmgoyal2009/winget-releaser/issues/291); as OpenKneeboard has its' own auto-updater, I don't get enough value from WinGet to maintain this manually.

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] **n/a** Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] **n/a** Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] **n/a** Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140999)

### CODE REVIEW

**Comment by fredemmott** [comment]
@mdanish-kh if you've a the script handy already, that'd be great - thanks!

**Comment by mdanish-kh** [comment]
Side note: If you don't wish to maintain package updates to WinGet, would you still want community maintaining its releases? Some users may want to use winget to `winget install FredEmmott.OpenKneeboard`

**Comment by fredemmott** [comment]
I'd be fine with that, as long as they stick to the 'stable' releases, not the prereleases - at least based [on GitHub releases metadata](https://api.github.com/repos/OpenKneeboard/OpenKneeboard/releases/latest), but ideally https://autoupdate.openkneeboard.com/stable.json (which is the same format as GitHub releases, but lets me independently choose when autoupdates go out compared  to early adopters who get the updates via Discord or other manual mechanism)

Another alternative: I see `wingetbot` doing similar things here, but I can't find any docs - does that have any support for github releases or equivalent APIs?

**Comment by mdanish-kh** [comment]
> I'd be fine with that, as long as they stick to the 'stable' releases, not the prereleases

As such, would you consider not removing these old versions so that WinGet users can still have value out of them?

> Another alternative: I see wingetbot doing similar things here, but I can't find any docs - does that have any support for github releases or equivalent APIs?

wingetbot's automation is limited as it's only designed to catch hash mismatches / update packages that use a "vanity" (non-versioned) URL. It also doesn't have the ability to query GitHub releases, it downloads the binary and parses out the "File version" field.

Another alternative tool, and the official one from the WinGet team for automating releases to WinGet repository is [Winget-Create](https://github.com/microsoft/winget-create/blob/main/README.md#using-windows-package-manager-manifest-creator-in-a-cicd-pipeline). Have you tried taking a look to see if it can fulfill your needs?

Either way, if you want to proceed with the removal, I can run the script.

**Comment by stephengillie** [comment]
Hi @fredemmott,

We have a limit of 1 manifest change, addition, or removal per PR. This PR modifies more than one PR. Can these changes be spread across multiple PRs?

(Automated response - build 813.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-26T14:32:14.0666542Z ##[error] One or more errors occurred. (The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.) The pull request contains more than one manifest. Either singleton or multi file manifest under one version directory.

(Automated response - build 813.)

**Comment by fredemmott** [comment]
> As such, would you consider not removing these old versions so that WinGet users can still have value out of them?

Yeah, no trouble keeping them around.

> Another alternative tool, and the official one from the WinGet team for automating releases to WinGet repository is [Winget-Create](https://github.com/microsoft/winget-create/blob/main/README.md#using-windows-package-manager-manifest-creator-in-a-cicd-pipeline). Have you tried taking a look to see if it can fulfill your needs?

This is currently part of my manual flows (e.g. I'm using https://github.com/fredemmott/HTCC/blob/master/installer/update-winget.ps1 in combination with the github releases API); I'll take a look at fully automating. I can probably take advantage of most of the credentials/PR creation stuff I setup to run winget-releaser as bot account.

**Pull request closed without merging**
