### PR TITLE
Ultimaker.Cura version 4.10.0

### PR DESCRIPTION
**Pull request by quhxl**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/19798)

### CODE REVIEW

**Review by jedieaston — APPROVED** [review]

**Comment by quhxl** [comment]
Is there a way to deal with the device driver installation?

**Review by jedieaston — CHANGES_REQUESTED** [review]
There isn't, although I thought there was Azure-Pipeline-Passed on this when it came up.

The version currently in the repo installs silently. Maybe it's worth opening an issue in Ultimaker/Cura.

Otherwise this is blocked by the circumstances described in this comment: https://github.com/microsoft/winget-cli/discussions/615#discussioncomment-484437

**Review by vedantmgoyal9 — APPROVED** [review]

**Comment by denelon** [comment]
@jedieaston in the other PR, I tested and got a "The parameter is incorrect.". I got the same error on this set of manifest files as well. What error were others getting here? I'd like to file an issue on Ultimaker Cura.

**Comment by ItzLevvie** [comment]
cc @denelon: I'm seeing this:
image

**Comment by quhxl** [comment]
> 
> 
> cc @denelon: I'm seeing this:
> image

me too

**Comment by jedieaston** [comment]
Not at my machine at the moment, but I got the same thing.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/19798#issuecomment-875798230

**Comment by quhxl** [comment]
> 
> 
> [#19798 (comment)](https://github.com/microsoft/winget-pkgs/pull/19798#issuecomment-875798230)

@ItzLevvie Should I close this PR? Or why are you suggesting changes?

**Comment by denelon** [comment]
It looks like Cura now has a driver as a part of the installation. It might be worth creating an issue on their repository to see if this is something they can get to install silently.

**Comment by ItzLevvie** [comment]
> @ItzLevvie Should I close this PR? Or why are you suggesting changes?

For now yes, this PR should be closed as you'll have to contact the application developer to put out a new version because it currently doesn't install fully unattended as there's an interactive driver prompt blocking the install.

**Pull request closed without merging**
