### PR TITLE
Remove version: Google.Chrome version 120.0.6099.217

### PR DESCRIPTION
**Pull request by PckgrBot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135438)

### CODE REVIEW

**Comment by drshtmstry** [comment]
> Sequence contains no elements

- #133371

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 642.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-19T04:47:50.8275460Z Processing manifest: manifests\g\Google\Chrome\120.0.6099.217
 2024-01-19T04:47:50.8284759Z -----------------------------------------------------
 2024-01-19T04:47:50.8291265Z Status: Started
 2024-01-19T04:47:50.8299331Z Manifest file is Deleted
 2024-01-19T04:47:51.1204463Z Status: Completed
 2024-01-19T04:47:51.1217897Z ##[error] Result: Failed
 2024-01-19T04:47:51.1305981Z ##[error] Sequence contains no elements
 2024-01-19T04:47:51.1877587Z ##[error]Manifest Validation Failed

(Automated response - build 642.)

**Comment by stephengillie** [comment]
URL: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise.msi 
Status Code: 200

(Automated message - build 642)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
