### PR TITLE
Add Cobian Backup 11.2.0.582 + txt file for unattended install

### PR DESCRIPTION
**Pull request by dumontirou**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [X] Have you tested your manifest locally with `winget install -m <manifest>`?

FYI : Cobian Backup can only be installed with admin privileges.
I've also added comments in the manifest explaining how to get the unattended install to work.
-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3810)

### CODE REVIEW

**Comment by dumontirou** [comment]
The error returned by the check is : 

> Manifest Error: Invalid field value. Field: Id Value: CobianBackup Line: 1, Column: 5 Manifest Warning: Silent and SilentWithProgress switches are not specified for InstallerType exe. Please make sure the installer can run unattended.

The installer can run unattended, but only if cbSetup.txt exists in the folder used for downloading the installer, which is : 

> C:\Users\%UserProfile%\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\TempState\WinGet

I've added multiple comments in the manifest explaining where to download that .txt file from and where to put it.

**Comment by dumontirou** [comment]
Sorry for the multiple changes, I've changed the folder structure and modified the manifest as needed.
The manifest contains a link to the text file to use for the unattended install.
If such a thing is not authorized, could you please add the text file to the folder, so that users will be able to download the text file from the repository ?

If you need more information, you can refer yourself to my previous comment.

**Comment by dumontirou** [comment]
> Greetings dumontirou
> During installation testing, this application failed to install with out user input.  Did you forget to add  Silent or SilentWithProgress switches?
> 
> Please investigate a fix and resubmit the Pull Request.

The Silent and SilentWithProgress switches are in the manifest, but they won't work if cbSetup.txt doesn't exist in the folder in which WinGet puts the installer

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/158

**Comment by dumontirou** [comment]
Closing this pull request given that the unattended installation can't be done without providing user credentials.

**Pull request closed without merging**
