### PR TITLE
dorssel.usbipd-win version 0.3.1

### PR DESCRIPTION
**Pull request by dorssel**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14867)

### CODE REVIEW

**Comment by dorssel** [comment]
This is an MSI installer. I tested winget locally with silent, normal (progress), and interactive. All behave as they should. Could it be that the validation server is just overloaded and simply timed out?

**Comment by denelon** [comment]
@dorssel are there any dependencies required? Sometimes we see UI pop when there are dependencies.

**Comment by dorssel** [comment]
I found the problem. It's a driver popup for Oracle that I locally have in my trusted publishers list...

Will have to rethink this. In any case, this installer won't work. Will abort this PR.

**Comment by dorssel** [comment]
I fixed the problem by improving the installer. It now detects silent install and will deal with the driver install accordingly. Updated to 0.3.1. It now verifies.

**Pull request merged**
