### PR TITLE
Add PublisherSupportURL to Viber.Viber

### PR DESCRIPTION
**Pull request by BrandonWanHuanSheng**
Add PublisherSupportURL to Viber.Viber 20.1.0.10

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/108061)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
Hmm. The link look like it works in my browser. But Invoke-WebRequest keep saying forbidden.

**Comment by BrandonWanHuanSheng** [comment]
> Hello @BrandonWanHuanSheng,
> 
> The package manager bot determined there was an issue with some of the URLs included in the manifest file. Please check the pull request for more details and make sure the urls are correct.
> 
> Template: msftbot/validationError/urls/smartScreen

URL is work on my browser. But Invoke-WebRequest and Wget keep saying forbidden which is incorrect.

**Comment by Trenly** [comment]
> > Hello @BrandonWanHuanSheng,
> > The package manager bot determined there was an issue with some of the URLs included in the manifest file. Please check the pull request for more details and make sure the urls are correct.
> > Template: msftbot/validationError/urls/smartScreen
> 
> URL is work on my browser. But Invoke-WebRequest and Wget keep saying forbidden which is incorrect.

The website blocks automated requests from services like Azure and GitHub. It is something that happens with (almost) all support sites that use Zendesk

**Comment by BrandonWanHuanSheng** [comment]
> > > Hello @BrandonWanHuanSheng,
> > > The package manager bot determined there was an issue with some of the URLs included in the manifest file. Please check the pull request for more details and make sure the urls are correct.
> > > Template: msftbot/validationError/urls/smartScreen
> > 
> > 
> > URL is work on my browser. But Invoke-WebRequest and Wget keep saying forbidden which is incorrect.
> 
> The website blocks automated requests from services like Azure and GitHub. It is something that happens with (almost) all support sites that use Zendesk

Why Zendesk want to blocks the support website?

**Comment by Trenly** [comment]
> Why Zendesk want to blocks the support website?

Zendesk doesn't block the support website. They block programmatic calls to the website to prevent spam. That's why you can access it from a browser, but the validation pipelines get 403 - Forbidden

**Comment by BrandonWanHuanSheng** [comment]
> > Why Zendesk want to blocks the support website?
> 
> Zendesk doesn't block the support website. They block programmatic calls to the website to prevent spam. That's why you can access it from a browser, but the validation pipelines get 403 - Forbidden

Oh, I see.

**Comment by BrandonWanHuanSheng** [comment]
It look like it is too much noise.

**Pull request closed without merging**
