### PR TITLE
EnderbytePrograms.PyinstallerHelper version 1.2.0.0

### PR DESCRIPTION
**Pull request by Enderbyte09**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/152435)

### CODE REVIEW

**Comment by Enderbyte09** [comment]
If any human is reading this, I have no clue why it is failing; The winget tests all worked as expected.

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 880.)

**Comment by Enderbyte09** [comment]
So should I submit the installer again?

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 
> 2024-05-06 17:19:58.420 [FAIL] Installer failed security check. Url: https://github.com/Enderbyte-Programs/PyinstallerHelper/releases/download/v1.2/pyinstallerhelper-1.2-setup.exe Result: 0x80004005

(Automated response - build 880.)

**Comment by stephengillie** [comment]
Hi @Enderbyte09,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 880.)

**Comment by stephengillie** [comment]
Hi @Enderbyte09, 

Sorry for all of the automation. It appears that the package didn't pass a virus or similar scan. My automation should trigger a retry every 18 hours until it passes.

**Comment by Enderbyte09** [comment]
The source code is from https://github.com/Enderbyte-Programs/Pyinstallerhelper if that helps...??? (Probably not).

**Comment by Enderbyte09** [comment]
Seems like it just isn't working. I will close and resubmit again later.

**Pull request closed without merging**
