### PR TITLE
Add FamiStudio

### PR DESCRIPTION
**Pull request by superusercode**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [X] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

https://github.com/BleuBleu/FamiStudio

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/2259)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
We have this passing through smartscreen.  But I am not able to run the app.  When I execute the app, it does not start.  Is it missing some dependency being installed?

**Comment by superusercode** [comment]
According to their itch page the "VS2015 runtime (x86) " is required https://bleubleu.itch.io/famistudio

**Comment by denelon** [comment]
We need to support dependencies, and the manifest schema needs to be updated.

**Review by ItzLevvie — APPROVED** [review]

**Comment by superusercode** [comment]
I will redo this PR to use the new file structure, now that dependencies are out(?)

**Comment by superusercode** [comment]
I will redo this PR to use the new file structure, now that dependencies are out(?)

**Pull request closed without merging**
