### PR TITLE
Fixed download URLs. Should use download.pdf24.org ...

### PR DESCRIPTION
**Pull request by sz5000**
Download URLs should be https://download.pdf24.org/... in order to use round robin DNS so that the download load is distributed across all available download servers. Thanks.

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/130330)

### CODE REVIEW

**Comment by sz5000** [comment]
@microsoft-github-policy-service agree

**Comment by sz5000** [comment]
"only one package version is being modified in your PR"

Please validate all packages from this pull request, because I had to change multiple packages and changing one by one takes a lot of work, it's easier that way.

**Comment by stephengillie** [comment]
Hi @sz5000,

We have a limit of 1 manifest version change per PR. This PR appears to change 17 PRs, so 16 of the changes will need to be moved to other PRs.

**Comment by sz5000** [comment]
Can't we commit all at once? Starting 17 pull requests makes things unnecessarily complicated.

**Pull request closed without merging**
