### PR TITLE
New package: ar51an.iPerf3 version 3.17.1

### LINKED ISSUE #1173: Add package manifest for iperf3
# Description of the new feature/enhancement
I use `iperf3` to perform network bandwidth tests on both Windows and Linux systems. Right now, I use the Scoop package manager, which includes the `iperf3` package. It would be great if this could get migrated over to WinGet as well.

Application Website: https://iperf.fr/
Scoop manifest: https://github.com/se35710/scoop-main/blob/master/bucket/iperf3.json

# Proposed technical implementation details (optional)

### PR DESCRIPTION
**Pull request by aisgbnok**
Checklist for Pull Requests
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Is there a linked Issue?
  - Resolves #1173 

Manifests
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/196159)

### CODE REVIEW

**Comment by aisgbnok** [comment]
@ar51an, just wanted to confirm your fine with your iperf3 builds being added to winget. If so, do you mind briefly reviewing the metadata in the [`ar51an.iPerf3.locale.en-US.yaml`](https://github.com/microsoft/winget-pkgs/blob/554682afcbbdd1726602462573cb03bb9bfc92b2/manifests/a/ar51an/iPerf3/3.17.1/ar51an.iPerf3.locale.en-US.yaml) file. I assume listing BSD license is correct and not the [Apache-2.0 license](https://github.com/ar51an/iperf3-win-builds?tab=Apache-2.0-1-ov-file) in your repo? 

It's fine if your not familiar with winget packages. Thank you.

---

I wasn't sure whether to go with your builds or BudMan's. I went with yours because you use GitHub as the cdn.

**Comment by ar51an** [comment]
> @ar51an, just wanted to confirm your fine with your iperf3 builds being added to winget. If so, do you mind briefly reviewing the metadata in the [`ar51an.iPerf3.locale.en-US.yaml`](https://github.com/microsoft/winget-pkgs/pull/196159/files#diff-ae0c512f92e1efde0dd9f192ff86b27088fd473e5df1b0f4de0198897e95c47e) file. I assume listing BSD license is correct and not the [Apache-2.0 license](https://github.com/ar51an/iperf3-win-builds?tab=Apache-2.0-1-ov-file) in your repo?
> 
> It's fine if your not familiar with winget packages. Thank you.
> 
> I wasn't sure whether to go with your builds or BudMan's. I went with yours because you use GitHub as the cdn.

Yes I am fine with it. Go with BSD license, it is the one iperf3 source code uses.

**Review by ItzLevvie — APPROVED** [review]

**Review by Dragon1573 — APPROVED** [review]
image
image

**Comment by MagicAndre1981** [comment]
as it installs and works can this be merged?

**Comment by stephengillie** [comment]
Sorry for the delay. 
- This package appears similar to a previous: https://github.com/microsoft/winget-pkgs/pull/135640
- Should that package's `InstallerUrl` and other details be used here?

**Comment by stephengillie** [comment]
Verify:
image

**Comment by MagicAndre1981** [comment]
> Sorry for the delay.
> 
> * This package appears similar to a previous

the old one was created before ArchiveBinariesDependOnPath support was added. So I would pick this PR

**Comment by aisgbnok** [comment]
> Sorry for the delay.
> 
> -  This package appears similar to a previous: [New package: iPerf.iPerf3 version 3.1.3 #135640](https://github.com/microsoft/winget-pkgs/pull/135640)
> - Should that package's `InstallerUrl` and other details be used here?

No. ESnet does not publish binary packages of iperf3. Additionally, [iperf and iperf3 are separate](https://iperf2.sourceforge.io/IperfCompare.html), iperf3 being maintained by ESnet. Given I agree with #180229, iperf3 should not be given the `iPerf.iPerf3` or `ESnet.iPerf3` package ID. I filled out the metadata to use `ar51an` as the publisher (the one who distributes the binary) and `ESnet` as the author.

There are a few community members that distribute iper3 binaries such as BudMan ([most recognized / listed in ESnet docs](https://github.com/esnet/iperf/blob/master/docs/obtaining.rst?plain=1#L30-L33)) and ar51an, I chose ar51an because they use GitHub releases as their CDN and [has been recognized by BudMan.](https://www.neowin.net/forum/topic/1234695-iperf-3171-windows-build/page/5/#findComment-598799237) [BudMan seems to use their own server, and I'm unsure if that will be a stable source for winget.](https://files.budman.pw/)

**Comment by ar51an** [comment]
`iperf.fr` also updated their windows binary links sometime back.
https://iperf.fr/iperf-download.php

**Comment by aisgbnok** [comment]
Just updated the release notes formatting. Verified again:

image

**Comment by stephengillie** [comment]
Verify:
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
