### PR TITLE
New version: AILight.AILZ80ASM version 1.0.10

### PR DESCRIPTION
**Pull request by kkamegawa**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest .\manifests\a\AILight\AILZ80ASM\1.0.10`?
- [ ] Have you tested your manifest locally with `winget install --manifest .\manifests\a\AILight\AILZ80ASM\1.0.10`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/124280)

### CODE REVIEW

**Comment by stephengillie** [comment]
Manual Validation ended with: 
image

This might be a false positive and we can retry tomorrow.

**Comment by kkamegawa** [comment]
Thank you @stephengillie 
This tool is a program to compile the old assembler called z80. Because it involves code generation, it is an easy target for malware detection, but it is not a problem.

**Comment by stephengillie** [comment]
> Thank you @ stephengillie This tool is a program to compile the old assembler called z80. Because it involves code generation, it is an easy target for malware detection, but it is not a problem.

@kkamegawa, thank you for your patience with this process. Please understand that we check every package numerous times in an attempt to prevent installing viruses onto user PCs.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
