### PR TITLE
Egnyte,Inc.EgnyteDesktopApp version 3.11.2.104

### PR DESCRIPTION
**Pull request by DanPrs**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15691)

### CODE REVIEW

**Comment by KaranKad** [comment]
`PackageIdentifier` should be `Egnyte.EgnyteDesktopApp` instead of `Egnyte,Inc.EgnyteDesktopApp`

**Comment by denelon** [comment]
@DanPrs please make the suggested changes to your branch. The validation will execute again after you push your changes.

**Comment by ItzLevvie** [comment]
cc @DanPrs since your other PR was merged, this PR should be closed because it's now in the master branch: https://github.com/microsoft/winget-pkgs/tree/master/manifests/e/Egnyte/EgnyteDesktopApp/3.11.2.104

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
cc @DanPrs since your other PR was merged, this PR should be closed because it's now in the master branch: https://github.com/microsoft/winget-pkgs/tree/master/manifests/e/Egnyte/EgnyteDesktopApp/3.11.2.104

**Pull request closed without merging**
