### PR TITLE
TEdit.TEdit version 4.13.0

### PR DESCRIPTION
**Pull request by vastar**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/97235)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @vastar,

The package installs normally, but requires Terraria content to run:
image

Is there a switch or other way to bypass this check?

**Comment by vastar** [comment]
Hello, @stephengillie. It should be possible to run TEdit without Terraria installed. The game needed only for optional texture data. On the screenshot error message says, that you have Terraria folder, but it is cannot recognize game files. Maybe you have deleted the game, but there are remnants, that TEdit cannot process correctly. Please, delete Terraria game folder and try again. If it does not work, you can also provide latest logs, located at C:\Users\[user]\AppData\Roaming\TEdit\Logs, so I can investigate this issue. On my machine, after I deleted Terraria and started the program, the logs look like this:

`
02-23-2023 16:56:52: Starting TEdit 4.13.0.0 
02-23-2023 16:56:52: OS: Microsoft Windows NT 10.0.19045.0 
02-23-2023 16:56:52: OS Name: Microsoft Windows 10 Pro  
02-23-2023 16:56:52: .NET Framework Version: 4.8 or later 
02-23-2023 16:56:52: Unable to locate Terraria. No texture data will be available. 
`

**Comment by stephengillie** [comment]
I found that clicking "Cancel" caused the application to launch.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
