### PR TITLE
Create WinGet package for March 2024 GDK Update 2

### PR DESCRIPTION
**Pull request by aaron-stebner**
Create WinGet package for March 2024 GDK Update 2

Tested locally with winget validate and winget install
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/155919)

### CODE REVIEW

**Comment by aaron-stebner** [comment]
@microsoft/xbox-developer-experience-toolbox for review

**Comment by RuthUlloa** [comment]
LGTM

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @aaron-stebner,

This manifest removes Apps and Features entries that are present in previous PR versions. These entries should be added to this version, to maintain version matching, and prevent the 'upgrade always available' situation with this package.

(Automated response - build 901.)

**Comment by aaron-stebner** [comment]
> Hi @aaron-stebner,
> 
> This manifest removes Apps and Features entries that are present in previous PR versions. These entries should be added to this version, to maintain version matching, and prevent the 'upgrade always available' situation with this package.
> 
> (Automated response - build 901.)

I'm not seeing any Apps and Features entries get removed.  Can you elaborate on this more please?

**Pull request merged**
