### PR TITLE
FilesCommunity.Files 2.4.31.0

### PR DESCRIPTION
**Pull request by kdpuvvadi**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

### CODE REVIEW

**Comment by kdpuvvadi** [comment]
Why dependency is not installing while testing in sandbox but works in physical system?

**Comment by Trenly** [comment]
> Why dependency is not installing while testing in sandbox but works in physical system?

Because the sandbox does not have experimental features enabled.

@denelon - Not sure how this package passed in #94170

**Comment by denelon** [comment]
It was a manual validation. I believe @stepheng had experimental features enabled. We'll go ahead and let it stand as grandfathered. We're working on one more bug related to the path for dependencies, and we can use that package as another solid end to end test case.

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Comment by ItzLevvie** [comment]
[Policy] Dependencies

**Comment by kdpuvvadi** [comment]
Can i close this or dependencies are still not available in the winget version in the pipeline?

**Comment by Trenly** [comment]
> Can i close this or dependencies are still not available in the winget version in the pipeline?

Dependencies are still not available. They likely won’t be until a new version of Winget is released as "latest" on the store and at GitHub and has been rolled out to ~ 50% of users

**Pull request closed without merging**
