### PR TITLE
New package: Liquibase.Liquibase version 4.24.0

### PR DESCRIPTION
**Pull request by Roganik**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/121864)

### CODE REVIEW

**Comment by Roganik** [comment]
Hi! 

When I test manifest locally, it requires my input in CLI. (**Enter** to start install, **Enter** to confirm default install location, **Enter** to open install location). Is it expected default behavior?

Per my understanding liquibase uses [install4j](https://www.ej-technologies.com/resources/install4j/help/doc/installers/installerModes.html). I can benefit if someone would point me to some other packages that use the same installer.

Thank you

**Comment by Roganik** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by stephengillie** [comment]
Hi @Roganik,

Could you double-check the installer switches? They aren't resulting in an unattended install.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

It seems not to have completed the install.

**Comment by stephengillie** [comment]
Hi @Roganik,

image

Is there an installer switch to bypass this message and install automatically?

**Comment by Trenly** [comment]
> Per my understanding liquibase uses [install4j](https://www.ej-technologies.com/resources/install4j/help/doc/installers/installerModes.html). I can benefit if someone would point me to some other packages that use the same installer.

Only install4j installers that have special silent switches have been able to be validated. The `-q` switch might work
* https://github.com/microsoft/winget-cli/issues/360

**Comment by Roganik** [comment]
Hi @stephengillie and @Trenly. I've added a switch to installer, so it works without user input. 

Now waiting for the checks to finish.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
