### PR TITLE
New version: GNU.Nano version 7.2

### PR DESCRIPTION
**Pull request by CoolPlayLin**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136827)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 669.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
image

Hi @CoolPlayLin,

Is a dependency missing?

**Comment by CoolPlayLin** [comment]
I don't know what it deps is.

CC @Trenly

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 679.)

**Comment by Jason-Clark-FG** [comment]
I wonder if this is the dependency: https://www.nano-editor.org/dist/win32-support/libncursesw6.dll

It's in the same folder as the portable app...

**Comment by Trenly** [comment]
> It's in the same folder as the portable app...

[policy] zip binary

**Comment by Jason-Clark-FG** [comment]
> > It's in the same folder as the portable app...
> 
> [Policy] zip binary

Yeah, and it doesn't work anyway. I tested with dropping the binary and dll in a folder in my path, and then it's looking for vt220 terminal when I open it in Windows Terminal.

Other options are:

- https://github.com/okibcn/nano-for-windows : This one gave me an archive scan warning when I created a test manifest, so not so sure about it (maybe related: https://github.com/okibcn/nano-for-windows/issues/36)
- https://github.com/lhmouse/nano-win : This one unfortunately so far is archived as a 7z file, and within the archive contains binaries for x86 & x64 in sub-folders (https://github.com/lhmouse/nano-win/issues/186)
- Fix the download link for the very old GNU.nano 2.7.5 package, which does work at least (https://www.nano-editor.org/dist/win32-support/nano-v2.7.5-55-g0d9a73472439.exe)

**Comment by NightFurySL2001** [comment]
I'd say its better with the [okibcn/nano-for-windows](https://github.com/okibcn/nano-for-windows) version as it has UTF-8 support matching official nano. [lhmouse/nano-win](https://github.com/lhmouse/nano-win) 's GitHub is ever changing, and the editor crashes/freezes when inputting UTF-8 text. Scoop nano is provided by okibcn, and I am currently working to change the Chocolatey nano to use okibcn version too.

**Comment by Trenly** [comment]
Although those other options may work, they would need to be put under a different PackageIdentifier since they aren’t from the same source / publisher

**Comment by Trenly** [comment]
@CoolPlayLin - Support for zipped binaries has now been added and is available in the pipelines. This will require you to update your submission to ManifestVersion: 1.9.0 and set ArchiveBinariesDependOnPath: true in the installer node. To keep things clean, this PR is being closed. Please submit a new PR for the latest version of this package. Thank you for your contributions!

**Pull request closed without merging**
