### PR TITLE
NETFoundation.WiXToolsetv3 version 3.11.2.4516

### PR DESCRIPTION
**Pull request by rhuijben**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/65900)

### CODE REVIEW

**Comment by rhuijben** [comment]
There is an old version of this patch in https://github.com/microsoft/winget-pkgs/pull/895
but that is targeted for a winget version that didn't support burn installers yet.

**Comment by Trenly** [comment]
* Duplicate of #58825
* Duplicate of #25268
* Duplicate of #23647

**Review by ItzLevvie — APPROVED** [review]
See https://github.com/microsoft/winget-pkgs/pull/65900#issuecomment-1181843282

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/65900#pullrequestreview-1037119788

**Comment by ItzLevvie** [comment]
Close with reason: Duplicate of previous PRs;

**Pull request closed without merging**
