### PR TITLE
New Version: MediaArea.MediaInfo.GUI 24.01.1

### PR DESCRIPTION
**Pull request by dmirandaa**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141628)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @dmirandaa,

> This PR's version number 24.1.1 has 3 parameters (sets of numbers between dots - major, minor, etc), which is greater than the current manifest's version 23.11, which has 2 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 857)

**Comment by dmirandaa** [comment]
Yes, it does match the version from the app About page and from the website.

Screenshot_20240302-005833-001

Screenshot_20240302-005633-001

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Thanks for the update. It doesn't quite exactly match - the 2nd parameter has a leading `0`, but I'm hoping that this can be safely ignored

**Comment by R-Adrian** [comment]
MediaArea.MediaInfo.GUI 24.01.1 keeps being updated in an infinite loop by winget because the app itself sets the displayed version number "24.01" in the registry, not "24.01.1"

**Comment by mdanish-kh** [comment]
> Yes, it does match the version from the app About page and from the website.
> 

@dmirandaa Actually, that's not the version it should be matching. It should be matching the version that's displayed in Control Panel since WinGet gets its metadata from the Control Panel / App&Features and does the package matching based on that version. If the version in the manifest does not match the version shown in Apps&Features / Control Panel, it can cause upgrade issues for the user. The correct version to put in this case is `24.01`

image

**Pull request merged**
