### PR TITLE
Fix PackageVersion for Lenovo.DockManager version 1.1.1.7

### PR DESCRIPTION
**Pull request by philjorgensen**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/44413)

### CODE REVIEW

**Comment by philjorgensen** [comment]
@OfficialEsco can you override the block? No idea how the metadata is noncompliant when I'm only removing one digit from PackageVersion fields.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
You forgot to update the version folder.

**Comment by OfficialEsco** [comment]
> @OfficialEsco can you override the block? No idea how the metadata is noncompliant when I'm only removing one digit from PackageVersion fields.

If you click the Checks tab you can see the issue in most cases
For this its
```
Manifest: The manifest file path must match PackageIdentifier and PackageVersion properties from manifest. 
actual 'manifests\l\Lenovo\DockManager\1.1.1.17', 
expected 'manifests\l\Lenovo\DockManager\1.1.1.7'
```

Hmm, it appears i was the one that approved https://github.com/microsoft/winget-pkgs/pull/44095 🤔 Must have zoomed trough a few PRs 🤦‍♂️
```
Enter a pull request number: #44413

Manifest validation succeeded.
Found Lenovo Dock Manager [Lenovo.DockManager] Version 1.1.1.7
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.lenovo.com/consumer/options/dockmanagersetup_1.1.1.7.exe
  ██████████████████████████████  5.41 MB / 5.41 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Name        : Lenovo Dock Manager version 1.1.1.7
Publisher   : Lenovo
Version     : 1.1.1.7
ProductCode : DockManager_is1
Uninstall   : winget uninstall --id "DockManager_is1"
```

**Comment by OfficialEsco** [comment]
> > You forgot to update the version folder.
> 
> Thanks for pointing that out, completely overlooked. Should I close this and create a new PR with the fixed folder version?

Tip no.2: Click `.` to open VSCode online, find the folder in the explorer and rename it =)

**Comment by philjorgensen** [comment]
@OfficialEsco I completely overlooked the folder version as @ItzLevvie pointed out. Thanks for helping out!

**Review by OfficialEsco — APPROVED** [review]

**Review by quhxl — APPROVED** [review]

**Pull request merged**
