### PR TITLE
New version: Facebook.Messenger version 203.0.555038473

### PR DESCRIPTION
**Pull request by vietthedev**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135207)

### CODE REVIEW

**Comment by hlqviet** [comment]
Same as #132775 and no idea why

image

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335215 2024-01-22 15:39:16.502 [CORE] DeliveryOptimization error: 0x80d05001, extended error: 0x00000000 2024-01-22 15:39:16.537 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFE201EA465: (caller: 00007FFE201EAD01) Exception(1) tid(1e04) 80D05001  2024-01-22 15:39:34.992 [CLI ] Package hash verification failed. SHA256 in manifest [6cbe5cbe600df546bb91b1cde2c1ca0943a7fba5e5debd8953d39a7458d432b0] does not match download [110f9ddd0addc37de47dce94184320eeb97b9cf6581992e338408e3f1467ca8a] MSI (s) (2C:58) [15:38:58:110]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (2C:8C) [15:38:59:482]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Additional Runtime - 14.38.33130. Product Version: 14.38.33130. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [073C:0C28][2024-01-22T15:38:55]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 628.)

**Pull request closed without merging**
