### PR TITLE
Update Origin to 10.5.82.43225

### PR DESCRIPTION
**Pull request by auanasgheps**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/3258)

### CODE REVIEW

**Comment by auanasgheps** [comment]
Right, my bad. The VM I am using for testing has all Visual C++ runtimes installed thanks to [this great installer](https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/).
I guess then we can't make this PR.

**Comment by KevinLaMS** [comment]
Sorry about that.  We are working on the dependency issue.

**Comment by auanasgheps** [comment]
Shall we keep this open unti it is resolved?

**Comment by auanasgheps** [comment]
I am closing since #6524 did this.

**Pull request closed without merging**
