### PR TITLE
stakira.OpenUTAU version 0.1.149

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/110019&drop=dogfoodAlpha

### CODE REVIEW

**Comment by mdanish-kh** [comment]
image

May just be a false positive on my end, but I'll wait until @stephengillie validates this PR

**Comment by ItzLevvie** [comment]
> image
> 
> May just be a false positive on my end, but I'll wait until @stephengillie can validate this PR as well

Seeing same here:
image

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
See https://github.com/microsoft/winget-pkgs/pull/110019#issuecomment-1596256229

**Comment by stephengillie** [comment]
> > image
> > May just be a false positive on my end, but I'll wait until @stephengillie can validate this PR as well
> 
> Seeing same here: image
> 
> cc @stephengillie

Maybe it got fixed overnight? I'm not seeing the same:
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
