### PR TITLE
Update URL for FastCopy.IPMsg version 5.6.1

### PR DESCRIPTION
**Pull request by Trenly**
From latest URL Scan:
> https://ipmsg.org/archive/ipmsg5.6.1_installer.exe for FastCopy.IPMsg version 5.6.1 redirects to https://raw.githubusercontent.com/FastCopyLab/IPMsgDist/main/ipmsg5.6.1_installer.exe

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/105744)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Comment by stephengillie** [comment]
I'm having difficulty navigating from the PackageUrl to the InstallerUrl.

**Comment by Trenly** [comment]
> I'm having difficulty navigating from the PackageUrl to the InstallerUrl.

@stephengillie - That may be because it's a redirected URL and isn't necessarily on the publisher's website. If you use <kbd>CTRL</kbd> + <kbd>J</kbd> in Chrome / Edge and look at the download URL for the file, you will see the github link.

See the video - https://youtu.be/xEvXFBo8dHM

This is the script I use for checking if URLs are redirected - 
```powershell
function Get-UrlResponse {
        Param
        (
            [Parameter(Mandatory = $true, Position = 0)]
            [string] $URL
        )
        try {
            $HTTP_Request = [System.Net.WebRequest]::Create($URL)
            $HTTP_Request.UserAgent = 'Microsoft-Delivery-Optimization/10.1'
            $HTTP_Response = $HTTP_Request.GetResponse()
            $ResponseUri = $HTTP_Response.ResponseUri
            $AbsoluteUrl = $HTTP_Response.ResponseUri.AbsoluteUri
            $HTTP_Status = [int]$HTTP_Response.StatusCode
            $ResponseLength = $HTTP_Response.ContentLength
            $Headers = @{}; $HTTP_Response.Headers.ForEach({ $Headers[$_] = $Http_Response.Headers[$_] })
        } catch {
            $HTTP_Status = 404
        }
        If ($null -eq $HTTP_Response) { $HTTP_Status = 404 }
        Else { $HTTP_Response.Close() }
        return @{
            Url           = $URL
            ResponseUrl   = $AbsoluteUrl
            ResponseCode  = $HTTP_Status
            ContentLength = $ResponseLength
            Headers       = $Headers
            Response      = $ResponseUri
        }
    }
```
And the result - 
```
PS D:\Git\winget-pkgs> Get-UrlResponse 'https://ipmsg.org/archive/ipmsg5.6.1_installer.exe'

Name                           Value
----                           -----
ResponseCode                   200
ResponseUrl                    https://raw.githubusercontent.com/FastCopyLab/IPMsgDist/main/ipmsg5.6.1_installer.exe
Headers                        {Vary, Content-Type, X-Content-Type-Options, Content-Length...}
Response                       https://raw.githubusercontent.com/FastCopyLab/IPMsgDist/main/ipmsg5.6.1_installer.exe
Url                            https://ipmsg.org/archive/ipmsg5.6.1_installer.exe
ContentLength                  4148112
```

**Comment by stephengillie** [comment]
> > I'm having difficulty navigating from the PackageUrl to the InstallerUrl.
> 
> @stephengillie - That may be because it's a redirected URL and isn't necessarily on the publisher's website. If you use CTRL + J in Chrome / Edge and look at the download URL for the file, you will see the github link.

Yes, this was the case for [FastCopy.FastCopy](https://github.com/microsoft/winget-pkgs/pull/105735), where the redirect is on the PackageUrl page. 
image

And while the URL reads ``, checking the download link reveals the redirect. 

But neither of the links on the IPMessenger PackageUrl page has that redirect - instead, Vector mirror is listed. 
image

From the InstallerUrl, these seem to be coming from the archive - is there an archive page? It might be navigable from the PackageUrl, satisfying the requirement through the archive page as intermediate.

**Comment by stephengillie** [comment]
Thanks. 
That is a lot of steps. I think it would be simpler to change the PackageUrl to https://github.com/FastCopyLab/IPMsgDist, but I'd be willing to accept this if you disagree.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
