### PR TITLE
New package: flawiddsouza.Restfox version 0.20.0

### PR DESCRIPTION
**Pull request by LukeCarrier**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164333)

### CODE REVIEW

**Comment by LukeCarrier** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Verify: :
image
image
image

Hi @LukeCarrier,

Since this application displays `0.19.0`, but the installer writes `0.20.0` to the Registry, a `DisplayVersion` is probably needed. What do you think?

**Comment by LukeCarrier** [comment]
Good catch! I’ll take a look at this tonight and see if I can make sense of why.

**Comment by stephengillie** [comment]
Re-verify:
image
image

**Review by stephengillie — APPROVED** [review]

**Comment by LukeCarrier** [comment]
Thank you @stephengillie! 🙇‍♂️

**Pull request merged**
