### PR TITLE
Add PhotoSync

### PR DESCRIPTION
**Pull request by ath0mas**
trying to add **touchbyte.PhotoSync** to **winget**

ping @touchbyte for help: how to run it silent _please_?

it really looks like a Nullsoft/NSIS installer but none of the standard options to run it silent worked
no `/SILENT`, `/VERYSILENT`, `-q`, `--quiet`?
not better trying some custom switches like `/CURRENTUSER` or `/ALLUSERS`
and no `/?` to help

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1223)

### CODE REVIEW

**Comment by ath0mas** [comment]
problem anticipated when I created this PR with [WIP] prefix in the title
waiting for a feedback from @touchbyte _please_

**Comment by ath0mas** [comment]
I just sent an email to the photosync-app support ; waiting for an answer :)

**Comment by ath0mas** [comment]
Thank you @hschottm from @touchbyte
the installer has been updated to forward the command line options, and it works great now :)

**Review by ghost — APPROVED** [review]
Validation has completed

**Pull request merged**
