### PR TITLE
New package: GameSir.GameSirConnect version 1.1.0

### PR DESCRIPTION
**Pull request by SpecterShell**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/180577)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @SpecterShell,

This package only shows a blank window - is this expected? Is specific hardware required? 
image

Verify while here:
image

**Comment by SpecterShell** [comment]
> Hi @SpecterShell,
> 
> This package only shows a blank window - is this expected? Is specific hardware required? image
> 
> Verify while here: image
> 
> Edit: Can you add a PackageUrl?

The package works normally in my VM.

image


The PackageUrl is available in the zh-CN locale manifest.

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by kenny10291977** [comment]
Hey

**Comment by kenny10291977** [comment]
Hey

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
> The package works normally in my VM.

It's probably an issue with my VM. 

> The PackageUrl is available in the zh-CN locale manifest.

I missed it, thank you. A new version appears to be available: `https://xjdl.bigeyes.com/gsw/download/GameSir-Connect-Setup-1.1.6.exe`

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
