### PR TITLE
Update 7zip.7zip.installer.yaml

### PR DESCRIPTION
**Pull request by elin1923**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/14408)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Uhhh why did you change the installertype to exe? now the installer will fail

**Comment by elin1923** [comment]
> Uhhh why did you change the installertype to exe? now the installer will fail

Because the syntax requires an installer type

**Comment by OfficialEsco** [comment]
Yes, Nullsoft is a InstallerType

**Comment by elin1923** [comment]
> Yes, Nullsoft is a InstallerType

But the installer is an exe file

**Comment by OfficialEsco** [comment]
EXE's InstallerTypes can be Nullsoft, Inno, Wix and burn.
If you have a Installer with `InstallerType: exe` you also need to add `InstallerSwitch`es.

**Comment by theincogtion** [comment]
I had 7zip "stable" installed and winget upgrade --all installed the alpha version of 7zip  👎 
`PS C:\Windows\system32> winget upgrade --all
Gefunden 7-Zip Alpha (exe) [7zip.7zip.Alpha.exe]
Diese Anwendung wird von ihrem Besitzer an Sie lizenziert.
Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern.
Downloading https://www.7-zip.org/a/7z2102-x64.exe
  ██████████████████████████████  1.41 MB / 1.41 MB
Der Installer-Hash wurde erfolgreich überprüft
Paketinstallation wird gestartet...
Erfolgreich installiert`

**Comment by ItzLevvie** [comment]
It's a known issue: https://github.com/microsoft/winget-pkgs/issues/17484#issuecomment-861378146

cc @OfficialEsco Maybe we should revert the changes and the `.exe` installer should be the default since that's probably what most people are using?

**Comment by OfficialEsco** [comment]
> It's a known issue: [#17484 (comment)](https://github.com/microsoft/winget-pkgs/issues/17484#issuecomment-861378146)
> 
> cc @OfficialEsco Maybe we should revert the changes and the `.exe` installer should be the default for Alpha since that's probably what most people are using?

Try removing `ProductCode: 7-Zip` first as that is probably how the Alpha version matched

**Pull request merged**
