### PR TITLE
TiberiusCN.HaloTeamBalancer version 1.2.0.6

### PR DESCRIPTION
**Pull request by coeus89**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/103176)

### CODE REVIEW

**Comment by coeus89** [comment]
Finishing up the pipeline to winget

**Comment by coeus89** [comment]
@microsoft-github-policy-service agree [company="TiberiusCN"]

**Comment by coeus89** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
This package has a large warning when launched:
image

**Comment by coeus89** [comment]
Hi,

This is my first app that I'm trying to publish. Do you know how to properly get rid of that warning? I'd be happy to do whatever is needed.

**Comment by stephengillie** [comment]
Unfortunately, it appears that this is a ClickOnce installer, which does not support silent installation.

ClickOnce are the only type to use the `componenturl` switch:
image

And from an internet search:
image

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
