### PR TITLE
[Portable] New Package: YT.DLP 2022.06.29

### PR DESCRIPTION
**Pull request by Trenly**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/68801)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Review by Trenly — COMMENTED** [review]
Bump

**Comment by Trenly** [comment]
Bump

**Comment by lechacon** [comment]
@trenly, @KaranKad , which one of #61435 and #68801 are we going to keep?

**Comment by Trenly** [comment]
> @Trenly, @KaranKad , which one of #61435 and #68801 are we going to keep?

I don’t think it matters much. I will say that I prefer the cleaner package identifier of #68801, it will make it easier for people to find

**Comment by Trenly** [comment]
@denelon - Great example for https://github.com/microsoft/winget-pkgs/issues/55437

**Comment by KaranKad** [comment]
I think we should have gone with `yt-dlp.yt-dlp` as `PackageIdentifier` as people are more familiar with it and it's in line with other package managers.

**Comment by Kissaki** [comment]
yeah, I agree. I am surprised and irritated it’s under yt when the github org is yt-dlp. I expected `yt-dlp.yt-dlp`, matching the github org + repo.

**Comment by Trenly** [comment]
I can move them very easily; Will do that now

**Pull request merged**
