### PR TITLE
signal adding correct publisher 1

### PR DESCRIPTION
**Pull request by bearmannl**
signal removing incorrect publisher version 22 / 42

#18166 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/18187)

### CODE REVIEW

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/2155#issuecomment-864525827

> Feel free to move the manifests (which i see you've stated with lmao), however recommend you to wait until i approve a Manifest in `OpenWhisperSystems.Signal` so you can easily make good manifests with `wingetcreate update "id" --version --url --submit`

**Comment by bearmannl** [comment]
> [#2155 (comment)](https://github.com/microsoft/winget-pkgs/pull/2155#issuecomment-864525827)
> 
> > Feel free to move the manifests (which i see you've stated with lmao), however recommend you to wait until i approve a Manifest in `OpenWhisperSystems.Signal` so you can easily make good manifests with `wingetcreate update "id" --version --url --submit`

Wasn't expecting you to respond so quick and had some time to kill, so started already... Anyway! 42 PR's created, did the changes automatically.

**Comment by OfficialEsco** [comment]
> > [#2155 (comment)](https://github.com/microsoft/winget-pkgs/pull/2155#issuecomment-864525827)
> > > Feel free to move the manifests (which i see you've stated with lmao), however recommend you to wait until i approve a Manifest in `OpenWhisperSystems.Signal` so you can easily make good manifests with `wingetcreate update "id" --version --url --submit`
> 
> Wasn't expecting you to respond so quick and had some time to kill, so started already... Anyway! 42 PR's created, did the changes automatically.

All of them failed because `ms` in `Systems` are getting censored..

**Comment by bearmannl** [comment]
> > > [#2155 (comment)](https://github.com/microsoft/winget-pkgs/pull/2155#issuecomment-864525827)
> > > > Feel free to move the manifests (which i see you've stated with lmao), however recommend you to wait until i approve a Manifest in `OpenWhisperSystems.Signal` so you can easily make good manifests with `wingetcreate update "id" --version --url --submit`
> > 
> > 
> > Wasn't expecting you to respond so quick and had some time to kill, so started already... Anyway! 42 PR's created, did the changes automatically.
> 
> All of them failed because `ms` in `Systems` are getting censored..
> 
> Edit: NEVERMIND
> ` Manifest: The manifest file path must match PackageIdentifier and PackageVersion properties from manifest. actual 'manifests\o\OpenWhisperSyste***\Signal', expected 'manifests\o\OpenWhisperSyste***\Signal\1.34.3'`
> You forgot to add the version to all the other version but this one.

Correct. Well, more like I ran the changes with PowerShell by hand for this version, folder got moved around correctly, then the next 20 didn't get moved into the version folder... and didn't bother to check since th first one rand without issue with the same PowerShell lines...

Shame on me for not checking beforehand... but fixed now anyway ☺

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
