### PR TITLE
Remove version: rwxrob.pomo version 0.2.3

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/196969)

### CODE REVIEW

**Comment by ItzLevvie** [comment]
[Policy] Highest-Package-Removal

**Comment by ItzLevvie** [comment]
[Policy] Highest-Version-Removal

**Comment by Trenly** [comment]
Close with reason: Duplicate;

**Comment by jamiebarrow** [comment]
@Trenly @Exorcism0666 As of writing there were three PRs for the package to be removed, but all three were closed as duplicates and the package hasn't been removed.

- https://github.com/microsoft/winget-pkgs/pull/196969 (this PR)
- https://github.com/microsoft/winget-pkgs/pull/197638
- https://github.com/microsoft/winget-pkgs/pull/197451

I noticed that the rwxrob/pomo repository is no longer available, and so I believe one of these should be re-opened and the PR merged.

Thanks!

**Pull request closed without merging**
