### PR TITLE
Nanoleaf.NanoleafDesktop version 0.8.1

### PR DESCRIPTION
**Pull request by ThioJoe**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/16481)

### CODE REVIEW

**Comment by ThioJoe** [comment]
Seemed to work without any input when I did it. I think it opened a browser window after it finished, not sure if that tripped it up.

**Comment by ThioJoe** [comment]
Ah I found the issue after running it in the sandbox. The program requires Visual C++ Redistributable, so it pops up a window that requires a click, and then also goes through and installs the redistributable. 

Looks it'll have to wait until that feature is added -- https://github.com/microsoft/winget-cli/issues/163

**Comment by denelon** [comment]
@ThioJoe if you would prefer, we can label the PR with "Blocking-Issue" and "Dependency" to keep the work you've done on the manifest, When we implement those pesky, blocking issues, we will attempt to approve the PRs.

**Comment by ThioJoe** [comment]
> @ThioJoe if you would prefer, we can label the PR with "Blocking-Issue" and "Dependency" to keep the work you've done on the manifest, When we implement those pesky, blocking issues, we will attempt to approve the PRs.

Oh not necessary, it wasn't much of a time investment. Appreciate it though 👍

**Pull request closed without merging**
