### PR TITLE
Revert Teamviewer to 15.42.6

### PR DESCRIPTION
**Pull request by aaronliu0130**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/109243&drop=dogfoodAlpha

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
The Package Version needs to be changed to 15.42.6 to match Control Panel, since it appears they rolled back the release

**Comment by Trenly** [comment]
> Shoot I still have to change the folder name, don't I?

I think so; And you will probably have to change the version in all 3 files for TeamViewer :(

**Comment by aaronliu0130** [comment]
@Trenly Apparently just a force push isn't good enough? I'm not well-versed in Git, how do I do a backwards merge?

**Comment by aaronliu0130** [comment]
f

**Comment by aaronliu0130** [comment]
Why is the installer validation STILL in progress?

**Review by Trenly — APPROVED** [review]

**Pull request merged**
