### PR TITLE
New version: Microsoft.OneDrive version 24.166.0818.0003

### PR DESCRIPTION
**Pull request by spectopo**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in workflow run [#7890](https://github.com/SpecterShell/Dumplings/actions/runs/10743842215).

<details>

<summary>Log</summary>

````
Updated: 24.161.0811.0001 → 24.166.0818.0003
Submitting WinGet manifests
Creating manifests
Uploading manifests and making commits
Creating a pull request
````

</details>

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/172085)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by spectopo** [comment]
@stephengillie Manual validation needed.

**Comment by ItzLevvie** [comment]
[Policy] Needs-Manual-Merge

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2147012867
> 2024-09-07 10:18:56.576 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-09-07 10:18:56.608 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFAE45FA465: (caller: 00007FFAE45FAD01) Exception(1) tid(1944) 80072EFD 
> 2024-09-07 10:18:59.132 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FFAE45F395E: (caller: 00007FFAE45F5C49) Exception(2) tid(1944) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-09-07 10:18:59.199 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.166.0818.0003/amd64/OneDriveSetup.exe
> 2024-09-07 10:19:09.888 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-09-07 10:19:09.888 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFAE45FA465: (caller: 00007FFAE45FAD01) Exception(3) tid(1944) 80072EFD 
> 2024-09-07 10:19:12.007 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FFAE45F395E: (caller: 00007FFAE45F5C49) Exception(4) tid(1944) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-09-07 04:27:29.682 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-09-07 04:27:29.849 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFA3738A465: (caller: 00007FFA3738AD01) Exception(1) tid(1f04) 80072EFD 
> 2024-09-07 04:27:32.157 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FFA3738395E: (caller: 00007FFA37385C49) Exception(2) tid(1f04) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-09-07 04:27:32.221 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.166.0818.0003/amd64/OneDriveSetup.exe
> 2024-09-07 04:27:42.490 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-09-07 04:27:42.490 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFA3738A465: (caller: 00007FFA3738AD01) Exception(3) tid(1f04) 80072EFD 
> 2024-09-07 04:27:44.611 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!00007FFA3738395E: (caller: 00007FFA37385C49) Exception(4) tid(1f04) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-09-07 11:28:50.244 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-09-07 11:28:50.369 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!55B057EB: (caller: 55B05E1C) Exception(1) tid(dd0) 80072EFD 
> 2024-09-07 11:28:52.683 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!55AFF0BF: (caller: 55B00E2B) Exception(2) tid(dd0) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-09-07 11:28:52.920 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.166.0818.0003/OneDriveSetup.exe
> 2024-09-07 11:29:03.252 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-09-07 11:29:03.252 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!55B057EB: (caller: 55B05E1C) Exception(3) tid(dd0) 80072EFD 
> 2024-09-07 11:29:05.324 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!55AFF0BF: (caller: 55B00E2B) Exception(4) tid(dd0) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-09-07 04:26:58.847 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-09-07 04:26:58.954 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!561D57EB: (caller: 561D5E1C) Exception(1) tid(82c) 80072EFD 
> 2024-09-07 04:27:01.196 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!561CF0BF: (caller: 561D0E2B) Exception(2) tid(82c) 80072EFD     Msg:[InternetOpenUrl() failed.] 
> 2024-09-07 04:27:01.228 [CLI ] Failed to download, waiting a bit and retry. Url: https://oneclient.sfx.ms/Win/Installers/24.166.0818.0003/OneDriveSetup.exe
> 2024-09-07 04:27:11.624 [CORE] DeliveryOptimization error: 0x80072efd, extended error: 0x00000000
> 2024-09-07 04:27:11.624 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!561D57EB: (caller: 561D5E1C) Exception(3) tid(82c) 80072EFD 
> 2024-09-07 04:27:13.742 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(122)\WindowsPackageManager.dll!561CF0BF: (caller: 561D0E2B) Exception(4) tid(82c) 80072EFD     Msg:[InternetOpenUrl() failed.] 

Automated error analysis suggests -2147012867 may mean Network or Firewall Error.

Automated error analysis suggests 80072EFD may mean The operation timed out.

(Automated response - build 895.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
