### PR TITLE
New version: spacelift-io.spacectl 1.7.0

### PR DESCRIPTION
**Pull request by mbialon**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/190812)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
{"packageData":{"DefaultLocale":{"PackageLocale":"en-us","PackageName":"spacectl","Publisher":"spacelift-io"},"installerHash":"52f4e19b-019b-46ff-b00a-cb975ba73f4d"},"submissionData":{"submissionIdentifier":"68e66a91-bb0a-4eb0-9252-d20b550382cf"},"supportedMetadataVersion":"1.2","version":"1.0"}
> 
> Installation failed with exit code -1978335187
> 2024-11-12 13:17:36.710 [CLI ] Manifest fields: Name [spacectl], Version [1.7.0]
> 2024-11-12 13:17:36.761 [CLI ] Generated temp download path: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\spacelift-io.spacectl.1.7.0\656336fd5239fd2b9eb76908e0b126dee259600a68b86918e8dbec384d76474b
> 2024-11-12 13:17:36.762 [CORE] Downloading to path: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\spacelift-io.spacectl.1.7.0\656336fd5239fd2b9eb76908e0b126dee259600a68b86918e8dbec384d76474b
> 2024-11-12 13:17:36.763 [CORE] DeliveryOptimization downloading from url: https://github.com/spacelift-io/spacectl/releases/download/v1.7.0/spacectl_1.7.0_windows_amd64.zip
> 2024-11-12 13:17:38.937 [CORE] Started applying motw to C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\spacelift-io.spacectl.1.7.0\656336fd5239fd2b9eb76908e0b126dee259600a68b86918e8dbec384d76474b with zone: 3
> 2024-11-12 13:17:38.981 [CORE] Started applying motw using IAttachmentExecute to C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\spacelift-io.spacectl.1.7.0\656336fd5239fd2b9eb76908e0b126dee259600a68b86918e8dbec384d76474b
> 2024-11-12 13:17:40.966 [FAIL] Installer failed security check. Url: https://github.com/spacelift-io/spacectl/releases/download/v1.7.0/spacectl_1.7.0_windows_amd64.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
{"packageData":{"DefaultLocale":{"PackageLocale":"en-us","PackageName":"spacectl","Publisher":"spacelift-io"},"installerHash":"a6a85b93-0e4d-4df7-9e09-8422504ed25b"},"submissionData":{"submissionIdentifier":"8f5b33ca-2fba-4a9d-8304-0780ac347f53"},"supportedMetadataVersion":"1.2","version":"1.0"}
> 
> Installation failed with exit code -1978335187
> 2024-11-13 11:04:54.002 [CLI ] Manifest fields: Name [spacectl], Version [1.7.0]
> 2024-11-13 11:04:54.090 [CLI ] Generated temp download path: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\spacelift-io.spacectl.1.7.0\656336fd5239fd2b9eb76908e0b126dee259600a68b86918e8dbec384d76474b
> 2024-11-13 11:04:54.093 [CORE] Downloading to path: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\spacelift-io.spacectl.1.7.0\656336fd5239fd2b9eb76908e0b126dee259600a68b86918e8dbec384d76474b
> 2024-11-13 11:04:54.094 [CORE] DeliveryOptimization downloading from url: https://github.com/spacelift-io/spacectl/releases/download/v1.7.0/spacectl_1.7.0_windows_amd64.zip
> 2024-11-13 11:04:55.180 [CORE] Started applying motw to C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\spacelift-io.spacectl.1.7.0\656336fd5239fd2b9eb76908e0b126dee259600a68b86918e8dbec384d76474b with zone: 3
> 2024-11-13 11:04:55.269 [CORE] Started applying motw using IAttachmentExecute to C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\spacelift-io.spacectl.1.7.0\656336fd5239fd2b9eb76908e0b126dee259600a68b86918e8dbec384d76474b
> 2024-11-13 11:04:57.527 [FAIL] Installer failed security check. Url: https://github.com/spacelift-io/spacectl/releases/download/v1.7.0/spacectl_1.7.0_windows_amd64.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
{"packageData":{"DefaultLocale":{"PackageLocale":"en-us","PackageName":"spacectl","Publisher":"spacelift-io"},"installerHash":"bd4821d8-dc0f-4e6b-8bb9-e71472db41cc"},"submissionData":{"submissionIdentifier":"9ba4e6a9-74fe-4408-8a3c-11bc08fa513c"},"supportedMetadataVersion":"1.2","version":"1.0"}
> 
> Installation failed with exit code -1978335187
> 2024-11-14 10:18:13.081 [CLI ] Manifest fields: Name [spacectl], Version [1.7.0]
> 2024-11-14 10:18:13.158 [CLI ] Generated temp download path: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\spacelift-io.spacectl.1.7.0\656336fd5239fd2b9eb76908e0b126dee259600a68b86918e8dbec384d76474b
> 2024-11-14 10:18:13.159 [CORE] Downloading to path: C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\spacelift-io.spacectl.1.7.0\656336fd5239fd2b9eb76908e0b126dee259600a68b86918e8dbec384d76474b
> 2024-11-14 10:18:13.160 [CORE] DeliveryOptimization downloading from url: https://github.com/spacelift-io/spacectl/releases/download/v1.7.0/spacectl_1.7.0_windows_amd64.zip
> 2024-11-14 10:18:14.894 [CORE] Started applying motw to C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\spacelift-io.spacectl.1.7.0\656336fd5239fd2b9eb76908e0b126dee259600a68b86918e8dbec384d76474b with zone: 3
> 2024-11-14 10:18:14.992 [CORE] Started applying motw using IAttachmentExecute to C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\spacelift-io.spacectl.1.7.0\656336fd5239fd2b9eb76908e0b126dee259600a68b86918e8dbec384d76474b
> 2024-11-14 10:18:18.775 [FAIL] Installer failed security check. Url: https://github.com/spacelift-io/spacectl/releases/download/v1.7.0/spacectl_1.7.0_windows_amd64.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
