### PR TITLE
Update Synology.DriveClient version 7.3.0.15082

### LINKED ISSUE #112274: [Update Request]: Synology Drive Client to version 3.3.0-15082
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

Synology.DriveClient

### Package Version

7.2.1.13271

### Please describe the changes you would like to see

New version available at 
https://global.synologydownload.com/download/Utility/SynologyDriveClient/3.3.0-15082/Windows/Installer/Synology%20Drive%20Client-3.3.0-15082.msi
MD5 f1f7b14792cef82f0bf815ea8c052579
Release notes at https://www.synology.com/de-de/releaseNote/SynologyDriveClient

Thank you @max-schmidt for the last update. PS There was a bugfix release to 3.2.1.13272 between those.

### PR DESCRIPTION
**Pull request by max-schmidt**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----
fix #112274

### CODE REVIEW

**Comment by max-schmidt** [comment]
The installer validation fails without any further information. Locally there are no problems with the installation. 
Is there anything I can do?

**Review by Trenly — APPROVED** [review]

**Pull request merged**
