### PR TITLE
New version: AlekseyHoffman.Sigma-File-Manager version 1.6.0

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

https://github.com/microsoft/winget-pkgs/pull/69693#issuecomment-1435248843

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/97103)

### CODE REVIEW

**Comment by aleksey-hoffman** [comment]
Cheers mate!

**Review by ItzLevvie — APPROVED** [review]

**Comment by aleksey-hoffman** [comment]
@OfficialEsco hey mate! Sorry to ask you again, but the v1.7 is out. 
I would really appreciate if you could update it or explain me how to update it myself

**Comment by OfficialEsco** [comment]
@aleksey-hoffman there is a few methods you could update it your self https://github.com/microsoft/winget-pkgs#authoring-a-manifest

The community made tool [YamlCreate](https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1) which i like requires you to have the repo cloned on your machine https://github.com/microsoft/winget-pkgs/blob/master/doc/tools/YamlCreate.md

Or you could use Microsoft's own made tool [WinGet-Create](https://github.com/microsoft/winget-create)

There is actually a third alternative now, [Komac](https://github.com/russellbanks/Komac) which i've not used yet.
But i see the Github Action [WinGet-Releaser](https://github.com/marketplace/actions/winget-releaser) have swapped over from YamlCreate to Komac so it should be the best tool

**Comment by aleksey-hoffman** [comment]
@OfficialEsco thanks! I will try it in the next release

**Pull request merged**
