### PR TITLE
Google.ProjectGameface version 0.3.30

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/106696)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
InstallationVerification-x64-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20230512235510

**Comment by stephengillie** [comment]
Hi @upintheairsheep,

The installer did not complete:
image

> Traceback (most recent call last):
  File "run_app.py", line 19, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "src\gui\__init__.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "src\gui\main_gui.py", line 27, in <module>
  File "customtkinter\__init__.py", line 67, in set_default_color_theme
    ThemeManager.load_theme(color_string)
  File "customtkinter\windows\widgets\theme\theme_manager.py", line 21, in load_theme
    with open(theme_name_or_path, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'assets/themes/google_theme.json'

**Comment by upintheairsheep** [comment]
> Hi @upintheairsheep,
> 
> The installer did not complete: image
> 
> > Traceback (most recent call last):
> > File "run_app.py", line 19, in 
> > File "", line 1007, in _find_and_load
> > File "", line 986, in _find_and_load_unlocked
> > File "", line 680, in _load_unlocked
> > File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
> > File "src\gui__init__.py", line 15, in 
> > File "", line 1007, in _find_and_load
> > File "", line 986, in _find_and_load_unlocked
> > File "", line 680, in _load_unlocked
> > File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
> > File "src\gui\main_gui.py", line 27, in 
> > File "customtkinter__init__.py", line 67, in set_default_color_theme
> > ThemeManager.load_theme(color_string)
> > File "customtkinter\windows\widgets\theme\theme_manager.py", line 21, in load_theme
> > with open(theme_name_or_path, "r") as f:
> > FileNotFoundError: [Errno 2] No such file or directory: 'assets/themes/google_theme.json'

Try on windows 11 and on a real machine first.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
I'm seeing the same as Stephen:
image

**Comment by upintheairsheep** [comment]
> I'm seeing the same as Stephen:
> image

Make an issue on Google’s GitHub repository

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Comment by ItzLevvie** [comment]
[Policy] Hardware

**Comment by denelon** [comment]
Supporting custom hardware in validation is "Not Planned".
* https://github.com/microsoft/winget-pkgs/issues/199504

**Pull request closed without merging**
