### PR TITLE
New package: XINGInc.HAL-O-ROIDMinami version 2.0.0

### PR DESCRIPTION
**Pull request by Exorcism0666**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140962)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-26 01:21:41.379 [CORE] WinGet, version [1.7.6-preview], activity [{A4F0DA7C-4E71-43B0-8ACD-B2C713CBC336}] 2024-02-26 01:21:41.380 [CORE] OS: Windows.Desktop v10.0.19045.3693 2024-02-26 01:21:41.380 [CORE] Command line Args: "D:\TOOLS\MetadataTracker\OWCValidation.InstallerMetadataTracker.exe" collect --inputFile C:\Users\validator\AppData\Local\Temp\e357513f-054b-439f-8a7c-ccdd3779c5ee\collector_input.json --outputFile C:\Users\validator\AppData\Local\Temp\e357513f-054b-439f-8a7c-ccdd3779c5ee\collector_output.json --logsDirectory D:\TRANSFER\a75c4dd9-87d4-ee11-907a-6045bdb7c696\output 2024-02-26 01:21:41.380 [CORE] Package: Microsoft.DesktopAppInstaller v1.21.2771.0 2024-02-26 01:21:41.380 [CORE] IsCOMCall:0; Caller: installer-metadata-collection 2024-02-26 01:21:41.381 [REPO] Opening InstallerMetadataCollectionContext input file: C:\Users\validator\AppData\Local\Temp\e357513f-054b-439f-8a7c-ccdd3779c5ee\collector_input.json 2024-02-26 01:21:41.393 [REPO] Parsing input JSON: {"packageData":{"DefaultLocale":{"PackageLocale":"en-us","PackageName":"CeVIO Voice Package - ハルオロイド・ミナミ（HAL-O-ROID）)","Publisher":"XING Inc."},"installerHash":"8c5f83b5-c93b-455f-b686-0c8cf19bdb52"},"submissionData":{"submissionIdentifier":"9fb3ff8a-8e0e-458d-972a-8591a6f7ffda"},"supportedMetadataVersion":"1.2","version":"1.0"} 2024-02-26 01:21:41.393 [REPO] Parsing input JSON version 1.0 2024-02-26 01:21:41.393 [REPO] Parsing input JSON 1.0 fields 2024-02-26 01:21:41.396 [REPO] Creating PredefinedInstalledSource with filter [ARP] 2024-02-26 01:21:41.396 [REPO] Creating new SQLite Index with version [Latest] at ':memory:' 2024-02-26 01:21:41.396 [SQL ] Opening SQLite connection #1: ':memory:' [6, 0] 2024-02-26 01:21:41.475 [REPO] Reading
> MSI UpgradeCodes 2024-02-26 01:21:41.476 [REPO] Examining ARP entries for Machine | X64 2024-02-26 01:21:41.482 [REPO] Examining ARP entries for Machine | X86 2024-02-26 01:21:41.487 [REPO] Reading
> MSI UpgradeCodes 2024-02-26 01:21:41.487 [REPO] Examining ARP entries for User | X64 2024-02-26 01:21:51.395 [REPO] Creating PredefinedInstalledSource with filter [ARP] 2024-02-26 01:21:51.395 [REPO] Creating new SQLite Index with version [Latest] at ':memory:' 2024-02-26 01:21:51.395 [SQL ] Opening SQLite connection #2: ':memory:' [6, 0] 2024-02-26 01:21:51.535 [REPO] Reading
> MSI UpgradeCodes 2024-02-26 01:21:51.536 [REPO] Examining ARP entries for Machine | X64 2024-02-26 01:21:51.547 [REPO] Examining ARP entries for Machine | X86 2024-02-26 01:21:51.556 [REPO] Reading
> MSI UpgradeCodes 2024-02-26 01:21:51.574 [REPO] Examining ARP entries for User | X64 2024-02-26 01:21:51.580 [REPO] Creating output JSON version for input version 1.0 2024-02-26 01:21:51.580 [REPO] Setting output JSON 1.0 fields 2024-02-26 01:21:51.580 [REPO] Creating metadata JSON version 1.2 2024-02-26 01:21:51.580 [REPO] Creating metadata JSON 1.2 fields File Watcher -> Register watching C:\, Filter =  Installing winget from 'C:\Winget\Dependencies' winget-cli Installation complete. Running defender with arguments -SignatureUpdate Standard output: Signature update started . . . Signature update finished.  Signature Update Completed Successfully. WinGet is installed. Running winget settings --enable LocalArchiveMalwareScanOverride End winget settings --enable LocalArchiveMalwareScanOverride Enabling override of local archive malware scan succeeded: True Running winget settings --enable LocalManifestFiles End winget settings --enable LocalManifestFiles Enabling installation of local manifests succeeded: True Scope set to:  Locale set to:  System Architecture: X64 Running with Elevation: True Running winget install --id CeVIO.CeVIOCS7 --accept-source-agreements --accept-package-agreements End winget install --id CeVIO.CeVIOCS7 --accept-source-agreements --accept-package-agreements Starting FileTracker File Watcher -> Begin watching C:\, Filter =  Blocked/Waiting on data collection initiation in Child. Unblocked from data collection initiation in Child. Running winget install --manifest C:\Users\validator\AppData\Local\Temp\Manifest.yaml --accept-package-agreements End winget install --manifest C:\Users\validator\AppData\Local\Temp\Manifest.yaml --accept-package-agreements Package Installed Successfully. Blocked/Waiting on data collection completion. Unblocked on data collection completion. Stopped Metadata collection Installer Type: msi Checking if C:\Windows\Installer\{863AD196-DDCB-41F3-B410-1939A37D482E}\_853F67D554F05449430E7E.exe executable file can be started.    at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)    at System.Diagnostics.Process.Start()    at Microsoft.OWCValidation.Install.Automation.Helpers.Runnable.<>c__DisplayClass11_0.<CanBeStarted>b__0() in C:\__w\1\s\src\OWCValidation.Install.Automation\Helpers\Runnable.cs:line 167    at System.Threading.Tasks.Task.InnerInvoke()    at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)    at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state) --- End of stack trace from previous location ---    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout)    at Microsoft.OWCValidation.Install.Automation.Helpers.Runnable.CanBeStarted() in C:\__w\1\s\src\OWCValidation.Install.Automation\Helpers\Runnable.cs:line 176    at Microsoft.OWCValidation.Install.Automation.Helpers.Runnable.Launch() in C:\__w\1\s\src\OWCValidation.Install.Automation\Helpers\Runnable.cs:line 113 Stopping FileTracker File Watcher -> Stop watching C:\, Filter =  Running defender with arguments -Scan -ScanType 2 -DisableRemediation Standard output: Scan starting... Scan finished. Full Scan Operation Completed Successfully. Input File Path: C:\Users\validator\AppData\Local\Temp\e357513f-054b-439f-8a7c-ccdd3779c5ee\collector_input.json Output File Path: C:\Users\validator\AppData\Local\Temp\e357513f-054b-439f-8a7c-ccdd3779c5ee\collector_output.json Log File Path: D:\TRANSFER\a75c4dd9-87d4-ee11-907a-6045bdb7c696\output Attempt to initiate metadata collection. Metadata collection initiated Attempt to release mutex: DAAS_VALIDATION_DATA_COLLECTION_INITIATED. Mutex: DAAS_VALIDATION_DATA_COLLECTION_INITIATED released. Waiting on mutex: DAAS_VALIDATION_INSTALL Resuming after DAAS_VALIDATION_INSTALL was released. Attempt to complete metadata collection. Metadata collection completed. ------------------------------------------------------------------------------------- MpCmdRun: Command Line: "c:\Program files\Windows Defender\MpCmdRun.exe" -SignatureUpdate  Start Time: ‎Mon ‎Feb ‎26 ‎2024 01:19:04 MpEnsureProcessMitigationPolicy: hr = 0x1 Start: MpSignatureUpdate() Calling MpUpdateStartEx with option 0x1 Update started  Search Started (MU/WU update) (Path: https://fe2cr.update.microsoft.com/v6/)... Search Completed  Download Started... Download Completed  Installation Started... Time Info - ‎Mon ‎Feb ‎26 ‎2024 01:19:47 Installation Completed  Update completed succesfully. (hr:0x00000000) Finish: MpSignatureUpdate() MpCmdRun: End Time: ‎Mon ‎Feb ‎26 ‎2024 01:19:47

(Automated response - build 816.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 

(Automated response - build 817.)

**Comment by stephengillie** [comment]
Verify:
image

The dependency needs a code to become usable, so can't verify the install inside of it.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
