### PR TITLE
TweakingTechnologies.TweakPass version latest

### PR DESCRIPTION
**Pull request by OyePradumya**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15198)

### CODE REVIEW

**Comment by OyePradumya** [comment]
@msftbot @KaranKad @ChuckFerring @jamespik please look into this. This has all the parameters set right, installs without user intervention, but here it doesn't pass. I guess this is an error. I tried this same manifest on 3 different systems and it worked just fine. Here @wingetbot fails it. Please help.

**Comment by OfficialEsco** [comment]
Well, my Firewall don't like Systweak

image
image
image

**Comment by OyePradumya** [comment]
> Well, my Firewall don't like Systweak
> 
> image
> image
> image

Sir but Validation-Unattended-Failed is for user input right? When the installer doesn't proceed without user input then this tag is labelled. For that the application must be downloaded and installer must have popped up. I am asking you to please turn off the firewall and test. I guess this is an issue in here

**Comment by OfficialEsco** [comment]
It fails because of a .NET Framework dependency.
image

**Comment by OyePradumya** [comment]
> It fails because of a .NET Framework dependency.
> image

Wow! Is there any fix for this?

**Comment by OfficialEsco** [comment]
No https://github.com/microsoft/winget-cli/issues/163

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 12/15/2023 7:49:41 PM 
Installer Verification Analysis Context Information: 
Specified hash doesn't match.
Actual hash:   9ADA0257EEA815D62A977D668F0FE22DAA99BA4BA41D23FA36A9FCA5F895F3EA
Expected hash: cbdf0dd0ab9d576aa0e231e8b3210b713b5df88b339739259195815521860ea1

**Comment by stephengillie** [comment]
Hi @OyePradumya,

The hash for this package is incorrect. But when I try to suggest a correct hash, I get an error that the branch has been removed. Has the branch been modified?

**Pull request closed without merging**
