### PR TITLE
Please add Icecat version 115.8.0esr

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140964)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  MSI (s) (84:B0) [01:41:06:290]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.38.33135. Product Version: 14.38.33135. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (84:40) [01:41:07:384]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Additional Runtime - 14.38.33135. Product Version: 14.38.33135. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [164C:1E44][2024-02-26T01:41:04]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 818.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  MSI (s) (84:B0) [01:41:06:290]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Minimum Runtime - 14.38.33135. Product Version: 14.38.33135. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. MSI (s) (84:40) [01:41:07:384]: Windows Installer installed the product. Product Name: Microsoft Visual C++ 2022 X64 Additional Runtime - 14.38.33135. Product Version: 14.38.33135. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 0. [164C:1E44][2024-02-26T01:41:04]w363: Could not create system restore point, error: 0x80070422. Continuing...

(Automated response - build 820.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  [1A8C:0CA0][2024-02-26T01:41:07]i500: Shutting down, exit code: 0x0 [1A8C:0CA0][2024-02-26T01:41:07]i007: Exit code: 0x0, restarting: No

(Automated response - build 821.)

**Comment by stephengillie** [comment]
Does this package have the wrong installer? 
Unsupported 16-bit application warning.

**Comment by alithechemist** [comment]
Hi, it is a 64bit installer, tested on win10.
I'll test it again ASAP.
Chip

**Comment by alithechemist** [comment]
> Does this package have the wrong installer? Unsupported 16-bit application warning.

Hi, indeed the installer was corrupted during transfer. 
The new installer is on place, you can try this whenever you want.
Thank you and sorry for the mistake.

Chip

**Comment by alithechemist** [comment]
Hi, is there anything i should do on my side?
Thanks!

**Comment by stephengillie** [comment]
Hi @alithechemist,

Yes, could you increment the `ManifestVersion` from `1.4.0` to `1.6.0`? We've depreciated the older versions, but the versions are so similar that in most cases, just incrementing the number is enough.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
