### PR TITLE
Updated Microsoft.OpenJDK.17 to 17.0.7

### PR DESCRIPTION
**Pull request by jmjaffe37**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/102970)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Review by mdanish-kh — CHANGES_REQUESTED** [review]
I'm surprised that the bot didn't comment the instructions for signing the CLA. Anyways,  you need to sign the CLA before your contributions are accepted. I'll copy-paste the bot message here:

> Please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.

```
@microsoft-github-policy-service agree [company="{your company}"]
```
 
> Options:
>
> * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
>
> ```
> @microsoft-github-policy-service agree
> ```
> 
> 
>     
>      
> 
> 
>      
>
> 
>      
>
> 
> * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> ```
> @microsoft-github-policy-service agree company="Microsoft"
> ```
> 
> Contributor License Agreement

**Comment by jmjaffe37** [comment]
@stephengillie do you know why the license/cla pipeline has not run yet for this PR? I believe this policy should pass since I am a Microsoft employee. It also looks like it has not run/passed on my other PR as well: https://github.com/microsoft/winget-pkgs/pull/102969

**Comment by jmjaffe37** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by stephengillie** [comment]
@denelon

**Comment by denelon** [comment]
@jmjaffe37 can you try without: company="Microsoft"

I'll ping the OSS team to see if this is a bug.

**Comment by jmjaffe37** [comment]
> @jmjaffe37 can you try without: company="Microsoft"
> 
> I'll ping the OSS team to see if this is a bug.

I tried both versions in my other PR (https://github.com/microsoft/winget-pkgs/pull/102969) and it still hasn't passed. I can try again here though

**Comment by jmjaffe37** [comment]
@microsoft-github-policy-service agree

**Comment by denelon** [comment]
@jmjaffe37 can you ping me on Teams?

**Comment by mdanish-kh** [comment]
Same feedback as https://github.com/microsoft/winget-pkgs/pull/102969#issuecomment-1521278981

**Comment by mdanish-kh** [comment]
@jmjaffe37 Same issue as pointed in https://github.com/microsoft/winget-pkgs/pull/102969#issuecomment-1521278981

**Pull request merged**
