### PR TITLE
Remove version: Tableau.Desktop version 24.2.1060

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/182702)

### CODE REVIEW

**Comment by SpecterShell** [comment]
@Exorcism0666 Could you close all the PRs related to Tableau? These installers are still available.

**Comment by stephengillie** [comment]
URL: https://downloads.tableau.com/esdalt/2024.2.3/TableauDesktop-64bit-2024-2-3.exe 
Response status code does not indicate success: 403 (Forbidden).

(Automated message - build 896)

**Comment by stephengillie** [comment]
Close with reason: Package still available.;

**Comment by stephengillie** [comment]
URL: https://downloads.tableau.com/esdalt/2024.2.3/TableauDesktop-64bit-2024-2-3.exe 
Response status code does not indicate success: 403 (Forbidden).

(Automated message - build 896)

**Pull request closed without merging**
