### PR TITLE
EA.Origin version 10.5.100.48178

### PR DESCRIPTION
**Pull request by mddtest**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/15601)

### CODE REVIEW

**Comment by mddtest** [comment]
Works via silent install and is different then the EA Desktop APP already submitted.

**Comment by mddtest** [comment]
EA has two different apps

EA Origin
EA Desktop (BETA)

**Comment by OfficialEsco** [comment]
Bro, read what it says in #10649

**Comment by OfficialEsco** [comment]
image

**Comment by mddtest** [comment]
I don't seem to be getting this error. fully uninstalled and re-ran and installs with no issues.

**Comment by ItzLevvie** [comment]
> I don't seem to be getting this error. fully uninstalled and re-ran and installs with no issues.

@mddtest: You'll see this error once you test your manifest inside a virtual machine

For now, Origin won't be added into the repository until package dependencies are supported by the Windows Package Manager because Origin requires a dependency that a clean installation of Windows doesn't have in order for the application to work correctly.

See more at https://github.com/microsoft/winget-cli/issues/163.

**Comment by mddtest** [comment]
> 
> 
> > I don't seem to be getting this error. fully uninstalled and re-ran and installs with no issues.
> 
> @mddtest: You'll encounter this error once you've tested your manifest inside of a VM.
> 
> For now, Origin won't be added into the repository until package dependencies are supported by the Windows Package Manager because Origin requires a dependency that a clean installation of Windows doesn't have in order for the application to work correctly.
> 
> Read more at [microsoft/winget-cli#163 (comment)](https://github.com/microsoft/winget-cli/issues/163#issue-618664416).

Thanks for the quick explanation.  learning quickly already submitted 2 pulls for other apps with out any issues.  I will start to use a VM for testing.

**Pull request closed without merging**
