### PR TITLE
clawSoft.clawPDF version 0.9.2

### LINKED ISSUE #105588: [Update Request]: clawSoft.clawPDF
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

clawSoft.clawPDF

### Package Version

0.9.2

### Please describe the changes you would like to see

There is a new release (0.9.2) available.
Download page Url: https://github.com/clawsoftware/clawPDF/releases

### PR DESCRIPTION
**Pull request by BrandonWanHuanSheng**
Please wait a while we are holding merge on another issue.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/105792)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
Why the validation failed? Still investigating.

**Comment by BrandonWanHuanSheng** [comment]
> Hello @BrandonWanHuanSheng,
> 
> The package manager bot determined there was an issue with one of the installers listed in the url field, and cannot continue.
> 
> The application included in this pull request failed to install during dynamic validation. This test is designed to ensure that the application installs on all environments without warnings. Please, verify that the application installs correctly on architectures specified in the manifest using winget cli.
> 
> Template: msftbot/validationError/installers/shellExecute

Could be win11 is alerting.

**Comment by BrandonWanHuanSheng** [comment]
> Hello @BrandonWanHuanSheng,
> 
> The package manager bot determined there was an issue with one of the installers listed in the url field, and cannot continue.
> 
> The application included in this pull request failed to install during dynamic validation. This test is designed to ensure that the application installs on all environments without warnings. Please, verify that the application installs correctly on architectures specified in the manifest using winget cli.
> 
> Template: msftbot/validationError/installers/shellExecute

It look like I still can't find the warning.

**Comment by BrandonWanHuanSheng** [comment]
@stephengillie  Did you know what is happening to this pipeline?

**Comment by BrandonWanHuanSheng** [comment]
@stephengillie Can you find where is the root cause of issue?

**Comment by Trenly** [comment]
The package has dependencies
```
INFO   : [05/03/2023 17:51:55:387] [CheckFX                                 ]: Property 'VSDNETMSG'  retrieved with value 'This setup requires the .NET Framework version [1].  Please install the .NET Framework and run this setup again.'.
INFO   : [05/03/2023 17:51:55:387] [CheckFX                                 ]: MsiSetPropertyW - Setting Property Value...
INFO   : [05/03/2023 17:51:55:387] [CheckFX                                 ]: MsiSetPropertyW - Setting property 'VSDNETMSG' to 'This setup requires the .NET Framework version v4.6.2.  Please install the .NET Framework and run this setup again.'.
|
INFO   : [05/03/2023 17:51:55:465] [VsdLaunchConditions                     ]: MsiRecordGetStringW - Getting value from column '2'...
To properly execute this program, you must have the Visual C++ Redistributable 14 installed. You can install the appropriate redistributable by selecting vc_redist.x86.exe for 32-bit Windows or vc_redist.x64.exe for 64-bit Windows. If you need to download and install it, click 'YES' to proceed to the download page.
```

**Comment by BrandonWanHuanSheng** [comment]
It look like that .NET Framework 4 can be enable from Windows App and Features.

**Comment by BrandonWanHuanSheng** [comment]
I am unable to add .NET Framework version v4.6.2. because it was blocked Windows Features.

**Comment by BrandonWanHuanSheng** [comment]
Because dependcies is still incomplete. It was blocked by Windows Features.

**Comment by BrandonWanHuanSheng** [comment]
It quite very noisy.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335226 
> 2023-05-04 10:14:12.893 [CLI ] ShellExecute installer failed: 1603 INFO   : [05/04/
> 2023 10:14:12:661] [VsdLaunchConditions                     ]: MsiSetPropertyW - Setting property 'HideFatalErrorForm' to 'TRUE'. ERROR  : [05/04/
> 2023 10:14:12:661] [VsdLaunchConditions                     ]: Custom Action failed with code: '1603' CustomAction VSDCA_VsdLaunchConditions returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox) Property(S): ErrorDialog = ErrorDialog Property(S): HideFatalErrorForm = TRUE MSI (s) (A0:18) [10:14:12:753]: Product: clawPDF 0.9.2 -- Installation failed. MSI (s) (A0:18) [10:14:12:753]: Windows Installer installed the product. Product Name: clawPDF 0.9.2. Product Version: 0.9.2. Product Language: 0. Manufacturer: Andrew Hess // clawSoft. Installation success or error status: 1603. 
> 2023-05-04 10:12:52.708 [CLI ] ShellExecute installer failed: 1603 INFO   : [05/04/
> 2023 10:12:52:268] [VsdLaunchConditions                     ]: MsiSetPropertyW - Setting property 'HideFatalErrorForm' to 'TRUE'. ERROR  : [05/04/
> 2023 10:12:52:283] [VsdLaunchConditions                     ]: Custom Action failed with code: '1603' MSI (s) (60:CC) [10:12:52:393]: Product: clawPDF 0.9.2 -- Installation failed. MSI (s) (60:CC) [10:12:52:393]: Windows Installer installed the product. Product Name: clawPDF 0.9.2. Product Version: 0.9.2. Product Language: 0. Manufacturer: Andrew Hess // clawSoft. Installation success or error status: 1603.

**Comment by BrandonWanHuanSheng** [comment]
> Automatic Validation ended with:
> > Installation failed with exit code -1978335226 
> > 2023-05-04 10:14:12.893 [CLI ] ShellExecute installer failed: 1603 INFO   : [05/04/
> > 2023 10:14:12:661] [VsdLaunchConditions                     ]: MsiSetPropertyW - Setting property 'HideFatalErrorForm' to 'TRUE'. ERROR  : [05/04/
> > 2023 10:14:12:661] [VsdLaunchConditions                     ]: Custom Action failed with code: '1603' CustomAction VSDCA_VsdLaunchConditions returned actual error code 1603 (note this may not be 100% accurate if translation happened inside sandbox) Property(S): ErrorDialog = ErrorDialog Property(S): HideFatalErrorForm = TRUE MSI (s) (A0:18) [10:14:12:753]: Product: clawPDF 0.9.2 -- Installation failed. MSI (s) (A0:18) [10:14:12:753]: Windows Installer installed the product. Product Name: clawPDF 0.9.2. Product Version: 0.9.2. Product Language: 0. Manufacturer: Andrew Hess // clawSoft. Installation success or error status: 1603. 
> > 2023-05-04 10:12:52.708 [CLI ] ShellExecute installer failed: 1603 INFO   : [05/04/
> > 2023 10:12:52:268] [VsdLaunchConditions                     ]: MsiSetPropertyW - Setting property 'HideFatalErrorForm' to 'TRUE'. ERROR  : [05/04/
> > 2023 10:12:52:283] [VsdLaunchConditions                     ]: Custom Action failed with code: '1603' MSI (s) (60:CC) [10:12:52:393]: Product: clawPDF 0.9.2 -- Installation failed. MSI (s) (60:CC) [10:12:52:393]: Windows Installer installed the product. Product Name: clawPDF 0.9.2. Product Version: 0.9.2. Product Language: 0. Manufacturer: Andrew Hess // clawSoft. Installation success or error status: 1603. 
> 
> InstallationVerification-x86-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20230504171252
> 

Look like .NET Framework 4.6.2 is blocked by the Windows Features. Because That Windows Features use higher version .NET Framework 4.8

**Comment by stephengillie** [comment]
> @stephengillie Look like .NET Framework 4.6.2 is blocked by the Windows Features. Because That Windows Features use higher version of .NET Framework 4.8 blocking the .NET Framework 4.6.2 Setup.

This might also be due to only the first dependency being installed. 
* https://github.com/microsoft/winget-cli/issues/2202

**Comment by BrandonWanHuanSheng** [comment]
Marking pull request as draft

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Comment by BrandonWanHuanSheng** [comment]
Can anyone retry running the pipeline?

**Comment by BrandonWanHuanSheng** [comment]
Hmm, it look like I already set the dependcies in.

**Comment by stephengillie** [comment]
Manual Validation ended with:
>  2023-10-04 17:03:43.577 [CLI ] Starting installer selection.
2023-10-04 17:03:43.577 [CLI ] Installer [X64,exe,Unknown,en-US] not applicable: Architecture was excluded by caller : X64
2023-10-04 17:03:43.580 [CLI ] No suitable installer found for manifest Microsoft.DotNet.Framework.DeveloperPack_4 with version 4.8.1
2023-10-04 17:03:43.581 [CLI ] Terminating context: 0x8a150104 at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DependenciesFlow.cpp:11a

**Comment by stephengillie** [comment]
* https://github.com/microsoft/winget-pkgs/issues/121946

**Comment by BrandonWanHuanSheng** [comment]
How about this pull request?

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
