### PR TITLE
update bottom to 0.6.4

### PR DESCRIPTION
**Pull request by ClementTsang**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/27478)

### CODE REVIEW

**Review by ImJoakim — CHANGES_REQUESTED** [review]
Please use the updated metadata that was added in #23668.

I would highly suggest using [winget-create](https://github.com/microsoft/winget-create) to easily update manifests with the latest metadata.

You can manually install it via the link above or install it via `winget install wingetcreate`.

**Comment by ClementTsang** [comment]
Thanks for the heads up, I'll take a look!

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/27478#pullrequestreview-752399773

**Comment by ClementTsang** [comment]
> I would highly suggest using winget-create to easily update manifests with the latest metadata.

Gonna open a new PR due to some branch mess, but just as some feedback, I tried using winget-create, and could *not* figure it out, and eventually hit API limits... so I guess I'll just manually create it for now.

**Comment by ryfu-msft** [comment]
Hey @ClementTsang,

I noticed you had some issues with the update command for Winget-Create and we are working on making improvements. The reason for the mismatch is that the existing manifest is expecting a ***neutral msi***, but we detected the installer to be an ***x64 msi***. 

Fortunately, in our latest release of Winget-Create, we added an interactive update flag for you to manually fix those mismatches by running

```powershell
wingetcreate update Clement.bottom -v <Version> -i
```

We hope you try it out, and feel free to tag me or create a new GitHub issue if it doesn't behave as you expected.

Thanks!

**Pull request closed without merging**
