### PR TITLE
Update manifest (PackageName): RealVNC.VNCServer version 7.8.0

### LINKED ISSUE #150613: [Package Issue]: RealVNC.VNCViewer, RealVNC.VNCServer
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The package name of VNC server is not correct (should be like the viewer):

Name| Id |Version|Match|Source
--- | --- | --- | --- |---
RealVNC Viewer  |                 RealVNC.VNCViewer  |              7.8.0 |        Tag: vnc |winget
**VNC Server** *   |                 RealVNC.VNCServer  |              7.8.0  |       Tag: vnc |winget

* should be "RealVNC Server"

### Steps to reproduce

No steps necessary

### Actual behavior

Name| Id |Version|Match|Source
--- | --- | --- | --- |---
RealVNC Viewer  |                 RealVNC.VNCViewer  |              7.8.0 |        Tag: vnc| winget
VNC Server   |                 RealVNC.VNCServer  |              7.8.0  |       Tag: vnc| winget|

### Expected behavior

Name| Id |Version|Match|Source
--- | --- | --- | --- |---
RealVNC Viewer  |                 RealVNC.VNCViewer  |              7.8.0 |        Tag: vnc| winget
RealVNC Server   |                 RealVNC.VNCServer  |              7.8.0  |       Tag: vnc| winget

### Environment

```raw
Windows Package Manager v1.7.10861
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19045.4291
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.22.10861.0
```

### Screenshots and Logs

_No response_

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] It's related to #150613, but unable to solve it.

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150625)

### CODE REVIEW

**Comment by Dragon1573** [comment]
It seems the server blocks `winget.exe` from downloading installer file. We are unable to submit it to the repository. 😞

```text
21:41:45 (base) D:\...\winget-pkgs issues/150613/7.8.0 ≡ 1ms pwsh> curl.exe -I `
> 'https://downloads.realvnc.com/download/file/viewer.files/VNC-Viewer-7.10.0-Windows-64bit.exe'
HTTP/1.1 405 Not Allowed
Server: CloudFront
Date: Tue, 23 Apr 2024 13:41:49 GMT
Content-Length: 2111
Connection: keep-alive
x-amzn-waf-action: captcha
Cache-Control: no-store, max-age=0
Content-Type: text/html; charset=UTF-8
X-Cache: Error from cloudfront
Via: 1.1 a3b511649bade26170091701ae26b616.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: SFO53-C1
X-Amz-Cf-Id: hIdGJRpCJqbIkLO64NfbjRTNJDfP7K9l_yQvmZRBo0LHmA_6j-C8nw==
```

**Comment by Dragon1573** [comment]
```text
21:43:54 (base) D:\...\winget-pkgs issues/150613/7.8.0 ≡ 2ms pwsh> winget download -e RealVNC.VNCServer
已找到 VNC Server [RealVNC.VNCServer] 版本 7.8.0
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://downloads.realvnc.com/download/file/vnc.files/VNC-Server-7.8.0-Windows.exe
执行此命令时发生意外错误：
Download request status is not success.
0x80190195 : ��ֹʹ�÷���(405)��
```

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> URI: https://downloads.realvnc.com/download/file/vnc.files/VNC-Server-7.8.0-Windows.exe, Validation result: Failed, Http status code: MethodNotAllowed

(Automated response - build 877.)

**Comment by Dragon1573** [comment]
> [!CAUTION]
>
> _RealVNC_ download server prevents `winget.exe` from downloading the installer file. Users will get `HTTP 405 Method Not Allowed` error.
>
> The manifest is no longer valid, and may need to be removed from the repository.

**Comment by stephengillie** [comment]
Hi @Dragon1573,

This manifest removes Apps and Features entries that are present in previous PR versions. These entries should be added to this version, to maintain version matching, and prevent the 'upgrade always available' situation with this package.

(Automated response - build 877.)

**Comment by vikingnope** [comment]
@Dragon1573 I think it's best if we close this PR since mine will be up and running soon: 

#151045

**Comment by Dragon1573** [comment]
> @Dragon1573 I think it's best if we close this PR since mine will be up and running soon:
> 
> #151045

Okay, this pull request will be closed without being merged.

> I implemented your fix as well

Oh! Thank you ❤️

**Pull request closed without merging**
