### PR TITLE
changed Zeit to Vercel

### PR DESCRIPTION
**Pull request by deadlynjdj**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/39579)

### CODE REVIEW

**Comment by deadlynjdj** [comment]
image

changed many versions of the file but it is in the correct place

**Comment by OfficialEsco** [comment]
You cannot change multiple manifest at the same time, also that is not how the Publisher field works.
VirtualBoxVM_gaOfJOBSwE

**Comment by deadlynjdj** [comment]
i will just do the latest tks for the info

**Comment by OfficialEsco** [comment]
The info will still be wrong and not accepted.

**Pull request closed without merging**
