### PR TITLE
Speed-Soft.Time-Sync.Client version 1.8.9.0

### PR DESCRIPTION
**Pull request by Speed7811**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/102193)

### CODE REVIEW

**Comment by stephengillie** [comment]
> Url validation error
> 
> * manifests\s\Speed-Soft\Time-Sync\Client\1.8.9.0
>   
>   * https://www.speed-soft.de
>     
>     * Http status code: BadGateway
>   * https://www.speed-soft.de/contact/
>     
>     * Http status code: BadGateway
>   * https://www.speed-soft.de/privacy/
>     
>     * Http status code: BadGateway
>   * https://www.speed-soft.de/software/licenses/
>     
>     * Http status code: BadGateway
>   * https://www.speed-soft.de/software/time_sync/details/releaseinfos.php?id=37
>     
>     * Http status code: BadGateway
>   * https://www.speed-soft.de/software/time_sync/details/releaseinfos.php
>     
>     * Http status code: BadGateway

This server appears to be having a network issue:
image

Often, this HTTP 502 response is generated by a CDN when its source is not responding, a load balancer when none of its servers are in the healthy pool, and by individual server kernels when their webserver threads are not responding.

**Comment by Speed7811** [comment]
@stephengillie: yes my provider changed some settings but it seems in the result that my site is down now :( . I think tomorrow the 502 is solved. I will give a feedback when it works.

**Comment by Speed7811** [comment]
Please can you start it again. My website is online now and my provider made an exception for the IP range 20.40.0.0/13.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
