### PR TITLE
New version: Nushell.Nushell version 0.96.0

### PR DESCRIPTION
**Pull request by fdncred**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164303)

### CODE REVIEW

**Comment by fdncred** [comment]
Any hint of why this is failing? The last few releases have gone through without a hitch. Today we make a release, without changing any of our msi creation process, and it fails.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-07-24 07:46:45.013 [FAIL] Installer failed security check. Url: https://github.com/nushell/nushell/releases/download/0.96.0/nu-0.96.0-x86_64-pc-windows-msvc.msi Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 886.)

**Comment by fdncred** [comment]
@stephengillie is that from the most recent check because the first time we tried with this release there was a defender false positive. so, i recompiled everything and create a new msi and the false positive went away.

**Comment by stephengillie** [comment]
Hi @fdncred,

Yes, that error is from the most recent run's logs. I've heard that it's possible to submit some type of "false positive form" to the Defender team, and request a scan from their team. Since we depend on the Defender service, once it's clear there, and an updated version is released, it should pass our scan too.

**Comment by fdncred** [comment]
The new version doesn't have any defender issues, so the validation here should've passed.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-07-25 08:04:14.283 [FAIL] Installer failed security check. Url: https://github.com/nushell/nushell/releases/download/0.96.0/nu-0.96.0-x86_64-pc-windows-msvc.msi Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 887.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
