### PR TITLE
New version: Vendicated.Vencord.Canary version 1.4.0

### PR DESCRIPTION
**Pull request by sharunkumar**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/191253)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978334972
> 2024-11-13 13:30:09.787 [CLI ] No suitable installer found for manifest Discord.Discord.Canary with version 1.0.478

Automated error analysis suggests -1978334972 may mean This package has a dependency missing from your system.

(Automated response - build 897.)

**Comment by stephengillie** [comment]
HI @sharunkumar,

Manual Validation ended with:
image

Is there a way to bypass this prompt and complete the install silently?

**Comment by sharunkumar** [comment]
> Is there a way to bypass this prompt and complete the install silently?

looks like passing `-install -branch canary` makes it auto install without the prompt. ill update the manifest

**Comment by sharunkumar** [comment]
@stephengillie when I run the exe from shell, it doesn't pop-out a new window:
image

but when run via winget install, it pops out a new console window

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue
[Policy] Interactive-Only-Installer

**Pull request closed without merging**
