### PR TITLE
New package: Gigabyte.GigabyteControlCenter version 24.01.02.01

### PR DESCRIPTION
**Pull request by rakleed**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135046)

### CODE REVIEW

**Comment by rakleed** [comment]
What is wrong?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 

(Automated response - build 586.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 

(Automated response - build 588.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-17T08:12:36.9962121Z ##[error] One or more errors occurred. (The file was not found. Verify git path must match with the casing of the file in disk. Not found file on 'manifests\g\Gigabyte\GigabyteControlCenter\24.01.02.01\Gigabyte.GigabyteControlCenter.installer.yaml') The file was not found. Verify git path must match with the casing of the file in disk. Not found file on 'manifests\g\Gigabyte\GigabyteControlCenter\24.01.02.01\Gigabyte.GigabyteControlCenter.installer.yaml'

(Automated response - build 589.)

**Comment by stephengillie** [comment]
This package installs and launches normally on a Windows 10 VM.

**Comment by rakleed** [comment]
@stephengillie

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-17T19:53:18.1739013Z ##[error] One or more errors occurred. (The file was not found. Verify git path must match with the casing of the file in disk. Not found file on 'manifests\g\Gigabyte\GigabyteControlCenter\24.01.02.01\Gigabyte.GigabyteControlCenter.installer.yaml') The file was not found. Verify git path must match with the casing of the file in disk. Not found file on 'manifests\g\Gigabyte\GigabyteControlCenter\24.01.02.01\Gigabyte.GigabyteControlCenter.installer.yaml'

(Automated response - build 602.)

**Comment by rakleed** [comment]
@stephengillie

> Hello @rakleed,
> 
> The package manager bot determined there was an issue with the pull request. Make sure the manifest files are under the manifests\partition\publisher\appname\version directory and only one package version is being modified in your PR. The partition of the path must be the first letter of the publisher in lower-case.
> 
> Example: Path: manifests / m / Microsoft / WindowsTerminal / 1.6.10571.0 / WindowsTerminal.yaml
> 
> For details on the error, see the details link below in the build pipeline.
> 
> You may also try the [Windows Package Manager Manifest Creator](https://github.com/microsoft/winget-create)
> 
> Template: msftbot/validationError/pullRequest

**Comment by rakleed** [comment]
I didn't change WindowsTerminal. What is the problem?

**Comment by rakleed** [comment]
> Hello @rakleed,
> 
> The package manager bot determined there was an issue with the pull request. Make sure the manifest files are under the manifests\partition\publisher\appname\version directory and only one package version is being modified in your PR. The partition of the path must be the first letter of the publisher in lower-case.
> 
> Example: Path: manifests / m / Microsoft / WindowsTerminal / 1.6.10571.0 / WindowsTerminal.yaml
> 
> For details on the error, see the details link below in the build pipeline.
> 
> You may also try the [Windows Package Manager Manifest Creator](https://github.com/microsoft/winget-create)
> 
> Template: msftbot/validationError/pullRequest

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
It's a casing issue with the publisher folder.

There's already a `GIGABYTE` (all upper-case) folder in this repository, and this pull request contains `Gigabyte` (first letter is upper-case and the rest is lower-case) which causes duplicate folder names.

So `PackageIdentifier` needs to be `GIGABYTE.GigabyteControlCenter` and the `Gigabyte` folder needs to be changed to `GIGABYTE` as well as the file names from `Gigabyte.GigabyteControlCenter` to `GIGABYTE.GigabyteControlCenter`.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
