### PR TITLE
cristiano100.roforge version 0.1

### PR DESCRIPTION
**Pull request by Cristiano100**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/120423)

### CODE REVIEW

**Comment by Cristiano100** [comment]
@stephengillie

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by Trenly** [comment]
The issue is resolved when using the PreRelease client which has dependencies as stable
[Policy] Dependencies

**Review by Trenly — CHANGES_REQUESTED** [review]

**Comment by Trenly** [comment]
Dependencies are now supported in the 1.6 client. If you could please submit a new manifest for the latest version of the package, it would be greatly appreciated!

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 1/4/2024 9:36:05 PM
 Installer Verification Analysis Context Information: 
 Specified hash doesn't match.
 Actual hash:   52078C951B5995B1020B63DD7C0BDCB33037FE2E9102D1675A80ADECC85651CD
 Expected hash: 032e3293563edcba08bf52b887b2e34f2e9df00ff310fa8046ae44bbe6a1b014

(Automated response - build 518.)

**Comment by stephengillie** [comment]
Hi @Cristiano100,

The package hash has apparently changed to `52078C951B5995B1020B63DD7C0BDCB33037FE2E9102D1675A80ADECC85651CD`. Unfortunately, GitHub doesn't easily allow me to suggest this hash.

**Pull request closed without merging**
