### PR TITLE
New version: dotenvx.dotenvx 1.11.3

### PR DESCRIPTION
**Pull request by motdotenv**
New version: dotenvx.dotenvx 1.11.3
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/169947)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-08-28 16:30:54.282 [FAIL] Installer failed security check. Url: https://github.com/dotenvx/dotenvx/releases/download/v1.11.3/dotenvx-1.11.3-windows-x86_64.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 891.)

**Comment by motdotla** [comment]
@stephengillie how can it be failing a security check? there are no security issues: https://www.virustotal.com/gui/url/2d5a829fc81042ecd6319a7a9debfa38134a0ac2bc4da0c5acdaeb0c21aa44f0?nocache=1

**Comment by motdotla** [comment]
could this be related to it being a cli rather than a windows form?

related: https://github.com/microsoft/winget-pkgs/pull/169603 and https://github.com/microsoft/winget-pkgs/pull/169176

**Comment by stephengillie** [comment]
No, this is definitely failing a Defender or similar scan. Based on the 80004005 code, it might be reporting that the installer file has already been quarantined or deleted.

**Comment by motdotla** [comment]
ok i will add a defender check to our github actions pipeline if i can - to try and debug. but isnt virustotal also/already a defender check? that is passing.

**Comment by stephengillie** [comment]
Oh - maybe the zip file was quarantined or deleted. I don't work directly with the pipeline VMs, so I'm not completely sure of the OS state from these logs alone.

**Comment by motdotla** [comment]
what does quarantined mean in this context and how can i repair that? seems like i have no control over this process? is there someone i can talk to who runs the vms?

**Comment by stephengillie** [comment]
Quarantined refers to the antivirus application moving a file to another location, to prevent it from being executed. We could request advice from internal team members, who do work with the VMs - but please understand these VMs are just running common Defender scans, and that our team doesn't work directly with the Defender teams. We also have no control over the outcome of Defender scans. 

I have heard (and seen screenshots) from other community members, who have submitted their packages to a Defender or similar website, and after a confirmed negative result, had their package pass and become merged. But again, I haven't worked directly with these and this is all I know of them.

**Comment by motdotla** [comment]
ok i will hope for that then currently. frustrating process. i've also submitted to microsoft's security intelligence for whitelisting - where it has been deemed to have no malware.

image

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\dotenvx.dotenvx__DefaultSource\dotenvx.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\dotenvx.exe returned exit code: 1

(Automated response - build 891.)

**Review by stephengillie — APPROVED** [review]

**Comment by motdotla** [comment]
thank you @stephengillie

**Pull request merged**
