### PR TITLE
Add: Bazel.Bazelisk version 1.14.0

### PR DESCRIPTION
**Pull request by cperrin88**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/83190)

### CODE REVIEW

**Comment by cperrin88** [comment]
@microsoft-github-policy-service agree

**Comment by zachcarp** [comment]
@cperrin88 Good morning. I've gone through the logs, and installed this and everything seems to finish successfully, however, I can't get it to do anything. Should this package have a dependency on Bazel? Do I need to install Bazel for it to properly function?

**Comment by cperrin88** [comment]
Running the command `bazelisk` should download the newest bazel version to `%LocalAppData%\bazelisk` and run it.

This is the expected output:
```
2022/10/13 10:12:17 Downloading https://releases.bazel.build/5.3.1/release/bazel-5.3.1-windows-x86_64.exe...
WARNING: Invoking Bazel in batch mode since it is not invoked from within a workspace (below a directory having a WORKSPACE file).
                                                           [bazel release 5.3.1]
Usage: bazel <command> <options> ...

Available commands:
  analyze-profile     Analyzes build profile data.
  aquery              Analyzes the given targets and queries the action graph.
  build               Builds the specified targets.
  canonicalize-flags  Canonicalizes a list of bazel options.
  clean               Removes output files and optionally stops the server.
  coverage            Generates code coverage report for specified test targets.
  cquery              Loads, analyzes, and queries the specified targets w/ configurations.
  dump                Dumps the internal state of the bazel server process.
  fetch               Fetches external repositories that are prerequisites to the targets.
  help                Prints help for commands, or the index.
  info                Displays runtime info about the bazel server.
  license             Prints the license of this software.
  mobile-install      Installs targets to mobile devices.
  print_action        Prints the command line args for compiling a file.
  query               Executes a dependency graph query.
  run                 Runs the specified target.
  shutdown            Stops the bazel server.
  sync                Syncs all repositories specified in the workspace file
  test                Builds and runs the specified test targets.
  version             Prints version information for bazel.

Getting more help:
  bazel help <command>
                   Prints help and options for <command>.
  bazel help startup_options
                   Options for the JVM hosting bazel.
  bazel help target-syntax
                   Explains the syntax for specifying targets.
  bazel help info-keys
                   Displays a list of keys used by the info command.
```

**Comment by ryfu-msft** [comment]
Hey @cperrin88,

Does this package have a dependency on the Microsoft C++ Redistributable package? When running in a clean sandbox, we were able to install successfully, but running the executable did not show the expected output. If that is the case, can you add the correct [Microsoft.VCRedist](https://github.com/microsoft/winget-pkgs/tree/master/manifests/m/Microsoft/VCRedist) package as a package dependency to the manifest? Here is an [example](https://github.com/microsoft/winget-pkgs/blob/92b8d5d7727aa641aa3d758dbd653a4c8ba4ec8c/manifests/v/VMware/WorkstationPro/16.2.3/VMware.WorkstationPro.installer.yaml#L20-L23).

**Comment by cperrin88** [comment]
@ryfu-msft You are correct. I have added the dependency like in the example.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
