### PR TITLE
New package: vivainio.RoughGrep

### PR DESCRIPTION
**Pull request by vivainio**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/182568)

### CODE REVIEW

**Comment by vivainio** [comment]
@microsoft-github-policy-service agree

**Comment by vivainio** [comment]
This implements issue #182569

**Comment by Dragon1573** [comment]
> [!TIP]
>
> Modify your [very first comment](https://github.com/microsoft/winget-pkgs/pull/182568#issue-2583871748) of this pull request as follows, can help linking this pull request to the related issue. When this pull request is successfully merged, the linked issue can also be closed as completed. ❤️
>
> ```diff
>   Checklist for Pull Requests
> 
>   - [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
> - - [x] Is there a linked Issue?
> + - [x] Resolve #182569
> ```

**Comment by Dragon1573** [comment]
> [!TIP]
>
> 1. Your package is published via _GitHub Releases_.
> 2. _GitHub Actions_ is enabled for your source repository.
>
> Are you willing to maintain your package with [WinGet Releaser v2](https://github.com/marketplace/actions/winget-releaser)? This can simplify your "manifest submission" process and speed up request reviewing and approval.

**Comment by stephengillie** [comment]
This application runs, but not from the symlink. Verify while here:
image

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Although adding `BurntSushi.ripgrep.MSVC` as a `Dependencies > PackageDependencies`, _RoughGrep_ still unable to launch via symbolic link.

```patch
diff --git a/manifests/v/vivainio/RoughGrep/3.14.3/vivainio.RoughGrep.installer.yaml b/manifests/v/vivainio/RoughGrep/3.14.3/vivainio.RoughGrep.installer.yaml
index c3df286b0a1..70110e1605d 100644
--- a/manifests/v/vivainio/RoughGrep/3.14.3/vivainio.RoughGrep.installer.yaml
+++ b/manifests/v/vivainio/RoughGrep/3.14.3/vivainio.RoughGrep.installer.yaml
@@ -8,6 +8,9 @@ NestedInstallerType: portable
 NestedInstallerFiles:
 - RelativeFilePath: RoughGrep\rgg.exe
   PortableCommandAlias: rgg
+Dependencies:
+  PackageDependencies:
+  - PackageIdentifier: BurntSushi.ripgrep.MSVC
 Installers:
 - Architecture: x64
   InstallerUrl: https://github.com/vivainio/RoughGrep/releases/download/v3.14.3/RoughGrep-3.14.3.zip
```

image
image

**Comment by Trenly** [comment]
@vivainio - Support for zipped binaries has now been added and is available in the pipelines. This will require you to update your submission to ManifestVersion: 1.9.0 and set ArchiveBinariesDependOnPath: true in the installer node. To keep things clean, this PR is being closed. Please submit a new PR for the latest version of this package. Thank you for your contributions!

**Pull request closed without merging**
