### PR TITLE
New package: advaith.CurrencyConverterPowerToys version 1.2.0

### LINKED ISSUE #171129: [Package Request]: PowerToys-Run-Currency-Converter
### How can we help?

None

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/releases/tag/v1.2.0
Publisher: advaith3600
Package Name: PowerToys-Run-Currency-Converter
Description: PowerToys Run plugin which will convert real and crypto currencies.
Package Version: 1.2.0
Installer URLs: 
- https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/releases/download/v1.2.0/CurrencyConverter-1.2.0-x64.exe
- https://github.com/Advaith3600/PowerToys-Run-Currency-Converter/releases/download/v1.2.0/CurrencyConverter-1.2.0-ARM64.exe

### PR DESCRIPTION
**Pull request by Advaith3600**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #171129

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

### CODE REVIEW

**Comment by Advaith3600** [comment]
@stephengillie Hi, could you help me understand if the issue with Internal-Error-Dynamic-Scan is something being messed up on my end? I have updated the manifest file in this PR with more details on the package. 

The plugin will install properly with or without PowerToys running, but a restart is required for it to list the contents. Even with the restart if you cannot view any output, it is likely the issue with the HTTP requests failing in the first try. Clearing the prompt and trying it again will fix the issue.

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Comment by stephengillie** [comment]
> @ stephengillie Hi, could you help me understand if the issue with Internal-Error-Dynamic-Scan is something being messed up on my end? I have updated the manifest file in this PR with more details on the package.

I'm not entirely sure why this package always gets the "IEDS" label. Here's more background on that label: 
- https://github.com/microsoft/winget-pkgs/discussions/155218

> The plugin will install properly with or without PowerToys running, but a restart is required for it to list the contents. Even with the restart if you cannot view any output, it is likely the issue with the HTTP requests failing in the first try. Clearing the prompt and trying it again will fix the issue.

A reboot is required? Sure enough, after rebooting it works as described:
image
The installer doesn't seem to add a Registry entry.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
