### PR TITLE
TorProject.Tor: new package

### PR DESCRIPTION
**Pull request by soredake**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/127334)

Depends on: https://github.com/microsoft/winget-cli/issues/2899

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\TorProject.Tor__DefaultSource\tor-expert-bundle-windows-x86_64-13.0.1.tar.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.

**Comment by stephengillie** [comment]
Manual Validation ended with:
> PS C:\Users\User\Desktop> C:\Users\User\AppData\Local\Microsoft\WinGet\Links\tor.exe
Program 'tor.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1 
char:1
...
> 
> PS C:\Users\User\Desktop> C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\TorProject.Tor__DefaultSource\tor.exe
Program 'tor.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1
char:1
...
> 
> PS C:\Users\User\Desktop>

**Comment by soredake** [comment]
This pr is waiting for https://github.com/microsoft/winget-cli/issues/2899 to be implemented first.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
 Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\TorProject.Tor__DefaultSource\tor-expert-bundle-windows-x86_64-13.0.1.tar.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\TorProject.Tor__DefaultSource\tor-expert-bundle-windows-x86_64-13.0.1.tar.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions) Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\tor.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\tor.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.

**Comment by stephengillie** [comment]
Manual Validation ended with:
> PS C:\Users\User\Desktop> C:\Users\User\AppData\Local\Microsoft\WinGet\Links\tor.exe
Program 'tor.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1
char:1
> C:\Users\User\AppData\Local\Microsoft\WinGet\Links\tor.exe
...
C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\TorProject.Tor__DefaultSource\tor.exe
Program 'tor.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1
char:1
> C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\TorProject.Tor_ ...
...
PS C:\Users\User\Desktop>

**Comment by stephengillie** [comment]
Hi @soredake,

These applications continually give the same error. Should I be launching these in a different way?

**Comment by soredake** [comment]
@stephengillie winget can't unpack .tar.gz yet, errors are expected. I'll close this pr until .tar.gz support is implemented.

**Pull request closed without merging**
