### PR TITLE
upgrade version

### PR DESCRIPTION
**Pull request by Sharkboy-j**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/17674)

### CODE REVIEW

**Comment by KaranKad** [comment]
Try adding 
```
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.dotnetRuntime
    MinimumVersion: 5.0.6.30021
```

**Comment by JeremiSharkboy** [comment]
> Looks like .net runtime requires restart to work properly, so it might not work.

=(

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
I'm seeing this, even though I've .NET 3.5, .NET 4 & .NET 5 installed on my device:
image

**Comment by JeremiSharkboy** [comment]
This is strange. It may be necessary to install .NET **Desktop** Runtime 5.0.7 x86 or x64. Im not sure

**Comment by ItzLevvie** [comment]
It works with the x86 one (I had x64 installed on my machine) but the version seems different from the one written in the manifest:
image

**Comment by JeremiSharkboy** [comment]
> It works with the x86 one (I had x64 installed on my machine) but the version seems different from the one written in the manifest:
> image
> 
> In the manifest: it's `0.9.7837.24720` and in the application it's `0.9.7838.20204`

Thats correct. That is because of autoupdater integrated into app

**Comment by ItzLevvie** [comment]
since the app works with the x86 runtime rather than the x64 one, could you perhaps make the message a bit more clearer as to which one the user should download?

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
