### PR TITLE
New version: C-PartnerSystemhausGmbH.QuickFinder version 4.4.36

### PR DESCRIPTION
**Pull request by kyndadumb**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/183866)

### CODE REVIEW

**Comment by kyndadumb** [comment]
Is there any kind of error message? We've had a false malware detection from Microsoft Defender, changed the setup, now the defender isn't alarming on our MSI and I was able to install error-free with this manifest.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-10-18 00:20:46.739 [FAIL] Installer failed security check. Url: https://download.c-partner.com/WinGet/4.4.36/QuickFinder.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Comment by stephengillie** [comment]
Hi @kyndadumb,

> Is there any kind of error message? We've had a false malware detection from Microsoft Defender, changed the setup, now the defender isn't alarming on our MSI and I was able to install error-free with this manifest.

Can you find the `Security intelligence version` in use? I'll try to match it with the version used in the pipelines. It's possible that your system might have had a slightly newer version than the last pipeline run.

**Comment by kyndadumb** [comment]
Hi @stephengillie,

thanks for the reply. On my client the `Security intelligence version` is `1.419.572.0`. I just tried installing again with my manifests which worked, as the screenshot shows.

winget_install

2024-10-18 18_24_27-Windows-Sicherheit

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
