### PR TITLE
New version: qBittorrent.qBittorrent version 4.3.8

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Here we go again

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/26231)

### CODE REVIEW

**Comment by jedieaston** [comment]
@OfficialEsco Tests won't run until you take it out of draft mode.

**Review by jedieaston — APPROVED** [review]
I know this is draft and we're at the mercy of Defender, but it works on my machine.

image

**Comment by OfficialEsco** [comment]
rip

**Comment by jedieaston** [comment]
It passes VirusTotal. There isn’t a list of antimalware software that step runs, is there?

**Review by jedieaston — CHANGES_REQUESTED** [review]
~~Maybe it would be worth trying to use the [FOSSHub mirror](https://www.fosshub.com/qBittorrent.html) instead?~~

nvm, see https://github.com/microsoft/winget-pkgs/pull/25178#issuecomment-900508433

**Comment by OfficialEsco** [comment]
https://github.com/microsoft/winget-pkgs/pull/25178#issuecomment-900508433

**Comment by jedieaston** [comment]
Oof. Thanks for the link.

**Comment by nopeinomicon** [comment]
Definitely would like to see this get through!

**Comment by jedieaston** [comment]
Why were these closed? Isn't this still an ongoing issue?

**Comment by ItzLevvie** [comment]
Read the latest comment from https://github.com/microsoft/winget-pkgs/pull/373#issuecomment-962492417.

Forgot to filter out draft PRs rather than just Blocking-Issue ones.

**Pull request closed without merging**
