### PR TITLE
New version: Jackett.Jackett version 0.21.1454

### PR DESCRIPTION
**Pull request by ilike2burnthing**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132103)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 
> 2023-12-29 08:20:48.627 [FAIL] Installer failed security check. Url: https://github.com/Jackett/Jackett/releases/download/v0.21.1454/Jackett.Installer.Windows.exe Result: 0x80004005

(Automated response - build 508.)

**Comment by stephengillie** [comment]
Hi @ilike2burnthing,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 509.)

**Comment by ilike2burnthing** [comment]
Definitely a false positive - https://www.virustotal.com/gui/file/316493ac14a72905065d344f886f65909b0e860366e6f4377d53f0a420ff4262

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
