### PR TITLE
New version: xpipe-io.xpipe version 8.3

### PR DESCRIPTION
**Pull request by crschnick**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/143772)

### CODE REVIEW

**Comment by crschnick** [comment]
I submitted this automatically with wingetcreate. Do I need to tick the boxes in the post manually?

**Comment by stephengillie** [comment]
Hi @crschnick,

> This PR's version number 8.3 has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 0.65.2, which has 3 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 869)

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
> Yeah the ProductCode isn't really necessary here I think

Agreed - my notes say that ProductCode can help when the installed application's ProductCode is different from the installer, and in this case it's only needed in 1 manifest.

**Comment by crschnick** [comment]
> Hi @crschnick,
> 
> > This PR's version number 8.3 has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 0.65.2, which has 3 parameters.
> 
> Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)
> 
> (Automated response - build 869)
> 
> Edit: my automation made an error here:
> 
> ```powershell
> PS C:\ManVal> winget search xpipe-io.xpipe
> Failed when searching source; results will not be included: msstore
> Name           Id                      Version Source
> ------------------------------------------------------
> XPipe          xpipe-io.xpipe          8.2     winget
> XPipe Portable xpipe-io.xpipe.portable 1.5.3   winget
> PS C:\ManVal>
> ```

Yes, the versioning scheme was changed. The portable package is a very old one that is no longer maintained.

image

**Pull request merged**
