### PR TITLE
Added dotUltimate version 2020.3.4.

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with winget validate <manifest>, where <manifest> is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with winget install -m <manifest>?

----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/8904)

### CODE REVIEW

**Comment by jedieaston** [comment]
The manifest is not compliant because the command line switches are more than 100 characters in length. The manifest currently in the repo has the same switches, is there any way around this?

**Comment by denelon** [comment]
@yao-msft I know we had talked about field sizes with the new schema. Is this something we can enable sooner rather than later to  allow this package manifest? I believe the new max length is 512.

**Comment by yao-msft** [comment]
The fix was checked in last week, should be included in our next round of prod deployment.

**Comment by jedieaston** [comment]
Looks like it’s still failing due to the switches being over 100 characters in length.

**Pull request merged**
