### PR TITLE
CS-Script v4.8.20.0

### PR DESCRIPTION
**Pull request by oleg-shilo**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/190116)

### CODE REVIEW

**Comment by oleg-shilo** [comment]
Not sure what why the WinGerSvc-Validation check is failing. The details page has no indication of the failure except a single line `Result: Result: Failed`
https://dev.azure.com/shine-oss/winget-pkgs/_build/results?buildId=23822&view=logs&j=68997d86-8ece-5ae8-3ac5-ccdbfa458731&t=b79910ce-dca5-5e27-ad7f-bd285eecb5a2&l=37

Running the package locally succeeds.

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-11-08 22:17:13.945 [FAIL] Installer failed security check. Url: https://github.com/oleg-shilo/cs-script/releases/download/v4.8.20.0/cs-script.win.v4.8.20.0.zip Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

Automated error analysis suggests 80004005 may mean Resource missing

(Automated response - build 897.)

**Review by stephengillie — APPROVED** [review]

**Comment by oleg-shilo** [comment]
@stephengillie, Thank you for your response. In this case, the failure was caused by the package containing the new `cs-script.net7.7z` file in one of the subfolders of the package. 

However, it was a lucky guess as there was no information about the actual cause of the 'failed security check'.
Steven, is it possible somehow to access the detailed info? Most likely the validation log contains some reference to the offender (cs-script.net7.7z). But how one can access it? I am not sure that even you saw it...

**Comment by stephengillie** [comment]
Hi @oleg-shilo,

This might have been covered in another thread - the "failed security check" might come from one of a number of sources. Unfortunately, the amount of information emitted has been reduced. We're working on a "log exfiltration" system, but as an engineering project, it's needed scheduling and developer time.

**Pull request merged**
