### PR TITLE
Remove old version of JanDeDobbeleer.OhMyPosh

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
null

### CODE REVIEW

**Review by OfficialEsco — DISMISSED** [review]

**Comment by vedantmgoyal2009** [comment]
I can't find anyway how to fix the issue. Please help if anyone knows...

**Comment by OfficialEsco** [comment]
Broken installer since https://github.com/microsoft/winget-pkgs/pull/36220 passed

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> I can't find anyway how to fix the issue. Please help if anyone knows...

Have you closed and re-opened the PR again?

image
image

Installer Scan sometimes falls under Validation-Installation-Error as well because the installation failed due to virus scan, but the pipelines doesn't treat it as Binary-Validation-Error.

PR #29248 got Validation-Installation-Error because of that error message, but passed several days later when I was able to get the installer working on my bare-metal machine.

**Comment by vedantmgoyal2009** [comment]
> but passed several days later when I was able to get the installer working on my bare-metal machine

I don't think it will work.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
