### PR TITLE
Update TI Connect CE version

### PR DESCRIPTION
**Pull request by NathanBnm**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/36111)

### CODE REVIEW

**Comment by jedieaston** [comment]
Duplicate of #36114

**Comment by NathanBnm** [comment]
> Duplicate of #36114

This is not a duplicate. There is a difference between "TI Connect" and "TI Connect CE" softwares.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
This cannot be added due to driver installation:
image

**Comment by NathanBnm** [comment]
There is no way to allow driver installation?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> There is no way to allow driver installation?

At the moment, no.

Several other applications, like Cura or Arduino 1.8.16+, as an example are currently blocked because of driver installation.

WinGet will accept interactive-only installers (so the user will have to interact with the driver install) in the future, but it's not currently implemented in the client right now.

**Pull request closed without merging**
