### PR TITLE
New package: staniel359.muffon.portable version 2.0.1

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/133478)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification.
>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by Trenly** [comment]
@exorcism0666 - Why isn't this just included with `staniel359.muffon` as a new installer node? Users will be able to select the portable version with `--installer-type portable`

**Comment by Exorcism0666** [comment]
@Trenly
image

**Comment by Trenly** [comment]
> @Trenly image

I disagree with @stephengillie. It would not be a duplicate installer if you set `InstallerType: portable`

`InstallerType: exe` is only for exes that install a program, not exes which are loose binaries

**Comment by Trenly** [comment]
In fact - the current version of muffon is actually correct

https://github.com/microsoft/winget-pkgs/blob/5c894ce8522d5caa65060d2970b06a628d7bd2d1/manifests/s/staniel359/muffon/1.6.0/staniel359.muffon.installer.yaml#L14-L23

**Review by Trenly — CHANGES_REQUESTED** [review]
Per discussion above, should be part of main package as it is for version 1.6.0

**Comment by stephengillie** [comment]
> I disagree with @stephengillie. It would not be a duplicate installer if you set `InstallerType: portable`

I was unaware that InstallerType could be used in this way. Thanks for educating me.

**Pull request closed without merging**
