### PR TITLE
New version: YouXiao.YXCalendar version 2.4.1.10

### PR DESCRIPTION
**Pull request by SpecterShell**
This pull request is automatically generated by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings) in [#3103](https://github.com/SpecterShell/Dumplings/actions/runs/7491003114)
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/133710)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-11T15:45:48.7715152Z Processing manifest: manifests\y\YouXiao\YXCalendar\2.3.12.20
 2024-01-11T15:45:48.7729704Z -----------------------------------------------------
 2024-01-11T15:45:48.7737483Z Status: Started
 2024-01-11T15:45:48.7745765Z Manifest file is Deleted
 2024-01-11T15:45:49.0875562Z Status: Completed
 2024-01-11T15:45:49.0891061Z ##[error] Result: Failed
 2024-01-11T15:45:49.0893806Z ##[error] Sequence contains no elements
 2024-01-11T15:45:49.1508747Z ##[error]Manifest Validation Failed

(Automated response - build 602.)

**Comment by drshtmstry** [comment]
> Sequence contains no elements

- #133371

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-29T20:28:28.2376637Z Processing manifest: manifests\y\YouXiao\YXCalendar\2.3.12.20
 2024-01-29T20:28:28.2386099Z -----------------------------------------------------
 2024-01-29T20:28:28.2393654Z Status: Started
 2024-01-29T20:28:28.2401488Z Manifest file is Deleted
 2024-01-29T20:28:28.5435791Z Status: Completed
 2024-01-29T20:28:28.5446985Z ##[error] Result: Failed
 2024-01-29T20:28:28.5475990Z ##[error] Sequence contains no elements
 2024-01-29T20:28:28.6208511Z ##[error]Manifest Validation Failed

(Automated response - build 675.)

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
