### PR TITLE
Add version: Piriform.CCleaner version 6.08

### LINKED ISSUE #94475: Piriform.CCleaner - Too verbose of version in manifest
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

The version stated in the manifest is too verbose for what the installer puts in the registry after install. Currently, even on latest version of the app, winget still states that there is a update waiting for it due to it comparing 6.08, what the installer puts in the registry as the version, to 6.08.10255, which is what the manifest states as the version expected. 

### Steps to reproduce

Upgrade CCleaner to the latest version and then check for updates using winget

### Actual behavior

Winget always states that there is a update ready even though there isn't 

### Expected behavior

The manifest and the registry key information align, winget doesn't show a false update listing

### Environment

```shell
Windows Package Manager (Preview) v1.4.3132-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.22621.1105
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.3132.0
```

### Screenshots and Logs

image

### PR DESCRIPTION
**Pull request by Trenly**
﻿- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

* Resolves #94475
* Resolves #94383

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/94481)

### CODE REVIEW

**Review by mdanish-kh — APPROVED** [review]
Version used in ReleaseNotes is `6.08.10255` https://www.ccleaner.com/ccleaner/release-notes. We could set this to PackageVersion and use `6.08` as DisplayVersion which would also make this consistent with [Piriform.CCleaner.ProTrial](https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/Piriform/CCleaner/ProTrial/6.08.10255).

But then again, we would run into the problem with version ranges and would need to add DisplayVersion to every manifest so I'm inclined towards this change.

**Comment by stephengillie** [comment]
Sandbox gives error:
> Pull request 94481 does not contain any manifest.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
