### PR TITLE
Fix semantic issues in manifests/m/Mp3tag/Mp3tag/3.20 per repology

### PR DESCRIPTION
**Pull request by Trenly**
* Related to microsoft/winget-pkgs#113794
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/144606)

### CODE REVIEW

**Review by OfficialEsco — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 870.)

**Comment by stephengillie** [comment]
Hi @Trenly,

This manifest adds Apps and Features entries that aren't present in previous PR versions. These entries should be added to the previous versions, or removed from this version.

(Automated response - build 870.)

**Comment by Trenly** [comment]
> Hi @Trenly,
> 
> This manifest adds Apps and Features entries that aren't present in previous PR versions. These entries should be added to the previous versions, or removed from this version.
> 
> (Automated response - build 870.)

Pretty sure it doesn't 😄

**Comment by mdanish-kh** [comment]
[Policy] reset feedback

**Review by mdanish-kh — APPROVED** [review]

**Pull request merged**
