### PR TITLE
New package: iPerf.iPerf3 version 3.1.3

### PR DESCRIPTION
**Pull request by solomoncyj**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135640)

### CODE REVIEW

**Comment by solomoncyj** [comment]
.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 642.)

**Comment by SNMetamorph** [comment]
Finally somebody introduced iperf3 package, thank you

**Review by ItzLevvie — APPROVED** [review]

**Comment by solomoncyj** [comment]
@stephengillie is the issue still blocking?

**Comment by ItzLevvie** [comment]
It's still blocked.

https://github.com/microsoft/winget-pkgs/labels/Moderator-Approved is a bug in my script which I use to automate approvals using GitHub CLI.

```
Enter a pull request number: 135640

Manifest validation succeeded.
Found iPerf3 [iPerf.iPerf3] Version 3.1.3
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://iperf.fr/download/windows/iperf-3.1.3-win64.zip
  ██████████████████████████████  1.33 MB / 1.33 MB
Successfully verified installer hash
Extracting archive...
Successfully extracted archive
Starting package install...
Command line alias added: "iperf3"
Path environment variable modified; restart your shell to use the new value.
Successfully installed

Name          : iPerf3
Publisher     : iPerf
Version       : 3.1.3
ProductCode   : iPerf.iPerf3__DefaultSource
Registry Path : Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Uninstall\iPerf.iPerf3__DefaultSource
Uninstall     : winget uninstall --id "iPerf.iPerf3__DefaultSource"

Press any key to continue . . .
```

```
PS C:\Users\WDAGUtilityAccount> echo $env:PATH
C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Users\WDAGUtilityAccount\AppData\Local\Microsoft\WindowsApps;C:\Users\WDAGUtilityAccount\AppData\Local\Microsoft\WinGet\Links;
PS C:\Users\WDAGUtilityAccount> dir C:\Users\WDAGUtilityAccount\AppData\Local\Microsoft\WinGet\Links


    Directory: C:\Users\WDAGUtilityAccount\AppData\Local\Microsoft\WinGet\Links


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---l          9/7/2024  11:39 AM              0 iperf3.exe


PS C:\Users\WDAGUtilityAccount> iperf3.exe -v
```

```
PS C:\Users\WDAGUtilityAccount\AppData\Local\Microsoft\WinGet\Packages\iPerf.iPerf3__DefaultSource\iperf-3.1.3-win64> iperf3 -v
iperf 3.1.3
CYGWIN_NT-10.0  2.5.1(0.297/5/3) 2016-04-21 22:14 x86_64
Optional features available: None
```

**Pull request closed without merging**
