### PR TITLE
Microsoft git installer options

### LINKED ISSUE #595: microsoft.git not respecting --disable-interactivity flag in winget
- [x] I was not able to find an [open](https://github.com/microsoft/git/issues?q=is%3Aopen)
        or [closed](https://github.com/microsoft/git/issues?q=is%3Aclosed) issue matching
        what I'm seeing, including in [the `git-for-windows/git` tracker](https://github.com/git-for-windows/git/issues).

### Setup

 - Which version of `microsoft/git` are you using? Is it 32-bit or 64-bit?

```
$ git --version --build-options

git version 2.40.1.vfs.0.2
cpu: x86_64
built from commit: 59bc9667c84164a4ad879d9b424687ca631f01b3
sizeof-long: 4
sizeof-size_t: 8
shell-path: /bin/sh
feature: fsmonitor--daemon
```

Are you using Scalar or VFS for Git?

Scalar

If VFS for Git, then what version?

```
$ gvfs version

GVFS 1.0.18081.2
```

 - Which version of Windows are you running? Vista, 7, 8, 10? Is it 32-bit or 64-bit?
```
$ cmd.exe /c ver

Microsoft Windows [Version 10.0.19045.3208]
```

 - Any other interesting things about your environment that might be related
   to the issue you're seeing?

These operations were performed in an administrative CMD prompt.

### Details

 - Which terminal/shell are you running Git from? e.g Bash/CMD/PowerShell/other

CMD

 - What commands did you run to trigger this issue? If you can provide a
   [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve)
   this will help us understand the issue.

```
winget install Microsoft.Git –disable-interactivity
```
 - What did you expect to occur after running these commands?

With the “—disable-interactivity” flag I expect no pop-ups. 

 - What actually happened instead?

However, since I had multiple git background processes running, it still gave me a pop-up even though I set the “—disable-interactivity” flag. The prompt was `The following process(es) use Git for Windows. Please terminate those processes and retry.` I know this is expected; however, there shouldn't be a prompt if “—disable-interactivity” flag is set.

If you run `winget --help`, it mentions ` --disable-interactivity   Disable interactive prompts`.

 - If the problem was occurring with a specific repository, can you specify
   the repository?

   * [ ] Public repo: **insert URL here**
   * [ ] Windows monorepo
   * [x] Office monorepo
   * [x] Other Microsoft-internal repo: any silo repo
   * [ ] Other internal repo.

### PR DESCRIPTION
**Pull request by derrickstolee**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

This resolves microsoft/git#595.

The `microsoft/git` manifest has lagged behind the `git/git` manifest, so let's catch it up a bit.

The biggest change is the additonal `InstallerSwitches` which fix the pop-ups that happen if there is another Git process running at the same time. I've checked that the pop-up is instead converted to a log message (and is not repeated, like the UI version does):

```
2023-08-09 13:18:29.491   Defaulting to Cancel for suppressed message box (Retry/Cancel):
                          The following process(es) use Git for Windows:
                          
                          bash.exe (PID 17664)
                          ssh-agent.exe (PID 6948)
                          MSYS2 terminal (PID 23020)
                          bash.exe (PID 14908)
                          ssh-agent.exe (PID 15748)
                          bash.exe (PID 2208)
                          ssh-agent.exe (PID 17104)
                          winpty.exe (PID 9088)
                          
                          Please terminate those processes and retry.
                          Alternatively, cancel to abandon setup altogether.
```
 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/116034&drop=dogfoodAlpha

### CODE REVIEW

**Review by mjcheetham — APPROVED** [review]

**Comment by ldennington** [comment]
Thanks so much for doing this! Would you mind elaborating a bit on how you tested these changes? I attempted to test using the [Sandbox ](https://github.com/microsoft/winget-pkgs/blob/master/doc/tools/SandboxTest.md) and got a popup with the `--disable-interactivity` flag. But that could have just been oddness with the Sandbox - I manually modified the script to add the flag, so it's possible I goofed on that.

**Review by mdanish-kh — APPROVED** [review]

**Comment by derrickstolee** [comment]
> Hello derrickstolee,
> 
> The pull request encountered an internal error and has been assigned to a developer to investigate.
> 
> Template: msftbot/validationError/internalError

I looked at the Azure Pipeline output and couldn't decipher it.

The only thing I could think is that maybe this diff could help (but I'm not sure):

```diff
diff --git a/manifests/m/Microsoft/Git/2.40.1.0.2/Microsoft.Git.installer.yaml b/manifests/m/Microsoft/Git/2.40.1.0.2/Microsoft.Git.installer.yaml
index b0ff831ca0..b838ed1c4b 100644
--- a/manifests/m/Microsoft/Git/2.40.1.0.2/Microsoft.Git.installer.yaml
+++ b/manifests/m/Microsoft/Git/2.40.1.0.2/Microsoft.Git.installer.yaml
@@ -11,7 +11,6 @@ InstallModes:
 - interactive
 - silent
 - silentWithProgress
-Scope: machine
 InstallerSwitches:
   Custom: /SUPPRESSMSGBOXES /enable-component windowsterminal
 UpgradeBehavior: install
@@ -20,6 +19,7 @@ Commands:
 ElevationRequirement: elevatesSelf
 Installers:
 - Architecture: x64
+  Scope: machine
   InstallerUrl: https://github.com/microsoft/git/releases/download/v2.40.1.vfs.0.2/Git-2.40.1.vfs.0.2-64-bit.exe
   InstallerSha256: BE2736C241F67A3AF21736072BFD0EE522BCB2847C51BA4A309F4EAB985909CE
 ManifestType: installer
```

**Comment by stephengillie** [comment]
Hi @derrickstolee,

> I looked at the Azure Pipeline output and couldn't decipher it.

This `Internal-Error-Dynamic-Scan` is a catch-all error for pipeline failures. Unfortunately, something about the installation of `Git` conflicts with our Automatic Validation pipeline and so it always requires Manual Validation. Sorry for any concern caused.

**Pull request merged**
