### PR TITLE
New version: WestWind.MarkdownMonster version 3.3.5.0

### PR DESCRIPTION
**Pull request by kkbruce**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/157558)

### CODE REVIEW

**Comment by kkbruce** [comment]
* https://www.virustotal.com/gui/file/ccf83dc21940d73af3413b1a34ea9ea5620616de69340c32eaf7982115f66a80
* https://www.microsoft.com/en-us/wdsi/submission/cfc89199-f75a-4fc4-9eb3-75ea38232d97

**Comment by stephengillie** [comment]
I'm not sure if SmartScreen is connected to VirusTotal. The second link requires login. 

We should have a documentation section on how to check for reported viruses and malware, how to report false positives, and how to monitor the status of rescans. Such as you're doing in this PR. Would you have any interest in writing out some of the steps that you've followed?

**Comment by kkbruce** [comment]
Providing the VirusTotal link shows that there isn't risk in executing the file.

The second link indicates that response and processing are carried out each time based on the two links provided by the wingetbot. There is no problem with the results displayed by Microsoft Defender SmartScreen（MDS） each time, as shown in the figure below.

image

As a software user, I am not the developer or owner. However, I can confirm that there is no indication of any risk for any version of this MM software, whether on company computers (with dedicated antivirus software) or personal computers (Microsoft's built-in antivirus mechanism). The Microsoft Defender SmartScreen mechanism used by winget-pkgs only vaguely mentions risks without providing clearer information, and I am unsure how to address this with the developers.

I can't do much. I just put the software I like on winget-pkgs to enrich the winget ecosystem. Whether it can be listed depends entirely on MDS's mood. Information security is very important, so I will only accept getting it. Since the MDS of winget-pkgs has such strong opinions about MM, I should close the PR directly if we get blocked. Let's go with the flow and spend little effort on this. Based on past experiences, neither you nor I have not the power to refute MDS's results.

**Comment by kkbruce** [comment]
@stephengillie 
Thank you for your hard work. As mentioned above, I will still try to upload the new version, but if we encounter MDS issues, we'll just let it pass.

**Pull request closed without merging**
