### PR TITLE
Update: Todesk.Todesk version 4.0.0.0

### PR DESCRIPTION
**Pull request by SpecterShell**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/34686)

### CODE REVIEW

**Review by OfficialEsco — COMMENTED** [review]
I'm still getting 3.3.3.0 with the old hash

**Comment by SpecterShell** [comment]
That is strange. I can get 4.0.0.0 and the hash is correct.

**Comment by OfficialEsco** [comment]
Prolly some CND shenanigans, gotta wait for widespread release

**Review by ItzLevvie — APPROVED** [review]
Still seeing the same as of 13th of November 2021:
image

Still seeing the same as of 14th of November 2021:
image

**Comment by OfficialEsco** [comment]
wingetbot just noticed a hash missmatch https://github.com/microsoft/winget-pkgs/pull/35135, and it installed 4.0.0.0 for me now

**Pull request merged**
