### PR TITLE
Tyrrrz.DiscordChatExporter.GUI version 2.39

### PR DESCRIPTION
**Pull request by CanePlayz**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/98388)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @CanePlayz,

Very similar situation as #98389 - where the package installs normally, but requires `Microsoft.VCRedist.2015+.x64` and apparently `Microsoft.DotNet.DesktopRuntime.7` or a similar package to run - but in GUI form: 
image

**Comment by stephengillie** [comment]
This would have to be handled by an installer switch, or by dependency once support returns. But only the first dependency might be installed, when it's supported.

**Comment by CanePlayz** [comment]
Alright, thanks. Similar to the CLI version, I think it's best for me to wait until there is dependency support in winget to fix this problem.

**Comment by CanePlayz** [comment]
Ok I got it

**Comment by CanePlayz** [comment]
Nice, now everything works, didn't know there's a `portable` type before, but it perfectly fits for this program.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
