### PR TITLE
New version: ryanvolz.radioconda version 2023.07.26

### PR DESCRIPTION
**Pull request by BrandonWanHuanSheng**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/125030)

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
At the same time while wingetbot is validating the installation.

**Comment by BrandonWanHuanSheng** [comment]
It seem like there is a lot of file being installed.

**Comment by stephengillie** [comment]
Validation continues overnight.

**Comment by stephengillie** [comment]
Validation continues.

**Comment by stephengillie** [comment]
Scanning underway.

**Comment by stephengillie** [comment]
Validation completed. So many packages asked for `VCredist` that I'm re-running with it as a dependency.
image

**Comment by stephengillie** [comment]
This has already proceeded to the scanning stage. Unsure why yesterday took so long to install.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
