### PR TITLE
New package: PeteAndJohn.FSUIPC7 version 7.4.9

### LINKED ISSUE #145075: [Package Request]: FSUIPC7
### How can we help?

I would like someone else to build the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: http://www.fsuipc.com/
Publisher: Pete & John Dowson's Software
Package Name: FSUIPC7
Description: Used to connect to Microsoft Flight Simulator and add hotkeys etc..
Package Version: 7.4.9
Installer URL: https://fsuipc.simflight.com/beta/Install_FSUIPC7.zip

### PR DESCRIPTION
**Pull request by schembriaiden**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.1.0 :rocket:

Resolves: https://github.com/microsoft/winget-pkgs/issues/145075

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/145196)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 870.)

**Comment by Trenly** [comment]
image

**Comment by vikingnope** [comment]
I think this needs Microsoft Flight Simulator to be installed as a dependency

**Comment by stephengillie** [comment]
I don't see a manifest for Microsoft.FlightSimulator currently in the repo. It could be added.

**Comment by vikingnope** [comment]
I don't think we would be able to add it since its from Steam and needs to be purchased from before.

**Comment by stephengillie** [comment]
This sounds almost like it might work better as a DSC Config file. Some Config files install other package managers, and also call them to install packages. If `Valve.Steam` had a DSC resource, we might be able to construct a DSC Config file that would install Steam, install the prerequisite, then install this package. However, as you indicated and unlike most other package managers, Steam has a payment and paywall system.

**Pull request closed without merging**
