### PR TITLE
New package: SolveSpace.SolveSpace version 3.1

### PR DESCRIPTION
**Pull request by ruevs**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/118952)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @ruevs,

This package has a dependency on `VCRedist`:
image

**Comment by ruevs** [comment]
> Hi @ruevs,
> 
> This package has a dependency on `VCRedist`: 

[stephengillie](https://github.com/stephengillie) since one of our versions ([`solvespace.exe`](https://github.com/solvespace/solvespace/releases/download/v3.1/solvespace.exe)) does not depend on `VCRedist` I removed the one that does (`solvespace-openmp.exe`) rather than adding the dependency. If someone wants the multi-threaded version they can download it from the [official download page](https://solvespace.com/download.pl) which explicitly states that `VCRedist` may be required if not already installed.

**Comment by stephengillie** [comment]
Unfortunately, this other version appears to have the same dependency:
image

**Comment by ruevs** [comment]
> Unfortunately, this other version appears to have the same dependency:

Strange. I'll have to investigate.

If instead I add the dependency - what ate the implications?

**Comment by stephengillie** [comment]
I believe we are generally accepting dependencies since the 1.6 release.

**Comment by stephengillie** [comment]
This package installs and launches normally in a Windows 10 VM.

**Comment by ruevs** [comment]
Is there anything else I should do for this pull request, apart from waiting for a review?

**Comment by ruevs** [comment]
@stephengillie what should I do to help merge this pull request?

**Comment by stephengillie** [comment]
Hi @ruevs,

This PR fell through the cracks - very sorry about that.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
