### PR TITLE
Remove unneccessary AppsandFeaturesEntries * manifests/w/WindSolutions/CopyTransControlCenter/5.003/WindSolutions.CopyTransControlCenter.installer.yaml

### PR DESCRIPTION
**Pull request by Trenly**

### CODE REVIEW

**Review by mdanish-kh — APPROVED** [review]

**Comment by Trenly** [comment]
[Policy] Reset Labels

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 899.)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 900)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 903)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 903)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 904)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 904)

**Pull request merged**
