### PR TITLE
Kiwix.Wikivoyage version 2.0.9.0

### PR DESCRIPTION
**Pull request by Jaifroid**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/67356)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]
Validation Pipelines are having issues right now so you'll most likely need to wait until Monday for it to be fixed.

**Comment by Jaifroid** [comment]
@AmelBawa-msft Just like #66581 and #64900, this PR will need a waiver added.

Background for the other MS devs: these three apps (Kiwix JS, WikiMed by Kiwix and Wikivoyage by Kiwix) are all based on the same codebase, and they are all msix/appxbundle UWP apps authored in HTML/JS. Recently (approx since end of June) winget has not been able to validate these app types in Azure, despite their being signed correctly and despite the manifest correctly installing in winget. Please see screenshots below as evidence of this for this Wikivoyage app.

image

image

**Comment by Jaifroid** [comment]
@yao-msft Thank you for adding the waiver for this package.

**Pull request merged**
