### PR TITLE
Updated Skillbrains.Lightshot v5.5.0.7

### LINKED ISSUE #23757: Lightshot package bad hash
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

Installing lightshot (`Skillbrains.lightshot`) fails with the error `Installer hash does not match; to override this check use --force`
It could be malacious, but I assume  this is just a config issue.
it seems like the install link is `https://app.prntscr.com/build/setup-lightshot.exe` - I assume that's a permalink for the latest package? If so the hash will obv change.

Is there a solution for a case like this? It seems like a symptom of a larger problem with permalinks and versioning/hashing.

# Steps to reproduce
run `winget install Skillbrains.lightshot` on a system that does not have it

# Expected behavior
It will download and install the package without problems

# Actual behavior
Installer downloads the executable, but fails to run it stating the hash does not match.

# Environment

```none
Windows Package Manager v1.0.11692
Windows: Windows.Desktop v10.0.19043.1110
Package: Microsoft.DesktopAppInstaller v1.12.11692.0
```

### PR DESCRIPTION
**Pull request by ImJoakim**
Resolves #23757

image

```
PS C:\Users\Test> winget install -m "M:\Git\winget-pkgs\manifests\s\Skillbrains\lightshot\5.5.0.7"
Found Lightshot [Skillbrains.lightshot]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://app.prntscr.com/build/setup-lightshot.exe
  2.65 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23768)

### CODE REVIEW

**Comment by ImJoakim** [comment]
I can't change `l` to `L` in the file name, okay, let's do this then.

**Comment by ImJoakim** [comment]
Ah, okay.

**Comment by ImJoakim** [comment]
Oof

**Review by OfficialEsco — APPROVED** [review]
@palenshus ?
```
Please enter the pull request number: 23768
Checking if the directory path to the manifest has 5 folders.
Manifest validation succeeded.
Found Lightshot [Skillbrains.Lightshot]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://app.prntscr.com/build/setup-lightshot.exe
  2.65 MB
Successfully verified installer hash
Starting package install...
Successfully installed
Press any key to continue . . .
```
image
image

**Comment by vedantmgoyal2009** [comment]
Try closing and reopening the PR (Re-run the pipelines).

**Comment by ImJoakim** [comment]
They really don't like the bots, do they 😅

**Comment by OfficialEsco** [comment]
```
URI: https://app.prntscr.com/, Validation result: Failed, Http status code: Forbidden 
URI: https://app.prntscr.com/help.html, Validation result: Failed, Http status code: Forbidden 
URI: https://app.prntscr.com/privacy.html, Validation result: Failed, Http status code: Forbidden 
URI: https://prnt.sc/, Validation result: Failed, Http status code: Forbidden 
URI: https://app.prntscr.com/license.html, Validation result: Failed, Http status code: Forbidden 
URI: https://app.prntscr.com/license.html, Validation result: Failed, Http status code: Forbidden 
URI: https://app.prntscr.com/build/setup-lightshot.exe, Validation result: Failed, Http status code: Forbidden
```

They can probably add a .validation for the url, but i don't think the bot is allowed to download the exe, so it will most likely hate this more than it hates calibre

**Comment by ImJoakim** [comment]
> They can probably add a .validation for the url, but i don't think the bot is allowed to download the exe, so it will most likely hate this more than it hates calibre...
> 
> Might be worth contacting Lightshot?

Yeah, I'll shoot them an email.

**Comment by palenshus** [comment]
Yes, this isn't the sort of thing we can waive, since we can't even download the app to run antivirus against it. If the publisher could allow-list our bot, that would be great

**Comment by ImJoakim** [comment]
> Yes, this isn't the sort of thing we can waive, since we can't even download the app to run antivirus against it. If the publisher could allow-list our bot, that would be great

Alrighty, let's see what they say from my email that I sent earlier.

**Comment by ImJoakim** [comment]
Still waiting on a reply from the email I sent.

**Pull request closed without merging**
