### PR TITLE
ChunghwaTelecom.HiCOSClient version 3.1.0

### PR DESCRIPTION
**Pull request by MysticCereal**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/100112)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @MysticCereal,

The package installed normally, but one of the applications had a message when launched with the link in the Start menu: 
image

Is this expected?

**Comment by MysticCereal** [comment]
Hi @stephengillie,
That should not have happened. The DLL is located in C:\Windows\system32 and is used to read smart cards, therefore it is one of the dependencies this program requires. 

A clean install of Windows 11 22H2 indicates that the file is included in the OS by default. This error doesn't seem to be coming from the program. Could it be something wrong with the OS used in the testing environment?

**Comment by MysticCereal** [comment]
Update: Retested manifest with a clean install of Windows 11 22H2. No problems during installation nor opening the program. Shown in screenshot: what's expected when opening the program. (It reminds the user to plug the smart card into a card reader before starting the inspection process.)

**Comment by stephengillie** [comment]
> Hi @MysticCereal,
> 
> The package installed normally, but one of the applications had a message when launched with the link in the Start menu: image
> 
> Is this expected?

This may have been due to running on a sandbox, which is a reduced form of a VM. On a full VM, this error isn't present.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
