### PR TITLE
New version: YaSuenag.SimpleCom version 1.2.5

### PR DESCRIPTION
**Pull request by YaSuenag**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/187940)

### CODE REVIEW

**Comment by YaSuenag** [comment]
As I wrote in #187950 , this PR is an original, so this should be merged.

**Comment by ItzLevvie** [comment]
Close with reason: Duplicate;

**Comment by YaSuenag** [comment]
@ItzLevvie  
As I wrote before, this PR is an original PR to register my app (SimpleCom) to winget-pkgs. Could you reopen and review this PR?

**Comment by ItzLevvie** [comment]
Reopen with reason: null;

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
