### PR TITLE
r82.EmojiKeyboard version 1.0

### PR DESCRIPTION
**Pull request by Twig6943**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/102061)

### CODE REVIEW

**Review by Trenly — CHANGES_REQUESTED** [review]
We don't allow redistributing / hosting the executable on your own GitHub repo. Packages must come from an official source

**Comment by Twig6943** [comment]
//Close pull request I'll send the original dl link in another pull request but it is allowed for me to distrubite the software tho 
image

**Comment by Twig6943** [comment]
I deleted the repository I created but I tried to use the original download link with "wingetcreate new" and it doesnt work. What should I do? do I reupload the repository I made to github and we call it a day or is there a fix for the original download link
image
also here is the original site https://download.cnet.com/Emoji-Keyboard/3000-20418_4-77548075.html

**Comment by stephengillie** [comment]
> I deleted the repository I created but I tried to use the original download link with "wingetcreate new" and it doesnt work. What should I do? do I reupload the repository I made to github and we call it a day or is there a fix for the original download link image also here is the original site https://download.cnet.com/Emoji-Keyboard/3000-20418_4-77548075.html

The download is failing because the repository was deleted. The original site is a 3rd party download site, which is normally not allowed, but this developer doesn't appear to have their own site, and there doesn't appear to be a better link for this package.

**Comment by Twig6943** [comment]
hey the bot said the url is invalid since I deleted the repo can you close the pull request or do I reupload the repo as its the only option?

**Comment by stephengillie** [comment]
> hey the bot said the url is invalid since I deleted the repo can you close the pull request or do I reupload the repo as its the only option?

Sure, I can close the PR for you.

**Pull request closed without merging**
