### PR TITLE
New version: WHONET.2023 version 23.12.5

### PR DESCRIPTION
**Pull request by drshtmstry**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

### CODE REVIEW

**Comment by drshtmstry** [comment]
https://dev.azure.com/ms/winget-pkgs/_build/results?buildId=520615&view=logs&j=871b4eed-22de-5cb6-c1c8-82f190de633f&t=58bdf892-4e45-5ba7-4782-31912f95e167&l=38
How to see what error caused checks to fail?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -2145844845 
> 2023-12-07 14:52:40.527 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000 
> 2023-12-07 14:52:40.607 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FF970B51EFD: (caller: 00007FF970B527D0) Exception(1) tid(324) 80190193 Forbidden (403). 
> 2023-12-07 14:52:41.122 [CORE] Download request failed. Returned status: 403 
> 2023-12-07 14:52:41.123 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(67)\WindowsPackageManager.dll!00007FF970B11D0B: (caller: 00007FF970B12129) Exception(2) tid(324) 80190193 Forbidden (403). 
> 2023-12-07 14:52:41.191 [CLI ] Failed to download, waiting a bit and retry. Url: https://whonet.org/WHONET
> 2023-Setup-x64.exe 
> 2023-12-07 14:52:41.799 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000 
> 2023-12-07 14:52:41.799 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FF970B51EFD: (caller: 00007FF970B527D0) Exception(3) tid(324) 80190193 Forbidden (403). 
> 2023-12-07 14:52:41.856 [CORE] Download request failed. Returned status: 403 
> 2023-12-07 14:52:41.857 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(67)\WindowsPackageManager.dll!00007FF970B11D0B: (caller: 00007FF970B12129) Exception(4) tid(324) 80190193 Forbidden (403). 
> 2023-12-07 14:52:42.074 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(67)\WindowsPackageManager.dll!00007FF970B11D0B: (caller: 00007FF970B12129) Exception(4) tid(324) 80190193 Forbidden (403).

**Comment by Trenly** [comment]
> Maybe there should be a "user-agent spoof" setting for winget.

The issue isn’t with winget, actually. If it was, you wouldn't be able to install the manifest locally. The issue is with the actual validation process. Something specific about the server performing the validation is causing the error.

@stephengillie - I also don’t believe it is a user-agent issue, because if it was, then either the "Installer Scan" or the  "Urls Validation" would have been where the failure was. During the "Installation Validation" stage where it failed, it would be using the winget user agent and not the Azure user agent. Since the manifest installs fine locally, the publisher clearly isn’t blocking the winget user agent. Maybe its the publisher has used 403 instead of 429 and is blocking when repeated requests come from an Azure IP.

Regardless, the issue isn’t with the winget client and there isn’t anything we can do to unblock the validation pipeline unless the publisher whitelists Azure on whatever protections they have in place

**Comment by Trenly** [comment]
Okay, now that is interesting . . . It doesn't make sense why it would fail repeatedly and then suddenly work when the installer node didn't change.

**Review by Trenly — APPROVED** [review]

**Pull request merged**
