### PR TITLE
New version: JetBrains.dotUltimate version 2024.1

### PR DESCRIPTION
**Pull request by SpecterShell**
Created by [🥟 Dumplings](https://github.com/SpecterShell/Dumplings).
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/148421)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-04-10 10:54:24.976 [CLI ] ShellExecute installer failed: 4294967295

And in the full installer log: 

> 10:54:24.004 |W|                               | stderr << "240 installation errors occurred. Check the installer log for details."
10:54:24.005 |V|                               | The message above is written to the standard error and output streams. Terminating with the code -1
10:54:24.016 |V|                               | Forcing shutdown...

Examples of installation errors:

> 10:54:23.985 |I| InstallerViewModel            |   10:53:55.729 dotPeek241: Could not extract “ExternalAnnotations\.NETCore\System.Xml.ReaderWriter\Annotations.xml (in JetBrains.ExternalAnnotations.10.2.147)”, fatal error writing out the result. Object reference not set to an instance of an object.
10:54:23.985 |I| InstallerViewModel            |   10:53:55.761 dotPeek241: Could not extract “JetBrains.PsiFeatures.UIInteractive.Features.dll (in JetBrains.Psi.Features.UIInteractive.Features.241.0.20240408.85029)”, fatal error writing out the result. Object reference not set to an instance of an object.
10:54:23.986 |I| InstallerViewModel            |   10:53:55.769 dotPeek241: Could not extract “MahApps.Metro.dll (in JetBrains.MahApps.Metro.1.5.0.1)”, fatal error writing out the result. Object reference not set to an instance of an object.
10:54:23.986 |I| InstallerViewModel            |   10:53:55.777 dotPeek241: Could not extract “JetBrains.Decompiler.Core.dll (in JetBrains.Psi.Features.Core.241.0.20240408.85029)”, fatal error writing out the result. Object reference not set to an instance of an object.
10:54:23.986 |I| InstallerViewModel            |   10:53:56.091 dotPeek241: Could not extract “NetCore\runtimes\unix\lib\netcoreapp3.0\System.Windows.Forms.dll (in JetBrains.WindowsDesktop.Mock.Runtime.0.0.3)”, fatal error writing out the result. Object reference not set to an instance of an object.

**Comment by SpecterShell** [comment]
> Automatic Validation ended with:
> 
> > 2024-04-10 10:54:24.976 [CLI ] ShellExecute installer failed: 4294967295
> 
> And in the full installer log:
> 
> > 10:54:24.004 |W|                               | stderr << "240 installation errors occurred. Check the installer log for details."
> > 10:54:24.005 |V|                               | The message above is written to the standard error and output streams. Terminating with the code -1
> > 10:54:24.016 |V|                               | Forcing shutdown...
> 
> Examples of installation errors:
> 
> > 10:54:23.985 |I| InstallerViewModel            |   10:53:55.729 dotPeek241: Could not extract “ExternalAnnotations.NETCore\System.Xml.ReaderWriter\Annotations.xml (in JetBrains.ExternalAnnotations.10.2.147)”, fatal error writing out the result. Object reference not set to an instance of an object.
> > 10:54:23.985 |I| InstallerViewModel            |   10:53:55.761 dotPeek241: Could not extract “JetBrains.PsiFeatures.UIInteractive.Features.dll (in JetBrains.Psi.Features.UIInteractive.Features.241.0.20240408.85029)”, fatal error writing out the result. Object reference not set to an instance of an object.
> > 10:54:23.986 |I| InstallerViewModel            |   10:53:55.769 dotPeek241: Could not extract “MahApps.Metro.dll (in JetBrains.MahApps.Metro.1.5.0.1)”, fatal error writing out the result. Object reference not set to an instance of an object.
> > 10:54:23.986 |I| InstallerViewModel            |   10:53:55.777 dotPeek241: Could not extract “JetBrains.Decompiler.Core.dll (in JetBrains.Psi.Features.Core.241.0.20240408.85029)”, fatal error writing out the result. Object reference not set to an instance of an object.
> > 10:54:23.986 |I| InstallerViewModel            |   10:53:56.091 dotPeek241: Could not extract “NetCore\runtimes\unix\lib\netcoreapp3.0\System.Windows.Forms.dll (in JetBrains.WindowsDesktop.Mock.Runtime.0.0.3)”, fatal error writing out the result. Object reference not set to an instance of an object.

I think it is due to out of disk space:

```
10:42:25.152 |E| ExtractPackagesToBinDirTasks::ExtractInputPackagesAsync| Could not open the destination file at “C:\Program Files (x86)\JetBrains\Installations\dotPeek241\ExternalAnnotations\.NETFramework\System.Xml\I18n.xml” for writing out the package JetBrains.ExternalAnnotations.10.2.147 part DotFiles\ExternalAnnotations\.NETFramework\System.Xml\I18n.xml. There is not enough space on the disk.
```

**Comment by stephengillie** [comment]
That's unexpected - This package, plus the OS, consume just 30 GB in my VM: 
image

**Comment by stephengillie** [comment]
Hi @SpecterShell,

> This PR's version number "2024.1" has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 2023.3.4, which has 3 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 876)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
