### PR TITLE
Added ImageMagick version 7.1.1-30 that uses an msix installer instead.

### PR DESCRIPTION
**Pull request by dlemstra**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/148305)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @dlemstra, 

This seems like it should have the `PackageIdentifier` of `ImageMagick.ImageMagick`. The [most recent PR](https://github.com/microsoft/winget-pkgs/pull/148122/files) for that package didn't include MSIX installers, so a new PR could update that manifest to include these installers.

**Comment by dlemstra** [comment]
That other package was created by someone outside the @ImageMagick team. That package contains a different kind of build so I don't want to replace it. We are also planning to add a `ImageMagick.Q8` and `ImageMagick.Q16` package in the future.

**Comment by stephengillie** [comment]
Verify:
image
Advanced options:
image

**Review by stephengillie — APPROVED** [review]

**Comment by github-account1111** [comment]
@dlemstra why not indicate the difference in the package name? I had to dig through old commits to figure this out because the two are named identically.

It also doesn't help that there doesn't appear to be an MSIX option on the [official download page](https://imagemagick.org/script/download.php#windows).

It's also confusing that the exe download mentions DLL while the MSIX download doesn't. The aforementioned download page recommends the DLL version. Is there a DLL version of the MSIX?

**Pull request merged**
