### PR TITLE
VMWare HorizonClient: Fixed package version number to prevent false upgrade notices

### PR DESCRIPTION
**Pull request by pxwiz**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/119123)

### CODE REVIEW

**Comment by pxwiz** [comment]
> Hello @pxwiz,
> 
> The package manager bot determined there was an issue with one of the installers listed in the url field, and cannot continue.
> 
> The application included in this pull request failed to install during dynamic validation. This test is designed to ensure that the application installs on all environments without warnings. Please, verify that the application installs correctly on architectures specified in the manifest using winget cli.
> 
> Template: msftbot/validationError/installers/shellExecute

The manifest contains a single architecture - x86 & I verified the application installs without any issues, before submitting the PR.

Request manual verification & override the package manager bot.

Thanks.

**Comment by pxwiz** [comment]
> The manifest contains a single architecture - x86 & I verified the application installs without any issues, before submitting the PR.
> 
> \winget-pkgs>winget install -m manifests\v\VMware\HorizonClient\8.10.0.37628 **Found VMware Horizon Client [VMware.HorizonClient] Version 8.10.0.37628** This application is licensed to you by its owner. Microsoft is not responsible for, nor does it grant any licenses to, third-party packages. **Successfully verified installer hash Starting package install... Successfully installed**
> 
> Request manual verification & override the package manager bot.
> 
> Thanks.

The manifest contains a single architecture - x86 & I verified the application installs without any issues, before submitting the PR.

\winget-pkgs>winget install -m manifests\v\VMware\HorizonClient\8.10.0.37628
Found VMware Horizon Client [VMware.HorizonClient] Version 8.10.0.37628
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Successfully installed

Request manual verification & override the package manager bot.

Thanks.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2023-09-07 23:17:05.099 [CLI ] Starting: 'C:\Users\VALIDA~1\AppData\Local\Temp\WinGet\VMware.HorizonClient.8.10.0.37628\VMware-Horizon-Client-2306-8.10.0-21964678.exe' with arguments '/silent /log "C:\Users\validator\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-VMware.HorizonClient.8.10.0.37628-2023-09-07-23-17-05.098.log" /norestart'
2023-09-07 23:17:42.151 [CLI ] ShellExecute installer failed: 2147942487
2023-09-07 23:17:42.152 [CLI ] Terminating context: 0x8a150006 at

**Comment by stephengillie** [comment]
Hi @pxwiz,

Manual Validation has completed. Were the branch not deleted, we could reopen the PR, provide the waiver (override), and then merge the commit.

**Comment by pxwiz** [comment]
> Hi @pxwiz,
> 
> Manual Validation has completed. Were the branch not deleted, we could reopen the PR, provide the waiver (override), and then merge the commit.

Thanks @stephengillie.  Have restored the branch & reopened the PR.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
