### PR TITLE
New version: Nushell.Nushell version 0.81.0

### PR DESCRIPTION
**Pull request by sitiom**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/109445&drop=dogfoodAlpha

### CODE REVIEW

**Comment by sitiom** [comment]
​

**Comment by fdncred** [comment]
@stephengillie I hate to call you out again to look at our broken submission but dang it, we just changed this msi so that it updates a per-user profile versus a per-system profile and it failed again. it's really frustrating to have every submission fail. i wonder what we can do better/different to make these work?

**Comment by Trenly** [comment]
@denelon / @stephengillie - Instead of just adding validation completed after manual validation, maybe this would be best as a shell-execute waiver?

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
> @denelon / @stephengillie - Instead of just adding validation completed after manual validation, maybe this would be best as a shell-execute waiver?

Yes, it's a bad habit I'm working to unlearn. I fell out of the waiver process when we were having an issue with automation removing wavers.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code -1978335226 
> 2MSI (s) (B8:5C) [08:36:59:941]: Product: nu -- Installation failed.
> 
> MSI (s) (B8:5C) [08:36:59:956]: Windows Installer installed the product. Product Name: nu. Product Version: 0.81.0. Product Language: 1033. Manufacturer: The Nushell Project Developers. Installation success or error status: 1603.

**Comment by fdncred** [comment]
> Automatic Validation ended with:
> 
> > Installation failed with exit code -1978335226
> > 2MSI (s) (B8:5C) [08:36:59:941]: Product: nu -- Installation failed.
> > MSI (s) (B8:5C) [08:36:59:956]: Windows Installer installed the product. Product Name: nu. Product Version: 0.81.0. Product Language: 1033. Manufacturer: The Nushell Project Developers. Installation success or error status: 1603.

I think this is the same issue it always fails with on this repo. However, if you run the installer, it works without issue. We thought the problem was installing to a system profile that needed authorization but now we're installing to a user profile, which each user should have access to. I'm really just throwing my hands up saying, "What can we try now?". 

version 0.80.0 https://github.com/microsoft/winget-pkgs/pull/106977#issuecomment-1551795077
version 0.79.0 https://github.com/microsoft/winget-pkgs/pull/103474 (no failure number listed, assume it's always been the same)

**Comment by fdncred** [comment]
> What would your preferred behavior be?

I'll ask the contributor who last modified our winget release. TBH, I'm sick of messing with it because we've had a dozen or so releases and maybe 1 or 2 have gone through without errors when the msi works fine running the install manually. Having said that, I personally lean toward "prohibitsElevation" because it sounds like the path of least resistance. However, I'm skeptical whether this will solve any problems. Not because I know better than anyone, but because we've tried a bunch of things and we always get an error.

**Pull request merged**
