### PR TITLE
KurtZimmermann.HDCleaner version 2.043

### PR DESCRIPTION
**Pull request by Info445**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/94995)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Info445,

The program installed in a sandbox, but gave an error when launched:
image

**Comment by Info445** [comment]
> Hi @Info445,
> 
> The program installed in a sandbox, but gave an error when launched: image

i must check this.thanks

**Review by OverRevvv — APPROVED** [review]

**Comment by Info445** [comment]
> > Hi @Info445,
> > The program installed in a sandbox, but gave an error when launched: image
> 
> i must check this.thanks

Works with Windows Sandbox
sandbox

**Comment by Info445** [comment]
> > > Hi @Info445,
> > > The program installed in a sandbox, but gave an error when launched: image
> > 
> > 
> > i must check this.thanks
> 
> Works with Windows Sandbox sandbox

Is HDCleaner installed? Installed in Temp Folder? Are all files in the same folder?

**Comment by Info445** [comment]
> > > Hi @Info445,
> > > The program installed in a sandbox, but gave an error when launched: image
> > 
> > 
> > i must check this.thanks
> 
> Works with Windows Sandbox sandbox

Is HDCleaner installed? Installed in Temp Folder? Are all files in the same folder?

**Pull request closed without merging**
