### PR TITLE
ARP/manifest update: RevoUninstaller.RevoUninstallerPro version 4.4.5

### PR DESCRIPTION
**Pull request by quhxl**
I am not sure about the architecture. It installs fine on x86, but is not listed as a 32-bit app in taskmgr.

- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/20778)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
> Pull request contains merge conflicts.

wut, do you have a resolve button? what does it suggest?

**Comment by quhxl** [comment]
> wut, do you have a resolve button? what does it suggest?

Nope, that's grayed out. (These conflicts are too complex to resolve in the web editor)

**Comment by OfficialEsco** [comment]
Oooooh, your repo is outdated, for example https://github.com/microsoft/winget-pkgs/pull/20596 is newer than the one you deleted, you should def rebase your repo now that YamlCreate.ps1 is updated :))

Do you want to update it (and add more metadata) or do you want me to do it?

**Comment by quhxl** [comment]
I often do it. But I should update my cloned repo eventually. Of course, by resetting the VM to a save point, I always jump back in time locally.

**Comment by quhxl** [comment]
@OfficialEsco But you can update the manifest. I'll close this PR.

**Comment by OfficialEsco** [comment]
Oh you create your Manifests on the VM? I would then suggest that you make a fancy git script which fetches the upstream and make a new branch for each PR (like the github client would do)

Aight 👍

**Pull request closed without merging**
