### PR TITLE
New version: reMarkable.reMarkableCompanionApp version 3.10.0.845

### LINKED ISSUE #150809: [Update Request]: reMarkable.reMarkableCompanionApp update to 3.10.0.845
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

reMarkable.reMarkableCompanionApp

### Package Version

3.10.0.845

### Please describe the changes you would like to see

New release available from this download URL: https://downloads.remarkable.com/latest/windows
Current package cannot install since hashes do not match

### PR DESCRIPTION
**Pull request by BiosPlus**
### Pull request has been created with [komac](https://github.com/russellbanks/Komac) v2.2.1 :rocket:

- Resolves #150809

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/150810)

### CODE REVIEW

**Review by stephengillie — APPROVED** [review]

**Comment by kris6673** [comment]
Hello, after the update the Install says it succeeds, but it does not install the application. Should I make a package issue issue for this instead of keeping this one alive? :)

**Comment by BiosPlus** [comment]
Good callout @kris6673, I'll give it a check.

It seems you're right, because it dumps the installer exe file into PATH, this is probably due to them changing the way that https://downloads.remarkable.com/latest/windows resolves, whereas it would previously link to the installer exe file, it now links to a zipped copy of it.

I'll do a quick experiment to see if I can solve for it.

**Comment by BiosPlus** [comment]
Figured it out, I'll resubmit it now

image

**Comment by kris6673** [comment]
> Figured it out, I'll resubmit it now
> 
> image

Nice, thank you!
Is it possible you could make a machine-wide/AllUsers package for it too? As far as i know, these are the commandline arguments needed to be passed to the EXE: "in --am --al -c AllUsers=true"

**Pull request merged**
