### PR TITLE
New Package: Avast.AvastAntivirus version 21.9.2494

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

```
PS C:\Users\Esco> winget install -m M:\a\Avast\AvastAntivirus\21.5.2470\
Found Avast Free Antivirus [Avast.AvastAntivirus]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading http://files.avast.com/iavs9x/avast_free_antivirus_setup_online.exe
  ██████████████████████████████  7.83 MB / 7.83 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

image

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/17876)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
@jamespik @ranm-msft

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
from https://docs.microsoft.com/en-us/windows/package-manager/package/winget-validation#error-labels about the `Validation-Defender-Error` label:
During dynamic testing, Microsoft Defender reported a problem. To reproduce this problem, install your application, then run a Microsoft Defender full scan. If you can reproduce the problem, fix the binary or submit it for analysis for false positive assistance. If you are unable to reproduce the problem, add a comment to get the Windows Package Manager engineers to investigate.

**Comment by OfficialEsco** [comment]
This got the `Validation-Defender-Error` label because `Avast Antivirus` disables `Microsoft Defender` when installed, the Technicians gotta manually approve any Antivirus for now, @KevinLaMS got assigned but AFAIK he dosn't look at PR's anymore...

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
image

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
image

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
