### PR TITLE
BeagleSoftware.BeagleEditor version 2024.4

### PR DESCRIPTION
**Pull request by ManiArasteh**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.
- Resolves: #174329
---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/174608)

### CODE REVIEW

**Comment by ManiArasteh** [comment]
Why no one accepting the package? 
Hello! Is anyone home?

**Comment by KarbitsCode** [comment]
> Why no one accepting the package? Hello! Is anyone home?

Moderators is on break today because today is sunday (or saturday in american time)
They will continue accepting the packages mostly starting monday.

**Comment by KarbitsCode** [comment]
Btw,

> Just add: `- Resolves: #174329` to the description on this PR so that it closes the issue when this PR is merged.
> 
> _Originally posted by @vikingnope in https://github.com/microsoft/winget-pkgs/issues/174327#issuecomment-2361244912_

**Comment by ManiArasteh** [comment]
Oh, no! How to enable auto-merge, again?

**Comment by ManiArasteh** [comment]
> (or saturday in american time)
Where? in Seattle?

**Comment by ManiArasteh** [comment]
Hey! It is 7:00! Start working and accept my package!

**Comment by ManiArasteh** [comment]
Please! Please merge this repository!

**Comment by KarbitsCode** [comment]
Which timezone are you from?

**Comment by ManiArasteh** [comment]
Iran

**Comment by ManiArasteh** [comment]
And now it is Monday (At least in my time zone)

**Comment by ManiArasteh** [comment]
Why no one is accepting my package? All of packages accepted except mine

**Comment by KarbitsCode** [comment]
> Why no one is accepting my package? All of packages accepted except mine

Usually, PR that has a https://github.com/microsoft/winget-pkgs/labels/New-Package label needs to be tested more thoroughly, like manually install and playing with the application a little bit, that is done by @stephengillie.

Other PR that was accepted by community moderators are just either a package update or deletion of obsolete packages.

It's 3AM right now in their timezone, so just be patient 😉

**Comment by ManiArasteh** [comment]
@KarbitsCode Microsoft is not only in America. It has many branches in many U.S. cities and even at other countries

**Comment by KarbitsCode** [comment]
> @KarbitsCode Microsoft is not only in America. It has many branches in many U.S. cities and even at other countries

I know.
Actually, i meant @stephengillie timezone, the only moderator that verifies this kind of cases.

**Comment by vikingnope** [comment]
@ItzLevvie, this is a duplicate to mine https://github.com/microsoft/winget-pkgs/pull/174344, so since you merged mine we should close this

**Comment by ManiArasteh** [comment]
And the workflow you opened a PR for it, doesn't work.

**Comment by vikingnope** [comment]
> And the workflow you opened a PR for it, doesn't work.

For the workflow to work, the PR has to be merged, so from now onwards it should work

**Comment by stephengillie** [comment]
> > Why no one accepting the package? Hello! Is anyone home?
> 
> Moderators is on break today because today is sunday (or saturday in american time) They will continue accepting the packages usually starting monday.

While we have moderators scattered around the planet, the bulk of moderation is indeed currently performed during business hours in the Pacific Time Zone.

**Pull request closed without merging**
