### PR TITLE
NAVER.MYBOX version 2.6.6.10

### PR DESCRIPTION
**Pull request by alexkoala**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/19949)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
I am stuck on this prompt and the application doesn't install when I press on the "OK" button:
image

**Comment by alexkoala** [comment]
> I am stuck on this prompt and the application doesn't install when I press on the "OK" button:
> image

You can't install 32bit version in 64bit Windows.

**Comment by ItzLevvie** [comment]
> You can't install 32bit version in 64bit Windows.

Is there not a x64 download link? Most people are using the 64-bit version of Windows.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Please see the latest comment.

**Comment by alexkoala** [comment]
> Please see the latest comment.

added 64bit in previous commit. Sorry for inconvenience.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
