### PR TITLE
GorillaDevs.Ferium version 4.5.2

### PR DESCRIPTION
**Pull request by theRookieCoder**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140834)

### CODE REVIEW

**Comment by theRookieCoder** [comment]
@microsoft-github-policy-service agree

**Comment by theRookieCoder** [comment]
I'm getting issues with windows defender locally too. After whitelisting the file I'm able to install it and it works fine.

**Comment by stephengillie** [comment]
Hi @theRookieCoder,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 821.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-24 00:51:53.272 [FAIL] Installer failed security check. Url: https://github.com/gorilla-devs/ferium/releases/download/v4.5.2/ferium-windows-msvc.zip Result: 0x80004005 2024-02-24 00:51:53.272 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6

(Automated response - build 821.)

**Comment by theRookieCoder** [comment]
I would like to get some help from moderation here. Firstly, this isn't a new manifest, this is an update of an existing one (have I configured something wrong?)

I also have no idea how I can resolve the validation error because it is a false positive by Windows Defender. I have already reported the false positive to Microsoft directly and have had no response.
Previous PRs (#139278 and #137742) had the same issue and the validation error was waived. Can I request the same to be done here?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\GorillaDevs.Ferium__DefaultSource\ferium.exe returned exit code: 2
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\ferium.exe returned exit code: 2

(Automated response - build 858.)

**Comment by stephengillie** [comment]
Hi @theRookieCoder.

Thanks for opening a PR. 

> I would like to get some help from moderation here. Firstly, this isn't a new manifest, this is an update of an existing one (have I configured something wrong?)

Each PR containing a manifest is automatically processed by our GitHub Actions into an Azure DevOps pipeline run, where the package described in the manifest is installed and scanned. The goal of this is to greatly limit the installation of compromised or otherwise potentially unwanted software (PUA). 

> I also have no idea how I can resolve the validation error because it is a false positive by Windows Defender. 

It's subtle, but the error changed from `Installation` to `Executable`. On the latest run, it wasn't blocked by Defender. The package installed normally and launched, but gave a non-zero exit code. Sometimes, it takes the Defender teams a few hours to a few days to clear a false positive. 

> Previous PRs (#139278 and #137742) had the same issue and the validation error was waived. Can I request the same to be done here?

Yes, we can apply a waiver for now. Eventually, can the exit code be changed to a 0?

**Comment by theRookieCoder** [comment]
Thanks for the feedback!

> The package installed normally and launched, but gave a non-zero exit code

This is a CLI application, so it expects some sort of subcommand or argument to be provided. Is there a way to tell the CI to check the version (`ferium --version`) or something infallible like that to result in a non-zero error code?

**Comment by stephengillie** [comment]
From the [schema](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.6.0/installer.md), there are 2 options here:

- `Commands:` - I haven't seen a PR using these, so I'm not sure of the impact. In theory, switches (such as `-V` in your example above) are put here. 
- `ExpectedReturnCodes` or similar - Putting `2` here might be the best option.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
