### PR TITLE
Convert to multi-manifest: `acfun.arlive` v0.3.3

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/21183)

### CODE REVIEW

**Review by jedieaston — CHANGES_REQUESTED** [review]
Why do you want to convert these to a multifile manifest? If it's only a single architecture, and only one language for locale data, there's not a great reason to do it? It just makes it harder to maintain (although most of our tools can do it, people starting out now have to understand how the three files change vs the easier singleton).

**Comment by vedantmgoyal2009** [comment]
It is written [here](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#what-next) that: 
"The multi-file manifest is the preferred method for building manifests. The mimimum required files are a version file, a defaultLocale file and an installer file."

**Review by ItzLevvie — COMMENTED** [review]
Waiting for @jedieaston to review the author's comments.

**Comment by denelon** [comment]
We're hoping https://github.com/microsoft/winget-create/issues/78 will make it easier for multi-lingual users to add locale specific metadata. The multi-file format makes it possible to add additional localizations.

**Comment by OfficialEsco** [comment]
> We're hoping [microsoft/winget-create#78](https://github.com/microsoft/winget-create/issues/78) will make it easier for multi-lingual users to add locale specific metadata. The multi-file format makes it possible to add additional localizations.

@jedieaston this is why i only make Multi Manifests, i want people to submit different locales, and i can add user/machine installers when people submit those, singleton's looks ugly tbh 🙄

**Review by ItzLevvie — APPROVED** [review]

**Comment by jedieaston** [comment]
Sorry I just saw this, I screwed up my GitHub notification settings and had to nuke my inbox. I have a PowerShell function to convert singletons to multifiles (makes my life a heck of a lot easier when adding additional architectures). Should we just do all of them?

**Comment by vedantmgoyal2009** [comment]
Just add that script in the Tools folder, I would convert the whole repository into the multi-manifest format in 3 days.

**Comment by OfficialEsco** [comment]
No, no automation, no reason to spam PR's like @vedantmgoyal2009 is doing just to convert them to Multi Manifest, we just need the latest version to be Multi Manifest with as much Metadata as possible.

These will be caught once they have not been updated for a few months. Me and @quhxl are checking letter for letter for APR and new versions and because Levvie only updated ARP (🙄) some new versions are probably missing but will be rechecked in a month.

**Comment by vedantmgoyal2009** [comment]
What is APR?

**Pull request merged**
