### PR TITLE
Fix: Properly select last version when Alpha/Beta/Dev versions are present

### LINKED ISSUE #21215: [YamlCreate] Help Wanted fixing Last Version selection
# Description of the new feature/enhancement

I need help with the `Read-PreviousWinGet-Manifest` function, the main visible issue is when you try to update for example Google Chrome which have this folder structure
```
| Google
|| Chrome
||| 91.0.4472.124
||| Beta
|||| 92.0.4515.81
||| Canary
|||| 93.0.4563.0
||| Dev
|||| 93.0.4557.4
```

The issue comes from the sorting of Get-ChildItem which places numbers on top and letters at the bottom, so when you do `Select-Object -Last 1 -ExpandProperty 'Name'` you'll get the last folder in folder which is Dev.

# Proposed technical implementation details (optional)

### PR DESCRIPTION
**Pull request by Trenly**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
-----

resolves #21215

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/21216)

### CODE REVIEW

**Comment by Trenly** [comment]
cc @OfficialEsco and @denelon

**Comment by OfficialEsco** [comment]
ooop, if i'm reading this correctly it will ignore any folders starting with a to z correct?
If that is so there is another issue, some annoying softwares contains atleast a v1.2.3.4, IIRC there are some rare cases where its a different letter, but very rare.
Scrolled trough `winget search` and spotted these:
```
Name                             Id                                 Version
------------------------------------------------------------------------------------------
Mazerator-Old                    WaterbugStudios.MazeratorOld       Nightly 20200420
WebDL                            Timber1900.WebDL                   v9.2
FileZilla Server                 TimKosse.FileZillaServer           beta 0.9.60
TeamViewerQS                     TeamViewer.TeamViewerQS            Latest (this should have been removed and we don't do latest anymore)
JetBrains MPS                    JetBrains.MPS                      MPS-211.7442.1291
MakeMKV                          GuinpinSoft.MakeMKV                v1.16.4
NoteTab Light                    FookesHolding.NoteTabLight         NoteTab Light 7.2
DJI Assistant 2 For Mavic        DJI.DJIAssistant2ForMavic          V2.0.14.1
DJI Assistant 2 For Phantom      DJI.DJIAssistant2ForPhantom        V2.0.10.4
DJI Assistant 2                  DJI.DJIAssistant2                  V1.2.5
DJI Assistant 2 (Consumer Drone… DJI.DJIAssistant2ConsumerSeries    V2.1.5.8
DJI Assistant 2 (Enterprise Ser… DJI.DJIAssistant2EnterpriseSeries  V2.1.0.2
DJI Assistant 2 (DJI FPV series) DJI.DJIAssistant2FPV               V2.1.1.11
DJI Assistant 2 For Autopilot    DJI.DJIAssistant2ForAutopilot      V2.0.3.7
DJI Assistant 2 For Battery Sta… DJI.DJIAssistant2ForBatteryStation V2.0.1.9
DJI Assistant 2 For MG           DJI.DJIAssistant2ForMG             V2.1.0.1
CHIRP                            CHIRP.CHIRP                        daily-20210706
AnyDesk                          AnyDeskSoftwareGmbH.AnyDesk        ad 6.3.2 (correct version)
AHM System Manager               Allen&Heath.AHMSystemManager       V1.03 - Rev. 62957
Avantis Director                 Allen&Heath.AvantisDirector        V1.11 - Rev. 64180
Custom Control Editor            Allen&Heath.CustomControlEditor    V1.1.1 - Rev. 58551
SQ MixPad                        Allen&Heath.SQMixPad               V1.5.0 - Rev. 56519
dLive Director                   Allen&Heath.dLiveDirector          V1.88 - Rev. 64094
AIMP                             AIMP.AIMP                          v4.70.2251, 23.05.2021
```

**Comment by denelon** [comment]
@OfficialEsco I'll wait to review/approve/merge until after you validate and approve.

**Comment by Trenly** [comment]
> ooop, if i'm reading this correctly it will ignore any folders starting with a to z correct?
> If that is so there is another issue, some annoying softwares contains atleast a v1.2.3.4, IIRC there are some rare cases where its a different letter, but very rare.
> Scrolled trough `winget search` and spotted these:
> 
> ```
> Name                             Id                                 Version
> ------------------------------------------------------------------------------------------
> Mazerator-Old                    WaterbugStudios.MazeratorOld       Nightly 20200420
> WebDL                            Timber1900.WebDL                   v9.2
> FileZilla Server                 TimKosse.FileZillaServer           beta 0.9.60
> TeamViewerQS                     TeamViewer.TeamViewerQS            Latest (this should have been removed and we don't do latest anymore)
> JetBrains MPS                    JetBrains.MPS                      MPS-211.7442.1291
> MakeMKV                          GuinpinSoft.MakeMKV                v1.16.4
> NoteTab Light                    FookesHolding.NoteTabLight         NoteTab Light 7.2
> DJI Assistant 2 For Mavic        DJI.DJIAssistant2ForMavic          V2.0.14.1
> DJI Assistant 2 For Phantom      DJI.DJIAssistant2ForPhantom        V2.0.10.4
> DJI Assistant 2                  DJI.DJIAssistant2                  V1.2.5
> DJI Assistant 2 (Consumer Drone… DJI.DJIAssistant2ConsumerSeries    V2.1.5.8
> DJI Assistant 2 (Enterprise Ser… DJI.DJIAssistant2EnterpriseSeries  V2.1.0.2
> DJI Assistant 2 (DJI FPV series) DJI.DJIAssistant2FPV               V2.1.1.11
> DJI Assistant 2 For Autopilot    DJI.DJIAssistant2ForAutopilot      V2.0.3.7
> DJI Assistant 2 For Battery Sta… DJI.DJIAssistant2ForBatteryStation V2.0.1.9
> DJI Assistant 2 For MG           DJI.DJIAssistant2ForMG             V2.1.0.1
> CHIRP                            CHIRP.CHIRP                        daily-20210706
> AnyDesk                          AnyDeskSoftwareGmbH.AnyDesk        ad 6.3.2 (correct version)
> AHM System Manager               Allen&Heath.AHMSystemManager       V1.03 - Rev. 62957
> Avantis Director                 Allen&Heath.AvantisDirector        V1.11 - Rev. 64180
> Custom Control Editor            Allen&Heath.CustomControlEditor    V1.1.1 - Rev. 58551
> SQ MixPad                        Allen&Heath.SQMixPad               V1.5.0 - Rev. 56519
> dLive Director                   Allen&Heath.dLiveDirector          V1.88 - Rev. 64094
> AIMP                             AIMP.AIMP                          v4.70.2251, 23.05.2021
> ```

Aahhh. That does complicate things a bit Let me look a bit further

**Comment by denelon** [comment]
@Trenly we had set a precedent initially with Visual Studio manifests. The "nesting" can be tricky to resolve. We do a recursive crawl from a manifest file to determine the "PackageIdentifier".

```
Visual Studio Load Test Controller 2019              Microsoft.VisualStudio.2019.TestController       16.10.31424.327
Visual Studio Test Agent 2019                        Microsoft.VisualStudio.2019.TestAgent            16.10.31424.327
Visual Studio Team Explorer 2019                     Microsoft.VisualStudio.2019.TeamExplorer         16.10.31424.327
Performance Tools for Visual Studio 2019             Microsoft.VisualStudio.2019.StandaloneProfiler   16.0.31321.278
Remote Tools for Visual Studio 2019                  Microsoft.VisualStudio.2019.RemoteTools          16.0.31321.278
Visual Studio Professional 2019 Preview              Microsoft.VisualStudio.2019.Professional-Preview 16.11.31320.298
Visual Studio Professional 2019                      Microsoft.VisualStudio.2019.Professional         16.10.31424.327
Visual Studio Enterprise 2019 Preview                Microsoft.VisualStudio.2019.Enterprise-Preview   16.11.31320.298
Visual Studio Enterprise 2019                        Microsoft.VisualStudio.2019.Enterprise           16.10.31424.327
Visual Studio Community 2019 Preview                 Microsoft.VisualStudio.2019.Community-Preview    16.11.31320.298
Visual Studio Community 2019                         Microsoft.VisualStudio.2019.Community            16.10.31424.327
Visual Studio Build Tools 2019                       Microsoft.VisualStudio.2019.BuildTools           16.10.31424.327
Visual Studio Enterprise 2022 Preview                Microsoft.VisualStudio.2022.Enterprise-Preview   17.0.31423.177
Visual Studio Community 2022 Preview                 Microsoft.VisualStudio.2022.Community-Preview    17.0.31423.177
Visual Studio Professional 2022 Preview              Microsoft.VisualStudio.2022.Professional-Preview 17.0.31423.177
```

```
Microsoft Visual Studio and .NET Framework Log Collection Tool Microsoft.VisualStudioCollect       16.0.28407.115
Microsoft Visual Studio Code Insiders                          Microsoft.VisualStudioCode.Insiders 1.59.0
Microsoft Visual Studio Code                                   Microsoft.VisualStudioCode          1.58.2
```

**Comment by OfficialEsco** [comment]
> Aahhh. That does complicate things a bit Let me look a bit further

Exactly this is where my brain is getting fried! 😁

> Would it be safe to assume that a version folder should only have manifests under it, and a Beta folder should only have version folders under it?

Yep the folder structure is always
```
| Google
|| Chrome
||| 91.0.4472.124
||| Beta
|||| 92.0.4515.81
||| Canary
|||| 93.0.4563.0
||| Dev
|||| 93.0.4557.4
```

Or in another rare case `/manifests/m/Microsoft/VisualStudio/2022/Community-Preview/17.0.31423.177/Microsoft.VisualStudio.2022.Community-Preview.installer.yaml`

**Review by denelon — APPROVED** [review]

**Comment by denelon** [comment]
@OfficialEsco let me know when you approve and I'll merge if there aren't any more changes.

**Comment by Trenly** [comment]
Leaving this here for anyone interested in the logic -

These changes should look at the App Folder, and find all files that are 0 or 1 levels deep. Because this is the app folder, we know that there will be no files at 0 depth, only Version/Beta directories. If a file is found at a depth of 1, then it means that it belongs to a version of that app. All Beta apps will only have directories at a depth of 1, and will therefore not be returned when we get the children recursively.

From here we extract the full paths of the files that were returned, then split them twice. Once to drop the file name and get the parent directory, and the second time to drop everything preceding the directory name (which leave us just the versions). With this list of versions, we can sort and select the last one as appropriate.

**Comment by OfficialEsco** [comment]
If(when) @Trenly can confirm it works on Google Chrome then you can merge it, as of now i'm stuck with
```
PS C:\Users\Esco\GitHub\winget-pkgs> .\Tools\YamlCreate.ps1
At C:\Users\Esco\GitHub\winget-pkgs\Tools\YamlCreate.ps1:945 char:24
+         git commit -m "$CommitType: `$PackageIdentifier` version $Pac ...
+                        ~~~~~~~~~~~~
Variable reference is not valid. ':' was not followed by a valid variable name character. Consider using ${} to
delimit the name.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : InvalidVariableReferenceWithDrive
```

**Comment by Trenly** [comment]
I tested with Chrome, VisualStudio, and a few randomly selected from your screenshot

**Review by OfficialEsco — APPROVED** [review]
Thaaaaaank you

**Pull request merged**
