### PR TITLE
SiberSystems.RoboForm version 9.1.9

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/27995)

### CODE REVIEW

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
image

**Comment by BajajAditya123** [comment]
ok

**Comment by BajajAditya123** [comment]
Can anybody help me with this??

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Please test your package in Windows Sandbox to make sure it installs fully unattended without requiring the user's attention:
https://github.com/microsoft/winget-pkgs/pull/27995#pullrequestreview-758066130.

Some installers may not have switches, and therefore, the package will not be added to the repository.

**Comment by BajajAditya123** [comment]
OK

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/27995#pullrequestreview-758138324

**Pull request closed without merging**
