### PR TITLE
MSI.Afterburner version 4.6.4

### PR DESCRIPTION
**Pull request by Macleykun**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/47081)

### CODE REVIEW

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
Techspot is not a official MSI Afterburner mirror.

**Comment by Macleykun** [comment]
> Techspot is not a official MSI Afterburner mirror.

While true, i've checked both sources and the hashes are the same.
I explained a bit more here: https://github.com/microsoft/winget-pkgs/issues/1990#issuecomment-1046041713

If unofficial sources aren't allowed even with same hash, i'm more then ok to close the pr :)

**Comment by Macleykun** [comment]
> Techspot is not a official MSI Afterburner mirror.

Actually. I've looked at guru3d and saw this:

A note to other media outlets and unaffiliated third parties: Those attempting to deep-link and/or distribute our software by uploading it to their own servers should refrain doing so. Only Guru3D.com and MSI are legally permitted to distribute MSI Afterburner; the same is true for Rivatuner statistics server, Rivatuner CORE application, and RTSS-related files. 

https://www.guru3d.com/files-details/msi-afterburner-beta-download.html#:~:text=A%20note%20to,RTSS%2Drelated%20files.%C2%A0

So, this means that guru3d is actually an authorized redistributer of msi :D !

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
This is currently blocked by `.zip` support for the following authorized domains by the publisher:
- www.msi.com
- www.guru3d.com

`.zip` support will be coming soon to future versions of WinGet so that will allow this package to be added in the future.

**Comment by Macleykun** [comment]
> @Macleykun,
> 
> One or more of the installer URLs doesn't appear valid.
> 
> This may happen for sites with policies prohibiting distribution or use by third parties.
> 
> This may happen for URLs pointing to domains that do not align with the publisher domain or package domain. If you could provide supporting evidence from the publisher that the URLs for the installer are correct, that would help us to validate and approve this PR.

https://www.techspot.com/downloads/downloadnow/4895/?evp=42d464f7f41b5241364018d49bca0650&file=5171
This url doesn't download a zip :-)

**Comment by OfficialEsco** [comment]
> > @Macleykun,
> > One or more of the installer URLs doesn't appear valid.
> > This may happen for sites with policies prohibiting distribution or use by third parties.
> > This may happen for URLs pointing to domains that do not align with the publisher domain or package domain. If you could provide supporting evidence from the publisher that the URLs for the installer are correct, that would help us to validate and approve this PR.
> 
> https://www.techspot.com/downloads/downloadnow/4895/?evp=42d464f7f41b5241364018d49bca0650&file=5171 This url doesn't download a zip :-)

Techspot is not Guru3d or MSI.
Guru3d is the Developer, MSI is the Publisher, we require a Official link from one of them.

**Comment by Macleykun** [comment]
asked msi support for a direct unzipped link. closing in the meantime

**Pull request closed without merging**
