### PR TITLE
Remove version: RussellBanks.Komac.Nightly version 2.1.1

### LINKED ISSUE #141715: [Package Issue]: RussellBanks.Komac was identified as RussellBanks.Komac.Nightly
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Installation issue.

### Brief description of your issue

image

The winget identified RussellBanks.Komac as RussellBanks.Komac.Nightly

CC @russellbanks

### Steps to reproduce

- Install RussellBanks.Komac
- Execute `winget update --all`

### Actual behavior

N/A

### Expected behavior

N/A

### Environment

```raw
 winget --info
Windows 程序包管理器 v1.7.10582
版权所有 (C) Microsoft Corporation。保留所有权利。

Windows: Windows.Desktop v10.0.22631.3235
系统体系结构: X64
软件包: Microsoft.DesktopAppInstaller v1.22.10582.0

Winget 目录
-------------------------------------------------------------------------------------------------------------------
日志                   %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
用户设置               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
可移植链接目录(用户)   %LOCALAPPDATA%\Microsoft\WinGet\Links
可移植链接目录(计算机) C:\Program Files\WinGet\Links
可移植包根目录(用户)   %LOCALAPPDATA%\Microsoft\WinGet\Packages
可移植包根目录         C:\Program Files\WinGet\Packages
可移植包根目录 (x86)   C:\Program Files (x86)\WinGet\Packages
安装程序下载           %USERPROFILE%\Downloads

链接
----------------------------------------------------------------------------
隐私声明             https://aka.ms/winget-privacy
许可协议             https://aka.ms/winget-license
第三方声明           https://aka.ms/winget-3rdPartyNotice
主页                 https://aka.ms/winget
Windows 应用商店条款 https://www.microsoft.com/en-us/storedocs/terms-of-sale

管理员设置                                状态
------------------------------------------------
LocalManifestFiles                        已启用
BypassCertificatePinningForMicrosoftStore 已禁用
InstallerHashOverride                     已启用
LocalArchiveMalwareScanOverride           已禁用
```

### Screenshots and Logs

_No response_

### PR DESCRIPTION
**Pull request by CoolPlayLin**
### badly identify

- Resolves #141715

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141827)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @russellbanks,

Do you approve of these changes?

(Automated response - build 857.)

**Comment by stephengillie** [comment]
Hi @CoolPlayLin,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 857.)

**Comment by stephengillie** [comment]
URL: https://github.com/russellbanks/Komac/releases/download/nightly/KomacSetup-nightly-x64.exe 
Status Code: 200

(Automated message - build 857)

**Review by russellbanks — APPROVED** [review]

**Comment by stephengillie** [comment]
URL: https://github.com/russellbanks/Komac/releases/download/nightly/KomacSetup-nightly-x64.exe 
Status Code: 200

(Automated message - build 857)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
