### PR TITLE
Microsoft.WindowsTerminal.Preview new version 1.15.2002.0

### PR DESCRIPTION
**Pull request by mivsvit**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/69397)

### CODE REVIEW

**Comment by mivsvit** [comment]
> Hello @mivsvit, The package manager bot determined that the metadata was not compliant.

```
 Manifest: The manifest file path must match PackageIdentifier and PackageVersion properties from manifest. actual 'manifests\m\Microsoft\WindowsTerminal\Preview\1.15.2003.0', expected 'manifests\m\Microsoft\WindowsTerminal\Preview\1.15.2002.0'
```

Looks like a transient error as the pipeline was running while the manifest was being corrected.

**Comment by krystofkrticka** [comment]
#68845

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
You forgot to update the version folder from `1.15.2003.0` to `1.15.2002.0`

**Review by ItzLevvie — APPROVED** [review]

**Comment by mivsvit** [comment]
Will submit new request with correct folder name

**Pull request closed without merging**
