### PR TITLE
New version: astral-sh.ruff version 0.3.2

### PR DESCRIPTION
**Pull request by frazar**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/143774)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @frazar,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 869.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-11 05:48:44.167 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.3.2/ruff-0.3.2-x86_64-pc-windows-msvc.zip Result: 0x80004005
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Packages\astral-sh.ruff__DefaultSource\ruff.exe returned exit code: 2
> Executable C:\Users\Validator\AppData\Local\Microsoft\WinGet\Links\ruff.exe returned exit code: 2

(Automated response - build 869.)

**Comment by stephengillie** [comment]
Hi @frazar,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 869.)

**Comment by stephengillie** [comment]
Hi @frazar,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 870.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-14 12:43:27.722 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFB1F47C11F: (caller: 00007FFB1F208D6F) LogHr(1) tid(558) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFB1F382B08: (caller: 00007FFB1F42BC20) Exception(1) tid(558) 8A15005E ] 
> 2024-03-14 12:43:27.722 [REPO] Failed to open available source: msstore
> 2024-03-14 12:43:29.695 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFB1F382B08: (caller: 00007FFB1F42BC20) Exception(1) tid(558) 8A15005E 
> 2024-03-14 12:43:35.894 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFB01B0C11F: (caller: 00007FFB01898D6F) LogHr(1) tid(1fa4) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFB01A12B08: (caller: 00007FFB01ABBC20) Exception(1) tid(1fa4) 8A15005E ] 
> 2024-03-14 12:43:35.894 [REPO] Failed to open available source: msstore
> 2024-03-14 12:43:52.019 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.3.2/ruff-0.3.2-x86_64-pc-windows-msvc.zip Result: 0x80004005
> 2024-03-14 12:43:31.800 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!5058535B: (caller: 50481A80) LogHr(1) tid(10b0) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!505CB5DD: (caller: 506612BF) Exception(1) tid(10b0) 8A15005E ] 
> 2024-03-14 12:43:31.800 [REPO] Failed to open available source: msstore
> 2024-03-14 12:43:33.747 [CLI ] Caught wil::ResultException: D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!505CB5DD: (caller: 506612BF) Exception(1) tid(10b0) 8A15005E 
> 2024-03-14 12:43:41.830 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!7901535B: (caller: 78F11A80) LogHr(1) tid(1e94) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!7905B5DD: (caller: 790F12BF) Exception(1) tid(1e94) 8A15005E ] 
> 2024-03-14 12:43:41.830 [REPO] Failed to open available source: msstore
> 2024-03-14 12:44:05.614 [FAIL] Installer failed security check. Url: https://github.com/astral-sh/ruff/releases/download/v0.3.2/ruff-0.3.2-i686-pc-windows-msvc.zip Result: 0x80004005

(Automated response - build 870.)

**Review by mdanish-kh — APPROVED** [review]

**Pull request merged**
