### PR TITLE
Move PrimateLabs.Geekbench2 2.4.3 to PrimateLabs.Geekbench.2 2.4.3

### PR DESCRIPTION
**Pull request by Trenly**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136582)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Program Files\Geekbench 2.4\geekbench_x86_64.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Program Files\Geekbench 2.4\geekbench_x86_64.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

(Automated response - build 661.)

**Comment by stephengillie** [comment]
InstallerUrl contains Manifest version instead of PR version:
- InstallerUrl: https://cdn.geekbench.com/Geekbench-2.4.3-WindowsSetup.exe

(Automated message - build 661)

**Comment by Trenly** [comment]
> Automatic Validation ended with:
> 
> > Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Program Files\Geekbench 2.4\geekbench_x86_64.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Program Files\Geekbench 2.4\geekbench_x86_64.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
> 
> (Automated response - build 661.)

Original PR - https://github.com/microsoft/winget-pkgs/pull/108041

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Exception during executable launch operation System.AggregateException: One or more errors occurred. (An error occurred trying to start process 'C:\Program Files\Geekbench 2.4\geekbench_x86_64.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.)  ---> System.ComponentModel.Win32Exception (216): An error occurred trying to start process 'C:\Program Files\Geekbench 2.4\geekbench_x86_64.exe' with working directory 'D:\TOOLS'. The specified executable is not a valid application for this OS platform.    --- End of inner exception stack trace ---    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

(Automated response - build 661.)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> Application Error 
> Faulting application name: Geekbench 2.exe, version: 0.0.0.0, time stamp: 0x516737c7 
> Faulting module name: Geekbench 2.exe, version: 0.0.0.0, time stamp: 0x516737c7 Exception code: 0x40000015 Fault offset: 0x00140a70 
> Faulting process id: 0x1f44 
> Faulting application start time: 0x01da50751501135b 
> Faulting application path: C:\Program Files (x86)\Geekbench 2.4\Geekbench 2.exe 
> Faulting module path: C:\Program Files (x86)\Geekbench 2.4\Geekbench 2.exe Report Id: bdf2a2d4-fac8-412d-b4e2-da893db9ec10 
> Faulting package full name:  
> Faulting package-relative application ID:   Windows Error Reporting Fault bucket -769467448, type 1 Event Name: APPCRASH Response: Not available Cab Id: 0  Problem signature: P1: Geekbench 2.exe P2: 0.0.0.0 P3: 516737c7 P4: Geekbench 2.exe P5: 0.0.0.0 P6: 516737c7 P7: 40000015 P8: 00140a70 P9:  P10:   Attached files: \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1980.tmp.dmp \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER19CF.tmp.WERInternalMetadata.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER19E0.tmp.xml \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER19DE.tmp.csv \\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER19EF.tmp.txt  These files may be available here: \\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_Geekbench 2.exe_c31b9169ca85effa3948e311e074daf7c69c7_8bbba88d_6bf322d6-e393-49f0-b5ca-da9c91519ebb  Analysis symbol:  Rechecking for solution: 0 Report Id: 14fbbe30-a4b6-4d7d-bcb6-ff3fa97d1a0b Report Status: 268435456 Hashed bucket: 04b914f0100c7f13844db98b1725d1e3 Cab Guid: 0

(Automated response - build 661.)

**Comment by stephengillie** [comment]
InstallerUrl contains Manifest version instead of PR version:
- InstallerUrl: https://cdn.geekbench.com/Geekbench-2.4.3-WindowsSetup.exe

(Automated message - build 669)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
