### PR TITLE
nkdAgility.AzureDevOpsMigrationTools version 13.0.4

### PR DESCRIPTION
**Pull request by MrHinsh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/106774)

### CODE REVIEW

**Comment by MrHinsh** [comment]
Locally I get "Archive scan detected malware." however I am positive I do not have any malware in the archive!

**Comment by stephengillie** [comment]
I believe the publisher's risqué name is triggering the [Policy 2.7](https://learn.microsoft.com/en-us/windows/package-manager/package/windows-package-manager-policies#27-adult-content) check.

**Comment by stephengillie** [comment]
This package works from its main location, but the symlink gave this error: 
> Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Hosting.Abstractions, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
   at VstsSyncMigrator.ConsoleApp.Program.\<Main\>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at VstsSyncMigrator.ConsoleApp.Program.Main(String[] args)
   at VstsSyncMigrator.ConsoleApp.Program.\<Main\>(String[] args)

**Comment by MrHinsh** [comment]
> Microsoft.Extensions.Hosting.Abstractions

This assembly is not needed for the application to run and is not referenced anywhere in the system. I'll go add it but (shrug)!

**Comment by MrHinsh** [comment]
@stephengillie if I have updated the app it will generate a new version. Do I need to submit a whole new one of these?

**Comment by MrHinsh** [comment]
It looks like the Pull Request validator was cancelled. Is there a way to kick it off?

**Comment by MrHinsh** [comment]
> > It looks like the Pull Request validator was cancelled. Is there a way to kick it off?
> 
> https://github.com/microsoft/winget-pkgs/pull/106831#issuecomment-1550024456

I very much private your help with this amateur trying to look cool!

**Comment by stephengillie** [comment]
Manual Validation failed with:
> Description: A .NET application failed. Application: migration.exe Path: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\nkdAgility.AzureDevOpsMigrationTools__DefaultSource\preview\migration.exe 
> Message: You must install .NET to run this application.  
>App: C:\Users\User\AppData\Local\Microsoft\WinGet\Packages\nkdAgility.AzureDevOpsMigrationTools__DefaultSource\preview\migration.exe Architecture: x64 
> App host version: 7.0.5 .
> NET location: Not found  
> Learn about runtime installation: https://aka.ms/dotnet/app-launch-failed  
> Download the .NET runtime: https://aka.ms/dotnet-core-applaunch?missing_runtime=true&arch=x64&rid=win10-x64&apphost_version=7.0.5

**Comment by MrHinsh** [comment]
This package does not need any dependencies. It's portable and runs on any Windows box OOB.

**Comment by stephengillie** [comment]
> @stephengillie do you know what might be triggering this dependency check? The executable is a portable assembly that does not need any additional components installed for it to run.
> 
> It's an unzip and execute from the folder.
> 
> I deploy it currently from Chocolatey! https://community.chocolatey.org/packages/vsts-sync-migrator/ just with an unzip.

Launching the application triggers the dependency check. It might be calling libraries only available with that package. 
image

With the dependency preinstalled, this package installs and runs normally:
```
migration 13.0.5+Branch.master.Sha.e4b664891a7dcb8a425b45226461b62ca1f0e8a0
Copyright (C) 2023 naked Agility with Martin Hinshelwood

ERROR(S):
  No verb selected.

  init       Creates initial config file

  execute    Record changes to the repository.

  help       Display more information on a specific command.
...
```

**Comment by MrHinsh** [comment]
> > @stephengillie do you know what might be triggering this dependency check? The executable is a portable assembly that does not need any additional components installed for it to run.
> > It's an unzip and execute from the folder.
> > I deploy it currently from Chocolatey! https://community.chocolatey.org/packages/vsts-sync-migrator/ just with an unzip.
> 
> Launching the application triggers the dependency check. It might be calling libraries only available with that package. image

I would have through that .NET would be installed by default on all Windows boxes? Does this mean that a portable application developed in .NET cant be deployed using Winget? How do we resolve this?

> With the dependency preinstalled, this package installs and runs normally:
> 
> ```
> migration 13.0.5+Branch.master.Sha.e4b664891a7dcb8a425b45226461b62ca1f0e8a0
> Copyright (C) 2023 naked Agility with Martin Hinshelwood
> 
> ERROR(S):
>   No verb selected.
> 
>   init       Creates initial config file
> 
>   execute    Record changes to the repository.
> 
>   help       Display more information on a specific command.
> ...
> ```

That looks great to me. It runs excellently and operates as expected. If no verb is selected then no action will be taken.

**Comment by stephengillie** [comment]
> I would have through that .NET would be installed by default on all Windows boxes? 

I believe this may have been judged to be a conflict of interest, and that Microsoft libraries have to compete fairly with other software libraries. 

> Does this mean that a portable application developed in .NET cant be deployed using Winget? How do we resolve this?

New applications which depend on .NET are being kept in a waiting list for dependency support, using the `Dependencies` label. 

> That looks great to me. Our documentation has instructions on pre-requisites and how to run the application. We don't bundle any pre-requisites and users are expected to do that themselves.

We validate that packages install and run successfully on fresh installs of Windows, without any prerequisites preinstalled. We generally expect that the installer will install all dependencies or prerequisites silently during the install process. The dependency feature is like a workaround for installers submitted by 3rd parties. 

> This is not a comertial tool, it is an OSS tool to developers and expert users to migrate data between Azure DevOps instances.

All packages available in the public manifest have to be usable for any user who might happen to download, in almost any terrestrial location, at any time. Including software enthusiasts who enjoy downloading and running random software applications as a hobby. If this is meant for local use, please consider a local manifest install, using the WinGet switch `--manifest C:\path\to\manifest\`

**Comment by MrHinsh** [comment]
@stephengillie how do I bump this?

**Comment by stephengillie** [comment]
I believe the `nkd` in the publisher section of the PackageIdentifier might be causing the [Policy 2.7](https://learn.microsoft.com/en-us/windows/package-manager/package/windows-package-manager-policies#27-adult-content) check, as it sometimes refers to an unclothed human.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
