### PR TITLE
New package: GoPro.Player version 2020.09.03

### PR DESCRIPTION
**Pull request by jo-chemla**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/172806)

### CODE REVIEW

**Comment by jo-chemla** [comment]
Woops, thanks for auto feedback. The official gopro player installer is actually downloaded from msstore, so I included the msstore direct url to the file. Probably not the adequate solution, awaiting contributor feedback - feel free to close PR if not doable!

**Comment by jo-chemla** [comment]
Is there a way to create a manifest for a package for which the only install method listed on the website is to use the Microsoft Store? https://gopro.com/en/us/info/gopro-player

Otherwise this PR can be closed, no worries!

image

**Comment by stephengillie** [comment]
This sounds similar to a tombstone:
- https://github.com/microsoft/winget-cli/issues/1900

**Pull request closed without merging**
