### PR TITLE
New package: Arm.ArmGnuToolchain version 12.2.MPACBTI-Rel1

### PR DESCRIPTION
**Pull request by seppeon**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/110755&drop=dogfoodAlpha

### CODE REVIEW

**Comment by seppeon** [comment]
Submission containing materials of a third party:
 - ARM Holdings

**Comment by seppeon** [comment]
```
PS C:\Users\David\Downloads> winget validate --manifest C:\Users\David\Downloads\manifests\a\Arm\ArmGnuToolchain\12.2.MPACBTI-Rel1
Manifest validation succeeded.
```

**Comment by seppeon** [comment]
```
PS C:\Users\David\Downloads> winget install --manifest C:\Users\David\Downloads\manifests\a\Arm\ArmGnuToolchain\12.2.MPACBTI-Rel1
Found Arm GNU Toolchain [Arm.ArmGnuToolchain] Version 12.2.MPACBTI-Rel1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://developer.arm.com/-/media/Files/downloads/gnu/12.2.mpacbti-rel1/binrel/arm-gnu-toolchain-12.2.mpacbti-rel1-mingw-w64-i686-arm-none-eabi.exe
  ██████████████████████████████   224 MB /  224 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```

**Comment by seppeon** [comment]
I noticed it installed in Program Files (x86), but the installer is 
`arm-gnu-toolchain-12.2.mpacbti-rel1-mingw-w64-i686-arm-none-eabi.exe`

`mingw-w64`
Is my arch correct?

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
> I noticed it installed in Program Files (x86), but the installer is `arm-gnu-toolchain-12.2.mpacbti-rel1-mingw-w64-i686-arm-none-eabi.exe`
> 
> I had noted, `mingw-w64`, but wasn't sure if I should have noted i686(`x86`). Is my arch correct?

Yes, it seems to be working fine. The architecture here is more to specify if it should be validated on a 32-bit or 64-bit OS. Machine scope might have more of a preference, as it specifies Program Files (or other locations?) as the install location, instead of %appdata% for user scope.

**Pull request merged**
