### PR TITLE
septentrio.rxtools version 24.0.0

### PR DESCRIPTION
**Pull request by DanielGekeler**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/190291)

### CODE REVIEW

**Comment by DanielGekeler** [comment]
@microsoft-github-policy-service agree

**Comment by DanielGekeler** [comment]
The installer also installs a driver and Windows asks the user to confirm.
grafik
How can i resolve this issue?

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 897.)

**Comment by DanielGekeler** [comment]
There is no dedicated installer for the driver.
This installer is made using the Qt Installer Framework, which doesn't offer much features.

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Comment by DanielGekeler** [comment]
How do we proceed with this issue? Is there a possible solution, or should I close this pull request?

**Comment by denelon** [comment]
I'll go ahead and close the PR. Hopefully we'll get an unattended option for the driver in the future.

**Pull request closed without merging**
