### PR TITLE
Update: JetBrains.ReSharper.EarlyAccess version 2021.2 EAP 6

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/21542)

### CODE REVIEW

**Review by OfficialEsco — CHANGES_REQUESTED** [review]
Wut 

```
Please enter the pull request number: 21542
Manifest validation succeeded.
Found JetBrains ReSharper (EAP) [JetBrains.ReSharper.EarlyAccess]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download-cdn.jetbrains.com/resharper/dotUltimate.2021.2.EAP6/JetBrains.dotUltimate.2021.2.EAP6.Checked.exe
  ██████████████████████████████  1.02 GB / 1.02 GB
Successfully verified installer hash
Starting package install...
Successfully installed
```
image

**Comment by vedantmgoyal2009** [comment]
Yep! It's a part of dotUltimate. The last time @ItzLevvie mentioned it [here](https://github.com/microsoft/winget-pkgs/pull/20095#issuecomment-875977623).

**Comment by vedantmgoyal2009** [comment]
cc @OfficialEsco

**Comment by OfficialEsco** [comment]
I've read it and i still can't validate it so i am waiting for Levvie

**Comment by vedantmgoyal2009** [comment]
cc @ItzLevvie

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
