### PR TITLE
New package: TechPowerUp.ThrottleStop version 9.6

### LINKED ISSUE #171060: [Package Request]: TechPowerUp.ThrottleStop version 9.6
### How can we help?

None

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

 | Key               | Value                                                                                                                                                           |
 | :----             | :------                                                                                                                                                         |
 | Download Page URL | <https://www.techpowerup.com/download/techpowerup-throttlestop/>                                                                                                |
 | Publisher         | TechPowerUp                                                                                                                                                     |
 | Package Name      | ThrottleStop                                                                                                                                                    |
 | Description       | ThrottleStop is a small application designed to monitor for and correct the three main types of CPU throttling that are being used on many laptop computers. |
 | Package Version   | 9.6                                                                                                                                                             |
 | Installer URL     | <https://sg1-dl.techpowerup.com/files/07vwq0mpN_WHetk3di4CAQ/1725237021/ThrottleStop_9.6.zip>                                                                   |

```[tasklist]
### Tasks
- [x] #171061 
```

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #171060

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/171061)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Dragon1573,

Manual Validation ended with:
> 9:31:34 AM: 2024-09-03 09:31:24.303 [CORE] DeliveryOptimization error: 0x80190194, extended error: 0x00000000
9:31:34 AM: 2024-09-03 09:31:24.305 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFA0100AAAE: (caller: 00007FFA01009CCA) Exception(1) tid(11c8) 80190194 Not found (404).
9:31:34 AM: 2024-09-03 09:31:26.056 [CORE] Download request failed. Returned status: 410
9:31:34 AM: 2024-09-03 09:31:26.056 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(167)\WindowsPackageManager.dll!00007FFA01007741: (caller: 00007FFA010035C3) Exception(2) tid(11c8) 8019019A Gone (410).
9:31:35 AM: 2024-09-03 09:31:26.077 [CLI ] Failed to download, waiting a bit and retry. Url: https://sg1-dl.techpowerup.com/files/07vwq0mpN_WHetk3di4CAQ/1725237021/ThrottleStop_9.6.zip
9:31:35 AM: 2024-09-03 09:31:33.393 [CORE] DeliveryOptimization error: 0x80190194, extended error: 0x00000000
9:31:35 AM: 2024-09-03 09:31:33.393 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFA0100AAAE: (caller: 00007FFA01009CCA) Exception(3) tid(11c8) 80190194 Not found (404).
9:31:35 AM: 2024-09-03 09:31:33.699 [CORE] Download request failed. Returned status: 410
9:31:35 AM: 2024-09-03 09:31:33.699 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(167)\WindowsPackageManager.dll!00007FFA01007741: (caller: 00007FFA010035C3) Exception(4) tid(11c8) 8019019A Gone (410).

Trying manually, I get:
image

I'm guessing the `1725237021` in the path is a Unix Epoch timestamp for `Monday, September 2, 2024 12:30:21 AM GMT`. Is the package available from a longer-lasting URL?

**Comment by Dragon1573** [comment]
When clicking <kbd>Download</kbd> button on `PackageUrl`, it'll perform a POST request to the page and navigate to a "mirror selection page". I can't find any long-lasting URL for the installer.

image

**Comment by stephengillie** [comment]
Hi @Dragon1573,

Unfortunately, this is beyond the means of the package manager to perform.

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Unsupported package. This package DOES NOT provide any long-term URL for installer downloading. It can' be supported by `winget.exe`.

**Comment by Dragon1573** [comment]
```text
23:56:36 C:\...\winget-pkgs  [issues/171060 ≡] 792ms pwsh> winget download -m .\manifests\t\TechPowerUp\ThrottleStop\9.6\
已找到 ThrottleStop [TechPowerUp.ThrottleStop] 版本 9.6
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
正在下载 https://sg1-dl.techpowerup.com/files/07vwq0mpN_WHetk3di4CAQ/1725237021/ThrottleStop_9.6.zip
执行此命令时发生意外错误：
Download request status is not success.
0x8019019a : 不存在(410)。
```

image

Installer file stored on server with a dynamically-generated URL.

```text
https://sg1-dl.techpowerup.com/files/07vwq0mpN_WHetk3di4CAQ/1725237021/ThrottleStop_9.6.zip
                                     ~~~~~~~~~~~~~~~~~~~~~~
                                     │                      ~~~~~~~~~~
                                     │                      └─> Unix-like UTC timestamp.
                                     └─> Encrypted content, algorithm currently unknown.                                                           
```

**Comment by stephengillie** [comment]
Manual Validation ended with:
> 4:54:22 PM: 
> 2024-09-09 16:54:13.854 [CORE] DeliveryOptimization error: 0x80190194, extended error: 0x00000000 4:54:22 PM: 
> 2024-09-09 16:54:13.855 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFD65B3AAAE: (caller: 00007FFD65B39CCA) Exception(1) tid(1d18) 80190194 Not found (404). 4:54:22 PM: 
> 2024-09-09 16:54:15.312 [CORE] Download request failed. Returned status: 410 4:54:22 PM: 
> 2024-09-09 16:54:15.312 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(167)\WindowsPackageManager.dll!00007FFD65B37741: (caller: 00007FFD65B335C3) Exception(2) tid(1d18) 8019019A Gone (410). 4:54:22 PM: 
> 2024-09-09 16:54:15.431 [CLI ] Failed to download, waiting a bit and retry. Url: https://sg1-dl.techpowerup.com/files/07vwq0mpN_WHetk3di4CAQ/1725237021/ThrottleStop_9.6.zip 4:54:22 PM: 
> 2024-09-09 16:54:21.703 [CORE] DeliveryOptimization error: 0x80190194, extended error: 0x00000000 4:54:22 PM: 
> 2024-09-09 16:54:21.703 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFD65B3AAAE: (caller: 00007FFD65B39CCA) Exception(3) tid(1d18) 80190194 Not found (404). 4:54:22 PM: 
> 2024-09-09 16:54:21.997 [CORE] Download request failed. Returned status: 410 4:54:22 PM: 
> 2024-09-09 16:54:21.997 [FAIL] C:\__w\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(167)\WindowsPackageManager.dll!00007FFD65B37741: (caller: 00007FFD65B335C3) Exception(4) tid(1d18) 8019019A Gone (410).

(Automated response - build 895.)

**Comment by Dragon1573** [comment]
Close with reason:

- https://github.com/microsoft/winget-pkgs/pull/171061#issuecomment-2338519609

**Pull request closed without merging**
