### PR TITLE
Update Baidunetdisk 7.5.0

### PR DESCRIPTION
**Pull request by Voya9e**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/21043)

### CODE REVIEW

**Comment by ImJoakim** [comment]
@Meng5in There's only support for one manifest / rename / change per PR currently - https://github.com/microsoft/winget-pkgs/issues/20218#issuecomment-879304774

**Comment by ImJoakim** [comment]
Please see my comment above - https://github.com/microsoft/winget-pkgs/pull/21043#issuecomment-880500698. You are currently adding multiple manifests in 1 PR, which is not supported.
You are adding version `7.4.3.3` and version `7.5.0`. You need to add one at a time (per PR).

**Review by ImJoakim — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/21043#issuecomment-880512722

**Comment by Meng5in** [comment]
> Please see my comment above - [#21043 (comment)](https://github.com/microsoft/winget-pkgs/pull/21043#issuecomment-880500698). You are currently adding multiple manifests in 1 PR, which is not supported.
> You are adding version `7.4.3.3` and version `7.5.0`. You need to add one at a time (per PR).

THANK you so much!

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Close and reopen the PR since the pipelines are running on machines from the U.S. and the download link is coming from China, it's downloading the application slowly.

**Comment by Meng5in** [comment]
> Close and reopen the PR since the pipelines are running on machines from the U.S. and the download link is coming from China, it's downloading the application slowly.

It's not work.

**Pull request closed without merging**
