### PR TITLE
New version: Jackett.Jackett version 0.22.71

### PR DESCRIPTION
**Pull request by ilike2burnthing**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/156726)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-06-05 23:07:13.887 [FAIL] Installer failed security check. Url: https://github.com/Jackett/Jackett/releases/download/v0.22.71/Jackett.Installer.Windows.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 883.)

**Comment by ilike2burnthing** [comment]
.

**Comment by ilike2burnthing** [comment]
Issues with wingetbot?

**Comment by ilike2burnthing** [comment]
I'll take that as a yes.

**Comment by ilike2burnthing** [comment]
Bit of a problem?
https://github.com/microsoft/winget-pkgs/pull/156480
https://github.com/microsoft/winget-pkgs/pull/156585

**Comment by stephengillie** [comment]
Sorry for the delay. `wingetbot run` wasn't listening to due to:

> Octokit was broken because comment id exceeded int maximum value for parsing JSON. A fix was submitted earlier, but we haven't got a NuGet package yet[.] 

- [@denelon on Gitter](https://matrix.to/#/!LEwByvxhTNZZcKeCCY:gitter.im/$c5J6uL4eU3A1Sy9vsPbUgBSahjnfLz6TDh98ZeW56G4?via=gitter.im&via=matrix.org&via=beeper.com)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
