### PR TITLE
New version: FlightGear.FlightGear version 2020.3.13

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/56254)

### CODE REVIEW

**Review by OfficialEsco — COMMENTED** [review]
```
Enter a pull request number: #56254

Manifest validation succeeded.
Found FlightGear [FlightGear.FlightGear] Version 2020.3.13
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://sourceforge.net/projects/flightgear/files/release-2020.3/FlightGear-2020.3.13.exe/download
  ██████████████████████████████  1.77 GB / 1.77 GB
Successfully verified installer hash
Starting package install...
Successfully installed

Name        : FlightGear v2020.3.13
Publisher   : The FlightGear Team
Version     : 2020.3.13
ProductCode : FlightGear_2020.3_is1
Uninstall   : winget uninstall --id "FlightGear_2020.3_is1"
```
Download might have timed out?

**Comment by OfficialEsco** [comment]
retry

**Review by ItzLevvie — APPROVED** [review]

**Comment by OfficialEsco** [comment]
@denelon the download is getting timed out
InstallationVerification-x64-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20220331154742

**Comment by ryfu-msft** [comment]
I manually validated this package and it worked for me. It just took a while for the install to complete which is why I think it's failing validation.

**Pull request merged**
