### PR TITLE
New version: SomePythonThings.WingetUIStore version 1.5.1

### PR DESCRIPTION
**Pull request by marticliment**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/89886)

### CODE REVIEW

**Review by russellbanks — APPROVED** [review]

**Comment by martinet101** [comment]
hi @russellbanks,

i have further tested the installer and i haven't found any errors during the whole installation.

Is there any way in which I can get some more info about the error in which Azure Pipelines are failing?

**Comment by russellbanks** [comment]
> i have further tested the installer and i haven't found any errors during the whole installation.

@martinet101, sometimes the pipelines have issues with certain apps or certain versions of apps. Sometimes that's a one-off, which is solved by a mod re-running the pipelines. If it's not, then an admin such as stephengillie will add a waiver or provide more insight into the issue. I approved the pull request pretty quickly because I know that the values are going to be correct as this package has had successful submissions before and this was automated.

**Pull request merged**
