### PR TITLE
Update: KRTirtho.Flemozi version 0.1.1

### PR DESCRIPTION
**Pull request by OfficialEsco**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

For #145586

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/146131)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
```
Enter a pull request number: #146131

Manifest has the following dependencies that were not validated; ensure that they are valid:
  - Packages
      Microsoft.VCRedist.2015+.x64
Manifest validation succeeded.
Found Flemozi [KRTirtho.Flemozi] Version 0.1.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
This package requires the following dependencies:
  - Packages
      Microsoft.VCRedist.2015+.x64
(1/1) Found Microsoft Visual C++ 2015-2022 Redistributable (x64) [Microsoft.VCRedist.2015+.x64] Version 14.36.32532.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.visualstudio.microsoft.com/download/pr/eaab1f82-787d-4fd7-8c73-f782341a0c63/917C37D816488545B70AFFD77D6E486E4DD27E2ECE63F6BBAAF486B178B2B888/VC_redist.x64.exe
  ██████████████████████████████  24.1 MB / 24.1 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Downloading https://github.com/KRTirtho/flemozi/releases/download/v0.1.1/Flemozi-windows-x86_64-setup.exe
  ██████████████████████████████  13.0 MB / 13.0 MB
Successfully verified installer hash
Starting package install...
Successfully installed

Name          : Flemozi version 0.1.1+2
Publisher     :
Version       : 0.1.1+2
ProductCode   : FBCAB0B1-8171-40FA-B28E-234B17743354_is1
Registry Path : Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\FBCAB0B1-8171-40FA-B28E-234B17743354_is1
Uninstall     : winget uninstall --id "FBCAB0B1-8171-40FA-B28E-234B17743354_is1"

Name          : Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.36.32532
Publisher     : Microsoft Corporation
Version       : 14.36.32532.0
ProductCode   : {8bdfe669-9705-4184-9368-db9ce581e0e7}
Registry Path : Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall\{8bdfe669-9705-4184-9368-db9ce581e0e7}
Uninstall     : winget uninstall --id "{8bdfe669-9705-4184-9368-db9ce581e0e7}"

Press any key to continue . . .
```

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> 2024-03-23 02:02:41.192 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFAC2D2C11F: (caller: 00007FFAC2AB8D6F) LogHr(1) tid(1060) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFAC2C32B08: (caller: 00007FFAC2CDBC20) Exception(1) tid(1060) 8A15005E ] 
> 2024-03-23 02:02:41.192 [REPO] Failed to open available source: msstore
> 2024-03-23 02:02:48.743 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(757)\WindowsPackageManager.dll!00007FFAA938C11F: (caller: 00007FFAA9118D6F) LogHr(1) tid(1d8c) 8A15005E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Rest\Schema\HttpClientHelper.cpp(30)\WindowsPackageManager.dll!00007FFAA9292B08: (caller: 00007FFAA933BC20) Exception(1) tid(1d8c) 8A15005E ] 
> 2024-03-23 02:02:48.743 [REPO] Failed to open available source: msstore
> 2024-03-23 02:02:50.068 [CLI ] No suitable installer found for manifest Microsoft.VCRedist.2015+.x64 with version 14.40.33617.1

(Automated response - build 873.)

**Comment by stephengillie** [comment]
Hi @OfficialEsco,

This manifest adds Apps and Features entries that aren't present in previous PR versions. These entries should be added to the previous versions, or removed from this version.

(Automated response - build 876.)

**Comment by OfficialEsco** [comment]
You told me to add it to all the versions in #145586 which is linked in the PR. but whatever

**Pull request closed without merging**
