### PR TITLE
Fix and update TI Connect CE software

### LINKED ISSUE #947: Fail to install TI Connect CE
When installing TI Connect CE (added in #614) I get the following exit code: "1624". Don't know what is making it fail.

### PR DESCRIPTION
**Pull request by NathanBnm**
This new manifest should fix #947.

As the 5.4 manifest is not working anymore (outdated and broken link) I will open a PR to remove it from the repo.

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/6013)

### CODE REVIEW

**Comment by NathanBnm** [comment]
Download URL is working fine. Don't know why it does make fail the pipeline 🤔

**Comment by KevinLaMS** [comment]
Ashwini can you investigate?

**Pull request merged**
