### PR TITLE
YoYoGamesLtd.GameMakerStudio2 version 2.3.3.574

### PR DESCRIPTION
**Pull request by Spahatticat**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/26850)

### CODE REVIEW

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Looks like it may need .NET Framework 3.5 - so we're stuck on dependency support:
image

If I close the window, it installs the rest of the dependencies and successfully installs the package:
image
image
image
image

Also, this PR is a duplicate of https://github.com/microsoft/winget-pkgs/pull/26205.

**Comment by TinyRobby** [comment]
so sorry I left...

**Comment by TinyRobby** [comment]
how can I help!

**Review by Spahatticat — COMMENTED** [review]
👍

**Comment by TinyRobby** [comment]
Sorry

**Pull request closed without merging**
