### PR TITLE
Fixed UpgradeBehavior for Edge WebView2 version 96.0.1054.53.

### LINKED ISSUE #1824: [Microsoft.EdgeWebView2Runtime]Unable to install, error code 2147748098
### Brief description of your issue

[Microsoft.EdgeWebView2Runtime]Unable to install, error code 2147748098

### PR DESCRIPTION
**Pull request by jedieaston**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

------

Technically resolves https://github.com/microsoft/winget-cli/issues/1824

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/39467)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by denelon** [comment]
@jedieaston, I've been chatting with the Edge team. Can you shed a bit of light on why you changed the upgrade behavior to "uninstall previous"?

**Comment by jedieaston** [comment]
In my testing, WebView2 wouldn't upgrade if it detected that a previous version was already installed (I assumed because it is supposed to be updated automatically in the background). The only way I was able to upgrade it if a existing version was installed was to uninstall the previous version.

Testing it now, it seems like I can't reproduce that behavior anymore. Maybe they fixed it?

**Comment by denelon** [comment]
There may be a few different packages attempting to use WebView2, and it is intended to "keep itself upgraded". We're talking with the team about publishing manifests themselves and taking advantage of [Enhancements to upgrade (Apps that upgrade themselves)](https://github.com/microsoft/winget-cli/issues/1163).

**Comment by jedieaston** [comment]
That would be awesome! Especially if they could cover the other Edge channels.

**Pull request merged**
