### PR TITLE
New version: Nushell.Nushell version 0.91.0

### PR DESCRIPTION
**Pull request by fdncred**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/142644)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @fdncred,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 861.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-05 16:53:38.520 [FAIL] Installer failed security check. Url: https://github.com/nushell/nushell/releases/download/0.91.0/nu-0.91.0-x86_64-pc-windows-msvc.msi Result: 0x80004005

(Automated response - build 861.)

**Comment by fdncred** [comment]
Thanks for the info. Please rescan. This msi was created within ci and automatically submitted here.

**Comment by stephengillie** [comment]
The software package didn't pass a Defender scan during the last run. My retry access is currently blocked due to some testing. But any commit (including any inconsequential change such as a line break or space) will also trigger another run.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
