### PR TITLE
Update manifest: Kubernetes.kwok version 0.4.0

### LINKED ISSUE #140049: [Package Issue] Typo: Kubernates.kwok
## Description

This is an issue about typo (word spelling). This should not affect users (I think).

> Hi, the Kubernates is a typo.
>
> _Originally posted by @wzshiming in https://github.com/microsoft/winget-pkgs/issues/130691#issuecomment-1951645517_
            
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/winget-pkgs/pull/140050
```

### PR DESCRIPTION
**Pull request by Dragon1573**
## Description

- Fix typo: Kubern{a ==> e}tes
- Resolve #140049

## Checks

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/140050)

### CODE REVIEW

**Comment by Dragon1573** [comment]
Is this pull request modified 2 packages at the same time (remove `Kubernates.kwok` and add `Kubernetes.kwok`)?

Should I split them into 2? @stephengillie

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-19T12:51:25.1799359Z ##[error] One or more errors occurred. (Addition and deletion only permitted in the same package directory.) Addition and deletion only permitted in the same package directory.

(Automated response - build 763.)

**Comment by Dragon1573** [comment]
Temporarily add new package of `Kubernetes.kwok` first, in order to prevent affecting users.

After the correct package is being merged, then the mis-spelling package identifier `Kubernates.kwok` can be removed.

**Comment by stephengillie** [comment]
There's also `Kubernetes.kwokctl` - is that the same or the CLI version?

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 785.)

**Comment by AsciiWolf** [comment]
@Dragon1573 There is another small typo in this PR name: Kubenetes :-)

**Comment by Dragon1573** [comment]
> There's also `Kubernetes.kwokctl` - is that the same or the CLI version?

They're not the same. Official dev team of it split them into 2 packages. I think `kwok` is something like daemon and `kwokctl` is the CLI controlling interface?

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
> They're not the same. Official dev team of it split them into 2 packages. I think `kwok` is something like daemon and `kwokctl` is the CLI controlling interface?

Thanks for disambiguating the similar branding.

**Comment by Dragon1573** [comment]
@stephengillie - Thank you for the approval. I'll create a removal PR for `Kubernates.kwok`

**Pull request merged**
