### PR TITLE
New version: FreedomScientific.JAWS.2024 version 2024.2409.2.400

### PR DESCRIPTION
**Pull request by BrettLewisVispero**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/175913)

### CODE REVIEW

**Comment by BrettLewisVispero** [comment]
@microsoft-github-policy-service agree [company="Vispero"]

**Comment by BrettLewisVispero** [comment]
@microsoft-github-policy-service agree company="Vispero"

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-09-30 13:53:13.220 [CLI ] ShellExecute installer failed: 2317879826
> [0C74:13A0][2024-09-30T13:53:08]i000: Initializing string variable 'JAWS64_ENABLE_UNTRUSTED_FONTS_EXCEPTION' to value '0'
> [0C74:13A0][2024-09-30T13:53:08]i000: Initializing string variable 'JAWSARM64_ENABLE_UNTRUSTED_FONTS_EXCEPTION' to value '0'
> [0C74:13A0][2024-09-30T13:53:11]i000: Setting string variable 'JAWS64_ENABLE_UNTRUSTED_FONTS_EXCEPTION' to value '1'
> [0C74:13A0][2024-09-30T13:53:11]i000: Setting string variable 'JAWSARM64_ENABLE_UNTRUSTED_FONTS_EXCEPTION' to value '1'
> [0C74:13A0][2024-09-30T13:53:12]e000: SetupApp: Variable was not found to remove prefix. This is not an error. Variable: vcredist2022_x86_InstalledVersion, 0x80070490
> [0C74:13A0][2024-09-30T13:53:12]e000: SetupApp: Variable was not found to remove prefix. This is not an error. Variable: vcredist2022_x64_InstalledVersion, 0x80070490
> [0C74:13A0][2024-09-30T13:53:12]e000: SetupApp: Variable was not found to remove prefix. This is not an error. Variable: vcredist2022_ARM64_InstalledVersion, 0x80070490
> [0C74:13A0][2024-09-30T13:53:12]i101: Detected package: ErrorReporting64, state: Absent, cached: None
> [0C74:13A0][2024-09-30T13:53:12]i101: Detected package: ErrorReportingARM64, state: Absent, cached: None
> [0C74:13A0][2024-09-30T13:53:12]e000: SetupApp: Failed to verify setup, 0x8A280A12
> [0C74:13A0][2024-09-30T13:53:12]i410: Variable: JAWS64_ENABLE_UNTRUSTED_FONTS_EXCEPTION = 1
> [0C74:13A0][2024-09-30T13:53:12]i410: Variable: JAWSARM64_ENABLE_UNTRUSTED_FONTS_EXCEPTION = 1
> MSI (s) (54:2C) [13:52:47:632]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (54:2C) [13:52:47:632]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (54:2C) [13:52:47:632]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (54:2C) [13:52:47:632]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (54:2C) [13:52:47:632]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> MSI (s) (54:2C) [13:52:49:304]: Executing op: ComponentRegister(ComponentId={D1A42A5C-40AF-58F8-91B7-BCDD0E523041},KeyPath=02*85*\SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules\C:\Program Files\dotnet\shared\Microsoft.NETCore.App\6.0.33\mscordaccore.dll,State=3,,Disk=1,SharedDllRefCount=0,BinaryType=0)
> MSI (s) (54:2C) [13:52:50:976]: Executing op: RegOpenKey(Root=-2147483646,Key=SOFTWARE\Microsoft\Windows\Windows Error Reporting\RuntimeExceptionHelperModules,,BinaryType=0,,)
> Property(S): ErrorDialog = ErrorDlg
> Property(S): OutOfDiskSpace = 0
> Property(S): OutOfNoRbDiskSpace = 0
> Property(S): PrimaryVolumeSpaceAvailable = 0
> Property(S): PrimaryVolumeSpaceRequired = 0
> Property(S): PrimaryVolumeSpaceRemaining = 0
> MSI (s) (54:E4) [13:52:51:507]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (54:E4) [13:52:51:507]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (54:E4) [13:52:51:507]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (54:E4) [13:52:51:507]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (54:E4) [13:52:51:507]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> MSI (s) (54:54) [13:52:52:117]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (54:54) [13:52:52:117]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (54:54) [13:52:52:117]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (54:54) [13:52:52:117]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (54:54) [13:52:52:117]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> MSI (s) (54:5C) [13:52:53:227]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (54:5C) [13:52:53:227]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (54:5C) [13:52:53:227]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (54:5C) [13:52:53:227]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (54:5C) [13:52:53:227]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.

Automated error analysis suggests -1978335226 may mean Running ShellExecute failed

(Automated response - build 896.)

**Comment by BrettLewisVispero** [comment]
Trying this again from scratch.

**Pull request closed without merging**
