### PR TITLE
New package: - VictorIX.BlenderLauncher version 2.2.0

### PR DESCRIPTION
**Pull request by jo-chemla**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Is there a linked Issue? `No`

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

Note I'm getting an error when trying to install locally, which appears to be widespread https://github.com/microsoft/winget-pkgs/issues/152915
```bash
C:\Users\jonathan\Downloads\winget-custom-komac>winget install --manifest VictorIX\BlenderLauncher\2.2.0\
Found Blender Launcher [VictorIX.BlenderLauncher] Version 2.2.0
La licence d’utilisation de cette application vous est octroyée par son propriétaire.
Microsoft n’est pas responsable des paquets tiers et n’accorde pas de licences à ceux-ci.
Downloading https://github.com/Victor-IX/Blender-Launcher-V2/releases/download/v2.2.0/Blender_
Unexpected error occurred while running command : (Une erreur inattendue s'est produite lors de l'exécution de la commande )
Download request status is not success.
0x80190194 : Not found (404).
```

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/172582)

### CODE REVIEW

**Comment by jo-chemla** [comment]
@microsoft-github-policy-service agree [company="jo-chemla"]

**Comment by jo-chemla** [comment]
@microsoft-github-policy-service agree

**Comment by jo-chemla** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Verify:
image
image
image
image

**Review by stephengillie — APPROVED** [review]

**Comment by jo-chemla** [comment]
Thanks for merging! 
Not sure why the `--version` flag gets appended to the install command. 
Also, the `-set-library-folder` could be exposed to the winget install options? Not sure how I could do that.

**Pull request merged**
