### PR TITLE
New package: Fiji.ImageJ version 2.15.1

### PR DESCRIPTION
**Pull request by ptsouchlos**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/167701)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2145844845
> 2024-08-14 07:45:34.205 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-08-14 07:45:34.259 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFCD552A465: (caller: 00007FFCD552AD01) Exception(1) tid(d00) 80190193 Forbidden (403).
> 2024-08-14 07:45:34.766 [CORE] Download request failed. Returned status: 403
> 2024-08-14 07:45:34.766 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFCD55243D6: (caller: 00007FFCD5525C49) Exception(2) tid(d00) 80190193 Forbidden (403).
> 2024-08-14 07:45:34.769 [CLI ] Failed to download, waiting a bit and retry. Url: https://downloads.imagej.net/fiji/latest/fiji-win64.zip
> 2024-08-14 07:45:35.455 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-08-14 07:45:35.455 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFCD552A465: (caller: 00007FFCD552AD01) Exception(3) tid(d00) 80190193 Forbidden (403).
> 2024-08-14 07:45:35.527 [CORE] Download request failed. Returned status: 403
> 2024-08-14 07:45:35.527 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFCD55243D6: (caller: 00007FFCD5525C49) Exception(4) tid(d00) 80190193 Forbidden (403).

Automated error analysis suggests -2145844845 may mean Forbidden (403).

Automated error analysis suggests 80190193 may mean Forbidden (403)

(Automated response - build 887.)

**Comment by DeveloperPaul123** [comment]
I can't seem to reproduce the download error. When I try it locally and on Sandbox things seem to work fine:

image

image

**Comment by stephengillie** [comment]
Hi @DeveloperPaul123,

image

Are you maybe using a DNS redirection tool?

**Comment by DeveloperPaul123** [comment]
@stephengillie I don't think I'm using a DNS redirect 🤔 Can you access their official site? https://fiji.sc If so can you download the zips from this site?

**Comment by DeveloperPaul123** [comment]
Oh, also looks like there is a European mirror I should probably use https://imagej.net/software/fiji/downloads

**Comment by stephengillie** [comment]
URL: https://downloads.imagej.net/fiji/latest/fiji-win64.zip 
OK

(Automated message - build 914)

**Comment by stephengillie** [comment]
Verify:
image

Hi @DeveloperPaul123,

This application displays version `2.14.0` while writing `2.15.1` to the Registry. It should probably have a `PackageVersion` of `2.14`0` (or even `2.14.0/1.54f`) and a `DisplayVersion` of `2.15`1. What do you think?

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2145844845
> 2024-08-21 05:45:09.805 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-08-21 05:45:09.864 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFD00DAA465: (caller: 00007FFD00DAAD01) Exception(1) tid(1ab0) 80190193 Forbidden (403).
> 2024-08-21 05:45:10.407 [CORE] Download request failed. Returned status: 403
> 2024-08-21 05:45:10.407 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFD00DA43D6: (caller: 00007FFD00DA5C49) Exception(2) tid(1ab0) 80190193 Forbidden (403).
> 2024-08-21 05:45:10.410 [CLI ] Failed to download, waiting a bit and retry. Url: https://downloads.imagej.net/fiji/latest/fiji-win64.zip
> 2024-08-21 05:45:11.220 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-08-21 05:45:11.220 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFD00DAA465: (caller: 00007FFD00DAAD01) Exception(3) tid(1ab0) 80190193 Forbidden (403).
> 2024-08-21 05:45:11.300 [CORE] Download request failed. Returned status: 403
> 2024-08-21 05:45:11.300 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFD00DA43D6: (caller: 00007FFD00DA5C49) Exception(4) tid(1ab0) 80190193 Forbidden (403).

Automated error analysis suggests -2145844845 may mean Forbidden (403).

Automated error analysis suggests 80190193 may mean Forbidden (403)

(Automated response - build 887.)

**Comment by stephengillie** [comment]
URL: https://downloads.imagej.net/fiji/latest/fiji-win64.zip 
OK

(Automated message - build 915)

**Comment by stephengillie** [comment]
Verify:
image

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
