### PR TITLE
Add PeerBrain

### PR DESCRIPTION
**Pull request by andrewstech**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/100748)

### CODE REVIEW

**Comment by andrewstech** [comment]
I think I know why the execution error is. Due to the application requiring a chromium based browser installed. By default on windows, edge is pre installed so this should be fine. In just assuming that edge is not in the azure testing CI.

**Comment by andrewstech** [comment]
> Hi @andrewstech,
> 
> The application installed normally, but when launched did not remain running and exited on its own:
> 
> ```
> Command: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --user-data-dir=C:\Users\User\AppData\Local\Temp\flaskwebgui --new-window --no-first-run --window-size=800,600 --app=http://127.0.0.1:50648
>  * Serving Flask app 'main' (lazy loading)
>  * Environment: production
>    WARNING: This is a development server. Do not use it in a production deployment.
>    Use a production WSGI server instead.
>  * Debug mode: off
> WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
>  * Running on http://127.0.0.1:50648
> Press CTRL+C to quit
> ```

Thanks for providing the logs. I am going to do some testing in a sandbox environment.

**Comment by stephengillie** [comment]
> Im very confused now as I have just installed it in a fresh windows sandbox and it works. image

Just to make this more confusing, it works now for me as well.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
