### PR TITLE
Remove version: Aserto.Topaz version 0.32.27

### PR DESCRIPTION
**Pull request by damn-good-b0t**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/186028)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by ItzLevvie** [comment]
[Policy] Needs-Manual-Merge

**Comment by stephengillie** [comment]
URL: https://github.com/aserto-dev/topaz/releases/download/v0.32.27/topaz_windows_x86_64.zip 
Response Error: The remote server returned an error: (404) Not Found.

(Automated message - build 923)

**Comment by stephengillie** [comment]
Hi @gertd,

Do you approve of these changes?

(Automated response - build 897.)

**Review by denelon — APPROVED** [review]

**Pull request merged**
