### PR TITLE
New package: nkdAgility.AzureDevOpsMigrationTools.Preview version 15.0.0-Preview.73

### PR DESCRIPTION
**Pull request by MrHinsh**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137154)

### CODE REVIEW

**Comment by MrHinsh** [comment]
This package has been tested locally and was successful with  --ignore-local-archive-malware-scan... This is the same product as https://github.com/microsoft/winget-pkgs/pull/135822 just from a new preview branch.

**Comment by MrHinsh** [comment]
@stephengillie im able to install it locally with the `winget install --manifest <path>` command! I do not see any error or issues...

**Comment by stephengillie** [comment]
Hi @MrHinsh,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 678.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-30 11:39:45.324 [FAIL] Installer failed security check. Url: https://github.com/nkdAgility/azure-devops-migration-tools/releases/download/v15.0.0-Preview.73/MigrationTools-15.0.0-Preview.73.zip Result: 0x80004005

(Automated response - build 678.)

**Comment by stephengillie** [comment]
Hi @MrHinsh,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 694.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-30 16:11:56.181 [FAIL] Installer failed security check. Url: https://github.com/nkdAgility/azure-devops-migration-tools/releases/download/v15.0.0-Preview.73/MigrationTools-15.0.0-Preview.73.zip Result: 0x80004005

(Automated response - build 694.)

**Comment by MrHinsh** [comment]
How do we poke the system?

**Comment by stephengillie** [comment]
Hi @MrHinsh,

I'm targetting about 18 hours between retries, so I'll retry in about 7 hours. Very soon, this retry process will be automated to be more consistent.

**Comment by MrHinsh** [comment]
Your help is very much apriciated

**Comment by MrHinsh** [comment]
Time to push it again @stephengillie?

**Comment by MrHinsh** [comment]
@stephengillie it look like it worked! You are the best!

**Comment by MrHinsh** [comment]
@ agree company="naked Agility Limited"

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
