### PR TITLE
Curtains.Stardock version 1.19

### PR DESCRIPTION
**Pull request by ghost**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/26681)

### CODE REVIEW

**Comment by OfficialEsco** [comment]
Bud, you have clearly not testing the manifest.

**Comment by BajajAditya123** [comment]
> Bud, you have clearly not testing the manifest.

I validated it. I ihave tested before submitting it. It was installed

**Comment by OfficialEsco** [comment]
`no` is not a silent install switch. This manifest does not install unattended.

**Comment by BajajAditya123** [comment]
so what do I do

**Comment by ImJoakim** [comment]
Hey there @BajajAditya123, all installers needs to install silently / unattended. @OfficialEsco added the InstallerSwitches so this would silently install / without user input in #26690. 

```
  InstallerSwitches:
    Silent: /s
    SilentWithProgress: /s
```

Your manifest does not install unattended / without user input:

image

I will go ahead and approve #26690 and this PR will automatically close. You can use this information and that PR as an example when creating other manifests in the future 😃

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/26681#issuecomment-911357889

**Comment by BajajAditya123** [comment]
what if we submit a application that has not have a license and silent installation

**Comment by OfficialEsco** [comment]
All Software have a License in some way or another. Copyright/EULA is a non Public License which is called Proprietary.
https://en.wikipedia.org/wiki/Proprietary_software

MOST software have silent switches, that is up to the Package Submitter to find. In the future we will support Interactive Only software but that will only be used for Software that CANNOT be silently installed.

**Pull request closed without merging**
