### PR TITLE
HydrusNetwork.HydrusNetwork version v515

### PR DESCRIPTION
**Pull request by Ryonez**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://api.github.com/repos/microsoft/winget-pkgs/pulls/95338)

### CODE REVIEW

**Comment by Ryonez** [comment]
> Hello @Ryonez,
> 
> Sorry we cannot process 95338 because you are changing validation-pipeline.yaml. Please remove that file from your PR. If you would like to discuss changes to validation-pipeline.yml, please file an issue.
> 
> Template: msftbot/pipelineModified

I have no idea what this error is, I'm using the winget create tool.

**Comment by Trenly** [comment]
There are some ongoing issues with the bot, the team is working to resolve them

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
