### PR TITLE
New version: DenoLand.Deno version 1.40.2

### PR DESCRIPTION
**Pull request by coolplaylinbot**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/136697)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Get-PRUserName,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 664.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-01-26 14:25:03.325 [FAIL] Installer failed security check. Url: https://github.com/denoland/deno/releases/download/v1.40.2/deno-x86_64-pc-windows-msvc.zip Result: 0x80004005

(Automated response - build 664.)

**Comment by CoolPlayLin** [comment]
CC @kt3k

**Comment by CoolPlayLin** [comment]
@stephengillie May we rerun again?

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
