### PR TITLE
Update: HiteVision.HitePai6 version 6.2.312

### PR DESCRIPTION
**Pull request by SpecterShell**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/175213)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2145844845
> 2024-09-26 00:29:27.649 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-09-26 00:29:27.649 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFA40A8A465: (caller: 00007FFA40A8AD01) Exception(2) tid(15cc) 80190193 Forbidden (403).
> 2024-09-26 00:29:58.935 [CORE] Download request failed. Returned status: 403
> 2024-09-26 00:29:58.935 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFA40A843D6: (caller: 00007FFA40A85C49) Exception(3) tid(15cc) 80190193 Forbidden (403).
> 2024-09-26 00:29:58.937 [CLI ] Failed to download, waiting a bit and retry. Url: https://appmarket.hitecloud.cn/appMarket/package/2024-09-03/72cea4ceba1948bda90003a74c417657/HitePai6.exe
> 2024-09-26 00:30:00.372 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-09-26 00:30:00.372 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFA40A8A465: (caller: 00007FFA40A8AD01) Exception(4) tid(15cc) 80190193 Forbidden (403).
> 2024-09-26 00:30:00.569 [CORE] Download request failed. Returned status: 403
> 2024-09-26 00:30:00.569 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFA40A843D6: (caller: 00007FFA40A85C49) Exception(5) tid(15cc) 80190193 Forbidden (403).
> MSI (s) (7C:D0) [00:28:35:124]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (7C:D0) [00:28:35:124]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (7C:D0) [00:28:35:124]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (7C:D0) [00:28:35:124]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (7C:D0) [00:28:35:124]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> Property(S): OutOfDiskSpace = 0
> Property(S): OutOfNoRbDiskSpace = 0
> Property(S): PrimaryVolumeSpaceAvailable = 0
> Property(S): PrimaryVolumeSpaceRequired = 0
> Property(S): PrimaryVolumeSpaceRemaining = 0
> MSI (s) (7C:64) [00:28:35:838]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (7C:64) [00:28:35:838]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (7C:64) [00:28:35:838]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (7C:64) [00:28:35:838]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (7C:64) [00:28:35:838]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.

Automated error analysis suggests -2145844845 may mean Forbidden (403).

Automated error analysis suggests 80190193 may mean Forbidden (403)

(Automated response - build 896.)

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2145844845
> 2024-09-26 00:29:27.649 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-09-26 00:29:27.649 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFA40A8A465: (caller: 00007FFA40A8AD01) Exception(2) tid(15cc) 80190193 Forbidden (403).
> 2024-09-26 00:29:58.935 [CORE] Download request failed. Returned status: 403
> 2024-09-26 00:29:58.935 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFA40A843D6: (caller: 00007FFA40A85C49) Exception(3) tid(15cc) 80190193 Forbidden (403).
> 2024-09-26 00:29:58.937 [CLI ] Failed to download, waiting a bit and retry. Url: https://appmarket.hitecloud.cn/appMarket/package/2024-09-03/72cea4ceba1948bda90003a74c417657/HitePai6.exe
> 2024-09-26 00:30:00.372 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-09-26 00:30:00.372 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FFA40A8A465: (caller: 00007FFA40A8AD01) Exception(4) tid(15cc) 80190193 Forbidden (403).
> 2024-09-26 00:30:00.569 [CORE] Download request failed. Returned status: 403
> 2024-09-26 00:30:00.569 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FFA40A843D6: (caller: 00007FFA40A85C49) Exception(5) tid(15cc) 80190193 Forbidden (403).
> MSI (s) (7C:D0) [00:28:35:124]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (7C:D0) [00:28:35:124]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (7C:D0) [00:28:35:124]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (7C:D0) [00:28:35:124]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (7C:D0) [00:28:35:124]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> Property(S): OutOfDiskSpace = 0
> Property(S): OutOfNoRbDiskSpace = 0
> Property(S): PrimaryVolumeSpaceAvailable = 0
> Property(S): PrimaryVolumeSpaceRequired = 0
> Property(S): PrimaryVolumeSpaceRemaining = 0
> MSI (s) (7C:64) [00:28:35:838]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (7C:64) [00:28:35:838]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (7C:64) [00:28:35:838]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (7C:64) [00:28:35:838]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (7C:64) [00:28:35:838]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.

Automated error analysis suggests -2145844845 may mean Forbidden (403).

Automated error analysis suggests 80190193 may mean Forbidden (403)

(Automated response - build 896.)

**Comment by stephengillie** [comment]
URL: https://appmarket.hitecloud.cn/appMarket/package/2024-09-03/72cea4ceba1948bda90003a74c417657/HitePai6.exe 
OK

(Automated message - build 923)

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -2145844845
> 2024-10-10 23:03:19.285 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-10-10 23:03:19.285 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FF916D4A465: (caller: 00007FF916D4AD01) Exception(2) tid(1d54) 80190193 Forbidden (403).
> 2024-10-10 23:03:51.323 [CORE] Download request failed. Returned status: 403
> 2024-10-10 23:03:51.323 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FF916D443D6: (caller: 00007FF916D45C49) Exception(3) tid(1d54) 80190193 Forbidden (403).
> 2024-10-10 23:03:51.324 [CLI ] Failed to download, waiting a bit and retry. Url: http://appmarket.hitecloud.cn/appMarket/package/2024-09-03/72cea4ceba1948bda90003a74c417657/HitePai6.exe
> 2024-10-10 23:03:52.510 [CORE] DeliveryOptimization error: 0x80190193, extended error: 0x00000000
> 2024-10-10 23:03:52.510 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!00007FF916D4A465: (caller: 00007FF916D4AD01) Exception(4) tid(1d54) 80190193 Forbidden (403).
> 2024-10-10 23:03:52.754 [CORE] Download request failed. Returned status: 403
> 2024-10-10 23:03:52.755 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(148)\WindowsPackageManager.dll!00007FF916D443D6: (caller: 00007FF916D45C49) Exception(5) tid(1d54) 80190193 Forbidden (403).
> MSI (s) (58:6C) [23:02:30:321]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (58:6C) [23:02:30:321]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (58:6C) [23:02:30:321]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (58:6C) [23:02:30:321]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (58:6C) [23:02:30:321]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.
> Property(S): OutOfDiskSpace = 0
> Property(S): OutOfNoRbDiskSpace = 0
> Property(S): PrimaryVolumeSpaceAvailable = 0
> Property(S): PrimaryVolumeSpaceRequired = 0
> Property(S): PrimaryVolumeSpaceRemaining = 0
> MSI (s) (58:9C) [23:02:31:024]: PROPERTY CHANGE: Adding OutOfDiskSpace property. Its value is '0'.
> MSI (s) (58:9C) [23:02:31:024]: PROPERTY CHANGE: Adding OutOfNoRbDiskSpace property. Its value is '0'.
> MSI (s) (58:9C) [23:02:31:024]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceAvailable property. Its value is '0'.
> MSI (s) (58:9C) [23:02:31:024]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRequired property. Its value is '0'.
> MSI (s) (58:9C) [23:02:31:024]: PROPERTY CHANGE: Adding PrimaryVolumeSpaceRemaining property. Its value is '0'.

Automated error analysis suggests -2145844845 may mean Forbidden (403).

Automated error analysis suggests 80190193 may mean Forbidden (403)

(Automated response - build 896.)

**Comment by stephengillie** [comment]
URL:  
Invalid URI: The hostname could not be parsed.

(Automated message - build 896)

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
