### PR TITLE
Manifest files for SSMS 20.1

### PR DESCRIPTION
**Pull request by Matteo-T**
New manifest files for SQL Server Management Studio 20.1 which is being released today, 4/9/2024.

Checklist for Pull Requests
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/148375)

### CODE REVIEW

**Comment by Matteo-T** [comment]
Oh maybe the links are not active yet.. They should become live shortly..

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installer Verification Analysis Context Information: 
 Installer https://go.microsoft.com/fwlink/?linkid=2267019&clcid=0x404
 Scan request id: 'c143793e-1691-42bf-afcc-fc9b2714bae7'
 
 Installer https://go.microsoft.com/fwlink/?linkid=2267019&clcid=0x40A
 Scan request id: '1d8d4132-3781-42f5-a3c0-ee5eb17eea9d'
 
 Installer https://go.microsoft.com/fwlink/?linkid=2267019&clcid=0x407
 Scan request id: 'cfda7878-92dc-48d2-bc40-5f45228f1825'
 
 Installer https://go.microsoft.com/fwlink/?linkid=2267019&clcid=0x416

(Automated response - build 876.)

**Comment by Matteo-T** [comment]
@stephengillie - I'm not exactly sure what is going on here. I am reasonably sure I used the exact same process I've used in the past. The only difference is that between 20.0 and 20.1 (now) I updated some stuff to the new schema 1.6.0 (which ended up in a mound of troubles for that PR, which were resolved eventually).

Is the system telling me that the SHA256 I have in the manifest files and the SHA256 of the files downloaded from the official links are NOT matching? Is there a way to see what the mismatch is? If there is a mismatch, then I have a much more serious issue at hands than just this PR...

**Comment by Matteo-T** [comment]
Uhm.... I do see these errors in some logs:

Specified hash doesn't match.
Actual hash:   2F66C26BEA7C81C3F8D626F2F4B25649525DD2029B4496ABCF09096D9E3D011C
Expected hash: 402fa78bd9e4b54538642d5a127e39be13239d69483fce657f2f8a78e0c48c38
Specified hash doesn't match.
Actual hash:   7881E892FE6D6DD0E4EA214B4CDA98A7B2D1296BC1EF3B0B6AB44AD3497D9E3E
Expected hash: 1ae4b6170b983b9cd74e3e85d7072935997c6147800f627b332e7d606b4c8e98

Let me take a look and see what I can figure out...

**Comment by Matteo-T** [comment]
I do not see a problem with I download the following 2 packages:

- InstallerUrl: https://go.microsoft.com/fwlink/?linkid=2267019&clcid=0x804
  InstallerSha256: 402FA78BD9E4B54538642D5A127E39BE13239D69483FCE657F2F8A78E0C48C38

-  InstallerUrl: https://go.microsoft.com/fwlink/?linkid=2267019&clcid=0x410
  InstallerSha256: 1AE4B6170B983B9CD74E3E85D7072935997C6147800F627B332E7D606B4C8E98
  
  When I run PowerShell, it seems to confirm that the 2 hashes I have in the manifest are correct:
  
  ```console
PS C:\Users\matteo\Downloads> Get-FileHash -Algorithm SHA256 .\SSMS-Setup-ITA.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          1AE4B6170B983B9CD74E3E85D7072935997C6147800F627B332E7D606B4C8E98       C:\Users\matteo\Downloads\SSMS…

PS C:\Users\matteo\Downloads> Get-FileHash -Algorithm SHA256 .\SSMS-Setup-CHS.exe

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          402FA78BD9E4B54538642D5A127E39BE13239D69483FCE657F2F8A78E0C48C38       C:\Users\matteo\Downloads\SSMS…
```

**Comment by stephengillie** [comment]
Hi @Matteo-T,

Thanks for performing the detective work. The manifest also works in a Windows 10 VM of mine:
image

It's possible that they might be receiving an HTML website containing a message instead of the installer - this might be part of an IP block of data centers. I'm not sure how to obtain the download from the Automatic Pipeline VM, and without seeing its payload I can only speculate on the cause and solution.

**Comment by Matteo-T** [comment]
Let me see if I can tweak the download links and provide direct links instead of fwlinks

It's definitely odd that this is reported to be a problem only for 2 links and not all of them.

I'll submit an updated PR in a few hours...



Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Matteo-T** [comment]
@stephengillie - I just pushed a commit that replaces the fwlinks with the actual target. There should be no 30x or other things like that (redirections) in the way, so it's as clean as I can make it. If it works, I'll look into updating my automation scripts to use that the next time around... to make this whole process more robust.

**Comment by stephengillie** [comment]
Hi @,

Do you approve of these changes?

(Automated response - build 876.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
