### PR TITLE
New version: Tyrrrz.LightBulb version 2.5.1

### PR DESCRIPTION
**Pull request by Exorcism0666**
Created by [🥟 Dumplings](https://github.com/Exorcism0666/Dumplings) in workflow run [#1693](https://github.com/Exorcism0666/Dumplings/actions/runs/9245945584).

**Logs**
````
Updated: 2.5 → 2.5.1
Cannot validate argument on parameter 'ChatID'. The argument is null, empty, or consists of only white-space characters. Provide an argument that contains non white-space characters, and then try the command again.
Submitting WinGet manifests
Cannot validate argument on parameter 'ChatID'. The argument is null, empty, or consists of only white-space characters. Provide an argument that contains non white-space characters, and then try the command again.
````
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/155250)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping Exorcism0666.
>[!warning]
>With the new version of Komac, numerous Pull Requests may contain bugs or unwanted elements. If such issues arise, please tag russellbanks so that these bugs can be addressed in future updates.

>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-05-26 13:33:11.733 [FAIL] Installer failed security check. Url: https://github.com/Tyrrrz/LightBulb/releases/download/2.5.1/LightBulb-Installer.win-arm64.exe Result: 0x80004005

Automated error analysis suggests -1978335187 may mean Installer failed security check. Another script should retry this every 18 hours. 

(Automated response - build 881.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:


(Automated response - build 881.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
