### PR TITLE
New version: mlocati.GetText version 0.21

### LINKED ISSUE #106184: [Update Request]: GnuWin32.GetText version 0.21.1
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

GnuWin32.GetText

### Package Version

0.21.1

### Please describe the changes you would like to see

There are newer versions available that have multiple bugfixes.
Url: https://mlocati.github.io/articles/gettext-iconv-windows.html

### PR DESCRIPTION
**Pull request by Dragon1573**
## Description

- Resolve #106184

## Checks

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- Have you tested your manifest locally with `winget install --manifest <path>`?
  - [x] x64
  - [ ] x86
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/131131)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @Dragon1573,

> Current manifest version 0.14.4 has 3 parameters, which is greater than this PR's version number 0.21's 2 parameters.

Is this intentional?

(Automated response - build 486)

**Comment by Dragon1573** [comment]
@stephengillie - Yes, it's intended. 

According to [this page](https://gnuwin32.sourceforge.net/packages/gettext.htm), version 0.14.4 was released on 2005-06-05.

According to https://github.com/microsoft/winget-pkgs/issues/106184#issuecomment-1569016274 and [this page](https://www.gnu.org/software/gettext/#header),

1. the current latest version is 0.22.4
2. **Michele Locati** is maintaining the Windows Binaries

According to [this page](https://mlocati.github.io/articles/gettext-iconv-windows.html), the latest windows binaries are version 0.21. They are released on 2020-08-12.

**Comment by Dragon1573** [comment]
Oops?! I think it's my fault ...

Windows prebuilt binaries are no longer released by GNUWin32. The [homepage](https://www.gnu.org/software/gettext/#header) of `gettext` saying **Michele Locati** is maintaining this package. We should change `GnuWin32.GetText` to `mlocati.GetText` as your advice in https://github.com/microsoft/winget-pkgs/issues/106184#issuecomment-1561326837.

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> This pull request requires Azure Pipeline checks to be passed. But it seems the pipeline can't be triggered by bot account automatically. Please moderators help trigger the pipeline manually.
>
> Thank you! ❤️

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
