### PR TITLE
New version: SimonG4ELI.SDR-Radio.Beta version 3.4

### LINKED ISSUE #182772: [Update Request]: SDR-Radio
### What type of update are you requesting?

A new version of an existing package

### Current Package Identifier

SimonG4ELI.SDR-Radio

### Package Version

3.4-b3485

### Please describe the changes you would like to see

There is a new beta release (3.4-b3485) available. Download Page Url: https://www.sdr-radio.com/download#Beta (https://irp.cdn-website.com/46d0be53/files/uploaded/SDR-Radio_V3.4-_64-bit-_2024-10-11_0637.zip)

Make sure to add the app using a `SimonG4ELI.SDR-Radio.Beta` namespace. See [this PR](https://github.com/microsoft/winget-pkgs/pull/137006) as an example.

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Resolve #182772

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/182807)

### CODE REVIEW

**Comment by Dragon1573** [comment]
Manually verified in _Windows Sandbox_ instance.

Install Log
Start Panel
Opening Page of the package
About Page of the package

**Review by AsciiWolf — CHANGES_REQUESTED** [review]
(See the previous comment.)

**Comment by AsciiWolf** [comment]
@stephengillie The version number is incorrect. Please read my previous comment.

**Comment by AsciiWolf** [comment]
Wait... It looks like I was wrong! The version number is incorrect, however the correct one is `3.4-b3485` not the one that I mentioned before. This can be confirmed by either running the app or reading the [v3.4 Release Notes](https://www.sdr-radio.com/v3-4-release-notes).

**Comment by stephengillie** [comment]
Verify:
image
image

image
image

Hi @AsciiWolf,

This is a similar situation as in https://github.com/microsoft/winget-pkgs/issues/181435#issuecomment-2408473217. It's also similar to https://github.com/microsoft/winget-pkgs/issues/182583#issuecomment-2409068429, and I believe the 3 options at the end are the same. 

Since subsequent package versions will write the same version number ot the Registry, only one version can be in the repo at a time. This installer writes `3.4` to the Registry - this has to match with either the `PackageVersion` or the `DisplayVersion` in the manifest to help the package manager match these. 

3 ways to fix this:

1. Use `3.4` as the PackageVersion and update the URLs and hashes each time a new version is released.
1. Add an AppsAndFeaturesEntries.DisplayVersion to the manifest with `3.4` as the value. However, since all versions have the same display version, only one manifest could exist within the repo at a time.
1. Ask the developer to update the installer so it writes unique version numbers to the Registry.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
