### PR TITLE
 New version: pizzaboxer.Bloxstrap version 2.3.0

### PR DESCRIPTION
**Pull request by pizzaboxer**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/105938)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
InstallationVerification-x64-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20230504151759

**Comment by pizzaboxer** [comment]
I see the Bloxstrap icon in the taskbar, looks like it didn't run silently? Can I see what window it's showing just in case it's an error or something?

**Comment by stephengillie** [comment]
> I see the Bloxstrap icon in the taskbar, looks like it didn't run silently? Can I see what window it's showing just in case it's an error or something?

Unfortunately the Automatic Validation only provides 1 screenshot per run. I'm guessing this is due to the dependency.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
