### PR TITLE
New package: fire-eggs.DarkThumbs version 1.9

### PR DESCRIPTION
**Pull request by soredake**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/166295)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335226
> 2024-08-06 00:21:59.353 [CLI ] ShellExecute installer failed: 1603
> Action start 0:21:58: AllocateRegistrySpace.
> Action ended 0:21:58: AllocateRegistrySpace. Return value 1.
> CustomAction +_757B733EE9E044A2F7FE91DD8D15F40B returned actual error code -2147024770 (note this may not be 100% accurate if translation happened inside sandbox)
> MSI (s) (24:B8) [00:21:59:071]: Product: DarkThumbs -- Error 1904. Module C:\Program Files\DarkThumbs\CBXShell.dll failed to register.  HRESULT -2147024770.  Contact your support personnel.
> Error 1904. Module C:\Program Files\DarkThumbs\CBXShell.dll failed to register.  HRESULT -2147024770.  Contact your support personnel.
> Property(S): ErrorDialog = ErrorDialog
> Property(S): OutOfDiskSpace = 0
> Property(S): OutOfNoRbDiskSpace = 0
> Property(S): PrimaryVolumeSpaceAvailable = 0
> Property(S): PrimaryVolumeSpaceRequired = 0
> Property(S): PrimaryVolumeSpaceRemaining = 0
> MSI (s) (24:B8) [00:21:59:211]: Product: DarkThumbs -- Installation failed.

Automated error analysis suggests -1978335226 may mean Running ShellExecute failed

Automated error analysis suggests 1603 may mean Install successful but system restart may be required. Should this be add as an `InstallerSuccessCode` or similar?

(Automated response - build 887.)

**Comment by stephengillie** [comment]
Hi @soredake,

The installer didn't seem to modify the filesystem. Is this expected? Could a dependency be needed?

**Comment by soredake** [comment]
@stephengillie
> Could a dependency be needed?

I don't think so, DarkThumbs bundles `vcruntime140_1.dll`
image

**Comment by soredake** [comment]
Turns out installer requires visual c++ libraries.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Verify:
image

**Pull request merged**
