### PR TITLE
Update: VMware.WorkstationPro version 16.2.4.20089737

### PR DESCRIPTION
**Pull request by virtualex-itv**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.2 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.2.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/88813)

### CODE REVIEW

**Comment by virtualex-itv** [comment]
@stephengillie - please assist here.  See above screenshot for proof that the package installs without issue.

**Comment by virtualex-itv** [comment]
@mdanish-kh Can you possibly have a look at this one as well, the package has been fixed as can be seen in the above screenshot but for some reason always fails validation and needs to be manually approved/merged.

**Review by ItzLevvie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
