### PR TITLE
New version: gopass.gopass-jsonapi version 1.15.14

### PR DESCRIPTION
**Pull request by dpprdan**

### CODE REVIEW

**Comment by dpprdan** [comment]
ping-ing seems to do the trick, (or it did in #194363)

**Comment by stephengillie** [comment]
Manual Validation ended with:
> Trojan:Win32/Bearfoos.A!ml

(Automated response - build 931.)

**Comment by dpprdan** [comment]
@stephengillie it's clean on virustotal, so probably a false positive?
https://www.virustotal.com/gui/url/0c8a50ded27cc45224b0e5295cd014c71bafcf89a7c25d88d1592b3d4b2ab08b
https://www.virustotal.com/gui/url/eeb8197f6795f2ad8dbbfe349178e84f45efd230306973ce878e5fcce887f166

Anything else I can do here?

**Comment by stephengillie** [comment]
Hi @dpprdan,

Just needed some time, for my VMs to catch up with the antivirus vendor. Thanks for your patience.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
