### PR TITLE
New package: IDRIX.VeraCrypt version 1.26.7

### PR DESCRIPTION
**Pull request by ypurpl**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135783)

### CODE REVIEW

**Comment by vvirtues** [comment]
> @vvirtues please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

**Comment by vvirtues** [comment]
ok, let's try this one more time. Hopefully I'm doing this right

**Comment by stephengillie** [comment]
I don't see a clear reason for the error.

**Comment by vvirtues** [comment]
I'll fix later, I think I sent the wrong flag

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 

(Automated response - build 642.)

**Comment by vvirtues** [comment]
since i'm using a tool to create the pull request (komac), I'll close this and open a new pull request instead

**Pull request closed without merging**
