### PR TITLE
 Add GAMA 1.8.1

### PR DESCRIPTION
**Pull request by RoiArthurB**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate <manifest>`, where `<manifest>` is the name of the manifest you're submitting?
- [x] Have you tested your manifest locally with `winget install -m <manifest>`?

-----

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/4157)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
we do not support ZIP yet.
https://github.com/microsoft/winget-cli/issues/140

**Comment by RoiArthurB** [comment]
Hello @KevinLaMS 
Ok, I thought it was, I'll keep this PR open until the ZIP is supported or reopen it after :smiley:

**Comment by RoiArthurB** [comment]
Hi @KevinLaMS, does the _zip_ format is supported now ? :)

**Comment by ItzLevvie** [comment]
> Hi @KevinLaMS, does the _zip_ format is supported now ? :)

Not yet.

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
Close with reason: Stale PR. Must be rewritten as mentioned above to ensure it complies with the 1.4.0 specification;

**Pull request closed without merging**
