### PR TITLE
Scrumchrono 0.1.4

### PR DESCRIPTION
**Pull request by pedrojreis**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/139975)

### CODE REVIEW

**Comment by pedrojreis** [comment]
@microsoft-github-policy-service agree

**Comment by pedrojreis** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 792.)

**Comment by stephengillie** [comment]
Hi @pedrojreis,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 796.)

**Comment by stephengillie** [comment]
Hi @pedrojreis,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 812.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
>  Installation failed with exit code -1978335187 2024-02-21 12:58:04.648 [CLI ] Installer [Arm64,portable,Unknown,en-US] not applicable: Machine is not compatible with Arm64 2024-02-21 12:58:04.648 [CLI ] Installer [X64,portable,Unknown,en-US] not applicable: Machine is not compatible with X64 2024-02-21 12:58:12.271 [FAIL] Installer failed security check. Url: https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.4/ScrumChrono_Windows_i386.zip Result: 0x80004005 2024-02-21 12:58:12.271 [CLI ] Terminating context: 0x8a15002d at D:\a\_work\1\s\external\pkg\src\AppInstallerCLICore\Workflows\DownloadFlow.cpp:1e6

(Automated response - build 812.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
