### PR TITLE
Metadata: Corsair.iCUE -> Corsair.iCUE.3 and Corsair.iCUE.4

### PR DESCRIPTION
**Pull request by Trenly**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

-----

These changes reflect the offering of separate downloads for v3 and v4 on https://www.corsair.com/us/en/downloads
image

This also makes it clear as to why you can't upgrade from v3 to v4 using `winget upgrade`
```raw
PS C:\Users\WDAGUtilityAccount> winget install icue --version 3.38.61
Found Corsair iCUE [Corsair.iCUE]
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://downloads.corsair.com/Files/CUE/iCUESetup_3.38.61_release.msi
  ██████████████████████████████   474 MB /  474 MB
Successfully verified installer hash
Starting package install...
Successfully installed

PS C:\Users\WDAGUtilityAccount> winget upgrade
Name           Id             Version     Available   Source
------------------------------------------------------------
Microsoft Edge Microsoft.Edge 89.0.774.68 93.0.961.38 winget

PS C:\Users\WDAGUtilityAccount> winget search icue
Name                    Id           Version
---------------------------------------------
CORSAIR iCUE 4 Software Corsair.iCUE 4.13.223

PS C:\Users\WDAGUtilityAccount>
```
image

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/26935)

### CODE REVIEW

**Comment by Trenly** [comment]
@ItzLevvie @OfficialEsco 
Would you be able to review these changes since it involves multiple manifests and can't be validated through the pipeline?

**Comment by OfficialEsco** [comment]
Nope, only Repo maintainers can approve this, and they don't..
Also i believe you can change the `PackageName` to `CORSAIR iCUE 3 Software` and `CORSAIR iCUE 4 Software` when going trough with this change

**Comment by Trenly** [comment]
> Nope, only Repo maintainers can approve this, and they don't..
What do you mean by “they don’t”?

> Also i believe you can change the `PackageName` to `CORSAIR iCUE 3 Software` and `CORSAIR iCUE 4 Software` when going trough with this change
Sounds good; I was just going with what was in the ARP entries

**Comment by OfficialEsco** [comment]
The maintainers/admins don't look at/approve PRs without backend issues..

When moving packages you might as well look at/fix the Metadata so it can't come back to cause issues :))

It causes less issues when it's under the same package, which is why the PackageName change here is a required change.

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
https://github.com/microsoft/winget-pkgs/pull/26935#event-5255429568

**Pull request closed without merging**
