### PR TITLE
Remove: ESET.Nod32 version 17.1.13.0

### PR DESCRIPTION
**Pull request by tobiasdegen**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/161974)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://download.eset.com/com/eset/apps/home/eav/windows/latest/eav_nt64.exe 
OK

(Automated message - build 911)

**Comment by stephengillie** [comment]
Hi @tobiasdegen,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 886.)

**Comment by tobiasdegen** [comment]
Hi,

a newer version is already merged. It's the same URL, but thue Hash changed.

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/pull/161808

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
