### PR TITLE
Macabacus.Macabacus version 9.5.4

### PR DESCRIPTION
**Pull request by khaffner**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/109106&drop=dogfoodAlpha

### CODE REVIEW

**Comment by khaffner** [comment]
Might need to add EULA=1 to the msi parameters

**Comment by ItzLevvie** [comment]
[Policy] Dependencies

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Review by mdanish-kh — CHANGES_REQUESTED** [review]
[Policy] Blocking-Issue

Does the package install silently without `EULA=1` switch? If not, then this package currently cannot be added to the winget repo.

See - 

- https://github.com/microsoft/winget-pkgs/issues/131328

**Comment by khaffner** [comment]
> [Policy] Blocking-Issue
> 
> Does the package install silently without `EULA=1` switch? If not, then this package currently cannot be added to the winget repo.
> 
> See -
> 
> * [P.S.A. Packages with explicit agreements in manifests removed #131328](https://github.com/microsoft/winget-pkgs/issues/131328)

Seems to me that [EULA=1 is required](https://help.macabacus.com/article/853-enterprise-deployment).

**Comment by denelon** [comment]
@khaffner the current schema is 1.9 this PR should be updated or closed.

**Pull request closed without merging**
