### PR TITLE
Add Microsoft To Do 2.19.31501.0

### LINKED ISSUE #1744: Package Request: Microsoft To Do
# Description of the new feature/enhancement

[Microsoft To Do](https://todo.microsoft.com/tasks/) currently is a great integrated solution for quick reminders that blend in well with the Windows 10 environment.

# Proposed technical implementation details (optional)

To Do is currently only available for installation via the Windows Store, which is not always a viable solution; adding this package would provide a simplified alternative.

### PR DESCRIPTION
**Pull request by SoftCreatR**
Auto Generated by softcreatr@winget.it on Fri, 12 Jun 2020 06:30:36 +0000

Resolves #1744

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/1807)

### CODE REVIEW

**Comment by KevinLaMS** [comment]
ToDo is a Microsoft app.  But the URL is not coming from Microsoft's server.  We want to avoid this due to the potential for spoofing.  Is this because it is a Store app?  If so, we are working on that feature.  Feel free to reach out to me to discuss further.  Kevinla@microsoft.com.

**Comment by SoftCreatR** [comment]
@kevinlams I had to use our Proxy because the Store API only returns temporary URLs.

> potential for spoofing

In theory, this should be avoidable using the provided SHA hash.

**Comment by KevinLaMS** [comment]
Thanks for clarifying.  I think this submission needs to get blocked on this feature.
https://github.com/microsoft/winget-cli/issues/117

**Comment by SoftCreatR** [comment]
That's fine. I'll stop the publishing process for this application. Less work for you, less work for me 😄

**Pull request closed without merging**
