### PR TITLE
add Idrix.VeraCrypt 1.24-Update7

### PR DESCRIPTION
**Pull request by smokeythemonkey**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23648)

### CODE REVIEW

**Review by ImJoakim — CHANGES_REQUESTED** [review]
> Manifest: The manifest file path must match PackageIdentifier and PackageVersion properties from manifest. actual '`manifests\i\Idrix\VeraCrypt\1.24-Update8`', expected '`manifests\i\Idrix\VeraCrypt\1.24-Update7`'

**Comment by ImJoakim** [comment]
I'm assuming that you're adding `1.24-Update7` and not `1.24-Update8` based on the install file.

You need to change the version folder so it matches the PackageVersion which is `1.24-Update7`:

`manifests/i/Idrix/VeraCrypt/1.24-Update8/` -> `manifests/i/Idrix/VeraCrypt/1.24-Update7/`

**Comment by ImJoakim** [comment]
It doesn't seem like this package has a silent/unattended install:

https://github.com/microsoft/winget-pkgs/issues/18101#issuecomment-864510427
https://github.com/veracrypt/VeraCrypt/issues/447

If you can find one, please change the InstallerSwitches. If not, it won't be possible to add this package.

**Comment by ImJoakim** [comment]
> * [x]  Have you tested your manifest locally with `winget install --manifest <path>`?

Also, when you're testing installation of the manifest locally, make sure that it installs without you having to click on anything / unattended.

**Comment by smokeythemonkey** [comment]
Guess it doesn't have an option to silently install :( will check with devs to see if its possible

**Pull request closed without merging**
