### PR TITLE
new version: dotpdnllc.paintdotnet 5.0.5

### PR DESCRIPTION
**Pull request by lychichem**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/107563)

### CODE REVIEW

**Comment by licon4812** [comment]
resolves #107679

**Review by mdanish-kh — CHANGES_REQUESTED** [review]
Please fix ReleaseDate to `ReleaseDate: 2023-05-20`

**Review by mdanish-kh — APPROVED** [review]

**Comment by lychichem** [comment]
> For me this still doesn't work. The URL for the ZIP is wrong. Here is my screen output
> 
> winget install --id dotPDNLLC.paintdotnet Gefunden paint.net [dotPDNLLC.paintdotnet] Version 5.0.5 Diese Anwendung wird von ihrem Besitzer an Sie lizenziert. Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern. Wird heruntergeladen https://github.com/paintdotnet/release/releases/download/v5.0.5/paint.net.5.0.5.install.arm64.zip Unerwarteter Fehler beim Ausführen des Befehls: Download request status is not success. 0x80190194 : Nicht gefunden (404).

Because paintdotnet just released 5.0.6

**Comment by juergenpf** [comment]
> > For me this still doesn't work. The URL for the ZIP is wrong. Here is my screen output
> > winget install --id dotPDNLLC.paintdotnet Gefunden paint.net [dotPDNLLC.paintdotnet] Version 5.0.5 Diese Anwendung wird von ihrem Besitzer an Sie lizenziert. Microsoft ist nicht verantwortlich und erteilt keine Lizenzen für Pakete von Drittanbietern. Wird heruntergeladen https://github.com/paintdotnet/release/releases/download/v5.0.5/paint.net.5.0.5.install.arm64.zip Unerwarteter Fehler beim Ausführen des Befehls: Download request status is not success. 0x80190194 : Nicht gefunden (404).
> 
> Because paintdotnet just released 5.0.6

Which also doesn't exist on github. The Assets mentioned on https://github.com/paintdotnet/release/releases/tag/v5.0.6 all have different URIs than the one referenced by the winget installer.

**Pull request merged**
