### PR TITLE
Dup - AntonPupkov.Aurora version 0.8.1

### PR DESCRIPTION
**Pull request by Masamune3210**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/27268)

### CODE REVIEW

**Comment by Masamune3210** [comment]
Only user input is accepting the EULA for the redist required if it is not already installed

**Comment by Masamune3210** [comment]
Only user input is accepting the EULA for the redist required if it is not already installed

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Not installing fully silent - I'm stuck here:
image

**Comment by Masamune3210** [comment]
Is there no way to get around dependencies? The only thing that shows to the user is that, and it doesn't show if it is already installed like it would be on most systems

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> Is there no way to get around dependencies? The only thing that shows to the user is that, and it doesn't show if it is already installed like it would be on most systems

No, as dependencies are not supported by Windows Package Manager yet.

This PR is also a duplicate of https://github.com/microsoft/winget-pkgs/pull/22900 so you can close it.

**Pull request closed without merging**
