### PR TITLE
New package: Microsoft.SQLServer.Compact version 4.0_SP1

### LINKED ISSUE #163711: [Package Request]:
### How can we help?

I would like help so I can submit the manifest.

### Please read and ensure the following

- [X] The installer meets the above requirements

### Please provide the following information

Download Page Url: https://www.microsoft.com/en-au/download/details.aspx?id=30709
Publisher: Microsoft Corporation
Package Name: Microsoft® SQL Server® Compact 4.0 SP1
Description: Microsoft SQL Server Compact 4.0 is a free, embedded database that software developers can use for building ASP.NET websites and Windows desktop applications. SQL Server Compact 4.0 has a small footprint and supports private deployment of its binaries within the application folder, easy application development in Visual Studio and WebMatrix, and seamless migration of schema and data to SQL Server.
Package Version:
Installer URL: https://download.microsoft.com/download/F/F/D/FFDF76E3-9E55-41DA-A750-1798B971936C/ENU/SSCERuntime_x64-ENU.exe

Resolves dependency issue in pull request https://github.com/microsoft/winget-pkgs/pull/163651 & https://github.com/microsoft/winget-pkgs/pull/163640

### PR DESCRIPTION
**Pull request by Dragon1573**
## Checklist for Pull Requests

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- Related #163711

## Manifests

- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/163798)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @,

Do you approve of these changes?

(Automated response - build 887.)

**Comment by Dragon1573** [comment]
> Is this a nested installer?

Maybe it is? I'm using _Komac_ and it inspect the installer file as a portable executable.

There's something wrong with my device, I can't launch _Windows Sandbox_ on it so I can't manually validate them.

`InstallerUrl` is provided by @amber-m-mvd in https://github.com/microsoft/winget-pkgs/issues/163711#issue-2417535498.

**Comment by y2k04** [comment]
Please refer to this comment: https://github.com/microsoft/winget-pkgs/issues/163711#issuecomment-2242063916

**Comment by amber-m-mvd** [comment]
@Dragon1573 would this work? (Just threw this together without the tool)
```
Created with komac v2.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Microsoft.SQLServer.Compact
PackageVersion: 4.0_SP1
ReleaseDate: 2020-04-22
Installers:
- Architecture: x64
  InstallerUrl: https://download.microsoft.com/download/F/F/D/FFDF76E3-9E55-41DA-A750-1798B971936C/ENU/SSCERuntime_x64-ENU.exe
  InstallerSha256: 443D149C7A1A3D5C26189BF727A55287341FAD620225FD7AED610BA1762286E4
  InstallerType: zip
  InstallModes:
  - interactive
  - silent
  - silentWithProgress
  UpgradeBehavior: install
  NestedInstallerType: msi
  NestedInstallerFiles:
  - RelativeFilePath: SSCERuntime_x64-ENU.msi
ManifestType: installer
ManifestVersion: 1.6.0
```

**Comment by Dragon1573** [comment]
```text
SSCERuntime_[x86|x64]-[LOC].exe   [<install options> [Display Options] [Logging Options <Log Filename>] [help Options]

1. Extraction Options
    /x[:<path>]     - Extracts the msi in the path specified 
2. Install Options
Following are the installation parameters that are supported 
    </package | /i> -  Installs or configures SQL Server Compact Runtime
    /a - Administrative install - Installs the  product on the network
    /uninstall      - Uninstalls the product
3. Display Options
    /quiet          - Quiet mode, no user interaction
    /passive        - Unattended mode (progress bar only)
    /q[n|b|r|f]     - Sets user interface level
    n - No UI
    b - Basic UI
    r - Reduced UI
    f - Full UI (default)
4. Help Options
    /help | /?      - Displays help information on the Console
5. Logging Options
    /l[i|w|e|a|r|u|c|m|o|p|v|x|+|!|*] <LogFile>
    i - Status messages
    w - Nonfatal warnings
    e - All error messages
    a - Start up of actions
    r - Action-specific records
    u - User requests
    c - Initial UI parameters
    m - Out-of-memory or fatal exit information
    o - Out-of-disk-space messages
    p - Terminal properties
    v - Verbose output
    x - Extra debugging information
    + - Append to existing log file
    ! - Flush each line to the log
    - Log all information, except for v and x options
    /log <LogFile>  - Equivalent of /l* <LogFile>
6. Repair Options
    /f[p|e|c|m|s|o|d|a|u|v]   : Repairs a product
    p - only if file is missing
    o - if file is missing or an older version is installed (default)
    e - if file is missing or an equal or older version is installed
    d - if file is missing or a different version is installed
    c - if file is missing or checksum does not match the calculated value
    a - forces all files to be reinstalled
    u - all required user-specific registry entries (default)
    m - all required computer-specific registry entries (default)
    s - all existing shortcuts (default)
    v - runs from source and recaches local package

Press ENTER to continue...
```

_Originally posted in `Help.txt` in `SSCERuntime_x64-ENU.exe`_

**Comment by Dragon1573** [comment]
image

1. Install `Microsoft.VCRedist.2015+.x64`.
2. Prepare offline `*.exe` of this package.
3. Try `& '.\Microsoft® SQL Server® Compact_4.0_SP1_X64_exe_en-US.exe' /i /passive /qb`.
4. Error occur.

**Comment by amber-m-mvd** [comment]
What about the MSI file that is contained inside the exe? Since it is a nested installer.

**Comment by amber-m-mvd** [comment]
Seems like it is related to .NET 3.5 not being installed.

https://answers.microsoft.com/en-us/windows/forum/all/unable-to-install-any-application-error/fb0ca806-ce16-486f-84fc-5c0d82102f5a

**Comment by Dragon1573** [comment]
Seems requires `Microsoft.VCRedist.2008.x64`? Worth a try.

**Comment by amber-m-mvd** [comment]
What about .NET 3.5?

**Comment by Dragon1573** [comment]
> What about .NET 3.5?

See https://github.com/microsoft/winget-pkgs/issues/157422#issuecomment-2171067571.

**.NET Framework 3.5** is a **Windows Feature**. Currently `winget.exe` doesn't support en/dis-able Windows Features.

**Comment by stephengillie** [comment]
Sorry, but the package manager has recently gained the ability to install Windows Features. This installs the .NET Framework 3.5:

```
Dependencies:
  WindowsFeatures:
    - netfx3 
Installers:
```

A list of Windows Feature names can be found with `Get-WindowsOptionalFeature -Online`.

**Comment by Dragon1573** [comment]
Windows Feature enabled, but still unable to install the package unattended. 😞

```text
01:51:44 D:\...\winget-pkgs  [issues/163711 ≡ +0 ~1 -0 !] 2ms pwsh> cat .\manifests\m\Microsoft\SQLServer\Compact\4.0_SP1\Microsoft.SQLServer.Compact.installer.yaml
# Created with komac v2.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Microsoft.SQLServer.Compact
PackageVersion: 4.0_SP1
InstallerType: exe
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2020-04-22
Dependencies:
  WindowsFeatures:
  - netfx3
InstallerSwitches:
  InstallLocation: /x:<INSTALLPATH>
  Interactive: /i
  Log: /log <LOGPATH>
  Silent: /i /quiet /qn
  SilentWithProgress: /i /passive /qb
Installers:
- Architecture: x64
  InstallerUrl: https://download.microsoft.com/download/F/F/D/FFDF76E3-9E55-41DA-A750-1798B971936C/ENU/SSCERuntime_x64-ENU.exe
  InstallerSha256: 443D149C7A1A3D5C26189BF727A55287341FAD620225FD7AED610BA1762286E4
ManifestType: installer
ManifestVersion: 1.6.0
01:51:52 D:\...\winget-pkgs  [issues/163711 ≡ +0 ~1 -0 !] 20ms pwsh> sudo winget install -m .\manifests\m\Microsoft\SQLServer\Compact\4.0_SP1\
已找到 Microsoft® SQL Server® Compact [Microsoft.SQLServer.Compact] 版本 4.0_SP1
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
此包需要以下依赖项：
  - Windows 功能
      netfx3
正在启用 [netfx3]...
已成功启用 Windows 功能依赖项
已成功验证安装程序哈希
正在启动程序包安装...
安装程序失败，退出代码为: 1639
```

**Comment by Dragon1573** [comment]
> [!NOTE]
>
> Close with reason: https://github.com/microsoft/winget-pkgs/labels/Blocking-Issue https://github.com/microsoft/winget-pkgs/labels/Area-External https://github.com/microsoft/winget-pkgs/labels/Interactive-Only-Installer

**Comment by stephengillie** [comment]
Error `1639` might mean `ERROR_INVALID_COMMAND_LINE` - Invalid command line argument. Suggestion is "Double-check the installer switches".

**Pull request closed without merging**
