### PR TITLE
New package: Nova_Max.XBatteryStatus version 1.2.1

### PR DESCRIPTION
**Pull request by tommaier123**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132230)

### CODE REVIEW

**Comment by tommaier123** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Hi @tommaier123,

This manifest removes Apps and Features entries that are present in previous PR versions. Should these entries be added to this version also?

(Automated response - build 509.)

**Comment by tommaier123** [comment]
Yes, only XBatteryStatus should be added, nothing should be removed

**Comment by stephengillie** [comment]
Hi @Trenly and @mdanish-kh,

What are your thoughts on the Apps and Features changes in this PR?

**Comment by Trenly** [comment]
> Hi @tommaier123,
> 
> This manifest removes Apps and Features entries that are present in previous PR versions. Should these entries be added to this version also?
> 
> (Automated response - build 509.)

I don't think there are any AppsAndFeaturesEntries in previous versions since there aren't any previous versions @stephengillie

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
Hi @tommaier123,

Sorry for the confusion in this PR.

**Comment by tommaier123** [comment]
No Problem :)

**Pull request merged**
