### PR TITLE
New version: Foxit.PhantomPDF 12.1.0.15250

### PR DESCRIPTION
**Pull request by degam-gh**

### CODE REVIEW

**Comment by degam-gh** [comment]
Can anybody check why this isn't working?

**Comment by denelon** [comment]
https://github.com/microsoft/winget-pkgs/issues/95543

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
While the main package installed and launched normally, some of the included EXEs require a `VCRedist` dependency: 
image

**Pull request merged**
