### PR TITLE
New package: Microsoft.UI.Xaml.2.8 version 2.8.5

### PR DESCRIPTION
**Pull request by Trenly**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

* Related to #111840

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/111849&drop=dogfoodAlpha

### CODE REVIEW

**Comment by Trenly** [comment]
Looks like the validation pipeline is too strict on Appx  packages, saying that Winget Manifest PackageVersion must match the version in the Appx Manifest, even though the true version is specified in AppsAndFeaturesEntries

**Comment by AmelBawa-msft** [comment]
@Trenly @denelon  Correct, today the validation does the following comparison:
Is the YAML `PackageVersion: 2.8.5` the same as the AppxManifest.xml `<Identity Name="Microsoft.UI.Xaml.2.8" ... Version="8.2306.22001.0" />`, which in this case it does not match.

@denelon, what should be the new behavior for this validation? Prioritizing `AppsAndFeaturesEntries.DisplayVersion`, checking if either of `PackageVersion` or `AppsAndFeaturesEntries.DisplayVersion` matches, or something else?

**Comment by denelon** [comment]
The more critical thing to match is the AppsAndFeaturesEntries.DisplayVersion if it's present, then we could allow the match to comply with our policy rather than requiring that the PackageVersion matching.

If the DisplayVersion is not present, then the PackageVersion must match.
If the DisplayVersion is present, then it must match, and the PackageVersion is not required to match.

**Review by mdanish-kh — APPROVED** [review]

**Comment by yao-msft** [comment]
This manifest will have winget upgrade related issues. Currently, AppsAndFeaturesEntries are for representing the ARP registry entries written by win32 apps. For msix, these entries are ignored and not used. We even have a validation that on individual installer level, if AppsAndFeaturesEntries exist with msix, a validation error will be returned.

If we do wish to let msix look at AppsAndFeaturesEntries, we need to go through the code and make sure no extra surprise would happen if we enable this new behavior. And for now I cannot think of a reason to enable this. Because msix always have a well defined version (no version mapping is actually needed). And we should implement the MarketingVersion (@trenly's proposal) if we want to allow showing a different version other than the appxmanifest version.

**Comment by yao-msft** [comment]
I'll create 2 follow up prs to make the manifest correct (aligned with current implementation)

**Comment by Trenly** [comment]
@yao-msft - You may want to also check the Microsoft Powershell, since I believe I recall someone mentioning it had the same issue

**Comment by yao-msft** [comment]
> @yao-msft - You may want to also check the Microsoft Powershell, since I believe I recall someone mentioning it had the same issue

I looked at the latest powershell manifest and preview manifest, they do not declare AppsAndFeaturesEntries. Are you referring to their package version not matching appxmanifest version?

**Comment by Trenly** [comment]
> Are you referring to their package version not matching appxmanifest version?

Yes

**Comment by mdanish-kh** [comment]
The concerning package is actually `Microsoft.PowerShell.Preview` and its case is a little bit different than this one. 

The issue is that the Preview manifest has InstallerTypes msi and msix where they don't have the same DisplayVersion value. Take the current latest manifest [7.4.0.4](https://github.com/microsoft/winget-pkgs/blob/master/manifests/m/Microsoft/PowerShell/Preview/7.4.0.4/Microsoft.PowerShell.Preview.installer.yaml) as an example. The MSI DisplayVersion is `7.4.0.4` while the version the MSIX uses is `7.4.4.0`. Previously, what we were doing was to use the MSIX version as the PackageVersion in the manifest and use `AppsAndFeaturesEntries` for the MSI installers. The problem with this approach is that the marketing version is actually the MSI version and we had users complaining that they were not being shown the correct version in winget upgrade / list output where the PackageVersion (msix version) was being shown. (https://github.com/microsoft/winget-pkgs/issues/99631). I looked at the manifest and then removed the AppsAndFeaturesEntries -> used MSI version as the PackageVersion / user-facing version -> tried to use ARP entries for msix where I was quickly met with the issue with `winget validate` not passing. So then I removed the ARP Entries as it didn't seem to mess with correlation after installing the package but then again the issue arose with the pipelines not allowing the PR to pass through the validation pipelines since they require the PackageVersion to match the version retrieved from the MSIX. Seeing all this, and having discussions with the PowerShell team in https://github.com/microsoft/winget-pkgs/issues/99631 and in https://github.com/microsoft/winget-pkgs/pull/99498, it seemed that we should have manual merges for these PRs as it's a temp scenario. The temporary scenario is due to the fact the pwsh team is working for making MSIs for ARM arch but until they start releasing them as MSI, they are using MSIX as a temporary solution for ARM (ref https://github.com/microsoft/winget-pkgs/issues/99631#issuecomment-1474716847)

**Comment by mdanish-kh** [comment]
@yao-msft What would you advise to do in this situation? If we were to use the MSIX version as the PackageVersion so that we don't need manual merges (and use AppsAndFeaturesEntries for MSI), we would have to go back and edit all previous manifests of PowerShell Preview as well to avoid the issue with version ranges and infinite upgrades for the user. And then again, the main problem would be that the user-facing version would not match the marketing version and imo it's more important that users feels they are getting the correct version from WinGet.

**Pull request merged**
