### PR TITLE
Remove version: MullvadVPN.MullvadVPN version 2024.1-beta1

### LINKED ISSUE #137814: [Package Issue]: MullvadVPN.MullvadVPN
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Last package of MullvadVPN.MullvadVPN is a beta version because of the pull request https://github.com/microsoft/winget-pkgs/pull/135226

Last stable version is the 2023.6

Sources:

https://mullvad.net/en/download/vpn/windows
https://github.com/mullvad/mullvadvpn-app/releases

### Steps to reproduce

"winget upgrade" :

Name                 Id                    Version  Available    Source
-----------------------------------------------------------------------
Mullvad VPN 2023.6.0 MullvadVPN.MullvadVPN 2023.6.0 2024.1-beta1 winget

### Actual behavior

winget is proposing a beta version

### Expected behavior

No beta

### Environment

```raw
Windows 11 x64
```

### Screenshots and Logs

_No response_

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/137820)

### CODE REVIEW

**Comment by Exorcism0666** [comment]
## For moderators

This account is automated by Github Actions and the source code was created by CoolPlayLin. If you have any questions about any pull request, don't hesitate to ping @Exorcism0666, I'll get a notification.
>[!important]
>Please carefully review these Pull Request before merging. If it is a Pull Request for removing incorrect content and the URLs are issue, free upon manual checking, please close this Pull Request directly. (It is best to inform Exorcism0666 of the closure.)

良い一日をお過ごしください！

**Comment by CoolPlayLin** [comment]
@Exorcism0666 Rerun please. This error is due to #133371

CC @stephengillie

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-04T14:24:11.2407862Z Processing manifest: manifests\m\MullvadVPN\MullvadVPN\2024.1-beta1
 2024-02-04T14:24:11.2423096Z -----------------------------------------------------
 2024-02-04T14:24:11.2430986Z Status: Started
 2024-02-04T14:24:11.2439554Z Manifest file is Deleted
 2024-02-04T14:24:11.4708201Z Status: Completed
 2024-02-04T14:24:11.4723314Z ##[error] Result: Failed
 2024-02-04T14:24:11.4756220Z ##[error] Sequence contains no elements
 2024-02-04T14:24:11.5335575Z ##[error]Manifest Validation Failed

(Automated response - build 695.)

**Comment by stephengillie** [comment]
> Sequence contains no elements

 - https://github.com/microsoft/winget-pkgs/issues/133371

(Automated response - build 695.)

**Review by KaranKad — APPROVED** [review]

**Pull request merged**
