### PR TITLE
Add AkelPad Portable 4.9.8

### PR DESCRIPTION
**Pull request by LukasNespor**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/winget-pkgs/pull/961)

### CODE REVIEW

**Comment by LukasNespor** [comment]
Ref #897

**Comment by LukasNespor** [comment]
Ref #897

**Comment by MarNicGit** [comment]
@LukasNespor I've noticed you're adding a lot of portable editions of applications. Wouldn't it be a better idea to append the package name with something like `Portable` to avoid future conflict with the default desktop versions of these applications?

**Comment by LukasNespor** [comment]
> @LukasNespor I've noticed you're adding a lot of portable editions of applications. Wouldn't it be a better idea to append the package name with something like `Portable` to avoid future conflict with the default desktop versions of these applications?
> 
> In this case the package name would be `AkelPad.AkelPadPortable`.

Good point. Closing this PR and creating new #1069 because I am an id*ot :) and removed my repo so I am not able to create new commit with change.

**Pull request closed without merging**
