### PR TITLE
Update: CozyCloud.CozyDrive version 3.28.1

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23725)

### CODE REVIEW

**Comment by quhxl** [comment]
WTF, I just finished the manifest one minute ago. Just saw this as the latest PR when I went to create my PR.

**Comment by OfficialEsco** [comment]
> WTF, I just finished the manifest one minute ago. Just saw this as the latest PR when I went to create my PR.

Huhu, just refreshed my RSS feed after 3 hours and noticed the update C:
Just setup every package with a GitHub release url to my RSS feed so gonna be first to spot the release now :o

**Comment by quhxl** [comment]
This is actually an extremely smart approach!

**Comment by OfficialEsco** [comment]
Very, unless the RSS reader can only hold 30% of the links and you notice it after you're done🤦‍♂️

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
