### PR TITLE
Add surface tools for IT -SurfaceUEFI Configurator for our commercial users

### PR DESCRIPTION
**Pull request by TAMSHUI**
Add surface tools for IT -SurfaceUEFI Configurator for our commercial users
 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/135071)

### CODE REVIEW

**Review by TAMSHUI — COMMENTED** [review]
FIX Manifest

**Review by TAMSHUI — COMMENTED** [review]
already fix it

**Comment by stephengillie** [comment]
Hi @TAMSHUI,

We had some unexpected work on our pipelines yesterday. Sorry for the impact.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 

(Automated response - build 597.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-01-17T19:27:15.8719251Z ##[error] One or more errors occurred. (Manifest: The filename must match the PackageIdentifier and ManifestType properties from the manifest. actual 'Microsoft.SurfaceUEFIConfigurator.YAML', expected 'Microsoft.SurfaceUEFI_Configurator.yaml'

(Automated response - build 598.)

**Comment by stephengillie** [comment]
Hi @TAMSHUI,

While the `PackageIdentifier` and file path have the underscore `_`: 

- `Microsoft.SurfaceUEFI_Configurator`
- `/Microsoft/SurfaceUEFI_Configurator/`

It's missing from the file names: 
- `Microsoft.SurfaceUEFIConfigurator.YAML`

These have to match. 

With your permission, I'd be happy to fix this for you.

**Comment by TAMSHUI** [comment]
@stephengillie of course! Thank you for your help!

**Comment by TAMSHUI** [comment]
@stephengillie I try it again but still has some problems and I have no idea, so I need your help😂

**Comment by stephengillie** [comment]
Sorry, independent of this, we've been performing unexpected work on our pipelines. 

- https://github.com/microsoft/winget-pkgs/issues/135118

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
