### PR TITLE
New Package: ShipDigital.PullWatch version 1.0.1

### PR DESCRIPTION
**Pull request by deblasis**
Signed-off-by: Alessandro De Blasis <alex@deblasis.net>Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.9 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.9.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/196181)

### CODE REVIEW

**Comment by deblasis** [comment]
@microsoft-github-policy-service agree

**Comment by deblasis** [comment]
Hi! Not sure what the problem is, the error message is quite confusing:

Installation Validation

[View raw log](https://dev.azure.com/shine-oss/8b78618a-7973-49d8-9174-4360829d979b/_apis/build/builds/32404/logs/54)


12/4/2024 11:53:13 AM

****************************************************************************************
Installation Verification
****************************************************************************************
Status: Started
============================================================================== 
Task         : Installation Validation
Description  : Invoke an Azure Function
Version      : 1.220.0
Author       : Microsoft Corporation
Help URL     : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/azure-function
============================================================================== 
POST ***?code=***&
Request body: {
  "operationId": "WinGetSvc-Validation-27-196181-20241204-1",
  "buildId": "32404",
  "planUrl": "[https://dev.azure.com/shine-oss/",](https://dev.azure.com/shine-oss/%22,)
  "hubName": "build",
  "projectId": "8b78618a-7973-49d8-9174-4360829d979b",
  "planId": "5de84000-8200-4b99-b3a1-afc7de1701f7",
  "jobId": "68997d86-8ece-5ae8-3ac5-ccdbfa458731",
  "timelineId": "5de84000-8200-4b99-b3a1-afc7de1701f7",
  "taskInstanceId": "b79910ce-dca5-5e27-ad7f-bd285eecb5a2",
  "authToken": ***
  "pullRequestNumber": "196181"
}
				Response Code: OK
				Response: 

12/4/2024 11:56:43 AM

****************************************************************************************
Installation Verification
****************************************************************************************
Status: Completed
Result: Result: Failed

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> No errors to post.

(Automated response - build 899.)

**Comment by deblasis** [comment]
Hi @stephengillie ! Do I have to do/change anything? Thanks!

**Comment by deblasis** [comment]
> Hello @deblasis,
> 
> The package manager bot determined there was an issue with installing the application correctly. Please check the application installs correctly. Once repaired, please push an update to your pull request.
> 
> Template: msftbot/validationError/installation/general

It installs locally using 

`winget install --manifest ./manifests/s/ShipDigital/PullWatch/1.0.1`

without any issue

**Review by Trenly — APPROVED** [review]

**Comment by stephengillie** [comment]
Verify:
image

**Pull request merged**
