### PR TITLE
New version: qBittorrent.qBittorrent version 4.3.7

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

image

@KaranKad would you look at that, called it 😁

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/23687)

### CODE REVIEW

**Comment by lychichem** [comment]
Cannot pass WD PUA scan...

**Comment by OfficialEsco** [comment]
```
8/6/2021 12:09:27 PM
Status: Completed
##[error] Installer https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-4.3.7/qbittorrent_4.3.7_setup.exe/download Scan information: 'Error information: BlockingDetectionFound'
##[error] Result: Failed

8/6/2021 12:09:34 PM
Status: Completed
##[error] Installer https://sourceforge.net/projects/qbittorrent/files/qbittorrent-win32/qbittorrent-4.3.7/qbittorrent_4.3.7_x64_setup.exe/download Scan information: 'Error information: BlockingDetectionFound'
##[error] Result: Failed
```

Trying again since the SmartScreen warning is gone and its not flagged as PUP from Microsoft on Virustotal anymore

**Comment by OfficialEsco** [comment]
boo

**Comment by OfficialEsco** [comment]
.

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
