### PR TITLE
Update Schema in PR Template

### PR DESCRIPTION
**Pull request by CoolPlayLin**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/116578&drop=dogfoodAlpha

### CODE REVIEW

**Comment by BrandonWanHuanSheng** [comment]
This one is most likely https://github.com/microsoft/winget-pkgs/labels/Author-Not-Authorized

**Comment by CoolPlayLin** [comment]
Call up admin -- @stephengillie

**Comment by BrandonWanHuanSheng** [comment]
@denelon

**Comment by Trenly** [comment]
@coolplaylin / @BrandonWanHuanSheng - Just an FYI that It's the weekend, so it's unlikely that either denelon or stephen will see this until Monday

**Comment by CoolPlayLin** [comment]
I am in UTC+8, I don't know their timezone😂@Trenly

**Comment by BrandonWanHuanSheng** [comment]
Why microsoft-github-policy-service did not commented?

**Comment by CoolPlayLin** [comment]
@BrandonWanHuanSheng It probably wingetbot hasn't added `Project-File`

**Comment by CoolPlayLin** [comment]
IMO, these issues including didn't add validation-metadata for automatically wavie PR was caused by validation update to support 1.5.0 manifest. It appears admin hasn't added such feature in this updating

**Review by denelon — APPROVED** [review]

**Comment by denelon** [comment]
We're mostly UTC-7 or UTC-8

**Pull request merged**
