### PR TITLE
New version: SomePythonThings.WingetUIStore version 2.1.0

### PR DESCRIPTION
**Pull request by marticliment**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/120608)

### CODE REVIEW

**Comment by marticliment** [comment]
same issue as always I suppose

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> Installation failed with exit code 1

**Comment by stephengillie** [comment]
> same issue as always I suppose

Hi @marticliment,

Yes, sorry. I'll report it to the internal team, so hopefully we'll have an update soon.

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
