### PR TITLE
Mariocube.AutoWADInjector version 3

### PR DESCRIPTION
**Pull request by upintheairsheep**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/103135)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
InstallationVerification-x86-Scope_Undefined-Locale_Undefined-ErrorScreenshot_20230422025751

**Comment by stephengillie** [comment]
> Automatic Validation ended with:
> > 2023-04-24 10:31:03.106 [CLI ] Starting: 'C:\Users\User\AppData\Local\Temp\WinGet\Mariocube.AutoWADInjector.3\extracted\Auto Injectuwad Injector v3.exe' with arguments ''

This package doesn't like the default install location, due to the dots `.` in the path name. I'm not sure how to fix this, as I don't believe it's possible to extract to a custom location.

**Comment by upintheairsheep** [comment]
> > Automatic Validation ended with:
> > > 2023-04-24 10:31:03.106 [CLI ] Starting: 'C:\Users\User\AppData\Local\Temp\WinGet\Mariocube.AutoWADInjector.3\extracted\Auto Injectuwad Injector v3.exe' with arguments ''
> 
> This package doesn't like the default install location, due to the dots `.` in the path name. I'm not sure how to fix this, as I don't believe it's possible to extract to a custom location.

Let’s make a net issue to get a folder name without any dots

**Comment by stephengillie** [comment]
Researching the [manifest specification](https://github.com/microsoft/winget-pkgs/blob/master/doc/manifest/schema/1.4.0/installer.md), this feature might already exist, possibly in `InstallLocation`. I'll test with a path similar to the default, but without dots.

**Comment by ItzLevvie** [comment]
[Policy] Blocking-Issue

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
Seems the package flags don't apply retroactively. 
[Policy] Reset Feedback

**Pull request closed without merging**
