### PR TITLE
New package: Google.OneVPN version 1.3.36.292

### PR DESCRIPTION
**Pull request by mezbauddin**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/116723&drop=dogfoodAlpha

### CODE REVIEW

**Comment by mezbauddin** [comment]
@microsoft-github-policy-service agree

**Comment by AsciiWolf** [comment]
Google, not Googel. ;-)

**Comment by mezbauddin** [comment]
@AsciiWolf I am so confused now what to do!

**Comment by mezbauddin** [comment]
https://github.com/microsoft/winget-pkgs/pull/116481 dosent seems to have correct version btw

**Comment by AsciiWolf** [comment]
I apologize, however I am not a Microsoft employee and my time is sadly limited. Just close this PR and suggest needed changes (version number etc.) as comments in the another one.

**Comment by AsciiWolf** [comment]
Anyway, it looks like that the second PR uses another (and probably more suitable) installer with different version number.

**Pull request closed without merging**
