### PR TITLE
New version: BlueStack.BlueStacks version 5.9.0.1062

### PR DESCRIPTION
**Pull request by TheDude53**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.1 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.1.0)?

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/68838)

### CODE REVIEW

**Comment by TheDude53** [comment]
The URLs seem to load fine for me. I wonder if the bot server has been blocked.

**Comment by TheDude53** [comment]
Is there a way to bypass the error?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
> Is there a way to bypass the error?

cc @TheDude53: You will have to remove it.

`support.bluestacks.com` is blocked by ZenDesk for Azure IPs.

**Review by ItzLevvie — DISMISSED** [review]

**Comment by TheDude53** [comment]
> You will have to remove it.

Fair enough. The links are removed now.

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
