### PR TITLE
New Version: qBittorrent.qBittorrent Version 4.4.0

### PR DESCRIPTION
**Pull request by ItsPizzaTime1501**
No idea whether or not this'll fail due to the scan like #34731 did but it's worth a shot as this is a new version.
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/40105)

### CODE REVIEW

**Comment by ItsPizzaTime1501** [comment]
the installer scan has been running for 12 and a half hours in pipelines, is that normal?

**Comment by OfficialEsco** [comment]
For any other installer, no, for qBittorrent, yes.. Microsoft Defender does for some reason not like qBittorrent.. I have tried to send a sample to Microsoft and it stays as Scanning until we cannot see the history anymore..

**Comment by ItsPizzaTime1501** [comment]
So should I just draft or close this PR until the issue is hopefully fixed eventually?

**Comment by OfficialEsco** [comment]
You can close it as it will not be fixed.. As you can see, sadly every version down to 4.3.6 is blocked because its flagged as PUP

**Pull request closed without merging**
