### PR TITLE
New package: NirSoft.ExtPassword version 1.01

### PR DESCRIPTION
**Pull request by ForeverFloating**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/167132)

### CODE REVIEW

**Comment by stephengillie** [comment]
> 8/12/2024 8:01:34 AM
Installer Verification Analysis Context Information: 
Installer https://www.nirsoft.net/utils/extpassword.zip
Scan request id: '6ed84507-79ed-4552-898f-d7e1620a454c'
Error information: BlockingDetectionFound

**Comment by ForeverFloating** [comment]
I'm getting an antivirus detection from Microsoft Defender when I try to download the ZIP file manually. Is that what is causing the `BlockingDetectionFound` error?

**Comment by stephengillie** [comment]
> I'm getting an antivirus detection from Microsoft Defender when I try to download the ZIP file manually. Is that what is causing the `BlockingDetectionFound` error?

This is very possible. I wish I had a way to check.

**Comment by ForeverFloating** [comment]
Closing this pull request for now because of the antivirus possibly flagging the ZIP file.

**Pull request closed without merging**
