### PR TITLE
Remove: Google.Chrome version 120.0.6099.268

### PR DESCRIPTION
**Pull request by ImJoakim**
﻿## Vanity URL - New version (121.0.6167.161) is available in repo

- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/138636)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise.msi 
Status Code: 200

(Automated message - build 763)

**Comment by stephengillie** [comment]
Hi @ImJoakim,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 763.)

**Comment by ImJoakim** [comment]
> Hi @ImJoakim,
> 
> This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)
> 
> (Automated response - build 763.)

@stephengillie The latest version is https://github.com/microsoft/winget-pkgs/tree/master/manifests/g/Google/Chrome/122.0.6261.39

**Review by ItzLevvie — APPROVED** [review]

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
