### PR TITLE
Update VCRedist Dependency

### PR DESCRIPTION
**Pull request by Trenly**
null

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/81838)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Comment by Trenly** [comment]
@denelon - Seems all of VMware.WorkstationPlayer is now having Binary-Validation-Error. What should we do here?

**Comment by Trenly** [comment]
cc @OfficialEsco @jedieaston

**Review by jedieaston — APPROVED** [review]

**Comment by ryfu-msft** [comment]
This needs further investigation, will follow up once the issue is resolved.

**Review by OfficialEsco — APPROVED** [review]

**Pull request merged**
