### PR TITLE
Janison.NAPLockeddownbrowser version 5.6.15

### PR DESCRIPTION
**Pull request by ps-dcs**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/133350)

### CODE REVIEW

**Comment by ps-dcs** [comment]
@microsoft-github-policy-service agree

**Comment by stephengillie** [comment]
Hi @ps-dcs,

Is this package available from another URL?

**Comment by ps-dcs** [comment]
> Hi @ps-dcs,
> 
> Is this package available from another URL?

@stephengillie, this is the official URL from the Australian Department of Education: [https://www.assessform.edu.au/naplan-online/locked-down-browser#-downloads-](https://www.assessform.edu.au/naplan-online/locked-down-browser#-downloads-)

It seems like the geo block the download outside of Australia, I have looked but it doesn't seem to be available from an alternate location.

I have submitted a support ticket to see if they can make an exception for the winget package.

**Comment by stephengillie** [comment]
Packages generally have to be available for download, by almost any number of users at the same time, from almost any number of terrestrial locations. Hosting with some type of blocking technology prevents many packages from being accepted.

**Pull request closed without merging**
