### PR TITLE
Create SpyShelter.yaml

### PR DESCRIPTION
**Pull request by JonMix**
Please add the SpyShelter winget pkg.

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/138467)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-09T00:13:01.0003878Z ##[error] One or more errors occurred. (Manifest: The filename must match the PackageIdentifier and ManifestType properties from the manifest. actual 'SpyShelter.yaml', expected 'SpyShelter.SpyShelter.locale.en-US.yaml') Manifest: The filename must match the PackageIdentifier and ManifestType properties from the manifest. actual 'SpyShelter.yaml', expected 'SpyShelter.SpyShelter.locale.en-US.yaml'

(Automated response - build 716.)

**Review by JonMix — COMMENTED** [review]
The filename should now match the PackageIdentifier and ManifestType properties from the manifest:  SpyShelter.SpyShelter.locale.en-US.yaml  
Thank you.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2024-02-09T02:10:07.9728272Z ##[error] Manifest Error: The multi file manifest is incomplete.A multi file manifest must contain at least version, installer and defaultLocale manifest. File: SpyShelter.SpyShelter.locale.en-US.yaml

(Automated response - build 726.)

**Comment by stephengillie** [comment]
Hi @JonMix,

This manifest is incomplete. If you'd like help building the manifest, please consider opening an [Issue](https://github.com/microsoft/winget-pkgs/issues), where community members who enjoy building manifests look to help others.

**Comment by JonMix** [comment]
@stephengillie 

Thank you.  I will try again carefully, and if I fail I will consider opening an issue for help.  Thank you for your patience.

**Comment by JonMix** [comment]
I will open a ticket as suggested, thank you.

**Pull request closed without merging**
