### PR TITLE
New package: coopdeluxe.sm64coopdx version 1.0.3

### PR DESCRIPTION
**Pull request by SomeStreamsandMaybePanels**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/173065)

### CODE REVIEW

**Comment by stephengillie** [comment]
Verify:
image
This window opens, then quickly closes. Does this package use OpenGL?
image

**Comment by SomeStreamsandMaybePanels** [comment]
Yes the package does use openGL

**Comment by SomeStreamsandMaybePanels** [comment]
Is there anything I need to change in regards to the program itself?

**Comment by Trenly** [comment]
@SomeStreamsandMaybePanels - Support for zipped binaries has now been added and is available in the pipelines. This will require you to update your submission to ManifestVersion: 1.9.0 and set ArchiveBinariesDependOnPath: true in the installer node. To keep things clean, this PR is being closed. Please submit a new PR for the latest version of this package. Thank you for your contributions!

**Pull request closed without merging**
