### PR TITLE
netease.idenityV

### PR DESCRIPTION
**Pull request by solomoncyj**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/50932)

### CODE REVIEW

**Comment by solomoncyj** [comment]
finally
@ItzLevvie

**Review by ItzLevvie — APPROVED** [review]

**Comment by solomoncyj** [comment]
>@solomoncyj,

One or more of the installer URLs doesn't appear valid.

This may happen for sites with policies prohibiting distribution or use by third parties.

This may happen for URLs pointing to domains that do not align with the publisher domain or package domain. If you could provide supporting evidence from the publisher that the URLs for the installer are correct, that would help us to validate and approve this PR.
how? cc @ItzLevvie @denelon can someone force-merge this branch for me?

**Comment by solomoncyj** [comment]
> @solomoncyj - I am looking into this PR, but I am not able to validate the source of Installer URL. Could you please help me pointing to publisher URL & where is the given installer URL coming from ?

https://idv.163.com/

**Review by ghost — APPROVED** [review]

**Pull request merged**
