### PR TITLE
Add: elvirbrk.notehighlight2016 v3.7

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

image

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/20929)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Comment by vedantmgoyal2009** [comment]
That was a duplicate of #20825. Moderator himself opened a duplicate PR. 😂

**Comment by OfficialEsco** [comment]
When going trough old folders i don't actually check for existing PR's because i expect them to be `Azure-Pipeline-Passed`, eitherway your Publisher and PackageName was wrong and it had less metadata so it dosn't matter as it would be more trouble to get it to repass Validation again

**Pull request merged**
