### PR TITLE
New version: aimotrens.impulsar 0.15.0

### PR DESCRIPTION
**Pull request by aimotrens**
Checklist for Pull Requests
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Is there a linked Issue?

Manifests
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/doc/Authoring.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the directory's name containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/164433)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\aimotrens.impulsar__DefaultSource\impulsar.exe returned exit code: 1
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\impulsar.exe returned exit code: 1

(Automated response - build 886.)

**Comment by aimotrens** [comment]
I will make a new version which corrects the exit code to 0, if no arguments are set. Can I change the manifest to 0.15.1 and push the changes to this PR or should I make a new PR and close this one?

**Comment by stephengillie** [comment]
Hi @aimotrens,

This is something of a known issue with our pipelines, and to mitigate, I usually approve any exit code below 1000. Feel free to make this modification to future versions, and I'll approve this PR. 

- Either route for updating the version number would be just fine. Making a new PR might be easier, especially if you're using manifest creation software. Because the file path needs to be updated with the new version, which might be non-trivial for users new to Git and other tools that we use.

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
- https://github.com/microsoft/winget-pkgs/issues/142854

**Pull request merged**
