### PR TITLE
FSN.TyperspeedSepia version 3.0.5

### PR DESCRIPTION
**Pull request by seedy60**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] Have you validated your manifest locally with `winget validate --manifest <path>`? 
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/19738)

### CODE REVIEW

**Comment by fireseed66** [comment]
If I can run the installer and execute the installed software just fine, how has the installer validation failed?

**Comment by denelon** [comment]
@fireseed66 it's the age old problem of "works on my machine". The validation is running in an isolated environment with minimal dependencies and very specific scope (user vs. machine) and architecture (x64, x86, etc.). There are many different reasons it might not pass validation, but run just fine on a different machine. I often get caught by dependencies on my local machine that aren't present in the testing environment to validate just those specific kinds of conditions. Of course there could always be a "bug" too.

**Comment by fireseed66** [comment]
Is there a way I can simply remove the manifest from here so it's no longer available on Winget, then start the whole manifest creation and submission process again?

**Comment by denelon** [comment]
Any users who want the package would loose access to it if there is no manifest. Are you wanting to manually create the manifest or use a tool? You could create it on a different branch and then attempt to merge it in.

**Comment by fireseed66** [comment]
I'll use the Winget Create tool. There's no option in this tool to remove the manifest, though. I'm not all that familiar with git, so...

**Pull request closed without merging**
