### PR TITLE
Remove version: Tableau.Public version 24.2.1060

### PR DESCRIPTION
**Pull request by Exorcism0666**
###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/182423)

### CODE REVIEW

**Comment by stephengillie** [comment]
URL: https://downloads.tableau.com/public/TableauPublicDesktop-64bit-2024-2-3.exe 
Response status code does not indicate success: 403 (Forbidden).

(Automated message - build 896)

**Comment by stephengillie** [comment]
Hi @Exorcism0666,

This manifest has the highest version number for this package. Is it available from another location? (This might be in error if the version is switching from semantic to string, or string to semantic.)

(Automated response - build 896.)

**Comment by stephengillie** [comment]
URL: https://downloads.tableau.com/public/TableauPublicDesktop-64bit-2024-2-3.exe 
Response status code does not indicate success: 403 (Forbidden).

(Automated message - build 896)

**Comment by stephengillie** [comment]
URL: https://downloads.tableau.com/public/TableauPublicDesktop-64bit-2024-2-3.exe 
Response status code does not indicate success: 403 (Forbidden).

(Automated message - build 896)

**Comment by SpecterShell** [comment]
@Exorcism0666 Could you close all the PRs related to Tableau?

**Review by stephengillie — APPROVED** [review]

**Comment by stephengillie** [comment]
> @Exorcism0666 Could you close all the PRs related to Tableau?

**Pull request closed without merging**
