### PR TITLE
update `Miller.Miller` to `6.10.0`

### PR DESCRIPTION
**Pull request by rursprung**
the manifest has been created using the following command:
```bash
wingetcreate update miller.miller -v 6.10.0 -u https://github.com/johnkerl/miller/releases/download/v6.10.0/miller-6.10.0-windows-386.zip https://github.com/johnkerl/miller/releases/download/v6.10.0/miller-6.10.0-windows-amd64.zip
```

the `ReleaseNotesUrl` has been manually added as `wingetcreate update` does not yet support release notes (see also
microsoft/winget-create#497).

- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/132018)

### CODE REVIEW

**Comment by rursprung** [comment]
@microsoft-github-policy-service agree

**Comment by rursprung** [comment]
@microsoft-github-policy-service agree

(didn't i just do that...?)

**Comment by rursprung** [comment]
as per @stephengillie's comment here the validation error is to be expected: https://github.com/microsoft/winget-pkgs/pull/123507#issuecomment-1776257043

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
