### PR TITLE
New package: Bilibili.CheeseStudio version 1.1.0

### PR DESCRIPTION
**Pull request by SpecterShell**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] This PR only modifies one (1) manifest
- [X] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.4 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.4.0)?

 ###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/110184&drop=dogfoodAlpha

### CODE REVIEW

**Comment by stephengillie** [comment]
This package didn't complete installing on a Windows 11 VM: 
image

Is it missing a dependency?

**Comment by SpecterShell** [comment]
This installer can download vcredist [from their server](http://boss.hdslb.com/cheese-studio/vendors/VC_redist.x64.exe) and install it automatically during installation. Maybe a network issue?

**Comment by stephengillie** [comment]
> This installer can download vcredist [from their server](http://boss.hdslb.com/cheese-studio/vendors/VC_redist.x64.exe) and install it automatically during installation. Maybe a temporary network issue?

Unfortunately, the issue persists. Is there an installer switch to skip? Maybe it can be specified as a dependency.

**Comment by SpecterShell** [comment]
It always downloads and installs the vcredist and there is no switch to skip it.
I think the problem is that the vcredist it downloaded is not the latest, which will exit immediately when a newer version is found.
image

**Review by ItzLevvie — APPROVED** [review]

**Pull request closed without merging**
