### PR TITLE
New version: Cube.CubePlatform version 3.6.8.1

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/58098)

### CODE REVIEW

**Review by OfficialEsco — COMMENTED** [review]
```
--> Installing the Manifest 3.6.8.1

Found 方块游戏平台 [Cube.CubePlatform] Version 3.6.8.1
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://download.cubejoy.com/app/3.6.8.1/CubeSetup_v3.6.8.1.exe
  ██████████████████████████████  49.7 MB / 49.7 MB
Installer hash does not match; this cannot be overridden when running as admin

--> Refreshing environment variables

--> Comparing ARP Entries
```

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
image

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
