### PR TITLE
New version: SomePythonThings.WingetUIStore version 2.0.2

### PR DESCRIPTION
**Pull request by marticliment**
###### Microsoft Reviewers: codeflow:open?pullrequest=https://github.com/microsoft/winget-pkgs/pull/112394&drop=dogfoodAlpha

### CODE REVIEW

**Comment by marticliment** [comment]
js the same issue as always

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> 2023-07-07 19:39:58.411 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\DODownloader.cpp(289)\WindowsPackageManager.dll!5870877F: (caller: 58708E35) Exception(1) tid(1e8c) 80072EE2  2023-07-07 19:39:59.130 [CORE] Download request failed. Returned status: 429 

Much like https://github.com/microsoft/winget-pkgs/pull/111297, Automatic Validation of this package is blocked by download throttling.

**Comment by stephengillie** [comment]
Automatic Validation ended with:
> ERROR: Signature Update failed with hr=80070652 CmdTool: Failed with hr = 0x80070652. Check C:\Users\VALIDA~1\AppData\Local\Temp\MpCmdRun.log for more information Standard error:  Signature Update Failed. Installation failed with exit code 1

**Comment by stephengillie** [comment]
The package installs normally in a Windows 10 VM, but WInGet still exists with exit code 1. It's confounding.

**Comment by stephengillie** [comment]
https://github.com/microsoft/winget-pkgs/issues/111634

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
