### PR TITLE
New version: SleuthKit.Autopsy version 4.19.2

### PR DESCRIPTION
**Pull request by OfficialEsco**
- [X] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [X] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [X] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [X] Have you tested your manifest locally with `winget install --manifest <path>`?
- [X] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/36638)

### CODE REVIEW

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Installs fine for me:
image

Maybe try closing and reopening the PR?

**Comment by Trenly** [comment]
Is this specifically an x86 package? It seems to install in the normal "Program Files" folder for me, so is this an issue where it might only validate as x64?

**Comment by OfficialEsco** [comment]
There are… 2 installers? x32 and x64, or do both install to Program Files?

**Comment by Trenly** [comment]
> There are… 2 installers? x32 and x64, or do both install to Program Files?

ahh, I missed that there were two. Guess I didn’t scroll far enough

**Comment by OfficialEsco** [comment]
*phew*

**Comment by OfficialEsco** [comment]
@ryfu-msft this one requires manual validation

**Pull request merged**
