### PR TITLE
New version: Google.Chrome.Beta version 108.0.5359.62 [FP-D]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | Google Chrome Beta | Google Chrome Beta    |
| Version     | 108.0.5359.62     | 108.0.5359.62 |
| Publisher   | Google LLC   | Google LLC      |
| ProductCode |           | {30C404D2-966A-3368-B874-915CD980AFB9}    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://github.com/vedantmgoyal2009/vedantmgoyal2009/tree/main/winget-pkgs-automation) in workflow run [4205](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/3568618654>)

### CODE REVIEW

**Review by mdanish-kh — CHANGES_REQUESTED** [review]
Looking at https://github.com/microsoft/winget-pkgs/pull/74226 and this PR, I guess this package could be divided into:
`OpenRA.OpenRA` and `OpenRA.OpenRA.Playtest`?

image

**Comment by stephengillie** [comment]
This version of the application isn't available for download from the provided URL anymore, nor is it available on the devleoper's GitHub releases page.

**Comment by mdanish-kh** [comment]
> This version of the application isn't available for download from the provided URL anymore, nor is it available on the devleoper's GitHub releases page.

Yep. Looks like the version got withdrawn by the publisher.

**Comment by russellbanks** [comment]
The automation has updated this pull request with Google Chrome Beta, so I will proceed with that.

**Review by russellbanks — APPROVED** [review]

**Pull request merged**
