### PR TITLE
New package: LocktimeSoftware.NetLimiter version 5.3.3.0

### PR DESCRIPTION
**Pull request by Masamune3210**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.5 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.5.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/120603)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:
image

**Comment by stephengillie** [comment]
Manual Validation ended with:
image

**Comment by stephengillie** [comment]
> Manual Validation ended with: image

This same box pops up when running the installer with the `/s` switch. The `/?` switch gives:
image

**Comment by stephengillie** [comment]
It seems `/exenoui` is the switch to use. However, that doesn't clear the license agreement:
image

**Comment by stephengillie** [comment]
Hi @Masamune3210,

Do you know of an installer switch to accept the license terms and conditions? I didn't see it in the installer's list of switches.

**Comment by Masamune3210** [comment]
> Hi @Masamune3210,
> 
> Do you know of an installer switch to accept the license terms and conditions? I didn't see it in the installer's list of switches.

Was waiting on the company to respond to a email, they just got back and said that it supports normal msi command line arguments and sent this along as well

https://netlimiter.com/docs/installation/command-line-options

**Comment by Masamune3210** [comment]
@stephengillie I will email them back and ask about if there is a switch to agree to the license through argument

**Comment by Masamune3210** [comment]
Accidentally deleted repo without moving pr, will recreate if/when I get a answer back from them @stephengillie

**Pull request closed without merging**
