### PR TITLE
New version: Bedrock-OSS.regolith version 1.2.0

### PR DESCRIPTION
**Pull request by Nusiq**
- [x] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [x] This PR only modifies one (1) manifest
- [x] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [x] Have you tested your manifest locally with `winget install --manifest <path>`?
- [x] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/141910)

### CODE REVIEW

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\LGUG2Z.komokana__DefaultSource\komokana.exe returned exit code: 2
> Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\komokana.exe returned exit code: 2

(Automated response - build 857.)

**Comment by Nusiq** [comment]
It looks like this error is somehow related to another package: https://github.com/microsoft/winget-pkgs/pull/141913

> Automatic Validation ended with:
> 
> > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Packages\LGUG2Z.komokana__DefaultSource\komokana.exe returned exit code: 2
> > Executable C:\Users\validator\AppData\Local\Microsoft\WinGet\Links\komokana.exe returned exit code: 2
> 
> (Automated response - build 857.)

**Comment by stephengillie** [comment]
Hi @Nusiq,

The package didn't pass a Defender or similar security scan. This might be a false positive and we can rescan tomorrow.

(Automated response - build 869.)

**Comment by stephengillie** [comment]
Automatic Validation ended with:

> Installation failed with exit code -1978335187
> 2024-03-03 05:49:53.098 [FAIL] Installer failed security check. Url: https://github.com/Bedrock-OSS/regolith/releases/download/1.2.0/regolith-1.2.0.msi Result: 0x80004005

(Automated response - build 869.)

**Review by stephengillie — APPROVED** [review]

**Pull request merged**
