### PR TITLE
New version: xpipe-io.xpipe version 8.4

### PR DESCRIPTION
**Pull request by crschnick**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] This PR only modifies one (1) manifest
- [ ] Have you [validated](https://github.com/microsoft/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`?
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.6 schema](https://github.com/microsoft/winget-pkgs/tree/master/doc/manifest/schema/1.6.0)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

---

 ###### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/microsoft/winget-pkgs/pull/144298)

### CODE REVIEW

**Comment by stephengillie** [comment]
Hi @crschnick,

> This PR's version number 8.4 has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 2.24.0, which has 3 parameters.

Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)

(Automated response - build 870)

**Comment by crschnick** [comment]
> Hi @crschnick,
> 
> > This PR's version number 8.4 has 2 parameters (sets of numbers between dots - major, minor, etc), which is less than the current manifest's version 2.24.0, which has 3 parameters.
> 
> Does this PR's version number **exactly** match the version reported in the Apps & features Settings page? (Feel free to attach a screenshot.)
> 
> (Automated response - build 870)

Where does your automation get that version from? I think it was the same issue last time. There is no xpipe 2.24.0

**Comment by stephengillie** [comment]
I was editing my reply but you've posted, so - 

This package doesn't work in `Find-WinGetPackage`, and my automation is built off of that, so the error gets perpetuated.  The version `2.24.0` is from the previous PR, due to variable reuse. (that should be easy to fix.) 

Sorry for causing concern.

**Review by stephengillie — APPROVED** [review]

**Comment by crschnick** [comment]
> I was editing my reply but you've posted, so -
> 
> This package doesn't work in `Find-WinGetPackage`, and my automation is built off of that, so the error gets perpetuated. The version `2.24.0` is from the previous PR, due to variable reuse. (that should be easy to fix.)
> 
> Sorry for causing concern.

Oh I see. So for the future, if I plan to have maybe 8.4.1 as a patch update in case any urgent bug needs to be fixed, I should always use the same amount of version numbers? I can just append a .0 if that would make it easier in general.

**Pull request merged**
