### PR TITLE
Mozilla.Firefox-msix version 94.0.0.0

### PR DESCRIPTION
**Pull request by oxygen-dioxide**
- [ ] Have you signed the [Contributor License Agreement](https://cla.opensource.microsoft.com/microsoft/winget-pkgs)?
- [ ] Have you checked that there aren't other open [pull requests](https://github.com/microsoft/winget-pkgs/pulls) for the same manifest update/change?
- [ ] Have you [validated](https://github.com/denelon/winget-pkgs/blob/master/AUTHORING_MANIFESTS.md#validation) your manifest locally with `winget validate --manifest <path>`? 
- [ ] Have you tested your manifest locally with `winget install --manifest <path>`?
- [ ] Does your manifest conform to the [1.0 schema](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md)?

Note: `<path>` is the name of the directory containing the manifest you're submitting.

-----

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/microsoft/winget-pkgs/pull/34087)

### CODE REVIEW

**Review by jedieaston — CHANGES_REQUESTED** [review]
Why can't this just be part of the `Mozilla.Firefox` manifest?

**Comment by oxygen-dioxide** [comment]
> Why can't this just be part of the `Mozilla.Firefox` manifest?

The version number format of this msix package is different from the `Mozilla.Firefox` manifest. For example, Mozilla.Firefox 94.0 is Mozilla.Firefox-msix 94.0.0.0

**Comment by jedieaston** [comment]
That's true, but due to Firefox's versioning scheme it shouldn't matter in practice (they only use to the second decimal point for any release), it shouldn't matter (94.0.0.0 would upgrade to 94.0.1 in winget's logic).

**Comment by OfficialEsco** [comment]
> 
> 
> That's true, but due to Firefox's versioning scheme it shouldn't matter in practice (they only use to the second decimal point for any release), it shouldn't matter (94.0.0.0 would upgrade to 94.0.1 in winget's logic).

WinGet also "ignore"/remove zero's, so if we flipped the numbers 94.0.0.0 would not show up as a upgrade for version 94.0 (Its just good practice to keep the 0's if the versions are the same)
This can also be corrected in Manifest Version 1.1 with ease since the msix dosn't break winget

**Comment by oxygen-dioxide** [comment]
#34147

**Comment by oxygen-dioxide** [comment]
> Why can't this just be part of the `Mozilla.Firefox` manifest?

Then how can the user choose which package to install between the exe package and the msix package?

**Review by ItzLevvie — CHANGES_REQUESTED** [review]
Added in https://github.com/microsoft/winget-pkgs/pull/34147?

**Pull request closed without merging**
