### PR TITLE
New version: OBSProject.OBSStudio version 28.0.1 [FP-D]

### PR DESCRIPTION
**Pull request by vedantmgoyal9**
### Result: Installation Successful
|             | Manifest                 | Add/Remove Programs                   |
| ----------- | ------------------------ | ------------------------------------- |
| Name        | OBS Studio | OBS Studio    |
| Version     | 28.0.1     | 28.0.1 |
| Publisher   | OBS Project   | OBS Project      |
| ProductCode |           | OBS Studio    |
#### Auto-updated by [vedantmgoyal2009/winget-pkgs-automation](https://bittu.eu.org/docs/wpa-intro) in workflow run [2826](<https://github.com/vedantmgoyal2009/vedantmgoyal2009/actions/runs/2983374175>)

### CODE REVIEW

**Review by ItzLevvie — DISMISSED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — APPROVED** [review]

**Review by ItzLevvie — DISMISSED** [review]

**Comment by Trenly** [comment]
Close with reason: Merge Conflict - General Repository Cleanup;

**Comment by vedantmgoyal2009** [comment]
@denelon please reopen this.

@trenly Atleast please take time to view the PRs... It adds a new version of RemNote.RemNote. MSFTbot didn't remove the lable.

**Comment by Trenly** [comment]
I'm sorry that I didn't see that. It gets *very* confusing when the branch is named Kiwix.Wikivoyage, and you pushed over the top of it. It really makes the entire PR history cluttered and confusing.

**Comment by denelon** [comment]
This still has the merge conflict.

**Comment by vedantmgoyal2009** [comment]
> nfusing when the branch is named Kiwi

That's because Trenly opened up a duplicate PR and got his merged, despite knowing there's already an open PR.

**Comment by Trenly** [comment]
> despite knowing there's already an open PR.

To be fair, this was still closed at the time I opened that one

**Review by ItzLevvie — APPROVED** [review]

**Pull request merged**
